### ISSUE TITLE
Does a native executable lambda work with localstack?

### ISSUE THREAD

**Issue by ababkin** [localstack/localstack#1000]
I've created a CF stack on localstack (run with `docker` option) that provisions a lambda that only has a thin node.js wrapper around a native executable (which was compiled to be made compatible with linux that runs on machines running lambdas on AWS). The lambdas work on the real AWS but do not react to events (I cannot see any evidence of them running) on localstack. Also of note is that I point to a zipped file on S3 rather than uploading the code directly (I don't know how well this works on localstack currently)
My question is "are native executable lambdas even supported in localstack"?
And if so, what would be my best way to debug this?
When I describe the stack on localstack, it shows these entries related to lambda: (notice the empty `PhysicalResourceId`)
``` 
        {
            "StackName": "qmuli-test",
            "StackId": "arn:aws:cloudformation:us-east-1:123456789:stack/qmuli-test/7ac28040-673e-4fe1-a94a-914adeb56e8c",
            "LogicalResourceId": "copyS3ObjectLambdaPermission",
            "PhysicalResourceId": "",
            "ResourceType": "AWS::Lambda::Permission",
            "Timestamp": "2010-07-27T22:27:28Z",
            "ResourceStatus": "CREATE_COMPLETE"
        },
        {
            "StackName": "qmuli-test",
            "StackId": "arn:aws:cloudformation:us-east-1:123456789:stack/qmuli-test/7ac28040-673e-4fe1-a94a-914adeb56e8c",
            "LogicalResourceId": "copyS3ObjectLambda",
            "PhysicalResourceId": "",
            "ResourceType": "AWS::Lambda::Function",
            "Timestamp": "2010-07-27T22:27:28Z",
            "ResourceStatus": "CREATE_COMPLETE"
        },
```

**Comment by whummer** [comment]
Thanks for reporting @ababkin . This should be supported in the meantime. We're using https://github.com/lambci/docker-lambda under the covers, which provides an almost identical environment to the real AWS Lambda service. Closing - please re-open if the problem persists.
