### ISSUE TITLE
bug: Cognito Hosted UI - Google Sign in does not work

### ISSUE THREAD

**Issue by lazylace37** [localstack/localstack#10007]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Through CDK, I have configured a Cognito User Pool and a User Pool Client, and set up the Google Identity Provider as described in the [docs](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_cognito.UserPoolIdentityProviderGoogle.html).  
I've also configured Amplify in a Javascript project to login and obtain a token, and I am able to access the Hosted UI and sign in with username and password.  
However, in the Hosted UI when I click the "Google (Google)" button to login with Google, I get redirected to a blank page: `https://localhost:4566/_aws/cognito-idp/undefined?response_type=code&redirect_uri=....&client_id=undefined&scope=undefined`.  

---

This is the link of the Hosted UI Amplify redirects me to:  
`https://localhost:4566/_aws/cognito-idp/login?redirect_uri=http%3A%2F%2Flocalhost%3A3000%2F&response_type=code&client_id=....&identity_provider=Google&scope=email%20profile%20openid&state=....&code_challenge=....&code_challenge_method=S256`

I analyzed a bit the Hosted UI sources in the browser and looking at the URL that gets constructed for the `idpLogin`
```javascript
const idp = IDP_PROVIDERS.filter(idp => idp.name === idpName)[0];
const details = idp.details || {};
const url = `${details.authorize_url}?response_type=code&redirect_uri=${CALLBACK_URL}&` +
  `client_id=${details.client_id}&scope=${details.authorize_scopes}`;
```
I noticed it tries to read `idp.details` which is empty:
```javascript
const IDP_PROVIDERS = [{"name": "Google", "type": "Google", "details": {}}];
```

---

Also, it is my understanding that it is possible to bypass the Hosted UI if the `identity_provider` parameter is provided in the URL, but I get redirected to the Hosted UI instead. [Source](https://docs.amplify.aws/react/build-a-backend/auth/add-social-provider/#:~:text=Also%2C%20note%20that,the%20below%20example.)

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

```typescript
this.userPool = new UserPool(this, "MyUserPool", {
  ....
});

const googleIdentityProvider = new UserPoolIdentityProviderGoogle(
  this,
  "Google",
  {
    clientId: "....",
    clientSecretValue: secretValue,
    userPool: this.userPool,
  },
);

this.uiAppClient = this.userPool.addClient("MyUiClient", {
  ....
  oAuth: {
    flows: {
      authorizationCodeGrant: true,
      implicitCodeGrant: true,
    },
    callbackUrls: ["http://localhost:3000"],
    logoutUrls: ["http://localhost:3000"],
  },
  supportedIdentityProviders: [UserPoolClientIdentityProvider.GOOGLE],
});

```

### Environment

```markdown
- OS:Ubuntu 23.04
- LocalStack:latest
```

**Comment by umotif-scotton** [comment]
I'm also encountering the same issue when trying to log in with a SAML IDP.
