### ISSUE TITLE
bug:  TLS (SSL) negotiation failed while inserting record in dynamodb

### ISSUE THREAD

**Issue by metojava** [localstack/localstack#10010]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello

I was trying apigw-lambda-snapstart-terraform project , from following repository:
https://github.com/aws-samples/serverless-patterns

tried with latest localstack-pro with increased lambda timeout config 
it is docker-compose.yml that is officially published on localstack website 

version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack-pro  # required for Pro
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
      - "127.0.0.1:443:443"              # LocalStack HTTPS Gateway (Pro)
    environment:
      - LOCALSTACK_AUTH_TOKEN=xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      - DEBUG=1
      - PERSISTENCE=${PERSISTENCE:-0}
      - LAMBDA_RUNTIME_ENVIRONMENT_TIMEOUT=300
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

--

after building and running terraform , tflocal actually, used Curl command from git shell:

curl -X POST -H 'Content-Type: application/json' -d '{ "stockId": "UNICORN_STOCK" , "quantity": 2 }' http://localhost:4566/restapis/9h6loyty37/prod/_user_request_/transactions

got error:

software.amazon.awssdk.crt.http.HttpException: TLS (SSL) negotiation failed

same project...  on Ubuntu 22 gave error: Noneobject has no attribute 'function_arn'

anyway provided all stack trace on windows execution  for reference 
/linux one is missing , sorry . saved from linux stacktrace but it was not saved really/

....

[UnicornStockBrokerFunction-eeee8e27-e78c-40c1-ab41-977c673dcace] [main] INFO org.springframework.cloud.function.adapter.aws.AWSLambdaUtils - Received: {"path": "/transactions", "headers": {"Host": "localhost:4566", "User-Agent": "curl/7.88.1", "accept": "*/*", "Content-Type": "application/json", "Content-Length": "46", "X-Forwarded-For": "172.20.0.1, localhost:4566", "x-localstack-edge": "http://localhost:4566"}, "multiValueHeaders": {"Host": ["localhost:4566"], "User-Agent": ["curl/7.88.1"], "accept": ["*/*"], "Content-Type": ["application/json"], "Content-Length": ["46"], "X-Forwarded-For": ["172.20.0.1, localhost:4566"], "x-localstack-edge": ["http://localhost:4566"]}, "body": "{ \"stockId\": \"UNICORN_STOCK\" , \"quantity\": 2 }", "isBase64Encoded": false, "httpMethod": "POST", "queryStringParameters": null, "multiValueQueryStringParameters": null, "pathParameters": {}, "resource": "/transactions", "requestContext": {"accountId": "000000000000", "apiId": "9h6loyty37", "resourcePath": "/transactions", "domainPrefix": "localhost", "domainName": "localhost", "resourceId": "iv2tu6b2fp", "requestId": "68296395-98dc-4bcc-ab7c-55c180cf0c7e", "identity": {"accountId": "000000000000", "sourceIp": "172.20.0.1", "userAgent": "curl/7.88.1"}, "httpMethod": "POST", "protocol": "HTTP/1.1", "requestTime": "07/Jan/2024:21:14:43 +0000", "requestTimeEpoch": 1704662083443, "authorizer": {}, "path": "/prod/transactions", "stage": "prod"}, "stageVariables": {}}
localstack-main  | 2024-01-07T21:18:15.904 DEBUG --- [   asgi_gw_1] l.s.l.i.version_manager    : [UnicornStockBrokerFunction-eeee8e27-e78c-40c1-ab41-977c673dcace] [main] ERROR com.unicorn.broker.data.TransactionRepository - Error while writing transaction to DynamoDB
localstack-main  | 2024-01-07T21:18:15.904 DEBUG --- [   asgi_gw_1] l.s.l.i.version_manager    : [UnicornStockBrokerFunction-eeee8e27-e78c-40c1-ab41-977c673dcace] java.util.concurrent.ExecutionException: software.amazon.awssdk.core.exception.SdkClientException: Unable to execute HTTP request: An exception occurred when acquiring connection
localstack-main  | 2024-01-07T21:18:15.904 DEBUG --- [   asgi_gw_1] l.s.l.i.version_manager    : [UnicornStockBrokerFunction-eeee8e27-e78c-40c1-ab41-977c673dcace]  at java.base/java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
localstack-main  | 2024-01-07T21:18:15.905 DEBUG --- [   asgi_gw_1] l.s.l.i.version_manager    : [UnicornStockBrokerFunction-eeee8e27-e78c-40c1-ab41-977c673dcace]  at java.base/java.util.concurrent.CompletableFuture.get(Unknown Source)
localstack-main  | 2024-01-07T21:18:15.906 DEBUG --- [   asgi_gw_1] l.s.l.i.version_manager    : [UnicornStockBrokerFunction-eeee8e27-e78c-40c1-ab41-977c673dcace]  at com.unicorn.broker.data.TransactionRepository.writeTransaction(TransactionRepository.java:35)
localstack-main  | 2024-01-07T21:18:15.909 DEBUG --- [   asgi_gw_1] l.s.l.i.version_manager    : [UnicornStockBrokerFunction-eeee8e27-e78c-40c1-ab41-977c673dcace]  at com.unicorn.broker.core.TransactionService.writeTransaction(TransactionService.java:29)
localstack-main  | 2024-01-07T21:18:15.909 DEBUG --- [   asgi_gw_1] l.s.l.i.version_manager    : [UnicornStockBrokerFunction-eeee8e27-e78c-40c1-ab41-977c673dcace]  at com.unicorn.broker.core.UnicornStockBrokerHandler.apply(UnicornStockBrokerHandler.java:24)
localstack-main  | 2024-01-07T21:18:15.910 DEBUG --- [   asgi_gw_1] l.s.l.i.version_manager    : [UnicornStockBrokerFunction-eeee8e27-e78c-40c1-ab41-977c673dcace]  at com.unicorn.broker.core.UnicornStockBrokerHandler.apply(UnicornStockBrokerHandler.java:9)
localstack-main  | 2024-01-07T21:18:15.910 DEBUG --- [   asgi_gw_1] l.s.l.i.version_manager    : [UnicornStockBrokerFunction-eeee8e27-e78c-40c1-ab41-977c673dcace]  at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.invokeFunctionAndEnrichResultIfNecessary(SimpleFunctionRegistry.java:929)
localstack-main  | 2024-01-07T21:18:15.910 DEBUG --- [   asgi_gw_1] l.s.l.i.version_manager    : [UnicornStockBrokerFunction-eeee8e27-e78c-40c1-ab41-977c673dcace]  at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.invokeFunction(SimpleFunctionRegistry.java:885)
localstack-main  | 2024-01-07T21:18:15.911 DEBUG --- [   asgi_gw_1] l.s.l.i.version_manager    : [UnicornStockBrokerFunction-eeee8e27-e78c-40c1-ab41-977c673dcace]  at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.doApply(SimpleFunctionRegistry.java:746)
localstack-main  | 2024-01-07T21:18:15.911 DEBUG --- [   asgi_gw_1] l.s.l.i.version_manager    : [UnicornStockBrokerFunction-eeee8e27-e78c-40c1-ab41-977c673dcace]  at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.apply(SimpleFunctionRegistry.java:589)
localstack-main  | 2024-01-07T21:18:15.913 DEBUG --- [   asgi_gw_1] l.s.l.i.version_manager    : [UnicornStockBrokerFunction-eeee8e27-e78c-40c1-ab41-977c673dcace]  at org.springframework.cloud.function.adapter.aws.FunctionInvoker.handleRequest(FunctionInvoker.java:92)
localstack-main  | 2024-01-07T21:18:15.914 DEBUG --- [   asgi_gw_1] l.s.l.i.version_manager    : [UnicornStockBrokerFunction-eeee8e27-e78c-40c1-ab41-977c673dcace]  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
localstack-main  | 2024-01-07T21:18:15.914 DEBUG --- [   asgi_gw_1] l.s.l.i.version_manager    : [UnicornStockBrokerFunction-eeee8e27-e78c-40c1-ab41-977c673dcace]  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
localstack-main  | 2024-01-07T21:18:15.914 DEBUG --- [   asgi_gw_1] l.s.l.i.version_manager    : [UnicornStockBrokerFunction-eeee8e27-e78c-40c1-ab41-977c673dcace]  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
localstack-main  | 2024-01-07T21:18:15.914 DEBUG --- [   asgi_gw_1] l.s.l.i.version_manager    : [UnicornStockBrokerFunction-eeee8e27-e78c-40c1-ab41-977c673dcace]  at java.base/java.lang.reflect.Method.invoke(Unknown Source)
localstack-main  | 2024-01-07T21:18:15.914 DEBUG --- [   asgi_gw_1] l.s.l.i.version_manager    : [UnicornStockBrokerFunction-eeee8e27-e78c-40c1-ab41-977c673dcace]  at lambdainternal.EventHandlerLoader$StreamMethodRequestHandler.handleRequest(EventHandlerLoader.java:383)
localstack-main  | 2024-01-07T21:18:15.914 DEBUG --- [   asgi_gw_1] l.s.l.i.version_manager    : [UnicornStockBrokerFunction-eeee8e27-e78c-40c1-ab41-977c673dcace]  at lambdainternal.EventHandlerLoader$2.call(EventHandlerLoader.java:925)
localstack-main  | 2024-01-07T21:18:15.914 DEBUG --- [   asgi_gw_1] l.s.l.i.version_manager    : [UnicornStockBrokerFunction-eeee8e27-e78c-40c1-ab41-977c673dcace]  at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:268)
localstack-main  | 2024-01-07T21:18:15.915 DEBUG --- [   asgi_gw_1] l.s.l.i.version_manager    : [UnicornStockBrokerFunction-eeee8e27-e78c-40c1-ab41-977c673dcace]  at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:207)
localstack-main  | 2024-01-07T21:18:15.915 DEBUG --- [   asgi_gw_1] l.s.l.i.version_manager    : [UnicornStockBrokerFunction-eeee8e27-e78c-40c1-ab41-977c673dcace]  at lambdainternal.AWSLambda.main(AWSLambda.java:196)
localstack-main  | 2024-01-07T21:18:15.915 DEBUG --- [   asgi_gw_1] l.s.l.i.version_manager    : [UnicornStockBrokerFunction-eeee8e27-e78c-40c1-ab41-977c673dcace] Caused by: software.amazon.awssdk.core.exception.SdkClientException: Unable to execute HTTP request: An exception occurred when acquiring connection
localstack-main  | 2024-01-07T21:18:15.915 DEBUG --- [   asgi_gw_1] l.s.l.i.version_manager    : [UnicornStockBrokerFunction-eeee8e27-e78c-40c1-ab41-977c673dcace]  at software.amazon.awssdk.core.exception.SdkClientException$BuilderImpl.build(SdkClientException.java:102)
localstack-main  | 2024-01-07T21:18:15.915 DEBUG --- [   asgi_gw_1] l.s.l.i.version_manager    : [UnicornStockBrokerFunction-eeee8e27-e78c-40c1-ab41-977c673dcace]  at software.amazon.awssdk.core.exception.SdkClientException.create(SdkClientException.java:47)
localstack-main  | 2024-01-07T21:18:15.915 DEBUG --- [   asgi_gw_1] l.s.l.i.version_manager    : [UnicornStockBrokerFunction-eeee8e27-e78c-40c1-ab41-977c673dcace]  at software.amazon.awssdk.core.internal.http.pipeline.stages.utils.RetryableStageHelper.setLastException(RetryableStageHelper.java:211)
localstack-main  | 2024-01-07T21:18:15.919 DEBUG --- [   asgi_gw_1] l.s.l.i.version_manager    : [UnicornStockBrokerFunction-eeee8e27-e78c-40c1-ab41-977c673dcace]  at software.amazon.awssdk.core.internal.http.pipeline.stages.utils.RetryableStageHelper.setLastException(RetryableStageHelper.java:207)
localstack-main  | 2024-01-07T21:18:15.920 DEBUG --- [   asgi_gw_1] l.s.l.i.version_manager    : [UnicornStockBrokerFunction-eeee8e27-e78c-40c1-ab41-977c673dcace]  at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryingExecutor.maybeRetryExecute(AsyncRetryableStage.java:183)
localstack-main  | 2024-01-07T21:18:15.920 DEBUG --- [   asgi_gw_1] l.s.l.i.version_manager    : [UnicornStockBrokerFunction-eeee8e27-e78c-40c1-ab41-977c673dcace]  at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryingExecutor.lambda$attemptExecute$1(AsyncRetryableStage.java:160)
localstack-main  | 2024-01-07T21:18:15.920 DEBUG --- [   asgi_gw_1] l.s.l.i.version_manager    : [UnicornStockBrokerFunction-eeee8e27-e78c-40c1-ab41-977c673dcace]  at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source)
localstack-main  | 2024-01-07T21:18:15.921 DEBUG --- [   asgi_gw_1] l.s.l.i.version_manager    : [UnicornStockBrokerFunction-eeee8e27-e78c-40c1-ab41-977c673dcace]  at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source)
localstack-main  | 2024-01-07T21:18:15.932 DEBUG --- [   asgi_gw_1] l.s.l.i.version_manager    : [UnicornStockBrokerFunction-eeee8e27-e78c-40c1-ab41-977c673dcace]  at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
localstack-main  | 2024-01-07T21:18:15.938 DEBUG --- [   asgi_gw_1] l.s.l.i.version_manager    : [UnicornStockBrokerFunction-eeee8e27-e78c-40c1-ab41-977c673dcace]  at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
localstack-main  | 2024-01-07T21:18:15.941 DEBUG --- [   asgi_gw_1] l.s.l.i.version_manager    : [UnicornStockBrokerFunction-eeee8e27-e78c-40c1-ab41-977c673dcace]  at software.amazon.awssdk.utils.CompletableFutureUtils.lambda$forwardExceptionTo$0(CompletableFutureUtils.java:76)
localstack-main  | 2024-01-07T21:18:15.941 DEBUG --- [   asgi_gw_1] l.s.l.i.version_manager    : [UnicornStockBrokerFunction-eeee8e27-e78c-40c1-ab41-977c673dcace]  at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source)
localstack-main  | 2024-01-07T21:18:15.941 DEBUG --- [   asgi_gw_1] l.s.l.i.version_manager    : [UnicornStockBrokerFunction-eeee8e27-e78c-40c1-ab41-977c673dcace]  at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source)
localstack-main  | 2024-01-07T21:18:15.942 DEBUG --- [   asgi_gw_1] l.s.l.i.version_manager    : [UnicornStockBrokerFunction-eeee8e27-e78c-40c1-ab41-977c673dcace]  at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
localstack-main  | 2024-01-07T21:18:15.942 DEBUG --- [   asgi_gw_1] l.s.l.i.version_manager    : [UnicornStockBrokerFunction-eeee8e27-e78c-40c1-ab41-977c673dcace]  at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
localstack-main  | 2024-01-07T21:18:15.943 DEBUG --- [   asgi_gw_1] l.s.l.i.version_manager    : [UnicornStockBrokerFunction-eeee8e27-e78c-40c1-ab41-977c673dcace]  at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage.lambda$null$0(MakeAsyncHttpRequestStage.java:103)
localstack-main  | 2024-01-07T21:18:15.946 DEBUG --- [   asgi_gw_1] l.s.l.i.version_manager    : [UnicornStockBrokerFunction-eeee8e27-e78c-40c1-ab41-977c673dcace]  at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source)
localstack-main  | 2024-01-07T21:18:15.946 DEBUG --- [   asgi_gw_1] l.s.l.i.version_manager    : [UnicornStockBrokerFunction-eeee8e27-e78c-40c1-ab41-977c673dcace]  at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source)
localstack-main  | 2024-01-07T21:18:15.946 DEBUG --- [   asgi_gw_1] l.s.l.i.version_manager    : [UnicornStockBrokerFunction-eeee8e27-e78c-40c1-ab41-977c673dcace]  at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
localstack-main  | 2024-01-07T21:18:15.946 DEBUG --- [   asgi_gw_1] l.s.l.i.version_manager    : [UnicornStockBrokerFunction-eeee8e27-e78c-40c1-ab41-977c673dcace]  at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
localstack-main  | 2024-01-07T21:18:15.947 DEBUG --- [   asgi_gw_1] l.s.l.i.version_manager    : [UnicornStockBrokerFunction-eeee8e27-e78c-40c1-ab41-977c673dcace]  at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage.lambda$executeHttpRequest$3(MakeAsyncHttpRequestStage.java:165)
localstack-main  | 2024-01-07T21:18:15.947 DEBUG --- [   asgi_gw_1] l.s.l.i.version_manager    : [UnicornStockBrokerFunction-eeee8e27-e78c-40c1-ab41-977c673dcace]  at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source)
localstack-main  | 2024-01-07T21:18:15.947 DEBUG --- [   asgi_gw_1] l.s.l.i.version_manager    : [UnicornStockBrokerFunction-eeee8e27-e78c-40c1-ab41-977c673dcace]  at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source)
localstack-main  | 2024-01-07T21:18:15.947 DEBUG --- [   asgi_gw_1] l.s.l.i.version_manager    : [UnicornStockBrokerFunction-eeee8e27-e78c-40c1-ab41-977c673dcace]  at java.base/java.util.concurrent.CompletableFuture$Completion.run(Unknown Source)
localstack-main  | 2024-01-07T21:18:15.947 DEBUG --- [   asgi_gw_1] l.s.l.i.version_manager    : [UnicornStockBrokerFunction-eeee8e27-e78c-40c1-ab41-977c673dcace]  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
localstack-main  | 2024-01-07T21:18:15.948 DEBUG --- [   asgi_gw_1] l.s.l.i.version_manager    : [UnicornStockBrokerFunction-eeee8e27-e78c-40c1-ab41-977c673dcace]  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
localstack-main  | 2024-01-07T21:18:15.949 DEBUG --- [   asgi_gw_1] l.s.l.i.version_manager    : [UnicornStockBrokerFunction-eeee8e27-e78c-40c1-ab41-977c673dcace]  at java.base/java.lang.Thread.run(Unknown Source)
localstack-main  | 2024-01-07T21:18:15.949 DEBUG --- [   asgi_gw_1] l.s.l.i.version_manager    : [UnicornStockBrokerFunction-eeee8e27-e78c-40c1-ab41-977c673dcace] Caused by: java.io.IOException: An exception occurred when acquiring connection
localstack-main  | 2024-01-07T21:18:15.950 DEBUG --- [   asgi_gw_1] l.s.l.i.version_manager    : [UnicornStockBrokerFunction-eeee8e27-e78c-40c1-ab41-977c673dcace]  at software.amazon.awssdk.http.crt.internal.CrtRequestExecutor.lambda$execute$2(CrtRequestExecutor.java:53)
localstack-main  | 2024-01-07T21:18:15.952 DEBUG --- [   asgi_gw_1] l.s.l.i.version_manager    : [UnicornStockBrokerFunction-eeee8e27-e78c-40c1-ab41-977c673dcace]  at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source)
localstack-main  | 2024-01-07T21:18:15.953 DEBUG --- [   asgi_gw_1] l.s.l.i.version_manager    : [UnicornStockBrokerFunction-eeee8e27-e78c-40c1-ab41-977c673dcace]  at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source)
localstack-main  | 2024-01-07T21:18:15.953 DEBUG --- [   asgi_gw_1] l.s.l.i.version_manager    : [UnicornStockBrokerFunction-eeee8e27-e78c-40c1-ab41-977c673dcace]  at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
localstack-main  | 2024-01-07T21:18:15.953 DEBUG --- [   asgi_gw_1] l.s.l.i.version_manager    : [UnicornStockBrokerFunction-eeee8e27-e78c-40c1-ab41-977c673dcace]  at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
localstack-main  | 2024-01-07T21:18:15.953 DEBUG --- [   asgi_gw_1] l.s.l.i.version_manager    : [UnicornStockBrokerFunction-eeee8e27-e78c-40c1-ab41-977c673dcace]  at software.amazon.awssdk.crt.http.HttpClientConnection.onConnectionAcquired(HttpClientConnection.java:112)
localstack-main  | 2024-01-07T21:18:15.953 DEBUG --- [   asgi_gw_1] l.s.l.i.version_manager    : [UnicornStockBrokerFunction-eeee8e27-e78c-40c1-ab41-977c673dcace] Caused by: software.amazon.awssdk.crt.http.HttpException: TLS (SSL) negotiation failed
localstack-main  | 2024-01-07T21:18:15.953 DEBUG --- [   asgi_gw_1] l.s.l.i.version_manager    : [UnicornStockBrokerFunction-eeee8e27-e78c-40c1-ab41-977c673dcace]  ... 1 more
localstack-main  | 2024-01-07T21:18:15.953 DEBUG --- [   asgi_gw_1] l.s.l.i.version_manager    : [UnicornStockBrokerFunction-eeee8e27-e78c-40c1-ab41-977c673dcace] END RequestId: eeee8e27-e78c-40c1-ab41-977c673dcace
localstack-main  | 2024-01-07T21:18:15.953 DEBUG --- [   asgi_gw_1] l.s.l.i.version_manager    : [UnicornStockBrokerFunction-eeee8e27-e78c-40c1-ab41-977c673dcace] REPORT RequestId: eeee8e27-e78c-40c1-ab41-977c673dcace   Duration: 180443.39 ms  Billed Duration: 180444 ms      Memory Size: 2048 MBMax Memory Used: 2048 MB
localstack-main  | 2024-01-07T21:18:15.953 DEBUG --- [   asgi_gw_1] l.s.lambda_.provider       : Lambda invocation duration: 212477.24ms
localstack-main  | 2024-01-07T21:18:15.985 DEBUG --- [-functhread6] localstack.http.asgi       : Error while writing responses: Connection closed (client_info: 127.0.0.1:40464)
localstack-main  | 2024-01-07T21:18:18.099  INFO --- [   asgi_gw_4] localstack.utils.bootstrap : Execution of "_load_service_plugin" took 2111.63ms
localstack-main  | 2024-01-07T21:18:18.099  INFO --- [   asgi_gw_4] localstack.utils.bootstrap : Execution of "require" took 2112.27ms

### Expected Behavior

it should not throw exception and write data into dynamodb

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker-compose up

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)
   build follow steps described in Readme of the project 
   use curl command above for testing , only change apigateway rest api id in url   
   following command gets rest-api description . can get id from there :
   awslocal apigateway get-rest-apis

### Environment

```markdown
- OS: windows 10 home edition , also ubuntu 22
- LocalStack: localstack-pro:latest
```

**Comment by metojava** [comment]
I found solution . Java dynamodb client points to amazon url by default . **one should make it to point it to locastack url instead**
https://docs.localstack.cloud/user-guide/integrations/sdks/java/#configuring-the-dynamodb-client
replacing dynamodb client as described on linked page (V2 actually) helped
thanks
only thing is that it takes some time until starts container for it and makes insert
I was thinking for best user experience it should be lightning fast ...
:)

**Comment by viren-nadkarni** [comment]
Hi @metojava, glad to see that you were able to resolve this issue. Please feel free to report other issues if any. Thanks for using LocalStack!
