### ISSUE TITLE
enhancement request: Add DynamoDB TTL to evict stale KV pairs

### ISSUE THREAD

**Issue by robertlcx** [localstack/localstack#10022]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Enhancement description

Lots of teams rely on TTL on their DynamoDB to reduce their significant AWS cloud spend by having stale KV pairs evicted from the store. Naturally, most teams want this on Localstack as well to maintain parity with what they have on AWS.

More on this here: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/TTL.html

### Anything else?

This is a user-requested feature.

**Comment by giograno** [comment]
Initial implementation provided in #10041
