### ISSUE TITLE
Localstack in version 3.x.x returns queueUrl with default port "4566" even when there was port binding to different port

### ISSUE THREAD

**Issue by patriano** [localstack/localstack#10024]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In version >3.x.x when locastack container is bind to port e.g. `52158` 
<img width="350" alt="image" src="https://github.com/localstack/localstack/assets/33000003/0688afbc-9009-4f2d-8b8a-c2252bb92496">

then after creating queue with name `core-DLQ` in SQS service it returns following queueUrl in response:
`http://localhost:4566/queue/us-east-1/000000000000/core-DLQ`

![image](https://github.com/localstack/localstack/assets/33000003/a8e9ed6c-7cb1-4115-a366-6e7fc35fa223)

### Expected Behavior

In version `2.3.2` (and lower) of localstack when locastack container is bind to port e.g. `52003` 
<img width="340" alt="image" src="https://github.com/localstack/localstack/assets/33000003/6380320f-9c4e-46d7-9f46-db446002a130">

then after creating queue with name `core-DLQ` in SQS service it returns following queueUrl in response:
`http://127.0.0.1:52003/queue/us-east-1/000000000000/core-DLQ`

![image](https://github.com/localstack/localstack/assets/33000003/e7694959-8d10-4f5c-97fc-b0a6bc9a93a8)

So localstack understands that there is other external port and uses it for queueUrl creation

### How are you starting LocalStack?

With a `docker run` command

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

We are using TestContainers in our project

![image](https://github.com/localstack/localstack/assets/33000003/b407a259-700f-418b-bb41-23e85c752f10)

`LOCALSTACK_HOST` is set to `localhost`

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

`CreateQueueResult result = clientSQS.createQueue("exampleQueueName");`

### Environment

```markdown
- OS: MacOs 14.2.1
- LocalStack: 3.0.2
```

**Comment by sharpnk** [comment]
Same issue here. This is pretty frustrating because we had to use Localstack v3 to get around this [issue](https://github.com/aws/aws-sdk-java/issues/3061) with newer aws sdk version(1.12.583).

**Comment by dmouser-kmart** [comment]
Facing the same issue as @sharpnk above - needed up upgrade to v3 to workaround issue with aws sdk version only to then strike this bug with queue urls always being returned on port 4566 despite our `testcontainers-java` using a random port.  Tried numerous workarounds without any success!

**Comment by suryakrish** [comment]
Facing the same issue as @sharpnk and @dmouser-kmart as above, I needed to upgrade to v3 to deal with aws sdk version upgrade. However this SQS queue urls returning port 4566 instead of random 5-digit port stucks my upgrade. :( 

I was bit successful by replacing `LocalStackContainer` with `ComposeContainer` (as it opens the port 4566 for localhost access from host machine, where tests are running in my mac machine. However I got introduced to other issues in Gitlab CI (ubuntu) that it was unable to open the port as errors below: 
`Exception when starting docker-compose container: org.testcontainers.containers.ContainerLaunchException: Timed out waiting for container port to open (172.17.0.1 ports: [32768, 4510, 4511, 4512, 4513, 4514, 4515, 4516, 4517, 4518....`

**Comment by nzerouali** [comment]
One workaround is to get the external SQS URL using getEndpointOverride and add to it the path part of the URL from queueUrl.

```kotlin
val externalSqsUrl = localStackContainer.getEndpointOverride(LocalStackContainer.Service.SQS).toString()
val localSqsUrl = amazonSQS.createQueue(CreateQueueRequest("my-queue")).queueUrl.toHttpUrl()

// Combine the hostname from the externalSqsUrl with the URL path from localSqsUrl
val externalQueueUrl = externalSqsUrl.toHttpUrl().newBuilder().encodedPath(localSqsUrl.encodedPath).build().toString()
```
e.g:
Example:
externalSqsUrl = "http://127.0.0.1:58254"
localSqlUrl = "http://127.0.0.1:4566/queue/us-east-1/000000000000/my-queue"

after combining it:
externalQueueUrl = "http://127.0.0.1:58254/queue/us-east-1/000000000000/my-queue"

**Comment by musketyr** [comment]
It seems to me that the valid workaround is setting env var `SQS_ENDPOINT_STRATEGY` to `dynamic`. in that case the resulting queue URL has the correct port.

**Comment by pcalouche** [comment]
> It seems to me that the valid workaround is setting env var `SQS_ENDPOINT_STRATEGY` to `dynamic`. in that case the resulting queue URL has the correct port.

@musketyr you're a lifesaver. That fixed all my broken tests when updating to LocalStack 3.

**Comment by roshea1-chwy** [comment]
> Same issue here. This is pretty frustrating because we had to use Localstack v3 to get around this [issue](https://github.com/aws/aws-sdk-java/issues/3061) with newer aws sdk version(1.12.583).

> It seems to me that the valid workaround is setting env var `SQS_ENDPOINT_STRATEGY` to `dynamic`. in that case the resulting queue URL has the correct port.

@sharpnk @musketyr Thanks for connecting the dots here. Just ran into the SDK v1.12.583+ SQS API issue with LocalStack 2, but `SQS_ENDPOINT_STRATEGY` "dynamic" allowed us to bump to LocalStack 3.3 and resolve it.

**Comment by patriano** [comment]
> It seems to me that the valid workaround is setting env var `SQS_ENDPOINT_STRATEGY` to `dynamic`. in that case the resulting queue URL has the correct port.

Yes, this solution should work, but was not working during submitting this bug as on localstack in version 3.0.2 dynamic strategy is not working and nothing is changing 😉

**Comment by alexrashed** [comment]
@patriano I'll close this issue since according to the discussion in this thread, it seems your issue has been fixed in the latest version of LocalStack. :)
