### ISSUE TITLE
enhancement request: Add support for validating requests on the API Gateway before proceeding with the integration

### ISSUE THREAD

**Issue by robertlcx** [localstack/localstack#10021]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Enhancement description

On AWS, you can configure API Gateway to perform basic validation of an API request before proceeding with the integration request.

When the validation fails, API Gateway immediately fails the request, returns a **400 error response** to the caller, and publishes the validation results in CloudWatch Logs. Exporting the results to CloudWatch isn't strictly required for a first revision of this ticket.

API Gateway can perform the basic request validation, so that you can focus on app-specific validation in the backend. For validation, API Gateway verifies either or both of the following conditions:

1. The required request parameters in the URI, query string, and headers of an incoming request are included and not blank.
The applicable request payload adheres to the configured [JSON schema](https://tools.ietf.org/html/draft-zyp-json-schema-04) request of the method.
2. To turn on validation, you specify validation rules in a [request validator](https://docs.aws.amazon.com/apigateway/latest/api/API_RequestValidator.html), add the validator to the API's [map of request validators](https://docs.aws.amazon.com/apigateway/latest/api/API_RequestValidator.html), and assign the validator to individual API methods.

This reduces unnecessary calls to the backend. More importantly, it lets you focus on the validation efforts specific to your application. You can validate a request body by verifying that required request parameters are valid and non-null or by specifying a model schema for more complicated data validation.

### Anything else?

This is a user-requested feature.

**Comment by bentsku** [comment]
Just a note, we currently support request validators for the request `Body` (validating the JSON Schema). 
https://github.com/localstack/localstack/blob/8ab41142e6d4fff30aaee170f861bc59f9f5aadf/localstack/services/apigateway/invocations.py#L95-L132

We are however still missing validating URI, query string, and headers.
