### ISSUE TITLE
bug: Unable to update API gateway proxy lambda using CDK

### ISSUE THREAD

**Issue by jamesphilipps** [localstack/localstack#10042]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When using CDK (cdklocal command) to create a simple API with a proxy integration to a lambda handler, the lambda is successfully created on the first run of CDK. On the second run, the update fails with the following message:

> failed: Error: The stack named example-stack failed to deploy: UPDATE_FAILED (An error occurred (BadRequestException) when calling the PutIntegration operation: Integrations of type 'AWS_PROXY' currently only supports Lambda function and Firehose stream invocations.): An error occurred (BadRequestException) when calling the PutIntegration operation: Integrations of type 'AWS_PROXY' currently only supports Lambda function and Firehose stream invocations.

> Deployment failed: Error: The stack named example-stack failed to deploy: UPDATE_FAILED (An error occurred (BadRequestException) when calling the PutIntegration operation: Integrations of type 'AWS_PROXY' currently only supports Lambda function and Firehose stream invocations.): An error occurred (BadRequestException) when calling the PutIntegration operation: Integrations of type 'AWS_PROXY' currently only supports Lambda function and Firehose stream invocations.

### Expected Behavior

The lambda is updated and the deployment completes without error

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

A full reproduction of the issue can be found at: https://github.com/jamesphilipps/localstack-cdk-error-example

### Environment

```markdown
- OS:WSL Ubuntu Linux with Windows Docker integration
- LocalStack Pro

ENV LOCALSTACK_BUILD_DATE=2024-01-09
ENV LOCALSTACK_BUILD_GIT_HASH=2028820
ENV LOCALSTACK_BUILD_VERSION=3.0.3.dev
```

### Anything else?

A full reproduction of the issue can be found at: https://github.com/jamesphilipps/localstack-cdk-error-example

**Comment by Yehonal** [comment]
I'm facing the same issue, when I change my lambda code and re-deploy

**Comment by Yehonal** [comment]
I'm wondering how someone could use Localstack when having an API with query parameters is one of the most common situations when you work on web applications.

Am I doing something wrong? Is there an alternative to it?

**Comment by Yehonal** [comment]
As a workaround for now I'm doing a double deployment locally, the first deployment without the API integration and the second deployment with the API integration. In this way, it removes the integration first (if any) and re-add it later.
It works but it takes double time to be deployed obviously
