### ISSUE TITLE
bug: redundant authorizer call(api ws gw)

### ISSUE THREAD

**Issue by kalitsinskyi81** [localstack/localstack#10059]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

API WS GW's authorizer lambda is called before the disconnect lambda is called, although such behavior was not observed in the real AWS API WS GW(it should be called while connection only)

### Expected Behavior

authorizer lambda should be called while connection only

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

```
  localstack:
    profiles: # explicit start only
      - localstack
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main_local}"
    image: localstack/localstack-pro:3.0.1
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4550:4510-4550"  # external services port range
      - "127.0.0.1:53:53"                # DNS config (required for Pro)
      #- "127.0.0.1:53:53/udp"           # do not work after Docker update, DNS config (required for Pro)
      - "127.0.0.1:443:443"              # LocalStack HTTPS Gateway (required for Pro)
    environment:
      - SERVICES=apigateway,lambda,dynamodb,sqs,sns,s3,iam,sts,logs,ec2,ssm
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN}
      - DEBUG=1
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./localstack-volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

1. create three lambdas, authorizer, connect and disconnect
2. create API Websocket Gateway (v2)
3. assign connect lambda on API GW `$connect` endpoint, disconnect lambda to`$disconnect in accordance
5. assign authorizer lambda as authorization for API GW
6. call API WS GW as a client with any tool like `wscat`(pass authorization)
7. trigger disconnection
8. observe authorizer was called **twice**

### Environment

```markdown
- OS: MacOS 14.2
- LocalStack: 3.0.1
```

**Comment by bentsku** [comment]
Hello @kalitsinskyi81 and thanks a lot for your report.

This issue should now be fixed in the `latest` localstack-pro image. Could you pull it using `docker pull localstack/localstack-pro:latest` and confirm that it fixes your issue?
Thanks!
