### ISSUE TITLE
feature request: Implement SchemaRegistry (AWS Glue) creation using CloudFormation

### ISSUE THREAD

**Issue by serhiikartashov** [localstack/localstack#10067]
AWS Glue Schema Registry is a key component for managing and evolving data schemas in a centralized and organized manner. To enhance the local development and testing experience using CloudFormation scripts, I suggest adding support for the Glue Schema Registry in AWS CloudFormation Localstack.

Four sources are available in AWS CloudFormation:
- [AWS::Glue::Registry](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-glue-registry.html)
- [AWS::Glue::Schema](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-glue-schema.html)
- [AWS::Glue::SchemaVersion](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-glue-schemaversion.html)
- [AWS::Glue::SchemaVersionMetadata](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-glue-schemaversionmetadata.html)

Localstack v3.0.2 doesn't support these Glue [resources](https://docs.localstack.cloud/user-guide/aws/cloudformation/) for CloudFormation. It's available by using **localaws** CLI, but it's not useful for automation purposes.

Looking forward to this feature with Create/Delete operations.

**Comment by serhiikartashov** [comment]
Hello team! Do you have any updates regarding this issue?

**Comment by macnev2013** [comment]
Hello, we are pleased to inform you that the requested feature, support for CFn providers, has been implemented. Kindly update to the latest `localstack-pro` container image and let us know if your issue has been resolved. Thank you!
