### ISSUE TITLE
feature request: Implement AWS DMS Service imitation

### ISSUE THREAD

**Issue by serhiikartashov** [localstack/localstack#10069]
Database Migration Service has lots of [features](https://aws.amazon.com/dms/features/) that might not be possible to imitate locally. But would be great to imitate some key features and sub-services for local development. Localstack v3.0.2 doesn't have DMS service. 

Would be great to imitate such DMS services:
- Replication Instance
- Replication Config
- Replication Task (FullLoad, Ongoing)
- Endpoint (Sources: Oracle, PostgreSQL, MySQL; Targets: Oracle, PostgreSQL, MySQL, Kafka topic)

AWS CLI [commands](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/dms/index.html)

Resources are available in AWS CloudFormation:
- [AWS::DMS::ReplicationInstance](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dms-replicationinstance.html)
- [AWS::DMS::ReplicationConfig](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dms-replicationconfig.html)
- [AWS::DMS::ReplicationTask](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dms-replicationtask.html)
- [AWS::DMS::Endpoint](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dms-endpoint.html)

Looking forward to this feature with Create/Delete operations.

**Comment by serhiikartashov** [comment]
Hello team! Do you have any updates regarding this issue?

**Comment by dschiavu** [comment]
Just noticed Moto [does support many DMS APIs already](https://github.com/getmoto/moto/blob/master/IMPLEMENTATION_COVERAGE.md), so it could perhaps be used for adding initial DMS support in LocalStack as well.

**Comment by HarshCasper** [comment]
Hi — We have shipped a preview state of DMS with LocalStack. Please take a look at the docs here: https://docs.localstack.cloud/user-guide/aws/dms/

**Comment by serhiikartashov** [comment]
@HarshCasper it seems this feature has moved to the Enterprise plan, we have only a Pro license.
I can't see the probability of using this feature in my project anymore.
