### ISSUE TITLE
Cfn: add AWS Glue Connection support in the Cfn

### ISSUE THREAD

**Issue by sienkiewiczPat** [localstack/localstack#10076]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Enhancement description

No resource provider found for "AWS::Glue::Connection". To find out if AWS::Glue::Connection is supported in LocalStack Pro, please check out our docs at https://docs.localstack.cloud/user-guide/aws/cloudformation/#resources-pro--enterprise-edition
I didn't get chance yet to look more into this one, as I am able to  create some connection manually (either using awslocal cli or through the UI. but failed with the Serverless framework).

**Comment by macnev2013** [comment]
Hello, we are pleased to inform you that the requested feature, support for CFn providers, has been implemented. Kindly update to the latest `localstack-pro` container image and let us know if your issue has been resolved. Thank you!
