### ISSUE TITLE
enhancement request: Add AWS::CloudFront::ResponseHeadersPolicy to CloudFormation

### ISSUE THREAD

**Issue by MarcelStranak** [localstack/localstack#10078]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Enhancement description

No resource provider found for `AWS::CloudFront::ResponseHeadersPolicy`.

**Comment by pinzon** [comment]
The solution for this issue has been just merged. Please make sure to use the latest version of LocalStack.
