### ISSUE TITLE
High memory issues running in docker container on macOS

### ISSUE THREAD

**Issue by archa347** [localstack/localstack#1007]
After starting up the docker container using `localstack start --docker`,  the memory usage spikes immediately, before I've even started interacting with the services.  

`docker stats` shows me this 
```0d3cf3d7546c        silly_chandrasekhar   5.47%               1.623GiB / 1.952GiB   83.14%              6.07kB / 2.13kB     164MB / 139MB       141```

Connecting to the container and running `top` gives me this [https://d.pr/free/i/z9gVXu](https://d.pr/free/i/z9gVXu)

My coworker, with pretty much the same setup, is using around 15 MiB of memory

I'm a docker noob, not really sure what the next troubleshooting steps should be from ehre

localstack: `0.8.7`
Docker Engine: `18.06.1-ce`
macOS: `10.14.1`

**Comment by whummer** [comment]
Thanks for reporting @archa347 . In the default configuration the startup is indeed relatively memory intensive, as multiple Python, Node, and Java processes are started in the container.

One way to limit the memory footprint is to select the set of service that should be started, via `SERVICES=...` (see README).

Also, a fix has been pushed in #1179 - the memory footprint of two of the Java processes should be significantly reduced. Can you please give it a try with the `latest` version of the Docker image?
