### ISSUE TITLE
bug: ECS does not support getting SecretManager JSON secret's specific key

### ISSUE THREAD

**Issue by jurgiskg** [localstack/localstack#10079]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Using the `arn:aws:secretsmanager:us-east-1:000000000000:secret:name:KEY::` format to fetch a specific key of JSON secret (documented in AWS [docs](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/secrets-envvar-secrets-manager.html#secrets-envvar-secrets-manager-update-container-definition)) results in the following error:
```
An error occurred (InternalError) when calling the RunTask operation (reached max retries: 4): exception while calling ecs.RunTask: An error occurred (ResourceNotFoundException) when calling the GetSecretValue operation: Secrets Manager can't find the specified secret
```

### Expected Behavior

The key format works and the specified key of JSON secret is successfully injected into ECS secret environment variables.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker-compose.yml

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

   using terraform to spin up an ECS service

### Environment

```markdown
- OS: macOS Sonoma 14.2.1 on Apple silicon
- LocalStack: 3.0.1
```

### Anything else?

The issue is already reported and verified in Localstack Slack https://localstack-community.slack.com/archives/CMAFN2KSP/p1700151228580459

**Comment by simonrw** [comment]
Hi, thanks for reporting this issue. This problem should have been fixed in the latest issue. Please pull the latest image (`docker pull localstack/localstack-pro`) or if you are using a tagged release, the fix is in `3.1.0`, and try again. 

I will close this issue as completed. Please feel free to re-open this issue, or create a new issue if your particular problem is not solved.
