### ISSUE TITLE
bug: RDS is too slow when executing queries

### ISSUE THREAD

**Issue by ctovarr** [localstack/localstack#10085]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I execute SQL migrations in an RDS database created by CDK and LocalStack, those migrations take hours to complete. Additionally, CPU usage goes above 100% and my LocalStack container stops responding to new requests 

```
reside-migrate-db  | 20230615175741/u qa-seed-data (5h41m47.075861682s)
reside-migrate-db  | 20230623233832/u DEV-1462-new-table-hs_audit_trail_sftp_upload (5h41m47.137609391s)
reside-migrate-db  | 20230626140621/u remove_dashboard_full_width_feature_flag (5h41m47.148945099s)
reside-migrate-db  | 20230713214327/u add_pcc_facility_picklists_and_items (5h41m47.167385891s)
reside-migrate-db  | 20230725120732/u add_unique_date_to_pcc_quota_limit (5h41m47.019565849s)
reside-migrate-db  | 20230728202811/u generate_pre_flight_transitions (5h41m47.020206099s)
reside-migrate-db  | 20230731234037/u truncate_admissions_transitions (5h41m47.024731474s)
```

### Expected Behavior

It should take a reasonable time, the same migration script with a Postgres container takes less than one second

```
reside-migrate-db  | 20230615175741/u qa-seed-data (176.190208ms)
reside-migrate-db  | 20230623233832/u DEV-1462-new-table-hs_audit_trail_sftp_upload (182.382708ms)
reside-migrate-db  | 20230626140621/u remove_dashboard_full_width_feature_flag (182.552459ms)
reside-migrate-db  | 20230713214327/u add_pcc_facility_picklists_and_items (190.516708ms)
reside-migrate-db  | 20230725120732/u add_unique_date_to_pcc_quota_limit (191.245416ms)
reside-migrate-db  | 20230728202811/u generate_pre_flight_transitions (192.126166ms)
reside-migrate-db  | 20230731234037/u truncate_admissions_transitions (196.596ms)

```

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

Recently I created another bug which I was able to solve by removing the cdk. context.json file. I used this stack

https://github.com/ctovarr/rds-bug-cdk

I can't share the migration SQL I have but I will work on creating a dummy table and inserting a bunch of resources and I will compare it with the docker-compose version.

### Environment

```markdown
- OS: 14.1.1 (23B81)
- LocalStack: localstack/localstack-pro:3.0.0
```

**Comment by bentsku** [comment]
Hello @ctovarr and sorry for the delay on this one. The repo has not been updated so I cannot check if the new fix we just worked on would apply, but we could make big `INSERT` and `COPY` queries around a 1000x times faster in our benchmarks. 

Could you try pulling `localstack/localstack-pro:latest` and see if that would fix your issue? Thank you!

**Comment by ctovarr** [comment]
Awesome, thank you so much. I just tested it and it executed fast. This will help us to continue migrating our infra to use LocalStack <3

**Comment by bentsku** [comment]
Awesome, thanks for the feedback! I'll close the issue then, thanks again for the report!
