### ISSUE TITLE
bug: Update `localstack/localstack:3` Docker Hub Image

### ISSUE THREAD

**Issue by ScottFinlaysonGMSL** [localstack/localstack#10094]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The existing `localstack/localstack:3` image doesn't include the fixes applied the `latest`. This includes the fix for https://github.com/localstack/localstack/issues/9977. The images haven't been updated for [2 months](https://hub.docker.com/r/localstack/localstack/tags) so possibly missing some other features as well.

We'd like to ensure backwards compatibility so would prefer no to use `latest` and stick to using major version numbers as the tag `3`.

### Expected Behavior

Update the docker hub tags for `localstack/localstack`:
- `3`
- `3.0`

### How are you starting LocalStack?

Custom (please describe below)

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker pull localstack/localstack:3

### Environment

```markdown
- OS: Ubuntu 22.04 (WSL)
- LocalStack:3.0.2
- AWS CLI: 2.15.5
```

**Comment by dfangl** [comment]
Hi @ScottFinlaysonGMSL !
You are right, there have not been tagged releases for quite some time before `3.1`. We will try to do tagged releases more regularly!
We released `3.1` last thursday, and updated the `3` tag with it as well, so I assume this issue can be closed.
Thank you for your report!
