### ISSUE TITLE
bug: Does not return deleted output when use with AWS SDK

### ISSUE THREAD

**Issue by alwismt** [localstack/localstack#10109]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Language : Golang

AWS return an output after deleting (version enabled bucket)

AWS output

`deletedOutput  {
      DeleteMarker: true,
      VersionId: "Zrexps8S2syfg7pXKH4x08EFaH8yDk47"
 }`

But when do it with localstack it comes empty
`deletedOutput  {
}`

The code I'm using 
`deleteObject := &s3.DeleteObjectInput{
		Bucket:    s3Bucket,
		Key:       s3Key,
		VersionId: versionID,
	}
	svc := s3.New(NewAWSSession())
	deletedOutput, err := svc.DeleteObject(deleteObject)
	if err != nil {
		err = fmt.Errorf("remove.removeFile: Failed to delete object from S3 %s, %v", *s3Key, err)
		applog.Error(op.ctx, err)
		return nil, err
	}
	fmt.Println()
	fmt.Println("deletedOutput ", deletedOutput)
	return deletedOutput.VersionId, nil`

### Expected Behavior

It should return deletedOutput like this
`deletedOutput  {
  DeleteMarker: true,
  VersionId: "Zrexps8S2syfg7pXKH4x08EFaH8yDk47"
}`

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal s3 mb s3://mybucket

### Environment

```markdown
- OS:
- LocalStack:
```

**Comment by bentsku** [comment]
Hello @alwismt and thanks for your report!

Could you try pulling a more recent version (superior to 3.0) and see if that would fix your issue? Significant efforts have been made to improve the parity of S3. 
You can try to pull either `localstack/localstack:3.2` or `localstack/localstack:latest`. Thanks!
