### ISSUE TITLE
bug: Lambda + Kafka Event Source Mapping Issue

### ISSUE THREAD

**Issue by MarcelStranak** [localstack/localstack#10103]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In AWS, the ConsumerGroupId parameter in the event-source-mapping configuration allows multiple Lambda functions with different consumer group IDs to listen to the same topic, and both receive the event. This functionality has been in place since 2022.

However, when implementing the same scenario in LocalStack, it appears that only one Lambda function is receiving the event. This deviation from the expected behavior fundamentally breaks the produce/consume rules and renders running Lambda + Kafka on LocalStack impractical unless restricted to a single consumer per topic.

### Expected Behavior

Multiple Lambda functions with different Consumer Group IDs should be able to listen to the same Kafka topic and receive events.

### How are you starting LocalStack?

With the `localstack` script

### Steps To Reproduce

- Deploy a Lambda function with an event-source-mapping configuration specifying different Consumer Group IDs.
- Produce events to the Kafka topic.
- Observe that only one Lambda function is receiving the event.

### Environment

```markdown
- OS: windows 11
- LocalStack: latest
```

### Anything else?

Docs:
- https://docs.aws.amazon.com/lambda/latest/dg/invocation-eventsourcemapping.html
- https://docs.aws.amazon.com/lambda/latest/dg/with-kafka.html

**Comment by gregfurman** [comment]
Hi @MarcelStranak. I tested this against ESM v2 and things seem to be working.

I did the following:
- Created 2 Lambdas.
- Created 2 event source mappings to MSK, each with different consumer group IDs
- Produced an event to MSK which both Lambdas consumed successfully.

Let me know if you're still noticing issues on your side!

**Comment by MarcelStranak** [comment]
Hello @gregfurman,

Thank you for the thorough testing and for providing the new ESM v2 provider.
I have confidence in your findings and you may proceed to close the issue.

Here is a waffle 🧇  for your troubles.

I greatly appreciate your excellent support and look forward to continuing our collaboration.
