### ISSUE TITLE
kms generate-data-key appears to ignore keyspec

### ISSUE THREAD

**Issue by andrewjohns-sym** [localstack/localstack#10126]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When generating an AES_128 Key, I expected the plainText to be 16 bytes
```bash
awslocal kms create-key --multi-region
{
    "KeyMetadata": {
        "AWSAccountId": "....,
        "KeyId": "mrk-bda8fe16003842e285483cdb987ef2ba",
        ...
        "MultiRegion": true
    }
}
awslocal kms generate-data-key --key-id mrk-bda8fe16003842e285483cdb987ef2ba --key-spec AES_128
{
    "CiphertextBlob": "...",
    "Plaintext": "2vnVm5kIsg250/KBLgWw/65qG5eh+VK8MxAMS8y1EIo=",
    "KeyId": ".../mrk-bda8fe16003842e285483cdb987ef2ba"
}
** bytes[da f9 d5 9b 99 08 b2 0d b9 d3 f2 81 2e 05 b0 ff ae 6a 1b 97 a1 f9 52 bc 33 10 0c 4b cc b5 10 8a]
```

### Expected Behavior

```bash
aws kms create-key --multi-region
{
    "KeyMetadata": {
        "AWSAccountId": "....,
        "KeyId": "mrk-839d967e2f69433c96a3262721908e1c",
        ...
        "MultiRegion": true
    }
}
aws kms generate-data-key --key-id mrk-839d967e2f69433c96a3262721908e1c --key-spec AES_128
{
    "CiphertextBlob": "...",
    "Plaintext": "jiwoeE6ImSA0zWL1W+gWOw==",
    "KeyId": ".../mrk-839d967e2f69433c96a3262721908e1c"
}
** bytes[8e 2c 28 78 4e 88 99 20 34 cd 62 f5 5b e8 16 3b]
```

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

start localstack with aws KMS service
Compare results to actual aws KMS service

### Environment

```markdown
- OS: WINDOWS
- LocalStack: 3.0.2
```

**Comment by shubham-padia** [comment]
I'd like to work on this issue.

My plan is to modify `generate-data-key` and `generate-data-key-without-plaintext` where they could accept either key_spec or number_of_bytes. key_spec would accept `AES_128` and `AES_256` as valid values for this operation. 

I'd need to modify `KmsCryptoKey` to modify the key_material based on the key_spec given. Although this key_spec is quite different from the one used in generate_data_key_pair, we can still modify `KmsCryptoKey` to suit our use case.

**Comment by sannya-singal** [comment]
Hey @shubham-padia thanks for your interest in contributing to Localstack 🎉 🚀 Kindly follow the [contribution guidelines](https://github.com/localstack/localstack/blob/master/docs/CONTRIBUTING.md) and feel free to open a PR and we can discuss any issues you are facing there. Thanks!
