### ISSUE TITLE
bug: <title> CreateRepository operation: API for service 'ecr' not yet implemented 

### ISSUE THREAD

**Issue by malhotraguy** [localstack/localstack#10137]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

awslocal ecr create-repository --repository-name localstack-lambda-container-image

An error occurred (InternalFailure) when calling the CreateRepository operation: API for service 'ecr' not yet implemented or pro feature - please check https://docs.localstack.cloud/references/coverage/ for further information 

----------------------------------------------------------------------------------------------------------------------------

**LOGS:-**

2024-01-29T21:42:54.655 ERROR --- [   asgi_gw_0] l.aws.handlers.logging     : exception during call chain: 
localstack-main  | 2024-01-29T21:42:54.657  INFO --- [   asgi_gw_0] l.aws.handlers.service     : API for service 'ecr' not yet implemented or pro feature - please check https://docs.localstack.cloud/references/coverage/ for further information
localstack-main  | 2024-01-29T21:42:54.665  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS ecr.CreateRepository => 501 (InternalFailure)

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

`version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - SERVICES=s3,lambda,iam,ecr
      - DEBUG=${DEBUG:-0}
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"`
      
#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

     
    docker-compose up

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal ecr create-repository --repository-name localstack-lambda-container-image

### Environment

```markdown
- OS:MacOS Version 14.3
- LocalStack:Version: 3.1.0
- awscli-local==0.22.0
```

**Comment by komarkovich** [comment]
Hi,

[ECR](https://docs.localstack.cloud/references/coverage/coverage_ecr/) is supported only in the PRO version of LocalStack.
