### ISSUE TITLE
Support Textract service

### ISSUE THREAD

**Issue by ansnoussi** [localstack/localstack#10144]
## Issue description
- currently the Textract service isn't supported by LocalStack, so cannot use it for local development.

## Proposed Solution
- Ideally, LocalStack should add support for the service, which is basically a wrapper for the [Tesseract library](https://pypi.org/project/pytesseract/).
- A full-blown emulation of the service might be too much work to add, if not already on the roadmap of LocalStack, so a mock implementation would be the next best thing, just to keep the seamless development flow locally.

**Comment by HarshCasper** [comment]
We have shipped the CRUD support for Textract with the `localstack/localstack:pro` image. Please pull the `latest` tag to get started. Here are the relevant docs: https://docs.localstack.cloud/user-guide/aws/textract/
