### ISSUE TITLE
Pointing golang SDK to localstack

### ISSUE THREAD

**Issue by mkj28** [localstack/localstack#1015]
Correct me if I am wrong - but to point an app using AWS SDK for Go to localstack - I need to modify the code? There is no environment variable I could set to specify the localstack endpoint url?

**Comment by dmnlk** [comment]
@mkj28 
you can change endpoint  by `github.com/aws/aws-sdk-go/aws/endpoints`

https://docs.aws.amazon.com/sdk-for-go/api/aws/endpoints/

**Comment by mkj28** [comment]
thanks @dmnlk for confirming, all the best
