### ISSUE TITLE
bug: Context passed to JavaScript resolvers of AppSync is missing the (redundant) args field

### ISSUE THREAD

**Issue by johannesfloriangeiger** [localstack/localstack#10181]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When using JavaScript resolvers, the `args` field of the `context` is undefined, despite being documented in the AWS Developer Guide (https://docs.aws.amazon.com/appsync/latest/devguide/resolver-context-reference-js.html).

### Expected Behavior

The field is present.

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    localstack start

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

Save the following minimal schema in the file `minimal.graphql`

    type Entity {
        id: String!
    }

    type Query {
	    getEntity(id: String!): Entity
    }

Then run

    awslocal appsync create-graphql-api --name entities --authentication-type API_KEY
    awslocal appsync start-schema-creation --api-id <API ID> --definition $(base64 < minimal.graphql)

Save the following example resolver in the file `getEntity-resolver.js`

    import { util } from '@aws-appsync/utils';
    import { get } from '@aws-appsync/utils/dynamodb';

    export function request(ctx) {
        const { id } = ctx.args;
        const key = { id };
        return get({
            key,
        })
    }

    export function response(ctx) {
        const { error, result } = ctx;
        if (error) {
            return util.appendError(error.message, error.type, result);
        }
        return result;
    }

And then run

    awslocal appsync create-resolver --api-id <API ID> --type-name Query --field-name getEntity --runtime name=APPSYNC_JS,runtimeVersion=1.0.0 --code "$(cat getEntity-resolver.js)"
    awslocal appsync create-api-key --api-id <API ID>

Now save the query in the file `minimal-query.json`

    {
      "query": "query {
        getEntity(id: \"1\") {
          id
        }
      }"
    }

And call the API using the URL and API key

    curl -v -H "x-api-key: <API key>" -H "Content-Type: application/json" -d @minimal-query.json <URL>

Note that you're getting the error message

    {"data": {"getEntity": null}, "errors": [{"message": "Docker container returned with exit code 1", "locations": [{"line": 1, "column": 16}], "path": ["getEntity"], "errorType": "ContainerException"}]}

and the Docker container shows an error along the lines of 

    TypeError: Cannot destructure property 'id' of 'ctx.args' as it is undefined.

Now, deleting the resolver, changing the code by replacing `ctx.args` with `ctx.arguments`, and creating the resolver again followed by the same curl command leads to a successful `{"data": {"getEntity": null}}`.

### Environment

```markdown
- OS: MacOs
- LocalStack: 3.1.1.dev
```

### Anything else?

This is a minor issue as `args` and `arguments` seemingly contain the same data, it's a bit of an annoyance though.

**Comment by simonrw** [comment]
Hi @johannesfloriangeiger , thanks for raising this issue. We fixed this issue early last month. Sorry for not updating this ticket sooner. Please pull the latest docker `localstack/localstack-pro:latest` docker image. If you continue to find issues, please feel free to open another GitHub issue.
