### ISSUE TITLE
lambda executor cannot separate Console.WriteLine from lambda response

### ISSUE THREAD

**Issue by mosesyu** [localstack/localstack#1019]
I am trying to use localstack with dotnetcore 2.0 inside docker. In the lambda, I use `Console.WriteLine` to log some information to CloudWatch according to https://docs.aws.amazon.com/lambda/latest/dg/dotnet-logging.html. When the same code is deployed to actual Lambda, everything seems to be working fine. But when it is deployed to localstack, https://github.com/localstack/localstack/blob/master/localstack/services/awslambda/lambda_executors.py#L64 causes the json library not able to parse the response from lambda, because the messages from `Console.WriteLine` is also written into `stdout`, and make the response not valid json any more.

What is the recommended way to log?

Thanks

**Comment by whummer** [comment]
Thanks for reporting @mosesyu . Closing this as outdated - should have been resolved in the meantime, as Lambda execution and logging has been significantly reworked. Please report here if the problem persists. Thanks
