### ISSUE TITLE
bug: Step functions does not support ECS service type

### ISSUE THREAD

**Issue by utibeabasi6** [localstack/localstack#10216]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```
6:48:04 AM | CREATE_FAILED        | AWS::StepFunctions::StateMachine | BuildSourceCodeWor...ateMachine67076E41
An error occurred (InvalidDefinition) when calling the CreateStateMachine operation: Error=NotImplementedError Args=["Unsupported service: 'ecs'."] in definition '{"StartAt":"Update Deployment: Status=BUILD_IN_PROGRESS","States"
```

I get the above error when trying to deploy my step functions workflow with CDKLocal

### Expected Behavior

The stack should deploy successfully

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal s3 mb s3://mybucket

### Environment

```markdown
- OS: Linux
- LocalStack: latest
```

**Comment by utibeabasi6** [comment]
would appreciate any help @MEPalma

**Comment by MEPalma** [comment]
@utibeabasi6 thanks for compiling this. It's planned in development and should be available in the coming weeks. I'll update this issue when support will be added.

**Comment by utibeabasi6** [comment]
Thanks
