### ISSUE TITLE
enhancement request: Add support for PreTokenGenerationLambda v2

### ISSUE THREAD

**Issue by jorge-castello** [localstack/localstack#10248]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Enhancement description

I am running LocalStack like this:
```
# Startup the service
export AWS_PROFILE=localstack
export AWS_ACCOUNT_ID=000000000000
export AWS_REGION=us-west-2
export AWS_STAGE=DEV

SERVICES=serverless,sts,s3,ssm,ec2,cloudformation,iam,lambda,ecr,rds,secretsmanager,docdb,cognito-idp,logs,apigateway DOCDB_PROXY_CONTAINER=1 localstack start -d
```
- I am deploying my application via AWS CDK
- The service that I am running into an issue: cognito and API Gateway Authorizer
- Errors: unfortunately, I am not receiving any errors, I believe that it is a feature gap

Describe the issue:
When I deploy my CDK to AWS, it 1) calls my PreTokenGeneration v2 Lambda which uses special logic to assign scopes to the user's access token based on the Cognito Groups they are in, and 2) the Cognito Authorizer will validate the scope is present.

Here is an example of my PreTokenGenerationLambda:

```
const preTokenGenerationLambda = new lambda.Function(
      scope,
      `${props.stage}-PreTokenGenerationLambda`,
      {
        functionName: `${props.stage}-PreTokenGenerationLambda`,
        runtime: lambda.Runtime.NODEJS_20_X,
        handler: "index.handler",
        code: lambda.Code.fromInline(`
            exports.handler = (event, context) => {
              const userGroups = event.request.groupConfiguration.groupsToOverride;
              if (userGroups && userGroups.includes("Admin")) {
                event.response = {
                  claimsAndScopeOverrideDetails: {
                    accessTokenGeneration: {
                      scopesToAdd: [${adminScopes
                        .map((s) => `"${s}"`)
                        .join(",")}],
                    },
                  },
                };
              }
              context.done(null, event);
            };
        `),
      },
    );
    preTokenGenerationLambda.grantInvoke(
      new iam.ServicePrincipal("cognito-idp.amazonaws.com"),
    );
```

Here is an example of one of my routes:

```
const storesResource = props.api.root.addResource("stores");
    const lambdaIntegration = new apigateway.LambdaIntegration(
      storesCrudLambda.lambda,
    );

const post = storesResource.addMethod(HttpMethod.POST, lambdaIntegration, {
      authorizer: props.cognitoAuthorizer,
      authorizationType: AuthorizationType.COGNITO,
      authorizationScopes: [
        formatScopeWithResourceServer(STORES_CREATE.scopeName),
      ],
    });
```

What is the issue:
- My PreTokenGenerationLambda does not get invoked during API requests
- Interestingly, LocalStack seems to be adding ALL scopes to my access token

My guess is that there may be a lack of support for v2 PreTokenGenerationLambda which was released only a few months back. Please let me know what other information I can provide to be most helpful!

### Anything else?

Let me know if there is additional information I can provide!

**Comment by kingsleyh** [comment]
I'm interested in this also - needed for modifying the access token

**Comment by justinc-patchwork** [comment]
Upvoted 👍

**Comment by giograno** [comment]
Hi @jorge-castello, thanks for opening this issue. We released a fix in the `latest` Docker image, enabling PreGenerationToken lambda V2_0. Please, give it a try and let us know if there are still some implementation gaps to be fixed. Thank you 🙏

**Comment by jorge-castello** [comment]
Hi @giograno,

Thank you so much for working on this and getting it shipped so quickly! I have a small bug to report with the behavior. Can you please take a look and let me know if my description is helpful or if there's any additional information I can share?

**Unexpected Behavior**
Currently, it looks like the `scopes` added to the access token are being `duplicated`.

**Expected Behavior**
Only scopes returned by the PreTokenGenerationLambda should be included in the access token.

---

### Code pointers

Here is my PreTokenGenerationLambda

```
const preTokenGenerationLambda = new lambda.Function(
      scope,
      `${props.stage}-PreTokenGenerationLambda`,
      {
        functionName: `${props.stage}-PreTokenGenerationLambda`,
        runtime: lambda.Runtime.NODEJS_20_X,
        handler: "index.handler",
        code: lambda.Code.fromInline(`
            exports.handler = (event, context) => {
              const userGroups = event.request.groupConfiguration.groupsToOverride;
              if (userGroups && userGroups.includes("Admin")) {
                event.response = {
                  claimsAndScopeOverrideDetails: {
                    accessTokenGeneration: {
                      scopesToAdd: [${adminScopes
                        .map((s) => `"${s}"`)
                        .join(",")}],
                    },
                  },
                };
              }
              console.log(JSON.stringify(event));
              context.done(null, event);
            };
        `),
      },
    );
```

I used https://jwt.io/ to parse the access token, which shows the correct scopes for my request:

```
"response": {
    "claimsAndScopeOverrideDetails": {
      "accessTokenGeneration": {
        "scopesToAdd": [
          "ice_cream_resource_server/stores.create",
          "ice_cream_resource_server/stores.read",
          "ice_cream_resource_server/stores.update",
          "ice_cream_resource_server/users.create",
          "ice_cream_resource_server/users.read",
          "ice_cream_resource_server/users.update",
          "ice_cream_resource_server/recipes.create",
          "ice_cream_resource_server/recipes.read",
          "ice_cream_resource_server/recipes.update"
        ]
      }
    }
  },
```

I also logged the access token that I am receiving in my Lambda function, and you'll notice there are duplicates:
```
{
  "scope": "
  # These should not be here (represents all scopes available)
  ice_cream_resource_server/stores.create 
  ice_cream_resource_server/stores.read 
  ice_cream_resource_server/stores.update 
  ice_cream_resource_server/stores.delete 
  ice_cream_resource_server/users.create 
  ice_cream_resource_server/users.read 
  ice_cream_resource_server/users.update 
  ice_cream_resource_server/users.delete 
  ice_cream_resource_server/recipes.create
  ice_cream_resource_server/recipes.read 
  ice_cream_resource_server/recipes.update 
  ice_cream_resource_server/recipes.delete 
  
  # These are the scopes that were returned by my PreTokenGenerationLambda
  ice_cream_resource_server/stores.create 
  ice_cream_resource_server/stores.read 
  ice_cream_resource_server/stores.update 
  ice_cream_resource_server/users.create 
  ice_cream_resource_server/users.read 
  ice_cream_resource_server/users.update 
  ice_cream_resource_server/recipes.create 
  ice_cream_resource_server/recipes.read 
  ice_cream_resource_server/recipes.update"
}
```

From what I can tell, this bug existed prior to your implementation for V2 PreTokenGenerationLambda. It appears that ALL scopes are being added to the access token by default. This is why we have ALL scopes + scopes added by the PreTokenGenerationLambda. The expected behavior should include 0 scopes by default, and then add only scopes returned by the PreTokenGenerationLambda.

Let me know your thoughts on this! Thanks in advance for taking a look.

**Comment by kingsleyh** [comment]
This is great - thanks very much :) 

I'm using the suppress functionality in the pre token generation lambda to remove the unwanted default scopes at the moment

**Comment by jorge-castello** [comment]
Makes sense 👍

@giograno - what are your thoughts on this?

**Comment by jorge-castello** [comment]
Personally, I prefer to not incorporate the suppress functionality into my PreTokenGenerationLambda. Let me know if it would make sense to open a separate bug request or if we can continue the conversation here. Thank you :)

**Comment by MarcelStranak** [comment]
Hi @jorge-castello, we opened a new PR that should resolve your follow-up issue. We will inform you when we have more details.

**Comment by jorge-castello** [comment]
HI Marcel,

Thanks a bunch! Do you mind if I look at the PR? I'm curious about it for my own learning purposes.

Thanks,
Jorge

**Comment by MarcelStranak** [comment]
Hi @jorge-castello, I am sorry, but this is not possible as Cognito is part of the pro offering.
I would like to let you know the issue has been resolved in the `latest` LocalStack Docker image. Please let us know if the issue has been resolved from your side. Thanks.

**Comment by jorge-castello** [comment]
HI @MarcelStranak,

Thanks for the update! I really appreciate all the help on this. On my side, it looks like the PreTokenGeneration lambda is now working as expected. Unfortunately, what I'm now seeing is that the Cognito Authorizer is not failing due to the missing scope, but instead is still allowing the request to succeed.

Here are some details on my side:

```
# Logged Scopes

"scope":"aws.cognito.signin.user.admin ice_cream_resource_server/stores.create ice_cream_resource_server/stores.read ice_cream_resource_server/stores.update ice_cream_resource_server/users.create ice_cream_resource_server/users.read ice_cream_resource_server/users.update ice_cream_resource_server/recipes.create ice_cream_resource_server/recipes.read ice_cream_resource_server/recipes.update ice_cream_resource_server/battingOrders.create ice_cream_resource_server/battingOrders.read ice_cream_resource_server/battingOrders.update"
```

As we can see, we are missing the `delete` scope.

When I construct my API on the CDK side of things, I do the following:

```
new GenericCrudApi(props, "battingOrders", battingOrdersCrudLambda, {
      [HttpMethod.POST]: BATTING_ORDERS_CREATE,
      [HttpMethod.GET]: BATTING_ORDERS_READ,
      [HttpMethod.PUT]: BATTING_ORDERS_UPDATE,
      [HttpMethod.DELETE]: BATTING_ORDERS_DELETE,
    });
```

Then in the base class:

```
import * as apigateway from "aws-cdk-lib/aws-apigateway";
import { CrudApiProps } from "./rest-api";
import { Lambda } from "../lambda";
import { AuthorizationType } from "aws-cdk-lib/aws-apigateway";
import { formatScopeWithResourceServer, Scope } from "../../config/api-scopes";
import { HttpMethod } from "aws-cdk-lib/aws-apigatewayv2";

export class GenericCrudApi {
  constructor(
    props: CrudApiProps,
    resourceName: string,
    lambdaFunction: Lambda,
    scopes: Record<string, Scope>,
  ) {
    const resource = props.api.root.addResource(resourceName);
    const itemResource = resource.addResource("{id}");

    const lambdaIntegration = new apigateway.LambdaIntegration(
      lambdaFunction.lambda,
    );

    this.addMethod(
      resource,
      HttpMethod.POST,
      lambdaIntegration,
      props,
      scopes[HttpMethod.POST],
    );

    [HttpMethod.GET, HttpMethod.PUT, HttpMethod.DELETE].forEach((method) => {
      this.addMethod(
        itemResource,
        method,
        lambdaIntegration,
        props,
        scopes[method],
      );
    });
  }

  addMethod(
    resource: apigateway.Resource,
    method: HttpMethod,
    integration: apigateway.LambdaIntegration,
    props: CrudApiProps,
    scope: Scope,
  ) {
    resource.addMethod(method, integration, {
      authorizer: props.cognitoAuthorizer,
      authorizationType: AuthorizationType.COGNITO,
      authorizationScopes: [formatScopeWithResourceServer(scope.scopeName)],
    });
  }
}

```

What I'm trying to illustrate is that I am adding the scopes I require for a given API endpoint in order for the request to proceed. I just deployed my same code to AWS and it works as expected. As a result, I believe that my implementation is sound.

However, LocalStack seems to just be allowing the request to proceed in the Cognito Authorizer even though the scopes required aren't present. One thing that I also noticed is that in the APIGateway UI for LocalStack, I noticed that Authorization Scopes is blank (see attached photo):

<img width="1624" alt="LocalStackAuthorizationScopes" src="https://github.com/localstack/localstack/assets/60675751/f4cbd2af-a0d2-43b2-a77f-ccf825fe2e2c">

Can you please let me know what the expected behavior is here? Do you think this is an issue with my logic? I'm hoping to get close to resolving on this issue so that I can move forward to my next task. In that regard, I really appreciate all of your continued support.

Let me know your thoughts!

Best,
Jorge

**Comment by MarcelStranak** [comment]
Hi @jorge-castello, thanks for the follow-up. Please make a new issue with your last message, so we can work on it there. This feature request has been fulfilled and closed. Thanks.

**Comment by giograno** [comment]
Hi @jorge-castello, sorry for the delay in the answer. We released a fix in the `latest` Docker image.
You should both see the scopes in the web UI and the Cognito authorized should correctly deny the request if the right scopes are not provided. Please let us know if you find any other issue 🙏

**Comment by jorge-castello** [comment]
No worries, sounds good!
