### ISSUE TITLE
bug: AppSync doesn't convert string values to boolean

### ISSUE THREAD

**Issue by ahsankarimbhai** [localstack/localstack#10257]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently in AWS if we have GraphQL schema that is supposed to return a boolean value for a  property such as `false` if lambda function returns a string value for that property such as `"false"`, AWS AppSync just simply convert that string to boolean such as `false`

In localstack it will return null with a GraphQL error: 
`Boolean cannot represent a non boolean value: 'false'`

### Expected Behavior

Localstack AppSync should convert string values `"true"` or `"false"` to boolean true or `false`

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker-compose.yml

#### Steps to reproduce

1. Create AppSync API with following schema:

```
schema {
  query: Query
}

type Query {
  listGames: [GameItem]
}

type GameItem {
  userId: ID!
  gameId: ID!
  content: String
  attachment: String
  createdAt: String
  isActive: Boolean
}
```

2. Create a simple lambda function that is called by AppSync API that returns following object:
```
export const listGames = async (event: any) => {
  console.log('in listGames');
  console.log("EVENT\n" + JSON.stringify(event, null, 2))
  return [{
    userId: 1,
    gameId: 1,
    content: "New Game",
    attachment: "SampleLogo.png",
    createdAt: "01-01-2024",
    isActive: "false",
  }]
};
```

3. Call the GraphQL API with following body:
```
{
  "query": "{ listGames { userId gameId content attachment createdAt isActive}}"
}
```

Expected Response:
```
{
    "data": {
        "listGames": [
            {
                "userId": "1",
                "gameId": "1",
                "content": "New Game",
                "attachment": "SampleLogo.png",
                "createdAt": "01-01-2024",
                "isActive": false
            }
        ]
    }
}
```

Actual Response:
```
{
    "data": {
        "listGames": [
            {
                "userId": "1",
                "gameId": "1",
                "content": "New Game",
                "attachment": "SampleLogo.png",
                "createdAt": "01-01-2024",
                "isActive": null
            }
        ]
    },
    "errors": [
        {
            "message": "Boolean cannot represent a non boolean value: 'false'",
            "locations": [
                {
                    "line": 1,
                    "column": 58
                }
            ],
            "path": [
                "listGames",
                0,
                "isActive"
            ],
            "errorType": "GraphQLError"
        }
    ]
}
```

### Environment

```markdown
- OS:MacOS
- LocalStack Image: localstack/localstack-pro:latest
```

**Comment by cloutierMat** [comment]
Hello @ahsankarimbhai,

Thank you for reporting this issue. A fix has been merged that will solve it.  It will be available in the next latest image release.

Please do not hesitate to contact us if you have any further questions or encounter new issues.
