### ISSUE TITLE
An error occurred (InternalError) when calling the DescribeImages operation (reached max retries: 2): exception while calling ec2.DescribeImages: bug: <title>

### ISSUE THREAD

**Issue by animesh223** [localstack/localstack#10285]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

LocalStack Pro EC2 instance creation is not working on my MacOs 

<img width="336" alt="Screenshot 2024-02-20 at 5 17 37 PM" src="https://github.com/localstack/localstack/assets/36562085/11369e05-e8a8-459e-85ea-54b1a52537ce">

<img width="991" alt="Screenshot 2024-02-20 at 5 18 19 PM" src="https://github.com/localstack/localstack/assets/36562085/d6d11afc-88c3-416d-af02-45073bd7c765">

### Expected Behavior

Expected to Get the EC2 instance be created as normal

### How are you starting LocalStack?

With the `localstack` script

### Steps To Reproduce

Used the below command and followed the steps as mentioned in https://docs.localstack.cloud/user-guide/aws/elastic-compute-cloud/

awslocal ec2 run-instances \
    --image-id ami-ff0fea8310f3 \
    --count 1 \
    --instance-type t3.nano \
    --key-name my-key \
    --security-group-ids '<SECURITY_GROUP_ID>' \
    --user-data file://./user_script.sh

### Environment

```markdown
- OS: MacOs Monterey
- LocalStack: 3.0.1
```

**Comment by viren-nadkarni** [comment]
Hi @animesh223, could you please provide LocalStack logs when this error occurs, this will help us reproduce and identify the problem? You can run LocalStack with `DEBUG=1` env flag set.
