### ISSUE TITLE
Add missing services to TestUtils and DockerTestUtils as well as async versions of clients

### ISSUE THREAD

**Issue by efenderbosch** [localstack/localstack#1029]
I tried forking with the intent of doing this myself and submitting a pull request, but I can't get it to build. See #1028 

Not a critical issue as it is fairly easy to construct clients for missing services and/or async clients, but it would be nice to have them in the utils.

We're using ``AWSSimpleSystemsManagement`` and ``AmazonSQSAsync`` specifically.

```java
    public AWSSimpleSystemsManagement ssm() {
        return AWSSimpleSystemsManagementClientBuilder.standard().
                withEndpointConfiguration(createEndpointConfiguration(LocalstackDocker.INSTANCE::getEndpointSSM)).
                withCredentials(getCredentialsProvider()).build();
    }
```

and

```java
    public AmazonSQSAsync sqsAsync() {
        return AmazonSQSAsyncClientBuilder.standard().
                withEndpointConfiguration(createEndpointConfiguration(LocalstackDocker.INSTANCE::getEndpointSQS)).
                withCredentials(getCredentialsProvider()).build();
    }
```

Is sufficient to add these to ``DockerTestUtils``

Other changes to make adding services/clients easier for users would be to change ``TestUtils::getEndpointConfiguration`` from ``protected`` to ``public`` and ``DockerTestUtils::createEndpointConfiguration`` from ``private`` to ``public``.

**Comment by netstart** [comment]
For now, I use some think like this...

I holpe it helps


```
import java.util.function.Supplier;

import cloud.localstack.TestUtils;
import cloud.localstack.docker.LocalstackDocker;

public class TestAsyncUtils extends TestUtils {

    public static AmazonDynamoDBAsync getClientDynamoAsyncDB() {
        return AmazonDynamoDBAsyncClientBuilder.standard()
                .withEndpointConfiguration(createEndpointConfiguration(LocalstackDocker.INSTANCE::getEndpointDynamoDB))
                .withCredentials(getCredentialsProvider())
                .build();
    }

    public static AmazonSQSAsync getClientAmazonSQSAsync() {
        return AmazonSQSAsyncClientBuilder.standard()
                .withEndpointConfiguration(createEndpointConfiguration(LocalstackDocker.INSTANCE::getEndpointSQS))
                .withCredentials(getCredentialsProvider())
                .build();
    }

    protected static AwsClientBuilder.EndpointConfiguration createEndpointConfiguration(Supplier<String> supplier) {
        return getEndpointConfiguration(supplier.get());
    }
}

```

**Comment by whummer** [comment]
@efenderbosch It's been a while since you first reported this issue. Do you think you could create a pull request, and we take care of fixing the builds (if the problem still persists)? That would be highly appreciated - thanks!

**Comment by whummer** [comment]
In the meantime, the Java libs have been moved to a separate repo here: https://github.com/localstack/localstack-java-utils , support for Java AWS SDK v2 clients has been added, and a couple of `Async*` client definitions has been added as well. If anything is missing, please feel free to open an issue in the other repo, or please create a pull request there. Thanks for your help.
