### ISSUE TITLE
bug: Deserialize Error APIGW WebSockets API in AWS_PROXY Lambda Function Using Rust

### ISSUE THREAD

**Issue by boymaas** [localstack/localstack#10295]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When using Rust to handle a Lambda function specifically for WebSocket connections, we encounter a `DeserializeError` during runtime. This issue manifests in LocalStack, not when I deploy the version to AWS. indicating a potential inconsistency in handling the WebSocket `requestContext` between AWS and Localstack.
```
ERROR Lambda runtime invoke{requestId="713a1843-ac35-4180-8c23-b328921b27e2" xrayTraceId="Root=1-65d65fce-f53266561295b78ce0df9be9;Parent=a9ed79fdc18dc5a9;Sampled=0"}: DeserializeError { inner: Error { path: Path { segments: [Map { key: "requestContext" }] }, original: Error("missing field connectedAt", line: 1, column: 1112) } }
```

### Expected Behavior

The Lambda function should correctly deserialize the WebSocket event without missing fields, allowing for successful handling of WebSocket requests.

### How are you starting LocalStack?

With the `localstack` script

### Steps To Reproduce

Deploy the Rust-based Lambda function targeting WebSocket connections.
Invoke the function with a WebSocket request.
Observe the DeserializeError related to the requestContext and specifically the connectedAt field.

### Environment

```markdown
- OS: MacOSX
- **Language & Version**: Rust
- **Framework/Library**: AWS Lambda for Rust
- **Deployment**: [Deployed/Version] vs [LocalStack]
- **Version**: Latest
```

**Comment by joe4dev** [comment]
Thank you for reporting this parity issue @boymaas .

Could you share a minimal reproducer sample (ideal) or describe the setup in more detail? In particular:
1. Are you using the API Gateway [WebSocket API](https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-websocket-api.html) with the Lambda integration?
2. I guess you are referring to `$context.connectedAt` as documented [here](https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-websocket-api-mapping-template-reference.html), right?

If so, this is likely an API Gateway issue.

----

**Internal note**: We do have a test in `localstack-ext` for the web socket integration `tests.aws.services.apigateway.test_websocket_apis.TestWebSockets.test_connect_disconnect_always_called` but it transforms `connectedAt`. According to [these AWS docs](https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-websocket-api-mapping-template-reference.html), it should be:
> The [Epoch](https://en.wikipedia.org/wiki/Unix_time)-formatted connection time.

We should validate that it satisfies this format.

**Comment by bentsku** [comment]
Hello @boymaas and thanks a lot for your report!

The fix has now been merged and should be available in `localstack/localstack-pro:latest`. Could you please give it a try by pulling the image and confirm that it works? Thank you!
