### ISSUE TITLE
bug: default for SQS AttributeNames differs from SQS

### ISSUE THREAD

**Issue by shiraWeiss** [localstack/localstack#10302]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If I understand correctly the default is set to "All", but on SQS there's no default and no attribute will be retrieved with the message.
(https://github.com/localstack/localstack/blob/1b5c37c8911f00eb6c6f95fa59a9721d64e4e2d4/localstack/services/cloudformation/models/sqs.py#L96)

This causes a difference on local development vs production, that can only be discovered after deploy.

### Expected Behavior

No default :)

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

Calling receive batch message from SQS

### Environment

```markdown
- OS:
- LocalStack:
```

### Anything else?

hello

**Comment by pinzon** [comment]
Hi @shiraWeiss, I triaged the issue and didn't find anything wrong with the SQS or the Cloudformation deployment. Also there has been a lot new changes in the way resources are deployed. Including the SQS Queues, here is the [code](https://github.com/localstack/localstack/blob/7488c721dea9b3352966a5cf7e80e2c8075b4a66/localstack/services/sqs/resource_providers/aws_sqs_queue.py#L96-L133) for how the resource is deployed now.  

Please try again with the latest version of LocalStack, if you are still encountering the issue please provide more detailed instructions I will be happy to reopen the issue.
