### ISSUE TITLE
bug: CognitoEventUserPoolsPreAuthentication event is not populated with details like UserName

### ISSUE THREAD

**Issue by nsarupumotif** [localstack/localstack#10339]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When a Cognito PreAuth event is triggered (by trying to log in a confirmed user). It is missing the user-name (in the header or the request).
It does have other data like email/sub-id etc.

### Expected Behavior

UserName should be present in the PreAuth event.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

spin up the latest localstack-pro image followed localstack guidelines:
1. create a lambda
2. cognito user pool (with link to preauthentication lambda)
3. cognito client id
4. signup and confirm a user
awslocal cognito-idp sign-up --client-id --username abc_xyz --password XXX --user-attributes Name=email,Value=[test-user@umotif.com](mailto:test-user@umotif.com)
5. Sign in
awslocal cognito-idp initiate-auth --client-id --auth-flow USER_PASSWORD_AUTH --auth-parameters USERNAME=abc_xyz,PASSWORD=XXX

### Environment

```markdown
- OS:MacBook Pro (Darwin)
- LocalStack: localstack-pro (latest) on 27th Feb 2023
```

### Anything else?

AWS specs mention the common parameters must be populated (common params has username)
https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-pre-authentication.html#cognito-user-pools-lambda-trigger-syntax-pre-auth

**Comment by giograno** [comment]
Hi @nsarupumotif, thanks for reporting the issue. We released a fix in the `latest` Docker image. Please let us know if you find any other issues.
