### ISSUE TITLE
enhancement request: Surface performance metrics on a per service basis

### ISSUE THREAD

**Issue by scottiedog45** [localstack/localstack#10348]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Enhancement description

We'd like to confirmation that none of the emulated AWS services are hitting resource or performance issues. Like, is the sqs service getting too inundated with requests? Is dynamo a bottleneck? Etc.

### 🧑‍💻 Implementation

Ideally some way to display or surface the service usage as it relates to the running localstack container. I.e. "Sqs functionality is using all of the resources available to the container..."

**Comment by alexrashed** [comment]
Hi @scottiedog45!
LocalStack is used by quite some heavy users and we take performance issues seriously.
However, the resource monitoring is something LocalStack itself can only do to a limited degree, and honestly also is a bit out of its responsibility as it heavily depends on the container orchestrator / runtime.
Depending on how you use LocalStack (in Docker, in Kubernetes,...) there are different approaches to monitor and limit the resource consumption.
- Running in plain Docker you can monitor the resource consumption with `docker stats`: https://docs.docker.com/config/containers/runmetrics/
- In Kubernetes you can assign resource limits and could use the resource metrics stack to monitor the resource consumption: https://kubernetes.io/docs/tasks/debug/debug-cluster/resource-usage-monitoring/

How are you running LocalStack and how would you want to use this resource metrics?
