### ISSUE TITLE
enhancement request: Add support for RDS BatchExecuteStatement

### ISSUE THREAD

**Issue by jakeleventhal** [localstack/localstack#10350]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Enhancement description

https://docs.localstack.cloud/references/coverage/coverage_rds-data/ Creating this issue to track coverage of BatchExecuteStatement

### 🧑‍💻 Implementation

Shouldn't be that crazy, batch implementation is clearly outlined in the AWS docs https://docs.aws.amazon.com/rdsdataservice/latest/APIReference/API_BatchExecuteStatement.html

**Comment by jakeleventhal** [comment]
@cloutierMat is there a PR or issue link for this?

**Comment by cloutierMat** [comment]
The PR is in a private repo for our `-pro` image features
