### ISSUE TITLE
Localstack Elasticsearch plugin Ingest User Agent Processor not available

### ISSUE THREAD

**Issue by ericbdc** [localstack/localstack#1035]
Plugin `Ingest User Agent Processor` is installed by default for Elasticsearch (ELK) on AWS. It is not the case in Localstack and think we basically expect it.

In addition, I was not able to install it manually through command `bin/elasticsearch-plugin install ingest-user-agent` as bin/elasticsearch-plugin is missing.

**Comment by whummer** [comment]
Thanks for reporting @ericbdc - would you by any chance be able to provide a pull request with a fix? Thanks!
