### ISSUE TITLE
enhancement request: Emulate more of AWS S3 errors (specifically "EntityTooLarge" and "Policy Condition failed")

### ISSUE THREAD

**Issue by caitlinshk** [localstack/localstack#10351]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Enhancement description

Hi there!

My project uses LocalStack to emulate file uploads to AWS S3 using a `<form>` element and it overall works great. But, I've noticed that there's some errors that are only thrown in real AWS, not in LocalStack. This means that I have to wait until we deploy to our staging environment to know when AWS throws errors and what those errors are. It would be nicer if LocalStack could throw the same errors in the same situations so I can (1) not need to deploy to staging to see these errors; and (2) can fix the errors locally and know that my fix works.

The two specific errors I've seen that aren't in LocalStack are:

### EntityTooLarge

We enforce that files uploaded to S3 can have a maximum size by [setting the `"content-length-range"` on the AWS upload request](https://github.com/civiform/civiform/blob/0e9425f85de22f2c15f904c2a70eec8c79aef62b/server/app/services/cloud/aws/SignedS3UploadRequest.java#L330-L346). If a user uploads a file larger than that see, AWS sends this error:
```
<Error>
  <Code>EntityTooLarge</Code>
  <Message>Your proposed upload exceeds the maximum allowed size</Message>
</Error>
```

but LocalStack will let the file upload proceed like normal. See https://github.com/civiform/civiform/issues/5675 and https://github.com/civiform/civiform/issues/6658.

### Policy condition failed
AWS enforces that the value in the `<input name="success_action_redirect">` element matches the value in the `<input name="Policy">` element. If they don't match, AWS sends this error:

```
<Error>
  <Code>AccessDenied</Code>
  <Message>Invalid according to Policy: Policy Condition failed: ["eq", "$success_action_redirect", "https://staging-aws.civiform.dev/programs/92148/blocks/7/updateFile/true/NEXT_BLOCK"]</Message>
</Error>
```
but LocalStack also let the file upload proceed like normal even when they didn't match. See https://github.com/civiform/civiform/issues/6737.

--------------

It'd be amazing if LocalStack could all throw these errors in the right circumstances so I notice these issues immediately instead of only noticing when we deploy to our staging environment with real AWS.

Thanks!
Caitlin

**Comment by bentsku** [comment]
Hello @caitlinshk and thanks a lot for the very detailed comment!

The fix had been merged and was part of the `latest` docker image. It is now also part of our latest release, `3.4`. You can give it a try! Thanks a lot again for the very detailed report. 

Please feel free to report any issue you'd still encounter or use case you might be missing, I'd be very interested to hear about them!

**Comment by caitlinshk** [comment]
Fantastic, thank you so much for adding these errors as part of LocalStack! I am no longer working on CiviForm (very unfortunately :disappointed: ), but I'll let the CiviForm team know in https://github.com/civiform/civiform/issues/6737 that LocalStack now has this feature!
