### ISSUE TITLE
bug: Localstack DNS resolution issues caused by resolv.conf 

### ISSUE THREAD

**Issue by kt-aaronbratt** [localstack/localstack#10356]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We are experiencing an issue resolving any domain from our Localstack container due to the resolv.conf file not respecting DNS entries added to it.  Same issue as the below reported issue from 12/2023. Localstack v3 is not useable with this current bug.
https://github.com/localstack/localstack/issues/9955

### Expected Behavior

I expect to be able to manage the dns of a localstack container as you would with any other docker container.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

Deploy Localstack with Github Codespaces.

### Environment

```markdown
- OS: N/A
- LocalStack: latest
```

**Comment by dfangl** [comment]
Hi @kt-aaronbratt !
The injection of Localstack as a DNS server for itself is indeed wanted and not a bug.
However, it should be using the dns server you configure as an upstream. Can you share if your LocalStack instance prints the line `Determined fallback dns: xx.xx.xx.xx` and does it display the correct DNS you are configuring?
If so, any DNS requests other than those to `localhost.localstack.cloud` will be forwarded to that DNS.

You can of course disable that behavior by setting `DNS_ADDRESS=0` completely. Still, it would be valuable feedback for us to see where your actual issues are!
