### ISSUE TITLE
enhancement request: Addnew  common string functions to vtl renderer

### ISSUE THREAD

**Issue by shucoshuco** [localstack/localstack#10369]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Enhancement description

During the vtl template rendering, only three common string functions are imlemented: trim, toLowerCase and toUpperCase.

I'm trying to render templates with other functions (toString, contains and replaceAll) and rendering is failing.

### 🧑‍💻 Implementation

This can be achieved adding new methods to class ExtendedString into VtlTemplate. I'll create a PR to add this methods.

**Comment by bentsku** [comment]
Closing, thanks again for implementing this! 🙏
