### ISSUE TITLE
bug: Authorization Header missing from Cloudfront Requests

### ISSUE THREAD

**Issue by Garethp** [localstack/localstack#10373]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When hitting a lambda in an RestApi behind a Cloudfront forwarded through `*.localhost.localstack.cloud`, the `Authorization` header seems to be stripped out. If I give it a Domain Name with Route53 and set my `/etc/hosts` to point to localhost for that, the header does appear (although in lowercase, as `authorization`). I'm not quite decided on whether I want to point my DNS to localstack though, so having the redirected domain names work as intended would be nice.

### Expected Behavior

When the request is made through the `*.localhost.localstack.cloud` URL, the Authorization header should be returned

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```ts
export class GatewayStack extends Stack {
  constructor(scope: Construct, id: string, props: StackProps) {
    super(scope, id, props);

    const api = new RestApi(this, "test-api", {
      restApiName: "test-api",
    });

    new Distribution(this, "ApiCloudfront", {
      defaultBehavior: {
        origin: new RestApiOrigin(api),
        allowedMethods: AllowedMethods.ALLOW_ALL,
        cachePolicy: CachePolicy.CACHING_DISABLED,
        originRequestPolicy: OriginRequestPolicy.ALL_VIEWER,
        viewerProtocolPolicy: ViewerProtocolPolicy.HTTPS_ONLY,
      },
    });

    const lambda = new Function(this, "lambda-handler", {
      runtime: Runtime.NODEJS_20_X,
      handler: "index.handler",
      code: Code.fromInline(
        "exports.handler = async (event) => ({statusCode: 200, body: JSON.stringify(event.headers, null, 4) })",
      ),
    });

    api.root.addMethod("GET", new LambdaIntegration(lambda));
  }
}
```

```sh
curl -H "Authorization: Bearer test" "https://$(awslocal cloudfront list-distributions | jq .DistributionList.Items[0].DomainName -r)"
```

### Environment

```markdown
- OS: Ubuntu 20.04
- LocalStack: 3.2
```

### Anything else?

I've replicated this bug here: https://github.com/Garethp/localstack-bugs/tree/no-authorization-header

If you clone the repo, check out the `no-authorization-header` branch and run `yarn install && ./start.sh` you should see that the response has the `Authorization` header stripped out

**Comment by bentsku** [comment]
Hello @Garethp and thanks again for your report! This issue should also be fixed with 3.3 and `latest`. Could you give it a try and validate that it fully fixes it for you in your entire setup? Thanks!
