### ISSUE TITLE
DynamoDB DeleteTable does not delete global tables

### ISSUE THREAD

**Issue by cloudtest-anon** [localstack/localstack#10376]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

- The DeleteTable API does not appear to remove the global table states.
- Creating a new global table with the same name results in a conflict.
- Listing global tables still shows the name of the deleted global table.

### Expected Behavior

- The global table should be deleted.

### How are you starting LocalStack?

With a `docker run` command

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    dynamodb = boto3.client('dynamodb', endpoint_url='http://localhost:4566', region_name='us-west-2')
    table = dynamodb.create_table(
          TableName='testtable',
          KeySchema=[
              {
                  'AttributeName': 'Id',
                  'KeyType': 'HASH'
              }
          ],
          AttributeDefinitions=[
              {
                  'AttributeName': 'Id',
                  'AttributeType': 'S'
              }
          ],
          ProvisionedThroughput={
              'ReadCapacityUnits': 5,
              'WriteCapacityUnits': 5
          }
      )
  
    table = dynamodb.create_global_table(
    GlobalTableName='testtable',
    ReplicationGroup=[
              {
                  'RegionName': 'us-west-2'
              },
          ]
     )
    
    resp = dynamodb.delete_table(
           TableName='testtable'
     )
     
    response = dynamodb.list_global_tables()
    print(response)

    > {'GlobalTables': [{'GlobalTableName': 'testtable', 'ReplicationGroup': [{'RegionName': 'us-west-2'}]}], 'ResponseMetadata': {'RequestId': 'd8143bd7-45ae-4eb1-abf6-1369fc02a7ec', 'HTTPStatusCode': 200, 'HTTPHeaders': {'content-type': 'application/x-amz-json-1.0', 'content-length': '103', 'x-amzn-requestid': 'd8143bd7-45ae-4eb1-abf6-1369fc02a7ec', 'x-amz-crc32': '145461334', 'connection': 'close', 'date': 'Fri, 01 Mar 2024 20:09:50 GMT', 'server': 'hypercorn-h11'}, 'RetryAttempts': 0}}
   
 

### Environment

```markdown
- OS: Ubuntu 22.04.2 LTS
- LocalStack: 3.2.0
- boto3: 1.28.6
```

**Comment by viren-nadkarni** [comment]
Hi @anna-mazhar, the `CreateGlobalTable` operation applies to version 2017.X of global tables. LocalStack only supports version 2019.X.

Please see [this note](https://docs.localstack.cloud/user-guide/aws/dynamodb/#global-tables) in the documentation.
