### ISSUE TITLE
enhancement request: Support XML templating in API Gateway

### ISSUE THREAD

**Issue by shucoshuco** [localstack/localstack#10380]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Enhancement description

Currently, API Gateway templating only supports JSON templates. There is a TODO comment in the code related to this enhancement.
Because they are the most common media types, I'd say it's an interesting option add also support for XML templating. 

### 🧑‍💻 Implementation

Two changes are required:
* Read the Accept header in order to decide which template we must apply to a response
* Add validation for XML response, the same as already exists for JSON responses

### Anything else?

Link to the TODO comment: https://github.com/localstack/localstack/blob/76292e1d01d3141cbedfc0aea9f7b36095d6a23a/localstack/services/apigateway/templates.py#L325

**Comment by bentsku** [comment]
Closed via #10381, thanks again for your contribution!
