### ISSUE TITLE
bug: ACM-PCA doesn’t honour validity dates

### ISSUE THREAD

**Issue by lenormf** [localstack/localstack#10405]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Certificates issued by LocalStack do not have the expected validity date.

The `Not After` date was set to exactly one year from the date of issuance, when providing with the “forever” absolute value [defined by RFC5280](https://datatracker.ietf.org/doc/html/rfc5280#section-4.1.2.5).

Also reproduced with a validity date set 3 years ahead.

### Expected Behavior

LocalStack should honour the validity date provided by requests, even the “forever” absolute value [defined by RFC5280](https://datatracker.ietf.org/doc/html/rfc5280#section-4.1.2.5).

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```console
$ awslocal acm-pca issue-certificate --certificate-authority-arn '…' --csr file://test_cert_.csr --signing-algorithm SHA256WITHRSA --validity Value=253402300799,Type="ABSOLUTE" --idempotency-token 1234
    {
        "CertificateArn": "arn:aws:acm-pca:eu-west-1:000000000000:certificate-authority/64bb6589-3f18-4f38-8c1c-8a93592ac101/certificate/9b4d38f134574fa58119c3ce7a4c3be9"
    }
```

```console
$ awslocal acm-pca get-certificate --certificate-authority-arn '…' --certificate-arn '…' | jq -r .Certificate | openssl x509 -text -noout
    Certificate:
        Data:
            Version: 3 (0x2)
            Serial Number:
                19:d0:95:8a:ac:db:f1:e6:cb:e6:33:72:17:91:23:94:bb:8c:2e:d4
            Signature Algorithm: sha512WithRSAEncryption
            Issuer: C = US, O = Amazon, OU = Server CA 1B, CN = 
            Validity
                Not Before: Mar  6 14:37:22 2024 GMT
                Not After : Mar  6 14:37:22 2025 GMT
[…]
```

### Environment

```markdown
- OS: Ubuntu 20.04
- LocalStack: `latest`
```

**Comment by frank-lenormand** [comment]
Re-opened as #10406.
