### ISSUE TITLE
Incompatible response of AWS S3 HeadBucket API

### ISSUE THREAD

**Issue by quangphamqonto** [localstack/localstack#1040]
Hi guys,

I found an incompatible response code for AWS S3 HeadBucket API. 

When we send this request to AWS, if the bucket is not found, it should return error code = "NoSuchBucket", but  localstack is returning "NotFound" instead.

**Comment by whummer** [comment]
Thanks for reporting @quangphamqonto . I'm unable to reproduce the issue you're describing. See the following commands against real AWS:
```
$ aws s3api head-bucket --bucket foobar-non-existing-bucket

An error occurred (404) when calling the HeadBucket operation: Not Found
```
```
$ aws --debug s3api head-bucket --bucket foobar-non-existing-bucket 2>&1 | grep NoSuchBucket
(no output)
```

Not entirely sure if this behavior may have changed on AWS. Closing this issue as "cannot reproduce" - please report here with detailed instructions on how to reproduce if the problem persists. Thanks

**Comment by ryan-gerstenkorn-sp** [comment]
Not sure if this is the same issue I ran into, I was getting this output when using things like ListBucket which I don't believe should return this message. Turned out the issue was I wasn't signing the requests, you can reproduce this with --no-sign-request on the cli.

```
$ aws s3 --no-sign-request --profile=local --endpoint-url=http://localhost:4566 ls                       

An error occurred (404) when calling the ListBuckets operation: Not Found
$ aws s3 --profile=local --endpoint-url=http://localhost:4566 ls                   
2020-07-04 00:58:56 asdf
```

**Comment by ryan-gerstenkorn-sp** [comment]
Opened https://github.com/localstack/localstack/issues/2671 on this.
