### ISSUE TITLE
bug: Headers aren't being transformed into Title Case the way that they are in AWS

### ISSUE THREAD

**Issue by Garethp** [localstack/localstack#10437]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When you send a request to API Gateway in LocalStack with the header "authorization" in lower-case, it's not being transformed into the title case "Authorization".

### Expected Behavior

Accord to the [AWS Documentation for API Gateway](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-known-issues.html) headers are case-sensitive, not insensitive. Furthermore, if you try to ping an API Gateway behind a Cloudfront with a lower-case header for something like "Authorization" then it gets transformed before reaching the handler Lambda. That means that in AWS, if you send a request with the header "authorization" then it gets recieved as "Authorization"

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```ts
export class GatewayStack extends Stack {
  constructor(scope: Construct, id: string, props: StackProps) {
    super(scope, id, props);

    const api = new RestApi(this, "test-api", {
      restApiName: "test-api",
    });

    new Distribution(this, "ApiCloudfront", {
      defaultBehavior: {
        origin: new RestApiOrigin(api),
        allowedMethods: AllowedMethods.ALLOW_ALL,
        cachePolicy: CachePolicy.CACHING_DISABLED,
        originRequestPolicy: OriginRequestPolicy.ALL_VIEWER,
        viewerProtocolPolicy: ViewerProtocolPolicy.HTTPS_ONLY,
      },
    });

    const lambda = new Function(this, "lambda-handler", {
      runtime: Runtime.NODEJS_20_X,
      handler: "index.handler",
      code: Code.fromInline(
        "exports.handler = async (event) => ({statusCode: 200, body: JSON.stringify(event.headers, null, 4) })",
      ),
    });

    api.root.addMethod("GET", new LambdaIntegration(lambda));
  }
}
```

```sh
curl -H "authorization: Bearer test" "https://$(awslocal apigateway get-rest-apis | jq .items[0].id -r).execute-api.localhost.localstack.cloud:4566/prod/"
```

### Environment

```markdown
- OS: Ubuntu 20.04
- LocalStack: 3.2
```

### Anything else?

I've replicated this bug here: https://github.com/Garethp/localstack-bugs/tree/headers-incorrect-case

If you clone the repo, check out the no-authorization-header branch and run yarn install && ./start.sh you should see that the response has the authorization in lower-case.

While this is a strange edge-case that I don't expect many to run into, we ran into this because we're using Cypress for our integration/smoke tests and Cypress has a bug they've decided not to fix where [the headers for requests made while running cypress are transformed into lower-case](https://github.com/cypress-io/cypress/issues/2879). They've decided not to fix this because HTTP Spec says headers are case-insensitive, which normally isn't an issue except for in this situation. When running our tests against our deployed AWS Environments the headers are transformed into a case-sensitive format for reading by our lambda (which we do to pull info from the header). This results in the case where our automated tests will pass against a deployed AWS environment but not a deployed LocalStack one.

Due to my testing environment, I'm only able to test AWS behavior through a Cloudfront sitting in front of an API Gateway rather than the API Gateway directly, so it may be worth double checking.

**Comment by bentsku** [comment]
Hello @Garethp and thanks again for your report! This issue should now be fixed and part of LocalStack 3.3 and `latest`. Could you give it a try and see if that fixes it for you? Thanks!

**Comment by Garethp** [comment]
Thanks for that @bentsku! I can confirm that it works in the isolated test that I set up, but I'm blocked from testing it against our larger application due to #10554

**Comment by bentsku** [comment]
Hi @Garethp! I'll close this issue as it should be fixed, and hopefully the other reported issue will be fixed in the near future. Thanks again for the report!
