### ISSUE TITLE
enhancement request: update aws sdk v3 in lambda runtime

### ISSUE THREAD

**Issue by joshbalfour** [localstack/localstack#10439]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Enhancement description

Please can you update the aws sdk v3 that are available at lambda runtime? I'm raising this as in October last year [an update went in](https://github.com/aws/aws-sdk-js-v3/issues/5364#issuecomment-1769093842) to support endpoint injection via environment variables, which is useful if you don't want to use the transparent DNS injection provided by localstack.

This will avoid us having to bundle them in the updated version to get the update.

### Anything else?

Big fan of the project 😄 Appreciate it

**Comment by joe4dev** [comment]
Hi @joshbalfour 

We strive for high [parity with AWS](https://web.archive.org/web/20240210010958/https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html) and therefore restrain from unnecessarily modifying the [official Lambda runtime images](https://github.com/aws/aws-lambda-base-images) from AWS, including the specific SDK version used for a given Lambda runtime. The AWS [Lambda runtimes](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html) page used to show the SDK version, but AWS recently removed this information (previous example https://web.archive.org/web/20240210010958/https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html). We don't want to break this parity with an unexpected SDK update. I hope this makes sense.

The new `AWS_ENDPOINT_URL` configuration is a great new feature we welcome 📈 .

Bundling a desired version of the SDK (possibly via a layer) or using transparent endpoint injection are both viable solutions.

Thanks for the shout-out 🙌
