### ISSUE TITLE
Unable to create a cluster

### ISSUE THREAD

**Issue by bgadicha1** [localstack/localstack#10442]
Unable to create a cluster by using this command
aws eks create-cluster   --name cluster1   --role-arn "arn:aws:iam::000000000000:role/eks-role"   --resources-vpc-config "{}" --endpoint-url=http://localhost:4566

The cluster is getting created in FAILED state immediately. Tried the UI route as well. same result. (Yes, I picked the role which exists)

**Comment by MarcelStranak** [comment]
Hello @bgadicha1,
Kindly provide us with the necessary information for the bug report based on our template, or alternatively, please close this issue and utilize the template to initiate a new one. 

Thank you.

For the bug report template, please follow this link: https://github.com/localstack/localstack/issues/new/choose

**Comment by bgadicha1** [comment]
Ok logged another issue following the template. Closing this.
