### ISSUE TITLE
mwaa container is missing java

### ISSUE THREAD

**Issue by don1uppa** [localstack/localstack#10447]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The real aws mwaa has a java package installed and I need that.
JAVA_HOME=/usr/lib/jvm/java-17-amazon-corretto.x86_64
They don't set JAVA_HOME but the code is there and you should emulate it.
my startup script sets JAVA_HOME by doint this:
eval $(java -XshowSettings:properties -version 2>&1 > /dev/null | sed -e '/java.home/!d' -e's/.*= /export JAVA_HOME="/' -e 's/$/&"/')

### Expected Behavior

Java should be there.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce
Run  a dag that does a bas command of:

  eval $(java -XshowSettings:properties -version 2>&1 > /dev/null | sed -e '/java.home/!d' -e's/.*= /export

**Comment by viren-nadkarni** [comment]
Hi @don1uppa, we have updated the LocalStack MWAA runners. They are now bundled with java-corretto 17. Please pull the most recent [Docker images](https://hub.docker.com/r/localstack/airflow/tags).
