### ISSUE TITLE
bug: Getting error when creating a repository

### ISSUE THREAD

**Issue by bgadicha1** [localstack/localstack#10449]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am trying to create a repository from the localstack UI. It goes well, but when i try to see the contents of the repository or try to push an image into it, I get this error in the logs.
 exception during call chain: 'NoneType' object has no attribute 'get_registry_endpoint'
After this, I cannot even delete that repository.

### Expected Behavior

I should be able to push the docker images into the created repository.
When I click the repository, I should not get the error message " exception during call chain: 'NoneType' object has no attribute 'get_registry_endpoint'"

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

./ localstack.exe start

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)
docker tag baffle-manager-v4:Release-Baffle.2.8.1.5 localhost.localstack.cloud:4511/baffle-manager-v4:Release-Baffle.2.8.1.5
docker push localhost.localstack.cloud:4511/baffle-manager-v4:Release-Baffle.2.8.1.5

 

### Environment

```markdown
- OS:Win11
- LocalStack:Pro
```

### Anything else?

![ls_image](https://github.com/localstack/localstack/assets/160370387/64be6543-57c6-4560-97d3-cd6c25cdd22b)

**Comment by bgadicha1** [comment]
It creates fine if I use immutable option. It fails if I use mutable. Is that expected behavior?

**Comment by MarcelStranak** [comment]
Hi @bgadicha1, please update to the [latest version of LocalStack Docker image](https://hub.docker.com/r/localstack/localstack-pro/tags). I am unable to reproduce your issue any more.
