### ISSUE TITLE
bug: api gateway v2 (pro) - entire query string not proxied on POST requests if :// is in any values in the query string

### ISSUE THREAD

**Issue by joshbalfour** [localstack/localstack#10451]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When proxying requests with API gateway, the query string doesn't make it through to the destination when in localstack, but on AWS it does

### Expected Behavior

The query string makes it to the destination

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)
localstack:
    container_name: "localstack-main"
    image: localstack/localstack-pro
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN:?}  # required for Pro
      - DISABLE_CORS_CHECKS=1
      - DISABLE_CUSTOM_CORS_APIGATEWAY=1
      - EXTRA_CORS_ALLOWED_HEADERS=x-edgeapi-session-id
      - DISABLE_TRANSPARENT_ENDPOINT_INJECTION=1
    volumes:
      - "./volume:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

### Environment

```markdown
- OS: macOS 14.1.1 (23B81)
- LocalStack: latest
```

**Comment by bentsku** [comment]
Hello @joshbalfour and thanks for your report!

Could you maybe give a little more information about the setup? What kind of integration are you using and with what parameters? Maybe a minimal reproducible sample just showing the behavior would be great.
Thanks!

**Comment by joshbalfour** [comment]
I've managed to reproduce it with this cloudformation:

```json
{
 "Resources": {
  "apiC8550315": {
   "Type": "AWS::ApiGatewayV2::Api",
   "Properties": {
    "Name": "repro",
    "ProtocolType": "HTTP"
   },
   "Metadata": {
    "aws:cdk:path": "repro/api/Resource"
   }
  },
  "apiDefaultStage04B80AC9": {
   "Type": "AWS::ApiGatewayV2::Stage",
   "Properties": {
    "ApiId": {
     "Ref": "apiC8550315"
    },
    "AutoDeploy": true,
    "StageName": "$default"
   },
   "Metadata": {
    "aws:cdk:path": "repro/api/DefaultStage/Resource"
   }
  },
  "apiANYreproproxyintegration21D3F2DD": {
   "Type": "AWS::ApiGatewayV2::Integration",
   "Properties": {
    "ApiId": {
     "Ref": "apiC8550315"
    },
    "IntegrationMethod": "ANY",
    "IntegrationType": "HTTP_PROXY",
    "IntegrationUri": {
      "Fn::Join": [
       "",
       [
        "https://",
        {
         "Fn::Join": [
          "",
          {
           "Fn::Split": [
            "https://",
            "https://xyz123.m.pipedream.net"
           ]
          }
         ]
        },
        "/token"
       ]
      ]
     },
     "PayloadFormatVersion": "1.0",
     "RequestParameters": {
      "overwrite:header.host": {
       "Fn::Join": [
        "",
        {
         "Fn::Split": [
          "https://",
          "https://xyz123.m.pipedream.net"
         ]
        }
       ]
      }
     }
   },
   "Metadata": {
    "aws:cdk:path": "repro/api/ANY--repro/proxy-integration/Resource"
   }
  },
  "apiANYreproDA1DE77E": {
   "Type": "AWS::ApiGatewayV2::Route",
   "Properties": {
    "ApiId": {
     "Ref": "apiC8550315"
    },
    "AuthorizationType": "NONE",
    "RouteKey": "ANY /repro",
    "Target": {
     "Fn::Join": [
      "",
      [
       "integrations/",
       {
        "Ref": "apiANYreproproxyintegration21D3F2DD"
       }
      ]
     ]
    }
   },
   "Metadata": {
    "aws:cdk:path": "repro/api/ANY--repro/Resource"
   }
  },
  "CDKMetadata": {
   "Type": "AWS::CDK::Metadata",
   "Properties": {
    "Analytics": "v2:deflate64:H4sIAAAAAAAA/12OwQ7CIBBEv8V7WYWD6dV40Wv9AIN0JdsqNLC0MY3/LpSbp5k3eYdRIFULh51eojD9KF70gPXG2oxNnu56IqsZF/2ZFawX5uk0UXN+uhIFs2qxDLWUqfOJa7s6Rhs0k3dF+cPN+24No0/BZHC+RxjifpYtyGP+NUQiEZJjeiN0NX9HuR3ktAAAAA=="
   },
   "Metadata": {
    "aws:cdk:path": "repro/CDKMetadata/Default"
   }
  }
 },
 "Parameters": {
  "BootstrapVersion": {
   "Type": "AWS::SSM::Parameter::Value<String>",
   "Default": "/cdk-bootstrap/hnb659fds/version",
   "Description": "Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]"
  }
 },
 "Rules": {
  "CheckBootstrapVersion": {
   "Assertions": [
    {
     "Assert": {
      "Fn::Not": [
       {
        "Fn::Contains": [
         [
          "1",
          "2",
          "3",
          "4",
          "5"
         ],
         {
          "Ref": "BootstrapVersion"
         }
        ]
       }
      ]
     },
     "AssertDescription": "CDK bootstrap stack version 6 required. Please run 'cdk bootstrap' with a recent version of the CDK CLI."
    }
   ]
  }
 }
}
```

**Comment by joshbalfour** [comment]
ok i've tracked it down, it has nothing to do with the stack at all, it's that if there's a `://` in the url it will remove the entire query string

e.g.
```sh
curl 'https://cda191a2.execute-api.localhost.localstack.cloud:4566/repro?redirect_uri=http://localhost:3001/example-client/success' -X POST 
```

results in `POST /repro` being proxied, as does 
```sh
curl 'https://cda191a2.execute-api.localhost.localstack.cloud:4566/repro?redirect_uri=://' -X POST 
```

but (notice no colon in the redirect_uri)
```sh
curl 'https://cda191a2.execute-api.localhost.localstack.cloud:4566/repro?redirect_uri=http//localhost:3001/example-client/success' -X POST 
```

proxies `POST /repro?redirect_uri=http//localhost:3001/example-client/success` just fine

**Comment by bentsku** [comment]
Hi @joshbalfour and thanks for the detailed steps! I'm currently working on it, I can confirm the issue.
Funny enough, if you URL-encode your query string parameters, it might not occur, I had trouble reproducing the issue with Python in the beginning, because it would URL-encode the parameter and I could not reproduce the issue. 

I'll keep you updated on the fix! Thanks again.

**Comment by joshbalfour** [comment]
@bentsku Thanks so much for fixing this so quickly, absolute legend 🚀

**Comment by bentsku** [comment]
Thanks for the kind words and the really nice investigation, helped a lot in zeroing on the issue 😄
