### ISSUE TITLE
bug: API Gateway Proxy does not forward the backend response code (always returns 200)

### ISSUE THREAD

**Issue by dmitriyklyuzov** [localstack/localstack#10461]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The LocalStack-based API Gateway does not forward the HTTP code from the backend and instead always returns a 200 response, regardless of what the backend response code was:
![Screenshot 2024-03-14 at 10 20 17 AM](https://github.com/localstack/localstack/assets/5950326/ae2f4df9-9537-42b4-9416-74394e2fcd1d)

### Expected Behavior

According to the [AWS Documentation](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-method-settings-method-response.html), _For proxy integrations, API Gateway automatically passes the backend response to the method response._ In other words, if the backend is returning an HTTP 401, the API Gateway should also return a 401 (not 200), as confirmed when deploying the same infrastructure to AWS:
![Screenshot 2024-03-14 at 10 20 21 AM](https://github.com/localstack/localstack/assets/5950326/bf6ae810-27d4-4a9c-840c-43a5e36666f5)

### How are you starting LocalStack?

With a `docker run` command

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Terraform code
```
resource "aws_api_gateway_rest_api" "root" {
  name        = "test-api-gw"
  description = "Test API Gateway"
}

resource "aws_api_gateway_resource" "icat_resource" {
  rest_api_id = aws_api_gateway_rest_api.root.id
  parent_id   = aws_api_gateway_rest_api.root.root_resource_id
  path_part   = "icat"
}

resource "aws_api_gateway_resource" "icat_proxy" {
  rest_api_id = aws_api_gateway_rest_api.root.id
  parent_id   = aws_api_gateway_resource.icat_resource.id
  path_part   = "{proxy+}"
}

resource "aws_api_gateway_method" "icat_api_method" {
  rest_api_id   = aws_api_gateway_rest_api.root.id
  resource_id   = aws_api_gateway_resource.icat_proxy.id
  http_method   = "ANY"
  authorization = "NONE"

  request_parameters = {
    "method.request.path.proxy" = true
  }
}

resource "aws_api_gateway_integration" "icat_integration" {
  rest_api_id             = aws_api_gateway_rest_api.root.id
  resource_id             = aws_api_gateway_resource.icat_proxy.id
  http_method             = aws_api_gateway_method.icat_api_method.http_method
  integration_http_method = "ANY"
  type                    = "HTTP_PROXY"
  uri                     = "<any public endpoint that does not return a 200>"

  request_parameters = {
    "integration.request.path.proxy" = "method.request.path.proxy"
  }
}

resource "aws_api_gateway_method_response" "icat_method_response" {
  rest_api_id = aws_api_gateway_rest_api.root.id
  resource_id = aws_api_gateway_resource.icat_proxy.id
  http_method = aws_api_gateway_method.icat_api_method.http_method
  status_code = "200"

  response_models = {
    "application/json" = "Empty"
  }
}

resource "aws_api_gateway_integration_response" "icat_integration_response" {
  rest_api_id = aws_api_gateway_rest_api.root.id
  resource_id = aws_api_gateway_resource.icat_proxy.id
  http_method = aws_api_gateway_method.icat_api_method.http_method
  status_code = aws_api_gateway_method_response.icat_method_response.status_code
}

resource "aws_api_gateway_deployment" "icat_deployment" {
  depends_on = [
    aws_api_gateway_method_response.icat_method_response,
    aws_api_gateway_integration_response.icat_integration_response,
  ]

  rest_api_id = aws_api_gateway_rest_api.root.id
  stage_name  = "local"
}

output "api_gateway_execution_url" {
  value = "https://${aws_api_gateway_rest_api.root.id}.execute-api.localhost.localstack.cloud:4566/local/"
}

```

Init && apply
`tflocal init && tflocal apply`

### Environment

```markdown
- OS: MacOS
- LocalStack: latest
```

**Comment by dmitriyklyuzov** [comment]
Thanks for fixing this! Any ETA on when this will be released?

**Comment by cloutierMat** [comment]
Hi @dmitriyklyuzov, Thank you for bringing that issue to our attention.
The fix should already be available in the `latest` Docker image.

**Comment by dmitriyklyuzov** [comment]
hi @cloutierMat awesome - just confirmed this works. Thanks!
