### ISSUE TITLE
bug: ContentBasedDeduplication with DeduplicationScope in FIFO queue not working as expected

### ISSUE THREAD

**Issue by CSandyHub** [localstack/localstack#10460]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I created an SQS FIFO queue with ContentBasedDeduplication set to true and DeduplicationScope as messageGroup.

When i try to send 2 messages with same message body but with different message group id , only one message is present in the queue

The MessageId remains same for each send-message response

### Expected Behavior

with ContentBasedDeduplication set to true and DeduplicationScope as messageGroup, sending 2 messages with same message body but with different message group id should result in two messages being in the queue

The MessageId changes for each send-message response

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker-compose up -d localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

1. First create SQS FIFO queue with the following command
```
awslocal sqs create-queue --region eu-central-1 --queue-name test-local-task-queue.fifo --attributes \
'{"FifoQueue":"true","ContentBasedDeduplication":"true","FifoThroughputLimit":"perQueue","DeduplicationScope":"messageGroup","VisibilityTimeout":"30","MessageRetentionPeriod":"345600"}'
```

2. Send a message to the queue with message group id G1

```
awslocal sqs send-message --queue-url http://localhost:4566/000000000000/test-local-task-queue.fifo --message-body A --message-group-id G1
```

4. Send a message to the queue with message group id G2

```
awslocal sqs send-message --queue-url http://localhost:4566/000000000000/test-local-task-queue.fifo --message-body A --message-group-id G2
```

5. Receive messages from the queue 

```
awslocal sqs receive-message --queue-url http://localhost:4566/queue/eu-central-1/000000000000/test-local-task-queue.fifo
```

### Environment

```markdown
- OS: MacOs
- LocalStack: latest
```

### Anything else?

When the same queue is created in AWS and if two messages with same body for different groups are sent, then you can see two messages in the queue 

![image](https://github.com/localstack/localstack/assets/63361965/359dfbfa-7431-4323-86f8-37e87f37fbd8)

**Comment by baermat** [comment]
Hello! We recently implemented some fixes regarding FIFO message group visibility. Please try to pull the latest version and tell us if that resolves your issue. Thank you!

**Comment by CSandyHub** [comment]
Hello @baermat , i have just tried it with the latest image and the issue still exists
