### ISSUE TITLE
bug: API Gateway works with GET HTTP integration method for Lambda Proxy, when it should only be POST

### ISSUE THREAD

**Issue by tinyg210** [localstack/localstack#10473]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

API Gateway will proxy requests to a Lambda function using the GET integration HTTP method, which does not work under normal circumstances on AWS. Trying to call the Lambda through the dedicated endpoint will result in an `Internal server error` message on AWS.

### Expected Behavior

Only the POST integration HTTP Method should be permitted for proxying requests to a Lambda.
The reason why this is important is that this is an essential configuration, and users who rely on LocalStack to test their infrastructure provisioning tools rely on this.
The [documentation](https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-lambda-proxy-integrations.html) is complex and ambiguous, but here's the important part:
<img width="706" alt="Screenshot 2024-03-17 at 23 30 54" src="https://github.com/localstack/localstack/assets/49899593/dad20533-9215-49bb-96fa-8cee5e255c11">

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

1. Clone the repo: https://github.com/localstack-samples/cloud-pods-collaboration-demo
2. Run `docker compose up`
3. Navigate to `terraform/main.tf`
4. Find the resource `"aws_iam_policy" "lambda_dynamodb_policy"` and uncomment the action  `"dynamodb:GetItem"`.
5. Find the resource `"aws_api_gateway_integration" "get_product_integration"` and modify the `integration_http_method` from POST to GET 
[The previous 2 steps exist because this repo demos a different feature]
6. Run the Terraform config file using `terraform-local`. There's a script in the same folder that covers all steps (run-tflocal.sh)
7. In the root folder, run the `invoke.sh` script. It does 3 curl calls: POST, POST, GET -- the last one should fail
8. The output of the script is:
`Product added/updated successfully. Product added/updated successfully. {"price":"29.99","name":"EcoFriendly Water Bottle","description":"A durable, eco-friendly water bottle designed to keep your drinks cold for up to 24 hours and hot for up to 12 hours. Made from high-quality, food-grade stainless steel, it's perfect for your daily hydration needs.","id":"34534"}⏎  `
And it should be:
`Product added/updated successfully. Product added/updated successfully. Internal server error⏎`
Because the last method should not work.

### Environment

```markdown
- OS: macOS Sonoma 14.4
- LocalStack: LocalStack Pro 3.2.0
```

**Comment by cloutierMat** [comment]
Fixed by #10512
