### ISSUE TITLE
Lambda CloudFormation - Missing Environment Variables

### ISSUE THREAD

**Issue by fivepapertigers** [localstack/localstack#1049]
When specifying a `AWS::Lambda::Function` in a CloudFormation configuration, the `Environment` variable map is not registered for the function.

I chased down the source code, and it seems like the issue is in `moto` (see https://github.com/spulec/moto/issues/1994). I figured I would record the issue here as well to record the need to upgrade the dependency in this library once that's fixed.

**Comment by flintinatux** [comment]
From what I can tell, this is still broken. @fivepapertigers, I found where your PR was merged in `moto`, but I don't think a new version has been released.

I also want to note that I'm seeing the same behavior when using the CLI to set env vars.  For example:

```sh
$ awslocal lambda update-function-configuration --function-name test --environment "{\"Variables\":{\"FOO\":\"bar\"}}"
$ awslocal lambda get-function-configuration --function-name test
{
    "FunctionName": "test",
    "FunctionArn": "arn:aws:lambda:us-east-1:000000000000:function:test",
    "Runtime": "nodejs8.10",
    "Handler": "src/index.handler",
    "CodeSize": 50,
    "Version": "$LATEST",
    "Environment": {}
}
```

**Comment by whummer** [comment]
Thanks for reporting @fivepapertigers  @flintinatux . There have been some enhancements in the CloudFormation implementation recently - can you please give it a try with the latest version on `master`?

**Comment by whummer** [comment]
Should have been fixed in the meantime, closing. Please re-open if the problem persists. Thanks
