### ISSUE TITLE
enhancement request: Additional Logging Configuration Flags

### ISSUE THREAD

**Issue by adinballew** [localstack/localstack#10494]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Steps to reproduce:
```docker-compose.yaml
  localstack:
    environment:
      # Logging
      - DEBUG=1
      - LS_LOG=debug # debug, info, warn, error, trace
```

Starting some version after `localstack:3.0.2` we started seeing some log outputs we would like the ability to disable. 

## Proposed Solution:
Add additional configuration flags to toggle the verbosity of these logs:
`localstack-main | xxxx-xx-xxxxxxxx DEBUG --- [  asgi_gw_11] rolo.gateway.wsgi          : POST localhost:4566/`

The `POST localhost:4566/` outputs at a very short interval and doesn't seem to provide much value to the debug log stream.

### 🧑‍💻 Implementation

The most simplistic solution would be to add another flag to the `docker-compose.yml` to disable this output. Maybe disabling these logs from the wsgi service. This could look something like:
```docker-compose.yaml
  localstack:
    environment:
      # Logging
      - DEBUG=1
      - LS_LOG=debug # debug, info, warn, error, trace
      - WSGI_LOGGING=error # or false for disabling entirely
```
   
However, the logs we care to see in this instance come from the lambdas running in localstack that use boto3. Another solution would be changing the log level that dockerized services such as lambda get output to. This could look something like:
```docker-compose.yaml
  localstack:
    environment:
      # Logging
      - DEBUG=1
      - LS_LOG=debug # debug, info, warn, error, trace
      -LAMBDA_LOG_LEVEL=info
```

**Comment by thrau** [comment]
thanks for the suggestion Adin @adinballew. an overhaul of logging is on the roadmap, and part of that will be more fine-grained loglevels. i can't give an ETA on that yet, but regardless we can look into a way to at least configure log-levels of individual loggers
