### ISSUE TITLE
SQS trigger lambda not in expected schema format

### ISSUE THREAD

**Issue by israelItzhakov** [localstack/localstack#10513]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have API GW RESET  that triggers SQS 
SQS triggers a  lambda
I print the event  from SQS and  I get this result

```
    body: '[{"userId":"5SyQgpjPSd","tenantId":"israel6686","deviceIdentifier":"agent-gKmUNApnH74U","message":{"_id":"UBgVCJXnwO","tenantId":"israel6686","userId":"5SyQgpjPSd","_created_at":"2024-02-11T12:32:26.753Z","bypassRules":[{"id":"WZx4nXpHpV","name":"Internal `Resources","status":"active","priority":"0","sources":[{"type":"users","value":[]},{"type":"groups","value":[]},{"type":"applications","value":[]}],"destinations":[{"type":"domains","value":["perimeter81.com","perimeter81.biz","perimeter81.in","safersoftware.net","cdn.auth0.com","cdn.eu.auth0.com","perimeter81-frontend-assets.s3.amazonaws.com","portal.checkpoint.com"]},{"type":"addresses","value":[]},{"type":"categories","value":[]}],"_created_at":"2024-02-11T11:34:44.644Z","_updated_at":"2024-02-11T11:34:44.646Z","tenantId":"israel6686"}],"enabled":false,"groupsOfUser":["JiguEDJDA1"],"rewarn` period":432      receiptHandle: 'ZDBkNjYwYzEtNjg1OC00M2Y3LTg2NDgtYWJiMmUyMzVkMjJjIGFybjphd3M6c3FzOnVzLWVhc3QtMTowMDAwMDAwMDAwMDA6bG9jYWwtc2RwdjItYWdlbnQtc3FzLXB1c2hlciBmYmZiZjQ4Ny05MDIyLT} ] } messageAttributes: {}9022-4d2e-8e63-3fa9dad85c65',0:local-sdpv2-agent-sqs-pusher',
``` 

### Expected Behavior

I expected that event schema aline with aws "SQSEvent"
 ` "Records": [
        {
            "messageId": "be0b950f-1952-4b8e-ae7b-f8b5ef52ac87",
            "receiptHandle": "AQEBCN12ckfngn869OAf8+PxEYm5Es5pOfx1fEzQVpwrKHoo57XFDQhLRE7g9Ab0h8sf/",
            "body": "[{\"tenantId\":\"tenantId_1\",\"userId\":\"userId_1\",\"deviceIdentifier\":\"deviceIdentifier_1\",\"message\",{\"webRules\":[],\"bypassRules\":[]}}]",
            "attributes": {
                "ApproximateReceiveCount": "1",
                "AWSTraceHeader": "Root=1-65a8fb4e-32a706e7e23ab1564a4959f1",
                "SentTimestamp": "1705573198512",
                "SenderId": "AROA34IABVPOKYT3QPVON:BackplaneAssumeRoleSession",
                "ApproximateFirstReceiveTimestamp": "1705573198517"
            },
            "messageAttributes": {},
            "md5OfBody": "8c39dd01850746176a9ac4b1748a382a",
            "eventSource": "aws:sqs",
            "eventSourceARN": "arn:aws:sqs:us-east-1:816580766684:test-sqs",
            "awsRegion": "us-east-1"
        }
    ]`

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

    With a docker run command

### Environment

```markdown
- OS:
- LocalStack:3.2.0
```

**Comment by thrau** [comment]
hello @israelItzhakov! could you please share how you set up the apigw sqs integration, as well as the sqs event source mapping?
