### ISSUE TITLE
Native Transcribe support for aarch64

### ISSUE THREAD

**Issue by kazazor** [localstack/localstack#10522]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When running on ARM based machines you get:
> cannot load library *.so

This is also described on this page: https://docs.localstack.cloud/user-guide/aws/transcribe/#getting-started

### Expected Behavior

The service should work without installing the AMD64 docker version. Using AMD64 makes everything SUPER slow on Mac. This is a VERY popular workstation for developers and should be fully supported.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

Just run it on ARM-based machines.

### Environment

```markdown
- OS: macOS
- LocalStack: latest
```

### docker-compose

```
localstack:
    image: localstack/localstack-pro:latest
    platform: linux/amd64
    pull_policy: always
    restart: always
    profiles: ["local"]
    # The localstack documentation (under GATEWAY_LISTEN: https://docs.localstack.cloud/references/configuration/) are not 100 great for macOS.
    # If we were to follow it we would have used: 127.0.0.1:4566:4566
    # The problem is IPv6 that could apply here and LocalSTack does not support it: https://docs.localstack.cloud/references/network-troubleshooting/
    # So we're defining the ports WITHOUT the localhost address
    ports:
      - "4566:4566" # LocalStack Gateway
      - "4510-4559:4510-4559" # external services port range
      - "53:53" # DNS config (required for Pro) - https://docs.localstack.cloud/user-guide/tools/transparent-endpoint-injection/
      - "53:53/udp" # DNS config (required for Pro) - https://docs.localstack.cloud/user-guide/tools/transparent-endpoint-injection/
      - "443:443" # LocalStack HTTPS Gateway (required for Pro)
    environment:
      # LS_LOG: "trace" # Uncomment for getting much more debug logs from LocalStack
      DEBUG: 1 # Change to 0 if you would like to have less noise in the LocalStack container's logs
      LOCALSTACK_AUTH_TOKEN: ${LOCALSTACK_AUTH_TOKEN} # Add it to your .env file at the root of the project
      PERSISTENCE: 1
      ENFORCE_IAM: 0 # https://docs.localstack.cloud/references/configuration/#iam
      EXTRA_CORS_ALLOWED_ORIGINS: "*" # https://docs.localstack.cloud/references/configuration/#security
      DOCKER_HOST: unix:///var/run/docker.sock
      DNS_LOCAL_NAME_PATTERNS: ".*(secretsmanager|rds).*.amazonaws.com" # The services that we would like their requests be redirected to AWS instead of Localstack. This is done via https://docs.localstack.cloud/user-guide/tools/dns-server/#skip-localstack-dns-resolution
      DNS_SERVER: 1.1.1.1 # DNS fallback server, all the non AWS requests will be forwarded to it
      DNS_ADDRESS: 127.0.0.1 # The LocalStack local DNS server address
    volumes:
      - "./localstack-hooks/ready.sh:/etc/localstack/init/ready.d/ready.sh"
      - "${LOCALSTACK_VOLUME_DIR:-./.localstack-volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock" # Enable to use services that use external docker images, like Lambda functions
```

### Anything else?

I'm opening this bug after being asked to do so in the pro support channel.

**Comment by kazazor** [comment]
Hi @viren-nadkarni , any plans on working on that any time soon?
The fact we're using amd on mac machines makes localstack just not usable for us. Uploading to S3 and downloading from Cloudfront takes ages to the point there is no way to continue working like this with the Pro plan.

**Comment by viren-nadkarni** [comment]
Hi @kazazor, the request has been noted by the engineering team and we'll try to get this out at the earliest. Unfortunatly it is difficult for me to provide a concrete ETA.

**Comment by kazazor** [comment]
Thank you @viren-nadkarni , looking forward to it.
Just to give a sense on the performance of LocalStack using amd on arm machines:
- uploading, using multi part, a 200 MB file takes 5+ minutes on a 50Mbps upload speed
- downloading that file again takes about the same time on a 100 Mbps download speed

**Comment by viren-nadkarni** [comment]
Hi @kazazor, LocalStack Transcribe now has aarch64 support. Please try the latest image and let us know your feedback. Thanks!

**Comment by kazazor** [comment]
You guys rock! Will test it out today!

**Comment by kazazor** [comment]
@viren-nadkarni IMO this issue needs to be reopened. As I wrote on your Pro support, now the error changed but it always fails with the error:
> Failed to create a model

So the transcriptions till doesn't work on arm machines

To clarify - the same files does work using localstack AMD64

**Comment by silv-io** [comment]
Hi @kazazor!

As seen in the PR which linked with this issue (#10629), we activated our Transcribe test suite for our ARM builds. (You can also verify this in our [latest CI run on master](https://app.circleci.com/pipelines/github/localstack/localstack/24207/workflows/1ec7eee9-4c1f-44bb-90d1-779f18781cb9/jobs/199898/parallel-runs/0/steps/0-109)).

The fix was also developed on an Apple Silicon device and verified to work there. As such, I would keep this particular issue as closed as the remaining problems seem unrelated to the ARM support itself. 

However, we for sure want to fix your remaining problems to get you going with LocalStack on ARM! The support team will shortly be in contact with you to work on further fixes for your use case.
