### ISSUE TITLE
bug: s3 - `PersistedS3ObjectStore.open() got an unexpected keyword argument 'mode'`

### ISSUE THREAD

**Issue by ihmpavel** [localstack/localstack#10529]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Adding files to `S3` via `PutObjectCommand` throws an error after upgrading to `localstack` version `=> 3.0.0`

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

In docker-compose.yml
```
services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    networks:
      - api
    environment:
      - SERVICES=s3,logs,dynamodb
      - DEBUG=0
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)
In Node JS, after upgrading to version `>= 3.0.0`

```
const s3 = new S3Client({
  // region: 'us-west-1',
  forcePathStyle: true,
  // endpoint: 'http://localhost:4566',
})

s3.send(
  new PutObjectCommand({
    Bucket: 'mybucket',
    Key: 'image.png',
    Body: fs.readFileSync('image.png'),
  })
)
```

An error is thrown

```
/pathToProject/node_modules/@smithy/smithy-client/dist-cjs/index.js:838
  const response = new exceptionCtor({
                   ^
S3ServiceException [InternalError]: exception while calling s3.PutObject: PersistedS3ObjectStore.open() got an unexpected keyword argument 'mode'
    at throwDefaultError (/pathToProject/node_modules/@smithy/smithy-client/dist-cjs/index.js:838:20)
    at /pathToProject/node_modules/@smithy/smithy-client/dist-cjs/index.js:847:5
    at de_CommandError (/pathToProject/node_modules/@aws-sdk/client-s3/dist-cjs/index.js:4756:14)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /pathToProject/node_modules/@smithy/middleware-serde/dist-cjs/index.js:35:20
    at async /pathToProject/node_modules/@aws-sdk/middleware-signing/dist-cjs/index.js:225:18
    at async /pathToProject/node_modules/@smithy/middleware-retry/dist-cjs/index.js:320:38
    at async /pathToProject/node_modules/@aws-sdk/middleware-flexible-checksums/dist-cjs/index.js:173:18
    at async /pathToProject/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/index.js:97:20
    at async /pathToProject/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/index.js:120:14 {
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 500,
    requestId: '72d0bfbc-84b6-43c8-8d95-1108cf601475',
    extendedRequestId: 's9lzHYrFp76ZVxRcpX9+5cjAnEH2ROuNkd2BHfIa6UkFVdtjf5mKR3/eTPFvsiP/XV/VLi31234=',
    cfId: undefined,
    attempts: 3,
    totalRetryDelay: 157
  },
  Code: 'InternalError',
  RequestId: '72d0bfbc-84b6-43c8-8d95-1108cf601475'
}
```

Prior version `3.0.0` everything was working without error. The only change made was upgrading `localstack`

### Environment

```markdown
- OS: MacOS Sonoma 14.3.1
- LocalStack: 3.2.0
```

**Comment by bentsku** [comment]
Hello @ihmpavel and thanks for your report.

This issue should only be present in some versions of `latest` in the `localstack/localstack-pro` image. From your report, it seems you're using the community image, but `PersistedS3ObjectStore` should be in the pro only.

Could you try running `docker pull localstack/localstack-pro:latest` again and see if that would solve your issue? Thanks!

**Comment by bentsku** [comment]
Would you be using `https://github.com/GREsau/localstack-persist` by chance?

Seems like the problematic code is here: https://github.com/GREsau/localstack-persist/blob/403f5b3c476cae31e1933231eee3aaace0dd1bec/src/localstack_persist/s3/storage.py#L35

You should move this issue to that repo, it seems the issue you're having is because of some incompatibility between both versions.
