### ISSUE TITLE
bug: StepFunction error when MaxAttempts value is 0 (only with new provider)

### ISSUE THREAD

**Issue by ayeganyan-atl** [localstack/localstack#10547]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When we set `MaxAttempts` to `0` and run the stepFunction, we get the following error:
```
MaxAttempts value MUST be a positive integer between 1 and 99999999, got '0'.
```

Error occurs **only** with the new stepfunction provider.

### Expected Behavior

AWS docs says that `0` is valid value for `MaxAttempts`, so we expect it should work:
```
MaxAttempts (Optional)
A positive integer that represents the maximum number of retry attempts (3 by default). If the error recurs more times than specified, retries cease and normal error handling resumes. A value of 0 specifies that the error is never retried. MaxAttempts has a maximum value of 99999999.
```

See: https://docs.aws.amazon.com/step-functions/latest/dg/concepts-error-handling.html

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack:3.2.0

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

The step function definition etc. does not matter, fails for all of them.

### Environment

```markdown
- OS: MacOS Sanoma 14.4 (23E214)
- LocalStack: 3.2.0
```

**Comment by MEPalma** [comment]
@ayeganyan-atl, thank you for assembling this bug report. Recent changes have been incorporated to address the issue you highlighted. These will be available in the next nightly version too. Your feedback on the effectiveness of these updates in resolving the reported issue would be greatly appreciated.
