### ISSUE TITLE
enhancement request: Extend WAFv2 coverage (IPSet, LoggingConfiguration) and add WAFv2 resources to CloudFormation

### ISSUE THREAD

**Issue by Relenna** [localstack/localstack#10558]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Enhancement description

Hi, 
I would like to request adding support for the following wafv2 objects:

- WAFv2::IPSet
- WAFv2::LoggingConfiguration

Also I would like to request adding possibility to create AWS::WAFv2 resources via CloudFormation. This includes new resources and existing ones: 

- AWS::WAFv2::IPSet
- AWS::WAFv2::WebACL
- AWS::WAFv2::WebACLAssociation
- AWS::WAFv2::LoggingConfiguration

**Comment by pinzon** [comment]
Hi @Relenna the PR with the requested feature was merged today. Please pull the latest version of LocalStack to use it.
