### ISSUE TITLE
bug: Lambda IAM Policy that allows cloudformation:UpdateTerminationProtection on it's current stack doesn't apply 

### ISSUE THREAD

**Issue by Garethp** [localstack/localstack#10555]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When creating a custom resource that sets a stacks `EnableTerminationProtection` to `true`, if the `Resources` in the IAM Policy for that lambda contains the specific stack name that it's targetting (`arn:aws:cloudformation:${props.env!.region}:${props.env!.account}:stack/custom-resource-stack/*`), `ENFORCE_IAM` will give a `AccessDeniedException` with the following debug information:

```
localstack-bugs | 2024-03-27T12:50:34.596 DEBUG --- [   asgi_gw_1] l.s.i.p.handler            : 0 permissions have been explicitly denied: []
localstack-bugs | 2024-03-27T12:50:34.596 DEBUG --- [   asgi_gw_1] l.s.i.p.handler            : 0 permissions have been explicitly allowed: []
localstack-bugs | 2024-03-27T12:50:34.596 DEBUG --- [   asgi_gw_1] l.s.i.p.handler            : 1 permissions have been implicitly denied: ["Action 'cloudformation:UpdateTerminationProtection' for 'arn:aws:cloudformation:eu-west-2:000000000000:stack/arn:aws:cloudformation:eu-west-2:000000000000:stack/custom-resource-stack/3f58d56f/*'"]
```

However the IAM Enforcement will let it execute if the policy contains a star rather than a specific stack name (`arn:aws:cloudformation:${props.env!.region}:${props.env!.account}:stack/*/*`).

### Expected Behavior

Considering that the IAM Policy is specifically set to allow this action, IAM Enforcement should resolve the resource properly and allow it

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```ts
export class CustomResourceStack extends Stack {
  constructor(scope: Construct, id: string, props: StackProps) {
    super(scope, id, props);

    const lambda = new Function(this, "CustomResourceLambda", {
      code: Code.fromInline(`
        const { CloudFormationClient, UpdateTerminationProtectionCommand } = require("@aws-sdk/client-cloudformation");
      
        exports.handler = async (event) => {
            if (event.RequestType == "Delete") return;
            
            const client = new CloudFormationClient({ region: "eu-west-2" });
          const command = new UpdateTerminationProtectionCommand({
            EnableTerminationProtection: true,
            StackName: event.StackId,
          });
          
          await client.send(command);
          
          return {};
        }
      `),
      handler: "index.handler",
      runtime: new Runtime("nodejs18.x", RuntimeFamily.NODEJS, {
        supportsInlineCode: true,
      }),
    });

    lambda.addToRolePolicy(
      new PolicyStatement({
        resources: [
          `arn:aws:cloudformation:${props.env!.region}:${props.env!.account}:stack/custom-resource-stack/*`,
        ],
        actions: ["cloudformation:UpdateTerminationProtection"],
        effect: Effect.ALLOW,
      }),
    );

    const provider = new Provider(this, "CustomResourceProvider", {
      onEventHandler: lambda,
    });

    new CustomResource(this, "CustomResource", {
      serviceToken: provider.serviceToken,
      properties: {},
    });
  }
}
```

### Environment

```markdown
- OS: Ubuntu 20.04
- LocalStack: latest
```

### Anything else?

This is a regression bug, since this test-case passes in LocalStack 3.2

I've reproduced the issue here: https://github.com/Garethp/localstack-bugs/tree/self-targetting-iam-policy
If you clone down the branch `self-targetting-iam-policy`, run yarn install and then ./start.sh you should see the issue in action

**Comment by dfangl** [comment]
Hi @Garethp !
We have identified the issue, and a fix is currently in our pipeline. I will update this issue once the fix is available in the latest localstack-pro image.

**Comment by dfangl** [comment]
A fix for this issue should now be available in the latest `localstack/localstack-pro` image. Please do not hesitate to reopen or open another issue if you have any more problems! Thank you for reporting this!
