### ISSUE TITLE
Moto 1.3.7?

### ISSUE THREAD

**Issue by bnoguchi** [localstack/localstack#1056]
It would be great to update moto-ext to 1.3.7 to mirror the latest release of moto 1.3.7. This will allow me to use S3 object versioning, which I've verified is working for me when I override moto-ext with moto 1.3.7 in ./requirements.txt in a local build of localstack.

**Comment by whummer** [comment]
Thanks for reporting - this should be fixed in #1072 (we now depend on moto directly).
