### ISSUE TITLE
bug: When running a step function I receive an exception " KeyError: 'error' "

### ISSUE THREAD

**Issue by phildunphytoo** [localstack/localstack#10596]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I run a step function and get an exception:
```
Exception=FailureEventException, Details={'taskFailedEventDetails": {}} at '(StateFail | {'comment': None, 'input_path': (InputPath| {'input_path_src': '$'}, 'output_path': (OutputPath| {'output_path': '$'}, 'state_entered_event_type': 'FailStateEntered', 'state_exited_event_type': None, 'cause': None, 'error': None, 'name': 'Failed', 'state_type': <StateType.Fail: 18>, 'continue_with': <localstack.services.stepfunctions.asl.component.state.state_continue_with.ContinueWithNext object at 0x7efdfc21c750>}

Exception in thread Thread-177 (_execution_logic):
Traceback (most recent call last):
File "/usr/local/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
File "/usr/local/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._Kwargs)
File "/opt/code/localstack/localstack/services/stepfunction/backend/execution_worker.py", line 76, in _execution_logic
   self._exec_comm.terminated()
File "/opt/code/localstack/localstack/services/stepfunction/backend/execution.py", line 70, in terminated
   self.execution.error = exit_program_state.error["error"]

KeyError: 'error'
```

### Expected Behavior

No exception thrown
Works as in AWS (it does work on real AWS)

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

Run localstack with docker-compose
Upload a step function
Run the step function

### Environment

```markdown
- OS: RHEL 8
- LocalStack: 3.2
- Docker: 24.0.2
```

### Anything else?

I guess something I do is wrong, I would love to have some hints on where to look for

**Comment by MEPalma** [comment]
Hello @phildunphytoo, thank you for proving this report. It seems as though the state machine defines a Fail state with no explicit Error or Cause fields. I can see this issue was resolved [in this commit](https://github.com/localstack/localstack/commit/da0076d9dcb017a8f96bd2c4c1019d53a11ed7e5), and is available in the latest version of LocalStack (v. 3.3). May I ask you to update this report on whether this issue is resolved for you in this latest version? Thank you.

**Comment by phildunphytoo** [comment]
it works now :)
thanks!

**Comment by MEPalma** [comment]
Thank you once again @phildunphytoo, I will close this issue, but should you experience further problems with this please do feel free to reopen it!
