### ISSUE TITLE
Feature Request: Updating boto3 to support transactWriteItems feature

### ISSUE THREAD

**Issue by eunicekokor** [localstack/localstack#1059]
https://github.com/aws/aws-sdk-php/issues/1687

Referencing because I have a similar issue. I think because localstack isn't on the latest boto3 version, this feature `transactWriteItems` https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/dynamodb.html?highlight=transac#DynamoDB.Client.transact_write_items is not adding things to dynamodb through localstack. Thoughts

**Comment by whummer** [comment]
Thanks for reporting - boto3 versions should have been updated in the meantime. Closing this issue, but please feel free to re-open if the problem persists. Thanks!
