### ISSUE TITLE
Cannot connect to localstack DynamoDB from Java client

### ISSUE THREAD

**Issue by thoefkens** [localstack/localstack#10598]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When trying to connect to DynamoDB (e.g. a listTables command) I am getting this error:

`Connect to localhost:4566 [localhost/127.0.0.1] failed: Connection refused: com.amazonaws.SdkClientException`

I am trying to connect as such:

`            ddb = AmazonDynamoDBClientBuilder.standard()
                    .withEndpointConfiguration(new AwsClientBuilder.EndpointConfiguration("http://localhost:4566", Regions.EU_CENTRAL_1.getName()))
                    .build();`

Running commands against localstack from the command line works fine though, with no access key or secret key set as environment variables.

` aws --endpoint-url=http://localhost:4566 --region=eu-central-1 dynamodb list-tables`

This command lists tables as expected.

### Expected Behavior

Connecting to DynamoDB using the same endpoint URL works from the command line as well as by using the AWS SDK.

### How are you starting LocalStack?

Custom (please describe below)

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

LocalStack Desktop

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

 aws --endpoint-url=http://localhost:4566 --region=eu-central-1 dynamodb list-tables

### Environment

```markdown
- OS: macOS Sonoma 14.3
- LocalStack: localstack/localstack-pro:latest
```

**Comment by bentsku** [comment]
Hello @thoefkens and thanks for your report. Could you explain where your Java code is running? Could it be inside a Docker container, which is why `localhost` is not resolving to LocalStack? 

You can have a look at our networking guide here: https://docs.localstack.cloud/references/network-troubleshooting/
Thanks!

**Comment by thoefkens** [comment]
@bentsku The code runs locally, and connects against localstack running as a docker container (started from Localstack-desktop). But as written, I can easily list my localstack resources from my localhost terminal. So it is not a networking issue from localhost -> docker container. aws-cli commands work perfectly fine.

**Comment by MarcelStranak** [comment]
Hi @thoefkens, please have a look at our documentation https://docs.localstack.cloud/user-guide/integrations/sdks/java/#dynamodb-service.
