### ISSUE TITLE
bug: static IV is used in localstack.utils.crypto

### ISSUE THREAD

**Issue by Gax-c** [localstack/localstack#10602]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When the IV is not provided, the default IV will be all zeros [here](https://github.com/localstack/localstack/blob/master/localstack/utils/crypto.py#L169). 
Using a static IV of zeros opens the system to certain types of replay attacks.

### Expected Behavior

Even if the IV is not provided, a random IV should also be generated to ensure security. 
Use the os.urandom() function or a similar secure random number generator to achieve this. 

### How are you starting LocalStack?

Custom (please describe below)

### Steps To Reproduce

Browsing the code.

**Comment by viren-nadkarni** [comment]
Hi @Gax-c, thanks for raising this issue.

I would like to emphasis that LocalStack is meant only for local development and testing purpose. It must not be used on production as it is not secure by design.
