### ISSUE TITLE
enhancement request: Add AWS:EC2::PrefixList and AWS::EC2::VPCEndpoint to CloudFormation

### ISSUE THREAD

**Issue by Relenna** [localstack/localstack#10606]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Enhancement description

Hi, I would like to request adding possibility to create 'AWS:EC2::PrefixList' and 'AWS::EC2::VPCEndpoint' resources via CloudFormation

**Comment by pinzon** [comment]
The solution for this issue has been merged. Please make sure to pull the latest image.
