### ISSUE TITLE
Hi, I'm testing this in localstack 3.3 but it seems it doesn't work right.

### ISSUE THREAD

**Issue by phildunphytoo** [localstack/localstack#10603]
Hi, I'm testing this in localstack 3.3 but it seems it doesn't work right.
I have a condition: "$[?(@.Status != '200')]" and it catches outputs that have Status = 200.. Any ideas?

_Originally posted by @phildunphytoo in https://github.com/localstack/localstack/issues/9937#issuecomment-2036293914_

**Comment by phildunphytoo** [comment]
I guys, any news? Thanks!

**Comment by MEPalma** [comment]
Hello @phildunphytoo, thank you for raising this issue. As I discussed in https://github.com/localstack/localstack/issues/10694#issuecomment-2107574118, this issue appears to be a limitation of the JsonPath library the StepFunctions interpreter relies on to resolve JsonPaths. We are looking into this issue and will be happy to update this issue when this is resolved. Thank you!

**Comment by phildunphytoo** [comment]
Ooohh alright! Thank you!
