### ISSUE TITLE
Document change from 'async' to 'asynchronous'  keyword change.

### ISSUE THREAD

**Issue by mgab** [localstack/localstack#1060]
In order to add support for Python 3.7 (by stop using the now-reserved word `async`), #827 changed the *many* places where this kewyord was use for the safe `asynchronous`. So far so good.

The problem is that this keyword is exposed in the public API in several places. Thus, this change that was crucial for Python 3.7, but it introduced backwards incompatible changes in a patch version (from v0.8.7 to v0.8.8) without any deprecation period or warning. The PR does not link any issue, so I'm afraid it has not been even considered. In fact, not even documentation or the `README.md` has been updated!

So, the point of this issue, apart from trying to convey the need to be extra careful when introducing backward incompatible changes, is to suggest updating the documentation. Docs and `README.md` still shows [example snippets](https://github.com/localstack/localstack#integration-with-nosetests) using the  outdated `async` keyword.

**Comment by whummer** [comment]
Thanks for pointing this out @mgab . The README has been updated in #1065
