### ISSUE TITLE
bug: CreationDate is not exist in describe-backup-vault output

### ISSUE THREAD

**Issue by Kater0k** [localstack/localstack#10601]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```aws --endpoint-url=http://localhost:4566 backup create-backup-vault --backup-vault-name test```
Output: 
```
{
    "BackupVaultName": "test",
    "BackupVaultArn": "arn:aws:backup:us-east-2:000000000000:backup-vault:test",
    "CreationDate": "2024-04-04T12:28:57.608553+03:00"
}
```

```aws --endpoint-url=http://localhost:4566 backup describe-backup-vault --backup-vault-name test```
Output:
```
{
    "BackupVaultName": "test",
    "BackupVaultArn": "arn:aws:backup:us-east-2:000000000000:backup-vault:test"
}
```

### Expected Behavior

```aws --endpoint-url=http://localhost:4566 backup describe-backup-vault --backup-vault-name test```
Output:
```
{
    "BackupVaultName": "test",
    "BackupVaultArn": "arn:aws:backup:us-east-2:000000000000:backup-vault:test"
    "CreationDate": "2024-04-04T12:28:57.608553+03:00"
}
```

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

Run localstack with docker-compose
Create aws backup-vault
Describe backup-vault

### Environment

```markdown
- OS: Ubuntu 20.04
- LocalStack: 3.3.0
```

**Comment by AbdullahMakhdoom** [comment]
This seems to be a feature available in Pro version of localstack. @viren-nadkarni

**Comment by viren-nadkarni** [comment]
> Correct me if I am wrong, but this seems to be a feature available in Pro version of localstack. @viren-nadkarni

@AbdullahMakhdoom That is correct

**Comment by viren-nadkarni** [comment]
> Can open-source contributors work on pro features?

@AbdullahMakhdoom I'm afraid not. LocalStack Pro is a paid offering and is not open-source

**Comment by viren-nadkarni** [comment]
> Can open-source contributors work on pro features? I don't see any codebase for backup feature in this repo. @viren-nadkarni

Sorry, I mislabelled this issue. Fixed now.

**Comment by giograno** [comment]
Closed by [this](https://github.com/localstack/localstack-ext/pull/2849)
