### ISSUE TITLE
Localstack S3 listNextBatchOfObjects pagination does not work as expected

### ISSUE THREAD

**Issue by RichardTran** [localstack/localstack#1061]
Found a pagination bug with localstack's s3. Primarily against s3Client.listNextBatchOfObjects.

    private void test() {
        s3Client.putObject(s3BucketName, "key1", "content");
        s3Client.putObject(s3BucketName, "key2", "content");
        s3Client.putObject(s3BucketName, "key3", "content");

        ListObjectsRequest listObjectsRequest = new ListObjectsRequest()
                .withBucketName(s3BucketName)
                .withPrefix("")
                .withDelimiter("/")
                .setMaxKeys(1); // 1 Key per request

        ObjectListing objectListing = s3Client.listObjects(listObjectsRequest);
        List<SomeObject> someObjList = createEmptyList();
        someObjList.addAll(mapFilesToSomeObject(objectListing)); // puts at least 1 item into the list

        while (objectListing.isTruncated()) {
            objectListing = s3Client.listNextBatchOfObjects(objectListing);
            someObjList.addAll(mapFilesToSomeObject(objectListing));
        }
        assertEquals(3, someObjList.size());
    }

    private List<SomeObject> mapFilesToSomeObject(ObjectListing objectListing) {
        return objectListing.getObjectSummaries()
            .stream()
            .map(S3ObjectSummary::getKey)
            .map(x -> this.toSomeObject(x)) // some deserialization method
            .collect(Collectors.toList());
    }

This while loop will only get the second item in its first loop. It still enters the loop once more to grab the third item since the condition is still true, but the 2nd call of listNextBatchOfObjects in that very loop returns an empty list, thus failing to grab that third item. I confirmed that listNextBatchOfObjects retrieves the "second page" only against localstack, with changing the amount of items and page sizes. On AWS s3, this works as expected.

Refer to s3Client.listNextBatchOfObjects:
https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/AmazonS3Client.html#listNextBatchOfObjects-com.amazonaws.services.s3.model.ObjectListing-

**Comment by gvauvert-axway** [comment]
I have the same issue with this similar call:
`List<S3ObjectSummary> listAllObjects(ListObjectsV2Request listObjectsRequest) {
        listObjectsRequest.setMaxKeys(5);
        List<S3ObjectSummary> result = new ArrayList<>();
        ListObjectsV2Result listObjectsResult;
        do {
            listObjectsResult = m_amazonS3.listObjectsV2(listObjectsRequest);
            result.addAll(listObjectsResult.getObjectSummaries());
            //
            String continuationToken = listObjectsResult.getNextContinuationToken();
            listObjectsRequest.setContinuationToken(continuationToken);
        } while (listObjectsResult.isTruncated());
        return result;
    }`

The line `listObjectsRequest.setMaxKeys(5)` has no impact and the code is still behaves as it were using the default value 1000 (instead of 5).

**Comment by gvauvert-axway** [comment]
I confirm the issue on localstack 0.9.0.

**Comment by whummer** [comment]
Thanks for reporting @RichardTran @gvauvert-axway . This should be fixed in the latest version - a test has been added in PR #1895 to cover this functionality. Please report here if the problem persists. Thanks

**Comment by whummer** [comment]
Thanks for reporting @RichardTran @gvauvert-axway . This should be fixed in the latest version - a test has been added in PR #1895 to cover this functionality. Please report here if the problem persists. Thanks
