### ISSUE TITLE
Add support for AWS managed master user passwords in aurora RDS clusters (postgres)

### ISSUE THREAD

**Issue by mbarr-hrp** [localstack/localstack#10654]
The API works, but no secret is created, and thus there's also no ability to add the rotation schedule.

Worse, there's no way to get the password that was generated for the DB.

This means that testing infrastucture (terraform) is not possible without extensive customization for localstack, and makes testing TF code nigh impossible.

(Yes, if your goal is storing the secret and retrieval, there is the workaround of hard coding the secret, but the name & pattern are frustrating to get right, and you still have to have code that is conditional on localstack.)

**Comment by nik-localstack** [comment]
Hello @mbarr-hrp 
Sorry for the late reply here and thanks for your report. 
I just want to inform you that a relevant change was pushed in the latest localstack-pro version, so this functionality is now available.
