### ISSUE TITLE
bug:AWS RDS Aurora clusters - Performance Insight

### ISSUE THREAD

**Issue by mbarr-hrp** [localstack/localstack#10655]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In terraform: aws_rds_cluster_instance : Upon creation: 

performance_insights_enabled = true will set the value of performance_insights_retention_period= 0, even if it's set to 7.

Every subsequent run will mark that as needing a change.  
The API will not accept 0  as a valid setting for performance_insights_retention_period, so you can't bypass the modification upon every apply, as it's seen as needing to be fixed.

(We don't need the actual perfomance_insights, but the value being stored correctly, and not requiring a change would be very helpful to avoid dirty plans.)

### Expected Behavior

I would expect performance_insights_retention_period to show a valid number, probably 7, as the default after creation.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

tf apply to create the RDS Aurora cluster. 

resource "aws_rds_cluster_instance" "instance" {
....
performance_insights_enabled =true
performance_insights_retention_period=7
}

(This is limited, but the test code used in support case 2783195633 should be enough to replicate.)

### Environment

```markdown
- OS: mac 14
- LocalStack:3.1.0
```

**Comment by steffyP** [comment]
Hi @mbarr-hrp, 
thanks for reporting! We fixed the issue, so setting the `performance_insights_retention_period` should now work when using the `latest` localstack image.
