### ISSUE TITLE
Coverage is locked to 4.0.3

### ISSUE THREAD

**Issue by alphachai** [localstack/localstack#1066]
Why has coverage been locked to `==4.0.3` for two years? Why not `>=4.0.0`?

If I add localstack to my pipenv, I can't lock because of this unnecessary dependency.

**Comment by hack2root** [comment]
python-coveralls 2.9.1 has requirement coverage==4.0.3, but you'll have coverage 4.5.3 which is incompatible.

**Comment by mknnaren** [comment]
@hack2root  Even I am having the same issue. Has anyone found a fix for this.
