### ISSUE TITLE
bug: Cannot create an asymmetric KMS key for import

### ISSUE THREAD

**Issue by agilethomas** [localstack/localstack#10677]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Creating an asymmetric KMS key with the plan to import the private key later does not work.

Options are:
`--customer-master-key-spec RSA_2048 (--key-spec for actual AWS)`
`--origin EXTERNAL`
`--key-usage ENCRYPT_DECRYPT`

Full command:
`awslocal kms create-key --key-usage ENCRYPT_DECRYPT --origin EXTERNAL --customer-master-key-spec RSA_2048`

Returns this error:
`KeySpec RSA_2048 is not supported for Origin EXTERNAL`

### Expected Behavior

This should work as AWS supports this behavior. Here is the same command but using AWS:

`aws kms create-key --profile sandbox --key-usage ENCRYPT_DECRYPT --origin EXTERNAL --key-spec RSA_2048`

and its output
```
{
    "KeyMetadata": {
        "AWSAccountId": "XXXXXXXXXXX",
        "KeyId": "3ba058ff-3d22-43cf-86fb-ebdb339f8bbb",
        "Arn": "arn:aws:kms:us-east-1:XXXXXXXX:key/3ba058ff-3d22-43cf-86fb-ebdb339f8bbb",
        "CreationDate": "2024-04-16T19:22:28.668000+00:00",
        "Enabled": false,
        "Description": "",
        "KeyUsage": "ENCRYPT_DECRYPT",
        "KeyState": "PendingImport",
        "Origin": "EXTERNAL",
        "KeyManager": "CUSTOMER",
        "CustomerMasterKeySpec": "RSA_2048",
        "KeySpec": "RSA_2048",
        "EncryptionAlgorithms": [
            "RSAES_OAEP_SHA_1",
            "RSAES_OAEP_SHA_256"
        ],
        "MultiRegion": false
    }
}
```

### How are you starting LocalStack?

Custom (please describe below)

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    localstack start --docker

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal kms create-key --key-usage ENCRYPT_DECRYPT --origin EXTERNAL --customer-master-key-spec RSA_2048

### Environment

```markdown
- OS: Ubuntu 20.04
- LocalStack: 3.3.0
```

### Anything else?

Same issue when using the PHP AWS SDK.

**Comment by sannya-singal** [comment]
Hey @agilethomas! Thanks for reaching out and logging this issue. 

I tried running the following command `awslocal kms create-key --key-usage ENCRYPT_DECRYPT --origin EXTERNAL --customer-master-key-spec RSA_2048` and it runs successfully for me. 

Can you kindly pull the `latest` docker image and check if the issue still persists?

**Comment by agilethomas** [comment]
Thanks @sannya-singal I was able to get pass this issue so it can be closed (updating the CLI doesn't automatically update the docker image so I guess I was on an old one). I am having other issues with the import (Unsupported padding, requested wrapping algorithm:'RSA_AES_KEY_WRAP_SHA_256') but I will open a different ticket if I can't resolve it.

**Comment by quirell** [comment]
@agilethomas 
Hey, did you solve the issue ? I'm getting the same Unsupported padding, requested wrapping algorithm:'RSA_AES_KEY_WRAP_SHA_256'
