### ISSUE TITLE
bug: EventBridge PutEvents not failing invalid entries

### ISSUE THREAD

**Issue by KrazyK786** [localstack/localstack#10675]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When making a PutEvents call against LocalStack, the provided entries do not appear to be validated for Detail, DetailType, and Source, per the the corresponding behavior of AWS.

### Expected Behavior

When making a PutEvents request to LocalStack, I expect to receive failed entries for entries that do not have the required Detail, DetailType, and Source.

### How are you starting LocalStack?

Custom (please describe below)

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```
aws events put-events \
  --endpoint-url http://localhost:4566 \
  --region us-east-1 \
  --entries '[{"DetailType": "Test", "Detail": "{\"test1\": \"test2\"}", "Source": "testing.123"}, {"DetailType": "Test2"}]'
```

#### running against LocalStack returns:
```json
{
    "FailedEntryCount": 0,
    "Entries": [
        {
            "EventId": "a4aa1d31-4d45-4894-8534-61e0a3d6778e"
        },
        {
            "EventId": "5a52b29c-6d4f-4e9b-9457-0dcb7717229f"
        }
    ]
}
```

#### running against AWS returns:
```json
{
    "FailedEntryCount": 1,
    "Entries": [
        {
            "EventId": "28bc32af-7944-0a4f-dfe0-f75703d4b8db"
        },
        {
            "ErrorCode": "InvalidArgument",
            "ErrorMessage": "Parameter Source is not valid. Reason: Source is a required argument."
        }
    ]
}
```

### Environment

```markdown
- OS: macOS Sonoma 14.4.1
- LocalStack: latest
```

### Anything else?

We did find a previous [issue](https://github.com/localstack/localstack/issues/3043) that seemed to address this scenario and referenced the AWS documentation for [PutEvents](https://docs.aws.amazon.com/eventbridge/latest/APIReference/API_PutEventsRequestEntry.html); while it does still list Detail, DetailType, and Source as "Required: No", they have added notes that any entries missing these fields will fail. (We have put a request in to AWS for clearer documentation on this issue.)

**Comment by maxhoheiser** [comment]
Dear all, we introduced the new EventBridge v2 with our release 3.5 officially last week. Amongst many other improvements and parity fixes, the new EventBridge v2 also handles entry validation for `put_event` correctly thus further improving the parity with AWS.

You can use the new EventBridge v2 by setting the environment variable `PROVIDER_OVERRIDE_EVENTS=v2`.

Please give us feedback regarding this or any other issues.
