### ISSUE TITLE
bug: Lambda fails due to missing runtime java21 when registering new Lambda

### ISSUE THREAD

**Issue by robinsving** [localstack/localstack#10683]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Trying (using Terraform) to register a lambda with the runtime "java21".

The localstack image is taken from [Docker hub](https://hub.docker.com/r/localstack/localstack).

```
Error: expected runtime to be one of [nodejs nodejs4.3 nodejs6.10 nodejs8.10 nodejs10.x nodejs12.x nodejs14.x nodejs16.x java8 java8.al2 java11 python2.7 python3.6 python3.7 python3.8 python3.9 dotnetcore1.0 dotnetcore2.0 dotnetcore2.1 dotnetcore3.1 dotnet6 nodejs4.3-edge go1.x ruby2.5 ruby2.7 provided provided.al2], got java21
│ 
│   with aws_lambda_function.lambda-my-function,
│   on main.tf line 607, in resource "aws_lambda_function" "lambda-my-function":
│  607:   runtime = "java21"
```

### Expected Behavior

The Lambda is registered, and executed using java21

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

```localstack:
    image: <internal-repo-mirror>/docker-hub/localstack/localstack:3.3
    ports:
      - '4563-4599:4563-4599'
      - '8055:8080'
    environment:
      - DISABLE_EVENTS=1
      - SERVICES=s3,sts,events,iam,ec2,lambda,apigateway,logs,aws
      - DEBUG=1
      - PERSISTENCE=/var/lib/localstack
    volumes:
      - './.localstack:/var/lib/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
    links:
      - "db:db"
    networks:
      - stack
```

After this, I register a lambda using terraform:
```
resource "aws_lambda_function" "lambda-my-function" {
  function_name = "my-my-function"

  role    = aws_iam_role.custom.arn
  handler = <my Java entrypoint>

  s3_bucket        = aws_s3_bucket.my_lambda.bucket
  s3_key           = "lambda.jar"
  source_code_hash = aws_s3_object.lambda_upload.source_hash

  runtime = "java21"
}
```

I have tried to add the following env-variable to no avail:
`      - LAMBDA_RUNTIME_IMAGE_MAPPING={"java21":"<internal-repo-mirror>/docker-hub/localstack/lambda-java:21"}`

### Environment

```markdown
- OS:Ubuntu 20.04
- LocalStack:3.3 and latest
```

**Comment by dfangl** [comment]
Hi @robinsving !
This issue is not with localstack, but your (outdated) terraform provider. 
Java21 support was released with the terraform aws provider version 5.27, so please update your terraform provider to at least that version.

**Comment by robinsving** [comment]
Of course, that makes sense. Thank you so much!
