### ISSUE TITLE
bug: SES smtplib.SMTPServerDisconnected: Connection unexpectedly closed

### ISSUE THREAD

**Issue by kaustumbh7** [localstack/localstack#10697]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am running 2 docker containers, 
1. My Django app in one container
2. Localstack server in the other

Both the containers are running in the same network but I keep getting `SES smtplib.SMTPServerDisconnected: Connection unexpectedly closed` error.

I have made sure that my Localstack setup is correct by following this [documentation](https://docs.localstack.cloud/user-guide/aws/ses/)

These are the configurations of my Django Email server-
```
EMAIL_FROM = "test_email@gmail.com"
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = 'localstack' # Name of my docker container in which localstack is running
EMAIL_PORT = 4566 # Port no. on which the localstack docker container is running on
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'test'
EMAIL_HOST_PASSWORD = 'test'
```

How can I fix this issue?

### Expected Behavior

Emails should get sent to Localstack SES without any exception.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker-compose up --build

Docker file contains the following localstack container-
```
  localstack:
    image: localstack/localstack:3.3.0
    container_name: localstack
    restart: always
    environment:
      # - DEBUG=1
      - GATEWAY_LISTEN=:4566
      - SERVICES=sqs,ses,s3
      - DEBUG=${DEBUG:-0}
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "4566:4566"
    networks:
      - test_network
```
#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

Verify email identity-
```
awslocal ses verify-email-identity --email test_email@gmail.com
```

### Environment

```markdown
- OS: macOS- 14.4 (23E214)
- LocalStack: 3.3.0
```

**Comment by thrau** [comment]
Hey @kaustumbh7! this is not an issue with localstack, but rather how you are trying to set up django. your config tells django to talk to localhost:4566 via SMTP, but AWS SES is not an SMTP server.

To use SES you will either need to create an [SMTP endpoint](https://docs.aws.amazon.com/ses/latest/dg/smtp-connect.html) (which localstack currently doesn't support), or use [django-ses](https://github.com/django-ses/django-ses).

**Comment by kaustumbh7** [comment]
Got it! Thank you so much for clarification 🙂 @thrau
