### ISSUE TITLE
bug: ASLParserException on CreateStateMachine operation if 'Map' state contains 'MaxConcurrencyPath' field

### ISSUE THREAD

**Issue by attila** [localstack/localstack#10692]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello there, it looks like state machines fail to create when they contain a Map state with "MaxConcurrencyPath" defined. The error thrown is:

`An error occurred (InvalidDefinition) when calling the CreateStateMachine operation: ASLParserException line 1:138, at "MaxConcurrencyPath", mismatched input '"MaxConcurrencyPath"' expecting {'"Comment"', '"Type"', '"Choices"', '"Default"', '"Branches"', '"SecondsPath"', '"Seconds"', '"TimestampPath"', '"Timestamp"', '"TimeoutSeconds"', '"TimeoutSecondsPath"', '"HeartbeatSeconds"', '"HeartbeatSecondsPath"', '"ItemProcessor"', '"Iterator"', '"ItemSelector"', '"MaxConcurrency"', '"Resource"', '"InputPath"', '"OutputPath"', '"ItemsPath"', '"ResultPath"', '"Result"', '"Parameters"', '"ResultSelector"', '"ItemReader"', '"Next"', '"End"', '"Cause"', '"CausePath"', '"Error"', '"ErrorPath"', '"Retry"', '"Catch"'}`

### Expected Behavior

Step function created successfully. See the option documented at https://docs.aws.amazon.com/step-functions/latest/dg/concepts-asl-use-map-state-inline.html#map-state-inline-additional-fields

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker compose up

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal stepfunctions create-state-machine --name 'example' --role-arn 'arn:aws:iam::000000000000:role/stepfunctions-role' --definition '{"StartAt":"MapState","States":{"MapState":{"Type":"Map","Iterator":{"StartAt":"Iterate","States":{"Iterate":{"Type":"Pass","End":true}}},"MaxConcurrencyPath":"$.Some.Path"}}}'

I inlined the definition in the example but here it is for better readability:

```json
{
  "StartAt": "MapState",
  "States": {
    "MapState": {
      "Type": "Map",
      "Iterator": {
        "StartAt": "Iterate",
        "States": {
          "Iterate": {
            "Type": "Pass",
            "End": true
          }
        }
      },
      "MaxConcurrencyPath": "$.Some.Path"
    }
  }
}
```

### Environment

```markdown
- OS: MacOS 14
- LocalStack: 3.3.0
```

**Comment by MEPalma** [comment]
@attila thank you for taking the time to compile this thorough report. I was able to replicate the behaviour. We recently merged some changes that aim to address this issue. These changes are scheduled to be included in the next nightly release too. I would be grateful if you could test the new build at your earliest convenience and provide feedback on whether it resolves the problem you encountered. Thank you once again for bringing this issue forward.

**Comment by MEPalma** [comment]
Hi @attila, thank you once again for the very thorough issue report. I believe this issue should be resolved from the next latest version of localstack. Would you mind verifying that the integer conversion is now working as expected? Thank you!

**Comment by attila** [comment]
Hey @MEPalma, I pulled `localstack/localstack:latest` and I was able to confirm the fix, thank you!

**Comment by MEPalma** [comment]
That's brilliant, thank you once again for reporting and following up on this issue!
