### ISSUE TITLE
SSH into EC2 using non 127.0.0.1 IP does not work on Mac 

### ISSUE THREAD

**Issue by clouder-coder** [localstack/localstack#10719]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

As per the following:
```
2024-04-25T03:21:06.733  INFO --- [   asgi_gw_1] l.s.ec2.vmmanager.docker   : Instance i-78a003ae34a846e5c will be accessible via SSH at: 127.0.0.1:22, 172.17.0.3:22
```
While I can successfully SSH with the `127.0.0.1` address,  somehow SSH  with the IP `172.17.0.3` does not work.  The SSH command using IP `172.17.0.3` will hang. 

### Expected Behavior

SSH into `172.17.0.3` should work just like `127.0.0.1` on Mac. 

### How are you starting LocalStack?

With the `localstack` script

### Steps To Reproduce

I used tflocal to spin up the EC2 instance, but I think the same issue can also be reproduced with steps mentioned in https://docs.localstack.cloud/user-guide/aws/ec2/#connecting-via-ssh

### Environment

```markdown
- OS: MacOS 14.4.1
- LocalStack: 3.3.1.dev20240424170543
```

**Comment by viren-nadkarni** [comment]
Hi @clouder-coder, network access to Dockerised instances is not possible on Mac OS. Please see https://docs.localstack.cloud/user-guide/aws/ec2/#networking

**Comment by clouder-coder** [comment]
@viren-nadkarni I see. Thanks for the prompt response.
