### ISSUE TITLE
bug: DELETE s3 returns empty response with content-type: application/XML breaking the client

### ISSUE THREAD

**Issue by vdayanand** [localstack/localstack#10712]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Similar issue: https://github.com/localstack/localstack/issues/4324

Delete request:
```
DELETE /bucket.123-venk/Project.toml HTTP/1.1
User-Agent: AWS.jl/1.0.0
Host: localhost
x-amz-date: xxx
x-amz-content-sha256: xxx
Content-MD5: xxx
x-amz-security-token: xxx
Accept: */*
Content-Length: 0
Accept-Encoding: gzip
```

Delete response:
```
HTTP/1.1 204 
Content-Type: application/xml
x-amz-request-id: xxx
x-amz-id-2: cas
Connection: close
date: Wed, 24 Apr 2024 06:20:18 GMT
server: hypercorn-h11
content-length: 0
```
Note the response is empty given content-type is `application/xml`. Empty response is not a valid XML and this breaks the AWS client.

### Expected Behavior

This is what I would expect (simllar to Amazon s3)
Delete request:
```
DELETE /bucket.123-venk/Project.toml HTTP/1.1
User-Agent: AWS.jl/1.0.0
Host: s3.us-east-1.amazonaws.com␍
x-amz-date: xxx
x-amz-content-sha256: xxx
Content-MD5: xxx
x-amz-security-token: xxx
Accept: */*
Content-Length: 0
Accept-Encoding: gzip

```
Delete response:
```
HTTP/1.1 204 No Content
x-amz-id-2: xxx
x-amz-request-id: xxx
Date: Wed, 24 Apr 2024 06:19:17 GMT
Server: AmazonS3
content-length: 0
```

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

### Environment

```markdown
- OS: macOS (arm64-apple-darwin22.4.0) 
- LocalStack: 3.3.0
```

**Comment by bentsku** [comment]
Hello @vdayanand and thanks for your report!

Having the `Content-Type` set for a payload with a content length of 0 should technically still be in line with HTTP specs, see this StackOverflow post: https://stackoverflow.com/questions/29784398/should-content-type-header-be-present-when-the-message-body-is-empty

I believe this is an issue with the client, it should not try to decode an empty message body.

However, as S3 does not return a content-type, we're lacking parity here and I'll still work on a fix. It could still be beneficial to report this in the client library, as this seems like a fragile behavior. 

I'll link the PR fixing this to this issue! Thanks
