### ISSUE TITLE
S3 Request Headers not respected

### ISSUE THREAD

**Issue by davepgreene** [localstack/localstack#1071]
It looks like none of the [S3-specific request headers](https://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectGET.html#RESTObjectGET-requests-request-headers) are handled by localstack. This causes calls to `GetObject` while specifying the `Range`, `If-Modified-Since`, `If-Unmodified-Since`, `If-Match`, and `If-None-Match` to return incorrect data.

I don't mind doing the leg work. Just unsure if the implementation should live in localstack or upstream in moto. Thoughts?

**Comment by whummer** [comment]
@davepgreene it's been a while since you reported this issue. It looks like some request headers (e.g., `If-Modified-Since`) are already implemented upstream in moto. Do you think we could revive this issue and evaluate what's currently still missing? Thanks a lot.

**Comment by yaitskov** [comment]
Please explain what happened with that issue.
As for now when downloading file from S3 with if-none-match Etag is ignored and whole content is returned in response.

**Comment by yaitskov** [comment]
Please merge this PR
https://github.com/localstack/localstack/pull/2855

It doesn't solve all issues but If-None-Match is working and my test written against real AWS S3 passing with this patch.
