### ISSUE TITLE
bug: unable to decode CustomEmailSender_SignUp encrypted code, got InvalidCiphertextException

### ISSUE THREAD

**Issue by vt-rcheng** [localstack/localstack#10737]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

this is a reopening of bug #9348
I have tried again with the latest localstack ver 3.4.1
So I am trying to implement Cognito lambda trigger

I first sign up
root@7f0236f21f67:/opt/code/localstack# awslocal cognito-idp sign-up   --client-id 7h3o0ebyozvd3vjhymdo8bvn0s   --username xxx@yyyy.zzz   --password 12345678Aa! --user-attributes Name=name,Value=+11111111111

the trigger then receives a CustomEmailSender_SignUp trigger
inside the request it has an encrypted code 

`AgV4RSjfaHPY6cDSoaPQHqQYCDyPQESesN3pMkPvq4wScOsAXwABABVhd3MtY3J5cHRvLXB1YmxpYy1rZXkAREFqdnpyZ2FKMjladVZnRFRSOTBKUXo1TCsranp2SHFGUlg2M2Q4VFM4amJ5b2ZYMk1HK0NrSGpNVkVEQnJod1o5UT09AAEAB2F3cy1rbXMAS2Fybjphd3M6a21zOnVzLWVhc3QtMTowMDAwMDAwMDAwMDA6a2V5LzY1NjY5OGRhLTZhYTQtNDU4OC05YmZhLWQ4NGYyOTE5YzNkZgB0NjU2Njk4ZGEtNmFhNC00NTg4LTliZmEtZDg0ZjI5MTljM2RmiNnmPzJkxa6K457GXPrcGUAvV50VVZOaylI49kJFvq5VTtzUnunN5Z56+OTBKRffyvn3QnIq1b69o3ARYvmTnnsjG36q6jTXGmXlqU+PYuACAAAQAKs2LNWFjBskSk7IaYj4DURDiqEI0zyZelixydYb0d09rgnGOQixeTl24EVeNNaEov////8AAAABAAAAAAAAAAAAAAABAAAABh4cPQLLvmi4rgpxsAMSLYgkGTwoWsEAZzBlAjEAoUeOu2COlANi9iWqegJ9yCZHeEadgjaPNxedYO9knstLAemrruN7pRL0bkrxs2BgAjBYXbovABctggQj7UQV9uOXKDj1ajCifAC8EBu4moFQMw3K2UIbH4yw2FYIACEakxs=
`

I try to use kms to decrypt the code

`root@7f0236f21f67:/opt/code/localstack# awslocal kms decrypt --ciphertext-blob fileb://<(echo "AgV4RSjfaHPY6cDSoaPQHqQYCDyPQESesN3pMkPvq4wScOsAXwABABVhd3MtY3J5cHRvLXB1YmxpYy1rZXkAREFqdnpyZ2FKMjladVZnRFRSOTBKUXo1TCsranp2SHFGUlg2M2Q4VFM4amJ5b2ZYMk1HK0NrSGpNVkVEQnJod1o5UT09AAEAB2F3cy1rbXMAS2Fybjphd3M6a21zOnVzLWVhc3QtMTowMDAwMDAwMDAwMDA6a2V5LzY1NjY5OGRhLTZhYTQtNDU4OC05YmZhLWQ4NGYyOTE5YzNkZgB0NjU2Njk4ZGEtNmFhNC00NTg4LTliZmEtZDg0ZjI5MTljM2RmiNnmPzJkxa6K457GXPrcGUAvV50VVZOaylI49kJFvq5VTtzUnunN5Z56+OTBKRffyvn3QnIq1b69o3ARYvmTnnsjG36q6jTXGmXlqU+PYuACAAAQAKs2LNWFjBskSk7IaYj4DURDiqEI0zyZelixydYb0d09rgnGOQixeTl24EVeNNaEov////8AAAABAAAAAAAAAAAAAAABAAAABh4cPQLLvmi4rgpxsAMSLYgkGTwoWsEAZzBlAjEAoUeOu2COlANi9iWqegJ9yCZHeEadgjaPNxedYO9knstLAemrruN7pRL0bkrxs2BgAjBYXbovABctggQj7UQV9uOXKDj1ajCifAC8EBu4moFQMw3K2UIbH4yw2FYIACEakxs=" | base64 --decode) --output text `

but got the following error

`An error occurred (InvalidCiphertextException) when calling the Decrypt operation: LocalStack is unable to deserialize the ciphertext blob. Perhaps the blob didn't come from LocalStack
`

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```
client.create_key(
    Description='product_master_key',
    KeyUsage='ENCRYPT_DECRYPT',
    Tags=[
        {
            'TagKey': '_custom_id_',
            'TagValue': '00000000-0000-0000-0000-000000000001'
        },
    ],    
)


client.create_user_pool(
        PoolName=user_pool_name,
        Policies={
            'PasswordPolicy': {
                'MinimumLength': 6,
                'RequireUppercase': True,
                'RequireLowercase': True,
                'RequireNumbers': True,
                'RequireSymbols': False,
                'TemporaryPasswordValidityDays': 30
            }
        },
        DeletionProtection='INACTIVE',
        LambdaConfig={
            'PreSignUp': localstack_lambda_router_arn,
            'CustomMessage': localstack_lambda_router_arn,
            'PostConfirmation': localstack_lambda_router_arn,
            'PreAuthentication': localstack_lambda_router_arn,
            'PostAuthentication': localstack_lambda_router_arn,
            'DefineAuthChallenge': localstack_lambda_router_arn,
            'CreateAuthChallenge': localstack_lambda_router_arn,
            'VerifyAuthChallengeResponse': localstack_lambda_router_arn,
            'PreTokenGeneration': localstack_lambda_router_arn,
            'UserMigration': localstack_lambda_router_arn,
            'CustomSMSSender': {
                'LambdaVersion': '$LATEST',
                'LambdaArn': localstack_lambda_router_arn
            },
            'CustomEmailSender': {
                'LambdaVersion': '$LATEST',
                'LambdaArn': localstack_lambda_router_arn
            },
            'KMSKeyID': master_kms_arn
        },
        MfaConfiguration='OFF',
        UserAttributeUpdateSettings={
            'AttributesRequireVerificationBeforeUpdate': [
                'phone_number',
                'email',
            ]
        },
        DeviceConfiguration={
            'ChallengeRequiredOnNewDevice': True,
            'DeviceOnlyRememberedOnUserPrompt': True
        },
        EmailConfiguration={
            'ReplyToEmailAddress': 'noreply@xxxx.yyy',
            'EmailSendingAccount': 'COGNITO_DEFAULT',
            'From': 'noreply@xxxx.yyy',
        },
        UserPoolTags={
            '_custom_id_': user_pool_id
        },
        AdminCreateUserConfig={
            'AllowAdminCreateUserOnly': False,
            'UnusedAccountValidityDays': 7,
        },
        UserPoolAddOns={
            'AdvancedSecurityMode': 'AUDIT'
        },
        UsernameConfiguration={
            'CaseSensitive': False
        },
        AccountRecoverySetting={
            'RecoveryMechanisms': [
                {
                    'Priority': 1,
                    'Name': 'verified_email'
                },
                {
                    'Priority': 2,
                    'Name': 'verified_phone_number'
                },
                {
                    'Priority': 3,
                    'Name': 'admin_only'
                }
            ]
        }
    )


client.create_user_pool_client(
        UserPoolId=user_pool_id,
        ClientName=user_pool_client_name,
        GenerateSecret=True,
        RefreshTokenValidity=1,
        AccessTokenValidity=1,
        IdTokenValidity=1,
        TokenValidityUnits={
            'AccessToken': 'hours',
            'IdToken': 'hours',
            'RefreshToken': 'days'
        },
        ReadAttributes=[
            'email',
            'phone_number'
        ],
        WriteAttributes=[
            'email',
            'phone_number'
        ],
        ExplicitAuthFlows=[
            'ALLOW_ADMIN_USER_PASSWORD_AUTH',
            'ALLOW_USER_PASSWORD_AUTH',
            'ALLOW_USER_SRP_AUTH',
            'ALLOW_REFRESH_TOKEN_AUTH',
        ],
        SupportedIdentityProviders=[
            'COGNITO',
            'Facebook',
            'Google',
            'LoginWithAmazon'
        ],
        CallbackURLs=[
            'http://localhost',
        ],
        LogoutURLs=[
            'http://localhost',
        ],
        AllowedOAuthScopes=[
            'phone',
            'email',
            'openid',
            'profile'
        ],
        AllowedOAuthFlowsUserPoolClient=True,
        PreventUserExistenceErrors='ENABLED',
        EnableTokenRevocation=True,
        EnablePropagateAdditionalUserContextData=True,
        AuthSessionValidity=15
    )

```

### Environment

```markdown
- OS:
- LocalStack:
```

**Comment by vt-rcheng** [comment]
I am also not sure why the client id of "CustomEmailSender_SignUp" event is "CLIENT_ID_NOT_APPLICABLE"
when sign up is performed, a client id is specified. other trigger event seems to have client_id value in them.

**Comment by giograno** [comment]
Hi @vt-rcheng, thanks for reporting the issue. Could you give us a few more details on how you generate the ciphertext in input? Have you tried to provide the key id to the `awslocal kms decrypt` command? Thank you 🙏

**Comment by vt-rcheng** [comment]
I didn't generate the ciphertext, localstack did when it sends out the CustomEmailSender_SignUp trigger. You will have to setup a cognito user pool and then sign up a user using email address to trigger the event. I have tried kms decrypt command, see my ticket description, and it did not work. The only way for me to decrypt is locally with aws_encryption_sdk. So I feel it is localstack's bug somewhere....

**Comment by giograno** [comment]
Hi @vt-rcheng, I've been investigating the issue a bit. According to the official [AWS docs](https://docs.aws.amazon.com/encryption-sdk/latest/developer-guide/introduction.html#intro-compatibility), the AWS KMS Decrypt operation cannot decrypt the encrypted message the AWS Encryption SDK returns.
I was also able to verify this behavior in one of our test ran against AWS.

We released a small set of parity fixes in our `latest` Docker image, based on what you reported. In particular:
- the ClientId in the event is now correctly reported;
- the event now also contains a bunch of data (e.g., user attributes) that were absent before.
Please let us know if you find any other issues 🙏
