### ISSUE TITLE
bug: CreateFlowLogs with S3 log destination fails to discover bucket

### ISSUE THREAD

**Issue by viren-nadkarni** [localstack/localstack#10773]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`EC2:CreateFlowLogs` when used with the S3 log destination type fails with following error:

```
$ awslocal ec2 create-flow-logs --resource-ids vpc-b996311b --resource-type VPC --log-destination-type s3 --log-destination arn:aws:s3:::flowlogs 
{
    "FlowLogIds": [],
    "Unsuccessful": [
        {
            "Error": {
                "Code": "400",
                "Message": "LogDestination: flowlogs does not exist."
            },
            "ResourceId": "vpc-b996311b"
        }
    ]
}
```

This is despite the S3 bucket existing:
```
$ awslocal s3 ls
2024-05-06 19:27:15 flowlogs
```

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

```
awslocal ec2 create-vpc --cidr-block 10.0.0.0/24 --query Vpc.VpcId --output text

awslocal s3 mb s3://flowlogs

awslocal ec2 create-flow-logs --resource-ids VPC --resource-type VPC --log-destination-type s3 --log-destination arn:aws:s3:::flowlogs 
```

### Environment

```markdown
- OS: jammy
- LocalStack: latest
```

### Anything else?

This occurs because in the Moto implementation of CreateFlowLogs, the S3 backend is directly accessed.

https://github.com/getmoto/moto/blob/dea4a98b64fe8b8a8d7b02e5446756d1b439af55/moto/ec2/models/flow_logs.py#L225-L231

On the other hand, the bucket lives in the S3 provider in LocalStack and the Moto backend is empty really.

**Comment by arunsriniv** [comment]
I am also facing this issue. Is there any workaround for this issue or a fix is required?
