### ISSUE TITLE
bug: ListSubscriptionsByTopic no longer paginates results

### ISSUE THREAD

**Issue by matt-phylum** [localstack/localstack#10796]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Regardless of how many subscribers you have, ListSubscriptionsByTopic returns all of them in a single page.

### Expected Behavior

ListSubscriptionsByTopic should paginate results, similar to how AWS does it and previous versions of LocalStack did it, so that tests of what happens when there are multiple pages work correctly.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

Localstack is started as part of a custom test environment. 101 e-mails are registered via Subscribe, and then the subscriptions are retrieved using ListSubscriptionsByTopic.

### Environment

```markdown
- OS: localstack/localstack container
- LocalStack: localstack/localstack@latest (sha256:f9310db87d9d76c449918a849562303b1c53f77c3598fdcb9c6cd7843d0f8cb6?)
```

### Anything else?

This was working yesterday (2024-05-07). It looks like #10788 replaced the existing implementation that supported pagination with a new one that doesn't. ListSubscriptions is probably similarly affected.

**Comment by bentsku** [comment]
Hello @matt-phylum and thanks for the report!

Yes, this bug fix for cross-account subscriptions introduced the small change in behavior, I'll re-introduce the pagination shortly. Thanks again for the report.
