### ISSUE TITLE
feature request: SES to SNS set_identity_notification_topic

### ISSUE THREAD

**Issue by ShedPlant** [localstack/localstack#10799]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

I have a SES Identity with Identity Notification Topics set up for Bounce, Complaint and Delivery. No Configuration Set is used.

It works in production i.e. every time an email is sent, something is published onto the SNS Topic and I can have something subscribe to the topic and do something with it.

In localstack I can see that some SES -> SNS support was added by https://github.com/localstack/localstack/pull/7207 . 
However I _think_ this only works for Configuration Sets and not the simpler 'set identity notification topic' command?

I have started localstack 3 from docker image and my resource setup is like:
```python
email_event_topic_arn = (sns_client.create_topic(
    Name="email-event-topic",
))["TopicArn"]
my_domain = "whatever.net"

ses_client.verify_domain_identity(Domain=my_domain)

ses_client.set_identity_notification_topic(
    Identity=my_domain,
    NotificationType="Delivery",
    SnsTopic=email_event_topic_arn,
)
```

I can see in localstack's logs:
```
AWS sns.CreateTopic => 200
AWS ses.VerifyDomainIdentity => 200
AWS ses.SetIdentityNotificationTopic => 200
```

If I test sending email in isolation, I can use localstack's HTTP API `/_aws/ses` to retrieve it ✅ .
If I post directly onto the email event topic, my subscriber lambda is invoked and does what it needs to do ✅ .
However, sending the email doesn't cause my email event topic subscriber lambda to be invoked 🔴 . 

Is this not supported yet or have I done something wrong?

Thanks for all your work on localstack 🖖 !

**Comment by dhruv-goyal-10** [comment]
Hey there. I was also facing the same issue. Is there any progress for the same?

Thanks
