### ISSUE TITLE
bug: make bucket returns 308 Permanent Redirect

### ISSUE THREAD

**Issue by jgagnon44** [localstack/localstack#10797]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am using the localstack Helm chart - please let me know if I should direct this issue there (any idea where?) instead.

I am working through modifying the deployment to satisfy pod security requirements.
I am running into a situation where I'm getting the following message in the localstack pod log:
```
LocalStack supervisor: Shutting down localstack (PID 15)...
make_bucket failed: s3://dex1 An error occurred (308) when calling the CreateBucket operation: Permanent Redirect
LocalStack supervisor: exiting
```
Does anyone have an idea what could be causing this?

### How are you starting LocalStack?

Custom (please describe below)

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

The localstack Helm chart (and the client application that needs to use it) are installed via Helm chart artifacts onto a Kubernetes cluster. A tool called Kubeapps is being used (for this use case) to deploy the charts to the cluster.

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

In the localstack Helm chart values.yaml file, the following start up script is used to create a profile and a bucket:

    awslocal configure set profile.localstack.aws_access_key_id my_user
    awslocal configure set profile.localstack.aws_secret_access_key my_password
    awslocal configure set profile.localstack.region us-east-1
    awslocal s3 mb s3://dex1 --profile localstack --endpoint-url=http://localstack.devhost.beast-code-demo.com

The endpoint URL makes use of a host name set up in an Ingress object configured elsewhere in the localstack chart values.

### Environment

```markdown
- OS: Ubuntu 20.04
- LocalStack:

LocalStack version: 3.4.1.dev
LocalStack build date: 2024-05-08
```

**Comment by bentsku** [comment]
Hello! 

I believe this issue was resolved in the community Slack by @simonrw.

The solution was to use `localhost:4566` in the `--endpoint-url` of the command, as the init scripts are running inside the LocalStack container and not outside of it where the Kubernetes configuration would have impact. 

I'll close the issue, but feel free to comment or re-open if there's still anything. Thanks!
