### ISSUE TITLE
APIGateway Lambda *custom* integration (as opposed to proxy integration).  Is it supported?

### ISSUE THREAD

**Issue by cspotcode** [localstack/localstack#1080]
Our backend uses APIGateway's "Lambda custom integration" which is different from the "Lambda proxy integration."  Is the custom integration supported in localstack?

We use type == "AWS" instead of type == "AWS_PROXY"
https://docs.aws.amazon.com/apigateway/api-reference/resource/integration/#type

I looked at the code, and it seems like localstack only supports AWS_PROXY integration for calling lambda functions from apigateway?

**Comment by saern** [comment]
We too have this requirement of `--type AWS` rather than `--type AWS_PROXY`, resulting in: `{"message": "API Gateway integration type \"AWS\" for method \"GET\" not yet implemented"}`. Is there anything we can do to help get this supported?

**Comment by whummer** [comment]
Thanks for reporting @cspotcode @ghost . This has been implemented in the meanwhile - an integration test and some refactoring/enhancements have been added in #2820 . When you get a chance, can you please give it another try with the `latest` version of the Docker image? Please report here if the problem persists. Thanks
