### ISSUE TITLE
EventBridge is still called 'Cloud Watch Events' in the resource browser

### ISSUE THREAD

**Issue by ben04rogers** [localstack/localstack#10804]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://github.com/localstack/localstack/assets/47819009/1892e5a4-5051-4bae-9beb-deaedadcb3b0)

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal s3 mb s3://mybucket

### Environment

```markdown
- OS:
- LocalStack:
```

**Comment by maxhoheiser** [comment]
Dear @ben04rogers , thank you for bringing this to our attention, we just released a new build of our web and desktop app that fixes the wrong name for EventBridge.
