### ISSUE TITLE
bug: Cannot create an SQS queue with FifoQueue: false

### ISSUE THREAD

**Issue by JavaScriptBach** [localstack/localstack#10812]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I can't create an SQS Queue using the AWS JavaScript SDK with FifoQueue: "false". Attempting to do so gives an error of `InvalidAttributeName: Unknown Attribute FifoQueue` and metadata saying that localstack responded with a 400.

### Expected Behavior

The queue is created successfully.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

docker-compose.yml

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```typescript
const sqs = new SQSClient({ endpoint: "http://localstack:4566", credentials: { accessKeyId: "foo", secretAccessKey: "bar", }, region: "us-east-1" });

await sqs.send(
    new CreateQueueCommand({
      QueueName: "test-queue",
      Attributes: {
        FifoQueue: "false",
      },
    }),
  );
```

### Environment

```markdown
- OS: Ubuntu 22.04
- LocalStack: 3.4.0
- @aws-sdk/client-sqs version: 3.370.0
```

**Comment by cloutierMat** [comment]
Hi @JavaScriptBach,

This is actually the behaviour observed with aws. Trying to create a queue with the `FifoQueue` attribute does result in an error.

```
▶ aws sqs create-queue --queue-name my-queue --attributes "{\"FifoQueue\":\"false\"}"

An error occurred (InvalidAttributeName) when calling the CreateQueue operation: Unknown Attribute FifoQueue.
```

This is a well known "issue" and the recommended approach is to either not set the attribute at all or to set it as `undefined`. Looking into it, I realised that Localstack was allowing for the original creation with the attribute set but wasn't allowing `create_queue` calls.

I just opened a PR that will bring parity with AWS behaviour.
