### ISSUE TITLE
Deleting S3 object tagging deletes the entire S3 object

### ISSUE THREAD

**Issue by tyleramos** [localstack/localstack#1083]
It appears that when deleting the tagging for an S3 object ends up deleting the entire S3 object instead of the tag.  

Here's a set of steps I used for replicating:
Started localstack with: `SERVICES=s3,lambda LAMBDA_EXECUTOR=docker localstack start --docker`
```
➜  aws --endpoint-url=http://localhost:4572 s3 mb s3://test-bucket
make_bucket: test-bucket
➜  aws --endpoint-url=http://localhost:4572 s3api put-object --bucket test-bucket --key test-file.txt --body ./test-file.txt
{
    "ETag": "\"c7e111bbf92ca25ca5c80edf7278c172\""
}
➜  aws --endpoint-url=http://localhost:4572 s3 ls s3://test-bucket --recursive
2019-01-10 14:03:02          6 test-file.txt
➜  aws --endpoint-url=http://localhost:4572 s3api put-object-tagging --bucket=test-bucket --key=test-file.txt --tagging="TagSet=[{Key=locked,Value=true}]"
➜  aws --endpoint-url=http://localhost:4572 s3api get-object-tagging --bucket=test-bucket --key=test-file.txt
{
    "TagSet": [
        {
            "Key": "locked",
            "Value": "true"
        }
    ]
}
➜  aws --endpoint-url=http://localhost:4572 s3api delete-object-tagging --bucket=test-bucket --key=test-file.txt
➜  aws --endpoint-url=http://localhost:4572 s3 ls s3://test-bucket --recursive
➜  
```

As you can see the test-file.txt was deleted from the bucket.  There are no warnings or errors in the localstack process output.  I've tested that this works as expected when using the CLI against a real AWS endpoint.

Specs:
```
➜  localstack --version
0.8.8
➜  aws --version
aws-cli/1.16.86 Python/3.6.5 Darwin/17.7.0 botocore/1.12.76
```

Let me know if you need any other information about how I'm running it.

**Comment by whummer** [comment]
Thanks for reporting @tyleramos . This is an upstream issue in moto, which we're using for S3 under the covers. The issue is that `DeleteObjectTagging` is missing in this dict in moto, and its default/fallback is `DeleteObject`: https://github.com/spulec/moto/blob/master/moto/s3/responses.py#L112 

It's been a while since you reported this issue, but do you think that you could create a small pull request against moto to fix this? Thanks!
