### ISSUE TITLE
How to debug an infinite loop?

### ISSUE THREAD

**Issue by amir-ziaei** [localstack/localstack#10841]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I run Localstack, it goes into an infinite loop. I'd like to get insights on why this is the case and how I should approach debugging it. 
It's most likely due to my init script. I don't know what exactly I'm doing wrong there. Ideally, I want Localstack to tell me I'm doing something wrong and error out. However, little information is shown in the console and I have to basically rely on guess and luck to find the source of the problem.

The log I keep seeing in the loop is:
```
2024-05-16T13:34:19.531 DEBUG --- [et.reactor-6] rolo.gateway.wsgi          : POST localhost:4566/
```

It keeps printing this into the console in a loop and eats all my machine's resources. How can I debug this issue?

### Expected Behavior

- Give better log insights and instruments to debug
- Perhaps prevent looping, and just kill the process or something

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

I can't share my init file because it's a proprietary project.

### Environment

```markdown
- OS:
- LocalStack:
  LocalStack version:
  LocalStack Docker image sha:
  LocalStack build date:
  LocalStack build git hash:

https://hub.docker.com/layers/localstack/localstack/latest/images/sha256-c79f44d73da47789652d38168c96d0f1f7926ea608c390e36e85de022e3e4841?context=explore
```

**Comment by thrau** [comment]
to increase the log level you can set `LS_LOG=trace-internal`, which should give you more indication of where requests are coming from
