### ISSUE TITLE
bug: Using IPv6 addresses in GATEWAY_LISTEN causes error

### ISSUE THREAD

**Issue by dietrich-iti** [localstack/localstack#10874]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Using IPv6 address(es) in the `GATEWAY_LISTEN` environment variable causes the LocalStack CLI to crash. This appears to be due to the way [HostAndPort.parse()](https://github.com/localstack/localstack/blob/81a32c9a296fc1ed37fcb50619aca5f393bd01b0/localstack/config.py#L499) is implemented -- it assumes that the only meaning of a colon in its input would be to separate a host and a port. Naturally this leads to trouble if I give it something like `'::1'`.

### Expected Behavior

The CLI accepts IPv6 addresses in `GATEWAY_LISTEN`, handling them the same way it does IPv4.

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    GATEWAY_LISTEN=127.0.0.1,::1 localstack start -d

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    N/A

### Environment

```markdown
- OS: macOS Sonoma 14.4.1
- LocalStack:
  LocalStack version: 3.4.1.dev
  LocalStack Docker image sha: 53cb4b3e335239cc8542eb0fbd9a24be03c1bafecb7d003643209b39c58b9751
  LocalStack build date: 2024-04-25
  LocalStack build git hash: 9287822
```

### Anything else?

I encountered this issue while trying to work around another issue:

I was setting up the LocalStack Github CI Action. I configured my code to use `http://localhost:4566` as the AWS endpoint URL, so it would talk to the port being published by the LocalStack Docker container that the CI Action sets up. Unfortunately, in that environment `localhost` resolves to the IPv6 loopback address `::1`, so the connection from my code to LocalStack was failing. I tried to mitigate this by using `GATEWAY_LISTEN` to effectively add `[::1]:4566` to the ports published by the container, which is where I discovered the problem.

Ultimately I was able to find two workarounds. One was just using the IPv4 loopback address `127.0.0.1` directly, instead of `localhost`. The other, more satisfying one was setting `DOCKER_FLAGS="-p [::1]:4566:4566"`. That manages to make it to the place where the container is created, so it lets me use `localhost` without any trouble.

If it would be appropriate, I can file a separate bug for the issue of "Docker container doesn't publish its ports to IPv6" too.

**Comment by MarcelStranak** [comment]
Hi @dietrich-iti,
We provide [network troubleshooting guides](https://docs.localstack.cloud/references/network-troubleshooting/) and also [GitHub Actions guide](https://docs.localstack.cloud/user-guide/ci/github-actions/).

> LocalStack only binds to IPv4 addresses (e.g. 127.0.0.1).
