### ISSUE TITLE
bug: localstack won't start ( M1, cli 3,4.0, Docker Desktop 4.30.0 )

### ISSUE THREAD

**Issue by gkatsanos** [localstack/localstack#10905]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```
$ brew install localstack/tap/localstack-cli

==> Auto-updating Homebrew...
Adjust how often this is run with HOMEBREW_AUTO_UPDATE_SECS or disable with
HOMEBREW_NO_AUTO_UPDATE. Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
==> Auto-updated Homebrew!
Updated 3 taps (supabase/tap, homebrew/core and homebrew/cask).
==> New Formulae
apache-flink-cdc       cloudflare-cli4        llama.cpp              ocicl                  vedic
==> New Casks
bias-fx                      font-playwrite-ca            font-playwrite-in            font-playwrite-us-modern
blitz-gg                     font-playwrite-de-la         font-playwrite-it-moderna    font-playwrite-us-trad
font-playwrite-au-nsw        font-playwrite-es            font-playwrite-it-trad       font-playwrite-za
font-playwrite-au-qld        font-playwrite-es-deco       font-playwrite-mx            hopper-disassembler
font-playwrite-au-sa         font-playwrite-fr-moderne    font-playwrite-ng-modern     mac-mouse-fix@2
font-playwrite-au-tas        font-playwrite-id            font-playwrite-nz            nessus
font-playwrite-au-vic        font-playwrite-ie            font-playwrite-tz

You have 4 outdated formulae installed.

==> Fetching localstack/tap/localstack-cli
==> Downloading https://github.com/localstack/localstack-cli/releases/download/v3.4.0/localstack-cli-3.4.0-darwin-ar
Already downloaded: /Users/gkatsanos/Library/Caches/Homebrew/downloads/7052f16917a6149cadd17ea908a6cb0e99419ed5316a5adce4e54fce8207140f--localstack-cli-3.4.0-darwin-arm64.tar.gz
==> Installing localstack-cli from localstack/tap
🍺  /opt/homebrew/Cellar/localstack-cli/64: 890 files, 50.6MB, built in 1 second
==> Running `brew cleanup localstack-cli`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
~ $ localstack start -d

     __                     _______ __             __
    / /   ____  _________ _/ / ___// /_____ ______/ /__
   / /   / __ \/ ___/ __ `/ /\__ \/ __/ __ `/ ___/ //_/
  / /___/ /_/ / /__/ /_/ / /___/ / /_/ /_/ / /__/ ,<
 /_____/\____/\___/\__,_/_//____/\__/\__,_/\___/_/|_|

 💻 LocalStack CLI 3.4.0
 👤 Profile: default

[16:46:09] starting LocalStack in Docker mode 🐳                                                   localstack.py:495
           preparing environment                                                                   bootstrap.py:1269
           configuring container                                                                   bootstrap.py:1277
           container image not found on host                                                       bootstrap.py:1258
[16:46:57] download complete                                                                        bootstrap.py:1262
```

![image](https://github.com/localstack/localstack/assets/1768834/52526e16-c2d5-462e-bdb7-9094970e9b9b)

~ $ localstack status services
❌ Error: could not connect to LocalStack health endpoint at http://localhost.localstack.cloud:4566
~ [1]$ sudo lsof -i :53
Password:
COMMAND   PID           USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
mDNSRespo 256 _mdnsresponder   59u  IPv4 0x1a366424b00a1f85      0t0  UDP *:domain
mDNSRespo 256 _mdnsresponder   60u  IPv6 0x1a366424b00a5395      0t0  UDP *:domain
mDNSRespo 256 _mdnsresponder   61u  IPv4 0x1a36642e497c145d      0t0  TCP *:domain (LISTEN)
mDNSRespo 256 _mdnsresponder   62u  IPv6 0x1a366424b15a5045      0t0  TCP *:domain (LISTEN)
~ $

### Expected Behavior

container starts

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal s3 mb s3://mybucket

### Environment

```markdown
- OS: Mac 12.6.2 (21G320)
- LocalStack:
  LocalStack version: 3.4.0
  LocalStack Docker image sha: bd02bb6f1e18574996ec995f882ef09422dbc26714453346a666a298965a8261 
  LocalStack build date: 
  LocalStack build git hash:
```

### Anything else?

🤷

**Comment by MarcelStranak** [comment]
Thank you for bringing this to our attention. We are aware of the [recent changes in Docker Desktop](https://docs.docker.com/desktop/release-notes/#4300) and currently suggest the following workarounds:

1. **Uncheck the corresponding box in Docker Desktop Settings:**
   Follow the steps illustrated in the screenshot or in our documentation [here](https://docs.localstack.cloud/user-guide/tools/dns-server/#system-dns-configuration) to disable it.
![image](https://github.com/localstack/localstack/assets/97876429/4479578d-18e1-4fd1-9403-26318c7f4700)


2. **Start LocalStack with a specific DNS address:**
   Run the following command:
   ```sh
   DNS_ADDRESS=0 localstack start
   ```

3. **Modify your `docker-compose.yml` file:**
   Remove port 53 as indicated in our [standard `docker-compose.yml` file](https://github.com/localstack/localstack/blob/master/docker-compose-pro.yml).

Please let us know if these solutions resolve the issue for you. If you need further assistance, feel free to reach out.

**Comment by rafrafek** [comment]
Is it resolved so that it works without changing the Docker settings, or is it resolved so that it now shows an error message and instructions to fix it in the terminal instead of `starting LocalStack in Docker mode 🐳` and hanging forever?

**Comment by MarcelStranak** [comment]
@rafrafek, we have updated the localstack cli as well, you can find the update in the docs as well https://github.com/localstack/docs/pull/1325.

**Comment by rafrafek** [comment]
I see, so it will no longer hang forever even with `--host-dns` thanks to removing the broken detection code in #11011

> 2. The port usability detection, which was broken in the docker desktop case, is removed now. This means if a user with port 53 already taken tries to set the flag, the docker exception explaining the failure to bind the port will be returned.

Thanks!
