### ISSUE TITLE
bug: Latest localstack doesn't support message-system-attribute-names in sqs 

### ISSUE THREAD

**Issue by kingan379** [localstack/localstack#10908]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently, passing **message-system-attribute-names** to localstack when receiving messages from sqs, does not work. This is a change that AWS introduced recently and is really important, because the previous argument (attribute-names) has been deprecated. 
More information: https://awscli.amazonaws.com/v2/documentation/api/latest/reference/sqs/send-message.html 

### Expected Behavior

Message-system-attribute-names parameter works when receving messages in sqs.

### How are you starting LocalStack?

Custom (please describe below)

### Steps To Reproduce

aws --endpoint-url=http://localhost:4566 sqs receive-message ....

### Environment

```markdown
- OS: Ubuntu 20.04.6 LTS
- LocalStack:
  LocalStack version:2.4.0 (also tried latest)
  LocalStack Docker image sha:
  LocalStack build date:
  LocalStack build git hash:
```

**Comment by HenrikPublic** [comment]
This might be the reason:
https://github.com/localstack/localstack/blame/df6f0a42ef64d9b423610d43f8fefaf843dc157d/localstack-core/localstack/services/sqs/provider.py#L1195

Added in https://github.com/localstack/localstack/pull/10806

There is a comment in there from @alexrashed  about the TODO and another comment from @thrau  that a backlog item has been added.

**Comment by palarnab** [comment]
Just discovered this problem after debugging a complete flow. Since this is a blocker to update to AWSSDK.SQS (v3.7.301.x), would you be kind enough to inform any approximate timeline, when this would be available in localstack?

**Comment by alexrashed** [comment]
Thanks for the clarification, I was not aware that this is actually breaking any upgrades. We have prioritized this issue and will try to resolve this asap (we will try to get this in the latest image sometime this week).
