### ISSUE TITLE
bug: Athena: fail to download hive archive

### ISSUE THREAD

**Issue by reneewang21** [localstack/localstack#10918]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

hi team, I got the below error when trying to run the Athena image on LocalstackPro v3.4.0. It looks like the Hive 2.3.9 version is no longer available on [the Apache website](https://dlcdn.apache.org/hive/).

```
localstackpro-1  | 2024-05-29T00:07:15.578  WARN --- [    Thread-9] localstack.utils.archives  : Attempt 4. Failed to download archive from https://dlcdn.apache.org/hive/hive-2.3.9/apache-hive-2.3.9-bin.tar.gz: Failed to download https://dlcdn.apache.org/hive/hive-2.3.9/apache-hive-2.3.9-bin.tar.gz, response code 404
``` 

### Expected Behavior

No error should occur

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker-compose.yml

### Environment

```markdown
- OS:
- LocalStack:
  LocalStack version:
  LocalStack Docker image sha:
  LocalStack build date:
  LocalStack build git hash:
```

**Comment by krisgeus** [comment]
I posted this in the community slack and it got fixed in the latest image.
If you want to keep using the 3.4.0 tag you can patch it

Create a file called patch.sh
```
#!/bin/bash

sed -i -e 's#dlcdn.apache.org#archive.apache.org/dist#g' /opt/code/localstack/.venv/lib/python3.11/site-packages/localstack_ext/packages/hive.py

```
and mount it in your docker container:
`- "./patch.sh:/etc/localstack/init/boot.d/patch-hive-download.sh"  # boot hook`

**Comment by reneewang21** [comment]
> I posted this in the community slack and it got fixed in the latest image. If you want to keep using the 3.4.0 tag you can patch it
> 
> Create a file called patch.sh
> 
> ```
> #!/bin/bash
> 
> sed -i -e 's#dlcdn.apache.org#archive.apache.org/dist#g' /opt/code/localstack/.venv/lib/python3.11/site-packages/localstack_ext/packages/hive.py
> ```
> 
> and mount it in your docker container: `- "./patch.sh:/etc/localstack/init/boot.d/patch-hive-download.sh" # boot hook`

Thanks! I'm able to pull the latest image and fix the issue.
