### ISSUE TITLE
Kinesis dies after a few thousand messages

### ISSUE THREAD

**Issue by sourada-e5** [localstack/localstack#1091]
If I start a localstack container like this:
```docker run -d --name test -p 4568:4568 -e DATA_DIR=/tmp/localstack localstack/localstack```
then send a few thousand little messages to a stream, for instance by running something like the below Python code, the Kinesis service dies.

I narrowed this down to kinesalite dying with an "Illegal instruction" message when using the LevelDB backing store. When I upgraded the npm leveldown package to 4.0.1, this problem went away. (Update: it's possible I was fooling myself with this... I'm trying 4.0.1 again and it's not helping.)

```
import boto3

s = boto3.Session(profile_name='dev')
c = s.client('kinesis', region_name='us-west-2', endpoint_url='http://localhost:4568/')
try:
    c.create_stream(StreamName='test', ShardCount=1)
except:
    pass

d = 'foo'
def send_messages(n):
    for a in range(n):
        c.put_record(StreamName='test', PartitionKey='Data', Data=d)

send_messages(10000)
```

**Comment by sourada-e5** [comment]
gdb is telling me that when kinesalite dies, it's an illegal instruction in
```0x00007ffff0a24e53 in snappy::RawUncompress(snappy::Source*, char*) () from /opt/code/localstack/localstack/node_modules/leveldown/build/Release/leveldown.node```
Disabling compression in LevelDB does seem to fix the problem. This seems to indicate that maybe the Snappy build linked into the leveldown.node executable is bad. Disabling compression is a workaround I can use for the short term, so I won't be investigating any more deeply on this for now.
Here's the patch I used on `/opt/code/localstack/localstack/node_modules/kinesalite/db/index.js`
```
31c31
<   var db = levelup(options.path ? require('leveldown')(options.path) : memdown()),
---
>   var db = levelup(options.path ? require('leveldown')(options.path) : memdown(), {compression: false}),
```

**Comment by sourada-e5** [comment]
FYI, I'm using Docker for Mac 2.0.0.2

**Comment by asaushkin** [comment]
This bug affects me too. I found an issue #514 opened in December 2017 with the same error.

**Comment by Teaxtor** [comment]
I also came across this bug using Docker/Docker-Compose for Linux.
When building a custom docker image just with kiensalite inserted, everything's fine.
Most likely, because the binary is build during the image creation process.
Is there any way to trigger a leveldb binary build?

**Comment by whummer** [comment]
Thanks for the detailed report @sourada-e5 @asaushkin @selm0 - just tested this with the latest version of the Docker image, and the 10000 requests went smoothly. Closing this issue as resolved, but please feel free to re-open if you come across this issue again. Thanks!
