### ISSUE TITLE
Unable to update resource type "AWS::XXX::XXX", id "XXX"

### ISSUE THREAD

**Issue by labbedaine** [localstack/localstack#10927]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Localstack is unable to update resource on second deployment of a Lambda.

```
2024-05-30T01:00:31.746  WARN --- [functhread15] l.s.c.resource_provider    : Unable to update resource type "AWS::ApiGateway::RestApi", id "ServerlessRestApi"
2024-05-30T01:00:31.855  WARN --- [functhread15] l.s.c.resource_provider    : Unable to update resource type "AWS::ApiGateway::Deployment", id "ServerlessRestApiDeployment47fc2d5f9d"
2024-05-30T01:00:31.890  WARN --- [functhread15] l.s.c.resource_provider    : Unable to update resource type "AWS::ApiGateway::Stage", id "ServerlessRestApiProdStage" 
```

### Expected Behavior

APi Gateway should be updated and my point to the updated version of the Lambda function. Currently the API returns Internal Server Error due to the inability of updating the resource.

### How are you starting LocalStack?

With the `localstack` script

### Steps To Reproduce

```
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/hello-world
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api 
          Properties:
            Path: /hello
            Method: get
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: false
        EntryPoints:
        - app.ts
```

1. Execute `samlocal build && samlocal deploy`
2. Execute `samlocal build && samlocal deploy` again.

### Environment

```markdown
- OS: Mac OS
- LocalStack:
  LocalStack version: 3.4.1.dev
  LocalStack Docker image sha: sha256:68b4674620ba703d866377b5f868133f69ff7f143d8427a3c819c068e4617fc1
  LocalStack build date: 2024-05-29
  LocalStack build git hash: 287138e59
```

**Comment by pavantfnsw** [comment]
I am facing the same issue. Its unable to deploy the second time. Sample warning message displayed,
`2024-09-18T03:12:19.396  WARN --- [-functhread9] l.s.c.resource_provider    : Unable to update resource type "AWS::ApiGateway::RestApi", `

**Comment by simonrw** [comment]
Hi thanks for raising this issue.

Unfortunately support for updating resources is limited at the moment. This is something we are aware of, and hope to fix in the near future. See the [note in our CloudFormation documentation](https://docs.localstack.cloud/user-guide/aws/cloudformation/#features).

Please prefer re-creating your stack instead of updating it.
