### ISSUE TITLE
S3 ETag header should not be returned for KMS encrypted objects

### ISSUE THREAD

**Issue by kgncan** [localstack/localstack#1092]
The ETag header should **not** be returned for S3 put requests, when a server side KMS encryption key is set.

I can't find the documentation reference for this, however, here's the code reference in the Java SDK [Version 2](https://github.com/aws/aws-sdk-java-v2/blob/a0379920f54cba715773f821ac5d237be8a47985/services/s3/src/main/java/software/amazon/awssdk/services/s3/checksums/ChecksumsEnabledValidator.java#L104), and [Version 1](https://github.com/aws/aws-sdk-java/blob/5fb7554098a60228347ab823ddde06567f1ef85c/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/AmazonS3Client.java#L1485). Also see [SkipMd5CheckStrategy.java#L197](https://github.com/aws/aws-sdk-java/blob/5fb7554098a60228347ab823ddde06567f1ef85c/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/internal/SkipMd5CheckStrategy.java#L197), [SkipMd5CheckStrategy.java#L54](https://github.com/aws/aws-sdk-java/blob/5fb7554098a60228347ab823ddde06567f1ef85c/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/internal/SkipMd5CheckStrategy.java#L54), [SkipMd5CheckStrategy.java#L245](https://github.com/aws/aws-sdk-java/blob/5fb7554098a60228347ab823ddde06567f1ef85c/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/internal/SkipMd5CheckStrategy.java#L245):

```
 * If SSE-C or SSE-KMS is involved then the Etag will be the MD5 of the ciphertext not the
 * plaintext so we can't validate it client side. Plain SSE with S3 managed keys will return an
 * Etag that does match the MD5 of the plaintext so it's still eligible for client side
 * validation.
```

This is causing a NullPointerException when using `aws-sdk-java-v2`

The previous version of the SDK skipped the checksum check if the kms headers were set (e.g, `x-amz-server-side-encryption-aws-kms-key-id`) 

```
 Caused by: java.lang.NullPointerException: null
	at software.amazon.awssdk.services.s3.checksums.ChecksumsEnabledValidator.validatePutObjectChecksum(ChecksumsEnabledValidator.java:129)
	at software.amazon.awssdk.services.s3.internal.handlers.AsyncChecksumValidationInterceptor.afterUnmarshalling(AsyncChecksumValidationInterceptor.java:86)
```

Additionally, I tried to set a CORS configuration which does not expose the etag header (following the [relevant code](https://github.com/localstack/localstack/blob/0f07aac326af45da977b468833a4e0e3ef25c755/localstack/services/s3/s3_listener.py#L232)), however, it is still returned.

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-85) by [Unito](https://www.unito.io/learn-more)

**Comment by kgncan** [comment]
Raised an issue with AWS SDK as no longer sure if the behaviour is wrong

**Comment by kgncan** [comment]
Confirmed the Localstack behaviour is wrong - the header `x-amz-server-side-encryption: aws:kms` should be included in the response too.

**Comment by macnev2013** [comment]
Hi @kgncan, Thanks for reporting the issue.
This should be fixed in the latest version of `localstack`. Can you please try again with the latest docker image of `localstack`? 
Thanks.
