### ISSUE TITLE
UnknownEndpoint s3.localhost.localstack

### ISSUE THREAD

**Issue by SureshKumar-sterlingcheck** [localstack/localstack#10943]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Inaccessible host: `s3.localhost.localstack.cloud' at port `4566'. This service may not be available in the `us-west-2' region.  
  code: 'UnknownEndpoint',
  region: 'us-west-2',
  hostname: 's3.localhost.localstack.cloud',
  retryable: true,
  originalError: Error: connect ECONNREFUSED 127.0.0.1:4566

### Expected Behavior

Should access

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce
docker-compose.yml file below:

version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

### Environment

```markdown
- OS:Windows
- LocalStack:
  LocalStack version:3.8
  LocalStack Docker image sha: localstack/localstack
  LocalStack build date:
  LocalStack build git hash:
```

### Anything else?
run  the integration test, the test fails
_No response_

**Comment by MarcelStranak** [comment]
Hi @SureshKumar-sterlingcheck, can you please share a reproduction code/sample that is failing? Thanks.
