### ISSUE TITLE
Startup script attempts to access network server

### ISSUE THREAD

**Issue by strk** [localstack/localstack#1098]
Starting localstack triggers access to central.maven.org, failing which (timeout) results in an inability to start the service. Is it possible to disable that access attempt ?

**Comment by strk** [comment]
The script does not seem to honour the `http_proxy` and `https_proxy` environment variables, which make things worst

**Comment by whummer** [comment]
Thanks for reporting @strk, the central.maven.org network access should not happen anymore in the latest version. If you're still seeing this behavior, then please report here with instructions to reproduce. Thanks!
