### ISSUE TITLE
bug: StepFunctions parallel states don't recognize "Parameters" field correctly.

### ISSUE THREAD

**Issue by northvankiwiguy** [localstack/localstack#11004]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In AWS Step Functions, the "parallel" state type provides the option of specifying the branch input using the `Parameters` field. However, LocalStack always passes the state's input as the input to each parallel branch.

I notice that there's no mention of `Parameters` in the AWS documentation (https://docs.aws.amazon.com/step-functions/latest/dg/amazon-states-language-parallel-state.html), but my tests indicate that it does work. 

### Expected Behavior

If the `Parameters` field is present in the Parallel state, the resulting JSON object should be used as input to each of the branches. However, if `Parameters` is not specified, the state's input should be used.

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    localstack start

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```
awslocal stepfunctions create-state-machine --name "parallel-test" --definition '{ "StartAt": "Parallel", "States": { "Parallel": { "Type": "Parallel", "Branches": [ { "StartAt": "Pass 1", "States": { "Pass 1": { "Type": "Pass", "End": true } } }, { "StartAt": "Pass 2", "State
s": { "Pass 2": { "Type": "Pass", "End": true } } } ], "End": true, "Parameters": { "a": 1 } } } }' --role-arn arn:aws:iam::000000000000:role/Admin

awslocal stepfunctions start-execution --state-machine-arn arn:aws:states:us-east-1:000000000000:stateMachine:parallel-test --input '{ "b": 2 }'
   
awslocal stepfunctions describe-execution --execution-arn arn:aws:states:us-east-1:000000000000:execution:parallel-test:e5888bd5-023f-4b8c-b4ae-83f9f705153d
```
   
Incorrect output: `"output": "[{\"b\":2},{\"b\":2}]",`

The correct output according to AWS is: `"output": "[{\"a\":1},{\"a\":1}]"`

### Environment

```markdown
- OS: MacOS, Amazon Linux
- LocalStack: 
  LocalStack version: 3.4.1.dev
  LocalStack Docker image sha: sha256:0378e35be1113cbe775fe9fe9973eae61adb6a13e3cf918805143975215e596d
  LocalStack build date: 2024-06-11
  LocalStack build git hash: 8e5b9ff2c
```

**Comment by MEPalma** [comment]
@northvankiwiguy thank you for your ongoing efforts in reporting issues with the Step Functions project! Your contributions are truly appreciated and play a significant role in helping us improve parity with AWS Step Functions. We've recently merged some updates intended to address the issue you raised. If possible, could you kindly confirm whether this resolves the issue so we can proceed with closing the bug report? Thanks again!

**Comment by northvankiwiguy** [comment]
Thanks, I'll take another look, and let you know early next week. I appreciate the fix!

**Comment by northvankiwiguy** [comment]
I've re-tested, and the `Parameters` field now seems to be recognized correctly. Thanks for fixing this!
