### ISSUE TITLE
bug: SQS -> Lambda only trigger once a minute

### ISSUE THREAD

**Issue by muttonhead** [localstack/localstack#11003]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have a setup of our application sending events to EventBridge -> SQS -> Lambda, with the SQS queue it only triggers the lambda with a single batch every minute even though it is backing up with messages. Removing the SQS queue and going straight to Lambda from EventBridge does not experience this. This happens both with a batch size of 1 or 10.

```
24-06-10T18:38:05.923  INFO --- [et.reactor-7] localstack.request.http    : POST /_localstack_lambda/3634a661eab2c29fe4b2c024611cca78/invocations/d4e0d313-a238-4d92-abc8-b29adbf4bae0/logs => 202
2024-06-10T18:38:05.942  INFO --- [et.reactor-0] localstack.request.http    : POST /_localstack_lambda/3634a661eab2c29fe4b2c024611cca78/invocations/d4e0d313-a238-4d92-abc8-b29adbf4bae0/response => 202
2024-06-10T18:39:07.003  INFO --- [et.reactor-3] localstack.request.http    : POST /_localstack_lambda/3634a661eab2c29fe4b2c024611cca78/invocations/689a93d9-4d1a-486d-a553-458a949c639e/logs => 202
2024-06-10T18:39:07.004  INFO --- [t.reactor-14] localstack.request.http    : POST /_localstack_lambda/3634a661eab2c29fe4b2c024611cca78/invocations/689a93d9-4d1a-486d-a553-458a949c639e/response => 202
```

### Expected Behavior

I would expect the lambda to keep running with batches until the queue is empty and to run quickly, this same setup in AWS results in pretty instant Lambda invocations.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

```
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack-pro:latest
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
      - "443:443"
    environment:
      # Activate LocalStack Pro: https://docs.localstack.cloud/getting-started/auth-token/
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN}
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
      - PERSISTENCE=${PERSISTENCE:-1}
      - HOSTNAME_EXTERNAL=localhost.localstack.cloud
      - SQS_ENDPOINT_STRATEGY=off
      - SNAPSHOT_FLUSH_INTERVAL=600
      - SNAPSHOT_LOAD_STRATEGY=ON_STARTUP
      - DYNAMODB_HEAP_SIZE=2G
      - EVENT_RULE_ENGINE=java
    volumes:
      - localstack-data:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

1. Create a SQS Queue
2. Create a lambda that triggers on an SQS queue
3. Create an EventBridge rule to match events and send to SQS
4. Send a number of events that match greater than batch size

### Environment

```markdown
- OS: Ubuntu 22.04
- LocalStack:
  LocalStack version: 3.4.1.dev20240604121021
  LocalStack Docker image sha: d31bd406268c987da8ea05f8109187f8ef55d79f690fc3133f1076d71b5d053c
  LocalStack build date: 2024-06-04
  LocalStack build git hash: b08d646
```

**Comment by maxhoheiser** [comment]
@muttonhead  thank you for bringing this to our attention, if I understood you correctly you encounter the issue that lambda does not pick up the events queued in the SQS queue correctly. 
Could you please confirm that the events are sent to the SQS queue correctly? Also, are you using `put_events` for each entry or batching multiple events together with a single `put_events`?

To replicate your issue and be able to move forward with a fix we would need a working sample from you - ideally, aws cli commands that you use to deploy all resources send the events, and test that lambda execution is as expected. 
Thank you :)

**Comment by joe4dev** [comment]
@muttonhead This issue is likely caused by our legacy Lambd Event Source Mapping implementation and should be resolved now. Does the issue persist with LocalStack 4.0 and our new Lambda Event Source Mapping implementation since [v3.8.0](https://blog.localstack.cloud/localstack-release-v-3-8-0/#new-default-lambda-event-source-mapping-implementation) (Oct'24)?
Feel free to re-open the issue, if so. Looking forward to hearing your feedback 👂 

We actively improve the SQS polling behavior (e.g., https://github.com/localstack/localstack/pull/11945).
/cc @gregfurman
