### ISSUE TITLE
Consider adding a prefix to docker environment variables

### ISSUE THREAD

**Issue by gilbsgilbs** [localstack/localstack#1102]
Hi,

Since environment variables are global, I think they should be prefixed by `LOCALSTACK_` in the docker image. For example `SERVICES` environment variable might conflict at some point with something else, so naming it `LOCALSTACK_SERVICES` would be nicer.

This could be optional to avoid breaking changes. Localstack would look for `LOCALSTACK_SERVICES` first, and if it's not defined would fallback to `SERVICES` just as today.

As far as I know, most (maybe all) official docker images do this. I think it's a good practice. See:
- https://hub.docker.com/_/postgres
- https://hub.docker.com/_/nginx
- https://hub.docker.com/_/mysql

Thanks.

**Comment by whummer** [comment]
Thanks @gilbsgilbs , sounds like a great idea. Do you think you could create a pull request with this change? That would be very much appreciated. I'd be happy to help out or provide guidance, if needed. Thanks!

**Comment by gilbsgilbs** [comment]
Hi @whummer. Thanks for assigning me the issue. I'll have a look at it ASAP.
