### ISSUE TITLE
Jenkins + High CPU/memory usage == dead localstack?

### ISSUE THREAD

**Issue by adamdavis40208** [localstack/localstack#1103]
When our build servers are running hot, any integration tests relying on localstack tend to fail.

We use docker-compose to start the apps, localstack, and then the tests.

Things proceed well, and then we start seeing "unable to connect" errors in the service logs (as if the container process was stopped, or the container fell over)

Doing a `docker inspect $(docker ps -aq)` doesn't show anything interesting (no containers were killed with OOMKilled or anything like that).

Any tips? Is this normal behaviour for localstack in docker-compose?

**Comment by denishamann1337** [comment]
Are you using your localstack in parallel locally?

**Comment by adamdavis40208** [comment]
It isn't a typical use case to do locally, but our jenkins slaves definitely run it in parallel on one host. 

Are there any gotchas we should we watching out for?

(And i'll run it in parallel on my local to see if we see the same issues)

Thanks for your time!

**Comment by denishamann1337** [comment]
With a 8 core machine we saw problems starting with 7 parallel localstack instances (when we were testing performance)

**Comment by whummer** [comment]
@denishamann1337 @adamdavis40208 There have been some performance improvements recently (reducing/limiting the heap space of the Java processes). Can you please give it a try with the `latest` version of the Docker image?

Also, have you tried configuring the set of service using the `SERVICES` environment variable?

**Comment by adamdavis40208** [comment]
Good to know! We took some time to keep our giant hungry build processes away from each other (not allowing them to spin up on the same jenkins slave) but I'll set this scenario up again and see what happens
