### ISSUE TITLE
feature request: AssociateSoftwareToken VerifySoftwareToken support in Cognito

### ISSUE THREAD

**Issue by akbisw** [localstack/localstack#11052]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

This allows users in cognito to set up TOTP as 2 Factor Authentication

### Anything else?

This is critical in testing MFA workflows

**Comment by giograno** [comment]
Hi @akbisw, we released an initial implementation for the `AssociateSoftwareToken` and `VerifySoftwareToken` in the `latest` Docker image. Feel free to report any additional issues 🙏
