### ISSUE TITLE
Can't retrieve SSM parameter using nodeJS aws-sdk lib

### ISSUE THREAD

**Issue by FreifeldRoyi** [localstack/localstack#1107]
I can't figure out why aws-sdk node lib won't retrieve ssm parameters.
Boto works just fine with the endpoint I set and decryption, but the node lib cannot retrieve the parameter.

**Comment by dmnlk** [comment]
Please write your `NodeJS` version, `AWS SDK for JavaScript` and sample code :)

**Comment by lmgarret** [comment]
Hi! I'm having the same issue, rather than opening a new issue I thought I could give the wanted info here instead. Please tell me if you prefer me to open a new issue instead :)

```NodeJS``` version: v10.16.0
```aws-sdk``` for ```JavaScript``` version: 2.499.0

Here is a sample TypeScript code reproducing the issue: 
```typescript
import AWS from 'aws-sdk';

const ssm: AWS.SSM = new AWS.SSM({
    region: 'localhost',
    endpoint: 'http://localhost:4583',
    accessKeyId: 'someId',
    secretAccessKey: 'someSecret',
});

main();

async function main() {
    await ssm
        .putParameter({
            Name: 'someName',
            Type: 'String',
            Value: 'someValue',
        })
        .promise()
        .catch((err: AWS.AWSError) => {
            console.error('Failed putting parameter');
            console.error(err);
        });

    await ssm
        .getParameter({
            Name: 'someName',
        })
        .promise()
        .catch((err: AWS.AWSError) => {
            console.error('Failed getting parameter');
            console.error(err);
        });
}
``` 

Thanks for your work!

**Comment by lmgarret** [comment]
I forgot to add that a simple fix to this is to specify an existing region.
Here, replace:
```typescript
const ssm: AWS.SSM = new AWS.SSM({
    region: 'localhost',
    endpoint: 'http://localhost:4583',
    accessKeyId: 'someId',
    secretAccessKey: 'someSecret',
});
``` 
with
```typescript
const ssm: AWS.SSM = new AWS.SSM({
    region: 'us-east-1',
    endpoint: 'http://localhost:4583',
    accessKeyId: 'someId',
    secretAccessKey: 'someSecret',
});
```
So this makes me believe that the issue comes from [aws-sdk-js](https://github.com/aws/aws-sdk-js).

**Comment by whummer** [comment]
Thanks for providing these details @lmgarret . Indeed, the region currently (1) needs to reflect a real AWS region name, and (2) needs to match the `DEFAULT_REGION` defined for the LocalStack process. Closing - please report here if there are any other issues related to this. Thanks
