### ISSUE TITLE
Cannot invoke lambda function with a large payload

### ISSUE THREAD

**Issue by sanjeevsiva17** [localstack/localstack#1110]
I have been trying to invoke lambda function, with a considerably large payload (2500 bytes) there is no error/success message. I tried using a small payload and it gets executed.

Tried using `print` inside the localstack code for better understanding, but could not getting anything helpful.

To Troubleshoot the problem, I tried to `DEBUG=1` and it works as of now. 

Here is the payload that I am passing.
`{
    "Records": [
      {
        "messageId": "eff958ee-d7fa-4291-8b5d-f9babb04c8e7",
        "receiptHandle": "AQEBiIlrIXLVwvJgJPmI3Qw9MFzOSEPB7Az3+hYqkC4cdDD0bFw8T43FSdLv2rb0VPJCas/5KA+nVnE0gA82REzTT6jPkw8L8ZOj98Kt52qGFdoWpZuK1HqFzA18BJAQg3/rWU0I/ClBwSuNGd5FStUUaEBNfhU+FQ4wDi6wdW7sVIIqGJ7HDHAl4qXSR1yD0QoRbjYgYbcDZu+yr5cg1SvWUpcAiWINjwu+N4yA9utEr4TYcY439XqZeVE1EwxNV7UIq8lJqRtTl1jvSya0hZWK0ng8i10NNUPGP+o/S4ByL9LfBgn13wFjYa0cDzoi7DlUNs+Kbr282R52w31mu+hQs0XxgCBrR4UCYEyvTiAFY0zCgnO5x1/rjPG8SaAYEPV5",
        "body": "{\n                \"Records\": [\n                    {\n                        \"eventVersion\": \"2.1\",\n                        \"eventSource\": \"aws:s3\",\n                        \"awsRegion\": \"us-east-1\",\n                        \"eventTime\": \"2019-01-17T10:56:49.275Z\",\n                 \"eventName\": \"ObjectCreated:Put\",\n                        \"userIdentity\": {\n                            \"principalId\": \"AWS:XXXXXXXX\"\n                        },\n                        \"requestParameters\": {\n                            \"sourceIPAddress\": \"180.151.69.66\"\n                        },\n                        \"responseElements\": {\n                            \"x-amz-request-id\": \"EB83377E620D5838\",\n                            \"x-amz-id-2\": \"q413p4G4uob6HMIPTz+g+EakQ/D0Rxr+EykRCItkVWyi0ATJNQI53aOaQ8LdW9Zj+MlpF9lWElo=\"\n   },\n                        \"s3\": {\n                            \"s3SchemaVersion\": \"1.0\",\n                            \"configurationId\": \"Bucket-SQS-Notification\",\n                            \"bucket\": {\n                                \"name\": \"test\",\n           \"ownerIdentity\": {\n                                    \"principalId\": \"AFG1YXBHBUKHW\"\n                                },\n                  \"arn\": \"arn:aws:s3:::test\"\n                            },\n                            \"object\": {\n               \"key\": \"123.eml\",\n                                \"size\": 1028307,\n                                \"eTag\": \"5e83856bca84110d17a33cddde8bda5b\",\n                                \"versionId\": \"UgQxpXhsIB9xudr67yfR9h4EiJiMNKZC\",\n                                \"sequencer\": \"005C405F712CC109C0\"\n                            }\n                        }\n                    }\n                ]\n            }",
        "attributes": [
          "Object"
        ],
        "messageAttributes": {},
        "md5OfBody": "7812759fd9e5f134a72b4617da56614c",
        "eventSource": "aws:sqs",
        "eventSourceARN": "arn:aws:sqs:us-east-1: XXXXXXX:XX",
        "awsRegion": "us-east-1"
      }
    ]
  }`

**Comment by whummer** [comment]
Thanks for reporting @sanjeevsiva17 

> To Troubleshoot the problem, I tried to DEBUG=1 and it works as of now.

Can you please post the output and any error logs from the terminal with `DEBUG=1` enabled?
