### ISSUE TITLE
bug: S3 Presign Upload URL (PUT) fails due to CORS

### ISSUE THREAD

**Issue by PascalArdex** [localstack/localstack#11112]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We are using LocalStack version 3.5
We have a .NET application using the AWS SDK
We use the S3 pre-sign PUT URLs upload to upload files into the S3 bucket
We are able to get the upload URL but the  actual file upload request is failing due to CORS
It used to work with 3.3

### Expected Behavior

PUT request to the S3 bucket should not be rejected due to CORS

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `docker-compose.yml`)

Starting with docker-compose
docker-compose up bug
docker-compose up aws-infrastructure
```
version: '3.8'
name: bug
services:

  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-bug}"
    image: localstack/localstack:3.5
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  aws-infrastructure:
    image: amazon/aws-cli
    entrypoint:
      - /bin/sh
      - -c
      - |
        echo "----------------------------------"
        echo "Creating S3 buckets"
        echo "----------------------------------"
        aws s3 mb s3://media-temp
        echo "----------------------------------"
        echo "Configuring CORS for media-temp bucket"
        echo "----------------------------------"
        cat <<EOF > cors-config.json
        {
          "CORSRules": [
            {
              "AllowedHeaders": ["*"],
              "AllowedMethods": ["PUT"],
              "AllowedOrigins": ["*"],
              "ExposeHeaders": ["ETag"]
            }
          ]
        }
        EOF
        aws s3api put-bucket-cors --bucket media-temp --cors-configuration file://cors-config.json
        echo "----------------------------------"
        echo "Done"
        echo "----------------------------------"
    environment:
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_ENDPOINT_URL: http://localstack:4566
      AWS_REGION: us-east-1


```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    aws s3 mb s3://media-temp
    aws s3api put-bucket-cors --bucket media-temp --cors-configuration file://cors-config.json

cors-config.json
```
        {
          "CORSRules": [
            {
              "AllowedHeaders": ["*"],
              "AllowedMethods": ["PUT"],
              "AllowedOrigins": ["*"],
              "ExposeHeaders": ["ETag"]
            }
          ]
        }
```

No errors appear in the command line
LocalStack logs are showing 
```
AWS s3.CreateBucket => 200
AWS s3.PutBucketCors => 200
```

Then I login into LocaStack > Services > S3 > <Bucket name> using Firefox
LocalStack shows an error popup "Network error"
In the console I see a lot of errors due to CORS
In LocalStack logs I see 
`AWS s3.ListObjectsV2 => 403 (AccessForbidden)`

Opening the Permissions tab show that the CORS config was NOT loaded correctly
I can manually set the CORS rule to workaround this problem
```
{
    "CORSRules": [
        {
            "AllowedHeaders": [
                "*"
            ],
            "AllowedMethods": [
                "PUT"
            ],
            "AllowedOrigins": [
                "app.localstack.cloud"
            ],
            "ExposeHeaders": [
                "ETag"
            ]
        }
    ]
}
```

Even if I set the AllowedOrigin to fit my own application the Presign upload still fails due to CORS

### Environment

```markdown
- OS: Windows / Docker
- LocalStack: 
  LocalStack version: 3.5.0
  LocalStack Docker image sha: 8d7b248e0bf5c462158344fe3915cf12461d65421b98c1f4158e3edfe2650a99
  LocalStack build date: 2024-06-13
  LocalStack build git hash: 54edb407d
```

**Comment by bentsku** [comment]
Hello @PascalArdex and thanks for your report!

I'm currently unable to reproduce the issue that you're mentioning. 

Regarding the issue with the Web Application, this is because you're configuring your CORS policy to only allow `PUT` requests, but the web application is calling `ListObjectsV2` which is a `GET` operation, and is then rejected.

Also, the format of your origin for the web app in your policy is wrong: you need to include the scheme:
`"AllowedOrigins": ["https://app.localstack.cloud"]`

Could you please set the `LS_LOG=trace` configuration flag in your Docker Compose and share the logs when the request from your application is rejected? 
Thank you!

**Comment by PascalArdex** [comment]
Hi,

Thank you for pointing this out. `AllowedOrigins` needed the scheme + `GET` method needed.
I think this used to work out of the box and default permissions are set automatically for `app.localstack.cloud` ?
![image](https://github.com/localstack/localstack/assets/131418329/c1376fdc-fd63-4177-ace1-f39261722ea0)

Correctly configured the S3 Presign Upload URL worked fine!

**Comment by bentsku** [comment]
Hi!

I believe adding the default permissions is only done when modifying/setting your CORS rules from the web application, to not "cut you off" directly from using it. If using the CLI, we are not interfering and adding our own CORS rules, to be in parity with AWS (some people might not use the web application and want to test in the exact same way as AWS).

We have some information about CORS in our S3 documentation: https://docs.localstack.cloud/user-guide/aws/s3/#configuring-cross-origin-resource-sharing-on-s3

> By default, LocalStack will apply specific CORS rules to all requests to allow you to display and access your resources through the LocalStack Web Application. If no CORS rules are configured for your S3 bucket, LocalStack will apply default rules unless specified otherwise.

So by default, if your bucket does not have rules configured, we are setting CORS not with the S3 configuration but with our global configuration. 

But if you specify rules yourself with an SDK or the CLI, we are only setting the rules you are sending out. Following the example on the documentation explains how to add the web application rules if you configure S3 with the AWS CLI. 

I hope that answers your question! Do you think we can consider the issue closed?

**Comment by PascalArdex** [comment]
Thank you so much ;-)
Just in case someone stumbles into this ticket.
The key part to have the S3 Presign Urls to work with LocalStack is to have the following env variables
```
                "AWS_ENDPOINT_URL": "http://localhost:4566"
                "AWS_ACCESS_KEY_ID": "test",
                "AWS_SECRET_ACCESS_KEY": "test",
```
