### ISSUE TITLE
Error while calling a Web Api hosted on local IIS from Lambda function executing in Docker container

### ISSUE THREAD

**Issue by nlee27** [localstack/localstack#1111]
I am getting an HttpClient error when I try to call a method on Web Api hosted on local IIS server. I have a lambda function that triggers when an object is added to S3 bucket. The lambda function is written in .Net code and needs to call a web api post method which is hosted on local IIS. 

How do I redirect the call to IIS server from inside the Lambda container. I have set LAMBDA_EXECUTOR to docker.

**Comment by whummer** [comment]
Thanks for reporting @nlee27 . Accessing services on your local machine from the Lambda container is dependent on your operating system.

For Linux, you can typically simply use the address of the Docker bridge (e.g., `172.17.0.1`). For MacOS, you can typically use the predefined domain name `host.docker.internal` - that might also work for Windows, although I'm not 100% sure.

If you have any updates on this issue, please share them here. Thanks
