### ISSUE TITLE
bug: GetAtt not extracting values properly from Stack Outputs when JSON form is used

### ISSUE THREAD

**Issue by lukasz-mazur2** [localstack/localstack#11128]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm not sure if this is limited to SSM Parameter only, but this is what I've observed in our use cases.

We have some complex templates that utilize PyPlate macros and json formatted parameters for nested stacks. 
I've simplified the scenario to the following:

Main stack - parent.yaml:
```AWSTemplateFormatVersion: '2010-09-09'
Resources:
  
  Param:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://standard-common-modules.s3.localhost.localstack.cloud/test-child2.yaml
      Parameters:
        Value: |-
            { 
              "Fn::GetAtt": "ChildParam.Outputs.Value"
            }
```
 
Child stacks:
- test-child2:
```
AWSTemplateFormatVersion: '2010-09-09'
Transform:
  - PyPlate
Parameters:
  Value:
    Type: String
Resources:
  ChildParam:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://standard-common-modules.s3.localhost.localstack.cloud/test-child.yaml
  Param:
    DependsOn: ChildParam
    Type: AWS::SSM::Parameter
    Properties:
      Name: test-param
      Type: String
      Value: |
        #!PyPlate
        import json
        output = json.loads(params['Value'])
Outputs:
  Name:
    Value: !Ref Param
  Value:
    Value: !GetAtt Param.Value
```

- test-child:
```
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  Param:
    Type: AWS::SSM::Parameter
    Properties:
      Name: child-param-name
      Type: String
      Value: child-2-param-name
Outputs:
  Name:
    Value: !Ref Param
  Value:
    Value: !GetAtt Param.Value
```

Everything seem to deploy properly from cloudformation perspective, but the actual value that GetAtt retrieved and put into the parameter value are all the available stack outputs

```$ awslocal ssm get-parameter --name test-param
{
    "Parameter": {
        "Name": "test-param",
        "Type": "String",
        "Value": "{'Name': 'child-param-name', 'Value': 'child-2-param-name'}",
        "Version": 1,
        "LastModifiedDate": 1719925660.265,
        "ARN": "arn:aws:ssm:eu-west-1:000000000000:parameter/test-param",
        "DataType": "text"
    }
}```

ChildParam nested stack description:

```$ awslocal cloudformation describe-stacks --stack-name test-stack-Param-cc
05b27a-ChildParam-e7870120
{
    "Stacks": [
        {
            "StackId": "arn:aws:cloudformation:eu-west-1:000000000000:stack/test-stack-Param-cc05b27a-ChildParam-e7870120/3c47eff4",
            "StackName": "test-stack-Param-cc05b27a-ChildParam-e7870120",
            "CreationTime": "2024-07-02T13:37:37.552000Z",
            "LastUpdatedTime": "2024-07-02T13:37:37.552000Z",
            "RollbackConfiguration": {},
            "StackStatus": "CREATE_COMPLETE",
            "DisableRollback": false,
            "NotificationARNs": [],
            "Capabilities": [
                "CAPABILITY_IAM",
                "CAPABILITY_NAMED_IAM",
                "CAPABILITY_AUTO_EXPAND"
            ],
            "Outputs": [
                {
                    "OutputKey": "Name",
                    "OutputValue": "child-param-name"
                },
                {
                    "OutputKey": "Value",
                    "OutputValue": "child-2-param-name"
                }
            ],
            "Tags": [],
            "EnableTerminationProtection": false,
            "DriftInformation": {
                "StackDriftStatus": "NOT_CHECKED"
            }
        }
    ]
}
```

### Expected Behavior

The same set of template on AWS with a json parameter:

![image](https://github.com/localstack/localstack/assets/149665539/dc5b44b5-b916-425b-b0a8-66d750a7f643)

results in:

![image](https://github.com/localstack/localstack/assets/149665539/13d8501f-b697-43a1-bdbd-02c647f6306c)

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run \
      --rm \
      --name localstack-main \
      -p 4566:4566 \
      -p 4510-4559:4510-4559 \
      -e LOCALSTACK_AUTH_TOKEN="$LOCALSTACK_AUTH_TOKEN" \
      -e LS_LOG=DEBUG  \
      -e POD_LOAD_CLI_TIMEOUT=3000 \
      -v /var/run/docker.sock:/var/run/docker.sock \
      localstack/localstack-pro:latest

### Environment

```markdown
- OS: Ubuntu 22.04.2 LTS (5.15.153.1-microsoft-standard-WSL2)
- LocalStack:
  LocalStack 3.5.1.dev20240702032247
  LocalStack Docker image sha: 815bc086e9e138ce7b1d358b677f40592ca16ad3a9860675fbb68a16556f87af
  LocalStack build date: 2024-07-02
  LocalStack build git hash: 2ac673d
```

**Comment by sannya-singal** [comment]
Hi @lukasz-mazur2! Thanks for reporting this issue. I tried running the following PyPlate macros template that uses json formatted parameters for `AWS::SSM::Parameter` resource type and it is getting properly deployed on localstack environment. 

```
AWSTemplateFormatVersion: "2010-09-09"
Description: tests String macro functions
Resources:
  Param:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "test-param"
      Type: "String"
      Value: |
        #!PyPlate
        import json
        output = []
        x = """{
        "xyz": "abc"
        }"""
        output.append(json.loads(x))
Transform: [PyPlate]
Outputs:
  Name:
    Value: !Ref Param
  Value:
    Value: !GetAtt Param.Value
```

Furthermore, I also confirmed these values are getting properly set in the `Outputs` of cloudformation:

```
{
    ...
            "Outputs": [
                {
                    "OutputKey": "Name",
                    "OutputValue": "test-param"
                },
                {
                    "OutputKey": "Value",
                    "OutputValue": "[{'xyz': 'abc'}]"
                }
            ],
   ...
}
```
 and also the `ssm` parameters for `test-param`:
 
 ```
{
    "Parameter": {
        "Name": "test-param",
        "Type": "String",
        "Value": "[{'xyz': 'abc'}]",
        "Version": 1,
        "LastModifiedDate": 1720593031.259,
        "ARN": "arn:aws:ssm:us-east-1:000000000000:parameter/test-param",
        "DataType": "text"
    }
}
```

Could you please check if this is working on your end and if you can still reproduce the issue? Meanwhile, I am continuing to investigate to see if I can reproduce the reported issue.

**Comment by lukasz-mazur2** [comment]
Hi @sannya-singal Thanks for looking into it.

Your scenario works for me as well, but mine is a bit different and maybe I've not explained this clear enough. 
Maybe this will help :)

This is how the nesting is done:
![image](https://github.com/localstack/localstack/assets/149665539/39864f33-6e91-4bae-98fe-6bbd006a6a56)
so in the parent template that I'm trying to deploy inside `Value` parameter I'm trying to pass the `GetAtt` function that is suppose to extract the SSM Parameter value from the double-nested stack (test-child.yaml)

I'm expecting it to get the `child-2-param-name` and set it as a value for `test-param` SSM Parameter instead what I'm getting is:

![image](https://github.com/localstack/localstack/assets/149665539/bf1cd3cd-8e77-4a2a-8a1e-f49d95e4562d)

**Comment by sannya-singal** [comment]
Thanks for the inputs @lukasz-mazur2, can you also let me know the commands that you are using to deploy these stacks on aws and localstack?

**Comment by sannya-singal** [comment]
I tried deploying the `test-child` stack and it deploys successfully on aws with correct outputs, but throws errors for `test-child2`.

**Comment by lukasz-mazur2** [comment]
What kind of error are You getting?

In both cases I have the `test-child.yaml` and `test-child2.yaml` uploaded to a s3 bucket and I'm just deploying `parent.yaml` via cli that ultimately deploys all 3 templates:

The cli command is simply:

`aws(local) cloudformation deploy --stack-name lm-test --template-file parent.yaml`

**Comment by sannya-singal** [comment]
`An error occurred (ValidationError) when calling the CreateChangeSet operation: Parameters: [Value] must have values`
thats the error I get.

**Comment by lukasz-mazur2** [comment]
Seems like You're trying to deploy `test-child2.yaml` directly and since it doesn't have a default value for `Value` parameter it fails.
I'm passing it from the parent stack, but it's also reproducible this way:

awslocal cloudformation deploy --stack-name lm-test --template-file test-child2.yaml --parameter-overrides Value='{"Fn::GetAtt":
"ChildParam.Outputs.Value"}'

**Comment by sannya-singal** [comment]
So I already tried deploying `parent.yaml` on aws but it resulted in an error: 

<img width="896" alt="image" src="https://github.com/localstack/localstack/assets/32308435/ba7ef863-f46c-453e-9b8a-a5d0504e3978">

and subsequently I tried to deploy the `test-child2.yaml`. Let me look into this.

**Comment by lukasz-mazur2** [comment]
It deploys successfully for me on both AWS and Localstack, so You must be missing something.

**Comment by sannya-singal** [comment]
Thanks @lukasz-mazur2 we are looking into it.

**Comment by pinzon** [comment]
Hi @lukasz-mazur2 , I was able to deploy  the initial templates and I believe that I understand the problem. Even if the Child2 stack has the same output in both AWS and Localstack. The test-param parameter has a different value stored in Localstack. I'll be working on this soon. 

![image](https://github.com/localstack/localstack/assets/18080804/04d34249-5e74-48a0-bc28-21b89b511126)
