### ISSUE TITLE
bug: Cloudfront not forwarding QueryStringParameters to ApiGateway

### ISSUE THREAD

**Issue by Garethp** [localstack/localstack#11127]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When we have a lambda sitting on an ApiGateway that's behind Cloudfront, hitting that lambda through the Cloudfront Distribution removes the `queryStringParameters` from the `event`

### Expected Behavior

Given a correctly configured Cloudfront Distribution, it should pass Query String Parameter and other metadata onto Api Gateway

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```ts
export class CloudfrontApiGateway extends Stack {
  constructor(scope: Construct, id: string, props: StackProps) {
    super(scope, id, props);

    const hostedZone = new PublicHostedZone(this, "HostedZone", {
      zoneName: "example.localhost.localstack.cloud",
    });

    const certificate = new Certificate(this, "Example", {
      domainName: "example.localhost.localstack.cloud",
    });

    const api = new RestApi(this, "test-api", {
      restApiName: "test-api",
      domainName: {
        domainName: "localstack-api-example.localhost.localstack.cloud",
        certificate,
      },
    });

    const distribution = new Distribution(this, "ApiCloudfront", {
      defaultBehavior: {
        origin: new HttpOrigin(
          "localstack-api-example.localhost.localstack.cloud",
          {
            protocolPolicy: OriginProtocolPolicy.HTTPS_ONLY,
          },
        ),
        allowedMethods: AllowedMethods.ALLOW_ALL,
        cachePolicy: CachePolicy.CACHING_DISABLED,
        originRequestPolicy: OriginRequestPolicy.ALL_VIEWER,
        viewerProtocolPolicy: ViewerProtocolPolicy.HTTPS_ONLY,
      },
      domainNames: ["example.localhost.localstack.cloud"],
      certificate: certificate,
    });

    new ARecord(this, "ARecord", {
      zone: hostedZone,
      recordName: "example.localhost.localstack.cloud.",
      target: RecordTarget.fromAlias(new CloudFrontTarget(distribution)),
    });

    const responseLambda = new Function(this, "hello-world", {
      runtime: Runtime.NODEJS_20_X,
      handler: "index.handler",
      code: Code.fromInline(
        "exports.handler = async (event) => ({statusCode: 201, body: JSON.stringify(event.queryStringParameters)})",
      ),
    });

    api.root.addMethod("GET", new LambdaIntegration(responseLambda));
  }
}
```

```sh
curl "https://example.localhost.localstack.cloud/?test=test"
```

### Environment

```markdown
- OS: Ubuntu 20.04
- LocalStack:
  LocalStack version: 3.5.1.dev20240702032247
  LocalStack Docker image sha: localstack/localstack-pro@sha256:815bc086e9e138ce7b1d358b677f40592ca16ad3a9860675fbb68a16556f87af
  LocalStack build date: 2024-07-02
  LocalStack build git hash: 2ac673d
```

### Anything else?

I've reproduced the issue here: https://github.com/Garethp/localstack-bugs/tree/apigateway-query-string-parameters
If you clone down the branch `apigateway-query-string-parameters`, run `yarn install`, and then `./start.sh` you should see the issue in action.

**Comment by bentsku** [comment]
Hello @Garethp and thanks for the report!

The fix has now been merged, and should be available in the `latest` Pro image. Feel free to pull it and give it a try. Thanks!

**Comment by teseo** [comment]
Hello @bentsku Javier Mellado here from RoS. I can see the latest release was 3.5 which is the one we're currently using and it seems to be the latest tag as well here on github. Is this the right image? `image: localstack/localstack-pro:3.5`

**Comment by teseo** [comment]
Hello @bentsku thanks for your message. Javier Mellado here from RoS. It looks like the latest image works for us. We'll be pulling `docker pull localstack/localstack-pro:latest@sha256:42f46367da83a8b34c6c732382c29148d328c0ed5a73ba5ea8e7f241b61b7081` until a new version and version tag is released

**Comment by bentsku** [comment]
Hello @teseo and sorry for the delay on that one!

Yes, for now, the fix is only present on the `latest` tag which is published from every commit on our main branch.
We're planning a tagged release next week on Thursday 25th of July (`3.6.0`), where the fix should be available.

Thanks for confirming it works for you now 😄 I'll close the issue, feel free if there's still anything.
