### ISSUE TITLE
Localstack user guide

### ISSUE THREAD

**Issue by suryacaprice** [localstack/localstack#1112]
I can see localstack is a very useful project and most of the developers use serverless framework these days . It would be helpful if the localstack team provides a simple user guide with the serverless https://serverless.com/ integration support for the locastack . As of now, only people who have high knowledge of this can only use it .

**Comment by arnagarjun** [comment]
or perhaps a plugin for serverless would be good too.
The currently available plugins does not seem be working and seems to have stopped active development.

**Comment by whummer** [comment]
Thanks for reporting @suryacaprice . The documentation is updated in #1143 (see new README section on Serverless). Please also refer to the documentation of the `localstack-serverless` plugin: https://github.com/localstack/localstack-serverless
