### ISSUE TITLE
Allow static naming of Local Stack's Docker container.

### ISSUE THREAD

**Issue by brettcooper** [localstack/localstack#1113]
I would like to be able to run Local Stack with Docker, but to be able to give the Docker container a static name of "localstack". Currently, Local Stack starts up in Docker with a random name.  If the name was static, I could configure all my microservices running in Docker to connect to "localstack" instead of some random named Docker container.  Perhaps an env variable could be used that can be overridden like LOCALSTACK_DOCKER_NAME or something?

**Comment by brettcooper** [comment]
Note to self: This can be done with docker-compose.yml "container_name:" property.

**Comment by whummer** [comment]
Sounds like a great suggestion, and should be easy to achieve by adding a flage here: https://github.com/localstack/localstack/blob/master/localstack/services/infra.py#L457

Would you be able to create a pull request @brettcooper ? That would be great. Thanks

**Comment by zelahi** [comment]
I apologize if I overstepped on anyone.  I submitted a PR to help with this @whummer

**Comment by whummer** [comment]
Thanks @zelahi !

**Comment by brettcooper** [comment]
Nope, didn't overstep @zelahi.  Been busy myself and haven't had a chance to implement this.  Thanks!
