### ISSUE TITLE
bug: GetResources() API in ResourceGroupsTaggingAPI is returning only VPC resources eventhough there are other resources with tags available

### ISSUE THREAD

**Issue by arunsriniv** [localstack/localstack#11147]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Only VPC resources are listed by GetResources() API. Other than VPC no other resource is listed in GetResources() API.

### Expected Behavior

Other tagged resources are also listed in listed in GetResources() API output

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker-compose.yaml

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

# awslocal ec2 create-vpc --cidr-block 10.0.0.0/16 --tag-specifications "ResourceType=vpc,Tags=[{Key=Name,Value=MyVPC}]"
{
    "Vpc": {
        "CidrBlock": "10.0.0.0/16",
        "DhcpOptionsId": "default",
        "State": "pending",
        "VpcId": "vpc-d5f72963",
        "OwnerId": "000000000000",
        "InstanceTenancy": "default",
        "Ipv6CidrBlockAssociationSet": [],
        "CidrBlockAssociationSet": [
            {
                "AssociationId": "vpc-cidr-assoc-ee1f36ad",
                "CidrBlock": "10.0.0.0/16",
                "CidrBlockState": {
                    "State": "associated"
                }
            }
        ],
        "Tags": [
            {
                "Key": "Name",
                "Value": "MyVPC"
            }
        ]
    }
}

# awslocal resourcegroupstaggingapi get-resources
{
    "ResourceTagMappingList": [
        {
            "ResourceARN": "arn:aws:ec2:us-east-1:000000000000:vpc/vpc-d5f72963",
            "Tags": [
                {
                    "Key": "Name",
                    "Value": "MyVPC"
                }
            ]
        }
    ]
}

# awslocal ec2 create-subnet --vpc-id vpc-d5f72963 --cidr-block 10.0.1.0/24 --tag-specifications "ResourceType=subnet,Tags=[{Key=Name,Value=MyPublicSubnet}]" --query 'Subnet.SubnetId' --output text
subnet-a5cb1c56

# awslocal resourcegroupstaggingapi get-resources
{
    "ResourceTagMappingList": [
        {
            "ResourceARN": "arn:aws:ec2:us-east-1:000000000000:vpc/vpc-d5f72963",
            "Tags": [
                {
                    "Key": "Name",
                    "Value": "MyVPC"
                }
            ]
        }
    ]
}

Subnets are not listed in get-resources

### Environment

```markdown
- OS: Ubuntu 22.04
- LocalStack: latest
  LocalStack version:
  LocalStack Docker image sha:
  LocalStack build date:
  LocalStack build git hash:
```

**Comment by silv-io** [comment]
Hi, this is something that needs fixing in our dependency, `moto`.

We've added the remaining missing EC2 resources in https://github.com/getmoto/moto/pull/8167. As soon as the dependency gets upgraded in localstack, the issue should be resolved
