### ISSUE TITLE
Support Fargate

### ISSUE THREAD

**Issue by palmerj** [localstack/localstack#1114]
Would be really great to support this in localstack

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-86) by [Unito](https://www.unito.io/learn-more)

**Comment by joaquinito01** [comment]
We will support Fargate soon!!!

**Comment by doodlesbykumbi** [comment]
@joaquinito01 How soon ? Also how can I help :)

**Comment by joaquinito01** [comment]
Please, support Fargate.

**Comment by thilko** [comment]
Would be interested in that feature too. Any plans to support fargate?

**Comment by HarshCasper** [comment]
Fargate is now available in the `localstack/localstack-pro:latest` image. Here is a [sample application](https://github.com/localstack-samples/sample-cdk-sqs-fargate-dynamodb) to get you started!
