### ISSUE TITLE
Athena support

### ISSUE THREAD

**Issue by kaidowei** [localstack/localstack#1115]
It would be awesome, if localstack supports Athena.

Our usecase is as follows: 
1) publish message to firehose
2) let firehose store that on s3
3) query these messages with athena

Is there any plan for this? I already saw the [roadmap](https://localstack.cloud/#roadmap) and some **Extended AWS Services** on the premium features. Is athena included there?

Thanks :+1:

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-87) by [Unito](https://www.unito.io/learn-more)

**Comment by ali-habibzadeh** [comment]
+ 1 for. Please add this!

**Comment by njfife** [comment]
I might be willing to help add support for this

**Comment by christhomas** [comment]
But what project provides athena like services that can be wrapped up and presented?

**Comment by dshalev** [comment]
> But what project provides athena like services that can be wrapped up and presented?
http://prestodb.github.io/

**Comment by christhomas** [comment]
presto sounds cool, is there any glue that it needs to "present" itself as athena? or is presto + a metadata store going to cut it and the aws cli is api compatible with that?

**Comment by TedisAgolli** [comment]
This is supported on the Pro Edition now right? Could close this.

**Comment by thrau** [comment]
Yes, we have athena support in localstack pro!
