### ISSUE TITLE
bug: No response metadata when an exception occurs with S3Client

### ISSUE THREAD

**Issue by reyncode** [localstack/localstack#11150]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am using the aws-sdk/client-s3 in TypeScript to interface with my localstack S3 instance. I would like to handle the exception details in my code using a try/catch structure as detailed in [aws-sdk/client-s3 README.md](https://github.com/aws/aws-sdk-js-v3/blob/main/clients/client-s3/README.md) but I am not getting any error metadata when an exception occurs. Here is how I am attempting to handle the exception:

```
export const putCommand = async (client: S3Client, input: PutObjectCommandInput): Promise<void> => {
  try {
    const command = new PutObjectCommand(input);
    await client.send(command);
  } catch (error) {
    console.log(error)
  }
}
```

When no exception occurs, I can log results of `await client.send(command);` to observe an object that looks like this:
```
"$metadata": Object { httpStatusCode: 200, attempts: 1, totalRetryDelay: 0, … }
```

When an exception does occur I am expecting to receive an [S3ServiceException](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/Package/-aws-sdk-client-s3/Class/S3ServiceException/) object but instead all I receive is `TypeError: NetworkError when attempting to fetch resource.` 

### Expected Behavior

When an exception happens, I expect to receive an S3ServiceException object that contains a metadata field populated with response data such as the http response code, request Id, etc.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker compose up -d

```
  storage:
    image: localstack/localstack:stable
    restart: no
    volumes:
      - app-storage-data:/var/lib/localstack
      - ./localstack/cors-config.json:/config/cors-config.json
      - ./localstack/init-storage.sh:/etc/localstack/init/ready.d/init-storage.sh
    ports:
      - "4566:4566"
    env_file:
      - .env
    environment:
      - DEBUG=${S3_DEBUG_MODE?Variable not set}
      - SERVICES=s3
      - FILE_BUCKET_NAME=${S3_FILE_BUCKET_NAME?Variable not set}
    command:
      - /bin/bash
      - -c
      - chmod +x ./localstack/init-storage.sh
    networks:
      - application-public

```

### Environment

```markdown
- OS:
- LocalStack:
  LocalStack version: 3.5.0
  LocalStack Docker image sha: sha256:d5b2f10d77f8655bee510a4fc7548290c735dcb6edefbf85d25dd1f70617c34a
  LocalStack build date: 2024-06-13
  LocalStack build git hash: 54edb407d
```

**Comment by bentsku** [comment]
Hello @reyncode and thanks for your report!

From what your exception is looking like, it seems the issue might not come from LocalStack, but that the exception raised is not an S3 exception but a more global HTTP one (the Network Error one) which must be raised by the underlying HTTP library the AWS SDK is using, which TypeScript cannot serialize. You might need to catch both kind of exception depending on the use case.
One other thing that points to that direction is that the metadata field is not fully returned by S3: only some fields are, and the SDK is responsible for putting them together (the HTTP status code, etc). 

Would you like to share how the exception is raised? Is there an issue communicating with LocalStack? Is that same test and exception returning correctly with AWS? 

Thanks!

**Comment by reyncode** [comment]
Thanks for the insight! 

I will need to do some more investigation as to what is going on. My initial thought was that the exception data wasn't being propagated from the LocalStack S3 instance because of the empty fields but I may be mistaken for thinking this. I haven't encountered any issues connecting or communicating with LocalStack but I'm unable to test that I get the same results with AWS because I am simply using LocalStack to learn more about using S3.

**Comment by bentsku** [comment]
No worries!
You can also look at LocalStack logs to see if anything would come up, but I suspect in that case that the request did not even hit LocalStack, which is why you don't get a response from which the SDK can serialize from.

It's also possible we might miss some fields for the response, in that case it would be good to share a small reproducible sample of your issue. 

Thanks!
