### ISSUE TITLE
lambda/TagResource method missing

### ISSUE THREAD

**Issue by rubelw** [localstack/localstack#1116]
The TagResource api call method does not seem to be available.  Get a 404 (NOT FOUND) when calling this method.

**Comment by whummer** [comment]
Thanks for reporting @rubelw . This should be relatively straight-forward to implement by adding a new `@app.route` in this file: https://github.com/localstack/localstack/blob/master/localstack/services/awslambda/lambda_api.py#L580
```
@app.route('%s/tags/<resource>' % PATH_ROOT, methods=['POST'])
def tag_resource(resource):
    # TODO implement
    ...
```
Do you think you could take a stab at this and raise a pull request with this new feature? That would be fantastic. Thanks!

**Comment by preethamvishy** [comment]
This issue seems to have been resolved by the PR. Is it good to close?

**Comment by whummer** [comment]
Yep, thanks!
