### ISSUE TITLE
bug: DynamoDB Streams not getting an event when ExecuteTransactionAsync is used to update the DB item

### ISSUE THREAD

**Issue by minhaz-mahbub-zocdoc** [localstack/localstack#11169]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

My setup contains the following

- a DynamoDB table with a corresponding stream
- a Lambda that reads events from the DDB stream and publishes to an SNS topic

I have some API calls in a service that either insert or update an item in my DDB table. 

When I perform those operations using `WriteItems` or by updating the table directly, I see the corresponding streams events get generated as expected followed by activity in my Lambda which acts on those stream events. 

However, when those operations are performed via `ExecuteTransactionAsync` instead, I do NOT see a corresponding DDB Streams event being generated, despite being able to observe that the change is reflected in my DDB table itself. All calls are being awaited.

### Expected Behavior

I think the expected behavior here is that the DDB Streams event should be generated regardless of what method is used to update the items in the DDB table. When I use `WriteItems`, invoke the Lambda directly, or update the item in the table directly using an instance of `AmazonDynamoDBClient`, I can observe that the stream event is generated and the lambda is kicked off properly.

When I use `ExecuteTransactionAsync` I can still observe that the item in the table is updated, but the corresponding stream event does not seem to be generated and the lambda does not get kicked off. All calls are being awaited.

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    I have a Makefile that contains a command which will call a shell script responsible for setting up localstack resources.
   `make setup-localstack`

Steps to Reproduce:

- Set up localstack resources (DDB Table with an associated stream + a lambda using the DDB stream for its event source mapping
- Insert a row in the DDB table (which should trigger a stream update and corresponding Lambda activity)
- Update the row in the DDB table via an awaited call that performs `ExecuteTransactionAsync`
- There should not be a second stream event generated and no corresponding Lambda Activity

### Environment

```markdown
- OS: macOS Sonoma 14.5
- LocalStack: localstack:3.3.0
  LocalStack version: 3.3.0
```

**Comment by joe4dev** [comment]
Thank you for sharing this issue @minhaz-mahbub-zocdoc  🙏 

We are actively working on improving our Lambda Event Source Mapping implementation 📈, also based on your valuable feedback. 
LocalStack 3.7.0 shipped today with a new implementation available using `LAMBDA_EVENT_SOURCE_MAPPING=v2`: https://blog.localstack.cloud/2024-08-29-localstack-release-v-3-7-0/#new-lambda-event-source-mapping-implementation

Please notice that we have not yet added test coverage for this scenario, so stay tuned for further updates if the current version does not resolve your issue 🚀 

---

sidenote: LocalStack now also supports [EventBridge Pipes](https://docs.localstack.cloud/user-guide/aws/pipes/) (Pro, preview) if you wish to connect DynamoDB directly to SNS.

**Comment by joe4dev** [comment]
Hi @minhaz-mahbub-zocdoc 

LocalStack 3.8.1 comes with our [new default implementation for Lambda Event Source Mapping](https://blog.localstack.cloud/localstack-release-v-3-8-0/#new-default-lambda-event-source-mapping-implementation). Does this issue persist?

If yes, feel free to share a minimal reproducer.
This issue could be a limitation of the underlying DynamoDB local implementation (e.g., mentioned in [this StackOverflow post](https://stackoverflow.com/a/32239201)) not supporting async transactions (i.e., ExecuteTransactionAsync), rather than being related to Lambda Event Source Mapping.
