### ISSUE TITLE
AWS IoT planned?

### ISSUE THREAD

**Issue by mvayngrib** [localstack/localstack#112]
amazing work guys!

is a local AWS IoT service planned?

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-88) by [Unito](https://www.unito.io/learn-more)

**Comment by mvayngrib** [comment]
or can we just use a local MQTT broker?

**Comment by qbnut** [comment]
I would also find this immensely useful as a development tool.

However from what I've read up so far on AWS IoT, it is more than just a basic MQTT Broker - that's the easy part ;)

For fully-fledged mocking, I guess this would also need IAM, Amazon Cognito, and probably a few other dependencies to be mocked also, as these comprise the ecosystem for supporting the rules and policies system fully.

**Comment by mvayngrib** [comment]
just for reference:
https://aws.amazon.com/blogs/iot/how-to-bridge-mosquitto-mqtt-broker-to-aws-iot/

**Comment by nishimura-yuji** [comment]
Do you have any progress on this issue?

**Comment by rsrini7** [comment]
Eager to looking for this...

**Comment by myroslav** [comment]
It look like IoT support is part of [LocalStack Pro](https://github.com/localstack/localstack/commit/f7ee0beaee38f06dfb960e515815c0fcde6ee28a). There is little information what exactly is supported. If anybody has more details, please share.

**Comment by myroslav** [comment]
@whummer, can you update us?

**Comment by nbrosnahan** [comment]
It's not clear to me how much of IoT is supported.  For instance, with the pro version, I appear to be able to do these things:

- list-things
- list-thing-groups

but I can't do these things: 

- list-billing-groups
- add-thing-to-billing-group
- add-thing-to-thing-group
- list-ca-certificates
- get-registration-code

Strangely enough, it appears that register-ca-certificate is available, but I don't know how you would use it if you can't get a registration code.

I would say it's probably a partial implementation and not really documented.

**Comment by thrau** [comment]
Yes AWS IoT is partially implemented, see our feature coverage: https://github.com/localstack/localstack/blob/master/doc/feature_coverage.md

We're happy to look into more specific feature requests!
