### ISSUE TITLE
bug: aws client region ignored using credentialsprovider + latest localstack docker image 

### ISSUE THREAD

**Issue by bergvandenp** [localstack/localstack#11213]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I create a topic with the java aws client in kotlin and the `credentialsProvider` is set, the region of the resulting topic ARN is set to `us-east-1`.
This odd behaviour happens when we upgrade LocalStack Docker image from '1.1.0' to 'latest'
```

```

### Expected Behavior

The resulting topic ARN contains region 'eu-west-1'

### How are you starting LocalStack?

Custom (please describe below)

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)
We're starting LocalStack in kotlin using a java library called 'localstack-utils:0.2.23'
```
@LocalstackDockerProperties(
    pullNewImage = true,
    imageTag = "latest",
    randomizePorts = true,
    services = ["sns", "sqs"],
    environmentVariableProvider = LocalStackDockerContextInitializer.LocalStackEnvironmentVariableProvider::class,
)
```

```
          val dockerConfig: LocalstackDockerConfiguration = PROCESSOR.process(LocalStackDockerContextInitializer::class.java)
            Localstack.INSTANCE.startup(dockerConfig)
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```
val snsClient: SnsClient =  
                SnsClient.builder()  
                    .credentialsProvider(AnonymousCredentialsProvider.create())  
                    .endpointOverride(URI.create(INSTANCE.endpointSNS))
                    .region(Region.EU_WEST_1)  
                    .build()  
                snsClient.createTopic(  
                    CreateTopicRequest.builder()  
                        .name("test")  
                        .build(),  
                ) 
```

### Environment

```markdown
- OS: MacOS 14.5 (23F79)
- LocalStack:
  LocalStack version:
  LocalStack Docker image sha: sha256:e6283910e8d25cfe0b2b884ae4e01ce352d04bd0fd5f1a4763e2b6b6e08ebdd4
  LocalStack build date:
  LocalStack build git hash:
```

### Anything else?

used libs:
localstack-utils:0.2.23
software.amazon.awssdk:sns:2.21.12

**Comment by bentsku** [comment]
Hello @bergvandenp and thanks for your report!

For LocalStack to know what user and region you are using, you might need to set the credentials to not be anonymous. I believe using the `AnonymousCredentialsProvider` will cause your SDK to not sign the request, and that is what LocalStack uses to understand where the request is aimed towards. 

We've only had this [current limitation](https://docs.localstack.cloud/user-guide/integrations/aws-cli/#current-limitations) listed in our usage of the AWS CLI in our documentation:
> Please also note there is a known limitation for issuing requests using --no-sign-request with the AWS CLI. LocalStack’s routing mechanism depends on the signature of each request to identify the correct service for the request. Thus, adding the flag --no-sign-requests provokes your request to reach the wrong service or region.

Could you try with the follow credentials provider and see if that fixes the issue?

```java
// Creating the AWS Credentials provider, using the default access and secret keys.

AwsCredentialsProvider credentials = StaticCredentialsProvider.create(AwsBasicCredentials.create("test", "test"));

val snsClient: SnsClient =  
                SnsClient.builder()  
                    .credentialsProvider(credentials)
                    .endpointOverride(URI.create(INSTANCE.endpointSNS))
                    .region(Region.EU_WEST_1)  
                    .build()  
                snsClient.createTopic(  
                    CreateTopicRequest.builder()  
                        .name("test")  
                        .build(),  
                ) 
```

Thanks!

**Comment by bergvandenp** [comment]
@bentsku thanks for your quick answer. Your suggestion gives the expected result indeed. thanks!

**Comment by bentsku** [comment]
Awesome, glad it could solve the issue! Can we consider the issue close?
