### ISSUE TITLE
CloudWatch Logs returns Internal Server Error 500

### ISSUE THREAD

**Issue by mmikhalko** [localstack/localstack#1122]
I'm getting the "500 Internal Server Error" when running the following:

aws --endpoint-url=http://localhost:4582 logs create-log-group --log-group-name test-group

An error occurred (500) when calling the CreateLogGroup operation (reached max retries: 4): <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>

**Comment by whummer** [comment]
Thanks for reporting @mmikhalko . Note that CloudWatch Logs is a different API endpoint - support added in #1161 . Please use port `4586` for CloudWatch Logs and port `4582` for regular CloudWatch
