### ISSUE TITLE
CloudWatch returns 500 error if a MetricDatum has a null value during putMetricData()

### ISSUE THREAD

**Issue by btpeterson** [localstack/localstack#1123]
I haven't tested this besides in java, but calling AmazonCloudWatch.putMetricData() that contains MetricDatum with null values returns a 500 error.

 ! com.amazonaws.services.cloudwatch.model.AmazonCloudWatchException: null (Service: AmazonCloudWatch; Status Code: 500; Error Code: 500 INTERNAL SERVER ERROR; Request ID: null)

It would be nice to have a more descriptive error message here.

**Comment by whummer** [comment]
Thanks for reporting @btpeterson . It seems that this is fixed in the latest version - added a small test in PR #1842 and verified that the call does not raise an Exception. Closing this issue - please re-open if the problem persists. Thanks
