### ISSUE TITLE
bug: Wrong DNS resolution when using podman

### ISSUE THREAD

**Issue by mfontana-elem** [localstack/localstack#11247]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When using Podman (rootless, but non-important), after pointing the container to use LocalStack container for DNS resolution ( by issuing `--dns ${LOCALSTACK_CONTAINER_IP}`, I get the loopback address `127.0.0.1`.

### Expected Behavior

I expect the IP of the container hosting LocalStack, as I do when running via Docker.

### How are you starting LocalStack?

Custom (please describe below)

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

```shell
$ podman network create --subnet 192.168.0.0/24 localstack_test
$ podman run --name localstack --net localstack_test --ip 192.168.0.33 localstack/localstack
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```shell
$ podman run --rm -it --net localstack_test --dns 192.168.0.33 alpine nslookup localhost.localstack.cloud
Server:		192.168.0.1
Address:	192.168.0.1:53

Name:	localhost.localstack.cloud
Address: 127.0.0.1

Name:	localhost.localstack.cloud
Address: ::1
```

### Environment

```markdown
- OS: Fedora 40
- LocalStack:
  LocalStack version: 3.5.1-dev
  LocalStack Docker image sha:
  LocalStack build date: 2024-07-23
  LocalStack build git hash: 1ebc389b2
```

### Anything else?

Starting with version 4.4 ([reference](https://github.com/containers/podman/issues/17499#issuecomment-1429845787)), Podman utilizes a DNS server on the gateway of every network (as far as I understand). As far as I know, every container created has one entry in `/etc/resolv.conf` for the gateway of each network the container belongs to.

It is hence the case that [_determine_best_ip](https://github.com/localstack/localstack/blob/1ebc389b2baa06cfc3c6c08434279461317a0c81/localstack-core/localstack/dns/server.py#L198) function behaves incorrectly. In particular:
```python
                if config.is_in_docker and self._is_gateway(ip_address):
                    return LOCALHOST_IP
```
this bit recognizes the request coming from the gateway and incorrectly assumes it comes from LocalStack itself.

Is this branching actually needed? Can't it just return the IP on the network interface instead of the loopback address?

**Comment by onlyann** [comment]
I believe this issue should be reopened as I am also running into it.

**Comment by kibiz0r** [comment]
> Is this branching actually needed? Can't it just return the IP on the network interface instead of the loopback address?

I don't think it is needed. Especially since localstack is configured to use itself as a nameserver, per /etc/resolv.conf. So any requests coming from the gateway are almost certainly not coming from localstack itself.

I agree that this issue should be reopened. I'm gonna go with your suggested fix for now though.
