### ISSUE TITLE
bug: AWS Batch Job Unable to Connect to RDS Instance in LocalStack Environment

### ISSUE THREAD

**Issue by ChzenChzen** [localstack/localstack#11244]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When running the infrastructure on LocalStack, the AWS Batch job is unable to establish a connection with the RDS instance. This issue does not occur in the Amazon AWS environment, where the setup works as expected.

### Expected Behavior

The AWS Batch job should be able to connect to the RDS instance successfully in both LocalStack and Amazon AWS environments, allowing for consistent behavior across development and production setups.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    localstack start

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)
 Deploy the following Terraform modules in order:
   - VPC
   - Security Groups
   - ECR
   - RDS
   - Batch
   - CloudWatch

 Ensure the following configurations are in place:
   - VPC with private subnets
   - Security groups allowing necessary traffic between Batch and RDS
   - ECR repository for the Batch job container image
   - RDS instance in the private subnet
   - AWS Batch compute environment, job queue, and job definition
   - CloudWatch log group for Batch job logs

source code to reproduce
[db-backuper.zip](https://github.com/user-attachments/files/16335818/db-backuper.zip)

### Environment

```markdown
- OS: Mac OS X Sanoma 14.5
- LocalStack: 
  LocalStack version: 3.5.1.dev20240719085433
  LocalStack Docker image sha:
  LocalStack build date: 2024-07-19
  LocalStack build git hash: de5b10b
```

**Comment by MarcelStranak** [comment]
Hi @ChzenChzen,

Thank you for your patience.

We have successfully reproduced the issue using the sample provided.

To resolve the issue, please change the host for the RDS endpoint in your batch Terraform configuration.
Use `localstack` instead of `localhost.localstack.cloud`, as the latter points to the localhost IP rather than the container IP.

```terraform
# Local variables
locals {
 rds_credentials = jsondecode([data.aws](http://data.aws/)_secretsmanager_secret_version.rds_credentials.secret_string)
 db_host         = "localstack"
 db_port         = local.rds_credentials.port
 db_name         = local.rds_credentials.db_name
 db_username     = local.rds_credentials.username
```
 db_password     = local.rds_credentials.password

}


We will continue with the investigation and look for an easier solution to the issue.
