### ISSUE TITLE
APIGateway and Lambda

### ISSUE THREAD

**Issue by anandmukundan** [localstack/localstack#1124]
Hi,

I have a dotnetcore Lambda and an API gateway to proxy the calls based on https://docs.aws.amazon.com/lambda/latest/dg/with-on-demand-https-example.html.

I use the AWS_PROXY for the put-integration type as I saw from other issues I looked into, that is what is supported in localstack.

The lambda receives json and returns json back.

When I call the API url, I see the lambda is getting called and is passed a JSON input, but this seems to be of the form {"body": "the real JSON I passed"}. This is breaking the lambda code as it is unable to parse this as it expects just the real JSON.

Is there anyway to make sure that the extra body tag is not added to the Lambda input?

Thanks

**Comment by MattCopenhaver** [comment]
That is how it's expected to work in AWS.  Your Lambda code should be looking for `event.body`, as the `event` has many other properties.  Here's an example (although it's a GET and does not have `body`): https://docs.aws.amazon.com/lambda/latest/dg/eventsources.html#eventsources-api-gateway-request

**Comment by whummer** [comment]
Thanks for providing the pointer @MattCopenhaver . Closing this one as resolved
