### ISSUE TITLE
bug: getMetricStatistics function returns empty datapoints

### ISSUE THREAD

**Issue by ugur-kap** [localstack/localstack#11260]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I've been using the `cloudWatch.getMetricStatistics()`function to test my metrics in e2e tests. And it always return empty Datapoints even when I got a 200 response on publishing metrics.
 
Here is my test:

```
    const failedOrdersMetric = await cloudwatchClient.getMetricStatistics({
      Namespace: 'Namespace',
      MetricName: 'FailedOrders',
      StartTime: subSeconds(Date.now(), 15),
      EndTime: addSeconds(Date.now(), 5),
      Period: 20, // seconds
      Statistics: [Statistic.Sum]
    });
    expect(failedOrdersMetric.Datapoints![0].Sum).toBe(2);
```

It was running as expected without any errors, but it has been throwing this error since yesterday. Because `failedOrdersMetric.Datapoints` is an empty array.
`Cannot read properties of undefined (reading 'Sum')`

I tried the same code with the localstack:3.5.0 version, and everything seems fine. So, I think there is some issue with your latest package.

### Expected Behavior

The test should run as expected without errors, just like package 3.5.0

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

   docker-compose up --build

### Environment

```markdown
- OS:
- LocalStack:
  LocalStack version: latest
  LocalStack Docker image sha:
  LocalStack build date:
  LocalStack build git hash:
```

**Comment by pinzon** [comment]
Hi @ugur-kap. Could you provide more info in how you push your metrics or even better a script that fails?
The Cloudwatch v2 provider is a bit more strict with the dimensions of the metrics and in some case it could return empty results (like in AWS)

I wrote this python test that passes with AWS, CW v1 and v2
```python
@markers.aws.validated
    def test_get_metric_statistics_with_same_timestamp(self, aws_client):
        namespace = f"test/{short_uid()}"
        # put metric data
        timestamp = datetime.now(tz=timezone.utc) - timedelta(seconds=20)
        for i in range(20):
            aws_client.cloudwatch.put_metric_data(
                Namespace=namespace,
                MetricData=[
                    dict(MetricName="FailedOrders", Value=i, Timestamp=timestamp)
                ],
            )

        # get metric statistics
        def _assert_results():
            stats_response = aws_client.cloudwatch.get_metric_statistics(
                Namespace=namespace,
                MetricName="FailedOrders",
                StartTime=timestamp - timedelta(seconds=15),
                EndTime=timestamp + timedelta(seconds=5),
                Period=10,
                Statistics=["Sum"],
            )
            assert len(stats_response["Datapoints"]) == 1
            assert stats_response["Datapoints"][0]["Sum"] == 190



        retry(_assert_results, retries=10, sleep=2.0)
```


In the meantime you could use `PROVIDER_OVERRIDE_CLOUDWATCH=v1` to use the old provider in LS 3.6.0.

**Comment by ugur-kap** [comment]
Hi @pinzon. I compared my code with yours and found some interesting things.
I use `Dimensions` key when I pushed metrics but not use them when trying to get statics in my test file.

here is the code example:

    const metricObj = {
      Namespace: 'namespace',
      MetricData: [
        {
          MetricName: 'FailedOrders',
          Dimensions: [
            {
              Name: 'Scope',
              Value: 'Orders'
            }
          ],
          Value: 2,
          Unit:  StandardUnit.Count
        }
      ]
    };

    await cloudwatchClient.putMetricData(metricObj);

    const failedOrdersMetric = await cloudwatchClient.getMetricStatistics({
      Namespace: 'namespace',
      MetricName: 'FailedOrders',
      StartTime: subSeconds(Date.now(), 15),
      EndTime: addSeconds(Date.now(), 5),
      Period: 20, // seconds
      Statistics: [Statistic.Sum],
    });
    expect(failedOrdersMetric.Datapoints![0].Sum).toBe(2);`

and this version of the code is failing when I used latest version of localstack but it's passed 3.5.0.

But it's passed with latest version after I added Dimensions key into my getMetricStatistics method.

    const failedOrdersMetric = await cloudwatchClient.getMetricStatistics({
      Namespace: 'namespace',
      MetricName: 'FailedOrders',
      StartTime: subSeconds(Date.now(), 15),
      EndTime: addSeconds(Date.now(), 5),
      Period: 20, // seconds
      Statistics: [Statistic.Sum],
      Dimensions: [
        {
          Name: 'Scope',
          Value: 'Orders'
        }
      ]
    });
    expect(failedOrdersMetric.Datapoints![0].Sum).toBe(2);

thanks!!
