### ISSUE TITLE
Issue with triggered Lambda (as container) not being in same network as localstack 

### ISSUE THREAD

**Issue by RichardWright** [localstack/localstack#1126]
Hi!

When invocating lambdas using s3 triggers, the lambas containers that are started are not in the user defined bridge network(they attach to the default bridge network). This stops the lambda communicating with other containers in the localstack network. I've no idea why this behaviour is happening, 

OS: Ubuntu 18.04
Docker version 18.09.1, build 4c52b90

**Comment by RichardWright** [comment]
Update: The behaviour of lambdas being attached to default bridge docker network instead of the localstack docker network I have observed still stands, but when run in a different location/a different physical network (namely my work one) the lambda can communicate with s3. I'm very confused by this and will investigate further. I am going to assume interference on the dns via my home ISP.

**Comment by shenie** [comment]
You can specify the lambda network by using `LAMBDA_DOCKER_NETWORK` configuration.
https://github.com/localstack/localstack#configurations

**Comment by whummer** [comment]
@RichardWright did you have a chance to try it with the `LAMBDA_DOCKER_NETWORK` configuration mentioned by @shenie above?

**Comment by RichardWright** [comment]
@whummer yep, that worked! thanks guys!

**Comment by nilathj** [comment]
Hi Richard,  What network did you use for LAMBDA_DOCKER_NETWORK?  Did you create your own network or use one which is already there?  

docker network ls gives me:
```
NETWORK ID          NAME                DRIVER              SCOPE
c527b2d90b04        bridge              bridge              local
0451a1fa097e        host                host                local
f8bb782b4bc4        none                null                local
```
I tried to use the existing bridge network, but I couldn't get the lambda to connect to localhost:4571 (Elasticsearch).  This is starting localstack using docker:
```
docker run --name localstack -d \
    -e LAMBDA_EXECUTOR=docker-reuse \
    -e LAMBDA_DOCKER_NETWORK=bridge \
    -e DOCKER_HOST=unix:///var/run/docker.sock \
    -e SERVICES=cloudformation,apigateway,s3,lambda,es,iam,cloudwatch \
    -e DEBUG=1 \
    -p 443:443 \
    -p 4567-4596:4567-4596 \
    -p 8080:8080 \
    -v $PWD:$PWD \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v /tmp/localstack:/tmp/localstack \
    localstack/localstack:latest
```

**Comment by shenie** [comment]
In your lambda could you try to connect using `localstack:4571` instead of `localhost:4571`?

**Comment by nilathj** [comment]
```
[INFO]	2019-05-02T04:44:59.959Z	52fdfc07-2182-154f-163f-5f0f9a621d72	DOING Elastic Search: http://localstack:4571/workspace/_search
[INFO]	2019-05-02T04:44:59.966Z	52fdfc07-2182-154f-163f-5f0f9a621d72	Starting new HTTP connection (1): localstack
[ERROR]	2019-05-02T04:45:00.987Z	52fdfc07-2182-154f-163f-5f0f9a621d72	Error Connecting: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
