### ISSUE TITLE
Case mismatch in LambdaExecutor.java

### ISSUE THREAD

**Issue by SamNelson** [localstack/localstack#1129]
When sending kinesis events through localstack through the LambdaExecutor, a few of the text strings do no match the expected text strings.
LambdaExecutor.java:59
`if (records.stream().anyMatch(record -> record.containsKey("Kinesis")))`
when "kinesis" is the actual key being passed.
The same is true for other keys on lines 67-71

``` . Map<String, Object> kinesis = (Map<String, Object>) get(record, "Kinesis");
String dataString = new String(get(kinesis, "Data").toString().getBytes());
byte[] decodedData = Base64.getDecoder().decode(dataString);
kinesisRecord.setData(ByteBuffer.wrap(decodedData));
kinesisRecord.setPartitionKey((String) get(kinesis, "PartitionKey"));
```

where the strings provided in the record have the following keys:
"kinesis", "data" and "partitionKey"

Replacing the strings allows the Lamdba to execute, but I'm not sure which casing is correct according to AWS standards.

**Comment by SamNelson** [comment]
When sending kinesis events through localstack through the LambdaExecutor, a few of the text strings do no match the expected text strings.
LambdaExecutor.java:59
`if (records.stream().anyMatch(record -> record.containsKey("Kinesis")))`
when "kinesis" is the actual key being passed.
The same is true for other keys on lines 67-71

``` . Map<String, Object> kinesis = (Map<String, Object>) get(record, "Kinesis");
String dataString = new String(get(kinesis, "Data").toString().getBytes());
byte[] decodedData = Base64.getDecoder().decode(dataString);
kinesisRecord.setData(ByteBuffer.wrap(decodedData));
kinesisRecord.setPartitionKey((String) get(kinesis, "PartitionKey"));
```

where the strings provided in the record have the following keys:
"kinesis", "data" and "partitionKey"

Replacing the strings allows the Lamdba to execute, but I'm not sure which casing is correct according to AWS standards.

**Comment by whummer** [comment]
Thanks for reporting @SamNelson - this should be fixed here: https://github.com/localstack/localstack/pull/1344/files#diff-93ccfa9ba7a702844e1f8ebb222a284cR71

Please report here if the problem persists. Thanks
