### ISSUE TITLE
Cloudformation create-stack: { "Ref": "AWS::StackName" } in resource names (ej. TopicName) will break deployment

### ISSUE THREAD

**Issue by janjilek** [localstack/localstack#1130]
If I have  { "Ref": "AWS::StackName" } in TopicName `{
   "event1": {
            "Type": "AWS::SNS::Topic",
            "Properties": {
                "Subscription": [
                    {
                        "Endpoint": {
                            "Fn::GetAtt": [
                                "queue1",
                                "Arn"
                            ]
                        },
                        "Protocol": "sqs"
                    }
                ],
                "TopicName": {
                    "Fn::Join": [
                        "",
                        [
                            {
                                "Ref": "AWS::StackName"
                            },
                            "-event1"
                        ]
                    ]
                }
            }
        }
}` it will throw `ClientError: An error occurred (AlreadyExists) when calling the CreateStack operation: The resource with the name requested already exists` during stack creation. I am quite sure, that this can break also other resources, but I haven't tested it. Once I replace `{ "Ref": "AWS::StackName" }` with some string, stack creates without problem. It will fail why resolving refs on line 362 in template_deployer.py files, because it will try to describe stack resource that does not exist (AWS::StackName string). 

Error stack below:
`localstack_1_cb8a01595556 | 2019-02-15T11:48:11:DEBUG:boto3.resources.factory: Loading sns:sns
localstack_1_cb8a01595556 | 2019-02-15T11:48:11:DEBUG:localstack.utils.cloudformation.template_deployer: Deploying resource type "SNS::Topic" id "prerenderPageRemovedEvent"
localstack_1_cb8a01595556 | 2019-02-15T11:48:11:DEBUG:localstack.utils.cloudformation.template_deployer: Resolving ref AWS::StackName - PhysicalResourceId
localstack_1_cb8a01595556 | 127.0.0.1 - - [15/Feb/2019 11:48:11] "POST / HTTP/1.1" 200 -
localstack_1_cb8a01595556 | 2019-02-15T11:48:11:ERROR:localstack.services.generic_proxy: Error forwarding request: list index out of range Traceback (most recent call last):
localstack_1_cb8a01595556 |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 233, in forward
localstack_1_cb8a01595556 |     updated_response = self.proxy.update_listener.return_response(**kwargs)
localstack_1_cb8a01595556 |   File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_listener.py", line 216,in return_response
localstack_1_cb8a01595556 |     template_deployer.deploy_template(template, req_data.get('StackName')[0])
localstack_1_cb8a01595556 |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 517, in deploy_template
localstack_1_cb8a01595556 |     deploy_resource(resource_id, resource_map, stack_name=stack_name)
localstack_1_cb8a01595556 |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 448, in deploy_resource
localstack_1_cb8a01595556 |     params[param_key] = resolve_refs_recursively(stack_name, tmp_value, resources)
localstack_1_cb8a01595556 |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 388, in resolve_refs_recursively
localstack_1_cb8a01595556 |     value[key] = resolve_refs_recursively(stack_name, val, resources)
localstack_1_cb8a01595556 |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 393, in resolve_refs_recursively
localstack_1_cb8a01595556 |     value[i] = resolve_refs_recursively(stack_name, value[i], resources)
localstack_1_cb8a01595556 |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 393, in resolve_refs_recursively
localstack_1_cb8a01595556 |     value[i] = resolve_refs_recursively(stack_name, value[i], resources)
localstack_1_cb8a01595556 |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 382, in resolve_refs_recursively
localstack_1_cb8a01595556 |     resources, attribute='PhysicalResourceId')
localstack_1_cb8a01595556 |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 362, in resolve_ref
localstack_1_cb8a01595556 |     resource_status = describe_stack_resources(stack_name, ref)[0]
localstack_1_cb8a01595556 | IndexError: list index out of range`

**Comment by whummer** [comment]
Thanks for reporting @janjilek . This should be fixed in the meantime - a test has been added in #1827 . Please re-open if the problem persists. Thanks
