### ISSUE TITLE
bug: ApiGateway (PutIntegrationResponse, PutMethodResponse) ResponseParameters don't work

### ISSUE THREAD

**Issue by lucascesconetto** [localstack/localstack#11303]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am passing the headers to be removed from the integration and response of the api gateway and it is not happening.

### Expected Behavior

ResponseParameters do the mapping remove and add configured headers

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    api-gateway:
    container_name: 'api-gateway'
    labels:
      component.description: localstack
    image: 'localstack/localstack:latest'
    build:
      network: host
    ports:
      - "4566:4566"
      - "8083:8083"
    environment:
      - SERVICES=apigateway
      - DATA_DIR=/tmp/localstack/data
      - DEFAULT_REGION=sa-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - CLEAR_TMP_FOLDER=0
    volumes:
      - ./pools/api-gateway/setup.sh:/etc/localstack/init/ready.d/init-aws.sh
      - /export/api-gateway/data:/tmp/localstack/data
      - /var/run/docker.sock:/var/run/docker.sock

      
#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```sh
API_ID=$(awslocal apigateway create-rest-api --name "Api Gateway" --query 'id' --output text  --tags="_custom_id_=2hemktidqe" --region sa-east-1)
RESOURCE_ID=$(awslocal apigateway get-resources --rest-api-id $API_ID --query 'items[0].id' --output text  --region sa-east-1)
NEW_RESOURCE_ID=$(awslocal apigateway create-resource --rest-api-id $API_ID --parent-id $RESOURCE_ID --path-part register --query 'id' --output text --region sa-east-1)
SERVICE_URI=http://api-service/register

echo "API_ID: $API_ID"
echo "RESOURCE_ID: $RESOURCE_ID"
echo "NEW_RESOURCE_ID: $NEW_RESOURCE_ID"
echo "SERVICE_URI: $SERVICE_URI"

awslocal apigateway put-method \
    --rest-api-id $API_ID \
    --resource-id $NEW_RESOURCE_ID \
    --http-method POST \
    --authorization-type "NONE" \
    --region sa-east-1

awslocal apigateway put-integration \
    --rest-api-id $API_ID \
    --resource-id $NEW_RESOURCE_ID \
    --http-method POST \
    --type HTTP \
    --integration-http-method POST \
    --uri http://api-service/register \
    --request-templates '{
        "application/json": "{\"number\": \"$input.path(\"$.text_number\")\"}"
    }' \
    --passthrough-behavior WHEN_NO_MATCH \
    --region sa-east-1

awslocal apigateway put-integration-response \
    --rest-api-id $API_ID \
    --resource-id $NEW_RESOURCE_ID \
    --http-method POST \
    --status-code 201 \
    --content-handling CONVERT_TO_TEXT \
    --response-templates "{}" \
    --response-parameters  "method.response.header.X-Banana=" \
    --region sa-east-1

awslocal apigateway put-method-response \
  --rest-api-id $API_ID \
  --resource-id $NEW_RESOURCE_ID \
  --http-method POST \
  --status-code 201 \
  --response-parameters "method.response.header.X-Banana=false" \
  --region sa-east-1

awslocal apigateway create-deployment \
    --rest-api-id $API_ID \
    --stage-name dev \
    --region sa-east-1
    
   ```

### Environment

```markdown
- OS: Ubuntu 22.04.1 LTS
- LocalStack: 
  LocalStack version:
  LocalStack Docker image sha: localstack/localstack@sha256:9243140a552c2f287bcba47bce904a24b027b97665dd06d0f149a4f016b64b2b
  LocalStack build date:
  LocalStack build git hash:
```

### Anything else?

I didn't find a similar problem to make a reference

**Comment by bentsku** [comment]
Hello @lucascesconetto and thanks for your report!

We're currently working in improving API Gateway REST APIs, and we have a fully rewritten implementation with much better parity available. Could you start LocalStack with the following configuration: `PROVIDER_OVERRIDE_APIGATEWAY=next_gen` as an environment variable and see if that would solve your issue?

See the documentation for the configuration: https://docs.localstack.cloud/references/configuration/

Thank you, please feel free to give any feedback.
