### ISSUE TITLE
bug: StepFunctions does not support States.x.Credentials

### ISSUE THREAD

**Issue by bblommers** [localstack/localstack#11311]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The following template is supported by AWS:
```
{
  "StartAt": "ListTables",
  "States": {
    "ListTables": {
      "Type": "Task",
      "Parameters": {},
      "Resource": "arn:aws:states:::aws-sdk:dynamodb:listTables",
      "End": true,
      "Credentials": {
        "RoleArn": "arn:aws:iam::123456789012:role/role/role"
      }
    }
  }
}
```

The SFN Grammer currently does not support this, and throws an error:
```
ASLParserException ['line 1:159, at "Credentials", mismatched input \'"Credentials"\' expecting {\'"Comment"\', \'"Type"\', \'"Choices"\', \'"Default"\', \'"Branches"\', \'"SecondsPath"\', \'"Seconds"\', \'"TimestampPath"\', \'"Timestamp"\', \'"TimeoutSeconds"\', \'"TimeoutSecondsPath"\', \'"HeartbeatSeconds"\', \'"HeartbeatSecondsPath"\', \'"ItemProcessor"\', \'"Iterator"\', \'"ItemSelector"\', \'"MaxConcurrencyPath"\', \'"MaxConcurrency"\', \'"Resource"\', \'"InputPath"\', \'"OutputPath"\', \'"ItemsPath"\', \'"ResultPath"\', \'"Result"\', \'"Parameters"\', \'"ResultSelector"\', \'"ItemReader"\', \'"ToleratedFailureCount"\', \'"ToleratedFailureCountPath"\', \'"ToleratedFailurePercentage"\', \'"ToleratedFailurePercentagePath"\', \'"Label"\', \'"Next"\', \'"End"\', \'"Cause"\', \'"CausePath"\', \'"Error"\', \'"ErrorPath"\', \'"Retry"\', \'"Catch"\'}', "line 1:231, at }, extraneous input '}' expecting <EOF>"]
```

### Expected Behavior

Verifying the role even exists is not really necessary for me, let alone assuming the role. But running this sample without error would be nice.

### How are you starting LocalStack?

With a `docker run` command

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run --rm -it -p 4566:4566 -p 4510-4559:4510-4559 localstack/localstack

### Environment

```markdown
LocalStack version: 3.6.1.dev
LocalStack build date: 2024-08-05
LocalStack build git hash: 2ea7e9eef
```

**Comment by MEPalma** [comment]
Thank you for taking the time to compile this report. We have recently added support for `Credentials`. Could you verify if this resolves your issue? If it does, feel free to close this issue. If you're still experiencing problems, please let us know and we'll investigate further. Thank you again for bringing this issue forward.

**Comment by bblommers** [comment]
Great, thank you @MEPalma!
