### ISSUE TITLE
bug: Step Functions do not support context object references outside of the payload block

### ISSUE THREAD

**Issue by russoalex** [localstack/localstack#11320]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

So while testing step functions we ran into an issue where references to the context object (i.e. $$, $$.Execution.Input, etc) within a step function definition succeeds only if that reference is in the context of the payload block.  According to the AWS documentation (https://docs.aws.amazon.com/step-functions/latest/dg/input-output-contextobject.html) as well as our own deployed step function the context object should be usable within the following fields

InputPath
OutputPath
ItemsPath (in Map states)
Variable (in Choice states)
ResultSelector
Parameters
Variable to variable comparison operators

I tracked down why this might be the case and all the way back in the ASL parser it looks like the context object is only parsed in the context of payload phase

https://github.com/localstack/localstack/blob/b58b0f8ef6b82d38bb847b843e111e98d6c40acf/localstack-core/localstack/services/stepfunctions/asl/antlr/ASLParser.g4

payload_binding:
    STRINGDOLLAR COLON STRINGPATH                # payload_binding_path
    | STRINGDOLLAR COLON STRINGPATHCONTEXTOBJ    # payload_binding_path_context_obj
    | STRINGDOLLAR COLON intrinsic_func          # payload_binding_intrinsic_func
    | keyword_or_string COLON payload_value_decl # payload_binding_value

so unfortunately fixing this will probably mean changes to the parser

### Expected Behavior

According to the AWS documentation (https://docs.aws.amazon.com/step-functions/latest/dg/input-output-contextobject.html) as well as our own deployed step function the context object should be usable within the following fields

InputPath
OutputPath
ItemsPath (in Map states)
Variable (in Choice states)
ResultSelector
Parameters
Variable to variable comparison operators

### How are you starting LocalStack?

Custom (please describe below)

### Steps To Reproduce

I personally started localstack with TestContainers in Java, but the issue should be reproducible anywhere given it's nature.

Attempt to use a context object ($$) in anything but a payload. 

### Environment

```markdown
- OS:
- LocalStack:
  LocalStack version:
  LocalStack Docker image sha:
  LocalStack build date:
  LocalStack build git hash:
```

**Comment by olivermeyer** [comment]
Not sure if this is any help, but somehow I'm able to access the context object from the `Parameters` of a `Task` state:
```
"ThisWorks": {
  "Type": "Task",
  "Resource": "arn:aws:states:::dynamodb:deleteItem",
  "Parameters": {
    "TableName": "some-table",
    "Key": {
      "someKey": {
        "S.$": "$$.Execution.Input.someKey"
      }
    },
  ...
  }
}
```
However I'm not able to access it from the `Parameters` of a `Pass` state:
```
"ThisDoesNotWork": {
  "Type": "Pass",
  "Parameters": {
    "someKey.$": "$$.Execution.Input.someKey"
  }
}
```
And I can also confirm that accessing the context from the `ItemSelector` of a `Map` state doesn't work.

**Comment by MEPalma** [comment]
Thank you for everyone involved in compiling and supporting this report. This was a very important aspect to point out, and I am very happy to see these workflows now being supported in LocalStack. I was able to replicate the behaviour, and we recently merged some changes that aim to address this issue. These changes are scheduled to be included in the next nightly release too. I would be grateful if you could test the new build and provide feedback on whether it resolves the problems you encountered. Thank you once again for bringing this issue forward!
