### ISSUE TITLE
bug: In Step Functions, the result of evaluating a JsonPath ending with an array access is always wrapped in an extra array

### ISSUE THREAD

**Issue by sigpwned** [localstack/localstack#11321]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In a Step Functions StateMachine, evaluating a JsonPath that ends with an array access (e.g., `$[0]`, `$.alpha[0]`, etc.) that is used in a `Parameters` or `ResultSelector` field always produces a result that is wrapped in one more array than it should be.

For example, given the step function definition:

    StartAt: State
    States:
      State:
        Type: Pass
        Parameters:
          firstItem.$: $.items[0]
        End: true

Invoking it with the input:

    {
      "items": [
        "alpha",
        "bravo"
      ]
    }

Produces the following output:

    {
      "firstItem": [
        "alpha"
      ]
    }

Note that the value of property `firstItem` has type array, when it should have type string.

### Expected Behavior

The result of evaluating a JsonPath that ends with an array access should produce the expected result. (Specifically, the result should not be wrapped in an extra array.)

For example, given the step function definition:

    StartAt: State
    States:
      State:
        Type: Pass
        Parameters:
          firstItem.$: $.items[0]
        End: true

Invoking it with the input:

    {
      "items": [
        "alpha",
        "bravo"
      ]
    }

Should produces the following output:

    {
      "firstItem": "alpha"
    }

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

Create a CloudFormation stack with the following template to create a state machine that can reproduce the error. (Of course, you can also just create the step function from the definition embedded in the template, but this seems easier to me.)

```
AWSTemplateFormatVersion: 2010-09-09
Resources:
  ExampleStateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: "example-state-machine"
      StateMachineType: STANDARD
      RoleArn: !GetAtt ExampleRole.Arn
      Definition:
        Comment: >-
          Given input like `{items:[{},{}]}`, this state machine gives output
          like `{firstItem:{}}` in AWS, but output like `{firstItem:[{}]}` in
          LocalStack.
        StartAt: State
        States:
          State:
            Type: Pass
            Parameters:
              firstItem.$: $.items[0]
            End: true
          
  ExampleRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: "example-role"
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: states.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: deny
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Deny
                Action: "*"
                Resource: "*"
```

Next, run the created StateMachine  `example-state-machine` with the following input:

```
{
  "items": [
    "alpha",
    "bravo"
  ]
}
```

Note that the Execution produces the following (incorrect) output:

```
{
  "firstItem": [
    "alpha"
  ]
}
```

Specifically, note that `$.firstItem` is wrapped in an extra array.

### Environment

```markdown
- OS: MacOS 14.5
- LocalStack:
  LocalStack version: 3.6.0
  LocalStack Docker image sha: fa257e4e37a4
  LocalStack build date: 2024-08-06
  LocalStack build git hash: 7f60a433f
```

### Anything else?

I have confirmed that running the StateMachine created by the above CloudFormation template with the given input in AWS vs LocalStack gives different outputs.

Specifically, executing the StateMachine with the following input:

```
{
  "items": [
    "alpha",
    "bravo"
  ]
}
```

Produces the following output in AWS:

```
{
  "firstItem": "alpha"
}
```

But produces the following output in LocalStack:

```
{
  "firstItem": [
    "alpha"
  ]
}
```

I have only tested this effect in `Parameters` and `ResultPath` fields of a StateMachine.

To the best of my ability to test, the issue only manifests when the JsonPath ends in an array access. The issue does not show up when an array access is internal to the JsonPath, or when there are only named field accesses (e.g., `$.a.b`) in a JsonPath. The issue manifests the same way if a JsonPath ends in two array accesses in a row. The issue manifests the same way if the syntax uses brackets (`$[0]`) or dots (`$.0`). I have not encountered any other JsonPath syntax permutations that cause the issue.

**Comment by MEPalma** [comment]
Thank you for taking the time to compile this report. I was able to replicate the behaviour that resulted in the failure. We recently merged some changes that aim to address this issue. These changes are scheduled to be included in the next nightly release too. I would be grateful if you could test the new build at your earliest convenience and provide feedback on whether it resolves the problem you encountered. Thank you once again for bringing this issue forward.
