### ISSUE TITLE
bug: AppSync errors when including AWS Scalars

### ISSUE THREAD

**Issue by jamesphilipps** [localstack/localstack#11326]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

AWS provides several [custom Scalars ](https://docs.aws.amazon.com/appsync/latest/devguide/scalars.html)

In order to use these scalars, they must be included in the schema like so:

```
scalar AWSDate
scalar AWSDateTime
scalar AWSTimestamp
 
type MyType {
    id: ID!
    date: AWSDate!
    dateTime: AWSDateTime!
    timestamp: AWSTimestamp!
}
```

When attempting to create the schema, an error is thrown indicating that there is a duplicate type "AWSDate". I assume LocalStack has some knowledge of the AWS types but is incorrectly handling their scalar declarations in the schema

### Expected Behavior

No error is thrown and the scalar is correctly registered (or ignored if already registered by default)

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack-pro

### Environment

```markdown
- OS: Windows
- LocalStack:
  LocalStack version: 3.5.1.dev
  LocalStack Docker image sha: 38276cfe60d6
```

**Comment by cloutierMat** [comment]
Hi @jamesphilipps,

Thank you for reporting this issue. It is important to note that AWS does not support custom scalar per-say. It has some `service-defined` scalar. The main difference would be that these service defined scalar are built in therefore can be referenced.

> In order to use these scalars, they must be included in the schema like so:

While, on aws, you can also add `scalar AWSDate` in your schema definition, it is not required to do so. The example in the Documentation page you shared is also not including them.

> I assume LocalStack has some knowledge of the AWS types but is incorrectly handling their scalar declarations in the schema

LocalStack doesn't currently fully support the AWS scalars and while they can be referenced in your schema, it won't be used for validation.

For the time being, if possible, I would suggest to remove the scalar declaration from your schema definition, as this configuration will work for both AWS and Localstack.

**Comment by jamesphilipps** [comment]
@cloutierMat Thanks for the fast reply. I'll try removing the scalars

**Comment by cloutierMat** [comment]
Awesome!
Let us know if you encounter any problems. In the meantime, I will leave this issue open, as this is a parity issue with AWS, that we will want to keep documented.

**Comment by cloutierMat** [comment]
@jamesphilipps 
I had a closer look at our implementation and was able to create a fix for the issue you are experiencing. I have opened a PR and will let you know once the fix is live.

**Comment by cloutierMat** [comment]
The issue has now been fixed and is live in the `latest` pro image.
