### ISSUE TITLE
bug: Lambda invocations don't support X-Ray Passive Tracing (via x-amzn-trace-id header)

### ISSUE THREAD

**Issue by northvankiwiguy** [localstack/localstack#11336]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When invoking a Lambda function, via the AWS SDK, I am seeing the `x-amzn-trace-id` HTTP header being ignored, but instead a totally new X-Ray Trace ID is being generated. In the code, [I can see a TODO ](https://github.com/localstack/localstack/blob/master/localstack-core/localstack/services/lambda_/invocation/execution_environment.py#L383)to implement "Passive Tracing", so I'm pretty sure this isn't implemented yet.

### Expected Behavior

When the `x-amzn-trace-id` HTTP is set by the caller (via the AWS SDK), that X-Ray Trace ID should be used as the basis for creating the new Trace ID. The `Root` field should be the same as what was passed in the HTTP header. The value should be stored in the `_X_AMZN_TRACE_ID` environment variable.

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    localstack start

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

Using the AWS SDK for JavaScript V3.
```
    const client = new LambdaClient({
      region: 'us-west-2',
      endpoint: 'http://localhost.localstack.cloud:4566'
    });

    client.middlewareStack.add((next, _context) => async (args) => {
        const requestId = "Root=1-65d5288a-733df1c374a9bc482f5e0442;Sampled=0"
        if (requestId) {
          (args.request as any).headers['x-amzn-trace-id'] = requestId;
        }
        return await next(args);
      }, { 
        step: "finalizeRequest"
      }
    )

    const command = new InvokeCommand({
      FunctionName: "ExampleStack-OrderLambda008D7AE5-cf1b6ac6",
      Payload: JSON.stringify({}),
    });
  
    const { Payload, LogResult } = await client.send(command);
```

My Lambda functions does, where I'd expect to see the header value I passed in (at least the `Root` should be the same).
```
console.log(`_X_AMZN_TRACE_ID ${process.env['_X_AMZN_TRACE_ID']}`)
```

### Environment

```markdown
- OS: Darwin 88665a330d66.ant.amazon.com 23.5.0 Darwin Kernel Version 23.5.0: Wed May  1 20:09:52 PDT 2024; root:xnu-10063.121.3~5/RELEASE_X86_64 x86_64
- LocalStack:
  LocalStack version: 3.6.1.dev
  LocalStack build date: 2024-08-09
  LocalStack build git hash: 15fec7554
```

**Comment by joe4dev** [comment]
Hi @northvankiwiguy 

That's correct, X-Ray trace header parsing and propagation through Lambda is not yet implemented.
Good news: Your scenario should be supported once https://github.com/localstack/localstack/pull/11708 is merged and shipped 🚀 


How are you using X-Ray with LocalStack? Feel free to share any feedback on improving tracing support at LocalStack :)
