### ISSUE TITLE
awslocal not in $path after pip install awscli-local

### ISSUE THREAD

**Issue by laplantb** [localstack/localstack#1136]
Step to reproduce using Dockerfile

FROM localstack/localstack:0.8.11
RUN pip install awscli-local
RUN awslocal sns create-topic --name sns-topic

error output: awslocal: command not found

awslocal is  not in $PATH
I have to  RUN export PATH="/root/.local/bin/:$PATH" 

This issue is not occuring on image 0.8.10

**Comment by shenie** [comment]
My bad... `awscli-local` is already installed in the latest Dockerfile from https://github.com/localstack/localstack/pull/1018/files#diff-3254677a7917c6c01f55212f86c57fbfR59

They were installed with `--user` switch hence they live in `/root/.local/bin`.
My guess is when you ran `pip install awscli-local` again it was a no-op.

Either way I've fixed it in https://github.com/localstack/localstack/pull/1137

**Comment by whummer** [comment]
Thanks for reporting @laplantb . Should be fixed in #1137

**Comment by msolimans** [comment]
Make sure you add python's `bin` directory to `$PATH`.  

In case of `python 2.7`: export $PATH=$PATH:~/Library/Python/2.7/bin
In case of `python 3.x`: export $PATH=$PATH:~/Library/Python/3.x/bin
