### ISSUE TITLE
bug: Api Gateway V1 custom authorizer CDK re-deployments do not replace the authorizer

### ISSUE THREAD

**Issue by Yehonal** [localstack/localstack#11365]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

This code in CDK is expected to work when I re-deploy my authorizer:

```
    const authorizer = new apigateway.RequestAuthorizer(this, authorizerId, {
      authorizerName: 'myAuthorizer',
      handler: authorizerProxyHandler,
      resultsCacheTtl: cdk.Duration.seconds(authorizerV2.resultTtlInSeconds),
      identitySources: [authorizerV2.identitySource],
    });

    const integration = new apigateway.LambdaIntegration(
      authorizerProxyHandler,
    );
```

However, the first deployment works by setting the right lambda integration, but on re-deployments the authorizer is not replaced with the new lambda. Even if I just change the authorizerName, it keeps the old one. 

As a workaround, I'm changing the RequestAuthorizer id on each deployment and this forces cloudformation to destroy the old resource and create the new one.

### Expected Behavior

When the authorizer code or RequestAuthorizer properties change, it should update the custom authorizer in the ApiGateway

### How are you starting LocalStack?

With the `localstack` script

### Steps To Reproduce

* Use the CDK code above to implement the custom authorizer
* deploy using cdk and test, it should be able to invoke the authorizer
* make a change to the authorizer code or the RequestAuthorizer properties
* re-deploy using cdk
* test the authorizer, it will tell that cannot invoke the lambda because it's pointing to the old one

### Environment

```markdown
- OS: Ubuntu 22.04
- LocalStack:
  LocalStack version: 3.6.1
```

**Comment by cloutierMat** [comment]
Hi @Yehonal, thank you for your report. I have looked into your issue and could root it to the fact the update operation for the authorizer in currently not handled. 

Thanks you for your patience as I look into a fix.
