### ISSUE TITLE
bug: hot-reload does not seem to work on apple silicon M1

### ISSUE THREAD

**Issue by reece-backhouse** [localstack/localstack#11386]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Creating a lambda with the hot-reload magic S3Bucket and correct key, the code works first time. However when making a change, the hot-reload isnt picking up the new changes and new invocations point to the old code.

The same code has been pushed and a colleague has pulled the code on his linux amd64 machine and the hot-reload works seemlessly

### Expected Behavior

hot-reload works on arm64

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker-compose up -d

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    local endpoint=http://localhost:4566

```
 local function_handler=index.handler
 local function_name=lambda
 local function_role=arn:aws:iam::000000000000:role/local
 local function_runtime=nodejs20.x

 aws --endpoint-url $endpoint lambda create-function \
  --code S3Bucket=hot-reload,S3Key="$DIST_FOLDER" \
  --timeout 60 \
  --function-name $function_name \
  --environment Variables="{LOG_LEVEL=info}" \
  --handler $function_handler \
  --role $function_role \
  --runtime $function_runtime \
  --region eu-west-1 
```

### Environment

```markdown
- OS: MacOs M1 Silicon 
- LocalStack:
  LocalStack version:  3.6.0
  LocalStack Docker image sha:
  LocalStack build date: 2024-07-25
  LocalStack build git hash: 5c077c795
```

**Comment by joe4dev** [comment]
Hi @reece-backhouse 👋 

Can you double-check the Docker file sharing permissions on macOS according to our docs: https://docs.localstack.cloud/user-guide/lambda-tools/hot-reloading/
> File sharing permissions with Docker Desktop on macOS: If using Docker Desktop on macOS, you might need to allow [file sharing](https://docs.docker.com/desktop/settings/mac/#file-sharing) for your target folders. MacOS may prompt you to grant Docker access to your target folders.

I can confirm that Lambda Hot reloading works on my arm64 Macbook Pro M1:

```bash
 Downloads awslocal lambda invoke --region eu-west-1 --function arn:aws:lambda:eu-west-1:000000000000:function:lambda outfile
{
    "StatusCode": 200,
    "ExecutedVersion": "$LATEST"
}
➜  Downloads cat outfile
"{\"date\":\"2024-08-26T20:00:22.564Z\",\"message\":\"V1\"}"%

# Changing V1 to V2 in index.js

➜  Downloads awslocal lambda invoke --region eu-west-1 --function arn:aws:lambda:eu-west-1:000000000000:function:lambda outfile
{
    "StatusCode": 200,
    "ExecutedVersion": "$LATEST"
}
➜  Downloads cat outfile
"{\"date\":\"2024-08-26T20:01:36.383Z\",\"message\":\"V2\"}"%
```

Sample `index.js`:

```js
exports.handler =  async (event) => {
  const payload = {
    date: new Date(),
    message: 'V2'
  };
  return JSON.stringify(payload);
};

```

**Comment by reece-backhouse** [comment]
Hey @joe4dev 

Thanks for responding.

The repo is in a subdirectory of the /Users directory which i think should be shared by default?

Is there anything i need to add to the docker compose?

**Comment by joe4dev** [comment]
Hi @reece-backhouse 

> The repo is in a subdirectory of the /Users directory which i think should be shared by default?

Correct. Here's how my Docker configuration looks like:
<img width="1033" alt="Screenshot 2024-08-27 at 11 27 46" src="https://github.com/user-attachments/assets/5ce33050-2077-42a1-8755-fac186c09538">
Under the "Privacy & Security" Settings, I allow access to the Downloads directory:
<img width="697" alt="Screenshot 2024-08-27 at 11 29 07" src="https://github.com/user-attachments/assets/2c3e3f25-0805-4eff-85e2-99d04c4bd01c">

> Is there anything i need to add to the docker compose?

Not really, unless you wish to [Share deployment configuration between different machines](https://docs.localstack.cloud/user-guide/lambda-tools/hot-reloading/#share-deployment-configuration-between-different-machines)

Do you see any warning or error logs if you start LocalStack in debug mode using `DEBUG=1`? Please check the LocalStack logs and the Lambda container logs.

**Comment by reece-backhouse** [comment]
hey @joe4dev 

The only warning on the startup is:

> 2024-08-28T10:04:36.866  WARN --- [  MainThread] l.services.internal        : Enabling diagnose endpoint, please be aware that this can expose sensitive information via your network.

Our docker configuration seems to be the same otherwise and my repo is cloned under /Users however when changes are reflected in my dist folder and the lambda is invoked, the lambda still uses the old code.

**Comment by joe4dev** [comment]
@reece-backhouse Do you get any more insights from the Lambda container logs when adjusting the [LocalStack Lambda Runtime Interface Emulator (RIE)](https://docs.localstack.cloud/user-guide/aws/lambda/#localstack-lambda-runtime-interface-emulator-rie) log level using `LAMBDA_DOCKER_FLAGS=-e LOCALSTACK_INIT_LOG_LEVEL=debug`?

**Comment by joe4dev** [comment]
@reece-backhouse This issue seems related to https://github.com/localstack/localstack/issues/11415#issuecomment-2312605725 and might be caused by different Docker versions. What version are you using?

Example: I can confirm that hot reloading works on my MacBook Pro M1 on macOS 14.6.1 (23G93) with Docker Desktop:
<img width="739" alt="Screenshot 2024-08-29 at 15 21 16" src="https://github.com/user-attachments/assets/d95edc61-f0dc-4142-af37-3b9dfdfeef77">

**Comment by reece-backhouse** [comment]
hey @joe4dev 

These are the version i have:

Docker version 4.33.0 (160616) ( a new version 4.34.0 (165256) seems to be available)
Docker Compose version v2.29.1-desktop.1
Docker Engine v27.1.1

INIT_LOG_LEVEL seems to not do anything noteworthy. I do however see this error now regardless of that var being present or not:

> 2024-08-30 10:05:28 2024-08-30T09:05:28.105  INFO --- [  MainThread] localstack.utils.http      : Unable to download Github artifact from https://cdn.jsdelivr.net/gh/localstack/localstack-artifacts@master/local-certs/server.key to /var/lib/localstack/cache/server.test.pem: Failed to download https://cdn.jsdelivr.net/gh/localstack/localstack-artifacts@master/local-certs/server.key, response code 403 Traceback (most recent call last):
2024-08-30 10:05:28   File "/opt/code/localstack/localstack-core/localstack/utils/http.py", line 290, in do_download
2024-08-30 10:05:28     download(download_url, target_file, timeout=timeout, request_headers=request_headers)
2024-08-30 10:05:28   File "/opt/code/localstack/localstack-core/localstack/utils/http.py", line 202, in download
2024-08-30 10:05:28     raise Exception("Failed to download %s, response code %s" % (url, r.status_code))
2024-08-30 10:05:28 Exception: Failed to download https://cdn.jsdelivr.net/gh/localstack/localstack-artifacts@master/local-certs/server.key, response code 403

**Comment by joe4dev** [comment]
@reece-backhouse Thanks for sharing the Docker versions

The certificate error is unrelated to Lambda hot reloading and an unfortunate side-effect of a current [incident](https://localstack.statuspage.io/incidents/lpwmzs8x47y8). Please update to the latest image and follow the recommendations on our status page. Sorry for the inconvenience.

**Comment by reece-backhouse** [comment]
hey @joe4dev 
i have resolved the ssl issue, however the hot-reloading is still not working

**Comment by dfangl** [comment]
Hi @reece-backhouse !
What file sharing implementation are you using on your Docker Desktop?
You can find it under `Settings - General`. We recommend `VirtioFS`, as we noticed it produces the most consistent behavior.

**Comment by reece-backhouse** [comment]
hey @dfangl 
My sharing implementation is VirtioFS already.
Do you have the Rosetta setting enabled in the same menu?

thanks

**Comment by dfangl** [comment]
Yes, it is enabled on my test machine.

Can you double check if the changes, once you make them, are propagated into the lambda docker container properly? For example using `docker exec <lambda_container> cat /var/task/<handlerfile>`.

**Comment by reece-backhouse** [comment]
hey @dfangl 

the code has the correct changes, which is strange. Perhaps this has something to do with how the lambda is being invoked?

We are using `InvokeCommand` with the correct function name with a lambda client with an endpoint of `http://localhost:4566`

**Comment by dfangl** [comment]
The method of invocation should not make any difference.

Sadly, I am not able to reproduce the same issue as on your machine at all. Could you try to set `LAMBDA_DOCKER_FLAGS=-e LOCALSTACK_INIT_LOG_LEVEL=debug` and post the logs of the spawned lambda container here?

Also, a docker restart might help, if you haven't tried this already.

**Comment by reece-backhouse** [comment]
I have found the issue for this. 

We were compiling our ts using tsc. For some reason compiling using tsc and hot reloading with localstack seems to be an issue. Switching to esbuild has fixed this.

**Comment by dfangl** [comment]
Very interesting, thanks for updating us! I will try to find the root cause for this on the next iteration of the hot reloading functionality, maybe there is something we can do there.
