### ISSUE TITLE
bug: LocalStack Overrides S3 Buckets, Causing Request Failures in Local Environment with NestJS, Node.js, and Axios

### ISSUE THREAD

**Issue by nireld** [localstack/localstack#11421]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The request fails when running in LocalStack with NestJS, Node.js, and Axios, while the same request succeeds when not using LocalStack. It seems like LocalStack is overriding or interfering with the S3 bucket configuration.

### Expected Behavior

The request should successfully retrieve the file from the S3 bucket when running in LocalStack, just as it does in a non-LocalStack environment.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

Set up LocalStack in a local environment with a NestJS and Node.js application.
Use Axios to attempt to access an existing file in an S3 bucket using a valid URL within the application.
Example URL: https://cloudfront-dns-prod-distbucket-1insu335c4yqy.s3.amazonaws.com/-_64eb1.js
Observe that the request fails in LocalStack but works fine when tested outside of LocalStack.

### Environment

```markdown
- OS: MAC
- LocalStack:
  LocalStack version: 3.4.0
```

**Comment by bentsku** [comment]
Hello @nireld and thanks for the report.

Unfortunately, it seems we don't have anything actionable here to try to debug or understand the issue. Could you please share a minimal reproducible sample, or share some LocalStack logs with the failure? Could it be related to the [virtual hosted style](https://docs.localstack.cloud/user-guide/aws/s3/#path-style-and-virtual-hosted-style-requests)?

Thanks!
