### ISSUE TITLE
feature request: s3 eventbridge notifications to include the version-id when bucket version is enabled.

### ISSUE THREAD

**Issue by eoghanArtrya** [localstack/localstack#11448]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Currently the version-id of objects created in s3 are not included in the resulting eventbridge notifications. Eyeballing the s3/notifications.py can see it is a property on the S3EventNotificationContext.

### 🧑‍💻 Implementation

https://github.com/localstack/localstack/blob/a23e2fc70542af481fb3a0bd7042627ff50f0802/localstack-core/localstack/services/s3/notifications.py#L708-L721
Just add `"version-id": ctx.key_version_id` to the object?

https://github.com/localstack/localstack/blob/a23e2fc70542af481fb3a0bd7042627ff50f0802/localstack-core/localstack/services/s3/notifications.py#L99-L116

### Anything else?

I am willing to look further at this and open a PR but i do want to first confirm its not a premium feature or something? It does look to be completely omitted.

**Comment by bentsku** [comment]
Hello @eoghanArtrya and thanks for the report!

I can tackle it this afternoon, as I can take the opportunity to also improve our handling of DeleteMarkers (currently we always send `Permanently Deleted` in EventBridge). I'll link the PR shortly!
