### ISSUE TITLE
Add support for S3 conditional writes

### ISSUE THREAD

**Issue by steingran** [localstack/localstack#11455]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

AWS S3 now supports Conditional Writes: https://aws.amazon.com/about-aws/whats-new/2024/08/amazon-s3-conditional-writes/

Can this features also be added to Localstack?

**Comment by bentsku** [comment]
Hello @steingran and thanks for your report!

We've already implemented the Conditional Write feature the day after it came out: #11402 and it is already part of the `3.7` docker image and `latest`. Could you please confirm that it is working for you? 

Thank you!

**Comment by steingran** [comment]
Great, that was quick. Sorry, I could not figure that out before creating this issue. I will check it out, thanks!

**Comment by bentsku** [comment]
No worries, we should have done a better job at advertising it too! It was a small line in our [3.7 release notes](https://blog.localstack.cloud/2024-08-29-localstack-release-v-3-7-0/). Please don't hesitate if you have any issues. Thank you!
