### ISSUE TITLE
bug: When querying RDS Data Execute Statement with SQL query of `information_schema.tables` returns wrong type

### ISSUE THREAD

**Issue by newhoggy** [localstack/localstack#11464]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Logs show this:

```
           ┃           │ AwsLogEntry {logLevel = Debug, builder = "[Client Request] {\n  host      = localhost:32809\n  secure    = False\n  method    = POST\n  target    = Nothing\n  timeout   = ResponseTimeoutMicro 70000000\n  redirects = 0\n  path      = /Execute\n  query     = \n  headers   = x-amz-content-sha256: b7393e014f3da8a51551a23cc15abb8adca4996a2800bb221b055d5eef4cad49; x-amz-date: 20240904T144038Z; host: localhost:32809; content-type: application/x-amz-json-1.1; authorization: AWS4-HMAC-SHA256 Credential=test/20240904/us-east-1/rds-data/aws4_request, SignedHeaders=content-type;host;x-amz-content-sha256;x-amz-date, Signature=4cc5f67921affffc80a1097a29a0a7b948c4298235f9c5ad2985f735c6e5369e\n  body      = {\"resourceArn\":\"arn:aws:rds:us-east-1:000000000000:cluster:my-cluster\",\"secretArn\":\"arn:aws:secretsmanager:us-east-1:000000000000:secret:my-aurora-cluster-LZssjE\",\"sql\":\"SELECT table_name\\nFROM information_schema.tables\\nWHERE table_schema = 'public'\\n  AND table_type = 'BASE TABLE';\\n\"}\n}"}
           ┃           │ AwsLogEntry {logLevel = Debug, builder = "[Client Response] {\n  status  = 200 \n  headers = content-type: text/plain; charset=utf-8; content-length: 133; x-amzn-requestid: 9e9d81c2-6466-4e4c-88e4-fdab84f88dcf; x-amz-request-id: 9e9d81c2-6466-4e4c-88e4-fdab84f88dcf; connection: close; date: Wed, 04 Sep 2024 14:40:38 GMT; server: hypercorn-h11\n}"}
           ┃           │ AwsLogEntry {logLevel = Trace, builder = "[Raw Response Body] {\n{\"records\": [[{\"doubleValue\": \"migration\"}], [{\"doubleValue\": \"users\"}], [{\"doubleValue\": \"projects\"}]], \"numberOfRecordsUpdated\": 0}\n}"}
           ┃           │ AwsLogEntry {logLevel = Error, builder = "[SerializeError] {\n  service = RDSData\n  status  = 200 \n  message = Error in $[0][0].doubleValue: parsing Double failed, unexpected String\n  body    = Just {\"records\": [[{\"doubleValue\": \"migration\"}], [{\"doubleValue\": \"users\"}], [{\"doubleValue\": \"projects\"}]], \"numberOfRecordsUpdated\": 0}\n}"}
```

In other words when running `ExecuteStatement` in RDS Data with the SQL query:

```sql
SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' AND table_type = 'BASE TABLE' 
```

The return JSON result is this:

```
{"records": [[{"doubleValue": "migration"}], [{"doubleValue": "users"}], [{"doubleValue": "projects"}]], "numberOfRecordsUpdated": 0}
```

But `doubleValue` is the incorrect type.  The values returned (eg. "migration", "users", "projects") are in fact strings and should be typed as `stringValue`.

### Expected Behavior

The expected returned JSON should be this:

```json
{"records": [[{"stringValue": "migration"}], [{"stringValue": "users"}], [{"stringValue": "projects"}]], "numberOfRecordsUpdated": 0}
```

ie `stringValue` instead of `doubleValue`.

### How are you starting LocalStack?

Custom (please describe below)

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal s3 mb s3://mybucket

### Environment

```markdown
- OS: Linux
- LocalStack:
  LocalStack version: All versions since localstack/localstack-pro:3.2.0
  LocalStack Docker image sha: `8b5eb7ce1906`
  LocalStack build date:
  LocalStack build git hash:

This worked properly in `localstack/localstack-pro:3.1.0`
```

**Comment by steffyP** [comment]
Hi @newhoggy, 

I am not able to reproduce your issue with the `latest` localstack version, e.g. it's returning `stringValue` for me as expected. 
I tested with aurora-mysql, which starts up `mysql:8.0.32` on my machine. 

Could you provide more input if you still see this issue with the `lastest` localstack version? 🙏 

E.g. what version are you using, how are you creating the aurora database, any additional settings you have for LocalStack startup, any scripts or inserts you run on the database.

**Comment by newhoggy** [comment]
We are using postgres.

**Comment by steffyP** [comment]
Hi @newhoggy, 

thanks for clarifying. We were able to reproduce the issue, the fix is available in the `latest` pro-image already. 
We would appreciate your feedback.

**Comment by newhoggy** [comment]
Wow!  Thanks.  Will try now.

**Comment by newhoggy** [comment]
Yep.  It looks to be working!

https://github.com/haskell-works/rds-data/actions/runs/10721033357?pr=7

Again, thanks so much!
