### ISSUE TITLE
Transfer ownership of serverless-localstack

### ISSUE THREAD

**Issue by temyers** [localstack/localstack#1147]
Follow up from #855.

@whummer - No worries on transferring ownership.  I was mindful that I wasn't giving the project the attention it deserved, so this is a good outcome.

I have added you to the serverless-localstack npm package - please can you confirm you have access?

**Comment by whummer** [comment]
Thanks @temyers - I can confirm that I have access to the npm package. 👍  Meanwhile, we've forked the project and released it under a new name [`localstack-serverless`](https://www.npmjs.com/package/localstack-serverless) which is more in line with our general naming scheme for all our components (`localstack-*`). Of course, we will continue listing your name as an author/contributor of the npm package, moving forward. Hope that's an acceptable solution for you. Thanks again for contributing this super useful package!

**Comment by temyers** [comment]
> Hope that's an acceptable solution for you
:+1: 

One point of consideration is how people will discover the plugin in the future.

the original `serverless-localstack` naming convention was in line with other Serverless Framework projects.

I don't have any data, but could the name change harm discoverability?

A couple of extra house keeping:
1. Remove the ```Archived

This project is no longer under active development.``` from your forked repo.

2. Name conflicts/renames, etc are confusing - is there anything I can do on the original repo/npm to help avoid confusion?

**Comment by whummer** [comment]
Good point @temyers - agreed. Renamed the package back to its original name: https://github.com/localstack/serverless-localstack/pull/4

**Comment by temyers** [comment]
I've also updated my original repository readme to point to it's new home.

Should be good to go.

I'd moved away from using Localstack, but can see you guys have been doing some great work.  So will be reevaluating again.

**Comment by temyers** [comment]
Also, if you think it's stable enough, adding here will help drive adoption and discoverability

https://github.com/serverless/plugins

**Comment by whummer** [comment]
Great. Thanks for the pointers!
