### ISSUE TITLE
bug: Authorized Route in API-GW-v2 always returns HTTP 401

### ISSUE THREAD

**Issue by awehrung** [localstack/localstack#11470]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When calling an endpoint for a route that uses a Lambda-Authorizer, I get an exception in Localstack and the call returns HTTP-status 401 with `{"message": "Unauthorized"}`, even when the authorizer always says OK.

### Expected Behavior

The call should return HTTP-status 200 and the expected response with a "pass-through" authorizer, as it does without an authorizer.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

As this needs a couple of resources to reproduce, I've put a small repo together: https://github.com/awehrung/localstack-testing

### Environment

```markdown
- OS:Ubuntu 22.04
- LocalStack-Pro: 3.7.0 (sha256:4efa49cbb948a802c3dc02964ba50d964950ee20e52910d1f822e3081b9b8eb8)

From the startup logs:

  LocalStack version: 3.7.1.dev1
  LocalStack build date: 2024-08-29
  LocalStack build git hash: a8555a9d
```

### Anything else?

Thanks for the support!

**Comment by mAdM4x1** [comment]
Same problem with Fedora Linux 40. Same configuration. (working on same project :smiley:

**Comment by awehrung** [comment]
Definitely! Thanks for the quick explanation. I came across this behaviour while debugging another problem with my setup, now I can hopefully reproduce my original problem completely. I'd probably better open another issue if this is the case.

**Comment by bentsku** [comment]
Yes, definitely! Feel free to close this issue and open a new one, we'll look into shortly too 😄

**Comment by awehrung** [comment]
Update @bentsku → it seems that the misconfiguration you pointed out was actually the root of my problem :sweat_smile: the apparent error was that no CORS-headers were present in the response, turns out that the "abrupt" 401-response of API-GW was the cause of this. Adding the `Authorization` header solves the issue.

When testing against AWS, it works fine without the `Authorization` header though (Auth info comes through a cookie). I probably configured both differently by mistake.

**Comment by bentsku** [comment]
Oh, awesome, thanks for the edit, I understand now how the situation came to be. Awesome, thanks a lot for coming back to us so quickly, and I'm glad the issue got resolved! 

We're currently working on a rewrite of our implementation 😄 I might ping you when it's available if you'd like to test it, hopefully we should be even closer to AWS in lots of situation. 

Thanks again!
