### ISSUE TITLE
feature request: Support for Serverless Framework V4

### ISSUE THREAD

**Issue by paulbenschmidt** [localstack/localstack#11493]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Currently, `serverless-localstack` (serverless [plugin](https://www.serverless.com/plugins/serverless-localstack) and [repo](https://github.com/localstack/serverless-localstack)) only provides support up to Serverless Framework version 3.39. 

At the end of 2024, Serverless Framework will no longer actively maintain non-v4 versions. Serverless's [docs](https://www.serverless.com/framework/docs/guides/upgrading-v4) mention: 
> Serverless Framework V.3 will continue to be maintained via critical security and bug fixes through 2024.

This issue was raised in the LocalStack Slack [here](https://localstack-community.slack.com/archives/CMAFN2KSP/p1725918073717339). Completing this feature request will require setting up tests and integrations.

### Anything else?

Docs for upgrading to Serverless V4 are [here](https://www.serverless.com/framework/docs/guides/upgrading-v4).

**Comment by lefuncq** [comment]
Hi there, any updates on that one?

**Comment by tchambard** [comment]
Hello, is there an ETA for V4 compatibility ?

**Comment by pinzon** [comment]
Hi everyone. We received confirmation from the Serverless team that the latest version of Serverless (v4.4.7) is compatible with the LocalStack plugin. Feel free to give it a try. I'm closing the issue and will reopen it if any issue arises.

**Comment by paulbenschmidt** [comment]
@pinzon: I'm trying the upgrade now! I'm currently getting a failure, saying that Serverless is expecting AWS credentials:
```
        _credentialsPromise: Promise {
          <rejected> [ServerlessError: AWS credentials missing or invalid. Original error from AWS: Could not load credentials from any providers] {
            code: 'AWS_CREDENTIALS_MISSING',
            originalMessage: 'Could not load credentials from any providers',
            originalName: 'CredentialsProviderError',
            providerError: CredentialsProviderError: Could not load credentials from any providers
                at <anonymous> (/home/runner/.serverless/releases/node_modules/@aws-sdk/credential-provider-node/dist-cjs/index.js:136:13)
                at <anonymous> (/home/runner/.serverless/releases/node_modules/@smithy/property-provider/dist-cjs/index.js:97:33)
                at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                at coalesceProvider (/home/runner/.serverless/releases/node_modules/@smithy/property-provider/dist-cjs/index.js:124:18)
                at <anonymous> (/home/runner/.serverless/releases/node_modules/@smithy/property-provider/dist-cjs/index.js:142:18)
                at getAwsCredentials (/home/runner/.serverless/releases/4.4.7/sf-core/src/lib/resolvers/providers/aws/credentials.js:50:12)
                at Aws.resolveCredentials (/home/runner/.serverless/releases/4.4.7/sf-core/src/lib/resolvers/providers/aws/aws.js:146:12)
                at Aws.resolveVariable (/home/runner/.serverless/releases/4.4.7/sf-core/src/lib/resolvers/providers/index.js:87:28)
                at Aws.resolveVariable (/home/runner/.serverless/releases/4.4.7/sf-core/src/lib/resolvers/providers/aws/aws.js:77:5)
                at getAwsCredentialProvider (/home/runner/.serverless/releases/4.4.7/sf-core/src/utils/credentials/index.js:40:20) {
              tryNextLink: false
            }
          }
        },
        isDefaultConfig: false
```

Localstack has a [closed issue for this bug](https://github.com/localstack/localstack/issues/6912) that recommends adding dummy creds. However, when I do this, I get the following failure:
```
Recoverable error occurred (read ECONNRESET), sleeping for ~7 seconds. Try 4 of 4
s:sls:aws:request: request: #5 CloudFormation.describeStackResource [
  {
    StackName: 'my-serverless-local-bucket',
    LogicalResourceId: 'ServerlessDeploymentBucket'
  }
]
s:sls:aws:request: request error: #5 - CloudFormation.describeStackResource TimeoutError: read ECONNRESET
s: Error: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:218:20)
```

**Comment by pinzon** [comment]
Hi @paulbenschmidt,  I don't think there has been any changes on how LocalStack handle credentials. I just manually tested running the sample template in our plugin repo and **it deploys correctly** using serverless version `4.4.7`.

From the logs it doesn't seem like a LocalStack issue to me. It looks like the  JS aws-sdk It's not able to access any credentials; and the connection is rejected like is trying to access AWS and not LS. Could be an issue with your current setup or template. 

I recommend triaging directly the aws-sdk lib or using a simpler template. Please open a new issue regarding that particular problem with a sample and logs from the serverless tool and logs .

**Comment by paulbenschmidt** [comment]
Thanks, @pinzon! You were correct. The issue was unrelated. It turned out to be a port issue: we were using some port overrides for CloudFormation and S3, but swapping back to the default 4566 worked fine.

**Comment by Berns89** [comment]
So with Serverless no longer going to add newer Node versions to V3 moving forward after v20 and end of life for v20 being April 2026, this is becoming more of a priority I hope? Basically Serverless is forcing everyone to move to v4 and the forked versions does not have all support atm. Does anyone have any ideas?

**Comment by pinzon** [comment]
@Berns89 as stated in an earlier comment. This is a non issue. The localstack-serverless plugin already works with Serverless  Framework v4.
