### ISSUE TITLE
bug: s3 PutObject hangs after requesting invalid range with GetObject

### ISSUE THREAD

**Issue by sameer** [localstack/localstack#11534]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The following sequence hangs on the last step:

1. Create a bucket `foo` (CreateBucket)
2. Upload a 500 byte object `bar` (PutObject)
3. Try to get an invalid range for `bar` i.e. `bytes=544-`, which returns InvalidRange as expected (GetObject)
4. Upload `bar` again with the same data, this times out (PutObject)

Step 3 causes step 4 to fail, but I'm not sure why.

### Expected Behavior

Step 4 should succeed.

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

`SERVICES=s3 LS_LOG=trace localstack start `

^ I have confirmed that it still happens without the `SERVICES` env var set.

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```
aws s3 mb s3://foo
dd if=/dev/zero of=bar bs=500 count=1 # make a 500 byte file
aws s3 cp bar s3://foo
aws s3api get-object --bucket foo --key bar --range 'bytes=544-' outfile # this fails, as expected
aws s3 cp bar s3://foo # this hangs and will eventually time out
```

### Environment

```markdown
- OS: macOS Sonoma 14.6.1
- LocalStack:
  LocalStack version: 3.7.3.dev28
  LocalStack build date: 2024-09-16
  LocalStack build git hash: dadf66461
```

### Anything else?

Based on the trace logs, the request never returns. I wonder if there's a deadlock somewhere.

**Comment by bentsku** [comment]
Hey @sameer, thank you so much for your report! The linked PR will fix the issue, once the PR is merged, the `latest` version of LocalStack should contain the fix in the hour or so after. Thanks again!
