### ISSUE TITLE
feature request: Support for ValidateStateMachineDefinition since this now blocks upgrading AWS Teraform provider to 5.67.0

### ISSUE THREAD

**Issue by tonestrike** [localstack/localstack#11553]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

On 9/12/24, [version 5.67.0 of the terraform-provider-aws](https://github.com/hashicorp/terraform-provider-aws/releases/tag/v5.67.0) was released which added support for plan time step function definition validation.

```
resource/aws_sfn_state_machine: Add plan-time validation of definition using the AWS Step Functions [Validation API](https://docs.aws.amazon.com/step-functions/latest/apireference/API_ValidateStateMachineDefinition.html) (https://github.com/hashicorp/terraform-provider-aws/issues/39229)
```

Since this relies on the `ValidateStateMachineDefinition` action, upgrading to the latest Terraform AWS provider causes any existing Step Function definition defined in Terraform to break.

Lack of support for this operation is documented [here](https://docs.localstack.cloud/references/coverage/coverage_stepfunctions/). It would be great to not have to pin the AWS provider version in order to deploy local step functions using Terraform with Localstack.

**Comment by MEPalma** [comment]
Thank you for taking the time to compile this report. I was able to replicate the behavior that resulted in the failure. We recently merged changes that introduced base support for ValidateStateMachineDefinition, which should unlock the workflow described. While more thorough definition validation logic for state machines is still being worked on, this initial implementation should address your immediate issue. Could you verify if this resolves your issue? If it does, feel free to close this issue. If you're still experiencing problems, please let us know and we'll investigate further. Thank you again for bringing this issue forward.
