### ISSUE TITLE
bug: fromDockerBuild makes error "spawnSync docker ENOENT"

### ISSUE THREAD

**Issue by namse** [localstack/localstack#11555]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I use `cdk.aws_lambda.Code.fromDockerBuild` to create code for lambda, it makes error `Error: spawnSync docker ENOENT`

### Expected Behavior

build without error

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

docker compose up, run cdk in `/etc/localstack/init/ready.d/init-aws.sh`

### Environment

```markdown
LocalStack version: 3.7.3.dev38
LocalStack build date: 2024-09-20
LocalStack build git hash: 5271fc02
```

**Comment by joe4dev** [comment]
Hi @namse 👋 

The Docker CLI is not installed in the LocalStack image. Could you double-check that the Docker CLI is installed where you are running Docker via CDK?
This GitHub issue shows how CDK discovers Docker https://github.com/aws/aws-cdk/issues/30570#issuecomment-2176755260 using `CDK_DOCKER` or assuming `docker` is in the `PATH`.
