### ISSUE TITLE
Separate Image per Service

### ISSUE THREAD

**Issue by deleugpn** [localstack/localstack#1156]
I'm currently using SQS for some integration tests and localstack is an amazing tool for that. However, it had quite an impact on the pipeline execution time due to the nearly 1GB download and container start-up process.
I was wondering whether it was considered before or if there's any hard limitation that prevents localstack from offering dedicated images for single services. I can only imagine that a dedicated image only for SQS would be much smaller than the full image box.

**Comment by whummer** [comment]
In terms of startup time, you can customize the services to be started by setting the environment variable `SERVICES=sqs`.

As far as download time, there are no plans to create N images for the N different services. However, one option we are considering is to provide a slim generic base image that only contains the core libs, which then downloads any required additional libraries on demand (depending on which service(s) is/are to be started).

**Comment by deleugpn** [comment]
Not ideal as having dedicated images per service, but sounds like it could be a huge improvement nonetheless and way easier to maintain. Awesome idea.

**Comment by ta32** [comment]
the issue of having many services in a single container - is that it takes ages to start up. If one service fails the whole container is still running and waiting for it. I understand this library is in development but i hope you eventually create separate images and use the compose file to start them up. It will give developers a lot of flexibility and confirms with docker best practises

for me the S3 service is not starting... 
2019-03-28T05:08:08:WARNING:infra.pyc: Service "s3" not yet available, retrying..

**Comment by whummer** [comment]
Thanks all for chiming in. Closing this as "won't fix" for now. We'll continue to roll out a single image, as that's what most users are asking for.

You can still configure multiple containers by using the `SERVICES` configuration, as specified above. You can then achieve the same functionality as with separate image.

The additional startup delay of parsing the Python code should be negligible (as each container would only activate the code parts that are relevant for its SERVICES). Thanks
