### ISSUE TITLE
feature request: Add ability to override cpu mode on libvirt EC2 instances

### ISSUE THREAD

**Issue by cwells** [localstack/localstack#11583]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Currently when creating an EC2 instance via libvirt, localstack uses the following configuration:

```
 <cpu mode='custom' match='exact' check='none'>
    <model fallback='forbid'>qemu64</model>
  </cpu>
```

I'm trying to boot Amazon Linux 2023 and it needs `host-passthrough` otherwise it kernel panics on boot.

I can get the instance to start by editing `/etc/libvirt/qemu/<instance-id>.xml` and changing this to

`<cpu mode='host-passthrough' check='none' migratable='on'/>`

and starting the instance via virsh.

It would be useful to be able to override the cpu mode. I tried using `QEMU_CPU=host-passthrough`, but I'm guessing this is overridden by the XML.

### Anything else?

It kind of seems like host-passthrough should be the default.

**Comment by viren-nadkarni** [comment]
This is now set by default using `<cpu mode="host-passthrough" />`
