### ISSUE TITLE
bug: Secret list include also deleted Secret

### ISSUE THREAD

**Issue by llowinge** [localstack/localstack#11635]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Lets say i create secret named `Secret1` and `Secret2`.
I then delete `Secret1`.
I list the secrets and `Secret1` is still present, but according to https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/secretsmanager/model/ListSecretsRequest.Builder.html#includePlannedDeletion(java.lang.Boolean) `By default, secrets scheduled for deletion aren't included.`.

### How are you starting LocalStack?

With a `docker run` command

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

### Environment

```markdown
- OS:
- LocalStack:
  LocalStack version:
  LocalStack Docker image sha:
  LocalStack build date:
  LocalStack build git hash:
```

**Comment by kaushal540** [comment]
Hi @dominikschubert @macnev2013  @MEPalma 

Please review this PR when you have a chance. It addresses the issue by improving the `list-secrets` API to exclude deleted secrets.

Thanks!

**Comment by kaushal540** [comment]
The issue has been addressed in [PR](https://github.com/getmoto/moto/pull/8335).
Please validate and close the ticket.

**Comment by llowinge** [comment]
@kaushal540 In which version of localstack i can verify it ?

**Comment by viren-nadkarni** [comment]
The fix will be available in LocalStack after the next Moto bump.
