### ISSUE TITLE
feature request: Support KMS DeriveSharedSecret operation

### ISSUE THREAD

**Issue by rbonestell** [localstack/localstack#11638]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Our software and team rely heavily on the `DeriveSharedSecret` operation in AWS KMS to securely derive shared secrets as part of our encryption and data security protocols. Currently, LocalStack KMS does not support this operation which forces us to implement additional "local only" code to handle this functionality during local development and testing. This adds unnecessary complexity and divergence from production environments, as well as the potential for bugs.

https://docs.aws.amazon.com/kms/latest/APIReference/API_DeriveSharedSecret.html

We would greatly benefit from LocalStack supporting the `DeriveSharedSecret` operation in its KMS implementation, as this would allow us to align our local testing environments more closely with AWS production environments, reduce overhead in our development processes, and streamline our local testing workflows.

Thank you for considering this feature request, and we appreciate all the work done to make LocalStack such a valuable tool for AWS emulation!

**Comment by sannya-singal** [comment]
Hey @rbonestell 👋 Thanks for creating a feature request. We now have an initial implementation of `DeriveSharedSecret` operation in KMS in the `latest` image. Please do not hesitate to contact us if you have any further questions or encounter new issues.

**Comment by rbonestell** [comment]
I've gotten around to implementing `DeriveSharedSecret` using LocalStack 4 Pro and it is not behaving with parity to AWS KMS. When I upload key material for the following key params, decryption using LocalStack KMS results fail to validate the signed message tag after deriving the shared key. This demonstrates that the derived key result from LocalStack doesn't match that derived by AWS KMS.

```
{
  keyParams: {
    Origin: "EXTERNAL",
    KeySpec: "ECC_NIST_P256",
    KeyUsage: "KEY_AGREEMENT",
  },
}
```

When debugging the code which uses the AWS SDK to execute the `DeriveSharedSecret` for the same data, same public key, and the private key, which was created and key material uploaded in the same manner to both AWS and LocalStack KMS, the resulting derived shared secrets are completely different from this simple code:

```
const command = new DeriveSharedSecretCommand({ 
	KeyAgreementAlgorithm: KeyAgreementAlgorithmSpec.ECDH,
	KeyId: keyId,
	PublicKey: publicKey
 });
const response = await this.kmsClient.send(command);
```
