### ISSUE TITLE
CloudWatch Logs supported?

### ISSUE THREAD

**Issue by mvayngrib** [localstack/localstack#117]
is something like this supposed to work at this time?

aws logs describe-log-groups --endpoint-url http://localhost:4582

**Comment by elioncho** [comment]
I also want to know if Cloud Watch Logs is supported

**Comment by obprado** [comment]
Is there any workaround to access logs while Logs are not accessible through CLI?

**Comment by jpradelle** [comment]
Using docker there is many logs running `docker logs localstack_localstack_1` where localstack_localstack_1 is docker instance name

For lambda triggered asynchronously (by SNS for example) logs are not in docker logs of localstack image, but can be found with a trick:
Run localstack with `LAMBDA_EXECUTOR=docker`
Each time a lambda is triggered it creates a new docker instance which can be found using `docker ps -a`
```
$ docker ps -a
CONTAINER ID        IMAGE                                               COMMAND                  CREATED             STATUS                      PORTS                                                                                                                      NAMES
ac7a9a146302        lambci/lambda:nodejs6.10                            "/var/lang/bin/nod..."   22 minutes ago      Exited (1) 21 minutes ago                                                                                                                              distracted_williams
353557389d4b        localstack/localstack                               "/usr/bin/supervis..."   31 minutes ago      Up 31 minutes               0.0.0.0:4567-4583->4567-4583/tcp, 0.0.0.0:8080->8080/tcp                                                                   localstack_localstack_1
```
And then open logs on it `docker logs distracted_williams`. The name of image change each time a lambda is triggered

**Comment by zachschultz** [comment]
@jpradelle while that is a good way to view logs from executing Lambdas, I don't think it addressed the main issue at hand (which I'm having too). I'd like to be able to test certain policies I'm writing for my lambdas against log groups and streams, and having CloudWatch Logs as a feature in localstack would be great, and necessary, for me to do the testing I want.

**Comment by ejjick** [comment]
I couldn't find a solution to this issue either. It seems the container you want to query with `docker logs` is always at top so this command makes it a bit easier.

```
docker logs `docker ps -a | sed -n 2p | grep -oE '[^ ]+$'\`
```

**Comment by whummer** [comment]
Initial support for CloudWatch Logs added in #1161 .

Lambda logs should be automatically forwarded to CloudWatch Logs (see integration tests in #1161).
