### ISSUE TITLE
bug: Hitting Internal Server Error(500) for get_bucket_policy for s3 in localstack

### ISSUE THREAD

**Issue by jsavantika** [localstack/localstack#11737]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hitting this error:

botocore.exceptions.ClientError: An error occurred (500) when calling the GetBucketPolicy operation (reached max retries: 4): Internal Server Error

### Expected Behavior

This use to work before I upgraded my terraform from 5.69.0 to 5.70.0

### How are you starting LocalStack?

With a `docker run` command

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    s3_client = boto3.client("s3")
    response = s3_client.get_bucket_policy(Bucket="bucket-name")

### Environment

```markdown
- OS:ubuntu:22.04
- Terraform: 5.70.0
- LocalStack:
  LocalStack version:3.8.0
```

**Comment by bentsku** [comment]
Hello @jsavantika and thanks for the report!

Unfortunately I cannot reproduce the issue directly. What exactly are the steps to reproduce the issue? Do you set up a Bucket Policy beforehand? Thanks!

**Comment by bentsku** [comment]
I still cannot reproduce the issue. Could you share a minimal reproducible sample? 

Starting LocalStack and running those operations do not trigger errors:
```bash
$ awslocal s3api get-bucket-policy --bucket test     
An error occurred (NoSuchBucket) when calling the GetBucketPolicy operation (reached max retries: 0): The specified bucket does not exist
$ awslocal s3 mb s3://test
make_bucket: test
$ awslocal s3api get-bucket-policy --bucket test
An error occurred (NoSuchBucketPolicy) when calling the GetBucketPolicy operation (reached max retries: 0): The bucket policy does not exist
```

I suspect it is maybe something related to the Policy in itself, some assumptions we make that may not hold? 

Could you start LocalStack with `LS_LOG=trace` and share the logs when this exception happens? Thanks
