### ISSUE TITLE
bug: initial, parallel jwks.json calls give different results

### ISSUE THREAD

**Issue by sam-super** [localstack/localstack#11750]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When the jwks.json endpoint is hit for the first time it takes a while to return. if multiple requests are issued in parallel against the same user pool, each one returns a different set of public keys (JWKs).

### Expected Behavior

Each one should return the same set (e.g. the first worker to receive the request should probably block the other reqs until the public key is generated and persisted before responding).

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

if you run this script you should see something like this:
```
Creating pool test-1730016221
Created with id: us-east-1_071588411fd043b8a53da2d29d0f4c36
Getting jwks.json (.keys[].kid) for the first time in parallel...
"f4af1919-f704-4733-a397-9bbc3ad500fc"
"5944898b-b609-4130-a268-28ed598ed8e8"
"bf373e25-9d63-4096-aeb0-32fdecd0caae"
"cca4c96f-d6ec-4eac-ba64-904d4eebfe1c"
Getting jwks.json (.keys[].kid) after a pause (still in parallel)
"cca4c96f-d6ec-4eac-ba64-904d4eebfe1c"
"cca4c96f-d6ec-4eac-ba64-904d4eebfe1c"
"cca4c96f-d6ec-4eac-ba64-904d4eebfe1c"
"cca4c96f-d6ec-4eac-ba64-904d4eebfe1c"
```

```bash
#!/usr/bin/env bash

set -e

POOL_NAME="test-$(date +%s)"

echo "Creating pool ${POOL_NAME}"

POOL_ID=$(aws --region=us-east-1 --endpoint-url=http://localhost:4566 cognito-idp create-user-pool --pool-name "$POOL_NAME" --output text --query 'UserPool.Id' --output text)

echo "Created with id: $POOL_ID"

get_jwk() {
  curl -s "http://localhost:4566/$POOL_ID/.well-known/jwks.json" | jq '.keys[].kid'
}

echo "Getting jwks.json (.keys[].kid) for the first time in parallel..."
get_jwk &
get_jwk &
get_jwk &
get_jwk &

wait

sleep 1

echo "Getting jwks.json (.keys[].kid) after a pause (still in parallel)"
get_jwk &
get_jwk &
get_jwk &
get_jwk &

wait
```

### Environment

```markdown
- OS: macos
- LocalStack:
  localstack/localstack-pro@sha256:e9daf0a54d8c1b8f9b5d3ae80983f00e2a60c31032b6c7d5a6c776638259e712
```

### Anything else?

The reason i found this is because i'm trying to get my tests to run in parallel, but due to the time to create pools/client etc, they share a cognito pool. When they spin up in parallel they make the same initial requests for the jwks.json and get different results for the `kid` in the keys, which causes the tests to fail auth (the access token jwt we create has a kid that doesn't match the jwk). 

I can work around this in my by making sure i issue a request to the jwks.json endpoint before my tests start and before i create the access token.

**Comment by bentsku** [comment]
Hello @sam-super and thanks for your report, it was very helpful!

I could reproduce the issue, and now have merged the fix. It is now available in the `localstack/localstack-pro:latest` image. Blocking during the creation of the keys also makes this quite faster. Thanks again!
