### ISSUE TITLE
bug: event.requestContext.connectionId not set when calling SQS from API WebSocket Gateway on $connect

### ISSUE THREAD

**Issue by chkp-roeyl** [localstack/localstack#11775]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When using AWS API Gateway WebSocket with $connect integration:
Previous Behavior: When a Lambda function was triggered for $connect, the event.requestContext.connectionId field was populated as expected.
Current Issue: After switching the $connect integration from Lambda to SQS, the connectionId field is missing in the context. However, other fields, such as requestId, authorizer, and querystring are still present.

### Expected Behavior

 event.requestContext.connectionId should be available in the context when using SQS with WebSocket $connect, similar to the behavior on AWS

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal s3 mb s3://mybucket

### Environment

```markdown
- OS: macOS
- LocalStack: 3.8.1
```

**Comment by cloutierMat** [comment]
Thank you for reporting the issue. I can confirm that currently the `connectionId` field is not populated.

I will be working on a fix shortly.

**Comment by cloutierMat** [comment]
Hi @chkp-roeyl and thanks again for your report,

I have just pushed a fix and it will be available in the next `latest` Pro release. Websocket's AWS integration should have a fully populated context.

Could you please run `docker pull localstack/localstack-pro:latest` and see if that would solve your issue? Thank you!

**Comment by chkp-roeyl** [comment]
Hi @cloutierMat , thanks for the update.
LocalStack is installed on my mac with version 3.8.1
When the release is scheduled to and what will be the version?

**Comment by cloutierMat** [comment]
Awesome @chkp-roeyl, I am glad to hear!

You can use `localstack/localstack-pro:latest`. It is our dev build containing all of the latest patches. Our next release will come towards the end of the month, so in the meantime I suggest using the `latest` tag.

I will close the issue for now, but feel free to reach out with any further questions you might have.
