### ISSUE TITLE
bug: Incorrect ZoneId is returned by LocalStack different from AWS ZoneId

### ISSUE THREAD

**Issue by arunsriniv** [localstack/localstack#11813]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

While describing the Availability Zones of AWS Regions, the ZoneId is returned incorrectly or messed up between Zone Name. It is different from AWS ZoneIds for the corresponding Zone Name. For example, in us-west-2, for ZoneName "us-west-2a", the expected ZoneId is "usw2-az1". But in LocalStack, the ZoneId is returned as "usw2-az2". Please refer below

AWS:
sudo aws ec2 describe-availability-zones --region us-west-2
{
    "AvailabilityZones": [
        {
            "State": "available",
            "OptInStatus": "opt-in-not-required",
            "Messages": [],
            "RegionName": "us-west-2",
            **"ZoneName": "us-west-2a",
            "ZoneId": "usw2-az1",**
            "GroupName": "us-west-2",
            "NetworkBorderGroup": "us-west-2",
            "ZoneType": "availability-zone"
        },
        {
            "State": "available",
            "OptInStatus": "opt-in-not-required",
            "Messages": [],
            "RegionName": "us-west-2",
            "ZoneName": "us-west-2b",
            "ZoneId": "usw2-az2",
            "GroupName": "us-west-2",
            "NetworkBorderGroup": "us-west-2",
            "ZoneType": "availability-zone"
        },
        {
            "State": "available",
            "OptInStatus": "opt-in-not-required",
            "Messages": [],
            "RegionName": "us-west-2",
            "ZoneName": "us-west-2c",
            "ZoneId": "usw2-az3",
            "GroupName": "us-west-2",
            "NetworkBorderGroup": "us-west-2",
            "ZoneType": "availability-zone"
        },
        {
            "State": "available",
            "OptInStatus": "opt-in-not-required",
            "Messages": [],
            "RegionName": "us-west-2",
            "ZoneName": "us-west-2d",
            "ZoneId": "usw2-az4",
            "GroupName": "us-west-2",
            "NetworkBorderGroup": "us-west-2",
            "ZoneType": "availability-zone"
        }
    ]
}

LocalStack:

# awslocal ec2 describe-availability-zones --region us-west-2
{
    "AvailabilityZones": [
        {
            "State": "available",
            "Messages": [],
            "RegionName": "us-west-2",
            **"ZoneName": "us-west-2a",
            "ZoneId": "usw2-az2",**
            "ZoneType": "availability-zone"
        },
        {
            "State": "available",
            "Messages": [],
            "RegionName": "us-west-2",
            "ZoneName": "us-west-2b",
            "ZoneId": "usw2-az1",
            "ZoneType": "availability-zone"
        },
        {
            "State": "available",
            "Messages": [],
            "RegionName": "us-west-2",
            "ZoneName": "us-west-2c",
            "ZoneId": "usw2-az3",
            "ZoneType": "availability-zone"
        },
        {
            "State": "available",
            "Messages": [],
            "RegionName": "us-west-2",
            "ZoneName": "us-west-2d",
            "ZoneId": "usw2-az4",
            "ZoneType": "availability-zone"
        }
    ]
}

### Expected Behavior

ZoneId corresponding to ZoneName as per AWS.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker compose

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    # awslocal ec2 describe-availability-zones --region us-west-2

### Environment

```markdown
- OS: Ubuntu 22.04
- LocalStack:
  LocalStack version: 3.8.1
  LocalStack Docker image sha:
  LocalStack build date:
  LocalStack build git hash:
```

**Comment by simonrw** [comment]
Hi, thanks for raising this issue.

This is expected behaviour from AWS, and is [documented as such](https://docs.aws.amazon.com/ram/latest/userguide/working-with-az-ids.html). The Zone IDs are not guaranteed to be the equivalents of the Zone names. In my testing, I find quite a few occurrences where the zone id does not match up to the zone name (i.e zone `...a` does not always have index `1`).

In fact the list of AZs available in an account is not consistent across accounts. For example, in one of my accounts I have `ap-northeast-1b` but not in another.
