### ISSUE TITLE
bug: SNS to SQS subscription with RawMessageDelivery missing MessageAttributes

### ISSUE THREAD

**Issue by Dreamescaper** [localstack/localstack#11835]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When SQS is subscribed to SNS with RawMessageDelivery: true, the message received from SQS contains no MessageAttributes.

### Expected Behavior

MessageAttributes are forwarded from SNS to SQS when RawMessageDelivery enabled.

### How are you starting LocalStack?

Custom (please describe below)

### Steps To Reproduce

Here's C# code using Testcontainers to start LocalStack.

```csharp
using Amazon.Runtime;
using Amazon.SimpleNotificationService;
using Amazon.SimpleNotificationService.Model;
using Amazon.SQS;
using Testcontainers.LocalStack;

// Setup LocalStack
await using var localStack = new LocalStackBuilder()
    .WithImage("localstack/localstack:3.8.1")
    .Build();

await localStack.StartAsync();

var credentials = new BasicAWSCredentials("my-test-key", "my-test-secret-key");
var sqsClient = new AmazonSQSClient(credentials, new AmazonSQSConfig { ServiceURL = localStack.GetConnectionString() });
var snsClient = new AmazonSimpleNotificationServiceClient(credentials, new AmazonSimpleNotificationServiceConfig { ServiceURL = localStack.GetConnectionString() });

// Create Queue and Topic
var topicArn = (await snsClient.CreateTopicAsync("events-topic")).TopicArn;
var queue = await sqsClient.CreateQueueAsync("events-queue");
var queueArn = (await sqsClient.GetQueueAttributesAsync(queue.QueueUrl, ["QueueArn"])).QueueARN;

// Subscribe Queue to Topic
await snsClient.SubscribeAsync(new SubscribeRequest
{
    TopicArn = topicArn,
    Endpoint = queueArn,
    Attributes = new() { ["RawMessageDelivery"] = "true" },
    Protocol = "sqs"
});

// Publish and Receive message
await snsClient.PublishAsync(new PublishRequest
{
    TopicArn = topicArn,
    Message = """{"message": "Message with attributes."}""",
    MessageAttributes = new Dictionary<string, MessageAttributeValue>
    {
        ["TestAttribute"] = new MessageAttributeValue { StringValue = "TestValue", DataType = "String" }
    }
});

await Task.Delay(100);

var message = (await sqsClient.ReceiveMessageAsync(queue.QueueUrl)).Messages.Single();

Console.WriteLine(message.Body); // {"message": "Message with attributes."}
Console.WriteLine(message.MessageAttributes.Count); // 0
```

### Environment

```markdown
- OS: Windows 11
- LocalStack:
  LocalStack version: 3.8.1
```

### Anything else?

I can see that this issue is mentioned multiple times:
https://github.com/localstack/localstack/issues/5395#issuecomment-1072644441
https://github.com/localstack/localstack/issues/131#issuecomment-365627073
https://github.com/localstack/localstack/issues/4086

Still, wasn't able to find any oped issue.

**Comment by bentsku** [comment]
Hello @Dreamescaper and thanks for your report.

Could you confirm this code works against AWS? From what I can see from our test suite, when using `RawMessageDelivery`, the SNS message attributes are sent as SQS Message attributes.

Meaning you will need to specify to the SQS request that you want to receive the message attributes: 

See https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/SQS/MSQSReceiveMessageAsyncReceiveMessageRequestCancellationToken.html and https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/SQS/TReceiveMessageRequest.html

You need to specify the `AttributeNames` parameter in order for SQS to return the `MessageSystemAttributeNames` field to you, as specified by the documentation: https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_ReceiveMessage.html#API_ReceiveMessage_RequestSyntax

By default, AWS won't sent any `MessageAttributes`. You can set that value to `All` to receive all of them. 

Could you please confirm that fixes your issue? Thanks!

**Comment by Dreamescaper** [comment]
:facepalm:

You're absolutely right, sorry for the confusion, my bad.
I've checked in AWS Console, therefore missed that i need to update request.
