### ISSUE TITLE
SSM parameters created via different interfaces is not shared

### ISSUE THREAD

**Issue by bethesque** [localstack/localstack#1184]
Firstly, thank you to everyone who has contributed to localstack. It is an incredibly useful thing to have, and I really appreciate it.

*Problem description:*

When accessing the mock SSM store via different interfaces (eg from host or from another docker container in a docker-compose stack) the data does not appear to be shared. Eg.

```
awslocal ssm put-parameter --name "foo" --type String --value "bar" --overwrite
awslocal ssm get-parameter --name "foo"
```

If you run those two statements on the same host (eg both on a 'seed' container, or both on the docker host) it works. If you execute one on the 'seed' container, and one on the host, they can't see each other's data.

*Steps to recreate:*

Please see https://github.com/bethesque/localstack-interface-issue

*Expected behaviour:*

When an SSM parameter is set from within another docker container, it should be able to be retrieved from the host machine.

*Actual behaviour:*

When an SSM parameter is set from within another docker container, it is not able to be retrieved from the host machine - the value is not set.

**Comment by watchdogtimer** [comment]
I'm also observing this issue with a similar setup, why would this be the issue? Does the localstack instance now "own" the data? Does it partition it by client origin?

**Comment by watchdogtimer** [comment]
@bethesque - this was an AWS Region config issue for me. The client that is putting the parameter to the store needs to be configured with the same region as the client that is getting the parameter. HTH

**Comment by whummer** [comment]
Thanks for reporting @bethesque , and thanks for providing a solution @watchdogtimer . This indeed looks like a region mismatch issue. Please ensure that regions are consistent across clients. Please report here if the problem persists. Thanks!
