### ISSUE TITLE
bug: localstack cdk bootstrap failing with localstack pro on mac

### ISSUE THREAD

**Issue by kriscoleman** [localstack/localstack#11866]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After starting a localstack pro default container, running `cdklocal bootstrap` with account 000000000000 results in an error. 

```sh
Account: 000000000000
 ⏳  Bootstrapping environment aws://000000000000/us-east-1...
 ❌  Environment aws://000000000000/us-east-1 failed bootstrapping: InvalidClientTokenId: The security token included in the request is invalid.
    at throwDefaultError (/Users/kriscoleman-testifysec/.nvm/versions/node/v20.18.0/lib/node_modules/aws-cdk/lib/index.js:459:129499)
    at /Users/kriscoleman-testifysec/.nvm/versions/node/v20.18.0/lib/node_modules/aws-cdk/lib/index.js:459:129834
    at de_CommandError (/Users/kriscoleman-testifysec/.nvm/versions/node/v20.18.0/lib/node_modules/aws-cdk/lib/index.js:480:40628)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/kriscoleman-testifysec/.nvm/versions/node/v20.18.0/lib/node_modules/aws-cdk/lib/index.js:453:667957
    at async /Users/kriscoleman-testifysec/.nvm/versions/node/v20.18.0/lib/node_modules/aws-cdk/lib/index.js:453:671416
    at async /Users/kriscoleman-testifysec/.nvm/versions/node/v20.18.0/lib/node_modules/aws-cdk/lib/index.js:459:149517
    at async /Users/kriscoleman-testifysec/.nvm/versions/node/v20.18.0/lib/node_modules/aws-cdk/lib/index.js:453:622449
    at async SDK.validateCredentials (/Users/kriscoleman-testifysec/.nvm/versions/node/v20.18.0/lib/node_modules/aws-cdk/lib/index.js:593:5528803)
    at async SdkProvider.forEnvironment (/Users/kriscoleman-testifysec/.nvm/versions/node/v20.18.0/lib/node_modules/aws-cdk/lib/index.js:593:5639569) {
  '$fault': 'client',
  '$metadata': [Object],
  Type: 'Sender',
  Code: 'InvalidClientTokenId'
}
The security token included in the request is invalid.
```

Things I have tried: 
1. confirming localstack is running
2. clearing aws/cdk caches
3. restarting
4. setting env vars like `LOCALSTACK_HOSTNAME=localhost` 
5. running with `-v` for verbose logs and looking for more info

### Expected Behavior

Bootstrap works without an invalid token error.

### How are you starting LocalStack?

Custom (please describe below)

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    localstack desktop

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    cdklocal bootstrap

### Environment

```markdown
- OS: mac
- LocalStack:
!LocalStack version: 3.8.2.dev122
"LocalStack build date: 2024-11-18
$LocalStack build git hash: fb9d2348
```

**Comment by kriscoleman** [comment]
reporting back... after some stabs in the dark I got past this error with: 

`AWS_PROFILE=localstack cdklocal bootstrap` 

I didn't find this anywhere in the documentation or anywhere helpful... I was scanning the slack community channel for my error and saw someone mention they set this env var and tried it. 

Is this an important step for localstack to work with cdk, and I'm missing it in the documentation?

**Comment by dominikschubert** [comment]
This is caused by a changed upstream in newer `aws-cdk` releases. See https://github.com/localstack/localstack/issues/11866 fore more information. We're investigating and working on a fix, but for now you can simply pin the version to `2.166.0` to avoid this issue.

**Comment by dominikschubert** [comment]
Please follow https://github.com/localstack/aws-cdk-local/issues/95 for updates on this issue.
