### ISSUE TITLE
feature request: lambda nodejs22.x runtime support

### ISSUE THREAD

**Issue by sam-extern-porsche** [localstack/localstack#11901]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Localstack should support the `nodejs22.x` AWS lambda runtime since it is now officially supported on the AWS side: [Lambda runtimes](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html#runtimes-supported)

### Anything else?

Trying to create a lambda with the `nodejs22.x` runtime results in the following error:

```
An error occurred (InvalidParameterValueException) when calling the CreateFunction operation: Value nodejs22.x at 'runtime' failed to satisfy constraint: Member must satisfy enum value set: [nodejs20.x, provided.al2023, python3.12, java17, provided, nodejs16.x, nodejs14.x, ruby2.7, python3.10, java11, python3.11, dotnet6, go1.x, java21, nodejs18.x, provided.al2, java8, java8.al2, ruby3.2, python3.7, python3.8, python3.9] or be a valid ARN
```

**Comment by joe4dev** [comment]
Thank you for raising this feature request @sam-extern-porsche 
We were waiting for the official AWS images and will ship the Node.js 22 Lambda runtime in the coming days. Stay tuned 🙌
