### ISSUE TITLE
bug: Cognito User Pool DeletionProtection property is ineffective

### ISSUE THREAD

**Issue by NateDimick** [localstack/localstack#11947]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

user pools with `DeletionProtection: ACTIVE` can be deleted

### Expected Behavior

The DeleteUserPool api should respond with an InvalidParameterException
```sh
$ aws cognito-idp delete-user-pool --user-pool-id us-east-1_5LTQ30K1O

An error occurred (InvalidParameterException) when calling the DeleteUserPool operation: The user pool cannot be deleted because deletion protection is activated. Deletion protection must be inactivated first.
```

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack-pro

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal cognito-idp create-user-pool --pool-name <any_value> --deletion-protection ACTIVE
    awslocal cognito-idp delete-user-pool --user-pool-id <generated_pool_id>

### Environment

```markdown
- OS: Ubuntu 20.04
- LocalStack:
  LocalStack version: 3.8.1
  LocalStack Docker image sha: sha256:e9daf0a54d8c1b8f9b5d3ae80983f00e2a60c31032b6c7d5a6c776638259e712
  LocalStack build date: 2024-10-8
  LocalStack build git hash: 307c4c26
```

**Comment by giograno** [comment]
Hi @NateDimick, thanks for reporting the issue. We shipped a fix in the `latest` Docker image. Please let us know if you have any other issues 🙏
