### ISSUE TITLE
Migrate to Open Distro for Elasticsearch

### ISSUE THREAD

**Issue by dmnlk** [localstack/localstack#1195]
AWS has published "Open Distro for Elasticsearch" recently.
https://aws.amazon.com/jp/blogs/aws/new-open-distro-for-elasticsearch/

I think localstack should use this ES, instead of normal ES for Elasticsearch service compatibility.
I'll try migrate to this.

**Comment by whummer** [comment]
Great find. Thanks @dmnlk , that would be awesome. Let me/us know if you need any help with the implementation.

**Comment by whummer** [comment]
Hi @dmnlk , quick follow-up. Were you able to make some progress with this migration. Would be great if you could push a PR, even if it is still a work-in-progress. Thanks!

**Comment by dmnlk** [comment]
Sorry,i will try it..!

**Comment by dmnlk** [comment]
I have tested this es in my branch.
but this is not compatible localstack(failed some test)...
I'll try later.
