### ISSUE TITLE
bug: Step Functions $$.StateMachine.Name and $$.State.Name are not supported

### ISSUE THREAD

**Issue by peter-smith-phd** [localstack/localstack#11950]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The following state machine fails to parse correctly:

```
{
  "StartAt": "fail",
  "States": {
    "fail": {
      "Type": "Fail",
      "ErrorPath": "$$.State.Name",
      "CausePath": "$$.StateMachine.Name"
    }
  }
}
```

The incorrect output is:
```
An error occurred (InvalidDefinition) when calling the CreateStateMachine operation: ASLParserException ['line 6:19, at "$$.State.Name", no viable alternative at input \'"ErrorPath":"$$.State.Name"\'', 'line 7:19, at "$$.StateMachine.Name", no viable alternative at input \'"CausePath":"$$.StateMachine.Name"\'']
```

### Expected Behavior

The ASL should parse correctly, and the state machine should return the state's name, and the state machine's name.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker-compose up

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

   awslocal stepfunctions create-state-machine --name "Fail_errors" --definition file://file.asl.json --role-arn arn:aws:iam::000000000000:role/Admin

### Environment

```markdown
- OS: Amazon Linux
- LocalStack:
  LocalStack version: 4.0.3.dev22
  localstack-main | LocalStack build date: 2024-11-27
  localstack-main | LocalStack build git hash: 0e01610bb
```

**Comment by peter-smith-phd** [comment]
I also see this code being problematic:
  
  ```
  {
    "Variable?": "$$.State.EnteredTime"
    "TimestampGreaterThanPath": "$.time"
    "Next": "pass1"
  }
```

**Comment by MEPalma** [comment]
Hello @peter-smith-phd, thank you once again for the very report. I believe this issue should be resolved from the next latest version of localstack. Would you mind verifying this scenario works as expected? Thank you!

**Comment by peter-smith-phd** [comment]
Thank you. I've confirmed that `$$.State.Name`, `$$.StateMachine.Name` and `$$.State.EnteredTime` are all supported now.

**Comment by MEPalma** [comment]
Thank you! I will close this issue. However, I’ve noticed some untested parity regarding which string expressions can be bound to each production. We will soon begin work to validate all these bindings.
