### ISSUE TITLE
bug: cant load @aws-lambda-powertools/logger in lambda

### ISSUE THREAD

**Issue by soralis0912** [localstack/localstack#11965]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

in deploy TypeScript-Lambda function

function build AWS SAM

SAM 

Build Failed
Error: NodejsNpmEsbuildBuilder:EsbuildBundle - Esbuild Failed: ✘ [ERROR] Could not resolve "@aws-lambda-powertools/logger"

    src/Test.ts:2:23:
      2 │ import { Logger } from '@aws-lambda-powertools/logger';
        ╵                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@aws-lambda-powertools/logger" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle.

@aws-lambda-powertools/logger is installed by npm

but cant build this function

so , im add external to exclude

but error in lambda
```
	"errorType": "Runtime.ImportModuleError",
	"errorMessage": "Error: Cannot find module '@aws-lambda-powertools/logger'\nRequire stack:\n- /var/task/Test.js\n- /var/runtime/index.mjs",
	"trace": [
		"Runtime.ImportModuleError: Error: Cannot find module '@aws-lambda-powertools/logger'",
		"Require stack:",
		"- /var/task/Test.js",
		"- /var/runtime/index.mjs",
		"    at _loadUserApp (file:///var/runtime/index.mjs:1087:17)",
		"    at async UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1119:21)",
		"    at async start (file:///var/runtime/index.mjs:1282:23)",
		"    at async file:///var/runtime/index.mjs:1288:1"
	]
```

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

deploy in AWS SAM by samlocal

### Environment

```markdown
- OS:
- LocalStack:
  LocalStack version: 3.8.2.dev32
  LocalStack build date: 2024-10-17
  LocalStack build git hash: 1bc0db543
```

**Comment by joe4dev** [comment]
Hi @soralis0912 👋 

The error message indicates that it's a Typescript-specific building issue. Does the same Lambda function deploy against real AWS?

The AWS PowerTools documentation could maybe help:
* documentation: https://github.com/aws-powertools/powertools-lambda-typescript?tab=readme-ov-file#install
* sample: https://github.com/aws-samples/serverless-typescript-demo

Please note that [Lambda Layers (Pro)](https://docs.localstack.cloud/user-guide/aws/lambda/#lambda-layers-pro) are a Pro feature in LocalStack.

**Comment by soralis0912** [comment]
@joe4dev yes its work in AWS lambda

testing now

https://github.com/soralis0912/lambda-sample

https://github.com/soralis0912/localstack-docker

this repos 

in AWS lambda is not required 

"@aws-sdk/*" packages

i guess "@aws-lambda-powertools/*" package same

**Comment by joe4dev** [comment]
> @joe4dev yes its work in AWS lambda
> 
> testing now
> 
> https://github.com/soralis0912/lambda-sample
> 
> https://github.com/soralis0912/localstack-docker
> 
> this repos
> 
> in AWS lambda is not required
> 
> "@aws-sdk/*" packages
> 
> i guess "@aws-lambda-powertools/*" package same

@soralis0912 I can reproduce this behavior on LocalStack, but also on AWS:

<img width="1233" alt="Screenshot 2024-12-06 at 18 01 53" src="https://github.com/user-attachments/assets/c3bab519-9fa8-432f-b474-6d9b8b8cb2e2">

Adding the PowerTools layer fixes the issue on AWS and LocalStack, as demonstrated with this patch: https://github.com/soralis0912/lambda-sample/pull/1

What are the exact steps you are using for the deployment?
