### ISSUE TITLE
DynamoDB point_in_time_recovery "support"

### ISSUE THREAD

**Issue by jrduncans** [localstack/localstack#1197]
I have terraform to create dynamo tables that set point_in_time_recovery enabled to true. Dynamo in localstack errors on trying to set that. Support for accepting and ignoring that setting so that I can use production terraform against local-stack would be very helpful.

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-90) by [Unito](https://www.unito.io/learn-more)

**Comment by usmangani1** [comment]
@jrduncans 
Thanks for reporting this issue.
Can you please help with the sample command or the script using which you are trying to create the dynamodb table with point_in_time_recovery which is resulting in the issue? 
This will help us reproduce and resolve the issue a bit faster.

**Comment by jrduncans** [comment]
We were doing this with terraform, with a setting of:

  point_in_time_recovery {
    enabled = true
  }

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dynamodb_table#point_in_time_recovery

I don't know exactly how Terraform in turns executes that (I _think_ this is the code: https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_dynamodb_table.go )

**Comment by usmangani1** [comment]
@jrduncans 

Can you please help us with the whole terraform file using which I can see the error ?.
Can you attach the error which you are seeing also ?

In the boto documentation I don't see support for any such parameter.
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/dynamodb.html#DynamoDB.Client.create_table

**Comment by claudobahn** [comment]
@usmangani1 I'm guessing this is the boto3 documentation for this functionality: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/dynamodb.html#DynamoDB.Client.update_continuous_backups

**Comment by usmangani1** [comment]
@claudobahn 
This issue for @jrduncans seems like setting this **point_in_time_recovery**  at the time of the table creation which is not something I dont see in boto documentation.After the table is created we can use the functionality of update_continous_backups.

@jrduncans  can you please help us here with the terraform script which is being used and the error trace which you are seeing ?

**Comment by benkeil** [comment]
Could be a first solution just to "mock" it, so that terraform can apply everything?

**Comment by Sohel-Ahmed** [comment]
I'm seeing that same issue, here is the terraform script:

`
provider "aws" {
  region                      = "us-east-1"
  s3_force_path_style         = true
  skip_credentials_validation = true
  skip_metadata_api_check     = true
  skip_requesting_account_id  = true

  endpoints {
    apigateway     = "http://localhost:4566"
    cloudformation = "http://localhost:4566"
    cloudwatch     = "http://localhost:4566"
    dynamodb       = "http://localhost:4566"
    es             = "http://localhost:4566"
    firehose       = "http://localhost:4566"
    iam            = "http://localhost:4566"
    kinesis        = "http://localhost:4566"
    lambda         = "http://localhost:4566"
    route53        = "http://localhost:4566"
    redshift       = "http://localhost:4566"
    s3             = "http://localhost:4566"
    secretsmanager = "http://localhost:4566"
    ses            = "http://localhost:4566"
    sns            = "http://localhost:4566"
    sqs            = "http://localhost:4566"
    ssm            = "http://localhost:4566"
    stepfunctions  = "http://localhost:4566"
    sts            = "http://localhost:4566"
    ec2            = "http://localhost:4566"
  }
}


terraform {
  # This module is now only being tested with Terraform 0.13.x. However, to make upgrading easier, we are setting
  # 0.12.26 as the minimum version, as that version added support for required_providers with source URLs, making it
  # forwards compatible with 0.13.x code.
  required_version = ">= 0.12.26"
}

# ---------------------------------------------------------------------------------------------------------------------
# CREATE THE DYNAMODB TABLE
# ---------------------------------------------------------------------------------------------------------------------

resource "aws_dynamodb_table" "example" {
  name         = "dynamodb-example"
  hash_key     = "userId"
  range_key    = "department"
  billing_mode = "PAY_PER_REQUEST"

  server_side_encryption {
    enabled = true
  }
  point_in_time_recovery {
    enabled = true
  }

  attribute {
    name = "userId"
    type = "S"
  }
  attribute {
    name = "department"
    type = "S"
  }

  ttl {
    enabled        = true
    attribute_name = "expires"
  }

  tags = {
    Environment = "production"
  }
}
`

Once you start the run the above script, you see the below error:
` Error: error enabling DynamoDB Table (dynamodb-example) point in time recovery: error updating DynamoDB PITR status: UnknownOperationException: An unknown operation was requested.`

and if you comment out the `ttl` block, it works fine.

**Comment by davecardwell** [comment]
This issue persists so I opened #7569 if you’d like to 👍 and subscribe to updates.
