### ISSUE TITLE
Localstack taking too long to become ready

### ISSUE THREAD

**Issue by aman-agrawal-coolblue** [localstack/localstack#1202]
Hi Guys,

I and my colleagues have been having this problem for a couple of days now, Localstack is taking too long to become ready (we are using the latest version on Windows 10 and running using Linux containers):

![image](https://user-images.githubusercontent.com/37109136/54530051-fa45d480-4981-11e9-93ab-1f5569f4ae4c.png)

After a while of waiting thus, this error shows up (to do with Elasticsearch service not being available):

![image](https://user-images.githubusercontent.com/37109136/54530247-91129100-4982-11e9-9eb8-06d037f24f46.png)

And sometimes, its S3 service that goes into a tizzy:

![image](https://user-images.githubusercontent.com/37109136/54530492-2f065b80-4983-11e9-899d-7750a63f1b13.png)

And after a little while longer, the whole thing just goes into a retry loop. I have tried all the usual rigour, restarting the Docker for Windows app, redownloading the image, rebooting the computer etc with no success.

This problem never happened in the previous version, it used to be all up and running fairly quickly. Is this something you guys are already aware of or can offer any ideas on?

Cheers
Aman

**Comment by mjonescb** [comment]
Confirm that this behavior isn't seen in 0.9.0.

**Comment by icekev** [comment]
I confirm I have been trying all the possible ways to get this up and running (In WLS), using the docker-compose, using --docker option to start, or simply by running it with python, and I am getting exactly the same behavior as mentioned by @aman-agrawal-coolblue 

Any idea ? 
It really seems to be boiling down to Elasticsearch and S3 for me as well...

![image](https://user-images.githubusercontent.com/5543043/54554490-ed79ae80-498a-11e9-8f57-c1c57a92c876.png)

**Comment by icekev** [comment]
Further investigations showed me that any type of service that require usage of a file system on windows just never launch (S3, ES...).

**Comment by aman-agrawal-coolblue** [comment]
I think there is a way to select the services that you want to start. I know this is not a fix but a workaround to get one going. It will be nice if someone from the Localstack could comment on this.

**Comment by shenie** [comment]
See `SERVICES` in https://github.com/localstack/localstack#configurations

**Comment by whummer** [comment]
> Further investigations showed me that any type of service that require usage of a file system on windows just never launch (S3, ES...).

Interesting..
@icekev @aman-agrawal-coolblue @mjonescb Can you try running with `DEBUG=1` and post any error logs or stacktraces you're seeing?

**Comment by swdgit** [comment]
#1243 and #1220 bring up the same issue. Notes there and from myself indicate no debug messages re: s3 not starting. additionally, I back ported to a prior version and saw the same/similar issues.

**Comment by dangreaves** [comment]
I'm also experiencing this on OSX with Python 3.7.3 and `TMPDIR=/private$TMPDIR localstack start --docker` to boot.

**Comment by aman-agrawal-coolblue** [comment]
For now, I have taken the approach suggested above of running only non-S3 services so its been a while since I ran all localstack services but I can see from the reports above that the problem persists.

For people who have used localstack for a while and know how to get around this issue (for e.g. by running only the services they need), its not the end of the world but someone just starting out with it will just want to run the whole thing and they will end up frustrated. Therefore I believe this issue deserves a proper resolution.

**Comment by austinbutler** [comment]
For me it works with version 0.9.0, not 0.9.1 or latest.

**Comment by swdgit** [comment]
Hmm, I’ll need to try that rev. I went back but maybe not that specific rev.

**Comment by austinbutler** [comment]
This seems to be working now with 0.9.4.

**Comment by whummer** [comment]
Closing this issue - please reopen if the problem persists. Thanks

**Comment by pcfleischer** [comment]
I was experiencing this same is and downgrading to 0.9.0 did work but I was also able to fix this by increasing my overall memory allocation to Docker.  I'm guess maybe some updates to s3 increased the footprint significantly and instead of failing it just hangs like crazy.

**Comment by justinlazaro-iselect** [comment]
Been waiting to finish like more than 1hour still `waiting for all localstack services to be ready` any thoughts? im a windows user @whummer  thanks.

![image](https://user-images.githubusercontent.com/54691710/82849867-7cd60680-9f2c-11ea-98cd-7148430da3b8.png)

**Comment by carlosdoordash** [comment]
In my case, I only had to add the following environment variables (I was using a common Helm chart that sets these higher to workaround pod initialization issues in our Kubernetes cluster)...
```
AWS_METADATA_SERVICE_TIMEOUT=1
AWS_METADATA_SERVICE_NUM_ATTEMPTS=1
```
as documented at https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html#using-environment-variables

**Comment by ktamas77** [comment]
> I was experiencing this same issue and downgrading to 0.9.0 did work but I was also able to fix this by increasing my overall memory allocation to Docker. I'm guess maybe some updates to s3 increased the footprint significantly and instead of failing it just hangs like crazy.

this is a great tip! I increased Docker's Memory allocation from 1.5gb to 4gb, and also removed the persistent Localstack volume - now it seems to be working great! Fingers crossed it will stays table: 🤞

**Comment by shashiranjan84** [comment]
Why this being closed? I still see this as a problem with version `0.12.5` on OSX if enable persistence by setting data directory
```
services:
  localstack:
    container_name: 'local_aws_stack'
    image: localstack/localstack:${LOCALSTACK_VERSION:-0.12.5}
    network_mode: bridge
    stdin_open: false
    tty: true
    ports:
      - '4566:4566'
      - '4571:4571'
    environment:
      - SERVICES=cloudformation,s3,dynamodb,sqs,iam
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
      - DATA_DIR=/tmp/localstack/data
      - DEFAULT_REGION=eu-west-1
    volumes:
      - ./data:/tmp/localstack
      - '/var/run/docker.sock:/var/run/docker.sock'
    ```

```
➜  main git:(branch/localstack-tests) ✗ TMPDIR=/private$TMPDIR docker-compose -f localstack-compose.yml up                
WARNING: Native build is an experimental feature and could change at any time
Creating local_aws_stack ... done
Attaching to local_aws_stack
local_aws_stack | Waiting for all LocalStack services to be ready
local_aws_stack | 2021-01-25 19:26:02,455 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
local_aws_stack | 2021-01-25 19:26:02,457 INFO supervisord started with pid 14
local_aws_stack | 2021-01-25 19:26:03,461 INFO spawned: 'dashboard' with pid 20
local_aws_stack | 2021-01-25 19:26:03,462 INFO spawned: 'infra' with pid 21
local_aws_stack | 2021-01-25 19:26:03,465 INFO success: dashboard entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
local_aws_stack | 2021-01-25 19:26:03,466 INFO exited: dashboard (exit status 0; expected)
local_aws_stack | (. .venv/bin/activate; exec bin/localstack start --host)
local_aws_stack | Starting local dev environment. CTRL-C to quit.
local_aws_stack | LocalStack version: 0.12.4
local_aws_stack | 2021-01-25 19:26:05,060 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
local_aws_stack | 2021-01-25T19:26:06:DEBUG:bootstrap.py: Loading plugins - scope "services", module "localstack": <function register_localstack_plugins at 0x7fafd2ef7550>
local_aws_stack | Starting edge router (https port 4566)...
local_aws_stack | Starting mock CloudFormation service on http port 4566 ...
local_aws_stack | Starting mock DynamoDB service on http port 4566 ...
local_aws_stack | Starting mock DynamoDB Streams service on http port 4566 ...
local_aws_stack | Starting mock IAM service on http port 4566 ...
local_aws_stack | Initializing DynamoDB Local with the following configuration:
local_aws_stack | Port: 45099
local_aws_stack | InMemory:     false
local_aws_stack | DbPath:       /tmp/localstack/data/dynamodb
local_aws_stack | SharedDb:     true
local_aws_stack | shouldDelayTransientStatuses: false
local_aws_stack | CorsParams:   *
local_aws_stack | 
local_aws_stack | [2021-01-25 19:26:07 +0000] [22] [INFO] Running on https://0.0.0.0:4566 (CTRL + C to quit)
local_aws_stack | 2021-01-25T19:26:07:INFO:hypercorn.error: Running on https://0.0.0.0:4566 (CTRL + C to quit)
local_aws_stack | 2021-01-25T19:26:07:INFO:localstack.multiserver: Starting multi API server process on port 39773
local_aws_stack | [2021-01-25 19:26:07 +0000] [22] [INFO] Running on http://0.0.0.0:39773 (CTRL + C to quit)
local_aws_stack | 2021-01-25T19:26:07:INFO:hypercorn.error: Running on http://0.0.0.0:39773 (CTRL + C to quit)
local_aws_stack | Waiting for all LocalStack services to be ready
local_aws_stack | Starting mock Kinesis service on http port 4566 ...
local_aws_stack | Starting mock S3 service on http port 4566 ...
local_aws_stack | Starting mock SQS service on http port 4566 ...
local_aws_stack | Listening at http://:::59947
local_aws_stack | Waiting for all LocalStack services to be ready
local_aws_stack | Waiting for all LocalStack services to be ready
local_aws_stack | Waiting for all LocalStack services to be ready
local_aws_stack | Waiting for all LocalStack services to be ready
local_aws_stack | Waiting for all LocalStack services to be ready
local_aws_stack | Waiting for all LocalStack services to be ready
local_aws_stack | Waiting for all LocalStack services to be ready
local_aws_stack | Waiting for all LocalStack services to be ready
local_aws_stack | Waiting for all LocalStack services to be ready
local_aws_stack | Waiting for all LocalStack services to be ready
local_aws_stack | Waiting for all LocalStack services to be ready
local_aws_stack | Waiting for all LocalStack services to be ready
local_aws_stack | Waiting for all LocalStack services to be ready
local_aws_stack | Waiting for all LocalStack services to be ready
local_aws_stack | Waiting for all LocalStack services to be ready
local_aws_stack | Waiting for all LocalStack services to be ready
local_aws_stack | Waiting for all LocalStack services to be ready
local_aws_stack | Waiting for all LocalStack services to be ready
local_aws_stack | Waiting for all LocalStack services to be ready
local_aws_stack | Waiting for all LocalStack services to be ready
local_aws_stack | Waiting for all LocalStack services to be ready
local_aws_stack | Waiting for all LocalStack services to be ready
local_aws_stack | Waiting for all LocalStack services to be ready
local_aws_stack | Waiting for all LocalStack services to be ready
local_aws_stack | Waiting for all LocalStack services to be ready
local_aws_stack | Waiting for all LocalStack services to be ready
local_aws_stack | Waiting for all LocalStack services to be ready
local_aws_stack | Waiting for all LocalStack services to be ready
local_aws_stack | Waiting for all LocalStack services to be ready
local_aws_stack | Waiting for all LocalStack services to be ready
local_aws_stack | Waiting for all LocalStack services to be ready
local_aws_stack | Waiting for all LocalStack services to be ready
local_aws_stack | Waiting for all LocalStack services to be ready
local_aws_stack | Waiting for all LocalStack services to be ready
local_aws_stack | Waiting for all LocalStack services to be ready
local_aws_stack | Waiting for all LocalStack services to be ready
local_aws_stack | Waiting for all LocalStack services to be ready
local_aws_stack | Waiting for all LocalStack services to be ready
local_aws_stack | Waiting for all LocalStack services to be ready
local_aws_stack | Waiting for all LocalStack services to be ready
local_aws_stack | Waiting for all LocalStack services to be ready
local_aws_stack | Waiting for all LocalStack services to be ready
local_aws_stack | Waiting for all LocalStack services to be ready
local_aws_stack | Waiting for all LocalStack services to be ready
local_aws_stack | Waiting for all LocalStack services to be ready
local_aws_stack | Waiting for all LocalStack services to be ready
local_aws_stack | Waiting for all LocalStack services to be ready
local_aws_stack | Waiting for all LocalStack services to be ready
local_aws_stack | Waiting for all LocalStack services to be ready
local_aws_stack | Waiting for all LocalStack services to be ready
local_aws_stack | Waiting for all LocalStack services to be ready
local_aws_stack | Waiting for all LocalStack services to be ready
local_aws_stack | Waiting for all LocalStack services to be ready
local_aws_stack | Waiting for all LocalStack services to be ready
local_aws_stack | Waiting for all LocalStack services to be ready
local_aws_stack | Waiting for all LocalStack services to be ready
local_aws_stack | Waiting for all LocalStack services to be ready
local_aws_stack | Waiting for all LocalStack services to be ready
local_aws_stack | Waiting for all LocalStack services to be ready
local_aws_stack | Waiting for all LocalStack services to be ready
local_aws_stack | Waiting for all LocalStack services to be ready
local_aws_stack | Waiting for all LocalStack services to be ready
local_aws_stack | Waiting for all LocalStack services to be ready
local_aws_stack | Waiting for all LocalStack services to be ready
local_aws_stack | Waiting for all LocalStack services to be ready
local_aws_stack | Waiting for all LocalStack services to be ready
local_aws_stack | Waiting for all LocalStack services to be ready
local_aws_stack | Waiting for all LocalStack services to be ready
local_aws_stack | Waiting for all LocalStack services to be ready
local_aws_stack | Waiting for all LocalStack services to be ready
local_aws_stack | Waiting for all LocalStack services to be ready
local_aws_stack | Waiting for all LocalStack services to be ready
local_aws_stack | Waiting for all LocalStack services to be ready
local_aws_stack | Waiting for all LocalStack services to be ready
local_aws_stack | Waiting for all LocalStack services to be ready
local_aws_stack | Waiting for all LocalStack services to be ready
local_aws_stack | Waiting for all LocalStack services to be ready
local_aws_stack | Waiting for all LocalStack services to be ready
local_aws_stack | Waiting for all LocalStack services to be ready
local_aws_stack | Waiting for all LocalStack services to be ready
^CGracefully stopping... (press Ctrl+C again to force)
Stopping local_aws_stack ... done
```

**Comment by ktamas77** [comment]
> > I was experiencing this same issue and downgrading to 0.9.0 did work but I was also able to fix this by increasing my overall memory allocation to Docker. I'm guess maybe some updates to s3 increased the footprint significantly and instead of failing it just hangs like crazy.
> 
> this is a great tip! I increased Docker's Memory allocation from 1.5gb to 4gb, and also removed the persistent Localstack volume - now it seems to be working great! Fingers crossed it will stays table: 🤞

update: unfortunately changing the memory didn't fix the problem permanently either :(

**Comment by ktamas77** [comment]
sometimes it starts, but this is how long it takes:

<img width="646" alt="Screen Shot 2021-01-26 at 2 20 56 PM" src="https://user-images.githubusercontent.com/1231708/105913519-cefe8880-5fe1-11eb-8b50-ffc880939b45.png">

**Comment by ktamas77** [comment]
My theory is that every time a persistent volume is being restored, the existing API calls are being read from the `/tmp/data/recorded_api_calls.json` file stored in the locastack container's volume.

for some reason, in my setup, in almost every second this line is being logged to this file:

```
{"a": "sqs", "m": "POST", "p": "/000000000000/dev-copy-idea", "d": "QWN0aW9uPVJlY2VpdmVNZXNzYWdlJlZlcnNpb249MjAxMi0xMS0wNSZRdWV1ZVVybD1odHRwJTNBJTJGJTJGbG9jYWxzdGFjayUzQTQ1NjYlMkYwMDAwMDAwMDAwMDAlMkZkZXYtY29weS1pZGVhJkF0dHJpYnV0ZU5hbWUuMT1BcHByb3hpbWF0ZVJlY2VpdmVDb3VudCZBdHRyaWJ1dGVOYW1lLjI9QVdTVHJhY2VIZWFkZXI=", "h": {"Remote-Addr": "172.21.0.13", "Host": "localstack:4566", "Content-Type": "application/x-www-form-urlencoded", "Aws-Sdk-Invocation-Id": "5ac06a6a70a6518b4208392706b3c304", "Aws-Sdk-Retry": "0/0", "X-Amz-Date": "20210126T222738Z", "Authorization": "AWS4-HMAC-SHA256 Credential=key/20210126/us-east-1/sqs/aws4_request, SignedHeaders=host;x-amz-date, Signature=858a2e8d4d95f9ddb00d8b30ce58aea4a3731967f1c510c960a0045e66688d03", "User-Agent": "aws-sdk-php/3.115.0 GuzzleHttp/6.4.1 curl/7.67.0 PHP/7.3.13", "Content-Length": "182", "X-Forwarded-For": "172.21.0.13, localstack:4566, 127.0.0.1, localstack:4566", "x-localstack-edge": "https://localstack:4566", "Connection": "close"}, "rd": "PFJlY2VpdmVNZXNzYWdlUmVzcG9uc2U+PFJlY2VpdmVNZXNzYWdlUmVzdWx0PjwvUmVjZWl2ZU1lc3NhZ2VSZXN1bHQ+PFJlc3BvbnNlTWV0YWRhdGE+PFJlcXVlc3RJZD40VE4xVjgyRVlZSDNKNUhDNjNSRVZMSlgxOFpBSUVGN0RaVURCN0JMUTVXR0dMQkNTUDhXPC9SZXF1ZXN0SWQ+PC9SZXNwb25zZU1ldGFkYXRhPjwvUmVjZWl2ZU1lc3NhZ2VSZXNwb25zZT4="}
```

I guess the problem could be that so many of these lines are being logged (more than 30k in the previous post) that when the persistent container starts up the next time, loading the tens of thousands of api calls could take for a very long time. 

The question is: what are these calls, are they necessary, and if not, how can we stop them being recorded in every second?

**Comment by ktamas77** [comment]
ps. it seems to be application related. 
based on my previous post, the persistent container/volume will read the `/tmp/data/recorded_api_calls.json` file at start to restore the state. if the local environment puts too many actions to this file (30k+ for an example like in the previous cost) then the startup time will be very, very long (almost feels like forever) next time.

So possible solution would be;
1) verify your local environment to make sure you are not sending unnecessary API calls to your local stack instance (for an example one of your service is trying to connecting in every seconds, etc)
2) increase the performance of local stack itself for faster startup
3) don't log failed actions to this file which didn't take actions (like connection errors) so local stack won't need to replay those at the next startup

**Comment by tmont** [comment]
This might be due to the API replay feature, where "persistent" storage is achieved by recording all the API calls and then replaying them on service start (apparently, I remember reading that once but now I can't find any documentation about it). My local S3 service just hung for a while, pegging the CPU until it replayed 6000 API calls. Bear in mind I'm only using the S3 service (`SERVICES=s3` environment variable), but this might also apply to anything that makes use of `DATA_DIR`.

```
s3_1           | Waiting for all LocalStack services to be ready
...snip
s3_1           | Waiting for all LocalStack services to be ready
s3_1           | Ready.
s3_1           | 2021-02-10T17:41:08:INFO:localstack.utils.persistence: Restored 6238 API calls from persistent file: /tmp/localstack/data/recorded_api_calls.json
s3_1           | 2021-02-10T17:41:08:INFO:localstack.utils.analytics.profiler: Execution of "start_api_services" took 257444.2880153656ms
```

Removing the persistent storage (i.e. removing the volumes from docker) resulted in this:

```
s3_1           | Waiting for all LocalStack services to be ready
s3_1           | Waiting for all LocalStack services to be ready
s3_1           | Ready.
s3_1           | 2021-02-10T17:51:04:INFO:localstack.utils.analytics.profiler: Execution of "start_api_services" took 12788.287878036499ms
```

Would be nice if persistent storage worked a little better, but such is life.

**Comment by cmbernard333** [comment]
On MacOS, docker 3.1.0, I am seeing this issue from a different context. 

I am trying to run localstack/localstack:0.12.6 from a spring boot configuration. It is declared as a static resource and launched at test start. When I run my junit tests the first time it works successfully but any other subsequent run it is stuck.

Starts like this in AwsTestConfig (annotated with `@TestConfiguration`)
```
    public static final LocalStackContainer localStackContainer = initContainer();

    /***
     *setup a localstack to run sqs
     */
    public static LocalStackContainer initContainer() {
        LocalStackContainer localStackContainer = new LocalStackContainer(DockerImageName.parse("localstack/localstack:0.12.6"))
                .withServices(LocalStackContainer.Service.SQS);
        localStackContainer.start();
        Runtime.getRuntime().addShutdownHook(new Thread(localStackContainer::stop));
        return localStackContainer;
    }

    /***
     *This configures the AWS libs to point to the local stack instance for SQS
     */
    @Primary
    @Bean(destroyMethod = "shutdown")
    public AmazonSQSAsync amazonSQS() {
        final AwsClientBuilder.EndpointConfiguration endpoint = localStackContainer.getEndpointConfiguration(LocalStackContainer.Service.SQS);
        return new AmazonSQSBufferedAsyncClient(AmazonSQSAsyncClientBuilder
                .standard()
                .withCredentials(credentialsProvider())
                .withEndpointConfiguration(endpoint)
                .build());
    }
    ```

```
2021-02-18 16:30:09.486  INFO 19728 --- [           main] 🐳 [localstack/localstack:0.12.6]        : Creating container for image: localstack/localstack:0.12.6
```

**Comment by kappaj2** [comment]
Running Mac and seeing same behaviour.
Running Docker 3.1.0 (51484) on MacOS Big Sur (11.2.1) with Java 15.

Even tried going back to version 0.9.0 of LocalStack, still no go.
Running localstack from the docker command seems to be fine:
$ docker run localstack/localstack:0.12.5

Also running localstack using the maven during Integration tests.

`     
     private static final DockerImageName localstackImage = DockerImageName.parse("localstack/localstack:0.9.0");

     public static LocalStackContainer localStack;

     /**
      * Create the LocalStackContainer that will emulate the AWS SQS Queue. Create the queue name that will be used.
      * The LocalStackContainer reference localStack can be accessed by all the other integration tests if required
      */
     static {
          System.out.println("************* doing before all in BaseIntegrationTests *************************************");
          try {
               if (localStack == null || !localStack.isRunning()) {
                    localStack = new LocalStackContainer(localstackImage)
                            .withServices(SQS)
                            .withEnv("DEFAULT_REGION", "eu-west-1")
                            .withReuse(true);

                    localStack.start();
                    localStack.execInContainer("awslocal", "sqs", "create-queue", "--queue-name", RESPONSE_QUEUE_NAME);
                    localStack.execInContainer("awslocal", "sqs", "create-queue", "--queue-name", SMS_QUEUE_NAME);
                    localStack.getEndpointConfiguration(SQS);
               }
          } catch (Exception ex) {
               ex.printStackTrace();
          }
     }
     `
Have not been able to pinpoint why it is doing this or get a consistent reliable workaround.
Response in the console:
`
08:51:58.949 [main] INFO  docker[localstack/localstack:0.9.0] - Creating container for image: localstack/localstack:0.9.0

`

**Comment by CruncherBigData** [comment]
I am facing the same issue, any updates ?

**Comment by kappaj2** [comment]
> I am facing the same issue, any updates ?

I managed to get it running on my Mac by enabling the "Use gRPC FUSE for file sharing".
Maybe something you can check.
