### ISSUE TITLE
SQS event source does not honor delay-seconds

### ISSUE THREAD

**Issue by efritz** [localstack/localstack#1207]
**Expected**

A message published to an SQS queue will remain unavailable to consumers for the time given by the delay-seconds parameter. If that queue is an event source to a lambda function, that function should be invoked only after the delay period.

**Actual Behavior**

All messages published to a queue for which there is an event source mapping to a running lambda will invoke the lambda immediately, regardless of the delay-seconds value.

**Additional Details**

It looks like the entire SQS queue backend is short-circuited when there is a listening lambda, which will get all incoming SQS messages immediately.

https://github.com/localstack/localstack/blob/1d1b3a0ca574af85766f54d1b30d26f777c71844/localstack/services/sqs/sqs_listener.py#L47

**Comment by iamdeadman** [comment]
Hi, 
Were you able to find a fix / solution for this ? I am also having a SQS queue which queries a 3rd party rest api which enforces a rate limit so I wanted to throttle the messages I sent in the queue and limit their receive event invocations. Hence, I tried the delaytime attribute but it didn't work and the lambda's are invoked almost immediately for me too and hence getting 429 rate limit errors from the 3rd part service

**Comment by efritz** [comment]
Unfortunately adding a delay would be a new venture for localstack. It seems that the current codebase does not attempt to do some of the niceties like asynchronous (delayed) event routing, or even retrying in most cases (I could be wrong there).

My solution was to write a proxy in front of localstack that handles the delayed SQS messages (holds it in memory on a timer until the time elapses, then publishes it to localstack). It wasn't ideal, but it worked well for local development.

I no longer have access to that code, but it was fairly simple Go program (fewer than 100 lines).

**Comment by whummer** [comment]
Thanks for reporting @efritz @iamdeadman . This is definitely a use case that could/should be supported by LocalStack.

Ultimately, I think it wouldn't be too hard to implement - essentially running a `time.sleep` in a background thread (or some other form of time scheduling) before calling the `process_sqs_message` function that @efritz posted.

Do you think you could try to contribute a pull request to add this functionality? Thanks!

**Comment by efritz** [comment]
Would persistence be an issue? Anything scheduled in memory will not make it to the underlying SQS queue if the stack restarts.

**Comment by HerrSchwarz** [comment]
I am not sure, how other teams are using localstack, but from my experience it is mainly used for integration tests and persistance would not be needed for that. This is different if you include stress tests. Would be great to be able to use this feature.

**Comment by whummer** [comment]
Thanks for reporting @efritz @iamdeadman @HerrSchwarz . This should be fixed in the latest version - an integration test has been added in #2235 to cover this functionality. Please report here if the problem persists. Thanks
