### ISSUE TITLE
Unable to get sqs notification on s3 object creation

### ISSUE THREAD

**Issue by ManigandanMS** [localstack/localstack#1216]
We have been trying to setup s3 and sqs on local stack. What we are trying to do is any object uploaded to s3 sqs queue needs to be notified. Find below bunch commands used. 

```
aws --endpoint-url=http://localhost:4572 s3 mb s3://march
aws --endpoint-url=http://localhost:4576 sqs create-queue --queue-name march
aws --endpoint-url=http://localhost:4572 s3api put-bucket-notification-configuration --bucket march --notification-configuration file://notification.json
aws --endpoint-url=http://localhost:4572 s3 cp test.csv s3://march
aws --endpoint-url=http://localhost:4576 sqs receive-message --queue-url http://localhost:4576/queue/march
```
notification.json content
```
{
  "QueueConfigurations": [
    {
      "QueueArn": "http://localstack:4576/queue/march",
        "Events": [
          "s3:ObjectCreated:*"
        ]
    }
  ]
}
```

Is there anything missing in my above steps? Is this a know issue?

**Comment by rjaduthie** [comment]
Maybe this is related to #1064, where I found that Localstack is only currently able to handle the deprecated API for adding notifications.  Although I reported the issue, I haven't had time nor motivation to spend time on it.  It would require some code changes, if you're game.  A more immediate solution for you is to use the deprecated API specification, with the notifications given as an object, rather than an array in your JSON.  Not sure if the old API supported multiple notifications (which may have been the reason for the change).

**Comment by ManigandanMS** [comment]
Appreciate your help.
Could you share some sample object? I am concerned that it may still not work for multiple s3 notification!!!!

**Comment by rjaduthie** [comment]
The AWS CLI documentation for the deprecated API function is here: https://docs.aws.amazon.com/cli/latest/reference/s3api/put-bucket-notification.html

In your case, I think the JSON configuration may be something like:
```
{
  "QueueConfigurations": 
    {
      "QueueArn": "http://localstack:4576/queue/march",
        "Events": [
          "s3:ObjectCreated:*"
        ]
    }
}
```

Also, you will have to use the command:
```
aws --endpoint-url=http://localhost:4572 s3api put-bucket-notification --bucket march --notification-configuration file://deprecated-notification.json
```

It looks like you might be able to add multiple event triggers, but referencing only one queue, one lambda and one topic.  I couldn't tell you what localstack does with this configuration.

Hope this helps!  Really, to get the right behaviour from localstack #1064 needs to be addressed.

**Comment by ManigandanMS** [comment]
tried using depricated method as well, post upload I dont see notification message in sqs

**Comment by rjaduthie** [comment]
I wonder if some of your commands are silently failing.

Are you able to post the logging from localstack that you get for each of the commands you are supplying?  For example, the terminal output that you get if you start localstack in an undetached docker container.

**Comment by ManigandanMS** [comment]
Thanks for your support, really appreciate it. 

If try to upload an object to localstack s3, I am able to get sqs notification. How ever I have another issue. If I use curl command and upload a presigned url to s3 I am not getting notification.

**Comment by rjaduthie** [comment]
Logs?

**Comment by ManigandanMS** [comment]
Starting mock S3 (http port 4572)...
Starting mock SQS (http port 4576)...
Starting mock SSM (http port 4583)...
Waiting for all LocalStack services to be ready
03:36:03.576 [main] INFO  org.elasticmq.server.Main$ - Starting ElasticMQ server (0.14.5) ...
2019-04-03T03:36:05:WARNING:werkzeug:  * Debugger is active!
2019-04-03T03:36:05:INFO:werkzeug:  * Debugger PIN: 153-070-175
2019-04-03T03:36:05:INFO:werkzeug:  * Running on http://0.0.0.0:4563/ (Press CTRL+C to quit)
* Running on http://0.0.0.0:4583/ (Press CTRL+C to quit)
Ready.
2019-04-03T03:36:05:INFO:werkzeug: 127.0.0.1 - - [03/Apr/2019 03:36:05] "GET / HTTP/1.1" 200 -
03:36:06.250 [elasticmq-akka.actor.default-dispatcher-4] INFO  akka.event.slf4j.Slf4jLogger - Slf4jLogger started
03:36:08.504 [main] INFO  org.elasticmq.server.Main$ - === ElasticMQ server (0.14.5) started in 7087 ms ===
03:36:08.521 [elasticmq-akka.actor.default-dispatcher-2] INFO  o.e.rest.sqs.TheSQSRestServerBuilder - Started SQS rest server, bind address 0.0.0.0:4561, visible server address http://3d4e761b592d:4576
2019-04-03T03:36:14:INFO:werkzeug: 127.0.0.1 - - [03/Apr/2019 03:36:14] "PUT /buck1/ HTTP/1.1" 200 -
03:36:15.512 [elasticmq-akka.actor.default-dispatcher-3] INFO  o.elasticmq.actor.QueueManagerActor - Creating queue QueueData(streaming-service-sqs-queue,MillisVisibilityTimeout(30000),PT0S,PT0S,2019-04-03T03:36:15.427Z,2019-04-03T03:36:15.427Z,None,false,false,None,None,Map())

**2019-04-03T03:39:57:INFO:werkzeug: 127.0.0.1 - - [03/Apr/2019 03:39:57] "PUT /buck1/zYZk/edr/endpoint/1/plain/123/2345d/1554178586/Dt3V7QVCxu?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20190402T041626Z&X-Amz-SignedHeaders=host&X-Amz-Expires=28799&X-Amz-Credential=local%2F20190402%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=02f76ea43c6b230d267d99a7a6d886aeadd77c130e960aa4af8fd3c6ec83eacc HTTP/1.1" 200 -**
### This is the response on localstack for presigned put on s3 via presigned url

2019-04-03T03:40:23:INFO:werkzeug: 127.0.0.1 - - [03/Apr/2019 03:40:23] "PUT /buck1/sLHu/edr/endpoint/1/plain/123/2345d/1554099428/VQDCMd75dR HTTP/1.1" 200 -
### Regular cp aws cli command for which we are getting sqs notification

**Comment by mcgloneleviROOT** [comment]
I am running into the same issue.  S3 notifications for created objects are not showing up in an SQS queue that I have created.

**Comment by mcgloneleviROOT** [comment]
I figured out the issue that I was hitting locally. I had to add the QueueARN instead of the URL:

```
{
    "QueueConfigurations": [
        {
            "QueueArn": "arn:aws:sqs:elasticmq:000000000000:test_queue",
            "Events": [
                "s3:ObjectCreated:*"
            ]
        }
    ]
}
```

I got the ARN from this command:
aws --endpoint-url=http://localhost:4576 sqs get-queue-attributes --queue-url http://localhost:4576/queue/test_queue --attribute-names All

I hope this helps.  I have seen other people using the queue URL, but maybe that broke with a recent update to LocalStack.

**Comment by pwaterz** [comment]
I was not able to use the newer style configuration when adding the notification to the s3 bucket. I ended up having to use the old api.
```
{
    "TopicConfiguration": {
        "Event": "s3:ObjectCreated:*",
        "Topic": "arn:aws:sqs:us-west-2:000000000000:my-sqs-topic"  
    }
}
```
`awslocal  s3api put-bucket-notification --bucket bucket-to-attach-to --notification-configuration file://depreciated-config.json`

**Comment by ashameem123** [comment]
@mcgloneleviROOT , @ManigandanMS , @rjaduthie   --> Please help

How to check if the SQS has received the notification from S3 ? 
Commands used:

aws --endpoint-url=http://localhost:4566 s3 mb s3://sqs-test-bucket
aws --endpoint-url=http://localhost:4576 sqs create-queue --queue-name test-queue
aws --endpoint-url=http://localhost:4566 s3api put-bucket-notification-configuration --bucket sqs-test-bucket --notification-configuration file://sqsConfiguration.json
aws --endpoint-url=http://localhost:4566 s3 cp s3-event.json s3://sqs-test-bucket
aws --endpoint-url=http://localhost:4576 sqs receive-message --queue-url http://localhost:4576/queue/test-queue

sqsConfiguration.json:
{
    "QueueConfigurations": [
        {
            "QueueArn": "arn:aws:sqs:us-east-1:000000000000:test-queue",
            "Events": [
                "s3:ObjectCreated:*"
            ]
        }
    ]
}


The output i am getting after running the last command (to receive msg):
![image](https://user-images.githubusercontent.com/54183749/92775154-c32c6580-f363-11ea-92d3-8ef5ad111b40.png)

Should it also print the content of  json  uploaded in s3?

**Comment by yiannissakk** [comment]
@ashameem123 I am getting the same json back when receiving the message, I was wondering if this is all the data that is included as I would expect it to at least contain the path of the file that generated the request. Is there a way to enrich the response?
