### ISSUE TITLE
Error using !Ref tag in cloudformation template

### ISSUE THREAD

**Issue by lolcookie** [localstack/localstack#1219]
Using localstack 0.9.1:

```
ConstructorError: could not determine a constructor for the tag '!Ref'
in "<unicode string>", line 478, column 12:
Value: !Ref SNSTopicUpdated
```

Strangely the error does not occur when running the same script in localstack docker.

**Comment by lolcookie** [comment]
The work around is to change the template to be like 
```
Value: 
    Ref: SNSTopicUpdated
```

However I shouldn't have to do this, is the team aware of this issue? Is it just on my machine?

**Comment by dooman87** [comment]
Got the same problem. Working fine on version 0.9.0

**Comment by whummer** [comment]
Thanks for reporting @lolcookie @dooman87 . This should be working in the latest version. We also have an example in our integration tests [here](https://github.com/localstack/localstack/blob/2293b9aa365cb36fa9e62e5d321ee81688a82950/tests/integration/templates/template1.yaml#L29), to avoid regressions in the future. Closing this issue - please report here if the problem persists. Thanks
