### ISSUE TITLE
Issue while running the localstack on ubuntu VM

### ISSUE THREAD

**Issue by sohrab1-shaikh** [localstack/localstack#1220]
When I run the command "localstack start" , i get the error message. The screnshot is at below location

[localstackissue-screenshot](https://s3.us-east-2.amazonaws.com/ss-bucket20/localstack_issue.png)

**Comment by swdgit** [comment]
infra.pyc: Service "s3" not yet available, retrying...  getting the same thing on Mac. just pulled from master and a few issues went away. Is this in some way related to issue https://github.com/localstack/localstack/issues/393 

I'm doing docker-compose up 

`localstack_1  | 2019-03-30T22:11:26:WARNING:infra.pyc: Service "s3" not yet available, retrying...
localstack_1  | Waiting for all LocalStack services to be ready
localstack_1  | Waiting for all LocalStack services to be ready
localstack_1  | 2019-03-30T22:11:50:WARNING:infra.pyc: Service "s3" not yet available, retrying...
localstack_1  | Waiting for all LocalStack services to be ready
localstack_1  | 2019-03-30T22:11:59:WARNING:infra.pyc: Service "s3" not yet available, retrying...
localstack_1  | Waiting for all LocalStack services to be ready
localstack_1  | 2019-03-30T22:12:11:WARNING:werkzeug:  * Debugger is active!
localstack_1  | 2019-03-30T22:12:11:INFO:werkzeug:  * Debugger PIN: 131-173-019`

not sure the xtra bit will help

**Comment by austinbutler** [comment]
For me it works with version 0.9.0, not 0.9.1 or latest.

**Comment by sohrab1-shaikh** [comment]
Will try v0.9.0, Thx
    On Tuesday, April 16, 2019, 7:05:45 AM GMT+5:30, austinbutler <notifications@github.com> wrote:  
 
 
For me it works with version 0.9.0, not 0.9.1 or latest.

**Comment by CConnection** [comment]
Same here on osx mojave. 0.9.0 works, 0.9.1 or latest not

**Comment by whummer** [comment]
Thanks for reporting @sohrab1-shaikh @CConnection @swdgit . Can you please try again with the latest version of the Docker image (version `0.9.5`)?
