### ISSUE TITLE
Could not set CORS configuration for S3 bucket

### ISSUE THREAD

**Issue by duykhoibui96** [localstack/localstack#1222]
Hi guys,

I would like to update s3 bucket CORS configuration with this configuration file
```
{
   "CORSRules":[
      {
         "AllowedOrigins":[
            "*"
         ],
         "AllowedHeaders":[
            "x-amz-tagging"
         ],
         "AllowedMethods":[
            "PUT", "GET"
         ],
         "MaxAgeSeconds":3000,
         "ExposeHeaders": ["x-amz-tagging"]
      } 
   ]
}

```

I use this command and it updated successfully

`awslocal s3api put-bucket-cors --bucket <<MY_BUCKET>>`

I have double-checked by using `get-bucket-cors` command and it shows correct configuration

`awslocal s3api get-bucket-cors --bucket <<MY_BUCKET>>`

Unfortunately, when I upload a file to S3 local, it always show error `Request header field x-amz-tagging is not allowed by Access-Control-Allow-Headers in preflight response.`

I took a look at your source code and see this line

https://github.com/localstack/localstack/blob/3e1f0cc3aac3872e99a8e65c42bc58778cfc427a/localstack/services/s3/s3_listener.py#L233

It uses field `CORSRule`, not `CORSRules` to append CORS header. Is this my mistake or an issue ?

Thanks,

**Comment by ganeko** [comment]
Hi,

Why this issue is closed without any info?. I'm trying a similar thing and I'm not getting the expected headers.

**Comment by JoergAdler** [comment]
Same here.

**Comment by ganeko** [comment]
As a very big workaround in development we are setting `crossorigin="anonymous"` in HTML elements that use assets from localstack.

**Comment by JoergAdler** [comment]
Have you tried to update localstack? Because for me, it was the same in 0.9.4 and was gone in 0.10.4

**Comment by ganeko** [comment]
> Have you tried to update localstack? Because for me, it was the same in 0.9.4 and was gone in 0.10.4

Yes, I have test it with the latest version. In fact, I'm getting CORB problems with audio files, see https://github.com/localstack/localstack/issues/1259

Proposed workaround works with CORS and CORB problems, but the second problem still happens.
