### ISSUE TITLE
Presigned S3 url doesnt notify sqs 

### ISSUE THREAD

**Issue by ManigandanMS** [localstack/localstack#1225]
I have configured s3 bucket with event configuration to sqs for every object creation. When I try out aws cli command I get the notification correctly. 

When I try using presigned url with curl/postman command, I dont get the sqs notification. **Is this a known issue and are there any work arounds?**

**Comment by ManigandanMS** [comment]
@whummer

**Comment by sdnakhla** [comment]
Sounds similar to this:  https://github.com/localstack/localstack/issues/945

**Comment by whummer** [comment]
Thanks for reporting - should be fixed in #1639
