### ISSUE TITLE
lambda_cwd is None

### ISSUE THREAD

**Issue by jrowen** [localstack/localstack#1226]
I'm seeing the following errors when trying to deploy a Python3.7 Lambda function via the cli.  It appears that the `lambda_cwd` variable is None.  Any ideas what could be happening?
```
DEBUG:localstack.services.awslambda.lambda_executors: Copying files to container "localstack_lambda_arn_aws_lambda_us-east-2_000000000000_function_func" from "None".
DEBUG:localstack.services.awslambda.lambda_executors: docker cp "None/." "localstack_lambda_arn_aws_lambda_us-east-2_000000000000_function_func:/var/task"
WARNING:localstack.services.awslambda.lambda_api: Error executing Lambda function arn:aws:lambda:us-east-2:000000000000:function:func: Command 'docker cp "None/."
```
I should also note that the other two messages appear, but I believe they are a symptom of the missing cwd value.
```
WARNING:localstack.services.awslambda.lambda_api: Function already exist: func
...
ERROR: 'docker cp "None/." "localstack_lambda_arn_aws_lambda_us-east-2_000000000000_function_func:/var/task"': exit code 1; output: lstat /opt/code/localstack/None: no such file or directory
```

**Comment by jrowen** [comment]
This error seems to be caused when I add `boto3-1.9.126` into the function zip.  Without it, everything works fine.  Is this version of `boto3` not yet supported?  I'm using the `apigatewaymanagementapi` client, which doesn't appear to be available in default version of `boto3` .

**Comment by whummer** [comment]
Thanks for reporting @jrowen . Seems like you have packaged the wrong `boto3` version into your function zip. In general, it is a good practice not to package `boto3` into the function, and instead use the one provided by the environment (both, in LocalStack and in the real AWS environment).

I double-checked that `apigatewaymanagementapi` boto3 client is available in the version of `boto3` we're using. Closing this issue - please reopen if the problem persists. Thanks
