### ISSUE TITLE
Not able to change the localstack docker timezone

### ISSUE THREAD

**Issue by cdcrazy2292** [localstack/localstack#1230]
Hi, I am trying to change my localstack docker container timezone to my local timezone instead of UTC, has anybody done this before or know how to do it? I have tried many different resources online but haven't succeeded. Any help will be appreciated. 
Thanks

**Comment by whummer** [comment]
Hi @cdcrazy2292 , you may be able to achieve this by adding a startup script and mounting it as `/docker-entrypoint-initaws.d` into the container (see https://github.com/localstack/localstack#initializing-a-fresh-instance). Not entirely sure, though. Is there a particular reason why you'd like to do this.

Closing this issue as it is not strictly LocalStack related, but please keep us in the loop if you find a solution for this. Thanks
