### ISSUE TITLE
LocalStack version 0.9.1 hasn't been pushed to the Docker registry

### ISSUE THREAD

**Issue by kalaspuff** [localstack/localstack#1232]
https://hub.docker.com/r/localstack/localstack/tags shows versions up to 0.9.0, however the 0.9.1 release notes where pushed to master 6 days ago [[3e1f0cc](https://github.com/localstack/localstack/commit/3e1f0cc3aac3872e99a8e65c42bc58778cfc427a)].

**Comment by whummer** [comment]
Thanks for the hint @kalaspuff - we had some issues with the build pipeline. Version 0.9.1 has been pushed now.
