### ISSUE TITLE
Feature request: SMTP

### ISSUE THREAD

**Issue by cburgmer** [localstack/localstack#1233]
We are using SES with AWS' SMTP server, and want to replicated this locally. More specifically, we have configured SES with a specific rule which will store emails for certain recipients in an S3 bucket instead of actually sending those (for testing purposes).

We have solved this for us, as we currently use https://github.com/Nilhcem/FakeSMTP to provide a mock SMTP server. We have replicated said rule with a manual `aws s3 sync`.

Is it correct to assume such a feature could belong directly with localstack?

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-92) by [Unito](https://www.unito.io/learn-more)

**Comment by thrau** [comment]
This feature is available in LocalStack pro. Should you have problems with the pro version, please let us know in Slack, thanks!
