### ISSUE TITLE
Feature : Honor attributes on SNS Subscription

### ISSUE THREAD

**Issue by fgarcia-betclic** [localstack/localstack#1235]
Hello,
I am working with a SNS to SQS project, in it we want to use the feature `RawMessageBody` when subscribing.
By looking into the code I found that the attributes are not persisted, for example `RawMessageBody` is always set to 'false'. Elsewhere in the code the parameters seems to be correctly used and send transform the message accordingly.

I created a PR fixing this : https://github.com/localstack/localstack/pull/1234
Thank you

**Comment by khanou** [comment]
Hi, 

I have the same request feature on my side to use the SNS/SQS into a proper way. 

Look like [PR #1234](https://github.com/localstack/localstack/pull/1234) did the trick.

**Comment by fgarcia-betclic** [comment]
Fixed by #1234
