### ISSUE TITLE
ctrl+z creates problem in environment that dont connect to internet

### ISSUE THREAD

**Issue by MT2017045** [localstack/localstack#1240]
localstack works fine in internet connected environment. we cloned our machine and took it a secure environment where internet dont work. localstack work fine there too, but when by mistake if ctrl+z is clicked in the running server, make install gets stuck and doesnt run again.

why it is getting stuck?
if once everything is properly installed and working, why there is a need to again install things after ctrl+z?

**Comment by pydo** [comment]
You probably detached the running process from your terminal. To return it to the foreground run `fg` from your terminal.

Here's an example where I start a python process, detach it with `ctrl+z` then bring it back to the foreground with `fg`.
```
devonh@devonh-desktop /tmp> python3                                        
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
Job 1, 'python3' has stopped
devonh@devonh-desktop /tmp> fg                                             
Send job 1, “python3” to foreground

>>> 
```

If I understood your issue correctly, it isn't related to localstack.

**Comment by whummer** [comment]
Thanks for reporting @MT2017045 , and thanks for providing the solution @pydo 👍
