### ISSUE TITLE
"Service "s3" not yet available, retrying" on Windows

### ISSUE THREAD

**Issue by thomasf-nvm** [localstack/localstack#1243]
Given:
Environment: Windows 10 build 1709 x64, Docker Toolbox 18.09.3, VirtualBox 5.2.26   
`git clone https://github.com/localstack/localstack.git`
`docker-machine start`

When:
`docker-compose up`

Then:
I expect localstack to start

Actual:
loop of:
`2019-04-10T12:41:42:WARNING:infra.pyc: Service "s3" not yet available, retrying...`
`Waiting for all LocalStack services to be ready`
which never completes.

**Comment by swdgit** [comment]
same issues with #1220 and #1202

**Comment by dangreaves** [comment]
This is also occurring for me on OSX when booting with:

```
TMPDIR=/private$TMPDIR localstack start --docker
```

**Comment by thomasf-nvm** [comment]
Just worked around it for now by editing the docker file and only starting
sqs service which is all I’m actually using.

**Comment by austinbutler** [comment]
For me it works with version 0.9.0, not 0.9.1 or latest.

**Comment by prodigeris** [comment]
Downgrading to 0.9.0 helped.

**Comment by thomasf-nvm** [comment]
Do you know which commit (or date) this is?

**Comment by wickedgenius** [comment]
Also found that 0.9.1 doesn't start s3 successfully, running on afresh Ubuntu 18.04 with just the pre-reqs.

Installing 0.9.0 works.

**Comment by whummer** [comment]
Installation should work now under Windows (see also the recent changes in #1631). Closing this issue - please re-open if the problem persists. Thanks
