### ISSUE TITLE
Docker image 0.9.1 and Latest doesn't start S3 on Windows 10

### ISSUE THREAD

**Issue by jimmytadams** [localstack/localstack#1270]
Docker image 0.9.1 and Latest doesn't start S3 on Windows 10 ... keep re-trying ...

**Comment by adamdavis40208** [comment]
https://github.com/localstack/localstack/issues/1243 and a couple others covers this

**Comment by whummer** [comment]
Thanks for reporting @jimmytadams . This should have been fixed in the meantime - please re-open this issue with more error details if the problem persists. Thanks
