### ISSUE TITLE
Unable to upload image in S3API via cli

### ISSUE THREAD

**Issue by Aki005** [localstack/localstack#1274]
aws s3api put-object --bucket xyz --key eca89af3c15d4e1fe509baac34517f25.jpg --body eca89af3c15d4e1fe509baac34517f25.jpg

Error parsing parameter '--body': Blob values must be a path to a file.

**Comment by whummer** [comment]
Seems like an issue related to usage of the AWS CLI, not related to LocalStack. Closing.
