### ISSUE TITLE
IAM endpoints always say they are not valid

### ISSUE THREAD

**Issue by christhomas** [localstack/localstack#1275]
I'm trying to use IAM and everytime I do, with awslocal or awscli, it always says that the endpoint is not valid.

I don't even get to try anything else. It just stops me each time at the same point. 

Has anybody else got this problem

**Comment by christhomas** [comment]
A new day and I restarted localstack to find that now it does work.

**Comment by leobarcellos** [comment]
@christhomas do you have a word about this?

I keep getting a `Connection was closed before we received a valid response from endpoint URL: "http://localhost:4593/".`

**Comment by christhomas** [comment]
Can you validate using netcat that the port is actually open?

**Comment by christhomas** [comment]
Once it started working again, it never stopped working again, so I never had any idea what was the problem but I never had the problem for long enough so I could try to find out what the problem was. Sorry

**Comment by leobarcellos** [comment]
I managed to get it to work using the `localstack@0.9.3` instead of the `localstack@latest`, for some reason the `latest` do not expose the IAM

**Comment by whummer** [comment]
Looks like this issue is fixed - closing. Thanks
