### ISSUE TITLE
Unable to create multiple python lambdas with same module names

### ISSUE THREAD

**Issue by mwbenowitz** [localstack/localstack#1282]
I am unable to create multiple python lambdas that share module names. For example, I have several functions that all have a `helpers.errors` module that implements various custom Exception types for each function. When creating these functions in localstack, the first function is created normally, but the subsequent functions fail with an `ImportError` because the module from the first function is loaded.

I've attempted different methods of loading the function code, including using the `__local__` override as will as the `ZipFile` option both within and without Docker. 

More concisely, if I have two functions:
```
function1
|--handler.py
|--helpers
     |--errors.py
         |--Exception1
         |--Exception2
```

```
function2
|--handler.py
|--helpers
     |--errors.py
         |--Exception1
         |--Exception3
```
The creation of `function2` will fail with an `ImportError` that `Exception3` cannot be imported.

**Comment by whummer** [comment]
Thanks for reporting @mwbenowitz . I'm assuming this is using the local (non-Docker) Lambda executor? Can you please try with the latest version of the code, and setting `LAMBDA_EXECUTOR=docker` - does the problem persist under these settings?

**Comment by mwbenowitz** [comment]
@whummer thank you, I updated my environment and was able to successfully create the functions with setting `LAMBDA_EXECUTOR=docker`

Using `local` still throws an error
