### ISSUE TITLE
Is SageMaker on the roadmap?

### ISSUE THREAD

**Issue by ccotar** [localstack/localstack#1287]
My team is going to be using SageMaker frequently and having it mocked by this system would be a huge plus.  What are the plans (if any) for SageMaker and LocalStack?

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-97) by [Unito](https://www.unito.io/learn-more)

**Comment by thrau** [comment]
We have very basic SageMaker support in pro, see [feature coverage](https://github.com/localstack/localstack/blob/master/doc/feature_coverage.md). Please let us know if you have specific feature requests.
