### ISSUE TITLE
Any plan to support Lambda Layers? 

### ISSUE THREAD

**Issue by rodbutters** [localstack/localstack#1289]
Issue #1246 shows how layers can be used with lambci/lambda-docker. 

Any interest / plans to implement layer subcommands for lambda?

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-98) by [Unito](https://www.unito.io/learn-more)

**Comment by justinian336** [comment]
Please!

**Comment by thrau** [comment]
We have Lambda Layer support in pro, see [feature coverage](https://github.com/localstack/localstack/blob/master/doc/feature_coverage.md). Please let us know if you have specific feature requests.
