### ISSUE TITLE
Allow docker image version to be specified in @LocalstackDockerProperties annotation

### ISSUE THREAD

**Issue by markcuk** [localstack/localstack#1295]
In order to make our builds repeatable we need to be able to lock the version of the localstack docker image that we are using. This could be added to the @LocalstackDockerProperties annotation (or be an environment variable).

**Comment by whummer** [comment]
Good point @markcuk  - any chance you can add a pull request with that change? Thanks!

**Comment by markcuk** [comment]
@whummer working on it right now
