### ISSUE TITLE
 Permission denied: '/tmp/localstack/zipfile.e88738e2'

### ISSUE THREAD

**Issue by nealeu** [localstack/localstack#1299]
Permissions are broken again due to some recent Dockerfile changes.

/tmp/localstack has root:root as owner rather than localstack:localstack.

**Comment by deleugpn** [comment]
Getting something similar to this as well as of today in my Pipeline. I'm guessing it's related to https://github.com/localstack/localstack/commit/0886a249ab8bbfea47b68597045a061ef5c55ece#diff-3254677a7917c6c01f55212f86c57fbfR67

**Comment by whummer** [comment]
@nealeu @deleugpn Can you please check if it works with the latest version of the Docker image? Thanks
