### ISSUE TITLE
Cloud formation account id different from other service

### ISSUE THREAD

**Issue by rihtak06** [localstack/localstack#1300]
Hi ,deploy server-less application in local-stack through cloud formation template but i start notice account id for cloud formation is 12345789 but for other service it is 00000000 ,so its like cloud formation  try to deploy service in different account

**Comment by whummer** [comment]
Thanks for reporting @rihtak06 - this should have been fixed in the meantime (see #1377). For example, after deploying a CloudFormation stack, this is the output of `list-stacks`:
```
$ AWS_DEFAULT_REGION=us-east-1 awslocal cloudformation list-stacks
{
    "StackSummaries": [
        {
            "StackId": "arn:aws:cloudformation:us-east-1:000000000000:stack/event-service-v03-local/2621533e-6a90-4d68-a2f6-f3522cc05888",
     ...
```
