### ISSUE TITLE
Handle "success_action_status" form field in S3 POST.

### ISSUE THREAD

**Issue by josh08h** [localstack/localstack#1302]
The form POST operation to S3 accepts a `success_action_status` field which can be set to 200/201/204, see [here](https://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectPOST.html). Localstack currently handles the `success_action_redirect` field [here](https://github.com/localstack/localstack/blob/master/localstack/services/s3/s3_listener.py#L518) and so we should look into handling the `success_action_status` field too.

The 201 from AWS responds with an XML document with some fields about the object that has just been created in AWS, see below.

```
<PostResponse>
    <Location>https://s3.amazonaws.com/link-to-the-file</Location>
    <Bucket>s3-bucket</Bucket>
    <Key>development/8614bd40-691b-4668-9241-3b342c6cf429/image.jpg</Key>
    <ETag>"32-bit-tag"</ETag>
</PostResponse>
```

**Comment by qasimzee** [comment]
I have a PR for this. @whummer what's the process of creating a PR?

**Comment by qasimzee** [comment]
ping :)

**Comment by qasimzee** [comment]
I took a stab on it: https://github.com/localstack/localstack/pull/1849
