### ISSUE TITLE
localstack makes header case insensitive

### ISSUE THREAD

**Issue by gdippolito** [localstack/localstack#1304]
Localstack is modifying the header to make them case insensitive. 
This behaviour is different from AWS apigateway/lambda and it may cause errors when a lambda function is inspecting the header to find a specific key.  

This is where this functionality has been implemented:
https://github.com/localstack/localstack/blob/8420ccf89203b262587a78077657bef31dd60d7a/localstack/services/generic_proxy.py#L184

Is there a way to disable this behaviour? 

What is the reason for this feature to be implemented in the first place, can we not forward directly the headers without modifying them? 

Thanks,
Giulio

**Comment by alfl** [comment]
FYI, the HTTP standard specifies that headers are case insensitive. Client code should in theory not expect servers to behave in non-standard ways.

I ran into this with Node proxies as well.

**Comment by whummer** [comment]
Thanks for reporting @gdippolito . As @alfl mentioned, the HTTP standard specifies that headers are case insensitive. In fact, all your client code should make case-insensitive comparisons and lookups. 

Generally our goal is to be AWS compatible, but in this particular case I would mark this as "won't fix", to remain compliant with the standards. Of course, please feel free to raise a pull request if you think there is a simple and easy solution to this issue. Thanks!
