### ISSUE TITLE
SNS RawMessageDelivery feature question

### ISSUE THREAD

**Issue by lucio81** [localstack/localstack#131]
Hi, there is any plan about implementing or managing the option RawMessageDelivery on the SNS/SQS service?

**Comment by Tetradeus** [comment]
aws --region us-east-1 --endpoint-url "http://localhost:4575" sns set-subscription-attributes --subscription-arn "arn:aws:sns:us-east-1:123456789012:....." --attribute-name RawMessageDelivery  --attribute-value true

Unable to parse response (syntax error: line 1, column 54), invalid XML received:
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>

**Comment by whummer** [comment]
Thanks for reporting @lucio81 and @Tetradeus . Support for `set-subscription-attributes`/`get-subscription-attributes` has been added in commit 39adfeb15c23c3b37907de7393d87a5dfaef1a60 . Can you please pull the latest version (Docker image tags `0.6.0` and `latest`) and give it a try. Thanks.

**Comment by bogdanbrindusan** [comment]
@whummer  It seems using the `RawMessageDelivery` the body is as expected, but the message attributes are not passed along. Is there an update about this? Thanks.

**Comment by whummer** [comment]
Closing for housekeeping reasons, should be fixed in the meantime - please re-open or comment here if the problem persists. Thanks
