### ISSUE TITLE
Add ability to use WebSockets

### ISSUE THREAD

**Issue by daveisfera** [localstack/localstack#1316]
AWS Lambda added support for [using WebSockets](https://aws.amazon.com/blogs/compute/announcing-websocket-apis-in-amazon-api-gateway/), so it would be very helpful to also be able to use them with `localstack` to test their use in a local development environment.

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-100) by [Unito](https://www.unito.io/learn-more)

**Comment by bRRRITSCOLD** [comment]
This would be aaaaaaamzing

**Comment by thrau** [comment]
This feature is available in LocalStack pro. Should you have problems with the pro version, please let us know in Slack, thanks!
