### ISSUE TITLE
Inconsistency in S3 PUT object response body

### ISSUE THREAD

**Issue by demisx** [localstack/localstack#1317]
When I "PUT" an object using a pre-signed by localstack S3 URL, the localstack responds with "Content Length: 233" and `<PutObjectResponse>...</PutObjectResponse>` XML in the body. 

When I run the same code against AWS S3, the content length is 0 and response body blank. Would be great if localstack matched the AWS S3 response.

Running the latest 0.9.3 localstack docker image.

**Comment by whummer** [comment]
Thanks for reporting @demisx - this should be fixed in the `latest` version of the Docker image (see #1376). Closing this issue - please reopen if the problem persists.
