### ISSUE TITLE
Specifying DEFALT_REGION in docker-compose causes SNS failure

### ISSUE THREAD

**Issue by shvincen** [localstack/localstack#1321]
When specifying the DEFAULT_REGION in my docker compose file my S3 notification can not be sent to the SNS topic.

Error:
2019-05-17T21:43:51:WARNING:localstack.services.s3.s3_listener: Unable to send notification for S3 bucket "test-commerce-local-app-internal" to SNS topic "arn:aws:sns:us-east-1:123456789012:test-queue"

Docker Compose:
version: '3'
services:
  localstack:
    image: localstack/localstack
    container_name: localstack_test
    ports:
      - "8080:8080"
      - "4567-4596:4567-4596"
      - "443:443"
    privileged: true
    environment:
      - DEBUG=1
      - DATA_DIR="/tmp/localstack/data"
      - DEFAULT_REGION="us-east-1"
      - HOST_TMP_FOLDER="/tmp/localstack"
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/tmp/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

**Comment by whummer** [comment]
Thanks for reporting @shvincen . Looks like this uses the incorrect account ID (`123456789012` instead of `000000000000`.
```
SNS topic "arn:aws:sns:us-east-1:123456789012:test-queue"
```
This should be fixed in the meantime. Please re-open this issue if the problem persists. Thanks
