### ISSUE TITLE
Docker example with junit5 throws java.lang.IllegalStateException

### ISSUE THREAD

**Issue by Ghilteras** [localstack/localstack#1324]
looks like this snippet for Junit5 (have not tested it with Junit4) is not working with `lambda` and `stepfunctions`

```
@ExtendWith(LocalstackDockerExtension.class)
@LocalstackDockerProperties(randomizePorts = true, services = { "sqs", "kinesis:77077" })
public class MyDockerCloudAppTest {
   ...
}
```

I get the error
```
java.lang.IllegalStateException: Service to port mapping has not been determined yet.

	at cloud.localstack.docker.LocalstackDocker.endpointForService(LocalstackDocker.java:183)
	at cloud.localstack.docker.LocalstackDocker.getEndpointLambda(LocalstackDocker.java:116)
	at cloud.localstack.DockerTestUtils.createEndpointConfiguration(DockerTestUtils.java:114)
	at cloud.localstack.DockerTestUtils.getClientLambda(DockerTestUtils.java:53)
```

Which seems misleading because even if I specifically set the port mapping localstack seems to ignore it. I also noticed that stepfunctions client is only available in the `DockerTestUtils` class and not in the `TestUtils` class so I cannot even try to do this without Docker.

**Comment by ImFlog** [comment]
Hello,
I think that specifying the `randomizePorts` + a default port for Kinesis is causing the error.
When you specify `RandomizePorts` it means this: 
```java
    public RunCommand withExposedPorts(String portsToExpose, boolean randomize) {
        String portsOption = String.format("%s:%s", randomize ? "" : portsToExpose, portsToExpose );
        addOptions("-p", portsOption);
        return this;
    }
```
So there is a high chance that the port 77077 is not on the exposed port list.
Try to chose an option, random or fixed port.
Hope it helps.

**Comment by ImFlog** [comment]
I've run some tests locally and I can confirm that mixing randomize ports and fixing one for a service cause the issue.
I'll create a PR to explain this.
