### ISSUE TITLE
Lambda function cannot make DynamoDB calls

### ISSUE THREAD

**Issue by MrBigDog2U** [localstack/localstack#1333]
I have a Lambda function that is subscribed to a Kinesis stream. The function is supposed to format a record from the data and write the record to a DynamoDB table. When running in localstack, the putRecord call returns an error 

```"put error - write EPROTO 139742444377984:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:\n"```

I am instantiating the DynamoDB object with options

```{"region":"us-west-1","endpoint":"172.17.0.1:4569" }```

Since it seemed this might be SSL related, I tried adding { sslEnabled: false } to the DynamoDB options. The result was the error changed to 

```"put error - 502"```

So, to be clear, this is a lambda function running in localstack attempting to write a record to a DynamoDB table running in the same localstack using LOCALSTACK_HOSTNAME:4569 as the dynamoDB endpoint.

**Comment by whummer** [comment]
Thanks for reporting @MrBigDog2U . This should be fixed in the latest version, an integration test has been added in #2330 . Can you please give it a try with the `latest` version of the Docker image? Please report here if the problem persists. Thanks
