### ISSUE TITLE
S3 event notification has default size of 1024, rather than actual size of s3 object

### ISSUE THREAD

**Issue by luked99** [localstack/localstack#1340]
I just noticed that in SQS events triggered by creating an S3 object, the size is always 1024, rather than the real size of the file.

With the 'real' AWS, you get the size of the file.

The code in get_event_message() has a default file_size parameter of 1024, but this is not supplied in send_notifications()

**Comment by whummer** [comment]
Good catch, thanks @luked99 . Do you think you could raise a small pull request with a fix? Thanks!

**Comment by JavierLuna** [comment]
I want to work on this :)

**Comment by whummer** [comment]
Yes, please @JavierLuna , please go ahead! A PR will be greatly appreciated - thanks!

**Comment by whummer** [comment]
Hi @JavierLuna, any update on this - did you have a chance to start working on this issue? Thanks

**Comment by whummer** [comment]
@luked99 @JavierLuna . This should be fixed in #2069 - please report here if the problem persists. Thanks
