### ISSUE TITLE
Incorrect response content-type header from cloudwatch logs

### ISSUE THREAD

**Issue by stevenhunter** [localstack/localstack#1343]
When using the .NET AWSSDK connected to localstack and querying cloudwatch logs e.g. 
 var logClient = new AmazonCloudWatchLogsClient(new AmazonCloudWatchLogsConfig()
            {
                ServiceURL = "http://localhost:4586",
                UseHttp = true,
                AuthenticationRegion = "eu-central-1",
            });
            var logGroupName = @"/aws/lambda/f1";
            var events = logClient.FilterLogEventsAsync(new FilterLogEventsRequest()
            {
                LogGroupName = logGroupName,
            }).GetAwaiter().GetResult();

The response is returned from the server but cannot be parsed by the SDK client code because the response's content-type header is text/html when it should be application/x-amz-json-1.1.  This confirmed using Fiddler traces comparing the response from localstack to the response from AWS in the cloud. Can this be fixed easily?

**Comment by whummer** [comment]
Thanks for reporting @stevenhunter . This should be fixed in #2244 - can you please give it a try with the `latest` version? Please report here if the problem persists. Thanks
