### ISSUE TITLE
SQS Messages has exp format on timestamp

### ISSUE THREAD

**Issue by adrianeui** [localstack/localstack#135]
SentTimestamp and ApproximateFirstReceiveTimestamp has exp number format rather long format, is this a valid value that can be sent from AWS ? I think this should be fixed to be a valid long number.

`{
    "Messages": [
        {
            "Body": "Test Message!",
            "Attributes": {
                "ApproximateFirstReceiveTimestamp": "1.49138149959e+12",
                "SenderId": "AIDAIT2UOQQY3AUEKVGXU",
                "ApproximateReceiveCount": "1",
                "SentTimestamp": "1.49138142195e+12"
            },
            "ReceiptHandle": "xuazrzyjcgpgzpzlxlyxmujbgzfkswixjkywshturlylrfwzyccutlumitgduyzddwkaoypcmswlkxrrjghdyztfewrpmkxdufptyketrfumwzicmggogdbaucwztvorplibccpfhirmalnixvfbklzrgncpisdsiuiajqwefxueqhuygfibmgqwx",
            "MD5OfBody": "df69267381a60e476252c989db9ac8ad",
            "MessageId": "a6ed436b-076a-0d8d-73e1-cc3291a19c28"
        }
    ]
}`

**Comment by ferranscopely** [comment]
I traced down the bug to moto (spulec/moto#996), and submitted a pull request which has already been merged.

Do you have an estimation on when a release of localstack containing this fix could happen?

**Comment by whummer** [comment]
Thanks for tracing down that bug @ferranscopely . The version is bumped in commit 5b3d8678eaddafc850f8777bd308bb6161b69692 . Can you please give it a try using the latest Docker image (tags `0.6.0` and `latest`). Feel free to re-open this ticket if there is any other issue. Thanks
