### ISSUE TITLE
Lambdas don't trigger from SQS messages if SendMessageBatch is used

### ISSUE THREAD

**Issue by taylorfinnell** [localstack/localstack#1364]
It appears lambdas are not triggered from items being pushed to SQS if [SendMessageBatch](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_SendMessageBatch.html) is used instead of [SendMessage](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_SendMessage.html)

**Comment by cosmir17** [comment]
@taylorfinnell, not answering your question, but I want to know. I would like to subscribe my local lambda service to a local aws service(dynamo db change feed). I searched for a way to so but couldn't find one. Can I ask how you could make a subscrition for your lambda service? Thank you :)

**Comment by wapmesquita** [comment]
I've faced the same issue. I was publishing a batch of messages to the queue that was supposed to trigger the lambda. It just worked when I changed publish a single message.

**Comment by scott-mcdonald** [comment]
Encountered the same problem. Was trying to determine if this is standard AWS behavior or specific to localstack. Going to assume specific to localstack although have not tried with actual AWS queues and lambdas yet to be 100% sure...

**Comment by whummer** [comment]
Thanks for reporting @taylorfinnell @cosmir17 @wapmesquita @scott-mcdonald . Would any of you be able to pick this up and create a small pull requests with a simple test? That would be highly appreciated - thanks! The `_send_message(..)` method in `sqs_listener.py` would be a good starting point: https://github.com/localstack/localstack/blob/master/localstack/services/sqs/sqs_listener.py#L261-L280

**Comment by mrosales** [comment]
A co-worker implemented a fix for this on a private fork this past summer, but we never got around to opening up a PR. I just took a glance and it seems like the `sqs_listener.py` and `lambda_api.py` logic has changed a fair amount from when the fork happened. I'm working on rebasing on master so I'll attempt to get a PR up for this.
