### ISSUE TITLE
Message attributes are not delivered when publishing a message on a SNS topic and receiving it from an SQS queue

### ISSUE THREAD

**Issue by jochenhebbrecht** [localstack/localstack#137]
#Hi,

When following the scenario:

---------------------------------------
`# CREATE SNS TOPIC AND SQS QUEUE`
`aws --endpoint-url=http://localhost:4576 --region us-east-1 sqs create-queue --queue-name queue1`
`aws --endpoint-url=http://localhost:4575 --region us-east-1 sns create-topic --name topic1`

`# EXTRACT 'QueueArn' ATTRIBUTE FOR SQS QUEUE`
`aws --endpoint-url=http://localhost:4576 --region us-east-1 sqs get-queue-attributes --queue-url $QUEUE_URL # extract arn of queue`

`# SUBSCRIBE SQS QUEUE ON TOPIC`
`aws --endpoint-url=http://localhost:4575 --region us-east-1 sns subscribe --topic-arn $TOPIC_ARN --protocol sqs --notification-endpoint $QUEUE_ARN`

`# PUBLISH MESSAGE`
`aws --endpoint-url=http://localhost:4575 --region us-east-1 sns publish --message text --message-attributes '{"an-attribute-key": {"DataType": "string","StringValue": "an-attribute-value"}}' --topic-arn $TOPIC_ARN`

`# RECEIVE MESSAGE`
`aws --endpoint-url=http://localhost:4576 --region us-east-1 sqs receive-message --queue-url $QUEUE_URL`

---------------------------------------

... we noticed the message attributes are not visible after receiving the message

---------------------------------------

`{
    "Messages": [
        {
            "Body": "text", 
            "ReceiptHandle": "xihnyhwwzvwkzblvarzotdngbseekjzmuwfxkufhoaprmbmpdzffnqlxgqywasojkpktizzgccbzrfsbvivuhwydylbseanncidlfigyvdzhgsazfwhwtoljshhxcqoylhshiavirbfywhqoehypjkachyyiepaedsohtzwlfioqjzlupoigglxdf", 
            "MD5OfBody": "1cb251ec0d568de6a929b520c4aed8d1", 
            "MD5OfMessageAttributes": "d41d8cd98f00b204e9800998ecf8427e", 
            "MessageId": "639cd590-96e4-23b5-e90b-946a4497206b", 
            "Attributes": {
                "ApproximateFirstReceiveTimestamp": "1.49872794573e+12", 
                "SenderId": "AIDAIT2UOQQY3AUEKVGXU", 
                "ApproximateReceiveCount": "1", 
                "SentTimestamp": "1.49872782733e+12"
            }
        }
    ]
}`

---------------------------------------

It is possible to visualize the MessageAttributes as well?
This was tested with localstack:0.5.5

**Comment by whummer** [comment]
Thanks for reporting @jochenhebbrecht . Unfortunately, I was unable to reproduce the issue. Here is the detailed output (note that the code below uses the `jq` command to extract identifiers):

```
$ QUEUE_URL=`aws --endpoint-url=http://localhost:4576 --region us-east-1 sqs create-queue --queue-name queue1 | jq -r .QueueUrl`

$ TOPIC_ARN=`aws --endpoint-url=http://localhost:4575 --region us-east-1 sns create-topic --name topic1 | jq -r .TopicArn`

$ QUEUE_ARN=`aws --endpoint-url=http://localhost:4576 --region us-east-1 sqs get-queue-attributes --queue-url $QUEUE_URL | jq -r .Attributes.QueueArn`

$ aws --endpoint-url=http://localhost:4575 --region us-east-1 sns subscribe --topic-arn $TOPIC_ARN --protocol sqs --notification-endpoint $QUEUE_ARN
{
    "SubscriptionArn": "arn:aws:sns:us-east-1:123456789012:topic1:1e5f1197-44bc-4443-ba13-538ac84dcf6a"
}

$ aws --endpoint-url=http://localhost:4575 --region us-east-1 sns publish --message text --message-attributes '{"an-attribute-key": {"DataType": "string","StringValue": "an-attribute-value"}}' --topic-arn $TOPIC_ARN
{
    "MessageId": "n/a"
}

$ aws --endpoint-url=http://localhost:4576 --region us-east-1 sqs receive-message --queue-url $QUEUE_URL
{
    "Messages": [
        {
            "Body": "{\"Type\": \"Notification\", \"Message\": \"text\", \"TopicArn\": \"arn:aws:sns:us-east-1:123456789012:topic1\"}", 
            "Attributes": {
                "ApproximateFirstReceiveTimestamp": "1499170208132.53", 
                "SenderId": "AIDAIT2UOQQY3AUEKVGXU", 
                "ApproximateReceiveCount": "1", 
                "SentTimestamp": "1499170207711.56"
            }, 
            "ReceiptHandle": "dkpvgbqnibjebhdotalmufhmsebaqblaswhwyzugfgiytkakhsfwvvlzvlkwxtqrkvphgbxvfylxaenfwdquhnmyapjqfkqeoqbrpfglwhrcpsaqvqgojuktbjqmtxtonhuqtnmhqestxfaajrfpbpzbvzxocmsjavsfritwqveuaerfsggdablna", 
            "MD5OfBody": "529638c7a3c00dbe3a0784dc5eff13d8", 
            "MessageId": "d13d2616-1bef-88c1-db0c-1e7da6b11d64"
        }
    ]
}
```

There have been some changes recently, could you please give it another try with the latest version (`0.6.0`)? Thanks

**Comment by Tetradeus** [comment]
Still present on master : commit 070873113447afbe19841acc44520c5e532ec87d

**Comment by whummer** [comment]
Forgot to mention - if you are running directly from the local repo code (and not in Docker), you may need to re-install the libraries etc:
```
make clean
make install
```
Hope that works.

**Comment by Tetradeus** [comment]
I run it in docker (with docker-compose)

**Comment by whummer** [comment]
I tried pulling the latest image and started up with `docker-compose`, but still cannot reproduce the issue. :/

We've now also added an integration test that specifically tests the SQS->SNS integration with respect to message attributes:
https://github.com/localstack/localstack/blob/master/tests/integration/test_notifications.py#L26-L48

I'm not sure how to continue debugging this t.b.h. We'll need to find a reliable way of reproducing the issue. Can you again please provide a few more details about your environment and the *exact* steps you're taking to reproduce the issue? Thanks

**Comment by jochenhebbrecht** [comment]
You cannot reproduce it any longer because of this pull request: https://bitbucket.org/atlassian/localstack/pull-requests/107/fix-sns-message-attributes-sqs/diff.

Leen Toelen fixed the issue.

**Comment by whummer** [comment]
Thanks for the heads up @jochenhebbrecht . I'm assuming this is also fixed for you now, @Tetradeus . If not, please feel free to re-open the issue and provide a reproducible test case. Thanks

**Comment by jochenhebbrecht** [comment]
Ticket can be closed, my issue is fixed. Thanks everybody!

**Comment by Tetradeus** [comment]
That works for me. Thanks !

**Comment by ccrolf** [comment]
Does this solution handle raw message delivery correctly? 

Reading the Amazon docs, they mention that you need to set Raw Message Delivery to true to get SNS message attributes across as SQS message attributes: http://docs.aws.amazon.com/sns/latest/dg/SNSMessageAttributes.html 

Might have time to look into it, and submit a PR, but want to make sure I'm right first :)

**Comment by bogdanbrindusan** [comment]
@ccrolf No it doesn't. It passed the body correctly, but the message attributes are not visible on the message from SQS.
