### ISSUE TITLE
SNS publish accepts messages to any ARN, even with no topics created.

### ISSUE THREAD

**Issue by camhashemi** [localstack/localstack#1371]
Steps to reproduce:

1. Run localstack docker image w/ only SNS enabled.
2. From command line, run `aws sns --endpoint-url http://localhost:4575 list-topics`
3. Confirm that there are no topics listed.
4. From command line, run `aws sns --endpoint-url http://localhost:4575 publish --topic-arn 'foo:bar' --message 'hello'`
5. Confirm that the request succeeds and a messageId is returned.

These are the expected responses that I get when targeting SNS on AWS directly:
1. `publish` returns an error because of improperly formatted ARN
2. `publish` returns an error because of topic not found.

[edit: fixed the command line parameters]

**Comment by ImFlog** [comment]
Hello,
What version of localstack are you using ?
This shouldn't happen since 0.9.4 (see #1331).

**Comment by camhashemi** [comment]
I confirmed that it's fixed on `latest`. I had an old cached version. Thank you!
