### ISSUE TITLE
s3 not working

### ISSUE THREAD

**Issue by DraconPern** [localstack/localstack#1372]
I see a lot of tutorials with this line, but it never works.
aws --endpoint-url=http://localhost:4572 s3 mb s3://tutorial

I get 
make_bucket failed: s3://tutorial Parameter validation failed:
Invalid type for parameter CreateBucketConfiguration.LocationConstraint, value: None, type: <class 'NoneType'>, valid types: <class 'str'>

What am I missing?

**Comment by whummer** [comment]
Thanks for reporting @DraconPern . I'm unable to reproduce this issue. Can you share a few details about your environment - OS version, LocalStack versions, which command do you use to start the stack, etc.

**Comment by DraconPern** [comment]
Ubuntu 16.04 LTS running it under docker. 
I have tried
docker -d -p "4567-4583:4567-4583" localstack/localstack
and also under docker compose
localstack:
    image: "localstack/localstack"
    ports:
      - "4567-4583:4567-4583"    

aws-cli was installed using sudo apt-get install aws-cli

**Comment by DraconPern** [comment]
I think this bug is upstream. https://github.com/boto/boto3/issues/125

**Comment by whummer** [comment]
Another possible issue could be the region - we currently only support a single region (controlled by the `DEFAULT_REGION` config variable), and it defaults to `us-east-1`. Which version are you using?

**Comment by magthe** [comment]
Could mcohen01/amazonica#418 be the same issue?

**Comment by DraconPern** [comment]
It was indeed the region.  Using us-east-1 actually has some weird issue because technically it can't be used with the api sdk's.  I used us-west-1 and everything worked.
