### ISSUE TITLE
Elasticsearch still installed with 6.2 instead of recent 6.7 upgrade

### ISSUE THREAD

**Issue by fingahoverit** [localstack/localstack#1381]
I pulled latest localstack image [docker _hub](https://hub.docker.com/r/localstack/localstack/tags)  (the one tagged latest after the 0.9.5) and started it.
When I request for the elasticsearch search service on localhost:4571, it answers this json below confirming that 6.2 version is running.

```json
{
  "name" : "HBvcfXJ",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "GjMcdl8QQuKosNw09hOg0Q",
  "version" : {
    "number" : "6.2.0",
    "build_hash" : "37cdac1",
    "build_date" : "2018-02-01T17:31:12.527918Z",
    "build_snapshot" : false,
    "lucene_version" : "7.2.1",
    "minimum_wire_compatibility_version" : "5.6.0",
    "minimum_index_compatibility_version" : "5.0.0"
  },
  "tagline" : "You Know, for Search"
}
```

Did I missed anything in my configuration ?

**Comment by chenrui333** [comment]
Any update on this issue?

**Comment by chenrui333** [comment]
I just did the fresh installation of localstack and I saw it is with `v6.7.0`. Can you re-check at your end?

```
$ curl http://localhost:4571
{
  "name" : "SUb6vPU",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "lgsVfeghSm6QSR3X-zbQ4g",
  "version" : {
    "number" : "6.7.0",
    "build_flavor" : "default",
    "build_type" : "zip",
    "build_hash" : "8453f77",
    "build_date" : "2019-03-21T15:32:29.844721Z",
    "build_snapshot" : false,
    "lucene_version" : "7.7.0",
    "minimum_wire_compatibility_version" : "5.6.0",
    "minimum_index_compatibility_version" : "5.0.0"
  },
  "tagline" : "You Know, for Search"
}
```

**Comment by chenrui333** [comment]
Sorry, I was using `pip install --user localstack`, I am trying docker image approach now.

**Comment by chenrui333** [comment]
I can confirm this issue does happen for `localstack start --docker` but not happen for vanilla `localstack start`

**Comment by workmanw** [comment]
I also had this experience using the latest docker image.

**Comment by whummer** [comment]
Thanks for reporting @fingahoverit . Should be fixed in the `latest` version of the Docker image.
