### ISSUE TITLE
Localstack docker lambda does not log to cloudwatch logs

### ISSUE THREAD

**Issue by PragyaU** [localstack/localstack#1394]
Running lambda using localstack in docker using below command:

docker-compose up

Added logs in Lambda script using python logging library. when lambda gets executed it does not log to Cloudwatch logs

Using following aws-cli commands:

aws --endpoint-url=http://localhost:4586 logs describe-log-groups

aws --endpoint-url=http://localhost:4586 logs describe-log-streams --log-group-name {log-group-name}

aws --endpoint-url=http://localhost:4586 logs get-log-events --log-group-name {log-group-name} --log-stream-name {log-stream-name}

**Comment by miron4dev** [comment]
Did you find a solution?

**Comment by whummer** [comment]
Thanks for reporting @PragyaU . This could potentially be related to a region mismatch. Please note that LocalStack uses a configuration option `DEFAULT_REGION` which is used to define the region that should be used to create resources on the server side - by default this region is `us-east-1`.

Can you please double-check that your terminal with the `aws` commands is configured with the same region (`AWS_DEFAULT_REGION=us-east-1`)? Hope that helps, please let us know. Thanks
