### ISSUE TITLE
Support for intrinsic functions

### ISSUE THREAD

**Issue by Chris5732** [localstack/localstack#1395]
We're trying to use our cloudformation templates with the latest docker version of localstack, however we keep getting errors relating to AWS intrinsic functions. For example when using !Join we get 

```yaml.constructor.ConstructorError: could not determine a constructor for the tag '!Join'```

We've tried using the long form version with a very simple join, e.g.

```
TopicName: Fn::Join
        - '_'
        - - 'AWS'
          - 'DUB'
```
But then get an error saying the topic name is not valid

```An error occurred (InvalidParameterValue) when calling the CreateStack operation: Topic names must be made up of only uppercase and lowercase ASCII letters, numbers, underscores, and hyphens, and must be between 1 and 256 characters long.```

Please can you advise on the use of intrinsic functions in localstack. Thank you

**Comment by russ-dav** [comment]
I am experiencing the same issue. I can only get these functions to work if I write it as follows:
`TopicName:
  Fn::Join: [ '-', [ 'AWS', 'DUB' ] ]`

**Comment by osvaldolove** [comment]
@Chris5732 I am having the same problem with the tags, however I can see you're missing a `:` after your Fn::Join... 

Try this and it should work:
```yaml
      TopicName: 
        Fn::Join:
          - '_'
          - - 'AWS'
            - 'DUB'
```

**Comment by whummer** [comment]
Thanks for providing a fix @osvaldolove . Closing this issue - please re-open if the problem persists @Chris5732 . Thanks
