### ISSUE TITLE
[support] How to verify if lambda functions are being executed from s3 notification ?

### ISSUE THREAD

**Issue by strk** [localstack/localstack#1398]
I'm trying to test an S3 notification triggering a lambda function but don't see any trace of the function being called in the localstack logs. Is there a way to get the logs to print those info ?

What's a recommended practice for debugging lambda function invocations ?

**Comment by stijnvanpoucke** [comment]
+1 Got the same question

**Comment by whummer** [comment]
Thanks for reporting @strk @stijnvanpoucke . If you start the latest version of LocalStack with `DEBUG=1` enabled, you should see the Lambda invocations being triggered.

Also, the Lambda invocation logs are now being sent to CloudWatch (just like in real AWS) - you can check the results/logs by querying local CloudWatch directly.

Closing this issue - please re-open if the problem persists. Thanks
