### ISSUE TITLE
Maven central releases vs docker image versions - code/image incompatibility

### ISSUE THREAD

**Issue by danieljamesscott** [localstack/localstack#1402]
I'm a little confused by the version numbering. The latest version available in maven central is `0.1.22`, which doesn't correspond with a number I can find anywhere else. The [Releases](https://github.com/localstack/localstack/releases) page looks fairly out of date, and the [docker images](https://hub.docker.com/r/localstack/localstack/tags) seem to match up with the changelog in the README.

Is the reason for the java version discrepancy simply because it's only released to maven when there are changes to the java integrations?

The reason I ask is because I've just encountered an issue with an incompatibility with docker images and the version of the code being used. This is caused by the use of `latest` as the default version. I recently cleaned out my docker images, which meant that I moved to the latest image when I next ran my JUnit tests. This caused a problem due to the filesystem path used in `LocalstackDocker.java`: 

https://github.com/localstack/localstack/blob/master/localstack/ext/java/src/main/java/cloud/localstack/docker/LocalstackDocker.java#L29

So, my code, running version `0.1.19` was looking in the python 2.7 directory, which does not exist in the latest version of the image, since it has been upgraded to python 3.

I have a couple of ideas to fix this issue:

1. Stop defaulting to `latest` for the image name and embed the version in the code.
2. Remove the need to access a version specific path to determine the port config.

**Comment by whummer** [comment]
Thanks for reporting @danieljamesscott .

> Is the reason for the java version discrepancy simply because it's only released to maven when there are changes to the java integrations?

Correct. There's currently no strong coupling between the LocalStack versions and the Maven/Java versions.

By default, the JUnit test runner uses the `latest` image tag. But the `@LocalstackDockerProperties` annotation also allows you to specify a specific Docker image tag:
```
@RunWith(LocalstackTestRunner.class)
@LocalstackDockerProperties(imageTag = "0.10.6")
public class S3FeaturesTest {
```

Closing this issue - please comment here if there are any more questions or issues. Thanks
