### ISSUE TITLE
STS usage XML error

### ISSUE THREAD

**Issue by pentatonicfunk** [localstack/localstack#1409]
I got error below, when trying to getFederationToken via sts (http://localhost:4592)
```
Error parsing XML: xmlns: 'https:\/\/sts.amazonaws.com\/doc\/ 2011-06-15\/' is not a valid URI
```

**Comment by whummer** [comment]
Thanks for reporting @pentatonicfunk . This should be fixed in #2369 - can you please give it a try with the latest version of the Docker image? Please report here if the problem persists. Thanks!
