### ISSUE TITLE
Support apigatewayv2

### ISSUE THREAD

**Issue by 0num4** [localstack/localstack#1419]
I want to create websocket api gateway

`aws apigateway create-rest-api --profile localstack --region us-east-1 --name 'API Test' --endpoint-url=http://localhost:4567`
OK

`aws apigatewayv2 create-api --profile localstack --name "myWebSocketApi2" --protocol-type WEBSOCKET --route-selection-expression '$request.body.action'  --region us-east-1 --endpoint-url=http://loc
alhost:4567`
NotFound

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-104) by [Unito](https://www.unito.io/learn-more)

**Comment by elver** [comment]
Seconding this request.

**Comment by Antnee** [comment]
We're currently developing a websocket API with API Gateway and Lambda. I'm just going through creating a script to set everything up when we do a `docker-compose up`, and I've come up against this problem myself. It looks as though Localstack doesn't support websockets yet, as it appears that this requires the `apigatewayv2` command:

```
awslocal apigatewayv2 create-api \
    --region ${REGION} \
    --name "${API_NAME}" \
    --protocol-type WEBSOCKET \
    --route-selection-expression '$request.body.action'
```

> localstack_1      | ERROR: Unable to find LocalStack endpoint for service "apigatewayv2"

Is this on a roadmap for development, maybe? Only available in Pro? Something else?

**Comment by rgrzesk** [comment]
Hi,

Any news on that? I am struggling with creating ``apigatewayv2`` with HTTP protocol, but it seems it is not supported.
When trying to create it using AWS CLI inside localstack I am getting:

```
An error occurred (404) when calling the CreateApi operation: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.</p>
```

**Comment by philippmalkov** [comment]
Is Premium access the cause of this?

> In addition to the above, the Pro version of LocalStack supports additional APIs and advanced 
> features, including:
> 
> - API Gateway V2 (WebSockets support)

This quote from home README

**Comment by thrau** [comment]
This feature is available in LocalStack pro. Should you have problems with the pro version, please let us know in Slack, thanks!
