### ISSUE TITLE
AWS Batch support

### ISSUE THREAD

**Issue by jumarko** [localstack/localstack#1421]
It'd be great if localstack supported AWS batch clone running on a local machine.
We use AWS batch for long-running tasks and it's such a pain for development.
I always have to build a new docker image, upload it to my devel ECR repository and only then I can test my changes from another component.
It would be a massive improvement to have a "mock" for AWS batch running locally - lot faster, easier to debug, etc.

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-105) by [Unito](https://www.unito.io/learn-more)

**Comment by thrau** [comment]
This feature is available in LocalStack pro. Should you have problems with the pro version, please let us know in Slack, thanks!
