### ISSUE TITLE
DynamoDB mock does not honour --return-consumed-capacity flag (since 0.5)

### ISSUE THREAD

**Issue by qbnut** [localstack/localstack#143]
# Summary
Since the change to DynamoDBLocal in 0.5, requesting to return consumed capacity as part of a DynamoDB request does not return a ConsumedCapacity structure in the result payload.

The usage notes for DynamoDBLocal from Amazon (http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocal.UsageNotes.html) does say that the values might be returned as null (as it's a mock)...
```
"In operation responses, nulls are returned instead of capacity units."
```
...however the JSON structure that represents it is instead completely absent. As a result, existing code that I have that checks these values on selected requests does not work against localstack from 0.5.0 upwards. This code of course works fine against AWS itself.

The bug can be triggered via the AWS CLI:

# AWS CLI
```
$ aws --endpoint-url=http://aws.local:4569 dynamodb get-item --table-name=<tablename> --key='{"Id": { "S": "<id>" }}' --return-consumed-capacity=TOTAL
```

This results in a HTTP POST to the DynamoDB endpoint in localstack that looks like this:
```
POST / HTTP/1.1
X-Amz-Target: DynamoDB_20120810.GetItem
Content-Type: application/x-amz-json-1.0

{"ConsistentRead":true,"Key":{"Id":{"S":"<id>"}},"ReturnConsumedCapacity":"TOTAL","TableName":"<tablename>"}
```

# In 0.4.x:
The 'ConsumedCapacity' structure in the JSON payload is appended if it was asked for in the request.

This is what I would class as the expected behaviour.
```
{
    "Item": {
        "Count": {
            "S": "0"
        }, 
        "Data": {
            "S": "<payload>"
        }, 
        "Id": {
            "S": "<id>"
        }
    }, 
    "ConsumedCapacity": {
        "CapacityUnits": 0.5, 
        "TableName": "<tablename>"
    }
}
```

# In 0.5.0 and above:
The 'ConsumedCapacity' structure in the JSON payload is absent.

Therefore any SDK code that asks for it, thus expected it in the result and subsequently tried to deserialize it fails:
```
{
    "Item": {
        "Count": {
            "S": "0"
        }, 
        "Data": {
            "S": "<payload>"
        }, 
        "Id": {
            "S": "<id>"
        }
    }
}
```

**Comment by whummer** [comment]
Thanks for reporting @qbnut , this should be fixed in https://github.com/localstack/localstack/pull/202 . (The Docker image is currently being built and pushed: https://travis-ci.org/localstack/localstack/builds/257188504)

Can you please give it a try with the latest version? Thanks

**Comment by whummer** [comment]
Closing this issue, please re-open if the problem persists.
