### ISSUE TITLE
Localstack exits with no error message or none-0 exit code

### ISSUE THREAD

**Issue by Logibox** [localstack/localstack#1433]
```
$ SERVICES=sns,sqs localstack start
Starting local dev environment. CTRL-C to quit.
Ready.
$ echo $?
0
```
I only require sns and sqs to be running, unsure how to debug this further - any advice?

**Comment by whummer** [comment]
Thanks for reporting @Logibox . This should be fixed in the meantime, default configuration is to start up in Docker now. Can you please give it a try after upgrading to the latest version:
```
$ pip install --upgrade --no-cache localstack
$ docker pull localstack/localstack
$ SERVICES=sns,sqs localstack start
```
Closing this issue - please re-open if the problem persists. Thanks
