### ISSUE TITLE
CloudWatch LogStream CreationTime should be long instead of floating point

### ISSUE THREAD

**Issue by gsfataviva** [localstack/localstack#1434]
The CreationTime of a CloudWatch LogStream should be a long but it is currently a floating point.

To see the issue execute these AWS CLI commands:-

```
aws --endpoint-url http://localhost:4586 logs create-log-group --log-group-name test1

aws --endpoint-url http://localhost:4586 logs create-log-stream --log-group-name test1 --log-stream-name 20190722

aws --endpoint-url http://localhost:4586 logs describe-log-streams --log-group-name test1

```
The result is:-

```
{
    "logStreams": [
        {
            "logStreamName": "20190722",
            "creationTime": 1563778930313.721,
            "arn": "arn:aws:logs:eu-west-1:0:log-group:test1:log-stream:20190722",
            "storedBytes": 0
        }
    ]
}
```
Note that the LocalStack creationTime is a float. The value returned by AWS is a long. See the examples in https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_DescribeLogGroups.html that show that the creationTime is a long.

The consequence is that libraries (e.g. Amazon's AWS SDK for .NET https://aws.amazon.com/sdk-for-net/) that use the AWS API fail because they cannot convert the creationTime to a date.

**Comment by jellybeat** [comment]
I confirm this affects also the Java SDK, causing the following exception:
```
Caused by: java.lang.NumberFormatException: For input string: "1.574371833583149E12"
```

**Comment by whummer** [comment]
Thanks for reporting @gsfataviva @jellybeat . This should be fixed in the latest version - please report here if the problem persists. Thanks
```
$ ...
$ awslocal logs describe-log-streams --log-group-name test1
{
    "logStreams": [
        {
            "logStreamName": "20190722",
            "creationTime": 1583691777058,
            "arn": "arn:aws:logs:eu-east-1:0:log-group:test1:log-stream:20190722",
            "storedBytes": 0
        }
    ]
}
```

**Comment by gsfataviva** [comment]
Great. Many thanks, @whummer :-).
