### ISSUE TITLE
Messages published from SNS topic to HTTP subscribers don't contain needed headers

### ISSUE THREAD

**Issue by Igor-G** [localstack/localstack#144]
Messages published from some SNS Topic to the HTTP subscribers don't contain the 'x-amz-sns-message-type=Notification' header. 
By not having this header, messages are filtered out on the consumer side (don't get to the handler of the message). In our case the consumer is a Java Spring application using the 'Spring Cloud AWS' project.

This issue might also be related to https://github.com/atlassian/localstack/issues/137

**Comment by Igor-G** [comment]
[This commit](https://github.com/Igor-G/localstack/commit/956234d5d04b1b028abc11c20924bdf35acb7475) (on my fork) fixes this issue. But since I'm not a Python developer, I cannot fulfill all the requirements from the [Contributing](https://github.com/atlassian/localstack#contributing) section. If someone is interested, can have a look at the commit and add the other required things for a PR.

**Comment by whummer** [comment]
Thanks for reporting @Igor-G . Since this is a minor change, I don't think we'll need additional tests for it. I'd be happy to merge your change, can you please open a pull request? Thanks

**Comment by Igor-G** [comment]
@whummer I created the PR for the master https://github.com/localstack/localstack/pull/145  (not sure that's right :) )

**Comment by whummer** [comment]
Thanks!
