### ISSUE TITLE
Presigned S3 URLs do not respect HOSTNAME_EXTERNAL and HOSTNAME variables

### ISSUE THREAD

**Issue by vlttnv** [localstack/localstack#1440]
I'm running localstack using docker.
I've set the env variables: `HOSTNAME_EXTERNAL` and `HOSTNAME` to `localhost` and `USE_SSL` to `false`.
When requesting a signed URL for upload to S3 I get: `"https://localstack:4572/local_bucket/duck.png...`

Here's part of the docker-compose file.
```
  localstack:
    image: localstack/localstack
    ports:
      - "4567-4584:4567-4584"
      - "8080:8080"
    environment:
      - SERVICES=s3
      - HOSTNAME_EXTERNAL=localhost
      - HOSTNAME=localhost
      - USE_SSL=false
      - START_WEB=1
      - DATA_DIR=/tmp/localstack/data
      - DEBUG=1
    volumes:
      - "/tmp/localstack:/tmp/localstack"
```

**Comment by FStolte** [comment]
I have the same problem: `USE_SSL` is set to `false`, but the generated URL starts with `https`.

**Comment by jberry92** [comment]
Getting this same issue any word on a fix?

**Comment by whummer** [comment]
Thanks for reporting @vlttnv @FStolte @jberry92 . This appears to be fixed in the meantime.

Using the docker-compose config you posted, I'm getting:
```
$ awslocal s3 mb s3://test
make_bucket: test
$ awslocal s3 presign s3://test/foo
http://localhost:4572/test/foo?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=_not_needed_locally_%2F20200104%2Feu-central-1%2Fs3%2Faws4_request&X-Amz-Date=20200104T104952Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=host&X-Amz-Signature=b336f7f5af3b56d0154443393cbef6984eef8ad2e3d72c2cfafa56602d9d4201
```

Closing this issue - please re-open with exact steps to reproduce if the problem persists. Thanks!
