### ISSUE TITLE
Support AWS Glue

### ISSUE THREAD

**Issue by zhaoyi0113** [localstack/localstack#1446]
I would be great if it supports AWS Glue

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-106) by [Unito](https://www.unito.io/learn-more)

**Comment by dallinb** [comment]
This issue has been duplicated by #3139 and marked as available-in-pro.  I have a professional subscription (it's awesome and I'll be renewing my annual subscription at the end of this month), however I can't find any mention of Glue support (other than "Details following soon.").  Am I missing something?

**Comment by mt-rpranata** [comment]
Is there any Glue services currently supported @dallinb? For example, AWS Glue Data Catalog (sans the crawler)? 
We are not subscribed to Pro yet at this point but might consider if there is AWS Glue Data Catalog service supported.

**Comment by dallinb** [comment]
Hi @mt-rpranata,

Sorry for the delay in getting back to you.  I have started my Docker container with `SERVICES` set to `glue,iam,s3`.  After doing this, I can run the following command `awslocal glue list-jobs` which have the following output:

```json
{
    "JobNames": []
}
``` 

Which suggests that the API is supported.

**Comment by mt-rpranata** [comment]
Thanks for getting back to me @dallinb. 

We are more interested in the Glue Catalog, do you think that only Glue Jobs are supported at the moment?

**Comment by appunni-dishq** [comment]
Is there any ETA on when can we see this in Pro version ?

**Comment by danw-mpl** [comment]
We're having mixed results with this.  Example:

```python
import boto3

client = boto3.client('glue', region_name='eu-west-1', endpoint_url='http://localhost:4566')

# Works
client.get_crawler(Name='crawler_name')

# 2021-09-22T14:17:59:INFO:localstack_ext.services.glue.glue_listener: Unsupported Glue API method "StartCrawler"
client.start_crawler(Name='crawler_name')

# 2021-09-22T14:16:17:INFO:localstack_ext.services.glue.glue_listener: Unsupported Glue API method "GetCrawlers"
client.get_crawlers()

# AttributeError: 'dict' object has no attribute 'value'
client.get_databases()
```

**Comment by whummer** [comment]
Thanks for reporting @danw-mpl @appunni-dishq @dallinb @mt-rpranata . We have now pushed a couple of enhancements for Glue (incl. basic API endpoints, importing Glue data catalogs from Athena, etc.) available in the Pro version (please make sure to pull the `latest` Docker image).

Full support for Glue crawlers is on our roadmap - we should be able to provide an update over the next 1-2 weeks. 👍 

Hope that helps - keep us posted how it goes. Closing this issue - please feel free to re-open (or open a new issue) in case you're experiencing any problems. Thanks for your help!

**Comment by ekeric13** [comment]
Are there any plans to support glue in the community version?
Specifically the glue schema registry as it integrates with MSK/kafka.
