### ISSUE TITLE
Pytest container to run against localstack container - [Errno 111] Connection refused - plz help

### ISSUE THREAD

**Issue by LEscobar-Driver** [localstack/localstack#1447]
I have 2 services in my docker-compose file. I have a localstack container and a pytest container. My localstack image boots up and them my pytest image is supposed to run against my localstack localhost endpoints but my pyests all fail due to this error 

`E   urllib3.exceptions.NewConnectionError: <botocore.awsrequest.AWSHTTPConnection object at 0x7fcf35fa36d0>: Failed to establish a new connection: [Errno 111] Connection refused`

**docker-compose.yml**

    version: "2.1"
    services:
      localstack:
        image: localstack/localstack
         container_name: localstack
        user: root
        ports:
          - '4563-4584:4563-4584'
          - '8055:8080'
        environment:
          - SERVICES=s3,es
          - DEBUG=0
          - DEFAULT_REGION=us-west-2
          - DATA_DIR=/tmp/localstack/data
          - HOSTNAME=localhost
          - LAMBDA_EXECUTOR=local
          - DOCKER_HOST=unix:///var/run/docker.sock
        volumes:
          - ./.localstack:/tmp/localstack
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:4571"]
            interval: 15s
            timeout: 20s
            retries: 5

      integrations:
        container_name: Integration_Tests
        build: ./docker_folder
        user: root
        image: 084661642518.dkr.ecr.us-west-2.amazonaws.com/test:latest
        volumes:
          - ./docker_folder:/Integrations
        depends_on:
          localstack:
            condition: service_healthy
        links:
          - localstack

**Dockerfile**

    FROM python:3.7
    COPY ./docker_folder/ /Integrations
    WORKDIR /Integrations
    RUN pip install -r requirements.txt
    CMD pytest -v --tb=short tests/

**Directory Structure**

    docker_folder
    |   tests
    |   |  test_docker.py
    |   |  test_localstack_1.py

**contents of test_localstack_1.py**

    import boto3
    import pytest

    def test_s3(capsys): 
        s3 = boto3.resource('s3', 
                        endpoint_url='http://localhost:4572/',
                        aws_access_key_id='localstack',
                        aws_secret_access_key='localstack',
                        region_name='us-west-2')  # Botocore/boto3 will be patched to use Localstack
        assert len(list(s3.buckets.all())) == 0

**contents of test_docker.py**

    import pytest

    def test_docker_testing_1():
        assert True

**cli cmd**
`$ sudo docker-compose up`

**output**

    Starting localstack ... done
    Recreating Integration_Tests ... done
    Attaching to localstack, Integration_Tests
    localstack      | Starting mock ES service (http port 4578)...
    localstack      | Starting local Elasticsearch (http port 4571)...
    localstack      | Starting mock S3 (http port 4572)...
    localstack      | Ready.
    localstack      | (. .venv/bin/activate; exec bin/localstack start)
    localstack      | Starting local dev environment. CTRL-C to quit.
    localstack      | Starting mock ES service (http port 4578)...
    localstack      | Starting local Elasticsearch (http port 4571)...
    localstack      | Starting mock S3 (http port 4572)...
    localstack      | Ready.
    localstack      | 2019-07-30 20:33:09,939 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
    localstack      | 2019-07-30 20:33:09,942 INFO supervisord started with pid 12
    localstack      | 2019-07-30 20:33:10,947 INFO spawned: 'dashboard' with pid 19
    localstack      | 2019-07-30 20:33:10,952 INFO spawned: 'infra' with pid 20
    localstack      | 2019-07-30 20:33:10,958 INFO success: dashboard entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
    localstack      | (. .venv/bin/activate; bin/localstack web)
    localstack      | (. .venv/bin/activate; exec bin/localstack start)
    localstack      | 2019-07-30 20:33:11,962 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
    localstack      | Starting local dev environment. CTRL-C to quit.
    localstack      | Starting mock ES service (http port 4578)...
    localstack      | Starting local Elasticsearch (http port 4571)...
    localstack      | Starting mock S3 (http port 4572)...
    localstack      | Ready.
    Integration_Tests | ============================= test session starts ==============================
    Integration_Tests | platform linux -- Python 3.7.4, pytest-4.6.3, py-1.8.0, pluggy-0.12.0 -- /usr/local/bin/python
    Integration_Tests | cachedir: .pytest_cache
    Integration_Tests | rootdir: /Integrations, inifile: pytest.ini
    Integration_Tests | plugins: cov-2.7.1
    Integration_Tests | collecting ... collected 2 items
    Integration_Tests | 
    Integration_Tests | tests/test_docker.py::test_docker_testing_1 PASSED                       [ 50%]
    Integration_Tests | tests/test_localstack_1.py::test_s3 FAILED                               [100%]
    Integration_Tests | 
    Integration_Tests | =================================== FAILURES ===================================
    Integration_Tests | ___________________________________ test_s3 ____________________________________
    Integration_Tests | /usr/local/lib/python3.7/site-packages/urllib3/connection.py:160: in _new_conn
    Integration_Tests |     (self._dns_host, self.port), self.timeout, **extra_kw)
    Integration_Tests | /usr/local/lib/python3.7/site-packages/urllib3/util/connection.py:80: in create_connection
    Integration_Tests |     raise err
    Integration_Tests | /usr/local/lib/python3.7/site-packages/urllib3/util/connection.py:70: in create_connection
    Integration_Tests |     sock.connect(sa)
    Integration_Tests | E   ConnectionRefusedError: [Errno 111] Connection refused

**Comment by ciaranevans** [comment]
Try to remove `- HOSTNAME=localhost` in your docker-compose and use http://localstack:4572 in your test.

That's how I've got it working

**Comment by LEscobar-Driver** [comment]
My problem was in the contents of test_localstack_1.py. 

Change url endpoint from `endpoint_url='http://localhost:4572/'` to `http://docker.for.mac.localhost:4572`
