### ISSUE TITLE
Request: Support Step Function State machines through Api Gateway

### ISSUE THREAD

**Issue by dglsparsons** [localstack/localstack#1451]
**Overview**

In AWS it is possible to trigger step functions through an API Gateway integration, see https://docs.aws.amazon.com/step-functions/latest/dg/tutorial-api-gateway.html

Similar integrations already occur within localstack, however the step function URIs are notably missing. See lines 66-88 of https://github.com/localstack/localstack/blob/master/localstack/services/apigateway/apigateway_listener.py

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-107) by [Unito](https://www.unito.io/learn-more)

**Comment by whummer** [comment]
Thanks for reporting @dglsparsons . It's been a while since this request has been raised, but support has now been added in #3329 . Can you please pull the `latest` Docker image and give it another try? Please report here if the problem persists. Thanks

**Comment by dglsparsons** [comment]
Hey, thanks for closing this. Sadly I can't test it because I've moved onto a different project now, but I appreciate your effort!
