### ISSUE TITLE
Cannot Delete Binary Objects 

### ISSUE THREAD

**Issue by Amr-Abouelleil-bose** [localstack/localstack#1452]
I have encountered a problem very similar to this [previously reported issue](https://github.com/localstack/localstack/issues/371). I am also using the aws go sdk, and am dealing with binary data. In this case, I also do not have any problem with the PutObject call, but the problem occurs when deleting the objects that were previously put using the aws DeleteObjects API.
Here's the logs reporting the error from the microservice I'm building:
```
ERRO[1148] [method: main.requestError] [msg: SerializationError: failed to unmarshal error message
	status code: 500, request id: , host id: 
caused by: UnmarshalError: failed to unmarshal error message
	00000000  3c 21 44 4f 43 54 59 50  45 20 48 54 4d 4c 20 50  |<!DOCTYPE HTML P|
00000010  55 42 4c 49 43 20 22 2d  2f 2f 57 33 43 2f 2f 44  |UBLIC "-//W3C//D|
00000020  54 44 20 48 54 4d 4c 20  33 2e 32 20 46 69 6e 61  |TD HTML 3.2 Fina|
00000030  6c 2f 2f 45 4e 22 3e 0a  3c 74 69 74 6c 65 3e 35  |l//EN">.<title>5|
00000040  30 30 20 49 6e 74 65 72  6e 61 6c 20 53 65 72 76  |00 Internal Serv|
00000050  65 72 20 45 72 72 6f 72  3c 2f 74 69 74 6c 65 3e  |er Error</title>|
00000060  0a 3c 68 31 3e 49 6e 74  65 72 6e 61 6c 20 53 65  |.<h1>Internal Se|
00000070  72 76 65 72 20 45 72 72  6f 72 3c 2f 68 31 3e 0a  |rver Error</h1>.|
00000080  3c 70 3e 54 68 65 20 73  65 72 76 65 72 20 65 6e  |<p>The server en|
00000090  63 6f 75 6e 74 65 72 65  64 20 61 6e 20 69 6e 74  |countered an int|
000000a0  65 72 6e 61 6c 20 65 72  72 6f 72 20 61 6e 64 20  |ernal error and |
000000b0  77 61 73 20 75 6e 61 62  6c 65 20 74 6f 20 63 6f  |was unable to co|
000000c0  6d 70 6c 65 74 65 20 79  6f 75 72 20 72 65 71 75  |mplete your requ|
000000d0  65 73 74 2e 20 20 45 69  74 68 65 72 20 74 68 65  |est.  Either the|
000000e0  20 73 65 72 76 65 72 20  69 73 20 6f 76 65 72 6c  | server is overl|
000000f0  6f 61 64 65 64 20 6f 72  20 74 68 65 72 65 20 69  |oaded or there i|
00000100  73 20 61 6e 20 65 72 72  6f 72 20 69 6e 20 74 68  |s an error in th|
00000110  65 20 61 70 70 6c 69 63  61 74 69 6f 6e 2e 3c 2f  |e application.</|
00000120  70 3e 0a                                          |p>.|

caused by: expected element type <Error> but have <title>] 
```
Any help/advice would be appreciated.

**Comment by puppeteer701vungle** [comment]
Also came across this issue.

**Comment by whummer** [comment]
@Amr-Abouelleil-bose @puppeteer701vungle Thanks for reporting. Can you please provide a short self-contained Go sample project to reproduce this issue? Thanks!

**Comment by ymgyt** [comment]
Hello, I also came across same issue, so I created [sample project](https://github.com/ymgyt/reproduce-localstack-issues-1452) to reproduce this issue.
I hope this helps you.

## Reproduce Steps

```
$ git clone https://github.com/ymgyt/reproduce-localstack-issues-1452.git
$ cd reproduce-localstack-issues-1452
$ docker-compose up --detach
# waiting localstack s3 ready...
$ go run main.go
delete error SerializationError: failed to unmarshal error message
	status code: 500, request id: , host id:
caused by: UnmarshalError: failed to unmarshal error message
	00000000  3c 21 44 4f 43 54 59 50  45 20 48 54 4d 4c 20 50  |<!DOCTYPE HTML P|
00000010  55 42 4c 49 43 20 22 2d  2f 2f 57 33 43 2f 2f 44  |UBLIC "-//W3C//D|
00000020  54 44 20 48 54 4d 4c 20  33 2e 32 20 46 69 6e 61  |TD HTML 3.2 Fina|
00000030  6c 2f 2f 45 4e 22 3e 0a  3c 74 69 74 6c 65 3e 35  |l//EN">.<title>5|
00000040  30 30 20 49 6e 74 65 72  6e 61 6c 20 53 65 72 76  |00 Internal Serv|
00000050  65 72 20 45 72 72 6f 72  3c 2f 74 69 74 6c 65 3e  |er Error</title>|
00000060  0a 3c 68 31 3e 49 6e 74  65 72 6e 61 6c 20 53 65  |.<h1>Internal Se|
00000070  72 76 65 72 20 45 72 72  6f 72 3c 2f 68 31 3e 0a  |rver Error</h1>.|
00000080  3c 70 3e 54 68 65 20 73  65 72 76 65 72 20 65 6e  |<p>The server en|
00000090  63 6f 75 6e 74 65 72 65  64 20 61 6e 20 69 6e 74  |countered an int|
000000a0  65 72 6e 61 6c 20 65 72  72 6f 72 20 61 6e 64 20  |ernal error and |
000000b0  77 61 73 20 75 6e 61 62  6c 65 20 74 6f 20 63 6f  |was unable to co|
000000c0  6d 70 6c 65 74 65 20 79  6f 75 72 20 72 65 71 75  |mplete your requ|
000000d0  65 73 74 2e 20 45 69 74  68 65 72 20 74 68 65 20  |est. Either the |
000000e0  73 65 72 76 65 72 20 69  73 20 6f 76 65 72 6c 6f  |server is overlo|
000000f0  61 64 65 64 20 6f 72 20  74 68 65 72 65 20 69 73  |aded or there is|
00000100  20 61 6e 20 65 72 72 6f  72 20 69 6e 20 74 68 65  | an error in the|
00000110  20 61 70 70 6c 69 63 61  74 69 6f 6e 2e 3c 2f 70  | application.</p|
00000120  3e 0a                                             |>.|

caused by: expected element type <Error> but have <title>
```

## versions

localstack docker image: `localstack/localstack:0.10.6`
go version: `1.13`
aws-sdk-go: `v1.29.4`

**Comment by whummer** [comment]
Thanks for reporting @Amr-Abouelleil-bose @ymgyt @puppeteer701vungle . This looks like an issue with the SDK configuration - please note that LocalStack requires all S3 SDKs to be configured to use *path style addressing* instead of the default virtual host name based addressing.

See also the Troubleshooting section in the README: https://github.com/localstack/localstack#troubleshooting

Please report here if the problem persists. Thanks

**Comment by Nasrin-Shiraly** [comment]
> Thanks for reporting @Amr-Abouelleil-bose @ymgyt @puppeteer701vungle . This looks like an issue with the SDK configuration - please note that LocalStack requires all S3 SDKs to be configured to use **path style addressing** instead of the default virtual host name based addressing.
> 
> See also the Troubleshooting section in the README: https://github.com/localstack/localstack#troubleshooting
> 
> Please report here if the problem persists. Thanks

Encountering the same issue on DeleteObjects. And just wanted to note that:
According to [Docs] (https://docs.aws.amazon.com/AmazonS3/latest/dev/VirtualHosting.html)

> Buckets created after September 30, 2020, will support only virtual hosted-style requests. Path-style requests will continue to be supported for buckets created on or before this date.

**Comment by dimpogissou** [comment]
Encountering the exact same issue with AWS Go SDK `v1.35.7,` using `S3ForcePathStyle: aws.Bool(true)` when building the client and localstack:latest image.
