### ISSUE TITLE
Docker exec wait time too short for travis

### ISSUE THREAD

**Issue by benwaffle** [localstack/localstack#1456]
I am using the docker test runner on travis ci. It was failing without a clear reason, but I think the problem is that `docker run` takes too long because it has to pull the docker image. Please consider increasing the `DEFAULT_WAIT_TIME_MINUTES` in `cloud.localstack.docker.DockerExe`.

I fixed it by setting `pullNewImage = true` in LocalstackDockerConfiguration

**Comment by whummer** [comment]
Thanks for reporting @benwaffle . This change has been added in #1901 - we'll publish it with the next release of the Java libs. Thanks
