### ISSUE TITLE
[S3] File is saved to bucket even if hash verification failed

### ISSUE THREAD

**Issue by MikkCZ** [localstack/localstack#1462]
Fighting with #1305 we have noticed that in a situation when the hash verification fails and LocalStack S3 responds with an error to the client, however the file is saved to the bucket, which should not in real AWS S3.

STR:
# Prepare a client and a file, that fails hash verification when put to S3 (e.g. reproduce #1305).
# Put the file to S3.
# The request fails on hash verification.

What should happen:
- Client receives an error in response and the bucket content stays unchanged - no file is saved.

What actually happens:
- Client does receive an error in response, but the file is saved to the bucket (its malformed version which server computed hash from) and available for anyone to read.

**Comment by whummer** [comment]
Thanks for reporting @MikkCZ . Issue #1305 has been fixed in the meantime, and the verification mechanism should now work properly. If the problem persists, please help us by providing a small, self-contained example to reproduce the issue. Thanks!
