### ISSUE TITLE
[SQS] ssl3_get_record:wrong version number

### ISSUE THREAD

**Issue by DominikPalo** [localstack/localstack#1464]
I'm using the latest version od localstack on Windows computer (docker mode) and when I try to pull messages from SQS using the official Node.js [AWS SDK](https://www.npmjs.com/package/aws-sdk) by calling `sqs.receiveMessage()` it fails with the error:
```
error:  Error: write EPROTO 12128:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:c:\ws\deps\openssl\openssl\ssl\record\ssl3_record.c:332:

    at WriteWrap.afterWrite [as oncomplete] (net.js:788:14)
```

**Comment by shavo007** [comment]
i get this issue @DominikPalo , how you fix it??

**Comment by MartinCerny-awin** [comment]
My issue was that I was connecting to https, but the service was running on http

**Comment by DenizBabat** [comment]
If your server is running with http and your client is running with https, you get this error. If you  check your both server and client http protocol, you can solve this issue.
