### ISSUE TITLE
What's the process to test APIGateway? 

### ISSUE THREAD

**Issue by netmailgopi** [localstack/localstack#1475]
I'm putting localstack to work for my team on windows, writing some docs so they can easily hop on it. Right now I run localstack with docker like (fyi)

`
   docker run -it -e LOCALSTACK_HOSTNAME="localhost"
   --platform "linux" -p 8080:8080 -p 4567-4585:4567-4585 
   -p 4590-4593:4590-4593 
   -v "C:\Users\gopiravi\AppData\Local\Temp\localstack:/tmp/localstack" 
   -v "C:\Users\gopiravi\AppData\Local\Temp:/var/run/docker.sock" 
   -e HOST_TMP_FOLDER="C:\Users\gopiravi\AppData\Local\Temp\localstack" 
   -e SERVICES="s3,sns,sqs,dynamodb,apigateway,cloudformation,iam,sts,cloudwatch" 
   --memory "2g" "localstack/localstack"
`

So the services are up. I was able to deploy a serverless.template to local cloudformation and test a lambda. I have this api-gateway project now and I did deploy it to local cloudformation - not sure how to hit the rest endpoint.

I hit http://localhost:4567/restapis/ and I get
`
{"item": [{"id": "1742025A-Z13", "name": "VotingService", "description": null, "createdDate": 1565388326}]}
`

I hit http://localhost:4567/restapis/1742025A-Z13 I get

`
{"id": "1742025A-Z13", "name": "VotingService", "description": null, "createdDate": 1565388356}
`

I named the apigateway stage as "alpha" but I can't see that in here though. Do I need to create resources, put-integration, put-method like talked about in https://github.com/localstack/localstack/issues/229#issue-247453666 ? I was under the impression that cloudformation deploy of the template would do all that.

**Comment by whummer** [comment]
Hi @netmailgopi , thanks for reporting.

Generally, LocalStack uses a certain URL pattern that includes `_user_request_` to expose invokable API endpoints. For example, if you deploy a Serverless project, it will print the endpoints in the final output like so:
```
$ serverless deploy --stage local
endpoints:
  GET - http://localhost:4567/restapis/h13u15iuhp/local/_user_request_/api/v1/{user_id}/data
...
```

Can you please share the relevant portion of your code/configuration, to help making this issue easier to reproduce? Thanks
