### ISSUE TITLE
Feature Request: S3:  Persistent Data

### ISSUE THREAD

**Issue by theskipster** [localstack/localstack#148]
Is it possible to have persistent data in the S3 bucket?  I would love to be able to initiate the environment with some files already in the S3 bucket.

Is there an alternative method to getting data into S3?

**Comment by theskipster** [comment]
This is a duplicate of #77, you can close.

**Comment by whummer** [comment]
Thanks for the follow up @theskipster . The current solution is only a workaround, but advanced support for data persistence is definitely on our roadmap, stay tuned!

**Comment by leonardoborges** [comment]
@whummer any updates on this feature?
