### ISSUE TITLE
Localstack error response code is incorrect for kinesis

### ISSUE THREAD

**Issue by nullhappens** [localstack/localstack#1480]
Looking at the kinesis implementation, specifically this line https://github.com/localstack/localstack/blob/master/localstack/services/kinesis/kinesis_listener.py#L137 it would seem that for any PUT_RECORDS operation the response code will be 200 which the java aws sdk will treat as a non exception.  Im curious as to why the status code is set to 200?

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-110) by [Unito](https://www.unito.io/learn-more)

**Comment by whummer** [comment]
Thanks for reporting @nullhappens - it's been a while since this request has been raised, and it should be fixed in the meantime. Please let us know if the problem persists with the `latest` version of the Docker image. Thanks
