### ISSUE TITLE
java.lang.RuntimeException:java.lang.IllegalStateException

### ISSUE THREAD

**Issue by vkolluru15** [localstack/localstack#1484]
When running local stack through maven mvn clean install -P integration-test I am getting the following error

`java.lang.RuntimeException: 
java.lang.IllegalStateException: Failed to run command 'bash -c cd "/tmp/localstack_install_dir"; make install', return code 2.
STDOUT: make setup-venv && \
	(test ! -e requirements.txt || (. .venv/bin/activate; pip -q install -r requirements.txt && \
		PYTHONPATH=. exec python localstack/services/install.py testlibs)) || exit 1
make[1]: Entering directory '/tmp/localstack_install_dir'
(test `which virtualenv` || pip install --user virtualenv) && \
	(test -e .venv || virtualenv  .venv)
make[1]: Leaving directory '/tmp/localstack_install_dir'
ERROR: 'javac -source 1.8 -target 1.8 -cp "/tmp/localstack_install_dir/localstack/utils/kinesis/java:/tmp/localstack_install_dir/localstack/infra/amazon-kinesis-client/aws-java-sdk-sts.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/jackson-databind-2.6.7.1.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/httpcore-4.4.9.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/checker-qual-2.5.2.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/jackson-annotations-2.6.0.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/jmespath-java-1.11.438.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/commons-lang3-3.7.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/jackson-dataformat-cbor-2.6.7.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/ion-java-1.0.2.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/jackson-core-2.6.7.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/aws-java-sdk-dynamodb-1.11.438.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/aws-java-sdk-s3-1.11.438.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/protobuf-java-2.6.1.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/commons-logging-1.1.3.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/aws-java-sdk-kinesis-1.11.438.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/guava-26.0-jre.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/amazon-kinesis-client-1.9.3.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/animal-sniffer-annotations-1.14.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/jsr305-3.0.2.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/j2objc-annotations-1.1.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/aws-java-sdk-kms-1.11.438.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/aws-java-sdk-cloudwatch-1.11.438.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/aws-java-sdk-core-1.11.438.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/httpclient-4.5.5.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/error_prone_annotations-2.1.3.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/joda-time-2.8.1.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/commons-codec-1.10.jar" /tmp/localstack_install_dir/localstack/utils/kinesis/java/cloud/localstack/*.java': exit code 2; output: javac: invalid source release: 1.8
Usage: javac <options> <source files>
use -help for a list of possible options

Makefile:18: recipe for target 'install' failed

STDERR: DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Traceback (most recent call last):
  File "localstack/services/install.py", line 234, in <module>
    install_amazon_kinesis_client_libs()
  File "localstack/services/install.py", line 158, in install_amazon_kinesis_client_libs
    JAVAC_TARGET_VERSION, JAVAC_TARGET_VERSION, classpath, java_files))
  File "/tmp/localstack_install_dir/localstack/utils/common.py", line 885, in run
    return do_run(cmd)
  File "/tmp/localstack_install_dir/localstack/utils/common.py", line 882, in do_run
    raise e
subprocess32.CalledProcessError: Command 'javac -source 1.8 -target 1.8 -cp "/tmp/localstack_install_dir/localstack/utils/kinesis/java:/tmp/localstack_install_dir/localstack/infra/amazon-kinesis-client/aws-java-sdk-sts.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/jackson-databind-2.6.7.1.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/httpcore-4.4.9.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/checker-qual-2.5.2.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/jackson-annotations-2.6.0.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/jmespath-java-1.11.438.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/commons-lang3-3.7.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/jackson-dataformat-cbor-2.6.7.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/ion-java-1.0.2.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/jackson-core-2.6.7.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/aws-java-sdk-dynamodb-1.11.438.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/aws-java-sdk-s3-1.11.438.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/protobuf-java-2.6.1.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/commons-logging-1.1.3.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/aws-java-sdk-kinesis-1.11.438.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/guava-26.0-jre.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/amazon-kinesis-client-1.9.3.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/animal-sniffer-annotations-1.14.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/jsr305-3.0.2.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/j2objc-annotations-1.1.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/aws-java-sdk-kms-1.11.438.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/aws-java-sdk-cloudwatch-1.11.438.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/aws-java-sdk-core-1.11.438.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/httpclient-4.5.5.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/error_prone_annotations-2.1.3.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/joda-time-2.8.1.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/commons-codec-1.10.jar" /tmp/localstack_install_dir/localstack/utils/kinesis/java/cloud/localstack/*.java' returned non-zero exit status 2
make: *** [install] Error 1
`
Running localstack locally from ~/.local/localstack start works fine.

Can you please advise what should I look into ?

**Comment by whummer** [comment]
Thanks for reporting @vkolluru15 .

> javac: invalid source release: 1.8

Which version of Java are you running? Looks like your JDK cannot compile classes under source level 1.8. Perhaps it would be advisable to upgrade the JDK version.

Apart from that, the Java JUnit test runner has been significantly reworked in the meantime, running LocalStack in Docker is now the default installation. Please give it a try with the latest version of the Java libs, and let us know if the problem persists. Thanks
