### ISSUE TITLE
SQS getQueueUrl returned localhost instead of the host's IP address.

### ISSUE THREAD

**Issue by jianlihenry** [localstack/localstack#1485]
My team has been using Localstack with TestContainers for a long time, and it worked fine. Lately we decided to run our test inside a docker container, and based on this article https://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/, we decide to use docker-by-docker instead of bringing up localstack containers inside the container we run the test. Basically it means the localstack container will run as a sibling with the test container, and they sit on the same network bridge on the actual host.

With this setup, there are a couple things that changed. When the TestContainers created a localstack container, it would dynamically assign an unused port range to map the localstack ports, so that the tests can access localstack by hitting `localhost:forwardedPort`. For example, on the port 3333 is mapped to 4572, which is for S3 in the localstack container, then on the host we can hit `localhost:3333` to access S3. Now, since we are hitting localstack from another container, we can't use `localhost` anymore, because `localhost` now means the container's host name, but the host that the containers run on. For example, if the actual host's IP is 172.20.0.1, the test container's IP is 172.20.0.2, and the localstack's container is 172.20.0.3, you can access localstack's S3 service by either using `172.20.0.1:3333` or `172.20.0.3:4572`. In the test container, if you hit `localhost:3333`, however, you are hitting `172.20.0.2:3333`, which would return connection error.

Now the problem came up. While bringing up the localstack in the test container, we actually successfully built AWS SQS clients with the endpoint that uses the localstack container's IP address, and the SQS client can successfully create queues and get queue urls. However, the queue urls it returned don't have the localstack container's IP address, but `localhost` in it (`http://localhost:xxxx/queue/queueName`), therefore sending message won't work, because there is nothing running on that port on localhost.

In a word, the queue url returned should be consistent with the endpoint configuration of the SQS client.

**Comment by lukasz-lapczyk** [comment]
@jianlihenry Did you try to set the `HOSTNAME_EXTERNAL` environment variable and connect to the localstack's container by its hostname instead of IP address?

**Comment by jianlihenry** [comment]
@lukasz-lapczyk I didn't find a ticket about the same issue https://github.com/testcontainers/testcontainers-java/issues/1102.

Solved by start the container with `withEnv("HOSTNAME_EXTERNAL", container.getContainerIpAddress())`.
