### ISSUE TITLE
[APIGateway] create-api-key returns 500 when tags are supplied

### ISSUE THREAD

**Issue by gdippolito** [localstack/localstack#1495]
The apigateway does not seem to support api key tags at the moment. 

The following code generates a 500 response when run against localstack.
`
awslocal apigateway create-api-key --name dave --tags "env=dev,owner=dave"
`

**Comment by whummer** [comment]
Thanks for reporting @gdippolito . This should be fixed in the latest version:
```
$ awslocal apigateway create-api-key --name dave --tags "env=dev,owner=dave"
{
    "id": "lhy7zzq1d8",
    "value": "is9YCvg2d8SpJ4KVWceG6x05hjrfUbInmlHFMZ7L",
    "name": "dave",
    "enabled": true,
    "createdDate": 1578153748,
    "lastUpdatedDate": 1578153748,
    "tags": {
        "env": "dev",
        "owner": "dave"
    }
}
```
Closing this issue - please report here if the problem persists. Thanks

**Comment by gdippolito** [comment]
Yes, it was fixed by me :P -> https://github.com/spulec/moto/pull/2390

Glad that a tag was released for `moto` and that `localstack` is pointing to that. 

Thanks for verifying the correct behaviour of the new api.
Cheers,
Giulio
