### ISSUE TITLE
Cannot send message to FIFO queue with DelaySeconds parameter

### ISSUE THREAD

**Issue by mclark1129** [localstack/localstack#1503]
If you attempt to send a message to a FIFO queue with a request that contains the `DelaySeconds` parameter, the request fails with an `InvalidParameterValue` response.

This is actually a problem with ElasticMQ, but I'm creating an issue here to track that the version localstack is using gets updated if/when a fix is released.

More Information: https://github.com/softwaremill/elasticmq/issues/273

**Comment by whummer** [comment]
Thanks for reporting @mclark1129 . This should be fixed in the latest version - an integration test has been added in #2227 to cover this functionality.
