### ISSUE TITLE
Localstack not starting because the previous test run did not shut down the container

### ISSUE THREAD

**Issue by tdao407** [localstack/localstack#1505]
Using `LocalstackDockerTestRunner` to run my unit tests does not shut down the `localstack` container sometimes. I'm currently using static ports so when the test runs again, the Localstack does not start because it is waiting on the port. 

Other than using randomPorts, is there a way to force Localstack to start?

Example of the test:

```
@RunWith(LocalstackDockerTestRunner.class)
@ExtendWith(LocalstackDockerExtension.class)
@LocalstackDockerProperties(services = {"s3:4572"})
public class MyTest {
  
    @Test
    public void testMethod() {

    }
}
```

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-112) by [Unito](https://www.unito.io/learn-more)

**Comment by whummer** [comment]
Thanks for reporting @tdao407 . Could the new annotation property `useSingleDockerContainer` help out here? https://github.com/localstack/localstack/blob/f980a0c724ee0d79b59211d40590188129754967/localstack/ext/java/src/main/java/cloud/localstack/docker/annotation/LocalstackDockerConfiguration.java#L37-L38

**Comment by rayjlinden** [comment]
I have the same issue.  Did anyone find a resolution?
