### ISSUE TITLE
Cloudwatch Logs DescribeLogGroups response nextToken format is incorrect

### ISSUE THREAD

**Issue by Jaystified** [localstack/localstack#1527]
Having deployed a large number of lambdas to localstack and enabled cloudwatch logs for all of them, I attempted to retrieve a list of log groups using
`aws logs describe-log-groups --endpoint-url http://localhost:4586 --region us-east-1`
However this only resulted in the following error message:
`Parameter validation failed: Invalid type for parameter nextToken, value: 50, type: <class 'int'>, valid types: <class 'str'>`
If I append `--no-paginate` to the command, I get some of the log groups, and immediately notice the following in the response json: `"nextToken": 50`

I attempted the same on regular aws (ie `aws logs describe-log-groups  --no-paginate`) and saw that the nextToken is actually the name of a log group:
`"nextToken": "/aws/lambda/service-stage-function"`

**Comment by whummer** [comment]
Thanks for reporting @Jaystified . I was able to reproduce this issue - it should be fixed via #1988 . Please report here if the problem persists. Thanks
