### ISSUE TITLE
Invalid type for parameter topicRulePayload.ruleDisabled, value: false, type: <class 'str'>, valid types: <class 'bool'>

### ISSUE THREAD

**Issue by wesselvdv** [localstack/localstack#1530]
Using the new IoT Core implementation in Localstack I am running into this error when deploying a lambda with an iot event:

```
botocore.exceptions.ParamValidationError: Parameter validation failed:

Invalid type for parameter topicRulePayload.ruleDisabled, value: false, type: <class 'str'>, valid types: <class 'bool'>
```

I am not sure if this is an error in the rendering of the cloudformation template by serverless, or if this is being validated too strictly by boto.

This line seems to cause the issue in serverless: https://github.com/serverless/serverless/blob/bd457eeb770796cb795857c8eea8b06d385a020f/lib/plugins/aws/package/compile/events/iot/index.js#L69

**Comment by wesselvdv** [comment]
It seems that the validation is too strict, when deploying the generated cloudformation stack manually on aws works.

**Comment by whummer** [comment]
Thanks, this should be fixed in the `latest` version. Closing this issue, please re-open if the problem persists.
