### ISSUE TITLE
No module found for lamda specific import

### ISSUE THREAD

**Issue by chrisrana** [localstack/localstack#1532]
I have written a lamda which use elasticsearch api

```
import logging
from elasticsearch import ElasticsearchException

LOGGER = logging.getLogger()
LOGGER.setLevel(logging.INFO)


def handler(event, context):
    LOGGER.info("I've been called!")
    return {
        "message": "Hello pytest!"
    }
```
I  am using python 3.6 runtime.I am using docker-compose to install local-stack on my windows 10 machine
I have install elasticsearch in my local pip install elasticsearch 
I am getting No module named 'elasticsearch' error when i invoke the lambda.
How to install lamda specific dependencies  ?

**Comment by ciaranevans** [comment]
Is your lambda running in a docker container?

I.E. `LAMBDA_EXECUTOR=docker` ?

**Comment by ciaranevans** [comment]
If it's `local` or `docker`, I'd recommend zipping up the required pip packages from your Site-Packages dir and uploading that as your lambda.

Something like:
```
    
#!/bin/sh

mkdir deps \
&& pip3 install -r requirements.txt --target ./deps \
&& cp <your-lambda-code> ./deps \
&& cd ./deps \
&& zip -qr lambda.zip .
```

Then upload `lambda.zip`, you should then be able to access your modules

**Comment by chrisrana** [comment]
Thanks it worked @ciaranevans

**Comment by chrisrana** [comment]
Above steps worked for me

**Comment by ciaranevans** [comment]
@chrisrana glad to hear!
