### ISSUE TITLE
InternalFailure: Uploaded Lambda code for runtime (nodejs8.10) is not in Zip format

### ISSUE THREAD

**Issue by explaura** [localstack/localstack#1536]
Hi! I'm trying to mock out a nodejs lambda, however when specifying a local .zip file I am running into the error `InternalFailure: Uploaded Lambda code for runtime (nodejs8.10) is not in Zip format`.

Code to setup the lambda below:
```node
const AWS = require('aws-sdk');

AWS.config.update({
  region: process.env.AWS_REGION,
  secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY,
  accessKeyId: process.env.AWS_ACCESS_KEY_ID,
});

const lambda = new AWS.Lambda({
  endpoint: process.env.LAMBDA_ENDPOINT,
});

const createLambdaParams = {
  FunctionName: 'handler',
  Runtime: 'nodejs8.10',
  Handler: 'index.handler',
};

const createLambdaRole = async () => {
  const roleParams = {
    AssumeRolePolicyDocument: JSON.stringify({
      Statement: [{
        Action: 'lambda:InvokeFunction',
        Resource: [ '*' ],
        Effect: 'Allow',
      }],
    }),
    Path: '/',
    RoleName: 'Test-Role-Lambda',
  };

  try {
    const data = await iam.createRole(roleParams).promise();
    return data.Role.Arn;
  } catch (err) {
    console.error(`Unable to create role: ${err}`);
    throw err;
  }
};

const createLambdas = async () => {
  try {
    const roleArn = await createLambdaRole();
    await lambda.createFunction({
      ...createLambdaParams,
      Role: roleArn,
      Code: {
        ZipFile: 'fileb://index.zip',
      },
    }).promise();
    console.log('Created lambdas');
  } catch (err) {
    console.error(`Unable to create lambdas: ${err}`);
    throw err;
  }
};
```
I zip up the `index.js` file via commadline using `zip index.zip index.js` (on a Mac if that makes a difference?).

`index.js` file below:
```node
exports.handler = function (event, context, callback) {
  console.log(event, context);
  callback(null, 'success');
};
```

When creating the lambda via CLI I don't have any issues and can create the lambda successfully:
```
aws --endpoint-url=http://localhost:4574 lambda create-function --function-name 'Test-Function-123' --runtime 'nodejs8.10' --role 'arn:aws:iam::000000000000:role/Test-Role-Lambda' --handler 'index.handler' --zip-file fileb://index.zip
```

I feel like I've tried everything under the sun (removing `fileb`, using a string and creating a `Buffer` with Base64 encoding...), however it's just not working out 😞. Any help is appreciated!

**Comment by whummer** [comment]
Hi @explaura , the AWS Javascript SDK expects to receive the bytes content of the zip file as the `ZipFile` parameter, see: https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Lambda.html#createFunction-property . Note that there are sometimes slight differences in the different language SDKs versus the CLI usage, so the docs are a good reference in such cases.

**Comment by explaura** [comment]
@whummer thanks for your help. I have also tried using `ZipFile: Buffer.from('index.zip')` and receive the same error (I ensure the file exists first using `fs`). Does the path need to be anything specific, or require a specific form of compression? Can't find any docs about this.

**Comment by whummer** [comment]
@explaura I think `Buffer.from(..)` only creates a `Buffer` object from a string passed as parameter. You'd probably need some combination of `Buffer.from` with `fs.readFileSync`. Sorry, but this is out of scope for LocalStack - I'd assume that the same code would also not run against real AWS. Would be great if you could prepare the code in a way that it works against real AWS, then we can look at any discrepancies with LocalStack. Thanks

**Comment by AliakbarSu** [comment]
@explaura I am facing the same issue. did you manage to solve it?

**Comment by explaura** [comment]
@AliakbarSu nope :/ I had to work around it by using the AWS CLI to create a lambda and pointing it to the Localstack lambda endpoint.

**Comment by AliakbarSu** [comment]
@explaura I managed to get it working by using fs.readFileSync()

```
var code_path =  path.resolve(__dirname, './layer.zip')
var params = {
  Content: {
     ZipFile: fs.readFileSync(code_path)
  }
}
```

complete example
[](https://medium.com/bam-lambda/tutorial-create-an-aws-lambda-function-with-node-js-37da059acaeb)

**Comment by explaura** [comment]
awesome @AliakbarSu well done! I'll keep this in mind for the future!
