### ISSUE TITLE
Feature - Neptune DB

### ISSUE THREAD

**Issue by rkholoniuk** [localstack/localstack#1537]
Any ideas how to integrate Neptune DB ?

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-115) by [Unito](https://www.unito.io/learn-more)

**Comment by btull89** [comment]
According to the readme, Neptune DB is available in the "Pro version of LocalStack".

**Comment by thrau** [comment]
This feature is available in LocalStack pro. Should you have problems with the pro version, please let us know in Slack, thanks!
