### ISSUE TITLE
Support for API Gateway Integration with dynamodb

### ISSUE THREAD

**Issue by aswingit** [localstack/localstack#1546]
I am trying to create an API gateway integration to put record into dynamodb. Looks like this is not supported.  Please consider this as a feature request if it is not yet supported. Please let me know if there are any work around available

**Flow** 
APIGateway -> DynamoDB ->DynamoDBStream -> Lambda -> Elasticsearch

**Error :** 
{"message": "API Gateway integration type \"AWS_PROXY\" for method \"PUT\" not yet implemented"}

**Configuration**
"Uri": {"Fn::Join": ["", ["arn:aws:apigateway:", { "Ref": "AWS::Region" }, ":dynamodb:action/PutItem"]]},

**Comment by whummer** [comment]
Thanks for reporting @aswingit . This should be fixed in #2411 - can you please give it a try with the `latest` version? Please report here if the problem persists. Thanks
