### ISSUE TITLE
EC2 | Can't terminate instance - (InvalidVolume.NotFound)

### ISSUE THREAD

**Issue by yonatanelkad** [localstack/localstack#1550]
Hey,
I'm trying to `terminate_instances` (https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ec2.html#EC2.Client.terminate_instances)
And in result i'm getting this exception:
`botocore.exceptions.ClientError: An error occurred (InvalidVolume.NotFound) when calling the TerminateInstances operation: The volume 'vol-65cfd6a4' does not exist.`

from localstack_client.session import client

client = client("ec2")

def _terminate_instance(instances_list):
    print(instances_list)
    res = client.terminate_instances(
        InstanceIds=instances_list,
    )
    return res

This is the instance object I try to delete:
`{u'Monitoring': {u'State': 'disabled'}, u'StateReason': {u'Message': 'Client.UserInitiatedShutdown: User initiated shutdown', u'Code': 'Client.UserInitiatedShutdown'}, u'PublicDnsName': 'None', u'RootDeviceType': 'ebs', u'State': {u'Code': 48, u'Name': 'terminated'}, u'EbsOptimized': False, u'LaunchTime': datetime.datetime(2019, 9, 8, 6, 32, 57, tzinfo=tzutc()), u'PrivateIpAddress': '10.157.6.48', u'ProductCodes': [], u'StateTransitionReason': 'User initiated (2019-09-09 07:15:11 UTC)', u'InstanceId': 'i-ecfbafa34eb6059e7', u'ImageId': 'ami-123', u'PrivateDnsName': 'ip-10-157-6-48.ec2.internal', u'KeyName': 'localkey', u'SecurityGroups': [{u'GroupId': 'None'}], u'ClientToken': 'ABCDE1234567890123', u'InstanceType': 'c4.large', u'NetworkInterfaces': [{u'Status': 'in-use', u'MacAddress': '1b:2b:3c:4d:5e:6f', u'SourceDestCheck': True, u'Description': 'Primary network interface', u'NetworkInterfaceId': 'eni-2bcc8bd0', u'PrivateIpAddresses': [{u'Primary': True, u'PrivateIpAddress': '10.157.6.48'}], u'Attachment': {u'Status': 'attached', u'DeviceIndex': 0, u'DeleteOnTermination': True, u'AttachmentId': 'eni-attach-787d892f', u'AttachTime': datetime.datetime(2015, 1, 1, 0, 0, tzinfo=tzutc())}, u'Groups': [{u'GroupId': 'None'}], u'OwnerId': '123456789012', u'PrivateIpAddress': '10.157.6.48'}], u'SourceDestCheck': True, u'Placement': {u'Tenancy': 'default', u'GroupName': '', u'AvailabilityZone': 'us-east-1a'}, u'Hypervisor': 'xen', u'BlockDeviceMappings': [{u'DeviceName': '/dev/sda1', u'Ebs': {u'Status': 'in-use', u'DeleteOnTermination': False, u'VolumeId': 'vol-65cfd6a4', u'AttachTime': datetime.datetime(2019, 9, 8, 6, 32, 57, tzinfo=tzutc())}}], u'Architecture': 'x86_64', u'KernelId': 'None', u'RootDeviceName': '/dev/sda1', u'VirtualizationType': 'paravirtual', u'Tags': [], u'AmiLaunchIndex': 0}`

**Comment by yonatanelkad** [comment]
Solved this issue by creating this instance with:
`        BlockDeviceMappings=[
            {
                'Ebs': {
                    'DeleteOnTermination': True
                }
            }]
`

**Comment by whummer** [comment]
Thanks for reporting, and for posting the workaround. This should be fixed in #2845 - can you please give it another try with the `latest` version of the Docker image. Please report here if the problem persists. Thanks
