### ISSUE TITLE
Kinesis to S3 file structure not correct

### ISSUE THREAD

**Issue by alphawolf1988** [localstack/localstack#1554]
For Kinesis, it seems to be, that AWS organizes its folders on S3 like: "prefix/2019/02/09/13/kinesis-stream-name-2019-02-09-10-02-32-db1db7a9-c484-40d1-b7ec-7651a55e4677"

The date in the path is UTC-time, the date in the file name is the UTC-time of the first received byte in the Kinesis stream for the specific file. This is the default behavior, so it would be nice to implement it in localstack.

**Comment by whummer** [comment]
Thanks for reporting @alphawolf1988 . This should be fixed in #1920 - closing this issue, please report here if the problem persists.
