### ISSUE TITLE
X-Ray

### ISSUE THREAD

**Issue by rjamesnw** [localstack/localstack#1559]
Will the X-Ray service be available at some point? I don't care of it fully exists, I'm just hoping the X-Ray SDK will just be ignored at least. ;)

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-118) by [Unito](https://www.unito.io/learn-more)

**Comment by thrau** [comment]
we have basic XRay support in pro: [feature coverage](https://github.com/localstack/localstack/blob/master/doc/feature_coverage.md).
