### ISSUE TITLE
Dependencies when attempting to add to conda-forge

### ISSUE THREAD

**Issue by mwilson8** [localstack/localstack#1561]
I'm attempting to add localstack to the conda-forge. One of the dependencies listed for localstack is subprocess32-ext, but the documentation on the PypI page (https://pypi.org/project/subprocess32-ext/ > 'Homepage') just links back to subprocess32; is subprocess32-ext necessary over subprocess32? More comments from review below:

https://github.com/conda-forge/staged-recipes/pull/9490/files/1ad390c2a2317f82368ef7291fe5def333ef2546#r323782672

https://github.com/conda-forge/staged-recipes/pull/9490/files/1ad390c2a2317f82368ef7291fe5def333ef2546#r323801458

**Comment by whummer** [comment]
Thanks for reporting @mwilson8 . The dependency `subprocess32-ext` is not needed anymore, it has been removed. We will soon cut a new release of the `localstack` pip package which will incorporate this change.

Please keep us posted how it goes, and if any other questions or issues come up. Thanks

**Comment by jakirkham** [comment]
Thanks @whummer! Would you mind letting us know here when the new release is made? 🙂

**Comment by whummer** [comment]
@jakirkham a new release has been made in the meantime. Please refer to the pypi package history here: https://pypi.org/project/localstack/#history Thanks

**Comment by jakirkham** [comment]
I’m not personally maintaining that one. Would follow up with the feedstock maintainers for `localstack`.

**Comment by mwilson8** [comment]
Thanks, @whummer !
@jakirkham `localstack 0.10.4.2` was released oct 6 & pushed to conda-forge oct 7 :)

**Comment by jakirkham** [comment]
Thanks for staying on top of things @mwilson8 ! 😀
