### ISSUE TITLE
Can't create domain name in apigateway service

### ISSUE THREAD

**Issue by golden-moon** [localstack/localstack#1564]
Hi, 

I am trying to create a domain name in apigateway service. I am using docker image of localstack. Do I miss something? 

`aws apigateway create-domain-name --endpoint-url=http://localhost:4567  --domain-name 'my.domain.com'`

returns:
`An error occurred (404) when calling the CreateDomainName operation: 
404 Not Found
The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.`

**Comment by whummer** [comment]
Thanks for reporting @golden-moon . This should be fixed in the latest version, an integration test has been added in #2326 . Can you please give it a try with the `latest` version of the Docker image? Please report here if the problem persists. Thanks
