### ISSUE TITLE
Invalid Access Key ID on lambda invocation from s3 bucket event

### ISSUE THREAD

**Issue by larquin** [localstack/localstack#1568]
I'm having an issue invoking lambdas via docker-compose. 

My docker compose file looks like this: 

```
 localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4567-4597:4567-4597"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=s3,lambda,iam,apigateway,sns,sqs,stepfunctions
      - DEFAULT_REGION=us-west-2
      - LAMBDA_EXECUTOR=docker
      - LAMBDA_REMOTE_DOCKER=true
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_REGION=us-west-2
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    privileged: true
```

Seems pretty straight forward. My lambdas listen to a bucket notification via SNS -> SQS, which seems to be invoking pretty well. 

After some log diving, docker-commands look to be set up correctly: 

```
Running lambda cmd: CONTAINER_ID="$(docker create -i   -p "35661":"35661" -e AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID" -e AWS_REGION="$AWS_REGION" -e AWS_SECRET_ACCESS_KEY="$AWS_SECRET_ACCESS_KEY" -e DOCKER_LAMBDA_USE_STDIN="$DOCKER_LAMBDA_USE_STDIN" -e HOSTNAME="$HOSTNAME" -e LOCALSTACK_HOSTNAME="$LOCALSTACK_HOSTNAME" -e AWS_LAMBDA_FUNCTION_NAME="$AWS_LAMBDA_FUNCTION_NAME" -e AWS_LAMBDA_FUNCTION_VERSION="$AWS_LAMBDA_FUNCTION_VERSION" -e AWS_LAMBDA_FUNCTION_INVOKED_ARN="$AWS_LAMBDA_FUNCTION_INVOKED_ARN"  --network="host"  "lambci/lambda:go1.x" "worker")";docker cp "/tmp/localstack/zipfile.9abb8cab/." "$CONTAINER_ID:/var/task"; docker start -ai "$CONTAINER_ID";
```

I went ahead and jumped in to the container that is running my lambda function: 

`docker exec -it <name> /bin/bash` 

Once in a bash prompt, I can see the environment variables are being set as expected: 

```
AWS_LAMBDA_FUNCTION_NAME=test-worker
AWS_SECRET_ACCESS_KEY=localstack
AWS_REGION=us-west-2
AWS_ACCESS_KEY_ID=localstack
AWS_LAMBDA_FUNCTION_INVOKED_ARN=arn:aws:lambda:us-west-2:000000000000:function:test-worker
```

However, when the lambdas are executed, my localstack log reports an interesting error, namely: 

```
 "errorMessage": "InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records.\n\tstatus code: 403
```

This could easily be a PEBKAC issue, or even an application code issue. But I was under the impression that localstack doesn't strictly "care" about credentials, and they can be relatively arbitrary. 

I made sure there was parity between my environment variables, my terraform provider, and any environment variables being injected into the docker-compose environment. 

After traipsing around some other issues, it seems that this could be a networking issue with the container that is being spun up via localstack in my docker-compose configuration? 

Any help would be appreciated.

**Comment by larquin** [comment]
I figured it out. This is definitely a networking issue!

**Comment by asavage** [comment]
I am having the same issue.  What was the networking issue you found?  ...and could you share your solution?

**Comment by jonnymwright** [comment]
@larquin 
 > I am having the same issue. What was the networking issue you found? ...and could you share your solution?

**Comment by strk** [comment]
I'm also having the `The AWS Access Key Id you provided does not exist in our records` message, can you share your solution @larquin ?

**Comment by ahmetsevki** [comment]
Your code is creating an s3 client, but not passing the `{ endpoint: 'http://localhost:4572', s3ForcePathStyle: true }` parameters.

**Comment by petervalencic** [comment]
Is there a way to avoid this step to pass the additional parameters to the AWS.S3 object? I'm asking because when I need to deploy the lambda on AWS I don't need to specify any additional parameters and so I would like to have the same lambda function running on localstack and on AWS.. Now I have two different versions...

**Comment by adamaraujodelima** [comment]
I had this problem in Lambda with S3. I fixed setting the policies in the lambda permissions and works for me. You had to set the policies with acess with S3 resources in lambda permissions. The lambda use self credentials that is controled by policies in settings.
