### ISSUE TITLE
Support installation on Windows

### ISSUE THREAD

**Issue by whummer** [localstack/localstack#157]
Although there have been some improvements lately ([PR 1](https://bitbucket.org/atlassian/localstack/pull-requests/98/use-tempfile-for-temporary-file-directory/diff), [PR 2](https://bitbucket.org/atlassian/localstack/pull-requests/119/use-built-in-functions-instead-of-sh/diff), [PR 3](https://bitbucket.org/atlassian/localstack/pull-requests/122/use-requests-instead-of-curl-wget/diff)), LocalStack still only works in UNIX-like environments (including Docker). We should continue to work towards native support for Windows.

**Comment by willpan** [comment]
What's the plan for `localstack-ext`?  That package is pulling in `pycrypto`, which requires building C extensions and that's a pain on Windows.  There's no wheel and the package doesn't look like it's being actively maintained ([the last commit was on Jun 20, 2014](https://github.com/dlitz/pycrypto)). The PyPI page for `localstack-ext` just points back to this repo. It'd be nice to be able to drop the `pycrypto` dependency for Windows.

**Comment by whummer** [comment]
Thanks for pointing that out @willpan . `localstack-ext` contains extended features that are not part of the open source offering. (We are currently preparing a private alpha version, more details will be published on the webpage soon: http://localstack.cloud)

In the latest updated version (`localstack-ext==0.7.0.1`) the `pycrypto` package has been removed and replaced with `pycryptodome`. Turns out that `pycrypto` actually exposes some security vulnerabilities (https://blog.sqreen.io/stop-using-pycrypto-use-pycryptodome/), and it is generally recommended to use `pycryptodome` which is a drop-in replacement that should work cross-platform.

Please let me know if there are any other issues. Thanks

**Comment by whummer** [comment]
Installation in Windows should now be supported and (mostly) working. Tracking new Windows-related issues elsewhere.
