### ISSUE TITLE
Bug when uploading file to S3 when file ends with new line characters because those get removed

### ISSUE THREAD

**Issue by AlexisWilke** [localstack/localstack#1571]
I'm using localstack as of commit f9dd152cbfab0a51e01e0c0b3ba7463304c8dba3

I ran in an issue where a file I first added to my S3 device (`PutObject()`) would come back out with one less byte. I verified what would be happening and where the error might be. The only possible location would be the localstack implementation (_unfortunately_).

My binary file ends with 0x0D. This is a `\r` character.

The system I use is [MinIO-Go](https://github.com/minio/minio-go) which sends a chunk-signature along the body of the file.  When that happens, it looks like you remove all `\r` and `\n` (in my test below I also added `\n` characters and they all get removed) instead of just one `\n` and then one `\r` (i.e. you're certain going backward for this exercise).

I can see that there is one 0x0D in my binary file and then the "\r\n" sequence just before the chunk-signature. You should only remove on "\r\n" and leave the rest alone.

Here is my go program to show the reproducible issue:

```
package main

import (
	"bytes"
	"fmt"
	"log"

	"github.com/minio/minio-go"
)

func main() {

        // all final 10 and 13 get removed from my data buffer!
	data := []byte{ 72, 101, 108, 108, 111, 10, 13, 10, 13, 10, 13, 10, 13 }
	//ioutil.WriteFile("/tmp/nolike.txt", data, 0644)

	mc, err := minio.New(
			"127.0.0.1:14572",	// localstack
			"foo",			// AWS access key id
			"bar",			// AWS secret access key
			false)
	if err != nil {
		log.Fatal("could not connect to S3", err)
	}

	err = mc.MakeBucket("bucket1", "us-east-1")
	if err != nil {
		exists, errBucketExists := mc.BucketExists("bucket1")
		hasBucket := errBucketExists == nil && exists
		if !hasBucket {
			log.Fatal("bucket1 does not exist and we could not create it", err, errBucketExists)
		}
	}

	fileReader := bytes.NewReader(data)
	size, err := mc.PutObject(
		"bucket1",
		"data",
		fileReader,
		int64(len(data)),
		minio.PutObjectOptions{
				ContentType: "audio/mpeg",
			})
	if err != nil {
		log.Fatal("PutObject failed.")
	}
	fmt.Println("size sent:", size)

	info, err := mc.StatObject("bucket1", "data", minio.StatObjectOptions{})
	if err != nil {
		log.Fatal("StatObject failed")
	}

	fmt.Println("info:", info)
	fmt.Println("info size:", info.Size, "(should be equal to", len(data), "if correct)")
}
```

At the end this program should print:

    info size: 13 (should be equal to 13 if correct)

But instead I get:

    info size: 7 (should be equal to 13 if correct)

because the `StatObject()` returns the correct size saved in S3, but not the expected size.

The exact set of bytes sent:

> 80 85 84 32 47 98 117 99 107 101 116 49 47 100 97 116 97 32 72 84 84 80 47 49 46 49 13 10 72 111 115 116 58 32 49 50 55 46 48 46 48 46 49 58 49 52 53 55 50 13 10 85 115 101 114 45 65 103 101 110 116 58 32 77 105 110 73 79 32 40 108 105 110 117 120 59 32 97 109 100 54 52 41 32 109 105 110 105 111 45 103 111 47 118 54 46 48 46 51 53 13 10 67 111 110 116 101 110 116 45 76 101 110 103 116 104 58 32 49 56 53 13 10 65 117 116 104 111 114 105 122 97 116 105 111 110 58 32 65 87 83 52 45 72 77 65 67 45 83 72 65 50 53 54 32 67 114 101 100 101 110 116 105 97 108 61 102 111 111 47 50 48 49 57 48 57 49 56 47 117 115 45 101 97 115 116 45 49 47 115 51 47 97 119 115 52 95 114 101 113 117 101 115 116 44 83 105 103 110 101 100 72 101 97 100 101 114 115 61 104 111 115 116 59 120 45 97 109 122 45 99 111 110 116 101 110 116 45 115 104 97 50 53 54 59 120 45 97 109 122 45 100 97 116 101 59 120 45 97 109 122 45 100 101 99 111 100 101 100 45 99 111 110 116 101 110 116 45 108 101 110 103 116 104 44 83 105 103 110 97 116 117 114 101 61 57 102 102 55 53 55 98 54 55 53 55 48 98 48 100 53 53 53 102 101 100 48 101 52 57 52 52 99 101 48 49 50 101 98 99 98 51 102 57 54 51 98 52 48 48 52 52 50 57 54 102 51 102 98 56 57 99 100 98 55 51 57 100 56 13 10 67 111 110 116 101 110 116 45 84 121 112 101 58 32 97 117 100 105 111 47 109 112 101 103 13 10 88 45 65 109 122 45 67 111 110 116 101 110 116 45 83 104 97 50 53 54 58 32 83 84 82 69 65 77 73 78 71 45 65 87 83 52 45 72 77 65 67 45 83 72 65 50 53 54 45 80 65 89 76 79 65 68 13 10 88 45 65 109 122 45 68 97 116 101 58 32 50 48 49 57 48 57 49 56 84 48 53 49 53 48 57 90 13 10 88 45 65 109 122 45 68 101 99 111 100 101 100 45 67 111 110 116 101 110 116 45 76 101 110 103 116 104 58 32 49 51 13 10 13 10 100 59 99 104 117 110 107 45 115 105 103 110 97 116 117 114 101 61 97 102 53 101 54 99 48 97 54 57 56 98 48 49 57 50 101 57 97 97 53 100 57 48 56 51 53 53 51 100 52 100 50 52 49 100 56 49 102 54 57 101 99 54 50 98 49 56 52 100 48 53 99 53 48 57 97 100 53 49 54 54 97 102 13 10 72 101 108 108 111 32 32 10 13 10 13 10 13 13 10 48 59 99 104 117 110 107 45 115 105 103 110 97 116 117 114 101 61 102 50 97 53 48 97 56 99 48 97 100 52 100 50 49 50 98 53 55 57 99 50 52 56 57 99 54 100 49 50 50 100 98 56 56 100 56 97 48 100 48 98 57 56 55 101 97 49 102 51 101 57 100 48 56 49 48 55 52 97 53 57 51 55 13 10 13 10

As we can see, near the end, there is a sequence of "10 13 ..." and then on "13 10" before the "48 59 99 ..." which is the _chunk-signature_:

`0;chunk-signature=f2a50a8c0ad4d212b579c2489c6d122db88d8a0d0b987ea1f3e9d081074a5937\r\n\r\n`

The bytes represent the following header and body (easier to read, but you may miss some bytes trying to just use that ASCII code):

```
PUT /bucket1/data HTTP/1.1
Host: 127.0.0.1:14572
User-Agent: MinIO (linux; amd64) minio-go/v6.0.35
Content-Length: 185
Authorization: AWS4-HMAC-SHA256 Credential=foo/20190918/us-east-1/s3/aws4_request,SignedHeaders=host;x-amz-content-sha256;x-amz-date;x-amz-decoded-content-length,Signature=9ff757b67570b0d555fed0e4944ce012ebcb3f963b40044296f3fb89cdb739d8
Content-Type: audio/mpeg
X-Amz-Content-Sha256: STREAMING-AWS4-HMAC-SHA256-PAYLOAD
X-Amz-Date: 20190918T051509Z
X-Amz-Decoded-Content-Length: 13

d;chunk-signature=af5e6c0a698b0192e9aa5d9083553d4d241d81f69ec62b184d05c509ad5166af
Hello  



0;chunk-signature=f2a50a8c0ad4d212b579c2489c6d122db88d8a0d0b987ea1f3e9d081074a5937

```

**Comment by whummer** [comment]
Thanks for reporting. Potential duplicates: #869 #1305 Can you please check if this issue is covered in one of the existing issues @AlexisWilke ? Then we can close this one and prioritize the other ones. Thanks

**Comment by AlexisWilke** [comment]
I checked #869 and it mentions a problem with a newline at the start, not the end. That is. I did not test newlines at the start of my files. That may also be a problem.

#1305 sounds closer to our problem, a user mentioned files ending with `0x0A` (although `0x0D` is also _affected_). I'll try to chunked encoding _trick_ to see what happens and report back.

**Comment by AlexisWilke** [comment]
Never mind. We see the header and it does include a `Content-Length`. So it can't be a chunked transfer. In other words, if the users could fix the problem in $1305 just by avoiding the `Transfer-Encoding: chunked`, then my issue is different.

That being said, all 3 seem to be closely related. As if someone was calling `trim()` on the received data before saving it.

Just in case, I tried to add 10 13 10 13 ... at the start and the size was correct on that end.

Then I tried to add 13 10 13 10 ... and the first 13 10 was removed. So I see the same issue as in #869 as well, just _not as bad_ I would say.

**Comment by AlexisWilke** [comment]
Okay, it looks like I was right when I was saying above that you were probably looping to remove the "\r\n" and removed too many of them.

Here we see two `for` loops, one testing at the start and one at the end and both are in link with the signature:

```
def strip_chunk_signatures(data):
    # For clients that use streaming v4 authentication, the request contains chunk signatures
    # in the HTTP body (see example below) which we need to strip as moto cannot handle them
    #
    # 17;chunk-signature=6e162122ec4962bea0b18bc624025e6ae4e9322bdc632762d909e87793ac5921
    # <payload data ...>
    # 0;chunk-signature=927ab45acd82fc90a3c210ca7314d59fedc77ce0c914d79095f8cc9563cf2c70

    data_new = re.sub(b'(\r\n)?[0-9a-fA-F]+;chunk-signature=[0-9a-f]{64}(\r\n){,2}', b'',
        data, flags=re.MULTILINE | re.DOTALL)
    if data_new != data:
        # trim \r (13) or \n (10)
        for i in range(0, 2):
            if len(data_new) and data_new[0] in (10, 13):
                data_new = data_new[1:]
        for i in range(0, 6):
            if len(data_new) and data_new[-1] in (10, 13):
                data_new = data_new[:-1]
    return data_new
```

There is no need for loops. There must exact 1 "10 13" sequence after the top signature and one before the bottom signature.

So I propose that you just remove the for entirely:

    if data_new != data:
        # trim \r (13) or \n (10)
        if len(data_new) and data_new[0] in (10, 13):
            data_new = data_new[1:]
        if len(data_new) and data_new[-1] in (10, 13):
            data_new = data_new[:-1]

If some tools really send more than one "10 13" sequence, then you need to know the size required before applying additional removes. But how would you ever know whether to remove the "10 13" at the start or at the end?!

**Comment by AlexisWilke** [comment]
Actually, I see that the chunk-signature regex will also alter 2 "\r\n":

```
    data_new = re.sub(b'(\r\n)?[0-9a-fA-F]+;chunk-signature=[0-9a-f]{64}(\r\n){,2}', b'',
        data, flags=re.MULTILINE | re.DOTALL)
```

As we see, you have a `{,2}` in there. That needs to be exactly 1, so remove the `{...}` entirely.

```
    data_new = re.sub(b'(\r\n)?[0-9a-fA-F]+;chunk-signature=[0-9a-f]{64}(\r\n)', b'',
        data, flags=re.MULTILINE | re.DOTALL)
```

If the "\r\n" is missing, it's a bug from the client. If they client put two of those, it's also a bug in the client's code.

Also, the first signature is not expected to be preceded by "\r\n", but the closing one is. I think that you could remove the if block as shown above and have two regex's. One for the start and one for the end. Something like this (untested):

```
    data_new = re.sub(b'^[0-9a-fA-F]+;chunk-signature=[0-9a-f]{64}(\r\n)', b'',
        data, flags=re.MULTILINE | re.DOTALL)
    data_new = re.sub(b'(\r\n)[0-9a-fA-F]+;chunk-signature=[0-9a-f]{64}$', b'',
        data_new, flags=re.MULTILINE | re.DOTALL)
```

The two newlines after the end of the block should be removed by the HTTP handler.

I'm not sure about the `^` and `$`, I've not used python much and the regex may view the buffer as one long string (one start, one end) or many lines. I suppose the `MULTILINE` is what changes that behavior and it's probably not useful here. Also the `DOTALL` is probably useless since we do not have a period in the expression. But it may have other necessary side effects.

These two lines would be all you need in that function.

**Comment by whummer** [comment]
Thanks for digging into this issue @AlexisWilke . I was able to reproduce this issue based on the HTTP dump you provided, and it should (hopefully) be fixed in #1608 . Can you please give it a try with the latest version of the Docker image?

**Comment by AlexisWilke** [comment]
Okay. I finally found the time to test this fix and it worked as expected. My Go program sent 19 bytes of text and you returned 19 bytes on `GET`. So I think this is fixed and most certainly the other two similar issues. Thank you.

**Comment by whummer** [comment]
Fantastic, thanks for testing @AlexisWilke !
