### ISSUE TITLE
New debug_java_port causing issues with lambda

### ISSUE THREAD

**Issue by a88zach** [localstack/localstack#1573]
We have several Kinesis streams set up with event notifications that trigger lambdas.  When the LAMBDA_EXECUTOR is set to 'docker' and we send a large number or records to Kinesis, multiple Lambdas will execute, but currently they are failing to create with error:

```
Exception: Lambda process returned error status code: 1. Output:
time="2019-09-18T17:28:11Z" level=error msg="error getting events from daemon: net/http: request canceled" 
Error response from daemon: driver failed programming external connectivity on endpoint busy_sanderson (a78e45a41d0ce5b0d8bab6ff54344fc34fe2b4969f55bf568e753121abc8759e): Bind for 0.0.0.0:38763 failed: port is already allocated
```

I believe this is due to the new debug_java_port introduced with this PR https://github.com/localstack/localstack/pull/1523

With this change, you are setting the port in the constructor by using a method known to have a race condition (https://github.com/localstack/localstack/blob/master/localstack/utils/common.py#L354)
(https://gist.github.com/gabrielfalcao/20e567e188f588b65ba2)

This should be changed to ensure unique ports are being issued across all lambdas

**Comment by rmrbest** [comment]
@a88zach Thanks for the issue. Let me check to fix it. @whummer what do you think?

**Comment by rmrbest** [comment]
@a88zach Do you put LAMDA_JAVA_OPTS as ennvironment variable in your docker run or docker-compose?

**Comment by rmrbest** [comment]
I think that always set a get_free_tcp_port, even when LAMDA_JAVA_OPTS is not set. May be, set a port when LAMDA_JAVA_OPTS is added, so is for debug purpose. If does not exist(not set), normal behaviour, i mean, don't set a port.

**Comment by a88zach** [comment]
Even with only setting the debug port when including java options, you're still going to run across this issue.  The main problem is that get_free_tcp_port is always going to return the same port as long as it is free.  With multiple dockers starting up at the same time you run into a race condition where  that function keeps giving out the same "free" port to multiple dockers b/c those dockers are still being initialized and have not taken the port yet

**Comment by rmrbest** [comment]
@whummer Could we use a random port? I've a bit time that weekend to fix it.

**Comment by whummer** [comment]
> I think that always set a get_free_tcp_port, even when debug_port is not set. May be, set a port when debug_port is added

I think this would be the right approach. Will push a fix asap @rmrbest

**Comment by whummer** [comment]
This should be fixed in #1586 - can you please give it a try with the latest version of the code? @a88zach @rmrbest

**Comment by whummer** [comment]
Closing for now - please re-open if the problem persists. thx

**Comment by paulbrimicombe** [comment]
This was actually a more serious bug than originally stated. In the original implementation the Lambda Executor `self.java_debug_port` is set once when `localstack` is initialised. This port is then used for _all_ invocations of _all_ lambda functions so any concurrently running lambdas will have the port clash (regardless of race conditions).

Isn't this still the case with the new implementation, but only if the debug port has been requested (i.e. any concurrent executions set up for debug will have the port clash)?

**Comment by a88zach** [comment]
Just tried with latest and the bug reported has been fixed for my use case
