### ISSUE TITLE
Support for EKS

### ISSUE THREAD

**Issue by manirahul83** [localstack/localstack#1574]
Hi,
Do you have support for EKS in the pipeline?

Thanks
Rahul

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-120) by [Unito](https://www.unito.io/learn-more)

**Comment by thrau** [comment]
We basic EKS support in Pro (see [feature coverage](https://github.com/localstack/localstack/blob/master/doc/feature_coverage.md). Please let is know if you have specific feature requests.

**Comment by debugger24** [comment]
Can we develop EKS support in the open source version ?
