### ISSUE TITLE
Firehose's DELIVERY_STREAM is gone every time the container is restarted.

### ISSUE THREAD

**Issue by tech-a-go-go** [localstack/localstack#1591]
Hi there,

All of firehose's delivery streams in localstack are gone every time the container is restarted.
(The container is not removed but just stopped and started)

How can I persist those streams even though I restart the container ?

Cheers

**Comment by larquin** [comment]
Seems like you might be able to use a volume for this, which is a docker-specific concern. For example, my docker-compose file looks something like this: 

```
version: '3.7'
services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - '4563-4599:4563-4599'
      - '8055:8080'
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - '~/docker/volumes/localstack:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
```

Before starting my environment, I simply created the directory where docker should mount it: 

`mkdir -p ~/docker/volumes/localstack`

Hopefully that answers your question!

**Comment by whummer** [comment]
Thanks for providing an answer, @larquin ! Closing this issue - please re-open if the problem persists @tech-a-go-go . Thanks!
