### ISSUE TITLE
Unable to invoke services through boto3 from latest. Works fine on 0.10.2

### ISSUE THREAD

**Issue by vikram-dogra** [localstack/localstack#1594]
Using `localstack/localstack:latest` or `localstack/localstack:0.10.3`, Unable to invoke any services from boto3. Getting **'Could not connect to the endpoint URL'** error. Same python boto3 code works fine on `localstack/localstack:0.10.2`.

Below error received when trying to start stepfunctions from lambda. 

	localstack-test    | {
	localstack-test    |   "errorType": "EndpointConnectionError",
	localstack-test    |   "errorMessage": "Could not connect to the endpoint URL: \"http://localhost:4585/\"",
	localstack-test    |   "stackTrace": [
	localstack-test    |     "  File \"/var/task/sqs_trigger_stepfunction.py\", line 85, in handler\n    input=json.dumps(input)\n",
	localstack-test    |     "  File \"/var/runtime/botocore/client.py\", line 320, in _api_call\n    return self._make_api_call(operation_name, kwargs)\n",
	localstack-test    |     "  File \"/var/runtime/botocore/client.py\", line 610, in _make_api_call\n    operation_model, request_dict)\n",
	localstack-test    |     "  File \"/var/runtime/botocore/endpoint.py\", line 102, in make_request\n    return self._send_request(request_dict, operation_model)\n",
	localstack-test    |     "  File \"/var/runtime/botocore/endpoint.py\", line 136, in _send_request\n    success_response, exception):\n",
	localstack-test    |     "  File \"/var/runtime/botocore/endpoint.py\", line 210, in _needs_retry\n    caught_exception=caught_exception, request_dict=request_dict)\n",
	localstack-test    |     "  File \"/var/runtime/botocore/hooks.py\", line 356, in emit\n    return self._emitter.emit(aliased_event_name, **kwargs)\n",
	localstack-test    |     "  File \"/var/runtime/botocore/hooks.py\", line 228, in emit\n    return self._emit(event_name, kwargs)\n",
	localstack-test    |     "  File \"/var/runtime/botocore/hooks.py\", line 211, in _emit\n    response = handler(**kwargs)\n",
	localstack-test    |     "  File \"/var/runtime/botocore/retryhandler.py\", line 183, in __call__\n    if self._checker(attempts, response, caught_exception):\n",
	localstack-test    |     "  File \"/var/runtime/botocore/retryhandler.py\", line 251, in __call__\n    caught_exception)\n",
	localstack-test    |     "  File \"/var/runtime/botocore/retryhandler.py\", line 277, in _should_retry\n    return self._checker(attempt_number, response, caught_exception)\n",
	localstack-test    |     "  File \"/var/runtime/botocore/retryhandler.py\", line 317, in __call__\n    caught_exception)\n",
	localstack-test    |     "  File \"/var/runtime/botocore/retryhandler.py\", line 223, in __call__\n    attempt_number, caught_exception)\n",
	localstack-test    |     "  File \"/var/runtime/botocore/retryhandler.py\", line 359, in _check_caught_exception\n    raise caught_exception\n",
	localstack-test    |     "  File \"/var/runtime/botocore/endpoint.py\", line 179, in _get_response\n    http_response = self._send(request)\n",
	localstack-test    |     "  File \"/var/runtime/botocore/endpoint.py\", line 223, in _send\n    return self.http_session.send(request)\n",
	localstack-test    |     "  File \"/var/runtime/botocore/httpsession.py\", line 278, in send\n    raise EndpointConnectionError(endpoint_url=request.url, error=e)\n"
	localstack-test    |   ]
	localstack-test    | }

Lambda code -

	...
    stepFunction = boto3.client(
            service_name='stepfunctions',
            endpoint_url='http://localhost:4585',
            region_name='us-east-1',
            aws_access_key_id='temp',
            aws_secret_access_key='temp'
        )
    response     = stepFunction.start_execution(
       stateMachineArn=arn:aws:states:us-east-1:000000000000:stateMachine:SFN_Check,
       input=json.dumps(input)
    )
	...

When directly called from command line it gets triggered - 

	aws --endpoint-url=http://localhost:4585 stepfunctions start-execution \
					--state-machine-arn arn:aws:states:us-east-1:000000000000:stateMachine:SFN_Check \
					--input '{ "one": "1", "two": "2" }'
	{
		"executionArn": "arn:aws:states:us-east-1:000000000000:execution:SFN_Check:05be3613-cb86-4d3e-8883-3cd50ad57af4",
		"startDate": 1569367616.618
	}

Getting similar issue of when trying to read a s3 bucket from a lambda. 

	localstack-test    | {
	localstack-test    |   "errorType": "EndpointConnectionError",
	localstack-test    |   "errorMessage": "Could not connect to the endpoint URL: \"http://localhost:4572/lbucket/1.txt\"",
	localstack-test    |   "stackTrace": [
	localstack-test    |     "  File \"/var/task/read_manifest.py\", line 33, in handler\n    lines = obj.get()['Body'].read().split(b'\\n')\n",
	localstack-test    |     "  File \"/var/runtime/boto3/resources/factory.py\", line 520, in do_action\n    response = action(self, *args, **kwargs)\n",
	localstack-test    |     "  File \"/var/runtime/boto3/resources/action.py\", line 83, in __call__\n    response = getattr(parent.meta.client, operation_name)(**params)\n",
	localstack-test    |     "  File \"/var/runtime/botocore/client.py\", line 320, in _api_call\n    return self._make_api_call(operation_name, kwargs)\n",
	localstack-test    |     "  File \"/var/runtime/botocore/client.py\", line 610, in _make_api_call\n    operation_model, request_dict)\n",
	localstack-test    |     "  File \"/var/runtime/botocore/endpoint.py\", line 102, in make_request\n    return self._send_request(request_dict, operation_model)\n",
	localstack-test    |     "  File \"/var/runtime/botocore/endpoint.py\", line 136, in _send_request\n    success_response, exception):\n",
	localstack-test    |     "  File \"/var/runtime/botocore/endpoint.py\", line 210, in _needs_retry\n    caught_exception=caught_exception, request_dict=request_dict)\n",
	localstack-test    |     "  File \"/var/runtime/botocore/hooks.py\", line 356, in emit\n    return self._emitter.emit(aliased_event_name, **kwargs)\n",
	localstack-test    |     "  File \"/var/runtime/botocore/hooks.py\", line 228, in emit\n    return self._emit(event_name, kwargs)\n",
	localstack-test    |     "  File \"/var/runtime/botocore/hooks.py\", line 211, in _emit\n    response = handler(**kwargs)\n",
	localstack-test    |     "  File \"/var/runtime/botocore/retryhandler.py\", line 183, in __call__\n    if self._checker(attempts, response, caught_exception):\n",
	localstack-test    |     "  File \"/var/runtime/botocore/retryhandler.py\", line 251, in __call__\n    caught_exception)\n",
	localstack-test    |     "  File \"/var/runtime/botocore/retryhandler.py\", line 277, in _should_retry\n    return self._checker(attempt_number, response, caught_exception)\n",
	localstack-test    |     "  File \"/var/runtime/botocore/retryhandler.py\", line 317, in __call__\n    caught_exception)\n",
	localstack-test    |     "  File \"/var/runtime/botocore/retryhandler.py\", line 223, in __call__\n    attempt_number, caught_exception)\n",
	localstack-test    |     "  File \"/var/runtime/botocore/retryhandler.py\", line 359, in _check_caught_exception\n    raise caught_exception\n",
	localstack-test    |     "  File \"/var/runtime/botocore/endpoint.py\", line 179, in _get_response\n    http_response = self._send(request)\n",
	localstack-test    |     "  File \"/var/runtime/botocore/endpoint.py\", line 223, in _send\n    return self.http_session.send(request)\n",
	localstack-test    |     "  File \"/var/runtime/botocore/httpsession.py\", line 278, in send\n    raise EndpointConnectionError(endpoint_url=request.url, error=e)\n"
	localstack-test    |   ]
	localstack-test    | }

Same code works fine on 0.10.2

**Comment by whummer** [comment]
Thanks for reporting @vikram-dogra . You Lambda is running in a separate Docker container - and by default that container has no access to LocalStack via `localhost` but using the environment variable `LOCALSTACK_HOSTNAME`.

Can you give it a try with this code:
```
import os
...
    print('Using LocalStack endpoint %s' % os.environ['LOCALSTACK_HOSTNAME'])
    stepFunction = boto3.client(
        service_name='stepfunctions',
        endpoint_url='http://%s:4585' % os.environ['LOCALSTACK_HOSTNAME'],
        region_name='us-east-1',
        aws_access_key_id='temp',
        aws_secret_access_key='temp'
    )
```

**Comment by whummer** [comment]
Thanks again - this should be fixed in `latest`, an integration test has been added in #2360 . Please report here if the problem persists. Thanks
