### ISSUE TITLE
Docker hub pull image issue

### ISSUE THREAD

**Issue by manjumukundan** [localstack/localstack#1599]
If localstack/localstack image is not available in local, localstack is not waiting for container to be available till docker pulls image from Docker Hub. Localstack stops the container before download and throws "Unable to pull image locally" error. 

This happens if pullImageNew is not set to true. Is that a mandatory property here? Even if its false, docker tries to download from Docker hub and localstack doesnt wait for the container to be set and throws error. But in the second run localstack picks the image from local downloaded from the previous run and works fine.

<img width="850" alt="Screen Shot 2019-09-26 at 12 08 02 PM" src="https://user-images.githubusercontent.com/15143298/65705398-5a66b300-e056-11e9-9bad-ad1a742733bb.png">

**Comment by whummer** [comment]
Thanks for reporting @manjumukundan . This should be fixed in #1943 - this change will be available when we release the next version of the Java libs (will happen soon). Thanks
