### ISSUE TITLE
Cannot connect to Cognito on pro closed beta

### ISSUE THREAD

**Issue by GrandathePanda** [localstack/localstack#1602]
```
 awslocal cognito-idp create-user-pool --cli-input-json file://api/test/aws_localstack_infra/cognito_user_pool.json                                                                                   

Connection was closed before we received a valid response from endpoint URL: "http://localhost:4590/".
```
I was recently accepted to the closed beta and I have exported the api key and tried both the docker image from the hub repo using localstack start and then via docker-compose after deleting the image and letting compose rebuild it.

In addition when I create a resource locally, the local web client updates but the app.localstack.cloud dashboard still says nothing is running.

I went over the docs a few times and spent a few hours trying to see if I was doing something obviously incorrect. Hoping to get some help to get this up and running :)

Thanks for all the work It's crazy watching this project mature.

**Comment by whummer** [comment]
Thanks for reporting @GrandathePanda . As discussed via slack, this issue should now be fixed. Please re-open if the problem persists. Thanks

**Comment by flesherj** [comment]
@whummer I just updated localstack and the localstack-ext as well as the docker image and continue to have this issue.  Is the solution documented elsewhere?

**Comment by whummer** [comment]
@flesherj Thanks for reporting, and apologies for the delay. We've looked into this issue with the API key and it should now be resolved - can you please give it another try? Please let us know (here or on Slack) if there are any other questions. Thanks!
