### ISSUE TITLE
`LocalstackExtension` starts everything per test

### ISSUE THREAD

**Issue by mar-kolya** [localstack/localstack#1615]
Hi,

So it looks like `LocalstackExtension` uses `beforeTestExecution`. This prevents `@BeforeEach` to be used to do initial setup of for example S3 buckets for tests.

Ideally localstack should be available for `@BeforeAll` so allow setup code to be pulled into setup methods.

In addition to that `Localstack.INSTANCE.setupInfrastructure()` is `protected` and not visible from tests - so tests cannot call it when they need infrastructure to be started.

The simplest solution seems to be to make `Localstack.INSTANCE.setupInfrastructure()` publically visible.

Thanks!

**Comment by whummer** [comment]
Thanks for suggesting this enhancement @mar-kolya . Do you think you could create a small pull request with this change? Thanks!

**Comment by AndyMacDroo** [comment]
Made a quick PR for this:
https://github.com/localstack/localstack/pull/1627

**Comment by whummer** [comment]
Thanks! Will release a new version of the Java libs shortly.
