### ISSUE TITLE
Invoke custom Authorizer when AWS_PROXY

### ISSUE THREAD

**Issue by rmrbest** [localstack/localstack#1618]
Would be possible invoke a custom authorizer lambda to get its response and add that information in request_context property. I can't see in apigateway_listener.py  authorizer block with its principalId. 

Or, we can pass as config a authorizer strucutre and add to request_context.

That issue has relation with #1315 

What do you think whummer

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-124) by [Unito](https://www.unito.io/learn-more)

**Comment by nr-96** [comment]
Hi guys, 
Is there are any updates on this?
