### ISSUE TITLE
S3 buckets created through cloudformation are not created in the template's region in Pro

### ISSUE THREAD

**Issue by Jaystified** [localstack/localstack#1622]
Any bucket created through cloudformation will have `"LocationConstraint": null`, implying us-east-1, although in AWS CloudFormation the bucket's region will always match the template's region.

**Comment by whummer** [comment]
Thanks for reporting @Jaystified . This should be fixed in #1628 - can you please give it a try with the latest version of the Docker image. Thanks

**Comment by Jaystified** [comment]
Can confirm it works now. Thanks!
