### ISSUE TITLE
Lambda Logs are not output to Docker logs till execution ends

### ISSUE THREAD

**Issue by ciaranevans** [localstack/localstack#1623]
When tailing docker container logs of Lambdas that have been invoked, the log output of the functions is not observed *until* the Lambda finishes executing, rather than when they are sent.

Example lambda `logs-test.py`:
```
from datetime import datetime
import logging
import time

LOGGER = logging.getLogger()
LOGGER.setLevel(logging.INFO)


def handler(event, context):
    LOGGER.info(datetime.now())
    time.sleep(300)
    LOGGER.info(datetime.now())
    return ""
```

To produce zip:
```
$ zip logs-test.zip logs-test.py
```

To create and invoke function:
```
import boto3
import botocore
from datetime import datetime

CONFIG = botocore.config.Config(connect_timeout=900, read_timeout=900, retries={'max_attempts': 0})

lambda_c = boto3.client('lambda', aws_access_key_id='', aws_secret_access_key='', region_name='eu-west-2',
                        endpoint_url='http://localhost:4574', config=CONFIG)

with open('./logs-test.zip', 'rb') as f:
    lambda_code = f.read()
lambda_c.create_function(
    FunctionName='logs-test',
    Runtime='python3.6',
    Role='',
    Handler='logs-test.handler',
    Code={'ZipFile': lambda_code},
    MemorySize=3000,
    Timeout=900
)

lambda_c.invoke(
    FunctionName='logs-test',
    InvocationType='RequestResponse'
)
```

Once the function is invoked, you can see the described behaviour by identifying the container with:
```
$ docker ps
CONTAINER ID        IMAGE                                       COMMAND                  CREATED             STATUS                      PORTS                                                       NAMES
1f1485acb9d7        lambci/lambda:python3.6                     "/var/lang/bin/pytho…"   6 seconds ago       Up 4 seconds                           
```

Then following the logs with:
```
$ docker logs -f 1f1485acb9d7
```

The expected log of the first datetime is not visible. Both calls to `LOGGER.info()` will only appear in the Docker logs when the 5 minutes is complete and the Lambda function terminates.

**Comment by kirbyjs** [comment]
As of right now awscli v2 is not released, but if you're willing to upgrade to it you can run the following command to get real time logs:

```
aws --endpoint-url=http://localhost:4586 logs tail /aws/lambda/$your_lambda_function_name --follow

**Comment by ciaranevans** [comment]
> As of right now awscli v2 is not released, but if you're willing to upgrade to it you can run the following command to get real time logs:
> 
> ```
> aws --endpoint-url=http://localhost:4586 logs tail /aws/lambda/$your_lambda_function_name --follow
> ```
Useful to know, but I guess then all the function invocations are logging to the same output?

**Comment by kirbyjs** [comment]
> but I guess then all the function invocations are logging to the same output?

@ciaranevans yep! Of course if you don't want to follow the logs, you can omit the `--follow` option. There's also a couple other options with it as well:

![image](https://user-images.githubusercontent.com/13893942/74077728-dbac5a00-49e7-11ea-8609-0c8b263cc821.png)

**Comment by ciaranevans** [comment]
> > but I guess then all the function invocations are logging to the same output?
> 
> @ciaranevans yep! Of course if you don't want to follow the logs, you can omit the `--follow` option. There's also a couple other options with it as well:
> 
> ![image](https://user-images.githubusercontent.com/13893942/74077728-dbac5a00-49e7-11ea-8609-0c8b263cc821.png)

Appreciated! Would have preferred docker commands (just because it's spinning up containers) but I will give this a go!

**Comment by whummer** [comment]
Looks like a solution/workaround has been provided for this issue - thanks for providing a pointer in the right direction @kirbyjs . @ciaranevans please report here if the problem persists, or if there's anything else that needs to be added. Thanks

**Comment by devklick** [comment]
Sorry to comment on an old thread, but I'm having some trouble with this and hoping someone can help. 

Despite my Node JS lambda logging with `console.log()` as soon as it's invoked, and I can see from the localstack console output that the code is getting past this point, I have no logs being created. The following returns no log groups:
```
awslocal --endpoint-url=http://localhost:4566 logs describe-log-groups
```
>{
&nbsp;&nbsp;&nbsp;&nbsp;"logGroups": []
}

Is there anything I'm missing to get these `console.log`s captured in CloudWatch?

Note, I'm using `awslocal` rather than `aws` because I dont have an AWS account I can use for testing this.

Also note, I'm using a different port to what was specified by @kirbyjs. I cannot connect to port 4586, so I swapped it out for the port mentioned in the localstack console logs as soon as localstack starts:
>2023-05-14T23:55:16.104  INFO --- [-functhread3] hypercorn.error            : Running on https://0.0.0.0:4566 (CTRL + C to quit)
