### ISSUE TITLE
Update LastModified of an S3 key

### ISSUE THREAD

**Issue by whummer** [localstack/localstack#163]
In certain scenarios, it would be useful to have an API to set the attributes of S3 buckets (e.g., LastModified of an S3 key). This is something we should investigate.

**Comment by whummer** [comment]
This has been implemented in the meantime - closing

**Comment by yuvsier** [comment]
@whummer Can you please point me at the documentation on how to do this? I can't seem to find it in the official docs. Thanks!

**Comment by marcfieldingbg** [comment]
Just adding my voice to this, I have an exact requirement where I'm writing code to move a lot of files between two folders on S3 based on date, it would be very useful if I could manipulate the dates on s3 Objects in LocalStack so that I can be sure everything's working as I expected.

**Comment by bentsku** [comment]
@marcfieldingbg Hello, this is quite an old issue and our parity with S3 has been greatly improved in the meantime.

You would like to be able to manipulate the dates internally? Some kind of LocalStack only endpoint to be able to change the `LastModified` attribute of an S3 object? I think this could be possible.

Would it be possible to open a new feature request on GitHub explaining your use-case? That way we can track it! Thank you!
