### ISSUE TITLE
ERROR: java.util.LinkedHashMap cannot be cast to APIGatewayProxyRequestEvent

### ISSUE THREAD

**Issue by kihong-kwon** [localstack/localstack#1634]
### Version
localstack / localstack : latest
DIGEST:b966d3ad668d

### OS 
Windows10 
(Docker + VirtualBox)

### ISSUE
My code is working on AWS. 
I am creating a localstack using cloud formation as follow.
deploy was Okay.. but when I call api gateway like this curl command

curl -iX POST http://192.168.99.100:4567/restapis/ge6gy2fvmr/local/_user_request_/updateEntitie -H 'Content-Type:application/json' -d '{"name": "test", "description": "test"}'
※My Code is here
https://github.com/kihong-kwon/my-first-lambda

I always get this error.
What I'm missing? 

```
localstack_1  | 2019-10-08T02:33:13:WARNING:localstack.services.awslambda.lambda_api: Error executing Lambda function arn:aws:lambda:ap-northeast-1:000000000000:function:my-first-lambda-local-CreateEntityFunction: Lambda process returned error status code: 1. Output:
localstack_1  | Exception in thread "main" java.lang.ClassCastException: java.util.LinkedHashMap cannot be cast to com.amazonaws.services.lambda.runtime.events.APIGatewayProxyRequestEvent
localstack_1  |         at net.kkhstudy.myfirstlambda.handler.RestSpringBootApiGatewayRequestHandler.handleRequest(RestSpringBootApiGatewayRequestHandler.java:23)
localstack_1  |         at cloud.localstack.LambdaExecutor.main(LambdaExecutor.java:113) Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 338, in run_lambda
localstack_1  |     event, context=context, version=version, asynchronous=asynchronous)
localstack_1  |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 81, in execute
localstack_1  |     return do_execute()
localstack_1  |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 66, in do_execute
localstack_1  |     result, log_output = self._execute(func_arn, func_details, event, context, version)
localstack_1  |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 226, in _execute
localstack_1  |     result, log_output = self.run_lambda_executor(cmd, stdin, environment)
localstack_1  |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 147, in run_lambda_executor
localstack_1  |     (return_code, log_output))
localstack_1  | Exception: Lambda process returned error status code: 1. Output:
localstack_1  | Exception in thread "main" java.lang.ClassCastException: java.util.LinkedHashMap cannot be cast to com.amazonaws.services.lambda.runtime.events.APIGatewayProxyRequestEvent
localstack_1  |         at net.kkhstudy.myfirstlambda.handler.RestSpringBootApiGatewayRequestHandler.handleRequest(RestSpringBootApiGatewayRequestHandler.java:23)
localstack_1  |         at cloud.localstack.LambdaExecutor.main(LambdaExecutor.java:113)
```

**Comment by Thomas-Franklin** [comment]
Hi just my input, as I had a similar error with ScheduledEvents, as it seems that not all input mappings is currently supported: https://github.com/localstack/localstack/blob/master/localstack/ext/java/src/main/java/cloud/localstack/LambdaExecutor.java#L71-L108

So for anything other than, `sqs`, `s3`, `dynamodb`, `Sns` and `kinesis` it will send the input as a `LinkedHashMap` - so in the request handler (https://github.com/kihong-kwon/my-first-lambda/blob/master/src/main/java/net/kkhstudy/myfirstlambda/handler/RestSpringBootApiGatewayRequestHandler.java#L24) it would also need to be a `LinkedHashMap` if using localstack.

**Comment by mvillafuertem** [comment]
same error

https://github.com/awsdocs/aws-lambda-developer-guide/blob/master/sample-apps/java-basic/src/main/java/example/HandlerWeatherData.java

```
> Exception in thread "main" java.lang.ClassCastException: class java.util.LinkedHashMap cannot be cast to class example.WeatherData (java.util.LinkedHashMap is in module java.base of loader 'bootstrap'; example.WeatherData is in unnamed module of loader 'app')
```

**Comment by DVader666** [comment]
This issue has been open for a while now. Are there any fixes, workarounds, solutions, tips about it? Any official answer?

I'm also experiencing a similar or the same issue with a Java-based lambda that should be triggered by an scheduled event or a custom POJO as payload for the scheduled event.

The same lambda works in AWS but fails in LocalStack (0.11.5):

```
Exception in thread "main" java.lang.ClassCastException: java.util.LinkedHashMap cannot be cast to com.xxx.DownloaderInput
at com.xxx.DownloaderFunction.apply(DownloaderFunction.java:16)
at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.invokeFunction(SimpleFunctionRegistry.java:502)
at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.lambda$doApply$3(SimpleFunctionRegistry.java:569)
at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:107)
at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:121)
at reactor.core.publisher.FluxJust$WeakScalarSubscription.request(FluxJust.java:99)
at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.request(FluxMapFuseable.java:162)
at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.request(FluxMapFuseable.java:162)
at reactor.core.publisher.BlockingIterable$SubscriberIterator.onSubscribe(BlockingIterable.java:224)
at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onSubscribe(FluxMapFuseable.java:90)
at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onSubscribe(FluxMapFuseable.java:90)
at reactor.core.publisher.FluxJust.subscribe(FluxJust.java:70)
at reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:62)
at reactor.core.publisher.BlockingIterable.iterator(BlockingIterable.java:81)
at org.springframework.cloud.function.adapter.aws.SpringBootRequestHandler.result(SpringBootRequestHandler.java:59)
at org.springframework.cloud.function.adapter.aws.SpringBootRequestHandler.handleRequest(SpringBootRequestHandler.java:52)
at cloud.localstack.LambdaExecutor.main(LambdaExecutor.java:113)
```

Where can I find documentation about officially supported AWS events for Java-based lambdas in LocalStack? Or is it still the case that custom objects, as well as ScheduledEvent objects, are not yet supported by LocalStack?

**Comment by macnev2013** [comment]
Thanks for reporting @kihong-kwon @Thomas-Franklin @mvillafuertem @DVader666 .
This should be fixed in the `latest` version of `localstack`.
Can you give it a try after pulling the latest image using `docker pull localstack/localstack`.

Let us know if the issue still persists.

**Comment by DVader666** [comment]
Yup. I pulled latest version and tested again with the same Java-based lambda (DownloaderFunction) and it accepted my custom POJO (DownloaderInput) as expected and same as when using the real AWS account. Good job!

**Comment by rvignacio** [comment]
Hello, could this be affecting LocalStack's APIGatewayV2? I am running a V2 integration and getting this same error. My object extends APIGatewayV2HTTPEvent.

**Comment by dfangl** [comment]
Hi!
This seems to be an issue exclusively related to the `local` executor.
Can you try to use a docker based executor (mount your docker socket into the container) or, even better, mount the docker socket into the container and use `PROVIDER_OVERRIDE_LAMBDA=asf` and check if this fixes you problems?
The local executor has a suboptimal support for most events, which leads to the problems described.
