### ISSUE TITLE
Data persistence for all services

### ISSUE THREAD

**Issue by whummer** [localstack/localstack#164]
We should document our roadmap for extended data persistence. (So far, persistent state is only supported for a few of the services). We'll keep this ticket as a reminder in the meantime.

**Comment by hoisu** [comment]
Can we have a estimate for SSM persistence?

**Comment by johansmolinski** [comment]
I am also interested in SSM (parameter store, specifically) persistence.

**Comment by dany74q** [comment]
@hoisu, @johansmolinski - here's a proposed implementation for SSM persistence, as a reference:
https://github.com/localstack/localstack/pull/2382

Hope it helps.

**Comment by whummer** [comment]
SSM persistence has been added in #2382 - thanks again @dany74q .
