### ISSUE TITLE
localstack - command not found

### ISSUE THREAD

**Issue by oren** [localstack/localstack#1644]
I installed Localstack with the pip command `pip install localstack` but when I type `localstack start --host` I get: command not found

pip list show me the following:
```
localstack (0.10.4.2)
localstack-client (0.14)
localstack-ext (0.10.42)
```

cat /etc/lsb-release:
```
Ubuntu 18.04.1 LTS
```

(I am using Windows Subsystem for Linux)

**Comment by whummer** [comment]
Thanks for reporting @oren . Please make sure that the pip `bin` (Unix) or `Scripts` (Windows) directory has been properly added to your system's path.

This is not a LocalStack issue per se, but a general pip/`PATH` setup issue, hence closing this issue. Please consult the web on how to set the pip path on your system, or report back here if you think this is a legitimate issue with LocalStack. Thanks!
