### ISSUE TITLE
Add support for python3.7 AWS Lambda runtime

### ISSUE THREAD

**Issue by Swington** [localstack/localstack#1648]

**Comment by whummer** [comment]
Thanks for reporting @Swington . The `python3.7` Lambda runtime should in fact already work out of the box - have you tried running a test with it?

To make things a bit more explicit, would you mind opening a small pull request that adds a constant to this file: https://github.com/localstack/localstack/blob/master/localstack/services/awslambda/lambda_executors.py#L26-L27

Again, this shouldn't have any functional impact, as `python3.7` should already work, given we're using the Docker images from https://github.com/lambci/docker-lambda under the covers (which already includes an image for `python3.7`). Closing this issue - please report here with more details if there are any problems. Thanks

**Comment by Swington** [comment]
@whummer Thank you for your response. 

I only used localstack as a docker container.
Indeed, python3.7 works out of the box, but only for `docker` and `docker-reuse` `LAMBDA_EXECUTOR` values. For `local`, the python that is used for runners `python3.6` and `python3.7` is container's python 3.6.

**Comment by whummer** [comment]
@Swington I think when using `LAMBDA_EXECUTOR=local`, we simply use the locally installed Python version. What does `python --version` say on your system?

From this line, it seems that any runtime value that starts with `python` shoud work:
https://github.com/localstack/localstack/blob/master/localstack/services/awslambda/lambda_api.py#L570

Do you think you can share a small example to reproduce the concrete issue you're facing?

Generally, using the local lambda executor is not recommended - it is better to use the container based execution, for reproducibility and platform independence.
