### ISSUE TITLE
Create an RDS service with DB functionality

### ISSUE THREAD

**Issue by whummer** [localstack/localstack#165]
RDS is an important service used by lots of cloud applications, we should consider supporting it in LocalStack. MySQL and Postgres images are readily available, potentially we can integrate them (e.g., using `docker-compose`).

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-128) by [Unito](https://www.unito.io/learn-more)

**Comment by njcongtou** [comment]
any updates?

**Comment by IhostVlad** [comment]
It will be good if `LocalStack` will implement `Aurora RDS` API, even if it will consist only mock responses to appropriate APIs.
Of course, self database can be installed separately and only be wrapped in target endpoint :)

**Comment by crypticmind** [comment]
How difficult/feasible would be to spin up an [H2](http://www.h2database.com/html/main.html) instance in localstack to mock RDS? H2 claims to have compatibility modes for IBM DB2, Apache Derby, HSQLDB, MS SQL Server, MySQL, Oracle, and PostgreSQL.

**Comment by h3ct0rjs** [comment]
Hi, Any updates on this?

**Comment by areguig** [comment]
> How difficult/feasible would be to spin up an [H2](http://www.h2database.com/html/main.html) instance in localstack to mock RDS? H2 claims to have compatibility modes for IBM DB2, Apache Derby, HSQLDB, MS SQL Server, MySQL, Oracle, and PostgreSQL.

H2 does not actually have a full compatibility mode for PostgreSQL, since RDS supports PG versions after 9.4. For example, the types JSON and JSONB are not supported (yet) by H2 and that is an important 'feature' of Postgres. I would like an update too.

**Comment by holmesal** [comment]
It would also be great to have localstack support for [aurora serverless](https://aws.amazon.com/rds/aurora/serverless/), and particularly the [data API](https://aws.amazon.com/blogs/aws/new-data-api-for-amazon-aurora-serverless/) - both are super useful when building serverless apps.

**Comment by whummer** [comment]
Hi @njcongtou @IhostVlad @crypticmind @h3ct0rjs @areguig @holmesal 

Initial support for **RDS** (Postgres) has been added to the LocalStack Pro edition. 🎉 If you want to check it out, please head over to the website and sign up for private beta access: https://localstack.cloud

**Comment by holyoaks** [comment]
Is there a way to connect a local psql or other postgresql client to one or more local rds localstack instances? I would like to be able to query the db directly for testing purposes, but don't see any solution other than awslocal.

**Comment by Arpitjit** [comment]
Is there a way to connect java spring application to spring-cloud API to localstack RDS postgress. when i am trying to connect to localstack spring-cloud api tries to lookupt instance to rds.aws.com, rather than that it should connect to locastack

**Comment by whummer** [comment]
Hi @Arpitjit , looks like Spring has `.endpoint` properties for each service - e.g., this README page may be helpful: https://github.com/spring-cloud/spring-cloud-aws/blob/main/docs/src/main/asciidoc/_configprops.adoc . Hope that helps as a starting point. Closing this issue for now - please let us know if there are any other questions. Thanks!
