### ISSUE TITLE
RawMessageDelivery true is not working

### ISSUE THREAD

**Issue by nirvana124** [localstack/localstack#1651]
Created SQS and SNS and add subscription to add SQS.
Set attributes of RawMessageDelivery as True/true so that only message is sent to the queue.

awslocal sns set-subscription-attributes --subscription-arn arn:aws:sns:us-east-1:000000000000:test-topic:7112e1d4-1817-4889-846c-5d0855942d27 --attribute-name RawMessageDelivery --attribute-value 'True'

Same way i added FilterPolicy that is working fine.

Getting the message with all the attributes and properties.

**Comment by whummer** [comment]
Thanks for reporting @nirvana124 . My guess is that the attribute value is case-sensitive (`true` vs `True`). This has been fixed in #1924 - can you please give it another try with the latest version? Closing this issue - please re-open if the problem persists. Thanks!
