### ISSUE TITLE
SQS Send Message Batch should not allow empty batches

### ISSUE THREAD

**Issue by ashleyfrieze** [localstack/localstack#1658]
Real SQS throws `There should be at least one SendMessageBatchRequestEntry in the request. (Service: AmazonSQS; Status Code: 400; Error Code: AWS.SimpleQueueService.EmptyBatchRequest;` when there is a send batch of zero size.

This would be useful to mimic inside localstack in order to find these bugs earlier.

**Comment by whummer** [comment]
Thanks for reporting @ashleyfrieze . This should be fixed in #2412 - can you please give it a try with the `latest` version? Please report here if the problem persists. Thanks
