### ISSUE TITLE
Allow persistent data to be cleared without restarting LocalStack

### ISSUE THREAD

**Issue by whummer** [localstack/localstack#166]
Currently the only way to "clear" all resources created in LocalStack is to restart the application. Some users have requested a way to clear all resources without restarting.

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-130) by [Unito](https://www.unito.io/learn-more)

**Comment by andreashe** [comment]
Yes this would be great. I tried by a script to remove existing content (iterating over all created stuff and remove it). But my lessons learned is; it is faster to restart localstack. But IMHO it would be better to run a clear somehow to make it even faster.
