### ISSUE TITLE
Cannot start "edge" service on some linux setups (conflicts with systemd-resolved)

### ISSUE THREAD

**Issue by Jaystified** [localstack/localstack#1660]
Running on Linux Mint 19.2

Trying to start localstack with the "edge" service on results in the following error:
```
docker: Error response from daemon: driver failed programming external connectivity on endpoint localstack_main (327991f9aca8706c9aefbe6f2f8b92d76409702a3831fca109d2da965add1a81): Error starting userland proxy: listen tcp 0.0.0.0:53: bind: address already in use.
```
It seems that systemd-resolver is already taking up that address.

**Comment by whummer** [comment]
Thanks for reporting @Jaystified . I was able to reproduce this issue on a Ubuntu machine. Can you please check the contents of your `/etc/resolv.conf`, in my case it is:
```
nameserver 127.0.0.53
```
.. which means that we can bind the DNS server to any other local address that doesn't conflict with this IP address. Does the following work for you?
```
$ DNS_ADDRESS=127.0.0.1 SERVICES=edge,cognito localstack start
...
$ host test123.cloudfront.net
test123.cloudfront.net has address 127.0.0.1
```

**Comment by Jaystified** [comment]
The `DNS_ADDRESS=127.0.0.1` workaround does work in my case!

**Comment by whummer** [comment]
Fantastic, thanks for confirming!

**Comment by FranzStrudel** [comment]
The workaround didn't work for me, or more accurately, the DNS_ADDRESS varaible don't seems to be taken into account

`$ DNS_ADDRESS=127.0.0.1 localstack start --docker`
`
/usr/share/python-wheels/requests-2.18.4-py2.py3-none-any.whl/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.25.7) or chardet (3.0.4) doesn't match a supported version!`
```
Starting local dev environment. CTRL-C to quit.
2019-11-26T15:04:39:INFO:localstack_ext.bootstrap.licensing: Successfully activated API key
docker run -it -e LOCALSTACK_HOSTNAME="localhost" -e DEFAULT_REGION="us-east-1" -e LOCALSTACK_API_KEY="XXXXXXXXXX" -e TEST_AWS_ACCOUNT_ID="000000000000" -e LOCALSTACK_HOSTNAME="localhost" -p **0.0.0.0**:53:53 -p **0.0.0.0**:53:53/udp -p 4510-4530:4510-4530 --rm --privileged --name localstack_main -p 8080:8080 -p 8081:8081  -p 443:443 -p 4567-4608:4567-4608  -v "/tmp/localstack:/tmp/localstack" -v "/var/run/docker.sock:/var/run/docker.sock" -e DOCKER_HOST="unix:///var/run/docker.sock" -e HOST_TMP_FOLDER="/tmp/localstack" "localstack/localstack" 
```
`docker: Error response from daemon: driver failed programming external connectivity on endpoint localstack_main (2fab832a0a1025fb85c25f47e23821dbc4721ef7d1c5b7578f0d6eb3c480d115): Error starting userland proxy: listen tcp 0.0.0.0:53: bind: address already in use.`

If I run the docker command manually overwriting 0.0.0.0 by 127.0.0.1, it does work.

**Comment by whummer** [comment]
Thanks @FranzStrudel - can you please try if it works after running the following:
```
pip install --upgrade --no-cache localstack localstack-client localstack-ext
```

**Comment by FranzStrudel** [comment]
Thanks for the feedback @whummer 

Sadly it didn't help :(

Should I use python2 or python3 ?

So far I used py3 (gave the same result), but I tried too with py2 and got this error 

`
/usr/share/python-wheels/requests-2.18.4-py2.py3-none-any.whl/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.25.7) or chardet (3.0.4) doesn't match a supported version!

Traceback (most recent call last):
  File "/home/polo/.local/bin/localstack", line 35, in <module>
    from localstack.utils import cli, bootstrap
  File "/home/polo/.local/lib/python2.7/site-packages/localstack/utils/cli.py", line 3, in <module>
    from localstack.utils.bootstrap import (
  File "/home/polo/.local/lib/python2.7/site-packages/localstack/utils/bootstrap.py", line 11, in <module>
    import pip as pip_mod
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 31, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/lib/python2.7/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 40, in <module>
    from pip._vendor import requests, six
ImportError: cannot import name requests
`

I tried installing the package python-requests to no avail.
