### ISSUE TITLE
IAM SimulatePrincipalPolicy returns XML error

### ISSUE THREAD

**Issue by adam-fowler** [localstack/localstack#1674]
The following aws cli command returns an XML parsing error.
```
aws --endpoint-url http://localhost:4593 iam simulate-principal-policy --action-names "iam:*,sns:*" --policy-source-arn arn:aws:iam::000000000000:user/testsimulatepolicy-user
```
The error is as follows
```
Unable to parse response (syntax error: line 1, column 54), invalid XML received:
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
```
I am running localstack as follows
```
docker run -d -p 4593:4593 -e SERVICES='iam' localstack/localstack
```

**Comment by imincik** [comment]
I confirm this issue.

**Comment by zagovorichev** [comment]
It is still there, any updates, suggestions how to fix? :(

**Comment by whummer** [comment]
Thanks for reporting @adam-fowler @imincik @zagovorichev . This issue should be fixed in #2477 (with a simple mocked response for now) - can you please give it a try with the `latest` version of the Docker image? Please report here if the problem persists. Thanks

**Comment by adam-fowler** [comment]
I pulled localstack:latest and am still getting the same error. Are you sure the fix is in the latest docker image? The release on github doesnt include these fixes.

**Comment by whummer** [comment]
Hi @adam-fowler , which version of the image are you using (what is the timestamp of when was it pushed)? We had some issues with our CI pipeline - the latest image should be pushed now. Can you please give it another try? Thanks

**Comment by adam-fowler** [comment]
Hi @whummer sorry took a while to get back. It nows returns a `NoSuchEntity` error, even though I just created the user I am passing to the function.
