### ISSUE TITLE
localstack 0.10.3 to latest not starting on reboot (Ubuntu 18.04)

### ISSUE THREAD

**Issue by AlexisWilke** [localstack/localstack#1689]
I installed a brand new VPS with Virtualbox. Installed Docker. Got Localstack and run `docker run localstack/localstack`. The Localstack starts and works great.

After a reboot, when I check for the `localstack` environment with `docker ps -a`, it says it exited:

```
$ sudo docker ps -a
CONTAINER ID        IMAGE                   COMMAND                  CREATED             STATUS                            PORTS               NAMES
d3e1caafe3a5        localstack/localstack   "docker-entrypoint.sh"   24 hours ago        Exited (137) About a minute ago                       my_localstack
```

I can just restart it and it works fine:

    sudo docker start my_localstack

And in this case it works every single time.

When I look at the log (see attached) I can see that some things time out and as a result docker decides to kill the whole thing.

My thinking would be that the order in which the containers are started is _random_ and that means certain docks start too soon, before others that are necessary. I have had the problem on two different computers. One native and this one VPS. Both computers are Xeon 4 CPUs minimum, way more RAM than docker uses... I'm not too sure why that would fail except because of the order in which things start. That being said, you may see something in the logs that tells you what the problem really is.

[localstack-json.log](https://github.com/localstack/localstack/files/3775371/localstack-json.log)

Relevant error?

> {"log":"2019-10-26T23:37:18:ERROR:localstack.services.generic_proxy: Error forwarding request: HTTPConnectionPool(host='127.0.0.1', port=4565): Max retries exceeded with url: / (Caused by NewConnectionError('\u003curllib3.connection.HTTPConnection object at 0x7fee0980c0b8\u003e: Failed to establish a new connection: [Errno 111] Connection refused',)) Traceback (most recent call last):\n","stream":"stdout","time":"2019-10-26T23:37:19.128835424Z"}  
> {"log":"  File \"/opt/code/localstack/.venv/lib/python3.6/site-packages/urllib3/connection.py\", line 157, in _new_conn\n","stream":"stdout","time":"2019-10-26T23:37:19.128859965Z"}  
> {"log":"    (self._dns_host, self.port), self.timeout, **extra_kw\n","stream":"stdout","time":"2019-10-26T23:37:19.128872345Z"}  
> {"log":"  File \"/opt/code/localstack/.venv/lib/python3.6/site-packages/urllib3/util/connection.py\", line 84, in create_connection\n","stream":"stdout","time":"2019-10-26T23:37:19.128883243Z"}  
> {"log":"    raise err\n","stream":"stdout","time":"2019-10-26T23:37:19.12889483Z"}  
> {"log":"  File \"/opt/code/localstack/.venv/lib/python3.6/site-packages/urllib3/util/connection.py\", line 74, in create_connection\n","stream":"stdout","time":"2019-10-26T23:37:19.128905738Z"}  
> {"log":"    sock.connect(sa)\n","stream":"stdout","time":"2019-10-26T23:37:19.128917082Z"}  
> {"log":"ConnectionRefusedError: [Errno 111] Connection refused\n","stream":"stdout","time":"2019-10-26T23:37:19.128927641Z"}

**Comment by AlexisWilke** [comment]
[From this other issue](https://github.com/localstack/localstack/issues/1655) I see that port 4565 is expected to be opened by DynamoDB. Only in my case the DynamoDB opens 4564 instead:

```
Initializing DynamoDB Local with the following configuration:
Port:   4564
InMemory:       false
DbPath: /tmp/localstack-data/dynamodb
SharedDb:       true
shouldDelayTransientStatuses:   false
CorsParams:     *

Step Functions Local
Version: 1.4.0
Build: 2019-09-18
```

**Comment by AlexisWilke** [comment]
Actually, looking at the start of my logs, I see the following error which says **Cannot find module 'leveldown'**.

```
internal/modules/cjs/loader.js:797
throw err;
^

Error: Cannot find module 'leveldown'
Require stack:
- /opt/code/localstack/localstack/node_modules/kinesalite/db/index.js
- /opt/code/localstack/localstack/node_modules/kinesalite/index.js
- /opt/code/localstack/localstack/node_modules/kinesalite/cli.js
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
at Function.Module._load (internal/modules/cjs/loader.js:687:27)
at Module.require (internal/modules/cjs/loader.js:849:19)
at require (internal/modules/cjs/helpers.js:74:18)
at Object.create (/opt/code/localstack/localstack/node_modules/kinesalite/db/index.js:31:35)
at kinesalite (/opt/code/localstack/localstack/node_modules/kinesalite/index.js:24:26)
at Object.<anonymous> (/opt/code/localstack/localstack/node_modules/kinesalite/cli.js:29:35)
at Module._compile (internal/modules/cjs/loader.js:956:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
at Module.load (internal/modules/cjs/loader.js:812:32) {
code: 'MODULE_NOT_FOUND',
requireStack: [
'/opt/code/localstack/localstack/node_modules/kinesalite/db/index.js',
'/opt/code/localstack/localstack/node_modules/kinesalite/index.js',
'/opt/code/localstack/localstack/node_modules/kinesalite/cli.js'
]
}
Step Functions Local
Version: 1.4.0
Build: 2019-09-18
```

**Comment by AlexisWilke** [comment]
Actually in my attachment in the main post, the first error has to do with the fact that we can't connect to 4565. And that's most certainly due to the fact that dynamoDB doesn't start.

> {"log":"2019-10-26T23:37:18:ERROR:localstack.services.generic_proxy: Error forwarding request: HTTPConnectionPool(host='127.0.0.1', port=4565): Max retries exceeded with url: / (Caused by NewConnectionError('\u003curllib3.connection.HTTPConnection object at 0x7fee0980c0b8\u003e: Failed to establish a new connection: [Errno 111] Connection refused',)) Traceback (most recent call last):\n","stream":"stdout","time":"2019-10-26T23:37:19.128835424Z"}  
> {"log":"  File \"/opt/code/localstack/.venv/lib/python3.6/site-packages/urllib3/connection.py\", line 157, in _new_conn\n","stream":"stdout","time":"2019-10-26T23:37:19.128859965Z"}  
> {"log":"    (self._dns_host, self.port), self.timeout, **extra_kw\n","stream":"stdout","time":"2019-10-26T23:37:19.128872345Z"}  
> {"log":"  File \"/opt/code/localstack/.venv/lib/python3.6/site-packages/urllib3/util/connection.py\", line 84, in create_connection\n","stream":"stdout","time":"2019-10-26T23:37:19.128883243Z"}  
> {"log":"    raise err\n","stream":"stdout","time":"2019-10-26T23:37:19.12889483Z"}  
> {"log":"  File \"/opt/code/localstack/.venv/lib/python3.6/site-packages/urllib3/util/connection.py\", line 74, in create_connection\n","stream":"stdout","time":"2019-10-26T23:37:19.128905738Z"}  
> {"log":"    sock.connect(sa)\n","stream":"stdout","time":"2019-10-26T23:37:19.128917082Z"}  
> {"log":"ConnectionRefusedError: [Errno 111] Connection refused\n","stream":"stdout","time":"2019-10-26T23:37:19.128927641Z"}  
> {"log":"\n","stream":"stdout","time":"2019-10-26T23:37:19.128938289Z"}  
>  {"log":"During handling of the above exception, another exception occurred:\n","stream":"stdout","time":"2019-10-26T23:37:19.128951544Z"}

**Comment by AlexisWilke** [comment]
Looking at the code, the port is defined as the _default kinesis backend port_.

```
.../localstack/localstack/constants.py:DEFAULT_PORT_KINESIS_BACKEND = 4565
```

Only I do not see anything about port 4565 and _«services that are behind a proxy»_.

**Comment by AlexisWilke** [comment]
Okay... I changed the script I used to create my localstack docker. I'm new to docker and used someone else's script but it looks like it creates problems. It may help you enhance your environment to have this script so here it is:

```
export LOCALSTACK_TMPDIR="/tmp/localstack-tmp"
export LOCALSTACK_SOCK=/var/run/docker.sock
export LOCALSTACK_SERVICES=
export LOCALSTACK_DEBUG=1
export LOCALSTACK_DATA_DIR="/tmp/localstack-data"
export LOCALSTACK_NAME="megaphone_localstack"
export LOCALSTACK_LAMBDA_EXECUTOR=
export LOCALSTACK_KINESIS_ERROR_PROBABILITY=
export LOCALSTACK_DYNAMODB_ERROR_PROBABILITY=

export PROXY_PORT_SERVICES="4567-4597:4567-4597"
export PROXY_PORT_WEB_UI="8080:8080"
export PROXY_PORT_SECURE_WEB_UI="8443:8443"

docker run -d                                            \                      
    -p "$PROXY_PORT_SERVICES"                            \
    -p "$PROXY_PORT_WEB_UI"                              \
    -p "$PROXY_PORT_SECURE_WEB_UI"                       \
    -v $LOCALSTACK_SOCK:$LOCALSTACK_SOCK                                           \
    -e DEBUG=$LOCALSTACK_DEBUG                           \
    -e TMPDIR=${LOCALSTACK_TMPDIR}                                                 \
    -e SERVICES=$LOCALSTACK_SERVICES                                               \
    -e DATA_DIR=$LOCALSTACK_DATA_DIR                                               \
    -e LAMBDA_EXECUTOR=$LOCALSTACK_LAMBDA_EXECUTOR                                 \
    -e KINESIS_ERROR_PROBABILITY=$LOCALSTACK_KINESIS_ERROR_PROBABILITY             \
    -e DYNAMODB_ERROR_PROBABILITY=$LOCALSTACK_DYNAMODB_ERROR_PROBABILITY           
\
    -e PORT_WEB_UI=$LOCALSTACK_PORT_WEB_UI                                         \
    -e DOCKER_HOST=unix://$LOCALSTACK_SOCK                                         \
    --name "$LOCALSTACK_NAME"                            \
    localstack/localstack
```

Now I only set `-d`, `-e DEBUG=1`, the `-p`, the `--name`. Everything else uses the default and it works just fine.

Also, to test the other versions, I changed the last line with:

```
docker -d ... \
    ... \
    localstack/localstack:<tag>
```

where I set `<tag>` to values such as 0.10.2, 0.10.3, 0.10.4, and latest. For a list of valid tags see here: https://hub.docker.com/r/localstack/localstack/tags

**Comment by whummer** [comment]
Should be fixed in #1711 - please report here if the problem persists. Thanks

**Comment by AlexisWilke** [comment]
Nope. It still doesn't work on a reboot.

```
alexis@localstack:~$ docker ps -a
CONTAINER ID        IMAGE                          COMMAND                  CREATED             STATUS                       PORTS               NAMES
91335412a2f9        localstack/localstack:latest   "docker-entrypoint.sh"   12 minutes ago      Exited (137) 4 minutes ago                       my_localstack
```

I'm attaching the logs from installation of the new version to the reboot. I then stopped the container.

[localstack-json.log.txt](https://github.com/localstack/localstack/files/3806958/localstack-json.log.txt)

Doing a start after the stop restarts the container just fine and it works as expected. The logs here do not include that step.

**Comment by AlexisWilke** [comment]
Okay, I found the main culprit: you have a [restart setting](https://docs.docker.com/config/containers/start-containers-automatically/) on a container and by default it's set to `no`.

That parameter can be set when you first call the `run` command:

    docker run --restart always [...]

and if you already have a container, you can update the container:

    docker update --restart always CONTAINER

Then it does auto-restart as expected.

The possible values are `no` (which is the default!), `on-failure`, `always`, and `unless-stopped`.

**IMPORTANT NOTE:** It looks like on Ubuntu, by default, the docker service is disabled. So on a reboot the service stays off which obviously means your containers are not going to start. To fix this issue, you generally have to do:

    sudo systemctl enable docker
    sudo systemctl start docker

The `enable` will make docker remember to auto-start on your next reboot.

`localstack` itself works as expected.
