### ISSUE TITLE
Tag retrieval broken in Cloudwatch Logs & Cloudwatch Events.

### ISSUE THREAD

**Issue by ballwood** [localstack/localstack#1698]
Using terraform to deploy the following two. TF likes scraping the API's  to see whats changes before it deploys

`Error: error setting tags: Error retreiving tags for arn:aws:events:us-west-2:111111111111:rule/terraform-20191029212821251900000001: SerializationError: failed to unmarshal error message`

Account number incorrect, region incorrect, might be causing the issue?

`Error: error listing CloudWatch Logs Group "/aws/lambda/local-engine-agentEventPublish" tags: SerializationError: failed to unmarshal error message
        status code: 500, request id:`

localstack_1  | NotImplementedError: The list_tags_log_group action has not been implemented in class <class 'moto.logs.responses.LogsResponse'>

**Comment by tgrades** [comment]
I have the same issue with list_tags_log_group. It's added in the last version of moto.
https://github.com/spulec/moto/blame/master/CHANGELOG.md#L25
But I assume localstack is using https://github.com/localstack/moto right?

**Comment by tgrades** [comment]
@whummer Sorry for pinging you, but this issue is pretty old and I worry that you guys wont notice it.
Is there a possibility in near future to update moto to latest version?

**Comment by clopatofsky** [comment]
I have the same issue here. Would be great to solve this issue for having the same stack of terraform resources for local environment.

**Comment by tgrades** [comment]
@whummer Hi. Sorry for a late response. I gave up setting up localstack for some time and just recently got back to it. I decided that I don't actually need Cloudwatch Logs, but events works. The only issue right now is that 60 min is a valid rate for AWS, but local stack throw an error that it can't be greater than 59, but this is a separate issue and easily fixable from my side
