### ISSUE TITLE
Testing GET with apigateway fails

### ISSUE THREAD

**Issue by a-kaly** [localstack/localstack#1702]
curl -i http://localhost:4567/restapis/285691604A-Z/test/_user_request_/HowMuchIsTheFish                                                                                            

HTTP/1.1 500 Internal Server Error
Server: BaseHTTP/0.6 Python/3.6.8
Date: Wed, 30 Oct 2019 13:46:07 GMT
x-amzn-errortype: InternalFailure
Content-Type: text/html; charset=utf-8
Content-Length: 532
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: HEAD,GET,PUT,POST,DELETE,OPTIONS,PATCH
Access-Control-Allow-Headers: authorization,content-type,content-md5,cache-control,x-amz-content-sha256,x-amz-date,x-amz-security-token,x-amz-user-agent

{"Type": "Server", "message": "Error executing Lambda function : 'NoneType' object has no attribute 'name' Traceback (most recent call last):\n  File \"/opt/code/localstack/localstack/services/awslambda/lambda_api.py\", line 311, in run_lambda\n    context = LambdaContext(func_details, version)\n  File \"/opt/code/localstack/localstack/services/awslambda/lambda_api.py\", line 90, in __init__\n    self.function_name = func_details.name()\nAttributeError: 'NoneType' object has no attribute 'name'\n", "__type": "InternalFailure"}%     

apigateway is setup but it is unable to invoke lambda? can anyone help please?

**Comment by pmcdowell-okta** [comment]
@a-kaly I can tell from the URL parameter **HowMuchIsTheFish**, that you and I are following a similar response someone posted on Stackoverflow of how the get the API Gateway working with localstack.

I too and struggling, and I can find little to no documentation around this, so maybe we could compare some notes.

I'm using Terraform, but I tried following the same thread you did and either I make soo many typos or something isn't working.

Using Terraform I get an error message regarding permissions.

If you get your stuff working let me know, and I'd be glad to show what I have. My stuff works on AWS, but can't quite get it working on Localstack.

**Comment by a-kaly** [comment]
_I got it to work by using the below if it helps._

#!/bin/bash

API_NAME=request-logger
REGION=us-east-1
STAGE=test

function fail() {
    echo $2
    exit $1
}

aws --endpoint-url http://localhost:4574 lambda create-function \
    --function-name ${API_NAME} \
    --handler main.entrypoint \
    --runtime python3.7 \
    --role something \
    --zip-file fileb://request-logger.zip && rm request-logger.zip

[ $? == 0 ] || fail 1 "Failed: AWS / lambda / create-function"

LAMBDA_ARN=$(aws --endpoint-url http://localhost:4574 lambda list-functions --query "Functions[?FunctionName==\`${API_NAME}\`].FunctionArn" --output text --region ${REGION})

aws --endpoint-url http://localhost:4567 apigateway create-rest-api \
    --region ${REGION} \
    --name ${API_NAME}

[ $? == 0 ] || fail 2 "Failed: AWS / apigateway / create-rest-api"

API_ID=$(aws --endpoint-url http://localhost:4567 apigateway get-rest-apis --query "items[?name==\`${API_NAME}\`].id" --output text --region ${REGION})
PARENT_RESOURCE_ID=$(aws --endpoint-url http://localhost:4567 apigateway get-resources --rest-api-id ${API_ID} --query 'items[?path==`/`].id' --output text --region ${REGION})

aws --endpoint-url http://localhost:4567 apigateway create-resource \
    --region ${REGION} \
    --rest-api-id ${API_ID} \
    --parent-id ${PARENT_RESOURCE_ID} \
    --path-part "{somethingId}"

[ $? == 0 ] || fail 3 "Failed: AWS / apigateway / create-resource"

RESOURCE_ID=$(aws --endpoint-url http://localhost:4567 apigateway get-resources --rest-api-id ${API_ID} --query 'items[?path==`/{somethingId}`].id' --output text --region ${REGION})

aws --endpoint-url http://localhost:4567 apigateway put-method \
    --region ${REGION} \
    --rest-api-id ${API_ID} \
    --resource-id ${RESOURCE_ID} \
    --http-method ANY \
    --request-parameters "method.request.path.somethingId=true" \
    --authorization-type "NONE" \

[ $? == 0 ] || fail 4 "Failed: AWS / apigateway / put-method"

aws --endpoint-url http://localhost:4567 apigateway put-integration \
    --region ${REGION} \
    --rest-api-id ${API_ID} \
    --resource-id ${RESOURCE_ID} \
    --http-method ANY \
    --type AWS_PROXY \
    --integration-http-method POST \
    --uri arn:aws:apigateway:${REGION}:lambda:path//2015-03-31/functions/${LAMBDA_ARN}/invocations \
    --passthrough-behavior WHEN_NO_MATCH \

[ $? == 0 ] || fail 5 "Failed: AWS / apigateway / put-integration"

aws --endpoint-url http://localhost:4567 apigateway create-deployment \
    --region ${REGION} \
    --rest-api-id ${API_ID} \
    --stage-name ${STAGE} \

[ $? == 0 ] || fail 6 "Failed: AWS / apigateway / create-deployment"

ENDPOINT=http://localhost:4567/restapis/${API_ID}/${STAGE}/_user_request_/HowMuchIsTheFish

echo "API available at: ${ENDPOINT}"

echo "Testing GET:"
curl -i ${ENDPOINT}

echo "Testing POST:"
curl -iX POST ${ENDPOINT}

**Comment by whummer** [comment]
Thanks for confirming that it is now working @a-kaly . @pmcdowell-okta if it still isn't working for you, can you please open another issue with a small, isolated test case that helps reproduce this issue? Thanks!

**Comment by han-so1omon** [comment]
@a-kaly What would the ENDPOINT translate to in the general case? Is it still `.../test/_user_request_/HowMuchIsTheFish`?
