### ISSUE TITLE
Add SNS subscription filter policy "exists" operator support

### ISSUE THREAD

**Issue by ryan-gustafson** [localstack/localstack#1703]
The ["exists"](https://docs.aws.amazon.com/sns/latest/dg/sns-subscription-filter-policies.html#attribute-key-matching) operator is not supported in the SNS Filter Policy.  This operator works upon attribute keys, but only attribute value based operators seem to currently work:

https://github.com/localstack/localstack/blob/950699c7b1256afc61d15dbff2a519e2db10635e/localstack/services/sns/sns_listener.py#L467-L482

Although using _FilterPolicy_ at all seems problematic at the moment too: https://github.com/localstack/localstack/issues/684#issuecomment-547978594

**Comment by whummer** [comment]
Thanks for reporting @ryan-gustafson . This should be fixed in #2292 - can you please give it a try with the `latest` version? Please report here if the problem persists. Thanks
