### ISSUE TITLE
Lambda update_function_configuration() returns an empty dict

### ISSUE THREAD

**Issue by lucianthorr** [localstack/localstack#1710]
The update_function_configuration currently returns an empty dict no matter what but certain lambda libraries (ie, Zappa) require a realistic return value... which is simply the current config after being updated.

https://github.com/localstack/localstack/blob/9cba1010dfcbf2b7672df4d7da46b7e8ab287f64/localstack/services/awslambda/lambda_api.py#L872

https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/lambda.html#Lambda.Client.update_function_configuration

There might also be some other magic enriching that result but my quick read-through looks like it's an empty dict.

**Comment by whummer** [comment]
Thanks for reporting @lucianthorr - this should be fixed in #1717 1739
