### ISSUE TITLE
Unable to execute template actions against localstack SES

### ISSUE THREAD

**Issue by kevinfguo** [localstack/localstack#1712]
Any template action I make against localstack's SES results in a 500 response. If I do something as simple as:

`aws --endpoint-url=http://localhost:4579 ses list-templates`

I get a 500. Same thing if I make an action such as:

`aws ses get-template --template-name test`

I would expect the proper error response, such as:
`An error occurred (TemplateDoesNotExist) when calling the GetTemplate operation: Template test does not exist.`

**Comment by bratzelk** [comment]
+1

**Comment by XiomarG** [comment]
the error log is `NotImplementedError: The get_template action has not been implemented`. Does this mean this ses module is not functioning partially? i can list identities

**Comment by whummer** [comment]
Thanks for reporting @kevinfguo @bratzelk @XiomarG . This should be fixed in the meantime, can you please do a `docker pull localstack/localstack` and give it a try with the latest version of the Docker image? Please report here if the problem persists. Thanks!
