### ISSUE TITLE
SerializationError: failed decoding JSON RPC response caused by: unsupported JSON value

### ISSUE THREAD

**Issue by pmcdowell-okta** [localstack/localstack#1717]
I'm using Terraform to create an API Gateway and required Lambda Functions.

I do realize this might not be supported, and I can work around any limitations that Localstack might have, **But**, I have no idea how to debug the response I get from Terraform, and/or then dig into Localstack to see what is getting sent or returned.

If anyone has any guidance, suggestions, or examples they would greatly be appreciated.

-Patrick@Okta

`Error: Error applying plan:

1 error(s) occurred:

* aws_lambda_permission.apigw_lambda: 1 error(s) occurred:

* aws_lambda_permission.apigw_lambda: SerializationError: failed decoding JSON RPC response
caused by: unsupported JSON value (map[Id:LambdaFuncAccess-4bbef270 PolicyArn:arn:aws:iam::000000000000:policy/lambda_policy_terraformLambdaWebsite Statement:[map[Action:lambda:InvokeFunction Effect:Allow Resource:arn:aws:lambda:us-east-1:000000000000:function:terraformLambdaWebsite Sid:4bbef270]] Version:2012-10-17])`

**Comment by pmcdowell-okta** [comment]
Here is a github repo that has the code required to see the error.

https://github.com/pmcdowell-okta/localstack-terraform-apigateway

**Comment by whummer** [comment]
Thanks for providing the Github repo with a reproducible example @pmcdowell-okta . This should be fixed in #1739 - I was able to get your example started via Terraform. Can you please give it a try and report here? Thanks
