### ISSUE TITLE
Setting TEST_AWS_ACCOUNT_ID does not change the account ID in ARNs

### ISSUE THREAD

**Issue by Jaystified** [localstack/localstack#1728]
It is my understanding that setting an environment varialbe `TEST_AWS_ACCOUNT_ID` for localstack sets that as the AWS account for the user in localstack.

However, setting it does not actually change any ARNs. For example:

1. Start localstack using `TEST_AWS_ACCOUNT_ID="111111111111" DEBUG=1 localstack start`
2. Deploy anything with an ARN (in this example I deployed a lambda)
3. Check the ARN. Example output for lambda:
```json
$ awslocal lambda list-functions
{
    "Functions": [
        {
            "FunctionName": "localtest-local-hello",
            "FunctionArn": "arn:aws:lambda:us-east-1:000000000000:function:localtest-local-hello",
            "Runtime": "nodejs10.x",
            "Role": "test_role",
            "Handler": "handler.hello",
            "CodeSize": 3077,
            "Description": "",
            "Timeout": 6,
            "MemorySize": 1024,
            "LastModified": "2019-11-06T06:43:53.451+0000",
            "CodeSha256": "V77gR13o90ET7+XquXBBc3Rxr1qDu1bE7S+A0Wbx5ys=",
            "Version": "$LATEST",
            "TracingConfig": {
                "Mode": "PassThrough"
            },
            "RevisionId": "3d4ed679-c1a9-4b7e-ad9e-f27e8543c5e9"
        }
    ]
}
```

ARN is still 000000000000

**Comment by whummer** [comment]
Thanks @Jaystified - should be fixed in #1731. Can you please try installing the latest version 0.10.5 of the `localstack` pip package. Thanks
