### ISSUE TITLE
S3 forbidden access when reading a bucket by a lambda function

### ISSUE THREAD

**Issue by arik123456** [localstack/localstack#1732]
I'm trying to use localstack to create a lambda function which downloads files from a s3 bucket but it fails with a Forbidden status

The lambda's code that download the file uses the boto3 library :

```
def handler(event, context):

    s3 = boto3.resource("s3")

    bucket = s3.Bucket("input")

    bucket.download_file("file", "/tmp")

```

The steps I've taken to create the bucket and upload the file are : 

- **Create a bucket** : 
`awslocal s3 mb s3://input`

- **Grant it with public access**
`awslocal s3api put-bucket-acl --bucket input  --acl public-read-write`

- **Upload a file into the bucket**
`awslocal s3 cp file s3://input/file`

The steps to create the lambda and run it are : 
- **Creating a zip file containing all the necessary files for the lambda**

- **Create the lambda function**

`awslocal lambda create-function     --function-name f1     --runtime python2.7     --handler main.handler     --memory-size 128     --zip-file fileb://main.zip     --role r1`

- **Run the function**

`awslocal lambda invoke --function-name f1 --payload '', my_test`

When I run the lambda function I receive the following exception : 

`An error occurred (403) when calling the HeadObject operation: Forbidden: ClientError
Traceback (most recent call last):
...
  File "/var/runtime/boto3/s3/inject.py", line 246, in bucket_download_file
    ExtraArgs=ExtraArgs, Callback=Callback, Config=Config)
  File "/var/runtime/boto3/s3/inject.py", line 172, in download_file
    extra_args=ExtraArgs, callback=Callback)
  File "/var/runtime/boto3/s3/transfer.py", line 307, in download_file
    future.result()
  File "/var/runtime/s3transfer/futures.py", line 106, in result
    return self._coordinator.result()
  File "/var/runtime/s3transfer/futures.py", line 265, in result
    raise self._exception
ClientError: An error occurred (403) when calling the HeadObject operation: Forbidden
`

**Comment by ciaranevans** [comment]
@arik123456 

Assuming from what you've put that both Lambda and S3 are 'LocalStack-ed' then you need to point the s3 boto client to the LocalStack url: ` s3 = boto3.resource("s3", endpoint_url="http://localhost:4572")` or similar.

**Comment by arik123456** [comment]
I tried this but now I get a connection error :


```
An error occurred (InternalFailure) when calling the Invoke operation (reached max retries: 4): Error executing Lambda function arn:aws:lambda:us-east-1:000000000000:function:f2: Lambda process returned error status code: 1. Output:
START RequestId: 0a5d1d68-ad08-4ee1-bb46-ede18f301223 Version: $LATEST

...
Could not connect to the endpoint URL: "http://localhost:4572/input/file": EndpointConnectionError
Traceback (most recent call last):

...

  File "/var/runtime/boto3/s3/inject.py", line 246, in bucket_download_file
    ExtraArgs=ExtraArgs, Callback=Callback, Config=Config)
  File "/var/runtime/boto3/s3/inject.py", line 172, in download_file
    extra_args=ExtraArgs, callback=Callback)
  File "/var/runtime/boto3/s3/transfer.py", line 307, in download_file
    future.result()
  File "/var/runtime/s3transfer/futures.py", line 106, in result
    return self._coordinator.result()
  File "/var/runtime/s3transfer/futures.py", line 265, in result
    raise self._exception
EndpointConnectionError: Could not connect to the endpoint URL: "http://localhost:4572/input/file"
```

**Comment by ciaranevans** [comment]
Bother sorry. Are your lambdas running in containers? If so, try `http://172.17.0.1:4572` that's the docker network address.

**Comment by arik123456** [comment]
Great It works.
Thanks

**Comment by sagarjunnarkar** [comment]
Above answer helped me to solve same problem for me.
I am using **s3fs** and I followed https://s3fs.readthedocs.io/en/latest/#self-hosted-s3
```python
AWS_DEFAULT_REGION='us-west-2'
AWS_SECRET_ACCESS_KEY='test'
AWS_SECRET_ACCESS_KEY='test'
s3 = s3fs.S3FileSystem(anon=False,client_kwargs={
         'endpoint_url': 'http://localhost:4566'
      })
```
When you create lambda function at that time s3fs and hence aiobotocore is initialized.
It requires ENV, and endpoint url. Otherwise you will get 403.
 
This solved my 403 forbidden issue for me.
