### ISSUE TITLE
S3 objects larger than 6MB cannot be accessed via the S3 URL (403 forbidden)

### ISSUE THREAD

**Issue by Jaystified** [localstack/localstack#1733]
Normally S3 objects in localstack can be accessed via `http://localhost:4572/bucket/key`.

However, if the object is 7 MBs or larger, attempting to access it via this URL will result in a 403 error. Objects any smaller are retrieved as expected.

(Possibly related: Lambda response size is limited to 6MB. Perhaps that is being used by accident?)

**Comment by whummer** [comment]
Thanks for reporting @Jaystified . Can you please provide more details - haven't been able to reproduce this.

Did you add `public-read` ACLs on the object or bucket level, e.g., by running `awslocal s3api put-bucket-acl --bucket buck1 --acl public-read`? If not, then 403 would in fact be the expected response. If we're not returning 403 for smaller objects, that that might be a bug.

Would be great if you could share a few shell commands (using `awslocal`) to reproduce this issue. Thanks!

**Comment by Jaystified** [comment]
Commands I'm using to reproduce:
```bash
sudo dd bs=1024 count=6144 skip="$RANDOM" if=/dev/sda of=6mb.bin
sudo dd bs=1024 count=61440 skip="$RANDOM" if=/dev/sda of=60mb.bin
```
Here's both the commands and what I'm seeing:
```bash
$ sudo dd bs=1024 count=6144 skip="$RANDOM" if=/dev/sda of=6mb.bin
6144+0 records in
6144+0 records out
6291456 bytes (6.3 MB, 6.0 MiB) copied
$ sudo dd bs=1024 count=61440 skip="$RANDOM" if=/dev/sda of=60mb.bin
61440+0 records in
61440+0 records out
62914560 bytes (63 MB, 60 MiB) copied
$ awslocal s3 mb s3://test
make_bucket: test
$ awslocal s3api put-bucket-acl --bucket test --acl public-read


```
