### ISSUE TITLE
Cannot create SNS topic with a fake region name (test-region)

### ISSUE THREAD

**Issue by skhare-r7** [localstack/localstack#1735]
Hello,
Is there a good reason why 
https://github.com/localstack/localstack/blob/f7a55fbb598afd3e10546957f41ae3a52225b069/localstack/services/sns/sns_listener.py#L37 exists?

I'm trying to create an SNS topic using docker-compose and it is refusing to let me use 'test-region' as the DEFAULT_REGION

**Comment by whummer** [comment]
Thanks for reporting @skhare-r7 . Unfortunately, arbitrary region names are currently not supported - there are too many places throughout the code base which assume a valid AWS region to be used. 

Do you have a specific reason why this would be required, and you cannot use one of the predefined AWS regions?

Going to close this as "won't fix" for now - but happy to discuss more if you are willing to provide a suitable solution that works across APIs. Thanks!
