### ISSUE TITLE
SNS rejecting dashes in e164 phonenumber format when subscribing sms

### ISSUE THREAD

**Issue by john20xdoe** [localstack/localstack#1748]
Hi all, this is a bugfix in **moto** that has been merged recently. (See full description and repro steps here:)
https://github.com/spulec/moto/issues/2529

Question: Is it possible to know when this will reflect in the recent localstack image?
I have recently pulled `image: localstack/localstack` and the bug is still occurring.

**Comment by whummer** [comment]
Thanks for reporting @john20xdoe - the latest version of `moto` should be included in the `latest` version of the `localstack/localstack` Docker image. We're using a fork of moto that we use to pull in changes regularly. Please report here if the problem persists. Thanks!

**Comment by john20xdoe** [comment]
thanks @whummer , seems to be fixed now. Need to delete my localstack image and repeat docker pull, and use localstack/localstack:latest instead of just localstack/localstack.
