### ISSUE TITLE
SNS is ignoring region?

### ISSUE THREAD

**Issue by janlau1111** [localstack/localstack#1749]
## SumUp

We start localstack latest docker-image and create a sns-topic via aws-cli. We then go on and check for the created topic and can see that the region we set in the creation command is ignored. 

`aws --endpoint="http://localhost:4575" --region=eu-central-1 sns create-topic --name something`

## Expected Behavior

We would expect a topic in the form `arn:aws:sns:eu-central-1:000000000000:something`.

## Current Behavior

We get `arn:aws:sns:us-east-1:000000000000:something`.

## Possible Solution

When we use the older version: 0.10.5 it works again. 

## Steps to Reproduce

```

1. docker pull localstack/localstack:latest
2. aws --endpoint="http://localhost:4575" --region=eu-central-1 sns create-topic --name something
3. aws --endpoint="http://localhost:4575" --region=eu-central-1 sns list-topics
4. then be sad :(

```

Thank you!

**Comment by whummer** [comment]
Thanks for reporting @janlau1111 . Please note that this request conflicts with #731. We have recently merged pull request #1744 which uses the server-side configuration `DEFAULT_REGION` as the region to use.

Can you please try setting `DEFAULT_REGION=eu-central-1` in the terminal where you're starting the LocalStack process? Thanks

**Comment by janlau1111** [comment]
@whummer With latest docker-image and setting `DEFAULT_REGION` to eu-central-1 the SNS ist create in `eu-central-1`. 

docker-compose with DEFAULT_REGION:
```
version: '3'
  
services:
  localstack:
    image: localstack/localstack
    ports:
    - "4572:4572"
    - "4574:4574"
    - "4575:4575"
    - "4576:4576"
    - "4582:4582"
    - "4592:4592"
    - "4593:4593"
    - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
    - DEFAULT_REGION=eu-central-1
    - SERVICES=cloudwatch,s3,lambda,sns,sqs,iam
    - DEBUG=${DEBUG- }
    - DATA_DIR=${DATA_DIR- }
    - PORT_WEB_UI=${PORT_WEB_UI- }
    - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
    - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
    - DOCKER_HOST=${LOCALSTACK_DOCKER_HOST-unix:///var/run/docker.sock}
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
~                                                        
```
Creating SNS-Topic:

```
aws --endpoint="http://localhost:4575" --region=eu-central-1 sns list-topics                                                                                      
_{
    "Topics": []
}_
[...]
aws --endpoint="http://localhost:4575" --region=eu-central-1 sns create-topic --name something                                                                
_{
    "TopicArn": "arn:aws:sns:eu-central-1:000000000000:something"
}_
[...]
aws --endpoint="http://localhost:4575" --region=eu-central-1 sns list-topics                                                                                      
_{
    "Topics": [
        {
            "TopicArn": "arn:aws:sns:eu-central-1:000000000000:something"
        }
    ]
}_
```
But this still means that the client setting "region" is ignored? Is that the intended behavior for the future?

Creating SNS in `eu-west-1` with `DEFAULT-REGION=eu-central-1`:
```
aws --endpoint="http://localhost:4575" --region=**eu-west-1** sns create-topic --name something                                                                  
{
    "TopicArn": "arn:aws:sns:**eu-central-1**:000000000000:something"
}
```

**Comment by whummer** [comment]
Thanks for confirming.

> But this still means that the client setting "region" is ignored? Is that the intended behavior for the future?

For now, this is the default behavior, since LocalStack by default is single-region (client-side regions are ignored, regions are taken from `DEFAULT_REGION` or `AWS_DEFAULT_REGION` on the server side). This behavior may change in the future, though. (In fact, we've already started working into this direction in the Pro version of LocalStack.)

Thanks.

**Comment by mlhrAnjaria** [comment]
Is this fixed?
