### ISSUE TITLE
Error: No module named 'localstack_ext.utils.aws.aws_models'

### ISSUE THREAD

**Issue by imriss** [localstack/localstack#1754]
When trying to start `localstack` with `--docker`, this error encountered:
```
2019-11-12T20:32:58:WARNING:bootstrap.py: Unable to load plugins from file /opt/code/localstack/.venv/lib/python3.7/site-packages/localstack_ext/plugins.py: No module named 'localstack_ext.utils.aws.aws_models'
```

The command used to start `localstack':
```
DNS_ADDRESS=127.0.0.1 SERVICES=s3,eks LOCALSTACK_API_KEY=23456789 localstack start --docker; 
```

When I checked inside the running container, these files were present in `/opt/code/localstack/.venv/lib/python3.7/site-packages/localstack_ext/utils/aws`:
```
__init__.py.enc    aws_models.py.enc  aws_utils.py.enc
```

Thanks in-advance

**Comment by tgrades** [comment]
I have the same thing. Also not sure if it's related but I get `KeyError: '${env:AWS_REGION}'` error in cloudformation related code. I'm thinking maybe it's bc localstack is missing this file.

**Comment by imriss** [comment]
The full `docker run` in the logs:
```
docker run -it -e SERVICES="s3,eks,ecs" -e LOCALSTACK_HOSTNAME="localhost" -e DEFAULT_REGION="us-east-1" -e LOCALSTACK_API_KEY="23456789" -e LOCALSTACK_HOSTNAME="localhost" -e PYTHONPATH=/opt/code/localstack/.venv/lib/python3.7/site-packages --rm --privileged --name localstack_main -p 8080:8080   -p 4601:4601 -p 4602:4602 -p 4572:4572  -v "/tmp/localstack:/tmp/localstack" -v "/var/run/docker.sock:/var/run/docker.sock" -e DOCKER_HOST="unix:///var/run/docker.sock" -e HOST_TMP_FOLDER="/tmp/localstack" "localstack/localstack"
```
The `AWS_REGION` is set to `us-east-1`.

**Comment by tgrades** [comment]
@imriss I managed to set everything up and deploy to localstack just a few minutes ago. So it is working even with this warning for me

**Comment by imriss** [comment]
@tgrades That is good. For me the main issue is later on when I call the `eks` service:
```
$ awslocal eks list-clusters
Connection was closed before we received a valid response from endpoint URL: "http://localhost:4602/clusters".
```
The `ec2` service works fine (if I do not set `SERVICES`):
```
awslocal ec2 describe-instances
{
    "Reservations": []
}
```
How can I set it up to have `eks` also deployed? Any advise? Thanks

**Comment by tgrades** [comment]
@imriss Can you pass `-e DEBUG=1` to docker and look if there some errors on the docker side?

**Comment by whummer** [comment]
Thanks for reporting @imriss . You can ignore the `No module named 'localstack_ext.utils.aws.aws_models'` error, the APIs should come up regardless.

What does your `SERVICES` configuration look like? Do you see the following in the terminal log output?
```
...
Starting mock EKS service (http port 4602)...
...
Ready.
```
Can you please give it another try after pulling the `localstack/localstack:latest` Docker image?

**Comment by thetumper** [comment]
I still see it with latest.

2019-11-19T21:29:29:WARNING:bootstrap.py: Unable to load plugins from file /opt/code/localstack/.venv/lib/python3.7/site-packages/localstack_ext/plugins.py: No module named 'localstack_ext.utils.aws.aws_models'

**Comment by Ezku** [comment]
Here's my docker-compose.yml:

```
version: "3.7"
services:
  localstack:
    image: localstack/localstack
    ports:
      - "4567-4584:4567-4584"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - LOCALSTACK_SERVICES=S3
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - localstack-data:/tmp/localstack
volumes:
  localstack-data:
```

Fails with the same error as above:

```
localstack_1  | Waiting for all LocalStack services to be ready
localstack_1  | 2019-12-02 08:40:52,849 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
localstack_1  | 2019-12-02 08:40:52,851 INFO supervisord started with pid 13
localstack_1  | 2019-12-02 08:40:53,853 INFO spawned: 'dashboard' with pid 19
localstack_1  | 2019-12-02 08:40:53,855 INFO spawned: 'infra' with pid 20
localstack_1  | (. .venv/bin/activate; bin/localstack web)
localstack_1  | 2019-12-02 08:40:53,862 INFO success: dashboard entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
localstack_1  | (. .venv/bin/activate; exec bin/localstack start --host)
localstack_1  | 2019-12-02 08:40:54,867 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
localstack_1  | 2019-12-02T08:40:56:WARNING:bootstrap.py: Unable to load plugins from file /opt/code/localstack/.venv/lib/python3.7/site-packages/localstack_ext/plugins.py: No module named 'localstack_ext.utils.aws.aws_models'
```

Then continues restarting the process but never gets out of the loop.

**Comment by arafel** [comment]
FYI I see a similar thing - the warning about AWS plugin and the looping start/fail infra state. I haven't been able to get any useful debug out of it yet I'm afraid.

macOS 10.14.6, docker-compose 1.24.1, docker 19.03.5, localstack/localstack image is c457d4e02672 (docker says 3 weeks ago).
