### ISSUE TITLE
[Feature] AWS Transfer (SFTP service)

### ISSUE THREAD

**Issue by bademux** [localstack/localstack#1759]
Hello,
Is SFTP API supported?
https://docs.aws.amazon.com/transfer/latest/userguide/API_Operations.html

Thanks for great project!

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-137) by [Unito](https://www.unito.io/learn-more)

**Comment by caiofralmeida** [comment]
The feature transfer SFTP is essential for me. Are you thinking about this?

If doesn't available you have any project to recommend?

Thank you for all contributions.

**Comment by jheinnic** [comment]
Seconding the previous poster's sentiment as I just found this issue during a google search in response to a peer's need for same while testing a lamba function.

**Comment by thrau** [comment]
This feature is available in LocalStack pro. Should you have problems with the pro version, please let us know in Slack, thanks!
