### ISSUE TITLE
can't create API gateway

### ISSUE THREAD

**Issue by zydrunasl** [localstack/localstack#176]
Hello,
i'm unable to create API gateway using latest localstack docker image.

ubuntu@ubuntuzl:~/localstack$ docker image ls |grep localstack
atlassianlabs/localstack                             latest              5631fe82b0ee        7 hours ago         1.21GB

ubuntu@ubuntuzl:~/localstack$ docker pull atlassianlabs/localstack
Using default tag: latest
latest: Pulling from atlassianlabs/localstack
Digest: sha256:62dcf60e8dc9e0c11bfa65f5113f88605ff9722f08efa3d4967d8e58b77465d4
Status: Image is up to date for atlassianlabs/localstack:latest

ubuntu@ubuntuzl:~/localstack$ date
Mon 17 Jul 13:14:41 EEST 2017
ubuntu@ubuntuzl:~/localstack$ aws --endpoint-url=http://localhost:4567 apigateway create-rest-api --name myapigw

Expecting value: line 1 column 1 (char 0)
ubuntu@ubuntuzl:~/localstack$

on aws 
ubuntu@ubuntuzl:~//localstack$ aws  apigateway create-rest-api --name myapigw --profile=test
{
    "name": "myapigw",
    "id": "tvdb80f4h3",
    "createdDate": 1499862274
}

**Comment by whummer** [comment]
Hi @zydrunasl , thanks for reporting. Just to clarify, how did you actually *start* LocalStack after pulling the Docker image?

The preferred/recommended way of starting LocalStack is via:
```
pip install localstack
localstack start --docker
```
After LocalStack has started up using the above commands, you can use the `aws ...` command line tool to create resources.

Can you please confirm that the above commands work? If it does not work, please post any relevant error output. Thanks

**Comment by zydrunasl** [comment]
Hello,
i'm using it from docker-compose.yml file
  localstack:
    image: atlassianlabs/localstack
    networks:
      - net
    ports:
      - "4567-4582:4567-4582"
      - "8888:8080"
    environment:
      - SERVICES=${SERVICES- }
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEFAULT_REGION=eu-central-1
    volumes:
      - "${TMP_DIR:-/tmp/localstack}:${TMP_DIR:-/tmp/localstack}"
      - "/var/run/docker.sock:/var/run/docker.sock"
We need it as docker image to use it with other images

Aslo i tried pip install localstack but i get 

....
  Successfully installed Jinja2-2.9.6 MarkupSafe-1.0 Werkzeug-0.12.2 airspeed-0.5.5.dev20160812 amazon-kclpy-1.4.4 asn1crypto-0.22.0 awscli-1.11.86 boto-2.46.1 boto3-1.4.4 botocore-1.5.49 cachetools-0.8.0 cffi-1.10.0 click-6.7 colorama-0.3.7 cookies-2.2.1 coverage-4.0.3 cryptography-1.9 decorator-4.1.1 dicttoxml-1.7.4 docopt-0.6.2 docutils-0.13.1 ecdsa-0.13 elasticsearch-5.3.0 enum34-1.1.6 envs-1.2.2 flask-0.10.1 flask-cors-3.0.3 flask-swagger-0.2.12 funcsigs-1.0.2 future-0.16.0 futures-3.1.1 idna-2.5 ipaddress-1.0.18 itsdangerous-0.24 jmespath-0.9.3 jsonpath-rw-1.4.0 localstack-ext-0.6.1.3 mock-2.0.0 moto-ext-1.0.1.4 nose-1.3.7 pbr-3.1.1 pep8-1.7.0 ply-3.10 psutil-5.2.0 pyOpenSSL-17.0.0 pyYAML-3.12 pyaml-16.12.2 pyasn1-0.2.3 pycparser-2.18 pycrypto-2.6.1 pyminifier-2.1 python-coveralls-2.7.0 python-dateutil-2.6.1 python-jose-1.3.2 pytz-2017.2 requests-2.11.0 requests-aws4auth-0.9 rsa-3.4.2 s3transfer-0.1.10 sh-1.12.14 srp-ext-1.0.7 subprocess32-ext-3.2.8.2 terminaltables-3.1.0 urllib3-1.21.1 warrant-0.2.0 xmltodict-0.10.2
  make[1]: Leaving directory '/tmp/pip-build-hSL2m0/localstack'
  make[1]: Entering directory '/tmp/pip-build-hSL2m0/localstack'
  (test -e localstack/infra/amazon-kinesis-client/aws-java-sdk-sts.jar || \
                { (test -e aws-java-sdk-sts.jar || curl -o aws-java-sdk-sts.jar http://central.maven.org/maven2/com/amazonaws/aws-java-sdk-sts/1.11.14/aws-java-sdk-sts-1.11.14.jar); \
                        mkdir -p localstack/infra/amazon-kinesis-client; \
                        cp aws-java-sdk-sts.jar localstack/infra/amazon-kinesis-client/aws-java-sdk-sts.jar; }) && \
        (test -e localstack/infra/localstack-utils.jar || curl -o localstack/infra/localstack-utils.jar https://bitbucket.org/atlassian/localstack/raw/mvn/release/com/atlassian/localstack-utils/1.0-SNAPSHOT/localstack-utils-1.0-SNAPSHOT.jar)
  make[1]: Leaving directory '/tmp/pip-build-hSL2m0/localstack'
  make[1]: Entering directory '/tmp/pip-build-hSL2m0/localstack'
  echo "Compiling"
  Compiling
  javac -cp /tmp/pip-build-hSL2m0/localstack/build/bdist.linux-x86_64/wheel/localstack/infra/amazon-kinesis-client/aws-java-sdk-sts.jar:/tmp/pip-build-hSL2m0/localstack/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/jackson-databind-2.6.6.jar:/tmp/pip-build-hSL2m0/localstack/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/httpcore-4.4.4.jar:/tmp/pip-build-hSL2m0/localstack/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/ion-java-1.0.2.jar:/tmp/pip-build-hSL2m0/localstack/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/jackson-annotations-2.6.0.jar:/tmp/pip-build-hSL2m0/localstack/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/jackson-dataformat-cbor-2.6.6.jar:/tmp/pip-build-hSL2m0/localstack/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/aws-java-sdk-cloudwatch-1.11.115.jar:/tmp/pip-build-hSL2m0/localstack/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/jackson-core-2.6.6.jar:/tmp/pip-build-hSL2m0/localstack/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/aws-java-sdk-core-1.11.115.jar:/tmp/pip-build-hSL2m0/localstack/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/aws-java-sdk-dynamodb-1.11.115.jar:/tmp/pip-build-hSL2m0/localstack/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/commons-logging-1.1.3.jar:/tmp/pip-build-hSL2m0/localstack/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/commons-codec-1.9.jar:/tmp/pip-build-hSL2m0/localstack/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/joda-time-2.8.1.jar:/tmp/pip-build-hSL2m0/localstack/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/httpclient-4.5.2.jar:/tmp/pip-build-hSL2m0/localstack/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/protobuf-java-2.6.1.jar:/tmp/pip-build-hSL2m0/localstack/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/aws-java-sdk-kinesis-1.11.115.jar:/tmp/pip-build-hSL2m0/localstack/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/aws-java-sdk-s3-1.11.115.jar:/tmp/pip-build-hSL2m0/localstack/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/aws-java-sdk-kms-1.11.115.jar:/tmp/pip-build-hSL2m0/localstack/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/guava-18.0.jar:/tmp/pip-build-hSL2m0/localstack/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/jmespath-java-1.11.115.jar:/tmp/pip-build-hSL2m0/localstack/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/amazon-kinesis-client-1.7.5.jar:/tmp/pip-build-hSL2m0/localstack/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/commons-lang-2.6.jar:/tmp/pip-build-hSL2m0/localstack/build/bdist.linux-x86_64/wheel/localstack/utils/kinesis/java localstack/utils/kinesis/java/com/atlassian/*.java
  (test ! -e localstack/ext/java || (cd localstack/ext/java && mvn -q -DskipTests package))
  Makefile:37: recipe for target 'compile' failed
  make[1]: Leaving directory '/tmp/pip-build-hSL2m0/localstack'
  Makefile:16: recipe for target 'install' failed

  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-hSL2m0/localstack/setup.py", line 110, in <module>
      'Topic :: Software Development :: Testing',
    File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
      dist.run_commands()
    File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/usr/lib/python2.7/dist-packages/wheel/bdist_wheel.py", line 215, in run
      self.run_command('install')
    File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 61, in run
      return orig.install.run(self)
    File "/usr/lib/python2.7/distutils/command/install.py", line 613, in run
      self.run_command(cmd_name)
    File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-hSL2m0/localstack/setup.py", line 63, in run
      do_make_install()
    File "/tmp/pip-build-hSL2m0/localstack/setup.py", line 43, in do_make_install
      raise e
  subprocess.CalledProcessError: Command 'make install' returned non-zero exit status 2

  ----------------------------------------
  Failed building wheel for localstack
  Running setup.py clean for localstack
Failed to build localstack
Installing collected packages: six, cachetools, airspeed, funcsigs, pbr, mock, argparse, boto, amazon-kclpy, futures, python-dateutil, docutils, jmespath, botocore, s3transfer, pyasn1, rsa, pyYAML, colorama, awscli, boto3, coverage, docopt, urllib3, elasticsearch, itsdangerous, Werkzeug, MarkupSafe, Jinja2, flask, flask-cors, flask-swagger, decorator, ply, jsonpath-rw, pycrypto, srp-ext, pyminifier, terminaltables, click, envs, requests, future, ecdsa, python-jose, warrant, localstack-ext, pytz, xmltodict, cookies, pyaml, dicttoxml, moto-ext, nose, pep8, psutil, ipaddress, idna, asn1crypto, enum34, pycparser, cffi, cryptography, pyOpenSSL, sh, python-coveralls, requests-aws4auth, subprocess32-ext, localstack
  Running setup.py install for localstack ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-hSL2m0/localstack/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-36LYKc-record/install-record.txt --single-version-externally-managed --compile --user --prefix=:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-hSL2m0/localstack/setup.py", line 19, in <module>
        with open('localstack/constants.py') as f:
    IOError: [Errno 2] No such file or directory: 'localstack/constants.py'

    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-hSL2m0/localstack/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-36LYKc-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-hSL2m0/localstack/

**Comment by whummer** [comment]
@zydrunasl Thanks for posting the details. A new version has been published that should (hopefully) fix this installation issue. Can you please give it another try and report back the output here:
```
pip install --upgrade localstack
```
Thanks

**Comment by zydrunasl** [comment]
Hello,
i managed to start docker which was installed with pip
pip uninstall -y localstack
pip install --upgrade localstack
localstack start --docker

but there is still problem with API gateway. I can create SQS.
root@ubuntuzl:localstack# aws --endpoint-url=http://localhost:4576 sqs create-queue --queue-name sqs-test
{
    "QueueUrl": "http://localhost:4576/123456789012/sqs-test"
}
root@ubuntuzl:localstack# aws --endpoint-url=http://localhost:4567 apigateway create-rest-api --name myapigw

An error occurred (500) when calling the CreateRestApi operation (reached max retries: 4): <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>

**Comment by whummer** [comment]
Can you please try starting with debug output enabled:
```
DEBUG=1 localstack start --docker
```
This should print the error  in the terminal when the 500 error happens. Please post the output here. Thanks

**Comment by zydrunasl** [comment]
Hello,
the problem was that i used export AWS_DEFAULT_REGION=eu-central-1.  API GW works only with us-east-1
thank you. I'm closing this issue

**Comment by whummer** [comment]
Good catch, thanks for following up. Note that you can also use the `awslocal` CLI tool (https://github.com/localstack/awscli-local), which allows you to run commands without specifying the endpoint URL:
```
awslocal sqs create-queue --queue-name sqs-test
awslocal apigateway create-rest-api --name myapigw
```
We will also incorporate a fix for the `AWS_DEFAULT_REGION` in the `awslocal` CLI.
