### ISSUE TITLE
POSTing XML to a lambda always throws a 502 Bad Gateway

### ISSUE THREAD

**Issue by jgwconsulting** [localstack/localstack#1762]
We have a lambda deployed to Localstack with an API gateway endpoint configured as AWS_PROXY. Invoking the Lambda with a POST works if the body is empty or contains JSON, however, sending XML in the body (regardless of the Content-Type) always returns a 502. The error in the Localstack log is:

```
localstack_1  | 2019-11-14T13:29:49:ERROR:localstack.services.generic_proxy: Error forwarding request: Expecting value: line 1 column 1 (char 0) Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 240, in forward
localstack_1  |     path=path, data=data, headers=forward_headers)
localstack_1  |   File "/opt/code/localstack/localstack/services/apigateway/apigateway_listener.py", line 35, in forward_request
localstack_1  |     data = data and json.loads(to_str(data))
localstack_1  |   File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
localstack_1  |     return _default_decoder.decode(s)
localstack_1  |   File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
localstack_1  |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
localstack_1  |   File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
localstack_1  |     raise JSONDecodeError("Expecting value", s, err.value) from None
localstack_1  | json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

I thought AWS_PROXY integration was supposed to pass data direct to the Lambda without any attempt to decode or validate? Is there a way to set up the API gateway integration so that it will happily accept XML?

This is the function that we're using to set up API Gateway after the lambda has been deployed: https://gist.github.com/jgwconsulting/0c5597a661cbc6d29aaa346b2aed5020

### UPDATE
_After I've read some of the Localstack code..._

This appears to be caused by ProxyListenerApiGateway assuming that the payload will always be JSON and, thus, barfing when it isn't: https://github.com/localstack/localstack/blob/3b00dc8fe1abf0381f710884b88e07b422f21665/localstack/services/apigateway/apigateway_listener.py#L38

From reading the code it looks like the simplest fix for this problem would be to move this line of code so that it comes after the user request handling, here: https://github.com/localstack/localstack/blob/3b00dc8fe1abf0381f710884b88e07b422f21665/localstack/services/apigateway/apigateway_listener.py#L46

AFAICT the user request handling code will deal happily with data that hasn't been parsed to a dictionary.

**Comment by jgwconsulting** [comment]
Appears to be caused by ProxyListenerApiGateway assuming that the payload will always be JSON and, thus, barfing when it isn't: https://github.com/localstack/localstack/blob/3b00dc8fe1abf0381f710884b88e07b422f21665/localstack/services/apigateway/apigateway_listener.py#L38

**Comment by tbmcphillips** [comment]
+1

**Comment by jgwconsulting** [comment]
@whummer Thanks for including this fix in a recent release and all your amazing work on Localstack. This appears to work fine now so I think this issue can be closed 👍
