### ISSUE TITLE
Start Stop Individual Services

### ISSUE THREAD

**Issue by fsproru** [localstack/localstack#1769]
Hey @whummer,

We started to talk about it in slack and picking it up over here. We're starting to implement the starting and stopping of individual services in [Commandeer](https://getcommandeer.com).

You mentioned you exposed an endpoint to list all running services and to start an individual service. It'll be ideal to hit an endpoint to stand up a service on a specific port.

That being said, this functionality is only available in the newest Docker image of LocalStack. And some users have an older image. Therefore, I see two ways to make it happen:

**1. The new way**
If you can tell us which version of LocalStack have the start and list endpoints exposed we can start hitting HTTP endpoints for this version. In addition to it if you can make an endpoint to stop an individual service it'll be amazing.

**2. The old way**
For the users with an older image of LocalStack, the only way I see to make it work is to capture which services are running, stop the whole container and start it with the new list of services including the service we want to start. While this will most likely work, this option will be very slow since you'll need to restart the whole thing every time you need to turn on an individual service or to change a port.

How can we make starting/stopping individual services more convenient for the users?

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-138) by [Unito](https://www.unito.io/learn-more)

**Comment by silv-io** [comment]
Hello @fsproru, is this feature still needed? LocalStack now supports lazy loading of services, so they are only started once they're needed. Also services are now all exposed on the same port without an intermediary proxy.

**Comment by fsproru** [comment]
Hi @silv-io, thanks for the followup. @bwship should be able to take it from here.
