### ISSUE TITLE
LocalStack on The Changelog podcast?

### ISSUE THREAD

**Issue by jerodsanto** [localstack/localstack#1770]
Howdy from [The Changelog](https://changelog.com/podcast)!

_(Never heard of The Changelog? We've been interviewing the hackers, leaders, and innovators of open source and software development since '09.)_

We'd love to have you on the show sometime soon. Who would be best person to join us to talk about LocalStack and all the cool stuff y'all are up to?

Please email editors@changelog.com to coordinate. 

Looking forward to it! 💚

**Comment by whummer** [comment]
Hi @jerodsanto - thanks for reaching out. Sounds like a great idea - we'll get in touch with you directly. 👍 Thanks
