### ISSUE TITLE
How can I set localstack not to check SSL certificates? 

### ISSUE THREAD

**Issue by khitsik** [localstack/localstack#1779]
I`m trying to set up aws-kcl with localstack and every time getting the issue that my SSL certificates are incorrect.

I see the solution in your README for AWS Java client, but what about node js?
Need your help

**Comment by dparrella** [comment]
Does this work? https://stackoverflow.com/questions/10888610/ignore-invalid-self-signed-ssl-certificate-in-node-js-with-https-request

**Comment by whummer** [comment]
Thanks for reporting @khitsik , and thanks for the pointer @dparrella . Usually you should get it working with a combination of this:
```
process.env["NODE_TLS_REJECT_UNAUTHORIZED"] = 0;
```
... and this config:
```
const AWS = require('aws-sdk')
var https = require('https');
AWS.config.update({ httpOptions: { agent: new https.Agent({ rejectUnauthorized: false }) } });
...
```
Closing this issue - please report here if the problem persists. Thanks
