### ISSUE TITLE
Add support for Node.js version 12 with lambdas

### ISSUE THREAD

**Issue by a88zach** [localstack/localstack#1789]
https://aws.amazon.com/about-aws/whats-new/2019/11/aws-lambda-supports-node-js-12/

AWS recently started supporting Node.js version 12.  This should also be supported by localstack

**Comment by whummer** [comment]
Thanks for reporting @a88zach . We're currently using the Docker images from `lambci` - can you please also open an upstream issue here: https://github.com/lambci/docker-lambda Thanks

**Comment by a88zach** [comment]
@whummer, looks like they have already added support for Node.js version 12.

https://github.com/lambci/docker-lambda#docker-tags

**Comment by tprimini-daitan** [comment]
The node 12 image is in lambci (https://github.com/lambci/docker-lambda/tree/master/nodejs12.x/build), but I believe localstack has not support to node 12 yet.

**Comment by wapmesquita** [comment]
Is it just adding the variable here -> https://github.com/localstack/localstack/blob/a64e1f4e3324fc0b65d7251523fdcd7ba169178c/localstack/services/awslambda/lambda_executors.py#L32 ???

I tried to find other references to `nodejs10.x` or `LAMBDA_RUNTIME_NODEJS10X`, for example, and couldn't found.

**Comment by jacsamell** [comment]
Looks like the prefix does need removing for the node12 images to work.
The prefix is added with this comment:

**Comment by tprimini-daitan** [comment]
@jacsamell you can use the image `localstack/localstack:0.10.5`. This is working without the prefix.

**Comment by wapmesquita** [comment]
`https://github.com/localstack/localstack/issues/1777`works with lambdas in Nodejs12.x. Although, this version has the issue https://github.com/localstack/localstack/issues/1777 what was fixed in the latest version that does not work with Nodejs12.x. :cry:

**Comment by cdcrazy2292** [comment]
Not sure how you guys are running it but I was able to specify the node version in my script that creates my Lambda and it worked. 

`
awslocal lambda create-function \
    --function-name ${NAME} \
    --zip-file "fileb://${FILE_SOURCE}/../dist/${LAMBDA_NAME}.zip" \
    --handler index.handler \

    --runtime nodejs12.x \

    --memory-size 128 \
    --role arn:aws:iam::123456:role/noPermissions \
    --region ${REGION} \
    --environment Variables="{}"
`
Where I specify the runtime as node12.x
Since localstack runs lambci/lambda:{version}
I just added node12.x which is a version that lambci has in docker hub. 

https://hub.docker.com/r/lambci/lambda

**Comment by unsign3d** [comment]
I can try to take care of this if you want

**Comment by whummer** [comment]
Yes, please go ahead @unsign3d - that would be highly appreciated. Thanks!

**Comment by wapmesquita** [comment]
I think the issue https://github.com/localstack/localstack/issues/1782 is also related to this one

**Comment by whummer** [comment]
Thanks all . This should be fixed in #1855 - please report here if the problem persists. Thanks
