### ISSUE TITLE
Update moto-ext to latest moto to fix IAM roles continuously redeploying on terraform

### ISSUE THREAD

**Issue by ballwood** [localstack/localstack#1799]
@whummer Just did a PR to fix IAM mock which was causing continual redeploys using terraform. Could the moto-ext lib be updated when it is merged or I can do a PR to the moto-ext repository.

https://github.com/spulec/moto/pull/2597

**Comment by whummer** [comment]
Thanks for providing the fix in moto @ballwood ! The version of moto-ext has been updated in the meantime, and your change is included in the latest version of LocalStack. Thanks
