### ISSUE TITLE
SNS: Triggering confirm-subscription via the CLI doesn't publish the message

### ISSUE THREAD

**Issue by yamafaktory** [localstack/localstack#1804]
Hi & thanks for this awesome project!

I'm using the latest docker image and now getting an issue with the `confirm-subscription` step when running it via the CLI.

Some recent changes have been merged in the project and now the confirmation step is required for SNS - which is a good thing!

However, when manually triggering the CLI to confirm the subscription, everything looks good in stdin except that nothing much happens. Here is a subset of my shell script:

```sh
# There are other steps before: creating topic, subscribe, define filter policy, all that works!
aws sns publish \
    --endpoint-url "$SNS_ENDPOINT_URL" \
    --topic-arn "$TOPIC_ARN" \
    --message "$MESSAGE_BODY" \
    --message-attributes "$MESSAGE_ATTRIBUTES"

# Here I basically ask the user to pick the tocken which is clearly visible in some lambda handler
read -p "Enter the SubscribeURL's token: "  TOKEN

# The step below works fine as you get back the SubscriptionArn
aws sns confirm-subscription \
    --endpoint-url "$SNS_ENDPOINT_URL" \
    --topic-arn "$TOPIC_ARN" \
    --token "$TOKEN"
```

As mentioned above, everything seems to work as I finally get the `SubscriptionArn` back:

```sh
{
    "SubscriptionArn": "arn:aws:sns:us-east-1:000000000000:test:68762e72-e9b1-410a-8b3b-903da69ee1d5"
}
```

However, the message should be published right after the confirmation step, which is not the case. Just to mention: nothing to do with Docker or whatsoever since everything communicates cleary.

Thanks!

N.B.: The same shell script without the confirm-subscription step and an older docker image was working.

**Comment by whummer** [comment]
Thanks for reporting @yamafaktory . If I understand correctly, what you're saying is: if messages have been sent to an SNS topic **before** a subscription has been confirmed, then these messages should be delivered to the subscription **after** it has been confirmed, right?

Are you sure that this reflects the behavior in real AWS? I just did a quick test, and it seems that AWS only delivers any messages to a subscription that are sent to the topic **after** the subscription has been confirmed.

Based on this simple test in real AWS, I'd close this issue as invalid - "works as expected". But please report here with more details if you have more evidence that the behavior in LocalStack is incorrect or inconsistent with AWS. Thanks!

**Comment by yamafaktory** [comment]
@whummer Hi & thanks for the update! As far as I remember my issue was that, even after the subscription was confirmed, upcoming messages were not catched... but maybe this has been solved already in the latest master? Anyway, thanks again and if I can reproduce it again, I'll report it back 👍.
