### ISSUE TITLE
How can I remove the 443 port when localstack start?

### ISSUE THREAD

**Issue by anakin** [localstack/localstack#1816]
Hello everyone,

I want to use port 443 for my web service, but localstack will take this port when it start, how can I disable this option? Thank you !!

**Comment by whummer** [comment]
Thanks for reporting @anakin - can you please add `edge:<port>` to your `SERVICES` configuration - e.g., `SERVICES=edge:54321` to run on port 54321. Hope that helps - please report here if the problem persists. Thanks
