### ISSUE TITLE
AWS Go v2 SDK Fails with RDS Endpoint

### ISSUE THREAD

**Issue by saidmasoud** [localstack/localstack#1819]
**Localstack version**: 0.10.5

Using Pro version of Localstack, I am trying to use the Localstack RDS endpoint to test my Go application, which uses [the AWS Go v2 SDK](https://github.com/aws/aws-sdk-go-v2). After creating an instance locally using the CLI, my Go code fails when I try to call the DescribeDBInstancesRequest function. The CLI version of the request works as expected. Can we expect the Go v2 SDK to be supported?

Code sample:

```go

func GetRdsResponse(dbInstanceName string) rds.DescribeDBInstancesResponse {
	cfg := getAwsConfig()
	svc := rds.New(cfg)
	var (
		input *rds.DescribeDBInstancesInput
	)

	if dbInstanceName != "" {
		input = &rds.DescribeDBInstancesInput{
			DBInstanceIdentifier: aws.String(dbInstanceName),
		}
	}

	req := svc.DescribeDBInstancesRequest(input)

	resp, err := req.Send(context.Background())
	if err != nil {
		panic("Unable to describe DB instances"  + err.Error()))
	}
	return *resp
}
```

Output:

```sh
panic: Unable to describe DB instances, SerializationError: failed to decode query XML error response
caused by: expected element type <ErrorResponse> but have <title>

goroutine 1 [running]:
log.Panic(0xc000468740, 0x1, 0x1)
	/usr/local/Cellar/go/1.13.4/libexec/src/log/log.go:338 +0xac
```

**Comment by whummer** [comment]
Thanks for reporting @saidmasoud . This should be fixed in the latest version - can you please give it another try after doing a `docker pull localstack/localstack`. Thanks

**Comment by whummer** [comment]
Going to close this issue as fixed. Please report here if the problem persists. Thanks!
