### ISSUE TITLE
S3 Terraform issue

### ISSUE THREAD

**Issue by romafederico** [localstack/localstack#1824]
Hi there.

I'm having an issue when using terraform to deploy resources into a running instance of localtack.
This happens when I start localstack from a `docker-compose` file using the `localstack/localstack:latest` image and also running `localstack start`. I'm using Terraform 0.12 and the following `.tf` file:

```
variable "prefix" {}
variable "region" {}

terraform {
  required_version = ">= 0.12"
  backend "local" {
  }
}

provider "aws" {
  region                        = var.region
  skip_credentials_validation   = true
  skip_metadata_api_check       = true
  skip_region_validation        = true
  s3_force_path_style           = true

  endpoints {
    s3 = "http://localhost:4572"
  }
}

resource "aws_s3_bucket" "test-bucket" {
  acl    = "public-read"
  bucket = "${var.prefix}-${terraform.workspace}-sample-bucket"
  force_destroy = true
}
```

Executing `tf init`, `tf plan` and `tf apply` passing the necessary variables creates the bucket with no problem. The second time I run `tf apply` with no changes to our `.tf` file, terraform tells me that it needs to refresh state to the following:

```
Terraform will perform the following actions:

  # aws_s3_bucket.test-bucket will be updated in-place
  ~ resource "aws_s3_bucket" "test-bucket" {
        acl                         = "public-read"
        arn                         = "arn:aws:s3:::anz-pos-default-sample-bucket"
        bucket                      = "anz-pos-default-sample-bucket"
        bucket_domain_name          = "anz-pos-default-sample-bucket.s3.amazonaws.com"
        bucket_regional_domain_name = "anz-pos-default-sample-bucket.s3.ap-southeast-2.amazonaws.com"
        force_destroy               = true
        hosted_zone_id              = "Z1WCIGYICN2BYD"
        id                          = "anz-pos-default-sample-bucket"
        region                      = "ap-southeast-2"
        tags                        = {}

      - object_lock_configuration {
        }

      - replication_configuration {
        }

      - server_side_encryption_configuration {
        }

        versioning {
            enabled    = false
            mfa_delete = false
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

Why do `object_lock_configuration`, `replication_configuration` and `server_side_encryption_configuration` need to be removed?

I'm posting this issue here, since I can't replicate the error when using an actual AWS account as a remote AWS provider, so I'm assuming this may be something I'm doing wrong with Localstack.

**Comment by whummer** [comment]
Thanks for reporting @romafederico . I was able to reproduce this behavior. This should be fixed in #1845 , subsequent Terraform `apply` runs now do not trigger changes anymore for this particular configuration. Closing this issue - please re-open if the problem persists. Thanks

**Comment by romafederico** [comment]
Is this going to be included in the next release or is there a way I can test it now?

**Comment by whummer** [comment]
@romafederico You can simply get the latest image via `docker pull localstack/localstack` and restart LocalStack to test this change. Thanks
