### ISSUE TITLE
Error on deleting object from s3 bucket

### ISSUE THREAD

**Issue by Chanonry** [localstack/localstack#1832]
Creating buckets and saving files to the bucket works. 
Deleting the object/s fails. 
The code works error free on aws s3.

Illustrating the problem:

```
// Only for bug reporting
func simpleDelete(endpoint string) (*s3.DeleteObjectResponse, error){

	defaultResolver := endpoints.NewDefaultResolver()
	myCustomResolver := func(service, region string) (aws.Endpoint, error) {
		if service == s3.EndpointsID {
			return aws.Endpoint{
				URL:           endpoint,
				SigningRegion: "",
			}, nil
		}
		return defaultResolver.ResolveEndpoint(service, "")
	}

	cfg := defaults.Config()
	//cfg.Region = endpoints.UsWest2RegionID
	cfg.Region = "local"
	cfg.EndpointResolver = aws.EndpointResolverFunc(myCustomResolver)
	fmt.Printf("cfg: %+v",cfg)
	svc := s3.New(cfg)
	svc.ForcePathStyle = true

	input := &s3.DeleteObjectInput{
		Bucket: aws.String("test-bucket"),
		Key:    aws.String("noRecords1.csv"),
	}

	req := svc.DeleteObjectRequest(input)
	result, err := req.Send(context.Background())
	if err != nil {
		if aerr, ok := err.(awserr.Error); ok {
			fmt.Println("aerr.Code():", aerr.Code())
			fmt.Println("aerr.Error():",aerr.Error())
		} else {
			fmt.Println("err:", err.Error())
		}
		return result, err
	}
	return result, nil
}
```

The test:

```
func Test_simpleDelete(t *testing.T) {

	tests := []struct {
		name    	string
		endpoint    string
		want    	*s3.DeleteObjectResponse
		wantErr 	bool
	}{
		{"illustrate failure", "http://localhost:4572", &s3.DeleteObjectResponse{},false},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, err := simpleDelete(tt.endpoint)
			if (err != nil) != tt.wantErr {
				t.Errorf("simpleDelete() error = %v, wantErr %v", err, tt.wantErr)
				return
			}
			if !reflect.DeepEqual(got, tt.want) {
				t.Errorf("simpleDelete() = %v, want %v", got, tt.want)
			}
		})
	}
}
```

Output :

=== RUN   Test_simpleDelete
--- FAIL: Test_simpleDelete (0.04s)
=== RUN   Test_simpleDelete/illustrate_failure
cfg: {Region:local Credentials:{Value:{AccessKeyID: SecretAccessKey: SessionToken: Source:AnonymousCredentials CanExpire:false Expires:0001-01-01 00:00:00 +0000 UTC}} EndpointResolver:0x1610ed0 HTTPClient:0xc000116da0 Handlers:{Validate:{list:[{Name:core.ValidateEndpointHandler Fn:0x1497b40} {Name:core.ValidateParametersHandler Fn:0x1497c60}] AfterEachFn:0x13fb170} Build:{list:[{Name:core.SDKVersionUserAgentHandler Fn:0x14046a0} {Name:core.AddHostExecEnvUserAgentHander Fn:0x1497d40}] AfterEachFn:0x13fb170} Sign:{list:[{Name:core.BuildContentLengthHandler Fn:0x1496780}] AfterEachFn:<nil>} Send:{list:[{Name:core.ValidateReqSigHandler Fn:0x1497160} {Name:core.SendHandler Fn:0x1497330}] AfterEachFn:<nil>} ValidateResponse:{list:[{Name:core.ValidateResponseHandler Fn:0x1497590}] AfterEachFn:<nil>} Unmarshal:{list:[] AfterEachFn:<nil>} UnmarshalMeta:{list:[] AfterEachFn:<nil>} UnmarshalError:{list:[] AfterEachFn:<nil>} Retry:{list:[] AfterEachFn:<nil>} AfterRetry:{list:[{Name:core.AfterRetryHandler Fn:0x1497700}] AfterEachFn:<nil>} CompleteAttempt:{list:[] AfterEachFn:<nil>} Complete:{list:[] AfterEachFn:<nil>}} Retryer:<nil> LogLevel:0 Logger:0xc000114070 DisableRestProtocolURICleaning:false DisableEndpointHostPrefix:false}

aerr.Code(): Forbidden
aerr.Error(): Forbidden: Forbidden
	status code: 403, request id: , host id: 
    --- FAIL: Test_simpleDelete/illustrate_failure (0.04s)
        saver_test.go:236: simpleDelete() error = Forbidden: Forbidden
            	status code: 403, request id: , host id: , wantErr false
FAIL

Process finished with exit code 1

**Comment by whummer** [comment]
Thanks for reporting @Chanonry .

I made slight modifications (see below), and the following worked for me:
```
$ awslocal s3 mb s3://test-bucket; echo '' > /tmp/foobar; awslocal s3 cp /tmp/foobar s3://test-bucket/noRecords1.csv
$ AWS_ACCESS_KEY_ID=foo AWS_SECRET_ACCESS_KEY=foo go test
PASS
ok  	...	0.031s
```

The complete source of file `sample_test.go` is as follows:
```
package sample

import (
	"fmt"
	"context"
	"testing"
	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/service/s3"
	"github.com/aws/aws-sdk-go-v2/aws/endpoints"
	"github.com/aws/aws-sdk-go-v2/aws/awserr"
	"github.com/aws/aws-sdk-go-v2/aws/external"
)

func simpleDelete(endpoint string) (*s3.DeleteObjectResponse, error){

        defaultResolver := endpoints.NewDefaultResolver()
        myCustomResolver := func(service, region string) (aws.Endpoint, error) {
                if service == s3.EndpointsID {
                        return aws.Endpoint{
                                URL:           endpoint,
                                SigningRegion: "",
                        }, nil
                }
                return defaultResolver.ResolveEndpoint(service, "")
        }

				cfg, _ := external.LoadDefaultAWSConfig()
        cfg.Region = "local"
				cfg.EndpointResolver = aws.EndpointResolverFunc(myCustomResolver)
      	svc := s3.New(cfg)
        svc.ForcePathStyle = true

        input := &s3.DeleteObjectInput{
                Bucket: aws.String("test-bucket"),
                Key:    aws.String("noRecords1.csv"),
        }
        req := svc.DeleteObjectRequest(input)
        result, err := req.Send(context.Background())
        if err != nil {
                if aerr, ok := err.(awserr.Error); ok {
                        fmt.Println("aerr.Code():", aerr.Code())
                        fmt.Println("aerr.Error():",aerr.Error())
                } else {
                        fmt.Println("err:", err.Error())
                }
                return result, err
        }
        return result, nil
}


func Test_simpleDelete(t *testing.T) {

	tests := []struct {
		name    	string
		endpoint    string
		want    	*s3.DeleteObjectResponse
		wantErr 	bool
	}{
		{"illustrate failure", "http://localhost:4572", &s3.DeleteObjectResponse{},false},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			_, err := simpleDelete(tt.endpoint)
			if (err != nil) != tt.wantErr {
				t.Errorf("simpleDelete() error = %v, wantErr %v", err, tt.wantErr)
				return
			}
		})
	}
}
```

Closing this issue - please re-open or comment here if there are any other problems. Thanks

**Comment by Chanonry** [comment]
Thanks for that.

Interestingly the test does not work for me.  I get :

=== RUN   Test_simpleDelete/illustrate_failure
aerr.Code(): NoSuchBucket
aerr.Error(): NoSuchBucket: The specified bucket does not exist
	status code: 404, request id: , host id: 
    --- FAIL: Test_simpleDelete/illustrate_failure (0.02s)
        saver_test.go:266: simpleDelete() error = NoSuchBucket: The specified bucket does not exist
            	status code: 404, request id: , host id: , wantErr false
FAIL

The only obvious difference is I am running in Docker. This is the relevant docker-compose block -

version: '3.2'
services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack_demo
    ports:
      - '4563-4599:4563-4599'
      - '8055:8080'
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/AWSServices/data
    volumes:
      - './.AWSServices:/tmp/AWSServices'
      - '/var/run/docker.sock:/var/run/docker.sock'

Anything obvious ?

**Comment by Chanonry** [comment]
OK, just for completeness.

When I run this standalone in a separate package with either localstack or localstack in Docker the test passes.

But not within the current packaging structure for some reason. In that case the both the object and bucket are deleted despite an error being returned which says the function failed as there is no bucket.
