### ISSUE TITLE
DynamoDB GlobalTables not supported?

### ISSUE THREAD

**Issue by pikach00** [localstack/localstack#1834]
Trying to create DynamoDB global table and getting error:
'An error occurred (UnknownOperationException) when calling the CreateGlobalTable operation: An unknown operation was requested.'

Also tried to run list-global-tables, getting error:
'An error occurred (UnknownOperationException) when calling the ListGlobalTables operation: An unknown operation was requested.'

So global tables are not supported? if not - is there a plan to support it? Thank you!

**Comment by rmsmani** [comment]
@whummer 
Inputs required to start working on this.

**Comment by whummer** [comment]
Thanks for reporting @pikach00 @rmsmani . Initial support for Global Tables has been added in #2635 - can you please give it a try with the `latest` version of the Docker image? Please report here with any feedback or if there are any issues with this initial implementation. Thanks

**Comment by pikach00** [comment]
Just checked. Works as expected
Thanks @whummer !
