### ISSUE TITLE
LocalstackDockerTestRunner class was removed. Needs documentation update.

### ISSUE THREAD

**Issue by edwinwilson** [localstack/localstack#1862]
According to current README : 

> Additionally, there is a version of the LocalStack Test Runner which runs in a docker container instead of installing LocalStack on the current machine. The only dependency is to have docker installed locally. The test runner will automatically pull the image and start the container for the duration of the test. The container can be configured by using the @LocalstackDockerProperties annotation.
@RunWith(LocalstackDockerTestRunner.class)
@LocalstackDockerProperties(services = { "sqs", "kinesis:77077" })
public class MyDockerCloudAppTest {
  @Test
  public void testKinesis() {
    AmazonKinesis kinesis = DockerTestUtils.getClientKinesis();

However **LocalstackDockerTestRunner.class** appears to be unavailable.
The documentation should be updated to reflect the change and explain support for JUnit4.

Thank you.

**Comment by edwinwilson** [comment]
Also it seems like this configuration requires to have pip installed locally.

**Comment by whummer** [comment]
Thanks for reporting @edwinwilson , good catch. Would you mind creating a small pull request to update the documentation? Thanks!

**Comment by edwinwilson** [comment]
@whummer done here : https://github.com/localstack/localstack/pull/1890
Thanks for the reply.
I'm assuming there is no docker support for the @RunWith annotation.

**Comment by whummer** [comment]
>  I'm assuming there is no docker support for the @RunWith annotation.

@edwinwilson It's actually the opposite - Docker is now the default configuration when running via `LocalstackTestRunner`. Thanks for the README update 👍 .
