### ISSUE TITLE
SNS lambda subscription not triggered when using TargetArn instead of TopicArn on publish

### ISSUE THREAD

**Issue by spinlud** [localstack/localstack#1876]
I am using `localstack` with `serverless-localstack` plugin to locally test lambda subscribed to an SNS topic.
I've noticed that when publishing the SNS event (using aws-sdk for javascript) the lambda is not triggered if you use `TargetArn` property to pass the topic ARN. Using the `TopicArn` property instead will trigger the lambda correctly.
On the real AWS lambda will be triggered regardless if you use `TargetArn` or `TopicArn` in the [publish method](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/SNS.html#publish-property).

This is the command I am using to launch `localstack`:

```
SERVICES="iam,s3,sns,lambda,serverless,cloudformation" LAMBDA_REMOTE_DOCKER=false LAMBDA_DOCKER_NETWORK=host LAMBDA_EXECUTOR=docker DEBUG=1 localstack start
```

This is the serverless configuration:

```
service: test-service

provider:
  name: aws
  runtime: nodejs10.x
  deploymentBucket:
    name: local-bucket
  environment:
    NODE_ENV: ${env:NODE_ENV}

plugins:
  - serverless-localstack

custom:
  localstack:
    debug: true
    host: http://localhost
    lambda:      
      mountCode: true

functions:
  rb-files-hub:
    handler: index.handler
    events:
        - sns: "arn:aws:sns:us-east-1:000000000000:test-topic"
```

`os`: MacOS 10.15
`Docker`: 2.1.0.5
`Python`: 3.7.4
`localstack`: 0.10.6

**Comment by whummer** [comment]
Thanks for reporting @spinlud . This should be fixed in #2270 - can you please give it a try with the `latest` version? Please report here if the problem persists. Thanks
