### ISSUE TITLE
Release a Maven Build

### ISSUE THREAD

**Issue by mattvv** [localstack/localstack#188]
Hey guys!

1.0-SNAPSHOT feels bad as a release, any chance of releasing a proper versioned maven build?

**Comment by whummer** [comment]
The Maven has now been published to Maven Central, initial version number is `0.1.1`:

https://repo.maven.apache.org/maven2/cloud/localstack/localstack-utils/0.1.1/localstack-utils-0.1.1.pom

The Maven instructions in the `README` have been updated as well. (PR https://github.com/localstack/localstack/pull/193)
