### ISSUE TITLE
The AWS Lambda `Invoke` API incorrectly encodes numbers, booleans.

### ISSUE THREAD

**Issue by shawnrusaw-wf** [localstack/localstack#1883]
The value of `lambda_api.JSON_START_CHARS` (https://github.com/localstack/localstack/blob/master/localstack/services/awslambda/lambda_api.py#L81-L83)  is not complete. `{` and `[` are a start, but `t` (true), `f` (false), `n` (null) and all the numbers `0-9` are also valid. 

This has the effect of converting numbers to strings of the number etc.

PR with proposed solution incoming.

**Comment by whummer** [comment]
Should be fixed in #1885 - thanks again!
