### ISSUE TITLE
changeMessageVisibility function doesn't work

### ISSUE THREAD

**Issue by RWeins** [localstack/localstack#1902]
Hi,

I'm using the changeMessageVisibility function in order to return a message to the queue, by calling
`serviceName.changeMessageVisibility(recipientId, 0);`

but it doesn't work, the message doesn't reappear in the queue.

**Comment by whummer** [comment]
Thanks for reporting @RWeins . 

We've added an integration test that uses `change_message_visibility` and asserts that a message can be received multiple times afterwards:
https://github.com/localstack/localstack/blob/master/tests/integration/test_sqs.py#L67-L77

Can you please provide a small, self-contained example that helps reproduce the specific issue you're facing? Thanks

**Comment by whummer** [comment]
@RWeins any updates on this? Have you been able to reproduce this issue? Please provide a small, self-contained example that exposes the behavior, then we'll be happy to look into it. Thanks!
