### ISSUE TITLE
Lambda should persist function.

### ISSUE THREAD

**Issue by abhimanyuNitSri** [localstack/localstack#1904]
When we use localstack to create kubernetes pod, containers in pod and pod itself restart multiple times. When a function is created in the lambda service and the pod/containers restart the function is not preset in the new container. there should be a way to persist the function and state of lambda service. We could use Persistent volume to store config which will maintaine the state the new container created.

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-144) by [Unito](https://www.unito.io/learn-more)

**Comment by GiladPeled** [comment]
any update regarding this one ?
