### ISSUE TITLE
Unable to get IAM security credentials from EC2 Instance Metadata Service.

### ISSUE THREAD

**Issue by grace-walker-cko** [localstack/localstack#1918]
I'm currently creating AWS resources via sessions in boto3 via localstack. My lambda is not able to connect to DynamoDb. I wasn't aware that roles needed to be set up in localstack, but I'm getting the error:

> Amazon.Runtime.AmazonServiceException: Unable to get IAM security credentials from EC2 Instance Metadata Service.
localstack                 |    at Amazon.Runtime.DefaultInstanceProfileAWSCredentials.FetchCredentials()
localstack                 |    at Amazon.Runtime.DefaultInstanceProfileAWSCredentials.GetCredentials()
localstack                 |    at Amazon.Runtime.DefaultInstanceProfileAWSCredentials.GetCredentialsAsync()
localstack                 |    at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext)

I had a little look in the aws-sdk and found this happens when 
EC2InstanceMetadata.IAMSecurityCredentials are null. This looks oddly familiar to a paragraph in the boto3 docs: 

> If you are running on Amazon EC2 and no credentials have been found by any of the providers above, boto3 will try to load credentials from the instance metadata service. In order to take advantage of this feature, you must have specified an IAM role to use when you launched your EC2 instance.

Which leads me to my question, is the lambda running as an EC2 instance in localstack and does this mean i will need to define a role for the function? I would have assumed that the environment variables would have been used in the AWS SDK which I am setting in the docker compose:

    environment:
      - SERVICES=s3,sqs,dynamodb,lambda,cloudwatch,logs,iam,ec2
      - HOSTNAME=localstack
      - LAMBDA_EXECUTOR=docker
      - AWS_DEFAULT_REGION=eu-west-2
      - AWS_ACCESS_KEY_ID=xxx
      - AWS_SECRET_ACCESS_KEY=xxx

**Comment by whummer** [comment]
Hi @grace-walker-cko . Looks like the client you're using in your function is trying to access real AWS, not the local APIs. You need to configure the endpoint URL of the SDK and point it to `http://${LOCALSTACK_HOSTNAME}:4569` (for DynamoDB). The environment variable `LOCALSTACK_HOSTNAME` is automatically configured when your Lambda spins up, and it points to the host address where LocalStack is available.

In general, LocalStack usually does not ask you for IAM security credentials, IAM roles, or the like. If you're getting an error related to IAM or security permissions, it is quite likely that your client is not correctly configured and talks to real AWS instead of LocalStack.

If you're using Java, you could also try using the `TestUtils` class from the LocalStack Maven package. Please refer to the examples in our integration tests, e.g., here: https://github.com/localstack/localstack/blob/master/localstack/ext/java/src/test/java/cloud/localstack/sample/SQSLambdaHandler.java#L23

Hope that helps - please report here if the problem persists or if there are any other issues. Thanks

**Comment by grace-walker-cko** [comment]
Thanks for the response, using this hostname variable (which resolves to an IP) I actually got a little further... 
> Request must contain either a valid (registered) AWS access key ID or X.509 certificate.
 
This error occurs with the following code:

            var config = new AmazonDynamoDBConfig { RegionEndpoint = RegionEndpoint.EUWest2, ServiceURL = $@"http://{Environment.GetEnvironmentVariable("LOCALSTACK_HOSTNAME")}:4569" };
            var credentials = new BasicAWSCredentials(Environment.GetEnvironmentVariable("AWS_ACCESS_KEY_ID"), Environment.GetEnvironmentVariable("AWS_SECRET_ACCESS_KEY"));
            _dynamoDbClient = new AmazonDynamoDBClient(credentials, config);

And the below code actually works:

            var config = new AmazonDynamoDBConfig { RegionEndpoint = RegionEndpoint.EUWest2, ServiceURL = $@"http://{Environment.GetEnvironmentVariable("LOCALSTACK_HOSTNAME")}:4569" };
            var credentials = new BasicAWSCredentials("xxx","xxx");
            _dynamoDbClient = new AmazonDynamoDBClient(credentials, config);

The only difference being that the environment variables are not being used in the working example. When I output the values of the variables they are indeed empty, however they _do_ appear as environment variables on the container itself.

I believe this is probably some issue in the AWS SDK and probably not localstack related. Thanks for the headsup with the hostname

**Comment by whummer** [comment]
@grace-walker-cko Great, glad you got it working. 👍 True - that's a limitation of the AWS SDK, we need to specify some (dummy) credentials to get it working. Thanks

**Comment by grace-walker-cko** [comment]
@whummer Sorry to bring this up again, I have done a basic test and it looks like my lambda in localstack is not able to access environment variables.

With the basic config as: 

>   localstack:
    image: localstack/localstack
    container_name: localstack
    environment:
      - SERVICES=dynamodb,dynamodbstreams,lambda,awslogs,sqs
      - LAMBDA_EXECUTOR=docker
      - HOSTNAME=localhost
      - HOSTNAME_EXTERNAL=localhost
      - AWS_DEFAULT_REGION=eu-west-2
      - AWS_ACCESS_KEY_ID=xxx
      - AWS_SECRET_ACCESS_KEY=xxx
      - TEST_VALUE=Grace
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "4569:4569"
      - "4572:4572"
      - "4576:4576"
      - "8080:8080"

And a .net lambda with SQS event source setup using Boto3 inside localstack, the environment variables are not available when using code 'Environment.GetEnvironmentVariable("TEST_VALUE")' in the .net app. The container variables exist, is there something missing to bridge the lambda to the container?

**Comment by whummer** [comment]
Hi @grace-walker-cko . Please note that the environment variables of the LocalStack container are different from the Lambda environment variables.

Please check out the API specs - you can pass environment variables when creating the Lambda function. Thanks

**Comment by kid-scarlet** [comment]
Sorry for digging up this old issue, but for anyone trying to get this to work, I found the solution here: https://qiita.com/YSFT_KOBE/items/d05349455e6943e3b97b

To summarize: Specify ANY credentials and then LocalStack will let you through and stop throwing this error.
