### ISSUE TITLE
Elasticsearch installed with version 6 instead of 7.1

### ISSUE THREAD

**Issue by shmuelamar** [localstack/localstack#1927]
Hey, great project!

aws now supports elastic 7.1 - from [here](https://aws.amazon.com/elasticsearch-service/faqs/):

> Q: Which Elasticsearch version does Amazon Elasticsearch Service support?
> 
> Amazon Elasticsearch Service currently supports Elasticsearch versions 7.1, 6.8, 6.7, 6.5, 6.4, 6.3, 6.2, 6.0, 5.6, 5.5, 5.3, 5.1, 2.3, and 1.5.
> 

I'm willing to submit a patch, it also seems to work properly on my machine with 7.1. let me know if you are interested in this improvement / fix :smile:

**Comment by CowChris** [comment]
@shmuelamar please do share the patch :)

**Comment by ScheerMT** [comment]
Looks like #2086 could be the ticket

**Comment by whummer** [comment]
Thanks for reporting @shmuelamar @ScheerMT @CowChris . Closing this issue - please track the progress of support for different Elasticsearch versions here: #2242 Thanks
