### ISSUE TITLE
Bump kinesalite to 3.3.0

### ISSUE THREAD

**Issue by stefanmoro** [localstack/localstack#1930]
Hey all!

It seems Kinesalite supports CBOR from v3.3.0 (https://github.com/mhart/kinesalite/pull/74). It'd be much appreciated to get that into localstack.

Thanks
Stefan

**Comment by whummer** [comment]
Hi @stefanmoro , that's great news, thanks for the update. Do you think you could create a small pull request to bump the version here? Thanks!

**Comment by stefanmoro** [comment]
Hi @whummer, I tried bumping kinesalite in package.js to 3.3.0, build the docker and run it together with my tests without disabling CBOR, but it failed. 
I also tried removing the `env_vars['AWS_CBOR_DISABLE'] = 'true'` in kinesis_connector.py which caused the localstack tests to fail.

So I guess something else is needed here, not just bump to kinesalite 3.3.0.

**Comment by alins** [comment]
i wonder if your tests will pass using kinesalite directly without disabling CBOR. in other words: is this a kinesalite problem or a localstack problem?

**Comment by whummer** [comment]
Closing this issue as resolved - we are now using kinesalite version `3.3.1`, as per `package.json`. Thanks

**Comment by bishtawi** [comment]
I am running the latest version of Localstack (with kinesalite version 3.3.1 in the package.json file) and I still get errors when enabling CBOR. I am curious to know if anyone else is running into this problem?
