### ISSUE TITLE
Standardize usage with terraform

### ISSUE THREAD

**Issue by danielptm** [localstack/localstack#1932]
As a user of localstack I would like a documented standardized way to run terraform scripts against a running localstack to create AWS infrastructure so that I don't have to duplicate work that involves programatically creating the resources when I use terraform to create resources in my cloud environment.

**Comment by whummer** [comment]
Thanks for reporting @danielptm . Very much agree that the documentation around Terraform usage could be improved. We should try to keep the details in the main README short and crisp, though.

Basically, it boils down to configuring the endpoint URLs for each service in the `provider` section. Here is a simple demo project that highlights how this can be done: https://github.com/localstack/localstack-pro-samples/blob/master/terraform-resources/test.tf. Do you think you could create a small pull request to add a few simple instructions to the README? That would be really appreciated, thanks!

**Comment by danielptm** [comment]
Sure. Once I succeed at doing it I will make the PR. Thanks!

**Comment by paultyng** [comment]
FYI, we also have a page in the TF docs about this you may be able to link to: https://www.terraform.io/docs/providers/aws/guides/custom-service-endpoints.html#localstack

**Comment by whummer** [comment]
Thanks for the pointer @paultyng ! A new section has been added to the README in #1963
