### ISSUE TITLE
CloudWatch doesn't support aws 2.10.+

### ISSUE THREAD

**Issue by yaoyaocjj** [localstack/localstack#1944]
We use aws 2.10.+ version in our repo, when try to setup localstack for cloudwatch in local environment, I got an error said `"error":{"message":"null (Service: CloudWatch, Status Code: 500, Request ID: null)",`.
Then I check the localstack log, found there is an error in data format:
![image](https://user-images.githubusercontent.com/20292287/72229291-6916ad00-35e8-11ea-9800-95e4351d332a.png)

**ValueError: time data '2020-01-13T01:22:32Z' does not match format '%Y-%m-%dT%H:%M:%S.%fZ'`**

When call the `software.amazon.awssdk.services.cloudwatch.CloudWatchClient` to put metric, we just give the **Instant timestamp**. 
Seems like localstack can not transfer the Instant to correct format.

**Comment by SeanBE** [comment]
This PR https://github.com/spulec/moto/pull/2801 fixes it. 
Not sure when moto will release the next version (last one in November).

**Comment by whummer** [comment]
Thanks for reporting @yaoyaocjj @SeanBE - this fix should have been integrated into LocalStack in the meantime - can you please give it a try with the `latest` version of the Docker image? Please report here if the problem persists. Thanks!
