### ISSUE TITLE
Support for MediaStore

### ISSUE THREAD

**Issue by trackness** [localstack/localstack#1945]
Hello,

Is support for MediaStore on the current roadmap?

Cheers

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-146) by [Unito](https://www.unito.io/learn-more)

**Comment by thrau** [comment]
We have begun implementing MediaStore implementation in Pro (see [feature coverage](https://github.com/localstack/localstack/blob/master/doc/feature_coverage.md). Please let is know if you have specific feature requests.
