### ISSUE TITLE
Write a proper changelog

### ISSUE THREAD

**Issue by jrr** [localstack/localstack#1946]
The changes in the [0.10.6](https://github.com/localstack/localstack/releases/tag/v0.10.6) release appear to be a semicolon-separated list of commits. Could somebody with access to the post format them? (and, ideally, synthesize what's changed into a [written summary for humans](https://keepachangelog.com/))

**Comment by whummer** [comment]
Thanks for reporting @jrr , good point about the change log - it should be prepared/formatted more carefully. The change log for release 0.10.6 has been updated, we'll also take it into account for future releases. Thanks!

**Comment by jrr** [comment]
That helps a lot. Thanks!
