### ISSUE TITLE
s3 consumes significant memory due to large buffer size

### ISSUE THREAD

**Issue by markwaddle** [localstack/localstack#1950]
This line configures moto, which uses a tempfile.SpooledTemporaryFile for each S3 key, to buffer up to 2GB in memory per key. If you write a large number of keys less than 2GB in size they will all stay in RAM.

https://github.com/localstack/localstack/blob/master/localstack/services/s3/s3_starter.py#L57

I recommend either:
* removing this FakeKey.__init__ patch altogether, and falling back to moto's default buffer size of 16MB
* changing the DEFAULT_KEY_BUFFER_SIZE to an even smaller size, such as 1MB

It will reduce the performance of the localstack s3 for larger files, however it will perform consistently and is much less likely to consume excessive amounts of RAM.

**Comment by markwaddle** [comment]
it turns out i was wrong about the root cause of my memory issues. it was due to re-using the same DATA_DIR on the host, which resulted in the s3 file accumulating bytes across many sessions. i will close this out as i can not say this is an actual problem.

**Comment by whummer** [comment]
@markwaddle Thanks for looking into this issue, and thanks for the detailed root cause analysis! Perhaps it would be worth adding a short note in the Troubleshooting section of the README, though. Thanks!
