### ISSUE TITLE
S3 requests with Range header broken when using SSL

### ISSUE THREAD

**Issue by milas** [localstack/localstack#1952]
Including the `Range` header on S3 requests triggers a `502 Bad Gateway` when localstack is run with SSL.

Sample test that demonstrates the issue:
```python
import logging
import io
import os

import boto3

logging.basicConfig(level=logging.INFO)


def test_range_s3():
    s3 = boto3.client('s3', endpoint_url='https://localhost:4572', use_ssl=True, verify=False)

    bucket = 'localstack-s3-range'
    obj_name = 'sample.bin'
    s3.create_bucket(Bucket=bucket)

    chunk_size = 1024

    with io.BytesIO() as data:
        data.write(os.urandom(chunk_size * 2))
        logging.info('Uploading object (size=%d)', data.getbuffer().nbytes)
        data.seek(0)
        s3.upload_fileobj(data, bucket, obj_name)

    range_header = f'bytes=0-{chunk_size - 1}'
    logging.info('Downloading using Range header: %s', range_header)
    
    # this will raise an exception
    # botocore.exceptions.ClientError: An error occurred (502) when calling the GetObject operation (reached max retries: 4): Bad Gateway
    resp = s3.get_object(Bucket=bucket, Key=obj_name, Range=range_header)
    
    content = resp['Body'].read()
    assert len(content) == chunk_size
```

This is a fairly recent regression:

Running against `localstack/localstack:latest` will fail using SSL but pass without SSL. 
Running against `localstack/localstack:0.10.6` will pass using SSL as well as without SSL.

I am guessing changes from either #1887 or #1906 broke this since those were related to `Range` functionality, but have not bisected to be sure.

**Comment by whummer** [comment]
Thanks for reporting @milas . This should be fixed in #1981 - your test case has been added to the code base to avoid regressions in the future. Please report here if the problem persists. Thanks

**Comment by phihag** [comment]
I still see this image with the `localstack/localstack:latest` and `localstack/localstack:0.10.7` docker images. It works fine in `localstack/localstack:0.10.7`.

**Comment by whummer** [comment]
@phihag can you please provide some more details about your setup and the issue you're seeing. Are you experiencing the _exact_ same issue? Please post some logs, as well as some steps to reproduce this issue. Thanks
