### ISSUE TITLE
KMS endpoint - help with pagination

### ISSUE THREAD

**Issue by SinFulNard** [localstack/localstack#1953]
Hi, hopefully looking for some help using the kms endpoint. I am attempting to enumerate a large amount of keys using the "ListKeysPages" function of the Golang sdk: https://docs.aws.amazon.com/sdk-for-go/api/service/kms/#KMS.ListKeysPages

It seems the pagination calls don't work when using the localstack endpoint. I wrote a small go snippet to test this account a dev real AWS account and also against my localstack endpoint (which is seeded with 400 odd keys):

```
func main() {
	// Uncomment to test against AWS service
	/*kmsSvc := kms.New(session.New(&aws.Config{
		Region: aws.String("us-west-2"),
	}))*/

	// Uncomment to test against Localstack service
	kmsSvc := kms.New(session.New(&aws.Config{
		Region:   aws.String("us-east-1"),
		Endpoint: aws.String("http://localhost:4599"),
	}))

	var results []*kms.KeyListEntry
	err := kmsSvc.ListKeysPages(&kms.ListKeysInput{},
		func(page *kms.ListKeysOutput, lastPage bool) bool {
			results = append(results, page.Keys...)
			return !lastPage
		})

	if err != nil {
		fmt.Println("Got error listing keys: ", err)
	} else {
		log.Println("Results count: ", len(results))
	}
}
```

When pointing to AWS, I receive a response as expected, the total count of keys available. When I run against localstack, I only ever retrieve 100 items. If I add an additional `spew.Dump(page)` to interrogate the results, I can see the `Truncated: true` is returned as part of the object.

I'm not sure if I've missed something obvious, so reaching out for help.

**Comment by SinFulNard** [comment]
Ah, reading a bit more - I wonder if I should also raise this issue here: https://github.com/nsmithuk/local-kms
If i'm reading correct, that is how the KMS is run?

**Comment by mfulleratlassian** [comment]
It appears the underlying local-kms package supports pagination ok. I tested with Python but that should not matter. 

After generating 105 KMS keys on a freshly started local-kms docker container:

![Screen Shot 2020-01-15 at 1 26 04 pm](https://user-images.githubusercontent.com/3432067/72399593-c3f00600-379a-11ea-84bc-6cf976fdedf4.png)

You can see I get the NextMarker back and I can gather the next page.

**Comment by SinFulNard** [comment]
I interrogated what keys existed in my localstack KMS and was surprised to find a bunch of "empty" entries:
```
➜ awslocal kms list-keys
{
    "Keys": [
        {
            "KeyArn": "arn:aws:kms:us-east-1:000000000000:key/002f1a55-7ee1-4b28-92cc-2d60099b77de",
            "KeyId": "002f1a55-7ee1-4b28-92cc-2d60099b77de"
        },
        {
            "KeyArn": "",
            "KeyId": ""
        },
        {
            "KeyArn": "",
            "KeyId": ""
        },
        {
            "KeyArn": "",
            "KeyId": ""
        },
        {
            "KeyArn": "",
            "KeyId": ""
        },
<snip>
```
I purged everything and started fresh, populating 110 keys via the basic CLI command `awslocal kms create-key`. Confirmed the phantom entries were not present and executed my test snippet again. The correct result was returned. I will attempt to track down what part of my testing is generating these empty keys.

👻 🔑
