### ISSUE TITLE
SQS synchronously invoking lambda

### ISSUE THREAD

**Issue by ronaldotd** [localstack/localstack#1967]
I have created a lambda function that is triggered by SQS messages received on a given queue.

In order to test this pipeline, I manually send messages to the queue using `awslocal sqs send-message`.  I have noticed that `awslocal` only returns after the lambda function is executed, for instance, if the function takes five seconds to execute, `awslocal` is blocked for five seconds.
Is this the expected behavior? A message received by the queue synchronously triggers the lambda function?
I have browsed the code, especially the SQS listener, and it seems that this is by design.
By the way, thanks for this great project!

**Comment by ronaldotd** [comment]
It seems that this PR is adding the async behavior I was looking for: https://github.com/localstack/localstack/pull/1352

**Comment by whummer** [comment]
Fixed in #1973 - thanks again!
