### ISSUE TITLE
Enhance request forwarding for non-existent Lambdas

### ISSUE THREAD

**Issue by sjmatta** [localstack/localstack#1971]
As an enhancement to https://github.com/localstack/localstack/pull/1194

It would be really helpful to send the Lambda name, either as data, a header, or as part of the URL.

At code location: https://github.com/localstack/localstack/blob/03c6f4bf250edd18eb818ed65090f508636b0bff/localstack/services/awslambda/lambda_api.py#L696

I can likely open a PR to handle this given some feedback on the feature and potential design.

Right now all I see is the following (using `npx http-echo-server`):
```
[socket#8] event: data
--> POST / HTTP/1.1
--> Host: 192.168.1.x:3000
--> User-Agent: python-requests/2.22.0
--> Accept-Encoding: gzip, deflate
--> Accept: */*
--> Connection: keep-alive
--> Content-Length: 9
--> Content-Type: application/x-www-form-urlencoded
-->
-->
[socket#8] event: data
--> Name=test
```

**Comment by whummer** [comment]
Great idea @sjmatta - would you be able to create a small pull request with this functionality? Shouldn't be too hard to add - I'd be happy to provide guidance if needed. Thanks!

**Comment by whummer** [comment]
Thanks @sjmatta - this has been added in #2397 .
