### ISSUE TITLE
SNS RedrivePolicy

### ISSUE THREAD

**Issue by jgbmattos** [localstack/localstack#1972]
As far as I notice localstack does not have implemented RedrivePolicy for SNS yet, is that correct?
This is something on the project roadmap?
May I contribute to the project implementing that feature?

**Comment by whummer** [comment]
Hi @jgbmattos , that is correct - RedrivePolicy/DeadLetterConfig has been implemented for SQS and Lambda, but not yet for SNS. A pull request would be greatly appreciated!!

Here are some pointers that may help as a starting point:
* https://github.com/localstack/localstack/blob/master/localstack/utils/aws/dead_letter_queue.py
* https://github.com/localstack/localstack/blob/3f334986fa89df78ddff3950e3ef727c9e8d0a22/tests/integration/test_sqs.py#L128-L140

Please let us know how it goes - happy to provide some guidance if needed. Thanks

**Comment by jgbmattos** [comment]
Hi @whummer. 
Thanks for the tips, helped me a lot.
I thought of something like that: [Link to commit](https://github.com/jgbmattos/localstack/commit/7cd50ea2bcef5095cfddd43dc324ed480525dfa4?diff=unified)
Feel free to criticise the implementation. This is not the final commit, I want your opinion before work in some tests. 

I notice that in case of an error in one subscriber the message is not sent to others. AWS works the same way? If thats not the case, do you think it would be nice to implement that feature as well?

**Comment by jgbmattos** [comment]
I created a little bash to create topic and everything.
`#SNS parameters
SNS_NAME="sns_redrive_policy_test"
SQS_DLQ_NAME="sqs_dlq_redrive_policy_test"

#Create SNS topic to send cloudformation notifications to
SNS_ARN=`aws --endpoint-url=http://localhost:4575 sns create-topic --name ${SNS_NAME} | jq -r '.TopicArn'`

#Get envs
SQS_DLQ_URL=`aws --endpoint-url=http://localhost:4576 sqs create-queue --queue-name ${SQS_DLQ_NAME} | jq -r '.QueueUrl'`
SQS_DLQ_ARN=`aws --endpoint-url=http://localhost:4576 sqs get-queue-attributes --queue-url ${SQS_DLQ_URL} --attribute-names QueueArn | jq -r '.Attributes .QueueArn'`

#Subscribe the queue to the notifications
aws --endpoint-url=http://localhost:4575 sns subscribe --topic-arn ${SNS_ARN} --protocol http --notification-endpoint http://127.0.0.1:8001/

#Set redrive policy
SUBSCRIPTION_ARN=`aws --endpoint-url=http://localhost:4575 sns list-subscriptions | jq -r '.Subscriptions[0].SubscriptionArn'`
aws --endpoint-url=http://localhost:4575 sns set-subscription-attributes --subscription-arn ${SUBSCRIPTION_ARN} --attribute-name RedrivePolicy --attribute-value "{\"deadLetterTargetArn\":\"${SQS_DLQ_ARN}\"}"

#echo result
aws --endpoint-url=http://localhost:4575 sns get-subscription-attributes --subscription-arn ${SUBSCRIPTION_ARN}`

**Comment by whummer** [comment]
Hi @jgbmattos , apologies for the delay. Can you please use the Github "pull request" feature and create a pull request against this repository, which would allow us to easily compare and discuss your changes. Please let me know if you have any questions. Thanks

**Comment by whummer** [comment]
@jgbmattos Thanks again - this should be supported in the meantime. A new `sns_error_to_dead_letter_queue(..)` function has been added here: https://github.com/localstack/localstack/blob/master/localstack/utils/aws/dead_letter_queue.py#L21-L29 Please report here if the problem persists. Thanks
