### ISSUE TITLE
DynamoDB with stram. DynamoDB Stream: Requested resource not found 

### ISSUE THREAD

**Issue by investr777** [localstack/localstack#1977]
Hello, can you help me with my problem?
I have localstack with services: DYNAMODB and DYNAMODB_STREAMS. They are runing in a docker container. I create dynamoDbClent and DynamoDbStreamClient:

```
AmazonDynamoDBStreamsClientBuilder.standard()
            .withEndpointConfiguration(
                AwsClientBuilder.EndpointConfiguration(
                    "http://${localstack.containerIpAddress}:${localstack.getMappedPort(4570)}",
                   "us-west-2"
                )
            )
            .build()

AmazonDynamoDBClientBuilder.standard()
        .withEndpointConfiguration(
            AwsClientBuilder.EndpointConfiguration(
                "http://${localstack.containerIpAddress}:${localstack.getMappedPort(4569}",
                 "us-west-2"
            )
        )
        .build()
```

I create a table in dynamodb with streamSpecification. 
I get streamArn from my table: 
`streamArn = dynamoDbClient.describeTable("myTable").table.latestStreamArn`
**_arn:aws:dynamodb:us-east-1:000000000000:table/myTable/stream/2020-01-24T10:25:22.737_**

But when I want to create:

```
dynamoDbStreamClient.describeStream(
                DescribeStreamRequest()
                    .withStreamArn(streamArn)
                    .withExclusiveStartShardId(lastEvaluatedShardId)
            )
```

I get exception:  `com.amazonaws.services.dynamodbv2.model.ResourceNotFoundException: Requested resource not found (Service: AmazonDynamoDBStreams; Status Code: 400; Error Code: ResourceNotFoundException; Request ID: null)`

Where is my mistake?

**Comment by investr777** [comment]
If I run localstack in docker container like:

`docker run --name loc -p 4569:4569 -p 4570:4570 -d localstack/localstack`

and create clients like:

```
AmazonDynamoDBStreamsClientBuilder.standard()
            .withEndpointConfiguration(
                AwsClientBuilder.EndpointConfiguration(
                    "http://localhost:4570",
                   "us-west-2"
                )
            )
            .build()

AmazonDynamoDBClientBuilder.standard()
        .withEndpointConfiguration(
            AwsClientBuilder.EndpointConfiguration(
                "http://localhost:4569",
                 "us-west-2"
            )
        )
        .build()
```

Everything is work. Why?

And if container localstack runs with help LocalStackContainer(), it's gives exception: `com.amazonaws.services.dynamodbv2.model.ResourceNotFoundException: Requested resource not found (Service: AmazonDynamoDBStreams; Status Code: 400; Error Code: ResourceNotFoundException; Request ID: null)`

**Comment by whummer** [comment]
Thanks for reporting @investr777 . Looks like this issue could be caused by a region mismatch. Please note that the server-side region needs to match the region used by your client.

Can you try starting LocalStack with the environment variable `DEFAULT_REGION=us-west-2` and give it another try? Please note that the stream ARN should then look something like this:
```
arn:aws:dynamodb:us-west-2:000000000000:table/myTable/stream/2020-01-24T10:25:22.737
```
(note the different region)

**Comment by investr777** [comment]
> Thanks for reporting @investr777 . Looks like this issue could be caused by a region mismatch. Please note that LocalStack by default is single-region, and the server-side region needs to match the region used by your client.
> 
> Can you try starting LocalStack with the environment variable `DEFAULT_REGION=us-west-2` and give it another try? Please note that the stream ARN should then look something like this:
> 
> ```
> arn:aws:dynamodb:us-west-2:000000000000:table/myTable/stream/2020-01-24T10:25:22.737
> ```
> 
> (note the different region)
> 
> Please let us know if that helps. Thanks.

I try region for clients us-east-1. It isn't work too. And I run with environment variable AWS_REGION = us-west-2. It isn't work too

**Comment by investr777** [comment]
If I run with terminal: `docker run --name loc -p 4569:4569 -p 4570:4570 -d localstack/localstack`
I create client wirh region **us-west-2**, and I get ARN with region us-east-1, and it's work. 
But I use the same configuration clients, but localstack container runs with help testcontainer, I get exception. 
So, configuration is the same here and there, but with testcontainer I get an exception, and with terminal - works.

**Comment by investr777** [comment]
In the "latest" version everything works. Sorry.

**Comment by whummer** [comment]
Awesome, thanks for confirming it works 👍
