### ISSUE TITLE
Cannot debug Java lambdas with Java 11 runtime

### ISSUE THREAD

**Issue by rp-199** [localstack/localstack#1985]
The lambda execution is not suspending and the lambda container has no port exposed when running a java 11 lambda with the latest localstack docker image by docker-compose with the environment variable LAMBDA_JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=_debug_port_
    
It works fine for java8 runtime executions.

Docker command:

> localstack_1  | 2020-01-26T12:42:04:INFO:localstack.services.awslambda.lambda_executors: Running lambda cmd: CONTAINER_ID="$(docker create -i   -e ENV="$ENV" -e DOCKER_LAMBDA_USE_STDIN="$DOCKER_LAMBDA_USE_STDIN" -e HOSTNAME="$HOSTNAME" -e LOCALSTACK_HOSTNAME="$LOCALSTACK_HOSTNAME" -e AWS_LAMBDA_FUNCTION_TIMEOUT="$AWS_LAMBDA_FUNCTION_TIMEOUT" -e AWS_LAMBDA_FUNCTION_NAME="$AWS_LAMBDA_FUNCTION_NAME" -e AWS_LAMBDA_FUNCTION_VERSION="$AWS_LAMBDA_FUNCTION_VERSION" -e AWS_LAMBDA_FUNCTION_INVOKED_ARN="$AWS_LAMBDA_FUNCTION_INVOKED_ARN"  --rm "lambci/lambda:java11" "com.XXX.XXX.Handler")";docker cp "/tmp/localstack/zipfile.0c90736c/." "$CONTAINER_ID:/var/task"; docker start -ai "$CONTAINER_ID";

I think this is due to the fact that the classpath arguments and java opts are only being set if the rutime is equal to LAMBDA_RUNTIME_JAVA8 (line 211 of ocalstack/localstack/services/awslambda/lambda_executors.py , commit 03c6f4bf250edd18eb818ed65090f508636b0bff)

**Comment by whummer** [comment]
Thanks for the pointer @rp-199 , this should be fixed in #1987 . Looks like this is also the root cause for #1979 . Please re-open this issue if the problem persists in the `latest` version. Thanks

**Comment by rp-199** [comment]
@whummer I can confirm that this is working.

Due to the changes to the remote debugging introduced since Java 9, the java options must be changed a little bit to get this to work:

- Java 8:
`agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=_debug_port_`

- Java 11:
`agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=*:_debug_port_` 

It's advised in the documentation that this comment is not secure and should be used the following instead:
`-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=127.0.0.1:_debug_port_`

But I didn't get this second one to work.

Source: https://www.baeldung.com/java-application-remote-debugging
