### ISSUE TITLE
Can multiple instances for any service invoked 

### ISSUE THREAD

**Issue by mayank-kapoor** [localstack/localstack#1990]
I need multiple instances of lambda services running using localstack, with each lambda having its own handler function. 

Same with SQS, I need it to scale it to 4 instances all  consuming different message streams.

Is it possible to scale instances in localstack ??

**Comment by whummer** [comment]
Hi @mayank-kapoor , thanks for your question. Yes, that should be possible - I don't see a particular reason why this would not work. While LocalStack doesn't provide the same scalability/performance as the real AWS cloud (for obvious reasons), it does allow you to add multiple resources (e.g., Lambda functions, SQS queues, S3 buckets, etc) in parallel.

Closing this issue, as this issue tracker is primarily for reporting bugs or for clarifying specific technical issues (not for general help on how to build an AWS app). Please prepare a small working example with the scenario you're describing, and get back to us if there are any particular issues. Thanks!

**Comment by mayank-kapoor** [comment]
@whummer this is my docker-compose for multiple sqs instances 
```version: '3.7'
services:
 sqs-1:
   image: localstack/localstack:latest
   environment:
     - SERVICES=sqs
     - DEBUG=1
     - DEFAULT_REGION=ap-southeast-2
     - DATA_DIR=/tmp/localstack/data
     - AWS_DEFAULT_REGION=ap-southeast-2
     - AWS_ACCESS_KEY_ID=foobar
     - AWS_SECRET_ACCESS_KEY=foobar
     - AWS_CBOR_DISABLE=true
     - SQS_PORT_EXTERNAL=1234
   ports:
    - "4567-4584:4567-4584"
   volumes:
     - './.localstack:/tmp/localstack'
     - '/var/run/docker.sock:/var/run/docker.sock'
 sqs-2:
   image: localstack/localstack:latest
   environment:
     - SERVICES=sqs
     - DEBUG=1
     - DEFAULT_REGION=ap-southeast-2
     - DATA_DIR=/tmp/localstack/data
     - AWS_DEFAULT_REGION=ap-southeast-2
     - AWS_ACCESS_KEY_ID=foobar
     - AWS_SECRET_ACCESS_KEY=foobar
     - AWS_CBOR_DISABLE=true
     - SQS_PORT_EXTERNAL=5678
   ports:
    - "5567-5584:5567-5584"
   volumes:
     - './.localstack:/tmp/localstack'
     - '/var/run/docker.sock:/var/run/docker.sock' ```


Sqs Instances do come up in parallel but I cant access the 2nd sqs instance from my host machine
 SQS_PORT_EXTERNAL=5678 does not map to anything as curl -X 'localhost:5678' throws connection refused.

**Comment by mayank-kapoor** [comment]
#1995
