### ISSUE TITLE
Unable to create a new apigateway  model

### ISSUE THREAD

**Issue by n9iels** [localstack/localstack#1991]
It seems impossible to create a new apigateway model, whatever I try I am getting a 404 Not Found error. The command I am  trying to run is
```
aws apigateway get-models --rest-api-id 6el5sjbx45 --endpoint-url http://localhost:4567
```
The given `rest-api-id` exists and is valid.

**Comment by xpositivityx** [comment]
@n9iels I was getting a 404 when trying to do the same thing with terraform. Looking at the code it doesn't look like the API for models is defined. I need this for the current project I am working on so I am up for tag teaming a PR to add this feature if you are!

**Comment by whummer** [comment]
Hi @xpositivityx @n9iels any updates on this issue - would you be able to contribute an upstream pull request against [`moto`](https://github.com/spulec/moto) to get this functionality in? That would be much appreciated, thanks!

**Comment by xpositivityx** [comment]
@whummer I can start working on it next week!

**Comment by whummer** [comment]
Thanks @xpositivityx @n9iels - this should be fixed in the `latest` version, can you please give it another try? An integration test has been added in #2390 to cover this functionality. Please report here if the problem persists. Thanks
