### ISSUE TITLE
My docker-compose.yml doesn't work at AWS Codebuild

### ISSUE THREAD

**Issue by inyukwo1** [localstack/localstack#1994]
I am currently using localstack with docker-compose.yml as below.
```
version: '3.2'
services:
  localstack:
    image: localstack/localstack:latest
    container_name: ohc_localstack
    ports:
      - '4563-4599:4563-4599'
      - '8055:8080'
    environment:
      - SERVICES=s3,dynamodb,sqs
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DEFAULT_REGION=ap-northeast-2
    volumes:
      - './.localstack:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
```

Using this file, I could use S3 as below commands
```
export AWS_ACCESS_KEY_ID=foobar
export AWS_SECRET_ACCESS_KEY=foobar
export AWS_DEFAULT_REGION=ap-northeast-2
docker-compose up -d
aws --endpoint-url=http://localhost:4572 s3 mb s3://ohc-s3
```
It works well at my local environment, but I want to do this at AWS Codebuild for unit test.
When I run my commands in Codebuild, it fails with logs below.
![image](https://user-images.githubusercontent.com/18697844/73316513-708bb680-4276-11ea-9139-8dc34eea38ba.png)
Do you have any ideas?

**Comment by whummer** [comment]
Thanks for reporting @inyukwo1 . This could be related to a timing issue. Please note that LocalStack may take a few seconds to fully start up.

Can you try adding, e.g., a `sleep 15` statement, or poll the output of the Docker container until the string `Ready.` appears in the logs? 

Also, would be easier to debug if you could set `DEBUG=1` and print out the logs of the container. Thanks

**Comment by inyukwo1** [comment]
Resolved adding `sleep 15s`. Thanks!
