### ISSUE TITLE
Maven dependency localstack-utils jar missing

### ISSUE THREAD

**Issue by JeromeSimmonds** [localstack/localstack#200]
Hi,

Adding the `localstack-utils` dependency to my project doesn't download any jar file, am I supposed to install it myself? The README just says to add the dependency to the pom...

Thanks.

**Comment by mattvv** [comment]
adding 
```
            <dependency>
                <groupId>cloud.localstack</groupId>
                <artifactId>localstack-utils</artifactId>
                <version>0.1.1</version>
                <scope>test</scope>
            </dependency>
```

Worked for me in my maven file. A heads up you will need to make sure docker is running before using.

**Comment by JeromeSimmonds** [comment]
My local repo only contains `localstack-utils-0.1.1.pom`, `localstack-utils-0.1.1.pom.lastUpdated` and `localstack-utils-0.1.1.pom.sha1`.

**Comment by whummer** [comment]
Thanks for reporting @JeromeSimmonds . It *should* work out of the box, you should not have to manually download any jar file, and starting the Docker container should not be necessary either (the `localstack-utils` library installs LocalStack to a temporary folder).

Can you please try the following:

* Clean libs from local Maven cache:
```
# assuming you are on UNIX:
rm -r ~/.m2/repository/cloud/localstack
```

* Clean the `localstack_install_dir` installation folder, which is located in your local temp folder (as reported by the `$TMPDIR` environment variable, and by Java's system property `java.io.tmpdir`). Depending on your platform, this may be located in either of these folders:
   * `/var/folders/abc/xyz/T/localstack_install_dir` (on Mac OS, where `abc` and `xyz` are some random strings)
   * `/tmp/localstack_install_dir`

You should be able to clean this folder via:
```
rm -r $TMPDIR/localstack_install_dir
```

After cleaning up, please re-run your test using Maven/Java. (This should re-install the required dependencies.)

If things are still not working, please post the output of the following commands:

```
$TMPDIR/localstack_install_dir/bin/localstack --version
$TMPDIR/localstack_install_dir/bin/localstack start
```

(Thinking more about this, we should probably allow users to configure whether to start LocalStack locally or in a Docker container, when executing from within Java. Currently we always default to local installation in `$TMPDIR/localstack_install_dir/`. The current workaround is to run the Docker container *before* running the Java tests, but that's probably not ideal.)

**Comment by JeromeSimmonds** [comment]
Thanks for answering.

So about Maven, if I declare the [Spring repo](https://repo.spring.io/libs-release) in my pom, the `localstack-utils` dependency is downloaded from there and gives me this error about `process-tree-killer`
`Failure to find org.ow2.proactive:process-tree-killer:jar:1.0.0 in https://repo.spring.io/libs-release was cached in the local repository, resolution will not be reattempted until the update interval of spring-releases has elapsed or updates are forced`

**Comment by mattvv** [comment]
I got the same error here. I had to add process-tree-killer to my nexus

**Comment by whummer** [comment]
@JeromeSimmonds @mattvv This issue should be solved with the latest version `localstack-utils:0.1.2` - the dependency on process-tree-killer has been removed. Can you please give it a try? Thanks

**Comment by JeromeSimmonds** [comment]
It works thanks!
