### ISSUE TITLE
Region is ignored when creating functions

### ISSUE THREAD

**Issue by n9iels** [localstack/localstack#2004]
## Issue description
When creating a lambda function for a specific region the function arn is always pointing to `us-east-1`.

## Steps to reproduce
1. Create a new Lambda function and specify the region. For example

```
aws lambda create-function --endpoint-url http://localhost:4574 --function-name MyLambdaFunction --zip-file fileb://./my-lambda.zip --handler 'class.Application' --runtime java11 --role role --region eu-west-1
```

The response will contain the following function arn:

```
arn:aws:lambda:us-east-1:000000000000:function:MyLambdaFunction
```

## Expected result
A function arn with the specified region, eg. `arn:aws:lambda:eu-west-1:000000000000:function:MyLambdaFunction`

## Version information
Latest docker images ~`0.10.7`~ `latest` (`5cd264909bd19202ff4cb070d7d6aade5439d72f8fc1603f7f272a9cf4a33c31`)

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-151) by [Unito](https://www.unito.io/learn-more)

**Comment by mayank-kapoor** [comment]
@n9iels Region is taken into account while creating functions 
Lambda Create : `aws --endpoint-url=http://localhost:4574 lambda create-function --function-name test-function --region ap-southeast-2 --runtime nodejs8.10 --handler index.lambdaHandler --memory-size 128 --zip-file fileb://handler.zip --role arn:aws:iam::000000000000:role/irrelevant:role/irrelevant`


Lambda get-function returns correct region :
`{
    "Code": {
        "Location": "http://localhost:4574/2015-03-31/functions/test-function/code"
    },
    "Configuration": {
        "TracingConfig": {
            "Mode": "PassThrough"
        },
        "Version": "$LATEST",
        "CodeSha256": "Th5AliFLsJ01GjpEYTls+KD9qcT9uEXmF1AhkGvGO7o=",
        "FunctionName": "test-function",
        "MemorySize": 128,
        "RevisionId": "88f0ff3e-d0af-4604-9678-23bdef33c493",
        "CodeSize": 644,
        "FunctionArn": "arn:aws:lambda:ap-southeast-2:000000000000:function:test-function",
        "Handler": "index.lambdaHandler",
        "Role": "arn:aws:iam::000000000000:role/irrelevant:role/irrelevant",
        "Timeout": 3,
        "LastModified": "2020-02-05T02:26:57.064+0000",
        "Runtime": "nodejs8.10",
        "Description": ""
    }
}`

**Comment by n9iels** [comment]
I just pulled the latest version from Dockerhub and tried again, still having the same result. For the record, I did not change the `DEFAULT_REGION` environment variable in the docker compose file. So my default region is indeed `us-east-1`, but I am expecting to see a Lambda created in the specified region.

**Comment by whummer** [comment]
Thanks for reporting. This should be fixed in the meantime - recent versions of LocalStack should allow you to create Lambdas (and other resources) created in the region specified by the client. Please let us know if the problem persists. Thanks!
