### ISSUE TITLE
Lambdas Call Actual AWS Instead of Localstack Edge

### ISSUE THREAD

**Issue by miles-po** [localstack/localstack#2006]
When I create a Lambda, the container Localstack creates to run it does not redirect AWS SDK endpoint DNS calls to itself; the lambda tries to connect to actual AWS on the public IPs and fails with an error like the following:
```
An error occurred (InternalFailure) when calling the Invoke operation (reached max retries: 4): Error executing Lambda function arn:aws:lambda:us-east-1:000000000000:function:S3IngestToKinesis: Lambda process returned error status code: 1. Result: {"errorType":"UnrecognizedClientException","errorMessage":"The security token included in the request is invalid."}
```
In a test lambda running locally, I called it with this code:
```js
const dns = require('dns');

exports.handler = (event, context, callback) => {
  const options = {
    family: 4,
  };
  dns.lookup('kinesis.us-east-1.amazonaws.com', options, (err, address, family) => {
    callback(err, address);
  });
};
// Returns "3.91.171.130", the public AWS endpoint
```
This means you must specify a Localstack endpoint even if you are running "edge" in the Pro version.

Would prefer the container inherited the DNS of the Localstack container (when run in docker-compose) or at least allowed the option in case someone had a hybrid Localstack/AWS environment.

Workaround is to edit every lambda to use the custom endpoint as a local hostname or IP of Localstack, eg.
```js
  const kinesis = new AWS.Kinesis({
    apiVersion: '2013-12-02',
    region: 'us-east-1',
    endpoint: 'http://10.5.0.3:4568'
  });
```

***EDIT: Workaround does not work unless the lambda is part of the same Docker network. See: LAMBDA_DOCKER_NETWORK***

**Comment by krimple** [comment]
If I understand correctly, you would have to set up conditional variables for a given stack/stage so when you deploy you'd conditionally set the endpoint to a localstack one or aws?

**Comment by miles-po** [comment]
That's what it looks like to me.

**Comment by whummer** [comment]
Thanks again for reporting this issue @miles-po . As discussed offline in the chat, you've been able to apply the workaround using `LAMBDA_DOCKER_NETWORK`. Closing this issue as resolved - please feel free to re-open if the problem persists. Thanks!
