### ISSUE TITLE
RDS Postgres Service lacks RDS Roles

### ISSUE THREAD

**Issue by jheinnic** [localstack/localstack#2009]
Our primary use for testing RDS with LocalStack involves mocking the setup and consumption of Postgres Logical Replication slots.

One of the things we typically need to do when bootstrapping this process is to use the RDS master account to create an account with replication privileges.

Unfortunately, the master user account does not have privilege to do this--we end up having to use the 'postgres' superuser, which should not even exist in the first place.  

Some deviations follow:
1)  Cannot create a test user and delegate the `rds_superuser` role when logged in as master user because master user is not privileged:
```
postgres=> create role testuser with password 'testuser' login;
ERROR:  permission denied to create role
```

2) .Cannot create a test user and delegate either the `rds_superuser` or `rds_replication` roles when logged in as `postgres` because neither role exists:
```
postgres=# create role testuser with password 'testuser' login; 
CREATE ROLE
postgres=# grant rds_superuser to testuser;  
ERROR:  role "rds_superuser" does not exist
postgres=# grant rds_replication to testuser;  
ERROR:  role "rds_replication" does not exist
```

3) Cannot create a replication slot when connected using the RDS master user account because it s not privleged:
```
postgres=> select pg_create_logical_replication_slot('slotb', 'wal2json');
ERROR:  must be superuser or replication role to use replication slots
```

**Comment by whummer** [comment]
Thanks for reporting @jheinnic . Can you please do a `docker pull localstack/localstack` and give it another try?

Getting this with latest:

```
$ psql -h localhost -p 4510 --user test
Password for user test: 
psql (11.2, server 11.6)
Type "help" for help.

test=# create role testuser with password 'testuser' login;
CREATE ROLE
test=# grant rds_superuser to testuser;  
GRANT ROLE
test=# grant rds_replication to testuser;  
GRANT ROLE
test=# select pg_create_logical_replication_slot('slotb', 'wal2json');
ERROR:  could not access file "wal2json": No such file or directory
```
Note that the issue with dynamically changing DB parameters (e.g., `rds.logical_replication`) at runtime still needs to be addressed - we'll use issue #2010 to follow up on that shortly. Thanks!
