### ISSUE TITLE
RDS Postgres Service does not apply rds.logical_replication=1 setting correctly.

### ISSUE THREAD

**Issue by jheinnic** [localstack/localstack#2010]
When the rds.logical_replication DB Parameter Group parameter value is set to 1, RDS is supposed change several instance parameters to enable logiical replication, such as setting `wal_level` = `logical`, but this has no effect on those parameters.

```
awslocal rds create-db-parameter-group --db-parameter-group-name jch.postgres9.6 --db-parameter-group-family postgres9.6
awslocal rds modify-db-parameter-group --db-parameter-group-name jch.postgres9.6 --parameters '[ {"ParameterName": "rds.logical_replication", "ParameterValue": "1", "ApplyMethod": "immediate"} ]'
awslocal rds modify-db-instance --db-instance-identifier  test-instance --db-parameter-group-name jch.postgres9.6
```

... then from a psql session logged in as the postgres super user ...

```
postgres=# select pg_create_logical_replication_slot('slotb', 'wal2json');
ERROR:  logical decoding requires wal_level >= logical
postgres=# 
postgres=# 
postgres=# show wal_level;
 wal_level 
-----------
 replica
(1 row)
```

**Comment by whummer** [comment]
Thanks for reporting @jheinnic . Can you please do a `docker pull localstack/localstack` and give it another try? The latest version has been improved to dynamically reload RDS parameters on `modify-db-instance` and restart the Postgres process if needed (required to start certain config parameters). Please report here if the problem persists. Thanks.

**Comment by whummer** [comment]
Closing this one as resolved - please re-open this issue if the problem persists. Thanks!
