### ISSUE TITLE
Sqs is not getting started but queue getting created

### ISSUE THREAD

**Issue by mayank-kapoor** [localstack/localstack#2012]
whummer

Issue Description: Sqs service is not getting started at all but create queue operation is success-full, logs attached as reference.

Not able to perform any operations apart from create queue

docker-compose file 
```version: '3.7'
services:
 sqs-1:
   image: localstack/localstack:latest
   environment:
     - SERVICES=sqs
     - DEBUG=1
     - HOSTNAME=aws-sqs1
     - HOSTNAME_EXTERNAL=aws-sqs1-ext
     - DEFAULT_REGION=ap-southeast-2
     - DATA_DIR=/tmp/localstack/data
     - AWS_DEFAULT_REGION=ap-southeast-2
     - AWS_ACCESS_KEY_ID=foobar
     - AWS_SECRET_ACCESS_KEY=foobar
     - AWS_CBOR_DISABLE=true
     - SQS_PORT_EXTERNAL=1234
   ports:
    - "1234:4576"
   volumes:
     - './.localstack:/tmp/localstack'
     - '/var/run/docker.sock:/var/run/docker.sock' 
```

![Sqs Logs](https://user-images.githubusercontent.com/50835622/73618444-e54a6080-467b-11ea-8445-1cfafb569ac5.png)

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-152) by [Unito](https://www.unito.io/learn-more)

**Comment by BR0kEN-** [comment]
Try to change the region to the default one (`us-east-1`).

https://github.com/localstack/localstack/issues/1290#issuecomment-531595250

**Comment by ambreenshameem** [comment]
@BR0kEN-  my SQS only works with $AWS_DEFAULT_REGION 

aws --endpoint-url=http://localhost:4574 lambda create-event-source-mapping --event-source-arn arn:aws:sqs:$AWS_DEFAULT_REGION:000000000000:my_sqs --function-name SQSdemo

It doesn't work with us-east-1 or elasticmq. Many people are using us-east-1 for triggering lambda thru SQS, trying to understand the correct behavior.

**Comment by whummer** [comment]
Thanks for reporting @mayank-kapoor - this should be fixed in the meantime as we've switched to a different SQS backend and pushed several fixes in the meantime. If the problem persists, please also try running without `DATA_DIR` enabled. Thanks
