### ISSUE TITLE
More fine-grained Dynamo error injection

### ISSUE THREAD

**Issue by mcintyre94** [localstack/localstack#2013]
I'm using Localstack to test a service which reads from a Dynamo table, then attempts to delete (using BulkWrite), and handles errors from the deletes in a specific way. Ideally I'd like to use error injection here such that I have a 0% chance of errors on the read, but a 100% on the write within this test to validate its behaviour when that delete fails. It'd be great to be able to configure the chance of read and write APIs erroring independently for this.

A possible workaround would be to inject the failure (by modifying config) in the code under test between read and write - but I can't really get away with that because that production code shouldn't know anything about localstack or being under test.

**Comment by whummer** [comment]
Hi @mcintyre94 , thanks for this suggestion. This would be definitely useful - we could introduce new config variables `DYNAMODB_READ_ERROR_PROBABILITY`/`DYNAMODB_WRITE_ERROR_PROBABILITY` to that effect. Do you think you could contribute a small pull request to add this feature? That would be much appreciated - thanks!

**Comment by whummer** [comment]
@mcintyre94 This feature has been added in #3057 - can you please give it a try with the `latest` version of the Docker image, and let us know if this covers your use case. Thanks
