### ISSUE TITLE
Add permission to lambda is failing

### ISSUE THREAD

**Issue by mayank-kapoor** [localstack/localstack#2016]
Add permission Call 
```aws --endpoint-url=http://localhost:4574 lambda add-permission --function-name test-function --action lambda:InvokeFunction --statement-id sqs --principal sqs.amazonaws.com ```

Error:
```An error occurred (500) when calling the AddPermission operation (reached max retries: 4): <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>```

Reference to add permission  : https://docs.aws.amazon.com/cli/latest/reference/lambda/add-permission.html

**Comment by victoriangtempus** [comment]
Also getting this same error:

My docker-compose.yaml
 `version: '2.1'
services:
  localstack:
    privileged: true
    container_name: localstack-main
    image: localstack/localstack
    ports:
      - "4566-4599:4566-4599"
      - 8080:8080
    environment:
      - SERVICES=lambda,sns,stepfunctions,cloudwatch,iam
      - LAMBDA_REMOTE_DOCKER=false
      - DATA_DIR=./data
      - LAMBDA_EXECUTOR=docker-reuse
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEBUG=1
      - LOCALSTACK_API_KEY=xxxx
      - DEFAULT_REGION=us-east-1 
      - HOST_TMP_FOLDER=${TMPDIR}
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"`

What I get when I do list-functions:
`{
    "Functions": [
        {
            "FunctionName": "bioinformatics-kickoff-lambda",
            "FunctionArn": "arn:aws:lambda:us-east-1:000000000000:function:bioinformatics-kickoff-lambda",
            "Runtime": "nodejs10.x",
            "Role": "arn:aws:iam::123456789012:role/service-role/sample-role",
            "Handler": "index.handler",
            "CodeSize": 44716481,
            "Description": "",
            "Timeout": 3,
            "LastModified": "2020-04-09T21:15:26.894+0000",
            "CodeSha256": "bmJ9vkWAnljIfdy3XWkbYplPbJjKjdShU1ob2sdM3P8=",
            "Version": "$LATEST",
            "Environment": {
                "Variables": {
                    "ANALYZE_DIPLOTYPE_CALL_STATE_MACHINE_ARN": "arn:aws:states:us-east-1:148609763264:stateMachine:rp-bioinf-pipeline-tooling-dcall",
                    "ANALYZE_VARIANT_CALL_STATE_MACHINE_ARN": "arn:aws:states:us-east-1:000000000000:stateMachine:test-state-machine",
                    "ANALYZE_VARIANT_CHARACTERIZATION_STATE_MACHINE_ARN": "arn:aws:states:us-west-2:491185294446:stateMachine:rp-development-analyze-variant-characterization-state-machine",
                    "GIT_HASH": "91084f0f2d65e05017bb36110b272815587b7900",
                    "LIMS_ROOT_URL": "\thttps://lims-service.stagingtempus.com",
                    "MACHINE_USER_EMAIL": "machine-user+rp-orchestration-staging-20181022@tempus.com",
                    "NODE_ENV": "development",
                    "OKTA_SERVER_URL": "https://tempus.oktapreview.com/oauth2/ausfjxf2zb85ZfrrS0h7",
                    "ORDER_HUB_ROOT_URL": "https://orderhub-p.devtempus.com",
                    "PAGER_DUTY_SNS_TOPIC_ARN": "arn:aws:sns:us-west-2:491185294446:pagerduty_sns_development",
                    "SCIENCE_REGION": "us-west-2",
                    "SERVICE_NAME": "rp-bioinformatics-kickoff-lambda-standalone"
                }
            },
            "TracingConfig": {
                "Mode": "PassThrough"
            },
            "RevisionId": "fe309c22-9713-4661-ae46-3e21c7470bae",
            "State": "Active",
            "LastUpdateStatus": "Successful"
        },
        {
            "FunctionName": "exampleLambda",
            "FunctionArn": "arn:aws:lambda:us-east-1:000000000000:function:exampleLambda",
            "Runtime": "nodejs8.10",
            "Role": "arn:aws:iam::000000000000:role/lambda-basic-execution",
            "Handler": "exampleLambda.handler",
            "CodeSize": 315,
            "Description": "",
            "Timeout": 3,
            "LastModified": "2020-04-09T21:24:36.937+0000",
            "CodeSha256": "feR0FxQIszbf/TeHuZE6ziMNZLEgYXPuFf8c5Dk2Qls=",
            "Version": "$LATEST",
            "TracingConfig": {
                "Mode": "PassThrough"
            },
            "RevisionId": "933ce3f0-2891-47f3-be8e-7a6dab171a17",
            "State": "Active",
            "LastUpdateStatus": "Successful"
        }
    ]
}`

Command I use to add permission
`awslocal lambda add-permission \                                                  BIOENG-653-integration-test-invoke-step-function * ] 1:08 PM
    --function-name exampleLambda \
    --action lambda:InvokeFunction \
    --statement-id sns \
    --principal sns.amazonaws.com`

Result of the command above
`An error occurred (500) when calling the AddPermission operation (reached max retries: 4): <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>`

**Comment by whummer** [comment]
Thanks for reporting @mayank-kapoor @victoriangtempus . This appears to be fixed in the `latest` version:
```
$ echo 'def handler(*args, **kwargs): pass' > /tmp/testlambda.py
$ (cd /tmp; zip testlambda.zip testlambda.py)
  adding: testlambda.py (deflated 1%)
$ awslocal lambda create-function --function-name func1 --runtime python3.6 --role r1 --handler testlambda.handler --zip-file fileb:///tmp/testlambda.zip
...
$ aws --endpoint-url=http://localhost:4574 lambda add-permission --function-name func1 --action lambda:InvokeFunction --statement-id sqs --principal sqs.amazonaws.com
{
    "Statement": "sqs"
}
```
Please report here with detailed steps to reproduce if the problem persists on your end. Thanks!
