### ISSUE TITLE
Configure the "destroy idle containers" behaviour

### ISSUE THREAD

**Issue by Ovski4** [localstack/localstack#2018]
Hi,

Would it be ok if it was possible to configure the "destroy idle containers behaviour"?

Running lambdas for the first time is slow. This is not an issue for asynchronous lambdas. However in my case some lambdas gets triggered by http requests and are called synchrously. http requests time out before the lambda gets bootstrapped and run for the first time.
When developing I'm not reloading pages every 10 minutes to keep lambda containers alive.

A few options I can think of:

- set the value of MAX_CONTAINER_IDLE_TIME_MS from an environment variable
- have another variable like DESTROY_IDLE_LAMBDAS that could be set to false and defaulted to true

What do you think? I would be happy to work on a PR for it

**Comment by whummer** [comment]
Hi @Ovski4 , interesting proposal. I think that is something that could be generally useful for a wider user base. Would you be able to contribute a pull request? That would be very much appreciated. Thanks!

**Comment by whummer** [comment]
Should be fixed in #2094 - thanks for digging into this. 👍
