### ISSUE TITLE
Use more open-ended version specifiers in requirements.txt

### ISSUE THREAD

**Issue by jperras** [localstack/localstack#2019]
## Summary

There are several dependency entries in the `requirements.txt`, which is loaded by the `setup.py` during installation of a `[full]` setup, that are pinned to exact versions.

Notably, in my case, `psutil`:

https://github.com/localstack/localstack/blob/9df78c39609f62bbe484ff1f4558155eaeffe9c4/requirements.txt#L38

This causes some very difficult to resolve dependency problems if using `pipenv` with some other package that requires an incompatible version of said dependency, which is very likely to happen if one of those dependencies is a pinned one.

### Steps to Reproduce

The `locustio` package is a load testing tool that *also* depends on `psutil`, but requires `>=5.6.7`. Attempting to have both `localstack[full]` and `locustio` in the same environment will result in a version incompatibility.

1.  Ensure `pipenv` is installed.
2. Create a `Pipfile` with the following entries:

    ```ini
    [[source]]
    name = "pypi"
    url = "https://pypi.org/simple"
    verify_ssl = true

    [packages]
    localstack = {extras = ["full"],version = "*"}
    locustio = "*"
    ```
3. `pipenv install` the above `Pipfile`.
4. An error output containing `ERROR: ERROR: Could not find a version that matches psutil==5.4.8,>=5.6.7` will be produced.

**Comment by whummer** [comment]
Thanks for reporting @jperras . Do you think you could take a stab at this and make the required changes? Very happy to accept a pull request.

Generally speaking, though, please note that installing `localstack[full]` on your local machine is not recommended / deprecated. The default and recommended way of installing LocalStack is using the Docker image (i.e., simply installing `localstack` and then running `localstack start`). I'm sure you have a reason for why you're choosing this particular installation path, but just wanted to mention it.

Thanks

**Comment by jperras** [comment]
@whummer Happy to take a shot at a pull request with the required changes. Anything I should know or take into consideration regarding testing other than running `make test`? I know changing some fundamental dependencies in a library can sometimes be tricky.

**Comment by whummer** [comment]
@jperras I think the easiest (and most reproducible) will be to either run `make docker-build` (which builds the image and runs the tests), or simply use the CI system to run the tests. You can simply fork the repo, create a pull request, and then Travis-CI will run the integration tests. Thanks

**Comment by whummer** [comment]
Any updates on this @jperras ? Would be great if we could get this one resolved. Thanks!
