### ISSUE TITLE
Can't create state machine for Step Function

### ISSUE THREAD

**Issue by Azuaron** [localstack/localstack#2027]
I'm trying to setup a Step Function locally, but I can't submit the state machine definition using the AWS CLI because it demands a --role-arn, but won't accept anything I give it:

> An error occurred (InvalidArn) when calling the CreateStateMachine operation: Invalid Role Arn: 'arn:aws:iam::aws:policy/AWSBatchFullAccess'

I've tried with and without IAM running. I've tried several different ARNs. Nothing seems to work.

Here's my docker-compose file:

```
  awsstack:
    image: localstack/localstack
    ports:
      # Step Functions: 4585
      # IAM: 4593
      - "4567-4593:4567-4593"
      - 8079:8079
    environment:
      - SERVICES=stepfunctions,iam
      - DEFAULT_REGION=us-east-1
      - DEBUG=0
      - DATA_DIR=${DATA_DIR- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - PORT_WEB_UI=8079
      - AWS_ACCESS_KEY_ID=access
      - AWS_SECRET_ACCESS_KEY=secret
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

Here's the CLI command I'm trying to use to create the state machine:

`aws --endpoint-url=http://localhost:4585 stepfunctions create-state-machine --name Test --role-arn arn:aws:iam::aws:policy/AWSBatchFullAccess --definition "{\"StartAt\":\"my-function\", \"States\": { \"my-function\": { \"Type\":\"Pass\", \"Result\": { \"x-datum\": 0.3 }, \"ResultPath\": \"$.coords\", \"End\": true }}}"`

Any help would be greatly appreciated.

**Comment by ciaranevans** [comment]
@Azuaron strange that you're having this issue. 

We don't use the CLI to provision our Step Functions, but we do use Terraform, (With the knowledge that IAM isn't enforced) we put the following role into our scripts:

```
role_arn = "arn:aws:iam::000000000000:role/a-role"
```

**Comment by Azuaron** [comment]
That did it! Don't know why that works and the others don't, but I'll take it.

**Comment by ciaranevans** [comment]
@Azuaron I think it might be the formatting of your arn. It's normally `arn:aws:service::<big-number>:thing/things-name`

Glad it worked!
