### ISSUE TITLE
SQS Service InvalidParameterValue error on WaitTimeSeconds

### ISSUE THREAD

**Issue by itomaldonado** [localstack/localstack#2030]
I was having some issues using `celery` and localstack, but after removing `celery` form the equation I found out that the problem is localstack and how it handles the `ReceiveMessage` SQS action when the `WaitTimeSeconds` parameter is sent.

Here is some interactions (and versions of everything I am using):
(localstack is inside a docker container... I show the version here)...
```
➜ aws --version
aws-cli/1.17.12 Python/3.7.4 Darwin/17.7.0 botocore/1.14.12

➜ ./bin/localstack --version
0.10.7

➜ aws --endpoint-url=http://localstack.docker:4576 sqs receive-message --queue-url=http://localhost:4576/queue/some-tasks --wait-time-seconds 30

An error occurred (InvalidParameterValue) when calling the ReceiveMessage operation: InvalidParameterValue; see the SQS docs.
```

Not sure why this parameter is wrong, since it is in the docs, any suggestions?

**Comment by whummer** [comment]
Thanks for reporting @itomaldonado . Looks like the maximum long polling wait time is 20 seconds - see, e.g., here: https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/examples-sqs-long-polling.html

We briefly tried it with values up to 20s and it seems to work fine.

Closing this issue, but please feel free to re-open or provide more details if the problem persists. Thanks!
