### ISSUE TITLE
aws cli s3 sync --exact-timestamps not matching API

### ISSUE THREAD

**Issue by wojons** [localstack/localstack#2032]
When running a sync command like 
```bash
aws s3 sync s3://bucket ./my/path --exact-timestamp
```

will re-download files every single time if i am  pulling from localstack s3 but when i run it on a real s3 bucket it will do the first sync and then not again until the  file changes. this is needed if the file size is the same but the contents change.

**Comment by Akhil-786** [comment]
### 

>  #[`_****_`](

- 

- [ ] @url

)

**Comment by rmsmani** [comment]
@whummer 
Am new to localstack development, so I need your help to start on this.

**Comment by Akhil-786** [comment]
ok fine

**Comment by macnev2013** [comment]
Hello @wojons, Thanks for reporting the bug.

**Comment by whummer** [comment]
Thanks for reporting @wojons @rmsmani @Akhil-786 , this should be fixed in `latest` - please report here if the problem persists. Thanks
