### ISSUE TITLE
Cannot resolve method 'useSingleDockerContainer'

### ISSUE THREAD

**Issue by sculley** [localstack/localstack#2038]
I am trying to set the useSingleDockerContainer attribute in the LocalstackDockerProperties annotation but its not available.

I am this version of [localstack-utils](https://mvnrepository.com/artifact/cloud.localstack/localstack-utils/0.2.0)

I can see that this version was added on the (7th Dec 2019) but the commit which added the useSingleDockerContainer attribute was on the (13th Dec 2019)

https://github.com/localstack/localstack/commit/f980a0c724ee0d79b59211d40590188129754967

When will the latest code be pushed to mvnrepository?

**Comment by whummer** [comment]
Thanks for reporting @sculley . This should have been fixed in the meantime - a new version `0.2.1` has been pushed to Maven Repository. Please report here if the problem persists. Thanks
