### ISSUE TITLE
Data persistence not working with pip installation and --docker flag

### ISSUE THREAD

**Issue by MatheusVellone** [localstack/localstack#204]
I installed localstack with `pip install`.
After that, I added `export DATA_DIR=/tmp/localstack/data` env var as the docs says to my `.bashrc` file and tested with the command `echo $DATA_DIR` which gave me the correct path.
Then I started it with the `--docker` flag, created some dynamo tables (and checked their existance) and stopped localstack process.
Re-started the process with the same command and lost all tables I previously created. I've tested this a couple of times and all of them resulted in the lost of data.

To try something else, I cloned this repo, `make install` and started with `make infra` to run a local copy. At this point, the `DATA_DIR` variable already was set.
After the process was running, created the same tables, stopped process and started it again, but in this case all tables had persisted.

Shouldn't data persistance through pip installation with --docker flag work too ?

**Comment by whummer** [comment]
Thanks for reporting @MatheusVellone . Can you please pull the latest version of the code, then run:
```
DATA_DIR=/tmp/localstack/data make docker-run
```
Once you confirm that this works, we'll release a new version. Thanks

**Comment by MatheusVellone** [comment]
Thanks for the quick response and fix @whummer!
Tested it and works perfectly!
