### ISSUE TITLE
Java arguments are not applied.

### ISSUE THREAD

**Issue by imayorski** [localstack/localstack#2044]
In case of lambda execution with the following properties:
LAMBDA_EXECUTOR=local
LAMBDA_JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5005
The arguments are not supplied to the runner.

**Comment by bitwisekaizen** [comment]
Is there any reason why this was deliberately left out? I'd like to be able to add java_opts to my lambda if running locally. Happy to submit a pr unless the reporter and I are missing something obvious.

**Comment by imayorski** [comment]
Fixed by #2050
