### ISSUE TITLE
Support Bucket Versioning Suspended

### ISSUE THREAD

**Issue by rockymountainnative** [localstack/localstack#2051]
With the introduction of localstack 0.10.0, bucket versioning disabled no longer works. The addition of Put/Get BucketVersioning and supporting Versioning = false, can resolve this issue.

https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutBucketVersioning.html

**Comment by whummer** [comment]
Thanks for reporting @rockymountainnative . This should be fixed in `latest`, an integration test has been added in #2402 to cover this functionality. Please report here if the problem persists. Thanks
