### ISSUE TITLE
Is QLDB on the roadmap?

### ISSUE THREAD

**Issue by mnp** [localstack/localstack#2054]
QLDB is not something you can run locally at the moment, not in a container or any other way.  You CAN run a PartiQL parser, but that's the extent of it.

Are there any plans to support QLDB?  Timeframe?  Open or enterprise?

Thanks!

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-154) by [Unito](https://www.unito.io/learn-more)

**Comment by whummer** [comment]
Thanks for reporting. Basic support for QLDB is provided in Pro in the meantime (see [feature coverage](https://github.com/localstack/localstack/blob/master/doc/feature_coverage.md)). Please let us know if you have specific feature requests. Thanks!
