### ISSUE TITLE
SNS SQS subscription: treatment of SNS message attributes of DataType Number diverges from AWS (Regression)

### ISSUE THREAD

**Issue by cmr-surgical-paul-wilkinson** [localstack/localstack#2056]
Hello,

My team has hit an issue introduced in a recent version of LocalStack.

When a message is sent to an SNS topic with an SQS queue subscription, and the message has a message attribute with "DataType" "Number" and "StringValue" "8", then the queue message's body presents that value as a number 8.0, rather than the string "8" (as AWS does).

The issue can be demonstrated with the script below. The script creates the topic, queue, and subscription, then publishes and receives a message:

    #!/usr/bin/env python3
    # -*- coding: utf-8 -*-

    import json
    import os
    import unittest

    import boto3

    RESOURCE_PREFIX = "paul-wilkinson-localstack-2020-02-14-"
    TOPIC_NAME = RESOURCE_PREFIX + "topic"
    QUEUE_NAME = RESOURCE_PREFIX + "queue"

    class TestSnsMessageAttributesToSqs(unittest.TestCase):
        def setUp(self):
            self.sns_resource = boto3.resource(
                service_name="sns", endpoint_url=os.getenv("SNS_ENDPOINT_URL"),
            )
            self.sqs_resource = boto3.resource(
                service_name="sqs", endpoint_url=os.getenv("SQS_ENDPOINT_URL"),
            )
            self.topic = self.sns_resource.create_topic(Name=TOPIC_NAME)
            self.queue = self.sqs_resource.create_queue(QueueName=QUEUE_NAME)
            queue_policy = {
                "Version": "2012-10-17",
                "Statement": [
                    {
                        "Effect": "Allow",
                        "Principal": {"AWS": "*"},
                        "Action": "SQS:SendMessage",
                        "Resource": self.queue.attributes["QueueArn"],
                        "Condition": {"ArnEquals": {"aws:SourceArn": self.topic.arn}},
                    }
                ],
            }
            self.queue.set_attributes(Attributes={"Policy": json.dumps(queue_policy)})
            self.topic.subscribe(Protocol="sqs", Endpoint=self.queue.attributes["QueueArn"])

        def tearDown(self):
            self.queue.delete()
            self.topic.delete()

        def test(self):
            publish_response = self.topic.publish(
                Message="Hello I am the SNS message",
                MessageAttributes={
                    "meal": {"DataType": "String", "StringValue": "peas"},
                    "number_of_widgets": {"DataType": "Number", "StringValue": "8"},
                },
            )
            sqs_messages = self.queue.receive_messages(
                MaxNumberOfMessages=1,
                MessageAttributeNames=[".*"],
                VisibilityTimeout=20,
                WaitTimeSeconds=10,
            )
            message_body = json.loads(sqs_messages[0].body)
            assert "8" == message_body["MessageAttributes"]["number_of_widgets"]["Value"]

    if __name__ == "__main__":
        unittest.main()

When I run this test against real AWS, it succeeds:

    $ AWS_PROFILE=dev python3.8 -m pytest sns_message_attributes_to_sqs.py
    [...]
    1 passed

Whereas when I run the same test against a localstack docker container (`localstack/localstack@sha256:6e1c4f42467dd77efd61c174af0d6625884d25c749df5895db544a995ae2e436` -- the most recent `:latest` image at the time of writing), the test fails:

    $ AWS_PROFILE=fake SNS_ENDPOINT_URL=http://localhost:4575 SQS_ENDPOINT_URL=http://localhost:4576 python3.8 -m pytest sns_message_attributes_to_sqs.py
    [...]
    E       AssertionError: assert '8' == 8.0

The issue is not present in localstack 0.10.4. I think it is caused by these two lines in `localstack/services/sns/sns_listener.py` introduced in https://github.com/localstack/localstack/pull/1760/commits/93fc1846e66f98a411de1a4a0e02150ba9acb7bf:

    if attribute['Type'] == 'Number':
        attribute['Value'] = float(attribute['Value'])

If I remove those lines, my test passes, but unsurprisingly it breaks other localstack tests introduced in the same commit.

Regards,
Paul Wilkinson

**Comment by usmangani1** [comment]
@cmr-surgical-paul-wilkinson 
If you keep these lines then all your sns_tests in tests_sns.py are passing ?Can you verify this and tell me?

**Comment by whummer** [comment]
Thanks for reporting @cmr-surgical-paul-wilkinson . This should be fixed in #2252 - can you please give it a try with the `latest` version of the Docker image? Please report here if the problem persists. Thanks

**Comment by bmastalski** [comment]
I can confirm that it's working with `localstack:latest`. We'll wait for the next tagged release. Thanks for fixing that!
