### ISSUE TITLE
Debug port not exposed.

### ISSUE THREAD

**Issue by imayorski** [localstack/localstack#2057]
When lambdas are executed with the following properties:
LAMBDA_EXECUTOR=docker
LAMBDA_JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5005

or
LAMBDA_EXECUTOR=docker
LAMBDA_JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=debug_port

The arguments are supplied to the java process but the port is not exposed in docker.

**Comment by whummer** [comment]
Thanks for reporting @imayorski . This should be fixed in #2205 - can you please give it a try with the `latest` version? Please report here if the problem persists. Thanks
