### ISSUE TITLE
About KMS

### ISSUE THREAD

**Issue by JeromeSimmonds** [localstack/localstack#206]
Hi,

Good job so far guys, just wondering if KMS is planned?

Thanks.

**Comment by adriangalera** [comment]
Any recent updates on this?

**Comment by nsmithuk** [comment]
@adriangalera & @JeromeSimmonds Don't know if this is any help to you, but I ended up building a way to do KMS locally: https://github.com/nsmithuk/local-kms

**Comment by ozbillwang** [comment]
@nsmithuk 

Any sample for us to make it work with localstack? 

for example, could  you provide a sample `docker-compose.yaml` that I can quickly start up with kinesis service?

**Comment by nsmithuk** [comment]
Hi @ozbillwang 

You shouldn't have any issues running local-kms alongside localstack; I've done this often. As you say above, just bind it to a port you have free in `docker-compose.yaml`.

If you're referring to whether localstack can integrate with local-kms, I'm not aware of localstack having any support for KMS backed encryption, so I don't believe they currently support this.

**Comment by whummer** [comment]
@nsmithuk local-kms looks great! Sorry I noticed this just now. Would you be willing to contribute a PR to make it easily accessible in LocalStack?

I'd be happy to provide guidance. I think we could simply create a new API starter that downloads a pre-built version of the `local-kms` binary (we could either bake it into the image, or lazily download it on demand).

Would be great to make KMS support easily accessible. Please let me know your thoughts. Thanks!

**Comment by ozbillwang** [comment]
nice idea. it would be great to merge them into one. I will help to test it if required.

By the way, seems the kms port in localstack has to be set to 4599 when i run with “awslocal” .

**Comment by nsmithuk** [comment]
@whummer Yes, quite happy to help make it more easily accessible in LocalStack. I'll take your lead on how best to go about it. Are any of the other services run from a pre-built binary, that I can take as an example?

**Comment by matthew-gill** [comment]
Hey @nsmithuk
I just started using local-kms for the first time today... Going to be really helpful, thank you!

Just adding a big +1 to this issue as it would be good to get this all rolled into one.

I'll be happy to help testing if needed!

**Comment by whummer** [comment]
Hi @nsmithuk , I took the liberty of adding a first integration of `local-kms` into LocalStack in this PR: #1839 .

Please review the changes and let us know if you'd like to change anything - including credits in the README, or providing your own repo of pre-built binaries, etc.

Great to have initial support for KMS via `local-kms`, really appreciate your work on this wonderful library!

/cc @JeromeSimmonds @adriangalera @ozbillwang @matthew-gill
