### ISSUE TITLE
Lambda Python3 : where does print output go?

### ISSUE THREAD

**Issue by LazyBrush** [localstack/localstack#2061]
Hi,

I'm working on converting a project to work with localstack.  I've got apigateway, dynamodb, sqs working nicely.  I'm using 'LAMBDA_EXECUTOR=local'.

However, I cannot work out how to get the output from 'print' statements.  

There were some posts describing using cloudwatch, but I couldn't get that working.

Eventually, the python code on the docker container is ran and perhaps the output is stored on that docker container in a file?  If so what's the path of this file?

Thanks!

**Comment by whummer** [comment]
Thanks for reporting @LazyBrush . Can you please try querying the logs from CloudWatch Logs.

Simple test for a Lambda function `func1` that was invoked via the `local` executor:
```
$ awslocal logs describe-log-groups
{
    "logGroups": [
        {
            "logGroupName": "/aws/lambda/func1",
            ...
        }
    ]
}
$ awslocal logs describe-log-streams --log-group-name /aws/lambda/func1
{
    "logStreams": [
        {
            "logStreamName": "2020/08/03/[LATEST]95350151",
            ...
        }
    ]
}
$ awslocal logs get-log-events --log-group-name /aws/lambda/func1 --log-stream-name 2020/08/03/[LATEST]95350151
{
    "events": [
        {
            "timestamp": 1596456607456,
            "message": "INFO: Debug output from Lambda function ...",
            "ingestionTime": 1596456607548
        }
    ]
}
```
Please report here if there are any issues with that. In a future iteration we may also add some debug logs directly to the container output in case `DEBUG=1` is enabled, to allow for easier debugging. Thanks

**Comment by howardwu1** [comment]
So I was able to print the logs after getting the logStreamName value from the describe-log-streams command. However, when I go and return the logStreamName using context.logStreamName in my node code, I get a different logStreamName -- which should work according to the getting started guide here https://docs.aws.amazon.com/lambda/latest/dg/gettingstarted-awscli.html

As an example, this is what I get from the context.logStreamName: -"2021/02/03/[$LATEST]7dc2ecaa90d0dc6c2b4913ab567d8c22"

This is what I get from describe-log-streams: 
"2021/02/03/[LATEST]613d2ea5"

and as you can see it follows the same format was @whummer's example ("2020/08/03/[LATEST]95350151").

Is there any reason why the format and even value would be different?
