### ISSUE TITLE
Re-enable test suite

### ISSUE THREAD

**Issue by mpicard** [localstack/localstack#2062]
The travis build status is quite deceiving, as you have disabled running the tests entirely. If the tests are all red, work should be prioritized to fix them, before releasing new versions.

https://github.com/localstack/localstack/blob/f384f5837caad840201258a3d94e19d4bf68571f/.travis.yml#L57

**Comment by whummer** [comment]
Thanks for reporting @mpicard . The Java sources have now been moved to a separate repo: https://github.com/localstack/localstack-java-utils . We'll fix and re-enable the tests over there.
