### ISSUE TITLE
[FR] Health check route for using localstack within a CI

### ISSUE THREAD

**Issue by applike-ss** [localstack/localstack#2072]
For using localstack within a CI it would be great to have a health check route that tells whether all services are up, running AND healthy.

Currently it feels like we break localstack while it is still starting with out requests to the services. This is yet to be proven though, it's just a guess.

We added localstack as part of our CI run within github actions and it is often triggering errors like this:
```
caused by: Post http://172.17.0.1:9872/: readfrom tcp 172.17.0.1:47524->172.17.0.1:9872: write tcp 172.17.0.1:47524->172.17.0.1:9872: write: broken pipe
```

As you can see based on the IP, we use the docker image (currently 0.10.7).
We separate SQS and SNS in different localstack containers but use the respective endpoint that is exposed via a port to the docker host. SQS is also enabled in the SNS localstack container, so that the proxying works properly.

Any hints to fixing the issue described are also appreciated!

**Comment by kbkk** [comment]
Hello,

we're using this pattern with SQS, I'm sure the same can be done with S3:
```
              until aws --endpoint-url=http://localhost:4576 sqs list-queues > /dev/null 2>&1; do
                sleep 1
              done
```

Although I agree a `/ready` endpoint would be welcome ;)

**Comment by whummer** [comment]
Thanks for reporting @applike-ss @kbkk . A basic `http://localhost:8080/health` endpoint has been added in #2080 - see updated README.

Can you please give it a try with the latest version. We can incrementally add more functionality to the health check endpoint as needed - please report here or open a follow-up issue if a particular functionality is missing. Thanks

**Comment by applike-ss** [comment]
@whummer thanks a lot! That was fast :-) We will check it out today.

**Comment by BeyondEvil** [comment]
For anyone reading this, I couldn't get a response from `8080`, I could however get one from `4566`, eg `http://localhost:4566/health`
