### ISSUE TITLE
[Pro] is it possible to use aurora serverless with AppSync?

### ISSUE THREAD

**Issue by nickygb** [localstack/localstack#2113]
Im evaluating to use localstack pro in order to test AppSync localy. Does localstack provide a mock of aurora Serverless? I have some resolvers that use aurora serverless as data source and i would like to have all my environment in localstack

**Comment by whummer** [comment]
Thanks for reporting @nickygb . AppSync now supports three different types of data sources:
* `AMAZON_DYNAMODB`: data from DynamoDB tables
* `RELATIONAL_DATABASE`: data from Aurora RDS databases (Postgres)
* `AWS_LAMBDA`: data returned from Lambda functions

Can you please give it a try with the `latest` version of the Docker image? We've also updated the demo project here: https://github.com/localstack/localstack-pro-samples/tree/master/appsync-graphql-api Please let us know if there are any issues. Thanks!
