### ISSUE TITLE
Windows 10: Unable to store certificate file under /tmp/localstack/server.test.pem, using tmp file instead: [Errno 13] Permission denied: '/tmp/localstack/server.test.pem'

### ISSUE THREAD

**Issue by AshwinDora** [localstack/localstack#2119]
I am running in windows 10 and i am getting a permission issues as mentioned. Below is the 

> trace.  Also it says its ready and the only service I have is dynamodb and when I try it using the URL - http://localhost:4569/  getting 'Site cannot be reached'

$ docker-compose up
Starting 7fd7bedee329_7fd7bedee329_localstack_main
Attaching to 7fd7bedee329_7fd7bedee329_localstack_main
7fd7bedee329_7fd7bedee329_localstack_main | Waiting for all LocalStack services to be ready
7fd7bedee329_7fd7bedee329_localstack_main | 2020-03-03 01:55:24,263 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
7fd7bedee329_7fd7bedee329_localstack_main | 2020-03-03 01:55:24,266 INFO supervisord started with pid 12
7fd7bedee329_7fd7bedee329_localstack_main | 2020-03-03 01:55:25,269 INFO spawned: 'dashboard' with pid 18
7fd7bedee329_7fd7bedee329_localstack_main | 2020-03-03 01:55:25,270 INFO spawned: 'infra' with pid 19
7fd7bedee329_7fd7bedee329_localstack_main | 2020-03-03 01:55:25,277 INFO success: dashboard entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
7fd7bedee329_7fd7bedee329_localstack_main | (. .venv/bin/activate; bin/localstack web)
7fd7bedee329_7fd7bedee329_localstack_main | (. .venv/bin/activate; exec bin/localstack start --host)
7fd7bedee329_7fd7bedee329_localstack_main | Starting local dev environment. CTRL-C to quit.
7fd7bedee329_7fd7bedee329_localstack_main | 2020-03-03 01:55:26,777 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
7fd7bedee329_7fd7bedee329_localstack_main | Waiting for all LocalStack services to be ready
**7fd7bedee329_7fd7bedee329_localstack_main | 2020-03-03T01:55:31:INFO:localstack.utils.common: Unable to store certificate file under /tmp/localstack/server.test.pem, using tmp file instead: [Errno 13] Permission denied: '/tmp/localstack/server.test.pem'**
7fd7bedee329_7fd7bedee329_localstack_main | Starting mock DynamoDB (http port 4569)...
7fd7bedee329_7fd7bedee329_localstack_main | Ready.

**Comment by AshwinDora** [comment]
My bad. Added the environment variable COMPOSE_CONVERT_WINDOWS_PATHS=1 and it started working as it resolves to that equivalent directory of /tmp

**Comment by whummer** [comment]
Thanks for posting the solution - glad you got it working 👍

**Comment by RSHUKL01** [comment]
@AshwinDora @whummer  I am getting the same error and I also added the variable environment variable COMPOSE_CONVERT_WINDOWS_PATHS=1 but still getting the same error. Can you please help?
