### ISSUE TITLE
Localstack pulls latest docker image

### ISSUE THREAD

**Issue by bitbier** [localstack/localstack#2142]
## Issue
There seems to be a disconnect between the docker image version and the version of localstack. When you run the localstack version, it will attempt to pull the latest version from docker hub instead of the specific version. This means that if you upgrade localstack, you will still be running it at the version it first started at.

Another issue related to this is that the latest version in dockerhub does not work correctly. This issue is related to CF not being able to find the deployment bucket because it was using the real AWS service instead of its local copy or something like that:

```
...
Serverless: [AWS cloudformation 404 0.025s 0 retries] updateStack({ StackName: 'sls-starter-kit-local',
  Capabilities: [ 'CAPABILITY_IAM', 'CAPABILITY_NAMED_IAM', [length]: 2 ],
  Parameters: [ [length]: 0 ],
  TemplateURL: 'https://s3.amazonaws.com/sls-starter-kit-local-ServerlessDeploymentBucket-562GSF2NSK7T/serverless/sls-starter-kit/local/1583799586032-2020-03-10T00:19:46.032Z/compiled-cloudformation-template.json',
  Tags: [ { Key: 'STAGE', Value: 'local' }, [length]: 1 ] })
  Serverless Error ---------------------------------------
  ServerlessError: The specified bucket does not exist
      at promise.catch.err (/Users/jstarker/.nvm/versions/node/v9.11.2/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:329:27)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:182:7)
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              9.11.2
     Framework Version:         1.61.3
     Plugin Version:            3.4.1
     SDK Version:               2.3.0
     Components Core Version:   1.1.2
     Components CLI Version:    1.4.0
```

At the time of this writing, here are the images (the latest version was 0.10.8):

<img width="1273" alt="Screen Shot 2020-03-09 at 6 21 14 PM" src="https://user-images.githubusercontent.com/548132/76270704-5f4da680-6233-11ea-9843-e0ccdc4268e7.png">

## Expected Behavior

`localstack` should check that is running the correct version of the docker image that matches it's version number.

## Background

When localstack is run via docker, it tries to pull the latest version from docker hub because the [`constants.py#DOCKER_IMAGE_NAME`](https://github.com/localstack/localstack/blob/master/localstack/constants.py#L60) only includes `localstack/localstack` and there is no logic to add the version as the tag.

## Workaround

My current workaround is to manually pull the correct version of localstack and tag it as latest so that it uses the correct one:

```
docker pull localstack/localstack:$(localstack --version)
docker tag localstack/localstack:$(localstack --version) localstack/localstack:latest
```

**Comment by whummer** [comment]
Thanks for reporting @bitbier . Can you please try using the `IMAGE_NAME` environment variable to pin LocalStack to a specific version/tag of the Docker image.

A short description has been added to the configuration section of the README:

>  * `IMAGE_NAME`: Specific name and tag of LocalStack Docker image to use, e.g., `localstack/localstack:0.11.0` (default: `localstack/localstack`).

Please report here if there are any issues. Thanks
