### ISSUE TITLE
Not getting ETag for GetObject call

### ISSUE THREAD

**Issue by rajeeshckr** [localstack/localstack#2146]
I have golang code making use of LocalStack for integration test.

As part of our code we expect ETag value to be populated for objects returned from a bucket.
```go
object, err := c.s3.GetObjectWithContext(ctx, &s3.GetObjectInput{
		Bucket: &c.bucket,
		Key:    &key,
		Range:  byteRange,
		//IfMatch: etag, // returns a 412 (precondition failed) if etag doesn't match
	})
	if err != nil {
		err = translateError(err)
		switch err {
		case ErrNotFound:
			return nil, errors.WithMessage(err, fmt.Sprintf("GetObject: object with key=%q not found", key))
		default:
			return nil, errors.WithMessage(err, fmt.Sprintf("GetObject: error retrieving key=%q expectedEtag=%s", key, pp(etag)))
		}
	}
	if object.ETag == nil {
		return nil, errors.Errorf("Object with key=%q had nil ETag", key)
	}
```

Code fails on the object.ETag check. We have another code where we do a HeadObject, that returns the ETag properly for the same Key.

```go
	ho, err := c.s3.HeadObjectWithContext(ctx, &s3.HeadObjectInput{
		Bucket: &c.bucket,
		Key:    &key,
	})
```

Is this a limitation or am I missing something? 
Thanks!

**Comment by whummer** [comment]
Thanks for reporting @rajeeshckr . This should be fixed in #2175 - can you please give it a try with the `latest` version. Please report here if the problem persists. Thanks
