### ISSUE TITLE
Localstack region is always null in getAccepterVpcInfo after vpc peering

### ISSUE THREAD

**Issue by Ghilteras** [localstack/localstack#2147]
Looks like if we create a VPC peering between two different regions using Localstack the region is always `null` when we query the accepter vpc info using the vpc peering id

See my java gist below to reproduce

https://gist.github.com/Ghilteras/e55d83985d9f1e105988f72223250181

**Comment by whummer** [comment]
Thanks for reporting and for providing the gist @Ghilteras . This issue should be fixed in #2668 - can you please give it a try with the `latest` version of the Docker image. Please report here if the problem persists. Thanks
