### ISSUE TITLE
Deploy LocalStack on Heroku

### ISSUE THREAD

**Issue by DariuszWietecha** [localstack/localstack#2155]
Good Morning,

Is it possible to deploy LocalStack on Heroku?
I'm trying this way:
https://devcenter.heroku.com/articles/container-registry-and-runtime#getting-started
and I met such issue:
`
...
Starting mock Secrets Manager (http port 4584)...
Starting mock SES (http port 4579)...
Starting mock SNS (http port 4575)...
Starting mock SQS (http port 4576)...
Starting mock SSM (http port 4583)...
Starting mock STS (http port 4592)...
Starting mock Cloudwatch Events (http port 4587)...
Starting mock StepFunctions (http port 4585)...
Ready.
..........................E..ERROR: Error forwarding request: ('Connection abort
ed.', ConnectionResetError(104, 'Connection reset by peer')) Traceback (most rec
ent call last):
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connectio
npool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connectio
npool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connectio
npool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1322, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 303, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 264, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/adapters
.py", line 439, in send
    resp = conn.urlopen(
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connectio
...`

Thanks in advance for your help.

**Comment by whummer** [comment]
Thanks for reporting @DariuszWietecha . Can you please share some details about your environment setup and the concrete Heroku configuration?

From the output (`..........................E..`) it seems that the Heroku instance is actually executing the integration tests, is that correct?

I'm not too familiar with the Heroku config, specifically whether Heroku allows you to easily start a Docker container within your instance. But if so, then it should be possibly to start an instance from the `localstack/localstack` Docker image. You can take this some inspiration from the docker-compose.yml file in this repository, which contains some of the basic configurations to start directly in Docker (without using the `localstack` CLI).

This question is somewhat off-topic, as this is primarily a bug tracker. But I'm leaving this issue open for a couple of days in case someone has an answer, or if you can find a solution and share it with us here. Thanks
