### ISSUE TITLE
Connection to localstack in jenkins fails with "SocketException : No connection could be made because the target machine actively refused it"

### ISSUE THREAD

**Issue by morlando016** [localstack/localstack#2162]
Ive got some integration tests that require localstack (SNS and SQS) in order to run. I am starting localstack in a docker container and then trying to hit the health check endpoint (http://localhost:8080/health) to ensure the services are up before continuing execution of the test. For some reason, this all works fine on my local machine, but on my jenkins server I am seeing `SocketException : No connection could be made because the target machine actively refused it`. I am not sure why this would be working on my development machine but not in jenkins.

My docker compose looks like this:

```version
services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - '4575:4575'
      - '4576:4576'
      - '8080:8080'
    environment:
      - SERVICES=sns, sqs
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
```

Here is my code where I try to call the health check. I try to connect for a minute before throwing an exception: 

```
Polly.Policy.Handle<Exception>()
			.WaitAndRetry(60, (_, __) => TimeSpan.FromSeconds(1))
			.Execute(() => {
				var healthCheckURL = "http://localhost:8080/health";
				var request = new HttpRequestMessage(HttpMethod.Get,
					healthCheckURL);
					var client = new HttpClient();
					var response = client.SendAsync(request).GetAwaiter().GetResult();
					body = response.Content.ReadAsStringAsync().GetAwaiter().GetResult();
				});
```

I also tried using host networking, but that just broke the tests on my local machine.

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-164) by [Unito](https://www.unito.io/learn-more)

**Comment by whummer** [comment]
Thanks for reporting @morlando016 . Looks like this configuration uses some outdated ports, which are no longer being used. Have you been able to get things running with the default edge port 4566 and the health check endpoint `http://localhost:4566/health`? Please let us know if the problem persists... Thanks!
