### ISSUE TITLE
Unable to invoke lambda via API gateway 

### ISSUE THREAD

**Issue by aragavendran** [localstack/localstack#2167]
I'm writing a small hello_world program in rust and trying to setup a local working environment. I'm using the example from this library. https://github.com/awslabs/aws-lambda-rust-runtime.
I have created scripts(using aws & awslocal) to deploy resources to aws and localstack respectively.
I'm able to create resources and successfully get response on AWS while the local setup(resource creation is successful) using localstack seems to have a problem. when i try to invoke the api gateway it gives me the below error.
```
MB	 Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 392, in run_lambda
    result, log_output = LAMBDA_EXECUTOR.execute(func_arn, func_details,
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 121, in execute
    return do_execute()
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 106, in do_execute
    raise e
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 95, in do_execute
    result, log_output = self._execute(func_arn, func_details, event, context, version)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 246, in _execute
    result, log_output = self.run_lambda_executor(cmd, stdin, environment)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 158, in run_lambda_executor
    raise Exception('Lambda process returned error status code: %s. Result: %s. Output:\n%s' %
Exception: Lambda process returned error status code: 1. Result: {"errorType":"JsonError","errorMessage":"JsonError: data did not match any variant of untagged enum RequestContext at line 1 column 579"}. Output:
```
i use the below link to invoke lambda 
```
http://localhost:4567/restapis/${API_ID}/${STAGE}/_user_request_/${HANDLER}?first_name=world
```

**Comment by aragavendran** [comment]
Hi, could you please let me know if you need any other inputs from my side. I would be more than happy to provide them

**Comment by whummer** [comment]
Thanks for reporting @aragavendran . I'm not too familiar with Lambdas in Rust, but from the error logs you posted, this appears to be an error coming from your Rust program. Can you please provide a complete, isolated example (including Lambda configurations & the Rust handler code) to help reproduce this issue? Thanks

**Comment by whummer** [comment]
Hi @aragavendran - any updates on this issue, have you been able to get it working in the meantime? Would be great if you could provide a small example, so we can reproduce this more easily. Thanks!

**Comment by aragavendran** [comment]
Hi @whummer My apologies for delayed response. We were able to use lambci/lambda:provided for our local setup and kind of using it for now. i will try to re-create this using localstack and report if the issue still exists.
thanks a lot for getting back on this
