### ISSUE TITLE
LocalStack timestamps on S3, SNS, and others not matching AWS timestamps

### ISSUE THREAD

**Issue by wkurkian** [localstack/localstack#2170]
Under utils/common.py, 

TIMESTAMP_FORMAT_MILLIS = '%Y-%m-%dT%H:%M:%S.%fZ'

The %f produces time with microseconds, for example: 2020-03-18T19:43:18.115783Z.

However, when interacting the AWS s3 and sns apis, I receive DateTimes like this:

2020-03-02T22:32:13.240Z
i.e. milliseconds. 

This seems like a simple change to the utils. TIMESTAMP_FORMAT_MILLIS is named as if it should be millis as well. This is seems like a simple change. Is there a reason it should be microseconds?

**Comment by whummer** [comment]
Thanks for reporting @wkurkian . 

> Is there a reason it should be microseconds?

No particular reason, looks like this is a bug that should be fixed. Would you be able to create a small pull request (plus a small test case) to fix this? Thanks, much appreciated!

**Comment by wkurkian** [comment]
I created a PR for this here: https://github.com/localstack/localstack/pull/2180

Let me know if there is anything I did incorrectly as part of creating this PR. I didn't create tests for every place this change affects code. I can add a couple more, but I have to do that a bit later.
