### ISSUE TITLE
S3 /docker-entrypoint-initaws.d volume not created/mounted

### ISSUE THREAD

**Issue by dg-ooda** [localstack/localstack#2171]
Hello,

I am using localstack version 0.10.8 according to my Pipfile.lock file. I am attempting to create a couple of S3 buckets at localstack startup time and this works fine in a local docker environment, my .sh files are found and executed as necessary. All good.

In our CI environment, the docker-entrypoint-initaws.d directory is not found anywhere within the docker container's filesystem.

The following is the service definition in our docker yml file:

localstack:
    image: localstack/localstack
    restart: always
    environment:
      - SERVICES=s3,s3api
      - REGION=us-west-2
      - HOSTNAME_EXTERNAL=localstack
      - FORCE_NONINTERACTIVE
      - DEBUG=1
    networks:
      xyz:
        aliases:
          - localstack
    volumes:
      - "./integration/initaws:/docker-entrypoint-initaws.d"

Is there something missing or incorrect in this definition that would lead to the docker-entrypoint-initaws.d directory from not being found in the filesystem, let alone within the root directory?

Thank you

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-165) by [Unito](https://www.unito.io/learn-more)

**Comment by dg-ooda** [comment]
Ok, I have an update on this topic. In both my working local environment and in our gitlab CI environment (where this fails), upon inspecting the localstack docker container, I see output of the following form:

"HostConfig": {
            "Binds": [
                "/build/integration/initaws:/docker-entrypoint-initaws.d:ro"
            ],

In my local environment, executing into the docker container, I can see the /docker-entrypoint-initaws.d directory, and it has the files from my initaws folder. In our gitlab CI environment, the /docker-entrypoint-initaws.d directory is simply not present.

Could this be due to a problem within localstack, or possibly a permissions problem?

**Comment by shenie** [comment]
Try this
```
volumes:
- "$PWD/integration/initaws:/docker-entrypoint-initaws.d"
```

because relative path in compose yaml assumes current executing dir and it might be diff in CI vs how you started compose service on your laptop.

**Comment by dg-ooda** [comment]
Thanks shenie, I did just give that a try. Same result unfortunately. The configuration of the bind mount looks right, there just is no docker-entrypoint-initaws.d directory in the root directory, nor anywhere in the localstack container's filesystem. I have verified that by executing find / -name docker-entrypoint-initaws.d -type d in the localstack container.

**Comment by shenie** [comment]
`/build/integration/initaws` that's the dir on host on your ci server...

Is `/build` dir really where the repo is checked out into?

Or should it have been `/build/<repo-name>/integration/initaws` ?

**Comment by dg-ooda** [comment]
Sorry, I was simplifying those directory names. Whether that volume bind point was ./integration or $PWD/integration very much looked the same in both environments. The actual directory name in our CI environment was in fact:

/builds/<repo-name>/<repo-name/integration/initaws.

And I could find the .sh file present in that directory. There simply does not exist a /docker-entrypoint-initaws.d  directory within the localstack docker container.

**Comment by leandroandrade87** [comment]
I'm facing the same issue, but in DroneCI.
@dg-ooda did you could resolve your pipeline?

**Comment by vvmoorthy** [comment]
I am having a similar problem. I am trying to run localstack as a kube pod and when I shell into the pod I do not see a /docker-entrypoint-initaws.d directory. I am using localstack/localstack:0.11.2. 

@dg-ooda and @leandroandrade87 any pointers on how you fixed this issue would be helpful.

**Comment by jslota-rt** [comment]
When I build my docker-compose file locally and run it everything is fine, but when I push to git actions it cannot find a csv file that I located in the directory. Its weird because the shell file is found.

I am seeing ``` The user-provided path /docker-entrypoint-initaws.d/ABA_Final.csv does not exist. ```

Wondering if this is related

**Comment by whummer** [comment]
Thanks for reporting @dg-ooda @leandroandrade87 @shenie @jslota-rt . Have you been able to get this resolved in the meantime, or does the problem persist? This seems to be related to a volume mounting issue in certain CI environments - @jslota-rt can you please share the docker-compose file used in your github actions configuration? Thanks!

**Comment by jslota-rt** [comment]
@whummer my issue has been resolved and it works as expected, had a .gitignore on the file I was trying to use, thank you!
