### ISSUE TITLE
No response for localhost with latest version of localstack

### ISSUE THREAD

**Issue by limengze126** [localstack/localstack#2174]
Hi,

I pulled the latest version of localstack/localstack image, and tried to start up the localstack container. However, with localstack container started up successfully, the localhost was not reachable. After docker run localstack, I tried to open pages like http://localhost:4571/ but I got the error: 
This page isn't working localhost didn't send any data.
ERR_EMPTY_RESPONSE

I tried many ports, like 4569 for dynamodb, 4570 for dynamodb stream, etc. However, none of them worked for me. Could somebody please take a look at this?

Thanks a lot!
Best,
Mengze

**Comment by dg-ooda** [comment]
Hi,

Have you tried http://localstack:4571 ?

**Comment by whummer** [comment]
Thanks for reporting @limengze126 . Can you please share the configuration (and environment variables) and the exact command you're using to start LocalStack? Are you using docker-compose or the `localstack` command line interface? In case of docker-compose, are the ports properly exposed to the host system?

**Comment by limengze126** [comment]
Hi @whummer ,

Thanks for your reply! Here are some info:
Container Info-
\u@\H:\w$ docker ps
CONTAINER ID        IMAGE                   COMMAND                  CREATED             STATUS              PORTS                                                                                      NAMES
d669c75dc8a3        localstack/localstack   "docker-entrypoint.sh"   4 minutes ago       Up 4 minutes        0.0.0.0:443->443/tcp, 0.0.0.0:4567-4615->4567-4615/tcp, 0.0.0.0:8080-8081->8080-8081/tcp   localstack_main
Image info-
\u@\H:\w$ docker image ls
REPOSITORY                                            TAG                 IMAGE ID            CREATED             SIZE
localstack/localstack                                 latest              8e3b3c87251e        22 hours ago        937MB
localstack/localstack                                 <none>              8a612c27347a        5 months ago        804MB
localstack/localstack                                 0.9.5               d4960b5805fa        9 months ago        704MB

I used localstack command line to start localstack.

localstack start      
Starting local dev environment. CTRL-C to quit.
docker run -it -e LOCALSTACK_HOSTNAME="localhost" -e TEST_AWS_ACCOUNT_ID="000000000000" -e DEFAULT_REGION="us-east-1" --rm --privileged --name localstack_main -p 8080:8080 -p 8081:8081  -p 443:443 -p 4567-4615:4567-4615  -v "/private/var/folders/vs/lrgk9xnj1dq61211n5j5mb7sg6g1y9/T/localstack:/tmp/localstack" -v "/var/run/docker.sock:/var/run/docker.sock" -e DOCKER_HOST="unix:///var/run/docker.sock" -e HOST_TMP_FOLDER="/private/var/folders/vs/lrgk9xnj1dq61211n5j5mb7sg6g1y9/T/localstack" "localstack/localstack" 
Waiting for all LocalStack services to be ready
2020-03-20 06:44:03,836 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2020-03-20 06:44:03,839 INFO supervisord started with pid 13
2020-03-20 06:44:04,845 INFO spawned: 'dashboard' with pid 19
2020-03-20 06:44:04,848 INFO spawned: 'infra' with pid 20
(. .venv/bin/activate; bin/localstack web)
2020-03-20 06:44:04,855 INFO success: dashboard entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
(. .venv/bin/activate; exec bin/localstack start --host)
Starting local dev environment. CTRL-C to quit.
2020-03-20 06:44:06,425 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Waiting for all LocalStack services to be ready
Waiting for all LocalStack services to be ready
Starting mock API Gateway (http port 4567)...
2020-03-20T06:44:17:INFO:localstack.multiserver: Starting multi API server process on port 51492
Starting mock CloudFormation (http port 4581)...
Starting mock CloudWatch (http port 4582)...
Starting mock DynamoDB (http port 4569)...
Starting mock DynamoDB Streams service (http port 4570)...
Starting mock EC2 (http port 4597)...
Starting mock ES service (http port 4578)...
Starting mock Firehose service (http port 4573)...
Starting mock IAM (http port 4593)...
Starting mock Kinesis (http port 4568)...
Starting mock KMS (http port 4599)...
Starting mock Lambda service (http port 4574)...
Starting mock CloudWatch Logs (http port 4586)...
Starting mock Redshift (http port 4577)...
Starting mock Route53 (http port 4580)...
Starting mock S3 (http port 4572)...
Starting mock Secrets Manager (http port 4584)...
Starting mock SES (http port 4579)...
Starting mock SNS (http port 4575)...
Starting mock SQS (http port 4576)...
Starting mock SSM (http port 4583)...
Starting mock STS (http port 4592)...
Starting mock Cloudwatch Events (http port 4587)...
Starting mock StepFunctions (http port 4585)...
Waiting for all LocalStack services to be ready
Ready.

Then I tried to access http://localhost:4571/, I got - "This page isn’t working localhost didn’t send any data.
ERR_EMPTY_RESPONSE"

Thanks!

**Comment by limengze126** [comment]
Hi @dg-ooda,

Thanks for your reply! It's not working as well.

**Comment by ps-mariotacke** [comment]
First time user; having the same issue. `ERR_EMPTY_RESPONSE`, I'm using the default `docker-compose.yml`. Any idea what could be wrong?

```
version: '2.1'

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack-light
    ports:
      - "4566-4599:4566-4599"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=${SERVICES-s3}
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

**Comment by ghukill** [comment]
Had the same issue as @ps-mariotacke; did not work with `localstack/localstack-light` but did with `localstack/localstack`

**Comment by whummer** [comment]
Thanks for reporting. Please note that the Elasticsearch Service (ES) starts up by default on port `4578`, but actual Elasticsearch instances on port `4571` (domains) are only started up once requested via the `CreateElastichsearchDomain` API - see the CLI docs here: https://docs.aws.amazon.com/cli/latest/reference/es/create-elasticsearch-domain.html .

Note that this is in line with the behavior on AWS - the API call returns an `Endpoint` attribute which contains the endpoint URL (hostname/port) that can be used to access the Elasticsearch cluster once it has started up and becomes available. 

Closing this issue - please report here if there are any other questions or issues. Thanks
