### ISSUE TITLE
API Gateway is missing endpoints for managing domain names

### ISSUE THREAD

**Issue by rldw** [localstack/localstack#2187]
# Type of request: This is a ...

[x] bug report
[] feature request

# Detailed description

Not sure if this is a bug or a missing feature, but API Gateway is missing endpoints for domain names.

## Expected behavior

I can manage API Gateway domain names via AWS CLI or Terraform.

## Actual behavior

Terraform stalls while trying to create the resource; the AWS CLI returns a 404.

# Steps to reproduce

## Command used to start LocalStack

`localstack start`

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

`AWS_ACCESS_KEY_ID=foo AWS_SECRET_ACCESS_KEY=bar aws --endpoint-url=http://localhost:4567 apigateway get-domain-names`

### AWS CLI Response

```
An error occurred (404) when calling the GetDomainNames operation: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.</p>
```

**Comment by rldw** [comment]
After some more digging: seems like moto is missing the required endpoints and the issue is thus related to the upstream moto? 

https://github.com/spulec/moto/blob/master/moto/apigateway/urls.py

**Comment by whummer** [comment]
Thanks for reporting @rldw . A PR has been added in https://github.com/spulec/moto/pull/2878 , this functionality should be included in the `latest` version of the LocalStack Docker image. Please report here if the problem persists. Thanks
