### ISSUE TITLE
debug_docker_java_port is not set when setting port in LAMBDA_JAVA_OPTS

### ISSUE THREAD

**Issue by giangvo** [localstack/localstack#2204]
# Type of request: This is a bug report

# Detailed description
When running a java lambda in localstack with `LAMBDA_EXECUTOR=docker` and  `LAMBDA_JAVA_OPTS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5005"` (replaced `_debug_port_` with `5005`), the port is not opened in the lambda execution docker container.

Looking at `Util.get_java_opts` in `localstack/services/awslambda/lambda_executors.py`, `debug_java_port` is not set in case `_debug_port_` is set

```
class Util:
    debug_java_port = False

    @classmethod
    def get_java_opts(cls):
        opts = config.LAMBDA_JAVA_OPTS or ''
        if '_debug_port_' in opts:
            if not cls.debug_java_port:
                cls.debug_java_port = get_free_tcp_port() ### <<< debug_java_port is only set here
            opts = opts.replace('_debug_port_', ('%s' % cls.debug_java_port))
        ### In other case, `cls.debug_java_port` is not set.
        return opts
```
## Expected behavior

`debug_java_port` should be set to the configured port

## Actual behavior

`debug_java_port` is empty

# Steps to reproduce
docker-compose file
```
version: '2.1'
services:
  localstack:
    container_name: localstack
    image: localstack/localstack
    privileged: true
    ports:
      - "4567-4582:4567-4582"
      - "9070:9070"
    environment:
      SERVICES: sqs,lambda
      DOCKER_HOST: unix:///var/run/docker.sock
      PORT_WEB_UI: 9070
      LAMBDA_EXECUTOR: docker
      LAMBDA_JAVA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5005"
      DEBUG: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/localstack:/tmp/localstack
```

## Command used to start LocalStack

`docker-compose up`

**Comment by giangvo** [comment]
PR created here: https://github.com/localstack/localstack/pull/2205

**Comment by whummer** [comment]
Thanks for reporting and creating the PR 👍
