### ISSUE TITLE
Lambda/Terraform Missing Response Element

### ISSUE THREAD

**Issue by triplejay2013** [localstack/localstack#2208]
# Type of request: This is a ...

[ x ] bug report
[ ] feature request

# Detailed description

I am running terraform against localstack successfully. After the first successful run, the terraform fails with the following message

`Error: error waiting for Lambda Function (...) update: unexpected state '', wanted target 'Successful'. last error: %!s(<
nil>)`      

I did some searching and triaging, and here are some relevant finds:        

1. [similar issue](https://github.com/localstack/localstack/issues/1822) which helped me find more related resources
2. The above issue was [fixed](https://github.com/localstack/localstack/pull/1838/files).
3. AWS [documentation](https://docs.aws.amazon.com/lambda/latest/dg/API_GetFunctionConfiguration.html#API_GetFunctionConfiguration_ResponseSyntax) suggests that there are a lot of ResponseElements that can be returned in a response, one of which (that I care about for now) is 'LastUpdateStatus'       
                                                                                                                   

## Expected behavior

Successive runs with terraform against localstack should not fail

## Actual behavior

Repeated runs with terraform (which deploy lambda resources) fail. 
See Error message above

**Comment by whummer** [comment]
Thanks for reporting - should be fixed in #2209 .
