### ISSUE TITLE
Feature request: autoscaling service support

### ISSUE THREAD

**Issue by yahel2410** [localstack/localstack#2211]
# Type of request: This is a feature request
# Detailed description
AWS autoscaling service is not supported.

# Steps to reproduce
## Command used to start LocalStack
`$ docker-compose up`

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
```
$ awslocal autoscaling describe-auto-scaling-groups
ERROR: Unable to find LocalStack endpoint for service "autoscaling"
```

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-169) by [Unito](https://www.unito.io/learn-more)

**Comment by sdouek** [comment]
We are also looking for autoscaling service support.
Is there any expectation

**Comment by silv-io** [comment]
Hi @yahel2410, @sdouek! AWS Auto Scaling is currently supported in the PRO version of LocalStack ([see the feature coverage for a more fine-grained breakdown](https://docs.localstack.cloud/localstack/coverage/#autoscaling))
