### ISSUE TITLE
Allow configuring the resource graph port

### ISSUE THREAD

**Issue by jafl** [localstack/localstack#2213]
# Type of request: This is a ...

[ ] bug report
[X] feature request

# Detailed description

On https://app.localstack.cloud/resources, I am able to change the port for loading the individual objects, e.g., lambdas, but I am not able to change the port for loading the resource graph.  It seems to be stuck at 8080.  I run something else on 8080, so I had to adjust my localstack to use 8081

**Comment by whummer** [comment]
Thanks for reporting @jafl . The edge path mapping has now been updated in #2915 to load the resource graph via the edge port as well - i.e., `POST https://app.localstack.cloud/graph`. This means that you can now use your port 8080 for other services. Hope that helps - please keep us posted if the problem persists. Thanks
