### ISSUE TITLE
multi region with dynamo db

### ISSUE THREAD

**Issue by synajen** [localstack/localstack#2217]
#2087 Type of request: This is a bug report

# Detailed description
I want to create 3 dynamo db tables in a central region (for example: us-east-1)
and read/write from a lambda in a different region (for example: eu-west-1).
When I create a table in the central region I see it is created in ALL regions.

## Expected behavior
1. In resources move to region us-east-1 and see the dynamo db tables
1. On pressing the table details, see arn with region us-east-1
1. In resources move to region eu-west-1 and do NOTsee the dynamo db tables

## Actual behavior
1. In resources move to region us-east-1 and see the dynamo db tables
1. On pressing the table details, see arn with region us-east-1
1. In resources move to region eu-west-1 and SEE the dynamo db tables
1. On pressing the table details, see arn with region eu-west-1
...

# Steps to reproduce
## Command used to start LocalStack
Localstack using docker compose:

  localstack:
     image: localstack/localstack
     environment:
       LOCALSTACK_API_KEY: ######
       SERVICES: edge,dynamodb:4569,lambda
       DEBUG: 1
     ports:
     - 443:443
     - 4574:4574
     - 4569:4569
     - 8080:8080
     networks:
      - network
     volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"

## steps/commands to reproduce
awslocal dynamodb create-table --endpoint-url "http://localhost:4569" --region "us-east-1" --table-name status --attribute-definitions AttributeName=var,AttributeType=S --key-schema AttributeName=var,KeyType=HASH --provisioned-throughput ReadCapacityUnits=5,WriteCapacityUnits=5

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-170) by [Unito](https://www.unito.io/learn-more)

**Comment by synajen** [comment]
are you handling this issue? when can we expect to have a fix ready?

**Comment by ryanatnexmo** [comment]
+1

**Comment by whummer** [comment]
Thanks for reporting @synajen @ryanatnexmo . This should be fixed in the meantime - multi-region support has recently been added (also in the community version). Can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists. Thanks!
