### ISSUE TITLE
LocalStack version 0.2.1 returning extra bytes in s3 get response

### ISSUE THREAD

**Issue by Rednirus** [localstack/localstack#2221]
Hi,

We are using localstack version 0.1.21 to run unit tests in our project. It was workinig fine until end of 2019. It started showing below error whihle running test cases. 

java.lang.IllegalArgumentException: Unknown port mapping for service. After googling for possible problems, we found below issue

https://github.com/localstack/localstack/issues/1293

As suggested we upgraded to latest version(0.2.1). But now, We are facing another issue. s3 get is returning some extra bytes in get response. It was working before upgrading. We have printed the response and found it prints 86  bytes(chunk signature). Previous version byte size was zero.

Could you please explain if this is bug or I am missing some configuration

LocalstackTestRunner and Localstack are new files with 0.2.1, 0.1.21 had LocalstackDockerTestRunner and LocalstackDocker.

```
@RunWith(LocalstackTestRunner.class)
@LocalstackDockerProperties(randomizePorts = true, services = {"s3"})
public class S3Test{
private static final String BUCKET = "my-test-bucket";
	@Autowired
    @Qualifier("awsS3Client")//it is created with default configuration using s3clientbuilder
    private AmazonS3Client amazonS3Client;
	
	@Before
    public void setUp() throws Exception {
        System.setProperty("aws.client", "localstack");
        System.setProperty("aws.s3.endpoint", Localstack.INSTANCE.getEndpointS3());
		...................
	}
	
	
    @Test
    public void test1() throws IOException, ClassNotFoundException {
        File file = Files.createTempFile("testfile", ".txt").toFile();
        String key = "testkey";
        amazonS3Client.putObject(BUCKET, key, file);
        S3Object value1 = amazonS3Client.getObject(BUCKET, key);
        byte[] bytes = IOUtils.toByteArray(value1.getObjectContent());
        printResults(bytes);
        assertArrayEquals(com.google.common.io.Files.toByteArray(file), bytes);
    }
	
	private void printResults(byte [] arr) throws IOException {
        File file1 = new File("d:\\demo.txt");
        OutputStream os = new FileOutputStream(file1);
        os.write(arr);
        BufferedReader br = new BufferedReader(new FileReader(file1));
        String line = null;
        System.out.println("File contents: ");
        while ((line = br.readLine()) != null) {
            System.out.println(line);
        }
    }
```
	
output on 0.1.21 is empty and test case passes. This is expected because file is empty file was saved in s3.

Output on 0.2.1 :test fails with below assertion error:

```
java.lang.AssertionError: array lengths differed, expected.length=0 actual.length=86
File contents:

0;chunk-signature=00fa94dcf5a419048a6cd61137dfdca2633bcfe528e508a80e98f97d5911a1fe
```

**Comment by whummer** [comment]
Thanks for reporting @Rednirus .

A few points:
* Can you please post the ID/timestamp of the Docker image you're using? For example:
```
$ docker images | grep localstack
localstack/localstack                latest               c6b071c19c68        27 hours ago        933MB
```

In case you're using an older version, can you please try a `docker pull localstack/localstack` and give it another try?

* Please ensure that your S3 client uses path style addressing (see notes in the [README](https://github.com/localstack/localstack#troubleshooting))
* Also, can you please share the contents of your `demo.txt` file?

Thanks

**Comment by whummer** [comment]
Any updates on this issue @Rednirus ? Would be great if you could help us reproduce this issue - potentially it is actually already solved in the `latest` version of the Docker image. Thanks
