### ISSUE TITLE
UnknownOperationException error for the transact-get-items command

### ISSUE THREAD

**Issue by cutsea110** [localstack/localstack#2225]
# Type of request: This is a ...

- [x] bug report?
- [ ] feature request

# Detailed description

Similar to the problem in #1059 , but I can't seem to use TransactGetItems or TransactGetItemsWithContext at hand.

I assume from the above issue that you should be able to use these APIs now, is that correct?
If so, please let me know the solution.

## Actual behavior

```
$ aws --endpoint-url=http://localhost:4569 dynamodb transact-get-items --transact-items file://transact-items.json 

An error occurred (UnknownOperationException) when calling the TransactGetItems operation: An unknown operation was requested.
```

# Steps to reproduce

## Command used to start LocalStack

```
$ docker-compose up
```

And, I succeeded to create-table, put-item, and scan items.

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

```
$ aws --endpoint-url=http://localhost:4569 dynamodb transact-get-items --transact-items file://transact-items.json 
```

**Comment by whummer** [comment]
Thanks for reporting @cutsea110 . Can you please share the contents of your `transact-items.json` file?

Please also do a `docker pull localstack/localstack` to test against `latest`. Looks like this appears to be working in the latest version:
```
$ awslocal dynamodb create-table --table-name customers --attribute-definitions AttributeName=id,AttributeType=S --key-schema AttributeName=id,KeyType=HASH --billing-mode PAY_PER_REQUEST
$ awslocal dynamodb transact-get-items --transact-items Get='{Key={id={S=foo}},TableName=customers}'
{
    "Responses": [
        {}
    ]
}
```

**Comment by whummer** [comment]
Looks like this is fixed in `latest` - please report here if the problem persists. Thanks!
