### ISSUE TITLE
CodeCommit Support

### ISSUE THREAD

**Issue by ebeyer1** [localstack/localstack#2229]
# Type of request: This is a ...
[ ] bug report
[x] feature request

# Detailed description
I use CodeCommit for application data storage. Are there any plans on supporting CodeCommit with LocalStack?

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-171) by [Unito](https://www.unito.io/learn-more)

**Comment by thrau** [comment]
closing this now. localstack pro comes with codecommit support!
