### ISSUE TITLE
serverless deploy with serverless-domain-manager

### ISSUE THREAD

**Issue by xxx87370343** [localstack/localstack#2237]
It seems to be a lack of resources compared to AWS during the deployment of localstack and cause serverless-domain-manager throw error. Is it my mistake or the problem of localstack?

localstack:
![image](https://user-images.githubusercontent.com/38454210/78243061-a880d580-7515-11ea-8c85-d41688156a0a.png)

![image](https://user-images.githubusercontent.com/38454210/78243009-96069c00-7515-11ea-9df0-570119602c62.png)

AWS:
![image](https://user-images.githubusercontent.com/38454210/78243219-f564ac00-7515-11ea-803e-4be52fe37a71.png)

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-172) by [Unito](https://www.unito.io/learn-more)

**Comment by JeremieDemarchez** [comment]
Did you find a solution ?
I think it is related to the LOCALSTACK_HOSTNAME environment variable, but I don't know how to manage that without going in the plugin code ...

**Comment by xxx87370343** [comment]
> Did you find a solution ?
> I think it is related to the LOCALSTACK_HOSTNAME environment variable, but I don't know how to manage that without going in the plugin code ...

sorry about that. though I think I finally pass it and build successfully. but it's too long and I forget how did I resolve it..

**Comment by xxx87370343** [comment]
> Did you find a solution ?
> I think it is related to the LOCALSTACK_HOSTNAME environment variable, but I don't know how to manage that without going in the plugin code ...

I found the doc I write before. And I remove the plugin finally
