### ISSUE TITLE
S3 policy not respected

### ISSUE THREAD

**Issue by lcardito** [localstack/localstack#2238]
# Type of request:
* [x] bug report
* [x] question?

# Detailed description
Hey folks!  Looks like the S3 mock is not respecting the policies I can correctly attach. Given the following policy:

```
aws --endpoint-url=http://localhost:33444 s3api get-bucket-policy --bucket my-super-bucket

{
  "Policy": "{\"Version\": \"2012-10-17\",\"Statement\": [{\"Effect\": \"Deny\",\"Principal\": \"*\",\"Action\": \"s3:*\",\"Resource\": [\"arn:aws:s3:::*\"]}]}"
}
```

## Expected behavior
When I use the CLI to list the bucket I'd expect a 4XX type of response, however..

## Actual behavior
```
aws --endpoint-url=http://localhost:33444 s3api list-objects --bucket my-super-bucket                                                                                                                                                   15:58:27
{
    "Contents": [
        {
            "LastModified": "2020-04-02T13:58:04.257Z", 
            "ETag": "\"67d12b8810ea7dca06fd088492a00689\"", 
            "StorageClass": "STANDARD", 
            "Key": "upload_test.txt", 
            "Owner": {
                "DisplayName": "webfile", 
                "ID": "75aa57f09aa0c8caeab4f8c24e99d10f8e7faeebf76c078efc7c6caea54ba06a"
            }, 
            "Size": 119
        }
    ]
}
```

# Steps to reproduce
## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
I am starting localstack as a container, then creating the bucket using the Java client:

```
    public static LocalStackContainer AWS_LOCAL_STACK = new LocalStackContainer()
            .withServices(S3);

        s3Client = AmazonS3ClientBuilder
            .standard()
            .withEndpointConfiguration(AWS_LOCAL_STACK.getEndpointConfiguration(S3))
            .build();

        s3Client.createBucket("my-super-bucket ");
        s3Client.setBucketPolicy("my-super-bucket ", "{" +
                "  \"Version\": \"2012-10-17\"," +
                "  \"Statement\": [" +
                "    {" +
                "      \"Effect\": \"Deny\"," +
                "      \"Principal\": \"*\"," +
                "      \"Action\": \"s3:*\"," +
                "      \"Resource\": [" +
                "        \"arn:aws:s3:::*\"" +
                "      ]}" +
                "  ]" +
                "}");
```

Any clue if this is expected or perhaps I am doing something wrong?

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-173) by [Unito](https://www.unito.io/learn-more)

**Comment by whummer** [comment]
Thanks for reporting @lcardito . Please note that by default LocalStack does not evaluate or enforce IAM policies (i.e., all requests are allowed, none are denied). If you'd like to give it a try, we have basic support for IAM enforcement in the Pro version (which we're actively extending on an ongoing basis). Hope that helps - thanks!

**Comment by lcardito** [comment]
Gotcha - thanks @whummer !
