### ISSUE TITLE
localstack does not support cloud watch event in serverless.yml?

### ISSUE THREAD

**Issue by xxx87370343** [localstack/localstack#2241]
It can be deployed normally on AWS

![image](https://user-images.githubusercontent.com/38454210/78279329-f1528180-7549-11ea-8aec-ba9620a16609.png)

![image](https://user-images.githubusercontent.com/38454210/78279477-25c63d80-754a-11ea-92bc-313e7950424c.png)

**Comment by whummer** [comment]
Thanks for reporting @xxx87370343 . This should be fixed in #2352 - can you please give it a try with the `latest` version? Please report here if the problem persists. Thanks
