### ISSUE TITLE
elastic search domain only 7.1? 

### ISSUE THREAD

**Issue by xxx87370343** [localstack/localstack#2242]
It seems that --elasticsearch-version is not use.

**Comment by whummer** [comment]
Thanks for reporting @xxx87370343 . Is there a strong use case for using an older version of Elasticsearch?

While technically possible, I'm not sure if there is much value in supporting older versions of Elasticsearch. Given the large size of the ES code, we can definitely not bake different versions into the Docker image, but we could download the ZIP file on the fly if users are requesting an ES version prior to 7.1. Thoughts?

**Comment by xxx87370343** [comment]
> Thanks for reporting @xxx87370343 . Is there a strong use case for using an older version of Elasticsearch?
> 
> While technically possible, I'm not sure if there is much value in supporting older versions of Elasticsearch. Given the large size of the ES code, we can definitely not bake different versions into the Docker image, but we could download the ZIP file on the fly if users are requesting an ES version prior to 7.1. Thoughts?

If I want to use version 6.4 of ES with localstack, how do I do?

**Comment by whummer** [comment]
@xxx87370343 A fix has been pushed in #2264 . Please note that for now we only fixed/patched the API response. The underlying Elasticsearch process is still using version 7.1.

If you happen to rely on a backwards-incompatible feature that is only provided in 6.x but not 7.x, then we would have to try and find a different approach that actually downloads and spins up different versions of Elasticsearch. But maybe the latest change actually fixes your issue. If not, then please report here and we'll reopen this issue.

**Comment by xxx87370343** [comment]
@whummer  If possible, I want to use es 6. X in localstack

**Comment by whummer** [comment]
Hi @xxx87370343 , a change has been added in #2299 . You should now be able to specify the Elasticsearch version, and the corresponding version will be downloaded to a temporary local directory on demand (currently, versions `6.7`, `7.1` and `7.4` are supported, with `7.1` being the default).

A new configuration option `SKIP_INFRA_DOWNLOADS` has been added which can be used to skip downloading additional custom Elasticsearch versions (in this case, only the default version baked into the Docker image will be started, regardless of which version is specified in the API call).

Can you please give it a try with the `latest` version, and please report here if there are any issues. Thanks!
