### ISSUE TITLE
Issue when invoking provisioned Node.js Lambda

### ISSUE THREAD

**Issue by KamuelaFranco** [localstack/localstack#226]
I am sure to set `LAMBDA_EXECUTOR=docker`, so I'm not really sure where to begin isolating this.

```An error occurred (Exception) when calling the Invoke operation: Error executing Lambda function: Unable to find executor for Lambda function "my-handler". Note that non-Python Lambdas require LAMBDA_EXECUTOR=docker Traceback (most recent call last):
  File "/Users/kamuela/Code/localstack/localstack/services/awslambda/lambda_api.py", line 296, in run_lambda
    process.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/kamuela/Code/localstack/localstack/services/awslambda/lambda_api.py", line 292, in do_execute
    result = func(event, context)
  File "/Users/kamuela/Code/localstack/localstack/services/awslambda/lambda_api.py", line 370, in generic_handler
    'Note that non-Python Lambdas require LAMBDA_EXECUTOR=docker') % lambda_name)
Exception: Unable to find executor for Lambda function "my-handler". Note that non-Python Lambdas require LAMBDA_EXECUTOR=docker
```

**Comment by whummer** [comment]
Hi, are you using `docker run ...` to start LocalStack? The problem in that case is that environment variables in your local terminal session are *not* automatically passed into the Docker container.

Therefore, the recommended way of starting LocalStack is using the CLI:
```
pip install localstack
LAMBDA_EXECUTOR=docker localstack start
```
Alternatively, if you want to stick with `docker run ...`, you can use the `-e` flag:
```
docker run -e LAMBDA_EXECUTOR=docker ...
```
Hope that helps.

**Comment by KamuelaFranco** [comment]
Thank you. How do I have the same effect while using `make infra` during active development?

**Comment by whummer** [comment]
No worries, I'm glad it works. `make infra` can directly read the environment variables because it runs the stack (i.e., the Python processes) directly on the local machine, not in Docker.
