### ISSUE TITLE
EC2 DescribeAvailabilityZones missing ZoneId

### ISSUE THREAD

**Issue by CpuID** [localstack/localstack#2263]
[x] bug report
[ ] feature request

# Detailed description

Missing attribute on EC2 `DescribeAvailabilityZones` API calls.

## Expected behavior

```
$ aws ec2 describe-availability-zones --region us-east-1
{
    "AvailabilityZones": [
        {
            "State": "available", 
            "ZoneName": "us-east-1a", 
            "Messages": [], 
            "ZoneId": "use1-az4", 
            "RegionName": "us-east-1"
        }, 
...
...
```

## Actual behavior

```
$ aws --endpoint-url=http://localhost:4566 ec2 describe-availability-zones
{
    "AvailabilityZones": [
        {
            "State": "available", 
            "ZoneName": "us-east-1a", 
            "Messages": [], 
            "RegionName": "us-east-1"
        }, 
...
...
```

# Steps to reproduce

See above.

## Command used to start LocalStack

```
$ docker run -it --rm -e SERVICES=ec2 -p 4566:4566 localstack/localstack:0.11.0
```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

See above, AWS CLI version 1.16.276 (probs not latest, but new enough)

**Comment by whummer** [comment]
Thanks for reporting @CpuID . This should be fixed in #2884 - can you please give it a try with the `latest` version of the Docker image. Please report here if the problem persists. Thanks
