### ISSUE TITLE
Recommended way to use outputs from Localstack with docker-compose in tests

### ISSUE THREAD

**Issue by staklau** [localstack/localstack#2265]
Let's say I want to use Localstack to spin up some resources in my CI/CD pipeline with `docker-compose` for testing my Java-application, and these resources will be used when I run my tests with `mvn clean package`. I spin up a Cognito User Pool, and need the ID of the pool for my tests. Specifically, my code looks like this:

> docker-compose.yml

```
version: '3.7'

services:
  localstack:
    container_name: "${kotlin-baseline}"
    build:
      context: .
      dockerfile: Dockerfile.localstack
    ports:
      - "9080:8080"
    environment:
      - SERVICES=cognito
      - LOCALSTACK_API_KEY=<OMITTED>
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEFAULT_REGION=eu-west-1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./src/test/resources/aws-local.sh:/docker-entrypoint-initaws.d/init.sh"
```

> Dockerfile.localstack

```
FROM localstack/localstack:latest
RUN apk add jq
```

> aws-local.sh

```
CREATE_USER_POOL_OUTPUT=$(awslocal cognito-idp create-user-pool --pool-name my_user_pool)
echo $CREATE_USER_POOL_OUTPUT | jq '.'
USER_POOL_ID=$(echo $CREATE_USER_POOL_OUTPUT | jq -r '.UserPool.Id')

CREATE_USER_POOL_CLIENT_OUTPUT=$(awslocal cognito-idp create-user-pool-client --user-pool-id $USER_POOL_ID --client-name my_user_pool_client)
echo $CREATE_USER_POOL_CLIENT_OUTPUT | jq '.'
```
Now, how would I go about using `USER_POOL_ID` in my tests? Do I need to "manually" install Localstack in the docker-container I'm running my tests in, instead of using `docker-compose`?

**Comment by dzhus** [comment]
`awslocal` won't be useful in the container you run the tests in, you should just share `my_user_pool` between aws container and your test container (via an environment variable, possibly specifying the same [env_file](https://docs.docker.com/compose/compose-file/#env_file) for both containers), then fetch the USER_POOL_ID using awscli or AWS API in the test container, using `http://localstack:...` as an endpoint. The test container will need a [`links: [localstack]`](https://docs.docker.com/compose/compose-file/#links) section in the docker-compose to be able to connect to localstack container.

**Comment by whummer** [comment]
Thanks for asking this questions about using the LocalStack container with initialized resources in your tests @staklau , and thanks @dzhus for providing an answer.

As @dzhus mentioned, there are different ways of passing the user pool ID to your tests. In fact, the other option would be to create the user pool directly in a setup method directly in your tests. Your test code would use the AWS SDK (depending on which language you're using, e.g., the Java AWS SDK, Golang AWS SDK, ...), and the SDK would be configured to use the API endpoints on the local host. Some examples of tests using the Java AWS SDK can be found here, for instance: https://github.com/localstack/localstack-java-utils/tree/master/src/test/java/cloud/localstack

Hope that helps. If you can provide some more details about how your tests are implemented specifically, we'll be happy to look into it and provide a more detailed answer. Thanks!
