### ISSUE TITLE
Displaying the version details in the logs

### ISSUE THREAD

**Issue by rmsmani** [localstack/localstack#2268]
# Type of request: This is a ...

[ ] bug report
[X ] feature request

# Detailed description
Am running the localstack using docker-compose up and the logs are being printed at console

Its good to have the below features in the logs while start-up (which is useful for debugging purpose).

1. Display the localstack version number
2. Display the docker container id.

...

## Expected behavior

...

## Actual behavior

...

# Steps to reproduce

## Command used to start LocalStack

...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

...

**Comment by rmsmani** [comment]
@whummer 
I can fix it if you give some startup on this....

**Comment by whummer** [comment]
Thanks, fixed in #2282
