### ISSUE TITLE
localstack ignores context handling attribute

### ISSUE THREAD

**Issue by sbelodon** [localstack/localstack#2273]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

localstack ignores context handling attribute

image: localstack/localstack:0.11.0
Terraform v0.12.24
terraform-provider-aws_v2.55.0_x4

## Expected behavior

 "content_handling" is not empty  in terraform.tfstate and content-type in lambda is correct

## Actual behavior

what i see in terraform.tfstate for both integration & response is
 "content_handling": "",

when requests comes to lambda it has application/octet-stream content-type.post request has application/json content-type

# Steps to reproduce

part of terraform script:
resource "aws_api_gateway_integration" "integration" {
  rest_api_id = aws_api_gateway_rest_api.api.id
  resource_id = aws_api_gateway_resource.resource.id
  http_method = aws_api_gateway_method.method.http_method
  integration_http_method = "POST"
  type = "AWS_PROXY"
  uri = aws_lambda_function.rest-lambda-handler.invoke_arn
  content_handling = "CONVERT_TO_TEXT"

  request_parameters = {
    "integration.request.path.proxy" = "method.request.path.proxy"
  }
}
resource "aws_api_gateway_integration_response" "integration_rsponse" {
  depends_on = [aws_api_gateway_integration.integration]
  rest_api_id = aws_api_gateway_rest_api.api.id
  resource_id = aws_api_gateway_resource.resource.id
  http_method = aws_api_gateway_method.method.http_method
  content_handling = "CONVERT_TO_BINARY"
  status_code = "200"

}

**Comment by whummer** [comment]
Thanks for reporting @sbelodon . This should be fixed upstream in https://github.com/spulec/moto/pull/3058 - can you please give it a try with the `latest` version of the Docker image? Please report here if the problem persists. Thanks
