### ISSUE TITLE
[IAM] AmazonIdentityManagement with null message is thrown instead of EntityAlreadyExistsException

### ISSUE THREAD

**Issue by Ghilteras** [localstack/localstack#2287]
# Type of request: This is a ...
[X] bug report

# Detailed description
`EntityAlreadyExistsException` is not thrown correctly when creating IAM objects that are already present. `AmazonIdentityManagementException` with a null message is thrown instead

## Expected behavior
Localstack should throw `EntityAlreadyExistsException` with a populated message (not null)

## Actual behavior
```
com.amazonaws.services.identitymanagement.model.AmazonIdentityManagementException: null (Service: AmazonIdentityManagement; Status Code: 409; Error Code: 409 Conflict; Request ID: null)
```
# Steps to reproduce
create an IAM role
try to re-create it, catch `EntityAlreadyExistsException` but `AmazonIdentityManagementException` with null message is thrown instead
## Command used to start LocalStack
docker-compose up with 0.11.0

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
https://gist.github.com/Ghilteras/a501b7aa17ae93cfca83aac4be91ceed

**Comment by Ghilteras** [comment]
this is a clone of https://github.com/localstack/localstack/issues/2231 that was imho closed by mistake

**Comment by whummer** [comment]
@Ghilteras Thanks for re-posting this issue. We'll close this one, and reopen #2231 . 👍
