### ISSUE TITLE
Content-MD5 headers on GET / HEAD requests to S3 cause 502 errors

### ISSUE THREAD

**Issue by top-quark** [localstack/localstack#2290]
# Type of request: This is a ...

[ X ] bug report
[ ] feature request

If you make a GET request to S3 with a Content-MD5 header, s3_listener.py will throw. This is due to passing a regex over None in strip_chunk_signatures:

While I agree that including Content-MD5 in a request that has no content is a daft thing to do, this appears to be a misfeature of the minio Java library and causes interoperation errors with localstack.

...

## Expected behavior
200 response (or 4xx error response as appropriate)
...

## Actual behavior
502 Bad Gateway error
...

# Steps to reproduce
`$ curl -H 'Content-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==' http://localstack:4572/path/to/object`

## Command used to start LocalStack

...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

...

**Comment by whummer** [comment]
Thanks for reporting @top-quark . This should be fixed in #2356 - can you please give it a try with the `latest` version? Please report here if the problem persists. Thanks
