### ISSUE TITLE
make install not working (MacOS Mojave, Python 3.7)

### ISSUE THREAD

**Issue by mcintyre94** [localstack/localstack#2297]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

Trying to run `make install` after cloning the repo, I get:

```bash
$ make install
make setup-venv && \
		(test ! -e requirements.txt || (. .venv/bin/activate; pip -q install -r requirements.txt && \
			PYTHONPATH=. exec python localstack/services/install.py testlibs)) || exit 1
(test `which virtualenv` || pip install --user virtualenv) && \
		(test -e .venv || virtualenv  .venv)
Using base prefix '/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7'
New python executable in /Users/callum/scratch/localstack/.venv/bin/python3.7
Also creating executable in /Users/callum/scratch/localstack/.venv/bin/python
Installing setuptools, pip, wheel...done.
ERROR: moto-ext 1.3.15.12 has requirement mock<=3.0.5, but you'll have mock 4.0.2 which is incompatible.
Done.
```

`virtualenv --version`: 16.0.0

`/Users/callum/scratch/localstack/.venv/bin/python --version`: Python 3.7.6

Given that dependencies are being installed into a virtualenv, I'm not sure what could be causing this issue for me locally. Has anyone seen this before?

Edit: Running `docker build .` in the repo, when it gets to `make install` I see the same error but it's able to continue. Should I just not be running `make install` locally outside of docker?

**Comment by whummer** [comment]
Thanks for reporting @mcintyre94 . I think you can safely ignore this error/warning. Also, please note that `make install` is usually only used for development mode, i.e., if you want to develop new features for LocalStack. For regular usage, we recommend running LocalStack in Docker via:
```
$ pip install localstack
$ localstack start
```
We'll try to clean up our dependencies to avoid this error/warning in the future. Closing this issue, but please do let us know if you're experiencing any errors or faulty behavior. Thanks!
