### ISSUE TITLE
CloudWatch get-metric-data throws 500

### ISSUE THREAD

**Issue by jskrnbindra** [localstack/localstack#2300]
CloudWatch get-metric-data throws 500

[-] bug report
[ ] feature request

# Detailed description
get-metric-data breaks by returning SERVER_ERROR using the aws cli

## Expected behavior
get-metric-data must return the requested metric 

## Actual behavior
the request fails with 
```
Unable to parse response (syntax error: line 1, column 54), invalid XML received:
b'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">\n<title>500 Internal Server Error</title>\n<h1>Internal Server Error</h1>\n<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>\n'
```

# Steps to reproduce
1. Put metric
2. Create get metric query file (inf.json)
3. Get Metric

## Command used to start LocalStack
`docker run -d -e SERVICES=cloudwatch -p 4582:4582 localstack/localstack`

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
- `aws cloudwatch --endpoint-url=http://localhost:4582 put-metric-data --namespace some/thing --metric-name someMetric --value 23`
- `echo '[{"Id":"some","MetricStat":{"Metric":{"Namespace":"some/thing","MetricName":"someMetric"},"Period":100,"Stat":"Sum"}}]' > inf.json`
- `aws cloudwatch --endpoint-url=http://localhost:4582 get-metric-data --metric-data-queries file://inf.json --start-time 07:32:34 --end-time 09:30:00`

**Comment by whummer** [comment]
Thanks for reporting @jskrnbindra. This has been fixed upstream and should be available in the `latest` version of the LocalStack Docker image. Please report here if the problem persists. Thanks!
