### ISSUE TITLE
Cloudformation IAM role requires RoleName

### ISSUE THREAD

**Issue by mcintyre94** [localstack/localstack#2303]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

`RoleName` is an optional parameter in `AWS::IAM::Role` resources: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-role.html#cfn-iam-role-rolename

But in localstack attempting to add a role without a RoleName fails because of a KeyError - it's read here: https://github.com/localstack/localstack/blob/master/localstack/services/cloudformation/cloudformation_starter.py#L563

Based on the AWS docs saying "If you don't specify a name, AWS CloudFormation generates a unique physical ID and uses that ID for the role name.", it'd probably be fine to just generate  a GUID when RoleName is missing - but localstack shouldn't fail to create the stack because of this.

## Expected behavior

Able to deploy to localstack cloudformation a role without `RoleName`

## Actual behavior

The deploy fails, with the root cause being a KeyError reading RoleName from the resource properties

# Steps to reproduce

## Command used to start LocalStack

`localstack start`

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

Save as template.yaml:

```
AWSTemplateFormatVersion: 2010-09-09
Resources:
  IamRoleLambdaExecution:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument: {}
```

`aws --endpoint-url http://localhost:4566 cloudformation create-stack --stack-name temp --template-body file://template.yaml --capabilities CAPABILITY_IAM`

**Comment by whummer** [comment]
Thanks for reporting @mcintyre94 . Should be fixed in #2309 - thanks again for the initial version of the PR. 👍
