### ISSUE TITLE
Windows Malformed Path in Volume Mounting Lambdas

### ISSUE THREAD

**Issue by benleim** [localstack/localstack#2305]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description
When executing a lambda with code mounted set as true, the path on Windows for volume mounting is malformed. The path does not conform to Docker's expectations for absolute path.

...

## Expected behavior
The path should conform to Docker's expectations. If it is an absolute path, it needs to begin with '/' and not include a ':' (which localstack may be misinterpreting because a colon is used as a delimiter).
...

## Actual behavior
For example, when a lambda is invoked and localstack runs the `docker create` command, it passes a `-v` flag to mount the volume when `mountCode: true` in the `.serverless` file. The volume flag that is set `-v "C:\Users\BenLeimberger\Documents\pmg.common.template.dockerproj":/var/task` is invalid because it is an absolute path and doesn't begin with '/'. Furthermore, I believe the path cannot have a ':'. It also seems from my testing that the forward slashes should be backward slashes.
...

# Steps to reproduce
- Use a Windows OS
- Create a basic `.serverless` file with some test function
- In the custom section of your `.serverless` file add the following yaml
```yaml
localstack:
        lambda:
            mountCode: true
```
- Run the localstack container (I'm on `0.11.0`)
- My lambda environment variables for the localstack service described in my `docker-compose.yml` file is as follows:
```yaml
LAMBDA_DOCKER_NETWORK: pmgcommontemplatedockerproj_lsnet
LAMBDA_EXECUTOR: docker-reuse
LAMBDA_REMOTE_DOCKER: "0"
```
My inclination is that `LAMBDA_EXECUTOR` and `LAMBDA_REMOTE_DOCKER` are both necessary but `LAMBDA_DOCKER_NETWORK` probably is not.

## Command used to start LocalStack
- `docker-compose up`
- Deploy a serverless function to localstack (just deploy locally)
...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
This is the command local stack is trying to run:
```console
docker create --rm --name "localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_ServiceName-local-hello" --entrypoint /bin/bash -v "C:\Users\BenLeimberger\Documents\pmg.common.template.dockerproj":/var/task --interactive -e AWS_LAMBDA_EVENT_BODY="$AWS_LAMBDA_EVENT_BODY" -e HOSTNAME="$HOSTNAME" -e LOCALSTACK_HOSTNAME="$LOCALSTACK_HOSTNAME"  -e stage=local -e connectionParameterName=DB-CONNECTION-OBJ -e AWS_LAMBDA_EVENT_BODY='{}' -e HOSTNAME=192.168.65.2 -e LOCALSTACK_HOSTNAME=192.168.65.2 -e _HANDLER=api/ServiceName/handler.PathName -e AWS_LAMBDA_FUNCTION_TIMEOUT=28 -e AWS_LAMBDA_FUNCTION_NAME=ServiceName-local-hello -e AWS_LAMBDA_FUNCTION_VERSION='$LATEST' -e AWS_LAMBDA_FUNCTION_INVOKED_ARN=arn:aws:lambda:us-east-1:000000000000:function:ServiceName-local-hello -e NODE_TLS_REJECT_UNAUTHORIZED=0 -e _LAMBDA_SERVER_PORT=5004  --network="pmgcommontemplatedockerproj_lsnet" "localstack/lambda:nodejs12.x"
```
It fails and returns `Error response from daemon: invalid mode: /var/task`. 
Once I change 
`-v "C:\Users\BenLeimberger\Documents\pmg.common.template.dockerproj":/var/task`
to 
`-v "/C/Users/BenLeimberger/Documents/pmg.common.template.dockerproj":/var/task` the container is created & doesn't error out.

...

**Comment by dstasiuk** [comment]
Hi guys. 
I got a similar issue.
How did you fix this? (сс: @benleim @olleolleolle @JackDanger)
thanks.

**Comment by dstasiuk** [comment]
![image](https://user-images.githubusercontent.com/12288518/88487997-e6a57780-cf92-11ea-835d-bed4b593202c.png)
![image](https://user-images.githubusercontent.com/12288518/88488023-1eacba80-cf93-11ea-8560-ce522f5b6afc.png)

**Comment by benleim** [comment]
@dstasiuk could you explain your issue / setup a bit more? The PR I opened solved my issue.

**Comment by dstasiuk** [comment]
@benleim Yes, sure.
My docker-compose file you can see above and I can't run lambda.
For now, I can't see your changes in the current version of the code.
I can fix this issue if change manual **lambda_cwd_on_host** in prepare_execution method from **D:\test1** to **/d/test1** as you did in this PR.

![image](https://user-images.githubusercontent.com/12288518/88701701-0d8ab780-d113-11ea-9538-750a4a074f96.png)
