### ISSUE TITLE
Refactoring potential tasks

### ISSUE THREAD

**Issue by rmsmani** [localstack/localstack#2307]
# Type of request: This is a ...

[ ] bug report
[X ] feature request

# Detailed description
Planning to refactoring the potential tasks for future release
...

## Expected behavior

...

## Actual behavior

...

# Steps to reproduce

## Command used to start LocalStack

...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

...

**Comment by rmsmani** [comment]
@whummer ... 
Information reqd to start working with this

**Comment by whummer** [comment]
@rmsmani Thanks for your help. I'll close this issue, as I think it probably makes more sense to create specific issues with proposals for refactorings. One thing that could definitely help us would be to create additional tests to increase the test coverage. If you could help us add additional tests, that would be highly appreciated! Thanks

**Comment by rmsmani** [comment]
Yeah sure
Will start including the new tc
