### ISSUE TITLE
Calling ACM list certificate returns error 

### ISSUE THREAD

**Issue by malathit** [localstack/localstack#2320]
# Type of request: This is a feature request

# Detailed description
Acm list certificates command returns the error
`ERROR: Unable to find LocalStack endpoint for service "acm"`

The logs show the following:
`2020-04-19T11:38:14:INFO:localstack.services.edge: Unable to find forwarding rule for host "localstack:4566", path "/", target header "CertificateManager.ListCertificates", auth header "AWS4-HMAC-SHA256 Credential=ASIA8NWMTLYQMOS08PHP/20200419/us-east-1/acm/aws4_request, SignedHeaders=amz-sdk-invocation-id;amz-sdk-retry;content-length;content-type;host;x-amz-date;x-amz-security-token;x-amz-target, Signature=3301067fd0c80bd1087e19cbae5bdc74a95fc95f7bf2578d8d95867fc8f67d21"`

## Expected behavior

...

## Actual behavior

...

# Steps to reproduce
Running the awslocal command inside localstack container, 
`awslocal acm list-certificates`

## Command used to start LocalStack

docker run localstack:latest -e SERVICES=sqs,sts,ec2,iam,secretsmanager,acm

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

...

**Comment by whummer** [comment]
Thanks for reporting @malathit . Initial support for ACM has been added in #2770 - can you please do a `docker pull localstack/localstack` and give it a try with the `latest` version of the Docker image? Please report here if the problem persists. Thanks
