### ISSUE TITLE
Latest docker image: generic_proxy: Error forwarding request: the JSON object must be str, bytes or bytearray, not NoneType

### ISSUE THREAD

**Issue by hanglili** [localstack/localstack#2321]
Hi, I have updated my LocalStack docker image today and I am getting into the following error:
ERROR:localstack.services.generic_proxy: Error forwarding request: the JSON object must be str, bytes or bytearray, not NoneType Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 246, in forward
    listener_result = listener.forward_request(method=method,
  File "/opt/code/localstack/localstack/services/dynamodb/dynamodb_listener.py", line 51, in forward_request
    data = json.loads(to_str(data))
  File "/usr/lib/python3.8/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType

Sometimes the error appears just right after starting LocalStack and sometimes, it appears when I am running the program. The program I am trying to run works fine and localstack does behave correctly, but it just that keep getting that error messages is annoying, so far it hasn't seem to affect the execution of my program and the services of localstack that it is using (it also uses DynamoDB).

## Command used to start LocalStack
TMPDIR=/private$TMPDIR SERVICES=serverless LAMBDA_EXECUTOR=docker LAMBDA_REMOVE_CONTAINERS=false DOCKER_HOST=unix:///var/run/docker.sock  DEBUG=1 localstack start --docker

**Comment by whummer** [comment]
Thanks for reporting @hanglili - this should be fixed in #2390. Can you please give it a try with the `latest` version? Please report here if the problem persists. Thanks
