### ISSUE TITLE
Cannot connect to endpoint URL 4573 Firehose

### ISSUE THREAD

**Issue by lucre5** [localstack/localstack#2331]
Hello, I am trying to test sending data from a CSV to S3 through Firehose with localstack. However, I am having troubles connecting to the endpoint URL for firehose.

The data from the CSV file should be channeled to a previously created S3 demo bucket through firehose.

I keep on getting this error:
 EndpointConnectionError: Could not connect to the endpoint URL: "https://firehose.http://localhost:4573.amazonaws.com". 
...

# Steps to reproduce
The docker-compose.yaml file is as follows:

```
version: '3.2'
services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack_demo
    ports:
      - '4563-4599:4563-4599'
      - '8055:8080'
    environment:
      - SERVICES=s3,firehose,iam
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - AWS_DEFAULT_REGION=eu-west-1
    volumes:
      - './.localstack:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
```

## Client code 
Here is how I started the Firehose delivery stream:

`aws --endpoint-url=http://localhost:4573 firehose create-delivery-stream --cli-input-json file://$PWD/firehose_skeleton.json `

And here is the firehose-skeleton.json file
<img width="436" alt="Screenshot 2020-04-21 at 18 02 26" src="https://user-images.githubusercontent.com/54433974/79892305-44f21580-83fa-11ea-8e2c-93440e3bb10d.png">

I am new to both localstack and docker, so I am struggling with finding a solution. The Firehose stream functions correctly when uploading sample data written directly in Python, but it struggles with data from CSV. Is there any issue with my yaml file or something related to how Firehose was initialised? Thank you for any help!
...

**Comment by whummer** [comment]
Thanks for reporting @lucre5 . Can you please do a `docker pull localstack/localstack` and give it another try with the latest version?

This is what I'm seeing with the latest version, using the same configuration that you prodived:
```
$ cat firehose_skeleton.json 
{
  "DeliveryStreamName": "s3-stream",
  "DeliveryStreamType": " DirectPut",
  "S3DestinationConfiguration": {
    "RoleARN": "arn:aws:iam::000000000000:role/super-role" ,
    "BucketARN": "arn:aws:s3:::demo-bucket",
    "Prefix": "test-log",
    "ErrorOutputPrefix": "test-error-log",
    "CompressionFormat": "UNCOMPRESSED",
    "CloudWatchLoggingOptions": {
      "Enabled": false
    }
  },
  "Tags": [{
    "Key": "tagKey",
    "Value": "tagValue"
  }]
}
$ awslocal firehose create-delivery-stream --cli-input-json file://$PWD/firehose_skeleton.json
{
    "DeliveryStreamARN": "arn:aws:firehose:eu-west-1:000000000000:deliverystream/s3-stream"
}
$ awslocal s3 mb s3://demo-bucket
$ awslocal firehose put-record --delivery-stream-name s3-stream --record 'Data=foobar'
{
    "RecordId": "0fc586c2-58eb-4adb-a324-c6bce9abb3cf"
}
$ awslocal s3 ls s3://demo-bucket/test-log/2020/05/10/14/
2020-05-10 16:56:02          6 s3-stream-2020-05-10-14-56-02-feac0c74-5875-4a27-97cb-94b716e3d866
```

Hope that helps to get it working on your end. If the problem persists, then please provide an isolated example (e.g., sequence of `awslocal`) commands to help reproduce this issue. Thanks!
