### ISSUE TITLE
[Bug Report] Windows

### ISSUE THREAD

**Issue by uDivy** [localstack/localstack#2342]
# Type of request: This is a ...

[ Error in starting the localstack ] bug report
[ ] feature request

# Detailed description
I am using latest src code { version:0.11.0 } on my **windows system** and starting the localstack using "docker-compose up" but getting following error logs:

=====
 2020-04-23T04:03:47:ERROR:localstack.services.generic_proxy: Error forwarding request: the JSON object must be str, bytes or bytearray, not NoneType Traceback (most recent call last):
localstack_main |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 246, in forward
localstack_main |     listener_result = listener.forward_request(method=method,
localstack_main |   File "/opt/code/localstack/localstack/services/dynamodb/dynamodb_listener.py", line 51, in forward_request
localstack_main |     data = json.loads(to_str(data))
localstack_main |   File "/usr/lib/python3.8/json/__init__.py", line 341, in loads
localstack_main |     raise TypeError(f'the JSON object must be str, bytes or bytearray, '
localstack_main | TypeError: the JSON object must be str, bytes or bytearray, not NoneType
localstack_main |
localstack_main | 2020-04-23T04:03:47:ERROR:localstack.services.generic_proxy: Error forwarding request: the JSON object must be str, bytes or bytearray, not NoneType Traceback (most recent call last):
localstack_main |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 246, in forward
localstack_main |     listener_result = listener.forward_request(method=method,
localstack_main |   File "/opt/code/localstack/localstack/services/dynamodb/dynamodb_listener.py", line 51, in forward_request
localstack_main |     data = json.loads(to_str(data))
localstack_main |   File "/usr/lib/python3.8/json/__init__.py", line 341, in loads
localstack_main |     raise TypeError(f'the JSON object must be str, bytes or bytearray, '
localstack_main | TypeError: the JSON object must be str, bytes or bytearray, not NoneType
=====

## Expected behavior

Able to access "http://localhost:4567/"

## Actual behavior

Getting 404 while accessing

# Steps to reproduce

Download and unzip the zipped src code latest localstack release {version 0.11.0}
Start the docker desktop
cd into the folder of the src code
run docker-compose up

## Command used to start LocalStack
docker-compose up
...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

...

**Comment by uDivy** [comment]
Hello Team.

The above issue is removed by adding SERVICES in docker-compose.yml file but whenever I am choosing ec2 service ; 
2020-04-23 05:25:17,397:API: 127.0.0.1 - - [23/Apr/2020 05:25:17] "HEAD / HTTP/1.1" 404 -

2020-04-23 05:25:17,688:API: 127.0.0.1 - - [23/Apr/2020 05:25:17] "HEAD / HTTP/1.1" 404 -

 I am getting 404.

Can anyone help me and provide the right way to connect to ec2 and deploy my code on ec2?

**Comment by whummer** [comment]
Thanks for reporting @uDivy , and for confirming that it works by setting the `SERVICES` variable. Please note that the EC2 API is not fully supported in LocalStack open source - hence, "deploy my code on ec2" (i.e., running a VM that executes your code) is not something that will be supported in the short term. We'll mark it as a feature request in our backlog for now. Thanks!

**Comment by uDivy** [comment]
Thank you 
@whummer for the support
