### ISSUE TITLE
[secretsmanager] Description is not persisted when creating secret

### ISSUE THREAD

**Issue by lukaszpierog** [localstack/localstack#2347]
# Type of request: This is a bug report

# Detailed description
When creating a new secret in secrets manager and providing the description, description cannot be later retrieved using list secrets operation

## Expected behavior
Proper description visible when listing secrets

## Actual behavior
Description is empty

# Steps to reproduce
Starting with an empty workspace
```
lpierog-mbp5:Desktop lpierog$ aws --endpoint-url=http://localhost:4566 secretsmanager list-secrets
{
    "SecretList": []
}
```
Create a secret with description
```
lpierog-mbp5:Desktop lpierog$ aws --endpoint-url=http://localhost:4566 secretsmanager create-secret --name test1 --secret-string {} --description "Some description"
{
    "ARN": "arn:aws:secretsmanager:us-east-2:1234567890:secret:test1-ltOSL",
    "Name": "test1",
    "VersionId": "dbd46bf9-fbe9-4255-a033-0ea13d34ab7f"
}
```
Then try to retrieve it and notice, that the description is empty
```
lpierog-mbp5:Desktop lpierog$ aws --endpoint-url=http://localhost:4566 secretsmanager list-secrets
{
    "SecretList": [
        {
            "ARN": "arn:aws:secretsmanager:us-east-2:1234567890:secret:test1-ltOSL",
            "Name": "test1",
            "Description": "",
            "KmsKeyId": "",
            "RotationEnabled": false,
            "RotationLambdaARN": "",
            "RotationRules": {
                "AutomaticallyAfterDays": 0
            },
            "Tags": [],
            "SecretVersionsToStages": {
                "dbd46bf9-fbe9-4255-a033-0ea13d34ab7f": [
                    "AWSCURRENT"
                ]
            }
        }
    ]
}
```

## Command used to start LocalStack
localstack start

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
```
awslocal secretsmanager create-secret --name test1 --secret-string {} --description "Some description"
awslocal secretsmanager list-secrets
```

**Comment by whummer** [comment]
Thanks for reporting @lukaszpierog , and thanks for fixing this issue upstream in `moto`. This should have been merged into LocalStack `latest` in the meantime - please report here if the problem persists. Thanks!
