### ISSUE TITLE
DynamoDB TTL not implemented

### ISSUE THREAD

**Issue by justinian336** [localstack/localstack#236]
I'm trying to use the recent time-to-live feature in DynamoDB, but I get a `An unknown operation was requested` exception. My guess is that the feature is not yet implemented in Localstack. Are there any plans for including it?

**Comment by whummer** [comment]
Thanks for reporting @justinian336 , this would indeed be a useful feature. Would you be able to work on a pull request? I'd be happy to provide the general direction, and help out where needed. Thanks

**Comment by justinian336** [comment]
Sure, I'd be glad to help. I'll study your code and make a PR when I'm ready. Do you have any guidelines for contributors?

**Comment by whummer** [comment]
Awesome. Please refer to the README for some basic guidelines: https://github.com/localstack/localstack#contributing
A few notes have been added to the developer docs, but this is currently only a skeleton (work in progress): https://github.com/localstack/localstack/tree/master/doc/developer_guides

Generally, `ProxyListenerDynamoDB.return_response` in [dynamodb_listener.py](https://github.com/localstack/localstack/blob/master/localstack/services/dynamodb/dynamodb_listener.py#L32) would be a good starting point. We can keep a list of TTL timestamps there, and clean up documents when needed.

**Comment by justinian336** [comment]
@whummer Got it, I'll try and let you know if I find some trouble.

**Comment by vincent6767** [comment]
Any updates here?

**Comment by whummer** [comment]
Initial support for TTL added in #599

**Comment by brainoutsource** [comment]
@whummer could you please clarify, is fully-functional DynamoDB TTL support done or it's just a mock to avoid getting errors on setting TTL settings? Thank you!

**Comment by whummer** [comment]
Thanks for the follow-up @brainoutsource . We still have this line in the listener code, so as of now the TTL response is simply mocked, without actually removing the items.
https://github.com/localstack/localstack/blob/8729ea45f56c9b61990db187dc0c4c73bb3b5416/localstack/services/dynamodb/dynamodb_listener.py#L119

I guess it shouldn't be too hard to add that functionality, though (check for expiry when a Scan/GetItem operation occurs, and then delete any pending expired items). Do you think you could try to contribute a pull request to add that feature? That would be much appreciated, thanks!

**Comment by Isanderthul** [comment]
I see that the current master is still lacking an implementation, maybe someone could add it? Please :)
https://github.com/localstack/localstack/blob/master/localstack/services/dynamodb/dynamodb_listener.py#L219

**Comment by Isanderthul** [comment]
@whummer you closed this issue, but maybe you could re-evaluate it and open it again, as it would be great if the ttl expire actually removed the document.

**Comment by ktalebian** [comment]
This is still not implemented correct?

**Comment by Isanderthul** [comment]
> This is still not implemented correct?

correct

**Comment by albertoxamin** [comment]
@whummer as of 2024 it still would be relevant to have the ttl that actually deletes the files

**Comment by giograno** [comment]
Hi there! We implemented the deletion of the stale items in our `latest` Docker image (see https://github.com/localstack/localstack/pull/10041). We added now a worker that runs every hour and performs the deletion. To activate the worker, you need to start localstack with the `DYNAMODB_REMOVE_EXPIRED_ITEMS` feature flag. 
We also added the `DELETE /_aws/dynamodb/expired` endpoint to programmatically trigger the job (it does not require the feature flag enabled).

**Comment by Isanderthul** [comment]
@giograno thank you very much. This is great news :) ty for the work.
