### ISSUE TITLE
Cognito and MFA auth are getting errors

### ISSUE THREAD

**Issue by jdtommy** [localstack/localstack#2361]
# Type of request:

[X] bug report
[ ] feature request

# Detailed description

I am using awslocal, Terraform or Pulumi to try and create a UserPool. The user pool gets created, but when I try and set-user-pool-mfa-config either with the cli or Terraform or Pulumi try through the API it fails with 
`The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.`

Even when I call get-user-pool-mfa-config from the cli I get the same error.

## Expected behavior

It should just create the MFA config or return the MFA config with out an error

## Actual behavior

You get an error with this detail
`The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.`

# Steps to reproduce

```
$ awslocal cognito-idp create-user-pool --pool-name my-pool
{
    "UserPool": {
        "Id": "us-east-1_812e40810a554a0b84df2610e0c014fb",
        "Name": "my-pool",
        "LastModifiedDate": 1588010762.0,
        "CreationDate": 1588010762.0,
        "Arn": "arn:aws:cognito-idp:us-east-1:123456789012:userpool/us-east-1_812e40810a554a0b84df2610e0c014fb"
    }
}

$ awslocal cognito-idp get-user-pool-mfa-config --user-pool-id us-east-1_812e40810a554a0b84df2610e0c014fb

An error occurred (500) when calling the GetUserPoolMfaConfig operation (reached max retries: 4): <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>

$ awslocal cognito-idp set-user-pool-mfa-config --user-pool-id us-east-1_812e40810a554a0b84df2610e0c014fb --mfa-configuration OFF

An error occurred (500) when calling the SetUserPoolMfaConfig operation (reached max retries: 4): <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
```
## Command used to start LocalStack

```
#!/bin/bash

export DEFAULT_REGION=us-west-2
export LOCALSTACK_API_KEY=...
export SERVICES='serverless,cognito,edge,ec2'
export FORCE_NONINTERACTIVE=true
#export DATA_DIR="$HOME/localstack/data"

localstack start
```

**Comment by whummer** [comment]
Thanks for reporting this issue @jdtommy . This should be fixed in the latest version - can you please do a `docker pull localstack/localstack` and give it another try? Please report here if the problem persists. Thanks!
