### ISSUE TITLE
ApiGateway UsagePlan api does not honour API Gateway behaviour with non existing api keys and usage plans

### ISSUE THREAD

**Issue by apalumbo** [localstack/localstack#2363]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description
There is an issue with the usage plan api of the api gateway, when you try to retrieve an usage plan that does not exists a 500 error is raised.
Also if you try to try to retrieve an usage plan key with a non added api key (if it is not jet added to the subscription plan).
The bug is *moto* related, I opended an issue an implemented a PR, I am creating this issue just to document the problem in localstack, to track for a future moto update.
[This is the issue for *moto*](https://github.com/spulec/moto/issues/2928) 
...

## Expected behavior
Should return 404 NotFound error 
...

## Actual behavior
Hangs with a 500 error
...

# Steps to reproduce
just try to check if an api key is in a subscription plan (fails with a 500 error if not)

## Command used to start LocalStack
localstack start
...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

...

**Comment by whummer** [comment]
Thanks for reporting this issue @apalumbo . The upstream issue is now fixed in moto (https://github.com/spulec/moto/issues/2928) and should be available in LocalStack now. Can you please give it a try with the `latest` version of the Docker image? Please report here if the problem persists. Thanks
