### ISSUE TITLE
Unable to insert 1000+n objects in S3

### ISSUE THREAD

**Issue by AdelinGhanaem** [localstack/localstack#2367]
# Type of request: bug report

# Detailed description
We are testing that our method can delete objects from s3 bucket by certain criteria, first, we are listing objects then picking up some of them to delete. Because S3 has a limit to delete 1000 objects per request we delete these in chunks. To test this behaviour we need to insert 1000+n objection in S3 and try to remove them by calling our function. However, the API seems to be unable to insert 1000+n objections.  

## Expected behaviour
size to be 1100
## Actual behaviour

size = 1000 
# Steps to reproduce
configure Localstack and run a test similar to the one below.

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

```scala 
"create 1000+n objects and delete them afterwards" in {
      val s3Client: AmazonS3 = AmazonS3ClientBuilder
        .standard
        .withPathStyleAccessEnabled(true)
        .withEndpointConfiguration(new EndpointConfiguration("localhost:4572", "eu-west-1"))
        .withClientConfiguration(new ClientConfiguration().withProtocol(Protocol.HTTP))
        .withCredentials(new AWSStaticCredentialsProvider(awsCreds))
        .build
      
      (1 to 1100).foreach { index =>
        s3Client.putObject("some_name", s"content/0000_$index", "some_content")
      }

      val s = s3Client.listObjects(srcBucketName).getObjectSummaries.asScala.toList.size

      println(s"SIZE: $s") // prints only 1000
      
    }
```

**Comment by whummer** [comment]
Thanks for reporting @AdelinGhanaem . This seems to be the expected behavior, as per https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjects.html . Did you test the same code against real AWS?
```
Returns some or all (up to 1,000) of the objects in a bucket ...
```

An integration test has been added in #2390 to cover this functionality. Please report here if there are any questions or other issues. Thanks

**Comment by whummer** [comment]
Thanks again - confirmed that this is the expected behavior. An integration test has been added in #2390. Please report here if the problem persists. Thanks
