### ISSUE TITLE
WARNING:infra.pyc:Service "kinesis" not yet available, retrying...

### ISSUE THREAD

**Issue by attilapalfi92** [localstack/localstack#237]
Freshly cloned the repository on Windows 10 with docker installed. I executed the docker-compose up command, but kinesis service is not willing to start. Other mock services are starting without a problem.

**Comment by whummer** [comment]
Hi @attilapalfi92 , thanks for reporting. Can you please try running with the environment variable `DEBUG=1` set. This should give you more detailed logs, can you please post the output here. Thanks

**Comment by attilapalfi92** [comment]
Here is the output of the first batch of trying. After retrying to start Kinesis 9 times, the process fails, and starts from the beginning.

$ docker-compose up
Recreating localstack_localstack_1 ...
Recreating localstack_localstack_1 ... done
Attaching to localstack_localstack_1
localstack_1  | 2017-08-09 10:27:38,085 CRIT Supervisor running as root (no user in config file)
localstack_1  | 2017-08-09 10:27:38,086 INFO supervisord started with pid 1
localstack_1  | 2017-08-09 10:27:39,088 INFO spawned: 'dashboard' with pid 8
localstack_1  | 2017-08-09 10:27:39,089 INFO spawned: 'infra' with pid 9
localstack_1  | (. .venv/bin/activate; bin/localstack web --port=8080)
localstack_1  | (. .venv/bin/activate; exec bin/localstack start)
localstack_1  | Starting local dev environment. CTRL-C to quit.
localstack_1  |  * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
localstack_1  |  * Restarting with stat
localstack_1  | Starting mock API Gateway (http port 4567)...
localstack_1  | Starting mock CloudWatch (http port 4582)...
localstack_1  | Starting mock SES (http port 4579)...
localstack_1  | Starting mock Kinesis (http port 4568)...
localstack_1  | Starting mock Redshift (http port 4577)...
localstack_1  | Starting mock S3 (http port 4572)...
localstack_1  | Starting mock CloudFormation (http port 4581)...
localstack_1  | Starting mock DynamoDB (http port 4569)...
localstack_1  | Starting mock SQS (http port 4576)...
localstack_1  |  * Debugger is active!
localstack_1  |  * Debugger PIN: 273-968-220
localstack_1  | Starting local Elasticsearch (http port 4571)...
localstack_1  | Initializing DynamoDB Local with the following configuration:
localstack_1  | Port:   4564
localstack_1  | InMemory:       true
localstack_1  | DbPath: null
localstack_1  | SharedDb:       true
localstack_1  | shouldDelayTransientStatuses:   false
localstack_1  | CorsParams:     *
localstack_1  | 2017-08-09 10:27:40,757 INFO success: dashboard entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
localstack_1  | 2017-08-09 10:27:40,758 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
localstack_1  |
localstack_1  | * Running on http://0.0.0.0:4559/ (Press CTRL+C to quit)
localstack_1  | * Running on http://0.0.0.0:4577/ (Press CTRL+C to quit)
localstack_1  | * Running on http://0.0.0.0:4563/ (Press CTRL+C to quit)
localstack_1  | * Running on http://0.0.0.0:4579/ (Press CTRL+C to quit)
localstack_1  | * Running on http://0.0.0.0:4566/ (Press CTRL+C to quit)
localstack_1  | * Running on http://0.0.0.0:4582/ (Press CTRL+C to quit)
localstack_1  | * Running on http://0.0.0.0:4561/ (Press CTRL+C to quit)
localstack_1  | Listening at http://:::4565
localstack_1  | Starting mock SNS (http port 4575)...
localstack_1  | Starting mock DynamoDB Streams service (http port 4570)...
localstack_1  | Starting mock Firehose service (http port 4573)...
localstack_1  | Starting mock Route53 (http port 4580)...
localstack_1  | Starting mock ES service (http port 4578)...
localstack_1  | Starting mock Lambda service (http port 4574)...
localstack_1  | * Running on http://0.0.0.0:4562/ (Press CTRL+C to quit)
localstack_1  | * Running on http://0.0.0.0:4580/ (Press CTRL+C to quit)
localstack_1  | [2017-08-09T10:27:43,584][INFO ][o.e.n.Node               ] [] initializing ...
localstack_1  | [2017-08-09T10:27:43,682][INFO ][o.e.e.NodeEnvironment    ] [BMMk8JF] using [1] data paths, mounts [[/ (overlay)]], net usable_space [52.3gb], net total_space [58.8gb], spins? [possibly], types [overlay]
localstack_1  | [2017-08-09T10:27:43,683][INFO ][o.e.e.NodeEnvironment    ] [BMMk8JF] heap size [483.3mb], compressed ordinary object pointers [true]
localstack_1  | [2017-08-09T10:27:43,686][INFO ][o.e.n.Node               ] node name [BMMk8JF] derived from node ID [BMMk8JFcQFSS_aZBdokQog]; set [node.name] to override
localstack_1  | [2017-08-09T10:27:43,686][INFO ][o.e.n.Node               ] version[5.3.0], pid[136], build[3adb13b/2017-03-23T03:31:50.652Z], OS[Linux/4.9.36-moby/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/1.8.0_131/25.131-b11]
localstack_1  | [2017-08-09T10:27:44,624][INFO ][o.e.p.PluginsService     ] [BMMk8JF] loaded module [aggs-matrix-stats]
localstack_1  | [2017-08-09T10:27:44,625][INFO ][o.e.p.PluginsService     ] [BMMk8JF] loaded module [ingest-common]
localstack_1  | [2017-08-09T10:27:44,625][INFO ][o.e.p.PluginsService     ] [BMMk8JF] loaded module [lang-expression]
localstack_1  | [2017-08-09T10:27:44,626][INFO ][o.e.p.PluginsService     ] [BMMk8JF] loaded module [lang-groovy]
localstack_1  | [2017-08-09T10:27:44,626][INFO ][o.e.p.PluginsService     ] [BMMk8JF] loaded module [lang-mustache]
localstack_1  | [2017-08-09T10:27:44,627][INFO ][o.e.p.PluginsService     ] [BMMk8JF] loaded module [lang-painless]
localstack_1  | [2017-08-09T10:27:44,627][INFO ][o.e.p.PluginsService     ] [BMMk8JF] loaded module [percolator]
localstack_1  | [2017-08-09T10:27:44,631][INFO ][o.e.p.PluginsService     ] [BMMk8JF] loaded module [reindex]
localstack_1  | [2017-08-09T10:27:44,631][INFO ][o.e.p.PluginsService     ] [BMMk8JF] loaded module [transport-netty3]
localstack_1  | [2017-08-09T10:27:44,631][INFO ][o.e.p.PluginsService     ] [BMMk8JF] loaded module [transport-netty4]
localstack_1  | [2017-08-09T10:27:44,634][INFO ][o.e.p.PluginsService     ] [BMMk8JF] no plugins loaded
localstack_1  | [2017-08-09T10:27:46,992][INFO ][o.e.n.Node               ] initialized
localstack_1  | [2017-08-09T10:27:46,993][INFO ][o.e.n.Node               ] [BMMk8JF] starting ...
localstack_1  | [2017-08-09T10:27:47,204][WARN ][i.n.u.i.MacAddressUtil   ] Failed to find a usable hardware address from the network interfaces; using random bytes: fb:20:cc:7c:31:f3:d4:5b
localstack_1  | [2017-08-09T10:27:47,372][INFO ][o.e.t.TransportService   ] [BMMk8JF] publish_address {127.0.0.1:9300}, bound_addresses {127.0.0.1:9300}
localstack_1  | [2017-08-09T10:27:47,386][WARN ][o.e.b.BootstrapChecks    ] [BMMk8JF] initial heap size [209715200] not equal to maximum heap size [524288000]; this can cause resize pauses and prevents mlockall from locking the entire heap localstack_1  | [2017-08-09T10:27:50,445][INFO ][o.e.c.s.ClusterService   ] [BMMk8JF] new_master {BMMk8JF}{BMMk8JFcQFSS_aZBdokQog}{4takd-QzRDq_uMxq3dDbRQ}{127.0.0.1}{127.0.0.1:9300}, reason: zen-disco-elected-as-master ([0] nodes joined)
localstack_1  | [2017-08-09T10:27:50,490][INFO ][o.e.h.n.Netty4HttpServerTransport] [BMMk8JF] publish_address {127.0.0.1:4560}, bound_addresses {127.0.0.1:4560}
localstack_1  | [2017-08-09T10:27:50,499][INFO ][o.e.n.Node               ] [BMMk8JF] started
localstack_1  | [2017-08-09T10:27:50,515][INFO ][o.e.g.GatewayService     ] [BMMk8JF] recovered [0] indices into cluster_state
localstack_1  | WARNING:infra.py:Service "kinesis" not yet available, retrying...
localstack_1  | WARNING:infra.py:Service "kinesis" not yet available, retrying...
localstack_1  | WARNING:infra.py:Service "kinesis" not yet available, retrying...
localstack_1  | WARNING:infra.py:Service "kinesis" not yet available, retrying...
localstack_1  | WARNING:infra.py:Service "kinesis" not yet available, retrying...
localstack_1  | WARNING:infra.py:Service "kinesis" not yet available, retrying...
localstack_1  | WARNING:infra.py:Service "kinesis" not yet available, retrying...
localstack_1  | WARNING:infra.py:Service "kinesis" not yet available, retrying...
localstack_1  | WARNING:infra.py:Service "kinesis" not yet available, retrying...
localstack_1  | ERROR:infra.py:Error checking state of local environment (after some retries): Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/localstack/services/infra.py", line 304, in check_infra
localstack_1  |     raise e
localstack_1  | UnicodeEncodeError: 'ascii' codec can't encode character u'\ufeff' in position 89: ordinal not in range(128)
localstack_1  |
localstack_1  | Error starting infrastructure: 'ascii' codec can't encode character u'\ufeff' in position 89: ordinal not in range(128)
localstack_1  | Killed
localstack_1  | Killed
localstack_1  | 2017-08-09 10:29:33,906 INFO reaped unknown pid 62
localstack_1  | 2017-08-09 10:29:33,907 INFO reaped unknown pid 64
localstack_1  | 2017-08-09 10:29:33,917 INFO reaped unknown pid 75
localstack_1  | Killed
localstack_1  | 2017-08-09 10:29:33,936 INFO reaped unknown pid 90
localstack_1  | 2017-08-09 10:29:33,939 INFO reaped unknown pid 88
localstack_1  | Killed
localstack_1  | Killed
localstack_1  | 2017-08-09 10:29:33,983 INFO reaped unknown pid 136
localstack_1  | Traceback (most recent call last):
localstack_1  |   File "bin/localstack", line 110, in <module>
localstack_1  |     infra.start_infra()
localstack_1  |   File "/opt/code/localstack/localstack/services/infra.py", line 380, in start_infra
localstack_1  |     raise e
localstack_1  | UnicodeEncodeError: 'ascii' codec can't encode character u'\ufeff' in position 89: ordinal not in range(128)
localstack_1  | 2017-08-09 10:29:36,012 INFO reaped unknown pid 65
localstack_1  | 2017-08-09 10:29:36,012 INFO reaped unknown pid 73
localstack_1  | 2017-08-09 10:29:36,012 INFO reaped unknown pid 87
localstack_1  | make: *** [Makefile:34: infra] Error 1
localstack_1  | 2017-08-09 10:29:36,013 INFO exited: infra (exit status 2; expected)
localstack_1  | 2017-08-09 10:29:36,013 INFO reaped unknown pid 137
localstack_1  | 2017-08-09 10:29:37,015 INFO spawned: 'infra' with pid 220
localstack_1  | (. .venv/bin/activate; exec bin/localstack start)
localstack_1  | Starting local dev environment. CTRL-C to quit.

**Comment by whummer** [comment]
OK, there seems to be a character encoding problem. These kinds of problems are a bit difficult to debug - I don't currently have access to a Windows machine, I will have to ask you to run a few commands and post the output.

First off, what's the output of this command:
```
docker run --entrypoint "" localstack/localstack bash -c 'make infra & sleep 6; . .venv/bin/activate; aws --endpoint-url=http://localhost:4568 kinesis list-streams'
```

Then this:
```
docker run --entrypoint "" localstack/localstack bash -c 'make infra & sleep 6; . .venv/bin/activate; aws --endpoint-url=http://localhost:4565 kinesis list-streams'
```

And then:
```
docker run --entrypoint "" -it localstack/localstack bash -c "sed -i 's/raise e/print(traceback.format_exc()); raise e/g' localstack/services/infra.py; cat localstack/services/infra.py | grep 'raise e'; make infra"
```

Thanks

**Comment by attilapalfi92** [comment]
Sorry for the late answer, I was on vacation. :) 

The output of the first command is:

WARNING:infra.py:Service "kinesis" not yet available, retrying...

An error occurred (502) when calling the ListStreams operation (reached max retries: 4): Bad Gateway

**Comment by attilapalfi92** [comment]
The output for the second command was the following:

An error occurred (502) when calling the ListStreams operation (reached max retries: 4): Bad Gateway

**Comment by attilapalfi92** [comment]
And for the last one:

$ docker run --entrypoint "" -it localstack/localstack bash -c "sed -i 's/raise e/print(traceback.format_exc()); raise e/g' localstack/services/infra.py; cat localstack/services/infra.py | grep 'raise e'; make infra"
                    print(traceback.format_exc()); raise e
            print(traceback.format_exc()); raise e
        print(traceback.format_exc()); raise e
(. .venv/bin/activate; exec bin/localstack start)
Starting local dev environment. CTRL-C to quit.
Starting mock API Gateway (http port 4567)...
Starting mock CloudWatch (http port 4582)...
Starting mock SES (http port 4579)...
Starting mock Kinesis (http port 4568)...
Starting mock Redshift (http port 4577)...
Starting mock S3 (http port 4572)...
Starting mock CloudFormation (http port 4581)...
Starting mock DynamoDB (http port 4569)...
Starting mock SQS (http port 4576)...
Starting local Elasticsearch (http port 4571)...
Starting mock SNS (http port 4575)...
Starting mock DynamoDB Streams service (http port 4570)...
Starting mock Firehose service (http port 4573)...
Starting mock Route53 (http port 4580)...
Starting mock ES service (http port 4578)...
Starting mock Lambda service (http port 4574)...
WARNING:infra.py:Service "kinesis" not yet available, retrying...
Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/infra.py", line 301, in check_infra
    plugin.check(expect_shutdown=expect_shutdown, print_error=print_error)
  File "/opt/code/localstack/localstack/services/infra.py", line 68, in check
    return self.check_function(expect_shutdown=expect_shutdown, print_error=print_error)
  File "/opt/code/localstack/localstack/services/kinesis/kinesis_starter.py", line 39, in check_kinesis
    assert isinstance(out['StreamNames'], list)
TypeError: 'NoneType' object has no attribute '__getitem__'

WARNING:infra.py:Service "kinesis" not yet available, retrying...
Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/infra.py", line 301, in check_infra
    plugin.check(expect_shutdown=expect_shutdown, print_error=print_error)
  File "/opt/code/localstack/localstack/services/infra.py", line 68, in check
    return self.check_function(expect_shutdown=expect_shutdown, print_error=print_error)
  File "/opt/code/localstack/localstack/services/kinesis/kinesis_starter.py", line 39, in check_kinesis
    assert isinstance(out['StreamNames'], list)
TypeError: 'NoneType' object has no attribute '__getitem__'

WARNING:infra.py:Service "kinesis" not yet available, retrying...
Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/infra.py", line 301, in check_infra
    plugin.check(expect_shutdown=expect_shutdown, print_error=print_error)
  File "/opt/code/localstack/localstack/services/infra.py", line 68, in check
    return self.check_function(expect_shutdown=expect_shutdown, print_error=print_error)
  File "/opt/code/localstack/localstack/services/kinesis/kinesis_starter.py", line 39, in check_kinesis
    assert isinstance(out['StreamNames'], list)
TypeError: 'NoneType' object has no attribute '__getitem__'

WARNING:infra.py:Service "kinesis" not yet available, retrying...
Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/infra.py", line 301, in check_infra
    plugin.check(expect_shutdown=expect_shutdown, print_error=print_error)
  File "/opt/code/localstack/localstack/services/infra.py", line 68, in check
    return self.check_function(expect_shutdown=expect_shutdown, print_error=print_error)
  File "/opt/code/localstack/localstack/services/kinesis/kinesis_starter.py", line 39, in check_kinesis
    assert isinstance(out['StreamNames'], list)
TypeError: 'NoneType' object has no attribute '__getitem__'

WARNING:infra.py:Service "kinesis" not yet available, retrying...
Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/infra.py", line 301, in check_infra
    plugin.check(expect_shutdown=expect_shutdown, print_error=print_error)
  File "/opt/code/localstack/localstack/services/infra.py", line 68, in check
    return self.check_function(expect_shutdown=expect_shutdown, print_error=print_error)
  File "/opt/code/localstack/localstack/services/kinesis/kinesis_starter.py", line 39, in check_kinesis
    assert isinstance(out['StreamNames'], list)
TypeError: 'NoneType' object has no attribute '__getitem__'

WARNING:infra.py:Service "kinesis" not yet available, retrying...
Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/infra.py", line 301, in check_infra
    plugin.check(expect_shutdown=expect_shutdown, print_error=print_error)
  File "/opt/code/localstack/localstack/services/infra.py", line 68, in check
    return self.check_function(expect_shutdown=expect_shutdown, print_error=print_error)
  File "/opt/code/localstack/localstack/services/kinesis/kinesis_starter.py", line 39, in check_kinesis
    assert isinstance(out['StreamNames'], list)
TypeError: 'NoneType' object has no attribute '__getitem__'

WARNING:infra.py:Service "kinesis" not yet available, retrying...
Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/infra.py", line 301, in check_infra
    plugin.check(expect_shutdown=expect_shutdown, print_error=print_error)
  File "/opt/code/localstack/localstack/services/infra.py", line 68, in check
    return self.check_function(expect_shutdown=expect_shutdown, print_error=print_error)
  File "/opt/code/localstack/localstack/services/kinesis/kinesis_starter.py", line 39, in check_kinesis
    assert isinstance(out['StreamNames'], list)
TypeError: 'NoneType' object has no attribute '__getitem__'

WARNING:infra.py:Service "kinesis" not yet available, retrying...
Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/infra.py", line 301, in check_infra
    plugin.check(expect_shutdown=expect_shutdown, print_error=print_error)
  File "/opt/code/localstack/localstack/services/infra.py", line 68, in check
    return self.check_function(expect_shutdown=expect_shutdown, print_error=print_error)
  File "/opt/code/localstack/localstack/services/kinesis/kinesis_starter.py", line 39, in check_kinesis
    assert isinstance(out['StreamNames'], list)
TypeError: 'NoneType' object has no attribute '__getitem__'

WARNING:infra.py:Service "kinesis" not yet available, retrying...
Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/infra.py", line 301, in check_infra
    plugin.check(expect_shutdown=expect_shutdown, print_error=print_error)
  File "/opt/code/localstack/localstack/services/infra.py", line 68, in check
    return self.check_function(expect_shutdown=expect_shutdown, print_error=print_error)
  File "/opt/code/localstack/localstack/services/kinesis/kinesis_starter.py", line 35, in check_kinesis
    LOGGER.error('Kinesis health check failed: %s %s' % (e, traceback.format_exc()))
UnicodeEncodeError: 'ascii' codec can't encode character u'\ufeff' in position 89: ordinal not in range(128)

ERROR:infra.py:Error checking state of local environment (after some retries): Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/infra.py", line 304, in check_infra
    print(traceback.format_exc()); raise e
UnicodeEncodeError: 'ascii' codec can't encode character u'\ufeff' in position 89: ordinal not in range(128)

Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/infra.py", line 304, in check_infra
    print(traceback.format_exc()); raise e
UnicodeEncodeError: 'ascii' codec can't encode character u'\ufeff' in position 89: ordinal not in range(128)

Error starting infrastructure: 'ascii' codec can't encode character u'\ufeff' in position 89: ordinal not in range(128)
Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/infra.py", line 363, in start_infra
    check_infra(apis=apis)
  File "/opt/code/localstack/localstack/services/infra.py", line 313, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "/opt/code/localstack/localstack/services/infra.py", line 313, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "/opt/code/localstack/localstack/services/infra.py", line 313, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "/opt/code/localstack/localstack/services/infra.py", line 313, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "/opt/code/localstack/localstack/services/infra.py", line 313, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "/opt/code/localstack/localstack/services/infra.py", line 313, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "/opt/code/localstack/localstack/services/infra.py", line 313, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "/opt/code/localstack/localstack/services/infra.py", line 313, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "/opt/code/localstack/localstack/services/infra.py", line 311, in check_infra
    print(traceback.format_exc()); raise e
UnicodeEncodeError: 'ascii' codec can't encode character u'\ufeff' in position 89: ordinal not in range(128)

Traceback (most recent call last):
  File "bin/localstack", line 110, in <module>
    infra.start_infra()
  File "/opt/code/localstack/localstack/services/infra.py", line 380, in start_infra
    print(traceback.format_exc()); raise e
UnicodeEncodeError: 'ascii' codec can't encode character u'\ufeff' in position 89: ordinal not in range(128)
make: *** [Makefile:34: infra] Error 1

**Comment by Kkari** [comment]
Hey there,

I have stumbled up on a similar problem. In the former repository of localstack:

https://bitbucket.org/atlassian/localstack/issues/30/error-when-starting-through-the-docker-on

I have managed to get kinesis to work with the commands described in the link above. It is a bit of a pain though, so if you have the time please look into it to get it work with the original configuration.

**Comment by whummer** [comment]
Closing this issue as outdated - please try with the latest version, in which this issue should be fixed.
