### ISSUE TITLE
Docker Image 0.11.0 requires sudo because of EDGE_PORT

### ISSUE THREAD

**Issue by ABevier** [localstack/localstack#2371]
We deploy localstack to Openshift which does not allow containers to run as root.  The update to 0.11.0 isn't working because edge.py is trying to sudo.

It looks like EDGE_PORT is set to 443 and EDGE_PORT_HTTP is 4566, which is causing the sudo block of edge.py to be hit.

I tried set EDGE_PORT to a value above 1024 as a work around and I got the following error:
`2020-04-30T03:40:08:WARNING:bootstrap.py: Unable to load plugins from file /opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/plugins.py: MyHTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /localstack/localstack-artifacts/raw/master/local-certs/server.key (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f20df003880>: Failed to establish a new connection: [Errno -2] Name does not resolve'))`

Where do these default configuration values come from?  I was surprised that EDGE_PORT was set to 443 by default.

**Comment by whummer** [comment]
Thanks for reporting @ABevier @birdsarah . The issue with `EDGE_PORT` being set to 443 should be fixed in the latest version. Can you please upgrade your pip packages and give it another try:
```
pip install --upgrade --no-cache localstack localstack-ext localstack-client
```
Hope that helps - please report here if the problem persists. Thanks!
