### ISSUE TITLE
Add missing 0.10.7 tag

### ISSUE THREAD

**Issue by bobtiernay-okta** [localstack/localstack#2374]
Currently the `0.10.7` tag appears to be missing. This makes it challenging to know why things stopped working between releases. We should retroactively add it and It should likely be placed on this commit:

https://github.com/localstack/localstack/commit/91ad02720fb1f2126c92176b23167a3d543e4c9d

Here is a list of the changes introduced in this version:
https://github.com/localstack/localstack/compare/v0.10.6...91ad02720fb1f2126c92176b23167a3d543e4c9d

**Comment by whummer** [comment]
Thanks for reporting @bobtiernay-okta . The missing image tag `0.10.7` has been pushed, based on the version in commit `91ad027`.

**Comment by bobtiernay-okta** [comment]
Thank you!
