### ISSUE TITLE
`generic_proxy.py`'s `Connection` header handling should be case insensitive

### ISSUE THREAD

**Issue by bobtiernay-okta** [localstack/localstack#2375]
# Type of request:

- [x] bug report
- [ ] feature request

# Detailed description

In `0.10.8`, `localstack/services/generic_proxy.py` has regressed with respect to `Connection` header handling. HTTP headers are expected to be [case insensitive](https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2).

In version `0.10.7` of `generic_proxy.py`:
```python
if forward_headers.get('Connection', '').lower() != 'keep-alive':
  self.close_connection = 1
```

in `0.10.8` [this was changed](https://github.com/localstack/localstack/commit/859cbc5ad1c23fefcec10a7a25570fe7581cbbb5) to
```python
if forward_headers.get('Connection') not in ['keep-alive', None]:
  self.close_connection = 1
```
Note that the call to `lower()` was removed.

## Expected behavior

Keep case `Connection` insensitive header handling. 

## Actual behavior

Case sensitive 

# Steps to reproduce

Send a request with `Connection: Keep-Alive`

## Command used to start LocalStack

N/A

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

N/A

**Comment by whummer** [comment]
Thanks for reporting @bobtiernay-okta . This should be fixed in #2377 - can you please give it a try with the `latest` version of the Docker image? Please report here if the problem persists. Thanks!

**Comment by bobtiernay-okta** [comment]
@whummer I'm wondering about the logic:
```python
        connection_header = forward_headers.get('Connection') or ''
        if connection_header.lower() not in ['keep-alive', '']:
            self.close_connection = 1
```

Why are `'keep-alive'`, `''` and `None` treated the same? Shouldn't this logic be the following instead?

```python
forward_headers.get('Connection', '').lower() == 'close':
            self.close_connection = 1
```

```python
forward_headers.get('Connection', '').lower() != 'keep-alive':
            self.close_connection = 1
```
?
or at least:

**Comment by bobtiernay-okta** [comment]
@whummer Per your ask, I've validated the fix and it looks like it does help quite a bit with our vast integration tests. I have a feeling a number of reported issues will benefit from these (at least  those using the Java AWS SDK). Looking forward to the next release so that we can move forward from `0.10.7`.
