### ISSUE TITLE
[SNS] Subscription endpoint error after upgrading >= 0.10.5

### ISSUE THREAD

**Issue by sylvain-duval** [localstack/localstack#2381]
# Type of request: This is a ...

[X] bug report
[ ] feature request

# Detailed description
Localstack is part of our project in development env, it's tagged in our docker-compose file with latest version.
After rebuilding our project with docker-compose recently our SNS endpoint application stopped working.
I tried different versions and it starts to fail from the 0.10.5 version and our endpoint didn't received notifications anymore.

## Context

Our automated procces is the following : 
- Create topic
- Subscribe http endpoint
- Confirm subscription calling the SubscribeURL

The create topic and subscribe API calls are made using PHP SDK and we use the **eu-west-3** region for SNS.

The confirmation subscription is just done using a request call to the SubscribeURL in our endpoint NodeJS App

## Errors

On 0.11.0 after creating a topic the generated TopicArn always contains the region **us-east-1** even tho we specified **eu-west-3** 

On >= 0.10.5 a direct call to the SubscribeURL lead to an error because it missing the Authorization header.
> I am not sure that the Authorization header is required when calling the SubscribeURL because it contains a token to validate subcription.

On 0.11.0 the hostname returned by localstack in the SubscribeURL in our environment is **localhost**
To properly call the subscribe url we have to replace **localhost** => **localstack**

> **On 0.10.5** the hostname returned by localstack in the SubscribeURL is a bit random but actually works

0.11.0, 0.10.5 both return 404 errors when calling the SubscribeURL
`<ErrorResponse xmlns=\"http://sns.amazonaws.com/doc/2010-03-31/\">\n <Error>\n <Type>Sender</Type>\n <Code>NotFound</Code>\n <Message>Topic does not exist</Message>\n </Error>\n <RequestId>xxx</RequestId>\n</ErrorResponse>`
> **On 0.10.5** The endpoint properly receive notifications even tho it returned an error

## Solution

For now I specified the version of localstack in our docker-compose file back to 0.10.2 to keep working in our actual env. as we don't need to call SubscribeURL in order to receive notifications

**Comment by whummer** [comment]
Thanks for reporting @sylvain-duval - we did a quick test and this seems to be fixed in the `latest` version of the Docker image. Please note that region used by your client needs to match the region configured for the server (configurable via `DEFAULT_REGION`, or `us-east-1` by default). Please report here if the problem persists. Thanks
