### ISSUE TITLE
USE_SSL=1 breaks cloudwatch logging

### ISSUE THREAD

**Issue by timoly** [localstack/localstack#2387]
[x] bug report
[ ] feature request

# Detailed description
cloudwatch logging doesn't work if USE_SSL is enabled. The problem seems to be in 
https://github.com/localstack/localstack/blob/f9d5c1a77088bf65e10d05a298ef7ab61fc64314/localstack/utils/cloudwatch/cloudwatch_util.py#L57
If protocol is https ,the service is enabled resolver returns False. Logging works normally when USE_SSL=0
Happens at least with 0.11.1, but seems to be the same problem with older versions also.

## Expected behavior
Cloudwatch logging works
...

## Actual behavior
Nothing is logged to cloudwatch logs

# Steps to reproduce
set USE_SSL=1

## Command used to start LocalStack
docker-compose up

**Comment by whummer** [comment]
Thanks for reporting @timoly . This should be fixed in #2389 - can you please give it a try with the `latest` version of the Docker image? Please report here if the problem persists. Thanks!

**Comment by timoly** [comment]
> Thanks for reporting @timoly . This should be fixed in #2389 - can you please give it a try with the `latest` version of the Docker image? Please report here if the problem persists. Thanks!

#2389 seems to fix the issue, thank you.
