### ISSUE TITLE
Manual push of 0.10.7 tag seems broken.

### ISSUE THREAD

**Issue by shawnrusaw-wf** [localstack/localstack#2388]
According to https://hub.docker.com/r/localstack/localstack/tags, 0.10.7 was manually pushed yesterday. That seems to have broken all of our CI using that tag in an as-yet unexplained way. Is it possible to leave that tag as it was?

**Comment by whummer** [comment]
Hi @shawnrusaw-wf , thanks for reporting. Are you sure that your CI was using tag `0.10.7`? This tag has actually been pushed in response to [this ticket](https://github.com/localstack/localstack/issues/2374). I briefly double-checked before pushing that the tag did not exist before, but may have overlooked it.

Do you know a way to find out via the API when an image tag was first created? Cannot find this information here, unfortunately: https://hub.docker.com/v2/repositories/localstack/localstack/tags/0.10.7

If worse comes to worst, would updating to a newer version be an option for you? Apologies for the inconvenience!

**Comment by shawnrusaw-wf** [comment]
The tag did exist on https://hub.docker.com/r/localstack/localstack/tags, but it was not tagged in github. I'm trying to track down a sha.

**Comment by shawnrusaw-wf** [comment]
```
[shawnrusaw@WF15544 localstack (master)]$ docker image history localstack/localstack:0.10.7
IMAGE               CREATED             CREATED BY          SIZE                COMMENT
1d7663bb2f3c        3 months ago                            880MB
[shawnrusaw@WF15544 localstack (master)]$ docker pull localstack/localstack:0.10.7
...
[shawnrusaw@WF15544 localstack (master)]$ docker image history localstack/localstack:0.10.7
IMAGE               CREATED             CREATED BY          SIZE                COMMENT
54618943c7c8        24 hours ago                            940MB
```

**Comment by whummer** [comment]
Thanks - any chance you can tag image `1d7663bb2f3c` under a different name, and push it to a public repo? I can then pull it and update `localstack/localstack:0.10.7`. Thanks

**Comment by whummer** [comment]
Edit: I think I should also be able to pull from Docker hub directly, if you can share the full sha256 image ID with me.
```
docker pull localstack/localstack@sha256:1d7663bb2f3c...
```
Can you please share this:
```
docker inspect 1d7663bb2f3c
```

**Comment by shawnrusaw-wf** [comment]
```
        "Id": "sha256:1d7663bb2f3c1bffd832fcf013b0e97907dccc7f7e626c76bafcf257d1715824"
```

thx!

**Comment by whummer** [comment]
@shawnrusaw-wf  Looks like the image is not available (anymore?) on Docker hub:
```
$ docker pull localstack/localstack@sha256:1d7663bb2f3c1bffd832fcf013b0e97907dccc7f7e626c76bafcf257d1715824
Error response from daemon: received unexpected HTTP status: 500 Internal Server Error
```
Can we please try the other option - can you try to temporarily tag and push the image with ID `1d7663bb2f3c` to a public Docker hub repo, so I can pull it from there? thanks

**Comment by shawnrusaw-wf** [comment]
just saw this now. reverting to 0.10.6 has solved our issue, but I'll try to get this pushed up. do you have a preferred public docker repo? @whummer

**Comment by whummer** [comment]
> EDIT: During the course of triaging an unrelated issue, this image has been deleted from my local laptop. I am not able to push it up.

Outch, should have asked you earlier to push it. Thanks, anyway.

**In case someone reads this** who still have the image with ID `1d7663bb2f3c` (`sha256:1d7663bb2f3c1bffd832fcf013b0e97907dccc7f7e626c76bafcf257d1715824`) in their local Docker cache, kindly please tag this image and push it to some public repo where we can pull it! :) Thanks

**Comment by eager** [comment]
> In case someone happens to read this who still has the image with ID 1d7663bb2f3c (sha256:1d7663bb2f3c1bffd832fcf013b0e97907dccc7f7e626c76bafcf257d1715824) in their local Docker cache, kindly please tag this image and push it to some public repo where we can pull it! :) Thanks

@shawnrusaw-wf @whummer is this still relevant? I was helping a member of my team troubleshoot something, I still had the old image.

https://hub.docker.com/layers/turo/localstack/0.10.7/images/sha256-72b0262a0c1f843cb2f47bd53d5243f8582b9555d135f5c5d970167e31903608?context=repo
