### ISSUE TITLE
[API GATEWAY] DELETE request response is 502 error after upgrading to 0.11.1

### ISSUE THREAD

**Issue by lazaro-lito** [localstack/localstack#2392]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description
DELETE requests used to work fine with localstack v0.11.0 or older.
I have a lambda proxy with the following response for DELETE requests:
```python
response = {
    'statusCode': 204
}
```
In v0.11.1, when DELETE request is sent, 502 Bad Gateway is received.

## Expected behavior
204 No Content response is received

## Actual behavior
502 Bad Gateway response is received

## Note
Based on the [change log](https://github.com/localstack/localstack/blob/master/CHANGELOG.md), the issue might be caused by the following:

> fix API Gateway put_integration to avoid responseTemplates containing null values

**Comment by whummer** [comment]
Thanks for reporting @lazaro-lito . This should be fixed upstream in https://github.com/localstack/localstack/pull/2495 , and the fix is now also available in LocalStack. Can you please give it a try with the `latest` version of the Docker image? Please report here if the problem persists. Thanks!
