### ISSUE TITLE
Poor performance when running AWS actions

### ISSUE THREAD

**Issue by tovbinm** [localstack/localstack#2395]
# Type of request: This is a ...
[x] question
[x] issue

# Detailed description
When using LocalStack some AWS actions take a lot of time. E.g. EC2 run/stop instance, Lambda function create. Sometimes it takes 30+ seconds to execute a single call!

## Expected behavior
It should not take so much time.

## Actual behavior
Sometimes it takes 30+ seconds to execute a single call!

# Steps to reproduce
## Command used to start LocalStack
`docker run -p 4566:4566 localstack/localstack:latest`

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
https://github.com/aws/aws-sdk-java-v2

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-180) by [Unito](https://www.unito.io/learn-more)

**Comment by whummer** [comment]
Thanks for reporting @tovbinm . Can you please provide some more details about your specific use case, and the environment you're running in. Are all operations performing equally poor, or are some operations significantly slower than others? Regarding Lambda functions - how large is the , which Lambda runtime are you using, and are you using a custom configuration for `LAMBDA_EXECUTOR`, or just the default (`LAMBDA_EXECUTOR=docker`)?

Right now, it is a bit hard to turn your request into an actionable work item - there may be several reasons why you are seeing poor performance, including (but not limited to) low memory allocated to the Docker engine, CPU throttling, networking issues, etc.

I'm afraid we'll have to close this issue in its current form, but please feel free to provide more specific details and a reproducible example, then we'll be happy to look into this! Thank you.

**Comment by snabar** [comment]
The lambda is in python3.8 run time, and all it does is print "hello world". However, it is loaded as a zip file from a local stack s3 bucket to mimic what our production workflow will be. The createFunction call takes much longer to execute than other calls.

**Comment by snabar** [comment]
I also have not used any custom configuration for LAMBDA_EXECUTOR.

**Comment by ltomes** [comment]
I am also experiencing this issue with lambdas running the python3.8 runtime.

The issue occurs with both `LAMBDA_EXECUTOR='docker'` and `LAMBDA_EXECUTOR='docker-reuse'` for me.

One of my lambda functions is using os specific c bindings, so I can't run `LAMBDA_EXECUTOR=local`

**Comment by whummer** [comment]
Thanks @tovbinm @snabar @ltomes  Closing this issue as outdated - we have recently added a number of performance improvements across different APIs (including Lambdas) and also significantly improved the startup performance of LocalStack. We continue to invest heavily in this area over the next couple of weeks. If you're experiencing any particular performance issues, please feel free to open a new issue with detailed steps to reproduce. Thanks!
