### ISSUE TITLE
Localstack 0.11.1 fails to start in Windows 10

### ISSUE THREAD

**Issue by sivakuna-aap** [localstack/localstack#2403]
# Type of request: This is a bug

[ x ] bug report
[  ] feature request

# Detailed description
Localstack 0.11.1 fails to start in Windows 10. 

## Expected behavior
Localstack 0.11.1 should start in Windows 10

## Actual behavior
Requirement already satisfied: pywin32>=223 in c:\program_files\\.conda\envs\lstack\lib\site-packages (from pypiwin32==223; sys_platform == "win32" and python_version >= "3.6"->docker>=2.5.1->moto-ext>=1.3.15.12) (227)
ERROR: No module named 'pwd'

# Steps to reproduce
choco install -y anaconda3
choco install -y microsoft-visual-cpp-build-tools
conda create -n localstack_env python=3.7.0 pip
conda activate localstack_env 
pip install --user --upgrade pip
pip install https://download.lfd.uci.edu/pythonlibs/s2jqpv5t/sasl-0.2.1-cp37-cp37m-win_amd64.whl
pip install localstack[full]

After installing localstack I configured AWS Profile using the below command:
aws configure --profile default

I looked up some of the issues related to Windows but none of the solutions resolve the error. Also, I tried with python version 3.7.7 but no luck. 

## Command used to start LocalStack
localstack start --host

**Comment by rekon** [comment]
Hi, I run **localstack** in Windows 10 using docker. The steps that I run are:

- start Docker Desktop
- `localstack start` in cmd/powershell

See if it works, since running locally on windows is [problematic](https://github.com/localstack/localstack#starting-locally-non-docker-mode)

**Comment by sivakuna-aap** [comment]
Thank you @rekon 

I was seeing if localstack can run natively on Windows but after some troubleshooting, I found that localstack is not built to natively run on Windows. 

https://github.com/localstack/localstack/blob/master/localstack/utils/common.py#L688

Hopefully, it will be built sometime in the future.
