### ISSUE TITLE
SNS createQueue with different tags dehaves differently than AWS

### ISSUE THREAD

**Issue by PhilLavoie** [localstack/localstack#2405]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description
If you run something like this, in nodejs and using the `aws-sdk`:
```js
await sns.createQueue({Name: "the-queue", Tags: [{Key: "theKey", Value: "theValue"}]}).promise();
await sns.createQueue({Name: "the-queue", Tags: [{Key: "otherKey", Value: "otherValue"}]}).promise();
```
The real cloud service will reject the second call with an error as such: `Invalid parameter: Tags Reason: Topic already exists with different tags`, whereas `localstack` lets the second call pass and doesn't update the tags.

You'll get the same behaviour with the `awscli`.
...

## Expected behavior
At least a 400 response code, as described here: https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_CreateQueue.html#API_CreateQueue_Errors
...

## Actual behavior
The second call succeeds but the queue tags are not updated.
...

# Steps to reproduce

* Start localstack
* Create a topic with a given set of tags
* Create the same topic with a different set of tags.

## Command used to start LocalStack
Using `docker-compose up -d`. Here is the `docker-compose` file:
```yml
version: "3.6"

services:
  sns-sqs:
    container_name: the-container
    image: localstack/localstack-light
    environment:
      SERVICES: sns
    ports:
      - "4566:4566"
```
...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

The aforementioned NodeJs `aws-sdk` can also be done with `awscli` commands:
```shell
# Edge port or default SNS port makes no difference.
aws sns create-topic --endpoint-url http://localhost:4566 --name topic-1
# This succeeds, without updating the tags.
aws sns create-topic --endpoint-url http://localhost:4566 --name topic-1 --tags "Key=tagKey,Value=tagValue"
```
If you try the same commands on the real thing, you'll get this reply:
```shell
An error occurred (InvalidParameter) when calling the CreateTopic operation: Invalid parameter: Tags Reason: Topic already exists with different tags
```

...

**Comment by whummer** [comment]
Thanks for reporting @PhilLavoie . This should be fixed in #2482 - can you please give it a try with the `latest` version? Please report here if the problem persists. Thanks
