### ISSUE TITLE
Lambda is not able to interact with Dynamo DB

### ISSUE THREAD

**Issue by abhilashnarayanan** [localstack/localstack#2409]
# Type of request: This is a ...

[X] bug report
[ ] feature request

# Detailed description
I have lambda and dynamodb for my application. Lambda is written in go language and it polls record from dynamo db when ever it's triggered. We are getting error "Internalfailure 500 error code" from lambda when it tries to interact with dynamo
...

## Expected behavior
when lambda is invoked, it should successfully retrieve record from dynamodb
...

## Actual behavior
"Internalfailure 500 error code" from lambda when it tries to interact with dynamo
...

# Steps to reproduce
Provision lambda and dynamodb
Add data to dynamo
Invoke lambda 
## Command used to start LocalStack
docker-compose -f docker-compose.yaml up -d
...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
awslocal lambda invoke --function-name "lambda" --payload '{"test":"test"}' response.json
...

**Comment by whummer** [comment]
Thanks for reporting @abhilashnarayanan . Can you please share the details of your handler code file? Please note that you'll need to configure the DynamoDB SDK in your Lambda to use `LOCALSTACK_HOSTNAME:xxxx` as the endpoint (instead of `localhost:xxxx`, which is not accessible from within the Lambda). Thanks

**Comment by abhilashnarayanan** [comment]
Thanks @whummer for your response. After changing endpoint inside lambda code to LOCALSTACK_HOSTNAME:xxxx, lambda is able to interact with Dynamo. One question though, i have latest version of localstack (0.11.1) and when i tried to use endpoint having edge port say LOCALSTACK_HOSTNAME:4566 - it does not work. Only if i use dynamo port 4569 , lambda is able to communicate with dynamo table. May i know what is causing this issue?
I have docker-compose yaml file and golang code for the same below


````
version: "3.3"
services:
  localstack:
    # Using an older version of localstack due to various issues with connections being closed early in Terraform
    image: artifactory-dockerhub.cloud.capitalone.com/localstack/localstack:latest
    ports:
      - "4567-4597:4567-4597"
      - 8080:8080
    environment:
      - "DEBUG=1"
      - "SERVICES=lambda,dynamodb,kinesis,s3"
      - "DOCKER_HOST=unix:///var/run/docker.sock"
      - "LAMBDA_EXECUTOR=docker"
      - "LOCALSTACK_HOSTNAME=localstack"
      - "LAMBDA_DOCKER_NETWORK=localstack-tutorial"
    volumes:
      - "/tmp/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  localstack:

networks:
  default:
    external:
      name: localstack-tutorial
````


```
`		dynamo_sess, err := session.NewSession(&aws.Config{
                 Endpoint:aws.String("http://" + readEnvOrDefault("LOCALSTACK_HOSTNAME", "localstack") + ":4566"), [=> works only if i change the port to 4569]
			Region:      aws.String("us-east-1"),
			Credentials: credentials.NewStaticCredentials("test", "test", "test"),
		})
	dynamodbClient = dynamodb.New(dynamo_sess)`
```

**Comment by whummer** [comment]
Thanks for confirming the fix, @abhilashnarayanan . Can you please ensure that port `4566` is exposed in your docker-compose configuration:
```
      - "4566-4597:4566-4597"
```
Please let us know if there are any other issues. Thanks
