### ISSUE TITLE
Unable to create any aws resource using awslocal command in Jenkins stage

### ISSUE THREAD

**Issue by abhilashnarayanan** [localstack/localstack#2417]
# Type of request: This is a ...
[X] bug report
[ ] feature request

# Detailed description
Unable to create any aws resource for localstack via Jenkin Pipeline
...

## Expected behavior
awslocal command should provision aws resource for localstack container running inside jenkin agent
...

## Actual behavior
awslocal command throws an error " - MainThread - botocore.retryhandler - DEBUG - retry needed, retryable exception caught: Connection was closed before we received a valid response from endpoint URL: "http://localhost:4572/test-bucket".
...

# Steps to reproduce
Create stage in jenkin pipeline to install localstack, awslocal and other required things
Call jenkin stage to start localstack using docker-compose
execute awslocal to create s3 bucket

## Command used to start LocalStack
docker-compose up

...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
` docker-compose -f docker-compose.yaml up -d
  awslocal --endpoint-url="http://localhost:4572" s3 mb s3://test-bucket "`

Is there a way i can bypass proxy to use awslocal cli to interact with localhost and create resource for localstack

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-182) by [Unito](https://www.unito.io/learn-more)

**Comment by whummer** [comment]
Thanks for reporting @abhilashnarayanan . Looks like the S3 service is not accessible - is the port exposed in the docker-compose config? Please post the full contents of your docker-compose.yml here, as well as the full output logs of the LocalStack container. Thanks

**Comment by whummer** [comment]
@abhilashnarayanan Please make sure to provide sufficient time for the container to start up before using the `awslocal` command line (you can use the health check endpoint). Also, please note that the port numbers have changed - we're now using a single entry point (edge service) on port `4566`. Please report here if the problem persists. Thanks
