### ISSUE TITLE
ERROR: Could not connect to endpoint URL. 

### ISSUE THREAD

**Issue by ebalakumar** [localstack/localstack#2421]
# This is a bug report

# Detailed description

I am using Localstack to test my changes in local. My lambda function is supposed to perform putObject and create object in the s3 bucket. The functionality works fine when directly tested with AWS environment. But in Localstack, it's not working. I get error.

## Expected behavior

The lambda function should be able to make request to s3. 

## Actual behavior

`Could not connect to the endpoint URL: "http://localhost:4572/doyouknowme/pokemon.jpeg"     raise EndpointConnectionError(endpoint_url=request.url, error=e)ponset_exceptionlhost:4572/doyouknowme/pokemon.jpeg"`

# Steps to reproduce

AWS Credentials:
```
[default]
aws_access_key_id = AKI****************
aws_secret_access_key = gL************************
region = us-east-1
```

lambda function code (python):
```
import json
import urllib.parse
import boto3
import base64

print('Loading function')
# session = boto3.Session(profile_name='personal')
# s3 = session.client('s3', endpoint_url='http://localhost:4574')

s3 = boto3.client('s3', endpoint_url='http://localhost:4572', region_name='us-east-1')


def lambda_handler(event, context):
    # raise Exception('Something went wrong')
    print("Received event: " + json.dumps(event, indent=2))


    try:
        image_data = base64.b64decode(event['image_data'])
        response = s3.put_object(
            Body=image_data,
            Bucket='doyouknowme',
            Key='pokemon.jpeg',
            ContentType='image/jpeg'
        )

        print(response)
        return response

    except Exception as e:
        print(e)
        # print(
        #     'Error getting object {} from bucket {}. Make sure they exist and your bucket is in the same region as '
        #     'this function.'.format(
        #         key, bucket))
        raise e

```

## Command used to start LocalStack

localstack start

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

```
aws --endpoint-url=http://localhost:4574 lambda invoke --function-name lambda_s3 --payload fileb://lambda_upload_input.json response.json
```

**Comment by whummer** [comment]
Thanks for reporting @ebalakumar . Please note that using `localhost` does not work when running inside the Lambda Docker container. Can you please try using the `LOCALSTACK_HOSTNAME` environment variable, which should point to the target host name where the APIs are accessible. If you search the README and issues list on Github for "LOCALSTACK_HOSTNAME", you should be able to find several examples. Please report here if the problem persists. Thanks

**Comment by YousraMashkoor** [comment]
how do I access the environment variable inside the lambda function? for example I'm using python to connect with my s3 bucket so should this do the trick? `s3 = boto3.client('s3', endpoint_url='http://'+LOCALSTACK_HOSTNAME+':4572', region_name='us-east-1')` or do I need to access with environ for example?

**Comment by mgagliardo** [comment]
@YousraMashkoor to access env vars you should do `os.environ['LOCALSTACK_HOSTNAME']` if it's a python script.

For more information check this response (it's for JS but also valid for python) -> https://github.com/localstack/localstack/issues/3183#issuecomment-754317067

Also please try not to answer on issues that have almost a year closed, try to open a new one or refer to the documentation.
