### ISSUE TITLE
JSON Web Key Set is not available on edge service port 4566

### ISSUE THREAD

**Issue by richardlund** [localstack/localstack#2425]
# Type of request: This is a ...

[* ] bug report
[ ] feature request

# Detailed description
We need the Cognito-provided JWKS to be accessible and were expecting the keyset to be available via the newly introduced port edge service port (4566).
...

## Expected behavior
Expected that:

`GET http://localhost:4566/us-east-1_04b784c38fa04d53b30e7bdd18ae1749/.well-known/jwks.json`

would return a JSON Web Key Set representation

e.g. :

```
{"keys": [{"kty": "RSA", "alg": "RS256", "use": "sig", "kid": "test-key", "n": "pOnjsdrF6EC-a-6y3j2n61gZ1CV3clLKBxigypyn8qDHlNXePfdMXaoJNvnMRuql_aktOy-xdgwPaVA16o5hL8je12gRQWIWbkVrQxoBabejVKmIJtBv5gifuQyEbvxqXjMrrGPlFOkx2AiXG2sJg_TedmQ1SujsEKjObX6u9SNvjSrNs7f8zvo2f8bp-KuLPK2QrUFzTZbnGB2L5WMIjOVyRxAuPC3QYqnyQGdjrE5ykcMgGtbTakdzAndWC4GuGlrKp2WUI9cLUOnh2xGZe7VemmJnGxWqw5qOhqCPWDI6kvReqA89-a9yUAUUWI0rs36b6DQjeyQr35cxmE648Q", "e": "AQAB"}]}
```
...

## Actual behavior
Response is

```
{
"status": "running"
}
```
...

# Steps to reproduce
As above

## Command used to start LocalStack
Docker Compose config:

```
  localstack:
    image: localstack/localstack:0.11.1
    ports:
      - "443:443"
      - "4566-4607:4566-4607"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - DEBUG=1
      - SERVICES=edge, cognito
      - LOCALSTACK_API_KEY=********
    volumes:
      - "/tmp/localstack:/tmp/localstack"
```
...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
N/A
...

**Comment by whummer** [comment]
Thanks for reporting @richardlund . This should be fixed in the `latest` version - the `jwks.json` and other well-known files for Cognito should now be accessible through the edge port as well. Can you please do a `docker pull localstack/localstack` and give it a try with the latest version? Please report here if the problem persists. Thanks!
