### ISSUE TITLE
Multiserver not starting when port 51492 is in use

### ISSUE THREAD

**Issue by Zip753** [localstack/localstack#2426]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

Recently introduced multiserver is running on port 51492, which belongs to the range of ephemeral ports, which can be busy at virtually any time: https://en.wikipedia.org/wiki/Ephemeral_port

From time to time, the CI pipeline in our organization fails with Localstack configuration error, which we recently traced - port 51492 isn't available while attempting to start multiserver.

## Expected behavior

Multiserver would attempt to bind to a dynamic port if the default port is busy, or it would be a constant port outside the ephemeral port range, or it would be possible to configure such a port via an environment variable.

## Actual behavior

When port 51492 is busy, multiserver fails to start with the following error logs:
```
2020-05-14T08:45:08:INFO:localstack.multiserver: Starting multi API server process on port 51492
2020-05-14T08:45:08:ERROR:localstack.services.generic_proxy: Exception running proxy on port 51492: [Errno 98] Address in use Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 427, in run_cmd
    self.httpd = ThreadedHTTPServer((self.listen_host, self.port), GenericProxyHandler)
  File "/usr/lib/python3.8/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib/python3.8/http/server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.8/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address in use
```

# Steps to reproduce

## Command used to start LocalStack

Localstack is used via a Docker container, which is built on top of `localstack/localstack` container, and only customizes the configuration a bit - loading some default files to S3 on startup. Eventually, the entrypoint script just calls `/usr/bin/supervisord -c /etc/supervisord.conf` and starts the container as usual.

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

...

**Comment by whummer** [comment]
Thanks for reporting @Zip753 . This should be fixed in #2450 - can you please give it a try with the `latest` version? Please report here if the problem persists. Thanks
