### ISSUE TITLE
Containers not removed and lambda receives wrong records from dynamodb (same for free and pro)

### ISSUE THREAD

**Issue by atigm** [localstack/localstack#2428]
I use lambda function to synchronize ES from changes on dynamodb table (stream).
I use batchWrite() or save() to put 20 records on dynamodb, with that I have both problems : 

1. Lambda receives the first record as INSERT, but for others it receives always MODIFY, it always receives the same record more than 20 times.
1. When I use LAMBDA_EXECUTOR=docker-reuse, nothing happend (lambda function not revoked). But when I use  LAMBDA_EXECUTOR=docker with LAMBDA_REMOVE_CONTAINERS=true, the containers not removed.

I use this config : 

docker-compose.yaml

```
localstack:
    privileged: true
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566-4599:4566-4599"
      - "${PORT_WEB_UI-8081}:${PORT_WEB_UI-8081}"
      - "8090:8080"
    environment:
      - SERVICES=dynamodb,es,lambda,iam,s3,ses
      - DEBUG=1
      - PORT_WEB_UI=8081
      - LAMBDA_EXECUTOR=docker  # or docker-reuse
      - LAMBDA_REMOTE_DOCKER=true        # or false
      - LAMBDA_REMOVE_CONTAINERS=true
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DATA_DIR=/tmp/localstack/data
      - DEFAULT_REGION=eu-west-3
      - LAMBDA_DOCKER_NETWORK=localstack-network
      - LOCALSTACK_HOSTNAME=localstack
      - HOSTNAME=localstack
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./aws:/docker-entrypoint-initaws.d"   # for run script in container
    networks:
      - localstack-network
```

Thank you for help

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-184) by [Unito](https://www.unito.io/learn-more)

**Comment by whummer** [comment]
Thanks for reporting @ahafid1 - can you please verify that this issue still persists with the `latest` version? If you could help us and provide a code snippet or project with a small, isolated example to help reproduce this issue, that would be great. Thanks!

**Comment by whummer** [comment]
Closing as resolved/outdated - please let us know if the problem persists.. Thanks!
