### ISSUE TITLE
Rest client http put returns "Not Found" error when adding S3 file

### ISSUE THREAD

**Issue by katehowe** [localstack/localstack#2430]
# Type of request:  

  bug report

# Detailed description

Performing http put request to http://localstack:{port_number}/{bucketname}/{file} returns "**Not Found**". 

docker-compose.yml:
services:
  localstack:
    image: localstack/localstack:0.11.0
    environment:
      - DEFAULT_REGION=eu-west-1
      - SERVICES=s3,secretsmanager
    ports:
      - "8016:4566"

Adding files to S3 via SDK works fine but put request to http://localstack:8016/{bucketname}/{file} returns "not found"

The problem goes away when explicitly specifying ports for localstack services:
    environment:
      - DEFAULT_REGION=eu-west-1
      - SERVICES=s3:**8016**,secretsmanager:**8017**
    ports:
      - "8016:8016"
      - "8017:8017"

## Expected behavior

Should be able to use one port 4566 for all services and be able add files to S3 via http requests 

## Actual behavior

 http put request to http://localstack:{port_number}/{bucketname}/{file} returns "Not Found". 

## Command used to start LocalStack

docker-compose up -d
.

**Comment by whummer** [comment]
Thanks for reporting @katehowe . This should be fixed in the meantime - can you please give it a try with `localstack/localstack:latest` or the `localstack/localstack:0.11.2` Docker image? Please report here if the problem persists. Thanks!
