### ISSUE TITLE
sqs aws command issue when LOCALSTACK_API_KEY is added

### ISSUE THREAD

**Issue by jmcgrath207** [localstack/localstack#2433]
[ X] bug report
[ ] feature request

# Detailed description

When I added the Environmental Variable LOCALSTACK_API_KEY in docker compose it makes certain aws command line stop working. 

```
$ aws sqs send-message --endpoint-url=http://localhost:4576 --queue-url http://localhost:4576/queue/fluentd-parsed-queue --message-body '{"test":"message"}'

An error occurred (AWS.SimpleQueueService.NonExistentQueue) when calling the SendMessage operation: AWS.SimpleQueueService.NonExistentQueue; see the SQS docs.

$ aws sqs receive-message --endpoint-url=http://localhost:4576 --queue-url http://localhost:4576/queue/fluentd-parsed-queue

An error occurred (AWS.SimpleQueueService.NonExistentQueue) when calling the ReceiveMessage operation: AWS.SimpleQueueService.NonExistentQueue; see the SQS docs.

```

If I remove the LOCALSTACK_API_KEY Environmental Var they work again. 

```
$ aws sqs send-message --endpoint-url=http://localhost:4576 --queue-url http://localhost:4576/queue/fluentd-parsed-queue --message-body '{"test":"message"}'
{
    "MD5OfMessageBody": "a2f6891e0965c933f2c876bdf0dcb441",
    "MessageId": "30c9622c-6f5c-4156-b66b-5c0404425a3c"
}


$ aws sqs receive-message --endpoint-url=http://localhost:4576 --queue-url http://localhost:4576/queue/fluentd-parsed-queue

{
    "Messages": [
        {
            "MessageId": "30c9622c-6f5c-4156-b66b-5c0404425a3c",
            "ReceiptHandle": "30c9622c-6f5c-4156-b66b-5c0404425a3c#ede040ae-d49b-45e9-871f-f6c1ea2fdbc4",
            "MD5OfBody": "a2f6891e0965c933f2c876bdf0dcb441",
            "Body": "{\"test\":\"message\"}"
        }
    ]
}
```

This does not appear to effect the true functionality of local stack's SQS since python's Boto3 and ruby's aws-sdk-sqs can add and receive messages to the queue. You can also see the resources in the web GUI just fine too.

**Comment by whummer** [comment]
Thanks for reporting @jmcgrath207 . Please note that the open source LocalStack is single-region (i.e., uses a single region defined in `DEFAULT_REGION`, or `us-east-1` by default), whereas the Pro version contains multi-region support, which means that resources are created in different regions, corresponding to the region configuration specified in the client SDK. Note that this is more in line with real AWS.

My assumption would be that the behavior you're seeing could be related to a region mismatch. Can you please double check which region your resources get created, and whether there is a mismatch in the regions? Specifically, does the terminal session that creates the SQS queue use a different environment configuration (`AWS_DEFAULT_REGION`) than the terminal session where you're running `aws sqs send-message`? We'll be happy to look more into this issue, but would be great to get some help on how to reproduce this issue. Thanks for your help!

**Comment by whummer** [comment]
Closing this issue for now (assuming that this is related to a region mismatch issue), but please feel free to reopen if more details become available that will help us reproduce the issue.

Please note that recently we have also made substantial changes to the backend implementation of the SQS API, so the behavior you're seeing may/should (hopefully) be more consistent now.

Hope that helps, please keep us posted how it goes. Thanks
