### ISSUE TITLE
EC2 Reserved Instances - 500 error

### ISSUE THREAD

**Issue by vasiliy-sharko** [localstack/localstack#2435]
[X ] bug report
[ ] feature request

# Detailed description

Commans that are used to purchase EC2 reserved instances produce 500 error:
 
```
$ aws ec2 describe-reserved-instances-offerings                                                                               

Unable to parse response (syntax error: line 1, column 54), invalid XML received. Further retries may succeed:
b'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">\n<title>500 Internal Server Error</title>\n<h1>Internal Server Error</h1>\n<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>\n'
```

## Expected behavior

CLI commands behave as described in [AWS documentation](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ri-market-concepts-buying.html)

# Steps to reproduce

Any of the following commands produce similar output, no matter what additional flags I use:

```
aws ec2 describe-reserved-instances-offerings ...
aws ec2 purchase-reserved-instances-offering ...
aws ec2 describe-reserved-instances ...
```

## Command used to start LocalStack

`docker run -d -e TEST_AWS_ACCOUNT_ID="000000000000" -e LOCALSTACK_HOSTNAME="localhost" -e DEFAULT_REGION="us-east-1" --rm --privileged --name localstack_main -p 8080-8081:8080-8081 -p 4566-4620:4566-4620 -p 10000:10000 -v "/tmp/localstack:/tmp/localstack" -v "/var/run/docker.sock:/var/run/docker.sock" -e DOCKER_HOST="unix:///var/run/docker.sock" -e HOST_TMP_FOLDER="/tmp/localstack" "localstack/localstack"`

**Comment by whummer** [comment]
Thanks for reporting @vasiliy-sharko . A simple version of mocked responses has been added in #2458 - can you please give it a try with the latest version? There's also an upstream issue in `moto` (which we're using for EC2 under the covers) that you can follow here: https://github.com/spulec/moto/issues/1741 . Thanks!
