### ISSUE TITLE
SNS publish does not work with aws-sdk-java 2.11.8

### ISSUE THREAD

**Issue by 2ndalpha** [localstack/localstack#2438]
[x ] bug report
[ ] feature request

# Detailed description

Newest version of AWS SDK (`2.11.8`) for Java sends data as query parameters when invoking SNS publish.
Older version (`2.10.23`) sent it all as a body.
Both versions of the SDK work fine with AWS servers but localstack fails with status 404.
## Expected behavior

Localstack is able to handle data as query parameters.

## Actual behavior

Localstack returns 404.
From logs
```
2020-05-18 14:40:31,712:API: 127.0.0.1 - - [18/May/2020 14:40:31] "POST /?Action=Publish&Version=2010-03-31&TopicArn=arn%3Aaws%3Asns%3Aeu-west-1%3A000000000000%3AXXX&Message=YYY HTTP/1.1" 404
```
# Steps to reproduce

## Command used to start LocalStack

Latest localstack Docker image

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

```kotlin
val request = PublishRequest.builder()
            .topicArn("x")
            .message("y")
            .build()
snsClient.publish(request)
```

**Comment by whummer** [comment]
Thanks for reporting @2ndalpha . This should be fixed in #2583 - can you please give it a try with the `latest` version of the Docker image? Please report here if the problem persists. Thanks
