### ISSUE TITLE
DynamoDB: Allow empty strings and binary values

### ISSUE THREAD

**Issue by MickL** [localstack/localstack#2443]
DynamoDB now supports empty strings and binary values: 

https://aws.amazon.com/about-aws/whats-new/2020/05/amazon-dynamodb-now-supports-empty-values-for-non-key-string-and-binary-attributes-in-dynamodb-tables/?nc1=h_ls

But with LocalStack I get:
> One or more parameter values were invalid: An AttributeValue may not contain an empty string

**Comment by whummer** [comment]
Thanks for reporting @MickL . This should be fixed in #2625 - can you please give it a try with the `latest` version of the Docker image? Please report here if the problem persists. Thanks
