### ISSUE TITLE
Fix return statusCode on deleteAlarms method

### ISSUE THREAD

**Issue by bahui80** [localstack/localstack#2447]
# Type of request: This is a ...

[X] bug report
[ ] feature request

# Detailed description
Nowadays there is a small difference in the return status code of the CloudWatch method `deleteAlarms(DeleteAlarmsRequest deleteAlarmsRequest)`. In AWS if DeleteAlarmsRequest() is a new empty object, it returns 400, whereas in localstack it returns 200.
...

## Expected behavior
When doing the following call to AWS using localstack, a 400 error should be get (AWS returns that):
```
DeleteAlarmsRequest currentBatch = new DeleteAlarmsRequest();
amazonCloudWatch.deleteAlarms(deleteAlarmsRequest);
```

## Actual behavior
When doing the following call to AWS using localstack, a 200 error should is get:
```
DeleteAlarmsRequest currentBatch = new DeleteAlarmsRequest();
amazonCloudWatch.deleteAlarms(deleteAlarmsRequest);
```

# Steps to reproduce
Create a connection to amazonCloudWatch and execute the following code:
```
DeleteAlarmsRequest currentBatch = new DeleteAlarmsRequest();
amazonCloudWatch.deleteAlarms(deleteAlarmsRequest);
```

**Comment by whummer** [comment]
Thanks for reporting @bahui80 . This should be fixed in https://github.com/spulec/moto/pull/3028 - can you please give it a try with the `latest` version of the Docker image? Please report here if the problem persists. Thanks!
