### ISSUE TITLE
Permission denied on docker-entrypoint.sh when running it for the first time

### ISSUE THREAD

**Issue by baskwo** [localstack/localstack#2452]
# Type of request: This is a bug report

# Detailed description
I'm new to localstack and when I tried to run it, I'm having an error.
It seems the docker container doesn't use the right user 
```/bin/bash: /usr/local/bin/docker-entrypoint.sh: Permission denied```

## Expected behavior
Run as expected.

## Actual behavior
Crash with a ```Permission denied``` exception.

# Steps to reproduce

1. ```pip3 install localstack```
2. ```localstack start```

## Command used to start LocalStack
```localstack start```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
N/A

**Comment by whummer** [comment]
Thanks for reporting this issue @baskwo . Can you please post the output of the command below. It should be something like this (note the executable flags, marked as `x`):

```
$ docker run --entrypoint= localstack/localstack ls -la /usr/local/bin/docker-entrypoint.sh
-rwxrwxr-x    1 root     root           898 May 24 17:20 /usr/local/bin/docker-entrypoint.sh
```

**Comment by baskwo** [comment]
Hi, thanks for the reply.
I have the same result as you :
```-rwxrwxr-x    1 root     root           898 May 24 17:20 /usr/local/bin/docker-entrypoint.sh```

As it is supposed to be executable as any user, I tried to see what is inside the file.
So I ran ```docker run -ti -u root --rm --entrypoint=/bin/bash localstack/localstack``` to have a terminal inside the container and when I try to do ```cat /usr/local/bin/docker-entrypoint.sh``` I still get a Permission Denied error as a root user.

**Comment by whummer** [comment]
Thanks for the update. Hm, that sounds like a general Docker issue. Can you `cat` any of the other files in the container, or are you getting a Permission Denied on all of them?

**Comment by baskwo** [comment]
I tried many files and I do have a Permission Denied on all of them!

**Comment by baskwo** [comment]
I found this issue https://forum.snapcraft.io/t/docker-fails-with-permission-denied-inside-containers/17602/5

I am using docker with snap so I will try using docker-ce in apt instead of snap.

**Comment by baskwo** [comment]
I just tried again with docker.io installing from apt instead of snap and everything works.
I guess we can close this issue as it is not related to localstack :)

**Comment by whummer** [comment]
Great, thanks you were able to figure it out!
