### ISSUE TITLE
{     "Version": "2012-10-17",     "Statement": [         {             "Sid": "ManageOwnAccessKeys",             "Effect": "Allow",             "Action": [                 "iam:CreateAccessKey",                 "iam:DeleteAccessKey",                 "iam:GetAccessKeyLastUsed",                 "iam:GetUser",                 "iam:ListAccessKeys",                 "iam:UpdateAccessKey"             ],             "Resource": "arn:aws:iam::*:user/${aws:username}"         }     ] }

### ISSUE THREAD

**Issue by pay02232** [localstack/localstack#2459]
# Type of request: This is a ...

[ ] bug report
[ ] feature request

# Detailed description

...

## Expected behavior

...

## Actual behavior

...

# Steps to reproduce

## Command used to start LocalStack

...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

...

**Comment by whummer** [comment]
Not sure how to interpret this request - closing. Please add more details and steps to reproduce. Thanks
