### ISSUE TITLE
EventBridge Unsupported Events rule target ARN

### ISSUE THREAD

**Issue by alyyousuf7** [localstack/localstack#2460]
I'm trying to create an Event Rule to trigger an SNS Topic. The topic is subscribed to something else.

I'm doing this with the following setup:
```bash
aws sns create-topic \
  --name MyNotification && \
aws sns subscribe \
  --topic-arn arn:aws:sns:us-east-1:000000000000:MyNotification \
  --protocol http \
  --notification-endpoint http://myservice/endpoint

aws events put-rule \
  --name MyEventRule \
  --schedule-expression "rate(1 minutes)" && \
aws events put-targets \
  --rule MyEventRule \
  --targets "Id"="MyEventTarget","Arn"="arn:aws:sns:us-east-1:000000000000:MyNotification"
```

When I publish anything to SNS, I get an HTTP request on my server. So that's working fine.

I don't get an HTTP request every minute (EventBridge), but I get the following log on my localstack every minute:
```
INFO:localstack.services.events.events_listener: Unsupported Events rule target ARN "arn:aws:sns:us-east-1:000000000000:MyNotification"
```

**Comment by whummer** [comment]
Thanks for reporting @alyyousuf7 . This should be fixed in #2468 - can you please give it a try with the `latest` version? Please report here if the problem persists. Thanks

**Comment by alyyousuf7** [comment]
https://hub.docker.com/r/localstack/localstack/tags says that the image was updated 6hr ago. I'm assuming image with this changes is not pushed yet.

**Comment by whummer** [comment]
Good point, thanks @alyyousuf7 . We had some issues with our CI pipeline - the `latest` image should be pushed now. 👍

**Comment by alyyousuf7** [comment]
It's working perfectly fine.

Thanks for adding the functionality and making it available pretty quickly!
