### ISSUE TITLE
cannot start elasticsearch after installing opendistro_sql plugin

### ISSUE THREAD

**Issue by sramli** [localstack/localstack#2462]
# Type of request: This is seemingly a bug of installing a new es pluging 

# Detailed description : 
I've installed and ran localstack using docker way , and I have the obligation of using opendistro_sql pluging 
https://opendistro.github.io/for-elasticsearch-docs/docs/install/plugins/#sql

So, since i did not found a ready-to-use feature to install the plugin , then I tried to do it by accessing the related docker container of local statck : 

* docker exec -it localstack_demo bash
* cd /opt/code/localstack/localstack/infra/elasticsearch/bin/
* ./elasticsearch-plugin install  elasticsearch-sql-7.1.0.0.zip
-> Installed sql

* then I double check the instalation : 
./elasticsearch-plugin list 
analysis-icu
analysis-kuromoji
analysis-phonetic
analysis-smartcn
analysis-stempel
analysis-ukrainian
ingest-attachment
mapper-murmur3
mapper-size
sql

## Expected behavior
The expected behavior is to get the embedded localstack's elasticsearch working fine with the said sql plugin 

## Actual behavior

after restarting localstack docker container , the elasticsearch service is no longer available..

**Comment by whummer** [comment]
Thanks for reporting @sramli . Please note that Elasticsearch has been refactored recently.

We were able to reproduce the issue. A quick Google search revealed that there is an incompatibility between the SQL plugin and some other built-in SQL features.

This seems to work:
```
$ awslocal es create-elasticsearch-domain --domain-name dom1
...
$ docker exec -it localstack_main bash
# cd /tmp/localstack/elasticsearch/7.1.0
# bin/elasticsearch-plugin install https://github.com/NLPchina/elasticsearch-sql/releases/download/7.1.0.0/elasticsearch-sql-7.1.0.0.zip
# bin/elasticsearch-plugin list
...
sql
# echo 'xpack.sql.enabled: false' >> config/elasticsearch.yml
```
Then restart the container, re-create the ES domain, and it should work. Please report here if the problem persists. Thanks
