### ISSUE TITLE
[docker] lost my config after docket restart

### ISSUE THREAD

**Issue by GuigZ-** [localstack/localstack#2463]
# Type of request: This is a ...

[*] bug report
[ ] feature request

# Detailed description

Hi, 

I work on localstack since few days, but I do not understand why after stop my locals ack container, I lost all topics in SQS. 

## Expected behavior

The expected behavior is to get the embedded localstack's sqs working fine. 

Actual  

## Actual behavior

When I restart my container, I lost my queues on sqs.

**Comment by GuigZ-** [comment]
I close my issue, with the last docker image, it's work.

Thanks for your job

**Comment by GuigZ-** [comment]
Today, i've a same problem with my s3, no document has been persist after docker stop and up. :(

**Comment by GuigZ-** [comment]
Okay I understand, the up is long because I use longpool on multiple micro service. And reset call is too long.

So for the sns topic, I have a bug. No sns topic are re up.

**Comment by GuigZ-** [comment]
@whummer sorry for the ping, you have an idea ? if you want i can try to understand and open pr. but i think you are so fastest than me.

**Comment by whummer** [comment]
Thanks for reporting @GuigZ- . Please note that persistence is disabled by default - i.e., all changes will be lost if you restart the LocalStack container. You can enable persistence by setting the `DATA_DIR` environment variable - please see the instructions in the README. Note that persistence is currently only supported for a subset of the APIs (not all of them).

Please let us know if that works for you - if not, then please add any error messages or detailed instructions on how to reproduce the issue. Thanks

**Comment by GuigZ-** [comment]
@whummer i open the pr, it's work for me on my local. 

Every request on sns should be not persist

**Comment by whummer** [comment]
Thanks again - PR #2505 has been merged.
