### ISSUE TITLE
Redshift: Datagrip can't connect to localhost cluster

### ISSUE THREAD

**Issue by xCloudx8** [localstack/localstack#2466]
# Detailed description
When starting localstack with Redshift service i can't connect to it via Datagrip at all giving me the following error: Error setting/closing connection: UnknownHostException. 
I'm getting the endpoint url by using the describe-clusters command.

## Expected behavior
Connect's to the mocked service Redshift

## Actual behavior
Do not connect giving unknown host exception

# Steps to reproduce
## Command used to start LocalStack
docker-compose up localstack

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
aws redshift --endpoint-url=http://localhost:4566 create-cluster --node-type dw.hs1.xlarge --number-of-nodes 2 --master-username redshift --master-user-password password --cluster-identifier localhost --publicly-accessible

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-188) by [Unito](https://www.unito.io/learn-more)

**Comment by xCloudx8** [comment]
Actually what i'm trying to achieve is to connect  to Redshift  mocked locally via Datagrip and do simple queries. Is that possible? Am i doing something unachievable?

**Comment by anadepaula** [comment]
I was also searching for a way to do this, but according to #833 this is not feasible yet using localstack only.
