### ISSUE TITLE
405 Method Not Allowed - Lambda GetLayerVersion method

### ISSUE THREAD

**Issue by mikecramergraze** [localstack/localstack#2469]
# Type of request: This is a ...

[ x ] bug report
[ ] feature request

# Detailed description

When calling localstack (Pro) lambda GetLayerVersion API method, 405 Method Not Allowed response is returned, due to the fact that GET is not an allowed verb for this path. Only OPTIONS, DELETE have been enabled.

https://docs.aws.amazon.com/lambda/latest/dg/API_GetLayerVersion.html

This prevents being able to use Terraform to handle lambda layers as the GetLayerVersion API call is made by Terraform during creation.

## Expected behavior

200 is returned with valid API response.

## Actual behavior

A 405 is returned:

```
An error occurred (405) when calling the GetLayerVersion operation: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>405 Method Not Allowed</title>
<h1>Method Not Allowed</h1>
<p>The method is not allowed for the requested URL.</p>
```

# Steps to reproduce
1. Publish a new lambda layer 
2. Call aws get-layer-version cli command

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

```
awslocal lambda publish-layer-version --layer-name somelayer --zip-file fileb://path/to/file.zip
awslocal lambda get-layer-version --layer-name somelayer --version-number 1
```

**Comment by whummer** [comment]
Thanks for reporting this issue @mikecramergraze . Can you please do a `docker pull localstack/localstack` and give it a try with the latest version of the Docker image? This should be (hopefully) fixed in the meantime. Please let us know if the problem persists. Thanks!
