### ISSUE TITLE
Windows Pathing Issue with Volume Sharing Lambdas

### ISSUE THREAD

**Issue by benleim** [localstack/localstack#2472]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description
When `mountCode: true` for a serverless.yml deployment to localstack on Windows, Localstack mounts the wrong path.
...

## Expected behavior
Docker expects the Windows client path value of the `-v` flag to begin with `/host_mtn/`.
...

## Actual behavior
Localstack does not add this to the Windows client path. This causes the volume sharing to fail. Once one tries to invoke a lambda without the proper volume sharing, the lambda fails with an error along the lines of "can't find no module 'lambda_name'".
...

# Steps to reproduce
1. In your `serverless.yml` set `mountCode: true` 
2. In your `docker-compose.yml` set the environment variable `LAMBDA_REMOTE_DOCKER: "0"` for the localstack container
3. Deploy some test lambda to the localstack container
4. Attempt to invoke with `awslocal lambda invoke --function-name LAMBDA_NAME out.txt` and replace LAMBDA_NAME with the name of your test lambda.
5. Note the invocation failure.

## Command used to start LocalStack
Started via a `docker-compose.yml` file. Pretty basic stuff.
...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
Just the `awslocal` invoke command outlined above.
...

**Comment by benleim** [comment]
I have a fix for this and will be issuing a PR shortly.

**Comment by whummer** [comment]
Thanks for contributing the fix @benleim 👍
