### ISSUE TITLE
Getting Authentication error

### ISSUE THREAD

**Issue by mirzawaqasahmed** [localstack/localstack#2475]
# Type of request: This is an issue

[x] bug report
[ ] feature request

# Detailed description
Setup a localstack using provider docker-compose and default configuration given [https://www.terraform.io/docs/providers/aws/guides/custom-service-endpoints.html#localstack](url)

When running a simple `aws_instance` resource, the `terraform plan` works. However, `terraform apply` doesnt work.
Throws and error like this below.
As you can see its able to apply `aws_iam_user` resource but not `aws_instance` resource.

```
aws_iam_user.lb: Refreshing state... [id=demouser]
aws_instance.myec2: Creating...

Error: Error launching source instance: AuthFailure: AWS was not able to validate the provided access credentials
        status code: 401, request id: 7d52d197-f256-4b0d-baff-58cf30579bf4

  on main.tf line 1, in resource "aws_instance" "myec2":
   1: resource "aws_instance" "myec2" {
```
Am I missing anything or is it really an error?
...

## Expected behavior
The terraform resource should be applied and not authentication error.
...

## Actual behavior
Throwing error:

```
aws_iam_user.lb: Refreshing state... [id=demouser]
aws_instance.myec2: Creating...

Error: Error launching source instance: AuthFailure: AWS was not able to validate the provided access credentials
        status code: 401, request id: 7d52d197-f256-4b0d-baff-58cf30579bf4

  on main.tf line 1, in resource "aws_instance" "myec2":
   1: resource "aws_instance" "myec2" {
```
...

# Steps to reproduce

## Command used to start LocalStack

`TMPDIR=/private$TMPDIR docker-compose up -d`
...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
```
provider "aws" {
  access_key                  = "mock_access_key"
  region                      = "us-east-1"
  s3_force_path_style         = true
  secret_key                  = "mock_secret_key"
  skip_credentials_validation = true
  skip_metadata_api_check     = true
  skip_requesting_account_id  = true

  endpoints {
    apigateway     = "http://localhost:4567"
    cloudformation = "http://localhost:4581"
    cloudwatch     = "http://localhost:4582"
    dynamodb       = "http://localhost:4569"
    es             = "http://localhost:4578"
    firehose       = "http://localhost:4573"
    iam            = "http://localhost:4593"
    kinesis        = "http://localhost:4568"
    lambda         = "http://localhost:4574"
    route53        = "http://localhost:4580"
    redshift       = "http://localhost:4577"
    s3             = "http://localhost:4572"
    secretsmanager = "http://localhost:4584"
    ses            = "http://localhost:4579"
    sns            = "http://localhost:4575"
    sqs            = "http://localhost:4576"
    ssm            = "http://localhost:4583"
    stepfunctions  = "http://localhost:4585"
    sts            = "http://localhost:4592"
  }
}
```

```
resource "aws_instance" "myec2" {
   ami = "ami-09d95fab7fff3776c"
   instance_type = "t2.micro"
}

resource "aws_iam_user" "lb" {
  name = "demouser"
  path = "/system/"
}
```
...

**Comment by usmangani1** [comment]
> # Type of request: This is an issue
> [x] bug report
> [ ] feature request
> 
> # Detailed description
> Setup a localstack using provider docker-compose and default configuration given [https://www.terraform.io/docs/providers/aws/guides/custom-service-endpoints.html#localstack](url)
> 
> When running a simple `aws_instance` resource, the `terraform plan` works. However, `terraform apply` doesnt work.
> Throws and error like this below.
> As you can see its able to apply `aws_iam_user` resource but not `aws_instance` resource.
> 
> ```
> aws_iam_user.lb: Refreshing state... [id=demouser]
> aws_instance.myec2: Creating...
> 
> Error: Error launching source instance: AuthFailure: AWS was not able to validate the provided access credentials
>         status code: 401, request id: 7d52d197-f256-4b0d-baff-58cf30579bf4
> 
>   on main.tf line 1, in resource "aws_instance" "myec2":
>    1: resource "aws_instance" "myec2" {
> ```
> 
> Am I missing anything or is it really an error?
> ...
> 
> ## Expected behavior
> The terraform resource should be applied and not authentication error.
> ...
> 
> ## Actual behavior
> Throwing error:
> 
> ```
> aws_iam_user.lb: Refreshing state... [id=demouser]
> aws_instance.myec2: Creating...
> 
> Error: Error launching source instance: AuthFailure: AWS was not able to validate the provided access credentials
>         status code: 401, request id: 7d52d197-f256-4b0d-baff-58cf30579bf4
> 
>   on main.tf line 1, in resource "aws_instance" "myec2":
>    1: resource "aws_instance" "myec2" {
> ```
> 
> ...
> 
> # Steps to reproduce
> ## Command used to start LocalStack
> `TMPDIR=/private$TMPDIR docker-compose up -d`
> ...
> 
> ## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
> ```
> provider "aws" {
>   access_key                  = "mock_access_key"
>   region                      = "us-east-1"
>   s3_force_path_style         = true
>   secret_key                  = "mock_secret_key"
>   skip_credentials_validation = true
>   skip_metadata_api_check     = true
>   skip_requesting_account_id  = true
> 
>   endpoints {
>     apigateway     = "http://localhost:4567"
>     cloudformation = "http://localhost:4581"
>     cloudwatch     = "http://localhost:4582"
>     dynamodb       = "http://localhost:4569"
>     es             = "http://localhost:4578"
>     firehose       = "http://localhost:4573"
>     iam            = "http://localhost:4593"
>     kinesis        = "http://localhost:4568"
>     lambda         = "http://localhost:4574"
>     route53        = "http://localhost:4580"
>     redshift       = "http://localhost:4577"
>     s3             = "http://localhost:4572"
>     secretsmanager = "http://localhost:4584"
>     ses            = "http://localhost:4579"
>     sns            = "http://localhost:4575"
>     sqs            = "http://localhost:4576"
>     ssm            = "http://localhost:4583"
>     stepfunctions  = "http://localhost:4585"
>     sts            = "http://localhost:4592"
>   }
> }
> ```
> 
> ```
> resource "aws_instance" "myec2" {
>    ami = "ami-09d95fab7fff3776c"
>    instance_type = "t2.micro"
> }
> 
> resource "aws_iam_user" "lb" {
>   name = "demouser"
>   path = "/system/"
> }
> ```
> 
> ...
@mirzawaqasahmed aws_instance is a method corresponding to aws ec2 and in the end points map ,the end point targeting the localstack ec2 is missing.So the request is being sent to actual aws and hence the issue.Adding the below localstack ec2 target end point to the end points map should resolve the issue.

ec2            = "http://localhost:4597"

Please try this and let us know in case if you still face the issue with this.Thanks

**Comment by whummer** [comment]
Thanks for reporting @mirzawaqasahmed , and thanks for providing a clarification @usmangani1 . Looks like this is a configuration issue that can be resolved by setting the ec2 endpoint in the TF script. Please report here if the problem persists. Thanks!
