### ISSUE TITLE
Any tips for troubleshooting SES pro functionality?

### ISSUE THREAD

**Issue by LouisStAmour** [localstack/localstack#2476]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description
I’ve tried to use either the documented SMTP variables or the JSON API /_messages_ endpoint and neither returns messages.

Localstack via Docker compose, there’s a message that scrolls by saying I’m licensed for pro. I’ve verified my from email address using a startup script. No issues at AWS CLI when sending using SES, I get a message ID back. But I can never view the messages, `:443/_messages_` endpoint as used by localstack cloud only returns { status: running } and the SMTP catch-all I set up using Inbucket doesn’t receive any emails from Localstack. DEBUG=1 is on, I don’t see any errors except Unable to find forwarding rule for host “localhost” (or “localstack”, I tried both), path `/_messages_?email=...`

I can confirm the logs say “Successfully activated API key” before the SES service loads. I tried removing services variable to run them all, still didn’t help.

Localstack 0.11.2 the logs say, via docker
...

## Expected behavior
SES emails shouldn’t be going into a black hole, Localstack documented pro functionality should work.
...

## Actual behavior
SES emails are stored memory-only at best?
...

**Comment by whummer** [comment]
Thanks a lot for reporting this issue @LouisStAmour . The `:443/_messages_` endpoint should be fixed in the `latest` version - can you please do a `docker pull localstack/localstack` and give it another try? Please report here if the problem persists. Thanks!
