### ISSUE TITLE
Installation on Mac OS fails

### ISSUE THREAD

**Issue by tobilg** [localstack/localstack#248]
When trying to install (via `pip install localstack`) on Mac OS Sierra, I see the following error message:

```bash
  Found existing installation: six 1.4.1
    DEPRECATION: Uninstalling a distutils installed project (six) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling six-1.4.1:
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_set.py", line 778, in install
    requirement.uninstall(auto_confirm=True)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_install.py", line 754, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 131, in copy2
    copystat(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 103, in copystat
    os.chflags(dst, st.st_flags)
OSError: [Errno 1] Operation not permitted: '/var/folders/mm/34z901_s7lxbsc4l73xsj0940000gn/T/pip-wqy0V9-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six-1.4.1-py2.7.egg-info'
```

**Comment by whummer** [comment]
Thanks for reporting @tobilg . This looks like an issue with permissions on the file system. This sometimes happens when you've been running `pip install` commands as `root`/`sudo` in the past, and then try to install new packages with a normal (non-root) system user.
Can you please try the following commands, and post the output here:
```
ls -la /var/folders/mm/34z901_s7lxbsc4l73xsj0940000gn/T/pip-wqy0V9-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six-1.4.1-py2.7.egg-info
sudo chmod -R 777 /var/folders/mm/34z901_s7lxbsc4l73xsj0940000gn/T/pip-wqy0V9-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/
pip install localstack
```
Thanks

**Comment by tobilg** [comment]
Thanks @whummer. Unfortunately it doesn't work as well and fails with the same error message.

**Comment by dinhtuan1991vt** [comment]
Can you try `pip install localstack --upgrade --ignore-installed six`?

**Comment by p1ng** [comment]
I was able to get this installed on MacOS Sierra with the following:

Uninstall old version of pip (if necessary)
`sudo pip uninstall pip`

Install python from brew
`brew install python`

Make sure pip is working after brew install
`which pip`

If not, run this
`brew unlink python && brew link python`

To resolve permission errors, I ran install with the `--user` flag
`pip install --user localstack`

**Comment by jeson114** [comment]
+1

**Comment by tobilg** [comment]
@dinhtuan1991vt it still fails unfortunately. Error message is

> IOError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/six.py'

**Comment by ssabnis** [comment]
I had the same issue, moved to VirtualBox and CentOS 7 VM, works great, no issue and also keeps mac clean and I can retry setup many times of messed up

**Comment by whummer** [comment]
@tobilg Sems like this could be related to #260, maybe this solution works for you: https://github.com/localstack/localstack/issues/260#issuecomment-334458631

**Comment by tobilg** [comment]
I could successfully install localstack with the method @whummer linked:

`pip install --user localstack`

**Comment by rv-rsouza** [comment]
`pip install --user localstack` Did the trick.

This should be added to the README file.

**Comment by bagada** [comment]
I had this error

_awsebcli 3.14.1 has requirement six==1.11.0, but you'll have six 1.10.0 which is incompatible.
awscli 1.15.40 has requirement botocore==1.10.40, but you'll have botocore 1.10.41 which is incompatible._

Then  I understood that problem was awsebcli and awscli
First uninstall both

**pip3 uninstall awsebcli 
pip3 uninstall awscli**

After, install localstack

**pip3 install  localstack**

That works for me.

**Comment by Berns89** [comment]
doesn't matter what I do I get localstack version 0.13.0.11 when running localstack --version on mac os,  have tried upgrading, I have tried brew uninstall. Nothing seems to help, any help appreciate
