### ISSUE TITLE
Lambda: Support for limits such as timeout, memory or concurrent executions?

### ISSUE THREAD

**Issue by mg98** [localstack/localstack#2483]
The documentation does not say much about the supported limits, which have great importance for the simulation quality imo.

Can someone tell me how these are currently supported in LocalStack Lambda?

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-191) by [Unito](https://www.unito.io/learn-more)

**Comment by recharge-dreams** [comment]
adfkj

**Comment by jamietanna** [comment]
I looked at this as part of diagnosing my slow runs of my tests (related: #4123) and found that it's currently hardcoded to have a concurrency lock, so only one Lambda can execute at a time.

It'd be really great to have this to scale i.e. 4, as it'd allow for folks to more meaningfully parallelise their tests

**Comment by dfangl** [comment]
Hi!
Please try using `PROVIDER_OVERRIDE_LAMBDA=asf`, our new provider has support for multiple concurrent environments for each lambda, and is way better performance wise. It also has support for timeouts.

Memory and concurrent executions are as of now still missing, but will be supported in the future.

**Comment by joe4dev** [comment]
@mg98 @jamietanna LocalStack 2.0 offers a [completely rewritten implementation](https://discuss.localstack.cloud/t/new-lambda-implementation-in-localstack-2-0/258) of [Lambda](https://docs.localstack.cloud/user-guide/aws/lambda/). It supports timeouts, concurrent executions, and even advanced [Lambda concurrency features](https://docs.aws.amazon.com/lambda/latest/dg/lambda-concurrency.html). Does this cover your scenarios?

## Memory Limits

The simulation of memory limits and its associated CPU scaling is currently not supported. Feel free to open a separate feature request and motivate your scenario. One challenge with enforcing memory limits in a development environment is that dev deployment packaging is typically not optimized for production and could accidentally hit memory limits. We support an opt-in feature for [ulimits](https://github.com/localstack/localstack/issues/6942), which could be used to simulate global memory limits for Lambda.
