### ISSUE TITLE
Incorrect layers response in lambda UpdateFunctionConfiguration call

### ISSUE THREAD

**Issue by mikecramergraze** [localstack/localstack#2490]
# Type of request: This is a ...

[ x ] bug report
[ ] feature request

# Detailed description

The lambda UpdateFunctionConfiguration call should return layers in the format of a list of structures as per the AWS documentation, however it currently returns a list of ARN strings instead (as per the request format).

https://docs.aws.amazon.com/cli/latest/reference/lambda/update-function-configuration.html - See **Output > Layers -> (list)**

This causes issues when using Terraform as it throws an error when attempting to marshal the response.

## Expected behavior

JSON response from UpdateFunctionConfiguration call to update layer ARN:

`
{"Layers":[{"Arn": "arn:aws:lambda:eu-west-1:000000000000:layer:somelayer:1", "CodeSize": 1234}]}
`

## Actual behavior

`
{"Layers":["arn:aws:lambda:eu-west-1:000000000000:layer:somelayer:1"]}
`

Error from aws cli:

`'unicode' object has no attribute 'get'`

# Steps to reproduce

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

`awslocal lambda update-function-configuration --function-name some-function --layers "arn:aws:lambda:eu-west-1:000000000000:layer:somelayer:1"`

**Comment by whummer** [comment]
Thanks a lot for reporting this issue @mikecramergraze . The message format returned by the API should be supported in the `latest` version - can you please do a `docker pull localstack/localstack` and give it another try? Please report here if the problem persists. Thanks!
