### ISSUE TITLE
Implement `ADMIN_NO_SRP_AUTH` (or equivalent) auth flow in Cognito

### ISSUE THREAD

**Issue by richardlund** [localstack/localstack#2491]
# Type of request: This is a ...

[ ] bug report
[X ] feature request

# Detailed description
We are currently testing a service that use the `AdminInitiateAuth` Cognito API for admin signin. This API call requires an `auth-flow` parameter of `ADMIN_NO_SRP_AUTH`. Unfortunately the LocalStack Cognito Service does not appear to implement this flow and we receive an unexpected error message during testing. If we use a 'real' instance of Cognito it works fine. 

## Expected behaviour
No error message and service works as expected.

## Actual behavior
Error as follows:

```
Unknown auth flow: ADMIN_NO_SRP_AUTH (Service: AWSCognitoIdentityProvider; Status Code: 400; Error Code: Exception; Request ID: null)
```

# Steps to reproduce
From command line:

```
awslocal cognito-idp admin-initiate-auth --user-pool-id <USERPOOLID> --client-id <CLIENTID> --auth-flow ADMIN_NO_SRP_AUTH --auth-parameters USERNAME=<USERNAME>,PASSWORD=<PASSWORD>,SECRET_HASH=<SECRET_HASH>
```

## Command used to start LocalStack
From Docker Compose file:

```
  localstack:
    image: localstack/localstack:0.11.1
    ports:
      - "443:443"
      - "4566-4607:4566-4607"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - DEBUG=1
      - SERVICES=edge, cognito
      - LOCALSTACK_API_KEY=******
    volumes:
      - "/tmp/localstack:/tmp/localstack"
```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

As above

**Comment by whummer** [comment]
Thanks a lot for reporting this issue @richardlund  . The `ADMIN_NO_SRP_AUTH` auth flow should be supported in the `latest` version - can you please do a `docker pull localstack/localstack` and give it another try? Please report here if the problem persists. Thanks!

**Comment by richardlund** [comment]
Hi @whummer . Unfortunately I still see the following error when using the `latest` image:

```Caused by: com.amazonaws.services.cognitoidp.model.AWSCognitoIdentityProviderException: Unknown auth flow: ADMIN_NO_SRP_AUTH (Service: AWSCognitoIdentityProvider; Status Code: 400; Error Code: Exception; Request ID: null)
```

**Comment by whummer** [comment]
Thanks for the follow-up @richardlund . This should now be fixed in the `latest` version of the Docker image (as per our discussion on Slack). Please let us know if there are still any issues related to this Cognito auth flow. Thanks!
