### ISSUE TITLE
s3 will not create bucket

### ISSUE THREAD

**Issue by Chanonry** [localstack/localstack#2498]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description
cannot create an s3 bucket from go aws-sdk-go-v2

Has worked previously.

## Expected behavior
create new bucket

## Actual behavior
failed to create test bucket, error: exceeded maximum number of attempts, 3, request send failed, Put http://nk-test-bucket-pdf.localhost:4572/: dial tcp: lookup nk-test-bucket-pdf.localhost: no such host FAIL

BUT same test will create an AWS bucket

AND 

aws --endpoint-url=http://localhost:4572 s3api create-bucket --bucket nk-test-bucket-pdf --region us-west-2

will also create the desired bucket 

Using 4566 has same effect.

# Steps to reproduce

Using image pulled from Docker Hub

## Command used to start LocalStack

docker-compose config

version: '3.2'
services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack_test
    environment:
      - SERVICES=s3,sqs,ssm,sts
      - DEBUG=1
      - DATA_DIR=
    ports:
      - '4572:4572'
      - '4576:4576'
      - '4583:4583'
      - '4592:4592'
    volumes:
      - './.AWSServices:/tmp/AWSServices'
      - '/var/run/docker.sock:/var/run/docker.sock'

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

svc := s3.New(testCfg)
input := &s3.CreateBucketInput{
		Bucket: aws.String(bucketName),
	}
req := svc.CreateBucketRequest(input)
_, err := req.Send(context.Background())

**Comment by mcintyre94** [comment]
This looks like an S3 path style issue. I'm not super familiar with the AWS Go SDK, but I think you want to call this function on your `testCfg`: https://docs.aws.amazon.com/sdk-for-go/api/aws/#Config.WithS3ForcePathStyle to force the correct path style.

**Comment by whummer** [comment]
Thanks for reporting @Chanonry , and thanks a lot for pointing out the solution @mcintyre94. Definitely looks like an S3 path style issue - please report here if the problem persists after applying the required configurations to the AWS Go SDK @Chanonry . Thanks!

**Comment by Chanonry** [comment]
Will check it out thanks. The code ref is  aws-sdk-go v1, I am using aws-sdk-go-v2 and configuring the client with a custom endpoint. As it was working successfully for several weeks I am not sure why the code would break unless the Docker image changed? Will check it out thanks for the suggestion

**Comment by Chanonry** [comment]
config is much simplified from v1. aws-sdk-g0-v2 has no such method https://docs.aws.amazon.com/sdk-for-go/v2/api/aws/#Config

**Comment by mcintyre94** [comment]
@Chanonry Looks like it's part of `Client` now - https://docs.aws.amazon.com/sdk-for-go/v2/api/service/s3/#Client See `ForcePathStyle`

**Comment by Chanonry** [comment]
Yes, just got there. 

Thanks for the help. 

Still not sure why it stoped working but hey it does now.

**Comment by mcintyre94** [comment]
Glad to hear it’s sorted! I’m afraid I have no idea why that would have changed for you, wonder if it’s something on the SDK side - I’ve always had to use path style with Localstack :)

**Comment by msdundar** [comment]
Nowadays the attribute name is `S3ForcePathStyle`, and is located here: https://docs.aws.amazon.com/sdk-for-go/api/aws/#Config

**Comment by noil** [comment]
I'm using aws-sdk-go-v2 and it helped me to set an attribute ```HostnameImmutable``` as ```true``` in the ```aws.Endpoint``` structure.

**Comment by LonelyPale** [comment]
```go
import "github.com/aws/aws-sdk-go-v2/aws"

var EndpointResolver = aws.EndpointResolverWithOptionsFunc(
	func(service, region string, options ...interface{}) (aws.Endpoint, error) {
		return aws.Endpoint{
			URL:               "http://127.0.0.1:8888",
			HostnameImmutable: true,
		}, nil
	})
```

**Comment by bollohz** [comment]
Hello there, I'm using the 1.1.0 docker image and still have the same issue? How can I workaround it?

**Comment by bollohz** [comment]
With the newest version of localstack (1.1.0 and above) adding the parameter `s3_force_path_style = true` to the terraform provider will solve the issue. 
Here are a more detailed code: 

`
provider "aws" {
    region                      = "eu-central-1"
    access_key                  = "fake"
    secret_key                  = "fake"
    skip_credentials_validation = true
    skip_metadata_api_check     = true
    skip_requesting_account_id  = true
    skip_get_ec2_platforms      = true
    s3_force_path_style         = true
    endpoints {
        apigateway     = "http://localhost:4566"
        cloudformation = "http://localhost:4566"
        cloudwatch     = "http://localhost:4566"
        dynamodb       = "http://localhost:4566"
        ec2            = "http://localhost:4566"
        es             = "http://localhost:4566"
        elasticache    = "http://localhost:4566"
        firehose       = "http://localhost:4566"
        iam            = "http://localhost:4566"
        kinesis        = "http://localhost:4566"
        lambda         = "http://localhost:4566"
        rds            = "http://localhost:4566"
        redshift       = "http://localhost:4566"
        route53        = "http://localhost:4566"
        s3             = "http://localhost:4566"
        s3api          = "http://localhost:4566"
        secretsmanager = "http://localhost:4566"
        ses            = "http://localhost:4566"
        sns            = "http://localhost:4566"
        sqs            = "http://localhost:4566"
        ssm            = "http://localhost:4566"
        stepfunctions  = "http://localhost:4566"
        sts            = "http://localhost:4566"
        events         = "http://localhost:4566"
    }
}
`
