### ISSUE TITLE
JUNit hook LocalstackTestRunner.ensureInstallation only checks if clone succeeded, not install

### ISSUE THREAD

**Issue by tadrinth** [localstack/localstack#250]
When using the JUnit hook for Localstack, LocalstackTestRunner.ensureInstallation is supposed to validate that LocalHost is successfully installed.  The install is a two step process of cloning the repo and then executing an install command.  However, it does this by checking if constants.py is present, which occurs during the clone, NOT by validating the results of the install command.  

This means that if the second step fails, further runs of the test will not re-attempt installation, even though localstack was not successfully installed.

Furthermore, it doesn't validate that localstack actually starts successfully. 

Once you're in this state, it will try to run localstack, silently fail because it isn't installed properly, and then all your tests fail to connect because localstack isn't running. 

A possible solution would be to create a marker file as the last part of the installation command and check for that file's existence, rather than checking for a file which appears after the git clone succeeds.  Then it will continue to retry the installation each time and generate an appropriate error. 

Ideally, it would also validate that trying to spin up localstack doesn't exit immediately with an error code.

**Comment by whummer** [comment]
Thanks for reporting @tadrinth , that's truly an important issue. The installation has been improved in #274 , I've basically followed your suggestion of adding a marker file and proper validation that LocalStack spins up properly. Can you give it a try with the latest version `0.1.4` of the Maven dependency? Thanks

**Comment by whummer** [comment]
Closing this ticket, as this issue seems to be solved with the PR mentioned above. Please re-open this ticket if the problem persists. Thanks
