### ISSUE TITLE
EventBridge support for target type "Firehose"

### ISSUE THREAD

**Issue by harrydaniels-IW** [localstack/localstack#2503]
[ ] bug report
[x] feature request

# Detailed description

Hi, I'm trying to mock a process which sends events via rules in EventBridge to Firehose and subsequently S3. However, It seems the firehose target type isn't supported yet. The way firehose sends events to S3 is great, is this on the roadmap?

`2020-06-03T16:02:53:WARNING:localstack.services.events.events_starter: Unsupported Events target service type "firehose"`

## Expected behavior

Put events to the event bus that meet a specific rule criteria are forwarded to firehose with additional eventbridge meta data.

## Actual behavior

Events sent to the eventbus that meet a specific rules criteria do nothing.

**Comment by whummer** [comment]
Thanks for reporting @harrydaniels-IW . Support for target type Firehose should be relatively easy to add - do you think you could contribute a small pull request to add this functionality? We'll be happy to provide guidance, if needed. That would be much appreciated, thanks!

**Comment by harrydaniels-IW** [comment]
Cheers for getting back to me @whummer. Happy to contribute, I'll check it out tomorrow!

**Comment by harrydaniels-IW** [comment]
Hi @whummer, i've pretty munch completed this PR. QQ why are there multiple files? i.e. event_starter.py and event_starter 2.py? Do both of these need to be completed?

**Comment by whummer** [comment]
Hi @harrydaniels-IW , thanks for the update - looking forward to reviewing the PR! Where do you see `event_starter 2.py` - looks like we don't currently have it on the master branch, do we? https://github.com/localstack/localstack/tree/master/localstack/services/events

**Comment by harrydaniels-IW** [comment]
Ah my mistake, i just cloned the repo twice which subsequently merged the two directories. Pull request for this feature here: https://github.com/localstack/localstack/pull/2523
Thanks!

**Comment by harrydaniels-IW** [comment]
This has been resolved in pull request #2523. https://github.com/localstack/localstack/pull/2523.
Closing issue.
