### ISSUE TITLE
aws ses - view email contents

### ISSUE THREAD

**Issue by YOU54F** [localstack/localstack#2514]
It looks like moto provides the ability to view the email raw contents which are sent via ses

https://github.com/spulec/moto/issues/1392

this came up in  https://github.com/localstack/localstack/issues/339 as a feature request

> amirsaber localstack uses [moto](https://github.com/spulec/moto) to mock SES service and it doesn't actually send email. It receives API call to send email and just stores it in memory and sends successful response back. Would be nice to have something like Inbox in Dashboard where you can see list of sent emails.

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-196) by [Unito](https://www.unito.io/learn-more)

**Comment by YarekTyshchenko** [comment]
A way to retrieve the requests programattically would be enough, since this is used from integration tests the most (I assume). I'd caution against actually sending the emails as the title says, this is a mock afterall.

**Comment by YOU54F** [comment]
> A way to retrieve the requests programattically would be enough, since this is used from integration tests the most (I assume). I'd caution against actually sending the emails as the title says, this is a mock afterall.

agreed, title updated. 👍 

For my use case, i would like my testers to be able to view the email content as rendered by a client, when they are running our full project setup locally. this plugin looks like it would solve that use-case. https://github.com/csi-lk/aws-ses-local - its a bit old and doesn't support rawemail so i would need to give it a little love :)

but for localstack, `a way to retrieve the requests programmatically` would benefit my devs developing in asserting the generated email contents

**Comment by YarekTyshchenko** [comment]
> For my use case, i would like my testers to be able to view the email content as rendered by a client, when they are running our full project setup locally

A common use case I imagine. I'm hoping that exposing the contents programatically means you (or anyone really) can throw a simple container in that renders them, and it doesn't put the implementation burden on localstack. Dividing problems and all that.

**Comment by yaitskov** [comment]
Hi,

So is there a hack to see email content?

Just Python print and logger.error doesn't have any effect on docker logs (env var DEBUG=ses).

**Comment by yaitskov** [comment]
Please, consider following PR.

It solves my issues. I hope it will satisfy everybody.

https://github.com/localstack/localstack/pull/3387

**Comment by YOU54F** [comment]
nicely done @yaitskov! and @whummer for merging 🚀 

I'll close this issue dow, I've not tested it out yet. feel free to nudge me if it needs reopening

**Comment by veelenga** [comment]
There is a tiny tool to preview the AWS SES emails in the browser: https://github.com/veertech/localstack-aws-ses-email-viewer
