### ISSUE TITLE
on MacOS, mounting /tmp/localstack makes lambdas slow

### ISSUE THREAD

**Issue by yonahforst** [localstack/localstack#2515]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description
When running localstack on MacOS using the example `docker-compose.yml`, Lambda functions can take a long time to start up. 

I think this is because of [existing performance issues with `osxfs`](https://forums.docker.com/t/file-access-in-mounted-volumes-extremely-slow-cpu-bound/8076/157), the file system server in Docker for Mac.

If your using `LAMBDA_EXECUTOR=docker`, the copying of zipped code to new `lambci/lambda` containers can take a very long time.

If you're using `serverless-localstack`, enabling `mountCode` solves the slow copying, but then actually requiring your code inside the lambda function can take a long time (mostly because of node_modules).

To solve this, I disabled mounting `/tmp/localstack` in my `docker-compose.yml`

```yml
    volumes:
      # - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```
...

## Expected behavior
...

## Actual behavior

...

# Steps to reproduce

## Command used to start LocalStack

...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

...

**Comment by whummer** [comment]
Thanks for reporting @yonahforst . Not sure if this is a bug per se, but performance can indeed become a bit slow if you're using large Lambda archives in MacOS. Would you mind creating a pull request with a small note in the README that describes your fix (perhaps in the Troubleshooting section)? Apart from the documentation change, is there anything else you think we can/should do here? Thanks

**Comment by whummer** [comment]
Thanks again. A short note on performance and Lambda mounting has now been added to the Troubleshooting part of the README: https://github.com/localstack/localstack#troubleshooting

**Comment by jgonera** [comment]
> Thanks again. A short note on performance and Lambda mounting has now been added to the Troubleshooting part of the README: https://github.com/localstack/localstack#troubleshooting

This is a dead link. Does this documentation live somewhere else now?

**Comment by jgonera** [comment]
@whummer Is there any place where I can find this explained in the official docs?

**Comment by whummer** [comment]
Hi @jgonera , we have restructured our docs in the meantime - the best way to get started with Lambda code mounting (hot swapping) is to follow our docs here: https://docs.localstack.cloud/tools/lambda-tools/hot-swapping/#code-hot-swapping-for-python-lambdas

Please keep us posted on how it goes - happy to provide more guidance if you have more specific questions regarding Lambda performance and/or code mounting.. 👍 Thanks

**Comment by jgonera** [comment]
@whummer That was useful but I'm still not sure why we need the `- "${TMPDIR:-/tmp/localstack}:/tmp/localstack"` mount. It still makes things slower because things like unzipping lambdas use the [slow macOS volume mounts](https://github.com/docker/roadmap/issues/7) instead of using container's native file system. Do I need this mount for anything if I don't use persistence?
