### ISSUE TITLE
Comma separating update statements in DynamoDB causes validation error

### ISSUE THREAD

**Issue by Woody1193** [localstack/localstack#2529]
# Type of request: This is a ...

[ x ] bug report
[ ] feature request

# Detailed description
When attempting to send an `UpdateRequest` to DynamoDB, having multiple SET operations separated by commas results in a validation exception. This is not the case with DynamoDB local or AWS DynamoDB
...

## Expected behavior
The update request to proceed without incident, as per DynamoDB local and AWS DynamoDB.
...

## Actual behavior
An error of the form `ValidationException: Invalid UpdateExpression: Syntax error; token: "updated", near: ", updated =" status code: 400, request id: 482c0c05-be94-4f05-bd92-8d3e3c9a2a1d` is returned.
...

# Steps to reproduce

Setup a DynamoDB table called `TEST_TABLE` with a composite primary key with fields `id` and `sort_key`, both strings. Then create a connection to this table and attempt the following update command.

    query := &dynamodb.UpdateItemInput{
        TableName:                   aws.String("TEST_TABLE"),
        ReturnConsumedCapacity:      aws.String(dynamodb.ReturnConsumedCapacityNone),
        ReturnItemCollectionMetrics: aws.String(dynamodb.ReturnItemCollectionMetricsNone),
        ReturnValues:                aws.String(dynamodb.ReturnValueNone),
        Key: map[string]*dynamodb.AttributeValue{
            "id":       {S: aws.String(id)},
            "sort_key": {S: aws.String(sortKey)},
        },
        UpdateExpression: aws.String("SET last_error = :st, updated = :ut"),
        ExpressionAttributeValues: map[string]*dynamodb.AttributeValue{
            ":st": {S: aws.String(status)},
            ":ut": {N: aws.String(strconv.FormatInt(time.Now().Unix(), 10))},
        },
    }

    conn.inner.UpdateItem(query)

## Command used to start LocalStack

Run via CircleCI with the following command

    version: 2
    jobs:
        build:
          docker:
          - image: golang:1.14.3
          - image: localstack/localstack
            environment:
              DEBUG: 1
              SERVICES: dynamodb:8000
              DEFAULT_REGION: ap-northeast-1
...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

...

**Comment by whummer** [comment]
Hi @Woody1193, thanks for reporting this issue. This appears to be an issue when using the keyword `updated`, which seems to be a reserved keyword in DynamoDB Local (which we're using under the covers). An integration test with multiple update expressions has been added in #2538 . Can you please confirm that your example works if you're using an attribute name other than "`updated`"?

I'm going to tag this issue as `won't fix` for now, as we do not have access to the source code of DynamoDB Local. If you would like to take a stab at it and contribute a fix or report this issue upstream with AWS / DynamoDB Local, that would be highly appreciated. Thanks!

**Comment by Woody1193** [comment]
@whummer Sorry for the late reply; I didn't get the notification for this. This query works with DynamoDB local and AWS. I checked the DynamoDB keywords and it looks like `update` is a keyword but `updated` is not. Am I off-base here?
