### ISSUE TITLE
[EC2] - Cannot CreateRoute to NetworkInterfaceId

### ISSUE THREAD

**Issue by postmart** [localstack/localstack#2530]
# Type of request: This is a ...

[x] bug report
[] feature request

# Detailed description

Cannot create a route with NetworkInterfaceId as next hop. This functionality relies on `moto` library, that does not have support for this yes:
```
moto.ec2.exceptions.MotoNotImplementedError: CreateRoute to NetworkInterfaceId has not been implemented in Moto yet.
```

## Expected behavior

Route created successfully

## Actual behavior

```
awslocal ec2 create-route --destination-cidr-block 0.0.0.0/0 --network-interface-id eni-1834da34 --route-table-id rtb-3378e5e1

Unable to parse response (syntax error: line 1, column 54), invalid XML received:
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
```

**Comment by whummer** [comment]
Thanks for reporting @postmart  . This should be fixed upstream in https://github.com/spulec/moto/pull/3063 , and the fix is now also available in LocalStack. Can you please give it a try with the `latest` version of the Docker image? Please report here if the problem persists. Thanks
