### ISSUE TITLE
Cannot create receipt rules in SES

### ISSUE THREAD

**Issue by arseniybanayev** [localstack/localstack#2531]
# Type of request: This is a ...
[x] bug report
[ ] feature request

# Detailed description
I am getting 500s running docker image `localstack/localstack:0.11.2` with `SERVICES=ses` when I try to create a rule set

```bash
awslocal ses create-receipt-rule-set --rule-set-name default-rule-set
```

in a `.sh` script in `/docker-entrypoint-initaws.d`.

```
Unable to parse response (syntax error: line 1, column 54), invalid XML received:
b'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">\n<title>500 Internal Server Error</title>\n<h1>Internal Server Error</h1>\n<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>\n'
```

**Comment by whummer** [comment]
Thanks for reporting @arseniybanayev . This should be fixed upstream in https://github.com/spulec/moto/pull/3059 , and the fix is now also available in LocalStack. Can you please give it a try with the `latest` version of the Docker image? Please report here if the problem persists. Thanks

**Comment by arseniybanayev** [comment]
Works now, thank you!
