### ISSUE TITLE
Make install cannot find a suitable quart version

### ISSUE THREAD

**Issue by gregghz** [localstack/localstack#2542]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

When running `make install` on a clean clone of localstack I get the following error:

```
ERROR: Could not find a version that satisfies the requirement quart>=0.12.0 (from -r requirements.txt (line 44)) (from versions: 0.1.0, 0.2.0, 0.3.0, 0.3.1, 0.4.0, 0.4.1, 0.5.0)
ERROR: No matching distribution found for quart>=0.12.0 (from -r requirements.txt (line 44))
```

## Expected behavior

No error

## Actual behavior

```
ERROR: Could not find a version that satisfies the requirement quart>=0.12.0 (from -r requirements.txt (line 44)) (from versions: 0.1.0, 0.2.0, 0.3.0, 0.3.1, 0.4.0, 0.4.1, 0.5.0)
ERROR: No matching distribution found for quart>=0.12.0 (from -r requirements.txt (line 44))
```

# Steps to reproduce

1. Clone repo
2. run `make install`

## Command used to start LocalStack

N/A

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

N/A

**Comment by payton** [comment]
For a temporary fix, checkout to 5bf74f2d718e0c47d3d7afd10142798fe8f8f53f and run the install. Quart was added right after that commit.

**Comment by whummer** [comment]
Thanks for reporting @gregghz @payton . Please note that more recent versions of `quart` require Python 3.6 or higher. Usually you should not need to clone the repo and run `make install`, unless you are planning to develop a feature or bug fix for LocalStack. Can you please elaborate a bit more on your use case?

Closing this issue for now, as this is related to the development setup of LocalStack (which should work with Python 3.6+). To make use of LocalStack, please use the recommended way of starting the stack in a Docker container. Thanks!

**Comment by gregghz** [comment]
I was planning to debug an issue I was experiencing with lambda. I have python 3.7 installed but make install uses pyenv to pick the version it needs doesn't it?

**Comment by zhenxiaotidal** [comment]
I have `pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.6)`, when running `pip3 install "localstack[full]"`:
```
  Could not find a version that satisfies the requirement Quart>=0.12.0 (from localstack[full]) (from versions: 0.1.0, 0.2.0, 0.3.0, 0.3.1, 0.4.0, 0.4.1, 0.5.0, 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.6.4, 0.6.5, 0.6.6, 0.6.7, 0.6.8, 0.6.9, 0.6.10, 0.6.11, 0.6.12, 0.6.13, 0.6.14, 0.6.15)
No matching distribution found for Quart>=0.12.0 (from localstack[full])
```

**Comment by naveenjohnsonv** [comment]
From their [site](https://pgjones.gitlab.io/quart/discussion/python_versions.html),
"The master branch and releases >= 0.7.0 onwards only support Python 3.7.0 or greater."
