### ISSUE TITLE
EC2 DescribeImages returns invalid type

### ISSUE THREAD

**Issue by adam-fowler** [localstack/localstack#2551]
# Type of request: This is a ...

[ x ] bug report
[ ] feature request

# Detailed description

The following 
```
awslocal ec2 describe-images --output text --query "Images[*].BlockDeviceMappings[*].Ebs.VolumeType"
```
Returns "ebs" repeatedly. "ebs" is not a valid value for `VolumeType`

## Expected behavior

Expected to returned one of `standard | io1 | gp2 | sc1 | st1`

## Command used to start LocalStack

```
docker run -d -p 4566-4597:4566-4597 -p 8080:8080 localstack/localstack
```

**Comment by whummer** [comment]
Thanks for reporting @adam-fowler . This should be fixed upstream in https://github.com/spulec/moto/pull/3074 - can you please give it a try with the `latest` version of the Docker image? Please report here if the problem persists. Thanks

**Comment by adam-fowler** [comment]
sorted! thank you
