### ISSUE TITLE
Unable to configure optional field for event-source-mapping for a lambda function (maximum-retry-attempts)

### ISSUE THREAD

**Issue by TanviAgg** [localstack/localstack#2552]
# Type of report
[x] bug report
[ ] feature request

# Detailed description
I am using a lambda function with a dynamodb stream (async).  I am trying to override the default value of maximum-retry-attempts while creating the event-source-mapping, but it is not working.

## Expected behavior
The max retries to be configurable.

## Actual behavior
Max retries do not get overridden.

# Steps to reproduce

## Command used to start LocalStack
`docker run -it -e SYNCHRONOUS_DYNAMODB_EVENTS=False -e LAMBDA_EXECUTOR=docker -e  -p 4566:4566 --rm --privileged --name $(LOCAL_DDB_NAME) -p 8080-8081:8080-8081 -p 4567-4620:4567-4620 -p 12121:12121  -v "$(DIR)/release/tmp/localstack:/tmp/localstack" -v "/var/run/docker.sock:/var/run/docker.sock" -e DOCKER_HOST="unix:///var/run/docker.sock" -e HOST_TMP_FOLDER="$(DIR)/release/tmp/localstack" -d "localstack/localstack"`

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
`awslocal dynamodb create-table --table-name local-users --attribute-definitions 'AttributeName=a1,AttributeType=S' --key-schema 'AttributeName=a1,KeyType=HASH' --provisioned-throughput 'ReadCapacityUnits=1,WriteCapacityUnits=1' --stream-specification 'StreamEnabled=true,StreamViewType=NEW_AND_OLD_IMAGES'`

`awslocal lambda create-function --function-name f1 --zip-file fileb://main.zip --handler main --environment "Variables={API_HOST=http://host.docker.internal:8085}" --runtime 'go1.x' --role r`

`awslocal lambda create-event-source-mapping --function-name f1 --event-source-arn $STREAM_ARN --batch-size 10 --maximum-retry-attempts 1 --starting-position TRIM_HORIZON`

This does not work as expected. Since my lambda handler is in golang, I have to use LAMBDA_EXECUTOR=docker which creates a new container (each with minimum size of 128mb) whenever lambda is invoked and that is causing a memory issue.
This is an amazing library by the way, great work!

**Comment by TanviAgg** [comment]
Update:
To ascertain whether the memory issue was indeed the reason why my program was failing, I tried writing the handler code in python (with LAMBDA_EXECUTOR=local) and it works now.

Earlier, the pile up of lambda functions was causing my ES container (running separately, not localstack ES) to stop because of low memory. 
I also noticed that lambda/dynamo streams were causing an issue with dynamodb and giving me "Post http://localhost:4569/: net/http: timeout awaiting response headers" errors. 
Is this a known issue? Any help to understand/explain this dynamo behaviour would be appreciated. Thank you.

**Comment by TanviAgg** [comment]
Update: 
Another issue with dynamodb stream and lambda mapping - old event-source-mappings with streams that are no longer available also invoke the lambda handler. 
Step 1: Create a lambda function.
Step 2: Create a dynamodb table and use update-table to enable stream.
Step 3: Add an event source mapping for the stream and lambda function created in step 1.
// Add some items to dynamo table, this triggers lambda
Step 4: Delete the table and recreate it (with the same name) and enable stream again (this time it has a different arn)
Step 5: Create a new event source mapping again.
// Add some items to dynamodb table
Step 6: Repeat steps 4 and 5 n times.

Now, whenever we add items to the dynamodb table, it triggers lambda n number of times, depending on the number of event source mappings that exist. 
I am not sure if this behaviour is correct.

**Comment by usmangani1** [comment]
@TanviAgg  it would be better if we can close this issue and create a new issue as the title is slightly misleading.Can you please create a new issue regarding this ? we will start working on it and try to resolve it as soon as possible.Thanks

**Unable to configure optional field for event-source-mapping for a lambda function (maximum-retry-attempts)**

**Comment by TanviAgg** [comment]
Hi, closing this issue as I have created a new one [here](https://github.com/localstack/localstack/issues/2561).
Thank you.
