### ISSUE TITLE
Java Lambdas are not working

### ISSUE THREAD

**Issue by zodeus** [localstack/localstack#256]
Hey there, just trying to get java lambdas to execute and I'm running into issues.
I've narrowed it down to the localstack containers /tmp/localstack/zipfile.x volume mount being empty in the lambda-docker container. I'm running localstack with privileged mode and mounted /var/run/docker to localstack, running docker images brings me back the correct list of images. Any suggestions? I think it has something to do with permissions, perhaps the lambda-docker container can't properly mount the other containers filesystem?

**Comment by whummer** [comment]
Hi @zodeus , thanks for reporting. Can you please provide the exact steps you're using to 1) start LocalStack, 2) create the JAR archive and deploy the Lambda, and 3) invoke the Lambda function. Also, please post any relevant command outputs and errors that you've seen. That would make debugging a bit easier. Thanks!

**Comment by zodeus** [comment]
Closing, duplicate of #255
