### ISSUE TITLE
aws-secretsmanager-jdbc to work with localstack

### ISSUE THREAD

**Issue by r-jindal** [localstack/localstack#2563]
How to make aws-secretsmanager-jdbc to work with localstack/secretmanager ?
I am using this config in my application.config file to connect with real AWS secretManager, I want to use localstack/secretmanager here.

>     driver-class-name = com.amazonaws.secretsmanager.sql.AWSSecretsManagerPostgreSQLDriver
>     url = "jdbc-secretsmanager:postgresql://postgres:5432/mydb"
>     secret-key = dev.rds.myteam.myservice.password
AWSSecretsManagerPostgreSQLDriver is a final class, so I cant extend that.
But there are constructors which take parameters like AWSSecretsManager client. I need to know the way, how to use them.

**Comment by whummer** [comment]
Thanks for reporting @r-jindal . I'm not too familiar with this library, but this class seems to have a constructor to pass an instance of `AWSSecretsManager`. If you can configure your code to use that constructor somehow, then it should be trivial to achieve (as when creating `AWSSecretsManager` allows you to pass all the required custom properties like `localhost` endpoint URL, etc).

https://github.com/aws/aws-secretsmanager-jdbc/blob/master/src/main/java/com/amazonaws/secretsmanager/sql/AWSSecretsManagerPostgreSQLDriver.java#L84-L86

This question about usage is a bit out of scope, but if you can provide a small, isolated repository on Github with the full project configuration and a maven/gradle build config, then it would be easier for other people to look into this issue. Thanks

**Comment by palaniappanrm** [comment]
Any update on this? @r-jindal @whummer

**Comment by anshulxyz** [comment]
Hi @palaniappanrm and @r-jindal 
Refer https://github.com/aws/aws-secretsmanager-jdbc#overriding-default-regions
You can provide endpoint by creating a `secretsmanager.properties` file the following content:
```properties
drivers.vpcEndpointUrl=http://0.0.0.0:4566
drivers.vpcEndpointRegion=us-east-1
```
