### ISSUE TITLE
DynamoDB Stream shardId wrong format

### ISSUE THREAD

**Issue by JavierGarciaGarciaPiksel** [localstack/localstack#2569]
# Type of request: This is a ...

[ ] bug report
[X ] feature request

# Detailed description

I'm using localstack to create a dynamoDb table locally with a dynamodb stream and a flink application consuming data from the stream
The shardId created in localstack follows this format

shardId-000000000000-798cedd84a2953c5af70a131f8701f35

Flink expects this format
shardId-00000001592367572726-07776efd

The difference is just after the prefix shardId.
Normally the real shardId created by amazon use is composed by shardId prefix, 20-digit timestamp and 0-36 or more characters separated by '-'

The current shardId format is not valid for flink applications and it's not following the real pattern used by amazon

## Expected behavior

ShardId must follow the pattern
shardId prefix, 20-digit timestamp and 0-36 or more characters separated by '-'

## Actual behavior

The shardId follows the pattern
shardId prefix, 12 0s and 33 characters separated by '-'

# Steps to reproduce

Create a dynamodb table

## Command used to start LocalStack

I'm using docker and docker compose to run localstack

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

aws --endpoint-url=http://localhost:4566 dynamodb create-table \
    --table-name temp4 \
    --attribute-definitions AttributeName=partition_key,AttributeType=S AttributeName=sort_key,AttributeType=S \
    --key-schema AttributeName=partition_key,KeyType=HASH AttributeName=sort_key,KeyType=RANGE \
    --provisioned-throughput ReadCapacityUnits=100,WriteCapacityUnits=100 \
    --stream-specification StreamEnabled=true,StreamViewType=NEW_AND_OLD_IMAGES

**Comment by whummer** [comment]
Thanks for reporting @JavierGarciaGarciaPiksel . This should be fixed via #2575 and #2581 - can you please give it a try with the `latest` version of the Docker image? Please report here if the problem persists. Thanks

**Comment by JavierGarciaGarciaPiksel** [comment]
That's perfect, working smoothly

**Comment by JavierGarciaGarciaPiksel** [comment]
Thanks a lot!
