### ISSUE TITLE
unsung dependency

### ISSUE THREAD

**Issue by pjz** [localstack/localstack#257]
Turns out localstack depends on having an `unzip` cli installed ([here](https://github.com/localstack/localstack/blob/master/localstack/services/install.py#L41) among other places).  Needs to be added to the list of dependencies.

**Comment by whummer** [comment]
Good point, thanks for flagging this @pjz , we should generally avoid calling external commands whenever possible. PR #265 fixes the issue by using native python code for extracting zip files.
