### ISSUE TITLE
Cloudformation: using Ref on a DynamoDB Table is returning the ARN instead of the table name

### ISSUE THREAD

**Issue by ameirwillowtree** [localstack/localstack#2573]
# Type of request: This is a ...

[X] bug report
[ ] feature request

# Detailed description
In my cloudformation template I use `Ref` on the logical ID of a DynamoDB table resource to pass the table name as an environment variable to a lambda function. According to the [docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dynamodb-table.html#aws-resource-dynamodb-table-return-values) 

> For the resource with the logical ID myDynamoDBTable, Ref will return the DynamoDB table name.

Instead I am getting back the full ARN but if the same cloudformation template is deployed to AWS I do get back the table name.

## Expected behavior

Calling `!Ref MyDynamoDBTable` in a cloudformation template will give back the table name

## Actual behavior

Calling `!Ref MyDynamoDBTable` in a cloudformation template is returning the table's ARN

# Steps to reproduce

## Command used to start LocalStack

docker-compose up

Here is my docker-compose.yaml file

```
version: "3"

services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4568-4599:4568-4599"
      - "${PORT_WEB_UI-8088}:${PORT_WEB_UI-8080}"
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - SERVICES=dynamodb:4569,s3:4572,secretsmanager:4584,ses:4579,cloudformation:4581,lambda:4574,iam:4593
      - DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=fake_access_key
      - AWS_SECRET_ACCESS_KEY=fake_secret_key
      - DEBUG=1
```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

Here is the cloudformation template:
```
AWSTemplateFormatVersion: '2010-09-09'

Resources:
  TableAccount:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: accountId
          AttributeType: S
      ProvisionedThroughput:
        WriteCapacityUnits: 5
        ReadCapacityUnits: 5
      TableName: UserAccount
      KeySchema:
        - KeyType: HASH
          AttributeName: accountId

  LambdaSync:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: DeploymentBucket
        S3Key: sync.zip
      Handler: index.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Runtime: nodejs12.x
      Environment:
        Variables:
          DYNAMO_TABLE: !Ref TableAccount

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: root
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - logs:*
            Resource: arn:aws:logs:*:*:*
```

**Comment by whummer** [comment]
Thanks for reporting @ameirwillowtree . This should be fixed in #2656 - can you please give it a try with the `latest` version of the Docker image? Please report here if the problem persists. Thanks
