### ISSUE TITLE
Localstack sqs related failure after version 11.2 - xml.etree.ElementTree.ParseError

### ISSUE THREAD

**Issue by redSlug** [localstack/localstack#2577]
# Type of request: This is a ...

[ x] bug report
[ ] feature request

# Detailed description
A script that uses a AWS wrapper to create queues is failing. It fails when using `localstack/localstack` image, but passes when pinning to `localstack/localstack:0.11.2`

Here is the output, 
```bash
18:48:55 creating test localstack queues
18:48:56 Traceback (most recent call last):
18:48:56   File "/root/.local/share/virtualenvs/mochi-8rsKKfLK/lib/python3.7/site-packages/botocore/parsers.py", line 432, in _parse_xml_string_to_dom
18:48:56     parser.feed(xml_string)
18:48:56 xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 0
18:48:56 
18:48:56 During handling of the above exception, another exception occurred:
18:48:56 
18:48:56 Traceback (most recent call last):
...
18:48:56     for n in self.list_client_queue_names()
18:48:56   File "/home/mochi/service/lib/aws/sqs.py", line 188, in list_client_queue_names
18:48:56     QueueNamePrefix=f"{ENVIRONMENT}-mochi"
18:48:56   File "/root/.local/share/virtualenvs/mochi-8rsKKfLK/lib/python3.7/site-packages/botocore/client.py", line 357, in _api_call
18:48:56     return self._make_api_call(operation_name, kwargs)
18:48:56   File "/root/.local/share/virtualenvs/mochi-8rsKKfLK/lib/python3.7/site-packages/botocore/client.py", line 648, in _make_api_call
18:48:56     operation_model, request_dict, request_context)
18:48:56   File "/root/.local/share/virtualenvs/mochi-8rsKKfLK/lib/python3.7/site-packages/botocore/client.py", line 667, in _make_request
18:48:56     return self._endpoint.make_request(operation_model, request_dict)
18:48:56   File "/root/.local/share/virtualenvs/mochi-8rsKKfLK/lib/python3.7/site-packages/botocore/endpoint.py", line 102, in make_request
18:48:56     return self._send_request(request_dict, operation_model)
18:48:56   File "/root/.local/share/virtualenvs/mochi-8rsKKfLK/lib/python3.7/site-packages/botocore/endpoint.py", line 135, in _send_request
18:48:56     request, operation_model, context)
18:48:56   File "/root/.local/share/virtualenvs/mochi-8rsKKfLK/lib/python3.7/site-packages/botocore/endpoint.py", line 167, in _get_response
18:48:56     request, operation_model)
18:48:56   File "/root/.local/share/virtualenvs/mochi-8rsKKfLK/lib/python3.7/site-packages/botocore/endpoint.py", line 218, in _do_get_response
18:48:56     response_dict, operation_model.output_shape)
18:48:56   File "/root/.local/share/virtualenvs/mochi-8rsKKfLK/lib/python3.7/site-packages/botocore/parsers.py", line 240, in parse
18:48:56     parsed = self._do_error_parse(response, shape)
18:48:56   File "/root/.local/share/virtualenvs/mochi-8rsKKfLK/lib/python3.7/site-packages/botocore/parsers.py", line 485, in _do_error_parse
18:48:56     root = self._parse_xml_string_to_dom(xml_contents)
18:48:56   File "/root/.local/share/virtualenvs/mochi-8rsKKfLK/lib/python3.7/site-packages/botocore/parsers.py", line 437, in _parse_xml_string_to_dom
18:48:56     "invalid XML received:\n%s" % (e, xml_string))
18:48:56 botocore.parsers.ResponseParserError: Unable to parse response (not well-formed (invalid token): line 1, column 0), invalid XML received:
18:48:56 b'{}'
```

## Expected behavior

no exception should be raised

## Actual behavior

```bash
18:48:56 botocore.parsers.ResponseParserError: Unable to parse response (not well-formed (invalid token): line 1, column 0), invalid XML received:
```
# Steps to reproduce
call command to list queues when there are no queues created yet,
```python
            return self.client.list_queues(
                QueueNamePrefix=f"{ENVIRONMENT}-mochi"
            )
```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

```python
class AWSSQSWrapper:
    def __init__(self):
        """
        Constructs the queues
        """
        try:
            self.sqs = boto3.resource("sqs", **BOTO_CLIENT_KWARGS)
            self.client = boto3.client("sqs", **BOTO_CLIENT_KWARGS)
            self.queues = {
                n: AWSQueue(n, self._get_queue_url(n), self._get_queue(n))
                for n in self.list_client_queue_names()
            }

        except (HTTPClientError, CredentialRetrievalError) as error:
            raise AWSSQSWrapperError(error)

    def _get_queue_url(self, queue_name: str):
        return self.client.get_queue_url(QueueName=queue_name)["QueueUrl"]

    def _get_queue(self, queue_name: str):
        return self.sqs.get_queue_by_name(  # pylint:disable=no-member
            QueueName=queue_name
        )

    def list_client_queues(self):
        try:
            return self.client.list_queues(
                QueueNamePrefix=f"{ENVIRONMENT}-mochi"
            )
        except (HTTPClientError, CredentialRetrievalError) as error:
            raise AWSSQSWrapperError(error)
```

**Comment by redSlug** [comment]
@fedebike FYI

**Comment by whummer** [comment]
Thanks for reporting @redSlug . I have been able to reproduce this issue, but only during startup if the SQS service is not fully started up yet.

The command used for testing is this one:
```
$ awslocal sqs list-queues --queue-name-prefix q1
```

* Step 1: Start LocalStack
* Step 2: Run the command above immediately after startup, *before* `Ready.` appears in the LS logs -> error "Unable to parse response"
* Step 3: Run the command above *after* `Ready.` appears in the LS logs -> command succeeds (with empty output)

Can you please double-check that `sqs` is included in your `SERVICES` configuration, and that LocalStack has fully started up? Is this issue related to startup/timing, or is it consistently reproducible under some other condition? Thanks

**Comment by redSlug** [comment]
@whummer this was consistently reproduced until we updated the localstack version to be pinned to `localstack/localstack:0.11.1`. The bug was occurring as part a Jenkins job using Docker. Every job ran consistently produced the error until we updated the pin.

This was the setup script that was failing in Jenkins,
```bash
#!/bin/bash

echo "running wait-for-it script for localstack localstack:4576"
until timeout 120 ./scripts/wait-for-it.sh localstack:4576 --timeout=30 --strict; do
    >&2 echo "localstack not available"
done

echo "creating test localstack queues"
pipenv run python service/scripts/queues/create_localstack_queues.py \
    --message-queue=$ENVIRONMENT-mochi-transactions \
    --dead-letter-queue=$ENVIRONMENT-mochi-transactions-dead-letter-queue
```

I don't think it was a timeout issue because it appears localstack was available after 30 seconds,
```bash
20:59:06 wait-for-it.sh: waiting 30 seconds for localstack:4576
20:59:11 wait-for-it.sh: localstack:4576 is available after 5 seconds
20:59:11 creating test localstack queues
```

this is part of our `docker-compose.yaml`, so yes, sqs is / was listed under SERVICES
```
  localstack:
    image: localstack/localstack:0.11.1
    expose:
      - "4561-4576"
      - "${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=sqs
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOSTNAME_EXTERNAL=localstack
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
```

please let me know if there is more helpful information I can provide

is there a better way to check if localstack is ready, besides checking for `localstack:4576` port being available?

**Comment by whummer** [comment]
Thanks for the update @redSlug . A change has been pushed recently - you should be able to get the service status from the health check endpoint on the edge port: http://localhost:4566/health . (Please pull the `latest` version of the Docker image.)

```
$ curl localhost:4566/health
{"services": {"sqs": "running", "s3": "running", "sts": "running", "apigateway": "running"}}
```

Please let us know if that works, or if there are any other issues. Thanks

**Comment by IgorEulalio** [comment]
@whummer im facing same issue, in another test.

i've used docker-compose to run localstack:
`version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack:0.11.2
    network_mode: bridge
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4571:4571"
    volumes:
      - ./localstack:/docker-entrypoint-initaws.d
    environment:
      - SERVICES=sqs`
      
mapped on my root folder, have an file named localstack/00_4576_configure_sqs.sh:
`echo "running sh file"

aws configure set aws_access_key_id default_access_key
aws configure set aws_secret_access_key default_secret_key
aws configure set default.region sa-east-1

awslocal sqs create-queue --queue-name submit_order`

in the startup of localstack, i receive message of health status of sqs service ok, but when run the sh script:
`localstack_main | Starting mock SQS service in http ports 4566 (recommended) and 4576 (deprecated)...
localstack_main | Waiting for all LocalStack services to be ready
localstack_main | Ready.
localstack_main | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initaws.d/00_4576_configure_sqs.sh
localstack_main | running sh file
localstack_main |
localstack_main | Unable to parse response (mismatched tag: line 7, column 2), invalid XML received. Further retries may succeed:
localstack_main | b'<HTML><HEAD>\r\n<TITLE>Access Denied</TITLE>\r\n</HEAD>\r\n<BODY>\r\n<FONT face="Helvetica">\r\n<big><strong></strong></big><BR>\r\n</FONT>\r\n<blockquote>\r\n<TABLE border=0 cellPadding=1 width="80%">\r\n<TR><TD>\r\n<FONT face="Helvetica">\r\n<big>Access Denied (authentication_failed)</big>\r\n<BR>\r\n<BR>\r\n</FONT>\r\n</TD></TR>\r\n<TR><TD>\r\n<FONT face="Helvetica">\r\nYour credentials could not be authenticated: "Credentials are missing.". You will not be permitted access until your credentials can be verified.\r\n</FONT>\r\n</TD></TR>\r\n<TR><TD>\r\n<FONT face="Helvetica">\r\nThis is typically caused by an incorrect username and/or password, but could also be caused by network problems.\r\n</FONT>\r\n</TD></TR>\r\n<TR><TD>\r\n<FONT face="Helvetica" SIZE=2>\r\n<BR>\r\n\r\n</FONT>\r\n</TD></TR>\r\n</TABLE>\r\n</blockquote>\r\n</FONT>\r\n</BODY></HTML>\r\n'`

**Comment by KyleJamesWalker** [comment]
I had the same issue (including 0.13 versions), and simply had pass the following env var into my docker:
```
SQS_PROVIDER=elasticmq
```

Example Run: `docker run --rm -it -p 4566:4566 -e SERVICES=s3,sqs -e SQS_PROVIDER=elasticmq localstack/localstack:0.13.0.8`

When I didn't have the SQS_PROVIDER passed, sqs would crash whenever accessed.

**Comment by chkal** [comment]
Looks like this issue only occurs if `SQS_PROVIDER` is set to `moto` (which is the default). It works well with `elasticmq`.
