### ISSUE TITLE
change endpoint url

### ISSUE THREAD

**Issue by mrigankt** [localstack/localstack#258]
we are using some third party  application for dynamodb and s3 due to localstack limitation of saving data in memory. we need to change the end point url in localstack to 3rd party url so that lcalstack can fetch data from third party in place of local stack in built services.  we also want to set those 3rd party application as lambda trigger in loclastack. please let us know how to do it and which file to make the changes.

**Comment by whummer** [comment]
Hi @mrigankt, please refer to the new configuration variables `DYNAMODB_BACKEND` and `S3_BACKEND` which have been introduced in #288. (e.g., `DYNAMODB_BACKEND=http://myhost:1234`)

Your code/tests should still connect the default ports on `localhost` to talk to those services (`4569` for DynamoDB, `4572` for S3), but LocalStack will forward all request made to these ports to the respective backend services if you configure the environment variables. Can you please give it a try and let me know if there are any issues. Thanks
