### ISSUE TITLE
DynamoDB S3Link not working

### ISSUE THREAD

**Issue by ramkumar-mn** [localstack/localstack#2590]
# Type of request: This is a bug
[ ] bug report
[ ] feature request

# Detailed description
When tried to use s3link using dynamodbmapper, getting the following errror.
` The AWS Access Key Id you provided does not exist in our records`.
I think this is because aws sdk cannot able to resolve s3 endpoint
...

## Expected behavior
Should be able to create link and upload the data.
...

## Actual behavior
Getting this error `The AWS Access Key Id you provided does not exist in our records`.
...

# Steps to reproduce
1. Start localstack using docker with services like dynamodb, s3 enabled.
1. Try to insert data to dynamodb which has S3Link object.

## Command used to start LocalStack
```
version: '2.1'
services:
  localstack:
    image: localstack/localstack
    ports:
      - "4567-4584:4567-4584"
    environment:
      - SERVICES=s3,dynamodb
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
```

command : `docker-compose up`
...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
```
public void save(Object object, byte[] image){
            S3Link s3Link = dynamoDBMapper.createS3Link(bucketName, "image_data.json");
            object.setImageData(s3Link);
            dynamoDBMapper.save(object);
            object.getImageData().uploadFrom(image);
}
```

...

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-200) by [Unito](https://www.unito.io/learn-more)

**Comment by whummer** [comment]
Thanks for reporting @ramkumar-mn . Can you please share the full configuration for your `dynamoDBMapper` client instance? Please note that you'll need to configure the endpoint URL pointing to the `http://localhost:...` endpoint, as well as some static fake credentials (the value should not matter, but some value needs to be present).

**Comment by ramkumar-mn** [comment]
Thanks @whummer . 
Here is my DynamoDbMapperConfiguration

```
    @Bean
    public AmazonDynamoDB amazonDynamoDB(AWSCredentialsProvider awsCredentialsProvider) {
        return AmazonDynamoDBClientBuilder.standard()
                .withCredentials(awsCredentialsProvider)
                .withEndpointConfiguration(new AwsClientBuilder
                        .EndpointConfiguration(endpoint, region))
                .build();
    }

    @Bean("awsCredentialsProvider")
    public AWSStaticCredentialsProvider awsCredentialsProvider() {
        return new AWSStaticCredentialsProvider(new BasicAWSCredentials(
                accessKey, secretKey));
    }


    @Bean
    public DynamoDBMapper dynamoDBMapper(AmazonDynamoDB amazonDynamoDB, DynamoDBMapperConfig mapperConfig, AWSCredentialsProvider awsCredentialsProvider) {
        return new DynamoDBMapper(amazonDynamoDB, mapperConfig, awsCredentialsProvider);
    }
```
accessKey : `test`
secretKey: `test`
endpoint: `http://127.0.0.1:4569`
region: `us-east-1`

**Comment by macnev2013** [comment]
Thanks for providing the configuration snippet @ramkumar-mn. Apologies for the long delay.

With default configuration S3 client uses real AWS endpoint. In order to use it with `LocalStack` - we need to create a client with `LocalStack` endpoint and use it in dynamodb mapper using `mapper.getS3ClientCache().useClient(s3client)`.

Here's a code snippet that might help you.
```
        String bucketName = "test";
        String serviceEndpoint = "http://localhost:4566";
        String s3ServiceEndpoint = "http://s3.localhost.localstack.cloud:4566";

        EndpointConfiguration endpointConfig = new EndpointConfiguration(serviceEndpoint, Regions.US_EAST_1.getName());
        EndpointConfiguration s3EndpointConfig = new EndpointConfiguration(s3ServiceEndpoint, Regions.US_EAST_1.getName());
        AWSCredentialsProvider s3CredentialProvider = new AWSStaticCredentialsProvider(new BasicAWSCredentials("test", "test"));
        AWSStaticCredentialsProvider awsCredProvider = new AWSStaticCredentialsProvider(new BasicAWSCredentials("test", "test"));

        AmazonDynamoDB client = AmazonDynamoDBClientBuilder
            .standard()
            .withCredentials(awsCredProvider)
            .withEndpointConfiguration(endpointConfig)
            .build();

        AmazonS3 s3client = AmazonS3ClientBuilder
            .standard()
            .withCredentials(s3CredentialProvider)
            .withEndpointConfiguration(s3EndpointConfig)
            .build();

        DynamoDBMapper mapper = new DynamoDBMapper(client, s3CredentialProvider);
        mapper.getS3ClientCache().useClient(s3client);
```
