### ISSUE TITLE
Cloudformation still doesn't work

### ISSUE THREAD

**Issue by denissabramovs** [localstack/localstack#2604]
Just tried to pull latest master and build docker images locally.
After successful build and launch, i have tried to deploy your test template from here https://github.com/localstack/localstack/blob/master/tests/integration/templates/template1.yaml and it's failing with status code 400 as invalid request and error message `Stack with id testingstack does not exist` and at the end we have 500 status code.
```
docker build .
docker run --rm --name localstackTest --network=host localstack/localstack:master
aws --debug --endpoint-url=http://localhost:4566 cloudformation deploy --template-file /var/local/test/cf.yaml --stack-name testingstack
```
I'm doing something wrong?

**Comment by denissabramovs** [comment]
The interesting part is, that it's actually creating stack, but not the resources in it, because:
`aws --debug --endpoint-url=http://localhost:4566 cloudformation list-stacks`
is returning us stack list:
`        {
            "StackId": "arn:aws:cloudformation:us-east-1:000000000000:stack/testingstack/f76eaf7f-7502-4adc-b39c-40b81d5477d1",
            "StackName": "testingstack",
            "TemplateDescription": "Simple CloudFormation Test Template",
            "CreationTime": "2020-06-22T19:16:25+00:00",
            "StackStatus": "CREATE_COMPLETE"
        }`
with status `CREATE_COMPLETE`

**Comment by denissabramovs** [comment]
Maybe it's not waiting for the stack to be created and trying to fetch stack when it not yet created?

**Comment by denissabramovs** [comment]
```
aws --debug --endpoint-url=http://localhost:4566 s3 ls
aws --debug --endpoint-url=http://localhost:4566 sqs list-queues
```
Both return empty lists, but there are definitely described sqs and s3 bucket in that testing cloudformation template.

**Comment by whummer** [comment]
Thanks for reporting @denissabramovs . This could potentially be an issue with a region mismatch. What is the output of the command below - are you using a custom region that is not `us-east-1`, by any chance?
```
$ env | grep REGION
AWS_DEFAULT_REGION=us-east-2
```
Also, could you please post the full logs from the LocalStack container? Thanks

**Comment by denissabramovs** [comment]
Thank you. That makes sense, i'll check it and report.

**Comment by denissabramovs** [comment]
Yes, thank you very much. It was the case. It's working now.
