### ISSUE TITLE
Use API gateway lambda proxy to invoke a custom lambda endpoint

### ISSUE THREAD

**Issue by mcintyre94** [localstack/localstack#2608]
# Type of request: This is a ...
[ ] bug report
[x] feature request

# Detailed description
This is somewhat similar to https://github.com/localstack/localstack/issues/2296 where we added support for step functions to call out to a custom lambda endpoint. I'm wondering if this would be plausible to do for API gateway as well? So I could have an API gateway set up with a lambda proxy, but instead of calling localstack's lambda endpoint it'd call my own configurable endpoint instead.

Looking at the existing code, API gateway calls `lambda_api.process_apigateway_invocation` here: https://github.com/localstack/localstack/blob/232ca315ed397354d9e89fa7530643156c8fa6f3/localstack/services/apigateway/apigateway_listener.py#L287

So since localstack is calling the lambda API directly rather than making a HTTP request, and since the lambda service seems to have custom code to handle the API gateway request, I'm guessing this wouldn't be trivial to swap out. Does it sound at all plausible as a feature request or is this too far outside of what localstack is designed for?

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-204) by [Unito](https://www.unito.io/learn-more)

**Comment by whummer** [comment]
Thanks for suggesting this enhancement @mcintyre94 . Generally, this seems a bit out of scope (or is at least not a very common use case), but technically it should be feasible to achieve this (similar to the `STEPFUNCTIONS_LAMBDA_ENDPOINT` configuration that was already introduced). Do you think you could take a stab at this and try to create a pull request with this feature? If there are any issues or blockers, we'll be happy to provide guidance/support. That would be much appreciated, thanks!

**Comment by hobochild** [comment]
I think I have a similar usecase - I have a [chalice](https://github.com/aws/chalice) app running in container along side localstack. I'd like all the lambda invocations from s3/sns to be proxied directly to the chalice dev container instead of invoking an actual lambda. It feels like it would be *alot* of work to get chalice bundling and executed in the lambda environment in a way that doesn't impact dev experience.

**Comment by hobochild** [comment]
I've actually found `LAMBDA_FORWARD_URL` which will do what I need thanks :+1:
