### ISSUE TITLE
SSM using awscli/awslocal is much slower than using AWSSimpleSystemsManagement sdk

### ISSUE THREAD

**Issue by LionH** [localstack/localstack#2611]
# Type of request: Bug report

[X] bug report
[ ] feature request

# Detailed description
I'm using testContainers to spin up localstack (v0.11.2). I figured out when adding an init.sh script to initialize with store params is much slower than using the java sdk to fill those values (approx. 40 parameters and increasing).

## Expected behavior
I expected both way of adding parameters were relatively similar

## Actual behavior
adding parameters through a shell script and aws-cli is slower

# Steps to reproduce
Sample project can be found [here](https://github.com/LionH/localstack-testcontainers-sample)

Here the results of processing time (sample with 60 parameters):
Initscript process time : 58s 687ms
Sdk init process time   : 19s 276ms

## Command used to start LocalStack
It is instantiated by TestContainers. No special changes on the default used.

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
put above

**Comment by whummer** [comment]
Thanks for reporting @LionH . I this this is expected, and not necessarily an issue with LocalStack. We have also noticed the behavior in the past that the CLI is much slower than the native SDKs for different programming languages.

Please note that the CLI has to perform a number of initialization tasks when the `aws` process starts - reading the environment configuration, loading the API specs from a local JSON file, mapping and validating the command line parameters, etc, etc.

Hence, the CLI is more suited for individual commands, but not ideally suited for batch processing of large number of requests.

Closing this issue for now, but please do report here if you find more evidence that there is something we can do on LocalStack side to make things better/faster. Thanks
