### ISSUE TITLE
Error 500 when getting shard iterator in dynamodb stream

### ISSUE THREAD

**Issue by JavierGarciaGarciaPiksel** [localstack/localstack#2616]
# Type of request: This is a ...

[ X] bug report
[ ] feature request

# Detailed description

I'm getting a 500 error (Internal error) when I try to get a shard iterator for a dynamodb stream

`aws --endpoint-url=http://localhost:4566 dynamodbstreams get-shard-iterator --stream-arn arn:aws:dynamodb:us-east-1:000000000000:table/metadata_local/stream/2020-06-25T07:27:58.128 --shard-id shardId-00000001593000000000-000000000000 --shard-iterator-type LATEST`

An error occurred (500) when calling the GetShardIterator operation (reached max retries: 4): <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>

## Expected behavior

Get shard iterator

## Actual behavior

Get an internal error

# Steps to reproduce

1. Create dynamodb table with stream enabled
2. List streams:
`aws --endpoint-url=http://localhost:4566 dynamodbstreams list-streams
{
    "Streams": [
        {
            "TableName": "metadata_local",
            "StreamArn": "arn:aws:dynamodb:us-east-1:000000000000:table/metadata_local/stream/2020-06-25T07:27:58.128",
            "StreamLabel": "2020-06-25T07:27:58.128"
        }
    ]
}`
3. Describe stream
`aws --endpoint-url=http://localhost:4566 dynamodbstreams describe-stream --stream-arn arn:aws:dynamodb:us-east-1:000000000000:table/metadata_local/stream/2020-06-25T07:27:58.128                                                     2 ↵
{
    "StreamDescription": {
        "StreamLabel": "2020-06-25T07:27:58.128",
        "StreamStatus": "ENABLED",
        "TableName": "metadata_local",
        "Shards": [
            {
                "ShardId": "shardId-00000001593000000000-000000000000",
                "SequenceNumberRange": {
                    "StartingSequenceNumber": "49608283705280920505809723516255054209044317068721127426"
                }
            }
        ],
        "StreamArn": "arn:aws:dynamodb:us-east-1:000000000000:table/metadata_local/stream/2020-06-25T07:27:58.128",
        "KeySchema": [
            {
                "KeyType": "HASH",
                "AttributeName": "partition_key"
            },
            {
                "KeyType": "RANGE",
                "AttributeName": "sort_key"
            }
        ]
    }
}`
4. Get shard iterator
`aws --endpoint-url=http://localhost:4566 dynamodbstreams get-shard-iterator --stream-arn arn:aws:dynamodb:us-east-1:000000000000:table/metadata_local/stream/2020-06-25T07:27:58.128 --shard-id shardId-00000001593000000000-000000000000 --shard-iterator-type LATEST`

An error occurred (500) when calling the GetShardIterator operation (reached max retries: 4): <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>

## Command used to start LocalStack

I run localstack using docker image

**Comment by whummer** [comment]
Thanks for reporting @JavierGarciaGarciaPiksel . This should be fixed in #2634 - can you please give it another try with the `latest` version of the Docker image? Please report here if the problem persists. Thanks

**Comment by JavierGarciaGarciaPiksel** [comment]
Thanks
Now it works perfectly
