### ISSUE TITLE
localstack SSM service giving ERROR

### ISSUE THREAD

**Issue by eerajoshi** [localstack/localstack#2618]
# Type of request: This seems to be a bug 

# Detailed description
I am trying to execute “aws ssm” command on localstack. Getting below mentioned error -

Steps:
1.	Create EC2 instance on localstack.
2.	Execute command on above created instance id
Command on local machine- 
C:\Users\esongara>aws  --endpoint-url=http://localhost:4566 ssm send-command --instance-ids "i-09fad7d0571cdfba0" --document-name "AWS-RunShellScript" --comment "IP config" --parameters commands="ifconfig" --output text

An error occurred (500) when calling the SendCommand operation (reached max retries: 2): <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>

Please let me know, how I can resolve this error. It would be really helpful. I also dropped a mail on info@localstack.cloud id. But no one reverted back....

## Expected behaviour
Command should get executed on EC2...

## Actual behavior
Command not getting executed on EC2...instead 500 ERROR is coming

# Steps to reproduce

## Command used to start LocalStack
docker-compose up

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
1.	Create EC2 instance on localstack.
2.	Execute command on above created instance id
Command on local machine- 
C:\Users\esongara>aws  --endpoint-url=http://localhost:4566 ssm send-command --instance-ids "i-09fad7d0571cdfba0" --document-name "AWS-RunShellScript" --comment "IP config" --parameters commands="ifconfig" --output text

**Comment by eerajoshi** [comment]
why closed this issue. This is still an issue...and unresolved

**Comment by whummer** [comment]
Thanks for reporting this issue @eerajoshi . Can you please provide some more details about your environment configuration. Which region are you using? Looks like we're hitting a problem here with one of the newer regions names (e.g., `aws-cn`) that are not being properly initialized in upstream `moto`. Thanks

**Comment by eerajoshi** [comment]
hi,
Thanks for taking it up.
My AWS config file has us-east-1 region.
Secondly, i tried the command by specifying "--region "us-east-1"
Please let me know, if i can help u with more details.

**Comment by bblommers** [comment]
FYI @whummer : The linked PR should fix this issue in Moto

**Comment by whummer** [comment]
Great, thanks for the heads-up @bblommers . 👍 Closing this issue, as this should now be fixed and available in the `latest` version @eerajoshi . Please report here if the problem persists. Thanks
