### ISSUE TITLE
Use latest dynamodb local

### ISSUE THREAD

**Issue by crash7** [localstack/localstack#2619]
# Type of request: This is a ...

[x] bug report
[x] feature request

# Detailed description

Hello! 

I'm trying to use the latest dynamodb local build with localstack (because I need the empty sets feature that they added in the last one) and I found that the version is fixed to an old one because of an issue in the docker version:

```
dynamodb_url = DYNAMODB_JAR_URL_ALPINE if in_docker() else DYNAMODB_JAR_URL
```
and
```
# TODO: Temporarily using a fixed version of DDB in Alpine, as we're hitting a SIGSEGV JVM crash with latest
DYNAMODB_JAR_URL_ALPINE = 'https://github.com/whummer/dynamodb-local/raw/master/etc/DynamoDBLocal.zip'
DYNAMODB_JAR_URL = 'https://s3-us-west-2.amazonaws.com/dynamodb-local/dynamodb_local_latest.zip'
```

The actual crash:
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x000000000000d7c6, pid=702, tid=0x00007f2d7f8f2b20
#
# JRE version: OpenJDK Runtime Environment (8.0_242-b08) (build 1.8.0_242-b08)
# Java VM: OpenJDK 64-Bit Server VM (25.242-b08 mixed mode linux-amd64 compressed oops)
# Derivative: IcedTea 3.15.0
# Distribution: Custom build (Wed Jan 29 10:43:50 UTC 2020)
# Problematic frame:
# C  0x000000000000d7c6
....
```

So far, seems that when localstack starts the jar in that particular port, it crashes, but using another port it works fine:
```
$ java -Djava.library.path=./DynamoDBLocal_lib -Xmx256m -jar DynamoDBLocal.jar -sharedDb -port 41645 -dbPath /tmp/localstack/data/dynamodb # this crashes

$ java -Djava.library.path=./DynamoDBLocal_lib -Xmx256m -jar DynamoDBLocal.jar -sharedDb -port 42645 -dbPath /tmp/localstack/data/dynamodb # this works
```

My question is: why? Is this related with the proxy? Any insight would be great.

# Localstack version
Tested with tags 0.11.2 and 0.8.6, but doesn't seem to matter since the zip is downloaded on start.

**Comment by crash7** [comment]
Ok, more digging:
```
    start_proxy_for_service('dynamodb', port, backend_port=PORT_DYNAMODB_BACKEND, update_listener=update_listener)
```

After calling this, dynamolocal crashes. So it must be something going on there that I don't follow (yet)

**Comment by whummer** [comment]
Thanks for reporting @crash7 . The version of DynamoDB has now been updated - can you please give it a try with the `latest` version of the Docker image? Please report here if the problem persists. Thanks

**Comment by crash7** [comment]
@whummer thanks for the reply (and fix).
Using v0.11.3 dynamo now accepts empty sets, so perfect.

One small problem (probably not related to this, I can open a new issue), since 0.11 I don't see a way to access the /shell from dynamo (previously on localhost:4564/shell), would be possible to map 4566/shell to -> dynamodb/shell?

Thanks

**Comment by whummer** [comment]
Thanks for the confirming the fix @crash7 . Access to the DynamoDB shell via the edge port has been added in #2648 - should be available in the `latest` image. Thanks

**Comment by crash7** [comment]
thanks @whummer 

When trying to access http://localhost:4566/dynamodb/shell or http://localhost:4566/shell I get a DNS not resolved error, sometimes I even get redirected to something like `http://cdfa96f208ca:4569/shell/`.

Any idea? Maybe I'm doing something wrong?

My compose is something like this
```
localstack:
    image: localstack/localstack:latest
    ports:
      - '4564:4564'
      - '4566:4566'
      - '4567-4584:4567-4584'
      - '8080:8080'
    environment:
      - DEBUG=true
      - DEFAULT_REGION=us-west-1
      - SERVICES=sqs,ssm,s3,sns,ses,dynamodb,kinesis,firehose
      - DYNAMODB_ERROR_PROBABILITY=0.0
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - PORT_WEB_UI=8080
      - EDGE_PORT=4566
```
