### ISSUE TITLE
Add SQS as target in EventBridge

### ISSUE THREAD

**Issue by alyyousuf7** [localstack/localstack#2620]
# Type of request: This is a ...
[ ] feature request

# Detailed description
I'm not able to register SQS target to EventBridge scheduled rule. The issue is exactly the same as my previous issue #2460, but that was for SNS as a target.

I wish to send a configured input (a constant JSON), instead of the EventBridge's own message to the SQS.

Thanks

**Comment by whummer** [comment]
Thanks for reporting @alyyousuf7 . This should be fixed in #2645 - can you please give it another try with the `latest` version of the Docker image? Please report here if the problem persists. Thanks

**Comment by alyyousuf7** [comment]
Thank you so much for swift feature development! I'll give it a try tomorrow, and let you know if I face an issue!
