### ISSUE TITLE
local stack started but getting the issue as  permission denied: /tmp/localstack/server.test.pem

### ISSUE THREAD

**Issue by RSHUKL01** [localstack/localstack#2623]
# Type of request: This is a ...

[ ] bug report

# Detailed description
local stack started but getting the issue as  permission denied: /tmp/localstack/server.test.pem
...

## Expected behavior
Run without error
...

# Steps to reproduce
Use my docker compose yaml file below
version: '2.1'
services:
  localstack:
    image: localstack/localstack
    ports:
      - "53:53"
      - "443:443"
      - "4510-4520:4510-4520"
      - "4566-4620:4566-4620"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - LOCALSTACK_API_KEY=2kgAL1q5TV
      - SERVICES=s3,emr,ec2,cloudformation
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOSTNAME=localhost localstack start
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      
    
## Command used to start LocalStack
docker-compose up

Error: [Errno 13] Permission denied: '/tmp/localstack/server.test.pem.key'

**Comment by mcintyre94** [comment]
I'm not familiar with this code, but it looks like this could be a unix permissions issue on either your `/tmp/localstack` folder, or `/tmp/localstack/server.test.pem`.

Can you run `ls -al /tmp | grep localstack` and `ls -al /tmp/localstack/server.test.pem` and paste in the results?

**Comment by whummer** [comment]
Thanks for reporting @RSHUKL01 . As @mcintyre94 mentioned, this looks like a permissions issue in the file system that gets mounted into the container. This message is only a warning and should not have any functional impact (as you mentioned) - we should have fallback logic in place that stores the cert files to a temporary location that is guaranteed to have write permissions.

Closing this issue, but please report here if your are in fact experiencing any functional issues with this (apart from the error/warning message). Thanks
