### ISSUE TITLE
Small deviation in SQS implementation

### ISSUE THREAD

**Issue by pwoolcoc** [localstack/localstack#2626]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

In the `ReceiveMessageResult` of the SQS service, I saw this XML from localstack:

```
...
<MessageAttribute>
     <Name>encoding</Name>
    <Value>
        <DataType>String</DataType>
        <StringValue><![CDATA[gzip]]></StringValue>
    </Value>
</MessageAttribute>
...
```

The `<![CDATA[gzip]]>` is slightly different from AWS, which doesn't wrap the value in a `<!CDATA[[]]>` section. This shouldn't be a problem for XML parsers that accept both plain characters and CDATA sections for this element, but the XML parser I was using did not, which causes an error when running the code against localstack but not when running the code against AWS. There is obviously a bug in the XML parser as well, but I thought that I should at least post this here since it is different than what AWS SQS does.

## Expected behavior

MessageAttribute::Value elements should not be wrapped in `CDATA` sections.

## Actual behavior

MessageAttribute::Value elements all seem to be wrapped in `CDATA` sections.

# Steps to reproduce

Send a message to the SQS service which contains some custom message attributes, then make a ReceiveMessageRequest.

## Command used to start LocalStack

`docker run --env "SERVICES=sqs" localstack/localstack`

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

...

**Comment by whummer** [comment]
Thanks for reporting @pwoolcoc . Out of curiosity, how is the `<StringValue>` escaped if the value contains a special character like `<`? Do you have an easy way to quickly test this? Thanks!

**Comment by mengelseatz** [comment]
I'm also running into this problem.   The official AWS Ruby SDK v3 fails with 
`undefined method 'cdata_block' for #<Aws::Xml::Parser::NokogiriEngine:0x00007fbd5e9ed590>` 

exception when trying to receive messages that have String or Number SQS MessageAttribute values.      Note this doesn't happen when passing Binary message attribute datatypes even though the actual value of a BinaryValue is a string.

**Comment by mengelseatz** [comment]
Also of note the AWS CLI just handles this transparently -if you pass CDATA in as part of your string (e.g. an HTML element) the system just handles it.   This is the response if I pass in HTML fragment as a string value message attribute in my SQS Message

`            "MessageAttributes": {
                "SessionToken": {
                    "StringValue": "<p>Testing</p>",
                    "DataType": "String"
                },
`
I wouldn't call this an "enhancement" ... it's definitely a bug in interpretation of what SQS is doing here.   Is this something ElasticMQ has to fix or is this a problem within LocalStack?

**Comment by pwoolcoc** [comment]
@whummer I'll try to get you this info today

**Comment by mengelseatz** [comment]
Just following ups - it's not ElasticMQ, it's LocalStack..  Just need to get rid of this CDATA wrapper:

https://github.com/localstack/localstack/blob/232ca315ed397354d9e89fa7530643156c8fa6f3/localstack/services/sqs/sqs_starter.py#L63

**Comment by mengelseatz** [comment]
After getting my head back into XML parsing/processing (it's been at least 10 years since I've heavily been involved with XML), CDATA in general shouldn't be used for this sort of programmatic XML processing from what I can glean.     For one wrapping it in CDATA means you can't actually use it as XML which appears to be the intent here?  
 
IMO that section that munges the XML as a string by replacing values should be removed and instead use a XML Parser to encode the values instead.   Encoded data can be decoded by the client application and parsed if needed.

**Comment by pwoolcoc** [comment]
@whummer looks like it's just being html-encoded:

```
<?xml version="1.0"?>
<ReceiveMessageResponse xmlns="http://queue.amazonaws.com/doc/2012-11-05/">
    <ReceiveMessageResult>
        <Message>
            <MessageId>...</MessageId>
            <ReceiptHandle>...</ReceiptHandle>
            <MD5OfBody>...</MD5OfBody>
            <MD5OfMessageAttributes>...</MD5OfMessageAttributes>
            <Body>foobar</Body>
            <MessageAttribute>
                <Name>Summary</Name>
                <Value>
                    <StringValue>&lt;h1&gt;foo&lt;/h1&gt;</StringValue>             <!-- THIS WAS SENT AS "<h1>foo</h1>" -->
                   <DataType>String</DataType>
                </Value>
            </MessageAttribute>
        </Message>
    </ReceiveMessageResult>
    <ResponseMetadata>
        <RequestId>...</RequestId>
    </ResponseMetadata>
</ReceiveMessageResponse>
```

**Comment by whummer** [comment]
Thanks for the update @pwoolcoc @mengelseatz - good catch that HTML encoding is used in AWS instead of CDATA. 👍  This should now be (hopefully) fixed in #2648 - can you please give it another try with the `latest` version of the Docker image? Please report here if the problem persists. Thanks

**Comment by mengelseatz** [comment]
@whummer  Thanks very much for the quick turn around on this.    Works as expected now out of the box when I pulled the latest image.   Much appreciated!!

**Comment by wojciechkedziora** [comment]
@whummer It seems that the problem still persists - probably the reason is different. The value inside `StringValue` tag is always wrapped into `<!CDATA[[]]>` section.

I suppose that replacement performed in [this line](https://github.com/localstack/localstack/blob/master/localstack/services/sqs/sqs_starter.py#L113) is not valid anymore.
```java
    # escape message responses to allow for special characters like "<"
    sqs_responses.RECEIVE_MESSAGE_RESPONSE = sqs_responses.RECEIVE_MESSAGE_RESPONSE.replace(
        "<StringValue>{{ value.string_value }}</StringValue>",
        "<StringValue>{{ _escape(value.string_value) }}</StringValue>",
    )
```

`RECEIVE_MESSAGE_RESPONSE` template from `moto` library has been changed and now contains:
```
<StringValue><![CDATA[{{ value.string_value }}]]></StringValue>
```

instead of 
```
<StringValue>{{ value.string_value }}</StringValue>
```

Could you take a look on it? Thanks.
