### ISSUE TITLE
DynamoDB: createTable gives invalid response when table already exists

### ISSUE THREAD

**Issue by svroonland** [localstack/localstack#2629]
# Type of request: This is a ...

[X] bug report
[ ] feature request

# Detailed description

When calling `DynamoDbAsyncClient.createTable` for a table that already exists, an empty `CreateTableResponse` is returned instead of an exception being thrown.

...

## Expected behavior

ResourceInUseException thrown

...

## Actual behavior

Empty `CreateTableResponse` object.

...

# Steps to reproduce

## Command used to start LocalStack

Docker-compose for `localstack/localstack` with `dynamodb` enabled

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

client.createTable("sdf")

client.createTable("sdf") // Should throw ResourceInUseException

...

**Comment by whummer** [comment]
Thanks for reporting @svroonland . This should be fixed in #2638 - can you please give it another try with the `latest` version of the Docker image? Please report here if the problem persists. Thanks

**Comment by svroonland** [comment]
Hi @whummer, AWS' behavior is to throw a `ResourceInUseException`, localstack now throws a `ResourceNotFoundException`.
