### ISSUE TITLE
Bug: install_amazon_kinesis_libs() failure

### ISSUE THREAD

**Issue by migurski** [localstack/localstack#263]
I’m experiencing a strange inconsistency between two systems, attempting to run localstack under virtualenv:

1. Mac OS X 10.12.5, Java 1.8.0_121, Python 3.6.0, `virtualenv -p python3 .venv`
2. Mac OS X 10.12.5, Java 1.8.0_144, Python 3.6.1, `python -m venv .venv`

On the second system _only_, `install_amazon_kinesis_libs()` fails to run. I’ve narrowed the problem down to a missing set of jars in the `amazon_kclpy` package: they’re present on system 1, and absent on system 2. I can’t determine why there’s an inconsistency, how or why to get system 2 to install the jars, or why they’re needed. I’m not using Kinesis, so I’m able to make progress by commenting out the call to `install_amazon_kinesis_libs()` in `install_components()`.

**Comment by whummer** [comment]
Thanks for reporting @migurski . This is fixed in #266 - we now only install `amazon_kclpy` for local development (when running `make install`), but _not_ when installing LocalStack via `pip`.

**Comment by migurski** [comment]
I confirmed on the second system that this worked. 👍
