### ISSUE TITLE
/health endpoint does not work when the edge port is mapped to localhost in docker

### ISSUE THREAD

**Issue by aaronjwhiteside** [localstack/localstack#2632]
# Type of request: This is a ...
[x] bug report

# Detailed description

When using docker and mapping the edge port to a port on localhost, trying to verify that the service is runnig via checking http://localhost:<mapped port>/health always returns in 404.

```
2020-06-27T03:57:20:INFO:localstack.services.edge: Unable to find forwarding rule for host "localhost:62907", path "/health?reload", target header "", auth header ""
```

**Comment by whummer** [comment]
Thanks for reporting @aaronjwhiteside . Can you please give it a try after pulling the `latest` Docker image, or use the new release version `0.11.3`?

I have been able to get this working with `latest`:
```
$ EDGE_PORT=51359 ... localstack start
...
$ curl http://localhost:51359/health
{"services": {"cloudformation": "running", "dynamodb": "running", "iam": "running", "lambda": "running", "logs": "running", "s3": "running", "ssm": "running", "sts": "running", "apigateway": "running"}}
```
Please report here if the problem still persists in the latest version. Thanks

**Comment by aaronjwhiteside** [comment]
Thanks @whummer, `0.11.3` fixes the issue for me.
