### ISSUE TITLE
Not able to connect with EMR service

### ISSUE THREAD

**Issue by uyadavv** [localstack/localstack#2636]
# Type of request: This is a service/feature request

# Detailed description
I am trying to create EMR cluster in Pro version of Localstack but getting this error " Could not connect to the endpoint URL: "http://localhost:4600/" "

...

## Expected behavior
Command should get executed on EMR service and Create a cluster.
...

## Actual behavior
Command not getting executed.
...

# Steps to reproduce
1. Start the Docker-Desktop.
2. Then Start the localstack with "Docker-compose up" command.
3. Execute the command on local machine:
aws --endpoint-url=http://localhost:4600 emr create-cluster --release-label emr-5.14.0 --instance-type m4.large --instance-count 2 

## Command used to start LocalStack
docker-compose up
...

**Comment by eerajoshi** [comment]
Request to look into the issue

**Comment by whummer** [comment]
Thanks for reporting @uyadavv @eerajoshi , and apologies for the delay. Looks like the required port is not exposed in your docker-compose configuration.

Can you either try using the edge port in your CLI command (`--endpoint-url=http://localhost:4566`) or expose the required ports in docker-compose.yml as well:
```
    ports:
      - "4566-4610:4566-4610"
      - ...
```
Please let us know if that works (or reach out directly on Slack), thanks!

**Comment by uyadavv** [comment]
When Execute the command on 4566:
aws --endpoint-url=http://localhost:4566 emr create-cluster --release-label emr-5.14.0 --instance-type m4.large --instance-count 2

Error got on first try: Read timeout on endpoint URL: "http://localhost:4566/"
Error got on third try:An error occurred (500) when calling the RunJobFlow operation (reached max retries: 2):

**Comment by whummer** [comment]
Thanks @uyadavv - can you please get in touch with us directly via Slack or email (info@localstack.cloud) - we'll be happy to look into this issue together with you in more detail. Thanks a bunch!

**Comment by chandu-ailneni** [comment]
I'm also facing the same issue in EMR cluster creation. What was the solution provided? @whummer
