### ISSUE TITLE
IAM Attached Policies Issues

### ISSUE THREAD

**Issue by RSHUKL01** [localstack/localstack#2649]
**Issue**
We attach policies to a role and when we try to list the policies attached to a role , we get null value as an output.
**Command used**:
Command to create role:
aws iam create-role --role-name trust-role-2 --assume-role-policy-document file://trust-policy.json --endpoint-url=http://localhost:443 - Executed successfully:

But when we tried to list the associated policies on the same role we get null values.
Command Used:
aws iam list-attached-role-policies --role-name trust-role-1 --endpoint-url=http://localhost:443 
Output:
 {
    "AttachedPolicies": []
}
Expected Result:
Policies should returned.

This is with the Pro Edition of LocalStack

**Comment by whummer** [comment]
Thanks for reporting @RSHUKL01 . We just ran a test against real AWS, and the behavior is the exact same as against LocalStack (empty list returned for `AttachedPolicies`). Please note that the "assume role policy" does not count towards the "attached role policies". Closing this issue, but please report here if there are any other issues. Thanks
