### ISSUE TITLE
LocalStack:Creation of route table with IPv6 is not working

### ISSUE THREAD

**Issue by RSHUKL01** [localstack/localstack#2651]
Issue:

Creation   of route table with IPv6 is not working
Command Used:

- aws ec2 create-vpc --cidr-block 10.0.0.0/16 --amazon-provided-ipv6-cidr-block --endpoint-url=http://localhost:443   
- aws ec2 describe-vpcs --vpc-id vpc-215c76da --endpoint-url=http://localhost:443
- aws ec2 create-subnet --vpc-id vpc-215c76da --cidr-block 10.0.0.0/24 --ipv6-cidr-block 2001:db8:1234:1a00::/56 --endpoint-url=http://localhost:443
- aws ec2 create-internet-gateway --endpoint-url=http://localhost:443
- aws ec2 attach-internet-gateway --vpc-id vpc-215c76da --internet-gateway-id igw-41a58cc5 --endpoint-url=http://localstack:443
- aws ec2 create-route-table --vpc-id vpc-215c76da --endpoint-url=http://localhost:443

**Error in the below command. This command is run after the above commands are executed successfully.**
 aws ec2 create-route --route-table-id rtb-74d6caff --destination-ipv6-cidr-block ::/0 --gateway-id igw-41a58cc5 --endpoint-url=http://localhost:443 

Error- Not Valid CIDR

**Comment by RSHUKL01** [comment]
@usmangani1  I read this earlier and it is not helping

**Comment by usmangani1** [comment]
Hey @RSHUKL01 , Which one are you talking about ?

**Comment by RSHUKL01** [comment]
@usmangani1  I an talking about my issue which is reported here.
@whummer Can you please suggest something
?

**Comment by whummer** [comment]
Thanks for reporting @RSHUKL01 . This should be fixed upstream in moto and has been integrated into the latest version of LocalStack. Can you please do a `docker pull localstack/localstack` and give it another try with the `latest` version of the Docker image? Please report here if the problem persists. Thanks

**Comment by RSHUKL01** [comment]
@whummer I am using the below docker compose yml file. It seems that I am using the latest version of the Docker image.
Let me know if I have to change or do any update in the below file.


version: '2.1'
services:
  localstack:
    image: ### localstack/localstack
    ports:
      - "53:53"
      - "443:443"
      - "4510-4520:4510-4520"
      - "4566-4620:4566-4620"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - LOCALSTACK_API_KEY=XXXXXXV
      - TEST_AWS_ACCOUNT_ID=000000000001,000000000002
      - SERVICES=s3,emr,ec2,cloudformation,iam,sts,vpc,cloudwatch,lambda,apigateway,sns,rds,secretsmanager,dynamodb
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      
      
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"

**Comment by whummer** [comment]
Thanks for the follow-up @RSHUKL01 . Please note that docker-compose will **not** automatically pull the actual latest version available on Docker Hub (hub.docker.com/), but it will use the image tagged `latest` in your local Docker image cache. After all, `latest` is nothing but a named tag from a Docker perspective - simular to `v1`, `v2` etc.

To really pull the latest version of the image from Docker hub (over the network), please use this command:
```
docker pull localstack/localstack
```
Hope that helps - please let us know. Thanks
