### ISSUE TITLE
Issue is related to s3: Sync Command is not working with exclude and include operation

### ISSUE THREAD

**Issue by RSHUKL01** [localstack/localstack#2655]
Issue: 
Sync Command is not working with exclude and include operation.

Command Used:
aws s3 sync . s3://my-bucket/path --exclude "*.txt" --include "MyFile*.txt" --exclude "MyFile?.txt" --endpoint-url=http://localhost:443

aws s3 sync . s3://my-bucket/path --exclude "*.txt" --endpoint-url=http://localhost:443

Error:
fatal error: An error occurred (InvalidAccessKeyId) when calling the ListObjectsV2 operation: The AWS Access Key Id you provided does not exist in our records.

**Comment by whummer** [comment]
Thanks for reporting @RSHUKL01 . Looks like this should be working if your environment is configured correctly.

Please make sure that `AWS_SECRET_ACCESS_KEY` and `AWS_ACCESS_KEY_ID` are set to a dummy value for testing.

Sample outputs with both AWS SDK v1 and SDK v2:
```
$ mkdir /tmp/test
$ cd /tmp/test
$ touch file1 file2 file3

$ export AWS_SECRET_ACCESS_KEY=test AWS_ACCESS_KEY_ID=test

$ aws --version
aws-cli/1.18.66 Python/3.8.2 Darwin/19.0.0 botocore/1.17.7
$ aws s3 sync . s3://my-bucket/path --exclude "*.txt" --endpoint-url=http://localhost:443
upload: ./file1 to s3://my-bucket/path/file1
upload: ./file3 to s3://my-bucket/path/file3
upload: ./file2 to s3://my-bucket/path/file2

$ awsv2 --version
aws-cli/2.0.28 Python/3.8.2 Darwin/19.0.0 botocore/2.0.0dev32
$ awsv2 s3 sync . s3://my-bucket1/path --exclude '*.txt' --endpoint-url=http://localhost:443
upload: ./file1 to s3://my-bucket1/path/file1
upload: ./file3 to s3://my-bucket1/path/file3
upload: ./file2 to s3://my-bucket1/path/file2
```

Hope that helps - please report here if the problem persists. Thanks
