### ISSUE TITLE
"localstack web" reports ERROR: cannot import name '_cancel_all_tasks'

### ISSUE THREAD

**Issue by nptech9806** [localstack/localstack#2662]
# Type of request: This is a bug report 

[X] bug report
localstack web
LocalStack version: 0.11.3
ERROR: cannot import name '_cancel_all_tasks'

# Detailed description
"localstack web" reports ERROR: cannot import name '_cancel_all_tasks'

...

## Expected behavior
expecting localstack web to start up and let me manage
...

## Actual behavior

ERROR: cannot import name '_cancel_all_tasks'
...

# Steps to reproduce

## Command used to start LocalStack
localstack web
...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
n/a
...

**Comment by whummer** [comment]
Thanks for reporting @nptech9806 .

Please note that the `web` command is not supposed to be started on the local machine, as it requires a set of additional dependencies. Instead, by default the Web UI is started in the LocalStack Docker container directly.

Also, please note that the Web UI is deprecated and may get removed in a future version (a deprecation notice has been added to the CLI usage docs in #2712). Thanks
