### ISSUE TITLE
Unsigned requests fail

### ISSUE THREAD

**Issue by ryan-gerstenkorn-sp** [localstack/localstack#2671]
Unsure if this is a bug or not but either way wanted to make a ticket incase anyone else comes across this. I guess I assumed skipping signing was ok since localstack didn't seem to care what I had setup for credentials and it also seems to work on the s3 specific port.

# Type of request: This is a ...

[* ] bug report
[ ] feature request

# Detailed description

Set `--no-sign-request` on any request using endpoint localhost:4566

Example:

$ aws s3 --no-sign-request --profile=local --endpoint-url=http://localhost:4566 ls 

An error occurred (404) when calling the ListBuckets operation: Not Found
$ aws s3 --no-sign-request --profile=local --endpoint-url=http://localhost:4572 ls 
2020-07-04 00:58:56 asdf
$ aws s3 --profile=local --endpoint-url=http://localhost:4566 ls                   
2020-07-04 00:58:56 asdf

# Steps to reproduce

~/.aws/config
```
[profile local]
region=us-east-1
s3 =
  addressing_style = path
```

~/.aws/credentials
```
[local]
aws_access_key_id = asdf
aws_secret_access_key = asd
```

Then follow the examples above.

**Comment by whummer** [comment]
Thanks for reporting @ryan-gerstenkorn-sp . This should be fixed in #2683 - can you please give it another try with the `latest` version of the Docker image? Please report here if the problem persists. Thanks
