### ISSUE TITLE
Feature Request - Eventbridge: Event Patterns

### ISSUE THREAD

**Issue by AlexCheema** [localstack/localstack#2672]
# Type of request: This is a ...
[ ] bug report
[X] feature request

# Detailed description
Eventbridge supports filtering events based on event patterns. See:
https://docs.aws.amazon.com/eventbridge/latest/userguide/filtering-examples-structure.html
https://docs.aws.amazon.com/eventbridge/latest/userguide/content-filtering-with-event-patterns.html

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-208) by [Unito](https://www.unito.io/learn-more)

**Comment by whummer** [comment]
Thanks for reporting @AlexCheema . Support for content based filtering has been added in #3258 - can you please pull the `latest` Docker image and give it another try? Please report here if anything is missing. Thanks
