### ISSUE TITLE
Is s3control supported?

### ISSUE THREAD

**Issue by neara** [localstack/localstack#2673]
Hi,

I am trying to figure out if `s3control` is supported in localstack? Is it possible to test code that creates s3 batch jobs? 

Thanks :pray:

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-209) by [Unito](https://www.unito.io/learn-more)

**Comment by thrau** [comment]
This feature is available in LocalStack pro. Should you have problems with the pro version, please let us know in Slack, thanks!
