### ISSUE TITLE
LocalStack: API Gateway

### ISSUE THREAD

**Issue by RSHUKL01** [localstack/localstack#2681]
Use case check the feasibility of API gateway and SNS service.

Command Used 

- aws sns create-topic --name service-proxy-topic  --output text  --query 'TopicArn' --enpoint-url=http://localhost:443

- aws sns subscribe --topic-arn arn:aws:sns:us-east-1:000000000000:service-proxy-topic --protocol sms --notification-endpoint +xxxxxxxx66 --endpoint-url=http://localhost:443

- aws sns publish --topic-arn arn:aws:sns:us-east-1:000000000000:service-proxy-topic --'This is a test' --endpoint-url=http://localhost:443

- aws apigateway create-rest-api --name 'Service Proxy' --output text --query 'id' --endpoint-url=http://localhost:443

- aws apigateway get-resources --rest-api-id nmafetnwf6 --endpoint-url=http:localhost:443

- aws apigateway get-resources --rest-api-id nmafetnwf6 --output text --query 'items[0].id' --endpoint-url=http://localhost:443

- aws apigateway create-resource --rest-api-id nmafetnwf6 --parent-id 0ak9uhavio --path-part ingest --output text --query 'id' --endpoint-url=http://localhost:443

- aws apigateway get-resources --rest-api-id nmafetnwf6 --endpoint-url=http://localhost:443

- aws iam create-role --role-name service-proxy-role --assume-role-policy-document '{"Version": "2012-10-17","Statement": {"Effect": "Allow","Principal": {"Service": "apigateway.amazonaws.com"},"Action": "sts:AssumeRole"}}' --output text --query 'Role.Arn') --endpoint-url=http://localhost:443

- aws iam put-role-policy --role-name service-proxy-role --policy-name 'sns-publish' --policy-document '{"Version": "2012-10-17","Statement": {"Effect": "Allow","Action": "sns:Publish","Resource": "'arn:aws:sns:us-east-1:000000000000:service-proxy-topic'"}}' --endpoint-url=http://localhost:443

- aws apigateway put-integration --rest-api-id nmafetnwf6 --resource-id gdryg4byff --http-method POST --type AWS --integration-http-method POST --uri 'arn:aws:apigateway:us-east-1:sns:path//' --credentials arn:aws:iam::000000000000:role/service-proxy-role  --passthrough-behavior NEVER --endpoint-url=http://localhost:443     

- aws apigateway put-integration-response --rest-api-id nmafetnwf6 --resource-id gdryg4byff --http-method POST --status-code 200 --response-templates application/json="" --endpoint-url=http://localhost:443       

- aws apigateway put-method-response --rest-api-id nmafetnwf6 --resource-id gdryg4byff --http-method POST --status-code 200  --response-models application/json="" --endpoint-url=http://localhost:443   

- aws apigateway create-deployment --rest-api-id nmafetnwf6 --stage-name prod --endpoint-url=http://localhost:443

Then I executed the below command in which I am getting error.

- curl -X POST https://nmafetnwf6.execute-api.us-east-1.amazonaws.com/prod/ingest --data 'Hello, from your terminal!' -H 'Content-Type: application/json'

- curl -iX POST http://localhost:443/restapis/nmafetnwf6/prod/ingest --data 'Hello, from your terminal!'

ERROR:
INFO:localstack.services.edge: Unable to find forwarding rule for host "localhost:443", path "/favicon.ico", target header "", auth header "", data "b''"

**Comment by RSHUKL01** [comment]
@whummer Can you please look into this?

**Comment by whummer** [comment]
Thanks for the detailed report @RSHUKL01. Please note that API Gateway invocations in LocalStack use a special URL pattern - please refer to the updated docs in the README here: https://github.com/localstack/localstack#invoking-api-gateway

In your example, the URL for executing the REST API method would look like this:
```
curl -iX '{}' http://localhost:443/restapis/nmafetnwf6/prod/_user_request_/ingest --data 'Hello, from your terminal!'
```
Hope that helps - please report here if that doesn't work or if there are any other issues. Thanks!

**Comment by RSHUKL01** [comment]
@whummer No It does not work.

**Comment by whummer** [comment]
Thanks for the update @RSHUKL01 . Can you please share the version of the Docker image you're using, and the concrete log output / error message you're seeing?

Can you please share the output of this command:
```
docker images
```
For example:
```
localstack/localstack                latest                                           bf271bf883cb        15 hours ago        677MB
```
... as well as the output of this command (with `nmafetnwf6` replaced with the correct API ID):
```
curl -iX '{}' http://localhost:443/restapis/nmafetnwf6/prod/_user_request_/ingest --data 'Hello, from your terminal!'
```
Thanks for your help.
