### ISSUE TITLE
No message received on the email regarding subscription

### ISSUE THREAD

**Issue by uyadavv** [localstack/localstack#2682]
# Type of request: This is a bug
[ ] bug report
[ ] feature request

# Detailed description
 Executed the command "aws --endpoint-url=http://localhost:4566 sns subscribe --topic-arn arn:aws:sns:us-east-1:000000000000:test-topic1 --protocol email --notification-endpoint upendra.ydvvv@gmail.com" but did not received any email of subscription to the address specified.
...

## Expected behavior
Must get an confirmation message by email to the address specified in the subscribe command.
...

## Actual behavior
No message received on the email.
...

# Steps to reproduce
1. Create an topic.
1. Now subscribe to the topic using the above command.

## Command used to start LocalStack
docker-compose up
...

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-211) by [Unito](https://www.unito.io/learn-more)

**Comment by luminescent** [comment]
I cannot use the email notification either, it seems to bot be working. How do we get it to work? 

Thank you

**Comment by sumitya** [comment]
it doesnt work for me either. I pulled the latest image as suggested in [2924](https://github.com/localstack/localstack/issues/2924)

**Comment by whummer** [comment]
Thanks for reporting @uyadavv @luminescent @sumitya . You should be able to retrieve the sent messages if you point `DATA_DIR` to a persistent folder that can be accessed from the host. Can you please give it another try with the `latest` Docker image? 

Start LocalStack with DATA_DIR:
```
$ DATA_DIR=/tmp/ls-data DEBUG=1 localstack start
```

Create test topic, email subscriber, publish message:
```
$ awslocal sns create-topic --name test-topic1
$ awslocal sns subscribe --topic-arn arn:aws:sns:us-east-1:000000000000:test-topic1 --protocol email --notification-endpoint upendra.ydvvv@gmail.com
$ awslocal sns publish --message 'msg1' --topic-arn arn:aws:sns:us-east-1:000000000000:test-topic1
```

This should create a new file in your DATA_DIR folder under `ses`:
```
$ cat /tmp/ls-data/ses/elajirvlobcwjcfe-avnpztjv-zmxx-nozk-aomk-xpvrxaifzzve-tlscdh.json
{"Source": "admin@localstack.com", "Region": "us-east-1", "Destinations": {"ToAddresses": ["upendra.ydvvv@gmail.com"], "CcAddresses": [], "BccAddresses": []}, "Subject": "SNS-Subscriber-Endpoint", "Body": "msg1"}
```

Hope that helps. Please note that actual sending of emails is not supported in the Community edition (we do have support for SMTP settings in Pro, though).. Please keep us posted how it goes.. Thanks!
