### ISSUE TITLE
DynamoDb Empty Response

### ISSUE THREAD

**Issue by triplejay2013** [localstack/localstack#2686]
# Type of request: This is a ...

[ x ] bug report
[ ] feature request

# Detailed description

Terraform versions:
- terraform v0.12.28
- aws v2.68.0

Localstack v0.11.0

## Expected behavior

When a table already exists, and I attempt to create it (in AWS), I get the following response
```
{"__type":"com.amazonaws.dynamodb.v20120810#ResourceInUseException","message":"Table already exists: thetable"}
```

## Actual behavior

When I try to do the same with Localstack, I get nothing (Empty Response). This has been the cause of quite a few issues( [this bug](https://github.com/terraform-providers/terraform-provider-aws/issues/14019) and [this resolution](https://github.com/terraform-providers/terraform-provider-aws/pull/13925/files) are what lead me to discover this issue)

**Comment by whummer** [comment]
Thanks for reporting @triplejay2013 . This should be fixed via #2638 - can you please do a `docker pull localstack/localstack` and give it another try with the `latest` version? Please report here if the problem persists. Thanks
