### ISSUE TITLE
LocalStack: RDS

### ISSUE THREAD

**Issue by RSHUKL01** [localstack/localstack#2691]
I want to write data from s3 to table at postgre1

I am attaching the script here which I am using. 

Error:
psycopg2.errors.UndefinedFile: could not open file "s3://personbucket/sample.txt" for reading: No such file or directory
HINT:  COPY FROM instructs the PostgreSQL server process to read a file. You may want a client-side facility such as psql's \copy.

script I am using:

```
import os
import boto3
import psycopg2
import subprocess

RDS_ENDPOINT = os.environ.get('RDS_ENDPOINT') or 'http://localhost:443'

#def subprocess_cmd(cmd):

    
    #command_output = subprocess.Popen(cmd, shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    #stdout, stderr = command_output.communicate()
    #if command_output.returncode == 0:
        #print(command_output.returncode)
        #print("Command is executed successfully")
    #else:
        #print(command_output.returncode)
        #print("Error: Command error- Please check the table and function name if already created")
        #exit(0)


def run_queries(instance):
    print('Run DB queries against RDS instance %s' % instance['DBInstanceIdentifier'])
    port = instance['Endpoint']['Port']
    conn = psycopg2.connect("dbname=test user=test password='test' host=localhost port=%s" % port)
    with conn.cursor() as cur:
        cur.execute('CREATE TABLE person ("id" INTEGER, "name" VARCHAR not null, PRIMARY KEY ("id"))')
        print("creation of table finishes")
        cur.execute("copy person from 's3://personbucket/sample.txt'")
    
    with conn.cursor() as cur:
        cur.execute("SELECT * FROM person")
        result = cur.fetchall()
        print(result)

#def copys3file():
    #print("copy statement")
    #cmd1='aws s3 cp file://sample.txt s3://personbucket/ --endpoint-url=http://localhost:443'
    #subprocess_cmd(cmd1)


def create_db():
    print('Creating RDS DB instance')
    client = connect_rds()
    instance = client.create_db_instance(Engine='postgres', DBInstanceClass='c1', DBInstanceIdentifier='i1')
    return instance['DBInstance']
    
def connect_rds():
    return boto3.client('rds', endpoint_url=RDS_ENDPOINT)

def main():
    instance = create_db()
    #copys3file()
    run_queries(instance)
    delete_db(instance)


if __name__ == '__main__':
    main()

**Comment by RSHUKL01** [comment]
@whummer  there is slight change in the above script. please use the below script. the above script is the one from pro local sample. Please use the below script.
import os
import boto3
import psycopg2
import subprocess

RDS_ENDPOINT = os.environ.get('RDS_ENDPOINT') or 'http://localhost:443'

#def subprocess_cmd(cmd):

    
    #command_output = subprocess.Popen(cmd, shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    #stdout, stderr = command_output.communicate()
    #if command_output.returncode == 0:
        #print(command_output.returncode)
        #print("Command is executed successfully")
    #else:
        #print(command_output.returncode)
        #print("Error: Command error- Please check the table and function name if already created")
        #exit(0)


def run_queries(instance):
    print('Run DB queries against RDS instance %s' % instance['DBInstanceIdentifier'])
    port = instance['Endpoint']['Port']
    conn = psycopg2.connect("dbname=test user=test password='test' host=localhost port=%s" % port)
    with conn.cursor() as cur:
        cur.execute('CREATE TABLE person ("id" INTEGER, "name" VARCHAR not null, PRIMARY KEY ("id"))')
        print("creation of table finishes")
        cur.execute("copy person from 's3://personbucket/sample.txt'")
    
    with conn.cursor() as cur:
        cur.execute("SELECT * FROM person")
        result = cur.fetchall()
        print(result)

#def copys3file():
    #print("copy statement")
    #cmd1='aws s3 cp file://sample.txt s3://personbucket/ --endpoint-url=http://localhost:443'
    #subprocess_cmd(cmd1)


def create_db():
    print('Creating RDS DB instance')
    client = connect_rds()
    instance = client.create_db_instance(Engine='postgres', DBInstanceClass='c1', DBInstanceIdentifier='i1')
    return instance['DBInstance']
    
def connect_rds():
    return boto3.client('rds', endpoint_url=RDS_ENDPOINT)

def main():
    instance = create_db()
    #copys3file()
    run_queries(instance)
    delete_db(instance)


if __name__ == '__main__':
    main()

**Comment by whummer** [comment]
Thanks for reporting @RSHUKL01 . This should be fixed in the latest version. Can you please do a `docker pull localstack/localstack` and give it another try with the `latest` version of the Docker image? Please report here if the problem persists. Thanks!

**Comment by RSHUKL01** [comment]
@whummer  I am using the below docker compose yml file. It seems that I am using the latest version of the Docker image.
Let me know if I have to change or do any update in the below file.

version: '2.1'
services:
localstack:
image: **localstack/localstack**
ports:
- "53:53"
- "443:443"
- "4510-4520:4510-4520"
- "4566-4620:4566-4620"
- "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
environment:
- LOCALSTACK_API_KEY=XXXXXXV
- TEST_AWS_ACCOUNT_ID=000000000001,000000000002
- SERVICES=s3,emr,ec2,cloudformation,iam,sts,vpc,cloudwatch,lambda,apigateway,sns,rds,secretsmanager,dynamodb
- DEBUG=1
- DATA_DIR=/tmp/localstack/data
- DOCKER_HOST=unix:///var/run/docker.sock

volumes:
  - "/var/run/docker.sock:/var/run/docker.sock"
  - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"

**Comment by RSHUKL01** [comment]
@whummer could you please let us know if there is any progress on this? let me know if you need any other detail from my end,

**Comment by whummer** [comment]
Thanks for the update @RSHUKL01 . Please note that adding `localstack/localstack:latest` is not sufficient, as Docker would be using an existing image from the local cache. Can you please always make sure to manually pull the latest version from Docker Hub:
```
docker pull localstack/localstack
```
Then, please report the version/ID of the image you're using, for example:
```
docker images
---
localstack/localstack                latest                                           bf271bf883cb        2 days ago          677MB
```
If it still doesn't work with the latest version, please provide the detailed error logs from your LocalStack Docker container.

Thanks for your help!
