### ISSUE TITLE
QLDB Document insert does not return expected result

### ISSUE THREAD

**Issue by A-R-Smith** [localstack/localstack#2693]
# Type of request: This is a ...

[X] bug report
[ ] feature request

# Detailed description
There is a difference in what is returned from transactions and commands against a table in a QLDB ledger in AWS vs in Localstack.

## Expected behavior
When inserting a document in AWS QLDB, the transaction returns an Amazon Ion value containing the created documentId.
From the qldbshell connected to a QLDB ledger in AWS:
```
qldbshell > insert into TEST `{"hello":"world"}`
INFO:
{
 documentId: "BabQrIORS5W0XOKhoASZAM"
}
INFO: (0.2968s)
```

## Actual behavior
When inserting a document in Localstack QLDB, the transaction returns an Amazon Ion value containing the document data that was inserted, NOT the documentId.
From the qldbshell connected to a QLDB ledger in Localstack:
```
qldbshell > insert into TEST `{"hello":"world"}`
INFO:
{
 hello: "world"
}
INFO: (1.4246s)
```
# Steps to reproduce
1) Start localstack with commands below
2) Create the ledger with this command: `aws qldb create-ledger --name TEST --permissions-mode ALLOW_ALL --endpoint-url=http://localhost:4566`
3) Connect to ledger with qldbshell: `qldbshell --ledger TEST -s=http://localhost:4566`
4) Create a test table: `create table TEST`
5) Try to insert a simple document: 
```
insert into TEST `{"hello":"world"}`
``` 
## Command used to start LocalStack
`TMPDIR=/private$TMPDIR SERVICES=qldb PORT_WEB_UI=8082 docker-compose -f docker-compose.yml up -d`
The docker-compose is the standard one provided [here](https://github.com/localstack/localstack/blob/master/docker-compose.yml).
...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

...

**Comment by whummer** [comment]
Many thanks for reporting this issue @A-R-Smith . This should be fixed in the `latest` version - can you please do a `docker pull localstack/localstack` and give it another try with the `latest` version of the Docker image? Please report here if the problem persists. Thanks!
