### ISSUE TITLE
Use aioboto3 as a backend for async calls

### ISSUE THREAD

**Issue by Akm0d** [localstack/localstack#2695]
# Type of request: This is a ...
[x] feature request

# Detailed description
Is it possible to drop-in replace boto3 with aioboto3 for asynchronous calls?

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-213) by [Unito](https://www.unito.io/learn-more)

**Comment by whummer** [comment]
Thanks for this suggestion @Akm0d . Can you please elaborate a bit on what would be the expected benefit, and why this should be done? Would love to start the discussion, but we'd need to understand the broader impact first. Thanks
