### ISSUE TITLE
LocalStack:Cloudformation Issue

### ISSUE THREAD

**Issue by RSHUKL01** [localstack/localstack#2696]
I am trying to create a stack through below command.

[template.txt](https://github.com/localstack/localstack/files/4889003/template.txt)

Command Used:
aws cloudformation validate-template --template-body file://template.json --endpoint-url=http://localhost:443

There is no valid response 
Response:
{
    "Parameters": [],
    "Description": "",
    "Capabilities": [],
    "CapabilitiesReason": "",
    "DeclaredTransforms": []
}

Then moving ahead 

- I created Key pair and describe it. Successfully created and got valid response on describing key pair.

After that I create stack in which I am getting error:
Command Used:
aws cloudformation create-stack --stack-name examplestack --template-body file://template.json --parameters ParameterKey=KeyExample ParameterValue=KeyExample --endpoint-url=http://localhost:443

Error: Unable to parse response (syntax error: line 1, column 54), invalid XML received. Further retries may succeed:
b'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">\n<title>500 Internal Server Error</title>\n<h1>Internal Server Error</h1>\n<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>\n'

@whummer  Can you please look into this?

**Comment by whummer** [comment]
Thanks for reporting @RSHUKL01 . Please see my comment in #2700 - can you kindly please provide a complete, isolated example (with a short code snippet, and/or the complete sequence of steps, including the CF template file), as well as the detailed error logs of the LocalStack container (with `DEBUG=1` enabled in the LocalStack configuration) to help reproduce this issue. Thanks
