### ISSUE TITLE
LocalStack: CloudFormation

### ISSUE THREAD

**Issue by RSHUKL01** [localstack/localstack#2697]
I am trying to delete my stack with the below command but unable to it.

Command:
 aws cloudformation delete-stack --stack-name examplestack1 --endpoint-url=http://localhost:443

Error:
Unable to parse response (not well-formed (invalid token): line 1, column 0), invalid XML received. Further retries may succeed:
b'{}'

@whummer  Can you please look into this. The stack which I created is in "CREATE_IN_PROGRESS" status and the status is not changing. I have raised an issue for the same. For reference please refer link https://github.com/localstack/localstack/issues/2696

**Comment by whummer** [comment]
Thanks for reporting @RSHUKL01 . Please see my comment in #2700 - can you kindly please provide a complete, isolated example (with a short code snippet, and/or the complete sequence of steps), as well as the detailed error logs of the LocalStack container (with `DEBUG=1` enabled in the LocalStack configuration) to help reproduce this issue. Thanks

**Comment by whummer** [comment]
Thanks for reporting @RSHUKL01 . This should be fixed upstream in https://github.com/spulec/moto/pull/3120 and is now available in the `latest` version of LocalStack - can you please do a `docker pull localstack/localstack` and give it another try? Please report here if the problem persists. Thanks

**Comment by RSHUKL01** [comment]
@whummer The issue is not yet fixed and giving the same error. I have pulled the latest docker image and try the same commands. Could you please reproduce it? Also let me know what command you are executing in case it work fine for you.

**Comment by usmangani1** [comment]
@RSHUKL01 
Please find the aws cli commands which are being used to create and delete the stack.As mentioned in the issue #2698 there is some issue with the template dynamo.json which is being used.Please correct that and try with the latest docker image.

```
$ awslocal cloudformation create-stack --stack-name examplestack1 --template-body file://dynamo.json
{
    "StackId": "arn:aws:cloudformation:us-east-1:000000000000:stack/examplestack1/4ceae632-5ee4-4b39-a316-448b56b07acb"
}

$ awslocal cloudformation delete-stack --stack-name examplestack1
$ awslocal cloudformation list-stacks --stack-status-filter CREATE_COMPLETE
{
    "StackSummaries": []
}
$ docker images | grep localstack
localstack/localstack   latest                   6110f7cf464f        9 hours ago         664MB
```
Please let us know in case if you have any other issue with the same.Thanks

**Comment by whummer** [comment]
Thanks for the update @usmangani1 . @RSHUKL01 if this problem persists with the `latest` version of the Docker image (after pulling it from Docker Hub), then please provide exact steps to reproduce, similar to the `awslocal` commands above. Many thanks for your help.
