### ISSUE TITLE
LocalStack: CloudFormation

### ISSUE THREAD

**Issue by RSHUKL01** [localstack/localstack#2699]
@whummer  

I am trying to list the stack resource but unable to do it. It is giving me the error. 

Command used: 
 aws cloudformation list-stack-resources --stack-name examplestack1 --endpoint-url=http://localhost:443

Screenshot 
![list stack resource](https://user-images.githubusercontent.com/65276850/86902841-20b9f100-c12c-11ea-9c98-f67cb7ef8ab6.PNG)

Error: Unable to parse response (syntax error: line 1, column 54), invalid XML received. Further retries may succeed:
b'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">\n<title>500 Internal Server Error</title>\n<h1>Internal Server Error</h1>\n<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>\n'

@whummer please help

**Comment by whummer** [comment]
Thanks for reporting @RSHUKL01 . Please see my comment in #2700 - can you kindly please provide a complete, isolated example (with a short code snippet, and/or the complete sequence of steps), as well as the detailed error logs of the LocalStack container (with `DEBUG=1` enabled in the LocalStack configuration) to help reproduce this issue. Thanks

**Comment by whummer** [comment]
@RSHUKL01 This should be fixed upstream in https://github.com/spulec/moto/pull/3120 and is now available in the `latest` version of LocalStack - can you please do a `docker pull localstack/localstack` and give it another try? Please report here if the problem persists. Thanks

**Comment by RSHUKL01** [comment]
@whummer We are getting the same error. Could you please try at your end and given me the commands which you are running so that we can re-produce at our end.
