### ISSUE TITLE
LocalStack:CloudFormation

### ISSUE THREAD

**Issue by RSHUKL01** [localstack/localstack#2700]
@whummer  I am trying to run below command to validate the template body used for creation of stack, The response which I am getting does not match the response I use to get in AWS. Let me know your response here. 

  aws cloudformation validate-template --template-body file://IAM.json --endpoint-url=http://localhost:443                                                 {
    "Parameters": [],
    "Description": "",
    "Capabilities": [],
    "CapabilitiesReason": "",
    "DeclaredTransforms": []
}

**Comment by whummer** [comment]
Thanks @RSHUKL01 . I noticed that you've created a couple of issues in the last 2-3 days. We appreciate that you take the initiative to report these issues, but can we please ask you to try and prepare your bug reports a bit more carefully by adhering to the following guidelines:
(1) use the Github search function to check if a related/similar issue already exists in the backlog
(2) create titles that reflect a proper summary of the issue being reported 
(3) try and combine similar/related problems into a single Github issue, and
(4) generally provide a concise description (including your environment configuration) and a complete, self-contained example to reproduce the issue.

This would greatly help us reproduce these issues and find a fix more efficiently/easily. Many thanks!

In particular, kindly please provide a small, isolated example (including the template body) to reproduce the issue being reported here (as well as the other issues you've reported). Thanks

**Comment by RSHUKL01** [comment]
[CloudFormation Issue Sheet.xlsx](https://github.com/localstack/localstack/files/4896574/CloudFormation.Issue.Sheet.xlsx)

Hi @whummer I have consolidate all the issues in excel sheet regarding cloud formation.
This excel sheet contain the following items:
Docker File Used
All Reported issues in different sheet.

Sheet further Contain
Issue Description
Command Used
Template Used
Error Message
Docker Log
Expected Output

Let me know if you need any other details on the same. @whummer Thanks for quick response here. Waiting for your response after you reproduce the issue and resolved them. Thanks.

**Comment by whummer** [comment]
Thanks again for providing the details @RSHUKL01 . Most of the linked issues in the sheet are now tracked elsewhere or have been resolved in the meantime. In case there are any additional issues, please open a follow-up ticket with detailed instruction on how to reproduce. Thanks!
