### ISSUE TITLE
SQS FIFO queue. The request include parameter that is not valid for this queue type

### ISSUE THREAD

**Issue by RuslanKharevych** [localstack/localstack#2705]
I use TestContainers with LocalStack for integration testing. But i can not send message to fifo queue.
`Nested exception is software.amazon.awssdk.services.sqs.model.SqsException: Value group-1 for parameter MessageGroupId is invalid. The request include parameter that is not valid for this queue type.`

Creating of fifo queue:
``` 
sqsClient.createQueue(CreateQueueRequest.builder()
                .queueName("test.fifo")
                .attributes(Map.of(
                        QueueAttributeName.CONTENT_BASED_DEDUPLICATION, "true",
                        QueueAttributeName.FIFO_QUEUE, "true"
                ))
                .build());
```

Sending of message:
``` 
SendMessageRequest sendMessageRequest = SendMessageRequest.builder()
                    .queueUrl(changeLogQueueUrl)
                    .messageBody(objectMapper.writeValueAsString(event))
                    .messageGroupId(groupId))
                    .messageDeduplicationId(event.getUuid())
                    .build();
sqsClient.sendMessage(sendMessageRequest);
```

**Comment by whummer** [comment]
Thanks for reporting @RuslanKharevych . This appears to be fixed (or at least is not reproducible) in the `latest` version - a simple integration test has been added in #2711 . Can you please do a `docker pull localstack/localstack` and ensure that your TestContainers setup is using the `latest` version of the Docker image? Please report (here with a small, fully self-contained example to reproduce) if the problem persists. Thanks

**Comment by RuslanKharevych** [comment]
> Thanks for reporting @RuslanKharevych . This appears to be fixed (or at least is not reproducible) in the `latest` version - a simple integration test has been added in #2711 . Can you please do a `docker pull localstack/localstack` and ensure that your TestContainers setup is using the `latest` version of the Docker image? Please report (here with a small, fully self-contained example to reproduce) if the problem persists. Thanks

@whummer now i get following error:
```Factory method 'sqsClient' threw exception; nested exception is software.amazon.awssdk.core.exception.Crc32MismatchException: Expected 1370073245 as the Crc32 checksum but the actual calculated checksum was 1782967770```

**Comment by Hainesy** [comment]
This issue seems to have reared its head again on localstack v13

**Comment by bidego** [comment]
Yup @Hainesy, just had to downgrade to 0.12.20

**Comment by heshamnaim** [comment]
I am seeing this issue 0.13.3

**Comment by sergey-telpuk** [comment]
I see too

**Comment by AndrejLukasevic** [comment]
Still in 0.14

**Comment by mindler-olli** [comment]
Workaround:

```
{
.
.
MessageGroupId: process.env.LOCALSTACK_HOSTNAME ? undefined : someId,
.
.
}
```
