### ISSUE TITLE
0.11.3: Rejected promise does not fail lambda invocation

### ISSUE THREAD

**Issue by artamonovkirill** [localstack/localstack#2706]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

0.11.3: Rejected promise does not fail lambda invocation.
In 0.11.2, the same steps failed the lambda invocation.

## Expected behavior

Lambda invocation fails.

## Actual behavior

Lambda invocation succeeds.

# Steps to reproduce

## Command used to start LocalStack

Started via TestContainers: https://github.com/artamonovkirill/localstack-lambda/blob/master/src/test/groovy/LocalStack.groovy

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

AWS SDK 2 for Java: `lambda.invoke { it.functionName('lambda') }`

A complete example can be found here: https://github.com/artamonovkirill/localstack-lambda/blob/master/src/test/groovy/LambdaSpec.groovy

**Comment by whummer** [comment]
Thanks for reporting @artamonovkirill . I believe the behavior you're seeing should be the correct one. I just did a quick test and deployed the test Lambda (with function body `exports.handler = () => Promise.reject()`) to LocalStack, as well as real AWS:

LocalStack:
```
$ awslocal lambda invoke --function-name test1 /tmp/out1.log
{
    "StatusCode": 200,
    "FunctionError": "Unhandled",
    "LogResult": "",
    "ExecutedVersion": "$LATEST"
}
$ echo $?
0
```

Real AWS:
```
$ aws lambda invoke --function-name test1 /tmp/out2.log
{
    "StatusCode": 200,
    "FunctionError": "Unhandled",
    "ExecutedVersion": "$LATEST"
}
$ echo $?
0
```

So, it seems that perhaps the behavior must have been incorrect in previous versions of LocalStack. Can you please double-check and also compare the behavior against real AWS? Please report here if you identify any reproducible discrepancies. Thanks!

**Comment by artamonovkirill** [comment]
@whummer , thanks for looking into the issue!
Indeed, the behavior is now correct - also according to the AWS documentation: https://docs.aws.amazon.com/lambda/latest/dg/nodejs-exceptions.html
I should've looked up that first myself.
