### ISSUE TITLE
Request to describe alarms for Metrics fails

### ISSUE THREAD

**Issue by uyadavv** [localstack/localstack#2707]
# Type of request: This is a feature request

# Detailed description
I have executed this command: 
" aws cloudwatch describe-alarms-for-metric --metric-name UsageMetrics --namespace NewPosts --endpoint-url=http://localhost:4566 "and getting Error.
--

"
...

## Expected behavior
Command must executed successfully.
...

## Actual behavior
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

# Steps to reproduce
1. Start the LocalStack
2. Execute the command in mentioned order:
aws cloudwatch put-metric-data --namespace "UsageMetrics" --metric-data file://metric.json --endpoint-url=http://localhost:4566
aws cloudwatch describe-alarms-for-metric --metric-name UsageMetrics --namespace NewPosts --endpoint-url=http://localhost:4566
--

## Command used to start LocalStack
docker-compose up
...

...

**Comment by whummer** [comment]
Thanks for reporting @uyadavv . This should be fixed upstream in spulec/moto#3148 - can you please give it another try with the `latest` version of the Docker image? Please report here if the problem persists. Thanks
