### ISSUE TITLE
When no EC2 instance and SNS topic is created then how the Put metric alarm command Executed

### ISSUE THREAD

**Issue by uyadavv** [localstack/localstack#2708]
# Type of request: This is a bug

# Detailed description

I executed this command "aws cloudwatch put-metric-alarm --alarm-name cpu-mon --alarm-description "Alarm when CPU exceeds 70 percent" --metric-name CPUUtilization --namespace AWS/EC2 --statistic Average --period 300 --threshold 70 --comparison-operator GreaterThanThreshold  --dimensions "Name=InstanceId,Value=i-12345678" --evaluation-periods 2 --alarm-actions arn:aws:sns:us-east-1:111122223333:MyTopic --unit Percent --endpoint-url=http://localhost:4566" and there is no instance created nor sns topic then how this command executed successfully.
...

## Expected behavior
Command must not execute.
...

## Actual behavior
Command executed successfully.
...

# Steps to reproduce

1. Start the localstack.
2. Execute these command in mentioned order:
a). aws cloudwatch put-metric-alarm --alarm-name cpu-mon --alarm-description "Alarm when CPU exceeds 70 percent" --metric-name CPUUtilization --namespace AWS/EC2 --statistic Average --period 300 --threshold 70 --comparison-operator GreaterThanThreshold  --dimensions "Name=InstanceId,Value=i-12345678" --evaluation-periods 2 --alarm-actions arn:aws:sns:us-east-1:111122223333:MyTopic --unit Percent --endpoint-url=http://localhost:4566 
b). aws cloudwatch describe-alarms --alarm-names "test-alarm-metric" --endpoint-url=http://localhost:4566

## Command used to start LocalStack
docker-compose up
...

**Comment by whummer** [comment]
Thanks for reporting @uyadavv . This appears to be the expected behavior, we're seeing the same behavior when running the request against real AWS:
```
$ aws cloudwatch put-metric-alarm --alarm-name cpu-mon --alarm-description "Alarm when CPU exceeds 70 percent" --metric-name CPUUtilization --namespace AWS/EC2 --statistic Average --period 300 --threshold 70 --comparison-operator GreaterThanThreshold --dimensions "Name=InstanceId,Value=i-12345678" --evaluation-periods 2 --alarm-actions arn:aws:sns:us-east-1:111122223333:MyTopic --unit Percent
$ echo $?
0
$ aws cloudwatch describe-alarms --alarm-names cpu-mon
{
    "MetricAlarms": [
        {
            "AlarmName": "cpu-mon",
            ...
            "AlarmActions": [
                "arn:aws:sns:us-east-1:111122223333:MyTopic"
            ],
...
```

Please re-open this issue if you have more evidence and a concrete example that the behavior diverges from real AWS. Thanks!
