### ISSUE TITLE
Can't queue multiple messages on SQS within a single message group

### ISSUE THREAD

**Issue by svenallers** [localstack/localstack#2710]
# Type of request: This is a bug report

# Detailed description
It is not possible to queue multiple messages within a single message group when using a FIFO queue with Sqs. Instead one can only receive the first message every following message is ignored.

## Expected behavior
Every message that is sent to a message group, should be received in order with calling `receive-message` on the SQS queue.

## Actual behavior
Only the first message that is sent to the queue can be received every following message is ignored.

# Steps to reproduce

## Command used to start LocalStack
```
docker run --env SERVICES="dynamodb,kinesis,sqs" --env TMPDIR="/tmp" --name localstack --publish 4568:4568 --publish 4569:4569 --publish 8080:8080 --publish 4576:4576 --rm localstack/localstack:0.11.2
```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
```
% awslocal sqs create-queue --queue-name q2.fifo  --attributes "FifoQueue=true"
{
    "QueueUrl": "http://localhost:4576/queue/q2.fifo"
}
% awslocal sqs send-message --queue-url http://localhost:4576/queue/q2.fifo --message-group-id 123 --message-deduplication-id 1 --message-body e1
{
    "MD5OfMessageBody": "cd3dc8b6cffb41e4163dcbd857ca87da",
    "MessageId": "60cddfd2-f460-4fa6-9082-f7add868677c"
}
% awslocal sqs send-message --queue-url http://localhost:4576/queue/q2.fifo --message-group-id 123 --message-deduplication-id 2 --message-body e2
{
    "MD5OfMessageBody": "68a9e49bbc88c02083a062a78ab3bf30",
    "MessageId": "b606e6a2-5e83-4c09-8041-f935d5ccc362"
}
% awslocal sqs send-message --queue-url http://localhost:4576/queue/q2.fifo --message-group-id 123 --message-deduplication-id 3 --message-body e3
{
    "MD5OfMessageBody": "7ed21b04c0dcde1c638e5c8480ad0026",
    "MessageId": "a0795291-8174-43ca-84a0-208ea7ed95eb"
}
% awslocal sqs receive-message --queue-url http://localhost:4576/queue/q2.fifo                                                                   
{
    "Messages": [
        {
            "MessageId": "60cddfd2-f460-4fa6-9082-f7add868677c",
            "ReceiptHandle": "60cddfd2-f460-4fa6-9082-f7add868677c#664c3d54-8363-49b7-9afe-aca4747250a9",
            "MD5OfBody": "cd3dc8b6cffb41e4163dcbd857ca87da",
            "Body": "e1"
        }
    ]
}
% awslocal sqs receive-message --queue-url http://localhost:4576/queue/q2.fifo
% awslocal sqs receive-message --queue-url http://localhost:4576/queue/q2.fifo
```

**Comment by whummer** [comment]
Thanks for reporting @svenallers . This should be fixed in the latest version - a simple integration test has been added in #2713 . Can you please do a `docker pull localstack/localstack` and give it another try with the `latest` version of the Docker image? Please report here if the problem persists. Thanks

**Comment by svenallers** [comment]
@whummer I just checked locally with the `latest` version and the issue still exists for me

**Comment by svenallers** [comment]
@whummer I added a comment to the PR after I looked into the test a little bit deeper. Seems that it only succeeds because `MaxNumberOfMessages` is provided (https://github.com/localstack/localstack/pull/2713/files#r455313289)

**Comment by whummer** [comment]
Thanks for leaving a comment on PR #2713 and confirming that it works. 👍
