### ISSUE TITLE
Pre-flight response has correct headers but 404 status

### ISSUE THREAD

**Issue by vinicri** [localstack/localstack#2723]
# Type of request: This is a ...
[x] bug report
[ ] feature request

# Detailed description
Request below gets the following response. 

```
curl 'http://localhost:4567/restapis/cjhlullf4b/dev/_user_request_/user' \
  -X 'OPTIONS' \
  -H 'Connection: keep-alive' \
  -H 'Pragma: no-cache' \
  -H 'Cache-Control: no-cache' \
  -H 'Accept: */*' \
  -H 'Access-Control-Request-Method: POST' \
  -H 'Access-Control-Request-Headers: content-type' \
  -H 'Origin: http://localhost:3000' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: same-site' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Referer: http://localhost:3000/' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36' \
  -H 'Accept-Language: en-US,en;q=0.9,pt-BR;q=0.8,pt;q=0.7' \
  --compressed
```

```
HTTP/1.1 404 Not Found
Server: BaseHTTP/0.6 Python/3.8.2
Date: Tue, 14 Jul 2020 18:26:49 GMT
Content-Length: 95
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: HEAD,GET,PUT,POST,DELETE,OPTIONS,PATCH
Access-Control-Allow-Headers: content-type,authorization,content-type,content-md5,cache-control,x-amz-content-sha256,x-amz-date,x-amz-security-token,x-amz-user-agent,x-amz-target,x-amz-acl,x-amz-version-id,x-localstack-target,x-amz-tagging,*
Access-Control-Expose-Headers: x-amz-version-id

```

lambda function seems to be correctly setup 

```
  userPost:
    handler: src/handler.userPost
    events:
      - http:
          path: /user
          method: post
          cors: true
```

## Expected behavior
return correct http status

## Actual behavior
returning 404 status

# Steps to reproduce
Setup a API gateway endpoint which requires a pre-flight request

## Command used to start LocalStack
```
 localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - '4563-4599:4563-4599'
      - '8055:8080'
    environment:
      - DEFAULT_REGION=us-east-1
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - SERVICES=lambda,s3,apigateway,dynamodb,cloudformation,sts,iam,cloudwatch
      - LAMBDA_EXECUTOR=docker
      - LAMBDA_REMOTE_DOCKER=0
      - API_GATEWAY_ID=foobar
    volumes:
      - './.localstack:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-216) by [Unito](https://www.unito.io/learn-more)

**Comment by vinicri** [comment]
Digging into localhost code I see I'm reaching this case

`https://github.com/localstack/localstack/blob/master/localstack/services/apigateway/apigateway_listener.py`

```python
if integration['type'] == 'AWS':
elif integration['type'] == 'AWS_PROXY':
elif integration['type'] == 'HTTP':
else:
        msg = ('API Gateway integration type "%s" for method "%s" not yet implemented' %
               (integration['type'], method))
        LOGGER.warning(msg)
        return make_error_response(msg, 404)

```

how can I setup integration type? It looks it's set to `MOCK` now.

**Comment by graham-** [comment]
Running into the same issue unfortunately with localstack reporting:

`WARNING:localstack.services.apigateway.apigateway_listener: API Gateway integration type "MOCK" for method "OPTIONS" not yet implemented`

in the console output when running in debug.

Is there any workaround possible, as it fails on the browser pre-flight `OPTIONS` request when trying to access my API?

**Comment by pwnb0t** [comment]
I'm running into a similar issue. I don't even have the correct headers being returned on the 404 status of the preflight.

```
curl -I -X OPTIONS http://localhost:4567/restapis/se375f54dc/local/_user_request_/test
HTTP/1.1 404
content-type: text/html; charset=utf-8
content-length: 95
connection: close
date: Thu, 30 Jul 2020 21:24:14 GMT
server: hypercorn-h11
```

**Comment by whummer** [comment]
Thanks for reporting @pwnb0t @graham- @vinicri - this should be (hopefully) fixed, support for MOCK integration types has been added in the meantime. Can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists.. Thanks for your help!
