### ISSUE TITLE
Localstack not returning correct error code when retreiving S3 files in DEEP_ARCHIVE storage class.

### ISSUE THREAD

**Issue by tcnleung** [localstack/localstack#2724]
# Type of request: This is a ...

[X ] bug report
[ ] feature request

# Detailed description
When retrieving S3 files that are in the DEEP_ARCHIVE class, AWS S3 returns an InvalidObjectState error, but localstack allows the retrieval of the file.
...

## Expected behavior
Localstack should return InvalidObjectState error when retrieving S3 files in the DEEP_ARCHIVE storage class.
...

## Actual behavior
Localstack returns files in the DEEP_ARCHIVE storage class successfully.

...

# Steps to reproduce

## Command used to start LocalStack

docker run --rm -it \
-p 4566-4597:4566-4597 \
-e SERVICES=s3,iam,4566-4597 \ 
 localstack/loackstack.0.11.1.sh
...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

# Set file to deep archived class
aws --endpoint-url=http://localhost:4566 s3 cp s3://somebucket/somefile s3://somebucket/somefile --storage-class=DEEP_ARCHIVE  

# retrieve archved file
aws --endpoint-url=http://localhost:4566  s3api get-object --bucket somebucket --key somefile somefile

**Comment by whummer** [comment]
Thanks for reporting @tcnleung . This should be fixed in #2817 - can you please do a `docker pull localstack/localstack` and give it another try with the `latest` version of the Docker image? Please report here if the problem persists. Thanks
