### ISSUE TITLE
SSM labels are not supported

### ISSUE THREAD

**Issue by cscetbon** [localstack/localstack#2726]
# Type of request:

[X ] bug report

# Detailed description
Labels can't be used in a search. SSM can't find the parameter I look for if I prefix it by `:label`
...

## Expected behavior
returns a parameter version that was labeled with the label used to look it up
...

## Actual behavior
raises `ParameterNotFound` exception
...

# Steps to reproduce

## Command used to start LocalStack
docker run --rm -ti -e SERVICES=ssm -p 4583:4583 localstack/localstack
...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
```
import boto3

key = "/first/example"
ssm = boto3.client('ssm', endpoint_url="http://127.0.0.1:4583")

ssm.put_parameter(Name=key, Value='something-dev', Type='SecureString', Overwrite=True)
ssm.label_parameter_version(Name=key, ParameterVersion=1, Labels=['dev'])
ssm.put_parameter(Name=key, Value='something-prod', Type='SecureString', Overwrite=True)
ssm.label_parameter_version(Name=key, ParameterVersion=2, Labels=['prod'])
ssm.get_parameter(Name=key + ":prod", WithDecryption=True)
```
...

**Comment by whummer** [comment]
Thanks for reporting @cscetbon . This has been fixed upstream in spulec/moto#3191 and should be available in LocalStack now. Can you please pull the `latest` Docker image and give it another try? Please report here if the problem persists. Thanks
