### ISSUE TITLE
HTTP/2 doesn't seem to work

### ISSUE THREAD

**Issue by laurst** [localstack/localstack#2728]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description
I want to retrieve data using http2. My use case is to retrieve pre-signed s3 urls, but any GET request on endpoints of the form `/xxx/yyy` (made with curl) seem to fail with the error : 
```
curl: (92) HTTP/2 stream 0 was not closed cleanly: Unknown error code (err 1)
```
Other endpoints, like `/health` for instance, hang forever

## Expected behavior
It is possible to GET resources, like s3 objects, using http2

## Actual behavior
Curl returns an error

# Steps to reproduce
* Run localstack (I'm using latest)
* In a shell, run : 
```shell
curl --http2 http://localhost:4566/a/b
```
* Get an error

## Command used to start LocalStack
```
localstack start
```

**Comment by laurst** [comment]
In case it helps, here is the verbose output from the curl command : 

```
$ curl -v --http2 http://localhost:4566/a/b
*   Trying ::1:4566...
* Connected to localhost (::1) port 4566 (#0)
> GET /a/b HTTP/1.1
> Host: localhost:4566
> User-Agent: curl/7.70.0
> Accept: */*
> Connection: Upgrade, HTTP2-Settings
> Upgrade: h2c
> HTTP2-Settings: AAMAAABkAAQCAAAAAAIAAAAA
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 101 
< upgrade: h2c
< date: Thu, 16 Jul 2020 09:11:21 GMT
< server: hypercorn-h11
* Received 101
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Connection state changed (MAX_CONCURRENT_STREAMS == 100)!
* http2 error: Invalid HTTP header field was received: frame type: 1, stream: 1, name: [:status], value: [101]
* HTTP/2 stream 0 was not closed cleanly: Unknown error code (err 1)
* stopped the pause stream!
* Connection #0 to host localhost left intact
curl: (92) HTTP/2 stream 0 was not closed cleanly: Unknown error code (err 1)
```

And this is my curl version : 
```
$ curl --version
curl 7.70.0 (x86_64-pc-linux-gnu) libcurl/7.70.0 OpenSSL/1.1.1g zlib/1.2.11 libidn2/2.3.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh2/1.9.0 nghttp2/1.40.0
Release-Date: 2020-04-29
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets
```

**Comment by whummer** [comment]
Thanks for reporting @laurst . Looks like our underlying HTTP/2 server (hypercorn) does not properly support h2c (HTTP/2 without TLS), at least not in a way that `curl` can understand (it may work with other clients, though). Can you please give it a try with using the HTTPS endpoint instead:
```
$ curl -k --http2 https://localhost:4566/a/b
<?xml version="1.0" encoding="UTF-8"?>
<Error>
    <Code>NoSuchBucket</Code>
    <Message>The specified bucket does not exist</Message>
    <BucketName>a</BucketName>
    <RequestID>7a62c49f-347e-4fc4-9331-6e8eEXAMPLE</RequestID>
</Error>
```
If you're using `localhost.localstack.cloud` as the host name, you should be able to omit the "ignore SSL warnings" flag `-k` as well:
```
$ curl --http2 https://localhost.localstack.cloud:4566/a/b
...
```
Hope that helps - please keep us posted if there are any other issues. Thanks
