### ISSUE TITLE
Localstack in Docker without binding to Docker.sock daemon

### ISSUE THREAD

**Issue by jrbarret** [localstack/localstack#2733]
# Type of request: This is a ...
[ ] bug report
[x] feature request

# Detailed description
I would like to run localstack in docker environment where the docker daemon is unavailable due to security policy. In this secure docker env the docker daemon is protected. This makes it impossible to use the docker daemon to run localstack in docker container. eg volume '/var/run/docker.sock:/var/run/docker.sock'

Is there a way to run localstack in docker container without binding to the docker daemon ? eg volume '/var/run/docker.sock:/var/run/docker.sock'

Currently, I need to bind my localstack running in docker to the docker daemon and I need to bind my spring boot app running in docker to the docker daemon in order to use localstack across docker containers in local environment. But when I deploy to a secure environement where docker daemon is not available I am out of luck. Hoping that there is a way to work around the docker daemon and run in secure environment without docker daemon.
...

## Expected behavior
DOCKER COMPOSE:
version: '2.1'

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "4566-4599:4566-4599"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=${SERVICES- }
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - HOST_TMP_FOLDER=${TMPDIR}
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"

## Actual behavior
DOCKER COMPOSE
version: '2.1'

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "4566-4599:4566-4599"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=${SERVICES- }
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

# Steps to reproduce
Run localstack in Docker using Docker Compose

## Command used to start LocalStack
docker-compose up
...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
...

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-217) by [Unito](https://www.unito.io/learn-more)

**Comment by thrau** [comment]
Hi @jrbarret, LocalStack can in principle run without the docker host mounted into the container. You can comment out both the `DOCKER_HOST` variable and the respective volume mount in your docker compose. However, if you are running services that depend on docker, like running lambdas, there's no way around that at the moment. Most services should work without the docker host mount though. Please let us know if you have specific problems in a follow up issue. Thanks!

**Comment by domainio** [comment]
@thrau thanks for the clarification, can you please tell if SQS can run without the volume?
or volume is mandatory for SQS (such as for Lambda)?

**Comment by thrau** [comment]
hey @domainio , if you're only using SQS, you don't need to mount the docker socket into the localstack container

**Comment by bechampion** [comment]
Chipping in here , what aws function would require to pass in  docker.sock?
