### ISSUE TITLE
EMR- Could not resolve hostname ec2-184-0-0-1.us-west-1.compute.amazonaws.com: No such host is known.

### ISSUE THREAD

**Issue by RSHUKL01** [localstack/localstack#2736]
whummer I am trying to do ssh on my emr cluster but unable to do it.

**Command used to create EMR CLuster**
 aws emr create-cluster --name "Cluster with My Custom AMI" --custom-ami-id ami-a518e6df --ebs-root-volume-size 20 --applications Name=Hadoop Name=Hive Name=Spark --release-label emr-5.7.0 --use-default-roles --instance-count 1 --instance-type m4.large  --endpoint-url=http://localhost:443 

**Command used to do SSH:**
 aws emr ssh --cluster-id  j-O3ENOTWUXMZBQ --key-pair-file key-example.pem --endpoint-url=http://localhost:443 

**Error:**
ssh -o StrictHostKeyChecking=no -o ServerAliveInterval=10 -i key-example.pem hadoop@ec2-184-0-0-1.us-west-1.compute.amazonaws.com -t
ssh: Could not resolve hostname ec2-184-0-0-1.us-west-1.compute.amazonaws.com: No such host is known.

[docker compose file.txt](https://github.com/localstack/localstack/files/4936862/docker.compose.file.txt)
Docker composed file is attached.

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-218) by [Unito](https://www.unito.io/learn-more)

**Comment by RSHUKL01** [comment]
@whummer We have tried again with the latest docker image but yet we are getting the same error. Could you please help here?
Error:
Error:
ssh -o StrictHostKeyChecking=no -o ServerAliveInterval=10 -i key-example.pem hadoop@ec2-184-0-0-1.us-west-1.compute.amazonaws.com -t
ssh: Could not resolve hostname ec2-184-0-0-1.us-west-1.compute.amazonaws.com: No such host is known.

**Comment by whummer** [comment]
Thanks for reporting @RSHUKL01 . Please note that the `emr create-cluster` API call currently only creates the in-memory representation, but does not spin up an actual cluster. If you work with the EMR or Athena API, then we do, however, spin up the `localstack_bigdata` Docker container, which is a singleton container used to run any Athena queries, Hadoop/Spark jobs, etc. 

So, in case you need an environment where you can run your Big Data processing jobs with all the dependencies preinstalled,  you could run `docker exec -it localstack_bigdata bash` to obtain a shell into the running `localstack_bigdata` container. 

Hope that helps - if you can share a few more details about your use case, we'll be happy to look into it in more detail. Thanks!
