### ISSUE TITLE
QLDB Cannot read document from table

### ISSUE THREAD

**Issue by A-R-Smith** [localstack/localstack#2739]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description
Thanks for the fix on the [last](https://github.com/localstack/localstack/issues/2693) bug! But alas, the work never ends... here's another issue for you.

Inserting into a QLDB ledger table and reading a simple ION document in Localstack is working correctly. However, when I insert a slightly more complex ION document with a mix of data types, I am unable to read it back out of the table.

## Expected behavior
```
qldbshell > insert into TEST `{id:"d4fcbe9680784e9c8b526474df87a16f",rate:5.00d-2,date1:2020-07-17T14:29:42.909Z,date2:2040-07-04T12:00:00.000Z,another_id:"9d3cee8bf9ba4b9582999108d3cf83be",third_id:"82b5426afbdc4b58b209f4ecb7545198",bool_col:false,nullable_col:null,small_number:1.06800d-5}`
INFO:
{
 documentId: "F6qRFxiGUtt55OcuLBRiAx"
}
INFO: (0.2390s)
qldbshell > select * from TEST
INFO:
{
 id: "d4fcbe9680784e9c8b526474df87a16f",
 rate: 0.0500,
 date1: 2020-07-17T14:29:42.909Z,
 date2: 2040-07-04T12:00:00.000Z,
 another_id: "9d3cee8bf9ba4b9582999108d3cf83be",
 third_id: "82b5426afbdc4b58b209f4ecb7545198",
 bool_col: false,
 nullable_col: null,
 small_number: 0.0000106800
}
INFO: (0.3553s)
qldbshell >
```
## Actual behavior
```
qldbshell > insert into TEST `{id:"d4fcbe9680784e9c8b526474df87a16f",rate:5.00d-2,date1:2020-07-17T14:29:42.909Z,date2:2040-07-04T12:00:00.000Z,another_id:"9d3cee8bf9ba4b9582999108d3cf83be",third_id:"82b5426afbdc4b58b209f4ecb7545198",bool_col:false,nullable_col:null,small_number:1.06800d-5}`
INFO:
{
 documentId: "b8d2a610"
}
INFO: (0.9860s)
qldbshell > select * from TEST
WARNING: OCC conflict or retriable exception occurred: An error occurred (500) when calling the SendCommand operation (reached max retries: 0):
WARNING: OCC conflict or retriable exception occurred: An error occurred (500) when calling the SendCommand operation (reached max retries: 0):
WARNING: OCC conflict or retriable exception occurred: An error occurred (500) when calling the SendCommand operation (reached max retries: 0):
WARNING: OCC conflict or retriable exception occurred: An error occurred (500) when calling the SendCommand operation (reached max retries: 0):
WARNING: OCC conflict or retriable exception occurred: An error occurred (500) when calling the SendCommand operation (reached max retries: 0):
WARNING: Error while executing query: An error occurred (500) when calling the SendCommand operation (reached max retries: 0):
INFO: (6.7645s)
qldbshell >
```
# Steps to reproduce
1) Start localstack with commands below
2) Create the ledger with this command: `aws qldb create-ledger --name TEST --permissions-mode ALLOW_ALL --endpoint-url=http://localhost:4566`
3) Connect to ledger with qldbshell: `qldbshell --ledger TEST -s=http://localhost:4566`
4) Create a test table: `create table TEST`
5) Insert a document:
```
insert into TEST `{id:"d4fcbe9680784e9c8b526474df87a16f",rate:5.00d-2,date1:2020-07-17T14:29:42.909Z,date2:2040-07-04T12:00:00.000Z,another_id:"9d3cee8bf9ba4b9582999108d3cf83be",third_id:"82b5426afbdc4b58b209f4ecb7545198",bool_col:false,nullable_col:null,small_number:1.06800d-5}`
```
6) Try to read the document:
```
select * from TEST
```
## Command used to start LocalStack

`TMPDIR=/private$TMPDIR SERVICES=qldb PORT_WEB_UI=8082 docker-compose -f docker-compose.yml up -d`
The docker-compose is the standard one provided [here](https://github.com/localstack/localstack/blob/master/docker-compose.yml).

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

...

**Comment by whummer** [comment]
Thanks for reporting this issue @A-R-Smith . This should be fixed in the meantime - can you please pull the `latest` image again and give it another try? Please let us know if the problem persists. Would be great if you could share an extended example with us (either here, or directly in the Slack channel), so we can ensure that your use case is covered. Many thanks for your help!
