### ISSUE TITLE
When enabling SSL (USE_SSL), /health return {}

### ISSUE THREAD

**Issue by CyrilDevOps** [localstack/localstack#2742]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description
I start localstack with USE_SSL true and when I try to get the services status with https://localhost:4566/health, I got {},
same with http://localhost:4566/health
...

## Expected behavior
I expect to see a json long of my services with their status
...

## Actual behavior
curl http or https to /health return {}
...

# Steps to reproduce

## Command used to start LocalStack
we use docker-compose :
  localstack:
    image: localstack/localstack-light
    container_name: localstack
    environment:
      HOSTNAME: localhost
      SERVICES: ${LOCALSTACK_SERVICES:-kinesis,cloudwatch,dynamodb}
      KINESIS_ERROR_PROBABILITY: ${KINESIS_ERROR_PROBABILITY:- }
      LAMBDA_REMOTE_DOCKER: 'false'
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-dev}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-dev}
      DEFAULT_REGION: us-east-1
      AWS_CBOR_DISABLE: 'true'
      CBOR_ENABLED: 'true'
      USE_SSL: 'true'
    healthcheck:
      test: ["CMD", "curl", "-qf", "http://localhost:4566/health?reload"]
      interval: 30s
      timeout: 1s
      retries: 10
    networks:
      backend:
        aliases:
          - localstack
    ports:
      - 4566:4566
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - type: bind
        source: ./localstack/initaws.d
        target: /docker-entrypoint-initaws.d
        read_only: true
    tmpfs:
      - /tmp/localstack:exec,mode=600

I tried it with localstack/localstack image, localstack/localstack-light, and even a fresh image from a git clone of the repo.
...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

...

**Comment by whummer** [comment]
Thanks for reporting @CyrilDevOps . This should be fixed in #2744 - can you please give it a try with the `latest` version of the Docker image (once the image has finished building in Travis-CI)? Please report here if the problem persists. Thanks

**Comment by CyrilDevOps** [comment]
We tested it this morning, it seems to work correctly now,
we have a good answer to the /health url.

thanks.
