### ISSUE TITLE
api gateway getUsagePlans does not respect GetUsagePlansRequest withLimit 

### ISSUE THREAD

**Issue by marcuswr** [localstack/localstack#2752]
# Type of request: This is a ...

[X] bug report
[ ] feature request

# Detailed description
Sending a GetUsagePlansRequest with a limit set through the sdk returns more than limit results. When executed against aws, the limit is correctly respected.
...

## Expected behavior
Set limit to n, receive up to n results.
...

## Actual behavior
Set limit to n, receive > n results.
...

# Steps to reproduce
Startup apigateway localstack service.
Create n + 1 usage plans
Request n usage plans via the aws sdk (note, the aws cli using --max-items returns the expected number of resuts)

## Command used to start LocalStack
docker-compose up

docker-compose.yaml
version: '3'
services:
  localstack:
    image: localstack/localstack
    ports:
      - "4567:4567"
    environment:
      - SERVICES=apigateway
    volumes:
      - "/private${TMPDIR}/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
aws --endpoint http://localhost:4567 apigateway create-usage-plan --name "test-1"
aws --endpoint http://localhost:4567 apigateway create-usage-plan --name "test-2"
aws --endpoint http://localhost:4567 apigateway get-usage-plans --max-items 1 # <= works as expected

# repro with aws java sdk (scala)
import com.amazonaws.services.apigateway.model.GetUsagePlansRequest
import com.amazonaws.services.apigateway.AmazonApiGatewayClientBuilder
val config = new com.amazonaws.client.builder.AwsClientBuilder.EndpointConfiguration("http://localhost:4567", "us-east-1")
val client = AmazonApiGatewayClientBuilder.standard.withEndpointConfiguration(config).build
client.getUsagePlans(new GetUsagePlansRequest().withLimit(1)).getItems.size // returns 2 should be 1

**Comment by whummer** [comment]
Thanks for reporting @marcuswr . Please note that the Elasticsearch installation has recently been refactored, and this appears to be working in the `latest` version.

A quick Google search revealed that there seems to be a compatibility issue between this plugin and a built-in SQL plugin.
```
$ awslocal es create-elasticsearch-domain --domain-name dom1
$ docker exec -it localstack_main bash
# cd /tmp/localstack/elasticsearch/7.1.0/
# bin/elasticsearch-plugin install https://github.com/NLPchina/elasticsearch-sql/releases/download/7.1.0.0/elasticsearch-sql-7.1.0.0.zip
#  ./elasticsearch-plugin list
...
sql
# echo 'xpack.sql.enabled: false' >> config/elasticsearch.yml
```
... then restart, and it should work.

Please report here if the problem persists. Thanks
