### ISSUE TITLE
Vulnerable libraries packaged in 0.11.3 container image

### ISSUE THREAD

**Issue by OliverCole** [localstack/localstack#2754]
# Type of request: This is a bug report

# Detailed description
We scanned [`localstack/localstack:0.11.3`](https://hub.docker.com/layers/localstack/localstack/0.11.3/images/sha256-3e658f7976d54211c9a8d50c288b097af2d9ff11b6a001a472bf7f56f0307645?context=explore) and our tool flagged up 35 vulnerabilities in libraries included in the container image.

## Expected behavior
No vulnerabilities found on scan tools.

## Actual behavior
Scan results: [0.11.3.txt](https://github.com/localstack/localstack/files/4954149/0.11.3.txt)

# Steps to reproduce
Scan with a commercially available scan tool.

## Command used to start LocalStack
N/A

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
N/A

**Comment by whummer** [comment]
Thanks for reporting @OliverCole . Please note that LocalStack is meant to support your development and testing flow on your local machine (or within an isolated environment like a CI/CD pipeline), but should *never* be used in a production environment or with *any* sensitive data whatsoever.

I'm afraid that fixing all these warnings/errors is out of scope and not really feasible - we are mostly focused on functionality and providing the best possible parity with the AWS APIs. Security is not really a focus at this point, as LocalStack should not be considered a "secure" environment anyway.

A lot of the issues reported seem to be about transitive dependencies - while technically possible, it would take a lot of time to track down all of these individual issues and provide updates/fixes on an ongoing basis. For example, we're using a library called [`amazon-kclpy`](https://pypi.org/project/amazon-kclpy) which seems to be using a couple of JAR files that are reported as being outdated by your tool (e.g., `/opt/code/localstack/.venv/lib/python3.8/site-packages/amazon_kclpy/jars/jackson-databind-2.6.7.1.jar`).

Having said that, we are more than happy to accept pull requests that help reduce the number of vulnerabilities being reported. If you could take a stab at it, that would be much appreciated! (We'll be happy to provide guidance, as needed). Thanks

**Comment by OliverCole** [comment]
Thanks @whummer - I completely agree that localstack shouldn't be used in production or with sensitive data.

Sadly, all the containers we use are pulled into an internal registry, and we aren't allowed to pull in containers with this level of known vulnerabilities, regardless of intended usage.

Unfortunately that means we won't be able to use the localstack containers at all :(
