### ISSUE TITLE
SQS queues created via docker-entrypoint-initaws.d are missing

### ISSUE THREAD

**Issue by philBrown** [localstack/localstack#2755]
# Type of request: This is a ...

- [x] bug report
- [ ] feature request

# Detailed description

When using Docker Compose, SQS queues created using a shell script mounted in `/docker-entrypoint-initaws.d` are not available.

After the container is started, creating queues via the AWS CLI work as expected.

## Expected behavior

After starting the containers, I should be able to query and send messages to the queues created in the shell script.

## Actual behavior

Querying for queues via
``` bash
aws --endpoint-url=http://localhost:4566 sqs list-queues
```
returns an empty response. Attempting to send a message responds with

> An error occurred (AWS.SimpleQueueService.NonExistentQueue) when calling the SendMessage operation: The specified queue does not exist for this wsdl version.

Creating a queue from the host after the container has started works correctly

``` bash
aws --endpoint-url=http://localhost:4566 sqs create-queue --queue-name Foo
```
> ```
> {
>     "QueueUrl": "http://localhost:4566/000000000000/Foo"
> }
> ```
``` bash
aws --endpoint-url=http://localhost:4566 sqs send-message --queue-url http://localhost:4566/000000000000/Foo --message-body "hi"
```
> ```
> {
>    "MD5OfMessageBody": "49f68a5c8493ec2c0bf489821c21fc3b",
>    "MessageId": "a38a322b-eea2-9e9a-69b2-e8d1a0159ac6"
> }
> ```

# Steps to reproduce

Using docker-compose, I mount a directory with shell scripts to create some SQS queues

docker-compose.yml (just the important bits)
``` yml
environment:
  - DEFAULT_REGION=ap-southeast-2
  - SERVICES=sqs
volumes:
  - "./localstack:/docker-entrypoint-initaws.d"
```
localstack/init.sh
``` bash
#!/usr/bin/env bash
set -x

awslocal sqs create-queue --queue-name MyQueue

set +x
```

The output from `docker-compose up` shows that these _appear_ to be working

``` none
aws-localstack | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initaws.d/init.sh
aws-localstack | ++ awslocal sqs create-queue --queue-name MyQueue
aws-localstack | {
aws-localstack |     "QueueUrl": "http://localhost:4576/000000000000/MyQueue"
aws-localstack | }
aws-localstack | ++ set +x
```

After the container has started, from the host use the AWS CLI to try and query the queues

``` bash
aws --endpoint-url=http://localhost:4566 sqs list-queues
```

The response will be empty

## Command used to start LocalStack

``` bash
docker-compose up
```

**Comment by philBrown** [comment]
As an addendum, I've used the same approach for SNS topics and they work just fine.

**Comment by philBrown** [comment]
Think I may have found a work-around.

In my `docker-compose.yml` file, I had set the `DEFAULT_REGION` environment variable as instructed in the [Configuration](https://github.com/localstack/localstack#configurations) section.

I also had to set the `AWS_DEFAULT_REGION`, otherwise `awslocal` was defaulting to `us-east-1`

**Comment by whummer** [comment]
Hi @philBrown , thanks for reporting. Glad you were able to find a workaround! As you mentioned, the client-side region (`AWS_DEFAULT_REGION`) needs to match the server-side region (`DEFAULT_REGION`) in this case. Please let us know if there are any other issues. Thanks

**Comment by philBrown** [comment]
Might be worth mentioning that in the docs along side `DEFAULT_REGION`.
