### ISSUE TITLE
clientContext is always undefined on lambda invoke

### ISSUE THREAD

**Issue by yonahforst** [localstack/localstack#2758]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description
When invoking a Lambda function, we should be able to [pass a ClientContext base64 string](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Lambda.html#invoke-property) and receive it (decoded) in the handler function context object.

However when I console.log the context object, `clientContext` is always `undefined`
```
START RequestId: e3f4ff44-4122-181d-291e-d46263299088 Version: $LATEST

2020-07-22T09:39:14.813Z    e3f4ff44-4122-181d-291e-d46263299088    INFO      {} {
  callbackWaitsForEmptyEventLoop: [Getter/Setter],
  succeed: [Function],
  fail: [Function],
  done: [Function],
  functionVersion: '$LATEST',
  functionName: 'userMgr-local-users',
  memoryLimitInMB: '1536',
  logGroupName: '/aws/lambda/userMgr-local-users',
  logStreamName: '2020/07/22/[$LATEST]0c043fa44889969a82ad0b09bd15493d',
  clientContext: undefined,
  identity: undefined,
  invokedFunctionArn: 'arn:aws:lambda:eu-west-1:000000000000:function:userMgr-local-users',
  awsRequestId: 'e3f4ff44-4122-181d-291e-d46263299088',
  getRemainingTimeInMillis: [Function: getRemainingTimeInMillis]
}
END RequestId: e3f4ff44-4122-181d-291e-d46263299088

```

I've tried invoking via the js-sdk:
```js
lambda.invoke({
FunctionName: 'userMgr-local-users',
Payload: '{"foo":"bar"}'
ClientContext: 'eyJjdXN0b20iOnsieC1jb3JyZWxhdGlvbi10ZXN0LWN1aWQiOiJja2N4NGttNXUwMDAwMGNzM2NpbzdvODJsIn19'
}).promise()
```
and via the cli:
```
awslocal lambda invoke --function-name userMgr-local-users --client-context foo response.json
```
in both cases the context object on the invoked function has the property `clientContext: undefined`
...

## Expected behavior
The context object should contain a `clientContext` key whose value is a string passed by the invoker (base64 decoded, if invoked via the js sdk)
...

## Actual behavior
`clientContext` is always undefined
...

# Steps to reproduce

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
```
echo "exports.handler = console.log" > index.js &&  zip function.zip index.js
awslocal lambda create-function --function-name myFunc --handler index.handler --runtime nodejs12.x --zip-file=fileb://function.zip --role foo
awslocal lambda invoke --function-name myFunc response.json --client-context foo
awslogs get /aws/lambda/myFunc --aws-endpoint-url=http://localhost:4586
```
...

**Comment by whummer** [comment]
Thanks for reporting @yonahforst . This should be fixed in #2762 - can you please give it another try with the `latest` version of the Docker image?

Please note that the client context parameter is currently only working for Node.js Lambdas - support for other runtimes will be added shortly.

Please report here if the problem persists. Thanks

**Comment by yonahforst** [comment]
thanks @whummer! I've pulled the latest version and it's working. there's one small inconsistency: the context is not base64 decoded before it's passed to the lambda handler.

The js sdk says that you need to send the context as a base64 encoded string and the lambda receives it already decoded. (i don't think it needs to be encoded when you invoke the lambda via the cli)

**Comment by whummer** [comment]
@yonahforst  Thanks for the update - another change has been pushed in #2807 which should now (hopefully) fix it and provide the same behavior as in AWS. Please let us know if the problem persists. Thanks
