### ISSUE TITLE
Lambda from CF Template not found

### ISSUE THREAD

**Issue by ghost** [localstack/localstack#2759]
# Type of request: This is a ...
[x] bug report
[ ] feature request

# Detailed description
When attempting to create a lambda from a CloudFormation template with the code stored in a Localstack S3 bucket I always receive:
`localstack_1   | 2020-07-22T12:34:27:WARNING:localstack.services.awslambda.lambda_api: Function not found: arn:aws:lambda:us-east-1:000000000000:function:my-stack-WriterLambda-KQSL7IWSQTUD` 
message in my logs and the lambda doesn't get created or work in Localstack.   The same exact CloudFormation template  works fine in AWS.

...

## Expected behavior
Lambda should work correctly when generated from a CF template
...

## Actual behavior
Error in docker-compose logs and WARNING
`localstack_1   | 2020-07-22T12:34:27:WARNING:localstack.services.awslambda.lambda_api: Function not found: arn:aws:lambda:us-east-1:000000000000:function:my-stack-WriterLambda-KQSL7IWSQTUD` and the lambda is non-functional or accessible although running 
`awslocal lambda list-functions` shows the function was created so it seems to be an issue with the the lambda access the zip file code in S3. 
...

# Steps to reproduce
Create CF template with a simple lambda, run the following commands (I'm doing this from a simple shell script inside /docker-entrypoint-initaws.d/localstack_init.sh ) and you will have to modify the --template-file and --body paths to suit your local setup.

```
export AWS_ACCESS_KEY_ID=localstack_secret
export AWS_SECRET_ACCESS_KEY=localstack_key


awslocal s3 mb s3://lambda-code-bucket --endpoint-url=http://localhost:4566

awslocal s3api put-object --bucket= lambda-code-bucket  --key lambda.zip --body lambda.zip --endpoint-url=http://localhost:4566

echo "---> Running LocalStack Cloudformation Deployment"

awslocal cloudformation deploy --template-file=cf_template.yml --region=us-east-1 --stack-name=my-stack --endpoint-url=http://localhost:4566

```

## Command used to start LocalStack
`docker-compose up`
...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
```
# this is the cf_template.yml file
---
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  DynamoWriterRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Join ["-", [{"Ref": "AWS::Region"}, {"Ref": "AWS::StackName"}, "DynamoWriterRole"]]
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: !Join ["-", [{"Ref": "AWS::Region"}, {"Ref": "AWS::StackName"}, "AllPolicies"]]
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: '*'
                Resource: '*'
                
  WriterLambda:
    Type: "AWS::Lambda::Function"
    Properties:
      Description: "Writer receives messages from SQS and writes them to DynamoDB"
      Handler: "lambda.handler"
      Role: !GetAtt DynamoWriterRole.Arn
      Code:
        S3Bucket: "lambda-code-bucket"
        S3Key: "lambda.zip"
      Runtime: "ruby2.7"
      MemorySize: 128

```

...

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-224) by [Unito](https://www.unito.io/learn-more)

**Comment by mengelseatz** [comment]
One quick followup - I tried doing an inline lambda as well just to test if it was somehow related to the S3 bucket code usage in a standard lambda but that also did not work and gives me the same errors both at startup and an inability to invoke the lambda from the command line or otherwise

```
      Code:
        ZipFile: |
          var aws = require('aws-sdk')
          var response = require('cfn-response')
          exports.handler = function(event, context) {
              console.log("REQUEST RECEIVED:\n" + JSON.stringify(event))
              response.send(event, context, "SUCCESS")
          }
        
      Runtime: "nodejs12.x"

```

**Comment by mengelseatz** [comment]
Also note that the lambdas ARE being copied into /tmp/localstack/zipfile.<key> in the Localstack container directory and unpacked. 

I've also pulled the latest Localstack as well just to make sure I was current with what's available.

thanks!

**Comment by mengelseatz** [comment]
OK sorry for the noise.. I was able to get my inline handler to work but had to remove the
```
var response = require('cfn-response')
```
as it's apparently not available in the lambda container.. still debugging but the use case of having a Code: entry in your CF template with a zip file stored in s3 doesn't work for the 3 runtimes I tried: ruby, python, js

**Comment by mengelseatz** [comment]
I was able to get inline javascript and python to work.   ZipFile's still don't work of the same code.

**Comment by whummer** [comment]
Thanks for reporting this issue @mengelseatz . Looks like you've been able to get it working with the `Code` parameter. What is the latest state of this - are you saying that the deployment is still failing if you use the `--template-file=cf_template.yml` parameter and point Lambda to the S3 bucket, is that correct? Thanks

**Comment by mengelseatz** [comment]
Yes @whummer I'm able to get the inline lambda working with both javascript and python but using a ZipFile key which I think is the more common case for anything more than a very simple bit of code it doesn't work.

**Comment by monty16597** [comment]
@mengelseatz Thank you for your reply. We have tried but we are not able to reproduce the issue. It might be possible that issue has already been resolved. Give it a try using latest release. Here is the reference to the repo (**https://github.com/monty16597/localstack-cf-zipfile**), we created to deploy stack according to your use-case, it might be helpful for you. **Thank you**

**Comment by dominikschubert** [comment]
Closing as stale
