### ISSUE TITLE
VPN Gateway attachment.vpc-id filter needs incorporated

### ISSUE THREAD

**Issue by alanbaldwin** [localstack/localstack#2761]
# Type of request: This is a ...

[X] bug report
[ ] feature request

# Detailed description

Trying to retrieve vpn gateways by vpc id fails. This has been fixed recently in the upstream library here: https://github.com/spulec/moto/issues/3154 but needs to be incorporated.  The attachment.vpc-id filter is used by terraform when creating an `aws_vpn_gateway_attachment` resource or an `aws_vpn_gateway` that's explicitly attached to a vpc, so it prevents mocking out creating those resources.

## Expected behavior

VPN Gateways should be able to be filtered by `attachment.vpc-id`

## Actual behavior

An error is returned from localstack:
```
b'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">\n<title>500 Internal Server Error</title>\n<h1>Internal Server Error</h1>\n<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>\n'
```

and the logs for localstack list the error:
```
moto.ec2.exceptions.FilterNotImplementedError: The filter 'attachment.vpc-id' for DescribeVpnGateways has not been implemented in Moto yet. Feel free to open an issue at https://github.com/spulec/moto/issues
```

# Steps to reproduce

## Command used to start LocalStack

`localstack -d start`

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

A minimal set of code to cause the error: 
```
awslocal ec2 create-vpn-gateway --type ipsec.1
awslocal ec2 describe-vpn-gateways --filter Name=attachment.vpc-id,Values=vpc-1234
```

**Comment by whummer** [comment]
Thanks for reporting @alanbaldwin . This should be fixed in the meantime - an integration test has been added in #2786 . Can you please do a `docker pull localstack/localstack` and give it another try with the `latest` version of the Docker image? Please report here if the problem persists. Thanks
