### ISSUE TITLE
Cache API Authorization for Pro features

### ISSUE THREAD

**Issue by badarsebard** [localstack/localstack#2764]
# Cached API Authorization for Pro features

[ ] bug report
[x] feature request

# Detailed description
When disconnected from the internet I'm unable to start the Pro features of localstack. Presumably because the API call fails. It would be nice if the authorization could be cached in some way so that the features remain active for a time until internet becomes available. This is particularly useful in my mind while traveling. Twenty-four hours seems like a reasonable time to live for the cached call.

**Comment by lfantone** [comment]
Another thing that I notice is if the `https://app.localstack.cloud/` is down, is not possible to start up localstack properly just hangs on:

```console
localstack_1  | Waiting for all LocalStack services to be ready
```

**Comment by whummer** [comment]
Thanks for this proposal @badarsebard @lfantone . This should be working in the `latest` version - can you please do `docker pull localstack/localstack` and give it another try?

Please make sure to mount a local folder from your disk into the LocalStack container under `/tmp/localstack`. When using the `localstack start` command, this happens automatically by default. 

Also, the default docker-compose.yml in this repo contains an instruction to mount a local tmp folder:
```
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
```
Once you're successfully authenticated, a cache token will be created locally which is valid for up to 24 hours. This should allow you to run LocalStack Pro offline for a certain period of time (e.g., when you're on a flight).

Hope that helps - please keep us posted how it goes, or if there are any issues. Thanks!
