### ISSUE TITLE
RDS Restoring from Snapshot is failing

### ISSUE THREAD

**Issue by bodiam** [localstack/localstack#2765]
# Type of request: This is a ...

[x ] bug report
[ ] feature request

# Detailed description

We're currently trying to write a small script which will create and restore snapshots. Currently, creating snapshots seems to work, but restoring is not. I'm a paid user, but unfortunately I can't see the source and see if this is implemented or not, I'm not sure where this is documented.

## Expected behavior

The RDS is restored

## Actual behavior

```
Unable to parse response (syntax error: line 1, column 54), invalid XML received:
b'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">\n<title>500 Internal Server Error</title>\n<h1>Internal Server Error</h1>\n<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>\n'
```

# Steps to reproduce

## Command used to start LocalStack

 SERVICES=s3,rds localstack start

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

awslocal rds create-db-instance --db-instance-identifier db2 --db-instance-class c1 --engine postgres
awslocal rds create-db-snapshot --db-snapshot-identifier db2-snapshot --db-instance-identifier db2
awslocal rds restore-db-instance-from-db-snapshot --db-instance-identifier db2-restore --db-snapshot-identifier db2-snapshot

**Comment by whummer** [comment]
Thanks for reporting @bodiam . This should be fixed in the `latest` version - can you please do a `docker pull localstack/localstack` and give it another try? Please reach out to us - either here, or via the Slack community channel - and let us know if the problem persists. Many thanks for your help.

**Comment by bodiam** [comment]
Hi @whummer , thanks for the quick fix, I'll have a look at it in the next few days!
