### ISSUE TITLE
SQS "Unable to find forwarding rule for host" when using 4566

### ISSUE THREAD

**Issue by nejordan15** [localstack/localstack#2766]
# Type of request: This is a ...
[X] bug report
[ ] feature request

# Detailed description
On version v0.11.1 (also reproduced on 11.3), there is an error, ` Unable to find forwarding rule for host`, when accessing sqs via the edge service port `4566`. When using `4576` there is no issue. I bring up localstack and create a queue and then try reading off the queue (without messages on it). For port `4576` there is no error on the (aws cpp sdk) client side nor in the localstack logs. For port `4566` there is a client side error and a localstack error log.

Also, the same error comes up when hitting the health endpoint for the edge service.

```
docker: /seu$ curl http://localstack-panda-worker-sqs:4566/health
{"status": "running"}
(service: localstack-panda-worker-sqs) (step: shell-panda-worker-sqs-23daf695) 2020-07-24T18:38:04:INFO:localstack.services.edge: Unable to find forwarding rule for host "localstack-panda-worker-sqs:4566", path "/health", target header "", auth header ""
```

## Expected behavior
Accessing an sqs queue on port `4566` with not have an error, same behavior as accessing `4576`.

## Actual behavior
Localstack Log
`2020-07-24T18:11:25:INFO:localstack.services.edge: Unable to find forwarding rule for host "localstack-panda-worker-sqs:4566", path "/queue/panda_worker_queue0", target header "", auth header ""`

aws cpp sdk error (not very helpful)
`with address : 172.25.0.2`

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-225) by [Unito](https://www.unito.io/learn-more)

**Comment by nejordan15** [comment]
I have installed localstack with pip, version 11.3, and used `localstack start` to reproduce this issue. Above is with docker compose and version 11.1.
Seems like there are similar issues opened with other services, but figured I'd open one for sqs since I didn't see it mentioned in another open issue.

**Comment by whummer** [comment]
Thanks for reporting @nejordan15 . Please note that the format for queue URLs has recently changed. The path used to be `/queue/panda_worker_queue0`, but is now encoding the account ID instead of "queue": `/000000000000/panda_worker_queue0`. Hope that helps - can you please give it another try with the `latest` version and see if this is fixed? Thanks

**Comment by nejordan15** [comment]
How about for the health endpoint?

**Comment by rochdev** [comment]
I'm getting the same error with S3 only when using port 4566. Using the deprecated port 4572 resolves the issue. It seems like there is an issue with the proxy.

**Comment by rochdev** [comment]
I tried with latest and also with 0.11.2 and both result in the error.

**Comment by whummer** [comment]
Thanks @rochdev @nejordan15 - we have added various enhancements to the edge routing logic in the meantime, looks like this issue should be resolved in the meantime. Closing - but please do let us know if the problem persists.. Thanks!
