### ISSUE TITLE
Cognito service function sign_up actually makes an admin_sign_up

### ISSUE THREAD

**Issue by Vaunorage** [localstack/localstack#2769]
# Type of request: This is a ...

[X ] bug report
[ ] feature request

# Detailed description
I wanted to test the sign up cognito service confirmation but did not get an email with the link. On closer inspection, I saw that localstack generates a temporary password which is a behavior found on admin_sign_up

## Expected behavior
Getting an email on my email address

## Actual behavior

![image](https://user-images.githubusercontent.com/10731763/88445339-e8830580-cdef-11ea-83b9-66622331e1a9.png)

# Steps to reproduce

## Command used to start LocalStack

>> docker run -it -e SERVICES="cognito,dynamodb" -e DEFAULT_REGION="us-east-1" -e LOCALSTACK_HOSTNAME="localhost" -e TEST_AWS_ACCOUNT_ID="000000000000" -e LOCALSTACK_API_KEY="srcx3NA47Y" -p 0.0.0.0:53:53 -p 0.0.0.0:53:53/udp -p 443:443 -p 4566:4566 --rm --privileged --name localstack_main -p 4569:4569 -p 4590-4591:4590-4591 -p 8080-8081:8080-8081 -v "/tmp/localstack:/tmp/localstack" -v "/var/run/docker.sock:/var/run/docker.sock" -e DOCKER_HOST="unix:///var/run/docker.sock" -e HOST_TMP_FOLDER="/tmp/localstack" "localstack/localstack" -e DNS_ADDRESS=0

>>client = boto3.client('cognito-idp', region_name='us-east-1', endpoint_url=Config.get_cognito_infos())
>> client.sign_up( ClientId=self.pool_infos[entity]["ClientId"], Username=username,Password=password,UserAttributes=userattributes )

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

...

**Comment by whummer** [comment]
Thanks for reporting @Vaunorage, and apologies for the long delay. This functionality should be working in the meantime, can you please give it another try after pulling the `latest` Docker image?

Please note that in order for the email sending to be enabled, you'll need to configure the `SMTP_HOST`, `SMTP_USER`, and `SMTP_PASS` environment variables.

After starting up LocalStack Pro with these configurations, I'm running this command:
```
$ awslocal cognito-idp sign-up --client-id $clientId --username testuser --password test123 --user-attributes Name=email,Value=test@example.com
```
... and then these logs appear in the LocalStack terminal output:
```
2020-08-30T08:59:09:INFO:localstack_ext.services.cognito.cognito_helpers: Confirmation code for Cognito user foo1: 4d6f0d17
2020-08-30T08:59:09:DEBUG:localstack_ext.utils.email_utils: Sending email to test@example.com
```
Hope that helps - please let us know if there any other issues with this feature. Thanks for your help!
