### ISSUE TITLE
awslocal ec2 authorize-security-group-ingress: cant add permission

### ISSUE THREAD

**Issue by AlexMcowkin** [localstack/localstack#2775]
# Type of request: This is a bug. I try to add description to my permission list.
when I try to describe my group I cant fing description

[*] bug report
[ ] feature request

# Detailed description
try to add permissions with description. the description does not save.
...

## Expected behavior
want to see the description
...

## Actual behavior
no description
                {
                    "FromPort": 5060,
                    "IpProtocol": "udp",
                    "IpRanges": [
                        {
                            "CidrIp": "217.26.172.176/32"
                        }
                    ],
                    "ToPort": 5060,
                    "UserIdGroupPairs": []
                },
                {
                    "FromPort": 5060,
                    "IpProtocol": "udp",
                    "IpRanges": [
                        {
                            "CidrIp": "217.26.172.177/32"
                        }
                    ],
                    "ToPort": 5060,

...

# Steps to reproduce

## Command used to start LocalStack

  localstack:
    image: localstack/localstack:0.11.0
    environment:
      - SERVICES=s3,iam,ec2
      - USE_SSL=false
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    ports:
      - "4592:4572"
      - "4595:4593"
      - "4568:4566"
      - "8095:8080"
      - "4585:4597"
    volumes:
      - ./docker/data/s3:/tmp/localstack/data
      - ./docker/localstack:/docker-entrypoint-initaws.d
    networks:
      - my-net
...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

// create new group
awslocal ec2 create-security-group --group-name my-security-group --description "docker security group"

// get group id
id=$(awslocal ec2 describe-security-groups --filters Name=group-name,Values=my-security-group --query "SecurityGroups[*].{ID:GroupId}" --output text)

// add default permissions
awslocal ec2 authorize-security-group-ingress --group-id $id --ip-permissions IpProtocol=udp,FromPort=5060,ToPort=5060,IpRanges='[{CidrIp=217.26.172.177/32,Description="SIP for site, Added by coder"},{CidrIp=217.26.172.173/32,Description="SIP for site, Added by coder"}]'

...

**Comment by usmangani1** [comment]
@AlexMcowkin Thanks for creating the issue.Using which command are you trying to retrieve the data of the permissions added.Where is this description missing? Can you please help us out with this command.It will help us resolving the issue a bit sooner.Thanks

**Comment by AlexMcowkin** [comment]
Hi.
I use docker on windows10 pro.

this is code in my docker compose file
`localstack:
image: localstack/localstack:0.11.0
environment:
- SERVICES=s3,iam,ec2
- USE_SSL=false
- DEBUG=1
- DATA_DIR=/tmp/localstack/data
ports:
- "4592:4572"
- "4595:4593"
- "4568:4566"
- "8095:8080"
- "4585:4597"
volumes:
- ./docker/data/s3:/tmp/localstack/data
- ./docker/localstack:/docker-entrypoint-initaws.d
networks:
- my-net`

After I run my docker I load my localstack container
`docker exec -ti ccmlocal_localstack_1 /bin/bash`

_inside container I run:_

`
**// create new group**
awslocal ec2 create-security-group --group-name my-security-group --description "docker security group"
`

`
**// get group id**
id=$(awslocal ec2 describe-security-groups --filters Name=group-name,Values=my-security-group --query "SecurityGroups[*].{ID:GroupId}" --output text)

**// add default permissions**
awslocal ec2 authorize-security-group-ingress --group-id $id --ip-permissions IpProtocol=udp,FromPort=5060,ToPort=5060,IpRanges='[{CidrIp=217.26.172.177/32,Description="SIP for site, Added by coder"},{CidrIp=217.26.172.173/32,Description="SIP for site, Added by coder"}]'
`
On this step I added descriptions.


finally I want to see my created groups
`awslocal ec2 describe-security-groups`


everything is OK but I dont see descriptions

**Comment by whummer** [comment]
Thanks for reporting @AlexMcowkin - this should be fixed upstream in spulec/moto#3196 and should now be available in LocalStack. Can you please pull the Docker image and give it another try with the `latest` version? Please report here if the problem persists. Thanks
