### ISSUE TITLE
Secrets manager: get random password returns incorrect length

### ISSUE THREAD

**Issue by melcloud** [localstack/localstack#2779]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description
When getting a random password from localstack secrets manager, the length of the returned password is incorrect when specifying exclude characters 

## Expected behavior
When generating a 120 characters password without certain characters, such as "'@, it should return the expected length of 120

## Actual behavior
It returns random length. Looks like it generates a 120 characters string than removing all those excluded characters

# Steps to reproduce

## Command used to start LocalStack
docker run -p 4566:4566 -e SERVICES=secretsmanager -e DEFAULT_REGION=ap-southeast-2 -e DOCKER_HOST=unix:///var/run/docker.sock localstack/localstack:latest

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

```csharp
var getRandomPasswordRequest = new GetRandomPasswordRequest
{
    ExcludeCharacters = "/@\"'\\",
    PasswordLength = 120
};

var randomPasswordResponse = await _secretsManager.GetRandomPasswordAsync(getRandomPasswordRequest);
```

**Comment by whummer** [comment]
Thanks for reporting @melcloud . This should be fixed upstream in spulec/moto#3213 - a simple integration test has been added in #2830 . Can you please pull the Docker image again and give it another try with the `latest` version? Please report here if the problem persists. Thanks
