### ISSUE TITLE
SQS doesn't work

### ISSUE THREAD

**Issue by natanaelAguiar** [localstack/localstack#2784]
# I'm facing a problem when running localstack

[x] bug report
[ ] feature request

# Detailed description
When i run the localstack image i'm facing some connections refused errors. It's intermitent sometimes happens and sometimes doesnt. Follow the stacktrace:

> 2020-07-28T21:12:20:WARNING:localstack.utils.server.http2_server: Error in proxy handler for request POST http://localstack:4566/: MyHTTPConnectionPool(host='ce84afd67bb5', port=4576): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1b9f1811f0>: Failed to establish a new connection: [Errno 111] Connection refused')) Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

# Steps to reproduce
As this problem is an intermitent one probably you will need to do sometimes. All that I do its run the localstack via docker compose.

> localstack:
    image: localstack/localstack:0.11.3
    ports:
      - "4566:4566"
      - "8088:8080"
    environment:
      - SERVICES=sqs,sns
      - DEFAULT_REGION=us-east-1
      - HOSTNAME_EXTERNAL=localstack

## Command used to start LocalStack
 docker-compose up

**Comment by whummer** [comment]
Thanks for reporting @natanaelAguiar . Can you please check if this issue is reproducible with the `latest` version of the Docker image?

```
docker pull localstack/localstack
```

In docker-compose.yml:
```
 image: localstack/localstack:latest
```
Thanks

**Comment by natanaelAguiar** [comment]
I found the problem. On the project that i'm working was using the atlasian/localstack version that is no long active, and we had not this problem with it. So basically the problem was that we had more services running in the same docker-compose file, that was trying access the aws services that were not up, because the localstack image was not ready, i just put a health check to start these containers only when the localstack become ready.
