### ISSUE TITLE
No support for AvailabilityZoneId when creating subnet

### ISSUE THREAD

**Issue by ncarroll0488** [localstack/localstack#2788]
# Type of request: This is a ...

[x] bug report
[] feature request

# Detailed description
When invoking `Action=CreateSubnet` using the `AvailabilityZoneId` parameter alongside a blank `AvailabilityZone` parameter, localstack ignores the value provided in `AvailabilityZoneId` and returns an error.
```
Value () for parameter availabilityZone is invalid.
```
This causes creation of subnets to fail, and third-party tools such as Terraform to eventually time out after re-submitting the request several times.

When invoking `Action=CreateSubnet` using the `AvailabilityZoneId` parameter without an `AvailabilityZone` parameter, localstack ignores the value provided in `AvailabilityZoneId` and creates the subnet in a random AZ.

## Expected behavior
Localstack should handle the `AvailabilityZoneId` parameter in the request URI, and set the availability zone appropriately. 

## Actual behavior
Localstack appears to completely ignore the `AvailabilityZoneId` parameter and returns an error if the mutually exclusive argument `AvailabilityZone` is present and empty. This does not reflect the behavior on real-world AWS regions.

```
Value () for parameter availabilityZone is invalid. Subnets can currently only be created in the following availability zones: af-south-1a, [...]
```

If `AvailabilityZone` is absent, Localstack ignores the provided value for `AvailabilityZoneId` and creates the subnet in whichever random AZ it chooses.

# Steps to reproduce
Invoke the CreateSubnet API call with a valid `AvailabilityZoneId` parameter and an empty `AvailabilityZone` parameter.
```
Action=CreateSubnet&AvailabilityZone=&AvailabilityZoneId=use1-az6&CidrBlock=203.0.113.0%2F24&Version=2016-11-15&VpcId=vpc-abcdef12
```
Alternately, Invoke the API call without specifying an empty `AvailabilityZone` parameter (this is what awslocal does):
```
Action=CreateSubnet&AvailabilityZoneId=use1-az6&CidrBlock=203.0.113.0%2F24&Version=2016-11-15&VpcId=vpc-abcdef12

{
    "Subnet": {
        "AvailabilityZone": "us-east-1e",
        "AvailabilityZoneId": "use1-az3",
        "AvailableIpAddressCount": 251,
        "CidrBlock": "203.0.113.0/24",
        "DefaultForAz": false,
        "MapPublicIpOnLaunch": false,
        "State": "pending",
        "SubnetId": "subnet-XXXXXXXX",
        "VpcId": "vpc-XXXXXXXX",
        "OwnerId": "111122223333",
        "AssignIpv6AddressOnCreation": false,
        "Ipv6CidrBlockAssociationSet": [],
        "SubnetArn": "<snip>"
    }
}
```
## Command used to start LocalStack
(in virtualenv) `localstack start`

### Blank AvailabilityZone
Awslocal cannot reproduce the error caused by a blank `AvailabilityZone` parameter. To observe this, you will have to send an HTTP request manually or use something other than awslocal/awscli. This could also be observed with terraform:
```hcl
resource "aws_vpc" "vpc" {
  cidr_block = "172.16.0.0/16"
}
resource "aws_subnet" "subnet" {
  vpc_id               = aws_vpc.vpc.id
  cidr_block           = "172.16.0.0/24"
  availability_zone_id = "use1-az6"
}
```
### No AvailabilityZone
This is how you observe the mismatched ID. It may require a few invocations due to random assignment.
```
awslocal create-vpc --cidr-block 172.16.0.0/16
awslocal create-subnet --cidr-block 172.16.0.0/24 --availability-zone-id use1-az6 --vpc-id vpc-XXXXXXXX
```

**Comment by whummer** [comment]
Thanks for the update @ncarroll0488 . This should be fixed upstream in spulec/moto#3198 and is now available in LocalStack. Can you please give it another try with the `latest` version of the Docker image? Please report here if the problem persists. Thanks!
