### ISSUE TITLE
WARNING:localstack_ext.services.cloudfront.cloudfront_api: Not yet implemented: Unable to find path mapping for POST /2020-05-31/distribution

### ISSUE THREAD

**Issue by joside** [localstack/localstack#2791]
# Type of request: This is a ...

[X] bug report
[ ] feature request

# Detailed description
Just installed localstack and following the cloudfront example on your doc page. (https://app.localstack.cloud/docs#cloudfront)
awslocal cloudfront create-distribution   --origin-domain-name bucket1.s3.amazonaws.com
responds with
An error occurred (404) when calling the CreateDistribution operation: Not Found

In the docker-compose logs this appears:
localstack_1  | 2020-07-30T12:52:47:WARNING:localstack_ext.services.cloudfront.cloudfront_api: Not yet implemented: Unable to find path mapping for POST /2020-05-31/distribution

...

## Expected behavior

...

## Actual behavior

...

# Steps to reproduce

## Command used to start LocalStack
docker-compose up with file from your examples, own api key)
...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

...

**Comment by whummer** [comment]
Thanks for reporting this issue @joside . This should be fixed in the `latest` version - can you please do a `docker pull localstack/localstack` and give it another try? Please let us know if the issue persists (either here or directly in our Slack channel). Thanks for your help!
