### ISSUE TITLE
RDS: Can't create snapshot anymore

### ISSUE THREAD

**Issue by bodiam** [localstack/localstack#2793]
# Type of request: This is a ...

[ x] bug report
[ ] feature request

# Detailed description

Last week, I've reported a bug saying that creating RDS snapshots cannot be restored. You've implemented a fix for that, thank you for that, so now I'm running on `0.11.3`. I can now create and restore snapshots using the `awslocal` command. 

However, when I use the Java API to restore a snapshot, it fails, because of the data parsing:

```
Exception in thread "main" software.amazon.awssdk.core.exception.SdkClientException: Unable to unmarshall response (Text '2020-07-31 01:03:08.249000+00:00' could not be parsed at index 10). Response Code: 200, Response Text: 
	at software.amazon.awssdk.core.exception.SdkClientException$BuilderImpl.build(SdkClientException.java:98)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleSuccessResponse(CombinedResponseHandler.java:108)
```

## Expected behavior

Snapshot can be restored

## Actual behavior

Snapshot cannot be restored and gives date parse exception

# Steps to reproduce

## Command used to start LocalStack

awslocal rds create-db-instance --db-instance-identifier db1 --db-instance-class c1 --engine postgres

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

```

        val client = RdsClient.builder()
            .region(Region.US_EAST_1)
            .endpointOverride(URI("http://localhost:443"))
            .credentialsProvider(
                ProfileCredentialsProvider.builder()
                    .profileName("localstack")
                    .build()
            ).build()


        val snapshotInstance = "db1-snapshot" + System.currentTimeMillis()

        val request = CreateDbSnapshotRequest.builder()
            .dbInstanceIdentifier("db1")
            .dbSnapshotIdentifier(snapshotInstance)
            .build()

        val describeDBInstances = client.describeDBInstances()
        println(describeDBInstances)

        val response = client.createDBSnapshot(request)
        println(response)

        val restoreDbRequest = RestoreDbInstanceFromDbSnapshotRequest.builder()
            .dbInstanceIdentifier("db1-dl")
            .dbSnapshotIdentifier(snapshotInstance)
            .build()

        val snapshot = client.restoreDBInstanceFromDBSnapshot(restoreDbRequest)  // THIS IS FAILING

        println(snapshot)

```

**Comment by whummer** [comment]
Thanks for the detailed report - this should be fixed in the `latest` version of the Docker image. Please let us know if the problem persists. Thanks for your help!
