### ISSUE TITLE
RDS: can't execute describeInstance() twice

### ISSUE THREAD

**Issue by bodiam** [localstack/localstack#2794]
# Type of request: This is a ...

[ x] bug report
[ ] feature request

# Detailed description

With the code in my previous bug report, when I execute the describeInstances() twice, LocalStack is failing with an error

## Expected behavior

I can describeInstances()

## Actual behavior

describeInstances() is giving this error:

```
Exception in thread "main" software.amazon.awssdk.services.rds.model.RdsException: null (Service: Rds, Status Code: 500, Request ID: null, Extended Request ID: null)
```

When looking at localStack itself, there is an error too, and it looks like this:

```
2020-07-31T01:23:33:WARNING:localstack.utils.server.http2_server: Error in proxy handler for request POST http://localhost:443/: list indices must be integers or slices, not str Traceback (most recent call last):
  File "/opt/code/localstack/localstack/utils/server/http2_server.py", line 83, in index
    result = await run_sync(handler, request, data)
  File "/opt/code/localstack/localstack/utils/async_utils.py", line 46, in run_sync
    return await loop.run_in_executor(THREAD_POOL, copy_context().run, func, *args)
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 555, in handler
    response = modify_and_forward(method=method, path=path_with_params, data_bytes=data, headers=headers,
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/utils/aws/aws_utils.py", line 19, in modify_and_forward
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 398, in modify_and_forward
    updated_response = update_listener.return_response(**kwargs)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/rds/rds_listener.py", line 94, in return_response
TypeError: list indices must be integers or slices, not str
```

# Steps to reproduce

## Command used to start LocalStack

```
awslocal rds create-db-instance --db-instance-identifier db1 --db-instance-class c1 --engine postgres
```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

Execute the following code **twice** (first time it will fail for different reasons)

```

        val client = RdsClient.builder()
            .region(Region.US_EAST_1)
            .endpointOverride(URI("http://localhost:443"))
            .credentialsProvider(
                ProfileCredentialsProvider.builder()
                    .profileName("localstack")
                    .build()
            ).build()


        val snapshotInstance = "db1-snapshot" + System.currentTimeMillis()

        val request = CreateDbSnapshotRequest.builder()
            .dbInstanceIdentifier("db1")
            .dbSnapshotIdentifier(snapshotInstance)
            .build()

        val describeDBInstances = client.describeDBInstances()
        println(describeDBInstances)

        val response = client.createDBSnapshot(request)
        println(response)

        val restoreDbRequest = RestoreDbInstanceFromDbSnapshotRequest.builder()
            .dbInstanceIdentifier("db1-dl")
            .dbSnapshotIdentifier(snapshotInstance)
            .build()

        val snapshot = client.restoreDBInstanceFromDBSnapshot(restoreDbRequest)

        println(snapshot)
```

**Comment by usmangani1** [comment]
@bodiam  Thanks for reporting the issue here.

We tried to reproduce this issue by using these aws cli commands given below and we are not successful to reproduce the issue.

 awslocal rds create-db-instance --db-instance-identifier db1 --db-instance-class c1 --engine postgres
{
    "DBInstance": {
        "DBInstanceIdentifier": "db1",
        "DBInstanceClass": "c1",
        "Engine": "postgres",
        "DBInstanceStatus": "available",
        "MasterUsername": "test",
        "DBName": "test",
        "Endpoint": {
            "Address": "localhost",
            "Port": 4513
        },
        "AllocatedStorage": 20,
        "InstanceCreateTime": "2020-08-01T22:22:31.176Z",
        "PreferredBackupWindow": "03:50-04:20",
        "BackupRetentionPeriod": 1,
        "DBSecurityGroups": [],
        "VpcSecurityGroups": [],
        "DBParameterGroups": [
            {
                "DBParameterGroupName": "default.postgres9.3",
                "ParameterApplyStatus": "in-sync"
            }
        ],
        "PreferredMaintenanceWindow": "wed:06:38-wed:07:08",
        "MultiAZ": false,
        "EngineVersion": "9.3.3",
        "AutoMinorVersionUpgrade": false,
        "ReadReplicaDBInstanceIdentifiers": [],
        "LicenseModel": "license-included",
        "OptionGroupMemberships": [
            {
                "OptionGroupName": "default.postgres9.3",
                "Status": "in-sync"
            }
        ],
        "PubliclyAccessible": false,
        "StatusInfos": [],
        "StorageType": "gp2",
        "StorageEncrypted": false,
        "DbiResourceId": "db-M5ENSHXFPU6XHZ4G4ZEI5QIO2U",
        "CopyTagsToSnapshot": false,
        "DBInstanceArn": "arn:aws:rds:us-east-1:000000000000:db:db1",
        "IAMDatabaseAuthenticationEnabled": false
    }
}

 awslocal  rds describe-db-instances 
{
    "DBInstances": [
        {
            "DBInstanceIdentifier": "db1",
            "DBInstanceClass": "c1",
            "Engine": "postgres",
            "DBInstanceStatus": "available",
            "MasterUsername": "test",
            "DBName": "test",
            "Endpoint": {
                "Address": "localhost",
                "Port": 4513
            },
            "AllocatedStorage": 20,
            "InstanceCreateTime": "2020-08-01T22:22:31.176Z",
            "PreferredBackupWindow": "03:50-04:20",
            "BackupRetentionPeriod": 1,
            "DBSecurityGroups": [],
            "VpcSecurityGroups": [],
            "DBParameterGroups": [
                {
                    "DBParameterGroupName": "default.postgres9.3",
                    "ParameterApplyStatus": "in-sync"
                }
            ],
            "PreferredMaintenanceWindow": "wed:06:38-wed:07:08",
            "MultiAZ": false,
            "EngineVersion": "9.3.3",
            "AutoMinorVersionUpgrade": false,
            "ReadReplicaDBInstanceIdentifiers": [],
            "LicenseModel": "license-included",
            "OptionGroupMemberships": [
                {
                    "OptionGroupName": "default.postgres9.3",
                    "Status": "in-sync"
                }
            ],
            "PubliclyAccessible": false,
            "StatusInfos": [],
            "StorageType": "gp2",
            "DBClusterIdentifier": "",
            "StorageEncrypted": false,
            "DbiResourceId": "db-M5ENSHXFPU6XHZ4G4ZEI5QIO2U",
            "CopyTagsToSnapshot": false,
            "DBInstanceArn": "arn:aws:rds:us-east-1:000000000000:db:db1",
            "IAMDatabaseAuthenticationEnabled": false
        }
    ]
}

 awslocal rds create-db-snapshot     --db-instance-identifier db1  --db-snapshot-identifier mydbsnapshot1
{
    "DBSnapshot": {
        "DBSnapshotIdentifier": "mydbsnapshot1",
        "DBInstanceIdentifier": "db1",
        "SnapshotCreateTime": "2020-08-01T22:22:55.742Z",
        "Engine": "postgres",
        "AllocatedStorage": 20,
        "Status": "available",
        "Port": 4513,
        "AvailabilityZone": "None",
        "VpcId": "",
        "InstanceCreateTime": "2020-08-01T22:22:55.742Z",
        "MasterUsername": "test",
        "EngineVersion": "9.3.3",
        "LicenseModel": "license-included",
        "SnapshotType": "manual",
        "OptionGroupName": "default.postgres9.3",
        "PercentProgress": 100,
        "SourceRegion": "us-east-1",
        "SourceDBSnapshotIdentifier": "",
        "StorageType": "gp2",
        "TdeCredentialArn": "",
        "Encrypted": false,
        "KmsKeyId": "None",
        "DBSnapshotArn": "arn:aws:rds:us-east-1:000000000000:snapshot:mydbsnapshot1",
        "Timezone": "",
        "IAMDatabaseAuthenticationEnabled": false
    }
}

awslocal rds restore-db-instance-from-db-snapshot --db-instance-identifier db1 --db-snapshot-identifier mydbsnapshot1 
{
    "DBInstance": {
        "DBInstanceIdentifier": "db1",
        "DBInstanceClass": "db.m1.small",
        "Engine": "postgres",
        "DBInstanceStatus": "available",
        "MasterUsername": "test",
        "DBName": "test",
        "Endpoint": {
            "Address": "localhost",
            "Port": 4513
        },
        "AllocatedStorage": 20,
        "InstanceCreateTime": "2020-08-01 22:23:07.053000+00:00",
        "PreferredBackupWindow": "03:50-04:20",
        "BackupRetentionPeriod": 1,
        "DBParameterGroups": [
            {},
            {}
        ],
        "PreferredMaintenanceWindow": "wed:06:38-wed:07:08",
        "MultiAZ": false,
        "EngineVersion": "9.3.3",
        "AutoMinorVersionUpgrade": false,
        "LicenseModel": "license-included",
        "OptionGroupMemberships": [
            {},
            {}
        ],
        "PubliclyAccessible": false,
        "StorageType": "gp2",
        "StorageEncrypted": false,
        "DbiResourceId": "db-M5ENSHXFPU6XHZ4G4ZEI5QIO2U",
        "CopyTagsToSnapshot": false,
        "DBInstanceArn": "arn:aws:rds:us-east-1:000000000000:db:db1",
        "IAMDatabaseAuthenticationEnabled": false
    }
}

 awslocal  rds describe-db-instances 
{
    "DBInstances": [
        {
            "DBInstanceIdentifier": "db1",
            "DBInstanceClass": "db.m1.small",
            "Engine": "postgres",
            "DBInstanceStatus": "available",
            "MasterUsername": "test",
            "DBName": "test",
            "Endpoint": {
                "Address": "localhost",
                "Port": 4513
            },
            "AllocatedStorage": 20,
            "InstanceCreateTime": "2020-08-01T22:23:07.053Z",
            "PreferredBackupWindow": "03:50-04:20",
            "BackupRetentionPeriod": 1,
            "DBSecurityGroups": [],
            "VpcSecurityGroups": [],
            "DBParameterGroups": [
                {
                    "DBParameterGroupName": "default.postgres9.3",
                    "ParameterApplyStatus": "in-sync"
                }
            ],
            "PreferredMaintenanceWindow": "wed:06:38-wed:07:08",
            "MultiAZ": false,
            "EngineVersion": "9.3.3",
            "AutoMinorVersionUpgrade": false,
            "ReadReplicaDBInstanceIdentifiers": [],
            "LicenseModel": "license-included",
            "OptionGroupMemberships": [
                {
                    "OptionGroupName": "default.postgres9.3",
                    "Status": "in-sync"
                }
            ],
            "PubliclyAccessible": false,
            "StatusInfos": [],
            "StorageType": "gp2",
            "DBClusterIdentifier": "",
            "StorageEncrypted": false,
            "DbiResourceId": "db-M5ENSHXFPU6XHZ4G4ZEI5QIO2U",
            "CopyTagsToSnapshot": false,
            "DBInstanceArn": "arn:aws:rds:us-east-1:000000000000:db:db1",
            "IAMDatabaseAuthenticationEnabled": false
        }
    ]
}

Can you please attach the whole script file using which you are trying to invoke the rds client ? This would help us to reproduce the issue and resolve it a bit sooner.Thanks

**Comment by bodiam** [comment]
Hi @usmangani1 , thanks for the response. I'm not sure why you're posting those awslocal commands, I've posted a Kotlin script in my issue which I use to reproduce the issue, please use that one

**Comment by whummer** [comment]
Thanks for the detailed report - this should be fixed in the `latest` version of the Docker image. Please let us know if the problem persists. Thanks for your help!

**Comment by bodiam** [comment]
Thanks for fixing, but we've decided that LocalStack is a little too instable for us at the moment.
