### ISSUE TITLE
Can't update scheduled lambda functions or state machines

### ISSUE THREAD

**Issue by yonahforst** [localstack/localstack#2803]
# Type of request: This is a ...
[x] bug report
[ ] feature request

# Detailed description
When I use serverless-localstack to deploy a lambda function with a schedule attached, the initial deploy works, but then I cannot update the stack. The same thing happens when I try to update a serverless stack which contains a stepfunction (using serverless-step-functions)

I get the following errors:
`type object 'LambdaPermission' has no attribute 'delete_from_cloudformation_json'`
`type object 'StateMachine' has no attribute 'update_from_cloudformation_json'`

Seems to be related to https://github.com/localstack/localstack/issues/1248
...

## Expected behavior
Function should update as normal
...

## Actual behavior
Can't update these functions. I need to restart localstack, and deploy them as if for the first time
...

# Steps to reproduce
deploy a serverless.yml which contains a function like this, and then try to update it

```yml
functions:
  cronJon:
    handler: cronJob.handler
    events:
      - schedule: rate(1 day)
```

## Command used to start LocalStack
...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
...

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-229) by [Unito](https://www.unito.io/learn-more)

**Comment by pinzon** [comment]
@yonahforst 
Hi. could you try again with the most recent version of localstack?

I just tried this.
1.- downloaded the [localstack-demo](https://github.com/whummer/localstack-demo) 
2.- Added a cronjob function and event.
3.- Deploy the serverless stack
4.- excuting again the command to update the stack

I had no issues updating the stack. maybe it is already fixed.

**Comment by whummer** [comment]
Thanks @yonahforst @pinzon . Closing this issue as outdated - our CloudFormation implementation has been rewritten entirely in the meantime, and this issue should now (hopefully) be resolved. Please let us know if the problem persists.. Thanks!
