### ISSUE TITLE
EC2 run-instances error for Pro Version

### ISSUE THREAD

**Issue by srakhe-uptycs** [localstack/localstack#2809]
# Type of request: This is a ...
[x] bug report

# Detailed description
When running run-instances on localstack, it runs as expected on a normal docker installation but when configured to run with an API key, it throws an error. In some cases the instance is initialised despite this and in other cases the command waits for the connection that is errored, to complete which results in indefinite wait time. (Note: Nothing is listening on this port)

## Expected behavior
Expected behavior is that the run-instances command results in creating an instance as:

```
{
    "Groups": [
        {
            "GroupName": "default",
            "GroupId": "sg-245f6a01"
        }
    ],
    "Instances": [
        {
            "AmiLaunchIndex": 0,
            "ImageId": "None",
            "InstanceId": "i-ef0d6cbea2bf4f181",
            "InstanceType": "m1.small",
            "KernelId": "None",
            "KeyName": "None",
            "LaunchTime": "2020-08-04T13:58:27+00:00",
            "Monitoring": {
                "State": "enabled"
            },
            "Placement": {
                "AvailabilityZone": "us-east-1a",
                "GroupName": "",
                "Tenancy": "default"
            },
            "PrivateDnsName": "ip-10-210-91-238.ec2.internal",
            "PrivateIpAddress": "10.210.91.238",
            "PublicDnsName": "ec2-54-214-107-236.compute-1.amazonaws.com",
            "PublicIpAddress": "54.214.107.236",
            "State": {
                "Code": 0,
                "Name": "pending"
            },
            "StateTransitionReason": "",
            "SubnetId": "subnet-32f8413f",
            "VpcId": "vpc-a5ebfbb9",
            "Architecture": "x86_64",
            "ClientToken": "",
            "EbsOptimized": false,
            "Hypervisor": "xen",
            "NetworkInterfaces": [
                {
```

## Actual behavior
An indefinite wait time with error in logs such as:

```
Unable to parse response (not well-formed (invalid token): line 1, column 0), invalid XML received. Further retries may succeed:
b'{}'
```

With error log:

```
requests.exceptions.ConnectionError: MyHTTPConnectionPool(host='172.17.0.1', port=4535): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0f584fa040>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

# Steps to reproduce
Initialize localstack with API key
Run the ec2 command

## Command used to start LocalStack
sudo docker-compose up

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
`aws ec2 run-instances --endpoint-url https://localhost:443 --no-verify-ssl`

My docker-compse.yml:

```
version: '2.0'
services:
  localstack:
    image: localstack/localstack:0.11.3
    container_name: localstack_demo
    ports:
      - '443:443'
      - '4510:4520:4510:4520'
      - '4563-4620:4563-4620'
      - '8055:8080'

    environment:
      - LOCALSTACK_API_KEY=123123123
      - DEBUG=1
      - SERVICES=ec2,iam,s3
      - EDGE_PORT=443
      - DEFAULT_REGION=us-east-1
      - TEST_AWS_ACCOUNT_ID=111111111111
```

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-230) by [Unito](https://www.unito.io/learn-more)

**Comment by whummer** [comment]
Thanks for reporting @srakhe-uptycs . Please note that for certain features of EC2 (e.g., launching Virtual Machines in VirtualBox) we need to start up a small daemon process on the local machine. These daemon processes are started automatically if you use `localstack start` to start up the stack, but these processes need to be started separately in case docker-compose is used.

It basically boils down to:
```
$ pip install --upgrade --no-cache localstack localstack-ext
$ export LOCALSTACK_API_KEY=...
$ localstack daemons
```
Just to confirm - which operating system are you on? (I'm assuming Mac OS or Linux, given that you've mentioned `sudo` above.)

Thanks for pointing out this issue - we will also update our documentation accordingly. Hope that helps - please keep us posted. Feel free to get in touch with us directly via email or on the Slack channel. Thanks!

**Comment by srakhe-uptycs** [comment]
I am running localstack on Ubuntu 18.04.3 LTS. I followed the steps mentioned above and I'm getting this error:
```
Traceback (most recent call last):
  File "/home/abacus/.local/bin/localstack", line 14, in <module>
    from localstack.utils import cli
  File "/home/abacus/.local/lib/python2.7/site-packages/localstack/utils/cli.py", line 24, in <module>
    from localstack.utils import bootstrap
  File "/home/abacus/.local/lib/python2.7/site-packages/localstack/utils/bootstrap.py", line 14, in <module>
    import pip as pip_mod
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 31, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/lib/python2.7/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 40, in <module>
    from pip._vendor import requests, six
ImportError: cannot import name requests
```

**Comment by srakhe-uptycs** [comment]
I had already tried this fix but it didn't work, have been using normal localstack for ec2 work.

```
$ localstack daemons
/usr/share/python-wheels/requests-2.18.4-py2.py3-none-any.whl/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.25.10) or chardet (3.0.4) doesn't match a supported version!
ERROR: Invalid command "daemons"
```

I have the dependencies installed in pip.

**Comment by whummer** [comment]
Hi @srakhe-uptycs , thanks for the update. Can you please ensure that the `LOCALSTACK_API_KEY` is set properly in your environment, and that you're using the latest version of the pip package:

```
pip install --upgrade localstack localstack-ext localstack-client
```
Hope that helps - please let us know if the problem persists. Thanks for your help!
