### ISSUE TITLE
Localstack is not responding after having parallel calls to stepfunction's getActivityTask endpoint

### ISSUE THREAD

**Issue by ghosalya** [localstack/localstack#2815]
# Type of request: This is a ...
[x] bug report
[ ] feature request

# Detailed description
When there are many processes that tries to hit stepfunction's `getActivityTask` endpoint, other part of localstack is not responsive. I am trying to hit `getActivityTask` with multiple lambda invocations, but this is reproducible outside of lambda.

Scenario:

1. In stepfunctions, there is an Activity, and a State Machine that uses said Activity
1. There are multiple parallel calls to stepfunction's `getActivityTask` endpoint, and while one of them returns a taskToken, the other waits and eventually times out (this is okay for my use case.).

Localstack's docker logs does not seem to output anything relevant.

## Expected behavior
During/after the parallel calls, other localstack services should work fine:

* Visiting http://localhost:4566/health returns the health of services
* Callling other services with localstack works as per usual

## Actual behavior
During/after the parallel calls, localstack is no longer responding:

* Visiting http://localhost:4566/health does not return response
* Callling other services with localstack results in timeout

# Steps to reproduce
I have created a small example repo to reproduce the behavior in https://github.com/ghosalya/localstack_sfn_bugreport

## Command used to start LocalStack
Within the example repo, run `./start_localstack.sh` ([link to file](https://github.com/ghosalya/localstack_sfn_bugreport/blob/master/start_localstack.sh)). 

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
To set up relevant resources in localstack, within the repo, you can run `./setup_resources.sh` ([link to file](https://github.com/ghosalya/localstack_sfn_bugreport/blob/master/setup_resources.sh)). As this script requires some additional JSON files, it should be run within the containing directory.

You can then run `python notify_activity.py` ([link to file](https://github.com/ghosalya/localstack_sfn_bugreport/blob/master/notify_activity.py)). This starts 1 state machine execution, and then calls `getActivityTask` within multiple threads.

Afterwards, visit http://localhost:4566/health and it won't return a response.

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-231) by [Unito](https://www.unito.io/learn-more)

**Comment by pinzon** [comment]
Hi @ghosalya , sorry for the long answer after my assignation.  
I took the task to run your test against the current localstack project and it worked as you describe in the expected behaviour section. 
I also tested it with docker using just 1 cpu and 250mb the ram and it also worked fine. 

There has been several patch that target performance issues. Mine was the PR #3250.
It's probably that your problem has been already fixed but please let me know if you still have issues.
