### ISSUE TITLE
AWS secrets manager operations are not done according to specification

### ISSUE THREAD

**Issue by melcloud** [localstack/localstack#2831]
# Type of request: This is a ...
[x] bug report
[ ] feature request

# Detailed description
When putting secret value into a none-existing secret, it creates a new secret and a new version
...

## Expected behavior
According to the documentation: 
> Specifies the secret to which you want to add a new version. You can specify either the Amazon Resource Name (ARN) or the friendly name of the secret. **The secret must already exist.**

Expect the command `aws --endpoint-url=http://172.17.0.2:4566 secretsmanager put-secret-value --secret-id test --secret-string "test"` to fail initially as secret doesn't exist
...

## Actual behavior
localstack creates a new secret and attach AWSCURRENT label
...

# Steps to reproduce
1. Start localstack
1. Run aws command

## Command used to start LocalStack
docker run --rm -it -p 4566:4566 -e SERVICES=secretsmanager -e DEFAULT_REGION=ap-southeast-2 -v /var/run/docker.sock:/var/run/docker.sock --name localstack localstack/localstack:latest
...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
aws --endpoint-url=http://172.17.0.2:4566 secretsmanager put-secret-value --secret-id test --secret-string "test"
...

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-234) by [Unito](https://www.unito.io/learn-more)

**Comment by whummer** [comment]
Thanks for reporting @melcloud . This should be fixed in the meantime - can you please pull the `latest` Docker image and give it another try? Please report here if the problem persists. Thanks

**Comment by purvafos4x** [comment]
still have this issue
