### ISSUE TITLE
Kinesis register_stream_consumer returns wrong format for ConsumerCreationTimestamp

### ISSUE THREAD

**Issue by elainearbaugh** [localstack/localstack#2834]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description
[register_stream_consumer](https://github.com/localstack/localstack/blob/v0.11.3/localstack/services/kinesis/kinesis_listener.py#L34) returns ConsumerCreationTimestamp in the format ['%Y-%m-%dT%H:%M:%S.%fZ'](https://github.com/localstack/localstack/blob/master/localstack/utils/common.py#L55v), but according to the [AWS CLI docs](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/kinesis/register-stream-consumer.html) (also [this](https://github.com/aws/aws-cli/blob/master/awscli/examples/kinesis/register-stream-consumer.rst))it should be a UNIX timestamp.

This breaks using register_stream_consumer with `software.amazon.awssdk.services.kinesis.KinesisAsyncClient` since it can't unmarshall the date in the response:
`software.amazon.awssdk.core.exception.SdkClientException: Unable to parse date : 2020-08-11T05:10:06.349Z`

...

## Expected behavior
ConsumerCreationTimestamp should be a float UNIX timestamp
...

## Actual behavior
ConsumerCreationTimestamp is a string formatted timestamp
...

# Steps to reproduce
Run any register_stream_consumer command

## Command used to start LocalStack
Java testcontainers/localstack 

...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
...

**Comment by elainearbaugh** [comment]
Have a PR, having some issues with local testing so will update tomorrow  https://github.com/localstack/localstack/pull/2835

**Comment by elainearbaugh** [comment]
PR is ready now

**Comment by whummer** [comment]
Thanks again for adding the PR 👍
