### ISSUE TITLE
PRO: Issue with using Lambda Layers

### ISSUE THREAD

**Issue by aaron-parsons** [localstack/localstack#2838]
# Type of request: This is a ...

[x ] bug report (?)
[ ] feature request

# Detailed description
Hi, 
We've been enjoying working with localstack and have upgraded to the pro edition to use lambda layers. I am having some issues getting lambda layers to work however. I can publish a python layer, as shown below, but if I try to use it when I create a function, it fails.

Any advice would be greatly appreciated.
...

## Expected behavior
I'm expecting create_lambda_response to create a server side function, that when I trigger it using an SNS message will print the event to the logs.
...

## Actual behavior

At the create_lambda_response call I get: 
```
botocore.exceptions.ClientError: An error occurred (InternalFailure) when calling the CreateFunction operation (reached max retries: 4): Unknown error: Command 'cd /tmp/tmp3vujx6ni; unzip -o /tmp/localstack/zipfile.d043824b/original_lambda_archive.zip' returned non-zero exit status 9. Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 957, in create_function
    result = set_function_code(func_details.code, lambda_name)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/awslambda/lambda_extended.py", line 86, in set_function_code
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/awslambda/lambda_extended.py", line 71, in copy_function_code
  File "/opt/code/localstack/localstack/utils/common.py", line 885, in unzip
    return run('cd %s; unzip %s %s' % (target_dir, flags, path))
  File "/opt/code/localstack/localstack/utils/common.py", line 1090, in run
    return do_run(cmd)
  File "/opt/code/localstack/localstack/utils/common.py", line 1087, in do_run
    return bootstrap.run(cmd, **kwargs)
  File "/opt/code/localstack/localstack/utils/bootstrap.py", line 582, in run
    raise e
  File "/opt/code/localstack/localstack/utils/bootstrap.py", line 542, in run
    output = subprocess.check_output(cmd, shell=True, stderr=stderr, env=env_dict, cwd=cwd)
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'cd /tmp/tmp3vujx6ni; unzip -o /tmp/localstack/zipfile.d043824b/original_lambda_archive.zip' returned non-zero exit status 9.
...
```

# Steps to reproduce

## Command used to start LocalStack
LOCALSTACK_API_KEY=xxxxx localstack start
...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

I run the following, where path_to_layer_zip is a zip file created following these instructions: https://docs.aws.amazon.com/lambda/latest/dg/configuration-layers.html

and lambda_handler_py is a .py file that just prints a json dump of the event. It is separately tested so I know it works.
If I comment out the Layers=[layer_arn] part, this script runs to completion.

```
from localstack.utils.aws import aws_stack
from localstack.utils.common import short_uid
from localstack.utils import testutil
import os

os.environ['AWS_SECRET_ACCESS_KEY'] = 'foo'
os.environ['AWS_ACCESS_KEY_ID'] = 'bar'
os.environ['AWS_DEFAULT_REGION'] = 'us-east-1'

lambda_client = aws_stack.connect_to_service('lambda')

resp = lambda_client.publish_layer_version(LayerName='test_layer', Description='Layer for test',  Content={'ZipFile':path_to_layer_zip})
layer_arn = resp["LayerVersionArn"]
valid_message_body = {"foo": "bar"}
func_uid = 'echo-test-%s' % short_uid()
create_lambda_response = testutil.create_lambda_function(handler_file=lambda_handler_py, func_name=func_uid, Layers=[layer_arn])
```
...

**Comment by aaron-parsons** [comment]
Hi @whummer @duongpv7 ,

Thanks for tagging this as high priority and looking into this.

This is issue is now blocking for me so I just wanted to get your opinion on whether you can tell if this is a valid bug from my description, or if I am doing something wrong.

If it is a bug then that’s fine, but I just didn’t want to wait if it was something that I am doing wrong. I am new to both AWS and localstack so just want to make sure. I am pretty sure from the doc that it is a bug though.

Please let me know if you need more information.

Thanks!
Aaron

**Comment by whummer** [comment]
Hi @aaron-parsons , just a quick follow-up - have you been able to get your Lambda with layers deployed, using the hint above..? Thanks

**Comment by aaron-parsons** [comment]
HI @whummer,

Sorry for the delay: I was on holiday.

Yes this works thanks. 

Not sure why I missed it.

Aaron
