### ISSUE TITLE
Docker lambda network/integration questions

### ISSUE THREAD

**Issue by bernljung** [localstack/localstack#284]
Hello,

I'm trying to figure out how to run localstack with docker-compose and invoking a lambda function that calls back to the localstack container. An example could be a lambda function that accesses S3 in localstack.

The docker-compose included in the repo is not specifying a network, which means that docker will use the docker-compose default, in this case localstack_default. 
Then lambda container is started in the bridge network and, unless I'm mistaken, we're not going to be able to communicate between the containers by alias/hostname. Something like this won't work, for instance: 

`
const s3 = new AWS.S3({
  apiVersion: '2007-03-01',
  endpoint: 'http://localstack:4572'
})
`
 
Therefore I'm not sure how to make requests towards the localstack container. 

Maybe the docker run command in lambda_api.py could also include whatever network localstack is using at the moment and access via alias will come for free? 

If I'm missing a step somewhere, which is not at all unlikely, please enlighten me :)

**Comment by whummer** [comment]
@bernljung the configuration has been updated in PR #286 . You should now be able to use the environment variable `$LOCALSTACK_HOSTNAME` in your Lambda function. In local execution, it points to `localhost` (unless overwritten by `HOSTNAME`), and when executing Lambdas in Docker , it points to the IP address of the Docker bridge interface, which should then allow your code to make cross-container invocations. It has been tested in our CI, please give it a try if it works for your setup as well. (Otherwise, you may be able to overwrite `LOCALSTACK_HOSTNAME` to use a specific custom endpoint.)

**Comment by bernljung** [comment]
@whummer Nice! This worked like a charm for me as well. :) 

Now my only current concern is the default docker-compose.yml as described in [255](https://github.com/localstack/localstack/issues/255). I am not able to get my uploaded zipfile.xxxxxx from the /tmp/localstack to be included when localstack runs the lambdaci container. 

I get "Unable to import module 'index': Error" every time. 

I have "solved" this in my setup by creating /tmp/localstack locally and using
`- "/tmp/localstack}:/tmp/localstack"`

instead of 
`- "${TMPDIR:-/tmp/localstack}:/tmp/localstack"`

This works for me but I guess it would be nice to have a solution that doesn't require any extra work outside of the actual docker-compose itself.

**Comment by njcongtou** [comment]
How you guys use $LOCALSTACK_HOSTNAME ?

I got this error message.

"errorMessage":"LOCALSTACK_HOSTNAME is not defined",

**Comment by njcongtou** [comment]
I triggered it using INVOKE and got this error. 

localstack_1     | START RequestId: 411ca9a6-bc84-19ce-301e-d2113583c399 Version: $LATEST
localstack_1     | module initialization error: ReferenceError
localstack_1     |     at Object.<anonymous> (/var/task/resources/eventLogger/logger.js:6:62)
localstack_1     |     at Module._compile (module.js:570:32)
localstack_1     |     at Object.Module._extensions..js (module.js:579:10)
localstack_1     |     at Module.load (module.js:487:32)
localstack_1     |     at tryModuleLoad (module.js:446:12)
localstack_1     |     at Function.Module._load (module.js:438:3)
localstack_1     |     at Module.require (module.js:497:17)
localstack_1     |     at require (internal/module.js:20:19)
localstack_1     |     at Object.<anonymous> (/var/task/resources/pipeline.js:3:22)
localstack_1     |     at Module._compile (module.js:570:32)

**Comment by njcongtou** [comment]
My docker compose file looks like this:

    environment:
      - DEFAULT_REGION=us-west-2
      - SERVICES=${SERVICES-lambda, kinesis, s3}
      - DEBUG=1
      - DATA_DIR=${DATA_DIR- }
      - LAMBDA_EXECUTOR=docker
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LOCALSTACK_HOSTNAME=${LOCALSTACK_HOSTNAME-localhost}

**Comment by njcongtou** [comment]
My issue: https://github.com/localstack/localstack/issues/338
