### ISSUE TITLE
Stale lambci docker images

### ISSUE THREAD

**Issue by adamdavis40208** [localstack/localstack#2841]
# Type of request: This is a ...
[x] bug report
[ ] feature request

# Detailed description
We had a docker-compose stack failing in circleCI but passing locally. What finally fixed it for us: pruning our local images.

It seems that localstack always does a docker run (or remote call), but never a pull to make sure the latest image is being used.

## Expected behavior
Two machines running the same docker-compose yaml should have the same results

## Actual behavior
Due to some machines having an older image, they were passing, newer machines weren't. 

# Steps to reproduce
## Command used to start LocalStack
docker-compose up, using localstack:latest

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-235) by [Unito](https://www.unito.io/learn-more)

**Comment by whummer** [comment]
Thanks for reporting @adamdavis40208 - good catch! Do you think you would be able to add a small pull request to add the functionality that's required here? That would be much appreciated - thanks!

**Comment by adamdavis40208** [comment]
yup, can do!

**Comment by whummer** [comment]
Hi @adamdavis40208 , after revisiting this issue, this is actually standard behavior of docker-compose. To my knowledge, docker-compose currently does not have a config option to always pull the latest image from Docker hub (it simply uses the image cached locally).

This can be added easily added to your startup script (doing a `docker pull` manually).

For now, we prefer to keep this behavior, as automatically pulling the image every time seems fairly intrusive to the user's environment. We'll update the README to reflect this accordingly. Please let us know or feel free to create a PR if you think anything particular is missing in the current docs/setup. Thanks!
