### ISSUE TITLE
Unable to get signing certificate for Cognito

### ISSUE THREAD

**Issue by limenutt** [localstack/localstack#2864]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description
There is a 500 error when executing `aws cognito-idp get-signing-certificate` for a user pool

## Expected behavior
Certificate information is returned

## Actual behavior
500 error
```
An error occurred (500) when calling the GetSigningCertificate operation (reached max retries: 4): <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
```

# Steps to reproduce

## Command used to start LocalStack

docker-compose up

docker-compose.yml

```
version: '2.1'
services:
  localstack:
    image: localstack/localstack
    ports:
      - "53:53"
      - "443:443"
      - "4510-4520:4510-4520"
      - "4566-4620:4566-4620"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - LOCALSTACK_API_KEY=***
      - SERVICES=serverless,cognito-idp,iam,lambda
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

```
pool_id=$(awslocal cognito-idp create-user-pool --pool-name test | jq -rc ".UserPool.Id")
awslocal cognito-idp get-signing-certificate --user-pool-id "$pool_id"
```

**Comment by whummer** [comment]
Thanks for reporting this issue @limenutt . This should be fixed in the `latest` version - can you please do a `docker pull localstack/localstack` and give it another try? Please let us know if the issue persists (and feel free to reach out directly in our Slack channel). Thanks for your help!
