### ISSUE TITLE
How to check if event is triggered between s3 and SNS after uploading a file in S3 bucket.

### ISSUE THREAD

**Issue by ambreenshameem** [localstack/localstack#2871]
Not a bug. Unable to find the answer anywhere hence had to open a ticket. 

I am trying to generate an event from s3 bucket to SNS topic after uploading a file in S3 bucket. I am able to perform all the steps but not sure how to check SNS topic if it has received the event successfully.
Also the SNS topic will only receive an event or the file (which was uploaded in s3) as well and can i print the content of the file once it is received by SNS?
...
Expected:
to be able to validate - SNS has received the event.

Actual: Not sure how to  validate SNS topic
...

# Steps to reproduce

docker-compose up -d
•	Create Bucket-> 
aws --endpoint-url=http://localhost:4566 s3 mb s3://test-bucket-sns
•	Create Topic->
aws sns create-topic --name putnotifications --endpoint-url=http://localhost:4575
•	Subscribe to the topic->
aws --endpoint-url=http://localhost:4575 sns subscribe --topic-arn arn:aws:sns:us-east-1:000000000000:putnotifications --protocol email --notification-endpoint abc@yahoo.com

•	Put-bucket-notification-configuration->
aws s3api put-bucket-notification-configuration --bucket test-bucket-sns --notification-configuration file://snsTopicConfiguration.json --endpoint-url=http://localhost:4566
•	Upload a file in created s3 bucket->
aws s3 cp color.json s3://test-bucket-sns --endpoint-url=http://localhost:4566

Notification configuration file:

{
    "TopicConfigurations": [
        {
            "TopicArn": "arn:aws:sns:us-east-1:000000000000:putnotifications",
            "Events": [
                "s3:ObjectCreated:*"
            ]
        }
    ]
}

**Comment by ambreenshameem** [comment]
@duongpv7   -- A response is greatly appreciated.

**Comment by whummer** [comment]
Thanks for reporting @ambreenshameem . Please note that SNS topics usually need to be connected to a downstream resource which receives the notification messages for further processing. Typically, an SQS queue is used for this purpose.

A small integration test has been added in #2891 for reference - please refer to the details there (also please note how the S3 bucket/object details are contained in the event in the test). Hope that helps - please let us know if there are any other issues. Thanks
