### ISSUE TITLE
SQS Queues created with /000000000000/ instead of /queue/ prefix

### ISSUE THREAD

**Issue by collinsauve** [localstack/localstack#2877]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

Please lmk if this should be filed against [awscli-local](https://github.com/localstack/awscli-local) instead.

In `localstack-light` tag `0.11.1`, creating queues in  with `awslocal` would create urls like this:

```
http://localhost:4576/queue/myname
```

With tag `0.11.4`, the same command produces urls like this:

```
http://localhost:4576/000000000000/myname
```

Is this change intentional?  Should this be considered a breaking change?  It does break some of our tooling that expects the url to follow a certain pattern.  We can update our tooling, but need to make sure this is intentional and will be stable behaviour.

## Expected behavior

No breaking changes across revision version changes.

## Actual behavior

Breaking change across revision version changes.

# Steps to reproduce

```
$ docker run -d --name ls1 localstack/localstack-light:0.11.1 
56a6ceeb5123a12c7c3f8c5444de5d6fa3dea93a05bef726d1922aecaad18803

$ docker exec ls1 awslocal sqs create-queue --queue-name myqueue
{
    "QueueUrl": "http://localhost:4576/queue/myqueue"
}
```

```
$ docker run -d --name ls2 localstack/localstack-light:0.11.4
e1892963463c85194026bd3a97e27d8aad769b52f593ad4f1b0dc7435f831694

$ docker exec ls2 awslocal sqs create-queue --queue-name myqueue
{
    "QueueUrl": "http://localhost:4576/000000000000/myqueue"
}
```

**Comment by whummer** [comment]
Thanks for reporting @collinsauve . This is indeed a breaking change, but one that was introduced to more closely mirror the behavior in real AWS - see issue #2518 and PR #2591 .

> Is this change intentional? Should this be considered a breaking change? It does break some of our tooling that expects the url to follow a certain pattern. We can update our tooling, but need to make sure this is intentional and will be stable behaviour.

This change is intentional and you can expect this to be the stable behavior, moving forward. Such breaking changes shouldn't happen very frequently, but in the future we'll make sure to flag them as breaking changes in the change log / release notes. Thanks

**Comment by collinsauve** [comment]
Great, thank you @whummer !
