### ISSUE TITLE
SQS name of missing queue is not reported

### ISSUE THREAD

**Issue by yaitskov** [localstack/localstack#2878]
On attempt to send message to non existing queue the SQS service returns 404 but doesn't explain what queue is missing. docker logs doesn't explain either. This is time consuming figuring out what queue actually is required if there are many queues in a test. 
Wireshark helps but it should be reported by service.

**Comment by whummer** [comment]
Thanks for reporting @yaitskov . This should be fixed upstream in spulec/moto#3261 and is now available in LocalStack. Can you please give it another try with the `latest` version? Please report here if the problem persists. Thanks
