### ISSUE TITLE
IAM PutRolePermissionsBoundary returns Internal Server Error

### ISSUE THREAD

**Issue by GreenyMcDuff** [localstack/localstack#2888]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

When calling the PutRolePermissionsBoundary API resource via the AWS CLI an Internal Server Error is returned

## Expected behavior

The command should complete without throwing an error.  It should not generate any output as per the AWS CLI documentation for [put-role-permissions-boundary](https://docs.aws.amazon.com/cli/latest/reference/iam/put-role-permissions-boundary.html)

## Actual behavior

The following error message is returned when issuing the put-role-permissions-boundary command

> Unable to parse response (syntax error: line 1, column 54), invalid XML received. Further retries may succeed:
b'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">\n<title>500 Internal Server Error</title>\n<h1>Internal Server Error</h1>\n<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>\n'

# Steps to reproduce

## Command used to start LocalStack

`docker run -d -p 4566:4566 localstack/localstack:0.11.4`

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

```
aws --endpoint-url=http://localhost:4566 iam create-role --role-name RoleWithPermissionsBoundary --assume-role-policy-document file://TrustPolicy1.json
aws --endpoint-url=http://localhost:4566 iam create-policy --policy-name CustomerManagedPolicy1 --policy-document file://CustomerManagedPolicy1.json
aws --endpoint-url=http://localhost:4566 iam put-role-permissions-boundary --role-name RoleWithPermissionsBoundary --permissions-boundary arn:aws:iam::000000000000:policy/CustomerManagedPolicy1
```

Where

TrustPolicy1.json

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "sts:AssumeRole",
            "Prinipal": {
                "AWS": "arn:aws:iam::000000000000:root"
            },
            "Resource": "*"
        }
    ]
}
```

CustomerManagedPolicy1.json

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "s3:*",
            "Resource": "*"
        }
    ]
}
```

**Comment by macnev2013** [comment]
Hey @GreenyMcDuff , Thanks for reporting.
This feature was added in PR [#3392](https://github.com/spulec/moto/pull/3329).
Please pull the `latest` image of the docker using `docker pull localstack/localstack:latest` and try give it a try.
Thanks.
