### ISSUE TITLE
How to create a s3 inventory in localstack ?

### ISSUE THREAD

**Issue by rahul-s20** [localstack/localstack#2889]
# Type of request: This is a ...
[ ] bug report
[ ] feature request

# Detailed description
...

## Expected behavior
...

## Actual behavior
...

# Steps to reproduce
## Command used to start LocalStack
...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
...

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-240) by [Unito](https://www.unito.io/learn-more)

**Comment by whummer** [comment]
Thanks for reporting @rahul-s20 . Creating bucket inventory configurations should be available in the `latest` Docker image:

```
$ awslocal s3 mb s3://bucket1
make_bucket: bucket1
$ awslocal s3api list-bucket-inventory-configurations --bucket bucket1
{
    "IsTruncated": false
}
```

In case you're looking for bucket inventories using the Glacier API, we provide support for that in the Pro version of LocalStack. Please keep us posted how it goes.. Thanks!
