### ISSUE TITLE
pre_token_generation Lambda doesn't receive any request data

### ISSUE THREAD

**Issue by soulshake** [localstack/localstack#2893]
Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

Lambdas triggered by Cognito authentication events don't receive valid input.

Reproduction repo: [here](https://github.com/soulshake/localstack-issue-2858/tree/28b610f7ebc770679ee388740036645e5b18d0ed)

## Expected behavior

A normal `event` from AWS Cognito as passed to a pre-token-generation Lambda trigger looks like:

```
{
    "version": "1",
    "triggerSource": "TokenGeneration_Authentication",
    "region": "us-east-2",
    "userPoolId": "us-east-2_Afk83o2fJFetc",
    "userName": "62104cf6-3619-4999-a55a-1ea67b7faetc",
    "callerContext": {
        "awsSdkVersion": "aws-sdk-unknown-unknown",
        "clientId": "8fn23kflv921jfnlksf2etc"
    },
    "request": {
        "userAttributes": {
            "sub": "62104cf6-3619-4999-a55a-1ea67b7faetc",
            "email_verified": "true",
            "cognito:user_status": "CONFIRMED",
            "phone_number_verified": "true",
            "phone_number": "+15555555555",
            "email": "fake@example.com"
        },
        "groupConfiguration": {
            "groupsToOverride": [],
            "iamRolesToOverride": [],
            "preferredRole": null
        }
    },
    "response": {
        "claimsOverrideDetails": null
    }
}
```

## Actual behavior

The LocalStack `event` looks like this instead:

```
{
  "version": "$LATEST",
  "triggerSource": "TokenGeneration_Authentication",
  "region": "us-east-2",
  "userPoolId": "us-east-2_5d3bb376099e4e1790f72225bab0593b",
  "callerContext": {
    "awsSdkVersion": "TODO",
    "clientId": "yepgmtk1s7l4pz2m6bm25osfvf"
  },
  "request": {
    "userAttributes": {},
    "validationData": {},
    "clientMetadata": {}
  },
  "response": {},
  "userAttributes": {}
}
```

# Steps to reproduce

Reproduction repo with instructions: [here](https://github.com/soulshake/localstack-issue-2858)

**Comment by whummer** [comment]
Thanks for reporting @soulshake - this should be fixed in the `latest` version. Can you please pull the Docker image and give it another try? Please let us know if the problem persists, or if any other attributes are still missing in the request. Thanks for your help!
