### ISSUE TITLE
bad interpreter: No such file or directory

### ISSUE THREAD

**Issue by pdashford** [localstack/localstack#2914]
# Type of request: This is a ...
[X] bug report
[ ] feature request

# Detailed description
After installing localstack on Mac I get the following when running `localstack --help`

Library/Python/3.7/bin/localstack: /usr/local/opt/python/bin/python3.7: bad interpreter: No such file or directory

which python
/usr/local/opt/python/libexec/bin/python

## Expected behavior
...

## Actual behavior
...

# Steps to reproduce
## Command used to start LocalStack
...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
...

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-244) by [Unito](https://www.unito.io/learn-more)

**Comment by whummer** [comment]
Thanks for reporting @pdashford . This appears to be an issue in your Python/pip environment - doesn't seem to be related to LocalStack. Thanks
