### ISSUE TITLE
Very slow connection between localstack's lambda and other services that run on docker images

### ISSUE THREAD

**Issue by ilaneden** [localstack/localstack#2918]
# Type of request: This is a ...
 bug report

# Detailed description
I'm using the latest version of localstack; I run a lambda that calls services that run on docker containers on my machine. The connection is really slow and I'm getting a lot of timeout errors. This is a new issue (happens only on the latest version), before that I was able to connect to the docker services without any problems 

## Expected behavior
Slow connection between localstack and docker containers
...

## Actual behavior
Fast connection between localstack and docker containers

...

# Steps to reproduce
## Command used to start LocalStack
...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
...

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-245) by [Unito](https://www.unito.io/learn-more)

**Comment by whummer** [comment]
Thanks for reporting @ilaneden . We have pushed a couple of performance improvements in the meantime - can you please pull the `latest` Docker image and give it another try? In case the problem still persists, please re-open this issue (or create a new one) with details about your environment and steps to reproduce. Thanks
