### ISSUE TITLE
Localstack securing

### ISSUE THREAD

**Issue by YuriiPaneiko** [localstack/localstack#2921]
Hello, is it possible to secure localstack? Because now anyone who has any aws access key id and secret key can access to localstack services.

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-246) by [Unito](https://www.unito.io/learn-more)

**Comment by thrau** [comment]
with localstack pro, when you enable `ENFORCE_IAM=1`, IAM rules are strictly enforced when running requests. i hope this answers your question! otherwise, please open a new issue with more details on what exactly it is you want to provide access control for.
