### ISSUE TITLE
[feature] lambda destination support ?

### ISSUE THREAD

**Issue by dfang** [localstack/localstack#2926]
# Type of request: This is a ...

[x] feature request

# Detailed description

add lambda function destination support ？

with serverless-localstack plugin, function with destinations would not deploy to localstack.

## Actual behavior

```
$ awslocal lambda update-function-event-invoke-config --function-name local-hello --cli-input-json file://input.json

An error occurred (405) when calling the UpdateFunctionEventInvokeConfig operation: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>405 Method Not Allowed</title>
<h1>Method Not Allowed</h1>
<p>The method is not allowed for the requested URL.</p>
```

# Steps to reproduce

https://www.serverless.com/blog/lambda-destinations
## Command used to start LocalStack

with serverless-localstack plugin
set autoStart: true

...

**Comment by whummer** [comment]
Thanks for reporting @dfang . This should be fixed in #2977 - can you please do a `docker pull localstack/localstack` and give it another try with the `latest` version of the Docker image? Please report here if the problem persists. Thanks

**Comment by dfang** [comment]
@whummer

`sls deploy -s local` didn't configure lambda destinations for me, so i try this

```
{
  "OnSuccess": {
    "Destination": "arn:aws:sns:us-east-1:000000000000:local-5da32ac332"
  },
  "OnFailure": {
    "Destination": "arn:aws:sns:us-east-1:000000000000:local-5da32ac332"
  }
}

$ awslocal lambda update-function-event-invoke-config --function-name local-hello --cli-input-json file://input.json
Parameter validation failed:
Unknown parameter in input: "OnSuccess", must be one of: FunctionName, Qualifier, MaximumRetryAttempts, MaximumEventAgeInSeconds, DestinationConfig
Unknown parameter in input: "OnFailure", must be one of: FunctionName, Qualifier, MaximumRetryAttempts, MaximumEventAgeInSeconds, DestinationConfig

```

if i remove double quote around arn:aws:sns:us-east-1:000000000000:local-5da32ac332, i will get invalid json error.

**Comment by whummer** [comment]
Thanks for the update @dfang . Can you please also provide the server-side logs (from the LocalStack Docker container) with the `DEBUG=1` environment enabled? Thanks

**Comment by whummer** [comment]
Quick update @dfang , can you please take a look at this repo and confirm whether you can reproduce the sample from there? https://github.com/macnev2013/lamdba-destinations-demo.git Thanks!

**Comment by whummer** [comment]
@dfang Closing this issue as "should be fixed" - please reopen if the problem persists. Thanks

**Comment by barnettj** [comment]
Hi everyone. I'm trying to implement lambda destinations for my localstack (LocalStack version: 0.12.3) lambda to SQS too.

After applying an update-function-event-invoke-config, it doesn't throw any errors, but can no longer call list-functions and does not route lambda response to destination.

`bash-5.0# awslocal lambda update-function-event-invoke-config --function-name function-local --cli-input-json file://destination.json
{
    "LastModified": "2020-12-17T03:49:48.479+0000",
    "FunctionArn": "arn:aws:lambda:us-east-1:000000000000:function:core.services.function-local",
    "DestinationConfig": {
        "OnSuccess": {
            "Destination": "arn:aws:sqs:us-east-1:000000000000:local-events"
        },
        "OnFailure": {
            "Destination": "arn:aws:sqs:us-east-1:000000000000:local-events"
        }
    }
}
bash-5.0# awslocal lambda list-functions

'str' object has no attribute 'get'`
