### ISSUE TITLE
Some more direction on how to create a Lambda function

### ISSUE THREAD

**Issue by togakangaroo** [localstack/localstack#2929]
# Type of request: This is a ...

[ ] bug report
[x ] feature request

But specifically for the documentation

# Detailed description

So disclaimer in that all of AWS is new to me but I can't be the only person in this boat.

I'm having trouble figuring out from the documentation and other writing available online how I am supposed to create a lambda function.

I have a very simple lambda

```js
     exports.handler = async (event) => {
       console.log(`Localstack lambda`, JSON.stringify(event))
       return {
         statusCode: 200,
         body: JSON.stringify(`yo yo, from localstack lambda`)
       }
     }
```

which I zip

```shell
     zip logging-lambda.zip logging-lambda.js
```

and then try to deploy

```shell
     aws lambda create-function \
         --endpoint http://localhost:4566 \
         --function-name loggingLambda \
         --runtime nodejs12.x \
         --role arn:aws:iam::000000000000:role/lambda-ex \
         --zip-file fileb://logging-lambda.zip \
         --handler index.handler
```

only to get the error

> An error occurred (ValidationError) when calling the CreateFunction operation: Unable to find handler script (/tmp/localstack/zipfile.38f20074/index.js) in Lambda archive. Config for local mount, docker, remote: "False", "False", "False"

My docker container has the following environment variables set

```
      - SERVICES=s3,sqs,sns,lambda
      - LAMBDA_EXECUTOR=local
      - LAMBDA_REMOTE_DOCKER=false
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
```

As best as I can read the docs I'm doing everything right, but clearly that's not the case and everything I can find online is all about using IDEs to upload (I'm in the command line)

Can we get some more info on what the recommended process for getting a lambda into localstack is top to bottom?

**Comment by whummer** [comment]
Thanks for reporting @togakangaroo . You're using the following handler definition:
```
--handler index.handler
```
... and this Lambda runtime:
```
         --runtime nodejs12.x \
```
As per the AWS Lambda documentation, this means that the handler file in your ZIP file should be named `handler.js` (instead of `logging-lambda.js`).

Hope that helps - please provide an update or more details if the problem persists. Thanks!

**Comment by togakangaroo** [comment]
Ok, thanks, that managed to get me to a useful place.

I renamed the file to `handler.js` and the zip to `handler.zip`

Then it had to be ```--handler handler.handler```

but I got back the expected response
