### ISSUE TITLE
status code 404 describing loadbalancers aws sdk

### ISSUE THREAD

**Issue by dev-trendrating** [localstack/localstack#2934]
# Type of request: This is a ...
[ x] bug report
[ ] feature request

# Detailed description
Triyng to call describe load balancers to get the list of loadbalancers using AWS SDK java
I'm using the version2 of SDK

## Expected behavior
Return the list of loadbalancers or an empty list if no loadbalancers are present

## Actual behavior
Returns a 404 http status code  and in localstack log appears the following line
2020-09-04T07:52:03:INFO:localstack.services.edge: Unable to determine forwarding port for API "elasticloadbalancing" - please make sure this API is enabled via the SERVICES configuration

Using aws-cli works properly
aws elbv2 describe-load-balancers --endpoint-url http://localhost:4566

running the following command doesn't change anything
curl -v -d '{"variable":"SERVICES","value":"ec2,elbv2,elb"}' 'http://localhost:4568/?_config_'

using the same java code against AWS works fine

# Steps to reproduce
Start localstack and run a simple java snippet to describe loadbalancers 

## Command used to start LocalStack
localstack start

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
AwsBasicCredentials awsc = AwsBasicCredentials.create(AWSClientImpl.AWS_ACCESS_KEY,
		AWSClientImpl.AWS_SECRET_KEY);
	ElasticLoadBalancingV2ClientBuilder elbb = ElasticLoadBalancingV2Client.builder();
	elbb.region(Region.US_EAST_1).credentialsProvider(StaticCredentialsProvider.create(awsc));
	elbb.endpointOverride(URI.create("http://localhost:4566"));
	ElasticLoadBalancingV2Client elbc = elbb.build();
	DescribeLoadBalancersResponse dlbr = elbc.describeLoadBalancers();

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-249) by [Unito](https://www.unito.io/learn-more)

**Comment by whummer** [comment]
Thanks @dev-trendrating and apologies for the very long delay on this one. We have made several refactorings and enhancements in the meantime - the `SERVICES` configuration is no longer required, as all services are now enabled by default and lazily loaded upon the first request. 👍 

Please note that ELB v2 is part of our Pro offering, and not available in the Community version of LocalStack - there's a free trial for Pro if you'd like to give it a try. Closing this issue as resolved - please let us know if there are any other issues. Thanks!
