### ISSUE TITLE
The TMPDIR symlink issue on Mac

### ISSUE THREAD

**Issue by msageryd** [localstack/localstack#2935]
[ ] bug report
[ ] feature request
[x] best practice question

# Detailed description
I'm trying out localstack right now (just had it spun up for the first time). My dev stack is handled via Docker Compose on OSX. 

I can either set the TMPDIR variable each time I start my stack as per your docs: 
`TMPDIR=/private$TMPDIR docker-compose up`

OR I could simply rewrite TMPDIR in my .bash-profile.

`export TMPDIR=/private$TMPDIR`

The latter is easier to me, but I wonder if I'm shooting myself in the foot by doing this. Will I break other stuff in OSX by directing TMPDIR directly to /private/var.. (where the /var symlink points), like this:

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-250) by [Unito](https://www.unito.io/learn-more)

**Comment by whummer** [comment]
Thanks @msageryd . Appending the `/private` prefix for the tmpdir path is the recommended way - seems to be working well for most Docker versions. Please let us know if there are any specific problems with that.. Thanks!
