### ISSUE TITLE
DynamoDB streams requires Kinesis to be up and running (undocumented)

### ISSUE THREAD

**Issue by jontg** [localstack/localstack#294]
When running locally, I've noticed that if I try to create a dynamodb table _with_ streams enabled, I get a network timeout, but if the stream is disabled I get a table created right away.  Interestingly, the table appears to be created — the NodeJS client is just never informed of it.

Steps to Reproduce
==================

Start up the container:
```bash
docker run -it \
  -e SERVICES="dynamodb,dynamodbstreams" \
  -p 4569:4569 \
  -p 4570:4570 \
  -p 8080:8080 \
  -e DATA_DIR="/tmp/localstack/data" \
  -v ${HOME}/data/localstack:/tmp/localstack \
  localstack/localstack
```

Browse to [the web shell](http://localhost:4569/shell/) for DynamoDB.

Try to create a DynamoDB table with streams _disabled_:
```javascript
var params = {
  TableName: 'test-without-executions',
  KeySchema: [ { AttributeName: 'id', KeyType: 'HASH' } ],
  AttributeDefinitions: [ { AttributeName: 'id', AttributeType: 'S' } ],
  ProvisionedThroughput: { ReadCapacityUnits: 10, WriteCapacityUnits: 10 },
  StreamSpecification: { StreamEnabled: false }
};
dynamodb.createTable(params, function(err, data) {
    if (err) ppJson(err); // an error occurred
    else ppJson(data); // successful response
});
```
and celebrate, for the table is created!  No logs from docker.

Next, try to create a _very similar_ table with streams _enabled_:
```javascript
var params = {
  TableName: 'test-with-executions',
  KeySchema: [ { AttributeName: 'id', KeyType: 'HASH' } ],
  AttributeDefinitions: [ { AttributeName: 'id', AttributeType: 'S' } ],
  ProvisionedThroughput: { ReadCapacityUnits: 10, WriteCapacityUnits: 10 },
  StreamSpecification: { StreamEnabled: true, StreamViewType: 'NEW_IMAGE' }
};
dynamodb.createTable(params, function(err, data) {
    if (err) ppJson(err); // an error occurred
    else ppJson(data); // successful response
});
```
and weep - the network console hangs and eventually delivers the following error:
<img width="402" alt="screen shot 2017-09-03 at 8 06 00 pm" src="https://user-images.githubusercontent.com/309263/30010340-de1d7c66-90e3-11e7-9b14-1607b1a7ea97.png">
Again, no logs from the docker side of things.

The table appears to have been created successfully :confused:?
<img width="556" alt="screen shot 2017-09-03 at 8 09 32 pm" src="https://user-images.githubusercontent.com/309263/30010346-e4a57232-90e3-11e7-9b82-81366fd29c0d.png">

**Comment by jontg** [comment]
Ah... you know what?  It looks like you also need `kinesis` enabled, in order for this flow to complete — otherwise it hangs trying to create the `kinesis` resource.

**Comment by whummer** [comment]
Good catch @jontg! I'm re-opening this issue because we should make that work out of the box (users should not have to care about starting `kinesis` when using DDB streams).

**Comment by jontg** [comment]
Ok, cool thanks @whummer !
