### ISSUE TITLE
Unsupported Choice Rule comparison operators in Step Functions 

### ISSUE THREAD

**Issue by onezeroecho** [localstack/localstack#2941]
# Type of request:

[x] bug report
[ ] feature request

# Detailed description

Not all Step Functions comparison operators in a [Choice Rule](https://docs.aws.amazon.com/step-functions/latest/dg/amazon-states-language-choice-state.html#amazon-states-language-choice-state-rules) are supported in LocalStack. In my use case, the `IsPresent` operator is not supported.

My example state machine definition:
```json
{
  "StartAt": "CheckValues",
  "States": {
    "CheckValues": {
      "Type": "Choice",
      "Choices": [
        {
          "And": [
            {
              "Variable": "$.x",
              "IsPresent": true
            },
            {
              "Variable": "$.y",
              "IsPresent": true
            }
          ],
          "Next": "Add"
        }
      ],
      "Default": "MissingValue"
    },
    "MissingValue": {
      "Type": "Fail",
      "Cause": "One or more missing values."
    },
    "Add": {
      "Type": "Task",
      "Resource": "arn:aws:lambda:us-east-1:000000000000:function:add",
      "ResultPath": "$.added",
      "TimeoutSeconds": 10,
      "End": true
    }
  }
}
```

## Expected behavior

The state machine should be created and return the `stateMachineArn` and `creationDate` in the response. I'm able to use the above state machine definition on AWS with no issues.

## Actual behavior

I get a `SCHEMA_VALIDATION_FAILED` error:

```json
An error occurred (InvalidDefinition) when calling the CreateStateMachine operation: Invalid State Machine Definition:
 ''SCHEMA_VALIDATION_FAILED: Field 'IsPresent' is not supported at /States/CheckValues/Choices[0]/And[0]',
'SCHEMA_VALIDATION_FAILED: This object should have only one of the following fields: [StringEquals, StringLessThanEquals,
NumericLessThanEquals, StringLessThan, StringGreaterThan, BooleanEquals, NumericLessThan, NumericGreaterThan,
NumericEquals, TimestampLessThan, TimestampGreaterThan, TimestampLessThanEquals, StringGreaterThanEquals,
NumericGreaterThanEquals, TimestampEquals, TimestampGreaterThanEquals] at /States/CheckValues/Choices[0]/And[0]'`
```

# Steps to reproduce

Versions:
```bash
$ awslocal --version
aws-cli/1.18.133 Python/3.6.9 Linux/4.15.0-112-generic botocore/1.17.56
```

Create state machine:
```bash
$ awslocal --debug stepfunctions create-state-machine\
        --name add \
        --definition "$(cat ./tmp/definition.json)" --role-arn arn:aws:iam::000000000000:role/stepfunctions-iam-role
```

**Comment by needanamehelp** [comment]
Can you please try the same with the latest docker image, as I can see I am facing no error while creating this State Machine, Thank you.

**Comment by whummer** [comment]
Thanks for reporting @onezeroecho . This appears to be fixed in the meantime - a small integration test has been added in #3122 . Can you please pull the `latest` Docker image and give it another try? Please report here if the problem persists. Thanks

**Comment by onezeroecho** [comment]
@needanamehelp @whummer I no longer got this error when I used version 0.11.6. I'm assuming this will work with the latest 0.12.0 release as well. Thanks for the help.
