### ISSUE TITLE
Lambda hits AWS instead of Localstack when using SDK

### ISSUE THREAD

**Issue by Lastin** [localstack/localstack#2945]
# Type of request: This is a ...
[ ] bug report
[x] feature request

# Detailed description
Redirect default AWS endpoints to Localhost at OS level when using `LAMBDA_EXECUTOR=docker-reuse`.
Maybe add list of endpoints to `/etc/hosts` file.
List of endpoints to redirect is here: https://github.com/aws/aws-sdk-go/blob/master/aws/endpoints/defaults.go
Maybe make it optional by docker env variable?

## Expected behavior
Default endpoint resolver points to Localhost services

## Actual behavior
Default endpoint resolver points to AWS endpoints

# Steps to reproduce
1. Make lambda in go
1. Try to connect to service e.g. Dynamodb
1. Get token error because it tries to authenticate with actual AWS

## Command used to start LocalStack
...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
...

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-254) by [Unito](https://www.unito.io/learn-more)

**Comment by aaron-parsons** [comment]
Hi. Is this the same issue as #2937 ?

**Comment by Lastin** [comment]
@aaron-parsons hard to say.  like #2937
