### ISSUE TITLE
Appsync - VTL - TransactionWriteItems - Invalid type for parameters

### ISSUE THREAD

**Issue by ngouass** [localstack/localstack#2947]
# Type of request: This is a ...
[x] bug report
[ ] feature request

# Detailed description
Trying to use a TransactWriteItems operation failed.

**images attribute is a list of string !**

```
Parameter validation failed:\n
Invalid type for parameter TransactItems[0].Put.Item.images, value: [{'S': 'image_2.jpeg'}], type: <class 'list'>, valid types: <class 'dict'>\n
```

```
Invalid type for parameter TransactItems[1].Update.ConditionExpression, value: {'expression': 'attribute_exists(PK)'}, type: <class 'dict'>, valid types: <class 'str'>\n\n
```

### GrapgQL Query
    const query = `
              mutation createItem {
                createItem(item: {
                    shopId: "apple",
                    title: "Iphone 11",
                    price: 800,
                    description: "black",
                    category: "smartphone",
                    images: ["image_2.jpeg"]
                  } ) {
                  shopId
                  title
                  description
                  price
                  category
                  images
                }
              }
            `### VTL Request
```
#set($updatedAttributes = $ctx.args.item)
#set($id = $util.autoId())

#set($discard = $ctx.args.input.put("itemId", $id))
#set($discard = $updatedAttributes.put("status", "AVAILABLE"))
#set($discard = $updatedAttributes.put("createdAt", $util.time.nowISO8601()))

{
  "version": "2018-05-29",
  "operation": "TransactWriteItems",
  "transactItems": [
    {
      "table": "${subItemsTable}",
      "operation": "PutItem",
      "key": {
        "PK": $util.dynamodb.toDynamoDBJson("ITEM#$id"),
        "SK": $util.dynamodb.toDynamoDBJson("ITEM#$id")
      },
      "condition": {
        "expression": "attribute_not_exists(PK)"
      },
      "attributeValues": $util.dynamodb.toMapValuesJson($updatedAttributes)
    },
    {
      "table": "${subItemsTable}",
      "operation": "UpdateItem",
      "key": {
        "PK": $util.dynamodb.toDynamoDBJson("SHOP#$ctx.args.item.shopId"),
        "SK": $util.dynamodb.toDynamoDBJson("PROFILE#$ctx.args.item.shopId")
      },
      "update" : {
        "expression" : "ADD #count :plusOne",
        "expressionNames" : {
            "#count" : "itemsCount"
        },
        "expressionValues" : {
            ":plusOne" : { "N" : 1 }
        }
      },
      "condition": {
        "expression": "attribute_exists(PK)"
      }
    },
    {
      "table": "${subItemsTable}",
      "operation": "UpdateItem",
      "key": {
        "PK": $util.dynamodb.toDynamoDBJson("SHOP#$ctx.args.item.shopId"),
        "SK": $util.dynamodb.toDynamoDBJson("CATEGORY#$ctx.args.item.category")
      },
      "update": {
        "expression" : "SET category = :value ADD #count :plusOne",
        "expressionNames" : {
            "#count" : "itemsCount",
            
        },
        "expressionValues" : {
            ":plusOne" : { "N" : 1 },
            ":value" : { "S": "$ctx.args.item.category" }
        }
      }
    }
  ]
}
```

## Expected behavior
First operation should add a new item
Second operation should update the itemsCount on shop object
Third Operation should add a new category item 

## Actual behavior
**images attribute is a list of string !**

```
Parameter validation failed:\n
Invalid type for parameter TransactItems[0].Put.Item.images, value: [{'S': 'image_2.jpeg'}], type: <class 'list'>, valid types: <class 'dict'>\n
```

```
Invalid type for parameter TransactItems[1].Update.ConditionExpression, value: {'expression': 'attribute_exists(PK)'}, type: <class 'dict'>, valid types: <class 'str'>\n\n
```

# Steps to reproduce
## Command used to start LocalStack
```
version: '2.1'

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "4566-4700:4566-4700"
      - "443:443"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=serverless,cloudformation,dynamodb,iam,s3,appsync,edge
      - DEBUG=1
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY}
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
...

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-255) by [Unito](https://www.unito.io/learn-more)

**Comment by ngouass** [comment]
Hello @whummer , any update ?

**Comment by whummer** [comment]
Thanks for reporting @ngouass, and apologies for the delay. We've been working on reproducing this issue, but seems like there are still a couple of details missing to reliably reproduce it (data source/types, resolver configs, etc). Do you think you could share these additional details, to create a complete, isolated example? Would be great if you could get in touch with us directly via email or Slack - we'll be happy to look into it. Thanks for your support in resolving this!

**Comment by whummer** [comment]
Hi again @ngouass , quick update - do you think you can share a small, isolated example that helps us reproduce this particular issue? We'll be very happy to look into it. Thanks for your help.

**Comment by ngouass** [comment]
Hi @whummer, sorry for the delay. 
I will try to create an isolated project this weekend and share that.

**Comment by ngouass** [comment]
Hi @whummer, sorry the delay.

After investigating, I found that there are some conversion issues with utilities functions:

```

$util.dynamodb.toMapValues -> not translating array properly
$util.dynamodb.toDynamoDB -> not translating array properly
$util.dynamodb.toMapValuesJson -> not translating array properly
```

### Issue

=====> Expected behaviour (https://docs.aws.amazon.com/appsync/latest/devguide/resolver-util-reference.html#dynamodb-helpers-in-util-dynamodb)
```
Input:      $util.dynamodb.toDynamoDB({ "foo": "bar", "baz" : 1234, "beep": [ "boop"] })
Output:     {
               "M" : {
                   "foo"  : { "S" : "bar" },
                   "baz"  : { "N" : 1234 },
                   "beep" : {
                       "L" : [
                           { "S" : "boop" }
                       ]
                   }
               }
           }
```
=====> Actual behaviour
```
Input:      $util.dynamodb.toDynamoDB({ "foo": "bar", "baz" : 1234, "beep": [ "boop"] })
Output:     {
               "M" : {
                   "foo"  : { "S" : "bar" },
                   "baz"  : { "N" : 1234 },
                   "beep" : [ { "S" : "boop" } ] -->SHOULD BE AN OBJECT--> { "L": [  { "S" : "boop" } ] }
                   }
               }
           }
```

**Comment by whummer** [comment]
Hi @ngouass , apologies for the long delay on this one - somehow this issue must have slipped through the cracks. 

This issue should be resolved in the meantime - we've also added a test case in our integration test suite to avoid regressions. Can you please confirm whether the VTL functions work properly for you with the `latest` Docker image? 

Please keep us posted how it goes - thanks for your help!
