### ISSUE TITLE
SSL Cert for localhost.localstack.cloud

### ISSUE THREAD

**Issue by jsk95** [localstack/localstack#2953]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description
Cert for localhost.localstack.cloud seems to be expired
![image](https://user-images.githubusercontent.com/48934750/92430282-78d2a980-f1e8-11ea-9206-d2823450fc90.png)

...

## Expected behavior
Should not be expired
...

## Actual behavior
Is expired
...

# Steps to reproduce

## Command used to start LocalStack

...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

...

**Comment by whummer** [comment]
Thanks for reporting @jsk95 . Theoretically, the certificate should get automatically updated (re-downloaded) in regular intervals. Perhaps there may have been a networking issue, or your machine is behind a firewall..?

<img width="602" alt="image" src="https://user-images.githubusercontent.com/2807888/92443144-5d987780-f1b1-11ea-81ba-9f6ee0b8b4db.png">

You can also try to manually delete (or rename) the certificate files in your local tmp folder in `$TMPDIR/localstack/server.test.pem*`, so the cert files should get re-initialized on the next startup. Hope that helps - please keep us posted. Thanks

**Comment by whummer** [comment]
Any update on this issue @jsk95 - have you been able to get it working with the instructions above? Thanks
