### ISSUE TITLE
Lambda trigger parameters missing (PreSignUp_*)

### ISSUE THREAD

**Issue by soulshake** [localstack/localstack#2964]
# Type of request: This is a ...
[x] bug report
[ ] feature request

# Detailed description
Lambdas triggered by Cognito `PreSignUp_*` events don't receive valid input.

This seems similar to https://github.com/localstack/localstack/issues/2893 except that it affects `PreSignUp_*` Lambda triggers as opposed to `preTokenGeneration`.

## Expected behavior
As described in [the documentation](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-pre-sign-up.html).
(Notably, the `userName` should contain the `sub`.)

Format of example `event` received as Lambda input (real Cognito):

```
{
    "version": "1",
    "region": "us-east-2",
    "userPoolId": "us-east-2_abc123",
    "userName": "e6102273-2a43-47cc-b12e-132c78334121",     # <--- note userName containing sub
    "callerContext": {
        "awsSdkVersion": "aws-sdk-unknown-unknown",
        "clientId": "CLIENT_ID_NOT_APPLICABLE"
    },
    "triggerSource": "PreSignUp_AdminCreateUser",
    "request": {
        "userAttributes": {
            "email": "foo@example.com"
        },
        "validationData": null
    },
    "response": {
        "autoConfirmUser": false,
        "autoVerifyEmail": false,
        "autoVerifyPhone": false
    }
}
```

#### PreSignUp_AdminCreateUser
Example `event` as received by Lambda running on LocalStack:

```
{
>   version: '$LATEST',
>   triggerSource: 'PreSignUp_AdminCreateUser',
>   region: 'us-east-2',
>   userPoolId: 'us-east-2_b6da970f6aed40f987eb7252ecbbf771',
>   callerContext: { awsSdkVersion: 'TODO', clientId: 'CLIENT_ID_NOT_APPLICABLE' },
>   request: {
>     userAttributes: { username: 'ruth@example.com', client_id: null },
>     validationData: {},
>     clientMetadata: {}
>   },
>   response: {}
> }
```

^ lacks top-level key `userName` containing the `sub`

#### PreSignUp_SignUp
```
{
  "version": "$LATEST",
  "triggerSource": "PreSignUp_SignUp",
  "region": "us-east-2",
  "userPoolId": "us-east-2_d72647ae02704a69acd0ba1c3e7143e5",
  "callerContext": {
    "awsSdkVersion": "TODO",
    "clientId": "j2vy46btl4s5f3145oxhq4gw7c"
  },
  "request": {
    "userAttributes": {},
    "validationData": {},
    "clientMetadata": {}
  },
  "response": {},
  "userName": "bob@example.com"
}
```

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-260) by [Unito](https://www.unito.io/learn-more)

**Comment by Gidmark-wowgroup** [comment]
This seems to affect Post authentication and Pre token generation requests as well

**Comment by whummer** [comment]
@soulshake @Gidmark-wowgroup  Apologies for the long delay on this one. We believe that this should be fixed in the meantime, can you please give it another try with the `latest` version of the Docker image? Please let us know if the problem persists. Thanks for your help!
