### ISSUE TITLE
LocalStack start not running the lambda at port 4574

### ISSUE THREAD

**Issue by vishalnigam** [localstack/localstack#2967]
# Type of request:.
Starting the LocalStack with 'SERVICES=s3,iam,sns,lambda,sqs,dynamodb LAMBDA_EXECUTOR=docker localstack start' command is not enabling the lambda. 
[ ] bug report
[ ] feature request

# Detailed description
# The log output of the LocalStack start as follows...
Starting local dev environment. CTRL-C to quit.
2020-09-09 22:08:00,457 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Starting edge router (https port 4566)...
Starting mock DynamoDB service in http ports 4566 (recommended) and 4569 (deprecated)...
Starting mock IAM service on http ports 4566 (recommended) and 4593 (deprecated)...
2020-09-09T22:08:02:INFO:botocore.credentials: Found credentials in environment variables.
Running on 0.0.0.0:4566 over https (CTRL + C to quit)
Running on 0.0.0.0:4569 over http (CTRL + C to quit)
Running on 0.0.0.0:4593 over http (CTRL + C to quit)
2020-09-09T22:08:02:INFO:localstack.multiserver: Starting multi API server process on port 50317
Running on 0.0.0.0:50317 over http (CTRL + C to quit)
Starting mock Lambda service on http ports 4566 (recommended) and 4574 (deprecated)...
Starting mock CloudWatch Logs service on http ports 4566 (recommended) and 4586 (deprecated)...
Starting mock S3 service on http ports 4566 (recommended) and 4572 (deprecated)...
Starting mock SNS service on http ports 4566 (recommended) and 4575 (deprecated)...
Starting mock SQS service on http ports 4566 (recommended) and 4576 (deprecated)...
Running on 0.0.0.0:4586 over http (CTRL + C to quit)
Running on 0.0.0.0:4572 over http (CTRL + C to quit)
Running on 0.0.0.0:4575 over http (CTRL + C to quit)
Running on 0.0.0.0:4576 over http (CTRL + C to quit)
Waiting for all LocalStack services to be ready
Ready.

====================================

## Expected behavior
As per my understanding, Lambda mock should be enabled and available at port 4574.

## Actual behavior
I can use awscli to create S3 buckets and push the documents as follows,
aws --endpoint-url=http://0.0.0.0:4566 s3api create-bucket --bucket iotest
aws --endpoint-url=http://0.0.0.0:4566 s3api put-object --bucket iotest --key runtime-zip --body ~/target/data-collection-lambda-0.0.1-SNAPSHOT-runtime.zip
aws --endpoint-url=http://0.0.0.0:4566 s3api list-objects-v2 --bucket iotest

Listing showing me following bucket and details,
{
    "Contents": [
        {
            "Key": "runtime-zip",
            "LastModified": "2020-09-10T16:27:42.000Z",
            "ETag": "\"89186d503a8b77e19dde6336b3ee77fa\"",
            "Size": 10689712,
            "StorageClass": "STANDARD"
        }
    ]
}

But using awscli for creating Lambda Layer or Lambda is not working. On using the following awscli command...

aws --endpoint-url=http://0.0.0.0:4566 lambda publish-layer-version --layer-name firstlayer --description "my-first-layer" --compatible-runtimes java8 --content S3Bucket=iotest,S3Key=runtime-zip

An error occurred (404) when calling the PublishLayerVersion operation: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.</p>

# Steps to reproduce
## Command used to start LocalStack
SERVICES=s3,iam,sns,lambda,sqs,dynamodb LAMBDA_EXECUTOR=docker localstack start

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
...

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-261) by [Unito](https://www.unito.io/learn-more)

**Comment by vishalnigam** [comment]
Please let me know if you have any idea as what is the issue of Lambda Service not working

**Comment by calvernaz** [comment]
Is this still in the plans to implement?
