### ISSUE TITLE
PRO:Unable to trigger Lambda through SNS

### ISSUE THREAD

**Issue by ashameem123** [localstack/localstack#2968]
# Type of request: This is a ...

[ ] bug report

# Detailed description
Trying to trigger an event from S3 to SNS which is connected to lambda. (Once SNS receives an event from S3, lambda should trigger)
...

## Expected behavior 
After uploading a file on S3, an event should be received by SNS topic and Lambda should trigger

...

## Actual behavior
Lambda isn't triggering and getting an exception/failure
...

# Steps to reproduce

docker-compose up -d 
1.	Create Bucket-> 
aws --endpoint-url=http://localhost:4566 s3 mb s3://test-bucket-sns
2.	Create Topic->
aws sns create-topic --name putnotifications --endpoint-url=http://localhost:4575
3.	Subscribe to the topic-> (NOT NECESSARY)
aws --endpoint-url=http://localhost:4575 sns subscribe --topic-arn arn:aws:sns:us-east-1:000000000000:putnotifications --protocol email --notification-endpoint test123@yahoo.com
4.  PUT Notification->
aws s3api put-bucket-notification-configuration --bucket test-bucket-sns --notification-configuration file://snsTopicConfiguration.json --endpoint-url=http://localhost:4566

5. Create Function->
aws lambda create-function --endpoint-url=http://localhost:4574 --function-name SQSdemo --runtime java11 --handler com.aws.lamda.SQSdemo --zip-file fileb://C:/AWS/Localstack/aws-lambda-example/target/aws-labmda-example-1.0-SNAPSHOT.jar --role arn:aws:iam::1234567:role/anything --environment Variables="{PROFILE=LOCAL,AWS_REGION=us-east-1}"

6. Subscribe lambda to Topic:
aws sns subscribe --topic-arn arn:aws:sns:us-east-1:000000000000:putnotifications --protocol lambda --notification-endpoint arn:aws:lambda:us-east-1:000000000000:function:SQSdemo --endpoint-url=http://localhost:4575

7. upload a file in s3:
aws s3 cp s3-event.json s3://test-bucket-sns --endpoint-url=http://localhost:4566

snsTopicConfiguration.json -
{
    "TopicConfigurations": [
        {
            "TopicArn": "arn:aws:sns:us-east-1:000000000000:putnotifications",
            "Events": [
                "s3:ObjectCreated:*"
            ]
        }
    ]
}

Docker file:
version: '2.1'

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main111}"
    image: localstack/localstack:latest
    ports:
      - "4566-4599:4566-4599"
      - "${PORT_WEB_UI-8081}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=${SERVICES- }
      ##- DEBUG=${DEBUG- }
      - DEBUG=1
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=docker
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LAMBDA_DOCKER_NETWORK=aws-lambda-example_default
      - HOST_TMP_FOLDER=${TMPDIR}
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

Error i am receiving is:
![LambdaException](https://user-images.githubusercontent.com/54183749/92799954-dba77a80-f379-11ea-9b90-a98b377d1db8.JPG)

**Comment by whummer** [comment]
Thanks for reporting @ashameem123 . This looks like a classpath issue (likely caused by incompatible class files in your Lambda archive, and in the LocalStack Java Lambda runner) - any chance you can provide a stripped-down version of `aws-labmda-example-1.0-SNAPSHOT.jar` to help us reproduce this issue in more detail? Thanks for your help.

**Comment by ashameem123** [comment]
@whummer - thanks for responding. I am not sure what do you mean by "stripped down version", but i have uploaded the working project on  --> https://github.com/ashameem123/testLocalStack



[Localstack_DemoProject-1.0-SNAPSHOT.jar.zip](https://github.com/localstack/localstack/files/5219635/Localstack_DemoProject-1.0-SNAPSHOT.jar.zip)


![LS_exception](https://user-images.githubusercontent.com/54183749/93110359-d2205a00-f67a-11ea-9667-fc2170fe8e9d.JPG)

**Comment by ashameem123** [comment]
@whummer   --> Also when i manually invoke lambda using below command, i can see the expected output,

aws --endpoint-url=http://localhost:4574 lambda invoke --function-name SNStoLambda outfile.txt

![LambdaInvokedManually](https://user-images.githubusercontent.com/54183749/93121694-e0767200-f68a-11ea-846c-3ae8593a2e4b.JPG)

**Comment by ashameem123** [comment]
@whummer --> Any update please?

**Comment by whummer** [comment]
Thanks for the update @ashameem123 . We have now merged a refactoring of the Java Lambda executor in PR #3077 which should (hopefully) fix this issue. Can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists. Many thanks for your support.

**Comment by ashameem123** [comment]
Issue is fixed.. Thank you so much for fixing it.
