### ISSUE TITLE
Lambdas can not access external variables in Python 3

### ISSUE THREAD

**Issue by cclauss** [localstack/localstack#297]
flake8 testing of https://github.com/localstack/localstack on Python 3.6.2  [Line 297](https://github.com/localstack/localstack/blob/master/localstack/utils/cloudformation/template_deployer.py#L294-L297)

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./localstack/utils/cloudformation/template_deployer.py:297:57: F821 undefined name 'e'
        if not list(filter(lambda marker: marker in str(e), markers)):
                                                        ^
```

**Comment by whummer** [comment]
Fixed in #299
