### ISSUE TITLE
MD5 checksum mismatch with SQS custom timer messages.

### ISSUE THREAD

**Issue by GabiruRyo** [localstack/localstack#2973]
# Type of request: This is a ...
[x] bug report
[ ] feature request

# Detailed description
Hello!
I'm trying to send and consume messages from a localstack SQS queue at a Spring Boot framework with Kotlin language, AWS SDK and Spring Cloud AWS Messaging libraries. 
Each message has a [custom timer](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-message-timers.html) which is set by adding an attribute `SQS_DELAY_HEADER` to the SQS message headers (code at `Steps to reproduce`). 

I can create the queue at SQS and create an SDK SQS client with the local custom endpoint without issues, but I 'm facing problems while subscribing to a queue and sending messages to it. I receive exceptions about MD5 mismatches.
Already saw PR #1850, tried updating the lib, but the problem still persists.
It works fine with the regular AWS official endpoint.

## Versions
* org.springframework.boot:2.2.6.RELEASE
* org.springframework.cloud:spring-cloud-aws-messaging:2.0.1.RELEASE
* com.amazonaws:aws-java-sdk:1.11.859
* kotlin:1.3.71
* java:8
* localstack:0.11.4

## Expected behavior
To send timer messages to a local SQS and listen to it without throwing any exceptions.

## Actual behavior
Throws MD5 checksum mismatch exceptions.
When trying to listen:

```
2020-09-11 17:39:34.184  WARN 64918 --- [lTaskExecutor-1] s.c.a.m.l.SimpleMessageListenerContainer : An Exception occurred while polling queue 'http://localhost:4566/000000000000/local_timeout_queue'. The failing operation will be retried in 10000 milliseconds

com.amazonaws.AmazonClientException: MD5 returned by SQS does not match the calculation on the original request. (MD5 calculated by the message attributes: "c60fab656652af01bb260464de19cfb4", MD5 checksum returned: "c46fe03ff8184c639fc3ee70ae665dc7")
```

When trying to send:

```
org.springframework.messaging.MessageDeliveryException: Failed to send message to QueueMessageChannel[QueueMessageChannel@3adcf05a]; nested exception is com.amazonaws.AmazonClientException: MD5 returned by SQS does not match the calculation on the original request. (MD5 calculated by the message attributes: "5246768cc0b4bf109184419a2985bafe", MD5 checksum returned: "6f107dbc0d440eb9a5750a9d55e18f5e")
```

# Steps to reproduce
## Command used to start LocalStack
I'm using docker-compose with some modifications from the repository's original.

```yaml
version: "3"
services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "8000:8000"
    environment:
      - SERVICES=sqs,ses
      - DEFAULT_REGION=us-east-1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "$PWD/localstack:/docker-entrypoint-initaws.d"
```

It runs an init script to create the `queue`, which is running fine.

```
aws configure set aws_access_key_id accesskey123
aws configure set aws_secret_access_key secretaccesskey123
aws sqs create-queue --endpoint-url=http://localhost:4566 --queue-name=local_timeout_queue --region=us-east-1
```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
Starting with the setup where `baseUrl` is the environment variable with the value `http://localhost:4566`

```kotlin
@Bean
fun amazonSQSAsync(): AmazonSQSAsync {

    return AmazonSQSAsyncClientBuilder
        .standard()
        .withEndpointConfiguration(
            AwsClientBuilder.EndpointConfiguration(baseUrl, "us-east-1")
        )
        .build()
}
```

The AWS credentials local environment variables:
`AWS_ACCESS_KEY_ID=accesskey123;AWS_SECRET_ACCESS_KEY=secretaccesskey123`

Using `org.springframework.cloud.aws.messaging.listener.annotation.SqsListener` it listens to a queue (environment variable `sqs-url.timeoutConfiguration` with the value `http://localhost:4566/000000000000/local_timeout_queue`) and handles the incoming data. 

```kotlin
@SqsListener(
    "\${sqs-url.timeoutConfiguration}",
    deletionPolicy = SqsMessageDeletionPolicy.ON_SUCCESS
)
fun handleTimeoutConfigurationMessage(data: String) {
    logger.info { "Trying to consume new message: $data" }

    val message = TimeoutConfigurationQueue(objectMapper.readTree(data))

    configurationService.consumeQueue(message)
}
```

To send messages, I'm using the method `convertAndSend` from  `org.springframework.cloud.aws.messaging.core.QueueMessagingTemplate`.

```kotlin
fun convertAndSendWithTimer(time: Int, message: TimeoutConfigurationMessage) {
    logger.info { "Sending new timeout message to queue: $message" }
    val headers: Map<String, Any> = mapOf(
        MessageHeaders.CONTENT_TYPE to MediaType.APPLICATION_JSON_VALUE,
        SqsMessageHeaders.SQS_DELAY_HEADER to time
    )
    queueMessagingTemplate.convertAndSend(
        sqsUrl,
        message,
        headers
    )
}
```

Thanks in advance!

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-262) by [Unito](https://www.unito.io/learn-more)

**Comment by tkent** [comment]
@GabiruRyo  - I'm fairly certain you're running into the issue I described in #2976. You ought to be able to confirm that by sending messages using the AWS SDK client, rather than using the `QueueMessagingTemplate`. For example...

```kotlin
// Convert your TimeoutConfigurationMessage object to a string first
val smr = SendMessageRequest(queueUrl, message)
  .withMessageAttributes(mapOf(
     MessageHeaders.CONTENT_TYPE to MessageAttributeValue()
         .withDataType(MessageAttributeDataTypes.STRING)
         .withStringValue(MediaType.APPLICATION_JSON_VALUE),
      SqsMessageHeaders.SQS_DELAY_HEADER to MessageAttributeValue()
         .withDataType(MessageAttributeDataTypes.NUMBER)
         .withStringValue(time.toString())
  ))
amazonSQSAsync.send(smr)
```

If that works, then we're probably bumping into the same thing.

**Comment by GabiruRyo** [comment]
@tkent Thanks for the reply. I'll try this later today.

**Comment by GabiruRyo** [comment]
@tkent I tested by sending the message with the AWS SDK client and it worked.

**Comment by tkent** [comment]
@GabiruRyo Ah, great! I think that answers that then. We're bumping into the same thing.

**Comment by tkent** [comment]
Now that #2976 is closed, this should be closed as well.
