### ISSUE TITLE
SQS - Wrong MD5 computed for message attributes when using custom data types

### ISSUE THREAD

**Issue by tkent** [localstack/localstack#2976]
[X ] bug report
[ ] feature request

# Detailed description

If you specify a [custom data type](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/sqs/model/MessageAttributeValue.html#setDataType-java.lang.String-) for a message attribute, then the MD5 returned from localstack will be wrong. For example, if sending a request using the following kotlin snippet:

```kotlin
val sqm = SendMessageRequest(queueUrl, message)
    .addMessageAttributesEntry(
        "somevalue",
        MessageAttributeValue()
            .withDataType(MessageAttributeDataTypes.STRING+".custom")
            .withStringValue("somevalue")
    )
amazonSQSAsync.sendMessage(sqm)
```

You'll get a stack trace along the lines of:

```
com.amazonaws.AmazonClientException: MD5 returned by SQS does not match the calculation on the original request. (MD5 calculated by the message attributes: "9e05cca738e70ff6c6041e82d5e77ef1", MD5 checksum returned: "47f91819dd92246543c0e731c46d3804")
```

...Where the returned MD5 sum is for an attribute map with the `.custom` part of the data type removed.

## Other Notes

This will come up often with applications that use [spring-cloud-aws-messaging](https://github.com/spring-cloud/spring-cloud-aws). That library expects all numeric message attributes to be custom, suffixed with their class name (for an example, see [here](https://github.com/spring-cloud/spring-cloud-aws/blob/master/spring-cloud-aws-messaging/src/main/java/org/springframework/cloud/aws/messaging/core/QueueMessageChannel.java#L215))

I'm fairly certain this is the same issue as #2973, but the title there suggests it's related to timer messages.

# Version Information

I only tested with `localstack/localstack:0.11.4`

# Steps to reproduce

Send any SQS message that includes a message attribute with a custom data type.

**Comment by tekener** [comment]
Bug was introduced with localstack/localstack:0.11.3. The previous version localstack/localstack:0.11.2 is running fine.

**Comment by whummer** [comment]
Thanks for reporting @tkent @tekener . This should be fixed upstream in spulec/moto#3346 and is now available in LocalStack. Can you please pull the `latest` Docker image and give it another try? Please report here if the problem persists. Thanks!

**Comment by tkent** [comment]
@whummer 

 I just tested with the latest localstack image (`b19b5b54c1f6ed82b95a015dbd8eacbf1a1b0a50977ddc0f7e00117e340bc45c`). Unfortunately, the upstream fix by @usmangani1 does not fix the issue at all. When custom data types are used with message attributes, the wrong MD5 is still computed.

The fix only added support for the the example custom data type I used in this issue (`String.custom`). That was meant for demonstration purposes only, I'm sure nobody happens to use that.

There was clearly a deep misunderstanding of how this is supposed to work, so I left a comment in in the merge request, https://github.com/spulec/moto/pull/3346/files

**Comment by whummer** [comment]
Thanks for the update @tkent . This should now (hopefully) be fixed via spulec/moto#3399 and is now available in LocalStack - can you please pull the `latest` Docker image and give it another try? Please report here if the problem persists. Thanks!

**Comment by tkent** [comment]
@whummer Confirmed! The changes by @artemtere fix the problem.

**Comment by HenrikPublic** [comment]
Will there be a 0.12.3 release, then?
I still see the problem in 0.12.2.
https://github.com/localstack/localstack/releases
