### ISSUE TITLE
localstack/bigdata container won't completely start up without intervention

### ISSUE THREAD

**Issue by ChristopherMacGown** [localstack/localstack#2979]
# Type of request: This is a ...
[X] bug report
[ ] feature request

# Detailed description
When launching an AWS Athena query, localstack will launch a helper container `localstack/bigdata` that runs as an entry point `/etc/bootstrap.sh`. After starting HDFS, Yarn, and Spark, the bootstrap script blocks waiting for HDFS to exit safe mode. Unfortunately, the HDFS namenode never comes up because `/tmp/hadoop-rootdfs/name is in an inconsistent state: storage directory does not exist or is not accessible.`.

It's possible to get the container to move forward by doing the following:

```
# After connecting to the container in interactive mode
root@26d869644255:# /usr/local/hadoop/sbin/stop-dfs.sh  # start-dfs.sh won't run if any data nodes or secondary name nodes are running
root@26d869644255:# hdfs namenode -format 
... a lot of verbosity elided ...
root@26d869644255:# /usr/local/hadoop/sbin/start-dfs.sh
```

At which point the bootstrap script will be able to exit readonly mode and continue

## Expected behavior
The container should come up without any intervention.

## Actual behavior
The container will not complete its startup unless the namenode is formatted.

# Steps to reproduce
This can be reproduced by merely starting the container with the following docker-compose configuration. The same thing happens if the container is instead started via localstack itself.

```
  localstack_bigdata:
    container_name: localstack_bigdata
    image: localstack/bigdata
    stdin_open: true
    tty: true
```

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-263) by [Unito](https://www.unito.io/learn-more)

**Comment by cmiller96catalyte** [comment]
Any update on this?

**Comment by whummer** [comment]
Thanks @ChristopherMacGown @cmiller96catalyte . In the meantime, we have added a number of enhancements to make the startup procedure of the localstack/bigdata container more stable (for EMR/Athena in Pro). Closing this issue as outdated - but please do let us know if the problem persists.. Thanks!

**Comment by 13tales** [comment]
I am also having this problem when trying to use Athena in Localstack Pro on MacOS; it hasn't been resolved.

**Comment by cmiller96** [comment]
This issue hasn't been resolved. I ran into this again on MacOS Ventura 13.4 M2 Pro. 

I had to log into the bigdata container to stop dfs, format namenode, then start dfs. The container then completed startup.

**Comment by whummer** [comment]
Thanks for the update @cmiller96 @13tales . Can you please share some details about your setup, and .

Please note that the original issue posted here was related to the old "bigdata container", which was our previous approach of running a sidecar container (alongside the LocalStack main container) to run the bigdata workloads for Athena, Glue, EMR, etc. 

By now, we have introduced a new execution mode called "mono container" which basically spins up the bigdata services (Hive, Spark, Hadoop, etc) in the `localstack_main` container directly.

In the issue you're seeing, are you referring to the new mono container mode? Please note that the old "bigdata container" mode is deprecated and will be removed in an upcoming release. 

If you can share some details about your use case, ideally a sequence of steps to reproduce the problem (ideally in a new Github issue), that would be great.. Thanks!

**Comment by cmiller96** [comment]
@whummer Ahh, I was still using the old sidecar BigData container. I updated to v2.2.0 and it started up without issue, sorry for the confusion.
