### ISSUE TITLE
SQS queue can't receive messages from an SNS topic in a different region

### ISSUE THREAD

**Issue by sadams** [localstack/localstack#2982]
[x] bug report
[ ] feature request

In localstack, SNS topics and subscriptions are global (they ignore region from the client), but SQS queues are regional. E.g. If you create an SQS queue in a region, it is only listed when your client connects to the correct region. So far, so good. However, in AWS each QueueUrl has the region in the url, so you can subscribe between regions (e.g. a queue in eu-west-2 can subscribe to a topic in us-east-1). In localstack this isn't the case, because the queue's QueueUrl doesn't have any identifier as to which region it is created in. If you try and get around this by giving queues regional names (which they don't require on AWS) it still doesn't work. I think this is because localstack assumes it only needs to resolve subscribed queues in the same region as the originating topic (or the subscription?).

## Expected behavior
Any SQS queues subscribed to an SNS topic, regardless of region, get a copy of a published message.

## Actual behavior
The non-default-region queue doesn't get the message and the console shows an error: "Removing non-existent queue..."

# Steps to reproduce

## Command used to start LocalStack

Using identical copy of https://github.com/localstack/localstack/blob/master/docker-compose.yml

    SERVICES=sqs,sns,s3 docker-compose up

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

```
export AWS_ACCESS_KEY_ID=foo 
export AWS_SECRET_ACCESS_KEY=foo
export AWS_PAGER=""
```

### ambiguous queue-url issue:

```
# create topic
aws --region 'us-east-1' --endpoint-url=http://localhost:4566 sns create-topic --name foo

# create queues
aws --region 'eu-west-2' --endpoint-url=http://localhost:4566 sqs create-queue --queue-name fooq
#{
#    "QueueUrl": "http://localhost:4566/000000000000/fooq"
#}
aws --region 'us-east-1' --endpoint-url=http://localhost:4566 sqs create-queue --queue-name fooq
#{
#    "QueueUrl": "http://localhost:4566/000000000000/fooq"
#}

# no way to determine which queue is subscribing (subs needs to be in the same region as the topic):
aws --region 'us-east-1' --endpoint-url=http://localhost:4566 sns subscribe --topic-arn "arn:aws:sns:us-east-1:000000000000:foo" --protocol "sqs" --notification-endpoint "http://localhost:4566/000000000000/fooq"
```

### work around (also not working)

```bash script

# create topic
aws --region 'us-east-1' --endpoint-url=http://localhost:4566 sns create-topic --name foo

# create queues
aws --region 'eu-west-2' --endpoint-url=http://localhost:4566 sqs create-queue --queue-name fooq-eu
#{
#    "QueueUrl": "http://localhost:4566/000000000000/fooq-eu"
#}
aws --region 'us-east-1' --endpoint-url=http://localhost:4566 sqs create-queue --queue-name fooq-us
#{
#    "QueueUrl": "http://localhost:4566/000000000000/fooq-us"
#}

# subscribe
aws --region 'us-east-1' --endpoint-url=http://localhost:4566 sns subscribe --topic-arn "arn:aws:sns:us-east-1:000000000000:foo" --protocol "sqs" --notification-endpoint "http://localhost:4566/000000000000/fooq-us"
aws --region 'us-east-1' --endpoint-url=http://localhost:4566 sns subscribe --topic-arn "arn:aws:sns:us-east-1:000000000000:foo" --protocol "sqs" --notification-endpoint "http://localhost:4566/000000000000/fooq-eu"

# publish message
aws --region 'us-east-1' --endpoint-url=http://localhost:4566 sns publish --topic-arn "arn:aws:sns:us-east-1:000000000000:foo" --message "111"

# check messages (us-east-1)
aws --region 'us-east-1' --endpoint-url=http://localhost:4566 sqs receive-message --visibility-timeout=5 --max-number-of-messages=5 --queue-url "http://localhost:4566/000000000000/fooq-us"
# has message

# check messages (eu-west-2)
aws --region 'eu-west-2' --endpoint-url=http://localhost:4566 sqs receive-message --visibility-timeout=5 --max-number-of-messages=5 --queue-url "http://localhost:4566/000000000000/fooq-eu"
# has NO message
# shows error in localstack logs: 
# 2020-09-15T13:19:33:INFO:localstack.services.sns.sns_listener: Removing non-existent queue "http://localhost:4566/000000000000/fooq-eu" subscribed to topic "arn:aws:sns:us-east-1:000000000000:foo"
```

**Comment by whummer** [comment]
Thanks for reporting @sadams . As you correctly pointed out, the assumption in general is that you're using a single region to create your resources. Would it be an option in your case to parameterize the region via `--region $REGION`, and then use the same region across the board for your tests? Marking this as an enhancement/feature request in the meantime. Thanks

**Comment by sadams** [comment]
> Thanks for reporting @sadams . As you correctly pointed out, the assumption in general is that you're using a single region to create your resources. Would it be an option in your case to parameterize the region via `--region $REGION`, and then use the same region across the board for your tests? Marking this as an enhancement/feature request in the meantime. Thanks

Thanks for getting back to me. I put all my topics/queues into a single region in the end and named my queues with regional suffixes to get around the issue. 

Either way, it's still great to have a local alternative to using real aws, so thanks for working on the project!
