### ISSUE TITLE
!!! ⚠️ Read this if you're experiencing connection issues with the "latest" Docker image ⚠️ !!!

### ISSUE THREAD

**Issue by whummer** [localstack/localstack#2983]
Dear LocalStack users,

We have recently merged a **breaking change**, which sunsets the deprecated service-specific ports and now **exposes ALL services** via the **edge service** ONLY (port `4566` by default) - see here: https://github.com/localstack/localstack/pull/2905

This change will be available in the `localstack/localstack:latest` Docker image, effective immediately. If you are using the `latest` image, then your client/test code is likely going to break, as the deprecated service-specific ports are not exposed anymore.

You basically have **two options**, moving forward:
1. Adjust your client logic to use `http://localhost:4566` (or `http://$LOCALSTACK_HOSTNAME:4566`) as the default endpoint to connect to, for all services
2. Roll back to using the Docker image version `localstack/localstack:0.11.5` (the last tagged version that uses the deprecated service ports)

If neither of these options works for you, please post a message in this thread, so we can address any remaining networking/connectivity issues caused by this recent change. Thanks!

**Comment by sdasari404** [comment]
hi @whummer,

Apologies in advance if this is unrelated to the port change or if it's an issue on my end. 

I have a simple lambda which should send a message to SQS when a file is added to my s3 bucket. 

**Serverless.yml**
```
service: test-lambda
frameworkVersion: '1'

plugins:
  - serverless-localstack

custom:
  localstack:
    debug: true
    stages:
      - local
    host: http://localhost
    edgePort: 4566
    autostart: true
    docker:
      sudo: False

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-southeast-2
  gameAssetsBucketName: assets-dev
  timeout: 30

  deploymentBucket:
    name: lambda-bucket 
    serverSideEncryption: AES256

functions:
  onItemAdded:
    handler: src/onItemAdded.handle
    events:
      - s3:
          bucket: ${self:provider.gameAssetsBucketName}
          event: s3:ObjectCreated:*
          # existing: true # commenting this out temporarily as localstack doesn't support adding a lambda to an existing S3 bucket, will need to be revisited and updated
```

**src/onItemAdded.js**
```
var AWS = require('aws-sdk');
var sqs = new AWS.SQS({accessKeyId:"hello", secretAccessKey: "world", region: "ap-southeast-2", apiVersion: '2012-11-05'});

module.exports.handler = async (event) =>  {
  try {
    const message = {
      bucket: event.Records[0].s3.bucket,
      object: event.Records[0].s3.object
    }
    console.log(`message: ${JSON.stringify(message)}`);
    var params = {
      MessageBody: JSON.stringify(message),
      QueueUrl: "http://localstack:4566/000000000000/test-queue",
      MessageGroupId: "default"
    };
    await sqs.sendMessage(params).promise()
      .then(data => console.log("Successfully added message to queue", data.MessageId))
      .catch(err => console.log("Error: ", err));;
  } catch (err) {
    console.log(err);
  }
}
```
**SQS queue**
```
>> SQS : ConfigQueue queue <<
{
    "QueueUrl": "http://localstack:4566/000000000000/test-queue"
}
```

When my handler tries to send a message to the Queue, I get the following error

```
Error:  UnknownEndpoint: Inaccessible host: `localstack'. This service may not be available in the `ap-southeast-2' region.
localstack_main | >     at Request.ENOTFOUND_ERROR (/var/task/node_modules/aws-sdk/lib/event_listeners.js:507:46)
localstack_main | >     at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
localstack_main | >     at Request.emit (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
localstack_main | >     at Request.emit (/var/task/node_modules/aws-sdk/lib/request.js:688:14)
localstack_main | >     at ClientRequest.error (/var/task/node_modules/aws-sdk/lib/event_listeners.js:339:22)
localstack_main | >     at ClientRequest.<anonymous> (/var/task/node_modules/aws-sdk/lib/http/node.js:96:19)
localstack_main | >     at ClientRequest.emit (events.js:315:20)
localstack_main | >     at ClientRequest.EventEmitter.emit (domain.js:482:12)
localstack_main | >     at Socket.socketErrorListener (_http_client.js:426:9)
localstack_main | >     at Socket.emit (events.js:315:20) {
localstack_main | >   code: 'UnknownEndpoint',
localstack_main | >   region: 'ap-southeast-2',
localstack_main | >   hostname: 'localstack',
localstack_main | >   retryable: true,
localstack_main | >   originalError: Error: getaddrinfo ENOTFOUND localstack
localstack_main | >       at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26) {
localstack_main | >     errno: 'ENOTFOUND',
localstack_main | >     code: 'NetworkingError',
localstack_main | >     syscall: 'getaddrinfo',
localstack_main | >     hostname: 'localstack',
localstack_main | >     region: 'ap-southeast-2',
localstack_main | >     retryable: true,
localstack_main | >     time: 2020-09-16T03:21:36.592Z
localstack_main | >   },
localstack_main | >   time: 2020-09-16T03:21:36.592Z
localstack_main | > }
localstack_main | > END RequestId: e48e15b0-eb8f-11e6-4d9e-77e538e666cb
localstack_main | > REPORT RequestId: e48e15b0-eb8f-11e6-4d9e-77e538e666cb	Init Duration: 390.45 ms	Duration: 284.51 ms	Billed Duration: 300 ms	Memory Size: 1536 MB	Max Memory Used: 57 MB
localstack_main | 2020-09-16T03:21:36:INFO:localstack.services.edge: Unable to find forwarding rule for host "7b7244a6f929:4566", path "/", target header "", auth header "", data "b''"
```

Please let me know if there is something I've missed in my config or how I could potentially fix this issue.

**Comment by rayjlinden** [comment]
This was a pretty freakin' big breaking change to make as a point release!!!  You guys had been pretty good about keeping things backward compatible which is why we were on latest (in retrospect that was foolish on our part.). This, of course, broke everything - and hours of engineering time was wasted because of it.  Fortunately, the fix to bin the docker version is an easy one.

We will update - but we have over 300 files that have those configs.  So it will take some time.

What I do not understand is why the hell did it have to be breaking change?  What is wrong with leaving those ports open?  You could have even made it so it was the edge router that hosted all those ports,  Or another stupid service that just listened on those ports and forwarded to the edge router.  You did not HAVE to break things.

You guys are getting popular enough and big enough you should start thinking about the impact of change on your users not just rushing to the "brave new world" no matter what pain it causes.

**Comment by billputer** [comment]
What's worse, is that this was pushed out to all users *without even a point release*! It's not in [the changelog](https://github.com/localstack/localstack/blob/master/CHANGELOG.md), there's nothing in [the GitHub releases](https://github.com/localstack/localstack/releases) to reflec this, and [Dockerhub docs](https://hub.docker.com/r/localstack/localstack) still show the old port numbers. This is a popular tool, and I bet the vast majority of users are following the recommended `image: localstack/localstack` which pulls latest. This is a fundamental failure of the release process.

**Comment by whummer** [comment]
Thanks all for the feedback.

>  You guys had been pretty good about keeping things backward compatible which is why we were on latest

@rayjlinden It is true that so far we have mostly been focusing on staying backward compatible. However, the changes in #2905 are a long overdue refactoring which can result in certain performance improvements (reduce open network ports, use in-memory processing instead of network roundtrips, less open file descriptors, ...) and gives us more flexibility and scalability to continue developing LocalStack, moving forward. In the future, we will continue to focus on backwards compatibility, and will reduce the number of painful, breaking changes to a minimum.

> this was pushed out to all users without even a point release!

@billputer That's correct - the changes are in fact not yet included in any point release, but only on `latest` (which is what probably most users are using, as you mentioned). Thanks for pointing out the change log - we have now updated the CHANGELOG and [release notes](https://github.com/localstack/localstack/releases/tag/v0.11.5) and included a note that should give an indication of the breaking change.

@sdasari404 I'm sorry, but your issue seems unrelated to the changes discussed here - can you try reading the `LOCALSTACK_HOSTNAME` environment variable in our Lambda handler and then use `http://$LOCALSTACK_HOSTNAME:4566/000000000000/test-queue` as the queue URL? Thanks

**Comment by westhechiang** [comment]
Great work, I'm on latest but I'm seeing that Elasticsearch is being started on port `4571`. I DO see that every other services I am using is using port `4566`.
![image](https://user-images.githubusercontent.com/7388796/93393857-143ace80-f828-11ea-904e-251f2a092e28.png)
![image](https://user-images.githubusercontent.com/7388796/93393933-37fe1480-f828-11ea-906d-c424665459c6.png)

**Comment by sdasari404** [comment]
> @sdasari404 I'm sorry, but your issue seems unrelated to the changes discussed here - can you try reading the `LOCALSTACK_HOSTNAME` environment variable in our Lambda handler and then use `http://$LOCALSTACK_HOSTNAME:4566/000000000000/test-queue` as the queue URL? Thanks

Thank you very much the reply @whummer, appreciate your help. 
I have tried setting the `LOCALSTACK_HOSTNAME` as suggested, but to no avail. I'll raise a seperate issue as this is not related to the current thread.

**Comment by rustybrooks** [comment]
I'm using the localstack-client library, and it still seems to want to be contacting the invididual old ports - is there a release coming for that?  The last release seems to be late august.

**Comment by Awarua-** [comment]
@rustybrooks you need to specify USE_LEGACY_PORTS=false in your environment for it to work

**Comment by rustybrooks** [comment]
@awarua- looks like that works, thanks.

**Comment by n7st** [comment]
Looks like the [documentation on Dockerhub](https://hub.docker.com/r/localstack/localstack) needs updating - it'll be incorrect for anyone pulling `latest`.

**Comment by wperron** [comment]
I reverted back to `0.11.5` but I'm still intermittently getting `OSError: [Errno 98]  Address in use` -- am I the only one getting this error?

**Comment by whummer** [comment]
Thanks for the pointer @n7st - the documentation on Docker Hub has been updated now. Please let us know if anything is missing.

@wperron not sure if related this issue is related to the recent changes around edge port - can you please share some details about your environment? Thanks

**Comment by wperron** [comment]
I have the following in my docker-compose file:

```yaml
services:
  localstack:
    image: localstack/localstack:0.11.5
    environment:
      - "SERVICES=ssm:4566"
    ports:
      - "4566-4584:4566-4584"
```

And I get the following stack trace every time I run docker-compose up:

```text
localstack_1  | 2020-09-21T18:23:38:INFO:localstack.utils.server.http2_server: Error running server event loop on port 4566: [Errno 98] Address in use Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/localstack/utils/server/http2_server.py", line 132, in run_app_sync
localstack_1  |     return loop.run_until_complete(serve(app, config, **run_kwargs))
localstack_1  |   File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
localstack_1  |     return future.result()
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/hypercorn/asyncio/__init__.py", line 39, in serve
localstack_1  |     await worker_serve(app, config, shutdown_trigger=shutdown_trigger)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/hypercorn/asyncio/run.py", line 69, in worker_serve
localstack_1  |     sockets = config.create_sockets()
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/hypercorn/config.py", line 166, in create_sockets
localstack_1  |     insecure_sockets = self._create_sockets(self.bind)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/hypercorn/config.py", line 214, in _create_sockets
localstack_1  |     sock.bind(binding)
localstack_1  | OSError: [Errno 98] Address in use
```

But I guess more importantly is I get a 400 error with an empty body when my code calls the GetParameter function

**Comment by wperron** [comment]
I removed the port number from the `SERVICES` variable and now it _seems_ to be cooperating, but honestly my confidence in this "fix" is very thin.

**Comment by joselitofilho** [comment]
I've got the same problem and I rolled back the Docker image `localstack:localstack` to version [1.1.0](https://hub.docker.com/layers/localstack/localstack/1.1.0/images/sha256-3d467ef33c2ec6309319a0af0c295c35cdf36a46f8e982d08f186824d67f2875?context=explore)  and it worked.

I'm doing that on github actions.
