### ISSUE TITLE
unexpected behaviour when step-function catches an error but not use "Catch" mechanism

### ISSUE THREAD

**Issue by elish214** [localstack/localstack#2984]
# Type of request: This is a ...
[X ] bug report
[ ] feature request

# Detailed description
we have "Unrecoverable Error" task in our step-function that suppose to update job_id's state to "FAILED" in case the step-function catches specific errors:

```
"Unrecoverable Error": {
                  "Type": "Task",
                  "Resource": "arn:aws:states:::dynamodb:updateItem",
                  "Parameters": {
                    "TableName": "${SomeTableName}",
                    "Key": {
                      "jobId": {"S.$": "$.jobId"}
                    },
                    "UpdateExpression": "SET #s = :s, #e = :e",
                    "ExpressionAttributeNames": {
                      "#s": "state",
                      "#e": "error"
                    },
                    "ExpressionAttributeValues": {
                      ":s": "FAILED",
                      ":e": {"S.$": "$.error.Cause"}
                    }
                  },
                  "ResultPath": "$.DynamoDB",
                  "End": true
                }
```

we have some steps that leads to this sate, such as:

```
"some step": {
                  "Type": "Task",
                  "Resource": "${SomeLambdaArn}",
                  "Next": "another step",
                  "Catch": [
                    {
                      "ErrorEquals": [
                        "UnrecoverableException",
                        "Lambda.Unknown",
                        "ValueError"
                      ],
                      "ResultPath": "$.error",
                      "Next": "Unrecoverable Error"
                    }
                  ]
                }
```

**it works fine in AWS console**, but when running it with localstack locally, the step function raises an error (we see it in the docker logs) but it doesn't catch it and move it to the "Unrecoverable Error" Task. we see it both in the table, using "dynamodb scan --table-name", and using our api lambda that gets a job_id's state from the dynamo table.

## Expected behavior
when ["UnrecoverableException", "Lambda.Unknown", "ValueError"] are being raised, we expect the step function to move forward to "Unrecoverable Error" Task and update our job_id's state to be "FAILED".

## Actual behavior
it doesnt move to "Unrecoverable Error" Task and so the job_id's state doesn't change to "FAILED".

# Steps to reproduce
create a step function with "Catch" mechanism for the steps. 
raise an exception that should be caught 
and notice that the "Next" step that should be called, isnt being called.
instead, the step function's status is "FAILED".

## Command used to start LocalStack
docker-compose up -d 
(for image: localstack/localstack-light:0.11.4) 

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
```
creating local step function using: 
                "awslocal stepfunctions \
                create-state-machine \
                --definition file://{file_name} \
                --name {step_function_name} \
                --role-arn {IAM_ROLE}"
```

creating dynamo uing: 

```
awslocal dynamodb create-table --cli-input-json file://{file_name}
```

creating lambdas using:

```
                awslocal lambda create-function \
                  --function-name {function_name} \
                  --runtime {runtime} \
                  --timeout {timeout} \
                  --memory-size {memory_size} \
                  --handler {handler} \
                  --role {IAM_ROLE} \
                  --zip-file fileb://{lambdas_zip_path} \
                  --environment Variables="{{{environment_variables}}}" \
```

creating s3 buckets using:

```
awslocal s3api  \
              put-bucket-notification-configuration  \
              --bucket {bucket_name}  \
              --notification-configuration file://{file_name}
```

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-265) by [Unito](https://www.unito.io/learn-more)

**Comment by elish214** [comment]
can anyone help us with this?
thanks :)

**Comment by elish214** [comment]
does anyone can help with it, please?
we still have this issue

**Comment by needanamehelp** [comment]
can you help us in how to exactly reproduce this issue, by sending the exact files you are using.

**Comment by elish214** [comment]
Hi :)
the code is company property so we cant share it.
the code above is very similar to what we have in our code.
every step in our SF has a "Catch" in it in order to update the job's status to "FAILED" in our dynamo table.
in case an exception is caught by the SF, the "Catch" has "Next": "Unrecoverable Error".
where the "Unrecoverable Error" task is:
"Unrecoverable Error": {
                  "Type": "Task",
                  "Resource": "arn:aws:states:::dynamodb:updateItem",
                  "Parameters": {
                    "TableName": "${SomeTableName}",
                    "Key": {
                      "jobId": {"S.$": "$.jobId"}
                    },
                    "UpdateExpression": "SET #s = :s, #e = :e",
                    "ExpressionAttributeNames": {
                      "#s": "state",
                      "#e": "error"
                    },
                    "ExpressionAttributeValues": {
                      ":s": "FAILED",
                      ":e": {"S.$": "$.error.Cause"}
                    }
                  },
                  "ResultPath": "$.DynamoDB",
                  "End": true
                }

it works well for us in AWS- any failure in our SF leads to the "Unrecoverable Error" task and update our dynamo table. 
while in localstack it looks like the "Catch" is completely ignored. we tried to change its "Next" to any lambda and it didnt work either.
https://docs.aws.amazon.com/step-functions/latest/dg/concepts-error-handling.html

thanks! :)

**Comment by elish214** [comment]
any idea whats the problem? :)
thanks

**Comment by elish214** [comment]
anyone? :)

**Comment by elish214** [comment]
hi,
we're pretty stuck in the flow due to this issue.
please let us know if it is a bug to be fix or should we search for an alternative.
thank you :)

**Comment by whummer** [comment]
Thanks for the update @elish214 . 

>  (for image: localstack/localstack-light:0.11.4)

There have been a couple of changes in StepFunctions recently. Can you please pull the `latest` Docker image and confirm if the problem still persists in the latest version? Thanks for your help.

**Comment by whummer** [comment]
Any update on this issue @elish214 ? Can you please pull the `latest` Docker image and confirm if the problem? Thanks

**Comment by elish214** [comment]
hi @whummer  :)
pulling the latest version is too much effort for us currently.
do you have a list of the features and fixes in the latest updates that includes our issue specifically?

we need to have the error catch mechanism in this update.
otherwise, pulling the latest version is a waste of time and effort for us.

thanks :)

**Comment by whummer** [comment]
> pulling the latest version is too much effort for us currently.
> pulling the latest version is a waste of time and effort for us.

That is unfortunate - spending the short amount of time to pull the latest image can often help us tremendously in reproducing issues or verifying whether the issue you're facing is actually fixed. Perhaps you can consider helping us in the future, that would be much appreciated. Thanks

A simple test has been added in #3429 - assuming that the `Catch` behavior should now be supported in the `latest` Docker image. Please report here if the problem persists. Thanks
