### ISSUE TITLE
PRO: ecr put-image-tag-mutability fails

### ISSUE THREAD

**Issue by kevindixon** [localstack/localstack#2985]
# Type of request: This is a ...

[X] bug report
[ ] feature request

# Detailed description
`awslocal ecr put-image-tag-mutability` fails with a 500 every time.

## Expected behavior
Mutability tag is set, or at least doesn't throw an error

## Actual behavior
500 is thrown.

If using `terraform` this also means you can create an ECR repository (which requires the mutability tag), but the tag is not set. Any attempt to re-apply the repository `terraform` will hang - in effect, this makes ECR localstack non-functional in terraform unless you stop localstack between `terraform` runs.

# Steps to reproduce
```
$ awslocal ecr create-repository --repository-name foo
{
    "repository": {
        "repositoryArn": "arn:aws:ecr:us-east-1:000000000000:repository/foo",
        "registryId": "d1b612ae",
        "repositoryName": "foo",
        "repositoryUri": "bd7148d6a2d8:4512/foo"
    }
}
$ awslocal ecr put-image-tag-mutability --repository-name foo --image-tag-mutability MUTABLE

An error occurred (500) when calling the PutImageTagMutability operation (reached max retries: 4): <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
```

## Command used to start LocalStack
`docker compose up`

```
version: '2.1'

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack:0.11.5
    ports:
      - "4566-4620:4566-4620"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=${SERVICES- }
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
      - LOCALSTACK_API_KEY=MYPROKEY
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
See above.

**Comment by kevindixon** [comment]
Any update?

**Comment by whummer** [comment]
Thanks for reporting @kevindixon , and apologies for the long delay. This should be fixed in the meaning - can you please pull the `latest` version of the Docker image and give it another try? Please let us know if the problem persists. Thanks for your help!

**Comment by kevindixon** [comment]
Thanks, all looks good @ `0.12.6`

**Comment by conan19842002** [comment]
I still got error 'An error occurred (400) when calling the CreateRepository operation' with version 0.12.6
