### ISSUE TITLE
ECR repository URI isn't addressable

### ISSUE THREAD

**Issue by kevindixon** [localstack/localstack#2988]
# Type of request: This is a ...

[X] bug report
[ ] feature request

# Detailed description
The documentation at https://app.localstack.cloud/docs#elastic-container-registry--ecr- provides an example as to how to create an ECR repository.
Running this example, the `repositoryUri` created cannot be used for pushing images.

## Expected behavior
`repositoryUri` works for pushing images.

## Actual behavior
The `repositoryUri` returned by `awslocal ecr create-repository` is no longer a `localhost` URI, but uses and ID instead, such as `ec1a420b3959:4513/foo`. You cannot push to this URI - must instead replace the ID with `localhost`.

# Steps to reproduce

## Command used to start LocalStack
`$ docker-compose up`
`docker-compose.yml:`
```
version: '2.1'

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack:0.11.5
    ports:
      - "4510-4520:4510-4520"
      - "4566-4620:4566-4620"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=${SERVICES- }
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY}
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
```
$ awslocal ecr create-repository --repository-name foo
{
    "repository": {
        "repositoryArn": "arn:aws:ecr:us-east-1:000000000000:repository/foo",
        "registryId": "df261d2a",
        "repositoryName": "foo",
        "repositoryUri": "ec1a420b3959:4513/foo"
    }
}
$ docker build -t ec1a420b3959:4513/foo .
$ docker push ec1a420b3959:4513/foo
The push refers to repository [ec1a420b3959:4513/foo]
Get https://ec1a420b3959:4513/v2/: Service Unavailable
```

**Comment by whummer** [comment]
Thanks for reporting @kevindixon . This should be fixed in the `latest` version - can you please pull the latest Docker image and give it another try? Please let us know if the problem persists. Thanks!

**Comment by kevindixon** [comment]
@whummer all works as expected in `0.12.6` - thanks!
