### ISSUE TITLE
Connection refused when connecting SQS in lambda

### ISSUE THREAD

**Issue by dingwenxiao** [localstack/localstack#2993]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

inserting data to Dynamodb triggers lambda, then lambda sends sqs message.
 
the queue does exist, as i did before it triggers lambda.
```
awslocal sqs create-queue --queue-name TestQueue
{
    "QueueUrl": "http://localhost:4576/000000000000/TestQueue"
}
```

Dynamodb triggered lambda successfully, and lambda received the event message.
However,  error happened when getting sqs url:

> Exception in thread "main" com.amazonaws.SdkClientException: Unable to execute HTTP request: Connect to 172.18.0.2:4566 [/172.18.0.2] failed: connect timed out

I tried both 4566 and 4567 ports; both failed with similar error.
## Expected behavior

Sqs receives message.
...

## Actual behavior
Error when connect to sqs. 
...

# Steps to reproduce

## Command used to start LocalStack

SERVICES=sqs,lambda,dynamodb TMPDIR=/private$TMPDIR DEBUG=1 docker-compose up
...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
```
public class Handler implements RequestHandler<DynamodbEvent, String> {
    @Override
    public String handleRequest(final DynamodbEvent dynamodbEvent, final Context context) {
          String response = new String("200 OK");
          String localstackHost = System.getenv("LOCALSTACK_HOSTNAME");
          AmazonSQS amazonSQS = AmazonSQSClientBuilder.standard().withEndpointConfiguration(
                new AwsClientBuilder.EndpointConfiguration("http://" + localstackHost + ":4566",
                        "us-west-2")).build();
            queueUrl = amazonSQS.getQueueUrl("TestQueue").getQueueUrl();// where error happened
            return response;

    }
```
...

**Comment by whummer** [comment]
Thanks for reporting @dingwenxiao . Could be related to #2994 - can you please check if the following comment fixes the problem: https://github.com/localstack/localstack/issues/2875#issuecomment-694113516 Thanks

**Comment by dingwenxiao** [comment]
@whummer  thanks, it fixed the issue.
