### ISSUE TITLE
Using localstack kinesis with AWS SDK

### ISSUE THREAD

**Issue by abhishekjoy1** [localstack/localstack#2997]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

I am using AWS-SDK-JAVA with Localstack Kinesis. I have written the following code snippet:

     ```
      AmazonKinesisClientBuilder clientBuilder = AmazonKinesisClientBuilder.standard();
      clientBuilder.setCredentials(new EnvironmentVariableCredentialsProvider());
      clientBuilder.setEndpointConfiguration(new AwsClientBuilder.EndpointConfiguration(
          "http://localhost:4568",
          Regions.US_WEST_2.getName()));

      AmazonKinesis kinesisClient = clientBuilder.build();

      PutRecordRequest putRecordRequest = new PutRecordRequest();
      putRecordRequest.setStreamName("test");
      putRecordRequest.setData(ByteBuffer.wrap(String.format("testData-%d", 1).getBytes()));
      putRecordRequest.setPartitionKey(String.format("partitionKey-%d", 1));
      kinesisClient.putRecord(putRecordRequest);

   ```

In this context I have also done the following changes:

Added `export AWS_CBOR_DISABLE=true` in .bash_profile

Added following line in ~/.aws/config:

`cborEnabled = false`

## Expected behavior

This should not throw any error, I think.

## Actual behavior

I keep getting the following error in the Java side:

    `Unable to unmarshal exception response with the unmarshallers provided (Service: AmazonKinesis; Status Code: 502; Error Code: null; Request ID: null)`
  ```

And in localstack, I am getting following error:

 ```
2020-09-17T14:44:50:ERROR:localstack.services.generic_proxy: Error forwarding request: 'utf-8' codec can't decode byte 0xbf in position 0: invalid start byte Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 247, in forward
    listener_result = listener.forward_request(method=method,
  File "/opt/code/localstack/localstack/services/kinesis/kinesis_listener.py", line 28, in forward_request
    data = json.loads(to_str(data or '{}'))
  File "/opt/code/localstack/localstack/utils/common.py", line 735, in to_str
    return obj.decode(encoding, errors) if isinstance(obj, six.binary_type) else obj
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbf in position 0: invalid start byte
```


# Steps to reproduce

## Command used to start LocalStack

`localstack start`

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

     ```
      AmazonKinesisClientBuilder clientBuilder = AmazonKinesisClientBuilder.standard();
      clientBuilder.setCredentials(new EnvironmentVariableCredentialsProvider());
      clientBuilder.setEndpointConfiguration(new AwsClientBuilder.EndpointConfiguration(
          "http://localhost:4568",
          Regions.US_WEST_2.getName()));
      AmazonKinesis kinesisClient = clientBuilder.build();

      PutRecordRequest putRecordRequest = new PutRecordRequest();
      putRecordRequest.setStreamName("test");
      putRecordRequest.setData(ByteBuffer.wrap(String.format("testData-%d", 1).getBytes()));
      putRecordRequest.setPartitionKey(String.format("partitionKey-%d", 1));
      kinesisClient.putRecord(putRecordRequest);
```

**Comment by pinzon** [comment]
@abhishekjoy1 I recreated your code using the last version of AWS SDK, and I did get that the same error.
But what I did different was to change the CBOR FLAG to false through System Properties and now it's running smoothly.

This is my code:
```
 package com.mycompany.mavenproject1;

import java.net.URI;
import java.net.URISyntaxException;
import java.nio.ByteBuffer;
import java.nio.charset.Charset;
import java.util.Properties;

import software.amazon.awssdk.auth.credentials.AwsCredentials;
import software.amazon.awssdk.auth.credentials.AwsCredentialsProvider;
import software.amazon.awssdk.auth.credentials.ContainerCredentialsProvider;
import software.amazon.awssdk.auth.credentials.EnvironmentVariableCredentialsProvider;
import software.amazon.awssdk.auth.credentials.SystemPropertyCredentialsProvider;
import software.amazon.awssdk.core.SdkBytes;
import software.amazon.awssdk.regions.Region;
import software.amazon.awssdk.services.codebuild.model.EnvironmentVariable;
import software.amazon.awssdk.services.kinesis.*;
import software.amazon.awssdk.services.kinesis.KinesisBaseClientBuilder;
import software.amazon.awssdk.services.kinesis.KinesisClient;
import software.amazon.awssdk.services.kinesis.KinesisClientBuilder;
import software.amazon.awssdk.services.kinesis.model.PutRecordRequest;
import software.amazon.awssdk.services.kinesis.model.PutRecordRequest.Builder;
import software.amazon.awssdk.core.SdkSystemSetting;

/**
 *
 * @author cristopher
 */
public class QuickStart {
    public static void main(String[] args) {

        KinesisClientBuilder clientBuilder = KinesisClient.builder();
        Properties keys = new Properties(System.getProperties());
        keys.setProperty("aws.accessKeyId", "test");
        keys.setProperty("aws.secretAccessKey", "test");
        
        // DISABLE CBOR
        System.setProperties(keys);
        System.setProperty(SdkSystemSetting.CBOR_ENABLED.property(), "false");
         
        clientBuilder.credentialsProvider(SystemPropertyCredentialsProvider.create());
        try {
            clientBuilder.endpointOverride(new URI("http://localhost:4566"));
            clientBuilder.region(Region.US_WEST_1);
        } catch (URISyntaxException e) {
            // TODO Auto-generater catch block
            e.printStackTrace();
        }
        KinesisClient kinesisClient = clientBuilder.build();
        
        SdkBytes payload = SdkBytes.fromByteBuffer(ByteBuffer.wrap(String.format("testData-%d", 1).getBytes()));
        Builder putRecordRequest = PutRecordRequest.builder();
        putRecordRequest.streamName("test");
        putRecordRequest.data(payload);
        putRecordRequest.partitionKey(String.format("partitionKey-%d", 1));
        
        kinesisClient.putRecord(putRecordRequest.build()); 
    }
}
```

**Comment by whummer** [comment]
Thanks for reporting @abhishekjoy1 . Support for CBOR encoding in Kinesis has been added in #3078 - can you please pull the `latest` Docker image and give it another try? Please report here if the problem persists. Thanks!
