### ISSUE TITLE
Getting error while triggering lambda by SQS

### ISSUE THREAD

**Issue by ashameem123** [localstack/localstack#2998]
This is a ...

[*] bug report

# Detailed description
 Getting error 
when trying to invoke lambda thru SQS.

## Expected behavior
Lambda should trigger on sending a message on SQS
...

## Actual behavior
Getting error " 2020-09-10T16:15:11:DEBUG:localstack.services.awslambda.lambda_api: Unable to poll SQS messages for queue arn:aws:sqs:us-east-1:000000000000:test_queue: An error occurred (AWS.SimpleQueueService.NonExistentQueue) when calling the GetQueueUrl operation: The specified queue does not exist for this wsdl version."

# Steps to reproduce
Created a Lambda Function:
aws lambda create-function --endpoint-url=http://localhost:4574 --function-name samplelambda --runtime java11 --handler lambda.snsEventHandler --zip-file fileb://C:\Workspace\AWSExample\csg-localstack-example\build\libs\lambdademo-1.0.0.jar --role arn:aws:iam::1234567:role/anything --environment Variables="{PROFILE=LOCAL,AWS_REGION=us-east-1}"

Create sqs queue:
aws --endpoint-url=http://localhost:4566 sqs create-queue --queue-name test_queue

Event source mapping:
aws --endpoint-url=http://localhost:4566 lambda create-event-source-mapping --event-source-arn arn:aws:sqs:us-east-1:000000000000:test_queue --function-name samplelambda

Sent a message to the queue:
aws --endpoint-url=http://localhost:4566 sqs send-message --queue-url http://localhost:4566/000000000000/test_queue --message-body “TestMessage!”

whummer

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-267) by [Unito](https://www.unito.io/learn-more)

**Comment by ankitatalgotra123** [comment]
here is the docker yml file used .PFA the 
version: '2.1'

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main3}"
    image: localstack/localstack
    ports:
      - "4566-4599:4566-4599"
      - "${PORT_WEB_UI-8081}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=sqs,dynamodb,s3,sns,lambda
      - DEFAULT_REGION=us-east-1  #temporarily added to test
      #${SERVICES- }
      ##- DEBUG=${DEBUG- }
      - DEBUG=1
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=local           #${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
PFB the SS of error:
![image](https://user-images.githubusercontent.com/49612001/93500774-2a34b600-f932-11ea-8545-29ca63370a4f.png)

**Comment by whummer** [comment]
Thanks for reporting @ashameem123 @ankitatalgotra123 . This certainly looks like a region mismatch issue. Can you please double-check which region is configured in the terminal where you are running the `aws` commands (please print `$AWS_REGION`/`$AWS_DEFAULT_REGION` environment variables, or your AWS profile details). 

Also, please post the output of these commands after creating the SQS queue:
```
aws --endpoint-url=http://localhost:4566 sqs list-queues
aws --endpoint-url=http://localhost:4566 sqs get-queue-attributes --queue-url http://localhost:4566/000000000000/test_queue
```
Thanks

**Comment by ashameem123** [comment]
can be closed. Working as expected
