### ISSUE TITLE
connect ECONNREFUSED 172.18.0.4:4572","errno":"ECONNREFUSED","code":"NetworkingError"

### ISSUE THREAD

**Issue by ameyasalagre** [localstack/localstack#3000]
# Type of request: This is a ...

[X ] bug report
[ ] feature request

# Detailed description
Cant connect to localstack from another cointainer
...

## Expected behavior

...

## Actual behavior

{"error":{"message":"connect ECONNREFUSED 172.18.0.4:4572","errno":"ECONNREFUSED","code":"NetworkingError","syscall":"connect","address":"172.18.0.4","port":4572,"region":"us-east-1","hostname":"localstack","retryable":true,"time":"2020-09-17T19:30:34.392Z"},"level":"error","message":"uncaughtException: connect ECONNREFUSED 172.18.0.4:4572\nError: connect ECONNREFUSED 172.18.0.4:4572\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1129:14)","stack":"Error: connect ECONNREFUSED 172.18.0.4:4572\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1129:14)","exception":true,"date":"Thu Sep 17 2020 19:30:34 GMT+0000 (Coordinated Universal Time)","process":{"pid":142,"uid":1000,"gid":1000,"cwd":"/home/node/app","execPath":"/usr/local/bin/node","version":"v12.13.1","argv":["/usr/local/bin/node","/home/node/app/dist/index.js"],"memoryUsage":{"rss":127279104,"heapTotal":85458944,"heapUsed":60143520,"external":20300343}},"os":{"loadavg":[0.345703125,0.37646484375,0.43505859375],"uptime":7844},"trace":[{"column":14,"file":"net.js","function":"TCPConnectWrap.afterConnect [as oncomplete]","line":1129,"method":"afterConnect [as oncomplete]","native":false}],"timestamp":"2020-09-17T19:30:34.400Z"}

# Steps to reproduce
I have following configuration in my docker-compose.yaml

version: '3.5'

services:
  localstack:
    image: localstack/localstack
    ports:
      - "4567-4593:4567-4593"
      - "8080:8080"
    host: 
      - http://localstack
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "./docker/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

i am using following hostname & port to connect from another cointainer

AWS_ENDPOINT: `http://localstack:4572`

## Command used to start LocalStack

...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

...

**Comment by JDiPierro** [comment]
I started seeing the same thing in CI builds today. Locally it does eventually start up but the latest version seems to be slower starting up than older versions. I've locked our builds to the `0.11.4` tag and they're building successfully again.

**Comment by whummer** [comment]
Thanks for reporting @ameyasalagre @JDiPierro . Can you please take a look at https://github.com/localstack/localstack/issues/2983 and see if that solves your issue? Please note that in the `latest` version, all services are now exposed via the edge service (port `4566`). Thanks

**Comment by ameyasalagre** [comment]
Thanks that solves my issue .
@whummer
