### ISSUE TITLE
KeyError: 'Items' in AWS::ApiGatewayV2::Integration resource (present in Pro Examples)

### ISSUE THREAD

**Issue by m-chandler** [localstack/localstack#3003]
# Type of request: This is a ...

[ X ] bug report
[ ] feature request

# Detailed description
KeyError: 'Items' when deploying localstack-pro example.
I was encountering an issue trying to deploy my own WebSocket API CloudFormation template. Blaming myself, I decided to try your example which deploys via the Serverless framework. Your example exhibits the same issue. It appears as though localstack has issues with deploying the AWS::ApiGatewayV2::Integration CloudFormation resource.

Link to your example:
https://github.com/localstack/localstack-pro-samples/tree/master/serverless-websockets

Logs attached.
## Expected behavior
The example to work as illustrated.

## Actual behavior
An error occurs during the deployment phase. 

# Steps to reproduce
Clone repo: https://github.com/localstack/localstack-pro-samples/tree/master/serverless-websockets
Follow repo instructions:

1. `make install`
2. launch localstack: `LOCALSTACK_API_KEY=... DEBUG=1 SERVICES=serverless localstack start`
3. deploy / test: `make run`

## Command used to start LocalStack
`LOCALSTACK_API_KEY=... DEBUG=1 SERVICES=serverless localstack start`

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
`SLS_DEBUG=1 npm run deploy`

[debug.log](https://github.com/localstack/localstack/files/5243785/debug.log)

**Comment by whummer** [comment]
Thanks for reporting @m-chandler , and apologies for the long delay. This should be fixed in the `latest` version of the Docker image - can you please pull the image and give it another try? Please let me know if the problem persists. Thanks for your help!
