### ISSUE TITLE
Cannot create SQS queue a non zero ReceiveMessageWaitTimeSeconds property via CloudFormation

### ISSUE THREAD

**Issue by m-chandler** [localstack/localstack#3004]
# Type of request: This is a ...

[ X ] bug report
[ ] feature request

# Detailed description
When trying to deploy the following template, an error is received that the "The specified queue already exists.".
Note that I have also tried explicitly setting "QueueName", although this shouldn't be required.

```
{
    "AWSTemplateFormatVersion": "2010-09-09",
    "Description": "Deploys an SQS queue",
    "Resources": {
        "MyQueue": {
            "Type": "AWS::SQS::Queue",
            "Properties": {
                "ReceiveMessageWaitTimeSeconds": 1
            }
        }
    }
}
```

Note that the following template works fine:
```
{
    "AWSTemplateFormatVersion": "2010-09-09",
    "Description": "Deploys an SQS queue",
    "Resources": {
        "MyQueue": {
            "Type": "AWS::SQS::Queue",
            "Properties": {
                "ReceiveMessageWaitTimeSeconds": 0
            }
        }
    }
}
```

When querying the CLI is appears that the SQS queue is created.

I'm only fairly new to localstack, but it would appear that at some point long polling worked? https://github.com/localstack/localstack/issues/2030

Logs are attached.

## Expected behavior
For the cloudformation deployment to succeed.

## Actual behavior
The cloudformation deployment fails

# Steps to reproduce
Start localstack.
Deploy above example CloudFormation template.

## Command used to start LocalStack
docker-compose up

docker-compose.yml:
```
version: '2.1'

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "4571:4571"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=${SERVICES- }
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
      - LOCALSTACK_API_KEY=...
      - DEBUG=1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    tmpfs:
      - /tmp/localstack:exec,mode=600
```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
_after placing the CloudFormation template into sqs-example.json:_
aws --endpoint-url http://localhost:4566 cloudformation create-stack --stack-name sqs-example --template-body file://sqs-example.json

[debug.log](https://github.com/localstack/localstack/files/5243967/debug.log)

**Comment by whummer** [comment]
Thanks for reporting @m-chandler . Looks like this should be fixed in the meantime - a small integration test has been added in #3066. Can you please pull the `latest` Docker image and give it another try? Thanks

**Comment by m-chandler** [comment]
Hi @whummer yes this seems to be fixed. I'll close the issue.
Thank you
