### ISSUE TITLE
[Cognito IDP] admin-set-password doesn't set password

### ISSUE THREAD

**Issue by soulshake** [localstack/localstack#3006]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

The `cognito-idp admin-set-user-password` command does not change the user's password.

## Expected behavior

`cognito-idp admin-set-user-password` should result in the user being able to log in with the new password and the old password should no longer work.

## Actual behavior

`cognito-idp admin-set-user-password` does not allow the user to log in with the new password, and the old password continues to work.

# Steps to reproduce

## Command used to start LocalStack

`docker-compose up`

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

```
1d8075c50b88:/terraform# export PASSWORD=password
1d8075c50b88:/terraform# export NEW_PASSWORD=Password
```

`admin-initiate-auth` with the old password works:

```
1d8075c50b88:/terraform# awslocal cognito-idp admin-initiate-auth --user-pool-id "$POOL_ID" --client-id "$CLIENT_ID" --auth-flow ADMIN_USER_PASSWORD_AUTH --auth-parameters "USERNAME=$USERNAME,PASSWORD=$PASSWORD,SECRET_HASH=$secret_hash"
{
    "AuthenticationResult": {
        "AccessToken": "...",
        "ExpiresIn": 86400,
        "TokenType": "Bearer",
        "RefreshToken": "7ae55da1",
        "IdToken": "..."
    }
}
```

The action of setting a new password appears to succeed:

```
1d8075c50b88:/terraform# awslocal cognito-idp admin-set-user-password --user-pool-id "$POOL_ID" --username "$USERNAME" --password "$NEW_PASSWORD" --permanent
1d8075c50b88:/terraform# echo $?
0
```

But trying to initiate auth with the new password fails:

```
1d8075c50b88:/terraform# awslocal cognito-idp admin-initiate-auth --user-pool-id "$POOL_ID" --client-id "$CLIENT_ID" --auth-flow ADMIN_USER_PASSWORD_AUTH --auth-parameters "USERNAME=$USERNAME,PASSWORD=$NEW_PASSWORD,SECRET_HASH=$secret_hash"

An error occurred (400) when calling the AdminInitiateAuth operation: Invalid password specified
```

Whereas the old password still works:

```
1d8075c50b88:/terraform# awslocal cognito-idp admin-initiate-auth --user-pool-id "$POOL_ID" --client-id "$CLIENT_ID" --auth-flow ADMIN_USER_PASSWORD_AUTH --auth-parameters "USERNAME=$USERNAME,PASSWORD=$PASSWORD,SECRET_HASH=$secret_hash"
{
    "AuthenticationResult": {
        "AccessToken": "...",
        "ExpiresIn": 86400,
        "TokenType": "Bearer",
        "RefreshToken": "327ca73b",
        "IdToken": "..."
    }
}
```

**Comment by soulshake** [comment]
P.S. It seems that `change-password` also doesn't work (same behavior as `admin-set-password` -- 0 exit code, password remains unchanged.

**Comment by whummer** [comment]
Hi @soulshake - a couple of enhancements for Cognito have been pushed recently. According to our tests, the behavior described here should be working with the `latest` version. Can you please pull the latest Docker image and give it another try? Many thanks for your support.

**Comment by soulshake** [comment]
I think this can be resolved :+1: Many thanks!
