### ISSUE TITLE
SQS message not deleted when lambda has been successfully invoked

### ISSUE THREAD

**Issue by matthall88** [localstack/localstack#3007]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description
Lambda invoked successfully via SQS event, but then message is not deleted from queue and lambda keeps re-invoking

Same as issue #2536 (closed but the submitter confirmed still occurring)
...

## Expected behavior
lambda invoked, message deleted from queue
...

## Actual behavior

```
WARNING:bootstrap.py: Thread run method <function LambdaExecutor.execute.<locals>.do_execute at 0x7f5a3cc98f70>(None) failed: An error occurred (ReceiptHandleIsInvalid) when calling the DeleteMessageBatch operation: The input receipt handle is invalid. Traceback (most recent call last):
  File "/opt/code/localstack/localstack/utils/bootstrap.py", line 533, in run
    result = self.func(self.params)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 159, in do_execute
    return _run(func_arn=func_arn)
  File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 146, in wrapped
    raise e
  File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 142, in wrapped
    result = func(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 155, in _run
    callback and callback(result, func_arn, event, error=raised_error, dlq_sent=dlq_sent)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 373, in delete_messages
    sqs_client.delete_message_batch(QueueUrl=queue_url, Entries=entries)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 337, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 656, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ReceiptHandleIsInvalid: An error occurred (ReceiptHandleIsInvalid) when calling the DeleteMessageBatch operation: The input receipt handle is invalid.
```
...

# Steps to reproduce

## Command used to start LocalStack
```
pip install localstack
localstack start
```
...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
create queue
create lambda
create second lambda
create event source mapping queue to second lambda
awslocal lambda invoke first lambda
post to queue via node API (from within first lambda)
The subscribed lambda is triggered and executes successfully, but the message is not deleted and then the lambda re-invokes repeatedly
...

**Comment by whummer** [comment]
LGTM, thanks (we still need to coordinate with the user to try and reproduce issue #3011, though).

**Comment by whummer** [comment]
Thanks for reporting @matthall88 . We haven't been able to reproduce this issue so far (a simple test extension has been added in #3011 to assert the functionality). Can you please share a small, isolated scenario (e.g., small project in a separate Github repo) to help reproduce this issue? That would be much appreciated, thanks

**Comment by matthall88** [comment]
Hi @whummer, I think I solved it - my lambda was using middy middleware and returning an unawaited promise from the original handler - this worked in AWS no bother, but changing the return from the original handler to 'return await Promise.resolve('success'); seems to have solved the issue :) closing.

**Comment by kyle-seesaw** [comment]
I also encountered this error.   In my case, the root cause turned out to be the fact that the VisibilityTimeout for the SQS queue was shorter than the execution timeout for the Lambda that was reading from it.   I believe the visibility timeout was expiring while the message's batch was still be processed, the message was being made visible to consumers again (potentially resulting in redelivery), and then when the Lambda completed processing and attempted to delete the batch it generated this error, probably because SQS no longer. considered the message in-flight to the original consumer.

The solution was to align the SQS visibility timeout on the queue with the Lambda execution timeout, so the message was guaranteed not to be scheduled for delivery prior to a timeout.
