### ISSUE TITLE
SES Java SDKv2 TemplatesMetadata CreatedTimestamp fails to parse

### ISSUE THREAD

**Issue by akaisuicchi** [localstack/localstack#3009]
# Type of request: This is a ...
[x] bug report
[ ] feature request

# Detailed description
SES template list returns a different format for CreatedTimestamp compared with the Java SDK (2.14.19)

```bash
software.amazon.awssdk.core.exception.SdkClientException: Unable to execute HTTP request: Text '2020-09-19 00:53:47.289893' could not be parsed at index 10
```

I also happening in `0.11.4` `0.11.5`

## Expected behavior
Returned CreatedTimestamp is one of the formats the sdk expects

## Actual behavior
Returned CreatedTimestamp is not well parsed. Fractional seconds might be needed

# Steps to reproduce
## Command used to start LocalStack
`docker run --rm -p 4566:4566 -e SERVICES=ses -e DEFAULT_REGION=us-east-1 localstack/localstack:latest`

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
command
`aws --profile localstack --endpoint-url=http://localhost:4566 ses create-template --cli-auto-prompt`
input
`--template: TemplateName=hell-world,SubjectPart=subject,TextPart=hello\nworld,HtmlPart=hello<br/>world`

```kotlin
fun listTemplates(): List<String> {
        val listTemplateRequest = ListTemplatesRequest
                .builder()
                .build()
        return this.syncClient.listTemplates(listTemplateRequest).templatesMetadata().map { list -> list.name() }
    }
```

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-268) by [Unito](https://www.unito.io/learn-more)

**Comment by whummer** [comment]
Thanks for reporting @akaisuicchi . This should be fixed in #3457 - can you please pull the `latest` Docker image and give it another try? Please report here if the problem persists. Thanks
