### ISSUE TITLE
SQS: FIFO queue to DLQ locks origin queue

### ISSUE THREAD

**Issue by chrisivens** [localstack/localstack#3013]
# Type of request: This is a ...
[x] bug report
[ ] feature request

# Detailed description
When a message moves from a FIFO queue to a dead letter queue, it locks the originating queue

## Expected behavior
Once a message is moved from a queue to the dead letter queue, the messages following it should be available to the consumers. The act of moving the message should behave equivalent to deleting a message

## Actual behavior
The virtual queue for the message group is locked until all messages are purged.

# Steps to reproduce
Have a FIFO queue with a redrive policy set. Read a message enough times for it to trigger a move to the DLQ. Attempt to read a second message from the same message group.

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-269) by [Unito](https://www.unito.io/learn-more)

**Comment by needanamehelp** [comment]
I have been trying to reproduce the issue, I think I have been unable to do so, I am doing the following:
1. created DLQ and FIFO queue
2. sent messages to FIFO queue, and read them enough times to get sent to DLQ
3. sent new messages to FIFO queue
I am able to read new messages in the FIFO queue

**Comment by chrisivens** [comment]
Hmm, I'll retest. I may have been on an older docker image. I was having this consistently happen.

**Comment by usmangani1** [comment]
@chrisivens,  Did you get any chance to reproduce this on the latest image ?

**Comment by irahulranjan** [comment]
will be resolved with the release of https://github.com/spulec/moto/pull/3537

**Comment by whummer** [comment]
Thanks for reporting @chrisivens @chrisivens . This should be fixed in the meantime - can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists. Thanks

**Comment by chrisivens** [comment]
I’ll take a look as soon as I get back in the office. Thanks for looking in to this. I’ve been crazy, busy lately so I didn’t get chance to verify things earlier when asked. My apologies.
