### ISSUE TITLE
SQS list queues returns empty response

### ISSUE THREAD

**Issue by manjula-chikkanagappa** [localstack/localstack#3016]
# Type of request: This is a ...

[ yes] bug report
[ ] feature request

# Detailed description

...Localstack SQS list queue command returns empty response. This used to work well in older versions of localstack.

**Command:**
(venv)$ aws --endpoint-url=http://localhost:4566 sqs list-queues --region=us-east-1
(venv)$ 

I am expecting a behavior similar to SNS

(venv) $ aws --endpoint-url=http://localhost:4566 sns list-topics --region=us-east-1
{
    "Topics": []
}

## Expected behavior
.Localstack SQS list queue command return empty array/list.
...

## Actual behavior
Localstack SQS list queue command returns empty response.
...

# Steps to reproduce

## Command used to start LocalStack
SERVICES=sqs,sns localstack start
...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
(venv)$ aws --endpoint-url=http://localhost:4566 sqs list-queues --region=us-east-1
...

**Comment by macnev2013** [comment]
Hey @manjula-chikkanagappa , Thanks for reporting.
This is the expected behaviour in AWS.
`list-queues` API should return `200 status` code with `empty body.`
`list-topics` API should return `200 status` code with `empty array of topics`.

**Comment by usmangani1** [comment]
@manjula-chikkanagappa  as @macnev2013 described this is how the aws behaves as well
Attached the responses of the commands.

```

$ aws sqs list-queues 
$ aws sns list-topics --region us-west-1
{
    "Topics": []
}

```
Please let us know in case if you need help with something else here.Thanks
