### ISSUE TITLE
Can't start localstack in Windows 10

### ISSUE THREAD

**Issue by jamespottsSAFC** [localstack/localstack#3017]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

LocalStack version: 0.11.5

When I start localstack I get an error saying: "Unable to list Docker containers via "docker ps --format '{{.Names}}'": environment can only contain strings".

This is the console output when running DEBUG=1 localstack start:

![image](https://user-images.githubusercontent.com/11425738/93789502-d5db5000-fc29-11ea-9edf-0c5e269dce64.png)

Pastebin link of console output: https://pastebin.pl/view/0edd54f8

I am running these commands in Git Bash.

## Expected behavior

LocalStack to start

## Actual behavior

LocalStack throws an error when attempting to list Docker containers

# Steps to reproduce

Install Docker Desktop on Windows 10
Install localstack on Windows 10
Run: localstack start

## Command used to start LocalStack

localstack start

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

N/A

**Comment by whummer** [comment]
Thanks for reporting @jamespottsSAFC . Can you please try upgrading the pip packages to the latest version:
```
pip install --upgrade --no-cache localstack localstack-client
```
Also, please upgrade your Python version to 3.x, as 2.7 is not supported anymore. Thanks

**Comment by jamespottsSAFC** [comment]
@whummer Yeah it looks like it was running it with Python 2.7 instead of 3 for some reason. I just uninstalled v2.7 so that it would use v3 and it has managed to start now.
