### ISSUE TITLE
PRO: With latest docker image pull, nothing is working except bucket creation

### ISSUE THREAD

**Issue by ashameem123** [localstack/localstack#3019]
# Type of request: This is a ...

[ ] bug report

# Detailed description
LocalStack version: 0.11.5

With the latest docker pull, unable to create function, SNS topic or SQS etc. Only create bucket operation is working.
...

## Expected behavior
should be able to create Function, topic, queues etc

...

## Actual behavior
getting error "Connection was closed before we received a valid response from endpoint URL: "http://localhost:4576/".

# Steps to reproduce

After running - docker pull localstack/localstack

## Command used to start LocalStack --> 
docker-compose up -d

aws sns create-topic --name putnotifications --endpoint-url=http://localhost:4575

aws --endpoint-url=http://localhost:4576 sqs create-queue --queue-name my_sqs

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
provided above

screen shot of the error:
![Localstack_LatestImagePullisBroken](https://user-images.githubusercontent.com/54183749/93915439-a54cf200-fccd-11ea-8e39-689f06cae943.JPG)

![LS_version](https://user-images.githubusercontent.com/54183749/93916633-746dbc80-fccf-11ea-81d9-d800144d2bf0.JPG)

**Comment by whummer** [comment]
Thanks for reporting @ashameem123 . Can you please share the contents of your `docker-compose.yml` configuration file. Please note that the `latest` version of the Docker image uses ONLY port 4566 for all services (see [here](https://github.com/localstack/localstack/issues/2983)). Can you please give it another try with using `--endpoint-url http://localhost:4566` for all `aws` commands above? Thanks

**Comment by ashameem123** [comment]
@whummer -- thanks for your response. 
I tried with 4566  and able to create SNS and SQS but function still throwing the same error. 

![LS_LatestDockerImageIssue](https://user-images.githubusercontent.com/54183749/93928276-ad159200-fcdf-11ea-85ea-937d60ef7f5e.png)

**Comment by whummer** [comment]
Thanks for the update @ashameem123 . Are you seeing any error logs in the container when running the `create-function` command? Can you please try adding the `--debug` flag to the `aws` command, and post the logs here? Thanks

**Comment by ashameem123** [comment]
@whummer , After running command -->
aws lambda create-function --endpoint-url=http://localhost:4566 --function-name SQSdemo --runtime java11 --handler com.aws.lamda.SQSdemo --zip-file fileb://C:
/AWS/Localstack/aws-lambda-example/target/aws-labmda-example-1.0-SNAPSHOT.jar --role arn:aws:iam::1234567:role/anything --environment Variables="{PROFILE=LOCAL,AWS_REGION=us-east-1}" -
-debug

logs were generated (LS_logs.docx), I guess this time function was created but the lambda isn't triggered with SNS event (attaching both logs and docker error )
[LS_logs.docx](https://github.com/localstack/localstack/files/5263746/LS_logs.docx)

[docker_logs.docx](https://github.com/localstack/localstack/files/5263757/docker_logs.docx)

I am stuck at SNS to Lambda step for quite a while now, please help me to get through this so i can test my actual services.

**Comment by whummer** [comment]
Thanks. I'm seeing this in the logs:

<img width="1019" alt="image" src="https://user-images.githubusercontent.com/2807888/93933155-87a97800-fd21-11ea-8fae-36f99cbae805.png">

Can you please try adding `cloudwatch` to the `SERVICES` environment variable? (We'll push a fix shortly to resolve this issue.)

**Comment by ashameem123** [comment]
@whummer - I added "cloudwatch" to the services and no longer getting the above error(but the SNS to Lambda issue exist)
Sounds like your team is working on the fix for "SNS TO LAMBDA trigger" , thanks for looking into it.

![LS_Sns2Lambda_Error](https://user-images.githubusercontent.com/54183749/93934745-38dfec00-fce9-11ea-90ef-22704d984637.JPG)


We can close this ticket.
