### ISSUE TITLE
PRO: Latest LS image pull shows edge port as 443?

### ISSUE THREAD

**Issue by ashameem123** [localstack/localstack#3020]
# Type of request: This is a ...
question

# Detailed description
with Localstack latest docker image pull, the edge port for the services is now showing as 443. Is that a new change introduced with version- 0.11.5

![LS_EdgePortChanged](https://user-images.githubusercontent.com/54183749/93921080-ac77fe00-fcd5-11ea-8e76-ccf80c0a178a.JPG)

**Comment by whummer** [comment]
Thanks for reporting @ashameem123 . I'm assuming you're using the Pro version - the edge service should be available on both - port `4566` and port `443`. We'll fix the log output to print the "correct" port (`4566`) instead. Please make sure to expose port `4566` for the Docker container - if the edge service is not available on that port, then please let us know. Thanks
