### ISSUE TITLE
listObjects does not Work with phpsdk

### ISSUE THREAD

**Issue by slider1337** [localstack/localstack#3021]
# Type of request: This is a ...
[x] bug report
[ ] feature request

# Detailed description
If I upload objects to my bucket I don't get a list of my objects back, using the listObjects method of the phpsdk.
I've reported this behaviour already in  #2535. For me this issue is not solved. I have to downgrade to localstack 0.11.0 to make it work.

## Expected behavior
listObjects should return the objects in my bucket/folder.

## Actual behavior
Only metadata is returned.

# Steps to reproduce

- docker-compose.yml

```
version: '3.7'

services:
  localstack:
    #image: localstack/localstack:0.11.0
    image: localstack/localstack:latest
    ports:
      - "4567-4584:4567-4584"
      - "8080:8080"
    environment:
      - SERVICES=s3
      - DATA_DIR=/tmp/localstack-test/data
      - DEBUG=1
      - USE_LIGHT_IMAGE=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEFAULT_REGION=eu-central-1
    volumes:
      - "${TMPDIR:-/tmp/localstack-test}:/tmp/localstack-test"
```
- test.php

```
<?php
require 'vendor/aws-autoload.php';

use Aws\S3\S3Client;

$config = [
	'credentials' => [
		'key'    => 'test-id',
		'secret' => 'test-secret',
	],
	'region' => 'eu-central-1',
	'version' => 'latest',
	'endpoint' => 'http://localhost:4572',
	'use_path_style_endpoint' => true,
];
$s3client = new S3Client($config);
$buckets = $s3client->listBuckets();
if (empty($buckets['Buckets'])) {
	$s3client->createBucket([
		'Bucket' => 'test',
	]);
	echo 'Bucket test created' . PHP_EOL;
} else {
	echo 'Bucket test exists' . PHP_EOL;
}

$s3client->upload('test', 'test.txt', 'test');
var_dump($s3client->listObjectsV2(['Bucket' => 'test']));
```
## Expected example (works with localstack:0.11.0)
```
> php test.php
Bucket test exists

class Aws\Result#245 (2) {
  private $data =>
  array(7) {
    'IsTruncated' =>
    bool(false)
    'Contents' =>
    array(1) {
      [0] =>
      array(5) {
        ...
      }
    }
    'Name' =>
    string(4) "test"
    'Prefix' =>
    string(0) ""
    'MaxKeys' =>
    int(1000)
    'KeyCount' =>
    int(1)
    '@metadata' =>
    array(4) {
      'statusCode' =>
      int(200)
      'effectiveUri' =>
      string(38) "http://localhost:4572/test?list-type=2"
      'headers' =>
      array(9) {
        ...
      }
      'transferStats' =>
      array(1) {
        ...
      }
    }
  }
  private $monitoringEvents =>
  array(0) {
  }
}
```
## Actual (with localstack:latest)
```
> php test.php
Bucket test exists

class Aws\Result#245 (2) {
  private $data =>
  array(1) {
    '@metadata' =>
    array(4) {
      'statusCode' =>
      int(200)
      'effectiveUri' =>
      string(38) "http://localhost:4572/test?list-type=2"
      'headers' =>
      array(16) {
        ...
      }
      'transferStats' =>
      array(1) {
        ...
      }
    }
  }
  private $monitoringEvents =>
  array(0) {
  }
}
```
Data is missing, so it seems, that there are no objects in the bucket.

**Comment by whummer** [comment]
Thanks for reporting @slider1337 . Please note that the `latest` Docker image uses a single entry point (edge port `4566`) only for all services (see #2983 ). Can you please give it another try after exposing port 4566 in your docker-compose configuration? Thanks

**Comment by slider1337** [comment]
I just tried with one port:

- docker-compose.yml
```
version: '3.7'

services:
  localstack:
    #image: localstack/localstack:0.11.0
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DATA_DIR=/tmp/localstack-test/data
      - DEBUG=1
      - USE_LIGHT_IMAGE=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEFAULT_REGION=eu-central-1
    volumes:
      - "${TMPDIR:-/tmp/localstack-test}:/tmp/localstack-test"
```
It has the same result:
```
> php test.php
Bucket test exists

class Aws\Result#245 (2) {
  private $data =>
  array(1) {
    '@metadata' =>
    array(4) {
      'statusCode' =>
      int(200)
      'effectiveUri' =>
      string(38) "http://localhost:4566/test?list-type=2"
      'headers' =>
      array(16) {
        ...
      }
      'transferStats' =>
      array(1) {
        ...
      }
    }
  }
  private $monitoringEvents =>
  array(0) {
  }
}
```

**Comment by simonbowen** [comment]
Jumping on this because I have the issues. I have isolated the problem which is explained in [this gist here](https://gist.github.com/simonbowen/1944c2f0da9d5398d076ddd8f01f361d). 

For some reason the Guzzle Stream response returns 0 when calling getSize.

**Comment by needanamehelp** [comment]
I created and listed the bucket with the script that you posted above, I think I am getting the desired result:

`Bucket test exists
object(Aws\Result)#235 (2) {
  ["data":"Aws\Result":private]=>
  array(7) {
    ["IsTruncated"]=>
    bool(false)
    ["Contents"]=>
    array(1) {
      [0]=>
      array(5) {
        ["Key"]=>
        string(8) "test.txt"
        ["LastModified"]=>
        object(Aws\Api\DateTimeResult)#247 (3) {
          ["date"]=>
          string(26) "2020-10-02 16:48:44.000000"
          ["timezone_type"]=>
          int(2)
          ["timezone"]=>
          string(1) "Z"
        }
        ["ETag"]=>
        string(34) ""098f6bcd4621d373cade4e832627b4f6""
        ["Size"]=>
        string(1) "4"
        ["StorageClass"]=>
        string(8) "STANDARD"
      }
    }
    ["Name"]=>
    string(4) "test"
    ["Prefix"]=>
    string(0) ""
    ["MaxKeys"]=>
    int(1000)
    ["KeyCount"]=>
    int(1)
    ["@metadata"]=>
    array(4) {
      ["statusCode"]=>
      int(200)
      ["effectiveUri"]=>
      string(38) "http://localhost:4566/test?list-type=2"
      ["headers"]=>
      array(16) {
        ["content-type"]=>
        string(30) "application/xml; charset=utf-8"
        ["content-length"]=>
        string(3) "433"
        ["access-control-allow-origin"]=>
        string(1) "*"
        ["last-modified"]=>
        string(29) "Fri, 02 Oct 2020 16:48:44 GMT"
        ["x-amz-request-id"]=>
        string(16) "1CC1D57FD3741A0E"
        ["x-amz-id-2"]=>
        string(64) "MzRISOwyjmnup1CC1D57FD3741A0E7/JypPGXLh0OVFGcJaaO3KW/hRAqKOpIEEp"
        ["accept-ranges"]=>
        string(5) "bytes"
        ["content-language"]=>
        string(5) "en-US"
        ["cache-control"]=>
        string(8) "no-cache"
        ["content-encoding"]=>
        string(8) "identity"
        ["access-control-allow-methods"]=>
        string(38) "HEAD,GET,PUT,POST,DELETE,OPTIONS,PATCH"
        ["access-control-allow-headers"]=>
        string(196) "authorization,content-type,content-md5,cache-control,x-amz-content-sha256,x-amz-date,x-amz-security-token,x-amz-user-agent,x-amz-target,x-amz-acl,x-amz-version-id,x-localstack-target,x-amz-tagging"
        ["access-control-expose-headers"]=>
        string(16) "x-amz-version-id"
        ["date"]=>
        string(29) "Fri, 02 Oct 2020 16:48:44 GMT"
        ["server"]=>
        string(13) "hypercorn-h11"
        ["connection"]=>
        string(5) "close"
      }
      ["transferStats"]=>
      array(1) {
        ["http"]=>
        array(1) {
          [0]=>
          array(0) {
          }
        }
      }
    }
  }
  ["monitoringEvents":"Aws\Result":private]=>
  array(0) {
  }
}`

Can you retry with the latest localstack version, and even if that doesn't work, help us in reproducing the issue.

**Comment by slider1337** [comment]
Works for me too with latest image, thanks for fixing!
