### ISSUE TITLE
Lambdas created do not use the localstack config variable DEFAULT_REGION

### ISSUE THREAD

**Issue by matthall88** [localstack/localstack#3025]
# Type of request: This is a ...
[x] bug report
[ ] feature request

# Detailed description
lambda containers calling out to aws services use region us-east-1 instead of the value provided to localstack as DEFAULT_REGION
...

## Expected behavior
lambda containers honour the default region override provided to top level localstack DEFAULT_REGION 
set the environment variable AWS_DEFAULT_REGION inside the lambda containers for lambci to pick up to be the same value as localstack DEFAULT_REGION
...

## Actual behavior
lambda containers revert to us-east-1
...

# Steps to reproduce
## Command used to start LocalStack
localstack start
...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
curl -v -d '{"variable":"DEFAULT_REGION","value":"eu-west-1"}' 'http://localhost:4566/?_config_'
deploy a lambda function with the following as the handler:

```
const {SQS} = require('aws-sdk');

const main = (event, context) => {
    console.log('aws config', JSON.stringify(SQS.config, null, 2));
}
module.exports = {
  main,
}
```

the region used in the config is showing as us-east-1
...

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-270) by [Unito](https://www.unito.io/learn-more)

**Comment by vincentippon** [comment]
Hello there, is this supposed to be resolved ? I currently have this issue using local LAMBDA_EXECUTOR, should I open a new issue or is it related ?

**Comment by whummer** [comment]
Thanks for reporting @matthall88 @vincentippon - this should be resolved in the meantime, support for multi-region setups has been added in 59294e6 . Please let us know if the problem persists. Thanks!
