### ISSUE TITLE
Feature Request: Add ability to use custom dns server for lambda containers similar to network

### ISSUE THREAD

**Issue by matthall88** [localstack/localstack#3026]
# Type of request: This is a ...

[ ] bug report
[x] feature request

# Detailed description
We can set LAMBDA_DOCKER_NETWORK to add lambda containers to an existing docker network on deployment. 
I think it would be good to be able to also set a LAMBDA_DOCKER_DNS flag to be able to set the dns server for the running lambda container. 
...

**Comment by whummer** [comment]
Added in #3027 - PR will be merged once the tests are fixed. Thanks again!
