### ISSUE TITLE
Option to log at different level (e.g. WARN or ERROR rather than INFO)

### ISSUE THREAD

**Issue by sadams** [localstack/localstack#3038]
# Type of request: This is a ...
[ ] bug report
[x] feature request

It would be nice to prevent INFO level logs being printed. Especially when used with a healthcheck, which runs forever and puts lines in the console every x seconds (see below):

```
localstack           | [2020-09-28 13:10:06 +0000] [21] [INFO] 172.26.0.2 - - [28/Sep/2020 13:10:06] "POST / HTTP/1.1" 200 -
localstack           | [2020-09-28 13:10:07 +0000] [21] [INFO] 172.26.0.2 - - [28/Sep/2020 13:10:07] "POST / HTTP/1.1" 200 -
...
```

## Expected behavior
I can set an env var like `LOG_LEVEL=error` which will change the logging to only output errors (or whatever level i choose).

## Actual behavior
Info level is always logged

# Steps to reproduce
## Command used to start LocalStack
Docker compose (boilerplate except for the healthcheck, which i use to work out when localstack is ready):

```
  localstack:
    container_name: "localstack"
    image: localstack/localstack
    healthcheck:
      test: ["CMD", "bash" ,"-c", "
      awslocal sqs list-queues &&
      awslocal sns list-topics
      "]
      timeout: 4s
      interval: 3s
      retries: 20
    ports:
      - "4566:4566"
      - "4571:4571"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=${SERVICES-sqs,sns}
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
NA

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-272) by [Unito](https://www.unito.io/learn-more)

**Comment by whummer** [comment]
Thanks for reporting @sadams . A new configuration variable `LS_LOG` has been added in #3542 . Hope that helps - please let us know if that doesn't work or if anything is missing. Thanks
