### ISSUE TITLE
AWS API Gateway - Only supports region us-east-1

### ISSUE THREAD

**Issue by triqi** [localstack/localstack#304]
I am unable to use the API Gateway service if I specify any other region other than us-east-1.

## Context

Using locakstack via [docker image](https://hub.docker.com/r/localstack/localstack/)

## Process

1. Start localstack in docker (`docker run -p "4567-4582:4567-4582" localstack/localstack`)
2. List rest apis with aws-cli (`aws --endpoint-url=http://localhost:4567 --region=ap-southeast-2 apigateway get-rest-apis`)
3. Request fails with 500 Internal Server Error

## Expected result

```json
{ 
  "items": []
}
```

## Current result

```html
An error occurred (500) when calling the GetRestApis operation (reached max retries: 4): <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>
```

### Debug output
```
apis = self.backend.list_apis()
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/apigateway/responses.py", line 25, in backendreturn apigateway_backends[self.region]
KeyError: u'ap-southeast-2'
```

## Possible Fix

The region has been hard-coded in `site-packages\moto\apigateway\__init__.py` at line 5.

```python
apigateway_backend = apigateway_backends['us-east-1']
```

**Comment by whummer** [comment]
Thanks for reporting @triqi . LocalStack currently doesn't have multi-region support. Closing this issue, please post any follow-up questions here: https://github.com/localstack/localstack/issues/167 Thanks
