### ISSUE TITLE
Time increasing when multiple processes try to create s3 bucket

### ISSUE THREAD

**Issue by akshatb19** [localstack/localstack#3041]
# Type of request: This is a ...
[x] bug report
[ ] feature request

# Detailed description
We have a single localstack instance, when multiple processes are trying to create s3 bucket, its having performance issues, the time taken to create bucket is increased.

To trigger multiple requests together, given below is a threaded ruby code, which hits localstack in parallel.
When command: `ruby aws.rb 1 1` is ran for single thread and single bucket, time is about 40ms. Whereas for multiple threads and multiple buckets, let's say 8 threads and 20 buckets for each thread, `ruby aws.rb 8 20`, the time is around 200ms for each.
...

## Expected behavior
Time should not increase with multiple hits in parallel
...

## Actual behavior
Time is increasing proportionally with the number of parallel processes.
...

# Steps to reproduce
Run the below code with different values of VAL_1 and VAL2

## Command used to start LocalStack
localstack start
...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
https://gist.github.com/akshatb19/0355291e60c6d15e3ee1e35537c99959
...

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-273) by [Unito](https://www.unito.io/learn-more)

**Comment by whummer** [comment]
Possibly related to #3071

**Comment by macnev2013** [comment]
Closing as a related issue #3071 . Please reopen this if the problem still persists.
