### ISSUE TITLE
PRO: Localstack dashboard and Docker container are not displaying the latest logs or activity

### ISSUE THREAD

**Issue by ashameem123** [localstack/localstack#3049]
Type of request: This is a ...

[ ] bug report

# Detailed description
LS version - 1.7.1  ?
Docker container is not showing any logs after invoking a lambda function. Not able to understand if the services are working or not. 
The PRO dashboard also is not getting updated and still shows the previously created /running services. 

## Expected behavior
The logs should be generated in LS Docker container and should display the output of the invoked function (ex: a print statement) if triggered successfully. 

The invoke command is giving : 
aws lambda invoke --function-name S3ToLambda outfile.txt --endpoint-url=http://localhost:4566
{
    "StatusCode": 200,
    "LogResult": "",
    "ExecutedVersion": "$LATEST"
}

## Actual behavior
The docker container doesn't display any response. It just shows the LS is available and ready.

# Steps to reproduce

Trying to invoke lambda by S3, steps are:

aws --endpoint-url=http://localhost:4566 s3 mb s3://test-bucket

aws lambda create-function --endpoint-url=http://localhost:4566 --function-name S3ToLambda --runtime java11 --handler lambda.functions.S3ToLambda --zip-file fileb://C:/AWS/Localstack/Localstack/localstackDemoAllServices/build/libs/eCare-localstackDemoAllServices.jar --role arn:aws:iam::1234567:role/anything --environment Variables="{PROFILE=LOCAL,AWS_REGION=us-east-1}"

aws s3api put-bucket-notification-configuration --bucket test-bucket --notification-configuration file://LambdaCongifuration.json --endpoint-url=http://localhost:4566

aws s3 cp color.json s3://test-bucket --endpoint-url=http://localhost:4566

docker-compose file:

version: '2.1'

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack:latest
    ports:
      - "4566-4599:4566-4599"
      - "${PORT_WEB_UI-8081}:${PORT_WEB_UI-8080}"
    environment:
      - LOCALSTACK_API_KEY=12344567
      - SERVICES=${SERVICES- }
      ##- DEBUG=${DEBUG- }
      - DEBUG=1
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=docker
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LAMBDA_DOCKER_NETWORK=localstackdemoallservices_default
      - HOST_TMP_FOLDER=${TMPDIR}
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

![LS_Dashboard issue](https://user-images.githubusercontent.com/54183749/94602428-764cf800-025a-11eb-9bdd-ca9327593ac5.jpg)
![LS_docker screen shot](https://user-images.githubusercontent.com/54183749/94602682-d348ae00-025a-11eb-9be8-7982f9f3fddd.JPG)

**Comment by whummer** [comment]
Many thanks for pointing this out @ashameem123 . We had a little glitch in our API layer, and the event storage was temporarily unavailable for a short period of time. This should be fixed in the meantime - please reach out any time (ideally via mail/Slack) if the problem occurs again. Thanks for your help!
