### ISSUE TITLE
PRO: Getting error on triggering lambda, unable to understand the logs

### ISSUE THREAD

**Issue by ashameem123** [localstack/localstack#3050]
Type of request: This is a ...

[ ] bug report
[ ] feature request

# Detailed description
On running my services on localstack, getting error after invoking lambda. Unable to understand the rootcause.

## Expected behavior
Lambda should trigger fine

## Actual behavior

Getting error 

# Steps to reproduce

- docker-compose up -d
create bucket
create sns 
Subscribe to topic
put bucket notification (s3 and sns)
create lambda function
Subscribe lambda to Topic
create SQS(lambda is feeding sqs)
source map lambda and sqs
upload a file in s3 (to generate an SNS event which should trigger lambda)
## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

[Localstack_error.docx](https://github.com/localstack/localstack/files/5301867/Localstack_error.docx)

**Comment by duongpv7** [comment]
Thanks for reporting @ashameem123 . Can you provide zip/jar version of lambda code to help us reproduce this issue in more detail? Thanks for your help.

**Comment by ashameem123** [comment]
@duongpv7 --Thanks for responding. I cannot provide the jar of the function as this is a live project i am working on. 
Is there a way we can debug it?

**Comment by ashameem123** [comment]
https://github.com/localstack/localstack/issues/2968 fix closed this issue as well.
