### ISSUE TITLE
Lambda SQS event source mapping issue

### ISSUE THREAD

**Issue by recharge-dreams** [localstack/localstack#3051]
# Type of request: This is a ...
[x] bug report
[ ] feature request

# Detailed description
I'm using localstack(0.11.5) for integration testing and these tests have been added as a part of CI/CD pipelines.
I'm facing transient issues and this is making pipelines **_highly_** unstable.
The below issue is very frequently seen.

```
 Unable to poll SQS messages for queue arn:aws:sqs:us-east-1:000000000000:my-first-queue: Unable to parse response (not well-formed (invalid token): line 1, column 0), invalid XML received. Further retries may succeed:

```

Not sure what's really going wrong here and even I don't know if event source mapping is the real cause or if there is any underlying issue.

Full debug log here:

```
Unable to poll SQS messages for queue arn:aws:sqs:us-east-1:000000000000:my-first-queue: Unable to parse response (not well-formed (invalid token): line 1, column 0), invalid XML received. Further retries may succeed:
learning_stack | b'{}'

learning_stack | Thread run method <function AdaptiveThreadPool.submit.<locals>._run at 0x7fccd740aaf0>(None) failed: No mock address: POST http://127.0.0.1:34123/ Traceback (most recent call last):

learning_stack | File "/opt/code/localstack/localstack/utils/bootstrap.py", line 521, in run

learning_stack | result = self.func(self.params)

learning_stack | File "/opt/code/localstack/localstack/utils/async_utils.py", line 28, in _run

learning_stack | return fn(*args, **kwargs)

learning_stack | File "/opt/code/localstack/localstack/services/generic_proxy.py", line 555, in handler

learning_stack | response = modify_and_forward(method=method, path=path_with_params, data_bytes=data, headers=headers,

learning_stack | File "/opt/code/localstack/localstack/services/generic_proxy.py", line 372, in modify_and_forward

learning_stack | response = requests_method(request_url, data=data_to_send,

learning_stack | File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/api.py", line 119, in post

learning_stack | return request('post', url, data=data, json=json, **kwargs)

learning_stack | File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/api.py", line 61, in request

learning_stack | return session.request(method=method, url=url, **kwargs)

learning_stack | File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/sessions.py", line 530, in request

learning_stack | resp = self.send(prep, **send_kwargs)

learning_stack | File "/tmp/localstack/zipfile.3f3142f2/requests_mock/mocker.py", line 131, in _fake_send

learning_stack | return _original_send(session, request, **kwargs)

learning_stack | File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/sessions.py", line 643, in send

learning_stack | r = adapter.send(request, **kwargs)

learning_stack | File "/tmp/localstack/zipfile.3f3142f2/requests_mock/adapter.py", line 258, in send

learning_stack | raise exceptions.NoMockAddress(request)

learning_stack | requests_mock.exceptions.NoMockAddress: No mock address: POST http://127.0.0.1:34123/
```

We are using three lambdas with SQS queues (event source mapping to those lambdas), along with dynamodb(amazon/dynamodb-local for performance reasons), s3 and stepfunctions.

_Sometimes_ the tests are running perfectly fine. And if some error as above occurs, subsequent tests are failing. I'm seeing the above chunk of debug log is infinitely generated (even when running the tests stopped)

I observed that the frequency of these transient issues is much lesser (but not zero, unfortunately) with localstack 0.11.4

## Expected behavior
No issues when running tests

## Actual behavior
Getting the above mentioned error

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
Creating a queue:

```
aws --endpoint-url=http://localhost:4566 sqs create-queue \
  --queue-name='my-first-queue' \
  --attributes '{ "MessageRetentionPeriod":"21600", "VisibilityTimeout":"30", "ReceiveMessageWaitTimeSeconds": "5"}'
```

Creating a lambda 

```
aws --endpoint-url=http://localhost:4566 lambda create-function \
  --function-name test-lambda \
  --runtime python3.7 \
  --timeout 100 \
  --memory-size 256 \
  --handler test_lambda.test_lambda_handler \
  --role arn:aws:iam::000000000000:role/a-role \
  --zip-file fileb://lambda.zip \
  --environment Variables="{DYNAMO_DB_TABLE=my-dynamo-table,ENVIRONMENT=mock,TEST_BUCKET=mock-bucket,LOG_LEVEL=DEBUG}"
```

and I'm having two more lambdas along with step functions, s3 integration...

Creating event source mapping:

```
aws --endpoint-url=http://localhost:4566 lambda create-event-source-mapping \
  --function-name test-lambda \
  --batch-size 1 \
  --event-source-arn arn:aws:sqs:us-east-1:000000000000:my-first-queue
```

docker-compose.yml:

```
version: '3.3'

services:
  localstack:
    container_name: first_stack
    image: localstack/localstack:0.11.5
    ports:
      - "4566:4566"
    environment:
      - SERVICES=lambda,sqs,stepfunctions,s3
      - DEBUG=1
      - LAMBDA_EXECUTOR=local  # This is giving us max performance when compared to docker-reuse
      - DOCKER_HOST=unix:///var/run/docker.sock

      - LAMBDA_REMOTE_DOCKER=false 
      - LOCALSTACK_HOSTNAME=localhost
      - LAMBDA_REMOVE_CONTAINERS=false
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  dynamo_local:
    image: amazon/dynamodb-local:latest
    container_name: mock.database
    ports:
      - "8000:8000"
    command: -jar -Xmx512m -Xms256m DynamoDBLocal.jar -inMemory -sharedDb
```

My test suite contains around 65 tests and altogether they will make 427 lambda calls (only to 1/3 lambdas I'm having, rest two lambdas will get invoked from sqs mappings, and it would be around 100 invocations).

**Configuration:**
OS: Mac OS X (Catalina 10.15.7)
RAM: 16GB
Processor: 2.6 GHz 6-Core Intel Core i7
Docker: 2.3.0.5
Docker Engine: 19.03.12

**Code and test dependencies:**

```
boto3==1.14.61
botocore==1.17.61
simplejson
requests==2.23.0
aiohttp
requests_mock
mock
pytest
awscli==1.18.138
```

Assuming all the tests run successfully, the total duration for this is around 55-60 seconds maximum.
Could you please let us know if localstack is capable of handling this load?
[Addressing this PR would be highly helpful #2483 ]

Seriously these intermittent issues are driving me crazy, and I've been trying to fix them since 3 weeks.
Any help/suggestions is/are greatly appreciated.
Thanks in advance!

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-274) by [Unito](https://www.unito.io/learn-more)

**Comment by whummer** [comment]
Thanks for reporting @recharge-dreams . Looks like your Lambda is using a library `requests_mock` which seems to be raising an error. Any chance you can share a minimal version of your `lambda.zip` archive to help us reproduce this issue more easily? Many thanks for your help.

**Comment by recharge-dreams** [comment]
Thanks for the response @whummer. I cannot share you the zip due to our security policies. :(

**Comment by whummer** [comment]
Thanks for the update @recharge-dreams . My assumption would be that something is wrong with the logic in your Lambda handler itself --
```
learning_stack | r = adapter.send(request, **kwargs)
learning_stack | File "/tmp/localstack/zipfile.3f3142f2/requests_mock/adapter.py", line 258, in send
learning_stack | raise exceptions.NoMockAddress(request)
learning_stack | requests_mock.exceptions.NoMockAddress: No mock address: POST http://127.0.0.1:34123/
```

I didn't mean to ask you to publish the _entire_ Lambda archive (we certainly don't want you to publish any confidential business logic). However, it would be great if you can try to construct a _minimal_ working example (with only test data and non-production code) to help reproduce the issue. We'll be very happy to look into it, but I'm afraid it will be hard if there is no way for us to reproduce the issue. Thanks for your help.
