### ISSUE TITLE
Tag latest docker image with version also

### ISSUE THREAD

**Issue by PauliusLe** [localstack/localstack#3054]
It is impossible to lock to a version which is latest now. Solution would be to multi tag new images with latest and version tags.

**Comment by whummer** [comment]
Thanks for reporting @PauliusLe . We have just released a new version, and we will make sure to push tagged releases more frequently in the future.

> Solution would be to multi tag new images with latest and version tags.

Not sure if this would really be a solution - we want version tags to be stable, point-in-time, immutable releases that should not change over time. One option would be to tag each and every `latest` image with the git commit hash. We believe that - with the currently velocity and frequency of changes - this will become hard to manage, though.

Hence, the solution we're proposing is that release tags will get created much more frequently in the future (e.g., apprx. ~1 tagged release per week). Hope that works for you, please share any other feedback you may have regarding tagging process and release frequency. Thanks

**Comment by PauliusLe** [comment]
@whummer that would work. I was confused by the fact that `latest` tag is not as stable and changes frequently. It could be tagged as `nightly`, so everyone who uses it would be aware that this image is potentially unstable. Just my thoughts.
