### ISSUE TITLE
Latest LocalStack does not print AWS Lambda log when S3 triggers it

### ISSUE THREAD

**Issue by gustavotemple** [localstack/localstack#3065]
# Type of request: This is a ...
* [x] bug report

# Detailed description
Even with DEBUG=1, latest LocalStack does not print AWS Lambda function log when S3 triggers the Lambda

## Expected behavior
Same as tag 0.11.5

```log
localstack_main | > START RequestId: Version:
localstack_main | > INFO hello world
localstack_main | > END RequestId:
localstack_main | > REPORT RequestId: Init Duration: ms Duration: ms Billed Duration: ms Memory Size: MB Max Memory Used: MB

```

## Actual behavior
There is no lambda log: 

```console
docker exec -it localstack_main sh
cd /tmp
cat localstack_infra.log
cat localstack_infra.err
```

# Steps to reproduce
## Command used to start LocalStack
https://github.com/localstack/localstack/blob/master/docker-compose.yml
I tried configure the docker-compose above with:

```yml
- SERVICES=s3, lambda
- DEBUG=1
- LAMBDA_EXECUTOR=docker
- LAMBDA_NETWORK=bridge
```

And then:

```console
sed -i 's:localstack/localstack:localstack/localstack\:latest:g' docker-compose.yml && \
docker-compose down -v --rmi all --remove-orphans && \
docker-compose up
```

I also tried clone the repo and:

```console
make clean && \
make install && \
make infra
```

But with no success.

The tag 0.11.5 works fine:

```console
sed -i 's/localstack\/localstack/localstack\/localstack:0.11.5/g' docker-compose.yml && \
docker-compose down -v --rmi all --remove-orphans && \
docker-compose up
```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
1. Create the S3:

```console
aws --endpoint-url=http://localhost:4566 s3 mb s3://foo
```

1. Add notification configuration:

```console
aws s3api put-bucket-notification-configuration --bucket foo --notification-configuration file://notification.json --endpoint-url http://localhost:4566
```

1. Notification configuration file:

```json
{
    "LambdaFunctionConfigurations": [
        {
            "Events": [
                "s3:ObjectCreated:*"
            ],
            "LambdaFunctionArn": "arn:aws:lambda:us-east-1:000000000000:function:bar"
        }
    ]
}
```

1. Create a simple index.js with a console.log('hello world'):

```javascript
'use strict';
const AWS = require('aws-sdk');
exports.handler = async (event, context, callback) => {
    console.log('hello world');
};
```

1. Create the lambda:

```console
npm install --production && \
zip -r bar.zip . && \
aws lambda create-function --function-name bar --zip-file fileb://bar.zip --handler index.handler --runtime nodejs12.x --timeout 60 --memory-size 512 --role bar --endpoint-url http://localhost:4566
```

1. Trigger the lambda:

```console
aws --endpoint-url=http://localhost:4566 s3 cp notification.json "s3://foo/notification.json"
```

P.S. Same setup works fine with LocalStack 0.11.5

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-276) by [Unito](https://www.unito.io/learn-more)

**Comment by duongpv7** [comment]
Issue already fixed

**Comment by ronyeh-lb** [comment]
@duongpv7  in which version?

**Comment by JackPeterFletch** [comment]
Im seeing similar. I'd like to be able to wait for Lambda completion after the S3 Trigger so I can make some assertions against localstack itself.

But until this fixes all I can do is poll for expected results with a timeout.
