### ISSUE TITLE
Lambda is not able to interact with Dynamo DB when using LOCALSTACK_HOSTNAME (version 0.11.4)

### ISSUE THREAD

**Issue by ilaneden** [localstack/localstack#3069]
# Type of request: This is a ...
[x ] bug report
[ ] feature request

# Detailed description
I try to connect from lambda to dynamo with the endpoint LOCALSTACK_HOSTNAME:4569. The connection cannot be established.(port 4566 does not work as well). I can, however, connect to dynamo only from my host using localhost:4569.
I also tried to connect from the lambda to dynamo with the endpoint localstack:4569 and the connection cannot be established as well.

docker-compose.yml

    `services:
      localstack:
        image: localstack/localstack:0.11.4
        container_name: localstack
        networks:
          - localstack-network
        ports:
          - "4566-4597:4566-4597"
          - '8080:8080'
        environment:
          - SERVICES=lambda,stepfunctions,dynamodb,s3,sns
          - DEBUG=1
          - DATA_DIR=/tmp/localstack/data
          - PORT_WEB_UI=${PORT_WEB_UI- }
          - LAMBDA_EXECUTOR=docker #${LAMBDA_EXECUTOR- docker-reuse}
          - DOCKER_HOST=unix:///var/run/docker.sock
          - LAMBDA_DOCKER_NETWORK=localstack-network
          - LAMBDA_REMOTE_DOCKER=true
          - LAMBDA_REMOVE_CONTAINERS=true
        volumes:
          - "/tmp${TMPDIR:-/tmp/localstack}:/tmp/localstack"
          - "/var/run/docker.sock:/var/run/docker.sock"` 
docker ps returns:

    `13:06:33  CONTAINER ID        IMAGE                          COMMAND                  CREATED             STATUS              PORTS                                                                                    NAMES
    13:06:33  b909ac695561        localstack/localstack:0.11.4   "docker-entrypoint.sh"   2 minutes ago       Up 2 minutes        4566-4568/tcp, 4593-4597/tcp, 0.0.0.0:4569-4592->4569-4592/tcp, 0.0.0.0:8055->8080/tcp   localstack`docker network inspect localstack-network returns:

    `09:34:47  [
    09:34:47      {
    09:34:47          "Name": "localstack-network",
    09:34:47          "Id": "1c39c8a1dddc4d9c117cf98d487f48efaa487348803a28be6d0d30521849f68f",
    09:34:47          "Created": "2020-10-05T06:31:39.933781539Z",
    09:34:47          "Scope": "local",
    09:34:47          "Driver": "bridge",
    09:34:47          "EnableIPv6": false,
    09:34:47          "IPAM": {
    09:34:47              "Driver": "default",
    09:34:47              "Options": null,
    09:34:47              "Config": [
    09:34:47                  {
    09:34:47                      "Subnet": "100.66.0.0/16",
    09:34:47                      "Gateway": "100.66.0.1"
    09:34:47                  }
    09:34:47              ]
    09:34:47          },
    09:34:47          "Internal": false,
    09:34:47          "Attachable": true,
    09:34:47          "Ingress": false,
    09:34:47          "ConfigFrom": {
    09:34:47              "Network": ""
    09:34:47          },
    09:34:47          "ConfigOnly": false,
    09:34:47          "Containers": {
    09:34:47              "2c1fa863daccbd4041163f6af7f1c3b8a353908138937e1de26e4f78c789a853": {
    09:34:47                  "Name": "localstack",
    09:34:47                  "EndpointID": "58803e6ee4001879dd85b0433f1bc31dbf3a554f7e1af900c0113a2421e74fea",
    09:34:47                  "MacAddress": "02:42:64:42:00:02",
    09:34:47                  "IPv4Address": "100.66.0.2/16",
    09:34:47                  "IPv6Address": ""
    09:34:47              }
    09:34:47          },
    09:34:47          "Options": {},
    09:34:47          "Labels": {
    09:34:47              "com.docker.compose.network": "localstack-network",
    09:34:47              "com.docker.compose.project": "infra",
    09:34:47              "com.docker.compose.version": "1.24.1"
    09:34:47          }
    09:34:47      }
    09:34:47  ]`the relevant part of the client code:

    `        localstack_hostname = os.environ.get('LOCALSTACK_HOSTNAME')
            _dynamo_resource = resource('dynamodb', endpoint_url=f'http://{localstack_hostname}:4569', region_name='us-east-1')`the value of LOCALSTACK_HOSTNAME is: 172.17.0.1

## Expected behavior
Lambda can interact with Dynamo DB
...

## Actual behavior
There is a connection error
...

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-278) by [Unito](https://www.unito.io/learn-more)

**Comment by whummer** [comment]
Thanks for reporting @ilaneden . Can you please share the relevant part of your client code, to make this a bit easier to reproduce. Also, can you please print the value of the `$LOCALSTACK_HOSTNAME` environment variable in your Lambda handler, and share it here?

It seems that you're using a custom Docker network - perhaps setting the configuration `LAMBDA_DOCKER_NETWORK=localstack-network` in your docker-compose should work? Thanks

**Comment by ilaneden** [comment]
thanks @whummer , setting LAMBDA_DOCKER_NETWORK=localstack-network does not solve this. I edited the description of the issue with the client code and the value of $LOCALSTACK_HOSTNAME

**Comment by whummer** [comment]
Thanks @ilaneden . Could be related to this issue: https://github.com/localstack/localstack/issues/2875 . Can you please try the solution suggested on that issue, adding this to docker-compose.yml:
```
network_mode: bridge
```

**Comment by meriouma** [comment]
@whummer I'm having a similar issue when using the docker lambda executor and cannot use bridge mode as I need the container to be on a network. I believe this problem was introduced by https://github.com/localstack/localstack/pull/2908. I'm not sure it's safe to assume that the HOSTNAME variable will be the docker's container-name, especially with docker-compose. To work around the issue, I had to make sure the HOSTNAME variable was the same as the docker-composer `container_name` property for localstack

**Comment by lmarsden** [comment]
We also ran into this when upgrading from 0.11.4 to 0.11.5. We are using `docker-compose` to spin up localstack. The `HOSTNAME` workaround suggested by @meriouma has sorted the issue for the time being.

**Comment by whummer** [comment]
Closing this issue as outdated. Please let us know if the problem persists. Thanks
