### ISSUE TITLE
localstack eventsbridge with SQS as target doesn't work

### ISSUE THREAD

**Issue by Salman-K** [localstack/localstack#3070]
# Type of request: Bug

[x] bug report
[ ] feature request

# Detailed description
When using eventsbridge on localstack with SQS as target, no messages are relayed/forwarded to the queue.

## Expected behavior
Message successfully appears on the queue, when pushed to eventsbridge.

## Actual behavior
No message appears on the queue

# Steps to reproduce

1. Setup localstack using docker
2. Create Queue
3. Create EventBus
4. Set Queue attributes to allow eventbridge access
5. Put target on eventbridge
6. Put new event onto eventbus
7. Check queue for message, no message appears

## Command used to start LocalStack

docker run -d -p "4567-4587:4567-4587" -p "4592-4593:4592-4593" -p 80:8080 -v /var/run/docker.sock:/var/run/docker.sock -e LAMBDA_EXECUTOR=docker --name aws localstack/localstack

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

Using poweshell

$AWS_REGION = 'us-east-1'
$LOCALSTACK_ENDPOINT = 'http://localhost'

aws --endpoint-url=${LOCALSTACK_ENDPOINT}:4576 sqs create-queue --queue-name orderTestQueue

aws --endpoint-url=${LOCALSTACK_ENDPOINT}:4587 --region ${AWS_REGION} events create-event-bus --name orderTestBus

aws --endpoint-url=${LOCALSTACK_ENDPOINT}:4587 --region ${AWS_REGION} events put-rule --name orderTestRuleMatchSource --event-bus-name orderTestBus --event-pattern file://rule-filter.json

aws --endpoint-url=${LOCALSTACK_ENDPOINT}:4576 sqs set-queue-attributes --queue-url "http://localhost:4576/queue/orderTestQueue" --attributes file://sqs-policy.json

aws --endpoint-url=${LOCALSTACK_ENDPOINT}:4587 --region ${AWS_REGION} events put-targets --rule orderTestRuleMatchSource --event-bus-name orderTestBus --targets file://rule-queue-arn.json

aws --endpoint-url=${LOCALSTACK_ENDPOINT}:4587 --region ${AWS_REGION} events put-events --entries file://order-data.json

aws --endpoint-url=${LOCALSTACK_ENDPOINT}:4576 sqs receive-message --queue-url "http://localstack:4576/queue/orderTestQueue"

Referenced files are attached.
Many Thanks
[event-bridge-files.zip](https://github.com/localstack/localstack/files/5326597/event-bridge-files.zip)

**Comment by usmangani1** [comment]
@Salman-K Thanks for reporting the issue.

Which version of localstack are you currently using ? After version 0.11.5 all the services can be only accessed only through edge port i.e 4566. look here [](https://github.com/localstack/localstack/issues/2983)

We are not able to reproduce this on the latest version and also there is already a test case for this functionality here 
[](https://github.com/localstack/localstack/blob/master/tests/integration/test_events.py#L112-L115)

In case if you are using the any of the older versions please let us know the version else you can simply replace the PORT number to 4566 and give it a try.

Please let us know in case if you need any help regarding the same.Thanks

**Comment by Salman-K** [comment]
Hi @usmangani1 Thanks for your reply.

I can't get localstack to work locally with latest tag on port 4566

![image](https://user-images.githubusercontent.com/20575874/95451178-55258f00-095f-11eb-9dce-d0a9609fe3bb.png)

can you please let me know, what i am missing here.
Thanks

**Comment by whummer** [comment]
Thanks for reporting @Salman-K . Looks like this could be a potential region issue - can you please give it another try by adding the `--region ${AWS_REGION}` to *all* the commands above..? Thanks

**Comment by mathieuruellan** [comment]
Hello i succeed to make it working with 0.11.6 version.
I have found a mistake in the SQS policy. The ARN should be "arn:aws:events:us-east-1:000000000000:rule/orderTestRuleMatchSource"

**Comment by Salman-K** [comment]
Thank you @mathieuruellan i was working with an older version, i'll give it a try and thank you for pointing out the error.
Much appreciated.

**Comment by Salman-K** [comment]
Thanks guys for your help, closing it.
