### ISSUE TITLE
LocalStack KMS:  Connection refused

### ISSUE THREAD

**Issue by sahussaimc** [localstack/localstack#3072]
# Type of request: This is a ...

[x ] bug report
[ ] feature request

# Detailed description
I'm mocking KMS using latest Localstack docker image on Win 10. Using awscli I seem to interact with localstack without problems:
```
C:\> awslocal kms list-keys
{
    "Keys": [
        {
            "KeyId": "4703a2e1-b627-4133-a55d-e69bf84ae203",
            "KeyArn": "arn:aws:kms:us-east-1:000000000000:key/4703a2e1-b627-4133-a55d-e69bf84ae203"
        }
    ]
}
```

http://localhost:4566/health seems to show things are good:
```
{"services": {"apigateway": "running", "cloudformation": "running", "cloudwatch": "running", "dynamodb": "running", "dynamodbstreams": "running", "ec2": "running", "es": "running", "firehose": "running", "iam": "running", "sts": "running", "kinesis": "running", "kms": "running", "lambda": "running", "logs": "running", "redshift": "running", "route53": "running", "s3": "running", "secretsmanager": "running", "ses": "running", "sns": "running", "sqs": "running", "ssm": "running", "events": "running", "stepfunctions": "running", "acm": "running"}}
```

In my code, I'm using localstack-dotnet-client (https://github.com/localstack-dotnet/localstack-dotnet-client) to interact with KMS. Everything was up and running until recently when I had to setup docker and localstack from scratch in the same dev environment. Trying to connect with KMS now gives me an exception:

`No connection could be made because the target machine actively refused it.`

I've gone through suggestions for similar past issues posted by others and no luck. Things I've tried:
- bumping up Docker resources (Memory 16GB, Swap: 4 GB)
- ensuring my code is explicitly connecting to "localhost"
- attempted using older versions of Localstack as far as 0.11.0
- various permutations of setting ENTRYPOINT, SERVICES, DEBUG

Suggestions for further debugging to help isolate the root of the problem would be appreciated!

## Expected behavior
Should be able to connect to localstack

## Actual behavior
Trying to connect to localstack gives a "connection actively refused" exception

# Steps to reproduce

## Command used to start LocalStack
set ENTRYPOINT=-d
localstack start

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
Rough idea of what I'm doing in my code:

```
// Creating KMS client
public static IAmazonKeyManagementService BuildKMSClient()
{
    ISession _session = SessionStandalone
                               .Init()
                               .WithConfig("localhost")
                               .Create();

    return _session.CreateClient<AmazonKeyManagementServiceClient>();
}
-----------------------------
// Using KMS client
GenerateDataKeyRequest dataKeyRequest = new GenerateDataKeyRequest()
{
    KeyId = _keyARN,
    KeySpec = DataKeySpec.AES_256
};

DataKeyPair keyPair = new DataKeyPair();
GenerateDataKeyResponse dataKeyResponse = await _kmsClient.GenerateDataKeyAsync(dataKeyRequest);
```

**Comment by whummer** [comment]
Thanks for reporting @sahussaimc . Please note that the network ports have recently changed in LocalStack - all services are not accessible via the edge service port `4566`.

Can you please try after upgrading the command line to the latest version:
```
pip install --upgrade awscli-local localstack-client
```

**Comment by sahussaimc** [comment]
@whummer Just tried updating and I think I'm at the latest:
```

C:\>pip install --upgrade awscli-local localstack-client
Requirement already up-to-date: awscli-local in c:\program files\python36\lib\site-packages (0.9)
Requirement already up-to-date: localstack-client in c:\program files\python36\lib\site-packages (1.4)
Requirement already satisfied, skipping upgrade: awscli in c:\program files\python36\lib\site-packages (from awscli-local) (1.18.150)
Requirement already satisfied, skipping upgrade: boto3 in c:\program files\python36\lib\site-packages (from localstack-client) (1.15.8)
Requirement already satisfied, skipping upgrade: s3transfer<0.4.0,>=0.3.0 in c:\program files\python36\lib\site-packages (from awscli->awscli-local) (0.3.3)
Requirement already satisfied, skipping upgrade: PyYAML<5.4,>=3.10; python_version != "3.4" in c:\program files\python36\lib\site-packages (from awscli->awscli-local) (5.2)
Requirement already satisfied, skipping upgrade: colorama<0.4.4,>=0.2.5; python_version != "3.4" in c:\program files\python36\lib\site-packages (from awscli->awscli-local) (0.4.3)
Requirement already satisfied, skipping upgrade: botocore==1.18.9 in c:\program files\python36\lib\site-packages (from awscli->awscli-local) (1.18.9)
Requirement already satisfied, skipping upgrade: docutils<0.16,>=0.10 in c:\program files\python36\lib\site-packages (from awscli->awscli-local) (0.15.2)
Requirement already satisfied, skipping upgrade: rsa<=4.5.0,>=3.1.2; python_version != "3.4" in c:\program files\python36\lib\site-packages (from awscli->awscli-local) (3.4.2)
Requirement already satisfied, skipping upgrade: jmespath<1.0.0,>=0.7.1 in c:\program files\python36\lib\site-packages (from boto3->localstack-client) (0.9.5)
Requirement already satisfied, skipping upgrade: urllib3<1.26,>=1.20; python_version != "3.4" in c:\program files\python36\lib\site-packages (from botocore==1.18.9->awscli->awscli-local) (1.25.8)
Requirement already satisfied, skipping upgrade: python-dateutil<3.0.0,>=2.1 in c:\program files\python36\lib\site-packages (from botocore==1.18.9->awscli->awscli-local) (2.8.0)
Requirement already satisfied, skipping upgrade: pyasn1>=0.1.3 in c:\program files\python36\lib\site-packages (from rsa<=4.5.0,>=3.1.2; python_version != "3.4"->awscli->awscli-local) (0.4.8)
Requirement already satisfied, skipping upgrade: six>=1.5 in c:\program files\python36\lib\site-packages (from python-dateutil<3.0.0,>=2.1->botocore==1.18.9->awscli->awscli-local) (1.12.0)
```

`awslocal` seems to connect with localstack kms properly as I mentioned in my original post so I'm assuming thats not a problem.

**Comment by whummer** [comment]
Thanks for your response - should have read your original post more carefully.

The problem appears to be this file which is hardcoding the service ports (which are now deprecated): https://github.com/localstack-dotnet/localstack-dotnet-client/blob/c15cc876a6043e55c441aa18079c42c24eca5da0/src/LocalStack.Client/Enums/AwsServiceEndpointMetadata.cs#L22

You basically have two options: 
* patch the library above to use port `4566` for all services
* fix your version of LocalStack to use `0.11.5`

Hope that helps, thanks.

**Comment by sahussaimc** [comment]
@whummer Thanks, I'll try this out and report back with the results.

**Comment by sahussaimc** [comment]
@whummer I made the change to use port 4566 in AwsServiceEndpointMetadata.cs like you suggested and that fixed the problem! Appreciate all your help!

Closing issue. Resolved.

**Comment by Blind-Striker** [comment]
@sahussaimc new version [LocalStack.Net](https://github.com/localstack-dotnet/localstack-dotnet-client) has released. All service has point ports use 4566 by default, but it also backward compatible.

And we have released another package called [LocalStack.Client.Extensions](https://www.nuget.org/packages/LocalStack.Client.Extensions/) which allow you to use LocalStack.Client similar to [AWSSDK.Extensions.NETCore.Setup](https://docs.aws.amazon.com/sdk-for-net/latest/developer-guide/net-dg-config-netcore.html)

See [Readme](https://github.com/localstack-dotnet/localstack-dotnet-client#localstack-client-extensions) for the details.

**Comment by whummer** [comment]
Awesome, thanks @sahussaimc @Blind-Striker !! 👍
