### ISSUE TITLE
Failed to run docker-compose locally

### ISSUE THREAD

**Issue by heat** [localstack/localstack#3073]
# Type of request: This is a ...

[x ] bug report
[ ] feature request

# Detailed description
I followed the installation to use by docker compose, but got error to connect into localhost:8080

## Expected behavior
the web running well 

## Actual behavior
curl: (56) Recv failure: Connection reset by peer

# Steps to reproduce
download last release

## Command used to start LocalStack
docker-compose up

**Comment by whummer** [comment]
Thanks for reporting @heat . Please note that the Web UI is now deprecated (no longer actively maintained), and requires to use the `localstack/localstack-full` Docker image. See this section of the README: https://github.com/localstack/localstack#web-dashboard-deprecated . Hope that helps - please let us know if there are any other issues. Thanks

**Comment by heat** [comment]
thank you whummer,  awesome. it help me 👍
