### ISSUE TITLE
LocalStack used via TestContainers fails to upload file to S3 when files is >= 1MB

### ISSUE THREAD

**Issue by mongoDynamo** [localstack/localstack#3082]
I'm using TestContainers to run localstack in Java. Here is some pseudo code of what I am doing : 

```
  @RunWith(SpringRunner.class)
  @SpringBootTest(classes = {Application.class, Properties.class}, webEnvironment = 
  SpringBootTest.WebEnvironment.RANDOM_PORT)
  public class SomeClass {

  @ClassRule
    public static LocalStackContainer localstack = new LocalStackContainer()
        .withServices(LocalStackContainer.Service.KINESIS).withServices(LocalStackContainer.Service.S3);

  @BeforeClass
    public static void beforeClass() throws InterruptedException, IOException {
      localKinesisClient = AmazonKinesisClientBuilder.standard()
          .withEndpointConfiguration(localstack.getEndpointConfiguration(LocalStackContainer.Service.KINESIS))
          .withCredentials(localstack.getDefaultCredentialsProvider()).build();

    s3Client = AmazonS3Client.builder().withEndpointConfiguration(localstack.getEndpointConfiguration(LocalStackContainer.Service.S3))
        .withCredentials(localstack.getDefaultCredentialsProvider()).build();

    new AWSXRay().beginDummySegment();
    environmentVariables.set("AWS_CBOR_DISABLE", "1");
    CreateStreamRequest createStreamRequest = new CreateStreamRequest();
    logger.info("Create Stream");
    try {
      localKinesisClient.createStream(createStreamRequest.withStreamName(streamName).withShardCount(1));
    } catch (ResourceInUseException exception) {
      logger.info("Stream: " + streamName + "already exists.");
    }

    s3Client.createBucket(s3BucketName);

    //Fails on this line when trying to insert a file of size 1MB
    s3Client.putObject(s3BucketName,"file",getFileContentsAsString("src/test/resources/largetextfield1mb.txt"));

    environmentVariables.set("KINESIS_URL", localstack.getEndpointConfiguration(LocalStackContainer.Service.KINESIS).getServiceEndpoint());
    environmentVariables.set("KINESIS_REGION", localstack.getEndpointConfiguration(LocalStackContainer.Service.KINESIS).getSigningRegion());

    environmentVariables.set("S3_URL", localstack.getEndpointConfiguration(LocalStackContainer.Service.S3).getServiceEndpoint());
    environmentVariables.set("S3_REGION", localstack.getEndpointConfiguration(LocalStackContainer.Service.S3).getSigningRegion());

    System.getenv("KINESIS_URL");
    System.getenv("S3_URL");

    Thread.sleep(500);
  }

}
```

I get the following error : 
Method threw 'com.amazonaws.SdkClientException' exception.

Unable to execute HTTP request: Read timed out

The above code works when I try saving something simple like a word; e.g. "someWord" but fails when I use the 1mb string. Anyway to fix this? This is my current disk set up for docker : 

![image](https://user-images.githubusercontent.com/38298138/95401427-2665d500-08db-11eb-8249-9362dc650a6b.png)

![image](https://user-images.githubusercontent.com/38298138/95401442-2fef3d00-08db-11eb-9108-5289c13f06e4.png)

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-281) by [Unito](https://www.unito.io/learn-more)

**Comment by whummer** [comment]
Thanks for reporting @mongoDynamo . We have recently pushed a change in #3091 that should fix blocking HTTP2 connections for certain types of request. Can you please pull the `latest` Docker image and verify if the issue is still reproducible? (You may need to configure your `LocalStackContainer` to use the latest image). Also - can you please share some details about your environment (operating system, Docker version, etc)? Thanks

**Comment by mongoDynamo** [comment]
> Thanks for reporting @mongoDynamo . We have recently pushed a change in #3091 that should fix blocking HTTP2 connections for certain types of request. Can you please pull the `latest` Docker image and verify if the issue is still reproducible? (You may need to configure your `LocalStackContainer` to use the latest image). Also - can you please share some details about your environment (operating system, Docker version, etc)? Thanks

Thanks, this is the docker version : `Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:39 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     true`

And I'm running on Mac OS High Sierra Version 10.13.6 (17G14019)

Also I've been using TestContainers with JUnit tests to run localstack, which I believe uses the latest image by default : e.g. 

`@ClassRule
  public static LocalStackContainer localstack = new LocalStackContainer()
      .withServices(LocalStackContainer.Service.S3).withServices(LocalStackContainer.Service.KINESIS).withSharedMemorySize(524288000L);`

**Comment by mongoDynamo** [comment]
@whummer I'm still having the same issue. {"status":500,"code":"internalServerError","message":"Read timed out"}

I'm not sure if there's a specific way to specify a specific version with testcontainers, but to my understanding testcontainers pulls from latest.

**Comment by ellisgl** [comment]
I'm seeing the docker image completely crash when uploading larger files (128MB). I'm doing it via PHP and the S3 PHP SDK.
2021-04-29 23:53:07,829:API: Error on request:
Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/werkzeug/serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/werkzeug/serving.py", line 312, in execute
    application_iter = app(environ, start_response)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/server.py", line 177, in __call__
    return backend_app(environ, start_response)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/core/utils.py", line 156, in __call__
    result = self.callback(request, request.url, {})
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/s3/responses.py", line 1004, in key_or_control_response
    response = self._key_response(request, full_url, headers)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/s3/responses.py", line 1175, in _key_response
    return self._key_response_post(request, body, bucket_name, query, key_name)
  File "/opt/code/localstack/localstack/services/s3/s3_starter.py", line 132, in s3_key_response_post
    result = s3_key_response_post_orig(request, body, bucket_name, query, key_name, *args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/s3/responses.py", line 1790, in _key_response_post
    multipart = bucket.multiparts[multipart_id]
KeyError: 'l9TxRidPUPC5WStZNTJm5wopzRFrBJNLaPZLPXqaeFS9GgivSdbb7EmA'

**Comment by whummer** [comment]
Thanks @ellisgl @mongoDynamo  Please note that we've recently added a number of enhancements around handling of large files which should (hopefully) resolve this issue for good.

The following upload with a 800MB file seems to be working fine - are you able to replicate this behavior?
```
$ dd if=/dev/urandom of=large_file.tmp count=800 bs=1000000
$ awslocal s3 mb s3://test
$ awslocal s3 cp large_file.tmp s3://test/large            
upload: ./large_file.tmp to s3://test/large
```

@ellisgl The error below points at a potential issue with the legacy persistence mechanism - do you have `DATA_DIR` enabled in your config? Can you please verify whether the upload works with the `DATA_DIR` option disabled? Thanks
```
KeyError: 'l9TxRidPUPC5WStZNTJm5wopzRFrBJNLaPZLPXqaeFS9GgivSdbb7EmA'
```

Hope that helps - please let us know if the problem persists.. Thanks!
