### ISSUE TITLE
SQS Dead Letter and normal queue wont list properly on cli

### ISSUE THREAD

**Issue by isikhi** [localstack/localstack#3085]
# Type of request: This is a ...
[X ] bug report
[ ] feature request

# Detailed description
I'm creating a dead letter queue and a normal queue. When I do aws sqs list-queues, only dead letter queues appear. but when I do listQueues with amazon sdk they all show up.
...

## Expected behavior
Should show all queues instead of only dead letters
...

## Actual behavior
Show only dead letter quueus
...

# Steps to reproduce
## Command used to start LocalStack
localstack start from cli
...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
```
isik@isik-v:~/someprojects$ aws --endpoint-url=http://localhost:4566 sqs list-queues
{
    "QueueUrls": [
        "http://localhost:4566/000000000000/dead_letter_isiktest_aq",
        "http://localhost:4566/000000000000/dead_letter_isiktest_bq",
        "http://localhost:4566/000000000000/dead_letter_isiktest_cq",
        "http://localhost:4566/000000000000/dead_letter_isiktest_dq",
        "http://localhost:4566/000000000000/dead_letter_isiktest_eq",
        "http://localhost:4566/000000000000/dead_letter_isiktest_fq",
        "http://localhost:4566/000000000000/dead_letter_isiktest_gq",
        "http://localhost:4566/000000000000/dead_letter_isiktest_hq",
]
}
```

When i list from sdk below result appear on console

```
        "http://localhost:4566/000000000000/dead_letter_isiktest_aq",
        "http://localhost:4566/000000000000/dead_letter_isiktest_bq",
        "http://localhost:4566/000000000000/dead_letter_isiktest_cq",
        "http://localhost:4566/000000000000/dead_letter_isiktest_dq",
        "http://localhost:4566/000000000000/dead_letter_isiktest_eq",
        "http://localhost:4566/000000000000/dead_letter_isiktest_fq",
        "http://localhost:4566/000000000000/dead_letter_isiktest_gq",
        "http://localhost:4566/000000000000/dead_letter_isiktest_hq",
        "http://localhost:4566/000000000000/isiktest_aq",
        "http://localhost:4566/000000000000/isiktest_bq",
        "http://localhost:4566/000000000000/isiktest_cq",
        "http://localhost:4566/000000000000/isiktest_dq",
        "http://localhost:4566/000000000000/isiktest_eq",
        "http://localhost:4566/000000000000/isiktest_fq",
        "http://localhost:4566/000000000000/isiktest_gq",
        "http://localhost:4566/000000000000/isiktest_hq",

```

...

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-282) by [Unito](https://www.unito.io/learn-more)

**Comment by usmangani1** [comment]
@isikhi 
Thanks for reporting the issue.

Can you please share us some sample commands on how you are creating these queues and the sequence?

**Comment by isikhi** [comment]
Sure @usmangani1 I create the queues with node js aws sdk . Like
createdQueueParams = { QueueName: queueName }

if it main queue i will add below params 
```
     if (!createdQueueParams.Attributes) createdQueueParams.Attributes = {};
      createdQueueParams.Attributes.RedrivePolicy = JSON.stringify({
        deadLetterTargetArn: deadLetterQueueAttributes.Attributes.QueueArn,
        maxReceiveCount: config.mq.deadLetterMaxReceivedCount,
      });
```

`sqs.createQueue(createdQueueParams)`


As i said it works queueus will be created but i cant see with sqs list-queues command when i connect localstack.

**Comment by usmangani1** [comment]
@isikhi 
We tried to reproduce the issue with the current version and we are not able to reproduce the issue.
Are you using the latest version of localstack ? If not, Can you please use the latest version and give it a try once and let us know if you still face the same issue?

Attaching the commands and their responses here for reference.

```
$ aws --endpoint-url=http://localhost:4566 sqs create-queue  --queue-name=my-test-queue
{
    "QueueUrl": "http://localhost:4566/000000000000/my-test-queue"
}
$ aws sqs create-queue --queue-name MyQueue --attributes file://sample.json  --endpoint-url=http://localhost:4566
{
    "QueueUrl": "http://localhost:4566/000000000000/MyQueue"
}
$ aws --endpoint-url=http://localhost:4566 sqs list-queues
{
    "QueueUrls": [
        "http://localhost:4566/000000000000/my-test-queue",
        "http://localhost:4566/000000000000/MyQueue"
    ]
}

```

**Comment by whummer** [comment]
Thanks for reporting @isikhi and thanks for looking into this @usmangani1 . Looks like we are not able to reproduce the issue at this point. Can you please give it a try after pulling the `latest` Docker image, and report here with exact steps to reproduce if the problem persists. Thanks
