### ISSUE TITLE
SQS SendMessage with file type JSON in message attribute is throwing error 'Invalid type for parameter MessageAttributes'

### ISSUE THREAD

**Issue by ashameem123** [localstack/localstack#3099]
This is a ...

[x] bug report
[ ] feature request

# Detailed description
unable to send JSON type message via SQS , getting error on uploading any json.

## Expected behavior
Should able to process a JSON file via SQS message to trigger and process lambda

## Actual behavior
"Everytime getting "Parameter validation failed.
 Invalid type for parameter MessageAttributes"

# Steps to reproduce

## Command used to start LocalStack  
docker-compose up -d

create queue:
aws --endpoint-url=http://localhost:4566 sqs create-queue --queue-name my_queue

create function:
aws lambda create-function --endpoint-url=http://localhost:4566 --function-name SQStoLambda --runtime java11 --role arn:aws:iam::000000000000:role/testpublish-function --handler lambda.functions.SQStoLambda --zip-file fileb://C:/AWS/Localstack/testAllServices/build/libs/testAllServices.jar --environment Variables="{PROFILE=LOCAL,AWS_REGION=us-east-1}"

event mapping:
aws --endpoint-url=http://localhost:4566 lambda create-event-source-mapping --event-source-arn arn:aws:sqs:us-east-1:000000000000:my_queue --function-name SQStoLambda

Send message to SQS

aws --endpoint-url=http://localhost:4566 sqs send-message --queue-url "http://localhost:4566/queue/my_queue" --message-body "Triggered thru sqs" --delay-seconds 10 --message-attributes file://color.json

Json files used: Unable to upload json file type hence copied the content in text file

[type1.txt](https://github.com/localstack/localstack/files/5373525/type1.txt)
[type2.txt](https://github.com/localstack/localstack/files/5373526/type2.txt)

![LS_InvalidInputParam](https://user-images.githubusercontent.com/54183749/95904041-92718e80-0d5c-11eb-90f5-f5bc220cff1b.JPG)

**Comment by usmangani1** [comment]
@ashameem123 
Thanks for reporting the issue. 
Looks like the message-attributes which are being passed are not of a valid type according to the documentation here
https://docs.aws.amazon.com/cli/latest/reference/sqs/send-message.html

Please try changing it accordingly and give it a try and if you still face the issue please let us know.Thanks

**Comment by ashameem123** [comment]
My json has no issues. I tried with the sample json given in aws website -https://docs.aws.amazon.com/cli/latest/reference/sqs/send-message.html and getting below error,

![image](https://user-images.githubusercontent.com/54183749/96030753-09bd2600-0e22-11eb-809b-a2a6250aa193.png)

**Comment by ashameem123** [comment]
thanks @usmangani1 . Indeed it was json issue. Thanks for looking into it
