### ISSUE TITLE
Regression: S3 error when attempting to delete using C# Amazon S3 SDK

### ISSUE THREAD

**Issue by peitschie** [localstack/localstack#310]
This regression was only introduced recently... perhaps related to 5507eea779ed6400763cfbfc9f320533f9f6bac4?

When attempting to delete files using the AWS C# S3 SDK, the following error is logged to the console:
```
2017-09-11T04:24:30:ERROR:localstack.services.generic_proxy: Error forwarding request: 'boundary' Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 166, in forward
    path=path, data=data, headers=forward_headers)
  File "/opt/code/localstack/localstack/services/s3/s3_listener.py", line 345, in forward_request
    expanded_data = expand_multipart_filename(original_data, headers)
  File "/opt/code/localstack/localstack/services/s3/s3_listener.py", line 261, in expand_multipart_filename
    boundary = params['boundary'].encode('ascii')
KeyError: 'boundary'
```

I'm doing c# code like the following:
```
if (files.S3Objects.Any())
{
    _s3.DeleteObjects(new DeleteObjectsRequest
    {
        BucketName = Bucket,
        Objects = files.S3Objects.Select(o => new KeyVersion { Key = o.Key }).ToList()
    });
}
```

This worked previously, and has only broken since I updated to the most recent docker image of localstack.

**Comment by peitschie** [comment]
Just confirming, the above block of code works correctly with docker image version 0.7.4, but hangs when run against 0.7.5, and spits out the captured error above.

**Comment by migurski** [comment]
I have a fix for this in https://github.com/localstack/localstack/pull/332. I’d be interested to see the underlying POST request this C# code makes, to improve the test coverage.

**Comment by peitschie** [comment]
Sorry, this is still on my radar, but I haven't yet had time to confirm! I'll post back when I get a chance... possibly sometime next week 😄
