### ISSUE TITLE
Documentation Update for WebUI env var

### ISSUE THREAD

**Issue by roundrobinshubham** [localstack/localstack#3108]
# Type of request: Documentation
[x] bug report
[ ] feature request

# Detailed description
The following in [README](https://github.com/localstack/localstack/blob/master/README.md)

```
PORT_WEB_UI: Port for the Web user interface / dashboard (default: 8080). Note that the Web UI is now deprecated, and requires to use the localstack/localstack-full Docker image.
```

States about web UI, for while now a different image has to be used

and 

the following

```
START_WEB: Flag to control whether the Web UI should be started in Docker (values: 0/1; default: 1).
```

this line forms some ambiguity. 

## Expected behavior
Documentation may require an updation for the above change, as in the env var `START_WEB` is it even required when we aren't using localstack-ful

## Actual behavior
# Steps to reproduce NA
## Command used to start LocalStack
NA

## Note -  Would like to heartily thank all the devs and contributors you guys rock cheers

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-290) by [Unito](https://www.unito.io/learn-more)

**Comment by whummer** [comment]
Thanks for reporting @shubhamknoldus - would you mind creating a small pull request to update the documentation? That would be much appreciated, thanks.

**Comment by whummer** [comment]
This has been updated in our docs in the meantime. Thanks!
