### ISSUE TITLE
QLDB doesn't match its functionality in AWS

### ISSUE THREAD

**Issue by IvanMigov** [localstack/localstack#3109]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description
I use the latest docker image of localstack. Have a license key.
docker-compose for localstack:
 ```
localstack:
    image: localstack/localstack:latest
    ports:
      - "53:53"
      - "443:443"
      - "4510-4520:4510-4520"
      - "4566-4620:4566-4620"
    env_file: ./docker-compose.env
    environment:
      - SERVICES=qldb
      - PORT_WEB_UI=8080
      - DEBUG=1
      - DATA_DIR=./tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - ./tmp/localstack:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock
```
docker-compose.env contains only one string with localstack api key
`LOCALSTACK_API_KEY=xxxxxxxxxxxxx`
to create ledger i use:
`aws qldb create-ledger --name CATALOG --permissions-mode ALLOW_ALL --endpoint-url=http://localhost:4566 --debug
`
then i connect to qlbd with shell:
`qldbshell -l CATALOG -s http://localhost:4566`

next commands have different results in localstack shell and AWS QLDB query editor:
```
SELECT * FROM history(assets) AS a WHERE a.metadata.id = '6f8b228a'
UPDATE assets AS a BY pid SET a = {} WHERE pid = '6f8b228a'
SELECT * FROM assets BY pid WHERE pid = '6f8b228a'
```
...

## Expected behavior
`SELECT * FROM assets BY pid WHERE pid = '6f8b228a' `should return current state of a document with metadata.id = '6f8b228a'

`UPDATE assets AS a BY pid SET a = {} WHERE pid = '6f8b228a'` should replace whole document (with metadata.id = '6f8b228a') with an empty object

`SELECT * FROM history(assets) AS a WHERE a.metadata.id = '6f8b228a'` should return history of changes for the document with metadata.id = '6f8b228a'
...

## Actual behavior
`SELECT * FROM assets BY pid WHERE pid = '6f8b228a'` - empty response

`UPDATE assets AS a BY pid SET a = {} WHERE pid = '6f8b228a'` makes new property with key = 'a' and value. = {}

`SELECT * FROM history(assets) AS a WHERE a.metadata.id = '6f8b228a'`- empty response
...

# Steps to reproduce

1. Make sure that you have latest image of localstack with `docker pull localstack/localstack` comand
2. Run localstack container with `docker-compose up -d localstack`
3. install AWS CLI with 
`curl "https://awscli.amazonaws.com/AWSCLIV2.pkg" -o "AWSCLIV2.pkg"` 
` sudo installer -pkg AWSCLIV2.pkg -target /`
4. create ledger with 
`aws qldb create-ledger --name CATALOG --permissions-mode ALLOW_ALL --endpoint-url=http://localhost:4566 --debug
`
5. connect to ledger 
`qldbshell -l CATALOG -s http://localhost:4566`
6. use commands to reproduce bug
`CREATE TABLE assets`

```
INSERT INTO assets
<< {
	'assetId': 4,
    'subTitle':'QLDB',
    'description':'Amazon Quantum Ledger Database'
} >>

```

`SELECT * FROM assets BY pid`
Grab pid of created record (in commands below i will use 'xxx' as id)

`UPDATE assets AS a BY pid SET a = {} WHERE pid = 'xxx'`
`SELECT * from assets by pid where pid = 'xxx'`
`SELECT * FROM history(assets) AS a WHERE a.metadata.id = 'xxx'`
## Command used to start LocalStack
`docker-compose up -d localstack`
...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
```
aws qldb create-ledger --name CATALOG --permissions-mode ALLOW_ALL --endpoint-url=http://localhost:4566 --debug
qldbshell -l CATALOG -s http://localhost:4566
CREATE TABLE assets
```
...

**Comment by whummer** [comment]
Hi @IvanMigov , thanks for the detailed report. This issue should be fixed in the meantime - can you please give it a try with the `latest` version of the Docker image? Please let us know if the problem persists. Many thanks for your help!

**Comment by IvanMigov** [comment]
## Expected behavior
`SELECT * FROM assets BY pid WHERE pid = '6f8b228a' `should return current state of a document with metadata.id = '6f8b228a'

`UPDATE assets AS a BY pid SET a = {'name':'somename', 'edited':true, 'number_field':3} WHERE pid = '1d89ac61'` should replace whole document (with metadata.id = '6f8b228a') with {'name':'somename', 'edited':true, 'number_field':3}

`SELECT * FROM history(assets) AS a WHERE a.metadata.id = '6f8b228a'` should return history of changes for the document with metadata.id = '6f8b228a'
...

## Actual behavior
`SELECT * FROM assets BY pid WHERE pid = '6f8b228a'` -  `Error while executing query: An error occurred (400) when calling the SendCommand operation: `

`UPDATE assets AS a BY pid SET a = {'name':'somename', 'edited':true, 'number_field':3} WHERE pid = '1d89ac61'` `Error while executing query: An error occurred (400) when calling the SendCommand operation: `

`SELECT * FROM history(assets) AS a WHERE a.metadata.id = '6f8b228a'`- redundant property 'pid' in data section 
...

**Comment by IvanMigov** [comment]
steps to reproduce `SELECT * FROM assets BY pid WHERE pid = '6f8b228a'`


```
CREATE TABLE tests
INSERT INTO tests << {'assetId': 4, 'subTitle':'QLDB', 'description':'Amazon Quantum Ledger Database'} >>
SELECT * from tests by pid
```
grab pid
`SELECT * from tests by pid where pid = '37aadb96'`
live example:
```
qldbshell > SELECT * from tests by pid
INFO: 
{
 assetId: 4,
 subTitle: "QLDB",
 description: "Amazon Quantum Ledger Database",
 pid: "37aadb96"
}
INFO: (2.2505s)
qldbshell > SELECT * from tests by pid where pid = '37aadb96'
WARNING: Error while executing query: An error occurred (400) when calling the SendCommand operation: 
INFO: (2.2109s)
qldbshell >


docker logs:
```
org.partiql.lang.syntax.LexerException: Lexer Error: at line 1, column 50: invalid character at, 
	at org.partiql.lang.syntax.SqlLexer$tokenize$1.invoke(SqlLexer.kt:426)
	at org.partiql.lang.syntax.SqlLexer.tokenize(SqlLexer.kt:455)
	at org.partiql.lang.syntax.SqlParser.parseExprNode(SqlParser.kt:1907)
	at org.partiql.lang.CompilerPipelineImpl.compile(CompilerPipeline.kt:164)
	at org.partiql.cli.Cli.run(Cli.kt:43)
	at org.partiql.cli.Main.runCli(main.kt:179)
	at org.partiql.cli.Main.main(main.kt:137)
2020-10-19T12:57:12:INFO:localstack_ext.services.qldb.qldb_api: Unable to execute query: Command '['/tmp/localstack/partiql/partiql-cli-0.2.1/bin/partiql', '-q', "SELECT * from tests by pid where pid = '37aadb96'", '-e', '/tmp/tmplgon0oeb', '-i', '/tmp/tmpf89wazmk', '-o', '/tmp/tmplvako4qm', '--of', 'ION_TEXT']' returned non-zero exit status 1. Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/qldb/qldb_api.py", line 216, in send_command
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/qldb/qldb_api.py", line 91, in execute_statement
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/qldb/partiql.py", line 42, in run_query
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/qldb/partiql.py", line 194, in run_query_select
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/tmp/localstack/partiql/partiql-cli-0.2.1/bin/partiql', '-q', "SELECT * from tests by pid where pid = '37aadb96'", '-e', '/tmp/tmplgon0oeb', '-i', '/tmp/tmpf89wazmk', '-o', '/tmp/tmplvako4qm', '--of', 'ION_TEXT']' returned non-zero exit status 1.

```

**Comment by whummer** [comment]
Thanks for providing these details @IvanMigov . As discussed via Slack - this issue should be fixed in `latest`. We'll work with you directly to look into any follow-up issues. Thanks for your support.
