### ISSUE TITLE
Tag the latest release

### ISSUE THREAD

**Issue by workmanw** [localstack/localstack#3117]
It looks like a new release was published to docker today and this solves some performance issues we've been seeing with edge ports. Can we please get a tag for `0.11.7` so we can pin it in our config?

**Comment by whummer** [comment]
Thanks for reporting @workmanw . I'd assume that the performance issue you mentioned was potentially fixed in #3091 . Let's hope it stays that way - otherwise please let us know. A new version `0.12.0` has been tagged in #3118 (image currently being built/pushed in our CI system). Thanks

**Comment by workmanw** [comment]
@whummer Thanks! Sorry I realized that you're using the docker `latest` as a CI/CD build so I shouldn't have assumed it was a new release. Thanks again, we're excited about edge ports.
