### ISSUE TITLE
EDGE_PORT isn't provided to the lambda environment

### ISSUE THREAD

**Issue by robkinyon-roivant** [localstack/localstack#3119]
# Type of request: This is a ...

[X] bug report
[ ] feature request

# Detailed description
LOCALSTACK_HOSTNAME Is provided for lambdas to use when making calls back to localstack. However, EDGE_PORT Is not provided. This means that the lambda cannot construct a correct URL.
...

## Expected behavior

Either of the following (or both!) would be okay:

* EDGE_PORT is provided and the URL is constructed as "http://${LOCALSTACK_HOSTNAME}:${EDGE_PORT}"
* LOCALSTACK_URL is provided and it contains the above value.

The LOCALSTACK_URL would be even better because it could take any SSL considerations into account.
...

## Actual behavior

...

# Steps to reproduce

## Command used to start LocalStack

...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

...

**Comment by whummer** [comment]
Thanks for reporting @robkinyon-roivant . This should be fixed in #3123 - can you please pull the `latest` Docker image and give it another try? Please report here if the problem persists. Thanks
