### ISSUE TITLE
Get queue url return 404

### ISSUE THREAD

**Issue by mikicho** [localstack/localstack#3126]
# Type of request: 

[x] bug report
[ ] feature request

# Detailed description
The queue is working as expected but when I `wait-for` it with:
```
curl -s -o /dev/null -w "%{http_code}" "http://localstack:4566?Action=GetQueueUrl&QueueName=jobs"
```
It returns `404`
With body:
```
{"status": "running"}
```

But the following command returns `200` (as expected):
```
curl -s -o /dev/null -w "%{http_code}" "http://localstack:4566/000000000000/jobs"
```

## Expected behavior
Return the queue URL with `200` response code

## Actual behavior
Returns `404` with `{"status": "running"}`

# Steps to reproduce
1. provision localstack with sqs queue named `jobs`
2. run `curl "localstack:4566?Action=GetQueueUrl&QueueName=jobs"` from another container in the same network

## Command used to start LocalStack
docker compose:
```
localstack:
    image: localstack/localstack:0.11.6
    environment:
      - SERVICES=sqs
      - DEBUG=1
      - DEFAULT_REGION=us-west-2
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    env_file:
      - .env
```

...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
n/a

**Comment by whummer** [comment]
Thanks for reporting @mikicho . The `curl` command you posted does not look like a valid AWS command. In particular, it is missing the `Authorization` HTTP header which is required by LocalStack to detect the target API, and also [required in real AWS to authenticate any request](https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-auth-using-authorization-header.html). Notably, this command would also not work when run against real AWS.

Can you please try to either:
(1) provide a fake `Authorization` header similar to the real AWS auth headers, to allow LocalStack to understand that this is an SQS request
(2) use any AWS SDK library (or the `awslocal` command line) to make the request (any SDK will add a corresponding `Authorization` header to the request).

Hope that helps - please let us know if there are any other questions or issues. Thanks

**Comment by mikicho** [comment]
@whummer 
Thanks for the quick response.
It worked before, just saying :)
and 
```
curl -s -o /dev/null -w "%{http_code}" "http://localstack:4566/000000000000/jobs"
```
is working with auth header
