### ISSUE TITLE
Support new step function features released in August

### ISSUE THREAD

**Issue by SteggyLeggy** [localstack/localstack#3129]
# Type of request: This is a ...

[ ] bug report
[x] feature request

# Detailed description
AWS has released a number of new step function features that are not currently supported by localstack.

They are detailed in this blog post [New Step Function Features](https://aws.amazon.com/blogs/aws/aws-step-functions-adds-updates-to-choice-state-global-access-to-context-object-dynamic-timeouts-result-selection-and-intrinsic-functions-to-amazon-states-languages/)

But they include

1. New comparison operators, IsNull, IsPresent etc.
2. ResultSelector field - transform output data into the context object
3. Reference context object in other sections
4. Dynamic Timeouts
5. JSON to String and vice versa converters
6. State Array changes

I'm particularly interested in 1 & 2 as they have improved our step functions flow but there isn't currently a way to use those in localstack.
...

## Expected behavior
The above features to be implemented.
...

## Actual behavior
I can't talk for all of the above features, but specifically the ResultSelector causes issues as localstack thinks that it's not a valid field and stops the creation of the step function.
...

# Steps to reproduce
Try and create a step function with a Task that has the ResultSelector field in it.

## Command used to start LocalStack
N/A
...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
N/A
...

**Comment by aidan-plenert-macdonald** [comment]
Requests should probably just be forwarded to https://hub.docker.com/r/amazon/aws-stepfunctions-local

Then behavior should match one for one.

**Comment by whummer** [comment]
Thanks for reporting @SteggyLeggy @aidan-plenert-macdonald . In the meantime, we have incorporated the latest StepFunctions Local release which supports a lot of the features you mentioned (e.g., IsPresent, etc). We'll keep incorporating the latest versions, please report any missing features against the upstream AWS Docker repo. Thanks

> Maintainers, any suggested best practices for sticking docker containers in? In lambda_executors, it looks like it took a lot of work. Any easier way to support this?

@aidan-plenert-macdonald Can you please elaborate a bit what specifically you're trying to achieve..? Perhaps it would make sense to open a separate issue to discuss this in more detail. Thanks
