### ISSUE TITLE
localstack eventsbridge with SQS as target, doesn't adhere to the rules condition

### ISSUE THREAD

**Issue by Salman-K** [localstack/localstack#3132]
# Type of request: Bug

[x] bug report
[ ] feature request

# Detailed description
When using eventsbridge on localstack with SQS as target, the rules are completely ignored and the messages are always pushed to the queue regardless.

## Expected behavior
Messages are dropped if condition in rule isn't met.

## Actual behavior
Message appears on the queue even though it clearly doesn't match the criteria of the rule pattern.

# Steps to reproduce

    1. Setup localstack using docker
    2. Create Queue
    3. Create EventBus
    4. Set Queue attributes to allow eventbridge access
    5. Put target on eventbridge
    6. Put new event onto eventbus
    7. Check queue for message

## Command used to start LocalStack
docker run -d -p "4567-4587:4567-4587" -p "4592-4593:4592-4593" -p 80:8080 -v /var/run/docker.sock:/var/run/docker.sock -e LAMBDA_EXECUTOR=docker  --name aws localstack/localstack:0.11.2

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
$AWS_REGION = 'us-east-1'
$LOCALSTACK_ENDPOINT = 'http://localhost'

aws --endpoint-url=${LOCALSTACK_ENDPOINT}:4576 sqs create-queue --queue-name orderTestQueue

aws --endpoint-url=${LOCALSTACK_ENDPOINT}:4587 --region ${AWS_REGION} events create-event-bus --name orderTestBus

aws --endpoint-url=${LOCALSTACK_ENDPOINT}:4587 --region ${AWS_REGION} events put-rule --name orderTestRuleMatchSource --event-bus-name orderTestBus --event-pattern file://rule-filter.json

aws --endpoint-url=${LOCALSTACK_ENDPOINT}:4576 sqs set-queue-attributes --queue-url "http://localhost:4576/queue/orderTestQueue" --attributes file://sqs-policy.json

aws --endpoint-url=${LOCALSTACK_ENDPOINT}:4587 --region ${AWS_REGION} events put-targets --rule orderTestRuleMatchSource --event-bus-name orderTestBus --targets file://rule-queue-arn.json

aws --endpoint-url=${LOCALSTACK_ENDPOINT}:4587 --region ${AWS_REGION} events put-events --entries file://order-data.json

aws --endpoint-url=${LOCALSTACK_ENDPOINT}:4576 sqs receive-message --queue-url "http://localstack:4576/queue/orderTestQueue"

## rule-filter.json
{"source": [ "UpdateOrder" ]}

## order-data.json
[{
	"EventBusName": "orderTestBus",
	"Source": "NewOrder",
	"DetailType": "OrderAdded",
	"Detail": "{\"order_id\":\"a787ecb\",\"quantity\":\"1\",\"customer_id\":\"alpha\"}"
}]
## sqs-policy.json
{"Policy":"{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Principal\":{\"AWS\":\"*\"},\"Action\":\"sqs:SendMessage\",\"Resource\":\"arn:aws:sqs:us-east-1:000000000000:orderTestQueue\",\"Condition\":{\"ArnEquals\":{\"aws:SourceArn\":\"arn:aws:events:us-east-1:000000000000:rule/orderTestRuleMatchSource\"}}}]}"}

## rules-queue-arn.json
[{"Id": "orderTestQueueCommand", "Arn": "arn:aws:sqs:us-east-1:000000000000:orderTestQueue", "InputPath": "$.detail"}]

As you can see above i am looking to filter the messages with source UpdateOrder, where as posting order-data.json with the content displayed also ends up on the queue, which shouldn't.

Unfortunately i can't use the latest version due to dependencies, could you please confirm if this was resolved, or what am i doing wrong here.

Referenced files are attached.
Many Thanks

[rule-queue-arn.zip](https://github.com/localstack/localstack/files/5403817/rule-queue-arn.zip)

**Comment by whummer** [comment]
Thanks for reporting @Salman-K . This should be fixed in #3144 - can you please pull the `latest` Docker image and give it another try? Please report here if the problem persists. Thanks

**Comment by Salman-K** [comment]
Hi @whummer, thanks for fixing this, however  i have found multiple problems with the fix. i will try to be as detailed as possible.

## 1. EventBridge pushes the message to the queue multiple time(s), i tested and could read the message atleast 5 times.

when you pushed the following content in **order-data.json**
[{
"EventBusName": "orderTestBus",
"Source": "UpdateOrder",
"DetailType": "OrderAdded",
"Detail": "{"order_id":"a787ecb","quantity":"1","customer_id":"alpha"}"
}]

check the queue, it appears on the queue atleast 5 times before the queue is dequeued properly.

## 2. EventBridge caches previously pushed data as a result of put-events and continously uses it inspite of new data pushed.

after you've pushed the following data in **order-data.json**
[{
"EventBusName": "orderTestBus",
"Source": "UpdateOrder",
"DetailType": "OrderAdded",
"Detail": "{"order_id":"a787ecb","quantity":"1","customer_id":"alpha"}"
}]

check the queue, the message will appear, now change the content of **order-data**.json to the following and push it to eventbridge again.

[{
"EventBusName": "orderTestBus",
"Source": "UpdateOrder",
"DetailType": "OrderAdded",
"Detail": "{"order_id":"by67r4","quantity":"12","customer_id":"alphaBeta"}"
}]

check the queue, the old message with detail "Detail": "{"order_id":"a787ecb","quantity":"1","customer_id":"alpha"}" will be pushed to the queue.

this was test using latest version of localstack using edge port 4566.

Thanks
