### ISSUE TITLE
AWS Timestream support?

### ISSUE THREAD

**Issue by philperron** [localstack/localstack#3133]
# Type of request:
[ ] bug report
[x] feature request

# Detailed description
Is there a time line of feature releases somewhere? I am wondering if there are plans to include Timestream to the localstack stack the same way we can interact locally with DynamoDB?

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-293) by [Unito](https://www.unito.io/learn-more)

**Comment by siyuanh** [comment]
Is the timestream fully supported? It is listed in the supported list, but when I experiment it, it doesn't work.

**Comment by arpekkar** [comment]
I would like to know the status of this as well. We are using AWS timestream but can it be localized with Localstack and what are the possible limitations with it?

**Comment by silv-io** [comment]
Hello @siyuanh, @arpekkar! Which functionality are you looking for in Timestream?

**Comment by mdodsworth** [comment]
It'd be helpful to know the level of support for Timestream. Basic functionality seems to be there: I can create databases/tables, write records, issue simple queries for example.

A couple of things that don't seem to work right now:
- support for multi-measure records
- UNION queries

In both cases, I've rigged something up to hit a real Timestream table to make sure it's not a me problem. Having documentation on supported/unsupported features and failing when trying to use unsupported functionality would save a lot of stumbling around.

**Comment by marcelosarquis** [comment]
Good morning team. Do we have any news on this topic? Cheers!

**Comment by marcelosarquis** [comment]
Thank you bot, but the case has not being completed.

**Comment by marcelosarquis** [comment]
Do we have any news here @silv-io ?

**Comment by whummer** [comment]
Hi @marcelosarquis , thanks for the update. Can you please share the details of your use case - do you have the same requirements as @mdodsworth ? 

Given that this issue is very old (from 2020) and the initial request was to add basic support for Timestream (which is now available), would be great if we can create follow-up issues for missing functionality, with detailed steps to reproduce. We'll be happy to look into it in more detail.. Thanks for your help! 🙌

**Comment by perryzjc** [comment]
> Hi all! I'm using the latest localstack-pro version (2.1.0) and I'm writing multi-measures records in a timestream table. When I query the measures table, it doesn't return the measures values. Is it possible the multi-measures feature is not supported ?
> 
> This is the timestream-write command:
> 
> `awslocal timestream-write write-records --database-name test-data-measures --table-name measures --records '[{"Dimensions":[{"Name":"dim_a","Value":"fb2299c6-6b83-418a-b778-9aa74cf534fa"}],"MeasureName":"MY_MEASURE","MeasureValues":[{"Name":"measureValue","Value":"1","Type":"DOUBLE"},{"Name":"start_time","Value":"1684152000000","Type":"TIMESTAMP"}],"MeasureValueType":"MULTI","TimeUnit":"MILLISECONDS","Time":"1684152180000","Version":1686647879684}]'`
> 
> This is the timestream-query output:
> 
> `# awslocal timestream-query query --query-string 'select * from test-data-measures.measures' --max-items 1` `INFO: Environment variable "AWS_DEFAULT_REGION" will be overwritten by "DEFAULT_REGION"`
> 
> ```json
> {
>     "Rows": [
>         {
>             "Data": [
>                 {
>                     "ScalarValue": "2023-05-15 12:03:00.000000000"
>                 },
>                 {
>                     "ScalarValue": "MY_MEASURE"
>                 },
>                 {
>                     "ScalarValue": "True"
>                 }
>             ]
>         }
>     ],
>     "ColumnInfo": [
>         {
>             "Name": "time",
>             "Type": {
>                 "ScalarType": "TIMESTAMP"
>             }
>         },
>         {
>             "Name": "measure_name",
>             "Type": {
>                 "ScalarType": "VARCHAR"
>             }
>         },
>         {
>             "Name": "measure_value::multi",
>             "Type": {
>                 "ScalarType": "MULTI"
>             }
>         }
>     ],
>     ...
> }
> ```

Is there any update on this?

**Comment by sannaroby** [comment]
> > Hi all! I'm using the latest localstack-pro version (2.1.0) and I'm writing multi-measures records in a timestream table. When I query the measures table, it doesn't return the measures values. Is it possible the multi-measures feature is not supported ?
> > This is the timestream-write command:
> > `awslocal timestream-write write-records --database-name test-data-measures --table-name measures --records '[{"Dimensions":[{"Name":"dim_a","Value":"fb2299c6-6b83-418a-b778-9aa74cf534fa"}],"MeasureName":"MY_MEASURE","MeasureValues":[{"Name":"measureValue","Value":"1","Type":"DOUBLE"},{"Name":"start_time","Value":"1684152000000","Type":"TIMESTAMP"}],"MeasureValueType":"MULTI","TimeUnit":"MILLISECONDS","Time":"1684152180000","Version":1686647879684}]'`
> > This is the timestream-query output:
> > `# awslocal timestream-query query --query-string 'select * from test-data-measures.measures' --max-items 1` `INFO: Environment variable "AWS_DEFAULT_REGION" will be overwritten by "DEFAULT_REGION"`
> > ```json
> > {
> >     "Rows": [
> >         {
> >             "Data": [
> >                 {
> >                     "ScalarValue": "2023-05-15 12:03:00.000000000"
> >                 },
> >                 {
> >                     "ScalarValue": "MY_MEASURE"
> >                 },
> >                 {
> >                     "ScalarValue": "True"
> >                 }
> >             ]
> >         }
> >     ],
> >     "ColumnInfo": [
> >         {
> >             "Name": "time",
> >             "Type": {
> >                 "ScalarType": "TIMESTAMP"
> >             }
> >         },
> >         {
> >             "Name": "measure_name",
> >             "Type": {
> >                 "ScalarType": "VARCHAR"
> >             }
> >         },
> >         {
> >             "Name": "measure_value::multi",
> >             "Type": {
> >                 "ScalarType": "MULTI"
> >             }
> >         }
> >     ],
> >     ...
> > }
> > ```
> 
> Is there any update on this?

Yes, they recently added the multi-measures support (more details [here](https://discuss.localstack.cloud/t/timestream-multi-measures-support/420/4))

**Comment by perryzjc** [comment]
> > > Hi all! I'm using the latest localstack-pro version (2.1.0) and I'm writing multi-measures records in a timestream table. When I query the measures table, it doesn't return the measures values. Is it possible the multi-measures feature is not supported ?
> > > This is the timestream-write command:
> > > `awslocal timestream-write write-records --database-name test-data-measures --table-name measures --records '[{"Dimensions":[{"Name":"dim_a","Value":"fb2299c6-6b83-418a-b778-9aa74cf534fa"}],"MeasureName":"MY_MEASURE","MeasureValues":[{"Name":"measureValue","Value":"1","Type":"DOUBLE"},{"Name":"start_time","Value":"1684152000000","Type":"TIMESTAMP"}],"MeasureValueType":"MULTI","TimeUnit":"MILLISECONDS","Time":"1684152180000","Version":1686647879684}]'`
> > > This is the timestream-query output:
> > > `# awslocal timestream-query query --query-string 'select * from test-data-measures.measures' --max-items 1` `INFO: Environment variable "AWS_DEFAULT_REGION" will be overwritten by "DEFAULT_REGION"`
> > > ```json
> > > {
> > >     "Rows": [
> > >         {
> > >             "Data": [
> > >                 {
> > >                     "ScalarValue": "2023-05-15 12:03:00.000000000"
> > >                 },
> > >                 {
> > >                     "ScalarValue": "MY_MEASURE"
> > >                 },
> > >                 {
> > >                     "ScalarValue": "True"
> > >                 }
> > >             ]
> > >         }
> > >     ],
> > >     "ColumnInfo": [
> > >         {
> > >             "Name": "time",
> > >             "Type": {
> > >                 "ScalarType": "TIMESTAMP"
> > >             }
> > >         },
> > >         {
> > >             "Name": "measure_name",
> > >             "Type": {
> > >                 "ScalarType": "VARCHAR"
> > >             }
> > >         },
> > >         {
> > >             "Name": "measure_value::multi",
> > >             "Type": {
> > >                 "ScalarType": "MULTI"
> > >             }
> > >         }
> > >     ],
> > >     ...
> > > }
> > > ```
> > 
> > 
> > Is there any update on this?
> 
> Yes, they recently added the multi-measures support (more details [here](https://discuss.localstack.cloud/t/timestream-multi-measures-support/420/4))

Thank you for sharing!
