### ISSUE TITLE
Unable to invoke lambda function compiled in java 11. Localstack latest image still shows java version 8.

### ISSUE THREAD

**Issue by ashameem123** [localstack/localstack#3136]
#2093  # Type of request: This is a ...

[*] bug report
[ ] feature request

# Detailed description
Unable to invoke lambda function compiled in java 11. Localstack latest image still shows java version 8.

## Expected behavior
Should be able to invoke lambda function compiled in java 11.

## Actual behavior
Getting error-
Exception in thread "main" java.lang.UnsupportedClassVersionError: publisFunction has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

# Steps to reproduce

docker-compose up -d
Create lambda function
Create SQS 
map lambda and sqs
send message to SQS to invoke lambda

Error message SS:
![image](https://user-images.githubusercontent.com/54183749/96603894-1a561c00-12ba-11eb-9d40-a19370a7c3aa.png)

![LS_error](https://user-images.githubusercontent.com/54183749/96603954-293cce80-12ba-11eb-9566-3942f96e564a.png)

Similar issue was reported #2093.  Couldn't find the answer if that was fixed and latest image of Localstack should compile in JAVA 11.

**Comment by ashameem123** [comment]
@whummer  , @usmangani1  --> Please have a look

**Comment by ashameem123** [comment]
![image](https://user-images.githubusercontent.com/54183749/97194337-09088600-1778-11eb-9892-235138ff7987.png)

Still facing the same issue.

**Comment by whummer** [comment]
Thanks for reporting @ashameem123 - we already have an open PR for this change (#3166), should get merged soon. Thanks
