### ISSUE TITLE
SES: send_raw_email TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by nsalhaji** [localstack/localstack#314]
Hi all,

I use this amazing stack for a few days ago, awesome job guys.

I'm using SES service from my Java program. All works fine when I'm using the real AWS services but when I switch to Localstack SES I got this error:

File "/usr/local/lib/python3.6/site-packages/moto/ses/responses.py", line 78, in send_raw_email
source = self.querystring.get('Source')[0]
TypeError: 'NoneType' object is not subscriptable

Thanks for you help.

**Comment by julienduchesne** [comment]
Isn't that upstream?

**Comment by nsalhaji** [comment]
Hi @whummer,

Any news about this bug ?

Thanks.

**Comment by tiago-loureiro** [comment]
I also ran into this issue and since it seems to be related to moto, I opened an issue [there](https://github.com/spulec/moto/issues/1421)

**Comment by whummer** [comment]
Thanks for reporting @nsalhaji @tiago-loureiro . This seems to be fixed in the `latest` version - please report here if the problem persists. Thanks

**Comment by bravecobra** [comment]
I just encountered the exact same issue. I am using the `latest` version.
