### ISSUE TITLE
S3 has a memory leak (cp/rm after a while, no space left)

### ISSUE THREAD

**Issue by AlexisWilke** [localstack/localstack#3143]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

Running a test that requires 2,500 files. All would never fit in one LocalStack, so I wrote a script which:

* Copy one file to AWS S3 (localstack).
* Execute a function which makes use of the uploaded file.
* Delete the file.
* Repeat.

## Expected behavior

The delete function (`aws rm file`) should restore the space used by the file before the delete.

## Actual behavior

The amount of memory space used by S3 grows "forever".

# Steps to reproduce

## Command used to start LocalStack

Install LocalStack docker

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

Copy a file, delete it, repeat with **different** files, see that the amount of RAM used by your instance of LocalStack grows forever.

**Comment by AlexisWilke** [comment]
I tried again a week ago with the latest docker version (v0.12.2) and it still leaks for me.

**Comment by whummer** [comment]
Thanks for reporting @AlexisWilke . This should be fixed in #3235 - can you please pull the `latest` image and give it another try? Please report here if the problem persists. Thanks
