### ISSUE TITLE
WebSockets action in payload does not route message to right Lambda handler

### ISSUE THREAD

**Issue by m-chandler** [localstack/localstack#3145]
# Type of request: This is a ...

[ X ] bug report
[ ] feature request

# Detailed description

This bug was initially found via using my own CloudFormation templates, and I've been able to replicate it using the [LockStack Demo: Websockets via API Gateway V2](https://github.com/localstack/localstack-pro-samples/tree/master/serverless-websockets). I've forked this repo and tweaked the example to make highlighting the issue a little easier (link below).

When sending a message to a API Gateway WebSockets API, AWS parse the message as JSON and use the "action" key to determine which Lambda function to invoke. This functionality does not appear to exist in LocalStack, it invokes the wrong function.

## Expected behavior

The "action" key in the WebSocket message payload should determine which handler is invoked.

## Actual behavior

It's unclear what logic LocalStack is using to determine which function to invoke. Perhaps it's simply invoking the first registered function? Perhaps it's random?

In my example repo, the following payload is sent to the websocket API: `{"action":"test-action-two"}`. If you look at serverless.yml, such an action should be handled by handler-two.js.
It seems that any/all actions are handled by the `connect` handler, which is not correct.

# Steps to reproduce

I've forked your LocalStack Pro Examples repo and added a couple of actions to highlight the bug.

https://github.com/m-chandler/localstack-pro-samples/tree/master/serverless-websockets

1. Clone my repo.
2. Install example dependencies (as per original README.md): `make install`
3. Start localstack (I used a docker-compose file, below).
4. Run example `make run`

## Command used to start LocalStack

docker-compose up

docker-compose.yml:
```
version: '2.1'

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "4510:4510"
      - "4571:4571"
      - "4572:4572"
      - "4513:4513"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=${SERVICES- }
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
      - LOCALSTACK_API_KEY=...
      - DEBUG=1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    tmpfs:
      - /tmp/localstack:exec,mode=600
```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

More examples using wscat. All actions are handled by the connect function.

```
C:\Users\User>wscat -c localhost:4513
Connected (press CTRL+C to quit)
> {"action":"test-action"}
< {"error": "Unable to find route for action \"test-action\", API ID \"5db998ad\""}
> {"action":"test-action-one"}
< "{\"handledBy\":\"connect\",\"event\":{\"action\":\"test-action-one\"}}"
> {"action":"test-action-two"}
< "{\"handledBy\":\"connect\",\"event\":{\"action\":\"test-action-two\"}}"
>
```

**Comment by whummer** [comment]
Thanks for the detailed report @m-chandler . There has indeed been a mapping issue between the API integrations and routes of the WebSocket API, when deployed via Serverless/CloudFormation. This issue should be fixed in the `latest` version - can you please do a `docker pull localstack/localstack` and give it another try? Please let us know if the problem persists. Thanks for your help!
