### ISSUE TITLE
WebSockets connect / disconnect routes are not invoked automatically

### ISSUE THREAD

**Issue by m-chandler** [localstack/localstack#3146]
# Type of request: This is a ...

[ X ] bug report
[ ] feature request

# Detailed description

When connecting to / disconnecting from an AWS API Gateway WebSockets API, the Lambda functions routed by $connect / $disconnect are invoked automatically. This is not the case with Localstack. The functions are not invoked.

## Expected behavior

The function mapped to the $connect route should be invoked upon connecct.
The function mapped to the $disconnect route should be invoked upon disconnect.

## Actual behavior

Neither functions are invoked.

# Steps to reproduce

I've forked your LocalStack Pro Examples repo and added a couple of actions to highlight the bug.

https://github.com/m-chandler/localstack-pro-samples/tree/master/serverless-websockets

1. Clone my repo.
2. Install example dependencies (as per original README.md): `make install`
3. Start localstack (I used a docker-compose file, below).
4. Run example `make run`

The example python script in this repo will connect to the websocket API, and then send a payload. If you review the logs, you will see that only a single function was invoked. Two function should have been invoked (one for "connect" and one for "action-two"). This might be confusing, but it actually does invoke the "connect" function, but this is only after you send a payload (and it's actually invoking the wrong function, see my other bug report: https://github.com/localstack/localstack/issues/3145)

## Command used to start LocalStack

docker-compose up

docker-compose.yml:
```
version: '2.1'

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "4510:4510"
      - "4571:4571"
      - "4572:4572"
      - "4513:4513"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=${SERVICES- }
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
      - LOCALSTACK_API_KEY=...
      - DEBUG=1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    tmpfs:
      - /tmp/localstack:exec,mode=600
```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

Connecting via wscat on Windows should trigger the $connect function to be invoked. Disconnecting should trigger the $disconnect function. The Localstack logs indicate that this does not take place.

```
C:\Users\User>wscat -c localhost:4513
Connected (press CTRL+C to quit)
> 
```

**Comment by whummer** [comment]
Thanks for reporting @m-chandler . This should be fixed in the meantime (along with the fix for #3145) - can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists. Thanks for your help!
