### ISSUE TITLE
WebSockets Lambda integration event is not in the correct structure

### ISSUE THREAD

**Issue by m-chandler** [localstack/localstack#3147]
# Type of request: This is a ...

[ X ] bug report
[ ] feature request

# Detailed description

The event provided to the Lambda function via WebSockets integration is incorrect. 

This event should contain important information about the connection (e.g. connection ID, headers, source IP), and the message sent from the connection should be contained in the 'body' property. In LocalStack, the event variable simply contains the message sent from the user - without any of this other information.

## Expected behavior

The event should mirror what is provided by API Gateway.
The message that the user sent should be in the 'body' property of the event object.

## Actual behavior

The event is just the raw message that the user sent. No other details are contained in the event.

# Steps to reproduce

Follow the pro example for WebSockets.
https://github.com/localstack/localstack-pro-samples/tree/master/serverless-websockets
I changed the logging in your example to make it super clear what logged:

```
console.log('event:', JSON.stringify(event));
console.log('context:', JSON.stringify(context));
```

The log entry appears like so, note that the event is just the raw payload sent from the connection. 

```
localstack_main | > START RequestId: a3e6eeb0-0c9b-1a38-be71-6b4ea3d3c3de Version: $LATEST
localstack_main | > 2020-10-21T07:01:43.155Z    a3e6eeb0-0c9b-1a38-be71-6b4ea3d3c3de    INFO    event: {"action":"test-action-two"}
localstack_main | > 2020-10-21T07:01:43.156Z    a3e6eeb0-0c9b-1a38-be71-6b4ea3d3c3de    INFO    context: {"callbackWaitsForEmptyEventLoop":true,"functionVersion":"$LATEST","functionName":"localstack-websockets-local-connectionHandler","memoryLimitInMB":"1536","logGroupName":"/aws/lambda/localstack-websockets-local-connectionHandler","logStreamName":"2020/10/21/[$LATEST]8a96451b8767f80187f71c1d7b29fce7","identity":{},"invokedFunctionArn":"arn:aws:lambda:us-east-1:000000000000:function:localstack-websockets-local-connectionHandler","awsRequestId":"a3e6eeb0-0c9b-1a38-be71-6b4ea3d3c3de"}
localstack_main | > END RequestId: a3e6eeb0-0c9b-1a38-be71-6b4ea3d3c3de
localstack_main | > REPORT RequestId: a3e6eeb0-0c9b-1a38-be71-6b4ea3d3c3de      Init Duration: 2107.40 ms       Duration: 6.40 ms       Billed Duration: 100 ms Memory Size: 1536 MB    Max Memory Used: 0 MB
```

## Command used to start LocalStack

docker-compose up

docker-compose.yml:
```
version: '2.1'

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "4510:4510"
      - "4571:4571"
      - "4572:4572"
      - "4513:4513"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=${SERVICES- }
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
      - LOCALSTACK_API_KEY=...
      - DEBUG=1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    tmpfs:
      - /tmp/localstack:exec,mode=600
```

**Comment by whummer** [comment]
Thanks for reporting @m-chandler . This should be (partially) fixed in the meantime (along with the fix for #3145) - the message is now sent in the `body` property of the event object, and additional metadata attributes have been added. Can you please pull the `latest` Docker image and give it another try? Please let us know if anything important is missing - we'll add more attributes as we go. Thanks for your help!
