### ISSUE TITLE
sqs_listener.py may contain incorrect validation regex

### ISSUE THREAD

**Issue by michaelmccord** [localstack/localstack#3151]
# Type of request: This is a ...

[x ] bug report
[ ] feature request

# Detailed description
As noted in sqs_listener.py [on this line](https://github.com/localstack/localstack/blob/d43a58d563a5a912de64d4e9c8bcac28a96d3857/localstack/services/sqs/sqs_listener.py#L24), the SendMessage endpoint only accepts certain characters as per the AWS documentation. However it appears the regex is missing the carriage return character code.
...

## Expected behavior
The indicated regex would include the carriage return character code.
...

## Actual behavior
It is not included.
...

# Steps to reproduce

Execute a SendMessage request which contains a carriage return in the body

## Command used to start LocalStack
N/A
...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
N/A
...

**Comment by whummer** [comment]
Thanks for reporting @michaelmccord . This should be fixed in #3216 - can you please pull the `latest` Docker image and give it another try? Please report here if the problem persists. Thanks
