### ISSUE TITLE
S3 Access-Control-Allow-Headers - not support custom HEADER

### ISSUE THREAD

**Issue by nsalhaji** [localstack/localstack#316]
Hi guys

I'm using such custom header like, "Content-Disposition", "x-amz-meta-XXX" when uploading file on S3.

When I try to upload from browser to S3, I got this error :
"Request header field x-amz-meta-name is not allowed by Access-Control-Allow-Headers in preflight response."

This error is related to static value of CORS_ALLOWED_HEADERS in generic_proxy.py file.

It cloud be nice if we can have the possibility to add custom CORS configuration setted by:
`awslocal s3api put-bucket-cors --bucket dev-inventory-loader --cors-configuration file://cors.json`

Thanks.

**Comment by nsalhaji** [comment]
Hi @whummer,

Any news about this feature ?

Thanks.

**Comment by whummer** [comment]
Closing as outdated / obsolete. Please open follow-up issues if the problem persists. Thanks
