### ISSUE TITLE
QLDB "documentId" format doesn't match AWS Console "documentId" format

### ISSUE THREAD

**Issue by IvanMigov** [localstack/localstack#3161]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description
I use the latest docker image of localstack. Have a license key.
docker-compose for localstack:
 ```
localstack:
    image: localstack/localstack:latest
    ports:
      - "53:53"
      - "443:443"
      - "4510-4520:4510-4520"
      - "4566-4620:4566-4620"
    env_file: ./docker-compose.env
    environment:
      - SERVICES=qldb
      - PORT_WEB_UI=8080
      - DEBUG=1
      - DATA_DIR=./tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - ./tmp/localstack:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock
```
docker-compose.env contains only one string with localstack api key
`LOCALSTACK_API_KEY=xxxxxxxxxxxxx`
to create ledger i use:
`aws qldb create-ledger --name CATALOG --permissions-mode ALLOW_ALL --endpoint-url=http://localhost:4566 --debug
`
then i connect to qlbd with shell:
`qldbshell -l CATALOG -s http://localhost:4566`

...

## Expected behavior
after i execute insert command i expect to receive documentId in format "KbW0guCaYjd2cAF1OP87oB" as in AWS Console
```
qldbshell > INSERT INTO assets  <<{'assetId': 2, 'title':'AWS EC2 222', 'description':'Amazon Elastic Compute Cloud 222'} >>
INFO: 
{
 documentId: "e4617f98"
}
INFO: (1.5853s)
qldbshell > 
```

...

## Actual behavior
 documentId: "e4617f98"
...

# Steps to reproduce

1. Make sure that you have latest image of localstack with `docker pull localstack/localstack` comand
2. Run localstack container with `docker-compose up -d localstack`
3. install AWS CLI with 
`curl "https://awscli.amazonaws.com/AWSCLIV2.pkg" -o "AWSCLIV2.pkg"` 
` sudo installer -pkg AWSCLIV2.pkg -target /`
4. create ledger with 
`aws qldb create-ledger --name CATALOG --permissions-mode ALLOW_ALL --endpoint-url=http://localhost:4566 --debug
`
5. connect to ledger 
`qldbshell -l CATALOG -s http://localhost:4566`
6. use commands to reproduce bug
`CREATE TABLE assets`

```
INSERT INTO assets
<< {
	'assetId': 4,
    'subTitle':'QLDB',
    'description':'Amazon Quantum Ledger Database'
} >>

```
## Command used to start LocalStack
`docker-compose up -d localstack`
...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
```
aws qldb create-ledger --name CATALOG --permissions-mode ALLOW_ALL --endpoint-url=http://localhost:4566 --debug
qldbshell -l CATALOG -s http://localhost:4566
CREATE TABLE assets
```
...

**Comment by whummer** [comment]
Thanks for reporting @IvanMigov 👍  - this should be fixed in the `latest` version of the Docker image. Please let us know if the problem persists. Thanks for your help.
