### ISSUE TITLE
GetUser is not supported in Localstack Cognito

### ISSUE THREAD

**Issue by msteve-tokzu** [localstack/localstack#3167]
# Type of request: This is a ...

[X] bug report
[ ] feature request

# Detailed description
When using the Amplify SDK, all of the sign in calls use GetUser to fetch the MFA status. Since Localstack does not support GetUser in it's calls (a 500 is thrown with an error message stating getUser is not supported, this makes the Cognito implementation unusable.
...

## Expected behavior
GetUser returns valid user information
...

## Actual behavior
GetUser throws a 500
...

# Steps to reproduce

Perform a getuser call

## Command used to start LocalStack

Started localstack as part of docker compose

```
version: "2.1"
services:
  # Dashboard: https://app.localstack.cloud/dashboard
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack:0.12.0 #5b792b1d1ef2
    ports:
      - "53:53"
      - "443:443"
      - "4510-4520:4510-4520"
      - "4566-4620:4566-4620"
      # - "4571:4571"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY}
      - SERVICES=edge,logs,cloudwatch,cognito,ses,lambda,s3,dynamodb,cloudformation,apigateway,dynamodbstreams,es,iam
      - DEBUG=1
      - LAMBDA_REMOTE_DOCKER=false
      - DEFAULT_REGION=us-east-1
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```
...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

This can be reproduced with the awslocal cognitoidp get-user command but this was initially discovered with the following react typescript snippet:

```
import { Auth } from 'aws-amplify';

type FormData = {
    username: string;
    password: string;
};

const { register, setValue, handleSubmit, errors } = useForm<FormData>();

const onSubmit = handleSubmit(async ({username, password}) => {
        try {
            const user = await Auth.signIn(username, password);
        } catch (error) {
            console.log('error signing in', error);
        }
      });
```

**Comment by msteve-tokzu** [comment]
A quick update here. It looks like the Auth.signIn is actually working but the getUser is going to be required for other Amplify calls so a fix would be much appreciated :)

**Comment by whummer** [comment]
Thanks for reporting @msteve-tokzu . This should be fixed in the meantime - can you please pull the `latest` Docker image and give it another try? Please let us know if this problem persists. Many thanks for your help.

**Comment by msteve-tokzu** [comment]
I tried the latest and then ran into a bunch of issues from what appears to be the moto cloudformation refactor. I'll try this out once I can get past those.
