### ISSUE TITLE
S3 head bucket returns wrong HTTP response since version 0.11.6

### ISSUE THREAD

**Issue by rldw** [localstack/localstack#3178]
# Type of request: This is a ...

[x ] bug report
[ ] feature request

# Detailed description

We have problems running our .NET integration tests against the current LocalStack version `0.11.6`. This problem does not occur with versions `0.11.5` or earlier. The root cause seems to be that a `HEAD` request to a non-existing S3 bucket via the .NET SDK returns a `HTTP 403` instead of a `HTTP 404`. I tried reproducing the problem with the Python boto3 SDK, but in this case LocalStack returns a 404 as expected (see Wireshark image below).

The only difference seems to be that .NET creates a signed request prior to making the `HEAD` request, whereas boto does not. See: https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/S3/MS3UtilDoesS3BucketExistAsyncIS3String.html

`HEAD` requests against LocalStack `0.11.6` with Python (returns 404) and .NET (returns 403) against non-existing buckets:
![Screenshot 2020-10-27 at 10 28 27](https://user-images.githubusercontent.com/11777541/97283232-dcb83c80-183f-11eb-9f7f-17bc039d062c.png)

`HEAD` request against LocalStack `0.11.0` with .NET return propper 404 against a non-existing bucket:
![Screenshot 2020-10-27 at 10 26 33](https://user-images.githubusercontent.com/11777541/97283348-03767300-1840-11eb-8562-43ea4ceb8ffd.png)

## Expected behavior

`HEAD` requests for non-existing S3 buckets should return `HTTP 404`.

## Actual behavior

`HEAD` requests for non-existing S3 buckets return `HTTP 403`.

# Steps to reproduce

## Command used to start LocalStack

`docker run -it -e TEST_AWS_ACCOUNT_ID="000000000000" -e LOCALSTACK_HOSTNAME="localhost" -e DEFAULT_REGION="eu-central-1" -e DEBUG="1" --rm --privileged --name localstack_main -p 4566-4621:4566-4621 -p 8080-8081:8080-8081  -v "/private/var/folders/kf/fn860qbx42s3mvz56fv0qr5r0000gn/T/localstack:/tmp/localstack" -v "/var/run/docker.sock:/var/run/docker.sock" -e DOCKER_HOST="unix:///var/run/docker.sock" -e HOST_TMP_FOLDER="/private/var/folders/kf/fn860qbx42s3mvz56fv0qr5r0000gn/T/localstack" "localstack/localstack"`

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

.NET snippet:
```
_s3Client.DoesS3BucketExistAsync("test-via-dotnet-sdk-" + DateTime.Now.Ticks.ToString())
```

Python snippet:
```
_s3Client.head_bucket(Bucket="test-via-python-boto3")
```

**Comment by macnev2013** [comment]
Thanks for reporting @rldw . Is it possible to provide a small git repository with compilation/running instructions to reproduce the issue ?
Thanks.

**Comment by macnev2013** [comment]
Quick update @rldw . We have made significant changes in the signature calculation for S3.
Can you please give it a try using aws credentials as `AWS_ACCESS_KEY_ID=test` and `AWS_SECRET_ACCESS_KEY=test`.
You can refer the documentation [here](https://github.com/localstack/localstack/blob/master/README.md#setting-up-local-region-and-credentials-to-run-localstack). Thanks.

**Comment by rldw** [comment]
Hey @macnev2013, indeed setting `AWS_ACCESS_KEY_ID=test` and `AWS_SECRET_ACCESS_KEY=test` as credentials solved the issue for us. Thanks for the quick reply and updating the docs for future reference.
