### ISSUE TITLE
WebSockets Add Missing Attributes

### ISSUE THREAD

**Issue by m-chandler** [localstack/localstack#3186]
# Type of request: This is a ...

[ ] bug report
[ x ] feature request

# Detailed description

Please refer to https://github.com/localstack/localstack/issues/3147 for background information. Thank you for all your help so far! The message is now in the correct structure, so I have created this issue as a feature request to ask for additional attributes to be added to the event.

Note that the attributes I'm requesting differ for the $connect handler vs user defined route handlers (as per AWS).

Full examples of each AWS event are below.

What I'm hoping for is:
- Headers (upon connect only, under the key: `headers`).
- A connection ID to refer to in all events: `requestContext.connectionId`. I understand this might be difficult depending on how complete the websockets implementation is. In order to send messages to websocket connections you're supposed to call `aws apigatewaymanagementapi post-to-connection --endpoint-url https://your.api.com --connection-id ABCXYZ --data somedata`. I understand this is possibly a completely separate feature request, and as such it might not be possible to provide this connection ID. Please let me know if I should log another request.

### Example events for your reference

_Connect Event_

```
{
    "headers": {
        "Host": "custom.domain.com",
        "Sec-WebSocket-Extensions": "permessage-deflate; client_max_window_bits",
        "Sec-WebSocket-Key": "xxxxxxxxxxxxxxxxxxxxxxxx",
        "Sec-WebSocket-Version": "13",
        "X-Amzn-Trace-Id": "Root=1-xxxxxxxx-xxxxxxxxxxxxxxxxxxxxxxxx",
        "X-Forwarded-For": "111.111.111.111",
        "X-Forwarded-Port": "443",
        "X-Forwarded-Proto": "https"
    },
    "multiValueHeaders": {
        "Host": [
            "custom.domain.com"
        ],
        "Sec-WebSocket-Extensions": [
            "permessage-deflate; client_max_window_bits"
        ],
        "Sec-WebSocket-Key": [
            "xxxxxxxxxxxxxxxxxxxxxxxx"
        ],
        "Sec-WebSocket-Version": [
            "13"
        ],
        "X-Amzn-Trace-Id": [
            "Root=1-xxxxxxxx-xxxxxxxxxxxxxxxxxxxxxxxx"
        ],
        "X-Forwarded-For": [
            "111.111.111.111"
        ],
        "X-Forwarded-Port": [
            "443"
        ],
        "X-Forwarded-Proto": [
            "https"
        ]
    },
    "requestContext": {
        "routeKey": "$connect",
        "messageId": null,
        "eventType": "CONNECT",
        "extendedRequestId": "xxxxxxxxxxxxxxxx",
        "requestTime": "27/Oct/2020:22:35:42 +0000",
        "messageDirection": "IN",
        "stage": "test",
        "connectedAt": 1603838142167,
        "requestTimeEpoch": 1603838142168,
        "identity": {
            "cognitoIdentityPoolId": null,
            "cognitoIdentityId": null,
            "principalOrgId": null,
            "cognitoAuthenticationType": null,
            "userArn": null,
            "userAgent": null,
            "accountId": null,
            "caller": null,
            "sourceIp": "111.111.111.111",
            "accessKey": null,
            "cognitoAuthenticationProvider": null,
            "user": null
        },
        "requestId": "xxxxxxxxxxxxxxxx",
        "domainName": "custom.domain.com",
        "connectionId": "xxxxxxxxxxxxxxxx",
        "apiId": "xxxxxxxxxx"
    },
    "isBase64Encoded": false
}
```

*User Defined Route Event (e.g. "my-handler")*

```
{
    "requestContext": {
        "routeKey": "my-handler",
        "messageId": "xxxxxxxxxxxxxxxx",
        "eventType": "MESSAGE",
        "extendedRequestId": "xxxxxxxxxxxxxxxx",
        "requestTime": "27/Oct/2020:22:45:44 +0000",
        "messageDirection": "IN",
        "stage": "test",
        "connectedAt": 1603838743419,
        "requestTimeEpoch": 1603838744757,
        "identity": {
            "cognitoIdentityPoolId": null,
            "cognitoIdentityId": null,
            "principalOrgId": null,
            "cognitoAuthenticationType": null,
            "userArn": null,
            "userAgent": null,
            "accountId": null,
            "caller": null,
            "sourceIp": "111.111.111.111",
            "accessKey": null,
            "cognitoAuthenticationProvider": null,
            "user": null
        },
        "requestId": "xxxxxxxxxxxxxxxx",
        "domainName": "custom.domain.com",
        "connectionId": "xxxxxxxxxxxxxxxx",
        "apiId": "xxxxxxxxxx"
    },
    "body": "{\"someproperty\":\"somevalue\"}",
    "isBase64Encoded": false
}
```

**Comment by whummer** [comment]
Thanks for reporting @m-chandler - additional/missing attributes have been added to the websocket events, the change should be available in the `latest` version. The second point you raised (regarding `aws apigatewaymanagementapi post-to-connection`) is not yet supported, but will be added shortly. Please let us know if the problem persists or if any key attributes are missing. Thanks for your help.

**Comment by m-chandler** [comment]
@whummer Thank you, looking good.
I have a couple of other requests; I'll log separate issues for these (including the post-to-connection request).
