### ISSUE TITLE
Any way to override a service port after #2905?

### ISSUE THREAD

**Issue by mxxk** [localstack/localstack#3187]
# Type of request: This is a ...

[ ] bug report
[ ] feature request
[x] request for clarification

# Detailed description

As a follow-up to #2230, now that #2905 made all services default to listen only on the `EDGE_PORT`, is there any way to explicitly override the service port? For S3, for example, here are the variations tried:

- `SERVICES=s3:10003`
- `S3_PORT=10003`
- `S3_PORT_EXTERNAL=10003`

While the first variant using `SERVICES` is no longer documented in `README.md`, it would seem that `S3_PORT_EXTERNAL` would be respected by LocalStack:

> - `<SERVICE>_PORT_EXTERNAL`: Port number to expose a specific service externally (defaults to service ports above). `SQS_PORT_EXTERNAL`, for example, is used when returning queue URLs from the SQS service to the client.
39b2784e97e54a48a37a8d7afb858b2d4e2dee51

Source: [`README.md@39b2784`](https://github.com/localstack/localstack/blob/39b2784e97e54a48a37a8d7afb858b2d4e2dee51/README.md#configurations)

## Expected behavior

The `docker run` command below would show:

<pre>
Starting edge router (https port 4566)...
Starting mock S3 service on http port <b>10003</b> ...
</pre>

## Actual behavior

The `docker run` command below shows:

<pre>
Starting edge router (https port 4566)...
Starting mock S3 service on http port <b>4566</b> ...
</pre>

# Steps to reproduce

## Command used to start LocalStack

```
docker run --rm -e SERVICES=s3:10003 -e S3_PORT=10003 -e S3_PORT_EXTERNAL=10003 localstack/localstack:0.12.1
```

**Comment by whummer** [comment]
Thanks for reporting @mxxk . As you mentioned, any recent and future releases of LocalStack are using a central edge port (`4566` by default) for all services. We are going to update the documentation in the README to properly reflect this. Please note that the `<SERVICE>_PORT_EXTERNAL` is only used to construct URLs that will be returned to the client (e.g., when operating behind a custom proxy), but this does not change the configuration of the edge port per se. Thanks
