### ISSUE TITLE
CloudFormation does not handle Existing resources on persistent stack

### ISSUE THREAD

**Issue by kellertobias** [localstack/localstack#3191]
# Type of request:
[x] bug report
[ ] feature request

# Detailed description
when I start localstack with persistence turned on and do an update of a stack, that I created before the restart, I get errors on already existing buckets (that were created within this stack and have not been changed):

```
[LOCALSTACK] 2020-10-28T13:22:43:INFO:localstack.services.cloudformation.cloudformation_starter: Error on moto CF resource creation. Ignoring, as should_be_created=False: 409 Conflict: <?xml version="1.0" encoding="UTF-8"?>
[LOCALSTACK] <Error>
[LOCALSTACK]     <Code>BucketAlreadyExists</Code>
[LOCALSTACK]     <Message>The requested bucket name is not available. The bucket namespace is shared by all users of the system. Please select a different name and try again</Message>
[LOCALSTACK]     <BucketName>bitpub-local</BucketName>
[LOCALSTACK]     <RequestID>7a62c49f-347e-4fc4-9331-6e8eEXAMPLE</RequestID>
[LOCALSTACK] </Error>
```

my template is:

```
{
    "AWSTemplateFormatVersion": "2010-09-09",
    "Description": "...",
    "Resources": {
        "S3BucketPub": {
            "Type": "AWS::S3::Bucket",
            "Properties": {
                "AccessControl": "PublicRead",
                "CorsConfiguration": {
                    "CorsRules": [
                        {
                            "AllowedHeaders": [
                                "*"
                            ],
                            "AllowedOrigins": [
                                "*"
                            ],
                            "MaxAge": 3000,
                            "AllowedMethods": [
                                "PUT",
                                "POST",
                                "GET",
                                "HEAD"
                            ]
                        }
                    ]
                },
                "BucketName": "test-local",
                "BucketEncryption": {
                    "ServerSideEncryptionConfiguration": [
                        {
                            "ServerSideEncryptionByDefault": {
                                "SSEAlgorithm": "AES256"
                            }
                        }
                    ]
                }
            }
        },
        "S3PolicyPub": {
            "Type": "AWS::S3::BucketPolicy",
            "Properties": {
                "Bucket": "test-local",
                "PolicyDocument": {
                    "Statement": [
                        {
                            "Effect": "Allow",
                            "Principal": "*",
                            "Action": "s3:GetObject",
                            "Resource": "arn:aws:s3:::bitpub-local/*"
                        }
                    ]
                }
            }
        }
    },
    "Outputs": {
        "OUTBucketPub": {
            "Value": {
                "Ref": "S3BucketPub"
            },
            "Description": "BUCKET_PUB",
            "Export": {
                "Name": "BUCKET_PUB"
            }
        }
    }
}
```

However the error does not consistently appear.

## Expected behavior
I start localstack with persistence enabled and apply a CFN Template. If I then restart localstack and reapply the exact same template, it should say that nothing is to do (just like AWS does).

## Actual behavior
Sometimes, I get an error that the bucket already exists, when I restart the local stack and reapply the CF template.

# Steps to reproduce
* start localstack with persistence on
* create stack with empty template
* update stack with template
* restart local stack
* update stack with same template
* get error that bucket already exists

## Command used to start LocalStack
```
DEFAULT_REGION=eu-central-1 LAMBDA_REMOTE_DOCKER=false DATA_DIR=/tmp/localstack/data SERVICES=s3,ses,sqs,sns,lambda,cloudformation,cloudwatch,logs,secretmanager,iam,stepfunctions localstack start --docker
```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
with the template above:

```python
def create_stack():
    stack = cf.create_stack(
        StackName=STACK_NAME,
        TemplateBody=json.dumps({
            "AWSTemplateFormatVersion": "2010-09-09",
            "Description": "...",
            "Resources": {}}
        , indent=4)
    )

def update_stack(template):
    stack = cf.update_stack(
        StackName=STACK_NAME,
        TemplateBody=template 
    )

    pprint(cf.list_stack_resources(StackName=STACK_NAME))
    pprint(cf.describe_stacks(StackName=STACK_NAME))

template = ...

create_stack()
update_stack(template)

# restart localstack

update_stack(template)
```

┆Issue is synchronized with this [Jira Task](https://localstack.atlassian.net/browse/LOC-75) by [Unito](https://www.unito.io/learn-more)

**Comment by msteve-tokzu** [comment]
I'm not a localstack dev but pretty heavy infra as code advocate and, as a result, Cloudformation is my bread and butter (well now the CDK :)).

Cloudformation in localstack uses moto behind the scenes and this doesn't have persistence built in. More than likely the localstack team will probably need to put this on the feature backlog to support it. Moto's cf support also went through a pretty large refactor and this seems to have also broken a few things that the localstack team actually went in and fixed for them (Thanks!).

Also, a bit annoyingly, DescribeStacks is also not supported so I've had to work around this.

For me, what my workflow is for dev, is to tear everything down and rebuild it on restart. I do an `rm -rf` on the data directory so things are always clean. I mean, as annoying as this is, I at least know that I have a repeatable environment.

If anything, it might be worthwhile to look into adding persistence to the moto stack but this might be a bit of a charged topic since the intent of moto is really around testing... and persistence can cause all sorts of odd automated test failures when used improperly.

**Comment by kellertobias** [comment]
@msteve-tokzu as we want to use localstack to mock AWS services not only for testing, but mainly for local developlemt, it is quite crucial to have a persistent storage of at least Objects in S3 Buckets and being able to reference them within the CF Template.
