### ISSUE TITLE
Cognito won't start by docker-compose.yml

### ISSUE THREAD

**Issue by bakupen** [localstack/localstack#3197]
# Type of request: This is a ...

[ X ] bug report
[ ] feature request

# Detailed description

Docker : 19.03.13
OS : MacOS Catalina 10.15.6

I want to use coginto's create_user_pool, but I get this message and I can't create the user.

`WARNING:localstack.utils.server.http2_server: Error in proxy handler for request POST http://localhost:4566/: Unable to find listener for service "cognito-idp" - please make sure to include it in $SERVICES Traceback (most recent call last):`

I checked and the cognito service is not running.

```
$ curl http://localhost:4566/health
{"services": {"dynamodbstreams": "running", "es": "running", "kinesis": "running", "s3": "running", "ses": "running", "sqs": "running", "ssm": "running", "dynamodb": "running"}}(pyenv)
```

The docker-compose.yml contains a cognito boot instruction.
This worked in March of this year.

...

## Expected behavior
cognito is running

...

## Actual behavior
cognito is not running

...

# Steps to reproduce

## Command used to start LocalStack

docker-compose.yml

```
version: '3.3'
services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
      - "8080:8080"
    environment:
      - SERVICES=dynamodb,cognito,ssm,sqs,es,s3,ses
      - DEFAULT_REGION=ap-northeast-1
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY}
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

test.py

```
cognito = boto3.client('cognito-idp', endpoint_url='http://localhost:4566/')
response = cognito.create_user_pool(	
    PoolName='staff',	
    Policies={	
        'PasswordPolicy': {	
            'MinimumLength': 8,	
            'RequireUppercase': True,	
            'RequireLowercase': True,	
            'RequireNumbers': True,	
            'RequireSymbols': False	
        }	
    },	
    AliasAttributes=[	
        'preferred_username'	
    ],	
    AdminCreateUserConfig={	
        'AllowAdminCreateUserOnly': True,	
        'UnusedAccountValidityDays': 7,	
    },	
    Schema=[	
        {	
            'Name': 'email',	
            'AttributeDataType': 'String',	
            'DeveloperOnlyAttribute': False,	
            'Mutable': True,	
            'Required': True,	
        },	
    ]	
)
```
...

**Comment by whummer** [comment]
Thanks for reporting @bakupen . Can you please get in touch with us directly (via email, Slack) - this might be an issue with your API key, we'll be happy to look into it. Thanks for your help!

**Comment by SantiagoAndre** [comment]
hello, i  have the same error, still not solved?

**Comment by bakupen** [comment]
Hi @SantiagoAndre .
This matter has been resolved.

I was using the wrong API key.
The correct key is written in the console under "Account > Subscriptions".
If you click on "Pro Edition" in Active Subscriptions, "Subscription Details" will appear and you can see the key.

(Sorry if the machine translation is hard to read...)
