### ISSUE TITLE
S3 upload Crashes on wrong date format in STS Temporary Credentials (xxx does not match format yyy)

### ISSUE THREAD

**Issue by kellertobias** [localstack/localstack#3199]
# Type of request: This is a ...
[x] bug report
[ ] feature request

# Detailed description
When I use slingshot uploader with STS temporary credentials, I get an error that the timestamp didn't match the format

```
2020-10-29T17:49:00:WARNING:bootstrap.py: Thread run method <function AdaptiveThreadPool.submit.<locals>._run at 0x7fec31435ca0>(None) failed: time data '2020-10-29T17:54:00.532Z' does not match format '%Y-%m-%dT%H:%M:%SZ' Traceback (most recent call last):
```

however, the AWS Documentation states that this format (%Y-%m-%dT%H:%M:%S.%IZ) is correct (https://docs.aws.amazon.com/STS/latest/APIReference/API_GetSessionToken.html)

## Expected behavior
Should not crash when uploading stuff to S3 with temporary credentials

## Actual behavior
crashes

possible solution would be to allow both formats here:
https://github.com/localstack/localstack/blob/669b7ab767c85b1031ecdc49602160f5d61423f8/localstack/services/s3/s3_listener.py#L1094

┆Issue is synchronized with this [Jira Task](https://localstack.atlassian.net/browse/LOC-73) by [Unito](https://www.unito.io/learn-more)

**Comment by usmangani1** [comment]
@kellertobias Thanks for reporting the issue.

Can you please help with some sample aws commands using which we can reproduce the issue ? This will help us resolve the issue sooner.Thanks

**Comment by whummer** [comment]
Thanks for reporting @kellertobias . This should be fixed in the meantime - can you please pull the `latest` Docker image and give it another try? Please report here if the problem persists. Thanks!
