### ISSUE TITLE
Cognito PostConfirmation trigger is not called if the user is confirmed in the PreSignup trigger

### ISSUE THREAD

**Issue by limenutt** [localstack/localstack#3200]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

I have 3 triggers for Cognito user pool defined:
```
{
    "UserPools": [
        {
            "Id": "ap-southeast-2_54f5adc2fca3473f9a30629fbf103f97",
            "Name": "userpool",
            "LambdaConfig": {
                "PreSignUp": "arn:aws:lambda:ap-southeast-2:000000000000:function:preSignUp",
                "PostConfirmation": "arn:aws:lambda:ap-southeast-2:000000000000:function:postConfirmation",
                "PreTokenGeneration": "arn:aws:lambda:ap-southeast-2:000000000000:function:preTokenGeneration"
            },
            "LastModifiedDate": 1604020862.0,
            "CreationDate": 1604020862.0
        }
    ]
}
```
PreSignUp trigger just confirms the user like so
```
export const preSignUpHandler: Handler<
  CognitoUserPoolTriggerEvent,
  CognitoUserPoolTriggerEvent
> = async (event, _context) => {
  event.response.autoConfirmUser = true;
  return event;
};
```

## Expected behavior

PostConfirmation trigger called after the PreSignup trigger is called

## Actual behavior

PreSignup trigger is called twice, PostConfirmation trigger never called

# Steps to reproduce
See snippets above.
I'm also able to call PostConfirmation lambda function directly with awslocal with no problems.
The issue is that it's not being called by localstack as a Cognito trigger.
When deployed to AWS both triggers are called correctly.

## Command used to start LocalStack

docker-compose, localstack version *0.12.1*

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

...

**Comment by whummer** [comment]
Thanks for reporting @limenutt . This should be fixed in the `latest` version - can you please pull the Docker image and give it another try? Please report here if the problem persists. Many thanks for your help!

**Comment by limenutt** [comment]
@whummer , I can confirm that the post-confirmation trigger is now called, but it is called with an incorrect event payload, e.g, it is missing `sub` property of the user details. Please make sure the trigger is called with the same payload as we receive in AWS.
