### ISSUE TITLE
Cognito userpool error response structure doesn't match the AWS error structure

### ISSUE THREAD

**Issue by limenutt** [localstack/localstack#3201]
# Type of request: This is a ...
[x] bug report
[ ] feature request

# Detailed description
During the exceptional situations like username is not found or the password is incorrect during the authentication, Cognito service returns errors with the detailed description of the error so that the client application is then able to turn those errors into actionable messages for the users.

## Expected behavior
Error responses and messages are **exactly** the same as AWS.

## Actual behavior
Error responses are missing headers and have the incorrect spelling of the response body properties and therefore could not be correctly handled by the official Cognito client libraries (aws-amplify)

#### from AWS:
```
Headers:
x-amzn-errormessage: Incorrect username or password.
x-amzn-errortype: NotAuthorizedException:
x-amzn-requestid: 55ae2950-3096-48c8-9bf7-86940cf27c27
Body:
{"__type":"NotAuthorizedException","message":"Incorrect username or password."}
```

#### from Localstack
```
x-amzn* headers:
x-amzn-errortype: Exception
Body:
{"Type": "User", "message": "Failed login attempt (invalid signature)."}
```

#### from AWS
```
x-amzn* headers:
x-amzn-errormessage: User does not exist.
x-amzn-errortype: UserNotFoundException:
x-amzn-requestid: 55ae2950-3096-48c8-9bf7-86940cf27c27
Body:
{"__type":"UserNotFoundException","message":"User does not exist."}
```

#### from Localstack
```
x-amzn* headers:
x-amzn-errortype: ResourceNotFoundException
Body:
{"Type": "User", "message": "Cannot find resource: Unable to find user object for username alias \"ma11@skychute.com.au\""}
```

# Steps to reproduce
Try different exception situations with Cognito in Localstack and the same situations with Cognito in AWS and you'll see the difference in the responses.

## Command used to start LocalStack
docker-compose, version 0.12.1

┆Issue is synchronized with this [Jira Task](https://localstack.atlassian.net/browse/LOC-72) by [Unito](https://www.unito.io/learn-more)

**Comment by whummer** [comment]
Thanks for the detailed report @limenutt . This should be fixed in the `latest` version - can you please pull the Docker image and give it another try? Please report here if the problem persists. Also, you mentioned that there are some Amplify libraries that depend on the exact format of these error messages - do you think you can share a small sample snippet with us, to help us reproduce this issue? Many thanks for your help!

**Comment by limenutt** [comment]
@whummer , I've checked some error responses and some look correct (e.g. the two responses I mentioned in the issue). However, we don't get anything in response when the lambda trigger failed (for example, when pre-token generation trigger has failed during the log in). Please refer how AWS responds in this situation.

**Comment by whummer** [comment]
Closing as outdated, should be fixed in the meantime..
