### ISSUE TITLE
WebSockets API without "default" route prevents all other routes from working

### ISSUE THREAD

**Issue by m-chandler** [localstack/localstack#3210]
# Type of request: This is a ...

[ X ] bug report
[ ] feature request

# Detailed description

If the "$default" route is not specified, no other routes work.

This is probably fairly low priority as there is a simple workaround (just define a $default route), Having said this, the route is not required in AWS' API Gateway implementation. Ideally LocalStack would mirror this functionality.

_Thank you for your continued support, much appreciated._

## Expected behavior

The "$default" route is optional in AWS. If you do not specify this route, the other routes should still function.

## Actual behavior

If you do not specify the "$default" route, no other routes can be found. Messages like so appear in the logs:

```
localstack_main | 2020-11-03T01:00:48:INFO:localstack_ext.services.apigateway.apigateway_extended: Unable to find route for action "$connect", API ID "45d6fafa"
```

# Steps to reproduce

Please refer to LocalStack Pro example:
https://github.com/localstack/localstack-pro-samples/blob/master/serverless-websockets/serverless.yml

Remove / comment out the following lines:

```
  defaultHandler:
    handler: handler.handler
    events:
      - websocket:
          route: $default
```

Follow LocalStack Pro example instructions, you should notice the below error in the logs:

```
localstack_main | 2020-11-03T01:00:48:INFO:localstack_ext.services.apigateway.apigateway_extended: Unable to find route for action "$connect", API ID "45d6fafa"
```

**Comment by whummer** [comment]
Thanks for reporting @m-chandler . This should be fixed in the meantime - can you please pull the `latest` image and give it another try? Please let us know if the problem persists. Many thanks for your help!

**Comment by m-chandler** [comment]
Hi @whummer, the issue still appears to persist.

As an aside, I can no longer deploy the Localstack Pro Example template I linked earlier. I've updated the installed npm packages, but sadly it will no longer deploy. That's a separate issue. I've got my own CloudFormation template that I'm using, but I prefer to use your examples as they're probably more familiar to you.

I've made a CloudFormation version of your serverless example that highlights the issue:
https://drive.google.com/file/d/1S26FVLu109ev122CkZtcOM2ur_drJ9me/view?usp=sharing

If you diff the two JSON CloudFormation template, you'll see the only difference is the existence / lack of the $default route.

To show that everything works **with** the $default route:
1. Start up localstack.
2. Run the script `deploy-default.sh` in my example. This should log the websockets API endpoint to console.
3. Connect to the websockets API endpoint (I use wscat). You will see in the logs that the $connect route was invoked.

To show that nothing works **without** the $default route:
1. Kill localstack started earlier (best to have a clean slate).
2. Start up localstack.
3. Run the script `deploy-no-default.sh` in my example. This should log the websockets API endpoint to console.
4. Connect to the websockets API endpoint (I use wscat). You will see no logs indicating that the $connect route was invoked. You can also try to invoke the "test-action" by sending `{"action":"test-action"}` from the wscat client. This yields the `Unable to find route for action \"test-action\"` error.

**Comment by m-chandler** [comment]
Hmm..

Sorry if this is a separate bug, but it certainly seems related.

I think the default route is still trumping all other routes? I don't know if this is a bug that's been reintroduced, but now it seems that every action is being handled by the $default handler.

Using my example:

1. Deploy via the script `deploy-default.sh`.
2. Connect to the websockets endpoint (via wscat or similar).
3. Review the logs, you'll note that the $default handler is being invoked, rather than the $connect handler: `localstack_main   | 2020-11-11T06:41:47:DEBUG:localstack.services.awslambda.lambda_executors: Lambda arn:aws:lambda:ap-southeast-2:000000000000:function:localstack-websockets-local-defaultHandler result / log output:`
4. If you close the wscat connection, again - you'll note that defaultHandler is invoked rather than the $disconnect handler.

**Comment by whummer** [comment]
Thanks for the update and for providing the comprehensive example @m-chandler . Can you please give it another try with the `latest` Docker image - looks like the sample you've shared on Google drive now works with the latest version (i.e., calls the `$connect` route when running deploy-no-default.sh). Many thanks for your help.

**Comment by m-chandler** [comment]
All looks good thank you!
