### ISSUE TITLE
WebSockets API implementation should support custom headers

### ISSUE THREAD

**Issue by m-chandler** [localstack/localstack#3211]
# Type of request: This is a ...
[ ] bug report
[ X ] feature request

# Detailed description
The localstack API Gateway WebSockets API implementation should support custom headers.

There's probably some good background here: https://github.com/localstack/localstack/issues/3186

API Gateway supports custom headers for WebSocket connections.

## Expected behavior
When you connect to an AWS API Gateway WebSockets API (for example with wscat) `wscat -c localhost:4513 -H CustomHeader:CustomValue`, the custom headers are made available within the `headers` property of the event object. 

## Actual behavior
The custom headers do not appear in the `headers` property.

I understand that headers have only recently been added (yesterday). I suspect these custom headers are simply not yet supported.

# Steps to reproduce
Refer to earlier issue. The event (and headers) are logged to console: https://github.com/localstack/localstack/issues/3147

┆Issue is synchronized with this [Jira Task](https://localstack.atlassian.net/browse/LOC-68) by [Unito](https://www.unito.io/learn-more)

**Comment by whummer** [comment]
Thanks for reporting @m-chandler . This should be fixed in the meantime - can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists. Thanks for your help!

**Comment by m-chandler** [comment]
Hi @whummer thanks, I can see the custom headers coming through!
One problem I did note is that it threw an exception when connecting via `wscat` (with or without any headers):
`KeyError: 'user-agent'`
If I provide this header when connecting, it works as expected. This header shouldn't be required though (i.e. it isn't in AWS' implementation). I'll leave the ticket open, but this is good enough for me at this point.

**Comment by whummer** [comment]
Thanks for confirming @m-chandler - the `'user-agent'` issue should also be fixed on `latest` in the meantime. Please let us know if there are any other issues. Thanks
