### ISSUE TITLE
WebSockets API management API

### ISSUE THREAD

**Issue by m-chandler** [localstack/localstack#3212]
# Type of request: This is a ...

[ ] bug report
[ X ] feature request

# Detailed description

I know you're already aware of this (I mentioned this briefly in an earlier issue: https://github.com/localstack/localstack/issues/3186). I closed the other issue as it had a different focus, felt it best to keep this feature request separate.

When users connect to an AWS API Gateway Websockets API they are assigned a connection ID. You may then manage this connection (post messages, disconnect) via the API Gateway Management API.

e.g. `aws apigatewaymanagementapi post-to-connection --endpoint-url https://your.api.com --connection-id ABCXYZ --data somedata`

At the moment (as you are aware), in localstack users are not assigned a "connection ID" (under the `request.connectionId` property in the event). Given this is missing, presumably the API Gateway Management API implementation is incomplete.

## Expected behavior

Websocket connections should be assigned a "connection ID" (set in the `request.connectionId` property of the event) which can be used via the API Gateway Management API to post messages to the connection.

## Actual behavior

Connections are not assigned a connection ID.

**Comment by whummer** [comment]
Thanks for reporting @m-chandler . This should be available in the meantime - can you please try again after pulling the `latest` Docker image? The `connectionId` is now propagated in the metadata of the Lambda event received from the WebSocket, and this connection ID can be used in an `aws apigatewaymanagementapi post-to-connection ...` API call. Hope that help - please keep us posted if there are any issues. Thanks for your help!

**Comment by m-chandler** [comment]
@whummer it works, thanks!
It works good enough at this stage, it does still deviate from AWS however the difference isn't critical for me so I don't need to annoy you any further about it.
