### ISSUE TITLE
DynamoDB tables are not scoped to the region in which they're created

### ISSUE THREAD

**Issue by m-chandler** [localstack/localstack#3213]
# Type of request: This is a ...

[ X ] bug report
[ ] feature request

# Detailed description

It seems that if you create a table in one region, that same table is "created" in every region with the data shared between regions.

Example further below.

This would make creating table with the same name in different regions impossible, as they'd share the same data.

## Expected behavior

DynamoDB tables should be scoped to a particular region. You should be able to create a "Music" table in ap-southeast-2, and then create a completely separate "Music" table in us-east-1.

Other services in localstack don't exhibit this behaviour. If you create a CloudFormation stack in one region, it does not exist in another region.

## Actual behavior

Creating a table results in it being accessible in every region - with the same underlying data shared between all regions.

# Steps to reproduce

Create your table.

```
awslocal dynamodb create-table \
    --table-name Music \
    --attribute-definitions \
        AttributeName=Artist,AttributeType=S \
        AttributeName=SongTitle,AttributeType=S \
    --key-schema \
        AttributeName=Artist,KeyType=HASH \
        AttributeName=SongTitle,KeyType=RANGE \
--provisioned-throughput \
        ReadCapacityUnits=10,WriteCapacityUnits=5 \
--region ap-southeast-2
```

Verify that it exists in the region you created it in:

`awslocal dynamodb describe-table --table-name Music --region ap-southeast-2`

Output is as expected:

```
{
    "Table": {
        ...
        "TableArn": "arn:aws:dynamodb:ap-southeast-2:000000000000:table/Music"
    }
}
```

Check if it exists in any other region:

`awslocal dynamodb describe-table --table-name Music --region us-east-1`

The following error is expected: `An error occurred (ResourceNotFoundException) when calling the DescribeTable operation: Cannot do operations on a non-existent table`

Instead, the following response is returned:

```
{
    "Table": {
        ...
        "TableArn": "arn:aws:dynamodb:us-east-1:000000000000:table/Music"
    }
}
```

## Command used to start LocalStack

`docker-compose up`

docker-compose.yml

```
version: '2.1'

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "4510:4510"
      - "4571:4571"
      - "4572:4572"
      - "4513:4513"
      - "4514:4514"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=${SERVICES- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
      - LOCALSTACK_API_KEY=...
      - DEBUG=1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    tmpfs:
      - /tmp/localstack:exec,mode=600
```

**Comment by whummer** [comment]
Thanks for reporting @m-chandler . This should be fixed in the meantime - can you please pull the `latest` Docker image and give it another try? Please report here if the problem persists. Thanks for your help.

**Comment by vijayopensource** [comment]
till having same issue. Create Music table in one region, is then available in all. This is accepted behaviour in localstack.

**Comment by whummer** [comment]
Hi @vijayopensource , I'm unable to replicate this issue with the latest version of LocalStack.

Creating a table in region `ap-southeast-2`:
```
$ awslocal dynamodb create-table \
    --table-name Music \
    --attribute-definitions \
        AttributeName=Artist,AttributeType=S \
        AttributeName=SongTitle,AttributeType=S \
    --key-schema \
        AttributeName=Artist,KeyType=HASH \
        AttributeName=SongTitle,KeyType=RANGE \
--provisioned-throughput \
        ReadCapacityUnits=10,WriteCapacityUnits=5 \
--region ap-southeast-2
```
Listing tables for region `ap-southeast-2`:
```
$ awslocal dynamodb list-tables --region ap-southeast-2
{
    "TableNames": [
        "Music"
    ]
}
```
Listing tables for region `us-east-1`:
```
$ awslocal dynamodb list-tables --region us-east-1
{
    "TableNames": []
}
```

Can you please do a `docker pull localstack/localstack` and see if you can replicate these results? Thanks

**Comment by ghilainm** [comment]
Same issue here with the latest version of localstack.
