### ISSUE TITLE
Consecutive executions of lambda if lambda executes more than 1 minute

### ISSUE THREAD

**Issue by amitheda** [localstack/localstack#3217]
# Type of request: This is a ...
[x] bug report
[ ] feature request

# Detailed description
I used localstack docker image version 0.11.5 and  LAMBDA_EXECUTOR=docker.
I am running a simple nodejs 12.x lambda whose execution time is 9 minutes.

## Expected behavior
Lambda function should run only once.
...

## Actual behavior
It launches the single docker container for invoking lambda. But after the 1 minute, it launches 5-6 other docker containers to execute the same lambda function.

**Note**  If execution time is less than 1 minute it runs only once.
...

# Steps to reproduce
1.  **index,js**

```
exports.handler = async function(event, context) {
  function wait() {
    return new Promise((resolve, reject) => {
      setTimeout(() => resolve('hello'), 500000);
    });
  }

  console.log(await wait());

  return 'exiting';
};
```

1. Create and invoke a lambda function.
1. Check the localstack logs  -  docker logs -f {locastack_container_id}

## Command used to start LocalStack
I am using Docker for running localstack.
...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
creating lambda function -

`awslocal lambda create-function --function-name demo --runtime nodejs12.x --role demo_executor --timeout 900 --memory-size 256 --handler index.handler --zip-file fileb://demo.zip`

invoke lambda function - 

`awslocal lambda invoke --function-name demo  demo_outfile`

...

┆Issue is synchronized with this [Jira Task](https://localstack.atlassian.net/browse/LOC-66) by [Unito](https://www.unito.io/learn-more)

**Comment by irahulranjan** [comment]
Hi @amitheda, Thanks for reporting the issue. Apparently, the behavior is the same in a real AWS environment. Please refer to the following for more details. 
https://aws.amazon.com/premiumsupport/knowledge-center/lambda-function-retry-timeout-sdk/
