### ISSUE TITLE
Failure to load docker plugin stops operations

### ISSUE THREAD

**Issue by strk** [localstack/localstack#3218]
When docker module is NOT available on the system, `localstack start --host` prints a WARNING about being unable to load the docker plugin and then silently fails to start. This was already reported in https://github.com/localstack/localstack/issues/3182#issuecomment-717207930 but  I'm filing this one to be more focused on the plugin issue.

I'd think that fatal errors should print ERROR instead of WARNING, and that `localstack start --host` should exit with a FAILURE exit code in those cases.

Also, why is docker module dependency not encoded in the pip repository ?

**Comment by whummer** [comment]
Thanks for reporting @strk . Please note that starting outside of Docker is not recommended/supported anymore at this point. The only supported way to start LocalStack these days is in Docker. The reason we had to make this decision is that there are lots of moving parts in the platform, and it became virtually impossible to manage all the various different operating systems, python versions, native libraries etc. that users were reporting. Hope that helps, sorry for not being able to support host-only installations (via the `--host` flag) at this point. Thanks
