### ISSUE TITLE
CreateDBParameterGroup and DescribeDBParameterGroups responses do not include key DBParameterGroupArn

### ISSUE THREAD

**Issue by ghost** [localstack/localstack#3219]
# Type of request: This is a ...
[x] bug report
[ ] feature request

# Detailed description
Although it is not documented in the RDS API reference, the [CreateDBParameterGroup](https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_CreateDBParameterGroup.html) and [DescribeDBParameterGroups](https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_DescribeDBParameterGroups.html) responses should contain a key `DBParameterGroupArn` for each parameter group returned.

Despite not being listed in the API reference, these keys are described in the CLI docs:

* https://awscli.amazonaws.com/v2/documentation/api/latest/reference/rds/create-db-parameter-group.html
* https://awscli.amazonaws.com/v2/documentation/api/latest/reference/rds/describe-db-parameter-groups.html

## Expected behavior
```
% aws rds create-db-parameter-group --db-parameter-group-name foo --db-parameter-group-family postgres12 --description bar 
{
    "DBParameterGroup": {
        "DBParameterGroupName": "foo",
        "DBParameterGroupFamily": "postgres12",
        "Description": "bar",
        "DBParameterGroupArn": "arn:aws:rds:us-east-1:REDACTED:pg:foo"
    }
}
% aws rds describe-db-parameter-groups
{
    "DBParameterGroups": [
        {
            "DBParameterGroupName": "foo",
            "DBParameterGroupFamily": "postgres12",
            "Description": "bar",
            "DBParameterGroupArn": "arn:aws:rds:us-east-1:REDACTED:pg:foo"
        }
    ]
}
```

## Actual behavior
```
% aws --endpoint http://127.0.0.1:4566/ rds create-db-parameter-group --db-parameter-group-name foo --db-parameter-group-family postgres12 --description bar 
{
    "DBParameterGroup": {
        "DBParameterGroupName": "foo",
        "DBParameterGroupFamily": "postgres12",
        "Description": "bar"
    }
}
% aws --endpoint http://127.0.0.1:4566/ rds describe-db-parameter-groups
{
    "DBParameterGroups": [
        {
            "DBParameterGroupName": "foo",
            "DBParameterGroupFamily": "postgres12",
            "Description": "bar"
        }
    ]
}
```

# Steps to reproduce
## Command used to start LocalStack
```
docker run --network bridge -p 4566:4566 --env LOCALSTACK_API_KEY=REDACTED --env SERVICES=rds localstack/localstack:0.12.1
```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
```
aws --endpoint http://127.0.0.1:4566/ rds create-db-parameter-group --db-parameter-group-name foo --db-parameter-group-family postgres12 --description bar
aws --endpoint http://127.0.0.1:4566/ rds describe-db-parameter-groups
```

┆Issue is synchronized with this [Jira Task](https://localstack.atlassian.net/browse/LOC-65) by [Unito](https://www.unito.io/learn-more)

**Comment by whummer** [comment]
Thanks for reporting @smslattery . This should be fixed in the meantime - can you please pull the `latest` Docker image and give it another try? Please let us known if the problem persists. Thanks for your help.
