### ISSUE TITLE
localstack list-metrics showing duplicate metrics for same dimension

### ISSUE THREAD

**Issue by sahajavidya** [localstack/localstack#3222]
# Type of request: This is a ...
[ x] bug report
[ ] feature request

# Detailed description
...
localstack list-metrics showing duplicate metrics for same dimension.

## Expected behavior
...
localstack list-metrics should not show duplicate metrics for same dimension.

## Actual behavior
...

# Steps to reproduce
Need Help on why localstack list-metrics is giving duplicate metrics name for same dimension.

I am doing as follows.

1) Initially no metrics was listed for --dimensions Name=InstanceId,Value=i-0bada24f4d28a7793

```
[root@xxxxx]# aws --endpoint-url=http://localhost:5000 cloudwatch list-metrics --namespace AWS/EC2 --dimensions Name=InstanceId,Value=i-0bada24f4d28a7793 --region us-east-1

{
    "Metrics": []
}
```

2) put metric data for MetricName: CPUUtilization

```
[root@xxxxx]# aws --endpoint-url=http://localhost:5000 cloudwatch put-metric-data --namespace AWS/EC2 --metric-data '[{ "MetricName": "CPUUtilization", "Dimensions": [ { "Name": "InstanceId", "Value": "i-0bada24f4d28a7793" } ], "Value": 28, "Unit": "Percent" }]'
```

3) Get the list of metrics and its work fine as bellows.

```
[root@xxxxx]# aws --endpoint-url=http://localhost:5000 cloudwatch list-metrics --namespace AWS/EC2 --dimensions Name=InstanceId,Value=i-0bada24f4d28a7793 --region us-east-1

{
    "Metrics": [
        {
            "Namespace": "AWS/EC2",
            "MetricName": "CPUUtilization",
            "Dimensions": [
                {
                    "Name": "InstanceId",
                    "Value": "i-0bada24f4d28a7793"
                }
            ]
        }
    ]
}
```

4) Again put metric data for same metric and instance.

```
[root@xxxx]# aws --endpoint-url=http://localhost:5000 cloudwatch put-metric-data --namespace AWS/EC2 --metric-data '[{ "MetricName": "CPUUtilization", "Dimensions": [ { "Name": "InstanceId", "Value": "i-0bada24f4d28a7793" } ], "Value": 28, "Unit": "Percent" }]'
```

5) Now again get the list of metrics, But this time we will see the same metric twice.

```
[root@xxxxx]# aws --endpoint-url=http://localhost:5000 cloudwatch list-metrics --namespace AWS/EC2 --dimensions Name=InstanceId,Value=i-0bada24f4d28a7793 --region us-east-1

{
    "Metrics": [
        {
            "Namespace": "AWS/EC2",
            "MetricName": "CPUUtilization",
            "Dimensions": [
                {
                    "Name": "InstanceId",
                    "Value": "i-0bada24f4d28a7793"
                }
            ]
        },
        {
            "Namespace": "AWS/EC2",
            "MetricName": "CPUUtilization",
            "Dimensions": [
                {
                    "Name": "InstanceId",
                    "Value": "i-0bada24f4d28a7793"
                }
            ]
        }
    ]
}
```

If we do put-metric-data again and try to get the list of metrics then localstack will list the same metric three times. It is keep on increasing and showing duplicate metrics.
Am I doing something wrong? Need help to resolve this issue.

## Command used to start LocalStack
...
...

┆Issue is synchronized with this [Jira Task](https://localstack.atlassian.net/browse/LOC-63) by [Unito](https://www.unito.io/learn-more)

**Comment by whummer** [comment]
Thanks for reporting @sahajavidya . This should be fixed upstream in the meantime and should now be available in LocalStack. Can you please pull the `latest` Docker image and give it another try? Please report here if the problem persists. Thanks

**Comment by sahajavidya** [comment]
Thanks @whummer , Verified. It is working.
