### ISSUE TITLE
Cannot calls dockerized localstack instance directly after setting it up

### ISSUE THREAD

**Issue by YoannKy** [localstack/localstack#3223]
# Type of request: This is a ...
[x] bug report
[ ] feature request

# Detailed description
I am trying to set up an integration test as shown in the image below:
![Diagram](https://user-images.githubusercontent.com/7498614/97919689-832ca200-1d58-11eb-9ec2-d7408ebcfa2f.jpg)

But once my container is built and I'm trying to run my test, **I'm facing a socket hang up** the first time I'm asserting. I thought it was due the connection not being available yet since retrying some seconds later resulted in a **successful call**.

But I tried using  [this library](https://www.npmjs.com/package/wait-port) that basically wait for the connection to be up
so my command looked like this:
`docker-compose up -d && wait-port 4566 && jest`
Unfortunately the latter did not work. Despite the port being up I'm still getting a socket hang up upon calling the container.
I also tried other ways to wait for the port to be ready but none of them resolved the issue.

I don't really know if this is a bug, I think the actual problem is that the container is not fully ready and I should wait for it.

## Expected behavior
Once containers has been set up, the call to the container should succeed

## Actual behavior
Altought container has been set up, the test runner tries to communicate with it but the request fails

# Steps to reproduce
* ENVIRONMENT:

```
nodejs: 12.19.0
localstack version:0.12.1
jest version: 26.6.2
docker version:  19.03.12-ce, build 48a66213fe
```

1. Create a docker container with lambda service up and a lambda ready to be called through entrypoint script
1. Make a function that calls a lambda through aws sdk
1. run jest to test your function 

## Command used to start LocalStack
`docker-compose up -d (dockerized)`

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
* minimalist docker-compose.yml

```
version: '3'
services:
  aws:
    image: localstack/localstack
    container_name: aws
    environment:
      - SERVICES=lambda
      - DEFAULT_REGION=eu-central-1
    ports:
      - 4566:4566
    volumes:
      - './__test__/docker/aws/setup.sh:/docker-entrypoint-initaws.d/setup.sh'
```

* This is my seeder script that simply creates a lambda from a dummy handler

```
#!/bin/bash
pip install awscli-local
echo 'export function handler() { return {} }' >> index.js
zip lambda.zip handler.js
awslocal lambda create-function --function-name test --runtime nodejs12.x --timeout 900 --role fakeArn --handler index.handler --zip-file fileb://lambda.zip
rm lambda.zip handler.js
```

* Function used to call the lambda

```
const lambda = new AWS.Lambda();
  const params =;
  try {
    const data = await lambda.invoke({
    FunctionName,
    InvocationType',
    Payload,
  }).promise();
} catch() {...}
```

* script test of my package.json

```
"test": "docker-compose up -d && jest",
```

*  test file skeleton:

```
descrtibe('test', () =>
  beforeAll(() => {
      AWS.config.update({
        endpoint: 'http://localhost:4566',
        region: 'eu-central-1',
    });

   it('...',   async() => {
    const resp = await handler();
   expect(resp).toEqual(....)
  })
});
```

┆Issue is synchronized with this [Jira Task](https://localstack.atlassian.net/browse/LOC-62) by [Unito](https://www.unito.io/learn-more)

**Comment by whummer** [comment]
Thanks for reporting @YoannKy . Can you please check if the details in the health check endpoint can be used to wait until the LocalStack instance is up and running?
```
$ curl -v http://localhost:4566/health
{"services": {"apigateway": "running", "cloudformation": "running",  ...
```
Please let us know if that helps. Thanks

**Comment by YoannKy** [comment]
Hi @whummer,

If i try to call the health endpoint immediatly after the setup of the container I'm getting an `Error: socket hang up` . Otherwise the health endpoint works correctly and indicates that the services are running.

There seems to be a delay between:
- the time when the container is up
- the time when the services are actualy reachable

I could just put an arbitrary wait in my integration test but that would just be a workaround.

**Comment by whummer** [comment]
Thanks for the update @YoannKy .

The pattern we usually recommend is to start a retry loop until the services are up and running (or until the process times out). Something like the pseudo code below:
```
def await_startup():
    for i in range(10):
        if all_services_available():
            return
   raise Exception(...)
```
Hope that helps - please let us know if there are any other issues. Thanks
