### ISSUE TITLE
Unable to handle incoming websockets message: 'target'

### ISSUE THREAD

**Issue by mariaines** [localstack/localstack#3229]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description
Hi, I'm trying to wire up a websockets api in localstack. I'm not using serverless :( so the example is not much help.

I am able to connect to the websocket with wscat:
```
$ wscat -c ws://localhost:4510
Connected (press CTRL+C to quit)
>
< {"error": "Unable to find route for action \"$request.body.action\", API ID \"3a06fa0c\""}
> {"action":"$default"}
>
```
but my lambda is not being called, instead I see this error message:
```
localstack_1           | 2020-11-10T21:48:47:INFO:localstack_ext.utils.websockets: Unable to handle incoming websockets message: 'target'
```

Any tips greatly appreciated!

## Expected behavior
My lambda integration should be called for all incoming messages

## Actual behavior
Lambda is not called

# Steps to reproduce

## Command used to start LocalStack
docker-compose up

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
```sh
  result=$(aws lambda create-function \
    --endpoint-url http://$HOST:4566 \
    --function-name WebsocketHandler \
    --runtime python3.8 \
    --role arn:aws:iam:isignored \
    --handler ws_service.ws_handler \
    --code S3Bucket="__local__",S3Key="$BUILDDIR" \
    --timeout 600 \
    --publish)
  echo "$result"
  result=$(aws apigatewayv2 create-api \
    --endpoint-url http://$HOST:4566 \
    --name "WebsocketService" \
    --protocol-type WEBSOCKET \
    --route-selection-expression '$request.body.action')
  echo "$result"
  apiId=$(echo "$result" | grep "\"ApiId\":" | awk -F "\"" '{print $4}')
  echo "$apiId"
  aws apigatewayv2 create-route \
    --endpoint-url http://$HOST:4566 \
    --api-id $apiId \
    --route-key '$default'
  aws apigatewayv2 create-integration \
    --endpoint-url http://$HOST:4566 \
    --api-id $apiId \
    --integration-type AWS_PROXY \
    --integration-method POST \
    --integration-uri arn:aws:apigateway:us-west-2:lambda:path/2015-03-31/functions/arn:aws:lambda:us-west-2:000000000000:function:WebsocketHandle/invocations
  result=$(aws apigatewayv2 create-deployment \
    --endpoint-url http://$HOST:4566 \
    --api-id $apiId)
  echo "$result"
  deploymentId=$(echo "$result" | grep "\"DeploymentId\":" | awk -F "\"" '{print $4}')
  echo "$deploymentId"
  aws apigatewayv2 create-stage \
    --endpoint-url http://$HOST:4566 \
    --api-id $apiId \
    --deployment-id $deploymentId \
    --stage-name Prod
```

**Comment by whummer** [comment]
Thanks for reporting this issue @mariaines . Looks like the `$default` route you're creating via `create-route` is not connected to the `AWS_PROXY` integration created via `create-integration`.

The `create-route` API call has a `--target` parameter which is technically not mandatory (as per the API spec), but without specifying the target, it is unclear which action should be performed if a certain route gets called. We need to verify whether the same configuration works when executed against real AWS - did you already have a chance to test that, by any chance?

In the meantime, something like this (adding `--target`) should (hopefully) work:
```
$ int_id=$(aws apigatewayv2 create-integration \
    --endpoint-url http://$HOST:4566 \
    --api-id $apiId \
    --integration-type AWS_PROXY \
    --integration-method POST \
    --integration-uri arn:aws:apigateway:us-west-2:lambda:path/2015-03-31/functions/arn:aws:lambda:us-west-2:000000000000:function:WebsocketHandle/invocations | jq -r '.IntegrationId')
 $ aws apigatewayv2 create-route \
    --endpoint-url http://$HOST:4566 \
    --api-id $apiId \
    --route-key '$default'
    --target integrations/$int_id
```
Hope that helps - please keep us posted how it goes. Thanks!

**Comment by mariaines** [comment]
That did it, thank you so much @whummer !  I had not tested this on AWS - we are using a SAM template for AWS so I was trying to translate that into awscli commands, and totally missed that part.  Thanks so much for the quick help!
