### ISSUE TITLE
Map dynamodb local event source to lambda function

### ISSUE THREAD

**Issue by mikebrules** [localstack/localstack#323]
Hi, I have a local dynamodb running, with a stream ARN. I was hoping I could use localstack to install a lambda function that consumes that stream - I have set up a event-source-mapping between the two. When I insert records into the DB, the Lambda may or may not be being called - I don't know - where would the lambda log to if it isn't being called from `invoke`

Is it possible to have a Lambda called from a Dynamo Local event source using localstack?

Thanks

**Comment by mikebrules** [comment]
okay, so the "mock" dynamo is actually dynamo local. I don't need both :)

**Comment by whummer** [comment]
Hey @mikebrules, triggering a Lambda from DynamoDB streams should be possible - were you able to get it running? Not sure what you're referring to when you say "both" - can you please clarify. Please re-open this ticket if there are any other issues. Thanks

**Comment by mikebrules** [comment]
@whummer thanks for getting back. In short, yes, I did get it working but I'm having lots of trouble getting it to stable, and I think this was partly my problem which was throwing me off. I can't currently get it to register a lambda function without it saying that it already exists (which it then won't invoke as it says is missing) -  despite killing the container and starting again...

**Comment by mikebrules** [comment]
@whummer no, I can't get this to work in the docker build. Its possible I am doing something wrong in terms of streams, but when I create a lambda and a dynamo table, I never get a kinesis stream - which I was outside docker where I was using the normal dynamodb local (not the one with localstack). My event source mappings seem to work, and the Web UI shows a link between the lambda and the table, but not via the event source kinesis stream which is what it did when I saw it working. Would be useful to see an example. I am meant to be using the streams endpoint for example?

**Comment by mikebrules** [comment]
Quick question then. When my table is created, the StreamArn is this

` LatestStreamArn": "arn:aws:dynamodb:ddblocal:000000000000:table/local-users/stream/2017-09-22T12:19:10.331`

I tried event mappins like this

    {
    "UUID": "8dd937b5-ebbb-466d-a295-c73b73ff5dd1",
    "StateTransitionReason": "User action",
    "LastModified": 1506082758.0,
    "BatchSize": 100,
    "EventSourceArn": "arn:aws:dynamodb:ddblocal:000000000000:table/local-publications/stream/*",
    "FunctionArn": "arn:aws:lambda:us-east-1:000000000000:function:DynamoToElasticPublications",
    "State": "Enabled",
    "LastProcessingResult": "OK"
    }

is that right? even if I specify the actual stream "2017-09-22T12:19:10.331" part it is still not working?

**Comment by mikebrules** [comment]
@whummer  - I'm still not getting any luck here - I suspect I am doing something wrong in my approach; do you know if I should 
a) use the kinesis endpoint ARN (the kinesis artefact gets created when I create a dynamotable) for my event mapping, or
b) use the dynamo table streamARN 

..they are different; I ask because the only time I saw this work, I was running  dynamo local (separate download - not part of localstack) and a lambda with an event mapping of the table ARN. 
It seemed to work, but I want to do this is localstack. Which approach is best?

Thanks

**Comment by whummer** [comment]
Thanks for the detailed report - it made debugging a lot easier. This should be fixed in #392 (the Docker image is currently being built and pushed by travis-ci). 

The following sequence of commands now works for me locally (note that I'm using the [awslocal](https://github.com/localstack/awscli-local) CLI):
```
awslocal lambda create-function --function-name f1 --zip-file fileb://lambda.zip --handler lambda.handler --environment "Variables={PRIMARY_ELASTIC_HOST=127.0.0.1:4571,SECONDARY_ELASTIC_HOST=127.0.0.1:4571,ENV=LOCAL}" --runtime 'nodejs6.10' --role r

awslocal dynamodb create-table --table-name local-users --attribute-definitions 'AttributeName=a1,AttributeType=S' --key-schema 'AttributeName=a1,KeyType=HASH' --provisioned-throughput 'ReadCapacityUnits=1,WriteCapacityUnits=1'

awslocal lambda create-event-source-mapping --function-name f1 --event-source arn:aws:dynamodb:us-east-1:000000000000:table/local-users --batch-size 10 --starting-position TRIM_HORIZON

awslocal dynamodb put-item --table-name local-users --item '{"a1":{"S":"123"}}'
```

Note that there is also an **alternative** (probably preferred) way of creating the stream and defining the mapping, as follows:
```
awslocal lambda create-function --function-name f1 --zip-file fileb://lambda.zip --handler lambda.handler --environment "Variables={PRIMARY_ELASTIC_HOST=127.0.0.1:4571,SECONDARY_ELASTIC_HOST=127.0.0.1:4571,ENV=LOCAL}" --runtime 'nodejs6.10' --role r

awslocal dynamodb create-table --table-name local-users --attribute-definitions 'AttributeName=a1,AttributeType=S' --key-schema 'AttributeName=a1,KeyType=HASH' --provisioned-throughput 'ReadCapacityUnits=1,WriteCapacityUnits=1' --stream-specification 'StreamEnabled=true,StreamViewType=NEW_AND_OLD_IMAGES'

STREAM_ARN=`awslocal dynamodbstreams list-streams | jq -r '.Streams[0].StreamArn'`

awslocal lambda create-event-source-mapping --function-name f1 --event-source $STREAM_ARN --batch-size 10 --starting-position TRIM_HORIZON

awslocal dynamodb put-item --table-name local-users --item '{"a1":{"S":"123"}}'
```

**Comment by mikebrules** [comment]
@whummer thanks loads for all this effort. I will give it a try and report back later on. Appreciate it!

**Comment by mikebrules** [comment]
@whummer that is really, really close. Everything works really well, with one exception. Using the example above, the Stream details (ViewType and SequenceNumber) are not those in my table. Here is my table def (relevant bit)

     "TableName" : "local-publications",
        "StreamSpecification" : {
          "StreamViewType": "NEW_IMAGE",
          "StreamEnabled":true
        }

Here is the relevant part of my event in my Lambda dumped out

         "SizeBytes": -1,
         "StreamViewType": "NEW_AND_OLD_IMAGES",
         "SequenceNumber": "1",
         ......
         "eventName":"INSERT","eventSourceARN":"arn:aws:dynamodb:us-east-1:000000000000:table/local-publications","eventSource":"aws:dynamodb"}

To create the event source, I did this, mentioning the full ARN (with date etc), which looks different to the one above in the event...

      aws lambda create-event-source-mapping --function-name dynamo-to-elastic-publications --event-source arn:aws:dynamodb:us-east-1:000000000000:table/local-publications/stream/2017-10-11T15:16:25 --batch-size 10 --starting-position TRIM_HORIZON --endpoint http://localhost:4574

Any idea why the two stream arns are not matching up? Its soooo close......

**Comment by whummer** [comment]
Basic support for increasing sequence numbers is added in #445. Does that solve your issue @mikebrules ?

**Comment by mikebrules** [comment]
@whummer sorry for the radio silence - I'm checking this now

**Comment by mikebrules** [comment]
hi @whummer - I can consistently put items to the table now which is great. However, updates to existing items are still failing - it seems that the event record received by the lambda function is incorrect, and has no data, and no eventType amongst other things. As an example;

Here is an event receieved by the lambda from a put-item cli call. 

(Call is)

    awslocal dynamodb put-item --table-name local-publications --item file://item.json

Event received by Lambda from the table insertion is correct and works well.

    {"Records":[{"eventID":"1","eventVersion":"1.0","dynamodb":{"Keys":{"publicationId":{"S":"1234567"}},"SizeBytes":-1,"StreamViewType":"NEW_AND_OLD_IMAGES","SequenceNumber":"1","NewImage":{.........},"awsRegion":"us-east-1","eventName":"INSERT","eventSourceARN":"arn:aws:dynamodb:us-east-1:000000000000:table/local-publications","eventSource":"aws:dynamodb"}]}
    
Now try anf update that record. This call works (i.e. does update the table), but the Lambda blows up because the event is not correct

Update an item

    awslocal dynamodb update-item --table-name local-publications --key file://key.json --expression-attribute-names file://att-names.json --expression-attribute-values file://att-values.json --update-expression "SET #N = :n"

resulting event in lambda. Note there is no eventName, no data (i.e no Keys), SizeBytes=-1

    {"Records":[{"eventID":"1","eventVersion":"1.0","awsRegion":"us-east-1","dynamodb":{"SizeBytes":-1,"StreamViewType":"NEW_AND_OLD_IMAGES","SequenceNumber":"1"},"eventSourceARN":"arn:aws:dynamodb:us-east-1:000000000000:table/local-publications","eventSource":"aws:dynamodb"}]}

Sorry to not to have better news. I'm unsure as to what else I can do to test - its possible my update-item call is not correct, but it _is_ updating the underlying table ok. Can I do anything else?

**Comment by mikebrules** [comment]
@whummer one update. I tried (for completeness) the remove method (delete-item). The event generated by this is very close - it has keys, the correct eventName, but is missing the NewImage (from which we would take the publicationId to remove from Elastic

    {"Records":[{"eventID":"1","eventVersion":"1.0","dynamodb":{"Keys":{"publicationId":{"S":"1234567"}},"SizeBytes":-1,"StreamViewType":"NEW_AND_OLD_IMAGES","SequenceNumber":"1"},"awsRegion":"us-east-1","eventName":"REMOVE","eventSourceARN":"arn:aws:dynamodb:us-east-1:000000000000:table/local-publications","eventSource":"aws:dynamodb"}]}

**Comment by whummer** [comment]
@mikebrules The event notifications for `update-item` should be fixed in #484 .

Regarding `delete-item`, it seems that `NewImage` is not part of the event triggered by AWS. For example, if you look at the examples posted here:
http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Streams.LowLevel.Walkthrough.CompleteProgram.html

Can you please confirm that the current version works for you, then we can close off this issue.

**Comment by mikebrules** [comment]
thanks @whummer, checking it now

**Comment by mikebrules** [comment]
@whummer I salute you. Great work, that is working exactly as expected - many thanks for all your efforts...
