### ISSUE TITLE
Releases - GitHub vs DockerHub

### ISSUE THREAD

**Issue by bradleyhurley** [localstack/localstack#3232]
I am looking for clarification on the differences between the tagged versions on DockerHub and the versions marked as releases on GitHub.

Is 0.12.2 considered the current release version? If so are release notes available for versions 0.12.0, 0.12.1, and 0.12.2?

**Comment by whummer** [comment]
Thanks for reporting @bradleyhurley - the missing releases and release notes have now been added here on Github.
