### ISSUE TITLE
create function in lambda not working

### ISSUE THREAD

**Issue by sumantdonthivvsrs** [localstack/localstack#3239]
# Type of request: This is a bug.
[ ] bug report
[ ] feature request

# Detailed description
 After pulling new image for local stack (**docker pull localstack/localstack)** on my mac.
Before pulling the new image it was working as expected,but with new image create function in lambda not working, 

...

## Expected behavior
the lambda function has to be created.
...

## Actual behavior
Unknown error: Command 'cd /tmp/localstack/zipfile.8b6156b1; unzip -o /tmp/localstack/zipfile.8b6156b1/original_lambda_archive.zip' returned non-zero exit status 12. Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 980, in create_function
    result = set_function_code(func_details.code, lambda_name)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 773, in set_function_code
    unzip(tmp_file, lambda_cwd)
  File "/opt/code/localstack/localstack/utils/common.py", line 941, in unzip
    return run('cd %s; unzip %s %s' % (target_dir, flags, path))
  File "/opt/code/localstack/localstack/utils/common.py", line 1146, in run
    return do_run(cmd)
  File "/opt/code/localstack/localstack/utils/common.py", line 1143, in do_run
    return bootstrap.run(cmd, **kwargs)
  File "/opt/code/localstack/localstack/utils/bootstrap.py", line 653, in run
    raise e
  File "/opt/code/localstack/localstack/utils/bootstrap.py", line 613, in run
    output = subprocess.check_output(cmd, shell=True, stderr=stderr, env=env_dict, cwd=cwd)
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'cd /tmp/localstack/zipfile.8b6156b1; unzip -o /tmp/localstack/zipfile.8b6156b1/original_lambda_archive.zip' returned non-zero exit status 12.

...

# Steps to reproduce
## Command used to start LocalStack
localstack start

...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
**I am trying this with lambda SDK.**

 public static final AWSCredentials TEST_CREDENTIALS = new BasicAWSCredentials(
            POPTestConstants.TEST_ACCESS_KEY,POPTestConstants.TEST_SECRET_KEY);

public static AWSLambda getClientLambda() {
        return AWSLambdaClientBuilder.standard().
                withEndpointConfiguration(getEndpointConfiguration()).
                withCredentials(getCredentialsProvider()).build();
    }

private static AwsClientBuilder.EndpointConfiguration getEndpointConfiguration() {
        return getEndpointConfiguration("http://localhost:4566");
    }

```
private static AwsClientBuilder.EndpointConfiguration getEndpointConfiguration(String endpointURL) {
    return new AwsClientBuilder.EndpointConfiguration(endpointURL, "us-west-2");
}
private static AWSCredentialsProvider getCredentialsProvider() {
    return new AWSStaticCredentialsProvider(TEST_CREDENTIALS);
}
```

...

┆Issue is synchronized with this [Jira Task](https://localstack.atlassian.net/browse/LOC-56) by [Unito](https://www.unito.io/learn-more)

**Comment by sumantdonthivvsrs** [comment]
I tried with cli also..its creating same issue..

**awslocal --endpoint=http://localhost:4566 lambda create-function  --function-name testfunction --role testrole  --runtime java11  --zip-file fileb:////test.jar  --handler handlername  --environment Variables="{samplekey=samplevalue}"  --region us-west-2**

**Error**

An error occurred (InternalFailure) when calling the CreateFunction operation (reached max retries: 4): Unknown error: Command 'cd /tmp/localstack/zipfile.fef3ef5e; unzip -o /tmp/localstack/zipfile.fef3ef5e/original_lambda_archive.zip' returned non-zero exit status 12. Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 980, in create_function
    result = set_function_code(func_details.code, lambda_name)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 773, in set_function_code
    unzip(tmp_file, lambda_cwd)
  File "/opt/code/localstack/localstack/utils/common.py", line 941, in unzip
    return run('cd %s; unzip %s %s' % (target_dir, flags, path))
  File "/opt/code/localstack/localstack/utils/common.py", line 1146, in run
    return do_run(cmd)
  File "/opt/code/localstack/localstack/utils/common.py", line 1143, in do_run
    return bootstrap.run(cmd, **kwargs)
  File "/opt/code/localstack/localstack/utils/bootstrap.py", line 653, in run
    raise e
  File "/opt/code/localstack/localstack/utils/bootstrap.py", line 613, in run
    output = subprocess.check_output(cmd, shell=True, stderr=stderr, env=env_dict, cwd=cwd)
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'cd /tmp/localstack/zipfile.fef3ef5e; unzip -o /tmp/localstack/zipfile.fef3ef5e/original_lambda_archive.zip' returned non-zero exit status 12.

**Comment by usmangani1** [comment]
@sumantdonthivvsrs  thanks for reporting the issue.Can you please help us with the zip file which is being used here to reproduce the issue ?

**Comment by sumantdonthivvsrs** [comment]
@usmangani1  , Thanks for comment, I am able to solve this issue ...This issue is because of duplicate dependency and that created **"ZIP Bomb"** ...Earlier with old local stack image I was not getting this ZIP Bomb error....So now I added  "duplicatesStrategy = DuplicatesStrategy.EXCLUDE" in gradle build  while jar file ....It resolved my issue.Thanks you.
