### ISSUE TITLE
Instance profile associations fail with Internal Server Error

### ISSUE THREAD

**Issue by clebio** [localstack/localstack#3241]
# Type of request: This is a ...
[x] bug report
[ ] feature request

# Detailed description
Creating or describing EC2 instance profile associations fails (see full repro steps below).

```sh
$ aws $ARS ec2 associate-iam-instance-profile --instance-id $INST --iam-instance-profile Name=$NAME

Unable to parse response (syntax error: line 1, column 54), invalid XML received. Further retries may succeed:
b'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">\n<title>500 Internal Server Error</title>\n<h1>Internal Server Error</h1>\n<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>\n'
```

Also with describe associations:

```sh
$ aws $ARS ec2 describe-iam-instance-profile-associations

Unable to parse response (syntax error: line 1, column 54), invalid XML received. Further retries may succeed:
b'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">\n<title>500 Internal Server Error</title>\n<h1>Internal Server Error</h1>\n<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>\n'
```

## Expected behavior
These operations don't fail and instead work.

## Actual behavior
`Unable to parse response (syntax error: line 1, column 54), invalid XML received. Further retries may succeed:
b'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">\n<title>500 Internal Server Error</title>\n<h1>Internal Server Error</h1>\n<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>\n'`

# Steps to reproduce
```sh
export AWS_ACCESS_KEY_ID=test
export AWS_SECRET_ACCESS_KEY=test

docker run --rm -d -p 4566:4566 --name localstack localstack/localstack

export ARS='--region=us-east-1 --endpoint-url=http://localhost:4566 '
INST=$(aws $ARS ec2 run-instances | jq -r '.Instances[].InstanceId')
NAME=fake
aws $ARS iam create-instance-profile --instance-profile-name $NAME
aws $ARS ec2 associate-iam-instance-profile --instance-id $INST --iam-instance-profile Name=$NAME
```

## Command used to start LocalStack
```
docker run --rm -d -p 4566:4566 --name localstack localstack/localstack
```

┆Issue is synchronized with this [Jira Task](https://localstack.atlassian.net/browse/LOC-55) by [Unito](https://www.unito.io/learn-more)

**Comment by miho120** [comment]
There is no support in the upstream moto module. I'll look into the moto code, might be will be easy to add this :)

**Comment by miho120** [comment]
Hi @clebio I've made a PR to the upstream (https://github.com/spulec/moto/pull/3482), so once it's merged we can merge the latest master to localstack and this should resolve your issue. @whummer correct me if I'm wrong.

**Comment by whummer** [comment]
This change is merged and should now be available in LocalStack - can you please pull the `latest` Docker image and give it another try? Please report here if the problem persists. Thanks
