### ISSUE TITLE
Usage of `docker inspect ..` is fragile, depends on how and what built the docker image

### ISSUE THREAD

**Issue by nhoughto** [localstack/localstack#3242]
[x] bug report
[ ] feature request

# Detailed description
`lambda_executor.py` current retrieves the container entrypoint from the docker image via `docker inspect --format="{{ .ContainerConfig.Entrypoint }}" ..`. This is fragile and may be missing depending on how the image in question is built. There is a `config` block _and_ a `containerconfig` block that are mostly the same, but sometimes different depending what built and what version of that thing built the image, for example we are seeing the entrypoint missing on images built with Docker for Mac 2.5.0.1, but not on earlier versions, others using `podman` are noticing the fragility in other projects:

https://github.com/containers/podman/issues/2017

## Expected behavior
entrypoint value is picked up from a validly built container

## Actual behavior
entrypoint is sometimes an empty string, which then for a `provided` lambda executor ends up with a script error trying to execute the handler name.

The simple fix is to change `--format="{{ .ContainerConfig.Entrypoint }}"` to `--format="{{ .Config.Entrypoint }}"` which seems like the more canonical way of getting that value.

┆Issue is synchronized with this [Jira Task](https://localstack.atlassian.net/browse/LOC-54) by [Unito](https://www.unito.io/learn-more)

**Comment by whummer** [comment]
Thanks for digging into this issue @nhoughto !

> The simple fix is to change --format="{{ .ContainerConfig.Entrypoint }}" to --format="{{ .Config.Entrypoint }}" which seems like the more canonical way of getting that value.

Sounds good to me - would you be able to create a small pull request with this change? Thanks for your help.

**Comment by nhoughto** [comment]
Yep done https://github.com/localstack/localstack/pull/3366
