### ISSUE TITLE
CloudFormation Ref of "AWS::ApiGatewayV2::Api" attempts to return "PhysicalResourceId" which is null (instead of "ApiId")

### ISSUE THREAD

**Issue by m-chandler** [localstack/localstack#3252]
# Type of request: This is a ...
[ X ] bug report
[ ] feature request

# Detailed description
I have an AWS::ApiGatewayV2::Api resource in my CloudFormation template.

Using "Ref" on this resource, should return the ApiId (for use across other resources in the stack).

Instead, the following error is observed:

```localstack_main   | 2020-11-17T06:34:32:WARNING:localstack.utils.cloudformation.template_deployer: Unable to extract reference attribute PhysicalResourceId from resource: {'ApiEndpoint': 'ws://localhost:4514', 'ApiId': '48a6e425', 'Description': 'Serverless Websockets', 'Name': 'local-localstack-websockets-websockets', 'ProtocolType': 'WEBSOCKET', 'RouteSelectionExpression': '$request.body.action'}```

Note that this was working fine a few days ago. Related to this? https://github.com/localstack/localstack/pull/3244

## Expected behavior
Ref on AWS::ApiGatewayV2::Api should return the ApiId.

## Actual behavior
An exception is thrown, as it attempts to get PhysicalResourceId, which either does not exist or simply isn't populated.

# Steps to reproduce
Please refer to the steps to reproduce contained within this comment / parent issue, as it is able to replicate the issue.
https://github.com/localstack/localstack/issues/3210#issuecomment-723768889

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-329) by [Unito](https://www.unito.io/learn-more)

**Comment by whummer** [comment]
Thanks for reporting @m-chandler and apologies for the delay. We just tried to reproduce this issue but it seems to be working with the `latest` Docker image. The example you've shared in this comment https://github.com/localstack/localstack/issues/3210#issuecomment-723768889 seems to deploy properly and the `Unable to extract reference ...` is not printed in the output logs. Can you please give it another try after pulling the latest image, and let us know if the problem still persists. Thanks for your help.

**Comment by m-chandler** [comment]
Indeed, looks like this bug has been fixed elsewhere.
Thanks!
