### ISSUE TITLE
EventBridge Caches data

### ISSUE THREAD

**Issue by Salman-K** [localstack/localstack#3254]
**Type of request: Bug**

[x] bug report
[ ] feature request
Detailed description

When using eventsbridge on localstack with SQS as target, the message is cached by eventbridge and is pushed to the queue even when a different message with different content is used.

**Expected behavior**
New message appears on the queue when a different message is pushed to eventbridge.

**Actual behavior**
Previously pushed message appears on the queue, even though a new message with new **detail** was pushed to eventbridge.

**Steps to reproduce**

    Setup localstack using docker
    Create Queue
    Create EventBus
    Set Queue attributes to allow eventbridge access
    Put target on eventbridge
    Put new event onto eventbus
    Check queue for message

**Command used to start LocalStack**

docker run -d -p "4566-4587:4566-4587" -p "4592-4593:4592-4593" -p 80:8080 -v /var/run/docker.sock:/var/run/docker.sock -e LAMBDA_EXECUTOR=docker,USE_LEGACY_PORTS=false --name aws localstack/localstack:latest

**Client code (AWS SDK code snippet, or sequence of "awslocal" commands)**

$AWS_REGION = 'us-east-1'
$LOCALSTACK_ENDPOINT = 'http://localhost'

aws --endpoint-url=${LOCALSTACK_ENDPOINT}:4566 sqs create-queue --queue-name orderTestQueue

aws --endpoint-url=${LOCALSTACK_ENDPOINT}:4566 --region ${AWS_REGION} events create-event-bus --name orderTestBus

aws --endpoint-url=${LOCALSTACK_ENDPOINT}:4566 --region ${AWS_REGION} events put-rule --name orderTestRuleMatchSource --event-bus-name orderTestBus --event-pattern file://rule-filter.json

aws --endpoint-url=${LOCALSTACK_ENDPOINT}:4566 sqs set-queue-attributes --queue-url "http://localhost:4566/queue/orderTestQueue" --attributes file://sqs-policy.json

aws --endpoint-url=${LOCALSTACK_ENDPOINT}:4566--region ${AWS_REGION} events put-targets --rule orderTestRuleMatchSource --event-bus-name orderTestBus --targets file://rule-queue-arn.json

aws --endpoint-url=${LOCALSTACK_ENDPOINT}:4566--region ${AWS_REGION} events put-events --entries file://order-data.json

aws --endpoint-url=${LOCALSTACK_ENDPOINT}:4566 sqs receive-message --queue-url "http://localstack:4566/queue/orderTestQueue"

**rule-filter.json**
{"source": [ "UpdateOrder" ]}

**order-data.json**
[{
"EventBusName": "orderTestBus",
"Source": "UpdateOrder",
"DetailType": "OrderAdded",
"Detail": "{"order_id":"a787ecb","quantity":"1","customer_id":"alpha"}"
}]

**sqs-policy.json**
{"Policy":"{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Principal":{"AWS":"*"},"Action":"sqs:SendMessage","Resource":"arn:aws:sqs:us-east-1:000000000000:orderTestQueue","Condition":{"ArnEquals":{"aws:SourceArn":"arn:aws:events:us-east-1:000000000000:rule/orderTestRuleMatchSource"}}}]}"}

**rules-queue-arn.json**
[{"Id": "orderTestQueueCommand", "Arn": "arn:aws:sqs:us-east-1:000000000000:orderTestQueue", "InputPath": "$.detail"}]

When you push the following message

[{
"EventBusName": "orderTestBus",
"Source": "UpdateOrder",
"DetailType": "OrderAdded",
**"Detail": "{"order_id":"a787ecb","quantity":"1","customer_id":"alpha"}"**
}]

Check the message on the queue, then make sure the queue is empty. Now push the following message with different content to eventbridge

[{
"EventBusName": "orderTestBus",
"Source": "UpdateOrder",
"DetailType": "OrderAdded",
**"Detail": "{"order_id":"b78t3yy","quantity":"2","customer_id":"beta"}"**
}]

Check the queue again, the old message would appear.
[rule-queue-arn.zip](https://github.com/localstack/localstack/files/5561594/rule-queue-arn.zip)

Referenced files are attached.
Many Thanks

**Comment by whummer** [comment]
Thanks for reporting @Salman-K . Please note that this is the expected behavior - messages are by default **not** automatically deleted from the queue after receiving them.

Please refer to the AWS docs here : https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-visibility-timeout.html

> When a consumer receives and processes a message from a queue, the message remains in the queue

Also, you'll notice that the `ApproximateReceiveCount` increases, every time you receive the same message again.
```
ApproximateReceiveCount": "2",
...
ApproximateReceiveCount": "3",
```

Hope that helps - please let us know if there are any other issues. Thanks
