### ISSUE TITLE
Issue after running pip install localstack

### ISSUE THREAD

**Issue by franciszabala** [localstack/localstack#327]
Hello, I'd like to report a bug or maybe I misunderstood the installation.

command used:

`virtualenv ~/.localstack`

`pip install --user localstack`

Localstack is installed in /home/<user>/.local/bin

Tried to run using 
./localstack start in /home/<user>/.local/bin directory

Error:
```
Starting local dev environment. CTRL-C to quit.
Error starting infrastructure: expected string or buffer Traceback (most recent call last):
  File "/home/user/.local/lib/python2.7/site-packages/localstack/services/infra.py", line 440, in start_infra
    event_publisher.fire_event(event_publisher.EVENT_START_INFRA)
  File "/home/user/.local/lib/python2.7/site-packages/localstack/utils/analytics/event_publisher.py", line 152, in fire_event
    event = AnalyticsEvent(event_type=event_type, payload=payload)
  File "/home/user/.local/lib/python2.7/site-packages/localstack/utils/analytics/event_publisher.py", line 37, in __init__
    self.m_id = kwargs.get('machine_id') or kwargs.get('m_id') or get_machine_id()
  File "/home/user/.local/lib/python2.7/site-packages/localstack/utils/analytics/event_publisher.py", line 88, in get_machine_id
    local_configs = json.loads(to_str(local_configs))
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer

ERROR: expected string or buffer

```
I am currently running Lubuntu 16.04 on a VirtualBox with Python 2.7 installed.

Let me know if I missed anything. Thanks!

**Comment by migurski** [comment]
Try skipping the `virtualenv` invocation? `pip install --user` will install packages to `~/.local`, while `~/.localstack` is used by LocalStack to store a JSON file with config details.

When running `virtualenv ~/.localstack && pip install --user localstack && ~/.local/bin/localstack start`, I can duplicate your error. My home dir looks like:

```
drwx------ 5 root root 4096 Sep 18 19:52 /root/.local
drwxr-xr-x 6 root root 4096 Sep 18 19:51 /root/.localstack
```

When running just `pip install --user localstack && ~/.local/bin/localstack start` I don’t see the same error, and my home dir looks like:

```
drwx------ 5 root root 4096 Sep 18 19:53 /root/.local
-rw-r--r-- 1 root root   26 Sep 18 19:53 /root/.localstack
```

**Comment by franciszabala** [comment]
It worked. I hate to delete the ./localstack and ./local directories first to make it work. Thank you!

**Comment by migurski** [comment]
🎉
