### ISSUE TITLE
Update spulec/moto dependency

### ISSUE THREAD

**Issue by relvira** [localstack/localstack#3272]
# Type of request: Dependency update
[ ] bug report
[x] feature request

# Detailed description
Hello folks, after using localstack for a while I've started using it as a Route53 mock. I recently discovered spulec/moto didn't support the `GetChange` method so I went ahead and submitted a pull request there to get it implemented (https://github.com/spulec/moto/pull/3486). 

Would you be able to update your moto dependency to latest so this change (and presumably others) are usable from within localstack?

Please let me know if there's anything I can do here to make thing smoother.

Cheers 🙇🏼 

## Expected behavior
All recent spulec/moto changes will be usable from localstack

## Actual behavior
Latest functionality from moto is missing in localstack

# Steps to reproduce
N/A

## Command used to start LocalStack
N/A

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
N/A

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-349) by [Unito](https://www.unito.io/learn-more)

**Comment by macnev2013** [comment]
Hello @relvira. We recently implemented route53 `GetChange` api in PR #3248 . Can you give it another try with the `latest` docker image? Thanks.

**Comment by relvira** [comment]
Hey @macnev2013, that's great news. I can confirm this works as expected now. Thanks so much for the quick response.

I'll go ahead and close this issue now.
