### ISSUE TITLE
Lambda Functions can't find modules packaged in Lambda Layers in 0.12.x line

### ISSUE THREAD

**Issue by sjmmck** [localstack/localstack#3273]
# Type of request: This is a ...
[x] bug report
[ ] feature request

# Detailed description
Sample test case with logs [localstack_test.tar.gz](https://github.com/localstack/localstack/files/5591324/localstack_test.tar.gz)

We are running Localstack Pro and are using Lambda Layers. In the 0.11.x line, our lambda code can reference the code we package into our layers. However, in the 0.12.x line, the lambda code is returning an `Unable to import module/No module named X` error when importing code packages into a layer. We're using the `python3.8` runtime.

I've attached a test case that exhibits the expected behavior (with 0.11.5) and the actual behavior (0.12.2 and today's `latest`). As far as I'm aware we are running the latest images. Here is a listing of the images I currently have pulled:

```
localstack/localstack                                                        latest                   5dcf9d7eb425        17 hours ago        635MB
localstack/localstack                                                        0.12.2                   e45a4750510f        2 weeks ago         839MB
localstack/lambda                                                            python3.8                16ae6dc75f87        8 weeks ago         532MB
localstack/localstack                                                        0.11.5                   e0eb37bb47b8        2 months ago        682MB
```

I looked through the release notes and the code changes that seemed relevant, but I didn't come up with anything. Perhaps we missed something we need to change as part of the upgrade to the 0.12.x line. Any help is greatly appreciated!

## Expected behavior
In the sample, the `main.foo` module should be able to import `barlayer.bar` module and call the `calculate_result` method, which returns `"BARLAYER SUCCESS"`

## Actual behavior
In the sample, the `main.foo` module is not able to import the `barlayer.bar` module and invoking the lambda return a stack trace including `[ERROR] Runtime.ImportModuleError: Unable to import module 'main/foo': No module named 'barlayer'`

# Steps to reproduce
Extract the contents of the attached `localstack_test.tar.gz`

Set the desired localstack docker image in the docker-compose.yaml file.

Run the following commands to reproduce the, making sure to export LOCALSTACK_API_KEY.

`docker-compose up -d`

Wait for localstack services to be available, then run

`./test.bash`

## Command used to start LocalStack
`docker-compose up -d`

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
See `test.bash` in the attached archive

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-350) by [Unito](https://www.unito.io/learn-more)

**Comment by smurphnturf** [comment]
I am also affected by this

**Comment by whummer** [comment]
Thanks for the detailed report @sjmmck @smurphnturf. Can you please pull the `latest` Docker image and give it another try? Running the script you shared, it seems that the Lambda runs successfully and finally prints `"BARLAYER SUCCESS"` on my machine. Can you please get in touch with us directly via email or Slack? (That would make it easier to debug the issue.) Thanks for your help!

**Comment by sjmmck** [comment]
Thanks @whummer I gave it another try just now and it didn't seem to make a difference. Here are the docker images I currently have locally. As you can see I have a very recent version of localstack. Though I do see the `localstack/lambda:python3.8` image is approximately 2 months old. I tried a `docker pull` and it indicated I already have the latest image.

```
localstack/localstack                                                        latest                    123ee7e9e9a1        About an hour ago   646MB
localstack/localstack                                                        <none>                    5a931a87fbc4        10 hours ago        643MB
localstack/localstack                                                        <none>                    5dcf9d7eb425        13 days ago         635MB
localstack/localstack                                                        0.12.2                    e45a4750510f        4 weeks ago         839MB
localstack/localstack                                                        0.11.6                    906ab8604861        2 months ago        673MB
localstack/lambda                                                            python3.8                 16ae6dc75f87        2 months ago        532MB
localstack/localstack                                                        0.11.5                    e0eb37bb47b8        2 months ago        682MB
```

What email and/or Slack channel should I use to continue the conversation? Thanks!

**Comment by whummer** [comment]
Hi @sjmmck - can you please get in touch with us directly at `info@localstack.cloud`. We'll take it from there.. Thanks

**Comment by shinahotelengine** [comment]
Hi @sjmmck  did you get this working for you? I am having the same issue where the code in layers are not visible to the the functions. Let me know if you did fix this.

Thanks
