### ISSUE TITLE
ListObjectsV2 behaving differently than AWS API for paginated requests with (Next)ContinuationToken

### ISSUE THREAD

**Issue by bouergh** [localstack/localstack#3277]
# Type of request: This is a ...
[x] bug report
[ ] feature request

# Detailed description
S3 listObjectsV2 doesn't behave like AWS API.

* It looks like it responds similarly to listObjects (v1) in Localstack, which is not the case on actual AWS.
* It accepts `''` as a `ContinuationToken` in parameters, when AWS throws with it (only accepts valid or undefined).
* It returns the id of the last evaluated object as `NextContinuationToken` whereas AWS returns an obfuscated value.
https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjectsV2.html

## Expected behavior
Expected behavior is response to a similar script ran against an actual S3 bucket (content redacted)

```
{ IsTruncated: true,
  Contents:
   [ { Key: REDACTED,
       LastModified: 2020-04-17T15:55:58.000Z,
       ETag: '"25b1c0b3e99f0c446d429cd78bfc9f3e"',
       Size: 57678,
       StorageClass: 'STANDARD' } ],
  Name: REDACTED,
  Prefix: REDACTED,
  MaxKeys: 1,
  CommonPrefixes: [],
  KeyCount: 1,
  NextContinuationToken:
   '1UXPMYrBuTgDJHMG134CKseyZ5g0oI8Mb+P/gomyEwqaUdoTQh0nMk01MpgZHOW5nZ6Hz60A2Y7Oum9FRlb7Y6Wcmc08X65VeNqLguUDR0ORFPKY50os4h/XKIc8n+mRF8hxJ/sWIX3T7A+ZQ5OIikA==' }

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

(node:3205) UnhandledPromiseRejectionWarning: InvalidArgument: The continuation token provided is incorrect
    at Request.extractError (/mnt/c/dev/REDACTED/node_modules/aws-sdk/lib/services/s3.js:700:35)
    at Request.callListeners (/mnt/c/dev/REDACTED/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/mnt/c/dev/REDACTED/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/mnt/c/dev/REDACTED/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/mnt/c/REDACTED/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/mnt/c/REDACTED/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /mnt/c/dev/REDACTED/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/mnt/c/dev/REDACTED/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/mnt/c/dev/REDACTED/node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListeners (/mnt/c/dev/REDACTED/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
(node:3205) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3205) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

## Actual behavior
Actual behavior is response to the script below ran against localstack

```
{ IsTruncated: true,
  Contents:
   [ { Key: 'stuff-0',
       LastModified: 2020-11-24T21:41:43.000Z,
       ETag: '"3ed7dceaf266cafef032b9d5db224717"',
       Size: 5,
       StorageClass: 'STANDARD' } ],
  Name: 'content-management',
  Prefix: '',
  MaxKeys: 1,
  CommonPrefixes: [],
  KeyCount: 1,
  NextContinuationToken: 'stuff-0' }

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

{ IsTruncated: true,
  Contents:
   [ { Key: 'stuff-0',
       LastModified: 2020-11-24T21:41:43.000Z,
       ETag: '"3ed7dceaf266cafef032b9d5db224717"',
       Size: 5,
       StorageClass: 'STANDARD' } ],
  Name: 'content-management',
  Prefix: '',
  MaxKeys: 1,
  CommonPrefixes: [],
  KeyCount: 1,
  NextContinuationToken: 'stuff-0' }
```

# Steps to reproduce
## Command used to start LocalStack
`docker compose up`
with following yaml

```
version: '2.3'
services:
  localstack:
    image: localstack/localstack:latest
    environment:
      - SERVICES=firehose,s3,lambda,sqs
      - DEFAULT_REGION=us-east-1
      - HOSTNAME=localstack
      - LAMBDA_EXECUTOR=docker
      - DOCKER_HOST=tcp://docker.for.win.localhost:2375
    expose:
      - "4566-4584"
    ports:
      - "4566-4584:4566-4584"
```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
NodeJS code to fill bucket, and then listObjectsV2 calls:

    const AWS = require('aws-sdk');
    
    main = async () => {
      const s3 = new AWS.S3({
        endpoint: 'http://localhost:4566',
        s3ForcePathStyle: true,
        accessKeyId: 'foobar',
        secretAccessKey: 'foobar',
        region: 'none',
        signatureVersion: 'v4',
        correctClockSkew: true,
        maxRetries: 3,
      });
      console.log('uploading...');
      for(index = 0; index < 420; index++){
        await s3.putObject({
          Bucket: 'content-management',
          Key: `stuff-${index}`,
          Body: 'test',
        }).promise();
      }
    
      console.log(`\n@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@\n`);
    
      const resultWithUndefined = await s3.listObjectsV2({
        Bucket: 'content-management',
        ContinuationToken: undefined,
        MaxKeys: 1,
      }).promise();
      console.log(resultWithUndefined);
    
      const resultWithEmpty = await s3.listObjectsV2({
        Bucket: 'content-management',
        ContinuationToken: '',
        MaxKeys: 1,
      }).promise();
      console.log(resultWithEmpty);
    };
    
    return main();Feel free to let me know if this behavior is not supposed to be implemented in the free localstack version or if I can improve this report in any way.
Thanks.

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-354) by [Unito](https://www.unito.io/learn-more)

**Comment by irahulranjan** [comment]
https://github.com/spulec/moto/pull/3545

**Comment by irahulranjan** [comment]
@whummer this is merged so we can close the issue.

**Comment by irahulranjan** [comment]
@bouergh This should be fixed in the latest version, can you pull and give it a shot?
Thanks.
