### ISSUE TITLE
Cognito OAuth2 TOKEN refreshtoken 

### ISSUE THREAD

**Issue by David-G-I** [localstack/localstack#3283]
# Type of request: This is a feature request.

# Detailed description
During the integration tests of the OAuth Flows via Cognito, I stumbled upon following issue:

Sending a request to http://localhost:4566/oauth2/token with grant_type = refresh_token returns 
{"__type": "Exception", "message": "Unsupported grant_type attribute: refresh_token"}

grant_type = authorization_code works as expected.

Can be easily reproduced with postman once the localstack container is running. 
LocalStack container version 0.12.2

**Comment by whummer** [comment]
Thanks for reporting @David-G-I , and apologies for the delay. This should be fixed in the meantime - can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists. Thanks for your help!
