### ISSUE TITLE
How to view S3 buckets?

### ISSUE THREAD

**Issue by guoliang** [localstack/localstack#3284]
# Detailed description
Since 0.11.0, all services resides on the same port. So e.g. I wanna check S3 bucket prior I went to `localhost:<port>/<bucket-name>`. Now with the new version I'm not sure how to. I tried with `localhost:4566/S3/<bucket-name>` and it seems to react to it but it resulted with bucket not found.

**Comment by pinzon** [comment]
Hi. you don't need to add S3 to the URL. 
It should be like this: `localhost:4566/<bucket-name>`

**Comment by guoliang** [comment]
> Hi. you don't need to add S3 to the URL.
> It should be like this: `localhost:4566/<bucket-name>`

If I enter `localhost:4566/<my-bucket-name>` 
It just go to a page where it says
![image](https://user-images.githubusercontent.com/542598/100379564-66148780-3015-11eb-82a8-c4a51bf8ad64.png)

But if I enter `localhost:4566/s3/<my-bucket-name>` 
It actually goes to page where it says that the bucket doesn't exist

![image](https://user-images.githubusercontent.com/542598/100379749-b55ab800-3015-11eb-8dbe-7bf6f24fa72b.png)

If it helps, I'm running localstack on Windows 10. I booted it up with the recommendation `> localstack start`

**Comment by pinzon** [comment]
That's the right behaviour.  In the second URL  you're looking for the bucket names **s3/\<my-bucket-name\>**

S3 service doesn't provide a file system.
You can read more about it here: [Configuring an index document](https://docs.aws.amazon.com/AmazonS3/latest/dev/IndexDocumentSupport.html)

**Comment by guoliang** [comment]
Ahh, I understand now. Thanks!
