### ISSUE TITLE
Getting No space left on device when trying to create a lambda using awslocal

### ISSUE THREAD

**Issue by ilaneden** [localstack/localstack#3290]
# Type of request: This is a ...

[* ] bug report
[ ] feature request

# Detailed description

When running the command awslocal \
                    lambda create-function I am getting the next error:
`An error occurred (InternalFailure) when calling the CreateFunction operation (reached max retries: 4): Unknown error: [Errno 28] No space left on device Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 957, in create_function
    result = set_function_code(func_details.code, lambda_name)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 724, in set_function_code
    lambda_cwd = lambda_cwd or set_archive_code(code_passed, lambda_name)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 702, in set_archive_code
    save_file(tmp_file, zip_file_content)
  File "/opt/code/localstack/localstack/utils/common.py", line 749, in save_file
    f.write(content)
OSError: [Errno 28] No space left on device

`
...

## Expected behavior

...

## Actual behavior

...

# Steps to reproduce

## Command used to start LocalStack

...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

...

**Comment by whummer** [comment]
Thanks for reporting @ilaneden . This indicates that your Docker environment is running out of disk space. Please use the commands `docker ps -a`, `docker rm ...` and `docker rmi ...` to delete unused containers and images to free up space. Thanks
