### ISSUE TITLE
test-invoke-method returns nothing

### ISSUE THREAD

**Issue by guoliang** [localstack/localstack#3291]
# Type of request: This is a ...

[ X ] bug report

# Detailed description
I have deployed a cloudformation definition with cdklocasl to localstack. It consist of a lambda function and RESTAPI to call it.

I can call it with the following URL
`http://localhost:4566/restapis/<rest-api-id>/<stage>/_user_request_/<method-name>`
However when I call with with aws-cli-local
`awslocal apigateway test-invoke-method --rest-api-id <id> --resource-id <id> --http-method GET`
It returns nothing.

The same command to AWS I get a response however.

## Expected behavior
Calling
`awslocal apigateway test-invoke-method --rest-api-id <id> --resource-id <id> --http-method GET`
returns nothing

## Actual behavior

Should return something

# Steps to reproduce

## Command used to start LocalStack

`localstack start`

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
Created a CDK project with the following cloud stack
```
import * as cdk from '@aws-cdk/core';

import * as lambda from "@aws-cdk/aws-lambda";
import * as apigateway from "@aws-cdk/aws-apigateway";

export class HelloWorldLocalStack extends cdk.Stack {
  constructor(scope: cdk.App, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const dynamoLambda = new lambda.Function(this, "DynamoLambdaHandler", {
			runtime: lambda.Runtime.NODEJS_12_X,
			code: lambda.Code.fromAsset("./functions"),
			handler: "function.handler",
    });

    // create API Gateway so lambda method can be accessed via REST API
    const api = new apigateway.RestApi(this, "hello-api");
    api.root.resourceForPath("hello")
      .addMethod("GET", new apigateway.LambdaIntegration(dynamoLambda));

    new cdk.CfnOutput(this, "HTTP API URL", {
      value : api.url ?? "Something went wrong with the deploy"
    });
  }
}

```

Deployed with 
`cdklocal deploy`

**Comment by calvernaz** [comment]
Hi @guoliang its been a long time since you opened this issue, this works in the latest version. If you still looking for this fix, please give it a try with the latest image.
