### ISSUE TITLE
localstack S3 service does not return Access-Control-Allow-Credentials header in response

### ISSUE THREAD

**Issue by portends** [localstack/localstack#3292]
# Type of request: This is a ...

[ x ] bug report
[ ] feature request

# Detailed description
Access-Control-Allow-Credentials is removed from the s3 response header
...

## Expected behavior
Access-Control-Allow-Credentials is returned when it is requested for
...

## Actual behavior
Access-Control-Allow-Credentials header is not returned in the response
...

# Steps to reproduce

## Command used to start LocalStack
...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
...

**Comment by whummer** [comment]
Thanks for reporting @portends . Added in #3309 - can you please pull the `latest` Docker image and give it another try? Please report here if the problem persists. Thanks
