### ISSUE TITLE
Lambda triggered by S3 event unable to access S3 file

### ISSUE THREAD

**Issue by OmarV-Ssense** [localstack/localstack#3298]
# Type of request: This is a ...

[X] bug report
[ ] feature request

# Detailed description
I'm trying to use localstack to set up a local docker environment with a lambda triggered by an s3 event. For this, I use the serverless framework with the `serverless-localstack` plugin. So far I have been able to deploy the lambda and make the trigger work, but I haven't been able to read the contents from the s3 file that triggered the lambda. I get an error that says `Missing credentials in config`. I made sure to add the `iamRoleStatements` properly in the `serverless.yml` file to grant access to S3.

I've tried a few things to make it work but no success so far:
- Attaching the `AmazonS3FullAccess` policy to the lambda role via aws cli using `awslocal`. The policy doesn't seem to attach properly to the role, when I list again the policies only the STS one appears, not the s3 one.
- Logging into the localstack container and executing manually the cmd to launch the `lambci/lambda` container. I noticed that the env variables with the access keys are not passed in the command, so I figured I could try passing them along like this:
```
docker run -i -v "/tmp/localstack/zipfile.b71cabbb":/var/task -e AWS_DEFAULT_REGION="us-east-1" -e AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID" -e AWS_SECRET_ACCESS_KEY="$AWS_SECRET_ACCESS_KEY" -e DOCKER_LAMBDA_USE_STDIN="$DOCKER_LAMBDA_USE_STDIN" -e LOCALSTACK_HOSTNAME="$LOCALSTACK_HOSTNAME" -e EDGE_PORT="$EDGE_PORT" -e _HANDLER="$_HANDLER" -e AWS_LAMBDA_FUNCTION_TIMEOUT="$AWS_LAMBDA_FUNCTION_TIMEOUT" -e AWS_LAMBDA_FUNCTION_NAME="$AWS_LAMBDA_FUNCTION_NAME" -e AWS_LAMBDA_FUNCTION_VERSION="$AWS_LAMBDA_FUNCTION_VERSION" -e AWS_LAMBDA_FUNCTION_INVOKED_ARN="$AWS_LAMBDA_FUNCTION_INVOKED_ARN" -e AWS_LAMBDA_COGNITO_IDENTITY="$AWS_LAMBDA_COGNITO_IDENTITY" -e NODE_TLS_REJECT_UNAUTHORIZED="$NODE_TLS_REJECT_UNAUTHORIZED" --rm "lambci/lambda:nodejs12.x" "handler.handler"
```
But for this ^ I get an error that says `The AWS Access Key Id you provided does not exist in our records.`

Help will be very appreciated.

## Expected behavior
The lambda can take the creds from the role assigned to it and access the s3 resources according to the config set in `serverless.yml`

## Actual behavior
`Missing credentials in config` error.

# Steps to reproduce

## Command used to start LocalStack
`docker-compose up`

docker-compose.yml:
```
version: '3.7'
services:

  localstack:
    image: localstack/localstack
    ports:
      - '4563-4584:4563-4584'
      - '8080:8080'
    
    environment:
      - SERVICES=s3,lambda,cloudformation,sts,iam
      - DEBUG=true
      - LAMBDA_EXECUTOR=docker
      - LAMBDA_REMOTE_DOCKER=false
      - DOCKER_HOST=unix:///var/run/docker.sock
      - START_WEB=1la
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=publickey
      - AWS_SECRET_ACCESS_KEY=secretkey

    volumes:
      - /tmp/localstack:/tmp/localstack
      - "/var/run/docker.sock:/var/run/docker.sock"
```

severless.yml
```
service: a-service
frameworkVersion: '2'

plugins:
  - serverless-localstack

provider:
  name: aws
  runtime: nodejs12.x
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: "*"

custom:
  s3Settings:
    bucket: 'bucket'
  localstack:
    debug: true
    stages:
      - local
    host: http://localhost 
    edgePort: 4566
    autostart: true
    docker:
      sudo: False

functions:
  loader:
    handler: handler.handler
    events:
      - s3:
          bucket: ${self:custom.s3Settings.bucket}
          existing: true
          event: s3:*
```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
```
async function createReadStream(fileDetails) {
    const s3Client = new aws.S3({apiVersion: '2006-03-01', region: 'us-east-1'});
    const s3FileObject = {
        Bucket: 'bucket',
        Key: fileDetails
    };

    try {
        const s3Obj = await s3Client.getObject(s3FileObject).promise();
        return s3Obj.createReadStream();
    } catch (error) {
        console.log(`error while trying to get object: ${error.message}`);
    }
}
```

**Comment by OmarV-Ssense** [comment]
UPDATE:
I was able to make it work manually by logging into the localstack docker container and running the command manually with the following tweaks:
- Pass more env variables to the `docker` cmd that will launch the lambci/lambda container:
   ```
   -e LOCALSTACK_HOSTNAME="172.17.0.1"
   -e AWS_DEFAULT_REGION="us-east-1"
   -e AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID"
   -e AWS_SECRET_ACCESS_KEY="$AWS_SECRET_ACCESS_KEY"
   ```
- Force the `LOCALSTACK_HOSTNAME` variable to be `172.17.01` instead of the regular `localhost` IP address that localstack sets by default

So, in summary, by letting the s3 trigger launch the lambda, the generated lambci/lambda command is:
```
docker run -i  -v "/tmp/localstack/zipfile.ce79eb2c":/var/task
-e DOCKER_LAMBDA_USE_STDIN="$DOCKER_LAMBDA_USE_STDIN"
-e LOCALSTACK_HOSTNAME="$LOCALSTACK_HOSTNAME"
-e EDGE_PORT="$EDGE_PORT"
-e _HANDLER="$_HANDLER"
-e AWS_LAMBDA_FUNCTION_TIMEOUT="$AWS_LAMBDA_FUNCTION_TIMEOUT"
-e AWS_LAMBDA_FUNCTION_NAME="$AWS_LAMBDA_FUNCTION_NAME"
-e AWS_LAMBDA_FUNCTION_VERSION="$AWS_LAMBDA_FUNCTION_VERSION"
-e AWS_LAMBDA_FUNCTION_INVOKED_ARN="$AWS_LAMBDA_FUNCTION_INVOKED_ARN"
-e AWS_LAMBDA_COGNITO_IDENTITY="$AWS_LAMBDA_COGNITO_IDENTITY"
-e NODE_TLS_REJECT_UNAUTHORIZED="$NODE_TLS_REJECT_UNAUTHORIZED"
--rm "lambci/lambda:nodejs12.x" "handler.handler"
```

While the complete working cmd is:
```
docker run -i -v "/tmp/localstack/zipfile.ce79eb2c":/var/task
-e LOCALSTACK_HOSTNAME="172.17.0.1"
-e AWS_DEFAULT_REGION="us-east-1"
-e AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID"
-e AWS_SECRET_ACCESS_KEY="$AWS_SECRET_ACCESS_KEY"
-e DOCKER_LAMBDA_USE_STDIN="$DOCKER_LAMBDA_USE_STDIN"
-e EDGE_PORT="$EDGE_PORT"
-e _HANDLER="$_HANDLER"
-e AWS_LAMBDA_FUNCTION_TIMEOUT="$AWS_LAMBDA_FUNCTION_TIMEOUT"
-e AWS_LAMBDA_FUNCTION_NAME="$AWS_LAMBDA_FUNCTION_NAME"
-e AWS_LAMBDA_FUNCTION_VERSION="$AWS_LAMBDA_FUNCTION_VERSION"
-e AWS_LAMBDA_FUNCTION_INVOKED_ARN="$AWS_LAMBDA_FUNCTION_INVOKED_ARN"
-e AWS_LAMBDA_COGNITO_IDENTITY="$AWS_LAMBDA_COGNITO_IDENTITY" 
-e NODE_TLS_REJECT_UNAUTHORIZED="$NODE_TLS_REJECT_UNAUTHORIZED"
--rm "lambci/lambda:nodejs12.x" "handler.handler"
```

So the remaining questions on my end would be:
- What should I do so that the automatically generated command includes the missing env variables (LOCALSTACK_HOSTNAME, AWS_DEFAULT_REGION, AWS_ACCESS_KEY_ID, and AWS_SECRET_ACCESS_KEY)?
- How should I force the `LOCALSTACK_HOSTNAME` env variable to `172.17.0.1` so that's the IP that the lambci/lambda container uses and why do I need to do this?

Thanks again

**Comment by whummer** [comment]
Thanks for reporting @OmarV-Ssense . The error message `The AWS Access Key Id you provided` indicates that the code in your Lambda is trying to access real AWS instead of the local LocalStack endpoint.

Please make sure to use the `LOCALSTACK_HOSTNAME` environment variable that gets passed to your Lambda handler (see notes in the README) and use it to configure the `endpoint` when constructing your AWS SDK client.

Please refer to an example in our integration tests here (the code is in Python, but it should work analogously in Node.js): https://github.com/localstack/localstack/blob/a63dcd30c475d5c2cf035703e40783c4cb5e3e9e/tests/integration/lambdas/lambda_send_message.py#L9-L10

Hope that helps - please keep us posted if the problem persists. Thanks

**Comment by OmarV-Ssense** [comment]
@whummer thank you for following up. Like I mentioned in my update comment, the problem seems to be that the command generated by localstack to pass on to the lambci/lambda container launched internally doesn't attach the environment variables. I was able to make it work manually with the second command that I mentioned. My question became how can I make sure that those env variables needed for the command to work are passed properly. Please see my [update commen](https://github.com/localstack/localstack/issues/3298#issuecomment-737518996)t for context
