### ISSUE TITLE
NodeJS Lambda trigger from Kinesis stream is hanging there for long time

### ISSUE THREAD

**Issue by njcongtou** [localstack/localstack#330]
I created a dummy stream and a Lambda function called hello in NodeJS 6.10. I would like to trigger lambda by the stream but does not work. 

1. I created Lambda function without any issue since I used hello world nodejs sample from AWS console. I downloaded that deployment package and created function in Localstack with no issues. 

2. I created stream with no issue. 

3. I use docker as Lambda executor since NodeJS Lambda needs it. My docker-compose file is as follows:

  localstack:
    image: localstack/localstack
    ports:
      - "4567-4582:4567-4582"
      - "8080:8080"
    environment:
      - SERVICES=${SERVICES-lambda, kinesis, s3}
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - LAMBDA_EXECUTOR=docker
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/tmp/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

How I tested it: 

1. I tried to invoke the Lambda by using invoke function. It returns 200 immediately but there is no hello world printed in the docker console. 

awslocal lambda \
    invoke \
    --function-name test \
    --no-verify-ssl \
    --payload 'sample_doc.json' \
    result.log

I tried to send a json doc. 

2. I send the sample json doc to kinesis stream which has mapping info the correct Lambda function. 

The result I got is the timeout due to slow response from Localstack services. It is hanging for a long time and then timed out. I can see there are something printed on the Localstack console. 

localstack_1     | docker run -v "/tmp/localstack/zipfile.3237f24f":/var/task -e AWS_LAMBDA_EVENT_BODY="$AWS_LAMBDA_EVENT_BODY" -e HOSTNAME="$HOSTNAME" "lambci/lambda:nodejs6.10" "index.handler"

localstack_1     | docker run -v "/tmp/localstack/zipfile.3237f24f":/var/task -e AWS_LAMBDA_EVENT_BODY="$AWS_LAMBDA_EVENT_BODY" -e HOSTNAME="$HOSTNAME" "lambci/lambda:nodejs6.10" "index.handler"

localstack_1     | docker run -v "/tmp/localstack/zipfile.3237f24f":/var/task -e AWS_LAMBDA_EVENT_BODY="$AWS_LAMBDA_EVENT_BODY" -e HOSTNAME="$HOSTNAME" "lambci/lambda:nodejs6.10" "index.handler"

So I think the Lambda function is triggered properly by the stream, but I am not sure why it is too slow to response. Since my Lambda is only a hello world example. 

Could someone help me with this issue ?

**Comment by whummer** [comment]
@njcongtou have you been able to resolve this issue? What was the fix? Thanks

**Comment by njcongtou** [comment]
No, I don't have a solution yet. I opened another Issue with more info. Did you have the same issue ?

**Comment by njcongtou** [comment]
https://github.com/localstack/localstack/issues/333
