### ISSUE TITLE
SNS DeleteTopic appears to not delete the resource and prevents recreation under different tags

### ISSUE THREAD

**Issue by FloatingGhost** [localstack/localstack#3304]
# bug report

# Detailed description

Creating a topic, deleting it, and then creating a new topic with the same name with different tags will throw `An error occurred (InvalidParameter) when calling the CreateTopic operation: Topic already exists with different tags`, even when `ListTopics` shows an empty list.

Something, somewhere is retaining list config even after deletion

Weirdly, creating with the _same_ tags seems to be ok. 

## Expected behavior

After deleting a topic, I should be able to create another one with the same name, with different tags.

## Actual behavior

The localstack response claims that the deleted resource is preventing creation of a new resource

# Steps to reproduce

## Command used to start LocalStack
```bash
docker run -it -e SERVICES=sns -p 4566:4566 localstack/localstack:0.12.2
```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
```bash
awslocal sns create-topic --name test --tags Key=tag,Value=value

# Topic created                
awslocal sns list-topics

awslocal sns delete-topic --topic-arn arn:aws:sns:us-east-1:000000000000:test

# This will return an empty list, it's "deleted"
awslocal sns list-topics

awslocal sns create-topic --name test --tags Key=tag,Value=someOtherValue

# Error thrown
```

**Comment by whummer** [comment]
Thanks for reporting @FloatingGhost . This should be fixed in #3306 - can you please pull the `latest` Docker image and give it another try? Please report here if the problem persists. Thanks
