### ISSUE TITLE
Integrate the possibility to add SNS as a target type for EventBridge

### ISSUE THREAD

**Issue by george-cionca** [localstack/localstack#3308]
# Type of request: This is a ...

[ ] bug report
[x] feature request

# Detailed description

After creating an event bus in EventBridge, I added a rule for sending the events to a target represented by an SNS topic.

I checked the logs and noticed that an integration between EventBridge and SNS is not currently implemented:

```python
localstack    | 2020-12-05T19:17:10:WARNING:localstack.services.events.events_starter: Unsupported Events target service type "sns"
```

I want to mention that I am currently using the ```latest``` Docker image.

I think the integration would have to be defined here: https://github.com/localstack/localstack/blob/master/localstack/services/events/events_starter.py#L97-L113

## Expected behavior

Sending an event that matches a specific rule to the event bus with **put-events** should forward the event to the SNS topic.

## Actual behavior

Sending an event that matches a specific rule to the event bus with **put-events** doesn't forward the event to the SNS topic.

**Comment by whummer** [comment]
Thanks for reporting @george-cionca . This should be fixed in #3342 - can you please pull the `latest` Docker image and give it another try? Please report here if the problem persists. Thanks
