### ISSUE TITLE
VPC endpoints misbehaving

### ISSUE THREAD

**Issue by clebio** [localstack/localstack#3310]
# Type of request: This is a ...

- [x] bug report
- [ ] feature request

# Detailed description

VPC endpoints are failing

## Expected behavior

`aws ec2 describe-vpc-endpoints` works

## Actual behavior

```

$ aws ec2 --region us-west-2 --endpoint-url=http://127.0.0.1:4566 describe-vpc-endpoints

Unable to parse response (syntax error: line 1, column 54), invalid XML received. Further retries may succeed:
b'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">\n<title>500 Internal Server Error</title>\n<h1>Internal Server Error</h1>\n<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>\n'
```

# Steps to reproduce

1. `docker run --rm -d -p 4566:4566 --name localstack localstack/localstack`
2. `aws ec2 --region us-west-2 --endpoint-url=http://127.0.0.1:4566 describe-vpc-endpoints`

## Command used to start LocalStack

`docker run --rm -d -p 4566:4566 --name localstack localstack/localstack`

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

```
$ aws --version
aws-cli/2.0.40 Python/3.8.5 Darwin/18.7.0 source/x86_64
```

Related:

* #2650

**Comment by whummer** [comment]
Thanks for reporting @clebio . This should be fixed upstream in spulec/moto#3524 - can you please pull the `latest` Docker image and give it another try? Please report here if the problem persists. Thanks

**Comment by sworisbreathing** [comment]
@whummer - Thanks for the quick turnaround!
I've just pulled down the `localstack/localstack-full:latest`. Here's what I see.

Fresh environment after `docker-compose up`:
```bash
$ aws --profile=localstack --endpoint-url=http://localhost:4566 ec2 describe-vpc-endpoints
{
    "VpcEndpoints": []
}
```

After running my terraform templates:

```
$ aws --profile=localstack --endpoint-url=http://localhost:4566 ec2 describe-vpc-endpoints
{
    "VpcEndpoints": [
        {
            "VpcEndpointId": "vpce-44cc95e4",
            "VpcEndpointType": "Gateway",
            "VpcId": "vpc-44cc95e4",
            "ServiceName": "com.amazonaws.ap-southeast-2.s3",
            "State": "available",
            "PrivateDnsEnabled": false,
            "CreationTimestamp": "2020-12-10T23:24:22.663273Z",
            "OwnerId": "123456789012"
        }
    ]
}
```

So it looks like the change got pulled into localstack successfully, but the owner/account ID is wrong. Localstack uses `000000000000`

**Comment by sworisbreathing** [comment]
I've raised spulec/moto#3539 to fix up the account id

**Comment by sworisbreathing** [comment]
I tested this a bit further this morning and it looks like there are more issues with moto's support for vpc endpoints, which I've raised in spulec/moto#3540
