### ISSUE TITLE
localstack lambda S3.put_object throws error while same function via S3 doesn't 

### ISSUE THREAD

**Issue by manas86** [localstack/localstack#3311]
# Type of request: This is a ...

[X ] bug report
[ ] feature request

# Detailed description
This is my lambda
```
def handler(event, context):
    LOGGER.info('putting something in S3')
    test_object_key = 'a-object-{0}'.format(date.today())
    more_binary_data = b'some body'
    S3_CLIENT.put_object(
        Bucket='a-bucket',
        Key=test_object_key,
        Body=more_binary_data
    )
    return {
        "message": "{0} placed into S3".format(test_object_key)
    }
```
as soon as I create lambda function and run this lambda, I get the below error

`(localstack_main | Exception: Lambda process returned error status code: 1. Result: {"errorMessage": "Could not connect to the endpoint URL: \"http://localhost:4566/a-bucket/a-object-2020-12-06\"", "errorType": "EndpointConnectionError", "stackTrace": [["/var/task/lambda.py", 27, "handler", "Body=more_binary_data"], ["/var/runtime/botocore/client.py", 357, "_api_call", "return self._make_api_call(operation_name, kwargs)"], ["/var/runtime/botocore/client.py", 648, "_make_api_call", "operation_model, request_dict, request_context)"], ["/var/runtime/botocore/client.py", 667, "_make_request", "return self._endpoint.make_request(operation_model, request_dict)"], ["/var/runtime/botocore/endpoint.py", 102, "make_request", "return self._send_request(request_dict, operation_model)"], ["/var/runtime/botocore/endpoint.py", 137, "_send_request", "success_response, exception):"], ["/var/runtime/botocore/endpoint.py", 231, "_needs_retry", "caught_exception=caught_exception, request_dict=request_dict)"], ["/var/runtime/botocore/hooks.py", 356, "emit", "return self._emitter.emit(aliased_event_name, **kwargs)"], ["/var/runtime/botocore/hooks.py", 228, "emit", "return self._emit(event_name, kwargs)"], ["/var/runtime/botocore/hooks.py", 211, "_emit", "response = handler(**kwargs)"], ["/var/runtime/botocore/retryhandler.py", 183, "__call__", "if self._checker(attempts, response, caught_exception):"], ["/var/runtime/botocore/retryhandler.py", 251, "__call__", "caught_exception)"], ["/var/runtime/botocore/retryhandler.py", 277, "_should_retry", "return self._checker(attempt_number, response, caught_exception)"], ["/var/runtime/botocore/retryhandler.py", 317, "__call__", "caught_exception)"], ["/var/runtime/botocore/retryhandler.py", 223, "__call__", "attempt_number, caught_exception)"], ["/var/runtime/botocore/retryhandler.py", 359, "_check_caught_exception", "raise caught_exception"], ["/var/runtime/botocore/endpoint.py", 200, "_do_get_response", "http_response = self._send(request)"], ["/var/runtime/botocore/endpoint.py", 244, "_send", "return self.http_session.send(request)"], ["/var/runtime/botocore/httpsession.py", 282, "send", "raise EndpointConnectionError(endpoint_url=request.url, error=e)"]]}. Output:)`

however, if I execute the same functionality using s3 boto3 it works like a charm:

```
if __name__ == '__main__':
    s3_client = get_s3_client()
s3_client.create_bucket(
                                  Bucket='a-bucket'
                            )
    test_object_key = 'a-object-{0}'.format(date.today())
    more_binary_data = 'some body'
    s3_client.put_object(
        Bucket='a-bucket',
        Key=test_object_key,
        Body=more_binary_data
    )
 print(s3_client.list_objects_v2(Bucket='a-bucket')['Contents'])
```
## Expected behavior

both lambda and s3 should behave exactly same.

## Actual behavior

...

# Steps to reproduce

## Command used to start LocalStack

...

**Comment by Kavyeshs41** [comment]
Hello @manas86, Thanks for reporting the issue. 
Can you please try obtaining the value of the LOCALSTACK_HOSTNAME variable from within your Lambda function to connect the S3 endpoint? 

`s3_endpoint = 'http://%s:4566' % os.environ['LOCALSTACK_HOSTNAME']`

The full code snippet looks something like this. 

```
import os
import boto3

s3_endpoint = 'http://%s:4566' % os.environ['LOCALSTACK_HOSTNAME']
s3_client = boto3.client('s3',endpoint_url=s3_endpoint,aws_access_key_id='test', aws_secret_access_key='test')

def handler(event, context):
    test_object_key = 'a-object'
    more_binary_data = b'some body'
    s3_client.create_bucket(Bucket='a-bucket')
    s3_client.put_object(
        Bucket='a-bucket',
        Key=test_object_key,
        Body=more_binary_data
    )
    return {
        "message": "{0} placed into S3".format(test_object_key)
    }
```

This will hopefully resolve your issue. Please report here if the problem still persists after these changes. Thanks!

**Comment by whummer** [comment]
Thanks for the update @manas86 @Kavyeshs41 - indeed, this looks like a usage issue that should be resolved by using the `LOCALSTACK_HOSTNAME` in your endpoint configuration. Thanks
