### ISSUE TITLE
SNS subscriptions for HTTP endpoints aren't confirmed. No notifications sent to HTTP endpoints.

### ISSUE THREAD

**Issue by BjoernKW** [localstack/localstack#3314]
# Type of request: This is a ...

[X] bug report
[ ] feature request

# Detailed description

When subscribing to an SNS topic with an HTTP endpoint that subscription isn't confirmed by LocalStack. Consequently, notifications won't be received by that HTTP endpoint either.

## Expected behavior

An HTTP endpoint subscription is confirmed and afterwards notifications are sent to that HTTP endpoint.

## Actual behavior

The subscription isn't confirmed and no notifications are sent.

# Steps to reproduce

1. Start LocalStack via Docker on port 4566.
2. Start local application.
3. Run `TEST_ARN=$(aws sns create-topic --endpoint-url http://localhost:4566--name test--output text --query 'TopicArn')``
4. Run
```
aws sns subscribe \
  --endpoint-url http://localhost:4566 \
  --topic-arn $TEST_ARN \
  --protocol http \
  --notification-endpoint http://host.docker.internal:8080/test
```
5. Run
```
aws sns publish \
  --topic-arn $TEST_ARN \
  --message "Test" \
  --endpoint-url http://localhost:4566
```

## Command used to start LocalStack

LocalStack is started via _docker-compose.yml_:

```
version: '3.3'

services:
  localstack:
    image: localstack/localstack:0.12.2
    ports:
      - 4566:4566
    environment:
      - SERVICES=sqs,sns,ses
      - DEFAULT_REGION=eu-central-1
```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

Please note: Neither `  --notification-endpoint http://localhost:8080/test` nor `  --notification-endpoint http://host.docker.internal:8080/test` as endpoints in the AWS CLI commands below result in the desired behaviour. So, doesn't seem to be a Docker network issue.

```
TEST_ARN=$(aws sns create-topic --endpoint-url http://localhost:4566--name test--output text --query 'TopicArn')

aws sns subscribe \
  --endpoint-url http://localhost:4566 \
  --topic-arn $TEST_ARN \
  --protocol http \
  --notification-endpoint http://host.docker.internal:8080/test

aws sns publish \
  --topic-arn $TEST_ARN \
  --message "Test" \
  --endpoint-url http://localhost:4566
```

**Comment by usmangani1** [comment]
@BjoernKW Thanks for reporting the issue.
This should be fixed in the meantime - can you please pull the latest Docker image and give it another try? Please let us know if the problem persists. Thanks!

**Comment by bentsku** [comment]
Hi @throrin19, this doesn't seem to be the same issue as the reported one here, at the time SNS did not send the message at all.

From your logs, it shows SNS tried to publish to the provided URL, but it seems it can't find it.
Also, it's a 404 error and not a connectivity error, which proves it can communicate but the server listening is not matching your route?

**Comment by throrin19** [comment]
If I curl it it works fine but in POST mode, not in GET mode

**Comment by bentsku** [comment]
Alright, this is a bit weird. But SNS is sending the message, as shown by the logs. The question is: what is returning 404? Do you see the request hitting your local service listening to port `4002` when sending publishing an SNS message?

**Comment by throrin19** [comment]
@bentsku After research it seems the package serverless-offline-sns the problem : it's unmaintained and I use one fork. I decided to change all the process and develop my own brick to resolve this problem.

thanks for your help.
