### ISSUE TITLE
S3 returns BucketNotEmpty when attempting to delete a non-existent bucket

### ISSUE THREAD

**Issue by FloatingGhost** [localstack/localstack#3316]
[x] bug report

# Detailed description

If you attempt to delete a bucket that does not exist, localstack will return the wrong error code

## Expected behavior

`NoSuchBucket` should be returned

## Actual behavior

`BucketNotEmpty` is returned

# Steps to reproduce

## Command used to start LocalStack

`docker run -it -e SERVICES=s3 -p 4566:4566 localstack/localstack:latest`

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

`awslocal s3api delete-bucket --bucket does-not-exist`

**Comment by whummer** [comment]
Thanks for reporting @FloatingGhost . This should be fixed in #4104 - can you please pull the `latest` Docker image and give it a try? Thanks for your help!
