### ISSUE TITLE
FIFO DLQ locks message group id

### ISSUE THREAD

**Issue by GirishKumar0310** [localstack/localstack#3319]
# Type of request: Defect

[ ] bug report
[ ] feature request

# Detailed description
Configure a FIFO SQS queue and and Dead Letter Queue.
Add a message with message group id say "MSG_GROUP_1", see to that we have lambda handler which fails to process the message which then goes to DLQ

After that if we add another message to SQS with same message group id MSG_GROUP_1, it never gets processed until we remove the first message from DLQ.

In real AWS service, when message gets moved to DLQ, it no more locks the message group id and we can add new messages with same message group id to SQS
...

## Expected behavior
As in AWS service, when message gets moved to DLQ, it should no more lock the message group id and we should be able to can add new messages with same message group id to SQS.

Please refer AWS documentation https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/using-messagegroupid-property.html

...

## Actual behavior
When message is pushed to DLQ, the message group id is blocked from any further processing in the source SQS
...

# Steps to reproduce

Configure a FIFO SQS queue and and Dead Letter Queue.
Add a message with message group id say "MSG_GROUP_1", see to that we have lambda handler which fails to process the message which then goes to DLQ

After that if we add another message to SQS with same message group id MSG_GROUP_1, it never gets processed until we remove the first message from DLQ.

## Command used to start LocalStack

we use docker compose as well as docker run
...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

...

**Comment by irahulranjan** [comment]
https://github.com/spulec/moto/pull/3537

**Comment by NabilCC** [comment]
My team has recently migrated our SQS provider from ElasticMQ > Localstack. 

We are seeing this issue since the migration.

Does anyone have a nicer workaround than purging the DLQ prior after every test to "unlock" the message group? This strategy won't be effective for more complex test scenarios where messages sent after the group has been "locked" by a message handle failure.

**Comment by whummer** [comment]
Thanks for reporting @NabilCC @GirishKumar0310 . This should be fixed in the meantime - can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists. Thanks

**Comment by NabilCC** [comment]
> Thanks for reporting @NabilCC @GirishKumar0310 . This should be fixed in the meantime - can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists. Thanks

Happy to confirm this issue has been resolved with the latest Docker image :-) Many thanks for the swift response! 👍
