### ISSUE TITLE
Unable to add localstack repository using Helm

### ISSUE THREAD

**Issue by harshit-budhraja** [localstack/localstack#3322]
# Type of request: This is a ...

[ ✔️ ] bug report
[ ] feature request

# Detailed description

While trying to add the `localstack` repo using helm, getting a 404 Not Found Error.
Please find the exact trace below:

```
➜  ~ helm repo add localstack-repo https://localstack.github.io/localstack
Error: looks like "https://localstack.github.io/localstack" is not a valid chart repository or cannot be reached: failed to fetch https://localstack.github.io/localstack/index.yaml : 404 Not Found
```

...

## Expected behavior

The repo should be added successfully.

...

## Actual behavior

Repo addition fails with a 404 Error Found.

...

# Steps to reproduce

## Command used to add LocalStack repo using Helm

`helm repo add localstack-repo https://localstack.github.io/localstack`

...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

NA
...

## Additional Information

OS: MacOS Catalina (10.15.7)
Terminal: ZSH
Helm Version: `version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"dirty", GoVersion:"go1.14.3"}`

On trying to open the mentioned charts URL in the browser, nginx throws a 404. Attaching screenshot.

![image](https://user-images.githubusercontent.com/52413945/101459927-e2d12b00-395e-11eb-892b-80bdf369ea17.png)

**Comment by whummer** [comment]
Thanks for reporting @harshit-budhraja . Can you please try adding this repo URL instead: http://helm.localstack.cloud . We'll make sure to update our documentation accordingly. Please let us know if the problem persists. Thanks

**Comment by harshit-budhraja** [comment]
@whummer Thanks for getting back! After changing the URL, it works well 👍🏻
