### ISSUE TITLE
Problem invoking lambda in local executor

### ISSUE THREAD

**Issue by dsvensson** [localstack/localstack#3334]
I've successfully created a lambda via:

```
aws --endpoint-url=http://localhost:4566 lambda create-function --function-name foo --runtime provided.al2 --handler foo --zip-file fileb:///path/to/foo.zip --role arn:aws:iam:local
```

But when I invoke it, localstack complains about the `runtime`:

> _Unable to find executor for Lambda function "foo". Note that Node.js, Golang, and .Net Core Lambdas currently require LAMBDA_EXECUTOR=docker_

The lambda in question is written in `C++` with all its dependencies under a lib-subdirectory, and if I exec into the localstack container and jump to the `/tmp/localstack/zipfile.b6796ea0` directory, I can execute it without problem via:

```
LAMBDA_TASK_ROOT=`pwd` _HANDLER=foo LD_LIBRARY_PATH=`pwd`/lib ./bootstrap
```

No matter what runtime I chose, I get this same error message, and from the looks of the source code, it's obvious that this is a limitation:

https://github.com/localstack/localstack/blob/master/localstack/services/awslambda/lambda_api.py#L730-L812

Doesn't look like there's any way around it.

**Comment by macnev2013** [comment]
Thanks for reporting @dsvensson. Can you provide a zip package which is working on real AWS, It would help us a lot in reproducing the issue. Thanks.

**Comment by mgagliardo** [comment]
Hey @dsvensson, thanks for creating the issue.
I have tested this with the `latest` docker image and it seems to be working for me.
I have created the zipfile and compiled the C++ code following [this doc](https://aws.amazon.com/blogs/compute/introducing-the-c-lambda-runtime/) which is a very basic "Hello world" in C++.
I was unable to reproduce the issue using a similar create-function on my local machine, can you please hand over 

```
$ awslocal lambda create-function --function-name foo --role somerole --runtime provided.al2 --handler hello --zip-file fileb://hello.zip
{
    "FunctionName": "foo",
    "FunctionArn": "arn:aws:lambda:us-east-1:000000000000:function:foo",
    "Runtime": "provided.al2",
    "Role": "somerole",
    "Handler": "hello",
    "CodeSize": 10669858,
    "Description": "",
    "Timeout": 3,
    "LastModified": "2021-02-15T16:43:26.293+0000",
    "CodeSha256": "cKsayAJFNdniNo/hLbJ4S55eYgfHH6U+BE/pbUnKmvw=",
    "Version": "$LATEST",
    "VpcConfig": {},
    "TracingConfig": {
        "Mode": "PassThrough"
    },
    "RevisionId": "2e95140b-1718-4b3f-8596-0bc6480f6cb4",
    "State": "Active",
    "LastUpdateStatus": "Successful",
    "PackageType": "Zip"
}

Lambda invoke:
```
$ awslocal lambda invoke --function-name foo test.txt
```

Output:
```
$ awslocal lambda invoke --function-name foo test.txt
{
    "StatusCode": 200,
    "LogResult": "",
    "ExecutedVersion": "$LATEST"
}
```

And on the localstack DEBUG logs:
```
2021-02-15T16:43:52:WARNING:localstack.services.awslambda.lambda_executors: Empty event body specified for invocation of Lambda "arn:aws:lambda:us-east-1:000000000000:function:foo"
2021-02-15T16:43:52:INFO:localstack.services.awslambda.lambda_executors: Running lambda cmd: CONTAINER_ID="$(docker create -i   -e DOCKER_LAMBDA_USE_STDIN="$DOCKER_LAMBDA_USE_STDIN" -e LOCALSTACK_HOSTNAME="$LOCALSTACK_HOSTNAME" -e EDGE_PORT="$EDGE_PORT" -e _HANDLER="$_HANDLER" -e AWS_LAMBDA_FUNCTION_TIMEOUT="$AWS_LAMBDA_FUNCTION_TIMEOUT" -e AWS_LAMBDA_FUNCTION_NAME="$AWS_LAMBDA_FUNCTION_NAME" -e AWS_LAMBDA_FUNCTION_VERSION="$AWS_LAMBDA_FUNCTION_VERSION" -e AWS_LAMBDA_FUNCTION_INVOKED_ARN="$AWS_LAMBDA_FUNCTION_INVOKED_ARN" -e AWS_LAMBDA_COGNITO_IDENTITY="$AWS_LAMBDA_COGNITO_IDENTITY"   --rm "lambci/lambda:provided.al2" "hello")";docker cp "/tmp/localstack/zipfile.5b29ae80/." "$CONTAINER_ID:/var/task"; docker start -ai "$CONTAINER_ID";
2021-02-15T16:43:53:DEBUG:localstack.services.awslambda.lambda_executors: Lambda arn:aws:lambda:us-east-1:000000000000:function:foo result / log output:
Hello, World!
```

As you can see the code is pretty straightforward:
```
#include <aws/lambda-runtime/runtime.h>

using namespace aws::lambda_runtime;

invocation_response my_handler(invocation_request const& request)
{
   return invocation_response::success("Hello, World!", "application/json");
}

int main()
{
   run_handler(my_handler);
   return 0;
}
```

Can you please show an example of the code you are using, how you are compiling it and what are you using as invoke function?  I also did not use any `LAMBDA_EXECUTOR` or ENV vars other than `SERVICES=lambda` and `DEBUG=1`.

Thanks!

**Comment by dsvensson** [comment]
Cool, perhaps fixed by the recent refactorings. Will have to try again. Looks like a lot of the code has changed.

**Comment by mgagliardo** [comment]
Sure, please check again and let us know. Thanks!
