### ISSUE TITLE
Question on Aurora with Localstack

### ISSUE THREAD

**Issue by guoliang** [localstack/localstack#3335]
### Type of request:

Question

### Detailed description

I looked into what localstack offers, and did not see that Aurora or Aurora Serverless is support.
So I'm just wondering what would the approach for me to develop lambda locally to run it against Aurora?
Would the solution be a hybrid where I run lambda locally with localstack, and CRUD operation will go to AWS?

**Comment by guoliang** [comment]
Even Aurora Serverless is available in PRO edition?
Because what I found is that connecting to, and then do CRUD is differently to a Aurora Serverless than with Aurora RDS.

**Comment by tiagotaveiragomes** [comment]
I am also interested in having aurora serverless and data api available in localstack

**Comment by thrau** [comment]
We have aurora serverless support through RDS in pro, see [feature coverage](https://github.com/localstack/localstack/blob/master/doc/feature_coverage.md). Please let us know if you have specific feature requests!
