### ISSUE TITLE
SNS Fifo topic 

### ISSUE THREAD

**Issue by nvedansh** [localstack/localstack#3336]
# Type of request: This is a bug report

# Detailed description
`aws --endpoint-url=http://localhost:4575 sns create-topic --name command_post_topic.fifo --attributes FifoTopic=true --attributes ContentBasedDeduplication=false --region us-east-1`

When the above command is executed the following error is thrown

> _**`An error occurred (InvalidParameterValue) when calling the CreateTopic operation: Topic names must be made up of only uppercase and lowercase ASCII letters, numbers, underscores, and hyphens, and must be between 1 and 256 characters long.`**_

Here the error is thrown because of the ".fifo" suffix which is necessary according to AWS. So not able to create a topic with 'fifo' suffix.

**Comment by nickcaballero** [comment]
Does this mean that SNS and SQS Pub/Sub will be supported? https://aws.amazon.com/blogs/aws/introducing-amazon-sns-fifo-first-in-first-out-pub-sub-messaging/

**Comment by wellermiranda** [comment]
+1

**Comment by Josh-Rosen** [comment]
+1

**Comment by PRASANTHRAJENDRAN** [comment]
Will the SNS FIFO topic and SNS SQS queue support will be available in localstack upcoming versions?

**Comment by whummer** [comment]
Thanks @nvedansh @nickcaballero @wellermiranda @Josh-Rosen @PRASANTHRAJENDRAN - this has been added in the meantime and should be available in the `latest` version of the Docker image. Can you please give it another try and let us know if it works? Thanks

**Comment by jgoux** [comment]
Hello @whummer , I'm on latest and still have this error.

```
2021-02-22T09:36:59:WARNING:localstack.utils.cloudformation.template_deployer: Error calling <bound method ClientCreator._create_api_method.<locals>._api_call of <botocore.client.SNS object at 0x7fc20391dcd0>> with params: {'Name': 'domainEventTopic.fifo'} for resource: {'Type': 'AWS::SNS::Topic', 'Metadata': {'aws:cdk:path': 'AppStack/Workers/DomainEvent/Resource'}, 'LogicalResourceId': 'WorkersDomainEvent75905C1B', 'Properties': {'ContentBasedDeduplication': True, 'DisplayName': 'Domain event subscription topic', 'FifoTopic': True, 'TopicName': 'domainEventTopic.fifo'}, '_state_': {}, 'PhysicalResourceId': None}
2021-02-22T09:36:59:INFO:localstack.utils.cloudformation.template_deployer: Unable to apply change set cdk-deploy-change-set: An error occurred (InvalidParameterValue) when calling the CreateTopic operation: Topic names must be made up of only uppercase and lowercase ASCII letters, numbers, underscores, and hyphens, and must be between 1 and 256 characters long.
```

**Comment by franciscojgarciav** [comment]
SNS Fifo topic is still no supported in the latest version of Localstack. While using the latest terraform sns_topic resource to create a FIFO topic, the operation works, but when inspecting the topic, it is not fifo. Please add this feature.

**Comment by ronyeh-lb** [comment]
+1

**Comment by HeavenH** [comment]
sns topic fifo already is feature in localstack?

**Comment by dineshvivek** [comment]
+1 

**Localstack error message :** 

An error occurred (InvalidParameterValue) when calling the CreateTopic operation: Topic names must be made up of only uppercase and lowercase ASCII letters, numbers, underscores, and hyphens, and must be between 1 and 256 characters long.

**Terraform Error Message:**

Terraform not allowing create the fifo topic without dot. │ Error: invalid topic name: user-updates-topic-fifo

**AWS Documentation**

Constraints: Topic names must be made up of only uppercase and lowercase ASCII letters, numbers, underscores, and hyphens, and must be between 1 and 256 characters long.

For a FIFO (first-in-first-out) topic, the name must end with the .fifo suffix. 

Seems localstack need to allow dot only for FIFO queue type

**Comment by scelestino** [comment]
+1

**Comment by bentsku** [comment]
Hello,

Sorry for the delay in responding to this issue and thanks for your reports.
 After investigating, it seems that the format of the request should be a map, per AWS CLI documentation.
https://awscli.amazonaws.com/v2/documentation/api/latest/reference/sns/create-topic.html

The CLI doesn’t allow map in the format of `--attributes FifoTopic=true --attributes ContentBasedDeduplication=false`, or it will only take into the account the last `attributes` parameter.

The correct command to create a Fifo topic with multiple attributes should be:
`aws --endpoint-url=http://localhost:4566 sns create-topic --name command_post_topic.fifo  --attributes FifoTopic=true,ContentBasedDeduplication=false --region us-east-1`.
 This command works and creates a SNS FifoTopic. 

####  About Terraform issues encountered in the comments.
 Based on https://github.com/localstack/localstack-terraform-samples, I just tested the following ressource from [Terraform docs](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sns_topic#example-with-first-in-first-out-fifo):
```
resource "aws_sns_topic" "topic" {
  name = "event-topic.fifo"
  fifo_topic = true
  content_based_deduplication = true
}
```
 This example works as expected for me. 

@dineshvivek @scelestino: could you please add a comment with a detailed explanation on how to reproduce your issue? I'll be happy to take a look.

**Comment by arthyrik** [comment]
I am using localstack-14.0.5 image for junit tests. Version of java maven dependency is 1.17.2. Have the same issue and can't create fifo topic/queue.

**Comment by bentsku** [comment]
Hello @arthyrik,
Could you add a comment with a detailed explanation on how to reproduce your issue? If you can provide any error in the logs as well, I'll be happy to help!

**Comment by jdolan-chwy** [comment]
Is this resolved? I'm using the AWS SDK 2.20.3 to programmatically create a FIFO topic, and subscribe that FIFO topic to a FIFO queue.

I see no errors when creating the topic, but after publishing to the topic and inspecting the messages in the queue, they are often not delivered in order. The messages all have the same message group ID, so order should have been preserved by the topic.

Is Localstack just silently accepting the FIFO topic request but not actually honoring it?

Sending and receiving messages directly to the FIFO queue in my test works just fine. It's only when I attempt to publish messages _thru_ the FIFO topic _to_ the FIFO queue that things fall apart.

**Comment by humphreyn** [comment]
As confirmed by @bentsku using the AWS CLI it works.

But when using the AWS SDK for Javascript  @aws-sdk/client-sns v3.287.0 it fails with the following error

`InvalidParameterValue: Topic names must be made up of only uppercase and lowercase ASCII letters, numbers, underscores, and hyphens, and must be between 1 and 256 characters long.
`

**Comment by bentsku** [comment]
Hello @humphreyn, could share a quick code snippet to show how you are encountering this issue? Thanks!
