### ISSUE TITLE
Appsync /schemacreation path

### ISSUE THREAD

**Issue by theBenForce** [localstack/localstack#3337]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

When trying to deploy an appsync api using terraform it gets stuck waiting for the api to be created and eventually times out. When I check the localstack logs I see a bunch of entries that look like this:

```
localstack_main  | 2020-12-09T20:39:07:WARNING:localstack_ext.services.appsync.appsync_api: Not yet implemented: Unable to find path mapping for GET /v1/apis/{API_ID}/schemacreation
```

Which, according to the [AWS API Docs](https://docs.aws.amazon.com/appsync/latest/APIReference/API_GetSchemaCreationStatus.html), should be returning a status message.

## Expected behavior

Return a status message from the `/v1/apis/{API_ID}/schemacreation` path so that terraform can stop waiting for the resource.

## Actual behavior

Terraform continually checks the status of the API's schema creation and eventually times out.

# Steps to reproduce

## Command used to start LocalStack

...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

...

**Comment by whummer** [comment]
Thanks for reporting this issue @theBenForce . This should be fixed in the meantime, can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists. Thanks for your help!
