### ISSUE TITLE
s3 initialize multipart upload with md5 metadata raises client exception

### ISSUE THREAD

**Issue by marcuswr** [localstack/localstack#3347]
# Type of request: This is a ...

[X] bug report
[ ] feature request

# Detailed description
S3 InitiateMultipartUploadRequest with metadata containing an MD5 checksum fails with:
The Content-MD5 you specified did not match what we received.

## Expected behavior
The client.initiateMultipartUpload(request); call should execute without exception.

## Actual behavior
The client.initiateMultipartUpload(request); throws the following exception:
The Content-MD5 you specified did not match what we received. (Service: Amazon S3; Status Code: 400; Error Code: BadDigest; Request ID: null; S3 Extended Request ID: null; Proxy: null)

The output from localstack:
  localstack    | 2020-12-11 23:42:26,413:API: 172.19.0.2 - - [11/Dec/2020 23:42:26] "PUT /test HTTP/1.1" 200 -
makes it appear that the call completed successfully, however, the client then raises an exception. The client does
not raise an exception when the same code is executed against the real aws s3 instance.

# Steps to reproduce
Start localstack s3 instance.
Initiate a multipart upload using the aws java s3 sdk and specify an MD5 value in the metadata.

## Command used to start LocalStack

docker-compose up

contents of docker-compose.yaml 
version: '3.7'
services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEBUG=1
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=fake
      - AWS_SECRET_ACCESS_KEY=fake
      - HOSTNAME_EXTERNAL=localstack
    volumes:
      - "/private${TMPDIR}/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

[s3-localstack-multipart-upload-md5.tar.gz](https://github.com/localstack/localstack/files/5682118/s3-localstack-multipart-upload-md5.tar.gz)

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

package com.example;

import junit.framework.TestCase;

import com.amazonaws.services.s3.model.InitiateMultipartUploadRequest;
import com.amazonaws.services.s3.model.ObjectMetadata;

import com.amazonaws.services.s3.AmazonS3;
import com.amazonaws.services.s3.AmazonS3ClientBuilder;
import com.amazonaws.client.builder.AwsClientBuilder.EndpointConfiguration;

public class S3MultipartUploadTest extends TestCase {
    public void test() {
        EndpointConfiguration configuration = new EndpointConfiguration("http://localstack:4566", "us-east-1");
        AmazonS3 client = AmazonS3ClientBuilder.standard()
            .withEndpointConfiguration(configuration)
            .withPathStyleAccessEnabled(true)
            .build();

        String bucket = "test";
        String key = "test.txt";
        ObjectMetadata metadata = new ObjectMetadata();
        metadata.setContentLength(100000);
        metadata.setContentMD5("cJW64Jglng3aS3rMYk3k4g==");
        metadata.setContentType("text/plain");
        InitiateMultipartUploadRequest request = new InitiateMultipartUploadRequest(bucket, key, metadata);

        client.initiateMultipartUpload(request);
    }
}

[s3-localstack-multipart-upload-md5.tar.gz](https://github.com/localstack/localstack/files/5682121/s3-localstack-multipart-upload-md5.tar.gz)

**Comment by Kavyeshs41** [comment]
Hello @marcuswr Thanks for reporting the issue. This should be fixed in #3394. Can you please try with latest docker image?
Please report here if issue still persist.

**Comment by whummer** [comment]
Thanks for reporting @marcuswr . This should (hopefully) be fixed in #3394 - can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists. Thanks
