### ISSUE TITLE
SQS Fifo Queue CLI bug

### ISSUE THREAD

**Issue by nvedansh** [localstack/localstack#3348]
# **This is a Bug Report**

**Detailed Description**

FIFO queue is not getting created when using AWS CLI, used the attributes FifoQueue, ContentBasedDeduplication.

> `aws --endpoint-url=http://localhost:4576 sqs create-queue --queue-name command_request.fifo --attributes FifoQueue=true --attributes ContentBasedDeduplication=false --region us-east-1`

and when we see the attributes for the queue

> `aws --endpoint-url=http://localhost:4576 sqs get-queue-attributes --queue-url http://localhost:4576/000000000000/command_request.fifo --attribute-names All`

the response is 

```
{
    "Attributes": {
        "ApproximateNumberOfMessages": "0",
        "ApproximateNumberOfMessagesDelayed": "0",
        "ApproximateNumberOfMessagesNotVisible": "0",
        "CreatedTimestamp": "1607754628.206932",
        "DelaySeconds": "0",
        "LastModifiedTimestamp": "1607754628.206932",
        "MaximumMessageSize": "262144",
        "MessageRetentionPeriod": "345600",
        "QueueArn": "arn:aws:sqs:us-east-1:000000000000:command_request.fifo",
        "Policy": "None",
        "RedrivePolicy": "None",
        "ReceiveMessageWaitTimeSeconds": "0",
        "VisibilityTimeout": "30"
    }
}

```
Notice that FifoQueue and ContentBasedDeduplication are not added in the response. 

When I recreated the same issue using the boto3 client

`self.sqs = boto3.client('sqs', region_name='us-east-1',
                                endpoint_url='http://localhost:4576')`

`self.queueUrl = self.sqs.create_queue(
            QueueName='command_request.fifo',
            Attributes={
                'FifoQueue': 'true',
                'ContentBasedDeduplication': 'false'
            }
        )['QueueUrl']
`

The output is:

```
{
    "Attributes": {
        "ApproximateNumberOfMessages": "0",
        "ApproximateNumberOfMessagesDelayed": "0",
        "ApproximateNumberOfMessagesNotVisible": "0",
        "CreatedTimestamp": "1607751153.158369",
        "DelaySeconds": "0",
        "LastModifiedTimestamp": "1607751153.158369",
        "MaximumMessageSize": "262144",
        "MessageRetentionPeriod": "345600",
        "QueueArn": "arn:aws:sqs:us-east-1:000000000000:command_request.fifo",
        "Policy": "None",
        "RedrivePolicy": "None",
        "ReceiveMessageWaitTimeSeconds": "0",
        "VisibilityTimeout": "30",
        "FifoQueue": "true",
        "ContentBasedDeduplication": "false"
    }
}
```

**PS:** Does localstack not support FifoQueue and FifoTopics? I have created another issue for SNS FifoTopic as well:
https://github.com/localstack/localstack/issues/3336. finding multiple issues on Fifo resources in localstack.

**Comment by usmangani1** [comment]
@nvedansh  Thanks for reporting the issue.
We tried to reproduce the issue on the latest version of localstack with the following commands and the expected parameters are present in the response. A way we pass attributes when creating the queue should be a bit different than what was done.
Please use the commands below and let us know if the issue still persists.


```
user/localstack % aws --endpoint-url=http://localhost:4566 sqs create-queue --queue-name command_request.fifo --attributes "FifoQueue=true,ContentBasedDeduplication=false" --region us-east-1
{
    "QueueUrl": "http://localhost:4566/000000000000/command_request.fifo"
}

user/localstack % aws --endpoint-url=http://localhost:4566 sqs get-queue-attributes --queue-url http://localhost:4576/000000000000/command_request.fifo --attribute-names All
{
    "Attributes": {
        "ApproximateNumberOfMessages": "0",
        "ApproximateNumberOfMessagesDelayed": "0",
        "ApproximateNumberOfMessagesNotVisible": "0",
        "CreatedTimestamp": "1607847593.013115",
        "DelaySeconds": "0",
        "LastModifiedTimestamp": "1607847593.013115",
        "MaximumMessageSize": "262144",
        "MessageRetentionPeriod": "345600",
        "QueueArn": "arn:aws:sqs:us-east-1:000000000000:command_request.fifo",
        "ReceiveMessageWaitTimeSeconds": "0",
        "VisibilityTimeout": "30",
        "FifoQueue": "true",
        "ContentBasedDeduplication": "false"
    }
}

```

**Comment by nvedansh** [comment]
Right, I tried it with the way you mentioned and it is working now. I am gonna go ahead and close this issue. Thanks for responding.
