### ISSUE TITLE
EventBridge InputPath is applied on all targets

### ISSUE THREAD

**Issue by jesmiatka** [localstack/localstack#3353]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

EventBridge InputPath is applied on all targets. 

The original event is overwritten after InputPath transformation in performed. This should not be done.

See:
https://github.com/localstack/localstack/blob/409a016fdf9a198219886056433a014e4bfb9b5e/localstack/services/events/events_starter.py#L107

The event parameter is overwritten in this line. It should be assigned to a new one (e.g. transformed_event) and used to pass to the methods below (e.g. send_event_to_sqs(transformed_event, arn)).

https://github.com/localstack/localstack/blob/409a016fdf9a198219886056433a014e4bfb9b5e/localstack/services/events/events_starter.py#L110

Can provide a localstack setup, but code seems to be self explanatory. 

## Expected behavior

InputPath transformation should only be performed on the defined target, not on all attached targets.

## Actual behavior

Once an InputPath transformation is performed, it's used on all attached targets.

# Steps to reproduce

## Command used to start LocalStack

...

**Comment by whummer** [comment]
Thanks for reporting @jesmiatka . This should be fixed in #3365 - can you please pull the `latest` Docker image and give it another try? Please report here if the problem persists. Thanks

**Comment by jesmiatka** [comment]
Hi @whummer,

It work correctly in the latest branch. Thanks for the fix @usmangani1.
