### ISSUE TITLE
The use of Sub in AWS::ApiGatewayV2::Route Target property results in runtime error (or silent failure)

### ISSUE THREAD

**Issue by m-chandler** [localstack/localstack#3357]
# Type of request: This is a ...

[ X ] bug report
[ ] feature request

# Detailed description

Using Sub (any variant) within the Target property of an AWS::ApiGatewayV2::Route resource results in either a runtime error when connecting to the WebSocket API, or no error (but the route does not work).

Note that Runtime Error refers to the following message in the logs:
```
localstack_main   | 2020-12-14T23:37:21:INFO:localstack_ext.services.apigateway.apigateway_extended: Unable to find integration for ID "${ConnectionHandlerWebsocketsIntegration}", API ID "1ff04c1d"
```

Runtime Error:
```
Target: !Sub "integrations/${ConnectionHandlerWebsocketsIntegration}"
```
Runtime Error:
```
Target:
  Fn::Sub: "integrations/${ConnectionHandlerWebsocketsIntegration}"
```
No runtime error, but fails silently - route doesn't work.
```
Target: 
    Fn::Sub: 
    - "integrations/${ConnectionHandlerWebsocketsIntegration}"
    - {}
```
Works!
```
Target:
  Fn::Join:
  - "/"
  - - integrations
    - Ref: DefaultHandlerWebsocketsIntegration
```

## Expected behavior

All the above variants should function exactly the same.

## Actual behavior

Only Fn::Join seems to work.

# Steps to reproduce

[serverless-websockets-intrinsic-functions.zip](https://github.com/localstack/localstack/files/5692249/serverless-websockets-intrinsic-functions.zip)

1. Download above ZIP, extract to working directory.
2. Start localstack (docker compose below).
3. Execute `deploy-working.sh`.
4. Connect to websocket via wscat `wscat -c localhost:4513`
    1. Note the logs indicate that the Lambda function for the connect handler is executing. Success!
5. Kill localstack.
6. Start localstack again (docker compose below).
7. Execute `deploy-broken.sh`.
8. Connect to websocket via wscat `wscat -c localhost:4513`
    1. Note the logs indicate `Unable to find integration for ID "${ConnectionHandlerWebsocketsIntegration}", API ID "1ff04c1d"`

Try any of the variants of Fn::Sub / !Sub on line 252 (`SconnectWebsocketsRoute.Properties.Target`) - none of them work.

## Command used to start LocalStack

`docker-compose up`

```
version: '2.1'

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
      - "4510:4510"
      - "4571:4571"
      - "4572:4572"
      - "4513:4513"
      - "4514:4514"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=${SERVICES- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
      - LOCALSTACK_API_KEY=...
      - DEBUG=1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    tmpfs:
      - /tmp/localstack:exec,mode=600
    network_mode: bridge
  dynamodb-admin:
    depends_on:
      - localstack
    image: aaronshaf/dynamodb-admin
    ports:
      - 8001:8001
    environment:
      - DYNAMO_ENDPOINT=http://localstack:4566
      - AWS_REGION=ap-southeast-2
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
    links:
      - localstack
    network_mode: bridge
```

**Comment by calvernaz** [comment]
Works in the current version!
