### ISSUE TITLE
The use of Sub in AWS::ApiGatewayV2::Integration IntegrationUri property results in runtime error

### ISSUE THREAD

**Issue by m-chandler** [localstack/localstack#3358]
# Type of request: This is a ...

[ X ] bug report
[ ] feature request

# Detailed description

Using !Sub within the IntegrationUri property of an AWS::ApiGatewayV2::Integration resource results in a runtime error when connecting to the WebSocket API.

Note that Runtime Error refers to the following message in the logs:
```
localstack_main   | 2020-12-15T00:10:38:WARNING:localstack.utils.aws.aws_stack: Unable to fix/canonicalize ARN: arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/${ConnectionHandlerLambdaFunction.Arn}/invocations
```

Runtime Error:
```
IntegrationUri: !Sub "arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ConnectionHandlerLambdaFunction.Arn}/invocations"
```
Works!
```
IntegrationUri:
  Fn::Join:
  - ''
  - - 'arn:'
    - Ref: AWS::Partition
    - ":apigateway:"
    - Ref: AWS::Region
    - ":lambda:path/2015-03-31/functions/"
    - Fn::GetAtt:
      - ConnectionHandlerLambdaFunction
      - Arn
    - "/invocations"
```

## Expected behavior

All the above variants should function exactly the same.

## Actual behavior

Only Fn::Join seems to work.

# Steps to reproduce

[serverless-websockets-intrinsic-functions-2.zip](https://github.com/localstack/localstack/files/5692312/serverless-websockets-intrinsic-functions-2.zip)

1. Download above ZIP, extract to working directory.
2. Start localstack (docker compose below).
3. Execute `deploy-working.sh`.
4. Connect to websocket via wscat `wscat -c localhost:4513`
    1. Note the logs indicate that the Lambda function for the connect handler is executing. Success!
5. Kill localstack.
6. Start localstack again (docker compose below).
7. Execute `deploy-broken.sh`.
8. Connect to websocket via wscat `wscat -c localhost:4513`
    1. Note the logs indicate `Unable to fix/canonicalize ARN:`

## Command used to start LocalStack

`docker-compose up`

```
version: '2.1'

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
      - "4510:4510"
      - "4571:4571"
      - "4572:4572"
      - "4513:4513"
      - "4514:4514"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=${SERVICES- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
      - LOCALSTACK_API_KEY=...
      - DEBUG=1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    tmpfs:
      - /tmp/localstack:exec,mode=600
    network_mode: bridge
  dynamodb-admin:
    depends_on:
      - localstack
    image: aaronshaf/dynamodb-admin
    ports:
      - 8001:8001
    environment:
      - DYNAMO_ENDPOINT=http://localstack:4566
      - AWS_REGION=ap-southeast-2
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
    links:
      - localstack
    network_mode: bridge
```

**Comment by whummer** [comment]
Thanks for reporting this issue @m-chandler . This should be fixed in the meantime - can you please pull the `latest` Docker image and give it another try? Please let us know if this problem persists. Thanks for your help!

**Comment by m-chandler** [comment]
@whummer it works fine in the small example I gave, but didn't work in my larger stack.
I had to add a "DependsOn' for the Lambda function in each each AWS::ApiGatewayV2::Integration.
Good enough for me - thanks!
