### ISSUE TITLE
API Gateway WebSocket Lambda integration event body should be string, not an object.

### ISSUE THREAD

**Issue by m-chandler** [localstack/localstack#3360]
# Type of request: This is a ...

[ X ] bug report
[ ] feature request

# Detailed description

This bug concerns the API Gateway to Lambda integration.

For consistency with AWS, the 'body' property in the Lambda event object should be a string (i.e. a stringified JSON object).

In localstack the 'body' property in the event is already an object, which differs to AWS.

## Expected behavior

For consistency with AWS, the 'body' property in the event object should be a string (i.e. a stringified JSON object).

```
{
    "requestContext": {
        ...
    },
    "body": "{\"action\":\"subscribe\",\"propA\":\"propAValue\"}"
}
```

## Actual behavior

In localstack, the 'body' property in the event is an object.

```
{
    "requestContext": {
        ...
    },
    "body": {
        "action": "subscribe",
        "propA": "propAValue"
    }
}
```

**Comment by whummer** [comment]
Thanks for reporting this issue @m-chandler . This should be fixed in the meantime - can you please pull the `latest` Docker image and give it another try? Please let us know if this problem persists. Thanks for your help!
