### ISSUE TITLE
Possible to specify starting port for deployed WebSockets APIs?

### ISSUE THREAD

**Issue by m-chandler** [localstack/localstack#3368]
# Type of request: This is a ...

[ ] bug report
[ X ] feature request

# Detailed description

When deploying a WebSockets API to localstack I would find it useful to specify the starting port.

It seems that when deploying a WebSockets API, sometimes the first deployed API is assigned port 4510, other times 4513.

Not only would this be useful for knowing the exact port that the **first** deployed API will run on, I would also like to run multiple localstack instances on the same host. I'd rather not have to wire different host/container ports to achieve this, as this would make the output from `awslocal apigatewayv2 get-apis` misleading.

**Comment by whummer** [comment]
Thanks for reporting @m-chandler . The default port range for these service instance ports (e.g., RDS instances, API GW instances, etc) is predefined as `4510-4530`.

We have now added two additional configuration variables `SERVICE_INSTANCES_PORTS_START`/`SERVICE_INSTANCES_PORTS_END` (also added to the documentation in the online app) that can be used to customize these port ranges and also start multiple LocalStack instances locally in parallel. Please note that the corresponding port ranges also need to be exposed in your Docker configuration (e.g., `docker-compose.yml`).

Hope that helps - please let us know if there are any issues. Thanks for your help!
