### ISSUE TITLE
Timeseries delete_table fails

### ISSUE THREAD

**Issue by villekr** [localstack/localstack#3372]
# Type of request: This is a ...

[x ] bug report
[ ] feature request

# Detailed description
macOS, localstack 0.12.3 PRO, python 3.8.1 and boto3 1.16.38.

```
import boto3

session = boto3.session.Session(region_name="eu-west-1")
ts_client = session.client("timestream-write", endpoint_url="http://localhost:4566")
database_name = "local_timestream"
table_name = "local_metervalues"
print("Creating...")
ts_client.create_database(DatabaseName=database_name)
ts_client.create_table(
    DatabaseName=database_name,
    TableName=table_name,
    RetentionProperties={
        "MemoryStoreRetentionPeriodInHours": 12,
        "MagneticStoreRetentionPeriodInDays": 30,
    },
)
print("Deleting...")
ts_client.delete_table(
    DatabaseName=database_name, TableName=table_name,
)  # -> ClientError Exception
ts_client.delete_database(DatabaseName=database_name)
print("Done...")
```
...

## Expected behavior
delete_table should work.
Above code works when executed towards AWS.
...

## Actual behavior

delete_table raises ClientError on docker logs one can see the following:
File ".../localstack_ext/services/timestream/timestream_api.py", line 36, in handle_request
KeyError: 'DeleteTable'
...

# Steps to reproduce

Run the above code

## Command used to start LocalStack

...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

...

**Comment by whummer** [comment]
Thanks for reporting @villekr . This should be fixed in the meantime - can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists. Thanks a lot for your help!

**Comment by villekr** [comment]
Tried with the latest localstack docker image. The exception is now different with above test snippet. It fails in ts_client.delete_database(DatabaseName=database_name) with:

An error occurred (InternalServiceError) when calling the DeleteDatabase operation: Error: Unable to find handler for action: Timestream_20181101.DeleteDatabase

**Comment by villekr** [comment]
Furthermore noticed that if I do list_tables(DatabaseName=database_name) after create_table I get:

An error occurred (InternalServiceError) when calling the ListTables operation: Error: Unable to find handler for action: Timestream_20181101.ListTables
