### ISSUE TITLE
Lambda destinations

### ISSUE THREAD

**Issue by barnettj** [localstack/localstack#3373]
# Type of request: This is a ...

[X] bug report
[ ] feature request

# Detailed description

Hi everyone.

This is related to the feature request here https://github.com/localstack/localstack/issues/2926.
I'm trying to implement lambda destinations for my localstack (LocalStack version: 0.12.3) lambda to SQS.

After applying an update-function-event-invoke-config, it doesn't throw any errors, but can no longer call list-functions and does not route lambda response to destination.

bash-5.0# awslocal lambda update-function-event-invoke-config --function-name function-local --cli-input-json file://destination.json
{
"LastModified": "2020-12-17T03:49:48.479+0000",
"FunctionArn": "arn:aws:lambda:us-east-1:000000000000:function:function-local",
"DestinationConfig": {
"OnSuccess": {
"Destination": "arn:aws:sqs:us-east-1:000000000000:local-events"
},
"OnFailure": {
"Destination": "arn:aws:sqs:us-east-1:000000000000:local-events"
}
}
}
bash-5.0# awslocal lambda list-functions

'str' object has no attribute 'get'`

## Expected behavior
lambda list-functions should return functions.
Destination should be configured and lambda responses should go via specification.
...

## Actual behavior
No responses are routed to destination.
list-function yields error 'str' object has no attribute 'get'`
...

# Steps to reproduce
I was able to reproduce the same issue with this demo project too https://github.com/macnev2013/lamdba-destinations-demo.

1. Startup localstack
2. Run deploy.sh to deploy roles/function/function-event-invoke-config
3. Invoke lambda as event

## Command used to start LocalStack
version: '3.2'
services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack_demo
    ports:
      - '4563-4599:4563-4599'
      - '8055:8080'
    environment:
      - SERVICES=sqs,lambda,iam
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - './.localstack:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'

compose up.
...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

...

**Comment by nhoughto** [comment]
This looks like a mapping bug with dead letter arn here:

https://github.com/localstack/localstack/blob/c30f99c8d2e19a5739ef0bdf295ec2f495fa45ee/localstack/utils/aws/aws_models.py#L253

This structure should be `DeadLetterConfig.TargetArn` not just DeadLetterConfig being the arn value, as per https://docs.aws.amazon.com/cli/latest/reference/lambda/get-function.html

hacky workaround is to change it to `self.dead_letter_config = {'TargetArn': dlq_arn}`

**Comment by barnettj** [comment]
After applying @nhoughto workaround, list-functions does indeed work again.

The destination routing is still problematic though.

A lambda event invocation still does not publish to SQS.

```2020-12-21T00:52:28:DEBUG:localstack.services.awslambda.lambda_executors: Lambda executed in Event (asynchronous) mode, no response will be returned to caller
2020-12-21T00:52:31:INFO:localstack.services.edge: Unable to find forwarding rule for host "localstack-595c669f6f-7vxvl:4566", path "GET /", target header "", auth header "", data "b''"```

I updated my test function to throw an error so we can test functionError scenario.

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/code/localstack/localstack/utils/bootstrap.py", line 581, in run
    result = self.func(self.params)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 165, in do_execute
    return _run(func_arn=func_arn)
  File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 149, in wrapped
    raise e
  File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 145, in wrapped
    result = func(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 157, in _run
    lambda_error_to_dead_letter_queue(func_details, event, e)
  File "/opt/code/localstack/localstack/utils/aws/dead_letter_queue.py", line 42, in lambda_error_to_dead_letter_queue
    return _send_to_dead_letter_queue('Lambda', source_arn, dlq_arn, event, error)
  File "/opt/code/localstack/localstack/utils/aws/dead_letter_queue.py", line 68, in _send_to_dead_letter_queue
    raise Exception(msg)
Exception: Unable to send message to dead letter queue http://localstack:4566/000000000000/local-video-events (code None): An error occurred (InvalidMessageContents) when calling the SendMessage operation: Message contains invalid characters
```

**Comment by whummer** [comment]
Thanks for reporting @barnettj @nhoughto . This should be fixed in #3430 - can you please pull the `latest` version and give it another try? Please report here if the problem persists. Thanks

**Comment by barnettj** [comment]
Thanks for the work on this issue @whummer and @irahulranjan.

I can now get the event coming through SQS, but it isn't adding the lambda response body:

Using the same example [project](https://github.com/macnev2013/lamdba-destinations-demo) above with latest localstack:
```
awslocal sqs receive-message --queue-url http://localhost:4566/000000000000/function-events
```

```
{
	"Messages": [{
		"MessageId": "67842be3-1d20-4851-7099-06a3c3ddd4bb",
		"ReceiptHandle": "lcjdueoqzbebgtyqxdfdvqixhifdsclxmuneuoevoyundfwjmmyrzylitggqjcusbukncrikjogehmuvynsiiitxmkgtxdhieabbiyjbpzuksdivcsjkhagycxbvamwbnwjbghxjlixxgzxuzwdkjprafeequcfufxtegcggrcezjymibqvvizpmn",
		"MD5OfBody": "6ab8ba87499a8c1361165482d0d2b2f6",
		"Body": "{\"version\": \"1.0\", \"timestamp\": \"2021-01-13T02:30:46.860Z\", \"requestContext\": {\"requestId\": \"665dea8b-47a5-43a2-b1e9-baa1c9ca9361\", \"functionArn\": \"arn:aws:lambda:us-east-1:000000000000:function:my-function\", \"condition\": \"RetriesExhausted\", \"approximateInvokeCount\": 1}, \"requestPayload\": {\"key\": \"value\"}, \"responseContext\": {\"statusCode\": 200, \"executedVersion\": \"$LATEST\"}, \"responsePayload\": {\"statusCode\": 200, \"headers\": null, \"multiValueHeaders\": null, \"body\": \"\"}}",
		"Attributes": {
			"SenderId": "AIDAIT2UOQQY3AUEKVGXU",
			"SentTimestamp": "1610505046899",
			"ApproximateReceiveCount": "1",
			"ApproximateFirstReceiveTimestamp": "1610505049656"
		}
	}]
}
```
You can see the \"body\": \"\"} at the end.

If I invoke the sample lambda synchronously we can see the response is:
```
bash-5.0# awslocal lambda invoke --function-name my-function  --payload '{ "key": "value" }' response.json
{
    "StatusCode": 200,
    "LogResult": "",
    "ExecutedVersion": "$LATEST"
}
bash-5.0# cat response.json
"2021/01/13/[$LATEST]97432522b8b5ca7b23fb5f94dd3d3e0c"
```

**Comment by nhoughto** [comment]
@barnettj  does this need to be reopened?

**Comment by barnettj** [comment]
Yeah still not working.

@irahulranjan I am still seeing the body in SQS message as empty

`{
    "Messages": [
        {
            "MessageId": "991e03b0-5a50-517d-6fe2-8d5cf5f09be1",
            "ReceiptHandle": "opghgtmumqlsoknhovzymaswxbdtenldvkibjsqgmkguskmswyqifjucgkkxwfefiyrinkoptmatpiwxflqmewkdktvtjujqgvccryexatzrwhfandlzotqgaavxpclfwqeokjiwwwxvpcfflwaxjpmdhgvgloowdapvpxtrfsbjhttirteyoqenz",
            "MD5OfBody": "6ab8ba87499a8c1361165482d0d2b2f6",
            "Body": "{\"version\": \"1.0\", \"timestamp\": \"2021-01-13T02:30:46.860Z\", \"requestContext\": {\"requestId\": \"665dea8b-47a5-43a2-b1e9-baa1c9ca9361\", \"functionArn\": \"arn:aws:lambda:us-east-1:000000000000:function:my-function\", \"condition\": \"RetriesExhausted\", \"approximateInvokeCount\": 1}, \"requestPayload\": {\"key\": \"value\"}, \"responseContext\": {\"statusCode\": 200, \"executedVersion\": \"$LATEST\"}, \"responsePayload\": {\"statusCode\": 200, \"headers\": null, \"multiValueHeaders\": null, \"body\": \"\"}}",
            "Attributes": {
                "SenderId": "AIDAIT2UOQQY3AUEKVGXU",
                "SentTimestamp": "1612299454208",
                "ApproximateReceiveCount": "2",
                "ApproximateFirstReceiveTimestamp": "1612299454223"
            }
        }
    ]
}`

This part specifically at the end of the nested "body" field:
`"body\": \"\"}}",`

I would be expecting something like this for the sample repo list above:

`"body\": \"2021/02/02/[$LATEST]2f1b8ab598b531e8582070f7a2e6099a\"}}",`

**Comment by irahulranjan** [comment]
Hi @barnettj, I tried executing the same set of commands and I am receiving the responsePayload properly. Can you try updating the to the latest localstack version?

**Comment by irahulranjan** [comment]
```
$awslocal lambda invoke --function-name my-function  --payload '{ "key": "value" }' response.json
{
    "StatusCode": 200,
    "LogResult": "",
    "ExecutedVersion": "$LATEST"
}
```

```
$cat response.json 
"2021/02/02/[$LATEST]647a44b5ca7d895833c6528e158cf78f"
```

```
$awslocal sqs receive-message --queue-url http://localhost:4566/000000000000/destination
{
    "Messages": [
        {
            "MessageId": "27d7113d-d411-ce3d-f2d8-63ab85fdcdd1",
            "ReceiptHandle": "twtlhunqxdvtzlpvgplwdlbnigdonmqpqbvqjoibsakbxzysudlysnufbuzvbsivoxiukbzdkzfgugwreutxbyojhmdqxbbxgpqspctjwunxljbwzyzwpeblkkgcfxipxlyxowesaggomnxlxkxgqhxbeeccypzabbfqpignyhscteroaovwjykrp",
            "MD5OfBody": "66b1492f7f80d4d578310ec0a521045a",
            "Body": "{\"version\": \"1.0\", \"timestamp\": \"2021-02-02T21:38:14.050Z\", \"requestContext\": {\"requestId\": \"7aee7dbf-dbb1-44be-9291-83b967263649\", \"functionArn\": \"arn:aws:lambda:us-east-2:000000000000:function:my-function\", \"condition\": \"Success\", \"approximateInvokeCount\": 1}, \"requestPayload\": {\"key\": \"value\"}, \"responseContext\": {\"statusCode\": 200, \"executedVersion\": \"$LATEST\"}, \"responsePayload\": \"2021/02/02/[$LATEST]647a44b5ca7d895833c6528e158cf78f\"}",
            "Attributes": {
                "SenderId": "AIDAIT2UOQQY3AUEKVGXU",
                "SentTimestamp": "1612301894086",
                "ApproximateReceiveCount": "1",
                "ApproximateFirstReceiveTimestamp": "1612301909987"
            }
        }
    ]
}
```

**Comment by barnettj** [comment]
Ah my apologies @irahulranjan. I can indeed get the responsePayload back (It was latest localstack, but I think i needed to rebuild the queue).

Thanks again for your work on this.

**Comment by irahulranjan** [comment]
No issues, Thanks for the confirmation!
