### ISSUE TITLE
S3 Invalid presigned getObject Url

### ISSUE THREAD

**Issue by nickzelei** [localstack/localstack#3374]
# Type of request: This is a ...

[ x] bug report
[ ] feature request

# Version
0.12.3

# Detailed description
There appears to be a bug when trying to download a file from S3 using a presigned getObject URL.
**This is specifically an issue when providing the `ResponseContentDisposition`.**
If this property isn't provided, the generated URL works as intended. This is also working on the version I'm coming from which is **0.10.9**
...

## Expected behavior
The file should download or preview based on the content disposition attachment type and filename.
I've verified this works as I am using this logic in a production app.
...

## Actual behavior
S3 returns an invalid signature error.

```
SignatureDoesNotMatchThe request signature we calculated does not match the signature you provided. Check your key and signing method.2176b97752ef28cftestGET 1608247963 /default.storage.bucket/f477842a-8f2b-45bb-aa71-2e1270a997c7fb5dywtf4kizdubgrlj0YDcoR9k=6662356479777466346b697a64756267726c6a305944636f52396b3d
```
...

# Steps to reproduce
Create file in S3.
Generate a URL via aws-sdk (@2.800.0)
GET url in browser or other means.

## Command used to start LocalStack
docker-compose.yml
```
  localstack:
    image: localstack/localstack:0.12.3
    container_name: files-api-localstack
    hostname: localstack
    ports:
      - "4566:4566"
    environment:
      SERVICES: s3,sns
      HOSTNAME: localstack
      HOSTNAME_EXTERNAL: localhost
      DEBUG: 1
      DOCKER_HOST: unix:///var/run/docker.sock
      DEFAULT_REGION: us-west-2
      DATA_DIR: /tmp/localstack/data
    volumes:
      - ./localstack:/tmp/localstack:delegated
      - /var/run/docker.sock:/var/run/docker.sock:delegated
```
...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

```
const contentDisposition = require('content-disposition');
const { S3 } = require('aws-sdk');

(async () => {
  const s3 = new S3({
    apiVersion: '2006-03-01',
    credentials: {
      accessKeyId: 'test',
      secretAccessKey: 'test',
      endpoint: '<localstack-url>'
    },
    region: 'us-west-2',
    s3ForcePathStyle: true,
  });

  const url = await s3.getSignedUrlPromise('getObject', {
    Bucket: 'my-bucket',
    Key: 'my-key',
    ResponseContentDisposition: getContentDisposition('foo.txt', 'inline'),
  });
  console.log(url);
})().catch(console.error);

function getContentDisposition(filename, type = 'inline') {
  return filename ? contentDisposition(filename, { type }) : undefined;
}
```

**Comment by whummer** [comment]
Thanks for reporting @nickzelei . Can you please ensure that you're using the following credentials when creating the presigned URL (see [README here](https://github.com/localstack/localstack#setting-up-local-region-and-credentials-to-run-localstack)).
```
export AWS_ACCESS_KEY_ID=test
export AWS_SECRET_ACCESS_KEY=test
```
Hope that helps - please keep us posted. Thanks

**Comment by nickzelei** [comment]
Yes I am using those credentials, thanks.

**Comment by irahulranjan** [comment]
Hi @nickzelei,
The above source code that you shared does not compile. Can you please share the working code?

**Comment by nickzelei** [comment]
Sorry about that, I've updated the code. I also converted to javascript to remove friction of having to also compile typescript.

**Comment by irahulranjan** [comment]
Hi @nickzelei , Have you configured the correct endpoint in the client code?

**Comment by nickzelei** [comment]
@irahulranjan yes, apologies I left that property out. I am copying this code snippet from our internal codebase and modifying it for this PR. I am executing the real internal code against localstack.

**Comment by irahulranjan** [comment]
Hi @nickzelei, Could you add the following while s3 initialization:
`var s3 = new AWS.S3({
  signatureVersion: 'v4'
});`

**Comment by nickzelei** [comment]
> Hi @nickzelei, Could you add the following while s3 initialization:
> `var s3 = new AWS.S3({ signatureVersion: 'v4' });`

Curious as to why? Doesn't the signatureVersion default to the latest, which is v4, when not provided?

**Comment by whummer** [comment]
Thanks for the update @nickzelei @irahulranjan . Looks like the default signatureVersion defaults to `'s3'` for S3 clients: https://github.com/aws/aws-sdk-js/blob/master/apis/s3-2006-03-01.normal.json#L12

**Comment by irahulranjan** [comment]
Apparently it defaults to s3. https://github.com/aws/aws-sdk-js/blob/master/apis/s3-2006-03-01.normal.json#L12

**Comment by nickzelei** [comment]
Hm, interesting. That isn't even a default value.

From the docs:
```
signatureVersion (String) — the signature version to sign requests with (overriding the API configuration). Possible values are: 'v2', 'v3', 'v4'.
```
[docs](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html)

Regardless, the code I'm executing in production works just fine with no signatureVersion present.

**Comment by nickzelei** [comment]
> Hi @nickzelei, Could you add the following while s3 initialization:
> `var s3 = new AWS.S3({ signatureVersion: 'v4' });`

I have verified that updating the signatureVersion to `v4` does fix my issue.

**Comment by whummer** [comment]
Thanks for confirming. For now I'd say this is best practice - we can add a note to the Troubleshooting section of the README, and print out a warning message if a different signature mechanism is being used.

This seems to be a relatively niche problem, hence not a high priority for now - although we'd be very happy to provide guidance if you'd like to contribute a pull request! Thanks for your help.

**Comment by nickzelei** [comment]
Appreciate it! I'm going to move forward with setting the sig version. Thank you @whummer and @irahulranjan

**Comment by irahulranjan** [comment]
Hi @nickzelei, Can I close this issue?

**Comment by nickzelei** [comment]
Sure thing! Closed.
