### ISSUE TITLE
admin_create_user does not delete the users from the user pool entirely

### ISSUE THREAD

**Issue by arpekkar** [localstack/localstack#3376]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

macOS, localstack 0.12.3 PRO, python 3.8.1 and boto3 1.16.38.

For some reason I'm not able to remove users from cognito user pool in
my integration tests. I get this error: "An error occurred (400) when
calling the AdminCreateUser operation: An account with the given
username already exists"

My integration tests are initialized so that I first create user pool for
the session and then for each function I create new user to the user
pool and after test I delete that user from the pool.

It seems to delete them in the tear down, but once I start creating the same user with same email for next test, it gives the error above "An error occurred (400) when
calling the AdminCreateUser operation: An account with the given
username already exists" - as if there still would be a record of that user in the pool

Workaround for the issue now is to to delete the whole user pool and creating a new one for each test, but this makes my tests slow because I need to create user pools for every test. Am I doing something wrong or is there some issues in the localstack?

## Expected behavior

I should be able to delete user from the pool _admin_delete_user_ and after that create the a new user with same email

## Actual behavior

It seems to delete the user as user pool list-users return zero users, but still I get the error 'An account with the given
username already exists' and I'm not able to create the user.

# Steps to reproduce

Create user pool in my conftest.py in scope="session":

```
integration_test_user_pool = integration_test_cognito.create_user_pool(
    PoolName=user_pool_name  # 'integration-test-user-pool'
)

```
Then in scope="function" I create user and finally I delete it in following way:

```
cognito_user_1 = integration_test_cognito.admin_create_user(
        UserPoolId=integration_test_user_pool["UserPool"]["Id"],
        Username=integration_test_dataset.user_1.email,
        UserAttributes=[
            {"Name": "email", "Value": integration_test_dataset.user_1.email}
        ],
    )
```

delete:

```
cognito_users = integration_test_cognito.list_users(
        UserPoolId=integration_test_user_pool["UserPool"]["Id"]
    )
for user in cognito_users["Users"]:
        integration_test_cognito.admin_delete_user(
            UserPoolId=integration_test_user_pool["UserPool"]["Id"],
            Username=user["Username"],
        )
```

**Comment by whummer** [comment]
Thanks for reporting @arpekkar . This should be fixed in the meantime - can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists. Thanks a lot for your help!

**Comment by villekr** [comment]
I can confirm this fix resolves the problem.

**Comment by davidlj95** [comment]
To speed up issues search, could we rename the title of the issue to `admin-delete-user`? As the bug was related to that operation, not the create one.
