### ISSUE TITLE
get_identity_pool_roles not implemented

### ISSUE THREAD

**Issue by theBenForce** [localstack/localstack#3378]
# Type of request: This is a ...

[ ] bug report
[x] feature request

# Detailed description

I'm trying to deploy a service with terraform that contains a [`aws_cognito_identity_pool_roles_attachment`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cognito_identity_pool_roles_attachment) resource. During deployment to localstack pro I see the following error logged several times, and terraform is stuck, continuously showing a `Still creating...` message.

```
NotImplementedError: The get_identity_pool_roles action has not been implemented
```

## Expected behavior

The `get_identity_pool_roles` api method should return details as defined in the [AWS Documentation](https://docs.aws.amazon.com/cognitoidentity/latest/APIReference/API_GetIdentityPoolRoles.html), even if application of the roles is not implemented.

## Actual behavior

The method isn't implemented, and an error is logged by localstack.

# Steps to reproduce

## Command used to start LocalStack

...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

...

**Comment by whummer** [comment]
Thanks for reporting @theBenForce . This should be fixed in the meantime - can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists. Thanks a lot for your help!
