### ISSUE TITLE
$LOCALSTACK_HOSTNAME not found? How to properly use LOCALSTACK_HOSTNAME env variable

### ISSUE THREAD

**Issue by njcongtou** [localstack/localstack#338]
I am running my lambda written in NodeJS and wants it to access localstack s3 service. So I have to use $LOCALSTACK_HOSTNAME env variable.

First, I set LOCALSTACK_HOSTNAME in my docker-compose file like this:

environment:
      - DEFAULT_REGION=us-west-2
      - SERVICES=${SERVICES-lambda, kinesis, s3}
      - DEBUG=1
      - DATA_DIR=${DATA_DIR- }
      - LAMBDA_EXECUTOR=docker
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LOCALSTACK_HOSTNAME=localstack

Then, I reference it from my NodeJS Lambda function.

s3 = new aws.S3({ apiVersion: 2006-03-01, endpoint: '${LOCALSTACK_HOSTNAME}:4572' });

But I got this error message.

Exception: Lambda process returned error status code: 1. Output:
START RequestId: a7e2d3a6-52e8-1fd3-51a7-f79777801360 Version: $LATEST
module initialization error: ReferenceError
    at Object.<anonymous> (/var/task/resources/eventLogger/logger.js:6:62)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/var/task/resources/pipeline.js:3:22)
    at Module._compile (module.js:570:32)

So how to use it properly ?

**Comment by njcongtou** [comment]
detailed error message:

2017-09-20T23:44:23.239Z	0466e24d-c7a8-19df-c26f-06e35c66ccc1	ReferenceError: LOCALSTACK_HOSTNAME is not defined
    at Response.s3.putObject (/var/task/resources/eventLogger/logger.js:30:110)
    at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:364:18)
    at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/var/task/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/var/task/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/var/task/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/task/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:685:12)

**Comment by whummer** [comment]
Thanks for reporting @njcongtou . Please note that `$LOCALSTACK_HOSTNAME` is not a global variable in your node.js program, but an *environment variable*. Have you tried accessing the environment variable using `process.env.LOCALSTACK_HOSTNAME`? Thanks

**Comment by njcongtou** [comment]
I did try to use `process.env.LOCALSTACK_HOSTNAME` but it still not worked. 

`process.env.LOCALSTACK_HOSTNAME is not defined`

**Comment by njcongtou** [comment]
I have found someone is able to do it in this issue. 
https://github.com/localstack/localstack/issues/284

**Comment by njcongtou** [comment]
Is this PR the fix ? https://github.com/localstack/localstack/pull/286

I am pulling the docker image. Maybe the fix is not in image?

**Comment by njcongtou** [comment]
I also tried to use docker IP directly as a host, but still does not work. 

ifconfig -> ip in en0

s3 = new aws.S3({ apiVersion: 2006-03-01, endpoint: '192.168.0.20:4572' });

**Comment by njcongtou** [comment]
This is my hello world nodejs lambda.

environment:
  - SERVICES=${SERVICES-lambda, kinesis, s3}
  - DEBUG=1
  - DATA_DIR=${DATA_DIR- }
  - LAMBDA_EXECUTOR=docker
  - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
  - DOCKER_HOST=unix:///var/run/docker.sock
  - LOCALSTACK_HOSTNAME=${LOCALSTACK_HOSTNAME- }
Reference LOCALSTACK_HOSTNAME in my code:

s3 = new AWS.S3({ apiVersion: '2006-03-01', endpoint: '${process.env.LOCALSTACK_HOSTNAME}:4572'});

Error:

localstack_1 | module initialization error: ReferenceError
localstack_1 | at Object. (/var/task/index.js:5:4)
localstack_1 | at Module._compile (module.js:570:32)
localstack_1 | at Object.Module._extensions..js (module.js:579:10)
localstack_1 | at Module.load (module.js:487:32)
localstack_1 | at tryModuleLoad (module.js:446:12)
localstack_1 | at Function.Module._load (module.js:438:3)
localstack_1 | at Module.require (module.js:497:17)
localstack_1 | at require (internal/module.js:20:19)
[hello.zip](https://github.com/localstack/localstack/files/1322014/hello.zip)

**Comment by whummer** [comment]
Looks like the reference error is caused by an undefined variable. If you change this:
```
s3 = new AWS.S3({ apiVersion: '2006-03-01', endpoint: `${process.env.LOCALSTACK_HOSTNAME}:4572`});
```
... to this:
```

var s3 = new AWS.S3({ apiVersion: '2006-03-01', endpoint: `${process.env.LOCALSTACK_HOSTNAME}:4572`});
```
then it should work.

**Comment by njcongtou** [comment]
@whummer Thanks for your reply. These are my complete creation part. 

const crypto = require('crypto'),
    R = require('ramda'),
    aws = require('aws-sdk'),
    s3 = new aws.S3({ apiVersion: `2006-03-01`, endpoint: `http://localstack:4572` });

**Comment by whummer** [comment]
Not sure about that. There might be another issue in your code, but I've been able to invoke the Lambda from `hello.zip` with the change described above.

**Comment by njcongtou** [comment]
@whummer Thanks let me try with hello.zip again.

**Comment by njcongtou** [comment]
@whummer I have tried hello world example again and located the exact issue. 

my lambda does 2 things, 1. list buckets 2. put object into one bucket I created. 

I am able to list bucket, but I am not able to put object into that bucket. The error I got is 

{ UnknownEndpoint: Inaccessible host: `mybucket.localstack'. This service may not be available in the `us-east-1' region.

Thanks for you help again. I wonder if I am doing it in the right way to save object into a bucket. The code is as follows:

const params = {
        Body: 'test',
        Bucket: 'mybucket',
        Key: 'test'
    };

    s3.putObject(params, (err) => {
      if (err) console.log(err, err.stack); // an error occurred
      else     console.log(data);           // successful response
    });

**Comment by njcongtou** [comment]
Is this issue related ? https://github.com/localstack/localstack/issues/43

**Comment by njcongtou** [comment]
I fixed it by taking advice from this Issue. https://github.com/localstack/localstack/issues/43

**Comment by njcongtou** [comment]
That is unfortunately the way how the S3 REST API (and hence the JS SDK) works. The design of the S3 API assumes that the bucket name is part of the domain name, hence the S3 JS SDK hardcodes the bucket name into the domain name of the URL used to contact the API.

There is a workaround, though. I was able to run your test by adding the following line to /etc/hosts:

127.0.0.1       hellobucket.localhost

**Comment by jpradelle** [comment]
I got something working with JS API without hosts file update using s3ForcePathStyle property:
```js
const s3 = new AWS.S3({ endpoint: 'http://127.19.0.1:4572', s3ForcePathStyle: true });
```
But I have localstack in docker if I use localhost it doesn't work, I have to put localstack docker ip to have it working, 127.19.0.1 instead of localhost.
