### ISSUE TITLE
localstack lambda doesn't seems to support golang

### ISSUE THREAD

**Issue by ypwu1** [localstack/localstack#3393]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description
I followed this tutorial [linked](https://blog.john-pfeiffer.com/localstack-apigateway-lambda-and-s3-integration-testing/) to create golang lambda. and no different except
with latest localstack
```
version: '3.7'

services:
  localstack:
    image: localstack/localstack:0.12.3
    ports:
      - "4566:4566"
    environment:
      - SERVICES=${SERVICES-lambda,apigateway,s3,cloudwatch}
      - DEBUG=${DEBUG- }
      - DEFAULT_REGION=ap-southeast-2
      - LAMBDA_EXECUTOR=docker
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LAMBDA_CONTAINER_REGISTRY="lambci/lambda:build-go1.x"
    volumes:
      - ".localstack:/tmp/localstack"
      - "/var/run
```

```
package main

import (
	"fmt"
	"github.com/aws/aws-lambda-go/lambda"
)

// MyEvent is a thing
type MyEvent struct {
	Name string `json:"name"`
}

// HandleRequest for an event
func HandleRequest(name MyEvent) (string, error) {
	return fmt.Sprintf("hi %s", name.Name), nil
}

func main() {
	lambda.Start(HandleRequest)
}
```

## Actual behavior
Get error
`{"errorMessage":"Lambda process returned error status code: 1. Result: . Output:\ninvalid reference format\nmust specify at least one container source\njson: cannot unmarshal array into Go value of type types.ContainerJSON","errorType":"Exception","stackTrace":["  File \"/opt/code/localstack/localstack/services/awslambda/lambda_api.py\", line 541, in run_lambda\n    result = LAMBDA_EXECUTOR.execute(func_arn, func_details, event, context=context,\n","  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 173, in execute\n    return do_execute()\n","  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 165, in do_execute\n    return _run(func_arn=func_arn)\n","  File \"/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py\", line 149, in wrapped\n    raise e\n","  File \"/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py\", line 145, in wrapped\n    result = func(*args, **kwargs)\n","  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 158, in _run\n    raise e\n","  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 146, in _run\n    result = self._execute(func_arn, func_details, event, context, version)\n","  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 303, in _execute\n    result = self.run_lambda_executor(cmd, stdin, env_vars=environment, func_details=func_details)\n","  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 210, in run_lambda_executor\n    raise Exception('Lambda process returned error status code: %s. Result: %s. Output:\\n%s' %\n"]}
`

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

aws lambda --endpoint-url=http://localhost:4566 invoke --function-name my-lambda --region=us-east-1 myout.log

**Comment by irahulranjan** [comment]
Hi @ypwu1, I am getting the correct output when I execute a lambda function with the code that you have given. 
Can you please share the sequence of aws CLI commands used which led to the issue? 
It would help us in resolving the issue faster.

**Comment by ypwu1** [comment]
@irahulranjan  This my scripts,  I ran it on mac oxs (10.15.7) with docker destop(3.0.2)
```
API_NAME=myl-ambda
REGION=ap-southeast-2
GOOS=linux go build -o bin/my-lambda main.go && zip -j -r bin/my-lambda.zip

awslocal lambda create-function \
    --region ${REGION} \
    --function-name ${API_NAME} \
    --runtime "go1.x" \
    --handler my-lambda \
    --memory-size 128 \
    --zip-file fileb://bin/my-lambda.zip \
    --role arn:aws:iam::123456:role/irrelevant
```

**Comment by ypwu1** [comment]
Reopen, sorry for accidentally closed

**Comment by irahulranjan** [comment]
Hi @ypwu1, Do you have the docker image **lambci/lambda:go1.x**? If not, please run **docker pull lambci/lambda:go1.x** and try.

**Comment by irahulranjan** [comment]
Hi @ypwu1, Closing this issue. Please reopen if the issue still persists
