### ISSUE TITLE
Terraform with localstack S3 backend fails

### ISSUE THREAD

**Issue by taksan** [localstack/localstack#3400]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

I'm trying to run a terraform project with an S3 backend bucket on localstack. I created the bucket and then ran terraform, but it ends up complaining that the bucket doesn't exist. The same code works on AWS S3. 

## Expected behavior

That terraform init finds the bucket and runs with success.

## Actual behavior

Terraform throws an error, saying the bucket doesn't exist.

# Steps to reproduce

1. Start localstack
2. Create a bucket named `bucket` with `aws --endpoint-url http://localhost:4566 --region us-east-1 s3 mb s3://backend`
3. Create the following terraform file:
```
terraform {
  backend "s3" {
    bucket          = "backend"
    key             = "tfkey/terraform.tfstate"
    region          = "us-east-1"
    endpoint        = "http://localhost:4566"
    sts_endpoint    = "http://localhost:4566"
  }
}
```
4. Set TF_LOG=TRACE
5. Execute `terraform init`

With debug enabled, you will see the following error:
```
2020/12/28 09:03:21 [DEBUG] [aws-sdk-go] <?xml version="1.0" encoding="UTF-8"?>
<Error>
    <Code>NoSuchBucket</Code>
    <Message>The specified bucket does not exist</Message>
    <BucketName>tfkey</BucketName>
    <RequestID>7a62c49f-347e-4fc4-9331-6e8eEXAMPLE</RequestID>
</Error>
2020/12/28 09:03:21 [DEBUG] [aws-sdk-go] DEBUG: Validate Response s3/GetObject failed, attempt 0/5, error NoSuchBucket: The specified bucket does not exist
	status code: 404, request id: 3C281AFA9A025FF7, host id: MzRISOwyjmnup3C281AFA9A025FF77/JypPGXLh0OVFGcJaaO3KW/hRAqKOpIEEp
Error refreshing state: S3 bucket does not exist.
```

Notice it complains that bucket `tfkey` doesn't exist, and that's not even the requested bucket (the requested bucket is `backend`)

## Command used to start LocalStack

With the following docker-compose.yml:

```
version: '2.1'

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    network_mode: bridge
    ports:
      - "4566:4566"
      - "4571:4571"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=${SERVICES- }
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

Just do docker-compose up

**Comment by taksan** [comment]
By the way, creating a bucket named `tfkey` will make it "work", but instead of creating the terraform state on s3://backend/tfkey/terraform.tfstate, it created on s3://tfkey/terraform.tfstate

**Comment by whummer** [comment]
Thanks for reporting @taksan - can you please ensure that the `s3_force_path_style` provider option is enabled? Please refer to the provider section in this example: https://github.com/localstack/localstack/blob/master/tests/integration/terraform/provider.tf#L8. Hope that helps - please let us know if the problem persists. Thanks

**Comment by taksan** [comment]
This is issue is not closed, it is still a bug.

I forgot to paste the providers.tf file, which was separate. Yes, the `s3_force_path_style  = true` was set. The problem is using localstack S3 in the backend. Creating S3 resources works fine. Let me paste the whole code:

backend.tf
```
terraform {
  backend "s3" {
    bucket          = "backend"
    key             = "tfkey/terraform.tfstate"
    region          = "us-east-1"
    endpoint        = "http://localhost:4566"
    sts_endpoint    = "http://localhost:4566"
  }
}
```

providers.tf
```
terraform {
  required_version = ">= 0.14.3"
  required_providers {
    aws       = "~> 3.12"
  }
}

provider "aws" {
  profile = "localstack"
  region  = "us-east-1"

  s3_force_path_style         = true
  skip_credentials_validation = true
  skip_metadata_api_check     = true
  skip_requesting_account_id  = true

  endpoints {
    apigateway     = "http://localhost:4566"
    cloudformation = "http://localhost:4566"
    cloudwatch     = "http://localhost:4566"
    dynamodb       = "http://localhost:4566"
    es             = "http://localhost:4566"
    firehose       = "http://localhost:4566"
    iam            = "http://localhost:4566"
    kinesis        = "http://localhost:4566"
    lambda         = "http://localhost:4566"
    route53        = "http://localhost:4566"
    redshift       = "http://localhost:4566"
    s3             = "http://localhost:4566"
    secretsmanager = "http://localhost:4566"
    ses            = "http://localhost:4566"
    sns            = "http://localhost:4566"
    sqs            = "http://localhost:4566"
    ssm            = "http://localhost:4566"
    stepfunctions  = "http://localhost:4566"
    sts            = "http://localhost:4566"
    ec2            = "http://localhost:4566"
  }
}```

**Comment by taksan** [comment]
Alright, I figured it out, thanks to @whummer tips. In this case, to fix the issue, the **backend** must be modified like this:

```
terraform {
  backend "s3" {
    bucket          = "backend"
    key             = "tfkey/terraform.tfstate"
    region          = "us-east-1"
    endpoint        = "http://localhost:4566"
    sts_endpoint    = "http://localhost:4566"
    force_path_style=true
  }
}
```
