### ISSUE TITLE
AWS S3 - ('Connection aborted.', error(61, 'Connection refused'))

### ISSUE THREAD

**Issue by wjlow** [localstack/localstack#341]
I'm using `TestUtils.getClientS3` from the Java SDK. I've put a break point after getting the S3 client, and then switched to AWS CLI to try and query S3, but I get an error:

```
$ aws --endpoint-url=http://localhost:4572 s3 ls s3://

('Connection aborted.', error(61, 'Connection refused'))
```

I've also tried using `--endpoint-url=http://test.localhost.atlassian.io:4572`

Instead of using `TestUtils.getClientS3`, I tried the following too with the same outcome:

```
AmazonS3ClientBuilder.standard
        .withEndpointConfiguration(new EndpointConfiguration(LocalstackTestRunner.getEndpointS3, TestUtils.DEFAULT_REGION))
        .withCredentials(new AWSStaticCredentialsProvider(TestUtils.TEST_CREDENTIALS))
        .withChunkedEncodingDisabled(true)
        .withPathStyleAccessEnabled(true)
        .build()
```

What am I doing wrong?

**Comment by whummer** [comment]
Thanks for reporting @wjlow . Can you provide a few details on how you are running LocalStack? Are you using the JUnit integration with `@RunWith(LocalstackTestRunner.class)`, or are you running LocalStack separately in a terminal? What is the log output of LocalStack in your case?

**Comment by wjlow** [comment]
Hi @whummer I'm running this in specs2 with Scala.

```

import org.junit.runner.RunWith
import cloud.localstack.{LocalstackTestRunner, TestUtils}
import org.specs2.mutable._


@RunWith(classOf[LocalstackTestRunner])
class FeedJobIntegrationSpec extends SpecificationWithJUnit {
  "test" should {
     "run" in {
          val s3 = TestUtils.getClientS3()
          s3.listBuckets.asScala.map(_.getName).foreach(println)
          1 == 1 
      }
   }
}

```

**Comment by wjlow** [comment]
Hmm... it must be how I'm integrating with the JUnit Test Runner through Specs2.

Created a bare Java project with JUnit and the same test worked.

I'm gonna try using JUnit in my Scala project for this test, and I'll let you know how I go.

**Comment by whummer** [comment]
Possible duplicate of #43 . Can you please try the fix suggested here: https://github.com/localstack/localstack/issues/43#issuecomment-308273958 (and here: https://github.com/localstack/localstack#troubleshooting)

**Comment by wjlow** [comment]
I managed to get it running by using JUnit for my test instead of Specs2 following the instructions here: https://alvinalexander.com/scala/how-to-use-junit-testing-with-scala

Thanks for the tool!
