### ISSUE TITLE
Hardcoded localhost causes issues with docker development

### ISSUE THREAD

**Issue by cimtico** [localstack/localstack#3415]
# Type of request: This is a ...

[x] feature request

# Detailed description
When attempting to set up localstack sqs with my application, I'm having issues with the returned urls, since they all have a hardcoded localhost, instead of the "domain" I used to access them (container to container network communication). It would be great if it was possible to configure the "domain" through an env var, which would also make it easier for us who develop within a containers.

## Expected behavior
When setting a "DOMAIN_URL" (or something like it), the created sqs queue urls return that domain instead of assuming "localhost".

## Actual behavior
It appears localhost is hardcoded as the response domain

# Steps to reproduce
Copy the docker-compose setup into a project's docker-compose (remove the network "bridge" setup, so that the app container can see the localstack container as "localstack")

## Command used to start LocalStack
docker-compose up localstack

**Comment by whummer** [comment]
Thanks for reporting @cimtico . You can use the `HOSTNAME_EXTERNAL` environment variable to achieve that.

For example, starting LocalStack like this:
```
$ HOSTNAME_EXTERNAL=foobar localstack start
```

... then the queue URL should contain your custom domain name:
```
$ awslocal sqs create-queue --queue-name q1
{
    "QueueUrl": "http://foobar:4566/000000000000/q1"
}
```
Additionally, if you also need to customize the external port number, you can use `SQS_PORT_EXTERNAL` for that purpose.

Hope that helps - please let us know if there are any issues. Thanks
