### ISSUE TITLE
I am not able to invoke apigateway of localstack

### ISSUE THREAD

**Issue by ravithejappl** [localstack/localstack#3417]
I am using different things to invoke localstack apigateway but it's giving error
I tried https://localhost:4566/{api_id}.execute-api.us-east-1.amazonaws.com/dev/
and http://localhost:4566/restapis/{api_id}/dev/todos

both are not working, Why it's calling bucket always 
Error I am getting is
<Error>
    <Code>NoSuchBucket</Code>
    <Message>The specified bucket does not exist</Message>
    <BucketName>restapis</BucketName>
    <RequestID>7a62c49f-347e-4fc4-9331-6e8eEXAMPLE</RequestID>

Please mention how to invoke apigateways.

**Comment by whummer** [comment]
Thanks for reporting @ravithejappl . We're using a special path format to identify API Gateway invocations - please refer to the note in the README here: https://github.com/localstack/localstack#invoking-api-gateway

Hope that helps - please keep us posted if things are unclear or if there are any other issues. Thanks
