### ISSUE TITLE
Unable to update stack "localstack-lambda-local": 'ApiGatewayDeployment1609579522368'

### ISSUE THREAD

**Issue by ravithejappl** [localstack/localstack#3421]
I am unable to update stack from vscode after making changes in serverless.yml file, I am trying to call serverless deploy --stage local to deploy it again but it's giving above mentioned error, is there any other thing do we need to follow for updating stack, in aws it's works fine.

**Comment by duongpv7** [comment]
Hi @ravithejappl, can you share your `serverless.yml` file to help us reproducing this issue?
Thanks

**Comment by whummer** [comment]
Hi @ravithejappl - thanks for reporting this issue. Do you think you can provide some more details (and a zip file or small sample repo with your project code) to help us reproduce this issue? Thanks for your help!

**Comment by levsilvestre** [comment]
Hello. 
I also have that error. could you help me?
I am working on MacOS.

**Comment by thrau** [comment]
There's not enough information for us to go on. Please try again with the latest docker image and open up a new issue should the problem resurface.
