### ISSUE TITLE
S3 metadata with dot . in the key is not stored

### ISSUE THREAD

**Issue by elrob** [localstack/localstack#3423]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

An S3 object metadata key with a `.` in it is lost silently.

Maybe the cause of this is similar to the cause of the underscore issue that was resolved with this workaround: https://github.com/localstack/localstack/pull/1965

## Expected behavior

As on AWS, a metadata key with a `.` in it is written and read without issue:
```
aws s3api put-object --bucket my-bucket --key my-key --metadata key-with.dot=123143123
aws s3api head-object --bucket my-bucket --key my-key
{
    "AcceptRanges": "bytes",
    "LastModified": "2021-01-03T15:57:20+00:00",
    "ContentLength": 0,
    "ETag": "\"d41d8cd98f00b204e9800998ecf8427e\"",
    "ContentType": "binary/octet-stream",
    "Metadata": {
        "key-with.dot": "123143123"
    }
}
```

## Actual behavior

Using localstack, a metadata key with a `.` is silently dropped:
```
aws --endpoint-url http://localhost:4566 s3api put-object --bucket my-bucket --key my-key --metadata key-with.dot=123143123
aws --endpoint-url http://localhost:4566 s3api head-object --bucket my-bucket --key my-key
{
    "LastModified": "2021-01-03T15:48:19+00:00",
    "ContentLength": 0,
    "ETag": "\"d41d8cd98f00b204e9800998ecf8427e\"",
    "ContentType": "binary/octet-stream",
    "Metadata": {}
}
```

# Steps to reproduce

(included above)

**Comment by whummer** [comment]
Thanks for reporting @elrob . This should be fixed in the meantime - can you please pull the `latest` Docker image and give it another try? Please report here if the problem persists. Thanks

**Comment by elrob** [comment]
@whummer 
Thank you. 
However, I have just tried with the latest: `localstack/localstack@sha256:1890318c68b5f1325f2a329cb232c6dda34de63daf766ea081c9168773365171`
and there is no change from the issue description above. The `Expected behavior` does not happen. `Actual behavior` is still what I'm experiencing. 
> a metadata key with a . is silently dropped:

**Comment by elrob** [comment]
Maybe the change on `localstack/moto` didn't get built/released properly? https://github.com/localstack/moto/releases

**Comment by whummer** [comment]
Thanks for the update @elrob . It seems like indeed there has been an issue when releasing and building the latest moto updates in our CI pipeline. Can you please pull the `latest` image again and give it another try? Please keep us posted how it goes.. Thanks

**Comment by elrob** [comment]
It works! Thank you.

```
$ aws --endpoint-url http://localhost:4566 s3api create-bucket --bucket my-bucket
$ aws --endpoint-url http://localhost:4566 s3api put-object --bucket my-bucket --key my-key --metadata key-with.dot=123143123
{
    "ETag": "\"d41d8cd98f00b204e9800998ecf8427e\""
}
$ aws --endpoint-url http://localhost:4566 s3api head-object --bucket my-bucket --key my-key
{
    "LastModified": "2021-01-24T14:03:59+00:00",
    "ContentLength": 0,
    "ETag": "\"d41d8cd98f00b204e9800998ecf8427e\"",
    "ContentType": "binary/octet-stream",
    "Metadata": {
        "key-with.dot": "123143123"
    }
}
```
