### ISSUE TITLE
How to read an SNS message ?

### ISSUE THREAD

**Issue by ashameem123** [localstack/localstack#3428]
# Type of request: This is a ...

User clarification

# Detailed description
I want to read messages received by SNS topic from lambda(screen shot attached-  trying to validate SNS - "email-sent")

When subscribe to the topic with endpoint as "email" and provide my email address , i never receive any notification to my email address containing message details (as received by SNS).
Is there a way to validate messages received by  SNS topic ?

## Expected behavior
should  be able to read SNS message content

## Actual behavior
Not sure how Localstack support this?

# Steps to reproduce

subscribe to topic command -

aws --endpoint-url=http://localhost:4566 sns subscribe --topic-arn arn:aws:sns:us-east-1:000000000000:putnotifications --protocol email --notification-endpoint test123@yahoo.com

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

...
Attaching the aws flow i am trying to test here.
![FlowToTest](https://user-images.githubusercontent.com/54183749/103676905-468f4980-4f47-11eb-9cfd-bc2ee03de7a2.jpg)

**Comment by emtiajium** [comment]
You can read it using the docker-compose command like, `docker-compose logs -f [put here your container name]`
