### ISSUE TITLE
Cant get or delete an event-source-mapping

### ISSUE THREAD

**Issue by mikebrules** [localstack/localstack#343]
Hello - I would expect this to work

        aws lambda list-event-source-mappings --endpoint http://localhost:4574
    
    {
     "EventSourceMappings": [
        {
            "UUID": "33473009-5eca-4fae-a3db-227d17e490f1",
            "StateTransitionReason": "User action",
            "LastModified": 1506077254.0,
            "BatchSize": 100,
            "State": "Enabled",
            "FunctionArn": "arn:aws:lambda:us-east-1:000000000000:function:DynamoToElasticUsers",
            "EventSourceArn": "arn:aws:dynamodb:ddblocal:000000000000:table/local-users",
            "LastProcessingResult": "OK"
        },.........

    aws lambda delete-event-source-mapping --uuid 33473009-5eca-4fae-a3db-227d17e490f1 --
    endpoint http://localhost:4574

    An error occurred (500) when calling the DeleteEventSourceMapping operation (reached max 
    retries: 4): <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
    <title>500 Internal Server Error</title>
    <h1>Internal Server Error</h1>
    <p>The server encountered an internal error and was unable to complete your request.  Either the 
    server is overloaded or there is an error in the application.</p>

Server error

     if uuid_value == m['uuid']:
     localstack_1  | KeyError: 'uuid'
     localstack_1  | 2017-09-22T10:58:46:ERROR:lambda_api: Exception on /2015-03-31/event-
     source-mappings/0ca61af5-f8e2-463e-83a8-b5c897867305 [DELETE]

Am I doing something wrong please?

**Comment by julienduchesne** [comment]
Don't know about the "list", but the delete was fixed here https://github.com/localstack/localstack/pull/340

**Comment by mikebrules** [comment]
thanks @julienduchesne, is that available in latest?

**Comment by whummer** [comment]
Yes, should be included if `latest` if you look at the timestamp here (images are built off of `master`): https://hub.docker.com/r/localstack/localstack/tags/

**Comment by mikebrules** [comment]
nice, fixed.  thanks @julienduchesne & @whummer
