### ISSUE TITLE
AWS S3 listVersions wrong ordering

### ISSUE THREAD

**Issue by igudkov-da** [localstack/localstack#3433]
# Type of request: This is a bug with S3 listVersions response ordering

[ x] bug report
[ ] feature request

# Detailed description
Wrong ordering of S3VersionSummary during AmazonS3 ``listVersions(ListVersionsRequest listVersionsRequest)`` method call

## Expected behavior
Versions are sorted from most recent to least recent as wrote in docs

## Actual behavior
Versions not sorted.

# Steps to reproduce

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

```
  //create versioned bucket
  amazonS3.createBucket("bucket");
  BucketVersioningConfiguration configuration =
                new BucketVersioningConfiguration().withStatus("Enabled");
  SetBucketVersioningConfigurationRequest setBucketVersioningConfigurationRequest =
                new SetBucketVersioningConfigurationRequest("bucket", configuration);
  amazonS3.setBucketVersioningConfiguration(setBucketVersioningConfigurationRequest);

  //save files
  List<SomeFileContent> contents = getSomeFilesContent();
  contents.forEach(content -> {
    ObjectMetadata objectMetadata = new ObjectMetadata();
    objectMetadata.setContentType("plain/text");
    objectMetadata.setContentLength(content.length);
    amazonS3.putObject("bucket", "fileName", new ByteArrayInputStream(content), objectMetadata);
  })

  //get versions
  ListVersionsRequest listVersionsRequest = new ListVersionsRequest().withBucketName(bucket);
  VersionListing versionListing = amazonS3.listVersions(listVersionsRequest)
  List<S3VersionSummary> summary = versionListing.getVersionSummaries(); //last saved file version should be first

```

**Comment by irahulranjan** [comment]
Hi @igudkov-da, the issue should be fixed in the master. can you pull and give it a try?

**Comment by whummer** [comment]
Thanks @igudkov-da @irahulranjan - should be fixed in the `latest` Docker image. Please report here if the problem persists. Thanks

**Comment by igudkov-da** [comment]
Hi there, still not worked correct.

**Comment by irahulranjan** [comment]
Hi @igudkov-da, can you please share the sequence of api calls/ aws cli commands and the output that you are getting.

**Comment by igudkov-da** [comment]
Hi @irahulranjan, below my simplify test on Java

```
import com.amazonaws.services.s3.AmazonS3;
import com.amazonaws.services.s3.AmazonS3ClientBuilder;
import com.amazonaws.services.s3.model.BucketVersioningConfiguration;
import com.amazonaws.services.s3.model.ListVersionsRequest;
import com.amazonaws.services.s3.model.ObjectMetadata;
import com.amazonaws.services.s3.model.PutObjectResult;
import com.amazonaws.services.s3.model.S3VersionSummary;
import com.amazonaws.services.s3.model.SetBucketVersioningConfigurationRequest;
import org.junit.Before;
import org.junit.ClassRule;
import org.junit.Test;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.testcontainers.containers.localstack.LocalStackContainer;
import org.testcontainers.utility.DockerImageName;

import java.io.ByteArrayInputStream;
import java.nio.ByteBuffer;
import java.security.SecureRandom;
import java.util.List;
import java.util.Random;
import java.util.stream.Collectors;
import java.util.stream.IntStream;

import static org.assertj.core.api.Assertions.assertThat;
import static org.testcontainers.containers.localstack.LocalStackContainer.Service.S3;

public class SummaryVersionsOrderTest {

    private static final Logger log = LoggerFactory.getLogger(SummaryVersionsOrderTest.class);

    @ClassRule
    public static final LocalStackContainer S3_CONTAINER = new LocalStackContainer(DockerImageName.parse("localstack/localstack:latest")).withServices(S3);
    private static final String VERSIONED_BUCKET = "versioned";
    private final AmazonS3 amazonS3Client = AmazonS3ClientBuilder.standard()
                                                                 .withCredentials(S3_CONTAINER.getDefaultCredentialsProvider())
                                                                 .withEndpointConfiguration(S3_CONTAINER.getEndpointConfiguration(S3))
                                                                 .build();

    @Before
    public void setUp() {
        S3_CONTAINER.start();
        amazonS3Client.createBucket(VERSIONED_BUCKET);
        BucketVersioningConfiguration configuration =
                new BucketVersioningConfiguration().withStatus("Enabled");
        SetBucketVersioningConfigurationRequest setBucketVersioningConfigurationRequest =
                new SetBucketVersioningConfigurationRequest(VERSIONED_BUCKET, configuration);
        amazonS3Client.setBucketVersioningConfiguration(setBucketVersioningConfigurationRequest);
    }

    @Test
    public void testScanResultMessage() {

        List<String> listOfVersion = getContent().stream().map(
                content -> {
                    ObjectMetadata objectMetadata = new ObjectMetadata();
                    objectMetadata.setContentType("plain/text");
                    objectMetadata.setContentLength(content.array().length);
                    PutObjectResult objectResult = amazonS3Client.putObject(VERSIONED_BUCKET, "file", new ByteArrayInputStream(content.array()), objectMetadata);
                    log.info("Saved version : {}", objectResult.getVersionId());
                    return objectResult.getVersionId();
                }).collect(Collectors.toList());

        ListVersionsRequest request = new ListVersionsRequest().withBucketName(VERSIONED_BUCKET);
        List<String> versionsFromSummary = amazonS3Client.listVersions(request)
                                                         .getVersionSummaries()
                                                         .stream()
                                                         .map(S3VersionSummary::getVersionId)
                                                         .collect(Collectors.toList());

        assertThat(listOfVersion).containsExactlyElementsOf(versionsFromSummary);
    }

    private List<ByteBuffer> getContent() {
        return IntStream.range(1, 5)
                        .boxed()
                        .map(this::randomContent)
                        .collect(Collectors.toList());
    }

    private ByteBuffer randomContent(int value) {
        byte[] content = new byte[100 * value];
        Random random = new SecureRandom();
        random.nextBytes(content);

        return ByteBuffer.wrap(content);
    }
}

```

sequence are:
- start container
- create bucket
- setBucketVersioningConfiguration
- x4 putObject calls
- listVersions call

**Comment by irahulranjan** [comment]
Hi @igudkov-da I converted the above code into sample cli commands:
`awslocal s3api create-bucket --bucket test
awslocal s3api put-bucket-versioning --bucket test --versioning-configuration Status=Enabled
awslocal s3api put-object --bucket test --key file
awslocal s3api put-object --bucket test --key file
awslocal s3api put-object --bucket test --key file1
awslocal s3api put-object --bucket test --key file
awslocal s3api list-object-versions --bucket test`

I get the following output which seems to be correct.
`{
    "Versions": [
        {
            "ETag": "\"d41d8cd98f00b204e9800998ecf8427e\"",
            "Size": 0,
            "StorageClass": "STANDARD",
            "Key": "file",
            "VersionId": "28cb2a7c-f3eb-498e-b5de-5397d7435d54",
            "IsLatest": true,
            "LastModified": "2021-01-12T19:58:45.000Z",
            "Owner": {
                "DisplayName": "webfile",
                "ID": "75aa57f09aa0c8caeab4f8c24e99d10f8e7faeebf76c078efc7c6caea54ba06a"
            }
        },
        {
            "ETag": "\"d41d8cd98f00b204e9800998ecf8427e\"",
            "Size": 0,
            "StorageClass": "STANDARD",
            "Key": "file",
            "VersionId": "d8da835b-3355-4e80-91eb-c9f3755fb47c",
            "IsLatest": false,
            "LastModified": "2021-01-12T19:58:43.000Z",
            "Owner": {
                "DisplayName": "webfile",
                "ID": "75aa57f09aa0c8caeab4f8c24e99d10f8e7faeebf76c078efc7c6caea54ba06a"
            }
        },
        {
            "ETag": "\"d41d8cd98f00b204e9800998ecf8427e\"",
            "Size": 0,
            "StorageClass": "STANDARD",
            "Key": "file",
            "VersionId": "8ad1bd89-3484-4c23-9848-d580123491b5",
            "IsLatest": false,
            "LastModified": "2021-01-12T19:57:38.000Z",
            "Owner": {
                "DisplayName": "webfile",
                "ID": "75aa57f09aa0c8caeab4f8c24e99d10f8e7faeebf76c078efc7c6caea54ba06a"
            }
        },
        {
            "ETag": "\"d41d8cd98f00b204e9800998ecf8427e\"",
            "Size": 0,
            "StorageClass": "STANDARD",
            "Key": "file",
            "VersionId": "04f81a32-48db-4b41-90bd-508a206d06d8",
            "IsLatest": false,
            "LastModified": "2021-01-12T19:57:34.000Z",
            "Owner": {
                "DisplayName": "webfile",
                "ID": "75aa57f09aa0c8caeab4f8c24e99d10f8e7faeebf76c078efc7c6caea54ba06a"
            }
        },
        {
            "ETag": "\"d41d8cd98f00b204e9800998ecf8427e\"",
            "Size": 0,
            "StorageClass": "STANDARD",
            "Key": "file1",
            "VersionId": "4ac9f790-7cc6-4a9d-8c7e-03565e8fd637",
            "IsLatest": true,
            "LastModified": "2021-01-12T19:57:42.000Z",
            "Owner": {
                "DisplayName": "webfile",
                "ID": "75aa57f09aa0c8caeab4f8c24e99d10f8e7faeebf76c078efc7c6caea54ba06a"
            }
        }
    ]
}`

Can you please try out the same and share the results?

**Comment by igudkov-da** [comment]
With cli it works for me to. But it is manual requests.
So I run my test one more time but with timeout 2 sec between each put request and it works fine too.
Without this timeout I've received summaries with ``lastModified`` equals for all elements, I guess this this the reason.
Dates don't store millis inside.

**Comment by igudkov-da** [comment]
@irahulranjan I guess here [append_last_modified_headers](https://github.com/localstack/localstack/blob/2c740f0949b72a2097edbcb1df07a3ff52aa1405/localstack/services/s3/s3_listener.py#L452) Millis should be add, no?

**Comment by irahulranjan** [comment]
@igudkov-da Can you please pull the latest localstack and try it out. The issue should be resolved. Thanks

**Comment by igudkov-da** [comment]
@irahulranjan now it works. Thanks.
