### ISSUE TITLE
Cloudwatch Metrics publication failed

### ISSUE THREAD

**Issue by ashameem123** [localstack/localstack#3436]
# Type of request: This is a ...

[*] bug report
[ ] feature request

# Detailed description
Getting error 404, publishing Cloud Watch metrics

## Expected behavior
Cloud Watch metrics should successfully publish.

## Actual behavior

Getting error 404, Metrics publication failed

Please refer the attached screen shot:

![image](https://user-images.githubusercontent.com/54183749/103796461-db0faf80-500c-11eb-92c4-fb644f460355.png)

**Comment by ashameem123** [comment]
@pinzon - any update on this issue ?

**Comment by pinzon** [comment]
Hi @ashameem123  looks like it's an issue with SDK v2 since the tests for cloudwatch [localstack-java-utils](https://github.com/localstack/localstack-java-utils) seem to work fine. I'm currently working on replicating the problem. 
Thank you for your patience

**Comment by pinzon** [comment]
@ashameem123 Could you provide more info info about how are you declaring your CloudWatch Client or how are you starting Localstack? 
I've just build an example with Java using AWS-SDK V2 and it works fine.

**Comment by ashameem123** [comment]
@pinzon Please find below the code for cloudwatch client builder,

public class CloudwatchService {

	CloudWatchClient cloudwatchClient;

	public CloudwatchService(@NonNull CloudWatchClient cloudwatchClient) {
		this.cloudwatchClient = cloudwatchClient;
	}

	public void publishMetrics(PutMetricsRequest metricsRequest) {

		PutMetricDataRequest.Builder requestBuilder = PutMetricDataRequest.builder();
		requestBuilder.namespace(metricsRequest.getNamespace());

		List<MetricDatum> awsMetricDataList = new ArrayList<>();

		for ( MetricData metricData : metricsRequest.getMetricDataList() ) {

			MetricDatum.Builder datumBuilder = MetricDatum.builder()
				.metricName(metricData.getItemName())
				.timestamp(metricData.getTimestamp())
				.unit(metricData.getUnit().toString())
				.value(metricData.getValue());

			if (metricData.isHighResolution()) {
				datumBuilder.storageResolution(1);
			} else {
				datumBuilder.storageResolution(60);
			}

			if (metricData.getDimensions() != null && !metricData.getDimensions().isEmpty()) {

				List<Dimension> awsDimensionList = new ArrayList<>();
				Set<String> keySet = metricData.getDimensions().keySet();
				Iterator<String> keyIter = keySet.iterator();

				while (keyIter.hasNext()) {
					Dimension.Builder dimBuilder = Dimension.builder();
					String key = keyIter.next();
					dimBuilder.name(key).value(metricData.getDimensions().get(key));
					awsDimensionList.add(dimBuilder.build());
					if (awsDimensionList.size() >= 10) {
						break;
					}
				}

				datumBuilder.dimensions(awsDimensionList);
			}
			awsMetricDataList.add(datumBuilder.build());
		}

		if (awsMetricDataList.isEmpty()) {
			return;
		}

		requestBuilder.metricData(awsMetricDataList);

		PutMetricDataRequest putRequest = requestBuilder.build();

		cloudwatchClient.putMetricData(putRequest);
	}
}


Command to start Localstack ->  docker-compose up -d

**Comment by pinzon** [comment]
Hi @ashameem123 your code doesn't show how it declares your CW client but I wrote a sample code that tries to approach your example, hope it helps you. I'm gonna close this issue for now since it looks like an usage problem and not really bug.
```
     public void testCWMultipleDimentionsAndMetrics() throws Exception {
        // final CloudWatchAsyncClient clientCW = TestUtils.getClientCloudWatchAsyncV2();
        final CloudWatchAsyncClient  clientCW = CloudWatchAsyncClient.builder()
                .httpClient(NettyNioAsyncHttpClient.builder().buildWithDefaults(
                    AttributeMap.builder().put(
                        SdkHttpConfigurationOption.TRUST_ALL_CERTIFICATES, java.lang.Boolean.TRUE).build()))
                .credentialsProvider(
                    StaticCredentialsProvider.create(AwsBasicCredentials.create("access", "secret"))
                )
                .region(Region.US_EAST_1)
                .endpointOverride(new URI("http://localhost:4566")).build();
        
        List<Dimension> awsDimensionList = new ArrayList<>();
        for (int i = 0; i < 10; i++) {
            awsDimensionList.add(Dimension.builder()
                    .name("UNIQUE_PAGES"+i)
                    .value("URLS"+i)
                    .build());
        };

        // Set an Instant object
        String time = ZonedDateTime.now( ZoneOffset.UTC ).format( DateTimeFormatter.ISO_INSTANT );
        Instant instant = Instant.parse(time);
        double dataPoint = 1.23423;
        
        List<MetricDatum> metrics = new ArrayList();
        for (int i = 0; i < 10; i++) {
            metrics.add(MetricDatum.builder()
            .metricName("PAGES_VISITED")
            .unit(StandardUnit.NONE)
            .value(dataPoint)
            .timestamp(instant)
            .dimensions(awsDimensionList).build());
        };

        PutMetricDataRequest request = PutMetricDataRequest.builder()
             .namespace("SITE/TRAFFIC")
             .metricData(metrics).build();

        PutMetricDataResponse response = clientCW.putMetricData(request).get();

    }
```
