### ISSUE TITLE
How to read data written in elastic search cluster ?

### ISSUE THREAD

**Issue by ashameem123** [localstack/localstack#3439]
# Type of request: This is a ...

[ ] bug report
[ ] feature request

# Detailed description
Need details on how to read data written in elastic search index in localstack, running ES in a different container. 
Also getting error 500 on hitting command -"list-elasticsearch-versions"

aws --endpoint-url=http://localhost:4571 es list-elasticsearch-versions

## Expected behavior
Should be able to lookup for running es version.
Also please provide some details on how to read es index content?

## Actual behavior
Getting error on running command - list-elasticsearch-versions

# Steps to reproduce
-Running es in a different container(docker-compose file attached)
- Once lambda is executed, it should write the data to es index

## Command used to start LocalStack
docker-compose up -d

Docker-compose.yml:
```
version: '2.2'

services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.6
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch6-8/data
    ports:
      - 9200:9200

  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack:latest
    ports:
      - "4566-4599:4566-4599"
      - "${PORT_WEB_UI-8081}:${PORT_WEB_UI-8080}"
    environment:
      - AWS_REGION=us-east-1
      - SERVICES=${SERVICES- }
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=docker
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LAMBDA_DOCKER_NETWORK=ecare-localstackdemoallservices_default
      - HOST_TMP_FOLDER=${TMPDIR}
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  data01:
    driver: local
```

Screenshot of the error:
![image](https://user-images.githubusercontent.com/54183749/103818311-e1625380-502d-11eb-9950-f729c94e5895.png)

**Comment by mgagliardo** [comment]
Hey @ashameem123, thanks for reporting this issue.

First of all I have just created PR https://github.com/localstack/localstack/pull/3582 to add the `list-elasticsearch-versions` and fix this.
```
$ awslocal es list-elasticsearch-versions
{
    "ElasticsearchVersions": [
        "7.7.0",
        "7.4.0",
        "7.1.0",
        "6.7.0"
    ]
}
```

Second, a few points in your PR:

1. `aws --endpoint-url=http://localhost:4571 es list-elasticsearch-versions`

This query should be against `http://localhost:4566` (localstack's API) and not against ES API, you can also use `awslocal` for this matter (as you can see in my example).

2. `list-elasticsearch-versions` is not to meant to list the current installed version but to list the `available` ES versions (to be installed). You can see that on the [AWS ES API definition](https://docs.aws.amazon.com/en_us/elasticsearch-service/latest/developerguide/es-configuration-api.html#es-configuration-api-actions-listelasticsearchversions)

3.  To read/write ES content you need to:
* Create an ES domain (wait for ES to come up):
```
$ awslocal --debug es create-elasticsearch-domain --domain-name test
```
* After is up, you can create your own index, interact with the ES API, etc. For example:
```
$ curl 'http://localhost:4571/_cat/health?format=json&pretty'
[
  {
    "epoch" : "1612812048",
    "timestamp" : "19:20:48",
    "cluster" : "elasticsearch",
    "status" : "green",
    "node.total" : "1",
    "node.data" : "1",
    "shards" : "0",
    "pri" : "0",
    "relo" : "0",
    "init" : "0",
    "unassign" : "0",
    "pending_tasks" : "0",
    "max_task_wait_time" : "-",
    "active_shards_percent" : "100.0%"
  }
]
```
```
$ curl -X PUT 'http://localhost:4571/index2?format=json&pretty'
{
  "acknowledged" : true,
  "shards_acknowledged" : true,
  "index" : "index2"
}
```
```
$ curl 'http://localhost:4571/_cat/indices?format=json&pretty'
[
  {
    "health" : "yellow",
    "status" : "open",
    "index" : "index2",
    "uuid" : "onXNXKxTTo2mN-ukipYowA",
    "pri" : "1",
    "rep" : "1",
    "docs.count" : "0",
    "docs.deleted" : "0",
    "store.size" : "208b",
    "pri.store.size" : "208b"
  }
]
```
And so on.. Please refer to the official elasticsearch documentation for more API methods, libraries, etc.

4. Lastly, at the moment you can not use your own, separated elasticsearch container/cluster and as far as I am concerned (correct me if I am wrong) localstack  does not have a roadmap for that, but neither AWS has that same functionality.

I am closing this, hoping I could resolve your inquiries. Cheers!
