### ISSUE TITLE
localstack fails at the creation of SNS topics

### ISSUE THREAD

**Issue by mnsanfilippo** [localstack/localstack#3441]
# Type of request: This is a ...

[ x] bug report
[ ] feature request

# Detailed description
A function that creates a sns topic is failing at localstack, if I run the code against AWS there is no problem and the topic is created
...

## Expected behavior
The SNS topic should be created and it should return the topic ARN
...

## Actual behavior

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x135f5ca]
```

If I create the topic with awscli, this is what I get:
` aws --endpoint-url=http://localhost:4566   sns create-topic --name aName`

```
Unable to parse response (not well-formed (invalid token): line 1, column 0), invalid XML received. Further retries may succeed:
b'{}'
```

...

# Steps to reproduce
Try to create a topic 

With awscli
` aws --endpoint-url=http://localhost:4566  sns create-topic --name aName`

With Go

```
	req, err :=  svc.CreateTopic(context.Background(), &sns.CreateTopicInput{
		Name:       aws.String(name),
	})

```
## Command used to start LocalStack
```
version: '2.1'

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-sns_test}"
    image: localstack/localstack:latest
    network_mode: bridge
    ports:
      - "4566:4566"
      - "4571:4571"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=sns,serverless
      - TMPDIR=/private/$TMPDIR
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      
```
`docker-compose up -d`
## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
With awscli
` aws --endpoint-url=http://localhost:4566  sns create-topic --name aName`

With Golang Code:

```
func TestCreateTopic(t *testing.T){

cfg, err := config.LoadDefaultConfig(context.TODO(), config.WithEndpointResolver(
		aws.EndpointResolverFunc(func(service, region string) (aws.Endpoint, error) {
			return aws.Endpoint{URL: "http://127.0.0.1:4566"}, nil
		})), config.WithRegion("us-east-1"), config.WithSharedConfigProfile(awsProfile))
	if err != nil {
		log.Fatal(err)
	}
	topicArn, err := CreateTopic("aName", cfg)
	if err != nil{
		logrus.Println(err)
		t.Error(err)
	}
	if  topicArn !=  ""{
		logrus.Println("The arn is:",  topicArn)
	}
}

```

```
func CreateTopic(name string, cfg aws.Config) (string, error) {

	svc := sns.NewFromConfig(cfg)
	req, err :=  svc.CreateTopic(context.Background(), &sns.CreateTopicInput{
		Name:       aws.String(name),
	})
	return *req.TopicArn, err
}
```

**Comment by irahulranjan** [comment]
hi @mnsanfilipp, Have you configured the test credentials?

**Comment by mnsanfilippo** [comment]
> hi @mnsanfilipp, Have you configured the test credentials?

Hello! I have this:
```
[dynamodb]
aws_access_key_id = 123
aws_secret_access_key = 123
```

and that is the profile that I use

**Comment by irahulranjan** [comment]
Hi @mnsanfilippo, I tried executing the above CLI command it creates the topic successfully. Can you use the following and try once:

~/.aws/credentials
[test]
aws_access_key_id = test
aws_secret_access_key = test

~/.aws/config
[profile test]
region = us-east-1
output = json

**Comment by mnsanfilippo** [comment]
Hello @irahulranjan, It worked well through awscli, but if I try to do it through the sdk, I get
`operation error SNS: CreateTopic, https response error StatusCode: 400, RequestID: bdc8b760, api error InvalidParameter: Invalid region specified in "Authorization" header: "" 
`

**Comment by irahulranjan** [comment]
@mnsanfilippo Can you please share a minimal main.go file using which I can reproduce the issue.

**Comment by mnsanfilippo** [comment]
@irahulranjan, yes, here it is
```
package main

import (
	"context"
	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/config"
	"github.com/aws/aws-sdk-go-v2/service/sns"
	"github.com/sirupsen/logrus"
	"log"
)

func main() {
	cfg, err := config.LoadDefaultConfig(context.TODO(), config.WithEndpointResolver(
		aws.EndpointResolverFunc(func(service, region string) (aws.Endpoint, error) {
			return aws.Endpoint{URL: "http://localhost:4566"}, nil
		})), config.WithRegion("us-east-1"), config.WithSharedConfigProfile("test"))
	if err != nil {
		log.Fatal(err)
	}

	svc := sns.NewFromConfig(cfg)
	req, err := svc.CreateTopic(context.Background(), &sns.CreateTopicInput{Name: aws.String("testTopic")})

	if err != nil {
		logrus.Println(err)
	}
	if *req.TopicArn != "" {
		logrus.Println("The arn is:", *req.TopicArn)
	}
}
```

**Comment by irahulranjan** [comment]
Please use the following:
`return aws.Endpoint{URL: "http://localhost:4566", **SigningRegion: "us-east-1"**}`

**Comment by mnsanfilippo** [comment]
Thanks!!!
My bad
Have a nice Weekend @irahulranjan
