### ISSUE TITLE
Error probabilities should be mutable

### ISSUE THREAD

**Issue by killthrush** [localstack/localstack#346]
For a number of integration test scenarios, I'd like to be able to modify the error probability setting while localstack is running.  This is mainly for performance - spin up docker/localstack at the beginning of the test run, run the suite, then spin everything down.  Unfortunately, I can't do this because the probability settings are in config and are essentially fixed for the lifetime of the process.

I'd like to be able to inject these settings into the docker container on demand so I can better control what my tests are doing.  I can see where to make the change, and I'd be happy to implement it, but wanted to see if there are any constraints on how I should approach it.  My initial though was just to let the services read the env var every time it's requested instead of storing it in config.  Thoughts on this?

**Comment by adriangalera** [comment]
Hi, I need to implement a similar scenario. However the approach of using the environment variables didn't work for me.
I end up reading a file on each request, which is not very nice. However it worked for me.
It would be very nice to add this feature without any hacky solution

**Comment by whummer** [comment]
Thanks for reporting @killthrush @adriangalera . Initial support has been added in #1201. Please refer to the PR and the instructions in the README on how to dynamically update configuration variables at runtime.

Closing this ticket - please comment here if there are any issues with this new feature.
