### ISSUE TITLE
Can't copy files to/from LocalStack -> S3 using Boto3 in separate docker container

### ISSUE THREAD

**Issue by cwmcmullen** [localstack/localstack#3469]
# Type of request: This is a ...

[ ] bug report
[ ] feature request
[*] problem report / request for help

I am brand new to LocalStack, so maybe I just need a little help getting my LocalStack environment configured correctly.

# Detailed description

Currently we are using the following services in AWS:

* RDS -> Postgres
* S3
* EC2 -> Linux. Python codebase runs in a Docker container  on ECS.

I’m using docker compose to launch:

* Localstack with the S3 service
* The above Python codebase in a Docker container.
  * This codebase accesses a Postgres DB running on my computer
  * This codebase uses Boto3 to access S3

When I start up the environment using ``docker-compose up``, the Python codebase is able to:

* Connect to the local Postgres DB
* Run list_objects_v2() against LocalStack -> S3

Also, outside of LocalStack I am able to copy files to/from the S3 bucket in the LocalStack container.

    $ aws --endpoint-url=http://localhost:4566 s3 cp hello_world.txt s3://laptop-s3-bucket/incoming/
    upload: ./hello_world.txt to s3://laptop-s3-bucket/incoming/hello_world.txt

    $ aws --endpoint-url=http://localhost:4566 s3 ls s3://laptop-s3-bucket/incoming/
    2021-01-14 07:49:04         12 hello_world.txt

    $ aws --endpoint-url=http://localhost:4566 s3 cp s3://laptop-s3-bucket/incoming/hello_world.txt .
    download: s3://laptop-s3-bucket/incoming/hello_world.txt to ./hello_world.txt

    $ aws --endpoint-url=http://localhost:4566 s3 rm s3://laptop-s3-bucket/incoming/hello_world.txt
    delete: s3://laptop-s3-bucket/incoming/hello_world.txt

BUT from the Python codebase I cannot copy files to/from the S3 bucket!

    botocore.exceptions.ClientError: An error occurred (403) when calling the HeadObject operation: Forbidden

I tried applying this S3 bucket policy which has not helped.

    {
      "Version": "2020-01-01",
      "Statement": [
        {
          "Sid": "AssignUserActions",
          "Effect": "Allow",
          "Principal": "*",
          "Action": [
            "s3:PutObject",
            "s3:GetObject",
            "s3:ListBucket",
            "s3:DeleteObject",
            "s3:GetBucketLocation",
            "S3:HeadBucket"
          ],
          "Resource": [
            "arn:aws:s3:::laptop-s3-bucket",
            "arn:aws:s3:::laptop-s3-bucket/*"
          ]
        }
      ]
    }

My docker-compose.yaml contains the following:

    version: "3.8"

    services:
      myapp:
        container_name  : myapp
        image           : myapp
        hostname        : myapp
        depends_on:
          - localstack
        networks:
          # for accessing S3 bucket in LocalStack
          - localstack-network

        environment:
          - AWS_ACCESS_KEY_ID       : foo
          - AWS_SECRET_ACCESS_KEY   : bar
          - ENDPOINT_URL            : http://host.docker.internal:4566
          - AWS_REGION              : us-east-1
          - AWS_ENVIRONMENT         : laptop

      localstack:
        container_name: localstack
        image: localstack/localstack
        hostname: localstack
        networks:
          - localstack-network
        ports:
          - "4566:4566"   # edge interface

        environment:
          - SERVICES=s3
          - DEBUG=0
          - DATA_DIR=/tmp/localstack/data
          - DOCKER_HOST=unix:///var/run/docker.sock
          - HOST_TMP_FOLDER=${TMPDIR}
        volumes:
          - ./data:/tmp/localstack
          - "/var/run/docker.sock:/var/run/docker.sock"
          - ./bin:/docker-entrypoint-initaws.d

    networks:
      localstack-network:
        external: false
        driver: bridge
        name: localstack-network

## Expected behavior

That the S3 upload/download commands would work in the LocalStack environment like they do when the codebase is running in AWS.

## Actual behavior

As mentioned above, I get the following ClientError

    botocore.exceptions.ClientError: An error occurred (403) when calling the HeadObject operation: Forbidden

# Steps to reproduce

## Command used to start LocalStack

    docker-compose up

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

    import boto3
    import os

    # This module includes methods that retrieve the values of environment
    # variables, as well as making sure the specified environment variable
    # is set. If not, an exception is raised.
    import de.docker_environment_variables

    class S3Connection:
        """
        This class initializes s3_client, s3_resource and s3_bucket objects.
        """
        def __init__(self):

            # https://boto3.amazonaws.com/v1/documentation/api/latest/reference/core/session.html#boto3.session.Session
            session = boto3.session.Session()

            session_args = {
                'service_name': 's3',
                'region_name': de.docker_environment_variables.aws_region(),
            }

            if de.docker_environment_variables.aws_environment() == 'laptop':
                # Don't use SSL when running on my laptop in order to eliminate
                # the following error with LocalStack:
                #
                # botocore.exceptions.SSLError: SSL validation failed for https://laptop-s3-bucket.s3.amazonaws.com/incoming/BCBSMN_DXTO_20201230133020.control [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)
                session_args['verify'] = False
                session_args['use_ssl'] = False

            if de.docker_environment_variable_names.DEV_ENDPOINT_URL in os.environ:
                session_args['endpoint_url'] = de.docker_environment_variables.endpoint_url()

            if de.docker_environment_variable_names.DEV_AWS_ACCESS_KEY_ID in os.environ:
                session_args['aws_access_key_id'] = de.docker_environment_variables.aws_access_key_id()

            if de.docker_environment_variable_names.DEV_AWS_SECRET_ACCESS_KEY in os.environ:
                session_args['aws_secret_access_key'] = de.docker_environment_variables.aws_secret_access_key()

            # Instantiate S3 client
            self.s3_client = session.client(**session_args)

            resource_args = dict()

            if de.docker_environment_variables.aws_environment() == 'laptop':
                # Don't use SSL when running on my laptop in order to eliminate
                # the following error with LocalStack:
                #
                # botocore.exceptions.SSLError: SSL validation failed for https://laptop-s3-bucket.s3.amazonaws.com/incoming/BCBSMN_DXTO_20201230133020.control [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)
                resource_args['verify'] = False
                resource_args['use_ssl'] = False

            if de.docker_environment_variable_names.DEV_AWS_ACCESS_KEY_ID in os.environ:
                resource_args['aws_access_key_id'] = de.docker_environment_variables.aws_access_key_id()

            if de.docker_environment_variable_names.DEV_AWS_SECRET_ACCESS_KEY in os.environ:
                resource_args['aws_secret_access_key'] = de.docker_environment_variables.aws_secret_access_key()

            # Instantiate Boto3 S3 resource
            self.s3_resource = boto3.resource('s3', **resource_args)

            self.s3_bucket = self.s3_resource.Bucket(de.docker_environment_variables.s3_bucket_name())

    s3_connection = S3Connection()
    s3_client = s3_connection.s3_client
    s3_bucket = s3_connection.s3_bucket

    response = s3_client.list_objects_v2(Bucket=de.docker_environment_variables.s3_bucket_name(),
                                         Prefix='incoming/')

    for element in response['Contents']:
        bucket_key = element['Key']

        with open(local_filepath, 'wb') as fh:
            # https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3.html#S3.Bucket.download_fileobj
            s3_bucket.download_fileobj(Key=bucket_key, Fileobj=fh)  # THIS IS WHERE THE ERROR OCCURS
                                                                    # botocore.exceptions.ClientError: An error occurred (403) when calling the HeadObject operation: Forbidden

**Comment by whummer** [comment]
Thanks for reporting @cwmcmullen . Can you please share some details about how your `s3_client` client is created? Please note that you'll need to configure the `endpoint_url` of your `boto3` client (similar to `--endpoint-url` for the `aws` command line).

This sample Lambda from our integration tests could be helpful: https://github.com/localstack/localstack/blob/1bdea066817ec6a9026ada987e9c8fb85a39002f/tests/integration/lambdas/lambda_triggered_by_sqs_download_s3_file.py#L9-L10

Hope that helps - please keep us posted. Thanks

**Comment by cwmcmullen** [comment]
I updated my original post (above) with my S3Connection class, that initializes S3 objects.

Thanks for the code snippet. My S3Connection class does pass the **endpoint_url**, **region_name** and **verify** arguments when instantiating the S3 Client (hopefully you can see that in my code above). It only does this when running on my laptop in a docker container, which is when I set my AWS_ENVIRONMENT variable to 'laptop', which you can see in my code above.

Also, my **bin/localstack-entrypoint.sh** script runs the following code to populate **~/.aws/config**, some of which you'll see is the same as what I have defined in **myapp -> environment**.

        aws configure set aws_access_key_id foo
        aws configure set aws_secret_access_key bar

        echo "[default]" > ~/.aws/config
        echo "region = us-east-1" >> ~/.aws/config
        echo "output = json" >> ~/.aws/config
        echo "verify = false" >> ~/.aws/config
        echo "use_ssl = false" >> ~/.aws/config

Thanks for your help!

**Comment by mgagliardo** [comment]
Hey @cwmcmullen, so a couple things:

* Guessing you are able from your container to your localstack using `host.docker.internal` (I have used the option `--link=localstack` which is basically the same) it looks like you are missing the parameter `resource_args['endpoint_url']` on your code, you are setting it up for your session args but not for your resource args and that is why it is failing

Taken from [boto3 docs](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/core/session.html#boto3.session.Session.resource)
```
endpoint_url (string) -- The complete URL to use for the constructed client. Normally, botocore will automatically construct the appropriate URL to use when communicating with a service. You can specify a complete URL (including the "http/https" scheme) to override this behavior. If this value is provided, then use_ssl is ignored.
```

So it is highly probably (won't lie, I have not taken a look at boto3's internal code) the `endpoint_url` is being set to `None` and because you have a cross reference (one pointing to `http://host.docker.internal:4566` and the other to `None` because of default values)  it is giving you a 403.

Here's the code I have used successfully (all hardcoded I know, but it checks out).


```
import boto3
import os

class S3Connection:
    """
    This class initializes s3_client, s3_resource and s3_bucket objects.
    """
    def __init__(self):

        # https://boto3.amazonaws.com/v1/documentation/api/latest/reference/core/session.html#boto3.session.Session
        session = boto3.session.Session()

        session_args = {
            'service_name': 's3',
            'region_name': 'us-east-1'
        }

        session_args['verify'] = False
        session_args['use_ssl'] = False
        session_args['endpoint_url'] = 'http://localstack:4566'
        session_args['aws_access_key_id'] = 'foo'
        session_args['aws_secret_access_key'] = 'bar'
        # Instantiate S3 client
        self.s3_client = session.client(**session_args)

        resource_args = dict()

        resource_args['verify'] = False
        resource_args['use_ssl'] = False
        resource_args['endpoint_url'] = 'http://localstack:4566'
        resource_args['aws_access_key_id'] = 'foo'
        resource_args['aws_secret_access_key'] = 'bar'

        # Instantiate Boto3 S3 resource
        self.s3_resource = boto3.resource('s3', **resource_args)
        self.s3_bucket = self.s3_resource.Bucket('test-bucket')

s3_connection = S3Connection()
s3_client = s3_connection.s3_client
s3_bucket = s3_connection.s3_bucket

response = s3_client.list_objects_v2(Bucket='test-bucket',Prefix='incoming/')

for element in response['Contents']:
    bucket_key = element['Key']

    # File and key are hardcoded
    with open('/tmp/potato.txt', 'wb') as fh:
        # https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3.html#S3.Bucket.download_fileobj
        s3_bucket.download_fileobj(Key='test.txt', Fileobj=fh)
```

I have run a simple alpine container and setup the awscli the same you did [here](https://github.com/localstack/localstack/issues/3469#issuecomment-760942867) and just ran this python code in it.

Let me know if it works for you.

**Comment by cwmcmullen** [comment]
Hey @mgagliardo,
Thanks for looking into this and letting me know the solution. 
I'll give your suggestions a try and let you know how it goes.
