### ISSUE TITLE
Specifying _debug_port_ or hardcoding portnumber  in docker_compose.yml in LAMBDA_JAVA_OPTS not being respected

### ISSUE THREAD

**Issue by VandanaAwasthi** [localstack/localstack#3479]
# Type of request: This is a ...

[ x] bug report
[ ] feature request

# Detailed description
in docker compose under environment section adding 
LAMBDA_JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=*:_debug_port_]
or
LAMBDA_JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=*:5025

is not suspending the java execution of lambda to enable me to remote debug using IDE.

## Expected behavior

should suspend execution, wait for remote debugger to attach to the process and then let developer step through the process.

## Actual behavior

it ignores the option and just executes the lambda function.

# Steps to reproduce
in docker compose under environment section adding 
LAMBDA_JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=*:_debug_port_]
or
LAMBDA_JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=*:5025
## Command used to start LocalStack

docker_compose up
which in turn starts localstack. 

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

...

**Comment by VandanaAwasthi** [comment]
i have done a bit of debug on the lambda_executor.py script
and I see 
on line 55
# whether to use our custom Java executor, or the default from lambci
# TODO: deprecated, should be removed in the future
USE_CUSTOM_JAVA_EXECUTOR = False    <<<<
and then on line 301 we read java_opts 
if USE_CUSTOM_JAVA_EXECUTOR and is_java_lambda(runtime):
            # if running a Java Lambda with our custom executor, set up classpath arguments
            java_opts = Util.get_java_opts()


looks like java_opts never gets read in. if I remove the first condition and check for java_opts for any java lambda invoke,
then I am able to bind to a given port.

Another issue in using _debug_port_ once the above condition is fixed is, that the free tcp port it binds to  is not output to user and user is unaware of which port to bind to for attaching the debugger.

**Comment by mgagliardo** [comment]
Hey @VandanaAwasthi, can you post some error logs, events, your code or whatever you might have? I tried reproducing the issue but got this, I am wondering if you got the same or maybe am I doing something wrong:

```
> ERROR: transport error 202: gethostbyname: unknown host
> ERROR: JDWP Transport dt_socket failed to initialize, TRANSPORT_INIT(510)
> JDWP exit error AGENT_ERROR_TRANSPORT_INIT(197): No transports initialized [debugInit.c:750]
2021-01-28T01:55:09:INFO:localstack.services.awslambda.lambda_api: Error executing Lambda function arn:aws:lambda:us-east-1:000000000000:function:test: Lambda process returned error status code: 2. Result: . Output:
ERROR: transport error 202: gethostbyname: unknown host
ERROR: JDWP Transport dt_socket failed to initialize, TRANSPORT_INIT(510)
JDWP exit error AGENT_ERROR_TRANSPORT_INIT(197): No transports initialized [debugInit.c:750] Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 550, in run_lambda
    result = LAMBDA_EXECUTOR.execute(func_arn, func_details, event, context=context,
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 174, in execute
    return do_execute()
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 166, in do_execute
    return _run(func_arn=func_arn)
  File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 149, in wrapped
    raise e
  File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 145, in wrapped
    result = func(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 157, in _run
    raise e
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 145, in _run
    result = self._execute(func_arn, func_details, event, context, version)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 323, in _execute
    result = self.run_lambda_executor(cmd, stdin, env_vars=environment, func_details=func_details)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 229, in run_lambda_executor
    raise InvocationException('Lambda process returned error status code: %s. Result: %s. Output:\n%s' %
localstack.services.awslambda.lambda_executors.InvocationException: Lambda process returned error status code: 2. Result: . Output:
ERROR: transport error 202: gethostbyname: unknown host
ERROR: JDWP Transport dt_socket failed to initialize, TRANSPORT_INIT(510)
JDWP exit error AGENT_ERROR_TRANSPORT_INIT(197): No transports initialized [debugInit.c:750]
```

**Comment by whummer** [comment]
Thanks for reporting @VandanaAwasthi and contributing the fix @mgagliardo . This change (#3530) is now available in the `latest` Docker image - please let us know if the problem persists. Thanks!

**Comment by jlosornogil** [comment]
@whummer the commits for this fix https://github.com/localstack/localstack/pull/3530 have been deleted from version [v0.12.16](https://github.com/localstack/localstack/commits/v0.12.16/localstack/services/awslambda/lambda_executors.py). So this problem is reproducible again in the default branch.
