### ISSUE TITLE
Lambda fallback can't signal FunctionError

### ISSUE THREAD

**Issue by jscheid** [localstack/localstack#3485]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

`forward_to_fallback_url` returns the binary POST response body, and only that, in https://github.com/localstack/localstack/blob/2c740f0949b72a2097edbcb1df07a3ff52aa1405/localstack/services/awslambda/lambda_api.py#L886 -- even if the response specifies `Content-Type: application/json`.

The binary body is then passed to `_create_response`, which never sets `details['FunctionError']` unless `result` is a `Response` or a `dict`, but it isn't. The response headers don't get passed through either.

## Expected behavior

A JSON response from the fallback is passed as a `dict` to `_create_response`, or the response headers get passed through. Either of the two would allow signalling a function error.

## Actual behavior

There's no way to set `X-Amz-Function-Error` in the final response headers, and therefore no way to signal a function error from the fallback.

# Steps to reproduce

Happy to provide these if needed, but I think it's fairly easy to see from the code that this isn't possible at the moment.

---

On a side note, the only reason we're using the fallback mechanism is because we couldn't find another way to integrate [Lambda containers](https://aws.amazon.com/blogs/aws/new-for-aws-lambda-container-image-support/) into our Localstack. I didn't see this mentioned in the roadmap -- are there any plans for supporting this use case eventually?

**Comment by jscheid** [comment]
Using this as a (crude) workaround:

```Dockerfile
FROM localstack/localstack

RUN sed -i 's/return response\.content/return response.json()/' \
  /opt/code/localstack/localstack/services/awslambda/lambda_api.py
```

**Comment by whummer** [comment]
Thanks for reporting @jscheid . This issue should be fixed in #3533 - can you please pull the `latest` Docker image and give it another try? Please report here if the problem persists. Thanks

**Comment by jscheid** [comment]
Thank you, I actually have a whole batch of other improvements related to the fallback. I'll try and create issues/PRs for those over the next few days.

**Comment by whummer** [comment]
Sounds great, thanks @jscheid . We'll be very happy to accept PRs, and work on any improvements related to Lambda fallback. 👍 Thanks for your help.

(On a side note, Lambda container images are available in the Pro version, in case you'd like to give that a try.)

**Comment by jscheid** [comment]
Good to know, thanks for the heads up. It looks like that pro feature was added only [recently](https://github.com/localstack/localstack/commit/c0f515bc3c86f2e3004bede58c4dc9aaf80c3dab#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R79)? Just trying to get a sense for how battle tested it is.
