### ISSUE TITLE
Regression with SNS -> SQS messages when using elasticmq backend

### ISSUE THREAD

**Issue by kgston** [localstack/localstack#3486]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

SNS is unable to forward the message to SQS (non fifo queue) when using the `elasticmq` backend and fails with the following log
```
2021-01-19T09:31:50:WARNING:localstack.services.sns.sns_listener: Unable to forward SNS message to SQS: An error occurred (InvalidParameterValue) when calling the SendMessage operation: Value for parameter MessageGroupId is invalid. The request include parameter that is not valid for this queue type Traceback (most recent call last):

File "/opt/code/localstack/localstack/services/sns/sns_listener.py", line 297, in message_to_subscribers

sqs_client.send_message(

File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 357, in _api_call

return self._make_api_call(operation_name, kwargs)

File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 676, in _make_api_call

raise error_class(parsed_response, operation_name)

botocore.exceptions.ClientError: An error occurred (InvalidParameterValue) when calling the SendMessage operation: Value for parameter MessageGroupId is invalid. The request include parameter that is not valid for this queue type
```
This is likely a regression due to #3435. Tested with the default backend on `0.12.5` and it works as expected. Also works with `elasticmq` backend on `0.12.4`

## Expected behavior

Same behavior with the `elasticmq` backend as with the default backend.

## Actual behavior

Fails on `elasticmq` backend, no SQS message received when SNS message is sent.

# Steps to reproduce

## Command used to start LocalStack

```yaml
  localstack:
    image: localstack/localstack:0.12.5
    ports:
      - 4566:4566
    environment:
      - AWS_DEFAULT_REGION=ap-northeast-1
      - SERVICES=sns,sqs
      - SQS_PROVIDER=elasticmq
```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
N.A.

**Comment by poulhenriksen** [comment]
We have the same problem, and we need to use elasticmq because performance is extremely poor when using moto, which is reported here: https://github.com/localstack/localstack/issues/2074

We are currently stuck on 11.2 because of these issues.

**Comment by nkuik** [comment]
The fix made here will hopefully take care of this issue when released.

**Comment by whummer** [comment]
Thanks for providing the fix @nkuik . This should now be available in the `latest` Docker image @kgston @poulhenriksen ,  we'll create a new tagged release shortly. Please let us know if the problem persists. Thanks
