### ISSUE TITLE
Fails in getting shard iterator for kinesis stream

### ISSUE THREAD

**Issue by aahdahl** [localstack/localstack#3488]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

I am trying to get the records from a stream with the aws cli, however, the command `aws kinesis get-records ...` returns an error when running locally.

## Expected behavior

the following is returned from `aws kinesis get-rercords`:
`
{
    "Records": [
        {
            "SequenceNumber": "123",
            "ApproximateArrivalTimestamp": "2021-01-19T12:00:11.590000+01:00",
            "Data": "SGVsbG8gd29ybGQ=",
            "PartitionKey": "1"
        }
    ],
    "NextShardIterator": "abc",
    "MillisBehindLatest": 0
}
` 

## Actual behavior

Returned value is:
`year 53022 is out of range`

# Steps to reproduce

## Command used to start LocalStack

Starting localstack with kinesis enabled

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

Create stream:
`awslocal kinesis create-stream --stream-name test --shard-count 1`

Add record:
`awslocal kinesis put-record --stream-name test --partition-key 1 --data SGVsbG8gd29ybGQ=`

Read records from start of stream:
`awslocal kinesis get-records --shard-iterator $(awslocal kinesis get-shard-iterator --stream-name test --shard-id shardId-000000000000 --shard-iterator-type AT_SEQUENCE_NUMBER --starting-sequence-number $(awslocal kinesis describe-stream --stream-name test --query 'StreamDescription.Shards[0].SequenceNumberRange.StartingSequenceNumber' --output text) --query ShardIterator --output text)`

**Comment by upanshu21** [comment]
I faced the same issue. I think this is the problem with the latest localstack version. It was running fine 15 days back but as soon as i pulled the latest image it gave me this message.
```
year 53022 is out of range
```
Again, I am using latest docker image to fireup the localstack kinesis. One thing you can do is pull the previous localstack docker image, make a docker-compose and test it with the aws cli. It should work.

**Comment by aahdahl** [comment]
gonna test this out and let you know @upanshu21 ! thx for the tip!

**Comment by aahdahl** [comment]
fyi @irahulranjan, @upanshu21: issue seems to have been introduced somewhere between 0.12.2 and 0.12.3. 0.12.2 works fine for me.

**Comment by whummer** [comment]
Thanks for reporting @aahdahl @upanshu21 . This should be fixed in #3515 - can you please pull the `latest` Docker image and give it another try? Please report here if the problem persists. Thanks

**Comment by upanshu21** [comment]
> Thanks for reporting @aahdahl @upanshu21 . This should be fixed in #3515 - can you please pull the `latest` Docker image and give it another try? Please report here if the problem persists. Thanks

will do !

**Comment by aahdahl** [comment]
> Thanks for reporting @aahdahl @upanshu21 . This should be fixed in #3515 - can you please pull the `latest` Docker image and give it another try? Please report here if the problem persists. Thanks

Tested the latest image now, i am getting the same issue still:
`year 53066 is out of range`
