### ISSUE TITLE
Cognito IDP: User signout operations return 500 internal server error

### ISSUE THREAD

**Issue by Caracal2021** [localstack/localstack#3489]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

I'm running Localstack in a Docker container and using the cognito-idp service. I can create a user pool; add a user; confirm signup; set a password; call initiate-auth to get an access token; these and other commands all work. But when I try to call a user signout operation, it fails with a nondescript 500 error.
Ideally I want to be using [admin-user-global-sign-out](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/cognito-idp/admin-user-global-sign-out.html), but I also tried with [global-sign-out](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/cognito-idp/global-sign-out.html) and both commands fail in the same way.

## Expected behavior

The command should successfully sign out the user, and return [no output](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/cognito-idp/admin-user-global-sign-out.html#output) - or if it fails, it should probably return a response explaining why.

## Actual behavior

The command fails with:

```
An error occurred (500) when calling the AdminUserGlobalSignOut operation (reached max retries: 4): <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
```

# Steps to reproduce

## Command used to start LocalStack

docker-compose

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

```
export COGNITO_POOL_ID=$(awslocal cognito-idp create-user-pool \
    --pool-name testuserpool \
	--alias-attributes preferred_username | jq -r .UserPool.Id)

awslocal cognito-idp admin-create-user --user-pool-id $COGNITO_POOL_ID --username HelloWorld

awslocal cognito-idp admin-confirm-sign-up --user-pool-id $COGNITO_POOL_ID --username HelloWorld

awslocal cognito-idp admin-set-user-password --user-pool-id $COGNITO_POOL_ID --username HelloWorld --password b6Fo7Ans6e1Ys3D

awslocal cognito-idp admin-user-global-sign-out --user-pool-id $COGNITO_POOL_ID --username HelloWorld
```

I'm quite new to localstack, so if I'm doing something wrong please let me know!

**Comment by whummer** [comment]
Thanks for reporting this issue @Caracal2021 . This should be fixed in the meantime - can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists or if there are any other issues. Thanks for your help!

**Comment by Caracal2021** [comment]
Now working perfectly. Thanks a lot!
