### ISSUE TITLE
cloudwatch get-metric-data result datapoint Timestamp is not in appropriate format. (milliseconds part should not be present)

### ISSUE THREAD

**Issue by sahajavidya** [localstack/localstack#3492]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description
cloudwatch get-metric-data result datapoint Timestamp is not in appropriate format. (milliseconds part should not be present)

[root@xxxxxx]# aws --endpoint-url=http://localhost:5000 cloudwatch get-metric-data --region us-east-1 --cli-input-json file://metricqueries.json
{
    "MetricDataResults": [
        {
            "Id": "localstackRequest",
            "Label": "CPUUtilization Average",
            "Timestamps": [
                "2021-01-20T05:56:56.698552+00:00"
            ],
            "Values": [
                27.5
            ],
            "StatusCode": "Complete"
        }
    ]
}

...

## Expected behavior

Expected output:-

{
    "MetricDataResults": [
        {
            "Id": "localstackRequest",
            "Label": "CPUUtilization Average",
            "Timestamps": [
                "2021-01-20T05:56:56+00:00"
            ],
            "Values": [
                27.5
            ],
            "StatusCode": "Complete"
        }
    ]
}
...

## Actual behavior

...

# Steps to reproduce

1) metricqueries.json file content
{
    "MetricDataQueries": [
        {
            "Id": "localstackRequest",
            "MetricStat": {
                "Metric": {
                    "Namespace": "AWS/EC2",
                    "MetricName": "CPUUtilization",
                    "Dimensions": [
                        {
                        "Name": "InstanceId",
                        "Value": "i-51511f92c6c4e32fc"
                        }
                    ]
                },
                "Period": 600,
                "Stat": "Average"
            },
            "ReturnData": true
        }
    ],
    "StartTime": "2021-01-20T04:00:00Z",
    "EndTime": "2021-01-21T04:00:00Z",
    "ScanBy": "TimestampDescending"
}

2) put metric data for MetricName: CPUUtilization
[root@xxxxx]# aws --endpoint-url=http://localstack:5000 cloudwatch put-metric-data --namespace AWS/EC2 --metric-data '[{ "MetricName": "CPUUtilization", "Dimensions": [ { "Name": "InstanceId", "Value": "i-51511f92c6c4e32fc" } ], "Value": 28, "Unit": "Percent" }]'

3) get-metric-data for metric - CPUUtilization
[root@xxxxxx]# aws --endpoint-url=http://localhost:5000 cloudwatch get-metric-data --region us-east-1 --cli-input-json file://metricqueries.json
{
    "MetricDataResults": [
        {
            "Id": "localstackRequest",
            "Label": "CPUUtilization Average",
            "Timestamps": [
                "2021-01-20T05:56:56.698552+00:00"
            ],
            "Values": [
                27.5
            ],
            "StatusCode": "Complete"
        }
    ]
}

We can see the value of Timestamps "2021-01-20T05:56:56.698552+00:00" include milliseconds. But if we do the same call with Actual AWS server, that does not provide the milliseconds part.
e.g. -  ( outoput from Actual AWS server )
[root@xxxxxx]# aws cloudwatch get-metric-data --region us-east-1 --cli-input-json file://metricqueries.json
{
    "MetricDataResults": [
        {
            "Id": "localstackRequest",
            "Label": "CPUUtilization",
            "Timestamps": [
                "2021-01-20T05:40:00+00:00"
            ],
            "Values": [
                0.7295660831712709
            ],
            "StatusCode": "Complete"
        }
    ],
    "Messages": []
}

## Command used to start LocalStack

...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

...

**Comment by whummer** [comment]
Thanks for reporting @sahajavidya . This should be fixed in #3497 - can you please pull the `latest` Docker image and give it another try? Please report here if the problem persists. Thanks

**Comment by sahajavidya** [comment]
Thanks working as expected.
