### ISSUE TITLE
Localstack not supporting multiple datapoints for get-metric-data API.

### ISSUE THREAD

**Issue by sahajavidya** [localstack/localstack#3493]
# Type of request: This is a ...

[x] bug report
[x] feature request

# Detailed description

Does localstack support multiple datapoints in get-metric-data Result.
Let say we are asking for metrics data for 1 hours in 10 minutes period.
Then suppose to get 6 datapoints for ec2 instance if available.

For example the output of get-metric-data will be something like this.

[root@xxxxxx]# aws cloudwatch get-metric-data --region us-east-1 --cli-input-json file://metricqueries.json
{
    "MetricDataResults": [
        {
            "Id": "localstackRequest",
            "Label": "CPUUtilization",
            "Timestamps": [
                "2021-01-20T04:50:00+00:00",
                "2021-01-20T04:40:00+00:00",
                "2021-01-20T04:30:00+00:00",
                "2021-01-20T04:20:00+00:00",
                "2021-01-20T04:10:00+00:00",
                "2021-01-20T04:00:00+00:00"
            ],
            "Values": [
                0.7331342039446354,
                0.7176345281077683,
                0.7164304899538062,
                0.7645920163017453,
                0.7498842271001853,
                0.7509308141150808
            ],
            "StatusCode": "Complete"
        }
    ],
    "Messages": []
}

**localstack always returning only one datapoint.**
...

## Expected behavior

...

## Actual behavior

...

# Steps to reproduce

1) Create a corntab job to push metric data to localstack for every 5 mins for one hours for MetricName: CPUUtilization
2) Then do get-metric-data for metric - CPUUtilization  with the following configuration:

metricqueries.json file content.

{
    "MetricDataQueries": [
        {
            "Id": "localstackRequest",
            "MetricStat": {
                "Metric": {
                    "Namespace": "AWS/EC2",
                    "MetricName": "CPUUtilization",
                    "Dimensions": [
                        {
                        "Name": "InstanceId",
                        "Value": "i-09603b2a8a61d831f"
                        }
                    ]
                },
                **"Period": 600,**
                "Stat": "Average"
            },
            "ReturnData": true
        }
    ],
    **"StartTime": "2021-01-20T04:00:00Z",
    "EndTime": "2021-01-20T05:00:00Z",**
    "ScanBy": "TimestampDescending"
}

**Asking metric data for 1 hour in 10 minutes period.** 

[root@xxxxxx]# aws --endpoint-url=http://localhost:5000 cloudwatch get-metric-data --region us-east-1 --cli-input-json file://metricqueries.json

The output  is always with one datapoints as below instead for 6 datapoints value.

{
    "MetricDataResults": [
        {
            "Id": "localstackRequest",
            "Label": "CPUUtilization Average",
            **"Timestamps": [
                "2021-01-20T06:47:35.808726+00:00"
            ],
            "Values": [
                26.428571428571427
            ],**
            "StatusCode": "Complete"
        }
    ]
}

## Command used to start LocalStack

...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

...

**Comment by irahulranjan** [comment]
Hi @sahajavidya, This should be fixed in the latest version of localstack. Can you pull and give it a shot?
Thanks!
