### ISSUE TITLE
no attribute 'error_response_throughput' when using dynamodb-error-probability

### ISSUE THREAD

**Issue by dradetsky** [localstack/localstack#3502]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

When running with dynamodb errors set to 1.0 and performing basically any kind of request, I see the following in the console: 

```
localstack_main | 2021-01-22T22:14:37:WARNING:localstack.utils.server.http2_server: Error in proxy handler for request POST http://localhost:4566/: 'ProxyListenerDynamoDB' object has no attribute 'error_response_throughput' Traceback (most recent call last):
localstack_main |   File "/opt/code/localstack/localstack/utils/server/http2_server.py", line 107, in index
localstack_main |     raise result
localstack_main |   File "/opt/code/localstack/localstack/utils/bootstrap.py", line 581, in run
localstack_main |     result = self.func(self.params)
localstack_main |   File "/opt/code/localstack/localstack/utils/async_utils.py", line 28, in _run
localstack_main |     return fn(*args, **kwargs)
localstack_main |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 605, in handler
localstack_main |     response = modify_and_forward(method=method, path=path_with_params, data_bytes=data, headers=headers,
localstack_main |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 373, in modify_and_forward
localstack_main |     listener_result = listener.forward_request(method=method,
localstack_main |   File "/opt/code/localstack/localstack/services/edge.py", line 105, in forward_request
localstack_main |     return do_forward_request(api, method, path, data, headers, port=port)
localstack_main |   File "/opt/code/localstack/localstack/services/edge.py", line 116, in do_forward_request
localstack_main |     result = do_forward_request_inmem(api, method, path, data, headers, port=port)
localstack_main |   File "/opt/code/localstack/localstack/services/edge.py", line 136, in do_forward_request_inmem
localstack_main |     response = modify_and_forward(method=method, path=path, data_bytes=data, headers=headers,
localstack_main |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 373, in modify_and_forward
localstack_main |     listener_result = listener.forward_request(method=method,
localstack_main |   File "/opt/code/localstack/localstack/services/dynamodb/dynamodb_listener.py", line 97, in forward_request
localstack_main |     return self.error_response_throughput()
localstack_main | AttributeError: 'ProxyListenerDynamoDB' object has no attribute 'error_response_throughput'
```

which seems like a mistake. It looks like we get one of those for every request.

## Expected behavior

I wouldn't expect the console to print anything

# Steps to reproduce

I made #3501 to simplify reproduction. Basically just pull that, pull the latest docker image, run `./example/run.sh`.

## Command used to start LocalStack

`docker-compose up`

**Comment by mgagliardo** [comment]
Hello @dradetsky, thanks for reporting this. 

So it looks there's a malformed call to the function `error_response_throughput` in the `dynamodb_listener.py`, I have placed a PR in place -> https://github.com/localstack/localstack/pull/3504

A couple of things to bear in mind (just in case, don't know if you were looking for):
1. I could not find a command to put a YAML, so I've used two JSONs that look exactly the same (but in JSON format, which basically is the same as YAML):
`table.json`
```
{
        "AttributeDefinitions": [
            {
                "AttributeName": "pk",
                "AttributeType": "S"
            },
            {
                "AttributeName": "sk",
                "AttributeType": "S"
            }
        ],
        "TableName": "test-table",
        "KeySchema": [
            {
                "AttributeName": "pk",
                "KeyType": "HASH"
            },
            {
                "AttributeName": "sk",
                "KeyType": "RANGE"
            }
        ],
        "ProvisionedThroughput": {
            "ReadCapacityUnits": 300,
            "WriteCapacityUnits": 300
        }
}
```

`get-item.json`:
```
{
    "TableName": "test-table",
    "Key": {
        "pk": {
            "S": "oh"
        },
        "sk": {
            "S": "hai"
        }
    }
}
```

2. Keep in mind if you put a very high value to `DYNAMODB_ERROR_PROBABILITY` like `1.0` localstack will for sure trigger a rate limit error as internally it uses random.random() which can't reach `1.0`:
```
DYNAMODB_ERROR_PROBABILITY: 1.0
rand: 0.831400480511171
DYNAMODB_ERROR_PROBABILITY: 1.0
rand: 0.28173143445489024
DYNAMODB_ERROR_PROBABILITY: 1.0
rand: 0.9397417695135991
DYNAMODB_ERROR_PROBABILITY: 1.0
rand: 0.5589624121894363
DYNAMODB_ERROR_PROBABILITY: 1.0
rand: 0.42649410518105657
DYNAMODB_ERROR_PROBABILITY: 1.0
rand: 0.7960012889753003
DYNAMODB_ERROR_PROBABILITY: 1.0
rand: 0.9802769601847469
DYNAMODB_ERROR_PROBABILITY: 1.0
rand: 0.9295909174569051
DYNAMODB_ERROR_PROBABILITY: 1.0
rand: 0.3067728899727761
DYNAMODB_ERROR_PROBABILITY: 1.0
rand: 0.27730150415430743
```

```
$ awslocal dynamodb get-item --cli-input-json file://get-item.json 

An error occurred (ProvisionedThroughputExceededException) when calling the GetItem operation (reached max retries: 9): The level of configured provisioned throughput for the table was exceeded. Consider increasing your provisioning level with the UpdateTable API
```

3. (And last) I strongly recommend to not push PRs to the repo, either put the config you used here for better debugging or use `gist` for that.

Anyways, thanks for reporting this! The PR should fix this issue.

**Comment by dradetsky** [comment]
@mgagliardo 

> I could not find a command to put a YAML,

The command was included in `example/run.sh`:

```
aws --endpoint http://localhost:4566 dynamodb create-table --cli-input-yaml file://example/table.yaml
```

If that didn't work for you, you may still be using the aws cli v1, whereas they're now recommending everyone upgrade to v2. I have

```
% aws --version
aws-cli/2.0.60 Python/3.9.1 Linux/5.9.14-arch1-1 source/x86_64.arch
```

> Keep in mind if you put a very high value to DYNAMODB_ERROR_PROBABILITY like 1.0 localstack will for sure trigger a rate limit error 

Of course, this was actually my intention. I'm working on something to generate metrics for how often my dynamodb requests error or retry, so the first step was to generate some errors. As I pointed out, it looked like every request contained that python exception, including all the automatic retries by the sdk, so it probably wasn't related to there being an unretryable error.

> I strongly recommend to not push PRs to the repo

I assume you mean as a way to share the config for replicating the issue. Why not? I mean, I can put things in gists or whatever if that's more helpful, but what's the problem with putting it in a PR?

**Comment by mgagliardo** [comment]
Hey @dradetsky, you are right, I was using an older version of the awscli but the result is exactly the same, whether it's a JSON or a YAML file (which well, in the end is a subset of JSON).

Talking about PRs, they are usually intended for fixes like bugs, improvements or extensions in the code, basically putting a PR also hits the CI which is a basically a queue that tests all the code in TravisCI. If you put a PR for an example code (and not a gist, or the code here in the issue or a zip - or whatever, you get my point -) other PRs in place that are actual fixes will get lagged behind as we will not be testing anything. It is a consideration and not mandatory, but it helps everyone :) .

In any case, this should be fixed once https://github.com/localstack/localstack/pull/3504 gets merged.

Cheers!
