### ISSUE TITLE
localstack not able to handle multiple ec2 get-metric-data request.

### ISSUE THREAD

**Issue by sahajavidya** [localstack/localstack#3507]
# Type of request: This is a ...

[x] bug report
[x] feature request

# Detailed description
We have created around 500 ec2 instance to do load testing for get-metric-data request.
if our application is sending one request at a time then local stack is responding but if making multiple get-metric-data request (even sending 2-3 request in parallel) local stack is not able to respond or taking very long time.
...

## Expected behavior

Is the localstack is meant for load testing?
...

## Actual behavior

...

# Steps to reproduce

## Command used to start LocalStack

...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

...

**Comment by mgagliardo** [comment]
Hello @sahajavidya, if I understood what you mean is to do loadtesting on localstack?

If that is the case, I would say no. If you read our description: 
```
LocalStack provides an easy-to-use test/mocking framework for developing Cloud applications. It spins up a testing environment on your local machine that provides the same functionality and APIs as the real AWS cloud environment. 
```

But besides that, the goal of Load Testing is to improve performance bottlenecks and to ensure stability and smooth functioning of software application before deployment, localstack is meant to work on your own machine (or any other machine) as a single deployed instance and not as a `cloud`. 

If you are trying to do Load Testing on EC2 instances to see how `get-metric-data` behaves you I guess you should go for the official AWS API as you:

1. Get the real experience of having EC2 instances deployed along with your application.
2. Get actual metrics from Cloudwatch.
3. See how the instance types/sizes along with the network schema you have behaves.
4. Get actual metrics from your application.

Does this answer your question?

Thanks!
