### ISSUE TITLE
Cloudwatch: Add validation API

### ISSUE THREAD

**Issue by jakobbraun** [localstack/localstack#3508]
Hi,

we would like to use localstack to test our CloudWatch connector.
For that, it is required to check if the data was reported correctly (no duplicates, no points missing).

Using the official CloudWatch API we can, however not test this, since it only gives eventual consistency and aggregates past data.
Since the aim of localstack is to simulate this API probably it will also not be possible to test it using localstack.

What would really help here would be a non-AWS standardized API that for example gives access to all reported metrics.
Is such or a similar approach for validating the behavior planned or possible?

**Comment by whummer** [comment]
Thanks for reporting @jakobbraun . A backdoor API to receive the raw CW metrics has been added in #3535. Is that what you had in mind?

Example:
```
$ curl http://localhost:4566/cloudwatch/metrics/raw
{'metrics': [{'ns': 'some/thing', 'n': 'someMetric', 'v': 23.0, 't': '2021-01-30T18:35:30.132Z', 'd': []}, {'ns': 'some/thing', 'n': 'someMetric', 'v': 18.0, 't': '2021-01-30T18:35:30.160Z', 'd': []}, {'ns': 'ug/thing', 'n': 'ug', 'v': 23.0, 't': '2021-01-30T18:35:30.186Z', 'd': []}]}
```
Hope that helps - please let us know if anything else is missing.

**Comment by jakobbraun** [comment]
Thanks a lot! That was exactly what I had in mind. Can you give an estimation of when you will make the next release, and by that, I can use this feature?

**Comment by whummer** [comment]
Thanks @jakobbraun , the change is available in the `latest` Docker image, and we are preparing a new release `0.12.6` which will be available in the course of the day (today).

**Comment by jakobbraun** [comment]
cool! Thanks a lot for your quick replies!
