### ISSUE TITLE
localstack will restart pod when inject network delay chaos by Chaos Mesh

### ISSUE THREAD

**Issue by WangXiangUSTC** [localstack/localstack#3512]
# Type of request: This is a ...

- [x] bug report
- [ ] feature request

# Detailed description

1. Deploy K8s by Kind

refer to [Kind installation](https://kind.sigs.k8s.io/docs/user/quick-start/#installation)

2. Deploy localstack in K8s by helm

```bash
helm repo add localstack-repo http://helm.localstack.cloud
helm upgrade --install localstack localstack-repo/localstack
```

and then run port forward:

```bash
kubectl port-forward svc/localstack 4566:4566
```

3. Create a dynamodb table by aws client
```bash
aws --endpoint-url=http://127.0.0.1:4566  dynamodb create-table --table-name test_table  --attribute-definitions AttributeName=first,AttributeType=S AttributeName=second,AttributeType=N --key-schema AttributeName=first,KeyType=HASH AttributeName=second,KeyType=RANGE --provisioned-throughput ReadCapacityUnits=5,WriteCapacityUnits=5
```

Then check it:
```bash
aws --endpoint-url=http://localhost:4566  dynamodb describe-table --table-name test_table
```

4. Use [Chaos Mesh](https://chaos-mesh.org/) to inject network delay to localstack pod

Deploy Chaos Mesh:

```bash
helm repo add chaos-mesh https://charts.chaos-mesh.org
curl -sSL https://mirrors.chaos-mesh.org/v1.1.1/crd.yaml | kubectl apply -f -
kubectl create ns chaos-testing
helm install chaos-mesh chaos-mesh/chaos-mesh --namespace=chaos-testing
```

Refer to [Installation Chaos Mesh](https://chaos-mesh.org/docs/user_guides/installation) for more details.

The chaos configure is as below:

```yaml
apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-delay
  namespace: default
spec:
  action: delay # the specific chaos action to inject
  mode: all
  selector:
    namespaces:
      - default
  delay:
    latency: "5s"
  duration: "9s"
  scheduler:
    cron: "@every 10s"
  direction: to
```
this will increase the network latency by more than 5 seconds.

save the config to `network_chaos.yaml` and run command below to create chaos experiment:

```bash
kubectl apply -f network_chaos.yaml
```

5. Use aws client to describe the table

run command:
```bash
aws --endpoint-url=http://localhost:4566  dynamodb describe-table --table-name test_table
```

## Expected behavior

Can get the table description successful

## Actual behavior

get error:
```log
An error occurred (ResourceNotFoundException) when calling the DescribeTable operation: Cannot do operations on a non-existent table
```

and it seems that the localstack Pod is restarted, and **the table does not exist after the restart**.

```bash
kubectl describe pod localstack-78c5774d85-p7pz2
```
```
Events:
  Type     Reason     Age                  From                         Message
  ----     ------     ----                 ----                         -------
  Normal   Scheduled  <unknown>            default-scheduler            Successfully assigned default/localstack-78c5774d85-p7pz2 to kind-control-plane
  Warning  Unhealthy  53s (x3 over 73s)    kubelet, kind-control-plane  Liveness probe failed: Get http://10.244.0.44:4566/health: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
  Normal   Killing    53s                  kubelet, kind-control-plane  Container localstack failed liveness probe, will be restarted
  Warning  Unhealthy  29s (x6 over 79s)    kubelet, kind-control-plane  Readiness probe failed: Get http://10.244.0.44:4566/health: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
  Normal   Pulled     23s (x2 over 5m37s)  kubelet, kind-control-plane  Container image "localstack/localstack:latest" already present on machine
  Normal   Started    22s (x2 over 5m37s)  kubelet, kind-control-plane  Started container localstack
  Normal   Created    22s (x2 over 5m37s)  kubelet, kind-control-plane  Created container localstack
  Warning  Unhealthy  20s (x2 over 5m30s)  kubelet, kind-control-plane  Readiness probe failed: Get http://10.244.0.44:4566/health: dial tcp 10.244.0.44:4566: connect: connection refused
  Warning  Unhealthy  14s (x2 over 5m33s)  kubelet, kind-control-plane  Liveness probe failed: Get http://10.244.0.44:4566/health: dial tcp 10.244.0.44:4566: connect: connection refused
```

**Comment by whummer** [comment]
Hi @WangXiangUSTC, thanks for your efforts working on the integration of LocalStack with Chaos Mesh! 

In terms of persistence: resources are by default only stored in-memory, but you can enable persistence by using the `DATA_DIR` environment variable to point to a folder in a persistent volume. Do you have some more insights as to why the pod is restarting as soon as you start the chaos experiment - any error logs reported from the LocalStack containers..? Thanks

**Comment by WangXiangUSTC** [comment]
> Hi @WangXiangUSTC, thanks for your efforts working on the integration of LocalStack with Chaos Mesh!
> 
> In terms of persistence: resources are by default only stored in-memory, but you can enable persistence by using the `DATA_DIR` environment variable to point to a folder in a persistent volume. Do you have some more insights as to why the pod is restarting as soon as you start the chaos experiment - any error logs reported from the LocalStack containers..? Thanks

Thanks! I will try the `DATA_DIR` environment variable.

And I run `kubectl logs -f {localstack-pod-name}` to get the pod's log, but can not find any error log, and then this command exist. Then I can see the pod restart. Maybe the `events` `Liveness probe failed: Get http://10.244.0.44:4566/health: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)` in the pod description can help.
