### ISSUE TITLE
Allowing s3 uploads when bucket is in subdomain

### ISSUE THREAD

**Issue by HoneyryderChuck** [localstack/localstack#3520]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

I'm currently experiencing the following bug:

```
xml.parsers.expat.ExpatError: syntax error: line 1, column 0
```

when uploading a file to localstack's S3, after being able to create a bucket using `awslocal mb`  cli command. I've found many references to this sort of bug, and they all seem to relate with the definition of the endpoint url for services, so I guess my issue has to do with it as well.

I'm using a docker-compose build, where localstack maps to the "aws" container,  and my script uses ruby's "aws-sdk-s3" gem, and the error happenns when I perform the following command:

```ruby
 s3_client = Aws::S3::Client.new(endpoint: "http://aws:4566", region: 'us-east-1', http_wire_trace: true, logger: Logger.new(STDERR)) # moar logs
object = s3_client.put_object(bucket: "test", key: "testimage", body: StringIO.new("bucketz"))
```

client-side backtrace is:

```
 "PUT /testimage HTTP/1.1\r\nContent-Type: \r\nAccept-Encoding: \r\nUser-Agent: aws-sdk-ruby3/3.111.2 ruby/3.0.0 x86_64-linux-musl aws-sdk-s3/1.87.0\r\nExpect: 100-continue\r\nContent-Md5: HVbaJ7NiGbk5o
U5+jrLqeA==\r\nHost: test.aws:4566\r\nX-Amz-Content-Sha256: a29e9871a693796ae6619303e870ad34e43edca0c92dccdcde4232c572a1f9fa\r\nContent-Length: 7\r\nX-Amz-Date: 20210127T140010Z\r\nAuthorization: AWS4-HMA
C-SHA256 Credential=test/20210127/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;user-agent;x-amz-content-sha256;x-amz-date, Signature=547c406fa20415ac40ed8ce2d5c4931a219e1fc7577f273ea25fc3a01a
0b0b2a\r\nAccept: */*\r\n\r\n"
-> "HTTP/1.1 100 Continue\r\n"
-> "date: Wed, 27 Jan 2021 14:00:10 GMT\r\n"
-> "server: hypercorn-h11\r\n"
-> "\r\n"
-> "HTTP/1.1 500 \r\n"
-> "content-type: text/html; charset=utf-8\r\n"
-> "content-length: 287\r\n"
-> "last-modified: Wed, 27 Jan 2021 14:00:10 GMT\r\n"
-> "x-amz-request-id: B01974FCEE3B7132\r\n"
-> "x-amz-id-2: MzRISOwyjmnupB01974FCEE3B71327/JypPGXLh0OVFGcJaaO3KW/hRAqKOpIEEp\r\n"
-> "access-control-allow-origin: *\r\n"
-> "access-control-allow-methods: HEAD,GET,PUT,POST,DELETE,OPTIONS,PATCH\r\n"
-> "access-control-allow-headers: authorization,content-type,content-length,content-md5,cache-control,x-amz-content-sha256,x-amz-date,x-amz-security-token,x-amz-user-agent,x-amz-target,x-amz-acl,x-amz-ver
sion-id,x-localstack-target,x-amz-tagging\r\n"
-> "access-control-expose-headers: x-amz-version-id\r\n"
-> "connection: close\r\n"
-> "date: Wed, 27 Jan 2021 14:00:10 GMT\r\n"
-> "server: hypercorn-h11\r\n"
-> "\r\n"
reading 287 bytes...
-> ""
-> "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 3.2 Final//EN\"><title>500 Internal Server Error</title><h1>Internal Server Error</h1><p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>\n"
read 287 bytes
Conn close
I, [2021-01-27T14:00:10.853432 #898]  INFO -- : [Aws::S3::Client 500 482.026996 3 retries] put_object(bucket:"test",key:"testimage",body:#<StringIO:0x00005571a4f9f8b0>) Aws::S3::Errors::Http500Error Aws::
S3::Errors::Http500Error
```

Listing buckets however works:

```ruby
 s3_client.list_buckets()
```

The problem seems to be related with the aws sdk "injecting" the bucket into the domain, i.e. it performs a request to "test.aws:4566", and I suspected that, if I could tell the sdk not to do that (seems I cannot, and AWS wants you to set the subdomain like that, as it's not a configurable option), this would work.

## Expected behavior

I expect localstack (or moto) to be able to accept file uploads to domains "descending" from the supported domain, i.e. if HOSTNAME is "aws", then "test.aws" should not be a problem.

## Actual behavior

Already described.

# Steps to reproduce

Set a simple docker-compose, with a localstack and ruby containers, where the localstack configures like:

```
aws:
    image: localstack/localstack
    environment:
      - SERVICES=s3
      - HOSTNAME=aws # also tried with test.aws here, no success
      - DEBUG=1
    ports:
      - 4566:4566
    volumes:
      - ./aws:/docker-entrypoint-initaws.d

# set a script to create the test bucket:
# awslocal s3 mb s3://test --region us-east-1
```

in the ruby image, install the "aws-dk-s3" gem and run the examples described above.

**Comment by mgagliardo** [comment]
Hi @HoneyryderChuck, this seems like a nice request but the thing is that the ruby SDK already contemplates this kind of issues, according to the [SDK docs](https://docs.aws.amazon.com/sdk-for-ruby/v2/api/Aws/S3/Client.html):

```
:force_path_style (Boolean) — default: false —

When set to true, the bucket name is always left in the request URI and never moved to the host as a sub-domain. See Plugins::S3BucketDns for more details.
```

For example:
```
require 'aws-sdk'

s3_client = Aws::S3::Client.new(
    endpoint: "http://aws:4566",
    region: 'us-east-1',
    force_path_style: true,
    http_wire_trace: true,
    logger: Logger.new(STDERR)
)
object = s3_client.put_object({
  bucket: "test",
  key: "testimage", 
  body: StringIO.new("bucketz")
})
```

And that is why your code is trying to use `test` as subdomain of the endpoint.

```
/ # ruby ruby.rb 
opening connection to aws:4566...
opened
<- "PUT /test/testimage HTTP/1.1\r\nContent-Type: \r\nAccept-Encoding: \r\nUser-Agent: aws-sdk-ruby3/3.111.2 ruby/2.6.6 x86_64-linux-musl aws-sdk-s3/1.87.0\r\nExpect: 100-continue\r\nContent-Md5: HVbaJ7NiGbk5oU5+jrLqeA==\r\nHost: aws:4566\r\nX-Amz-Date: 20210127T212752Z\r\nX-Amz-Content-Sha256: a29e9871a693796ae6619303e870ad34e43edca0c92dccdcde4232c572a1f9fa\r\nAuthorization: AWS4-HMAC-SHA256 Credential=potato/20210127/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;user-agent;x-amz-content-sha256;x-amz-date, Signature=4f43a0f0265d9c0c6cc1ee436a747fd575cec67ce8a306d34f1393bfec4a5001\r\nContent-Length: 7\r\nAccept: */*\r\n\r\n"
-> "HTTP/1.1 100 Continue\r\n"
-> "date: Wed, 27 Jan 2021 21:27:52 GMT\r\n"
-> "server: hypercorn-h11\r\n"
-> "\r\n"
-> "HTTP/1.1 200 \r\n"
-> "content-type: text/html; charset=utf-8\r\n"
-> "content-length: 0\r\n"
-> "etag: \"1d56da27b36219b939a14e7e8eb2ea78\"\r\n"
-> "last-modified: Wed, 27 Jan 2021 21:27:52 GMT\r\n"
-> "access-control-allow-origin: *\r\n"
-> "x-amz-request-id: 693ED69BCBCD47A9\r\n"
-> "x-amz-id-2: MzRISOwyjmnup693ED69BCBCD47A97/JypPGXLh0OVFGcJaaO3KW/hRAqKOpIEEp\r\n"
-> "access-control-allow-methods: HEAD,GET,PUT,POST,DELETE,OPTIONS,PATCH\r\n"
-> "access-control-allow-headers: authorization,content-type,content-length,content-md5,cache-control,x-amz-content-sha256,x-amz-date,x-amz-security-token,x-amz-user-agent,x-amz-target,x-amz-acl,x-amz-version-id,x-localstack-target,x-amz-tagging\r\n"
-> "access-control-expose-headers: x-amz-version-id\r\n"
-> "connection: close\r\n"
-> "date: Wed, 27 Jan 2021 21:27:52 GMT\r\n"
-> "server: hypercorn-h11\r\n"
-> "\r\n"
reading 0 bytes...
-> ""
read 0 bytes
Conn close
I, [2021-01-27T21:27:52.131579 #85]  INFO -- : [Aws::S3::Client 200 0.023797 0 retries] put_object(bucket:"test",key:"testimage",body:#<StringIO:0x00007f51ec16edc0>)  

---

$ awslocal s3 ls s3://test
2021-01-27 22:27:52          7 testimage
```

**Comment by HoneyryderChuck** [comment]
I thought I might be missing some option, thx for the tip. Still, given the impending depreciation of path style bucket URLs, shouldn't localstack deal with it regardless?

**Comment by mgagliardo** [comment]
Thing is with the code I've shown you (which I think is more or less the same you have) what is happening is that your container does not know what is the path because it can't resolve the DNS:

```
# ruby ruby.rb 
opening connection to test.aws:4566...
opening connection to test.aws:4566...
opening connection to test.aws:4566...
```

`aws` is defined by DNS or link between containers, but `test.aws` is not, it is a totally different behaviour with aws as `aws.amazon.com` is a public DNS.

**Comment by HoneyryderChuck** [comment]
Sure, but let's assume that it's possible (which it is, I'm setting, `- "aws:test.aws"` the `links` section of the ruby image, apologies for omitting that detail).

**Comment by mgagliardo** [comment]
Allright then, I'll work on a fix for that matter. Thanks for reporting it.

**Comment by HoneyryderChuck** [comment]
Thank you @mgagliardo . in the meantime, I'll use the path variant.

**Comment by HoneyryderChuck** [comment]
No need to prioritize it just for me though. Just found out that localstack doesn't support "private" buckets (using IAM/sigv4 access), which was what I need to test my open-source project, in the free version, and that's a bit of a deal-breaker for me 😭

**Comment by mgagliardo** [comment]
Hey @HoneyryderChuck, could you please send me the steps to reproduce this and what some output/debug logs? I need to know what are you trying and what's actually happening, the more input, the better. Cheers.

**Comment by HoneyryderChuck** [comment]
Sorry for the delay.

Project: https://gitlab.com/honeyryderchuck/httpx
Branch: https://gitlab.com/honeyryderchuck/httpx/-/tree/issue-108

How to reproduce:

1. build/run: `docker-compose -f docker-compose.yml -f docker-compose-ruby-3.0.yml run --entrypoint sh httpx`
2. setup shell/env: https://gitlab.com/honeyryderchuck/httpx/-/blob/issue-108/test/support/ci/build.sh#L5-32
3. run the test: `bundle exec ruby -Itest test/aws_sigv4_test.rb --name /get_object/`

The test [comments the part where an access to a private s3 object should trigger an error response](https://gitlab.com/honeyryderchuck/httpx/-/blob/issue-108/test/aws_sigv4_test.rb#L106-109).

Above it you'll see the "force path" param.
