### ISSUE TITLE
Path matching for API Gateway endpoints doesn't match behavior of AWS

### ISSUE THREAD

**Issue by kyle-hiller-nh** [localstack/localstack#3524]
[x] bug report
[ ] feature request

# Detailed description

We are using localstack 0.11.3. You can reproduce by creating an API gateway with two endpoints on it that use the same method, one of which has a variable in and the other with a static path part, like so:

`POST test/{testVar}`

and 

`POST test/create` 

and the make a request to `POST test/create` 

If you attempt to make a request to `POST test/create`, 

## Expected behavior

 In AWS, the request will be routed to the more specific route rather than the one with the variable.

## Actual behavior

the request will be routed to `POST test/{testVar}`.

**Comment by whummer** [comment]
Thanks for reporting @kyle-hiller-nh . This issue is potentially already fixed in #3677 - can you please pull the `latest` Docker image and give it another try? Please keep us posted how it goes. Thanks!
