### ISSUE TITLE
Support for AWS Xray trace header propagation in SQS / EMQ backend

### ISSUE THREAD

**Issue by kubawach** [localstack/localstack#3528]
# Type of request: This is a ...

[ ] bug report
[x] feature request

# Detailed description

Current localstack uses EMQ 0.15.7. This version does not support AWS XRay trace header propagation for SQS. Therefore value passed as a header to SQS won't be mapped back as a system attribute of a message, breaking trace propagation.

## Expected behavior
AWS XRay tracing header is supported and trace propagation works as expected (ie as with the real AWS SQS). This is supported by elasticmq since  0.15.8 (see https://github.com/softwaremill/elasticmq/pull/405)

## Actual behavior
AWS XRay tracing header not propagated.

# Steps to reproduce

## Command used to start LocalStack

NA

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

NA

**Comment by mgagliardo** [comment]
Hey @kubawach thanks for reporting this, I have created a PR, once it is merged you should be able to download the `latest` docker image and test this out. Cheers!

**Comment by whummer** [comment]
Thanks @kubawach and @mgagliardo . Just to confirm - in the latest version, we're using `moto`'s SQS implementation by default, and ElasticMQ is disabled by default (but can be enabled via `SQS_PROVIDER=elasticmq`, see [here](https://github.com/localstack/localstack/blob/a63dcd30c475d5c2cf035703e40783c4cb5e3e9e/localstack/services/install.py#L48)). 

Are you using a custom value for `elasticmq`, or simply the defauly? In any case, I think we should make this functionality available in LocalStack, regardless of the backend being used. Do you have a small example you can share with us to replicate this behavior? Thanks!

**Comment by kubawach** [comment]
@mgagliardo thanks for the fix, I appreciate it :)

@whummer yes, we're using custom SQS_PROVIDER value (`elasticmq`). OpenTelemetry Java instrumentation relies on the AWS XRay trace header propagation thru SQS produce / consume for trace context propagation. Example test: https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/aws-sdk/aws-sdk-1.11/javaagent/src/test/groovy/SqsTracingTest.groovy 
We've switched for this test from `localstack` to direct usage of `elasticmq`. Once there is a version of `localstack` with newer emq, we're going to switch back (the project uses `localstack` for a lot of tests, thanks for your great work by the way :) )
