### ISSUE TITLE
Stack logs

### ISSUE THREAD

**Issue by sabrehagen** [localstack/localstack#353]
It would be really useful to get the logs of the services in the stack, for example, REST API requests received (url, params), outgoing calls made, etc.

I can't see any documentation on how to enable this. Is it currently implemented?

Thanks

**Comment by garyorser-wf** [comment]
From my usage with a docker-compose file, I think all you need to do is set an environment variable.
e.g.   DEBUG=sqs

**Comment by whummer** [comment]
Correct, please set the `DEBUG=1` environment variable to enable debug logs.

**Comment by jtomaszewski** [comment]
It doesn't contain full url though, which makes it hard to debug region-related problems:

![image](https://user-images.githubusercontent.com/1862580/90778023-6b6a8380-e2fc-11ea-891e-c7df09785644.png)

Any idea if those logs can be somehow improved?

**Comment by ffMathy** [comment]
@whummer can you open this again? The URL alone doesn't provide a lot of context.
