### ISSUE TITLE
Unexpected protocol "email" for SNS subscription

### ISSUE THREAD

**Issue by BentCoder** [localstack/localstack#3532]
Hi,

Is there a way to find out what would be the **`--token`** for **`confirm-subscription`** command before publishing messages to the topic? Currently I can successfully publish before token confirmation stage and get a message ID but I see `WARNING:localstack.services.sns.sns_listener: Unexpected protocol "email" for SNS subscription` error in logs.

Thanks

Given that I have a topic

```json
$ aws --profile localstack --endpoint-url http://localhost:4566 sns create-topic --name newsletter
{
    "TopicArn": "arn:aws:sns:eu-west-1:000000000000:newsletter"
}
```

I then subscribe to it

```json
$ aws --profile localstack --endpoint-url http://localhost:4566 sns subscribe --topic-arn arn:aws:sns:eu-west-1:000000000000:newsletter --protocol email --notification-endpoint hello@example.com
{
    "SubscriptionArn": "arn:aws:sns:eu-west-1:000000000000:newsletter:72c11b69-ff81-4435-ae7d-e27b1602e3f8"
}
```

Finally the subscription looks like

```json
$ aws --profile localstack --endpoint-url http://localhost:4566 sns list-subscriptions
{
    "Subscriptions": [
        {
            "SubscriptionArn": "arn:aws:sns:eu-west-1:000000000000:newsletter:72c11b69-ff81-4435-ae7d-e27b1602e3f8",
            "Owner": "",
            "Protocol": "email",
            "Endpoint": "hello@example.com",
            "TopicArn": "arn:aws:sns:eu-west-1:000000000000:newsletter"
        }
    ]
}
```

**Comment by whummer** [comment]
Thanks for reporting @BentCoder . This should be fixed in #3571 - can you please pull the `latest` Docker image and give it another try? Please report here if the problem persists. Thanks
