### ISSUE TITLE
HTTP/2 proxy hangs when request contains Expect: 100-continue header

### ISSUE THREAD

**Issue by HoneyryderChuck** [localstack/localstack#3537]
[x] bug report

# Detailed description

Using the S3 service, when performing a "put object" request, it'll fail if the comms are done using HTTP/2. I've tried using both plaintext and TLS-enabled HTTP/1.1, and it seems to work. If I remove the `Expect` header, HTTP/2 works as well.

## Expected behavior

S3 upload request works.

## Actual behavior

Request hangs.

# Steps to reproduce

Running smth similar to [this http request using httpx](https://gitlab.com/honeyryderchuck/httpx/-/blob/issue-108/test/support/requests/plugins/aws_authentication.rb#L29-37) to a localstack instance, while setting/unsetting the `Expect` header. the plugin/aws-authentication is unnecessary to reproduce it, so you can just `HTTPX.with(...).put(....)`

**Comment by whummer** [comment]
Thanks for reporting @HoneyryderChuck , and apologies for the long delay. 

This appears to be fixed in the meantime:
```
$ awslocal s3 mb s3://bucket1
$ curl --http2 -XPUT -H 'Expect: 100-continue' -d 'test123' http://bucket1.s3.localhost.localstack.cloud:4566/test
$ curl --http2 -H 'Expect: 100-continue' http://bucket1.s3.localhost.localstack.cloud:4566/test
test123
```

Please let us know if the problem persists with the library you're using/developing. Thanks for your help!
