### ISSUE TITLE
S3 doesn't throw BucketAlreadyExistsException in case bucket already exists

### ISSUE THREAD

**Issue by peter-ponzel** [localstack/localstack#3540]
# Type of request: This is a ...

[x] bug report

# Detailed description

creating the same bucket more than once is working although it should not

## Expected behavior

throwing an BucketAlreadyExistsException

## Actual behavior

no exception thrown

# Steps to reproduce

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

```java
s3Client.createBucket(CreateBucketRequest.builder()
            .bucket("foobar")
            .build());

s3Client.createBucket(CreateBucketRequest.builder()
            .bucket("foobar")
            .build());
```

Thank you,
Peter

**Comment by macnev2013** [comment]
Thanks for reporting, @peter-ponzel. 
The behavior you are seeing is similar to real AWS. While creating a bucket in the default region, it does not throw an exception if the bucket exists. Thanks.

**Comment by whummer** [comment]
Thanks @peter-ponzel @macnev2013 . This should be the correct behavior, and is now also covered by a small integration test via #4082 . Thanks!
