### ISSUE TITLE
Add ability to specify valid SES addresses

### ISSUE THREAD

**Issue by nirvdrum** [localstack/localstack#3550]
# Type of request: This is a ...

[x] bug report
[x] feature request

# Detailed description

I guess depending on how you look at this, it's either a bug report or a feature request. As it stands, I think every email relayed through localstack's SES support will fail with some variation of:

```
Aws::SES::Errors::MessageRejected: Did not have authority to send from email support@localhost
```

If it were just a warning, that'd be acceptable, but it also returns an HTTP 400 error, which causes AWS's clients to raise an exception. The error stems from email validation performed in Moto:

https://github.com/spulec/moto/blob/4ce936a2842434779bca71ec465eb12478e2e508/moto/ses/models.py#L134-L140

I think localstack either needs to provide a way to configure the valid address list or should override the relevant method in Moto to treat all addresses as valid.

## Expected behavior

SES via localstack should mock sending emails without error.

## Actual behavior

Emails sent to localstack's SES always fail because the valid address list used by Moto's validation is always empty.

# Steps to reproduce

* Enable SES in localstack
* Connect to localstack's SES endpoint from an AWS client library
* Call `send_raw_email` on the client

## Command used to start LocalStack

I'm starting localstack from Docker using the _localstack/localstack_ image's standard entry point. I have the following env vars set:

```
SERVICES=s3,ses
DEBUG=1
DATA_DIR=/tmp/localstack/data
EDGE_PORT=7004
LS_LOG=debug
```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

I'm using the _aws-sdk-rails_ gem in a Ruby project. The client call is:

https://github.com/aws/aws-sdk-rails/blob/4318556673e68e2bb83cf6c54f792f31f00a1568/lib/aws/rails/mailer.rb#L27-L39

**Comment by irahulranjan** [comment]
Hi @nirvdrum,
You will have to verify the email address before using it to send the message. Sample CLI commands:
```
$awslocal ses verify-email-identity --email-address support@localhost
$awslocal ses send-email --from support@localhost --destination file://destination.json --message file://message.json
{
    "MessageId": "hgtktqvfbibktoif-boeivlzb-yddl-upsi-eqay-cybohxeyruzw-komqfj"
}
```

**Comment by dheerajkulakarni** [comment]
Hey @nirvdrum, this is how I solved this issue, all the scripts in this directly **/docker-entrypoint-initaws.d/** will get executed after the localstack service comes up. So I have written a script with the command to verify the email address and mounted it in that directory which helped me to make local stack SES up with some pre-verified emails.

**Comment by nirvdrum** [comment]
Thanks for the information. I didn't see anything in the localstack docs and the Moto docs indicated one would need to override the verification method. We don't need to run this operation for our actual AWS environment either, so it never occurred to me to invoke some additional commands.

I still think it'd be much nicer if there were just an env var to set with SES valid addresses and the Docker image could just process them when the container is started. But if that's out of scope for the project, documenting the process would be fine as well.

**Comment by irahulranjan** [comment]
Please refer to the following: https://docs.aws.amazon.com/ses/latest/DeveloperGuide/verify-domains.html
It states that AWS requires you to verify a domain or an email address to send mail using that domain/email address.

**Comment by whummer** [comment]
Thanks for reporting @nirvdrum and providing solutions @dheerajkulakarni @irahulranjan . 

> We don't need to run this operation for our actual AWS environment either, so it never occurred to me to invoke some additional commands.

@nirvdrum can you please confirm whether the behavior we have on LocalStack is correct - are you seeing a different behavior on real AWS? It seems that indeed on AWS email addresses also need to be validated (either by visiting a validation link that is sent to the email, or by using the `VerifyEmailIdentity` API). Please let us know if you're observing a different behavior. Thanks

**Comment by nirvdrum** [comment]
I'm sorry. I thought I replied to this. But, we had verified our domain with SES using the AWS console as a one-off process. Consequently, we had no code for that in our Docker bootstrap. I no longer work at the company that was making use of _localstack_. It sounds like it's working as designed and usability concerns were just use error, so I'll close this out.
