### ISSUE TITLE
S3 GET request returns internal server error for non-existing key when Range header is passed

### ISSUE THREAD

**Issue by bezsias** [localstack/localstack#3555]
# Type of request: This is a ...

[ x] bug report
[ ] feature request

# Detailed description

Get request for non-existing key fails with HTTP status 500 when `Range` header is specified. Version 0.12.6.

## Expected behavior

Return 404 response with `NoSuchKey` error code.

## Actual behavior

Returns 500, internal error.

# Steps to reproduce

## Command used to start LocalStack

`docker-compose up`

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

`awslocal s3api create-bucket --bucket mybucket`
` curl -v -H "Range: bytes=0-1024" http://localhost:4566/mybucket/nosuch.key`

**Comment by whummer** [comment]
Thanks for reporting @bezsias . This should be fixed in #3567 - can you please pull the `latest` Docker image and give it another try? Please report here if the problem persists. Thanks
