### ISSUE TITLE
Not able to access internet when hitting api of another container using localstack 12.5 lambda

### ISSUE THREAD

**Issue by tarunsingh2789** [localstack/localstack#3556]
# Type of request: This is a ...

[ ] bug report

# Detailed description

I am not able to access internet if I am hitting api of other docker container(running on port-9090 ) inside localstack(running on 12.5,port 4566) lambda handler function

## Expected behavior

{ "Key" : " value" }

## Actual behavior

ConnectionError","errorMessage":"HTTPConnectionPool(host='localhost', port=9090): Max retries exceeded with url: Caused by NewConnectionError('\u003curllib3.connection.HTTPConnection object at 0x7ff8185c8ad0\u003e: Failed to establish a new connection:

# Steps to reproduce
Localstack 12.5 running in 4566
My project code running in 9090

I have created ping.py file and tried calling below function

Python file (ping.py)

import sys
import requests

def handler(event, context):
print("Inside handler")
x = requests.get('http://localhost:9090/ping')
print(x.status_code)
return str(x.content)

## Command used to start LocalStack

docker compose up

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

- Used aws cli create lambda function
- Used  aws cli invoke lambda function

When I am hitting the http://localhost:9090/ping api from postman it's giving valid response.

 If I replace ping url to below url in handler which is hosted on Google then I am getting 200 status code without any issue. 
x = requests.get('https://w3schools.com')

**Comment by ShadabShariff** [comment]
Hi @tarunsingh2789, thank you for raising the issue, i have tried to replicate the same in my local and have faced the similar issue, this mostly because the docker run through localhost has to be made available to host network.
Could you please try restarting the local host docker with the env variable : **LAMBDA_DOCKER_NETWORK="host"** and please let me know if it works out for you. Thanks.

**Comment by tarunsingh2789** [comment]
Thanks ShadabShariff 😊 The issue has been resolved after adding the above env variable .

**Comment by tarunsingh2789** [comment]
Closed
