### ISSUE TITLE
Choosing listening ports doesn't work anymore 

### ISSUE THREAD

**Issue by cscetbon** [localstack/localstack#3558]
# Type of request: This is a bug report

# Detailed description
Starting with 0.11.6 changing listening port doesn't work anymore
```
docker run --name localstack -e SERVICES=s3:4571 localstack/localstack:0.11.6
...
Starting mock S3 service on http port 4566 ...
...
```

before 0.11.1 it was working as expected 
```
docker run --name localstack -e SERVICES=s3:4571 localstack/localstack:0.11.0
...
Starting mock S3 (http port 4571)
```
Starting with 0.11.1 it listens to the chosen port + the default one
```
docker run --name localstack -e SERVICES=s3:4571 localstack/localstack:0.11.1
...
Starting mock S3 service in http ports 4566 (recommended) and 4571 (deprecated)
..
```

I can see it says deprecated but I don't know why and it's a breaking change. Was it done on purpose ?

## Expected behavior
I would expect it to listen only on the port I choose.

**Comment by whummer** [comment]
Thanks for reporting @cscetbon . Recent versions of LocalStack are using a single port (edge service) as the single entry point for all API request. You can customize this port number by setting the `EDGE_PORT` environment variable.

Please refer to the following issue for some background on this change: https://github.com/localstack/localstack/issues/2983

Hope that helps - please keep us posted if there are any issues. Thanks!

**Comment by cscetbon** [comment]
@whummer you might have closed it too fast. Aren't you in charge of https://hub.docker.com/r/localstack/localstack ? If yes, the documentation should be updated cause it still says SERVICES could be used and it's only valid until 0.11.5. It's confusing. That issue might just be a documentation issue in that case.

**Comment by whummer** [comment]
Thanks for the pointer @cscetbon , the documentation on Docker Hub was indeed not fully up-to-date. We have now updated the docs there, please let us know if anything else is unclear or needs to be updated. Thanks!

**Comment by cscetbon** [comment]
Perfect, thanks @whummer !
