### ISSUE TITLE
kinesis invoked java8 lambda return base64 encoded record data

### ISSUE THREAD

**Issue by xyang7421** [localstack/localstack#356]
tested with docker run localstack/localstack, the retrieved record data is base64 encoded with the following code, which returns the original data in AWS env. Also the sequencenumber is always null.

 for(KinesisEvent.KinesisEventRecord rec : event.getRecords()) 
{
  String msg = new String(rec.getKinesis().getData().array());

**Comment by whummer** [comment]
Thanks for reporting @xyang7421 , this should be fixed in #365 . Can you please give it a try with the latest version and confirm that it works. Thanks
