### ISSUE TITLE
ListObjects returns error when ListObjectsRequest.Marker is empty string ( "" )

### ISSUE THREAD

**Issue by asautins** [localstack/localstack#3563]
[X] bug report
[ ] feature request

# Detailed description

In earlier versions of localstack ( e.g., 0.10.5 ) as well as on AWS if ListObjectsRequest.Marker is set to an empty string ("") ListObjects returns successfully.  On version 0.12.6 if Marker is set to empty string (404) Not Found is returned.

## Expected behavior

Behavior matching AWS.  If ListObjectsRequest.Marker = "" do not return an error.

## Actual behavior

An error is returned ( NotFound ) when ListObjectsRequest.Marker = "".  It works correctly when ListObjectsRequest.Marker = null.

# Steps to reproduce

Execute ListObjects with Marker = "".  0.12.6 will return NotFound.  AWS and Localstack 0.10.5 will execute successfully.
Execute ListObjects with Marker = null.  0.12.6, aws and 0.10.5 will all execute successfully.

**Comment by whummer** [comment]
Thanks for reporting @asautins . This should be fixed in #3580 - can you please pull the `latest` Docker image and give it another try? Please report here if the problem persists. Thanks

**Comment by asautins** [comment]
I re-ran our tests using `latest `and it seems to work correctly.  Thank you for the fix and the quick response!
