### ISSUE TITLE
unable to upload to s3 from lambda

### ISSUE THREAD

**Issue by tim-oe** [localstack/localstack#3566]
# Type of request: This is a ...

[ X] bug report
[ ] feature request

# Detailed description
i have the following project https://github.com/tim-oe/node-101/tree/s3api
using [latest](https://github.com/localstack/localstack/releases/tag/v0.12.6) localstack

within an [sqs event lambda, see SQSHandler](https://github.com/tim-oe/node-101/blob/s3api/src/functions/handler.ts)  I'm attempting to post to an s3 bucket.

```
        const d: Date = new Date();
        const request: S3.Types.PutObjectRequest = {
        Bucket: "node-101-archive",
        Body: Buffer.from(JSON.stringify(record.body), "utf-8"),
        Key: 'click-' + d.getMilliseconds() + '.json'};
    
        try {
        logger.info("uploading to s3 " + request.Key);
        const data: ManagedUpload.SendData = await s3.upload(request).promise();
        logger.info("uploaded to s3", data);
    } catch (err) {
        logger.error("error uploading to s3", err, err.stack);
    }
```

using default config, `const s3: AWS.S3 = new AWS.S3();`

i get the following error:  InvalidAccessKeyId
i followed the recommendation of this issue
https://github.com/localstack/localstack/issues/948
setting the end point in the config still fails with error below
`const s3Config: S3.Types.ClientConfiguration = {
    endpoint: 'http://' + process.env.LOCALSTACK_HOSTNAME + ':4566',
    apiVersion: '2006-03-01'
}` 

i get the following error:
I can upload a file to the bucket from awslocal fine.

the bucket is configured from the [init script](https://github.com/tim-oe/node-101/blob/s3api/bin/localstack-entrypoint.sh)

[serverless yml](https://github.com/tim-oe/node-101/blob/s3api/serverless.yml)
...

## Expected behavior
successful upload to s3
...

## Actual behavior
without endpoint config InvalidAccessKey
with it
`"originalError": {
     "message": "getaddrinfo ENOTFOUND node-101-archive.172.17.0.1",
     "errno": "ENOTFOUND",
     "code": "NetworkingError",
     "syscall": "getaddrinfo",
     "hostname": "node-101-archive.172.17.0.1",
     "region": "us-west-2",
     "retryable": true,
     "time": "2021-02-06T05:33:00.333Z"
}`

...

# Steps to reproduce
using the project https://github.com/tim-oe/node-101
s3api branch
deploy project above: `serverless deploy --stage local --region us-west-2`
hit api gateway endpoint `curl -v -i  http://localhost:4566/restapis/XXXXX/local/_user_request_/echo`

## Command used to start LocalStack
docker-compose up
[docker compose file](https://github.com/tim-oe/node-101/blob/s3api/docker-compose.yml)
...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
[handler.ts](https://github.com/tim-oe/node-101/blob/s3api/src/functions/handler.ts)
...

**Comment by irahulranjan** [comment]
Hi @tim-oe can you try after setting the `s3ForcePathStyle` as true?

**Comment by tim-oe** [comment]
That worked, thanks.

**Comment by jl-DaDar** [comment]
I have same problem but I am using python boto3 and I do not have s3ForcePathStyle

**Comment by macnev2013** [comment]
Thanks for reporting @jl-DaDar. Can you please share the error, localstack version and the command you've used to start localstack?
Thanks.

**Comment by jl-DaDar** [comment]
` START RequestId: 59208983-e0c9-1537-f3d6-e7c2bc50d677 Version: $LATEST
> Upload to s3 failed!
> Upload to s3 failed!
> ##>> w:512 h:512
> rect: 698.071900 865.000000 | 452.537760 614.160000
> Output => maptype: 1 destination: 2
> Output => maptype: 2 destination: 2
> Output => maptype: 3 destination: 2
> Output => maptype: 0 destination: 2
> output to aws
> [WARN] 2021-03-30 04:58:25.715 ClientConfiguration [140405098149632] Retry Strategy will use the default max attempts.
> [WARN] 2021-03-30 04:58:25.715 ClientConfiguration [140405098149632] Retry Strategy will use the default max attempts.
> [WARN] 2021-03-30 04:58:25.715 STSAssumeRoleWithWebIdentityCredentialsProvider [140405098149632] Token file must be specified to use STS AssumeRole web identity creds provider.
> [WARN] 2021-03-30 04:58:25.715 ClientConfiguration [140405098149632] Retry Strategy will use the default max attempts.
> @@ writing w:2048 h:2048
> Preparing for base64 output...
> @@ writing w:2048 h:2048
> Preparing for base64 output...
> output to aws
> [WARN] 2021-03-30 04:58:25.763 ClientConfiguration [140405197014784] Retry Strategy will use the default max attempts.
> [WARN] 2021-03-30 04:58:25.763 STSAssumeRoleWithWebIdentityCredentialsProvider [140405197014784] Token file must be specified to use STS AssumeRole web identity creds provider.
> [WARN] 2021-03-30 04:58:25.763 ClientConfiguration [140405197014784] Retry Strategy will use the default max attempts.
> output to aws
> [WARN] 2021-03-30 04:58:25.768 ClientConfiguration [140405188622080] Retry Strategy will use the default max attempts.
> [WARN] 2021-03-30 04:58:25.768 STSAssumeRoleWithWebIdentityCredentialsProvider [140405188622080] Token file must be specified to use STS AssumeRole web identity creds provider.
> [WARN] 2021-03-30 04:58:25.768 ClientConfiguration [140405188622080] Retry Strategy will use the default max attempts.
> @@ writing w:2048 h:2048
> Preparing for base64 output...
> output to aws
> [WARN] 2021-03-30 04:58:25.813 ClientConfiguration [140405180229376] Retry Strategy will use the default max attempts.
> [WARN] 2021-03-30 04:58:25.813 STSAssumeRoleWithWebIdentityCredentialsProvider [140405180229376] Token file must be specified to use STS AssumeRole web identity creds provider.
> [WARN] 2021-03-30 04:58:25.813 ClientConfiguration [140405180229376] Retry Strategy will use the default max attempts.
> [WARN] 2021-03-30 04:58:27.024 AWSErrorMarshaller [140405098149632] Encountered AWSError 'InvalidAccessKeyId': The AWS Access Key Id you provided does not exist in our records.
> [ERROR] 2021-03-30 04:58:27.024 AWSClient [140405098149632] HTTP response code: 403
> Resolved remote host IP address: 52.216.138.22
> Request ID: 810ESY67WY92BHCY
> Exception name: InvalidAccessKeyId
> Error message: The AWS Access Key Id you provided does not exist in our records.
> 7 response headers:
> connection : close
> content-type : application/xml
> date : Tue, 30 Mar 2021 04:58:26 GMT
> server : AmazonS3
> transfer-encoding : chunked
> x-amz-id-2 : WWQDSIOor0rllGZ6YuXdalUjJb903GZPD5d3dR2zaJ93g20DoDfqeD7iLg60AqVOoyYHAuB0gJA=
> x-amz-request-id : 810ESY67WY92BHCY
> [WARN] 2021-03-30 04:58:27.024 AWSClient [140405098149632] If the signature check failed. This could be because of a time skew. Attempting to adjust the signer.
> [WARN] 2021-03-30 04:58:27.054 AWSErrorMarshaller [140405188622080] Encountered AWSError 'InvalidAccessKeyId': The AWS Access Key Id you provided does not exist in our records.
> [ERROR] 2021-03-30 04:58:27.054 AWSClient [140405188622080] HTTP response code: 403`


actually we are not on boto3, but aws cpp sdk

**Comment by jl-DaDar** [comment]
we are  on 0.12.7

**Comment by jl-DaDar** [comment]
`
auto config = get_config(true);
Aws::S3::S3Client s3_client(config);

Aws::S3::Model::PutObjectRequest request;
request.SetBucket(bucket_name);
request.SetKey(key);

auto sstream = std::make_shared<std::stringstream>();
sstream->write(buffer, buffer_len);

request.SetBody(sstream);
Aws::S3::Model::PutObjectOutcome outcome = s3_client.PutObject(request);
return outcome.IsSuccess();

`

**Comment by macnev2013** [comment]
Thanks for providing the stack trace. If you are using pre-signed url - please make sure that you are using access key and secret key as `test`.
Thanks.

**Comment by jl-DaDar** [comment]
we don't use presign url, do we still need to explicitly add access key and secret to config? They are already in environment variable

**Comment by macnev2013** [comment]
Is it possible to provide a small isolated example (a git repo) with deployment instructions? It would help us a lot in debugging the issue.
Thanks.

**Comment by jl-DaDar** [comment]
sorry i think it was a bug in our code, the request actually went to a real aws service.

**Comment by macnev2013** [comment]
Thanks for the update @jl-DaDar .
