### ISSUE TITLE
Chalice + CDK isn't working

### ISSUE THREAD

**Issue by jarrodldavis** [localstack/localstack#3572]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description
I'm experiencing a few issues while deploying a [Chalice app using CDK](https://aws.amazon.com/blogs/developer/aws-chalice-adds-support-for-the-aws-cdk/) to LocalStack.

## Deployments
When I run `cdklocal deploy` (after running `cdklocal bootstrap`), I'm getting an `UPDATE_FAILED` error from CloudFormation. I'm not sure if that's related to or causing the following issues, but redeploying appears to be successful (mostly).

## API Gateway Integration not yet implemented

This check for the integration type:
https://github.com/localstack/localstack/blob/c75b4c905edbaa9e9de266fbd0b761f8d5d45d87/localstack/services/apigateway/apigateway_listener.py#L285-L295
expects `integration_type` to be uppercased (line 293). For some reason, `integration_type` is coming through as lower case (specifically: `aws_proxy`). As a result, when calling the API Gateway, I receive this error message:

```json
{
    "message": "API Gateway AWS integration action URI \"arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:000000000000:function:myproject-lambda-94b20fb4/invocations\", method \"GET\" not yet implemented"
}
```

I was able to confirm and correct the issue by editing `apigateway_listener.py` in the Docker container and restarting LocalStack. 

## `chalice` somehow missing

After clearing the previous hurdles, it appears something is amiss with the deployed Lambda itself.

When calling the API Gateway, the Lambda function fails with this error:

```json
{
    "errorMessage": "Lambda process returned error status code: 1. Result: {\"errorType\":\"Runtime.ImportModuleError\",\"errorMessage\":\"Unable to import module 'app': cannot import name 'Chalice' from 'chalice' (unknown location)\"}. Output:\n\u001b[32mSTART RequestId: 76f28b6a-dfac-178f-3a00-de1408fa9ae2 Version: $LATEST\u001b[0m\n[ERROR] Runtime.ImportModuleError: Unable to import module 'app': cannot import name 'Chalice' from 'chalice' (unknown location)\n\u001b[32mEND RequestId: 76f28b6a-dfac-178f-3a00-de1408fa9ae2\u001b[0m\n\u001b[32mREPORT RequestId: 76f28b6a-dfac-178f-3a00-de1408fa9ae2\tInit Duration: 195.16 ms\tDuration: 3.44 ms\tBilled Duration: 4 ms\tMemory Size: 1536 MB\tMax Memory Used: 33 MB\t\u001b[0m",
    "errorType": "InvocationException",
    "stackTrace": [
        "  File \"/opt/code/localstack/localstack/services/awslambda/lambda_api.py\", line 568, in run_lambda\n    result = LAMBDA_EXECUTOR.execute(func_arn, func_details, event, context=context,\n",
        "  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 174, in execute\n    return do_execute()\n",
        "  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 166, in do_execute\n    return _run(func_arn=func_arn)\n",
        "  File \"/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py\", line 149, in wrapped\n    raise e\n",
        "  File \"/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py\", line 145, in wrapped\n    result = func(*args, **kwargs)\n",
        "  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 157, in _run\n    raise e\n",
        "  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 145, in _run\n    result = self._execute(func_arn, func_details, event, context, version)\n",
        "  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 323, in _execute\n    result = self.run_lambda_executor(cmd, stdin, env_vars=environment, func_details=func_details)\n",
        "  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 229, in run_lambda_executor\n    raise InvocationException('Lambda process returned error status code: %s. Result: %s. Output:\\n%s' %\n"
    ]
}
```

## Expected behavior
Deploying the CDK + Chalice app should work, allowing me to call the API Gateway endpoint and receive a successful response from the Lambda function.

## Actual behavior
Deploying doesn't seem to work correctly, API Gateway doesn't see the integration type correctly, and the Lambda function appears to be missing dependencies.

# Steps to reproduce

## Command used to start LocalStack
`localstack start`

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
- Follow the instructions to [create and deploy a CDK + Chalice app](https://aws.amazon.com/blogs/developer/aws-chalice-adds-support-for-the-aws-cdk/)
- Install [`cdklocal`](https://github.com/localstack/aws-cdk-local)
- alias `cdklocal` to use `AWS_DEFAULT_REGION` (see below)
- run `cdklocal bootstrap` and `cdklocal deploy`

The `cdklocal` alias is required since since the scaffolded app uses a `boto3` method on startup that requires an AWS region to be set:
```
alias cdklocal='AWS_DEFAULT_REGION=us-east-1 cdklocal'
```

**Comment by whummer** [comment]
Thanks for reporting @jarrodldavis - there have been a couple of changes around API Gateway, CloudFormation and other APIs. Can you please give it another try with the `latest` Docker image and let us know if the problem still persists? Thanks for your help!

**Comment by brianmingus2** [comment]
@whummer did you get a chance to look at this ticket?

https://github.com/localstack/chalice-local/issues/4

**Comment by areeves87** [comment]
FWIW I am able to build and deploy the chalice-cdk example project with cdklocal and chalice-local following the same instructions @jarrodldavis gave. Only additional detail is that in the chalice app.py file I needed to update the dynamodb resource's endpoint_url to use the LOCALSTACK_HOSTNAME when deploying the lambda to localstack. Eg
```python
app = Chalice(app_name='cdkdemo')
configs = {}
if os.environ.get('LOCALSTACK_HOSTNAME'):
    endpoint_url = 'http://%s:4566' % os.environ['LOCALSTACK_HOSTNAME']
    configs['endpoint_url'] = endpoint_url
dynamodb = boto3.resource('dynamodb', **configs)
dynamodb_table = dynamodb.Table(os.environ.get('APP_TABLE_NAME', ''))
```
