### ISSUE TITLE
Prefix of "/" is required for the bucket name when calling `AmazonS3.listObjects(String bucketName)`, when using the AWS Java SDK with localstack

### ISSUE THREAD

**Issue by xiandalong** [localstack/localstack#3573]
# Type of request: This is a bug report

# Detailed description
I was using localstack 0.10.4 as the simulator for local s3. I created a bucket and put a file under the bucket, but I when using `AmazonS3.listObjects(String bucketName)` in the s3 sdk, it gives me an empty list. I spent quite some time on this, and found out that a prefix of "/" is needed for the bucketName, even though the bucket names you get from `AmazonS3.listBuckets()` doesn't have the prefix.

## Expected behavior
I should be able to just use bucket name as input without the prefix. (This applies to not only `AmazonS3.listObjects(String bucketName)` , but also `AmazonS3.doesObjectExist(String bucketName, String objectName)`, not sure if there're other methods suffering from the same issue.)

## Actual behavior
I need to include a prefix of "/" for the bucket name when calling `AmazonS3.listObjects(String bucketName)`, when working with localstack s3 simulator.

# Steps to reproduce
* Run localstack 0.10.4 in docker (actually tried to use latest 0.12.6 and seeing the same issue)
* Use AWS s3 java SDK in a java application
* With AWS CLI tool, Create bucket and put a file under the bucket
* In the java application, create an instance of AmazonS3 connected to localstack, and print the result of `AmazonS3.listObjects(String bucketName)`
* The result is an empty list.

## Command used to start LocalStack
Use `docker compose` to start it in docker.

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
How we provide `AmazonS3` with Guice Injection:
```
@Provides
@Singleton
@Inject
AmazonS3 provideS3Client(@Named("s3Cred") AWSCredentialsProvider credentialsProvider, S3Config config) {
    AmazonS3ClientBuilder clientBuilder = AmazonS3ClientBuilder.standard()
            .withCredentials(credentialsProvider);

    if (StringUtils.isNoneBlank(config.getRegion(), config.getEndpoint())) {
        clientBuilder.withEndpointConfiguration(
                new AwsClientBuilder.EndpointConfiguration(config.getEndpoint(), config.getRegion())
        );
    }
    return clientBuilder
            .withCredentials(credentialsProvider)
            .build();
}
```
Then we just call it's methods like `AmazonS3.listObjects(String bucketName)` in other classes where this gets in injected.

## Environment
* AWS Java SDK version used: 1.11.940
* JDK version used: 8
* Operating System and version: MacOS Catalina 10.15.7

**Comment by whummer** [comment]
Thanks for reporting @xiandalong . Can you please enable path-style addressing in your S3 clients.

Please refer to this repo for an example how we're creating S3 clients in our Java integration tests: https://github.com/localstack/localstack-java-utils/blob/master/src/main/java/cloud/localstack/awssdkv1/TestUtils.java#L127-L133
```
    public static AmazonS3 getClientS3() {
        AmazonS3ClientBuilder builder = AmazonS3ClientBuilder.standard().
                withEndpointConfiguration(getEndpointConfigurationS3()).
                withCredentials(getCredentialsProvider());
        builder.setPathStyleAccessEnabled(true);
        return builder.build();
    }
```
Hope that helps - please keep us posted. Thanks

**Comment by xiandalong** [comment]
Hi @whummer , thanks for providing the solution. While this fixes the problem for localstack, I do have to configure my application so that it turn this `setPathStyleAccessEnabled` option on for dev environment but not staging or production. Do you guys still consider this a bug? because it's not obvious to the user that we'll need to turn this on in Java SDK in order for localstack to work the same way as we're interacting with s3 on AWS cloud.

**Comment by whummer** [comment]
Thanks for the update @xiandalong . For now, setting `setPathStyleAccessEnabled` is required (we've seen most of our users  solve this in their code by using some kind of environment variable that activates the local endpoints for testing).

In a future iteration, we may be switching to domain-style addressing, which will make this setting obsolete. Stay tuned! Thanks
