### ISSUE TITLE
EventBridge returning error 500 in a valid Json

### ISSUE THREAD

**Issue by Josemaralves** [localstack/localstack#3575]
# Type of request: This is a ...

[X] bug report
[ ] feature request

# Detailed description

Eventbridge is throwing a error in Json.loads when trying to PutEvents

## Expected behavior

Is Expected to successfully send a message

## Actual behavior

EventBridge is returning error 500 and throwing Json Parse error in Localstack container.

# Steps to reproduce

1. Run latest Localstack Image in Debug Mode
docker run -p 4566:4566 -e DEBUG=true localstack/localstack:latest

2. Send any message to EventBridge

3.Check in Logs a Parse Error. 

## Command used to start LocalStack

docker run -p 4566:4566 -e DEBUG=true localstack/localstack:latest

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

PutEventsRequest eventsRequest = mountRequest(requestEntry);
PutEventsResponse putEventsResponse = client.putEvents(eventsRequest);

**Comment by usmangani1** [comment]
@Josemaralves Thanks for reporting the issue. 
We had tried to reproduce the issue on the current version of localstack using the json added below but we are not successful to do so.

`
%  aws --endpoint-url=http://localhost:4566 events put-events --entries file://sample.json

[
  {
    "Source": "com.mycompany.myapp",
    "Detail": "{ \"key1\": \"value1\", \"key2\": \"value2\" }",
    "Resources": [
      "resource1",
      "resource2"
    ],
    "DetailType": "myDetailType"
  },
  {
    "Source": "com.mycompany.myapp",
    "Detail": "{ \"key1\": \"value3\", \"key2\": \"value4\" }",
    "Resources": [
      "resource1",
      "resource2"
    ],
    "DetailType": "myDetailType"
   }
]`

Can you please give this a try on the latest version, If the issue still persists can you please give us the JSON which you are trying with.

**Comment by usmangani1** [comment]
Thanks for reporting @Josemaralves .can you please pull the latest Docker image and give it another try? Please keep us posted if the problem persists. Thanks for your help!
