### ISSUE TITLE
LAMBDA_FALLBACK_URL sends as application/x-www-form-urlencoded Content-Type

### ISSUE THREAD

**Issue by jkentjnr** [localstack/localstack#3584]
# Type of request: This is a ...

[X] bug report
[ ] feature request

# Detailed description

When LocalStack forwards a request to a fallback url, the POST body is in form data -- not in its raw original form.

## Expected behavior

payload.json:
```
{
    "action": "syncResponse"
}
```

Expect listener at LAMBDA_FALLBACK_URL to receive the payload.json in the POST body.

## Actual behavior

Receiving using `npx http-echo-server`:
```
--> POST /localstack HTTP/1.1
--> Host: host.docker.internal:5000
--> User-Agent: python-requests/2.25.1
--> Accept-Encoding: gzip, deflate
--> Accept: */*
--> Connection: keep-alive
--> lambda-function-name: fake-name
--> Content-Length: 19
--> Content-Type: application/x-www-form-urlencoded
--> 
--> 
[socket#2] event: data
--> action=syncResponse
```

Listener at LAMBDA_FALLBACK_URL receiving `action=syncResponse` as form data in the POST body.

# Steps to reproduce

## Command used to start LocalStack
`docker-compose up` with `LAMBDA_FALLBACK_URL=http://${DOCKER_GATEWAY_HOST:-host.docker.internal}:5000/localstack`

`npx http-echo-server 5000`

In a seperate session:

`aws --endpoint-url=http://localhost:4566 lambda invoke --invocation-type RequestResponse --function-name fake-name --payload fileb://payload.json response.json`

**Comment by pinzon** [comment]
This issue should have been fixed with the merge of my latest PR.
