### ISSUE TITLE
Disabled lambda event source mapping to SQS still triggers lambda on SQS event

### ISSUE THREAD

**Issue by jmeros** [localstack/localstack#3585]
# Type of request: This is a ...

[X] bug report
[ ] feature request

# Detailed description

LocalStack version: 0.12.5

If an event source mapping is disabled between a SQS and a Lambda , i.e.

`awslocal lambda update-event-source-mapping --uuid <uuid> --no-enabled`

The above has no effect and the lambda function will still be invoked.

Similar to the problem described on [#2541](https://github.com/localstack/localstack/issues/2541)

## Expected behavior

The lambda should not be invoked, according to the [AWS API doc](https://docs.aws.amazon.com/lambda/latest/dg/API_UpdateEventSourceMapping.html#API_UpdateEventSourceMapping_RequestSyntax)

> Enabled
> Disables the event source mapping to pause polling and invocation.

## Actual behavior

The associated lambda of an event source mapping is invoked even though it is disabled.

# Steps to reproduce

## Command used to start LocalStack

`DEFAULT_REGION=eu-central-1 TEST_AWS_ACCOUNT_ID=111111111111 DEBUG=true localstack start`

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

Start a bash session in the container

`docker exec -it localstack bash`

Run the following

```
# Create lambda function
TMPDIR=$(mktemp -d)
cd $TMPDIR
echo 'def handler(event, context): print("Received:", event)' > function.py
zip function.zip function.py
awslocal lambda create-function \
    --function-name stream_processor \
    --runtime python3.8 \
    --role anything \
    --handler function.handler \
    --zip-file fileb://function.zip

# Create SQS
QUEUE_URL=$(awslocal sqs create-queue --queue-name foo \
    | python3 -c "import sys, json; print(json.load(sys.stdin)['QueueUrl'])")

# Create disabled event source mapping between SQS and Lambda
awslocal lambda create-event-source-mapping \
       --event-source-arn arn:aws:sqs:eu-central-1:111111111111:foo \
       --function-name stream_processor \
       --no-enabled

# Send event to SQS
awslocal sqs send-message \
    --queue-url $QUEUE_URL \
    --item '{"id": {"S": "1"}, "message": {"S": "Hello"}}'
```

Check the logs from localstack and you should something like this:

```
...
> START RequestId: d36a5989-17ca-187e-adfd-f697fe564993 Version: $LATEST
> Received: {'Records': [{'body': '{"id": {"S": "1"}, "message": {"S": "Hello"}}', 'receiptHandle': 'jsuitijhidjacwfgdndjhmwqlemrvkovpylhjwcnpnqpbvfoulnrjerbcyudnqirnehspzpamgpuelpyarqmfzpdbdrzhvbdktlagusnnvetmswfqwukoewmhnfntaeaqfbmypdxboczevbsrvdlzuifjcxdedqmfmzopbxlqpjqfgkivpqpxsnop', 'md5OfBody': '99f1e56f06e936d2ec193df9c4cd9b8e', 'eventSourceARN': 'arn:aws:sqs:eu-central-1:111111111111:foo', 'eventSource': 'aws:sqs', 'awsRegion': 'eu-central-1', 'messageId': 'f34bee72-a413-7b13-5025-d531883d636f', 'attributes': {'SenderId': 'AIDAIT2UOQQY3AUEKVGXU', 'SentTimestamp': '1612864699061', 'ApproximateReceiveCount': '1', 'ApproximateFirstReceiveTimestamp': '1612864699110'}, 'messageAttributes': {}, 'md5OfMessageAttributes': None, 'sqs': True}]}
> END RequestId: d36a5989-17ca-187e-adfd-f697fe564993
> REPORT RequestId: d36a5989-17ca-187e-adfd-f697fe564993        Init Duration: 253.05 ms        Duration: 6.72 ms       Billed Duration: 7 ms   Memory Size: 1536 MB    Max Memory Used: 24 MB 
```

**Comment by jmeros** [comment]
@ShadabShariff, could you please take a look at my commit [120df93
](https://github.com/jmeros/localstack/commit/120df938febc723ce9319ffe503b48593f5eac1a) as a possible solution to this issue? If you agree, I can request a PR from it to this issue?

**Comment by whummer** [comment]
Hi @jmeros , apologies for the long delay on this one. Looks like you have a fix in your branch that could be a great solution or starting point - can you please create a PR against this repo, so we can take a closer look and get it merged? Thanks!
