### ISSUE TITLE
DetailType does not appear to be handled correctly in event bridge patterns

### ISSUE THREAD

**Issue by alexbaileyuk** [localstack/localstack#3586]
# Type of request: This is a ...

[X] bug report
[ ] feature request

# Detailed description

Event patterns using `DetailType` do not appear to be handled correctly in EventBridge.

## Expected behavior

When using `DetailType` in event patterns, the event should be routed to the target correctly. In the below scenario, there should be a message in the relevant SQS Queue.

## Actual behavior

When using `DetailType` in event patterns, the event is not routed to the target. In the below scenario, there should be a message in the relevant SQS Queue.

# Steps to reproduce

## Command used to start LocalStack

```
localstack start
```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

```
# Create Queue
laws sqs create-queue --queue-name dev-test-queue

# Get Queue ARN
laws sqs get-queue-attributes --queue-url http://localhost:4566/000000000000/dev-test-queue

# Create Event Bus
laws events create-event-bus --name dev-event-bus

# Create Event Rule
laws events put-rule --name dev-test-rule --event-bus-name dev-event-bus --event-pattern '{"Source": ["com.service"],"DetailType": ["my.detail"]}'

# Create Event Target
laws events put-targets --rule dev-test-rule --event-bus-name "dev-event-bus" --targets "Id"="1","Arn"="arn:aws:sqs:eu-west-1:000000000000:dev-test-queue"

# Push Test Event
laws events put-events --entries file:///tmp/test-event.json

# Check SQS Queue
laws sqs receive-message --queue-url http://localhost:4566/000000000000/dev-test-queue
```

**test-event.json**
```
[
  {
    "Source": "com.service",
    "Detail": "{ \"test\": \"testing\" }",
    "Resources": [],
    "DetailType": "my.detail",
    "EventBusName": "dev-event-bus"
  }
]
```

**Comment by macnev2013** [comment]
Thanks for reporting @alexbaileyuk .

The behavior you are observing is expected behavior from AWS.

When creating a `event rule (event-pattern)` in AWS, it is **not performing any string normalization** on the rules json passed by the cli.
Whereas while `putting event` to the event bus, it **converts the event json** to the [standard event structure.](https://docs.aws.amazon.com/eventbridge/latest/userguide/aws-events.html)

i.e. This rule (event-pattern) -> `'{"Source": ["com.service"],"DetailType": ["my.detail"]}'` does not match with the event because event json will be converted to `'{"source": "aws.sqs", "detail": "{ \"test\": \"testing\" }","resources": [],"detail-type": "my.detail","eventbusname": "dev-event-bus"}'`


**Working example:**

```
# Create Queue
awslocal sqs create-queue --queue-name dev-test-queue

# Get Queue ARN
awslocal sqs get-queue-attributes --queue-url http://localhost:4566/000000000000/dev-test-queue

# Create Event Bus
awslocal events create-event-bus --name dev-event-bus

# Create Event Rule
awslocal events put-rule --name dev-test-rule --event-bus-name dev-event-bus --event-pattern '{"source": ["com.service"], "detail-type": ["my.detail"]}'

# Create Event Target
awslocal events put-targets --rule dev-test-rule --event-bus-name "dev-event-bus" --targets "Id"="1","Arn"="arn:aws:sqs:us-east-1:000000000000:dev-test-queue"

# Push Test Event
awslocal events put-events --entries file://test-event.json

# Check SQS Queue
awslocal sqs receive-message --queue-url http://localhost:4566/000000000000/dev-test-queue
```

**test-event.json**
```
[
  {
    "Source": "com.service",
    "Detail": "{ \"test\": \"testing\" }",
    "Resources": [],
    "DetailType": "my.detail",
    "EventBusName": "dev-event-bus"
  }
]
```

**Comment by whummer** [comment]
Thanks for reporting @alexbaileyuk and thanks for clarifying @macnev2013 . Looks like we're using the correct behavior in this case (same as on AWS). Please report here if there is more evidence that indicates a bug or incorrect behavior. Thanks!
