### ISSUE TITLE
EC2 enum missing in java library, so it is not possible to mock aws cloud computing service  

### ISSUE THREAD

**Issue by nazymko** [localstack/localstack#3590]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description
EC2 Supported by localstack but it is missing in the library 

org.testcontainers.containers.localstack.LocalStackContainer.Service
...

## Expected behavior
EC2 Present in the services enumeration 
...

## Actual behavior
EC2 missing so it is not possible to activate it via env variable (as it is overridden by services from 'withServices()

Code bellow starts only IAM service 
```
    @Rule
    public LocalStackContainer localstack = new LocalStackContainer(localstackImage)
            .withServices(LocalStackContainer.Service.IAM)
            .withEnv("SERVICES", "ec2,iam");
```
...

# Steps to reproduce
Use LocalStackContainer from localstack 1.15.1 
 
## Command used to start LocalStack
Java configuration

@RunWith(MockitoJUnitRunner.class)
...
 DockerImageName localstackImage = DockerImageName.parse("localstack/localstack:0.12.5");
    @Rule
    public LocalStackContainer localstack = new LocalStackContainer(localstackImage)
            .withServices(LocalStackContainer.Service.IAM)
            .withEnv("SERVICES", "ec2,I am");

...

**Comment by pinzon** [comment]
@nazymko even thou testcointainers is different project, I provided the fix in their repo. 
It's just waiting to be merged so I'm gonna close this issue.
