### ISSUE TITLE
GetMetricData incompatible with JAVA SDK v2

### ISSUE THREAD

**Issue by VanRoy** [localstack/localstack#3592]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

GetMetricData on Cloudwatch return no points from with AWS Java SDK v2 ( but boto or CLI works).

## Expected behavior

GetMetricData should return points added with PutMetricData with the AWS Java SDK v2.

## Actual behavior

GetMetricData java method return empty list with the AWS Java SDK v2.

# Steps to reproduce

The step to reproduce is already described in the related moto bug : https://github.com/spulec/moto/issues/3645

I already done the fix in moto here : https://github.com/spulec/moto/pull/3675

**Comment by pinzon** [comment]
Hi @VanRoy sorry for my very late answer, some issues take more time than expected. 
I see that you already made a fix and it has been merge.
So I'm closing this issue.

**Comment by VanRoy** [comment]
@pinzon thanks a lot.
