### ISSUE TITLE
Stepfunctions is stuck when parallel tasks have 3 or 4 different lambdas

### ISSUE THREAD

**Issue by ivy-wei-yang** [localstack/localstack#3607]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

When step functions has parallel tasks, and parallel tasks points to 3 or 4 or more different lambdas, the step functions execution is stuck at starting the lambdas. For the example below, it is >=3, for our actual project, it is stuck when >=4.
![Localstack-4-parallel-stuck](https://user-images.githubusercontent.com/55932651/108048634-24432c80-70ac-11eb-945a-cb41c6ba7899.JPG)

It was successful when there were 2 parallel tasks.
![Localstack-2-parallel-run](https://user-images.githubusercontent.com/55932651/108048310-bdbe0e80-70ab-11eb-8ae2-3edc908d04b8.JPG)

## Expected behavior

Step functions can run successfully when there are parallel tasks which points to >= 3 different lambdas

## Actual behavior

Step functions execution is stuck at starting the >= 3 lambdas 

# Steps to reproduce

## Command used to start LocalStack

docker-compose pull

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

serverless.yml
```

service: test-parallel # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'local'}
  region: ap-southeast-2
  timeout: 30 # will need to reduce this at some point, kept failing
  versionFunctions: false
  deploymentBucket:
    name: deploy-local
    serverSideEncryption: AES256 # when using server-side encryption
  environment:
    NODE_ENV: production
    stage: ${self:provider.stage}

package:
  exclude:
    - src/**
    - dist/test/**
    - node_modules

functions:
  mymethod1:
    handler: dist/handlers/mymethodHandler.mymethod1
  mymethod2:
    handler: dist/handlers/mymethodHandler.mymethod2
  mymethod3:
    handler: dist/handlers/mymethodHandler.mymethod3
  mymethod4:
    handler: dist/handlers/mymethodHandler.mymethod4

stepFunctions:
  stateMachines:
    Test:
      name: test-parallel-local
      definition:
        Comment: examples to run 4 methods on parallel
        StartAt: ParallelExamples
        States:
          ParallelExamples:
            Type: Parallel
            End: true
            ResultPath: $.parallelExamples
            Branches:
              - StartAt: Parallel_1
                States:
                  Parallel_1:
                    Type: Task
                    Resource: 'arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${opt:stage}-mymethod1'
                    End: true
              - StartAt: Parallel_2
                States:
                  Parallel_2:
                    Type: Task
                    Resource: 'arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${opt:stage}-mymethod2'
                    End: true
              - StartAt: Parallel_3
                States:
                  Parallel_3:
                    Type: Task
                    Resource: 'arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${opt:stage}-mymethod3'
                    End: true
              - StartAt: Parallel_4
                States:
                  Parallel_4:
                    Type: Task
                    Resource: 'arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${opt:stage}-mymethod4'
                    End: true
    

custom:
  localstack:
    stages:
      - local # list of stages for which the plugin should be enabled
    host: http://localhost  # optional - LocalStack host to connect to
    edgePort: 4566  # optional - LocalStack edge port to connect to
    autostart: false  # optional - Start LocalStack in Docker on Serverless deploy
    lambda:
      mountCode: false  # Enable this flag to improve performance
    debug: true

plugins:
  - serverless-step-functions
  - serverless-pseudo-parameters
  - serverless-plugin-aws-alerts
  - serverless-plugin-select
  - serverless-localstack

```

docker-compose.yml
```
version: "3.3"
services:

  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack:0.12.5
    network_mode: bridge
    environment:
      - SERVICES=iam,cloudformation,sts,s3,ses,sns,sqs,lambda,dynamodb,stepfunctions
      - DEFAULT_REGION=ap-southeast-2
      - LAMBDA_EXECUTOR=docker
      - LAMBDA_REMOTE_DOCKER=1
      - DEBUG=1
      # - STEPFUNCTIONS_LAMBDA_ENDPOINT=http://localhost:4566
    ports:
      - "4566:4566"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
```

mymethodHandler.ts
```
export function mymethod1(): void {
    console.log("mymethod1");
}
export function mymethod2(): void {
    console.log("mymethod2");
}
export function mymethod3(): void {
    console.log("mymethod3");
}
export function mymethod4(): void {
    console.log("mymethod4");
}
```

Note: need to create the deployment bucket "deploy-local" before deploy serverless into localstack.

**Comment by pinzon** [comment]
Hi @ivy-wei-yang I tested the issue you described with the lates LocalStack version. I also added even more parallel functions but It works perfectly.
I'm guessing it has to do with hardware limitations.

I'm adding the reproducer code so you can tell me if I'm doing something wrong. 
After running `docker-compose up` I run  `./run.sh` to deploy the serverless project and run the state machine once.
[reproducer.zip](https://github.com/localstack/localstack/files/6231174/reproducer.zip)

**Comment by pinzon** [comment]
Hi @ivy-wei-yang I tested the issue you described with the lates LocalStack version. I also added even more parallel functions but It works perfectly.
I'm guessing it has to do with hardware limitations.

I'm adding the reproducer code so you can tell me if I'm doing something wrong. 
After running `docker-compose up` I run  `./run.sh` to deploy the serverless project and run the state machine once.
[reproducer.zip](https://github.com/localstack/localstack/files/6231174/reproducer.zip)
