### ISSUE TITLE
Getting error when lambda is trying to write to S3 bucket - Unable to execute HTTP request: Connect to 172.29.0.4:4572

### ISSUE THREAD

**Issue by ashameem123** [localstack/localstack#3609]
# Type of request: This is a ...

[*] bug report
[ ] feature request

# Detailed description
Why am i getting this-
"software.amazon.awssdk.core.exception.SdkClientException: Unable to execute HTTP request: Connect to 172.29.0.4:4572 [/172.29.0.4] failed: Connection refused (Connection refused)" 

when my lambda is trying to put an object in S3 bucket , i am getting above error.
All Localstack services runs on 4566 , no where my code configure port 4572.

## Expected behavior

Lambda should successfully put an object in s3 bucket 

## Actual behavior

getting above error mentioned.

# Steps to reproduce

All buckets, lambdas ,SNS are successfully created on port 4566 , when lambda is invoked, getting above error and object is not placed in the s3 bucket.

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
sleep 2
aws --endpoint-url=http://localhost:4566 s3 mb s3://mybucket-000000000000-us-east-1

sleep 5
aws sns create-topic --name bucket-notification --endpoint-url=http://localhost:4566

sleep 5

#create function

aws lambda create-function --endpoint-url=http://localhost:4566 --function-name my-s3-function --runtime java11 --handler test.event.s3.publish.function.myS3Function --zip-file fileb://my-s3-function.zip --role arn:aws:iam::1234567:role/anything --environment file://environmentvariables.json

#Subscribe lambda to Topic:
aws sns subscribe --topic-arn arn:aws:sns:us-east-1:000000000000:bucket-notification --protocol lambda --notification-endpoint arn:aws:lambda:us-east-1:000000000000:function:my-s3-function --endpoint-url=http://localhost:4566

aws --endpoint-url=http://localhost:4566 sns publish --topic-arn arn:aws:sns:us-east-1:000000000000:tib-notification --message file://copyfiletos3.json

screen shots:
![image](https://user-images.githubusercontent.com/54183749/108092015-e0b3d880-7041-11eb-91ef-ce235e8e87dd.png)

**Comment by irahulranjan** [comment]
Hi @ashameem123, Thanks for reporting the issue. Can you please share the localstack startup commands, environmentvariables.json, and the lambda zip file?

**Comment by ashameem123** [comment]
@irahulranjan  - Replied via email.

**Comment by ashameem123** [comment]
Is there a way i can DM you the details you need? I'm sorry can't provide the zip file on this forum as it is live project specific.

**Comment by irahulranjan** [comment]
@ashameem123 can you provide a zip with minimal code (without any project-specific code) that just tries to write to the bucket?
It would be helpful if you can share the code where the session is getting created and the call is made to s3.

**Comment by ashameem123** [comment]
[csg-tib-event-s3-function-1.0-SNAPSHOT.zip](https://github.com/localstack/localstack/files/5991625/csg-tib-event-s3-function-1.0-SNAPSHOT.zip)

localstack startup command:
docker-compose up -d

Env variables file content:
{
	"Variables": {
		"S3_BUCKET": "tib-notification-000000000000-us-east-1",
		"TOPIC_ARN": "arn:aws:sns:us-east-1:000000000000:tib-audit",
		"REDIS_NODE": "redis:6379",
		"SNS_SIGNING_REGION": "us-east-1",
		"S3_KEY_OUTPUT": "output",
		"USE_LOCALSTACK":"true"

	}
}

**Comment by ashameem123** [comment]
@irahulranjan -Please find the details:

[my-s3-function.zip.zip](https://github.com/localstack/localstack/files/5991655/my-s3-function.zip.zip)

localstack startup command:
docker-compose up -d

Env variables file content:
{
	"Variables": {
		"S3_BUCKET": "mybucket-000000000000-us-east-1",
		"TOPIC_ARN": "arn:aws:sns:us-east-1:000000000000:tib-audit",
		"REDIS_NODE": "redis:6379",
		"SNS_SIGNING_REGION": "us-east-1",
		"S3_KEY_OUTPUT": "output",
		"USE_LOCALSTACK":"true"

	}
}

**Comment by irahulranjan** [comment]
Hi @ashameem123, while creating the s3 service you have to specify the endpoint parameter as the localstack endpoint. Can you try it out? 
Python Example:
```
endpoint = 'http://%s:4566' % os.environ['LOCALSTACK_HOSTNAME']
client = boto3.client(..., endpoint_url=endpoint)
```

Meanwhile please share the sample message being published to the sns topic. When I publish a dummy message I get the following error:
```
Class not found: test.event.s3.publish.function.myS3Function: java.lang.ClassNotFoundException
```

**Comment by ashameem123** [comment]
[copyFileToS3.docx](https://github.com/localstack/localstack/files/6006133/copyFileToS3.docx)
I am not able to upload JSON file, Please convert it into json and publish to SNS.

**Comment by ashameem123** [comment]
@irahulranjan - Hi, Any update please?

**Comment by irahulranjan** [comment]
@ashameem123, Hi I am getting the following error when I try the steps:
```
raceback (most recent call last):
  File "/Users/rahul/py/localstack/localstack/utils/bootstrap.py", line 593, in run
    result = self.func(self.params)
  File "/Users/rahul/py/localstack/localstack/services/awslambda/lambda_executors.py", line 168, in do_execute
    return _run(func_arn=func_arn)
  File "/Users/rahul/py/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 149, in wrapped
    raise e
  File "/Users/rahul/py/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 145, in wrapped
    result = func(*args, **kwargs)
  File "/Users/rahul/py/localstack/localstack/services/awslambda/lambda_executors.py", line 159, in _run
    raise e
  File "/Users/rahul/py/localstack/localstack/services/awslambda/lambda_executors.py", line 147, in _run
    result = self._execute(func_arn, func_details, event, context, version)
  File "/Users/rahul/py/localstack/localstack/services/awslambda/lambda_executors.py", line 325, in _execute
    result = self.run_lambda_executor(cmd, stdin, env_vars=environment, func_details=func_details)
  File "/Users/rahul/py/localstack/localstack/services/awslambda/lambda_executors.py", line 232, in run_lambda_executor
    (return_code, result, log_output), log_output, result)
localstack.services.awslambda.lambda_executors.InvocationException: Lambda process returned error status code: 1. Result: {"errorType":"java.lang.ClassNotFoundException","errorMessage":"Class not found: test.event.s3.publish.function.myS3Function"}. Output:
START RequestId: f82d9130-761b-145b-9122-a6319760a91b Version: $LATEST
Class not found: test.event.s3.publish.function.myS3Function: java.lang.ClassNotFoundException
java.lang.ClassNotFoundException: test.event.s3.publish.function.myS3Function
	at java.base/java.net.URLClassLoader.findClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Unknown Source)
```

Can you share the correct zip file.

Also i am using AWS CLI, isn't it’s enough to specify service URL to make LocalStack S3 work?
Yes


> @irahulranjan - Hi, Any update please?
> Also i am using AWS CLI, isn't it’s enough to specify service URL to make LocalStack S3 work?

yes, specifying just the s3 URL should work.

**Comment by ashameem123** [comment]
@irahulranjan - please find the zip and commands i am using to trigger this function.

#!/bin/bash

sleep 2
aws --endpoint-url=http://localhost:4566 s3 mb s3://tib-notification-000000000000-us-east-1

sleep 2
aws --endpoint-url=http://localhost:4566 s3api put-object --bucket tib-notification-000000000000-us-east-1 --key output/QATEST/

sleep 5
aws sns create-topic --name tib-notification --endpoint-url=http://localhost:4566

sleep 3

#create function

aws lambda create-function --endpoint-url=http://localhost:4566 --function-name tib-event-s3-function --runtime java11 --handler csg.tib.event.s3.publish.function.TiBEventS3Function --zip-file fileb://tib-event-s3-function.zip --role arn:aws:iam::1234567:role/anything --environment file://environmentvariables.json


sleep 5

#Subscribe lambda to Topic:
aws sns subscribe --topic-arn arn:aws:sns:us-east-1:000000000000:tib-notification --protocol lambda --notification-endpoint arn:aws:lambda:us-east-1:000000000000:function:tib-event-s3-function --endpoint-url=http://localhost:4566

sleep 3
aws --endpoint-url=http://localhost:4566 sns publish --topic-arn arn:aws:sns:us-east-1:000000000000:tib-notification --message file://copyfiletos3.json

ZIP File:
[tib-event-s3-function.zip.zip](https://github.com/localstack/localstack/files/6045787/tib-event-s3-function.zip.zip)

**Comment by irahulranjan** [comment]
Hi @ashameem123,

Can you please share the sample snippet where s3 session is getting created and the put object is called?

**Comment by ashameem123** [comment]
@irahulranjan : Here is the code snippet, 
![S3ClientCreationAndPUTobjcall](https://user-images.githubusercontent.com/54183749/109674503-9734b480-7b3c-11eb-801f-3d7afad30135.png)

**Comment by irahulranjan** [comment]
Hi @ashameem123, Can you share the implementation of constructLocalStackClient?
Also which version of Localstack are you using. Can you try pulling the latest image and give a shot?
When I run the steps mentioned by you I get the following error.
```
2021-03-03T01:17:30:DEBUG:localstack.services.awslambda.lambda_executors: Lambda executed in Event (asynchronous) mode, no response will be returned to caller
2021-03-03T01:17:30:INFO:localstack.services.awslambda.lambda_executors: Running lambda cmd: docker run -i  -v "/private/var/folders/6s/n58qc5ws68x9dfhl95_j_20h0000gp/T/localstack/zipfile.41a6df8b":/var/task -e S3_BUCKET="$S3_BUCKET" -e TOPIC_ARN="$TOPIC_ARN" -e REDIS_NODE="$REDIS_NODE" -e SNS_SIGNING_REGION="$SNS_SIGNING_REGION" -e S3_KEY_OUTPUT="$S3_KEY_OUTPUT" -e USE_LOCALSTACK="$USE_LOCALSTACK" -e AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID" -e AWS_SECRET_ACCESS_KEY="$AWS_SECRET_ACCESS_KEY" -e AWS_REGION="$AWS_REGION" -e DOCKER_LAMBDA_USE_STDIN="$DOCKER_LAMBDA_USE_STDIN" -e LOCALSTACK_HOSTNAME="$LOCALSTACK_HOSTNAME" -e EDGE_PORT="$EDGE_PORT" -e _HANDLER="$_HANDLER" -e AWS_LAMBDA_FUNCTION_TIMEOUT="$AWS_LAMBDA_FUNCTION_TIMEOUT" -e AWS_LAMBDA_FUNCTION_NAME="$AWS_LAMBDA_FUNCTION_NAME" -e AWS_LAMBDA_FUNCTION_VERSION="$AWS_LAMBDA_FUNCTION_VERSION" -e AWS_LAMBDA_FUNCTION_INVOKED_ARN="$AWS_LAMBDA_FUNCTION_INVOKED_ARN" -e AWS_LAMBDA_COGNITO_IDENTITY="$AWS_LAMBDA_COGNITO_IDENTITY"   --rm "lambci/lambda:java11" "csg.tib.event.s3.publish.function.TiBEventS3Function"
2021-03-03T01:17:35:DEBUG:localstack.services.awslambda.lambda_executors: Lambda arn:aws:lambda:us-east-1:000000000000:function:tib-event-s3-function result / log output:
{"errorType":"io.lettuce.core.RedisConnectionException","errorMessage":"Unable to connect to redis:6379"}
> Unable to connect to redis:6379: io.lettuce.core.RedisConnectionException
> io.lettuce.core.RedisConnectionException: Unable to connect to redis:6379
> 	at io.lettuce.core.RedisConnectionException.create(RedisConnectionException.java:78)
> 	at io.lettuce.core.RedisConnectionException.create(RedisConnectionException.java:56)
> 	at io.lettuce.core.AbstractRedisClient.getConnection(AbstractRedisClient.java:234)
> 	at io.lettuce.core.RedisClient.connect(RedisClient.java:207)
> 	at csg.redis.module.config.dagger.RedisModule.provideRedisConnection(RedisModule.java:76)
> 	at csg.redis.module.config.dagger.RedisModule_ProvideRedisConnectionFactory.provideRedisConnection(RedisModule_ProvideRedisConnectionFactory.java:44)
> 	at csg.redis.module.config.dagger.RedisModule_ProvideRedisConnectionFactory.get(RedisModule_ProvideRedisConnectionFactory.java:34)
> 	at csg.redis.module.config.dagger.RedisModule_ProvideRedisConnectionFactory.get(RedisModule_ProvideRedisConnectionFactory.java:10)
> 	at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
> 	at csg.redis.module.config.dagger.RedisModule_ProvideRedisServiceFactory.get(RedisModule_ProvideRedisServiceFactory.java:35)
> 	at csg.redis.module.config.dagger.RedisModule_ProvideRedisServiceFactory.get(RedisModule_ProvideRedisServiceFactory.java:10)
> 	at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
> 	at csg.tib.event.s3.publish.function.service.TiBEventS3Service_Factory.get(TiBEventS3Service_Factory.java:38)
> 	at csg.tib.event.s3.publish.function.service.TiBEventS3Service_Factory.get(TiBEventS3Service_Factory.java:9)
> 	at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
> 	at csg.tib.event.s3.publish.function.component.DaggerTiBEventS3Component.injectTiBEventS3Function(DaggerTiBEventS3Component.java:91)
> 	at csg.tib.event.s3.publish.function.component.DaggerTiBEventS3Component.inject(DaggerTiBEventS3Component.java:88)
> 	at csg.tib.event.s3.publish.function.TiBEventS3Function.<init>(TiBEventS3Function.java:27)
> 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
> 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
> 	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
> Caused by: java.net.UnknownHostException: redis: Name or service not known
> 	at java.base/java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
> 	at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(Unknown Source)

```

Will it be possible to just share a sample zip that just uploads to S3?

**Comment by ashameem123** [comment]
@irahulranjan - Here is the implementation code for LS client:

![image](https://user-images.githubusercontent.com/54183749/110644156-d4531380-81da-11eb-8b3b-0c14afc813e4.png)

Getting same results after doing - docker pull localstack/localstack

**Comment by macnev2013** [comment]
Hi @ashameem123 , Thanks for reporting.
Can you please check the following things.
- Make sure to properly set the `HOST_TMP_FOLDER` environment variable for the LocalStack container when using `LAMBDA_REMOTE_DOCKER=false`
- Please make sure the `container_name: localstack_main` or add `MAIN_CONTAINER_NAME` in `environment`
- If you are using `non-default edge port` make sure it is exposed in docker-compose
- make sure you are using `network_mode: bridge`

Also, Can you provide us the commands/docker-compose that you have used to start localstack?

Thanks.

**Comment by whummer** [comment]
Closing as "should be fixed" - please let us know if the problem persists with the `latest` Docker image  @ashameem123 (please pull from Docker Hub). Thanks!

**Comment by sparshneel** [comment]
Guys was this issue fixed? I am still getting this with latest localstack docker image
