### ISSUE TITLE
FiFo queue doesn't work as expected when using MessageDeduplicationId

### ISSUE THREAD

**Issue by kzupan** [localstack/localstack#3615]
# Type of request: This is a ...

[x ] bug report
[ ] feature request

# Detailed description
Messages with same `MessageDeduplicationId` and `MessageGroupId` are duplicated in FiFo sqs queue when using latest version of `localstack` docker image.

## Expected behavior
The second message that is send into FiFo queue with same `MessageDeduplicationId` and same `MessageGroupId` should be ignored according to https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/using-messagededuplicationid-property.html.

## Actual behavior
Messages with same `MessageDeduplicationId` and same `MessageGroupId` are duplicated.

# Steps to reproduce

## Command used to start LocalStack

```
version: '3.3'
services:
  localstack:
    container_name: localstack
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - DEFAULT_REGION=eu-west-1
      - SERVICES=sns,sqs
```
### Create FiFo queue:

```
aws sqs create-queue --endpoint-url http://localhost:4566 --queue-name test-queue.fifo --attributes "FifoQueue=true,ContentBasedDeduplication=false"
```

```
{
    "QueueUrl": "http://localhost:4566/000000000000/test-queue.fifo"
}
```

### Check queue attributes
```
aws sqs get-queue-attributes --endpoint-url http://localhost:4566 --queue-url http://localhost:4566/000000000000/test-queue.fifo
```

```
{
    "Attributes": {
        "ApproximateNumberOfMessages": "0",
        "ApproximateNumberOfMessagesDelayed": "0",
        "ApproximateNumberOfMessagesNotVisible": "0",
        "CreatedTimestamp": "1613644673.823228",
        "DelaySeconds": "0",
        "LastModifiedTimestamp": "1613644673.823228",
        "MaximumMessageSize": "262144",
        "MessageRetentionPeriod": "345600",
        "QueueArn": "arn:aws:sqs:eu-west-1:000000000000:test-queue.fifo",
        "ReceiveMessageWaitTimeSeconds": "0",
        "VisibilityTimeout": "30",
        "FifoQueue": "true",
        "ContentBasedDeduplication": "false"
    }
}
```
#### Message 1
```
aws sqs send-message --endpoint-url http://localhost:4566 --queue-url http://localhost:4566/000000000000/test-queue.fifo --message-body="msg1" --message-deduplication-id="dedup" --message-group-id="group"

```

```
{
    "MD5OfMessageBody": "3fccf7e8ef8bb6df5c1a77f579c5b914",
    "MessageId": "6fd015b4-5b3e-b976-fa0d-dacdee031f78"
}
```

#### Message 2

```
aws sqs send-message --endpoint-url http://localhost:4566 --queue-url http://localhost:4566/000000000000/test-queue.fifo --message-body="msg2" --message-deduplication-id="dedup" --message-group-id="group"

```

```
{
    "MD5OfMessageBody": "68b619a68d46df0f5fb66f50b5ccdde1",
    "MessageId": "7f8fa1e7-ae18-7a45-5fc3-33827cc3f9ef"
}
```

## Receive messages
```
aws sqs receive-message --endpoint-url http://localhost:4566 --queue-url http://localhost:4566/000000000000/test-queue.fifo --attribute-names All --message-attribute-names All --max-number-of-messages 10
```

```
{
    "Messages": [
        {
            "MessageId": "6fd015b4-5b3e-b976-fa0d-dacdee031f78",
            "ReceiptHandle": "iqlhsuogcwhzdornfofbazqxrxwnkchkldoxtvcgfaetyncaxvxmeokcstyoqtsgmmueammekeqjhvuaifkxblavxrfiblgwfiwqzgdfmmsdlryjrjajqdascnyomkckksqiwtmjqzxfbbxeranphkfcnbvvgxymgwzxsavmrtksvlffgwaezrzvz",
            "MD5OfBody": "3fccf7e8ef8bb6df5c1a77f579c5b914",
            "Body": "msg1",
            "Attributes": {
                "SenderId": "AIDAIT2UOQQY3AUEKVGXU",
                "SentTimestamp": "1613644919784",
                "ApproximateReceiveCount": "1",
                "ApproximateFirstReceiveTimestamp": "1613644987903",
                "MessageDeduplicationId": "dedup",
                "MessageGroupId": "group"
            }
        },
        {
            "MessageId": "7f8fa1e7-ae18-7a45-5fc3-33827cc3f9ef",
            "ReceiptHandle": "gtodrwqqitrbqdedldkezjxquzdontpjlprekqwicdxgxyrexytdmyabcmhrybvqzoimxblxtpelftawyqxrbayafjnfegwvpahvlviopavfocfjalltgijnokevszhdflfjxsrapaxjldjdkqphfcpwqxlezetkdmiwgioedbocelwqpextltjdy",
            "MD5OfBody": "68b619a68d46df0f5fb66f50b5ccdde1",
            "Body": "msg2",
            "Attributes": {
                "SenderId": "AIDAIT2UOQQY3AUEKVGXU",
                "SentTimestamp": "1613644946176",
                "ApproximateReceiveCount": "1",
                "ApproximateFirstReceiveTimestamp": "1613644987904",
                "MessageDeduplicationId": "dedup",
                "MessageGroupId": "group"
            }
        }
    ]
}
```

**Comment by usmangani1** [comment]
@kzupan  Thanks for reporting the issue. While we tried to reproduce this issue we observed that the "ContentBasedDeduplication" attribute is being set to false.This property has to be set to true for the deduplication to be considered.

I had tried the same set of commands by enabling the "ContentBasedDeduplication" on the queue and the behaviour is as expected.

`usman@Usman ~ % aws sqs create-queue --endpoint-url http://localhost:4566 --queue-name test-queue.fifo --attributes "FifoQueue=true,ContentBasedDeduplication=true"               

{
    "QueueUrl": "http://localhost:4566/000000000000/test-queue.fifo"
}
usman@Usman ~ % aws sqs get-queue-attributes --endpoint-url http://localhost:4566 --queue-url http://localhost:4566/000000000000/test-queue.fifo                                                                            

{
    "Attributes": {
        "ApproximateNumberOfMessages": "0",
        "ApproximateNumberOfMessagesDelayed": "0",
        "ApproximateNumberOfMessagesNotVisible": "0",
        "CreatedTimestamp": "1613890058.48696",
        "DelaySeconds": "0",
        "LastModifiedTimestamp": "1613890058.48696",
        "MaximumMessageSize": "262144",
        "MessageRetentionPeriod": "345600",
        "QueueArn": "arn:aws:sqs:us-east-1:000000000000:test-queue.fifo",
        "ReceiveMessageWaitTimeSeconds": "0",
        "VisibilityTimeout": "30",
        "FifoQueue": "true",
        "ContentBasedDeduplication": "true"
    }
}
usman@Usman ~ % aws sqs send-message --endpoint-url http://localhost:4566 --queue-url http://localhost:4566/000000000000/test-queue.fifo --message-body="msg2" --message-deduplication-id="dedup" --message-group-id="group"

{
    "MD5OfMessageBody": "68b619a68d46df0f5fb66f50b5ccdde1",
    "MessageId": "759f45db-13c9-32e2-23e6-984aae39cd7c"
}
usman@Usman ~ % aws sqs send-message --endpoint-url http://localhost:4566 --queue-url http://localhost:4566/000000000000/test-queue.fifo --message-body="msg2" --message-deduplication-id="dedup" --message-group-id="group"


{
    "MD5OfMessageBody": "68b619a68d46df0f5fb66f50b5ccdde1",
    "MessageId": "01b2331f-aacf-4c7b-7cae-354518bf9faf"
}
usman@Usman ~ % aws sqs receive-message --endpoint-url http://localhost:4566 --queue-url http://localhost:4566/000000000000/test-queue.fifo --attribute-names All --message-attribute-names All --max-number-of-messages 10

{
    "Messages": [
        {
            "MessageId": "759f45db-13c9-32e2-23e6-984aae39cd7c",
            "ReceiptHandle": "gsohnnmkcmyitmjcbepksrybmhctfnnlhxdylihbsgjbvreipxeqndhledhshntsxfmoiiltylxfvjjtcoaaqltkhqcesoulcwhevaknlvksvkqxpeurbkroedxlyrcrnysucnhrzugtnekydmxdzlwjxqpyrcyytvoxngryurljdbbqjoygvmeyy",
            "MD5OfBody": "68b619a68d46df0f5fb66f50b5ccdde1",
            "Body": "msg2",
            "Attributes": {
                "SenderId": "AIDAIT2UOQQY3AUEKVGXU",
                "SentTimestamp": "1613890070548",
                "ApproximateReceiveCount": "1",
                "ApproximateFirstReceiveTimestamp": "1613890078581",
                "MessageDeduplicationId": "dedup",
                "MessageGroupId": "group"
            }
        }
    ]
}`

**Comment by kzupan** [comment]
@usmangani1 According to [documentation](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/FIFO-queues.html#FIFO-queues-exactly-once-processing), you should either have `ContentBasedDeduplication` se to true or send `MessageDeduplicationId` explicitly.

In the first case the body of the message gets hashed and the hash is then compared to previous messages. In the second case only `MessageDeduplicationId` is comprared.

This worked in the previous versions of localstack. Also `ContentBasedDeduplication` is set to false by default on AWS.

Regards

**Comment by kzupan** [comment]
@usmangani1 Can you check again if the implementation is according to the documentation?

**Comment by bhales42** [comment]
This issue needs to be re-opened since the localstack behavior does not match AWS.  Here is the specific documentation:
https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/FIFO-queues-exactly-once-processing.html
```
To configure deduplication, you must do one of the following:
-- Enable content-based deduplication. 
-- Explicitly provide the message deduplication ID
```

**Comment by SleepyBrett** [comment]
Re-open please, localstack is behaving incorrectly.
