### ISSUE TITLE
Can't Disable CloudWatch Events Rule

### ISSUE THREAD

**Issue by scottiemc7** [localstack/localstack#3616]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description
CloudWatch Events rules using schedule expressions do not respect the enabled/disabled property

## Expected behavior
Setting a scheduled rule to DISABLED should disable the event

## Actual behavior
The rule continues to trigger

# Steps to reproduce
Create a rule on a minute schedule 
`awslocal events put-rule --name TestRule --schedule-expression "cron(0/1 * * * ? *)"`

Create an SNS topic as a target
`sns create-topic --name TestTopic`

Assign the target to the rule
`awslocal events put-targets --rule TestRule --targets '"Id"="1","Arn"="arn:aws:sns:us-east-1:000000000000:TestTopic"'`

Disable the rule
`awslocal events disable-rule --name TestRule `

Verify rule is disabled
`awslocal events list-rules`
`RULES   arn:aws:events:us-east-1:000000000000:rule/TestRule     TestRule        cron(0/1 * * * ? *)     DISABLED`
Note that the rule continues to trigger even though the status is set to DISABLED

## Command used to start LocalStack
`docker-compose up`

version: '2.1'

services:

  localstack:
    image: localstack/localstack:latest
    container_name: localstack_main
    ports:
      - "4566:4566"
      - "4567-4584:4567-4584"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=lambda,cloudformation,iam,logs,events,secretsmanager,ssm,sqs,s3,apigateway,stepfunctions,ec2,sns
      - HOSTNAME=localhost
      - START_WEB=0
      - DEBUG=1
      - LAMBDA_EXECUTOR=docker
      - LAMBDA_REMOTE_DOCKER=true
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - ${LOCALSTACK_DIR}/startup:/docker-entrypoint-initaws.d
      - "//var/run/docker.sock:/var/run/docker.sock"

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
`awslocal events put-rule --name TestRule --schedule-expression "cron(0/1 * * * ? *)"`
`awslocal sns create-topic --name TestTopic`
`awslocal events put-targets --rule TestRule --targets '"Id"="1","Arn"="arn:aws:sns:us-east-1:000000000000:TestTopic"'`
`awslocal events disable-rule --name TestRule `

**Comment by whummer** [comment]
Thanks @scottiemc7 @irahulranjan . This should be fixed in #3622 - can you please pull the `latest` Docker image and give it another try? Thanks for your help

**Comment by scottiemc7** [comment]
This seems to work. The only problem I see is that if you create a rule in a disabled state using cloudformation it still continues to fire, but I can work around that by disabling it from the command line. Thank you so much.
