### ISSUE TITLE
s

### ISSUE THREAD

**Issue by steinmaerivoet** [localstack/localstack#3626]
# Type of request: This is a ...

[ ] bug report
[ ] feature request

# Detailed description

...

## Expected behavior

...

## Actual behavior

...

# Steps to reproduce

## Command used to start LocalStack

...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

...

**Comment by whummer** [comment]
Looks like something went wrong when opening this issue, @steinmaerivoet ?
