### ISSUE TITLE
PRO: Support Step Functions as Eventbridge target

### ISSUE THREAD

**Issue by kevindixon** [localstack/localstack#3628]
# Type of request: This is a ...

[ ] bug report
[x] feature request

# Detailed description
Currently, Step Functions as an Eventbridge target is not supported - see https://github.com/localstack/localstack/blob/master/localstack/services/events/events_starter.py#L116

## Expected behavior
A Step Function state machine can be set as an Eventbridge target.

## Actual behavior
`Unsupported Events target service type "states"`

# Steps to reproduce

## Command used to start LocalStack
N/A

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
N/A

**Comment by whummer** [comment]
Thanks for reporting @kevindixon . This should be fixed in #3657 - can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists. Thanks for your help!
