### ISSUE TITLE
Support for intrinsic functions in Step Functions

### ISSUE THREAD

**Issue by scottiemc7** [localstack/localstack#3629]
# Type of request: This is a ...

[ ] bug report
[X] feature request

# Detailed description
When attempting to use an intrinsic function in a state machine, localstack fails with a SCHEMA_VALIDATION_FAILED error. I'm assuming this is because intrinsic functions are not yet supported.

## Expected behavior
The state machine would create without issue. Tested in AWS and this state machine works.

## Actual behavior
SCHEMA_VALIDATION_FAILED: The value for the field '[FIELDNAME].$' must be a valid JSONPath

# Steps to reproduce
Attempt to create a state machine using an intrinsic function.    
Example state machine:
`{
  "Comment": "This state machine causes a SCHEMA_VALIDATION_FAILED error",
  "StartAt": "Hello",
  "States": {
    "Hello": {
      "Type": "Pass",
      "Result": {
        "StringifyMe": {
          "MyKey": "MyValue"
        }
      },
      "Next": "World"
    },
    "World": {
      "Type": "Pass",
      "Parameters": {
        "JsonAsString.$": "States.JsonToString($.StringifyMe)"
      },
      "ResultPath": "$.StringOutput",
      "End": true
    }
  }
}`

## Command used to start LocalStack
`docker-compose up`

version: '2.1'

services:

localstack:
image: localstack/localstack:latest
container_name: localstack_main
ports:
- "4566:4566"
- "4567-4584:4567-4584"
- "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
environment:
- SERVICES=lambda,cloudformation,iam,logs,events,secretsmanager,ssm,sqs,s3,apigateway,stepfunctions,ec2,sns
- HOSTNAME=localhost
- START_WEB=0
- DEBUG=1
- LAMBDA_EXECUTOR=docker
- LAMBDA_REMOTE_DOCKER=true
- DATA_DIR=/tmp/localstack/data
volumes:
- ${LOCALSTACK_DIR}/startup:/docker-entrypoint-initaws.d
- "//var/run/docker.sock:/var/run/docker.sock"

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
Create a role
`awslocal iam create-role --role-name Test --assume-role-policy-document '{\"Version\": \"2012-10-17\", \"Statement\": [{\"Effect\": \"Allow\", \"Principal\": {\"Service\": \"states.amazonaws.com\"}, \"Action\": \"sts:AssumeRole\"} ] }'`

Create a state machine
`awslocal stepfunctions create-state-machine --name Test --definition '{\"Comment\": \"A Hello World example of the Amazon States Language using Pass states\", \"StartAt\": \"Hello\", \"States\": {\"Hello\": {\"Type\": \"Pass\", \"Result\": {\"Hello\": {\"Json\": \"Value\"} }, \"Next\": \"World\"}, \"World\": {\"Type\": \"Pass\", \"Parameters\": {\"NewState.$\": \"States.JsonToString($.Hello)\"}, \"ResultPath\": \"$.Test\", \"End\": true } } }' --role-arn " arn:aws:iam::000000000000:role/Test"`

**Comment by kevindixon** [comment]
I'm similarly using Step Functions state machine with intrinsic functions (particularly `Format`, but pretty much all of them at some point). 
Would be great if Localstack could support them - I'd be using Localstack for both integration testing of state machines and Lambda/ECS and also for local development.

**Comment by danielblignaut** [comment]
I'd suggest using the official local AWS step functions server (use the docker version, the downloadable jar version is very outdated). This supports intrinsic functions currently and with docker-compose, and confinguring the step functions config you should be able to get it to play nicely with the rest of localstack.

I assume localstack uses this docker image unless they have a custom step function implementation. It should just require updating the docker image they use.

**Comment by danielblignaut** [comment]
In fact they're using the local jar file (outdated version) instead of the docker image here https://hub.docker.com/r/amazon/aws-stepfunctions-local

I assume the solution would be to update the code here to use the docker image instead:
https://github.com/localstack/localstack/blob/master/localstack/services/stepfunctions/stepfunctions_starter.py

**Comment by whummer** [comment]
Great, thanks for the pointer @danielblignaut - we'll look into that right away.. 👍

**Comment by whummer** [comment]
@kevindixon @danielblignaut @scottiemc7 This should be fixed in #3642 - StepFunctions intrinsic functions are now available in the `latest` Docker image. Please let us know if there are any other issues. Thanks
