### ISSUE TITLE
Localstack Not Determining Correct URL for Kinesis/Firehose Delivery Stream with Elasticsearch Destination

### ISSUE THREAD

**Issue by andkvo** [localstack/localstack#3630]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

I am trying to set up an elasticsearch domain in localstack and then use that as the delivery destination for kinesis (also in localstack). I've found that I cannot set it up by specifying the elasticsearch domain ARN when configuring the Kinesis/Firehose stream. I can, however, get it to work correctly, if I use the alternate syntax of ClusterEndpoint to set up the stream (and manually specify the port number).

It would appear that localstack is not detecting the endpoint URL correctly. See the `get_elasticsearch_endpoint` method in aws_stack.py. Specifically, I think the es_client.describe_elasticsearch_domain(DomainName=domain) line is not working correctly, but I HAVE NOT verified that. I'm a Python noob.

...

## Expected behavior: Data suppled to `aws kinesis put-record` appears in Elasticsearch index
 
...

### Note the "port 9200" which is not where localstack created the elasticsearch installation.

service-localstack | 2021-02-22T18:52:51:WARNING:localstack.utils.kinesis.kinesis_util: Unable to process JSON line: '{"shard_id": "shardId-000000000000", "records": [{"data": "eyAidGFyZ2V0IjogImJhcnJ5IiB9", "partition...': ConnectionError(MyHTTPConnectionPool(host='localhost', port=9200): Max retries exceeded with url: /activity/activity/c0ada33f-7cc4-4527-ba0c-6c2edea8a69e/_create (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f856854c220>: Failed to establish a new connection: [Errno 111] Connection refused'))) caused by: ConnectionError(MyHTTPConnectionPool(host='localhost', port=9200): Max retries exceeded with url: /activity/activity/c0ada33f-7cc4-4527-ba0c-6c2edea8a69e/_create (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f856854c220>: Failed to establish a new connection: [Errno 111] Connection refused'))) Traceback (most recent call last):
service-localstack |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connection.py", line 169, in _new_conn
service-localstack |     conn = connection.create_connection(
service-localstack |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 96, in create_connection
service-localstack |     raise err
service-localstack |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 86, in create_connection
service-localstack |     sock.connect(sa)
service-localstack | ConnectionRefusedError: [Errno 111] Connection refused
service-localstack |
service-localstack | During handling of the above exception, another exception occurred:
service-localstack |
service-localstack | Traceback (most recent call last):
service-localstack |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
service-localstack |     httplib_response = self._make_request(
service-localstack |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 394, in _make_request
service-localstack |     conn.request(method, url, **httplib_request_kw)
service-localstack |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connection.py", line 234, in request
service-localstack |     super(HTTPConnection, self).request(method, url, body=body, headers=headers)
service-localstack |   File "/usr/lib/python3.8/http/client.py", line 1230, in request
service-localstack |     self._send_request(method, url, body, headers, encode_chunked)
service-localstack |   File "/usr/lib/python3.8/http/client.py", line 1276, in _send_request
service-localstack |     self.endheaders(body, encode_chunked=encode_chunked)
service-localstack |   File "/usr/lib/python3.8/http/client.py", line 1225, in endheaders
service-localstack |     self._send_output(message_body, encode_chunked=encode_chunked)
service-localstack |   File "/usr/lib/python3.8/http/client.py", line 1004, in _send_output
service-localstack |     self.send(msg)
service-localstack |   File "/usr/lib/python3.8/http/client.py", line 944, in send
service-localstack |     self.connect()
service-localstack |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connection.py", line 200, in connect
service-localstack |     conn = self._new_conn()
service-localstack |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connection.py", line 181, in _new_conn
service-localstack |     raise NewConnectionError(
service-localstack | urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f856854c220>: Failed to establish a new connection: [Errno 111] Connection refused

...

# Steps to reproduce

1. Create an Elasticsearch domain
> aws --region us-east-1 --endpoint-url http://localhost:4566 es create-elasticsearch-domain --domain-name es-local --elasticsearch-version 6.7.0

2. Create a Kinesis Delivery Stream with ES as the destination

> aws --region us-east-1 --endpoint-url http://localhost:4566 \
  firehose create-delivery-stream \
  --delivery-stream-name activity-to-elasticsearch-local \
  --delivery-stream-type KinesisStreamAsSource \
  --kinesis-stream-source-configuration "KinesisStreamARN=arn:aws:kinesis:us-east-1:000000000000:stream/activity-local,RoleARN=arn:aws:iam::000000000000:role/Firehose-Reader-Role" \
  --elasticsearch-destination-configuration "RoleARN=arn:aws:iam::000000000000:role/Firehose-Reader-Role,DomainARN=arn:aws:es:us-east-1:000000000000:domain/es-local,IndexName=activity,TypeName=activity,S3Configuration={RoleARN=arn:aws:iam::000000000000:role/Firehose-Reader-Role,BucketARN=arn:aws:s3:::000000000000:kinesis-activity-backup-local,CompressionFormat=UNCOMPRESSED,EncryptionConfiguration={NoEncryptionConfig=NoEncryption},CloudWatchLoggingOptions={Enabled=false}},ProcessingConfiguration={Enabled=false}"

3. Issue Kinesis Put Record Command

aws --endpoint-url http://127.0.0.1:4566 kinesis put-record --stream-name activity-local --data "{ \"target\": \"barry\" }" --partition-key partition

## Command used to start LocalStack

> docker-compose -f docker-compose.localstack.yaml up

...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

...

**Comment by Dgame** [comment]
@andkvo Anything new on this front? I have a similar problem. How did you solve it?

**Comment by mgagliardo** [comment]
Hello @Dgame, @andkvo please refer to [this response](https://github.com/localstack/localstack/issues/4057#issuecomment-845540031) while investigating, the `list-streams` action should show up the right stream name and you should be able to use that one. I'll keep digging into this to see if it is actually a bug. Cheers

**Comment by mgagliardo** [comment]
Forget what I just wrote, found the issue and working on it.

**Comment by mgagliardo** [comment]
This is fixed via the previous response and the linked issue.
