### ISSUE TITLE
Unable to find forwarding rule for host "localhost:4566", path "DELETE 

### ISSUE THREAD

**Issue by kjpaladin** [localstack/localstack#3635]
# Type of request: This is a ...

- [X] bug report

# Detailed description

This is my localstack version

> localstack --version
> 0.12.6.1

I am using the latest version of amazon java sdk
```
<dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-java-sdk-s3</artifactId>
            <version>1.11.959</version>
</dependency>
```
This is my config for aws localstack connection
```
return AmazonS3ClientBuilder.standard()
                .enablePathStyleAccess()
                .withEndpointConfiguration(
                        new AwsClientBuilder.EndpointConfiguration("http://localhost:4566", region)
                )
                .build();
```

**Issue: Deleting an object on the localstack s3 service will produce an error.**

## Expected behavior
No errors and the file should be deleted.

## Actual behavior
INFO:localstack.services.edge: Unable to find forwarding rule for host "localhost:4566", path "DELETE /<_bucket_>/<_filename_>", target header "", auth header "", data "b''"

# Steps to reproduce
Delete an existing file using the aws java sdk.

## Command used to start LocalStack
localstack start

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
`amazonS3.deleteObject(bucket, filename);`

**Comment by macnev2013** [comment]
Thanks for reporting @kjpaladin . We have recently added many improvements in S3. Can you please pull the `latest` docker image and give it another try? Please let us know if the problem persists. Thanks.

**Comment by whummer** [comment]
Closing as should-be-fixed - please let us know if the problem persists @kjpaladin
