### ISSUE TITLE
awslocal redshift invalid xml error 

### ISSUE THREAD

**Issue by 959210490** [localstack/localstack#3637]
Thanks for localstack!
When running the following command:
`awslocal redshift authorize-cluster-security-group-ingress --cluster-security-group-name default --cidrip  192.168.10.0/28`
I get the following error:
`Unable to parse response (syntax error: line 1, column 54), invalid XML received. Further retries may succeed:
b'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">\n<title>500 Internal Server Error</title>\n<h1>Internal Server Error</h1>\n<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>\n'
`

I want to connect redshift by my local serve ，Pass the article
[https://docs.aws.amazon.com/zh_cn/redshift/latest/mgmt/getting-started-cli.html](url)
when I running Step 3 throw Exception 

now I connect the Redshift by local serve , throw Exception 
`[HY000][500150] [Amazon](500150) Error setting/closing connection: The server closed the connection..`

**Comment by whummer** [comment]
Thanks for reporting @959210490 . This should be fixed in the meantime - can you please pull the `latest` Docker image and give it another try? Please report here if the problem persists. Thanks
