### ISSUE TITLE
S3 lifecycle configuration not deleted

### ISSUE THREAD

**Issue by kinbald** [localstack/localstack#3639]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

Hello
After creating an S3 bucket and put a lifecycle configuration. I want to remove it and then remove the bucket.
I execute the AWS Cli command [delete-bucket-lifecycle](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/s3api/delete-bucket-lifecycle.html).

## Expected behavior

Configuration should be removed.

## Actual behavior

Configuration is still present. If you remove the bucket and recreate another one with same name. It will directly have the configuration from the old one.
I assume it should take some time on real AWS S3 to replicate configuration but not in this context.

# Steps to reproduce

## Command used to start LocalStack
`docker-compose up localstack`

`docker-compose.yml`:
```version: '3'
services:
  localstack:
    image: localstack/localstack:0.12.6
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - HOSTNAME=localstack
      - HOSTNAME_EXTERNAL=192.168.10.199
      - DEFAULT_REGION=eu-west-1
      - DEBUG=1
      - DATA_DIR=${DATA_DIR- }
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
 ```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

```
[15:06:53][@/] user@cloud:...docker/war#aws --endpoint-url=http://localhost:4566 s3 mb s3://test
make_bucket: test
[15:07:06][@/] user@cloud:...docker/war#aws --endpoint-url=http://localhost:4566 s3api put-bucket-lifecycle-configuration --bucket test --lifecycle-configuration  file:///tmp/lifecycle.json
[15:07:18][@/] user@cloud:...docker/war#aws --endpoint-url=http://localhost:4566 s3api get-bucket-lifecycle-configuration --bucket test
{
    "Rules": [
        {
            "Expiration": {
                "Days": 1
            },
            "Filter": {
                "Prefix": ""
            },
            "Status": "Enabled"
        }
    ]
}
[15:07:24][@/] user@cloud:...docker/war#aws --endpoint-url=http://localhost:4566 s3api delete-bucket-lifecycle --bucket test
[15:07:31][@/] user@cloud:...docker/war#aws --endpoint-url=http://localhost:4566 s3api get-bucket-lifecycle-configuration --bucket test
{
    "Rules": [
        {
            "Expiration": {
                "Days": 1
            },
            "Filter": {
                "Prefix": ""
            },
            "Status": "Enabled"
        }
    ]
}
```
By the way, is LifeCycle performed in the background or just replies to CLI requests ? 
I mean will this configuration really make objects expires at some point on LocalStack ?

Thanks for your help.

**Comment by whummer** [comment]
Thanks for reporting @kinbald . This should be fixed in the meantime - can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists. Thanks!

> By the way, is LifeCycle performed in the background or just replies to CLI requests ?
> I mean will this configuration really make objects expires at some point on LocalStack ?

At this point, we're simply emulating the CLI response in this case, the objects are currently not really expired. This is primarily due to the fact that LocalStack environments are usually relatively short-lived, hence testing of bucket lifecycle hasn't been a strong requirement for most users. If this is something you think should be added, please feel free to create a new feature request ticket. Thanks

**Comment by kinbald** [comment]
Working as expected, thanks @whummer .
