### ISSUE TITLE
PRO: destroying aws_rds_cluster_parameter_group fails

### ISSUE THREAD

**Issue by blairham** [localstack/localstack#3640]
# Type of request: This is a ...

[X] bug report
[ ] feature request

# Detailed description
I've written a terratest for a module that uses a rds_cluster_parameter_group, which is created successfully. However, on destruction, it does not respond and times out.
...

## Expected behavior
Destroying any resource after a successful creation should respond correctly
...

## Actual behavior
destroy fails to respond and causes a timeout
```
TestExamplesComplete 2021-02-24T10:30:58-05:00 logger.go:66: module.rds_cluster.aws_rds_cluster_parameter_group.default: Still destroying... [id=test, 3m20s elapsed]
...
TestExamplesComplete 2021-02-24T10:31:08-05:00 logger.go:66: Error: timeout while waiting for state to become 'destroyed' (timeout: 3m0s)
```
...

# Steps to reproduce
create a simple resource
```
resource "aws_rds_cluster_parameter_group" "default" {
  name        = "test"
  description = "DB cluster parameter group"
  family      = "aurora-mysql5.7"
}

run terraform apply, then terraform destroy
```

## Command used to start LocalStack
I'm using the localstack helm chart to run it in a k8s with port forwarding
[done] √ Deployed helm chart (Release revision: 1)
[done] √ Successfully deployed localstack with helm
[done] √ Port forwarding started on 4566:4566, 4571:4571 (localstack/localstack-b8cc784cf-vrjtr)

Waiting for all LocalStack services to be ready
Starting mock Cloudwatch Events service on http ports 443/4566 ...
Starting mock StepFunctions service on http ports 443/4566 ...
Starting mock SWF service on http ports 443/4566 ...
2021-02-24T15:26:01:INFO:botocore.credentials: Found credentials in environment variables.
Waiting for all LocalStack services to be ready
Ready.
...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

...

**Comment by whummer** [comment]
Thanks for reporting @blairham. This should be fixed in the meantime - can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists. Thanks for your help!
