### ISSUE TITLE
[PRO] AWS::Lambda::EventInvokeConfig unsupported in CloudFormation

### ISSUE THREAD

**Issue by Exgaves** [localstack/localstack#3648]
# Type of request: This is a ...

[x ] bug report
[ ] feature request

# Detailed description
Currently Serverless supports easy configuration of a Lambda to have 2 important properties, maximumEventAge and maximumRetryAttempts. For some systems these are imperative points of configuration.
When Serverless deploys to Localstack the CloudFormation template produced puts these properties in a resource called [AWS::Lambda::EventInvokeConfig](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-eventinvokeconfig.html). When Localstack parses a CloudFormation template including this resource the stack fails as Localstack does not support this type.
...

## Expected behavior
Localstack supports the CloudFormation resource AWS::Lambda::EventInvokeConfig or at least does not fail when recieving it.
...

## Actual behavior
Localstack produces an error such as the following and fails to produce that stack in CloudFormation.
```
2021-02-26T01:07:21:WARNING:localstack.utils.cloudformation.template_deployer: Unexpected resource type Lambda::EventInvokeConfig when resolving references of resource TestFunctionLambdaEvConf: {'Type': 'AWS::Lambda::EventInvokeConfig', 'LogicalResourceId': 'TestFunctionLambdaEvConf', 'Properties': {'FunctionName': 'some-service-local-TestFunction', 'DestinationConfig': {}, 'Qualifier': '$LATEST', 'MaximumEventAgeInSeconds': 60, 'MaximumRetryAttempts': 2}, 'PhysicalResourceId': None}
```
...

# Steps to reproduce

1. Create a Serverless Lambda (JavaScript specifically for me)
2. Install localstack plugin
2. Configure the Lambda function to have either or both **maximumEventAge** and **maximumRetryAttempts**
3. Attempt to deploy the Lambda function to localstack.
4. Check Localstack logs.

## Command used to start LocalStack

Started via a docker-compose.yml file.
`docker-compose -f "./docker-compose.yml" up -d --build --force-recreate localstack`

```
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    hostname: localstack.localhost.com
    networks:
      - mynetwork
    ports:
      - "4566:4566"
      - "433:433"
      - "4510:4510"
    environment:
      - LAMBDA_EXECUTOR=docker
      - LAMBDA_REMOTE_DOCKER=true
      - LAMBDA_REMOVE_CONTAINERS=true
      - LAMBDA_DOCKER_NETWORK=mynetwork
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY}
      - SERVICES=dynamodb,sqs,sns,s3,cloudformation,elasticache,rds,serverless
      - DEFAULT_REGION=us-west-2
      - DEBUG=${DEBUG- }
      - MAIN_CONTAINER_NAME=localstack
      - HOSTNAME=localstack.localhost.com
      - HOSTNAME_EXTERNAL=localstack.localhost.com
      - LOCALSTACK_HOSTNAME=localstack.localhost.com
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    healthcheck:
      test: "curl --fail --request GET http://localhost:4566/health || exit 1"
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 120s
```

...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

...

**Comment by whummer** [comment]
Thanks for reporting @Exgaves . This should be fixed in #3650 - can you please pull the `latest` Docker image and give it another try? Please report here if the problem persists. Thanks for your help!
