### ISSUE TITLE
CW Events rule targets unhooked after update

### ISSUE THREAD

**Issue by scottiemc7** [localstack/localstack#3652]
# Type of request: This is a ...

[X ] bug report
[ ] feature request

# Detailed description
When updating an existing CloudWatch Events rule, the targets of the rule are removed.

## Expected behavior
In AWS, updating a CWE rule does not remove the rule targets.

## Actual behavior
The CWE rule targets are removed.

# Steps to reproduce
Create a rule
`awslocal events put-rule --name TestRule --schedule-expression "cron(0/1 * * * ? *)"`

Create an SNS topic as a target
`awslocal sns create-topic --name TestTopic`

Assign the target to the rule
`awslocal events put-targets --rule TestRule --targets '"Id"="1","Arn"="arn:aws:sns:us-east-1:000000000000:TestTopic"'`

Note the rule targets
`awslocal events list-targets-by-rule --rule TestRule`

Update the rule
`awslocal events put-rule --name TestRule --schedule-expression "cron(0/2 * * * ? *)"`

Note the rule targets are missing
`awslocal events list-targets-by-rule --rule TestRule`

## Command used to start LocalStack
`docker-compose up`

version: '2.1'

services:

localstack:
image: localstack/localstack:latest
container_name: localstack_main
ports:
- "4566:4566"
- "4567-4584:4567-4584"
- "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
environment:
- SERVICES=lambda,cloudformation,iam,logs,events,secretsmanager,ssm,sqs,s3,apigateway,stepfunctions,ec2,sns
- HOSTNAME=localhost
- START_WEB=0
- DEBUG=1
- LAMBDA_EXECUTOR=docker
- LAMBDA_REMOTE_DOCKER=true
- DATA_DIR=/tmp/localstack/data
volumes:
- ${LOCALSTACK_DIR}/startup:/docker-entrypoint-initaws.d
- "//var/run/docker.sock:/var/run/docker.sock"

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
`awslocal events put-rule --name TestRule --schedule-expression "cron(0/1 * * * ? *)"`
`awslocal sns create-topic --name TestTopic`
`awslocal events put-targets --rule TestRule --targets '"Id"="1","Arn"="arn:aws:sns:us-east-1:000000000000:TestTopic"'`
`awslocal events put-rule --name TestRule --schedule-expression "cron(0/2 * * * ? *)"`

**Comment by whummer** [comment]
Thanks for reporting @scottiemc7 . This should be fixed in the meantime - can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists. Thanks!
