### ISSUE TITLE
Cloudformation - AWS::SecretsManager::Secret resource inconsistencies

### ISSUE THREAD

**Issue by scottiemc7** [localstack/localstack#3653]
# Type of request: This is a ...

[X] bug report
[ ] feature request

# Detailed description
There seem to be two inconsistencies in how localstack handles the  AWS::SecretsManager::Secret resource in Cloudformation.

1.  A `Ref` returns a resource name [instead of an ARN](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-secretsmanager-secret.html#aws-resource-secretsmanager-secret-return-values).
2. The `Name` property is required, but [shouldn't be](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-secretsmanager-secret.html#cfn-secretsmanager-secret-name).

The workaround for 1 is to use the `Fn::GetAtt` function to retrieve the ARN.

## Expected behavior
The stack should create successfully.

## Actual behavior
The stack fails to create.

# Steps to reproduce
Attempt to create a Cloudformation stack with the `bad.template` template.
`awslocal cloudformation create-stack --stack-name "OhNoes" --template-body file://bad.template`

`good.template` is a working example using `Fn::GetAtt` to get the secret ARN and specifying the `Name` property.
`awslocal cloudformation create-stack --stack-name "OhGood" --template-body file://good.template`

#### Templates
[templates.zip](https://github.com/localstack/localstack/files/6052615/templates.zip)

## Command used to start LocalStack
`docker-compose up`

version: '2.1'

services:

localstack:
image: localstack/localstack:latest
container_name: localstack_main
ports:

    "4566:4566"
    "4567-4584:4567-4584"
    "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
    SERVICES=lambda,cloudformation,iam,logs,events,secretsmanager,ssm,sqs,s3,apigateway,stepfunctions,ec2,sns
    HOSTNAME=localhost
    START_WEB=0
    DEBUG=1
    LAMBDA_EXECUTOR=docker
    LAMBDA_REMOTE_DOCKER=true
    DATA_DIR=/tmp/localstack/data
    volumes:
    ${LOCALSTACK_DIR}/startup:/docker-entrypoint-initaws.d
    "//var/run/docker.sock:/var/run/docker.sock"

**Comment by usmangani1** [comment]
@scottiemc7 Thanks for reporting the issue.
We tried to reproduce this on the latest version of localstack and the stack is being created successfully for both the templates.Can you please try this on the new version of localstack ?

```
usman@moto % awslocal cloudformation create-stack --stack-name "OhNoes" --template-body file://bad_template.json


{
    "StackId": "arn:aws:cloudformation:us-east-1:000000000000:stack/OhNoes/4353e6b4"
}
usman@moto % awslocal cloudformation create-stack --stack-name "OhGood" --template-body file://good_template.json


{
    "StackId": "arn:aws:cloudformation:us-east-1:000000000000:stack/OhGood/72bfbd2a"
}
```

**Comment by scottiemc7** [comment]
I will try again on Monday and let you know. Thanks for looking into it.

**Comment by usmangani1** [comment]
@scottiemc7  Did you get a chance to try this out ?

**Comment by scottiemc7** [comment]
I tried creating the stack using localstack 0.12.10 and it seems to be working now. Thank you for your help!
