### ISSUE TITLE
Unsupported authorizer type: REQUEST

### ISSUE THREAD

**Issue by andres-bayon** [localstack/localstack#3656]
# Type of request: This is a ...

- [ ] bug report
- [x] feature request

# Detailed description

Using PRO version, when I create a Custom Lambda Authorizer with type `REQUEST` I get an error saying it is not supported.

## Expected behavior

Lambda authorizer is called.

## Actual behavior

Lambda authorizer is not called and I get the following warning:

```
WARNING:localstack_ext.services.apigateway.apigateway_extended: Unsupported authorizer type: "REQUEST"
```
# Steps to reproduce

## Command used to start LocalStack
```
version: '2.1'

services:
  localstack:
    image: localstack/localstack-full:latest
    ports:
      - "4510-4520:4510-4520"
      - "4566-4620:4566-4620"
    environment:
      - LOCALSTACK_API_KEY=gTeGVq8UUe
      - SERVICES=serverless,ssm
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOSTNAME_EXTERNAL=localstack
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
````
```
TMPDIR=/private$TMPDIR docker-compose up
```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

This is the CloudFormation part of the template I use to create the Authorizer:

```json
{
"AuthorizerApiGatewayAuthorizer": {
      "Type": "AWS::ApiGateway::Authorizer",
      "Properties": {
        "AuthorizerResultTtlInSeconds": 300,
        "IdentitySource": "method.request.header.Authorization",
        "Name": "authorizer",
        "RestApiId": {
          "Ref": "ApiGatewayRestApi"
        },
        "AuthorizerUri": {
          "Fn::Join": [
            "",
            [
              "arn:",
              {
                "Ref": "AWS::Partition"
              },
              ":apigateway:",
              {
                "Ref": "AWS::Region"
              },
              ":lambda:path/2015-03-31/functions/",
              {
                "Fn::GetAtt": [
                  "AuthorizerLambdaFunction",
                  "Arn"
                ]
              },
              "/invocations"
            ]
          ]
        },
        "Type": "REQUEST"
      }
    },
}
```

**Comment by whummer** [comment]
Thanks for reporting this issue @andres-bayon , and apologies for the long delay. This should be fixed in the meantime - can you please pull the `latest` Docker image and give it another try? Please let us know if there are any issues. Thanks for your help!

**Comment by andres-bayon** [comment]
> Thanks for reporting this issue @andres-bayon , and apologies for the long delay. This should be fixed in the meantime - can you please pull the `latest` Docker image and give it another try? Please let us know if there are any issues. Thanks for your help!

Sorry, but I have tried again with the latest image and I get the same error.
