### ISSUE TITLE
Managed policies fail to validate

### ISSUE THREAD

**Issue by xyloponion** [localstack/localstack#3658]
**# Type of request: This is a ...**

[X ] bug report
[ ] feature request

**# Detailed description**

When any ManagedPolicy resource is specified in either a YAML or JSON file, the stack will fail to create with a validation error.  This will fail using the latest version of localstack, but will succeed using earlier versions.

**## Expected behavior**

The stack should be created successfully.

**## Actual behavior**

The stack fails to be created, and fails with the following validation validation error:

_An error occurred (ValidationError) when calling the CreateStack operation: Unable to create stack "MyNewStack": Unable to parse response (not well-formed (invalid token): line 1, column 0), invalid XML received. Further retries may succeed:
b'{}'_

**# Steps to reproduce**

Attempt to create a stack using a template that specifies any ManagedPolicy resource.

Please see attached file 'sample.txt' for an example YAML creation file that can be used to replicate this issue.
[sample.txt](https://github.com/localstack/localstack/files/6059858/sample.txt)

Create the stack using:

`aws cloudformation create-stack --endpoint-url=http://localhost:4566 --stack-name MyNewStack --template-body file://sample.yml`

**Comment by mgagliardo** [comment]
Hello @xyloponion, can you please pull the `latest` docker image and give a try again? I have tested this locally using your `sample.txt` without issues:

```
$ awslocal cloudformation create-stack --stack-name MyNewStack --template-body file://sample.txt
{
    "StackId": "arn:aws:cloudformation:us-east-1:000000000000:stack/MyNewStack/b8c2914b"
}
```
```
$ awslocal cloudformation list-stacks
{
    "StackSummaries": [
        {
            "StackId": "arn:aws:cloudformation:us-east-1:000000000000:stack/MyNewStack/b8c2914b",
            "StackName": "MyNewStack",
            "CreationTime": "2021-03-01T09:26:37.884Z",
            "StackStatus": "CREATE_COMPLETE"
        }
    ]
}
```
```
$ awslocal cloudformation describe-stacks --stack-name MyNewStack
{
    "Stacks": [
        {
            "StackId": "arn:aws:cloudformation:us-east-1:000000000000:stack/MyNewStack/b8c2914b",
            "StackName": "MyNewStack",
            "Parameters": [
                {
                    "ParameterKey": "EnvironmentCode",
                    "ParameterValue": "dev"
                }
            ],
            "CreationTime": "2021-03-01T09:26:37.884Z",
            "StackStatus": "CREATE_COMPLETE",
            "Capabilities": [],
            "Outputs": [],
            "Tags": []
        }
    ]
}
```

```
Ready.
2021-03-01T09:26:17:INFO:localstack.utils.analytics.profiler: Execution of "start_api_services" took 6096.2889194488525ms



2021-03-01T09:26:37:DEBUG:localstack.services.cloudformation.cloudformation_api: Creating stack "MyNewStack" with 1 resources ...
2021-03-01T09:26:42:DEBUG:localstack.utils.cloudformation.template_deployer: Handling "Add" for resource "ManagedPolicy" (1/2) type "AWS::IAM::ManagedPolicy" in loop iteration 1
2021-03-01T09:26:42:DEBUG:localstack.utils.cloudformation.template_deployer: Running action "create" for resource type "IAM::ManagedPolicy" id "ManagedPolicy"
2021-03-01T09:26:42:DEBUG:localstack.utils.cloudformation.template_deployer: Action "update" not yet implemented for CF resource type AWS::IAM::ManagedPolicy
2021-03-01T09:26:42:DEBUG:localstack.utils.cloudformation.template_deployer: Handling "Modify" for resource "ManagedPolicy" (1/1) type "AWS::IAM::ManagedPolicy" in loop iteration 1
```

**Comment by mgagliardo** [comment]
Now that I'm reading closely, I can see the error you are seeing is (probably) because of a malformed JSON, however I have parsed the YAML you have brought and looks good. Please double check that as well? Thanks

**Comment by xyloponion** [comment]
Hi Miguel,

Nope, I still have the same issue.  Doesn't work when I use latest, does
work when I use an earlier version.

I have tried this with other yaml files also, and can confirm it definitely
does not work.

Regards,
Matt Vermeulen

**Comment by mgagliardo** [comment]
Hey Matt, any chance you can show the output of:
- How are you starting the localstack container
- The output of the container (please enable DEBUG=1)
- The output of the aws cli with --debug flag.

This would help us with further debugging.
Thanks

**Comment by xyloponion** [comment]
Hi Miguel,

Here's the container log with debug flag set:
[container_log.txt](https://github.com/localstack/localstack/files/6066478/container_log.txt)

Also, here's a zip file with a sample docker compose setup that highlights the issue.  Note:  in the 'tester.yml' file, if you change the image from **localstack:latest** to **localstack:0.12.2** it will work.

[localstack_test.zip](https://github.com/localstack/localstack/files/6066481/localstack_test.zip)

Cheers,
Matt

**Comment by mgagliardo** [comment]
Found the issue, line 15 of your docker compose, you are missing `SERVICES=iam`, please check the error log line:

```
localstack_test     | localstack.utils.server.http2_server.HTTPErrorResponse: Unable to find listener for service "iam" - please make sure to include it in $SERVICES
```

So your `docker-compse.yml` should look like this:
```
version: '3.4'

networks:
  localstack_test_network:

services:
  
  localstack:
    image: localstack/localstack:latest
    container_name: localstack_test
    ports:
      - "4563-4584:4563-4584"
      - "8050:8080"
    environment:
      - SERVICES=s3,dynamodb,cloudformation,secretsmanager,iam
      - DEFAULT_REGION=us-east-1
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    networks:
      - localstack_test_network
      
  localstack.setup:
    image: atlassian/pipelines-awscli:latest
    volumes:
      - "./src:/var/setup"
    environment:
      - AWS_ACCESS_KEY_ID=dummyaccess
      - AWS_SECRET_ACCESS_KEY=dummysecret
      - AWS_DEFAULT_REGION=us-east-1
      - http_proxy=
      - https_proxy=
      - DEBUG=1
    networks:
      - localstack_test_network
    depends_on:
      - localstack
    entrypoint: /bin/sh -c
    command: >
      "
      sleep 10;
      aws cloudformation create-stack --debug --endpoint-url=http://localstack:4566 --stack-name MyNewStack --template-body file:///var/setup/sample.yml --parameters ParameterKey=EnvironmentCode,ParameterValue=local
      "
```

Debug logs (working):
[debug_logs.log](https://github.com/localstack/localstack/files/6067822/debug_logs.log)

**Comment by xyloponion** [comment]
Hi Miguel,

Thanks a lot for your time on this.  It is much appreciated.

Regards,
Matt

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
