### ISSUE TITLE
Unable to start localstack

### ISSUE THREAD

**Issue by g-one** [localstack/localstack#366]
installed localstack with the following command:
pip install --user localstack --ignore-installed six
Following is the log:
Collecting localstack
Requirement already satisfied: xmltodict==0.10.2 in /Library/Python/2.7/site-packages (from localstack)
Requirement already satisfied: nose==1.3.7 in /Library/Python/2.7/site-packages (from localstack)
Requirement already satisfied: boto3==1.4.4 in /Library/Python/2.7/site-packages (from localstack)
Requirement already satisfied: psutil==5.2.0 in /Library/Python/2.7/site-packages (from localstack)
Requirement already satisfied: localstack-ext in /Library/Python/2.7/site-packages (from localstack)
Collecting six==1.10.0 (from localstack)
  Using cached six-1.10.0-py2.py3-none-any.whl
Requirement already satisfied: subprocess32-ext==3.2.8.2 in /Library/Python/2.7/site-packages (from localstack)
Requirement already satisfied: flask==0.10.1 in /Library/Python/2.7/site-packages (from localstack)
Requirement already satisfied: requests-aws4auth==0.9 in /Library/Python/2.7/site-packages (from localstack)
Requirement already satisfied: pyYAML==3.12 in /Library/Python/2.7/site-packages (from localstack)
Requirement already satisfied: flask-swagger==0.2.12 in /Library/Python/2.7/site-packages (from localstack)
Requirement already satisfied: flake8==3.4.1 in /Library/Python/2.7/site-packages (from localstack)
Requirement already satisfied: requests==2.18.4 in /Library/Python/2.7/site-packages (from localstack)
Requirement already satisfied: elasticsearch==5.3.0 in /Library/Python/2.7/site-packages (from localstack)
Requirement already satisfied: python-coveralls==2.7.0 in /Library/Python/2.7/site-packages (from localstack)
Collecting pyOpenSSL==17.0.0 (from localstack)
  Using cached pyOpenSSL-17.0.0-py2.py3-none-any.whl
Requirement already satisfied: coverage==4.0.3 in /Library/Python/2.7/site-packages (from localstack)
Collecting docopt==0.6.2 (from localstack)
Collecting flask-cors==3.0.3 (from localstack)
  Using cached Flask_Cors-3.0.3-py2.py3-none-any.whl
Collecting jsonpath-rw==1.4.0 (from localstack)
Collecting moto-ext==1.1.5 (from localstack)
  Using cached moto_ext-1.1.5-py2.py3-none-any.whl
Collecting awscli==1.11.86 (from localstack)
  Using cached awscli-1.11.86-py2.py3-none-any.whl
Collecting boto==2.46.1 (from localstack)
  Using cached boto-2.46.1-py2.py3-none-any.whl
Collecting airspeed==0.5.5.dev20160812 (from localstack)
Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in /Library/Python/2.7/site-packages (from boto3==1.4.4->localstack)
Requirement already satisfied: s3transfer<0.2.0,>=0.1.10 in /Library/Python/2.7/site-packages (from boto3==1.4.4->localstack)
Collecting botocore<1.6.0,>=1.5.0 (from boto3==1.4.4->localstack)
  Using cached botocore-1.5.95-py2.py3-none-any.whl
Requirement already satisfied: srp-ext==1.0.7.1 in /Library/Python/2.7/site-packages (from localstack-ext->localstack)
Requirement already satisfied: dnslib==0.9.7 in /Library/Python/2.7/site-packages (from localstack-ext->localstack)
Requirement already satisfied: warrant-ext>=0.2.0.3 in /Library/Python/2.7/site-packages (from localstack-ext->localstack)
Requirement already satisfied: pyaes==1.6.0 in /Library/Python/2.7/site-packages (from localstack-ext->localstack)
Requirement already satisfied: pyminifier==2.1 in /Library/Python/2.7/site-packages (from localstack-ext->localstack)
Requirement already satisfied: itsdangerous>=0.21 in /Library/Python/2.7/site-packages (from flask==0.10.1->localstack)
Requirement already satisfied: Werkzeug>=0.7 in /Library/Python/2.7/site-packages (from flask==0.10.1->localstack)
Requirement already satisfied: Jinja2>=2.4 in /Library/Python/2.7/site-packages (from flask==0.10.1->localstack)
Requirement already satisfied: pycodestyle<2.4.0,>=2.0.0 in /Library/Python/2.7/site-packages (from flake8==3.4.1->localstack)
Requirement already satisfied: enum34; python_version < "3.4" in /Library/Python/2.7/site-packages (from flake8==3.4.1->localstack)
Requirement already satisfied: configparser; python_version < "3.2" in /Library/Python/2.7/site-packages (from flake8==3.4.1->localstack)
Requirement already satisfied: pyflakes<1.6.0,>=1.5.0 in /Library/Python/2.7/site-packages (from flake8==3.4.1->localstack)
Requirement already satisfied: mccabe<0.7.0,>=0.6.0 in /Library/Python/2.7/site-packages (from flake8==3.4.1->localstack)
Requirement already satisfied: idna<2.7,>=2.5 in /Library/Python/2.7/site-packages (from requests==2.18.4->localstack)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /Library/Python/2.7/site-packages (from requests==2.18.4->localstack)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Python/2.7/site-packages (from requests==2.18.4->localstack)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /Library/Python/2.7/site-packages (from requests==2.18.4->localstack)
Requirement already satisfied: sh in /Library/Python/2.7/site-packages (from python-coveralls==2.7.0->localstack)
Requirement already satisfied: cryptography>=1.7 in /Library/Python/2.7/site-packages (from pyOpenSSL==17.0.0->localstack)
Collecting decorator (from jsonpath-rw==1.4.0->localstack)
  Using cached decorator-4.1.2-py2.py3-none-any.whl
Collecting ply (from jsonpath-rw==1.4.0->localstack)
Collecting cookies (from moto-ext==1.1.5->localstack)
  Using cached cookies-2.2.1-py2.py3-none-any.whl
Collecting dicttoxml (from moto-ext==1.1.5->localstack)
Requirement already satisfied: mock in /Library/Python/2.7/site-packages (from moto-ext==1.1.5->localstack)
Requirement already satisfied: pytz in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from moto-ext==1.1.5->localstack)
Collecting pyaml (from moto-ext==1.1.5->localstack)
  Using cached pyaml-17.8.0-py2.py3-none-any.whl
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /Library/Python/2.7/site-packages (from moto-ext==1.1.5->localstack)
Collecting rsa<=3.5.0,>=3.1.2 (from awscli==1.11.86->localstack)
  Using cached rsa-3.4.2-py2.py3-none-any.whl
Requirement already satisfied: docutils>=0.10 in /Library/Python/2.7/site-packages (from awscli==1.11.86->localstack)
Collecting colorama<=0.3.7,>=0.2.5 (from awscli==1.11.86->localstack)
  Using cached colorama-0.3.7-py2.py3-none-any.whl
Collecting cachetools==0.8.0 (from airspeed==0.5.5.dev20160812->localstack)
  Using cached cachetools-0.8.0-py2.py3-none-any.whl
Requirement already satisfied: futures<4.0.0,>=2.2.0; python_version == "2.6" or python_version == "2.7" in /Library/Python/2.7/site-packages (from s3transfer<0.2.0,>=0.1.10->boto3==1.4.4->localstack)
Requirement already satisfied: envs>=0.3.0 in /Library/Python/2.7/site-packages (from warrant-ext>=0.2.0.3->localstack-ext->localstack)
Requirement already satisfied: python-jose-ext>=1.3.2.2 in /Library/Python/2.7/site-packages (from warrant-ext>=0.2.0.3->localstack-ext->localstack)
Requirement already satisfied: MarkupSafe>=0.23 in /Library/Python/2.7/site-packages (from Jinja2>=2.4->flask==0.10.1->localstack)
Requirement already satisfied: ipaddress in /Library/Python/2.7/site-packages (from cryptography>=1.7->pyOpenSSL==17.0.0->localstack)
Requirement already satisfied: asn1crypto>=0.21.0 in /Library/Python/2.7/site-packages (from cryptography>=1.7->pyOpenSSL==17.0.0->localstack)
Requirement already satisfied: cffi>=1.7 in /Library/Python/2.7/site-packages (from cryptography>=1.7->pyOpenSSL==17.0.0->localstack)
Requirement already satisfied: funcsigs>=1; python_version < "3.3" in /Library/Python/2.7/site-packages (from mock->moto-ext==1.1.5->localstack)
Requirement already satisfied: pbr>=0.11 in /Library/Python/2.7/site-packages (from mock->moto-ext==1.1.5->localstack)
Collecting pyasn1>=0.1.3 (from rsa<=3.5.0,>=3.1.2->awscli==1.11.86->localstack)
  Using cached pyasn1-0.3.6-py2.py3-none-any.whl
Requirement already satisfied: future<1.0 in /Library/Python/2.7/site-packages (from python-jose-ext>=1.3.2.2->warrant-ext>=0.2.0.3->localstack-ext->localstack)
Requirement already satisfied: pycryptodome<3.4.0,>=3.3.1 in /Library/Python/2.7/site-packages (from python-jose-ext>=1.3.2.2->warrant-ext>=0.2.0.3->localstack-ext->localstack)
Requirement already satisfied: ecdsa<1.0 in /Library/Python/2.7/site-packages (from python-jose-ext>=1.3.2.2->warrant-ext>=0.2.0.3->localstack-ext->localstack)
Requirement already satisfied: pycparser in /Library/Python/2.7/site-packages (from cffi>=1.7->cryptography>=1.7->pyOpenSSL==17.0.0->localstack)
Installing collected packages: six, pyOpenSSL, docopt, flask-cors, decorator, ply, jsonpath-rw, cookies, dicttoxml, boto, pyaml, moto-ext, botocore, pyasn1, rsa, colorama, awscli, cachetools, airspeed, localstack
Successfully installed airspeed-0.5.5.dev20160812 awscli-1.11.86 boto-2.46.1 botocore-1.5.95 cachetools-0.8.0 colorama-0.3.7 cookies-2.2.1 decorator-4.1.2 dicttoxml-1.7.4 docopt-0.6.2 flask-cors-3.0.3 jsonpath-rw-1.4.0 localstack-0.8.0 moto-ext-1.1.5 ply-3.10 pyOpenSSL-17.0.0 pyaml-17.8.0 pyasn1-0.3.6 rsa-3.4.2 six-1.10.0

When i try to run localstack start, im getting the following error:
localstack start
-bash: localstack: command not found

**But when i do** 
 **pip search localstack**
awscli-local (0.4)        - Thin wrapper around the "aws" command line interface for use with LocalStack
localstack-client (0.3)   - A lightweight python client for LocalStack.
localstack-ext (0.7.0.7)  - Extensions for LocalStack
  INSTALLED: 0.7.0.7 (latest)
localstack (0.8.0)        - An easy-to-use test/mocking framework for developing Cloud applications
  INSTALLED: 0.8.0 (latest)
Anything i'm missing here? Any help is much appreciated.

Thanks,
Jeevan

**Comment by whummer** [comment]
Thanks for reporting @g-one . Looks like your Python environment is not configured correctly, the `$PATH` environment variable should contain a path to the Python `bin` folder. Which operating system are you on? I'm assuming Mac Os (or Linux) in the instructions below.

You can print the `PATH` using:
```
echo $PATH
```
It should normally contain a path similar to `/Users/__your_username__/Library/Python/2.7/bin`. You can extend your `~/.profile` file and add a new line to it. Note that the actual path may vary depending on your local Python installation.
```
export PATH=/Users/__your_username__/Library/Python/2.7/bin:$PATH
```
Then open a new terminal window, and the path should be set correctly.

**Comment by g-one** [comment]
@whummer Appreciate your response. 
with echo $PATH, Python location as: 
 /Library/Frameworks/Python.framework/Versions/3.6/bin

Now i was able to get through this problem by uninstalling pip and installed localstack with pip2 and it did worked.

But now i'm facing a new issue. Will create a new thread.
Thank You
Jeevan

**Comment by kishorkumarravi** [comment]
"pip3 install localstack"  works!!

**Comment by Ahulkv** [comment]
I tried installing with pip3 but installation was successfull but could not start it with localstack start command

**Comment by rashthedude** [comment]
I'm facing the same issue. Any pointers?

**Comment by gabriel-os-sousa** [comment]
> I tried installing with pip3 but installation was successfull but could not start it with localstack start command

@Ahulkv @rashthedude 

[Try this](https://stackoverflow.com/a/68734093). It worked for me!

**Comment by Yasas4D** [comment]
As @whummer  suggests, you need to set the $PATH environment variable properly as it should contain a path to the Python bin folder. It's in `/home/user/.local/bin` Also, Check the localstack is there!

![image](https://user-images.githubusercontent.com/49401137/159231381-1349fdcf-21cd-4e2b-b0da-b049046c5a38.png)

**Comment by AlexeyInc** [comment]
@Yasas4D Thanks a lot! 
You comment is really helpful
