### ISSUE TITLE
Kinesis - Latency in GetRecords and PutRecords

### ISSUE THREAD

**Issue by sidharthjs** [localstack/localstack#3660]
# Type of request: This is a ...

[ ] bug report
[X] feature request

# Detailed description
Feature request:
It would be great if we have the mechanism to introduce failures or delays for the GetRecords and PutRecords API. This will provide a mechanism to do fault injection on the Kinesis component. 

I had a chance to work on fault testing the Kinesis dependency of a service and I found no tool to inject abort or delay faults for Kinesis. My intention is to make the GetRecords or PutRecords to fail and see how the service behaves. I noticed the `KINESIS_LATENCY ` environment variable and I initially thought that that could serve my purpose but it looks like it just mimicks the response of the GetRecords or PutRecords call whereas my requirement is to fail or delay those 2 Kinesis APIs.

I would like to get a clarification too about the `KINESIS_LATENCY` env variable here. Is my observation and understanding right about this env variable? Please let me know if `KINESIS_LATENCY` can do more than this.
...

## Expected behavior

...

## Actual behavior

...

# Steps to reproduce

## Command used to start LocalStack

...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

...

**Comment by SwatsonCodes** [comment]
Hi @sidharthjs , you can intentionally inject Kinesis errors using the `KINESIS_ERROR_PROBABILITY` environment variable. Please find documentation for this variable as well as the `KINESIS_LATENCY` variable here:
https://docs.localstack.cloud/aws/kinesis/
If you need further clarification around these behaviors please feel free to reopen this issue.
