### ISSUE TITLE
Cloudformation - StateMachine dependencies cause exception

### ISSUE THREAD

**Issue by scottiemc7** [localstack/localstack#3661]
# Type of request: This is a ...

[X] bug report
[ ] feature request

# Detailed description
Attempting to create a stack containing a basic `AWS::StepFunctions::StateMachine` with `DependsOn` relationships or `Ref`s to an `AWS::StepFunctions::Activity` causes an exception.

## Expected behavior
The stack would create.

## Actual behavior
The stack fails with the message:

> An error occurred (ValidationError) when calling the CreateStack operation: Unable to create stack "Test": Resource deployment loop completed, pending resource changes: [{'Type': 'Resource', 'ResourceChange': {'Action': 'Add', 'LogicalResourceId': 'SFSM22S5Y', 'PhysicalResourceId': None, 'ResourceType': 'AWS::StepFunctions::StateMachine', 'Replacement': 'False', 'ChangeSetId': None}}, {'Type': 'Resource', 'ResourceChange': {'Action': 'Add', 'LogicalResourceId': 'SFSM22S5Y', 'PhysicalResourceId': None, 'ResourceType': 'AWS::StepFunctions::StateMachine', 'Replacement': 'False', 'ChangeSetId': None}}]

Debug:
>  2021-03-02T00:10:17:DEBUG:localstack.services.cloudformation.cloudformation_api: Unable to create stack "Test": Resource deployment loop completed, pending resource changes: [{'Type': 'Resource', 'ResourceChange': {'Action': 'Add', 'LogicalResourceId': 'SFSM22S5Y', 'PhysicalResourceId': None, 'ResourceType': 'AWS::StepFunctions::StateMachine', 'Replacement': 'False', 'ChangeSetId': None}}, {'Type': 'Resource', 'ResourceChange': {'Action': 'Add', 'LogicalResourceId': 'SFSM22S5Y', 'PhysicalResourceId': None, 'ResourceType': 'AWS::StepFunctions::StateMachine', 'Replacement': 'False', 'ChangeSetId': None}}] Traceback (most recent call last):
localstack_main |   File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_api.py", line 312, in create_stack
localstack_main |     deployer.deploy_stack()
localstack_main |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1712, in deploy_stack
localstack_main |     self.apply_changes(self.stack, self.stack, stack_name=self.stack.stack_name, initialize=True)
localstack_main |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1942, in apply_changes
localstack_main |     return self.apply_changes_in_loop(changes, existing_stack, stack_name)
localstack_main |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1988, in apply_changes_in_loop
localstack_main |     raise Exception('Resource deployment loop completed, pending resource changes: %s' % changes)
localstack_main | Exception: Resource deployment loop completed, pending resource changes: [{'Type': 'Resource', 'ResourceChange': {'Action': 'Add', 'LogicalResourceId': 'SFSM22S5Y', 'PhysicalResourceId': None, 'ResourceType': 'AWS::StepFunctions::StateMachine', 'Replacement': 'False', 'ChangeSetId': None}}, {'Type': 'Resource', 'ResourceChange': {'Action': 'Add', 'LogicalResourceId': 'SFSM22S5Y', 'PhysicalResourceId': None, 'ResourceType': 'AWS::StepFunctions::StateMachine', 'Replacement': 'False', 'ChangeSetId': None}}]

# Steps to reproduce
Attempt to create a stack with the attached template
`awslocal cloudformation create-stack --stack-name "Test" --template-body file://statemachine_test.template`

#### Template
[statemachine_test.zip](https://github.com/localstack/localstack/files/6065255/statemachine_test.zip)

## Command used to start LocalStack
`docker-compose up`

version: '2.1'

services:

localstack:
image: localstack/localstack:latest
container_name: localstack_main
ports:

"4566:4566"
"4567-4584:4567-4584"
"${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
environment:
SERVICES=lambda,cloudformation,iam,logs,events,secretsmanager,ssm,sqs,s3,apigateway,stepfunctions,ec2,sns
HOSTNAME=localhost
START_WEB=0
DEBUG=1
LAMBDA_EXECUTOR=docker
LAMBDA_REMOTE_DOCKER=true
DATA_DIR=/tmp/localstack/data
volumes:
${LOCALSTACK_DIR}/startup:/docker-entrypoint-initaws.d
"//var/run/docker.sock:/var/run/docker.sock"

**Comment by whummer** [comment]
Thanks for reporting @scottiemc7 . This should be fixed in #3679 - can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists. Thanks
