### ISSUE TITLE
Missing rending exception not added in render template function

### ISSUE THREAD

**Issue by dheerajkulakarni** [localstack/localstack#3664]
# Type of request: This is a ...

[ x] bug report

# Detailed description
AWS throws MissingRenderingException when there is some templateVariableData is missing in the templateDataRequest, which is not the case with localstack, seems like MissingRenderingException check is not added at all in render_template function in moto 

## Expected behavior

When there is template variable missing in template request MissingRenderingException has to be thrown.

## Actual behavior
Email is  getting sent successfully

# Steps to reproduce

1. Create a template in ses
2. use created template to send templated mail with some missing template variables

## Command used to start LocalStack

docker run --env SERVICES=ses -p 4566:4566 localstack/localstack

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

val testRenderTemplateRequest = TestRenderTemplateRequest()
testRenderTemplateRequest.templateData = templateVariablesData
testRenderTemplateRequest.templateName = templateId
client.testRenderTemplate(testRenderTemplateRequest)

**Comment by dheerajkulakarni** [comment]
Hey @usmangani1, We are kind of waiting for this feature, so any updates on this?

**Comment by whummer** [comment]
Thanks @dheerajkulakarni @usmangani1 . This should be fixed upstream in the meantime - can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists. Thanks!
