### ISSUE TITLE
Update to latest moto version 2

### ISSUE THREAD

**Issue by ayushghosh** [localstack/localstack#3667]
We fixed issues in moto library and been waiting for it to be incorporated in localstack.

Since moto has released the v2.0.0 do we have any estimated timeline for it to be integrated in localstack.

**Comment by whummer** [comment]
Thanks for reporting @ayushghosh . This should be fixed in the meantime - can you please pull the `latest` Docker image and give it another try? Please let us know if there are any issues. Thanks!
