### ISSUE TITLE
Cloudformation - References to AWS::ApiGateway::RestApi cause exception

### ISSUE THREAD

**Issue by scottiemc7** [localstack/localstack#3668]
# Type of request: This is a ...

[X] bug report
[ ] feature request

# Detailed description
When creating a stack containing a `AWS::ApiGateway::Model` referencing a `AWS::ApiGateway::RestApi`, localstack throws an exception. This happens even if there are conditions on the API and Model that should cause both resources to be ignored.

## Expected behavior
The stack would create.

## Actual behavior
The stack errors out with this message:
> An error occurred (ValidationError) when calling the CreateStack operation: Unable to create stack "Test": Resource deployment loop completed, pending resource changes: [{'Type': 'Resource', 'ResourceChange': {'Action': 'Add', 'LogicalResourceId': 'AGRA16EMH', 'PhysicalResourceId': None, 'ResourceType': 'AWS::ApiGateway::RestApi', 'Replacement': 'False', 'ChangeSetId': None}}, {'Type': 'Resource', 'ResourceChange': {'Action': 'Add', 'LogicalResourceId': 'AGM1P07R', 'PhysicalResourceId': None, 'ResourceType': 'AWS::ApiGateway::Model', 'Replacement': 'False', 'ChangeSetId': None}}, {'Type': 'Resource', 'ResourceChange': {'Action': 'Modify', 'LogicalResourceId': 'AGRA16EMH', 'PhysicalResourceId': None, 'ResourceType': 'AWS::ApiGateway::RestApi', 'Replacement': 'False', 'ChangeSetId': None}}, {'Type': 'Resource', 'ResourceChange': {'Action': 'Modify', 'LogicalResourceId': 'AGM1P07R', 'PhysicalResourceId': None, 'ResourceType': 'AWS::ApiGateway::Model', 'Replacement': 'False', 'ChangeSetId': None}}]

Debug:
> 2021-03-02T19:31:54:INFO:localstack.utils.cloudformation.template_deployer: Unable to create stack Test: Resource deployment loop completed, pending resource changes: [{'Type': 'Resource', 'ResourceChange': {'Action': 'Add', 'LogicalResourceId': 'AGRA16EMH', 'PhysicalResourceId': None, 'ResourceType': 'AWS::ApiGateway::RestApi', 'Replacement': 'False', 'ChangeSetId': None}}, {'Type': 'Resource', 'ResourceChange': {'Action': 'Add', 'LogicalResourceId': 'AGM1P07R', 'PhysicalResourceId': None, 'ResourceType': 'AWS::ApiGateway::Model', 'Replacement': 'False', 'ChangeSetId': None}}, {'Type': 'Resource', 'ResourceChange': {'Action': 'Modify', 'LogicalResourceId': 'AGRA16EMH', 'PhysicalResourceId': None, 'ResourceType': 'AWS::ApiGateway::RestApi', 'Replacement': 'False', 'ChangeSetId': None}}, {'Type': 'Resource', 'ResourceChange': {'Action': 'Modify', 'LogicalResourceId': 'AGM1P07R', 'PhysicalResourceId': None, 'ResourceType': 'AWS::ApiGateway::Model', 'Replacement': 'False', 'ChangeSetId': None}}]
localstack_main | 2021-03-02T19:31:54:DEBUG:localstack.services.cloudformation.cloudformation_api: Unable to create stack "Test": Resource deployment loop completed, pending resource changes: [{'Type': 'Resource', 'ResourceChange': {'Action': 'Add', 'LogicalResourceId': 'AGRA16EMH', 'PhysicalResourceId': None, 'ResourceType': 'AWS::ApiGateway::RestApi', 'Replacement': 'False', 'ChangeSetId': None}}, {'Type': 'Resource', 'ResourceChange': {'Action': 'Add', 'LogicalResourceId': 'AGM1P07R', 'PhysicalResourceId': None, 'ResourceType': 'AWS::ApiGateway::Model', 'Replacement': 'False', 'ChangeSetId': None}}, {'Type': 'Resource', 'ResourceChange': {'Action': 'Modify', 'LogicalResourceId': 'AGRA16EMH', 'PhysicalResourceId': None, 'ResourceType': 'AWS::ApiGateway::RestApi', 'Replacement': 'False', 'ChangeSetId': None}}, {'Type': 'Resource', 'ResourceChange': {'Action': 'Modify', 'LogicalResourceId': 'AGM1P07R', 'PhysicalResourceId': None, 'ResourceType': 'AWS::ApiGateway::Model', 'Replacement': 'False', 'ChangeSetId': None}}] Traceback (most recent call last):
localstack_main |   File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_api.py", line 312, in create_stack
localstack_main |     deployer.deploy_stack()
localstack_main |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1712, in deploy_stack
localstack_main |     self.apply_changes(self.stack, self.stack, stack_name=self.stack.stack_name, initialize=True)
localstack_main |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1942, in apply_changes
localstack_main |     return self.apply_changes_in_loop(changes, existing_stack, stack_name)
localstack_main |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1988, in apply_changes_in_loop
localstack_main |     raise Exception('Resource deployment loop completed, pending resource changes: %s' % changes)
localstack_main | Exception: Resource deployment loop completed, pending resource changes: [{'Type': 'Resource', 'ResourceChange': {'Action': 'Add', 'LogicalResourceId': 'AGRA16EMH', 'PhysicalResourceId': None, 'ResourceType': 'AWS::ApiGateway::RestApi', 'Replacement': 'False', 'ChangeSetId': None}}, {'Type': 'Resource', 'ResourceChange': {'Action': 'Add', 'LogicalResourceId': 'AGM1P07R', 'PhysicalResourceId': None, 'ResourceType': 'AWS::ApiGateway::Model', 'Replacement': 'False', 'ChangeSetId': None}}, {'Type': 'Resource', 'ResourceChange': {'Action': 'Modify', 'LogicalResourceId': 'AGRA16EMH', 'PhysicalResourceId': None, 'ResourceType': 'AWS::ApiGateway::RestApi', 'Replacement': 'False', 'ChangeSetId': None}}, {'Type': 'Resource', 'ResourceChange': {'Action': 'Modify', 'LogicalResourceId': 'AGM1P07R', 'PhysicalResourceId': None, 'ResourceType': 'AWS::ApiGateway::Model', 'Replacement': 'False', 'ChangeSetId': None}}]

# Steps to reproduce
Attempt to create a stack with the attached template. This should not create any resources because of the condition.
`awslocal cloudformation create-stack --stack-name "Test" --template-body file://apigateway.template`

This also fails the same way, but should create all resources in the template
`awslocal cloudformation create-stack --stack-name "Test" --template-body file://apigateway.template --parameters "ParameterKey=Create,ParameterValue=True,UsePreviousValue=false"`

#### Template
[apigateway.zip](https://github.com/localstack/localstack/files/6071618/apigateway.zip)

## Command used to start LocalStack
`docker-compose up`

version: '2.1'

services:

localstack:
image: localstack/localstack:latest
container_name: localstack_main
ports:

"4566:4566"
"4567-4584:4567-4584"
"${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
environment:
SERVICES=lambda,cloudformation,iam,logs,events,secretsmanager,ssm,sqs,s3,apigateway,stepfunctions,ec2,sns
HOSTNAME=localhost
START_WEB=0
DEBUG=1
LAMBDA_EXECUTOR=docker
LAMBDA_REMOTE_DOCKER=true
DATA_DIR=/tmp/localstack/data
volumes:
${LOCALSTACK_DIR}/startup:/docker-entrypoint-initaws.d
"//var/run/docker.sock:/var/run/docker.sock"

**Comment by whummer** [comment]
Thanks for reporting @scottiemc7 . This should be fixed in #3679 - can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists. Thanks
