### ISSUE TITLE
User name with spaces in windows ends up with an error "No such file or directory"

### ISSUE THREAD

**Issue by stevenpila** [localstack/localstack#3674]
# Type of request: This is a ...

[1 ] bug report
[ ] feature request

# Detailed description
Hi,

When we just try to create sns topic using awslocal, we always get an error that there's no such file or directory.
It seems this is a problem where user name has spaces in windows (E.g., C:\Users\Sample Name\) because when one of us tried doing this with no spaces in username, it's working as expected.

As a workaround, we just created a new user w/o spaces in the username but we would love to know if there's a solution to this one so we don't have to create new user since we would also have to transfer other files.

We also tried looking some solutions but failed. Can anyone help us with this one please?

Thanks and appreciate the response.
...

## Expected behavior
It should successfully create sns topic
...

## Actual behavior
python: can't open file 'C:\Users\EASE': [Errno 2] No such file or directory
...

# Steps to reproduce
1. In windows, your username must have spaces (E.g., C:\Users\Sample Name\)
2. Run **docker-compose. up** from docker-compose.yml where SNS service is enabled.
3. Using awslocal command, run **awslocal sns create-topic --name my-topic**
## Command used to start LocalStack
docker-compose up
...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
![image](https://user-images.githubusercontent.com/6943024/109902908-085b9f80-7cd6-11eb-8fbf-67d2b84b60e6.png)
...

**Comment by whummer** [comment]
Thanks for reporting @stevenpila . This has also been reported in https://github.com/localstack/awscli-local/issues/38 - can you please give it a try with the latest version of the pip package and let us know if the problem persists? Thanks for your help.
