### ISSUE TITLE
can't find '__main__' module in 'C:\\Users\\Office' while trying to localstack start

### ISSUE THREAD

**Issue by FatehAhmad** [localstack/localstack#3687]
the command I run on cmd to start the package:-

`localstack start`

The error message I get:-

`can't find '__main__' module in 'C:\\Users\\Office'`
Now I dont understand why it is looking for `__main__ at 'C:\\Users\\Office' when the path to python in my system is C:\Users\Office User\AppData\Local\Programs\Python\Python37`

It seems like it is breaking because of the whitespace in the username Office user

What could be the issue here?

**Comment by mgagliardo** [comment]
Hello @FatehAhmad, this looks like a path issue indeed, while we investigate this you could run it with docker.
