### ISSUE TITLE
Connect to real AWS services

### ISSUE THREAD

**Issue by recharge-dreams** [localstack/localstack#3689]
# Type of request: This is a ...

## Query
Hi,

Is there is anyway I can force localstack to use actual AWS credentials? (this will be highly helpful in testing the code with the existing data in lower environments. Basically I wanted to avoid deploying the lambda code every time to test my changes. I'm trying to find if I can run lambda locally with the data from my _real_ AWS dynamo db).

Also, it would be great if you elaborate the documentation/provide an example on how to use `LAMBDA_FORWARD_URL`.

BTW, thank you very much for this cool stuff.

Thanks!

**Comment by whummer** [comment]
> I'm trying to find if I can run lambda locally with the data from my real AWS dynamo db).

Hi @recharge-dreams, yes this is technically possible - you can create IAM credentials in AWS and configure them in the environment of your LocalStack Lambda function (`AWS_ACCESS_KEY_ID`/`AWS_SECRET_ACCESS_KEY`). Please note that we do **NOT recommend** doing that, though - mixing LocalStack with real AWS production credentials can be dangerous (use at your own risk).

Regarding your second question - we have this in the README:
> * `LAMBDA_FORWARD_URL`: URL used to forward all Lambda invocations (useful to run Lambdas via an external service).
So, for example if you configure `LAMBDA_FORWARD_URL=http://my.lambda.host:54321`, then all Lambda invocations will not be executed inside LocalStack itself, but will instead be forwarded as `Invoke` API calls to the server listening at `http://my.lambda.host:54321`.

Hope that helps, please keep us posted if anything else is unclear. Thanks
