### ISSUE TITLE
Lambda can't find layer code Nodejs12.x version 0.12.7

### ISSUE THREAD

**Issue by cwilliamsonslyp** [localstack/localstack#3693]
# Type of request: This is a ...

[X] bug report
[ ] feature request

# Detailed description

We're getting lambda layer errors in version 0.12.7 using a Nodejs12.x runtime. This doesn't happen in localstack version 11.2 (our current version). We've tested the commands used to deploy the layer and lambda against our real AWS environment and everything works as expected. Any help is appreciated 😄 
...

## Expected behavior

A Nodejs12.x and Nodejs14.x lambda with a layer should be able to access the layer code and execute successfully.
...

## Actual behavior
The lambda fails with the following output from the localstack container
![image](https://user-images.githubusercontent.com/64388493/110257484-43b9df00-7ff2-11eb-8796-e5b6d81b8d77.png)

...

# Steps to reproduce

docker-compose file

```
version: "3.7"
services:

  localstack:
    image: localstack/localstack:0.12.7
    container_name: my_localstack
    ports:
      - "443:443"
      - "4510-4520:4510-4520"
      - "4566-4620:4566-4620"
    environment:
      - DNS_ADDRESS=0
      - START_WEB=0
      - LAMBDA_EXECUTOR=docker-reuse
      - LAMBDA_REMOTE_DOCKER=true
      - LOCALSTACK_API_KEY=${MY_LOCALSTACK_API_KEY}
      - DNS_RESOLVE_IP=172.17.0.1
      - LAMBDA_REMOVE_CONTAINERS=true
      - DEFAULT_REGION=ap-southeast-2
      - SERVICES=lambda,events,dynamodb,sqs,kinesis,s3,kms
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - './.localstack:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
```

## Command used to start LocalStack

docker-compose up
...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

BasicLambda -> Lambda with no layers that works as expected
Layer -> contains the layer code for the LambdaWithPackage function
LambdaWithPackage -> Lambda which depends on the above layer
[localstackLambdaIssue.zip](https://github.com/localstack/localstack/files/6098103/localstackLambdaIssue.zip)

Create the layer zip (run from root of zip)
```
cd layer
zip -r nodejs.zip nodejs/
cd ..
```

Upload the layer
```
cd layer
aws --endpoint http://localhost:443 lambda publish-layer-version --layer-name package-layer --zip-file fileb://nodejs.zip
cd ..
```

Package the lambda:
```
cd lambdaWithPackage
zip function.zip index.js
cd ..
```

Create the lambda:

```
cd lambdaWithPackage
aws --endpoint-url http://localhost:443 lambda create-function --function-name function-with-package --runtime nodejs12.x --handler index.handler --layers arn:aws:lambda:ap-southeast-2:000000000000:layer:package-layer:1 --memory-size 128 --zip-file fileb://function.zip --role arn:aws:iam:123456:role/irrelevant
cd ..
```

...

**Comment by monty16597** [comment]
Hello @cwilliamsonslyp ,
Lambda layer feature is being supported in the PRO version of the localstack only. So `aws --endpoint http://localhost:443 lambda publish-layer-version --layer-name package-layer --zip-file fileb://nodejs.zip` command has probably given you the error which will fail the function invocation as you can see in your logs.

Thanks.

**Comment by cwilliamsonslyp** [comment]
We have pro accounts. Is there a specific configuration required besides adding `LOCALSTACK_API_KEY` as a container environment variable to enable the layer functionality?

**Comment by whummer** [comment]
Thanks for reporting @cwilliamsonslyp , and apologies for the long delay.

Looks like this has been fixed in the meantime - can you please do a `docker pull localstack/localstack` and give it another try with the `latest` Docker image?

This is what I'm seeing in the logs when running your Lambda:
```
2021-05-01T17:48:00:DEBUG:localstack.services.awslambda.lambda_executors: Lambda arn:aws:lambda:eu-central-1:000000000000:function:function-with-packkage result / log output:
{"message":"My lambda WORKSS!","a":"special value"}
```

Please note that a few configuration parameters may have to be adjusted to get the Lambda executor fully working in your docker-compose stack. We have now added a new `config validate` command line utility, which can help you resolve common configuration issues with docker-compose: 
```
$ localstack config validate
2021-05-01T19:51:32:WARNING:bootstrap.py: Please configure the "HOST_TMP_FOLDER" environment variable to point to the absolute path of a temp folder on your host system (e.g., HOST_TMP_FOLDER=${TMPDIR})
2021-05-01T19:51:32:WARNING:bootstrap.py: Please use "container_name: localstack_main" or add "MAIN_CONTAINER_NAME" in "environment".
2021-05-01T19:51:32:WARNING:bootstrap.py: Network mode is not set to "bridge" which may cause networking issues in Lambda containers. Consider adding "network_mode: bridge" to you docker-compose file, or configure LAMBDA_DOCKER_NETWORK with the name of the Docker network of your compose stack.
```

Hope that helps - please keep us posted how it goes. Thanks!
