### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by carloscarcamo** [localstack/localstack#37]
Would be nice to have a wiki and some examples of how to use this

**Comment by xaviarias** [comment]
I have never used pip` or `docker` and I would like to be able to start a container, just by following the README. Where `pip` installs `localstack` so I can run the `docker-compose` comand?

**Comment by whummer** [comment]
The documentation has recently been updated and improved. There is now a `localstack start --docker` command which facilitates the task of running *LocalStack* in Docker. I hope that makes things a bit easier.

This is a fairly high-voted issue. Please let me know which other parts of the documentation need improving, I'm happy for any suggestions (and of course also pull requests!).

**Comment by brentsmyth** [comment]
I think it would be really great to see a tutorial on setting up a `API Gateway -> Lambda -> Dynamo` pipeline with docker compose.

**Comment by erkkikeranen** [comment]
It would be really nice to have a documented summary what works and what does not. 

Also I can't find any information how to contact anyone if I want to test the pro (paid) version.

**Comment by cristal2431** [comment]
It would be really nice to have a proper documentation on how to use each functions. Specially AG, I cannot find much information on this.

**Comment by whummer** [comment]
Closing this issue as outdated, for housekeeping reasons.
