### ISSUE TITLE
How do I use LocalStack for .NET Core?

### ISSUE THREAD

**Issue by whummer** [localstack/localstack#370]
Note: Copied over from https://bitbucket.org/atlassian/localstack/issues/59/how-do-i-use-localstack-for-net-core

---

**NOT A BUG**

I'm new to localstack and I did not know where to ask questions like this as I could not find any forum for localstack.

I'm facing difficulties in deploying my application developed in [.Net Core] using Visual Studio on localstack.

I'm trying to execute the samples provided with Visual Studio(Blogs and Hello) for learning.
Could you guys please provide me with the steps to execute my application on localstack?
Following are the details : 1). Runtime : dotnetcore1.0 2). OS : Windows 3). Application uses API Gateway which invokes lambda function developed in C# using .Net Core 1.0.

**Comment by edenzz** [comment]
Can you please give some feedback here?

**Comment by whummer** [comment]
Closing this for housekeeping reasons. This should be resolved in the meantime. Please comment here if the problem persists. Thanks
