### ISSUE TITLE
localstack status and UI show container stopped

### ISSUE THREAD

**Issue by diegosasw** [localstack/localstack#3700]
# Type of request: This is a ...

[X] bug report
[ ] feature request

# Detailed description
I subscribed to LocalStack PRO
I have access to https://app.localstack.cloud/dashboard but I can see there that docker status is not running and a warining on step 2 stating Docker container not running
I set the LOCALSTACK_API_KEY

I installed localstack CLI with pip
I run localstack and I can see the api key being detected, it shows Ready and I am able to interact with it using AWS Local CLI, but the UI keeps showing it's not running and `localstack status` keeps showing it's stopped.

Also https://localhost.localstack.cloud/health cannot connect
...

## Expected behavior
container status running
...

## Actual behavior
container status stopped and UI showing Docker Status: not running
...

# Steps to reproduce

## Command used to start LocalStack

```
SERVICES=s3,lambda,cloudwatch,dynamodb,sns,sqs,apigatewayv2 localstack start
```
...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
```
$ localstack --version
0.12.6.1
$ localstack status
Base version:           0.12.7
Docker image:           Tag latest, ID 83d2ef529645, Created 2021-03-10T12:47:03
Container status:       stopped
```
...

**Comment by diegosasw** [comment]
What's on port 53? I've just tried to run docker-compose to see if that way it's detected. My docker-compose file is
```
version: '2.1'
services:
  localstack:
    image: localstack/localstack
    ports:
      - "53:53"
      - "443:443"
      - "4510-4520:4510-4520"
      - "4566-4620:4566-4620"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - LOCALSTACK_API_KEY=****
      - SERVICES=s3,lambda,dynamodb,sns,sqs,cloudwatch,cloudformation
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

and it complains about 
```
c:\src>docker-compose -f localstack-compose.yml up
Starting src_localstack_1 ...
Starting src_localstack_1 ... error

ERROR: for src_localstack_1  Cannot start service localstack: driver failed programming external connectivity on endpoint src_localstack_1 (142fe57928daa8be1916657ffd66f00d72490e4745db598be96588d2da869249): Error starting userland proxy: listen tcp4 0.0.0.0:53: bind: address already in use

ERROR: for localstack  Cannot start service localstack: driver failed programming external connectivity on endpoint src_localstack_1 (142fe57928daa8be1916657ffd66f00d72490e4745db598be96588d2da869249): Error starting userland proxy: listen tcp4 0.0.0.0:53: bind: address already in use
ERROR: Encountered errors while bringing up the project.
```

Not sure what's using the port 53, probably something related to localstack old execution with localstack CLI (that is stopped now). So I have modified the mapping as in `54:53` and now it runs although it shows some SSL errors, but that way the https://app.localstack.cloud/dashboard shows docker as running.

Hopefully someone lets me know why running it with localstack CLI does not show as running in the status and cannot check health.

**Comment by diegosasw** [comment]
I'm using Windows 10 (running commands with git bash)

I've just noticed that the docker-compose I'm using does not match the one at the repo's, so I am a bit confused.

If I try the following:
```
version: '2.1'
services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    network_mode: bridge
    ports:
      - "4566:4566"
      - "4571:4571"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - LOCALSTACK_API_KEY=***
      - SERVICES=${SERVICES- }
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
``` 
I can see localstack starting, the UI still shows docker is stopped and localstack status also shows
```
$ localstack status
Base version:           0.12.7
Docker image:           Tag latest, ID 83d2ef529645, Created 2021-03-10T12:47:03
Container status:       stopped
```

I'm a bit confused, is the port 53 mapping necessary? or is the "new" approach to use that _edge service_ the doc talks about?

There is no TCP port 53 being used but the docker compose from my first message (same as in https://app.localstack.cloud/docs) still complains. 

I remember seeing some before (not anymore) being used by the svchost.exe from the Internet Connection Sharing windows service (which I couldn't stop)

PS: Setting 0.0.0.0 or 22.22.22.22 or 0 as suggested in docs, does not make any difference.

Thanks

![ports](https://user-images.githubusercontent.com/57327772/110655199-2128f100-81bf-11eb-9399-fd82680ecfcd.PNG)

**Comment by diegosasw** [comment]
In any case, the `localstack start` works, independently of the UI and localstack status showing there is no container running. Not even sure if there is any advantage of using docker-compose/docker instead of the localstack CLI. The documentation is not very helpful regarding that, at least for those of us who see localstack for first time.

**Comment by mgagliardo** [comment]
I would definitely go for the docker solution as you can always have the latest release from there.

Could you please run the docker-compose with `- DEBUG=1`  and `docker-compose up` so you can watch the logs on your screen for any errors?

To check if it is already running you should `docker-compose status` or `docker ps` should be enough.

**Comment by diegosasw** [comment]
Maybe I wasn't clear with my message. I have tried 3 ways of running localstack. I'm trying to follow documentation to use the **PRO version** but get different instructions depending on whether I look at the repo README or at the https://app.localstack.cloud/docs

## First approach (the "new" way described at the repo's README)

I've got the following `localstack-compose.yml`

```
version: '2.1'
services:
  localstack:
    container_name: "localstack-main-foo"
    image: localstack/localstack
    network_mode: bridge
    ports:
      - "4566:4566"
      - "4571:4571"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - LOCALSTACK_API_KEY=1XR6O*****
      - SERVICES=s3,lambda,sns,sqs
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      #- PORT_WEB_UI=${PORT_WEB_UI- }
      #- LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      #- KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
```
I execute `docker-compose -f localstack-compose.yml` and it runs well.
I can interact with it using awslocal CLI and, of course, `docker ps` shows the container is running properly.
BUT in https://app.localstack.cloud/dashboard the dashboard shows docker container not running.
Additionally `localstack status` shows
```
$ localstack status
Base version:           0.12.7
Docker image:           Tag latest, ID 83d2ef529645, Created 2021-03-10T12:47:03
Container status:       stopped
```
which is simply not accurate.
**Is this way to run it OK? Is it even reading the `LOCALSTACK_API_KEY` properly and unlocking all the PRO services?**


## Second approach (the way described at https://app.localstack.cloud/docs)

I've got the following `localstack-compose.yml`

```
version: '2.1'
services:
  localstack:
    image: localstack/localstack
    ports:
      - "53:53"
      - "443:443"
      - "4510-4520:4510-4520"
      - "4566-4620:4566-4620"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - LOCALSTACK_API_KEY=1XR6O*****
      #- DNS_ADDRESS=0.0.0.0
      - SERVICES=s3,lambda,sns,sqs
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```
I execute `docker-compose -f localstack-compose.yml` and it does not spin up the container. It shows
```
$ docker-compose -f localstack-compose.yml up
Removing localstack-sandbox_localstack_1
Recreating 9390b25a0e88_localstack-main-foo ...
Recreating 9390b25a0e88_localstack-main-foo ... error

ERROR: for 9390b25a0e88_localstack-main-foo  Cannot start service localstack: driver failed programming external connectivity on endpoint localstack-sandbox_localstack_1 (cfe936668c4537a1bc564fe90e9605991087e95b9f85fd3e0d634dda8d0eebf5): Error starting userland proxy: listen tcp4 0.0.0.0:53: bind: address already in use

ERROR: for localstack  Cannot start service localstack: driver failed programming external connectivity on endpoint localstack-sandbox_localstack_1 (cfe936668c4537a1bc564fe90e9605991087e95b9f85fd3e0d634dda8d0eebf5): Error starting userland proxy: listen tcp4 0.0.0.0:53: bind: address already in use
ERROR: Encountered errors while bringing up the project.
```
localstack is, therefore, not running
```
$ awslocal s3 ls
Could not connect to the endpoint URL: "http://localhost:4566/"
``` 
and no containers are in execution
```
$ docker ps
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES

```
Additionally, there is nothing running on TCP 53 according to resource monitor. So that error is very strange.

**Is this way to run it OK? Is it even reading the `LOCALSTACK_API_KEY` properly and unlocking all the PRO services?**


## Third approach (the not so recommended way to run it with localstack CLI)
It runs well
```
$ SERVICES=s3,lambda,sns,sqs localstack start
Starting local dev environment. CTRL-C to quit.
docker run -it -e SERVICES="s3,lambda,sns,sqs" -e TEST_AWS_ACCOUNT_ID="000000000000" -e DEFAULT_REGION="us-east-1" -e LOCALSTACK_HOSTNAME="localhost" -e LOCALSTACK_API_KEY="1XR6O****" -e HOSTNAME="5CD013DP5L" --rm --privileged --name localstack_main -p 4566:4566 -p 8080-8081:8080-8081  -v "C:\Users\DIEGO~1.MAR\AppData\Local\Temp\localstack:/tmp/localstack" -v "/var/run/docker.sock:/var/run/docker.sock" -e DOCKER_HOST="unix:///var/run/docker.sock" -e HOST_TMP_FOLDER="C:\Users\DIEGO~1.MAR\AppData\Local\Temp\localstack" "localstack/localstack"
Waiting for all LocalStack services to be ready
2021-03-10 16:13:45,474 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2021-03-10 16:13:45,476 INFO supervisord started with pid 14
2021-03-10 16:13:46,479 INFO spawned: 'dashboard' with pid 20
2021-03-10 16:13:46,480 INFO spawned: 'infra' with pid 21
2021-03-10 16:13:46,483 INFO success: dashboard entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2021-03-10 16:13:46,484 INFO exited: dashboard (exit status 0; expected)
(. .venv/bin/activate; exec bin/localstack start --host)
2021-03-10 16:13:47,486 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Starting local dev environment. CTRL-C to quit.

LocalStack version: 0.12.7
LocalStack docker image id: b0a0e869aea4
LocalStack build date: 20210310
LocalStack build git hash: 95f91f6

2021-03-10T16:13:49:INFO:localstack.utils.analytics.profiler: Execution of "load_plugin_from_path" took 2449.0950107574463ms
2021-03-10T16:13:49:INFO:localstack.utils.analytics.profiler: Execution of "load_plugins" took 2454.6308517456055ms
Waiting for all LocalStack services to be ready
2021-03-10T16:13:53:INFO:localstack_ext.bootstrap.licensing: Successfully activated API key
Starting DNS servers (tcp/udp port 53 on 0.0.0.0)...
Starting edge router (http port 4566)...
Starting edge router (https port 443)...
Starting mock CloudWatch service on http ports 443/4566 ...
Starting mock Lambda service on http ports 443/4566 ...
Starting mock CloudWatch Logs service on http ports 443/4566 ...
Starting mock S3 service on http ports 443/4566 ...
Starting mock SNS service on http ports 443/4566 ...
Starting mock SQS service on http ports 443/4566 ...
2021-03-10T16:13:56:INFO:localstack_ext.utils.aws.metadata_service: Starting AWS instance metadata service on port 80
2021-03-10T16:13:56:INFO:botocore.credentials: Found credentials in environment variables.
2021-03-10T16:13:56:INFO:botocore.credentials: Found credentials in environment variables.
[2021-03-10 16:13:56 +0000] [22] [INFO] Running on https://0.0.0.0:4566 (CTRL + C to quit)
2021-03-10T16:13:56:INFO:hypercorn.error: Running on https://0.0.0.0:4566 (CTRL + C to quit)
[2021-03-10 16:13:56 +0000] [22] [INFO] Running on https://0.0.0.0:443 (CTRL + C to quit)
2021-03-10T16:13:56:INFO:hypercorn.error: Running on https://0.0.0.0:443 (CTRL + C to quit)
[2021-03-10 16:13:56 +0000] [22] [INFO] Running on http://0.0.0.0:50575 (CTRL + C to quit)
2021-03-10T16:13:56:INFO:hypercorn.error: Running on http://0.0.0.0:50575 (CTRL + C to quit)
Waiting for all LocalStack services to be ready
2021-03-10T16:14:01:INFO:botocore.credentials: Found credentials in environment variables.
Ready.
```

I can interact with it using awslocal CLI and `docker ps` shows the container is running properly
BUT in https://app.localstack.cloud/dashboard the dashboard shows docker container not running.
Additionally `localstack status` shows
```
$ localstack status
Base version:           0.12.7
Docker image:           Tag latest, ID 83d2ef529645, Created 2021-03-10T12:47:03
Container status:       stopped
```
**Is this expected?** Maybe there is a bug in https://app.localstack.cloud/dashboard, or maybe I'm not using the proper mechanism to run it, as it seems the documentation is not up to date..

**Which docker compose is 'wrong' for the latest localstack docker image?**

**Comment by diegosasw** [comment]
1. New docker compose
    Ok
2. Old docker compose
    Restarting docker or reinstalling it doesn't make any difference. Nothing running on 53 afaik
    ```
$ netstat -a | grep :53
  TCP    127.0.0.1:53480        kubernetes:53481       ESTABLISHED
  TCP    127.0.0.1:53481        kubernetes:53480       ESTABLISHED
  TCP    192.168.1.135:53440    lb-140-82-113-25-iad:https  ESTABLISHED
  TCP    192.168.1.135:53455    mad07s23-in-f14:https  TIME_WAIT
  TCP    192.168.1.135:53467    lb-140-82-113-25-iad:https  ESTABLISHED
  TCP    192.168.1.135:53468    140:https              ESTABLISHED
  TCP    192.168.1.135:53469    ec2-52-32-34-32:https  TIME_WAIT
  TCP    192.168.1.135:53472    ec2-52-10-162-146:https  ESTABLISHED
  TCP    192.168.1.135:53473    wiki-ubuntu-com:http   TIME_WAIT
  TCP    192.168.1.135:53478    mad07s22-in-f4:https   ESTABLISHED
  TCP    192.168.1.135:53479    mad07s22-in-f4:https   ESTABLISHED
  TCP    192.168.1.135:53483    mad07s23-in-f3:https   ESTABLISHED
  TCP    192.168.1.135:53484    mad41s14-in-f3:https   ESTABLISHED
  TCP    192.168.1.135:53485    mad41s14-in-f1:https   ESTABLISHED
  TCP    192.168.1.135:53486    mad07s22-in-f14:https  ESTABLISHED
  TCP    192.168.1.135:53487    mad07s10-in-f2:https   ESTABLISHED
  TCP    192.168.1.135:53488    mad41s10-in-f2:https   ESTABLISHED
  TCP    192.168.1.135:53489    mad07s09-in-f2:https   ESTABLISHED
  TCP    192.168.1.135:53490    gw:http                ESTABLISHED
  TCP    192.168.1.135:53491    gw:http                ESTABLISHED
  TCP    192.168.1.135:53492    gw:http                ESTABLISHED
  TCP    192.168.1.135:53493    mad41s04-in-f10:http   ESTABLISHED
  TCP    192.168.1.135:53494    gw:http                ESTABLISHED
  TCP    192.168.1.135:53495    gw:http                ESTABLISHED
  TCP    192.168.1.135:53496    gw:http                ESTABLISHED
  TCP    192.168.1.135:53497    waw02s06-in-f66:http   ESTABLISHED
  TCP    192.168.1.135:53498    mad07s09-in-f2:https   ESTABLISHED
  TCP    192.168.1.135:53499    waw02s06-in-f66:https  TIME_WAIT
  TCP    192.168.1.135:53500    waw02s06-in-f66:https  ESTABLISHED
  TCP    192.168.1.135:53501    waw02s06-in-f66:http   ESTABLISHED
  TCP    192.168.1.135:53502    waw02s06-in-f66:http   TIME_WAIT
  TCP    192.168.1.135:53503    waw02s06-in-f66:http   TIME_WAIT
  TCP    192.168.1.135:53505    mad07s22-in-f14:https  ESTABLISHED
  TCP    192.168.1.135:53506    xx-fbcdn-shv-01-mad1:https  ESTABLISHED
  TCP    192.168.1.135:53507    93.184.220.29:http     ESTABLISHED
  TCP    192.168.1.135:53508    mad41s10-in-f2:https   ESTABLISHED
  TCP    192.168.1.135:53509    mad07s10-in-f2:https   ESTABLISHED
  TCP    192.168.1.135:53510    mad41s14-in-f10:https  TIME_WAIT
  TCP    192.168.1.135:53511    xx-fbcdn-shv-01-mad1:https  ESTABLISHED
  TCP    192.168.1.135:53512    mad07s23-in-f2:https   ESTABLISHED
  TCP    192.168.1.135:53514    mad41s04-in-f10:https  ESTABLISHED
  TCP    192.168.1.135:53515    mad07s09-in-f1:https   ESTABLISHED
  TCP    192.168.1.135:53516    mad07s09-in-f3:http    ESTABLISHED
  TCP    192.168.1.135:53517    mad07s09-in-f3:http    ESTABLISHED
  TCP    192.168.1.135:53519    mad41s14-in-f3:https   ESTABLISHED
  TCP    192.168.1.135:53521    mad41s04-in-f3:https   ESTABLISHED
  TCP    192.168.1.135:53522    mad07s22-in-f4:https   ESTABLISHED
  TCP    192.168.1.135:53523    mad07s10-in-f13:https  ESTABLISHED
  TCP    192.168.1.135:53524    edge-star-mini-shv-01-mad1:https  ESTABLISHED
  TCP    192.168.1.135:53527    mad41s14-in-f14:https  ESTABLISHED
  TCP    192.168.1.135:53528    mad41s04-in-f3:https   ESTABLISHED
  TCP    192.168.1.135:53529    mad41s14-in-f14:https  ESTABLISHED
  TCP    192.168.1.135:53530    104.22.56.217:https    ESTABLISHED
  TCP    192.168.1.135:53531    93.184.220.29:http     ESTABLISHED
  TCP    192.168.1.135:53532    mad41s14-in-f14:https  ESTABLISHED
  TCP    192.168.1.135:53533    mad07s09-in-f8:https   ESTABLISHED
  TCP    192.168.1.135:53534    waw02s06-in-f74:https  ESTABLISHED
  TCP    192.168.1.135:53535    waw02s06-in-f74:https  TIME_WAIT
  TCP    192.168.1.135:53536    mad41s14-in-f3:https   ESTABLISHED
  TCP    192.168.1.135:53538    mad07s22-in-f4:https   ESTABLISHED
  TCP    192.168.1.135:53540    13.107.21.200:https    ESTABLISHED
  TCP    192.168.1.135:53541    e2-ha:https            ESTABLISHED
  TCP    192.168.1.135:53543    e2-ha:https            ESTABLISHED
  TCP    192.168.1.135:53544    spdc:https             ESTABLISHED
  TCP    192.168.1.135:53545    216.218.159.29:https   ESTABLISHED
  UDP    0.0.0.0:5353           *:*
  UDP    0.0.0.0:5355           *:*
  UDP    192.168.1.135:5353     *:*
  UDP    [::1]:5353             *:*
    ```
3. localstack CLI
   This works well, it's picking LOCALSTACK_API_KEY=123 properly from the system environment variables as it shows in the console output.

In any case the localstack UI dashboard never detects the docker container running. If that's not really a problem, this can be closed. Thanks

**Comment by mgagliardo** [comment]
I am a bit overwhelmed with this, @whummer could you please confirm if there's anything in particular going on with the dashboard UI or is there any particular issue?

**Comment by mgagliardo** [comment]
ICS is just an allowance service to allow (duh) other network users to connect through your computer (using NAT of course), so I actually recommend that unless you don't have a personal, but rather an enterprise computer/server.

**Comment by jordanParamo** [comment]
@mgagliardo I misspoke. Unfortunately, even running as administrator, Windows 10 will not allow a user to stop ICS. DNS will have to be allocated to a different IP address in order for this to work.
![Screenshot 2021-03-10 194159](https://user-images.githubusercontent.com/50218595/110722995-f21f7900-81d8-11eb-86c2-01c948a7735b.png)

Linux users rejoice! For you, it's being caused by systemd, modifying /etc/systemd/resolved.conf and reallocating the IP specified there will do the trick.

**Comment by mgagliardo** [comment]
What about trying this? https://www.its.hku.hk/faq/network/remote/disable-ics-win

**Comment by jordanParamo** [comment]
@mgagliardo It restarts ICS with a new PID.
I found the problem:

localstack/services/generic_proxy.py Line 626 is trying to start a the userland proxy at 0.0.0.0
Error: `Error starting userland proxy: listen tcp4 0.0.0.0:53: bind: address already in use`
Code: `if not host:
        host = '0.0.0.0'`
        
How does a user override that variable?

**Comment by mgagliardo** [comment]
Listening on `0.0.0.0` means it is doing so on all your interfaces, you can do the port mapping on your `docker-compose.yml`, like this:

```
    ports:
      - "127.0.0.1:53:53"
```

**Comment by theodorebourgeon** [comment]
It works for me with the new docker version (on MacOs) and this specific port forwarding ! @mgagliardo

**Comment by cyberwombat** [comment]
@theodorebourgeon can you share your compose file perhaps?  I have tried updating docker, setting `"127.0.0.1:53:53"` etc to no avail. I am a bit baffled as to why this issue was closed with no apparent resolution.

**Comment by jordanParamo** [comment]
@cyberwombat Use these ports, fixed it right up. If it still gives you trouble, head down to the Settings tab in app.localstack.cloud and change the address to localhost:4566, AKA the new localstack edge port. Just got it to work yesterday while trying to set up a local dev environment for AWS SAM (so long sls)

```ports:
      - "127.0.0.1:53:53"
      - "443:443"
      - "4510-4520:4510-4520"
      - "4566-4620:4566-4620"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"

**Comment by cyberwombat** [comment]
Hmm no go. Here's what I have w docker 20.10.5 MacOS Big Sur. 
```
version: '2.1'
services:
  localstack:
    image: localstack/localstack-full
    ports:
      - "127.0.0.1:53:53"
      - "443:443"
      - "4510-4520:4510-4520"
      - "4566-4620:4566-4620"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - LOCALSTACK_API_KEY=.......
      - SERVICES=serverless,cognito,dynamodb,appsync,apigateway,apigatewaymanagementapi,apigateway2,cloudfront,cloudwatch,codebuild,es,lambda,s3,ses,sns,sqs,events
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```
The   `https://app.localstack.cloud/` dashboard says not running and the resource management show no resources. However what is odd is that the main overview page of the dashboard shows Ive created 37 resources and the log shows them all correctly. Says I made 13 Dynamodb tables but going to `https://app.localstack.cloud/resources/dynamodb` shows no tables. Very odd...
