### ISSUE TITLE
KCL 2.2.x and 2.3.x are not able to load data from stream

### ISSUE THREAD

**Issue by njofce** [localstack/localstack#3701]
# Type of request: This is a ...

[ x] bug report
[ ] feature request

# Detailed description

I think this is a bug, but might be a feature request. Following the tutorial on AWS docs (https://docs.aws.amazon.com/streams/latest/dev/building-enhanced-consumers-kcl-java.html) it's simple to configure KCL to load data from a stream.
...

## Expected behavior

The expected behavior is that the KCL is able to consume the stream.
...

## Actual behavior

KCL is able to create a Dynamo table for leases, and I think it's able to lock a shard and place the lease in Dynamo. But it fails to load the record. For each record, the `ShardRecordProcessor` must be created, but it's not.

...

# Steps to reproduce

## Command used to start LocalStack

Running localstack via docker
...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
The same code used here
https://docs.aws.amazon.com/streams/latest/dev/building-enhanced-consumers-kcl-java.html
...

**Comment by pinzon** [comment]
Hi @njofce recently these PR's (#3758 & #3691 ) have been recently merged. 
I think they also address this issue. 
Please let me know if it still fails.
