### ISSUE TITLE
Dashboard Resources Overview - No resources found

### ISSUE THREAD

**Issue by Tobolov** [localstack/localstack#3708]
# Type of request: This is a ...

[ X] bug report
[ ] feature request

# Detailed description
Visiting the page `https://app.localstack.cloud/resources` always shows `No resources found. Please start by creating some resources in your LocalStack instance on localhost.`.
As validation that LocalStack is setup correctly locally, I can still view resources in the other resource tabs. 

# Cause of bug
I believe the source of the bug is the API request made to https://api.localstack.cloud/v1/graph. If I instead redirect this request to https://127.0.0.1:4566/v1/graph (Configured custom local endpoint) the Resources Overview graph loads as expected.

**Comment by whummer** [comment]
Thanks for reporting @Tobolov . This should be fixed in the meantime - please let us know if the problem persists. Thanks for your help!
