### ISSUE TITLE
Could not load file or assembly System.IO.Pipelines when running lambda in localstack

### ISSUE THREAD

**Issue by diegosasw** [localstack/localstack#3710]
# Type of request: This is a ...

[X] bug report
[ ] feature request

# Detailed description
I am getting errors when running a C# lambda on dotnetcore3.1 that has been created using Amazon templates. When running the exact same (following the exact same steps in AWS CLI) in a real AWS everything works well.

Why the difference? Why is my lambda in localstack complaining about not being able to load file or assembly `System.IO.Pipelines` but in AWS it's all good? Isn't localstack the "same" environment?

All the code here: https://gitlab.com/sunnyatticsoftware/sandbox/localstack-sandbox/-/tree/master/02-lambda-dotnet-webapi

and `System.IO.Pipelines` seems to be an assembly that comes in the package `Amazon.Lambda.AspNetCoreServer 5.3.0`
...

## Expected behavior
When running the lambda with a given [payload_sample.json](https://gitlab.com/sunnyatticsoftware/sandbox/localstack-sandbox/-/raw/master/02-lambda-dotnet-webapi/payload_sample.json)
```
$ awslocal lambda invoke --function-name lambda-dotnet-webapi-function --payload file://payload_sample.json response.json --log-type Tail
{
    "StatusCode": 200,
    "FunctionError": "Unhandled",
    "LogResult": "XXX==",
    "ExecutedVersion": "$LATEST"
}
$ cat response.json

{"statusCode":200,"headers":{},"multiValueHeaders":{"Content-Type":[null]},"body":"Welcome to running ASP.NET Core on AWS Lambda","isBase64Encoded":false}
```
...

## Actual behavior

When running the lambda with a given [payload_sample.json](https://gitlab.com/sunnyatticsoftware/sandbox/localstack-sandbox/-/raw/master/02-lambda-dotnet-webapi/payload_sample.json)
```
$ awslocal lambda invoke --function-name lambda-dotnet-webapi-function --payload file://payload_sample.json response.json --log-type Tail
{
    "StatusCode": 200,
    "FunctionError": "Unhandled",
    "LogResult": "XXX==",
    "ExecutedVersion": "$LATEST"
}
$ cat response.json

{"errorMessage":"Lambda process returned error status code: 1. Result: {\"errorType\":\"FileNotFoundException\",\"errorMessage\":\"Could not load file or assembly 'System.IO.Pipelines, Version=4.0.2.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.\\n\",\"stackTrace\":[\"at Amazon.Lambda.AspNetCoreServer.AbstractAspNetCoreFunction`2.FunctionHandlerAsync(TREQUEST request, ILambdaContext lambdaContext)\",\"at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine\\u0026 stateMachine)\",\"at Amazon.Lambda.AspNetCoreServer.AbstractAspNetCoreFunction`2.FunctionHandlerAsync(TREQUEST request, ILambdaContext lambdaContext)\",\"at lambda_method(Closure , Stream , Stream , LambdaContextInternal )\"]}. Output:\niptables v1.4.21: can't initialize iptables table `nat': iptables who? (do you need to insmod?)\nPerhaps iptables or your kernel needs to be upgraded.\n\u001b[40m\u001b[32minfo\u001b[39m\u001b[22m\u001b[49m: Microsoft.Hosting.Lifetime[0]\n      Application started. Press Ctrl+C to shut down.\n[Information] Microsoft.Hosting.Lifetime: Application started. Press Ctrl+C to shut down. \n[Information] Microsoft.Hosting.Lifetime: Hosting environment: Production \n\u001b[40m\u001b[32minfo\u001b[39m\u001b[22m\u001b[49m: Microsoft.Hosting.Lifetime[0]\n      Hosting environment: Production\n\u001b[40m\u001b[32minfo\u001b[39m\u001b[22m\u001b[49m: Microsoft.Hosting.Lifetime[0]\n      Content root path: /var/task\n[Information] Microsoft.Hosting.Lifetime: Content root path: /var/task \n\u001b[32mSTART RequestId: 6bd3f662-3db8-1464-51f2-a4a776bd558e Version: $LATEST\u001b[0m\nCould not load file or assembly 'System.IO.Pipelines, Version=4.0.2.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.\n: FileNotFoundException\n   at Amazon.Lambda.AspNetCoreServer.AbstractAspNetCoreFunction`2.FunctionHandlerAsync(TREQUEST request, ILambdaContext lambdaContext)\n   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)\n   at Amazon.Lambda.AspNetCoreServer.AbstractAspNetCoreFunction`2.FunctionHandlerAsync(TREQUEST request, ILambdaContext lambdaContext)\n   at lambda_method(Closure , Stream , Stream , LambdaContextInternal )\n\n\n\u001b[32mEND RequestId: 6bd3f662-3db8-1464-51f2-a4a776bd558e\u001b[0m\n\u001b[32mREPORT RequestId: 6bd3f662-3db8-1464-51f2-a4a776bd558e\tInit Duration: 2328.85 ms\tDuration: 39.86 ms\tBilled Duration: 100 ms\tMemory Size: 1536 MB\tMax Memory Used: 0 MB\t\u001b[0m\nStarting daemons...\nImportError: No module named site\n","errorType":"InvocationException","stackTrace":["  File \"/opt/code/localstack/localstack/services/awslambda/lambda_api.py\", line 574, in run_lambda\n    result = LAMBDA_EXECUTOR.execute(func_arn, func_details, event, context=context,\n","  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 176, in execute\n    return do_execute()\n","  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 168, in do_execute\n    return _run(func_arn=func_arn)\n","  File \"/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py\", line 149, in wrapped\n    raise e\n","  File \"/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py\", line 145, in wrapped\n    result = func(*args, **kwargs)\n","  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 159, in _run\n    raise e\n","  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 147, in _run\n    result = self._execute(func_arn, func_details, event, context, version)\n","  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 325, in _execute\n    result = self.run_lambda_executor(cmd, stdin, env_vars=environment, func_details=func_details)\n","  File \"/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/awslambda/lambda_extended.py\", line 262, in run_lambda_executor\n","  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 231, in run_lambda_executor\n    raise InvocationException('Lambda process returned error status code: %s. Result: %s. Output:\\n%s' %\n"]}
```
...

# Steps to reproduce

The steps with `aws --profile diegosasw` work well. The steps with `awslocal` have the error. Here's the comparison to reproduce.

The code is the same, the `function.zip` is the same (view repo), and it has been created as follows:
```
dotnet new serverless.AspNetCoreWebAPI -n Sample.Lambda.DotNet.WebApi
dotnet build
dotnet publish -c Release -o publish
cd publish
zip -r ../function.zip *
```

### In AWS
Create role
```
aws --profile diegosasw iam create-role --role-name lambda-dotnet-webapi-ex --assume-role-policy-document '{"Version": "2012-10-17", "Statement": [{ "Effect": "Allow", "Principal": {"Service": "lambda.amazonaws.com"}, "Action": "sts:AssumeRole"}]}'
```

Attach AWSLambdaBasicExecutionRole policy to role
```
aws --profile diegosasw iam attach-role-policy --role-name lambda-dotnet-webapi-ex --policy-arn arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
```

Create lambda
```
aws --profile diegosasw lambda create-function --function-name lambda-dotnet-webapi-function --zip-file fileb://function.zip --handler Sample.Lambda.DotNet.WebApi::Sample.Lambda.DotNet.WebApi.LambdaEntryPoint::FunctionHandlerAsync --runtime dotnetcore3.1 --role arn:aws:iam::308309238958:role/lambda-dotnet-webapi-ex
```

Invoke lambda
```
aws --profile diegosasw lambda invoke --function-name lambda-dotnet-webapi-function --payload file://payload_sample.json response.json --log-type Tail
```

### In localstack with awslocal
Create role
```
awslocal iam create-role --role-name lambda-dotnet-webapi-ex --assume-role-policy-document '{"Version": "2012-10-17", "Statement": [{ "Effect": "Allow", "Principal": {"Service": "lambda.amazonaws.com"}, "Action": "sts:AssumeRole"}]}'
```

Attach AWSLambdaBasicExecutionRole policy to role
```
awslocal iam attach-role-policy --role-name lambda-dotnet-webapi-ex --policy-arn arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
```

Create lambda
```
awslocal lambda create-function --function-name lambda-dotnet-webapi-function --zip-file fileb://function.zip --handler Sample.Lambda.DotNet.WebApi::Sample.Lambda.DotNet.WebApi.LambdaEntryPoint::FunctionHandlerAsync --runtime dotnetcore3.1 --role arn:aws:iam::000000000000:role/lambda-dotnet-webapi-ex
```

Invoke lambda
```
awslocal lambda invoke --function-name lambda-dotnet-webapi-function --payload file://payload_sample.json response.json --log-type Tail
```

## Command used to start LocalStack
```
export LOCALSTACK_API_KEY=******
SERVICES=iam,lambda,s3,apigateway,sns,sqs,cloudformation localstack start
```

on Ubuntu 20.04 LTS running as WSL2 in Windows 10.
...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

...

**Comment by sergeyfsv-da** [comment]
Any updates on this issue? Have faced the same problem with aws lambda netcore 3.0 and everything from the examples (nothing more).

**Comment by diegosasw** [comment]
I don't have any news on this, nor a workaround

**Comment by bladmoreno** [comment]
I am having kind of the same issue, my configuration is very similar, but my logs are diferent, here they are

localstack    | 2021-08-05 04:49:53,458:API: 127.0.0.1 - - [05/Aug/2021 04:49:53] "GET /restapis/fduhbub3o5/resources?limit=100 HTTP/1.1" 200 -
localstack    | 2021-08-05 04:49:53,484:API: 127.0.0.1 - - [05/Aug/2021 04:49:53] "GET /restapis/fduhbub3o5/stages/local HTTP/1.1" 200 -
localstack    | 2021-08-05T04:49:53:DEBUG:localstack.services.awslambda.lambda_api: Running Lambda function arn:aws:lambda:us-east-1:000000000000:function:50874-UH-GetMessageAsync-local from API Gateway invocation: GET /Message
localstack    | 2021-08-05T04:49:53:INFO:localstack.services.awslambda.lambda_executors: Determined main container target IP: 172.19.0.2
localstack    | 2021-08-05T04:49:53:INFO:localstack.services.awslambda.lambda_executors: Running lambda: arn:aws:lambda:us-east-1:000000000000:function:50874-UH-GetMessageAsync-local
localstack    | 2021-08-05T04:49:53:DEBUG:localstack_ext.services.awslambda.lambda_launcher: Executing docker-separate image execution for image localstack/lambda:dotnetcore3.1
localstack    | 2021-08-05T04:49:53:DEBUG:localstack.utils.docker: Getting the entrypoint for image: localstack/lambda:dotnetcore3.1
localstack    | 2021-08-05 04:49:53,809:API: 127.0.0.1 - - [05/Aug/2021 04:49:53] "POST / HTTP/1.1" 200 -
localstack    | 2021-08-05 04:49:53,846:API: 127.0.0.1 - - [05/Aug/2021 04:49:53] "POST / HTTP/1.1" 200 -
localstack    | 2021-08-05T04:49:53:INFO:localstack.services.awslambda.lambda_api: Error executing Lambda function arn:aws:lambda:us-east-1:000000000000:function:50874-UH-GetMessageAsync-local: bad escape \U at position 2 Traceback (most recent call last):
localstack    |   File "/usr/lib/python3.7/sre_parse.py", line 1015, in parse_template
localstack    |     this = chr(ESCAPES[this][1])
localstack    | KeyError: '\\U'
localstack    |
localstack    | During handling of the above exception, another exception occurred:
localstack    |
localstack    | Traceback (most recent call last):
localstack    |   File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 752, in run_lambda
localstack    |     lock_discriminator=lock_discriminator,
localstack    |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 279, in execute
localstack    |     return do_execute()
localstack    |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 269, in do_execute
localstack    |     return _run(func_arn=func_arn)
localstack    |   File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 157, in wrapped
localstack    |     raise e
localstack    |   File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 153, in wrapped
localstack    |     result = func(*args, **kwargs)
localstack    |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 256, in _run
localstack    |     raise e
localstack    |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 242, in _run
localstack    |     result = self._execute(func_arn, func_details, event, context, version)
localstack    |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 507, in _execute
localstack    |     event=stdin, env_vars=environment, func_details=func_details, docker_flags=docker_flags
localstack    |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/localstack_ext/services/awslambda/lambda_extended.py", line 360, in run_lambda_executor
localstack    |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 358, in run_lambda_executor
localstack    |     func_details, env_vars, command, docker_flags=docker_flags, stdin=event_stdin_bytes
localstack    |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/localstack_ext/services/awslambda/lambda_launcher.py", line 238, in docker_separate_execute_in_container
localstack    |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 1087, in get_host_path_for_path_in_docker
localstack    |     return re.sub(r"^%s/(.*)$" % config.TMP_FOLDER, r"%s/\1" % config.HOST_TMP_FOLDER, path)
localstack    |   File "/usr/lib/python3.7/re.py", line 194, in sub
localstack    |     return _compile(pattern, flags).sub(repl, string, count)
localstack    |   File "/usr/lib/python3.7/re.py", line 311, in _subx
localstack    |     template = _compile_repl(template, pattern)
localstack    |   File "/usr/lib/python3.7/re.py", line 302, in _compile_repl
localstack    |     return sre_parse.parse_template(repl, pattern)
localstack    |   File "/usr/lib/python3.7/sre_parse.py", line 1018, in parse_template
localstack    |     raise s.error('bad escape %s' % this, len(this))
localstack    | re.error: bad escape \U at position 2
localstack    |

**Comment by kongo23** [comment]
I had a similar issue but with another assembly. If you are using dotnetcore try to package lambda with `dotnet-lambda package` command using amazon lambda tools instead of zip.

**Comment by aquilacf** [comment]
A workaround for this is to publish as self-contained, zip it yourself and update the code.
```
dotnet publish --self-contained true --runtime linux-arm64 -c Release -o publish
find publish -print | zip publish -@
awslocal lambda update-function-code --function-name "my-lambda" --zip-file fileb://publish.zip
```
⚠️  Make sure you change the runtime to match your architecture!

The application is significantly larger, but it works. You might want to update the code using S3.
```
awslocal s3 cp publish.zip s3://my-bucket/publish.zip
awslocal lambda update-function-code --function-name "my-lambda" --s3-bucket "my-bucket" --s3-key "publish.zip"
```
