### ISSUE TITLE
How To Mock Terraform data "aws_ami" Data Source For Localstack

### ISSUE THREAD

**Issue by johnsmith-coder** [localstack/localstack#3714]
# Type of request: This is a general Localstack query...

[ ] bug report

# Detailed description
Hi, I am new to Localstack and am trying to see if I can get an EC2 instance I have already configured and running with Terraform to run in Localstack. However I am getting an error related to the Terraform "aws_ami" data source which I think should be either mocked or ignored but I don't know how. 

## Expected behavior
I have the following data source piece of Terraform code for my EC2 instance which specifies which AMI ID to use for the EC2 instance:

```
data "aws_ami" "amazon-linux-2" {
  most_recent = true
  owners      = ["amazon"]

  filter {
    name   = "owner-alias"
    values = ["amazon"]
  }

  filter {
    name   = "name"
    values = ["amzn2-ami-hvm*"]
  }
}
```

I would expect Localstack to be able to ignore or mock this data source as it is already successfully doing it for the following data source in my code:

`data "aws_caller_identity" "current" {}`

by the use of the 'sts' Service. 
...

## Actual behavior
I get the following Terraform error, ie it can't find a matching AMI:

```
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.terraform_remote_state.remote_vpc_state: Refreshing state...
module.compute.data.aws_caller_identity.current: Refreshing state...
module.compute.data.aws_ami.amazon-linux-2: Refreshing state...

Error: Your query returned no results. Please change your search criteria and try again.

  on compute\main.tf line 7, in data "aws_ami" "amazon-linux-2":
   7: data "aws_ami" "amazon-linux-2" {
```

# Steps to reproduce
My Work Environment:

- Windows 10
- Localstack 0.12.7
- Docker Desktop

This is my docker-compose.yml file:

```
version: '2.1'

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    network_mode: bridge
    ports:
      - "4566:4566"
      - "4571:4571"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=${SERVICES- }
      - DEBUG=1
      - DATA_DIR=/data
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

I have configured my Terraform aws provider code very similarly to how it is described in the Terraform documentation [here](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/custom-service-endpoints#localstack), ie:

```
provider "aws" {
  access_key                  = "mock_access_key"
  region                      = "eu-west-1"
  s3_force_path_style         = true
  secret_key                  = "mock_secret_key"
  skip_credentials_validation = true
  skip_metadata_api_check     = true
  skip_requesting_account_id  = true

  endpoints {
    ec2            = "http://localhost:4566"
    iam            = "http://localhost:4566"
    s3             = "http://localhost:4566"
    sts            = "http://localhost:4566"
    cloudformation = "http://localhost:4566"
    cloudwatch     = "http://localhost:4566"
    dynamodb       = "http://localhost:4566"
    es             = "http://localhost:4566"
    lambda         = "http://localhost:4566"
    redshift       = "http://localhost:4566"
    secretsmanager = "http://localhost:4566"
    ses            = "http://localhost:4566"
    sns            = "http://localhost:4566"
    sqs            = "http://localhost:4566"
    ssm            = "http://localhost:4566"
  }
}
```

## Command used to start LocalStack
docker-compose up
...

**Comment by mgagliardo** [comment]
Hello @johnsmith-coder, thanks for reporting this.

So basically the `describe-images` API is taken from the moto library [here](https://github.com/localstack/moto/blob/master/moto/ec2/responses/amis.py#L42), as far as I can see there's a JSON set of AMIs [here](https://github.com/localstack/moto/blob/9bfd95476b6ff55a510ea8b0ba77f98598bbf4b5/moto/ec2/resources/amis.json), so if you do (for example):

```
$ awslocal ec2 describe-images --owners 801119661308
```

It will return the list of AMIs you are looking for, same will happen with *some* filters, however with the `owner-alias` like you are using:

```
$ awslocal ec2 describe-images --filters Name=owner-alias,Values=amazon
```

It will return:

```
moto.ec2.exceptions.FilterNotImplementedError: The filter 'owner-alias' for DescribeImages has not been implemented in Moto yet. Feel free to open an issue at https://github.com/spulec/moto/issues
```

As the backend is yet not implemented for this particular usecase. Let me know if you need this and we can put it on the list of things to implement.

Cheers!

**Comment by johnsmith-coder** [comment]
Hi @mgagliardo thank you very much for looking at this and thank you for your reply. Yes please and this to the list of things to implement. I played around with the 'owners' field, I didn't know that a lot of AWS AMIs are owned by '801119661308' but I also noticed that a lot are owned by '137112412989', do you know why this is? Just curious.

**Comment by mgagliardo** [comment]
Hey @johnsmith-coder, I guess it is something on moto's end, they are probably using repeated examples or something like that. I'll put this on my pipeline but this one can be closed as only the filters feature is missing.
