### ISSUE TITLE
"Invalid endpoint" when using default container name and docker network

### ISSUE THREAD

**Issue by lorengordon** [localstack/localstack#3719]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

When connecting to localstack over a docker network, from another container, the default container name `localstack_main` is not a valid endpoint (according to awscli, anyway). Fairly sure this is because of the underscore (`_`).

I figure you won't want to change that default, so I'm kind of just opening this to help others get to a resolution more quickly, as there is a simple enough workaround. Or maybe you are open to changing it?

## Expected behavior

Connecting to `http://localstack_main:4566` should succeed.

## Actual behavior

Receive the error message, `Invalid endpoint: http://localstack_main:4566`.

# Steps to reproduce

## Command used to start LocalStack

```
$ ENTRYPOINT=-d localstack start --docker
$ docker network create localstack
$ docker network connect localstack localstack_main
```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

```
$ docker run --network localstack --rm -it -e AWS_DEFAULT_REGION=us-east-1 -e AWS_ACCESS_KEY_ID=test -e AWS_SECRET_ACCESS_KEY=test amazon/aws-cli --endpoint-url=http://localstack_main:4566 lambda list-functions

Invalid endpoint: http://localstack_main:4566
```

# Workaround

Set the container name explicitly using the env `MAIN_CONTAINER_NAME`:

```
$ ENTRYPOINT=-d MAIN_CONTAINER_NAME=localstack localstack start --docker
$ docker network connect localstack localstack

$ docker run --network localstack --rm -it -e AWS_DEFAULT_REGION=us-east-1 -e AWS_ACCESS_KEY_ID=test -e AWS_SECRET_ACCESS_KEY=test amazon/aws-cli --endpoint-url=http://localstack:4566 lambda list-functions
{
    "Functions": []
}
```

**Comment by mgagliardo** [comment]
Hello @lorengordon, thanks for reporting this.

As you can see on [this config file](https://github.com/localstack/localstack/blob/master/localstack/config.py#L176) there's an environment variable (you can also pass at runtime) called `MAIN_CONTAINER_NAME`.

So you can do this:

```
$ MAIN_CONTAINER_NAME=localstack ENTRYPOINT=-d localstack start --docker
$ docker network create localstack
$ docker network connect localstack localstack
```

And then connect any of your containers to `http://localstack:4566` which is the name of the container in this case. I strongly recommend using docker-compose so you can modify this easier, though.

**Comment by lorengordon** [comment]
@mgagliardo All good, I'm aware of the env, you posted my _exact_ workaround in the OP 😉

**Comment by mgagliardo** [comment]
> @mgagliardo All good, I'm aware of the env, you posted my _exact_ workaround in the OP wink

Right, I see you edited and I did not refresh the post though, Cheers! :)
