### ISSUE TITLE
Version  0.12.7 released by not yet published to pypi.org

### ISSUE THREAD

**Issue by afbarbaro** [localstack/localstack#3723]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description
Release 0.12.7 is available for download here: https://github.com/localstack/localstack/releases/tag/v0.12.7
but it's not yet published as a pip package so it can't be pulled via `pip`.  Version 0.12.6 is the latest published on pypi.org: https://pypi.org/project/localstack/

...

## Expected behavior
Latest package should be available in pypi.org
...

## Actual behavior
Previous version (0.12.6) is the latest available.
...

# Steps to reproduce

## Command used to start LocalStack
N.A.
...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
N.A.
...

**Comment by whummer** [comment]
Thanks for bringing this to our attention @afbarbaro ! Version `0.12.7` has now been pushed to pypi. Thanks
