### ISSUE TITLE
[IoT] [Pro] Missing commands

### ISSUE THREAD

**Issue by MathiasKoch** [localstack/localstack#3733]
It seems like there are some basic commands missing in the IoT service.
Is it documented anywhere, which commands are implemented and which are still missing?

So far it seems like
- `get-policy`
- `attach-policy`
- `attach-thing-principal`

is missing/not working

Also the `describe-endpoint` seems to return correct endpoint if omitting the `--endpoint-type`, but wrong if `--endpoint-type iot:Data` or `--endpoint-type iot:Data-ATS`

**Comment by whummer** [comment]
Hi @MathiasKoch , thanks for reporting this issue. This should be fixed in the meantime - can you please pull the `latest` version and give it another try? 

In terms of the endpoints - we are currently returning the local endpoints like, e.g., `localhost:4510`. It seems that for `iot:Data` and `iot:Data-ATS` AWS is simply returning different hostnames for these particular endpoint types - is there anything particular you would have expected , or can you please share some details how you are connecting to these endpoints?

Please let us know if there are any other issues. Thanks for your help!

**Comment by MathiasKoch** [comment]
@whummer 
Thanks for fixing this so quickly.

Regarding the `--endpoint-type`, this is what AWS reports back:
```
➜  aws iot describe-endpoint
{
    "endpointAddress": "xxxxxxxxxxxxxx.iot.eu-west-1.amazonaws.com"
}
➜  aws iot describe-endpoint --endpoint-type iot:Data
{
    "endpointAddress": "xxxxxxxxxxxxxx.iot.eu-west-1.amazonaws.com"
}
➜  aws iot describe-endpoint --endpoint-type iot:Data-ATS
{
    "endpointAddress": "xxxxxxxxxxxxxx-ats.iot.eu-west-1.amazonaws.com"
}
```

I think it would make sense for localstack to just return `localhost:4510` in all three cases, as localstack deos not distingush between ATS (Amazon Trust Service), and legacy certificates.

**Comment by MathiasKoch** [comment]
I still seem to have an issue with `attach-policy`. The other commands works great now! Thanks.

➜  awslocal iot list-policies
{
    "policies": [
        {
            "policyName": "ThingPolicyFbduo",
            "policyArn": "arn:aws:iot:eu-west-1:000000000000:policy/ThingPolicyFbduo"
        }
    ]
}
➜  awslocal iot list-certificates
{
    "certificates": [
        {
            "certificateArn": "arn:aws:iot:eu-west-1:1:cert/97ceb1c5b05fbc04ef612945c77ba9755121572b6854f90aa00ec762abf649b2",
            "certificateId": "97ceb1c5b05fbc04ef612945c77ba9755121572b6854f90aa00ec762abf649b2",
            "status": "ACTIVE",
            "creationDate": 1616057423.161369
        }
    ]
}
➜ awslocal iot attach-policy --policy-name ThingPolicyFbduo --target arn:aws:iot:eu-west-1:1:cert/97ceb1c5b05fbc04ef612945c77ba9755121572b6854f90aa00ec762abf649b2

An error occurred (ResourceNotFoundException) when calling the AttachPolicy operation: The specified resource does not exist

**Comment by whummer** [comment]
Thanks for the update @MathiasKoch . These issues (attach-policy and ARN mismatch) should be fixed in the meantime - can you please give it another try with the `latest` image? Thanks for your help!
