### ISSUE TITLE
Unsupported API Gateway V2 API GET /v2/apis

### ISSUE THREAD

**Issue by ne0guille** [localstack/localstack#3735]
# Type of request: This is a ...

[x ] bug report
[ ] feature request

# Detailed description
Having this error when trying to create an ApiGatewayV2::Api with cloudformation, im running this on linux ubuntu 18.04
```
localstack_1  | 2021-03-16T18:11:27:DEBUG:localstack.utils.cloudformation.template_deployer: Running action "create" for resource type "ApiGatewayV2::Api" id "Api"
localstack_1  | 2021-03-16T18:11:27:DEBUG:localstack.utils.cloudformation.template_deployer: Request for resource type "ApiGatewayV2::Api" in region us-east-1: create_api {'Name': 'DEV-api-gateway', 'ProtocolType': 'HTTP'}
localstack_1  | 2021-03-16T18:11:27:INFO:localstack_ext.services.apigateway.apigateway_extended: Unsupported API Gateway V2 API GET /v2/apis
localstack_1  | 2021-03-16T18:11:27:DEBUG:localstack.utils.cloudformation.template_deployer: Extract resource attribute: ApiGatewayV2::Api PhysicalResourceId
localstack_1  | 2021-03-16T18:11:27:INFO:localstack_ext.services.apigateway.apigateway_extended: Unsupported API Gateway V2 API GET /v2/apis
localstack_1  | 2021-03-16T18:11:27:INFO:localstack.utils.cloudformation.template_deployer: Unable to determine PhysicalResourceId for "ApiGatewayV2::Api" resource, ID "Api"
```
...

## Expected behavior

Api gateway v2 created successfully
...

## Actual behavior

...

# Steps to reproduce

Create a new Api gateway v2 on CFT
```
  Api:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: Dev-api-gateway
      ProtocolType: HTTP
```

## Command used to start LocalStack
docker compose
## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
awslocal cloudformation create-stack --stack-name name --parameters file://parameters.json --template-body file://gateway.yml

**Comment by thrau** [comment]
This feature is available in LocalStack pro. Should you have problems with the pro version, please let us know in Slack, thanks!
