### ISSUE TITLE
[Lambda] [Pro] Missing environment variables for provided lambda runtime

### ISSUE THREAD

**Issue by MathiasKoch** [localstack/localstack#3740]
It seems like there are some environment variables missing for lambda containers when running provided runtimes?
This is  from inside a lambda container:
```
bash-4.2# printenv | grep AWS_LAMBDA
AWS_LAMBDA_FUNCTION_VERSION=$LATEST
AWS_LAMBDA_FUNCTION_TIMEOUT=10
AWS_LAMBDA_FUNCTION_NAME=ms-device-provisioner-provision
AWS_LAMBDA_FUNCTION_INVOKED_ARN=arn:aws:lambda:eu-west-1:000000000000:function:ms-device-provisioner-provision
AWS_LAMBDA_COGNITO_IDENTITY=
bash-4.2# ls
bootstrap
```

And this is the requirements of the `lambda-http` runtime for rust (https://github.com/awslabs/aws-lambda-rust-runtime/blob/d3ff4352c4b0e64fb46af2ca425db39211237e26/lambda-runtime/src/lib.rs#L55-L65):

```
endpoint: env::var("AWS_LAMBDA_RUNTIME_API")?,
function_name: env::var("AWS_LAMBDA_FUNCTION_NAME")?,
memory: env::var("AWS_LAMBDA_FUNCTION_MEMORY_SIZE")?.parse::<i32>()?,
version: env::var("AWS_LAMBDA_FUNCTION_VERSION")?,
log_stream: env::var("AWS_LAMBDA_LOG_STREAM_NAME")?,
log_group: env::var("AWS_LAMBDA_LOG_GROUP_NAME")?,
```

I think especially the `AWS_LAMBDA_RUNTIME_API` is crucial?

**Comment by whummer** [comment]
Thanks for the update @MathiasKoch . This should (hopefully) be fixed in the meantime - we were able to get the `lambda-http` runtime for Rust running. Can you please give it another try with the `latest` image? Please let us know if the problem persists. Thanks for your help!
