### ISSUE TITLE
SQS Access to Other containers and host at the same time

### ISSUE THREAD

**Issue by joelhess** [localstack/localstack#3742]
# Type of request: This is a ...

[ ] bug report
[ ] feature request
[x] Question?

# Detailed description
I'm trying to set up localstack in docker so that other containers running on the same docker network can access it, as well as the host. I've set the `HOSTNAME_EXTERNAL` prop, and my other container can talk to it just fine. Now when I try and access the queue my host, the queue URL's returned back to me have the value from `HOSTNAME_EXTERNAL` and are no longer valid because that name can't be resolved by the host. Is there a way to configure localstack to be able to use SQS from both angles simultaneously?
...

## Expected behavior
To be able to talk to SQS on Localstack from another container and the host simultaneously.
...

## Actual behavior
QueueUrl returned back contains a host that only works for one of them at a time.
...

# Steps to reproduce

## Command used to start LocalStack

...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

...

**Comment by mgagliardo** [comment]
Hello @joelhess, can you please put an example so I can try reproduce the issue?

IMHO there should not be any need to set `HOSTNAME_EXTERNAL`, as it should be enough with the container name (which you can set with docker) to resolve it, then you can use `localhost` for your (duh) local tests.

Example (I'm doing it over CLI but you get the point:

```
$ docker run -d --rm --name localstack -p 4566:4566 localstack/localstack:latest
```
```
$ docker run -ti --link localstack --rm -e AWS_ACCESS_KEY_ID=test -e AWS_SECRET_ACCESS_KEY=test amazon/aws-cli --region=us-east-1 --endpoint=http://localstack:4566 sqs create-queue --queue-name test
{
    "QueueUrl": "http://localhost:4566/000000000000/test"
}
```

```
$ awslocal sqs list-queues
{
    "QueueUrls": [
        "http://localhost:4566/000000000000/test"
    ]
}
```

**Comment by joelhess** [comment]
I agree, and you are correct about running the local tests. But when the other container tries to access localstack the same way, it will get localhost back in the queue url, and will not be able to use that URL returned from the getQueue URL call  (i.e. http://localhost:4566/...) to continue talking to localstack.

**Comment by mgagliardo** [comment]
Right, then what you can do is simply edit your hosts file on your own machine so:

`127.0.0.1 localstack`

What happens with that is that your machine needs to know the IP (whether is local or not) of localstack

**Comment by joelhess** [comment]
That'll work once, but I can't automate it for tests running in a CI job.

**Comment by mgagliardo** [comment]
> That'll work once, but I can't automate it for tests running in a CI job.

Ok, then I need to know your usecase, why couldn't you run everything on your CI from another container?

i.e.
- run localstack (background) with `HOSTNAME_EXTERNAL` set
- run container X (creates sqs queue, etc.)
- run container Y (verifies container X work)

**Comment by mgagliardo** [comment]
I am closing this though, as this is far from being related to localstack, but more to networking/docker. So not a proper issue.
