### ISSUE TITLE
CloudFormation : Ref call on SQS does not return correct URL

### ISSUE THREAD

**Issue by codan84** [localstack/localstack#3748]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

In CloudFormation, when using `Ref` function with SQS logical resource ID as a parameter we would expect to get a URL for the queue ([docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-sqs-queues.html)).  
When setting `HOSTNAME_EXTERNAL` and `HOSTNAME` on the localstack container, we would expect this queue URL to have that hostname. However, it does not - it is still set to localhost!

## Expected behavior

If `HOSTNAME_EXTERNAL` and `HOSTNAME` are set to a certain value (ie `localstack`), this is reflected in the queue URL. So `Ref` on the queue should return:
`http://localstack/000000000000/my-awesome-queue`

## Actual behavior

The `Ref` call still returns `localhost` as the host:
`http://localhost/000000000000/my-awesome-queue`

# Steps to reproduce

1. Create a CloudFormation template with a Lambda and SQS.
2. In Lambda environment section add
```
"Environment": {
  "Variables": {
    "MY_QUEUE_URL": {
      "Ref": "MyQueueLogicalId"
    }
  }
},
```
3. Deploy to localstack
4. Check the actual populated environment variable of the lambda (or log it and trigger the lambda)

## Temp workaround

In JS lambdas I have temporarily fixed it like so:
```
//TODO: remove replace once this issue in localstack is fixed
const queueUrl = process.env.LOCALSTACK_HOSTNAME
  ? process.env.MY_QUEUE_URL.replace('localhost', process.env.LOCALSTACK_HOSTNAME)
  : process.env.MY_QUEUE_URL
```

## Command used to start LocalStack

N/A

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

N/A

**Comment by mgagliardo** [comment]
Hello @codan84, I was unable to reproduce this, I am using the following JSON (I know it's a bit longer than SQS/Lambda, my bad about that) and I am seeing everything working as expected, would you please pull the `latest` image and check it out?

[test-bucket-notification.json.zip](https://github.com/localstack/localstack/files/6167808/test-bucket-notification.json.zip)
