### ISSUE TITLE
Cannot execute queries against RDS data service

### ISSUE THREAD

**Issue by ericderegt** [localstack/localstack#3770]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description
I'm trying to write to and query a RDS database using the rdsdataservice in LocalStack (I have a pro account). I'm following the steps in the guide, but when I execute statements from my code I'm not able to connect to the database. I've verified that I can connect to the database with awslocal from within the container after creating the database cluster. When I run my AWS SDK code first it says it can't start an RDS proxy listener and then on subsequent retries I get a connection refused.
...

## Expected behavior
Should not return an error.
...

## Actual behavior
I'm getting a 500 in my code. When I look at the logs I see

```
localstack_ext.services.rds.rds_listener: Unable to start RDS proxy listener for ports 4510->35695: "<socket.socket fd=69, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('172.20.0.2', 4510), raddr=('172.20.0.2', 41268)> (FD 69) is already registered"
```

On subsequent attempts to run this code I get

```
psycopg2.OperationalError: could not connect to server: Connection refused Is the server running on host "bf80e87db" (172.20.0.2) and accepting TCP/IP connections on port 4510?
```

I've tried restarting the docker-compose and I get the same issue.
...

# Steps to reproduce
1. docker-compose up
2. exec into docker container
3. awslocal rds create-db-cluster --db-cluster-identifier test_cluster --engine aurora-postgresql
4. awslocal secretsmanager create-secret --name dbpass --secret-string test
5. awslocal rds create-db-instance --db-instance-identifier test_db --db-cluster-identifier test_cluster --db-instance-class c1 --engine aurora-postgresql
6. awslocal rds-data execute-statement --database test --resource-arn arn:aws:rds:us-east-1:000000000000:cluster:test_cluster --secret-arn arn:aws:secretsmanager:us-east-1:1234567890:secret:secret_name --sql 'SELECT 123' ----- this succeeds
7. Run Go rdsdataservice code to create table, insert row, query row, etc

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
```
         sql := "CREATE TABLE users_test....."
	input := rdsdataservice.ExecuteStatementInput{
		Database:    aws.String(os.Getenv("AURORA_DATABASE_NAME")),
		ResourceArn: aws.String(os.Getenv("AURORA_ARN")),
		SecretArn:   aws.String(os.Getenv("SECRETS_MANAGER_ARN")),
		Sql:         aws.String(sql),
	}

	_, err := rdsSvc.ExecuteStatement(&input)
```
...

**Comment by whummer** [comment]
Thanks for reporting @ericderegt . Can you please share a few more details about your environment - which Docker image tag/age are you using. The startup logs should contain something like this - can you please share the output: 
```
LocalStack version: 0.12.8
LocalStack Docker image id: 036a7e8a793d
LocalStack build date: 2021-03-20
LocalStack build git hash: 537fcee
```
Thanks for your help!

**Comment by ericderegt** [comment]
I don't see the other lines you mentioned, but I see LocalStack version: 0.11.3. I can try to upgrade and see if that fixes the issue. I didn't realize I wasn't on the latest version.

**Comment by whummer** [comment]
Thanks for the update @ericderegt . Looks like you're using a fairly old version of the Docker image (the latest version is `0.12.9`, and we have pushed various changes and improvements since `0.11.3`). Can you please do a `docker pull localstack/localstack` and give it another try? Please keep us posted how it goes. Thanks!
