### ISSUE TITLE
Networking Error while accessing aws services from lambda

### ISSUE THREAD

**Issue by HardikShah-PFG** [localstack/localstack#3771]
# Type of request: This is a Bug report.

# Detailed description
While accessing the file from S3 or record from dynamodb, getting below error. 
2021-03-23T13:39:21.131Z c5b7c577-213d-12aa-83bd-88abf8770d72 INFO { Error: Client network socket disconnected before secure TLS connection was established

> at TLSSocket.onConnectEnd (_tls_wrap.js:1125:19)

> at Object.onceWrapper (events.js:286:20)

> at TLSSocket.emit (events.js:203:15)

> at TLSSocket.EventEmitter.emit (domain.js:448:20)

> at endReadableNT (_stream_readable.js:1145:12)

> at process._tickCallback (internal/process/next_tick.js:63:19)

> message:

> 'Client network socket disconnected before secure TLS connection was established',

> code: 'NetworkingError',

> path: null,

> host: 'ls-s3-sample.s3.amazonaws.com',

> port: 443,

> localAddress: undefined,

> region: 'us-east-1',

> hostname: 'ls-s3-sample.s3.amazonaws.com',

> retryable: true,

> time: 2021-03-23T13:39:21.127Z }

## Expected behavior

.

## Actual behavior

...

# Steps to reproduce

## Command used to start LocalStack

docker-compose up

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

aws lambda invoke --function-name GetItem --profile localstack --endpoint-url http://localhost:4566/ out.txt --log-type Tail --query 'LogResult' --output text

--Lambda code:
// dependencies
  const AWS = require('aws-sdk');

  // get reference to S3 client
  const s3 = new AWS.S3();

  exports.handler = async (event, context, callback) => {
try {
          const params = {
              Bucket: srcBucket,
              Key: srcKey
          };
          var origimage = await s3.getObject(params).promise();

      } catch (error) {
          console.log(error);
          return;
      }  
}

**Comment by mgagliardo** [comment]
Hello @HardikShah-PFG, you are not calling the right endpoint, that is why you are seeing:

`host: 'ls-s3-sample.s3.amazonaws.com',`

You should be calling it the following (as example):
```
const s3 = new AWS.S3({ 
    accessKeyId: "1234", 
    secretAccessKey: "5678", 
    endpoint: new AWS.Endpoint('http://localhost:4566'), 
    s3ForcePathStyle: true, 
  
});
```

Give it a try and let me know how it goes. Cheers

**Comment by HardikShah-PFG** [comment]
Thanks @mgagliardo . Now got a different error. 
> 2021-03-23T14:19:28.874Z b395d8d0-2716-1e85-2b8c-b1f85bda8a59 INFO { Error: connect ECONNREFUSED 127.0.0.1:4566

> at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)

> message: 'connect ECONNREFUSED 127.0.0.1:4566',

> errno: 'ECONNREFUSED',

> code: 'NetworkingError',

> syscall: 'connect',

> address: '127.0.0.1',

> port: 4566,

> region: 'us-east-1',

> hostname: 'localhost',

> retryable: true,

> time: 2021-03-23T14:19:28.866Z }

**Comment by mgagliardo** [comment]
My mistake, pasted a typo:

Instead of:
```
    endpoint: new AWS.Endpoint('http://localhost:4566'), 
```

It should be `process.env.LOCALSTACK_HOSTNAME`, like this (for example):
```
const S3HOST = process.env.LOCALSTACK_HOSTNAME
const AWS = require('aws-sdk');
const s3 = new AWS.S3({ 
    accessKeyId: "1234",
    secretAccessKey: "5678",
    endpoint: new AWS.Endpoint(`http://${S3HOST}:4566`),
    s3ForcePathStyle: true,
});
```

**Comment by HardikShah-PFG** [comment]
Thanks. It worked!

**Comment by mgagliardo** [comment]
Glad to help. Cheers.
