### ISSUE TITLE
RDS Mysql Engine support

### ISSUE THREAD

**Issue by AritraWork97** [localstack/localstack#3772]
# Type of request: This is a ...

[ ] bug report
[* ] feature request

# Detailed description

Currently RDS supports database engine of only postgres. The mysql engine is also used by many people and if this functionality is implemented it would be very useful.
...

## Expected behavior

...

## Actual behavior

...

# Steps to reproduce

## Command used to start LocalStack

...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

...

**Comment by whummer** [comment]
Thanks for reporting @AritraWork97 . This is now supported in the meantime - can you please pull the `latest` Docker image and give it another try? Please let us know if there are any issues. Thanks!

**Comment by tamirhad** [comment]
Hey @whummer,
I am trying to create a new RDS mysql instance with no luck, I can see the following process inside localstack container:
`mysqld --user localstack --datadir=/tmp/localstack/data/rds-data-mysql/us-west-2/test/data --bind-address=0.0.0.0 --port 4510 --socket /tmp/mysql-states/96622051/mysqld.sock --pid-file=/tmp/mysql-states/5a44faf5/mysqld.pid --skip-networking=0`
in fact I can log in to mysql inside the container using the socket: `mysql -u root -p -S /tmp/mysql-states/96622051/mysqld.sock`
but i need to log in to mysql via tcp outside the container, is it possible sonehow?

**Comment by whummer** [comment]
Hi @tamirhad , thanks for reaching out. Can you please make sure that the following port range is configured for the LocalStack container (e.g., in docker-compose.yml):
```
ports:
  - "4510-4530:4510-4530"
```

Hope that helps - please keep us posted how it goes. Thanks!

**Comment by tamirhad** [comment]
Thanks for the quick answer!
I managed to fix that, I used localhost instead of 127.0.0.1(which is using socket by default)

**Comment by tamirhad** [comment]
Hey,
It seems like the root user does not have enough permissions.
this is the log from the container: `2021-11-28T16:46:58:INFO:localstack_ext.services.rds.db_utils: Starting MySQL RDS server on port 4510 (backend port 4510) - database "test", user "root"`
root user permissions:
`GRANT ALL PRIVILEGES ON "test".* TO "root"@%`
why root gets permissions to the test schema only, is it configurable? in contrast to RDS where the root user gets permissions to everything
