### ISSUE TITLE
Can't create a mock repo on ECR

### ISSUE THREAD

**Issue by conan19842002** [localstack/localstack#3775]
# Type of request: This is a bug 

[x] bug report
[ ] feature request

# Detailed description
I am trying to create a mock repo on ECR but got error 'Connection was closed before we received a valid response from endpoint URL: "http://localhost:4566/'
...

## Expected behavior
A mock repo should be created
...

## Actual behavior
Connection was closed before we received a valid response from endpoint URL: "http://localhost:4566/"
...

# Steps to reproduce
1. Start localstack with serverless service
2. Create a mock repo
## Command used to start LocalStack
docker-compose.yml:
```
version: '3.5'

services:
  localstack:
    image: localstack/localstack:0.10.4
    container_name: localstack
    ports:
      - "4566-4599:4566-4599"    
    environment:
      - SERVICES=s3,lambda,ecr,iam
      - HOSTNAME_EXTERNAL=127.0.0.1
      - LAMBDA_EXECUTOR=local
      - DEFAULT_REGION=eu-west-1
      - LAMBDA_REMOVE_CONTAINERS=false
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEBUG=${DEBUG}
    volumes:
      - "${TMPDIR}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```
...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
Create a mock repo:
```
awslocal ecr create-repository --endpoint-url=http://localhost:4566 --repository-name mock-repo
```

**Comment by mgagliardo** [comment]
Hello @conan19842002, as you can see, this feature is still not available for the OSS version, although it is for the PRO.
```
localstack.utils.server.http2_server.HTTPErrorResponse: Unable to find listener for service "ecr"
```
Closing as dupliated per https://github.com/localstack/localstack/issues/970
