### ISSUE TITLE
s3:PutLifecyclePolicy always returns HTTP/500 due to enforced DNS bucket names

### ISSUE THREAD

**Issue by synfinatic** [localstack/localstack#3780]
# Type of request: This is a ...

[ x] bug report
[ ] feature request

# Detailed description

This seems to be a regression in the latest docker image.  Basically putting a S3 bucket policy:

```
PUT /xxx-xx-xxx.000000000000.us-east-1.xxxx?lifecycle= HTTP/1.1
Host: localhost:4566
User-Agent: aws-sdk-go/1.32.12 (go1.13.7; darwin; amd64) APN/1.0 HashiCorp/1.0 Terraform/0.12.29 (+https://www.terraform.io)
Content-Length: 451
Authorization: AWS4-HMAC-SHA256 Credential=NOSUCH_KEY_ID/20210324/us-east-1/s3/aws4_request, SignedHeaders=content-length;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=9b749f5be6793cd04057b54c00775b764470de3fa4d8304d20c5110258cb746a
Content-Md5: TIs5aMSOWy8nG0Nhn6jOfg==
X-Amz-Content-Sha256: 831c755194258ddeb4488ff5ca8ee8634db2b043709e52125d2126736ebf2842
X-Amz-Date: 20210324T200233Z
Accept-Encoding: gzip
Connection: close

<LifecycleConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Rule><AbortIncompleteMultipartUpload><DaysAfterInitiation>7</DaysAfterInitiation></AbortIncompleteMultipartUpload><Expiration><Days>1</Days></Expiration><Filter><Prefix></Prefix></Filter><ID>Server Access Logs Lifecycle rule</ID><NoncurrentVersionExpiration><NoncurrentDays>1</NoncurrentDays></NoncurrentVersionExpiration><Status>Enabled</Status></Rule></LifecycleConfiguration>
```

Returns a HTTP/500:

```
HTTP/1.1 500 
content-type: text/html; charset=utf-8
content-length: 2
date: Wed, 24 Mar 2021 20:02:33 GMT
server: hypercorn-h11
Connection: close

{}
```

The log seems to explain the issue is that incorrectly assuming/forcing DNS compatible bucket names for the call:

2021-03-24T20:14:06:WARNING:localstack.utils.server.http2_server: Error in proxy handler for request PUT http://localhost:4566/xxx-xx-xxx.000000000000.us-east-1.xxxx?lifecycle=: Bucket named xxx-xx-xxx.000000000000.us-east-1.xxxx is not DNS compatible. Virtual hosted-style addressing cannot be used. The addressing style can be configured by removing the addressing_style value or setting that value to 'path' or 'auto' in the AWS Config file or in the botocore.client.Config object. Traceback (most recent call last):

## Expected behavior

HTTP/200 and attach the policy to the specified bucket

## Actual behavior

After 2min it fails to return correctly

# Steps to reproduce

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

Terraform code, but the above should be enough?

**Comment by macnev2013** [comment]
Thanks for reporting @synfinatic. It would be great if you can also provide the terraform code. Thanks.

**Comment by synfinatic** [comment]
Example:

```
$ aws --endpoint-url=http://localhost:4566/ s3api put-bucket-lifecycle-configuration --bucket xxx-xx-xxx.000000000000.us-east-1.xxxx --lifecycle-configuration file://rule
```

contents of `rule`:
```json
{
    "Rules": [
        {
            "Status": "Enabled",
            "ID": "Test",
            "AbortIncompleteMultipartUpload": {
                "DaysAfterInitiation": 7
            }
        }
    ]
}
```

**Comment by whummer** [comment]
Hey @synfinatic , thanks for reporting. We recently added support for virtual host based addressing for S3 endpoints, which seems to have introduced this regression.

Can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists. Thanks for your help!

**Comment by synfinatic** [comment]
Works for me now.
