### ISSUE TITLE
Use of same Lambda code for Local, Pilot and Prod

### ISSUE THREAD

**Issue by HardikShah-PFG** [localstack/localstack#3784]
# Type of request: This is a Bug and/or feature request.

[ ] bug report
[ ] feature request

# Detailed description
To use other services in Lambda, we need to pass Id, key and Endpoint url as below.
```
const db = new AWS.DynamoDB.DocumentClient({ 
  accessKeyId: "1234",
  secretAccessKey: "5678",
  endpoint: new AWS.Endpoint(`http://${LocalStack_HOST}:4566`)
});
```
Due to this, we can't move the same code as it is to the actual AWS environment as it will not work or we need to set Id, Key, and endpoint in the environment variables. Most of the time, the Role will be assigned to Lambda to call other services which will not require Id and Key. What will be the best way to write lambda to avoid this kind of issue and have a seamless transition of code deployment to local to pilot to prod AWS. 
...

## Expected behavior
Endpoint url,id, key can be configured somewhere else and code will remain the same as it is deployed on AWS Lambda. 
...

## Actual behavior

...

# Steps to reproduce

## Command used to start LocalStack

...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

...

**Comment by mgagliardo** [comment]
Hello @HardikShah-PFG. As the dependency is not on localstack's side but more on the SDK side I would tell you there is nothing coming from the `localstack` team we can do about it, as the SDK already has the endpoints embedded and there is no other way to change that.

What I personally suggest you is (assuming you are running CI/CD jobs with test/build/deploy) you can have your tests `mock` the AWS SDK calls by overriding this class property (if that would be the case), or if it is a function that receives say a DB client you can even override it, that is the usual way of testing correctly.

I am closing this as it has little to do with localstsack itself, but please feel free to keep posting messages for discussion as I would like to help you in any case.
