### ISSUE TITLE
Creation of AWS Security Group Rule hangs using terraform

### ISSUE THREAD

**Issue by arussel** [localstack/localstack#3785]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description
Using a simple terraform project with only 3 resources, the creations hangs on creation of aws_security_group_rule even after we can see that the rule has been created. I have created a small project to reproduce the error:
I have created a small repo to show the problem:
https://github.com/arussel/terraform-localstack-aws_security_group_rule

## Expected behavior
terraform to return as soon as the rule is created

## Actual behavior
hangs 

# Steps to reproduce
see the project, we just need to run `TF_LOG=TRACE terraform apply`

## Command used to start LocalStack
docker with docker-compose, docker-compose file provided in the project

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
terraform

**Comment by dominikschubert** [comment]
Has been fixed in the meantime. Validated by a successful terraform apply of  https://github.com/arussel/terraform-localstack-aws_security_group_rule
