### ISSUE TITLE
LocalStack 0.12.8 tag missing

### ISSUE THREAD

**Issue by volphy** [localstack/localstack#3786]
Is there a reason why 0.12.8 release is not tagged in the git repository:
https://github.com/localstack/localstack/tags

whereas a relevant Docker image is available in the DockerHub registry:
https://hub.docker.com/r/localstack/localstack/tags?page=1&ordering=last_updated
?

Is 0.12.8 sufficiently stable or is using 0.12.7 still recommended?

**Comment by whummer** [comment]
Thanks for the pointer @volphy - this release has now also been tagged in Github and published to Pypi:
https://github.com/localstack/localstack/releases/tag/v0.12.8

Also, a new version `0.12.9` will be released shortly. Thanks for your help.
