### ISSUE TITLE
Looping while creating ses domain identity

### ISSUE THREAD

**Issue by vamshisiddarth** [localstack/localstack#3787]
# Type of request:

- [x] bug report

# Detailed description

I'm trying to create  ses domain identity resource on localstack 0.12.7 using the below code. It gets into the infinite loop once it is fired. When I use aws cli and list the identifiers, I'm able to see the one which I'm trying to create but the terraform is still stuck in the creating phase itself.

## Expected behavior

ses domain identity resource should be created and terraform should exit returning success message.

## Actual behavior

ses domain identity resource is being created but terraform is still stuck in the creation state.

# Steps to reproduce

execute the provided code

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

```tf
provider "aws" {
  access_key                  = "test"
  region                           = "us-east-1"
  s3_force_path_style   = true
  secret_key                  = "test"
  skip_credentials_validation = true
  skip_metadata_api_check     = true
  skip_requesting_account_id  = true

  endpoints {
    ses = "http://localhost:4566"
    route53 = "http://localhost:4566"
  }
}

resource "aws_route53_zone" "zone" {
  name = "test.com"
}

resource "aws_ses_domain_identity" "protocols" {
  domain   = aws_route53_zone.zone.name
}
```

Please let me know if you need anything else. TIA

**Comment by mgagliardo** [comment]
Hey @vamshisiddarth, would you please pull the `latest` docker image and give it a try? This should be fixed now. Please comment it out if needed, thanks!
