### ISSUE TITLE
Connect to external url from a Lambda made by localstack

### ISSUE THREAD

**Issue by rnjailamba** [localstack/localstack#3791]
# Type of request: This is a ...

[x] bug report 

# Detailed description

We have Cognito set up with Lambda triggers. The Lambda triggers work well till we do not request an external resource ex. localhost:5432 or google.com. The moment we do this we get an error of "Connection Refused".

## Expected behavior

The external resource should be accessible.

## Actual behavior

```
localstack    | > Using Lambda API Runtime target host: ''
localstack    | > Starting daemons...
localstack    | > Host '' resolves to '192.168.65.2'
localstack    | >     return getattr(self._sock,name)(*args)
localstack    | > error: [Errno 111] Connection refused
localstack    | > 
localstack    | > Unable to get response from DNS server at 192.168.65.2:53: <class 'socket.error'> [Errno 111] Connection refused Traceback (most recent call last):
```

# Steps to reproduce

## Command used to start LocalStack

`docker-compose up` with the below docker-compose.yml

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

docker-compose.yml

```
version: "3.7"
services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack}"
    image: localstack/localstack-full
    hostname: localstack
    networks:
      - mynet
    ports:
      - "4566-4599:4566-4599"
      - '8081:8080'      
      - 443:443      
    environment:
      - SERVICES=lambda,cognito,apigateway
      - LOCALSTACK_API_KEY=XYZ
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=docker      
      # - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-docker-reuse }
      - LAMBDA_REMOTE_DOCKER=false
      - LAMBDA_DOCKER_NETWORK=host
      - LAMBDA_REMOVE_CONTAINERS=true
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${PWD}/.localstack
    volumes:
      - "./.localstack:/tmp/localstack"      
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./bin:/docker-entrypoint-initaws.d
networks:
  mynet:
    external: true
    name: mynet
```

**Comment by mgagliardo** [comment]
Hello @rnjailamba, have you tried using `LAMBDA_DOCKER_DNS`? It is in the docs, you can setup your own DNS server with that.

**Comment by rnjailamba** [comment]
Thanks @mgagliardo @whummer. 
2 changes led to the fix -
`LAMBDA_EXECUTOR=docker-reuse` and
removing the quotes around "host"       -` LAMBDA_DOCKER_NETWORK="host"`
Simply hit localhost:8080 within the Lambda and got a 200 back.
