### ISSUE TITLE
Cannot find handler module when invoking Lambda

### ISSUE THREAD

**Issue by nalhabash** [localstack/localstack#3827]
# Type of request: This is a potential bug request

[x] bug report
[ ] feature request

# Detailed description

Hi ! 👋 
I'm trying to run a lambda function in a localstack docker container, but when I invoke it I run into this error:
```
{
    "StatusCode": 200,
    "FunctionError": "Unhandled",
    "LogResult": "",
    "ExecutedVersion": "$LATEST"
}
```

And in the logs I get:
`localstack    | 2021-04-04T18:45:23.337Z        undefined       ERROR   Uncaught Exception      {"errorType":"Runtime.HandlerNotFound","errorMessage":"index.handler is undefined or not exported","stack":["Runtime.HandlerNotFound: index.handler is undefined or not exported","    at Object.module.exports.load (/var/runtime/UserFunction.js:144:11)","    at Object.<anonymous> (/var/runtime/index.js:43:30)","    at Module._compile (internal/modules/cjs/loader.js:1063:30)","    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)","    at Module.load (internal/modules/cjs/loader.js:928:32)","    at Function.Module._load (internal/modules/cjs/loader.js:769:14)","    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)","    at internal/main/run_main_module.js:17:47"]}`

Could this be a bug ? I'm leaning more towards a mistake in my configuration, but I don't see it so far.

### Steps to reproduce:

Here are the relevant files from the directory:
```
.
├── build
│   └── index.js
│   └── index.zip //archive that only has index.js in it
├── docker-compose.yml
```

My `index.js`:
```
exports.handler = function(event) {
    return '200';
}
```

And my `docker-compose.yml`:
```
version: '3.4'

services:
  localstack:
    image: localstack/localstack
    ports:
      - '4566:4566'
    environment:
      DEFAULT_REGION: us-east-2
      DEBUG: 1
      LAMBDA_EXECUTOR: docker
      LAMBDA_REMOTE_DOCKER: 0
      HOST_TMP_FOLDER: ${TMPDIR}
      SERVICES: lambda,dynamodb,s3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./build:/tmp/localstack/build
```

### Lambda creation

After running `docker-compose up`, I create my function in the CLI (or in code with the CDK).
I tried both 
```
awslocal lambda create-function --function-name my-function --zip-file fileb://build/index.zip --handler index.handler --runtime nodejs14.x --role whatever 
``` 
and 
```
awslocal lambda create-function --function-name my-function --code S3Bucket="__local__",S3Key="/tmp/localstack/build" --handler index.handler --runtime nodejs14.x --role whatever 
```

### Lambda Invocation

Tried 3 ways:
- `aws cli: awslocal lambda invoke --function-name my-function --payload "{}" output.txt`
- With a node Lambda client
- With a POST request to `http://localhost:4566/2015-03-31/functions/my-function/invocations` with an empty body

## Expected behavior

Getting a 200 response

## Actual behavior
```
{
   "errorType": "Runtime.HandlerNotFound",
   "errorMessage": "index.handler is undefined or not exported"
}
```

**Comment by mgagliardo** [comment]
Hello @nalhabash, as stated in the docs:

```
false: your Lambda function definitions will be passed to the container by mounting a volume (potentially faster). This requires to have the Docker client and the Docker host on the same machine. Also, HOST_TMP_FOLDER must be set properly, and a volume mount like ${HOST_TMP_FOLDER}:/tmp/localstack needs to be configured if you're using docker-compose.
```

You seem to be missing the volume mount, for example: 
```
volumes:
   ...
   - ${PWD}/localstack_tmp:/tmp/localstack
```

See a very similar issue (if not duplicate) [here](https://github.com/localstack/localstack/issues/3518#issuecomment-768104607).

If you still need help please paste an example of your code so we can further debug.

Cheers!

**Comment by nalhabash** [comment]
Hi @mgagliardo ! Thanks a lot for the example ! Setting the proper `HOST_TMP_FOLDER` and a couple more things helped, and lambda gets invoked !!

A few points that were unclear to me in the docs:

- That `HOST_TMP_FOLDER` folder that I need to mount to /tmp/localstack doesn't need to be where my lambda handler code is.
- When creating the lambda with the `--code` option and S3Bucket set to `__local__` the S3Key value:
    - Should point to where the file is on the host
    - Absolutely needs to be an absolute path

**Comment by mgagliardo** [comment]
1. Correct, ir does not need to be where your code is, you just need to
make sure the environment variable is set and the volume is mounted.
2. I am not sure but I think you can use both. An example i always have
that works is:

 localstack_init/lambda.sh
```
...
    --code S3Bucket="__local__",S3Key="$LAMBDA_LOCAL" \
...
```

docker-compose.yml
```
...
environment:
      - LAMBDA_LOCAL=${PWD}/lambda
...
```

As you can see it is a full path but exposed as env var. So that should
work for sure.

Hope it helps. Cheers
