### ISSUE TITLE
What to do about failing boto3.client('sts').get_caller_identity()?

### ISSUE THREAD

**Issue by luminescent** [localstack/localstack#3832]
# Type of request: This is a ...

[ ] bug report
[x] feature request

I chose feature request but it's more of a request for advice!

# Detailed description

I am trying to create some lambdas in localstack. The create process fails because of this line of code: 
`        aws_identity = boto3.client('sts').get_caller_identity()`

Which fails with this exception: 

```
localstack_main |     raise caught_exception
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/endpoint.py", line 200, in _do_get_response
localstack_main |     http_response = self._send(request)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/endpoint.py", line 269, in _send
localstack_main |     return self.http_session.send(request)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/httpsession.py", line 351, in send
localstack_main |     raise ConnectionClosedError(
localstack_main | botocore.exceptions.ConnectionClosedError: Connection was closed before we received a valid response from endpoint URL: "https://sts.amazonaws.com/".
localstack_main | 

```

Which presumably means that behind the scenes the boto3 client tries to connect to AWS. Does localstack offer a similar endpoint that can be queried to get an identity? Then I could hopefully convince boto3 to call  an endpoint inside the container rather than make a call to AWS. 
This could be done via hosts redirection inside the container, or an env variable, etc, but it all hangs on localstack exposing an enpoint like that. 
Additionally I expect that the call to AWS, even if my container manages to connect to it, will fail anyway, so fixing the network error would not help!

## Expected behavior

I would like to know if the token/identity functionality exists in localstack so I could configure boto3 to use that.

Perhaps the docker componse file could contain an env variable that tells boto3 to use localstack instead. 

## Actual behavior

boto3 calls https://sts.amazonaws.com

# Steps to reproduce

## Command used to start LocalStack

`docker-compose up` (using the compose file taken from this repo)

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

Usual commands with `awslocal lambda create function --runtime python3.6`. 

Lambda's Python code contains snippets like this: 

```
import boto3 

aws_identity = boto3.client('sts').get_caller_identity()
aws_account = aws_identity['Account']
```

**Comment by mgagliardo** [comment]
Hello @luminescent, have you tried pointing your boto3 client to localstack's ENV var?

Example code (tested and working):

```
import boto3
from os import environ

LOCALSTACK_HOSTNAME = environ['LOCALSTACK_HOSTNAME']

def lambda_handler(event, context):
  aws_identity = boto3.client('sts', endpoint_url="http://" + LOCALSTACK_HOSTNAME + ":4566", aws_access_key_id='test', aws_secret_access_key='test', region_name='us-east-1').get_caller_identity()
  aws_account = aws_identity['Account']
  response = {
      "statusCode": 200,
      "body": "AWS Account: " + aws_account,
      "isBase64Encoded": False,
  }
  return response
```

output:
```
localstack_1  | 2021-04-06T10:31:07:DEBUG:localstack.services.awslambda.lambda_executors: Lambda arn:aws:lambda:eu-west-1:000000000000:function:test_lambda_py result / log output:
localstack_1  | {"statusCode":200,"body":"AWS Account: 000000000000","isBase64Encoded":false}
localstack_1  | > START RequestId: 6eb131d7-5f1f-13de-bbd3-0a07b9b3aec4 Version: $LATEST
localstack_1  | > END RequestId: 6eb131d7-5f1f-13de-bbd3-0a07b9b3aec4
localstack_1  | > REPORT RequestId: 6eb131d7-5f1f-13de-bbd3-0a07b9b3aec4	Init Duration: 225.20 ms	Duration: 70.65 ms	Billed Duration: 71 ms	Memory Size: 1536 MB	Max Memory Used: 36 MB
```

**Comment by luminescent** [comment]
Thank you, I didn't point to it as I didn't know what URL to use. 

It looks to be "http//$LOCALSTACK_HOSTNAME:4566" and I think that is what I needed to know, so that's excellent! 

I also didn't know if localstack has implemented support for getting the identity. 

I am closing this as it looks to do what I need. I will reopen if I don't get it to work.

**Comment by luminescent** [comment]
For anyone needing the same thing but trying to avoid specifying the endpoint_url everytime, I have a workaround using a reverse proxy, that intercepts the calls made to AWS endpoints and redirects them to localstack on 4566.

https://github.com/luminescent/localstack-reverse-proxy
