### ISSUE TITLE
Deployment project

### ISSUE THREAD

**Issue by 346180990** [localstack/localstack#3838]
# Type of request: This is a ...

[ ] bug report
[ ] feature request

# Detailed description

I want to use localstack as the production environment. I see that localstack is a test and development environment. Is there any problem for localstack as a production environment

## Expected behavior

...

## Actual behavior

...

# Steps to reproduce

## Command used to start LocalStack

...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

...

**Comment by mgagliardo** [comment]
Hello @346180990, as explained on the official documentation, LocalStack provides an `easy-to-use test/mocking framework` for developing Cloud applications. That being said, localstack is a testing framework and is recommended to run only CI tests/integration/etc. or for developing on your local machine, and `it is not meant` for production use.

Please let us know if there's anything else we can help or provide information. Cheers
