### ISSUE TITLE
create_integration_response cannot create a custom responseTemplate

### ISSUE THREAD

**Issue by RodriGuerra98** [localstack/localstack#3840]
# Type of request: This is a ...

[ ] bug report
[ X] feature request

# Detailed description
I am trying to run the combo of APIGW + Lambda asynchronously. Everything is working find but in the response of the APIGW I need to receive the requestId of the Lambda.  I guess the problem is in this line: https://github.com/localstack/localstack/blob/801109efe81da5d0cb943c7f73ec750b36da5f91/localstack/services/apigateway/apigateway_starter.py#L119 since the response_template variable is always set to None without having any option to add my custom template.
...

## Expected behavior
Body of the response from the APIGW: 
```
{ "requestId": requestId }
```

...

## Actual behavior
Body of the response:
```
{}
```
...

# Steps to reproduce
x-amazon-apigateway-integration section, everything works except the response. (The "if" is because when we work with sync petitions we need the body response from the lambda and when we work async we just need the requestId)
```
responses:
    default:
      statusCode: 200
      contentHandling: CONVERT_TO_TEXT
      responseTemplates:
        application/json: '
          #if($util.parseJson($input.json(''$.body'')).isEmpty())
            {
              "requestId": "$context.requestId"
            }
          #{else}
            $util.parseJson($input.json(''$.body''))
          #end'
```
## Command used to start LocalStack
.
...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

...

**Comment by KrishnanRanjithkumar** [comment]
Thanks for reporting @RodriGuerra98. Could you please share a small self-contained example/repo to reproduce this issue?
