### ISSUE TITLE
Cognito - InitiateAuth - client metadata not passed in Migration lambda trigger event

### ISSUE THREAD

**Issue by John-D8** [localstack/localstack#3841]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

When configuring a Migration lambda trigger in Cognito, then calling InitiateAuth to the Cognito service while passing some data in the ClientMetadata property, this data is not passed on to the lambda function inside the event.

## Expected behavior

ClientMetadata is expected to be passed in the event sent to the Migration lambda.

## Actual behavior

ClientMetadata & ValidationData are empty in the event received in the Migration lambda.

# Steps to reproduce

1) Define a user pool in Cognito with a Migration lambda trigger.
2) Try to authenticate to Cognito (InitiateAuth) with a user that does not exist in the user pool, and send some data inside the ClientMetadata property.
3) Event is sent to the defined lambda, however the event does not contain the client metadata.

According to [this](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_InitiateAuth.html#API_InitiateAuth_RequestSyntax) the client metadata should be passed inside the event.validationData.

Event received:

```
{"version":"$LATEST","triggerSource":"UserMigration_Authentication","region":"eu-west-1","userPoolId":"eu-west-1_6405dc80d47243d2a03fdba04a5657b5","callerContext":{"awsSdkVersion":"TODO","clientId":"<my_client_id>"},"request":{"userAttributes":{},"validationData":{},"clientMetadata":{},"username":"user@example.com","password":"pass"},"response":{},"userName":"user@example.com"}
```

## Command used to start LocalStack

...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

```
const cognito = new AWS.CognitoIdentityServiceProvider({ endpoint: 'http://localhost:4566'});
const clientId = '<my_client_id>';
const res = await cognito.initiateAuth({
        ClientId: clientId,
        AuthFlow: 'USER_PASSWORD_AUTH',
        AuthParameters: {
          USERNAME: 'user@example.com',
          PASSWORD: 'pass',
        },
        ClientMetadata: {
            'role': 'admin'
        }
    }).promise();
```

**Comment by whummer** [comment]
Thanks for reporting @John-D8 - this should (hopefully) be fixed in the meantime. Can you please pull the `latest` Docker image and give it another try? Please keep us posted how it goes. Thanks for your help!

**Comment by John-D8** [comment]
Seems to work, thanks!
