### ISSUE TITLE
/health endpoint should return `endpoint` names, not `service` names

### ISSUE THREAD

**Issue by synfinatic** [localstack/localstack#3842]
# Type of request: This is a ...

[ ] bug report
[X ] feature request

# Detailed description

Basically:
https://github.com/localstack/localstack#service-health-checks

But this really sucks because AWS doesn't always use the service name as the API endpoint name that you need to override.  For example, you don't connect to `cloudwatch`, you have to connect to `monitoring`.  And some services have multiple API endpoints: `kms` and `kms-fips` for example.

AWS Docs on cloudwatch: https://docs.aws.amazon.com/general/latest/gr/cw_region.html

## Expected behavior

Able to programmatically detect which API endpoints are available without building & maintaining a custom map of service names to endpoint names.

**Comment by whummer** [comment]
Thanks for this suggestion @synfinatic . The `/health` check endpoint is basically using the same service names as the ones that can be configured for the `SERVICES` configuration variable. We're basically using the service names defined in the [`boto3` library](https://boto3.amazonaws.com/v1/documentation/api/latest/index.html). 

Happy to make any adjustments in the service names to better suit your use case - can you please make a concrete proposal for the service name mapping, or ideally create a pull request for the same? Thanks for your help!

**Comment by synfinatic** [comment]
since this is tracking the service names per the `SERVICES` config variable, I'm going to withdraw this request.
