### ISSUE TITLE
Allow deployment of single JAR for Java Lambdas

### ISSUE THREAD

**Issue by whummer** [localstack/localstack#385]
AWS supports two forms of archives for deploying Java Lambda functions:
1. "Fat" JAR - single jar file with all dependencies
2. ZIP - zip archive with class files in `/` and jar files in `/lib`

http://docs.aws.amazon.com/lambda/latest/dg/lambda-java-how-to-create-deployment-package.html

LocalStack currently expects a single JAR file within a ZIP file, which is incompatible with what AWS expects.

**Comment by mapleoin** [comment]
Another thing which doesn't work is having a python handler in a subdirectory. It's the same piece of code which is to blame it seems to me: https://github.com/localstack/localstack/blob/master/localstack/services/awslambda/lambda_api.py#L373-L391

**Comment by hypergori** [comment]
Hi, localstack still does not allow the java lambda zip package with multiple jars in lib folder.
https://docs.aws.amazon.com/lambda/latest/dg/create-deployment-pkg-zip-java.html
And raises the error "the CreateFunction operation: Expected exactly one *.jar entry in zip file, found 78"

**Comment by whummer** [comment]
Thanks for the pointer @hypergori . This should now finally be fixed in #1820 - please drop a short note here if the problem persists. Thanks

**Comment by Azuaron** [comment]
I think there's still a problem here. I have a zip that works in AWS, but fails to load my classes in localstack. Structure:

```
.
| logback.xml
|-- com
    +-- company
        +-- project
            +-- package
                |-- LambdaFunctionHandler.class
                |-- Pojo.class
                +-- Utility.class
+-- lib
    |-- third.jar
    |-- party.jar
    +-- jars.jar
```

Response:

```
Exception in thread "main" java.lang.ClassNotFoundException: com.company.project.package.LambdaFunctionHandler
```

**Comment by martin-sommerseth** [comment]
> I think there's still a problem here. I have a zip that works in AWS, but fails to load my classes in localstack. Structure:
> 
> ```
> .
> | logback.xml
> |-- com
>     +-- company
>         +-- project
>             +-- package
>                 |-- LambdaFunctionHandler.class
>                 |-- Pojo.class
>                 +-- Utility.class
> +-- lib
>     |-- third.jar
>     |-- party.jar
>     +-- jars.jar
> ```
> 
> Response:
> 
> ```
> Exception in thread "main" java.lang.ClassNotFoundException: com.company.project.package.LambdaFunctionHandler
> ```

We have the same problem as Azuaron
