### ISSUE TITLE
SQS never becomes "ready" - stuck in "Waiting for all LocalStack services to be ready"

### ISSUE THREAD

**Issue by carlos-kubra** [localstack/localstack#3855]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description
SQS queues don't start correctly, and seem stuck in a starting state.

I am running local stack in Docker using docker compose with the following configuration:
```
  localstack:
    image: localstack/localstack
    expose:
      - "4566"
    ports:
      - "4566-4599:4566-4599"
      - "9001:9001"
    environment:
      - SERVICES=sqs,s3,sns
      - DEBUG=1
      - DEFAULT_REGION=us-east-1
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOSTNAME_EXTERNAL=localstack
    volumes:
      - ./data/localstack:/tmp/localstack
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./bin/localstack:/docker-entrypoint-initaws.d

  myjava-app:
    image: {javaImg}
    restart: always
    expose:
      - "8080"
      - "5005"
    ports:
      - "5005:5005"
      - "8080:8080"
```

I am attempting to connect using a container running a Java application in the same `Docker Daemon` but in a different `container`. 
These containers are both part of the default `bridge` network.

...

## Expected behavior
The SQS queues should be ready for requests within (n) minutes.

...

## Actual behavior
 - SQS queues never become "ready" for requests.  Waited for over 15 minutes.
 - Requests to SQS from the JVM result in an http connection timeout.
 - Requests using awslocal result in a connection timeout.
...

# Steps to reproduce
- Configure a Java application using `aws-java-sdk-sqs:1.11.415`
- Use the configuration provided in **Client code** below
- Start localstack and the Java app using `docker-compose -f docker-compose.yml up -d`

**Troubleshooting**
 - Curl to `localstack:4566` from the container running the JVM show local stack health endpoint as `{"status": "running"}`
 - `awslocal s3 ls` shows buckets as expected
 - `pip install --upgrade --no-cache localstack`
 -  - `docker logs {localStackContainer} -f` show
 ```
2021-04-09 23:21:20,104:API: 127.0.0.1 - - [09/Apr/2021 23:21:20] "POST /000000000000/private-bucket HTTP/1.1" 200 -
Waiting for all LocalStack services to be ready
Waiting for all LocalStack services to be ready
Waiting for all LocalStack services to be ready
2021-04-09 23:21:40,154:API: 127.0.0.1 - - [09/Apr/2021 23:21:40] "POST /000000000000/private-bucket HTTP/1.1" 200 -
Waiting for all LocalStack services to be ready
Waiting for all LocalStack services to be ready
Waiting for all LocalStack services to be ready
2021-04-09 23:22:00,198:API: 127.0.0.1 - - [09/Apr/2021 23:22:00] "POST /000000000000/private-bucket HTTP/1.1" 200 -
Waiting for all LocalStack services to be ready
Waiting for all LocalStack services to be ready
Waiting for all LocalStack services to be ready
2021-04-09 23:22:20,246:API: 127.0.0.1 - - [09/Apr/2021 23:22:20] "POST /000000000000/private-bucket HTTP/1.1" 200 -
Waiting for all LocalStack services to be ready
Waiting for all LocalStack services to be ready
Waiting for all LocalStack services to be ready
2021-04-09 23:22:40,294:API: 127.0.0.1 - - [09/Apr/2021 23:22:40] "POST /000000000000/private-bucket HTTP/1.1" 200 -
Waiting for all LocalStack services to be ready
Waiting for all LocalStack services to be ready
2021-04-09 23:23:00,339:API: 127.0.0.1 - - [09/Apr/2021 23:23:00] "POST /000000000000/private-bucket HTTP/1.1" 200 -
Waiting for all LocalStack services to be ready
Waiting for all LocalStack services to be ready
Waiting for all LocalStack services to be ready
2021-04-09 23:23:20,385:API: 127.0.0.1 - - [09/Apr/2021 23:23:20] "POST /000000000000/private-bucket HTTP/1.1" 200 -
Waiting for all LocalStack services to be ready
Waiting for all LocalStack services to be ready
Waiting for all LocalStack services to be ready
2021-04-09 23:23:40,430:API: 127.0.0.1 - - [09/Apr/2021 23:23:40] "POST /000000000000/private-bucket HTTP/1.1" 200 -
Waiting for all LocalStack services to be ready
Waiting for all LocalStack services to be ready
Waiting for all LocalStack services to be ready
2021-04-09 23:24:00,479:API: 127.0.0.1 - - [09/Apr/2021 23:24:00] "POST /000000000000/private-bucket HTTP/1.1" 200 -
Waiting for all LocalStack services to be ready
```

## Command used to start LocalStack
`docker-compose -f docker-compose.yml up -d` on the docker yml above

...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
```
AmazonSQSAsync amazonSQS = AmazonSQSAsyncClientBuilder.standard()
      .withEndpointConfiguration(
          new AwsClientBuilder.EndpointConfiguration("http://localstack:4566", "us-east-1")
      )
      .withCredentials( credentialsProvider )
      .build();
  }
```
...

**Comment by mgagliardo** [comment]
Hello @carlos-kubra, quick question (maybe I did not understand clearly). You are running both applications at the same time from what I can see on the docker-compose.yml, but your Java app immediately starts running requests to localstack even if it is not up and running healthy? Is that so?

A couple things:
* Have you tried [waiting for](https://github.com/kassambara/docker-compose-wait-for-container) localstack to start before running queries against it?
* What is running on the localstack start? I can see you are mounting `docker-entrypoint-initaws.d`
* What happens if you run your app locally and waiting for localstack to be healthy instead of using docker on your app?

**Comment by carlos-kubra** [comment]
Hi @mgagliardo thanks for your quick reply, I have tried to start localstack up independently of the Java app and I still observe the same `Waiting for all LocalStack services to be ready`. 
I also get the same error running my Java app outside of Docker (locally) and waiting for localstack to become healthy. The odd part here is the health endpoint shows `{"status": "running"}` in either scenario (docker or local).

I have a few configurations and some awslocal commands in my `docker-entrypoint-initaws.d`

```
aws configure set aws_access_key_id ...
aws configure set aws_secret_access_key ...
aws configure set default.region ...

awslocal sqs create-queue --queue-name ...
awslocal s3api create-bucket --bucket ...
awslocal sns create-topic --name ...
awslocal sns subscribe ...
mkdir -p /tmp/localstack/data
```

**Comment by mgagliardo** [comment]
Hello again @carlos-kubra, thanks for answering.
I know it might sound silly but have you tried removing cached stuff (i.e. tmp or data directories which might), also pulling the `latest` docker image?

I have tried it myself with the latest image on my machine and could not reproduce the issue, I am guessing this is something local to your machine, specs:
```
macOS Big Sur Version 11.1 (20C69)
Docker version 20.10.5, build 55c4c88
```

DEBUG:
```
localstack_1  | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initaws.d/entrypoint.sh
localstack_1  | {
localstack_1  |     "QueueUrl": "http://localstack:4566/000000000000/test"
localstack_1  | }
localstack_1  | 2021-04-13 09:28:10,312:API: 127.0.0.1 - - [13/Apr/2021 09:28:10] "POST / HTTP/1.1" 200 -
localstack_1  | {
localstack_1  |     "Location": "/test"
localstack_1  | }
localstack_1  | 2021-04-13 09:28:11,069:API: 127.0.0.1 - - [13/Apr/2021 09:28:11] "PUT /test HTTP/1.1" 200 -
localstack_1  | {
localstack_1  |     "TopicArn": "arn:aws:sns:us-east-1:000000000000:test"
localstack_1  | }
localstack_1  |
localstack_1  | 2021-04-13 09:28:11,753:API: 127.0.0.1 - - [13/Apr/2021 09:28:11] "POST / HTTP/1.1" 200 -
localstack_1  | 2021-04-13 09:28:18,712:API: 127.0.0.1 - - [13/Apr/2021 09:28:18] "POST / HTTP/1.1" 200 -
localstack_1  | 2021-04-13T09:28:31:INFO:localstack.services.edge: Unable to find forwarding rule for host "localhost:4566", path "GET /health/", target header "", auth header "", data "b''"
```

```
$ awslocal sqs list-queues
{
    "QueueUrls": [
        "http://localstack:4566/000000000000/test"
    ]
}
```

**Comment by carlos-kubra** [comment]
I have not removed cached items just yet but I have run `pip install --upgrade --no-cache localstack`. I will attempt to clear every docker image out and restart from a clean state.

**Comment by carlos-kubra** [comment]
> I have not removed cached items just yet but I have run `pip install --upgrade --no-cache localstack`. I will attempt to clear every docker image out and restart from a clean state.

I have removed all local docker containers/images and rebuilt.

```
macOS Catalina 10.15.7
Docker version 20.10.5, build 55c4c88
```

```
Waiting for all LocalStack services to be ready
2021-04-13 19:30:34,367 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2021-04-13 19:30:34,369 INFO supervisord started with pid 15
2021-04-13 19:30:35,371 INFO spawned: 'dashboard' with pid 21
2021-04-13 19:30:35,373 INFO spawned: 'infra' with pid 22
2021-04-13 19:30:35,378 INFO success: dashboard entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2021-04-13 19:30:35,378 INFO exited: dashboard (exit status 0; expected)
(. .venv/bin/activate; exec bin/localstack start --host)
2021-04-13 19:30:36,380 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Starting local dev environment. CTRL-C to quit.

LocalStack version: 0.12.9.1
LocalStack build date: 2021-04-13
LocalStack build git hash: b1dc51bf

Starting edge router (https port 4566)...
Starting mock S3 service on http port 4566 ...
2021-04-13T19:30:39:INFO:localstack.utils.analytics.profiler: Execution of "load_plugin_from_path" took 3300.1391887664795ms
2021-04-13T19:30:39:INFO:localstack.utils.analytics.profiler: Execution of "load_plugins" took 3300.755023956299ms
2021-04-13T19:30:39:DEBUG:bootstrap.py: Loading plugins - scope "services", module "localstack": <function register_localstack_plugins at 0x7f28c25dcee0>
2021-04-13T19:30:39:INFO:localstack.multiserver: Starting multi API server process on port 40097
[2021-04-13 19:30:39 +0000] [23] [INFO] Running on http://0.0.0.0:40097 (CTRL + C to quit)
2021-04-13T19:30:39:INFO:hypercorn.error: Running on http://0.0.0.0:40097 (CTRL + C to quit)
[2021-04-13 19:30:39 +0000] [23] [INFO] Running on https://0.0.0.0:4566 (CTRL + C to quit)
2021-04-13T19:30:39:INFO:hypercorn.error: Running on https://0.0.0.0:4566 (CTRL + C to quit)
Starting mock SNS service on http port 4566 ...
Starting mock SQS service on http port 4566 ...
2021-04-13 19:30:40,893:API:  * Running on http://0.0.0.0:36641/ (Press CTRL+C to quit)
Waiting for all LocalStack services to be ready
```

**Comment by mgagliardo** [comment]
Are you using the localstack python client? Please note it might have side effects while using it on OS like Mac (i.e. firewall, 'privacy'  - settings - issues) as it tries to open ports on your local machine and listen on every interface, and Mac has side effects for that.

Could you please try on a clean directory using docker-compose (or docker run)?

**Comment by carlos-kubra** [comment]
This does fix it for me, thank you!

**Comment by mgagliardo** [comment]
Glad to help. Cheers

**Comment by odusseys** [comment]
Having the same issue. Creating a new directory solves this temporarily but after a while it reverts to this randomly.

**Comment by dpmedeiros** [comment]
My organization is having this issue as well, though we happen to be running through docker-compose.

I initially thought that rolling back to 0.12.6 fixed the issue, but then it started happening again.

Can we reopen this?

**Comment by CruncherBigData** [comment]
I am having the exact same issue, anyone got a solution ?

**Comment by johnrichardrinehart** [comment]
I'm having this same issue on `0.12.12`.

**Comment by shachar-av** [comment]
Also having this same issue on `0.12.12`

**Comment by shachar-av** [comment]
I think I may have got a way around that.. (running on mac)
in docker-compose.yml 'volumes' section, I added:

```
      - "./localstack_tmp:/tmp/"
```

and then before every run - make sure to delete this folder (`./localstack_tmp`)

**Comment by micogongob** [comment]
@shachar-av solution worked for me. Deleting the `localstack_tmp` directory every time before running the container.

**Comment by gwasky** [comment]
> 
> 
> I think I may have got a way around that.. (running on mac) in docker-compose.yml 'volumes' section, I added:
> 
> ```
>       - "./localstack_tmp:/tmp/"
> ```
> 
> and then before every run - make sure to delete this folder (`./localstack_tmp`)

This solution however clears "some" previously created resources

**Comment by odusseys** [comment]
this doesn't seem like a proper solution. Clearing volumes regularly is problematic if there is data which should not be cleared ...

**Comment by shachar-av** [comment]
> this doesn't seem like a proper solution. Clearing volumes regularly is problematic if there is data which should not be cleared ...

sure, it is a workaround, not a proper solution.

**Comment by kewur** [comment]
I was using the data dir to keep the created resoruces and populated data around, but now every time I restart my machine I'm having to clear the data dir and run the repopulation script. This used to work but then stopped working for some reason. I also think a proper solution is needed as clearing everything everytime is not a proper solution

**Comment by shachar-av** [comment]
> I think I may have got a way around that.. (running on mac) in docker-compose.yml 'volumes' section, I added:
> 
> ```
>       - "./localstack_tmp:/tmp/"
> ```
> 
> and then before every run - make sure to delete this folder (`./localstack_tmp`)

here's another possible workaround that recently worked for me, it might be better then previous suggested one as it removes much less data/state AFAIU:
```
rm localstack_tmp/hsperfdata_localstack/* ; docker-compose restart localstack
