### ISSUE TITLE
Cognito - InitiateAuth with Migration script throws UserNotFoundException

### ISSUE THREAD

**Issue by John-D8** [localstack/localstack#3857]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

Trying to authenticate using a migration lambda trigger which returns an existing user (exists in custom DB, does not exist yet in Cognito), results in a UserNotFoundException being thrown instead of returning successfully with tokens.
Same workflow works in real AWS Cognito.

## Expected behavior

InitiateAuth should return successfully with tokens (access token, refresh token & id token).

## Actual behavior

UserNotFoundException exception is thrown to the client.
In addition, the following errors appear in localstack logs:
```
localstack           | 2021-04-10T10:15:59:INFO:localstack_ext.services.cognito.cognito_helpers: Unable to find password config for username b979db72-8d63-4ff4-bcce-0cfa31859f05, aliases ['user@example.com']
localstack           | 2021-04-10T10:15:59:INFO:localstack_ext.services.cognito.cognito_listener: Error in Cognito action "InitiateAuth":
localstack           | 2021-04-10T10:15:59:INFO:localstack_ext.services.cognito.cognito_helpers: User does not exist.
```

# Steps to reproduce

1) Have some DB that contains a user.
2) Create a user pool with a Migration Lambda trigger defined, that returns the predefined user.
3) Call InitiateAuth with the existing user defined above.

## Command used to start LocalStack

Localstack is defined in docker-compose.yml

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

Client code:
```
  const cognito = new AWS.CognitoIdentityServiceProvider({ endpoint: 'http://localhost:4566' });
  const clientId = '<client_id>';
  try {
    const res = await cognito.initiateAuth({
        ClientId: clientId,
        AuthFlow: 'USER_PASSWORD_AUTH',
        AuthParameters: {
          USERNAME: 'user@example.com',
          PASSWORD: 'pass',
        },
        ClientMetadata: {
            'role': 'admin'
        }
    }).promise();
  } catch (err) {
     // throws UserNotFoundException
  }
```

Data returned by lambda:
```
{
	"version": "$LATEST",
	"triggerSource": "UserMigration_Authentication",
	"region": "eu-west-1",
	"userPoolId": "eu-west-1_2b31f3f1ff5340cc91bc47875a60caf2",
	"callerContext": {
		"awsSdkVersion": "TODO",
		"clientId": "<client_id>"
	},
	"request": {
		"userAttributes": {},
		"validationData": {},
		"clientMetadata": {},
		"username": "user@example.com",
		"password": "pass"
	},
	"response": {
		"userAttributes": {
			"email": "user@example.com",
			"email_verified": "true",
			"username": "user@example.com",
			"dev:custom:userId": "10685",
			"dev:custom:status": "invited"
		},
		"finalUserStatus": "CONFIRMED",
		"messageAction": "SUPPRESS"
	},
	"userName": "user@example.com",
}
```

**Comment by whummer** [comment]
Thanks for reporting @John-D8 - this should (hopefully) be fixed in the meantime. Can you please pull the `latest` Docker image and give it another try? Please keep us posted how it goes. Thanks for your help!

**Comment by John-D8** [comment]
Seems to work, thanks!
