### ISSUE TITLE
IsTruncated becomes PascalCase in ListMultipartUploads.

### ISSUE THREAD

**Issue by Hakuyume** [localstack/localstack#3865]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

`ListMultipartUploads` returns `<IsTruncated>False</IsTruncated>` where other APIs (e.g. `ListObjects`) return `<IsTruncated>false</IsTruncated>`. [Rusoto](https://github.com/rusoto/rusoto) does not work with localstack since it assumes lowercase.
## Expected behavior

Returns `<IsTruncated>false</IsTruncated>` (lowercase).

## Actual behavior

Returns `<IsTruncated>False</IsTruncated>` (PascalCase).

# Steps to reproduce

## Command used to start LocalStack
```
$ docker run --detach --env SERVICES=s3 --publish 4566:4566 localstack/localstack:0.12.9
```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
```
$ docker run --env AWS_ACCESS_KEY_ID=test --env AWS_SECRET_ACCESS_KEY=test --network host amazon/aws-cli --endpoint-url http://localhost:4566 s3api create-bucket --bucket foo
$ docker run --env AWS_ACCESS_KEY_ID=test --env AWS_SECRET_ACCESS_KEY=test --network host amazon/aws-cli --debug --endpoint-url http://localhost:4566 s3api list-multipart-uploads --bucket foo
...
2021-04-13 06:12:56,165 - MainThread - botocore.parsers - DEBUG - Response body:
b'<?xml version="1.0" encoding="UTF-8"?><ListMultipartUploadsResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Bucket>foo</Bucket><KeyMarker></KeyMarker><UploadIdMarker></UploadIdMarker><MaxUploads>1000</MaxUploads><IsTruncated>False</IsTruncated></ListMultipartUploadsResult>
...
```

**Comment by mgagliardo** [comment]
Created https://github.com/localstack/moto/pull/17 to fix this

**Comment by mgagliardo** [comment]
Once moto new release gets to localstack this will be solved. For now I'm closing this. Thanks for reporting it!
