### ISSUE TITLE
Cognito - ForgotPassword with migration lambda not working

### ISSUE THREAD

**Issue by yonatandbinahai** [localstack/localstack#3867]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

When calling Cognito ForgotPassword API for a user that doesn't exist in a user pool, and the user pool has a defined user migration lambda trigger - the migration lambda is not called, and an InternalServerError error is being thrown.

## Expected behavior

The migration lambda should be called with `UserMigration_ForgotPassword` as trigger source.
The returned user from the lambda should be used to continue the forgot password flow.

## Actual behavior

The migration lambda is not called, and the following error is being thrown to the client:
```
Error in Cognito action "ForgotPassword": An error occurred (UserNotFoundException) when calling the AdminGetUser operation: user@example.com
```

# Steps to reproduce

1) Define a user pool with a migration lambda trigger defined.
2) Send a  `ForgotPassword` call to Cognito in localstack with a username that doesn't exist in the user pool, but exists in my custom DB.

## Command used to start LocalStack

docker-compose

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

```
    const cognito = new AWS.CognitoIdentityServiceProvider({ endpoint: 'http://localhost:4566' });
    const clientId = '<client_id>';
    try {
      const res = await cognito.forgotPassword({
        ClientId: clientId,
        Username: 'user@example.com'
      }).promise();
      console.log(res);
    } catch (err) {
      console.log(err); // InternalServerError is thrown
    }
```

**Comment by whummer** [comment]
Hi @yonatandbinahai, apologies for the long delay on this one - we've just discovered this issue while cleaning up the backlog, and we believe that this issue should have been fixed in the meantime. Please do let us know if the problem persists.. Thanks!
