### ISSUE TITLE
LocalStack: Cloudformation Stack Filtering not working as expected

### ISSUE THREAD

**Issue by DanielMarquesBus** [localstack/localstack#3878]
# Type of request: This is a ...

[ x ] bug report
[ ] feature request

# Detailed description

When I try to list stacks and filter the stack status, it lists all the stacks rather than filter them out.

I saw someone had this issue before and was meant to be fixed, but doesnt seem like its fixed:
- https://github.com/localstack/localstack/issues/2698

## Expected behavior

Stacks should be filtered

## Actual behavior

All stacks are returned

# Steps to reproduce

Run latest docker version of localstack.
Create new stack
Try to run something like:
aws --endpoint-url=http://localhost:4566 cloudformation list-stacks --stack-status-filter DELETE_FAILED

It will return all stacks when it should return an empty list

## Command used to start LocalStack
docker run --network host -d -e DEFAULT_REGION="eu-west-1" localstack/localstack:latest

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
aws --endpoint-url=http://localhost:4566 cloudformation list-stacks --stack-status-filter DELETE_FAILED

Using boto3, the same thing happens:
response = self.__cloudformation_client.list_stacks(StackStatusFilter=['CREATE_FAILED'])

...

**Comment by GonzaloSaad** [comment]
Hello! Are you accepting any help on this issue? Or is it already a work in progress? I'd like to contribute!

**Comment by DanielMarquesBus** [comment]
Hi Gonzalo, as far as I know, no one seems to be working on it unless Whummer is doing something? Thanks for the help!

**Comment by GonzaloSaad** [comment]
Yes! I saw he assigned himself! Just for the fun at least I'll get into it! Is my first time actually in the code of localstack :eyes:, so wish me luck haha!

**Comment by whummer** [comment]
@GonzaloSaad please feel free to pick up this item - a PR would be much appreciated! 👍

**Comment by GonzaloSaad** [comment]
I was able to reproduce it on my end :partying_face: ! Working in the solution :muscle:

**Comment by whummer** [comment]
Thanks for contributing a fix @GonzaloSaad ! 👍 (@DanielMarquesBus the fix will become available in the `latest` Docker image shortly..)
