### ISSUE TITLE
S3 Service not starting on Ubuntu

### ISSUE THREAD

**Issue by clearmechris** [localstack/localstack#3882]
# Type of request: This is a ...

[ x] bug report
[ ] feature request

# Detailed description
s3 service will not start on ubuntu desktop, fails in an infite loop d
...

## Expected behavior
s3 service will start and be available locally.

...

## Actual behavior
This goes on forever:
Waiting for all LocalStack services to be ready
2021-04-16T13:29:52:WARNING:localstack.services.plugins: Service "s3" not yet available, retrying...
Waiting for all LocalStack services to be ready

After looping it will display the following message:
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/plugins.py", line 102, in check_infra
    check_service_health(api=name, print_error=print_error)
  File "/opt/code/localstack/localstack/services/plugins.py", line 121, in check_service_health
    raise e
  File "/opt/code/localstack/localstack/services/plugins.py", line 117, in check_service_health
    plugin.check(expect_shutdown=expect_shutdown, print_error=print_error)
  File "/opt/code/localstack/localstack/services/plugins.py", line 45, in check
    return self.check_function(expect_shutdown=expect_shutdown, print_error=print_error)
  File "/opt/code/localstack/localstack/services/s3/s3_starter.py", line 42, in check_s3
    assert isinstance(out['Buckets'], list)
TypeError: 'NoneType' object is not subscriptable

2021-04-16T13:31:45:INFO:localstack.utils.analytics.profiler: Execution of "start_api_services" took 129779.57606315613ms
2021-04-16 13:31:47,135 INFO exited: infra (exit status 2; not expected)
2021-04-16 13:31:47,136 INFO spawned: 'infra' with pid 618
ERROR: 'NoneType' object is not subscriptable
(. .venv/bin/activate; exec bin/localstack start --host)
make: *** [Makefile:54: infra] Error 1
...

# Steps to reproduce
localstack start

## Command used to start LocalStack

localstack start
...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

...

## System Environment

LocalStack version: 0.12.9.1
LocalStack Docker image id: e8899c217614
LocalStack build date: 2021-04-15
LocalStack build git hash: 4a0e3b3c
Python Version: Python 3.8.5

**Comment by mgagliardo** [comment]
Hello @clearmechris, would you please try with the docker image? We strongly advise to do so as the localstack binary (The one you install with `pip`) has some downsides like firewalls, issues with permissions/selinux. 

You can test that out by doing (for example):

```
$ docker run -d --name localstack -p 4566:4566 localstack/localstack:latest  
```

Or using the `docker-compose.yml` example on the repo. It would also help to see some debug logs if you won't use the docker runner.

**Comment by clearmechris** [comment]
It seems like neither work, here are the logs that are generated by the
container failing when starting up s3

**Comment by mgagliardo** [comment]
Hello @clearmechris, I can't see the logs, can you please paste them? Thanks.

**Comment by clearmechris** [comment]
Sure, I am away from my machine at the moment, let me shoot you them later
on when I get home.

If we could keep this open that would be great, from memory its a python
null object pointer

Chris

**Comment by mgagliardo** [comment]
Sure, thanks. I'll reopen it as soon as I reproduce it.
