### ISSUE TITLE
Cognito - trying to delete users empty user pool throws "user pool not found" instead of "user not found"

### ISSUE THREAD

**Issue by John-D8** [localstack/localstack#3883]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

When trying to delete a user as admin from an empty user pool, Cognito cannot find the user pool although the pool exists.

## Expected behavior

UserNotFoundException should be thrown

## Actual behavior

ResourceNotFoundException is thrown ("Cannot find resource: Unable to find user pool <user pool id>")

# Steps to reproduce

1) Create a user pool in Cognito
2) Try to delete user a user as admin

## Command used to start LocalStack

docker-compose

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

```
const username = 'nonexisting@user.com';
try {
    const res = await this.cognitoService.adminDeleteUser({
            UserPoolId: "<pool id>"
            Username: username,
          }).promise());
} catch {
    // ResourceNotFoundException  is thrown instead of UserNotFoundException 
}
```

**Comment by whummer** [comment]
Thanks for reporting @John-D8 . This should be fixed in the meantime - can you please give it another try with the `latest` Docker image? Please let us know if the problem persists. Thanks for your help!
