### ISSUE TITLE
Listing of objects at s3 is not working while using php sdk

### ISSUE THREAD

**Issue by demianchuk** [localstack/localstack#3891]
# Type of request: This is a bug report

# Detailed description
I creates s3 bucket using awslocal and added at that bucket images. As you see at screen 1 - I can list files inside a bucket using a prefix at url: http://localhost:4566/ct-dev-cms/?prefix=landing-page

![screen1](https://user-images.githubusercontent.com/19871155/115245869-a93ad880-a125-11eb-836d-d0c8faf821b7.png)

But while using php sdk library I have several problems
use Aws\S3\S3Client;

 $s3client = new S3Client([
      'region'  => 'eu-central-1',
      'version' => '2006-03-01',
      'credentials'   => false,
      'endpoint' => "http://localstack:4566",
      'use_path_style_endpoint' => true,
      'debug' => true,
  ]);

$list = $s3client->listObjects([
    'Bucket'    => "ct-dev-cms",
    'Prefix'    => "landing-page",
]);

var_dump($list);die;

In that case I am getting the error: 

Error executing "ListObjects" on "http://localstack:4566/ct-dev-cms?prefix=landing-page&encoding-type=url"; AWS HTTP error: Client error: `GET http://localstack:4566/ct-dev-cms?prefix=landing-page&encoding-type=url` resulted in a `404 Not Found` response:
{"status": "running"}
Unable to parse error information from response - Error parsing XML: String could not be parsed as XML

The main problem here is that php library is not adding slash after bucket name -> ...**ct-dev-cms?prefix** ... while in fact it works only with **ct-dev-cms/?prefix**

I tried to make work around on that case by using slash at the end of bucket name (though for sure it is bad solution)

$list = $this->s3client->listObjects([
    'Bucket'    => "ct-dev-cms/",
    'Prefix'    => "landing-page",
]);

but  in that case I get empty list - and seems it is similar to that issue: https://github.com/localstack/localstack/issues/2535, which is was closed (so I assume that the same problem appeared again)
 
...

## Expected behavior
I have to get the list of objects from bucket using prefix
...

## Actual behavior
either bug with slash causes xml parse error or I get empty list 
...

# Steps to reproduce
as above

## Command used to start LocalStack
docker-compose

localstack:
      container_name: localstack_service
      image: localstack/localstack
      ports:
        - "4566:4566"
        - "4571:4571"
      environment:
        - SERVICES=s3,sqs
        - DEBUG=1
        - DATA_DIR=/tmp/localstack/data
      volumes:
        - ./ci/.data/localstack:/tmp/localstack
        - /var/run/docker.sock:/var/run/docker.sock
        - ./bin:/docker-entrypoint-initaws.d
        - 
...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
awslocal s3api create-bucket --bucket ct-dev-cms
awslocal s3api put-bucket-acl --bucket ct-dev-cms --acl public-read

put any image to ct-dev-cms/landing-page

run php code:

use Aws\S3\S3Client;

 $s3client = new S3Client([
      'region'  => 'eu-central-1',
      'version' => '2006-03-01',
      'credentials'   => false,
      'endpoint' => "http://localstack:4566",
      'use_path_style_endpoint' => true,
      'debug' => true,
  ]);

$list = $s3client->listObjects([
    'Bucket'    => "ct-dev-cms",
    'Prefix'    => "landing-page",
]);

var_dump($list);die;
...

**Comment by macnev2013** [comment]
Thanks for reporting the issue @demianchuk .

Looks like this issue is similar to #3613. Lets us know if this does not help. Thanks

**Comment by demianchuk** [comment]
Yes, you are right. That is the same problem as to #3613. Thank you for your help
I am closing the case

**Comment by demianchuk** [comment]
Thank you
