### ISSUE TITLE
dynamoDB stream event passing "Keys":null

### ISSUE THREAD

**Issue by maturiaditya** [localstack/localstack#3899]
# Type of request: This is a ...

[X] bug report
[ ] feature request

# Detailed description

Hi, I am connecting stream from dynamo DB to lambda. Currently, I am seeing the event data is passing "Keys":null. I am not sure if this is expected behavior or there is a bug there. 
...

## Expected behavior
Keys should have values
...

## Actual behavior
Keys: null
...

# Steps to reproduce

## Command used to start LocalStack

...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

...

**Comment by KrishnanRanjithkumar** [comment]
Thanks for reporting @maturiaditya . Could you please share same code samples to reproduce the issue?

**Comment by maturiaditya** [comment]
Thanks for the response @KrishnanRanjithkumar. 
I am trying with some sample code and it looks like it's working. Something wrong with my project config I suppose, false alarm here. Thanks.
