### ISSUE TITLE
S3 Website configuration not supported

### ISSUE THREAD

**Issue by vangorra** [localstack/localstack#390]
It doesn't appear S3 website configurations are supported at the moment.

```
$ aws --endpoint-url=http://localstack:4574 --region=us-east-1 s3api get-bucket-website --bucket myBucket
An error occurred (404) when calling the GetBucketWebsite operation: Not Found
```

Workaround:
For the time being, I'll add an nginx container to my docker compose setup to proxy the buckets.
myBucket.localstack will proxy to http://localstack:4574/myBucket.

**Comment by puppeteer701vungle** [comment]
Can you please share the config?

**Comment by whummer** [comment]
This feature has been added in the meantime - closing.
