### ISSUE TITLE
EventBridge putEvents giving 500 InvokeError

### ISSUE THREAD

**Issue by rnjailamba** [localstack/localstack#3902]
# Type of request: This is a ...

[x ] bug report
[ ] feature request

# Detailed description
We are putting an event in EventBridge by 
  `const result = await eventbridge.putEvents(params).promise()`
for eventbridge initialised by
```
const eventbridge = new AWS.EventBridge({
    endpoint: 'http://localhost:4566'
  }
)
```
but getting
`
2021-04-20T20:28:30.381Z	ace0652e-56fa-12fa-7286-fb01f0d092a1	ERROR	Invoke Error 	{"errorType":"UnknownError","errorMessage":"","code":"UnknownError","message":"","statusCode":500,"time":"2021-04-20T20:28:30.379Z","retryable":true,"stack":["UnknownError","    at Request.extractError (/var/task/node_modules/aws-sdk/lib/protocol/json.js:52:27)","    at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:106:20)","    at Request.emit (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:78:10)","    at Request.emit (/var/task/node_modules/aws-sdk/lib/request.js:688:14)","    at Request.transition (/var/task/node_modules/aws-sdk/lib/request.js:22:10)","    at AcceptorStateMachine.runTo (/var/task/node_modules/aws-sdk/lib/state_machine.js:14:12)","    at /var/task/node_modules/aws-sdk/lib/state_machine.js:26:10","    at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:38:9)","    at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:690:12)","    at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:116:18)"]}
`
## Expected behavior
putEvents by AWS SDK should work.

## Actual behavior
We get an InvokeError

# Steps to reproduce
At the top level we are using AWS CLI V1 and localstack is also ver1 installed with python3
1. `docker-compose --env-file .env up -d` with the .env file only consisting of the API Key
2. Run `sh ./1-cloudformation-deploy.sh` to create cloudformation stack and deploy locally
3. Copy the name of the function 'XYZ' (find name of function by `awslocal lambda list-functions --region us-east-1 --query 'Functions[].FunctionName'`
) and invoke the created function by
```
awslocal lambda invoke \
--function-name 'XYZ' \
--region us-east-1 \
--invocation-type Event \
--payload '{ "key": "value" }' \
response.json; 
```
4. Check localstack logs to see an `Invoke Error, "statusCode":500`
5. This happened on line 35 of `atmProducer/handler.js` which puts an event
  `const result = await eventbridge.putEvents(params).promise()`
for eventbridge initialised as
```
const eventbridge = new AWS.EventBridge({
    endpoint: 'http://localhost:4566'
  }
)
```

## Command used to start LocalStack
docker-compose.yml
```
version: "3.7"
services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack}"
    image: localstack/localstack:latest
    networks:
      - mynet
    ports:
      - "4566-4599:4566-4599"
      - 443:443
    environment:
      - SERVICES=lambda,cognito,apigateway,cloudformation,sqs,sns,events,stepfunctions,s3,serverless,firehose,es
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY}
      - DEBUG=1
      - LOCALSTACK_HOSTNAME=localhost
      - DATA_DIR=/tmp/localstack/data
      - LAMBDA_EXECUTOR=docker-reuse
      - LAMBDA_REMOTE_DOCKER=false
      - LAMBDA_DOCKER_NETWORK=host
      - LAMBDA_REMOVE_CONTAINERS=true
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=/tmp/localstack
    volumes:
      - "/tmp/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./bin:/docker-entrypoint-initaws.d
networks:
  mynet:
    name: mynet
```
and below command
`docker-compose --env-file .env up -d` with the .env file only consisting of the API Key

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
All required code and readme is here https://github.com/rnjailamba/localstack-cloudformation-lambda-eventbridge

**Comment by whummer** [comment]
Thanks for reporting @rnjailamba . Looks like the Lambda CLI expects base64 encoded inputs under certain circumstances. I think you may want to add something like this to your invocation:

```
awslocal lambda invoke --function-name test10-lambda-263092bf --region us-east-1 --invocation-type Event --payload '{"test":"123"}' --cli-binary-format raw-in-base64-out response.json
```
(We'll improve the error logging on LocalStack side for this case..)
Please keep us posted how it goes, thanks!

**Comment by rnjailamba** [comment]
@waltercool i moved to AWS CLI V2 to run this but still see the same issue. Putting all the details below
`awslocal lambda invoke --function-name test10-lambda-766bad5e --region us-east-1 --invocation-type Event --payload '{"test":"123"}' --cli-binary-format raw-in-base64-out response.json
`
```
{
    "StatusCode": 202,
    "LogResult": "",
    "ExecutedVersion": "$LATEST"
}
```
`aws --version`
`aws-cli/2.1.38 Python/3.8.8 Darwin/19.4.0 exe/x86_64 prompt/off`
Adding relevant logs -

`2021-04-20T23:01:58.218Z	206bc7b1-f59d-1fe6-8d4b-5d6fbaf19df1	ERROR	Invoke Error 	{"errorType":"UnknownError","errorMessage":"","code":"UnknownError","message":"","statusCode":500,"time":"2021-04-20T23:01:58.216Z","retryable":true,"stack":["UnknownError","    at Request.extractError (/var/task/node_modules/aws-sdk/lib/protocol/json.js:52:27)","    at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:106:20)","    at Request.emit (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:78:10)","    at Request.emit (/var/task/node_modules/aws-sdk/lib/request.js:688:14)","    at Request.transition (/var/task/node_modules/aws-sdk/lib/request.js:22:10)","    at AcceptorStateMachine.runTo (/var/task/node_modules/aws-sdk/lib/state_machine.js:14:12)","    at /var/task/node_modules/aws-sdk/lib/state_machine.js:26:10","    at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:38:9)","    at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:690:12)","    at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:116:18)"]}
`

**Comment by waltercool** [comment]
@rnjailamba While I do use localstack for my architecture, I don't cover lambda functions with localstack, so can't help from my side  :-(

Or you wanted to tag whummer and picked me by mistake? :-)

**Comment by rnjailamba** [comment]
Thanks for the help, yes i made a mistake there but thanks for the reply :)

**Comment by diegosasw** [comment]
I don't use lambda myself, but does the same happen if you pass a `--payload file://test_payload.json` instead of the inline json?

**Comment by rnjailamba** [comment]
@whummer  is on this version aws-cli/1.19.53 Python/3.8.2 Darwin/19.6.0 botocore/1.20.53 so we moved to exactly aws-cli/1.19.53 Python/3.9.4 Darwin/19.4.0 botocore/1.20.53 and the problem is fixed without any other change.

Adding some commands used to go to the exact version of python and aws cli and awslocal cli below - 
```
brew install python3
pyenv install 3.8.2
pyenv global 3.8.2
eval "$(pyenv init -)"
```
add above to ~/.bash_profile

```
pip3 install awscli-local[ver1]
pip3 install awscli==1.19.53 
```
