### ISSUE TITLE
Protecting API Gateway with COGNITO_USER_POOLS returns error: "Unable to get Cognito identity (404)"

### ISSUE THREAD

**Issue by seibelj** [localstack/localstack#3911]
# Type of request: This is a ...

[ X ] bug report
[ ] feature request

# Detailed description
I am trying to protect an API Gateway resource using:

```
resource "aws_api_gateway_authorizer" "address_authorizer" {
  name                   = "address-authorizer"
  rest_api_id            = aws_api_gateway_rest_api.address_api_gw_rest_api.id
  type = "COGNITO_USER_POOLS"
  identity_source = "method.request.header.Authorization"
  provider_arns = ["arn:aws:cognito-idp:us-east-1:123456789012:userpool/${aws_cognito_user_pool.internal.id}"]
}
```

Everything appears to be setup properly. I can get the JWT from Cognito in localstack. When I pass it with `Authorization` head (`Bearer ...`) to the API, I get the error:

```
{
  "error": "Unable to get Cognito identity (404): b'{\"status\": \"running\"}'"
}
```
The docker container has logs:
```
localstack_1 | 2021-04-21T03:59:31:INFO:localstack.services.edge: Unable to find forwarding rule for host "localhost:4566", path "POST /", target header "_get_identity_for_credentials_", auth header "Bearer eyJ0eX...", data "b''"
```

When I don't pass the JWT at all, I get:
```
{
  "error": "Unable to get Cognito identity (404): b'{\"error\": \"Unable to verify access ID __internal_call__\"}'"
}
```
Nothing in docker logs.

## Expected behavior
JWT is validated against the user pool.

## Actual behavior
Error I can't find a reason for.
...

# Steps to reproduce
Create a new API Gateway resource and lambda, and protect it using resource `aws_api_gateway_authorizer` with `type = "COGNITO_USER_POOLS"`, and have a `aws_cognito_user_pool` you can reference

**Comment by whummer** [comment]
Thanks for reporting @seibelj . Can you please share the API Gateway endpoint URL you are invoking? Please note that there are generally 2 formats for API GW endpoints supported (assuming `api123` is your API ID):
* `http://localhost:4566/restapis/api123/stage/_user_request_`, or
* `https://api123.execute-api.localhost.localstack.cloud/stage`

Which of the two are you using? We'll be happy to reproduce and look into this issue right away.. Thanks

**Comment by seibelj** [comment]
This is the URL type `http://localhost:4566/restapis/api123/stage/_user_request_`. Thank you

**Comment by whummer** [comment]
Thanks for the update @seibelj. This should be (hopefully) fixed in the meantime - can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists. Thanks for your help!
