### ISSUE TITLE
AWS .NET SDK: Presigned Urls with ResponseHeaderOverrides are not working properly

### ISSUE THREAD

**Issue by pweissenbacher** [localstack/localstack#3912]
# Type of request: This is a ...

[x ] bug report
[ ] feature request

# Detailed description
The issue was already being observed during #3522. The behavior of LocalStack using v4 signatures has indeed improved, but when using `ResponseHeaderOverrides` the signature still fails.

```
...
ResponseHeaderOverrides = new ResponseHeaderOverrides
{
    ContentType = "text/plain",
    ContentDisposition = "attachment;filename=test.txt",  // does work
    ContentDisposition = "attachment; filename=test.txt" // does NOT work
                                     ^ space char breaks signature
}
...
```

This problem also persists when creating the `ContentDisposition` string with standard .NET methods:
```
var filename = "test.txt";
var contentDisposition = new ContentDispositionHeaderValue("attachment");
contentDisposition.SetHttpFileName(filename);
```

As mentioned by @KarlKl:
"The space char "breaks" the signature, the signature created isn't valid and I'm getting a 403 like before. I think the original AWS implementation does somehow parse the Content-Disposition and trims spaces before signature creation."

Are there any updates on this?

**Comment by whummer** [comment]
Thanks for reporting @pweissenbacher . This should be fixed in #3947 - can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists. Thanks!
