### ISSUE TITLE
Expired Let's Encrypt certificate on localstack.cloud

### ISSUE THREAD

**Issue by anderius** [localstack/localstack#3919]
# Type of request: This is a ...

[X ] bug report
[ ] feature request

# Detailed description

The Let's Encrypt certificate on https://localstack.cloud/ expired today. Just a heads up! I could find no repository for the web site, so I am telling you this way. :-)

**Comment by whummer** [comment]
Many thanks for the pointer @anderius ! 👍 (this is now fixed..) Thanks
