### ISSUE TITLE
Different behaviour on 2 different computers for the same compose file - lambda container not created in one instance

### ISSUE THREAD

**Issue by luminescent** [localstack/localstack#3920]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

I am using the same docker-compose file on my personal laptop and on the work virtual machine. I have pinned the localstack version to be sure. 

On the home machine, a lambda is executed in a new container that is launched specifically for the execution. I get a log output that shows the command used such that the container is launched, I can see the new container with `docker stats` etc. 

On my work VM (with the same OS), the lambda seems to be executed on the localstack container itself. I cannot see a different container when I am monitoring with `docker stats`, and I get a different output coming out of the localstack container. Eg there is no log for the command used to launch the container. Additionally, if I set environment variables in the compose file for the localstack container, I can access them in the lambda when running on the work machine but not on the other. More so, print messages from the lambda are visible in the localstack output in the terminal where I run compose up, etc. So clearly my work Docker executes the lambda inside the localstack container and the other does not. 

## Expected behavior

I expect localstack to behave the same for the same compose file. 

## Actual behavior

It doesn't execute a lambda in a different container on one of the machines, but does in the other. I don't know why!

# Steps to reproduce

## Command used to start LocalStack

(some services excluded)

```
version: "2.1"

services:
  localstack_main:
    container_name: localstack_main
    hostname: localstack_main
    image: localstack/localstack:0.12.9.1
    ports:
      - "4566:4566"
      - "4571:4571"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=${SERVICES- }
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
      - LAMBDA_DOCKER_NETWORK=myfolder_lntk
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - lntk

networks:
  lntk:
    driver: bridge
```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

```
awslocal lambda create-function \
    --region us-east-1 \
    --function-name "$1" \
    --runtime python3.6 \
    --handler lambda.exec \
    --zip-file "fileb://${1}.zip" \
    --role arn:aws:iam::123456:role/irrelevant 
```

```
awslocal lambda invoke \
    --function-name "$1" \
    --payload "file://${1}.json" out.txt
```

**Comment by luminescent** [comment]
I have pinned the `LAMBDA_EXECUTOR` to `docker` and localstack does indeed try to create the container even on the work machine, but it fails: 
```
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.29/containers//json: dial unix /var/run/docker.sock: connect: permission denied
```
I suspect it silently errors and then falls back to the other mode. Perhaps it should be made obvious to the user which mode it is using or if it switches due to errors.

**Comment by mgagliardo** [comment]
Hello @luminescent, would you please make sure the following are pinned on the `docker-compose` as expected?

`LAMBDA_EXECUTOR=docker`
`LAMBDA_REMOTE_DOCKER=false`
`HOST_TMP_FOLDER=/tmp/example-folder`

I am also leaving an example docker-compose.yml I have just tested both on 2 vagrant machines, 1 mac and 1 ubuntu notebook as well, all working as expected.

docker-compose.yml:
```
version: '3.9'

services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LAMBDA_EXECUTOR=docker
      - LAMBDA_REMOTE_DOCKER=false
      - HOST_TMP_FOLDER=/tmp/example-folder
    volumes:
      - /tmp/example-folder:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock
```

On the other hand for your comment, the following line: `dial unix /var/run/docker.sock: connect: permission denied` explicitly says that you have no permissions to connect to the unix socket. So either your user has little permissions (check with `id $user` it is included in the `docker` group) or you can even run docker-compose as root, also check that the docker service is up and running. 

Let me know in any case.

Cheers!

**Comment by luminescent** [comment]
Thank you for looking into this.

Once I pin the executor, they both work the same way for me as well, trying
to launch a container for the lambda, but I didn't figure I would have to
pin it until it switched to the other behaviour on the work machine. It
looks like either the defaults are different or it figures it cannot run
the docker executer and falls back on embedded maybe?

On the error itself, on my work machine Docker runs rootless (company
policy), and I am finding out that the permissions on the Docker socket are
rwxrw____ which might explain why it cannot work. I don't know if my user
has been added to the docker group. I don't know enough about Docker to
find my way around this, using a tcp socket was mentioned but yet to
understand how that works.

I think it's clear by now that this isn't a localstack problem 🙂 Maybe
apart from the fact that not specifying an executor defaults to different
things on different systems.
