### ISSUE TITLE
Stuck on modifying aws_api_gateway_resource with Terraform

### ISSUE THREAD

**Issue by kigawas** [localstack/localstack#3938]
## Terraform configs
- Resource
https://gist.github.com/mendhak/8303d60cbfe8c9bf1905def3ccdb2176

- Provider
```tf
provider "aws" {
  region = "ap-northeast-1"

  access_key = "mock_access_key"
  secret_key = "mock_secret_key"

  s3_force_path_style         = true
  skip_credentials_validation = true
  skip_metadata_api_check     = true
  skip_requesting_account_id  = true

  endpoints {
    apigateway = "http://localhost:4566"
    kinesis    = "http://localhost:4566"
    lambda     = "http://localhost:4566"
    s3         = "http://localhost:4566"
  }
}

```

## Steps to reproduce

Just modify `path_part   = "{proxy+}"` to any string
```bash
$ terraform apply -auto-approve
aws_api_gateway_rest_api.MyDemoAPI: Refreshing state... [id=33q0k8ypm9]
aws_api_gateway_resource.MyDemoResource: Refreshing state... [id=zjbdca5xem]
aws_api_gateway_method.MyDemoMethod: Refreshing state... [id=agm-33q0k8ypm9-zjbdca5xem-GET]
aws_api_gateway_integration.MyDemoIntegration: Refreshing state... [id=agi-33q0k8ypm9-zjbdca5xem-GET]
aws_api_gateway_deployment.teststage: Refreshing state... [id=mmu756oq89]
aws_api_gateway_resource.MyDemoResource: Modifying... [id=zjbdca5xem]
```

**Comment by CodePint** [comment]
We also experienced errors with terraform apply hanging with localstack on api-gateway/lambda/dynamodb. We found this was resolving to pinning the version in our docker-compose to: `localstack/localstack:0.12.12`

**Comment by whummer** [comment]
Thanks for reporting @kigawas @CodePint , and apologies for the long delay on this one. This should be (hopefully) fixed in the meantime - can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists.. Thanks for your help!
