### ISSUE TITLE
SQS GetQueueUrl in docker statically assigns port 4576.

### ISSUE THREAD

**Issue by typingduck** [localstack/localstack#394]
Previously (localstack docker version 0.7.0) the SQS requests respected randomly assigned docker ports. 
So SQS request GetQueueUrl on a host port 10000 mapped to container port 4576 then the response would be localhost:10000.

On the latest localstack docker version (142df3656c04) GetQueueUrl instead returns localhost:4576.

Why this matters: Some SQS client libraries use the SQS GetQueueUrl extensively as a quick way to resolve queue names. And for testing it is normal not to have static port numbers.

**Comment by whummer** [comment]
Thanks for reporting @typingduck , this should be fixed in #440. As long as the client requests contains a `Host` header (which should be the case for most clients), the correct port should now be returned for the queue URL. Can you please give it a try with the latest version. Thanks

**Comment by whummer** [comment]
Closing this issue, please re-open if the problem persists. Thanks
