### ISSUE TITLE
Cognito - user attributes not passed to Pre-Authentication lambda

### ISSUE THREAD

**Issue by John-D8** [localstack/localstack#3940]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

When authentication with an existing user to a user pool with a defined pre-authentication lambda, the user's attributes are not passed in the request to the lambda.

## Expected behavior

User attributes should be passed in the request object to the lambda function

## Actual behavior

User attributes are not passed in the request object to the lambda function

# Steps to reproduce

1) Define a user pool with a pre-authentication lambda trigger.
2) Add a user to the user pool with at least one user attribute.
3) Try to authenticate to the user pool with the user

## Command used to start LocalStack

docker compose

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

```
      res = await cognito.initiateAuth({
        ClientId: clientId,
        AuthFlow: 'USER_PASSWORD_AUTH',
        AuthParameters: {
          USERNAME: 'user@example.com',
          PASSWORD: 'pass',
        }
      }).promise();
```

Received data (userAttributes is empty):
```
{
	"version": "$LATEST",
	"triggerSource": "PreAuthentication_Authentication",
	"region": "eu-west-1",
	"userPoolId": "<user_pool_id>",
	"callerContext": {
		"awsSdkVersion": "TODO",
		"clientId": "<client_id>"
	},
	"request": {
		"userAttributes": {},
		"validationData": {},
		"clientMetadata": {}
	},
	"response": {}
}
```

**Comment by whummer** [comment]
Thanks for reporting @John-D8 . This should be fixed in the meantime - can you please pull the `latest` Docker image and give it another try? Please keep us posted if the problem persists. Thanks for your help!
