### ISSUE TITLE
Not possible to fetch lambda using ARN as function name

### ISSUE THREAD

**Issue by j-sv** [localstack/localstack#3954]
# Type of request: This is a ...

[*] bug report
[ ] feature request

# Detailed description

From: https://docs.aws.amazon.com/cli/latest/reference/lambda/get-function.html

> --function-name (string)
> 
>     The name of the Lambda function, version, or alias.
> 
>         Name formats
> 
>         Function name - my-function (name-only), my-function:v1 (with alias).
>         Function ARN - arn:aws:lambda:us-west-2:123456789012:function:my-function .
>         Partial ARN - 123456789012:function:my-function .
> 
>     You can append a version number or alias to any of the formats. The length constraint applies only to the full ARN. If you specify only the function name, it is limited to 64 characters in length.

The AWS SDK allows fetching a lambda function using the ARN as function name. Using `awslocal`, getting a function using the function name works, but using the full ARN fails saying the resources does not exist.

This also fails when using e.g. a `data` attribute to fetch information about a lambda function.

## Expected behavior

Fetching a function using its ARN should work

## Actual behavior

An error is returned.

# Steps to reproduce

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

```bash
$ cat handler.py
def handler():
    pass

$ zip -q handler.zip handler.py

$ awslocal lambda get-function --function-name example
{
    "Configuration": {
        "FunctionName": "example",
        "FunctionArn": "arn:aws:lambda:us-east-1:000000000000:function:example",
        "Runtime": "python3.6",
        "Role": "arn:aws:iam::123456790:role/ignore",
        "Handler": "handler.handler",
        "CodeSize": 194,
        "Description": "",
        "Timeout": 3,
        "LastModified": "2021-05-03T10:25:47.526+0000",
        "CodeSha256": "iXRiTrH41JzAaBMUO5tBj/XZ//4nOACx5sjaO2QXOgQ=",
        "Version": "$LATEST",
        "VpcConfig": {},
        "TracingConfig": {
            "Mode": "PassThrough"
        },
        "RevisionId": "838d6ad4-0a90-4eab-b5ef-92c37a765aa4",
        "Layers": [],
        "State": "Active",
        "LastUpdateStatus": "Successful",
        "PackageType": "Zip"
    },
    "Code": {
        "Location": "http://localhost:4566/2015-03-31/functions/example/code"
    },
    "Tags": {}
}

$ awslocal lambda get-function --function-name arn:aws:lambda:us-east-1:000000000000:function:example

An error occurred (ResourceNotFoundException) when calling the GetFunction operation: Function not found: arn:aws:lambda:us-east-1:000000000000:function:example
```

This would also fail.
```terraform
data "aws_lambda_function" "function" {
    function_name = "arn:aws:lambda:us-east-1:000000000000:function:example"
}
```

**Comment by mgagliardo** [comment]
Thanks for reporting this @j-sv, please fetch the `latest` docker image and give it a try again. Thanks!
