### ISSUE TITLE
SQS Localstack - ChangeMessageVisibility to greater than 12 hours doesn't raise exception

### ISSUE THREAD

**Issue by yadwinder11** [localstack/localstack#3956]
# Type of request: This is a ...
- [x] bug report
- [ ] feature request

# Detailed description
SQS Localstack does not raise an exception when the subsequent message `Visibility Timeout` period  (set by ChangeMessageVisibility on retry) exceeds the maximum 12 hour period. However, a similar operation in SQS generates the exception.

## Expected behavior
The following exception should be raised:
 
```
Aws::SQS::Errors::InvalidParameterValue: Value 43200 for parameter VisibilityTimeout is invalid. Reason: Total VisibilityTimeout for the message is beyond the limit [43200 seconds]
```

## Actual behavior
No exception raised.

# Steps to reproduce
1. Send a message to the SQS queue
2. Don't delete the messages and in order to reprocess it, set the Visibility Timeout to 1 minute
3. On retry don't delete the messages and in order to reprocess it again, set the Visibility Timeout to 12 hours.
As the maximum Visibility Timeout period exceed the 12 hours period, Localstack SQS should raise the exception similar to AWS SQS Queues.

**Comment by whummer** [comment]
Thanks @yadwinder11  @usmangani1 . This should be fixed in the meantime - can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists. Thanks!
