### ISSUE TITLE
support route53 "create-reusable-delegation-set" API

### ISSUE THREAD

**Issue by pll** [localstack/localstack#3961]
This API call does not seem to be supported yet. Currently I'm attempting to evaluate localstack as a means of testing our terraform code, and currently use delegations sets in our code to create subdomains and automatically enter the NS records for that subdomain into the parent domain zone file.

**Comment by whummer** [comment]
Thanks for reporting @pll . This should be fixed in 7029bd25e19e787e336d830548d29957536b71ab - can you please pull the `latest` Docker image and give it another try? Please keep us posted how it goes.. Thanks!
