### ISSUE TITLE
Support for the resourcegroupstaggingapi() API

### ISSUE THREAD

**Issue by pll** [localstack/localstack#3962]
moto supports a mock for the resourcegroupstaggingapi() API, it would awesome if localstack also had this support.

Thanks!

**Comment by synfinatic** [comment]
Funny that this ticket was opened just a few hours ago... I too need support for resource groups for terraform testing since we use resource groups extensively to manage AWS resources in our multi-tenant accounts.

**Comment by pll** [comment]
> I too need support for resource groups for terraform testing since we use resource groups extensively to manage AWS resources in our multi-tenant accounts.

LOL. Glad I can be of help!  I got the moto team to support the resourcegroupstaggingapi() call for pyton a couple years ago, and it looks like they've really expanded the support for it. Hopefully that makes it easier for the localstack team.

I'd love to hear how your using resource groups with terraform, when I deal with AWS support, I get the feeling no one is using it but me!

**Comment by whummer** [comment]
Thanks for reporting @pll @synfinatic . This has been added in #3975 - can you please pull the `latest` Docker image and try again? Thanks!
