### ISSUE TITLE
Support PATCH requests in CORS configuration

### ISSUE THREAD

**Issue by wmaciejak** [localstack/localstack#3964]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

The source of the issue is fact that Localstack has preconfigured mocked OPTIONS endpoint for API Gateway where the `Access-Control-Allow-Methods` header has only `GET, POST, PUT, DELETE` values. It means that we cannot make a PATCH request cause will be rejected.

## Expected behavior

The best idea is to have the ability to define the behavior of OPTIONS action for each one resource, but since it's not possible it would be super helpful to have just an additional PATCH method in the above-mentioned header.

Header `Access-Control-Allow-Methods` should have the values `GET, POST, PUT, DELETE, PATCH`

## Actual behavior

Currently, header `Access-Control-Allow-Methods` have this values `GET, POST, PUT, DELETE`

**Comment by whummer** [comment]
Thanks for reporting and fixing this @wmaciejak  - the `latest` Docker image is currently being built in our CI system and will become available in ~30 mins. Thanks!
