### ISSUE TITLE
ECS list-task-definitions sort parameters not working

### ISSUE THREAD

**Issue by dirathea** [localstack/localstack#3970]
# Type of request: This is a Bug

[x] bug report
[ ] feature request

# Detailed description

Register some ecs task definitions, then list using `awslocal ecs list-task-definitions --sort DESC`. It will return in ascending order.

## Expected behavior

The task-definitions ARN should be sorted based on the parameters.

## Actual behavior

The task-definitions ARN returned in ascending order. Seems like ignoring the `--sort` options.

# Steps to reproduce

1. Register several ECS Task Definitions under the same family
2. Do `awslocal ecs list-task-definitions --sort DESC`.

## Command used to start LocalStack

SERVICES=ecs localstack start

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

`awslocal ecs list-task-definitions --sort DESC --family my-task-family`

**Comment by whummer** [comment]
Thanks for reporting @dirathea - this should be fixed in the meantime. Can you please pull the `latest` Docker image and give it another try? Thanks for your help!
