### ISSUE TITLE
Can't sign S3 urls assuming IAM role via aws-cli

### ISSUE THREAD

**Issue by ganeko** [localstack/localstack#3971]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

When we try to sign S3 urls via aws-cli (`aws-cli/2.0.46 Python/3.8.5 Darwin/19.6.0 source/x86_64`) with IAM role credentials we always get signing error. Following the README, it is possible to sign URLs based on basic credentials (access key + secret) using `test` value but it is impossible for us to get correctly signed urls based on access key, secret and token.

## Expected behavior

The signed url should be accessible from the browser once signed.

## Actual behavior

The signed url is not accessible, we receive the following error,

```
<Error>
<Code>SignatureDoesNotMatch</Code>
<Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message>
<RequestId>b72b7386</RequestId>
<HostId>ebb8c48f</HostId>
<AWSAccessKeyId>test</AWSAccessKeyId>
<StringToSign></StringToSign>
<SignatureProvided>e806312c7556d41dd6565dfae080f6d1b507893dc0f68099a2a8f160481b1deb</SignatureProvided>
<StringToSignBytes>65383036333132633735353664343164643635363564666165303830663664316235303738393364633066363830393961326138663136303438316231646562</StringToSignBytes>
</Error>
```

# Steps to reproduce

## Command used to start LocalStack

We are using LocalStack 0.12.9 in a docker container using the standard script.

### Working signed urls

```
export AWS_ACCESS_KEY_ID=test
export AWS_SECRET_ACCESS_KEY=test
aws s3 presign dev-audios/5a/04/5a04fbb6-5b9c-4fef-a782-6447d705fadc.mp3 --endpoint-url=http://localstack:4566
```

Result,

```
http://localstack:4566/dev-audios/5a/04/5a04fbb6-5b9c-4fef-a782-6447d705fadc.mp3?
X-Amz-Algorithm=AWS4-HMAC-SHA256&
X-Amz-Credential=test%2F20210505%2Fus-east-1%2Fs3%2Faws4_request&
X-Amz-Date=20210505T171625Z&+
X-Amz-Expires=3600&
X-Amz-SignedHeaders=host&
X-Amz-Signature=ac45d04a91c1cf57c9fb2da976a58d79147f512c322e2670348971e256e9ad68
```

### Non-working signed urls

Following https://aws.amazon.com/es/premiumsupport/knowledge-center/iam-assume-role-cli/ of how to assume a role via aws-cli (`Create environment variables to assume the IAM role and verify access` section).

```
export AWS_ACCESS_KEY_ID=test
export AWS_SECRET_ACCESS_KEY=test
export AWS_SESSION_TOKEN=test            ==> `test` or what?
aws s3 presign dev-audios/5a/04/5a04fbb6-5b9c-4fef-a782-6447d705fadc.mp3 --endpoint-url=http://localstack:4566
```

Result,

```
http://localstack:4566/dev-audios/5a/04/5a04fbb6-5b9c-4fef-a782-6447d705fadc.mp3?
X-Amz-Algorithm=AWS4-HMAC-SHA256&
X-Amz-Credential=test%2F20210505%2Fus-east-1%2Fs3%2Faws4_request&
X-Amz-Date=20210505T171840Z&
X-Amz-Expires=3600&
X-Amz-SignedHeaders=host&
X-Amz-Security-Token=test&
X-Amz-Signature=ed38b4ea460ca6fa3e16bb00e525ce3e4bb0e43e71b0c81fd37f71527f477c90
```

**Comment by whummer** [comment]
Thanks for reporting @ganeko . We're currently looking into this issue in more detail.

Meanwhile, as a workaround we have introduced a new configuration value `S3_SKIP_SIGNATURE_VALIDATION=1` which you can enable in your LocalStack container environment, to temporarily skip the signature validation.

Hope that helps - please keep us posted how it goes. Thanks!

**Comment by ganeko** [comment]
> Thanks for reporting @ganeko . We're currently looking into this issue in more detail.
> 
> Meanwhile, as a workaround we have introduced a new configuration value `S3_SKIP_SIGNATURE_VALIDATION=1` which you can enable in your LocalStack container environment, to temporarily skip the signature validation.
> 
> Hope that helps - please keep us posted how it goes. Thanks!

Thank you very much @whummer and @macnev2013 for the incredible speed with the workaround!. We are waiting for the next release to be able to do tests since we use fixed versions in our environment for localstack. If you need any help or testing, please let me know. Thanks mates!

**Comment by ganeko** [comment]
> Thanks for reporting @ganeko . We're currently looking into this issue in more detail.
> 
> Meanwhile, as a workaround we have introduced a new configuration value `S3_SKIP_SIGNATURE_VALIDATION=1` which you can enable in your LocalStack container environment, to temporarily skip the signature validation.
> 
> Hope that helps - please keep us posted how it goes. Thanks!

Hi @whummer ,

I've been testing the new tag `S3_SKIP_SIGNATURE_VALIDATION` and it doesn't seem to work.

I'm creating a docker container with the `0.12.11` image from docker hub (https://hub.docker.com/r/localstack/localstack/tags?page=1&ordering=last_updated) using vagrant as follows:

```
  config.vm.define :localstack do |localstack|
    localstack.vm.provider :docker do |p|
      p.name = "#{vagrant_env_id}_localstack"
      p.image = 'localstack/localstack:0.12.11'
      p.ports = ["4566:4566"]
      p.env = {SERVICES: 's3,sns,sqs', DATA_DIR: '/tmp/localstack/data', S3_SKIP_SIGNATURE_VALIDATION: '1'}
      p.volumes = ["#{File.expand_path('../localstack/data')}:/tmp/localstack/data"]
    end
  end
```

The behavior remains the same as I have described above, the second signed url does not work and returns the error `The request signature we calculated does not match the signature you provided`.

Any suggestions how I can test this?

Thanks in advance.

**Comment by whummer** [comment]
Thanks for the update @ganeko . We've pushed a couple more enhancements in S3 presign URL calculation (including #4081) - can you please pull the `latest` image and give it one more try? It should now also support presign URLs with session IDs in the credentials. Please let us know if the problem persists.. Thanks for your help!
