### ISSUE TITLE
Can't sign S3 urls via PHP SDK

### ISSUE THREAD

**Issue by ganeko** [localstack/localstack#3972]
# Type of request: This is a ...

[X] bug report
[ ] feature request

# Detailed description

When we try to use the PHP SDK (`aws/aws-sdk-php v3.180.2`) for S3 using basic credentials (access key + secret) or assuming an IAM role, all the URLs signed for S3 return an error.

Basic credentials:
```
'key' => 'test',
'secret' => 'test'
```

IAM role (instance role):
```
{
  "Code" : "Success",
  "LastUpdated" : "2019-03-13T17:21:26Z",
  "Type" : "AWS-HMAC",
  "AccessKeyId" : "test",
  "SecretAccessKey" : "test",
  "Token" : "test",                      ==> `test` or what?
  "Expiration" : "2045-03-13T23:56:04Z"
}
```

## Expected behavior

The signed url should be accessible from the browser once signed.

## Actual behavior

The signed url is not accessible, we receive the following error,

```
<Error>
<Code>SignatureDoesNotMatch</Code>
<Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message>
<RequestId>d7091ccf</RequestId>
<HostId>ee4921f5</HostId>
<AWSAccessKeyId>test</AWSAccessKeyId>
<StringToSign></StringToSign><SignatureProvided>829c4eb3924f2549d1fd24d3807fa41f0c27b5cb175176c4133d8c654755d4ee</SignatureProvided>
<StringToSignBytes>38323963346562333932346632353439643166643234643338303766613431663063323762356362313735313736633431333364386336353437353564346565</StringToSignBytes>
</Error>
```

# Steps to reproduce

## Command used to start LocalStack

We are using LocalStack 0.12.9 in a docker container using the standard script.

### Using basic credentials

```
use Aws\S3\S3Client;

$client = new S3Client([
    'endpoint' => 'http://localstack:4566',
    'credentials' => [
        'key' => 'test',
        'secret' => 'test'
    ],
    'region' => 'us-east-1',
    'version' => 'latest',
    'use_path_style_endpoint' => true
]);

$command = $client->getCommand('GetObject', [
    'Bucket' => 'dev-images',
    'Key' => '6a/7a/6a7a952d-faeb-4ca6-9034-ee433f1c6b46_150.jpg'
]);

$request = $client->createPresignedRequest($command, ($expires = time() + 172800));

return (string) $request->getUri();
```

Result,

```
http://localstack:4566/dev-images/6a/7a/6a7a952d-faeb-4ca6-9034-ee433f1c6b46_150.jpg?
X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&
X-Amz-Algorithm=AWS4-HMAC-SHA256&
X-Amz-Credential=test%2F20210505%2Fus-east-1%2Fs3%2Faws4_request&
X-Amz-Date=20210505T174423Z&
X-Amz-SignedHeaders=host&
X-Amz-Expires=172800&
X-Amz-Signature=816dfd508a3595d9ca0291be7f5c6bf4e1d1602278c1bc907ecbfe89e2bb79f1
```

### Using IAM role (instance role)

```
use Aws\Credentials\CredentialProvider;
use Aws\S3\S3Client;

$client = new S3Client([
    'endpoint' => 'http://localstack:4566',
    'credentials' => CredentialProvider::instanceProfile(),
    'region' => 'us-east-1',
    'version' => 'latest',
    'use_path_style_endpoint' => true
]);

$command = $client->getCommand('GetObject', [
    'Bucket' => 'dev-images',
    'Key' => '6a/7a/6a7a952d-faeb-4ca6-9034-ee433f1c6b46_150.jpg'
]);

$request = $client->createPresignedRequest($command, ($expires = time() + 172800));

return (string) $request->getUri();
```

Result (a `X-Amz-Security-Token` is added in this case),

```
http://localstack:4566/dev-images/6a/7a/6a7a952d-faeb-4ca6-9034-ee433f1c6b46_150.jpg?
X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&
X-Amz-Security-Token=test&
X-Amz-Algorithm=AWS4-HMAC-SHA256&
X-Amz-Credential=test%2F20210505%2Fus-east-1%2Fs3%2Faws4_request&
X-Amz-Date=20210505T174455Z&
X-Amz-SignedHeaders=host&
X-Amz-Expires=172800&
X-Amz-Signature=3b666137aee1c74a09adeb34d7a031ba2e69df6f6fc44eb2f47a32ac4d1363f6
```

**Comment by whummer** [comment]
Thanks for reporting @ganeko . We're currently looking into this issue in more detail.

Meanwhile, as a workaround we have introduced a new configuration value `S3_SKIP_SIGNATURE_VALIDATION=1` which you can enable in your LocalStack container environment, to temporarily skip the signature validation.

Hope that helps - please keep us posted how it goes. Thanks!

**Comment by ganeko** [comment]
> Thanks for reporting @ganeko . We're currently looking into this issue in more detail.
> 
> Meanwhile, as a workaround we have introduced a new configuration value `S3_SKIP_SIGNATURE_VALIDATION=1` which you can enable in your LocalStack container environment, to temporarily skip the signature validation.
> 
> Hope that helps - please keep us posted how it goes. Thanks!

Thank you very much @whummer and @macnev2013 for the incredible speed with the workaround!. We are waiting for the next release to be able to do tests since we use fixed versions in our environment for localstack. If you need any help or testing, please let me know. Thanks mates!

**Comment by whummer** [comment]
Thanks for the update @ganeko . We've pushed a couple more enhancements in S3 presign URL calculation (including #4081) - can you please pull the `latest` image and give it another try? We'll also release a new tagged version shortly.. Thanks!
