### ISSUE TITLE
S3 pre-signed multipart uploading does not work

### ISSUE THREAD

**Issue by richardARPANET** [localstack/localstack#3974]
# Type of request: This is a ...

- [x] bug report
- [ ] feature request

# Detailed description

When using localstack s3 I'm able to generate multi-part upload urls, but not upload the file parts to them.

## Expected behavior

When PUT request is made to the presigned urls the response should include `eTag` header.

## Actual behavior

Response is missing `eTag` header. This header is required, so the upload cannot proceed.
Here are the headers in the PUT request response:

```python
{
	'content-type': 'text/html; charset=utf-8',
	'content-length': '585',
	'access-control-allow-origin': 'localhost:4566',
	'access-control-allow-methods': 'GET,PUT',
	'access-control-allow-headers': '*',
	'access-control-expose-headers': 'ETag',
	'access-control-max-age': '86400',
	'access-control-allow-credentials': 'true',
	'last-modified': 'Wed, 05 May 2021 20:19:53 GMT',
	'x-amz-request-id': '932148CB34729FF5',
	'x-amz-id-2': 'xxxxxxxxxxxxxxxxxx/xxxxxxxxxxx/xxxxxxxxxxx',
	'connection': 'close',
	'date': 'Wed, 05 May 2021 20:19:53 GMT',
	'server': 'hypercorn-h11'
}
```

Note, when I run the exact same code against real S3, instead of localstack, everything works.

## Example code

Here's the actual code I'm running. 

https://github.com/VeemsHQ/veems/blob/master/veems/common/management/commands/import_seed_data.py#L57

This line and below is looping over the parts and doing the PUT requests for each of them.

**Comment by macnev2013** [comment]
Thanks for reporting @richardARPANET. Can you provide a self contained, isolated reproducible example (a git repo) with deployment instruction ? Thanks

**Comment by richardARPANET** [comment]
Sorry I don't have time

**Comment by macnev2013** [comment]
Hi @richardARPANET . We tired to reproduce the test case based on your use case. But we are not able to reproduce it. We have created a [git-repo](https://github.com/macnev2013/presigned-multipart-upload-python) with exact commands we have used. Can you take a look at it? Let us know if we are missing something, we will be happy to look into it.
 
Thanks.
