### ISSUE TITLE
[BUG] LocalStack PRO - HTTP API does not work

### ISSUE THREAD

**Issue by micheleangioni** [localstack/localstack#3976]
# Detailed description

Using LocalStack PRO, deploying an HTTP API (Gateway V2) doesn't work at all.

## Expected behavior

Once an application has been successfully deployed via Serverless Framework

<img width="461" alt="image" src="https://user-images.githubusercontent.com/7933034/117305513-1d43e300-ae7f-11eb-93a6-dcab48f588b7.png">

I expect the HTTP API to be working as expected.

## Actual behavior

The endpoints don't work.

HTTP call error (eg. via Postman):

<img width="589" alt="image" src="https://user-images.githubusercontent.com/7933034/117305612-39e01b00-ae7f-11eb-8171-0081c6466515.png">

Internal error:

<img width="639" alt="image" src="https://user-images.githubusercontent.com/7933034/117305709-4f554500-ae7f-11eb-97b6-b80e8e753ee7.png">

# Steps to reproduce

Try to deploy [sls-node-ts](https://github.com/micheleangioni/sls-node-ts/tree/httpApi) (use the `httpApi` branch!)

## Command used to start LocalStack

LocalStack is being started using `docker-compose`.
Unfortunately v0.12.10 has several problems on MacOS, therefore I had to downgrade to v0.12.9

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

In order to deploy the application, it's enough to run `npm run deploy-local`, i.e.

`node --max-old-space-size=4096 node_modules/serverless/bin/serverless.js deploy --stage local --region us-east-1 --verbose --force`

**Comment by whummer** [comment]
Thanks for reporting @micheleangioni . Looks like the URLs are incorrectly printed by the Serverless plugin - we'll fix that shortly.

Meanwhile, instead of the following:
```
https://b2ad9ec1.execute-api.us-east-1.localhostgraphql
```
... the URL for invoking your API should probably be:
```
https://b2ad9ec1.execute-api.localhost.localstack.cloud/graphql
```

Can you please also share the version of the `serverless-localstack` plugin you're using? Thanks for your help!

**Comment by micheleangioni** [comment]
Hi @whummer , 
thanks for your fast reply.

In the bug description there is a link to the source code of the deployed application, I'll re-post the links it here:

- [Source Code](https://github.com/micheleangioni/sls-node-ts)
- [Serverless File](https://github.com/micheleangioni/sls-node-ts/blob/httpApi/serverless.yml)
- [package.json](https://github.com/micheleangioni/sls-node-ts/blob/httpApi/package.json)

This is the version of the `serverless-localstack` plugin used:

![image](https://user-images.githubusercontent.com/7933034/117438749-3fe30400-af32-11eb-9bd7-e0610ebd04a8.png)

Hope it helps :)

**Comment by whummer** [comment]
Thanks for the pointer @micheleangioni . We've pushed a couple of fixes which should (hopefully) resolve this issue. Can you please try the following:

Pull the latest Docker image:
```
docker pull localstack/localstack
```

add a slash prefix to the API GW paths in `serverless.yml`:
```
path: /graphql
...
path: /users
```
update to the latest version of serverless-localstack:
```
"serverless-localstack": "^0.4.31"
```

Please keep us posted how it goes. Thanks!

**Comment by micheleangioni** [comment]
Hi @whummer , 
thanks for the answer but I have problems with the new image.
Once I've launched LocalStack (from MacOS) 

<img width="924" alt="image" src="https://user-images.githubusercontent.com/7933034/117618746-af453780-b16e-11eb-8149-1d2c407d806f.png">

any command fails

<img width="635" alt="image" src="https://user-images.githubusercontent.com/7933034/117618581-71e0aa00-b16e-11eb-8b7b-06b3f2f5d6c4.png">

<img width="641" alt="image" src="https://user-images.githubusercontent.com/7933034/117618607-7b6a1200-b16e-11eb-84f0-9e6a205897dd.png">

and of course the Dashboard doesn't connect

![image](https://user-images.githubusercontent.com/7933034/117618660-9046a580-b16e-11eb-97bd-538fcd1366f5.png)

**Comment by micheleangioni** [comment]
Hey @whummer , I've just re-tried but I'm getting the say error :( 
Please, let me know if I can help somehow.

Thanks!

**Comment by micheleangioni** [comment]
I just want to share some more tries, hoping it will be helpful.

I tried to give try downgrading to `localstack/localstack:0.12.9`

I fixed the path as suggested above

<img width="939" alt="image" src="https://user-images.githubusercontent.com/7933034/118265776-f35f7180-b4b9-11eb-8e01-e2c9dc0b0bec.png">

It correctly uploads to LocalStack

<img width="652" alt="image" src="https://user-images.githubusercontent.com/7933034/118265795-feb29d00-b4b9-11eb-961a-79f9f41e326c.png">

but unfortunately hitting the `https://7294b789.execute-api.localhost.localstack.cloud:4566/users` endpoint returns an error

<img width="646" alt="image" src="https://user-images.githubusercontent.com/7933034/118265873-1722b780-b4ba-11eb-9a4d-e1a1342841a4.png">

<img width="635" alt="image" src="https://user-images.githubusercontent.com/7933034/118265895-20138900-b4ba-11eb-8674-34245b6424e2.png">

Hope it helps :)

**Comment by micheleangioni** [comment]
Hey @whummer , could you please give an update about this? We really look forward to working with this :)
Thanks :)

**Comment by micheleangioni** [comment]
Thanks @whummer , the new v0.12.12 version fixes the problem! 🎉 

<img width="646" alt="image" src="https://user-images.githubusercontent.com/7933034/121356181-eacf4f00-c930-11eb-9ce7-1f04abca0c3c.png">

**Comment by whummer** [comment]
Awesome, glad you were able to get it working @micheleangioni ! Apologies for the long delay on this one - please keep us posted if there are any other issues.. Thanks for your help!
