### ISSUE TITLE
Support for reusable-delegation-sets

### ISSUE THREAD

**Issue by pll** [localstack/localstack#3984]
The route53 service supports an API for managing re-useable delegation sets (glue records):

- https://docs.aws.amazon.com/cli/latest/reference/route53/create-reusable-delegation-set.html
- https://docs.aws.amazon.com/cli/latest/reference/route53/delete-reusable-delegation-set.html
- https://docs.aws.amazon.com/cli/latest/reference/route53/get-reusable-delegation-set-limit.html
- https://docs.aws.amazon.com/cli/latest/reference/route53/list-reusable-delegation-sets.html

As far as I can tell, localstack does not support these calls:

```
$ awslocal route53 create-hosted-zone --name foo.bar --caller-reference foo.bar
{
    "HostedZone": {
        "Id": "/hostedzone/UNAPR8I9X5JFNSA",
        "Name": "foo.bar.",
        "Config": {
            "PrivateZone": false
        },
        "ResourceRecordSetCount": 0
    },
    "DelegationSet": {
        "NameServers": [
            "moto.test.com"
        ]
    }
}

$ awslocal route53 create-reusable-delegation-set --caller-reference foo.bar

An error occurred (404) when calling the CreateReusableDelegationSet operation: Not Found
$ awslocal route53 create-reusable-delegation-set --caller-reference foo.bar --hosted-zone-id=UNAPR8I9X5JFNSA

An error occurred (404) when calling the CreateReusableDelegationSet operation: Not Found
```

These calls are necessary for working with sub-domains, e.g. `subdomain.foo.bar` need to be created, and the NS record for that subdomain needs to be plugged into the `foo.bar` parent domain with an NS record for the new subdomain.  It's usually a good practice to create the re-usable delegation set first, then create the subdomain and the parent domain glue record with the same delegation set.

Thanks.
--
Paul

**Comment by whummer** [comment]
Thanks for reporting @pll . This seems to be related to https://github.com/localstack/localstack/issues/3961 . We have recently pushed a fix which should add support for these API methods - can you please do a `docker pull localstack/localstack` and give it another try with the `latest` Docker image? Thanks for your help.

**Comment by pll** [comment]
Hi @whummer - Sorry, didn't realize I had reported this yesterday. I even looked for the issue and didn't see it, then just figured I'd forgotten it since I filed a different bug at roughly the same time.

I did pull a :latest image this morning. But the delegation-sets were still failing. I'll re-pull and test.

Is there a difference between pulling :latest on localstack vs. localstack-full ?

**Comment by whummer** [comment]
Ok, great, thanks for the update. 

> Is there a difference between pulling :latest on localstack vs. localstack-full ?
`localstack` is the default `light` image, whereas `localstack-full` is a larger image which contains certain additional libraries pre-packaged (e.g., Elasticsearch). You can use either of the two images - if you are not customizing the configuration, then the default `localstack/localstack` image is used.

Closing this issue for now - please let us know if the problem persists. Thanks!
