### ISSUE TITLE
Cognito - updating an existing user's attirbute fails with UserNotFoundException

### ISSUE THREAD

**Issue by John-D8** [localstack/localstack#3990]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

Trying to update an existing user's attributes as an admin fails with a UserNotFoundException.

## Expected behavior

User's attributes should be updated successfully

## Actual behavior

UserNotFoundException is thrown

# Steps to reproduce

1) Create a user pool and add a user with at least one custom attribute
2) Try to update one of the custom attributes as an admin.

## Command used to start LocalStack

docker-compose

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

```
      const res = await cognito.adminUpdateUserAttributes({
        Username: 'user@example.com',
        UserPoolId: pool.Id,
        UserAttributes: [ {
          Name: 'custom:status',
          Value: 'invited'
        }],
      }).promise();
```

**Comment by whummer** [comment]
Thanks for reporting @John-D8 . This should (hopefully) be fixed in the meantime - can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists. Thanks for your help!
