### ISSUE TITLE
Cognito - Pre Authentication lambda not called on InitiateAuth

### ISSUE THREAD

**Issue by John-D8** [localstack/localstack#3991]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

When authenticating a user in a user pool with a defined Pre-Authentication lambda trigger, the lambda is not triggered, and so any error that would be thrown by the lambda and disallow the user authentication is not taken into consideration.

## Expected behavior

The configured pre-authentication lambda should be triggered, and its result should be taken into consideration when allowing/disallowing the user's authentication.

## Actual behavior

The pre-authentication lambda is not triggered

# Steps to reproduce

1) Create a user pool with a pre-authentication lambda trigger defined (possible throw an error in the lamdba to simulate authentication failure).
2) Create a user in the user pool
3) Try to authenticate with this user

## Command used to start LocalStack

docker-compose

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

```
      res = await cognito.initiateAuth({
        ClientId: clientId,
        AuthFlow: 'USER_PASSWORD_AUTH',
        AuthParameters: {
          USERNAME: 'user@example.com',
          PASSWORD: 'pass',
        },
      }).promise();
```

**Comment by whummer** [comment]
Thanks for reporting @John-D8 . We've tried to replicate this issue with the `latest` Docker image, but without success so far. Can you please share some more details - is the `PreAuthentication_Authentication` trigger Lambda not being called at all, or is it failing to reject the auth flow in case the Lambda raises an error? Thanks for your help!

**Comment by John-D8** [comment]
@whummer seems this doesn't happen now in the `latest` image..
