### ISSUE TITLE
Unable to get IAM security credentials from EC2 Instance Metadata Service

### ISSUE THREAD

**Issue by AghaKhan** [localstack/localstack#3994]
I am in https://s3.console.aws.amazon.com/s3/buckets/spidermonabucket?region=us-west-2&tab=objects
and see my file. I copied the URL https://spidermonabucket.s3-us-west-2.amazonaws.com/spidermona.mp4
Now I create in c# file
```
mediaFileUri = "https://spidermonabucket.s3-us-west-2.amazonaws.com/spidermona.mp4";
bucketName = "spidermonabucket"
transcriptionJobName = "maleblackwidowf6bbcd64-bd27-436a-aefe-97058dce5396Job" //fileName+Guid + "job"

 StartTranscriptionJobRequest requestJob = new StartTranscriptionJobRequest
            {
                TranscriptionJobName = transcriptionJobName,
                LanguageCode = "en-US",
                Media = new Media()
                {
                    MediaFileUri = mediaFileUri
                },
                OutputBucketName = bucketName
            };

            var responce = await transcribeServiceClient.StartTranscriptionJobAsync(requestJob);
```
I get error
Unable to get IAM security credentials from EC2 Instance Metadata Service
Thanks Agha

**Comment by whummer** [comment]
Thanks for reporting @AghaKhan . Can you please help us understand your environment setup a bit better? If I understand correctly, you're working in the real AWS environment, is that right? Please note that LocalStack is a service to test your logic locally, i.e., outside of the real AWS Cloud environment. 

I think your question is best answered in one of the AWS Support forums. Hope that helps - please let us know if you have any particular questions related to LocalStack. Thanks!
