### ISSUE TITLE
SQS sending/receiving much slower than expected - contains benchmarks and reproduction repo info

### ISSUE THREAD

**Issue by FrederikP** [localstack/localstack#3998]
# Type of request: This is a ...

[x] bug report ?
[ ] feature request
[x] FYI benchmark info !

# Detailed description

We were using localstack in our end2end tests for a service that uses sqs (and s3). We were wondering for a while, why our tests were taking forever and started investigating. We noticed that the sqs sends were taking much longer than we expected, making our transactions much slower than what we saw on production. And that although the localstack container was running on the same host, whereas in production there is some network latency between our service and sqs.

We isolated the issue by performing some benchmarks that didn't take any service specifics into consideration. I have created a [repo](https://gitlab.com/FrederikP/localstack-sqs-performance-repro/) that reproduces this. It's on gitlab, because I'm much quicker setting up proper CI there. We are running the benchmark against localstack (only sqs enabled) and the same benchmark against [elasticmq](https://github.com/softwaremill/elasticmq). We ended up switching to elasticmq in our end2end tests and it gives the benchmark some more meaning. 

We spent some time to figure this out, so we though it might be interesting to share it with you as some sort of a contribution. Of course it would be amazing if we could at some point switch back to localstack instead of using multiple containers to mock AWS.

## Expected behavior

We expected localstack perform similarly to what we see on production (of course we don't expect it to scale forever horizontally) or similarly to how elasticmq performs.

## Actual behavior
We are seeing performance that is an order of magnitude worse than what we expected, making it pretty much unusable in our end2end tests.

Also I noticed that localstack is pretty much using 100% of one CPU thread all the time during the benchmark.

Here is the [benchmark output for elasticmq:](https://gitlab.com/FrederikP/localstack-sqs-performance-repro/-/jobs/1252447243)

```
Using SQS endpoint: http://elasticmq:9324/
number of events to send: 1000
sending in parallel with 50 concurrent connections/workers
sending finished, avg duration: 0.065s, total duration: 3.454
receiving+deleting sequentially - one by one
received: 1000 of 1000
receiving+deleting finished, avg duration receive: 0.003s, avg duration delete: 0.003s, total duration: 5.926
```

Here is the [benchmark output for localstack](https://gitlab.com/FrederikP/localstack-sqs-performance-repro/-/jobs/1252447242):

```
Using SQS endpoint: http://localstack:4566/
number of events to send: 1000
sending in parallel with 50 concurrent connections/workers
sending finished, avg duration: 1.172s, total duration: 23.917
receiving+deleting sequentially - one by one
received: 1000 of 1000
receiving+deleting finished, avg duration receive: 0.041s, avg duration delete: 0.017s, total duration: 57.748
```

# Steps to reproduce

See https://gitlab.com/FrederikP/localstack-sqs-performance-repro/

**Comment by thrau** [comment]
Hi Frederik @FrederikP, and everyone following. Sorry for the long silence on this issue. There are some fundamental reasons why the current SQS provider is slow, which are hard to fix. We have rolled out an experimental version of a new SQS provider, and it would be great if you could give it a try.

Here are some results using the benchmark script you provided on my machine:

## moto SQS Provider
Start with: `docker run --rm -it -p 4566:4566 localstack/localstack`
```
 % AWS_ENDPOINT=http://localhost:4566 python benchmark.py
Using SQS endpoint: http://localhost:4566
number of events to send: 1000
sending in parallel with 50 concurrent connections/workers
sending finished, avg duration: 1.585s, total duration: 32.357
receiving+deleting sequentially - one by one
received: 1000 of 1000
receiving+deleting finished, avg duration receive: 0.065s, avg duration delete: 0.023s, total duration: 87.526
```

## localstack-native SQS Provider
Start with: `docker run --rm -it -e PROVIDER_OVERRIDE_SQS=asf -p 4566:4566 localstack/localstack`
```
 % AWS_ENDPOINT=http://localhost:4566 python benchmark.py
Using SQS endpoint: http://localhost:4566
number of events to send: 1000
sending in parallel with 50 concurrent connections/workers
sending finished, avg duration: 0.315s, total duration: 6.465
receiving+deleting sequentially - one by one
received: 1000 of 1000
receiving+deleting finished, avg duration receive: 0.010s, avg duration delete: 0.009s, total duration: 19.213
```
