### ISSUE TITLE
Unable to find forwarding rule for Host - S3

### ISSUE THREAD

**Issue by ntaylor-barnett** [localstack/localstack#4004]
# Type of request: This is a ...

[X ] bug report
[ ] feature request

# Detailed description

I have dug through as many articles as I can and it appears like this is a bit of a recurring issue. It does seem related to #3453 however.

I am using the aws-go-sdk to try and initiate an S3 multipart upload by calling CreateMultipartUploadWithContext. The bucket is created in other steps and AWS CLI confirms it exists (also executed from code). The example bucketname in this case is "testbucket" and the key is "55e3cfea0b8e10513a0400671d30bf33"

## Expected behavior

S3 Multipart upload is initialized and the call returns a 200 response.

## Actual behavior

 I get a 404 error from localstack and the localstack debug logs show the following.
`localstack-dbg | 2021-05-12T06:28:49:INFO:localstack.services.edge: Unable to find forwarding rule for host "localstack-dbg:4566", path "POST /testbucket/55e3cfea0b8e10513a0400671d30bf33?uploads=", target header "", auth header "AWS4-HMAC-SHA256 Credential=id string/20210512/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=af78b5c447f64de720abd7e584dce7d32e9f1d9725bf9973b8f3e724c9f71043", data "b''"`

# Steps to reproduce

## Command used to start LocalStack

```
localstack:
    image: localstack/localstack:0.12.6
    container_name: localstack-dbg
    ports:
      - '4563-4599:4563-4599'
      - '443:443'
      # - '8079:8080'
    environment: 
      - SERVICES=ssm,s3,kinesis,dynamodb,sqs
      - DEBUG=true
      - HOSTNAME=localstack-dbg
    #  - DATA_DIR=/tmp/localstack/data
    volumes:
     # - './.localstack:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      - intTestNet
```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

Go (using aws-sdk-go@v1.38.31

```
bucketName := "testbucket"
uploadid := "55e3cfea0b8e10513a0400671d30bf33"
metadata := make(map[string]*string, len(info.MetaData))
res, err := store.Service.CreateMultipartUploadWithContext(ctx, &s3.CreateMultipartUploadInput{
		Bucket:   aws.String(bucketName),
		Key:      store.keyWithPrefix(uploadId),
		Metadata: metadata,
	})
```

**Comment by whummer** [comment]
Thanks @ntaylor-barnett . From the request headers (`...Credential=id string/20210512...`) it seems that you have your client configured with `AWS_ACCESS_KEY_ID` set to the string `"id string"`, is that right? I think the issue might be here that we're not expecting the access key string to contain a space. Can we try configuring `AWS_ACCESS_KEY_ID=test` in your client? Thanks

**Comment by ntaylor-barnett** [comment]
> Thanks @ntaylor-barnett . From the request headers (`...Credential=id string/20210512...`) it seems that you have your client configured with `AWS_ACCESS_KEY_ID` set to the string `"id string"`, is that right? I think the issue might be here that we're not expecting the access key string to contain a space. Can we try configuring `AWS_ACCESS_KEY_ID=test` in your client? Thanks

This was it! Changing my bogus AWS_ACCESS_KEY_ID from "id string" to the less bogus "idstring" resolved it. Thank you so much!
