### ISSUE TITLE
nose is unmaintained and will stop working with Python 3.10

### ISSUE THREAD

**Issue by tirkarthi** [localstack/localstack#4007]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

https://github.com/nose-devs/nose/issues/1099 . Nose is unmaintained and it will stop working in Python 3.10 . It will be good to migrate to pytest . There https://github.com/pytest-dev/nose2pytest maintained by pytest devs that helps with migration.

**Comment by dominikschubert** [comment]
:heavy_check_mark:
