### ISSUE TITLE
localstack is handling SNS create-platform-endpoint differently than AWS

### ISSUE THREAD

**Issue by metalheart** [localstack/localstack#4009]
CreatePlatformEndpoint action for SNS service fails to execute multiple times with the same data.

[x] bug report
[ ] feature request

# Detailed description
AWS SNS documentation states that calling CreatePlatformEndpoint action multiple times must succeed: https://docs.aws.amazon.com/sns/latest/api/API_CreatePlatformEndpoint.html
Localstack returns an error on the second call because endpoint is present, moreover it seems that created endpoints are global and so it is not possible to create an endpoint with the same token for another platform application.

## Expected behavior
Calling CreatePlatformEndpoint action with the same arguments must succeed.

## Actual behavior
Calling CreatePlatformEndpoint action with the same arguments multiple times fails.

# Steps to reproduce
aws --endpoint-url=http://0.0.0.0:4566 sns create-platform-application --name my.app --platform GCM --attributes PlatformCredential=123
aws --endpoint-url=http://0.0.0.0:4566 sns create-platform-endpoint  --platform-application-arn arn:aws:sns:us-east-1:000000000000:app/GCM/my.app  --token test1
aws --endpoint-url=http://0.0.0.0:4566 sns create-platform-endpoint  --platform-application-arn arn:aws:sns:us-east-1:000000000000:app/GCM/my.app  --token test1

## Command used to start LocalStack
pipenv run localstack start

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
awslocal sns create-platform-application --name my.app --platform GCM --attributes PlatformCredential=123
awslocal sns create-platform-endpoint  --platform-application-arn arn:aws:sns:us-east-1:000000000000:app/GCM/my.app  --token test1
awslocal sns create-platform-endpoint  --platform-application-arn arn:aws:sns:us-east-1:000000000000:app/GCM/my.app  --token test1

**Comment by whummer** [comment]
Thanks for reporting @metalheart . This should be fixed upstream in the meantime - can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists. Thanks!

**Comment by whummer** [comment]
Actually, my apologies - this was my mistake, PR is still open.

**Comment by whummer** [comment]
@metalheart PR has been merged now - this is now available in the `latest` Docker image. Thanks!

**Comment by metalheart** [comment]
Hi! Thanks for a quick fix, I verified that it is working with the latest docker image!
