### ISSUE TITLE
Question: How to access other localstack AWS services from within a lambda?

### ISSUE THREAD

**Issue by vangorra** [localstack/localstack#401]
Since node lambdas are ran inside a sub docker container, they do not have access to the dns names docker compose creates. How are we suppose to create a lambda that will call another lambda or access an S3 bucket? The only workaround I've found so far is to set the endpoint host to the host ip of the compose stack. This works for running other lambdas but fails for working with S3.
This seems like a common use case. What am I missing?

**Comment by whummer** [comment]
Thanks for reporting @vangorra . Have you tried using the `LOCALSTACK_HOSTNAME` environment variable in your Lambda? Using this as the target host should normally work (basically it points to the host ip of the compose stack), although depending on your environment there may be additional customizations needed.

I'm wondering why you can access the Lambda API but not the S3 API - what are the error details in the S3 case?

**Comment by vangorra** [comment]
Allow me to clarify. Whenever I have a lambda that needs to manipulate S3, I get this error:
```Inaccessible host: cemx-local-app.172.17.0.1```
You'll notice I'm using LOCALSTACK_HOSTNAME. The problem is this will not resolve. S3 performs REST actions to bucket.hostname. So how can we work with S3 when the endpoint is an ip address?

**Comment by whummer** [comment]
I see, this is actually an issue inherent to how S3 addresses buckets - we need to configure the client library to use path style access instead of domain style access. This is documented in the [Troubleshooting section](https://github.com/localstack/localstack#troubleshooting) in the README.

**Comment by vangorra** [comment]
Perfect! I'm using the node sdk and the option s3ForcePathStyle is what I needed. Thank you!!!
