### ISSUE TITLE
Cognito - custom email sender lambda trigger not fired

### ISSUE THREAD

**Issue by yonatandbinahai** [localstack/localstack#4011]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

Adding a new user to a user pool with a defined custom email sender lambda trigger, does not trigger the defined lambda.

## Expected behavior

Custom email lambda should be triggered

## Actual behavior

Custom email lambda is not triggered

# Steps to reproduce

1) Create a user pool with a custom email sender lambda trigger
2) Add a user to the user pool

## Command used to start LocalStack

docker-compose

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

```
      await this.cognitoService.adminCreateUser({
        UserPoolId: pool.Id,
        Username: 'user@example.com',
        UserAttributes: [
          { Name: 'email', Value: user.username },
          { Name: 'email_verified', Value: 'true' },
        ],
        TemporaryPassword: 'SomePass9'
        DesiredDeliveryMediums: [ 'EMAIL' ],
      }).promise();
```

**Comment by whummer** [comment]
Thanks for reporting @John-D8 . This should (hopefully) be fixed in the meantime. Can you please pull the `latest` Docker image and give it another try? Please keep us posted how it goes. Thanks for your help!

**Comment by yonatandbinahai** [comment]
@whummer this still seems to reproduce in 0.12.17.5

**Comment by whummer** [comment]
Thanks @yonatandbinahai . We've just looked into this again and pushed a few more enhancements - can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists.. (further details to be discussed via Slack). Thanks!
