### ISSUE TITLE
 The security token included in the request is invalid.

### ISSUE THREAD

**Issue by manas86** [localstack/localstack#4012]
# Type of request: This is a ...

[ ] bug report

# Detailed description

My application container keeps getting " The security token included in the request is invalid." while calling SNS endpoint.
Inside my application, I could reach the localstack and query properly `aws --endpoint-url=http://localstack:4566 sqs list-queues --region eu-west-1`, however when my application tries to reach this same services, it seems my application is trying to connect the actual AWS endpoint, not the localstack.  i'm using latest localstack and inside my application container AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY all are set as dummy for localstack. 
`
DEBUG wire - http-outgoing-1 << "<?xml version="1.0"?><ErrorResponse xmlns="http://queue.amazonaws.com/doc/2012-11-05/"><Error><Type>Sender</Type><Code>InvalidClientTokenId</Code><Message>The security token included in the request is invalid.</Message><Detail/></Error><RequestId>caaa8379-9945-5e7a-ba5d-da6ff25fdc2e</RequestId></ErrorResponse>"`

**Comment by mgagliardo** [comment]
Hello @manas86, can you please show how are you running localstack? And at least some of the code of your application?

You can see it's indeed calling AWS:  `DEBUG wire - http-outgoing-1 << "<?xml version="1.0"?><ErrorResponse xmlns="http://queue.amazonaws.com`

**Comment by manas86** [comment]
```
sure, version: '2'
services:
  # Initiating localstack
  local-stack-endpoints:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack}"
    image: localstack/localstack
    hostname: localstack
    ports:
      - "4566:4566"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      SERVICES: s3,sqs,lambda,ec2,dynamodb,sns,cloudformation,sts,iam,cloudwatch,apigateway,events,secretsmanager
      COMPOSE_HTTP_TIMEOUT: 120
      DEBUG: 1
      DATA_DIR: /tmp/localstack/data
      PORT_WEB_UI: 8080
      LAMBDA_EXECUTOR: ${LAMBDA_EXECUTOR- }
      LAMBDA_REMOTE_DOCKER: 'false'
      LAMBDA_REMOVE_CONTAINERS: 'true'
      KINESIS_ERROR_PROBABILITY: ${KINESIS_ERROR_PROBABILITY- }
      DOCKER_HOST: unix:///var/run/docker.sock
      HOST_TMP_FOLDER: ${TMPDIR}
      AWS_ACCESS_KEY_ID: dummyaccess
      AWS_SECRET_ACCESS_KEY: dummysecret
      AWS_DEFAULT_REGION: eu-west-1
    volumes:
      - ./data:/tmp/localstack
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./bin:/docker-entrypoint-initaws.d
    networks:
      - my_awesome_network
  # creating streamset container
  streamsets-dc:
    image: streamset:latest
    container_name: streamsets-dc
    ports:
      - 18443:18443
    entrypoint: /bin/sh -c
    command: >
      "
      /docker-entrypoint.sh dc -exec;
      "
    depends_on:
      - local-stack-endpoints
    volumes:
      - ./streamsets/config.properties:/apps/streamsets/streamsets-datacollector/etc/config.properties
    networks:
      - my_awesome_network
    environment:
      ENVIRONMENT: PRD
      SDC_JAVA_OPTS: "-Dfile.encoding=UTF-8 -Dsun.jnu.encoding=UTF-8"
      SDC_JAVA8_OPTS: "-Dcom:amazonaws:sdk:disableCertChecking"
      SDC_MX_HEAP_SET: 1024
      SDC_MN_HEAP_SET: 1024
      AWS_ACCESS_KEY_ID: dummyaccess
      AWS_SECRET_ACCESS_KEY: dummysecret
      AWS_DEFAULT_REGION: eu-west-1
```
I think somewhere in my application I have to initalize the endpoint, the application is a 3rd party application though.

**Comment by mgagliardo** [comment]
Indeed if you do not have access to the application base code, it would be great to know what the application does internally.
Thing is you can't override AWS endpoints with environment variables (sadly).

**Comment by mgagliardo** [comment]
Closing this for now as it seems internal to the application, if you have any more information please let us know or feel free to reopen. Thanks.

**Comment by manas86** [comment]
Yes, you can close this, but as a workaround, if anyone has a similar issue, then all you can do is change the /etc/hosts file to refer to the localstack container ip for your app.  Although docker-compose should able to find each other but inmy case it is not. So just proposing the workaround. The more subtle way is to add the network's tag for ipam and ipv4_address for each services.  But please close this call. thanks.
