### ISSUE TITLE
Secretsmanager GetSecretValue Query with Incomplete ARN

### ISSUE THREAD

**Issue by oguzdemir** [localstack/localstack#4014]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description
[Per aws's `GetSecretValue` description, the `secret-id` parameter can be an incomplete ARN.](https://docs.aws.amazon.com/cli/latest/reference/secretsmanager/get-secret-value.html)

> _If you specify an ARN, we generally recommend that you specify a complete ARN. You can specify a partial ARN too—for example, if you don’t include the final hyphen and six random characters that Secrets Manager adds at the end of the ARN when you created the secret. A partial ARN match can work as long as it uniquely matches only one secret._

However, if I omit the last hypen and the random 6 chars string from the ARN, it doesn't return the secret. 

# Steps to reproduce
I create a secret with
```
awslocal secretsmanager create-secret --name="test-something" --secret-string="x"
```
Result:
```
{
    "ARN": "arn:aws:secretsmanager:us-west-2:00000000:secret:test-something-nLBTe",
    "Name": "test-something",
    "VersionId": "89c5c869-de83-491f-8045-3caea868e7f8"
}
```

If I do:
```
awslocal secretsmanager get-secret-value \
    --secret-id=arn:aws:secretsmanager:us-west-2:00000000:secret:test-something-nLBTe
```

It's perfectly fine.
```
{
    "ARN": "arn:aws:secretsmanager:us-west-2:00000000:secret:test-something-nLBTe",
    "Name": "test-something",
    "VersionId": "89c5c869-de83-491f-8045-3caea868e7f8",
    "SecretString": "x",
    "VersionStages": [
        "AWSCURRENT"
    ],
    "CreatedDate": 1620918559
}
```

But if I do 
```
awslocal secretsmanager get-secret-value \
    --secret-id=arn:aws:secretsmanager:us-west-2:00000000:secret:test-something
```

It returns error
```
An error occurred (ResourceNotFoundException) when calling the GetSecretValue operation: Secrets Manager can't find the specified secret.
```

I figured out that if I add a hyphen `-` at the end, it also returns the value. If I add hyphen + some random string, it also returns the value even though the ARN doesn't match. 

I believe it is caused by the following lines, it basically omits after the last hyphen and send the remaining as the request. 
https://github.com/localstack/localstack/blob/cb2e893e04421cdedadf6932064fda638c94dae8/localstack/services/secretsmanager/secretsmanager_listener.py#L23-L25

Thanks!

**Comment by whummer** [comment]
Thanks for reporting @oguzdemir . This should be fixed in #4018 - can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists. Thanks!
