### ISSUE TITLE
api_calls files renamed - Undocumented Breaking Change!

### ISSUE THREAD

**Issue by collinsauve** [localstack/localstack#4017]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

v0.12.10 includes [this commit](https://github.com/localstack/localstack/commit/6bb4483e5745f4c92a16e4b69c145a51f6ef0a52#diff-6e3681013970e454ab7ccd3713aad4c61d42f1b45aa7fce7fbacb86585856bb5) which changes the `API_FILE_PATTERN` from `{api}_api_calls.json` to `api_calls_{api}.json`.

For anyone using this feature (persistence in separate files), they will lose previously persisted data.

This breaking change does not appear to be documented at https://github.com/localstack/localstack/releases

## Expected behavior

Breaking changes are documented in releases.

## Actual behavior

Not documented.

**Comment by collinsauve** [comment]
P.S. if anyone wants a workaround, here's a script to move them (assume PWD is $DATA_DIR)

```
for f in *_api_calls.json; do
  sudo mv "$f" "$(echo "$f" | sed 's/_api_calls.json$/.json/' | sed 's/^/api_calls_/')"
done
```

**Comment by whummer** [comment]
Thanks for the pointer @collinsauve , and apologies for the undocumented change. The reason for it was that this name pattern makes it much easier to identify all persistence files with the same prefix - sorry I didn't catch this early enough in my PR review. Sorry again, and thanks for your help!
