### ISSUE TITLE
Unable to retrieve tags for Parameters in SSM Parameter Store

### ISSUE THREAD

**Issue by sappusaketh** [localstack/localstack#4019]
# Type of request: This is a bug report

[ X ] bug report
[ ] feature request

# Detailed description
Unable to retrieve SSM parameter tags

## Expected behavior
Should be able to add and retrieve tags for Parameters in SSM Parameter Store
## Actual behavior
* `put-parameter` call takes tags option when adding a param but it is not clear whether those tags are getting created. 
* When I call `list-tags-for-resource` no tags are returned.

# Steps to reproduce
```bash
# Add Parameter with Tags
aws --endpoint-url=http://localhost:4566 --region=us-west-2 ssm put-parameter --name "/testing/tags" --value "123" --type "String" --tags "Key=os,Value=windows"

# Get Parameters that matches the tag filter. This is returning above added Parameter
aws --endpoint-url=http://localhost:4566 --region=us-west-2 ssm describe-parameters --parameter-filters "Key=tag:os,Option=Equals,Values=windows"

# This call supposed to return tags added in first call but it returns empty array
aws --endpoint-url=http://localhost:4566 --region=us-west-2 ssm list-tags-for-resource  --resource-type "Parameter" --resource-id "/testing/tags"
```
## Command used to start LocalStack

```bash
docker-compose up
```

**Comment by usmangani1** [comment]
@sappusaketh Thanks for reporting the issue.

There has been a small issue when adding the tags to the resource in the upstream. We are working on the fix.We will update here once done.Thanks

**Comment by whummer** [comment]
Thanks @sappusaketh @usmangani1 . This should be fixed in the meantime - can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists. Thanks!

**Comment by sappusaketh** [comment]
Hi @whummer  I pulled latest image and ran above commands and I m still seeing the issue

**Comment by sappusaketh** [comment]
Pulled the latest image and works as expected now thanks for fixing it @usmangani1 @whummer
