### ISSUE TITLE
Failed to connect to localhost port 4566: Connection refused

### ISSUE THREAD

**Issue by venkatkollimarla** [localstack/localstack#4020]
# Type of request: This is a connection issue to localstack endpoint
[x] bug report

# Detailed description
Hi Team, 
I am able to use localstack locally and test services S3 and SQS as part of my python integration tests
When I am running docker-compose up -d in CircleCI job for my integration tests to test against localstack URL
I could see the container up and running

Am I missing anything in config or something?

### My docker-compose.yml is:
`version: "3.7"
services:
  localstack:
    container_name: awslocal
    image: localstack/localstack
    hostname: awslocal
    network_mode: bridge
    ports:
      - "${EDGE_PORT-4566}:4566"
    environment:
      - SERVICES=s3,sqs,iam
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=/tmp/localstack
      - HOSTNAME_EXTERNAL=awslocal
      - AWS_DEFAULT_REGION=us-east-2
    volumes:
      - "${TEMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
`
...
## Expected behavior
Should connect to localstack endpoint from aws-cli or python code
...

## Actual behavior
`#!/bin/bash -eo pipefail
**docker-compose up -d --remove-orphans**
docker ps
docker inspect --format='{{json .Config}}' awslocal
curl http://localhost:4566/health
Pulling localstack (localstack/localstack:)...
latest: Pulling from localstack/localstack

Digest: sha256:e8afe0dd02a84b3042d62c76a53ac84c6e94547399bc27288905ac09b01f52aa

**Status: Downloaded newer image for localstack/localstack:latest**

Creating awslocal ... 

CONTAINER ID        IMAGE                   COMMAND                  CREATED             STATUS              PORTS                                        NAMES
**20c44b290126        localstack/localstack   "docker-entrypoint.sh"   7 seconds ago       Up 5 seconds        4571/tcp, 0.0.0.0:4566->4566/tcp, 8080/tcp   awslocal**

{"Hostname":"awslocal","Domainname":"","User":"","AttachStdin":false,"AttachStdout":false,"AttachStderr":false,"ExposedPorts":{"4566/tcp":{},"4571/tcp":{},"8080/tcp":{}},
"Tty":false,"OpenStdin":false,"StdinOnce":false,
"Env":["SERVICES=s3,sqs,iam","DOCKER_HOST=unix:///var/run/docker.sock","HOST_TMP_FOLDER=/tmp/localstack",
**"HOSTNAME_EXTERNAL=awslocal"**,"AWS_DEFAULT_REGION=us-east-2",
"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/jvm/java-11/bin:/opt/terraform",
"NODE_VERSION=15.14.0","YARN_VERSION=1.22.5","LANG=C.UTF-8","JAVA_HOME=/usr/lib/jvm/java-11",
"MAVEN_HOME=/usr/share/maven","MAVEN_CONFIG=/opt/code/localstack","ES_TMPDIR=/tmp",
"LOCALSTACK_BUILD_DATE=2021-05-13","LOCALSTACK_BUILD_GIT_HASH=cb2e893e",
"LD_LIBRARY_PATH=/usr/lib/jvm/java-11/lib:/usr/lib/jvm/java-11/lib/server",
**"LOCALSTACK_HOSTNAME=localhost"**,"USER=localstack","PYTHONUNBUFFERED=1",
"PYTHONPATH=/opt/code/localstack/.venv/lib/python3.8/site-packages","START_WEB=0"],"Cmd":null,"Image":"localstack/localstack",
"Volumes":{"/tmp/localstack":{},"/var/run/docker.sock":{}},"WorkingDir":"/opt/code/localstack",
"Entrypoint":["docker-entrypoint.sh"],"OnBuild":null,"Labels":{"authors":"LocalStack Contributors",
"com.docker.compose.config-hash":"a2f7e37c91067ec06be3f5e803de0737c69252d6c44cbb32fff2ba3eeb104743",
"com.docker.compose.container-number":"1","com.docker.compose.oneoff":"False","com.docker.compose.project":"project",
"com.docker.compose.service":"localstack","com.docker.compose.version":"1.24.1"}}

**curl: (7) Failed to connect to localhost port 4566: Connection refused**`
...

# Steps to reproduce
Using this docker-compose.yml file below, I was able to run docker-compose up and see the container running with name "awslocal" but cannot even check health

## Command used to start LocalStack
`docker-compose up -d --remove-orphans`
...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
`curl http://localhost:4566/health`
...

**Comment by venkatkollimarla** [comment]
> Hello @venkatkollimarla, could you elaborate a bit more? If I understand correctly you are running the localstack container on your CircleCI job and then running an integration test against it using `http://localhost:4566`, is that correct?
> If that is the case, CrcleCI just runs a docker in docker implementation, so what you would need to do is to use a network and attach to it (for example, using another docker container on the same network and using `--link`).
> You can find an example from CircleCI [here](https://github.com/CircleCI-Public/circleci-demo-docker/tree/docker-compose)
> 
> Let us know how it goes. Cheers

Hi @mgagliardo 
Thanks for the response!
The link went to their repo, but in their docker-compose,yml I did not see any --link w.r.t network)
Could you share the direct link to example you were referring to?

**Comment by mgagliardo** [comment]
Sure, no need to `--link` though, just being on the same network is enough.

https://github.com/CircleCI-Public/circleci-demo-docker/blob/docker-compose/.circleci/config.yml#L77

**Comment by venkatkollimarla** [comment]
> Sure, no need to `--link` though, just being on the same network is enough.
> 
> https://github.com/CircleCI-Public/circleci-demo-docker/blob/docker-compose/.circleci/config.yml#L77

Thanks a lot pointing to right direction!
I did try these as below:
**docker-compose up -d**

# docker-compose will start 2 containers, the one with service will be named `contacts`
# we start another container with curl in the same network as `contacts`, this way we have
# all exposed ports from `contacts` available on `localhost` in this new container
**docker run --network container:awslocal \
  appropriate/curl --retry 10 --retry-delay 1 --retry-connrefused http://localhost:8080/awslocal/test**
**curl http://localhost:4566/health**

Could you help identify what else is missing/causing?
=======
I see this in the console as result:
![image](https://user-images.githubusercontent.com/26193384/118203764-bac48700-b42a-11eb-9586-507a7d2fe712.png)

**Comment by mgagliardo** [comment]
Yes, what I sent you was an example, but in there you are:
* Using a non-existent image
* Pointing to an address that does and will not existe (`localhost:8080` instead of `localstack:4566`)

What you should be doing is using the AWS CLI container (for example) and adding the `endpoint_url` flag so it points to the localstack container on the same network.

**Comment by venkatkollimarla** [comment]
@mgagliardo I ran it with correct host, my bad I posted it too quick
```
docker run --network container:awslocal \
              appropriate/curl --retry 20 --retry-delay 2 --retry-connrefused http://awslocal:4566/
            docker inspect --format='{{json .Config}}' awslocal
            sleep 30
curl http://awslocal:4566/health
```
docker run command above works and I could see the service running but curl failed and also the tests: 
{"status": "running"}{"Hostname":"awslocal","Domainname":"","User":"","AttachStdin":false,"AttachStdout":false,"AttachStderr":false,"ExposedPorts":{"4566/tcp":{},"4571/tcp":{},"8080/tcp":{}},"Tty":false,"OpenStdin":false,"StdinOnce":false,"Env":["SERVICES=s3,sqs,iam","DOCKER_HOST=unix:///var/run/docker.sock","HOST_TMP_FOLDER=/tmp/localstack","HOSTNAME_EXTERNAL=awslocal","AWS_DEFAULT_REGION=us-east-2","PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/jvm/java-11/bin:/opt/terraform","NODE_VERSION=15.14.0","YARN_VERSION=1.22.5","LANG=C.UTF-8","JAVA_HOME=/usr/lib/jvm/java-11","MAVEN_HOME=/usr/share/maven","MAVEN_CONFIG=/opt/code/localstack","ES_TMPDIR=/tmp","LOCALSTACK_BUILD_DATE=2021-05-13","LOCALSTACK_BUILD_GIT_HASH=4d1a1af8","LD_LIBRARY_PATH=/usr/lib/jvm/java-11/lib:/usr/lib/jvm/java-11/lib/server","LOCALSTACK_HOSTNAME=localhost","USER=localstack","PYTHONUNBUFFERED=1","PYTHONPATH=/opt/code/localstack/.venv/lib/python3.8/site-packages","START_WEB=0"],"Cmd":null,"Image":"localstack/localstack","Volumes":{"/tmp/localstack":{},"/var/run/docker.sock":{}},"WorkingDir":"/opt/code/localstack","Entrypoint":["docker-entrypoint.sh"],"OnBuild":null,"Labels":{"authors":"LocalStack Contributors","com.docker.compose.config-hash":"0aa3266ed4a877e8a918e675347e6a7ef0380c5bfe7839da80f08d67f0bd9224","com.docker.compose.container-number":"1","com.docker.compose.oneoff":"False","com.docker.compose.project":"project","com.docker.compose.service":"localstack","com.docker.compose.version":"1.24.1"}}

**curl: (6) Could not resolve host: awslocal**

**Comment by mgagliardo** [comment]
Can you remove `network_mode: bridge` from the docker compose and try again?

**Comment by venkatkollimarla** [comment]
> Can you remove `network_mode: bridge` from the docker compose and try again?
Yeah, I did remove `network_mode: bridge` tried but still the curl failed.

This is my current docker-compose file:
```
version: "3.7"
services:
  localstack:
    container_name: awslocal
    image: localstack/localstack
    hostname: awslocal
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,sqs,iam
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=/tmp/localstack
      - HOSTNAME_EXTERNAL=awslocal
      - AWS_DEFAULT_REGION=us-east-2
    volumes:
      - "${TEMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

Output on console:
Status: Downloaded newer image for localstack/localstack:latest

Creating awslocal ... 

CONTAINER ID        IMAGE                   COMMAND                  CREATED             STATUS                  PORTS                                        NAMES
3d81ddadd0dc        localstack/localstack   "docker-entrypoint.sh"   1 second ago        Up Less than a second   4571/tcp, 0.0.0.0:4566->4566/tcp, 8080/tcp   awslocal
running-docker-run--network-container:awslocal
Unable to find image 'appropriate/curl:latest' locally
latest: Pulling from appropriate/curl

Digest: sha256:c8bf5bbec6397465a247c2bb3e589bb77e4f62ff88a027175ecb2d9e4f12c9d7
Status: Downloaded newer image for appropriate/curl:latest
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Transient problem: connection refused Will retry in 2 seconds. 20 
Warning: retries left.
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Transient problem: connection refused Will retry in 2 seconds. 19 
Warning: retries left.
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Transient problem: connection refused Will retry in 2 seconds. 18 
Warning: retries left.
100    21  100    21    0     0    777      0 --:--:-- --:--:-- --:--:--   777
{"status": "running"}{"Hostname":"awslocal","Domainname":"","User":"","AttachStdin":false,"AttachStdout":false,"AttachStderr":false,"ExposedPorts":{"4566/tcp":{},"4571/tcp":{},"8080/tcp":{}},"Tty":false,"OpenStdin":false,"StdinOnce":false,"Env":["SERVICES=s3,sqs,iam","DOCKER_HOST=unix:///var/run/docker.sock","HOST_TMP_FOLDER=/tmp/localstack","HOSTNAME_EXTERNAL=awslocal","AWS_DEFAULT_REGION=us-east-2","PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/jvm/java-11/bin:/opt/terraform","NODE_VERSION=15.14.0","YARN_VERSION=1.22.5","LANG=C.UTF-8","JAVA_HOME=/usr/lib/jvm/java-11","MAVEN_HOME=/usr/share/maven","MAVEN_CONFIG=/opt/code/localstack","ES_TMPDIR=/tmp","LOCALSTACK_BUILD_DATE=2021-05-14","LOCALSTACK_BUILD_GIT_HASH=02ef6a04","LD_LIBRARY_PATH=/usr/lib/jvm/java-11/lib:/usr/lib/jvm/java-11/lib/server","LOCALSTACK_HOSTNAME=localhost","USER=localstack","PYTHONUNBUFFERED=1","PYTHONPATH=/opt/code/localstack/.venv/lib/python3.8/site-packages","START_WEB=0"],"Cmd":null,"Image":"localstack/localstack","Volumes":{"/tmp/localstack":{},"/var/run/docker.sock":{}},"WorkingDir":"/opt/code/localstack","Entrypoint":["docker-entrypoint.sh"],"OnBuild":null,"Labels":{"authors":"LocalStack Contributors","com.docker.compose.config-hash":"e0b160f3cfd0a0bcca813c555e22f3680d75016d92e200c3f7adf43206d79c9f","com.docker.compose.container-number":"1","com.docker.compose.oneoff":"False","com.docker.compose.project":"project","com.docker.compose.service":"localstack","com.docker.compose.version":"1.24.1"}}

**curl: (6) Could not resolve host: awslocal**

Exited with code exit status 6

**Comment by venkatkollimarla** [comment]
Hey @mgagliardo : Thank you so much for your help and support here!
I was able to resolve this, below is the CircleCI config that helped me:
Note: We do not even need any remote-docker setup or any docker-compose config file, just the image would do the job

```
integration_tests:
    working_directory: "~/project"
    docker:
      - image: circleci/python:3.6.8
      - image: localstack/localstack
    steps:
      - *attach_workspace
      - *add_permissions_to_environment
      - restore_cache:
          name: "Restore Dependencies from Cache"
          key: deps-{{ .Branch }}-{{ checksum "requirements.txt" }}-{{ checksum "test_requirements.txt" }}
      - run:
          name: Waiting for localstack to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 4566 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for localstack && exit 1
      - run:
          name: "Run Integration Tests"
          command: |
            make integration-tests
      - *persist_workspace
```

**Comment by mgagliardo** [comment]
Thanks for the update and good to know it worked for you @venkatkollimarla . Cheers!
