### ISSUE TITLE
Content-Length in S3 "GetObject" is nil using AWS-SDK-GO package

### ISSUE THREAD

**Issue by ntaylor-barnett** [localstack/localstack#4021]
# Type of request: This is a ...

[X ] bug report
[ ] feature request

# Detailed description

My code needs to get a file it has uploaded into S3. A part of the logic is to make decisions based on the length of data of the object prior to processing it. Unfortunately, I am seeing a difference in behaviour between Localstack and real AWS S3.

Note: This is not my code. I am attempting to implement TUS.io. The part of their code that hits the problem described below is here: https://github.com/tus/tusd/blob/master/pkg/s3store/s3store.go#L891
This is also accessing S3 via the latest AWS SDK Go package.

I am mainly raising it here as the difference in behaviour is observed through the AWS Go SDK when connecting to either Localstacks S3 or AWSs S3.

## Expected behavior

All relevant fields are populated in return and behaves the same as S3 in AWS. Below screen shot is from the debugged code using real AWS S3
![S3 Good](https://user-images.githubusercontent.com/39506459/118206123-277c6780-b4a5-11eb-985f-39338e31ed7f.PNG)

## Actual behavior

ContentLength is not populated.
![S3 Bad](https://user-images.githubusercontent.com/39506459/118206160-3d8a2800-b4a5-11eb-81ce-d3a217ca3291.PNG)

Note: When I use the AWS CLI to interact with Localstack and enable debug, I can see "Content-Length" in the CLIs debug output.

# Steps to reproduce

## Command used to start LocalStack
```
localstack:
    image: localstack/localstack:0.12.10
    container_name: localstack-dbg
    ports:
      - '4563-4599:4563-4599'
      - '443:443'
      # - '8079:8080'
    environment: 
      - SERVICES=ssm,s3,kinesis,dynamodb,sqs
      - DEBUG=true
      - HOSTNAME=localstack-dbg
    #  - DATA_DIR=/tmp/localstack/data
    volumes:
     # - './.localstack:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      - intTestNet
```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

```
obj, err := store.Service.GetObjectWithContext(ctx, &s3.GetObjectInput{
		Bucket: aws.String(store.Bucket),
		Key:    store.metadataKeyWithPrefix(uploadId + ".part"),
	})
```
store.Service is the S3 client from the SDK. err is nil and it all looks good with the exception that content-length is not populated.

# Remediation attempts

I have tried to inject delays thinking there might be some kind of race condition internal to localstack but that has had no change. Using the AWS CLI, I can confirm that the file exist and it is of a length I expect. Other S3 operations seem to work fine and the file can be downloaded, however the content-length not being set is unusual. I have tried digging into the AWS SDK code to see what is going on there, but it is fairly tricky to walk through it all to find what is going on.

**Comment by macnev2013** [comment]
Thanks for reporting @ntaylor-barnett. We tried to reproduce the issue. But it is working as expected.

Here's the simple command/snippet we used. Please let us know if we are missing anything.
Thanks

`docker-compose.yaml`
```
version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    network_mode: bridge
    ports:
      - "4566:4566"
      - "4571:4571"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=${SERVICES- }
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```
Run docker-compose
```
docker-compose up -d
```

`test.go`
```
package main

import (
    "github.com/aws/aws-sdk-go/aws"
    "github.com/aws/aws-sdk-go/aws/session"
    "github.com/aws/aws-sdk-go/service/s3"
	"github.com/aws/aws-sdk-go/aws/credentials"
    "fmt"
    "os"
)

func main() {

    bucket := "test"
	item := "test"
	const S3Endpoint = "http://localhost:4566"

    sess, _ := session.NewSession(&aws.Config{
        Region: aws.String("us-east-1"),
		Credentials: credentials.NewStaticCredentials("test", "test", ""),
		Endpoint: aws.String(S3Endpoint),
	},)

    svc := s3.New(sess, &aws.Config{
   	    DisableRestProtocolURICleaning: aws.Bool(true),
    })

    out, _ := svc.GetObject(&s3.GetObjectInput {
   	    Bucket: aws.String(bucket),
    	Key: aws.String(item),
    })

    fmt.Println("Response:", out)
}

func exitErrorf(msg string, args ...interface{}) {
    fmt.Fprintf(os.Stderr, msg+"\n", args...)
    os.Exit(1)
}
```
Run the code
```
$ go run test.go
```
