### ISSUE TITLE
Error waiting for SNS topic subscription

### ISSUE THREAD

**Issue by sparkmuse** [localstack/localstack#4022]
# Type of request: This is a ...

[x ] bug report
[ ] feature request

# Detailed description

I create a topic, a queue and a subscription. After I have created them I tried to destroy my resources I get an error.

## Expected behavior

My resources are deleted without errors.

## Actual behavior

An error occurs:

```bash
aws_sns_topic_subscription.subscription: Destroying... [id=arn:aws:sns:us-east-1:000000000000:topic:a0d47652-3ae4-46df-9b63-3cb6e154cfcd]
╷
│ Error: error waiting for SNS topic subscription (arn:aws:sns:us-east-1:000000000000:topic:a0d47652-3ae4-46df-9b63-3cb6e154cfcd) deletion: InvalidParameter: Unable to find subscription for given ARN
│   status code: 400, request id: 2168e636
```

# Steps to reproduce

With the following terraform main.tf configuration:

```tf
terraform {
  required_version = ">= 0.12.26"
}

provider "aws" {
  region                      = "us-east-1"
  s3_force_path_style         = true
  skip_credentials_validation = true
  skip_metadata_api_check     = true
  skip_requesting_account_id  = true

  endpoints {
    sns            = "http://localhost:4566"
    sqs            = "http://localhost:4566"
  }
}

resource "aws_sqs_queue" "queue" {
  name = "queue"
}

resource "aws_sns_topic" "topic" {
  name = "topic"
}

resource "aws_sns_topic_subscription" "subscription" {
  endpoint = aws_sqs_queue.queue.arn
  protocol = "sqs"
  topic_arn = aws_sns_topic.topic.arn
}

```

I run the commands:
```bash
terraform init
terraform plan
terraform apply -auto-approve

terraform destroy # Error caused here
```

## Command used to start LocalStack

```bash
docker run --rm -ti -p 4566:4566 localstack/localstack
```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

<none>

**Comment by usmangani1** [comment]
@sparkmuse Thanks for reporting the issue.

There seems to be an issue while deleting the subscription created. We are looking into this.

**Comment by whummer** [comment]
Thanks @sparkmuse @usmangani1 . This should be fixed upstream in the meantime - can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists. Thanks!

**Comment by sparkmuse** [comment]
Thanks a lot. @whummer  @usmangani1  I confirm this is working now.
