### ISSUE TITLE
--elasticsearch-cluster-config is (at least partially) ignored

### ISSUE THREAD

**Issue by Dgame** [localstack/localstack#4023]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

I'm using `localstack:latest` as a docker image. But when I try to create a new Elasticsearch domain with a specific configuration, the `InstanceType` and `InstanceCount` are ignored.

## Expected behavior

`InstanceCount` and `InstanceType` are recognised.

## Actual behavior

InstanceCount and InstanceType are ignored.

# Steps to reproduce

Setup `localstack:latest` as a docker image and try to setup an elasticsearch domain with `--elasticsearch-cluster-config` included.

## Command used to start LocalStack

Since I'm using docker (or more specific docker-compose) I'm using `docker-compose up -d`

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

I've tried 2 different approaches, once with shorthand syntax and one with json syntax, both got the same unexpected Output:

```sh
aws --endpoint-url=http://localhost:4566 es create-elasticsearch-domain --domain-name mylogs-2 --elasticsearch-version 7.10 --elasticsearch-cluster-config '{ "InstanceType": "m3.xlarge.elasticsearch", "InstanceCount": 4, "DedicatedMasterEnabled": true, "ZoneAwarenessEnabled": true, "DedicatedMasterType": "m3.xlarge.elasticsearch", "DedicatedMasterCount": 3}'
```

I'm expecting to get `m3.xlarge.elasticsearch` as `InstanceType` and 4 as `InstanceCount` but the output looks like this:

```json
{
    "DomainStatus": {
        "DomainId": "000000000000/mylogs-2",
        "DomainName": "mylogs-2",
        "ARN": "arn:aws:es:us-east-1:000000000000:domain/mylogs-2",
        "Created": true,
        "Deleted": false,
        "Endpoint": "http://localhost:4571",
        "Processing": false,
        "ElasticsearchVersion": "7.10",
        "ElasticsearchClusterConfig": {
            "InstanceType": "m3.medium.elasticsearch",
            "InstanceCount": 1,
            "DedicatedMasterEnabled": true,
            "ZoneAwarenessEnabled": false,
            "DedicatedMasterType": "m3.medium.elasticsearch",
            "DedicatedMasterCount": 1
        },
        "EBSOptions": {
            "EBSEnabled": true,
            "VolumeType": "gp2",
            "VolumeSize": 10,
            "Iops": 0
        },
        "CognitoOptions": {
            "Enabled": false
        }
    }
}
```

What I get is `m3.medium.elasticsearch` as `InstanceType` instead of `m3.xlarge.elasticsearch`  and 1 as `InstanceCount` instead of 4.

I've used the json syntax as well:
```sh
aws es create-elasticsearch-domain --domain-name mylogs-1 --elasticsearch-version 7.10 --elasticsearch-cluster-config InstanceType=r6g.large.elasticsearch,InstanceCount=6 --endpoint-url=http://localhost:4566
```

but got the same result. :/

**Comment by mgagliardo** [comment]
Hello @Dgame, the config is hardcoded for elasticsearch, I will add this to our pipeline and get back to you with a fix. Cheers.

**Comment by Dgame** [comment]
@mgagliardo Ah thanks, that's good to know but a pity to hear. We were going to use localstack for our local development but we need to be able to configure it.

**Comment by Dgame** [comment]
Thanks @mgagliardo for the quick work, I really appreciate it. :)

**Comment by Dgame** [comment]
@mgagliardo I've tried your change and it works as in I get the right output after executing 
```sh
aws --endpoint-url=http://localhost:4566 es create-elasticsearch-domain --domain-name mylogs --elasticsearch-version 7.10 --elasticsearch-cluster-config '{ "InstanceType": "m3.xlarge.elasticsearch", "InstanceCount": 4, "DedicatedMasterEnabled": true, "ZoneAwarenessEnabled": true, "DedicatedMasterType": "m3.xlarge.elasticsearch", "DedicatedMasterCount": 3}'
```

but if I visit http://localhost:4571/_cat/nodes?v I just get
```
ip        heap.percent ram.percent cpu load_1m load_5m load_15m node.role master name
127.0.0.1           35           0  -1    0.02    1.56     4.86 dimrt     *      cf94a821bb89
```

and if I visit http://localhost:4571/_cluster/health I get
```json
{"cluster_name":"elasticsearch","status":"green","timed_out":false,"number_of_nodes":1,"number_of_data_nodes":1,"active_primary_shards":0,"active_shards":0,"relocating_shards":0,"initializing_shards":0,"unassigned_shards":0,"delayed_unassigned_shards":0,"number_of_pending_tasks":0,"number_of_in_flight_fetch":0,"task_max_waiting_in_queue_millis":0,"active_shards_percent_as_number":100.0}
```

Is it me or am I somehow not getting the right number of nodes 🤔

**Comment by mgagliardo** [comment]
Hello @Dgame, so those are 2 different things.
Localstack is just an interface to some mock'd and/or real services (like kafka, ES) and not a realistic service per-se.
In this case you are asking for the ES AWS interface to create X amount of instances, size, etc. With that you will get the response with an AWS format needed.
On the other hand, bringing up an actual elasticsearch cluster that size locally is not only expensive (resources are limited), that is why we are bringing up a single-noded cluster, even if you ask for 2 masters-3 nodes.
What you can do as a side solution is to use a custom brought up service cluster (check docs for this) and point localstack to that service backend cluster, this way you can run your own custom cluster and use it if you want. 
Hope this answers your question. Cheers

**Comment by Dgame** [comment]
Ah, I see. Thanks @mgagliardo for the explanation, I thought I had done something wrong. Maybe it should be in the docs (or maybe I just didn't find it).

**Comment by mgagliardo** [comment]
Should be this one:



```<SERVICE>_BACKEND: Custom endpoint URL to use for a specific service, where <SERVICE> is the uppercase service name (currently works for: APIGATEWAY, CLOUDFORMATION, DYNAMODB, ELASTICSEARCH, KINESIS, S3, SNS, SQS). This allows to easily integrate third-party services into LocalStack.```

**Comment by Dgame** [comment]
Wonderful, thank you very much. ❤️ But I actually meant that the docs should say that no matter how many nodes you specify, it will always be a single-node cluster behind the scenes. I was confused by it and have not been able to find anything about it in the docs.

**Comment by Dgame** [comment]
@mgagliardo Before I open yet another issue, a quick question: How should I connect an elasticsearch cluster to localstack when both are in different `docker-compose.yml` files? Normally I would use the same network, but it's suggested that I declare `network_mode: bridge`, which - for some reason - is not compatible with `networks`.
I tried using the same network and it works indeed, but I had to remove `network_mode: bridge`, which kind of bugs me.

I'm sure that a tutorial series would be _really_ helpful (or I'm just too dumb). Maybe I will start something like that sometime, if none of you have the time to do it. :)

**Comment by mgagliardo** [comment]
I think you are a bit mixed up here.
[Network mode](https://docs.docker.com/compose/compose-file/compose-file-v3/#network_mode) is not different than using the `--network` flag for the sake of this example, so you can leave it behind (remove it from the YAML) and just use the same network on both the compose files (if you are using separated YAMLs indeed). One simple thing to mitigate this is creating a network outside the compose context using [docker network create](https://docs.docker.com/engine/reference/commandline/network_create/) and then setting up that same one on both compose YAMLs.

I'll try to add some docs regarding this and setting up a separate kafka environment so y'all can test it out, hope my answer clarifies your doubts. 

Cheers!

**Comment by Dgame** [comment]
> I'll try to add some docs regarding this and setting up a separate kafka environment so y'all can test it out, hope my answer clarifies your doubts.

It does indeed, I guess that means I can start to really work with it now. Thank you very much for your help and patience.

**Comment by mgagliardo** [comment]
Nothing to thank mate, we are here to help. Cheers!
