### ISSUE TITLE
Dimensions not returned in LocalStack 0.12.10

### ISSUE THREAD

**Issue by orpiske** [localstack/localstack#4026]
# Type of request: This is a ...

- [x] bug report
- [ ] feature request

# Detailed description
Recently we upgraded the localstack on our test suite and we noticed that one of our Cloud Watch tests started to fail because the dimensions are not being returned from LocalStack. 

Specifically, we identified this behavior when upgrading from 0.12.9.1 to 0.12.10. 

The AWS client logs don't seem to indicate any reasons about why this is happening. 

## Expected behavior
Dimensions should be returned for metrics. For example, with 0.12.9.1:

`docker run --rm -e SERVICES=cloudwatch -it -p 4566:4566 -p 4571:4571 localstack/localstack:0.12.9.1`

```
aws --endpoint-url=http://localhost:4566 cloudwatch put-metric-data --namespace a --metric-data "MetricName=test1,Dimensions=[{Name=dimension1,Value=value1}]" && aws --endpoint-url=http://localhost:4566 cloudwatch list-metrics
{
    "Metrics": [
        {
            "Namespace": "a",
            "MetricName": "test1",
            "Dimensions": [
                {
                    "Name": "dimension1",
                    "Value": "value1"
                }
            ]
        }
    ]
}
```

...

## Actual behavior
What we experience successive calls to [Metric::dimensions](https://javadoc.io/doc/software.amazon.awssdk/cloudwatch/latest/software/amazon/awssdk/services/cloudwatch/model/Metric.html#dimensions--) produce no results (whereas they do with 0.12.9.1).

# Steps to reproduce
Run LocalStack 0.12.10: 

```docker run --rm -e SERVICES=cloudwatch -it -p 4566:4566 -p 4571:4571 localstack/localstack:0.12.10```

Put the metrics and list them:
```
aws --endpoint-url=http://localhost:4566 cloudwatch put-metric-data --namespace a --metric-data "MetricName=test1,Dimensions=[{Name=dimension1,Value=value1}]" && aws --endpoint-url=http://localhost:4566 cloudwatch list-metrics

{
    "Metrics": [
        {
            "Namespace": "a",
            "MetricName": "test1",
            "Dimensions": []
        }
    ]
}
```

## Command used to start LocalStack
`docker run --rm -e SERVICES=cloudwatch -it -p 4566:4566 -p 4571:4571 localstack/localstack:0.12.10`

**Comment by whummer** [comment]
Thanks for reporting @orpiske . This should be fixed in the meantime - can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists. Thanks!

**Comment by orpiske** [comment]
@whummer  Thanks for such a quick fix! I have just trying with the latest and it work as expected (manually as well as on our test suite):

`docker run --rm -e SERVICES=cloudwatch -it -p 4566:4566 -p 4571:4571 localstack/localstack:latest` 

```
{               
    "Metrics": [
        {                    
            "Namespace": "a",     
            "MetricName": "test1",
            "Dimensions": [
                {                        
                    "Name": "dimension1",
                    "Value": "value1"
                }
            ]
        }
    ]
} 

```
