### ISSUE TITLE
Cloudwatch get-metric-statistics

### ISSUE THREAD

**Issue by ZeroInputCtrl** [localstack/localstack#4027]
# Type of request: This is a ...

[+] bug report (may just not be implemented yet? Appears similar to https://github.com/localstack/localstack/issues/2300)
[ ] feature request

# Detailed description
When calling `get-metric-statistics` a 500 is returned</br>
This was tested with ruby aws sdk and awslocal with the same error

## Expected behavior
Expect a json return akin to the output here https://docs.aws.amazon.com/cli/latest/reference/cloudwatch/get-metric-statistics.html#examples

## Actual behavior

```
Unable to parse response (syntax error: line 1, column 54), invalid XML received. Further retries may succeed:
b'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">\n<title>500 Internal Server Error</title>\n<h1>Internal Server Error</h1>\n<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>\n'
```

# Steps to reproduce

## Command used to start LocalStack
docker-compose up, no extra configuration, commands ran locally on docker container itself

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

```sh
awslocal cloudwatch put-metric-data --namespace test --metric-data '[{ "MetricName": "metric", "Dimensions":[{ "Name": "Jobs", "Value": "blarg_local" }], "Value": 2, "Unit": "Count" }]'
awslocal cloudwatch get-metric-statistics --namespace test --metric-name metric --dimensions Name=Jobs,Value=blarg_local --start-time 2021-05-14T13:00:00Z --end-time 2021-05-14T13:56:00Z --period 1 --statistics sum --unit count
```

**Comment by usmangani1** [comment]
@ZeroInputCtrl  Thanks for reporting the issue. This functionality does not seem to be implemented yet. We will comeback to you with a fix.Cheers

**Comment by whummer** [comment]
Thanks @ZeroInputCtrl @usmangani1 . This has been fixed and released in the meantime - can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists. Thanks!
