### ISSUE TITLE
LocalStack CloudWatch Logs For SNS Topic

### ISSUE THREAD

**Issue by Blind-Striker** [localstack/localstack#4036]
## Type of request: This is a kind of question, I'm not sure if the current state of Localstack is supporting CloudWatch logs for SNS

[ ] bug report
[X] feature request (if it's not supported yet)

# Detailed description

We're developing a simple API that gets events from various clients. Basically, what it does is, gets the event, validates it, and then publish it to an SNS topic. 

The whole purpose of this API is to get some specific domain events and publish them to SNS. So the IaC scripts contain only the creation of SNS topics. Creating the SNS subscriptions is not a part nor the responsibility of this project. 

Our stack is .NET and we have used AWS.NET CDK to deploy the SNS topic to LocalStack. While we writing our integration tests, we have realized that even if we could publish our events to an SNS Topic successfully in LocalStack, we haven't seen any CloudWatch logs.

We used both AWS CLI and AWS CloudWatch SDK to query logs but there weren't any log groups or logs created by SNS.

## Expected behavior

We should be able to see some CloudWatch logs for our SNS topic.

## Actual behavior

We couldn't see any logs that related to our SNS topic.

# Steps to reproduce

## Command used to start LocalStack

We have used dotnet test containers to start LocalStack

```csharp
  ITestcontainersBuilder<TestcontainersContainer> localStackBuilder =
      new TestcontainersBuilder<TestcontainersContainer>()
          .WithName($"LocalStack-0.12.6-{DateTime.Now.Ticks}")
          .WithImage("localstack/localstack:0.12.6")
          .WithMount("/var/run/docker.sock", "/var/run/docker.sock")
          .WithCleanUp(true)
          .WithEnvironment("DEFAULT_REGION", "eu-central-1")
          .WithEnvironment("DATA_DIR", "/tmp/localstack/data")
          .WithEnvironment("SERVICES", "iam,s3,sns,cloudformation,cloudwatch,logs,sts")
          .WithEnvironment("DOCKER_HOST", "unix:///var/run/docker.sock")
          .WithEnvironment("LS_LOG", "debug")
          .WithEnvironment("DOCKER_GATEWAY_HOST", "172.17.0.1")
          .WithPortBinding(4566, 4566);
```

### With CLI
```
awslocal logs describe-log-groups --region eu-central-1
```

### With SDK
```csharp
  var amazonCloudWatch = ServiceProvider.GetRequiredService<IAmazonCloudWatchLogs>();

  DescribeLogGroupsResponse describeLogGroupsResponse = await amazonCloudWatch.DescribeLogGroupsAsync();

  foreach (LogGroup logGroup in describeLogGroupsResponse.LogGroups)
  {
      var describeLogStreamsRequest = new DescribeLogStreamsRequest() {LogGroupName = logGroup.LogGroupName};

      var describeLogStreamsResult = await amazonCloudWatch.DescribeLogStreamsAsync(describeLogStreamsRequest);

      foreach (var stream in describeLogStreamsResult.LogStreams)
      {
          var eventsRequest = new GetLogEventsRequest()
          {
              LogStreamName = stream.LogStreamName,
              LogGroupName = describeLogStreamsRequest.LogGroupName
          }; 
          var result = await amazonCloudWatch.GetLogEventsAsync(eventsRequest);
          
          foreach (var events in result.Events)
          {
              _testOutputHelper.WriteLine(events.Timestamp + "  - " +  events.Message );
          }
      }
  }
```

**Comment by pinzon** [comment]
The feature has been merged.
Thanks for using Localstack.

**Comment by Blind-Striker** [comment]
> The feature has been merged. Thanks for using Localstack.

Hey, @pinzon very glad to hear that. Thank you for your effort!
