### ISSUE TITLE
Unable to download file by presigned link (STS)

### ISSUE THREAD

**Issue by nikoncode** [localstack/localstack#4047]
# Type of request: This is a ...

[X] bug report
[ ] feature request

# Detailed description

I see that it's required to use test/test key auth to be able to download file by signed url and it's working, but how to deal with STS credentials providers? If I authorize through STS all operations working perfectly, except access to signed URL.

**Comment by naspeh** [comment]
Hi @nikoncode,

You can specify `S3_SKIP_SIGNATURE_VALIDATION=1` and presigned URL with STS credentials should work in this case.
