### ISSUE TITLE
Wrong suffix in Secret manager

### ISSUE THREAD

**Issue by ioannisGiak89** [localstack/localstack#4055]
# Type of request: This is a ...

[x ] bug report
[ ] feature request

# Detailed description

When you create a secret using aws-sdk the ARN that is provided is not the same with the one that would be provided by AWS.

More specific the ARN that is provided is missing one character from the suffix. 

Then in  cdkLocal when you call  `Secret.fromSecretCompleteArm()` and you pass the ARN you expect to get the secret. However it errors with `secretCompleteArn does not appear to be complete; missing 6-character suffix`

## Expected behavior

When you create the secret the ARN should have a 6 character suffix

## Actual behavior

The ARN has 5 characters

# Steps to reproduce

## Command used to start LocalStack

Start localStack using docker compose

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

```
const AWS = require('aws-sdk');

const secretsManager = new AWS.SecretsManager({
    apiVersion: '2017-10-17',
    accessKeyId: 'a',
    secretAccessKey: 'b',
    region: 'eu-west-1',
    endpoint: 'http://localhost:4566',
});

const {ARN, Name}= await secretsManager
  .createSecret({
     Name: 'TestSecret',
     SecretString: JSON.stringify({
        password: 'pass'
     })
  })
  .promise();

console.log(ARN);
console.log(Name);
```

**Comment by ioannisGiak89** [comment]
Thanks @usmangani1 for updating this one. Do you know when are you going to release this fix?

**Comment by usmangani1** [comment]
@ioannisGiak89  This change is already merged. Can you please pull the latest version of localstack and give it a try ?
Please let us know in case if you face any issues.

**Comment by ioannisGiak89** [comment]
Yes that works on latest thanks. Our docker compose was on locked `0.12.10`
