### ISSUE TITLE
Pre-signed s3 PUT request CORS error still present in 0.12.7 after being marked as fixed in 0.11.2 #2564

### ISSUE THREAD

**Issue by steowens** [localstack/localstack#4056]
# Type of request: This is a ...

[ X] bug report
[ ] feature request

# Detailed description
After installing localstackversion 0.12.7  I get a CORS error "No 'Access-Control-Allow-Origin' header is present on the requested resource" when trying to upload a file from a web browser to localstack s3 with a pre-signed PUT request. This behavior was marked as fixed in issue #2564 but apparently this is not the case.
...

## Expected behavior
The file should be uploaded to localstack s3 with no CORS error from the browser.
...

## Actual behavior
[Error] Failed to load resource: Origin http://localhost:3000 is not allowed by Access-Control-Allow-Origin. (risk-matrix.png, line 0)
...

# Steps to reproduce
The following curl was taken from developer tools on safari where the request failed.

curl 'http://localhost:4566/kmaas-local-fileshares/ea3ce40c-477d-11e3-80ea-7d49c594634a/risk-matrix.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20210520T185937Z&X-Amz-SignedHeaders=host&X-Amz-Expires=600&X-Amz-Credential=test%2F20210520%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=daad08a966cc9a0177c1c854f90b6714bf9461e2b65e0c887c5dcd76f04857e8' \
-X 'PUT' \
-H 'Content-Type: application/octet-stream' \
-H 'Origin: http://localhost:3000' \
-H 'Accept: */*' \
-H 'Referer: http://localhost:3000/' \
-H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.2 Safari/605.1.15'

## Command used to start LocalStack
localstack start
...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
    putFileS3 = (s3PutUrl, file) => {
		return new Promise(function(resolve, reject) {
				if(!s3PutUrl){
					reject(new Error("Null argument s3PutUrl"));
					return;
				}
				if(!file){
					reject(new Error("Null argument file."));
					return;
				}			
				let XHR = new XMLHttpRequest();
				
			    XHR.onerror = function (err) {
			      reject(err);
			      return;
			    };
				
				console.log("putFileS3, request header set");
			    XHR.onreadystatechange = function () {
			        if (XHR.readyState === XMLHttpRequest.DONE) {
			        	if(XHR.status > 299){
			            	reject(new Error("Call to " + s3PutUrl + " returns error with status: " + XHR.status + "; " + XHR.responseText));
		                } else {
		                	resolve({
			                	message: "Upload to S3 returns HTTP Status: " + XHR.status,
			                	s3ResponseBody: XHR.responseText
			                });
		                }
			        } 
			    };
			    try {
			    	XHR.open('PUT', s3PutUrl, true);
			    	XHR.setRequestHeader('Content-Type', 'application/octet-stream');
			    	XHR.send(file);
			    } catch(err) {
			    	console.error("File send failed. " + err.message);
			    	throw err;
			    }
			    
			});
	}
...

**Comment by steowens** [comment]
Attaching a project to enable the reproduction of the issue.  This project is a spring boot project and a web page.  The project requires the following infrastructure on the host:

Java 11
Python 2 - or some way to host the web page
Maven 2 or 3 - to build the project
Localstack - obviously

[DemoCorsBugLocalStackS3.zip](https://github.com/localstack/localstack/files/6541304/DemoCorsBugLocalStackS3.zip)

The README.md file tells you how to set everything up.

**Comment by steowens** [comment]
Attached is a HAR file of the transaction captured by FireFox
{
  "log": {
    "version": "1.2",
    "creator": {
      "name": "Firefox",
      "version": "81.0.2"
    },
    "browser": {
      "name": "Firefox",
      "version": "81.0.2"
    },
    "pages": [
      {
        "startedDateTime": "2021-05-25T11:05:57.860-07:00",
        "id": "page_1",
        "title": "Upload File",
        "pageTimings": {
          "onContentLoad": -243273,
          "onLoad": -242960
        }
      }
    ],
    "entries": [
    /// This is the preflight request to the spring boot application
      {
        "pageref": "page_1",
        "startedDateTime": "2021-05-25T11:05:57.860-07:00",
        "request": {
          "bodySize": 0,
          "method": "OPTIONS",
          "url": "http://localhost:7777/api/prepares3url?userId=ssss",
          "httpVersion": "HTTP/1.1",
          "headers": [
            {
              "name": "Host",
              "value": "localhost:7777"
            },
            {
              "name": "User-Agent",
              "value": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:81.0) Gecko/20100101 Firefox/81.0"
            },
            {
              "name": "Accept",
              "value": "*/*"
            },
            {
              "name": "Accept-Language",
              "value": "en-US,en;q=0.5"
            },
            {
              "name": "Accept-Encoding",
              "value": "gzip, deflate"
            },
            {
              "name": "Access-Control-Request-Method",
              "value": "POST"
            },
            {
              "name": "Access-Control-Request-Headers",
              "value": "authorization,content-type"
            },
            {
              "name": "Origin",
              "value": "http://localhost:7778"
            },
            {
              "name": "DNT",
              "value": "1"
            },
            {
              "name": "Connection",
              "value": "keep-alive"
            }
          ],
          "cookies": [],
          "queryString": [
            {
              "name": "userId",
              "value": "ssss"
            }
          ],
          "headersSize": 406
        },
/// This is the preflight response from the spring boot application
        "response": {
          "status": 200,
          "statusText": "",
          "httpVersion": "HTTP/1.1",
          "headers": [
            {
              "name": "Access-Control-Allow-Origin",
              "value": "http://localhost:7778"
            },
            {
              "name": "Access-Control-Allow-Methods",
              "value": "POST, GET, OPTIONS, DELETE"
            },
            {
              "name": "Access-Control-Allow-Headers",
              "value": "Content-Type, x-requested-with, Authorization"
            },
            {
              "name": "Access-Control-Max-Age",
              "value": "30"
            },
            {
              "name": "Access-Control-Expose-Headers",
              "value": "Content-Disposition"
            },
            {
              "name": "Content-Length",
              "value": "0"
            },
            {
              "name": "Date",
              "value": "Tue, 25 May 2021 18:05:57 GMT"
            },
            {
              "name": "Keep-Alive",
              "value": "timeout=60"
            },
            {
              "name": "Connection",
              "value": "keep-alive"
            }
          ],
          "cookies": [],
          "content": {
            "mimeType": "text/plain",
            "size": 0,
            "text": ""
          },
          "redirectURL": "",
          "headersSize": 388,
          "bodySize": 388
        },
        "cache": {},
        "timings": {
          "blocked": 1,
          "dns": 0,
          "connect": 1,
          "ssl": 0,
          "send": 0,
          "wait": 2,
          "receive": 0
        },
        "time": 4,
        "_securityState": "insecure",
        "serverIPAddress": "127.0.0.1",
        "connection": "7777"
      },
/// This is the post to the spring boot application
      {
        "pageref": "page_1",
        "startedDateTime": "2021-05-25T11:05:57.876-07:00",
        "request": {
          "bodySize": 142,
          "method": "POST",
          "url": "http://localhost:7777/api/prepares3url?userId=ssss",
          "httpVersion": "HTTP/1.1",
          "headers": [
            {
              "name": "Host",
              "value": "localhost:7777"
            },
            {
              "name": "User-Agent",
              "value": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:81.0) Gecko/20100101 Firefox/81.0"
            },
            {
              "name": "Accept",
              "value": "*/*"
            },
            {
              "name": "Accept-Language",
              "value": "en-US,en;q=0.5"
            },
            {
              "name": "Accept-Encoding",
              "value": "gzip, deflate"
            },
            {
              "name": "Authorization",
              "value": "BEARER xyz123"
            },
            {
              "name": "Content-Type",
              "value": "application/json"
            },
            {
              "name": "Content-Length",
              "value": "142"
            },
            {
              "name": "Origin",
              "value": "http://localhost:7778"
            },
            {
              "name": "DNT",
              "value": "1"
            },
            {
              "name": "Connection",
              "value": "keep-alive"
            }
          ],
          "cookies": [],
          "queryString": [
            {
              "name": "userId",
              "value": "ssss"
            }
          ],
          "headersSize": 389,
          "postData": {
            "mimeType": "application/json",
            "params": [],
            "text": "{\"operation\":\"put_object\",\"target\":{\"type\":\"user\",\"userId\":\"ssss\"},\"fileName\":\"risk-matrix.png\",\"encryptionKey\":null,\"encryptionKeyHash\":null}"
          }
        },
// This is the response back from the spring boot application
        "response": {
          "status": 200,
          "statusText": "",
          "httpVersion": "HTTP/1.1",
          "headers": [
            {
              "name": "Access-Control-Allow-Origin",
              "value": "http://localhost:7778"
            },
            {
              "name": "Access-Control-Expose-Headers",
              "value": "Content-Disposition"
            },
            {
              "name": "Content-Type",
              "value": "application/json"
            },
            {
              "name": "Transfer-Encoding",
              "value": "chunked"
            },
            {
              "name": "Date",
              "value": "Tue, 25 May 2021 18:05:57 GMT"
            },
            {
              "name": "Keep-Alive",
              "value": "timeout=60"
            },
            {
              "name": "Connection",
              "value": "keep-alive"
            }
          ],
          "cookies": [],
          "content": {
            "mimeType": "application/json",
            "size": 413,
            "text": "{\"s3PutUrl\":\"http://localhost:4566/buggybugbug/inbox/ssss/risk-matrix.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20210525T180557Z&X-Amz-SignedHeaders=host&X-Amz-Expires=600&X-Amz-Credential=test%2F20210525%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=dcd83d251c9adae144026270258ed432605af336d6a664dfb8316a46514b1c9c\",\"message\":\"Internal error, unsupported folder type\",\"resultCode\":200,\"result\":\"SUCCESS\"}"
          },
          "redirectURL": "",
          "headersSize": 266,
          "bodySize": 679
        },
        "cache": {},
        "timings": {
          "blocked": -1,
          "dns": 1,
          "connect": 1,
          "ssl": 0,
          "send": 0,
          "wait": 5,
          "receive": 1
        },
        "time": 7,
        "_securityState": "insecure",
        "serverIPAddress": "127.0.0.1",
        "connection": "7777"
      },

Here is the Preflight request to Localhost
      {
        "pageref": "page_1",
        "startedDateTime": "2021-05-25T11:05:57.887-07:00",
        "request": {
          "bodySize": 0,
          "method": "OPTIONS",
          "url": "http://localhost:4566/buggybugbug/inbox/ssss/risk-matrix.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20210525T180557Z&X-Amz-SignedHeaders=host&X-Amz-Expires=600&X-Amz-Credential=test%2F20210525%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=dcd83d251c9adae144026270258ed432605af336d6a664dfb8316a46514b1c9c",
          "httpVersion": "HTTP/1.1",
          "headers": [
            {
              "name": "Host",
              "value": "localhost:4566"
            },
            {
              "name": "User-Agent",
              "value": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:81.0) Gecko/20100101 Firefox/81.0"
            },
            {
              "name": "Accept",
              "value": "*/*"
            },
            {
              "name": "Accept-Language",
              "value": "en-US,en;q=0.5"
            },
            {
              "name": "Accept-Encoding",
              "value": "gzip, deflate"
            },
            {
              "name": "Access-Control-Request-Method",
              "value": "PUT"
            },
            {
              "name": "Access-Control-Request-Headers",
              "value": "content-type"
            },
            {
              "name": "Origin",
              "value": "http://localhost:7778"
            },
            {
              "name": "DNT",
              "value": "1"
            },
            {
              "name": "Connection",
              "value": "keep-alive"
            }
          ],
          "cookies": [],
          "queryString": [
            {
              "name": "X-Amz-Algorithm",
              "value": "AWS4-HMAC-SHA256"
            },
            {
              "name": "X-Amz-Date",
              "value": "20210525T180557Z"
            },
            {
              "name": "X-Amz-SignedHeaders",
              "value": "host"
            },
            {
              "name": "X-Amz-Expires",
              "value": "600"
            },
            {
              "name": "X-Amz-Credential",
              "value": "test/20210525/us-east-1/s3/aws4_request"
            },
            {
              "name": "X-Amz-Signature",
              "value": "dcd83d251c9adae144026270258ed432605af336d6a664dfb8316a46514b1c9c"
            }
          ],
          "headersSize": 651
        },
// Here is the response back from Localhost for the preflight request note that * is provided in the access-control-allow-origin header rather than http://localhost:7778
        "response": {
          "status": 200,
          "statusText": "",
          "httpVersion": "HTTP/1.1",
          "headers": [
            {
              "name": "content-type",
              "value": "text/html; charset=utf-8"
            },
            {
              "name": "content-length",
              "value": "0"
            },
            {
              "name": "access-control-allow-origin",
              "value": "*"
            },
            {
              "name": "access-control-allow-methods",
              "value": "HEAD,GET,PUT,POST,DELETE,OPTIONS,PATCH"
            },
            {
              "name": "access-control-allow-headers",
              "value": "authorization,content-type,content-length,content-md5,cache-control,x-amz-content-sha256,x-amz-date,x-amz-security-token,x-amz-user-agent,x-amz-target,x-amz-acl,x-amz-version-id,x-localstack-target,x-amz-tagging"
            },
            {
              "name": "access-control-expose-headers",
              "value": "x-amz-version-id"
            },
            {
              "name": "connection",
              "value": "close"
            },
            {
              "name": "date",
              "value": "Tue, 25 May 2021 18:05:58 GMT"
            },
            {
              "name": "server",
              "value": "hypercorn-h11"
            }
          ],
          "cookies": [],
          "content": {
            "mimeType": "text/html; charset=utf-8",
            "size": 0,
            "text": ""
          },
          "redirectURL": "",
          "headersSize": 549,
          "bodySize": 549
        },
        "cache": {},
        "timings": {
          "blocked": 1,
          "dns": 0,
          "connect": 1,
          "ssl": 0,
          "send": 0,
          "wait": 1026,
          "receive": 0
        },
        "time": 1028,
        "_securityState": "insecure",
        "serverIPAddress": "127.0.0.1",
        "connection": "4566"
      },
// Here is the put request to Localhost.  Note the HAR file shows a response code of 500.  But this is misleading see console error in next comment below
      {
        "pageref": "page_1",
        "startedDateTime": "2021-05-25T11:05:58.917-07:00",
        "request": {
          "bodySize": 0,
          "method": "PUT",
          "url": "http://localhost:4566/buggybugbug/inbox/ssss/risk-matrix.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20210525T180557Z&X-Amz-SignedHeaders=host&X-Amz-Expires=600&X-Amz-Credential=test%2F20210525%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=dcd83d251c9adae144026270258ed432605af336d6a664dfb8316a46514b1c9c",
          "httpVersion": "HTTP/1.1",
          "headers": [
            {
              "name": "Host",
              "value": "localhost:4566"
            },
            {
              "name": "User-Agent",
              "value": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:81.0) Gecko/20100101 Firefox/81.0"
            },
            {
              "name": "Accept",
              "value": "*/*"
            },
            {
              "name": "Accept-Language",
              "value": "en-US,en;q=0.5"
            },
            {
              "name": "Accept-Encoding",
              "value": "gzip, deflate"
            },
            {
              "name": "Content-Type",
              "value": "application/octet-stream"
            },
            {
              "name": "Content-Length",
              "value": "34596"
            },
            {
              "name": "Origin",
              "value": "http://localhost:7778"
            },
            {
              "name": "DNT",
              "value": "1"
            },
            {
              "name": "Connection",
              "value": "keep-alive"
            }
          ],
          "cookies": [],
          "queryString": [
            {
              "name": "X-Amz-Algorithm",
              "value": "AWS4-HMAC-SHA256"
            },
            {
              "name": "X-Amz-Date",
              "value": "20210525T180557Z"
            },
            {
              "name": "X-Amz-SignedHeaders",
              "value": "host"
            },
            {
              "name": "X-Amz-Expires",
              "value": "600"
            },
            {
              "name": "X-Amz-Credential",
              "value": "test/20210525/us-east-1/s3/aws4_request"
            },
            {
              "name": "X-Amz-Signature",
              "value": "dcd83d251c9adae144026270258ed432605af336d6a664dfb8316a46514b1c9c"
            }
          ],
          "headersSize": 628
        },
        "response": {
          "status": 500,
          "statusText": "",
          "httpVersion": "HTTP/1.1",
          "headers": [
            {
              "name": "content-type",
              "value": "text/html; charset=utf-8"
            },
            {
              "name": "content-length",
              "value": "2"
            },
            {
              "name": "date",
              "value": "Tue, 25 May 2021 18:05:58 GMT"
            },
            {
              "name": "server",
              "value": "hypercorn-h11"
            }
          ],
          "cookies": [],
          "content": {
            "mimeType": "text/html; charset=utf-8",
            "size": 2,
            "text": "{}"
          },
          "redirectURL": "",
          "headersSize": 136,
          "bodySize": 138
        },
        "cache": {},
        "timings": {
          "blocked": -1,
          "dns": 0,
          "connect": 1,
          "ssl": 0,
          "send": 0,
          "wait": 12,
          "receive": 0
        },
        "time": 12,
        "_securityState": "insecure",
        "serverIPAddress": "127.0.0.1",
        "connection": "4566"
      }
    ]
  }
}

**Comment by steowens** [comment]
Console error:  Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:4566/buggybugbug/inbox/ssss/risk-matrix.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20210525T180557Z&X-Amz-SignedHeaders=host&X-Amz-Expires=600&X-Amz-Credential=test%2F20210525%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=dcd83d251c9adae144026270258ed432605af336d6a664dfb8316a46514b1c9c. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

**Comment by steowens** [comment]
When I look at the Localstack container logs I can see that internally the following is happening, and I don't know why but that is a separate issue which if you could maybe give me a clue on I would be most appreciative of the advice:
2021-05-24T20:12:04:WARNING:localstack.utils.server.http2_server: Error in proxy handler for request PUT http://localhost:4566/buggybugbug/inbox/steve/risk-matrix.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20210524T201204Z&X-Amz-SignedHeaders=host&X-Amz-Expires=600&X-Amz-Credential=test%2F20210524%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=4a000245480626029a804e083220d337d1f9707b795aeafe2ec8a1af699a9f0a: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte Traceback (most recent call last):
  File "/opt/code/localstack/localstack/utils/server/http2_server.py", line 129, in index
    raise result
  File "/opt/code/localstack/localstack/utils/bootstrap.py", line 671, in run
    result = self.func(self.params)
  File "/opt/code/localstack/localstack/utils/async_utils.py", line 28, in _run
    return fn(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 607, in handler
    response = modify_and_forward(method=method, path=path_with_params, data_bytes=data, headers=headers,
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 373, in modify_and_forward
    listener_result = listener.forward_request(method=method,
  File "/opt/code/localstack/localstack/services/edge.py", line 56, in forward_request
    auth_header = get_auth_string(method, path, headers, data)
  File "/opt/code/localstack/localstack/services/edge.py", line 181, in get_auth_string
    data_components = parse_request_data(method, path, data)
  File "/opt/code/localstack/localstack/utils/common.py", line 833, in parse_request_data
    result = parse_qs(to_str(data or ''))
  File "/opt/code/localstack/localstack/utils/common.py", line 984, in to_str
    return obj.decode(encoding, errors) if isinstance(obj, six.binary_type) else obj
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte

2021-05-25T17:59:13:ERROR:localstack.services.s3.s3_utils: Presign signature calculation failed: <Response [403]>
2021-05-25T17:59:13:WARNING:bootstrap.py: Thread run method <function AdaptiveThreadPool.submit.<locals>._run at 0x7f1e5f03f9d0>(None) failed: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte Traceback (most recent call last):
  File "/opt/code/localstack/localstack/utils/bootstrap.py", line 671, in run
    result = self.func(self.params)
  File "/opt/code/localstack/localstack/utils/async_utils.py", line 28, in _run
    return fn(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 607, in handler
    response = modify_and_forward(method=method, path=path_with_params, data_bytes=data, headers=headers,
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 373, in modify_and_forward
    listener_result = listener.forward_request(method=method,
  File "/opt/code/localstack/localstack/services/edge.py", line 56, in forward_request
    auth_header = get_auth_string(method, path, headers, data)
  File "/opt/code/localstack/localstack/services/edge.py", line 181, in get_auth_string
    data_components = parse_request_data(method, path, data)
  File "/opt/code/localstack/localstack/utils/common.py", line 833, in parse_request_data
    result = parse_qs(to_str(data or ''))
  File "/opt/code/localstack/localstack/utils/common.py", line 984, in to_str
    return obj.decode(encoding, errors) if isinstance(obj, six.binary_type) else obj
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte

**Comment by kellertobias** [comment]
@steowens how did you fix it?

**Comment by steowens** [comment]
> @steowens how did you fix it?

I stopped using local stack and deployed my service to Fargate to run against real S3.   That fixed it.

**Comment by micksatana** [comment]
The problem still exists in `latest` tag (ID: `sha256:3c6af6b372e74cd169ecb6d1492cd06f614bfb985581154ac2c9e62bf4ee63c3`)

**Comment by iamjaredwalters** [comment]
Seeing this problem as well on `latest` and `0.13.2`. Anyone found a resolution?

**Comment by andreleoni** [comment]
I got the same blem in the `latest` version (`LocalStack version: 1.3.2.dev` described on log), and solved with this two variables described in documentation here https://docs.localstack.cloud/references/configuration/#security

```
- DISABLE_CORS_CHECKS=1
- DISABLE_CUSTOM_CORS_S3=1
```
