### ISSUE TITLE
HTTP GET S3 object always returns 403.

### ISSUE THREAD

**Issue by vangorra** [localstack/localstack#406]
Trying to get a file from a S3 bucket always results in a 403. I've set the bucket policy to allow getObject from * but I don't think localstack supports bucket policies anyway.

Here is what I'm running.
```
curl -v http://localstack-core:4572/mybucket/index.html 
> GET /mybucket/index.html HTTP/1.1
> Host: localstack-core:4572
> User-Agent: curl/7.52.1
> Accept: */*
> 
< HTTP/1.1 403 Forbidden
< Server: BaseHTTP/0.3 Python/2.7.13
< Date: Sun, 15 Oct 2017 20:26:20 GMT
< Content-Type: text/html; charset=utf-8
< Content-Length: 0
< Server: Werkzeug/0.12.2 Python/2.7.13
< Date: Sun, 15 Oct 2017 20:26:20 GMT
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Methods: HEAD,GET,PUT,POST,DELETE,OPTIONS,PATCH
< Access-Control-Allow-Headers: authorization,content-type,content-md5,x-amz-content-sha256,x-amz-date,x-amz-security-token,x-amz-user-agent
< 
* Curl_http_done: called premature == 0
* Connection #0 to host localstack-core left intact
```

If I try it on a file that doesn't exist. I correctly get this result:
```
curl -v http://localstack-core:4572/mybucket/index2.html
*   Trying 172.18.0.2...
* TCP_NODELAY set
* Connected to localstack-core (172.18.0.2) port 4572 (#0)
> GET /mybucket/index2.html HTTP/1.1
> Host: localstack-core:4572
> User-Agent: curl/7.52.1
> Accept: */*
> 
< HTTP/1.1 404 Not Found
< Server: BaseHTTP/0.3 Python/2.7.13
< Date: Sun, 15 Oct 2017 20:32:46 GMT
< Content-Type: text/html; charset=utf-8
< Content-Length: 207
< Server: Werkzeug/0.12.2 Python/2.7.13
< Date: Sun, 15 Oct 2017 20:32:46 GMT
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Methods: HEAD,GET,PUT,POST,DELETE,OPTIONS,PATCH
< Access-Control-Allow-Headers: authorization,content-type,content-md5,x-amz-content-sha256,x-amz-date,x-amz-security-token,x-amz-user-agent
< 
<?xml version="1.0" encoding="UTF-8"?>
<Error>
    <Code>NoSuchKey</Code>
    <Message>The specified key does not exist.</Message>
    
    <RequestID>7a62c49f-347e-4fc4-9331-6e8eEXAMPLE</RequestID>
* Curl_http_done: called premature == 0
* Connection #0 to host localstack-core left intact
</Error>
```

I can correctly get a listing of files (including index.html) with the following curl command:
```
curl -v http://localstack-core:4572/mybucket/
```

**Comment by vangorra** [comment]
Something important to note. Using the Node API for getting objects appears to work.

**Comment by kenjinino** [comment]
I was having the same issue @vangorra 
It worked running localstack using docker-compose method, but I had to specify it's docker image to use version 0.8.0 (I don't know if version 0.8.1 is working)
https://hub.docker.com/r/localstack/localstack/tags/ 

* Modified docker-compose.yml
```
version: '2.1'

services:
  localstack:
    image: localstack/localstack:0.8.0
    ports:
      - "4567-4582:4567-4582"
      - "8080:8080"
    environment:
      - SERVICES=${SERVICES- }
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

**Comment by vangorra** [comment]
@kenjinino Thanks. I'm also using docker-compose. I'm using localstack/localstack:latest though.

**Comment by whummer** [comment]
This seems to be an upstream issue in `moto`. 

In order to access a bucket object using `GET`, a bucket ACL for public read needs to be defined:
https://github.com/spulec/moto/blob/master/moto/s3/responses.py#L557-L558

We can set the bucket ACL via the `?acl` query string and using HTTP headers (haven't tested it, but it should work). However, the XML payload based type of request to set bucket ACL is not implemented yet:
https://github.com/spulec/moto/blob/master/moto/s3/responses.py#L376
Which client are you using to create the bucket policy? Does it use the headers based request format for put-bucket-acl, or the XML payload based format?

**Comment by vangorra** [comment]
Hey @whummer, I'm using the node AWS SDK, I'm not sure which method it uses to put the bucket ACL but I'm going to guess it's an XML body. The API docs are not clear. At any rate, I'm not setting any bucket ACLs, rather, I'm creating a bucket policy (see below). It doesn't sound like moto supports bucket policies.

``` json
{
  "Bucket": {
    "Ref": "S3DataBucket"
  },
  "PolicyDocument": {
    "Version": "2012-10-17",
    "Statement": [
      {
        "Action": [
          "s3:GetObject"
        ],
        "Effect": "Allow",
        "Resource": "arn:aws:s3:::myBucket/*",
        "Principal": {
          "AWS": [
            "*"
          ]
        }
      }
    ]
  }
}
```

A possible work around may be to manually put a read policy on the bucket using url args. Rather messy all things considered.

**Comment by whummer** [comment]
Does using the bucket policy work in AWS, though? My understanding is that the policy grants permission to any AWS principal, but if you run a `curl` command with no authentication tokens against a bucket, you are essentially running an anonymous request (and "anonymous" != "any AWS principal" in my understanding). I think that is what ACLs are for. I'm not entirely sure though, I'd have to do more research on that topic. But can you confirm that your example using the policy works on AWS?

**Comment by vangorra** [comment]
The policy in question does work on AWS and does allow public users access. I was successfully able to access files in my bucket via curl and incognito with a url like this: https://myBucket.s3.amazonaws.com/file.txt

According to the following article, bucket ACLs are a legacy feature (presumably for backwards compatibility) and you should really be using bucket or IAM policies. https://aws.amazon.com/blogs/security/iam-policies-and-bucket-policies-and-acls-oh-my-controlling-access-to-s3-resources/

**Comment by GeoffreyBooth** [comment]
I’m running into this issue too.

```coffee
# This DIDN’T work:
s3.putBucketPolicy
    Bucket: 'media'
    Policy: JSON.stringify
      Version: '2012-10-17'
      Statement: [
        Action: ['s3:GetObject']
        Effect: 'Allow'
        Resource: 'arn:aws:s3:::media/*'
        Principal:
          AWS: ['*']
      ]
  , (err, data) ->
    throw err if err
    console.log 'S3 bucket “media” access policy set'

# But this DID work:
s3.putBucketAcl
    Bucket: 'media'
    ACL: 'public-read'
  , (err, data) ->
    throw err if err
    console.log 'S3 bucket “media” access policy set'
```

**Comment by Pickachu** [comment]
any updates on this?

**Comment by ranchoiver** [comment]
Does anybody have a solution for this bug?

**Comment by mcqj** [comment]
@wonder27young aws cli returns an error 
Unknown options: --grants, read=uri=http://acs.amazonaws.com/groups/global/AllUsers

**Comment by ioben** [comment]
This seemed to resolve my issue:
```
awsl s3api put-bucket-acl --bucket test --acl public-read
```
Note, it only works on files created after setting the ACL.

**Comment by LEscobar-Driver** [comment]
Is this problem fixed?? I cannot view any files that I upload using awslocal. I can see the files but I cannot access them?? I am not using docker, just running localstack locally

**Comment by victoruiz** [comment]
Just in case this is related... there's a bug with multipart uploads regarding ACLs https://github.com/localstack/localstack/issues/1170

**Comment by Sripaad** [comment]
Am trying to view the data inside a file which is inside the bucket, this is the error am getting and everywhere i am using the same region.
``` 
wget http://localhost:4572/<bucket-name>/<filename>.json
Warning: Failed to set locale category LC_NUMERIC to en_IN.
Warning: Failed to set locale category LC_TIME to en_IN.
Warning: Failed to set locale category LC_COLLATE to en_IN.
Warning: Failed to set locale category LC_MONETARY to en_IN.
Warning: Failed to set locale category LC_MESSAGES to en_IN.
--2019-07-22 15:33:26--  http://localhost:4572/<bucket-name>/<filename>
Resolving localhost (localhost)... ::1, 127.0.0.1
Connecting to localhost (localhost)|::1|:4572... connected.
HTTP request sent, awaiting response... 403 Forbidden
2019-07-22 15:33:26 ERROR 403: Forbidden.
```

**Comment by arun0009** [comment]
This worked for me:
```
aws  --endpoint-url=http://localhost:4572 s3api create-bucket --bucket arun-dev --region us-east-1
aws --endpoint-url=http://localhost:4572 s3api put-bucket-acl --bucket arun-dev --acl public-read
aws --endpoint-url=http://localhost:4572 s3 cp test.json s3://arun-dev
curl -v http://localhost:4572/arun-dev/test.json
```

**Comment by whummer** [comment]
Looks like this problem is fixed. Please report here or create a follow-up issue if this problem persists. Thanks
