### ISSUE TITLE
POST for Lambda invocation returns malformed content-type

### ISSUE THREAD

**Issue by mummoo** [localstack/localstack#4061]
# Type of request: This is a ...

[X] bug report
[ ] feature request

# Detailed description

When I invoke a python lambda function using the post as follows, the response content-type contains incorrect values "content-type: application/json, application/json" instead of just "content-type: application/json"

POST endpoint:   http://localhost:4566/2015-03-31/functions/my-math-function/invocations

...

## Expected behavior
The response header's content-type should be "application/json" instead of "application/json, application/json"

...

## Actual behavior
curl -i  -X POST http://localhost:4566/2015-03-31/functions/my-math-function/invocations   -d '{"action": "square","number": 3}'
HTTP/1.1 200
**content-type: application/json, application/json**

...

# Steps to reproduce

## Command used to start LocalStack

It can be reproduced using simple set-up. Run localstack (default port of 4566). Using the same set of example in https://docs.aws.amazon.com/lambda/latest/dg/python-package-create.html:

aws --endpoint-url=http://localhost:4566 iam create-role --role-name lambda-ex --assume-role-policy-document '{"Version": "2012-10-17","Statement": [{ "Effect": "Allow", "Principal": {"Service": "lambda.amazonaws.com"}, "Action": "sts:AssumeRole"}]}'

aws --endpoint-url=http://localhost:4566  iam attach-role-policy --role-name lambda-ex --policy-arn arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

aws --endpoint-url=http://localhost:4566 lambda create-function --function-name my-math-function --zip-file fileb://my-deployment-package.zip --handler lambda_function.lambda_handler --runtime python3.8 --role arn:aws:iam::your-account-id:role/lambda-ex

 curl -i -X POST http://localhost:4566/2015-03-31/functions/my-math-function/invocations   -d '{"action": "square","number": 3}'
HTTP/1.1 200
**content-type: application/json, application/json**
content-length: 13
x-amz-log-result:
x-amz-executed-version: $LATEST
access-control-allow-origin: *
access-control-allow-methods: HEAD,GET,PUT,POST,DELETE,OPTIONS,PATCH
access-control-allow-headers: authorization,content-type,content-length,content-md5,cache-control,x-amz-content-sha256,x-amz-date,x-amz-security-token,x-amz-user-agent,x-amz-target,x-amz-acl,x-amz-version-id,x-localstack-target,x-amz-tagging
access-control-expose-headers: x-amz-version-id
connection: close
date: Sun, 23 May 2021 00:04:53 GMT
server: hypercorn-h11

{"result":9}

The "content-type" in the response is incorrect.

...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

...

**Comment by mummoo** [comment]
@KrishnanRanjithkumar  Thanks for looking into this. Is it a localstack issue? any workaround available?

**Comment by whummer** [comment]
Thanks for reporting @mummoo . This should be fixed in #4131 - can you please pull the `latest` Docker image and give it another try? Please report here if the problem persists. Thanks!
