### ISSUE TITLE
A sample working docker-compose.yml file for PRO version on Windows 10.

### ISSUE THREAD

**Issue by nexuschakri** [localstack/localstack#4068]
A sample docker-compose.yml file that works with PRO version on windows 10 should be released on very high priority as invoking lambda functions always fails in PRO version. We are just beating around the bush in vain ...  to make the docker-compose.yml work with the PRO version. No matter what combination of docker startup configuration we set ... it never worked and always throws this error ...

 "errorMessage": "Lambda process returned error status code: 127. Result: . Output:\nWARNING: Localhost DNS setting (--dns=127.0.0.1) may fail in containers.\ndocker: Error response from daemon: OCI runtime create failed: container_linux.go:367: starting container process caused:."

"c:\localstack" can be the example folder containing the "docker-composer.yml". 

# Type of request: This is a ...

[ ] bug report
[ ] feature request

# Detailed description

...

## Expected behavior

...

## Actual behavior

...

# Steps to reproduce

## Command used to start LocalStack

...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

...

**Comment by sjoukedv** [comment]
There is literally a `docker-compose.yml`  file in the [root of the repository](https://github.com/localstack/localstack/blob/master/docker-compose.yml) (also mentioned in the README), but here is my example:

1. make sure `LOCALSTACK_API_KEY` exists in the environment
2. have the docker daemon running

```
version: '3.1'

services: 
  localstack:
    image: localstack/localstack:latest
    # or use fixed version
    # image: localstack/localstack:0.12.1
    hostname: localstack
    environment:
      - EDGE_PORT=4566
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - SERVICES=lambda,s3,secretsmanager,serverless,stepfunctions,iam,apigateway,logs,dynamodb
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY}
      - DEBUG=1
      # optional for debug purposes
      # - LAMBDA_REMOVE_CONTAINERS=false
      - DOCKER_HOST=unix:///var/run/docker.sock
    ports: 
      - '4566-4597:4566-4597'
    volumes: 
      - '${TMPDIR:-/tmp/localstack}:/tmp/localstack'
      - "/var/run/docker.sock:/var/run/docker.sock"
```

Pick one of these [pro examples](https://github.com/localstack/localstack-pro-samples) or [serverless examples](https://github.com/localstack/serverless-examples) and you should be good to go.

**Comment by nexuschakri** [comment]
Tried the above version of docker-compose.yml file but  this time the serverless was not even able to deploy the app. The same serverless deploys the app perfectly in a community edition. only when I set the LOCALSTACK_API_KEY it breaks. 

//////////// docker-compose up debug-msg/////////////
localstack_1  | WARNING: SSL Certificate checking for endpoints has been explicitly disabled.
localstack_1  | May 27, 2021 8:10:09 AM com.amazonaws.http.apache.client.impl.ApacheConnectionManagerFactory createSocketFactoryRegistry
localstack_1  | WARNING: SSL Certificate checking for endpoints has been explicitly disabled.
localstack_1  | May 27, 2021 8:10:09 AM com.amazonaws.internal.DefaultServiceEndpointBuilder getServiceEndpoint
localstack_1  | INFO: {databrew, us-east-1} was not found in region metadata, trying to construct an endpoint using the standard pattern for this region: 'databrew.us-east-1.amazonaws.com'.
localstack_1  | Waiting for all LocalStack services to be ready
localstack_1  | 2021-05-27T08:10:12:INFO:botocore.credentials: Found credentials in environment variables.
localstack_1  | Ready.

//// serverless deploy error /////

C:\localstack>sls deploy --stage local --region us-east-1

Serverless: Skip plugin function Package.packageService (lambda.mountCode flag is enabled)
Serverless: Skip plugin function AwsCompileFunctions.downloadPackageArtifacts (lambda.mountCode flag is enabled)
Serverless: Skip plugin function AwsDeploy.extendedValidate (lambda.mountCode flag is enabled)
Serverless: Creating Stack...
Serverless: Checking Stack create progress...
......
Serverless: Stack create finished...
Serverless: Uploading CloudFormation file to S3...
Serverless: Skip plugin function AwsDeploy.uploadFunctionsAndLayers (lambda.mountCode flag is enabled)
Serverless: Validating template...
Serverless: Skipping template validation: Unsupported in Localstack
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
....
Serverless: Operation failed!
Serverless: View the full error output: https://us-east-1.console.aws.amazon.com/cloudformation/home?region=us-east-1#/stack/detail?stackId=arn%3Aaws%3Acloudformation%3Aus-east-1%3A000000000000%3Astack%2FuploadToS3-local%2Fa96df56b

 Serverless Error ----------------------------------------

  An error occurred: uploadToS3-local - UPDATE_FAILED.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          win32
     Node Version:              14.17.0
     Framework Version:         2.43.0
     Plugin Version:            5.1.3
     SDK Version:               4.2.2
     Components Version:        3.10.0

When I set "- LAMBDA_REMOTE_DOCKER=false" the serverless deploys the app OK but it still throws an error in invoking the lambda function. Very strange because it works perfectly in community version. It is a very simple lambda code that uploads a png file to the bucket thats all.

**Comment by sjoukedv** [comment]
I remember having to set `LAMBDA_REMOTE_DOCKER=false` explicitly for some reason, but the image works fine after that for me.

Does it work OK for invocation of a hello-world lambda (without s3)?

I am using S3 in a layer (same applies to lambda). Specifically regarding s3 I had to make sure I use this endpoint (for NodeJS) `${process.env.LOCALSTACK_HOSTNAME}`  and use `s3ForcePathStyle: true`. Here is a snippet:

```
const AWS = require("aws-sdk");
const AWS_REGION = process.env.AWS_DEFAULT_REGION || 'us-east-1';

// Global AWS SDK configuration
if(process.env.STAGE == "local"){
  AWS.config.update({
    region: AWS_REGION,
    endpoint: `http://${process.env.LOCALSTACK_HOSTNAME}:4566`,
    s3ForcePathStyle: true
  }) 
}
```

Hope this helps

**Comment by schwarz** [comment]
Please give the following `docker-compose.yml` a try:

```
version: "3.8"
services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "443:443"
      - "4566:4566"
      - "4571:4571"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - LOCALSTACK_API_KEY=yourapikey
      - SERVICES=${SERVICES- }
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
    volumes:
      - "${TMPDIR:-./tmpdir}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

Create `C:/localstack/tmpdir` just to be safe. Save the following to `C:/localstack/tmpdir/testlambda.py` and create a zip archive called `testlambda.zip`:

```python
def handler(*args, **kwargs):
  return "OK"
```

Using [awscli-local](https://github.com/localstack/awscli-local):

```
$ cd C:/localstack/tmpdir
$ awslocal.bat lambda create-function --function-name func1 --runtime python3.6 --role r1 --handler testlambda.handler --zip-file fileb://testlambda.zip
$ awslocal.bat lambda get-function --function-name func1
$ awslocal.bat lambda invoke --function-name func1 test.txt
```

`get-function` should return some JSON describing the function and `test.txt` should contain the string `OK`.
