### ISSUE TITLE
S3 request-payment-configuration does not work

### ISSUE THREAD

**Issue by synfinatic** [localstack/localstack#4071]
# Type of request: This is a ...

[ X] bug report
[ ] feature request

# Detailed description

S3 has the [requester pays](https://docs.aws.amazon.com/AmazonS3/latest/userguide/RequesterPaysBuckets.html) feature, but this is not implemented with localstack.

## Expected behavior

Setting "payer: requester" returns this config as part of the get request.  GET/PUT's to S3 bucket requires client to specify `x-amz-request-payer` to work

## Actual behavior

Setting the Payer to requester is a no-op.

# Steps to reproduce

```
aws --endpoint-url http://localhost:56975 s3api put-bucket-request-payment --bucket dev.o19vmb.us-east-1.bucket --request-payment-configuration '{"Payer": "Requestor"}'
aws --endpoint-url http://localhost:56975 s3api get-bucket-request-payment --bucket dev.o19vmb.us-east-1.bucket
```
## Command used to start LocalStack

docker

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

See above

**Comment by macnev2013** [comment]
Thanks for reporting the issue @synfinatic. We have add this feature in #4094.
Can you please pull the `latest` docker image and try again ?

Thanks
