### ISSUE TITLE
Missing queryStringParameters property when parsing Lambda events in a Websockets API

### ISSUE THREAD

**Issue by borjatur** [localstack/localstack#4072]
# Type of request: This is a ...

[ x] bug report
[ ] feature request

# Detailed description
Missing **queryStringParameters** when parsing events in Lambda executions used to built a websockets api service with ApiGateway v2. In our API implementation we use the query string to provide some context at connection time. e.g:

` wscat -c "ws://localhost:4510/sandbox?userId=foo&roomId=testroom"`

In AWS the event contains a queryStringParameters property with the query string already parsed, see the expected behaviour

## Expected behavior
Non relevant fields have been omitted for the sake of clarity.
```
{
    "headers": {...},
    "multiValueHeaders": {...},
    "queryStringParameters": {
        "roomId": "testroom",
        "userId": "foo"
    },
    "multiValueQueryStringParameters": {
        "roomId": [
            "testroom"
        ],
        "userId": [
            "foo"
        ]
    },
    "requestContext": {...},
    "isBase64Encoded": false
}
```

## Actual behavior
See that queryStringParameters is not included, instead the query string is part of **requestContext.path** property.
```
{
  "headers": {...},
  "multiValueHeaders": {...},
  "requestContext": {
    "path": "/sandbox?userId=foo&roomId=testroom",
    "resourcePath": "/",
    "apiId": "51cc2f16",
    "domainPrefix": "51cc2f16",
    "domainName": "51cc2f16.execute-api.localhost.localstack.cloud",
    "accountId": "",
    "resourceId": null,
    "stage": "test",
    "identity": {
      "sourceIp": "127.0.0.1"
    },
    "httpMethod": null,
    "protocol": "HTTP/1.1",
    "requestTime": "2021-05-26T07:28:07.612Z",
    "requestTimeEpoch": 1622014087612,
    "routeKey": "$connect",
    "messageId": null,
    "eventType": "CONNECT",
    "requestId": "d1410e00-dfdc-421b-95e2-69877e077754",
    "connectionId": "4e3ee778"
  },
  "isBase64Encoded": false,
  "body": "{\"action\": \"$connect\"}"
}
```
# Steps to reproduce

Just including query string at connection time, a really quick example which can be used as part of any connection url:

` wscat -c "ws://localhost:4510/sandbox?foo=bar"`

## Command used to start LocalStack

LOCALSTACK_API_KEY=<api_key> DEBUG=1 SERVICES=serverless,apigatewayv2,iam,lambda,s3,dynamodb,cloudformation,sts,apigateway,cloudformation,cloudwatch,dynamodb,ec2,es,elasticache,firehose,kinesis,rds,redshift,route53,secretsmanager,ses,sns,sqs,ssm localstack start

**Comment by whummer** [comment]
Thanks for reporting @borjatur . This should be fixed in the meantime. Can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists. Thanks for your help!
