### ISSUE TITLE
Support ruby2.7 runtime

### ISSUE THREAD

**Issue by sjoukedv** [localstack/localstack#4073]
AWS supports the following Ruby runtimes:

Name | Identifier | SDK for Ruby | Operating system
-- | -- | -- | --
Ruby 2.7 | ruby2.7 | 3.0.1 | Amazon Linux 2
Ruby 2.5 | ruby2.5 | 3.0.1 | Amazon Linux

Currently, `localstack/lambda` only contains the `ruby2.5` tag. Will the 2.7 runtime be supported in the (near) future?

**Comment by sjoukedv** [comment]
In addition to that (taken from [here](https://docs.aws.amazon.com/lambda/latest/dg/runtime-support-policy.html)):


Name | Identifier | Operating system | End of support phase 1 start | End of support phase 2 start
-- | -- | -- | -- | --
Ruby 2.5 | ruby2.5 | Amazon Linux | July 30, 2021 | Aug 30, 2021

**Comment by whummer** [comment]
Thanks for reporting @sjoukedv . This should be fixed in the meantime - can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists. Thanks!
