### ISSUE TITLE
Cognito InitiateAuth ClientMetadata is not passed to Pre Authentication Lambda

### ISSUE THREAD

**Issue by Ron-lab** [localstack/localstack#4074]
# Type of request: This is a ...

[ x] bug report
[ ] feature request

# Detailed description
When sending login request with ClientMetadata, the ClientMetadata is not received by the Pre Authentication Lambda event['request']['validationData'].
 
## Expected behavior
Sending ClientMetadata on the cognito.initiateAuth() request should result in receiving the data in the pre-authenication lambda (when this tigger is applied). The event['request']['validationData'] should contain the ClientMetadata according to [docs]. (https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-pre-authentication.html)

## Actual behavior
The Pre-Authentication Lambda event['request'] field doesn't contain the data:
```
  'request': {
    'userAttributes': {
       //Custom fields are OK
    },
    'validationData': {
      //Client Metadata is missing here
    },
    'clientMetadata': {
      
    }
  }
```

# Steps to reproduce
1. Send login request (javascript aws-sdk): 
`      res = await cognito.initiateAuth({
        ClientId: clientId,
        AuthFlow: 'USER_PASSWORD_AUTH',
        AuthParameters: {
          USERNAME: 'someuser@gmail.com',
          PASSWORD: '1234'
        },
        ClientMetadata: {
          'custumFiled': 'data'
        }
      }).promise();`
2. Check the event['request']['validationData'] - data is missing
## Command used to start LocalStack
Inside docker-compose  use: image: localstack/localstack:latest
...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
See above
...

**Comment by whummer** [comment]
Thanks for reporting @Ron-lab . This should be fixed in the meantime - can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists. Thanks for your help!
