### ISSUE TITLE
Pro - API Gateway v2 WebSockets can't postToConnection from lambda running in LocalStack

### ISSUE THREAD

**Issue by alsper** [localstack/localstack#4090]
# Type of request: This is a ...

[X ] bug report
[ ] feature request

# Detailed description

It seems impossible to send messages to API Gateway Management Connections from lambda functions orchestrated by LocalStack. It seems there is a lack of clear documentation on how to set up the DNS so these lambda containers can correctly resolve `*.execute-api.localhost.localstack.cloud` domains to the correct LocalStack service.

The following is the error that is returned when trying to use the API Gateway Management SDK Client for Node.js.

```
 2021-06-01T18:02:37.758Z c81acc53-9cde-1539-e3e4-324843a4eb1b ERROR Error: connect ECONNREFUSED 1127.0.0.1:443

> at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {

> errno: 'ECONNREFUSED',

> code: 'NetworkingError',

> syscall: 'connect',

> address: '127.0.0.1',

> port: 443,

> region: 'eu-west-2',

> hostname: 'cc4985c2.execute-api.localhost.localstack.cloud',

> retryable: true,

> time: 2021-06-01T18:02:37.757Z

> }
```

## Expected behavior

It should correctly send messages to the LocalStack endpoint for the API Gateway v2 endpoint for an API Gateway v2 Resource deployed to LocalStack.

## Actual behavior

Network connection refused error with the LocalStack lambda container trying to resolve `*.execute-api.localhost.localstack.cloud` to `127.0.0.1` which produces a .

# Steps to reproduce

- Create and deploy an API Gateway v2 stack to LocalStack with some route integrations and lambdas hooked up.
- Write code to send messages back to the client in the lambda via the API Gateway Management client in the AWS SDK.
- Test connecting to the WebSocket server/send a message to trigger the lambda on the route integration that sends messages to the WebSocket connection to be consumed by the client.

## Command used to start LocalStack

Docker compose stack
```
version: '3.1'

services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - '4566:4566'
      - '4510:4510'
    networks:
      default:
        aliases:
          - localhost.localstack.cloud
          - s3.localhost.localstack.cloud
    environment:
      HOSTNAME: localhost
      LOCALSTACK_API_KEY: '${LOCALSTACK_API_KEY}'
      SERVICES: 'lambda,secretsmanager,s3,dynamodb,cloudformation,iam,apigateway'
      # Use a docker lambda executor so we can run nodejs lambdas in LocalStack in addition to python lambdas.
      LAMBDA_EXECUTOR: 'docker-reuse'
      # Ensure we mount the lambda code from the host instead of uploading to a local S3 bucket.
      LAMBDA_REMOTE_DOCKER: 'false'
      HOST_TMP_FOLDER: '${PWD}'
      DOCKER_HOST: 'unix:///var/run/docker.sock'
      DNS_RESOLVE_IP: '172.17.0.1'
      DEFAULT_REGION: 'eu-west-2'
      DEBUG: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/tmp/localstack
```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

```typescript
const apigwManagementApi = new AWS.ApiGatewayManagementApi({
  apiVersion: '2018-11-29',
  endpoint: `${event.requestContext?.domainName}/${event.requestContext.stage}`,
});
const { connectionId } = event.requestContext;

await apigwManagementApi
  .postToConnection({ ConnectionId: connectionId, Data: payloadData })
  .promise();
```

**Comment by alsper** [comment]
I found switching the endpoint to `http://host.docker.internal:4566` worked in the end, however this isn't documented anywhere and it would be good to see this work correctly with the endpoint built from the information in the request context or at least some good documentation/working example of sending messages back from lambdas to clients in these WebSocket APIs.

**Comment by tobias-zeptio** [comment]
We have this running with the endpoint set as "http://localstack:4566" while running lambdas i docker.

**Comment by whummer** [comment]
Thanks for reporting @alsper . Can you please try exposing port `53` (and ideally port `443`) in your docker-compose config as well:
```
ports:
    - '53:53'
    - '443:443'
    - ...
```
This should enable a small DNS server that will resolve `execute-api.localhost.localstack.cloud` to the IP address of the LocalStack API endpoint (same as `$LOCALSTACK_HOSTNAME`).

Alternatively, you can use `host.docker.internal`, as has been mentioned, or use the `LOCALSTACK_HOSTNAME` environment variable directly to extract the host.

Hope that helps - please keep us posted if there are any other questions or issues. Thanks for your help!
