### ISSUE TITLE
cognito-idp admin-create-user `--force-alias-creation` flag ignored

### ISSUE THREAD

**Issue by victorlora** [localstack/localstack#4100]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

LocalStack seemingly ignores the [`--force-alias-creation`](https://docs.aws.amazon.com/cli/latest/reference/cognito-idp/admin-create-user.html) preventing multiple Cognito users to be created with the same email address.

## Expected behavior
[Documented](https://docs.aws.amazon.com/cli/latest/reference/cognito-idp/admin-create-user.html) API behavior:

> --force-alias-creation | --no-force-alias-creation (boolean)
> 
>     This parameter is only used if the phone_number_verified or email_verified attribute is set to True . 
>     Otherwise, it is ignored.
> 
>     If this parameter is set to True and the phone number or email address specified in the 
>     UserAttributes parameter already exists as an alias with a different user, the API call will
>     migrate the alias from the previous user to the newly created user. The previous user
>     will no longer be able to log in using that alias.
> 
>     If this parameter is set to False , the API throws an AliasExistsException error if the alias
>     already exists. The default value is False .

## Actual behavior

Getting the following error message:

> An error occurred (InternalServerError) when calling the AdminCreateUser operation (reached max retries: 2):
> Error in Cognito action "AdminCreateUser": Different existing values for alias keys
> "MultiKey(['second-user'])"/"MultiKey(['first-user', 'foo@example.com'])": "<some-value-1>" != "<some-value-2>"

# Steps to reproduce
With the following in `~/.aws/credentials`:
```
[local]
aws_access_key_id = test
aws_secret_access_key = test
```

1. Create a new user pool
    ```
    aws --endpoint-url "http://localhost:4566" \
        --profile local \
        cognito-idp create-user-pool --pool-name MyUserPool
    ```
2. `export POOL_ID=<my-user-pool-id>`
3. Create the first user
    ```
    aws --endpoint-url "http://localhost:4566" --profile local cognito-idp admin-create-user \
          --user-pool-id $POOL_ID \
          --username first-user \
          --user-attributes Name=email,Value=foo@example.com Name=email_verified,Value=true \
          --message-action SUPPRESS \
          --force-alias-creation
    ```
4. Create the second user with the same email
    ```
    aws --endpoint-url "http://localhost:4566" --profile local cognito-idp admin-create-user \
          --user-pool-id $POOL_ID \
          --username second-user \
          --user-attributes Name=email,Value=foo@example.com Name=email_verified,Value=true \
          --message-action SUPPRESS \
          --force-alias-creation
    ```

## Command used to start LocalStack
`docker run --rm -it \
     -p 4566:4566 \
     -e SERVICES=cognito \
     -e LOCALSTACK_API_KEY=REDACTED \
     localstack/localstack-light:0.12.11`

**Comment by whummer** [comment]
Thanks for reporting @victorlora . This should be fixed in the meantime - can you please pull the `latest` Docker image and give it another try? Please report here if the problem persists. Thanks for your help!
