### ISSUE TITLE
LAMBDA_FORWARD_URL fails to forward invocation can't encode event object.

### ISSUE THREAD

**Issue by hobochild** [localstack/localstack#4106]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

I'm trying to forward the lambda invocations to a local service using the `LAMBDA_FORWARD_URL`.  I've created a basic lambda and set the `LAMBDA_FORWARD_URL`.

```
  localstack:
    image: localstack/localstack
    ports:
      - 4566:4566
    environment:
      SERVICES: sqs,s3,cloudwatch,lambda,logs,iam,apigateway
      EDGE_PORT: 4566
      AWS_DEFAULT_REGION: us-east-1
      DEBUG: 1
      DATA_DIR: /tmp/localstack
      LAMBDA_FORWARD_URL: http://app:8000 # app is a local docker-compose service
    volumes:
      - "${PWD}/.localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

I then invoke the lambda via curl:

```
curl http://localhost:4566/restapis/9p75zh27rw/api/_user_request_/xyz
```

But I hit a JSON encoding issue in the `lamba_api.py` module before it calls the invocation it appears that there is a datetime object in the `event` object that can't be serialised? 

```
localstack_1  | 2021-06-06T15:43:27:DEBUG:localstack.services.awslambda.lambda_api: Running Lambda function arn:aws:lambda:us-east-1:000000000000:function:dream-dev from API Gateway invocation: GET /xyz
localstack_1  | 2021-06-06T15:43:27:INFO:localstack.services.awslambda.lambda_api: Error executing Lambda function arn:aws:lambda:us-east-1:000000000000:function:dream-dev: Object of type datetime is not JSON serializable Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 597, in run_lambda
localstack_1  |     invoke_result = forward_to_external_url(func_details, event, context, invocation_type)
localstack_1  |   File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 942, in forward_to_external_url
localstack_1  |     data = json.dumps(event) if isinstance(event, dict) else str(event)
localstack_1  |   File "/usr/lib/python3.8/json/__init__.py", line 231, in dumps
localstack_1  |     return _default_encoder.encode(obj)
localstack_1  |   File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
localstack_1  |     chunks = self.iterencode(o, _one_shot=True)
localstack_1  |   File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
localstack_1  |     return _iterencode(o, 0)
localstack_1  |   File "/usr/lib/python3.8/json/encoder.py", line 179, in default
localstack_1  |     raise TypeError(f'Object of type {o.__class__.__name__} '
localstack_1  | TypeError: Object of type datetime is not JSON serializable
```

Is this a bug or am I using `LAMBDA_FORWARD_URL` incorrectly?

Thanks in advance for any help!

**Comment by mgagliardo** [comment]
Hello @hobochild, would you please add some more information for example the code you are using, commands you are running, etc? The call seems to be fine to your service, but the problem is your service is not returning a proper JSON:

```
TypeError: Object of type datetime is not JSON serializable
```

**Comment by hobochild** [comment]
Hey @mgagliardo, thanks for the response. 

I don't think it has anything to do with my code as the serialise error happens [here](https://github.com/localstack/localstack/blob/master/localstack/services/awslambda/lambda_api.py#L943) before any call is made to my service. 

If I invoke the lambda with via awscli and pass in an event payload then everything works correctly. 

```
awslocal lambda invoke --function-name dream-dev --payload "{}" out.txt
```

However as I mentioned previously it fails when calling it via curl:

```
curl http://localhost:4566/restapis/9p75zh27rw/api/_user_request_/xyz
```

So my guess is that the default event object that localstack constructs has a datetime object in there? 

For clarity this is my lambda function - packaged and deployed via [chalice](https://github.com/aws/chalice)
```
from chalice import Chalice, Response
from chalice.test import Client

app = Chalice(app_name="dream")


@app.route("/xyz")
def index():
    return {"hello": "world"}
```

**Comment by mgagliardo** [comment]
Hello @hobochild, sorry for the delay. As I do not have much experience with chalice, would you mind telling me how to deploy the lambda forwarder correctly to test this out? An "step by step" would be ok if it is not too much trouble for you.

**Comment by hobochild** [comment]
Hey @mgagliardo no stress, I've actually been able to avoid the issue for now as the invocations of all of the lambda's are via sns, which doesn't trigger the issue. Only calling it via an http request triggers the issue.

You shouldn't need to touch Chalice to reproduce the issue. Simply create any lambda with localstack, set the LAMBDA_FORWARD_URL value to something (it doesn't matter what). Then call the lambda via curl. eg

```
curl http://localhost:4566/restapis/9p75zh27rw/api/_user_request_/xyz
```

**Comment by hobochild** [comment]
Closing as this isn't affecting me and I'm not sure many real world cases would encounter this bug.
