### ISSUE TITLE
Allow go1.x runtime lambda functions to execute locally

### ISSUE THREAD

**Issue by yammine** [localstack/localstack#4113]
# Type of request: This is a ...

[ ] bug report
[x] feature request

# Detailed description

Go lambdas suffer from the need to be run with a `docker` executor within localstack. This is the cause of significant slowness in some of our integration testing that inserts items into a dynamo table that has streams + a lambda subscribed. There is roughly a ~3s overhead per item inserted which makes a modest test suite take ~7 minutes to complete (vs. the 10 seconds without lambdas enabled)

Seems the PutItem request blocks until the lambda has finished its invocation.

I suspect allowing the lambdas to execute locally would avoid incurring such a steep cost for invocation. Since the go lambdas are simply binaries it seems like this may be straightforward -- though I have not delved into the code here much.

## Expected behavior

Go lambdas can run with the `local` executor 

## Actual behavior

The `awslocal logs <func-name>` output:
```
2021-06-07T19:56:10.848000+00:00 2021/06/07/[LATEST]25a3db3d START a18cfe30-f8a0-45e1-82af-d3963edb6850: Lambda arn:aws:lambda:us-east-1:000000000000:function:func-name started via "local" executor ...
2021-06-07T19:56:10.854000+00:00 2021/06/07/[LATEST]25a3db3d Unable to find executor for Lambda function "func-name". Note that Node.js, Golang, and .Net Core Lambdas currently require LAMBDA_EXECUTOR=docker
```

**Comment by whummer** [comment]
Hi @yammine , thanks for this suggestion. Do you think you would be able to help with an initial implementation of local Go invocations? This would be a good starting point (we currently only support local execution for Python): https://github.com/localstack/localstack/blob/master/localstack/services/awslambda/lambda_api.py#L855-L867 Thanks for your help!

**Comment by pinzon** [comment]
Hi @yammine, I'm currently working on developing the feature you requested but I'm stuck running a golang lambda function locally on my Linux machine.
If I could do it then I could integrate the process into Localstack. 
I was hopping you could help me figuring out some errors I wrote in this [issue](https://github.com/lambci/docker-lambda/issues/340)

**Comment by pinzon** [comment]
The PR #4310 handles this feature and it has been recently merged.
So I'm closing this issue.
