### ISSUE TITLE
LocalStack Java Utils cannot load localstack config file 

### ISSUE THREAD

**Issue by AntonOellerer** [localstack/localstack#4115]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description
The docker image 0.12.12 seems to have python 3.7 instead of 3.8 installed.
With 0.12.11, everything works as expected.
## Expected behavior
[localstack java utils](https://github.com/localstack/localstack-java-utils) can read the port configuration from the localstack config file.

## Actual behavior
When using [localstack java utils](https://github.com/localstack/localstack-java-utils), startup fails since the port configuration can not be loaded.
This config is expected to be in `/opt/code/localstack/.venv/lib/python3.8/`, but in the `0.12.12` image only `/opt/code/localstack/.venv/lib/python3.7` is present.

# Steps to reproduce
1. Install localstack
2. Install localstack-java-utils 0.2.11 via maven
3. Write a test (for me the error came up when requesting a s3 service)

## Command used to start LocalStack
Done by the localstack-java-utils plugin

**Comment by cabral-ricardo** [comment]
same problem,
java.lang.IllegalArgumentException: Unknown port mapping for service: s3
at cloud.localstack.Localstack.getServicePort(Localstack.java:232)
at cloud.localstack.Localstack.endpointForService(Localstack.java:223)
at cloud.localstack.Localstack.getEndpointS3(Localstack.java:122)
at cloud.localstack.awssdkv1.TestUtils.getEndpointConfigurationS3(TestUtils.java:232)
at cloud.localstack.awssdkv1.TestUtils.getClientS3(TestUtils.java:133)

**Comment by pinzon** [comment]
Hi, thank you for reporting this issue, I have already a PR that addresses it. 
Hopefully it will be merge soon.

**Comment by cabral-ricardo** [comment]
great. I changed to `findify.s3mock` while I wait this deploy

**Comment by pinzon** [comment]
My PR addressing this issue has been merge. so I'll close this issue.
