### ISSUE TITLE
Cognito migration lambda not called

### ISSUE THREAD

**Issue by Ron-lab** [localstack/localstack#4116]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description
When running cognito.initiateAuth() with username and password and the user doesn't exist in the user pool, the migration-lambda is not called

## Expected behavior
Calling the migration lambda if use doesn't exist in the pool
...

## Actual behavior
migration lambada is not called
...

# Steps to reproduce
- Run cognito.initiateAuth() on user that wasn't migrated
## Command used to start LocalStack
Using image: localstack/localstack:latest
...

```
## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
```
       res = await cognito.initiateAuth({
        ClientId: clientId,
        AuthFlow: 'USER_PASSWORD_AUTH',
        AuthParameters: {
          USERNAME: 'myuser@email.com',
          PASSWORD: '1234',
        },
        ClientMetadata: {

        }
      }).promise();
```

...

**Comment by whummer** [comment]
Thanks for reporting @Ron-lab , and apologies for the delay. The migration / trigger configuration may depend on some details how you've configured your user pool, user pool client, etc. So far we haven't been able to replicate the issue - would you mind sharing a complete, isolated example that we can run to replicate this issue end-to-end? Also, I'm assuming this is still reproducible with the `latest` Docker image? Thanks for your help!

**Comment by whummer** [comment]
Quick follow-up on this issue @Ron-lab - have you been able to give this another try in the meantime? We have recently pushed a number of enhancements for the Cognito API, in particular also related to migration triggers. Please let us know if the problem persists with the `latest` Docker image - happy to look into it in more detail.. Thanks!
