### ISSUE TITLE
AWS Step Functions API support

### ISSUE THREAD

**Issue by vicneanschi** [localstack/localstack#412]
Will [LocalStack](https://github.com/localstack/localstack) support [Step Functions](https://aws.amazon.com/step-functions/)?

This would require an implementation of [State Machine](http://docs.aws.amazon.com/step-functions/latest/dg/concepts-states.html)  which is described by [Amazon States Language](http://docs.aws.amazon.com/step-functions/latest/dg/concepts-amazon-states-language.html).

For starters it would be enough to support just one [type of tasks](http://docs.aws.amazon.com/step-functions/latest/dg/concepts-tasks.html) - [Lambda Function](http://docs.aws.amazon.com/step-functions/latest/dg/tutorial-creating-lambda-state-machine.html).

**Comment by whummer** [comment]
Hi @vicneanschi , no immediate plans at this point, given the current backlog of issues and bug reports. But would you be able to spike out an initial implementation? I'd be happy to help out and provide guidance. Thanks!

**Comment by HerveNivon** [comment]
Here, we are willing to implement it. Do you have guidance you can share?

cc @ChristopheBougere

**Comment by ChristopheBougere** [comment]
I've started an implementation of a local stepfunctions.
My plan was to make it as an standalone node package first, and to integrate it to `localstack` later. Would that be conceivable to integrate a node program in `localstack`? I guess this is what you are doing with dynamodb local too, which is in Java?
And here are the guidances I've started with, let me know what you think:
- 100% reflect stepfunctions API and errors, like in localstack
- need to start the server
- using redux (https://redux.js.org/) for state management

For information, I've just published a state machine validator that uses JSON schemas: https://www.npmjs.com/package/asl-validator (not tested a lot yet)

If someone is interested to contribute, let me know I'll probably put my WIP on github soon.

**Comment by whummer** [comment]
Thanks for jumping on that feature @HerveNivon @ChristopheBougere . Yes, integrating a node program is totally conceivable, we're already doing that, for example with [kinesalite](https://github.com/localstack/localstack/blob/master/localstack/services/kinesis/kinesis_starter.py#L22-L23).

To add to your list of bullet points: ideally, we would want to keep the dependency stack as light-weight as possible, to avoid blowing up the Docker image size. Please bear that in mind when designing your solution. Not sure how many dependencies redux will pull in transitively (I'll probably do a quick test later today).

Also, please bear in mind @ChristopheBougere that LocalStack is built on the principle of replaceability, so we may be switching implementations in the future, depending on users' needs. Therefore, the best way to ensure your specific requirements are covered by the respective implementation is to add as many (integration) tests as possible. Thanks!

Super excited to see this implemented!

**Comment by ChristopheBougere** [comment]
That makes a lot of sense @whummer, I'll keep that in mind and let you know of the progress.
I usually try to keep the number of dependencies low.
BTW, do you know the node version packaged in the docker image? (having node >= 6 would help having a clean code without needing babel compilation)

**Comment by whummer** [comment]
```
$ docker run --entrypoint= localstack/localstack node -v
v8.4.0
```

**Comment by tristanbenier** [comment]
Hi @whummer ,

As previously mentionned by @ChristopheBougere and @HerveNivon , we developed a node package to run a local Step Functions server.
https://www.npmjs.com/package/stepfunctions-local/

It is fully compliant with AWS Step Functions API and can be easily called by changing the endpoint.

Are you interested in integrating the service into your stack ? If so, how can we proceed ?
Also, in order to implement integration tests, we would need to solve the issue https://github.com/localstack/localstack/issues/557 I have opened. If anyone could have a look and test, that would be awesome.

Cheers'

**Comment by ChristopheBougere** [comment]
Hi @whummer and contributors,

Any news on this? I would be happy to start a localstack stepfunctions integration, (using [stepfunctions-local](https://www.npmjs.com/package/stepfunctions-local)), but I may need help as I'm not familiar with the localstack code.

**Comment by whummer** [comment]
Initial support for Step Functions added in this PR: https://github.com/localstack/localstack/pull/1133
