### ISSUE TITLE
KInesis subscribe to shard API events continuation token is invalid 

### ISSUE THREAD

**Issue by daryl-d** [localstack/localstack#4120]
# Type of request: This is a ...

[X] bug report
[ ] feature request

# Detailed description
The events returned by the kinesis subscribe to shard api is not complying the the AWS specification.
I ran into this problem when testing out V2 of the KCL multilangdaemon.

## Expected behavior

In my opinion, should be returning the sequence number of the last record returned by the kinesis get records call or the sequence number  given in the request or '0' if no records are specified.

I've made a [PR](https://github.com/localstack/localstack/pull/4119) matching what I expect
...

## Actual behavior

It is returning the shard iterator as the [continuation token](https://github.com/localstack/localstack/blob/master/localstack/services/kinesis/kinesis_listener.py#L296)

This goes against the aws docs [here](https://docs.aws.amazon.com/kinesis/latest/APIReference/API_SubscribeToShardEvent.html)

# Steps to reproduce

Covered by test case in PR

**Comment by whummer** [comment]
Merged in #4119 - should become available in the `latest` Docker image shortly (in ~30 mins). Thanks again!
