### ISSUE TITLE
S3 GetBucketEncryption method breaks at parse error (rusoto_s3) in 0.12.10+ versions

### ISSUE THREAD

**Issue by Veetaha** [localstack/localstack#4122]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

When updating from `0.12.9.1` docker image of localstack to any of the more recent ones we are experiencing a breakage using [`rusoto_s3::S3::get_bucket_encryption`](https://docs.rs/rusoto_s3/0.46.0/rusoto_s3/struct.S3Client.html#method.get_bucket_encryption) API call of the Rust SDK implementation.

The returned error is the following:
```
ParseError("START Expected ServerSideEncryptionConfiguration got BucketEncryptionStatus")
```

Supposedly this commit introduced the breaking change: https://github.com/localstack/localstack/commit/9552b4b994917d61d47823b6663b3b7b6fd34cfa

The returned raw XML's shape was changed:

- `0.12.9.1`:
  ```xml
  <?xml version="1.0" encoding="utf-8"?>
  <ServerSideEncryptionConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
    <Rule>
      <ApplyServerSideEncryptionByDefault>
        <SSEAlgorithm>AES256</SSEAlgorithm>
      </ApplyServerSideEncryptionByDefault>
      <BucketKeyEnabled>true</BucketKeyEnabled>
    </Rule>
  </ServerSideEncryptionConfiguration>
  ```

- `0.12.10`:
  ```xml
  <?xml version="1.0" encoding="UTF-8"?>
  <BucketEncryptionStatus xmlns="http://doc.s3.amazonaws.com/2006-03-01">
    <Rule>
      <ApplyServerSideEncryptionByDefault>
        <SSEAlgorithm>AES256</SSEAlgorithm>
      </ApplyServerSideEncryptionByDefault>
    </Rule>
  </BucketEncryptionStatus>
  ```

The XML from `0.12.9.1` version actually matches the [AWS API docs for GetBucketEncryption method](https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetBucketEncryption.html).

## Expected behavior

`GetBucketEncryption` method should return the same shape XML as in `0.12.9.1`, there wasn't a breaking change note, so it should work as before?

## Actual behavior

The Rust SDK fails to parse the new shape of response for `GetBucketEncryption`.

# Steps to reproduce

## Command used to start LocalStack

```
docker run ... localstack/localstack:{any version greater than 0.12.9.1}`
```

Use the following terraform resource to deploy a sample bucket:
```tf
resource "aws_s3_bucket" "bucket" {
  bucket = "test-bucket"
  server_side_encryption_configuration {
    rule {
      apply_server_side_encryption_by_default {
        sse_algorithm = "AES256"
      }
      bucket_key_enabled = true
    }
  }
}
```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

```
awslocal s3api get-bucket-encryption --bucket test-bucket --debug
```

View the output logs of the returned Request and see that the XML doesn't match the expected shape from `0.12.9.1` version. This makes the Rust SDK fail to parse it.

**Comment by whummer** [comment]
Thanks for reporting @Veetaha . This should be fixed in the meantime - can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists. Thanks!

**Comment by Veetaha** [comment]
@whummer it's fixed, but only partly.

I am rerunning the same tests, but there is `BucketKeyEnabled` element missing in the returned XML:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<ServerSideEncryptionConfiguration xmlns="http://doc.s3.amazonaws.com/2006-03-01">
   <Rule>
      <ApplyServerSideEncryptionByDefault>
         <SSEAlgorithm>AES256</SSEAlgorithm>
      </ApplyServerSideEncryptionByDefault>
   </Rule>
</ServerSideEncryptionConfiguration>
```

Version `0.12.9.1` still works

**Comment by Veetaha** [comment]
@whummer I suggest reopening the issue while it's not fixed according to https://github.com/localstack/localstack/issues/4122#issuecomment-861679369

**Comment by whummer** [comment]
Thanks for the update @Veetaha - this should now (hopefully) be fixed in the `latest` Docker image. Please keep us posted if the problem persists. Thanks!

**Comment by Veetaha** [comment]
The `latest` image seems to be fixed, thanks, waiting for the next semver release to migrate.
