### ISSUE TITLE
S3Presigner getting 500 response

### ISSUE THREAD

**Issue by israelaqwak** [localstack/localstack#4125]
# Type of request: This is a ...

[ X] bug report
[ ] feature request

# Detailed description
I am trying to use localstack for testing a Java Spring GRPC service @ Maven.
This service has a flow where it reads a file from s3, then presigns it to a new location and returns the download URL.
On actual flow it works fine, but for some reason it doesn't on the test flow with localstack.
I am getting a 500 status on the connection that performs the presign.
...

## Expected behavior
Presigning an object and downloading it afterwards using the URL.
...

## Actual behavior
Getting a 500 response when presigning.
...

# Steps to reproduce

Running via Java with Maven
Pom:
<dependency>
            <groupId>org.testcontainers</groupId>
            <artifactId>localstack</artifactId>
            <version>${testcontainers.version}</version>
            <scope>test</scope>
</dependency>

@Container
public static final LocalStackContainer localStackContainer = new LocalStackContainer(DockerImageName.parse("localstack/localstack:0.12.9"))
            .withServices(S3);

KEY = "test" (as requested in the docs regarding having presign work) for accessKeyId and secretAccessKey

S3Client def:

public S3Client getS3Client(String partnerId) {
        return S3Client.builder()
                .endpointOverride(localStackContainer.getEndpointOverride(S3))
                .credentialsProvider(StaticCredentialsProvider
                        .create(AwsBasicCredentials.create(KEY, KEY)))
                .region(Region.of(localStackContainer.getRegion()))
                .build();
}

S3Presigner def:

public S3Presigner getS3Presigner(String partnerId) {
    return S3Presigner.builder()
            .endpointOverride(localStackContainer.getEndpointOverride(S3))
            .credentialsProvider(StaticCredentialsProvider
                    .create(AwsBasicCredentials.create(KEY, KEY)))
            .region(Region.of(localStackContainer.getRegion()))
            .build();
}

private static void signBucket(S3Presigner presigner, String bucketName, String keyName, byte[] inputBytes) {

        try {

          PutObjectRequest objectRequest = PutObjectRequest.builder()
                  .bucket(bucketName)
                  .key(keyName)
                  .contentType("text/plain")
                  .contentLength((long) inputBytes.length)
                  .build();

          PutObjectPresignRequest presignRequest = PutObjectPresignRequest.builder()
                  .signatureDuration(Duration.ofMinutes(SIGN_DURATION_MINUTES))
                  .putObjectRequest(objectRequest)
                  .build();

          PresignedPutObjectRequest presignedRequest = presigner.presignPutObject(presignRequest);

          // Upload content to the Amazon S3 bucket by using this URL
          URL url = presignedRequest.url();

          // Create the connection and use it to upload the new object by using the presigned URL
          HttpURLConnection connection = (HttpURLConnection) url.openConnection();
          connection.setDoOutput(true);
          connection.setRequestProperty("Content-Type", "text/plain");
          connection.setRequestMethod("PUT");
          OutputStream out = connection.getOutputStream();
          IOUtils.copy(new ByteArrayInputStream(inputBytes), out);
          out.close();
          if (connection.getResponseCode() != 200) { #Getting responseCode 500 here
              String errorMsg = String.format("Sign bucket - got a non 200 response code: %d, with message: %s",
                      connection.getResponseCode(), connection.getResponseMessage());
              logger.error(errorMsg);
              throw Status.UNAVAILABLE
                      .withDescription(errorMsg)
                      .asRuntimeException();
          }
      } catch (S3Exception | IOException e) {
              logger.error(String.format("Got an error while trying to presign the logs object: %s", e.getMessage()));
              throw Status.UNAVAILABLE
                      .withDescription(e.getMessage())
                      .asRuntimeException();
      }
}

...

**Comment by macnev2013** [comment]
Thanks for reporting the issue @israelaqwak. Looks like you are using fairly older version - `localstack/localstack:0.12.9`. We have added bunch of improvements/fixes in meanwhile. Can you please give it another try with the latest version? Thanks

**Comment by israelaqwak** [comment]
Thanks, that solved it. Should've tried that before.
