### ISSUE TITLE
localstack/localstack:0.12.12 and localstack-full:0.12.12 have incorrect PYTHONPATH

### ISSUE THREAD

**Issue by mdaniel** [localstack/localstack#4128]
# Type of request: This is a ...

[X] bug report
[ ] feature request

# Detailed description

```console
$ docker run --name lstack localstack/localstack-full:0.12.12
$ sleep 120  # or while ! docker logs lstack | grep ^Ready; do sleep 1; done
$ docker exec lstack awslocal sts get-caller-identity
Traceback (most recent call last):
  File "/usr/bin/awslocal", line 34, in <module>
    from localstack_client import config  # noqa: E402
ModuleNotFoundError: No module named 'localstack_client'
```
One can see the misalignment via

```console
$ docker exec lstack bash -exc 'ls -ld $PYTHONPATH'
+ ls -ld /opt/code/localstack/.venv/lib/python3.8/site-packages
ls: /opt/code/localstack/.venv/lib/python3.8/site-packages: No such file or directory
```

and demonstrate it is merely a bogus PYTHONPATH via

```console
$ docker exec -e PYTHONPATH=/opt/code/localstack/.venv/lib/python3.7/site-packages ls awslocal sts get-caller-identity
```

Strangely enough, the `localstack:0.12.12` flavor _also_ has the PYTHONPATH pointed at a missing directory, but with that image the `docker exec lstack awslocal sts get-caller-identity` works as expected, so maybe it has some per-script override that `full` does not

## Expected behavior

```console
$ docker exec lstack awslocal sts get-caller-identity
{
    "UserId": "AKIAIOSFODNN7EXAMPLE",
    "Account": "000000000000",
    "Arn": "arn:aws:sts::000000000000:user/moto"
}
```

## Actual behavior

See above

# Steps to reproduce

See above

## Command used to start LocalStack

See above

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

See above

**Comment by whummer** [comment]
Thanks for reporting @mdaniel . This issue has already been fixed in #4121 - we'll push a new release shortly. Thanks!

**Comment by whummer** [comment]
Update: @mdaniel - we've now pushed a hotfix for the `0.12.12` release - can you please pull the image again and give it another try. Thanks!

**Comment by mdaniel** [comment]
I can confirm it seems all better now, thanks for the quick turn-around!
