### ISSUE TITLE
Serverlss on Host unable to deply to localsrack on docker

### ISSUE THREAD

**Issue by ssabnis** [localstack/localstack#413]
I am able successfully start the services in docker running on CentOS 7. Serverless deploying from host to docker hangs for long time. and I get an error 

> "The specified bucket does not exist" 

Following error on the docker terminal tab
```
caught_exception)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/retryhandler.py", line 223, in __call__
attempt_number, caught_exception)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
raise caught_exception
EndpointConnectionError: Could not connect to the endpoint URL: "http://localhost.localdomain:4581/"

Any clue what is going on here.

Thanks


```

**Comment by whummer** [comment]
Thanks for reporting @ssabnis . Please refer to the Troubleshooting section in the README regarding path style access to S3 buckets: https://github.com/localstack/localstack#troubleshooting

**Comment by ssabnis** [comment]
Issue resolved I think I need run this in the context of the VM that I am using.
