### ISSUE TITLE
Validation fails for V4 S3 presigned links with custom get options.

### ISSUE THREAD

**Issue by cmlara** [localstack/localstack#4133]
# Type of request: This is a ...

[X ] bug report
[ ] feature request

# Detailed description
V4 presigned link validation fails when additional query parameters are included in the signature.
example (before signing):  http://localstack:4566/text.txt?test=value  will not validate in localstack  however AWS will validate it

## Expected behavior
Links should validate as valid (same code tested against AWS and successful) 
## Actual behavior
Error: The request signature we calculated does not match the signature you provided. Check your key and signing method

# Steps to reproduce

## Command used to start LocalStack
docker run -d --name localstack_test --rm -p 4566:4566 -e EDGE_PORT=4566 -e SERVICES=s3 -e HOSTNAME_EXTERNAL=localstack localstack/localstack:0.12.12

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

```
<?php
require 'vendor/autoload.php';

use Aws\S3\S3Client;
use Aws\CommandInterface;
use Psr\Http\Message\RequestInterface;
use Aws\Middleware;

$config = [
	'credentials' => [
		'key'    => 'test',
		'secret' => 'test',
	],
	'region' => 'us-east-1',
	'version' => 'latest',
	'endpoint' => 'http://localstack:4566',
];


$client = new S3Client($config);

$buckets = $client->listBuckets();
if (empty($buckets['Buckets'])) {
        $client->createBucket([
                'Bucket' => 'testbucket',
        ]);
        echo 'Bucket test created' . PHP_EOL;
} else {
        echo 'Bucket test exists' . PHP_EOL;
}

$client->upload('testbucket', 'test.txt', 'test');


$cmd = $client->getCommand('GetObject', [
    'Key' => 'test.txt',
    'Bucket' => 'testbucket',
]);


$cmd->getHandlerList()->appendBuild(
    Middleware::mapRequest(function (RequestInterface $request) {
        // Return a new request with the added header
        return $request->withUri(
            $request->getUri()->withQuery(
                $request->getUri()->getQuery() . "test=val&itok=abc123&atest=atestval"
            )
        );
    }),
    'add-custom-param'
);

$request = $client->createPresignedRequest($cmd, '+3 days');
$presignedUrl = (string)$request->getUri();
echo $presignedUrl;

````
# More details

I'm not in a spot to put a debugger on this to confirm, however I believe this portion of code in localstack/services/s3/s3_utils.py  may be at fault:
```
                if (key_lower not in (header[0].lower() for header in headers) and
                        key_lower not in params_header_override):
                    if key_lower in (allowed_param.lower() for allowed_param in ALLOWED_QUERY_PARAMS):
                        query_string[key] = query_params[key][0]
                    elif key_lower in (blacklisted_header.lower() for blacklisted_header in BLACKLISTED_HEADERS):
                        pass
                    else:
                        sign_headers[key] = query_params[key][0]
```

I believe If I'm reading this code correctly and following the rest of the code execution correct that this will add all query string parameters that are not in ALLOWED_QUERY_PARAMS  into signed_headers when it should be part of query_string which will throw off the calculation later as all query parameters need to be before headers in the S3 algorithm.

Reference: https://docs.aws.amazon.com/AmazonS3/latest/API/images/sigV4-using-auth-header.png

**Comment by whummer** [comment]
Thanks @cmlara @macnev2013 . This should now be fixed in #4157 - can you please pull the `latest` Docker image and give it another try? Please report here if the problem persists. Thanks for your help!
