### ISSUE TITLE
Sqs rejects whole batch if one message is invalid

### ISSUE THREAD

**Issue by kandrejevs2** [localstack/localstack#4135]
# Type of request: This is a ...

[ * ] bug report
[ ] feature request

# Detailed description

When sending messages to sqs in a batch of 10, if one of them contains invalid binary character, the whole batch is rejected by localstack.

this bug appeared in 11.2 version

## Expected behavior

valid messages should be sent to sqs and invalid ones should be in "failed" data object

![image](https://user-images.githubusercontent.com/57944366/121673002-1a10c800-cab9-11eb-850b-34938596c6c0.png)

## Actual behavior

all 10 messages are failed when 9 should not be rejected

![image](https://user-images.githubusercontent.com/57944366/121674144-5690f380-caba-11eb-90ce-d42c938afe42.png)

# Steps to reproduce

send batch message containing 10 messages where one of them contains invalid character e.g. `mb_chr(1, 'UTF-8'),`
https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_SendMessageBatch.html

**Comment by usmangani1** [comment]
@kandrejevs2  Thanks for reporting the issue. 

Which error are you receiving in this case. Usually whenever a given entry in a batch is wrong. AWS returns an error "SQS.Client.exceptions.InvalidBatchEntryId" and will not process any message in the batch and this is expected.

The failed entries in the response are usually the entries which AWS SQS tried to process but the processing was not successful.

Please let us know in case if you have any further queries regarding this.Thanks.

**Comment by kandrejevs2** [comment]
Hi @usmangani1 .

the screenshots are same request against aws sqs and localstack. as you can see localstack behaves differently than aws. prior 11.2 version it was working correctly- correct messages in batch are processed, in 11.2 it started to reject whole batch.

**Comment by baermat** [comment]
This is fixed in the our new SQS-Provider.
To run LocalStack with this SQS-Provider, set PROVIDER_OVERRIDE_SQS=asf as environment variable for LocalStack
