### ISSUE TITLE
Consider Kinesis-Mock over Kinesalite

### ISSUE THREAD

**Issue by etspaceman** [localstack/localstack#4137]
# Type of request: This is a ...

- [ ] bug report
- [X] feature request

# Detailed description

Kinesalite has been a great mock for a long time. However, it is missing several API calls (e.g. UpdateShards), and seems to be on life-support as of late (last commit being Oct. 2020).

[Kinesis-Mock](https://github.com/etspaceman/kinesis-mock) is a new mock which supports all API calls except SubscribeToShard (due to lack of support for the required Http2 Features in the Scala ecosystem). It is distributed as a docker image, but there is also a jar executable that can be used. 

I am the creator of Kinesis-Mock, so I can work with Localstack on any changes that would be needed to make this pairing work, if desired.

**Comment by whummer** [comment]
Thanks for providing `kinesis-mock` @etspaceman - looks like a great implementation. In fact, we've recently been facing some issues/limitations with kinesalite (although, as you mentioned, it's been absolutely great and very reliable for a long time!). 

I've added a first quick-and-dirty integration in #4139 - to give it a try and see if the tests are passing. Looks like there are still some issues with the tests, we should look into those. 

One important feature for us is persistence - does `kinesis-mock` allow to persist the state of streams, or is this feature on your roadmap? Perhaps we can work together on these missing features, then it would be a great addition to LocalStack.. Thanks for your help!

**Comment by etspaceman** [comment]
When you say persistence of streams, can you clarify what you're looking for?

WRT the size and runtime, the docker image uses a graal native-image which is compressed. No JVM needed. The docker image is 24MB. I believe the actual executable is smaller, at least comparable to the kinesalite offering. That's specifically built for Linux though. I could potentially create executables for Mac and Windows environments, but I'm not sure what that would mean for your distribution. 

Can certainly look into any failing tests as well!

**Comment by etspaceman** [comment]
Do you have a schema/format for the persisted data that you're using today? Seems like something I could add pretty trivially.

**Comment by etspaceman** [comment]
I've started some work on the data persistence here: https://github.com/etspaceman/kinesis-mock/pull/93.

Looking into the tests, there are a couple of errors:

- One is being thrown because a stream is not currently ACTIVE when leveraging it. The mock has a configured delay when creating resources in order to mimic the Kinesis behavior in a production like environment. See https://github.com/etspaceman/kinesis-mock#service-configuration. I would recommend either setting the configuration to `0ms` or adding sleeps to ensure resources are active.
- The other error seems to be with the DynamoDBStreams API, in which it is trying to get a shard iterator by referencing a sequence number that does not exist. It looks like the test uses AT_SEQUENCE_NUMBER for its request, and passes in a StartingSequenceNumber from the shard's range, but it doesn't look like data is actually produced with that sequence number (unless I'm misreading this?). My mock is set up to fail the request if the sequence number is not associated with an actual record. What is this test trying to accomplish? If you're looking to get data from the beginning of the stream, you could use TRIM_HORIZON instead.

**Comment by etspaceman** [comment]
@whummer I've completed a [PR](https://github.com/etspaceman/kinesis-mock/pull/93) to add persistence to the kinesis-mock. Can you take a look at the configuration here and ensure that it will align with your requirements? The idea is that the data will be persisted on an interval to disk as a JSON file, and will also be flushed to disk if the service is exited. The path and file name is configurable, and the service can be started from an existing file. 

https://github.com/etspaceman/kinesis-mock/blob/e0543b67154eba3292c12d5dd8eae3332dbed53f/README.md#service-configuration

**Comment by etspaceman** [comment]
I also created https://github.com/etspaceman/kinesis-mock/pull/95 to fix the AT_SEQUENCE_NUMBER issue in the tests that are being experienced.

**Comment by whummer** [comment]
Awesome @etspaceman ! Really great to see the quick turnaround. I don't fully grasp everything that's going on in your PR (not really a Scala expert here), but definitely looks great. 

Btw - plugin implementations (like the one you're creating here) are free to choose their own serialization format - no need to use JSON per se. So, if it turns out there's a more efficient binary format, we could switch to that as well in the future. (not critical for now, though)

Looking forward to the next steps - do you want to take over the draft PR #4139 , and create a new PR that incorporates your changes? Looking forward to it - thanks again! 🚀

**Comment by etspaceman** [comment]
Sounds good!

**Comment by etspaceman** [comment]
I opened https://github.com/localstack/localstack/pull/4152 with some updates to your original draft. 

Something I noticed is that Localstack has a lot of proxied endpoints to handle the kinesalite lack of support for these features. We'll want to disable that for kinesis-mock. That seems to be a pretty invasive change though and I'm not terribly familiar with the Localstack inner workings. @whummer it might be helpful if you're able to do some commits to this as well. I can add you as a collaborator to my fork so we could both make commits. LMK what you think.

**Comment by whummer** [comment]
Thanks for the update @etspaceman , looks great.

> might be helpful if you're able to do some commits to this as well. I can add you as a collaborator to my fork so we could both make commits. LMK what you think.

Sure, happy to contribute to your fork as well, so we can push this over the line... 👍 Thanks!

**Comment by whummer** [comment]
Done in #4152
