### ISSUE TITLE
Error requires - LAMBDA_EXECUTOR=docker when invoked.

### ISSUE THREAD

**Issue by ssabnis** [localstack/localstack#414]
I am getting the same error I am running localstack without docker, I am able to deploy, but invoke fails with he following error 
```
'Note that Node.js Lambdas currently require LAMBDA_EXECUTOR=docker') % lambda_name)
Exception: Unable to find executor for Lambda function "my-service-dev-hello". Note that Node.js Lambdas currently require LAMBDA_EXECUTOR=docker

**Comment by whummer** [comment]
Thanks for reporting @ssabnis . What command are you using to start LocalStack? The `LAMBDA_EXECUTOR` environment variable needs to be set in the shell that runs the server, like this:
```
LAMBDA_EXECUTOR=docker localstack start
```

**Comment by ssabnis** [comment]
@whummer thanks for the info. in the second part you mention that Lambda execution need docker. Do I have to start the localstack like 'localstack start --docker' still. And custom set up still point to localhost as shown. ?

```
{
    "APIGateway": "http://localhost:4567",
    "CloudFormation": "http://localhost:4581",
    "CloudWatch":"http://localhost:4582",
    "DynamoDB": "http://localhost:4569",
    "DynamoDBStreams": "http://localhost:4570",
    "ES": "http://localhost:4571",
    "Firehose": "http://localhost:4573",
    "Kinesis": "http://localhost:4568",
    "Lambda": "http://localhost:4574",
    "Redshift": "http://localhost:4577",
    "Route53": "http://localhost:4580",
    "S3": "http://localhost:4572",
    "SES": "http://localhost:4579",
    "SNS": "http://localhost:4575",
    "SQS": "http://localhost:4576"
}

```

**Comment by whummer** [comment]
No, starting the LocalStack framework in Docker is optional - you can do it, but it is not required. With `LAMBDA_EXECUTOR=docker`, LocalStack will run Lambda functions in Docker containers. In fact, a new container is started (and terminated) for each individual Lambda invocation. But again, LocalStack itself can still run on the local machine (and not in Docker).

The configuration points to `localhost` by default. What do you mean by "custom setup" - did you configure any of the [configuration variables](https://github.com/localstack/localstack#configurations)?

**Comment by ssabnis** [comment]
@whummer thanks it worked, I have another question how can I upload the dependent Python modules required for the Lambda when execution.

**Comment by whummer** [comment]
Thanks for confirming that it worked, closing this issue now.

Regarding code packaging, you'll have to create your own logic to create a self-contained zip archive. This is outside the scope of LocalStack. However, you may be able to re-use some of the functionality that we use in our tests to create Lambda functions with module dependencies: https://github.com/localstack/localstack/blob/master/localstack/utils/testutil.py#L51-L74 At least it can serve as a starting point. There are also some specialized libraries out there which facilitate the task of creating Lambda archives (e.g., Serverless framework might help).
