### ISSUE TITLE
Localstack accuses dupplicated egress rule when using terraform

### ISSUE THREAD

**Issue by LuizEduardoCardozo** [localstack/localstack#4141]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

When running the script above, the terraform accuses the following error

```
╷
│ Error: Error authorizing security group egress rules: InvalidPermission.Duplicate: The specified rule already exists
│ 	status code: 400, request id: 7a62c49f-347e-4fc4-9331-6e8eEXAMPLE
│ 
│   with aws_security_group.allow_connection,
│   on main.tf line 9, in resource "aws_security_group" "allow_connection":
│    9: resource "aws_security_group" "allow_connection" {
│ 
╵
``` 

Im using the localstack downloaded using pip.

```
dmitri@laptop:~/Dev/terraform-test$ localstack status
Base version:		0.12.11
Docker image:		Tag latest, ID bc631a3ed305, Created 2021-05-21T12:26:28
Container status:	running (name: "localstack_main", IP: 172.17.0.2)
```

```
dmitri@laptop:~/Dev/terraform-test$ terraform version
Terraform v1.0.0
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v3.45.0
```

## Expected behavior

The terraform script should create a ec2 instance, with two ingress rules, and one egress rule.

## Actual behavior

The terraform accuses an error

# Steps to reproduce

## Command used to start LocalStack

Be sure you have terraform installed on your machine. Copy the main.tf, and uses the following commands:

starting terraform

```sh
localstack start
```

terraform

```sh
terraform init
terraform plan
terraform apply
```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

main.tf

```
provider "aws" {
    region = "us-east-1"

    endpoints {
        ec2 = "http://localhost:4566"
    }
}

resource "aws_security_group" "allow_connection" {
    name = "allow_connections"
    description = "allow tcp and http ingress, and every egress"

    ingress {
        description = "http port"
        from_port = 80
        to_port = 80
        protocol = "tcp"
        cidr_blocks = ["0.0.0.0/0"]
    }

    ingress {
        description = "ssh port"
        from_port = 443
        to_port = 443
        protocol = "tcp"
        cidr_blocks = ["0.0.0.0/0"]
    }

    egress {
        from_port = 0
        to_port = 0
        protocol = "-1"
        cidr_blocks = ["0.0.0.0/0"]
    }
}

resource "aws_instance" "machine" {
    ami = "ami-0b683223eeade51eb"
    instance_type = "t2.micro"

    security_groups = [aws_security_group.allow_connection.name]
}
```

**Comment by usmangani1** [comment]
@LuizEduardoCardozo Thanks for reporting the issue.
We found that currently when creating the security group a default egress rule with the same configurations is also being added hence you are seeing this error. While we are working on fixing this you can try changing the configurations of the egress rule/remove this egress rule and give it a try.

We are working on the fix and will release a fix for this soon. Thanks

**Comment by LuizEduardoCardozo** [comment]
@usmangani1 can I connect to a localstack ec2 instance, like using ssh?

**Comment by LuizEduardoCardozo** [comment]
@usmangani1 can I connect to a localstack ec2 instance, like using ssh?

**Comment by usmangani1** [comment]
@LuizEduardoCardozo While working on the fix We realised that the rule which we are adding is the default outbound rule which gets added to all the security groups and hence there is no change required in this case.

`By default, a security group includes an outbound rule that allows all outbound traffic. You can remove the rule and add outbound rules that allow specific outbound traffic only. If your security group has no outbound rules, no outbound traffic originating from your instance is allowed.`

**Comment by LuizEduardoCardozo** [comment]
@usmangani1 thanks!

**Comment by whummer** [comment]
Thanks @LuizEduardoCardozo @usmangani1 . In the LocalStack Pro version we have basic support for building AMIs and launching EC2 VMs (which you can ssh into), but this feature is still in beta. If you'd like to give it a try - please feel free to ping me and we can look into your requirements in more detail. Thanks!

**Comment by LuizEduardoCardozo** [comment]
@whummer how does the free version works? Can I contribute in some way with the free version (launching a docker container to emulate the ec2 instance, for example), or this is out of free version scope?

I'm using the localstack as much to study aws and at my work, and the ec2 foils me a lot.
