### ISSUE TITLE
API Gateway - Default Prod Stage

### ISSUE THREAD

**Issue by jleck** [localstack/localstack#4144]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

When using an API gateway on amazon, it creates a default stage of prod. This works fine in localstack, but the URLs in app.localstack.cloud still have /stage/ rather than /prod/ in the URL.

## Expected behavior

Correct URL.

## Actual behavior

Incorrect URL.

**Comment by dfangl** [comment]
Will be fixed in the next web update.
