### ISSUE TITLE
AttributeError: module 'localstack.services.awslambda.lambda_api' has no attribute 'BUCKET_MARKER_LOCAL'

### ISSUE THREAD

**Issue by daleobrien** [localstack/localstack#4147]
# Type of request: This is a ...

[X] bug report
[ ] feature request

# Detailed description
When creating a lambda function using `awslocal lambda create-function ...` using the docker image,`localstack/localstack:latest`, currently the one just after `localstack/localstack:0.12.12` fails.

## Expected behavior

The lambda function is created as it would when using  `localstack/localstack:0.12.12`.

## Actual behavior

```
2021-06-15T05:34:21:DEBUG:localstack.services.awslambda.lambda_api: Unknown error: module 'localstack.services.awslambda.lambda_api' has no attribute 'BUCKET_MARKER_LOCAL' Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 1090, in create_function
    result = set_function_code(func_details.code, lambda_name)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/localstack_ext/services/awslambda/lambda_extended.py", line 311, in set_function_code
AttributeError: module 'localstack.services.awslambda.lambda_api' has no attribute 'BUCKET_MARKER_LOCAL'
```

# Steps to reproduce

## Command used to start LocalStack

```

...

export LAMBDA_REMOTE_DOCKER=false
export BUCKET_MARKER_LOCAL='local'
export LAMBDA_EXECUTOR=docker
export SERVICES=cognito,lambda,rds,secretsmanager,ses,sqs,apigateway

localstack start --docker
```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

```
awslocal lambda create-function \
--function-name "some_name"\
--runtime nodejs12.x \
--handler index.handler \
--timeout 3 \
--memory-size 1024 \
--role arn:aws:iam::000000000000:role/irrelevant \
--zip-file fileb://src/function.zip
```

**Comment by whummer** [comment]
Thanks for reporting @daleobrien @garymcleanhall . This should be fixed in the meantime - can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists. Thanks for your help!

**Comment by daleobrien** [comment]
That update worked for me, thank you.
