### ISSUE TITLE
Lambda:alias is blocked by Localstack logic

### ISSUE THREAD

**Issue by DavidTanner** [localstack/localstack#4158]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

Calling `listEventSourceMappings` with the FunctionName `${FunctionName}:${Alias}` gets thrown as an exception, when the AWS API does not.

https://github.com/localstack/localstack/blob/ea4dcf408b86491e5e2d95c44e5474706624ba9d/localstack/utils/aws/aws_stack.py#L505-L506

## Expected behavior

```json
{
    "EventSourceMappings": []
}
```

## Actual behavior

```html
An error occurred (500) when calling the ListEventSourceMappings operation (reached max retries: 4): <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
```
# Steps to reproduce

## Command used to start LocalStack

```bash
docker run -d -p "4566:4566" -v /var/run/docker.sock:/var/run/docker.sock -e SERVICES=lambda 'localstack/localstack:0.12.12'
```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

```bash
aws --endpoint-url http://localhost:4566 lambda list-event-source-mappings --function-name functionName:deployed
```

**Comment by pinzon** [comment]
Thank you for interest in the project. The PR addressing this issue has been merged.
