### ISSUE TITLE
Service plugins seem to overwrite logging configuration of other components

### ISSUE THREAD

**Issue by thrau** [localstack/localstack#4162]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

If i run localstack with `SERVICES=s3,sqs,sns,ec2 localstack`, and run a unit test, I get detailed log output:

```
2021-06-17 21:55:41,140:API: 127.0.0.1 - - [17/Jun/2021 21:55:41] "PUT /notif-e9ee5c57 HTTP/1.1" 200 -
2021-06-17 21:55:41,269:API: 127.0.0.1 - - [17/Jun/2021 21:55:41] "POST / HTTP/1.1" 200 -
2021-06-17 21:55:41,367:API: 127.0.0.1 - - [17/Jun/2021 21:55:41] "POST / HTTP/1.1" 200 -
2021-06-17 21:55:41,491:API: 127.0.0.1 - - [17/Jun/2021 21:55:41] "POST / HTTP/1.1" 200 -
2021-06-17 21:55:41,593:API: 127.0.0.1 - - [17/Jun/2021 21:55:41] "HEAD /notif-e9ee5c57 HTTP/1.1" 200 -
2021-06-17 21:55:41,642:API: 127.0.0.1 - - [17/Jun/2021 21:55:41] "DELETE /notif-e9ee5c57 HTTP/1.1" 204 -
...
```

Whereas when I run it without setting any services, running the same unit test yields no log output at all.

It looks like some plugins are overwriting the log configuration of certain components.

## Expected behavior

I would expect that starting services does not have side effects in the logging configuration

## Actual behavior

but it apparently has

# Steps to reproduce

## Command used to start LocalStack

`DEBUG=1 SERVICES=s3,sqs,sns,ec2 localstack start --host`

vs

`DEBUG=1 localstack start --host` (community version)

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

manually run a test from `test_s3.py`

**Comment by thrau** [comment]
lambda seems to be the culprit. if i add lambda to `SERVICES=s3,sqs,sns,ec2` the http logging output disappears

**Comment by pinzon** [comment]
Hi @thrau I haven't been able to reproduce this issue. 
When I run localstack whether on docker or not and set lambda service or any other I still don't get the logs when running the s3 unit test. 

I also tried running some lambda service functions with awscli but still I' dont get those logs. 

Could you provide more info about your setup and also in how you run the test?
Thanks!

**Comment by pinzon** [comment]
Seems to me like every service that is using the `generic_proxy.serve_flask_app` function is quieting the logs in 2 levels: 

- In the [function itself](https://github.com/localstack/localstack/blob/cf3d1f704b7c583da9f17a9016df9156032fc4d8/localstack/services/generic_proxy.py#L440), the default is to quiet the logs 
- the service that calls this method, also defaults to quiet the logs, [example](https://github.com/localstack/localstack/blob/cf3d1f704b7c583da9f17a9016df9156032fc4d8/localstack/services/awslambda/lambda_api.py#L2008)

So if you start localstack with any service that starts with that function (like lambda, firehose, etc) the logs will dissapear.

I think a fix could be to replace all `quiet=True` for  `quiet=None`  and in the method, assert that if the passed value is None, use the inverse of `config.DEBUG` like this:

I'll make a PR with this in mind.
