### ISSUE TITLE
Reject AWS S3 requests missing Content-MD5 header when object lock is enabled

### ISSUE THREAD

**Issue by jszwedko** [localstack/localstack#4166]
# Type of request: This is a ...

[ ] bug report
[x] feature request

# Detailed description

We had a user [report an issue](https://github.com/timberio/vector/issues/7310) on a project I work on where it couldn't write to S3 if object lock was enabled because the requests were missing the `Content-MD5` header. I went to add a test for this before modifying the implementation, but found that localstack does not enforce this same restriction.

## Expected behavior

localstack rejects AWS S3 object put requests when object lock is enabled and the request is lacking the `Content-MD5` header.

## Actual behavior

localstack accepts the object write without the `Content-MD5` header.

# Steps to reproduce

I'll link to the test I am writing once I push it.

## Command used to start LocalStack

```
  docker run -d --network=vector-test-integration-aws --name vector_localstack_aws \  -p 4566:4566 -p 4571:4571 \  -e SERVICES=kinesis,s3,cloudwatch,elasticsearch,es,firehose,sqs \  localstack/localstack-full:0.11.6
```

**Comment by pinzon** [comment]
Hi @jszwedko thank you for your patience.
I've been triaging this problem since yesterday and after understanding how s3 object lock works, I think the moto project doesn't support the feature.

I'm currently working in a solution. thinking maybe just add a flag that object lock is enabled and the key_put response should enforce the content-md5 header.

**Comment by pinzon** [comment]
Hi, @jszwedko the feature Object Lock was recently merged into moto, I made sure to include a simple validation that the Content-Md5 header exists in the requests that include an object-lock parameter or if the bucket has a default lock configuration.

Hopefully you'll see the changes soon in Localstack.
