### ISSUE TITLE
PIP version of localstack doesn't start in host mode (no swf service)

### ISSUE THREAD

**Issue by egobrain** [localstack/localstack#4181]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

swf service files doesn't exists in pip version 
If you download localstack via pip

pip install localstack

or 

pip install localstack[full]

and run it in host mode

localstack start --host

it fails

...

## Expected behavior

localstack successfully started in host mode

...

## Actual behavior

2021-06-21T13:55:19:WARNING:bootstrap.py: Unable to load plugins from file /home/venv/lib/python3.7/site-packages/localstack/plugins.py: No module named 'localstack.services.swf'

...

# Steps to reproduce

pip install localstack==0.12.12

localstack start --host

## Command used to start LocalStack

localstack start --host

...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

...

**Comment by whummer** [comment]
Thanks for reporting @egobrain . Looks like we had an `__init__.py` file missing in the swf folder. This should be fixed in the meantime - can you please try again with the `0.12.13` version on pypi? Please let us know if the problem persists. Thanks!
