### ISSUE TITLE
Switch from using "docker" CLI to Docker Python client for running Lambda containers

### ISSUE THREAD

**Issue by whummer** [localstack/localstack#4182]
Switch from using `docker` CLI to Docker Python client for running Lambda containers.

Currently, we're using `docker` shell commands in various places in the code base. In an effort to reduce the number of shell calls (mostly for security reasons), we should replace any `docker` commands with the corresponding Docker Python library commands.

The ultimate goal would be to strip out the `docker` binary from the container - which will save us another ~60MB of disk space in the final image.

**Comment by dfangl** [comment]
This is already implemented :)
