### ISSUE TITLE
cloudtrail command get-trail fails with 500 (pro version)

### ISSUE THREAD

**Issue by mummoo** [localstack/localstack#4199]
# Type of request: This is a ...

[X] bug report
[ ] feature request

# Detailed description

Bring up the localstack pro version with cloudtrail enabled.

If you run the "describe-trails" command, it returns the list. However, if you run "awslocal cloudtrail  get-trail" with a cloudtrail name that doesn't exist, it throws 500 as follows. Note that this command works well if the cloudtrail exists with this name.

Against real AWS, we get the following:
   An error occurred (TrailNotFoundException) when calling the GetTrail operation: Unknown trail..

bash-5.0# awslocal cloudtrail describe-trails
{
    "trailList": []
}
bash-5.0# awslocal cloudtrail  get-trail --name test
An error occurred (500) when calling the GetTrail operation (reached max retries: 4): <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>

## Expected behavior

return:
 An error occurred (TrailNotFoundException) when calling the GetTrail operation: Unknown trail
...

## Actual behavior
500 error in localstack
...

# Steps to reproduce
Bring up localstack pro version.

run. "awslocal cloudtrail  get-trail --name test".

## Command used to start LocalStack
docker-compose up
...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

...

**Comment by whummer** [comment]
Thanks for reporting @mummoo . This should be fixed in the meantime - can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists. Thanks for your help!
