### ISSUE TITLE
Can I use route53 service as local dns ?

### ISSUE THREAD

**Issue by odedpriva** [localstack/localstack#420]
For lack of a better place, I'm asking it here. 

Can I use localstack route53 service as a local DNS server ?

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-302) by [Unito](https://www.unito.io/learn-more)

**Comment by ashu2108** [comment]
is this feature still missing? on the localstack

**Comment by jonathan-wylie** [comment]
It would be nice to get an answer for this. I can see that some of route53 is supported, I can create hosted zones etc. I can't see if there is a way for localstack to use that config as a local dns server. It would be really good if it could. Maybe the pro version can? It does at least have a dns server I think.

**Comment by tylerauerbeck** [comment]
@whummer Any update here?

**Comment by whummer** [comment]
Hi @ashu2108  @jonathan-wylie @tylerauerbeck apologies for the delay - yes, this feature is available in the Pro version, which provides a built-in DNS server that is capable of serving DNS responses based on the record sets stored in Route53. Hope that helps - please keep us posted if there are any questions or issues.. Thanks!
