### ISSUE TITLE
S3 "x-amz-bucket-region" header is missing

### ISSUE THREAD

**Issue by wvargas-ods** [localstack/localstack#4205]
# Type of request: S3 "x-amz-bucket-region" header is missing

[ ] bug report
[x] feature request

# Detailed description
I'm using the Net::Amazon::S3 library in Perl, and I can't list the items from a S3 bucket because localstack is not returning the header "x-amz-bucket-region":

https://metacpan.org/dist/Net-Amazon-S3/source/lib/Net/Amazon/S3/Bucket.pm#L390

...

## Expected behavior

Return the x-amz-bucket-region header

...

## Actual behavior

No header

...

# Steps to reproduce

https://metacpan.org/pod/Net::Amazon::S3#SYNOPSIS

**Comment by wvargas-ods** [comment]
More info about the x-amz-bucket-region header: https://docs.aws.amazon.com/en_us/AmazonS3/latest/API/API_HeadBucket.html

**Comment by wvargas-ods** [comment]
Thank you @rezafuru for working on this issue, I'll test it on my project ASAP 😄

**Comment by rezafuru** [comment]
Happy to  hear,  :smile: ! Please let me know whether it solved your problem once you've tested it

**Comment by wvargas-ods** [comment]
It worked like a charm, thank you @rezafuru 💯
