### ISSUE TITLE
Feature request: Lambda container reuse.

### ISSUE THREAD

**Issue by vangorra** [localstack/localstack#421]
A nice feature to add would be the reuse of lambda containers. Currently, it appears localstack will create the container, run the lambda, then remove the container. This results in a fair amount of overhead each time a lambda executes. By keeping the container alive, it would make subsequent calls much faster.  Some sort of TTL would need to be written to expire the container after a certain amount of inactivity.

This would also be consistent with how AWS manages lambda containers. They refer to it as a freeze, thaw. https://docs.aws.amazon.com/lambda/latest/dg/lambda-introduction.html

**Comment by whummer** [comment]
This would certainly be a great improvement @vangorra . Given the current backlog of bugs/issues, I don't think we can treat it as a priority, though. But I'd be more than happy to accept a PR if you're able to spike out an initial solution? Thanks

**Comment by vangorra** [comment]
Understood. I'll poke around a bit.

**Comment by vangorra** [comment]
FYI. My original PR has been subsumed by #443

**Comment by whummer** [comment]
Fixed in #443 . Thanks again @vangorra !
