### ISSUE TITLE
question: AWS Lambda + S3 + SNS

### ISSUE THREAD

**Issue by sergey-morenets** [localstack/localstack#4238]
### Is there an existing issue for this?

- [X] I have searched the existing issues and read the documentation

### Question

Hi

Is the following use-case supported by LocalStack? It's possible in real AWS environment but I couldn't find any mentioning in the documentation/examples of LocalStack.

1) Create AWS Lambda
2) Create S3 Bucket
3) Create SNS topic
4) Configure SNS topic so that each new upload to S3 bucket will produce new message to SNS topic that will trigger AWS Lambda execution.

Thanks, Sergit

**Comment by mgagliardo** [comment]
Hello @sergey-morenets, yes that usecase is supported, even if it is not the same (SNS functionality is missing) [here](https://github.com/localstack/localstack/issues/3183) you can find a usecase for s3 reporting to lambda, and [here](https://github.com/localstack/localstack/issues/4086) there's a usecase for sns subscription to a specific SQS topic, same should work for S3 and lambda.

I have not gone through all the issues, but you should definitely give a try to this and let us know if you have any issues!

Cheers

**Comment by sergey-morenets** [comment]
Hi @mgagliardo 

Thank you for the quick response. I just tested this use-case and it seemed not working correctly (or not supported). Can you please check that? So the steps to reproduce are:

1) Create S3 bucket: aws s3 mb s3://mybucket --endpoint-url http://localhost:4566
2) Create SNS topic: aws sns create-topic --name mytopic --endpoint-url=http://localhost:4566
3) Specify SNS topic as a destination for S3 event notifications: aws s3api put-bucket-notification-configuration --endpoint-url http://localhost:4566 --bucket mybucket --notification-configuration file://notification.json
4) Print S3 notification configuration: aws s3api get-bucket-notification-configuration --bucket mybicket --endpoint-url http://localhost:4566

And the list of configurations is empty. If I specify AWS Lambda as destination for S3 events then **aws s3api get-bucket-notification-configuration** command will print configurations and S3 events will reach AWS Lambda.

notification.json:

```
{
  "TopicConfigurations": [
    {
      "Id": "1234567890110",
      "TopicArn": "arn:aws:sns:us-east-1:000000000000:mytopic",
      "Events": [
        "s3:ObjectCreated:*"
      ]
    }
  ]
}
```

**Comment by sergey-morenets** [comment]
Yes, I just re-tested it again and it works fine now. Probably some misspelling during the first test.
The only thing I didn't know is that  _aws s3api put-bucket-notification-configuration_ command **replaces** existing configuration. I thought it appended new configurations.

**Comment by mgagliardo** [comment]
Glad it worked. And yes, that is correct, [put-bucket-notification-configuration](https://docs.aws.amazon.com/cli/latest/reference/s3api/put-bucket-notification-configuration.html) replaces the existing configuration. Cheers!
