### ISSUE TITLE
[PRO] Cognito not returning a scope

### ISSUE THREAD

**Issue by nadeem-clearaccept** [localstack/localstack#4242]
### Is there an existing issue for this?

- [X] I have searched the existing issues and read the documentation

### Question

How do I get Custom scopes to return when contacting the token endpoint?

### Anything else?

I have set up a Cognito with a user pool, user pool client, custom domain and resources and provided custom scopes to the user pool client. Event with all this, when I hit the custom domain URI to generate a token from the user pool client (https://localhost.localstack.cloud/oauth2/token) it creates me a JWT token but does not include the custom scopes.

I have attached the JSON for the User pool, client and domain. I have left out the resources since I used specific commands to create them but it should not be hard to re-create them based on the custom scope information on the User Pool Client.

[cognito-setup-json.zip](https://github.com/localstack/localstack/files/6747365/cognito-setup-json.zip)

**Comment by whummer** [comment]
Thanks for reporting @nadeem-clearaccept . This should be fixed in the meantime - can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists. Thanks for your help!
