### ISSUE TITLE
Cognito lambda trigger - name <function_name> is not defined in lambda when using persistence

### ISSUE THREAD

**Issue by yonatandbinahai** [localstack/localstack#4243]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When authenticating via Cognito with a Pre-authentication lambda (written in python) and using localstack persistence, the lambda fails with the following error.
Function `print_time` is a function that exists in the same uploaded file as the lambda handler.
Lambdas are configured to run in `local` mode.
When running without persistence, the lambda function execution succeeds.

```
{"__type": "InternalServerError", "message": "Error in Cognito action \"InitiateAuth\": Error running Cognito trigger
Lambda \"arn:aws:lambda:eu-west-1:000000000000:function:my-function\": b'{\"errorType\":
\"InvocationException\", \"errorMessage\": \"name \\'print_time\\' is not defined\", \"stackTrace\": [\" File
\\\\\"/opt/code/localstack/localstack/services/awslambda/lambda_api.py\\\\\", line 602, in run_lambda\\\\n result =
LAMBDA_EXECUTOR.execute(func_arn, func_details, event, context=context,\\\\n\", \" File
```

### Expected Behavior

Lambda function should execute successfully

### How are you starting LocalStack?

With a docker-compose file

## How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

docker-compose

## Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

InitiateAuth

### Environment

```markdown
- OS: Windows 10
- LocalStack: latest
```

### Anything else?

Relevant localstack configuration in `docker-compose` file:

```
    environment:
      - SERVICES=ssm,sqs,cognito-idp,iam,lambda
      - DATA_DIR=/tmp/localstack/data
      - LAMBDA_EXECUTOR=local
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
      - LOCALSTACK_API_KEY=<my_api_key>
      - DEFAULT_REGION=eu-west-1
      - LAMBDA_DOCKER_NETWORK=server_default
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

**Comment by giograno** [comment]
Hi @yonatandbinahai, thanks for reporting the issue. Unfortunately, I am picking this up after quite some time. Please excuse us 🙏 . Since **a lot** of things have changed (and very much improved!) in the meanwhile, I would ask you to update to the `latest` Docker image and give it another try. Thanks for your understanding!

**Comment by giograno** [comment]
Closing the issue. Feel free to reopen any time if the issue occurs again 🙏
