### ISSUE TITLE
Are Lambdas written in .NET Core supported?

### ISSUE THREAD

**Issue by mstepanyak** [localstack/localstack#425]

**Comment by whummer** [comment]
Hi @mstepanyak , unfortunately .Net Lambdas are currently not supported. We're using `lambci`'s Docker images for executing the Lambda code - they have an open issue there which you can follow: https://github.com/lambci/docker-lambda/issues/52

**Comment by DarriusWrightGD** [comment]
Now that .NET 2.0 is supported by lambci will you guys be adding support for localstack soon?

**Comment by hartmannr76** [comment]
[Working on it](https://github.com/localstack/localstack/pull/693)

**Comment by hartmannr76** [comment]
@whummer FYI, This can be closed with the merged PR
