### ISSUE TITLE
Using Other Items in the localstack

### ISSUE THREAD

**Issue by ssabnis** [localstack/localstack#426]
How do use SQS or Kinesis Stream in localstack, where I want listen to events from Kinesis by Lambda and store in S3, any examples.  Thanks

**Comment by whummer** [comment]
Hi @ssabnis . The examples in the integration tests should provide a good starting point: https://github.com/localstack/localstack/blob/master/tests/integration/test_integration.py#L189-L214 . There are also various excellent tutorials out there on how to write AWS applications using Kinesis, Lambda, S3, and other services. Providing a comprehensive answer to this question might be a bit out of scope for the LocalStack issue tracker.
