### ISSUE TITLE
Getting moto action not implemented for Autoscaling group

### ISSUE THREAD

**Issue by cbarmstrong** [localstack/localstack#4270]
Hi,

I'm receiving the following exception from moto when trying to deploy an autoscaling group and launch template:

`NotImplementedError: The enable_metrics_collection action has not been implemented`

I'm using terraform for the deployment and believe it's likely related to setting the enabled_metrics and metrics_granularity options on the aws_autoscaling_group resource. I see in the moto docs that this is listed as not yet implemented, but is there any workarounds or fixes imminent?

**Comment by whummer** [comment]
Thanks for reporting @cbarmstrong , and apologies for the long delay on this one. This should be fixed in the meantime - can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists. Thanks for your help!
