### ISSUE TITLE
bug: rusoto cloudformation describe-stacks response parse error

### ISSUE THREAD

**Issue by kshpytsya** [localstack/localstack#4271]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Rusoto (Rust) equivalent of `aws cloudformation describe-stacks` CLI command fails parsing the output:

```
thread 'tests::describe_stacks' panicked at 'called `Result::unwrap()` on an `Err` value: ParseError("Expected EndElement DescribeStacksResponse got Some(Ok(EndDocument))")', src/lib.rs:30:14
```

### Expected Behavior

Rusoto client should be able to successfully call the "describe-stacks" API.

### How are you starting LocalStack?

With a `docker run` command

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run --rm -it -p 4566:4566 localstack/localstack:latest

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    git clone https://github.com/kshpytsya/bug-rusoto-cloudformation-localstack
    cd bug-rusoto-cloudformation-localstack/
    AWS_ACCESS_KEY_ID=test AWS_SECRET_ACCESS_KEY=test AWS_DEFAULT_REGION=us-east-1 LOCALSTACK_ENDPOINT=http://localhost:4566 cargo t

### Environment

```markdown
- OS: Gentoo, Arch
- LocalStack: latest
```

### Anything else?

Not sure if this is related:

https://github.com/localstack/localstack/issues/3300

**Comment by dominikschubert** [comment]
Good news! :grin: 

This seems to have been fixed in the meantime using the newest LocalStack version.

![image](https://user-images.githubusercontent.com/620817/184385338-65cba740-ee4c-40cf-b142-363e0c42fdd4.png)
