### ISSUE TITLE
bug: Localstack with terraform sns + sqs subscription not working

### ISSUE THREAD

**Issue by pyaesone17** [localstack/localstack#4285]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have terraform module with sns and sqs, basically sqs is subscribing the topic of sns using resource "aws_sns_topic_subscription" block. But it is stuck at creating and resulting in error.

Error: waiting for SNS topic subscription m confirmation: timeout while waiting for state to become 'false' (timeout: 2m0s)

### Expected Behavior

It should be able to create subscription.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    terraform apply

### Environment

```markdown
- OS: Mac OS 10.15.3 - Catalina
- LocalStack: Latest image
```

### Anything else?

When I check on dashboard url, surprisingly sns is not created there too even though it is success in console

_No response_

**Comment by pyaesone17** [comment]
I checked by querying SNS and SQS and listing subscriptions, actually it is working but not sure why terraform apply stuck although resource creation is done !

That could be the reason "waiting for SNS topic subscription m confirmation: timeout while waiting for state to become 'false' "

**Comment by mgagliardo** [comment]
Hello @pyaesone17, could you please share your terraform code or an example? I am trying with the following and seems to work for me, my setup:

```
MacOS BigSur 11.4 (20F71)

Docker version 20.10.7, build f0df350 (installed via brew)

Localstack latest (running via docker)

Terraform v1.0.2
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.49.0
```

main.tf:
```
provider "aws" {
  region = "us-east-1"

  access_key = "test"
  secret_key = "test"

  s3_force_path_style         = true
  skip_credentials_validation = true
  skip_metadata_api_check     = true
  skip_requesting_account_id  = true

  endpoints {
    sns            = "http://localhost:4566"
    sqs            = "http://localhost:4566"
  }
}

resource "aws_sqs_queue" "queue" {
  name = "queue"
}

resource "aws_sns_topic" "topic" {
  name = "topic"
}

resource "aws_sns_topic_subscription" "subscription" {
  endpoint = aws_sqs_queue.queue.arn
  protocol = "sqs"
  topic_arn = aws_sns_topic.topic.arn
}
```

apply:
```
aws_sqs_queue.queue: Creating...
aws_sns_topic.topic: Creating...
aws_sns_topic.topic: Creation complete after 0s [id=arn:aws:sns:us-east-1:000000000000:topic]
aws_sqs_queue.queue: Creation complete after 0s [id=http://localhost:4566/000000000000/queue]
aws_sns_topic_subscription.subscription: Creating...
aws_sns_topic_subscription.subscription: Creation complete after 0s [id=arn:aws:sns:us-east-1:000000000000:topic:32668cbf-c762-4afb-a212-b23ba659e36f]

Apply complete! Resources: 3 added, 0 changed, 0 destroyed.
```

destroy:
```
aws_sns_topic_subscription.subscription: Destroying... [id=arn:aws:sns:us-east-1:000000000000:topic:32668cbf-c762-4afb-a212-b23ba659e36f]
aws_sns_topic_subscription.subscription: Destruction complete after 0s
aws_sqs_queue.queue: Destroying... [id=http://localhost:4566/000000000000/queue]
aws_sns_topic.topic: Destroying... [id=arn:aws:sns:us-east-1:000000000000:topic]
aws_sns_topic.topic: Destruction complete after 0s
aws_sqs_queue.queue: Destruction complete after 1s

Destroy complete! Resources: 3 destroyed.
```

**Comment by pyaesone17** [comment]
Hi @mgagliardo Thanks for your time, my terraform version is v0.13.5. Have a nice day !

**Comment by mgagliardo** [comment]
Hello @pyaesone17, same happens with 0.13.5, I am unable to reproduce it.
