### ISSUE TITLE
bug: SerializationError: failed decoding JSON RPC response\n\tstatus code: 200, request id: \ncaused by: parsing time 

### ISSUE THREAD

**Issue by nimar** [localstack/localstack#4286]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I call `CreateEventSourceMapping` between a lambda function and a queue I'm getting the following error:
```
SerializationError: failed decoding JSON RPC response\n\tstatus code: 200, request id: \ncaused by: parsing time \"2021-07-12T19:50:08.129+0000\" as \"2006-01-02T15:04:05.999999999Z\": cannot parse \"+0000\" as \"Z\"
```

### Expected Behavior

No error is expected. Note that the response shows that the underlying operation was successful the error was in serializing the response because the timestamp couldn't be parsed. This operation was working fine on the July 7 version.

### How are you starting LocalStack?

With a `docker run` command

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

I'm using the Go SDK to create a lambda function, a queue, and adding a mapping between the two.

### Environment

```markdown
- OS: Mac
- LocalStack: latest https://hub.docker.com/layers/localstack/localstack/latest/images/sha256-6d37f237f5aace6044d7419db2cb41e04ec3019c5159ae0276319c38f2c2e349?context=explore

Note: the problem doesn't appear in version 0.12.15 published on July 7.
```

### Anything else?

I believe the error was caused by this recent [commit](https://github.com/localstack/localstack/commit/01e81ec38bfc20e6598a98765538aee967aba8eb#diff-e814f546cf35a9785c661a31876d52e103af2726060066ca056771e672492d0aR251). cc @whummer 

Note that the timestamp has become `return isoformat_milliseconds(timestamp) + "+0000"` The error message clearly states that `cannot parse \"+0000\" as \"Z\"`

**Comment by wimax-grapl** [comment]
I can confirm this as well, just started happening with today's `latest`; going back to 0.12.15 does the trick. Thanks for submitting an issue!

**Comment by BGarber42** [comment]
I'm getting this for ELBs also

```
2021-07-16T12:27:18.125-0400 [INFO]  provider.terraform-provider-aws_v3.24.1_x5.exe: 2021/07/16 12:27:18 [DEBUG] [aws-sdk-go] <DescribeLoadBalancersResponse xmlns="http://elasticloadbalancing.amazonaws.com/d
oc/2012-06-01/"><DescribeLoadBalancersResult><LoadBalancerDescriptions><member><SecurityGroups></SecurityGroups><LoadBalancerName>Learn-ELB</LoadBalancerName><CreatedTime>2021-07-16T15:56:00.222661+00:00</Cr
eatedTime><HealthCheck></HealthCheck><VPCId>vpc-16614d95</VPCId><ListenerDescriptions><member><PolicyNames></PolicyNames><Listener><Protocol>HTTP</Protocol><LoadBalancerPort>80</LoadBalancerPort><InstancePro
tocol>HTTP</InstanceProtocol><InstancePort>8000</InstancePort><SSLCertificateId></SSLCertificateId></Listener></member></ListenerDescriptions><Instances></Instances><Policies><AppCookieStickinessPolicies></A
ppCookieStickinessPolicies><LBCookieStickinessPolicies></LBCookieStickinessPolicies><OtherPolicies></OtherPolicies></Policies><AvailabilityZones></AvailabilityZones><CanonicalHostedZoneName>Learn-ELB.us-east
-1.elb.amazonaws.com</CanonicalHostedZoneName><CanonicalHostedZoneNameID>Z3ZONEID</CanonicalHostedZoneNameID><Scheme>None</Scheme><DNSName>Learn-ELB.us-east-1.elb.amazonaws.com</DNSName><BackendServerDescrip
tions></BackendServerDescriptions><Subnets><member>subnet-d14818c6</member></Subnets></member></LoadBalancerDescriptions></DescribeLoadBalancersResult><ResponseMetadata><RequestId>f9880f01-7852-629d-a6c3-3ae
2-666a409287e6dc0c</RequestId></ResponseMetadata></DescribeLoadBalancersResponse>: timestamp=2021-07-16T12:27:18.125-0400
2021-07-16T12:27:18.125-0400 [INFO]  provider.terraform-provider-aws_v3.24.1_x5.exe: 2021/07/16 12:27:18 [DEBUG] [aws-sdk-go] DEBUG: Unmarshal Response elasticloadbalancing/DescribeLoadBalancers failed, atte
mpt 13/25, error SerializationError: failed decoding Query response
        status code: 200, request id:
caused by: parsing time "2021-07-16T15:56:00.222661+00:00" as "2006-01-02T15:04:05.999999999Z": cannot parse "+00:00" as "Z": timestamp=2021-07-16T12:27:18.125-0400

```

Using terraform.

**Comment by ackdav** [comment]
Hi @nimar - thank you for raising this issue! A lot of time has passed since this issue was raised and lambda went through numerous improvements... Could you update to the latest localstack version and double check whether this issue is still present?
Thanks!

**Comment by nimar** [comment]
Hi @ackdav, indeed a long time has passed. I am no longer working on that project so I don't have an environment to reproduce. Feel free to close the issue.

**Comment by ackdav** [comment]
Alright - thank you for the prompt answer @nimar :)
