### ISSUE TITLE
question: how can i get the message sent from SNS sms

### ISSUE THREAD

**Issue by osalas891123** [localstack/localstack#4288]
### Is there an existing issue for this?

- [X] I have searched the existing issues and read the documentation

### Question

how can i get the message sent from SNS sms. I need the real message for 2FA usage.

**Comment by mgagliardo** [comment]
Hello @osalas891123, as you can see on the documentation localstack is intended to be as a mock for AWS services, not a real one though.
That being said, there is no current way of sending a real SMS message as it would incur in actual carrier costs (or at least a SaaS like twilio). 
Let us know if there is anything we can help with. Cheers
