### ISSUE TITLE
Call to AmazonS3Util.DoesS3BucketExistV2Async comes back with no descript error

### ISSUE THREAD

**Issue by darren-uka2** [localstack/localstack#4289]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

A call is made to AmazonS3Util.DoesS3BucketExistV2Async(IAmazonS3 s3Client, string bucketName) method in the AWSDK library for C# and throws the error message 

"Error making request with Error Code NotFound and Http Status Code NotFound. No further error information was returned by the service."

I tried the same call to the live version of AWS and it worked with no issues

### Expected Behavior

I expect the call to check if a bucket exists or not on localstack

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal s3 mb s3://mybucket

### Environment

```markdown
- OS: Windows 10
- LocalStack: latest
```

**Comment by whummer** [comment]
Thanks for reporting @darren-uka2 . This should be fixed in #4315 - can you please pull the `latest` Docker image and give it another try? Please report here if the problem persists. Thanks!
