### ISSUE TITLE
question: how can i log to console/file the message sent from SNS sms

### ISSUE THREAD

**Issue by osalas891123** [localstack/localstack#4293]
### Is there an existing issue for this?

- [X] I have searched the existing issues and read the documentation

### Question

How can i log to console/file the message sent from SNS sms, not only the MessageId, the use case is i need to test 2FA code sent to mobile and now only the MessageId is shown.

**Comment by mgagliardo** [comment]
Hello @osalas891123 can you please elaborate a bit more? If I understand your use case correctly you need to send an SMS and you need to get the message (text) you are sending as well as the MessageID, is that correct?

```
$ awslocal sns create-topic --name test
{
    "TopicArn": "arn:aws:sns:us-east-1:000000000000:test"
}
```

```
$ awslocal sns subscribe --topic-arn arn:aws:sns:us-east-1:000000000000:test --protocol sms --notification-endpoint +15555551234
{
    "SubscriptionArn": "arn:aws:sns:us-east-1:000000000000:test:98c579a3-0aaf-4b00-988d-35ca16b16e6f"
}
```

```
$ awslocal sns publish --topic-arn arn:aws:sns:us-east-1:000000000000:test --message 'This is a test'
{
    "MessageId": "04ee1689-6f15-4b7c-befb-49a41763d640"
}
```

Localstack debug logs:
```
2021-07-14 10:29:54,531:API: 127.0.0.1 - - [14/Jul/2021 10:29:54] "POST / HTTP/1.1" 200 -
2021-07-14 10:29:55,448:API: 127.0.0.1 - - [14/Jul/2021 10:29:55] "POST / HTTP/1.1" 200 -
2021-07-14T10:30:27:DEBUG:localstack.services.sns.sns_listener: Publishing message to TopicArn: arn:aws:sns:us-east-1:000000000000:test | Message: This is a test
2021-07-14T10:30:27:INFO:localstack.services.sns.sns_listener: Delivering SMS message to +15555551234: This is a test
```

What is exactly that you need to get here?

**Comment by osalas891123** [comment]
Why the behaviour without using a topic is not the same. (ex. sending the message directly to a mobile phone number). It only log the MessageId

**Comment by mgagliardo** [comment]
Can you please elaborate a bit more? I might not be understanding your need. The MessageId is present when you publish a message to the topic and that is all you need.
