### ISSUE TITLE
bug: Terraform hangs while creating event source mapping in Localstack

### ISSUE THREAD

**Issue by keenan-v1** [localstack/localstack#4295]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We have a terraform script that sets up localstack and terraform is currently hanging on creating an event source mapping after today's docker image update (sha256:96bbe7cd1e5c63eb41fda7118c013f066d2711ab44bb417b29318dcca5931480). We've let it go for as long as 30 minutes. Localstack doesn't show anything in the container logs regarding any issues.

### Expected Behavior

It's expected that the event source mapping should create fairly quickly.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    `docker-compose.yaml`

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```
resource "aws_lambda_event_source_mapping" "lambda-event-source-mapping" {
  event_source_arn  = aws_sqs_queue.my_event_source.arn
  enabled           = true
  function_name     = aws_lambda_function.my_lambda.arn
  batch_size        = 1
}
```

### Environment

```markdown
- OS: debian buster
- LocalStack: latest on docker.io as of 2021-07-13
```

**Comment by keenan-v1** [comment]
Additional note: Rolling back to the 0.12.15 docker tag resolves the issue. That should narrow down what changed.

**Comment by josephpohlmann** [comment]
I've run into this too, running version 0.12.14 (and 0.12.12).  Running through terraform with TF_LOG turned up, I caught this:

```
2021-07-16T16:52:24.929-0400 [INFO]  provider.terraform-provider-aws_v3.50.0_x5: 2021/07/16 16:52:24 [DEBUG] [aws-sdk-go] {"BatchSize":1,"EventSourceArn":"arn:aws:sqs:us-west-2:000000000000:my_queue","FunctionArn":"arn:aws:lambda:us-west-2:000000000000:function:my_lambda","LastModified":"2021-07-16T20:52:24.953+0000","LastProcessingResult":"OK","StartingPosition":"LATEST","State":"Enabled","StateTransitionReason":"User action","UUID":"dee00b3e-b22b-459e-97b1-3960d8dd9425"}: timestamp=2021-07-16T16:52:24.929-0400
2021-07-16T16:52:24.929-0400 [INFO]  provider.terraform-provider-aws_v3.50.0_x5: 2021/07/16 16:52:24 [DEBUG] [aws-sdk-go] DEBUG: Unmarshal Response lambda/CreateEventSourceMapping failed, attempt 11/25, error SerializationError: failed decoding JSON RPC response
        status code: 200, request id: 
caused by: unable to parse time string, parse errors:
 * "2006-01-02T15:04:05.999999999Z": parsing time "2021-07-16T20:52:24.953+0000" as "2006-01-02T15:04:05.999999999Z": cannot parse "+0000" as "Z"
 * "2006-01-02T15:04:05.999999999Z07:00": parsing time "2021-07-16T20:52:24.953+0000" as "2006-01-02T15:04:05.999999999Z07:00": cannot parse "+0000" as "Z07:00"
 * "2006-01-02T15:04:05Z07:00": parsing time "2021-07-16T20:52:24.953+0000" as "2006-01-02T15:04:05Z07:00": cannot parse "+0000" as "Z07:00": timestamp=2021-07-16T16:52:24.929-0400
```

It appears that this may be due to timestamp formatting issues in lambda_api.py ??

**Comment by euadams** [comment]
Hello. I've run into this issue as well and my terraform log also produces something similar.

```
Error: error creating Lambda Event Source Mapping (arn:aws:sqs:us-east-1:000000000000:request-queue): SerializationError: failed decoding JSON RPC response
	status code: 200, request id: 
caused by: unable to parse time string, parse errors:
 * "2006-01-02T15:04:05.999999999Z": parsing time "2021-07-13T18:04:02.280+0000" as "2006-01-02T15:04:05.999999999Z": cannot parse "+0000" as "Z"
 * "2006-01-02T15:04:05.999999999Z07:00": parsing time "2021-07-13T18:04:02.280+0000" as "2006-01-02T15:04:05.999999999Z07:00": cannot parse "+0000" as "Z07:00"
 * "2006-01-02T15:04:05Z07:00": parsing time "2021-07-13T18:04:02.280+0000" as "2006-01-02T15:04:05Z07:00": cannot parse "+0000" as "Z07:00"
```

Any progress on this issue?

**Comment by pinzon** [comment]
I'm looking into this today. I've been really stuck with another patch. Thank you for your patience.

**Comment by pinzon** [comment]
@jrauen I've just seen that your second PR is having trouble with the tests? let me know if you need help or not. 
I'm currently working on other issues so it will take while to look into this one.
Thanks!

**Comment by jrauen** [comment]
This should be resolved in the latest build since the pull request #4323 was merged into master.

**Comment by pinzon** [comment]
@jrauen thank you!! 
I'm closing this issue then.
