### ISSUE TITLE
Start pip installed localstack detached

### ISSUE THREAD

**Issue by taormania** [localstack/localstack#430]
I'm working to get localstack to start by a script that will then run some other commands to setup the dependencies I'll be creating in localstack. Is there a detach command to not let the localstack startup interrupt the script?

**Comment by whummer** [comment]
Hi @taormania , if you run LocalStack in Docker, there is an (undocumented) feature to pass additional flags to `docker run`, which you can use to detach the container and run it in the background:
```
ENTRYPOINT=-d make docker-run
```

For running LocalStack in local mode on the host system (without Docker), there is currently no such option, but typically there should be an option to run the process in the background. Which programming language and command are you using to start LocalStack from your script?

**Comment by taormania** [comment]
That should work for me actually. Thanks!
