### ISSUE TITLE
bug: getting "bad escape \U at position 2 Traceback (most recent call last)" error whenever I try to invoke lambda

### ISSUE THREAD

**Issue by joffarex** [localstack/localstack#4300]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Whenever I invoke lambda either by CLI or from Step Functions, ANY lambda returns this error. This is the full JSON output of the response 

```json
{
  "errorMessage": "bad escape \\U at position 2",
  "errorType": "error",
  "stackTrace": [
    "  File \"/opt/code/localstack/localstack/services/awslambda/lambda_api.py\", line 739, in run_lambda\n    callback=callback,\n",
    "  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 224, in execute\n    return do_execute()\n",
    "  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 214, in do_execute\n    return _run(func_arn=func_arn)\n",
    "  File \"/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py\", line 157, in wrapped\n    raise e\n",
    "  File \"/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py\", line 153, in wrapped\n    result = func(*args, **kwargs)\n",
    "  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 201, in _run\n    raise e\n",
    "  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 189, in _run\n    result = self._execute(func_arn, func_details, event, context, version)\n",
    "  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 441, in _execute\n    cmd = self.prepare_execution(func_details, environment, command)\n",
    "  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 944, in prepare_execution\n    Util.get_host_path_for_path_in_docker(lambda_cwd),\n",
    "  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 1087, in get_host_path_for_path_in_docker\n    return re.sub(r\"^%s/(.*)$\" % config.TMP_FOLDER, r\"%s/\\1\" % config.HOST_TMP_FOLDER, path)\n",
    "  File \"/usr/lib/python3.7/re.py\", line 194, in sub\n    return _compile(pattern, flags).sub(repl, string, count)\n",
    "  File \"/usr/lib/python3.7/re.py\", line 311, in _subx\n    template = _compile_repl(template, pattern)\n",
    "  File \"/usr/lib/python3.7/re.py\", line 302, in _compile_repl\n    return sre_parse.parse_template(repl, pattern)\n",
    "  File \"/usr/lib/python3.7/sre_parse.py\", line 1018, in parse_template\n    raise s.error('bad escape %s' % this, len(this))\n"
  ]
}
```

And the lambda looks like this
```javascript
module.exports.handler = (event, context, callback) => {
  console.log("event", event);

  callback(null, { message: `test ${i}` });
}
```

### Expected Behavior

I expect lambda functions to run without any errors other than my own custom thrown ones.

### How are you starting LocalStack?

With the `localstack` script

### Steps To Reproduce

1. `docker run -it -e DEFAULT_REGION="eu-central-1" -e LAMBDA_REMOTE_DOCKER="false" -e TEST_AWS_ACCOUNT_ID="101010101010" -e LOCALSTACK_HOSTNAME="localhost" --rm --privileged --name localstack_main -p 4566:4566 -p 4571:4571  -v "C:\Users\{username}\AppData\Local\Temp\localstack:/tmp/localstack" -v "/var/run/docker.sock:/var/run/docker.sock" -e DOCKER_HOST="unix:///var/run/docker.sock" -e HOST_TMP_FOLDER="C:\Users\{username}\AppData\Local\Temp\localstack" "localstack/localstack"` replace `{username}` with your actual user.
2. Deploy provided lambda with `serverless.yml` 
3. `awslocal lambda invoke --function-name <name> <output-file-name>`

### Environment

```markdown
- OS: Windows 10 Enterprise 2004 Build 19041.630
- LocalStack: latest
```

**Comment by mgagliardo** [comment]
Hello @joffarex, I do not know what your username is (would be good to know if it has spaces between or not) but you can see the actual error is this:

```
  "errorMessage": "bad escape \\U at position 2",
```

Coming from:

```
    "  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 1087, in get_host_path_for_path_in_docker\n    return re.sub(r\"^%s/(.*)$\" % config.TMP_FOLDER, r\"%s/\\1\" % config.HOST_TMP_FOLDER, path)\n",
```

Which means there's a problem with the way you are mounting your `HOST_TMP_FOLDER` directory,

Can you try escaping all the backward slashes when you pass the arguments? For example, something like this:
```
-v "C:\\Users\\{username}\\AppData\\Local\\Temp\\localstack:/tmp/localstack"

-e HOST_TMP_FOLDER="C:\\Users\\{username}\\AppData\\Local\\Temp\\localstack"
```

**Comment by joffarex** [comment]
@mgagliardo Thanks for answer. my actual username is this `Tornike_Goshadze` so it has no spaces in it, but yeah I'll defenetly try to escape them and will reply with an answer. have not thought about it. Thanks

**Comment by joffarex** [comment]
Thanks. escaping all backward slashes fixed the problem. closing this.
