### ISSUE TITLE
bug: : Creating Lambda Function with dependencies error updating permissions as file is currently not readable

### ISSUE THREAD

**Issue by jericopulvera** [localstack/localstack#4304]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

51:39:INFO:localstack.utils.common: Updating permissions as file is currently not readable: /tmp/localstack/zipfile.525d9443/index.js

### How are you starting LocalStack?

With a `docker run` command

### Steps To Reproduce

ENDPOINT_URL="http://localhost:4566"

zip function.zip -r function

aws --endpoint-url="$ENDPOINT_URL" lambda create-function \
--function-name "testFunction" \
--zip-file "fileb://testfunction.zip" \
--handle "index.handler" \
--runtime "nodejs14.x" \
--role r1;

### Environment

```markdown
- OS: macOS 11.1
- LocalStack: latest
```

### Anything else?

I can create a function if it's just a single js file.

**Comment by mgagliardo** [comment]
Hello @jericopulvera can you please share your code and the commands you are running so I can test it properly? For example besides the create function, are you invoking it in any particular way?

Thanks

**Comment by jericopulvera** [comment]
I haven't been able to create the function.

> Hello @jericopulvera can you please share your code and the commands you are running so I can test it properly? For example besides the create function, are you invoking it in any particular way? Also please share how are you running localstack?
> 
> Thanks

**Comment by mgagliardo** [comment]
Ok, so what is the code for your function, how are you zipping it, etc?

**Comment by jericopulvera** [comment]
> Ok, so what is the code for your function, how are you zipping it, etc?


function/index.js
```
"use strict";

exports.handler = async (event, context) => {
  return `Successfully processed  records.`;
};

```

```sh
zip -r testfunction.zip function
```

```sh
aws --endpoint-url="http://localhost:4566" lambda create-function
--function-name "testFunction"
--zip-file "fileb://testfunction.zip"
--handle "test.handler"
--runtime "nodejs14.x"
--role r1;
```

**Comment by jericopulvera** [comment]
none directory zip gets created properly.

test.js
```
"use strict";

exports.handler = async (event, context) => {
  return `Successfully processed  records.`;
};

```

```sh
zip test.zip test.js
```

```sh
aws --endpoint-url="http://localhost:4566" lambda create-function \
--function-name "testFunction" \
--zip-file "fileb://test.zip" \
--handle "test.handler" \
--runtime "nodejs14.x" \
--role r1;
```

**Comment by jericopulvera** [comment]
> > Ok, so what is the code for your function, how are you zipping it, etc?
> 
> function/index.js
> 
> ```
> "use strict";
> 
> exports.handler = async (event, context) => {
>   return `Successfully processed  records.`;
> };
> ```
> 
> ```shell
> zip -r testfunction.zip function
> ```
> 
> ```shell
> aws --endpoint-url="http://localhost:4566" lambda create-function \
> --function-name "testFunction2" \
> --zip-file "fileb://testfunction.zip" \
> --handle "index.handler" \
> --runtime "nodejs14.x" \
> --role r1;
> ```
> 
> Output
> 
> ```
> An error occurred (InternalFailure) when calling the CreateFunction operation (reached max retries: 2): Unknown error: [Errno 2] No such file or directory: '/tmp/localstack/zipfile.5594be20/index.js' Traceback (most recent call last):
>   File "/opt/code/localstack/localstack/utils/common.py", line 835, in ensure_readable
>     with open(file_path, "rb"):
> FileNotFoundError: [Errno 2] No such file or directory: '/tmp/localstack/zipfile.5594be20/index.js'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 1291, in create_function
>     result = set_function_code(func_details.code, lambda_name)
>   File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 929, in set_function_code
>     run_for_max_seconds(25, _set_and_configure)
>   File "/opt/code/localstack/localstack/utils/common.py", line 1577, in run_for_max_seconds
>     raise result
>   File "/opt/code/localstack/localstack/utils/common.py", line 1558, in _worker
>     fn_result = _function(*args, **kwargs)
>   File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 925, in _set_and_configure
>     lambda_handler = do_set_function_code(code, lambda_name, lambda_cwd=lambda_cwd)
>   File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 1034, in do_set_function_code
>     ensure_readable(main_file)
>   File "/opt/code/localstack/localstack/utils/common.py", line 839, in ensure_readable
>     os.chmod(file_path, default_perms)
> FileNotFoundError: [Errno 2] No such file or directory: '/tmp/localstack/zipfile.5594be20/index.js'
> ```
> 
> ![image](https://user-images.githubusercontent.com/23246308/125646893-57971db3-3aae-407c-88be-d81c5ca32eac.png)

@mgagliardo I added the error logs. hope it helps.

**Comment by mgagliardo** [comment]
Can you please elaborate a bit more what is the problem? I am doing exactly the same as you and I am seeing the output correctly.

test.js:
```
"use strict";

exports.handler = async (event, context) => {
  console.log("This is a test");
  return `Successfully processed  records.`;
};
```

Create/Invoke:
```
$ zip -r testfunction.zip test.js

$ awslocal lambda create-function  --function-name "testFunction"  --zip-file "fileb://testfunction.zip"  --handle "test.handler"  --runtime "nodejs14.x"  --role r1;
{
    "FunctionName": "testFunction",
    "FunctionArn": "arn:aws:lambda:us-east-1:000000000000:function:testFunction",
    "Runtime": "nodejs14.x",
    "Role": "r1",
    "Handler": "test.handler",
    "CodeSize": 523,
    "Description": "",
    "Timeout": 3,
    "LastModified": "2021-07-14T15:15:03.269+0000",
    "CodeSha256": "V+m0kHjaTVuVGqF+eUc9rBF3TlsOZK3nI1/PMihTRyE=",
    "Version": "$LATEST",
    "VpcConfig": {},
    "TracingConfig": {
        "Mode": "PassThrough"
    },
    "RevisionId": "d6c37a6d-05c7-4513-a38b-d5910fa69bf8",
    "State": "Active",
    "LastUpdateStatus": "Successful",
    "PackageType": "Zip"
}

$ awslocal lambda invoke --function-name testFunction test.json
{
    "StatusCode": 200,
    "LogResult": "",
    "ExecutedVersion": "$LATEST"
}
```

Localstack DEBUG logs (set with `-e DEBUG=1`):
```
2021-07-14T15:15:09:INFO:localstack.services.awslambda.lambda_executors: node -e 'require("/tmp/localstack/zipfile.02b43533/test.js").handler({},{"function_name": "testFunction", "function_version": "$LATEST", "client_context": null, "invoked_function_arn": "arn:aws:lambda:us-east-1:000000000000:function:testFunction", "cognito_identity": null, "aws_request_id": "cad39d30-0336-4f94-8381-f1824181f889", "memory_limit_in_mb": 1536, "log_group_name": "/aws/lambda/testFunction", "log_stream_name": "2021/07/14/[1]8b67fb44"})'
2021-07-14T15:15:09:DEBUG:localstack.services.awslambda.lambda_executors: Lambda arn:aws:lambda:us-east-1:000000000000:function:testFunction result / log output:

This is a test
>
2021-07-14 15:15:09,709:API: 127.0.0.1 - - [14/Jul/2021 15:15:09] "POST / HTTP/1.1" 200 -
2021-07-14 15:15:09,728:API: 127.0.0.1 - - [14/Jul/2021 15:15:09] "POST / HTTP/1.1" 200 -
```

Output file `test.json`:
```
This is a test
```

**Comment by jericopulvera** [comment]
@mgagliardo Move the test.js inside a folder and zip that folder and use that zip to create the function.

**Comment by jericopulvera** [comment]
@mgagliardo you can refer to this

https://docs.aws.amazon.com/lambda/latest/dg/nodejs-package.html

**Comment by mgagliardo** [comment]
Sure, here you go:

```
$ cat index.js
"use strict";

exports.handler = async (event, context) => {
  require("bryan");
  return `Successfully processed  records.`;
};
```

```
$ cat node_modules/bryan/index.js
console.log("This is a demo")
```

```
$ tree
.
├── index.js
├── node_modules
│   └── bryan
│       └── index.js
├── test.json
└── testfunction.zip
```

```
$ zip -r testfunction.zip .

$ awslocal lambda create-function   --function-name "testFunction"   --zip-file "fileb://testfunction.zip"   --handle "index.handler"   --runtime "nodejs14.x"   --role r1
{
    "FunctionName": "testFunction",
    "FunctionArn": "arn:aws:lambda:us-east-1:000000000000:function:testFunction",
    "Runtime": "nodejs14.x",
    "Role": "r1",
    "Handler": "index.handler",
    "CodeSize": 809,
    "Description": "",
    "Timeout": 3,
    "LastModified": "2021-07-14T15:34:32.318+0000",
    "CodeSha256": "JGpRG6Q6q1I8bXgBaOvP6K0TYTdIsojJoj4G5PT69wo=",
    "Version": "$LATEST",
    "VpcConfig": {},
    "TracingConfig": {
        "Mode": "PassThrough"
    },
    "RevisionId": "4a1cde12-ea87-436a-a3aa-21b6ca23c3aa",
    "State": "Active",
    "LastUpdateStatus": "Successful",
    "PackageType": "Zip"
}

$ awslocal lambda invoke --function-name testFunction test.json
{
    "StatusCode": 200,
    "LogResult": "",
    "ExecutedVersion": "$LATEST"
}
```

Output:
```
2021-07-14 15:34:32,821:API: 127.0.0.1 - - [14/Jul/2021 15:34:32] "POST /2015-03-31/functions HTTP/1.1" 200 -
2021-07-14T15:34:36:INFO:localstack.services.awslambda.lambda_executors: node -e 'require("/tmp/localstack/zipfile.e74e8cd2/index.js").handler({},{"function_name": "testFunction", "function_version": "$LATEST", "client_context": null, "invoked_function_arn": "arn:aws:lambda:us-east-1:000000000000:function:testFunction", "cognito_identity": null, "aws_request_id": "192b99ca-e204-4157-af9e-f7c9ffcd02a6", "memory_limit_in_mb": 1536, "log_group_name": "/aws/lambda/testFunction", "log_stream_name": "2021/07/14/[1]72bc0cb6"})'
2021-07-14T15:34:36:DEBUG:localstack.services.awslambda.lambda_executors: Lambda arn:aws:lambda:us-east-1:000000000000:function:testFunction result / log output:
This is a demo
>
```

You can refer to [this example](https://aws.amazon.com/blogs/compute/nodejs-packages-in-lambda/)

I am closing this as it is a user issue unrelated to localstack.

**Comment by jericopulvera** [comment]
@mgagliardo 

![image](https://user-images.githubusercontent.com/23246308/125652840-18da6cda-f4eb-41ec-83c6-809dfba03c33.png)

In my local a simple index.js inside a directory that is zipped returns permissions errors. please look at the screenshot.

**Comment by mgagliardo** [comment]
Have you tried what I pasted above? Can you show me your directory structure?

**Comment by jericopulvera** [comment]
![image](https://user-images.githubusercontent.com/23246308/125653547-7db5e5ad-5501-4e4a-8eb3-7ed24161a6f0.png)

index.js
```js
"use strict";

exports.handler = async (event, context) => {
  return `Successfully processed  records.`;
};

```

**Comment by mgagliardo** [comment]
Please note you `should not` zip `the folder` but the files inside it, example:

This will `not work`:
```
zip -r function.zip myfolder/
```

This `will` work:
```
cd myfolder
zip -r function.zip .
```

**Comment by jericopulvera** [comment]
> Please note you `should not` zip `the folder` but the files inside it, example:
> 
> This will `not work`:
> 
> ```
> zip -r function.zip myfolder/
> ```
> 
> This `will` work:
> 
> ```
> cd myfolder
> zip -r function.zip .
> ```

Missed that little detail. Thanks for the help.

**Comment by mgagliardo** [comment]
Great you could solve it mate. Cheers
