### ISSUE TITLE
bug: Route53 zone vpc associations do not persist

### ISSUE THREAD

**Issue by jrauen** [localstack/localstack#4312]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When associating a route53 hosted zone with a VPC, the association does not persist.

### Expected Behavior

Subsequent calls to get-hosted-zone should show the VPC association config.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker-compose up localstack

```
version: "3.3"
services:
  localstack:
    image: localstack/localstack
    environment:
      HOSTNAME: "localstack"
      HOSTNAME_EXTERNAL: "localstack"
      SERVICES: "sts,route53,iam,elb,acm,ec2,efs"
      LOCALSTACK_API_KEY: ${LOCALSTACK_API_KEY}
      DEBUG: 1
    ports:
      - "443:443"
      - "4566:4566"
      - "4571:4571"
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```
> awslocal route53 associate-vpc-with-hosted-zone --hosted-zone-id "KEHOISS658KE87K"  --vpc "VPCRegion=us-west-2,VPCId=vpc-6589e232"
{
    "ChangeInfo": {
        "Id": "efe11a97",
        "Status": "INSYNC",
        "SubmittedAt": "2021-07-16T19:35:33.461000+00:00"
    }
}
> awslocal route53 get-hosted-zone --id KEHOISS658KE87K
{
    "HostedZone": {
        "Id": "/hostedzone/KEHOISS658KE87K",
        "Name": "example.com.",
        "Config": {
            "Comment": "Managed by Terraform",
            "PrivateZone": false
        },
        "ResourceRecordSetCount": 0
    },
    "DelegationSet": {
        "NameServers": [
            "dns.localhost.localstack.cloud"
        ]
    }
}

```

### Environment

```markdown
- OS: Windows 10
- LocalStack: `754a96b122ec`
```

**Comment by whummer** [comment]
Thanks for reporting @jrauen , and apologies for the long delay on this one. This issue should be fixed in the meantime (via #5118) - can you please pull the `latest` Docker image and give it another try? Please keep us posted how it goes.. Thanks!
