### ISSUE TITLE
question: How to configure localstack to only use a named profile

### ISSUE THREAD

**Issue by travis-jorge** [localstack/localstack#4331]
### Is there an existing issue for this?

- [X] I have searched the existing issues and read the documentation

### Question

I have seen examples of where aws configure localstack is used to configure a localstack profile but I don't see how localstack knows to use this profile over the default profile. Can someone point me in the right direction on how to use the docker-compose with a named profile?

**Comment by mgagliardo** [comment]
Hello @travis-jorge, if I understand correctly what you need is to specify the aws access key and secret access key to use against localstack? Can you explain a it more what would be your usecase? Thanks!

**Comment by travis-jorge** [comment]
@mgagliardo  my fault after some more digging and experimentation I realized my understanding of how loclastacks works was flawed. Thanks for getting back to me. I thought you needed to give localstack specific credentials to pass to docker which is not the case. You can close this thank you agian.
