### ISSUE TITLE
bug: S3 PutObject event does not match EventBridge rule

### ISSUE THREAD

**Issue by braden-unearth** [localstack/localstack#4332]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

PutObject operations in s3 create an event in EventBridge. These events fail to match event bridge rules which match a specified bucket. 

The a rule which looks like this:
```
{
    "source": ["aws.s3"],
    "detail-type":["AWS API Call via CloudTrail"],
    "detail":{
        "eventSource":["s3.amazonaws.com"],
        "eventName":["PutObject"],
        "requestParameters":{
            "bucketName":["myBucket"]
        }
    }
}
```
Should match any PutObject event in the `myBucket` bucket.

The event detail in localstack looks like the following:
```{
    "eventVersion": "1.05",
    "userIdentity": {
        "type": "Root",
        "principalId": "000000000000",
        "arn": "arn:aws:iam::000000000000:root",
        "accountId": "000000000000",
        "accessKeyId": "ABCTEST0000000123",
        "sessionContext": {
            "attributes": {
                "mfaAuthenticated": "false",
                "creationDate": "2021-07-20T22:52:08.333Z"
            }
        }
    },
    "eventTime": "2021-07-20T22:52:08.333Z",
    "eventSource": "s3.amazonaws.com",
    "eventName": "PutObject",
    "awsRegion": "us-west-2",
    "sourceIPAddress": "1.2.3.4",
    "userAgent": "console.amazonaws.com",
    "requestParameters": {},
    "responseElements": {},
    "requestID": "df8c54a9-5680-4af5-ac96-37e097ae5b0a",
    "eventID": "49833047-0f1f-49cd-94dc-f7babac00ba9",
    "eventType": "AwsApiCall",
    "readOnly": true,
    "recipientAccountId": "000000000000"
}
```
As you can see the property `requestParameters` is empty. 

### Expected Behavior

The event should contain all of the pertinent details so that EventBridge rule matching works as expected.

In this specific case the event should have a property `requestParameters`:
```
"requestParameters": {
    "legal-hold": "",
    "bucketName": "myBucket",
    "key": "test_image.jpg"
}
```

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker-compose up 

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)
    
    awslocal s3 mb s3://mybucket
    awslocal events put-rule --name testRule --event-pattern '{ "source": ["aws.s3"], "detail-type":["AWS API Call via CloudTrail"], "detail":{ "eventSource":["s3.amazonaws.com"], "eventName":["PutObject"], "requestParameters":{ "bucketName":["mybucket"] } } }'
    awslocal s3 cp test_image.jpg s3://mybucket/test_image.jpg
  

Then look at the event history at https://app.localstack.cloud/resources/trail
The PutObject event is displayed and the event details will contain an empty requestParameters attribute.

### Environment

```markdown
- OS: Mac OSX 11.4
- LocalStack Image: 6d214ec60265
```

**Comment by whummer** [comment]
Hi @braden-unearth , apologies for the super long delay on this one. This issue should be (hopefully) fixed in the meantime (`requestParameters` should now be propagated on S3 CloudTrail update events). Can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists - we'll be happy to dig into it in more detail in that case. Thanks for your help!
