### ISSUE TITLE
QLDB: Unable to execute query: near "CREATE": syntax error", "__type": "BadRequestException"}

### ISSUE THREAD

**Issue by sub007** [localstack/localstack#4334]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

An update query results in Badrequest exception.

localstack_main | 2021-07-21T17:04:51:DEBUG:localstack.services.edge: IN(qldb): "POST /" - headers: {'Remote-Addr': '172.17.0.1', 'Host': 'localhost', 'User-Agent': 'QLDB Driver for Golang v1.1.1 aws-sdk-go/1.39.4 (go1.14; linux; amd64)', 'Content-Length': '233', 'Authorization': 'AWS4-HMAC-SHA256 Credential=test/20210721/us-east-1/qldb/aws4_request, SignedHeaders=content-length;content-type;host;x-amz-date;x-amz-target, Signature=0f2b8e452f5e25861c77808337209b2e520a09fe8197192052ea81961de93850', 'Content-Type': 'application/x-amz-json-1.0', 'X-Amz-Date': '20210721T170451Z', 'X-Amz-Target': 'QLDBSession.SendCommand', 'Accept-Encoding': 'gzip', 'X-Forwarded-For': '172.17.0.1, localhost', 'x-localstack-edge': 'https://localhost'} - data: b'{"ExecuteStatement":{"Parameters":[{"IonBinary":"4AEA6iFA"},{"IonBinary":"4AEA6oRKb2hu"}],"Statement":"**UPDATE People SET age = ? WHERE firstName = ?**","TransactionId":"transaction-4ce6fa22-62aff762"},"SessionToken":"session-e8004432"}'

localstack_main | 2021-07-21T17:04:51:WARNING:localstack_ext.services.qldb.qldb_api: Unable to execute query: near "CREATE": syntax error Traceback (most recent call last):
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/localstack_ext/services/qldb/qldb_api.py", line 221, in send_command
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/localstack_ext/services/qldb/qldb_api.py", line 95, in execute_statement
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/localstack_ext/services/qldb/partiql.py", line 52, in run_query
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/localstack_ext/services/qldb/partiql.py", line 174, in run_query_update
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/localstack_ext/services/qldb/partiql.py", line 95, in run_query_over_json
localstack_main | sqlite3.OperationalError: near "CREATE": syntax error
localstack_main |
localstack_main | 2021-07-21 17:04:51,315:API: 127.0.0.1 - - [21/Jul/2021 17:04:51] "POST / HTTP/1.1" 400 -
localstack_main | 2021-07-21T17:04:51:DEBUG:localstack.services.edge: OUT(qldb): "POST /" - status: 400 - response headers: {'x-amzn-errortype': 'BadRequestException', 'Content-Type': 'text/html; charset=utf-8', 'Content-Length': '118', 'Access-Control-Allow-Origin': '*', 'Server': 'Werkzeug/2.0.1 Python/3.7.10', 'Date': 'Wed, 21 Jul 2021 17:04:51 GMT', 'Access-Control-Allow-Methods': 'HEAD,GET,PUT,POST,DELETE,OPTIONS,PATCH', 'Access-Control-Allow-Headers': 'authorization,content-type,content-length,content-md5,cache-control,x-amz-content-sha256,x-amz-date,x-amz-security-token,x-amz-user-agent,x-amz-target,x-amz-acl,x-amz-version-id,x-localstack-target,x-amz-tagging,amz-sdk-invocation-id,amz-sdk-request', 'Access-Control-Expose-Headers': 'x-amz-version-id'} - **response: b'{"Type": "User", "message": "Unable to execute query: near \\"CREATE\\": syntax error", "__type": "BadRequestException"}'**

### Expected Behavior

The update query shouldn't fail.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

Start the localstack with QLDB as the only service along with the LOCALSTACK_API_KEY.

### Environment

```markdown
- OS: Ubuntu 18.04.3
- LocalStack:
 LocalStack version: 0.12.15
 Image DIGEST:sha256:ddd11b0900c8d65eb3d7757c6030d595717ed61f3c2c764a49ede2ee4b898573
```

**Comment by whummer** [comment]
Hi @sub007 - thanks for reporting, and apologies for the delay. We have tried to replicate your query based on the logs provided - the code below seems to be working (in Python):

```
        query_client = boto3.client("qldb-session", endpoint_url=...)
        # create ledger and create table (omitted)
        ...
        # start session and transaction
        result = query_client.send_command(StartSession={"LedgerName": ledger_name})
        session_token = result["StartSession"]["SessionToken"]
        result = query_client.send_command(SessionToken=session_token, StartTransaction={})
        tx_id = result["StartTransaction"]["TransactionId"]

        # run query
        query = "UPDATE People SET age = ? WHERE firstName = ?"
        params = [
            {"IonBinary": base64.b64decode("4AEA6iFA")},
            {"IonBinary": base64.b64decode("4AEA6oRKb2hu")},
        ]
        statement = {"TransactionId": tx_id, "Statement": query, "Parameters": params}
        result = query_client.send_command(SessionToken=session_token, ExecuteStatement=statement)
        ...
```
Can you please pull the `latest` Docker image and give it another try? If the problem persists - can you please share a few snippets of your client code running the query? Happy to dig into it in more detail... Thanks for your help!

**Comment by whummer** [comment]
Quick follow-up on this issue @sub007 - we have pushed a number of enhancements for the QLDB API in the meantime, have you been able to give this another try with the `latest` Docker image? Closing for now - but please do let us know if the problem persists.. Thanks for your help!
