### ISSUE TITLE
bug: [PRO] Using terraform to destroy and restore RDS cluster causes error

### ISSUE THREAD

**Issue by travis-jorge** [localstack/localstack#4335]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Spinning up an RDS cluster and then using terraform destroy then terraform apply causes an error

`
│ Error: error creating RDS cluster: :
│       status code: 400, request id:
│
│   with module.db.aws_rds_cluster.this[0],
│   on .terraform/modules/db/main.tf line 35, in resource "aws_rds_cluster" "this":
│   35: resource "aws_rds_cluster" "this" {
` 
I tried with and without delete protection enabled

using the following settings

`
### RDS CLUSTER + DATABASE

module "db" {
  source                          = "terraform-aws-modules/rds-aurora/aws"
  version                         = "3.7.0"
  name                            = module.this.id
  engine                          = "aurora-postgresql"
  engine_mode                     = "serverless"
  engine_version                  = null
  replica_count                   = var.replica_count
  db_subnet_group_name            = aws_db_subnet_group.rds_isolated.name
  vpc_security_group_ids          = [aws_security_group.rds_sg.id]
  vpc_id                          = local.vpc_id
  monitoring_interval             = var.monitoring_interval
  skip_final_snapshot             = var.skip_final_snapshot
  apply_immediately               = var.apply_immediately
  storage_encrypted               = true
  db_parameter_group_name         = aws_db_parameter_group.aurora_db_postgresql10_parameter_group.id
  db_cluster_parameter_group_name = aws_rds_cluster_parameter_group.aurora_cluster_postgresql10_parameter_group.id
  database_name                   = var.database_name
  create_random_password          = false
  username                        = var.master_username
  password                        = random_password.master_password.result
  deletion_protection             = true
  create_security_group           = false
  backup_retention_period         = var.backup_retention_period
  kms_key_id                      = aws_kms_key.trfuser_svc_kms_key.arn
  scaling_configuration = {
    auto_pause               = var.auto_pause
    min_capacity             = var.rds_min_capacity
    max_capacity             = var.rds_max_capacity
    seconds_until_auto_pause = var.seconds_until_auto_pause
    timeout_action           = var.timeout_action
  }
  tags = module.this.tags
}

`

### Expected Behavior

you should be able to spin up and tear down the infrastructure as many times as you want without error

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce
1. start localstack 
2. run the following script to tag the resources for the sample project
```
VPCID=$(aws ec2 describe-vpcs --query Vpcs[].VpcId --output text)
echo "Tagging NEW VPC ${VPCID}"
aws ec2 create-tags --resources "${VPCID}" --tags Key=Environment,Value=LOCAL Key=ManagedBy,Value=localstack Key=EksSg,Value=09e79e169504d5555 Key=PrivxSg,Value=sg-03a6e555f842fd3c4
SUBNET1=$(aws ec2 describe-subnets --query Subnets[0].SubnetId --output text)
SUBNET2=$(aws ec2 describe-subnets --query Subnets[1].SubnetId --output text)
echo "Tagging Public Subnet ${SUBNET1}"
aws ec2 create-tags --resources "${SUBNET1}" --tags Key=Type,Value=Public
echo "Tagging Isolated Subnet ${SUBNET2}"
aws ec2 create-tags --resources "${SUBNET2}" --tags Key=Type,Value=Isolated
```
3. Run Terrform Apply
4. Run Terraform Destroy
5. Run Terraform Apply - this time it will fail to create

[rdscreate.zip](https://github.com/localstack/localstack/files/6862673/rdscreate.zip)

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker-compose -f docker-compose.yaml -f docker-compose.terraform.yaml up -d

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)
These commands are used in the bootstrapping to tag some of the default vpc resources 

VPCID=$(aws ec2 describe-vpcs --query Vpcs[].VpcId --output text)
echo "Tagging NEW VPC ${VPCID}"
aws ec2 create-tags --resources "${VPCID}" --tags Key=Environment,Value=LOCAL Key=ManagedBy,Value=localstack Key=EksSg,Value=09e79e167894d7444 Key=PrivxSg,Value=sg-03a6e256f563fd3c9
SUBNET1=$(aws ec2 describe-subnets --query Subnets[0].SubnetId --output text)
SUBNET2=$(aws ec2 describe-subnets --query Subnets[1].SubnetId --output text)
echo "Tagging Public Subnet ${SUBNET1}"
aws ec2 create-tags --resources "${SUBNET1}" --tags Key=Type,Value=Public
echo "Tagging Isolated Subnet ${SUBNET2}"
aws ec2 create-tags --resources "${SUBNET2}" --tags Key=Type,Value=Isolated

### Environment

```markdown
- OS: Ubuntu 20.04
- LocalStack: latest
```

**Comment by travis-jorge** [comment]
I am using a pro api key

**Comment by travis-jorge** [comment]
@whummer I also added a sample app to this ticket

**Comment by travis-jorge** [comment]
https://localstack-community.slack.com/archives/CMAFN2KSP/p1626962063206400 workaround can be found here

**Comment by whummer** [comment]
Great, thanks for providing the link to the workaround. Closing this issue for now - please do reach out directly in case there are any other issues. Thanks!
