### ISSUE TITLE
question: Subscribe local SQS to AWS SNS

### ISSUE THREAD

**Issue by pintomau** [localstack/localstack#4342]
### Is there an existing issue for this?

- [X] I have searched the existing issues and read the documentation

### Question

Hi.

Hopefully this hasn't been asked before.

I'm trying to subscribe a local SQS to a remote SNS topic through localtunnel .

```
aws --profile sns-profile sns subscribe --topic-arn arn-sns --protocol https --notification-endpoint https://my-subdomain.loca.lt/queue/my-queue
```

yields:
```
{
    "SubscriptionArn": "pending confirmation"
}
```

How does one "confirm" this subscription in localstack?

Is there another way to achieve this?

Thanks.

### Anything else?

Queue is managed under a private Cloudfoundry installation.

Using localstack 0.10.7

**Comment by mgagliardo** [comment]
Hello @pintomau, a couple questions here:

1. Does your endpoint implement sns-subscription? 
2. Is this application connected against localstack? Either via a bridged network or a link? When you say localtunnel you mean between your app and the localstack container?
3. If you add `DEBUG=1` to localstack's environment you should see the following:

```
localstack_main  | 2021-07-27T12:21:53:DEBUG:localstack.services.sns.sns_listener: Publishing message to TopicArn: arn:aws:sns:us-east-1:000000000000:mySnsTopic | Message: You have chosen to subscribe to the topic arn:aws:sns:us-east-1:000000000000:mySnsTopic.
localstack_main  | To confirm the subscription, visit the SubscribeURL included in this message.
localstack_main  | 2021-07-27T12:21:54:INFO:localstack.services.sns.sns_listener: Received error on sending SNS message, putting to DLQ (if configured): 405 Client Error: Method Not Allowed for url: http://www.google.com/
```

You can see I did on purpose against google.com, but you can also your application must implement the endpoint functionality describe [in this doc](https://docs.aws.amazon.com/sns/latest/dg/SendMessageToHttp.confirm.html), do you also see this debug log or anything else? There's a thread related to this same issue as well [here](https://stackoverflow.com/questions/51133649/aws-sns-http-subscription-is-not-calling-endpoint). In any case let me know. Cheers!

**Comment by mgagliardo** [comment]
Closing for being unresponsive. Feel free to reopen or ask here. Thanks
