### ISSUE TITLE
bug: elasticache Redis (cluster mode enabled) not created in localstac sucessfully 

### ISSUE THREAD

**Issue by geniusayush** [localstack/localstack#4346]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

i am trying to create a elasticache cluster wuith redis (cluster mode enabled) . it basically should create a cluster with n primary nodes and each node having m replicas. 

aws elasticache create-replication-group  was tried and it ran successfully . but replacing aws with aws local was not a success

i see the output as 
```
{
aws_1            |     "ReplicationGroup": {
aws_1            |         "ReplicationGroupId": "penta-redis",
aws_1            |         "Description": "Demo cluster with replicas",
aws_1            |         "Status": "available",
aws_1            |         "CacheNodeType": "cache.t3.micro",
aws_1            |         "ARN": "arn:aws:elasticache:us-east-1:000000000000:replicationgroup:penta-redis"
aws_1            |     }
aws_1            | }
```
but calling on redis-cli dosent seem to work . 
no success message is deliverd or port is informed

awslocal elasticache create-cache-cluster . this works but it creates an elasticache (cluster mode disabled ) with a single priamry node and multiple replicas

### Expected Behavior

awslocal elasticache create-replication-group should create a elasticache (cluster mode enabled) with specifed nodes and replicas

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

   `awslocal elasticache create-replication-group    --replication-group-id demo-redis    --replication-group-description "Demo cluster with replicas"    --num-node-groups 3    --replicas-per-node-group 2    --cache-node-type cache.t3.micro    --cache-parameter-group default.redis6.x.cluster.on    --engine redis    --engine-version 6.x    --security-group-ids xxxxxx    --cache-subnet-group-name xxxxxx`

compose file
```
aws:
    build: ./localstack
    ports:
      - "443:443"
      - "4566:4566"
      - "4571:4571"
    environment:
      SERVICES: 's3,sqs,sns,elasticache'
      DEBUG: '1'
      LOCALSTACK_API_KEY: xxxxxxxx
```

### Environment

```markdown
- OS: ubuntu latest
- LocalStack: latest
```

**Comment by whummer** [comment]
Thanks for reporting @geniusayush @NathanBurkett and apologies for the long delay on this one. We are now working on this issue with high priority.

In the meantime, if you'd like to create a Redis cache cluster with cluster mode enabled, you can use the `create-cache-cluster` API with multiple (3+) cache nodes (we have recently added support for cluster mode):
```
$ awslocal elasticache --debug create-cache-cluster --engine redis --cache-cluster-id c1 --num-cache-nodes 3 --replication-group-id rg1
...
            "Port": 4510
```
We can then connect to the main node (on port 4510 in the output above):
```
$ redis-cli -c -p 4510
127.0.0.1:4510> set foo bar
-> Redirected to slot [12182] located at 127.0.0.1:4512
OK
127.0.0.1:4512> cluster slots
1) 1) (integer) 5461
   2) (integer) 10922
   3) 1) "127.0.0.1"
      2) (integer) 4511
      3) "832bd92efb73fdde5e978099dd20d671aa923ee3"
2) 1) (integer) 10923
   2) (integer) 16383
   3) 1) "127.0.0.1"
      2) (integer) 4512
      3) "bc5d70917e863bc278fecacd989fe65162bd249e"
3) 1) (integer) 0
   2) (integer) 5460
   3) 1) "127.0.0.1"
      2) (integer) 4510
      3) "11f611ff5bf70a261bdf32a86fdf7c434ef59266"
```

Hope that helps. Will ping you soon with an update regarding `create-replication-group` - thanks!

**Comment by whummer** [comment]
Hi @geniusayush NathanBurkett , apologies for the delay. This issue should now be (hopefully) fixed - support for `create-replication-group` has been added in the meantime. Can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists. Thanks for your help!
