### ISSUE TITLE
bug: S3 creation with terraform not working on latest image

### ISSUE THREAD

**Issue by JorgeBoscan** [localstack/localstack#4353]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have a terraform script which is working fine on 0.12.15, but on the latest tag s3 buckets timeout when applying the script.
`aws_s3_bucket.s3_test_bucket[1]: Still creating... [3m0s elapsed]
aws_s3_bucket.s3_test_bucket[0]: Still creating... [3m0s elapsed]
╷
│ Error: error getting S3 Bucket CORS configuration: timeout while waiting for state to become 'success' (timeout: 2m0s)
│
│   with aws_s3_bucket.s3_test_bucket[1],
│   on localstack.tf line 42, in resource "aws_s3_bucket" "s3_test_bucket":
│   42: resource "aws_s3_bucket" "s3_test_bucket" {
│
╵
╷
│ Error: error getting S3 Bucket CORS configuration: timeout while waiting for state to become 'success' (timeout: 2m0s)
│
│   with aws_s3_bucket.s3_test_bucket[0],
│   on localstack.tf line 42, in resource "aws_s3_bucket" "s3_test_bucket":
│   42: resource "aws_s3_bucket" "s3_test_bucket" {
│
╵`

### Expected Behavior

S3 creation through terraform should work the same as 0.12.15

### How are you starting LocalStack?

With a `docker run` command

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run -d -p 4566:4566 -p 4571:4571 -e SERVICES="sqs,sns,s3,secretsmanager" -e AWS_DEFAULT_REGION=us-west-2 --name localstack localstack/localstack:latest

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

Terraform script with:
`
variable "localstack_host" {
  default = "localhost"
}

terraform {
  required_version = "= 0.15.5"

  required_providers {
    aws = "~> 2.39.0"
  }
}

provider "aws" {
  alias                       = "local"
  region                      = "us-west-2"
  access_key                  = "test"
  secret_key                  = "test"
  skip_credentials_validation = true
  skip_metadata_api_check     = true
  skip_requesting_account_id  = true
  endpoints {
    s3  = "http://${var.localstack_host}:4566"
  }
}

locals {
  environment = "localstack"
  s3_buckets = [
    "test1",
    "test2"
  ]
}

resource "aws_s3_bucket" "s3_test_bucket" {
  count    = "${length(local.s3_buckets)}"
  bucket   = "${local.environment}-${element(local.s3_buckets, count.index)}"
  provider = aws.local
}`

### Environment

```markdown
- OS: macos 11.4
- LocalStack: latest
```

**Comment by mgagliardo** [comment]
Hello @JorgeBoscan, I am not sure if I am doing anything different but I was able to apply this without issues using Terraform `1.0.2` and localstack `latest` docker image.

Let me know if there is anything I need to do different. Cheers!

main.tf:
```
provider "aws" {
  region                      = "us-east-1"
  access_key                  = "mock_access_key"
  secret_key                  = "mock_secret_key"
  s3_force_path_style         = true
  skip_credentials_validation = true
  skip_metadata_api_check     = true
  skip_requesting_account_id  = true

  endpoints {
    s3 = "http://localhost:4566"
  }
}

locals {
  environment = "localstack"
  s3_buckets = [
    "test1",
    "test2",
  ]
}

resource "aws_s3_bucket" "s3_test_bucket" {
  count = "${length(local.s3_buckets)}"
  bucket = "${local.environment}-${element(local.s3_buckets, count.index)}"
}
```

Apply:
```
$ terraform apply -auto-approve
terraform apply -auto-approve;

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # aws_s3_bucket.s3_test_bucket[0] will be created
  + resource "aws_s3_bucket" "s3_test_bucket" {
      + acceleration_status         = (known after apply)
      + acl                         = "private"
      + arn                         = (known after apply)
      + bucket                      = "localstack-test1"
      + bucket_domain_name          = (known after apply)
      + bucket_regional_domain_name = (known after apply)
      + force_destroy               = false
      + hosted_zone_id              = (known after apply)
      + id                          = (known after apply)
      + region                      = (known after apply)
      + request_payer               = (known after apply)
      + tags_all                    = (known after apply)
      + website_domain              = (known after apply)
      + website_endpoint            = (known after apply)

      + versioning {
          + enabled    = (known after apply)
          + mfa_delete = (known after apply)
        }
    }

  # aws_s3_bucket.s3_test_bucket[1] will be created
  + resource "aws_s3_bucket" "s3_test_bucket" {
      + acceleration_status         = (known after apply)
      + acl                         = "private"
      + arn                         = (known after apply)
      + bucket                      = "localstack-test2"
      + bucket_domain_name          = (known after apply)
      + bucket_regional_domain_name = (known after apply)
      + force_destroy               = false
      + hosted_zone_id              = (known after apply)
      + id                          = (known after apply)
      + region                      = (known after apply)
      + request_payer               = (known after apply)
      + tags_all                    = (known after apply)
      + website_domain              = (known after apply)
      + website_endpoint            = (known after apply)

      + versioning {
          + enabled    = (known after apply)
          + mfa_delete = (known after apply)
        }
    }

Plan: 2 to add, 0 to change, 0 to destroy.
aws_s3_bucket.s3_test_bucket[1]: Creating...
aws_s3_bucket.s3_test_bucket[0]: Creating...
aws_s3_bucket.s3_test_bucket[0]: Creation complete after 1s [id=localstack-test1]
aws_s3_bucket.s3_test_bucket[1]: Creation complete after 1s [id=localstack-test2]

Apply complete! Resources: 2 added, 0 changed, 0 destroyed.
```

List buckets:
```
$ awslocal s3api list-buckets
{
    "Buckets": [
        {
            "Name": "localstack-test2",
            "CreationDate": "2021-07-24T03:49:40+00:00"
        },
        {
            "Name": "localstack-test1",
            "CreationDate": "2021-07-24T03:49:40+00:00"
        }
    ],
    "Owner": {
        "DisplayName": "webfile",
        "ID": "bcaf1ffd86f41161ca5fb16fd081034f"
    }
}
```

**Comment by mgagliardo** [comment]
Found the underlying issue with exactly the same code as you used, it looks you are missing the `s3_force_path_style` property in your terraform provider block so:

```
provider "aws" {
  alias = "local"
  region = "us-west-2"
  access_key = "test"
  secret_key = "test"
  skip_credentials_validation = true
  skip_metadata_api_check = true
  skip_requesting_account_id = true
  s3_force_path_style         = true
  
  endpoints {
    s3 = "http://${var.localstack_host}:4566"
  }
}
```

That does the job. Closing this issue now. Cheers!
