### ISSUE TITLE
In Cognito validate user password against configured Policy

### ISSUE THREAD

**Issue by hosuaby** [localstack/localstack#4369]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Assuming there is a Cognito user-pool with configured password policies:

```
aws --endpoint-url=http://localhost:4566 --region=us-west-1 \
    cognito-idp create-user-pool \
    --pool-name mypool \
    --alias-attributes preferred_username email phone_number \
    --policies 'PasswordPolicy={MinimumLength=6,RequireUppercase=true,RequireLowercase=true,RequireNumbers=true,RequireSymbols=true}'
```

If after we create an user within that user-pool, and after change his password using operations `cognito-idp admin-set-user-password` or `cognito-idp change-password`, any password will be accepted without verification.

Real Cognito instance rejects passwords that do not respect policies.

**Comment by giograno** [comment]
Duplicate of #8356.
