### ISSUE TITLE
bug: Route table association fails with terraform

### ISSUE THREAD

**Issue by jrauen** [localstack/localstack#4373]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When creating a route table association the terraform aws provider (~>3.47.0) throws a null pointer exception. After creating the association, the provider performs a `DescribeRouteTables` API call to obtain the [AssociationState](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_RouteTableAssociationState.html). The Localstack response does not include the AssociationState in the Associations. This is an upstream issue with spulec/moto but I wanted to mention it here for tracking.

I've created a [pull request](https://github.com/spulec/moto/pull/4096) with the upstream project to fix this issue.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

see above

### Environment

```markdown
- OS: 
- LocalStack:
```

**Comment by mgagliardo** [comment]
Hello @jrauen, can you please share the terraform code so we can debug this out?

**Comment by jrauen** [comment]
This should provide a good example you can dig through.
```
resource "aws_vpc" "test" {
  cidr_block = "172.30.0.0/22"
}

resource "aws_subnet" "test" {
  cidr_block              = "172.30.0.0/24)
  vpc_id                  = aws_vpc.test.id
  map_public_ip_on_launch = false
  availability_zone       = "us-east-1"
}

resource "aws_route_table" "test" {
  vpc_id = aws_vpc.test.id
}

resource "aws_route_table_association" "test" {
  subnet_id      = aws_subnet.test.id
  route_table_id = aws_route_table.test.id
}
```

**Comment by mgagliardo** [comment]
I think this is a good opportunity to expand a bit our integration tests, adding https://github.com/localstack/localstack/pull/4374 to do so
