### ISSUE TITLE
feature request: add PartiQL (ExecuteStatement API) support to DynamoDB

### ISSUE THREAD

**Issue by intptr-t** [localstack/localstack#4378]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Are there any plans to support DynamoDB's ExecuteStatement API?

Currently, localstack does not support ExecuteStatement.
When I run it, I will get an error like the following.
```
An error occurred (UnknownOperationException) when calling the ExecuteStatement operation: An unknown operation was requested.
```

**What PartiQL**
https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/ql-reference.html

**DynamoDB local already supported**
https://aws.amazon.com/about-aws/whats-new/2021/02/you-now-can-use-partiql-with-dynamodb-local-to-query-insert-update-and-delete-table-data-in-amazon-dynamodb

**We will be able to do the following**

* Preparation: Table creation(ref: [Step 1: Create a Table](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/getting-started-step-1.html))
```bash
awslocal dynamodb create-table \
    --table-name Music \
    --attribute-definitions \
        AttributeName=Artist,AttributeType=S \
        AttributeName=SongTitle,AttributeType=S \
    --key-schema \
        AttributeName=Artist,KeyType=HASH \
        AttributeName=SongTitle,KeyType=RANGE \
    --provisioned-throughput \
        ReadCapacityUnits=10,WriteCapacityUnits=5
```

* INSERT (ref: [PartiQL Insert Statements for DynamoDB](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/ql-reference.insert.html))
```bash
awslocal dynamodb execute-statement --statement "INSERT INTO Music value {'Artist':'Acme Band','SongTitle':'PartiQL Rocks'}"
```

Thanks!

**Comment by whummer** [comment]
Thanks for reporting @intptr-t . This should be fixed in the meantime - can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists.. Thanks!

**Comment by intptr-t** [comment]
@whummer 
Thanks for your responding.

I pulled the new image (latest).
However, the ExecuteStatement API did not work for dynamodb in the localstack.

The startup_info.json is as follows,
```startup_info.json
[
    {
        "timestamp": "2021-08-05T08:45:13.313397",
        "localstack_version": "0.12.16",
        "localstack_ext_version": "0.12.14.5",
        "pro_activated": false
    }
]
```

Just to be sure, I also checked with DynamoDB local, and it worked as expected here.

```
aws dynamodb create-table \
    --table-name Music \
    --attribute-definitions \
        AttributeName=Artist,AttributeType=S \
        AttributeName=SongTitle,AttributeType=S \
    --key-schema \
        AttributeName=Artist,KeyType=HASH \
        AttributeName=SongTitle,KeyType=RANGE \
    --provisioned-throughput \
        ReadCapacityUnits=10,WriteCapacityUnits=5 \
    --endpoint-url http://localhost:8000

aws dynamodb execute-statement --statement "INSERT INTO Music value {'Artist':'Acme Band','SongTitle':'PartiQL Rocks'}" \
    --endpoint-url http://localhost:8000
```

Please accept my request again.
Thanks.

**Comment by whummer** [comment]
Thanks for the update @intptr-t - looks like there has been a small issue in our CI pipeline. The feature should now be available after pulling the `latest` Docker image. Please keep us posted how it goes. Thanks!

**Comment by intptr-t** [comment]
@whummer 
Thanks for the update.
It worked as expected.
