### ISSUE TITLE
bug: SNS Subscription Filter Policy "exists" false does not match 

### ISSUE THREAD

**Issue by krecz** [localstack/localstack#4379]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm encountering an issue with the "exists" property on SNS Filter Policy. It logs that it can't match the policy even though I would expect it to match.

```
2021-07-28T17:57:02:INFO:localstack.services.sns.sns_listener: SNS filter policy {'source': ['source1'], 'priority': [{'exists': False}]} 
does not match attributes {'clientId': {'Type': 'String', 'Value': 'Id123'}, 'source': {'Type': 'String', 'Value': 'source1'}, 'awsRegionName': {'Type': 'String', 'Value': 'us-east-1'}}
```

### Expected Behavior

Policy matches and message is sent to subscribers.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    I run in a docker-compose script and load my CloudFormation script on init.

Using the following CloudFormation script I create the subscription. 

```
"Subscription": {
            "Type": "AWS::SNS::Subscription",
            "Properties": {
                "TopicArn": {
                    "Ref": "MyTopic"
                },
                "Endpoint": {
                    "Fn::GetAtt": [
                        "MyQueue",
                        "Arn"
                    ]
                },
                "Protocol": "sqs",
                "FilterPolicy": {
                    "source": [
                        "source1"
                    ],
                    "priority":  [{"exists": false}]
                },
                "RawMessageDelivery": true
            }
        },
```

### Environment

```markdown
- OS: Windows
- LocalStack: latest
```

**Comment by mrjrt** [comment]
I can cofirm I've just hit this with localstack/localstack:0.12.20
