### ISSUE TITLE
bug: [PRO] When querying table names using Java SDK, "IonException: Not a single value" is thrown

### ISSUE THREAD

**Issue by richardkabiling** [localstack/localstack#4383]
### Is there an existing issue for this?

- [X] I have searched the existing issues

#### Action
Querying QLDB table names using Driver from localstack pro:
```
driver.getTableNames();
```

#### Dependencies

```
    <dependency>
      <groupId>software.amazon.awssdk</groupId>
      <artifactId>qldb</artifactId>
      <version>2.17.2</version>
    </dependency>
```

#### Exception

```
com.amazon.ion.IonException: not a single value

	at com.amazon.ion.impl.lite.IonSystemLite.singleValue(IonSystemLite.java:513)
	at com.amazon.ion.impl.lite.IonSystemLite.singleValue(IonSystemLite.java:534)
	at com.amazon.ion.impl.lite.IonSystemLite.singleValue(IonSystemLite.java:526)
	at software.amazon.qldb.ResultRetriever.next(ResultRetriever.java:162)
	at software.amazon.qldb.StreamResult$IonIterator.next(StreamResult.java:175)
	at software.amazon.qldb.StreamResult$IonIterator.next(StreamResult.java:120)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at software.amazon.qldb.BufferedResult.<init>(BufferedResult.java:45)
	at software.amazon.qldb.QldbSession.execute(QldbSession.java:66)
	at software.amazon.qldb.QldbDriverImpl.execute(QldbDriverImpl.java:150)
	at software.amazon.qldb.QldbDriverImpl.getTableNames(QldbDriverImpl.java:199)
```

#### Dockerfile
```
version: '2.1'

services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
      - "443:443"
    environment:
      SERVICES: "qldb"
      START_WEB: "0"
      DEFAULT_REGION: "eu-west-1"
      LOCALSTACK_API_KEY: "..."
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "./init.d:/docker-entrypoint-initaws.d"
```

### Expected Behavior

Driver names are returned.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker compose up

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```
      driver.getTableNames();
```

Executing the query under the hood also yields the same exception
```
      var result = driver.execute(txn -> {
        return txn.execute("SELECT VALUE name FROM information_schema.user_tables WHERE status = 'ACTIVE'");
      });
```

Note that running this query in qldbshell works just fine.

### Environment

```markdown
- OS: MacOS Big Sur
- LocalStack: latest
- Language: Java
- AWS SDK (QLDB): 2.17.2
```

**Comment by whummer** [comment]
Hi @richardkabiling , thanks for reporting this issue.  We have done a few tests, and so far haven't been able to replicate the issue you've been seeing.

Simple example:
```
$ awslocal qldb create-ledger --name l1 --permissions-mode p1
$ qldbshell -l l1 -s http://localhost:4566
> create table foo1;
...
> create table foo2;
...
> SELECT VALUE name FROM information_schema.user_tables WHERE status = 'ACTIVE'
INFO: 
foo1,
foo2
INFO: (0.9839s)
```
Can you please share a few more details about your end-to-end use case, to help us replicate this issue? Also, can you please share the version/build date of the image that gets printed during startup, e.g.:

```
LocalStack version: 0.12.15
LocalStack Docker image id: 32b32983ea36
LocalStack build date: 2021-07-30
LocalStack build git hash: 7412a410
```
Thanks for your help! (Happy to continue the conversation here, or over on Slack..)

**Comment by whummer** [comment]
Actually, please ignore the comment above - just noticed this part:
> Note that running this query in qldbshell works just fine.

We'll look into reproducing the issue using the 2.x AWS Java SDK. Will ping you soon with an update. Thanks!

**Comment by whummer** [comment]
Quick update @richardkabiling - we have now pushed a few enhancements in the QLDB API which should (hopefully) resolve the issue you've been seeing. A small integration test has been added [here](https://github.com/localstack/localstack-java-utils/blob/master/src/test/java/cloud/localstack/awssdkv2/ProFeaturesSDKV2Test.java#L26-L59). 

Can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists. Thanks for your help!
