### ISSUE TITLE
bug: 2 cognito user pools use the same jwks key

### ISSUE THREAD

**Issue by seibelj** [localstack/localstack#4384]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

This seems to have started recently. If you create two user pools, both return the same well-known key when you use curl, but in terraform they say they have different keys. When tokens are issued, they are using the wrong key.

### Expected Behavior

User pools should have their own keys and issue tokens signed properly.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

Add 2 pools like so:

```
resource "aws_cognito_user_pool" "internal" {
  name = "internal-users"

  password_policy {
    minimum_length = 6
  }
}

resource "aws_cognito_user_pool" "external" {
  name = "external-users"

  password_policy {
    minimum_length = 6
  }
}
```
Issue tokens with each pool. Use jwt.io to get the `iss` url. Then curl each:

`curl http://localhost:4566/us-east-1_e0.../.well-known/jwks.json`

`curl http://localhost:4566/us-east-1_3b.../.well-known/jwks.json`

Both return the same keys, even though in the terraform state they are supposed to be different. Furthermore, tokens issued by those pools use the same signature! It's like one of the pools' keys is being ignored and it is defaulting to the first pool.

### Environment

```markdown
- OS: macOS
- LocalStack: latest
```

**Comment by whummer** [comment]
Thanks for reporting this issue @seibelj  . This should be fixed in the meantime - can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists. Thanks for your help!

**Comment by seibelj** [comment]
Confirmed this is fixed. We don't like to use edge (latest) tags - do you know when next release will be tagged? Thanks for quick fix
