### ISSUE TITLE
bug: localstack docker file throwing error

### ISSUE THREAD

**Issue by manas86** [localstack/localstack#4390]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If I try to build the docker image from this existing master repo's Dockerfile not the pull from this repository, it shows me 
 "/localstack/infra/stepfunctions" not found: not found

In the current master branch, Dockerfile at line number 43 mentioned `ADD localstack/infra/stepfunctions localstack/infra/stepfunctions` while in the existing folder structure there are no infra folder exists. 

### Expected Behavior

It should build the docker image locally without any issues.If I clone the repo to my local machine. 

### How are you starting LocalStack?

Custom (please describe below)

### Steps To Reproduce

1) clone the repo
2) build the image using `docker build -t localstack .`

### Environment

```markdown
- OS: mac
- LocalStack: master
```

**Comment by whummer** [comment]
Thanks for reporting @manas86 . Please note that there are a few commands we need to run to prepare the Docker build - specifically, downloading some dependencies like the StepFunctions local binary. 

We generally recommend using the `make docker-build` command to build the Docker image locally (we'll make sure to update that in our documentation). Hope that helps - please let us know if there are any issues with that. Thanks!

**Comment by manas86** [comment]
.thanks for the quick response. even-if I try to execute `make docker-build`, I'm still getting error. I ran the  build-image command in `venv`, still error.  is there any process to build the image locally?

**Comment by whummer** [comment]
Hi @manas86 , we have now updated the README [here](https://github.com/localstack/localstack#building-the-docker-image). Can you please share the full logs of `make docker-build`, and the latest error message you're seeing? Thanks
