### ISSUE TITLE
feature request: Add support for aws pinpoint to roadmap

### ISSUE THREAD

**Issue by scottleedavis** [localstack/localstack#4393]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

https://roadmap.localstack.cloud/

https://aws.amazon.com/pinpoint/

### Anything else?

https://aws.amazon.com/pinpoint/

**Comment by whummer** [comment]
Thanks for reporting @scottleedavis . Do you mind adding it to the roadmap page directly, so other users can also chime in an upvote this feature request? (You can sign in with your Github user account and add new feature requests on the page). 

We're planning to tackle an initial version of Pinpoint soon - would be great if you can also share a few details what are the key use cases / features you'd like to see supported initially. Thanks for your help!

**Comment by HarshCasper** [comment]
Hi,

The Pinpoint service is now available in `localstack/localstack-pro:latest` image. Please pull the image to get started. Here are the docs: https://docs.localstack.cloud/user-guide/aws/pinpoint/
