### ISSUE TITLE
I gonna quit using this product since a ton of errors

### ISSUE THREAD

**Issue by vincentpham13** [localstack/localstack#4397]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

I gonna quit using this product since a ton of errors

### 🧑‍💻 Implementation

I gonna quit using this product since a ton of errors

### Anything else?

I gonna quit using this product since a ton of errors

**Comment by whummer** [comment]
Thanks for the feedback @vincentpham13 . We're working very hard to address any issues and make the product better on a daily basis. If you're experiencing any specific errors, we'd appreciate it if you could provide some details and steps to reproduce - we'll be happy to get them resolved. Thanks!
