### ISSUE TITLE
bug: INFO:localstack.services.awslambda.lambda_api: Error executing Lambda function #pro

### ISSUE THREAD

**Issue by bladmoreno** [localstack/localstack#4414]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have a dotnet core 3.1 Lambda/ApiGateway project, I have been able to deploy the function and create the ApiGateway, but once I try to call the function straight through the AWS Local CLI or through the ApiGetway I get this error:
```
localstack    | 2021-08-05T04:49:53:INFO:localstack.services.awslambda.lambda_api: Error executing Lambda function arn:aws:lambda:us-east-1:000000000000:function:50874-UH-GetMessageAsync-local: bad escape \U at position 2 Traceback (most recent call last):
```
### Expected Behavior

To run the Lambda function and receive an payload back

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

I call the lambda function through the ApiGateway endpoint

https://localhost.localstack.cloud/restapis/fduhbub3o5/local/_user_request_/Message
```
{"errorType": "error", "errorMessage": "bad escape \\U at position 2", "stackTrace": [" File \"/opt/code/localstack/localstack/services/awslambda/lambda_api.py\", line 752, in run_lambda\n lock_discriminator=lock_discriminator,\n", " File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 279, in execute\n return do_execute()\n", " File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 269, in do_execute\n return _run(func_arn=func_arn)\n", " File \"/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py\", line 157, in wrapped\n raise e\n", " File \"/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py\", line 153, in wrapped\n result = func(*args, **kwargs)\n", " File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 256, in _run\n raise e\n", " File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 242, in _run\n result = self._execute(func_arn, func_details, event, context, version)\n", " File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 507, in _execute\n event=stdin, env_vars=environment, func_details=func_details, docker_flags=docker_flags\n", " File \"/opt/code/localstack/.venv/lib/python3.7/site-packages/localstack_ext/services/awslambda/lambda_extended.py\", line 360, in run_lambda_executor\n", " File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 358, in run_lambda_executor\n func_details, env_vars, command, docker_flags=docker_flags, stdin=event_stdin_bytes\n", " File \"/opt/code/localstack/.venv/lib/python3.7/site-packages/localstack_ext/services/awslambda/lambda_launcher.py\", line 238, in docker_separate_execute_in_container\n", " File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 1087, in get_host_path_for_path_in_docker\n return re.sub(r\"^%s/(.*)$\" % config.TMP_FOLDER, r\"%s/\\1\" % config.HOST_TMP_FOLDER, path)\n", " File \"/usr/lib/python3.7/re.py\", line 194, in sub\n return _compile(pattern, flags).sub(repl, string, count)\n", " File \"/usr/lib/python3.7/re.py\", line 311, in _subx\n template = _compile_repl(template, pattern)\n", " File \"/usr/lib/python3.7/re.py\", line 302, in _compile_repl\n return sre_parse.parse_template(repl, pattern)\n", " File \"/usr/lib/python3.7/sre_parse.py\", line 1018, in parse_template\n raise s.error('bad escape %s' % this, len(this))\n"]}

//
HOST_TMP_FOLDER on docker image once configure in docker-compose.yml
--

 HOST_TMP_FOLDER='C:\Users\W0DC0~1.MOR\AppData\Local\Temp/localstack'

//
```

docker-compose.yml
```
services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack}"
    image: localstack/localstack
    hostname: localstack
    ports:
      - "443:443"
      - "4566-4597:4566-4597"
    environment:
      - LOCALSTACK_API_KEY=## REDACTED by @dfangl 
      - SERVICES=sns,sqs,s3,cloudformation,cloudwatch,logs,iam,lambda,dynamodb,dynamodbstreams,apigateway,apigatewayv2,sts,kms,ssm,cognito,rds,cognito-idp,stepfunctions,firehose,es
      - PORT_WEB_UI=8080
      - DEBUG=1
      - SLS_DEBUG=*
      - DEFAULT_REGION=us-east-1
      - LAMBDA_REMOTE_DOCKER=false
      - LAMBDA_EXECUTOR=docker
      - HOST_TMP_FOLDER=${TMPDIR}/localstack
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - localstack
    

networks:
  localstack:
    external: false
    driver: bridge
    name: localstack
```

### Environment

```markdown
- OS: Windows 10 Enterprise build 19042.1110
- LocalStack: latest
```

**Comment by bladmoreno** [comment]
Now I am getting this stacktrace:

localstack    | 2021-08-05T16:23:21:DEBUG:localstack.services.awslambda.lambda_executors: Lambda arn:aws:lambda:us-east-1:000000000000:function:50874-UH-GetMessageAsync-local result / log output:
localstack    |
localstack    | > WARNING: Localhost DNS setting (--dns=127.0.0.1) may fail in containers.
localstack    | > docker: Error response from daemon: OCI runtime create failed: container_linux.go:367: starting container process caused: exec: "/tmp/4b09f282.sh": stat /tmp/4b09f282.sh: no such file or directory: unknown.
localstack    | 2021-08-05 16:23:21,422:API: 127.0.0.1 - - [05/Aug/2021 16:23:21] "POST / HTTP/1.1" 200 -
localstack    | 2021-08-05 16:23:21,476:API: 127.0.0.1 - - [05/Aug/2021 16:23:21] "POST / HTTP/1.1" 200 -
localstack    | 2021-08-05 16:23:21,559:API: 127.0.0.1 - - [05/Aug/2021 16:23:21] "POST / HTTP/1.1" 200 -
localstack    | 2021-08-05 16:23:21,623:API: 127.0.0.1 - - [05/Aug/2021 16:23:21] "POST / HTTP/1.1" 200 -
localstack    | 2021-08-05 16:23:21,733:API: 127.0.0.1 - - [05/Aug/2021 16:23:21] "POST / HTTP/1.1" 200 -
localstack    | 2021-08-05T16:23:21:INFO:localstack.services.awslambda.lambda_api: Error executing Lambda function arn:aws:lambda:us-east-1:000000000000:function:50874-UH-GetMessageAsync-local: Lambda process returned with error. Result: . Output:
localstack    | WARNING: Localhost DNS setting (--dns=127.0.0.1) may fail in containers.
localstack    | docker: Error response from daemon: OCI runtime create failed: container_linux.go:367: starting container process caused: exec: "/tmp/4b09f282.sh": stat /tmp/4b09f282.sh: no such file or directory: unknown. Traceback (most recent call last):
localstack    |   File "/opt/code/localstack/localstack/utils/docker.py", line 335, in _run_async_cmd
localstack    |     stderr,
localstack    | subprocess.CalledProcessError: Command '['docker', 'run', '--rm', '--entrypoint', '/tmp/4b09f282.sh', '-v', 'C:\\Users\\w.moreno\\Source\\UH\\UH_50874_MessageHistoryAPI\\deploy:/var/task', '-v', '~/Source/UH/UH_50874_MessageHistoryAPI:/tmp', '--interactive', '-e', 'SERVERLESS_STAGE=local', '-e', 'SERVERLESS_REGION=us-east-1', '-e', 'SERVERLESS_PROJECT=MessageHistoryAPI', '-e', 'SERVERLESS_SERVICE_NAME=UH-50874-MessageHistoryAPI', '-e', 'UHDynamoDB_STORE=50874-UH-Messages-local', '-e', 'AWS_ACCESS_KEY_ID=test', '-e', 'AWS_SECRET_ACCESS_KEY=test', '-e', 'AWS_REGION=us-east-1', '-e', 'DOCKER_LAMBDA_USE_STDIN=1', '-e', 'LOCALSTACK_HOSTNAME=172.17.0.2', '-e', 'EDGE_PORT=443', '-e', '_HANDLER=50874_UH_MessageHistoryAPI::UH_MessageHistory.MessageHistoryHandler::GetMessageAsync', '-e', 'AWS_LAMBDA_FUNCTION_TIMEOUT=6', '-e', 'AWS_LAMBDA_FUNCTION_NAME=50874-UH-GetMessageAsync-local', '-e', 'AWS_LAMBDA_FUNCTION_VERSION=$LATEST', '-e', 'AWS_LAMBDA_FUNCTION_INVOKED_ARN=arn:aws:lambda:us-east-1:000000000000:function:50874-UH-GetMessageAsync-local', '-e', 'AWS_LAMBDA_COGNITO_IDENTITY={}', '-e', 'LOCALSTACK_DEBUG=1', '--user', 'root', '--cap-add', 'NET_ADMIN', '--dns', '127.0.0.1', 'localstack/lambda:dotnetcore3.1', '50874_UH_MessageHistoryAPI::UH_MessageHistory.MessageHistoryHandler::GetMessageAsync']' returned non-zero exit status 127.
localstack    |
localstack    | During handling of the above exception, another exception occurred:
localstack    |
localstack    | Traceback (most recent call last):
localstack    |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 358, in run_lambda_executor
localstack    |     func_details, env_vars, command, docker_flags=docker_flags, stdin=event_stdin_bytes
localstack    |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/localstack_ext/services/awslambda/lambda_launcher.py", line 242, in docker_separate_execute_in_container
localstack    |   File "/opt/code/localstack/localstack/utils/docker.py", line 267, in run_container
localstack    |     result = self._run_async_cmd(cmd, stdin, kwargs.get("name") or "", image_name)
localstack    |   File "/opt/code/localstack/localstack/utils/docker.py", line 346, in _run_async_cmd
localstack    |     "Docker process returned with errorcode %s" % e.returncode, e.stdout, e.stderr
localstack    | localstack.utils.docker.ContainerException: ('Docker process returned with errorcode 127', b'', b'WARNING: Localhost DNS setting (--dns=127.0.0.1) may fail in containers.\ndocker: Error response from daemon: OCI runtime create failed: container_linux.go:367: starting container process caused: exec: "/tmp/4b09f282.sh": stat /tmp/4b09f282.sh: no such file or directory: unknown.\n')
localstack    |
localstack    | The above exception was the direct cause of the following exception:
localstack    |
localstack    | Traceback (most recent call last):
localstack    |   File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 752, in run_lambda
localstack    |     lock_discriminator=lock_discriminator,
localstack    |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 279, in execute
localstack    |     return do_execute()
localstack    |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 269, in do_execute
localstack    |     return _run(func_arn=func_arn)
localstack    |   File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 157, in wrapped
localstack    |     raise e
localstack    |   File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 153, in wrapped
localstack    |     result = func(*args, **kwargs)
localstack    |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 256, in _run
localstack    |     raise e
localstack    |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 242, in _run
localstack    |     result = self._execute(func_arn, func_details, event, context, version)
localstack    |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 507, in _execute
localstack    |     event=stdin, env_vars=environment, func_details=func_details, docker_flags=docker_flags
localstack    |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/localstack_ext/services/awslambda/lambda_extended.py", line 360, in run_lambda_executor
localstack    |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 397, in run_lambda_executor
localstack    |     ) from error
localstack    | localstack.services.awslambda.lambda_executors.InvocationException: Lambda process returned with error. Result: . Output:
localstack    | WARNING: Localhost DNS setting (--dns=127.0.0.1) may fail in containers.
localstack    | docker: Error response from daemon: OCI runtime create failed: container_linux.go:367: starting container process caused: exec: "/tmp/4b09f282.sh": stat /tmp/4b09f282.sh: no such file or directory: unknown.
localstack    |

**Comment by ackdav** [comment]
Hi @bladmoreno - thank you for raising this and apologies for the late response. Would you be able to pull the latest LocalStack version and double-check whether this issue still persists?
Thank you!
