### ISSUE TITLE
API gateway put-integration-response error:UnrecognizedClientException  when calling the PutIntegrationResponse operation: The security token included in the request is invalid

### ISSUE THREAD

**Issue by ashameem123** [localstack/localstack#4416]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Trying to create a MOCK service and getting error - **An error occurred (UnrecognizedClientException) when calling the PutIntegrationResponse operation: The security token included in the request is invalid.** on running put-integration-response command. 
Note: Method request, Integration request and method response are executing fine.

### Expected Behavior

I am expecting a successful execution of put-integration-response while creating and deploying APIGW.

### How are you starting LocalStack?

With a `docker run` command

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

  docker-compose up -d

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

create rest api:
aws --endpoint-url=http://localhost:4566 lambda create-function --function-name my-mock-function --runtime python  --handler csg-my-mock.lambda_handler --role arn:aws:lambda:us-east-1:521128443362:function:my-function --zip-file fileb://my-mock-function.zip

aws --endpoint-url=http://localhost:4566 apigateway create-rest-api --region us-east-1 --name 'my-mock-apigw'

retreive parent id:
aws --endpoint-url=http://localhost:4566 apigateway get-resources --region us-east-1 --rest-api-id 4m23p9zhjh

create resource:
aws --endpoint-url=http://localhost:4566 apigateway create-resource --region us-east-1 --rest-api-id 4m23p9zhjh --parent-id m1yfa786oy --path-part "POST"

create POST method:
 aws --endpoint-url=http://localhost:4566 apigateway put-method --region us-east-1 --rest-api-id 4m23p9zhjh --resource-id idgdyigjtw --http-method POST --request-parameters "method.request.header.Content-Type:application/json=true" --authorization-type "NONE"

 aws --endpoint-url=http://localhost:4566 apigateway put-method --region us-east-1 --rest-api-id 4m23p9zhjh --resource-id idgdyigjtw --http-method POST --request-parameters "integration.request.header.body-header.Content-Type:application/json=true" --authorization-type "NONE"
 

lambda Integration:

aws --endpoint-url=http://localhost:4566 apigateway put-integration --region us-east-1 --rest-api-id 4m23p9zhjh --resource-id idgdyigjtw --http-method POST --type LambdaFunction --integration-http-method POST --uri arn:aws:apigateway:us-east-1:lambda:path/2021-08-06/functions/arn:aws:lambda:us-east-1:000000000000:function:my-mock-function/invocations --request-templates '{"application/json":"{\"statusCode\": $input.json('$.statusCode'), \"message\": $input.json('$.message')}"}' --passthrough-behavior WHEN_NO_TEMPLATES

Create Responses:
 
 aws --endpoint-url=http://localhost:4566 apigateway put-integration-response --rest-api-id 4m23p9zhjh --resource-id idgdyigjtw --http-method POST --status-code 200 --selection-pattern '2\d{2}' --region us-east-1

 aws --endpoint-url=http://localhost:4566 apigateway put-method-response --rest-api-id 4m23p9zhjh --resource-id idgdyigjtw --http-method POST --status-code 200 --response-models "{}" --region us-east-1

Deploy API:

aws --endpoint-url=http://localhost:4566 apigateway create-deployment --region us-east-1 --rest-api-id 2ppkhhwu05 --stage-name test

### Environment

```markdown
- OS: Windows
- LocalStack: latest (LocalStack version: 0.12.16)
```

### Anything else?

version: '2.1'

services:

  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack-full:latest
    ports:
      - "4566-4620:4566-4620"
    environment:
      - AWS_REGION=us-east-1
      - SERVICES=${SERVICES- }
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - LAMBDA_DOCKER_NETWORK=my-automation_default
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TEMP_LOCALSTACK_DIR}
    volumes:
      - "${TEMP_LOCALSTACK_DIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  data01:
    driver: local
  data02:
    driver: local

FLOW i am trying to create :
![image](https://user-images.githubusercontent.com/54183749/128536633-714c13a0-055f-447f-823e-8768044d5d2b.png)

TO MAKE A SUCCESFULL CONNECTION BETWEEN APIGW AND LAMBDA , DO I HAVE TO ADD PERMISSIONS AS WELL?
No matter what i'm unable to make the connection and test the created apigw

**Comment by whummer** [comment]
Thanks for reporting @ashameem123 . 

> TO MAKE A SUCCESFULL CONNECTION BETWEEN APIGW AND LAMBDA , DO I HAVE TO ADD PERMISSIONS AS WELL?

No, you should not have to add any permissions in the default configuration.

We have slightly modified/adjusted the sample you've shared - running the bash script below seems to be working against the `latest` version of LocalStack. Can you please give this a try and confirm if it works for you? Also, kindly please share the full log output and more details of the command that yields the `UnrecognizedClientException` error. Thanks!

```
#!/bin/bash

awslocal lambda create-function --function-name my-mock-function --runtime python --handler handler.handler --role test --zip-file fileb://lambda.zip

api_id=$(awslocal apigateway create-rest-api --name 'my-mock-apigw' | jq -r .id)

parent_id=$(awslocal apigateway get-resources --rest-api-id $api_id | jq -r '.items[0].id')

res_id=$(awslocal apigateway create-resource --rest-api-id $api_id --parent-id $parent_id --path-part "POST" | jq -r .id)

awslocal apigateway put-method --rest-api-id $api_id --resource-id $res_id --http-method POST --request-parameters "method.request.header.Content-Type:application/json=true" --authorization-type "NONE"

awslocal apigateway put-method --rest-api-id $api_id --resource-id $res_id --http-method POST --request-parameters "integration.request.header.body-header.Content-Type:application/json=true" --authorization-type "NONE"

awslocal apigateway put-integration --rest-api-id $api_id --resource-id $res_id --http-method POST --type LambdaFunction --integration-http-method POST --uri arn:aws:apigateway:us-east-1:lambda:path/2021-08-06/functions/arn:aws:lambda:us-east-1:000000000000:function:my-mock-function/invocations --request-templates '{"application/json":"\"{\"statusCode\": $input.json('"'"'$.statusCode'"'"'), \"message\": $input.json('"'"'$.message'"'"')}\""}' --passthrough-behavior WHEN_NO_TEMPLATES

awslocal apigateway put-integration-response --rest-api-id $api_id --resource-id $res_id --http-method POST --status-code 200 --selection-pattern '2\d{2}'

awslocal apigateway put-method-response --rest-api-id $api_id --resource-id $res_id --http-method POST --status-code 200 --response-models "{}"

awslocal apigateway create-deployment --rest-api-id $api_id --stage-name test
```

**Comment by ashameem123** [comment]
@whummer -Please have a look and provide an update, I am really stuck with testing due to APIGW issue for most of the lambdas I'm working on.

**Comment by whummer** [comment]
Thanks for the update @ashameem123 - looking at the output from the screenshot which is printing `LAMBDAFUNCTION` as the integration type (automatically gets converted to uppercase), it seems that we need to adjust the `--type LambdaFunction` parameter in the script above:
```
awslocal apigateway put-integration --rest-api-id $api_id --resource-id $res_id --http-method POST --type AWS --integration-http-method POST --uri arn:aws:apigateway:us-east-1:lambda:path/2021-08-06/functions/arn:aws:lambda:us-east-1:000000000000:function:my-mock-function/invocations --request-templates '{"application/json":"\"{\"statusCode\": $input.json('"'"'$.statusCode'"'"'), \"message\": $input.json('"'"'$.message'"'"')}\""}' --passthrough-behavior WHEN_NO_TEMPLATES
```

(In fact, the integration type `LambdaFunction` does not seem to exist, but should be `AWS` instead). Hope that helps - please keep us posted how it goes. Thanks!

**Comment by ambreenshamim** [comment]
@whummer - getting different error now,
![image](https://user-images.githubusercontent.com/89807574/131576490-3e41bc87-f64c-495a-9737-04bc54c23084.png)

here is the function i am trying to integrate with apigw:
[mock-function.txt](https://github.com/localstack/localstack/files/7086822/mock-function.txt)

**Comment by whummer** [comment]
Thanks for the update - as discussed via chat, we can close this issue and continue the conversation elsewhere. Thanks
