### ISSUE TITLE
bug: Firehose ExtendedS3DestinationDescription is ignoring the "Extended" portions

### ISSUE THREAD

**Issue by josephpohlmann** [localstack/localstack#4417]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Please refer to closed ticket:  https://github.com/localstack/localstack/issues/496

Although this fix addressed the simple case of accepting, storing, and replying with "ExtendedS3DestinationDescription" for KinesisFirehose, it didn't actually address the fact that this information is not honored by the code.  Currently, it is treated identically to "S3DestinationDescription".

This means that things like the ProcessingConfiguration can never execute.

### Expected Behavior

If you'll look at line 98 of https://github.com/localstack/localstack/blob/master/localstack/services/firehose/firehose_api.py

This encapsulates the entirety of the work being done against an Extended configuration.  ProcessingConfiguration, at minimum, should be honored.

See:  https://docs.aws.amazon.com/firehose/latest/APIReference/API_ExtendedS3DestinationDescription.html

(In my current stack, I have a lambda acting as a filter/normalizer for firehose data.  I need to be able to have that data properly processed.)

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker-compose up

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal firehose describe-delivery-stream --delivery-stream-name=<mystream>

```json
{
    "DeliveryStreamDescription": {
        "DeliveryStreamName": "<mystream>",
        "DeliveryStreamARN": "arn:aws:firehose:us-east-1:<myid>:deliverystream/<mystream>",
        "DeliveryStreamStatus": "ACTIVE",
        "DeliveryStreamType": "DirectPut",
        "VersionId": "1",
        "CreateTimestamp": "2021-08-05T16:55:55.200126-04:00",
        "Destinations": [
            {
                "DestinationId": "21ad409a",
                "ExtendedS3DestinationDescription": {
                    "RoleARN": "arn:aws:iam::<myid>:role/<mystream>",
                    "BucketARN": "arn:aws:s3:::<mybucket>",
                    "Prefix": "incoming/!{timestamp:yyyy/MM/dd/}",
                    "ErrorOutputPrefix": "failures/!{firehose:error-output-type}/!{timestamp:yyyy/MM/dd/}",
                    "BufferingHints": {
                        "SizeInMBs": 5,
                        "IntervalInSeconds": 120
                    },
                    "CompressionFormat": "UNCOMPRESSED",
                    "EncryptionConfiguration": {
                        "NoEncryptionConfig": "NoEncryption"
                    },
                    "ProcessingConfiguration": {
                        "Enabled": true,
                        "Processors": [
                            {
                                "Type": "Lambda",
                                "Parameters": [
                                    {
                                        "ParameterName": "LambdaArn",
                                        "ParameterValue": "arn:aws:lambda:us-east-1:<myid>:function:<mylambda>:$LATEST"
                                    }
                                ]
                            }
                        ]
                    },
                    "S3BackupMode": "Disabled",
                    "DataFormatConversionConfiguration": {
                        "Enabled": false
                    }
                }
            }
        ],
        "HasMoreDestinations": false
    }
}
```

```bash
    awslocal firehose put-record --delivery-stream-name=<mystream> --record=Data=whatever
```
```json
{
    "RecordId": "b4793fe4-0348-48ca-b9c4-d89449639f8e"
}
```

NOTE:  The data does indeed make it to the S3 bucket, it's just that the lambda never processes it.

Oh, and also, firehose S3 Prefix does not appear to honor Custom Prefixes, per this page:  https://docs.aws.amazon.com/firehose/latest/dev/s3-prefixes.html

That is a much less concerning issue.

### Environment

```markdown
- OS: OSX (but in docker)
- LocalStack: latest
```

### Anything else?

See above...

**Comment by josephpohlmann** [comment]
I have coded up a solution to at least part of this bug/enhancement.  Just need to figure out how to get it to you for review.  Will do it tomorrow.  Thanks!

**Comment by ackdav** [comment]
Hi @josephpohlmann ! Thank you for raising this issue and starting with a fix! Would you be able to pull the latest localstack version and see if the issue persists? If yes, I'm happy to assist in making the PR!
Thanks!
