### ISSUE TITLE
Problem invoke lambda nodejs function

### ISSUE THREAD

**Issue by nolafs** [localstack/localstack#442]
Hi 

I am having issue running lambda nodejs function. When I invoke it I am receiving the following error:

```
REPORT RequestId: 4525d048-2030-1b53-d5a0-8bd678b8988f  Duration: 8.76 ms       Billed Duration: 100 ms Memory Size: 1536 MB    Max Memory Used: 28 MB  
 Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 298, in run_lambda
    result, log_output = run_lambda_executor(cmd, env_vars)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 384, in run_lambda_executor
    (return_code, log_output))
Exception: Lambda process returned error status code: 1. Output:
START RequestId: 4525d048-2030-1b53-d5a0-8bd678b8988f Version: $LATEST
Unable to import module 'twitterstream': Error
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
END RequestId: 4525d048-2030-1b53-d5a0-8bd678b8988f
REPORT RequestId: 4525d048-2030-1b53-d5a0-8bd678b8988f  Duration: 8.76 ms       Billed Duration: 100 ms Memory Size: 1536 MB    Max Memory Used: 28 MB 
```

I am running localstack in a docker container

Cheers
Olaf

**Comment by whummer** [comment]
Hi @nolafs , the error message indicates that your Lambda function attempts to import the `twitterstream` module, which does not appear to be present in your Lambda archive. Can you please check the contents of the zip file you're uploading to Lambda - does it contain a folder `twitterstream` or a file `twitterstream.js`?

Please note that this is out of scope for LocalStack, but there are plenty of projects out there which simplify the packaging of Lambda archives (e.g., Serverless project, Apex, ...)

**Comment by GeoffreyBooth** [comment]
I’m getting the same error. In my case I have a `.zip` file with just one `index.js` file, not in any folder; with just the following contents:

```js
exports.uploadHandler = function (event, context, callback) {
  console.log(event, context);
  callback();
};
```

I can create the function successfully, and running `awslocal lambda get-function --function-name uploadHandler` returns:

```json
{
    "Configuration": {
        "FunctionName": "uploadHandler",
        "FunctionArn": "arn:aws:lambda:us-west-1:000000000000:function:uploadHandler",
        "Runtime": "nodejs6.10",
        "Handler": "index.uploadHandler",
        "CodeSize": 50,
        "Timeout": 60,
        "Version": "$LATEST"
    },
    "Code": {
        "Location": "http://localhost:4574/2015-03-31/functions/uploadHandler/code"
    }
}
```

But running it (`awslocal lambda invoke --function-name uploadHandler output`) gives me the same error:

```bash
An error occurred (InternalFailure) when calling the Invoke operation (reached max retries: 4): Error executing Lambda function: Lambda process returned error status code: 1. Output:
START RequestId: 1129b0f1-b0de-1c59-a086-33aae95c492b Version: $LATEST
Unable to import module 'index': Error
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
END RequestId: 1129b0f1-b0de-1c59-a086-33aae95c492b
REPORT RequestId: 1129b0f1-b0de-1c59-a086-33aae95c492b	Duration: 9.51 ms	Billed Duration: 100 ms	Memory Size: 1536 MB	Max Memory Used: 28 MB
 Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 327, in run_lambda
    result, log_output = run_lambda_executor(cmd, env_vars, async)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 417, in run_lambda_executor
    (return_code, log_output))
Exception: Lambda process returned error status code: 1. Output:
START RequestId: 1129b0f1-b0de-1c59-a086-33aae95c492b Version: $LATEST
Unable to import module 'index': Error
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
END RequestId: 1129b0f1-b0de-1c59-a086-33aae95c492b
REPORT RequestId: 1129b0f1-b0de-1c59-a086-33aae95c492b	Duration: 9.51 ms	Billed Duration: 100 ms	Memory Size: 1536 MB	Max Memory Used: 28 MB
```

**Comment by GeoffreyBooth** [comment]
Could this be due to the bug fixed by #448? It appears there hasn’t been a new version pushed to hub.docker.com since that PR was merged in; do you mind releasing a new version?

**Comment by whummer** [comment]
Thanks for digging into this error @GeoffreyBooth . The configuration values for docker-compose are a bit fragile, and you seem to have hit a combination of environment variables and volume paths that breaks the logic for mounting code into the Lambda container. This should be fixed in #461 where we now default to using `LAMBDA_REMOTE_DOCKER=true` when executing inside docker-compose. 

@nolafs Can you also please give it a try with the latest version of the Docker image? Thanks

**Comment by whummer** [comment]
Closing this issue, as the problem appears to be fixed with the latest change. Please comment here if the problem persists. Thanks.

**Comment by benleim** [comment]
Is there a way to fix this without using `LAMBDA_REMOTE_DOCKER=true`? I'm wanting to set `mountCode=true`, which requires `LAMBDA_REMOTE_DOCKER=false`.
