### ISSUE TITLE
bug: [PRO] [Cognito IDP] ResourceNotFoundException when calling AdminEnableUser / AdminDisableUser operations

### ISSUE THREAD

**Issue by Caracal2021** [localstack/localstack#4421]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Calls to the Cognito AdminDisableUser and AdminEnableUser APIs have recently started failing with a ResourceNotFoundException. This is the error given:

`An error occurred (ResourceNotFoundException) when calling the AdminDisableUser operation: Cannot find resource: Unable to find handler for API method 'AdminDisableUser'`

The same error occurs using both the AWS SDK and the command line.

### Expected Behavior

These methods should work without issue.
As mentioned above, the error only started appearing recently. Unfortunately I can't recall the exact time when it first showed up, but it was some time within the last two weeks.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker-compose.yml

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal cognito-idp create-user-pool --pool-name Purgatorio
    // (copy the user pool id from the output)
    awslocal cognito-idp admin-create-user --user-pool-id [pool id] --username Developer123
    awslocal cognito-idp admin-create-user --user-pool-id [pool id] --username Developer123

### Environment

```markdown
- OS: Linux Amazon WorkSpace
- LocalStack: latest
```

**Comment by whummer** [comment]
Thanks for reporting @Caracal2021 . This should be (hopefully) fixed in the meantime - can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists. Thanks for your help!

**Comment by Caracal2021** [comment]
Yes, fixed for me now. Thanks a lot @whummer !
