### ISSUE TITLE
question: Do you plan to support using yaml format for openapi/swagger spec used by import-rest-api

### ISSUE THREAD

**Issue by NashSequeira** [localstack/localstack#4434]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Recently this issue was fixed: https://github.com/localstack/localstack/issues/171, but only for .json spec files. If using yaml format, it still uses the json parser, and get exception when calling `awslocal apigateway import-rest-api --body 'fileb://pets.yaml'`.

**Comment by thrau** [comment]
This feature is available in LocalStack pro. Should you have problems with the pro version, please let us know in Slack, thanks!
