### ISSUE TITLE
KMS keys not being persisted on latest docker image

### ISSUE THREAD

**Issue by gabrielmmontenegro** [localstack/localstack#4441]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi team,

Just a follow up that the latest localstack docker image isn't persisting KMS keys. 
After downgrading to version 0.12.10 the KMS persistence worked as expected.

PS: also tried adding "-e KMS_DATA_PATH=/tmp/local-kms" to the docker run command but it doesn't worked.

### How are you starting LocalStack?

With a `docker run` command

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run --restart always --name localstack -e DATA_DIR=/tmp/localstack/data -e SERVICES=s3,kms -p 4566:4566 -p 4571:4571 -d localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal kms create-key
    docker restart [container]
    awslocal kms list-keys

### Environment

```markdown
- OS: Ubuntu 20.04
- LocalStack: latest
```

**Comment by leonhandl3r** [comment]
Any response? I also stuck with it

**Comment by bentsku** [comment]
Hi @leonhandl3r, could you please open a new issue? This issue is from 2021 and had been solved then. Are you encountering a new issue with a different LocalStack version?
