### ISSUE TITLE
question: nodejs debug support

### ISSUE THREAD

**Issue by brucekaufman** [localstack/localstack#4443]
### Is there an existing issue for this?

- [X] I have searched the existing issues and read the documentation

### Question

Is it possible to enable debug of nodejs lambda functions running inside a docker container in local stack?  I can't find any documentation on this anywhere.  Localstack is a wonderful tool and we are evaluating using it for our developers but not being able to debug will probably kill its adoption.

**Comment by pradyum619** [comment]
I want to achieve the same, need to add breakpoints to nodejs lambda function, but unable to do it. Any idea on how to do this?
I am using vsCode

**Comment by whummer** [comment]
Thanks for reporting @brucekaufman @pradyum619 . We have published a small sample that demonstrates debugging of Python Lambdas inside Visual Studio Code: https://github.com/localstack/localstack-pro-samples/tree/master/lambda-mounting-and-debugging 

Perhaps that can help as a starting point. We're planning to invest quite some time to improve the debugging experience for Lambda functions over the next couple of weeks. 

Can you please share some details about your particular use case - which IDE are you using, can you share some details about the logic in your Lambda handlers, etc.? Thanks!

**Comment by brucekaufman** [comment]
Hi @whummer - I actually was able to get nodejs debugging working (with some limitations) using vscode as the IDE.  I have a prototype project repo which I am willing to share, but it is currently in my company's private github - I am working to make this public so that I can share it with you.  I'll reach out with a link as soon as it is available.

**Comment by whummer** [comment]
That would be fantastic @brucekaufman , we'll be happy to promote your work in this repo and make any required changes to simplify the integration of nodejs Lambda debugging.. Looking forward to learning about your insights!!

**Comment by brucekaufman** [comment]
hi @whummer I was able to get permission to open this repo up to the public -

https://github.com/himarley/microservice-prototype

I am going to work on improving the documentation here and probably adding some automation around deployment of the contrived services.  One thing to note is that the debug functionality is currently broken with the newest version of localstack - I put up a PR last night which is intended to address this here:

https://github.com/localstack/localstack/pull/4766
