### ISSUE TITLE
bug: website certificate expired

### ISSUE THREAD

**Issue by pwillis-els** [localstack/localstack#4453]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The https://roadmap.localstack.cloud/ website appears to have an expired certificate

### Expected Behavior

Browsing the site displays a valid cert

### How are you starting LocalStack?

With the `localstack` script

### Steps To Reproduce

Browse website, see certificate warning

**Comment by whummer** [comment]
Hi @pwillis-els , thanks for bringing this to our attention. The certificate has now been update. Thanks for your help! 👍
