### ISSUE TITLE
AWS CLI SQS for localstack - cannot set queue attributequestion: <title>

### ISSUE THREAD

**Issue by kicaj29** [localstack/localstack#4462]
### Is there an existing issue for this?

- [X] I have searched the existing issues and read the documentation

### Question

I am trying to change one of queue parameters in my localstack but it does not work. I am getting the following errors:

```
aws sqs set-queue-attributes --queue-url http://localhost:4566/000000000000/BatchReadyToProcessRequest --attribute VisibilityTimeout=3600 

An error occurred (InvalidAddress) when calling the SetQueueAttributes operation: The address https://sqs.us-east-2.amazonaws.com/ is not valid for this endpoint.
```

Any idea why it is trying to talk to amazonaws.com when I use localstack?

The queue name is correct because it is returned by command

`aws --endpoint-url=http://localhost:4566 sqs list-queues`

I am following these docs: https://awscli.amazonaws.com/v2/documentation/api/latest/reference/sqs/set-queue-attributes.html

**Comment by mgagliardo** [comment]
Hello @kicaj29, it looks you are missing the `--endpoint-url http://localhost:4566` on your command.

So it should be:

`aws sqs set-queue-attributes --endpoint-url http://localhost:4566 --queue-url http://localhost:4566/000000000000/BatchReadyToProcessRequest --attribute VisibilityTimeout=3600`

Let me know how it goes. Cheers

**Comment by kicaj29** [comment]
Yes - it is working now - so simple :)

But then there is bug in docs https://awscli.amazonaws.com/v2/documentation/api/latest/reference/sqs/change-message-visibility.html
Even in the example --endpoint-url param is not used.
