### ISSUE TITLE
Feature request: Cognito UsernameExistsException: User creation

### ISSUE THREAD

**Issue by Daveo24** [localstack/localstack#4465]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

If I run the following command twice...

`aws cognito-idp admin-create-user --endpoint-url http://localhost:4566 --user-pool-id $pool_id --username user-test`

What I would like to see is some validation similar to aws cognito, currently it responds saying it has created the user-test although there is only ever one user of that name.

`An error occurred (UsernameExistsException) when calling the AdminCreateUser operation: User account already exists`

**Comment by whummer** [comment]
Thanks for reporting @Daveo24 - this should be fixed in the meantime. Can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists. Thanks for your help!

**Comment by Daveo24** [comment]
Works a treat @whummer thank you, is there anyway we can contribute to the pro version? Our company has pro licenses enabled.

I have one other feature request with regards to cognito so will raise that later today. Thanks again for your time and effort.
