### ISSUE TITLE
question: Localstack Pro - Cognito - Which calls are not implemented?

### ISSUE THREAD

**Issue by James654987** [localstack/localstack#4476]
### Is there an existing issue for this?

- [X] I have searched the existing issues and read the documentation

### Question

I get a ResourceNotFound exception with certain Cognito calls and I'm wondering if they just aren't implemented yet? Currently I see this with `AdminResetUserPassword` and `RespondToAuthChallenge`

I read through the documentation [here](https://localstack.cloud/docs/reference/cognito/) and it says "LocalStack Pro contains basic support for authentication via AWS Cognito" so it sounds like not everything would be implemented.

I'm using LocalStack version 0.12.16

**Comment by whummer** [comment]
Thanks for the update @James654987 - feature coverage for Cognito should be reasonably high by now (ResourceNotFound could be related to a region mismatch, potentially). 

Can you please share a few more details about your environment setup and your use case (ideally a few snippets of your client code). We'll be happy to look into it in more detail.. Thanks for your help!

**Comment by James654987** [comment]
Thanks for the reply. I'm running .Net 3.1 and have a method in our test project that starts up a docker container using the 0.12.16 image from docker hub.

```
var response = await _dockerClient.Containers.CreateContainerAsync(new CreateContainerParameters
                {
                    Name = _containerName,
                    Image = _imageName,
                    ExposedPorts = new Dictionary<string, EmptyStruct>
                {
                    { "4566", default},
                    { "8081", default},
                    { "443", default},
                },

                    HostConfig = new HostConfig
                    {
                        PortBindings = new Dictionary<string, IList<PortBinding>>
                    {
                        {"4566", new List<PortBinding> {new PortBinding { HostPort = "4566" } }},
                        {"8081", new List<PortBinding> {new PortBinding { HostPort = "8081" } }},
                        {"443", new List<PortBinding> {new PortBinding { HostPort = "443" } }}
                    }
                    },
                    Env = new List<string> { "SERVICES=cognito", "PORT_WEB_UI=8081", "LOCALSTACK_API_KEY=***" }
                });
```
The ResourceNotFound exception gets thrown from this line: 

`resp = await CognitoClient.AdminResetUserPasswordAsync(new AdminResetUserPasswordRequest { Username = "reset-user-password-test", UserPoolId = "us-east-1_a4df258671514d5590ad68e54b5502ca" });`

(the values above are not hard-coded in our implementation, but I printed them here for ease)

As far as I can tell, the same region and PoolId is used throughout the test cycle and everything uses the same localstack/cognito instance as only is created during the tests, then disposed of when the tests have finished.

I also tried calling AdminGetUser right before AdminResetUserPassword and it correctly retrieves the user details. 
One thing I noticed though is that is shows the users's status "enabled" as false. I tried running AdminEnableUser to enable it, but this call also throws the ResourceNotFound exception.

**Comment by whummer** [comment]
Thanks for the update @James654987 . You mentioned that you're using the `0.12.16` image - can you please give it a try with with `latest` Docker image tag? We have just pushed a few enhancements which should (hopefully) get this issue resolved. 

Otherwise, if the problem persists, can you please help us run a few diagnostic commands using the `awslocal` command line:
```
$ awslocal cognito-idp list-user-pools --max-results 10
...
$ awslocal cognito-idp list-users --user-pool-id ...
...
```
Thanks!

**Comment by whummer** [comment]
Thanks for the update @James654987 , and apologies for the long delay on this one. In the meantime, we have significantly extended our Cognito implementation, and added support for the missing APIs that were mentioned above (including `AdminResetUserPassword`, `RespondToAuthChallenge`, etc). Also, the integration with API Gateway Cognito authorizers has been extensively tested and seems to be working reasonably well for most users, based on the feedback we're receiving.

> As far as I can tell, the same region and PoolId is used throughout the test cycle and everything uses the same localstack/cognito instance as only is created during the tests, then disposed of when the tests have finished.

That is correct - the `PoolId` is a generated value, and by default the state is disposed of once the LocalStack instance terminates. You can try making use of the persistence feature (by pointing the `DATA_DIR` config to a persistent folder/volume on your machine), in which case the state would get preserved across restarts of LocalStack.

Hope that helps - please keep us posted how it goes with the `latest` Docker image. we'll be happy to dig into it in more details in case you're still experiencing any problems. Thanks for your help!
