### ISSUE TITLE
question: Anyway to make the created log group and log stream persist?

### ISSUE THREAD

**Issue by Thiti-Dev** [localstack/localstack#4478]
### Is there an existing issue for this?

- [X] I have searched the existing issues and read the documentation

### Question

I persist the s3 data by making the  tmp/localstack binded and everything's fine but I also wanted to make the things that are created in logs(service) persist too. How can I archive this?

**Comment by thrau** [comment]
This feature is available in LocalStack pro. Should you have problems with the pro version, please let us know in Slack, thanks!
