### ISSUE TITLE
feature request:  Support email-json for SNS subscription

### ISSUE THREAD

**Issue by kornicameister** [localstack/localstack#4484]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

I would like to request extending `sns_listener` with an ability to understand `email-json` next to `email` protocol.

### 🧑‍💻 Implementation

1. check if protocol is `email` or `email-json`
2. for email json interpret body/message as json

**Comment by whummer** [comment]
Hi @kornicameister , thanks for reporting. Looks like you already have a fairly good idea about the implementation approach for this feature - do you think you could create a first draft pull request with these changes? That would be really appreciated. Thanks!

**Comment by iamrajiv** [comment]
@whummer I want to work on this.
