### ISSUE TITLE
Localstack PRO:-Enable/Increase logs for localstack_bigdata docker container

### ISSUE THREAD

**Issue by HritikBangar** [localstack/localstack#4490]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Whenever any athena query is made , localstack container spins localstack_bigdata container. In order to debug my code, i need logs from localstack_bigdata container to see things going wrong. But when i try to see the logs of that container , following are the only logs i see
`rm: cannot remove '/tmp/*.pid': No such file or directory

/

[ OK ] OpenBSD Secure Shell server sshd        

Waiting for hdfs to exit from safemode

Safe mode is OFF

Started`

### Anything else?

![image](https://user-images.githubusercontent.com/35094048/130845524-73d439bd-a0f7-4e8e-a9a9-5d02f4e7246b.png)

**Comment by whummer** [comment]
Thanks for reporting @HritikBangar , and apologies for the delay. Please note that the `localstack_bigdata` container is running a bunch of different processes (Hive, Presto, Hadoop, Spark, etc), most of which are logging to separate log files, and not to stdout of the container. 

The best place to start digging into the different log files would be to `exec` into the container and output the log files in `/tmp` and inside `/var/log`:
```
$ docker exec -it localstack_bigdata bash
# cat /tmp/hdfs-namenode.log 
...
# cat /tmp/hive-metastore.log
...
# cat /tmp/hiveserver2.log
...
# cat /tmp/presto.log
...
```

Also, please note that the majority of relevant logs should get forwarded and printed in the main LocalStack container (with `DEBUG=1` enabled in the environment).

Hope that helps - please keep us posted how it goes. If you could share a few more details about your specific use case and requirements, we'll be happy to look into it. (Please feel free to reach out directly via email or Slack..) Thanks for your help!
