### ISSUE TITLE
question: Is it possible to use _custom_id_ on API Gateway with Terraform?

### ISSUE THREAD

**Issue by kevinhill83** [localstack/localstack#4499]
### Is there an existing issue for this?

- [X] I have searched the existing issues and read the documentation

### Question

> Providing custom IDs for API Gateway REST APIs: You can specify tags={"_custom_id_":"myid123"} on creation of an API Gateway REST API, to assign it the custom ID "myid123" (can be useful to have a static API GW endpoint URL for testing).

I'm wondering if it is possible to specify the _custom_id_ in a project using Terraform with LocalStack?

Using: 

```
resource "aws_api_gateway_rest_api" "myAPI" {
  name        = "myAPI"
  tags = {
      _custom_id_ = "myid123"
  }
}
```

still resulted in a random id being created for the API

**Comment by radufilipescu** [comment]
actually you can, check this out:

https://github.com/localstack/localstack-terraform-samples/blob/master/apigateway-custom-id/main.tf
