### ISSUE TITLE
Unable to use self-signed certs - CN incorrect, and/or missing subject alternative name field

### ISSUE THREAD

**Issue by stevebakh** [localstack/localstack#451]
When enabling SSL for the services (required as the Kinesis producer will only support HTTPS), I would like to add the generated self-signed cert to my java truststore so that I can interact with the services. In some instances, I can disable SSL verification, but in others I cannot (for example, when using the Jest ES client library). 

I have tried adding the generated certs to my truststore, however, there is no Subject Alternative Name field, and the CN on the cert doesn't match the host (localhost in this instance), so I'm unable to make use of the cert. If I add a `localstack` entry to my hosts file, it works.

The error essentially looks like this:

```
Caused by: javax.net.ssl.SSLPeerUnverifiedException: Certificate for <localhost> doesn't match any of the subject alternative names: []
```
Please consider setting the certificate CN to the configured hostname (defaulting to localhost), and or add the subject alternative name field to the cert, which would include the various DNS entries to enable use of the cert.

**Comment by whummer** [comment]
Thanks for reporting @stevebakh . The relevant code can be found in [`commons.py`](https://github.com/localstack/localstack/blob/master/localstack/utils/common.py#L501-L553). Would you be able to create a pull request with the required changes? Thanks

**Comment by stevebakh** [comment]
Hi @whummer - thanks for the reply.

I hate to be _that_ guy, so, sorry in advance! :(

I'm not sure I'd be best placed to make the change. I'm unfamiliar with the project's code base (not to mention Python!) 
The easiest/simplest solution, I imagine, would be to use the hostname for the CN value, which means passing it into that function. While updating the existing code to set the CN would make the certs at least usable, an even better solution would be to generate certs using letsencrypt, and then users wouldn't have to disable SSL verification or add the certs to their truststores.

Somebody better acquainted with the code and the testing framework in use would make much shorter work of it than I would, though.

**Comment by roek5803** [comment]
Hi @stevebakh 

I'm currently trying to start localstack with USE_SSL set to true. But can't figure out how. Were you able to make it work?

When creating a dynamoDB table i get this error:
```
! sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

And right now i set the endpoint to:
```
https://localhost:4569
```

So if i understand you correctly i should add localstack to my /etc/hosts file and add the generated certs to the truststore (and change the endpoint to https://localstack:4569). Where is the generated certs located?

**Comment by whummer** [comment]
Thanks for providing more details @stevebakh @roek5803 

> an even better solution would be to generate certs using letsencrypt

This is unfortunately not possible with `localhost` APIs. I'm afraid we won't be able to provide local HTTPS APIs that can be validated out of the box with default configuration of most SSL libraries - this is an inherent limitation (in fact - it's not a bug, it's a feature!).

But most SDKs/clients should allow you to add a setting to skip certificate validation (please use this configuration only for testing, not for production).

If you have any more insights into this issue or find out some other solution, please report back here. Thanks
