### ISSUE TITLE
RedisConnectionException:Unable to bridge Localstack and Redis containers together so the lambda can find the active redis connection and can be triggered

### ISSUE THREAD

**Issue by ashameem123** [localstack/localstack#4514]
### Is there an existing issue for this?

- [X] I have searched the existing issues and read the documentation

### Question

I have a lambda that should trigger when there is an active Redis conncetion.
I am able to create a redis container but not sure if my localstack container is able to bridge with Redis correctly. 
Getting below exception  on uploading a file in s3 which should trigger lambda

**Unable to connect to master.de-duplication-redis-rep.w5fy5n.use1.cache.amazonaws.com:6379: io.lettuce.core.RedisConnectionException**

Flow I'm trying to test?:
![image](https://user-images.githubusercontent.com/54183749/131393819-a11a954e-6000-4de7-bcd8-4781cbd8bbc4.png)

Docker-Compose file :

version: '3.9'

services:

  redis:
    image: redis
    container_name: redis
    hostname: redis
    ports:
      - 6379:6379

  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
      - "443:443"
    environment:
      - SERVICES=${SERVICES- }
      - DEBUG=1
      - DATA_DIR=${DATA_DIR- }
      - LAMBDA_EXECUTOR=docker
    #  - LAMBDA_REMOTE_DOCKER=false
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LAMBDA_DOCKER_NETWORK=my-automation_default
      - HOST_TMP_FOLDER=${TEMP_LOCALSTACK_DIR}
    volumes:
      - "${TEMP_LOCALSTACK_DIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  data01:
    driver: local
  data02:
      driver: local

networks:
  my-automation_default:
    driver: bridge

### Anything else?

Logs:
[output.txt](https://github.com/localstack/localstack/files/7079098/output.txt)

**Comment by ambreenshamim** [comment]
@whummer -Please have a look, The bridging looks good but still getting RedisConnectionException,

![image](https://user-images.githubusercontent.com/89807574/131748898-27337152-a2c9-41df-8941-5f4cb6d3d142.png)

**Comment by whummer** [comment]
Thanks for reporting @ambreenshamim - can you please paste the relevant snippet of your Lambda code which causes the exception, as well as ideally a full stacktrace of the error (if available). Thanks!

**Comment by ambreenshamim** [comment]
@whummer - I sent you the code snippet and output logs in the chat.

**Comment by ashameem123** [comment]
thanks working as expected with latest docker pull
