### ISSUE TITLE
Expand LAMBDA_FORWARD_URL functionality

### ISSUE THREAD

**Issue by adamlewisgucci** [localstack/localstack#4519]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

LAMBDA_FORWARD_URL is a useful idea but a little restricted for whenever you want to have more than one lambda redirected. I would like to request the development of:

LAMBDA_FORWARD_URLS

Where the value is a comma separated list of <lambda-name>=<endpoint> such as:
LAMBDA_FORWARD_URLS=a-lambda=http://a-lambda:9001,b-lambda=http://b-lambda:9001

This would enable us to use docker-compose with multiple lambdas **without** requiring docker-in-docker techniques.

### 🧑‍💻 Implementation

When invoking lambda, I imagine localstack would:
- Invoke the specific LAMBDA_FORWARD_URLS value
- Invoke the LAMBDA_FORWARD_URL value
- Invoke the lambda as uploaded locally

**Comment by whummer** [comment]
Hi @adamlewisgucci , thanks for suggesting this feature/extension. Can you please share some more details about your end-to-end use case, so we can understand and scope this request a bit better? 

I noticed that you're using 9001 - am I right in assuming that you're using [LambCI](https://github.com/lambci/docker-lambda) containers listening on that port, or is something else listening on `http://[a|b]-lambda:9001`? 

In any case, I guess we'd be interested to learn if you're facing any particular limitations (e.g., performance, runtime compatibility, debugging support, etc.) with the current Lambda execution modes provided by LocalStack - that feedback would be very helpful for us to optimize the end-to-end Lambda capabilities within the platform. Thanks for your help!

**Comment by adamlewisgucci** [comment]
You would be correct to guess lambci containers 👍 

To give a fuller history, we've been pushing the boundaries of what's possible with a lambda recently. As we needed to use a .jar file to talk to a particular service, we chose to implement a kotlin lambda that executes in the java11 runtime (The actual number might be incorrect). When we compile a fat jar and upload to aws of the form com.package.my.HandlerClass:handlerMethod it works. Having spent some time yesterday trying to run the same in LocalStack we hit problems. There are issues I can see in GitHub hitting at historical problems that fat jars aren't supported/the handler syntax/it will only invoke it if you're inheriting a certain class but nothing that looks like an easy fix vs "just use lambci because we know it works".

LocalStack was going to be a bit of a cherry-on-top solution, as our lambda is triggered by SQS. Invoking purely to the lambci container means we have to wrap our payload in an SQS body first. Invoking via SQS pointed to the lambda would have made the developer experience nicer but this has been abandoned.

We found the "LAMBDA_FORWARD_URL" feature and did in fact get it to work, but felt it wasn't a pattern we would want to establish as it is limited by the fact that it would only work for instances where we run up systems of only one lambda running in lambci, not n lambdas running in lambci.

**Comment by whummer** [comment]
Thanks for providing the context @adamlewisgucci 👍 . Essentially, were also using lambci containers under the covers, however with a few customizations applied, and currently not using their built-in "stay open" mode (we're currently using our own `docker-reuse` mechanism).

We're currently very actively working on various Lambda enhancements - ranging from performance improvements, to better debugging capabilities, persistence/versioning support, etc. So, looks like we're in the same boat when it comes to pushing the boundaries of what's possible with local Lambda execution! Do you think you could share a small project that we could take as a starting point to work on some of these extensions? Perhaps we can come up with a nice joint approach that can also be leveraged by the broader community - would be a nice outcome. 👍  Thoughts?

**Comment by dotdashnotdot** [comment]
Providing an example on company time would be a bit of a no-no, so I've put this together tonight in my spare time to highlight roughly what the use case would look like. General idea/goal as already highlighted is to implement <SERVICE>_BACKEND type functionality for lambda 👍 

[LocalStack.zip](https://github.com/localstack/localstack/files/7094385/LocalStack.zip)

**Comment by adamlewisgucci** [comment]
@whummer - any update on this?

**Comment by adamlewisgucci** [comment]
It's been one year... I'm guessing this isn't going to be dealt with - so this is the last time I'll respond to the bot
