### ISSUE TITLE
bug: Memory leak

### ISSUE THREAD

**Issue by empeekdev** [localstack/localstack#4524]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We use localstack for simulating s3 service. For the last month we have issues with memory leak of something. For some reasons localstack uses more than 50 gb RAM! It’s not even staging environment so we do not understand why localstack use so much memory. Also, this memory usage causes the server to crash and it stop to accept any requests. Localstack version - 0.11.3.3, startup type - via localstack cli with --docker flag. Have you any thoughts about my problem?

### Expected Behavior

Localstack should not use so much RAM

### How are you starting LocalStack?

With the `localstack` script

### Steps To Reproduce

Install and run localstack 0.11.3.3. Wait some time - after 10-15 minutes should take a lot of RAM

### Environment

```markdown
- OS: Ubuntu 18.04
- LocalStack:  0.11.3.3
```

**Comment by empeekdev** [comment]
Closing this issue because problem possibly related to our misconfigurations

**Comment by whummer** [comment]
Thanks for the update @empeekdev - out of curiosity, is there anything you can share with the community, so other people don't run into similar configuration issues? That would be great, thanks! If you're experiencing any issues that look like legitimate memory leaks in LocalStack, please do let us know (ideally with an isolated reproducible example). Thanks!
