### ISSUE TITLE
Unable to login to ECR registry to push image

### ISSUE THREAD

**Issue by cbellinz** [localstack/localstack#4525]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Starting localstack with ecr service enabled allows me to create a repository which i can query:

```
{
    "repository": {
        "repositoryArn": "arn:aws:ecr:eu-west-1:000000000000:repository/xxx/stateless-worker",
        "registryId": "aaa711d0",
        "repositoryName": "xxx/stateless-worker",
        "repositoryUri": "aws.xxx.local:4510/xxx/stateless-worker",
        "createdAt": "2021-09-01T13:10:12+01:00",
        "imageTagMutability": "MUTABLE",
        "imageScanningConfiguration": {
            "scanOnPush": false
        },
        "encryptionConfiguration": {
            "encryptionType": "AES256"
        }
    }
}
```

When i try to login to the registry to push an image or even curl the registry, i get an EOF  or no response.

E.g.:

docker login --username AWS http://aws.xxx.local:4510/xxx/stateless-worker

- results in: Error response from daemon: Get "http://aws.xxx.local:4510/v2/": EOF

E.g.:

curl http://aws.xxx.local:4510/v2/

- results in: curl: (52) Empty reply from server

We recently upgraded our localstack version to latest from 0.12.11 which did allow us to upload containers.

### Expected Behavior

Container registry should be working on the advertised port in the repository URI and allow pushes from host using docker commands.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

Compose File

```
services:
  localstack:
    image: localstack/localstack:latest
    # image: localstack/localstack:0.12.11
    ports:
      - "8080:8080"
      - "4566:4566"
      - "4510:4510"
      - "4571:4571"
    environment:
      - LOCALSTACK_API_KEY=123456
      - DEFAULT_REGION=eu-west-1
      - HOSTNAME_EXTERNAL=aws.xxx.local
      - DATA_DIR=/tmp/localstack/data
      - DEBUG=1
      - LAMBDA_REMOTE_DOCKER=0
      - SERVICES="edge,serverless,kms,secretsmanager,s3,ecr,cloudformation,cloudwatch,sts,logs,sqs,sns,ssm,events"
      - LAMBDA_EXECUTOR=local
    volumes:
      - "${PWD}/localstack/tmp:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

```

Commands to recreate

```
awslocal ecr create-repository --repository-name xxx/stateless-worker --image-tag-mutability MUTABLE
existing_repository_uri=$(awslocal ecr describe-repositories --repository-names xxx/stateless-worker --query "repositories[0].repositoryUri" --output text)
# Requires a basic dockerfile
docker build -t ${existing_repository_uri}:1.0.0 .
awslocal ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin ${existing_repository_uri}
docker push ${existing_repository_uri}:1.0.0

```

### Environment

```markdown
- OS: Mac OSX 11.5.2
- LocalStack: 0.12.17.3
```

**Comment by jim-sheldon** [comment]
To piggyback on this: 

I can't login either, but I can use the boto3 ECR client methods `describe_repositories()` and `get_authorization_token()` methods.
(Assuming I can `push()` without first logging in to ECR) I use docker-py's `push()` method to upload images to ECR, which does not throw any exception.
So then I run the boto3 ECR `describe_images` command to see if `push()` worked, and localstack crashes with the following exception:
```
MyHTTPConnectionPool(host='localhost', port=4510): Max retries exceeded with url: /v2/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f433cfaf4d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
```
 
Also, using docker-py's `login()` method throws the following exception:
```
docker.errors.APIError: 500 Server Error: Internal Server Error ("b'{"message":"Get http://localhost:4510/v2/: dial tcp [::1]:4510: connect: connection refused"}'")
```

**Comment by whummer** [comment]
Thanks for reporting @cbellinz @jim-sheldon . This should be fixed in the meantime - can you please pull the `latest` version and give it another try? Please let us know if the problem persists.. Thanks for your help!

**Comment by cbellinz** [comment]
Thanks @whummer. I can confirm that i am now able to login and upload to ECR using Docker client.

**Comment by jim-sheldon** [comment]
Same, thank you @whummer!

**Comment by Cpinto0594** [comment]
Hi i'm facing this issue when executing this command:

aws ecr --region us-west-2 --profile localstack --endpoint-url=https://localhost.localstack.cloud:4566 get-login-password | docker login  --username AWS --password-stdin localhost.loc
alstack.cloud:4511/PROJECT_NAME

list index out of range
Error: Cannot perform an interactive login from a non TTY device

aws version:
aws-cli/2.4.4 Python/3.8.8 Windows/10 exe/AMD64 prompt/off

Localstack image:
  image: localstack/localstack:0.13
