### ISSUE TITLE
ApiKeyRequired in API Gateway not working from cloudformation

### ISSUE THREAD

**Issue by lordoflairs** [localstack/localstack#4529]
Hello,
I have tried to create a mock integration in api gateway from cloudformation.
Tested with latest (105b2dd7ba2c) docker-image.

We would like to be able to test our api-keys in api gateway but setting up ApiKeyRequired does not seem to work.

Using attached template.yml
Running:
aws cloudformation create-stack --stack-name api-gateway --template-body file://template.yml --endpoint-url=http://localhost:4566
aws apigateway get-rest-apis --endpoint-url=http://localhost:4566
aws apigateway get-resources --rest-api-id ${CREATED_REST_API_ID} --endpoint-url=http://localhost:4566

But the response here is apiKeyRequired = false
```
{
    "items": [
        {
            "id": "rootId",
            "path": "/"
        },
        {
            "id": "childId",
            "parentId": "rootId",
            "pathPart": "mock",
            "path": "/mock",
            "resourceMethods": {
                "POST": {
                    "httpMethod": "POST",
                    "authorizationType": "NONE",
                    "apiKeyRequired": false,
                    "methodIntegration": {
                        "type": "MOCK",
                        "requestParameters": {},
                        "requestTemplates": {
                            "application/json": "{\"statusCode\": $input.json('$.statusCode'), \"message\": $input.json('$.message')}"
                        },
                        "passthroughBehavior": "WHEN_NO_MATCH",
                        "cacheNamespace": "d30e4c73",
                        "cacheKeyParameters": []
                    }
                }
            }
        }
    ]
}
```
It is also possible to access the endpoint without providing an api key.
```
curl -v -H "Content-Type: application/json" http://localhost:4566/restapis/${CREATED_REST_API_ID}/LATEST/_user_request_/mock -d ' 
{"statusCode":200}
'
```

Expecting forbidden as when this template is run in AWS.

Regards,
Björn Bohlin
[template.zip](https://github.com/localstack/localstack/files/7097904/template.zip)

**Comment by dominikschubert** [comment]
Fixed in #4610
