### ISSUE TITLE
bug: ses bounce email simulator and sns, sqs, lambda trigger

### ISSUE THREAD

**Issue by nparfait** [localstack/localstack#4531]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Using the SES bounce email simulator with an SNS Topic and SQS Queue with a lambda trigger does not trigger the lambda and the message body content is not correct.
SES -> SNS -> SQS -> lambda

The message that ends up on the SQS Queue looks like the below.
The Body element is not correct it has a "Message" object which should not be there. 

{
    "Messages": [
        {
            "MessageId": "3049e02d-9f4f-0197-0302-48a8a9c5a66e",
            "ReceiptHandle": "krdytjsnsvyhnayptflagdkbjycyqnevjsujirbggscsziyylkgesggvvckidrxlvjzidxapmuwlxjilwycldntpjvwejpzaujgetqqmtqhkqmvifoczpriucfavhsytqratdbhcpmefwuhbwzvitpuhhlhomvjpavgquqtwwrjpyhmszafmmeebd",
            "MD5OfBody": "be9bf0773f654680629163de32d74c14",
            "Body": "{\n  \"Message\": {\n    \"bounce\": {\n      \"bounceSubType\": \"General\",\n      \"bounceType\": \"Permanent\",\n      \"bouncedRecipients\": [\n        {\n          \"action\": \"failed\",\n          \"diagnosticCode\": \"smtp; 550 user unknown\",\n          \"emailAddress\": \"recipient1@example.com\",\n          \"status\": \"5.0.0\"\n        },\n        {\n          \"action\": \"delayed\",\n          \"emailAddress\": \"recipient2@example.com\",\n          \"status\": \"4.0.0\"\n        }\n      ],\n      \"feedbackId\": \"000001378603176d-5a4b5ad9-6f30-4198-a8c3-b1eb0c270a1d-000000\",\n      \"remoteMtaIp\": \"127.0.2.0\",\n      \"reportingMTA\": \"example.com\",\n      \"timestamp\": \"2012-05-25T14:59:38.605Z\"\n    },\n    \"mail\": {\n      \"commonHeaders\": {\n        \"date\": \"Mon, 08 Oct 2018 14:05:45 +0000\",\n        \"from\": [\n          \"Sender Name <sender@example.com>\"\n        ],\n        \"messageId\": \" custom-message-ID\",\n        \"subject\": \"Message sent using Amazon SES\",\n        \"to\": [\n          \"Recipient Name <recipient@example.com>\"\n        ]\n      },\n      \"destination\": [\n        \"recipient@example.com\"\n      ],\n      \"headers\": [\n        {\n          \"name\": \"From\",\n          \"value\": \"\\\"Sender Name\\\" <sender@example.com>\"\n        },\n        {\n          \"name\": \"To\",\n          \"value\": \"\\\"Recipient Name\\\" <recipient@example.com>\"\n        }\n      ],\n      \"headersTruncated\": false,\n      \"messageId\": \"000001378603177f-7a5433e7-8edb-42ae-af10-f0181f34d6ee-000000\",\n      \"sendingAccountId\": \"000000000000\",\n      \"source\": \"sender@example.com\",\n      \"sourceArn\": \"arn:aws:ses:us-west-2:888888888888:identity/example.com\",\n      \"sourceIp\": \"127.0.3.0\",\n      \"timestamp\": \"2018-10-08T14:05:45 +0000\"\n    },\n    \"notificationType\": \"Bounce, Complaint, or Delivery.\"\n  },\n  \"MessageId\": \"f1bb6190-5dbe-48cb-9e0e-44c846bd6ed8\",\n  \"Signature\": \"EXAMPLElDMXvB8r9R83tGoNn0ecwd5UjllzsvSvbItzfaMpN2nk5HVSw7XnOn/49IkxDKz8YrlH2qJXj2iZB0Zo2O71c4qQk1fMUDi3LGpij7RCW7AW9vYYsSqIKRnFS94ilu7NFhUzLiieYr4BKHpdTmdD6c0esKEYBpabxDSc=\",\n  \"SignatureVersion\": \"1\",\n  \"SigningCertURL\": \"https://sns.us-east-1.amazonaws.com/SimpleNotificationService-f3ecfb7224c7233fe7bb5f59f96de52f.pem\",\n  \"Subject\": \"my subject\",\n  \"Timestamp\": \"2021-09-02T11:47:39.606Z\",\n  \"TopicArn\": \"arn:aws:sns:us-east-1:000000000000:ses_bounces_topic\",\n  \"Type\": \"Notification\",\n  \"UnsubscribeURL\": \"https://sns.us-east-1.amazonaws.com/?Action=Unsubscribe&SubscriptionArn=arn:aws:sns:us-east-1:000000000000:some-topic:2bcfbf39-05c3-41de-beaa-fcfcc21c8f55\"\n}"
        }
    ]
}

### Expected Behavior

When executing this in the real AWS environment, the body does not contain Message.

{
    "Messages": [
        {
            "MessageId": "2d721a55-efb6-43a5-8dc7-xxx",
            "ReceiptHandle": "xxx",
            "MD5OfBody": "xxx",
            "Body": "{\n  \"Type\" : \"Notification\",\n  \"MessageId\" : \"60897e9b\",\n  \"TopicArn\" : \"arn:aws:sns:ap-southeast-2:000000000000:ses_bounces_topic\",\n  \"Message\" : \"{\\\"notificationType\\\":\\\"Bounce\\\",\\\"bounce\\\":{\\\"feedbackId\\\":\\\"aaaaa\\\",\\\"bounceType\\\":\\\"Permanent\\\",\\\"bounceSubType\\\":\\\"General\\\",\\\"bouncedRecipients\\\":[{\\\"emailAddress\\\":\\\"bounce@simulator.amazonses.com\\\",\\\"action\\\":\\\"failed\\\",\\\"status\\\":\\\"5.1.1\\\",\\\"diagnosticCode\\\":\\\"smtp; 550 5.1.1 user unknown\\\"}],\\\"timestamp\\\":\\\"2021-09-02T12:40:25.000Z\\\",\\\"remoteMtaIp\\\":\\\"2.2.2.2\\\",\\\"reportingMTA\\\":\\\"dns; b232-10.smtp-out.ap-southeast-2.amazonses.com\\\"},\\\"mail\\\":{\\\"timestamp\\\":\\\"2021-09-02T12:40:23.842Z\\\",\\\"source\\\":\\\"noone@nowhere.com.au\\\",\\\"sourceArn\\\":\\\"arn:aws:ses:ap-southeast-2:000000000000:identity/domainname.com\\\",\\\"sourceIp\\\":\\\"1.1.1.1\\\",\\\"sendingAccountId\\\":\\\"000000000000\\\",\\\"messageId\\\":\\\"0108017ba6864a22-000000\\\",\\\"destination\\\":[\\\"bounce@simulator.amazonses.com\\\"],\\\"headersTruncated\\\":false,\\\"headers\\\":[{\\\"name\\\":\\\"From\\\",\\\"value\\\":\\\"noone@nowhere.com\\\"},{\\\"name\\\":\\\"To\\\",\\\"value\\\":\\\"bounce@simulator.amazonses.com\\\"},{\\\"name\\\":\\\"Subject\\\",\\\"value\\\":\\\"Test\\\"},{\\\"name\\\":\\\"MIME-Version\\\",\\\"value\\\":\\\"1.0\\\"},{\\\"name\\\":\\\"Content-Type\\\",\\\"value\\\":\\\"text/plain; charset=UTF-8\\\"},{\\\"name\\\":\\\"Content-Transfer-Encoding\\\",\\\"value\\\":\\\"7bit\\\"}],\\\"commonHeaders\\\":{\\\"from\\\":[\\\"noone@nowhere.com\\\"],\\\"to\\\":[\\\"bounce@simulator.amazonses.com\\\"],\\\"subject\\\":\\\"Test\\\"}}}\",\n  \"Timestamp\" : \"2021-09-02T12:40:25.260Z\",\n  \"SignatureVersion\" : \"1\",\n  \"Signature\" : \"xxx\",\n  \"SigningCertURL\" : \"https://sns.ap-southeast-2.amazonaws.com/SimpleNotificationService-xxx.pem\",\n  \"UnsubscribeURL\" : \"https://sns.ap-southeast-2.amazonaws.com/?Action=Unsubscribe&SubscriptionArn=arn:aws:sns:ap-southeast-2:000000000000:ses_bounces_topic:xxx\"\n}"
        }
    ]
}

Also this should trigger the lambda execution but doesn't.
manually pushing to the SQS queue does trigger the lambda

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)
Using quarkus handler (can replace with anything equivalent

FUNCTION_NAME=SESBounceHandler
HANDLER=io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler::handleRequest
RUNTIME=java11
ZIP_FILE=fileb://ses-bounce-handler/target/function.zip
IAM_ROLE_NAME=lambda-sqs-trigger
LAMBDA_ROLE_ARN=arn:aws:iam::000000000000:role/${IAM_ROLE_NAME}
SNS_TOPIC_NAME=ses_bounces_topic
SQS_TOPIC_NAME=ses_bounces_queue
SNS_TOPIC_ARN=arn:aws:sns:us-east-1:000000000000:${SNS_TOPIC_NAME}
SQS_QUEUE_URL=http://localhost:4566/000000000000/${SQS_TOPIC_NAME}
SQS_QUEUE_ARN=arn:aws:sqs:us-east-1:000000000000:${SQS_TOPIC_NAME}

# Create role
awslocal iam create-role \
--role-name ${IAM_ROLE_NAME} \
--assume-role-policy-document '{"Version": "2012-10-17", "Statement": [{"Effect": "Allow", "Action": ["lambda:InvokeFunction"]}, {"Effect": "Allow", "Action": ["sqs:SendMessage", "sqs:ReceiveMessage", "sqs:DeleteMessage", "sqs:GetQueueAttributes"]}]}'

# create lambda
awslocal lambda create-function \
--function-name ${FUNCTION_NAME} \
--zip-file ${ZIP_FILE} \
--handler ${HANDLER} \
--runtime ${RUNTIME} \
--role ${LAMBDA_ROLE_ARN} \
--timeout 30 \
--memory-size 256

# create sqs queue
awslocal sqs create-queue --queue-name ${SQS_TOPIC_NAME}

# create sns topic
awslocal sns create-topic --name ${SNS_TOPIC_NAME}

# subscribe sns topic to queue
awslocal sns subscribe --protocol sqs \
--topic-arn ${SNS_TOPIC_ARN} \
--notification-endpoint ${SQS_QUEUE_ARN} 

# set up ses
## create identity
awslocal ses verify-domain-identity --domain domain.com.au
## to send bounces
awslocal ses set-identity-notification-topic --identity domain.com.au --notification-type "Bounce" --sns-topic ${SNS_TOPIC_ARN}

#link lambda to SQS
awslocal lambda create-event-source-mapping \
--event-source-arn ${SQS_QUEUE_ARN} \
--function-name ${FUNCTION_NAME} \
--batch-size 1

## send test bounce email - doesn't trigger lambda
aws --endpoint-url=http://localhost:4566 ses send-email --to bounce@simulator.amazonses.com --subject "Test" --text "Hello World" --from me@domain.com.au

## test send messsage to queue - triggers lambda
awslocal sqs send-message --queue-url ${SQS_QUEUE_URL} --message-body \
'{
"eventType":"Bounce",
"bounce":{
    "bounceType":"Permanent",
    "bounceSubType":"General",
    "bouncedRecipients":[
    {
    "emailAddress":"recipient@example.com",
    "action":"failed",
    "status":"5.1.1",
    "diagnosticCode":"smtp; 550 5.1.1 user unknown"
    }
    ],
    "timestamp":"2017-08-05T00:41:02.669Z",
    "feedbackId":"01000157c44f053b-61b59c11-9236-11e6-8f96-7be8aexample-000000",
    "reportingMTA":"dsn; mta.example.com"
},
"mail":{
"timestamp":"2017-08-05T00:40:02.012Z",
"source":"Sender Name <sender@example.com>",
"sourceArn":"arn:aws:ses:us-east-1:123456789012:identity/sender@example.com",
"sendingAccountId":"123456789012",
"messageId":"EXAMPLE7c191be45-e9aedb9a-02f9-4d12-a87d-dd0099a07f8a-000000",
"destination":[
"recipient@example.com"
],
"headersTruncated":false,
"headers":[
{
"name":"From",
"value":"Sender Name <sender@example.com>"
},
{
"name":"To",
"value":"recipient@example.com"
},
{
"name":"Subject",
"value":"Message sent from Amazon SES"
},
{
"name":"MIME-Version",
"value":"1.0"
},
{
"name":"Content-Type",
"value":"multipart/alternative; boundary=\"----=_Part_7307378_1629847660.1516840721503\""
}
],
"commonHeaders":{
"from":[
"Sender Name <sender@example.com>"
],
"to":[
"recipient@example.com"
],
"messageId":"EXAMPLE7c191be45-e9aedb9a-02f9-4d12-a87d-dd0099a07f8a-000000",
"subject":"Message sent from Amazon SES"
},
"tags":{
"ses:configuration-set":[
"ConfigSet"
],
"ses:source-ip":[
"192.0.2.0"
],
"ses:from-domain":[
"example.com"
],
"ses:caller-identity":[
"ses_user"
]
}
}
}'

### Environment

```markdown
- OS: MacOS
- LocalStack: latest
```

**Comment by dfangl** [comment]
Hi @nparfait !

Please try pulling from latest to see if your issue is already resolved, since I cannot reproduce it on latest.
I used this steps to reproduce your issue:
`localstack start`
```
#!/bin/bash
FUNCTION_NAME=SESBounceHandler
HANDLER=handler.handler
RUNTIME=python3.8
ZIP_FILE=fileb://function.zip
IAM_ROLE_NAME=lambda-sqs-trigger
LAMBDA_ROLE_ARN=arn:aws:iam::000000000000:role/${IAM_ROLE_NAME}
SNS_TOPIC_NAME=ses_bounces_topic
SQS_TOPIC_NAME=ses_bounces_queue
SNS_TOPIC_ARN=arn:aws:sns:us-east-1:000000000000:${SNS_TOPIC_NAME}
SQS_QUEUE_URL=http://localhost:4566/000000000000/${SQS_TOPIC_NAME}
SQS_QUEUE_ARN=arn:aws:sqs:us-east-1:000000000000:${SQS_TOPIC_NAME}


echo "#####################"
echo "Creating resources..."
echo "#####################"
awslocal iam create-role --role-name ${IAM_ROLE_NAME} --assume-role-policy-document '{"Version": "2012-10-17", "Statement": [{"Effect": "Allow", "Action": ["lambda:InvokeFunction"]}, {"Effect": "Allow", "Action": ["sqs:SendMessage", "sqs:ReceiveMessage", "sqs:DeleteMessage", "sqs:GetQueueAttributes"]}]}'

awslocal lambda create-function --function-name ${FUNCTION_NAME} --zip-file ${ZIP_FILE} --handler ${HANDLER} --runtime ${RUNTIME} --role ${LAMBDA_ROLE_ARN} --timeout 30 --memory-size 256

awslocal sqs create-queue --queue-name ${SQS_TOPIC_NAME}

awslocal sns create-topic --name ${SNS_TOPIC_NAME}

awslocal sns subscribe --protocol sqs --topic-arn ${SNS_TOPIC_ARN} --notification-endpoint ${SQS_QUEUE_ARN}

echo "#################"
echo "Setting up SES..."
echo "#################"
awslocal ses verify-domain-identity --domain domain.com.au

awslocal ses set-identity-notification-topic --identity domain.com.au --notification-type "Bounce" --sns-topic ${SNS_TOPIC_ARN}

#link lambda to SQS
awslocal lambda create-event-source-mapping --event-source-arn ${SQS_QUEUE_ARN} --function-name ${FUNCTION_NAME} --batch-size 1

# Reproduction
set -x
trap read debug

aws --endpoint-url=http://localhost:4566 ses send-email --to bounce@simulator.amazonses.com --subject "Test" --text "Hello World" --from me@domain.com.au
```

As for the incorrect format: Both of your examples (as well as the tests I conducted against aws myself) contain this message attribute. Only the message order is not identical.

If you have any more problems with this issue, please do not hesitate to comment or reopen!
