### ISSUE TITLE
bug: 'Invalid kube-config file. No configuration found' during awslocal create cluster

### ISSUE THREAD

**Issue by digantatessell** [localstack/localstack#4547]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have started a minikube cluster and my kubeconfig is present. However when I am trying to create EKS using `awslocal` command, there is an error that kubeconfig not found.

### Expected Behavior

EKS cluster should get created.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

   awslocal eks create-cluster --name cluster1 --role-arn r1 --resources-vpc-config '{}'

### Environment

```markdown
- OS: OSX 11.4
- LocalStack: 0.12.17.5
```

### Anything else?

`localstack_1  | Starting mock SES service on http ports 443/4566 ...
localstack_1  | Starting mock SNS service on http ports 443/4566 ...
localstack_1  | Starting mock SQS service on http ports 443/4566 ...
localstack_1  | Starting mock SSM service on http ports 443/4566 ...
localstack_1  | Starting mock Cloudwatch Events service on http ports 443/4566 ...
localstack_1  | Starting mock StepFunctions service on http ports 443/4566 ...
localstack_1  | Starting mock SWF service on http ports 443/4566 ...
localstack_1  | Starting mock Resource Groups Tagging API service on http ports 443/4566 ...
localstack_1  | Starting mock Resource Groups API service on http ports 443/4566 ...
localstack_1  | Starting mock Support service on http ports 443/4566 ...
localstack_1  | Waiting for all LocalStack services to be ready
localstack_1  | 2021-09-06T16:38:26:INFO:botocore.credentials: Found credentials in environment variables.
localstack_1  | Ready.
localstack_1  | 2021-09-06T16:39:05:ERROR:eks_api: Exception on /clusters [POST]
localstack_1  | Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/localstack_ext/services/eks/eks_api.py", line 62, in load_config
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/kubernetes/config/kube_config.py", line 815, in load_kube_config
localstack_1  |     persist_config=persist_config)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/kubernetes/config/kube_config.py", line 773, in _get_kube_config_loader
localstack_1  |     'Invalid kube-config file. '
localstack_1  | kubernetes.config.config_exception.ConfigException: Invalid kube-config file. No configuration found.
localstack_1  |
localstack_1  | During handling of the above exception, another exception occurred:`

**Comment by drewcorlin1** [comment]
I am also experiencing the same issue. I have started a k8s cluster in docker desktop, and am trying to create the cluster from Terraform. I get the same error: `Exception: Unable to connect to local Kubernetes cluster: Invalid kube-config file. No configuration found.`

**Comment by digantatessell** [comment]
Any update on this issue?

**Comment by whummer** [comment]
Thanks for reporting @digantatessell @drewcorlin1 , and apologies for the long delay on this one. We have recently added a couple of enhancements to the EKS API - it now supports a fully embedded mode inside Docker, which should work out of the box for most environments (i.e., no dependency on existing kube-config file, like in the past). 

Can you please pull the `latest` Docker image, and refer to the updated documentation here: https://docs.localstack.cloud/aws/elastic-kubernetes-service/ Please keep us posted how it goes - happy to provide more guidance in case the problem persists (ideally, please reach out on Slack directly). Thanks for your help!
