### ISSUE TITLE
question: All awslocal "lists" are empty, what am I doing wrong?

### ISSUE THREAD

**Issue by BStenfors9119** [localstack/localstack#4557]
### Is there an existing issue for this?

- [X] I have searched the existing issues and read the documentation

### Question

I am working with the latest version of localstack and awslocal cli.

I am deploying via CDK.  
Localstack boots up fine and the bootstrapping works flawlessly too.

Everything I try to list with awslocal comes up empty.

Items I am trying to list:

```
awslocal cloudformation list-stacks
awslocal apigateway get-rest-apis
```

I am trying to figure out if it is due to the latest version or something with my CDK app.

Thanks,
B

UPDATE:

Realized that I need to set USE_SINGLE_REGION=1 for my DEFAULT_REGION to be applied.

I noticed USE_SINGLE_REGION is deprecated in 0.12.17, how is it suggested to use a default region now because it wasn't working without setting the USE_SINGLE_REGION env var?

Thanks and feel free to close this!

**Comment by mgagliardo** [comment]
Hello @BStenfors9119. Could you please share a bit of your code so as to try reproduce your issue? Can you also paste some DEBUG logs (you can activate these with `DEBUG=1`) to see if there's anything going on the backend? Let me know.


On the region matter, you should be able to use something like this with docker:
```
docker run -ti --rm --name localstack -e DEBUG=1 -e DEFAULT_REGION=us-east-1 -p 4566:4566 localstack/localstack:latest
```

Anyways you can see there's a default region defined here:

localstack/config.py:
```
 61 # default AWS region
 62 if "DEFAULT_REGION" not in os.environ:
 63     os.environ["DEFAULT_REGION"] = os.environ.get("AWS_DEFAULT_REGION") or AWS_REGION_US_EAST_1
 64 DEFAULT_REGION = os.environ["DEFAULT_REGION"]
```

localstack/constants.py:
```
147 # default AWS region us-east-1
148 AWS_REGION_US_EAST_1 = "us-east-1"
```

And even if the USE_SINGLE_REGION is deprecated is still usable (even if not recommended at all).
localstack/config.py:
```
168 # whether to use the legacy single-region mode, defined via DEFAULT_REGION
169 USE_SINGLE_REGION = is_env_true("USE_SINGLE_REGION")
```

**Comment by BStenfors9119** [comment]
> Hello @BStenfors9119. Could you please share a bit of your code so as to try reproduce your issue? Can you also paste some DEBUG logs (you can activate these with `DEBUG=1`) to see if there's anything going on the backend? Let me know.
> 
> On the region matter, you should be able to use something like this with docker:
> 
> ```
> docker run -ti --rm --name localstack -e DEBUG=1 -e DEFAULT_REGION=us-east-1 -p 4566:4566 localstack/localstack:latest
> ```
> 
> Anyways you can see there's a default region defined here:
> 
> localstack/config.py:
> 
> ```
>  61 # default AWS region
>  62 if "DEFAULT_REGION" not in os.environ:
>  63     os.environ["DEFAULT_REGION"] = os.environ.get("AWS_DEFAULT_REGION") or AWS_REGION_US_EAST_1
>  64 DEFAULT_REGION = os.environ["DEFAULT_REGION"]
> ```
> 
> localstack/constants.py:
> 
> ```
> 147 # default AWS region us-east-1
> 148 AWS_REGION_US_EAST_1 = "us-east-1"
> ```
> 
> And even if the USE_SINGLE_REGION is deprecated is still usable (even if not recommended at all).
> localstack/config.py:
> 
> ```
> 168 # whether to use the legacy single-region mode, defined via DEFAULT_REGION
> 169 USE_SINGLE_REGION = is_env_true("USE_SINGLE_REGION")
> ```

First, thanks for the reply!

The region part was the issue.  I didn't realize that multi-regions were "implemented" so when I was executing `awslocal <command>` it wasn't returning anything.  Once I added the region switch "--region" it started returning items.

So that is when I decided to read the latest documentation :D, thus bringing me to the realization I needed to add the USE_SINGLE_REGION=1 in my docker compose file. 

I think going forward I just need to adjust my scripts to add specific region but the USE_SINGLE_REGION flag will work for now.

Does that make sense?

**Comment by mgagliardo** [comment]
That would be correct. `awslocal` probable defaults to region `us-east-1` so if you are creating things on another region you will need to specify that (same on aws cli). Thanks for replying! Closing the issue now.
