### ISSUE TITLE
bug: SQS get-queue-attributes not working after v0.12.17.3

### ISSUE THREAD

**Issue by lukeggchapman** [localstack/localstack#4563]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Calling the following aws cli command returns nothing:

```
aws --endpoint-url=http://localhost:4566 sqs get-queue-attributes --queue-url http://localhost:4566/000000000000/queue-name
```

### Expected Behavior

In v0.12.17 it returns the following:

```
{
    "Attributes": {
        "ApproximateNumberOfMessages": "0",
        "ApproximateNumberOfMessagesDelayed": "0",
        "ApproximateNumberOfMessagesNotVisible": "0",
        "CreatedTimestamp": "1631087752.485528",
        "DelaySeconds": "0",
        "LastModifiedTimestamp": "1631087752.485528",
        "MaximumMessageSize": "262144",
        "MessageRetentionPeriod": "345600",
        "QueueArn": "arn:aws:sqs:ap-southeast-2:000000000000:queue-name",
        "ReceiveMessageWaitTimeSeconds": "0",
        "VisibilityTimeout": "30"
    }
}

```

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker-compose up localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal sqs --region $DEFAULT_REGION create-queue --queue-name queue-name

#### Ran from outside docker environment

aws --endpoint-url=http://localhost:4566 sqs get-queue-attributes --queue-url http://localhost:4566/000000000000/queue-name

### Environment

```markdown
- OS: macOS 10.15.7
- LocalStack: v0.12.17.3, v0.12.17.4, v0.12.17.5
```

### Anything else?

I could only test using the available docker images and it appears somewhere between v0.12.17 and v0.12.17.3

**Comment by mgagliardo** [comment]
Hello @lukeggchapman, I have just tried with localstack `latest` release which is `v.0.12.17.5` and it looks nit to me, can you tell me if I am doing anything different than you? Maybe you can share how are you running localstack and turn on `DEBUG=1` to see what's happening inside the container as I could not reproduce this issue. Thanks!

```
$ aws --endpoint-url=http://localhost:4566 sqs create-queue --queue-name test
{
    "QueueUrl": "http://localhost:4566/000000000000/test"
}

$ aws --endpoint-url=http://localhost:4566 sqs get-queue-attributes --queue-url http://localhost:4566/000000000000/test --attribute-names All
{
    "Attributes": {
        "ApproximateNumberOfMessages": "0",
        "ApproximateNumberOfMessagesDelayed": "0",
        "ApproximateNumberOfMessagesNotVisible": "0",
        "CreatedTimestamp": "1631088754.483822",
        "DelaySeconds": "0",
        "LastModifiedTimestamp": "1631088754.483822",
        "MaximumMessageSize": "262144",
        "MessageRetentionPeriod": "345600",
        "QueueArn": "arn:aws:sqs:us-east-1:000000000000:test",
        "ReceiveMessageWaitTimeSeconds": "0",
        "VisibilityTimeout": "30"
    }
}
```

output from localstack:
```
Ready.
2021-09-08 08:12:29,107:API: 127.0.0.1 - - [08/Sep/2021 08:12:29] "POST / HTTP/1.1" 200 -
2021-09-08T08:12:29:INFO:bootstrap.py: Execution of "start_api_services" took 6181.02ms
2021-09-08 08:12:34,485:API: 127.0.0.1 - - [08/Sep/2021 08:12:34] "POST / HTTP/1.1" 200 -
2021-09-08 08:12:48,156:API: 127.0.0.1 - - [08/Sep/2021 08:12:48] "POST / HTTP/1.1" 200 -
```

**Comment by lukeggchapman** [comment]
Hi @mgagliardo, thanks for getting back to me so quickly.
I've compared the behaviour with AWS and Localstack is working correctly.

From the AWS docs:
>  The AttributeName.N parameter is optional, but if you don't specify values for this parameter, the request returns empty results.

I had a test that was not passing the ` --attribute-names All`, and the behaviour of Localstack changed to align with AWS between v0.12.17 and v0.12.17.3
