### ISSUE TITLE
feature request: AWS::DynamoDB::GlobalTable Cloudformation Support

### ISSUE THREAD

**Issue by bbuckland** [localstack/localstack#4565]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

AWS now supports the AWS::DynamoDB::GlobalTable resource in Cloudformation; however, when trying to create it in Localstack, one would get the following warning message

> WARNING:moto: No Moto CloudFormation support for AWS::DynamoDB::GlobalTable

Ideally, a user could create Global dynamo tables, so that they don't have to alter their Cloudformation scripts for local development, or maintain separate scripts for local vs cloud.

**Comment by bbuckland** [comment]
@dominikschubert anything that I can do to drive this forward? I'd be happy to contribute this feature to the project. Thank you!

**Comment by dominikschubert** [comment]
> @dominikschubert anything that I can do to drive this forward? I'd be happy to contribute this feature to the project. Thank you!

@bbuckland Sure, if you want to implement this, please let me know so we an avoid working on it in parallel :wink:. Contributions are always welcome. I'd expect the feature to be fairly straight forward to implement. The process would consist of these two parts:

- [ ] Add the `AWS::DynamoDB::GlobalTable` resource to https://github.com/localstack/localstack/blob/master/localstack/services/cloudformation/models/dynamodb.py
- [ ] Create a new test file named `test_cloudformation_dynamodb.py` in  `tests/integration/cloudformation` and include at least one test that verifies a stack with a ` AWS::DynamoDB::GlobalTable` resource is created successfully.

**Comment by HarshCasper** [comment]
This feature is now available in our `localstack/localstack:latest` image. Please pull the Docker image to get started!
