### ISSUE TITLE
Cloud Pods Push Errors - _pods s3 bucket missing?

### ISSUE THREAD

**Issue by m-chandler** [localstack/localstack#4566]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm trying to get a reasonably sized deployment to localstack. It seems that when a CloudFormation deployment fails, it's best to just start with a fresh container and try again, and remnants of the old deploy seem to hang around. It is incredibly time consuming to have to stop the docker container, destroy it, restart it, and deploy N number of stacks just to get back to the same point to test one minor adjustment to a template.

Cloud Pods might solve this for me, as I could take a snapshot just before trying the latest step, and then quickly roll back?

In my attempts to use Cloud Pods I've either encountered a bug, or I do not understand the documentation. I may not even have my docker-compose file right, it could easily be my fault, but I've tried my best with the available documentation.

I made a pod called "testing" in the LocalStack Cloud UI:

![image](https://user-images.githubusercontent.com/2039337/132606019-b413bb1f-eb5b-4708-b423-682b54594f47.png)

When trying to use `localstack pod push testing` I receive the following error:

```
Exception: Unable to get local pod state via management API http://localhost:4566/_pods/state (code 404): b'<?xml version="1.0" encoding="UTF-8"?>\n<Error>\n    <Code>NoSuchBucket</Code>\n    <Message>The specified bucket does not exist</Message>\n    <BucketName>_pods</BucketName>\n    <RequestID>7a62c49f-347e-4fc4-9331-6e8eEXAMPLE</RequestID>\n</Error>
```

I wondered if perhaps the empty pod needs to be pulled first. I don't think this is correct, but I tried anyway. When I run `localstack pod pull testing` I receive the following error:

```
C:\...>python C:\Users\<user>\AppData\Local\Programs\Python\Python39\Scripts\\localstack pod pull testing
Pulling state of cloud pod "testing" from local folder: more-testing
Traceback (most recent call last):
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python39\Scripts\localstack", line 23, in <module>
    main()
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python39\Scripts\localstack", line 19, in main
    main.main()
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python39\lib\site-packages\localstack\cli\main.py", line 6, in main
    cli()
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python39\lib\site-packages\localstack\cli\plugin.py", line 30, in __call__
    self.group(*args, **kwargs)
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python39\lib\site-packages\localstack_ext\cli\localstack.py", line 105, in cmd_pod_pull
    pods_client.pull_state(name,ThgSM)
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python39\lib\site-packages\localstack_ext\bootstrap\pods_client.py", line 319, in pull_state
    backend.pull()
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python39\lib\site-packages\localstack_ext\bootstrap\pods_client.py", line 132, in pull
    self.deploy_pod_into_instance(local_folder)
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python39\lib\site-packages\localstack_ext\bootstrap\pods_client.py", line 82, in deploy_pod_into_instance
    cp_r(src_folder,tgt_folder,rm_dest_on_conflict=fXxzA)
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python39\lib\site-packages\localstack\utils\common.py", line 902, in cp_r
    return shutil.copytree(src, dst, **kwargs)
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 552, in copytree
    with os.scandir(src) as itr:
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'more-testing\\api_states'
```

### Expected Behavior

For Cloud Pods to work as per documentation

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

docker-compose.yml 

```
version: '2.1'

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=serverless,sns,sqs,kms,route53,acm
      - DATA_DIR=/tmp/localstack/data
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
      - LOCALSTACK_API_KEY=...
      - DEBUG=true
      - KMS_PROVIDER=local-kms
    volumes:
      - "/c/temp/localstack:/tmp/localstack"
    network_mode: bridge
  dynamodb-admin:
    depends_on:
      - localstack
    image: aaronshaf/dynamodb-admin
    ports:
      - 8001:8001
    environment:
      - DYNAMO_ENDPOINT=http://localstack:4566
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
    links:
      - localstack
    network_mode: bridge
```

Local DATA_DIR directory seems to work (as CloudPods doco requires):
![image](https://user-images.githubusercontent.com/2039337/132606448-2c3fdc1d-8c3a-4663-af75-b6e4d9bc426c.png)

1. `docker-compose up`
2. wait until running
3. from a new cmd prompt, set DATA_DIR to C:/temp/localstack (not sure if this is required, might just be required for the docker container?)
4. from same cmd prompt: set LOCALSTACK_API_KEY
5. from same cmd prompt: `localstack login` - enter creds.
6. from same cmd prompt: `localstack pod push testing`
7. observe error re: s3 bucket not existing

### Environment

```markdown
- OS: Windows
- LocalStack: latest sha256:0d1fa3b037d075011b27771479e96e74f5765389affe0d93c6ab14fe848b4503

Pip packages.
localstack               0.12.17.5
localstack-client        1.24
localstack-ext           0.12.16.14
```

**Comment by whummer** [comment]
Thanks for reporting @m-chandler . It looks like you may be using an older version of the image. Can you please share the version info that gets printed in the startup logs, e.g.:
```
LocalStack version: 0.12.17.5
LocalStack Docker container id: 60594aa17b01
LocalStack build date: 2021-09-08
LocalStack build git hash: 5ab42534
```

Doing a `docker pull localstack/localstack` and restarting the compose-stack might help - can we please give that a try? Thanks!

**Comment by m-chandler** [comment]
Hi @whummer thanks for looking so promptly.

Still no success, it's almost as though the pods feature is disabled in my container, is it behind a flag of some sort?

Have run `docker pull localstack/localstack`.

Output is as follows during the startup:

```
LocalStack version: 0.12.17.5
LocalStack Docker container id: 08035694864e
LocalStack build date: 2021-09-09
LocalStack build git hash: b769810a
```

I tidied up my docker-compose.yml file as well (shouldn't be any differences, but maybe worth mentioning).

docker-compose.yml:
```
version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    network_mode: bridge
    ports:
      - "127.0.0.1:53:53"
      - "127.0.0.1:53:53/udp"
      - "127.0.0.1:443:443"
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4571:4571"
    environment:
      - SERVICES=${SERVICES- }
      - DEBUG=true
      - DATA_DIR=/tmp/localstack-data
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - LOCALSTACK_API_KEY=<masked>
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/c/tmp/localstack-data:/tmp/localstack-data"
```

Steps I'm following:
1. Delete any data within /c/tmp/localstack-data (don't want existing state to conflict).
2. Delete existing & start up new container... logs look fine.
3. Create a resource `awslocal s3api create-bucket --bucket kfc-bucket`
4. Confirm: Logs look good: `"PUT /kfc-bucket HTTP/1.1" 200 -`
5. Localstack login, looks good: `successfully logged in`
6. Attempt to push pod: `localstack pod push testing` (`testing` is the name of the pod, as shown in initial ticket).
7. Docker logs show 404, as does the `pod push` response (full example in initial ticket): `"GET /_pods/state HTTP/1.1" 404 -`

**Comment by m-chandler** [comment]
Was using the wrong API key, sorry for wasting your time.
