### ISSUE TITLE
question: How do I test CDK AMI Lookup

### ISSUE THREAD

**Issue by kornicameister** [localstack/localstack#4570]
### Is there an existing issue for this?

- [X] I have searched the existing issues and read the documentation

### Question

I am trying to setup a test case against my stack deployed with CDK. In that stack I have a piece of code that fetches AMZ Linux 2 AMI for given region. For obvious reasons deploying the stack fails. Wonder if any faced that issue?

**Comment by mgagliardo** [comment]
Hello @kornicameister, wonder if [the answer from this thread](https://github.com/localstack/localstack/issues/3714#issuecomment-798811876) would help you out with this. It looks like the same issue to me.

**Comment by kornicameister** [comment]
Well, I didn't stumble onto that one :/
But information in it allowed to change my code so that I inject base image name over `-c` and that worked correctly. I have another issue but that one is not related to base AMI.

**Comment by mgagliardo** [comment]
Great to know! Cheers @kornicameister
