### ISSUE TITLE
bug: PRO looping at start-up with SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by yoshiroyo** [localstack/localstack#4571]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When starting up localstack with a LOCALSTACK_API_KEY it fails with either docker-compose up or localstack start.  
It goes into a loop where it repeats this same failure over and over again:

localstack_main | Starting mock ACM service on http port 4566 ...
localstack_main | 2021-09-09T17:16:41:INFO:localstack_ext.bootstrap.install: Unable to download local test SSL certificate from https://cdn.jsdelivr.net/gh/localstack/localstack-artifacts@master/local-certs/server.key to /tmp/localstack/server.test.pem: MyHTTPSConnectionPool(host='cdn.jsdelivr.net', port=443): Max retries exceeded with url: /gh/localstack/localstack-artifacts@master/local-certs/server.key (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)'))) Traceback (most recent call last):
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 706, in urlopen
...

I am behind a corporate proxy (CISCO) and have attempted to add the CACerts with no luck.  Localstack does start successfully without the [PRO] LOCALSTACK_API_KEY. I am far from a network or docker expert but have attempted to follow several possible workarounds suggested in other issues and on stackoverflow.

### Expected Behavior

LocalStack PRO should be able to start and run when the same system/environment/configuration is able to start and run Community Edition.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

have tried starting it both with docker-compose and with localstack start.  Both end up looping in the sameway

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

localstack start

docker-compose up

docker-compose.yml:
version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    network_mode: bridge
    ports:
      - "53:53"
      - "53:53/udp"
      - "443:443"
      - "4566:4566"
      - "4571:4571"
      - "8082:8082"
    environment:
      - SERVICES=${SERVICES- }
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
      - PORT_WEB_UI=8082
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

### Environment

```markdown
- OS: Windows 10
- LocalStack: LocalStack CLI 0.12.17.5 LocalStack version: 0.12.17.5
```

**Comment by whummer** [comment]
Thanks for reporting @yoshiroyo . We have now pushed a small enhancement which should get this issue resolved (we are now using a fallback download location from `api.localstack.cloud`, in case Github is blocked by your corporate firewall). 

Can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists. Thanks for your help!
