### ISSUE TITLE
bug: Batch DescribeJobDefinitions throws an error when requesting all job definitions

### ISSUE THREAD

**Issue by jim-sheldon** [localstack/localstack#4577]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When calling boto3 `[Batch.client.describe_job_definitions()](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/batch.html#Batch.Client.describe_job_definitions)` an error occurs when requesting all job definitions. 

```
    response = self.batch_client.describe_job_definitions()
  File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 676, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (500) when calling the DescribeJobDefinitions operation (reached max retries: 4):
```

However, when calling `describe_job_definitions()` with the `jobDefinitionName` argument set, I get a response back with the expected payload.

I pointed `Batch.Client` at AWS, running `describe_job_definitions()` without the `jobDefinitionName` argument set, and it responded with the expected payload and no `ClientError`, so I do not suspect the bug lies in boto3.

### Expected Behavior

`describe_job_definitions()` should not throw a `ClientError` and should return the payload indicated in the API docs.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

```
    docker-compose -f docker-compose.yml up --build
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```
batch_client = boto3.client("batch", endpoint_url="http://localstack:4566")
batch_client.describe_job_definitions()
```

### Environment

```markdown
- OS: Mac OS 10.15
- LocalStack: latest
```

**Comment by dfangl** [comment]
Hi @jim-sheldon  !
This issue should be resolved now, and the fix will be included in the next release. Thank you for reporting this issue!

**Comment by jim-sheldon** [comment]
Hi @dfangl, thank you for helping fix this issue; I now see the method working as expected!
