### ISSUE TITLE
feature: add except when lambda function exceed size

### ISSUE THREAD

**Issue by ltarquinio** [localstack/localstack#4596]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Hi,
I've developed an new lambda function at localstack, but when i went to deploy at AWS, it exceed the limit size of 256mb.

### 🧑‍💻 Implementation

When run lambda in localstack, it should except about the size.

**Comment by whummer** [comment]
Thanks for reporting @ltarquinio . Can you please share some details (code snippets) about how you're creating your Lambda function - are you uploading a large zip file in the `CreateFunction` API call directly, or are you putting your zip file to S3 first, and then reference the S3 bucket/object in the `CreateFunction` call? Thanks!
