### ISSUE TITLE
question: Workaround to skip loading ES plugins

### ISSUE THREAD

**Issue by iamthen0ise** [localstack/localstack#4599]
### Is there an existing issue for this?

- [X] I have searched the existing issues and read the documentation

### Question

Hi!

I love Localstack, and just one thing bothering me every time.
Is there any workaround to skip loading ElasticSearch plugins on first start? I try to minimize the time of ES start, and ES plugins are not vital for me.

Thank you!

**Comment by mgagliardo** [comment]
Hello @iamthen0ise, you can definitely minimize the start time of ES by running your own node along with localstack, [there's a guide here](https://github.com/localstack/localstack/blob/master/doc/external_services_integration/elasticsearch/HOWTO.md) on how to achieve that, it is fairly simple and definitely reduces loading time. 

Let me know if this works for you. Cheers!

**Comment by iamthen0ise** [comment]
@mgagliardo Thank you, and this particular solution is really great!

I'm still dependant on other LS services, so just curious if any customization for ES available inside LS.

With solution above I have to wait for plugins too.

I'll take standalone ES 7.11 image and run it aside with stack. 

So, feel free to close ticket if Localstack has no such settings that rule plugins lifecycle.

Thank you!

**Comment by mgagliardo** [comment]
I'll close the ticket but definitely gonna take a look at the possibility to improve ES times passing a list of plugins. Thanks for your comments!
