### ISSUE TITLE
How to publish to my localstack using AWS SNS SDK 

### ISSUE THREAD

**Issue by pratikshelar87** [localstack/localstack#460]
I am able to start localstack locally and perform the SNS SQS operations but I want my JAVA application to be able to the same using the AWS SDK client.

But I observe that the SDK client still posts request to AMAZON PROD region instead of localhost where the localstack is running.

How can I configure my application to be able to push to local stack instead of amazon

**Comment by whummer** [comment]
Hi @pratikshelar87 , the AWS Java SDK provides a configuration option to specify the *endpoint URL* the application should connect to. Please refer to our Java tests here:
https://github.com/localstack/localstack/blob/master/localstack/ext/java/src/main/java/cloud/localstack/TestUtils.java#L40-L44

```
	public static AmazonSQS getClientSQS() {
		return AmazonSQSClientBuilder.standard().
				withEndpointConfiguration(getEndpointConfigurationSQS()).
				withCredentials(getCredentialsProvider()).build();
	}
```

**Comment by pratikshelar87** [comment]
Thanks @whummer ,

Turns out the aws sdk version we were using was pretty old. :-(
I updated it and I can now see the above config.

**Comment by pratikshelar87** [comment]
Thanks @whummer 

Tuyrns out the version of sdk we were using was pretty old. Updated that and now I can see the endpoint config.
