### ISSUE TITLE
bug: Cannot use Lamnbda Layers: 404

### ISSUE THREAD

**Issue by hazam** [localstack/localstack#4608]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Trying to create some Lambda Layer in the PRO version, but got 404

```
│ Error: error reading Lambda Layer version (arn:aws:lambda:us-east-1:000000000000:layer:metacicd-automation-dev-cerberus:4): : 
│ 	status code: 404, request id: 
│ 
│   with module.lambda_layer_cerberus.aws_lambda_layer_version.this[0],
│   on .terraform/modules/lambda_layer_cerberus/main.tf line 93, in resource "aws_lambda_layer_version" "this":
│   93: resource "aws_lambda_layer_version" "this" {
```

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker-compose up 

Can read in logs 

2021-09-16T14:47:32:INFO:localstack_ext.bootstrap.licensing: Successfully activated API key

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    terraform code

### Environment

```markdown
- OS: ubuntu 20.04
- LocalStack: latest
```

**Comment by whummer** [comment]
Hi @hazam , thanks for reporting. Can you please share the version/age of the Docker image you're using - does the problem persist after pulling the `latest` Docker image? Also, would be great if you could share the relevant snippets of your terraform script here, so we can replicate the use case end-to-end. Thanks for your help!

**Comment by hazam** [comment]
Hi, yes it persists after pulling fresh image. TF snippet
```
module "lambda_layer_jenkins" {
  source  = "terraform-aws-modules/lambda/aws"
  version = "1.48.0"


  create_layer           = true
  create_package         = false
  local_existing_package = "lambdaLayer/python-jenkins/python-jenkins.zip"
  layer_name             = "metacicd-automation-python-jenkins"
  description            = "Layer for jenkins"
  compatible_runtimes    = ["python3.7"]
}
```

**Comment by dfangl** [comment]
Issue should be fixed with the next release.
