### ISSUE TITLE
bug: Unable to find forwarding rule for host - DynamoDB

### ISSUE THREAD

**Issue by jaredpetersen** [localstack/localstack#4609]
### Is there an existing issue for this?

- [X] I have searched the existing issues

Symptoms are the exact same as https://github.com/localstack/localstack/issues/4004 but this is DynamoDB and a different workaround worked here.

### Current Behavior

When using the v2 Java SDK with the anonymous credentials provider to insert items into LocalStack DynamoDB, LocalStack returns a 404 status code with a response body of `{ "status": "running" }`. LocalStack also logs:

```
2021-09-16T21:23:46:INFO:localstack.services.edge: Unable to find forwarding rule for host "dev-localstack:4566", path "POST /", target header "DynamoDB_20120810.PutItem", auth header "", data "b'{"TableName":"loyalty-order-process-dev","Item":{"last_updated":{"S":"2021-09-16T21:23:46.052302Z"..."
```

The item is never inserted and the Java v2 SDK throws an exception.

The AWS cli works totally fine, however.

### Expected Behavior

Item is put into DynamoDB

### How are you starting LocalStack?

Custom (please describe below)

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

We have a Kubernetes setup that we run Localstack in. However, Localstack is bone stock without any configuration overrides.

We're pinned to version 0.12.16 though.

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

For the AWS v2 Java SDK (with Spring) we are using the following DynamoDB configuration:
```java
@Profile("dev")
@Bean(name = "dynamoDbClient")
DynamoDbClient dynamoDbClientDev() {
    return DynamoDbClient.builder()
        .endpointOverride(URI.create("http://dev-localstack:4566"))
        .credentialsProvider(AnonymousCredentialsProvider.create())
        .region(Region.of(region))
        .build();
}
```

This is not successful.

We are able to put items into DynamoDB via the AWS CLI though:
```sh
aws dynamodb --endpoint-url http://dev-localstack:4566 put-item \
    --table-name loyalty-order-process-dev \
    --item '{ "user_id": {  "S": "2154078486" }, "request_id": {  "S": "36ab1d2d-e7d0-498e-bc20-033351b89ec8" }, "last_updated": {  "S": "2021-09-16T10:31:33.517075Z" }, "version": {  "N": "2" }, "process_state": {  "S": "ORDER_CREATED" }, "sku": {  "S": "BNSCSH-5" }}'
```

However, if we update the DynamoDB client to use dummy credentials, everything works:
```java
@Profile("dev")
@Bean(name = "dynamoDbClient")
DynamoDbClient dynamoDbClientDev() {
    return DynamoDbClient.builder()
        .endpointOverride(URI.create("http://dev-localstack:4566"))
        .credentialsProvider(StaticCredentialsProvider.create(AwsBasicCredentials.create("FAKE", "FAKE")))
        .region(Region.of(region))
        .build();
}
```

So something about the Anonymous credentials provider does not jive well with Localstack.

### Environment

```markdown
- OS: MacOS 11.5 for the Java Code, LocalStack is running on who knows what in Kubernetes
- LocalStack: 0.12.16
```

### Anything else?

I ran a proxy tool while making these requests and here's the request that the v2 Java SDK sent:

```sh
curl \
    -H 'Host: dev-localstack:4566' \
    -H 'amz-sdk-invocation-id: 7913bd2f-e6cd-8b86-7410-70f7d4233b8d' \
    -H 'amz-sdk-request: attempt=1; max=8' \
    -H 'Content-Type: application/x-amz-json-1.0' -H 'User-Agent: aws-sdk-java/2.15.42 Mac_OS_X/10.16 OpenJDK_64-Bit_Server_VM/11.0.5+10-LTS Java/11.0.5 kotlin/1.3.72-release-468 (1.3.72) vendor/Amazon.com_Inc. io/sync http/Apache' \
    -H 'X-Amz-Target: DynamoDB_20120810.PutItem' \
    --data-binary '{"TableName":"loyalty-order-process-dev","Item":{"last_updated":{"S":"2021-09-16T13:51:42.115611-07:00"},"user_id":{"S":"6"},"expiration_timestamp":{"N":"1633035102"},"process_state":{"S":"STARTED"},"sku":{"S":"ROOMBA"},"request_id":{"S":"c62127f6-1736-11ec-9621-0242ac130002"},"version":{"N":"0"}},"ConditionExpression":"attribute_not_exists(user_id)"}' \
    'http://dev-localstack:4566/'
```

Response (status code 404):
```
{"status": "running"}
```

The AWS CLI makes a different request (redacted, since it's passing credentials apparently, and with a different payload because of the request I made ):
```sh
curl \
  -H 'Host: dev-localstack:4566' \
  -H 'X-Amz-Target: DynamoDB_20120810.PutItem' \
  -H 'Content-Type: application/x-amz-json-1.0' \
  -H 'User-Agent: aws-cli/2.0.7 Python/3.7.4 Darwin/20.6.0 botocore/2.0.0dev11' \
  -H 'X-Amz-Date: 20210916T205209Z' \
  -H 'X-Amz-Security-Token: REDACTED'
  -H 'Authorization: AWS4-HMAC-SHA256 Credential=REDACTED/20210916/us-east-1/dynamodb/aws4_request, SignedHeaders=content-type;host;x-amz-date;x-amz-security-token;x-amz-target, Signature=REDACTED' \
  --data-binary '{"TableName": "loyalty-order-process-dev", "Item": {"user_id": {"S": "2154078486"}, "request_id": {"S": "36ab1d2d-e7d0-498e-bc20-033351b89ec8"}, "last_updated": {"S": "2021-09-16T10:31:33.517075Z"}, "version": {"N": "2"}, "process_state": {"S": "ORDER_CREATED"}, "expiration_timestamp": {"N": "1631873763"}, "sku": {"S": "BNSCSH-5"}}}' \
  'http://dev-localstack:4566/'
```

Response (status code 200):
```
{"ConsumedCapacity":{"TableName":"loyalty-order-process-dev","CapacityUnits":1.0}}
```

This was fixed once we switched to the other credentials providers. So I think something is wrong there.

**Comment by workfreda** [comment]
I experience the exact same thing with golang AWS SDK v2. Same setup with credentials as jared.

**Comment by whummer** [comment]
Thanks for reporting @jaredpetersen @workfreda , and apologies for the delay. This should be fixed in the meantime - can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists. Thanks for your help!

**Comment by workfreda** [comment]
I can confirm it works with my setup. However, I'll let @jaredpetersen have the last word as he created the issue. Thanks for the help!

**Comment by jaredpetersen** [comment]
I'm not able to confirm that the latest branch fixes our issue since we're pretty set on version pinning in my organization where this problem occurred. But good to know that this was (apparently) fixed.

Any ideas on when the current `latest` image will get a version tag?

Thanks for the previous prompt response 😄
