### ISSUE TITLE
bug: not possible to use CloudWatch as EventBridge target

### ISSUE THREAD

**Issue by Sotam** [localstack/localstack#4611]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When trying to use CloudWatch as a target for an EventBridge eventbus I receive a warning `WARNING:localstack.utils.aws.aws_stack: Unsupported Events rule target ARN: "arn:aws:logs:us-east-1:000000000000:log-group:/aws/events/log-imports"` and nothing happens.

### Expected Behavior

I expected to be able to use CloudWatch loggroup as an EventBrigde eventbus target, like I can using AWS.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    `docker-compose.yaml`

#### Additional files
JSON file needed for the `put-events` call

```
[
  {
    "Source": "com.mycompany.myapp",
    "Detail": "{ \"key1\": \"value1\", \"key2\": \"value2\" }",
    "Resources": [
      "resource1",
      "resource2"
    ],
    "DetailType": "myDetailType",
    "EventBusName": "messages-eb"
  }
]
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal logs create-log-group --log-group-name /aws/events/log-imports
    awslocal events create-event-bus --name messages-eb
    awslocal events put-rule --name forward-message --event-bus-name messages-eb --event-pattern "{""account"": [""000000000000""]}"
    awslocal events put-targets --rule forward-message --event-bus-name messages-eb --targets "Id"="1","Arn"="arn:aws:logs:us-east-1:000000000000:log-group:/aws/events/log-imports"

    awslocal events put-events --entries file://events.json
    

### Environment

```markdown
- OS: Windows 10
- LocalStack: 0.12.17
- Docker Desktop (with WSL2)
```

**Comment by mgagliardo** [comment]
Hello @Sotam, thanks for reporting this. 
Besides the application does not accept using CloudWatch as EventBridge target, do you know what would be the actual usage for this? I have replicated this on an AWS test account and when I run `put-events` on cloudwatch I don't see any logs whatsoever. If you could explain me this so I can replicate the behaviour. Thanks!!

**Comment by Sotam** [comment]
Hi @mgagliardo, thanks for your response. Currently we use CloudWatch target for logging purposes. 

So we have an application that sends publishes/puts messages to an event bus and the event bus has two rules:
- one uses CloudWatch as a target
- one for forwading messages to another EventBridge event bus is in a different account (or region)

By having the CloudWatch as a target we can make sure our application is working as intented, in case there might be some misconfiguration at the other AWS account that's connected using target type `Event bus in a different account or Region`.

Here are some command outputs:
```
aws events list-targets-by-rule --rule forward-to-sbp --event-bus-name messages-eb
{
    "Targets": [
        {
            "Id": "...GUID...",
            "Arn": "arn:aws:logs:eu-west-1:..:log-group:/aws/events/log-imports"
        },
        {
            "Id": "...GUID...",
            "Arn": "arn:aws:events:eu-west-1:...:event-bus/...redacted...",
            "RoleArn": "arn:aws:iam::...:role/ecsEventsRole"
        }
    ]
}
```

```
aws logs describe-log-groups
{
    "logGroups": [
        {
            "logGroupName": "/aws/events/log-imports",
            "creationTime": ...,
            "retentionInDays": 30,
            "metricFilterCount": 0,
            "arn": "arn:aws:logs:eu-west-1:...:log-group:/aws/events/log-imports:*",
            "storedBytes": 1825487
        }
    ]
}
```

```
aws events put-events --entries file://events.json
{
    "FailedEntryCount": 0,
    "Entries": [
        {
            "EventId": "...GUID..."
        }
    ]
}
```

After the put-events call I can view the data in CloudWatch. I hope this helps understanding our case. Please, let me know if you have any questions left :-)
