### ISSUE TITLE
bug: Amazon.SQS.AmazonSQSException: MD5 hash mismatch for message id

### ISSUE THREAD

**Issue by nibro7778** [localstack/localstack#4621]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We have dotnet core application and when we trying to consume the message from SQS using MassTransit it's throwing this error. When I revert the localstack version to 0.11.2 it's working fine.  

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

```
services:
  
  localstack:
    image: localstack/localstack:latest
    environment:
      - SERVICES=sqs,sns,s3,cognito
      - USE_SINGLE_REGION=1
      - DEFAULT_REGION=ap-southeast-2
      - HOSTNAME_EXTERNAL=localhost
      - DEBUG=1
      - LOCALSTACK_API_KEY=XXXXXX
    ports:
      - "4566:4566"
    healthcheck:
      test:
        - CMD
        - bash
        - -c
        - awslocal sqs list-queues
          && awslocal sns list-topics
          && awslocal sns list-subscriptions
          && awslocal s3 ls
      interval: 5s
      timeout: 10s
      start_period: 10s
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

Trying to consume the message from dotnet core consumer app  which uses Masstransit for consuming the message

### Environment

```markdown
- LocalStack: latest
```

**Comment by michaelmccord** [comment]
I have also run into this exact issue
