### ISSUE TITLE
bug: PySpark Job error occurred (500) when calling the RunJobFlow operation

### ISSUE THREAD

**Issue by MBeguinG1** [localstack/localstack#4622]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When doing the [EMR Getting Started tutorial](https://docs.aws.amazon.com/emr/latest/ManagementGuide/emr-gs.html) with Localstack, the Pyspark job fails with the following error `An error occurred (500) when calling the RunJobFlow operation`

### Expected Behavior

The PySpark job should succeed and the output should be available in an S3 bucket

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

  docker compose up

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)
Files available [here](https://docs.aws.amazon.com/emr/latest/ManagementGuide/emr-gs.html#emr-getting-started-manage)

    awslocal s3 mb s3://emr-data
    awslocal s3 cp health_violations.py s3://emr-data
    awslocal s3 cp food_establishment_data.csv s3://emr-data

    awslocal emr create-cluster \
        --release-label emr-5.9.0 --applications Name=Spark --ec2-attributes KeyName=myKey \
        --instance-groups InstanceGroupType=MASTER,InstanceCount=1,InstanceType=m4.large InstanceGroupType=CORE,InstanceCount=2,InstanceType=m4.large \
        --steps Type=Spark,Name="SparkApp",ActionOnFailure=TERMINATE,Args=[s3://emr-data/health_violations.py,--data_source,s3://emr-data/food_establishment_data.csv,--output_uri,s3://emr-data/MyOutputFolder]

### Environment

```markdown
- OS: Windows 10 Pro with Docker Desktop version 4.0.1
- LocalStack: 0.12.17
```

### Anything else?

Logs of the localstack docker container: [log.txt](https://github.com/localstack/localstack/files/7201789/log.txt)

**Comment by whummer** [comment]
Thanks for reporting @MBeguinG1 , and apologies for the delay. Can you please share the full logs of your LocalStack container (with `DEBUG=1` enabled in the container environment). We'll be happy to look into it - also, happy to discuss in more detail in our Slack channel (please let us know if you haven't received an invite link)... Thanks for your help!

**Comment by whummer** [comment]
Hi @MBeguinG1 , quick update. In the meantime we have pushed a number of enhancements for the EMR API, especially around PySpark jobs, S3 integration, etc - can you please pull the `latest` Docker image and give it another try? 

Please let us know if the problem persists - happy to look into it in more detail if you could share your PySpark script and the LocalStack logs. Thanks!
