### ISSUE TITLE
bug: S3 operations allow versionID in unversioned buckets

### ISSUE THREAD

**Issue by FloatingGhost** [localstack/localstack#4624]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

HeadObject returns 404 when specifying a version ID in an unversioned bucket

### Expected Behavior

It should return 400 - 

```bash
aws s3api head-object --bucket my-unversioned-bucket --key what --version-id nope

An error occurred (400) when calling the HeadObject operation: Bad Request
```

### How are you starting LocalStack?

With a `docker run` command

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

`docker run --rm -d -p 4566:4566 -e 'DEFAULT_REGION=eu-west-1' -e 'SERVICES=s3' --name localstack localstack/localstack:0.12.17.5`

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```bash
awslocal s3api create-bucket --bucket noversion
awslocal s3api head-object --bucket noversion --version-id what --key test 
```

Returns `An error occurred (404) when calling the HeadObject operation: Not Found`

### Environment

```markdown
- OS: Arch
- LocalStack: 0.12.17.5
```

**Comment by Gabriel-scodiero** [comment]
@claim

**Comment by pinzon** [comment]
Hi @FloatingGhost thank you for reporting this issue. I just submited PR with the fix.

I just want to clarify that even with the fix merged and applied, you will still see and incorrect status code in this situation, probably the code `403`.

For some reason Aws CLI after receiving and error code from this function it will try several times (as expected) and then it will try again ignoring the endpoint parameter and using the real AWS endpoint. 

I'll close this issue once the PR is merged.
