### ISSUE TITLE
S3NotificationConfiguration to lambda, lambdaEvent.Records[0].s3.object.key is URL encoded.

### ISSUE THREAD

**Issue by vangorra** [localstack/localstack#465]
I've setup a bucket with a notification configuration pointing to a lambda function. I'm uploading a file with a key that looks something like this "files/2017-11-15 14:22:21_file.csv".

When the resulting lambda is called, the key comes in as partially URL encoded. "files/2017-11-15 14%3A22%3A21_file.csv".

The way AWS actually operates is the proper url decoded key is passed to the lambda function.

**Comment by GeoffreyBooth** [comment]
How are you getting this notification to work? I’m getting an exception: #462

**Comment by vangorra** [comment]
My mistake. Localstack is sending the correct data.
S3 in production AWS does send a url encoded string as the key. You must url decode it.
