### ISSUE TITLE
question: Is there a way to make an API call to AWS that by-passed the LocalStack proxy?

### ISSUE THREAD

**Issue by 1Mill** [localstack/localstack#4660]
### Is there an existing issue for this?

- [X] I have searched the existing issues and read the documentation

### Question

I am trying to permit `kms` requests to AWS while keeping `ecr` and `lambda` calls proxied to LocalStack. I see the documentation for [DNS_LOCAL_NAME_PATTERNS](https://localstack.cloud/docs/getting-started/configuration/#dns_local_name_patterns) which seems to permit this use case but perhaps I am not understanding the regex patterns I should be using. 

Any help would be appreciated.

### Anything else?

Attached below is an example of the output I am seeing when trying to make the `kms.us-east-1.amazonaws.com` API request using `@aws-sdk/client-kms@^3.33.0` under the hood in my Node lambda. 

![image](https://user-images.githubusercontent.com/17913154/135203310-e1184d98-fa19-4ade-b70c-761aab87fd90.png)

**Comment by whummer** [comment]
Hi @1Mill , thanks for reporting. We have just pushed a few minor enhancement - can you please pull the `latest` Docker image and give it another try?

Can you please try enabling the following environment configurations in your LocalStack Pro instance:
```
TRANSPARENT_LOCAL_ENDPOINTS=0 
DNS_LOCAL_NAME_PATTERNS='.*(ecr|lambda).*.amazonaws.com'
```

Then, when testing with a simple Lambda that attempts to connect to ECR, Lambda, and KMS:
```
cat <<EOT > /tmp/test_lambda.py
import boto3
def handler(*args, **kwargs):
  print(boto3.client("ecr").describe_repositories())
  print(boto3.client("lambda").list_functions())
  print(boto3.client("kms").list_keys())
EOT
(cd /tmp; zip testlambda.zip test_lambda.py)
awslocal lambda create-function --function-name f1 --runtime python3.6 --role r1 --handler test_lambda.handler --timeout 30 --zip-file fileb:///tmp/testlambda.zip
awslocal lambda invoke --function-name f1 /tmp/tmp.out
```

The result is that the first two invocations succeed (see `repositories` and `Functions` below), whereas the third invocation to KMS fails, as it is trying to access AWS directly (and no credentials are configured in the Lambda).

```
START RequestId: 587faa35-644d-44ea-8c21-40424847f2a7 Version: $LATEST
/var/runtime/urllib3/connectionpool.py:851: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
{'repositories': [], 'ResponseMetadata': {'HTTPStatusCode': 200, ...}
/var/runtime/urllib3/connectionpool.py:851: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
{'Functions': [...], 'ResponseMetadata': {'HTTPStatusCode': 200, ...}
/var/runtime/urllib3/connectionpool.py:851: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
An error occurred (UnrecognizedClientException) when calling the ListKeys operation: The security token included in the request is invalid.: ClientError
Traceback (most recent call last):
  File "/var/task/test_lambda.py", line 5, in handler
    print(boto3.client("kms").list_keys())
  File "/var/runtime/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/var/runtime/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (UnrecognizedClientException) when calling the ListKeys operation: The security token included in the request is invalid.
```

Hope that helps - please keep us posted how it goes. Please re-open this issue if the problem persists or if you cannot replicate the above behavior with the latest image.. Thanks for your help!
