### ISSUE TITLE
bug: EC2 instance create-snapshots failure

### ISSUE THREAD

**Issue by dhananjayjk** [localstack/localstack#4672]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`Unable to parse response (syntax error: line 1, column 54), invalid XML received. Further retries may succeed:
b'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">\n<title> 500 Internal Server Error</title>\n< h1>Internal Server Error</h1>\n<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>\n'
![image](https://user-images.githubusercontent.com/42510914/135445760-bf423f38-9088-43ad-bb54-e956a40683f8.png)
![image](https://user-images.githubusercontent.com/42510914/135446009-5c09a7b6-1f56-420c-83db-4e7e75d63f9e.png)

### Expected Behavior

{
    'Snapshots': [
        {
            'Description': 'string',
            'Tags': [
                {
                    'Key': 'string',
                    'Value': 'string'
                },
            ],
            'Encrypted': True|False,
            'VolumeId': 'string',
            'State': 'pending'|'completed'|'error',
            'VolumeSize': 123,
            'StartTime': datetime(2015, 1, 1),
            'Progress': 'string',
            'OwnerId': 'string',
            'SnapshotId': 'string',
            'OutpostArn': 'string'
        },
    ]
}

### How are you starting LocalStack?

With a `docker run` command

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker pull localstack/localstack
    docker run  -d -p 4566:4566 -p 4571:4571 localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)
    
    aws configure
    aws --endpoint-url=http://localhost:4566  ec2 run-instances --image-id ami-03cf127a
    aws --endpoint-url=http://localhost:4566  ec2 create-snapshots --instance-specification InstanceId=<ID>

### Environment

```markdown
- OS: Ubuntu 18.04
- LocalStack: latest
```

**Comment by dhananjayjk** [comment]
Hi @mgagliardo,
Were you able to recreate the error?

**Comment by mgagliardo** [comment]
Hi @dhananjayjk, yes. Sorry for the delay I have been quite busy but been able to reproduce and now working on a fix, this is on moto's side so it will take a few. Thanks for understanding. Cheers!

**Comment by dhananjayjk** [comment]
Hi @mgagliardo,
thank you for your response.
Meanwhile, is there any way to create working docker image from older localstack versions for the above use case?
