### ISSUE TITLE
bug: Elasticache not saving state

### ISSUE THREAD

**Issue by wesleymilan** [localstack/localstack#4674]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After restarting docker the Elasticache Cluster doesn't work anymore and we have to create it again. Also, it's not saving on Pods.

### Expected Behavior

After restarting docker Elasticache cluster previously created should be available

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker-compose up

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

aws elasticache describe-cache-clusters \
    --endpoint-url=http://localhost:4566

### Environment

```markdown
- OS: MacOS
- LocalStack: Lastest
```

**Comment by whummer** [comment]
Thanks for reporting @wesleymilan . This should be fixed in the meantime - can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists. Thanks for your help!

**Comment by wesleymilan** [comment]
Hi whummer, thank you! These is my tests results:

- When running using `docker-compose up -d` and stop using `docker-compose stop` it works perfectly.

- When running using `docker-compose up` and stop using `CTRL + c` it fails with `ERROR: 2` and even saving the files into the data folder it doesn't restore the previous state of Elasticache Cluster.
I believe it's related to the kill signal of the service or something like that, I had a similar problem before. I don't know is your architecture, but a good solution would be saving the final state of a resource when it is created.
