### ISSUE TITLE
SQS does not delete message after acknowledgment from code

### ISSUE THREAD

**Issue by JoaoRXFernandesJG** [localstack/localstack#468]
await sqsClient.DeleteMessageAsync(new DeleteMessageRequest(_queueUrl, message.ReceiptHandle));

Should delete message from queue but not working.

Happy to help if you point me in the right direction.

Cheers,

Joao

**Comment by wcalebgray** [comment]
+1 this is leaving a gap in my test suite currently

**Comment by whummer** [comment]
Can you please provide a few more details @wcalebgray - ideally, a small self-contained example that makes it easier to reproduce this issue. Thanks!

**Comment by whummer** [comment]
Unable to reproduce this issue - added a test in [this PR](https://github.com/localstack/localstack/pull/1742) to ensure we have this covered and don't run into a regression in the future.

Please report here with more details if the problem persists.

**Comment by srini85** [comment]
Ive also got the same issue when using a dotnet client to delete the message of the queue. @whummer - the merged test case is not quite correct i think. It verifies the message does not exist in the queue after receiving it and deleting it. I understand the default visibility timeout is 30 seconds so whether the delete is called or not, I think the test case would pass if I am not mistaken

**Comment by whummer** [comment]
Thanks for your message @srini85 . Good point about the message visibility.

It does seem to work, though, even if setting the visibility timeout to `0`. The tests have been updated in this PR: #1781 - can you please take a look if this addresses your concern?

**Comment by srini85** [comment]
@whummer I think the test case is now correct because the visibility is set to 0. With regards to my earlier comment on having this issue, I found it to to be an issue with the way I was using the library. I was pointing to an incorrect SQS client and hence i was having an issue. Its working fine for me
