### ISSUE TITLE
bug: Container image lambdas do not support ImageConfig parameters

### ISSUE THREAD

**Issue by evjrob** [localstack/localstack#4685]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

Container image lambdas should support the ImageConfig parameters to override WORKDIR, ENTRYPOINT, and CMD at execution time.

If you attempt to create a container image lambda function with the following ImageConfig:

    {
      "EntryPoint": [
        "python",
        "-m",
        "awslambdaric"
      ],
      "Command": [
        "app.lambda_handler"
      ],
      "WorkingDirectory": "/my/work/dir"
    }

The produced lambda in localstack has no ImageConfig:
    
    {
      "FunctionName": "test",
      "FunctionArn": "arn:aws:lambda:us-east-1:000000000000:function:test",
      "Role": "arn:aws:iam::012345678901:role/DummyRole",
      "Handler": "handler.handler",
      "Description": "",
      "Timeout": 3,
      "LastModified": "2021-10-01T17:47:20.296+0000",
      "Version": "$LATEST",
      "VpcConfig": {},
      "TracingConfig": {
          "Mode": "PassThrough"
      },
      "RevisionId": "2fe1832e-af46-478c-ba07-93752907a3bc",
      "Layers": [],
      "State": "Active",
      "LastUpdateStatus": "Successful",
      "PackageType": "Image"
    }

### Expected Behavior

    {
      "FunctionName": "test",
      "FunctionArn": "arn:aws:lambda:us-east-1:000000000000:function:test",
      "Role": "arn:aws:iam::012345678901:role/DummyRole",
      "Handler": "handler.handler",
      "Description": "",
      "Timeout": 3,
      "LastModified": "2021-10-01T17:47:20.296+0000",
      "Version": "$LATEST",
      "VpcConfig": {},
      "TracingConfig": {
        "Mode": "PassThrough"
      },
      "RevisionId": "2fe1832e-af46-478c-ba07-93752907a3bc",
      "Layers": [],
      "State": "Active",
      "LastUpdateStatus": "Successful",
      "PackageType": "Image"
      "ImageConfigResponse": {
        "ImageConfig": {
            "EntryPoint": [
                "python",
                "-m",
                "awslambdaric"
            ],
            "Command": [
                "app.lambda_handler"
            ],
            "WorkingDirectory": "/my/work/dir"
        }
    }

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker-compose up

with the following service defined in docker-compose.yml:

    my_localstack:
      container_name: "my_localstack"
      image: localstack/localstack:0.12.18
      network_mode: bridge
      ports:
        - "127.0.0.1:53:53"
        - "127.0.0.1:53:53/udp"
        - "127.0.0.1:443:443"
        - "127.0.0.1:4566:4566"
      environment:
        - LOCALSTACK_API_KEY=*****
        - SERVICES=lambda
        - DEBUG=1
        - DATA_DIR=/tmp/localstack/data
        - LAMBDA_EXECUTOR=docker
        - LAMBDA_REMOTE_DOCKER=true
        - DOCKER_HOST=unix:///var/run/docker.sock
        - HOST_TMP_FOLDER=${TMPDIR:-/tmp/}localstack
      volumes:
        - "${TMPDIR:-/tmp}/localstack:/tmp/localstack"
        - "/var/run/docker.sock:/var/run/docker.sock"

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

     aws lambda --endpoint=http://127.0.0.1:4566 --region=us-east-1 create-function --function-name test --package-type Image --code "ImageUri=helloworld:latest" --image-config file://imageconf.json --role arn:aws:iam::012345678901:role/DummyRole

where imageconf.json contains:

    {
      "EntryPoint": [
        "python",
        "-m",
        "awslambdaric"
      ],
      "Command": [
        "app.lambda_handler"
      ],
      "WorkingDirectory": "/my/work/dir"
    }

### Environment

```markdown
- OS: Windows 10 with WSL2
- LocalStack: 0.12.18
```

### Anything else?

Creating a new docker image that contains the following hard-coded WORKDIR, ENTRYPOINT, and CMD works exactly as expected:

    FROM helloworld:latest

    WORKDIR /my/work/dir
    ENTRYPOINT ["python", "-m", "awslambdaric"]
    CMD ["app.lambda_handler"]

**Comment by whummer** [comment]
Thanks for reporting @evjrob . This should be fixed in the meantime - can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists.. Thanks for your help!

**Comment by evjrob** [comment]
You're absolutely correct! Thanks for the quick fix, and my apologies for neglecting to test on the latest docker image before submitting the issue. The following command still doesn't appear to return the expected configuration JSON with the ImageConfig section, but this is only a cosmetic issue for me.
    
    aws lambda --endpoint=http://127.0.0.1:4566 --region=us-east-1 get-function-configuration --function-name <my_function_name>
