### ISSUE TITLE
bug: <SERVICE>_PORT_EXTERNAL doesn't work for Neptune and Elasticache

### ISSUE THREAD

**Issue by wesleymilan** [localstack/localstack#4691]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm trying to setup a stable development environment that needs to run automatically when the container starts, but the port of services change every time the container is started, so I'm trying to set a fixed port for each one but it also doesn't work, the port number stays the default and changing on every start-up.

### Expected Behavior

It should accept and run the service with the port specified on docker-compose.yml

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker-compose up

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```
localstack.docker:
    container_name: "localstack"
    image: localstack
    expose:
      - 53
      - 443
      - 4510-4530
      - 4566-4620
      - 6379
      - 8182
    ports:
      - "53:53"
      - "4443:443"
      - "4510-4530:4510-4530"
      - "4566-4620:4566-4620"
      - "6379:6379"
      - "8182:8182"
    environment:
      - LOCALSTACK_API_KEY=XXXXXXXXX
      - SERVICES=iam,sqs,sns,sts,cloudwatch,lambda,appconfig,iot,neptune,elasticache,apigateway
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
      - NEPTUNE_PORT_EXTERNAL=8182
      - ELASTICACHE_PORT_EXTERNAL=6379
    volumes:
      - "./localstack/tmp:/tmp/localstack"
```

### Environment

```markdown
- OS: MacOS
- LocalStack: Lastest
```

### Anything else?

My trial period is ending and after two weeks of trying to use localstack I don't know if it worth to subscribe

**Comment by alexrashed** [comment]
Hi @wesleymilan and sorry for the delay on your question.
The `*_PORT_EXTERNAL` configuration has been deprecated and is not used anymore. Instead we are using "external service ports", a range of ports used for services which need their own port. You already added that do your compose too (but it would be worth updating your config, we have a nice example here in the root of the repo).
You can find more information on this in our docs: https://docs.localstack.cloud/references/external-ports/
Let me know if this helps! Thanks!
