### ISSUE TITLE
feature request: Override AWS_ENDPOINT_URL environment variable in lambda

### ISSUE THREAD

**Issue by Tobolov** [localstack/localstack#4698]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Ability to override the environment variable AWS_ENDPOINT_URL within docker containers spawned to service lambda functions.

I have tried `LAMBDA_DOCKER_FLAGS=-e AWS_ENDPOINT_URL=http://127.0.0.1:15000`, however this does not work.
I also tried setting `EDGE_PORT=15000`, which successfully change the port in AWS_ENDPOINT_URL, but it broke kinesis and seems sort of hacky.

### 🧑‍💻 Implementation

Add a new environment variable `LAMBDA_AWS_ENDPOINT_URL` which when present, overrides the environment variable AWS_ENDPOINT_URL provided to the function.

This can be implemented within the `/localstack/services/awslambda/lambda_executors.py` on LambdaExecutorContainers._execute() function.

**Comment by pinzon** [comment]
It's fixed if you pass the lambda flags using quotes like this (you can ignore how I start lambda):

`LAMBDA_DOCKER_FLAGS="-e AWS_ENDPOINT_URL=http://127.0.0.1:15000" python bin/localstack start --host`

if you don't use them you're passing to different env vars.
