### ISSUE TITLE
aws-sdk-ruby raise where awscli works

### ISSUE THREAD

**Issue by ook** [localstack/localstack#472]
Hi,

I meet a weird bug when using ruby `aws-sdk` with localstack, whereas `awscli` works perfectly with localstack.

```
Aws::S3::Resource.new.bucket('mybucket').exists?

/usr/local/lib/ruby/2.2.0/net/http.rb:879:in `initialize': unable to connect to `mybucket.localstack`; SocketError: getaddrinfo: Name or service not known (Seahorse::Client::NetworkingError)` raised by Aws Seahorse.
```

In the same container, it works with awscli:

```
root@35afc611394b:/app/user# aws --endpoint-url=http://localstack:4572 s3 mb s3://mybucket
make_bucket: mybucket
```

I created a project with a docker-compose setup to show the problem: https://github.com/ook/localstack-s3-problem

Have I forget some configuration to make localstack works with `aws-sdk-ruby` or is it a bug in aws-sdk-ruby ?

**Comment by whummer** [comment]
Hi @ook , this is a known issue/limitation. Please refer to the Troubleshooting section of the README - you'll need to configure the ruby `aws-sdk` to use *path based addressing* instead of *host based addressing*.

**Comment by robkinyon-roivant** [comment]
This comes up as a top hit when searching for "ruby aws-sdk-s3 localstack", so I thought I would share the actual answer.
```ruby
      require 'aws-sdk-s3'
      Aws.config.update(
        endpoint: 'http://localhost:4572',
        credentials: Aws::Credentials.new('sofake', 'solie'),
        region: 'us-east-1',
        force_path_style: true,
      )
      Aws::S3::Resource.new.create_bucket(bucket: 'foo')
```
