### ISSUE TITLE
Bug: v0.12.17 breaks GitHub Actions (v0.12.18 still broken)

### ISSUE THREAD

**Issue by micheleangioni** [localstack/localstack#4720]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When upgrading LocalStack to v0.12.17, Node.js tests in GitHub Actions cannot connect anymore

### Expected Behavior

Upgrading to v0.12.17 doesn't break the tests

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

Go to this page https://github.com/micheleangioni/sls-node-ts/commits/testBranch

Tests running at commit 79dc94d23d3cf2c94ea5d2aa4254168fe75946b6 with LocalStack v0.12.16 run without problems https://github.com/micheleangioni/sls-node-ts/runs/3863736562

Just updating LocalStack to v0.12.17 is enough to break everything, see https://github.com/micheleangioni/sls-node-ts/commit/fb7c8632412b338297da6b9bfe72ba2f49082caf
tests failing here https://github.com/micheleangioni/sls-node-ts/runs/3863773280

### Environment

```markdown
GitLab CI conf: https://github.com/micheleangioni/sls-node-ts/blob/testBranch/.github/workflows/ci.yml

docker-compose: https://github.com/micheleangioni/sls-node-ts/blob/testBranch/dev/docker-compose.yaml
```

### Anything else?

There are no breaking changes in the release notes. v0.12.18 is broken as well.

Please, let me know if I can support with the investigation.

Thanks

**Comment by micheleangioni** [comment]
Hey @dfangl , thanks for your answer.

I've added the container logs as you suggested, here you can see the output: https://github.com/micheleangioni/sls-node-ts/runs/3944281825 .
Let me know if I can provide further help.

**Comment by dfangl** [comment]
@micheleangioni Actually, could you move that build step after the test execution? So we can also see the requests the tests make.
Generally, from what I see, a first guess is a region mismatch between the table creation and the queries itself. With 0.12.17, multi region support was added to LocalStack, depending on the request. If you tests ask for us-east-1 tables, but eu-west-1 tables are created, it will not find them.
This differs from the behavior of 0.12.16. For now you can disable this behavior using the (deprecated) configuration options `DEFAULT_REGION=us-east-1` and `USE_SINGLE_REGION=1`
