### ISSUE TITLE
bug: LAMBDA_DOCKER_DNS unavailable pro users? Doesn't work in conjunction with LOCALSTACK_API_KEY.

### ISSUE THREAD

**Issue by m-chandler** [localstack/localstack#4727]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Unable to use LAMBDA_DOCKER_DNS in conjunction with LOCALSTACK_API_KEY, seems to be forcefully overridden to 127.0.0.1.

### Expected Behavior

Should be able to override the Lambda container's DNS.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

1. Use the below docker-compose file (with a valid API key).
`docker-compose up`

```
version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    network_mode: bridge
    ports:
      - "127.0.0.1:53:53"
      - "127.0.0.1:53:53/udp"
      - "127.0.0.1:443:443"
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4571:4571"
    environment:
      - SERVICES=${SERVICES- }
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - LAMBDA_EXECUTOR=docker-reuse
      - LOCALSTACK_API_KEY=<MASKED>
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR:-/tmp/}localstack
      - LAMBDA_DOCKER_DNS=8.8.8.8
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

2. Deploy the following CloudFormation template (just ignore what it does, it's not relevant).
`awslocal cloudformation create-stack --template-body file://lambda.yml 
--stack-name lambda`

```
---
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Resources:
  ConnectFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: test
      MemorySize: 2048
      Timeout: 15
      Handler: index.handler
      Runtime: python3.8
      PackageType: Zip
      InlineCode: |
        import os
        import boto3
        from urllib.request import urlopen
        def handler(event, context):
          with urlopen("https://api.nasa.gov/planetary/apod?api_key=DEMO_KEY") as response:
            response_content = response.read()
            print(response_content)
```

3. Execute the function contained within the CloudFormation Stack (just to get the Lambda container spawned).
`awslocal lambda invoke --function-name test blah.txt`

4. Inspect the Lambda container.
`docker ps -a` - note ID of Lambda container
`docker inspect <container_id>`
Note host config DNS points to 127.0.0.1:
```
            "Dns": [
                "127.0.0.1"
            ]
```

5. Repeat steps (remove LOCALSTACK_API_KEY) - should now work.

### Environment

```markdown
OS: Win 10
LocalStack version: 0.12.18
LocalStack Docker container id: 523619e72cbd
LocalStack build date: 2021-10-12
LocalStack build git hash: 2f1c32e4
```

**Comment by m-chandler** [comment]
Hi @dfangl , thanks for the response.

I do actually want to use the localstack container DNS, the problem is we have a complex environment with multiple localstack instances on the same host; I am using a custom bridge network and trying to get the Lambda containers to talk directly to the IP of their parent localstack container for DNS (e.g. 172.17.0.2); I can't bind the parent localstack containers to the host IP because this would allow only one container to bind.

In my testing with busybox this works; I'm just lacking the necessary control over how Localstack spawns the Lambda container. I'd be able to do this with `LAMBDA_DOCKER_DNS` if the override wasn't getting in the way.

Setting DNS_ADDRESS to 0 just shifts the problem. The Lambda containers now get the right DNS IP, but it disables the DNS server which is not the desired effect.

I tried setting DNS_ADDRESS to my desired IP (e.g. 172.17.0.2); but still in the logs I see: `Starting DNS servers (tcp/udp port 53 on 0.0.0.0)...`, and then spawned Lambda's get 127.0.0.1.

**Comment by nghia11110** [comment]
> Hi @m-chandler ! Can you try disabling the DNS Server for transparent endpoint injection by setting `DNS_ADDRESS=0` when starting localstack? Currently the [LocalStack DNS Server](https://docs.localstack.cloud/tools/local-endpoint-injection/dns-server/) overrides the `LAMBDA_DOCKER_DNS` setting.

this works for me. Thank you so much for your help
