### ISSUE TITLE
bug: invalid VPC IPv6 CIDR block

### ISSUE THREAD

**Issue by bhuisgen** [localstack/localstack#4729]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello,

It seems that the generated VPC IPv6 CIDR blocks are invalid. Localstack returns a CIDR block 2400:6500:d9d1:1f27::/56 but it should be 2400:6500:d9d1:1f00::/56 

Maybe, I'm wrong but I didn't reproduce this behaviour with the AWS console.

### Expected Behavior

2400:6500:d9d1:1f00::/56

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

    docker run localstack/localstack

    aws --endpoint-url http://192.168.0.253:14566 ec2 create-vpc --cidr-block=10.0.0.0/16 --amazon-provided-ipv6-cidr-block

```
{
    "Vpc": {
        "CidrBlock": "10.0.0.0/16",
        "DhcpOptionsId": "dopt-1a2b3c4d2",
        "State": "pending",
        "VpcId": "vpc-006d8edb",
        "OwnerId": "000000000000",
        "InstanceTenancy": "default",
        "Ipv6CidrBlockAssociationSet": [
            {
                "AssociationId": "vpc-cidr-assoc-aca0cf13",
                "Ipv6CidrBlock": "2400:6500:d9d1:1f27::/56",
                "Ipv6CidrBlockState": {
                    "State": "associated"
                }
            }
        ],
        "CidrBlockAssociationSet": [
            {
                "AssociationId": "vpc-cidr-assoc-f9da457c",
                "CidrBlock": "10.0.0.0/16",
                "CidrBlockState": {
                    "State": "associated"
                }
            }
        ],
        "Tags": []
    }
}
```

### Environment

```markdown
- OS: Linux Debian
- LocalStack: latest image (localstack/localstack@sha256:b8cac89822390506ed6eceb6aa16e4b1228af3bd8b6bcf094378b446cca87406)
```

### Anything else?

Same problem with Terraform: 

`Error: "2400:6500:ac3a:26eb::/56" is not a valid CIDR block; did you mean "2400:6500:ac3a:2600::/56"?`

**Comment by dfangl** [comment]
Quick update: A fix for this behavior is implemented. I will close this issue once the PR is merged and available in LocalStack.
