### ISSUE TITLE
bug: Unable to use $default stage for API Gateway v2

### ISSUE THREAD

**Issue by beanaroo** [localstack/localstack#4731]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

While being able to create a stage named `$default` on an API Gateway of type HTTP, it is not possible to query it using the API.

Using the CLI:

```
awslocal apigatewayv2 get-stage --api-id c4ef1ad5 --stage-name '$default'

An error occurred (NotFoundException) when calling the GetStage operation: Unable to find stage "%24default" in API "c4ef1ad5"
```

Using Terraform `apply`:

```
$ terraform apply

aws_apigatewayv2_stage.default: Creating...

Error: Provider produced inconsistent result after apply

When applying changes to aws_apigatewayv2_stage.default, provider
"registry.terraform.io/hashicorp/aws" produced an unexpected new value: Root
resource was present, but now absent.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```

Using Terraform `import`:
```
$ terraform import aws_apigatewayv2_stage.default 'c4ef1ad5/$default'

aws_apigatewayv2_stage.default: Importing from ID "c4ef1ad5/$default"...

Error: NotFoundException: Unable to find stage "%24default" in API "c4ef1ad5"
{
  RespMetadata: {
    StatusCode: 404,
    RequestID: ""
  },
  Message_: "Unable to find stage \"%24default\" in API \"c4ef1ad5\""
}

```

### Expected Behavior

The created resource should be available in order to make use of the special `$default` stage.

- [AWS Documentation](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-stages.html)

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

Unmodified [docker-compose.yml](https://github.com/localstack/localstack/blob/master/docker-compose.yml)

```
docker-compose pull
docker-compose up
```

##### 1. Create API

```
$ awslocal apigatewayv2 create-api --name foobar --protocol-type HTTP

{
    "ApiEndpoint": "8220ba2c.execute-api.localhost.localstack.cloud:4566",
    "ApiId": "c4ef1ad5",
    "Name": "foobar",
    "ProtocolType": "HTTP"
}
```

##### 2. Create Stage

```
$ awslocal apigatewayv2 create-stage --api-id c4ef1ad5 --stage-name '$default'

{
    "CreatedDate": "2021-10-14T22:24:15.343372+13:00",
    "StageName": "$default"
}
```

##### 3. Query Stage

```
$ awslocal apigatewayv2 get-stage --api-id c4ef1ad5 --stage-name '$default'

An error occurred (NotFoundException) when calling the GetStage operation: Unable to find stage "%24default" in API "c4ef1ad5"
```
    

### Environment

```markdown
- OS: Arch Linux
- LocalStack: 0.12.18
```

### Anything else?

Omitting the `$` works, but `$default` has a special behaviour of serving from the API base path. I'm not sure if this part is implemented in localstack.

I am using a Pro License Key from a trial evaluation.

**Comment by whummer** [comment]
Thanks for reporting @beanaroo , and apologies for the delayed response. We had an issue with escaping the URL-encoded path parameters which resulted in an issue when using `$default` (which gets escaped to `%24default`). 

This should be fixed in the meantime - can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists - thanks for your help!

**Comment by zlintz** [comment]
For those that find this issue but are just trying to do a normal import via terraform of the `$default` stage, single quotes are your friend because of the `$`

`terraform import aws_apigatewayv2_stage.your_api_stage 'asdffdsa/$de
fault'`
