### ISSUE TITLE
feature request: Allow using the amazon-maintained lambda docker image repository

### ISSUE THREAD

**Issue by isaac-j-miller** [localstack/localstack#4733]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Feature description

Allow using the amazon/aws-lambda-* docker image repositories instead of lambdaci. The structure of this repository doesn't currently work with the expected structure of the lambda repository.
I think that it makes more sense to use the docker images released and maintained by amazon rather than lambdaci, which hasn't been updated in forever (probably because the amazon repository made it obsolete)

### 🧑‍💻 Implementation

I have a fork and a PR (https://github.com/localstack/localstack/pull/4734) that implements this

**Comment by awilkins** [comment]
Question : isn't it an issue here that the `lambci/lambda` images use a completely different invocation mechanism?

I've been picking this apart this week trying to automate the creation of GraalVM native images ; my thinking was

- Create a Java / GraalVM runtime so I can use the `native-image-agent` tool to harvest configuration
- Use Localstack to run the API test suite against the functions integrated with APIG
   - Bind mount an output folder so I can gather the agent output
- Use the config outputs to build native images

But if I use a standard image with the AWS [RIE](aws/aws-lambda-runtime-interface-emulator) in it, my functions never execute, except when I open a shell in the container and `curl` the endpoint manually. The `lambci/lambda` images never write the config files.

What I've been able to glean so far is that Localstack doesn't seem to execute Lambdas in containers by calling the `2015-03-31/functions/function/invocations` endpoint over the network. 

It cheats :

- Containers are started with an entrypoint of `/bin/bash`
- The real entrypoint is then read from the container definition and `docker exec` is used to run it
  - The entrypoint in the `lambci` containers is [rapid](https://github.com/lambci/docker-lambda/blob/master/provided/run/init.go), a small Go program that fulfils the role that the standard RIE does, plus a few more features ..
  - The event is injected either by putting it in an environment variable, or passing it via `STDIN`
  - `rapid` then handles the business of being the local implementation of the Lambda runtime API, starts up the bootstrap, sends the event to it, and then kills it when it returns a response (I think the `SIGKILL` is what's stopping my config being written).

This is understandable in the context of docker networking being a PITA, but I think it means that Localstack isn't currently compatible with images that don't support the kludge of injecting the event body via `docker exec`.
