### ISSUE TITLE
SQS: Does it have UI?

### ISSUE THREAD

**Issue by Oleg26Dev** [localstack/localstack#4756]
### Is there an existing issue for this?

- [X] I have searched the existing issues and read the documentation

### Question

Does SQS have an UI like ElasticMQ has  to check the queues state?

(UI is bundled with both standard and native images. It is exposed on the address that is defined in rest-stats configuration (by default 0:0:0:0:9325).
https://github.com/softwaremill/elasticmq)

**Comment by thrau** [comment]
This feature is available in LocalStack pro. Should you have problems with the pro version, please let us know in Slack, thanks!
