### ISSUE TITLE
question: network bridge or not?

### ISSUE THREAD

**Issue by webaaz** [localstack/localstack#4757]
### Is there an existing issue for this?

- [X] I have searched the existing issues and read the documentation

### Question

I use localstack and it was working well with SQS.

Now I need to add lambda and trigger.

The command ```localstack config validate```
Tell me that my network should be problematic
```WARNING:bootstrap.py: Network mode is not set to "bridge" which may cause networking issues in Lambda containers. Consider adding "network_mode: bridge" to you docker-compose file.```

But if I use ```"network_mode: bridge"``` instead of my own network, The local DNS doesn't work anymore and I got an error because the container "localstack" isn't defined in DNS and other container could not send messages to the queue.
```Error executing "SendMessage" on "http://localstack:4566/000000000000/queue"; AWS HTTP error: cURL error 6: Could not resolve host: localstack```

SO how can I use the bridge mode and resolve the localstack container name?

**Comment by dfangl** [comment]
I will close this now, if you have any further issues with this, please do not hesitate to reopen or create a new ticket!

**Comment by webaaz** [comment]
Hi! Thanks for you answer, it's now clear for me.
