### ISSUE TITLE
question: No longer possible to wait for initScripts:initialized?

### ISSUE THREAD

**Issue by 1ma** [localstack/localstack#4769]
### Is there an existing issue for this?

- [X] I have searched the existing issues and read the documentation

### Question

A [recent commit](https://github.com/localstack/localstack/commit/f41b25cc8d68e97ce8eacd4374ded4a8072e50f6#diff-368e25a43c4a3200ecb9ae21e7b2a94da05d8eb24680bd6c2a37ee0e275bcd0aL67) scrapped the `{"features:initScripts":"initialized"}` feature that my team was relying on to bootstrap our development environment.

Basically we are putting a provisioning script in `/docker-entrypoint-initaws.d/` that installs Terraform and runs our Terraform definitions against `http://localhost:4566`. Then, the service that needs the AWS infrastructure has an entrypoint that polls `http://localstack:4566/health` and keeps looking for `{"features:initScripts":"initialized"}` in the response before attempting to actually start the service.

We found by trial and error that this was the most reliable way to bring up our stack, as opposed to looking for specific services to appear in the `/health` payload. However, now with this change we can't detect exactly when our Terraform provisioning finishes. It'd be great to get back that feature, or to have another way to detect when the LocalStack entrypoint has finished running the scripts in `/docker-entrypoint-initaws.d/`. For now we'll be sticking to `:0.12.19` instead of `:latest` as suggested.

Thank you.

**Comment by thrau** [comment]
should be back to normal. container will be deployed in about 45 minutes. please give it a whirl then
