### ISSUE TITLE
LocalStack SQS: using .NET AWS SDK program runs indefinitely when requesting messages with MessageAttributeNames = "All"

### ISSUE THREAD

**Issue by Svaly** [localstack/localstack#4783]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When requesting messages from localstack SQS using .NET SDK **with** option MessageAttributeNames = "All" **program never finishes.**

When requesting messages from localstack SQS  using .NET SDK **without** option MessageAttributeNames program works as expected (but of course it doesn't return any custom MessageAttributes, which I need).

When requesting messages from real AWS SQS using .NET SDK with option MessageAttributeNames = "All" program works as expected.

When requesting messages from localstack SQS using AWS CLI with option MessageAttributeNames = "All" program works as expected

### Expected Behavior

When requesting messages from localstack SQS using .NET SDK **with** option MessageAttributeNames = "All" program should be able to get all messages with all custom attributes instead of running indefinitely without returning anything.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

I prepared sample one clasas console .net project to reproduce the problem.

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)
[https://github.com/Svaly/aws-localstack-test/blob/main/docker-compose.yml](https://github.com/Svaly/aws-localstack-test/blob/main/docker-compose.yml)

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

[https://github.com/Svaly/aws-localstack-test/blob/main/LocalstackTest/Program.cs ](https://github.com/Svaly/aws-localstack-test/blob/main/LocalstackTest/Program.cs )

### Environment

```markdown
- OS: Windows 10
- LocalStack: latest
```

**Comment by chaz-doyle-cko** [comment]
I am having the same issue... But it is also occurring if I specify an explicit list of MessageAttributeNames to return.

**Comment by Stephen-Stanbridge** [comment]
I've got same issue :(

**Comment by KrishnanRanjithkumar** [comment]
Hi @Svaly  @Stephen-Stanbridge  @chaz-doyle-cko  thanks for reporting. This issue should be fixed in  #4853 . Could you please pull the latest docker image and give it another try? Thanks!!!!

**Comment by Svaly** [comment]
Hi @KrishnanRanjithkumar it is working now! Thank you!
