### ISSUE TITLE
The path is not shared from OS X and is not known to Docker.

### ISSUE THREAD

**Issue by ozbillwang** [localstack/localstack#480]
Get this error when start localstack on mac.

```
$ localstack start --docker
Starting local dev environment. CTRL-C to quit.
docker run -it -p 8080:8080 -p 443:443 -p 4567-4582:4567-4582 -p 4590-4593:4590-4593 -v "/var/folders/q5/s3zcbh6mzhwq4gxj/T/localstack:/tmp/localstack" -v "/var/run/docker.sock:/var/run/docker.sock" -e DOCKER_HOST="unix:///var/run/docker.sock" -e HOST_TMP_FOLDER="/var/folders/q5/s3zcbh6mzhwq4gxj/T/localstack" "localstack/localstack"
docker: Error response from daemon: Mounts denied:
The path /var/folders/q5/s3zcbh6mzhwq4gxj/T/localstack
is not shared from OS X and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> File Sharing.
See https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.
```

I installed `docker for mac`. 

How to fix it?

**Comment by whummer** [comment]
Thanks for reporting @ozbillwang . Have you tried following the instructions to configure `Docker -> Preferences... -> File Sharing`? Below is a screenshot of the configuration window, you can add the `/var` directory using the plus sign `+`.

Also, can you please post the output of this command:
```
ls -la /var
```

![image](https://user-images.githubusercontent.com/2807888/33225352-abc0fca2-d143-11e7-9fb0-3796b82b7d93.png)

**Comment by ozbillwang** [comment]
I try to share the folder which is a link to /private/var/folder in mac. 

But get this error.  Seems it is problem in `docker for mac`.

<img width="567" alt="screen shot 2017-11-25 at 4 47 46 pm" src="https://user-images.githubusercontent.com/8954908/33227822-69181ae4-d200-11e7-939e-8b3f92f3e575.png">

**Comment by whummer** [comment]
What is the output of these commands:
```
localstack --version
```

Maybe this command works for you:
```
TMPDIR=/private$TMPDIR localstack start --docker
```

**Comment by ozbillwang** [comment]
That's helpful, and in fact this issue has been explained in the README in `docker-compose` part. But I didn't link it to `docker for mac`

**Comment by SparkD3V** [comment]
I get this error too. It;s isnt working whatever i do

**Comment by mmc378** [comment]
> I get this error too. It;s isnt working whatever i do

SAME! Can anyone help?? My error says ERROR: for worker  Cannot start service worker: Mounts denied: 
The path /var/www/static

but there's no pre-existing static path in my computer :/

**Comment by whummer** [comment]
@zyand3v have you tried running this command?
```
TMPDIR=/private$TMPDIR localstack start --docker
```
Can you share a screenshot of your Docker File Sharing preferences?

**Comment by notnmeyer** [comment]
fwiw, adding the path in preferences was not enough for me. i also had to restart docker for mac.

**Comment by davidmatas** [comment]
I solved adding `var/folders` in file sharing

![image](https://user-images.githubusercontent.com/271760/72806821-40309080-3c56-11ea-9fb3-e97e7089e255.png)

**Comment by freddyparedes** [comment]
Hola, tenia el mismo problema en Mac OS, Solo añadí las rutas en "File Sharing" en DockerDesktop, y con VisualStudioCode+ docker plugins for vsc, pude iniciar mi contenedor desde docker-compose.yml + 2do click mouse + "Compose Down".


![image](https://user-images.githubusercontent.com/63678118/85949891-5807f100-b927-11ea-8f62-7f61b6bf9f28.png)

**Comment by djangofan** [comment]
How did you do that?  
Mac-Pro:localstack me$ ln -s /private/var /var
ln: /var/var: Permission denied

Also, Docker user interface refuses to add '/var/folders', which is a folder that technically doesn't exist on a mac.

So, can anyone clarify how you got it working?   I haven't used LocalStack in about two years but this used to work for me back in the day.

**Comment by OGProgrammer** [comment]
Using docker for Mac here too. Using the docker-compose method, see my config

```
  localstack:
    image: localstack/localstack
    container_name: localstack_main
    ports:
      - "4566-4599:4566-4599"
      - "8080:8080"
    environment:
      - SERVICES=sns,ses,sqs
      - DEBUG=true
      - DATA_DIR=/tmp/localstack/data
      - PORT_WEB_UI=8080
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/tmp/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

I have the `/private`, `/tmp` and `/var` folders added in docker permissions. 

When I first try to bring the docker stack up, I first get this error for all my containers configured in my docker-compose.yml:

`ERROR: for localstack  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)`

If I try to bring it up again right after this error, I then get this error for all my containers configured. 

`ERROR: for localstack  Cannot start service localstack: Mounts denied: EOF`

If I take out localstack from my config, all works so something up with localstack. Trying to keep this in my docker-compose.yml and not use the pip install way.

**Comment by djangofan** [comment]
> 
> `ERROR: for localstack Cannot start service localstack: Mounts denied: EOF`
> 
> If I take out localstack from my config, all works so something up with localstack. Trying to keep this in my docker-compose.yml and not use the pip install way.

I don't remember for sure, but to start LocalStack on a MAC,  I think their is a wierdness where you have to pass a pre-defined TMPDIR or something into the docker-compose command in order for it to work.   I don't remember exactly, but I am pretty sure you cannot do it purely from docker-compose.yml without it.     I am not the expert, maybe someone else can chime in.

**Comment by abzal0** [comment]
After adding the folder, restarting both terminal and docker resolved the issue on my side

**Comment by wds33817** [comment]
Thanks [abzal0](https://github.com/abzal0) Save me some time searching!

**Comment by ruimartinsptl** [comment]
Hi, I had a similar problem, check if this solution is useful for you: https://stackoverflow.com/a/73221436/2280741
