### ISSUE TITLE
How do you set the default kinesis region in the new world of multi-region?

### ISSUE THREAD

**Issue by alins** [localstack/localstack#4811]
### Is there an existing issue for this?

- [X] I have searched the existing issues and read the documentation

### Question

I find the documentation super confusing on this point:

```
USE_SINGLE_REGION=1). Deprecated and inactive as of version 0.12.17 - LocalStack now has full multi-region support.
```

followed by

```
USE_SINGLE_REGION: Whether to use the legacy single-region mode, defined via DEFAULT_REGION.
```

which one is it? is it removed or not? 

I'm trying to set kinesis region (using `kinesis-mock`) . default region for `kinesis-mock` is `us-east-1` and I'm creating my stream *after* localstack starts in `us-west-2`.  I can't use `KINESIS_INITIALIZE_STREAMS` to set the region per stream.

according to kinesis-mock doc, once has to use `AWS_REGION` which doesn't seem to work when I set that for localstack. as far as I can tell from the code, localstack doesn't seem to set `AWS_REGION` env variable when it starts `kinesis-mock`, which means (assuming what I just said is correct) while `localstack` *may* multi-region, `kinesis-mock` is hardcoded to `us-east-1`

so how do I do this? i hope the question makes sense

**Comment by whummer** [comment]
Hi @alins , please make sure to pull the `latest` LocalStack Docker image. If you're using the latest image, the region should be entirely determined by the client, and it should work like this:

```
$ AWS_DEFAULT_REGION=us-east-1 awslocal kinesis create-stream --stream-name s1 --shard-count 1
$ AWS_DEFAULT_REGION=us-east-2 awslocal kinesis create-stream --stream-name s2 --shard-count 1
$ AWS_DEFAULT_REGION=us-east-1 awslocal kinesis list-streams                                  
{
    "StreamNames": [
        "s1"
    ]
}
$ AWS_DEFAULT_REGION=us-east-2 awslocal kinesis list-streams                                  
{
    "StreamNames": [
        "s2"
    ]
}
```

Are you able to replicate these results? Please let us know if the problem persists.. Thanks!

**Comment by alins** [comment]
yup, that works. awesome!!
