### ISSUE TITLE
IAM persistence via DATA_DIR 

### ISSUE THREAD

**Issue by nagaliri** [localstack/localstack#4814]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

IAM persistence in DATA_DIR directory so that when we restart the localstack, IAM users will be available.

### 🧑‍💻 Implementation

IAM persistence in DATA_DIR directory so that when we restart the localstack, IAM users will be available.

**Comment by whummer** [comment]
Thanks for reporting @nagaliri . This should be fixed in the meantime - persistence for IAM is now available in the Pro version. Please let us know if the problem persists.. Thanks for your help!
