### ISSUE TITLE
bug: boto3 SQS client has different return than awslocal cli on minikube

### ISSUE THREAD

**Issue by zmcgrath96** [localstack/localstack#4817]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have searched through the other issues on here and have yet to figure out why I am getting this issue. I have two centos pods running in my minikube cluster. I installed localstack on my cluster using the helm command below: 

```bash
helm install localstack localstack-repo/localstack  --set extraEnvVars[0].name=HOSTNAME_EXTERNAL  --set extraEnvVars[0].value="localstack_host"
```

To make sure I set up localstack correctly I did this experiment: I installed `awslocal` cli tool on both of my centos pods. On one pod I ran this (and its corresponding output):

```bash
awslocal sqs create-queue --queue-name application_logs --endpoint=http://localstack:4566/
{
    "QueueUrl": "http://localstack_host:4566/000000000000/application_logs"
}
```

And on the other pod I used the `list-queues` cli command to get the queues. Here is the command and output for that:

```bash
awslocal sqs list-queues --endpoint=http://localstack:4566/
{
    "QueueUrls": [
        "http://localstack_host:4566/000000000000/application_logs"
    ]
}
```

So I know that the queue exists. I also put a message in the queue on one pod and managed to receive that message on the other pod. So I know that I have an SQS queue and I am able to use that queue on 2 different pods. However, I am trying to access the queue in a python script so that I can have a running consumer. Here is what my python script looks like: 

```python
import boto3

session = boto3.Session()
client = session.client('sqs',
                        endpoint_url='http://localstack:4566/',
                        region_name='us-west-2',
                        aws_secret_access_key='x',
                        aws_access_key_id='x',
                        use_ssl=False)


print('Looking for other queues...')
response = client.list_queues()
print(response)
```

When I run this script I get the following output: 

```bash
{'ResponseMetadata': {'RequestId': '7S4KMSXVWWZUR276FWN0P56L48YEICI911VR1GT7OD7L2PSQ4MDG', 'HTTPStatusCode': 200, 'HTTPHeaders': {'content-type': 'text/html; charset=utf-8', 'content-length': '190', 'x-amzn-requestid': '7S4KMSXVWWZUR276FWN0P56L48YEICI911VR1GT7OD7L2PSQ4MDG', 'x-amz-crc32': '214139796', 'access-control-allow-origin': '*', 'access-control-allow-methods': 'HEAD,GET,PUT,POST,DELETE,OPTIONS,PATCH', 'access-control-allow-headers': 'authorization,cache-control,content-length,content-md5,content-type,etag,location,x-amz-acl,x-amz-content-sha256,x-amz-date,x-amz-request-id,x-amz-security-token,x-amz-tagging,x-amz-target,x-amz-user-agent,x-amz-version-id,x-amzn-requestid,x-localstack-target,amz-sdk-invocation-id,amz-sdk-request', 'access-control-expose-headers': 'etag,x-amz-version-id', 'connection': 'close', 'date': 'Sat, 30 Oct 2021 00:01:15 GMT', 'server': 'hypercorn-h11'}, 'RetryAttempts': 0}}
```

So I am in theory connected to the same endpoint and am sending and receiving valid requests from that endpoint. However, I do not see the queue, so I cannot interact with that queue from my python script

### Expected Behavior

My expected behavior is that when I run the python script shown above, I should get a response that has this form: 

```bash
{'QueueUrls': ['http://localstack_host:4566/000000000000/application_logs'], 'ResponseMetadata': {'RequestId': '7S4KMSXVWWZUR276FWN0P56L48YEICI911VR1GT7OD7L2PSQ4MDG', 'HTTPStatusCode': 200, 'HTTPHeaders': {'content-type': 'text/html; charset=utf-8', 'content-length': '190', 'x-amzn-requestid': '7S4KMSXVWWZUR276FWN0P56L48YEICI911VR1GT7OD7L2PSQ4MDG', 'x-amz-crc32': '214139796', 'access-control-allow-origin': '*', 'access-control-allow-methods': 'HEAD,GET,PUT,POST,DELETE,OPTIONS,PATCH', 'access-control-allow-headers': 'authorization,cache-control,content-length,content-md5,content-type,etag,location,x-amz-acl,x-amz-content-sha256,x-amz-date,x-amz-request-id,x-amz-security-token,x-amz-tagging,x-amz-target,x-amz-user-agent,x-amz-version-id,x-amzn-requestid,x-localstack-target,amz-sdk-invocation-id,amz-sdk-request', 'access-control-expose-headers': 'etag,x-amz-version-id', 'connection': 'close', 'date': 'Sat, 30 Oct 2021 00:01:15 GMT', 'server': 'hypercorn-h11'}, 'RetryAttempts': 0}}
```

The only difference between this expected response and the one I am actually getting is the `QueueUrls` field with the correct queue url that I see using the `awslocal` cli. 

### How are you starting LocalStack?

Custom (please describe below)

### Steps To Reproduce

Reproducing: 

1. Start minikube
```bash
minikube start
```
2. Deploy localstack
```bash
helm install localstack localstack-repo/localstack --set extraEnvVars[0].name=HOSTNAME_EXTERNAL --set extraEnvVars[0].value="localstack_host"
```

3. Start up 2 debug centos containers:
```bash
kubectl run debug --image=centos -it -- bash 
# do this one in a different terminal session
kubectl run debug2 --image=centos -it -- bash 
```

4. In each of those containers install python3, aws cli and awslocal cli
```bash
dnf install python3 -y
pip3 install awscli
pip3 install awscli-local
```

5. In one of the debug pods create the queue
```bash
awslocal sqs create-queue --queue-name application_logs --endpoint=http://localstack:4566/
```

6. In the other debug pod list the queues
```bash
awslocal sqs list-queues --endpoint=http://localstack:4566/
```
    You should see a valid queue url

7. Copy and paste the python code from above into some python file and run that file. You should not see the queue

### Environment

```markdown
- OS: MacOS 10.15.7 (Catalina)
- LocalStack: latest
- Minikube: 1.23.2
- Python3: 3.6.8
- boto3: latest
- centos: latest
```

### Anything else?

I have gone over a lot of the other issues submitted and have yet to find a solution. Setting the `HOSTNAME_EXTERNAL` was an idea I got from a different ticket, but I had the same issue with this environment variable and without it. I have also tried using `elasticmq` as the SQS engine, but I got the same issue. Let me know if I have neglected any information. Thank you!

**Comment by pinzon** [comment]
Hi @zmcgrath96 this is not a bug on minikube. if you follow the steps with the docker container or **even with aws** you'll get the same result.

In the steps to reproduce, your awscli commands are using us-east-1 by default but in the python client you're using us-west-2.

SQS queues are region locked. which means if you created a queue in a region like  and then uses a client set to a different region(like in your process),  it won't come up in the result.

I made sure this was the same situation happening on minikube.

Thanks for using Localstack.
