### ISSUE TITLE
bug: The secretsmanager list-secrets command filters incorrectly

### ISSUE THREAD

**Issue by hairyhenderson** [localstack/localstack#4820]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It seems that filters on the Secrets Manager ListSecrets method is incorrectly interpreted by localstack. A filter like `Key=name,Values=/` _should_ mean "any secret where the `name` starts with `/`. However, localstack seems to interpret this as "any secret where the `name` contains `/`".

### Expected Behavior

I get the following behaviour on AWS, and I expect localstack to behave the same way:

```console
$ aws secretsmanager create-secret --name 'testing1/one' --secret-string 'testing1' --query 'Name'
testing1/one
$ aws secretsmanager create-secret --name '/testing2/two' --secret-string 'testing2' --query 'Name'
/testing2/two
```

```console
$ aws secretsmanager list-secrets --filters Key=name,Values='/' --query 'SecretList[*].Name'
/testing2/two
$ aws secretsmanager list-secrets --filters Key=name,Values='!/' --query 'SecretList[*].Name'
testing1/one
```

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    localstack start

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```console
$ aws --endpoint-url=http://localhost:4566 secretsmanager create-secret --name 'testing1/one' --secret-string 'testing1' --query 'Name'
testing1/one
$ aws --endpoint-url=http://localhost:4566 secretsmanager create-secret --name '/testing2/two' --secret-string 'testing2' --query 'Name'
/testing2/two
```

```console
$ aws --endpoint-url=http://localhost:4566 secretsmanager list-secrets --filters Key=name,Values='/' --query 'SecretList[*].Name'
testing1/one    /testing2/two
$ aws --endpoint-url=http://localhost:4566 secretsmanager list-secrets --filters Key=name,Values='!/' --query 'SecretList[*].Name'
```

### Environment

```markdown
- OS: macOS 12.0.1 (Monterey)
- LocalStack: 0.12.19.1
```

**Comment by macnev2013** [comment]
Hello, we are pleased to inform you that we have implemented changes that should resolve your reported issue. Kindly update to the latest LocalStack container image and let us know if your issue has been resolved. Thank you!
