### ISSUE TITLE
bug: S3 Copy Operation fails if source key contains embedded percent encodings

### ISSUE THREAD

**Issue by bodnarbm** [localstack/localstack#4823]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Bucket to Bucket or Key to Key copy operations fail with a 404 Not Found error during the CopyObject operation if the source key has an embedded percent encoding or other url encoding.

### Expected Behavior

Copy Operations should allow the source key to have an embedded percent encoding and should find and copy the S3 object to the new destination key / bucket.

### How are you starting LocalStack?

With a `docker run` command

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

```
❯ docker run -p 4566:4566 -d --name localstack localstack/localstack
```
#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```
❯ echo "Some File" > with%2Furl%2Fencoding
❯ awslocal s3 mb s3://src-bucket
make_bucket: src-bucket
❯ awslocal s3 cp with%2Furl%2Fencoding s3://src-bucket/some/file/with%2Furl%2Fencoding
upload: ./with%2Furl%2Fencoding to s3://src-bucket/some/file/with%2Furl%2Fencoding
❯ awslocal s3 cp s3://src-bucket/some/file/with%2Furl%2Fencoding downloaded_with%2Furl%2Fencoding
download: s3://src-bucket/some/file/with%2Furl%2Fencoding to ./downloaded_with%2Furl%2Fencoding
❯ cat downloaded_with%2Furl%2Fencoding
Some File
❯ awslocal s3 mb s3://dest-bucket
make_bucket: dest-bucket
❯ awslocal s3 cp s3://src-bucket/some/file/with%2Furl%2Fencoding s3://dest-bucket/some/file/with%2Furl%2Fencoding
copy failed: s3://src-bucket/some/file/with%2Furl%2Fencoding to s3://dest-bucket/some/file/with%2Furl%2Fencoding An error occurred (404) when calling the CopyObject operation: Not Found
```

### Environment

```markdown
- OS: Windows 10 running Ubuntu 20.04 under WSL2
- LocalStack: latest
```

### Anything else?

While this was discovered when using localstack, I believe the root issue here is in the way moto handles url decoding the source key during the copy operation. I opened https://github.com/spulec/moto/issues/4513 directly with moto, but wanted to submit the issue here in case further support is needed in localstack after the moto issue is addressed.

**Comment by bodnarbm** [comment]
Just an quick update that spulec/moto#4514 merged into the upstream moto to address the issue there. If there's anything I can do to help with pulling that change into moto-ext, please let me know.

Thanks!

**Comment by whummer** [comment]
Thanks for the pointer @bodnarbm . 👍  This has now been released in the latest `moto-ext` release `2.2.3.8`. The `latest` LocalStack Docker image is being [built in our CI pipeline](https://app.circleci.com/pipelines/github/localstack/localstack/2327/workflows/4a729704-e3f1-4938-8115-0f4125bf78a0) right now and should become available in the next ~30 mins or so. Once done, can you then please pull the `latest` image and give it a try? Thanks!

**Comment by whummer** [comment]
@bodnarbm - quick update, the last build apparently failed, but rerunning the build worked. The changes are now available in the `latest` Docker image. Please let us know if the problem persists, or if there are any other issues. Thanks for your help!

**Comment by bodnarbm** [comment]
🎉 @whummer, I just tried the latest image and works great for our use case. Thanks for the quick response on this!
