### ISSUE TITLE
bug: Cognito Failed to create ResourceServer

### ISSUE THREAD

**Issue by lee-butn** [localstack/localstack#4832]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Failed to create resource server of cognito : ```Error creating Cognito Resource Server: ResourceNotFoundException: Cannot find resource: Unable to find handler for API method 'CreateResourceServer'```

### Expected Behavior

Able to create resource server

### How are you starting LocalStack?

Custom (please describe below)

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

 
pulumi up

### Environment

```markdown
- OS: 
- LocalStack:
```

**Comment by whummer** [comment]
Thanks for reporting @lee-butn . This should be fixed in the meantime - can you please pull the `latest` version of the `localstack/localstack` Docker image and give it another try? Please keep us posted how it goes - thanks for your help!
