### ISSUE TITLE
bug:  Service discovery return missing Namespace ID

### ISSUE THREAD

**Issue by lee-butn** [localstack/localstack#4833]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

lso getting error when create private DNS name in service discovery operation response missing Namespace ID 
namespaceID, ok := operationOutput.Operation.Targets[servicediscovery.OperationTargetTypeNamespace]

	if !ok {
		return fmt.Errorf("error creating Service Discovery Private DNS Namespace (%s): operation response missing Namespace ID", name)
	}

### How are you starting LocalStack?

Custom (please describe below)

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

terraform

### Environment

```markdown
- OS: 
- LocalStack:
```

**Comment by whummer** [comment]
Thanks for reporting @lee-butn . Can you please share a few snippets of your test code (i.e., which APIs are called, with which parameters)? This would greatly help us replicate this issue end-to-end.. Thanks!

Also, just to confirm - are you literally using this exact command to start up LocalStack? 
```
docker run localstack/localstack
```

Please note that this command is not supported, as it will not expose the required port mappings, volume mounts, etc. 

We recommend using the `localstack start` CLI command, or using a `docker-compose.yml` config file (see README for details). Please keep us posted how it goes.. Thanks!

**Comment by lee-butn** [comment]
This is my docker-compose.yaml
`version: '2.1'

services:
  localstack:
    image: "localstack/localstack:latest"
    ports:
      - 4566:4566
      - 4571:4571      
    environment:
      - SERVICES=${SERVICES- acm,apigateway,mediastore,route53,iam,efs,cloudwatch,ecr,ecs,sts,ec2,cognito,servicediscovery}
      - DEBUG=${DEBUG- }
      - DATA_DIR=/tmp/localstack/data
      - LOCALSTACK_API_KEY=2lANsXWiOl
    volumes:
      - "./.localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"`
 
I am use pulumi/terraform client .

`import * as pulumi from "@pulumi/pulumi";
import * as vpc from "./vpc";
import * as aws from "@pulumi/aws";

export const butnPrivateDnsNamespace = new aws.servicediscovery.PrivateDnsNamespace(`${pulumi.getStack()}-local`, {
    name : `${pulumi.getStack()}-local`,
    description: "private name space for butn-up discovery",
    vpc: vpc.defaultvpc.id,
    tags: {
        Environment: `${pulumi.getStack()}`,    
    }
});`

Error:
`I1103 11:23:35.717883   14340 snapshot.go:288] SnapshotManager: sameSnapshotMutation.End() eliding write
I1103 11:23:35.717883   14340 step_executor.go:327] StepExecutor worker(36): step same on urn:pulumi:localstack::butnup-infra::awsx:x:ec2:Vpc$awsx:x:ec2:Subnet$aws:ec2/route:Route::localstack-butnup-private-0-nat-0 retired
I1103 11:23:35.717883   14340 source_eval.go:1068] ResourceMonitor.RegisterResource operation finished: t=aws:ec2/route:Route, urn=urn:pulumi:localstack::butnup-infra::awsx:x:ec2:Vpc$awsx:x:ec2:Subnet$aws:ec2/route:Route::localstack-butnup-private-0-nat-0, #outs=19
I1103 11:23:35.717883   14340 rpc.go:74] Marshaling property for RPC[ResourceMonitor.RegisterResource(aws:ec2/route:Route,localstack-butnup-private-0-nat-0)]: __meta={{"e2bfb730-ecaa-11e6-8f88-34363bc7c4c0":{"create":120000000000,"delete":300000000000}}}
I1103 11:23:35.717883   14340 rpc.go:74] Marshaling property for RPC[ResourceMonitor.RegisterResource(aws:ec2/route:Route,localstack-butnup-private-0-nat-0)]: carrierGatewayId={}
I1103 11:23:35.717883   14340 rpc.go:74] Marshaling property for RPC[ResourceMonitor.RegisterResource(aws:ec2/route:Route,localstack-butnup-private-0-nat-0)]: destinationCidrBlock={0.0.0.0/0}
I1103 11:23:35.717883   14340 rpc.go:74] Marshaling property for RPC[ResourceMonitor.RegisterResource(aws:ec2/route:Route,localstack-butnup-private-0-nat-0)]: destinationIpv6CidrBlock={}
I1103 11:23:35.717883   14340 eventsink.go:59] RegisterResource RPC prepared: t=aws:ec2/natGateway:NatGateway, name=localstack-butnup-0
I1103 11:23:35.717883   14340 eventsink.go:62] eventSink::Debug(<{%reset%}>RegisterResource RPC prepared: t=aws:ec2/natGateway:NatGateway, name=localstack-butnup-0<{%reset%}>)
I1103 11:23:35.717883   14340 rpc.go:74] Marshaling property for RPC[ResourceMonitor.RegisterResource(aws:ec2/route:Route,localstack-butnup-private-0-nat-0)]: destinationPrefixListId={}
I1103 11:23:35.717883   14340 rpc.go:74] Marshaling property for RPC[ResourceMonitor.RegisterResource(aws:ec2/route:Route,localstack-butnup-private-0-nat-0)]: egressOnlyGatewayId={}
I1103 11:23:35.717883   14340 rpc.go:74] Marshaling property for RPC[ResourceMonitor.RegisterResource(aws:ec2/route:Route,localstack-butnup-private-0-nat-0)]: gatewayId={}
I1103 11:23:35.717883   14340 rpc.go:74] Marshaling property for RPC[ResourceMonitor.RegisterResource(aws:ec2/route:Route,localstack-butnup-private-0-nat-0)]: id={r-rtb-3fee904e1080289494}
I1103 11:23:35.717883   14340 rpc.go:74] Marshaling property for RPC[ResourceMonitor.RegisterResource(aws:ec2/route:Route,localstack-butnup-private-0-nat-0)]: instanceId={}
I1103 11:23:35.717883   14340 rpc.go:74] Marshaling property for RPC[ResourceMonitor.RegisterResource(aws:ec2/route:Route,localstack-butnup-private-0-nat-0)]: instanceOwnerId={}
I1103 11:23:35.717883   14340 rpc.go:74] Marshaling property for RPC[ResourceMonitor.RegisterResource(aws:ec2/route:Route,localstack-butnup-private-0-nat-0)]: localGatewayId={}
I1103 11:23:35.718536   14340 rpc.go:74] Marshaling property for RPC[ResourceMonitor.RegisterResource(aws:ec2/route:Route,localstack-butnup-private-0-nat-0)]: natGatewayId={nat-c2ea024939e1e340a}
I1103 11:23:35.718536   14340 rpc.go:74] Marshaling property for RPC[ResourceMonitor.RegisterResource(aws:ec2/route:Route,localstack-butnup-private-0-nat-0)]: networkInterfaceId={}
I1103 11:23:35.718536   14340 rpc.go:74] Marshaling property for RPC[ResourceMonitor.RegisterResource(aws:ec2/route:Route,localstack-butnup-private-0-nat-0)]: origin={CreateRoute}
I1103 11:23:35.718536   14340 rpc.go:74] Marshaling property for RPC[ResourceMonitor.RegisterResource(aws:ec2/route:Route,localstack-butnup-private-0-nat-0)]: routeTableId={rtb-3fee904e}
I1103 11:23:35.719638   14340 rpc.go:74] Marshaling property for RPC[ResourceMonitor.RegisterResource(aws:ec2/route:Route,localstack-butnup-private-0-nat-0)]: state={active}
I1103 11:23:35.719638   14340 rpc.go:74] Marshaling property for RPC[ResourceMonitor.RegisterResource(aws:ec2/route:Route,localstack-butnup-private-0-nat-0)]: transitGatewayId={}
I1103 11:23:35.719638   14340 rpc.go:74] Marshaling property for RPC[ResourceMonitor.RegisterResource(aws:ec2/route:Route,localstack-butnup-private-0-nat-0)]: vpcEndpointId={}
I1103 11:23:35.719638   14340 rpc.go:74] Marshaling property for RPC[ResourceMonitor.RegisterResource(aws:ec2/route:Route,localstack-butnup-private-0-nat-0)]: vpcPeeringConnectionId={}
I1103 11:23:35.724921   14340 eventsink.go:59] RegisterResource RPC finished: resource:https-access[aws:ec2/securityGroupRule:SecurityGroupRule]; err: null, resp: urn:pulumi:localstack::butnup-infra::awsx:x:ec2:SecurityGroup$awsx:x:ec2:IngressSecurityGroupRule$aws:ec2/securityGroupRule:SecurityGroupRule::https-access,sgrule-795109322,__meta,,,{"schema_version":"2"},cidrBlocks,,,,,,,,0.0.0.0/0,description,,,allow HTTPS access from anywhere,fromPort,,443,id,,,sgrule-795109322,protocol,,,tcp,securityGroupId,,,sg-4095cf4beb7102fab,self,,,,false,toPort,,443,type,,,ingress,,
I1103 11:23:35.725096   14340 eventsink.go:62] eventSink::Debug(<{%reset%}>RegisterResource RPC finished: resource:https-access[aws:ec2/securityGroupRule:SecurityGroupRule]; err: null, resp: urn:pulumi:localstack::butnup-infra::awsx:x:ec2:SecurityGroup$awsx:x:ec2:IngressSecurityGroupRule$aws:ec2/securityGroupRule:SecurityGroupRule::https-access,sgrule-795109322,__meta,,,{"schema_version":"2"},cidrBlocks,,,,,,,,0.0.0.0/0,description,,,allow HTTPS access from anywhere,fromPort,,443,id,,,sgrule-795109322,protocol,,,tcp,securityGroupId,,,sg-4095cf4beb7102fab,self,,,,false,toPort,,443,type,,,ingress,,<{%reset%}>)
I1103 11:23:35.741415   14340 eventsink.go:59] RegisterResource RPC finished: resource:localstack-butnup-0[aws:ec2/natGateway:NatGateway]; err: null, resp: urn:pulumi:localstack::butnup-infra::awsx:x:ec2:Vpc$awsx:x:ec2:NatGateway$aws:ec2/natGateway:NatGateway::localstack-butnup-0,nat-c2ea024939e1e340a,allocationId,,,eipalloc-6afc8bb5,connectivityType,,,public,id,,,nat-c2ea024939e1e340a,networkInterfaceId,,,eni-2fce77c9,privateIp,,,10.218.137.191,publicIp,,,127.30.47.201,subnetId,,,subnet-369fb067,tags,,,,,,tagsAll,,,,,,,
I1103 11:23:35.741415   14340 eventsink.go:62] eventSink::Debug(<{%reset%}>RegisterResource RPC finished: resource:localstack-butnup-0[aws:ec2/natGateway:NatGateway]; err: null, resp: urn:pulumi:localstack::butnup-infra::awsx:x:ec2:Vpc$awsx:x:ec2:NatGateway$aws:ec2/natGateway:NatGateway::localstack-butnup-0,nat-c2ea024939e1e340a,allocationId,,,eipalloc-6afc8bb5,connectivityType,,,public,id,,,nat-c2ea024939e1e340a,networkInterfaceId,,,eni-2fce77c9,privateIp,,,10.218.137.191,publicIp,,,127.30.47.201,subnetId,,,subnet-369fb067,tags,,,,,,tagsAll,,,,,,,<{%reset%}>)
I1103 11:23:35.751122   14340 eventsink.go:59] RegisterResource RPC prepared: t=aws:ec2/route:Route, name=localstack-butnup-private-0-nat-0
I1103 11:23:35.751122   14340 eventsink.go:62] eventSink::Debug(<{%reset%}>RegisterResource RPC prepared: t=aws:ec2/route:Route, name=localstack-butnup-private-0-nat-0<{%reset%}>)
I1103 11:23:35.755888   14340 eventsink.go:59] RegisterResource RPC finished: resource:localstack-butnup-private-0-nat-0[aws:ec2/route:Route]; err: null, resp: urn:pulumi:localstack::butnup-infra::awsx:x:ec2:Vpc$awsx:x:ec2:Subnet$aws:ec2/route:Route::localstack-butnup-private-0-nat-0,r-rtb-3fee904e1080289494,__meta,,,{"e2bfb730-ecaa-11e6-8f88-34363bc7c4c0":{"create":120000000000,"delete":300000000000}},carrierGatewayId,,,,destinationCidrBlock,,,0.0.0.0/0,destinationIpv6CidrBlock,,,,destinationPrefixListId,,,,egressOnlyGatewayId,,,,gatewayId,,,,id,,,r-rtb-3fee904e1080289494,instanceId,,,,instanceOwnerId,,,,localGatewayId,,,,natGatewayId,,,nat-c2ea024939e1e340a,networkInterfaceId,,,,origin,,,CreateRoute,routeTableId,,,rtb-3fee904e,state,,,active,transitGatewayId,,,,vpcEndpointId,,,,vpcPeeringConnectionId,,,,,
I1103 11:23:35.755888   14340 eventsink.go:62] eventSink::Debug(<{%reset%}>RegisterResource RPC finished: resource:localstack-butnup-private-0-nat-0[aws:ec2/route:Route]; err: null, resp: urn:pulumi:localstack::butnup-infra::awsx:x:ec2:Vpc$awsx:x:ec2:Subnet$aws:ec2/route:Route::localstack-butnup-private-0-nat-0,r-rtb-3fee904e1080289494,__meta,,,{"e2bfb730-ecaa-11e6-8f88-34363bc7c4c0":{"create":120000000000,"delete":300000000000}},carrierGatewayId,,,,destinationCidrBlock,,,0.0.0.0/0,destinationIpv6CidrBlock,,,,destinationPrefixListId,,,,egressOnlyGatewayId,,,,gatewayId,,,,id,,,r-rtb-3fee904e1080289494,instanceId,,,,instanceOwnerId,,,,localGatewayId,,,,natGatewayId,,,nat-c2ea024939e1e340a,networkInterfaceId,,,,origin,,,CreateRoute,routeTableId,,,rtb-3fee904e,state,,,active,transitGatewayId,,,,vpcEndpointId,,,,vpcPeeringConnectionId,,,,,<{%reset%}>)
I1103 11:23:36.082516   14340 provider_plugin.go:1531] provider received rpc error `Unknown`: `1 error occurred:
	* error creating Service Discovery Private DNS Namespace (localstack-local): operation response missing Namespace ID

`
I1103 11:23:36.082516   14340 provider_plugin.go:1534] rpc error kind `Unknown` may not be recoverable
I1103 11:23:36.082516   14340 provider_plugin.go:760] Provider[aws, 0xc001b5d080].Create(urn:pulumi:localstack::butnup-infra::aws:servicediscovery/privateDnsNamespace:PrivateDnsNamespace::localstack-local) failed: 1 error occurred:
	* error creating Service Discovery Private DNS Namespace (localstack-local): operation response missing Namespace ID

I1103 11:23:36.083127   14340 eventsink.go:86] eventSink::Error(<{%reset%}>1 error occurred:
	* error creating Service Discovery Private DNS Namespace (localstack-local): operation response missing Namespace ID

<{%reset%}>)
I1103 11:23:36.083317   14340 snapshot.go:316] SnapshotManager: createSnapshotMutation.End(..., false)
I1103 11:23:36.083392   14340 snapshot.go:536] SnapshotManager.markOperationComplete(urn:pulumi:localstack::butnup-infra::aws:servicediscovery/privateDnsNamespace:PrivateDnsNamespace::localstack-local)
I1103 11:23:36.367190   14340 step_executor.go:327] StepExecutor worker(28): step create on urn:pulumi:localstack::butnup-infra::aws:servicediscovery/privateDnsNamespace:PrivateDnsNamespace::localstack-local failed with an error: 1 error occurred:
	* error creating Service Discovery Private DNS Namespace (localstack-local): operation response missing Namespace ID`
