### ISSUE TITLE
question: Are there any plans to update/rename Elasticsearch parts to OpenSearch?

### ISSUE THREAD

**Issue by Dgame** [localstack/localstack#4834]
### Is there an existing issue for this?

- [X] I have searched the existing issues and read the documentation

### Question

AWS has changed / renamed its service to OpenSearch. Are there any plans to also use OpenSearch or to use the term OpenSearch instead of Elasticsearch?

**Comment by thrau** [comment]
Hi @Dgame, we don't have concrete plans yet, but it's definitely on my radar. I don't think we will rename existing elasticsearch code, but instead implement the opensearch API and use the official opensearch binary in the backend, which may take a while to get done.

**Comment by Dgame** [comment]
Would be nice to have. I've just updated my aws-cli and therefore have to use `opensearch` instead of `elasticsearch` which results in this:

> An error occurred (404) when calling the CreateDomain operation: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
><title>404 Not Found</title>
><h1>Not Found</h1>
><p>The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.</p>

Input was
```sh
aws --endpoint=http://localhost:4566 opensearch create-domain --domain-name Test
```

**Comment by thrau** [comment]
ok we can look into prioritizing this. but `aws es` should still be available, right? see the docs: https://docs.localstack.cloud/aws/elasticsearch/

**Comment by Dgame** [comment]
> ok we can look into prioritizing this. but `aws es` should still be available, right? see the docs: https://docs.localstack.cloud/aws/elasticsearch/

Yes, that still works.

**Comment by Dgame** [comment]
As mentioned [here](https://github.com/localstack/localstack/issues/5047#issuecomment-986915350): since we have an explicit denial message for using OpenSearch, maybe it can be prioritised. 😄 I would really appreciate it. 👍

**Comment by thrau** [comment]
We've started working on an implementation of OpenSearch in #5169

**Comment by silv-io** [comment]
We're happy to announce that LocalStack now supports OpenSearch! 🚀
For detailed information on how to use it refer to the [LocalStack documentation on OpenSearch](https://docs.localstack.cloud/aws/opensearch/).

Feel free to let us know about any difficulties or problems which occur while using the new feature by creating new issues. (using the new tag "aws:opensearch")

**Comment by Dgame** [comment]
@thrau @silv-io 
Could it be that the Firehose API has not been updated? I think the related `AmazonopensearchserviceDestinationConfiguration` (https://docs.aws.amazon.com/cli/latest/reference/firehose/create-delivery-stream.html) was not added [here](https://github.com/localstack/localstack/blob/53b5c7788bf35b1882b6cb1949e17d27e198cf61/localstack/services/cloudformation/models/kinesisfirehose.py#L23-L27). After some troubleshooting I found out that `ElasticsearchDestinationConfiguration` works, but not `AmazonopensearchserviceDestinationConfiguration`.

**Comment by thrau** [comment]
Hi Randy @Dgame. The firehose integration is still work in progress. There are a few details to iron out and we will in fact start implementing it this week. Can't give you an exact ETA, but looking into having it ready by end of next week.
