### ISSUE TITLE
question: How to run LocalStack without internet connection?

### ISSUE THREAD

**Issue by phildunphytoo** [localstack/localstack#4840]
### Is there an existing issue for this?

- [X] I have searched the existing issues and read the documentation

### Question

I need to be able to run LocalStack (simple, not pro) without internet connection. 
Is there a way I can do it?

I'm running it using Docker and receive this output:
```
Waiting for all LocalStack services to be ready
2021-11-02 15:31:59,405 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2021-11-02 15:31:59,407 INFO supervisord started with pid 14
2021-11-02 15:32:00,411 INFO spawned: 'infra' with pid 20
(. .venv/bin/activate; exec bin/localstack start --host --no-banner)
2021-11-02 15:32:01,435 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Waiting for all LocalStack services to be ready

LocalStack version: 0.12.19.1
LocalStack build date: 2021-11-01
LocalStack build git hash: c49f2b0a

Starting edge router (https port 4566)...
2021-11-02 15:32:11,987 INFO exited: infra (exit status 2; not expected)
2021-11-02 15:32:11,988 INFO spawned: 'infra' with pid 144
Error starting infrastructure: gave up waiting for edge server on 0.0.0.0:4566 Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/infra.py", line 396, in start_infra
    thread = do_start_infra(asynchronous, apis, is_in_docker)
  File "/opt/code/localstack/localstack/services/infra.py", line 505, in do_start_infra
    thread = start_runtime_components()
  File "/opt/code/localstack/localstack/utils/bootstrap.py", line 91, in wrapped
    return f(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/infra.py", line 498, in start_runtime_components
    f"gave up waiting for edge server on {config.EDGE_BIND_HOST}:{config.EDGE_PORT}"
TimeoutError: gave up waiting for edge server on 0.0.0.0:4566

(. .venv/bin/activate; exec bin/localstack start --host --no-banner)
2021-11-02T15:32:11:INFO:bootstrap.py: Execution of "start_runtime_components" took 5033.95ms
Traceback (most recent call last):
  File "bin/localstack", line 23, in <module>
    main()
  File "bin/localstack", line 19, in main
    main.main()
  File "/opt/code/localstack/localstack/cli/main.py", line 6, in main
    cli()
  File "/opt/code/localstack/localstack/cli/plugin.py", line 15, in __call__
    self.group(*args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/opt/code/localstack/localstack/cli/localstack.py", line 111, in cmd_start
    bootstrap.start_infra_locally()
  File "/opt/code/localstack/localstack/utils/bootstrap.py", line 405, in start_infra_locally
    return infra.start_infra()
  File "/opt/code/localstack/localstack/services/infra.py", line 410, in start_infra
    raise e
  File "/opt/code/localstack/localstack/services/infra.py", line 396, in start_infra
    thread = do_start_infra(asynchronous, apis, is_in_docker)
  File "/opt/code/localstack/localstack/services/infra.py", line 505, in do_start_infra
    thread = start_runtime_components()
  File "/opt/code/localstack/localstack/utils/bootstrap.py", line 91, in wrapped
    return f(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/infra.py", line 498, in start_runtime_components
    f"gave up waiting for edge server on {config.EDGE_BIND_HOST}:{config.EDGE_PORT}"
TimeoutError: gave up waiting for edge server on 0.0.0.0:4566
make: *** [Makefile:233: infra] Error 1
^C2021-11-02 15:32:12,993 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Waiting for all LocalStack services to be ready
```

**Comment by phildunphytoo** [comment]
thanks for the response! 
I've tried the same command as yours and still get the same error..

**Comment by phildunphytoo** [comment]
I'm running on RHEL8 and it doesn't work.
I got it to work using Docker on Windows on another machine I have.

**Comment by mgagliardo** [comment]
It would be cool if you could post the output from the command as well as add `DEBUG=1` as an environment variable. 
Another thing would be to check (`docker inspect $CONTAINER_ID`)  the docker network config and see why there's an issue with that.
Last one, would be checking if you have another service running on the same port/s, you can check this out with netstat or ss, for example `netstat -tunlp | grep 4566` (or any other port you are using for this).

**Comment by phildunphytoo** [comment]
Docker inspect seems OK. even without binding the ports to the host, the image fails to run with the same error message.. it seems something inside the docker image is bothering it..

**Comment by mgagliardo** [comment]
What localstack container image are you using? I have ran the test using the `latest` image.

**Comment by phildunphytoo** [comment]
I've tried with the full and normal one. Both latest. 
normal image ID: b61e4bbe0e8a, created in the last 2 days according to docker

**Comment by mgagliardo** [comment]
I have now tested this with both the latest and 0.12.19 images, both on a mac and linux (ubuntu 20.04) everything looking good on my side.
I know it might sound silly but have you tried restarting your machine/s and testing again?

**Comment by phildunphytoo** [comment]
Got it working with version 0.12.19! thanks a lot!!!

**Comment by mgagliardo** [comment]
Good to know mate. Cheers!

**Comment by anhoxa** [comment]
I've been having similar error as OP with 0.12.20; it only started yesretday.

**Comment by anhoxa** [comment]
It was mentioned above that 0.12.19 works and my version is 0.12.20. Changed the docker-compose.yml to use 0.12.19 and it fails once, but eventually restarts correctly without looping.

**Comment by kigawas** [comment]
It connects to `analytics.localstack.cloud` when starting, if there's no network connection it'll fail.

**Comment by kigawas** [comment]
Okay I see, another network connection is 
```
CFN_RESPONSE_MODULE_URL = (
    "https://raw.githubusercontent.com/LukeMizuhashi/cfn-response/master/index.js"
)
```

**Comment by anhoxa** [comment]
Well that is unsettling.  We're using `localstack` in a specialised test network that is cut off from the Internet.  Newer versions having exterior dependencies at runtime will be a problem.

**Comment by whummer** [comment]
Hi @anhoxa , please feel free to reach out to us at info@localstack.cloud (or in the Slack channel). We may be able to provide a custom fully offline version of the image that matches your requirements. (Not as part of the open source / community image, though, as here we focus on having a slim image, with lazy loading of some dependencies at runtime).

**Comment by anhoxa** [comment]
This morning I tried the most recent build with `DISABLE_EVENTS=1` set in the configuration and it appears to be working now, no restart loop.  If the restart loop issue occurs again I'll reach out.  Thank you.

FYI
```
localstack_1  | LocalStack version: 0.13.0.10
localstack_1  | LocalStack build date: 2021-12-03
localstack_1  | LocalStack build git hash: 47e6b57f
```

**Comment by anhoxa** [comment]
OK.  This is no longer working.  Sometimes it starts up other times without issue and now no; its looking like timing related thing.
```
localstack_1  | LocalStack version: 0.13.0.10
localstack_1  | LocalStack build date: 2021-12-03
localstack_1  | LocalStack build git hash: 5d55f84e
```
Was working fine in Windows hosted, Ubuntu guest VM within a docker container, while my colleague on a Mac with same VM setup, same localstack version/hash had the restart loop.  Now today, without any VM changes the same occurs for me (Windows).   Keeps looping.  Is this an offline vs online issue?  Why does it work sometimes?
```
localstack_1  | Starting edge router (https port 4566)...
localstack_1  | 2021-12-08T17:02:31.198:INFO:bootstrap.py: Execution of "prepare_environment" took 646.79ms
localstack_1  | Waiting for all LocalStack services to be ready
localstack_1  | Waiting for all LocalStack services to be ready
localstack_1  | 2021-12-08 17:02:43,455 INFO exited: infra (exit status 2; not expected)
localstack_1  | 2021-12-08 17:02:43,457 INFO spawned: 'infra' with pid 557
localstack_1  | Error starting infrastructure: gave up waiting for edge server on 0.0.0.0:4566 Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/localstack/services/infra.py", line 397, in start_infra
localstack_1  |     thread = do_start_infra(asynchronous, apis, is_in_docker)
localstack_1  |   File "/opt/code/localstack/localstack/services/infra.py", line 512, in do_start_infra
localstack_1  |     thread = start_runtime_components()
localstack_1  |   File "/opt/code/localstack/localstack/utils/bootstrap.py", line 78, in wrapped
localstack_1  |     return f(*args, **kwargs)
localstack_1  |   File "/opt/code/localstack/localstack/services/infra.py", line 504, in start_runtime_components
localstack_1  |     raise TimeoutError(
localstack_1  | TimeoutError: gave up waiting for edge server on 0.0.0.0:4566
localstack_1  |
localstack_1  | . .venv/bin/activate; LOCALSTACK_INFRA_PROCESS=1 exec bin/localstack start --host --no-banner
localstack_1  | 2021-12-08T17:02:43.285:INFO:bootstrap.py: Execution of "start_runtime_components" took 12082.25ms
localstack_1  | Traceback (most recent call last):
localstack_1  |   File "bin/localstack", line 23, in <module>
localstack_1  |     main()
localstack_1  |   File "bin/localstack", line 19, in main
localstack_1  |     main.main()
localstack_1  |   File "/opt/code/localstack/localstack/cli/main.py", line 6, in main
localstack_1  |     cli()
localstack_1  |   File "/opt/code/localstack/localstack/cli/plugin.py", line 15, in __call__
localstack_1  |     self.group(*args, **kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
localstack_1  |     return self.main(*args, **kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/click/core.py", line 1053, in main
localstack_1  |     rv = self.invoke(ctx)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
localstack_1  |     return _process_result(sub_ctx.command.invoke(sub_ctx))
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
localstack_1  |     return ctx.invoke(self.callback, **ctx.params)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/click/core.py", line 754, in invoke
localstack_1  |     return __callback(*args, **kwargs)
localstack_1  |   File "/opt/code/localstack/localstack/cli/localstack.py", line 123, in cmd_start
localstack_1  |     bootstrap.start_infra_locally()
localstack_1  |   File "/opt/code/localstack/localstack/utils/bootstrap.py", line 299, in start_infra_locally
localstack_1  |     return infra.start_infra()
localstack_1  |   File "/opt/code/localstack/localstack/services/infra.py", line 411, in start_infra
localstack_1  |     raise e
localstack_1  |   File "/opt/code/localstack/localstack/services/infra.py", line 397, in start_infra
localstack_1  |     thread = do_start_infra(asynchronous, apis, is_in_docker)
localstack_1  |   File "/opt/code/localstack/localstack/services/infra.py", line 512, in do_start_infra
localstack_1  |     thread = start_runtime_components()
localstack_1  |   File "/opt/code/localstack/localstack/utils/bootstrap.py", line 78, in wrapped
localstack_1  |     return f(*args, **kwargs)
localstack_1  |   File "/opt/code/localstack/localstack/services/infra.py", line 504, in start_runtime_components
localstack_1  |     raise TimeoutError(
localstack_1  | TimeoutError: gave up waiting for edge server on 0.0.0.0:4566
localstack_1  | make: *** [Makefile:256: infra] Error 1
localstack_1  | 2021-12-08 17:02:44,497 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (start
secs)
```

**Comment by kigawas** [comment]
> OK. This is no longer working. Sometimes it starts up without issue and other times not; its looking like timing related thing.
> 
> ```
> localstack_1  | LocalStack version: 0.13.0.10
> localstack_1  | LocalStack build date: 2021-12-03
> localstack_1  | LocalStack build git hash: 5d55f84e
> ```
> 
> Was working fine in Windows hosted, Ubuntu guest VM within a docker container, while my colleague on a Mac with same VM setup, same localstack version/hash had the restart loop. Now today, without any VM changes the same occurs for me (Windows). Keeps looping. Is this an offline vs online issue? Why does it work sometimes?
> 
> ```
> localstack_1  | Starting edge router (https port 4566)...
> localstack_1  | 2021-12-08T17:02:31.198:INFO:bootstrap.py: Execution of "prepare_environment" took 646.79ms
> localstack_1  | Waiting for all LocalStack services to be ready
> localstack_1  | Waiting for all LocalStack services to be ready
> localstack_1  | 2021-12-08 17:02:43,455 INFO exited: infra (exit status 2; not expected)
> localstack_1  | 2021-12-08 17:02:43,457 INFO spawned: 'infra' with pid 557
> localstack_1  | Error starting infrastructure: gave up waiting for edge server on 0.0.0.0:4566 Traceback (most recent call last):
> localstack_1  |   File "/opt/code/localstack/localstack/services/infra.py", line 397, in start_infra
> localstack_1  |     thread = do_start_infra(asynchronous, apis, is_in_docker)
> localstack_1  |   File "/opt/code/localstack/localstack/services/infra.py", line 512, in do_start_infra
> localstack_1  |     thread = start_runtime_components()
> localstack_1  |   File "/opt/code/localstack/localstack/utils/bootstrap.py", line 78, in wrapped
> localstack_1  |     return f(*args, **kwargs)
> localstack_1  |   File "/opt/code/localstack/localstack/services/infra.py", line 504, in start_runtime_components
> localstack_1  |     raise TimeoutError(
> localstack_1  | TimeoutError: gave up waiting for edge server on 0.0.0.0:4566
> localstack_1  |
> localstack_1  | . .venv/bin/activate; LOCALSTACK_INFRA_PROCESS=1 exec bin/localstack start --host --no-banner
> localstack_1  | 2021-12-08T17:02:43.285:INFO:bootstrap.py: Execution of "start_runtime_components" took 12082.25ms
> localstack_1  | Traceback (most recent call last):
> localstack_1  |   File "bin/localstack", line 23, in <module>
> localstack_1  |     main()
> localstack_1  |   File "bin/localstack", line 19, in main
> localstack_1  |     main.main()
> localstack_1  |   File "/opt/code/localstack/localstack/cli/main.py", line 6, in main
> localstack_1  |     cli()
> localstack_1  |   File "/opt/code/localstack/localstack/cli/plugin.py", line 15, in __call__
> localstack_1  |     self.group(*args, **kwargs)
> localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
> localstack_1  |     return self.main(*args, **kwargs)
> localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/click/core.py", line 1053, in main
> localstack_1  |     rv = self.invoke(ctx)
> localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
> localstack_1  |     return _process_result(sub_ctx.command.invoke(sub_ctx))
> localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
> localstack_1  |     return ctx.invoke(self.callback, **ctx.params)
> localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/click/core.py", line 754, in invoke
> localstack_1  |     return __callback(*args, **kwargs)
> localstack_1  |   File "/opt/code/localstack/localstack/cli/localstack.py", line 123, in cmd_start
> localstack_1  |     bootstrap.start_infra_locally()
> localstack_1  |   File "/opt/code/localstack/localstack/utils/bootstrap.py", line 299, in start_infra_locally
> localstack_1  |     return infra.start_infra()
> localstack_1  |   File "/opt/code/localstack/localstack/services/infra.py", line 411, in start_infra
> localstack_1  |     raise e
> localstack_1  |   File "/opt/code/localstack/localstack/services/infra.py", line 397, in start_infra
> localstack_1  |     thread = do_start_infra(asynchronous, apis, is_in_docker)
> localstack_1  |   File "/opt/code/localstack/localstack/services/infra.py", line 512, in do_start_infra
> localstack_1  |     thread = start_runtime_components()
> localstack_1  |   File "/opt/code/localstack/localstack/utils/bootstrap.py", line 78, in wrapped
> localstack_1  |     return f(*args, **kwargs)
> localstack_1  |   File "/opt/code/localstack/localstack/services/infra.py", line 504, in start_runtime_components
> localstack_1  |     raise TimeoutError(
> localstack_1  | TimeoutError: gave up waiting for edge server on 0.0.0.0:4566
> localstack_1  | make: *** [Makefile:256: infra] Error 1
> localstack_1  | 2021-12-08 17:02:44,497 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (start
> secs)
> ```

https://github.com/localstack/localstack/issues/4840#issuecomment-985330439

Probably cache

**Comment by phildunphytoo** [comment]
Tested latest version 0.14.0 and it's not working without internet connection (also with DISABLE_EVENTS=1)
Any thoughts?
Thanks!

**Comment by NickKelly1** [comment]
I've tried `latest`, `0.14.0`, `1.13.3`, `1.13.3-amd64`, and get the same error

**Comment by anhoxa** [comment]
This ticket should be re-opened since it is in completely inline with the project mission statement show in a big .svg at the top of the repository:

> A fully functional local cloud stack. Develop and test your cloud and serverless apps offline!

**Comment by congon4tor** [comment]
I'm facing the same issue running localstack with no internet is pretty much a requirement for my use case... has anyone found a solution?

**Comment by nipuna-perera** [comment]
facing the same.

**Comment by congon4tor** [comment]
I managed to get this working with no internet access after some help on the localstack slack. I added the `SKIP_SSL_CERT_DOWNLOAD=1` environment variable. Hopefully that helps you out too

**Comment by marcoswca** [comment]
> I managed to get this working with no internet access after some help on the localstack slack. I added the `SKIP_SSL_CERT_DOWNLOAD=1` environment variable. Hopefully that helps you out too

It works for me, I was facing issues with version 0.14, thanks.

**Comment by bkoprivica** [comment]
> > I managed to get this working with no internet access after some help on the localstack slack. I added the `SKIP_SSL_CERT_DOWNLOAD=1` environment variable. Hopefully that helps you out too
> 
> It works for me, I was facing issues with version 0.14, thanks

Still the same bug persists in the version 1.1.1.dev 

localstack-test | WARNING
localstack-test | ============================================================================
localstack-test |   It seems you are mounting the LocalStack volume into /tmp/localstack.
localstack-test |   This will break the LocalStack container! Please update your volume mount
localstack-test |   destination to /var/lib/localstack. In the meantime, we have set
localstack-test |   LEGACY_DIRECTORIES=1, to make LocalStack behave as in <1.0.0, and which 
localstack-test |   should prevent any serious issues, but will be removed soon!
localstack-test |   You can suppress this warning by setting LEGACY_DIRECTORIES=1
localstack-test | 
localstack-test |   See: https://github.com/localstack/localstack/issues/6398
localstack-test | ============================================================================
localstack-test | 
localstack-test | Waiting for all LocalStack services to be ready
localstack-test | 2022-09-12 21:01:14,554 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
localstack-test | 2022-09-12 21:01:14,557 INFO supervisord started with pid 16
localstack-test | 2022-09-12 21:01:15,561 INFO spawned: 'infra' with pid 21
localstack-test | 2022-09-12 21:01:16,564 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
localstack-test | 
localstack-test | LocalStack version: 1.1.1.dev
localstack-test | LocalStack Docker container id: de36fdbbe4b3
localstack-test | LocalStack build date: 2022-09-12
localstack-test | LocalStack build git hash: f42316e0
localstack-test | 
localstack-test | Waiting for all LocalStack services to be ready
localstack-test | Waiting for all LocalStack services to be ready
localstack-test | 2022-09-12T21:01:31.746  INFO --- [  MainThread] localstack.utils.bootstrap : Execution of "start_runtime_components" took 14805.28ms
localstack-test | Error starting infrastructure: gave up waiting for edge server on 0.0.0.0:4566 Traceback (most recent call last):
localstack-test |   File "/opt/code/localstack/localstack/services/infra.py", line 420, in start_infra
localstack-test |     thread = do_start_infra(asynchronous, apis, is_in_docker)
localstack-test |   File "/opt/code/localstack/localstack/services/infra.py", line 517, in do_start_infra
localstack-test |     thread = start_runtime_components()
localstack-test |   File "/opt/code/localstack/localstack/utils/bootstrap.py", line 77, in wrapped
localstack-test |     return f(*args, **kwargs)
localstack-test |   File "/opt/code/localstack/localstack/services/infra.py", line 509, in start_runtime_components
localstack-test |     raise TimeoutError(
localstack-test | TimeoutError: gave up waiting for edge server on 0.0.0.0:4566
localstack-test | 2022-09-12 21:10:52,598 INFO exited: infra (exit status 1; not expected)
localstack-test | Waiting for all LocalStack services to be ready
localstack-test | 2022-09-12 21:10:53,601 INFO spawned: 'infra' with pid 1113
localstack-test | 2022-09-12 21:10:54,603 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
localstack-test | 
localstack-test | LocalStack version: 1.1.1.dev
localstack-test | LocalStack Docker container id: de36fdbbe4b3
localstack-test | LocalStack build date: 2022-09-12
localstack-test | LocalStack build git hash: f42316e0
localstack-test | 
localstack-test | Waiting for all LocalStack services to be ready
...

**Comment by weickmanna** [comment]
Experiencing same problem with 1.1.
Startup without internet connection is way slower but will  succeed before timing out when I add following envs:

- SKIP_SSL_CERT_DOWNLOAD=1
- SKIP_INFRA_DOWNLOADS=1
- DISABLE_EVENTS=1

**Comment by phildunphytoo** [comment]
I'm unable to run version 3.0 without internet.. I only need lambda, sqs, s3, step function and events.. Is there a cookbook or something? thanks!
