### ISSUE TITLE
bug: docker-entrypoint-initaws.d/ init script not properly executing

### ISSUE THREAD

**Issue by nickolasclarke** [localstack/localstack#4852]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have a simple bash script to initialize an s3 bucket, found at `/docker-entrypoint-initaws.d/localstack_s3.sh`

```bash
BUCKET=my_bucket

awslocal s3api head-bucket --bucket $BUCKET &>/dev/null
if [ $? -eq 0 ]; then
  echo "localstack S3 bucket $BUCKET already exists"
else
  awslocal s3 mb s3://$BUCKET
  echo "localstack S3 bucket created"
fi
```
when I stand up localstack with ` docker-compose -f docker-compose/localstack.yaml` , I get the following in the logs: 

```
/usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initaws.d/localstack_s3.sh
```
without any further output. I can verify this did not run properly by executing `awslocal s3 ls` from the container, which returns nothing. However, this script executes fine manually. 

```
docker exec -it localstack bash /docker-entrypoint-initaws.d/localstack_s3.sh
make_bucket: my_bucket
localstack S3 bucket created
```
followed by:
```
docker exec -it localstack awslocal s3 ls
my_bucket
```

### Expected Behavior

the script at `/docker-entrypoint-initaws.d/localstack_s3.sh` should execute properly on and initialize an s3 bucket or skip, if has already been created. 

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal s3 mb s3://mybucket

### Environment

```markdown
- OS: MacOS 11.5.2
- LocalStack: 0.12.12 initially, also tested with localstack/localstack:latest
```

**Comment by nickolasclarke** [comment]
on further testing, I do get the output from `echo "localstack S3 bucket $BUCKET already exists"` at startup in the localstack docker logs  if I've already run the script. Perhaps there is an issue with my bash script, or at least how its being interpreted?

**Comment by whummer** [comment]
Thanks for reporting @nickolasclarke . Can you please share your LocalStack startup configuration - are you using the persistence feature by setting `DATA_DIR`, by any chance? Thanks

**Comment by nickolasclarke** [comment]
Yes I do have that set.


```docker
version: "3.3"                                                                                                                                  
 
services: 
 localstack:
   container_name: localstack
   ports:
     - 4566:4566 # All services
   environment:
     - SERVICES=kinesis,dynamodb,secretsmanager,ses,s3
     - DEBUG=true
     - DATA_DIR=/tmp/localstack/data
     - KINESIS_ERROR_PROBABILITY=.001
     - DYNAMODB_ERROR_PROBABILITY=.001
     - DOCKER_HOST=unix:///var/run/docker.sock
```

**Comment by nickolasclarke** [comment]
@whummer any thoughts here?

**Comment by d1820** [comment]
I am having a similar issue with startup scripts executing. In my case I get an error "/docker-entrypoint-initaws.d/localstack.sh: line 1: ﻿#!bin/bash: No such file or directory" if i run the script manually it all works fine. so not sure what i may be missing in this script its pretty standard, and I have even removed everything but just an echo command and still get the error. Anyone seen this as well?

**Comment by nickolasclarke** [comment]
@whummer ping again

**Comment by nickolasclarke** [comment]
@whummer or anyone else, any updates here?

**Comment by nickolasclarke** [comment]
@whummer 🏓

**Comment by nickolasclarke** [comment]
@d1820 I also was able to remove the BOM encoding and this appears to now work.

**Comment by igortche123** [comment]
I have the same problem. But what I see - the scripts mapped into the `/docker-entrypoint-initaws.d/` folder have no exec flag although the source scripts have. May be it's the problem?

**Comment by HarshCasper** [comment]
Hi — We have recently released [Initialization Hooks](https://docs.localstack.cloud/references/init-hooks/) with LocalStack to customize or initialize your LocalStack instance. Can you please give it a run with our new setup and report a new issue if you're still experiencing this issue on a [supported version](https://hub.docker.com/r/localstack/localstack/tags) of LocalStack? 

I will be closing this issue since it's an outdated setup right now. Thank you in advance. Your assistance is appreciated.
