### ISSUE TITLE
How much memory need be assigned to localstack docker stack?

### ISSUE THREAD

**Issue by ozbillwang** [localstack/localstack#486]
How much memory need be assigned to localstack docker stack?

I run `localstack` in a vagrant instance via virtualbox, and already assign 1GB memory on it.

```
$ docker-compose up -d
$ docker ps
-bash: fork: Cannot allocate memory
-bash: wait_for: No record of process 3000
```

### Updates
After adjust the memory to 3GB,  the problem is gone.

**Comment by whummer** [comment]
LocalStack should work fine with ~750MB, 1GB should definitely be enough. Elasticsearch is the most memory "hungry" process with up to 500MB (default configuration), so if you want to use less memory, you can configure the `SERVICES` environment variable to only spin up certain services.

However, to me, the error message above looks more like the host machine is running out of memory, not the Docker container? The fact that `Cannot allocate memory` occurs when you run `docker ps` could be a sign that the entire host operating system (Mac OS) is out of memory. But then the weird thing is that it apparently works if you assign 3GB. Did you by any chance restart your machine or terminate any other programs on the machine when switching from 1GB to 3GB?

**Comment by ozbillwang** [comment]
Thanks, @whummer. The vagrant instance has several docker running on it (just for testing).

Even stop all the applications I can, I still get the same issue at 1GB memory. When start the localstack docker container, the system is slow down immediately, fan is active and running on my mac.

**Comment by whummer** [comment]
For the latest version of LocalStack - make sure to allocate at least 2GB if you start all services, which is the default. You can also reduce the memory footprint by customizing the `SERVICES` configuration variable (see README)
