### ISSUE TITLE
bug: API Gateway with Rest API doesn't support custom domains

### ISSUE THREAD

**Issue by mLupine** [localstack/localstack#4860]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When a custom domain is configured for the API Gateway and base path mapping is created for a Rest API, pointing that domain to a LocalStack instance does not make it trigger appropriate API Gateway backend.

### Expected Behavior

A Rest API is triggered and its response is successfully returned.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker-compose & SLS plugin for deployments

#### How to reproduce

- point host port 443 to internal 4566 in docker-compose.yml
- point a domain (`api.example.com`) to 127.0.0.1 using `/etc/hosts` (`127.0.0.1 api.example.com`)
- start a LocalStack instance and create an API Gateway using Terraform (+ Route53 records, ACM certificates, etc. for `api.example.com`)
- deploy Lambdas using Serverless and attach them to the previously created API Gateway
- create a base path mapping using `awslocal apigateway create-base-path-mapping --domain-name api.example.com --rest-api-id "API_GW_ID" --stage local`
- when visiting `https://api.example.com/some_api_endpoint`, an empty json object is returned and the following exception is thrown: 
```
  File "/opt/code/localstack/localstack/services/apigateway/apigateway_listener.py", line 442, in set_api_id_stage_invocation_path
    raise Exception(f"Unable to extract API Gateway details from request: {path} {headers}")
```

### Environment

```markdown
- OS: doesn't matter
- LocalStack: latest Docker, Git commit `174faf67720451c00ab879897a12097b72b4add2`
```

### Anything else?

I've verified that `set_api_id_stage_invocation_path` does not return in [line 416](https://github.com/localstack/localstack/blob/master/localstack/services/apigateway/apigateway_listener.py#L416) because `stage` is missing from `invocation_context`.

I've confirmed that hardcoding the value of `stage` makes it works properly, so I guess fixing it won't be difficult. I'm not familiar the code of LocalStack enough to know where to extract the value of `stage` from, though, so I'm creating this issue instead of a PR.

We're using the **PRO** version of LocalStack, if that makes any difference.

**Comment by mLupine** [comment]
The workaround I described (hardcoding the value of `stage`) does not work anymore, probably due to some changes introduced [here](https://github.com/localstack/localstack/commit/19011ca0873b800c57da05f7cb2e42ffb5e0280d). Visiting `https://api.example.com/test_endpoint/test` returns the following:
```xml
<Error>
<Code>NoSuchBucket</Code>
<Message>The specified bucket does not exist</Message>
<BucketName>test_endpoint</BucketName>
<RequestID>7a62c49f-347e-4fc4-9331-6e8eEXAMPLE</RequestID>
</Error>
```

**Comment by whummer** [comment]
Thanks for reporting @mLupine. This should be (hopefully) fixed in the meantime - can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists.. Thanks for your help!

**Comment by mLupine** [comment]
Hi @whummer, I'm not able to test it on the `latest` image, as it seems to not work correctly at the moment. I get a ton of errors similar to this during Serverless deployment:
```
2021-11-10T10:54:24:WARNING:localstack.utils.cloudformation.template_deployer: Unexpected error retrieving details for resource type AWS::S3::Bucket: Exception: invalid or missing encoding declaration for '/opt/code/localstack/.venv/lib/python3.7/site-packages/localstack_ext/services/cloudformation/cloudformation_extended.py.enc' - {'BucketEncryption': {'ServerSideEncryptionConfiguration': [{'ServerSideEncryptionByDefault': {'SSEAlgorithm': 'AES256'}}]}, 'BucketName': 'redacted-local-serverlessdeploymentbuck-0f04e42e'} - status: None
```

**Comment by whummer** [comment]
Hi @mLupine , thanks for bringing this to our attention. This issue should be resolved in the meantime. Can you please give it another try after pulling the `latest` Docker image now? Thanks for your help!

**Comment by mLupine** [comment]
Indeed, works great now (this actually also fixed another bug that we had to work around). Thanks!
