### ISSUE TITLE
ECR deployment not working on latest version

### ISSUE THREAD

**Issue by estebane-frb** [localstack/localstack#4863]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Trying the following service:

environment:
      - SERVICES=ecr

I am now getting the following error: "POST http://localhost:4566/: no provider exists for service ecr Traceback" when trying to run a simple ECR deployment.

I am using the latest version via the published docker-compose.yml in this repo.

### Expected Behavior

ECR repo created. 

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

docker-compose up

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

terraform apply

here is my terraform:
provider "aws" {
  region                      = "us-east-1"
  access_key                  = "mock"
  secret_key                  = "mock"
  skip_credentials_validation = true
  skip_metadata_api_check     = true
  skip_requesting_account_id  = true

  endpoints {
    ecr            = "http://localhost:4566"
  }
}

resource "aws_ecr_repository" "example" {
  name                 = "example-repo"
  image_tag_mutability = "MUTABLE"

  image_scanning_configuration {
    scan_on_push = false
  }
}

### Environment

```markdown
- OS: 
- LocalStack:latest
```

**Comment by whummer** [comment]
Thanks for reporting @estebane-frb . Please note that ECR is a service currently only available in LocalStack Pro - just to confirm, do you have the API key configured in your instance? If that's the case, then kindly please get in touch with us directly (email/Slack) - this might be an issue with your API key (happy to look into it in more detail). Thanks for your help!

**Comment by estebane-frb** [comment]
Thanks for your prompt reply, I hadn't realized this required Pro level. In that case we can close this ticket. Thanks for the information!
