### ISSUE TITLE
Mechanism for specifying the version of moto when using localstack?

### ISSUE THREAD

**Issue by kbalk** [localstack/localstack#4879]
### Is there an existing issue for this?

- [X] I have searched the existing issues and read the documentation

### Question

moto is released more often than LocalStack and if you use both LocalStack and moto (through `initaws.d/start.sh`), that means waiting something like a month versus a week to see a new moto feature.

I don't know how you're pulling in moto for your docker image, but would it be possible to have a means of pulling in the latest version of moto when the LocalStack docker image is used, versus the version of moto that was available at the time the docker image was created?

Maybe this is something that could/should be resolved outside of LocalStack?

**Comment by mgagliardo** [comment]
Hello @kbalk, I might not be able to provide a proper solution for this but maybe @thrau and @whummer can do a better job than I do but I see two options here:

1. Something you can do for example is use the make method `make docker-mount-run` described [here](https://github.com/localstack/localstack/blob/master/Makefile#L127), which basically installs some necessary files and specifies a `MOTO_DIR`. As a workaround to this you can modify the file and use your own `MOTO_DIR`.

2. One other option would be to install the necessary libs (using `make install`) and modify the [requirements.txt](https://github.com/localstack/localstack/blob/master/requirements.txt#L53) file to match your needs.

3. Very very hacky, but you can do the latter and swim into `.venv/libs/python/........../moto` and download/copy/checkout the one you need and then use `make docker-mount-run` to your own.

Let me know if this helps you, sorry I could not provide a better, less-hacky solution here.

**Comment by kbalk** [comment]
I had thought about #3, but much better to know #1 and #2.  Thank you.

**Comment by mgagliardo** [comment]
I'll close this considering the issue as resolved but as I mentioned maybe the team can provide a better update than I did. Cheers!
