### ISSUE TITLE
Requirements are inconsistent

### ISSUE THREAD

**Issue by mikedal** [localstack/localstack#488]
In recent versions of localstack, the pinned versions of the requirements are in conflict. Specifically, moto-ext==1.1.24 requires botocore>=1.7.12,  and boto3==1.4.4 requires botocore<1.6.0,>=1.5.0.

This prevents localstack from being installed by tools which do proper dependency resolution, such as pipenv. This issue appears to have been introduced version 0.8.2.

To reproduce (assuming [pipenv](https://docs.pipenv.org/install.html#installing-pipenv) is installed):
`mkdir repro && cd repro` 
`pipenv install localstack`

**Comment by dhoeric** [comment]
same here ☹️

**Comment by whummer** [comment]
Thanks for reporting @mikedal , this should be fixed in #533 . Can you please give it a try with the latest version `0.8.4`.

**Comment by mikedal** [comment]
Yep, works for me now. Thanks!
