### ISSUE TITLE
bug: memory leak 

### ISSUE THREAD

**Issue by Ne0xygene** [localstack/localstack#4896]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

localstack is used with 3 aws services : S3, SES, SQS.
I have allocated 4GB RAM for usage in docker.
The RAM usage of `localstack` container is increasing indefinitely until it reaches the limit then it restarts.

### Expected Behavior

It shouldn't use that much ram.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

Run `docker-compose up localstack` with following configuration :
```  localstack:
    image: localstack/localstack:0.12.20
    container_name: localstack
    environment:
      - DATA_DIR=/opt/localstack/data
      - SERVICES=s3,ses,sqs
      - DEBUG=1
    ports:
      - 4566:4566
    volumes:
      - localstack-data:/opt/localstack/data```

### Environment

```markdown
- OS: macOS Big Sur 11.5.2 (20G95)
- LocalStack: try on latest and 0.12.20
- Docker: 20.10.8
- Docker-Compose: 1.29.2
```

### Anything else?

localstack container logs:
```
localstack                      | 2021-11-10 16:34:54,531 INFO exited: infra (exit status 2; not expected)
localstack                      | 2021-11-10 16:34:54,581 INFO spawned: 'infra' with pid 32950
localstack                      | (. .venv/bin/activate; exec bin/localstack start --host --no-banner)
localstack                      | make: *** [Makefile:233: infra] Killed
localstack                      | 2021-11-10 16:34:55,645 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```

Docker usage info:
```
CONTAINER ID   NAME                           CPU %     MEM USAGE / LIMIT     MEM %     NET I/O           BLOCK I/O         PIDS
56042968bc32   localstack                     103.97%   2.111GiB / 3.841GiB   54.94%    31.7MB / 32.3MB   28.4GB / 41kB     50
```

**Comment by thrau** [comment]
Hi @Ne0xygene, could you help us understand a bit better how you are using localstack, so we can reproduce the issue? How long is the container running for? How many SQS/SNS messages are you sending over what period of time? How many buckets do you have and are you storing a lot of files in them? Are you using a particular AWS SDK?

Any other info like that will be helpful, thanks!

**Comment by Ne0xygene** [comment]
Hello,

**How long is the container running for?**
The container runs for about 40-45 minutes before it starts to exceed the memory limit (4GB). Then it restarts.

**How many SQS/SNS messages are you sending over what period of time?**
I only send messages for specific actions (Upload of files).
When the problem occured, i only sent like 2/3 messages  in 15 minutes.

**How many buckets do you have and are you storing a lot of files in them? **
I have 1 bucket and 1 file store in it.

**Are you using a particular AWS SDK?**
https://github.com/aws/aws-sdk-go-v2

**Additional information:**
I have this message showed constantly:
```
localstack                      | Waiting for all LocalStack services to be ready
localstack                      | Waiting for all LocalStack services to be ready
localstack                      | Waiting for all LocalStack services to be ready
localstack                      | Waiting for all LocalStack services to be ready
localstack                      | Waiting for all LocalStack services to be ready
```

**Comment by Ne0xygene** [comment]
As an additional note, I'm also on Apple M1.

**Comment by chezsmithy** [comment]
@Ne0xygene 0.13.0 was just published with experimental arm support. Perhaps see how that works on your M1?

**Comment by Ne0xygene** [comment]
Hello @chezsmithy ,
I just upgraded to 0.13.0. And everything looks fine. I no longer have the memory leak issue. Thanks !

**Comment by thrau** [comment]
that's great news, @Ne0xygene! and thanks @chezsmithy for pointing out the new release. closing this now
