### ISSUE TITLE
Connecting localstack container to mysql container in the same network fails

### ISSUE THREAD

**Issue by yosilliq** [localstack/localstack#4907]
### Is there an existing issue for this?

- [X] I have searched the existing issues and read the documentation

### Question

Hi guys, I'm running a stepfunction flow which triggers some Lambda functions.
One of the functions tries to access mySql DB **which is on another docker-container**.
Both localstack and mySql containers are on the same docker network but I'm still getting connection error when function tries to connect using the domain name.

Seems that when running a stepfunction, the localstack container spawns a sub-container that is not a part of the network and doesn't have the env-setup.
Is there any env-variable I should set to solve this ?
I have set
LAMBDA_EXECUTOR=docker 
and
LAMBDA_DOCKER_NETWORK=<my-docker-net>

but seems it does not join the network
I ran: docker network inspect server_lc_network
and the localstack container is not there.

I have connected it manually with the command: 
    docker network connect server_lc_network localstack_main
but it is still not connecting.

Any ideas ?

Thanks 

### Anything else?

thanks

**Comment by dfangl** [comment]
Hi @yosilliq !
You would need to use `LAMBDA_DOCKER_NETWORK=server_lc_network`, then the spawning lambda containers should be in the correct network.
If this does not fix your issue, please share your docker-compose file and the logs of your lambda execution!

**Comment by yosilliq** [comment]
Hello, sorry for the late response (some production issues).. :)

My docker-compose.yml file is:
version: "2.1"
services:
  localstack:
    container_name: "localstack_main"
    image: localstack/localstack
    hostname: localstack
    ports:
      - "4566-4599:4566-4599" # ports of the different services
      - "9000:9000"

    environment:
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - SERVICES=serverless,events,athena,glue,lambda,stepfunctions,s3,logs,iam,cloudformation,apigateway,cloudwatch
      - LOCALSTACK_API_KEY=3jaLBCq92g
      - LAMBDA_DOCKER_NETWORK=server_lc_network
      - LAMBDA_EXECUTOR=docker
      - LAMBDA_REMOTE_DOCKER=0
      - DOCKER_FLAGS="-v /tmp:${DATA_DIR}"
      - EDGE_PORT=4566
      - IMAGE_NAME=localstack/localstack-full
    networks:
      - lc_network

networks:
  lc_network:
    driver: bridge

    
The problem is that despite  LAMBDA_DOCKER_NETWORK=server_lc_network 
when I do 'docker network inspect server_lc_network' the localstack_main container is not on the list.
I also tried and added the 'networks' section 
    networks:
      - lc_network

networks:
  lc_network:
    driver: bridge

Thanks!

**Comment by lynxeyedua** [comment]
Try connect to "host.docker.internal:3306" from your lambda, if port 3306 is reachable from your host. 

Not sure that this is conceptually correct, but worked for me.

**Comment by dfangl** [comment]
The localstack container itself should be added to your network by docker-compose itself. The LAMBDA_DOCKER_NETWORK environment variable only affects the localstack container.
You want your `db` container in the same network as localstack_main. If in the same docker-compose file, this should happen automatically if no explicit `network: ` is passed to a service. Then, you configure the environment variable `LAMBDA_DOCKER_NETWORK` to be that same network name. Per default in docker-compose, this is `[project_name]_default` per default, where the `[project_name]` is the docker-compose project name, normally the name of the parent directory of your docker-compose environment.
So, if your folder is called `server`, your default network name would be `server_default`, which would be the value of `LAMBDA_DOCKER_NETWORK`.
Please report if a setup like this works for you.

**Comment by dfangl** [comment]
I will close this now. If there are any problems with the suggested solution, please do not hesitate to reopen or file a new issue! Thanks!
