### ISSUE TITLE
bug: Images are duplicated in ECR repositories.

### ISSUE THREAD

**Issue by gjke** [localstack/localstack#4908]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Images are duplicated in ECR repositories. After creating multiple ECR repositories and pushing a single image to each of them, each of them has all the images that have been pushed to other repositories.

### Expected Behavior

Each ECR repository only has images that have been pushed to it.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

Create two ECR repositories:
`awslocal ecr create-repository --repository-name hello-world-1`
```
{
    "repository": {
        "repositoryArn": "arn:aws:ecr:eu-central-1:000000000000:repository/hello-world-1",
        "registryId": "5bdb3cbd",
        "repositoryName": "hello-world-1",
        "repositoryUri": "localhost:4510/hello-world-1",
        "createdAt": "2021-11-11T18:24:25+01:00",
        "imageTagMutability": "MUTABLE",
        "imageScanningConfiguration": {
            "scanOnPush": false
        },
        "encryptionConfiguration": {
            "encryptionType": "AES256"
        }
    }
}
```

`awslocal ecr create-repository --repository-name hello-world-2`
```
{
    "repository": {
        "repositoryArn": "arn:aws:ecr:eu-central-1:000000000000:repository/hello-world-2",
        "registryId": "6d443d7f",
        "repositoryName": "hello-world-2",
        "repositoryUri": "localhost:4511/hello-world-2",
        "createdAt": "2021-11-11T18:24:35+01:00",
        "imageTagMutability": "MUTABLE",
        "imageScanningConfiguration": {
            "scanOnPush": false
        },
        "encryptionConfiguration": {
            "encryptionType": "AES256"
        }
    }
}
```

Pull the hello-world  image:
`docker pull hello-world`

Tag it for the first repository and push it:
`docker tag hello-world:latest localhost:4510/hello-world-1`
`docker push localhost:4510/hello-world-1`

Make sure it is in the first repository and that the second repository is empty:
`awslocal ecr list-images --repository-name hello-world-1`
```
{
    "imageIds": [
        {
            "imageDigest": "sha256:01433e86a06b752f228e3c17394169a5e21a0995f153268a9b36a16d4f2b2184",
            "imageTag": "latest"
        }
    ]
}
```

`awslocal ecr list-images --repository-name hello-world-2`
```
{
    "imageIds": []
}
```

So far so good. Now tag it for the second repository and push it:
`docker tag hello-world:latest localhost:4511/hello-world-2`
`docker push localhost:4511/hello-world-2 `

List images in both repositories:
`awslocal ecr list-images --repository-name hello-world-1 `
```
{
    "imageIds": [
        {
            "imageDigest": "sha256:01433e86a06b752f228e3c17394169a5e21a0995f153268a9b36a16d4f2b2184",
            "imageTag": "latest"
        },
        {
            "imageDigest": "sha256:01433e86a06b752f228e3c17394169a5e21a0995f153268a9b36a16d4f2b2184",
            "imageTag": "latest"
        }
    ]
}
```

`awslocal ecr list-images --repository-name hello-world-2`
```
{
    "imageIds": [
        {
            "imageDigest": "sha256:01433e86a06b752f228e3c17394169a5e21a0995f153268a9b36a16d4f2b2184",
            "imageTag": "latest"
        },
        {
            "imageDigest": "sha256:01433e86a06b752f228e3c17394169a5e21a0995f153268a9b36a16d4f2b2184",
            "imageTag": "latest"
        }
    ]
}
```

### Environment

```markdown
- OS: Mac M1 Big Sur
- LocalStack: 0.12.20
```

**Comment by dfangl** [comment]
Sorry for the long wait. This should be fixed in the :latest image! Thanks for reporting this!
