### ISSUE TITLE
Java AWSLambda - event based invocation of the function

### ISSUE THREAD

**Issue by teroxik** [localstack/localstack#491]
Hi, first thanks for great open source project.

I'm currently trying set up some tests around my java based lambda function - reading from dynamo streams and pushing to kinesis. Everything is set up I can invoke the function manually and the function gets invoked automatically. So far so good, unfortunately the event based invocation is not working:

```
2017-11-30T07:50:38:WARNING:localstack.services.awslambda.lambda_api: Error executing Lambda function: 'NoneType' object has no attribute 'cwd' Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 251, in run_lambda
    event, context=context, version=version, async=async)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 441, in execute
    lambda_cwd = func_details.cwd
AttributeError: 'NoneType' object has no attribute 'cwd'
```

Looking quickly at the code it seems that the tmp_dir property is not set correctly for the lambda function. I can see in the code that there is difference how the lambda gets executed for the java based ones as it uses **execute_java_lambda** function and ti seems to me that this function is not called in case of the event invocation. Cold eventually try to fix that. Is this a known issue?

**Comment by kprzerwa-r7** [comment]
@teroxik with everything set up correctly, it should be working...
```
POST /2015-03-31/functions/<FunctionArn>/invocations?Qualifier=Qualifier HTTP/1.1 
X-Amz-Invocation-Type: Event 
Content-Type: application/json

<Payload>
 ```
At the moment only KinesisEvent and SNSEvent are supported, and we've got tests for both.
Your error would indicate that function arn is empty and details can not be retrieved.
Can you share your lambda setup and the command you're invoking the lambda with? (aws cli? REST?)

**Comment by teroxik** [comment]
@kprzerwa-r7 Thank you for your response and offered help.

I'm setting DDB streams processing using lambda. So I tried to get the stream arn for the mapping using two different ways which I have found in other issue mentioned as working:

```
STREAM_ARN='aws dynamodb describe-table \
          --region us-east-1 \
          --endpoint ${LOCAL_HOST}:${DYNAMO_PORT} \
          --table-name ${TABLE_NAME} | jq --raw-output .Table.LatestStreamArn'

STREAM_ARN='aws dynamodbstreams list-streams --endpoint ${LOCAL_HOST}:4570 --region us-east-1 | jq -r '.Streams[0].StreamArn''
```

There is a subtle difference in what is being returned:
1) arn:aws:dynamodb:ddblocal:000000000000:table/test-table-dev/stream/2017-12-11T11:39:46.113
2) arn:aws:dynamodb:us-east-1:000000000000:table/test-table-dev/stream/2017-12-11T11:39:51

The invocation works - when I directly use a cli with a wrong event type. I can see that the source mapping kicks in - as my test is to write into the dynamo and see if the event gets processed. After I do an insert into dynamo  I see in the logs a corresponding lambda failure which I have initially mentioned.

If I use the 1) for the mapping seems that the function doesn't get triggered at all, I don't see anything related to the actual lambda execution.

**Comment by teroxik** [comment]
So you were right @kprzerwa-r7. I had the reference in source mapping to the lambda function wrong.

It gets executed now but I get a class cast Exception:
```
java.lang.ClassCastException: java.util.LinkedHashMap cannot be cast to com.amazonaws.services.lambda.runtime.events.DynamodbEvent
``` 

Closing this and will open another once I will find more. Thanks for your help.

**Comment by kprzerwa-r7** [comment]
@teroxik The last error you've posted is a limitation in LambdaExecutor. Block here -> https://github.com/localstack/localstack/blob/master/localstack/ext/java/src/main/java/cloud/localstack/LambdaExecutor.java#L52-L85 is responsible for parsing appropriate event type object out of event payload and passing it to the handler. As you can see, it does not support DynamodbEvent yet (hence the TODO).

**Comment by teroxik** [comment]
@kprzerwa-r7 Ok, PR is coming for this soon.

**Comment by aggansu** [comment]
+1

Facing similar issue with S3Event object.
