### ISSUE TITLE
bug: 'cognito:user_status' is not sent to post-auth lambda in 'userAttributes'

### ISSUE THREAD

**Issue by EinavBar18** [localstack/localstack#4915]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When log in via cognito it triggers a post-auth lambda that receives a request from cognito.
That request includes user attributes such as 'cognito:user_status' and some custom properties.

When log in via localstack it triggers that lambda but 'cognito:user_status' is missing in the user attributes in the request.

### Expected Behavior

 'cognito:user_status' is exist in the request to the post auth lambda.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal s3 mb s3://mybucket

### Environment

```markdown
- OS: 
- LocalStack:
```

**Comment by whummer** [comment]
Hi @EinavBar18 , thanks for reporting. This should be (hopefully) fixed in the meantime - can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists, or if you're experiencing any other discrepancies with real AWS. Thanks for your help!
