### ISSUE TITLE
bug: aws v2 dynamodb table management

### ISSUE THREAD

**Issue by zhammer** [localstack/localstack#4923]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

i've written up the current behavior, as well as a reproducible environment, here: https://gist.github.com/zhammer/6f95a75a8f5059f7d6d2624449ca296d

### Expected Behavior

i should be able to create & delete dynamodb tables using aws sdk v2.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

see README.md in https://gist.github.com/zhammer/6f95a75a8f5059f7d6d2624449ca296d

### Environment

```markdown
- OS: Darwin 20.5.0
- LocalStack: localstack/localstack:2021-11-15 (have tried a few versions)
```

**Comment by zhammer** [comment]
update: i tested this against the `latest` (`1.17.0`) image of https://hub.docker.com/r/amazon/dynamodb-local and the bug does _not_ occur

**Comment by zhammer** [comment]
i tested this against the latest localstack release (1.13.0) and still see the bug. digging deeper into the localstack code, i'm suspecting that this has to do with the dynamodb proxy code:

https://github.com/localstack/localstack/blob/07b6887a4e6c0458def3ab4b1a99c6f5620942e6/localstack/services/dynamodb/dynamodb_listener.py#L127-L134

see the `ResourceInUseException` exception in that python proxy code, and the corresponding error we see in our application logs:

```
SDK 2021/11/15 16:22:08 DEBUG Request
POST / HTTP/1.1
Host: localhost:4566
User-Agent: aws-sdk-go-v2/1.11.0 os/macos lang/go/1.17.2 md/GOOS/darwin md/GOARCH/amd64 api/dynamodb/1.8.0
Content-Length: 219
Accept-Encoding: identity
Amz-Sdk-Invocation-Id: edd944a7-c470-4857-b38b-b89803f348f7
Amz-Sdk-Request: attempt=1; max=3
Authorization: AWS4-HMAC-SHA256 Credential=foobar/20211115//dynamodb/aws4_request, SignedHeaders=accept-encoding;amz-sdk-invocation-id;amz-sdk-request;content-length;content-type;host;x-amz-date;x-amz-target, Signature=8be5c9bc98a28de2b7c42be6bb0ec0fab1bc6f9ebe755b2272b17c83fb20878f
Content-Type: application/x-amz-json-1.0
X-Amz-Date: 20211115T212208Z
X-Amz-Target: DynamoDB_20120810.CreateTable

{"AttributeDefinitions":[{"AttributeName":"id","AttributeType":"S"}],"KeySchema":[{"AttributeName":"id","KeyType":"HASH"}],"ProvisionedThroughput":{"ReadCapacityUnits":10,"WriteCapacityUnits":10},"TableName":"my-table"}
SDK 2021/11/15 16:22:08 DEBUG Response
HTTP/1.1 400 
Connection: close
Content-Length: 112
Access-Control-Allow-Headers: authorization,cache-control,content-length,content-md5,content-type,etag,location,x-amz-acl,x-amz-content-sha256,x-amz-date,x-amz-request-id,x-amz-security-token,x-amz-tagging,x-amz-target,x-amz-user-agent,x-amz-version-id,x-amzn-requestid,x-localstack-target,amz-sdk-invocation-id,amz-sdk-request
Access-Control-Allow-Methods: HEAD,GET,PUT,POST,DELETE,OPTIONS,PATCH
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: etag,x-amz-version-id
Content-Type: application/x-amz-json-1.0
Date: Mon, 15 Nov 2021 21:22:08 GMT
Server: hypercorn-h11
X-Amz-Crc32: 1756396488
X-Amzn-Requestid: d2a9dff8-fa9d-4d6e-b464-150c5675c320

{"__type":"com.amazonaws.dynamodb.v20120810#ResourceInUseException","Message":"Cannot create preexisting table"}
2021/11/15 16:22:08 error creating table: operation error DynamoDB: CreateTable, https response error StatusCode: 400, RequestID: d2a9dff8-fa9d-4d6e-b464-150c5675c320, ResourceInUseException: 
```

**Comment by zhammer** [comment]
may be getting closer to a solution here. i've been testing behavior of the same aws calls using both the aws-sdk-go and aws-sdk-go v2 libraries against localstack running on my development environment. after being stuck for a while, i found this util function (and comment)

https://github.com/localstack/localstack/blob/d5b9d1cf64ae92866a00d24554d160bc2612da05/localstack/services/dynamodb/dynamodb_listener.py#L611-L618

i added the following log line near the top of `forward_request` (after the headers have been prepared) to compare credentials from v1 vs v2.

```py
print(f"Action={action}, Auth={re.search(r'Credential=[^,]*', headers['Authorization']).group(0)}")
```

logs from v1
```
Action=CreateTable, Auth=Credential=test/20211116/us-east-1/dynamodb/aws4_request
Action=ListTables, Auth=Credential=test/20211116/us-east-1/dynamodb/aws4_request
Action=Scan, Auth=Credential=test/20211116/us-east-1/dynamodb/aws4_request
Action=DeleteTable, Auth=Credential=test/20211116/us-east-1/dynamodb/aws4_request
Action=ListTables, Auth=Credential=test/20211116/us-east-1/dynamodb/aws4_request
```

logs from v2
```
Action=CreateTable, Auth=Credential=test/20211116//dynamodb/aws4_request
Action=ListTables, Auth=Credential=test/20211116/us-east-1/dynamodb/aws4_request
Action=Scan, Auth=Credential=test/20211116//dynamodb/aws4_request
Action=DeleteTable, Auth=Credential=test/20211116//dynamodb/aws4_request
Action=ListTables, Auth=Credential=test/20211116/us-east-1/dynamodb/aws4_request
```

the two `ListTables` calls are internal calls made by localstack when a user sends a `CreateTable` or `DeleteTable`, here:

https://github.com/localstack/localstack/blob/07b6887a4e6c0458def3ab4b1a99c6f5620942e6/localstack/services/dynamodb/dynamodb_listener.py#L79-L81

the rest of the calls (`CreateTable`, `Scan`, `DeleteTable`) come from the go app. it seems that the v2 sdk doesn't add a region into the `Credential` string, whereas v1 does. that's why in v2 we see "test/20211116//dynamodb/aws4_request" whereas in v1 we see "test/20211116/us-east-1/dynamodb/aws4_request". according to the `prepare_request_headers` docstring, this means that dynamodblocal will send these requests to "different namespaces." i'm not sure exactly what that means but it seems like it could be the culprit.

it would explain why my app can run against dynamodblocal. all requests use the same credential, without the empty region. when localstack is involved it interjects its own requests to dynamodblocal and uses what seems to be the proper credential string. since that's different from the credential coming from my app, the requests hit a different namespace.

now i just need to figure out if this is due to a config issue in my go code or an issue with the sdk... i'm imagining it's an issue with my setup :)

**Comment by zhammer** [comment]
resolution was to add a `SigningReason` to my `aws.Endpoint` in config. lol.

```go
		config.WithEndpointResolver(aws.EndpointResolverFunc(func(service, region string) (aws.Endpoint, error) {
			return aws.Endpoint{URL: "http://localhost:4566", SigningRegion: "us-east-2"}, nil
		})),
```

**Comment by thrau** [comment]
Hi Zach @zhammer , glad your issue was resolved ;-) 

is there anything in the docs on our end that could have helped you, that we can improve?
