### ISSUE TITLE
Can't create RDS MySQL Database

### ISSUE THREAD

**Issue by DIU-marc** [localstack/localstack#4931]
Hi,
when i want to create a Database via Terraform, I'll get the error below (shown in console/stdout) while apply:

`ERROR: 'apk add /tmp/localstack/ls-mysql-pkgs/*.apk': exit code 99; output: b'fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86_64/APKINDEX.tar.gz fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/community/x86_64/APKINDEX.tar.gz
ERROR: /tmp/localstack/ls-mysql-pkgs/busybox-1.31.1-r10.apk: BAD signature`

I am using localstack:latest.

Some more Debug output:

`2021-11-16T12:51:28:INFO:localstack_ext.services.rds.db_utils: Unable to startup DB instance: Command 'apk add /tmp/localstack/ls-mysql-pkgs/*.apk' returned non-zero exit status 99. Traceback (most recent call last):
|File "/opt/code/localstack/.venv/lib/python3.7/site-packages/localstack_ext/services/rds/db_utils.py", line 63, in do_startup
|File "/opt/code/localstack/.venv/lib/python3.7/site-packages/localstack_ext/services/rds/db_utils.py", line 145, in start_db_instance
|File "/opt/code/localstack/.venv/lib/python3.7/site-packages/localstack_ext/services/rds/db_utils.py", line 199, in install_mysql
|File "/opt/code/localstack/localstack/utils/common.py", line 1753, in run
|  return do_run(cmd, run_cmd, cache_duration_secs)
|File "/opt/code/localstack/localstack/utils/common.py", line 1727, in do_run
|  return run_cmd()
|File "/opt/code/localstack/localstack/utils/common.py", line 1751, in run_cmd
|  return localstack.utils.run.run(cmd, **kwargs)
|File "/opt/code/localstack/localstack/utils/run.py", line 109, in run
|  raise e
|File "/opt/code/localstack/localstack/utils/run.py", line 59, in run
|  output = subprocess.check_output(cmd, shell=shell, stderr=stderr, env=env_dict, cwd=cwd)
|File "/usr/lib/python3.7/subprocess.py", line 411, in check_output
|  **kwargs).stdout
|File "/usr/lib/python3.7/subprocess.py", line 512, in run
|  output=stdout, stderr=stderr)
| subprocess.CalledProcessError: Command 'apk add /tmp/localstack/ls-mysql-pkgs/*.apk' returned non-zero exit status 99.`

**Comment by thrau** [comment]
Hi @DIU-marc , could you provide a bit more information on how you are starting localstack? we have a template here with the information we typically need to reproduce an issue: https://github.com/localstack/localstack/issues/new?assignees=&labels=bug%2Cneeds-triaging&template=bug-report.yml&title=bug%3A+%3Ctitle%3E

could you please run another docker pull on the latest image? it looks like you're not on the current latest (0.13) which uses debian instead of alpine, and python 3.8. judging from the logs you're still on the previous version.

**Comment by DIU-marc** [comment]
Thanks for that quick response!

This error has been fixed with the pull (now on 0.13). But now I'm getting:

`[ERROR] mysqld: Can't lock aria control file '/tmp/localstack/data/rds-data-mysql/us-east-1/my_db/data/aria_log_control' for exclusive use, error: 11. Will retry for 30 seconds
[ERROR] mysqld: Got error 'Could not get an exclusive lock; file is probably in use by another process' when trying to use aria control file '/tmp/localstack/data/rds-data-mysql/us-east-1/my_db/data/aria_log_control'
[ERROR] Plugin 'Aria' init function returned error.
[ERROR] Plugin 'Aria' registration as a STORAGE ENGINE failed.
ERROR: 1932  Table 'information_schema.(temporary)' doesn't exist in engine


The problem could be conflicting information in an external my.cnf files. You can ignore these by doing:
shell> /usr/bin/mysql_install_db --defaults-file=~/.my.cnf
`

I am running localstack via docker-compose on a Linux host (Ubuntu 18) with config:

`localstack:
    image: localstack/localstack:latest
    ports:
      - "443:443"
      - "4566:4566"
      - "4571:4571"
    environment:
      AWS_REGION: ${AWS_REGION}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY}
      HOSTNAME: localstack
      SERVICES: lambda,apigateway,rds,s3,cloudformation,sns,iam
      DOCKER_HOST: unix:///var/run/docker.sock
      LAMBDA_EXECUTOR: docker
      DATA_DIR: /tmp/localstack/data
    volumes:
      - ./.localstack:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock`

**Comment by DIU-marc** [comment]
Update:

After removing all terraform sources and a docker-compose down (restarting), now everything works fine.

**Comment by thrau** [comment]
yep, possibly. glad your issue is solved!
