### ISSUE TITLE
bug: Unable to download ARM64 lambda layers

### ISSUE THREAD

**Issue by mLupine** [localstack/localstack#4932]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The Pro version of LocalStack supports fetching Lambda layers from AWS. Your lambda layer proxy probably uses the x86_64 architecture to extract the contents of a specified layer. Layers can, however, specify architectures they're compatible with and if a layer is only compatible with arm64, the proxy returns error 500. 
```
Exception: Error code 500 when requesting layer content from proxy service
```

You can reproduce the issue by trying to fetch the arm64 version of my [Git layer](https://github.com/mLupine/lambda-git). `arn:aws:lambda:eu-west-1:110966697890:layer:lambda-git-x86_64:1` works just fine, but `arn:aws:lambda:eu-west-1:110966697890:layer:lambda-git-arm64:1` fails with the aforementioned error. 

### Expected Behavior

The layer should be downloaded successfully.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    Docker-Compose + SLS plugin

### Environment

```markdown
- OS: macOS Monterey
- LocalStack: 0.13.0 / latest
```

### Anything else?

https://github.com/localstack/localstack/issues/4921#issuecomment-970170281

**Comment by joe4dev** [comment]
Thank you for reaching out @mLupine 

We just implemented fetching shared lambda layers in our new lambda provider implementation. Could you try:

1. Pulling the latest LocalStack Pro image: `docker pull localstack/localstack-pro`
2. Starting LocalStack with the feature flag `PROVIDER_OVERRIDE_LAMBDA=v2`

We are currently working on fixing an ARM-related issue for x86 functions https://github.com/localstack/localstack/issues/7637

Further, we are planning to test ARM functions in the coming weeks.

**Comment by joe4dev** [comment]
Hi @mLupine 

Your example with public ARM layers is now supported in LocalStack. Please:

1. Pull the latest LocalStack image: `docker pull localstack/localstack-pro`
2. Start LocalStack with the feature flag `PROVIDER_OVERRIDE_LAMBDA=v2`

Does this fix your issue?

## Example

It is now possible to create lambda functions that run on ARM (on ARM hosts only) with public ARM layers (pro feature):

```bash
# Create
awslocal lambda create-function --function-name my-lambda \
--zip-file fileb://function.zip \
--handler main.handler --runtime python3.9 \
--role arn:aws:iam::000000000000:role/lambda-role \
--layers "arn:aws:lambda:us-east-1:110966697890:layer:lambda-git-arm64:1" \
--architectures arm64
```

Given such a Python lambda function:

```python
print('## PLATFORM')
print(platform.machine())
print('## LAYER GIT')
os.system('git --version')
```

We can see the following output using the layer from your example:

```plain
## PLATFORM
aarch64
## LAYER GIT
git version 2.33.1
```
