### ISSUE TITLE
bug: AWS Batch Cloudwatch Events have incorrect information

### ISSUE THREAD

**Issue by bforcier1** [localstack/localstack#4934]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After successfully submitting a job to localstack Batch, the Cloudwatch Event messages are processed for `RUNNING` states. The setup being:

application.submitJob -> Localstack Batch -> Localstack CloudwatchEvent -> Localstack SNS -> Localstack SQS -> application

Localstack is publishing a message:
`localstack_1  | 2021-11-16T16:36:12:DEBUG:localstack.services.sns.sns_listener: Publishing message to TopicArn: arn:aws:sns:us-east-1:000000000000:chainlink000-local-batch-event-running-job-sns | Message: {"version": "0", "id": "aabb8918-7a41-44f3-9c0d-24f7c144f48a", "detail-type": "Batch Job State Change", "source": "aws.batch", "account": "000000000000", "time": "2021-11-16T16:36:12Z", "region": "us-east-1", "resources": ["arn:aws:batch:us-east-1:000000000000:job/e48706ad-78d6-4bef-b68d-30242c176b3c"], "detail": {"jobName": "2db6a183-dd2b-4615-8b80-41b72fd88ec3", "jobId": "e48706ad-78d6-4bef-b68d-30242c176b3c", "status": "RUNNING", "attempts": [], "createdAt": 1637080572413, "retryStrategy": {"attempts": 1}, "dependsOn": [], "parameters": {}, "container": {"image": "busybox", "vcpus": 2, "memory": 2000, "command": [], "volumes": [], "environment": [], "mountPoints": [], "ulimits": []}}}`

Although this message seemingly has totally different values than expected. And some values aren't present at all. Compared to the results from describing the job via the SDK:

```
aws --endpoint-url=http://localhost:4566 batch describe-jobs --jobs e48706ad-78d6-4bef-b68d-30242c176b3c
{
    "jobs": [
        {
            "jobName": "2db6a183-dd2b-4615-8b80-41b72fd88ec3",
            "jobId": "e48706ad-78d6-4bef-b68d-30242c176b3c",
            "jobQueue": "arn:aws:batch:us-east-1:000000000000:job-queue/XXX",
            "status": "FAILED",
            "createdAt": 1637080571806,
            "startedAt": 1637080571861,
            "stoppedAt": 1637080572639,
            "dependsOn": [],
            "jobDefinition": "arn:aws:batch:us-east-1:000000000000:job-definition/XXX:1",
            "container": {
                "vcpus": 2,
                "memory": 4000,
                "command": [
                    "bash",
                    "-c",
                    "<LONG_COMMAND>"
                ],
                "volumes": [],
                "environment": [
                    {
                        "name": "AWS_BATCH_JOB_ID",
                        "value": "e48706ad-78d6-4bef-b68d-30242c176b3c"
                    },
                    {
                        "name": "AWS_ACCESS_KEY_ID",
                        "value": "test"
                    },
                    {
                        "name": "AWS_SECRET_ACCESS_KEY",
                        "value": "test"
                    },
                    {
                        "name": "LOCALSTACK_HOSTNAME",
                        "value": "172.19.0.2"
                    }
                ],
                "readonlyRootFilesystem": false,
                "ulimits": [
                    {
                        "hardLimit": 10240,
                        "name": "nofile",
                        "softLimit": 10240
                    }
                ],
                "privileged": false,
                "logStreamName": "XXX/default/e48706ad-78d6-4bef-b68d-30242c176b3c"
            }
        }
    ]
}
```
see Memory, Image, Command among others. 

### Expected Behavior

The JSON events published should follow the interface defined here https://docs.aws.amazon.com/batch/latest/userguide/batch_cwe_events.html

Additionally neither the event message nor the describeJob result completely implement all fields documented here https://docs.aws.amazon.com/batch/latest/APIReference/API_DescribeJobs.html#API_DescribeJobs_ResponseSyntax

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

```
docker-compose up --build 
version: '2.1'

services:
  localstack:
    image: localstack/localstack:0.12.20
    ports:
      - "4566:4566" # omnibus port
    environment:
      - SERVICES=sqs,s3,sns,cloudwatch,batch,dynamodb,cloudwatch,ec2,route53,ssm,iam,events,logs,sts
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEBUG=1
      - LOCALSTACK_API_KEY=XXX
    volumes:
      - "/tmp/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)
```
  aws --endpoint-url=http://localhost:4566 sqs receive-message --queue-url <BATCH_EVENT_QUEUE_URL>
  aws --endpoint-url=http://localhost:4566 batch describe-jobs --jobs e48706ad-78d6-4bef-b68d-30242c176b3c
```

### Environment

```markdown
- OS: MacOS Catalina 10.15.7 
- LocalStack: 0.12.20
```

**Comment by whummer** [comment]
Thanks for reporting @bforcier1 . We've just pushed a couple of enhancements which should (hopefully) resolve the incorrect fields published to the EventBridge messages. Can you please pull the `latest` Docker image and give it another try? 

Also, we'll look into adding the missing fields from the `DescribeJob` API call - given that there is a relatively long list of parameters for Batch jobs, it would be great if you could share some details about your use case, to help us prioritize which features to focus on first. Thanks for your help!
