### ISSUE TITLE
bug: SQS QueueArn does not match what is returned with getQueueArn()

### ISSUE THREAD

**Issue by mhkhung** [localstack/localstack#4935]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

QueueArn returned by get-queue-attributes is not the same as the API getQueueArn() causing issues when trying to set dead letter queue etc.

### Expected Behavior

QueueArn is consistent

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    aws --endpoint-url=http://localhost:4566 sqs

To reproduce:
Create a queue via localStack and use aws cli to inspect the queue attributes:
```
$ aws --endpoint-url=http://localhost:4566 sqs get-queue-attributes --queue-url="http://localhost:4566/000000000000/TestQueue" --attribute-names All
{
    "Attributes": {
        "ApproximateNumberOfMessages": "0",
        "ApproximateNumberOfMessagesDelayed": "0",
        "ApproximateNumberOfMessagesNotVisible": "0",
        "CreatedTimestamp": "1637083084.543154",
        "DelaySeconds": "0",
        "LastModifiedTimestamp": "1637083084.543154",
        "MaximumMessageSize": "262144",
        "MessageRetentionPeriod": "345600",
        "QueueArn": "arn:aws:sqs:us-east-1:000000000000:TestQueue",
        "ReceiveMessageWaitTimeSeconds": "0",
        "VisibilityTimeout": "30"
    }
}
```
Note the QueueArn contains us-east-1 in the Arn.

Using the php API getQueueArn('http://localhost:4566/000000000000/TestQueue') returns
```
arn:aws:localhost:4566:000000000000:TestQueue
```

It's causing issues when trying to set dead letter queue:
```
ws\Sqs\Exception\SqsException: Error executing "SetQueueAttributes" on "http://localhost:4566/000000000000/TestQueue"; AWS HTTP error: Client error: `POST http://localhost:4566/000000000000/TestQueue` resulted in a `400 Bad Request` response:
<?xml version="1.0" encoding="UTF-8"?>
  <ErrorResponse>
    <Errors>
      <Error>
        <Code>AWS.SimpleQueueService (truncated...)
 AWS.SimpleQueueService.NonExistentQueue (client): Could not find DLQ for arn:aws:localhost:4566:000000000000:TestQueue_dead - <?xml version="1.0" encoding="UTF-8"?>
  <ErrorResponse>
    <Errors>
      <Error>
        <Code>AWS.SimpleQueueService.NonExistentQueue</Code>
        <Message><![CDATA[Could not find DLQ for arn:aws:localhost:4566:000000000000:TestQueue_dead]]></Message>
        
      </Error>
    </Errors>
  <RequestId>SGTQWTXIM5MQOQA3IG3VJZHFNM288SD9YR6DOU8RY6ZKI3WON5C3</RequestId>
</ErrorResponse>

```

### Environment

```markdown
- OS: Debian 10, docker
- LocalStack: Latest in docker
```

**Comment by thrau** [comment]
hey @mhkhung, thanks for the bug report. could you maybe provide a minimal working example of the php code you are running? i assume it is this method you are calling? https://docs.aws.amazon.com/aws-sdk-php/v3/api/class-Aws.Sqs.SqsClient.html#_getQueueArn

**Comment by thrau** [comment]
actually it looks like this may be a limitation of the PHP AWS SDK. looking at the code, they directly parse the URL, which in the `localhost:4566` case doesn't resolve correctly: https://github.com/aws/aws-sdk-php/blob/15f6b434b92826a321191bf5b72820934d970580/src/Sqs/SqsClient.php#L73-L88

could you, as a workaround, use the `getQueueAttributes` method to get the ARN from the attributes directly? obviously this involves an API call, but i don't see a way around it at the moment.

**Comment by mhkhung** [comment]
Thanks.. I am doing a str_replace as a workaround when I am running unit-tests for now.. 
```
if (defined('CI_PHPUNIT_TEST')) {
    $arn = str_replace('localhost:4566', 'sqs:us-east-1', $arn);
}
```

**Comment by thrau** [comment]
closing this for now as i don't see how we could easily fix this.
