### ISSUE TITLE
bug: Documentation is lacking for specific ports

### ISSUE THREAD

**Issue by posita** [localstack/localstack#4936]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

There doesn't appear to be a unified list of services and default ports in the documentation. The Getting Started section, for example, suggests mapping port 4571, but completely neglects to tell anyone why or what it's used for. Searching for 4571 in the docs yields mixed results. Only when one stumbles onto the ElasticSearch result does the answer reveal itself.

### How are you starting LocalStack?

With a `docker run` command

### Steps To Reproduce

Consider _prominently_ featuring a list (table?) of services and their respective ports.

**Comment by thrau** [comment]
thanks for the hint Matt @posita. we've only recently removed the necessity for 4571 with custom elasticsearch endpoints #4866. most services can be routed through the edge port 4566. APIs that spawn backend services with binary protocols (like RDS, redis, etc, ...) require a port from the service port range, and one will be allocated from there.

but i agree the docs and our example could use some updating there!

I've linked this issue in the docs repo: https://github.com/localstack/docs/issues/80

**Comment by alexrashed** [comment]
Hi @posita!
With https://github.com/localstack/docs/pull/108 we've added some documentation on the external service ports.
You can find the deployed version here: https://docs.localstack.cloud/localstack/external-ports/
As @thrau mentioned, the port 4571 is not used in the latest LocalStack version anymore.
Does the new section in the docs answer your questions?

**Comment by posita** [comment]
Yup! Thanks for the change. Looks good! Want me to close this?

**Comment by thrau** [comment]
thanks Matt, glad we could help!
