### ISSUE TITLE
feature request: local mount of lambda layer code

### ISSUE THREAD

**Issue by navels** [localstack/localstack#4937]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

We can use the `__local__` S3 bucket to mount lambda function code into the lambda container.  But the [lambda container](https://github.com/lambci/docker-lambda) also supports mounting layer code:
```
docker run --rm \
  -v <code_dir>:/var/task:ro,delegated \
  [-v <layer_dir>:/opt:ro,delegated] \
  lambci/lambda:<runtime> \
  [<handler>] [<event>]
```
and my reading of the localstack code is that this should be trivial to implement.

For now I just pass that mount flag via `LAMBDA_DOCKER_FLAGS` and that works but it would be better to wire this up in localstack like we do for the function code.

### 🧑‍💻 Implementation

This code: [lambda_executors.py](https://github.com/localstack/localstack/blob/d5b9d1cf64ae92866a00d24554d160bc2612da05/localstack/services/awslambda/lambda_executors.py#L1195-L1199) should be straightforward to modify to allow a mount for the layers.

**Comment by davecardwell** [comment]
I think this still a worthwhile addition and the Issue should not be closed.

**Comment by dfangl** [comment]
Hi!
This functionality is now implemented in our new provider `PROVIDER_OVERRIDE_LAMBDA=asf`, and should work in the image pushed in around 1 hour.
Please note the instructions given here: https://github.com/localstack/localstack/issues/7200#issuecomment-1355311772 , they are the same for the layers. So please provide the s3 bucket name `hot-reload` and s3 key of the path on your local machine when creating a lambda.

Please notice that for hot reloading layers, *only one* layer may be assigned per function. So basically, if a hot reloading layer is added to a function, it has to be the only one, no others (neither hot reloading nor normal layers) will be allowed.

**Comment by navels** [comment]
Thanks!
