### ISSUE TITLE
bug: S3 Copy does not honour KMS parameters

### ISSUE THREAD

**Issue by FloatingGhost** [localstack/localstack#4951]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When requesting an S3 copy, it is possible to specify SSE KMS keys to encrypt the result - localstack does not respect these settings

It returns
```json
{
    "CopyObjectResult": {
        "ETag": "\"f02e326f800ee26f04df7961adbf7c0a\"",
        "LastModified": "2021-11-18T12:50:48+00:00"
    }
}
```

### Expected Behavior

```bash
aws s3api copy-object --bucket bugreport-kmstest --key dest.txt --copy-source '/bugreport-kmstest/source.txt' --ssekms-key-id $key --server-side-encryption aws:kms

{
    "ServerSideEncryption": "aws:kms",
    "SSEKMSKeyId": "redacted",
    "CopyObjectResult": {
        "ETag": "\"someEtag\"",
        "LastModified": "2021-11-18T12:45:38+00:00"
    }
}
```

### How are you starting LocalStack?

With a `docker run` command

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run --rm -p 4566:4566 -e 'DEFAULT_REGION=eu-west-1' -e 'SERVICES=s3,kms' --name localstack localstack/localstack:latest

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```bash
KEY=$(awslocal kms create-key | jq -r .KeyMetadata.KeyId)
awslocal s3api create-bucket --bucket test
echo "dummy" > testFile.txt        
                                   
awslocal s3api put-object --bucket test --key source.txt --body testFile.txt
awslocal s3api copy-object --copy-source '/test/source.txt' --bucket test --key dest.txt --ssekms-key-id $KEY --server-side-encryption aws:kms
```

### Environment

```markdown
- OS: Arch Linux, docker
- LocalStack: docker latest @ 18/11/2021
```

**Comment by FloatingGhost** [comment]
source of this seems to be moto, seeing if i can patch

**Comment by FloatingGhost** [comment]
Raised PR with moto that should rectify the situation, will need a moto-ext release when that's merged https://github.com/spulec/moto/pull/4593

**Comment by naspeh** [comment]
Hi @FloatingGhost,

Thank you for reporting and fixing the issue.

It's already in our fork https://github.com/localstack/moto/blob/d5b04f3ca22e207b3d6c4fc20cb36e1d76e53ee4/moto/s3/models.py#L2062-L2063

Please try the latest docker image: `localstack/localstack:latest`

**Comment by naspeh** [comment]
Just tested locally the steps from the description
```sh
$ awslocal s3api create-bucket --bucket test
{
    "Location": "http://test.s3.localhost.localstack.cloud:4566/"
}

$ awslocal s3api put-object --bucket test --key source.txt --body /tmp/testFile.txt

{
    "ETag": "\"f02e326f800ee26f04df7961adbf7c0a\""
}

$ awslocal s3api copy-object --copy-source '/test/source.txt' --bucket test --key dest.txt --ssekms-key-id $KEY --server-side-encryption aws:kms

{
    "ServerSideEncryption": "aws:kms",
    "SSEKMSKeyId": "f1fec580-3583-4518-9086-9cf4c864abbe",
    "CopyObjectResult": {
        "ETag": "\"f02e326f800ee26f04df7961adbf7c0a\"",
        "LastModified": "2021-11-23T12:58:49.000Z"
    }
}
```
Looks good. Once again thank you.
