### ISSUE TITLE
ExtendedS3DestinationConfiguration not supported to set S3 destination on Firehose stream

### ISSUE THREAD

**Issue by MerelCHT** [localstack/localstack#496]
When creating a new firehose stream it's not possible to set an S3 destination using the `.withExtendedS3DestinationConfiguration()` method. Currently, you have to use `.withS3DestinationConfiguration()`, but this method has been deprecated. Could you please update the code to support the new ExtendedS3DestinationConfiguration?

**Comment by whummer** [comment]
Thanks for reporting @MerelCHT . Can you please provide a few more details about this issue. How exactly did you start LocalStack? I'm assuming you are referring to the Java AWS SDK when you mention `withExtendedS3DestinationConfiguration()`?

When you say it's not possible to use this method - did you receive a particular error/exception in your client program upon execution? Can you please share the error details: (1) the error output from your client program, as well as (2) any relevant output from the LocalStack process.

Ideally, if you could post a small self-contained code snippet to reproduce the issue, that would be great. Thanks

**Comment by MerelCHT** [comment]
I'm using LocalStack with docker compose, so starting it with `docker-compose up`. I am using it for testing, where the expectation is that when I publish data to the firehose stream, it should end up in the S3 bucket I've set as the firehose destination. However when setting up the firehose stream as follows: 

    val firehoseClient = AmazonKinesisFirehoseClient.builder()
      .withEndpointConfiguration(new 
         AwsClientBuilder.EndpointConfiguration("http://localhost:4573", "eu-west-1"))
      .withCredentials(new AWSStaticCredentialsProvider(new BasicAWSCredentials("foo", "bar")))
      .build()

    private def createFirehoseStream(
     stream: String,
     s3BucketArn: String,
     prefix: String,
     bufferIntervalInSeconds: Int = 60) = {

    val s3DestinationConfiguration = new ExtendedS3DestinationConfiguration()
      .withPrefix(prefix)
      .withBucketARN(s3BucketArn)
      .withRoleARN("arn:aws:iam::12345:role/firehose_delivery_role")
      .withBufferingHints(new BufferingHints().withIntervalInSeconds(bufferIntervalInSeconds))

    val createDeliveryStreamRequest = new CreateDeliveryStreamRequest()
      .withDeliveryStreamName(stream)
      .withExtendedS3DestinationConfiguration(s3DestinationConfiguration)
    firehoseClient.createDeliveryStream(createDeliveryStreamRequest) }

And calling it like this: `createFirehoseStream("firehose-test-stream", "arn:aws:s3:::test-bucket", "test")`

I couldn't get my tests to pass. I didn't get any errors but when I ran the following command `aws firehose --endpoint http://localhost:4573 describe-delivery-stream --delivery-stream-name firehose-test-stream` The result was this:

`
{
    "DeliveryStreamDescription": {
        "HasMoreDestinations": false,
        "VersionId": "1",
        "CreateTimestamp": 1513073666.549834,
        "DeliveryStreamARN": "arn:aws:firehose:eu-west-1:000000000000:deliverystream/firehose-test-stream",
        "DeliveryStreamStatus": "ACTIVE",
        "DeliveryStreamName": "firehose-test-stream",
        "Destinations": []
    }
}
`

So clearly no S3 destination was set. (In the web UI I could also see that the firehose stream wasn't connected to the S3 bucket). When I then changed it to use the deprecated `.withS3DestinationConfiguration()` I found that it did create the destination correctly. 

I hope this is enough information, but let me know if you need anything else.

**Comment by akashgoel1197** [comment]
I am facing the same issues is the issue resolved ??

**Comment by awsmsrc** [comment]
I'm also seeing this behavior

**Comment by JonSEng** [comment]
I'm seeing this also (tested today) with scalatest using `"org.testcontainers" % "localstack" % "1.12.2"`

**Comment by taylorperkins** [comment]
Also having the same issue. 
```bash
>> awslocal --version
aws-cli/1.16.183 Python/3.7.3 Darwin/18.7.0 botocore/1.12.173
```

docker-compose.yaml
```yaml
version: '3.2'
services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack_demo
    ports:
      - '4563-4599:4563-4599'
      - '8055:8080'
    environment:
      - SERVICES=lambda,dynamodb,dynamodbstreams,kinesis,firehose,s3,iam,sts
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - LAMBDA_EXECUTOR=docker
    volumes:
      - './.localstack:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
```

Assuming that anything like `$TEXT` is treated as a variable, I have a firehose delivery stream config file like the following
```json
{
    "DeliveryStreamName": "$FIREHOSE_STREAM_NAME",
    "DeliveryStreamType": "DirectPut",
    "ExtendedS3DestinationConfiguration": {
        "RoleARN": "$ROLE_ARN",
        "BucketARN": "arn:aws:s3:::$S3_BUCKET_NAME",
        "Prefix": "$PROCESSED_PREFIX",
        "ErrorOutputPrefix": "$ERROR_PREFIX",
        "BufferingHints": {
          "SizeInMBs": 5,
          "IntervalInSeconds": 60
        },
        "CompressionFormat": "UNCOMPRESSED",

        "CloudWatchLoggingOptions": {
          "Enabled": true,
          "LogGroupName": "web_analytics",
          "LogStreamName": "web_analytics_firehose_data_success"
        },
        "ProcessingConfiguration": {
            "Enabled": true,
            "Processors": [
                {
                    "Type": "Lambda",
                    "Parameters": [
                        {
                            "ParameterName": "LambdaArn",
                            "ParameterValue": "$PROCESSING_FUNCTION_ARN"
                        },
                        {
                            "ParameterName": "NumberOfRetries",
                            "ParameterValue": "3"
                        }
                    ]
                }
            ]
        },
        "S3BackupMode": "Enabled",
        "S3BackupConfiguration": {
            "RoleARN": "$ROLE_ARN",
            "BucketARN": "arn:aws:s3:::$S3_BUCKET_NAME",
            "Prefix": "$PROCESSED_PREFIX",
            "ErrorOutputPrefix": "$ERROR_PREFIX",
            "BufferingHints": {
              "SizeInMBs": 5,
              "IntervalInSeconds": 60
            },
            "CompressionFormat": "UNCOMPRESSED",

            "CloudWatchLoggingOptions": {
              "Enabled": true,
              "LogGroupName": "web_analytics",
              "LogStreamName": "web_analytics_firehose_data_backup"
            }
        }
    }
}
```

Lambda function exists, S3 bucket exists with their appropriate keys. Running:
```bash
>> awslocal firehose create-delivery-stream --cli-input-json file://config.json
```
☝️ does not produce an error, but outputs the arn as expected. Running:
```bash
>> awslocal firehose describe-delivery-stream --delivery-stream-name ${FIREHOSE_STREAM_NAME}
{
    "DeliveryStreamDescription": {
        "DeliveryStreamName": "firehoseDeliveryStream",
        "DeliveryStreamARN": "arn:aws:firehose:us-east-1:000000000000:deliverystream/firehoseDeliveryStream",
        "DeliveryStreamStatus": "ACTIVE",
        "DeliveryStreamType": "DirectPut",
        "VersionId": "1",
        "CreateTimestamp": 1576096422.7296188,
        "Destinations": [],
        "HasMoreDestinations": false
    }
}
```
Note that the `Destinations` key is empty. 

Like others have mentioned already, using `S3DestinationConfiguration` works fine. 
My main reason for using the `ExtendedS3DestinationConfiguration` is to implement a lambda function as a Processor. 

@whummer I would love to see this implemented! Would be happy to do any additional testing / triaging to get this moving. Thanks!

**Comment by DorBashan** [comment]
I'm also experiencing the same issue with [python localstack](https://github.com/mintel/pytest-localstack)

**Comment by mrsufgi** [comment]
@taylorperkins same - ```ExtendedS3DestinationConfiguration``` not working but ```S3DestinationConfiguration``` does not :( 

probably never implemented :(

**Comment by mrsufgi** [comment]
@whummer I just dug a little into the source code. 

https://github.com/localstack/localstack/blob/f384f5837caad840201258a3d94e19d4bf68571f/localstack/services/firehose/firehose_api.py#L83

I believe that supporting all ExtendedS3DestinationConfiguration would be a lot of work, but for a happy path integration with Lambda, It could easily be implemented with help from 

https://github.com/localstack/localstack/blob/77d4061526741d9063d388de0a183347b5d9c428/tests/integration/test_lambda.py#L187

probably sending the ```data``` into the lambda and pass the response to as the new "converted" data as an S3Object. 

probably more complex then that, but its a start :)

**Comment by whummer** [comment]
Thanks for digging into this issue @mrsufgi @DorBashan @taylorperkins @JonSEng @awsmsrc @akashgoel1197 @MerelCHT . Rudimentary initial support for `ExtendedS3DestinationConfiguration` has been added in #2068 - can you please give it a try with the `latest` version of the Docker image. Please report here if the problem persists or if there are any other issues. Thanks
