### ISSUE TITLE
bug: s3 `Location` paramter for `samlocal package` followed by `samlocal deploy` isn't usable

### ISSUE THREAD

**Issue by BatmanAoD** [localstack/localstack#4965]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I use `samlocal package` to process a CloudFormation template, then `samlocal deploy` to deploy the template, any `Location` parameters referring to local files break the deploy process.

`sam` replaces these local paths with s3 URIs, but uses `https://s3...` rather than `s3://...` to do so. When using `localstack`, the URIs appear to be valid (e.g. I can use `wget <URI>` to create a copy of the hosted file).

However, `samlocal deploy` gives an error like this:

```
Error: Unable to upload artifact http://localhost:4566/aws-sam-cli-managed-default-samclisourcebucket-d3541a59/<checksum>.template referenced by Location parameter of <name> resource.
Location parameter of <name> resource is invalid. It must be a S3 URL or path to CloudFormation template file. Actual: <localpath>/http:/localhost:4566/aws-sam-cli-managed-default-samclisourcebucket-d3541a59/<checksum>.template
```

(This example uses `--resolve-s3` for both `package` and `deploy`. `<localpath>` is the parent folder containing my original CloudFormation template. `<name>` and `<checksum>` are arbitrary.)

If I manually replace the `https://s3` URIs in the exported CloudFormation file created by `samlocal package` with `s3://` URIs, the deployment appears to get further (though I then run into another issue, #4964).

### Expected Behavior

The `https://s3` paths are used successfully to deploy the stack.

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    USE_LIGHT_IMAGE=0
    DATA_DIR=<some path>
    LOCALSTACK_API_KEY=<key>

    export USE_LIGHT_IMAGE DATA_DIR LOCALSTACK_API_KEY
    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```
samlocal package \
        --region us-west-2 \
        --resolve-s3 \
        --template-file template.yml \
        --output-template-file template-export.yml
        
samlocal deploy         --template-file template-export.yml \
                        --stack-name <elided> \
                        --region us-west-2 \
                        --resolve-s3 \
                        --capabilities "CAPABILITY_NAMED_IAM" "CAPABILITY_AUTO_EXPAND" \
                        --parameter-overrides <elided>
```

### Environment

```markdown
- OS: Ubuntu 20.04.3 on WSL (5.10.60.1-microsoft-standard-WSL2, Windows 11 host)
- LocalStack: 0.13.0
```

### Anything else?

I can't share my template files, but if necessary I can try to craft a minimal example.

**Comment by dominikschubert** [comment]
@BatmanAoD 

> I can't share my template files, but if necessary I can try to craft a minimal example.

That'd be awesome if you could do that and would definitely help us a lot in getting this fixed soon :+1:

**Comment by BatmanAoD** [comment]
Okay, I've reproduced it with a very simple example. The `data` directory was used as `DATA_DIR`, and the `cf` directory contains the parent template (`template.yml`) and nested template (`nested/template.yml`). `cf/deploy_failure.log` shows the invocations I used and the terminal output. 

[nested_failure.tar.gz](https://github.com/localstack/localstack/files/7573457/nested_failure.tar.gz)

**Comment by BatmanAoD** [comment]
As you can see from the example, I am using the `AWS::Serverless-2016-10-31` transform, which the documentation says is supported.

**Comment by BatmanAoD** [comment]
@dominikschubert did you see my example above?

**Comment by bamajap** [comment]
@dominikschubert 
This is still happening with aws-sam-cli-local v1.55.0.

I ran into this same problem, so I tried it with the small example files provided above and it's the same exact behavior as if no changes were made.  Please advise.
