### ISSUE TITLE
bug: Unable to delete buckets

### ISSUE THREAD

**Issue by bep0st** [localstack/localstack#4974]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I can create/read buckets, upload/read/delete files but I can't delete buckets. If I try to delete a bucket I get the following error:

`remove_bucket failed: s3://test An error occurred (500) when calling the DeleteBucket operation (reached max retries: 2): Internal Server Error`

### Expected Behavior

It is possible to delete buckets.

### How are you starting LocalStack?

With a docker-compose file

#### docker-compose.yml
```
...
localstack:
    image: localstack/localstack:latest
    ports:
      - '4566:4566'
    environment:
      - AWS_DEFAULT_REGION=eu-central-1
      - SERVICES=s3
      - DEBUG=1
      - EDGE_PORT=4566
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - './localstack:/tmp/localstack'
...
```

#### Client commands

aws --endpoint-url=http://localhost:4566 s3 mb s3://test
aws --endpoint-url=http://localhost:4566 s3 rb s3://test --force    

### Environment

```markdown
- Host-OS: Windows
- Docker-OS: Linux
- LocalStack: latest
```

**Comment by mgagliardo** [comment]
Hello @bep0st, can you please show me your debug code output? I could not reproduce this issue on my machine:

docker-compose.yml:
```
localstack:
    image: localstack/localstack:latest
    ports:
      - '4566:4566'
    environment:
      - AWS_DEFAULT_REGION=eu-central-1
      - SERVICES=s3
      - DEBUG=1
      - EDGE_PORT=4566
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - './localstack:/tmp/localstack'
```

output:
```
$ aws --profile=localstack  --endpoint-url=http://localhost:4566 s3 rb s3://test
remove_bucket: test

$ aws --profile=localstack  --endpoint-url=http://localhost:4566 s3 mb s3://test
make_bucket: test

$ aws --profile=localstack  --endpoint-url=http://localhost:4566 s3 mb s3://test-1
remove_bucket: test-1

$ aws --profile=localstack  --endpoint-url=http://localhost:4566 s3 rb s3://test-1 --force
remove_bucket: test-1

$ aws --profile=test   --endpoint-url=http://localhost:4566 s3 mb s3://test-2
make_bucket: test-2

$ aws --profile=test   --endpoint-url=http://localhost:4566 s3 rb s3://test-2
remove_bucket: test-2
```

**Comment by bep0st** [comment]
Hello @mgagliardo 
Do you mean the docker logs?

**Comment by mgagliardo** [comment]
Yes, that would be ok, do you see anything relevant?

**Comment by bep0st** [comment]
Hello @mgagliardo 
Here is my [docker.log](https://github.com/localstack/localstack/files/7575167/docker.log). I hope it is helpfull. Thanks for your support.

**Comment by mgagliardo** [comment]
Hello @bep0st I can see there are some weird SSL related errors on top of the file and I don't see the same on my run:

```
{"log":"2021-11-20T20:13:16.879:INFO:bootstrap.py: Execution of \"prepare_environment\" took 620.13ms\n","stream":"stdout","time":"2021-11-20T20:13:17.5981102Z"}
{"log":"2021-11-20T20:13:16.941:INFO:localstack_ext.bootstrap.install: Unable to download Github artifact from from https://cdn.jsdelivr.net/gh/localstack/localstack-artifacts@master/local-certs/server.key to /tmp/localstack/server.test.pem: MyHTTPSConnectionPool(host='cdn.jsdelivr.net', port=443): Max retries exceeded with url: /gh/localstack/localstack-artifacts@master/local-certs/server.key (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1131)'))) Traceback (most recent call last):\n","stream":"stdout","time":"2021-11-20T20:13:17.5981146Z"}
```

Can you please try running a plain docker run like this and let me know if it keeps happening to you?
`docker run -ti -e DEBUG=1 --rm --name localstack -p 4566:4566 localstack/localstack:latest`

**Comment by bep0st** [comment]
Hello @mgagliardo 
Unfortunately, same behavior (see [docker2.log](https://github.com/localstack/localstack/files/7575579/docker2.log)). It is strange that this only happens if I try to delete the bucket. All other operations work.

**Comment by bep0st** [comment]
Ok, I found out that the bucket was deleted after all, but the application stops executing due to an internal crash. My current workaround is to restart the Docker container :(.

**Comment by mgagliardo** [comment]
@bep0st can you try a cleanup of your local folder or restarting the system? Also does the error output have any difference with what you shared before?

**Comment by bep0st** [comment]
@mgagliardo I have deleted my local folder and changed the docker-compose.yml to

localstack:
    image: localstack/localstack:latest-amd64
    ports:
      - '4566:4566'
    environment:
      - AWS_DEFAULT_REGION=eu-central-1
      - SERVICES=s3
      - DEBUG=1
      - EDGE_PORT=4566
      
Finally I have restarted the container but same issue again.

**Comment by mgagliardo** [comment]
Have you tried restarting your system? It is very weird it is trying to connect to your internal host port 3128. As you are using windows I guess this has something to do with your docker engine running on the windows VM. Can you try restarting the service as well?

**Comment by bep0st** [comment]
I have restarted my windows, docker and the container several times. My Docker is running with WSL2.

**Comment by naspeh** [comment]
Hi @bep0st, 

> I was wrong here. The problem is that the buckets aren't persistent even though I have configure `DATA_DIR=/tmp/localstack/data`

We have this warning:
> WARNING:localstack.services.infra: Persistence mechanism for community services (based on API calls record&replay) will be deprecated in 0.13.0

To enable the persistence mechanism based on API calls record&replay, you should add `EAGER_SERVICE_LOADING=1` as well for now.

I can't reproduce the original issue with `Failed to connect to proxy URL: "http://host.docker.internal:3128"` though yet.

**Comment by mgagliardo** [comment]
Considering this as closed for now. I have tested this and could not reproduce on 1 windows, 2 linux and 1 mac machine and we have have not received any other reports related.
If you have any other comments feel free to add them here or open a new issue. Cheers!

**Comment by bep0st** [comment]
Hello @naspeh  and @mgagliardo 
I have downloaded the latest version 0.13.0.7. Unfortunately, I have the same issue again but I found the following message in the logs:
`{"log":"2021-11-25T16:20:55.604:WARNING:localstack.utils.server.http2_server: Error in proxy handler for request DELETE http://localhost:4566/new-bucket-03d1c977/: maximum recursion depth exceeded in comparison Traceback (most recent call last):\n","stream":"stdout","time":"2021-11-25T16:20:56.4805965Z"}`
Could you explain me why this log entry appears? What it the reason?

**Comment by naspeh** [comment]
Hi @bep0st,

Could you please add `LS_LOG=trace` to your environment vars and repeat your case. Then share the full log.

It's hard to say something by just this message `maximum recursion depth exceeded in comparison Traceback`

**Comment by bep0st** [comment]
Hello @naspeh 
Here my [docker3.log](https://github.com/localstack/localstack/files/7604503/docker3.log)

**Comment by naspeh** [comment]
Could you please specify also?
```
AWS_DEFAULT_REGION=us-east-1
```
And try again.

Also please share your `AWS region` that you use with `aws --profile=localstack`

**Comment by naspeh** [comment]
this is the loop in  `botocore`:
```
{"log":"  File \"/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/utils.py\", line 1432, in get_bucket_region\n","stream":"stdout","time":"2021-11-25T17:00:30.4135882Z"}
{"log":"    response = self._client.head_bucket(Bucket=bucket)\n","stream":"stdout","time":"2021-11-25T17:00:30.4135915Z"}
{"log":"  File \"/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py\", line 391, in _api_call\n","stream":"stdout","time":"2021-11-25T17:00:30.4135947Z"}
{"log":"    return self._make_api_call(operation_name, kwargs)\n","stream":"stdout","time":"2021-11-25T17:00:30.413598Z"}
{"log":"  File \"/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py\", line 705, in _make_api_call\n","stream":"stdout","time":"2021-11-25T17:00:30.4136014Z"}
{"log":"    http, parsed_response = self._make_request(\n","stream":"stdout","time":"2021-11-25T17:00:30.4136052Z"}
{"log":"  File \"/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py\", line 725, in _make_request\n","stream":"stdout","time":"2021-11-25T17:00:30.4136125Z"}
{"log":"    return self._endpoint.make_request(operation_model, request_dict)\n","stream":"stdout","time":"2021-11-25T17:00:30.4136171Z"}
{"log":"  File \"/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/endpoint.py\", line 102, in make_request\n","stream":"stdout","time":"2021-11-25T17:00:30.4136206Z"}
{"log":"    return self._send_request(request_dict, operation_model)\n","stream":"stdout","time":"2021-11-25T17:00:30.4136248Z"}
{"log":"  File \"/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/endpoint.py\", line 136, in _send_request\n","stream":"stdout","time":"2021-11-25T17:00:30.4136282Z"}
{"log":"    while self._needs_retry(attempts, operation_model, request_dict,\n","stream":"stdout","time":"2021-11-25T17:00:30.4136317Z"}
{"log":"  File \"/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/endpoint.py\", line 252, in _needs_retry\n","stream":"stdout","time":"2021-11-25T17:00:30.4136349Z"}
{"log":"    responses = self._event_emitter.emit(\n","stream":"stdout","time":"2021-11-25T17:00:30.4136384Z"}
{"log":"  File \"/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/hooks.py\", line 357, in emit\n","stream":"stdout","time":"2021-11-25T17:00:30.4136427Z"}
{"log":"    return self._emitter.emit(aliased_event_name, **kwargs)\n","stream":"stdout","time":"2021-11-25T17:00:30.4136462Z"}
{"log":"  File \"/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/hooks.py\", line 228, in emit\n","stream":"stdout","time":"2021-11-25T17:00:30.4136492Z"}
{"log":"    return self._emit(event_name, kwargs)\n","stream":"stdout","time":"2021-11-25T17:00:30.4136526Z"}
{"log":"  File \"/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/hooks.py\", line 211, in _emit\n","stream":"stdout","time":"2021-11-25T17:00:30.413656Z"}
{"log":"    response = handler(**kwargs)\n","stream":"stdout","time":"2021-11-25T17:00:30.4136636Z"}
{"log":"  File \"/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/utils.py\", line 1375, in redirect_from_error\n","stream":"stdout","time":"2021-11-25T17:00:30.4136808Z"}
{"log":"    new_region = self.get_bucket_region(bucket, response)\n","stream":"stdout","time":"2021-11-25T17:00:30.4136842Z"}
{"log":"  File \"/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/utils.py\", line 1432, in get_bucket_region\n","stream":"stdout","time":"2021-11-25T17:00:30.4136874Z"}
```

Where it tries to retrieve `get_bucket_region` and fails for some reason.

This is why I think specifying `AWS_DEFAULT_REGION=us-east-1` could potentially help.

@bep0st please let us know about your tries.

**Comment by bep0st** [comment]
Hello @naspeh 

// docker-compose.yml
```
  localstack:
    image: localstack/localstack:latest-amd64
    ports:
      - '4566:4566'
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - SERVICES=s3
      - DEBUG=1
      - EDGE_PORT=4566
      - DATA_DIR=/tmp/localstack/data
      - EAGER_SERVICE_LOADING=1
      - LS_LOG=trace
    volumes:
      - './localstack:/tmp/localstack'
      - '//var/run/docker.sock:/var/run/docker.sock'
```

// aws config
```
[default]
region = us-east-1
[profile localstack]
region = us-east-1
```

// aws credentials
```
[default]
aws_access_key_id = test
aws_secret_access_key = test
[localstack]
aws_access_key_id = test
aws_secret_access_key = test
```

// S3 Browser Configuration
![image](https://user-images.githubusercontent.com/77197673/143490228-a41bd863-2d44-4950-a45d-7a2f657f0009.png)

Thanks for your support!

**Comment by naspeh** [comment]
With all these settings, do you still get `maximum recursion depth exceeded` error?

Please share once again your logs.

**Comment by bep0st** [comment]
Hello @naspeh 

Yes, still same issue. 

Steps to reproduce:
1. aws s3 --endpoint-url http://localhost:4566 --profile localstack mb s3://test 
    make_bucket: test
2. aws s3 --endpoint-url http://localhost:4566 --profile localstack rb s3://test
    remove_bucket failed: s3://test An error occurred (500) when calling the DeleteBucket operation (reached max retries: 2): Internal Server Error
  
Here is my [docker4.log](https://github.com/localstack/localstack/files/7605535/docker4.log)
