### ISSUE TITLE
question: Does the s3 service work with multipart uploads

### ISSUE THREAD

**Issue by ThrowsException** [localstack/localstack#5016]
### Is there an existing issue for this?

- [X] I have searched the existing issues and read the documentation

### Question

Im currently using the v3 s3 client and the Upload lib to do a multipart upload of a csv file. I was looking to test this locally with localstack but I'm getting `getaddrinfo ENOTFOUND` when trying to run my code. Ive recreated the issue using this 

```ts
import { S3Client, CreateBucketCommand } from '@aws-sdk/client-s3';
import { Upload } from '@aws-sdk/lib-storage';

const s3 = new S3Client({ endpoint: 'http://localhost:4566' });
const bucketCommand = new CreateBucketCommand({ Bucket: 'testbucket' });
s3.send(bucketCommand); // This part works fine I can see the bucket is created

const upload = new Upload({
  client: s3,
  params: {
    Bucket: 'testbucket',
    Key: 'foo',
    Body: 'test,foo',
    ContentType: 'text/csv',
  },
});

upload.done().then(console.log).catch(console.error);  
```

```
Error: getaddrinfo ENOTFOUND testbucket.localhost
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'testbucket.localhost',
  '$metadata': { attempts: 1, totalRetryDelay: 0 }
}
```

Even if the bucket already exists and I just run the `Upload` part I get the same error.

**Comment by ThrowsException** [comment]
Immediately after posting I found this related to java https://insignificantbit.com/how-to-upload-to-aws-s3/. I found a similar way to do this in the node sdk using the`forcePathStyle` config https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-s3/interfaces/s3clientconfig.html#forcepathstyle

That seems to switch from using some kind of dns entry to using the endpoint url + the bucket/key 

success response 
```
{
  '$metadata': {
    httpStatusCode: 200,
    requestId: 'S9RR1RHROPZBDY2V8LU7819API3SRDT3EL34770XFSYI7EGR68U6',
    extendedRequestId: 'MzRISOwyjmnupFEE2F881B771FD9A7/JypPGXLh0OVFGcJaaO3KW/hRAqKOpIEEp',
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  },
  Bucket: 'testbucket',
  BucketKeyEnabled: undefined,
  ETag: '"830ae6040e6bb520b8f9dea8f64f47cf-1"',
  Expiration: undefined,
  Key: 'foo',
  Location: 'http://localhost:4566/testbucket/foo',
  RequestCharged: undefined,
  SSEKMSKeyId: undefined,
  ServerSideEncryption: undefined,
  VersionId: 'null'
}
```

This seems to fix my issue but is there another way of handling this? I'd prefer the tests and the code not switch between how they are accessing buckets but at least this is a workaround for now.

**Comment by whummer** [comment]
Thanks for reporting @ThrowsException . Can you please confirm if it works when you set `s3.localhost.localstack.cloud` as the endpoint hostname? Thanks

```
const s3 = new S3Client({ endpoint: 'http://s3.localhost.localstack.cloud:4566' });
```

**Comment by ThrowsException** [comment]
@whummer that does appear the work. is that a docker thing exposing the `s3.localhost.localstack.cloud` or is that something the underlying webserver is doing?

**Comment by naspeh** [comment]
we have dns record for `s3.localhost.localstack.cloud` and `*.s3.localhost.localstack.cloud` that points to 127.0.0.1 :) and `localstack` server in you docker container can handle these domains.

I think we can close this issue, if there is something else left, please let us know.

@ThrowsException thank you for reporting once again.

**Comment by ThrowsException** [comment]
@naspeh Im still a little confused though. What should be the expected way to set the endpoint attribute for aws clients? should `localhost` be avoided and one of the DNS entries used instead?  It seems jarring to be able to use localhost:4566 for everything except here and you have to dig into the source or run some trial and error to know what URL the client is actually trying to use.

**Comment by whummer** [comment]
Hi @ThrowsException , please note that this is a peculiarity of the S3 API - it defines two bucket addressing styles, path-based addressing and hostname-based addressing, see here: https://docs.aws.amazon.com/AmazonS3/latest/userguide/VirtualHosting.html

Since using subdomains for `localhost` does not work in most environments, the S3 SDK clients need to be created a bit differently.

There's basically two options:
* Setting `forcePathStyle=true`, as you indicated in your first post 
* Setting `s3.localhost.localstack.cloud` as the endpoint URL, which will then work with the default hostname-based addressing

Hope that helps - please keep us posted how it goes.. Thanks!
