### ISSUE TITLE
bug: DynamoDB Stream Lambdas fail because no "SequenceNumber" field in event

### ISSUE THREAD

**Issue by toadzky** [localstack/localstack#5018]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have a rust lambda running using the `provided.al2` runtime and the `docker` lambda executor. When I update my dynamo table, the lambda invokes but the event has an incorrect structure and the lambda throws an error parsing the event payload. The error from the lambda container is 

```
Error: Error("missing field `SequenceNumber`", line: 1, column: 1022)
```

Here's a copy of the `AWS_LAMBDA_EVENT_BODY` set by localstack: 

```json

{
    "Records": [
        {
            "eventID": "79ac67bf",
            "eventVersion": "1.1",
            "dynamodb": {
                "ApproximateCreationDateTime": 1637948167.023251,
                "SizeBytes": 722,
                "Keys": {
                    ...
                },
                "NewImage": {
                    ....
                },
                "StreamViewType": "NEW_AND_OLD_IMAGES"
            },
            "awsRegion": "test-region",
            "eventSource": "aws:dynamodb",
            "eventName": "INSERT",
            "eventSourceARN": "arn:aws:dynamodb:test-region:000000000000:table/k4JV6xP4"
        }
    ]
}
```

### Expected Behavior

The lambda should invoke with a correctly structured event, as [defined by AWS](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_streams_StreamRecord.html). Here's an example from [the official tutorial](url) (highlighting by me): 

```json
{
    "Records": [
        {
            "eventID": "7de3041dd709b024af6f29e4fa13d34c",
            "eventName": "INSERT",
            "eventVersion": "1.1",
            "eventSource": "aws:dynamodb",
            "awsRegion": "region",
            "dynamodb": {
                "ApproximateCreationDateTime": 1479499740,
                "Keys": {
                    ...
                },
                "NewImage": {
                    ...
                },
                *"SequenceNumber": "13021600000000001596893679",*
                "SizeBytes": 112,
                "StreamViewType": "NEW_IMAGE"
            },
            "eventSourceARN": "arn:aws:dynamodb:region:123456789012:table/BarkTable/stream/2016-11-16T20:42:48.104"
        }
    ]
}
```

### How are you starting LocalStack?

Custom (please describe below)

### Steps To Reproduce

I'm using the Java library `testcontainers` to spin up localstack and I'm using the standard Java SDK clients to interact with it. Everything seems to wire up correctly, but the event given to the lambda is wrong.

### Environment

```markdown
- OS: Linux (Ubuntu 21.04)
- LocalStack: tested with 0.13.0.4
```

### Anything else?

While this showed up on a provided lambda, digging through the code it seems like a sequence number is assigned when pushed to the dyanmodbstreams system, but not when pushed directly to the lambda system. i have no idea why this would be, since in the real aws, i'm pretty sure lambda polls the dynamostreams api, so i don't understand the short-circuit with an unfinished event.

This showed up for me with rust, but I'm pretty sure the issue is basically avoided by other languages have relaxed rules on the parsing - meaning it doesn't validate that all required fields are actually present or it's a scripting language that doesn't verify structure at all.

**Comment by whummer** [comment]
Thanks for reporting @toadzky . This should be fixed in #5186 - can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists.. Thanks!
