### ISSUE TITLE
bug: "No rule to make target 'infra'."

### ISSUE THREAD

**Issue by src-r-r** [localstack/localstack#5020]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Localstack services to not start.
```
localstack_main | Waiting for all LocalStack services to be ready
localstack_main | 2021-11-28 00:32:54,572 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
localstack_main | 2021-11-28 00:32:54,574 INFO supervisord started with pid 14
localstack_main | 2021-11-28 00:32:55,576 INFO spawned: 'dashboard' with pid 20
localstack_main | 2021-11-28 00:32:55,578 INFO spawned: 'infra' with pid 21
localstack_main | 2021-11-28 00:32:55,581 INFO success: dashboard entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
localstack_main | 2021-11-28 00:32:55,581 INFO exited: dashboard (exit status 0; expected)
localstack_main | 2021-11-28 00:32:55,582 INFO exited: infra (exit status 2; not expected)
localstack_main | make: *** No rule to make target 'infra'.  Stop.
localstack_main | 2021-11-28 00:32:56,585 INFO spawned: 'infra' with pid 22
localstack_main | 2021-11-28 00:32:56,589 INFO exited: infra (exit status 2; not expected)
localstack_main | make: *** No rule to make target 'infra'.  Stop.
localstack_main | 2021-11-28 00:32:58,593 INFO spawned: 'infra' with pid 23
localstack_main | 2021-11-28 00:32:58,597 INFO exited: infra (exit status 2; not expected)
```

As expected, this is confirmed by the inability for aws to connect to the endpoint:

```
> aws --endpoint-url=http://localhost:4566 s3 ls                                                             

Connection was closed before we received a valid response from endpoint URL: "http://localhost:4566/".
```

### Expected Behavior

I expect no error messages present, for localstack to be running, and for aws to connect to the s3 services on localstack.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker-compose up

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    aws --endpoint-url=http://localhost:4566 s3 ls   

### Environment

```markdown
- OS: Ubuntu 20.04
- LocalStack: latest, as well as 0.12.5 (as recommended by [issue 3939](https://github.com/localstack/localstack/issues/3939) )
```

### Anything else?

I ran across this SO post regarding the CRIT message:

https://stackoverflow.com/questions/63608075/userwarning-supervisord-is-running-as-root-and-it-is-searching-for-its-configur

I made the mistake previously of cloning the localstack repo and trying to bug squash my way to a successful startup. Is there a file that I can copy & mount in docker-compose as an easy workaround.

Relevant section of docker-compose.yml:

```
  localstack:
    restart: always
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    # Use version 0.12.5 https://github.com/localstack/localstack/issues/3939
    image: "localstack/localstack:0.12.5"
    network_mode: bridge
    ports:
      - '4566-4583:4566-4583'
    environment:
      - EAGER_SERVICE_LOADING=1
      - SERVICES=
      - "SERVICES=${SERVICES:-s3,iam,infra}"
      - DEBUG=${DEBUG:-1}
      - DATA_DIR=${DATA_DIR:-/tmp/localstack/data}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR:-docker}
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY:-0.01}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEFAULT_REGION=${DEFAULT_REGION:-us-east-1}
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - HOST_TMP_FOLDER=${TMPDIR:-/tmp/}localstack
      - EDGE_PORT=4566
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - TEST_S3_BUCKET_NAME=${TEST_S3_BUCKET_NAME}
      - TEST_SFTP_USERNAME=${TEST_SFTP_USERNAME}
      - TEST_SFTP_PASSWORD=${TEST_SFTP_PASSWORD}
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./docker/localstack:/opt/code/localstack"
```

**Comment by thrau** [comment]
Thanks for the report Jordan @src-r-r, could you please run localstack with `DEBUG=1` and post the full startup log?

**Comment by thrau** [comment]
i just saw that you are mounting the `"./docker/localstack` into `/opt/code/localstack`". that's not something we can support, since you are overwriting the entire source folder of the container with whatever is in `./docker/localstack`.

is there any particular reason why you need this? maybe we can find a better solution for what you are trying to do.

**Comment by src-r-r** [comment]
Whoops. Thanks, @thrau 
I was running into startup issues (that ended up being an issue with permissions--docker on Linux 🙄). I had forgotten and was overriding the code by mounting this git repo as a volume in order to diagnose the issue.
After realizing it was a permission issue and not an issue with the code base (which was a nightmare to get going anyway--ran into a corner) I had forgotten to remove that volume mount line. After removing it and restarting, everything started working.
