### ISSUE TITLE
bug: Query param containing the word 'Signature' in an API Gateway request causes an error

### ISSUE THREAD

**Issue by janczarn** [localstack/localstack#5041]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have set up an API Gateway with a Lambda integration. I am able send GET requests to the API like so:

`curl "http://localhost:4566/restapis/<api_id>/dev/_user_request_/test?testParam=1"`

and the expected response is received. If I include the query param 'Signature' (case sensitive) like so:

`curl "http://localhost:4566/restapis/<api_id>/dev/_user_request_/test?Signature=1"`

The following response will be received (if S3 is enabled - if S3 is not enabled, LocalStack displays an error complaining that S3 is not enabled):

`<?xml version="1.0" encoding="utf-8"?>
<Error><Code>AccessDenied</Code><Message>Query-string authentication requires the Signature, Expires and AWSAccessKeyId parameters</Message><RequestId>59a1121d</RequestId><HostId>1a30763b</HostId></Error>`

If I include a query param that contains the word 'Signature' (case sensitive) like so:

`curl "http://localhost:4566/restapis/<api_id>/dev/_user_request_/test?TestSignature=1"`

The following response will be received (if S3 is enabled - if S3 is not enabled, LocalStack displays an error complaining that S3 is not enabled):

`<?xml version="1.0" encoding="UTF-8"?>
<Error>
    <Code>NoSuchBucket</Code>
    <Message>The specified bucket does not exist</Message>
    <BucketName>restapis</BucketName>
    <RequestID>7a62c49f-347e-4fc4-9331-6e8eEXAMPLE</RequestID>
</Error>`

In both cases the request is not sent to the Lambda function (i.e. no Lambda Docker container is started).

### Expected Behavior

The request should be sent to the Lambda function.

### How are you starting LocalStack?

With the `localstack` script

### Steps To Reproduce

`SERVICES=s3,lambda,apigateway LAMBDA_REMOTE_DOCKER=0 localstack start`

Example lambda code: [code.zip](https://github.com/localstack/localstack/files/7626861/code.zip)

`aws --endpoint-url http://localhost:4566 lambda create-function --function-name test --runtime nodejs14.x --code S3Bucket=__local__,S3Key=<code_dir> --handler index.handler --role Default`

`aws --endpoint-url http://localhost:4566 apigateway create-rest-api --name test`

`aws --endpoint-url http://localhost:4566 apigateway get-resources --rest-api-id <rest_api_id>`

`aws --endpoint-url http://localhost:4566 apigateway create-resource --rest-api-id <rest_api_id> --parent-id <parent_id> --path-part test`

`aws --endpoint-url http://localhost:4566 apigateway put-method --rest-api-id <rest_api_id> --resource-id <resource_id> --http-method ANY --authorization-type NONE`

`aws --endpoint-url http://localhost:4566 apigateway put-integration --rest-api-id <rest_api_id> --resource-id <resource_id> --http-method ANY --integration-http-method ANY --type AWS_PROXY --uri arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-west-1:000000000000:function:test/invocations`

`aws --endpoint-url http://localhost:4566 apigateway create-deployment --rest-api-id <rest_api_id> --stage-name dev`

To ensure it all works (should return 'hello' regardless of query params):

`curl "http://localhost:4566/restapis/c8hjip4ans/dev/_user_request_/test?somesignature=1"`

To reproduce the bug:

`curl "http://localhost:4566/restapis/c8hjip4ans/dev/_user_request_/test?Signature=1"`
`curl "http://localhost:4566/restapis/c8hjip4ans/dev/_user_request_/test?someSignature=1"`

### Environment

```markdown
- OS: Ubuntu 20.04
- LocalStack: latest
```

**Comment by naspeh** [comment]
@janczarn thank you for reporting  and the detailed description, I was able to reproduce it, I need to investigate it further and prepare a fix.

----

For more automated way of reproducing it I used this shell snipped
```sh
cat << "EOFROOT" | sh
set -eux
[ -d code ] || (
mkdir code
cat << "EOF" > code/index.js
exports.handler = async event => {
	return {
		statusCode: 200,
		body: 'hello'
	}
}
EOF
)

aws --endpoint-url http://localhost:4566 lambda create-function --function-name test --runtime nodejs14.x --code S3Bucket=__local__,S3Key=$(pwd)/code --handler index.handler --role Default

rest_api_id=$(aws --endpoint-url http://localhost:4566 apigateway create-rest-api --name test | jq -r .id)
[ -z "$rest_api_id" ] && false

parent_id=$(aws --endpoint-url http://localhost:4566 apigateway get-resources --rest-api-id $rest_api_id | jq -r .items[].id)
[ -z "$parent_id" ] && false

resource_id=$(aws --endpoint-url http://localhost:4566 apigateway create-resource --rest-api-id $rest_api_id --parent-id $parent_id --path-part test | jq -r .id)
[ -z "$resource_id" ] && false

aws --endpoint-url http://localhost:4566 apigateway put-method --rest-api-id $rest_api_id --resource-id $resource_id --http-method ANY --authorization-type NONE

aws --endpoint-url http://localhost:4566 apigateway put-integration --rest-api-id $rest_api_id --resource-id $resource_id --http-method ANY --integration-http-method ANY --type AWS_PROXY --uri arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:000000000000:function:test/invocations

aws --endpoint-url http://localhost:4566 apigateway create-deployment --rest-api-id $rest_api_id --stage-name dev

curl "http://localhost:4566/restapis/$rest_api_id/dev/_user_request_/test?somesignature=1"
curl "http://localhost:4566/restapis/$rest_api_id/dev/_user_request_/test?Signature=1"
curl "http://localhost:4566/restapis/$rest_api_id/dev/_user_request_/test?someSignature=1"
EOFROOT

```

**Comment by naspeh** [comment]
Once again thank you for reporting @janczarn, it should be fixed by https://github.com/localstack/localstack/pull/5062. Please try the latest docker image: `localstack/localstack:latest`.
