### ISSUE TITLE
Unable to find forwarding rule for hose when using SES

### ISSUE THREAD

**Issue by zachjbrowning** [localstack/localstack#5044]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm using localstack for SES, and attempting to send requests to it using the AWSSDK for .NET. I'm seeing this error:

```localstack     | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initaws.d/init.sh
localstack     |
localstack     | 2021-11-27T23:21:26.439:DEBUG:plugin.manager: instantiating plugin 
PluginSpec(localstack.aws.provider.ses:default = <function ses at 0x7efcec2e44c0>)
localstack     | 2021-11-27T23:21:26.439:DEBUG:plugin.manager: loading plugin localstack.aws.provider:ses:default
localstack     | 2021-11-27T23:21:26.467:INFO:localstack.services.infra: Starting mock SES service on http port 4566 ...
localstack     | 2021-11-27T23:21:26.468:INFO:localstack.services.motoserver: starting moto server on http://0.0.0.0:38063
localstack     | 2021-11-27T23:21:26.470:DEBUG:localstack.services.plugins: checking service health ses:38063
localstack     | 2021-11-27T23:21:44.364:INFO:localstack.services.edge: Unable to find forwarding rule for host "localhost:4566", path "POST /v2/email/outbound-emails", target header "", auth header "", data "b'{"Content":{"Simple":{"Body":{"Text":{"Data":"Some content"}},"Subject":{"Data":"Some subject"}}},..."
```

When I use the CLI instead of the SDK to send a similar request, I get no error and it returns a response from SES.

I am not running into the same issue with other localstack services, for instance I can happily query DynamoDB using the SDK with no issues, so it seems to be isolated to SES.

### Expected Behavior

I expected localstack to successfully return a response from SES, as it does when I use the CLI or send a request to dynamodb.

### How are you starting LocalStack?

Custom (please describe below)

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

I am using Batect (similar to docker-compose).  My container definition is as follows:
```  
localstack:
    image: localstack/localstack
    ports:
      - local: 4566
        container: 4566
    environment:
      AWS_ACCESS_KEY_ID: fake
      AWS_SECRET_ACCESS_KEY: fake
      AWS_REGION: ap-southeast-2
      AWS_DEFAULT_REGION: ap-southeast-2
      AWS__ServiceUrl: http://localstack:4566
      SERVICES: dynamodb, ses
      HOSTNAME_EXTERNAL: localhost
      DEBUG: "1"
    volumes:
      - local: ./.batect/localstack/init.sh
        container: /docker-entrypoint-initaws.d/init.sh
      - local: .
        container: /code
```
and task definition:
```
run-localstack:
  run:
    container: localstack
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)
I run the docker container using:
```
./batect run-localstack
```

I then configure my aws client to point to `http://localstack:4566` (I'm confident this is being done right as I have it working with dynamodb on localstack. My request using the .NET SDK looks as follows:

```
var emailRequest = new SendEmailRequest
{
    Destination = new Destination(),
    FromEmailAddress = "from@email.com",
    Content = new EmailContent
    {
        Simple = new Message
        {
            Subject = new Content { Data = "Some subject" },
            Body = new Body
            {
                Text = new Content{ Data ="Some content" }
            },
        }
    }
    
};
emailRequest.Destination.ToAddresses.Add("to@email/com");

return await _sesClient.SendEmailAsync(emailRequest);
```

doing a similar request using the CLI works perfectly fine:
```
>_$ aws ses send-email --from sender@example.com --destination file://destination.json --message file://message.json --endpoint-url=http://localhost:4566
MessageId: bzqksxsuvtwxlyxz-ttkeepqr-jjgi-glra-dajw-genrwdaekzox-rcwmjs
>_$
```

### Environment

```markdown
- OS: Windows 11
- LocalStack: latest
```

### Anything else?

I've uploaded the full output from localstack in case it helps :) 
[log-output.txt](https://github.com/localstack/localstack/files/7628770/log-output.txt)

**Comment by pinzon** [comment]
Hi @zachjbrowning
By reading the logs it seems that your SES client is trying to reach the version 2 of the service which is currently **not supported by Localstack**. So make sure to use version 1.

I'll leave a small project I just wrote to test this issue. Let me know if you need more help.
[project.zip](https://github.com/localstack/localstack/files/7651757/project.zip)
