### ISSUE TITLE
bug: Can't create aws_kms_key using latest version of localstack

### ISSUE THREAD

**Issue by jarthur-scottlogic** [localstack/localstack#5046]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

Since https://github.com/localstack/localstack/pull/5021/files there has been some strange behaviour surrounding kms key creation. When running terraform against localstack everything is created as normal apart from the aws_kms_keys which just hang
![image](https://user-images.githubusercontent.com/81358272/144208301-7d76ece0-6e2a-49c6-8fd5-fe0e71230fda.png)

 Also, when we use the com.amazonaws.services.kms.AWSKMS.createKey() method, it returns a key id and successful response as though a key has been created but in reality no such key exists.

These issues don't come up with version 0.13.0.8 but do when using :latest version.

### Expected Behavior

Terraform should create an aws_kms_key resource in very little time rather than just hanging.

### How are you starting LocalStack?

With a docker-compose file

#### Docker compose

```
services:
  aws:
    build:
      context: docker
      dockerfile: localstack.Dockerfile
    environment:
      SERVICES: lambda, apigateway, iam, ec2, sqs, s3, sts, kms, sns, ssm
      EDGE_PORT: "45678"
      EXTERNAL_HOSTNAME: localhost
      DEFAULT_REGION: eu-west-2
      TEST_AWS_ACCOUNT_ID: 123456789012
      LAMBDA_EXECUTOR: local
      LAMBDA_JAVA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:5025"
      DEBUG: "1"
    extra_hosts:
      - "notify.internal:host-gateway"
    networks:
      - di-authentication-api-net
    ports:
      - 45678:45678
      - 5025:5025
    healthcheck:
      test:
        - CMD
        - bash
        - -c
        - awslocal s3 ls terraform-state
      interval: 5s
      timeout: 10s
      start_period: 10s
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

#### localstack.Dockerfile
``` 
# localstack Dockerfile
#
# Container used to run tasks requiring Localstack in the build pipeline.

FROM localstack/localstack:latest

COPY localstack/*.sh /docker-entrypoint-initaws.d/

#RUN apk add argon2 argon2-dev
RUN apt-get install argon2
```

#### Terraform

```
resource "aws_kms_key" "id_token_signing_key" {
  description              = "KMS signing key for ID tokens"
  deletion_window_in_days  = 30
  key_usage                = "SIGN_VERIFY"
  customer_master_key_spec = "ECC_NIST_P256"

  tags = local.default_tags
}

resource "aws_kms_key" "audit_payload_signing_key" {
  description              = "KMS signing key for audit payloads"
  deletion_window_in_days  = 30
  key_usage                = "SIGN_VERIFY"
  customer_master_key_spec = "ECC_NIST_P256"

  tags = local.default_tags
}
```

### Environment

```markdown
- OS: Windows 10.0.19043
- LocalStack: latest
```

**Comment by pinzon** [comment]
Hi @jarthur-scottlogic just wanted to let you know that I replicated the issue and after several trials it seems like it's a problem with the moto KMS service.

I'm working on fixing it but in the meantime you could use `KMS_PROVIDER=local-kms` to change the service provider as a temporal fix.

**Comment by matelang** [comment]
Hi,

We have tried using local-kms as well, but I still can not get localstack to properly work with Terraform.
I also posted a comment on the PR by @pinzon.

Do you think it's related or should I open a separate issue?


Happy to help investigate,
Mate

**Comment by pinzon** [comment]
Hi @matelang, I'll close this issue since the PR solves the original stated problem stated above. 
**Please open a new issue with the new information,** this helps keep better tracking of the PR and the problem it solves, and even makes it easier if someone else has to handle the issue.

Thanks.
