### ISSUE TITLE
bug: KeyError: 'IndexName' by using Firehose with Elasticsearch / OpenSearch-Cluster Endpoint

### ISSUE THREAD

**Issue by Dgame** [localstack/localstack#5047]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I get the error
```
ERROR:firehose_api: Exception on / [POST]

Traceback (most recent call last):

  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app

    response = self.full_dispatch_request()

  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1518, in full_dispatch_request

    rv = self.handle_user_exception(e)

  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function

    return cors_after_request(app.make_response(f(*args, **kwargs)))

  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1516, in full_dispatch_request

    rv = self.dispatch_request()

  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1502, in dispatch_request

    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)

  File "/opt/code/localstack/localstack/services/firehose/firehose_api.py", line 349, in post_request

    response = put_record(stream_name, record)

  File "/opt/code/localstack/localstack/services/firehose/firehose_api.py", line 75, in put_record

    return put_records(stream_name, [record])

  File "/opt/code/localstack/localstack/services/firehose/firehose_api.py", line 85, in put_records

    es_index = es_dest["IndexName"]

KeyError: 'IndexName'
```

in my docker container.

### Expected Behavior

The data is written to the Elasticsearch-Cluster without any error.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

I have a docker-compose infrastructure with localstack:latest as image and a OpenSearch-Cluster as a Backend for localstack.

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

I'm using the AWS-SDK (the `FirehoseClient`) with the correct endpoint.

### Environment

```markdown
- OS: WSL (Ubuntu 20.04) in Windows 10
- LocalStack: Latest
```

**Comment by Dgame** [comment]
I think my problem can be solved if I use `ESDestinationDescription` (see [here](https://github.com/localstack/localstack/blob/3437384cdc98a4b4217387f63a2f6cf93cf5d0c8/localstack/services/firehose/firehose_api.py#L177)) instead of `ElasticsearchDestinationConfiguration` as mentioned in the [aws-cli docs](https://docs.aws.amazon.com/cli/latest/reference/firehose/create-delivery-stream.html#description). This should be mentioned, though.

**Comment by Dgame** [comment]
As said, if I'm using `ESDestinationDescription` I can publish messages into the stream but they never reach the (external) Elasticsearch/OpenSearch Cluster. I tried using `DomainARN` and `ClusterEndpoint`.

**Comment by Dgame** [comment]
I've tried to create a delivery-stream by hand with this:

```sh
aws --endpoint=http://localhost:4566 firehose create-delivery-stream --delivery-stream-name de_test --elasticsearch-destination-configuration '{ "RoleARN": "arn:aws:iam::000000000000:role/Firehose-Reader-Role", "ClusterEndpoint": "http://osc_01:9200", "IndexName": "de.test", "S3Configuration": { "RoleARN": "arn:aws:iam::000000000000:role/Firehose-Reader-Role", "BucketARN": "arn:aws:s3:::000000000000:es-backup-local" } }'
```

and put data into it:

```sh
aws --endpoint=http://localhost:4566 firehose put-record --delivery-stream-name de_test --record '{"Data":"eyJfbG9jYWxlIjoiZGVfREUiLCJzdHVkeSI6eyJIYWxsbyI6IldlbHQifX0="}'
```

but I get the error

> An error occurred (500) when calling the PutRecord operation (reached max retries: 2): <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
> <title>500 Internal Server Error</title>
> <h1>Internal Server Error</h1>
> <p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>

Inside the localstack container I see this error:

> 2021-12-06T13:45:35:ERROR:firehose_api: Exception on / [POST]
> 
> Traceback (most recent call last):
> 
>   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
> 
>     response = self.full_dispatch_request()
> 
>   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1518, in full_dispatch_request
> 
>     rv = self.handle_user_exception(e)
> 
>   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
> 
>     return cors_after_request(app.make_response(f(*args, **kwargs)))
> 
>   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1516, in full_dispatch_request
> 
>     rv = self.dispatch_request()
> 
>   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1502, in dispatch_request
> 
>     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
> 
>   File "/opt/code/localstack/localstack/services/firehose/firehose_api.py", line 349, in post_request
> 
>     response = put_record(stream_name, record)
> 
>   File "/opt/code/localstack/localstack/services/firehose/firehose_api.py", line 75, in put_record
> 
>     return put_records(stream_name, [record])
> 
>   File "/opt/code/localstack/localstack/services/firehose/firehose_api.py", line 85, in put_records
> 
>     es_index = es_dest["IndexName"]
> 
> KeyError: 'IndexName'

I can only guess what the problem is, but it seems that it does not find the key "IndexName" even though I have specified it. Perhaps the original configuration has been lost due to the differences in naming `ESDestinationDescription` vs `ElasticsearchDestinationConfiguration` ([see my comment here](https://github.com/localstack/localstack/issues/5047#issuecomment-986673454))?

**Comment by Dgame** [comment]
I set the LS_LOG environment variable to "trace" and I think I found the culprit:
> 06T15:59:26.373:ERROR:localstack.services.firehose.firehose_api: Unable to put record to stream: The client noticed that the server is not Elasticsearch and we do not support this unknown product

It seems that I am not allowed to use OpenSearch. That is troublesome.

**Comment by thrau** [comment]
Hey Randy @Dgame, sorry, looks like this is a limitation of the python elasticsearch client (the message `The client noticed that the server is not Elasticsearch and we do not support this unknown product` comes from there). In our firehose implementation, we're explicitly connecting to the cluster with the Elasticsearch python client:

https://github.com/localstack/localstack/blob/7c4c7e611e412b36d62528fda61aa2f764ac94da/localstack/services/firehose/firehose_api.py#L177-L183

https://github.com/localstack/localstack/blob/7c4c7e611e412b36d62528fda61aa2f764ac94da/localstack/utils/aws/aws_stack.py#L1089-L1091

This was sort of to be expected with the opensearch/elasticsearch contention. Looks like we either need to add a new control path + client for opensearch, or use a client library that's compatible with both elasticsearch and opensearch. [But seems like it's going to be the first option](https://aws.amazon.com/blogs/opensource/keeping-clients-of-opensearch-and-elasticsearch-compatible-with-open-source/).

**Comment by thrau** [comment]
i did a bit more digging:

* actually it looks like this product check in elasticsearch-py was [introduced recently](https://github.com/elastic/elasticsearch-py/commit/12c869df56e644863f05c74faa19151416b22aa2#diff-fc82e88e81fd6215f478fa610758f3422778bd88490cbd842c185e3c930c0d0c) with 7.14.0
* looks like we're currently getting elasticsearch 7.15.2 with the >=7.0.0 version range.

=> maybe pinning the client to 7.10.1 will help. i can give it a try.

@Dgame could you share the docker-compose you are using to start up opensearch?

**Comment by Dgame** [comment]
@thrau I can do that as soon as I get home. Actually, it's just the standard template from the [documentation](https://opensearch.org/docs/latest/opensearch/install/docker/#sample-docker-compose-file) with a few tweaks, more nodes and a few renames. 😄 Any Elasticsearch client should be working fine with OpenSearch until Elasticsearch  version 7.10.2 ([see here](https://opensearch.org/)).

**Comment by thrau** [comment]
alright! then i'll just pin the elasticsearch client and hope for the best ;-)

**Comment by Dgame** [comment]
> alright! then i'll just pin the elasticsearch client and hope for the best ;-)

Thank you very much, I will try it as soon as possible. 🙂 But still, if you need the OpenSearch for the update from elasticsearch to opensearch, I can provide it.

**Comment by thrau** [comment]
fix is underway, should be deployed in about an hour. please let me know if the workaround helped.

**Comment by Dgame** [comment]
It worked! Thank you so much! 🙂

**Comment by thrau** [comment]
fantastic! let us know if new issues appear. opensearch is an ongoing struggle ;-)
