### ISSUE TITLE
feature request: Route53Resolver

### ISSUE THREAD

**Issue by badarsebard** [localstack/localstack#5048]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Support for the Route53 Resolver service. Some common resources for the resolver service are the resolver endpoint, resolver rule, and resolver rule association.

### 🧑‍💻 Implementation

The service exists in the localstack/moto fork so my guess is the edge router just needs to load or connect to that backend.

**Comment by whummer** [comment]
Hi @badarsebard , thanks for reporting. Initial support for Route53Resolver has been added in the meantime - can you please pull the `latest` Docker image and give it another try? 

Would be great if you can share a few more details about your specific requirements (e.g., a few snippets of your client code) - we'll be happy to look into it in more detail and add any features that may currently still be missing.. Thanks!

**Comment by badarsebard** [comment]
I still receive a `no provider exists for service Route53Resolver` error.

**Comment by whummer** [comment]
Thanks @badarsebard , can you please share the startup configuration you're using. Please note that it should work with the default configuration after pulling the `latest` Docker image (no need to configure the `SERVICES` config variable):

```
$ docker images | grep localstack
localstack/localstack                latest                   42e9c4ba7a61   2 days ago
$ localstack start
...
```

Then we can use the `awslocal` command line to list the resolver rules:
```
$ awslocal route53resolver list-resolver-rules
{
    "ResolverRules": [],
    "MaxResults": 10
}
```

Can you please share the client code used to call the Route53 Resolver API - is it from a Terraform script? Judging from the error message you've shared, it might be possible that `Route53Resolver` is used as the service name in the request, whereas LocalStack is currently expecting the lower-case string `route53resolver` (which is also the default in `boto3` and the `awslocal` CLI). Thanks for your help!
