### ISSUE TITLE
bug: DynamoDB becomes unresponsive when there is a consumer for SQS Queue

### ISSUE THREAD

**Issue by ibrahim-cdprc** [localstack/localstack#5053]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

consumer:
```
const { Consumer } = require('sqs-consumer');
const AWS = require('aws-sdk')

const sqs = new AWS.SQS({
    credentials: new AWS.Credentials('xyz456', 'abc123'),
    region: 'us-east-1'
})

const app = Consumer.create({
  queueUrl: 'http://localhost:4566/000000000000/records',
  region: 'us-east-1',
  sqs,
  handleMessage: async (message) => {
    // do some work with `message`
    console.log(message)
  }
});

app.on('error', (err) => {
  console.error(err.message);
});

app.on('processing_error', (err) => {
  console.error(err.message);
});

app.start();

console.log("started....");
```

as soon as the consumer gets started the dynamo ui and queries to dynamo db gets slow and unresponsive. very weird issue. took me days to figure it out.

### Expected Behavior

Should not slow down DynamoDB

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    version: '3.7'
    services:
      localstack:
        container_name: localstack
        image: localstack/localstack
        ports:
          - "4566-4599:4566-4599"
          - "8080:8080"
        environment:
          - SERVICES=dynamodb,s3,sqs
          - DEBUG=1
          - USE_LIGHT_IMAGE=1
          - DATA_DIR=/tmp/localstack/data
          - PORT_WEB_UI=8080
          - DOCKER_HOST=unix:///var/run/docker.sock
        volumes:
          - "./.localstack:/tmp/localstack"
          - "./app/backend/aws/files/:/files/"
          - "/var/run/docker.sock:/var/run/docker.sock"
          - "./app/backend/aws/init.sh:/docker-entrypoint-initaws.d/init.sh"
    
      localstack-s3-ui:
        container_name: localstack-s3-ui
        depends_on: [localstack]
        image: gosuper/localstack-s3-ui
        ports:
          - 9000:9000
        environment:
          - API_REQ_FILE_PATH=/tmp/localstack/data/recorded_api_calls.json
          - PORT=9000
        volumes:
          - "./.localstack:/tmp/localstack"
    
      dynamodb-admin:
        depends_on:
          - localstack
        image: aaronshaf/dynamodb-admin
        ports:
          - 8001:8001
        environment:
          - DYNAMO_ENDPOINT=http://localstack:4566

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal sqs create-queue --queue-name records

### Environment

```markdown
- OS: MAC OS Big Sur 11.6.1
- LocalStack: latest
```

**Comment by dominikschubert** [comment]
Hi @ibrahim-cdprc ! There was a persistence bug related to the `DATA_DIR` environment variable. We've just pushed a fix for this that might fix your issue. Please test it with with the latest docker image and let us know if this issue persists!
