### ISSUE TITLE
Cloudwatch required to run lambda

### ISSUE THREAD

**Issue by adriangalera** [localstack/localstack#506]
Hi!
I am trying to run lambda using localstack from python:
```python
infra.start_infra(async=True,apis=['dynamodb', 'lambda', 'dynamodbstreams', 'kinesis'])
```
However, if I don't initialize CloudWatch API the execution block and I see a Connection Refused Exception while trying to connect to CloudWatch API.

If I enable CloudWatch API, everything works fine:
```python
infra.start_infra(async=True,apis=['dynamodb', 'lambda', 'dynamodbstreams', 'kinesis', 'cloudwatch'])
```
Please, include somewhere in the documentation this kind of dependencies ;)

**Comment by whummer** [comment]
Thanks for reporting @adriangalera . This should have been fixed in the meantime. Also, we can now specify API dependencies here: https://github.com/localstack/localstack/blob/master/localstack/services/infra.py#L36 Closing this issue - please re-open or comment here if the problem persists.
