### ISSUE TITLE
bug: S3 copy object does not copy content type or metadata

### ISSUE THREAD

**Issue by david-mk-lawrence** [localstack/localstack#5068]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Running S3 copy object (which copies an object from one bucket to another bucket) does not respect parameters like content type, metadata, or metadata-directive (possibly others, but these are the only ones I've tested).

The object gets successfully copied to the target bucket, however the copied object's content type is _always_ "binary/octet-stream" and metadata is _always_ empty, regardless of the parameters set in the copy object command.

### Expected Behavior

The copied object should respect parameters set in the copy object command, such as content-type, metadata, and metadata-directive. For example, if the copy object command specifies that the object should have content-type "application/json", the resulting object should _not_ have a content-type of "binary/octet-stream".

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

```yml
# docker-compose.yml
services:
  localstack:
    image: localstack/localstack
    environment:
      SERVICES: "s3"
    ports:
      - 4566:4566
      - 4571:4571
```

```sh
docker-compose up -d
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```json
// object.json
{
    "data": {
        "key": "value"
    }
}
```

```sh
# Create the buckets
aws s3api --endpoint-url http://localhost:4566 create-bucket --bucket target-bucket
aws s3api --endpoint-url http://localhost:4566 create-bucket --bucket source-bucket

# Put object in source bucket with content type and metadate
aws s3api --endpoint-url http://localhost:4566 put-object \
    --bucket source-bucket \
    --key source-object \
    --content-type application/json \
    --metadata "{\"key\": \"value\"}" \
    --body object.json

# Running "head" on the object *correctly* reports the content-type of the object 
aws s3api --endpoint-url http://localhost:4566 head-object \
    --bucket source-bucket \
    --key source-object

# Copy the object to the target bucket with explicit content type and metadata
aws s3api --endpoint-url http://localhost:4566 copy-object \
    --bucket target-bucket \
    --key target-object \
    --copy-source "source-bucket/source-object" \
    --content-type application/json \
    --metadata "{\"key\": \"value\"}" \

# Running "head" on the copied object *incorrectly* reports the content-type and metadata
aws s3api --endpoint-url http://localhost:4566 head-object \
    --bucket target-bucket \
    --key target-object

```

### Environment

```markdown
- OS: macOS Big Sur (11.6)
- LocalStack: latest
```

**Comment by naspeh** [comment]
@david-mk-lawrence thank you for reporting and detailed explanation. I'm making some fixes to this, I will let you know when they will be available in the latest localstack.

**Comment by naspeh** [comment]
Hi @david-mk-lawrence,

We've fixed this on `moto` side: https://github.com/spulec/moto/pull/4666

Also, we've added compatibility checks into our repo: https://github.com/localstack/localstack/pull/5085

Please note that when you specify `--metadata` for `copy-object` and want to replace it for a new object, you have to specify `--metadata-directive=REPLACE`, ref: https://docs.aws.amazon.com/cli/latest/reference/s3/cp.html
```
--metadata-directive
...
Valid values are COPY and REPLACE. If this parameter is not specified, COPY will be used by default.
...
```

Please try the latest docker image: `localstack/localstack:latest`

Thank you for reporting.
