### ISSUE TITLE
bug: Ctrl+c not killing container when localstack is started through "npm run" script

### ISSUE THREAD

**Issue by kevinswarner** [localstack/localstack#5069]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am starting Localstack using an NPM script in package.json.

```
"scripts": {
    "localstack": "SERVICES=dynamodb localstack start",
}
```

When I do this, the Docker container starts and operates fine. However, when I attempt to kill the container using Ctrl+c in the terminal window, the actual docker container itself is not stopped.

However, if I start Localstack directly in the terminal, not using an NPM script, and then use Ctrl+c, the actual docker container does stop correctly.

I am not sure if this is a Localstack issue or not. This worked fine on my previous environment, but I recently moved to a new development machine, so I am not sure what is different, except I believe Docker is a new version and Localstack is also a new version on this machine.

### Expected Behavior

When I press Ctrl+c in the terminal window where I have started Localstack through an NPM script, I would also expect the actual Docker container to be stopped / killed.

### How are you starting LocalStack?

Custom (please describe below)

### Steps To Reproduce

Start Localstack using an NPM script.

In package.json
```
"scripts": {
    "localstack": "SERVICES=dynamodb localstack start",
}
```
In terminal...
```
npm run localstack
```

Then, in the same terminal window, press Ctrl+c.

The Docker container (in Docker Desktop) is still running.

### Environment

```markdown
- OS: MacOS Monterey 12.0.1
- LocalStack: 0.13.0.10
- Node version: 14.17.3
- NPM version: 6.14.13
```

### Anything else?

This may not be a bug, but I would love to know how to get the expected behavior, which did in fact work on my old machine / environment. Thanks!

**Comment by thrau** [comment]
Thanks for the report Kevin @kevinswarner. This may be a regression due to https://github.com/localstack/localstack/pull/4969 where we changed the way we block the terminal. Will take a look tomorrow and try to reproduce.

**Comment by thrau** [comment]
I failed to reproduce this on my machine. I use Linux Mint with terminator 1.91 as terminal emulator. Tried it with both bash and zsh, as well as node 16 and node 14.

Here's how it behaves (as expected)
![Peek 2021-12-05 17-20](https://user-images.githubusercontent.com/3996682/144754762-3fac6bab-eb61-44b6-a252-f391ae84ad33.gif)

**Comment by thrau** [comment]
Maybe this is something Mac OS specific? @whummer could you give this a try. Here's a gist: https://gist.github.com/thrau/82d006ff4cf1d26fcbfebb332d0c44a9

**Comment by kevinswarner** [comment]
Also, I am using zsh and oh-my-zsh, if that makes any difference. Thanks for looking into this.

**Comment by naspeh** [comment]
I can reproduce this with Linux as well
```
[8:07] tfns:/opt/localstack/support/issue-5069 [env: env] [master ●] 
$ npm run localstack

> npm-run@1.0.0 localstack /opt/localstack/support/issue-5069
> SERVICES=dynamodb localstack start


     __                     _______ __             __
    / /   ____  _________ _/ / ___// /_____ ______/ /__
   / /   / __ \/ ___/ __ `/ /\__ \/ __/ __ `/ ___/ //_/
  / /___/ /_/ / /__/ /_/ / /___/ / /_/ /_/ / /__/ ,<
 /_____/\____/\___/\__,_/_//____/\__/\__,_/\___/_/|_|

 💻 LocalStack CLI 0.13.0.10

[08:07:55] starting LocalStack in Docker mode 🐳                                                                                                                                                                                                                 localstack.py:115
───────────────────────────────────────────────────────────────────────────────────────────────────────────────── LocalStack Runtime Log (press CTRL-C to quit) ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────
2021-12-06T08:07:55.056:INFO:localstack.plugins: configuring container with edge ports: [4566, 0]
Waiting for all LocalStack services to be ready
2021-12-06 08:07:55,872 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2021-12-06 08:07:55,875 INFO supervisord started with pid 14
2021-12-06 08:07:56,878 INFO spawned: 'infra' with pid 20
. .venv/bin/activate; LOCALSTACK_INFRA_PROCESS=1 exec bin/localstack start --host --no-banner
2021-12-06 08:07:57,888 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

LocalStack version: 0.13.0.10
LocalStack Docker container id: 93002cb94c1f
LocalStack build date: 2021-12-03
LocalStack build git hash: 47e6b57f

Starting edge router (https port 4566)...
Ready.
[2021-12-06 08:07:58 +0000] [21] [INFO] Running on https://0.0.0.0:4566 (CTRL + C to quit)
2021-12-06T08:07:58.515:INFO:hypercorn.error: Running on https://0.0.0.0:4566 (CTRL + C to quit)
^Cok, bye!

Aborted!
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! npm-run@1.0.0 localstack: `SERVICES=dynamodb localstack start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the npm-run@1.0.0 localstack script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-12-06T08_08_01_714Z-debug.log


[8:08] tfns:/opt/localstack/support/issue-5069 [env: env] [master ●] 1 ↵
$ docker ps                   
CONTAINER ID   IMAGE                   COMMAND                  CREATED          STATUS          PORTS                                          NAMES
93002cb94c1f   localstack/localstack   "docker-entrypoint.sh"   12 seconds ago   Up 12 seconds   4571/tcp, 127.0.0.1:4566->4566/tcp, 5678/tcp   localstack_main

```

I tested changes from https://github.com/localstack/localstack/pull/5079 and it solved it.

**Comment by kevinswarner** [comment]
That seems to have solved it for me. Thanks!
