### ISSUE TITLE
bug: Issue logging unicode to cloudwatch

### ISSUE THREAD

**Issue by guydunton** [localstack/localstack#5084]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I've tried logging unicode (the `’` character) to Cloudwatch both through the cli and using `console.log` within a lambda and either way I get the following error message when I view the logs:
```
'ascii' codec can't encode character '\u2019' in position 1: ordinal not in range(128)`
```

### Expected Behavior

Logs should be displayed with unicode present

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

docker-compose.yml:

```
version: '3.8'

services:
  localstack:
    container_name: '${LOCALSTACK_DOCKER_NAME-localstack_main}'
    image: localstack/localstack
    ports:
      - '4566:4566'
      - '4571:4571'
    environment:
      - SERVICES=${SERVICES- }
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - HOST_TMP_FOLDER=${TMPDIR:-/tmp/}localstack
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LAMBDA_DOCKER_NETWORK=ls-network
    volumes:
      - '${TMPDIR:-/tmp}/localstack:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
networks:
  default:
    name: ls-network
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

You will need to replace the timestamp with a recent one

```bash
awslocal logs create-log-group --log-group-name my-logs
awslocal logs create-log-stream --log-group-name my-logs --log-stream-name mylogstream
awslocal logs put-log-events --log-group-name my-logs --log-stream-name mylogstream --log-events '[{"timestamp":1638885815000,"message":"’"}]'
awslocal logs get-log-events --log-group-name my-logs --log-stream-name mylogstream
```bash



### Environment

```markdown
- OS: MacOS
- LocalStack: latest
```

**Comment by pinzon** [comment]
Hi @guydunton thank you for providing such easy code to test your issue. To me it seems to work fine I even tested with emojis and I didn't get any problem. 

Make sure to PULL the latest image and tell me if it keeps failing for you.

![imagen](https://user-images.githubusercontent.com/18080804/145260487-3de96803-5171-46a9-9a21-701b6688505f.png)
