### ISSUE TITLE
Having issue with docker-entrypoint-initaws.d in git actions

### ISSUE THREAD

**Issue by jslota-rt** [localstack/localstack#5090]
### Is there an existing issue for this?

- [X] I have searched the existing issues and read the documentation

### Question

Hello when I run my docker composed with local stack on my machine it all works, 

but then when I try to run it in git actions it can't find the .csv file I have located in docker-entrypoint-initaws.d for my shell script,

Does anyone have any references or examples of how I can fix this and get it working? 

Thank you

**Comment by thrau** [comment]
Hi John @jslota-rt, thanks for the report. It's a bit hard to tell what the problem could be with the information we have. It would be helpful if you could share the relevant details of your docker-compose file that starts localstack and your github actions workflow step. Specifically how you are mounting directories from the actions worker into the container.

**Comment by jslota-rt** [comment]
Hi @thrau 

I am adding it on volumes 
```
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./seed:/docker-entrypoint-initaws.d"
```
   
I have in that seed directory a test.sh script which executes fine and a CSV (ABA_Final.csv) file with data that I am using in that test.sh script

The test.sh looks as such
```
awslocal --endpoint-url=http://localstack:4566 s3 mb s3://dataiku-intermediate-s3/dataiku/raw/fps_data/ABA_Final --region us-west-2
awslocal --endpoint-url=http://localstack:4566 s3 cp /docker-entrypoint-initaws.d/ABA_Final.csv s3://dataiku-intermediate-s3/dataiku/raw/fps_data/ABA_Final/ABA_Final.csv
```

When I fire the docker-compose up on my machine it works but then in git actions I am seeing in the pipeline with the logs,

`The user-provided path /docker-entrypoint-initaws.d/ABA_Final.csv does not exist.
`

Let me know if I can provide anything else and thank you so much

**Comment by jslota-rt** [comment]
The bash file I see is found and working 

```
/usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initaws.d/test.sh
```

**Comment by jslota-rt** [comment]
I am so sorry, I looked in the directory on git actions and it is not there, I had the csv in my git ignore, took me 2 days to figure that last piece out, thank you so much @thrau for your quick reply and sorry for not seeing that before hand
