### ISSUE TITLE
Question: Advice on integrating aws-mock into localstack?

### ISSUE THREAD

**Issue by nottoseethesun** [localstack/localstack#51]
Background: https://github.com/treelogic-swe/aws-mock has good support for mocking EC2, which I don't see is available in localstack. 

How would one go about integrating the EC2 mocking support in aws-mock with localstack?  Where is the integration point for a new AWS mock service, and what is its API?

**Comment by russellc92** [comment]
hey, did you or anyone have any luck with this?

**Comment by whummer** [comment]
Closing this issue as duplicate of #691 - let's continue the discussion here:
https://github.com/localstack/localstack/issues/691

**Comment by nottoseethesun** [comment]
Cool, thanks.
