### ISSUE TITLE
Error: Cannot find module '...' when invoke the lambda function (hot-deploying mode)

### ISSUE THREAD

**Issue by cuongphamrb** [localstack/localstack#5102]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I calling this function using curl command as below:
```
curl --location --request POST 'http://localhost:4566/2015-03-31/functions/my-function/invocations' \
--header 'Content-Type: application/json' \
--data-raw ''
```

Current response: 
```
{
    "errorMessage": "Lambda process returned error status code: 1. Result: . Output:\ninternal/modules/cjs/loader.js:905\n  throw err;\n  ^\n\nError: Cannot find module 'aws-sdk' .........",
    "errorType": "InvocationException",
    "stackTrace": [
        "  File \"/opt/code/localstack/localstack/services/awslambda/lambda_api.py\", line 809, in run_lambda\n    result = LAMBDA_EXECUTOR.execute(\n",
        "  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 443, in execute\n    return do_execute()\n",
        "  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 433, in do_execute\n    return _run(func_arn=func_arn)\n",
        "  File \"/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py\", line 158, in wrapped\n    raise e\n",
        "  File \"/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py\", line 154, in wrapped\n    result = func(*args, **kwargs)\n",
        "  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 420, in _run\n    raise e\n",
        "  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 416, in _run\n    result = self._execute(lambda_function, inv_context)\n",
        "  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 1357, in _execute\n    raise InvocationException(result, log_output)\n"
    ]
}
```

### Expected Behavior

Function should return response

### How are you starting LocalStack?

With a docker-compose file

#### I start localstack using docker-compose.yml
```
version: '3.8'
services:
  localstack:
    container_name: localstack
    image: localstack/localstack
    network_mode: bridge
    ports:
      - '127.0.0.1:53:53' # only required for Pro
      - '127.0.0.1:53:53/udp' # only required for Pro
      - '127.0.0.1:443:443' # only required for Pro
      - '127.0.0.1:4510-4530:4510-4530' # only required for Pro
      - '127.0.0.1:4566:4566'
      - '127.0.0.1:4571:4571'
    environment:
      - SERVICES=lambda,sqs,dynamodb,secretsmanager
      - DEFAULT_REGION=us-east-1
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - LAMBDA_EXECUTOR=local
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LAMBDA_REMOTE_DOCKER=false
      - HOST_TMP_FOLDER=../dist
      - LAMBDA_CONTAINER_REGISTRY=lambci/lambda
    volumes:
      - '../dist:/tmp/localstack:rw'
      - '/var/run/docker.sock:/var/run/docker.sock'

```
#### I created a function as below

    laws lambda create-function --function-name my-function \
    --code S3Bucket="__local__",S3Key="/tmp/localstack/" \
    --handler index.handler \
    --runtime nodejs12.x \
    --role whatever 

### Environment

```markdown
- OS: Mac M1
- LocalStack: latest
```

### Anything else?

I can run this function successfully using lambci/lambda directly. Not sure what is wrong in my setup

**Comment by peledies** [comment]
any update on this? I have the same issue with a very similar setup

**Comment by dfangl** [comment]
Hi!
Hot reloading is generally not supported well in the local executor.
Please try switching to the latest localstack with its new file hierarchy, and please use the docker executor modes for hot reloading.
After doing this, please do not set HOST_TMP_FOLDER. I think, even in your configuration, this is one of the main problems, as relative paths will not work there, in addition to hot reloading being barely supported in the local executor.

You can also use our new lambda provider, using `PROVIDER_OVERRIDE_LAMBDA=asf`, which should work even better for hot reloading.
Please do not hesitate to ask any more questions. As this issue is quite old, I will close it for now, please open another issue if you still have problems using the latest localstack version.
