### ISSUE TITLE
bug: Api Gateway Methodsettings

### ISSUE THREAD

**Issue by kmacmcfarlane** [localstack/localstack#5105]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Deploying a AWS Sam template to localstack via cloudformation results in an API Gateway deploy that does not invoke the function. Subsequently, all requests return an `Unable to find integration for: GET /foo/bar` error. If I specify `GET` for the lambda invocation eventsource method instead of `ANY`, requests go through, but I need to use `GET` and `PUT`.

### Expected Behavior

The specified lambda function should be invoked regardless of the HTTP method used.

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    DEBUG=1 localstack start

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    sam build
    samlocal deploy --resolve-s3 --capabilities CAPABILITY_IAM --stack-name $(PROJECT_NAME) --region us-east-1 -t .aws-sam/build/template.yaml
    

### Environment

```markdown
- OS: Linux (Ubuntu)
- LocalStack: 0.12.20
```

### Anything else?

`awslocal apigateway get-stages --rest-api-id=xxxxxxx`
```
{
    "item": [
        {
            "deploymentId": "ccjq7wewws",
            "stageName": "Stage",
            "description": "",
            "cacheClusterEnabled": false,
            "methodSettings": {},
            "variables": {}
        },
        {
            "deploymentId": "ccjq7wewws",
            "stageName": "test",
            "description": "",
            "cacheClusterEnabled": false,
            "methodSettings": {},
            "variables": {},
            "tags": {}
        }
    ]
}
```

rendered SAM template after sam build
```
AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Runtime: go1.x
    Environment:
      Variables:
        WORKSPACE: test
        ENVIRONMENT: test
        LOG_LEVEL: debug
Resources:
  Api:
    Type: AWS::Serverless::Function
    Properties:
      Handler: endorsements-api
      FunctionName: endorsements-api
      CodeUri: Api
      Timeout: 30
      Events:
        AllEvents:
          Type: Api
          Properties:
            Path: '{proxy+}'
            Method: ANY
            RestApiId:
              Ref: ApiGateway
    Metadata:
      BuildMethod: makefile
  ApiGateway:
    Type: AWS::Serverless::Api
    Name: endorsements-api-gateway
    Properties:
      Name: endorsements-api-gateway
      StageName: test
      MethodSettings:
      - HttpMethod: *
        ResourcePath: /*
Outputs:
  ApiID:
    Value:
      Ref: ApiGateway
  LocalURI:
    Value:
      Fn::Sub: http://localhost:4566/restapis/${ApiGateway}/test/_user_request_/docs/index.html
  Endpoint:
    Value:
      Fn::Sub: https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/Prod/

```

`awslocal apigateway get-integrations --restapi-id=xxxxxx` shows there is an ANY style integration deployed, though it fails for all requests:
```
{
    "items": [
        {
            "id": "3hocyhz56b",
            "path": "{proxy+}",
            "resourceMethods": {
                "X-AMAZON-APIGATEWAY-ANY-METHOD": {
                    "httpMethod": "X-AMAZON-APIGATEWAY-ANY-METHOD",
                    "apiKeyRequired": false,
                    "methodIntegration": {
                        "type": "aws_proxy",
                        "httpMethod": "X-AMAZON-APIGATEWAY-ANY-METHOD",
                        "uri": "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:000000000000:function:endorsements-api/invocations",
                        "requestTemplates": {},
                        "cacheNamespace": "84748f6c",
                        "cacheKeyParameters": [],
                        "integrationResponses": {
                            "200": {
                                "statusCode": 200,
                                "responseTemplates": {}
                            }
                        }
                    }
                }
            }
        }
    ]
}
```

**Comment by calvernaz** [comment]
Hi @kmacmcfarlane it's been a long time since you issued this request, but I think I have good news for you, I finally came around this issue and a fix for it in the latest build. Do you mind to give it a try?

**Comment by kmacmcfarlane** [comment]
Is that available through pip, or do I need to build from source?

**Comment by calvernaz** [comment]
Hi @kmacmcfarlane, you can just pull the `latest` docker build. Or build from the source, we recommend the docker build given is simplicity and well documented configurations.

**Comment by kmacmcfarlane** [comment]
It's working as expected now, thanks!
