### ISSUE TITLE
SSM - PutParameter - Value '' at 'value' failed to satisfy constraint: Member must have length greater than or equal to 1.

### ISSUE THREAD

**Issue by yonatandbinahai** [localstack/localstack#5108]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When trying to update a SSM parameter with an empty string (with `PutParameter`), the following error occurs:
`1 validation error detected: Value '' at 'value' failed to satisfy constraint: Member must have length greater than or equal to 1.` 

### Expected Behavior

We should be able to set a SSM parameter value to an empty string

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

const requestParams: AWS.SSM.PutParameterRequest = {
    Name: 'parameterName',
    Value: '',
    Overwrite: true,
  };
  await ssm.putParameter(requestParams).promise(); // validation error occurs

### Environment

```markdown
- OS: Windows 10
- LocalStack: 0.13.1
```

**Comment by whummer** [comment]
Thanks for reporting @yonatandbinahai - just to confirm, have you been able to get this resolved in the meantime, or does the problem persist with the `latest` image? Thanks!

**Comment by yonatandbinahai** [comment]
@whummer sorry, it was a mistake, apparently AWS SSM doesn't allow storing empty values either, so works as expected.
