### ISSUE TITLE
Is the kinesalite production ready ? 

### ISSUE THREAD

**Issue by ranjanshubham** [localstack/localstack#512]
As mentioned in the issue name ,  kinesalite that we are  using with kinesalite is production ready ?

**Comment by whummer** [comment]
Hi @ranjanshubham , you should not be using LocalStack in production at all. The purpose of LocalStack is to provide a test environment for local development and continuous integration testing, but we do not recommend to use it as a production service (kinesalite provides no fault tolerance, resilience, etc.). What exactly is your use case when you mention "production ready"?

**Comment by ranjanshubham** [comment]
Hi @whummer ,
What i mean with production ready is that any testing done with kinesalite is ready to go on production ? I have one more question . As AWS Kinesis does not support distributed mode for kinesis but it supports data replication in the form of 3 zones inside a region. Is kinesalite following the same ?

**Comment by whummer** [comment]
Please note that LocalStack is useful for local unit and integration testing, but it cannot fully replace actual integration testing on AWS. Please make sure to properly test your code in both - LocalStack as well as AWS, to ensure production readiness of your code. Closing this issue
