### ISSUE TITLE
_parse_search_filters does not parse the filters correctly

### ISSUE THREAD

**Issue by shaibs3** [localstack/localstack#5127]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

ec2_starter.py
`def _parse_search_filters(self):
        search_filters = self._get_multi_param("Filter")
        for filter in search_filters:
            filter["Values"] = []
            for i in range(1, 100):
                **val = filter.get("Value.%s" % i)**
                if val is None:
                    break
                filter["Values"].append(val)
        return search_filters`\

the filter.get syntax is incorrect. so it will not retrieve the values from the array.
so instead of filter.get("Value.%s" % i) will evaluate to the value inside the array  it evaluates to null

### Expected Behavior

the code should give the value in the array. instead it returns none

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    aws --endpoint-url=http://localhost:4566 ec2 describe-vpc-endpoint-services  --filters Name=service-type,Values=Interface

### Environment

```markdown
- OS: macos
- LocalStack: 0.12.20
```

### Anything else?

the fix can be similar to 
 values = filter["Value"]
            for i in values:
                val = i
                if val is None:
                    break

**Comment by viren-nadkarni** [comment]
Fixed with #5128
