### ISSUE TITLE
When using LAMBDA_EXECUTOR=local, running into module not found issue

### ISSUE THREAD

**Issue by maturiaditya** [localstack/localstack#5131]
### Is there an existing issue for this?

- [X] I have searched the existing issues and read the documentation

### Question

The deployment seems to be working fine. However, the modules that are part of dev dependencies (like `aws-sdk`) which are not actually needed as part of dependencies are not included in the package and I'm running into the following issue when invoking lambda. 

`Error: Cannot find module 'aws-sdk'`

Also, I have a lot of modules that are part of the layer. However, I have like 20 lambdas using the same layer, and it is slowing my deployment process and I don't know if there is a way around it.  Please advise.

**Comment by dominikschubert** [comment]
Hi @maturiaditya. This is a known issue with the local executor. As a workaround you could add the aws-sdk somewhere in a node_modules folder up the directory tree of the lambda code you're executing.

**Comment by maturiaditya** [comment]
Got it, thanks @dominikschubert
