### ISSUE TITLE
bug: LAMBDA_REMOVE_CONTAINERS flag doesn't seem to work

### ISSUE THREAD

**Issue by david-wb** [localstack/localstack#5135]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I use `LAMBDA_REMOVE_CONTAINERS=0`, lambda containers are still removed immediately after invocation, which prevents from seeing the logs. 

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

Create a containerized lambda function and run it with localstack. Set `LAMBDA_REMOVE_CONTAINERS=0` and notice that lambda invocation containers are immediately removed.

### Environment

```markdown
- OS: Ubuntu
- LocalStack: latest
```

**Comment by navels** [comment]
The docs don't say this but this only works with the docker-reuse executor, sadly.

**Comment by jmmacdo4** [comment]
@whummer Any chance we could get this flag working with the regular docker flag? Searching through the cloudwatch logs is time consuming. Even just stopping the container and not deleting it should suffice because we could get the logs.
