### ISSUE TITLE
question: How do I increase the file size limit for S3 signed URLs?

### ISSUE THREAD

**Issue by dwolfhub** [localstack/localstack#5142]
### Is there an existing issue for this?

- [X] I have searched the existing issues and read the documentation

### Question

How do I increase the file size limit for S3 signed URLs? If I try to upload anything larger than 250M I get a 413 response. Is there a setting I can change?

**Comment by dwolfhub** [comment]
Update: I found this line. Does this mean the value is hard coded and not configurable or can i overwrite this? 

https://github.com/localstack/localstack/blob/3816ce769383f5809217443b520e5eb419a482ee/localstack/utils/server/http2_server.py#L150

**Comment by dwolfhub** [comment]
Does it make sense to allow a dev to override this value using an environment variable? I'm happy to put together a PR if I can get some direction.

**Comment by duaneking** [comment]
This is an arbitrary limitation imposed by the framework and not AWS, so this is a legit bug.

**Comment by duaneking** [comment]
No leave it open

**Comment by duaneking** [comment]
This is a legit bug.

**Comment by MarcelStranak** [comment]
Hi, this should be fixed in https://github.com/localstack/localstack/pull/5617
You can specify the size with env variable 
```
# default max content length for HTTP server requests (256 MB)
DEFAULT_MAX_CONTENT_LENGTH = 256 * 1024 * 1024
```

**Comment by duaneking** [comment]
This needs reopened it was just ignored by the devs, until its confirmed fixed.
