### ISSUE TITLE
bug: Incorrect ARN for lambda function

### ISSUE THREAD

**Issue by sergey-morenets** [localstack/localstack#5147]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi

I've used AWS Lambda functionality in LocalStack multiple times however on one environment it fails to work correctly.
So the Lambda function seems to created successfully but when I try to invoke Lambda or get Lambda information the error message shows that Lambda ARN contains incorrect region (ap-northeast-1) instead of the region that I specified when created it(us-east-1).

Moreover, I added environment variable DEFAULT_REGION=us-east-1 but the region was still wrong in ARN (another bug ?).

I added another environment variable DEBUG=1 but there's only one line related to Lambdas:

`2021-12-19T13:14:47.134:DEBUG:localstack.utils.run: Executing command: cd /tmp/localstack/zipfile.ffcdfae4; unzip -o -q /tmp/localstack/zipfile.ffcdfae4/original_lambda_archive.zip`

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

   Our docker-compose.yml:

```
version: '3.8'
services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=dynamodb,s3,sns,sqs,kms,lambda,cloudformation,cloudwatch
      - DATA_DIR=/tmp/localstack/data
```

I added new environment variable but it hasn't solved the issue:

`      - DEFAULT_REGION=us-east-1`

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)
`
      aws lambda create-function --endpoint-url http://localhost:4566 --function-name httpHandler --runtime java11 --handler aws.lambda.HttpHandler --region us-east-1 --zip-file fileb://build/distributions/aws-lambda.zip --role arn:aws:iam::12345:role/ignoreme `

The output of this command shows correct ARN:

```
{
    "FunctionName": "httpHandler",
    "FunctionArn": "arn:aws:lambda:us-east-1:000000000000:function:httpHandler",
    "Runtime": "java11",
    "Role": "arn:aws:iam::12345:role/ignoreme",
    "Handler": "aws.lambda.HttpHandler",
    "CodeSize": 16250291,
    "Description": "",
    "Timeout": 3,
    "LastModified": "2021-12-19T14:46:21.543+0000",
    "CodeSha256": "rKzyJUsojhVmE72sxjX+kci3F52+dwzaPZk1dDy8O/k=",
    "Version": "$LATEST",
    "VpcConfig": {},
    "TracingConfig": {
        "Mode": "PassThrough"
    },
    "RevisionId": "89f708ce-51b3-4f94-a0c1-c8f249d52f70",
    "State": "Active",
    "LastUpdateStatus": "Successful",
    "PackageType": "Zip",
    "Architectures": [
        "x86_64"
    ]
}
```

But when I try to get lambda info: 

`aws lambda get-function --function-name httpHandler  --endpoint-url http://localhost:4566 `

I receive an error where incorrect region is used(ap-northeast-1):

`An error occurred (ResourceNotFoundException) when calling the GetFunction operation: Function not found: arn:aws:lambda:ap-northeast-1:000000000000:function:httpHandler`

### Environment

```markdown
- OS: Windows 10
- LocalStack: 0.13.1
```

### Anything else?

.

**Comment by whummer** [comment]
Thanks for reporting @sergey-morenets . Please note that recent versions of LocalStack have full multi-region support, i.e., the region is determined by the configuration of the calling client (just like in real AWS). In particular, please note that `DEFAULT_REGION` is now deprecated and obsolete.

Looks like your terminal session may be configured to use the `ap-northeast-1` region. You could either configure your session to fix the region setting (e.g., setting the `AWS_DEFAULT_REGION=us-east-1` environment variable), or pass the `--region` explicitly:

```
aws lambda get-function --function-name httpHandler --endpoint-url http://localhost:4566 --region us-east-1
```

Btw, we recommend installing the [`awslocal`](https://github.com/localstack/awscli-local) command line, which makes things a bit easier:

```
pip install awscli-local
awslocal lambda get-function --function-name httpHandler
```

Hope that helps, please let us know if that fixes your issue. Thanks!

**Comment by sergey-morenets** [comment]
Hi @whummer 

Thank you for the explanation. However it raise a little bit more questions for me.

1) You said that DEFAULT_REGION environment variable is obsolete and deprecated. However docs for LocalStack docker image don't mention that: https://hub.docker.com/r/localstack/localstack

`DEFAULT_REGION: AWS region to use when talking to the API (default: us-east-1).`

2) You said about cross-region support but the only mentioning in the docs is that (https://docs.localstack.cloud/aws/multi-region-support/):

`While the open source version of LocalStack can only be configured to use a single region (e.g., us-east-1), the Pro version contains several extensions that allow resources to be addressed across regions, using their unique ARN identifiers.`

I used open source version so I still can use this feature? 

3) Cross-region support and Lambda function usage should be documented somehow. If I specified a region(us-west-1) using AWS_REGION environment variable on my PC I can create a lambda in another region (us-east-1).
However I can't invoke it by name(incorrect ARN) and if I try to print all the lambdas:

`aws lambda list-functions --endpoint-url http://localhost:4566`

I see the empty list. So in my opinion the last operation should print all the lambda functions in all the regions(because I don't specify the region in the parameters). Or at least mention this case in the documentation (resources access for cross-region client).

Thank you

**Comment by whummer** [comment]
Thanks for the detailed pointers @sergey-morenets ! 

> I used open source version so I still can use this feature?

Yes, this feature has recently been migrated and is now also available for the Community version. 👍 

We have now updated our docs (Docker Hub README, and removed obsolete multi-region section on docs.localstack.cloud). Please let us know if there are any other questions or issues.. Thanks!

**Comment by sergey-morenets** [comment]
Hi @whummer 

Thank you for the updates in the documentation. This page (https://hub.docker.com/r/localstack/localstack) contains a link that return 404:

https://hub.docker.com/r/localstack/doc/troubleshoot/README.md
