### ISSUE TITLE
bug: PRO version: The provided ARN 'arn:aws:states:us-east-1:000000000000:elasticmapreduce:addStep.sync' is invalid

### ISSUE THREAD

**Issue by Anastasiia-Kosiak** [localstack/localstack#5149]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I started a localstack docker container on my laptop. I wrote a Python script using boto3 to create a stepfunction that submits a step to an EMR cluster. When I start an execution of the stepfunction, I get the following error message:
```
localstack_main | 2021-12-19 22:38:59.904: arn:aws:states:us-east-1:000000000000:execution:us-east-2_CreateClusterStateMachine:c83a3978-0a2b-460c-a439-1d0b35308511 : 
{"Type":"ExecutionFailed","PreviousEventId":2,"ExecutionFailedEventDetails":{"Error":"States.Runtime","Cause":"An error
 occurred while scheduling the state 'CopyTransform'. The provided ARN 'arn:aws:states:us-east-
1:000000000000:elasticmapreduce:addStep.sync' is invalid."}}
```

### Expected Behavior

I expect the stepunction to sumbit a step to an EMR cluster and finish its execution after it.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)
I have the following docker-compose.yml file:
```
version: "3.8"

services:
  localstack:
    container_name: localstack_main
    image: localstack/localstack
    ports: 
      - '4566-4597:4566-4597'
    environment:
      - EDGE_PORT=4566
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - SERVICES=s3,sqs,secretsmanager,emr,lambda,stepfunctions,sns,iam,ec2,es,serverless
      - DEFAULT_REGION=us-east-2
      - HOST_TMP_FOLDER=/tmp
      - LOCALSTACK_API_KEY=<my_API_key>
    volumes:
      - "/tmp/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

```
And I start the docker container with `docker-compose up`.   

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)
Here's my boto3 script, named `create-stepfunc.py`:
```
import json
import boto3

ip_address = '192.168.242.188'
sfn_client = boto3.client('stepfunctions', 'us-east-2', endpoint_url="http://{}:4566".format(ip_address))

asl_definition = {
  "Comment": "comment",
  "StartAt": "CopyTransform",
  "States": {
    "job": {
      "Type": "Task",
      "Resource": "arn:aws:states:::elasticmapreduce:addStep.sync",
      "InputPath": "$",
      "ResultPath": "$.TaskResults",
      "Parameters": {
        "ClusterId": "j-MYNWL4XHY53KQ",
        "Step": {
          "Name": "CopyTransform",
          "ActionOnFailure": "CONTINUE",
          "HadoopJarStep": {
            "Jar": "command-runner.jar",
            "Args.$": "States.Array('spark-submit','s3://source-code/job.py')"
          }
        }
      },
      "Catch": [],
      "End": True
    }
  }
}

response = sfn_client.create_state_machine(
    name='CopyTransform',
    definition=json.dumps(asl_definition),
    roleArn='arn:aws:iam::123456789012:role/DummyRole'
)
print(response)

```
I run the script: `python create-stepfunc.py`
And then start the execution with the following command:
`awslocal stepfunctions start-execution --state-machine-arn arn:aws:states:us-east-2:000000000000:stateMachine:CopyTransform`
After that I see an error message about the invalid ARN.

### Environment

```markdown
- OS: Ubuntu 20.04
- LocalStack: 0.13.0.8
```

### Anything else?

![Screenshot from 2021-12-20 00-57-20](https://user-images.githubusercontent.com/94955509/146693971-280be9b7-d134-4b80-b47b-b96ba4daed70.png)
![Screenshot from 2021-12-20 00-57-38](https://user-images.githubusercontent.com/94955509/146693978-38af0759-842e-4386-8fa2-0ca78ddad039.png)

**Comment by dominikschubert** [comment]
Thank you for reporting this. We're currently rethinking & rewriting part of the region support in stepfunctions. In the course of this rewrite we'll also tacke your issue :+1: 

You can follow the issue here for any new updates on the region support changes: #5030

**Comment by dominikschubert** [comment]
Just checked with the newer upstream version (1.8.1) and it seems unfortunately that they still didn't add support for the "optimized" EMR addStep task. Will close this since it is currently out of our hands unfortunately. 

Please note that the behavior can be achieved with using the more generalized aws-sdk task or alternatively a lambda task that adds this step for you.

**Comment by Anastasiia-Kosiak** [comment]
@dominikschubert Got it, thanks for your help with this!
