### ISSUE TITLE
During make install requirements are satisfied by host environment instead of virtual

### ISSUE THREAD

**Issue by vaclav-krajicek** [localstack/localstack#515]
Hi,
I have a suspicion that during 'make install', which is done on background (e.g. if I use java LocalstackTestRunner class for unittesting against localstack, and probably in other occasions), installation of python prerequisites is not done right because 
$(PIP_CMD) -q install -r requirements.txt is called with host system PYTHONPATH
while subsequently
PYTHONPATH=. exec python localstack/services/install.py testlibs)
is called with PYTHONPATH erased in Makefile's install target (/Makefile: 14-16)

Some of prerequisites (six, urllib3, etc.) are satisfied by host system in the installation step while they are not present in runtime (test phase later).

It might be the cause lot of complaints from users that localstacks reports invalid import in python code. Quick fix is to uninstall everything related on the host system and allow pip to install all prerequisites to virtualenv's site-packages.

As a permanent fix I would recommend to add PYTHONPATH=. before 'pip install -q install -r requirements.txt' in Makefile

What is your opinion about this?

**Comment by whummer** [comment]
Closing this one as outdated - should have been fixed in the meantime.
