### ISSUE TITLE
[SNS] MessageStrucure json is not supported

### ISSUE THREAD

**Issue by gitis** [localstack/localstack#516]
There is a requirement in SNS documentation which states:

> Set MessageStructure to json if you want to send a different message for each protocol. For example, using one publish action, you can send a short message to your SMS subscribers and a> longer message to your email subscribers. If you set MessageStructure to json, the value of the Message parameter must:
> * be a syntactically valid JSON object; and
> * contain at least a top-level JSON key of "default" with a value that is a string.

SNS in AWS production stripes the top-level json key "default" and sends only it's contents. Localstack leaves the "default" key in the message, causing inconsistencies between production and development environments.

**Comment by whummer** [comment]
Thanks for reporting @gitis . Would you be able to provide a small example with the SNS topic configuration, as well as the expected result? Thanks

**Comment by whummer** [comment]
Fixed in #668
