### ISSUE TITLE
CONN REFUSED for SQS from "aws-sdk"  but not for SQSClient from "aws-sdk/client-sqs"

### ISSUE THREAD

**Issue by ChaitraliPalasdeokar** [localstack/localstack#5163]
### Is there an existing issue for this?

- [X] I have searched the existing issues and read the documentation

### Question

I want to send messages to SQS from a lambda function and was writing integration test cases for it using localstack
I tried it with two methods-
1. By creating SQS object from "aws-sdk" library
```
import { SQS } from '@aws-sdk';
const sendMessageRequest: SendMessageRequest = {
      QueueUrl:
        'http://localhost:4566/000000000000/transaction-processor-queue-test.fifo',
      MessageBody:
        '{"accountId": 36002,"attributes": []}',
      MessageDeduplicationId: '123',
      MessageGroupId: '555443',
    }
 const sqs = new SQS(endpoint: http://${process.env.LOCALSTACK_HOSTNAME}:4566);
 await sqs.sendMessage(sendMessageRequest).promise()
```

2. By creating SQSClient object from 'aws-sdk/client-sqs' library
```
import { SendMessageRequest, SQSClient } from '@aws-sdk/client-sqs';
const sendMessageRequest: SendMessageRequest = {
      QueueUrl:
        'http://localhost:4566/000000000000/transaction-processor-queue-test.fifo',
      MessageBody:
        '{"accountId": 36002,"attributes": []}',
      MessageDeduplicationId: '123',
      MessageGroupId: '555443',
    }
const sqs = new SQS(endpoint: http://${process.env.LOCALSTACK_HOSTNAME}:4566);
await sqsClient.send(new SendMessageCommand(sendMessageRequest));
```
Added this line in docker-compose.yml

`- HOSTNAME_EXTERNAL=localstack`

The test case on local stack is running fine with SQSClient object but fails when used SQS object and throws ECONNREFUSED 127.0.0.1:4566 error. Both of the objects are using the same endpoint. Hence quite confused as in why the connection is getting refused for SQS object and why is it passing for SQSClient? Any particular difference between the two that I'm missing?

### Anything else?

https://github.com/localstack/localstack/issues/3562

**Comment by pinzon** [comment]
Hi @ChaitraliPalasdeokar, thank you for reporting the issue. It seems to me that it could have been a problem with the Library and not with LocalStack.  But it works flawlessly now.
 
I used this code to reproduced your issue. 
```typescript
import { SQS } from 'aws-sdk';
import { CreateQueueRequest, SendMessageRequest } from 'aws-sdk/clients/sqs';

const sqs = new SQS({ endpoint: "http://localhost:4566", region:"us-east-1" });

const sendMessageRequest: SendMessageRequest = {
  QueueUrl: 'http://localhost:4566/000000000000/transaction-processor-queue-test',
  MessageBody: '{"accountId": 36002,"attributes": []}',
}

const createQueueRequest: CreateQueueRequest = {
  QueueName: "transaction-processor-queue-test"
}


async function main() {
  await sqs.createQueue(createQueueRequest).promise()
  await sqs.sendMessage(sendMessageRequest).promise()
}
main();
```

I'm closing this issue but feel free to comment and provide your logs here if you still have the same problem.
