### ISSUE TITLE
SQS receive_message with "\r\n" in message body loses "\r"

### ISSUE THREAD

**Issue by baermat** [localstack/localstack#5172]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When programmatically sending an SQS message to a queue with a message body that contains "\r\n", the "\n" is lost.
sent    =     "{\r\n\"machineID\" : \"d357006e26ff47439e1ef894225d4307\"}"
received = "{\n\"machineID\" : \"d357006e26ff47439e1ef894225d4307\"}"

### Expected Behavior

When programmatically sending an SQS message to a queue with a message body that contains "\r\n", the message should stay the same
sent    =     "{\r\n\"machineID\" : \"d357006e26ff47439e1ef894225d4307\"}"
received = "{\n\"machineID\" : \"d357006e26ff47439e1ef894225d4307\"}"

### How are you starting LocalStack?

With the `localstack` script

### Steps To Reproduce

  localstack start

Then send a message programmatically, e.g.:

`
String queue ="dev-elh-queue";//"local-CSM-Connector-DIM";
queue="local-CSM-Connector-DIM";
final SqsClient client = SqsClient.builder()
        .endpointOverride(URI.create("http://localhost:4566"))
        .build();
final String qURL = client.getQueueUrl(GetQueueUrlRequest.builder().queueName(queue).build()).queueUrl();
String msg="{\r\n" + "\"machineID\" : \"d357006e26ff47439e1ef894225d4307\"" + "}";
client.purgeQueue(PurgeQueueRequest.builder().queueUrl(qURL).build());
client.sendMessage(SendMessageRequest.builder().queueUrl(qURL).messageBody(msg).build());
final Message message = client.receiveMessage(ReceiveMessageRequest.builder().queueUrl(qURL).build()).messages().get(0);
System.out.println(message);
`
This was the code the customer posted

### Environment

```markdown
- OS: Unkown
- LocalStack: Unknown
```

### Anything else?

Customer issue, see https://localstack-community.slack.com/archives/CMAFN2KSP/p1640085456219700
This was not reproducable with LS version 0.12.19.3 and all manual CLI calls. It was however reproducable with a python test 
`test_message_with_carriage_return`

**Comment by pinzon** [comment]
The fix has been merged to the Moto repository. It shouldn't take too long before being reflected in Localstack.
