### ISSUE TITLE
bug: Localstack SQS message processing 10 times slower in 0.13.2 vs 0.12.20

### ISSUE THREAD

**Issue by davy-oo** [localstack/localstack#5178]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When running LocalStack as a linux container on a Docker for Desktop on Windows configured for running Windows container, the processing of SQS messages are 10 times slower than in previous 0.12.20. If localstack and test is run on a linux container, the processing time is similar to the 0.12.20.

The attached example ([LocalstackSQSSlowness.zip](https://github.com/localstack/localstack/files/7770856/LocalstackSQSSlowness.zip)) creates 2 queues that processes messages and log the time it takes for each operation on a message:
- await SQS.ChangeMessageVisibilityAsync()
- await SQS.DeleteMessageAsync()
- await SQS.SendMessageAsync()

At the end of the test which last for 40s, the queues are deleted and the number of processed messages is printed.

On my laptop, about 70 messages can be processed in 40s vs about 700 on 0.12.20 version. Each of the calls are slower compared to 0.12.20.

Some logs from 0.13.2:
```
5:58:18 PM Changed message visibility aurppxosly Queue: http://localhost:4566/000000000000/testQueue_2 in 0.24s
5:58:18 PM Deleted message: hybxndioqj Queue: http://localhost:4566/000000000000/testQueue_1 in 0.24s
5:58:18 PM Deleted message: aurppxosly Queue: http://localhost:4566/000000000000/testQueue_2 in 0.23s
5:58:18 PM Created 2 messages on other queue: http://localhost:4566/000000000000/testQueue_1 in 0.49s
5:58:18 PM Created 2 messages on other queue: http://localhost:4566/000000000000/testQueue_2 in 0.48s
```

### Expected Behavior

Processing speed is back to the 0.12.20, about 700 messages can be processed in 40s.

Some logs from 0.12.20:

```
6:05:47 PM Changed message visibility bngkgyvkeb Queue: http://localhost:4566/000000000000/testQueue_1 in 0.02s
6:05:47 PM Deleted message: aytcwkvqdb Queue: http://localhost:4566/000000000000/testQueue_2 in 0.02s
6:05:47 PM Deleted message: bngkgyvkeb Queue: http://localhost:4566/000000000000/testQueue_1 in 0.02s
6:05:47 PM Created 2 messages on other queue: http://localhost:4566/000000000000/testQueue_2 in 0.06s
6:05:47 PM Created 2 messages on other queue: http://localhost:4566/000000000000/testQueue_1 in 0.05s
```

### How are you starting LocalStack?

With a `docker run` command

## Prepare the localstack environment:

1. Configure Docker for Desktop in "Windows container" mode, using WSL2 to run the linux containers. The C:\ProgramData\Docker\config\daemon.json should have ```"experimental": true``` settings.
2. Start Localstack in a powershell cmd.

```
  docker network create -d nat linux-dependencies
  docker run --network linux-dependencies --platform linux --name localstack_linux -d `
             -p 4566:4566 -e SERVICES=sqs,sns,logs -e EAGER_SERVICE_LOADING=1 `
             localstack/localstack:0.13.2
```

## Run the test

1. Build a Windows container that can run the attached test example using the attached zip
2. Run the container containing the test

```
  docker build -t thetest .
  docker run --rm --network linux-dependencies thetest:latest
```
Actual result: about 70 messages can be processed in 40s.

Expected result: About 700 messages can be processed in 40s, like in 0.12.20.

### Environment

```markdown
- OS: Windows 10
- LocalStack: 0.13.2
```

### Anything else?

C# solution to demonstrate the slowness
[LocalstackSQSSlowness.zip](https://github.com/localstack/localstack/files/7770856/LocalstackSQSSlowness.zip)

**Comment by thrau** [comment]
hi @davy-oo , thanks for the detailed report and the example code. Unrelated to this issue, we have recently added an experimental SQS provider which solves lots of performance problems of the old one, but may not yet be feature complete. It would be great if you could give it a try. You can enable it by adding the environment variable `PROVIDER_OVERRIDE_SQS=asf`.

Meanwhile we'll investigate what exactly caused the performance decrease.

**Comment by thrau** [comment]
I tried to reproduce this with Frederik's benchmark script used in #3998, but could not reproduce the issue. In fact, for some reason, throughput it even slower in 0.12.20 for me:

Here are the relevant results for 0.13.2/latest (`docker run --rm -it -p 4566:4566 localstack/localstack`):
```
sending finished, avg duration: 1.585s, total duration: 32.357
receiving+deleting finished, avg duration receive: 0.065s, avg duration delete: 0.023s, total duration: 87.526
```

And for 0.12.20 (`docker run --rm -it -p 4566:4566 localstack/localstack:0.12.20`)

```
sending finished, avg duration: 2.065s, total duration: 42.095
receiving+deleting finished, avg duration receive: 0.083s, avg duration delete: 0.027s, total duration: 109.925
```

**Comment by kicaj29** [comment]
I understand that you run your test in docker desktop configured as linux containers mode, correct?

I have suspicion that this problem exist only for docker desktop configured as windows containers mode.

Can you re-run this test on environment described by Davy in section "Prepare the localstack environment".
It means run docker desktop in windows container mode but with enabled experimental flag:

C:\ProgramData\Docker\config\daemon.json

`{
  "registry-mirrors": [],
  "insecure-registries": [],
  "debug": false,
  "experimental": true
}`

**Comment by davy-oo** [comment]
I updated  the description of this issue as I can confirm that when running localstack container with Docker for desktop using Linux containers works as expected for number of messages processed (about 600 processed). I would say this issue might be related to the switch to Debian base image and how this image behaves with docker networking/DNS.

**Comment by davy-oo** [comment]
@thrau I dug a bit more into the DNS issues and found out that ``/etc/hosts``` is not created when the image is started with Docker for desktop configured using Windows container and experimental flag set to true. If we add an ```/etc/hosts``` file with a single ```127.0.0.1  localhost``` line in the 0.13.2 running container, then the processing speed is about 800 messages for 40s, even better than 0.12.20(about 700 in 40s).
The /etc/hosts file is present on the 0.12.20 running container with the same configuration.

I also did run a test using docker for desktop configured using Linux containers, the /etc/hosts file is correctly created in 0.13.2.

Would it be possible to add this file to the image somehow? I'm not sure how this file get created by Debian but it seems it does not succeed doing it this specific case.

**Comment by davy-oo** [comment]
We did mitigate this issue for our case by adding an /etc/hosts file after the container has started with the following command:
```
docker exec localstack_linux python3 -c "print('\n127.0.0.1 localhost\n', file=open('/etc/hosts', 'a'))"
```

**Comment by thrau** [comment]
sorry for being unresponsive @davy-oo, i was offline a few days. those are fantastic insights, thanks so much for digging into it.

i'll try to reproduce the issue on my machine with docker desktop for windows

in the meantime /cc @dfangl, do you have any thoughts/insights on this?

**Comment by zorji** [comment]
I also had the same issue.
I have a test to batch insert 2002 messages into SQS with `sqs.sendMessageBatch`, so there are around 201 requests (each batch can support max 10 messages).

Before I upgrade to 0.13 from 0.12.17, it takes less than 10 seconds to complete but now it takes 126 seconds on average.

I noticed the first 20 requests were very fast and then it started to get slow.

**Comment by dfangl** [comment]
Oh, completely missed that ping.
As far as I know, the /etc/hosts file is mounted from the host system into the container on start, and any /etc/hosts file will be overridden. Still, it was present in 0.12.20 days (its present in alpine for some reason, did not look into that) but its not in debian:buster-slim (the current base image).
As example, this is a line from running `mount` inside debian:buster-slim:
```
/dev/mapper/cryptroot on /etc/hosts type ext4 (rw,relatime)
``` 
It seems this does not work correctly using this Windows container mode (have never worked with it, just guessing in this case).
I will investigate further using windows, but it seems manually creating this file is a possible solution. We could also add it to the image, since it gets overridden by docker (if that works) anyway.

**Comment by dfangl** [comment]
I can definitively reproduce a performance issue in this setting on my machine. For me, performance is cut in half, more or less. If I would have to guess, is that `localhost` lookups for internal requests take longer without the host file in this setting. 
We could add the file /etc/hosts and just let it override by "normal" docker behavior, like in alpine days. Thoughts on that @thrau ?

**Comment by dfangl** [comment]
Hi there! We did not go through with the workaround, as the new SQS implementation was on the way. 
This implementation is now the default, can you confirm the performance is better on `localstack/localstack:latest`?

**Comment by davy-oo** [comment]
I just reran the same test from description above (without /etc/host workaround):

- released localstack/localstack:**0.14.2** -> **50** messages processed in 40s
- localstack/localstack:**latest** -> **2** messages processed in 40 s. 

The latest one does not seem ok yet. Workaround is still needed to get fast.
I can see logs like following in the latest container. The logs do not appear in 0.14.2:
```
2022-05-18T12:48:32.582:WARNING:localstack.aws.protocol.serializer: Response object SendMessageResult contains a member which is not specified: ResponseMetadata
2022-05-18T12:48:52.866:WARNING:localstack.aws.protocol.serializer: Response object ReceiveMessageResult contains a member which is not specified: ResponseMetadata
```

**Comment by thrau** [comment]
Hey Davy @davy-oo, the PR i linked should fix that issue. Could you please check if you still have the same problems with latest?

**Comment by davy-oo** [comment]
With latest being version 0.14.3 from 2022-05-23:
I ran without the /etc/hosts workaround. This now gives the same 50 messages per 40s on both 0.14.2 and latest.

When I add the /etc/hosts workaround, the numbers looks like:
- **0.14.2**: **880** messages per 40s
- **latest**: **1050** messages per 40s

The original issue is still there, but the messages are processed faster on latest when the workaround is applied.
Is it possible to add the localhost entry to /etc/hosts so that workaround is not needed?

**Comment by dfangl** [comment]
Hi @davy-oo !
We have implemented the workaround in `localstack/localstack:latest`, would it be possible for you to try now?

**Comment by davy-oo** [comment]
I can confirm that with latest being:

> LocalStack version: 0.14.3.1
> LocalStack build date: 2022-05-25
> LocalStack build git hash: 496e6015

The issue is fixed and speed is as above on docker in windows container mode. I think this can now be closed.

**Comment by thrau** [comment]
great, thanks @davy-oo for all your input!
