### ISSUE TITLE
bug: S3 MultipartsUpload ListParts Deserialization error

### ISSUE THREAD

**Issue by dlsrb6342** [localstack/localstack#5191]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am using localstack S3 Multipart Upload with `aws-sdk-go-v2`. I got `failed to decode response body, expected IsTruncated to be of type *bool, got []uint8 instead` error message from `ListParts` API. This occurs only Multipart Upload doesn't have any part yet. The response sample is below.
`IsTruncated` should be boolean.
```xml
<?xml version="1.0" encoding="UTF-8"?>
<ListPartsResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
  <Bucket>test-bucket</Bucket>
  <Key>BSfR2buH4kh48xEn9cpvU7</Key>
  <UploadId>GrfT5pW5kx5kU9BXbMIF4CPs0E4ZVeMIEtf40FEiabSZNDZHqx86ujmA</UploadId>
  <StorageClass>STANDARD</StorageClass>
  <Initiator>
    <ID>...</ID>
    <DisplayName>...</DisplayName>
  </Initiator>
  <Owner>
    <ID>...</ID>
    <DisplayName>...</DisplayName>
  </Owner>
  <PartNumberMarker>0</PartNumberMarker>
  <NextPartNumberMarker>0</NextPartNumberMarker>
  <MaxParts>1000</MaxParts>
  <IsTruncated>[]</IsTruncated>
</ListPartsResult>
```

### Expected Behavior

 I tested with AWS S3 and it works well. You can see `IsTruncated` is `false` below. `moto-ext` and `moto` should return boolean type response to `IsTruncated`. 

```xml
<?xml version="1.0" encoding="UTF-8"?>
<ListPartsResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
  <Bucket>test-bucket</Bucket>
  <Key>nDh3ZFVnyESMeVTuRgvkZk</Key>
  <UploadId>76E1sfmU6V_UqArz8GCKPzt6_PRnbRW08cNLeSmlAomDSBVMnWmiSQqvSaytlGbA3tLqr45_sIZSFP9KpMZiO8XyPjkGSX2ghhoiHPnylzIvQM0i_8otyi.Ro_Dqy2ml000M15q7v0wIujYNkvxHJQVkC7bEiVKKKEcReTKyqBA-</UploadId>
  <Initiator>
    <ID>...</ID>
    <DisplayName>...</DisplayName>
  </Initiator>
  <Owner>
    <ID>...</ID>
  </Owner>
  <StorageClass>STANDARD</StorageClass>
  <PartNumberMarker>0</PartNumberMarker>
  <NextPartNumberMarker>0</NextPartNumberMarker>
  <MaxParts>1000</MaxParts>
  <IsTruncated>false</IsTruncated>
</ListPartsResult>
```

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)
```yaml
// docker-compose.yaml
version: '3'
services:
  localstack:
    image: localstack/localstack
    ports:
      - 4566:4566
    environment:
      KINESIS_PROVIDER: kinesis-mock
      SERVICES: dynamodb,s3
      DEFAULT_REGION: ap-northeast-2
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)
awslocal s3 mb s3://test-bucket

### Environment

```markdown
- OS: MacOS BigSur
- LocalStack: latest
```

### Anything else?

I tested python client with [moto](https://github.com/spulec/moto) and [moto-ext](https://github.com/localstack/moto). 
```python3
@mock_s3
def test_multipart_upload_should_return_0():
    bucket = "dummybucket"
    s3_client = boto3.client("s3", "us-east-1")

    key = "test_file"
    s3_client.create_bucket(Bucket=bucket)

    mpu = s3_client.create_multipart_upload(Bucket=bucket, Key=key)
    mpu_id = mpu["UploadId"]

    list_parts_result = s3_client.list_parts(Bucket=bucket, Key=key, UploadId=mpu_id)
    print(list_parts_result)
```

There is no error and result is correct. I think python xml parser works well with empty array `IsTruncated`.

**Comment by dlsrb6342** [comment]
https://github.com/spulec/moto/pull/4724

I submit PR to fix this issue.

**Comment by dlsrb6342** [comment]
@whummer 
Could you check this issue? This fix is already merged to "spulec/moto". It need to apply to moto-ext.

**Comment by macnev2013** [comment]
Hi @dlsrb6342 , Thanks for reporting the issue and apologies for the delay.

This issue has been fixed in the `latest` version of `Localstack`. Can you please give it another try?

Feel free to reopen the issue, if it still persists. Thanks.
