### ISSUE TITLE
bug: Wrong username created in RDS Postgres via CDK/Cloudformation

### ISSUE THREAD

**Issue by jcpage** [localstack/localstack#5195]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I deployed an Aurora Postgres DB, looked up the port and secrets, but when I tried to connect to it, it said "role xxx doesn't exist".  I took a wild guess and connected as 'postgres' user, which did work (with no password... hmm).  When I looked at the users/roles configured, I saw that the one I had tried to create actually used ARN to the secret and not the secret value itself.

Role name                            |                         Attributes                         | Member of 
-----------------------------------------------------------------+---------------------
postgres                                                        | Superuser, Create role, Create DB, Replication, Bypass RLS | {}
 **{{resolve:secretsmanager:arn:aws:secretsmanager:us-east-1:00000** | Superuser                                                  | {}

The username & password are stored correctly in secretsmanager, confirmed via the web app UI.

Here is the CDK code I used to create the secret & db - this deploys as expected to AWS, so I believe it's correct.

```
const dbSecret = new Secret(this, `DbSecret`, {
      generateSecretString: {
        secretStringTemplate: JSON.stringify({ username: `splycer` }),
        excludePunctuation: true,
        includeSpace: false,
        generateStringKey: `password`,
      },
    })
    const rdsSecurityGroup = new SecurityGroup(
      this,
      `RdsSecurityGroup`,
      {
        allowAllOutbound: false,
        securityGroupName: `RdsSecurityGroup`,
        vpc,
      }
    )
    const database = new DatabaseCluster(this, `RdsDatabase`, {
      engine: DatabaseClusterEngine.auroraPostgres({
        version: AuroraPostgresEngineVersion.VER_13_4,
      }),
      credentials: Credentials.fromSecret(dbSecret),
      instanceProps: {
        instanceType: InstanceType.of(
          InstanceClass.BURSTABLE3,
          InstanceSize.MEDIUM
        ),
        securityGroups: [rdsSecurityGroup],
        vpcSubnets: {
          subnetType: SubnetType.PRIVATE_ISOLATED,
        },
        vpc,
      },
      instances: 1,
      defaultDatabaseName: dbConfig.databaseName,
    })


```

### Expected Behavior

Database user created should be the resolved value of the username in the secret, not the pre-processed template from Cloudformation.

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    localstack start

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    cdklocal deploy   -  see above for CDK code snippet.

### Environment

```markdown
- OS: MacOS 12.1 arm64 (M1 Max)
- LocalStack: 0.13.1.2,  Pro Trial Key
```

**Comment by jcpage** [comment]
Probably doesn't add much, but here are the logs.  I notice it also tries to create a separate server on the same port (then tries a different one) - is there a reason it creates another server instance for a "test" database?

2021-12-28T05:59:25.543:INFO:localstack_ext.services.rds.db_utils: Starting RDS server on port 4512 (backend port 40655) - database "splyce", user "{{resolve:secretsmanager:arn:aws:secretsmanager:us-east-1:000000000000:secret:LocalStack-DbSecret685A0FA5-f25af328-JdIMAT:SecretString:username::}}"
2021-12-28T05:59:29.059:INFO:localstack_ext.utils.postgresql: Starting PostgreSQL query listener/rewriter on port 4512->40655
2021-12-28T05:59:30.403:WARNING:localstack_ext.services.rds.db_utils: Another PostgreSQL instance already exists on port 4512 with key cluster/us-east-1/dbc-93dca92b
2021-12-28T05:59:32.610:INFO:localstack_ext.services.rds.db_utils: Starting RDS server on port 4510 (backend port 53543) - database "test", user "test"
2021-12-28T05:59:36.053:INFO:localstack_ext.utils.postgresql: Starting PostgreSQL query listener/rewriter on port 4510->53543

**Comment by whummer** [comment]
Thanks for reporting @jcpage , this should be fixed in the meantime. Can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists.. Thanks for your help!

**Comment by jcpage** [comment]
Hey - I can try to see if this specific bit is working, but I am hitting a bigger issue that prevents me from really testing it end-to-end - "cdklocal deploy" always fails on even the most trivial CDK app stack when I am using the Pro trial.  My trivial example succeeds when not setting a LOCALSTACK_API_KEY.

Error is below - I have poked around in logs and haven't been able to find any root cause - the resources seem to get created but it always fails at the end.   Anyway, I'll file a separate issue for this, but since RDS is a Pro feature may not be able to verify the other fix until it's resolved.

```
 ❌  LocalStack failed: Error: The stack named LocalStack failed to deploy: CREATE_FAILED (Deployment failed)
    at Object.waitForStackDeploy (/Users/jake/.nvm/versions/node/v16.13.1/lib/node_modules/aws-cdk/lib/api/util/cloudformation.ts:309:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at prepareAndExecuteChangeSet (/Users/jake/.nvm/versions/node/v16.13.1/lib/node_modules/aws-cdk/lib/api/deploy-stack.ts:351:26)
    at CdkToolkit.deploy (/Users/jake/.nvm/versions/node/v16.13.1/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:194:24)
    at initCommandLine (/Users/jake/.nvm/versions/node/v16.13.1/lib/node_modules/aws-cdk/bin/cdk.ts:267:9)
The stack named LocalStack failed to deploy: CREATE_FAILED (Deployment failed)
```

**Comment by jcpage** [comment]
Re: dynamic reference & db username - I was able to verify it as the secret and DB were created before it failed.  The username is created successfully.  It's created without a password but accepts a password when connecting so I don't think that's essential for local testing - but may be important for some, ie a nice to have to verify E2E deployment as managing secrets can be a bit trick to test...

**Comment by whummer** [comment]
Thanks for the update @jcpage - can you please share a minimal repro example of your CDK app stack? We'll be happy to dig into it in more detail to get it resolved.. Thanks!

**Comment by jcpage** [comment]
Hey - filed in #5210.  Thanks!
