### ISSUE TITLE
s3 api ignores ExposeHeaders CORS rule

### ISSUE THREAD

**Issue by ozsay** [localstack/localstack#520]
looks like setting ExposeHeaders has no effect on requests to s3 (headers such as `x-amz-version-id` don't reach the clients) for browser-based uploads. 

http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectPOST.html

**Comment by whummer** [comment]
Thanks for reporting @ozsay , would you be able to a pull request with the required changes? A good starting point would be the [`add_cors_headers`](https://github.com/localstack/localstack/blob/fc097dc2cfe95603497682eadcb526ec6642a414/localstack/services/s3/s3_listener.py#L197-L212) function in `s3_listener.py`. I'd be happy to provide some guidance for the implementation if needed. Thanks

**Comment by whummer** [comment]
Initial support for `ExposeHeaders` has been added in #571 . Can you please give it a try with the latest version @ozsay

**Comment by ozsay** [comment]
@whummer thanks! 

looking at the PR it appears that it might work. Unfortunately, for my case, i need specifically the `x-amz-version-id` header. 

but, it might have fixed a problem for someone else so thanks anyways. hopefully support for versions will be added soon :)

**Comment by bne** [comment]
@whummer do you see the completed implementation of ExposeHeaders to add the remaining headers and their value from `request_headers` (after checking if there was a relevant key of course).

Apologies, I haven't tried this out, but something along the lines of:

```
elif header in request_headers:
    response.headers[header] = request_headers.get(header)
```
here: https://github.com/localstack/localstack/blob/71c5d39e6bbcd7d6d47ee66e6535a8b8d8e0b17f/localstack/services/s3/s3_listener.py#L236
