### ISSUE TITLE
Lambda fails to access S3 file

### ISSUE THREAD

**Issue by lixinchina1** [localstack/localstack#5209]
### Is there an existing issue for this?

- [X] I have searched the existing issues and read the documentation

### Question

I am cloning a working terraform config that pushing configuraiton to AWS to localstack, obvious changes the necessary info to point to localstack.  However, I am seeing this error when lambda trying to read a file which was just successfully unload:

` "message": "{\"bucket\":\"mybucket\",\"error\":\"InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records.\\n\\tstatus code: 403, request id: H1EV53RGW3K5B5AT, host id: CjqkpuQuOAFbOeirQ8rqRwZM5y3rGSwuXmTc7P/4uY1YArGTtFbAWTodk4dwpHsu/aF+1WeTb6s=\",\"key\":\"xxxx/2021-07-02-01-00-07.888111111.gz\",\"msg\":\"failed to get object\",\"ts\":\"2021-12-29T23:42:29.168544773Z\"}",`

I am able to download the file via aws cli so it's definitely there.  I follow this past thread:

https://github.com/localstack/localstack/issues/1568

it mentions about setting the permission in a policy attached to the lambda role (which I already did and worked fine in AWS).  I then attached an inline policy to the role to make sure it has the permission:

```
{
            "Sid": "VisualEditor1",
            "Effect": "Allow",
            "Action": [
                "s3:PutObject",
                "s3:GetObject",
                "s3:ListBucket"
            ],
            "Resource": [
                "mybucket/myresource/*"
            ]
        },
} 
```
but still same error.  I am running out of ideas :(

I start all the services with: localstack start -d

and this is the config I injected to tf main.ty:

```
provider "aws" {
  region = "us-east-1"
  access_key = "localstack"
  secret_key = "localstack"
  skip_credentials_validation = true
  skip_requesting_account_id = true
  skip_metadata_api_check = true
  s3_force_path_style = true
  endpoints {
    s3 = "http://localhost:4566"
    lambda = "http://localhost:4566"
    dynamodb = "http://localhost:4566"
    cloudwatch = "http://localhost:4566"
    iam = "http://localhost:4566"
    events = "http://localhost:4566"
    secretsmanager = "http://localhost:4566"
    resourcegroups = "http://localhost:4566"
  }
}

```

**Comment by whummer** [comment]
Hi @lixinchina1 , thanks for reaching out. Can you please share the relevant parts of your Lambda handler code? 

Please note that you'll need to configure any AWS SDK clients in your Lambda code to use `http://$LOCALSTACK_HOSTNAME:4566` as the endpoint URL, where `$LOCALSTACK_HOSTNAME` is an environment variable that is accessible from within your Lambda handler code.

Please note that in the Pro version of LocalStack, we have more advanced additional features that allow transparent injection of the local endpoints into your Lambda handlers (without modification), but in the community version the preferred way is to read the `$LOCALSTACK_HOSTNAME` endpoint from the environment. More details can be found here: https://docs.localstack.cloud/tools/local-endpoint-injection

Hope that helps - please keep us posted how it goes.. Thanks!
