### ISSUE TITLE
Clarify LEGACY_PERSISTENCE meaning and effect on Community version

### ISSUE THREAD

**Issue by cbromberg** [localstack/localstack#5219]
From what I have found the following sentence is the only existing documentation about the meaning of LEGACY_PERSISTENCE

> Whether to enable legacy persistence mechanism based on API calls record&replay (deprecated). Only relevant for Community version, not relevant for advanced persistence mechanism in Pro.

What I understand from this sentence (and that might be wrong) is that services that use recorded_api_calls.json as persistence mechanism will loose persistence - that is loose the ability to persist data longer than the lifetime of a container. 
This would mean S3 would loose persistence.
On the other hand other services - like ElasticSearch and DynamoDB - will continue to be persisted into their 'native' persistence format.

Is that correct? Please clarify - also would that mean that data is still persistent inside a (running or stopped) container as long as the container is not recreated (e.g. docker-compose down)?
Thanks in advance, Chris

**Comment by cbromberg** [comment]
Btw. I came from this page: https://docs.localstack.cloud/localstack/configuration/

**Comment by whummer** [comment]
Hi @cbromberg , thanks for asking this question. 

> What I understand from this sentence (and that might be wrong) is that services that use recorded_api_calls.json as persistence mechanism will loose persistence - that is loose the ability to persist data longer than the lifetime of a container.
This would mean S3 would loose persistence.

That is correct. However, as you correctly pointed out, other services that have custom persistence enabled should not be affected.

Any mechanism that can preserve the in-memory state would still work, i.e., `docker-compose down`/`up` would _not_ work (as it restarts the init processes in the container), but `docker-compose pause`/`unpause` should continue to work. 👍

**Comment by cbromberg** [comment]
Hi @whummer - thanks for answering, I think adding that information to  https://docs.localstack.cloud/localstack/configuration/ or even on a separate page (which is linked from the explanation of the LEGACY_PERSISTENCE variable) and a list of services that loose 'external persistence' (likewise a list of services that still have an 'external persistence') would be helpful to many of your users (and contributors).

Cheers, Chris
