### ISSUE TITLE
DynamoDB Stream MODIFY

### ISSUE THREAD

**Issue by adriangalera** [localstack/localstack#522]
Hi,
I am using Dynamo DB + Dynamo DB Streams + Lambda on localstack doker container.

When I perform a put item everything works fine and the lambda function is working OK.

However, when I perform a put item on an already inserted item, I was expecting a MODIFY record in the DynamoDB stream. In the DynamoDB the update takes place while in the Stream I get a INSERT record.

**Comment by adriangalera** [comment]
With update-item operation, generate the MODIFY event correctly.

**Comment by whummer** [comment]
Thanks for reporting @adriangalera . This should be fixed in #542 - can you please give it a try with the latest version? Thanks

**Comment by whummer** [comment]
Closing this issue. Please re-open or comment here if the problem persists.
