### ISSUE TITLE
bug: HTTP Proxy integrations take more specificity than explicitly defined resources

### ISSUE THREAD

**Issue by ajhaining** [localstack/localstack#5226]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm trying to use the HTTP_PROXY feature to provide a fallback to an old API whilst the endpoints are replaced with API GW + Lambda.

I currently have an API Gateway set up similar to the following:

```
/resource
    /{proxy+}
        ANY -> HTTP_PROXY
    /test
        GET -> AWS_PROXY -> Lambda
```

When I do a request to `http://localhost:4566/restapis/uslhbxmpgd/v1/_user_request_/resource/test` the `{proxy+}` resource catches the request.

I have tested the configuration in AWS and this behaviour isn't present. The `/test` catches the request and forwards an event through to the Lambda Integration.

### Expected Behavior

`{proxy+}` to have lowest possible specificity if other resources are defined at the same level, meaning it should only catch requests that don't have another matching resource.

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    localstack start

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

I'm using terraform to configure the environments:

```hcl
resource "aws_api_gateway_resource" "resource" {
  rest_api_id = aws_api_gateway_rest_api.api.id
  parent_id   = aws_api_gateway_rest_api.api.root_resource_id
  path_part   = "resource"
}

resource "aws_api_gateway_resource" "fallback-proxy-resource" {
  rest_api_id = aws_api_gateway_rest_api.api.id
  parent_id   = aws_api_gateway_resource.resource.id
  path_part   = "{proxy+}"
}

resource "aws_api_gateway_method" "fallback-proxy-method" {
  rest_api_id   = aws_api_gateway_rest_api.api.id
  resource_id   = aws_api_gateway_resource.fallback-proxy-resource.id
  http_method   = "ANY"
  authorization = "NONE"

  request_parameters = {
    "method.request.path.proxy"           = true
    "method.request.header.authorization" = false
  }
}

resource "aws_api_gateway_integration" "fallback-proxy-method-integration" {
  rest_api_id             = aws_api_gateway_rest_api.api.id
  resource_id             = aws_api_gateway_resource.fallback-proxy-resource.id
  http_method             = aws_api_gateway_method.fallback-proxy-method.http_method
  type                    = "HTTP_PROXY"
  integration_http_method = "ANY"
  uri                     = "https://httpbin.org/anything/{proxy}"

  request_parameters = {
    "integration.request.path.proxy"           = "method.request.path.proxy"
    "integration.request.header.authorization" = "method.request.header.authorization"
  }
}

resource "aws_api_gateway_resource" "test-resource" {
  rest_api_id = aws_api_gateway_rest_api.api.id
  parent_id   = aws_api_gateway_resource.resource.id
  path_part   = "test"
}

resource "aws_api_gateway_method" "test-GET-method" {
  rest_api_id   = aws_api_gateway_rest_api.api.id
  resource_id   = aws_api_gateway_resource.test-resource.id
  http_method   = "GET"
  authorization = "NONE"
}

resource "aws_api_gateway_integration" "test-GET-method-integration" {
  rest_api_id             = aws_api_gateway_rest_api.api.id
  resource_id             = aws_api_gateway_resource.test-resource.id
  http_method             = aws_api_gateway_method.test-GET-method.http_method
  integration_http_method = "POST"
  type                    = "AWS_PROXY"
  uri                     = "arn..."
}
```

### Environment

```markdown
- OS: macOS 12.0.1
- LocalStack: 0.13.3 and 0.13.2
```

### Anything else?

I've tested using versions pre and post the fix for other HTTP proxy issues by @calvernaz in #5212 and it doesn't seem to be related.

**Comment by calvernaz** [comment]
Reproducible with [TF](https://gist.github.com/calvernaz/c50b6ffff11584b7ba827fad3fc72048)

**Comment by calvernaz** [comment]
Hi @ajhaining, thanks for reporting this. I merged a fix for this, can you try the latest version?

**Comment by ajhaining** [comment]
Just tested, working great! Thanks for sorting this so quickly @calvernaz
