### ISSUE TITLE
bug: EventBridge discards request headers and parameters for scheduled API Destinations calls

### ISSUE THREAD

**Issue by bentcoder** [localstack/localstack#5229]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am using Localstack in local environment to schedule cron calls every minute to a dummy POST endpoint (*using [https://webhook.site/](https://webhook.site/)*) which works fine. However, only the body is kept but the request headers, query string parameters and path parameters are all discarded. Whether I test this with AWS CLI or with a Golang example, the issue still persist.

### Expected Behavior

The request headers, query string parameters and path parameters are kept in the request.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

I am giving a Golang example to help you prevent manual copy+paste job.

1. Bring up Localstack container first.
2. Get yourself a webhook URL from [https://webhook.site/](https://webhook.site/).
3. Replace `https://webhook.site/your-uuid-goes-here` in the code below with yours.
4. Run `$ go run main.go` command.
5. Wait for 1 minute and check the webhook page to see request details.

```golang
package main

import (
	"log"

	"github.com/aws/aws-sdk-go/aws"
	"github.com/aws/aws-sdk-go/aws/session"
	"github.com/aws/aws-sdk-go/service/eventbridge"
)

func main() {
	ses, err := session.NewSessionWithOptions(session.Options{
		Profile: "localstack",
		Config: aws.Config{
			Region:   aws.String("eu-west-1"),
			Endpoint: aws.String("http://localhost:4566"),
		},
	})
	if err != nil {
		log.Fatalln(err)
	}

	evb := eventbridge.New(ses)

	// Create Rule -------------------------------------------------------------
	outRule, err := evb.PutRule(&eventbridge.PutRuleInput{
		Name:               aws.String("http-cron-rule"),
		ScheduleExpression: aws.String("cron(* * * * * *)"),
	})
	if err != nil {
		log.Fatalln(err)
	}
	_ = outRule

	// Create Connection -------------------------------------------------------
	outConn, err := evb.CreateConnection(&eventbridge.CreateConnectionInput{
		AuthParameters: &eventbridge.CreateConnectionAuthRequestParameters{
			BasicAuthParameters: &eventbridge.CreateConnectionBasicAuthRequestParameters{
				Password: aws.String("hello"),
				Username: aws.String("world"),
			},
			InvocationHttpParameters: &eventbridge.ConnectionHttpParameters{
				BodyParameters: []*eventbridge.ConnectionBodyParameter{{
					Key:           aws.String("body_key_x"),
					Value:         aws.String("body_val_x"),
					IsValueSecret: aws.Bool(false),
				}},
				HeaderParameters: []*eventbridge.ConnectionHeaderParameter{{
					Key:           aws.String("hdr_key_x"),
					Value:         aws.String("hdr_val_x"),
					IsValueSecret: aws.Bool(false),
				}},
				QueryStringParameters: []*eventbridge.ConnectionQueryStringParameter{{
					Key:           aws.String("qry_key_x"),
					Value:         aws.String("qry_val_x"),
					IsValueSecret: aws.Bool(true),
				}},
			},
		},
		AuthorizationType: aws.String("Basic"),
		Name:              aws.String("http-connection"),
	})
	if err != nil {
		log.Fatalln(err)
	}

	// Create Api Destination---------------------------------------------------
	outDest, err := evb.CreateApiDestination(&eventbridge.CreateApiDestinationInput{
		ConnectionArn:      outConn.ConnectionArn,
		HttpMethod:         aws.String("POST"),
		InvocationEndpoint: aws.String("https://webhook.site/your-uuid-goes-here"), // Change this to yours
		Name:               aws.String("http-api-destination"),
	})
	if err != nil {
		log.Fatalln(err)
	}
	// outDest.ApiDestinationArn

	// Create Target -----------------------------------------------------------
	outTarg, err := evb.PutTargets(&eventbridge.PutTargetsInput{
		Rule: aws.String("http-cron-rule"),
		Targets: []*eventbridge.Target{
			{
				Id:    aws.String("http-target-1"),
				Arn:   outDest.ApiDestinationArn,
				Input: aws.String(`{"body_key":"body_val"}`),
				HttpParameters: &eventbridge.HttpParameters{
					HeaderParameters:      map[string]*string{"hdr_key": aws.String("hed_val")},
					PathParameterValues:   []*string{aws.String("par_1")},
					QueryStringParameters: map[string]*string{"qry_key": aws.String("qry_val")},
				},
			},
		},
	})
	if err != nil {
		log.Fatalln(err)
	}
	_ = outTarg
}
```

**Logs**

```bash
localstack    | DEBUG:localstack.services.events.events_listener: Notifying 1 targets in response to triggered Events rule http-cron-rule
localstack    | DEBUG:localstack.utils.aws.message_forwarding: Calling EventBridge API destination (state "ACTIVE"): POST https://webhook.site/your-uuid-goes-here
```

### Environment

```markdown
- OS: Mac OS
- LocalStack: latest
```

### Anything else?

Following the example [here](https://aws.amazon.com/blogs/compute/using-api-destinations-with-amazon-eventbridge/).

**Comment by bentcoder** [comment]
Hi @calvernaz 
I see you have done [this piece work](https://github.com/localstack/localstack/commit/f829aac7e2af1754eb7f70a1f7369ce5e17764ed) and I wonder if there is anything else could be done to solve the issue I described above? FYI - I pulled the latest image and nothing has changed.
Thanks

**Comment by pinzon** [comment]
The PR that fixes this issue has been merged. Make sure to pull the latest version of Localstack.

**Comment by bentcoder** [comment]
I've just managed to test this again with the latest image. So the findings are:

[create connection](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/events/create-connection.html)

Body, header and query string key-values pairs are all handled just fine. 👍 

---

[put-targets](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/events/put-targets.html)

Only body key-value pairs are handled. Both header and query string key-values pairs are still ignored.

> .... If you’re using ApiDestinations, the corresponding Connection can also have these values configured. In case of any conflicting keys, values from the Connection take precedence.

Whether you give conflicting keys or not, they always get ignored. If there is no conflict, I guess these new additions should be merged in the request.

**Comment by pinzon** [comment]
@bentcoder thank you so much for the feedback and the testing code. I'll work on it as soon as a I have time.

**Comment by bentcoder** [comment]
@pinzon Thanks for this. I can confirm that everything works **apart from** the base64 encoding of authorization header. It still goes as a plain string `Basic hello:world` rather than `Basic aGVsbG86d29ybGQ=`. I tested it more than one app just to make sure.

```bash
aws --profile localstack --endpoint-url http://localhost:4566 events create-connection \
    --name some-name \
    --authorization-type Basic \
    --auth-parameters "{\"BasicAuthParameters\":{\"Username\":\"hello\",\"Password\":\"world\"}}"
```
