### ISSUE TITLE
bug: GetAccountAuthorizationDetails Lacks User Tags Field

### ISSUE THREAD

**Issue by ncc-erik-steringer** [localstack/localstack#5230]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The operation `iam:GetAccountAuthorizationDetails` does not appear to behave the same as in AWS IAM. 

When calling AWS via AWS CLI (aws-cli/1.22.27 botocore/1.23.27, `aws iam get-account-authorization-details`), the `UserDetailList` field includes all the users as well as a `Tags` field.

When calling LocalStack (0.13.2.1) via AWS CLI + botocore, the `UserDetailList` field does not include that `Tags` field.

(Boto3 details: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/iam.html#IAM.Client.get_account_authorization_details)

It also appears that the IAM Roles are being returned with `Tags`.

### Expected Behavior

I'd expect LocalStack to return the `Tags` field in the `UserDetailsList` field for each IAM User.

### How are you starting LocalStack?

With the `localstack` script

### Steps To Reproduce

```bash
localstack start -d
terraform init
terraform apply  # with main.tf creating iam users/roles that are tagged
aws --endpoint-url http://localhost:4566 iam get-account-authorization-details --filter User
```

### Environment

```markdown
- OS: Ubuntu 20.04
- LocalStack: 0.13.2.1
```

**Comment by dfangl** [comment]
Thank you for reporting this!
This has now been fixed upstream and will make it into the :latest image soon.
