### ISSUE TITLE
bug: (Reopen) SQS FIFO queue. The request include parameter that is not valid for this queue type

### ISSUE THREAD

**Issue by intptr-t** [localstack/localstack#5236]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```bash
% awslocal sqs create-queue --queue-name "test.fifo" --attributes "ContentBasedDeduplication=true,FifoQueue=true"
{
    "QueueUrl": "http://localhost:4566/000000000000/test.fifo"
}

% awslocal sqs send-message --queue-url "http://localhost:4566/000000000000/test.fifo" --message-body "__dummy__" --message-group-id "__dummy__group_id__" --message-deduplication-id "__dummy__id__"
An error occurred (InvalidParameterValue) when calling the SendMessage operation: Value __dummy__group_id__ for parameter MessageGroupId is invalid. Reason: The request include parameter that is not valid for this queue type.
```

### Expected Behavior

It will behave the same as the real thing.

```bash
%aws sqs create-queue --queue-name "test.fifo" --attributes "ContentBasedDeduplication=true,FifoQueue=true"
{
    "QueueUrl": "https://sqs.ap-northeast-1.amazonaws.com/************/test.fifo"
}

% aws sqs send-message --queue-url "https://sqs.ap-northeast-1.amazonaws.com/************/test.fifo" --message-body "__dummy__" --message-group-id "__dummy__group_id__" --message-deduplication-id "__dummy__id__"
{
    "MD5OfMessageBody": "6240564be04a846edf0d616f3be37f1f",
    "MessageId": "3ea8e32a-7ec0-4603-9247-257d0d8bfc3e",
    "SequenceNumber": "18866968061922799616"
}
```

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

Copy [docker-compose.yml](https://github.com/localstack/localstack/blob/master/docker-compose.yml), enable SQS, and start it.

### Environment

- OS:

```
% sw_vers
ProductName:	macOS
ProductVersion:	12.1
BuildVersion:	21C52
```

- LocalStack: 0.13.2

### Anything else?

Since the event was reproduced, I have reopened.
previous issue: https://github.com/localstack/localstack/issues/2705

**Comment by SwatsonCodes** [comment]
I am unable to reproduce this in version `0.13.3`

**Comment by intptr-t** [comment]
@SwatsonCodes 
Thanks for your comments.
I updated to 0.13.3 and it doesn't reproduce anymore.

**Comment by sergey-telpuk** [comment]
@intptr-t Hello, It dosent work again in 0.13.3. I have this error

**Comment by intptr-t** [comment]
@sergey-telpuk @dfangl 
In my environment, it works as expected when generated from the CLI.
However, when I generate a SQS queue from Cloudformation(in localstack), `FifoQueue` and `ContentBasedDeduplication` are not set correctly, and it seems to be generated as a standard queue.

There seems to be a problem with patterns that are generated without APIs such as CLI.

I'm not familiar with the localstack code, so I'll wait until someone fixes it...

**template.yml**
```yml
AWSTemplateFormatVersion: 2010-09-09
Description: testing

Resources:
  TestQueue:
    Type: AWS::SQS::Queue
    Properties:
      ContentBasedDeduplication: true
      DelaySeconds: 0
      FifoQueue: true
      KmsDataKeyReusePeriodSeconds: 86400
      KmsMasterKeyId: alias/aws/sqs
      MaximumMessageSize: 262144
      MessageRetentionPeriod: 345600
      QueueName: 'create-from-cfn.fifo'
      ReceiveMessageWaitTimeSeconds: 0
      VisibilityTimeout: 900
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
```

**deploy command**
```
awslocal cloudformation deploy --template-file template.yml --stack-name TestStack --capabilities CAPABILITY_IAM

or 

awslocal cloudformation create-stack --template-body file://template.yml --stack-name  TestStack --capabilities CAPABILITY_IAM

```

**check attributes**

```
awslocal sqs get-queue-attributes --queue-url "http://localhost:4566/000000000000/create-from-cfn.fifo" --attribute-names All
{
    "Attributes": {
        "ApproximateNumberOfMessages": "0",
        "ApproximateNumberOfMessagesDelayed": "0",
        "ApproximateNumberOfMessagesNotVisible": "0",
        "CreatedTimestamp": "1643637734.9506",
        "DelaySeconds": "0",
        "LastModifiedTimestamp": "1643637734.9506",
        "MaximumMessageSize": "262144",
        "MessageRetentionPeriod": "345600",
        "QueueArn": "arn:aws:sqs:ap-northeast-1:000000000000:create-from-cfn.fifo",
        "ReceiveMessageWaitTimeSeconds": "0",
        "VisibilityTimeout": "900"
    }
}
```

----

**When generated from the CLI**
```
awslocal sqs get-queue-attributes --queue-url "http://localhost:4566/000000000000/create-from-cli.fifo" --attribute-names All
{
    "Attributes": {
        "ApproximateNumberOfMessages": "0",
        "ApproximateNumberOfMessagesDelayed": "0",
        "ApproximateNumberOfMessagesNotVisible": "0",
        "CreatedTimestamp": "1643639120.250814",
        "DelaySeconds": "0",
        "LastModifiedTimestamp": "1643639120.250814",
        "MaximumMessageSize": "262144",
        "MessageRetentionPeriod": "345600",
        "QueueArn": "arn:aws:sqs:ap-northeast-1:000000000000:create-from-cli.fifo",
        "ReceiveMessageWaitTimeSeconds": "0",
        "VisibilityTimeout": "30",
        "ContentBasedDeduplication": "true",
        "DeduplicationScope": "queue",
        "FifoQueue": "true",
        "FifoThroughputLimit": "perQueue"
    }
}
```

## example: temporary workaround

Run the API to set attributes such as ContentBasedDeduplication=true, FifoQueue=true from the CLI.

```
awslocal sqs set-queue-attributes --queue-url "http://localhost:4566/000000000000/create-from-cfn.fifo" --attributes "ContentBasedDeduplication=true,FifoQueue=true"
```

**Comment by sergey-telpuk** [comment]
> @sergey-telpuk @dfangl 
> In my environment, it works as expected when generated from the CLI.
> However, when I generate a SQS queue from Cloudformation(in localstack), `FifoQueue` and `ContentBasedDeduplication` are not set correctly, and it seems to be generated as a standard queue.
> 
> There seems to be a problem with patterns that are generated without APIs such as CLI.
> 
> I'm not familiar with the localstack code, so I'll wait until someone fixes it...
> 
> **template.yml**
> ```yml
> AWSTemplateFormatVersion: 2010-09-09
> Description: testing
> 
> Resources:
>   TestQueue:
>     Type: AWS::SQS::Queue
>     Properties:
>       ContentBasedDeduplication: true
>       DelaySeconds: 0
>       FifoQueue: true
>       KmsDataKeyReusePeriodSeconds: 86400
>       KmsMasterKeyId: alias/aws/sqs
>       MaximumMessageSize: 262144
>       MessageRetentionPeriod: 345600
>       QueueName: 'create-from-cfn.fifo'
>       ReceiveMessageWaitTimeSeconds: 0
>       VisibilityTimeout: 900
>     UpdateReplacePolicy: Delete
>     DeletionPolicy: Delete
> ```
> 
> **deploy command**
> ```
> awslocal cloudformation deploy --template-file template.yml --stack-name TestStack --capabilities CAPABILITY_IAM
> 
> or 
> 
> awslocal cloudformation create-stack --template-body file://template.yml --stack-name  TestStack --capabilities CAPABILITY_IAM
> 
> ```
> 
> **check attributes**
> 
> ```
> awslocal sqs get-queue-attributes --queue-url "http://localhost:4566/000000000000/create-from-cfn.fifo" --attribute-names All
> {
>     "Attributes": {
>         "ApproximateNumberOfMessages": "0",
>         "ApproximateNumberOfMessagesDelayed": "0",
>         "ApproximateNumberOfMessagesNotVisible": "0",
>         "CreatedTimestamp": "1643637734.9506",
>         "DelaySeconds": "0",
>         "LastModifiedTimestamp": "1643637734.9506",
>         "MaximumMessageSize": "262144",
>         "MessageRetentionPeriod": "345600",
>         "QueueArn": "arn:aws:sqs:ap-northeast-1:000000000000:create-from-cfn.fifo",
>         "ReceiveMessageWaitTimeSeconds": "0",
>         "VisibilityTimeout": "900"
>     }
> }
> ```
> 
> ----
> 
> **When generated from the CLI**
> ```
> awslocal sqs get-queue-attributes --queue-url "http://localhost:4566/000000000000/create-from-cli.fifo" --attribute-names All
> {
>     "Attributes": {
>         "ApproximateNumberOfMessages": "0",
>         "ApproximateNumberOfMessagesDelayed": "0",
>         "ApproximateNumberOfMessagesNotVisible": "0",
>         "CreatedTimestamp": "1643639120.250814",
>         "DelaySeconds": "0",
>         "LastModifiedTimestamp": "1643639120.250814",
>         "MaximumMessageSize": "262144",
>         "MessageRetentionPeriod": "345600",
>         "QueueArn": "arn:aws:sqs:ap-northeast-1:000000000000:create-from-cli.fifo",
>         "ReceiveMessageWaitTimeSeconds": "0",
>         "VisibilityTimeout": "30",
>         "ContentBasedDeduplication": "true",
>         "DeduplicationScope": "queue",
>         "FifoQueue": "true",
>         "FifoThroughputLimit": "perQueue"
>     }
> }
> ```
> 
> ## example: temporary workaround
> 
> Run the API to set attributes such as ContentBasedDeduplication=true, FifoQueue=true from the CLI.
> 
> ```
> awslocal sqs set-queue-attributes --queue-url "http://localhost:4566/000000000000/create-from-cfn.fifo" --attributes "ContentBasedDeduplication=true,FifoQueue=true"
> ```

Hi, thanks for checking, yes I approve this works as expected

**Comment by haroutbezdjian** [comment]
Hello, i still get the same error as the initial issue in version 0.14.0, aws sns publish in localstack resulting 

`Value __dummy__group_id__ for parameter MessageGroupId is invalid. Reason: The request include parameter that is not valid for this queue type.`

**Comment by ackdav** [comment]
Hello @intptr-t, thank you for raising this issue! Following the original snippets, I'm unable to reproduce the issue (using the latest version):
```
(.venv) ➜  localstack git:(master) awslocal sqs create-queue --queue-name "test.fifo" --attributes "ContentBasedDeduplication=true,FifoQueue=true"
{
    "QueueUrl": "http://localhost:4566/000000000000/test.fifo"
}
(.venv) ➜  localstack git:(master) awslocal sqs send-message --queue-url "http://localhost:4566/000000000000/test.fifo" --message-body "__dummy__" --message-group-id "__dummy__group_id__" --message-deduplication-id "__dummy__id__"
{
    "MD5OfMessageBody": "6240564be04a846edf0d616f3be37f1f",
    "MessageId": "2a07b356-688e-414b-9271-33f4222509eb",
    "SequenceNumber": "14348802621387571200"
}
```

Could you double-check on your end whether this issue still persists using the latest version?
Thanks!

**Comment by intptr-t** [comment]
@ackdav 
Thanks for letting us know!!
I have checked with the follow version and can confirm that it works fine.

```
LocalStack version: 1.3.1.dev
LocalStack build date: 2022-12-13
LocalStack build git hash: c4fe1280
```
