### ISSUE TITLE
question: Missing github tag/release for 0.13.3?

### ISSUE THREAD

**Issue by lorengordon** [localstack/localstack#5239]
### Is there an existing issue for this?

- [X] I have searched the existing issues and read the documentation

### Question

Curious about the release process... I see a docker tag for 0.13.3, as well as an entry in changelog.md, but no github tag. What causes the delta?

**Comment by whummer** [comment]
Thanks for the reminder @lorengordon . The release tag (plus changelog, plus pypi package) has been pushed a few days ago, release notes on Github still missing - we'll add them right away.. Thanks!

**Comment by lorengordon** [comment]
Thanks @whummer! I subscribe to github for release notifications, but have some automation tied to the dockerhub tags using dependabot. So it surprised me to see a PR for 0.13.3 when I didn't recall seeing an email from github about the release!

**Comment by whummer** [comment]
I see, thanks for clarifying. Makes perfect sense - usually we try to do all the release steps in tandem, we'll take better care of this next time.. Thanks!
