### ISSUE TITLE
bug: Unable to reach Api Gateway endpoint created by samlocal

### ISSUE THREAD

**Issue by Dranaxel** [localstack/localstack#5252]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm trying to deploy hello-world application on localstack on my computer but when i try to curl the api gateway point I could not resolve the address.

### Expected Behavior

curl should return  {"statusCode":200,"body":"{\"message\": \"hello world\"}"}

### How are you starting LocalStack?

With the `localstack` script

### Steps To Reproduce

Run localstack with `localstack start`
Follow the stop of this [tutorial](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-getting-started-hello-world.html)
After deploying, curl to the address displayed

### Environment

```markdown
- OS: Debian 10.10 on WSL
- LocalStack: 0.13.3

I'm using it throught pipenv.
```

### Anything else?

I noticed an error on the localstack logs, doesn't seem relevant to me but who knows
![image](https://user-images.githubusercontent.com/17832323/148951721-27221f2c-ee3e-4a77-b0bd-bb60d8766430.png)

**Comment by calvernaz** [comment]
I @Dranaxel thanks for reporting this! Do you mind to show your SAM code and which endpoint are you trying to hit?

The endpoint should be the one documented [here](https://docs.localstack.cloud/aws/apigatewayv2/)

**Comment by Dranaxel** [comment]
Hi @calvernaz,
I did read the documentation and it's more clear now...
Thanks for the help and sorry for the time loss.
