### ISSUE TITLE
bug: event.version is missing, causing issues in apollo-server-lambda

### ISSUE THREAD

**Issue by micheleangioni** [localstack/localstack#5259]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When deploying lambdas to LocalStack via API Gateway v1 or v2, [the official AWS event payload](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html) is not respected.

In the specific, the version key

![image](https://user-images.githubusercontent.com/7933034/149171036-e60fdebb-52bd-4750-9f57-3f9be41ca50d.png)

![image](https://user-images.githubusercontent.com/7933034/149171073-8c03b673-59b1-4ac6-92c1-76d3cc258180.png)

is not present, i.e. `event.version` is undefined.

Packages like [apollo-server-lambda](https://github.com/apollographql/apollo-server/tree/main/packages/apollo-server-lambda) use it to infer the correct event payload. Without it, it falls back to Gateway v1, making the application crash when deploying to LocalStack a lambda using Gateway v2 with that package.

As a reference, @vendia/serverless-express uses it [here](https://github.com/vendia/serverless-express/blob/mainline/src/event-sources/utils.js#L85).

### Expected Behavior

I expect the `version` key to be always present.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

Just use the Serverless Framework to deploy a Lambda via Gateway, either v1 or v2. You can use [sls-node-ts](https://github.com/micheleangioni/sls-node-ts) or any other project.

Then inspect the event object received by the lambda. You'll notice the `version` key is missing.

### Environment

```markdown
- OS: MacOS Big Sour 11.6
- LocalStack: 0.13.3
```

### Anything else?

If you need more evidence, please let me know.

Thanks :)

**Comment by micheleangioni** [comment]
More investigation resulted into discovering that the whole event format is wrong, [please see this](https://github.com/localstack/localstack/issues/5259)

**Comment by calvernaz** [comment]
Hi @micheleangioni, thanks for reporting this! I'll close this issue, because as you mentioned the full event is not being properly sent and you already created a issue for that https://github.com/localstack/localstack/issues/5281
