### ISSUE TITLE
bug: SecretsManager never returns timestamps

### ISSUE THREAD

**Issue by haggholm** [localstack/localstack#5273]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I create secrets and look them up, e.g. via `awslocal secretsmanager list-secrets` or a JS API, all timestamp fields are `undefined`: `CreatedDate`, `LastChangedDate`, etc.

### Expected Behavior

I expect the secrets to be listed with the proper creation and update dates included.

### How are you starting LocalStack?

With a `docker run` command

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run --rm -p 4566:4566 --name=localstack localstack/localstack:latest

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal secretsmanager create-secret --name foo --secret-string '{"foo": "bar"}'
    awslocal secretsmanager list-secrets

### Environment

```markdown
- OS: Ubuntu 20.04
- LocalStack: 0.13, latest
```

**Comment by dfangl** [comment]
Will be fixed by https://github.com/spulec/moto/pull/4770

**Comment by dfangl** [comment]
This should be fixed in :latest! Thanks for reporting this!

**Comment by haggholm** [comment]
LGTM; thank you.
