### ISSUE TITLE
bug: Global tables do not work (version 2019.11.21)

### ISSUE THREAD

**Issue by ChristianWolf1** [localstack/localstack#5275]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I try to create global tables in localstack by following the [tutorial from AWS ](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/V2globaltables.tutorial.html#V2creategt_cli).
The table description for the created table in region us-east-2 looks correct, if I issue "awslocal dynamodb describe-table --table-name Music --region us-east-2

No "Music" table is created in region us-east-1 though.

Am I doing something wrong, or is this not supported right now? 
I was also wondering whether the replication delay between tables is configurable, so that it is similar to that of AWS, which is in the range of several seconds.

### Expected Behavior

A created table "Music" in region us-east-1.

### How are you starting LocalStack?

With a `docker run` command

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

awslocal dynamodb create-table \\
    --table-name Music \\
    --attribute-definitions \\
        AttributeName=Artist,AttributeType=S \\
        AttributeName=SongTitle,AttributeType=S \\
    --key-schema \\
        AttributeName=Artist,KeyType=HASH \\
        AttributeName=SongTitle,KeyType=RANGE \\
    --billing-mode PAY_PER_REQUEST \\
    --stream-specification StreamEnabled=true,StreamViewType=NEW_AND_OLD_IMAGES \\
    --region us-east-2

awslocal dynamodb update-table --table-name Music --replica-updates "{\\"Create\\": {\\"RegionName\\":\\"us-east-1\\"}}" --region us-east-2 

### Environment

```markdown
- OS: Ubuntu 20.10
- LocalStack: 0.13.3
```

**Comment by giograno** [comment]
Hi @ChristianWolf1, thanks for the feature request! We rolled out initial support for global tables version 2019.11.21 (see https://github.com/localstack/localstack/pull/6744). While this is not yet a fully-fledged implementation, you should be able to replicate the AWS tutorial at the very least.
