### ISSUE TITLE
bug: sqs asf provider queue attributes not working

### ISSUE THREAD

**Issue by kandrejevs2** [localstack/localstack#5276]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://user-images.githubusercontent.com/57944366/149506803-6811be67-c7f2-4567-bcbf-3073e6a4709f.png)

ApproximateNumberOfMessages returns stack trace instead of number of messages in queue
https://docs.aws.amazon.com/aws-sdk-php/v3/api/api-sqs-2012-11-05.html#getqueueattributes

### Expected Behavior

Number of messages in queue should be returned

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker-compose.yml

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    aws sdk https://docs.aws.amazon.com/aws-sdk-php/v3/api/api-sqs-2012-11-05.html#getqueueattributes

### Environment

```markdown
- OS: ubuntu 20.04 with docker
- LocalStack: latest
```

**Comment by baermat** [comment]
Hi @kandrejevs2 , thanks for reporting this.
This should be fixed in the latest docker image, please pull it and report if the issue persists, thanks!
