### ISSUE TITLE
bug: Object of type TimestreamDB is not JSON serializable

### ISSUE THREAD

**Issue by eriksvedin2** [localstack/localstack#5277]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm working on getting a timestreamdb set up with localstack. I've been able to start localstack and create a database successfully using:
aws --endpoint-url=http://localhost:4566 timestream-write create-database --database-name my-database
However, when I later try to query the database it says that the database does not exist.
And when using the boto3 list_databases method I receive an error 500:

```
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
```

From the localstack logs I see:
```TypeError: Object of type TimestreamDB is not JSON serializable```

### Expected Behavior

I expect my created database to show up.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    Using this docker-compose file:
    
    `version: '3'
  
      services:
        rabbit:
          image: rabbitmq:3.8-management
          ports:
            - "15672:15672"
            - "5672:5672"
          restart: always
        localstack:
          image: localstack/localstack:0.12.20
          ports:
            - "127.0.0.1:53:53"
            - "127.0.0.1:53:53/udp"
            - "127.0.0.1:443:443"
            - "127.0.0.1:4510-4530:4510-4530"
            - "127.0.0.1:4566:4566"
            - "127.0.0.1:4571:4571"
          environment:
            - LOCALSTACK_API_KEY=MY_API_KEY
            - HOST_TMP_FOLDER=/tmp/localstack
            - DOCKER_HOST=unix:///var/run/docker.sock
          volumes:
            - "${TMPDIR:-/tmp}/localstack:/tmp/localstack"
            - "/var/run/docker.sock:/var/run/docker.sock"
  `

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    aws --endpoint-url=http://localhost:4566 timestream-write create-database --database-name my-database
    
    Then from python:
    
    `
    import boto3
    from botocore.config import Config
    Config(
            region_name='us-east-1',
            signature_version='v4',
        )
    write_client = boto3.client('timestream-write', config=boto3_config, endpoint_url='http://localhost:4566')
    write_client.list_databases()
    `

### Environment

```markdown
- OS: OSX 10.14.6
- LocalStack: Tried with 0.12.20, 0.13.3
```

**Comment by whummer** [comment]
Thanks for reporting @eriksvedin2 . This should be fixed in the meantime - can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists.. Thanks for your help!

**Comment by eriksvedin2** [comment]
This works thanks! I seem to be unable to query the database though. I'm always receiveing "relation does not exist" errors. I'll open a separate issue for this.
