### ISSUE TITLE
how many file capacity when update file to s3

### ISSUE THREAD

**Issue by ansonGitHub** [localstack/localstack#5284]
### Is there an existing issue for this?

- [X] I have searched the existing issues and read the documentation

### Question

When I upload a lots of file to S3. It works normally at the beginning. But After a while It show "An error occurred (NoSuchBucket) when calling the ListObjectsV2 operation: The specified bucket does not exist". It there any limited for S3 capacity?

BTW I use the Community Edition

**Comment by dfangl** [comment]
Hi! The file capacity is not arbitrarily limited, but is limited by your system, i.E. how much Disk space the container can use etc. 
Could you maybe give more insight to your problem, in essence how are you uploading your files, what file sizes we are talking about here and so on.
Just tested using awscli, without problems with 2GB+ of 500Mb files.

**Comment by dfangl** [comment]
I am closing this for now, if you have any specific issues, please reopen with information about the type of data you push into S3, your host operating system, and how you are starting localstack (i.e. your docker-compose file or command you are starting it with).
