### ISSUE TITLE
bug: relation db.table does not exist when using timestream-query

### ISSUE THREAD

**Issue by eriksvedin2** [localstack/localstack#5285]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When making a simple query to a newly created table/database in timestream using the boto3 client, I receive error 500.

"InternalServiceError: relation \\"my-database.readings\\" does not exist\"

### Expected Behavior

I expect to receieve an empty response since I know there is a database and table, but no data yet.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    version: '3'

    services:
      rabbit:
        image: rabbitmq:3.8-management
        ports:
          - "15672:15672"
          - "5672:5672"
        restart: always
      localstack:
        image: localstack/localstack:latest
        ports:
          - "127.0.0.1:53:53"
          - "127.0.0.1:53:53/udp"
          - "127.0.0.1:443:443"
          - "127.0.0.1:4510-4530:4510-4530"
          - "127.0.0.1:4566:4566"
          - "127.0.0.1:4571:4571"
        environment:
          - LOCALSTACK_API_KEY="..."
          - HOST_TMP_FOLDER=/tmp/localstack
          - DOCKER_HOST=unix:///var/run/docker.sock
        volumes:
          - "${TMPDIR:-/tmp}/localstack:/tmp/localstack"
          - "/var/run/docker.sock:/var/run/docker.sock"

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

Creating the database using aws cli:

    aws --endpoint-url=http://localhost:4566 timestream-write create-database --database-name my-database

In a python app I'm creating a table and run the query:
   
    ...
    database_name = 'my-database'
    table_name = 'readings'
    
    boto3_config = Config(
            region_name='us-east-1',
            signature_version='v4',
        )
    query_client = boto3.client('timestream-query', config=boto3_config, endpoint_url='http://localhost:4566')
    write_client = boto3.client('timestream-write', config=boto3_config, endpoint_url='http://localhost:4566')
    
    ## Create table, which prints out a success response
    retention_properties = {
        'MemoryStoreRetentionPeriodInHours': 25,
        'MagneticStoreRetentionPeriodInDays': 367,
    }
    magnetic_store_write_properties = {
        'EnableMagneticStoreWrites': True
    }

    returned = write_client.create_table(
        DatabaseName=database_name,
        TableName=table_name,
        RetentionProperties=retention_properties,
        MagneticStoreWriteProperties=magnetic_store_write_properties,
    )
    log.info(f'returned: {returned}')
        
So far so good, the log prints:

    {'Table': {'Arn': 'arn:aws:timestream:us-east-1:000000000000:database/my-database/table/readings', 'TableName': 'readings', 'DatabaseName': 'my-database', 'TableStatus': 'ACTIVE', 'RetentionProperties': {'MemoryStoreRetentionPeriodInHours': 25, 'MagneticStoreRetentionPeriodInDays': 367}, 'CreationTime': datetime.datetime(2022, 1, 17, 8, 37, 34, tzinfo=tzlocal()), 'LastUpdatedTime': datetime.datetime(2022, 1, 17, 8, 37, 34, tzinfo=tzlocal()), 'MagneticStoreWriteProperties': {'EnableMagneticStoreWrites': True}}, 'ResponseMetadata': {'HTTPStatusCode': 200, 'HTTPHeaders': {'content-type': 'application/json', 'content-length': '398', 'access-control-allow-origin': '*', 'access-control-allow-methods': 'HEAD,GET,PUT,POST,DELETE,OPTIONS,PATCH', 'access-control-allow-headers': 'authorization,cache-control,content-length,content-md5,content-type,etag,location,x-amz-acl,x-amz-content-sha256,x-amz-date,x-amz-request-id,x-amz-security-token,x-amz-tagging,x-amz-target,x-amz-user-agent,x-amz-version-id,x-amzn-requestid,x-localstack-target,amz-sdk-invocation-id,amz-sdk-request', 'access-control-expose-headers': 'etag,x-amz-version-id', 'connection': 'close', 'date': 'Mon, 17 Jan 2022 07:37:34 GMT', 'server': 'hypercorn-h11'}, 'RetryAttempts': 0}}
    
    
But I then I try to run a query against it:

    query = f'SELECT * FROM "{database_name}".{table_name} ORDER BY time DESC LIMIT 10'
    return query_client.query(QueryString=query)
    
And receive the error:
    {"Type": "Server", "message": "InternalServiceError: relation \\"my-database.readings\\" does not exist\\nLINE 1: SELECT * FROM \\"my-database\\".readings ORDER BY time DESC LIMI...\\n                      ^\\n", "__type": "InternalServiceError"}

### Environment

```markdown
- OS: osx 10.14.6
- LocalStack: latest (17/1/2021 08:50)
```

### Anything else?

I started by usin the paginator query, which I would like to use in my real application, but that failed in the same fashion as described above. So I fell back to the normal query hoping that it might work but no.

**Comment by whummer** [comment]
Thanks for reporting @eriksvedin2 . Looks like the issue here is the dash (`-`) in the database name. As a quick fix, you could try renaming your database, e.g., as follows:
```
database_name = 'mydb1'
```
We'll work on a fix with high priority - thanks for your help!

**Comment by eriksvedin2** [comment]
@whummer The workaround solves the problem for now, thanks for the quick reply once again!

**Comment by whummer** [comment]
Hi again @eriksvedin2 , thanks for confirming. The fix should be rolled out in the meantime - when you get a chance, can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists.. Thanks!
