### ISSUE TITLE
bug: localstack pro - can delete aws organization even if org has member accounts present 

### ISSUE THREAD

**Issue by ashmantak** [localstack/localstack#5288]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I can delete organization even if the organization has member accounts present. 

### Expected Behavior

As per the official document - https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/organizations.html#Organizations.Client.delete_organization 

We should not be able to delete organization if there are member accounts present in it. 

We should get exception : 
`An error occurred (OrganizationNotEmptyException) when calling the DeleteOrganization operation: To delete an organization you must first remove all member accounts (except the master).`

### How are you starting LocalStack?

With a `docker run` command

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

`docker run --rm -it -p 4566:4566 -p 4571:4571 -p 443:443 -e LOCALSTACK_API_KEY=<API_KEY> -e DEBUG=1 localstack/localstack:latest`

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

   Step 1 : 
   Create an organization .
` awslocal organization create-organization`

Step2 :
Add a member account to the organization 
`awslocal organizations create-account --email susan@example.com --account-name "Test Account" `

Step3:
Verify member account is present in the organization alongside master account
`awslocal organizations list-accounts`

Step4: 
Delete the organization 
`awslocal organizations delete-organization`

Result : Organization is deleted. 

### Environment

```markdown
- OS: 
- LocalStack:
```

**Comment by dfangl** [comment]
Fixed in https://github.com/spulec/moto/pull/4773

**Comment by dfangl** [comment]
This should be fixed in :latest. Thanks for reporting this!
