### ISSUE TITLE
Make dependency lazy-loading optional

### ISSUE THREAD

**Issue by jcmcken** [localstack/localstack#529]
Issue #1 made it so that many dependencies are lazily fetched and installed. This should be made optional, so that localstack can be distro-tized (e.g. made into an RPM, DEB, etc.). This behavior also makes it more difficult to install localstack when running on a corporate LAN that has limited or no direct access to the Internet.

**Comment by whummer** [comment]
Closing this as obsolete - installation process has evolved and been adapted to new requirements in the meantime.
