### ISSUE TITLE
feature request: support for reporting partial batch failure for a SQS batch

### ISSUE THREAD

**Issue by onoumenon** [localstack/localstack#5301]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

AWS lambda has [support for reporting partial batch failure for a SQS batch](https://docs.aws.amazon.com/lambda/latest/dg/with-sqs.html#services-sqs-batchfailurereporting). We're currently using it for our lambda functions on our [serverless.yml](https://www.serverless.com/blog/improved-sqs-batch-error-handling-with-aws-lambda), and would like to test the configuration locally. It'd be great to have it supported on LocalStack.

### Anything else?

![Screenshot 2022-01-19 at 6 00 31 PM](https://user-images.githubusercontent.com/39733588/150461615-949ec0b5-564b-4c0c-8a51-0047a7f0faef.png)

```
            "FunctionResponseTypes": [
                "ReportBatchItemFailures"
            ]
```
is missing from localstack's event source mapping despite setting it

**Comment by chucky2305** [comment]
We would also :heart: to see this feature coming to localstack

**Comment by diegodalben** [comment]
Hi! 

I've this same need.

**Comment by maora-gi** [comment]
Hi,

I have the same issue!

Should be a solution anytime soon?

**Comment by thrau** [comment]
Hey everyone, sorry for the long delay on this. I'm cooking up a PR in #6606 and hope to have it merged by end of next week!
