### ISSUE TITLE
bug: SQS message delivered in the wrong format in case of SNS subscription

### ISSUE THREAD

**Issue by rohanjaswal2507** [localstack/localstack#5303]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

While publishing a message to a SNS topic that has an SQS subscription attached to it, localstack attaches certain extra attributes to the body of the message that is to be delivered to SQS queue.
For example, if the message published to SNS topic is
`'{"hello": "world"}'`

then, the message delivered to the SQS is:
`
{"Type": "Notification", "MessageId": "some_message_id", "message": "{\"hello:\": \"world\"}", "TopicArn": "topic_arn" }
`

This is happening when `RawMessageDelivery` is set to True.

### Expected Behavior

As I see in our production application which has a similar setup (SQS subscription on SNS topic), the message delivered the SQS consumer is:
`'{"hello": "world"}`

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    aws --endpoint-url=http://localhost:4566 sqs create-queue --queue-name test-queue
    aws --endpoint-url=http://localhost:4566 sns create-topic --name test-topic
    aws --endpoint-url=http://localhost:4566 sns subscribe --topic-arn arn:aws:sns:us-east-1:000000000000:test-topic --protocol sqs --notification-endpoint http://localhost:4566/000000000000/test-queue
    
    aws --endpoint-url=http://localhost:4566 sns publish  --topic-arn arn:aws:sns:us-east-1:000000000000:test-topic --message '{"hello": "world"}'

### Environment

```markdown
- OS: MacOS monterey 12.1
- LocalStack: latest
```

**Comment by MarcelStranak** [comment]
Hello @rohanjaswal2507 ,

I have had a look at the reported issue. I was not able to reproduce it with the provided information.
If I understand it correctly in AWS you have created a SNS Subscription with **RawMessageDelivery** set to **True**.

Are you using the same setting in LocalStack environment?
In the commands you have provided, I can see that it's missing the attribute tag **RawMessageDelivery**.

For my test, I have used commands you have provided, but created 2 queues with 2 different subscriptions.

```bash
aws --endpoint-url=http://localhost:4566 sqs create-queue --queue-name test-queue
aws --endpoint-url=http://localhost:4566 sqs create-queue --queue-name test-queue2
```

```JSON
{
    "QueueUrls": [
        "http://localhost:4566/000000000000/test-queue",
        "http://localhost:4566/000000000000/test-queue2"
    ]
}
```

First subscription(attribute set during the creation, RawMessageDelivery is set to true):
```bash
aws --endpoint-url=http://localhost:4566 sns subscribe  --topic-arn arn:aws:sns:us-east-1:000000000000:test-topic --protocol sqs  --attributes=RawMessageDelivery=true --notification-endpoint http://localhost:4566/000000000000/test-queue
```

```JSON
{
    "Attributes": {
        "TopicArn": "arn:aws:sns:us-east-1:000000000000:test-topic",
        "Endpoint": "http://localhost:4566/000000000000/test-queue",
        "Protocol": "sqs",
        "SubscriptionArn": "arn:aws:sns:us-east-1:000000000000:test-topic:bc8d56a6-5195-40d5-864b-34cc280413d8",
        "RawMessageDelivery": "true",
        "PendingConfirmation": "false"
    }
}
```

Second subscription(default, RawMessageDelivery is not set to true):
```bash
aws --endpoint-url=http://localhost:4566 sns subscribe  --topic-arn arn:aws:sns:us-east-1:000000000000:test-topic --protocol sqs  --notification-endpoint http://localhost:4566/000000000000/test-queue2
```

```JSON
{
    "Attributes": {
        "TopicArn": "arn:aws:sns:us-east-1:000000000000:test-topic",
        "Endpoint": "http://localhost:4566/000000000000/test-queue2",
        "Protocol": "sqs",
        "SubscriptionArn": "arn:aws:sns:us-east-1:000000000000:test-topic:e8f9dec1-1b37-4b58-9bc7-8c6406c3c1f5",
        "PendingConfirmation": "false"
    }
}
```


You can list the subscriptions using _list-subscriptions_ and check the attributes by using _get-subscription-attributes_.
```bash
aws --endpoint-url=http://localhost:4566 sns list-subscriptions
aws --endpoint-url=http://localhost:4566 sns get-subscription-attributes  --subscription-arn  #ARN recevied from the previous command
```

When I published the message, I received the message on 2 queues with different body messages.
```bash
aws --endpoint-url=http://localhost:4566 sns publish --topic-arn "arn:aws:sns:us-east-1:000000000000:test-topic" --message '{"hello": "world"}'

aws --endpoint-url=http://localhost:4566 sqs receive-message --queue-url "http://localhost:4566/000000000000/test-queue"
aws --endpoint-url=http://localhost:4566 sqs receive-message --queue-url "http://localhost:4566/000000000000/test-queue2"
```
```json
{
    "Messages": [
        {
            "MessageId": "8bd5e535-d53a-3b98-0005-8c88219c4512",
            "ReceiptHandle": "example",
            "MD5OfBody": "49dfdd54b01cbcd2d2ab5e9e5ee6b9b9",
            "Body": "{\"hello\": \"world\"}"
        }
    ]
}
```
```json
{
    "Messages": [
        {
            "MessageId": "d43bc7b8-a7cb-f90a-e298-18b560469607",
            "ReceiptHandle": "example",
            "MD5OfBody": "1085558dd3edfa64d95da62b8f46be38",
            "Body": {
                "Type": "Notification",
                "MessageId": "12b74452-44a5-4c57-a106-e1d33cc28951",
                "TopicArn": "arn:aws:sns:us-east-1:000000000000:test-topic",
                "Message": "{\"hello\": \"world\"}",
                "Timestamp": "2022-01-20T09:40:15.632Z",
                "SignatureVersion": "1",
                "Signature": "",
                "SigningCertURL": ""
            }
        }
    ]
}
```

Used LocalStack version: 0.13.3

Please try and test it with the set parameter **--attributes=RawMessageDelivery=true**. Let me know if this helped or if the issue still persist.
