### ISSUE TITLE
question: Podman compatibility for MacOS

### ISSUE THREAD

**Issue by yolanv** [localstack/localstack#5304]
### Is there an existing issue for this?

- [X] I have searched the existing issues and read the documentation

### Question

The Docker Desktop license forced me to change to Podman on my MacOS device. I looked through the Localstack documentation to use Podman instead of Docker but could only find the **podman-docker** library, which is only available for Linux. 
As of right now, I can't find a way to use LocalStack on my MacOS device without installing Docker Desktop (which is not possible anymore).

If anyone was able to get it working with Podman, I'd love to hear how you did that.

### Anything else?

https://docs.localstack.cloud/localstack/podman/

**Comment by dfangl** [comment]
Hi!
Did you already try the instructions in section "Rootfull Podman without podman-docker "
: https://docs.localstack.cloud/localstack/podman/#rootfull-podman-without-podman-docker

If so, did it work?

**Comment by yolanv** [comment]
Hello, 
Thanks for your answer. I figured this documentation was for Linux operating systems only. 
Does this documentation include MacOS aswell? It doesn't seem like it, but I could be wrong.

Thank you!

**Comment by dfangl** [comment]
Hi!
Podman on MacOS is currently not very well supported, but definitively something we work on in the future.
For now, a main problem is bind mounts not being supported, and the podman socket not exposed to your host.
You can start localstack manually in podman `podman run --rm --name localstack_main -p 127.0.0.1:4566:4566 -p 127.0.0.1:4571:4571 -e DEFAULT_REGION=us-east-1 -e DEBUG=1 -e LEGACY_DOCKER_CLIENT=1 -e TEST_AWS_ACCOUNT_ID=000000000000 -e DOCKER_HOST=unix:///run/podman/podman.sock -e HOST_TMP_FOLDER=/tmp/localstack -e SET_TERM_HANDLER=1 --privileged localstack/localstack `, the problem will be persistence (due to the missing bind mounts, you could use volumes though) and everything starting additional containers will not work (so no Lambda, ECS etc).

We are trying to support the case better, but it should be possible to get it to run at least.

**Comment by yolanv** [comment]
Thank you!

**Comment by yolanv** [comment]
@dfangl 
Hello, 

We put the localstack issue on hold for a bit, but now wanting to run it again, I ran your command but it fails to start up with the message: 
```
FileNotFoundError: [Errno 2] No such file or directory: 'docker'
2022-03-09 13:16:45,969 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Waiting for all LocalStack services to be ready
```

I have a docker alias which refers to podman, but its probably looking for the binary itself. Do you have an idea on how we can get around this? Thank you!

**Comment by anvena** [comment]
Any update about how to start localstack inside podman for mac users ?

**Comment by MarcelStranak** [comment]
Hi, 
can you please try running it with this modified command?
```
podman run --rm --name localstack_main -p 4566:4566 -p 4571:4571 -e DEFAULT_REGION=us-east-1 -e DEBUG=1  -e TEST_AWS_ACCOUNT_ID=000000000000 -e DOCKER_HOST=unix:///run/podman/podman.sock --privileged localstack/localstack
```

**Comment by dsdshcym** [comment]
@MarcelStranak Thanks for this command!
It works for me without any issues so far 👍

**Comment by gpazo** [comment]
> Hi! Podman on MacOS is currently not very well supported, but definitively something we work on in the future. For now, a main problem is bind mounts not being supported, and the podman socket not exposed to your host. You can start localstack manually in podman `podman run --rm --name localstack_main -p 127.0.0.1:4566:4566 -p 127.0.0.1:4571:4571 -e DEFAULT_REGION=us-east-1 -e DEBUG=1 -e LEGACY_DOCKER_CLIENT=1 -e TEST_AWS_ACCOUNT_ID=000000000000 -e DOCKER_HOST=unix:///run/podman/podman.sock -e HOST_TMP_FOLDER=/tmp/localstack -e SET_TERM_HANDLER=1 --privileged localstack/localstack `, the problem will be persistence (due to the missing bind mounts, you could use volumes though) and everything starting additional containers will not work (so no Lambda, ECS etc).
> 
> We are trying to support the case better, but it should be possible to get it to run at least.

Is there any update on this? I was able to get `podman` going with this command above but confirmed **everything starting additional containers will not work (so no Lambda, ECS etc).** is still missing functionality.  Any workaround? 

From the quickstart guide: https://docs.localstack.cloud/getting-started/quickstart/

I am able to get all the way to "Run the sample AWS application" but it gets hung up when I upload a test image presenting this error: https://docs.localstack.cloud/user-guide/aws/lambda/#docker-not-available

**Comment by dfangl** [comment]
Hi @gpazo ! https://docs.localstack.cloud/references/podman/#podman-on-windows can you try the docker compose file linked here?

I tested it on MacOS as well, even though it says Windows, it should work.

**Comment by elireyes2017** [comment]
@gpazo It's been over a year since you posted your help on this issue. I literally cannot thank you enough! I got my LocalStack/MacOS Silicon/Podman setup to deploy LocalStack and additional AWS services like S3 and Lambda. Thank you!!!!!
