### ISSUE TITLE
bug: JWT token "username" field emitted by Cognito token endpoint contains the email

### ISSUE THREAD

**Issue by davidlj95** [localstack/localstack#5307]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When LocalStack emits a JWT token as response to the [`POST /oauth2/token` endpoint](https://docs.aws.amazon.com/cognito/latest/developerguide/token-endpoint.html) as part of the OAuth2 authorization code grant protocol, there's a mismatch compared to AWS Cognito behaviour in the `username` field of the JWT issued token.

The JWT issued token **contains the email** of the user. However, username would be expected. 

Extra information: when accessing the login page provided by LocalStack at `/login`, used the email instead of the username. 

### Expected Behavior

Either if you use email or username in the `/login` page when using Cognito IdP as part of the OAuth2 auth flow, the emitted JWT token issued by LocalStack later contains the `username` in the JWT `username` field, not the email (so it's the expected behaviour in sync w/ AWS Cognito IdP behaviour).

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

Sample `docker-compose.yml` from the repository with:
- `cognito-idp` as the only enabled service
- Some `SMTP_` settings 

However I think the configuration probably isn't the source of the issue.

To reproduce, enable `cognito-idp` service & create a pool with a client and domain.  Create a user with `AdminCreateUser` op as stated below in client commands. 

Then, start the OAuth2 flow by using the created pool & client configuration. 
**In the login page, use the email to sign in**. Then, the emitted JWT token after exchanging the code per token will return a JWT token with the username field populated with the email instead of the username.

##### 1. User pool creation
```
aws cognito-idp create-user-pool --pool-name "foo" --cli-input-json "$(cat "$PATH_USER_POOL_TEMPLATE_JSON")"
```

<summary>
📄 User pool JSON template
<details>
<pre>
{
    "PoolName": "OVERWRITTEN BY COMMAND",
    "Policies": {
        "PasswordPolicy": {
            "MinimumLength": 8,
            "RequireUppercase": true,
            "RequireLowercase": true,
            "RequireNumbers": true,
            "RequireSymbols": true,
            "TemporaryPasswordValidityDays": 7
        }
    },
    "LambdaConfig": {},
    "AutoVerifiedAttributes": [
        "email"
    ],
    "AliasAttributes": [
        "email"
    ],
    "SmsVerificationMessage": "Your verification code is {####}. ",
    "EmailVerificationMessage": "Your verification code is {####}. ",
    "EmailVerificationSubject": "Your verification code",
    "VerificationMessageTemplate": {
        "SmsMessage": "Your verification code is {####}. ",
        "EmailMessage": "Your verification code is {####}",
        "EmailSubject": "Your reset password code",
        "DefaultEmailOption": "CONFIRM_WITH_CODE"
    },
    "SmsAuthenticationMessage": "Your authentication code is {####}. ",
    "MfaConfiguration": "OFF",
    "EmailConfiguration": {
        "EmailSendingAccount": "COGNITO_DEFAULT"
    },
    "UserPoolTags": {},
    "AdminCreateUserConfig": {
        "AllowAdminCreateUserOnly": true,
        "InviteMessageTemplate": {
            "SMSMessage": "Your username is {username} and temporary password is {####}",
            "EmailMessage": "Your username is {username} and temporary password is {####}",
            "EmailSubject": "Welcome!"
        }
    },
    "Schema": [
        {
            "Name": "email",
            "AttributeDataType": "String",
            "DeveloperOnlyAttribute": false,
            "Mutable": true,
            "Required": true,
            "StringAttributeConstraints": {
                "MinLength": "0",
                "MaxLength": "2048"
            }
        }
    ],
    "UserPoolAddOns": {
        "AdvancedSecurityMode": "AUDIT"
    },
    "UsernameConfiguration": {
        "CaseSensitive": false
    },
    "AccountRecoverySetting": {
        "RecoveryMechanisms": [
            {
                "Priority": 1,
                "Name": "verified_email"
            }
        ]
    }
}
</pre>
</details>
</summary>

##### 2. User pool client creation
```
aws cognito-idp create-user-pool-client --user-pool-id "$CREATED_USER_POOLID" \
  --callback-urls "https://localhost:9100/v1/auth/idpresponse" \
  --logout-urls "http://localhost:8100/" \
  --cli-input-json "$(cat "$PATH_USER_POOL_CLIENT_TEMPLATE_JSON")"
```

<summary>
📄 User pool client JSON template
<details>
<pre>
{
  "UserPoolId": "OVERWRITTEN BY COMMAND",
  "ClientName": "foo-service",
  "GenerateSecret": true,
  "RefreshTokenValidity": 30,
  "ExplicitAuthFlows": [
    "ALLOW_REFRESH_TOKEN_AUTH"
  ],
  "SupportedIdentityProviders": [
    "COGNITO"
  ],
  "CallbackURLs": [
    "OVERWRITTEN BY COMMAND"
  ],
  "LogoutURLs": [
    "OVERWRITTEN BY COMMAND"
  ],
  "AllowedOAuthFlows": [
    "code"
  ],
  "AllowedOAuthScopes": [
    "openid"
  ],
  "AllowedOAuthFlowsUserPoolClient": true,
  "PreventUserExistenceErrors": "ENABLED"
}
</pre>
</details>
</summary>

##### 3. User pool domain creation
```
aws cognito-idp create-user-pool-domain --domain "foodomain" --user-pool-id "$CREATED_USER_POOLID"
```

##### 4. User creation
```
aws cognito-idp admin-create-user \
  --user-pool-id "$CREATED_USER_POOL_ID" \
  --username "$(uuidgen | lowercase)" \
  --user-attributes 'Name=email,Value=example@example.com' 'Name=email_verified,Value=true' \
  --desired-delivery-mediums EMAIL --no-force-alias-creation
```

### Environment

```markdown
- OS: macOS Monterrey 12.0.1 (21A559)
- LocalStack: latest
```

**Comment by giograno** [comment]
Hi @davidlj95, thanks for opening the issue, and sorry for the long wait. To the best of my understanding, this should be fixed by now. Please give it a try with the latest version of LocalStack and feel free to open a new issue if you experience any other problems. Thank you!
