### ISSUE TITLE
bug: state query parameter is not forwarded when redirecting back in the OAuth2 Cognito flows

### ISSUE THREAD

**Issue by davidlj95** [localstack/localstack#5308]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In LocalStack's [Cognito login page via OAuth2](https://docs.localstack.cloud/aws/cognito/#oauth-flows-via-cognito-login-form), the `state` parameter is not being forwarded.

[AWS docs state that the `/login` endpoint](https://docs.aws.amazon.com/cognito/latest/developerguide/login-endpoint.html#:~:text=Required.-,state,-An%20opaque%20value) can accept a `state` query param in the URL that will be returned to the client upon redirect when finishing the OAuth2 flow part in that page. It is also mentioned as recommended [in section 4.1.1 as part of the OAuth2 RFC chapter about authorization code grant type](https://datatracker.ietf.org/doc/html/rfc6749#section-4.1.1). 

So, if you construct the `/login` authorization URL with `code`, `client_id` and `redirect_uri` and `state`, you can access the login page with `state` query param in the URL. But then, the `state` **query param is not forwarded** when the login page redirects to the `redirect_uri` provided, despite it should.

It's a query param [**RECOMMENDED** in the OAuth2 RFC in section 4.1.1](https://datatracker.ietf.org/doc/html/rfc6749#section-4.1.1). Therefore also **"Optional, but strongly recommended"** in [AWS docs of the `/login` endpoint](https://docs.aws.amazon.com/cognito/latest/developerguide/login-endpoint.html#:~:text=Required.-,state,-An%20opaque%20value).

### Expected Behavior

When [LocalStack's Cognito login page via OAuth2](https://docs.localstack.cloud/aws/cognito/#oauth-flows-via-cognito-login-form) redirects back to the provided `redirect_uri`, the `state` query parameter is forwarded if provided.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

Sample `docker-compose.yml` from the repository with:
- `cognito-idp` as the only enabled service
- Some `SMTP_` settings 

However I think the configuration probably isn't the source of the issue.

To reproduce, enable `cognito-idp` service & create a pool with a client and domain.  Create a user with `AdminCreateUser` op as stated below in client commands.

Then, start the Cognito OAuth2 flow by going to the login page and providing the mandatory params + `state` query param. Sign in. The URI you are being redirected to (provided `redirect_uri`) does not contain the `state` parameter but it should.

Same as in #5307 

##### 1. User pool creation
```
aws cognito-idp create-user-pool --pool-name "foo" --cli-input-json "$(cat "$PATH_USER_POOL_TEMPLATE_JSON")"
```

<summary>
📄 User pool JSON template
<details>
<pre>
{
    "PoolName": "OVERWRITTEN BY COMMAND",
    "Policies": {
        "PasswordPolicy": {
            "MinimumLength": 8,
            "RequireUppercase": true,
            "RequireLowercase": true,
            "RequireNumbers": true,
            "RequireSymbols": true,
            "TemporaryPasswordValidityDays": 7
        }
    },
    "LambdaConfig": {},
    "AutoVerifiedAttributes": [
        "email"
    ],
    "AliasAttributes": [
        "email"
    ],
    "SmsVerificationMessage": "Your verification code is {####}. ",
    "EmailVerificationMessage": "Your verification code is {####}. ",
    "EmailVerificationSubject": "Your verification code",
    "VerificationMessageTemplate": {
        "SmsMessage": "Your verification code is {####}. ",
        "EmailMessage": "Your verification code is {####}",
        "EmailSubject": "Your reset password code",
        "DefaultEmailOption": "CONFIRM_WITH_CODE"
    },
    "SmsAuthenticationMessage": "Your authentication code is {####}. ",
    "MfaConfiguration": "OFF",
    "EmailConfiguration": {
        "EmailSendingAccount": "COGNITO_DEFAULT"
    },
    "UserPoolTags": {},
    "AdminCreateUserConfig": {
        "AllowAdminCreateUserOnly": true,
        "InviteMessageTemplate": {
            "SMSMessage": "Your username is {username} and temporary password is {####}",
            "EmailMessage": "Your username is {username} and temporary password is {####}",
            "EmailSubject": "Welcome!"
        }
    },
    "Schema": [
        {
            "Name": "email",
            "AttributeDataType": "String",
            "DeveloperOnlyAttribute": false,
            "Mutable": true,
            "Required": true,
            "StringAttributeConstraints": {
                "MinLength": "0",
                "MaxLength": "2048"
            }
        }
    ],
    "UserPoolAddOns": {
        "AdvancedSecurityMode": "AUDIT"
    },
    "UsernameConfiguration": {
        "CaseSensitive": false
    },
    "AccountRecoverySetting": {
        "RecoveryMechanisms": [
            {
                "Priority": 1,
                "Name": "verified_email"
            }
        ]
    }
}
</pre>
</details>
</summary>

##### 2. User pool client creation
```
aws cognito-idp create-user-pool-client --user-pool-id "$CREATED_USER_POOLID" \
  --callback-urls "https://localhost:9100/v1/auth/idpresponse" \
  --logout-urls "http://localhost:8100/" \
  --cli-input-json "$(cat "$PATH_USER_POOL_CLIENT_TEMPLATE_JSON")"
```

<summary>
📄 User pool client JSON template
<details>
<pre>
{
  "UserPoolId": "OVERWRITTEN BY COMMAND",
  "ClientName": "foo-service",
  "GenerateSecret": true,
  "RefreshTokenValidity": 30,
  "ExplicitAuthFlows": [
    "ALLOW_REFRESH_TOKEN_AUTH"
  ],
  "SupportedIdentityProviders": [
    "COGNITO"
  ],
  "CallbackURLs": [
    "OVERWRITTEN BY COMMAND"
  ],
  "LogoutURLs": [
    "OVERWRITTEN BY COMMAND"
  ],
  "AllowedOAuthFlows": [
    "code"
  ],
  "AllowedOAuthScopes": [
    "openid"
  ],
  "AllowedOAuthFlowsUserPoolClient": true,
  "PreventUserExistenceErrors": "ENABLED"
}
</pre>
</details>
</summary>

##### 3. User pool domain creation
```
aws cognito-idp create-user-pool-domain --domain "foodomain" --user-pool-id "$CREATED_USER_POOLID"
```

##### 4. User creation
```
aws cognito-idp admin-create-user \
  --user-pool-id "$CREATED_USER_POOL_ID" \
  --username "$(uuidgen | lowercase)" \
  --user-attributes 'Name=email,Value=example@example.com' 'Name=email_verified,Value=true' \
  --desired-delivery-mediums EMAIL --no-force-alias-creation
```

### Environment

```markdown
- OS: macOS Monterrey 12.0.1 (21A559)
- LocalStack: latest
```

**Comment by twissteros** [comment]
This issue actually blocks integrating LocalStack's Cognito with Spring Security.

**Comment by giograno** [comment]
Hi @davidlj95, thanks for reporting the issue. We released a fix that you will find by pulling the `latest` Docker image. 
Please feel free to report eventual additional problems. Thank you very much 🙏

**Comment by davidlj95** [comment]
Great news @giograno , thanks ! 😊
