### ISSUE TITLE
bug: invite an unconfirmed user (send invite again) does not behave as expected

### ISSUE THREAD

**Issue by davidlj95** [localstack/localstack#5309]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When creating a user in an AWS Cognito User Pool, you can use [`AdminCreateUser`][admin-create-user-api] if the user doesn't sign up themselves, but it's an administrator of the app who does it for them. 

Then, the user has seven days to use the received temporary password (sms / email) to sign in into the app and set their own password. After that, the temporary password expires.

It is very useful then, to be able to invite the same user again, so if somehow they lost the first temporary password message or they wanted a new one after that time to receive another invitation.

In order to do so, you can call [`AdminCreateUser`][admin-create-user-api] again, specifying the `username` you want to reinvite and setting [`MessageAction` field in the request](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_AdminCreateUser.html#:~:text=Required%3A%20No-,MessageAction,-Set%20to%20RESEND) to `RESEND` & the [`DesiredDeliveryMediums`](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_AdminCreateUser.html#API_AdminCreateUser_RequestSyntax). 

> A bit weird though, but we found it by checking [a StackOverflow post](https://stackoverflow.com/a/53195458/3263250)

In LocalStack, however, when calling the `AdminCreateUser` API, with a `username` that already exists, but hasn't registered yet so could be reinvited again, the response is `400 UsernameExistsException`.

[admin-create-user-api]: https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_AdminCreateUser.html

### Expected Behavior

In AWS Cognito User Pools API, the expected behaviour is to return `200 OK` response if the user with that username exists and is not confirmed (can be reinvited).

Or `400 UnsupportedUserStateException` if the user with that username exists, but the user is already registered. 

More specifically, not in `FORCE_CHANGE_PASSWORD` [status](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_UserType.html#:~:text=Required%3A%20No-,UserStatus,-The%20user%20status), but in `CONFIRMED` status. This transition happens once the user completes the first sign in flow by setting their password using the received temporary password.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

Sample `docker-compose.yml` from the repository with:
- `cognito-idp` as the only enabled service
- Some `SMTP_` settings 

However I think the configuration probably isn't the source of the issue.

To reproduce, enable `cognito-idp` service & create a pool with a client and domain.  Create a user with `AdminCreateUser` op as stated below in client commands.

Then, when calling `AdminCreateUser` API again (when the created user has not completed the first sign in yet). Specify we want to invite the user, instead of create a new one by setting `MessageAction` field set to `RESEND` (and in this case `DesiredDeliveryMediums` set to `EMAIL`). Response is `400 UsernameExistsException` instead of `200 ok`.

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)
Same as in #5307 

##### 1. User pool creation
```
aws cognito-idp create-user-pool --pool-name "foo" --cli-input-json "$(cat "$PATH_USER_POOL_TEMPLATE_JSON")"
```

<summary>
📄 User pool JSON template
<details>
<pre>
{
    "PoolName": "OVERWRITTEN BY COMMAND",
    "Policies": {
        "PasswordPolicy": {
            "MinimumLength": 8,
            "RequireUppercase": true,
            "RequireLowercase": true,
            "RequireNumbers": true,
            "RequireSymbols": true,
            "TemporaryPasswordValidityDays": 7
        }
    },
    "LambdaConfig": {},
    "AutoVerifiedAttributes": [
        "email"
    ],
    "AliasAttributes": [
        "email"
    ],
    "SmsVerificationMessage": "Your verification code is {####}. ",
    "EmailVerificationMessage": "Your verification code is {####}. ",
    "EmailVerificationSubject": "Your verification code",
    "VerificationMessageTemplate": {
        "SmsMessage": "Your verification code is {####}. ",
        "EmailMessage": "Your verification code is {####}",
        "EmailSubject": "Your reset password code",
        "DefaultEmailOption": "CONFIRM_WITH_CODE"
    },
    "SmsAuthenticationMessage": "Your authentication code is {####}. ",
    "MfaConfiguration": "OFF",
    "EmailConfiguration": {
        "EmailSendingAccount": "COGNITO_DEFAULT"
    },
    "UserPoolTags": {},
    "AdminCreateUserConfig": {
        "AllowAdminCreateUserOnly": true,
        "InviteMessageTemplate": {
            "SMSMessage": "Your username is {username} and temporary password is {####}",
            "EmailMessage": "Your username is {username} and temporary password is {####}",
            "EmailSubject": "Welcome!"
        }
    },
    "Schema": [
        {
            "Name": "email",
            "AttributeDataType": "String",
            "DeveloperOnlyAttribute": false,
            "Mutable": true,
            "Required": true,
            "StringAttributeConstraints": {
                "MinLength": "0",
                "MaxLength": "2048"
            }
        }
    ],
    "UserPoolAddOns": {
        "AdvancedSecurityMode": "AUDIT"
    },
    "UsernameConfiguration": {
        "CaseSensitive": false
    },
    "AccountRecoverySetting": {
        "RecoveryMechanisms": [
            {
                "Priority": 1,
                "Name": "verified_email"
            }
        ]
    }
}
</pre>
</details>
</summary>

##### 2. User pool client creation
```
aws cognito-idp create-user-pool-client --user-pool-id "$CREATED_USER_POOLID" \
  --callback-urls "https://localhost:9100/v1/auth/idpresponse" \
  --logout-urls "http://localhost:8100/" \
  --cli-input-json "$(cat "$PATH_USER_POOL_CLIENT_TEMPLATE_JSON")"
```

<summary>
📄 User pool client JSON template
<details>
<pre>
{
  "UserPoolId": "OVERWRITTEN BY COMMAND",
  "ClientName": "foo-service",
  "GenerateSecret": true,
  "RefreshTokenValidity": 30,
  "ExplicitAuthFlows": [
    "ALLOW_REFRESH_TOKEN_AUTH"
  ],
  "SupportedIdentityProviders": [
    "COGNITO"
  ],
  "CallbackURLs": [
    "OVERWRITTEN BY COMMAND"
  ],
  "LogoutURLs": [
    "OVERWRITTEN BY COMMAND"
  ],
  "AllowedOAuthFlows": [
    "code"
  ],
  "AllowedOAuthScopes": [
    "openid"
  ],
  "AllowedOAuthFlowsUserPoolClient": true,
  "PreventUserExistenceErrors": "ENABLED"
}
</pre>
</details>
</summary>

##### 3. User pool domain creation
```
aws cognito-idp create-user-pool-domain --domain "foodomain" --user-pool-id "$CREATED_USER_POOLID"
```

##### 4. User creation
```
aws cognito-idp admin-create-user \
  --user-pool-id "$CREATED_USER_POOL_ID" \
  --username "$(uuidgen | lowercase)" \
  --user-attributes 'Name=email,Value=example@example.com' 'Name=email_verified,Value=true' \
  --desired-delivery-mediums EMAIL --no-force-alias-creation
```

### Environment

```markdown
- OS: macOS Monterrey 12.0.1 (21A559)
- LocalStack: latest
```

**Comment by giograno** [comment]
Thanks @davidlj95 for the report. Unfortunately, I'm going to close this issue because it is quite outdated, and therefore, using an old version of LocalStack (it relies on an LS version [pre-ASF rollout](https://localstack.cloud/blog/2022-07-13-announcing-localstack-v1-general-availability/)).
Please, give it a new try with the current release and feel free to open a new issue if the problem still occurs. Thank you and sorry for the inconvenience.

**Comment by shyamHugo** [comment]
Still facing the same issue

**Comment by giograno** [comment]
Thanks @shyamHugo for resurfacing the issue. We shipped an issue in the `latest` Docker image. Please let us know if you experience any other issues.
