### ISSUE TITLE
Docker Launch Requires many unneeded deps

### ISSUE THREAD

**Issue by gaffo** [localstack/localstack#531]
The docker launch python command of localstack requires a bunch of deps like boto3 / etc, but doesn't actually need them, which slows setup time for just using docker way down. Maybe just break it out to it's own very simple python module that just has the port / env setup code and that's it?

**Comment by whummer** [comment]
Good point 👍 - This has been fixed in the meantime, dependencies are not lazily installed, and by default we're running LocalStack in Docker.
