### ISSUE TITLE
feature request: implement `GET /logout` Cognito IdP OAuth2 endpoint

### ISSUE THREAD

**Issue by davidlj95** [localstack/localstack#5310]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

AWS Cognito offers as part of their login via OAuth2 a [`GET /logout` endpoint](https://docs.aws.amazon.com/cognito/latest/developerguide/logout-endpoint.html).

It is very useful as the `GET /login` endpoint sets a session (via a cookie) when the user signs in. So if the user logs out from the app, but tries to sign in again, if they do it whilst the session is active (<1hr), instead of asking for credentials it will show a big button saying "Continue as X". So user can click on that and get back logged in. 

If you want from your app to logout the user from all sessions around so they have to type their username / email + password to sign in back, then this endpoint is very useful.

### 🧑‍💻 Implementation

Add the new endpoint, the code should be pretty straight forward, as doesn't imply much logic. Here's a sample of it using Node.js + Express.

Assuming we can query user pool clients by its id + their allowed logout URIs setup during the client creation.

```javascript
userPoolClient = userPoolClients.findById(req.query.client_id);

if(!userPoolClient) { 
  throw new Error('Unknown client id');
}

const logoutUri = req.query.logout_uri;
if(!userPoolClient.allowedLogoutUris.includes(logoutUri) {
  throw new Error('Logout URI not allowed by client');
}

res.location(logoutUri);
res.status(302).end();
```

**Comment by whummer** [comment]
Thanks for reporting @davidlj95 . In the meantime we have implemented a first version of the `/logout` Cognito endpoint. Can you please pull the `latest` Docker image and try again? 

On successful login, the Cognito UI will now store a cookie in your local browser, which will allow you to easily re-login with the same username. When hitting the `http://localhost:4566/logout?client_id=...&...` endpoint, the client-side cookies and server-side refresh tokens will get flushed, requiring your user to re-login via the UI.

Hope that helps - please keep us posted how it goes.. Thanks!

**Comment by davidlj95** [comment]
Amazing! 🤩  Thanks to you for the real quick implementation 💪 

Very nice that we also have the session-based (via cookes) behaviour on the mock Cognito login UI so we can be closer with AWS 👍 

Will do a test today and let you know. 

Thanks again 🙏

**Comment by davidlj95** [comment]
Hi @whummer ,

Just gave it a try and it is now the same behaviour as AWS Cognito 💪  Just for the record, leaving here a screenshot of the page you see if you haven't logged out and access again the login page:

![image](https://user-images.githubusercontent.com/8050648/151419902-e2e28666-720f-4d3e-9089-7714e65d21d9.png)

The cookie is named `ls_cognito_token` and contains a JWT whose header decodes as follows:
```
{
  "client_id": "rxaji5s1kcinouu7y716n3aw3f",
  "username": "{email/username used to sign in}",
  "code": "356284",
  "location": "https://localhost:9100/v1/auth/idpresponse?code=356284"
}
```
Only small difference is that the cookie is set to expire with the session, but AWS Cognito one expires in 1 hour. Not a detail we care about for our use case TBH. 

Also, the logout endpoint works like a charm! 💪  Only detail is AWS Cognito one returns a ~plain old~ 302, whilst LocalStack's returns a 307 👁️  Nothing to worry about either IMHO.

Thanks a lot again for the quick implementation! Closing as all has been solved.
