### ISSUE TITLE
bug: IAM Assumerole not working as expected

### ISSUE THREAD

**Issue by Sohel-Ahmed** [localstack/localstack#5313]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi Localstack team,

I'm trying to assume a role using aws cli with localstack endpoint but when I try to check the access after assuming the role, it looks that it doesn't restrict the permissions to the assumed role instead it has all same permissions before assuming role and able to access everything.

In this case here, I'm assuming role only Amazon RDS Read Only Access, but I'm able to create s3 bucket and list buckets etc. 

### Expected Behavior

Should only allow me Amazon RDS Read Only Access after assuming the role.

### How are you starting LocalStack?

Custom (please describe below)

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    localstack start

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

   ```➜  ~ cat example-role-trust-policy.json
{
    "Version": "2012-10-17",
    "Statement": {
        "Effect": "Allow",
        "Principal": { "AWS": "arn:aws:iam::000000000000:root" },
        "Action": "sts:AssumeRole"
    }
}
➜  ~ aws iam create-role --role-name example-role --assume-role-policy-document file://example-role-trust-policy.json  --endpoint-url http://localhost:4566
➜  ~ aws iam attach-role-policy --role-name example-role --policy-arn "arn:aws:iam::aws:policy/AmazonRDSReadOnlyAccess" --endpoint-url http://localhost:4566
➜  ~ aws iam list-attached-role-policies --role-name example-role --endpoint-url http://localhost:4566
➜  ~ aws iam list-roles --query "Roles[?RoleName == 'example-role'].[RoleName, Arn]"  --endpoint-url http://localhost:4566
➜  ~ aws sts assume-role --role-arn "arn:aws:iam::000000000000:role/example-role" --role-session-name AWSCLI-Session --endpoint-url http://localhost:4566
➜  ~ export AWS_ACCESS_KEY_ID="XXXXXXXXXXXXX"
➜  ~ export AWS_SECRET_ACCESS_KEY="XXXXXXXXXXXXXXXXXXX"
➜  ~ export AWS_SESSION_TOKEN="XXXXXXXXXXXXXX"
➜  ~ aws sts get-caller-identity --endpoint-url http://localhost:4566
➜  ~ aws s3 ls  --endpoint-url http://localhost:4566
➜  ~ aws s3api create-bucket --bucket my-bucket --region us-east-1 --endpoint-url http://localhost:4566
➜  ~ aws sts get-caller-identity --endpoint-url http://localhost:4566
➜  ~ aws s3 ls  --endpoint-url http://localhost:4566
2022-01-18 09:28:01 my-bucket```


### Environment

```markdown
- OS: Mac OS Big Sur 11.6.2
- LocalStack: 0.12.19.1
```

**Comment by PikaBlue107** [comment]
IAM enforcement currently seems to be a LocalStack Pro feature, enabled by setting the environment variable `ENFORCE_IAM=1`.

https://docs.localstack.cloud/user-guide/aws/iam/

**Comment by krishgopi007** [comment]
Hi @PikaBlue107 ,

Do you know if enforce_iam=1  will work with localstack_pro TRIAL version   ?

**Comment by PikaBlue107** [comment]
@krishgopi007 I'm only parroting what I find in the docs, and I don't see an exact answer to your question, but I imagine the trial version for Pro has all of the same features as the full Pro version.
