### ISSUE TITLE
bug: Unable to create FIFO queue using CDK

### ISSUE THREAD

**Issue by heshamnaim** [localstack/localstack#5330]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Queues created via CDK are not set as FIFO type

### Expected Behavior

Expect the queues to be FIFO.

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    localstack start -d

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)
```
sqs_notifier_queue = sqs.Queue(self, "notifier-queue", fifo = True, queue_name = 'notifier.fifo', content_based_deduplication = True)
sqs_db_queue = sqs.Queue(self, "db-queue", fifo = True, queue_name = 'db.fifo', content_based_deduplication = True, visibility_timeout = core.Duration.seconds(90 + 5))
```

above creates standard queues however using awslocal cli works to create FIFO queues. This is the work around I am using now. After deploying i delete and recreate the queues 

```
awslocal sqs delete-queue --queue-url http://localhost:4566/000000000000/db.fifo;
awslocal sqs create-queue --queue-name "db.fifo" --attributes "ContentBasedDeduplication=true,FifoQueue=true";
awslocal sqs delete-queue --queue-url http://localhost:4566/000000000000/notifier.fifo;
awslocal sqs create-queue --queue-name "notifier.fifo" --attributes "ContentBasedDeduplication=true,FifoQueue=true"'
```

### Environment

```markdown
- OS: Mac
- LocalStack: 0.13.3.3
```

**Comment by heshamnaim** [comment]
![image](https://user-images.githubusercontent.com/1829304/150699356-6a7473a2-55fa-4ae7-b09d-e78aa17ddeb3.png)

added a screen shot after cdk creation

**Comment by heshamnaim** [comment]
![image](https://user-images.githubusercontent.com/1829304/150699521-cbb2e008-8b8d-4e5b-986b-63628ce35f89.png)

here is what it looks like after deleted and recreated via `awslocal` cli.

**Comment by pinzon** [comment]
Hi @heshamnaim this is a problem with Moto SQS, the PR is already in review but in the meantime you can change the service provider with `SQS_PROVIDER=elasticmq`

**Comment by heshamnaim** [comment]
Thanks @pinzon for the update!

**Comment by pinzon** [comment]
The PR that fixes this issue has been merged. Make sure to download the latest image of Localstack.
Thank you for reporting the problem.
