### ISSUE TITLE
question: Lambda Java runtime missing modules?

### ISSUE THREAD

**Issue by NutterzUK** [localstack/localstack#5331]
### Is there an existing issue for this?

- [X] I have searched the existing issues and read the documentation

### Question

When I create a Java lambda function making use of Java's new HTTP Client (New in Java 11), I get Class Not Found failures that differ from the behaviour on AWS.

After searching and googling, I found someone else who has made a very small example of this issue, but it doesn't look to be resolved as far as I can tell:

https://github.com/Jimon-s/localstack-issue-lambda-httpclient

How can I use the Java http client module in my lambda on localstack?

Happy to contribute a fix if there's anything needed that isn't supported, though I may need pointing in the right direction.

Thanks,

### Anything else?

https://github.com/Jimon-s/localstack-issue-lambda-httpclient

**Comment by whummer** [comment]
Thanks for reporting this issue and providing the reproducible sample! Please note that we're in the process of migrating our Lambda implementation to use the official AWS base images (see also discussion on [this draft PR](https://github.com/localstack/localstack/pull/4734)). We're working on it with high priority, and should hopefully have a first version out in the next 1-2 weeks. As a workaround in the meantime, we'd recommend packaging any missing JAR files into your Lambda deployment package. Thanks!

**Comment by NutterzUK** [comment]
@whummer Thanks! That's perfect and exactly what I was after.

Would any additional support with testing this help? I'd be happy to have a go building that PR locally and seeing how it goes, if it would help?

**Comment by dfangl** [comment]
Thank you for the offer @NutterzUK . We will ping you again once the work is mature enough to be tested!

**Comment by NutterzUK** [comment]
Hi @dfangl , I was wondering if there has been any progress on this that I may be able to help out with testing please?

**Comment by dfangl** [comment]
Hi @NutterzUK !
The new lambda provider should now be ready for testing in the meantime. Can you try setting `PROVIDER_OVERRIDE_LAMBDA=asf` and check if this fixes this problem? Thanks!
Sorry for the long wait!

**Comment by dfangl** [comment]
Will close this, if it does not work for the new provider, please report in a new issue, linking this one and that you use the new provider! Thank you!
