### ISSUE TITLE
question: Having trouble installing in Windows 11

### ISSUE THREAD

**Issue by dkhierl-chacrasoftware** [localstack/localstack#5335]
### Is there an existing issue for this?

- [X] I have searched the existing issues and read the documentation

### Question

Using Python 3.9 following the installation page, and when about to install `py -m pip install localstack` it gives me this long error

![image](https://user-images.githubusercontent.com/94277848/150676503-d6b92c52-7eff-4420-9842-830257923b7f.png)
![image](https://user-images.githubusercontent.com/94277848/150676528-967de63d-5d32-4c09-ab78-8c2e112cc5da.png)

**Comment by MarcelStranak** [comment]
Hi, can you please download the latest version of VS build tools? 
https://visualstudio.microsoft.com/downloads/ -> https://aka.ms/vs/17/release/vs_BuildTools.exe

Different ways of installing VS build tools:
**In powershell:**
**Chocolatey:**
https://community.chocolatey.org/packages/visualstudio2022buildtools
`choco install visualstudio2022buildtools`
**Winget:**
`winget install "Visual Studio Build Tools 2022"`
