### ISSUE TITLE
SNS HTTP Subscription - 'Response' object has no attribute 'get_data'

### ISSUE THREAD

**Issue by ricardo-ropelli** [localstack/localstack#5342]
import requests

if __name__ == '__main__':
    subscriber = {
        "Endpoint": "http://localhost:8080/iaas-opendata-opbf1-lake-consumer",
        "TopicArn": "arn:aws:sns:sa-east-1:000000000000:iaas-opendata-opbf1-lake-consumer",
        "SubscriptionArn": "SubscriptionArn"
    }

    response = requests.post(
        subscriber["Endpoint"],
        headers={
            "Content-Type": "text/plain",
            # AWS headers according to
            # https://docs.aws.amazon.com/sns/latest/dg/sns-message-and-json-formats.html#http-header
            "x-amz-sns-message-type": "Notification",
            "x-amz-sns-topic-arn": subscriber["TopicArn"],
            "x-amz-sns-subscription-arn": subscriber["SubscriptionArn"],
            "User-Agent": "Amazon Simple Notification Service Agent",
        },
        data="This is a simple message",
        verify=False,
    )

    delivery = {
        "statusCode": response.status_code,
        "providerResponse": response.get_data(),
    }

lib requests does not have 'get_data', instead must use 'content'.
Example: response.content.decode("utf-8")

https://github.com/localstack/localstack/blob/1f72e552b8a2bd6739d648e4b6f06fb64350ebdb/localstack/services/sns/sns_listener.py#L639

**Comment by whummer** [comment]
Thanks again for reporting and providing a fix @ricardo-ropelli ! 👍
