### ISSUE TITLE
bug: LocalStack returns ListAllMyBuckets response when sending ListSecrets

### ISSUE THREAD

**Issue by rlauer6** [localstack/localstack#5344]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

LocalStack is returning ListAllMyBuckets response when a SecretsManager request for ListSecrets 

**Update:** my POST payload was incorrectly sending `Credential=.../us-west-2/s3/aws4_request` in the header although the rest of the headers were correctly indicating the service (secretsmanager).  AWS ignores the inconsistency and returns the correct result.  

### Expected Behavior

I would have expected either that the behavior mimics AWS or an error would be generated.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

### Environment

```markdown
- OS: 
- LocalStack:
```

**Comment by thrau** [comment]
Hi Rob, thanks for reporting. As you have found, we rely on correct headers to be able to route the request to the correct service. We cannot fallback properly to an endpoint prefix (like "secretsmanager.aws...") since we're ingesting all service requests to `localhost`. Glad you found the error!
