### ISSUE TITLE
bug: `AmazonopensearchserviceDestinationConfiguration` is not supported for Firehose-Streams

### ISSUE THREAD

**Issue by Dgame** [localstack/localstack#5357]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

As mentioned [here](https://github.com/localstack/localstack/issues/4834#issuecomment-1021009701) it seems like the `AmazonopensearchserviceDestinationConfiguration` was not added while implementing OpenSearch. I guess it just needs be added [here](https://github.com/localstack/localstack/blob/53b5c7788bf35b1882b6cb1949e17d27e198cf61/localstack/services/cloudformation/models/kinesisfirehose.py#L23-L27).

### Expected Behavior

I can (and should) use `AmazonopensearchserviceDestinationConfiguration` instead of `ElasticsearchDestinationConfiguration` (which I should only be able to use if I use ElasticSearch-Service).

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

Well, just use `AmazonopensearchserviceDestinationConfiguration` and your stream will never be able to deliver the records to your (external) Cluster. But it works with `ElasticsearchDestinationConfiguration`.

### Environment

```markdown
- OS: Windows mit WSL (Ubuntu 20.04)
- LocalStack: latest
```

**Comment by silv-io** [comment]
Yes, the Firehose API has not yet been updated to also support OpenSearch. 
We're currently working on merging the internal management of Elasticsearch and OpenSearch clusters (see #5341). This will allow us to add that functionality to the Firehose API. We'll keep you posted when the feature is ready!

**Comment by Dgame** [comment]
Thanks a lot!
