### ISSUE TITLE
bug:Lambda Layer implementation in localstack pro version

### ISSUE THREAD

**Issue by sherif2021github** [localstack/localstack#5358]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

 I have Localstack pro license but unable to add lambda layer.There is no proper  documentation found for that.I will be great full for any support..Currently i am facing import issues in the lambda code.

### Expected Behavior

Lambda layer implementation steps or code snippets for python environment.

### How are you starting LocalStack?

With a `docker run` command

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal s3 mb s3://mybucket

### Environment

```markdown
- OS: Ubuntu 20.04
- LocalStack: latest
```

### Anything else?

nothing

**Comment by whummer** [comment]
Thanks for reporting @sherif2021github . Can you please share your full LocalStack configuration (e.g., docker-compose.yml), as well as a few snippets of your application code, to help us replicate your use case end-to-end. Please also share the full logs of your LocalStack container, with `DEBUG=1` enabled.

Also, here's a simple sample application using Lambda layers that could help as a starting point: https://github.com/localstack/localstack-pro-samples/tree/master/serverless-lambda-layers Hope that helps - please keep us posted how it goes.. Thanks!

**Comment by ashameem123** [comment]
@whummer - Does LS has any documentation on hw to use lambda layers ? I have PRO license but unable to find steps on how to test my functions that has lambda layer configuration.

**Comment by silv-io** [comment]
Hello @ashameem123! Documentation about Lambda layers can be found in [our docs page](https://docs.localstack.cloud/aws/lambda/#lambda-layers)

**Comment by dfangl** [comment]
I will close this now as the original question has been answered. If you find any issues with the lambda layer implementation, please do not hesitate to open another issue!
