### ISSUE TITLE
Message attributes are not delivered when publishing a message on a SNS topic and receiving it from an SQS queue

### ISSUE THREAD

**Issue by JoaoRXFernandesJG** [localstack/localstack#537]
Hi,

Following up on [https://github.com/localstack/localstack/issues/137](https://github.com/localstack/localstack/issues/137) I'm not being able to see MessageAttributes when publishing on SNS and receiving on SQS.

@whummer the steps you proposed on 137 don't seem to be receiving the MessageAttributes but only Attributes if that makes any sense?

Any help would be most appreciated.

Please don't hesitate should you need any additional details.

Thanks,

Joao

PS: great work on this project!

**Comment by JoaoRXFernandesJG** [comment]
Managed to figure it out, message attributes actually show up within the Body attribute.

The only thing missing from @whummer example is the --attribute-names All parameter as such:
QUEUE_ARN=`aws --endpoint-url=http://localhost:4576 --region us-east-1 sqs get-queue-attributes --queue-url $QUEUE_URL --attribute-names All | jq -r .Attributes.QueueArn`

**Comment by philBrown** [comment]
Leaving this link here as this was driving me bonkers too. I thought it was a LocalStack issue but this is how the real thing works too

https://stackoverflow.com/questions/44238656/how-to-add-sqs-message-attributes-in-sns-subscription
