### ISSUE TITLE
feature request: [Lambda] Support ES Modules in Node.js runtime

### ISSUE THREAD

**Issue by esperecyan** [localstack/localstack#5383]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

The AWS Lambda Node.js runtime now allows ES Modules script to be specified directly as handler.
https://aws.amazon.com/about-aws/whats-new/2022/01/aws-lambda-es-modules-top-level-await-node-js-14/

Is it possible to support ES Modules in LocalStack as well?

**Comment by pinzon** [comment]
Hi @esperecyan, the support for this feature was implemented in #6200, I tested myself both of the methods describe by AWS in this [doc](https://aws.amazon.com/blogs/compute/using-node-js-es-modules-and-top-level-await-in-aws-lambda/).
