### ISSUE TITLE
bug: docker-compose `command:` option doesn't work.

### ISSUE THREAD

**Issue by y-okamoto-1113** [localstack/localstack#5390]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

docker-compose `command:` option doesn't work.

this is my `docker-compose.yml`.
```.yml
localstack:
    image: localstack/localstack:latest
    container_name: localstack
    command: aws --endpoint-url=http://localhost:4566 s3api create-bucket --bucket s3-test-bucket
    ports:
      - 4566:4566
    environment:
      SERVICES: s3
      AWS_DEFAULT_REGION: ap-northeast-1
      DATA_DIR: /tmp/localstack/data
      DEBUG: 1
      LS_LOG: trace-internal
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
    volumes:
      - ./docker/localstack/:/docker-entrypoint-initaws.d
```

when i run `docker-compose up localstack`, localstack container gets up, but  `s3-test-bucket` isn't created.
because docker-compose `command:` option doesn't work.

### Expected Behavior

i expects that docker-compose `command:` option runs well.
because i want to create s3 bucket when localstack container gets up.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)
i start localstack, using docker-compose.yml
```.yml
localstack:
    image: localstack/localstack:latest
    container_name: localstack
    command: aws --endpoint-url=http://localhost:4566 s3api create-bucket --bucket s3-test-bucket
    ports:
      - 4566:4566
    environment:
      SERVICES: s3
      AWS_DEFAULT_REGION: ap-northeast-1
      DATA_DIR: /tmp/localstack/data
      DEBUG: 1
      LS_LOG: trace-internal
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
    volumes:
      - ./docker/localstack/:/docker-entrypoint-initaws.d
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)
i run only `docker-compose up localstack`.

### Environment

```markdown
- OS: Big Sur 11.6 (Intel chip, not M1)
- LocalStack: docker image, `localstack/localstack:latest`
```

### Anything else?

i love localstack!!!
Thank you for developing such a wonderful software!

**Comment by whummer** [comment]
Thanks for reporting @y-okamoto-1113 , and for the positive feedback. Indeed, the `command` does not work (and is not supposed to).

Given that you already have this volume mount:
```
    volumes:
      - ./docker/localstack/:/docker-entrypoint-initaws.d
```
... you can create an executable shell script in `./docker/localstack/init.sh` with this content:
```
awslocal s3api create-bucket --bucket s3-test-bucket
```
This script should get executed when the container starts. Please note that you need to run `chmod +x init.sh` to make the script executable! Hope that helps - please keep us posted how it goes..

**Comment by y-okamoto-1113** [comment]
@whummer 
>  Indeed, the command does not work (and is not supposed to).

thank you very much!
I understood the specification.

i could create a bucket . using `awslocal s3api create-bucket --bucket s3-test-bucket`
But i could NOT, using `aws --endpoint-url=http://localhost:4566 s3api create-bucket --bucket s3-test-bucket`.
i have no idea...😭

please would you teach me why....

**Comment by y-okamoto-1113** [comment]
@whummer 
Thank you so much!!!
I've fixed it!!!

**Comment by RollsChris** [comment]
Hi I'm having the same issue, if I'm understanding correctly then localstack already has an entry point defined in the image so "command" property wont work. 

I have tried putting the command in a script here "C:\Users\<name>\.docker\localstack\init.sh" on my host machine ( not sure what this will achieve, I have not seen it mentioned before) but its not working.

I'm not sure what else to try, any tips?
Thanks
