### ISSUE TITLE
bug: Can`t create state machine of type EXPRESS

### ISSUE THREAD

**Issue by Mateus-pilo** [localstack/localstack#5392]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hey Guys ✌, I`m trying to crate a state machine of type **EXPRESS** on the local, throug CDKLOCAL with the following code:

``` 
const stepfunction = new sfn.StateMachine(this, "StateMachine", {
      definition,
      stateMachineType: sfn.StateMachineType.EXPRESS,
});
```

But when i call  ```cdklocal deploy``` the machine state created stayed the STANDARD see this image:

![image](https://user-images.githubusercontent.com/56692712/151662909-7450a6db-1d16-4b8e-9a16-e5871083cdaa.png)

But when i call ``` cdk deploy``` on AWS the machine state created stayed the normal EXPRESS.

Has anyone ever experienced this 😎 ?

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

### Environment

```markdown
- OS: Ubuntu 20
- LocalStack: docker image, `localstack/localstack:latest`
```

**Comment by pinzon** [comment]
Hi @Mateus-pilo, the PR that fixes this issue has been merged. Just consider that the execution of the Express type is yet to be supported.
