### ISSUE TITLE
bug: LocalStack randomly stops responding

### ISSUE THREAD

**Issue by GalFuchs** [localstack/localstack#5397]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

LocalStack runs fine for a while, after an unspecified amount of time (could be two minutes, could be an hour) the console spits out a message `localstack_main   | Listening at http://:::51679` and LocalStack stops responding.
This has been reproduced on several different machines.

### Expected Behavior

LocalStack should continue working as planned.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker-compose.yml (partial, only listing LocalStack service):
   ```localstack:
    image: localstack/localstack:latest
    container_name: localstack_main
    ports:
      - "4566:4566"
      - "4571:4571"
      - "4600:4600"
    environment:
      - SERVICES=s3,sqs,dynamodb,lambda,apigateway,iam,sns,route53,acm,kms,sts,ec2,cloudwatch
      - KINESIS_PROVIDER=kinesalite
      - DEFAULT_REGION=us-east-1
      - DEBUG=1
      - START_WEB=0
      - LS_LOG=error
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LOCALSTACK_API_KEY=$LOCALSTACK_API_KEY
      - LAMBDA_EXECUTOR=docker
      - LAMBDA_REMOTE_DOCKER=false
      - HOST_TMP_FOLDER=${PWD}/tmp/localstack
      - LAMBDA_DOCKER_NETWORK=local-dev_default
      - PERSIST_ALL=false
      - LAMBDA_CONTAINER_REGISTRY=mlupin/docker-lambda
      - LAMBDA_DOCKER_FLAGS=--add-host [redacted]:172.17.0.1
    volumes:
      # Logs
      - ./logs/localstack:/var/log/localstack
      # Docker Lambda executor requirements
      - ${PWD}/tmp/localstack:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    Infrastructure created with Terraform.

### Environment

```markdown
- OS: MacOS Monterey 12.1 (Apple M1)
- LocalStack: latest
```

### Anything else?

Started happening randomly, doesn't seem to be related to any commands being run as far as we are aware.

**Comment by kubukoz** [comment]
I'm seeing something similar: even a `curl localhost:4566` within localstack's docker container seems to hang every couple seconds. I believe this is happening when you have something calling SQS, but I haven't yet been able to minimize the issue more.

What I'm getting happens on macos amd64, macos arm64 and linux arm64.

**Comment by HarshCasper** [comment]
Thank you for reaching out.

This issue will be closed because I cannot reproduce the error with the latest LocalStack version. Please use the recommended [`docker-compose.yml`](https://github.com/localstack/localstack/blob/master/docker-compose.yml) to try starting LocalStack. If you're still experiencing this issue on the [latest supported version](https://hub.docker.com/r/localstack/localstack/tags) of LocalStack, please file a new issue for that version of LocalStack.
