### ISSUE TITLE
bug: IAM 

### ISSUE THREAD

**Issue by bentcoder** [localstack/localstack#5399]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

This CLI [example](https://docs.localstack.cloud/aws/iam/) may be out of date as I am always able to run any S3 commands even if I enable IAM enforcer with `ENFORCE_IAM=1`.

### Expected Behavior

At least see the permission errors as shown in the example.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

Same commands as the ones in the link above.

### Environment

```markdown
- OS: MacOS
- LocalStack: latest
```

### Anything else?

I am also able to run any AWS S3 operations with Golang SDK.

**Comment by dominikschubert** [comment]
@bentcoder Are you running localstack with an active API key? Asking because this is a LocalStack PRO feature and when running community (i.e. without a key) this would be the expected behavior.

**Comment by bentcoder** [comment]
I see! In that case this can be clpsed as I am not using PRO. Thank you.

**Comment by erihanse** [comment]
Is the intention to list this as a pro feature under https://docs.localstack.cloud/aws/feature-coverage?
