### ISSUE TITLE
UnsupportedContentTypeException on multipart upload.

### ISSUE THREAD

**Issue by max8github** [localstack/localstack#540]
Getting this error when doing a multipart upload with alpakka:
```
akka.http.scaladsl.unmarshalling.Unmarshaller$UnsupportedContentTypeException: Unsupported Content-Type, supported: application/xml, application/octet-stream
```

Issue seems similar to this one and others, where the JSON content-type was not provided:
```
https://github.com/akka/alpakka/issues/457
https://github.com/akka/alpakka/issues/142
https://github.com/findify/s3mock/issues/61
https://github.com/findify/s3mock/issues/66
```
The fix in s3mock is probably similar to the fix needed in Localstack for this issue.

**Comment by whummer** [comment]
Thanks for reporting @max8github . A couple of fixes around multipart uploads have been pushed in the meantime - closing this issue, please re-open if the problem persists.
