### ISSUE TITLE
bug: lambda authorizer ignored in pro

### ISSUE THREAD

**Issue by bkerzner** [localstack/localstack#5406]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am creating an API Gateway with a Lambda Authorizer via a CloudFormation stack. When I invoke the API without an `Authorization` header or with an invalid value for the `Authorization` header, the API returns a 200. It's as if the Lambda Authorizer is bypassed entirely. 

### Expected Behavior

If I omit the `Authorization` header, an invocation of the API Gateway should return a 4XX code. If I provide an `Authorization` header with an invalid value, an invocation of the API Gateway should return a 4XX code.

### How are you starting LocalStack?

With a `docker run` command

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

docker run --rm -it -p 4566:4566 -p 4571:4571 -e LOCALSTACK_API_KEY=$env:LOCALSTACK_API_KEY localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```
# create s3 bucket and upload c# lambda authorizer zip to s3
aws --endpoint-url=http://localhost:4566 s3api create-bucket --bucket timeseries-ingest-lambda-artifacts
aws --endpoint-url=http://localhost:4566 s3 cp index.zip s3://timeseries-ingest-lambda-artifacts/KinesisAPILambdaAuthorizer/index.zip
# create stream
aws --endpoint-url=http://localhost:4566 kinesis create-stream --stream-name test-timeseries-ingest-stream --shard-count 1
# create stack
aws --endpoint-url=http://localhost:4566 cloudformation create-stack --stack-name test-kinesis-api --template-body file://cloudformation-kinesis-api-resources-PER-ENVIRONMENT.yaml --parameters ParameterKey=AppName,ParameterValue=timeseries-ingest ParameterKey=Environment,ParameterValue=test
```

This is the CloudFormation template: [cloudformation-kinesis-api-resources-PER-ENVIRONMENT.yaml.txt](https://github.com/localstack/localstack/files/7973188/cloudformation-kinesis-api-resources-PER-ENVIRONMENT.yaml.txt)

### Environment

```markdown
- OS: Ubuntu 20.04
- LocalStack: latest (as of 3 days ago)
```

### Anything else?

**Comment by calvernaz** [comment]
Hi @bkerzner, whilst trying to reproduce this issue I see some errors in LocalStack coming from cloudformation, even tho que `aws cli` succeeds. 

But to make sure, I'm being hit by the same issue, could you run these commands in your side?

**Comment by calvernaz** [comment]
Hi @bkerzner you can dismiss the error above, I sorted it out. I have good news for you, because i recently fixed this issue, once it gets upstream I'll notify you.

**Comment by bkerzner** [comment]
Awesome, that's great.

**Comment by calvernaz** [comment]
Hi @bkerzner, the changes were published upstream yesterday. Could you try the new docker image? 👍

**Comment by bkerzner** [comment]
Hi, so I'm trying to verify the fix, but running into this error, which does not happen when the CloudFormation stack is deployed in AWS:
```
localstack.utils.cloudformation.template_deployer: Unexpected error retrieving details for resource type AWS::ApiGateway::Method: Exception: Unable to fetch details for resource "KinesisIngestApiResource1" (attribute "Ref")
```
I even added
```
DependsOn
-KinesisIngestApiResource1
```
in the `AWS::ApiGateway::Method` resource definition, but that didn't fix it.

Thoughts?

**Comment by calvernaz** [comment]
Hi @bkerzner, does this error stops the authorizer from being called? 

Some errors are just flagging that the resource is not created and we recursively need to lookup and create them. I was able to do it in the repository above (https://github.com/localstack/support-samples/tree/main/localstack_issue_5406).

**Comment by calvernaz** [comment]
Hi @bkerzner, sorry that repository is private, I'll find a way to share with you.

I need to go back to the cloudformation code, because the Authorizer is not being built properly.

**Comment by calvernaz** [comment]
Hi @bkerzner I have a public repository you can check now https://github.com/localstack/troubleshooting-issues/tree/main/issue_5406. There are instructions to test it using the authorization header.

**Comment by calvernaz** [comment]
Hi @bkerzner, are you using the project above to test it? I could reproduce the previous issue and call the authorizers. So I'm wondering if you are testing something different and there are other issues

**Comment by bkerzner** [comment]
Good point. So I ran it just now with the above project. At first, the `run.sh` script was failing because `lambda.zip` did not exist in the directory. To fix this, I zipped up `lambda.py` then ran the `run.sh` script again, successfully. 

Then I did this:
```
C:\Users\BorisKerzner>curl -v -X POST "http://localhost:4566/restapis/4b05xoq7dz/local/_user_request_/sites/1/ingest"  -H "Content-Type:application/json" -d "{\"HID\": \"ad\",\"SID\": \"consequat ex velit sed\",\"Data\": {\"ipsum_e_\": 50662226}}"
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 4566 (#0)
> POST /restapis/4b05xoq7dz/local/_user_request_/sites/1/ingest HTTP/1.1
> Host: localhost:4566
> User-Agent: curl/7.55.1
> Accept: */*
> Content-Type:application/json
> Content-Length: 76
>
* upload completely sent off: 76 out of 76 bytes
< HTTP/1.1 403
< Content-Type: text/html; charset=utf-8
< Content-Length: 142
< x-amzn-errortype: AuthorizationError
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Methods: HEAD,GET,PUT,POST,DELETE,OPTIONS,PATCH
< Access-Control-Allow-Headers: authorization,cache-control,content-length,content-md5,content-type,etag,location,x-amz-acl,x-amz-content-sha256,x-amz-date,x-amz-request-id,x-amz-security-token,x-amz-tagging,x-amz-target,x-amz-user-agent,x-amz-version-id,x-amzn-requestid,x-localstack-target,amz-sdk-invocation-id,amz-sdk-request
< Access-Control-Expose-Headers: etag,x-amz-version-id
< Connection: close
< date: Tue, 01 Mar 2022 19:40:48 GMT
< server: hypercorn-h11
<
{"Type": "User", "message": "Authorization failed: the JSON object must be str, bytes or bytearray, not dict", "__type": "AuthorizationError"}* Closing connection 0

C:\Users\BorisKerzner>curl -v -X POST "http://localhost:4566/restapis/4b05xoq7dz/local/_user_request_/sites/1/ingest"  -H "Content-Type:application/json" -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c" -d "{\"HID\": \"ad\",\"SID\": \"consequat ex velit sed\",\"Data\": {\"ipsum_e_\": 50662226}}"
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 4566 (#0)
> POST /restapis/4b05xoq7dz/local/_user_request_/sites/1/ingest HTTP/1.1
> Host: localhost:4566
> User-Agent: curl/7.55.1
> Accept: */*
> Content-Type:application/json
> Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
> Content-Length: 76
>
* upload completely sent off: 76 out of 76 bytes
< HTTP/1.1 403
< Content-Type: text/html; charset=utf-8
< Content-Length: 142
< x-amzn-errortype: AuthorizationError
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Methods: HEAD,GET,PUT,POST,DELETE,OPTIONS,PATCH
< Access-Control-Allow-Headers: authorization,cache-control,content-length,content-md5,content-type,etag,location,x-amz-acl,x-amz-content-sha256,x-amz-date,x-amz-request-id,x-amz-security-token,x-amz-tagging,x-amz-target,x-amz-user-agent,x-amz-version-id,x-amzn-requestid,x-localstack-target,amz-sdk-invocation-id,amz-sdk-request
< Access-Control-Expose-Headers: etag,x-amz-version-id
< Connection: close
< date: Tue, 01 Mar 2022 19:43:14 GMT
< server: hypercorn-h11
<
{"Type": "User", "message": "Authorization failed: the JSON object must be str, bytes or bytearray, not dict", "__type": "AuthorizationError"}* Closing connection 0 
```

I got a 403 in both cases. 

That's a Python error, right? For what it's worth, you had suggested enclosing the JSON payload in single quotes while the fields & values inside were enclosed in double quotes. This wasn't working on my Windows machine, so I changed the single quotes to double quotes, then escaped all the remaining double quotes within.

Thoughts?

**Comment by bkerzner** [comment]
Different alternatives for single & double quotes in the request JSON payload:

```
C:\Users\BorisKerzner>curl -X POST "http://localhost:4566/restapis/4b05xoq7dz/local/_user_request_/sites/1/ingest"  -H "Content-Type:application/json" -d "{'HID':'ad','SID':'consequat','Data':{'ipsum_e_': 50662226}}"
{"Type": "User", "message": "Authorization failed: the JSON object must be str, bytes or bytearray, not dict", "__type": "AuthorizationError"}

C:\Users\BorisKerzner>curl -X POST "http://localhost:4566/restapis/4b05xoq7dz/local/_user_request_/sites/1/ingest"  -H "Content-Type:application/json" -d '{"HID":"ad","SID":"consequat","Data":{"ipsum_e_": 50662226}}'
{"Type": "User", "message": "Authorization failed: the JSON object must be str, bytes or bytearray, not dict", "__type": "AuthorizationError"}curl: (3) [globbing] unmatched close brace/bracket in column 9
```

**Comment by calvernaz** [comment]
Yes sorry I should have provided the zip or do it inside the run script. So that's a well known issue actually when the lamba runtime is not docker. If you install docker it should work just fine or just wait for us to fix the local runtime issue.

**Comment by bkerzner** [comment]
I have Docker installed. Localstack is running as a Docker container. So how would I make the lambda runtime also run in Docker?
