### ISSUE TITLE
bug: inconsistent KMS behavior for version > 0.12.16

### ISSUE THREAD

**Issue by telaoumatenyanis** [localstack/localstack#5410]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

For any version > 0.12.16, the localstack KMS behavior diverge from the actual KMS behavior for disabled keys.

1. Disabling keys does not work with ARN
```
aws kms disable-key --key-id arn:aws:kms:us-west-2:000000000000:key/806ebe89-b4f1-4853-819f-ffb3b3cdf3e6 --endpoint-url http://localhost:4566

An error occurred (500) when calling the DisableKey operation (reached max retries: 4): <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>

aws kms disable-key --key-id 806ebe89-b4f1-4853-819f-ffb3b3cdf3e6 --endpoint-url http://localhost:4566
> success
```

2. Encrypting using the disabled key works
```
aws kms encrypt --key-id arn:aws:kms:us-west-2:000000000000:key/806ebe89-b4f1-4853-819f-ffb3b3cdf3e6 --plaintext test  --endpoint-url http://localhost:4566

{
    "KeyId": "arn:aws:kms:us-west-2:000000000000:key/806ebe89-b4f1-4853-819f-ffb3b3cdf3e6", 
    "CiphertextBlob": "ODA2ZWJlODktYjRmMS00ODUzLTgxOWYtZmZiM2IzY2RmM2U22uw5MyKyuiZAFjQOUK3bO4rASoz4fRGONdin75t3xfs="
}
```

3. Generating a data key using the disabled key works
```
aws kms generate-data-key --key-id arn:aws:kms:us-west-2:000000000000:key/806ebe89-b4f1-4853-819f-ffb3b3cdf3e6 --key-spec AES_256  --endpoint-url http://localhost:4566
{
    "Plaintext": "redacted", 
    "KeyId": "arn:aws:kms:us-west-2:000000000000:key/806ebe89-b4f1-4853-819f-ffb3b3cdf3e6", 
    "CiphertextBlob": "redacted"
}
```

I guess there might be more issues, but I haven't tested all APIs.

### Expected Behavior

In localstack version 0.12.16 and in KMS production, the following behavior is expected:

1. Disabling keys works with ARN
```
aws kms disable-key --key-id  arn:aws:kms:us-west-2:000000000000:key/806ebe89-b4f1-4853-819f-ffb3b3cdf3e6  
> success
```

2. Encrypting using the disabled key does not work
```
aws kms encrypt --key-id arn:aws:kms:us-west-2:000000000000:key/806ebe89-b4f1-4853-819f-ffb3b3cdf3e6 --plaintext test

An error occurred (DisabledException) when calling the Encrypt operation: arn:aws:kms:us-west-2:000000000000:key/806ebe89-b4f1-4853-819f-ffb3b3cdf3e6  is disabled.
```

3. Generating a data key using the disabled key works
```
aws kms generate-data-key --key-id arn:aws:kms:us-west-2:000000000000:key/806ebe89-b4f1-4853-819f-ffb3b3cdf3e6  --key-spec AES_256

An error occurred (DisabledException) when calling the GenerateDataKey operation: arn:aws:kms:us-west-2:000000000000:key/806ebe89-b4f1-4853-819f-ffb3b3cdf3e6  is disabled.
```

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

All commands available in current and expected behavior.

Replace the key id with an id returned by an `aws kms create-key` command.

### Environment

```markdown
- OS: Amazon Linux 2
- LocalStack: Works in 0.12.16, fails in versions above 0.12.16
```

### Anything else?

N/A

**Comment by telaoumatenyanis** [comment]
In 0.12.17, the KMS implementation was moved to `moto`.

Looks like the moto implementation isn't checking for the key state: https://github.com/spulec/moto/blob/0a1bb6bae165b38cdec5e299a7f859f2cb27de93/moto/kms/models.py#L364-L384

The underlying `encrypt` function is also tagged as "not compatible with KMS APIs": https://github.com/spulec/moto/blob/0a1bb6bae165b38cdec5e299a7f859f2cb27de93/moto/kms/utils.py#L105

**Comment by taras-kobernyk-localstack** [comment]
Apologies for the delay. But the code has been finally merged, the key state constraints are there already.
I am going to close the ticket, but please let us know if something is still wrong.
