### ISSUE TITLE
Running cloudformation deploy

### ISSUE THREAD

**Issue by srobayo222** [localstack/localstack#5414]
### Is there an existing issue for this?

- [X] I have searched the existing issues and read the documentation

### Question

Hi Guys

Im trying to do a deploy with cloudformation using the following script
<pre>%aws_cli% cloudformation deploy ^
--template-file ../output/packaged-storage.yaml ^
    --stack-name %stack_prefix%-storage ^
    --parameter-overrides ^
        StackPrefix=%stack_prefix% ^
        ApplicationKey=%application_key% ^
        EnvironmentType=%environment_type% ^
        CdnCertificateArn=%cdn_certificate_arn% ^
        ImagesCdnHost=%images_cdn_host% ^
    --capabilities CAPABILITY_NAMED_IAM CAPABILITY_IAM ^
    --no-fail-on-empty-changeset</pre>

but in console i recieve some errors that i didnt found on the itnernet

`localstack.utils.cloudformation.template_deployer: Action "delete" for resource type Lambda::Version not yet implemented`
`localstack.utils.cloudformation.template_deployer: Unexpected resource type WAFv2::WebACL when resolving references of resource ImagesWebACL`

The resourse im trying to deploy on tthe yaml looks like this
<pre>ImagesWebACL:
    Type: AWS::WAFv2::WebACL
    Properties:
      DefaultAction:
        Allow: {}
      Name:
        Fn::Sub: ${StackPrefix}-images-WebAcl
      Rules:
      - Name: AWS-AWSManagedRulesCommonRuleSet
        Priority: 0
        OverrideAction:
          None: {}
        VisibilityConfig:
          SampledRequestsEnabled: true
          CloudWatchMetricsEnabled: true
          MetricName:
            Fn::Sub: ${StackPrefix}-images-MetricForAMRCRS
        Statement:
          ManagedRuleGroupStatement:
            VendorName: AWS
            Name: AWSManagedRulesCommonRuleSet
            ExcludedRules:
            - Name: NoUserAgent_HEADER
      Scope: CLOUDFRONT
      VisibilityConfig:
        SampledRequestsEnabled: true
        CloudWatchMetricsEnabled: true
        MetricName:
          Fn::Sub: ${StackPrefix}-images-WebAcl</pre>

I need to say that this scripts works fine on aws

**Comment by MarcelStranak** [comment]
Hi, currently the `AWS::WAFv2::WebACL` template is not yet supported in the LocalStack. Please create a [feature-request](https://github.com/localstack/localstack/issues/new/choose) for the future reference. 
You can find the list of supported CF templates on our documentation site: https://docs.localstack.cloud/aws/cloudformation/
