### ISSUE TITLE
NoSuchBucket  when accessing http://localhost:4566/restapis

### ISSUE THREAD

**Issue by pew-x2** [localstack/localstack#5418]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I'm trying to list restapis, which I've understood should be possible with http://localhost:4566/restapis, I get NoSuchBucket. 

### Expected Behavior

Would get an empty list of restapis since I have not created any. 

Accessing restapis does neither not work when I have created one , but that might be me not  doing it correctly. 

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

(using docker-compose.yml declared bellow under "Anything else")
docker-compose up 

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

curl http://localhost:4566/restapis

### Environment

```markdown
- OS: 
mac
- LocalStack: 
localstack:latest docker image
```

### Anything else?

This is my docker-compose file that I have made from docker-compose.yml on master branch.

version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    network_mode: bridge
    ports:
      # - "127.0.0.1:53:53"                # only required for Pro
      # - "127.0.0.1:53:53/udp"            # only required for Pro
      # - "127.0.0.1:443:443"              # only required for Pro
      - "127.0.0.1:4510-4559:4510-4559"
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4571:4571"
    environment:
      - SERVICES=lambda,s3,apigateway
      - DEBUG=1
      # - DATA_DIR=${DATA_DIR-}
      # - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      # - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY-}  # only required for Pro
      - HOST_TMP_FOLDER=${TMPDIR:-/tmp/}localstack
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

**Comment by dominikschubert** [comment]
You'll need to do a "normal" AWS API call such as via the AWS CLI:  `awslocal apigateway get-rest-apis` if you want to get a list of your deployed APIs.

**Comment by dhallam** [comment]
For @pew-x2 and anyone else who comes across this in future, you can hit the endpoint by presenting an 

```
curl -H "Authorization: AWS4-HMAC-SHA256 Credential=testkey/date/eu-west-2/apigateway/aws4_request" http://localhost:4566/restapis
```

making sure to set the region (`eu-west-2` in the example above) with whichever region you are using.

You can see this in use in the localstack serverless demo at https://github.com/localstack/localstack-demo/blob/master/demo/web/index.html#L24

**Comment by stevendwood** [comment]
I try to do a GET on my API Gateway endpoint using the URL pattern discussed here since local DNS issues prevent the default URL from working http://localhost:4566/restapis/0v1p6q6/local/_user_request_/my/path1 

but this didn't work at all for me - encountering the problem described here which lead me to this page.

If i follow the advice from @dhallam above, it improves I guess, but it then fails with the message:

Unknown Operation: unable to find operation for request to service apigateway. The exception is raised in the localstack source code [here](https://github.com/localstack/localstack/blob/2977f13b8028bcc8b393e9797a2ac37f78e9b590/localstack/aws/protocol/parser.py#LL559C4-L559C4)

**Comment by stevendwood** [comment]
Re above I actually had a typo in the URL and was trying to hit _user_request instead of _user_request_

**Comment by derekvantonder3DD** [comment]
Thank you, @dhallam your advice worked well for me.
