### ISSUE TITLE
bug: Cant start exec sync state machine express

### ISSUE THREAD

**Issue by ewertonviana1** [localstack/localstack#5422]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi, I'm creating a state machine express in the cli, but i canot run sync.

I get:
```Could not connect to the endpoint URL: "http://sync-localhost:4566/"```
        
      
        
        

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    ```docker run localstack/localstack```

## Create State Machine Express
    ```awslocal stepfunctions create-state-machine --name test-express --definition '{"Comment": "A Hello World example of the Amazon States Language using Pass states", "StartAt": "Hello", "States": { "Hello": { "Type": "Pass", "Result": "Hello", "Next": "World" },"World": {"Type": "Pass","Result": "World","End": true}}}' --type EXPRESS --role-arn YOU ROLE```
    
 ## Run State Machine Express  
   ``` awslocal stepfunctions  start-sync-execution --state-machine-arn arn:aws:states:us-east-1:000000000000:stateMachine:test-express```
    
 ## I Get
 ```Could not connect to the endpoint URL: "http://sync-localhost:4566/"```
 

### Environment

```markdown
- OS: 
- LocalStack:
```

**Comment by dominikschubert** [comment]
Closing in favor of the existing issue at  #5258
