### ISSUE TITLE
Problem while trying to install localstack on Windows 10 having Python 3.10.2

### ISSUE THREAD

**Issue by vinayr-sharma** [localstack/localstack#5429]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

While I am trying to install local on my windows machine (Windows 10, Python 3.10.2)

Getting following error
 File "C:\Users\Vinayr.sharma\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 2184: character maps to <undefined>
      [end of output]

Do I need to install any other packages etc?

### How are you starting LocalStack?

Custom (please describe below)

### Steps To Reproduce

Run command "pip install localstack"

### Environment

```markdown
- OS: Windows 10 Enterprise
- LocalStack:
```

**Comment by a-kalatsei-godeltech** [comment]
Today I faced with the same issue. I downgraded python version to 3.9.10 and managed to install localstack.

**Comment by silv-io** [comment]
Hi @a-kalatsei-godeltech, @vinayr-sharma! Does 3.10 work for you on the latest version (`1.0.3`)? Since the creation of this issue and now [we added Python 3.10 support](https://github.com/localstack/localstack/commit/a1517d8c396b81e96ea356255cb6dc401c1791a4).
