### ISSUE TITLE
Inject latency for SSM parameter store?

### ISSUE THREAD

**Issue by minghsieh-prenetics** [localstack/localstack#543]
Hi,

Could anybody provide any instruction to inject some latency for SSM parameter store?

The reason behind this is I have asked my local AWS solution architect (AWS employee) that if there's any request limit for SSM parameter store, since in case if we have AZ/regional failure then shifting containers to different AZ/region would incur a lot of SSM parameter calls at the same time. The AWS solution architect didn't directly respond with the exact number but suggested us to implement retry mechanism. Therefore, I need SSM getParameter, getParameters, and getParameterByPath having random high latency and/or failure. Just wonder how I should achieve this, or point me to some documentation to read on.

Have searched this topic but it does not come out any.

Thanks a lot.

**Comment by awerlang** [comment]
AWS SDK supports automatic retries with exponential backoff.

See: https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/SSM.html
Look for `maxRetries` and `retryDelayOptions `.
