### ISSUE TITLE
bug: DynamoDB: PartiQL statements not reflected in DynamoDB Stream

### ISSUE THREAD

**Issue by GalFuchs** [localstack/localstack#5445]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have a setup of a DynamoDB table with a DynamoDB Stream enabled and set to trigger a Lambda function.
When executing DynamoDB operations (adding items etc) through code, awslocal-cli or NoSQL Workbench everything works as expected - the changes are reflected in the Stream and the Lambda function is triggered.

When executing PartiQL statements using NoSQL Workbench, the change is applied to the table but nothing is added to the stream (noted by using awslocal dynamodbstreams get-records [...]) and the Lambda function is obviously not triggered.

### Expected Behavior

PartiQL operations should be reflected in DynamoDB streams.

### How are you starting LocalStack?

With a docker-compose file

#### docker-compose.yml

```
version: '3.0'
services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"
      - "4571:4571"
      - "4600:4600"
    environment:
      - SERVICES=s3,sqs,dynamodb,lambda,apigateway,iam,sns,route53,acm,kms,sts,ec2,cloudwatch
      - KINESIS_PROVIDER=kinesalite
      - DEFAULT_REGION=us-east-1
      - DEBUG=1
      - START_WEB=0
      - LS_LOG=error
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LOCALSTACK_API_KEY=$LOCALSTACK_API_KEY
      - LAMBDA_EXECUTOR=docker
      - LAMBDA_REMOTE_DOCKER=false
      - HOST_TMP_FOLDER=${PWD}/tmp/localstack
      - LAMBDA_DOCKER_NETWORK=local-dev_default
      - PERSIST_ALL=false
      - LAMBDA_CONTAINER_REGISTRY=mlupin/docker-lambda
    volumes:
      - ./logs/localstack:/var/log/localstack
      - ${PWD}/tmp/localstack:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)
[dynamodbstreamsbug.zip](https://github.com/localstack/localstack/files/8023932/dynamodbstreamsbug.zip)
    Download dynamodbstreamsbug.zip, unpack and do `terraform init` & `terraform apply` in the extracted directory.
    Once terraform is done running, do `awslocal dynamodb batch-write-item --request-items file://dynamodb-items.json` to populate the TEST table. Note that both TEST and TEST_2 get populated.
    Insert or edit an item in NoSQL Workbench (or however else you wish) - interface-based operation updates get added to the DynamoDB Stream, while PartiQL updates do not.

### Environment

```markdown
- OS: OSX 12.2
- LocalStack: latest
- Terraform: latest
```

**Comment by whummer** [comment]
Thanks for reporting @GalFuchs . This should be fixed in the meantime - can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists. Thanks for your help!

**Comment by steffyP** [comment]
Hi @GalFuchs,
thanks for reporting that issue! We have recently pushed some changes that should address your issue. 
Could you use `localstack/localstack:latest` and verify if your problem is solved?
