### ISSUE TITLE
feature request: Cloudwatch - evaluate alarm state when calling put_metric_data

### ISSUE THREAD

**Issue by steffyP** [localstack/localstack#5446]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Currently, Cloudwatch allows the creation of alarms. However, the alarm's state should also be evaluated/changed when data is collected. 
Consequently, any related actions (alarm, ok, insufficent_data) should be triggered.

There is a related issue #5150, where the alarm did not trigger defined actions when using `set-alarm-state` (which changes the state manually).

**Comment by grze888siu** [comment]
- [ ]
