### ISSUE TITLE
bug: SendMessageBatch does not maintain order of messages for FIFO queues

### ISSUE THREAD

**Issue by sam-goodwin** [localstack/localstack#5462]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have created a SQS Queue with the following configuration:

```js
{
  FifoQueue: "true",
  ContentBasedDeduplication: "true",
  DeduplicationScope: "messageGroup",
  FifoThroughputLimit: "perMessageGroupId",
}
```

I am then calling the `SendMessageBatch` API where some of the entries have the same `MessageGroupId`. Those messages are then received out of order when I later call `receiveMessage`.

### Expected Behavior

According to the docs, the order should be maintained when I call `receiveMessage`: https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_SendMessageBatch.html

> Delivers up to ten messages to the specified queue. This is a batch version of [SendMessage](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_SendMessage.html). For a FIFO queue, multiple messages within a single batch are enqueued in the order they are sent.

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

```
localstack start
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```ts
import { SQS } from "aws-sdk";

repro().catch((err) => {
  console.error(err);
  process.exit(1);
});

async function repro() {
  const sqs = new SQS({
    endpoint: "http://localhost:4566",
    credentials: {
      accessKeyId: "test",
      secretAccessKey: "test",
    },
    region: "us-east-1",
    sslEnabled: false,
    s3ForcePathStyle: true,
  });
  const response = await sqs
    .createQueue({
      QueueName: "test.fifo",
      Attributes: {
        FifoQueue: "true",
        ContentBasedDeduplication: "true",
        DeduplicationScope: "messageGroup",
        FifoThroughputLimit: "perMessageGroupId",
      },
    })
    .promise();
  const QueueUrl = response.QueueUrl!;

  const ids = Array.from(new Array(10)).map((_, i) => i);

  console.log(ids);

  await sqs
    .sendMessageBatch({
      QueueUrl,
      Entries: ids.map((i) => ({
        Id: i.toString(10),
        MessageBody: `${i}`,
        MessageDeduplicationId: `${i}`,
        MessageGroupId: "group",
      })),
    })
    .promise();

  const messages = await sqs
    .receiveMessage({
      QueueUrl,
      MaxNumberOfMessages: 10,
    })
    .promise();

  // should be: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
  // but is:    [0, 9, 1, 2, 3, 4, 5, 6, 7, 8]
  // why is `9` re-ordered?
  console.log(messages.Messages?.map((msg) => JSON.parse(msg.Body!)));

  await sqs
    .deleteQueue({
      QueueUrl,
    })
    .promise();
}
```

It outputs:
```
[
  0, 9, 1, 2, 3,
  4, 5, 6, 7, 8
]
```

Why is one item out of order?

### Environment

```markdown
- OS: MacOS 11.5.1, Apple M1
- LocalStack: 

LocalStack version: 0.14.0
LocalStack Docker container id: b42c8fe0a5f5
LocalStack build date: 2022-02-09
LocalStack build git hash: 8f644817
```
```


### Anything else?

_No response_

**Comment by thrau** [comment]
Hi @sam-goodwin, could you please check whether you are seeing the same behavior with localstack 1.0.4 ? looks like you're on a fairly old version.

**Comment by thrau** [comment]
closing the issue for now. please re-open and tag me if the issue persists with the latest version
