### ISSUE TITLE
bug:  Timestream write fails for record with 'MeasureValueType' 'VARCHAR'

### ISSUE THREAD

**Issue by kp2222** [localstack/localstack#5466]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Timestream write works fine when the "MeasureValueType" is a number but it fails to create the record when the type is "VARCHAR". Here is the exact error response I am getting

```
root@32804e5a0870:/opt/code/localstack# awslocal timestream-write write-records --database-name testDB --table-name testTable --records '[{"MeasureName":"cpu","MeasureValue":"test", "MeasureValueType": "VARCHAR", "TimeUnit":"SECONDS","Time":"1636986409"}]'

An error occurred (InternalServiceError) when calling the WriteRecords operation (reached max retries: 4): InternalServiceError: {'S': 'ERROR', 'V': 'ERROR', 'C': '22P02', 'M': 'invalid input syntax for type numeric: "test"', 'F': 'numeric.c', 'L': '5653', 'R': 'set_var_from_str'}
```

### Expected Behavior

TimestreamWrite should be able to insert records that contain a MeasureValue of type "VARCHAR"

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands 
    awslocal timestream-write create-database --database-name testDB
    awslocal timestream-write create-table --database-name testDB --table-name testTable
    awslocal timestream-write write-records --database-name testDB --table-name testTable --records '[{"MeasureName":"page-action","MeasureValue":"Page Viewed","TimeUnit":"SECONDS","Time":"1636986409"}]'

### Environment

```markdown
- OS: 
- LocalStack:
```

**Comment by whummer** [comment]
Thanks for reporting @kp2222, and apologies for the long delay. In the meantime we have pushed a couple of enhancements for data type handling in Timestream - can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists.. Thanks!

**Comment by whummer** [comment]
Closing as resolved - please re-open if the problem persists. Thanks
