### ISSUE TITLE
bug: IAM Roles are automatically deleted

### ISSUE THREAD

**Issue by chan-dev** [localstack/localstack#5481]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The roles are automatically deleted after creating roles via `aws` cli or the web dashboard 

### Expected Behavior

The roles should persist

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    sudo docker compose up

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    aws --endpoint-url=http://localhost:4566 iam create-role --role-name LambdaIAMRole --description "Lambda IAM Role" --assume-role-policy-document file://lambda-assume-role-policy.json

### Environment

```markdown
- OS: Xubuntu 20.04
- LocalStack: latest
```

**Comment by whummer** [comment]
Thanks for reporting @chan-dev . Can you please elaborate a bit more - when you say the roles are automatically deleted, is that after a restart of the LocalStack container, or during the same session (i.e., without container restart). Also, can you please share the exact command you're using to verify whether the created role is present (presumably `aws iam list-roles ...`).

Please note that by default the state in LocalStack is ephemeral (i.e., only kept in memory), so the behavior would be expected if a restart of the container is involved. Thanks

**Comment by chan-dev** [comment]
@whummer This is what i've observed so far. 

It seems like within the same session, when you click a certain `IAM role` in the web dashboard and an alert error occurs causing that certain role to be deleted.

![image](https://user-images.githubusercontent.com/46891115/154075390-7add9a57-f926-4d84-a7a4-f8db24e35a1f.png)

However, the role is persisted when you don't click it.

**Comment by dfangl** [comment]
Hi @chan-dev ! We quite revamped a lot of the UI and Localstack in the meantime.
I could not find any action in the new Web UI which would result in a deletion of the IAM role.
Can you double check if the issue is fixed for you? Thanks!
