### ISSUE TITLE
bug: serverless-localstack doesn't seem to work for serverless v3

### ISSUE THREAD

**Issue by MarioSimou** [localstack/localstack#5485]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I came across the serverless-localstack plugin and I tried to extend my serverless setup to utilise localstack during local development, but it seems that I get the below error when I enable `mountCode` for `lambda`. More specifically, the plugin fails when cloudformation attempts to deploy the services. If I remove the `mountCode` flag, the plugin is working as expected.

Here are the logs I get from the locastack container:
```
serverless-localstack-plugin-example-aws | 2022-02-14T22:26:11.793:INFO:localstack.utils.common: Updating permissions as file is currently not readable: /home/msimou/Desktop/projects/others/serverless-localstack-plugin-example/.js
serverless-localstack-plugin-example-aws | 2022-02-14T22:26:13.215:INFO:localstack.utils.common: Updating permissions as file is currently not readable: /home/msimou/Desktop/projects/others/serverless-localstack-plugin-example/.js
serverless-localstack-plugin-example-aws | 2022-02-14T22:26:15.821:INFO:localstack.utils.common: Updating permissions as file is currently not readable: /home/msimou/Desktop/projects/others/serverless-localstack-plugin-example/.js
serverless-localstack-plugin-example-aws | 2022-02-14T22:26:21.189:INFO:localstack.utils.common: Updating permissions as file is currently not readable: /home/msimou/Desktop/projects/others/serverless-localstack-plugin-example/.js
serverless-localstack-plugin-example-aws | 2022-02-14T22:26:21.195:WARNING:localstack.utils.cloudformation.template_deployer: Error calling <bound method ClientCreator._create_api_method.<locals>._api_call of <botocore.client.Lambda object at 0x7f604e1d6f40>> with params: {'Code': {'S3Bucket': '__local__', 'S3Key': '/home/msimou/Desktop/projects/others/serverless-localstack-plugin-example'}, 'FunctionName': 'serverless-localstack-plugin-example-local-first', 'Handler': '.webpack/service/first.hello', 'MemorySize': 128, 'Runtime': 'nodejs14.x', 'Role': 'arn:aws:iam::000000000000:role/serverless-localstack-plugin-example-local-us-east-1-lambdaRole', 'Timeout': 6} for resource: {'Type': 'AWS::Lambda::Function', 'DependsOn': ['FirstLogGroup'], 'LogicalResourceId': 'FirstLambdaFunction', 'Properties': {'Code': {'S3Bucket': '__local__', 'S3Key': '/home/msimou/Desktop/projects/others/serverless-localstack-plugin-example'}, 'Handler': '.webpack/service/first.hello', 'Runtime': 'nodejs14.x', 'FunctionName': 'serverless-localstack-plugin-example-local-first', 'MemorySize': 128, 'Timeout': 6, 'Role': 'arn:aws:iam::000000000000:role/serverless-localstack-plugin-example-local-us-east-1-lambdaRole'}, '_state_': {}}
```

Here are the logs I get while deploy my changes to localstack
```
Using custom endpoint for CloudFormation: http://localhost:4566
Executing created change set
Using custom endpoint for CloudFormation: http://localhost:4566
Using custom endpoint for CloudFormation: http://localhost:4566
  UPDATE_IN_PROGRESS - AWS::CloudFormation::Stack - ServerlessDeploymentBucketPolicy
  CREATE_COMPLETE - AWS::CloudFormation::Stack - FirstLogGroup
  CREATE_COMPLETE - AWS::CloudFormation::Stack - IamRoleLambdaExecution
Using custom endpoint for CloudFormation: http://localhost:4566
Using custom endpoint for CloudFormation: http://localhost:4566
  CREATE_FAILED - AWS::CloudFormation::Stack - serverless-localstack-plugin-example-local
Using custom endpoint for CloudFormation: http://localhost:4566
Using custom endpoint for CloudFormation: http://localhost:4566
Using custom endpoint for CloudFormation: http://localhost:4566
``` 

I have also created [this](https://github.com/MarioSimou/serverless-localstack-plugin-example) repository to test it locally.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker-compose up

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    npm i && npm run start:dev

### Environment

```markdown
- OS:Debian 10 (buster)
- LocalStack: 0.14.0
```

### Anything else?
I have also created [this](https://github.com/MarioSimou/serverless-localstack-plugin-example) repository to test it locally.

**Comment by bentsku** [comment]
Hello @MarioSimou and sorry for the delay in responding.

Thanks for the sample to reproduce the issue. I've just opened a PR on your repo with an updated sample, which works locally for me. Some configuration variables changed, and the issue might have come from this configuration of your volumes:
```yaml
volumes:
      - type: bind
        source: $PWD
        target: /tmp/localstack/data/lambda
```
The container needs to access the exact same path as your local path where the lambda code resides.
It is now replaced with:
```yaml
volumes:
    - "$PWD:$PWD"
```
Which will create the right path in the container, so it can access the path given by the Serverless plugin. 

You can read more about the local count mounting with Serverless here:
https://docs.localstack.cloud/user-guide/integrations/serverless-framework/#local-code-mounting-for-lambda-functions
About the code mounting in general:
https://docs.localstack.cloud/user-guide/tools/lambda-tools/hot-swapping/

Hope that fixes your issue!

**Comment by MarioSimou** [comment]
Thanks for the work @bentsku. I just tested the changes locally and work fine

**Comment by bentsku** [comment]
Awesome! I'm glad it's working. Don't hesitate to open a new issue if you encounter another problem, I'll close this one. Thanks!
