### ISSUE TITLE
question: How to use INIT_SCRIPTS_PATH with localstack start?

### ISSUE THREAD

**Issue by apiel** [localstack/localstack#5486]
### Is there an existing issue for this?

- [X] I have searched the existing issues and read the documentation

### Question

Base on the documentation https://docs.localstack.cloud/localstack/configuration/#core , I should be able to set INIT_SCRIPTS_PATH to set my setup script.

I created a folder localstack containing an sqs.sh file:
```bash
#!/usr/bin/env bash

awslocal sqs create-queue --queue-name my-queue
```

And then start localstack with `INIT_SCRIPTS_PATH=./localstack localstack start` (using python installation). But this is not working. However, if I am using docker-compose, it is working properly. Is this feature not working with the python installation?

**Comment by whummer** [comment]
Hi @apiel , thanks for reporting. This configuration is currently not yet fully integrated with the `localstack` CLI - however, you could use the generic `DOCKER_FLAGS` config to add a volume mount to the `docker run ...` command:

```
DOCKER_FLAGS="-v ./localstack:/docker-entrypoint-initaws.d" localstack start
```

Hope that helps - please keep us posted how it goes..

**Comment by apiel** [comment]
Thanks, it is working but only with absolute path.
