### ISSUE TITLE
feature request: Publish Step Function EventBridge events on execution status changes

### ISSUE THREAD

**Issue by pushred** [localstack/localstack#5492]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Step Functions includes an [EventBridge Events](https://docs.aws.amazon.com/step-functions/latest/dg/cw-events.html) feature where certain events can be emitted to the default event bus automatically when execution status changes. From what I can tell based on the following, this functionality does not exist in LocalStack.

- [Step Function-related events currently published by LocalStack](https://github.com/localstack/localstack/blob/57eb03e760f7bbafb1ba22be24cc5c02138b4b2d/localstack/services/stepfunctions/stepfunctions_listener.py)

- [LocalStack Step Function integration tests](https://github.com/localstack/localstack/blob/4aa29eea183cd85e24582e556f712dfc95353684/tests/integration/test_stepfunctions.py)

There are [5 different events](https://docs.aws.amazon.com/step-functions/latest/dg/cw-events.html#cw-events-events) that are documented for each status that is also available from the DescribeExecution API.

I see that the `events` endpoint is configured in the [usage of Step Functions Local](https://github.com/localstack/localstack/blob/57eb03e760f7bbafb1ba22be24cc5c02138b4b2d/localstack/services/stepfunctions/stepfunctions_starter.py#L45) however if I configure SQS as a target like so, I do not receive any events after executing a workflow. This works in the AWS environment given this EventBridge rule:

```sh
aws --endpoint-url=http://localhost:4566 events put-rule \
  --name local-execution-events \
  --event-pattern '{
    "source": ["aws.states"],
    "detail-type": ["Step Functions Execution Status Change"],
    "detail": {
      "stateMachineArn": [
        "arn:aws:states:us-east-1:000000000000:stateMachine:example-workflow"
      ]
    }
  }'
```

### 🧑‍💻 Implementation

I'm not sure how [stepfunctions_listener](https://github.com/localstack/localstack/blob/57eb03e760f7bbafb1ba22be24cc5c02138b4b2d/localstack/services/stepfunctions/stepfunctions_listener.py) fits into the bigger picture exactly but it appears that it at least stubs part of what is needed.

Understanding that LocalStack wraps [Step Functions Local](https://docs.aws.amazon.com/step-functions/latest/dg/sfn-local.html), it may not be possible to replicate each event unless DescribeExecution has been implemented by it. But it should be possible to publish events for at least the following states:

|State|Trigger|
|-----|-------|
|`STARTED`|Following a [successful start](https://github.com/localstack/localstack/blob/57eb03e760f7bbafb1ba22be24cc5c02138b4b2d/localstack/services/stepfunctions/stepfunctions_starter.py#L66-L75)|
|`SUCCEEDED`|Based on output in [check_stepfunctions](https://github.com/localstack/localstack/blob/57eb03e760f7bbafb1ba22be24cc5c02138b4b2d/localstack/services/stepfunctions/stepfunctions_starter.py#L78-L94)|
|`FAILED`|Similarly based on above output|

I'm not sure that `ABORTED` applies here. `TIMEDOUT` may also not be possible.

**Comment by isaac-j-miller** [comment]
Any update on this?

**Comment by dominikschubert** [comment]
Hi @isaac-j-miller . We're currently in the progress of rewriting the service with our own implementation which will allow us to customize it more to our liking with things like the proposed feature from this thread.

I think it would be quite interesting to prioritize this as one of our first additional features. I can't give a concrete ETA  but feel free to ping us again if there's been no update in the next 4 weeks on this issue.

Would you be willing to test an initial implementation to provide us with some early feedback when its available?

**Comment by isaac-j-miller** [comment]
That sounds great! I’d definitely be willing to test it out and provide
feedback.

**Comment by MEPalma** [comment]
Hello @isaac-j-miller @pushred,

Continuing from @dominikschubert's update, we are pleased to announce that our new service implementation now includes support for publishing Step Function events on EventBridge.

We value your input and would greatly appreciate any early feedback you can provide on this new implementation, particularly concerning the feature request mentioned in this issue. At the moment, the optimized service integrations are limited to SQS, StepFunctions, DynamoDB, and Lambda. Aws-sdk is otherwise supported.

To enable the new service backend, simply set `PROVIDER_OVERRIDE_STEPFUNCTIONS=v2`.

Thank you!

**Comment by pushred** [comment]
Thanks! I'm sure this will be valuable for someone out there 😀 Unfortunately for us we had to abandon LocalStack more broadly in favor of real AWS dev environments. Emulation wasn't sufficient for our needs.
