### ISSUE TITLE
Guidance on how to proceed with non uniform port ranges

### ISSUE THREAD

**Issue by brucekaufman** [localstack/localstack#5494]
### Is there an existing issue for this?

- [X] I have searched the existing issues and read the documentation

### Question

When localstack switched to using the docker python SDK instead of the docker CLI, it broke functionality around non-uniform port ranges.  In https://github.com/localstack/localstack/issues/5465 I was able to fix the issue from the localstack side, but this exposed an undocumented difference between the CLI and the SDK in terms of how non-uniform port ranges are handled.  In the CLI, docker will map the host port to a randomly selected open port within the range, while the SDK will map the host port to ALL ports in the range.  I've dug around in the source code of the docker python SDK and the the capability of supporting the CLI based functionality does not appear to exist, although perhaps I have missed something.

**Background**
A non uniform port range is one where a range of host ports can be mapped to a single container port EG `-p 9230-9231:9230`.  The biggest value add for our use case is to be able to attach a debugger to multiple nodejs lambda containers simultaneously.  Being able to debug lambda containers in localstack is one of the single most important reasons we adopted it as part of our developer tooling.  This regression prevents our ability to upgrade localstack and putting our future use of the tool at risk.

I've opened this question to try to solicit input from the localstack core developers around the best approach here.  I was hoping that there might be some way to handle this on the localstack side as I have not gotten any traction in the docker SDK github.

**Idea 1: emulate docker CLI behavior in localstack**
When a non-uniform port range is defined, attempt to map to a single host port in the range.  If docker throws, trap the exception, and then re-attempt on a different port in the range.  While not being ideal, this would be a small fix that I might be able to implement in short order. 

**Idea 2: bespoke nodejs debug handling**
In this approach we would eliminate the need for a non-uniform port range to solve the problem at hand, specifically to dynamically select a host port at the time the lambda docker container is spun up, and passing that port to the `--inspect` or `--inspect-brk` command line inputs to node.  To do this localstack would have to know which host ports are available within the range, which i don't know enough about the internals of localstack to know how complex this would be.

```
localstack  | Traceback (most recent call last):
localstack  |   File "/opt/code/localstack/localstack/utils/docker_utils.py", line 1316, in start_container
localstack  |     container.start()
localstack  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/docker/models/containers.py", line 404, in start
localstack  |     return self.client.api.start(self.id, **kwargs)
localstack  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/docker/utils/decorators.py", line 19, in wrapped
localstack  |     return f(self, resource_id, *args, **kwargs)
localstack  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/docker/api/container.py", line 1111, in start
localstack  |     self._raise_for_status(res)
localstack  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/docker/api/client.py", line 270, in _raise_for_status
localstack  |     raise create_api_error_from_http_exception(e)
localstack  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
localstack  |     raise cls(e, response=response, explanation=explanation)
localstack  | docker.errors.APIError: 500 Server Error for http+docker://localhost/v1.41/containers/0bbb17874a9517cbe55dad13c52727cb65179911ac084701050c7599ff591b8b/start: Internal Server Error ("driver failed programming external connectivity on endpoint pensive_spence (4b69f3114ebdb00cceb81cd46b95e0c8e7fec97561a56dd7610f20985d97837e): Bind for 0.0.0.0:9231 failed: port is already allocated")
```

**Comment by whummer** [comment]
Thanks for reporting @brucekaufman . Can you please share a few more details to help us replicate your use case end-to-end.

You've mentioned this:
>  The biggest value add for our use case is to be able to attach a debugger to multiple nodejs lambda containers simultaneously.

Seems your primary use case is to have non-uniform port ranges for the Lambda containers, i.e., specified via the `LAMBDA_DOCKER_FLAGS` config option - is that correct? Do you also have the use case to expose non-uniform port ranges for the LocalStack Docker container itself, or is it primarily for the Lambda Docker containers that get created as part of a Lambda invocation? 

If you can share some more details, or ideally a small reproducible example (e.g., shell script with some `awslocal` commands), we'd be happy to take a closer look and come up with a solution.. Thanks!

**Comment by brucekaufman** [comment]
Hi @whummer - to see a working example of this in action you can view the prototype I've previously shared which uses localstack + serverless for a nodejs development environment:

https://github.com/himarley/microservice-prototype

Please see the section on 'debug'.  The setup as defined works with the pinned version of localstack but will not work for anything newer (where the docker CLI was replaced with the docker python SDK).  The one which will 100% reproduce the error traceback i put in my orginal comment is:

```
sls invoke -f direct
```

this will invoke a lambda function which attempts to invoke a second lambda.  Since the debug port is not available the second lambda will fail to run.  If you follow the setup instructions in that repo and then run the command above you'll be able to see the error in the main localstack container.


```
Seems your primary use case is to have non-uniform port ranges for the Lambda containers, i.e., specified via the LAMBDA_DOCKER_FLAGS config option - is that correct? Do you also have the use case to expose non-uniform port ranges for the LocalStack Docker container itself, or is it primarily for the Lambda Docker containers that get created as part of a Lambda invocation?
```

yes this is 100% correct - see the configuration in the example repo.  We presently don't have a need to expose any ports in the main localstack container, after all we're trying to debug our lambda service code, not the localstack code :).
