### ISSUE TITLE
bug: Error deploying CDK stack "ApiGatewayToKinesisStreams" to localstack

### ISSUE THREAD

**Issue by eugene-coast** [localstack/localstack#5500]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am trying to deploy a very small CDK stack, containing ApiGatewayToKinesesStreams [solution](https://github.com/awslabs/aws-solutions-constructs/blob/main/source/patterns/%40aws-solutions-constructs/aws-apigateway-kinesisstreams/lib/index.ts) using "localstack deploy". The deployment fails with:
```
 ❌  cdk--dev--source-gateway-kinesis failed: Error: The stack named cdk--dev--source-gateway-kinesis failed to deploy: CREATE_FAILED (Deployment failed)
    at Object.waitForStackDeploy (/Users/eprystupa/.config/yarn/global/node_modules/aws-cdk/lib/api/util/cloudformation.ts:309:11)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at prepareAndExecuteChangeSet (/Users/eprystupa/.config/yarn/global/node_modules/aws-cdk/lib/api/deploy-stack.ts:355:26)
    at CdkToolkit.deploy (/Users/eprystupa/.config/yarn/global/node_modules/aws-cdk/lib/cdk-toolkit.ts:201:24)
    at initCommandLine (/Users/eprystupa/.config/yarn/global/node_modules/aws-cdk/bin/cdk.ts:281:9)
The stack named cdk--dev--source-gateway-kinesis failed to deploy: CREATE_FAILED (Deployment failed)
```

I also do see the following error in localstack logs:
```
2022-02-16T19:42:46.508:WARNING:localstack.utils.cloudformation.template_deployer: Unexpected error retrieving details for resource type AWS::Kinesis::Stream: Exception: 'Name' - {'RetentionPeriodHours': 24, 'ShardCount': 1, 'StreamEncryption': {'EncryptionType': 'KMS', 'KeyId': 'alias/aws/kinesis'}, 'StreamModeDetails': {'StreamMode': 'PROVISIONED'}} - status: None
```

The deployment to AWS using "cdk deploy" works just fine.

### Expected Behavior

I expect the deployment to localstack to succeed, just like it does when deploying to AWS.

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

```
export LOCALSTACK_API_KEY=<my-api-key>
localstack start
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```typescript
import {Stack, StackProps} from 'aws-cdk-lib';
import {Construct} from 'constructs';
import {ApiGatewayToKinesisStreams} from '@aws-solutions-constructs/aws-apigateway-kinesisstreams';

class SourceGatewayKinesisStack extends Stack {
    constructor(scope: Construct, id: string, props?: StackProps) {
        super(scope, id, props);
        
        new ApiGatewayToKinesisStreams(this, `cdk--dev--source`, {});
    }
}

export {SourceGatewayKinesisStack};
```

### Environment

```markdown
- OS: MacOS Monterey 12.1
- LocalStack: 0.14.0
```

**Comment by pinzon** [comment]
Hi @eugene-coast thank you for reporting this issue. Right now I'm trying to triage this issue but I'm stuck with an error due to Construct class not matching for ApiGatewayToKinesisStreams.

```{
	"resource": "/home/cristopher/Proyectos/whummer/localstack-reproducers/5500/test/lib/test-stack.ts",
	"owner": "typescript",
	"code": "2345",
	"severity": 8,
	"message": "Argument of type 'import(\"/home/cristopher/Proyectos/whummer/localstack-reproducers/5500/test/node_modules/constructs/lib/construct\").Construct' is not assignable to parameter of type 'import(\"/home/cristopher/Proyectos/whummer/localstack-reproducers/5500/test/node_modules/@aws-cdk/core/lib/construct-compat\").Construct'.\n  Type 'Construct' is missing the following properties from type 'Construct': onValidate, onPrepare, onSynthesize, validate, and 2 more.",
	"source": "ts",
	"startLineNumber": 9,
	"startColumn": 36,
	"endLineNumber": 9,
	"endColumn": 41
}```

could you provide me with the package.json of your project so I can see the correct version of the libs?

**Comment by eugene-coast** [comment]
Sure, here is the package.json content:

{
  "name": "infra",
  "version": "0.1.0",
  "bin": {
    "infra": "bin/infra.js"
  },
  "scripts": {
    "build": "tsc",
    "watch": "tsc -w",
    "test": "jest",
    "cdk": "cdk"
  },
  "devDependencies": {
    ***@***.***/jest": "^27.4.1",
    ***@***.***/node": "17.0.21",
    "aws-cdk": "2.15.0",
    "jest": "^27.5.1",
    "ts-jest": "^27.1.3",
    "ts-node": "^9.1.1",
    "typescript": "~3.9.10"
  },
  "dependencies": {
    ***@***.***/aws-apigateway-kinesisstreams": "^2.3.0",
    ***@***.***/aws-kinesisstreams-lambda": "^2.3.0",
    ***@***.***/aws-sns-sqs": "^2.3.0",
    ***@***.***/aws-sqs-lambda": "^2.3.0",
    "aws-cdk-lib": "2.15.0",
    "constructs": "^10.0.75",
    "source-map-support": "^0.5.21"
  }
}

Eugene Prystupa

Engineering

-

***@***.***

coastpay.com
