### ISSUE TITLE
Unable to use BIN function in Timestream local database

### ISSUE THREAD

**Issue by joshdura** [localstack/localstack#5501]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When running the following query against a local timestream database, we aren't able to get the BIN function to be recognized.

Query
```
SELECT "time",
       BIN("time", 5m) AS "time_bin_5m"
  FROM "localdb"."localtable";
```

Error
```
       BIN("time"...
       ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
```

### Expected Behavior

Should be able to use the BIN function

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

        localstack:
          image: localstack/localstack:latest
          container_name: localstack
          ports:
              - "53:53" # only required for Pro
              - "53:53/udp" # only required for Pro
              - "443:443" # only required for Pro
              - "4510-4530:4510-4530" # only required for Pro
              - "4563-4599:4563-4599"
              - "8055:8080"
          environment:
              - SERVICES=s3,timestream
              - DEBUG=1
              - DATA_DIR=/tmp/localstack/data
              - LOCALSTACK_API_KEY=<redacted>
              - AWS_ACCESS_KEY_ID=local
              - AWS_SECRET_ACCESS_KEY=local
              - AWS_DEFAULT_REGION=us-east-1
          volumes:
              - ./stubs/s3:/tmp/localstack
              - "${TMPDIR:-/tmp}/localstack:/tmp/localstack"
              - "/var/run/docker.sock:/var/run/docker.sock"
              - "./localstack/timestream.sh:/docker-entrypoint-initaws.d/init-timestream.sh"

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal timestream-query query \
      --query-string "SELECT "time",
             BIN("time", 5m) AS "time_bin_5m"
        FROM "localdb"."localtable""

### Environment

```markdown
- OS: Ubuntu
- LocalStack: latest
```

**Comment by whummer** [comment]
Hi @joshdura , thanks for reporting. This should be fixed in the meantime, available in the `latest` Docker image (as also discussed via Slack). Please let us know if you're facing any other issues. Thanks!
