### ISSUE TITLE
feature request: provide replacement for "check_service()" function to use in python code as before 0.14.0 release

### ISSUE THREAD

**Issue by aspacca** [localstack/localstack#5506]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Our integration tests start a localstack container by code in the test and use the "check_service()" (`check_kinesis`, `check_sqs` etc) functions to wait for the various services to be up in the setup of the test before running the actual test.

We then use the localstack package in the tests (`localstack.utils.aws.aws_stack`) to interact with localstack to provision the  integrations we need for the test.

The docker container esposes random ports, and we were able to rely on setting proper `TEST_%SERVICE%_URL` environment variables and mocking `PORT_%SERVICE%_BACKEND` values in the tests. In order to do so we relied on some of the `localstack.services` code.

(see https://github.com/elastic/elastic-serverless-forwarder/blob/main/tests/handlers/aws/test_handler.py#L588-L602 for an example)

We tried today to update to v0.14.0 for the part regarding the package dependencies in the tests (the docker image was always `latest`) and we found out most of the check function we used were refactored in a manner they cannot be used as external helpers.

see the difference between these two versions:
https://github.com/localstack/localstack/blob/v0.12.19/localstack/services/kinesis/kinesis_starter.py#L167-L183
https://github.com/localstack/localstack/blob/v0.14.0/localstack/services/kinesis/kinesis_starter.py#L47-L63

We would like to have a replacement with behaviour similar to the previous one, or any other alternative for the specific test setup we have (mix of local stack docker bootstrap and integrations provision directly in the python test code)

Thanks

### 🧑‍💻 Implementation

The minimal implementation would be to just "port" the previous implementation in `testutil`

**Comment by aspacca** [comment]
hi @whummer , thanks for the prompt feedback and the example for the readiness probe

> Also, please note that we have recently introduced a new mechanism for lazily loading the services, so technically the infra checks should no longer be required (as soon as the edge proxy on port 4566 becomes available).

I have to understand when exactly port 4566, exposed as random port on the host from the docker container, becomes available. At the moment I wait for the random port to be exposed in the container object I run with the docker package, but I'm not sure this happens after it becomes available on localstack in the container. I will comment with my findings


I need also to mock the boto clients inside the code I test, currently doing this:
https://github.com/elastic/elastic-serverless-forwarder/blob/main/tests/handlers/aws/test_handler.py#L753-L754
```
        with mock.patch("storage.S3Storage._s3_client", aws_stack.connect_to_service("s3")):
            with mock.patch("handlers.aws.sqs_trigger.get_sqs_client", lambda: aws_stack.connect_to_service("sqs")):
```

If I got it right I should add mocking `localstack.config.EDGE_PORT`:
````
with mock.patch("localstack.config.EDGE_PORT", self._LOCALSTACK_HOST_PORT):
        with mock.patch("storage.S3Storage._s3_client", aws_stack.connect_to_service("s3")):
            with mock.patch("handlers.aws.sqs_trigger.get_sqs_client", lambda: aws_stack.connect_to_service("sqs")):
```

is this correct?

**Comment by whummer** [comment]
@aspacca Yes, this approach with mocking `localstack.config.EDGE_PORT` for the boto3 client creation should (hopefully) work - looks good to me! 👍

**Comment by aspacca** [comment]
@whummer it seems setting `SERVICE_BACKEND` env variables, and using the `aws_stack.connect_to_service` is enough

https://github.com/elastic/elastic-serverless-forwarder/pull/80/files#diff-871fed4f87f348f6fb2a26f5f1996037296b8e6da76cc5e2620da48c8334bed4R593-R604
