### ISSUE TITLE
bug: API Gateway to S3, GET not yet implemented

### ISSUE THREAD

**Issue by druelens** [localstack/localstack#5508]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When creating an API Gateway with an integration of type AWS to S3, the uri to get objects from an S3 bucket is not working, returning:

`{
    "status": 400,
    "body": "{\"Type\": \"User\", \"message\": \"Error invoking integration for API Gateway ID '3en931aay2': API Gateway AWS integration action URI \\\"arn:aws:apigateway:us-east-1:s3:action/GetObject&Bucket=saxpress-drawio=Key={item}\\\", method \\\"GET\\\" not yet implemented\", \"__type\": \"InvalidRequest\"}",
    "headers": {
        "x-amzn-errortype": "InvalidRequest",
        "Content-Type": "text/html; charset=utf-8",
        "Content-Length": "280"
    }
}`

### Expected Behavior

Retrieve S3 object.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

```
localstack:
    image: localstack/localstack:latest
    hostname: localstack
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - HOSTNAME_EXTERNAL=localstack
      - SERICES=s3,lambda,apigateway,apigatewayv2
      - DEBUG=1
    ports:
      - '4566-4583:4566-4583'
      - '8055:8080'
    volumes:
      - 'saxpress-localstack-data:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './.localstack:/docker-entrypoint-initaws.d'
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```
awslocal apigateway create-rest-api --region us-east-1 --name ${API_NAME} --endpoint-url=http://localhost:4566

awslocal apigateway create-resource \
  --region ${REGION} \
  --rest-api-id ${API_ID} \
  --parent-id ${PARENT_RESOURCE_ID} \
  --path-part "{proxy+}"

awslocal apigateway put-method \
  --region ${REGION} \
  --resource-id ${RESOURCE_ID} \
  --rest-api-id ${API_ID} \
  --http-method "GET" \
  --authorization-type "NONE" \
  --request-parameters "method.request.path.proxy=true"

awslocal apigateway put-integration \
  --region ${REGION} \
  --resource-id ${RESOURCE_ID} \
  --rest-api-id ${API_ID} \
  --type "AWS" \
  --http-method "GET" \
  --uri "arn:aws:apigateway:${REGION}:s3:action/GetObject&Bucket=${BUCKET_NAME}=Key={item}" \
  --credentials "${ROLE_ARN}" \
  --integration-http-method "GET" \
  --request-parameters "integration.request.path.item=method.request.queryString.proxy,integration.request.path.object=context.requestId"

awslocal apigateway put-method-response \
  --region ${REGION} \
  --resource-id ${RESOURCE_ID} \
  --rest-api-id ${API_ID} \
  --status-code "200" \
  --http-method "GET" \
  --response-parameters "method.response.header.Content-Type=true" \
  --response-models "application/json=Empty"

awslocal apigateway put-integration-response \
  --region ${REGION} \
  --resource-id ${RESOURCE_ID} \
  --rest-api-id ${API_ID} \
  --status-code "200" \
  --http-method "GET" \
  --response-parameters "method.response.header.Content-Type=integration.response.header.Content-Type"
```

Testing the method:
```
root@localstack:/opt/code/localstack# awslocal apigateway test-invoke-method --rest-api-id ${API_ID} --resource-id ${RESOURCE_ID} --http-method GET --path-with-query-string index.html
{
    "status": 400,
    "body": "{\"Type\": \"User\", \"message\": \"Error invoking integration for API Gateway ID '3en931aay2': API Gateway AWS integration action URI \\\"arn:aws:apigateway:us-east-1:s3:action/GetObject&Bucket=saxpress-drawio=Key={item}\\\", method \\\"GET\\\" not yet implemented\", \"__type\": \"InvalidRequest\"}",
    "headers": {
        "x-amzn-errortype": "InvalidRequest",
        "Content-Type": "text/html; charset=utf-8",
        "Content-Length": "280"
    }
}
```

### Environment

```markdown
- OS: macOS Big Sur
- LocalStack: latest
```

**Comment by druelens** [comment]
Great, thanks @calvernaz !

**Comment by druelens** [comment]
Hi @calvernaz , thanks a lot for fixing this! Can confirm the GET request seems to be working now.
I do however still have another issue, that the {item} path variable does not seem to be passed from the method request to the integration request. I have these exact request parameters in a terraform config which works, so maybe I'm missing something in the localstack config or it's not implemented.

The intention is to use the greedy {proxy+} path variable as the key to retrieve from the bucket.

Let me know if you'd like me to submit another issue for this.

**Comment by calvernaz** [comment]
Hi @druelens thanks for confirming! You are right and we know exactly what's the issue, but it's a limitation in the current implementation. 

I have this [example](https://github.com/localstack/localstack-terraform-samples/blob/master/apigateway-s3-deploy/main.tf ) how to get "almost" the same behaviour. Unfortunately, at the moment we can't map `querystring` to `path` (locations), and different parameter names.

But, I think you can achieve what you intended using the example.
