### ISSUE TITLE
Firehose to Elastisearch stream can't be created

### ISSUE THREAD

**Issue by sumitsarkar** [localstack/localstack#552]
I am running localstack on Docker and using CLI scripts to start up a firehose to s3 and elasticsearch stream. The S3 destination gets created and works like a charm. 

However, the elasticsearch destination is never created and ignored completely. There were no errors coming up either.

The elasticsearch configuration:
 ``` 
 {
  "RoleARN": "arn:aws:iam::000000000000:role/firehose",
  "DomainARN": "arn:aws:es:us-east-1:000000000000:domain/audit-logs-bkbn-default",
  "IndexName": "audit-log-bkbn",
  "TypeName": "bkbn",
  "IndexRotationPeriod": "OneMonth",
  "S3BackupMode": "AllDocuments",
  "S3Configuration": {
    "RoleARN": "arn:aws:iam::000000000000:role/firehose",
    "BucketARN": "arn:aws:s3:::efk-bucket-backbone-default",
    "BufferingHints": {
      "SizeInMBs": 10,
      "IntervalInSeconds": 400
    },
    "CompressionFormat": "UNCOMPRESSED"
  }
}
```

The command run for creating firehose stream:

```
aws --endpoint-url=${URL}:${FIREHOSE_PORT} firehose create-delivery-stream \
      --delivery-stream-name audit-stream-backbone-default \
      --elasticsearch-destination-configuration file://./es.json
```

The end result:

```
$ aws --endpoint-url=http://192.168.99.100:4573 firehose describe-delivery-stream --delivery-stream-name audit-stream-backbone-default
{
    "DeliveryStreamDescription": {
        "DeliveryStreamName": "audit-stream-backbone-default",
        "DeliveryStreamARN": "arn:aws:firehose:us-east-1:000000000000:deliverystream/audit-stream-backbone-default",
        "DeliveryStreamStatus": "ACTIVE",
        "VersionId": "1",
        "CreateTimestamp": 1515757815.738184,
        "Destinations": [],
        "HasMoreDestinations": false
    }
}
```

**Comment by sumitsarkar** [comment]
The feature is yet to be implemented. Closing the ticket.

**Comment by rayjlinden** [comment]
Bummer.  Is anyone working on it?

**Comment by whummer** [comment]
Initial implementation has been added in #550 . Can you elaborate @rayjlinden , which issue are you experiencing in particular regarding the Firehose -> Elastisearch integration?

**Comment by rayjlinden** [comment]
I ended up going another way (using the basic lambda integration with kinesis.) . Firehose turned out to have some limitations that were not going to work for us.  (I.e. you can not delete or update data.)
