### ISSUE TITLE
bug: cannot add tags to db parameter group on create via terraform

### ISSUE THREAD

**Issue by JSanchezIO** [localstack/localstack#5521]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm creating an RDS cluster using [this module](https://registry.terraform.io/modules/terraform-aws-modules/rds-aurora/aws/latest) and it's failing when attempting to tag the DB Parameter Group right after it's created. This module works fine against `localstack/localstack:0.14` but fails against the latest build.

<details>
<summary>Working Logs with 0.14</summary>
<pre>
2022-02-18T21:55:27.771-0600 [INFO]  provider.terraform-provider-aws_v3.74.2_x5: 2022/02/18 21:55:27 [DEBUG] [aws-sdk-go] DEBUG: Response rds/CreateDBParameterGroup Details:
---[ RESPONSE ]--------------------------------------
HTTP/1.1 200 
Connection: close
Access-Control-Allow-Headers: authorization,cache-control,content-length,content-md5,content-type,etag,location,x-amz-acl,x-amz-content-sha256,x-amz-date,x-amz-request-id,x-amz-security-token,x-amz-tagging,x-amz-target,x-amz-user-agent,x-amz-version-id,x-amzn-requestid,x-localstack-target,amz-sdk-invocation-id,amz-sdk-request
Access-Control-Allow-Methods: HEAD,GET,PUT,POST,DELETE,OPTIONS,PATCH
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: etag,x-amz-version-id
Content-Type: text/html; charset=utf-8
Date: Sat, 19 Feb 2022 03:55:27 GMT
Server: hypercorn-h11

-----------------------------------------------------: timestamp=2022-02-18T21:55:27.771-0600
2022-02-18T21:55:27.771-0600 [INFO]  provider.terraform-provider-aws_v3.74.2_x5: 2022/02/18 21:55:27 [DEBUG] [aws-sdk-go] <CreateDBParameterGroupResponse xmlns="http://rds.amazonaws.com/doc/2014-09-01/"><CreateDBParameterGroupResult><DBParameterGroup>
          <DBParameterGroupName>sto-d-xx-rds-db-parameter-group-ue1</DBParameterGroupName>
          <DBParameterGroupFamily>aurora-postgresql12</DBParameterGroupFamily>
          <Description>Managed by Terraform</Description>
          <DBParameterGroupArn>arn:aws:rds:us-east-1:000000000000:pg:sto-d-xx-rds-db-parameter-group-ue1</DBParameterGroupArn>
        </DBParameterGroup></CreateDBParameterGroupResult><ResponseMetadata><RequestId>7805c127-af22-11c3-96ac-6999cc5f7e72</RequestId></ResponseMetadata></CreateDBParameterGroupResponse>: timestamp=2022-02-18T21:55:27.771-0600
2022-02-18T21:55:27.771-0600 [INFO]  provider.terraform-provider-aws_v3.74.2_x5: 2022/02/18 21:55:27 [INFO] DB Parameter Group ID: sto-d-xx-rds-db-parameter-group-ue1: timestamp=2022-02-18T21:55:27.771-0600
2022-02-18T21:55:27.771-0600 [INFO]  provider.terraform-provider-aws_v3.74.2_x5: 2022/02/18 21:55:27 [DEBUG] [aws-sdk-go] DEBUG: Request rds/AddTagsToResource Details:
---[ REQUEST POST-SIGN ]-----------------------------
POST / HTTP/1.1
Host: localhost:4566
User-Agent: APN/1.0 HashiCorp/1.0 Terraform/1.1.5 (+https://www.terraform.io) terraform-provider-aws/3.74.2 (+https://registry.terraform.io/providers/hashicorp/aws) aws-sdk-go/1.42.38 (go1.16; darwin; arm64)
Content-Length: 439
Authorization: AWS4-HMAC-SHA256 Credential=test/20220219/us-east-1/rds/aws4_request, SignedHeaders=content-length;content-type;host;x-amz-date, Signature=ba574153ec03d7feba5a2559ef7556b4b2181e0ee7a63232cdc7d002845ca003
Content-Type: application/x-www-form-urlencoded; charset=utf-8
X-Amz-Date: 20220219T035527Z
Accept-Encoding: gzip

Action=AddTagsToResource&ResourceName=arn%3Aaws%3Ards%3Aus-east-1%3A000000000000%3Apg%3Asto-d-xx-rds-db-parameter-group-ue1&Tags.Tag.1.Key=Application&Tags.Tag.1.Value=STO&Tags.Tag.2.Key=ParentEnvironment&Tags.Tag.2.Value=D&Tags.Tag.3.Key=ResourceType&Tags.Tag.3.Value=RDS&Tags.Tag.4.Key=Environment&Tags.Tag.4.Value=XX&Tags.Tag.5.Key=Location&Tags.Tag.5.Value=UE1&Tags.Tag.6.Key=Name&Tags.Tag.6.Value=Db-Parameter-Group&Version=2014-10-31
-----------------------------------------------------: timestamp=2022-02-18T21:55:27.771-0600
2022-02-18T21:55:27.795-0600 [INFO]  provider.terraform-provider-aws_v3.74.2_x5: 2022/02/18 21:55:27 [DEBUG] [aws-sdk-go] DEBUG: Response rds/AddTagsToResource Details:
---[ RESPONSE ]--------------------------------------
HTTP/1.1 200 
Connection: close
Access-Control-Allow-Headers: authorization,cache-control,content-length,content-md5,content-type,etag,location,x-amz-acl,x-amz-content-sha256,x-amz-date,x-amz-request-id,x-amz-security-token,x-amz-tagging,x-amz-target,x-amz-user-agent,x-amz-version-id,x-amzn-requestid,x-localstack-target,amz-sdk-invocation-id,amz-sdk-request
Access-Control-Allow-Methods: HEAD,GET,PUT,POST,DELETE,OPTIONS,PATCH
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: etag,x-amz-version-id
Content-Type: text/html; charset=utf-8
Date: Sat, 19 Feb 2022 03:55:27 GMT
Server: hypercorn-h11

-----------------------------------------------------: timestamp=2022-02-18T21:55:27.795-0600
2022-02-18T21:55:27.795-0600 [INFO]  provider.terraform-provider-aws_v3.74.2_x5: 2022/02/18 21:55:27 [DEBUG] [aws-sdk-go] <AddTagsToResourceResponse xmlns="http://rds.amazonaws.com/doc/2014-10-31/"><ResponseMetadata><RequestId>b194d9ca-a664-11e4-b688-194eaf8658fa</RequestId></ResponseMetadata></AddTagsToResourceResponse>: timestamp=2022-02-18T21:55:27.795-0600
</pre>
</details>

<details>
<summary>Broken Logs with latest</summary>
<pre>
2022-02-18T21:51:52.173-0600 [INFO]  provider.terraform-provider-aws_v3.74.2_x5: 2022/02/18 21:51:52 [DEBUG] [aws-sdk-go] DEBUG: Response rds/CreateDBParameterGroup Details:
---[ RESPONSE ]--------------------------------------
HTTP/1.1 200 
Connection: close
Access-Control-Allow-Headers: authorization,cache-control,content-length,content-md5,content-type,etag,location,x-amz-acl,x-amz-content-sha256,x-amz-date,x-amz-request-id,x-amz-security-token,x-amz-tagging,x-amz-target,x-amz-user-agent,x-amz-version-id,x-amzn-requestid,x-localstack-target,amz-sdk-invocation-id,amz-sdk-request
Access-Control-Allow-Methods: HEAD,GET,PUT,POST,DELETE,OPTIONS,PATCH
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: etag,x-amz-version-id
Content-Type: text/html; charset=utf-8
Date: Sat, 19 Feb 2022 03:51:52 GMT
Server: hypercorn-h11

-----------------------------------------------------: timestamp=2022-02-18T21:51:52.173-0600
2022-02-18T21:51:52.173-0600 [INFO]  provider.terraform-provider-aws_v3.74.2_x5: 2022/02/18 21:51:52 [DEBUG] [aws-sdk-go] <CreateDBParameterGroupResponse xmlns="http://rds.amazonaws.com/doc/2014-09-01/"><CreateDBParameterGroupResult><DBParameterGroup>
          <DBParameterGroupName>sto-d-xx-rds-db-parameter-group-ue1</DBParameterGroupName>
          <DBParameterGroupFamily>aurora-postgresql12</DBParameterGroupFamily>
          <Description>Managed by Terraform</Description>
          <DBParameterGroupArn>arn:aws:rds:us-east-1:000000000000:pg:sto-d-xx-rds-db-parameter-group-ue1</DBParameterGroupArn>
        </DBParameterGroup></CreateDBParameterGroupResult><ResponseMetadata><RequestId>7805c127-af22-11c3-96ac-6999cc5f7e72</RequestId></ResponseMetadata></CreateDBParameterGroupResponse>: timestamp=2022-02-18T21:51:52.173-0600
2022-02-18T21:51:52.173-0600 [INFO]  provider.terraform-provider-aws_v3.74.2_x5: 2022/02/18 21:51:52 [INFO] DB Parameter Group ID: sto-d-xx-rds-db-parameter-group-ue1: timestamp=2022-02-18T21:51:52.173-0600
2022-02-18T21:51:52.174-0600 [INFO]  provider.terraform-provider-aws_v3.74.2_x5: 2022/02/18 21:51:52 [DEBUG] [aws-sdk-go] DEBUG: Request rds/AddTagsToResource Details:
---[ REQUEST POST-SIGN ]-----------------------------
POST / HTTP/1.1
Host: localhost:4566
User-Agent: APN/1.0 HashiCorp/1.0 Terraform/1.1.5 (+https://www.terraform.io) terraform-provider-aws/3.74.2 (+https://registry.terraform.io/providers/hashicorp/aws) aws-sdk-go/1.42.38 (go1.16; darwin; arm64)
Content-Length: 439
Authorization: AWS4-HMAC-SHA256 Credential=test/20220219/us-east-1/rds/aws4_request, SignedHeaders=content-length;content-type;host;x-amz-date, Signature=53e93829ab2552d98d08651d29b2bf5889552d2d7029b10bfbc95b9f67058f82
Content-Type: application/x-www-form-urlencoded; charset=utf-8
X-Amz-Date: 20220219T035152Z
Accept-Encoding: gzip

Action=AddTagsToResource&ResourceName=arn%3Aaws%3Ards%3Aus-east-1%3A000000000000%3Apg%3Asto-d-xx-rds-db-parameter-group-ue1&Tags.Tag.1.Key=ResourceType&Tags.Tag.1.Value=RDS&Tags.Tag.2.Key=Location&Tags.Tag.2.Value=UE1&Tags.Tag.3.Key=ParentEnvironment&Tags.Tag.3.Value=D&Tags.Tag.4.Key=Environment&Tags.Tag.4.Value=XX&Tags.Tag.5.Key=Application&Tags.Tag.5.Value=STO&Tags.Tag.6.Key=Name&Tags.Tag.6.Value=Db-Parameter-Group&Version=2014-10-31
-----------------------------------------------------: timestamp=2022-02-18T21:51:52.174-0600
2022-02-18T21:51:52.232-0600 [INFO]  provider.terraform-provider-aws_v3.74.2_x5: 2022/02/18 21:51:52 [DEBUG] [aws-sdk-go] DEBUG: Response rds/AddTagsToResource Details:
---[ RESPONSE ]--------------------------------------
HTTP/1.1 404 
Connection: close
Access-Control-Allow-Headers: authorization,cache-control,content-length,content-md5,content-type,etag,location,x-amz-acl,x-amz-content-sha256,x-amz-date,x-amz-request-id,x-amz-security-token,x-amz-tagging,x-amz-target,x-amz-user-agent,x-amz-version-id,x-amzn-requestid,x-localstack-target,amz-sdk-invocation-id,amz-sdk-request
Access-Control-Allow-Methods: HEAD,GET,PUT,POST,DELETE,OPTIONS,PATCH
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: etag,x-amz-version-id
Content-Type: text/html; charset=utf-8
Date: Sat, 19 Feb 2022 03:51:52 GMT
Server: hypercorn-h11

-----------------------------------------------------: timestamp=2022-02-18T21:51:52.232-0600
2022-02-18T21:51:52.232-0600 [INFO]  provider.terraform-provider-aws_v3.74.2_x5: 2022/02/18 21:51:52 [DEBUG] [aws-sdk-go] <ErrorResponse xmlns="http://None.amazonaws.com/doc/2010-03-31/"><Error>
        <Type>Sender</Type>
        <Code>None</Code>
        <Message>Unable to find resource 'sto-d-xx-rds-db-parameter-group-ue1' for tagging</Message>
        </Error><RequestId>d6fe4c61</RequestId>
        </ErrorResponse>: timestamp=2022-02-18T21:51:52.232-0600
2022-02-18T21:51:52.232-0600 [INFO]  provider.terraform-provider-aws_v3.74.2_x5: 2022/02/18 21:51:52 [DEBUG] [aws-sdk-go] DEBUG: Validate Response rds/AddTagsToResource failed, attempt 0/25, error None: Unable to find resource 'sto-d-xx-rds-db-parameter-group-ue1' for tagging
	status code: 404, request id: d6fe4c61: timestamp=2022-02-18T21:51:52.232-0600
</pre>
</details>

### Expected Behavior

I'm able to use [this module](https://registry.terraform.io/modules/terraform-aws-modules/rds-aurora/aws/latest) successfully as I was with `localstack/localstack:0.14`.

### How are you starting LocalStack?

With the `localstack` script

### Steps To Reproduce

1. Create Terraform Resource
    ```
     resource "aws_db_parameter_group" "db_parameter_group" {
       name   = "my-awesome-db-parameter-group"
       family = "aurora-postgresql12"
   
       tags = {
         Application       = "my-app"
         Environment       = "my-env"
         Location          = "my-region"
         Name              = "my-awesome-db-parameter-group"
         ParentEnvironment = "my-parent-env"
         ResourceType      = "RDS"
       }
     }
    ```
2. Start LocalStack
3. Apply Terraform

### Environment

```markdown
- OS: M1 Mac Monterey
- LocalStack: latest
```

**Comment by steffyP** [comment]
Hi, we were able to reproduce your issue. 
As RDS is a pro feature the PR will not be visible here, however. The latest version should already be available with the fix.
