### ISSUE TITLE
Permission denied error when trying to create or update a Lambda function

### ISSUE THREAD

**Issue by aaronshaver** [localstack/localstack#553]
Here's what happened.

1. I wrote a Python Lambda function which included the line `print(context.get_remaining_time_in_millis())` from https://github.com/lambci/docker-lambda/blob/master/examples/python/lambda_function.py
2. LocalStack wasn't happy and shows an exception
3. Fine, I update my script to not have that line and try to do `aws lambda update-function`

But this fails (see stack trace below) and there seems to be a file locking issue that prevents an update to the function. I even tried clearing out all the files in the directory it mentions but no luck. In the end I rebooted my Mac and that "fixed" it.

```
2018-01-12T12:23:24:ERROR:lambda_api: Exception on /2015-03-31/functions/PostProposal/code [PUT]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/site-packages/localstack/services/awslambda/lambda_api.py", line 551, in update_function_code
    result = set_function_code(data, function)
  File "/usr/local/lib/python3.6/site-packages/localstack/services/awslambda/lambda_api.py", line 349, in set_function_code
    save_file(tmp_file, zip_file_content)
  File "/usr/local/lib/python3.6/site-packages/localstack/utils/common.py", line 410, in save_file
    with open(file, mode) as f:
PermissionError: [Errno 13] Permission denied: '/private/var/folders/yr/hgdc3qg10bj0rtnt9tqzjfwm0000gp/T/localstack/zipfile.7eb74e45/original_lambda_archive.zip'
```

**Comment by whummer** [comment]
Thanks for reporting @aaronshaver . How did you start up LocalStack? I'm assuming locally on the machine, and not in a Docker container?

I wasn't able to reproduce the issue. The following commands work for me:
```
awslocal lambda create-function --function-name f1 --handler lambda.handler --runtime python --role r1 --zip-file fileb://lambda.zip
awslocal lambda update-function-code --function-name f1 --zip-file fileb://lambda.zip
```
Can you please try again and post the output of these commands:
```
ls -la /private/var/folders/yr/hgdc3qg10bj0rtnt9tqzjfwm0000gp/T/localstack
ls -la /private/var/folders/yr/hgdc3qg10bj0rtnt9tqzjfwm0000gp/T/localstack/zipfile.*
```

**Comment by juancho088** [comment]
I'm having the same issue and already changed permissions using chmod. I have tried using the docker-compose, pip and build, and always fails.

**Comment by whummer** [comment]
@aaronshaver @juancho088 Is this issue resolved, or are you still seeing it in the latest version? Can you please help provide a few more details, it is really hard to debug or reproduce this issue based on the information that has been provided.

> In the end I rebooted my Mac and that "fixed" it.

After rebooting, did the problem occur again?

**Comment by vamaq** [comment]
Hi there! I'm also having the same issue.
In order to reproduce this the lambda function execution should fail.
After failing the update of the lambda function gets blocked.

```
Permission denied: '/private/var/folders/xs/b1tfnq8d4094b_nz02pk4xlw0000gn/T/localstack/zipfile.7e847f38/original_lambda_archive.zip'
```

```
ls -la /private/var/folders/xs/b1tfnq8d4094b_nz02pk4xlw0000gn/T/localstack/*
-rw-r--r--  1 juanramil  staff   822 Sep 21 09:38 /private/var/folders/xs/b1tfnq8d4094b_nz02pk4xlw0000gn/T/localstack/lambda_script_l_f9784eab.py
-rw-r--r--  1 juanramil  staff  1197 Sep 21 09:38 /private/var/folders/xs/b1tfnq8d4094b_nz02pk4xlw0000gn/T/localstack/lambda_script_l_f9784eab.pyc
-rw-r--r--  1 juanramil  staff   300 Sep 21 09:38 /private/var/folders/xs/b1tfnq8d4094b_nz02pk4xlw0000gn/T/localstack/sqs.22147e9b.conf

/private/var/folders/xs/b1tfnq8d4094b_nz02pk4xlw0000gn/T/localstack/zipfile.0e93fb6a:
total 0
dr-xr-xr-x   2 juanramil  staff   64 Sep 21 09:38 .
drwxr-xr-x  22 juanramil  staff  704 Sep 21 09:40 ..

/private/var/folders/xs/b1tfnq8d4094b_nz02pk4xlw0000gn/T/localstack/zipfile.136a2202:
total 0
dr-xr-xr-x   2 juanramil  staff   64 Sep 21 09:37 .
drwxr-xr-x  22 juanramil  staff  704 Sep 21 09:40 ..

/private/var/folders/xs/b1tfnq8d4094b_nz02pk4xlw0000gn/T/localstack/zipfile.19c74574:
total 0
dr-xr-xr-x   2 juanramil  staff   64 Sep 21 09:39 .
drwxr-xr-x  22 juanramil  staff  704 Sep 21 09:40 ..

/private/var/folders/xs/b1tfnq8d4094b_nz02pk4xlw0000gn/T/localstack/zipfile.1ccc746b:
total 16
drwxr-xr-x   4 juanramil  staff  128 Sep 21 09:38 .
drwxr-xr-x  22 juanramil  staff  704 Sep 21 09:40 ..
-rw-r--r--   1 juanramil  staff  822 Sep 21 09:38 lambda_syncer.py
-rw-r--r--   1 juanramil  staff  518 Sep 21 09:38 original_lambda_archive.zip

/private/var/folders/xs/b1tfnq8d4094b_nz02pk4xlw0000gn/T/localstack/zipfile.42ffa919:
total 0
dr-xr-xr-x   2 juanramil  staff   64 Sep 21 09:40 .
drwxr-xr-x  22 juanramil  staff  704 Sep 21 09:40 ..

/private/var/folders/xs/b1tfnq8d4094b_nz02pk4xlw0000gn/T/localstack/zipfile.4340c008:
total 0
dr-xr-xr-x   2 juanramil  staff   64 Sep 21 09:37 .
drwxr-xr-x  22 juanramil  staff  704 Sep 21 09:40 ..

/private/var/folders/xs/b1tfnq8d4094b_nz02pk4xlw0000gn/T/localstack/zipfile.4691c3f3:
total 0
dr-xr-xr-x   2 juanramil  staff   64 Sep 21 09:38 .
drwxr-xr-x  22 juanramil  staff  704 Sep 21 09:40 ..

/private/var/folders/xs/b1tfnq8d4094b_nz02pk4xlw0000gn/T/localstack/zipfile.7649f2e6:
total 0
dr-xr-xr-x   2 juanramil  staff   64 Sep 21 09:37 .
drwxr-xr-x  22 juanramil  staff  704 Sep 21 09:40 ..

/private/var/folders/xs/b1tfnq8d4094b_nz02pk4xlw0000gn/T/localstack/zipfile.7e847f38:
total 0
dr-xr-xr-x   2 juanramil  staff   64 Sep 21 09:40 .
drwxr-xr-x  22 juanramil  staff  704 Sep 21 09:40 ..

/private/var/folders/xs/b1tfnq8d4094b_nz02pk4xlw0000gn/T/localstack/zipfile.934f0ab0:
total 0
dr-xr-xr-x   2 juanramil  staff   64 Sep 21 09:39 .
drwxr-xr-x  22 juanramil  staff  704 Sep 21 09:40 ..

/private/var/folders/xs/b1tfnq8d4094b_nz02pk4xlw0000gn/T/localstack/zipfile.acbd0726:
total 0
dr-xr-xr-x   2 juanramil  staff   64 Sep 21 09:38 .
drwxr-xr-x  22 juanramil  staff  704 Sep 21 09:40 ..

/private/var/folders/xs/b1tfnq8d4094b_nz02pk4xlw0000gn/T/localstack/zipfile.bf2783b1:
total 0
dr-xr-xr-x   2 juanramil  staff   64 Sep 21 09:37 .
drwxr-xr-x  22 juanramil  staff  704 Sep 21 09:40 ..

/private/var/folders/xs/b1tfnq8d4094b_nz02pk4xlw0000gn/T/localstack/zipfile.c3b18acc:
total 0
dr-xr-xr-x   2 juanramil  staff   64 Sep 21 09:39 .
drwxr-xr-x  22 juanramil  staff  704 Sep 21 09:40 ..

/private/var/folders/xs/b1tfnq8d4094b_nz02pk4xlw0000gn/T/localstack/zipfile.cae3e6c5:
total 0
dr-xr-xr-x   2 juanramil  staff   64 Sep 21 09:37 .
drwxr-xr-x  22 juanramil  staff  704 Sep 21 09:40 ..

/private/var/folders/xs/b1tfnq8d4094b_nz02pk4xlw0000gn/T/localstack/zipfile.d4bfe8a7:
total 0
dr-xr-xr-x   2 juanramil  staff   64 Sep 21 09:38 .
drwxr-xr-x  22 juanramil  staff  704 Sep 21 09:40 ..

/private/var/folders/xs/b1tfnq8d4094b_nz02pk4xlw0000gn/T/localstack/zipfile.f799256d:
total 0
dr-xr-xr-x   2 juanramil  staff   64 Sep 21 09:38 .
drwxr-xr-x  22 juanramil  staff  704 Sep 21 09:40 ..```

```
ls -la /private/var/folders/xs/b1tfnq8d4094b_nz02pk4xlw0000gn/T/localstack/zipfile.*
/private/var/folders/xs/b1tfnq8d4094b_nz02pk4xlw0000gn/T/localstack/zipfile.0e93fb6a:
total 0
dr-xr-xr-x   2 juanramil  staff   64 Sep 21 09:38 .
drwxr-xr-x  22 juanramil  staff  704 Sep 21 09:40 ..

/private/var/folders/xs/b1tfnq8d4094b_nz02pk4xlw0000gn/T/localstack/zipfile.136a2202:
total 0
dr-xr-xr-x   2 juanramil  staff   64 Sep 21 09:37 .
drwxr-xr-x  22 juanramil  staff  704 Sep 21 09:40 ..

/private/var/folders/xs/b1tfnq8d4094b_nz02pk4xlw0000gn/T/localstack/zipfile.19c74574:
total 0
dr-xr-xr-x   2 juanramil  staff   64 Sep 21 09:39 .
drwxr-xr-x  22 juanramil  staff  704 Sep 21 09:40 ..

/private/var/folders/xs/b1tfnq8d4094b_nz02pk4xlw0000gn/T/localstack/zipfile.1ccc746b:
total 16
drwxr-xr-x   4 juanramil  staff  128 Sep 21 09:38 .
drwxr-xr-x  22 juanramil  staff  704 Sep 21 09:40 ..
-rw-r--r--   1 juanramil  staff  822 Sep 21 09:38 lambda_syncer.py
-rw-r--r--   1 juanramil  staff  518 Sep 21 09:38 original_lambda_archive.zip

/private/var/folders/xs/b1tfnq8d4094b_nz02pk4xlw0000gn/T/localstack/zipfile.42ffa919:
total 0
dr-xr-xr-x   2 juanramil  staff   64 Sep 21 09:40 .
drwxr-xr-x  22 juanramil  staff  704 Sep 21 09:40 ..

/private/var/folders/xs/b1tfnq8d4094b_nz02pk4xlw0000gn/T/localstack/zipfile.4340c008:
total 0
dr-xr-xr-x   2 juanramil  staff   64 Sep 21 09:37 .
drwxr-xr-x  22 juanramil  staff  704 Sep 21 09:40 ..

/private/var/folders/xs/b1tfnq8d4094b_nz02pk4xlw0000gn/T/localstack/zipfile.4691c3f3:
total 0
dr-xr-xr-x   2 juanramil  staff   64 Sep 21 09:38 .
drwxr-xr-x  22 juanramil  staff  704 Sep 21 09:40 ..

/private/var/folders/xs/b1tfnq8d4094b_nz02pk4xlw0000gn/T/localstack/zipfile.7649f2e6:
total 0
dr-xr-xr-x   2 juanramil  staff   64 Sep 21 09:37 .
drwxr-xr-x  22 juanramil  staff  704 Sep 21 09:40 ..

/private/var/folders/xs/b1tfnq8d4094b_nz02pk4xlw0000gn/T/localstack/zipfile.7e847f38:
total 0
dr-xr-xr-x   2 juanramil  staff   64 Sep 21 09:40 .
drwxr-xr-x  22 juanramil  staff  704 Sep 21 09:40 ..

/private/var/folders/xs/b1tfnq8d4094b_nz02pk4xlw0000gn/T/localstack/zipfile.934f0ab0:
total 0
dr-xr-xr-x   2 juanramil  staff   64 Sep 21 09:39 .
drwxr-xr-x  22 juanramil  staff  704 Sep 21 09:40 ..

/private/var/folders/xs/b1tfnq8d4094b_nz02pk4xlw0000gn/T/localstack/zipfile.acbd0726:
total 0
dr-xr-xr-x   2 juanramil  staff   64 Sep 21 09:38 .
drwxr-xr-x  22 juanramil  staff  704 Sep 21 09:40 ..

/private/var/folders/xs/b1tfnq8d4094b_nz02pk4xlw0000gn/T/localstack/zipfile.bf2783b1:
total 0
dr-xr-xr-x   2 juanramil  staff   64 Sep 21 09:37 .
drwxr-xr-x  22 juanramil  staff  704 Sep 21 09:40 ..

/private/var/folders/xs/b1tfnq8d4094b_nz02pk4xlw0000gn/T/localstack/zipfile.c3b18acc:
total 0
dr-xr-xr-x   2 juanramil  staff   64 Sep 21 09:39 .
drwxr-xr-x  22 juanramil  staff  704 Sep 21 09:40 ..

/private/var/folders/xs/b1tfnq8d4094b_nz02pk4xlw0000gn/T/localstack/zipfile.cae3e6c5:
total 0
dr-xr-xr-x   2 juanramil  staff   64 Sep 21 09:37 .
drwxr-xr-x  22 juanramil  staff  704 Sep 21 09:40 ..

/private/var/folders/xs/b1tfnq8d4094b_nz02pk4xlw0000gn/T/localstack/zipfile.d4bfe8a7:
total 0
dr-xr-xr-x   2 juanramil  staff   64 Sep 21 09:38 .
drwxr-xr-x  22 juanramil  staff  704 Sep 21 09:40 ..

/private/var/folders/xs/b1tfnq8d4094b_nz02pk4xlw0000gn/T/localstack/zipfile.f799256d:
total 0
dr-xr-xr-x   2 juanramil  staff   64 Sep 21 09:38 .
drwxr-xr-x  22 juanramil  staff  704 Sep 21 09:40 ..
```
