### ISSUE TITLE
feature request: support cloudwatch filter subscriptions for invoking lambda functions

### ISSUE THREAD

**Issue by SwatsonCodes** [localstack/localstack#5542]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

In AWS, it is possible to create a CloudWatch subscription filter that invokes a Lambda function. This is described in this guide:
https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/SubscriptionFilters.html
Essentially, the subscription filter works by tailing a CloudWatch log stream and invoking a given Lambda function whenever it encounters one or more logs in the stream that match a particular pattern.

I attempted to do this in localstack using the following commands, but the Lambda is never invoked. I verified that the commands produce the desired behavior in AWS.

```
# create standard lambda execution role
awslocal iam create-role --role-name lambda-ex --assume-role-policy-document file://role.json

awslocal logs create-log-group --log-group-name test

awslocal logs create-log-stream \
	--log-group-name test \
	--log-stream-name test

# the contents of the lambda function doesn't matter, we just need something to invoke for testing
awslocal lambda create-function \
    --function-name relay \
    --zip-file fileb://relay.zip \
    --handler relay.lambda_handler \
    --role "arn:aws:iam::000000000000:role/lambda-ex" \
    --runtime python3.8

awslocal lambda add-permission \
    --function-name "relay" \
    --statement-id "relay" \
    --principal "logs.us-east-1.amazonaws.com" \
    --action "lambda:InvokeFunction" \
    --source-arn "arn:aws:logs:us-east-1:000000000000:log-group:test:*" \
    --source-account "000000000000"


awslocal logs put-subscription-filter \
    --log-group-name test \
    --filter-name test \
    --filter-pattern "" \
    --destination-arn arn:aws:lambda:us-east-1:000000000000:function:relay

# put some log event
awslocal logs put-log-events --log-group-name test --log-stream-name test --log-events "[{\"timestamp\": 1645470882218 , \"message\": \"hello from cloudwatch\"}]"
```
Currently, the Lambda is never executed even though the subscription filter is in place.

**Comment by steffyP** [comment]
Hi @SwatsonCodes,

do you know with which version you initially tested this scenario? 
I tried with the `latest` docker image, and it seems to work. 
Could give it another try? 🙏
