### ISSUE TITLE
moto-ext containing some changes specific for LocalStack. can you publish git repository for it?

### ISSUE THREAD

**Issue by errdos** [localstack/localstack#555]
moto-ext containing some changes specific for LocalStack. can you publish git repository for it?
i wish to add some small hacks/function to moto and i cant use the original moto github due to it missing some features/hacks you added for local stack.

currently i can copy the changes and commit them myself but it might cause some issues in the future with merging my changes to your branch :/

if it is already published and i might have missed ill appreciate if you can guide me to the location.
thanks in advnce
er

**Comment by whummer** [comment]
Hi @errdos , I've moved the fork for `moto-ext` into the `localstack-fixes` branch of this repository: https://github.com/localstack/moto

Can you please raise a PR against the [`localstack-fixes` branch](https://github.com/localstack/moto/tree/localstack-fixes) of that repo. Thanks!

Also, at some point we should check out the current diff of `moto-ext` to see if we can get the changes merged upstream.
