### ISSUE TITLE
bug: Multi-account SNS topic ARNs use both account IDs

### ISSUE THREAD

**Issue by dpwdec** [localstack/localstack#5551]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When running localstack in multi account mode using `TEST_AWS_ACCOUNT_ID=000000000001,000000000002` the ARNs for topics created using `aws sns` CLI utility contain both account IDs rather than the account in which they were created. 

For example listing topics after creation shows:
```json
{
    "Topics": [
        {
            "TopicArn": "arn:aws:sns:eu-west-1:000000000001,000000000002:my-topic"
        }
    ]
}
```

### Expected Behavior

Running the `create-topics` command should produce a topic with the following ARN:

```json
{
    "TopicArn": "arn:aws:sns:eu-west-1:000000000001:my-topic"
}
```

### How are you starting LocalStack?

With the `localstack` script

### Steps To Reproduce

1. Start a pro version localstack running instance running:
```bash
LOCALSTACK_API_KEY=********** TEST_AWS_ACCOUNT_ID=000000000001,000000000002 EDGE_PORT=4566 IMAGE_NAME=localstack/localstack:0.11.0 localstack start -d
```
2. Create an SNS topics using the aws CLI:
```bash
AWS_ACCESS_KEY_ID=000000000001 aws --endpoint-url=http://localhost:4566 sns create-topic --name my-topic
```

### Environment

```markdown
- OS: macOS Catalina
- LocalStack: localstack/localstack:0.11.0
```

**Comment by thrau** [comment]
hi @dpwdec, i wasn't able to reproduce the problem. it seems you are using an older version of localstack. could you please check whether your issue still occurs with the latest image?
