### ISSUE TITLE
feature request: Elasticsearch service not available in the community edition?

### ISSUE THREAD

**Issue by trineshchetty** [localstack/localstack#5555]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Hey guys. Just want confirmation about elasticseach/opensearch. Is it available in the community edition?

**Comment by silv-io** [comment]
Hello @trineshchetty, thanks for the question! OpenSearch is available in the Community edition (see [here](https://github.com/localstack/localstack/tree/master/localstack/services/opensearch). What is exclusive to the PRO version of localstack is persistence in OpenSearch/Elasticsearch.
