### ISSUE TITLE
feature request:  appsync lambda resolver 

### ISSUE THREAD

**Issue by cemo** [localstack/localstack#5557]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

We would like to use localstack appsync with lambda resolvers. It seems it is not supported. Please add support for it. 

### 🧑‍💻 Implementation

I think it is not a big deal since appsync and lambda support is already available. There might some missing glue codes.

### Anything else?

We can also contribute if someone can point necessary place but I could not see pro version codes in this repo.

**Comment by whummer** [comment]
Hi @cemo, thanks for reporting. This should actually already be available in the `latest` Docker image - you can create an AppSync data source with `type=AWS_LAMBDA`, and specifying `lambdaConfig={"lambdaFunctionArn": ...}`.

Can you please share a few more details - ideally a few snippets of your client code, so we can replicate your use case end-to-end.. Thanks for your help!
