### ISSUE TITLE
bug: Unable to Delete S3 Objects using the Java SDK

### ISSUE THREAD

**Issue by kusold** [localstack/localstack#5558]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

You are unable to issue delete commands using the Java SDK

I tried two different ways. The first was deleting multiple objects, and the second was a single.

```java
s3.deleteObjects(new DeleteObjectsRequest(bucketName).withKeys(keys));
```
```
localenv-localstack-1  | 2022-02-23T03:59:52.326:INFO:localstack.services.edge: Unable to find forwarding rule for host "localstack:4566", path "POST /foo-example/?delete", target header "", auth header "", data "b'<Delete><Object><Key>sftp/outgoing/testfile.pgp</Key></Object></Delete>'"
```

```java
keyList.forEach((key) -> s3.deleteObject(new DeleteObjectRequest(bucketName, key)));
```

```
localenv-localstack-1  | 2022-02-23T04:05:07.175:INFO:localstack.services.edge: Unable to find forwarding rule for host "localstack:4566", path "DELETE /foo-example/sftp/outgoing/testfile.pgp", target header "", auth header "", data ""
```

### Expected Behavior

You should be able to delete files in S3.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

Start localstack, create a file in S3, then try to delete it using the Java SDK.

### Environment

```markdown
- OS: Mac/Docker
- LocalStack: 0.14.0
```

### Anything else?

I believe this is a missed use case from https://github.com/localstack/localstack/pull/3500

**Comment by kusold** [comment]
`deleteObjects` is failing because the path is `?delete` instead of `?delete=`

https://github.com/localstack/localstack/blob/3bc7a8c4cd62e0f6e15c94960ff11b0500388b28/localstack/services/edge.py#L487

`deleteObject` is failing because `edge.py` doesn't take into account `DELETE` methods for S3. 
https://github.com/localstack/localstack/blob/3bc7a8c4cd62e0f6e15c94960ff11b0500388b28/localstack/services/edge.py

I can force the behavior I want by setting the user-agent:

```
AwsClientBuilder.EndpointConfiguration endpointConfiguration = new AwsClientBuilder.EndpointConfiguration(
            config().getString("aws_s3_endpoint_url"),
            S3Helper.resolveAWSRegion().getName()
        );

        ClientConfiguration config = new ClientConfiguration();
        config.setUserAgentPrefix("aws-cli/localstack-workaround");

        AmazonS3 s3 = AmazonS3Client.builder()
            .withClientConfiguration(config)
            .withEndpointConfiguration(endpointConfiguration)
            .withPathStyleAccessEnabled(true)
            .build();
```

**Comment by pinzon** [comment]
@kusold could you provide more info about your Project or JAVA SDK version? I just added some tests in the localstack-java-utils project to validate the deletion of S3 objects with both SDK versions and the tests pass correctly.

**Comment by kusold** [comment]
`Java SDK 8`

`com.amazonaws:aws-java-sdk-s3:1.11.228`

These versions aren't up to date by any definition, but they do work when communicating with AWS S3.

**Comment by kusold** [comment]
The AWS docs say that they support both HTTP methods that I pointed out in https://github.com/localstack/localstack/issues/5558#issuecomment-1048471104 . I think this issue might be more related to `edge.py` not supporting the AWS S3 deletion spec, then a particular client implementation.

https://docs.aws.amazon.com/AmazonS3/latest/API/API_DeleteObject.html
https://docs.aws.amazon.com/AmazonS3/latest/API/API_DeleteObjects.html

**Comment by pinzon** [comment]
The thing about the error reproducer is that makes it easy to integrate a test either on this project or in localstack-java-utils( where we validate some different AWS behaviors or features) to validate the according change.

But no worries. I'll write a test with the http requests. Thanks for the documentation link 👍.
