### ISSUE TITLE
bug: SerializationError when calling cloudwatch "EnableAlarmActions"

### ISSUE THREAD

**Issue by nikoboerger1369** [localstack/localstack#5562]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When calling 

`cloudWatchClient.EnableAlarmActions(&cloudwatch.EnableAlarmActionsInput{AlarmNames: alarmNames})`

with golang I receive a SerializationError with bytes in the error message saying: 

`<!DOCTYPE HTM |UBLIC "-//W3C//DTD HTML 3.2 Final//EN">.<title>500 Internal Server Error</title>.<h1>Internal Server Error</h1>.<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.`

I believe this is a bug, since other cloudwatch operations like "DescribeAlarms" work flawlessly with the same client.

### Expected Behavior

I expected the call to go through without any errors

### How are you starting LocalStack?

With a `docker run` command

### Steps To Reproduce

Start localstack, create alarms and call cloudwatch "EnableAlarmActions"

**Comment by steffyP** [comment]
Hi @nikoboerger1369,

when you use the latest image, e.g.  pull`localstack/localstack:latest`, the cloudwatch API for `enable-alarm-action` and `disable-alarm-action` is available. 
Please let us know if it works as expected.

**Comment by steffyP** [comment]
Hi @nikoboerger1369,

we have merged the missing feature a few days ago and it should resolve your problem. If you still encounter any problems, feel free to re-open this ticket.
