### ISSUE TITLE
Connection error from Lambda execution (NodeJS)

### ISSUE THREAD

**Issue by tristanbenier** [localstack/localstack#557]
Hi,

I am facing an issue when I try to access another localstack AWS service from a Lambda execution (in NodeJS).

I launch localstack services using `LAMBDA_EXECUTOR=docker`.

I have created a lambda which lists all the functions using AWS.Lambda.listFunctions() (https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Lambda.html#listFunctions-property).

This throws the following error when invoked : 
```
{
  "errorMessage":"connect ECONNREFUSED 127.0.0.1:4574",
  "errorType":"NetworkingError",
  "stackTrace": [
    "Object.exports._errnoException (util.js:1018:11)",
    "exports._exceptionWithHostPort (util.js:1041:20)",
    "TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)"
  ]
}
```

Notes:
- same error when trying to execute a S3 function.
- tried to set different endpoints when instantiating my Lambda clients, all send the same error
- lambda executed as a simple nodejs file (not as a lambda) works fine

Anyone has seen this error before ?

Cheers' !

**Comment by Pat-rice** [comment]
I have the same problem with dynamoDB.
Here's an example: 
`lambda_dynamodb.js`
```const AWS = require('aws-sdk');
const dynamoDB = new AWS.DynamoDB({
  region  : 'eu-west-1',
  endpoint: 'http://localhost:4569'
});
const documentClient = new AWS.DynamoDB.DocumentClient({service: dynamoDB});

module.exports.handler = (event, context, callback) => {
  let params = {
	TableName : 'local-test',
	Item: {id : 123, username : 'foo'}
  };

  documentClient.put(params).promise()
  .then((response) => {
  	callback(null, response);	
  })
  .catch(callback);

};
```

If I invoke it I get : 
```
{"errorMessage":"connect ECONNREFUSED 127.0.0.1:4569","errorType":"NetworkingError","stackTrace":["Object.exports._errnoException (util.js:1018:11)","exports._exceptionWithHostPort (util.js:1041:20)","TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)"]}
````

Here's a "get started" script to reproduce it, given that your lambda file is called `lambda_dynamodb.js`:
```
zip lambda.zip lambda_dynamodb.js
awslocal dynamodb create-table \
         --attribute-definitions \
                AttributeName=id,AttributeType=S \
         --table-name local-test \
         --provisioned-throughput ReadCapacityUnits=1,WriteCapacityUnits=1 \
         --key-schema \
                AttributeName=id,KeyType=HASH
awslocal lambda create-function --function-name fdynamo --runtime=nodejs6.10 --role=r1 --handler=lambda_dynamodb.handler --zip-file fileb://lambda.zip
awslocal lambda invoke --function-name fdynamo result.log
```

**Comment by blueshirts** [comment]
Seeing the same issue.  Returns this error when trying to connect to DynamoDB from a Lamba.  As mentioned running the code via script instead of as a Lambda works.

**Comment by blueshirts** [comment]
Seems like the issue is related to the fact that the lambdas are being executed in their own containers rather than on the container running the other AWS services.  I don't have a lot of insight into this but it looks like you must use the LOCALSTACK_HOSTNAME value in your endpoint configuration.

LOCALSTACK_HOSTNAME is a read-only environment variable.  It is documented in the readme though I didn't see it until I came across the issue below.  Below is the configuration that I used to connect to DynamoDB.

```
const client = new AWS.DynamoDB.DocumentClient({endpoint: `http://${process.env.LOCALSTACK_HOSTNAME}:4569`})
```

Here is the related issue.
https://github.com/localstack/localstack/issues/377

**Comment by whummer** [comment]
Thanks for clarifying @blueshirts ! Does using `LOCALSTACK_HOSTNAME` solve your issue @Pat-rice @tristanbenier ? Closing this issue now for housekeeping reasons, but please leave a comment here if the problem persists or if there are any other issues. Thanks

**Comment by Pat-rice** [comment]
Yes it's working by using `LOCALSTACK_HOSTNAME` for dynamoDB endpoint, thanks for this, that wasn't obvious :)

**Comment by rudresh-ajgaonkar** [comment]
@Pat-rice LOCALSTACK_HOSTNAME should be specified in the template.yml? What should be the value for it?

**Comment by jacobus** [comment]
Not completely related, but in case in helps someone, when running with `sam local' you can specify that it should use the local network:

` sam local invoke MyLambdaFunction --event sample-event.json --docker-network host`

https://stackoverflow.com/a/57544678/828757

**Comment by Flaavius** [comment]
> Not completely related, but in case in helps someone, when running with `sam local' you can specify that it should use the local network:
> 
> ` sam local invoke MyLambdaFunction --event sample-event.json --docker-network host`
> 
> https://stackoverflow.com/a/57544678/828757

this solved my issue. thanks 💯
