### ISSUE TITLE
bug: cognito-idp admin-add-user-to-group fails with UserNotFoundException with custom region

### ISSUE THREAD

**Issue by vittoriozamboni** [localstack/localstack#5595]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After creating a user pool, one group and one users, I am trying to associate one user to the existing group.
The pool is created within a specific region, which is not the default us-east-1.
The command fails throwing a `UserNotFoundException`, but the list-users correctly returns the user.

If the region is not specified, it works (run all the commands without specifying `--region`).

### Expected Behavior

The user is associated to the group.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

   `docker-compose up`

Commands: 
 - create a user pool:
   `awslocal --region=eu-west-1 cognito-idp create-user-pool --pool-name localstack-issue-pool`
   this correctly returns the ID starting with `eu-west-1`
- create a group:
   `awslocal --region=eu-west-1 cognito-idp create-group --group-name admins --user-pool-id <pool_ID>`
- create a user:
   `awslocal --region=eu-west-1 cognito-idp admin-create-user --username mainuser@domain.com --user-pool-id <pool_ID>`
- associate:
   `awslocal --region=eu-west-1 cognito-idp admin-add-user-to-group --username mainuser@domain.com --group-name admins --user-pool-id <pool_ID>`

The same error is triggered also by creating items with the JS SDK.

### Environment

```markdown
- OS: MacOS 12.2.1
- LocalStack: 0.14.0
```

**Comment by whummer** [comment]
Thanks for reporting @vittoriozamboni . We've tried to replicate this issue, but without success so far.

The following script appears to work (all commands return successful exit code `0`):
```
region=--region=eu-west-1
poolId=$(awslocal $region cognito-idp create-user-pool --pool-name localstack-issue-pool | jq -r .UserPool.Id)
awslocal $region cognito-idp create-group --group-name admins --user-pool-id $poolId
awslocal $region cognito-idp admin-create-user --username mainuser@domain.com --user-pool-id $poolId
awslocal $region cognito-idp admin-add-user-to-group --username mainuser@domain.com --group-name admins --user-pool-id $poolId
```
Can you please pull the `latest` Docker image (and configure it in your docker-compose.yml) and give it another try? Thanks for your help.

**Comment by vittoriozamboni** [comment]
Hi @whummer thanks for your response and investigation. 
If I start a brand new environment it works, at this point I am not sure if there was something else causing conflicts. 

I will update the thread if I will face the issue again.
