### ISSUE TITLE
question: aws lambda event for kafka seems not working

### ISSUE THREAD

**Issue by tranchiendang** [localstack/localstack#5599]
### Is there an existing issue for this?

- [X] I have searched the existing issues and read the documentation

### Question

I am setting up like this:
`export const consumeEvent: AWSFunction = {
  handler: `${handlerPath(__dirname)}/handler.consumeEventMessage`,
  events: [
    {
      kafka: {
        accessConfigurations: {
          saslScram512Auth: ["arn:aws:secretsmanager:us-east-1:000000000000:secret:localstack1-CJsErQ"]
        },
        bootstrapServers: ["localhost:9092"],
        topic: "my_topic"
      }
    },
  ],
};`

But when i tried to produce message to topic, no aws lambda was trigger at all.
Any advise will be appreciated. Thanks.

**Comment by whummer** [comment]
Thanks for reporting @tranchiendang . Please note that certain features and services, including Managed Streaming for Kafka (MSK) and Lambda Kafka event source mappings are only available in the Pro version of LocalStack. More details can be found in our docs here: https://docs.localstack.cloud/aws/managed-streaming-for-kafka Hope that helps, thanks.

**Comment by dominikschubert** [comment]
@tranchiendang  Could you please elaborate a bit more on your setup and how you're creating all related resources? A small self-contained sample would be ideal for us to try and reproduce your issue here.
