### ISSUE TITLE
feature request: add .NET 6 lambda support

### ISSUE THREAD

**Issue by JSanchezIO** [localstack/localstack#5601]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

.NET 6 was recently added to AWS Lambda. It would be beneficial if LocalStack added it so I can continue using it for local development.

**Comment by MiguelAlhoLGC** [comment]
The dotnet  3.1 images in use seem to be built from the Lambci entity/repo which seems to be a dead project at the moment:

https://github.com/lambci/docker-lambda/issues/353

Guessing this would need a new image to be defined somewhere to be supported? Are there any guidelines into how to get this included / updated?

**Comment by JSanchezIO** [comment]
@MiguelAlhoLGC I'm not sure if this would help, but the .NET Lambda repository has the images for the Lambda Runtime.

https://github.com/aws/aws-lambda-dotnet/tree/master/LambdaRuntimeDockerfiles

**Comment by JSanchezIO** [comment]
Thanks for the callout @adam-knights! For those watching this issue, I'm comfortable with closing it now but would personally prefer to wait for the new LocalStack release to land with .NET 6 support. If no one has any objections, I'll wait until then to close it.

**Comment by christopher-taormina-zocdoc** [comment]
when will this be released?

**Comment by JSanchezIO** [comment]
Seems this was released in [v0.14.3](https://github.com/localstack/localstack/releases/tag/v0.14.3)
