### ISSUE TITLE
question: SNS to Firehose message processing

### ISSUE THREAD

**Issue by adiberk** [localstack/localstack#5602]
### Is there an existing issue for this?

- [X] I have searched the existing issues and read the documentation

### Question

Looking at the sns service - I see that we support firehose as a protocol for subscription.  However it doesn't seem that we actually have a conditional to later check for that protocol and a message comes to SNS.  
I am trying to create a setup locally where SNS messages get sent to firehose which will then forward them to opensearch. 
- Please let me know if this is supposed to be possible?

My configuration:
**OpenSearch:**
` aws --endpoint-url=http://${LOCALSTACK_HOST}:${PORT} opensearch create-domain --domain-name dev_open_search
`
**Firehose:**
`aws --endpoint-url=http://${LOCALSTACK_HOST}:${PORT} firehose create-delivery-stream --delivery-stream-name activity-to-opensearch-local --delivery-stream-type DirectPut --amazonopensearchservice-destination-configuration "RoleARN=arn:aws:iam::000000000000:role/Firehose-Reader-Role,DomainARN=arn:aws:es:us-east-1:000000000000:domain/dev_open_search,IndexName=activity,TypeName=activity,S3Configuration={RoleARN=arn:aws:iam::000000000000:role/Firehose-Reader-Role,BucketARN=arn:aws:s3:::kinesis-activity-backup-local}"
`
**Subscribe Firehose to sns topic:**
`aws --endpoint-url=http://${LOCALSTACK_HOST}:${SNS_PORT} sns subscribe --topic-arn arn:aws:sns:${AWS_REGION}:000000000000:${TOPIC_NAME} --protocol firehose --notification-endpoint arn:aws:firehose:us-east-1:000000000000:deliverystream/activity-to-opensearch-local
`

**Comment by lucasklaassen** [comment]
This is the error I get when trying to subscribe firehose to SNS using localstack.
`2022-05-07T17:17:21.626:WARNING:localstack.services.sns.sns_listener: Unexpected protocol "firehose" for SNS subscription`

**Comment by adiberk** [comment]
> This is the error I get when trying to subscribe firehose to SNS using localstack.
> 
> `2022-05-07T17:17:21.626:WARNING:localstack.services.sns.sns_listener: Unexpected protocol "firehose" for SNS subscription`

Maybe it has since changed. I delved into the code and saw that firehouse was an actual option to pass on a protocol. It may have changed since the posting

**Comment by lucasklaassen** [comment]
@adiberk looks like I can create the subscription but when the first message is published to the topic that's the error I get from localstack.

**Comment by sat4win** [comment]
I am also receiving the same error while using LocalStack. I have performed following steps:
1. Created a topic in sns
2. Created a S3 bucket
3. Created firehose delivery stream with source DirectPut and destination is S3 bucket created above
4. Subscribe to topic with firehose protocol and assign delivery stream ARN as notification end point.
5. publish a message to topic

Got the following error:
WARNING:localstack.services.sns.provider: Unexpected protocol "firehose" for SNS subscription

**Comment by pinzon** [comment]
@adiberk The PR with the changes for this feature has been merged. Make sure to pull the latest LocalStack image. Thank you for the the issue.
