### ISSUE TITLE
bug: API Gateway domainPrefix

### ISSUE THREAD

**Issue by c1moore** [localstack/localstack#5603]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When hitting an API Gateway endpoint using `http://subdomain.localhost:4566/x`, the `domainPrefix` is set to the original API Gateway's URL prefix (which happens to be the ID of the API).

For example:

My request
```
GET http://subdomain.localhost:4566/x
```

`domainName` passed to Lambda: `lpblmcpd36.execute-api.localhost.localstack.cloud`

`domainPrefix` passed to Lambda: `lpblmcpd36`

### Expected Behavior

[Wildcard Custom Domain Names](https://docs.aws.amazon.com/apigateway/latest/developerguide/how-to-custom-domains.html#wildcard-custom-domain-names) is a core feature I'm looking to use.  Basically, this feature allows you to provide multitenancy via a subdomain.

So, when I send `GET http://subdomain.localhost:4566/x`, I expect `domainName` to be `subdomain.localhost` and domainPrefix to be `subdomain`. 

If that's not possible, perhaps the `domainName` could be `subdomain.lpblmcpd36.execute-api.localhost.localstack.cloud` and the `domainPrefix` would be `subdomain`.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

`docker-compose.yml`

```yml
version: "3.1"

services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - 4566:4566
```

Pulumi Code

```ts
const apiGateway = new RestAPI('api-gateway', {
  stageName: config.require('env'),
  routes: [{
    path: '/x',
    method: 'GET',
    eventHandler: myLambda,
  }],
});
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

`pulumilocal up`

### Environment

```markdown
- OS: Unbuntu 20
- LocalStack: latest
```

### Anything else?

https://docs.aws.amazon.com/apigateway/latest/developerguide/how-to-custom-domains.html#wildcard-custom-domain-names

**Comment by calvernaz** [comment]
Hi @c1moore, the fix was merged, do you mind to try in the latest docker image?
