### ISSUE TITLE
question: Access localstack opensearch from another container

### ISSUE THREAD

**Issue by adiberk** [localstack/localstack#5609]
### Is there an existing issue for this?

- [X] I have searched the existing issues and read the documentation

### Question

I have a docker-compose file which starts one localstack container and another backend container.  FOr localstack I am running sns,sqs, and opensearch.  All 3 seem to be setup correctly.  I am able to curl the opensearch endpoint from my terminal just fine.  However, when I try to access open search from inside a connected container I get 500 error and I see localstack logging s3 issues - it thinks I am accessing s3.
- I supposed the issue stems from the fact that opensearch is a custom domain and resolved by DNS and I may need some special networking magic to get it to work.   

Here is my configuration for opensearch and localstack
Docker-compose localstack service:
`localstack:
    container_name: localstack
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
      - "8055:8080"
    env_file:
      - .env
    healthcheck:
      test: aws sns list-topics
      interval: 3s
      timeout: 20s
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - SERVICES=sns,sqs,events,opensearch
      # - DATA_DIR=/tmp/localstack/data
      - AWS_DEFAULT_REGION=us-east-1
      - HOSTNAME_EXTERNAL=localhost
      - AWS_ACCESS_KEY_ID=1234
      - AWS_SECRET_ACCESS_KEY=1234
      - DEBUG=1
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - ./bootstrap_localstack:/docker-entrypoint-initaws.d/`
      
I then have a start_opensearch.sh file which runs the following
`aws --endpoint-url=http://localhost:4566 opensearch create-domain --domain-name dev_open_search --domain-endpoint-options '{ "CustomEndpoint": "http://127.0.0.1:4566/opensearch", "CustomEndpointEnabled": true }' --cluster-config '{ "InstanceType": "m3.xlarge.elasticsearch", "InstanceCount": 4, "DedicatedMasterEnabled": true, "ZoneAwarenessEnabled": true, "DedicatedMasterType": "m3.xlarge.elasticsearch", "DedicatedMasterCount": 3}'
`
Any help would greatly appreciated

**Comment by adiberk** [comment]
Figured it out - I had to use aliases in docker

**Comment by thrau** [comment]
Ok, thanks for letting us know @adiberk :-) Glad you got it running
