### ISSUE TITLE
InvalidAccessKeyId

### ISSUE THREAD

**Issue by contactshivakumar** [localstack/localstack#5612]
### Is there an existing issue for this?

- [X] I have searched the existing issues and read the documentation

### Question

I created a lambda function (Reference: - https://docs.aws.amazon.com/cdk/v2/guide/serverless_example.html) using cdklocal and successfully deployed it.  While accessing the function  I get below error.

**"InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records.**

Please advise if there is a fix for this 

Environment
--------------
$env:AWS_ACCESS_KEY_ID="test" 
$env:AWS_SECRET_ACCESS_KEY="test"
$env:AWS_DEFAULT_REGION="us-east-1"

### Anything else?

Error
-----
"InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records.\n at Request.extractError (/tmp/localstack/zipfile.dc962354/node_modules/aws-sdk/lib/services/s3.js:710:35)\n at Request.callListeners (/tmp/localstack/zipfile.dc962354/node_modules/aws-sdk/lib/sequential_executor.js:106:20)\n at Request.emit (/tmp/localstack/zipfile.dc962354/node_modules/aws-sdk/lib/sequential_executor.js:78:10)\n at Request.emit (/tmp/localstack/zipfile.dc962354/node_modules/aws-sdk/lib/request.js:686:14)\n at Request.transition (/tmp/localstack/zipfile.dc962354/node_modules/aws-sdk/lib/request.js:22:10)\n at AcceptorStateMachine.runTo (/tmp/localstack/zipfile.dc962354/node_modules/aws-sdk/lib/state_machine.js:14:12)\n at /tmp/localstack/zipfile.dc962354/node_modules/aws-sdk/lib/state_machine.js:26:10\n at Request. (/tmp/localstack/zipfile.dc962354/node_modules/aws-sdk/lib/request.js:38:9)\n at Request. (/tmp/localstack/zipfile.dc962354/node_modules/aws-sdk/lib/request.js:688:12)\n at Request.callListeners (/tmp/localstack/zipfile.dc962354/node_modules/aws-sdk/lib/sequential_executor.js:116:18)"

**Comment by whummer** [comment]
Thanks for reporting @contactshivakumar . Please note that you'll need to configure your AWS SDK client to talk to the endpoints on `localhost`. A few more details can be found here: https://docs.localstack.cloud/tools/local-endpoint-injection/ (see the note on using `http://${LOCALSTACK_HOSTNAME}:${EDGE_PORT}` as the endpoint URL in your AWS SDK client). Hope that helps - please share more details and a few snippets of your Lambda handler if the problem persists. Thanks

**Comment by pereiraguilherme** [comment]
Hi, I'm also having this issue but using the Go AWS SDK. I first got the error 403 just like @contactshivakumar had, after adding the proper configuration on S3 client from the SDK, I was getting this error:
 `2022/03/14 20:43:18 RequestError: send request failed
caused by: Put "http://my-bucket.172.17.0.2:4566/myFile.json": dial tcp: lookup my-bucket.172.17.0.2 on 192.168.65.5:53: no such host` 
There is still more configuration need to be done after configure the SDK @whummer ? Thanks in advance!

**Comment by whummer** [comment]
Hi @pereiraguilherme, you may have to configure path-based bucket addressing (as opposed to hostname-based addressing) in your Go AWS S3 SDK. Can you please give that a try and let us know if it works? Thanks!
