### ISSUE TITLE
EC2 docker engine user-data support

### ISSUE THREAD

**Issue by BorjaSalazar** [localstack/localstack#5630]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

In order to use localstack to cover all our use cases we need support to read the user-data provided when launching an instance.

**Comment by whummer** [comment]
Hi @BorjaSalazar , thanks for reporting. We have now pushed a couple of enhancements for EC2 Docker containers (in the Pro version) which should add support for user-data scripts in EC2 Docker container. Can you please pull the `latest` Docker image and give it another try? Please keep us posted on how it goes.. Thanks!
