### ISSUE TITLE
feature request: Can you make the DOCKER_FLAGS option mutable in the Localstack Orb for CircleCI

### ISSUE THREAD

**Issue by kachaje** [localstack/localstack#5637]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Currently, the CircleCI Orb for running `Localstack` only allows `image-tag` and `install-awslocal` parameters to be customized. It will help us a lot if the `DOCKER_LOGS` option is also provided as a mutable attribute so that a user can have more control on how the Orb is used.
A case in point would be the fact that when it is executed, it locks the instance to a specific network connection mode which sometimes requires changing to fit test scenarios like where you have to change the network mode to `host` from the default.
By default, the Orb also locks all open ports to `127.0.0.1` which may not always be practical for all use cases as some cases need to access the ports from inside Docker containers and the ports will not be accessible

### 🧑‍💻 Implementation

If I had a chance to update the code, I'd modify the `start` command as follows:

- add a parameter `docker-flags` on the `parameters` section for `start` command with a default value `'-d'` which is the current default; type `string` and a description of course
- update the `DOCKER_FLAGS='-d'` part on the `steps` run command that executes `Localstack` to `DOCKER_FLAGS=<<parameters.docker-flags>>` and leave the rest as is for now

**Comment by whummer** [comment]
Thanks for reporting @kachaje . These are some great suggestions that can improve the LocalStack CircleCI Orb. 👍 

Can you please share a copy of your CircleCI config - looks like the `DOCKER_FLAGS` config should be configurable via the `environment` configuration, potentially.

> If I had a chance to update the code, I'd modify the start command as follows:

In fact, the code for the CircleCI is open source - would you mind creating a pull request against this repo? https://github.com/localstack/ci-plugin-circleci Thanks!
