### ISSUE TITLE
feature request: Support for MFA devices in Cognito-IDP

### ISSUE THREAD

**Issue by silv-io** [localstack/localstack#5638]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

The Cognito-IDP API is missing parts of the API which handle MFA devices. This leads to diverging responses when starting an authentication flow with, e.g., `AdminInitiateAuth` for user pools with MFA enabled.

**Comment by whummer** [comment]
Fixed with the latest changes implemented in Pro. 👍 🎉
