### ISSUE TITLE
question: increase GSI limit on dynamodb tables

### ISSUE THREAD

**Issue by viyatgandhi** [localstack/localstack#5672]
### Is there an existing issue for this?

- [X] I have searched the existing issues and read the documentation

### Question

How can we increase GSI limit on DynamoDB? Default is 20 (in localstack and AWS). 

On AWS we can request it for more but I don't see a way to increase it on localstack.

`│ Error: error creating DynamoDB Table: ValidationException: GlobalSecondaryIndex count exceeds the per-table limit
│ 	status code: 400, request id: 6fa820e4-7185-4803-971c-6ede1e6801fa`

**Comment by whummer** [comment]
Thanks for reporting @viyatgandhi . Can you please share some more details about your use case, and a reproducible example? (ideally a Pyhon code snippet or a sequence of `awslocal` commands). If I understand correctly, you're attempting to call the `create_table` API with a `GlobalSecondaryIndexes` parameter array containing more than 20 items, is that correct?

**Comment by giograno** [comment]
Hi @viyatgandhi, thanks for reporting the issue. We implemented a fix that you can find in the `latest` Docker image. Please let us know if other problems arise 🙏

**Comment by viyatgandhi** [comment]
@giograno Thanks for implementing the fix. I think it would be better to print warning message or keep configuration point if we want to exceed 20 GSIs on table. Although AWS provides a way to exceed the limit they review it on case by case basis. So if a user is unaware about the limitation before hand on local dev they may face problem deploying on real AWS environment. 

@whummer Sorry for not providing any details earlier. For quick background we are following DynamoDB best practices (https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/bp-general-nosql-design.html#bp-general-nosql-design-concepts) and keeping related data in single large table. To fetch, sort, filter closely related data in single table we need 20+ GSIs. To have better performance on server side we are delegating some functionality on DynamoDB vs on server itself. Hopefully this provides a context of the need.
