### ISSUE TITLE
question: Is `AWS::ApiGateway::RequestValidator` CloudFormation resource supported?

### ISSUE THREAD

**Issue by bkerzner** [localstack/localstack#5675]
### Is there an existing issue for this?

- [X] I have searched the existing issues and read the documentation

### Question

I was testing a CloudFormation template with a resource, and the API was returning a 400 with error message "Invalid Request Body" when I had a RequestValidator set up, even though the body, by all accounts, appeared to adhere to the schema in the associated `AWS::ApiGateway::Model`. Before filing a bug, wanted to make sure this is supported.

**Comment by calvernaz** [comment]
Hi @bkerzner, do you have a template you can share? or the request validator set up?

**Comment by calvernaz** [comment]
Hi @bkerzner I made a couple of simple tests (compared to yours) with the request validator and the resource was created. I don't know exactly how can I help you further, but happy to if you need to. Thanks!
