### ISSUE TITLE
bug: Cannot send an event to EventBridge from a Lambda container 

### ISSUE THREAD

**Issue by fmaronnaud** [localstack/localstack#5680]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

- Create a lambda **container** that will contain code to send an event on EventBridge
- The event is not sent to EventBridge and the Lambda is timing out (see error below)

```
localstack_main | 2022-03-15T16:35:29.720:DEBUG:localstack.utils.container_utils.docker_sdk_client: Removing container: b2a6a59ed46fa40eb4de623152e3488f26d84e27f3aa86bb1b3c348c6c6c707b
localstack_main | 2022-03-15T16:35:30.089:DEBUG:localstack.services.plugins: checking service health cloudwatch:4566
localstack_main | 2022-03-15T16:35:30.106:INFO:localstack.utils.threads: Thread run method <function LambdaExecutor.execute.<locals>.do_execute at 0x7ff8b63d2700>(None) failed: Timeout - Lambda container did not report result after 30 secs Traceback (most recent call last):
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/awslambda/lambda_extended.py.enc", line 479, in do_run_lambda_executor
localstack_main |   File "/usr/local/lib/python3.8/queue.py", line 178, in get
localstack_main |     raise Empty
localstack_main | _queue.Empty
localstack_main |
localstack_main | During handling of the above exception, another exception occurred:
localstack_main |
localstack_main | Traceback (most recent call last):
localstack_main |   File "/opt/code/localstack/localstack/utils/threads.py", line 38, in run
localstack_main |     result = self.func(self.params, **kwargs)
localstack_main |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 450, in do_execute
localstack_main |     return _run(func_arn=func_arn)
localstack_main |   File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 170, in wrapped
localstack_main |     raise e
localstack_main |   File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 166, in wrapped
localstack_main |     result = func(*args, **kwargs)
localstack_main |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 437, in _run
localstack_main |     raise e
localstack_main |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 433, in _run
localstack_main |     result = self._execute(lambda_function, inv_context)
localstack_main |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 756, in _execute
localstack_main |     result = self.run_lambda_executor(lambda_function=lambda_function, inv_context=inv_context)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/awslambda/lambda_extended.py.enc", line 565, in run_lambda_executor
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/awslambda/lambda_extended.py.enc", line 461, in run_lambda_executor
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/awslambda/lambda_extended.py.enc", line 486, in do_run_lambda_executor
localstack_main | localstack.services.awslambda.lambda_executors.InvocationException: Timeout - Lambda container did not report result after 30 secs
```

### Expected Behavior

- Create a lambda container image that will contain code to send an event on EventBridge
- The event is sent to EventBridge and the lambda complete properly

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

 `docker-compose up`
 ```
 version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    network_mode: bridge
    ports:
      - "127.0.0.1:53:53"                # only required for Pro
      - "127.0.0.1:53:53/udp"            # only required for Pro
      - "127.0.0.1:447:443"              # only required for Pro
      - "127.0.0.1:4510-4530:4510-4530"  # only required for Pro
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4571:4571"
    environment:
      - SERVICES=${SERVICES- }
      #- DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - LAMBDA_EXECUTOR=docker     
      - LOCALSTACK_API_KEY=XXXXXXXXX
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=C:\ltmp
      - DOCKER_FLAGS=1
      - EXTRA_CORS_ALLOWED_HEADERS=sentry-trace
      #- LAMBDA_DOCKER_NETWORK=development
    volumes:
      - 'C:\ltmp:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
  
volumes:
  localstack-vol:
 ```
    

##### AWS SDK code snippet

Ultimately, the following method is timing out (https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/EventBridge/MEventBridgePutEventsAsyncPutEventsRequestCancellationToken.html):
```
Amazon.EventBridge.Model.PutEventsResponse eventsResponse = await Client.PutEventsAsync(request);
```

### Environment

```markdown
- OS: Windows
- LocalStack: latest
```

### Anything else?

- Note that when the same stack is deployed to AWS, it is working as expected
- The same thing happens with the default or a custom bus

**Comment by whummer** [comment]
Thanks for reporting @fmaronnaud, and apologies for the long delay. Can you please share some details about the logic in your Lambda container - please note that the EventBridge client would need to be configured to use `http://$LOCALSTACK_HOSTNAME:4566` as the endpoint URL (reading `LOCALSTACK_HOSTNAME` from the environment). 

Also, we have recently pushed a number of enhancements for the Lambda container image execution - can you please pull the `latest` Docker image and confirm if the problem still persists? Thanks for your help!

**Comment by fmaronnaud** [comment]
Hello @whummer, thank you for getting back to me, and no worries for the delay. I updated my Localstack to the latest and was able to see a different error message. Updating the service URL to the Localstack hostname/port was what ultimately made everything work. Sorry about the false alarm and thank you for your help

**Comment by kalki7** [comment]
@fmaronnaud I'm having a similar issue at the moment using javascript
`import { Context, APIGatewayProxyResult, APIGatewayEvent } from 'aws-lambda';
import { EventBridgeClient, PutEventsCommand} from "@aws-sdk/client-eventbridge";

const ebClient = new EventBridgeClient({ endpoint :'http://localhost:4566'})
const data = await ebClient.send(new PutEventsCommand(params));
`

I'm getting the error message as follows : 
connect ECONNREFUSED 127.0.0.1:4566

Could you please elaborate on what you'd updated in the service URL that got it to work. TIA
