### ISSUE TITLE
bug: Unable to Query Athena after upgrading to latest

### ISSUE THREAD

**Issue by jmdotnet** [localstack/localstack#5683]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After updating to the latest version of Localstack and localstack/bigdata images, I now get the following error running Athena queries:

```
localstack_main | 2022-03-15T23:48:01.207:INFO:localstack_ext.services.athena.provider: Athena error for query "test 1,2,3":
localstack_main | ('Exec command returned with exit code 1', None, b"cp: '/usr/local/hadoop-2.9.2/share/hadoop/tools/lib/aws-java-sdk-bundle-1.11.199.jar' and '/usr/local/apache-hive-2.3.5-bin/lib/aws-java-sdk-bundle-1.11.199.jar' are the same file\ncp: '/usr/local/hadoop-2.9.2/share/hadoop/tools/lib/hadoop-aws-2.9.2.jar' and '/usr/local/apache-hive-2.3.5-bin/lib/hadoop-aws-2.9.2.jar' are the same file\n") Traceback (most recent call last):
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/utils/hadoop.py.enc", line 182, in start_hadoop_spark_container
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/utils/hadoop.py.enc", line 159, in run_in_spark
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/utils/hadoop.py.enc", line 164, in run_in_container
localstack_main |   File "/opt/code/localstack/localstack/utils/container_utils/docker_sdk_client.py", line 642, in exec_in_container
localstack_main |     raise ContainerException(
localstack_main | localstack.utils.container_utils.container_client.ContainerException: ('Exec command returned with exit code 1', None, None)
localstack_main | 
```

Before updating to latest, queries were running successfully.  I tried clearing out all related docker images/volumes/containers still get this error every time a query is run.  

Below are the logs when localstack starts up:

`localstack_main | Waiting for all LocalStack services to be ready
localstack_main | 2022-03-16 00:07:52,768 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
localstack_main | 2022-03-16 00:07:52,771 INFO supervisord started with pid 14
localstack_main | 2022-03-16 00:07:53,774 INFO spawned: 'infra' with pid 20
localstack_main | 2022-03-16 00:07:55,332 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
localstack_main | 
localstack_main | LocalStack version: 0.14.1
localstack_main | LocalStack Docker container id: 3772c542329b
localstack_main | LocalStack build date: 2022-03-15
localstack_main | LocalStack build git hash: 4d199cac
localstack_main | 
localstack_main | 2022-03-16T00:07:55.331:INFO:localstack_ext.bootstrap.licensing: Successfully activated API key
localstack_main | Starting mock Azure APIs (port 12121)
localstack_main | Starting DNS servers (tcp/udp port 53 on 0.0.0.0)...
localstack_main | Starting edge router (http port 4566)...
localstack_main | Starting edge router (https port 443)...
localstack_main | Ready.
localstack_main | [2022-03-16 00:07:57 +0000] [20] [INFO] Running on https://0.0.0.0:12121 (CTRL + C to quit)
localstack_main | 2022-03-16T00:07:57.724:INFO:hypercorn.error: Running on https://0.0.0.0:12121 (CTRL + C to quit)
localstack_main | 2022-03-16T00:07:57.930:INFO:localstack_ext.utils.aws.metadata_service: Starting AWS instance metadata service on port 80
localstack_main | 2022-03-16T00:07:57.948:INFO:botocore.credentials: Found credentials in environment variables.
localstack_main | 2022-03-16T00:07:57.958:INFO:botocore.credentials: Found credentials in environment variables.
localstack_main | [2022-03-16 00:07:58 +0000] [20] [INFO] Running on https://0.0.0.0:4566 (CTRL + C to quit)
localstack_main | 2022-03-16T00:07:58.099:INFO:hypercorn.error: Running on https://0.0.0.0:4566 (CTRL + C to quit)
localstack_main | [2022-03-16 00:07:58 +0000] [20] [INFO] Running on https://0.0.0.0:443 (CTRL + C to quit)
localstack_main | 2022-03-16T00:07:58.111:INFO:hypercorn.error: Running on https://0.0.0.0:443 (CTRL + C to quit)`

### Expected Behavior

Query completes successfully.  

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

**_docker-compose.yml_**

```
version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    network_mode: bridge
    ports:
      - "127.0.0.1:53:53"                # only required for Pro (DNS)
      - "127.0.0.1:53:53/udp"            # only required for Pro (DNS)
      - "127.0.0.1:443:443"              # only required for Pro (LocalStack HTTPS Edge Proxy)
      - "127.0.0.1:4510-4559:4510-4559"  # external service port range
      - "127.0.0.1:4566:4566"            # LocalStack Edge Proxy
    environment:
      - SERVICES=${SERVICES-}
      - DEBUG=${DEBUG-}
      - DATA_DIR=${DATA_DIR-}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY-}
      - HOST_TMP_FOLDER=${TMPDIR:-/tmp/}localstack
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    docker-compose up

    awslocal athena start-query-execution --query-string 'SELECT 1, 2, 3'

### Environment

```markdown
- OS: MacOs
- LocalStack: Latest
```

### Anything else?

Docker Images:
localstack/localstack                           latest    cf376df7e3bd   4 hours ago     1.48GB
localstack/bigdata                              latest    95705cf5d219   14 hours ago    3.79GB

**Comment by viren-nadkarni** [comment]
Thanks for reporting this @jmdotnet . We're working on this and will release a fix very soon.

**Comment by viren-nadkarni** [comment]
@jmdotnet We have fixed the problem in `latest` build of `localstack/localstack`

**Comment by jmdotnet** [comment]
Just installed the latest build and was able to successfully query via Athena. Thank you!
