### ISSUE TITLE
feature request: API action 'ModifyVolume' for service 'ec2'

### ISSUE THREAD

**Issue by hyurii** [localstack/localstack#5684]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Trying to resize ebs volume I got an error:
An error occurred (InternalFailure) when calling the ModifyVolume operation: API action 'ModifyVolume' for service 'ec2' not yet implemented.

It looks like resizing volumes are not supported in localstack at the moment.

**Comment by kowalczykp** [comment]
Looking forward for this feature, are there any plans/estimates about when this can be delivered? Thanks in advance
