### ISSUE TITLE
bug: error on lambda layers when data persistence is activated

### ISSUE THREAD

**Issue by tvallois** [localstack/localstack#5685]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We're using localstack pro with lambda layers. `DATA_DIR` env var is defined because we need to persist S3, SQS and other services data. To apply the aws infrastructure in localstack, we use Terraform.

At the first terraform apply executation, everything works fine, layers are created and can be used without any issues however if we reset localstack docker, localstack is unable to find user code for layer. Error: 

`arn:aws:lambda:eu-west-1:000000000000:layer:python_38_ffmpeg: 'NoneType' object has no attribute 'get`

@dfangl 

### Expected Behavior

Localstack should restart without any issues and should be able to find lambda layers again.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)
docker-compose.yml:
   ```
  localstack:
    container_name: "localstack"
    image: localstack/localstack
    ports:
      - '4566-4583:4566-4583'
    env_file:
      - .env
    environment:
      - SERVICES=lambda,s3,dynamodb,sqs
      - DEBUG=true
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LAMBDA_EXECUTOR=docker-reuse
      - LAMBDA_DOCKER_NETWORK=dev-network
      - TMPDIR=/opt/code/localstack/localstack/data
      - DATA_DIR=/opt/code/localstack/localstack/data
      - HOSTNAME_EXTERNAL=localstack
    volumes:
      - "./data/localstack:/opt/code/localstack/localstack/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - dev-network
   ```
    docker compose up -d localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

terraform apply with `aws_lambda_function` with lambda_layers

### Environment

```markdown
- OS: Ubuntu 20.04
- LocalStack: latest
```

**Comment by dfangl** [comment]
There was a recent update regarding Lambda persistence, especially for layers. Could you try pulling from localstack/localstack:latest and check again?

**Comment by tvallois** [comment]
Yes, the problem is gone. Thanks !
