### ISSUE TITLE
bug: SQS with SSE times out

### ISSUE THREAD

**Issue by alekspickle** [localstack/localstack#5693]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It's basically the same as #5197 but this time with new-ish SSE configuration which was added in #5366.

I have a simple terraform project 
```
resource "aws_sqs_queue" "my_queue" {
  name                      = "my_queue_name"
  sqs_managed_sse_enabled = true
 }

```

### Expected Behavior

sqs queue created without problem

### How are you starting LocalStack?

With a `docker run` command

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal s3 mb s3://mybucket

### Environment

```markdown
- OS: Linux
- LocalStack: 0.12.17.3
- Terraform AWS provider: 4.3.0
- terraform: 1.0.0
```

### Anything else?
Yep, this reproduces in `localstack:0.14.1` as well

**Comment by thrau** [comment]
potentially fixed by #6572, will try later

**Comment by thrau** [comment]
seems to indeed work now with `latest`. Aleks @alekspickle, could you please give it a try with the latest docker image?

**Comment by alekspickle** [comment]
Yep, with latest version seems to be working!
