### ISSUE TITLE
EventBridge event-pattern not correctly matched on detail content

### ISSUE THREAD

**Issue by SolomkaRuslan** [localstack/localstack#5701]
### Is there an existing issue for this?

- [x] I have searched the existing issues

#### This is a similar issue to already closed [#3369](https://github.com/localstack/localstack/issues/3369)
It looks like the event pattern of EventBridge is not applied correctly on the detail field when the value is a nested object or a completely different object.

### Expected Behavior

The provided example does not put messages in SQS.

### How are you starting LocalStack?

With a docker-compose file

### The following scripts return two items in SQS, but should not.

    awslocal events create-event-bus \
    --name detail-bus-1

    awslocal sqs create-queue \
    --queue-name "detail-sqs-1"

    awslocal events put-rule \
    --name "detail-rule-1" \
    --event-bus-name "detail-bus-1" \
    --event-pattern '{ "detail": { "event": { "data": { "type": ["1"] } } } }'

    awslocal events put-targets \
    --rule "detail-rule-1" \
    --event-bus-name "detail-bus-1" \
    --targets "Id"="detail-target-rule-1","Arn"="arn:aws:sqs:us-east-1:000000000000:detail-sqs-1","InputPath"="$.detail"

    awslocal events put-events --entries '[{"DetailType": "test", "Source": "aws.test", "Detail": "{ \"event\": {\"data\": {\"type\": \"2\"} } }", "EventBusName": "detail-bus-1"}]'

    awslocal events put-events --entries '[{"DetailType": "test", "Source": "aws.test", "Detail": "{ \"hello\": \"world\" }", "EventBusName": "detail-bus-1"}]'

    awslocal sqs receive-message --queue-url http://localhost:4566/000000000000/detail-sqs-1 --max-number-of-messages 10

### Environment

```markdown
- OS: Ubuntu 20.04
- LocalStack: latest
```

**Comment by whummer** [comment]
Hi @SolomkaRuslan , thanks for reporting, and apologies for the long delay. This should be fixed in the meantime - can you please pull the `latest` Docker image and give it another try? Please keep us posted on how it goes.. Thanks!
