### ISSUE TITLE
feature request: KMS - support importing keys

### ISSUE THREAD

**Issue by davecardwell** [localstack/localstack#5702]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

https://docs.aws.amazon.com/kms/latest/developerguide/importing-keys-get-public-key-and-token.html

When importing your own KMS key you must call `GetParametersForImport` to retrieve an import token and the public key with which to encrypt your key material prior to submission.

As of LocalStack v0.14.1 this results in the error:
> API action 'TrentService.GetParametersForImport' for service 'kms' not yet implemented`

Blocked at this point I was unable to test if `ImportKeyMaterial` also needs implementing.

### Anything else?

It looks like there is some prior work here that may be helpful: https://github.com/nsmithuk/local-kms

**Comment by whummer** [comment]
Hi @davecardwell , an initial version of KMS key import has been added in #5735 . Can you please pull the `latest` Docker image and give it a try? Please keep us posted on how it goes.. Thanks!

**Comment by whummer** [comment]
Closing as resolved - please let us know if the problem persist or if anything else is needed. Thanks!

**Comment by davecardwell** [comment]
Apologies, @whummer. I’ve been out of the office then catching up, so only just got to this.

In attempting to test this it seems that the `KMS_PROVIDER=local-kms` environment variable no longer works, and it attempts to use moto. I had come to rely on this and their support for an `/init/seed.yaml` file which my LocalStack install no longer picks up.

**Comment by davecardwell** [comment]
Raised #5792 - will retest the import once I can get past that.
