### ISSUE TITLE
Detect `localstack` target in terraform

### ISSUE THREAD

**Issue by Veetaha** [localstack/localstack#5705]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

We are using the following code to heuristically detect wether the current deployment goes to localstack process in our terraform code:

```tf
data "aws_caller_identity" "current" {}
output "is_localstack" {
  value = data.aws_caller_identity.current.id == "000000000000"
}
```

However, it's not reliable, `localstack` may change the implementation details and assign different user ID there, that's we would like to have other way of detecting that the deployment goes to `localstack` in terraform.

### 🧑‍💻 Implementation

I am not sure what the best way to implement it is. One option is that `localstack` could maintain a community terraform module that hides that logic under the hood, or use some existing metadata data source of AWS to expose that in a documented way to users. For example, the [`description` field ](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/region#description)of `data "aws_region"` could contain the word `localstack`.

**Comment by whummer** [comment]
Thanks for reporting @Veetaha . Actually, I think your approach with the check based on account ID actually makes sense. You can configure the AWS account ID via the `TEST_AWS_ACCOUNT_ID` environment variable, and you can rely on the default value to be present (at least in the foreseeable future).

The other approach using region description does not seem to work. Running the following minimal example: 
```
data "aws_region" "current" {}

output "is_localstack" {
  value = data.aws_region.current.description
}
```
... with debug logging:
```
TF_LOG=debug tf apply
```
... yields this output:
```
Changes to Outputs:
  + is_localstack = "Europe (Frankfurt)"
```
... however, no requests are being made to LocalStack itself (so, it seems like the description mapping is hardcoded in Terraform itself).

**Comment by Veetaha** [comment]
We have this terraform module as a workaround today. Maybe it should be documented? I am not sure we can rely on such behavior 🤔 

```hcl
# Note: created issue to track progress on how to detect localstack from terraform
# https://github.com/localstack/localstack/issues/5705

data "aws_caller_identity" "current" {}

output "is_localstack" {
  value = data.aws_caller_identity.current.id == "000000000000"
}
```

**Comment by HarshCasper** [comment]
We have documented this here: https://github.com/localstack/docs/pull/999
