### ISSUE TITLE
bug: KMS Sign returns Unknown Error when using Lambda Containers

### ISSUE THREAD

**Issue by LukaHedt** [localstack/localstack#5716]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When attempting to sign some document using Localstack KMS inside a lambda container (also running on localstack), the localstack KMS listener returns some unknown error.

The KMS key and lambda containers have been created from the same CDK app deploy, and I can see all the resources in the localstack web console.

The test application I'm using to prove this behaviour is available here:
https://github.com/LukaHedt/localstack_kms_test

Instructions to run are in the main Readme, and the `/localstack/Readme.md` file.

`aws-sdk` returns an unknown error, and the localstack docker logs that I receive are available here:
https://pastebin.com/58Z3fXi3

Have done an amount of testing and can confidently claim the following:
- Have tested on multiple machines with the same outcome
- Doesn’t make a difference if I specify an ARN or a KeyID in the signing request
- Downgrading localstack versions either didn’t make a difference, or I couldn’t actually deploy a localstack container with version 0.12.20 or lower.

### Expected Behavior

KMS Sign should return a signature for the given payload.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

Test application demonstrating the current behaviour is available here:

https://github.com/LukaHedt/localstack_kms_test

Full instructions to run are in the `/localstack/Readme.md` file.

### Environment

```markdown
- OS: MacOS Monteray 12.3
- LocalStack: 0.14.0
```

**Comment by whummer** [comment]
Hi @LukaHedt , thanks for reporting. We have now pushed a couple of enhancements for KMS, which should (hopefully) get this issue resolved. Can you please pull the `latest` Docker image and give it another try? With the latest image, we were able to run your example end-to-end (with the Lambda function performing the `Sign` operation). Please let us know if the problem persists.. Thanks!

**Comment by LukaHedt** [comment]
The latest docker image seems to have solved this issue.

Thankyou!!
