### ISSUE TITLE
bug: AWS Athena prepared statement not saved

### ISSUE THREAD

**Issue by lakshmigirijatalagadadeevi** [localstack/localstack#5727]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I created a prepared statement using this statement -

PREPARE prep_stmt FROM
SELECT * FROM "dbname"."tablename" WHERE columnname = ? ORDER BY columnname desc

![image](https://user-images.githubusercontent.com/10536730/159550024-82519afa-0306-4696-a8e9-347b8f6119cb.png)

Works fine. 

```
localstack_main  | 2022-03-22T18:18:30.181:INFO:localstack_ext.services.athena.provider: Running Athena query ID "0f8f394f": PREPARE prep_stmt FROM
localstack_main  | SELECT * FROM "dbname"."tablename" WHERE columnname = ? ORDER BY columnname desc
localstack_main  | 
localstack_main  | 2022-03-22T18:18:59.616:INFO:localstack_ext.services.athena.provider: Creating default Athena results bucket aws-athena-query-results-000000000000-us-east-1
```
Now I try to EXECUTE the prepared statement using this query -

```
EXECUTE prep_stmt USING 'test'
```

I get the following error -

```
 2022-03-22T18:19:03.995:INFO:localstack_ext.services.athena.provider: Athena error for query "EXECUTE prep_stmt USING 'test'
localstack_main  | ":
localstack_main  | Unable to get result from Presto server after 10 retries: PrestoUserError(type=USER_ERROR, name=NOT_FOUND, message="Prepared statement not found: prep_stmt", query_id=20220322_175438_00023_48imq) Traceback (most recent call last):
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/athena/provider.py.enc", line 57, in _run_query
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/athena/query_utils.py.enc", line 37, in execute_query
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/utils/hadoop.py.enc", line 318, in execute_presto_query
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/utils/hadoop.py.enc", line 353, in execute_presto_queries
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/utils/hadoop.py.enc", line 349, in run_with_retries
localstack_main  | Exception: Unable to get result from Presto server after 10 retries: PrestoUserError(type=USER_ERROR, name=NOT_FOUND, message="Prepared statement not found:prep_stmt", query_id=20220322_175438_00023_48imq)
```

### Expected Behavior

Ideally the prepared statement should save and execute should work.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal s3 mb s3://mybucket

awslocal athena start-query-execution --query-string "CREATE DATABASE dbname"

awslocal s3 cp ./data.csv s3://datalake // upload test csv to s3

### Environment

```markdown
- OS: macOS Monterey 12.0.1
- LocalStack: latest
```

**Comment by whummer** [comment]
Hi @lakshmigirijatalagadadeevi , thanks for reporting, and apologies for the very long delay. We have now added support for prepared statements in Athena - can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists, or if there are any other issues.. Thanks!
