### ISSUE TITLE
bug: EventBridge oauth http parameters are not being used correctly when requesting a token to call an API destination

### ISSUE THREAD

**Issue by andrew-ubco** [localstack/localstack#5729]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am using an EventBridge API destination and a connection that is authenticated using oauth. The authentication is not working - in the logs I receive:

```
2022-03-22T21:30:03.668:DEBUG:localstack.utils.aws.message_forwarding: Calling EventBridge API destination (state "ACTIVE"): POST http://...

2022-03-22T21:30:04.538:INFO:localstack.services.events.events_starter: Unable to send event notification {'version': '0', 'id': 'ae52c3c1-627c-47c7-a19b-80030ba9a5eb', 'detail-type': 'MyEvent',... to target {'Id': 'Webhook', 'Arn': 'arn:aws:events:ap-southeast-2:000000000000:api-destination/MyDestination/84cf2309-57c9-4d39-af65-2bc36639d01a', 'RoleArn': 'arn:aws:iam::000000000000:role/service-role/MyRole'}: Invalid return character or leading space in header: authorization
```

I believe this is due to incorrect handling of the OAuthHttpParameters (and this fails for me as I need to set audience and grant_type in my token requests). 

The structure of the OAuthParameters property of a connection (see https://docs.aws.amazon.com/eventbridge/latest/APIReference/API_CreateConnection.html) is actually:

```
      "OAuthParameters": { 
         "AuthorizationEndpoint": "string",
         "ClientParameters": { 
            "ClientID": "string",
            "ClientSecret": "string"
         },
         "HttpMethod": "string",
         "OAuthHttpParameters": { 
            "BodyParameters": [ 
               { 
                  "IsValueSecret": boolean,
                  "Key": "string",
                  "Value": "string"
               }
            ],
            "HeaderParameters": [ 
               { 
                  "IsValueSecret": boolean,
                  "Key": "string",
                  "Value": "string"
               }
            ],
            "QueryStringParameters": [ 
               { 
                  "IsValueSecret": boolean,
                  "Key": "string",
                  "Value": "string"
               }
            ]
         }
      }
```

I may be wrong, but it looks to me like the code in [auth_keys_from_connection](https://github.com/localstack/localstack/blob/master/localstack/utils/aws/message_forwarding.py#L174-L204) is trying to read `BodyParameters`, `HeaderParameters`, and `QueryStringParameters` as properties directly on `OAuthParameters` (ie. the same level as `ClientParameters`), when they are actually sub-properties of `OAuthHttpParameters`.

This (for me) results in the token request failing, and hence the above error about the `authorization` header (as no `token_type` or `access_token` is received from the token endpoint).

(Also, the integration test for this behaviour doesn't use these additional parameters).

### Expected Behavior

I expected the body parameters from the oauth http parameters to be sent correctly to the token server, and then I would receive a valid access_token to be used in the calls from EventBridge to my API destination.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

`docker compose up -d` using the standard docker-compose.

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```
awslocal events create-event-bus --name MyBus

awslocal events create-connection \
  --name MyConnection \
  --authorization-type OAUTH_CLIENT_CREDENTIALS \
  --auth-parameters "{\"OAuthParameters\":{\"AuthorizationEndpoint\":\"https://auth/token\",\"HttpMethod\":\"POST\",\"ClientParameters\":{\"ClientID\":\"MyClientId\",\"ClientSecret\":\"MyClientSecret\"},\"OAuthHttpParameters\":{\"BodyParameters\":[{\"Key\":\"audience\",\"Value\":\"https://auth/audience\"},{\"Key\":\"grant_type\",\"Value\":\"client_credentials\"}]}}}"

awslocal events create-api-destination \
    --name MyApiDestination \
    --connection-arn "arn-from-connection-created-above" \
    --http-method POST \
    --invocation-endpoint "http://my/endpoint"

awslocal events put-rule \
    --name MyRule \
    --event-bus-name MyBus \
    --event-pattern "{\"detail-type\":[\"MyEvent\"]}"

awslocal events put-targets \
    --rule MyRule \
    --event-bus-name MyBus \
    --targets "Id"="Webhook","Arn"="arn-from-api-destination-created-above"

awslocal events put-events --entries '[{"Source": "MySource", "DetailType": "MyEvent", "EventBusName": "MyBus", "Detail": "{ \"data\": {\"key\": \"value\" }}"}]'
```

(Obviously above I have replace client ID, secret, etc)

### Environment

```markdown
- OS: Debian 10 (WSL)
- LocalStack: 0.14.1
```

**Comment by pinzon** [comment]
hi @andrew-ubco, thank you for reporting the problem, the solution has been merged.
