### ISSUE TITLE
bug: Bootstrapping fails when run a second time

### ISSUE THREAD

**Issue by jonathanbyrne** [localstack/localstack#5732]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

When `cdklocal bootstrap` is run a second time, it fails trying to deploy CDKToolkit.

<img width="1092" alt="image" src="https://user-images.githubusercontent.com/3814989/159690147-a7981934-7623-4047-9c45-78e7776d2b53.png">

### Expected Behavior

I'm fairly new to CDK, but I would imagine that it should not fail.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

Here is my `docker-compose.yaml` file, although it occurs with the default file as well.

```
version: "3.8"

services:
  localstack:
    container_name: "localstack-lenderreporting"
    image: localstack/localstack
    network_mode: bridge
    ports:
      - "127.0.0.1:53:53"
      - "127.0.0.1:53:53/udp"
      - "127.0.0.1:443:443"
      - "127.0.0.1:4510-4559:4510-4559"
      - "127.0.0.1:4566:4566"
    environment:
      - DISABLE_CORS_CHECKS=1
      - MAIN_CONTAINER_NAME=localstack-lenderreporting
      - SERVICES=lambda,sqs,dynamodb,s3,ses,sts,cloudformation,ssm,iam,kms,secretsmanager,ecr,sns,acm,apigateway,route53
      - DEBUG=0
      - DATA_DIR=/tmp/localstack/data
      - LAMBDA_EXECUTOR=local
      - HOST_TMP_FOLDER=/tmp/localstack
      - EXTRA_CORS_ALLOWED_ORIGINS=app://.
    volumes:
      - localstack:/tmp/localstack
volumes:
  localstack:
    name: localstack-lender-reporting
  dockersock:
    name: dockersock-lender-reporting
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```
mkdir /tmp/test; cd /tmp/test
cdklocal init sample-app --language=typescript
cdklocal synth
cdklocal bootstrap
cdklocal deploy
cdklocal bootstrap
```

### Environment

```markdown
- OS: Windows 11
- LocalStack: 0.14.2 (latest as of 03/23/2022)
- AWS CLI: aws-cli/2.4.21 Python/3.8.8 Windows/10 exe/AMD64 prompt/off
- CDK: 2.15.0
- CDKLocal: 2.15.0
```

**Comment by m1n9o** [comment]
I met the problem with `cdklocal` 2.17.0 (build f9cd009).

**Comment by dominikschubert** [comment]
Should be fixed in recent versions. Let us know if you still encounter a create failure when re-bootstrapping.
