### ISSUE TITLE
bug: DynamoDB PartiQL integration can not process `IS NOT MISSING`

### ISSUE THREAD

**Issue by scorpio-13** [localstack/localstack#5736]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

While running a select query 
```sql
SELECT * FROM <TABLE_NAME> WHERE <ATTR_NAME> IS NOT MISSING
```
Gives an error
```log
An error occurred (InternalFailure) when calling the ExecuteStatement operation (reached max retries: 2): The request processing has failed because of an unknown error, exception or failure
```

However, if we run (same query without `NOT`)
```sql
SELECT * FROM <TABLE_NAME> WHERE <ATTR_NAME> IS MISSING
```
it works fine

### Expected Behavior

The Keyword `NOT` should be allowed in query to return desired results from the table, as it is supported in the DynamoDB console.

![image](https://user-images.githubusercontent.com/20901523/159820966-43b9846f-8248-4893-96a7-b89f4dfbd946.png)

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

   aws --endpoint-url http://localhost:4566 dynamodb execute-statement --statement "SELECT * FROM <TABLE_NAME> WHERE <ATTR_NAME> IS NOT MISSING"

### Environment

```markdown
- OS: MacOS(Monterey 12.3)
- LocalStack: latest
```

**Comment by giograno** [comment]
Hi @scorpio-13, many thanks for reporting this issue!
We added an integration test covering your use case (with the commit f9aa2f55321cffde31f098b190715cc3be9a9096). 
The feature should be now covered. You could pull the `latest` Docker image and give it a try.
