### ISSUE TITLE
bug: MessageGroupId truncated to single character when batch publishing on SNS FIFO Topic forwarded to subscribed SQS FIFO Queue

### ISSUE THREAD

**Issue by jwriley** [localstack/localstack#5746]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When publishing a batch of messages on an SNS FIFO topic for which there is a subscribed SQS FIFO queue, the MessageGroupId that is passed to the SQS FIFO queue will only contain the first character of the MessageGroupId that was provided to SNS. I think It is in [this line](https://github.com/localstack/localstack/blob/master/localstack/services/sns/sns_listener.py#L536) that the truncation is occurring. The result of this is that when using the example MessageGroupIds as found in [this AWS documentation](https://docs.aws.amazon.com/sns/latest/dg/fifo-message-grouping.html) all of the messages sent to SQS will have the same MessageGroupId (`p`) and thus the receiving of messages from the queue will be restricted to a single thread.

You can see this happening in the steps to reproduce section where the `MessageGroupId` attribute of the received SQS message is only `m` even though the provided `MessageGroupId` was `myMessageGroupId`.

It is also worth noting that this same behavior is not exhibited when publishing messages using the non-batched publish variant.

### Expected Behavior

The MessageGroupId should be forwarded from the SNS FIFO Topic to the SQS FIFO Queue.

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    /usr/local/bin/localstack start

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)
```
    awslocal sns create-topic --name my-topic.fifo --attributes FifoTopic=true
    # {
    #    "TopicArn": "arn:aws:sns:us-east-1:000000000000:my-topic.fifo"
    #}
    awslocal sqs create-queue --queue-name my-queue.fifo --attributes FifoQueue=true;
    # {
    #     "QueueUrl": "http://localhost:4566/000000000000/my-queue.fifo"
    # }
    awslocal sns subscribe --topic-arn arn:aws:sns:us-east-1:000000000000:my-topic.fifo --protocol sqs --notification-endpoint http://localhost:4566/000000000000/my-queue.fifo
    # {
    #    "SubscriptionArn": "arn:aws:sns:us-east-1:000000000000:my-topic.fifo:a423ba9b-1c0e-43b4-8449-cc8b07a63992"
    # }
    awslocal sns publish-batch --topic-arn arn:aws:sns:us-east-1:000000000000:my-topic.fifo --publish-batch-request-entries Id=myId,Message=myMessage,MessageGroupId=myMessageGroupId,MessageDeduplicationId=myMessageDeduplicationId
    # {
    #   "Successful": [
    #      {
    #           "Id": "myId",
    #           "MessageId": "f9ae1e43-63a0-42f6-88d1-954455ab30d4"
    #      }
    #  ],
    #  "Failed": [] 
    # }
    awslocal sqs receive-message --queue-url http://localhost:4566/000000000000/my-queue.fifo --attribute-name All
    # {
    # "Messages": [
    #     {
    #         "MessageId": "42ba95c7-9e80-3ba9-e896-deca7e4775b4",
    #         "ReceiptHandle": "ltppdoqgfgyuyvyxzozupbrqkzornlqdzcdjqdgesytvaofbotvkgmdmmhpczdficqxrwqemrsxylipaeagmtzemytoetpzujdgevfrvnhwnckujhyetalfbpbyoxttjycswpxmxtaewqbnouoxypouwhbekkbarrumkquheurpjqtsvlmcswntme",
    #         "MD5OfBody": "4a05d1186559fe66dfda6a2ddfc5c910",
    #         "Body": "{\"Type\": \"Notification\", \"MessageId\": \"f9ae1e43-63a0-42f6-88d1-954455ab30d4\", \"TopicArn\": \"arn:aws:sns:us-east-1:000000000000:my-topic.fifo\", \"Message\": \"myMessage\", \"Timestamp\": \"2022-03-24T17:32:07.876Z\", \"SignatureVersion\": \"1\", \"Signature\": \"EXAMPLEpH+..\", \"SigningCertURL\": \"https://sns.us-east-1.amazonaws.com/SimpleNotificationService-0000000000000000000000.pem\", \"Subject\": null}",
    #         "Attributes": {
    #             "SenderId": "AIDAIT2UOQQY3AUEKVGXU",
    #             "SentTimestamp": "1648143127882",
    #             "ApproximateReceiveCount": "1",
    #             "ApproximateFirstReceiveTimestamp": "1648143154188",
    #             "MessageGroupId": "m"
    #         }
    #     }
    # ]
    #}
```

### Environment

```markdown
- OS: osX 12.2.1
- LocalStack: 0.14.1
```

**Comment by thrau** [comment]
should be fixed by #5751
