### ISSUE TITLE
Web Console: Lambda - Allow expanding lambda logs

### ISSUE THREAD

**Issue by LukaHedt** [localstack/localstack#5747]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Currently the Localstack Web Console truncates long logs in the lambda page.

Ideally, a method of viewing the entire log would be ideal. Even better if it can parse JSON type logs.

### 🧑‍💻 Implementation

The web console needs to simply remove or alter the log truncation code.

Or offer an expansion like the AWS Web console does wherein it shows the entire log, as parsed json if required.

**Comment by pandomic** [comment]
@MarcelStranak , @dfangl I think we already rolled out an improved logs view in April.
We can iterate further later and add an ANSI escape character parser and maybe a JSON parser/preview.
