### ISSUE TITLE
bug: TLS Handshake Failure 

### ISSUE THREAD

**Issue by agfunderburg10** [localstack/localstack#5749]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When making a curl call to against localstack in a container, it causes localstack to die and restart. 

I am using a Mac M1 that has been upgraded to Monterey 12.3.

From what I can tell, this is related to the security cipher that curl uses, as the browser works correct, and I can get it to work correctly if I force a specific cipher that matches the browser. ie 
`curl -v -k --ciphers TLS_AES_256_GCM_SHA384 https://localhost:4566/health`

### Expected Behavior

The localstack service should not crash and restart. 

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

I am using the default docker-compose in the master branch.

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker-compose up -d

#### Steps to reproduce:

- Clone localstack project locally
- Run `docker-compose up -d`
- run this command `curl -v -k https://localhost:4566/health`

Expected: A response would be returned with the service health.
Actual: 
```
*   Trying 127.0.0.1:4566...
* Connected to localhost (127.0.0.1) port 4566 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* (304) (OUT), TLS handshake, Client hello (1):
* LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to localhost:4566 
* Closing connection 0
curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to localhost:4566 
```

Important Note: Visiting it in the browser is successful. Also, forcing the cipher is successful.

### Environment

```markdown
- OS: MacOS Monterey 12.3
- LocalStack: latest
- curl --version

curl 7.79.1 (x86_64-apple-darwin21.0) libcurl/7.79.1 (SecureTransport) LibreSSL/3.3.5 zlib/1.2.11 nghttp2/1.45.1
Release-Date: 2021-09-22
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS GSS-API HSTS HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz MultiSSL NTLM NTLM_WB SPNEGO SSL UnixSockets
```
```


### Anything else?

I spent the day attempting to debug this directly in the container to find the root of the issue. However, it appears to die before the request ever even makes it to the localstack python code (as that's where I was debugging). I wasn't sure where to troubleshoot further or find logs additional logs. The only info that shows up in the localstack logs is this:
```
2022-03-24 13:26:41,955 INFO exited: infra (terminated by SIGSEGV; not expected)
2022-03-24 13:26:42,969 INFO spawned: 'infra' with pid 5130
```

If you need more troubleshooting info, please let me know.

**Comment by sgtoj** [comment]
I can reproduce. Confirmed it is the cipher. However, it's the same cipher used by default on Apple M1 once it upgraded to the MacOS 12.3.

**Comment by silv-io** [comment]
The cipher used by macOS 12.3 (without using Rosetta) seems to be `AEAD-CHACHA20-POLY1305-SHA256`

**Comment by dfangl** [comment]
Sorry for the long wait on this one. We've just been able to reproduce this, and are looking for a fix now.

**Comment by dfangl** [comment]
Thanks for reporting this. It should be fixed with #5856 , just tested on a M1 Mac, and the segfault is now gone.
Could you confirm the fix works on your machine? Please do not forget to pull from latest: `docker pull localstack/localstack:latest`.

**Comment by agfunderburg10** [comment]
Confirmed this is working with the latest image. Thank you!!!

**Comment by adispennette** [comment]
Has this issue resurfaced with MacOS 14.5?
image localstack/localstack:0.11.2
```
2024-06-18 07:22:14 Starting local dev environment. CTRL-C to quit.
2024-06-18 07:22:15 2024-06-18 14:22:15,183 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-06-18 07:22:15 2024-06-18T14:22:15:INFO:localstack_ext.bootstrap.install: Unable to download local test SSL certificate: MyHTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /localstack/localstack-artifacts/raw/master/local-certs/server.key (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
2024-06-18 07:22:17 2024-06-18T14:22:17:INFO:localstack.utils.common: Unable to store key/cert files for custom SSL certificate: [Errno 13] Permission denied: '/tmp/localstack/server.test.pem.key'
```
