### ISSUE TITLE
bug: Web console - CloudWatch Logs 404ing

### ISSUE THREAD

**Issue by GalFuchs** [localstack/localstack#5754]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Selecting any CloudWatch Logs group in the new Web UI leads to a 404 page.

### Expected Behavior

CloudWatch Logs should be viewable.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker-compose up

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    Invoke any Lambda, try to go to specific log group in CloudWatch Logs.

### Environment

```markdown
- OS: MacOS Monterey
- LocalStack: latest
```

**Comment by GalFuchs** [comment]
Any update on this?
This is quite a blocker for us, if our developers don't have easy access to Lambda invocation logs.

**Comment by steffyP** [comment]
Hi @GalFuchs,

to clarify, by the "new Web UI" you mean the WebUi available at `app.localstack.cloud`?
In the meantime, accessing log groups with `CloudWatch Logs` should be possible. It will show all related log streams, which also contain the actual logs. Can you confirm it is working for you?

If you still experience troubles, please share details on how you are trying to access the logs. Thank you!

**Comment by GalFuchs** [comment]
Hey @steffyP!
Yes, that is what I meant by "new Web UI" (since by the time of posting, the current design was new)
This issue has indeed been resolved (it has been over two months after all :) ), though the timestamps showing in Epoch time instead of some actual Datetime format is a bit of a hassle, but as long as it works...

**Comment by steffyP** [comment]
Hi @GalFuchs,
thanks for the update!
Do you still see the timestamp unformatted in the logs view? This should actually have been fixed already as well. I just checked and I can see the timestamp formatted as `yyyy-MM-dd HH:mm:ss` in the `Log Events` for a Log Stream.

**Comment by GalFuchs** [comment]
When viewing log events it is indeed formatted, but viewing the stream list shows up like this:
<img width="1268" alt="image" src="https://user-images.githubusercontent.com/96415795/172326380-19e5c531-7c89-491e-aa45-55d9d3ef993a.png">
Which makes it a bit of a chore figuring out which one to dive into

**Comment by steffyP** [comment]
Thanks for pointing this out, @GalFuchs. Your feedback has been recorded and we will try to improve the UX in that matter. 

Is it alright with you if we close this ticket though, as the original issue with the `404 error` was resolved?
