### ISSUE TITLE
There is NO way to add an external EnvironmentVariable to a Container using the Java SDK

### ISSUE THREAD

**Issue by aecc** [localstack/localstack#576]
The containers are only created with a single environment variable, without possibility to load system or external ones:

Container.java: 47
```
.withEnvironmentVariable(LOCALSTACK_EXTERNAL_HOSTNAME, externalHostName)
```

The constructor is also private, so there is literally no way of doing so. This is needed e.g. in case we need to make the container to use SSL (USE_SSL=true). 

I propose to being able to create it using some kind of: createLocalstackContainer(String externalHostName, Map<String, String> extraEnvs)
or
withEnvironmentVariables(...) 

Use:
I need to make connections use SSL given that I need to create a Kinesis integration test using the KPL (which always uses SSL).

**Comment by whummer** [comment]
Thanks for reporting @aecc . Shouldn't it work if you call `withEnvironmentVariable(..)` multiple times consecutively?
```
RunCommand cmd = new RunCommand("myimage")
    .withEnvironmentVariable("var1", "value1")
    .withEnvironmentVariable("var2", "value2")
    .withEnvironmentVariable("var3", "value3");
```

**Comment by aecc** [comment]
Hi @whummer , sadly, the api to create a Container is private, so as an user of a Container I cannot create one unless is through the createLocalstackContainer() call.

**Comment by aecc** [comment]
I just created a PR with a proposed solution #579
