### ISSUE TITLE
feature request: Missing/Unimplemented EMR API

### ISSUE THREAD

**Issue by mviamari** [localstack/localstack#5760]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

The following APIs are reported as Not Implementing when using terraform with Localstack Pro:

* API action 'GetAutoTerminationPolicy' for service 'emr' not yet implemented
* API action 'ListInstanceFleets' for service 'emr' not yet implemented

Currently, terraform is able to create the EMR cluster but when terraform queries the localstack image for the current state of the cluster, those APIs are not available and it causes an error. This causes `terraform apply` to fail after the resources have been created, but before the `apply` step completes.

Additionally, the `awslocal` commands corresponding to those endpoints fail as well.
* `awslocal emr list-instance-fleets --cluster-id XXXX`
* `awslocal emr get-auto-termination-policy --cluster-id XXXX`

Additionally, I can describe the new created cluster, after the failed `terraform apply` when using the `awslocal` interface (`awslocal emr list-clusters`, `awslocal emr describe-cluster`).

**Comment by whummer** [comment]
Hi @mviamari , thanks for reporting. Support for EMR instance fleets and termination policy APIs has been added in the meantime - can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists.. Thanks for your help!
