### ISSUE TITLE
bug: Glue crawler cannot read parquet file to determine schema.

### ISSUE THREAD

**Issue by jasonboutwell** [localstack/localstack#5764]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

awslocal glue start-crawler c1

Output:
WARNING:localstack_ext.services.glue.glue_listener: Unable to start crawler c1: 'utf-8' codec can't decode byte 0xf0 in position 7: invalid continuation byte

### Expected Behavior

Expected Glue data catalog table to be created based on the parquet schema, and partitioned correctly.

The error suggests that the crawler is attempting to read the parquet file using an incorrect codec.

I have confirmed that the same crawler works when run against plain text CSV files in localstack.

The sample parquet file was copied from a running ETL in AWS. I ran the parquet-cli tool against it and successfully retrieved the schema.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

docker-compose -f docker-compose.yml up

awslocal s3 mb s3://mybucket
awslocal s3 cp my.snappy.parquet s3://mybucket
awslocal glue create-database --database-input '{"Name":"db1"}' 
awslocal glue create-crawler --name c1 --database-name db1 --role r1 --targets '{"S3Targets": [{"Path": "s3://mybucket/t1"}]}'
awslocal glue start-crawler --name c1

### Environment

```markdown
- OS: MacOS 11.6.1
- LocalStack:
```

**Comment by whummer** [comment]
Hi @jasonboutwell , thanks for reporting. This should be (hopefully) fixed in the meantime - can you please pull the `latest` LocalStack Docker image and give it another try? Please let us know if the problem persists.. Thanks!

**Comment by alexrashed** [comment]
It seems like this issue has been resolved. I'll close it for now. Please feel free to post a comment if it's not fixed yet.
