### ISSUE TITLE
question: S3 Empty ObjectTagging Exception error 500

### ISSUE THREAD

**Issue by rodrigolmacedo** [localstack/localstack#5769]
### Is there an existing issue for this?

- [X] I have searched the existing issues and read the documentation

### Question

Hello everyone, how are you?

First I want to congratulate the team for the great product.

Question: when i try to put object with objectTagging empty array, the localstack give me a 500 error code. is possible to request a fix to that?
java:
![image](https://user-images.githubusercontent.com/7695045/160708399-4b344598-d784-4168-8044-3ee9fd29f200.png)
debug:
![image](https://user-images.githubusercontent.com/7695045/160708330-cfdabc33-b45f-4de6-bae7-ae622af8e8fb.png)

**Comment by rodrigolmacedo** [comment]
After debug i found the request, when send java Collections.emptyList()...
`PUT http://127.0.0.1:4566 /bucketteste/1762253d-6dda-44a7-8469-46774fe2c0f5_img3.png Parameters: ({"tagging":[null]}Headers: (Content-Length: 36, Content-Type: application/xml, Content-MD5: k6PBbu32RmFaV5nRULDSlw==, ) `
I was investigating and saw this
![image](https://user-images.githubusercontent.com/7695045/161546132-6717a5a2-1768-40ad-9424-6fd0b76aba3b.png)
I didn't find any validation of empty or null when going this way.
![image](https://user-images.githubusercontent.com/7695045/161547537-b5071223-8444-4796-adf2-e343a5cc8764.png)
![image](https://user-images.githubusercontent.com/7695045/161547317-6553d244-eb5c-4199-9998-ca52c2805ee4.png)

maybe I haven't seen it, or simply the fact that I don't know python very well, sorry.

**Comment by nickgvt** [comment]
When creating an object it is created with an empty tag set
```
{
    "VersionId": "null",
    "TagSet": []
}
```
Adding tags to the object works fine using the aws cli and js client, but attempting to remove the tags on an s3 object with `aws s3api --endpoint http://localhost:4566 put-object-tagging --bucket public-files --key sampleFile.txt  --tagging '{"TagSet": []}'
` results in 500 internal server error when using aws cli and the js client.

Logging seems to indicate this is a moto bug, so should this issue be opened in their repo instead, or is this a localstack issue?
```
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/moto/s3/responses.py", line 1688, in _tagging_from_xml
    for tag in parsed_xml["Tagging"]["TagSet"]["Tag"]:
TypeError: 'NoneType' object is not subscriptable
```

**Comment by macnev2013** [comment]
Thanks for reporting the issues.

The newer version should resolve your issue. Can you please give it another try with the `latest` version of `LocalStack`?

Please let us know if the issue still persists. Thanks.
