### ISSUE TITLE
bug: use custom header instead of Authorisation for routing and region detection

### ISSUE THREAD

**Issue by calvernaz** [localstack/localstack#5780]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We are using the `Authorization` header for routing purposes

```
 "authorization: AWS4-HMAC-SHA256 <...>"
```

https://github.com/localstack/localstack/issues/5770

### Expected Behavior

Use a custom header to avoid causing confusion with backend integrations

### How are you starting LocalStack?

With a `docker run` command

### Steps To Reproduce

Run a custom HTTP integration without authorisation

### Environment

```markdown
- OS: 
- LocalStack:
```

### Anything else?

No

**Comment by whummer** [comment]
Good point @calvernaz , certainly something we should consider in the next iteration - also good input for ASF Gateway. /cc @alexrashed @thrau 

Wondering if for now we should take a simpler approach - recording the original `Authorization` header that comes in from the user request at the edge proxy and adding it as a `x-localstack-authorization` header to the request. We can then extract this header in the API Gateway implementation and forward it to the backend (e.g., Lambda) when constructing the invocation event. 

This way we would leave the routing logic untouched for now, but still solve the user issue in #5770 to forward the correct auth header (API key) to the user's Lambda event. Thoughts?

**Comment by calvernaz** [comment]
Your suggestion is pretty much this ticket - basically keep the logic as is, but use a custom header to hold the information.
