### ISSUE TITLE
bug: Difference in Vertex ID generation behavior between AWS Neptune and Localstack Neptune

### ISSUE THREAD

**Issue by mpinf** [localstack/localstack#5781]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

**AWS NeptuneDB**: When a new vertex is added into graph in AWS Neptune DB, it creates new UUID as default and assigns to vertex as T.id. 
**localstack NeptuneDB**: When a new vertex is added into graph in localstack pro NeptuneDB, it creates new integer id and assigns to vertex as T.id.

So it appears that the DefaultIdManager in localstack is generating integer ids, whereas AWS Neptune is generating string UUIDs.

### Expected Behavior

**Desired**: default ID generation behavior should be same which means in localstack it should generate default string UUID instead of integer id 

**Optional**: provide a mechanism to configure/override default behavior in localstack configuration.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    `docker-compose up`

#### After starting localstack, create new DB cluster using following command

    `awslocal neptune create-db-cluster --engine "neptune" --db-cluster-identifier "neptunelocaldb"`

#### Now using any client follow these steps - (we used Jypyter notebook as well as C# Gremlin.Net)
Create new vertex and then query using the default id

#### With AWS Neptune
g.addV("person")

//Returns New vertex created
v[4abff024-cc4e-c05c-f269-8c5e4b5d00e8]

//Now query the vertex using id
g.V("4abff024-cc4e-c05c-f269-8c5e4b5d00e8")

//above query returns the newly created vertex

#### With Localstack Neptune
g.addV("person")

// Returns New vertext created
v[41]

// Now query the vertex using the ID
g.V(41) or g.V("41")

// both queries above return empty list (no vertex found)

### Environment

```markdown
- OS: Ubuntu 20.04 WSL
- LocalStack: latest
```

**Comment by dfangl** [comment]
This should be fixed in :latest, as confirmed in Slack. Closing this for now. If there are any more issues, please do not hesitate to open another issue!
