### ISSUE TITLE
feature request: Implement ECS CreateCapacityProvider

### ISSUE THREAD

**Issue by noahjepstein** [localstack/localstack#5790]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

I'm not able to attach an ASG as an ECS capacity provider because CreateCapacityProvider is not implemented yet in localstack. This implementation would allow you to use an ASG as opposed to Fargate instances for ECS.

If it matters, using terraform to create the capacity provider like
```
resource "aws_ecs_capacity_provider" "provider" {
  name = "provider"
  auto_scaling_group_provider {
    auto_scaling_group_arn = module.asg.autoscaling_group_arn
  }
}
```

### Anything else?

Related discussion in slack: https://localstack-community.slack.com/archives/CLRFWBFC3/p1648584051032039

**Comment by whummer** [comment]
Hi @noahjepstein , thanks for reporting. This should be (hopefully) resolved in the meantime (in Pro) - can you please pull the `latest` Docker image and give it another try?

With the following minimal TF configuration:
```

resource "aws_autoscaling_group" "test" {
  name                      = "test-asg"
  min_size                  = 2
  max_size                  = 5
  launch_configuration      = aws_launch_configuration.foobar.name
  availability_zones        = ["us-east-1a"]
}

resource "aws_launch_configuration" "foobar" {
  name          = "web_config"
  image_id      = "ami-ekslinux"
  instance_type = "t2.micro"
}

resource "aws_ecs_capacity_provider" "provider" {
  name = "provider"
  auto_scaling_group_provider {
    auto_scaling_group_arn = aws_autoscaling_group.test.arn
  }
}

```

... I'm getting this result:
```
$ tflocal apply
...
aws_launch_configuration.foobar: Creating...
aws_launch_configuration.foobar: Creation complete after 0s [id=web_config]
aws_autoscaling_group.test: Creating...
aws_autoscaling_group.test: Creation complete after 0s [id=foobar3-terraform-test]
aws_ecs_capacity_provider.provider: Creating...
aws_ecs_capacity_provider.provider: Creation complete after 0s [id=arn:aws:ecs:us-east-1:000000000000:capacity_provider/provider/a0694b75-4753-42f9-abae-d3f34057734c]

Apply complete! Resources: 3 added, 0 changed, 0 destroyed.
```

Hope that helps - please keep us posted on how it goes.. Thanks!

**Comment by whummer** [comment]
Closing this issue as resolved - please do let us know if the problem persists.. Thanks for your help!
