### ISSUE TITLE
question: User identity in lambda event or context for Cognito users

### ISSUE THREAD

**Issue by vittoriozamboni** [localstack/localstack#5791]
### Is there an existing issue for this?

- [X] I have searched the existing issues and read the documentation

### Question

Hi! 

Thanks a lot for your hard work on this tool!
I have a question around identities and how they are forwarded to lambdas from AppSync. 

In my current (Pro) stack, I have:
- a Cognito user pool and a Cognito user pool client, and a single user that belongs to "root" group;
- an AppSync service with a query that is connected to a lambda, with permissions set by `@aws_cognito_user_pools`.

I can successfully obtain an ID Token by using `USER_PASSWORD_AUTH` authentication flow, and I can use the returned token to call the AppSync endpoint with the header `Authorization: Bearer <TOKEN>`.

The lambda input objects however do not send any information about the user logged in: the first argument identity section is just a simple `{ identity: { sub: "admin" } }` object and the `context` second argument has an empty `identity` value. 

Is there any specific configuration I need to change to be able to determine the user within the lambda?

From [the specification](https://docs.aws.amazon.com/appsync/latest/devguide/resolver-context-reference.html#aws-appsync-resolver-context-reference-identity) of the VTL template, the identity should contain more information, i.e. 
```
{
    "sub" : "uuid",
    "issuer" : "string",
    "username" : "string"
    "claims" : { ... },
    "sourceIp" : ["x.x.x.x"],
    "defaultAuthStrategy" : "string"
}
```

Is this a design choice to always return "admin" if the user is authenticated? If yes, is there any plan to support a more granular information?

**Comment by vittoriozamboni** [comment]
More context:

The lambdas are created with Serverless, and this is the actual VTL template:

```
{
    "version" : "2018-05-29",
    "operation": "Invoke",
    "payload": {
        "identity": $util.toJson($ctx.identity),
        "args": $util.toJson($ctx.arguments),
       "requestContext": $util.toJson($ctx)
    }
}

```

The lambdas are written in Typescript and runs in nodes12.x container.

**Comment by biancacatalunha** [comment]
I have the same issue, anyone able to answer this question?

**Comment by ugurhicyilmam** [comment]
I have the same issue

**Comment by romuaa** [comment]
@vittoriozamboni Did you ever find a solution for this? We seem to have the same problem. Running serverless/localstack and the Lambdas use written in Python3
