### ISSUE TITLE
bug: KMS_PROVIDER=local-kms not honored

### ISSUE THREAD

**Issue by davecardwell** [localstack/localstack#5792]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When updating from 0.14.1 to 0.14.2 it appears that the `KMS_PROVIDER` environment variable is no longer honored, and `local-kms` is not used.

### Expected Behavior

Setting `KMS_PROVIDER=local-kms` and using the KMS service should launch `local-kms` as it did previously.

### How are you starting LocalStack?

With a `docker run` command

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run -e KMS_PROVIDER=local-kms localstack/localstack:0.14.1

    docker run -e KMS_PROVIDER=local-kms localstack/localstack:0.14.2

##### 0.14.1

    awslocal kms list-keys
    # {
    #     "Keys": []
    # }

    ps x|grep kms
    #   164 ?        Ss     0:00 /bin/sh -c /opt/code/localstack/localstack/infra/kms/local-kms.linux-arm64.bin
    #   165 ?        Sl     0:00 /opt/code/localstack/localstack/infra/kms/local-kms.linux-arm64.bin
    #   179 pts/0    S+     0:00 grep kms

##### 0.14.2

    awslocal kms list-keys
    # {
    #     "Keys": []
    # }

    ps x|grep kms
    #   151 pts/0    S+     0:00 grep kms

### Environment

```markdown
- OS: macOS 12.3
- LocalStack: 0.14.2
- Docker: 20.10.13, build a224086
```

**Comment by pedromorais-raidiam** [comment]
Did anyone ever manage to see with moto since local-kms got removed?
