### ISSUE TITLE
feature request: Make the localhost.localstack.cloud certificate a wildcard

### ISSUE THREAD

**Issue by mbklein** [localstack/localstack#5803]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

In order to support OpenSearch via SSL in `domain` mode, it would be a big help if the `localhost.localstack.cloud` certificate were a wildcard that would support `*.opensearch.localhost.localstack.cloud` as well.

### 🧑‍💻 Implementation

Update the certificate signing request for the `localhost.localstack.cloud` domain to include `*.opensearch.localhost.localstack.cloud` or `*.localhost.localstack.cloud` as a Subject Alternative Name.

**Comment by whummer** [comment]
Hi @mbklein , thanks for the pointer. We have now updated the local SSL certificate to also cover `*.opensearch.localhost.localstack.cloud` subdomains. 👍 

Please note that you may need to clean out the cached certificates in `$TMPDIR/localstack/cache/server.test.pem*`. Technically, the cert should be auto-updated after a couple of hours, so hopefully it will run out of the box. Hope that helps - please let us know if there are any issues.. Thanks!

**Comment by mbklein** [comment]
@whummer Thank you for the extremely quick turnaround on this. Unfortunately, it seems there's one more snag to overcome, and I'm not sure how to do it (or if it's even possible).

I assumed that a wildcard certificate would work for as many subdomains as required, e.g., `common.us-east-1.opensearch.localhost.localstack.cloud` would match `*.opensearch.localhost.localstack.cloud` or `*.localhost.localstack.cloud`. But the RFC is vague on the issue, and it turns out that most browsers and HTTP clients will only replace the `*` with a single, un-dotted name. So to match `common.us-east-1.opensearch.localhost.localstack.cloud`, you'd need a cert for `*.us-east-1.opensearch.localhost.localstack.cloud`.

Multiply the number of domain-specific services you'd need to support (6, I think?) by the number of regions currently offered by AWS (25), and you've by far exceeded LetsEncrypt's 100-name Subject Alternative Name limit.

I'm going to solve my immediate problem by creating my OpenSearch domain with a custom endpoint of `common.opensearch.localhost.localstack.cloud` so it can use the new wildcard cert. But I'm afraid a completely seamless solution may be out of reach.
