### ISSUE TITLE
feature request: support TRIM_HORIZON starting position for kinesis stream event source mappings on Lambda functions

### ISSUE THREAD

**Issue by SwatsonCodes** [localstack/localstack#5804]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Currently LocalStack only supports the `LATEST` starting position for Kinesis stream event source mappings on Lambda functions. This means that the Lambda function is only triggered when new data enters the stream, after the mapping has been defined. We should support `TRIM_HORIZON` as well, where the Lambda function is continually triggered starting with the oldest value(s) in the stream.
https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-lambda.StartingPosition.html

### 🧑‍💻 Implementation

Currently the call for invoking a mapped lambda function lives in the `return_response` method of the kinesis listener. It is invoked immediately before returning a response on calls to `PutRecord` and `PutRecords`.
https://github.com/localstack/localstack/blob/master/localstack/services/kinesis/kinesis_listener.py#L176

This is problematic because under this implementation there's no good way to support `TRIM_HORIZON`. Mapped lambda functions are only invoked when new data is added to the stream; there's no good way to iterate through old records.

I think what we need to do instead is maintain an internal mapping of kinesis streams/shards -> lambda functions. We should run a [subscribe_to_shard](https://github.com/localstack/localstack/blob/master/localstack/services/kinesis/kinesis_listener.py#L322) operation on a background thread for each mapping. These threads should loop indefinitely.

### Anything else?

This issue was brought to my attention via this bug report:
https://github.com/localstack/localstack/issues/5774

**Comment by MarcelStranak** [comment]
@SwatsonCodes Hi, shouldn't this be closed?

**Comment by SwatsonCodes** [comment]
Hey @MarcelStranak, I am working on this feature actively.

**Comment by SwatsonCodes** [comment]
this feature is encompassed in this PR: https://github.com/localstack/localstack/pull/5807
