### ISSUE TITLE
bug: Step Functions not invoking with a body through an API Gateway

### ISSUE THREAD

**Issue by SuttonO-Webeo** [localstack/localstack#5808]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When calling end point an API Gateway to invoke a Step Function within LocalStack via a Cloud Formation template, the body maps as expected by an exception is then thrown implying that the JSON object is invalid

```
localstack-bug-node14-localstack-1  | 2022-04-05T13:03:07.443:INFO:localstack.services.apigateway.integration: Method request body before transformations: {
localstack-bug-node14-localstack-1  |     "name": 1234
localstack-bug-node14-localstack-1  | }
localstack-bug-node14-localstack-1  | 2022-04-05T13:03:07.515:INFO:localstack.services.apigateway.integration: Endpoint request body after transformations:
localstack-bug-node14-localstack-1  | {"input": "{"name": 1234}", "stateMachineArn": "arn:aws:states:eu-west-1:000000000000:stateMachine:TestStateMachine-LOCAL"}
localstack-bug-node14-localstack-1  | 2022-04-05T13:03:07.515:ERROR:localstack.services.apigateway.apigateway_listener: Error invoking integration for API Gateway ID '35avh96ud7': Expecting ',' delimiter: line 1 column 14 (char 13)
localstack-bug-node14-localstack-1  | Traceback (most recent call last):
localstack-bug-node14-localstack-1  |   File "/opt/code/localstack/localstack/services/apigateway/apigateway_listener.py", line 503, in invoke_rest_api_integration
localstack-bug-node14-localstack-1  |     response = invoke_rest_api_integration_backend(invocation_context)
localstack-bug-node14-localstack-1  |   File "/opt/code/localstack/localstack/services/apigateway/apigateway_listener.py", line 660, in invoke_rest_api_integration_backend
localstack-bug-node14-localstack-1  |     payload = json.loads(payload)
localstack-bug-node14-localstack-1  |   File "/usr/local/lib/python3.8/json/__init__.py", line 357, 
in loads
localstack-bug-node14-localstack-1  |     return _default_decoder.decode(s)
localstack-bug-node14-localstack-1  |   File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
localstack-bug-node14-localstack-1  |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
localstack-bug-node14-localstack-1  |   File "/usr/local/lib/python3.8/json/decoder.py", line 353, in raw_decode
localstack-bug-node14-localstack-1  |     obj, end = self.scan_once(s, idx)
localstack-bug-node14-localstack-1  | json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 
column 14 (char 13)
```

### Expected Behavior

The API Gateway call is made and the body is correctly mapped and passed onto the Step Function

### How are you starting LocalStack?

With a docker-compose file

### git repo

git repo to be used to reproduce this can be found [here](https://github.com/lf-tech-team/localstack-bug-node14)

#### reproduce

1. clone repo
2. run ```docker-compose up```
3. run ```samlocal build```
4. run ```samlocal deploy -g```
5. follow samlocal deployment steps
6. take the API Gateway URL from the output
7. POST to the URL provided by the deployment output, with a valid JSON body e.g. ```{ "name": "test" }```

### Environment

```markdown
- OS: Windows 10
- LocalStack: Latest
```

**Comment by calvernaz** [comment]
Hi @SuttonO-Webeo we have a preliminary fix for your case, but as it affects how templating works with other integrations we are still testing the solution. I'll ping you back once we finish.

**Comment by calvernaz** [comment]
Hi @SuttonO-Webeo I've been following this up and I think the issue is with the CF template, you can see it [here](https://github.com/aws/serverless-application-model/issues/1895). I made a couple of changes to fix your case, but then broke other scenarios and I believe at this stage they are incompatible - fixing the CF behaviour and other uses of the `escapeJavascript` function. Let's hope they fix the issue in their side.

**Comment by SuttonO-Webeo** [comment]
Hi @calvernaz thanks for looking into this. Just got to wait for AWS to fix it then :)
