### ISSUE TITLE
bug: KMS_PROVIDER value for Local KMS Changed in v0.14.2, KMS Seeding Broken

### ISSUE THREAD

**Issue by chrisguitarguy** [localstack/localstack#5810]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I've been using [local-kms](https://github.com/nsmithuk/local-kms) plus a seed file to run KMS services in localstack.

Prior to v0.14.2, one enabled local kms by setting `KMS_PROVIDER=local-kms` in the environment. As of 0.14.2, you must now set `KMS_PROVIDER=kms-local`.

See:

- https://github.com/localstack/localstack/commit/70958beb42bbf3d686dbf4453618618b6705879a#diff-3fd64ba3c8832466471dbed37a546b444b49a5af9addef343ef2bde67b117a76R142
- https://github.com/localstack/localstack/commit/70958beb42bbf3d686dbf4453618618b6705879a#diff-5a917c94cad13ad3c54be6073451f7cb3270e939f5ed6aa898cfd8a74bb11501L56-L60

Because of this any seeding stuff I had for local kms stopped working (local KMS was no longer being used) and tests started failing.

### Expected Behavior

Ideally localstack would have kept the same environment variable value and not unexpectedly broken, I got suprised by this when some tests started failing on CI.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

Here's a reproducer: https://github.com/chrisguitarguy/localstack-0.14.2-kms-seeding-bug

```
docker-compose up -d
./bug.sh
```

### Environment

```markdown
- OS: MacOS
- LocalStack: 0.14.2 (in Docker)
```

**Comment by merowinger92** [comment]
This has been adressed here: https://github.com/localstack/localstack/pull/5793

**Comment by chrisguitarguy** [comment]
Ope, my bad, I did not search thoroughly enough!
