### ISSUE TITLE
bug: EMR API Inconsistencies

### ISSUE THREAD

**Issue by mviamari** [localstack/localstack#5812]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When creating and describing an EMR cluster through terraform, several inconsistencies are shown if `terraform apply` is run, followed immediately by `terraform plan`. It's not clear to me if this is a bug in terraform or localstack in all cases.

Several of these are the result of terraform apparently expecting `null`, but the Localstack API returning a placeholder for an empty value: `"None", {}, etc`

* `ebs_root_volume_size` is always read back as 0, even when it's specified as non-zero in the config.
* `autoscaling_role` is readback as "None" if it's not defined in terraform
* `auto_termination_policy` is readback as {}
* `log_uri` is readback as "None" if its not defined in terraform
* `core_instance_group.ebs_config.iops` is readback as 0 when it is unspecified

### Expected Behavior

Immediately after running `terraform apply`, `terraform plan` should not show any required changes

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

Docker Compose

```
version: '3.8'

services:

  localstack:
    image: localstack/localstack:latest
    environment:
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY}
      - DEBUG=1
      - AWS_DEFAULT_REGION=us-east-1
      - DEFAULT_REGION=us-east-1
      - USE_SSL=false
      - AWS_ACCESS_KEY_ID=test123
      - AWS_SECRET_ACCESS_KEY=testabc
      - AWS_CA_BUNDLE=/etc/ssl/cert.pem
      - REQUESTS_CA_BUNDLE=/etc/ssl/cert.pem
      - SSL_CERT_FILE=/etc/ssl/cert.pem
      - HOST_TMP_FOLDER=/tmp/localstack
      - DATA_DIR=/tmp/localstack/data # This is the where the data will be stored/saved, inside the docker instance
      - DOCKER_HOST=unix:///var/run/docker.sock
      - OUTBOUND_HTTP_PROXY=${HTTP_PROXY}
      - OUTBOUND_HTTPS_PROXY=${HTTPS_PROXY}
    ports:
      - '4566-4599:4566-4599'
    volumes:
      - "/tmp/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ${CA_CERT_LOCATION}:/etc/ssl/cert.pem
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

terraform resource
```
resource "aws_emr_cluster" "default_cluster" {
  name          = "default-emr-cluster"
  release_label = "emr-6.5.0"
  applications  = ["Spark"]

  termination_protection            = false
  keep_job_flow_alive_when_no_steps = true

  service_role = "EMR_Default_Role"

  # autoscaling_role = "None"
  # auto_termination_policy {}
  ebs_root_volume_size = 100

  master_instance_group {
    instance_type  = "m5.xlarge"
    instance_count = 3
  }

  core_instance_group {
    instance_type  = "m5.xlarge"
    instance_count = 3

    ebs_config {
      size                 = "1000"
      type                 = "gp2"
      volumes_per_instance = 1
    }
  }

  #Logging
  # log_encryption_kms_key_id
  # log_uri = "None"
}
```

### Environment

```markdown
- OS: MacOS Monterey 12.2.1 
- LocalStack version: 0.14.2
- LocalStack Docker container id: cffb27dab98a
- LocalStack build date: 2022-04-01
- LocalStack build git hash: 3d8b2835
```

**Comment by whummer** [comment]
Hi @mviamari, thanks for reporting. We have now pushed a couple of enhancements which should (hopefully) resolve the issues you've mentioned in this ticket. Can you please pull the `latest` Docker image and give it another try? Please keep us posted on how it goes.. Thanks!

**Comment by mviamari** [comment]
Thanks @whummer. This appears to be working as expected now.
