### ISSUE TITLE
bug: Service discovery return missing Namespace ID 

### ISSUE THREAD

**Issue by lee-butn** [localstack/localstack#5817]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Same problem with happen again #4833 in latest release

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal s3 mb s3://mybucket

### Environment

```markdown
- OS: 
- LocalStack:
```

**Comment by whummer** [comment]
Thanks for reporting @lee-butn . We have now pushed a small change that should (hopefully) get this issue resolved. Can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists.. Thanks!

**Comment by whummer** [comment]
Closing this issue as resolved - please do let us know if the problem persists.. Thanks for your help!
