### ISSUE TITLE
issue while invoking get-object api with specified version 

### ISSUE THREAD

**Issue by ricdong** [localstack/localstack#582]
hi 
Does localstack supports the s3 bucket versioning?  I  try to use the s3 mock service for my unit test, the following test steps are: 

1. `aws --endpoint-url=http://localhost:4572 s3api create-bucket --bucket my-bucket` 
2. `aws --endpoint-url=http://localhost:4572 s3api put-bucket-versioning --bucket my-bucket --versioning-configuration Status=Enabled`
3. `aws --endpoint-url=http://localhost:4572 s3 cp /tmp/000_1 s3://my-bucket/output/000_1`
4.  `aws --endpoint-url=http://localhost:4572 s3 rm s3://my-bucket/output/000_1 `
5. `aws --endpoint-url=http://localhost:4572 s3api list-object-versions --bucket my-bucket --prefix output/`
the output of `list-object-versions` is:

``` 

    "DeleteMarkers": [
        {
            "Owner": {
                "DisplayName": "webfile",
                "ID": "75aa57f09aa0c8caeab4f8c24e99d10f8e7faeebf76c078efc7c6caea54ba06a"
            },
            "IsLatest": true,
            "VersionId": "1",
            "Key": "output/000_1",
            "LastModified": "2018-01-25T06:27:06.276Z"
        }
    ],
    "Versions": [
        {
            "LastModified": "2018-01-25T06:27:06.276Z",
            "VersionId": "0",
            "ETag": "\"0cc175b9c0f1b6a831c399e269772661\"",
            "StorageClass": "STANDARD",
            "Key": "output/000_1",
            "Owner": {
                "DisplayName": "webfile",
                "ID": "75aa57f09aa0c8caeab4f8c24e99d10f8e7faeebf76c078efc7c6caea54ba06a"
            },
            "IsLatest": false,
            "Size": 1
        }
    ]
}
``` 
6. then use the version-id to get my deleted object `aws --endpoint-url=http://localhost:4572 s3api get-object --bucket my-bucket --key output/ --version-id 0  /tmp/a`
the error output: 

``` 
An error occurred (500) when calling the GetObject operation (reached max retries: 4): Internal Server Error 
``` 
Did I miss something ? any help will be appreciated.

**Comment by spinningarrow** [comment]
Can you try this on the latest localstack? It's working for me.

**Comment by whummer** [comment]
Closing this issue as outdated/obsolete. Please create a follow-up issue with error details if the problem persists. Thanks
