### ISSUE TITLE
feature request: Surface expired or missing API key via `localstack wait`

### ISSUE THREAD

**Issue by posita** [localstack/localstack#5820]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Originally raised [on Slack](https://localstack-community.slack.com/archives/CMAFN2KSP/p1649264485098269).

Our GH Actions started [timing out](https://localstack-community.slack.com/archives/CMAFN2KSP/p1649264485098269) one day on our `localstack start -d ; localstack wait …` command (per the [recommended instructions](https://docs.localstack.cloud/ci/github-actions/)). We couldn't figure out what was going on. It turns out that we had an expired API key, but didn't know it. The problem is that LocalStack appears to endlessly loop on startup when it encounters a stale API key. This makes it _look_ like `localstack wait …` is timing out, but that hides the true problem.

Ideally, LocalStack should fail immediately under these circumstances and the problem should be surfaced in logs visible via GitHub's actions interface.

### 🧑‍💻 Implementation

One idea:

1. Cause LocalStack to fail immediately when the API key expired and when pro services are requested.
2. Augment the [recommended instructions](https://docs.localstack.cloud/ci/github-actions/) to surface the problem if LocalStack fails to start up. I don't know if this would work:

``` sh
localstack wait -t 30 ||  ( localstack logs && exit 1 )  # <-- wait up to 30 seconds and then dump logs if wait fails
```

**Comment by HarshCasper** [comment]
Hi @posita 👋 

I am currently working on it. I will share an update over here once its fixed.
