### ISSUE TITLE
bug: SQS Concurrent Poll Not Finding Messages

### ISSUE THREAD

**Issue by austinarbor** [localstack/localstack#5824]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It seems like at certain times the ReceiveMessage call takes the full WaitTimeSeconds even if there are messages available on the queue

### Expected Behavior

If there are messages on the queue, the ReceiveMessage call should return immediately

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

```yml
  localstack:
    image: localstack/localstack:latest
    environment: 
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - SERVICES=sqs,sts
    ports:
      - '4566:4566'
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

I created a reproducer project: https://github.com/austinarbor/localstack-long-poll to demonstrate the problem. Clone the project and run `./gradlew run`.  Let it run for ~20 seconds. If you don't see the issue, kill the process and start it again. It has never taken me more than 3 starts to get it to reproduce.

You will see logs like the below. As you can see, we are constantly putting messages on the queue, but even after polling, the consumers are not finding the messages.
```
> Task :run
Starting Consumer A
Starting Consumer B
(Producer) Putting message on queue 'testA.fifo': -1271882532. Current Depth: 0
(Producer) Putting message on queue 'testA.fifo': 2129777260. Current Depth: 0
(Consumer A) Poll took 714 ms
(Consumer A) Received: 2129777260
(Producer) Putting message on queue 'testB.fifo': ack: 2129777260. Current Depth: 0
(Consumer B) Poll took 759 ms
(Consumer B) Received: ack: 2129777260
(Producer) Putting message on queue 'testA.fifo': -485493464. Current Depth: 0
(Producer) Putting message on queue 'testA.fifo': -1604791900. Current Depth: 1
(Producer) Putting message on queue 'testA.fifo': -282920307. Current Depth: 2
(Producer) Putting message on queue 'testA.fifo': 1494969506. Current Depth: 3
(Producer) Putting message on queue 'testA.fifo': -998941739. Current Depth: 4
(Producer) Putting message on queue 'testA.fifo': -268403871. Current Depth: 5
(Producer) Putting message on queue 'testA.fifo': -693628700. Current Depth: 6
(Producer) Putting message on queue 'testA.fifo': -652537954. Current Depth: 7
(Producer) Putting message on queue 'testA.fifo': 266404710. Current Depth: 8
(Producer) Putting message on queue 'testA.fifo': 1563771637. Current Depth: 9
(Consumer B) Poll took 20074 ms
(Consumer A) Poll took 20072 ms
```

### Environment

```markdown
- OS: Mac OS 12.3.1
- LocalStack: latest
```

### Anything else?

The architecture of the application this repro represents is a two-service platform.

Service A puts messages on Service B's queue. Service B consumes the message, processes it, and then responds on Service A's queue. Service A processes it, and responds back, etc.  WIth 2 back and forth exchanges, it often takes upwards of 40 seconds. The majority of the time is just waiting for the current ReceiveMessage poll to complete, at which point it returns empty and restarts the polling process.

**Comment by wimax-grapl** [comment]
I am also seeing this behavior in 0.14.3, for what it's worth.

**Comment by thrau** [comment]
The latest docker image should now include a fix for the issue. It was a bug related to how we do blocking reads when both WaitTimeSeconds and MaxNumberOfMessages were specified.

Could you please check out the latest image and see if the issue persist?

**Comment by austinarbor** [comment]
i think this looks much better now, thanks for fixing!

**Comment by wimax-grapl** [comment]
I'll try to repro later today.

**Comment by thrau** [comment]
awesome! i'll close the issue for now, please feel free to re-open and ping me if the issue persists.
