### ISSUE TITLE
Localstack SES Notification to SNS

### ISSUE THREAD

**Issue by sabbysabs** [localstack/localstack#5829]
I'm sending an email via SES and I have the notification setup to go to SNS, in which I have an SQS subscribed to my topic, however when I try to retrieve messages from the SQS there are no messages on the queue.

I've published a message directly to SNS and it goes to SQS when I've subscribed them.

Looking at the ses/ses_starter.py that the functionality to push notifications from ses does not exist, but I'm no python expert.

Here is a [StackOverflow](https://stackoverflow.com/questions/71768287/testcontainers-localstack-ses-and-publishing-to-sns), that I created describing my issue.

I should also note, that I'm writing an integration test via TestContainers using the LocalStack Module that mimics this workflow.

**Comment by sabbysabs** [comment]
I'm guessing this PR needs to be merged and it will use the ConfigurationSet: https://github.com/localstack/localstack/pull/5771.

**Comment by bentsku** [comment]
Thanks for your report! 

This feature is now implemented with this PR: #7207
