### ISSUE TITLE
Tail lambda logs from a Node runtime with LAMBDA_EXECUTOR=docker enabled

### ISSUE THREAD

**Issue by zachschultz** [localstack/localstack#583]
I am trying to test Node runtime Lambda functions and ran into the issue of needing the `LAMBDA_EXECUTOR=docker` environment variable set. To solve this, I start localstack like so now: `LAMBDA_EXECUTOR=docker localstack start --docker`.

I can successfully create and invoke Lambda functions, but I'm not able to see any of the logging. Is there a way I can access the container that these Lambda functions are being run on and tail their logs?

The reason I'd like to tail logs is because I need more than simply reading the outfile you pass to `aws local lambda invoke...`. I have 2 functions, the first writing to a Kinesis stream, and the second with an event-source-mapping to that same stream. My goal is to be able to test and verify that running my first lambda, which writes to the stream, will activate the second lambda.

**Comment by whummer** [comment]
Thanks for reporting. Closing, as this should have been fixed in the meantime. There's another issue around logs being published in batches (and not real-time) which you can track here: https://github.com/localstack/localstack/issues/1623
