### ISSUE TITLE
bug: API Gateway refusing to invoke any POST route with a non-LocalStack Referer header

### ISSUE THREAD

**Issue by mbklein** [localstack/localstack#5833]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If I create an API Gateway V2 HTTP API with both `GET` and `POST` routes, the `GET` routes work fine when invoked with or without a `Referer` header, but `POST` routes return `403 Forbidden` if a `Referer` is present (_unless_ that `Referer` starts with `https://localhost.localstack.cloud`). The LocalStack log (with debugging on) reports that it was blocked because it was a “CORS request from forbidden origin.”

For what it's worth, I've noticed that the same behavior occurs on any other LocalStack route as well, including `/` or `/health`. (I realize those routes aren't usually invoked via `POST`, but they do respond and exhibit the same Referer/403 behavior described above.) That's not really a problem, but the information may help pinpoint where the CORS decision is being made.

### Expected Behavior

API Gateway V2 `POST` routes can accept a `Referer` header and pass it along to the configured integration.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

I have created a [small project](https://github.com/mbklein/hello-api) that demonstrates the issue using Terraform to deploy the API. Its `README.md` file will walk you through reproducing the problem.

### Environment

```markdown
- OS: MacOS 12.3
- LocalStack: 0.14.2 (build date 2022-04-08)
- Docker Engine: 20.10.13
```

**Comment by calvernaz** [comment]
Hi @mbklein thanks for reporting this - the behaviour is definitely not consistent, so we need to fix it. Although, you can use the environment variable `DISABLE_CORS_CHECKS = 0` to disable the check, and the `Referer` will be passed to the integration. 

Tell us if that works for you, thanks! 👍 

Resource: https://docs.localstack.cloud/localstack/configuration/
