### ISSUE TITLE
bug: DynamoDB ResourceNotFoundException when performing BatchGetItem

### ISSUE THREAD

**Issue by cmschuetz** [localstack/localstack#5843]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am receiving a ResourceNotFoundException when attempting to run a BatchGetItem operation on a table that exists.  Downgrading to `0.14.2` fixes the issue and I was not receiving this issue on Friday when running the `latest` container.  I am able to run `scan` and `query` requests successfully on these tables.

### Expected Behavior

BatchGetItem should work on tables that exist

### How are you starting LocalStack?

With a `docker run` command

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

- `awslocal dynamodb create-table --table-name test-table --attribute-definitions AttributeName=PK,AttributeType=S --key-schema AttributeName=PK,KeyType=HASH --provisioned-throughput ReadCapacityUnits=1,WriteCapacityUnits=1`
- `awslocal dynamodb list-tables`
```
{
    "TableNames": [
        "test-table"
    ]
}
```
- `awslocal dynamodb batch-get-item --request-items '{ "test-table": { "Keys": [{ "PK": {"S": "test-key"} }] } }'`
```
An error occurred (ResourceNotFoundException) when calling the BatchGetItem operation: Cannot do operations on a non-existent table
```

### Environment

```markdown
- OS: 
- LocalStack: latest
```

**Comment by terenceduong** [comment]
We've got the same issue, we are using docker-compose and provisioning Dynamo tables. No changes to our stack lately and suddenly broke today (error messages of similar nature to `Cannot do operations on a non-existent table`).

Reverted to image 0.14.2 as @cmschuetz and that fixed our stack too.

**Comment by seek-josh-zhu** [comment]
Hi @cmschuetz , thank you for the fix, but it looks like this PR only fix the the BatchGetItem, we have the same issue when using `Query` and `Delete`, are you guys planing to get it fixed in the other PR as well?

**Comment by giograno** [comment]
Hi @cmschuetz, could you please open a separate issue, ideally with some examples/steps to replicate? Thank you very much!

**Comment by cmschuetz** [comment]
> Hi @cmschuetz, could you please open a separate issue, ideally with some examples/steps to replicate? Thank you very much!

I'm all good! Thanks for the fix.  @seek-josh-zhu should open a new one
