### ISSUE TITLE
bug: unsubscribing from SNS topic does not send confirmation request to HTTP endpoint

### ISSUE THREAD

**Issue by maciejwalkowiak** [localstack/localstack#5846]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

For HTTP endpoint, unsubscribe just removes subscription.

### Expected Behavior

Unsubscribe should remove subscription and send notification to the endpoint that unsubscribe event happened (look https://docs.aws.amazon.com/sns/latest/dg/sns-message-and-json-formats.html under "HTTP/HTTPS unsubscribe confirmation JSON format")

### How are you starting LocalStack?

Custom (please describe below)

### Steps To Reproduce

With Testcontainers.

### Environment

```markdown
- OS: OSX
- LocalStack: 0.14.0
```

**Comment by pinzon** [comment]
The solution to this issue has been merged. Thank you for your support.

**Comment by maciejwalkowiak** [comment]
Awesome thank you @pinzon!
