### ISSUE TITLE
feature request: API Gateway v1 REST API integration features - mapping templates, event invocation, mocks

### ISSUE THREAD

**Issue by mbklein** [localstack/localstack#5850]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

I couldn't figure out whether the following was a feature request or bug report, and I also couldn't find a great way to split the four distinct parts of it into separate issues because they're all somewhat intertwined.

I have set up a [demo repository](https://github.com/nulib/localstack-api-gateway) with APIs that can be deployed to both LocalStack and AWS to demonstrate the differences in behavior. Referring to that repo's [README.md](https://github.com/nulib/localstack-api-gateway/blob/main/README.md) while reading the descriptions below might be helpful.

There are at least three features that seem to be either missing or mishandled in LocalStack's API Gateway v1 service.

### [Integration Request/Response Data Mapping](https://docs.aws.amazon.com/apigateway/latest/developerguide/request-response-data-mappings.html)

This seems to be partially implemented in LocalStack, but behaves differently from how it works in AWS.

- In AWS, when there is a matching request mapping template, the entire `event` object sent to the Lambda is replaced by the transformation result. In LocalStack, the transformation result becomes the `body` of the original `event`, which is then passed to the Lambda.
- In AWS, Lambda integrations can specify additional request and response headers to be automatically added to the request and response. LocalStack does not add these headers. (This includes the `X-Amz-Invocation-Type` header, mentioned below.)
- In AWS, the `{statusCode: 200, body: body}` [proxy response format](https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-lambda-proxy-integrations.html#api-gateway-simple-proxy-for-lambda-output-format) is only used for `AWS_PROXY` integrations, not `AWS` integrations. In LocalStack, `AWS` integrations will not return anything unless the Lambda response is in that format.

### [Asynchronous Lambda Invocation](https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-lambda-integration-async.html)

- In AWS, the `X-Amz-Invocation-Type` header controls whether the Lambda is invoked synchronously (`X-Amz-Invocation-Type: RequestResponse`) or asynchronously (`X-Amz-Invocation-Type: Event`). LocalStack does not respect the `Event` type invocation.

### [Mock Integrations](https://docs.aws.amazon.com/apigateway/latest/developerguide/how-to-mock-integration.html)

- AWS allows REST API resources to define mock integrations that return static / mapped responses without calling any backend service. LocalStack returns `{}` for all mock integrations instead of using the specified mappings.

### Anything else?

There might be a lot more to this than what I've documented. I haven't gone through every feature of REST API method and integration request and response specifications.

**Comment by mbklein** [comment]
I see that most of what I described above is known not to work in the moto backend. http://docs.getmoto.org/en/latest/docs/services/apigateway.html

**Comment by sam-goodwin** [comment]
Ran into this problem also. When can we expect a fix?

**Comment by whummer** [comment]
Hi @mbklein @sam-goodwin , thanks for reporting. We've recently added a couple of enhancements for API Gateway (incl. Lambda integration output response mapping, asynchronous invocations, and basic support for mock integrations). When you get a chance, can you please pull the `latest` Docker image and give it another try? Please keep us posted on how it goes, thanks!
