### ISSUE TITLE
bug: Incorrect Websocket HTTP/HTTP PROXY Integration

### ISSUE THREAD

**Issue by jl-DaDar** [localstack/localstack#5851]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

192.168.48.7 - - [12/Apr/2022 17:35:12] "POST /connection/websocket/ HTTP/1.1" 200 -
INFO:root:POST  request,
Path: /connection/websocket/
Headers:
User-Agent: python-requests/2.25.1
Accept-Encoding: gzip, deflate
Accept: */*
connection: Upgrade
sec-websocket-version: 13
sec-websocket-key: yMViiS4z7+gIxPf4vtkXWQ==
upgrade: websocket
sec-websocket-extensions: permessage-deflate; client_max_window_bits
host: 127.0.0.1:4610
Content-Length: 22
Body:
{"action": "$connect"}

### Expected Behavior

HTTP example
https://hookbin.com/9X9qy8NVwkiW1OXXwMWo/jWmn0GGRM
HTTP PROXY example
https://hookbin.com/Z2LYlrEppYsK6bmmQLKy/LRpeYq9LD

no request body

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

create a websocket api, setup http integration for $connect route, connect to the api and try to capture the http integration request

### Environment

```markdown
- OS: 
- LocalStack:
```

**Comment by whummer** [comment]
Hi @jl-DaDar , thanks for reporting. Looks like the hookbin.com links are expired by now (getting a 404 error) - would you mind sharing the details one more time (either directly here on the Github issue, or as a text file attachment..). Any steps to help us replicate this issue more easily would be appreciated.. Thanks!
