### ISSUE TITLE
bug: TransactionCancelledException not properly filled in DynamoDB Java SDK

### ISSUE THREAD

**Issue by danielfmsouza** [localstack/localstack#5860]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm trying to test the TransactionWriteItems feature of DynamoDB using Java SDK.

According to AWS documentation, if at least one of the items that are part of the transaction fail we'll get a `TransactionCanceledException`. 

Specifically for Java SDK consumers, we have `getCancellationReasons()` property that retrieves all cancellation reasons. [The documentation](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/dynamodbv2/model/TransactionCanceledException.html#:~:text=DynamoDB%20cancels%20a%20TransactWriteItems%20request,operation%20targets%20the%20same%20item.) says:
_If using Java, DynamoDB lists the cancellation reasons on the `CancellationReasons` property. This property is not set for other languages. Transaction cancellation reasons are ordered in the order of requested items, if an item has no error it will have NONE code and Null message._

Unfortunately this property comes empty when using `localstack`.

Please check the picture below with debugging information. Although the exception detailed message is properly set with two reasons, they are not present in the list:
![Localstack](https://user-images.githubusercontent.com/947854/163290163-679801c9-bf8c-4380-9154-da000c5fb42b.jpg)

### Expected Behavior

The property [`getCancellationReasons`](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/dynamodbv2/model/TransactionCanceledException.html#getCancellationReasons--) should be filled with all reasons provided in `detailMessage`.

Exception class: [`TransactionCanceledException`](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/dynamodbv2/model/TransactionCanceledException.html)

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker-compose.yml

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

Any operation using `TransactionWriteItems` which ends up in exception. 
Then the exception must be caught using the Java AWS SDK, since it's the one the implements the referred property.

Code example:

### Environment

```markdown
- OS: macOS Monterey 12.3
- LocalStack: 0.14.2
- DynamoDB Java SDK: software.amazon.awssdk:dynamodb -> 2.17.148
```

### Anything else?

This problem goes away when pinning the latest version of localstack in `docker-compose`!
See the difference:

* Broken version (without any specific version in `docker-compose.yml`):
LocalStack version: 0.14.2
2022-04-14T01:07:53.130783425Z LocalStack build date: 2022-04-10
2022-04-14T01:07:53.130797008Z LocalStack build git hash: e601ead5

* Working version (specifying `image: localstack/localstack:0.14.2` in `docker-compose.yml`):
LocalStack version: 0.14.2
2022-04-14T00:55:28.957122761Z LocalStack build date: 2022-04-01
2022-04-14T00:55:28.957124428Z LocalStack build git hash: 3d8b2835

I presume we (can) get nightly builds or such when we don't specify the version when pulling the image.

**Comment by bblommers** [comment]
If it's helpful, this error was raised in Moto as well: https://github.com/spulec/moto/issues/5010, and we fixed it as of moto >= 3.1.5.dev12

**Comment by grze888siu** [comment]
- [ ]

**Comment by grze888siu** [comment]
- [ ]

**Comment by grze888siu** [comment]
**![image](https://user-images.githubusercontent.com/103291574/167172218-a0532718-ee7c-4313-a34c-6a77696d9321.png)**

**Comment by grze888siu** [comment]
- [ ]

**Comment by grze888siu** [comment]
- [ ]

**Comment by alexrashed** [comment]
Hey @brucekaufman!
We just released a fix for the issue, it is already contained in the latest image on DockerHub.
Please let us know if you still experience any issues concerning the error messages.
