### ISSUE TITLE
bug: cloudtrail doesn't write event to bucket

### ISSUE THREAD

**Issue by yangzhang21** [localstack/localstack#5867]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I used to use cloudtrail in 0.12.10  to log event with the script
```
AWSL='aws --endpoint-url http://localhost:4566'
$AWSL s3 mb s3://cloudtrail-bucket
$AWSL cloudtrail create-trail --name cloudtrail-abc--s3-bucket-name cloudtrail-bucket --s3-key-prefix 12345 --is-multi-region-trail 
```
which works fine. 
now I upgrade to 0.14.2. seems cloudtrail is broken. bucket is created, cloudtrail is created, but cloudtrail is not written to the bucket. 

using cli command `aws --endpoint-url http://localhost:4566 cloudtrail lookup-events`, i can see all the events, which means cloudtrail is working, but somehow it doesn't write to bucket any more.  

I have a valid pro account.

any thoughts?

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

  localstack:
    image: localstack/localstack:0.14.2
    container_name: customer-env
    environment:
      - AWS_DEFAULT_REGION=us-west-2
      - EDGE_PORT=4566
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEBUG=1
      - LAMBDA_DOCKER_NETWORK=docker-compose_default
      - MAIN_CONTAINER_NAME=customer-env
      - LOCALSTACK_API_KEY=<my pro key>
      - HOSTNAME_EXTERNAL=customer-env
    ports:
      - 443:443
      - 4566:4566
      - 4571:4571
    volumes:
      - "./customer-env:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./customer-env-scripts:/docker-entrypoint-initaws.d

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```
AWSL='aws --endpoint-url http://localhost:4566'
$AWSL s3 mb s3://cloudtrail-bucket
$AWSL cloudtrail create-trail --name cloudtrail-abc--s3-bucket-name cloudtrail-bucket --s3-key-prefix 12345 --is-multi-region-trail 
```

### Environment

```markdown
- OS: Tried on MacOS and Ubuntu/Windows 11, same behavior
- LocalStack: 0.14.2
```

**Comment by MarcelStranak** [comment]
Hello,

I was unable to reproduce your issue.  Can you please confirm that you see the files in S3 using the script below? Thank you.

```bash

aws --endpoint-url http://localhost:4566 s3 mb s3://cloudtrail-bucket
aws --endpoint-url http://localhost:4566 cloudtrail create-trail --name cloudtrail-abc --s3-bucket-name cloudtrail-bucket --s3-key-prefix 12345 --is-multi-region-trail

aws --endpoint-url http://localhost:4566 cloudtrail start-logging --name cloudtrail-abc

aws --endpoint-url http://localhost:4566 s3 mb s3://s3-for-cloudtrail-logs
echo "hello world" > object1.txt && awslocal s3api put-object --bucket s3-for-cloudtrail-logs --key myapp/object1.txt --body object1.txt
aws --endpoint-url http://localhost:4566 cloudtrail lookup-events
aws --endpoint-url http://localhost:4566 s3api list-objects  --bucket cloudtrail-bucket
```

**Comment by yangzhang21** [comment]
@MarcelStranak  looks we missed `aws --endpoint-url http://localhost:4566 cloudtrail start-logging --name cloudtrail-abc` to start the cloudtrail. after I add this to the script it works properly now. but weird it worked without this line in `0.12.10` . I am going to close this ticket
