### ISSUE TITLE
bug: S3 doesn't verify the X-Amz-Content-Sha256 header

### ISSUE THREAD

**Issue by Cyberax** [localstack/localstack#5868]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The current S3 emulation code in `S3_SKIP_SIGNATURE_VALIDATION=0` mode checks for the `Content-MD5` header validity but ignores the `X-Amz-Content-Sha256` header.

This causes problems for our tests that depend on the handling of this header.

### Expected Behavior

The tests should check for the SHA256 sum, just like it checks the MD5 sum validity in https://github.com/localstack/localstack/blob/3d7dfbbc958d17c66d748d83f4f729cf393da7de/localstack/services/s3/s3_listener.py#L902 .

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

You need to submit a request with mismatched `X-Amz-Content-Sha256` header.

### Environment

```markdown
- OS: macOS
- LocalStack: 0.14.2
```

**Comment by whummer** [comment]
Thanks for reporting this issue @Cyberax ! Since you seem to have a fairly good understanding of what the logic could look like, do you think you could spike out a first pull request? Even if it's just a first draft implementation with a basic test, that would be super helpful - we'll be happy to chime in and provide guidance. Thanks in advance!

**Comment by swaingotnochill** [comment]
Hi Team and @Cyberax,

I was trying to reproduce this issue. For now, I am testing a 'GET' request with Authorization header and 'x-am-content-sha256' header. 
I was using the below code to make a request with mistmatched headers.


```
import sys, os, base64, datetime, hashlib, hmac
from attr import has
import requests

method = 'GET'
service = 's3'
host = '127.0.0.1:4566'
region = ''
request_parameters = ''
endpoint = 'http://localbucket.s3.localhost.localstack.cloud:4566/test4.txt'

def sign(key,msg):
    return hmac.new(key, msg.encode('utf-8'), hashlib.sha256).digest()

def getSignatureKey(key, dateStamp, regionName, serviceName):
    kDate = sign(('AWS4' + key).encode('utf-8'), dateStamp)
    kRegion = sign(kDate, regionName)
    kService = sign(kRegion, serviceName)
    kSigning = sign(kService, 'aws4_request')
    return kSigning

access_key = 'test'
secret_key = 'test'

t = datetime.datetime.utcnow()
amzdate = t.strftime('%Y%m%dT%H%M%SZ')
datestamp = t.strftime('%Y%m%d')


canonical_uri = '/'
canonical_querystring = request_parameters

# Testing with wrong x-amz-content-sha256 header
payload_hash = hashlib.sha256(('Not an empty string').encode('utf-8')).hexdigest()

# Testing with correct x-amz-content-sha256 header
# Since its a get request, payload will be empty string.
# hash_payload = hashlib.sha256(('').encode('utf-8')).hexdigest()

canonical_headers = 'host:'+ host + '\n' + 'x-amz-content-sha256:' + payload_hash + '\n' + 'x-amz-date:' + amzdate + '\n'

signed_headers = 'host;x-amz-content-sha256;x-amz-date'

canonical_request = method + '\n' + canonical_uri + '\n' + canonical_querystring + '\n' + canonical_headers + '\n' + signed_headers + '\n' + payload_hash


algorithm = 'AWS4-HMAC-SHA256'
credential_scope = datestamp + '/' + region + '/' + service + '/' + 'aws4_request'

string_to_sign = algorithm + '\n' + amzdate + '\n' + credential_scope + '\n' + hashlib.sha256(canonical_request.encode('utf-8')).hexdigest()

signing_key = getSignatureKey(secret_key, datestamp, region, service)

signature = hmac.new(signing_key, (string_to_sign).encode('utf-8'), hashlib.sha256).hexdigest()

authorization_header = algorithm + ' ' + 'Credential=' + access_key + '/' + credential_scope + ', ' + 'SignedHeaders=' + signed_headers + ', ' + 'Signature=' + signature

headers = {'x-amz-date' : amzdate, 'x-amz-content-sha256' : payload_hash, 'Authorization' : authorization_header }

request_url = endpoint + '?' + canonical_querystring

print('\nBEGIN REQUEST------------------\n')
print('REQUEST URL =' + request_url)
r = requests.get(request_url, headers=headers)


print('\nRESPONSE----------\n')
print('RESPONSE CODE : %d\n' % r.status_code)
print(r.text)

```

The output received is: 
```
BEGIN REQUEST------------------

REQUEST URL =http://localbucket.s3.localhost.localstack.cloud:4566/test4.txt?

RESPONSE----------

RESPONSE CODE : 200

Test without checksum algorithm

```

Can you please verify if this is the exact issue you were facing? From the looks of it, we are not verifying the 'x-amz-content-heder' whereas this is mandatory for all Signature Version 4 requests.

If there are any issues in the way I am reproducing the error, please let me know. 

Once it is confirmed or I am able to reproduce this, I wish to work on this issue. :)
