### ISSUE TITLE
bug: `Unable to find details for Lambda` when restarting docker-compose with hotswap

### ISSUE THREAD

**Issue by Ramin314** [localstack/localstack#5887]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When running localstack in a docker compose setup, hotswapped lambda functions do not persist between restarts even though it looks like they are there. When running `docker-compose up` the first time, everything works. Hitting `Ctrl+C` and then running `docker-compose up` again, I hotswap deploy the lambda and it looks like it's worked, but when pinging the lambda endpoint, it yields

```
localstack_1  | 2022-04-18T18:02:00.285:DEBUG:localstack.services.awslambda.lambda_api: Running Lambda function arn:aws:lambda:us-east-1:000000000000:function:AppStack-HelloHandler2E4FBA4D-19ba50b7 from API Gateway invocation: GET /hello
localstack_1  | 2022-04-18T18:02:00.285:DEBUG:localstack.services.awslambda.lambda_api: Unable to find details for Lambda arn:aws:lambda:us-east-1:000000000000:function:AppStack-HelloHandler2E4FBA4D-19ba50b7 in region us-east-1
```

### Expected Behavior

Lambda functions should run as before

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

docker-compose.yml:

```
version: "2.1"
services:
  localstack:
    image: localstack/localstack
    ports:
      - "443:443"
      - "4510-4520:4510-4520"
      - "4566-4620:4566-4620"
    environment:
      - HOSTNAME_EXTERNAL=localstack
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - HOST_TMP_FOLDER=${PWD}/localstack-vol
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LAMBDA_EXECUTOR=docker
      - LAMBDA_NETWORK=bridge
      - LOCALSTACK_API_KEY=localstack_api_key
      - LAMBDA_STAY_OPEN_MODE=0
      - LAMBDA_REMOTE_DOCKER=0
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./localstack-vol:/tmp/localstack"
  app:
    build: .
    expose:
      - "4566"
    volumes:
    - "${PWD}:${PWD}"
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "/etc/passwd:/etc/passwd"
    depends_on:
      - localstack
    command: sh -c "/wait && cd ${PWD} && cdklocal deploy --outputs-file cdk-outputs.json --require-approval never --hotswap AppStack'"
    environment:
      - WAIT_HOSTS=localstack:4566
      - LOCALSTACK_HOSTNAME=localstack
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
```

The dockerfile is nothing special:

```
FROM node:14-alpine

# Add docker-compose-wait tool
ENV WAIT_VERSION 2.7.2
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/$WAIT_VERSION/wait /wait
RUN chmod +x /wait

RUN apk add docker
RUN apk add python3
RUN apk add aws-cli
```
#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

The cdk code just creates an API gateway with a lambda function that returns hello world

```
    const api = new apigateway.RestApi(this, 'api', {
      description: 'api gateway',
      defaultCorsPreflightOptions: {
        allowHeaders: [
          'Content-Type',
          'X-Amz-Date',
          'Authorization',
          'X-Api-Key',
        ],
        allowMethods: [
          'OPTIONS',
          'GET',
          'POST',
          'PUT',
          'PATCH',
          'DELETE',
        ],
        allowCredentials: true,
        allowOrigins: ['*'],
      },
    });

    const helloLambda = new NodejsFunction(this, 'HelloHandler', {
      runtime: lambda.Runtime.NODEJS_14_X,
      memorySize: 1024,
      timeout: Duration.seconds(5),
      handler: 'handler',
      entry: path.join(__dirname, '/../routes/hello.js'),
    });
```

with hello.js

```
export async function handler(event) {
  return {
    statusCode: 200,
    headers: { 'Content-Type': 'text/plain' },
    body: `Hello, world! You've hit ${event.path}\n`,
  };
};
```

### Environment

```markdown
- OS: Ubuntu 20.04
- LocalStack: latest
```

**Comment by whummer** [comment]
Hi @Ramin314, thanks for reporting . Please note that by default the resources in LocalStack are not persisted - i.e., after a restart of your LocalStack container you'll need to re-create the Lambda function definitions (only the Lambda definition needs to be re-created via `CreateFunction`, the mounted hotswap Lambda directories themselves can remain unchanged). We have some more advanced support for persistence, but that is only available in the Pro version of LocalStack. 

One thing you could look into is to create a startup script - see `INIT_SCRIPTS_PATH` configuration [here](https://docs.localstack.cloud/localstack/configuration/#core) . Hope that helps, please keep us posted how it goes. Thanks
