### ISSUE TITLE
Feature request: add warning if FIFO queue is missing fifo attributes

### ISSUE THREAD

**Issue by maples3** [localstack/localstack#5888]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Our team has been using localstack for some SQS queues, and recently we spent quite a bit of time troubleshooting issues when someone rebuilt their Docker instance (we were not pinning localstack to a specific version, so it was pulling the latest).

Command:
`awslocal sqs create-queue --queue-name queueName.fifo;`

Error message:
`An error occurred (InvalidParameterValue) when calling the CreateQueue operation: Can only include alphanumeric characters, hyphens, or underscores. 1 to 80 in length`

I'm sure it's obvious to people who use this all the time that we were just missing `--attributes FifoQueue=true` parameter, but it was not to us.  Especially because this command had worked perfectly find in the previous version of localstack (0.13.0).

It would be nice if there was a check to see if the queue ended in ".fifo", and printed a warning along the lines of "Did you forget to set the FifoQueue=true attribute?"

### 🧑‍💻 Implementation

In the area which prints the above error message
```
if (queueName.endsWith(".fifo") && queueAttributes.fifoQueue == false)
{
    echo "You're trying to create a queue ending in \".fifo\".  Please use the --attributes parameter to set FifoQueue appropriately.
}
```

**Comment by thrau** [comment]
The SQS provider now (like AWS) correctly raises an `InvalidParameterValue` when trying to use the `.fifo` queue suffix without the `FifoQueue` attribute and vice versa.

**Comment by bartmcleod** [comment]
When will this be available to the localstack docker container? This still has the issue, at least with the aws-sdk for php.

**Comment by bartmcleod** [comment]
See my [EDIT] in the above comment if you run into the same issue. FifoQueue needs to be under Attributes
