### ISSUE TITLE
bug: sending email with cognito

### ISSUE THREAD

**Issue by ugurhicyilmam** [localstack/localstack#5889]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm getting the following error after I signup a new user with cognito:

`localstack_1  | 2022-04-18T20:58:11.521:DEBUG:localstack_ext.bootstrap.email_utils: Sending email to test@test.com
localstack_1  | 2022-04-18T20:58:12.585:DEBUG:localstack_ext.bootstrap.email_utils: Unable to run login/auth command against SMTP server, skipping: key: expected bytes or bytearray, but got 'str'
localstack_1  | 2022-04-18T20:58:12.809:DEBUG:localstack_ext.services.cognito_idp.provider: Unable to send email, please update SMTP configuration: (500, b'5.5.1 Invalid command', 'test@example.com')
`

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

```
version: '3.1'

services:

  localstack:
    image: localstack/localstack:latest
    network_mode: bridge
    environment:
      - DEBUG=1
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - LAMBDA_EXECUTOR=docker
      - HOST_TMP_FOLDER=${TMPDIR:-/tmp/}localstack
      - LAMBDA_REMOTE_DOCKER=0
      - SERVICES=dynamodb,lambda,sqs,sts,s3,cloudformation,iam,cloudwatch,appsync,cognito,ses,sns
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LOCALSTACK_API_KEY={api key}
      - EXTRA_CORS_ALLOWED_ORIGINS=*
      - REQUIRE_PRO=1
      - SMTP_HOST={smtp host}
      - SMTP_USER={smtp user}
      - SMTP_PASS={smtp password}
      - SMTP_EMAIL={smtp email}
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4571:4571"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

### Environment

```markdown
- OS: macOS Monterey 12.1
- LocalStack: latest
```

**Comment by whummer** [comment]
Hi @ugurhicyilmam , thanks for reporting. Can you please share your SMTP configuration - I'm assuming you are setting the `SMTP_*` config variables, right? Which SMTP server are you using to send out the emails? 

Also - we have in the meantime pushed a couple of enhancements for Cognito, can you please double-check if this problem persists with the `latest` Docker image? Thanks for your help!
