### ISSUE TITLE
bug: health endpoint does not return feature states

### ISSUE THREAD

**Issue by nao23** [localstack/localstack#5901]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`/health` endpoint does not return feature states which was stored from [docker-entrypoint.sh](https://github.com/localstack/localstack/blob/v0.14.2/bin/docker-entrypoint.sh#L68) .

```shell
❯ docker run -p 4566:4566 -d localstack/localstack:latest
❯ curl -XGET -s http://127.0.0.1:4566/health | jq .
{
  "services": {
    "acm": "available",
    "apigateway": "available",
    "cloudformation": "available",
    "cloudwatch": "available",
    "config": "available",
    "dynamodb": "available",
    "dynamodbstreams": "available",
    "ec2": "available",
    "es": "available",
    "events": "available",
    "firehose": "available",
    "iam": "available",
    "kinesis": "available",
    "kms": "available",
    "lambda": "available",
    "logs": "available",
    "opensearch": "available",
    "redshift": "available",
    "resource-groups": "available",
    "resourcegroupstaggingapi": "available",
    "route53": "available",
    "route53resolver": "available",
    "s3": "available",
    "s3control": "available",
    "secretsmanager": "available",
    "ses": "available",
    "sns": "available",
    "sqs": "available",
    "ssm": "available",
    "stepfunctions": "available",
    "sts": "available",
    "support": "available",
    "swf": "available"
  },
  "version": "0.14.2"
}
```

### Expected Behavior

`/health` endpoint return feature states.

### How are you starting LocalStack?

With a `docker run` command

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

* `docker run -p 4566:4566 -d localstack/localstack:latest`

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

* `curl -XGET -s http://127.0.0.1:4566/health | jq .`

### Environment

```markdown
- OS: macOS v12.2 (Monterey)
- LocalStack: latest
```

**Comment by eltonsv** [comment]
+1, we're also seeing the issue as well on our CI runs after the latest image push 

Not sure if this is the exact digest
https://hub.docker.com/layers/localstack/localstack/localstack/latest/images/sha256-7098b281d66be6b4a389e8fa96d2c7e07896f03ae53767b8bc8f524cf55e649e?context=explore

**Comment by thrau** [comment]
thanks for the report, and for digging into this @nao23. the problems around the `/health` endpoint should now be fixed!
