### ISSUE TITLE
IAmazonCognitoIdentityProvider with Localstack  Pro version missing user attributes in AdminCreateUserAsync() successful response

### ISSUE THREAD

**Issue by alina-tudorache** [localstack/localstack#5904]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We are using IAmazonCognitoIdentityProvider with Localstack  Pro version and when doing AdminCreateUserAsync() with a AdminCreateUserRequest that contain the User attributes the response is successful but the User contain zero attributes in the response, we need to do again a get with AdminGetUserAsync() to get the user attributes set. 

### Expected Behavior

The attributes should be in User response, if we do again a get - AdminGetUserAsync() the response contain the User attributes set

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal s3 mb s3://mybucket
AddLocalStack extension

### Environment

```markdown
- OS: 
- LocalStack:
```

**Comment by giograno** [comment]
Hi @alina-tudorache, thank you very much for reporting the issue. 
We have pushed a fix with the `latest` Docker image. Give it a try and please let us know if you encounter any other problem. Thank you very much 🙏
