### ISSUE TITLE
 API action 'DescribeNetworkAcls' for service 'ec2' not yet implemented

### ISSUE THREAD

**Issue by veeruns** [localstack/localstack#5911]
### Is there an existing issue for this?

- [X] I have searched the existing issues and read the documentation

### Question

When querying for network-acls with filters using AWS CLI,ending up with an error.

`An error occurred (InternalFailure) when calling the DescribeNetworkAcls operation: API action 'DescribeNetworkAcls' for service 'ec2' not yet implemented`

Command: 

`aws --endpoint http://localhost:4566 ec2 describe-network-acls --filters Name=entry.rule-number,Values=100`

without the filters, describe-network-acls seems to work correctly. 

Attachment: One command with filter (--debug)

[output-filter.txt](https://github.com/localstack/localstack/files/8534235/output-filter.txt)

Command without filter
[output-nofilter.txt](https://github.com/localstack/localstack/files/8534237/output-nofilter.txt)

**Comment by viren-nadkarni** [comment]
PR submitted upstream https://github.com/spulec/moto/pull/5049
