### ISSUE TITLE
feature request: Support for Lambda Function URLs

### ISSUE THREAD

**Issue by bnol** [localstack/localstack#5914]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Lambda Function URLs have been officially released. Any plan to support it?

https://aws.amazon.com/blogs/aws/announcing-aws-lambda-function-urls-built-in-https-endpoints-for-single-function-microservices/
https://docs.aws.amazon.com/lambda/latest/dg/lambda-urls.html

**Comment by tycobbb** [comment]
neat timing, was just looking to use this. any idea if or when the feature might land?

**Comment by pinzon** [comment]
@tycobbb it looks simple enough but in the best case could be next week.

**Comment by tycobbb** [comment]
awesome thanks for responding :)

**Comment by evbo** [comment]
When I invoke a lambda _synchronously_ (accidentally, my lambda is an `async` Rust function) I get a curious error message documented here:
https://github.com/localstack/localstack/issues/3935
https://github.com/localstack/localstack/issues/3871

Is the url logged actually an endpoint intended to show status? Are there any docs explaining how to access `functions` urls such as these? 
> http://localhost:4566/2015-03-31/functions/rustTest

For instance, if I load that URL it appears to default to `us-east-1`, but my infrastructure is in `us-west-2`, so I'm not sure how to modify the url to point to `us-west-2`

Thanks and hopefully I've stumbled upon early beta features for listing lambda status? Maybe even progress/logs?!

**Comment by pinzon** [comment]
hi @evbo I think I understand your situation but could you open a new issue for it? for better tracking. Here is for the Lamda URL feature, which allows the invocation of a lambda through an easy to set up endpoint.

**Comment by pinzon** [comment]
@evbo thanks for reporting it. I added a commit in my PR that should help with that situation even though this issue and the PR are for another feature.

**Comment by pinzon** [comment]
Hi @evbo the feature was just added to Localstack  so I'm closing this issue. :wave:

**Comment by Smiles840** [comment]
Handle it as they say  hahha, thank you bro
