### ISSUE TITLE
feature request: expose arbitrary ports for connecting to EC2 

### ISSUE THREAD

**Issue by noorvir** [localstack/localstack#5931]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

We have a gRPC service running in an EC2 instance on localstack which we'd like to connect to over port `9000` while testing. Currently, the localstack networking for EC2 instances only exposes port 22 for connecting over SSH. Ideally, we want the following:

1. Issue a call to the localstack endpoint to run an EC2 instance, which gets spawned as a Docker container.
2. The instance is assigned a private IP that is queryable through the AWS API call to `describe-instances` at `Reservations[0].Instances[0].PrivateIpAddress`. 
3. We are able to connect to the insatance at `privateIp:port`

### 🧑‍💻 Implementation

It might be tricky to expose arbitrary ports and bind them to the corresponding ones on the host since they might already be in use. Perhaps the user could specify the port mapping for EC2 instances when starting the localstack container through docker compose.

**Comment by viren-nadkarni** [comment]
Thanks for reporting this, tracking the feature request at #6546
