### ISSUE TITLE
feature request: Support mounting volumes to ECS containers

### ISSUE THREAD

**Issue by davecardwell** [localstack/localstack#5941]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

I am developing a Node.js application that will ultimately be deployed to ECS.

During development it would be useful to be able to mount my code into the container so I can use hot-reloading to achieve a quick feedback loop as I make changes, while keeping the local infrastructure as close as possible to production.

Currently I am forced to use a separate container with Docker Compose that does not truly reflect our production environment.

### 🧑‍💻 Implementation

Perhaps it could be implemented as an EFS volume similar to the Lambda \_\_local\_\_ S3 bucket? Then that can be attached to the ECS task in the standard way.

**Comment by ptrhck** [comment]
Any plans to support this in the near future? Is there any workaround?

**Comment by joshbalfour** [comment]
@ptrhck `DOCKER_FLAGS` might help https://docs.localstack.cloud/references/configuration/#docker

**Comment by joshbalfour** [comment]
I worked around this by applying this patch to [docker_sdk_client.py](https://github.com/localstack/localstack/blob/v1.3.0/localstack/utils/container_utils/docker_sdk_client.py)

docker_sdk_client.py.patch:
```patch
532a533,535
>             mount_volumes = [
>                 (os.environ['BUILD_DIR'],os.environ['BUILD_DIR_INSIDE_CONTAINER'])
>             ]
681c684
<             raise ContainerException() from e
---
>             raise ContainerException() from e
\ No newline at end of file

```

Dockerfile:
```Dockerfile
FROM localstack/localstack-pro:1.3.0

COPY docker_sdk_client.py.patch /opt/code/localstack/localstack/utils/container_utils

RUN apt install patch -y && \
  cd /opt/code/localstack/localstack/utils/container_utils && \
  patch docker_sdk_client.py docker_sdk_client.py.patch && \
  apt remove patch -y


```

**Comment by whummer** [comment]
Hi @davecardwell @ptrhck  @joshbalfour , thanks for reporting. We have now added initial support for ECS task volume mounts, which should (hopefully) help you achieve the functionality you're looking for.

We can use the ECS bind mounts feature, as per the docs: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/bind-mounts.html

For example, you can register a task definition similar to the following to mount a host path `/host/path` into the container under `/container/path` (using Python in this example):
```
        ecs_client.register_task_definition(
            family=task_family,
            containerDefinitions=[
                {
                    "name": container_name,
                    "image": "alpine",
                    "command": ["..."],
                    "mountPoints": [
                        {"containerPath": "/container/path", "sourceVolume": "test-volume"}
                    ],
                }
            ],
            volumes=[{"host": {"sourcePath": "/host/path"}, "name": "test-volume"}],
        )
```

We have yet to update our docs with this new feature (following soon). Can you please pull the `latest` Docker image and give it a try? Looking forward to getting your feedback.. Thanks!

**Comment by whummer** [comment]
We have now updated our docs to include ECS task mounting as outlined above: https://docs.localstack.cloud/user-guide/aws/elastic-container-service/#mounting-local-directories-for-ecs-tasks

Closing this issue as resolved - please do keep us posted if this solution works for your use case.. Looking forward to getting your feedback. Thanks!
