### ISSUE TITLE
feature request: Prevent bad API Destination Connection names

### ISSUE THREAD

**Issue by bsschwa** [localstack/localstack#5943]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Currently, AWS restricts the API Destination Connection with the following restrictions:

> Maximum of 64 characters consisting of numbers, lower/upper case letters, .,-,_.

However, the CLI does not enforce these rules, causing the connection ARN to be invalid.
Ex:
```
awslocal events create-connection --name "API ConnectionWithSpace" --authorization-type APIKEY --auth-parameters '{"ApiKeyAuthParameters":{"ApiKeyName":"a","ApiKeyValue":"a"}}'

awslocal events create-connection --name "APIConnectionSpecialChar$" --authorization-type APIKEY --auth-parameters '{"ApiKeyAuthParameters":{"ApiKeyName":"a","ApiKeyValue":"a"}}'

awslocal events create-connection --name "APIConnectionMoreThanSixtyFourCharacters012345678901234567890123456789" --authorization-type APIKEY --auth-parameters '{"ApiKeyAuthParameters":{"ApiKeyName":"a","ApiKeyValue":"a"}}'
```

![image](https://user-images.githubusercontent.com/3469050/165583788-d67ab973-f510-46f1-b635-fde1cd981481.png)

![image](https://user-images.githubusercontent.com/3469050/165581563-90538b86-5827-41bf-974d-052e8c2af29c.png)

**Comment by pinzon** [comment]
The solution has been merged. Thank you for reporting the issue.
