### ISSUE TITLE
bug: LocalStack Cloud doesn't set content type of uploaded files in S3

### ISSUE THREAD

**Issue by mad-ice** [localstack/localstack#5947]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When uploading a file to S3 through LocalStack Cloud it's content type is always set to `application/octet-stream`. This causes issues for files used in web applications like SVG or CSS files (related: https://github.com/localstack/localstack/issues/5814). This results in the asset not being loaded properly by the browser. The request does return status 200 OK, but since the Content-Type header is incorrect the asset doesn't load. This issue does not occur on files that we uploaded through our own "media manager" in which we do include the Content-Type header.
![image](https://user-images.githubusercontent.com/10806423/165737320-dbdd290d-5eb2-4276-961f-a276e913ca41.png)

After looking for a while it seems that this is expected behavior if no Content-Type`header is used when executing the PutObject API call to S3 (see: https://github.com/localstack/localstack/pull/565). This also means that the fix should be pretty straight forward, which is to read the file's content type after uploading to LocalStack Cloud and including it in the PutObject request to S3.

### Expected Behavior

I expect the content type of files to be set to their actual value instead of always being `application/octet-stream`. This should allow browsers to use web assets properly.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

1. Have LocalStack running locally.
2. Create a bucket in S3 (either programmatically or via LocalStack Cloud, doesn't matter).
3. Upload an SVG file to the bucket via LocalStack Cloud.
4. Open the network tab in your browser's developer console.
5. Download the file.
6. The `Content-Type` response header is currently `application/octet-stream`, but should have been `image/svg+xml`.

### Environment

```markdown
- OS: N/A?
- LocalStack: Latest
```

**Comment by doublevcodes** [comment]
Hello, I'm going to attempt to solve this issue.

**Comment by macnev2013** [comment]
Hello @mad-ice, Thank you for reporting the issue. 

This has been resolved in the `latest` version of LocalStack. 
Could you possibly try again with the 'latest' version? 

Please let us know if the problem persists. Thanks.
