### ISSUE TITLE
question: is there a way to have more than one record in lambda dynamo stream 

### ISSUE THREAD

**Issue by kip-13** [localstack/localstack#5951]
### Is there an existing issue for this?

- [X] I have searched the existing issues and read the documentation

### Question

I would like to know if exist a way to have the correct numbers of records in lambda from dynamo streams.
I configured the batch size in sam template to 20 but always the num of records is 1.

Thanks for this amazing project.

**Comment by MarcelStranak** [comment]
Hi, could you please share more details about your question? Could you provide a working snippet of the code? Thanks.

**Comment by kip-13** [comment]
Yes, of course.

Now we have a serverless function defined in a template where the value of [`events > stream > batchSize`](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-function-dynamodb.html#sam-function-dynamodb-batchsize) is 10.
I did some tests with localstack, the records received in the lambda are always 1, not 10 or at least 2 because it could affect `MaximumBatchingWindowInSeconds` value.

Trying to search the snippet where I saw the stream event trigger, I notice there is a new file which create a lambda payload with batch size :thinking: 
https://github.com/localstack/localstack/blob/0ff7f475ace522fa50aaf11dafee2f1b42b03d0c/localstack/services/awslambda/event_source_listeners/stream_event_source_listener.py#L182-L188

Im going to test it, but could you help me if the snippet above would solve this situation? Thanks
