### ISSUE TITLE
Error:'NoneType' object has no attribute 'group' Traceback when invoking lambdas

### ISSUE THREAD

**Issue by AnshuTylerTech** [localstack/localstack#5958]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi, I have setup localstack in docker on WSL2. When trying to invoke the lambdas an internal server error 500 is thrown. I used these commands to verify that everything was up and running.
awslocal s3 ls
awslocal apigateway --endpoint=http://localhost:4566/ get-rest-apis

```
2022-04-19T23:51:27.921:INFO:localstack.utils.threads: Thread run method <function AdaptiveThreadPool.submit.<locals>._run at 0x7f7ca22f9940>(None) failed: 'NoneType' object has no attribute 'group' Traceback (most recent call last):
  File "/opt/code/localstack/localstack/utils/threads.py", line 38, in run
    result = self.func(self.params, **kwargs)
  File "/opt/code/localstack/localstack/utils/asyncio.py", line 30, in _run
    return fn(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 970, in handler
    return modify_and_forward(
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 514, in wrapper
	
    value = func(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 594, in modify_and_forward
    listener_result = listener.forward_request(
  File "/opt/code/localstack/localstack/services/edge.py", line 176, in forward_request
    result = do_forward_request(api, method, path, data, headers, port=port)
  File "/opt/code/localstack/localstack/services/edge.py", line 231, in do_forward_request
    result = do_forward_request_inmem(api, method, path, data, headers, port=port)
  File "/opt/code/localstack/localstack/services/edge.py", line 255, in do_forward_request_inmem
    response = modify_and_forward(
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 514, in wrapper
    value = func(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 594, in modify_and_forward
    listener_result = listener.forward_request(
  File "/opt/code/localstack/localstack/services/apigateway/apigateway_listener.py", line 105, in forward_request
    result = invoke_rest_api_from_request(invocation_context)
  File "/opt/code/localstack/localstack/services/apigateway/apigateway_listener.py", line 440, in invoke_rest_api_from_request
    set_api_id_stage_invocation_path(invocation_context)
  File "/opt/code/localstack/localstack/services/apigateway/apigateway_listener.py", line 398, in set_api_id_stage_invocation_path
    api_id = extract_api_id_from_hostname_in_url(host_header)
  File "/opt/code/localstack/localstack/services/apigateway/apigateway_listener.py", line 435, in extract_api_id_from_hostname_in_url
    api_id = match.group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```

Here are some details.
Web request is created
```
var webRequest = WebRequest.Create($"http://{AwsApiGatewayRequest.Host}{AwsApiGatewayRequest.AbsolutePath}");

Host and AbsolutePath are fed from these attributes:
"AwsDocumentList": {
    "LambdaHost": "localhost:4566/restapis/lyilfjse93/local/_user_request_",
    "LambdaPath": "/list-objects/"
  },
```

Internal 500 error is thrown when a GetResponse() method is called
response = request.GetResponse();

The logs are from this GetResponse() error.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal s3 mb s3://mybucket

### Environment

```markdown
- OS: Ubuntu
- LocalStack:
```

**Comment by whummer** [comment]
HI @AnshuTylerTech , thanks for reporting. Can you please share the image hash/age of the LocalStack Docker image on your local machine? We believe that this issue should be fixed in the meantime - can you please do a `docker pull localstack/localstack` and give it another try with the latest version? Thanks!

**Comment by kylejPomelo** [comment]
Hi @whummer I was able to reproduce this issue when I was calling `aws lambda create-function` only when there were layers present - 

this command failed - 
```
aws lambda create-function --endpoint-url=http://localhost:4566  \
  --function-name my-lambda-function \
  --runtime python3.8 \
  --region us-west-2 \
  --role $ROLE_ARN \
  --layers \"$LAYER_1_ARN\" \"$LAYER_2_ARN\" \"$LAYER_3_ARN\" \"$LAYER_4_ARN\" \
  --zip-file fileb://source.zip \
  --handler lambda-function.py
```

while this would succeed - 

```
aws lambda create-function --endpoint-url=http://localhost:4566  \
  --function-name my-lambda-function \
  --runtime python3.8 \
  --region us-west-2 \
  --role $ROLE_ARN \
  --zip-file fileb://source.zip \
  --handler lambda-function.py
```

I'm running the latest version of the localstack-pro docker image. Would you mind help taking a look? In the meantime, I'm gonna see if I can create the function without layers, then add them after the fact

**Comment by bentsku** [comment]
Hello @kylejPomelo, is this the exact same issue? 

Could you share the stack trace from LocalStack logs?

**Comment by kylejPomelo** [comment]
> Hi @whummer I was able to reproduce this issue when I was calling `aws lambda create-function` only when there were layers present -
> 
> this command failed -
> 
> ```
> aws lambda create-function --endpoint-url=http://localhost:4566  \
>   --function-name my-lambda-function \
>   --runtime python3.8 \
>   --region us-west-2 \
>   --role $ROLE_ARN \
>   --layers \"$LAYER_1_ARN\" \"$LAYER_2_ARN\" \"$LAYER_3_ARN\" \"$LAYER_4_ARN\" \
>   --zip-file fileb://source.zip \
>   --handler lambda-function.py
> ```
> 
> while this would succeed -
> 
> ```
> aws lambda create-function --endpoint-url=http://localhost:4566  \
>   --function-name my-lambda-function \
>   --runtime python3.8 \
>   --region us-west-2 \
>   --role $ROLE_ARN \
>   --zip-file fileb://source.zip \
>   --handler lambda-function.py
> ```
> 
> I'm running the latest version of the localstack-pro docker image. Would you mind help taking a look? In the meantime, I'm gonna see if I can create the function without layers, then add them after the fact
> 
> here are the exception logs:
> 
> ```
> 2023-09-04 10:05:47 2023-09-04T16:05:47.893 ERROR --- [   asgi_gw_1] l.aws.handlers.logging     : exception during call chain: 'NoneType' object has no attribute 'group'
> 2023-09-04 10:05:47 2023-09-04T16:05:47.895  INFO --- [   asgi_gw_1] localstack.request.aws     : AWS lambda.CreateFunction => 500 (InternalError)
> 2023-09-04 10:05:47 2023-09-04T16:05:47.930 ERROR --- [   asgi_gw_2] l.aws.handlers.logging     : exception during call chain: 'NoneType' object has no attribute 'group'
> 2023-09-04 10:05:47 2023-09-04T16:05:47.930  INFO --- [   asgi_gw_2] localstack.request.aws     : AWS lambda.CreateFunction => 500 (InternalError)
> 2023-09-04 10:05:48 2023-09-04T16:05:48.084 ERROR --- [   asgi_gw_7] l.aws.handlers.logging     : exception during call chain: 'NoneType' object has no attribute 'group'
> 2023-09-04 10:05:48 2023-09-04T16:05:48.084  INFO --- [   asgi_gw_7] localstack.request.aws     : AWS lambda.CreateFunction => 500 (InternalError)
> 2023-09-04 10:05:48 2023-09-04T16:05:48.884 ERROR --- [   asgi_gw_3] l.aws.handlers.logging     : exception during call chain: 'NoneType' object has no attribute 'group'
> 2023-09-04 10:05:48 2023-09-04T16:05:48.885  INFO --- [   asgi_gw_3] localstack.request.aws     : AWS lambda.CreateFunction => 500 (InternalError)
> 2023-09-04 10:05:51 2023-09-04T16:05:51.478 ERROR --- [   asgi_gw_6] l.aws.handlers.logging     : exception during call chain: 'NoneType' object has no attribute 'group'
> 2023-09-04 10:05:51 2023-09-04T16:05:51.478  INFO --- [   asgi_gw_6] localstack.request.aws     : AWS lambda.CreateFunction => 500 (InternalError)
> 2023-09-04 10:05:51 
> 2023-09-04 10:05:51 An error occurred (InternalError) when calling the CreateFunction operation (reached max retries: 4): exception while calling lambda.CreateFunction: 'NoneType' object has no attribute 'group'
> ```
> 
> thanks!

hi @bentsku I actually figured out the issue, it was a combination of two things. the layer arn variables didn't have the version appended, meaning 

LAYER_1_ARN=arn:aws:lambda:us-west-2:000000000000:layer:layer-1

when it should've been 

LAYER_1_ARN=arn:aws:lambda:us-west-2:000000000000:layer:layer-1:1

then when I removed the quotations surrounding those variables, it worked

**Comment by kylejPomelo** [comment]
> Hello @kylejPomelo, is this the exact same issue?
> 
> Could you share the stack trace from LocalStack logs?

hi @bentsku I actually figured out the issue, it was a combination of two things. the layer arn variables didn't have the version appended, meaning 

LAYER_1_ARN=arn:aws:lambda:us-west-2:000000000000:layer:layer-1

when it should've been 

LAYER_1_ARN=arn:aws:lambda:us-west-2:000000000000:layer:layer-1:1

then when I removed the quotations surrounding those variables, it worked

**Comment by bentsku** [comment]
Could try removing the quotes around your method? The original report is about calling an API Gateway route, I don't think we're in the same kind of issue here.

```bash
aws lambda create-function --endpoint-url=http://localhost:4566  \
  --function-name my-lambda-function \
  --runtime python3.8 \
  --region us-west-2 \
  --role $ROLE_ARN \
  --layers $LAYER_1_ARN $LAYER_2_ARN $LAYER_3_ARN $LAYER_4_ARN \
  --zip-file fileb://source.zip \
  --handler lambda-function.py
```

**Comment by bentsku** [comment]
Ah, awesome, glad you could find a solution!

**Comment by markrin** [comment]
Had same error on `update-function-configuration` because of using just layer name at `--layers` instead of full layer arn with version
