### ISSUE TITLE
question: Missing API keys in 14 days trial period

### ISSUE THREAD

**Issue by eddy147** [localstack/localstack#5992]
### Is there an existing issue for this?

- [X] I have searched the existing issues and read the documentation

### Question

Subscribed for a 14 day trial, (ulumaster@ulu.io) and I expected to have API keys so I can try out the IOT api's.
If I go to Account Settings > API Keys, the API keys are empty.

Maybe that is correct for a trial period?
How can I try out the IoT connection in a trial period?

**Comment by whummer** [comment]
Hi @eddy147 , thanks for reaching out. We've just sent out an invite to our Slack channel to your email, so we can support you there. Alternatively, please get in touch directly to info@localstack.cloud . Looking forward to having you on board. Thanks!
