### ISSUE TITLE
bug: A lambda function is configured and yet is not triggered

### ISSUE THREAD

**Issue by EinavBar18** [localstack/localstack#5997]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I Added a lambda function to cognito configuration to be triggered after "adminCreateUser" in order to send mail.
if "DesiredDeliveryMediums" is: [ 'EMAIL' ] and "MessageAction" is undefined, in "adminCreateUser" request, the lambda should be triggered.
That configuration is not shown on localstack's dashboard although when Im using cli to get configuration it is shown.
The lambda is not triggered. 

### Expected Behavior

The configured lambda should be triggered on "adminCreateUser" when  "DesiredDeliveryMediums" is: [ 'EMAIL' ] and "MessageAction" is undefined.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

   docker-compose.yml

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal s3 mb s3://mybucket

### Environment

```markdown
- OS: 
- LocalStack:
```

**Comment by yonatandbinahai** [comment]
@lukqw  A minimal setup of the user pool & user creation is as follows (the initialization of some used variables was omitted to keep the code minimal, as their value doesn't seem relevant for this issue).
Note: our user pool initialization is done in python and the cognito user management is done in our NodeJS server

Setup lambda & user pool (python):
```
lambda = lambda_client.create_function(
  FunctionName='some_function',
  Role=role['Arn'],
  Code={
     'ZipFile': file_data.read()
  },
  Handler='send-email-lambda.handler',
  Runtime='python3.8',
  PackageType='Zip'
)

policies = {
  'PasswordPolicy': {
    'MinimumLength': 8,
    'RequireUppercase': True,
    'RequireLowercase': True,
    'RequireNumbers': True,
    'TemporaryPasswordValidityDays': 365
  }
}

lambda_config = {
  'CustomEmailSender': {
    'LambdaVersion': 'V1_0',
    'LambdaArn': lambda['FunctionArn'],
  }
}

admin_create_user_config = {'AllowAdminCreateUserOnly': True}
cognito.create_user_pool(
            PoolName=user_pool_name,
            Policies=policies,
            LambdaConfig=lambda_config,
            AdminCreateUserConfig=admin_create_user_config,
            Schema=schema,
        )
```

Create user (nodeJS):
```
            await this.cognitoService.adminCreateUser({
              UserPoolId: containerId,
              Username: user.username,
              UserAttributes: [
                { Name: 'email', Value: user.username },
                { Name: 'email_verified', Value: 'true' },
              ],
              TemporaryPassword: 'Password1' ,
              MessageAction: undefined,
              DesiredDeliveryMediums: [ 'EMAIL' ],
            }).promise();
```

**Comment by lukqw** [comment]
Hi @yonatandbinahai and @EinavBar18, this issue has now been resolved and should be fixed in our `latest` docker image in the upcoming days.
