### ISSUE TITLE
feature request: New Checksum Support for S3 Object Integrity Checks

### ISSUE THREAD

**Issue by jmgottfried** [localstack/localstack#6008]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Recently, AWS added support for more checksum algorithms for S3 object integrity checks (only md5 was supported so far):
* CRC32
* CRC32C
* SHA-1
* SHA-256

Please add support for this new feature into the localstack S3 interface.

More Details:
* https://aws.amazon.com/blogs/aws/new-additional-checksum-algorithms-for-amazon-s3/
* https://docs.aws.amazon.com/AmazonS3/latest/userguide/checking-object-integrity.html#using-additional-checksums
* https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutObject.html#API_PutObject_RequestSyntax

**Comment by pinzon** [comment]
The feature has been implemented, make sure to pull the latest docker image. 
Thank you for reporting this issue @jmgottfried.
