### ISSUE TITLE
Could not able to create/search records in Localstack Elasticsearch from Sam local lambda

### ISSUE THREAD

**Issue by rakhesh-idexcel** [localstack/localstack#6028]
### Is there an existing issue for this?

- [X] I have searched the existing issues and read the documentation

### Question

Created Elasticsearch domain from the local stack and can able to create and query documents from Postman successfully. But when I tried to connect Elasticsearch endpoint from Sam through node-fetch, **Connection Refused ** error throws.

I tried Endpoint 
`http://host.docker.internal:4571/lotest/_all/_search`

It doesn't help, throws error as ** reason: socket hang up","type":"system","errno":"ECONNRESET","code":"ECONNRESET"**

Please help me to connect SAM and Localstack Elasticsearch through HTTP call

### Anything else?

Sharing my docker file

```
version: "3.9"

services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    network_mode: bridge
    environment:
      - node.name=elasticsearch
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data

  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    network_mode: bridge
    ports:
      - "4566:4566"
      - "4571:4571"
    depends_on:
      - elasticsearch
    environment:
      - ES_CUSTOM_BACKEND=http://elasticsearch:9200
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    links:
      - elasticsearch

volumes:
  data01:
    driver: local
```

**Comment by pinzon** [comment]
@rakhesh-idexcel when you're writing Lambda function and you want to refer to your Localstack instance, it is recommended to use `localhost.localstack.cloud`  as the host, so the request of your lambda container doesn't target itself. 

By the way If I remember correctly, now every request should go through the 4566 port even for external services. I tried your setup an made the request using port 4571 and it never worked for me.

Here's the [documentation](https://docs.localstack.cloud/aws/elasticsearch) on how the ElasticSearch service works now.
