### ISSUE TITLE
CloudFormation Delete bug: 

### ISSUE THREAD

**Issue by bwship** [localstack/localstack#6038]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When deleting a stack, it shows a status of DELETE_COMPLETE but it never actually removes the stack.

![delete-complete](https://user-images.githubusercontent.com/1326114/167662642-e330df97-d6d8-4145-9d8a-4ff80948746e.png)

### Expected Behavior

I would expect the stack to be removed after it has successfully been deleted.

### How are you starting LocalStack?

Custom (please describe below)

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    Using Commandeer (under the hood it is starting up a docker container.

#### Client commands

    Deleting any stack from LocalStack seems to cause this.  I am currently deleting it from Commandeer, which under the hood is using the CloudFormation AWS Javascript SDK.

### Environment

```markdown
- OS: Mac
- LocalStack: 0.14.2
```

**Comment by pinzon** [comment]
The PR to this issue has been merged. Please test the solution and if you still have issues let me know. 
Thanks for reporting it.
