### ISSUE TITLE
question: Is BatchPutItem supported in AppSync template resolvers?

### ISSUE THREAD

**Issue by ugurhicyilmam** [localstack/localstack#6046]
### Is there an existing issue for this?

- [X] I have searched the existing issues and read the documentation

### Question

Is `BatchPutItem` operation supported with AppSync?

I get the following error from AppSync:

`{
  "errors": [
    "Unsupported AppSync DynamoDB template operation \"BatchPutItem\"\n\nGraphQL request:2:3\n1 | mutation {\n2 |   putNotes(\n  |   ^\n3 |     pk: \"string\""
  ]
}`

**Comment by silv-io** [comment]
Hello @ugurhicyilmam, this feature should be available in the latest docker image. Can you pull the image again and check if it works for you now? Thanks 🙂
