### ISSUE TITLE
s3:ObjectCreated triggered when S3 object is tagged

### ISSUE THREAD

**Issue by GeoffreyBooth** [localstack/localstack#605]
I used s3.putBucketNotificationConfiguration so that a Lambda function is triggered for every file uploaded into an S3 bucket:

```coffee
s3.putBucketNotificationConfiguration
  Bucket: "inbox"
  NotificationConfiguration:
    LambdaFunctionConfigurations: [
      Events: ['s3:ObjectCreated:*']
      LambdaFunctionArn: "arn:aws:lambda:#{process.env.AWS_REGION}:#{lambdaId}:function:inboxHandler"
      Id: 'inboxHandler'
    ]
```

In that Lambda function, I call `s3.putObjectTagging` to add some tags to the S3 object. When I do so, however, the Lambda function gets triggered again, setting off an infinite loop.

`s3:ObjectCreated` shouldn’t be triggered by tags updating an S3 object. That doesn’t happen in real AWS S3.

**Comment by whummer** [comment]
Thanks for reporting @GeoffreyBooth - can you please try the latest version, this should be fixed in #608.

**Comment by GeoffreyBooth** [comment]
I can’t get that far now, due to #614.

**Comment by pacanukeha** [comment]
I think I'm suffering from this at the moment.

**Comment by whummer** [comment]
@pacanukeha Can you please provide a small self-contained example (code and/or AWS CLI commands) to reproduce this issue? Thanks

**Comment by duongpv7** [comment]
This issue fixed in latest version

**Comment by whummer** [comment]
@GeoffreyBooth @pacanukeha  Appears to be fixed in `latest` - please report here if the problem persists. Thanks
