### ISSUE TITLE
LocalStack DYNAMODB_WRITE_ERROR_PROBABILITY

### ISSUE THREAD

**Issue by saurabhpatil30** [localstack/localstack#6056]
### Is there an existing issue for this?

- [X] I have searched the existing issues and read the documentation

### Question

After configuring it  withEnv("DYNAMODB_WRITE_ERROR_PROBABILITY", "1.0") — it is expected to throw dynamo throuput exception , but throwing 500 error - `(Service: DynamoDb, Status Code: 500, Request ID: null, Extended Request ID: null)","operationType":"PutItem","kinesisRecordMetaData":{"recordInsertionDate":"01-01-2021"}}, Response - PutObjectResponse(ETag="5435b0664a1337227d380fbd83ebcc89")

**Comment by whummer** [comment]
Thanks for reporting @saurabhpatil30 . This should be fixed via #6063 - can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists.. Thanks!
