### ISSUE TITLE
bug: Localstack behaves differently to the real AWS when using API Gateway V2 and a custom authoriser which denies access for a request [pro]

### ISSUE THREAD

**Issue by smbkr** [localstack/localstack#6057]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Localstack responds with:

403 Forbidden
```json
{"Type": "User", "message": "Authorization failed: Unexpected Effect=Deny (expected: \"Allow\") in Lambda authorizer response", "__type": "AuthorizationError"}
```

### Expected Behavior

AWS responds with:

401 Unauthorized
```json
{"message": "Unauthorized"}
```

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker compose up

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

N/A

- Create an API Gateway V2 with a custom authoriser configured to authenticate incoming requests
- Have the custom authoriser return a policy which denies the request:
  ```json
    {
      "Version":"2012-10-17",
      "Statement":[
        {
          "Action":"execute-api:Invoke",
          "Effect":"Deny",
          "Resource":"arn:aws:foo:bar:arn:for:lambda:handler"
        }
      ]
    }
  ```

### Environment

```markdown
- OS: Mac OS 11.6.1
- LocalStack: latest
```

### Anything else?

This makes it impossible to write valid/accurate tests because Localstack behaves differently to the real AWS.

**Comment by smbkr** [comment]
It looks like as of 0.14.3 that this works as expected. When my requests are unauthorised, I now receive a response where the status code is `401` and the body is `{"message": "Unauthorised"}` as expected.

**Comment by smbkr** [comment]
I may have spoken too soon - this morning our tests are failing in the same way again, we are getting `403` instead of `401` from Localstack. It looks like `0.14.3.1` was released last night, I guess this must have included a change that's reverted this behaviour.

It doesn't look like there is a tag for `0.14.3.0` on Docker hub, only `0.14.3` (which I guess is the same as `0.14.3.1`) and `0.14.3.1`

**Comment by calvernaz** [comment]
Hi @smbkr, sorry for the regression and we understand that you're expecting a 401. AWS [documentation](https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-use-lambda-authorizer.html#api-gateway-lambda-authorizer-token-lambda-function-create) explicitly states that a Deny policy will return a 403, and we validated this against AWS. So with that in mind and with the documentation example, is it possible that for you case you would just exit the lambda with an `unauthorised` message?

**Comment by smbkr** [comment]
Thanks for the reply @calvernaz, I believe that the REST integration for API Gateway V1 responds with 403 when a 'Deny' policy is returned by the authoriser function, however the HTTP integration for API Gateway V2 responds with 401 in the same circumstance in my testing:

```
❯ curl -H 'x-api-key: badapikey' https://my-api-v2.dev/foobar -i
HTTP/2 401
date: Thu, 26 May 2022 08:03:08 GMT
content-type: application/json
content-length: 26
apigw-requestid: SuUZOgrMDoEEPFA=

{"message":"Unauthorized"}%
```

**Comment by calvernaz** [comment]
Thanks @smbkr, I'll look into it.

**Comment by smbkr** [comment]
Thanks @calvernaz

We did a little more testing of our implementation in the real AWS yesterday. Our authoriser function expects an 'x-api-key' header with a key we look up in our DB, and compare the key's permissions with the endpoint being accessed and return an 'Allow' or 'Deny' policy. We have a few scenarios we're testing:

- when the 'x-api-key' header is missing
- when the 'x-api-key' header is empty
- when the 'x-api-key' header is included, but the given key is not found in the db
- when the key is found, but the permitted scopes for the key do not match the incoming request
- when the key is found and the scopes match

I believe that in the first three scenarios, our handler throws an exception and we get a 401 from AWS

When the key is found but the scope is wrong, we return a 'Deny' policy, and we get a 403 from AWS

When the key is found and the scope matches, we return an 'Allow' policy and the subsequent API Gateway integration is invoked

We're going to verify that our test suite is expecting the correct type of response for each scenario to make sure the error isn't on our side, and if we still think there's a mismatch between AWS and Localstack, we'll update here, so perhaps hold off for now until you hear further from myself (or @n-erwen who is also looking at this on our side)

Thanks!

**Comment by n-erwen** [comment]
We found the issue, it was a bug on our side. Everything is working as expected, thank you very much for the help!
