### ISSUE TITLE
Localstack crashing while doing S3 copy

### ISSUE THREAD

**Issue by kvkk** [localstack/localstack#6064]
### Is there an existing issue for this?

- [X] I have searched the existing issues and read the documentation

### Question

I am new to localstack and started experimenting with it on my laptop. 

**What am I trying to achieve:**
Set up some SQS queues and trigger a set of lambda functions locally. 

**What did I do:**
I installed and started localstack using `localstack start`. 
As my lambda functions are > 50MB, to deploy my lambda functions, I started copying jars to localstack S3 using `awslocal s3 cp ../../components/router/build/libs/router.jar s3://lambda-code/`. 
I tried copying my jars multiple times to deploy lambda function without any errors.  After a couple of tries, figured out how to do it and deployed couple of lambda functions (I think).

**What is the problem**
Now when i try to copy remaining jars, I am seeing an error in copy operation
`Connection was closed before we received a valid response from endpoint URL: "http://localhost:4566/lambda-code/router.jar?uploadId=XQlcAvtQQS1a3Kxuk9NnIiVfGYpJXRFTNy6U0E0w56S5iglLwts6qXaOw`

In the logs, I see localstack container getting killed and restarted. I also observed my S3 bucket is gone.
I restarted localstack, created new s3 bucket and tried to upload a jar resulted in same error as above immediately unlike before where I was able to upload some of the jars. 

**Questions:**
1. Is there a total size limit on jars that can be uploaded (My jars are typically 40-70MB but i uploaded them multiple times so i might have hit a limit)
2. Are the jars which i uploaded persisted somewhere counting against that limit and causing the error right away after restart. In addition, I created couple of dynamodb tables which are also persisted as i can see tables after each restart
3. If they are persisted, how can i reset this environment to remove old jars and such

**Workaround**
I restarted my laptop restarting my kube cluster and all VMs. That solved my problem but would like to know if there is something wrong with my setup

Environment:
I am running localstack on Mac M1 with Rancher as Kubernetes cluster

Any help is appreciated.

Thanks,
Venkat

**Comment by dfangl** [comment]
Hi there!
Would it be possible for you to provide the logs of LocalStack crashing when it happens next time?
Also, what exact version of LocalStack (it is printed on startup) do you run?
For example, with #5856 we managed to fix an issue with LocalStack segfaulting on some connections on MacOS, maybe you are running into the same issue with an outdated image.

**Comment by kvkk** [comment]
Turned out I am not bringing docker containers down causing all new uploads to consume disk space.
