### ISSUE TITLE
Localstack - Unable to get cloudwatch log streams

### ISSUE THREAD

**Issue by tweezy** [localstack/localstack#6077]
Hi everyone, I'm using localstack (0.14.2.4) with the Terraform provider integration. So far i've setup a simple API gateway which calls to a lambda function. This lambda function is running on the `provided.al2` runtime, where the lambda is written in Rust. This integration works perfectly, and I get my desired api response.

I've also added some aws_cloudwatch_log_group integration. When I use the following command; `awslocal logs describe-log-groups` I am returned this json response:
```
{
    "logGroupName": "/aws/lambda/dev-join-group",
    "creationTime": 1652799250524,
    "retentionInDays": 14,
    "metricFilterCount": 0,
    "arn": "arn:aws:logs:us-east-1:000000000000:log-group:/aws/lambda/dev-join-group",
    "storedBytes": 6262
}
```

I would then presume I have a log stream due to the `storedBytes` having a value, alluding to the fact that data exists somewhere in a stream. My next command is to then describe some log streams under that group name; `awslocal logs describe-log-streams --log-group-name="/aws/lambda/dev-join-group"`

However, I am returned the following message; `An error occurred (ResourceNotFoundException) when calling the DescribeLogStreams operation: The specified log group does not exist`. This does not make sense to me, as we can see above this log group does infact exist.

At this point I've tried many of the same commands, either using `aws` where I set the endpoint url to; `--endpoint-url=http://localhost:4566`, I've also specifically tried setting the region to; `us-east-1`, I still have the problem.

Any ideas here? Thanks

**Comment by tweezy** [comment]
I've made a little bit of progress. If I exec into my running localstack container (localstack_main) and do `awslocal logs describe-log-streams --log-group-name="/aws/lambda/dev-join-group"` I do get some log streams back. It appears that I am unable to describe log streams that are kept in the container.

**Comment by steffyP** [comment]
Hi @tweezy,

could you please elaborate a bit more on your setup (e.g. how do you start LocalStack), and give a minimal example for the entire setup of this integration, where you experience the described problem with the log stream?
