### ISSUE TITLE
bug: Lambda code unable to connect to port on host machine (Localstack in Docker for Mac)

### ISSUE THREAD

**Issue by eob** [localstack/localstack#6085]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have:
* a service running on my host machine at port `8080`. 
* Localstack running from within a docker-compose container

When a Lambda function attempts to connect to port `host.docker.internal:8080`, it fails with the message:

```
HTTPConnectionPool(host=\'host.docker.internal\', port=8080): Max retries exceeded with url: /api/v1/space/get (Caused by NewConnectionError(\'<urllib3.connection.HTTPConnection object at 0x400fcda280>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution\'))
```

When a Lambda function attempts to connect to `$LOCALSTACK_HOSTNAME:8080`, it hangs indefinately.

### Expected Behavior

I expect a process running within Docker to be able to connect to a port on the host machine.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker-compose up localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    We have python scripts brokering this, but it's essentially:
    - Deploy a lambda function.
    - Invoke the lambda function
    
    The code of the lambda function uses the `requests` library in Python to contact the host machine on port 8080

#### Localstack Config:

From docker-compose.yml:

```
  localstack:
    image: localstack/localstack
    environment:
      - SERVICES=s3,lambda,ecs,servicediscovery,ssm,events
      - HOSTNAME=localstack
      - IMAGE_NAME=localstack/localstack
      - DEFAULT_REGION=us-west-2
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - DEBUG=1
      - LOCALSTACK_API_KEY=XXXXX
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOSTNAME_EXTERNAL=localstack
#      - LAMBDA_EXECUTOR=local
    ports:
      - "4566:4566"
    volumes:
      - ./.localstack:/docker-entrypoint-initaws.d
      - "/var/run/docker.sock:/var/run/docker.sock"
```

### Environment

```markdown
- OS: MacOS 12.3.1
- LocalStack: localstack/localstack
- Docker Versions:
  - Engine: 20.10.14
  - Compose: v2.5.0
  - Desktop: 4.8.1
  - Kubernetes: v1.24.0
```

**Comment by dfangl** [comment]
Hi there! Just to test: can you set `DNS_ADDRESS=0` as environment variable and check if that fixes your issue? Thanks!
If not, please share the complete logs of a run with failed tests. If there is information in there which should not be public, please reach out in the Slack community (link shown in the message above).
