### ISSUE TITLE
bug: illegal file name in S3 bucket is crashing listing

### ISSUE THREAD

**Issue by sohah** [localstack/localstack#6098]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

creating a buggy file name on s3 can crash the listing of the bucket content, unlike the aws behavior that does not crash. 

### Expected Behavior

the actual aws behavior is that it truncates the file name, and allows the retrieval of the file:

`.txt-05-19 12:41:08         14 6T79`

### How are you starting LocalStack?

With a docker-compose file

### start localstack using docer
`docker-compose up`

### replicate the bug

You can replicate this bug by following these steps:
   1. `mkdir bug1`
   2. `cd bug1`
   3. `vim 6T7\x159\x12\r\x08.txt`
   4.  write anything then save and close.
   5. make a new bucket for testing:
        `awslocal s3api create-bucket --bucket buggy-bucket2 --region us-east-1`
   7. copy the file created to the new bucket:
         ` awslocal s3 cp 6T7\cu9\cr\r\b.txt s3://buggy-bucket2/ `
   9. list bucket contents:
        ` awslocal s3 ls s3://buggy-bucket2`

what you get is as a reply is

`Unable to parse response (not well-formed (invalid token): line 1, column 265), invalid XML received. Further retries may succeed:
b'<?xml version="1.0" encoding="UTF-8"?><ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Name>buggy-bucket</Name><Prefix></Prefix><MaxKeys>1000</MaxKeys><KeyCount>1</KeyCount><Delimiter>/</Delimiter><IsTruncated>false</IsTruncated><Contents><Key>6T7\x159\x12\r\x08.txt</Key><LastModified>2022-05-19T17:27:05.000Z</LastModified><ETag>&#34;e1a7b816b92fe20d6013be6ad1946e27&#34;</ETag><Size>14</Size><StorageClass>STANDARD</StorageClass></Contents></ListBucketResult>'`docker

### Environment

```markdown
- OS: mac os Montery 12.2.0, also on Ubuntu 16.0LS
- LocalStack:
```

### Anything else?

here is my docker-compose file:

`version: '3.0'
services:
  localstack:
    container_name: localstack
    image: localstack/localstack
    network_mode: bridge
    environment:
      - DEBUG=1
      - DEFAULT_REGION=us-east-1
      - LAMBDA_EXECUTOR=docker
      - LAMBDA_REMOTE_DOCKER=true
      - LAMBDA_REMOVE_CONTAINERS=true
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LOCALSTACK_API_KEY=1hAzxwAB9D
    volumes:
      - ./localstack/bootstrap:/opt/bootstrap/
      - ./data:/tmp/localstack
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - '4566:4566'
      - '443:443'`

**Comment by whummer** [comment]
Thanks for reporting @sohah , we have now pushed a fix which should (hopefully) get this issue resolved - can you please pull the `latest` Docker image and give it another try? Please keep us posted on how it goes.. Thanks!

**Comment by pinzon** [comment]
@whummer I'm closing this issue based on @sohah's thumbs up reaction. 
![image](https://user-images.githubusercontent.com/18080804/177221107-e866e082-1c60-452d-b883-b94659c481ab.png)
