### ISSUE TITLE
bug: LocalStack test container DynamoDB query occasionally throwing Crc32MistmatchException

### ISSUE THREAD

**Issue by LouieMiddleHawkeye** [localstack/localstack#6105]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have a service that needs to query DynamoDB, so we have a container test using local stack creating local DynamoDb tables. For the most part the test passes as expected, but occasionally it fails with a `Crc32MismatchException: Expected 583912891 as the Crc32 checksum but the actual calculated checksum was 0` when making the dynamo query. I deployed the service to AWS and have ran it multiple times and haven't seen the error on AWS. It's making me think that it's an issue with the LocalStack container.

### Expected Behavior

The dynamo query returns the expected result every time.

### How are you starting LocalStack?

Custom (please describe below)

### Steps To Reproduce

I'm using a java junit test container using LocalStack v0.14.2 and the default synchronous `DynamoDbClient` given in the java aws sdk. 

The code looks a little something like:

``` 
public List<Results> getBetweenTimes(Instant startTime, Instant endTime) {
        Validation.validateQueryTimes(startTime, endTime);

        List<AllResults> results = new ArrayList<>();
        results.addAll(getBetweenTimes(startTime, endTime, CONTENT_TYPE));
        results.addAll(getBetweenTimes(startTime, endTime, CONTENT_TYPE));
        results.addAll(getBetweenTimes(startTime, endTime, CONTENT_TYPE));
     
        return results;
}

List<T> getBetweenTimes(Instant startTime, Instant endTime, String contentType) {
        Validation.validateQueryTimes(startTime, endTime);
        return getRowsBetweenTimes(startTime, endTime, contentType)
            .stream()
            .map(row -> processRow(row, venueId))
            .map(r -> getTracking(r.asByteArray()))
            .collect(Collectors.toList());
}

private List<Map<String, AttributeValue>> getRowsBetweenTimes(Instant startTime, Instant endTime, String contentType) {
        QueryResponse response = dynamoClient.query(
            QueryRequest.builder()
                .keyConditionExpression(CONTENT_TYPE_COLUMN + " = :content_type and " + TIME_COLUMN + " between :start_millis_utc and :end_millis_utc")
                .expressionAttributeValues(Map.of(
                        ":content_type", AttributeValue.builder().s(contentType).build(),
                        ":start_millis_utc", AttributeValue.builder().n(String.valueOf(startTime.toEpochMilli())).build(),
                        ":end_millis_utc", AttributeValue.builder().n(String.valueOf(endTime.toEpochMilli())).build()
                    )
                )
                .tableName(dynamoTable)
                .build()
        );

        if (response.sdkHttpResponse().isSuccessful()) {
            return response.items();
        } else {
            log.error("Failed to query Dynamo for content of type {}, between times {} - {}", contentType, startTime, endTime);
            return List.of();
        }
    }

```

I'm calling `getBetweenTimes` and every now and again one of the calls to `getBetweenTimes` in the `results.addAll` I get the exception.

### Environment

```markdown
- OS: Windows 10 Pro v21H1
- LocalStack: v0.14.2
```

**Comment by LouieMiddleHawkeye** [comment]
@whummer Hi, just wondering what the timeline usually is for GitHub issues?

**Comment by ackdav** [comment]
Thank you for the report. I'm going to close this issue because: 
- the LS version used is quite outdated (v0.14 vs v2.1)
- it lacks a clear way to reproduce it
- it's been stale for over a year

if the issue still persists with the current version - please open a new ticket, thx!
