### ISSUE TITLE
feature request: Support mapping of runtime to container name

### ISSUE THREAD

**Issue by Tohaker** [localstack/localstack#6111]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

The use case I have in mind is to run Node 16.x Lambdas - the default container registry is `lambci/lambda` which is effectively abandoned. [Not even Node 14.x has been published](https://github.com/lambci/docker-lambda/pull/330). However, switching the registry over to [`amazon/aws-lambda-nodejs`](https://hub.docker.com/r/amazon/aws-lambda-nodejs) still fails to pull the container, since localstack is looking for the tag `nodejs16.x`. I'd like to be able to specify that if the runtime is `nodejs16.x` it just looks for tag `16`.

**Comment by Tohaker** [comment]
For what it's worth, I managed to work around the issue by running the following command with this dockerfile;

```sh
docker build -t lambci/lambda:nodejs16.x -f Dockerfile.nodejs16x .
```

Dockerfile.nodejs16x
```
FROM amazon/aws-lambda-nodejs:16 as base

FROM lambci/lambda:nodejs12.x

COPY --from=base /var/lang/bin/node /var/lang/bin/node
```

**Comment by Brian-Kavanagh** [comment]
Building on @Tohaker 's workaround, the the following worked for *NodeJS 18*;

    docker build -t lambci/lambda:nodejs18.x -f Dockerfile.nodejs18x .

Dockerfile.nodejs18x

    FROM amazon/aws-lambda-nodejs:18 as base
    FROM lambci/lambda:nodejs12.x
    COPY --from=base /var/lang/bin/node /var/lang/bin/node
    COPY --from=base /var/lang/lib      /var/lang/lib

**Comment by dfangl** [comment]
Hi! You can also use `PROVIDER_OVERRIDE_LAMBDA=asf` if you need node18 support, as our new provider comes with many improvements, including nodejs 18 support. Building a lambci image from the amazon/aws-lambda-nodejs image might not work for all executor types, its better to use the new provider altogether (it is also based on those images but properly instruments them).
