### ISSUE TITLE
Uploading to S3 presigned URLs doesn't check Content-MD5 or other presigned constraints

### ISSUE THREAD

**Issue by chiastic-security** [localstack/localstack#612]
If I generate a presigned URL for uploading into a bucket, and I specify a content type or a content MD5 to be encapsulated into the URL, these are not then enforced when I upload to that URL. I can set whatever `Content-MD5` header I like in the HTTP upload, and it's accepted.

Furthermore, the `Content-MD5` header doesn't get checked even against the content being uploaded. I can set the header to `blah` and I don't get any errors.

Is this expected?

**Comment by whummer** [comment]
Thanks for reporting @chiastic-security . Any chance you can provide a short code snippet to reproduce this issue? Ideally either a Python unit test, or a sequence of `aws` (or `awslocal`) commands that we can run in a terminal. Thanks

**Comment by MerelCHT** [comment]
@whummer The script attached reproduces the bug by creating a bucket and uploading a file to it with a randomly specified `Content-MD5` header. When running it against normal AWS the following exception is thrown: `An error occurred (InvalidDigest) when calling the PutObject operation: The Content-MD5 you specified was invalid`. However when running it against localstack it successfully uploads to file to the bucket. 

[upload-my-file.sh.zip](https://github.com/localstack/localstack/files/1874948/upload-my-file.sh.zip)

**Comment by chiastic-security** [comment]
@whummer is there any update on this? Anything more that you need from our end?

**Comment by whummer** [comment]
@chiastic-security @MerelCHT This should be fixed in #772 - can you please give it a try with the latest version on `master` (or the `latest` Docker image).

**Comment by whummer** [comment]
Seems to be fixed, closing - please reopen if the problem persists.
