### ISSUE TITLE
question: Using self-hosted Kafka with AWS Lambda

### ISSUE THREAD

**Issue by AlexeyRaga** [localstack/localstack#6121]
### Is there an existing issue for this?

- [X] I have searched the existing issues and read the documentation

### Question

I am trying to configure self-hosted Kafka to be a source for a lambda and am getting this error:

```
2022-05-23T02:51:52.150:ERROR:lambda_api: Exception on /2015-03-31/event-source-mappings/ [POST]
Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 1678, in create_event_source_mapping
    mapping = add_event_source(data)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 254, in add_event_source
    mapping = build_mapping_obj(data)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 233, in build_mapping_obj
    batch_size = check_batch_size_range(source_arn, batch_size)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 195, in check_batch_size_range
    source = source_arn.split(":")[2].lower()
IndexError: list index out of range
```

Here is my configuration:

```terraform
resource "aws_lambda_event_source_mapping" "consumer" {
  enabled                       = true
  function_arn                  = (known after apply)
  function_name                 = (known after apply)
  id                            = (known after apply)
  last_modified                 = (known after apply)
  last_processing_result        = (known after apply)
  maximum_record_age_in_seconds = (known after apply)
  maximum_retry_attempts        = (known after apply)
  parallelization_factor        = (known after apply)
  starting_position             = "TRIM_HORIZON"
  state                         = (known after apply)
  state_transition_reason       = (known after apply)
  topics                        = [ "domain-events" ]
  uuid                          = (known after apply)

  self_managed_event_source {
      endpoints = {
          "KAFKA_BOOTSTRAP_SERVERS" = "kafka:29092"
        }
    }

  source_access_configuration {
      type = "VPC_SECURITY_GROUP"
      uri  = "security_group:subnet-0475b7b5"
    }
  source_access_configuration {
      type = "VPC_SECURITY_GROUP"
      uri  = "security_group:subnet-0fdedbdc"
    }
  source_access_configuration {
      type = "VPC_SECURITY_GROUP"
      uri  = "security_group:subnet-d13980ae"
    }
  source_access_configuration {
      type = "VPC_SUBNET"
      uri  = "subnet:subnet-0475b7b5"
    }
  source_access_configuration {
      type = "VPC_SUBNET"
      uri  = "subnet:subnet-0fdedbdc"
    }
  source_access_configuration {
      type = "VPC_SUBNET"
      uri  = "subnet:subnet-d13980ae"
    }
}
```

I do not provide any auth here because none is required by the Kafka cluster, and `VPC_SECURITY_GROUP` and `VPC_SUBNET` URIs are, by documentation, not in a form of ARN.

Yet Localstack fails accepting this configuration because it tries to do access the first element of the collection
```
source_arn = data["SourceAccessConfigurations"][0]["URI"]
...
batch_size = check_batch_size_range(source_arn, batch_size)
```

and then to parse it just to get a string out of it:
```
source = source_arn.split(":")[2].lower()
source = "kafka" if "secretsmanager" in source else source
```

Which looks like a hack/bug. Checking "Self managed event source" for having `KAFKA_BOOTSTRAP_SERVERS` endpoint would perhaps be a cleaner way of determining whether Kafka is used or not?

### Anything else?

Please advice how to proceed

**Comment by AlexeyRaga** [comment]
It looks like that if I add this one artificially:
```
  source_access_configuration {
    type = "SASL_SCRAM_512_AUTH"
    uri = aws_secretsmanager_secret.lambda_trigger.arn
  }
```

and I remove all the other `source_access_configuration` (because otherwise `[0]` indexing can get the wrong one) I can finally deploy the mapping.

BUT it doesn't seem to be triggering at all: no logs in the lambda log group, no logs in the `localstack` container...

Topic definitely does exist and has data in it, but Kafka doesn't see any consumer group IDs that can be related to the lambda and the lambda ins't getting invoked....

**Comment by seanttaylor** [comment]
Just wondering if y'all ever figured this one out...? I have exactly the issue you describe @AlexeyRaga: a correctly configured Kafka cluster and topic with the source access configuration shown above ☝️. Topic definitely has data in it but there is no evidence in the lambda logs that my lambda is being triggered at all by the Kafka activity.

**Comment by isaac-j-miller** [comment]
Is there any update on this? Doesn't seem to be working for me either

**Comment by bencebalint-ovo** [comment]
> edit: it is apparently a pro feature

@isaac-j-miller how did you arrive to this conclusion? 

The [user guide](https://docs.localstack.cloud/user-guide/integrations/kafka/) doesn't say it's a "pro feature".

The [docs for MSK](https://docs.localstack.cloud/user-guide/aws/managed-streaming-for-kafka/) are tagged "pro" but that's different I suppose?

**Comment by thrau** [comment]
Hello! The lambda integration with self-managed kafka clusters is part of our MSK implementation and also a pro feature.  We've clarified the part in the docs!
