### ISSUE TITLE
feature request: TagResourceCommand not supported

### ISSUE THREAD

**Issue by aslotte** [localstack/localstack#6125]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

When trying to send the `TagResourceCommand` using the `ECSlient` from the AWS SDK in Node.js, an error is thrown saying that this API is not implemented.

```
await ecs.send(new TagResourceCommand({
      resourceArn: ecsTask.taskDefinitionArn,
      tags: [{ key: 'latestUsage', value: new Date().toISOString() }],
    }));
```

**Comment by whummer** [comment]
Hi @aslotte , thanks for reporting - this should be (hopefully) resolved in the meantime. Can you please pull the `latest` Docker image and give it another try? Please keep us posted on how it goes.. Thanks!

**Comment by whummer** [comment]
Hi @aslotte , quick follow-up. Closing this issue as resolved - please do let us know if the problem persists.. Thanks for your help!
