### ISSUE TITLE
Error when creating StepFunction after upgrading to `0.14.3` (from `0.14.2`)

### ISSUE THREAD

**Issue by xtaixe** [localstack/localstack#6126]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm using LocalStack with Testcontainers on Java. After upgrading to `0.14.3` (from `0.14.2`) the tests setup methods that create a step function fail with

```
software.amazon.awssdk.services.sfn.model.SfnException: null (Service: Sfn, Status Code: 500, Request ID: null)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleErrorResponse(CombinedResponseHandler.java:125)
```

### Expected Behavior

The StepFunction is created.

### How are you starting LocalStack?

Custom (please describe below)

### Steps To Reproduce

Small reproducer. This works with `0.14.2`.

```java
import org.testcontainers.containers.localstack.LocalStackContainer;
import org.testcontainers.utility.DockerImageName;
import software.amazon.awssdk.auth.credentials.AwsBasicCredentials;
import software.amazon.awssdk.auth.credentials.StaticCredentialsProvider;
import software.amazon.awssdk.regions.Region;
import software.amazon.awssdk.services.sfn.SfnClient;
import software.amazon.awssdk.services.sfn.model.CreateStateMachineRequest;

import static java.lang.String.format;
import static org.testcontainers.containers.localstack.LocalStackContainer.Service.STEPFUNCTIONS;

public class Test {

    private static final DockerImageName DOCKER_IMAGE = DockerImageName.parse("localstack/localstack:0.14.3");

    public static void main(String[] args) {
        final LocalStackContainer localstack = new LocalStackContainer(DOCKER_IMAGE)
                .withServices(STEPFUNCTIONS);

        localstack.start();

        final var region = localstack.getRegion();
        final var stateMachineDefinition = loadDefinition()
                .replace("{{lambdaReverse}}", format("arn:aws:lambda:%s:000000000000:function:reverse-string", region));

        var result = sfClient(localstack)
                .createStateMachine(CreateStateMachineRequest.builder()
                        .name("test")
                        .definition(stateMachineDefinition)
                        .build());

        System.out.println(result.stateMachineArn());
    }

    private static SfnClient sfClient(LocalStackContainer localstack) {
        return SfnClient.builder()
                .endpointOverride(localstack.getEndpointOverride(STEPFUNCTIONS))
                .region(Region.of(localstack.getRegion()))
                .credentialsProvider(credentials(localstack))
                .build();
    }

    private static StaticCredentialsProvider credentials(LocalStackContainer localstack) {
        return StaticCredentialsProvider.create(
                AwsBasicCredentials.create(localstack.getAccessKey(), localstack.getSecretKey()));
    }

    private static String loadDefinition() {
        return """
                {
                  "Comment": "A simple AWS Step Functions state machine that calls the revere lambda.",
                  "StartAt": "Add data",
                  "States": {
                    "Add data": {
                      "Comment": "See https://docs.aws.amazon.com/step-functions/latest/dg/amazon-states-language-pass-state.html",
                      "Type": "Pass",
                      "Result": "Processed",
                      "ResultPath": "$.statemachine",
                      "Next": "Lambda Reverse"
                    },
                    "Lambda Reverse":  {
                      "Type": "Task",
                      "Resource": "{{lambdaReverse}}",
                      "InputPath": "$.value",
                      "ResultPath": "$.reversed",
                      "End": true
                    }
                  }
                }
                """;
    }

}
```

### Environment

```markdown
- OS: Mac
- LocalStack: `0.14.3`
```

**Comment by dominikschubert** [comment]
Not sure how this works with testcontainers but please check the logs of the localstack container that it starts. They might give us more insights as to why it returns a 500 status now.

**Comment by xtaixe** [comment]
I think I figured it out. It seems I wasn't getting all the logs. Now I see: `Invalid type for parameter roleArn, value: None, type: <class 'NoneType'>, valid types: <class 'str'>`, so it seems `roleArn` is mandatory now. After setting a dummy role arn the setup succeeds, but now I'm getting test failures...

I'm seeing a lot of `2022-05-23T17:10:15.039:ERROR:localstack.services.awslambda.event_source_listeners.stream_event_source_listener: An error occurred (ResourceNotFoundException) when calling the DescribeStream operation: Stream arn:aws:dynamodb:us-east-1:000000000000:table/ohPNe8D was not found.`, but I'm not sure that is related, since it seems to start before my tests actually begin to do anything.

**Comment by xtaixe** [comment]
To avoid confusions, the test failures are not related to step functions. One is related to dead letter queues and anoter one to lambdas.

**Comment by xtaixe** [comment]
Feel free to close the issue, I've managed to figure out all the necessary changes (a different one for each failing test, lucky me!). For the record:

- Setting `roleArn` when creating a step function is now required.
- `maxReceiveCount` must be an int (previously a string was accepted).
- Queues urls being returned as `127.0.0.1` instead of `localhost` (we replace this for queues in lambdas).
- Had to add DynamoDB stream definition and use the stream ARN for a lambda event source (previously just the table ARN was working). I wonder if this will be a problem in another place I need to upgrade.
- Had to remove base64 encoding for kinesis (which it seems before was required and automatically decoded). This was was truly puzzling and hard to figure out.

LocalStack is a great asset and I understand that some of the above are issues on our side and some are odd due to how we use LocalStack in this case, but I must say that we are usually having a really hard time upgrading LocalStack, even for really close versions like in this case.
