### ISSUE TITLE
question: Health Check returning 404

### ISSUE THREAD

**Issue by marcusvoltolim** [localstack/localstack#6128]
### Is there an existing issue for this?

- [X] I have searched the existing issues and read the documentation

### Question

It makes sense for the url http://localhost:4566 to return Http NotFound(404) and responseText: {"status": "running"}.

It would make more sense to return Http OK (200)...

![image](https://user-images.githubusercontent.com/9442331/169861476-ef1e1bf1-403d-4174-9d83-0b73894626eb.png)

**Comment by thrau** [comment]
hi @marcusvoltolim , thanks for reporting. that's indeed a bit unintuitive behavior. in general i would recommend not depending on the root path `/`, but instead use `/_localstack/health` as the health endpoint. that will return OK 200 correctly!
we may change the behavior of `/` fairly soon.
