### ISSUE TITLE
DYNAMODB_SHARE_DB environment variable not honored by LocalStackContainer java client 

### ISSUE THREAD

**Issue by giriprashant7891** [localstack/localstack#6139]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Even if I set the `DYNAMODB_SHARE_DB` parameter in the LocalStackContainer java client, it is still not honoring it.
```
public static final LocalStackContainer LOCALSTACK_CONTAINER =
            new LocalStackContainer(localstackImage)
                    .withServices(Service.DYNAMODB)
                    .withEnv("DEBUG", "1")
                    .withEnv("DYNAMODB_SHARE_DB", "1")
                    .withImagePullPolicy(PullPolicy.alwaysPull());
```

The logged output still looks like below:
```
org.testcontainers.containers.output.WaitingConsumer - STDOUT: 
org.testcontainers.containers.output.WaitingConsumer - STDOUT: CorsParams:	*
org.testcontainers.containers.output.WaitingConsumer - STDOUT: shouldDelayTransientStatuses:	false
org.testcontainers.containers.output.WaitingConsumer - STDOUT: SharedDb:	false
org.testcontainers.containers.output.WaitingConsumer - STDOUT: DbPath:	null
org.testcontainers.containers.output.WaitingConsumer - STDOUT: InMemory:	true
org.testcontainers.containers.output.WaitingConsumer - STDOUT: Port:	43503
org.testcontainers.containers.output.WaitingConsumer - STDOUT: Initializing DynamoDB Local with the following configuration:
org.testcontainers.containers.output.WaitingConsumer - STDOUT: Listening at http://:::42875
```

### Expected Behavior

I was expecting that the DynamoDB container that comes up should have a shared DB.

### How are you starting LocalStack?

Custom (please describe below)

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

I'm using the java client. 

### Environment

```markdown
- OS: 
  MAC OS Monterey: 12.2.1
- LocalStack: 
  1.17.2
```

**Comment by thrau** [comment]
Hi @giriprashant7891, thanks for reporting. I can't make out which localstack version you are using. neither 12.2.1 nor 1.17.2 are valid localstack version.
The latest version definitely passes through `DYNAMODB_SHARE_DB` correctly and i've also tested it with `DYNAMODB_SHARE_DB=1 DEBUG=1 localstack start` and can see it being initialized correctly:

```
2022-05-24T23:24:27.035:DEBUG:localstack.utils.run: Executing command: ['java', '-Xmx256m', '-javaagent:/opt/code/localstack/localstack/infra/dynamodb/ddb-local-loader-0.1.jar', '-Djava.library.path=/opt/code/localstack/localstack/infra/dynamodb/DynamoDBLocal_lib', '-jar', '/opt/code/localstack/localstack/infra/dynamodb/DynamoDBLocal.jar', '-port', '41345', '-inMemory', '-sharedDb']
2022-05-24T23:24:27.337:INFO:localstack.services.dynamodb.server: Initializing DynamoDB Local with the following configuration:
2022-05-24T23:24:27.337:INFO:localstack.services.dynamodb.server: Port:	41345
2022-05-24T23:24:27.337:INFO:localstack.services.dynamodb.server: InMemory:	true
2022-05-24T23:24:27.337:INFO:localstack.services.dynamodb.server: DbPath:	null
2022-05-24T23:24:27.337:INFO:localstack.services.dynamodb.server: SharedDb:	true
2022-05-24T23:24:27.337:INFO:localstack.services.dynamodb.server: shouldDelayTransientStatuses:	false
2022-05-24T23:24:27.337:INFO:localstack.services.dynamodb.server: CorsParams:	*
2022-05-24T23:24:27.350:INFO:localstack.services.dynamodb.server:
```

could you please double check whether you are using the latest image, or send the full log output?

**Comment by giriprashant7891** [comment]
@thrau Sorry, I believe there is some confusion on my end. I am using the java APIs of the TestContainer code, with version `1.17.2`, which internally has a localstack module: https://www.testcontainers.org/modules/localstack/. So I'm guessing that my question is better directed towards that group?

**Comment by thrau** [comment]
which version of loclastack are you using @giriprashant7891? what's the value of `localstackImage` you are passing to testcontainers?

**Comment by giriprashant7891** [comment]
@thrau I believe that I'm using version `0.13.0`.

**Comment by thrau** [comment]
Could you try to upgrade to 0.14.3 see if the problem persists?

**Comment by giriprashant7891** [comment]
@thrau Unfortunately, I can only use the versions present in my organizations repository at the time being (which is 0.13.0). But it is no worry, for the time being, I have figured out a way around this. If this issue has been fixed in later versions, I'll close out this ticket.
