### ISSUE TITLE
client metadata and validation data are not being passed to Cognitos trigger lambdas

### ISSUE THREAD

**Issue by mkdirJava** [localstack/localstack#6151]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Given I have a sign up lambda trigger that needs data from verification data and client metadata
When I add a new user to cognito with the relevant data via cli or terraform
Then I get a error on the trigger lambda

### Expected Behavior

Given I have a sign up lambda trigger that needs data from verification data and client metadata
When I add a new user to cognito with the relevant data via cli or terraform
Then I should not get an error on the lambda should the data exsist

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

Have made a repo exhibiting the behaviour 
https://github.com/mkdirJava/localstack_bug_cognito_client_meta_data_and_varification_data_to_cognito_lambda_triggers

Thought about dockerising it but thought too much work and adds more confusion

### Environment

```markdown
- OS: Windows WSL Ubuntu
- LocalStack: docker image with tag localstack/localstack ( believe this is latest )
```

### Anything else?

Closest bug found was this one.

https://github.com/localstack/localstack/issues/3940

This is for user attribute to be exposed to cognitive lambda triggers

**Comment by giograno** [comment]
Hi @mkdirJava, thanks for reporting the issue! We released a fix that you will find in the `latest` Docker image. Please feel free to report any other issues you might encounter. Thanks for the patience 🙏
