### ISSUE TITLE
feature request: Support for SageMaker endpoint

### ISSUE THREAD

**Issue by yuvalshi0** [localstack/localstack#6161]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Is there any plan to support SageMaker endpoints API?
https://aws.amazon.com/blogs/machine-learning/using-amazon-sagemaker-inference-pipelines-with-multi-model-endpoints/

https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_CreateEndpointConfig.html
https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_CreateEndpoint.html

**Comment by SwiftyIsSwaggy** [comment]
Hello @yuvalshi0, I think this would be a great addition and I was also previously anticipating such a feature. However, I managed to find a simple workaround which was basically creating a lambda function to invoke the endpoint and then creating an API to invoke the lambda function.

**Comment by nathanielrindlaub** [comment]
@yuvalshi0 - have you had any luck spinning up SageMaker endpoints with LocalStack? This would also be phenomenally useful to me.

**Comment by silv-io** [comment]
Hi @yuvalshi0, @SwiftyIsSwaggy, @nathanielrindlaub, we're happy to announce initial support for SageMaker Endpoints in LocalStack Pro! To try it out, get the latest version `1.2.0` and check out our [docs](https://docs.localstack.cloud/aws/sagemaker/#model-deployment-and-inference) and [sample](https://github.com/localstack/localstack-pro-samples/tree/master/sagemaker-inference)!
