### ISSUE TITLE
bug: ECS cluster not removed properly using Pulumi

### ISSUE THREAD

**Issue by SanderHagen** [localstack/localstack#6172]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello, I am using Pulumi and Localstack to run a stack. I'm running into a problem with an ECS cluster. I start it using this code and it starts succesfully.
```
  const ecsCluster = new aws.ecs.Cluster(
    'test',
    {
      name: 'test',
    },
    {
      provider,
    },
  );
```
```awslocal ecs describe-clusters --cluster test --region eu-central-1``` shows this
```
{
    "clusters": [
        {
            "clusterArn": "arn:aws:ecs:eu-central-1:000000000000:cluster/test",
            "clusterName": "test",
            "status": "ACTIVE",
            "registeredContainerInstancesCount": 0,
            "runningTasksCount": 0,
            "pendingTasksCount": 0,
            "activeServicesCount": 0
        }
    ],
    "failures": []
}
```
But when I do `pulumilocal down` I get this error
```error: deleting urn:pulumi:localstack::Development::aws:ecs/cluster:Cluster::test: 1 error occurred:
    	* error waiting for ECS Cluster (arn:aws:ecs:eu-central-1:000000000000:cluster/test) to become Deleted: couldn't find resource (21 retries)```
Even though it does exist. It does however get deleted properly

### Expected Behavior

When doing `pulumilocal down` I expect the ECS cluster to be found and removed properly

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    `docker-compose up` from repo

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

using Pulumi

```  const ecsCluster = new aws.ecs.Cluster(
    'test',
    {
      name: 'test',
    },
    {
      provider,
    },
  );
```

Then `pulumilocal destroy` to remove the cluster

### Environment

```markdown
- OS: Ubuntu 22.04
- LocalStack: latest
```

**Comment by whummer** [comment]
Thanks for reporting @SanderHagen . We have now pushed a few enhancements for ECS which should (hopefully) get this issue resolved. Can you please pull the `latest` Docker image and give it another try? Please keep us posted on how it goes.. Thanks!

**Comment by whummer** [comment]
Hi again @SanderHagen , quick follow-up - closing this issue as resolved for now. Please let us know if the problem persists - happy to look into it in more detail in that case. Thanks!
