### ISSUE TITLE
Incorrect S3 GetBucket Content-Type

### ISSUE THREAD

**Issue by steedlem** [localstack/localstack#618]
When I make a request to 

http://mybucket.localhost:4572/?prefix=folder%2F&marker=folder%2F&max-keys=1001

I see the Content-Type header is text/xml; charset=utf-8  but when I make the call to aws directly:

http://mybucket.s3.amazonaws.com/?prefix=folder%2F&marker=folder%2F&max-keys=1001

I see Content-Type header is application/xml

My S3 Client relies on application/xml.  I was able to edit the client code to look for text/xml if I am in my local env, but I figured this should probably be changed.

**Comment by whummer** [comment]
Thanks for reporting @steedlem - fixed in #645
