### ISSUE TITLE
Can't delete items from S3 bucket 

### ISSUE THREAD

**Issue by RichSchulz** [localstack/localstack#6187]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After creating a bucket in the localstack I can save objects to that bucket from my client (which is a Python backend using boto3), and can get the head of that object from my client, and list the objects in that bucket, but I cannot delete that exact same object (getting a 404 Command not found error).

From delete object I get the following error `botocore.exceptions.ClientError: An error occurred (404) when calling the DeleteObject operation: Not Found`

### Expected Behavior

I would expect that I can also delete and list the objects in the bucket from my client

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    Deploying the latest helm chart on EKS

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal s3 mb s3://sample-bucket

Then from the python client using boto3 I perform the following steps:
Assuming KEY is an existing key
```
s3_client = boto3.client("s3", endpoint_url="http://localstack:4566/", region_name="us-east-1", config=Config(signature_version=UNSIGNED))
s3_client.delete_object(Bucket='sample-data', Key=KEY)
```

Also failing is:
`s3_client.list_buckets()`

### Environment

```markdown
- OS: deploying it on EKS
- LocalStack: 0.14.2 (from the latest helm chart)
```

### Anything else?

When performed on an actual S3 bucket all of the above operations work with the same client code

**Comment by whummer** [comment]
Thanks for reporting @RichSchulz . Can you please share the value of `KEY`, as well as the steps performed to create an object under that key? Potentially, the issue could be related to the KEY, e.g., if it contains special characters, or multiple slashes in sequence (`...//...`). Thanks

**Comment by RichSchulz** [comment]
Thanks for the reply @whummer . The key was created with the same client using `s3_client.put_object(Body=file, Bucket=self.bucket_name, Key=key)`. The key used was a postgresql generated UUID (one example key which didn't work was `38800f86-9c2d-4a8b-9eb6-98869655b9b9`). Hope that helps, let me know if you need more information

**Comment by peterson-dc** [comment]
I'm experiencing the exact same issue as @limedaniel with version 1.1.0

**Comment by edanisko** [comment]
same issue in 1.2.0

**Comment by anugrahsinghal** [comment]
same issue in 1.2.1.dev

**Comment by bentsku** [comment]
Hi @limedaniel, @peterson-dc, @edanisko and @anugrahsinghal, do you still encounter the issue with our latest version?
Also, just wanted to confirm, the buckets you created are not versioned?

**Comment by Traumlos** [comment]
possible solution for this problem [in this thread
](https://github.com/localstack/localstack/issues/3573#issuecomment-774696949)

as localstack requieres a `/` as prefix for the bucketname
