### ISSUE TITLE
Allow setting the Postgresql version when using the RDS service

### ISSUE THREAD

**Issue by holyoaks** [localstack/localstack#6188]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Currently, enabling the RDS service locks the Postgresql version to 11.14. My application relies on JSONB columns, which are not available until Postgres 12. Boto3 and AWS of course allow specifying a wide range of supported Postgresql versions, from 11 up to 14.2. While I can comprehend that supporting every minor version of Postgres in localstack may not be viable, at least we should have the option to specify the major version of Postgres that we would like to use in localstack. I think that the current version and two prior (currently 14, 13, and 12) should be sufficient to support. Sticking with 11.14, frankly, means that localstack is significantly out of date with what most software will be using.

**Comment by holyoaks** [comment]
Absolutely. For my needs, any version of 12 would be better than 11.14. Thanks!

**Comment by sandrade25** [comment]
@thrau 
if managing multiple versions introduces too much complexity, 
would a compromise of being able to specify DB versions in docker compose variables be doable? 
so it's still a single version. But the version can be specified by the user running the container?

**Comment by steffyP** [comment]
Hi @holyoaks, hi @sandrade25 

for RDS instances using postgres, we have a [new feature that takes the defined engine-version into account](https://docs.localstack.cloud/aws/rds/#postgres-versions). We currently support postgres versions 11, 12, and 13. 
You need to set the env `RDS_PG_CUSTOM_VERSIONS=1` to enable the feature. 

Does it solve your problem?

**Comment by steffyP** [comment]
Hi @holyoaks,
the feature is available in LocalStack version 1.0.0 upwards. 
Exactly, you can then use the API call for `create-db-instance` or `create-db-cluster` and set `--engine-version` accordingly. 
Please be aware that only major versions are taken into regard.

**Comment by holyoaks** [comment]
Perfect. Thank you!
