### ISSUE TITLE
DynamoDB stream ARN as `stream/latest`

### ISSUE THREAD

**Issue by xtaixe** [localstack/localstack#6196]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

With LocalStack `0.14.2` we were using something like `arn:aws:dynamodb:ap-south-1:000000000000:table/table-name/stream/latest` as the DynamoDB stream ARN and it was working fine. With `0.14.3` we see the following error:
```
2022-06-03T08:49:26.263:ERROR:localstack.services.awslambda.event_source_listeners.stream_event_source_listener: An error occurred (ResourceNotFoundException) when calling the DescribeStream operation: Stream arn:aws:dynamodb:us-east-1:000000000000:table/04tEMt8/stream/latest was not found.

Traceback (most recent call last):

  File "/opt/code/localstack/localstack/services/awslambda/event_source_listeners/stream_event_source_listener.py", line 307, in _monitor_stream_event_sources

    stream_description = self._get_stream_description(stream_client, stream_arn)
```

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

1. Run localstack
2. Create a DynamoDB table
3. Create a Lambda with an event source mapping with the table ARN + `/stream/latest`
4. Add items to the table
5. Get the error mentioned above.

### Environment

```markdown
- OS: macOS 12.4
- LocalStack: 0.14.3
```

### Anything else?

I understand this is not an AWS feature, but it was supported before and it feels that for testing it makes sense to support some additional stuff that make things easier.

Actually, this is going to be a blocker for us to be able to keep upgrading LocalStack. We generate tons of stuff before even running LocalStack and not being able to obtain the ARN until runtime would be a huge undertaking and source of complexity, so, to set expectations, we would really appreciate to get some guidance on if this is going to be considered to be fixed/added or it's unlikely. Thanks.

**Comment by xtaixe** [comment]
Hi. Any chance we can get some feedback on this soon to set expectations on our side and start figuring out what are our options to be able to upgrade? Thanks. cc @silv-io

**Comment by MarcelStranak** [comment]
Hi @xtaixe, can you please download the latest release of LocalStack 0.14.4 or  localstack/localstack:latest to see if the issue is persisting? Thank you.

**Comment by xtaixe** [comment]
@whummer as I mentioned this is a huge blocker for us since we generate everything before running Localstack and this is the only resource without a predefined name (at least from what we use). All the solutions we have considered are quite problematic in one way or another.

I understand that you don't want to have certain behaviors that are too different from AWS. I wonder if in this case a feature (environment variables?) to predefine the name/time that the stream will have could be considered. That seems more reasonable as a setup for a testing element like Localstack, than using the `/latest` stream name.

(sorry for the late reply, I was on leave).
