### ISSUE TITLE
Unimplemented ElastiCache API

### ISSUE THREAD

**Issue by enes789** [localstack/localstack#6197]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

The following API is reported as Not Implementing when using terraform with Localstack Pro:

-    API action 'DescribeCacheParameters' for service 'elasticache' not yet implemented

### 🧑‍💻 Implementation

When I try to create ElastiCache as a Resource Block on localstack, everything is ok. But trying to create cloudposse/elasticache-redis/aws module, it gives error like `Error: InternalFailure: API action 'DescribeCacheParameters' for service 'elasticache' not yet implemented`. 

Here is the terraform codes that I got a success result:

```
resource "aws_elasticache_cluster" "example" {
  cluster_id           = "cluster-example"
  engine               = "redis"
  node_type            = "cache.t3.micro"
  num_cache_nodes      = 1
  parameter_group_name = "default.redis6.x"
  port                 = 6379
  engine_version       = "6.2"
}

```

Here is the terraform codes that I got a failure result:

```
module "redis" {
  source  = "cloudposse/elasticache-redis/aws"
  version = "0.43.0"

  name        = "localstack"
  stage       = "test"
  namespace   = "local"
  environment = "local"

  vpc_id                               = "vpc-130c3498"
  allowed_security_groups             = ["sg-0d62fd9a0d2af04e3"]
  subnets                              = ["subnet-72cce7ba","subnet-c80f5f36"]
  cluster_size                         = 1
  instance_type                        = "cache.t3.micro"
  apply_immediately                    = true
  cluster_mode_enabled                 = true
  multi_az_enabled                     = true
  automatic_failover_enabled           = true
  cluster_mode_num_node_groups         = 1
  cluster_mode_replicas_per_node_group = 1
  engine_version                       = "4.0.10"
  family                               = "redis4.0"
  at_rest_encryption_enabled           = false
  transit_encryption_enabled           = false
  cloudwatch_metric_alarms_enabled     = true
  snapshot_retention_limit             = 1

  parameter          = [{name="cluster-enabled",value="yes"},{name="notify-keyspace-events",value="lK"}]
}

```

**Comment by thrau** [comment]
hi @enes789, thanks for reporting! looks like indeed we don't have the API method implemented yet. i can't give you an exact ETA but we'll look into getting it on the roadmap!

**Comment by silv-io** [comment]
Hi @enes789, we have now added the implementation to the requested feature. The addition is deployed and should resolve the problem you have reported. Would you please pull the latest Docker image and give it another try? Thank you.

**Comment by silv-io** [comment]
Hi @enes789, that error should be fixed in the latest Docker image. Can you pull again and try it out? Thank you

**Comment by enes789** [comment]
Hi @silv-io. I tried it. The problem I have looks solved. It is running well. Thanks
