### ISSUE TITLE
LocalstackDockerTestRunner to use docker-compose.yml

### ISSUE THREAD

**Issue by vujevits** [localstack/localstack#620]
It would be nice to be able to use the same docker container during development and when running my tests. Right now it seems like the test runner is pulling an image where all services are available, with random ports.

**Comment by galvinograd** [comment]
+1

**Comment by whummer** [comment]
Thanks for reporting @vujevits @galvinograd . This is a pretty old request - meanwhile, the Java client has been moved to a separate repo here: https://github.com/localstack/localstack-java-utils . Please feel free to open an issue there, or contribute a pull request to add this functionality. Thanks for your help!
