### ISSUE TITLE
How to define API Gateway V2 hostname predicatble via docker-compose?

### ISSUE THREAD

**Issue by ellisium** [localstack/localstack#6201]
### Is there an existing issue for this?

- [X] I have searched the existing issues and read the documentation

### Question

I found that doc section => 
> Providing custom IDs for API Gateway REST APIs: You can specify tags={"_custom_id_":"myid123"} on creation of an API Gateway REST API, to assign it the custom ID "myid123" (can be useful to have a static API GW endpoint URL for testing).

How can I do same thing via docker-compose? To match with my domainName?
Otherwise, how can I get this env? value from my cloudFormation script to initialize my domainName matching with it?

Thanks

**Comment by whummer** [comment]
Thanks for reporting @ellisium , can you please share some details on how your REST API is being created, and what exactly you'd like to achieve? Please also share your CloudFormation template to help us fully understand and replicate the use case. Thanks!

**Comment by ellisium** [comment]
hello @whummer thx for reply.

In my case, the hostname/APIID deployed on aws is based on feature branch name, ex branch-XXX.xxx.dev so it's predictable. 
So I would like to configure localstack following the same aws pattern via docker-compose

Adding in docker-compose YML a new key:
`    environment:
       - CUSTOM_ID=branch-XXX.xxx.dev
       - STAGE=local 
`
=>  `http://<apiId>.execute-api.localhost.localstack.cloud:4566/<stageId>/<path>`
=> `http://$CUTOM_ID.execute-api.localhost.localstack.cloud:4566/$STAGE/<path>`
=> `http://branch-XXX.xxx.dev.execute-api.localhost.localstack.cloud:4566/local/<path>`
Main stack: 
` new ApiStack(this, 'api', {
      certificateArn: config.edgeCertificateArn,
      domainName: config.domainName,
      subDomainName: getSubDomainName('api'),
});`

Nested API stack:
`
   const domainName = `${props.subDomainName}.${props.domainName}`;

    this.domain = new DomainName(this, 'domain', {
      domainName,
      certificate: Certificate.fromCertificateArn(
        this,
        'certificate',
        props.certificateArn,
      ),
    });

this.api = this.create_http_api('api', {
      corsPreflight: {
        allowHeaders: ['Authorization', 'Content-Type'],
        allowMethods: [
          CorsHttpMethod.GET,
          CorsHttpMethod.HEAD,
          CorsHttpMethod.OPTIONS,
          CorsHttpMethod.POST,
          CorsHttpMethod.PUT,
          CorsHttpMethod.DELETE,
        ],
        allowOrigins: ['*'],
        maxAge: Duration.days(1),
      },
      defaultDomainMapping: {
        domainName: this.domain,
      },
    });

 this.apiHandler = this.create_lambda('handler', {
      entry: path.resolve(
        __dirname,
        '../../../../api/build/lambdas/api/index.js',
      ),
      environment: {
        BUCKET_NAME: this.bucket.bucketName,
        CUSTOM_DATA_BUCKET: props.customDataBucket.bucketName,
        ENVIRONMENT: domainName,
      },
    });
`

**Comment by ellisium** [comment]
I will add that API gateway is created via cloud formation on localstack however apiId is dynamic one and doesnt match with DomainName instanciation.  Can you consider to complete cloud formation feature to support this if it's not possible to predefine apiId via docker-compose variable?
