### ISSUE TITLE
PRO feature request: Support for JdbcTargets with Glue crawlers

### ISSUE THREAD

**Issue by jasonboutwell** [localstack/localstack#6203]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

I need to create a crawler that will run against a source Redshift table via JDBC, create the corresponding Glue table, and populate the partition data. Currently, this is only possible using S3Targets. Thanks!

**Comment by alexrashed** [comment]
Since v1, there is initial support for RedShift targets as JdbcTargets in Glue Crawlers.
I'm going to close this issue for now, please feel free to create a new issue if you experience any problems with RedShift JDBC connections as JdbcTarget.
