### ISSUE TITLE
bug: SNS delivery logs always created

### ISSUE THREAD

**Issue by GalFuchs** [localstack/localstack#6216]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We are testing conditional enabling/disabling of SNS delivery logging in our Terraform configuration.
However, it seems LocalStack enables SNS delivery logs regardless of whether or not the appropriate IAM roles are created and supplied/configured, which makes it impossible for us to test this.

Is this the expected outcome? Am I wrong in assuming LocalStack aims to emulate AWS as closely as possible, without such shortcuts (which could lead to unexpected behaviour)?

### Expected Behavior

```
resource "aws_sns_topic" "topic" {
  name              = "test-topic"

  sqs_success_feedback_role_arn = var.enable_sns_log ? var.sns_success_iam_role_arn : null
  sqs_failure_feedback_role_arn = var.enable_sns_log ? var.sns_failure_iam_role_arn : null
  sqs_success_feedback_sample_rate = var.enable_sns_log ? 100 : null
}
```

SNS delivery logs should not be created when feedback role ARNs are not supplied and vice versa

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker-compose, irrelevant in this case though.

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    See above Terraform snippet

### Environment

```markdown
- OS: macOS Monterey
- LocalStack: 0.14.4.dev
```

**Comment by MarcelStranak** [comment]
Hi @GalFuchs  are you running LocalStack with ENFORCE_IAM=1?

https://docs.localstack.cloud/aws/iam/

**Comment by GalFuchs** [comment]
Hi @MarcelStranak - no I am not. You might want to add it to https://docs.localstack.cloud/localstack/configuration/ as well.
