### ISSUE TITLE
Are s3api acls supported? 

### ISSUE THREAD

**Issue by andres-lowrie** [localstack/localstack#622]
Hello, 

Firstly thanks for all the hard work on this, total lifesaver :heart: 

-------

So I'm trying to set some acls on a bucket, but I'm getting a timeout and nothing in the logs (I'm running via docker-compose)

```
aws s3api --endpoint-url http://127.0.0.1:4572 put-bucket-acl --acl x-amz-grant-read --bucket user1

An error occurred (500) when calling the PutBucketAcl operation (reached max retries: 4): Internal Server Error
```

was wondering if this feature is supported or not (or if a plans to support it are on some roadmap)

Thank you much

**Comment by whummer** [comment]
Thanks for reporting @andres-lowrie . I believe `x-amz-grant-read` is not a valid ACL value for use with `put-bucket-acl`. Looking at the API specs (https://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketPUTacl.html) , it seems that `x-amz-grant-read` is an HTTP header name that would require as values a list of grantees. (`"Allows the specified grantee(s) to list the objects in the bucket"`)

What you probably want is an ACL of `public-read`:
```
aws s3api --endpoint-url http://127.0.0.1:4572 put-bucket-acl --acl public-read --bucket user1
```

Closing this issue now, but please feel free to comment here if you have any other questions.
