### ISSUE TITLE
bug: Secrets manager "ReplicateSecretToRegions not yet implemented"

### ISSUE THREAD

**Issue by elbazon** [localstack/localstack#6221]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When attempting to create a secrets manager with replication to whatever region, I am given the following error message:
"Error: error adding Secrets Manager Secret replica: InternalFailure: API action 'ReplicateSecretToRegions' for service 'secretsmanager' not yet implemented".

The issue is that I did not receive this message the first time creating the resource.
But when I try to update the resource, the issue occurs.

### Expected Behavior

No issues whatsoever....

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

I am using terraform to create my resources.
This is the .tf file content:

########################################
#     Email Sender Lambda Env Vars     #
########################################
```
resource "aws_secretsmanager_secret" "emails-sender-env-vars" {
  name = "${var.product_name}/${var.project_env}/${trimprefix(module.emails-sender-lambda.lambda_name, "${var.project_env}-${var.product_name}-")}-env-vars"
  description = "${var.product_name}/${var.project_env}/${trimprefix(module.emails-sender-lambda.lambda_name, "${var.project_env}-${var.product_name}-")}-env-vars"
  kms_key_id = var.kms_secretsmanager

  replica {
    region = "eu-central-1"
  }

  tags = merge(local.base_tags, {
    function = "${trimprefix(module.emails-sender-lambda.lambda_name, "${var.project_env}-${var.product_name}-")}"
  })
}
```
### Environment

```markdown
- OS: macOS Monterey 12.3.1
- LocalStack: latest
```

### Anything else?

nope

**Comment by cmoralesmx** [comment]
Hi, is someone already working on this? I'd like to contribute, I've setup a dev environment following your documentation

**Comment by HarshCasper** [comment]
@cmoralesmx We have LocalStack engineers working on this. I am assigning you as well so that you can put up a PR for this, and maybe our engineers can help you with writing tests :)

**Comment by dfangl** [comment]
This issue is officially freed up now, so feel free to take it @cmoralesmx .

**Comment by cmoralesmx** [comment]
Thanks @HarshCasper, I'm all in for writing tests!
Pardon my ignorance @dfangl, I'm not sure how to proceed from here? I usually open a PR after committing changes. In this case I haven't yet.

**Comment by dfangl** [comment]
Just opening a PR with `fixes #...` works and will properly reference (and close when merged) this issue. You are already assigned, so feel free to start right away!
