### ISSUE TITLE
Can't pass extra arguments to Docker when spinning EC2 instances

### ISSUE THREAD

**Issue by davidcsi** [localstack/localstack#6226]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Need to pass extra arguments to docker when starting new instances:

```
awslocal ec2 run-instances --image-id ami-a33ac4f1069a --count 1 --instance-type t2.micro --key-name MyKeyPair --security-group-ids --subnet-id $first_subnet --associate-public-ip-address
```

This starts the docker with no access from the out side

### Expected Behavior

Passing extra arguments to Docker when starting the containers, something like:

```
DOCKER_EC2_EXTRA="-p 0.0.0.0:8080:80 -v ${pwd}/localconfig:/opt/localconfig" awslocal ec2 run-instances --image-id ami-a33ac4f1069a --count 1 --instance-type t2.micro --key-name MyKeyPair --security-group-ids --subnet-id $first_subnet --associate-public-ip-address
```

This would run the container like:

```
docker run -p 0.0.0.0:8080:80 -v ${pwd}/localconfig:/opt/localconfig ...
```
And make the container accessible from the outside as well as allow to mount the specific volume, which development-wise would be VERY useful.

### How are you starting LocalStack?

Custom (please describe below)

### Steps To Reproduce

```
LOCALSTACK_API_KEY=[my-key] DEBUG=1 SERVICES=ssm,s3,ec2,route53,iam,cloudformation localstack start
```

### Environment

```markdown
- OS: Mac OSX 12.4
- LocalStack: 0.14.2.9
```

**Comment by davidcsi** [comment]
Hello all, I see this was accepted, but not sure if it's been implemented.

**Comment by viren-nadkarni** [comment]
Thanks for reporting this, tracking the port-binding feature request at https://github.com/localstack/localstack/issues/6546

**Comment by viren-nadkarni** [comment]
The ability to expose ports of Dockerised instances has now been implemented. Please refer to [this page](https://docs.localstack.cloud/user-guide/aws/elastic-compute-cloud/#networking) for more details.

To add files to the instance storage, we recommend using either a [custom Docker base image](https://docs.localstack.cloud/user-guide/aws/elastic-compute-cloud/#base-images), or using [user data](https://docs.localstack.cloud/user-guide/aws/elastic-compute-cloud/#user-data) to download them remotely.
