### ISSUE TITLE
Localstack docker login error

### ISSUE THREAD

**Issue by Cpinto0594** [localstack/localstack#6228]
### Is there an existing issue for this?

- [X] I have searched the existing issues and read the documentation

### Question

Hi i'm facing this issue when executing this command:

aws ecr --region us-west-2 --profile localstack --endpoint-url=https://localhost.localstack.cloud:4566/ get-login-password | docker login --username AWS --password-stdin localhost.localstack.cloud:4511/PROJECT_NAME

list index out of range
Error: Cannot perform an interactive login from a non TTY device

aws version:
aws-cli/2.4.4 Python/3.8.8 Windows/10 exe/AMD64 prompt/off

Localstack image:
image: localstack/localstack:0.13

**Comment by DaKeiser** [comment]
This command should help you out.

`docker login -u AWS -p $(aws ecr --region us-west-2 --profile localstack --endpoint-url=https://localhost.localstack.cloud:4566/ get-login-password) localhost.localstack.cloud:4511/PROJECT_NAME`

It's not a Localstack issue though.

**Comment by whummer** [comment]
That's great, thanks @DaKeiser for providing a fix/workaround, and @Carlos-Pinto-J for confirming it works..! 👍
