### ISSUE TITLE
bug: Wrong SentTimestamp value in Sqs Message Header

### ISSUE THREAD

**Issue by siarheiputsik** [localstack/localstack#6247]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am using testcontainer with localstack image 
```Java
var container = new LocalStackContainer(DockerImageName.parse("localstack/localstack:0.14.3"))
                 .withServices(SNS, SQS);
 ```
```Java
@SqsListener(value = "$queue}", deletionPolicy = ON_SUCCESS)
 void handle(@Payload MessageDto message, @Headers Map<String, String> headers) {
    
     // SentTimestamp = 1654854414 ~[Tue Jan 20 1970 03:40:54]
     String sentTimestamp = headers.get(SENT_TIMESTAMP_HEADER);
     Instant time = Instant.ofEpochMilli(Long.parseLong(sentTimestamp));
     
     // returns false as Tue Jan 20 1970 03:40:54 is not between now and now - 60s
     assertThat(time).isBetween(Instant.now().minusSeconds(60),
                                Instant.now());
}
```

### Expected Behavior

I expect `sentTimestamp` header in sqs message be in millis: 
``` Java
String sentTimestamp = headers.get(SENT_TIMESTAMP_HEADER);
Instant time = Instant.ofEpochMilli(Long.parseLong(sentTimestamp));
```
So the code above will return me ~now().

### How are you starting LocalStack?

Custom (please describe below)

### Steps To Reproduce

I am using testcontainer integrations    

```Java    
private static final LocalStackContainer CONTAINER = new LocalStackContainer(DockerImageName.parse("localstack/localstack:0.14.3")).withServices(SNS, SQS);
```

### Environment

```markdown
- OS: Windows 11 Pro. version: 21H2. OS build: 22000.708
- LocalStack: docker hub image localstack/localstack:0.14.3
```

### Anything else?

The same behavior was replicated for `localstack/localstack:0.14.3.1` image.
However, it's not the case for `localstack/localstack:0.14.2` version and below, header `sentTimestamp` returned in the correct format.

Btw, if returned timestamp [1654854414] multiply by 1000 then the expected time is returned [Fri Jun 10 2022 11:46:54].
So I assume there is a problem in second to millis conversion which was introduced in ` 0.14.3`

**Comment by bentsku** [comment]
Hello and thanks for your report,
It seems this issue has been resolved in #6147. Would you please pull the latest Docker image and give it a try?
Thank you!
