### ISSUE TITLE
PRO feature request: Cloudformation to support  DocDB::*

### ISSUE THREAD

**Issue by gooftroop** [localstack/localstack#6254]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Localstack states `DocumentDb` is supported, but Cloudformation support is missing (getting `Unexpected resource type DocDB::DBCluster` when attempting to create a new docdb). Can the cloudformation resources for DocDB be added?

**Comment by gooftroop** [comment]
Is this a feature that can be added in the near future? I'm currently blocked on progress with various services and am looking for a workaround without much luck

**Comment by whummer** [comment]
Hi @gooftroop , thanks for reporting. We have now pushed a few enhancements which should add support for DocDB resources. 👍  Can you please pull the `latest` Docker image and give it another try? Please let us know if there are any issues.. Thanks!
