### ISSUE TITLE
Bug: Not able to deploy lambda function via localstack and cdklocal - TypeScript

### ISSUE THREAD

**Issue by starfrogsplash** [localstack/localstack#6266]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`index.handler is undefined or not exported` for the simple lambda function

as you can see in the screenshot provided it is zipped in the cdk.out,

so im not sure what to do,

```
import { CfnOutput, Duration, Stack, StackProps } from 'aws-cdk-lib';
import * as sns from 'aws-cdk-lib/aws-sns';
import * as subs from 'aws-cdk-lib/aws-sns-subscriptions';
import * as sqs from 'aws-cdk-lib/aws-sqs';
import * as dynamodb from 'aws-cdk-lib/aws-dynamodb';
import { Function, Runtime, Code } from "aws-cdk-lib/aws-lambda"
import {LambdaIntegration, RestApi} from "aws-cdk-lib/aws-apigateway";
import { Construct } from 'constructs';

export class AwsCdkStack extends Stack {
  constructor(scope: Construct, id: string, props?: StackProps) {
    super(scope, id, props);

      const lambda = new Function(this, 'helloWorldLambda', {
        runtime: Runtime.NODEJS_12_X,
        code: Code.fromAsset('./lib/helloWorldLambda'),
        handler: 'index.handler'
      });

      const api = new RestApi(this,'api',{})

      const lambdaIntegration = new LambdaIntegration(lambda)
      
      const lambdaResource = api.root.addResource('hello')
      lambdaResource.addMethod("GET", lambdaIntegration)

      new CfnOutput(this, "Endpoint", { value: `http://localhost:4566/restapis/${api.restApiId}/prod/_user_request_${lambdaResource.path}` })
  }
}

```

![Screenshot 2022-06-13 at 23 19 29](https://user-images.githubusercontent.com/22579826/173466238-ee74c639-6997-4d33-8ee9-d01a258a4b78.png)
![Screenshot 2022-06-14 at 00 53 51](https://user-images.githubusercontent.com/22579826/173466244-4f88b74a-09b5-46d8-b02c-4a43a8fcc284.png)
![Screenshot 2022-06-14 at 00 55 13](https://user-images.githubusercontent.com/22579826/173466245-f3440fe0-dab4-44a0-ab2e-1f3a4c46856c.png)
![Screenshot 2022-06-14 at 00 55 36](https://user-images.githubusercontent.com/22579826/173466249-4abd83eb-08c8-417a-b869-0eaba3d8b94b.png)

### Expected Behavior

expect lambda function to run

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker-compose up
    
```
version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack:0.14.3
    network_mode: bridge
    ports:
      - "127.0.0.1:4510-4559:4510-4559"  # external service port range
      - "127.0.0.1:4566:4566"            # LocalStack Edge Proxy
    environment:
      - DEBUG=${DEBUG-}
      - DATA_DIR=${DATA_DIR-}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      - HOST_TMP_FOLDER=${TMPDIR:-/tmp/}localstack
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```
cdklocal bootstrap
cdklocal deploy
curl http://localhost:4566/restapis/7gw4zybpa5/prod/_user_request_/hello
```

### Environment

```markdown
- OS: macOS Monterey
- LocalStack: 0.14.3
```

### Anything else?

same issue which is closed https://github.com/localstack/localstack/issues/3510

which was apparently fixed at the latest version for docker, but im not having any luck at all for a simple app

**Comment by dominikschubert** [comment]
Hi @starfrogsplash ! As far as I can see the issue here should be that you're directly bundling the typescript file (`index.ts`) instead of transpiling it to javascript first. You'd either need to use an `index.js` file manually instead or use something like the CDK NodeJsFunction which will automatically use babel to transpile & package your function and any necessary dependencies.

**Comment by starfrogsplash** [comment]
![Screenshot 2022-06-14 at 09 49 34](https://user-images.githubusercontent.com/22579826/173535904-d0f07c99-026f-40b7-bd1c-9319ac5eaab1.png)

awesome that worked
