### ISSUE TITLE
bug: dynamodb batch write item returns 500 if missing primary key and sort key from item(s)

### ISSUE THREAD

**Issue by amwill04** [localstack/localstack#6290]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When running `batch-write-item` and `request-items` is missing the primary key and/or the sort key for a given table it returns `500` meaning that any `sdk` will try again before exhausting retries and hiding the true `ValidationException` error.

### Expected Behavior

Return `ValidationException` error

### How are you starting LocalStack?

With a `docker run` command

### Steps To Reproduce

```shell
docker run -d --rm -it -p 4566:4566 -p 4510-4559:4510-4559 localstack/localstack

aws --endpoint-url=http://localhost:4566 dynamodb create-table \
    --table-name temp-table \
    --attribute-definitions AttributeName=id,AttributeType=S AttributeName=sortKey,AttributeType=S \
    --key-schema AttributeName=id,KeyType=HASH AttributeName=sortKey,KeyType=RANGE \
    --provisioned-throughput ReadCapacityUnits=5,WriteCapacityUnits=5

aws --endpoint-url=http://localhost:4566 dynamodb list-tables


aws --endpoint-url=http://localhost:4566 dynamodb   batch-write-item \
    --request-items '{"temp-table":[{"PutRequest":{"Item":{"anotherKey":{"S":"missing primary key and sort key"}}}}]}'
```

### Environment

```markdown
- OS: macos
- LocalStack: latest
```

### Anything else?

Run this against AWS and correct error will return with no retries

**Comment by MarcelStranak** [comment]
Hi, Thank you for the report. Meanwhile, to get more detailed information, you can set `DEBUG=1`. This will provide more logging in the LocalStack logs.
More information about the env conf: https://docs.localstack.cloud/localstack/configuration/#core

**Comment by amwill04** [comment]
Checked that it wasnt an dynamodb local issue but If you use dyanmodb local directly you will receive the correct error response. 

```
❯ aws --endpoint-url=http://localhost:8000 dynamodb   batch-write-item \
    --request-items '{"temp-table":[{"PutRequest":{"Item":{"anotherKey":{"S":"missing primary key and sort key"}}}}]}'

An error occurred (ValidationException) when calling the BatchWriteItem operation: One of the required keys was not given a value
```

**Comment by amwill04** [comment]
I dont know enough regarding the inner workings of `localstack` to know why it does a `find_existing_items` but as the `request-items` are missing the `pirmaryKey` its failing here on the

```python
search_key[key_name] = put_item["Item"][key_name]
```

So it never actually calls `batch-write`

**Comment by giograno** [comment]
Hi @amwill04, thanks for reporting this issue. We released a fix you can find by pulling the `latest` Docker image.
Please do not hesitate to report any eventual problems.
