### ISSUE TITLE
feature request: 3rd party requirements for AWS Lambda hot swapping

### ISSUE THREAD

**Issue by ptrhck** [localstack/localstack#6291]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

The basic Python serverless example demonstrates how to deploy an AWS Lambda function to localstack and also demonstrates how to enable [hot code swapping](https://docs.localstack.cloud/integrations/serverless-framework/#local-code-mounting-for-lambda-functions). Either, I have missed this feature or it is not available yet: How swapping with third party requirements.

This issue https://github.com/localstack/localstack/issues/6181 addresses the problem already. There is no problem deploying an application with additional dependencies (For example this [serverless Flask API](https://github.com/serverless/examples/tree/v3/aws-python-flask-api)). But when you enable hot code swapping, the provided source code will be mounted to `/var/task`. Here, AWS Lambda unzips all the source code and the Python requirements. Now, when the local source folder is mounted to `/var/task`, this mount overrides the unziped files and the Python requirements are gone.

### 🧑‍💻 Implementation

The mount folder `/var/task` is fixed [here](https://github.com/localstack/localstack/blob/1adfeb2e9f54f448442dffba39d244024bba71cf/localstack/services/awslambda/lambda_executors.py#L1235). A starting point could be to make this configurable through an environment variable, such that I cloud mount my source code to `/var/task/src` specifically and all unzipped requiredments at `/var/task` would remain.

I guess changing this constant, would impact other things though.

### Anything else?

The only workaround I can currently think of is using a [Dockerfile](https://github.com/localstack/localstack/issues/6181) as I have more control about the Lambda environment. Can this be achieved with any current localstack implementation or is this a new feature?

**Comment by dfangl** [comment]
Hi! I will close this in favor of #6181. I already answered a possible solution in there, happy to discuss further improvements if you want in there!
