### ISSUE TITLE
Retain resource definitions between restarts

### ISSUE THREAD

**Issue by mikeholmesuk** [localstack/localstack#630]
I may be missing something but I've gone through the docs and the other issues on here and I can't seem to find anything relating to this (not even a 'no, you can't do that').

What I'm looking for in essence is a way of being able to have an instance of localstack running  in docker without then having to go and (re)define all the necessary resources every time it starts. This is firstly so I can set up an instance once and then not have to go through and do it every time I restart, but also so I have a manner of being able to share a portable instance of these definitions for local dev/ testing across the team I'm working with.

I suppose one way would be to have a way of creating/ configuring resources as environment variables so I could set up and make something portable using `docker-compose` or what have you.  That way only a docker-compose definition would be required. 

The other way I tried (and failed) was to spin up an instance in docker, add the resources via the AWS CLI and then commit the docker container as an image. That way I can check the image into our docker repo and have it pulled down again via docker compose. Again it doesn't retain definitions between restarts though.

Any thoughts on how I can achieve this?

**Comment by whummer** [comment]
Thanks for reporting. Please note that by default the state of the APIs is ephemeral - i.e., state is only kept in memory and not persisted to disk. Meanwhile, we do have persistence support available for a couple of services - see `DATA_DIR` variable. We will add support for more APIs as we go... Hope that helps, thanks.
