### ISSUE TITLE
bug: error using getMetricData

### ISSUE THREAD

**Issue by eddumelendez** [localstack/localstack#6303]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Using micrometer aws sdk v2 to put metrics in localstack's cloudwatch service. According to the logs put metrics are ok but when performing a `getMetricData` operation there is a `KeyError: 'metric_stat._stat'` and `File "/opt/code/localstack/localstack/aws/api/cloudwatch/__init__.py", line 1160, in get_metric_data
    raise NotImplementedError
NotImplementedError`

See logs [here](https://gist.github.com/eddumelendez/802e5eedea6fe4824e89971ff7562be2)

### Expected Behavior

Get the metric using the aws sdk v2

### How are you starting LocalStack?

With a `docker run` command

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run --rm -e SERVICES=cloudwatch -e DEBUG=1 -e LS_LOG=trace -p 4566:4566 localstack/localstack:0.14.3.1

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```java
Dimension dimension = Dimension.builder().name("app").value("test").build();
Metric metric = Metric.builder().namespace("awspring/spring-cloud-aws").metricName("test.count").dimensions(dimension).build();
MetricStat metricStat = MetricStat.builder().metric(metric).unit(StandardUnit.COUNT).period(60).build();
MetricDataQuery metricDataQuery = MetricDataQuery.builder().metricStat(metricStat).id("test1").returnData(true).build();
GetMetricDataResponse response = this.cloudWatchAsyncClient.getMetricData(GetMetricDataRequest
							.builder().startTime(startTime).endTime(endTime).metricDataQueries(metricDataQuery).build())
							.get();
```

### Environment

```markdown
- OS: macos M1 Pro
- LocalStack: 0.14.3.1
```

**Comment by steffyP** [comment]
Hi @eddumelendez,

I have a follow-up question regarding your `MetricDataQuery`: as I understand, the `MetricStat` from your code snippet do not have `stat` included. [According to the API reference](https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_MetricStat.html), it is a required argument though. 

When I add `stat` to your snippet, a response is returned (no errors in LocalStack either). 
```
MetricStat metricStat = MetricStat.builder().stat("SAMPLE_COUNT").metric(metric).unit(StandardUnit.COUNT).period(60).build();

```

Could this be the missing piece?

**Comment by eddumelendez** [comment]
you're right! I was missing it. thanks @steffyP !
