### ISSUE TITLE
bug: S3 RoutingRules do not seem to work

### ISSUE THREAD

**Issue by WezBacon** [localstack/localstack#6308]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When attempting to access a resource that does not exist within the relevant S3 bucket the routing rules do not redirect to the file I have specified.

`http://localhost:4566/mybucket/something.png` returns XML `<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>something.png</Key>
<RequestID>7a62c49f-347e-4fc4-9331-6e8eEXAMPLE</RequestID>
</Error>`

`http://mybucket.s3-website.localhost.localstack.cloud:4566/something.png` returns a 404 

### Expected Behavior

When attempting to access a resource that does not exist within the relevant S3 bucket the routing rules should redirect to the file I have specified.

visiting ` http://localhost:4566/mybucket/something.png` should redirect to `http://localhost:4566/mybucket/default.png`

visiting `http://mybucket.s3-website.localhost.localstack.cloud:4566/something.png` should redirect to `http://mybucket.s3-website.localhost.localstack.cloud:4566/default.png`

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    `  localstack:
    image: localstack/localstack-full:0.12.18
    hostname: localstack
    ports:
      #- 8901:4566
      - 8055:8080
      - 8056:8088
      - 4566-4599:4566-4599
    environment:
      - SERVICES=s3,sns,sqs,lambda,apigateway,apigatewayv2,cloudwatch,ec2,iam,secretsmanager
      - DOCKER_SOCK=/var/run/docker.sock
      - DOCKER_HOST=unix:///var/run/docker.sock
      - FORCE_NONINTERACTIVE=1
      - LAMBDA_REMOTE_DOCKER=false
      - LAMBDA_EXECUTOR=docker
      - LOCALSTACK_HOSTNAME=localstack
      - EDGE_PORT=4566
      - HOST_TMP_FOLDER=/tmp/localstack
      - PORT_WEB_UI=8088
      - LAMBDA_DOCKER_NETWORK=appnetwork
      - DEBUG=1
      - DEFAULT_REGION=eu-west-1
      - EAGER_SERVICE_LOADING=1
      - DISABLE_CORS_CHECKS=1
    networks:
      - appnetwork`

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal s3 mb s3://mybucket

    awslocal s3api put-bucket-website --bucket mybucket --website-configuration file:///mybucket-s3-website-config.json

mybucket-s3-website-config.json contains the following 
`{
    "IndexDocument": {
        "Suffix": "default.png"
    },
    "ErrorDocument": {
        "Key": "default.png"
    },
    "RoutingRules": [
    {
        "Condition": {
            "HttpErrorCodeReturnedEquals": "403"
        },
        "Redirect": {
            "HostName": "mybucket.s3-website.localhost.localstack.cloud:4566",
            "HttpRedirectCode": "302",
            "Protocol": "https",
            "ReplaceKeyWith": "default.png"
        }
    },
    {
        "Condition": {
            "HttpErrorCodeReturnedEquals": "404"
        },
        "Redirect": {
            "HostName": "mybucket.s3-website.localhost.localstack.cloud:4566",
            "HttpRedirectCode": "302",
            "Protocol": "http",
            "ReplaceKeyWith": "default.png"
        }
    }
]
}`
    

### Environment

```markdown
- OS: Ubuntu 20.04
- LocalStack: 0.12.18 and latest
```

### Anything else?

This is a setup that I have working already in production and so I know that the config is correct as far as AWS is concerned but it just refuses to work locally.

**Comment by macnev2013** [comment]
Hi @WezBacon, Thanks for reporting.

This has been resolved in the `latest` version of LocalStack.
Could you possibly try again with the `latest` version?

Please let us know if the problem persists. Thanks.
