### ISSUE TITLE
ContentLength not correctly set for Java sdk 2.0 S3Client when getting object

### ISSUE THREAD

**Issue by jonassvalin** [localstack/localstack#631]
When I perform a get-object request through the CLI I receive a ContentLength in the response:

`aws --endpoint-url=http://localhost:4572 s3api get-object --key tmp/some_file.tar.gz --bucket somebucketname C:\Users\User\Downloads\some_file.tar.gz`
```
{
    "LastModified": "Thu, 01 Mar 2018 08:13:42 GMT",
    "ContentLength": 25,
    "ETag": "\"e1c1a37e204f89a266e6bba6bb26e332\"",
    "ContentType": "binary/octet-stream",
    "Metadata": {}
}
```

However, when performing the same request in code using the Java sdk 2.0 S3Client the ContentLength is null:

```
ResponseInputStream<GetObjectResponse> responseInputStream = s3Client.getObject(GetObjectRequest.builder()
                    .bucket(bucketname)
                    .key(filename)
                    .build());
Long contentLength = responseInputStream.response().contentLength(); //is null
```

The S3Client works correctly and sets the contentLength property correctly in the response when accessing a file in a real bucket in AWS, so I suspect that there is something wrong in LocalStack causing this behaviour.

**Comment by whummer** [comment]
@jonassvalin Has this issue, by any chance, been fixed by PR #669?
