### ISSUE TITLE
bug: KeyError when try to insert records trought batchWrite

### ISSUE THREAD

**Issue by tecnoher** [localstack/localstack#6310]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Could you please take a look at this error please?

The error I'm getting from localstack logs is this:

`DEBUG:localstack.utils.threads: FINISHED: <Future at 0x7f87fea66d40 state=finished raised KeyError>
WARNING:localstack.utils.server.http2_server: Error in proxy handler for request POST http://localhost:4566/: 'uniqueDebtKey' Traceback (most recent call last):`

My table:

`{
    "Table": {
        "AttributeDefinitions": [
            {
                "AttributeName": "uniqueDebtKey",
                "AttributeType": "S"
            }
        ],
        "TableName": "test-debts-1",
        "KeySchema": [
            {
                "AttributeName": "uniqueDebtKey",
                "KeyType": "HASH"
            }
        ],
        "TableStatus": "ACTIVE",
        "CreationDateTime": 1655810837.978,
        "ProvisionedThroughput": {
            "LastIncreaseDateTime": 0.0,
            "LastDecreaseDateTime": 0.0,
            "NumberOfDecreasesToday": 0,
            "ReadCapacityUnits": 10,
            "WriteCapacityUnits": 10
        },
        "TableSizeBytes": 0,
        "ItemCount": 0,
        "TableArn": "arn:aws:dynamodb:us-east-1:000000000000:table/test-debts-1"
    }
}`

Items list:
`item [
  {
    uniqueDebtKey: { S: '201911-11-20000000000' },
    dueDate: { S: '2019-12-07' },
    taxPayer: { S: '20000000000' },
    paymentDescription: { S: 'AUTONO11/19' },
    amount: { S: '10559.74' },
    period: { N: 201911 },
    paymentType: { N: 11 }
  },
  {
    uniqueDebtKey: { S: '201911-11-20000000001' },
    dueDate: { S: '2019-12-05' },
    taxPayer: { S: '20000000001' },
    paymentDescription: { S: 'AUTONO11/19' },
    amount: { S: '7679.82' },
    period: { N: 201911 },
    paymentType: { N: 11 }
  }
]`

### Expected Behavior

I expect the process to save my two objects throw batchWrite method

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal s3 mb s3://mybucket

### Environment

```markdown
- OS:Ubuntu 20
- LocalStack: latest
```

**Comment by giograno** [comment]
Hi @tecnoher, many thanks for reporting your issue. I have been trying to replicate your issue; unfortunately, without success so far. What I've been doing is the following:

```bash
#!/bin/bash

# create the table
awslocal dynamodb create-table --table-name test-debts-1 \
  --attribute-definitions \
    AttributeName=uniqueDebtKey,AttributeType=S \
  --key-schema \
    AttributeName=uniqueDebtKey,KeyType=HASH \
  --provisioned-throughput ReadCapacityUnits=10,WriteCapacityUnits=10 

# write the items in batch
awslocal dynamodb batch-write-item --request-items file://items.json

# just check if the items have been correctly written
awslocal dynamodb scan --table-name test-debts-1
```

The content of `items.json` is the following:

```json
{
    "test-debts-1": [
        {
            "PutRequest": {
                "Item": {
                    "uniqueDebtKey": {
                        "S": "201911-11-20000000000"
                    },
                    "dueDate": {
                        "S": "2019-12-07"
                    },
                    "taxPayer": {
                        "S": "20000000000"
                    },
                    "paymentDescription": {
                        "S": "AUTONO11/19"
                    },
                    "amount": {
                        "S": "10559.74"
                    },
                    "period": {
                        "S": "201911"
                    },
                    "paymentType": {
                        "N": "11"
                    }
                }
            }
        },
        {
            "PutRequest": {
                "Item": {
                    "uniqueDebtKey": {
                        "S": "201911-11-20000000001"
                    },
                    "dueDate": {
                        "S": "2019-12-05"
                    },
                    "taxPayer": {
                        "S": "20000000001"
                    },
                    "paymentDescription": {
                        "S": "AUTONO11/19"
                    },
                    "amount": {
                        "S": "7679.82"
                    },
                    "period": {
                        "S": "201911"
                    },
                    "paymentType": {
                        "N": "11"
                    }
                }
            }
        }
    ]
}
```

Could you please share a few more details about:
- how you ran commands against LocalStack (command line, programmatically with any programming language, etc...);
- the specific arguments you used to create the table. I assumed a specific configuration from your description, but maybe I am missing something.

Thank you very much 🙏

**Comment by giograno** [comment]
I am closing this, as likely a possible duplicate of https://github.com/localstack/localstack/issues/6290. Feel free to re-open if the error re-occurs 🙏

**Comment by hkroger** [comment]
@giograno There is something wrong with region setting and `DYNAMODB_SHARE_DB=1` here. I used your example to create table and populate it.

If I  now set the `AWS_REGION` wrong on purpose, it should still work because `DYNAMODB_SHARE_DB=1` which I use?

```
❯ export AWS_REGION=us-east-1

❯ aws --endpoint-url=http://localhost:4566  dynamodb batch-write-item --request-items file://items.json

An error occurred (InternalError) when calling the BatchWriteItem operation (reached max retries: 2): exception while calling dynamodb.BatchWriteItem: Unknown table: test-debts-1 not found in dict_keys([])

❯ aws --endpoint-url=http://localhost:4566 dynamodb scan --table-name test-debts-1
```

BatchWrite fails but scan works just fine. Is it because table name in batchwrite goes along with the data?

**Comment by hkroger** [comment]
Note, the above issue is probably not related to the original problem reported so maybe splitting this up to another issue would make sense.
