### ISSUE TITLE
Unable to install localstack on mac

### ISSUE THREAD

**Issue by RayeesMir** [localstack/localstack#633]
<img width="1078" alt="screen shot 2018-03-02 at 12 15 33 pm" src="https://user-images.githubusercontent.com/11449067/36886814-2ada14de-1e14-11e8-8e87-ec282c227a4f.png">
<img width="901" alt="screen shot 2018-03-02 at 12 20 22 pm" src="https://user-images.githubusercontent.com/11449067/36886816-2cf43d3a-1e14-11e8-84fa-07c42a988394.png">
I am not able to install localstack on my mac Sierra

**Comment by whummer** [comment]
Thanks for reporting @RayeesMir . This is a known issue in recent versions of MacOS. See, for example, here, how this has been solved for other python packages: https://github.com/jupyterlab/jupyterlab/issues/3260#issuecomment-345866285

**Comment by kellyfj** [comment]
I hit this issue too - thanks for the fix - it got me further

**Comment by whummer** [comment]
Glad that helps. Going to close this issue - please reopen if the problem persists. Thanks
