### ISSUE TITLE
bug: amazonS3.putObject fails with InputStream > 268mb

### ISSUE THREAD

**Issue by mgrundie-r7** [localstack/localstack#6332]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When using the aws sdk for java putObject fails when I try to send a byte array greater then 268000000 bytes

```
var blobBytes = new byte[269000000];
metadata.setContentLength(blobBytes.length);
amazonS3.putObject(bucket, key, new ByteArrayInputStream(blobBytes), metadata);
```

> Caused by: com.amazonaws.SdkClientException: Unable to execute HTTP request: Broken pipe (Write failed)
> 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1207)
> 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1153)
> 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:802)
> 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:770)
> 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:744)
> 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:704)
> 	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:686)
> 	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:550)
> 	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:530)
> 	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5437)
> 	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5384)
> 	at com.amazonaws.services.s3.AmazonS3Client.access$300(AmazonS3Client.java:421)
> 	at com.amazonaws.services.s3.AmazonS3Client$PutObjectStrategy.invokeServiceCall(AmazonS3Client.java:6508)
> 	at com.amazonaws.services.s3.AmazonS3Client.uploadObject(AmazonS3Client.java:1856)
> 	at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1816)
> 	at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1748)
> 
> Caused by: java.net.SocketException: Broken pipe (Write failed)
> 	at java.base/java.net.SocketOutputStream.socketWrite0(Native Method)
> 	at java.base/java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:110)
> 	at java.base/java.net.SocketOutputStream.write(SocketOutputStream.java:150)
> 	at org.apache.http.impl.io.SessionOutputBufferImpl.streamWrite(SessionOutputBufferImpl.java:124)
> 	at org.apache.http.impl.io.SessionOutputBufferImpl.flushBuffer(SessionOutputBufferImpl.java:136)
> 	at org.apache.http.impl.io.SessionOutputBufferImpl.write(SessionOutputBufferImpl.java:167)
> 	at org.apache.http.impl.io.ContentLengthOutputStream.write(ContentLengthOutputStream.java:113)
> 	at org.apache.http.entity.InputStreamEntity.writeTo(InputStreamEntity.java:144)
> 	at com.amazonaws.http.RepeatableInputStreamRequestEntity.writeTo(RepeatableInputStreamRequestEntity.java:160)
> 	at org.apache.http.impl.DefaultBHttpClientConnection.sendRequestEntity(DefaultBHttpClientConnection.java:156)
> 	at org.apache.http.impl.conn.CPoolProxy.sendRequestEntity(CPoolProxy.java:152)
> 	at org.apache.http.protocol.HttpRequestExecutor.doSendRequest(HttpRequestExecutor.java:238)
> 	at com.amazonaws.http.protocol.SdkHttpRequestExecutor.doSendRequest(SdkHttpRequestExecutor.java:63)
> 	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123)
> 	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
> 	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
> 	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
> 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
> 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
> 	at com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72)
> 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1331)
> 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1145)
> 	... 56 common frames omitted

	
Changing the size of the byte array to 268000000 works.

### Expected Behavior

A PutObjectResult is returned instead of an exception

### How are you starting LocalStack?

With a `docker run` command

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

```
docker run --platform linux/arm64/v8 -it --name localstack \
-p 4566:4566 -p 8080 \
-e SERVICES=sqs,s3 -e HOSTNAME_EXTERNAL=localstack \
--add-host localstack:127.0.0.1 \
-v $HOME/localstacksettings/localstack_env:/docker-entrypoint-initaws.d:ro \
localstack/localstack
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```
    # create buckets
      for bucket in "${buckets[@]}"; do
        awslocal s3api create-bucket --bucket ${bucket}
      done
```

### Environment

```markdown
- OS: MacOS 12.4 Monterey (Apple Silicon)
- LocalStack: 0.14.2 / 0.14.3 / latest
```

### Anything else?

This works for my colleagues using an very old version of of localstack (0.9.1) but I've had to get a newer version since I have  an M1 Mac

**Comment by rei-paypay** [comment]
I'm seeing the same behaviour here where uploading a 284MB file will cause a `Connection was closed before we received a valid response from endpoint URL` error when using AWS CLI. Also docker seems to also get a SIGKILL and reboot every time I try to `cp` this file over to s3. Is there any update/solution to this?

**Comment by MarcelStranak** [comment]
Hi,

Could you please set in your AWS config file these values if the upload still fails?
Location: `~/.aws/config`

```
[default]
region = us-east-1
output = json
s3 =
  use_accelerate_endpoint = false
  addressing_style = path
```  

More information can be found here: https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html

For the bigger files, I would suggest using **multipart uploads** or **TransferManager**.

**Comment by mgrundie-r7** [comment]
@MarcelStranak  the config did not resolve the issue for me

**Comment by mgrundie-r7** [comment]
Using a transfer manager (see below) resolved the issue. I'm not sure why this works however since I read that TransferManager does not do multipart uploads for ByteArrayInputStream

`      TransferManager xfer_mgr = TransferManagerBuilder.standard().withS3Client(amazonS3).build();

      try 
      {
         var blobBytes = byteArrayOutputStream.toByteArray();
         metadata.setContentLength(blobBytes.length);
         //amazonS3.putObject(bucket, key, new ByteArrayInputStream(blobBytes), metadata);
         Upload xfer = xfer_mgr.upload(bucket, key, new ByteArrayInputStream(blobBytes), metadata);
         xfer.waitForUploadResult();
     }`

**Comment by thrau** [comment]
Thanks for sharing @mgrundie-r7! We are starting to rework S3 and http IO associated with file uploads so hopefully those problems will go away soon. Glad you found a workaround for now.
