### ISSUE TITLE
Implement AT_TIMESTAMP for opening Kinesis shard iterator

### ISSUE THREAD

**Issue by thaddock** [localstack/localstack#635]
My application uses AT_TIMESTAMP when restarting after failures, and I found that localstack's Kinesis does not support this:

InvalidArgumentException: Must either specify (1) AT_SEQUENCE_NUMBER or AFTER_SEQUENCE_NUMBER and StartingSequenceNumber or (2) TRIM_HORIZON or LATEST and no StartingSequenceNumber. Request specified AT_TIMESTAMP and no StartingSequenceNumber.

It would be a nice-to-have to also set fake timestamps somehow when adding to the queue.

**Comment by cablehead** [comment]
Yes, please.

**Comment by alegrin** [comment]
Would be very useful 🙏

**Comment by whummer** [comment]
@thaddock @cablehead @alegrin LocalStack uses kinesalite under the covers, which seems to support `AT_TIMESTAMP`: https://github.com/mhart/kinesalite/blob/4019d70a135226f33f1cdec4091f4391e631d2c9/actions/getShardIterator.js#L79

Can you share a snippet of code with your exact request? Did you specify the `StartingSequenceNumber` parameter in your request?

**Comment by thaddock** [comment]
I have verified, this works for me now, which is great.
