### ISSUE TITLE
Localstack Kinesis Data Streams to capture the DynamoDB table change events is performing very slow.

### ISSUE THREAD

**Issue by anekar3416** [localstack/localstack#6352]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We have recently started using the Localstack to mock couple of aws services in our development environment.
I am trying to process the DynamoDB change events using the Kinesis Data Streams, which is behaving as expected.

To run the functional tests I am using the test container to start the localstack container like below. 

```
private static final GenericContainer localstack =
            new GenericContainer("localstack/localstack:0.14.2")
                    .withExposedPorts(4566);
.
.
localstack.start();
```

The strange behaviour I am observing is that the test cases are taking lot of time to interact with the DynamoDB running on the localstack container.
Prior moving to the Localstack, my team was using the AWS DynamoDB local and the performance was very good.

I am just wondering is it because of the below mentioned slowness issue with the localstack?
https://github.com/localstack/localstack/issues/1205

Or is there some other configurations that I am missing here?
I am using gradle enterprise to run my tests with 10 remote executors.

**Comment by anekar3416** [comment]
Is there any update on this?

**Comment by ackdav** [comment]
Hello @anekar3416 - thank you for raising this issue. Is there anything specific to your setup/approach that isn't mentioned in the linked issue #1205 ?
Additionally, could you please update your localstack instance, try again, and compare the performance? (it should have improved quite a bit since opening this issue...)
