### ISSUE TITLE
Write a timestream record using .Net AWSSDK NuGet packages

### ISSUE THREAD

**Issue by gabrielhruiz** [localstack/localstack#6356]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We use the code (which is shown in section "Anything else") to write records using .Net 6 and AWSSDK NuGet packages.

We are sure that the Timestream services are running and configured correctly in LocalStack. We can see this in the LoacalStack web and in the CLI using awslocal commands.

When we try to write several records at line 79 and throw the error: _"Failed to discover the endpoint for the request. Requests will not succeed until an endpoint can be retrieved or an endpoint is manually specified."_ (complete stack trace is shown in section "Anything else" too). Then I try to Write a record using the CLI and that is written successfully.

### Expected Behavior

To write in LocalStack Timestream the records to see them in the web query editor.

### How are you starting LocalStack?

With a `docker run` command

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run -dt -p 4566:4566 -p 4571:4571 -p 443:443 -e LOCALSTACK_API_KEY='API_KEY' localstack/localstack

#### Create DB

    awslocal timestream-write  create-database --database-name timeStreamDB

#### Create Table

    awslocal timestream-write  create-table --database-name timeStreamDB --table-name timeStreamTable

### Environment

```markdown
- OS: Windows 11
- LocalStack: latest
- .Net 6
- AWSSDK.Core package version 3.7.12.3
- AWSSDK.TimestreamWrite package version 3.7.1.72
```

### StackTrace

Amazon.Runtime.Internal.EndpointDiscoveryResolverBase.ProcessInvokeEndpointOperation(String cacheKey, Func`1 InvokeEndpointOperation, Boolean endpointRequired)
   en Amazon.Runtime.Internal.EndpointDiscoveryResolverBase.ResolveEndpoints(EndpointOperationContextBase context, Func`1 InvokeEndpointOperation)
   en Amazon.TimestreamWrite.AmazonTimestreamWriteClient.EndpointOperation(EndpointOperationContextBase context)
   en Amazon.Runtime.Internal.EndpointDiscoveryHandler.DiscoverEndpoints(IRequestContext requestContext, Boolean evictCacheKey)
   en Amazon.Runtime.Internal.EndpointDiscoveryHandler.<InvokeAsync>d__2`1.MoveNext()
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Amazon.Runtime.Internal.CredentialsRetriever.<InvokeAsync>d__7`1.MoveNext()
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Amazon.Runtime.Internal.RetryHandler.<InvokeAsync>d__10`1.MoveNext()
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en Amazon.Runtime.Internal.RetryHandler.<InvokeAsync>d__10`1.MoveNext()
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Amazon.Runtime.Internal.CallbackHandler.<InvokeAsync>d__9`1.MoveNext()
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Amazon.Runtime.Internal.CallbackHandler.<InvokeAsync>d__9`1.MoveNext()
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Amazon.Runtime.Internal.ErrorCallbackHandler.<InvokeAsync>d__5`1.MoveNext()
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Amazon.Runtime.Internal.MetricsHandler.<InvokeAsync>d__1`1.MoveNext()
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   en Energy.Cloud.Server.MeasurementsDTOHandler.<SaveRecords>d__6.MoveNext()
   en ...\MeasurementsDTOHandler.cs: línea 79

### .Net Code

```
using Amazon.TimestreamWrite;
using Amazon.TimestreamWrite.Model;
using CloudWatch;
using Energy.Cloud.Model;

namespace Energy.Cloud.Server
{
    public class MeasurementsDTOHandler
    {
        
        private readonly ICloudWatchLogs _logger;

        private readonly IAmazonTimestreamWrite _timeStreamClient;

        private readonly IConfiguration _configuration;


        public MeasurementsDTOHandler(ICloudWatchLogs logger, IAmazonTimestreamWrite timeStreamClient, IConfiguration configuration)
        {
            _logger = logger;

            _timeStreamClient = timeStreamClient;

            _configuration = configuration;
        }

        public async Task Process(House house, MeasurementsDTO measurements)
        {
            var records = CreateMessagesToTimeStream(house, measurements);
            await SaveRecords(records);
        }

        private List<Amazon.TimestreamWrite.Model.Record> CreateMessagesToTimeStream(House house, MeasurementsDTO measurements)
        {
            var records = new List<Amazon.TimestreamWrite.Model.Record>();

            foreach(var measurement in measurements.Measurements)
            {
                string timeString = ((DateTimeOffset)Convert.ToDateTime(measurement.TimeStamp)).ToUnixTimeSeconds().ToString();

                var dimensions = new List<Dimension>{
                     new Dimension { Name = "GrafanaUserName", Value = house.GrafanaUserName },
                     new Dimension { Name = "HouseId", Value = house.Id.ToString() },
                     new Dimension { Name = "Device", Value = measurement.DeviceUserName },

                };

                var record = new Amazon.TimestreamWrite.Model.Record
                {
                    Dimensions = dimensions,
                    MeasureName = measurement.MeasurementType.ToString(),
                    MeasureValue = ConvertValue(MeasureValueType.DOUBLE, measurement.Value.ToString()),
                    MeasureValueType = MeasureValueType.DOUBLE,
                    Time = timeString,
                    TimeUnit = TimeUnit.SECONDS,
                    
                };

                records.Add(record);
            }
           
            return records;

        }

        private async Task SaveRecords(List<Record> records)
        {
            foreach (var chunk in records.Chunk(100))
            {
                try
                {

                    var writeRecordsRequest = new WriteRecordsRequest
                    {
                        DatabaseName = _configuration.GetSection("TimeStream").GetSection("Database").Value,
                        TableName = _configuration.GetSection("TimeStream").GetSection("TableName").Value,
                        Records = chunk.ToList()
                    };
                    WriteRecordsResponse response = await _timeStreamClient.WriteRecordsAsync(writeRecordsRequest);
                                

                }
                catch (RejectedRecordsException e)
                {
                    _logger.Error("RejectedRecordsException:" + e.ToString());
                    
                    foreach (RejectedRecord rr in e.RejectedRecords)
                    {
                        _logger.Error("RecordIndex " + rr.RecordIndex + " : " + rr.Reason);
                    }

                }
                catch (Exception ex)
                {
                    _logger.Error(ex.ToString());
                }
            }

        }

        private string ConvertValue(Amazon.TimestreamWrite.MeasureValueType valueType, string measureValue)
        {
            if (valueType == Amazon.TimestreamWrite.MeasureValueType.DOUBLE)
            {
                return Convert.ToDouble(measureValue).ToString().Replace(",", ".");
            }

            return measureValue;
        }
    }
}

```

**Comment by MarcelStranak** [comment]
Hi, can you please try to use an example from these docs?  https://docs.localstack.cloud/integrations/sdks/dotnet/

**Comment by gabrielhruiz** [comment]
We have changed the dependency injection of the service by `IAmazonTimestreamWrite _timeStreamClient = new AmazonTimestreamWriteClient(Amazon.RegionEndpoint.USEast1);` in the class constructor. Debugging the new code we are sure that credentials and endpoints are correct.

Now the error is "The table timeStreamTable does not exist.", but the DB and Tables were created previously.

Then we try to List all DBs to know info about the environment using the next code in the constructor:
```
IAmazonTimestreamWrite _timeStreamClient = new AmazonTimestreamWriteClient(Amazon.RegionEndpoint.USEast1);
var db = _timeStreamClient.ListDatabasesAsync(new ListDatabasesRequest()).Result;
```
But throws the next error: _'One or more errors occurred. (User: arn:aws:iam::564853041914:user/st-timestreamdb-iam-user is not authorized to perform: timestream:ListDatabases on resource: arn:aws:timestream:us-east-1:564853041914:database/* because no identity-based policy allows the timestream:ListDatabases action)'._

Maybe this case means that we have to create IAM roles in LocalStack? or really The code is not working with the correct environment though the debugger says another thing.

**Comment by gabrielhruiz** [comment]
We try using the next code too:
````
var timestreamConf = new AmazonTimestreamWriteConfig()
{
    RegionEndpoint = Amazon.RegionEndpoint.USEast1,
    ServiceURL = "http://localhost:4566"
};
IAmazonTimestreamWrite _timeStreamClient = new AmazonTimestreamWriteClient(timestreamConf);
````
But the error is the same: _Failed to discover the endpoint for the request. Requests will not succeed until an endpoint can be retrieved or an endpoint is manually specified._

**Comment by 78ptRiot** [comment]
Hey, I have been receiving the exact same error and was wondering if/how you were able to fix it?

**Comment by gabrielhruiz** [comment]
Hi, we don't have found a solution using LocalStack yet...

**Comment by kamal-mahmassani-cko** [comment]
+1 on this is very needed

**Comment by gabrielhruiz** [comment]
This issue was resolved by AWS as Nugget package bug.
