### ISSUE TITLE
bug: localstack pro apigateway v2 websocket does not call $disconnect

### ISSUE THREAD

**Issue by paulrobello** [localstack/localstack#6383]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when websocket disconnects the $disconnect is not called

### Expected Behavior

when websocket disconnects the $disconnect should be called

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)
docker compose up -d

Lots of Pulumi Typescript

### Environment

```markdown
- OS: OSX and Windows 11
- LocalStack: 0.14.4
```

**Comment by paulrobello** [comment]
Any updates on this? We have a pretty big websocket project that requires various cleanup tasks to be run on disconnect and would love to be using LS to prototype it.

**Comment by calvernaz** [comment]
@whummer did your recent routes changes fix this issue?

**Comment by paulrobello** [comment]
> @whummer did your recent routes changes fix this issue?

not sure what route changes you are referring to.

**Comment by paulrobello** [comment]
I have verified the last working docker version of LS Pro where the disconnect event fires is 0.14.2

**Comment by calvernaz** [comment]
Hi @paulrobello, sorry if you get confused I was messaging @whummer because they were some recent changes in the routes. I made a sample that you can try that call the disconnect route integration on disconnect. However, something worth to mention, as per AWS documentation, the disconnect route can be closed before the integration responds.

```
The connection can be closed by the server or by the client. As the connection is already closed when it is executed, $disconnect is a best-effort event. Gateway will try its best to deliver the $disconnect event to your integration, but it cannot guarantee delivery.
```

Localstack sample: https://github.com/localstack/localstack-terraform-samples/tree/master/apigatewayv2-ws-sample

**Comment by calvernaz** [comment]
@paulrobello AWS or Localstack will have little no none responsibility on calling disconnect client side. So, my suggestion is just make sure the client disconnect on client side (browser) is happening when you close the window or tab.

**Comment by paulrobello** [comment]
I am not saying that the backend has any responsibility in calling disconnect on client side. I am saying that closing the browser / tab does not call disconnect nor is there a clean way to intercept such a thing. What I am saying is that AWS somehow detects that the client is gone and invokes the disconnect event on the api-gw.

**Comment by calvernaz** [comment]
@paulrobello got it, it closes by inactivity - that would be worth to specify in the issue, what you are looking for is to close the connection by inactivity (idle).

**Comment by paulrobello** [comment]
For LS I believe if the browser is connected and idle for long enough the disconnect seems to fire just fine. However on browser close disconnect is never fired. In AWS on browser close the disconnect is fired  immediately not after some time has passed.

**Comment by cabeaulac** [comment]
I'm testing this on latest LS Pro

**Comment by calvernaz** [comment]
@cabeaulac Do you have a sample to reproduce it?

**Comment by cabeaulac** [comment]
@calvernaz  No, I don't have a stand-alone sample to reproduce this yet. I'm working on a new demo repo that should be able to reproduce it soon.
