### ISSUE TITLE
Docker Image not running properly [LocalstackDockerTestRunner]

### ISSUE THREAD

**Issue by fabianoo** [localstack/localstack#641]
Hello, guys.

I'm running integration tests in Java using the `LocalstackDockerTestRunner`. The thing is that when I run it on my machine it runs beautifully. But when I run it on my Jenkins machine, the container never gets ready.  So, when I get the container logs, I get the following error:

```
Starting local Elasticsearch (http port 4571)...
ERROR: 'chmod -R 777 /opt/code/localstack/localstack/infra/elasticsearch': chmod: /opt/code/localstack/localstack/infra/elasticsearch/data: No such file or directory

Error starting infrastructure: Command 'chmod -R 777 /opt/code/localstack/localstack/infra/elasticsearch' returned non-zero exit status 1 Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/infra.py", line 477, in start_infra
    t1 = plugin.start(async=True)
  File "/opt/code/localstack/localstack/services/infra.py", line 75, in start
    return self.start_function(**kwargs)
  File "/opt/code/localstack/localstack/services/es/es_starter.py", line 40, in start_elasticsearch
    run('chmod -R 777 %s/infra/elasticsearch' % ROOT_PATH)
  File "/opt/code/localstack/localstack/utils/common.py", line 618, in run
    return do_run(cmd)
  File "/opt/code/localstack/localstack/utils/common.py", line 615, in do_run
    raise e
CalledProcessError: Command 'chmod -R 777 /opt/code/localstack/localstack/infra/elasticsearch' returned non-zero exit status 1
```
What could it be? Someone could help me?

EDIT: I tried at least 5 different version of the docker container.

About the O.S.:
```
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.3.1611 (Core) 
Release:	7.3.1611
Codename:	Core
```
Docker version: `Docker version 17.06.2-ce, build cec0b72`

Kernel version: `3.10.0-514.10.2.el7.x86_64`

EDIT2: I upgraded the docker-ce, and the error continues. New version: `Docker version 17.12.1-ce, build 7390fc6`

EDIT3: I tested on 3 machines with kernel version 4.x and it worked as it mean. I get up another CentOS with the `3.10.0-514.10.2.el7.x86_64` version and the error was reproduced.

Regards,
Fabiano

**Comment by whummer** [comment]
Thanks for reporting - this issue should be fixed in the meantime.
