### ISSUE TITLE
bug: send large size message >256KB not throw exception

### ISSUE THREAD

**Issue by yin836** [localstack/localstack#6420]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When send big message (>256KB ), old version throw GenericQueueException, but not in latest version

### Expected Behavior

When send big message (>256KB ), should throw GenericQueueException

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

docker run localstack/localstack:latest

### Environment

```markdown
- OS:Ubuntu 20.04
- LocalStack:latest
```

**Comment by thrau** [comment]
Thanks for reporting, this has now been implemented in #6767 and available in 1.1+
