### ISSUE TITLE
feature request: Add support for AWS::IAM::AccessKey

### ISSUE THREAD

**Issue by itaibb** [localstack/localstack#6425]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When creating an AccessKey for a user via cdklocal, accesskey is not created. When outputting the accesskey id and secret, undefined is returned.
When trying to create the accesskey for the same user created via aws cli, accesskey is created properly.
when deploying to AWS with same code via CDK, accesskey is created for the user properly.
Code:
```
const user = new User(this, 'service-account-user', {
            userName: `test-user`
});
const accessKey = new CfnAccessKey(this, `test-user-access-key`, {
            userName: user.userName,
});
new CfnOutput(this, `test-user-access-key-id`, {value: accessKey.ref});
new CfnOutput(this, `test-user-access-key-secret`, {value: accessKey.attrSecretAccessKey});
```
CdkLocal Output:
```
Outputs:
TestStack.testuseraccesskeyid = undefined
TestStack.testuseraccesskeysecret = undefined
```
Localstack log:
```
2022-07-10T07:38:02.797:WARNING:localstack.utils.cloudformation.template_deployer: Unexpected resource type IAM::AccessKey when resolving references of resource testuseraccesskeyE1E625D3: {"Type": "AWS::IAM::AccessKey", "Metadata": {"aws:cdk:path": "TestStack/test-user-access-key"}, "LogicalResourceId": "testuseraccesskeyE1E625D3", "Properties": {"UserName": "test-user"}, "PhysicalResourceId": null}. To find out if IAM::AccessKey is supported in LocalStack Pro, please check out our docs at https://docs.localstack.cloud/aws/cloudformation
```
AwsLocal cli accesskey fetching:
```
awslocal iam list-access-keys --user-name test-user                   
{
    "AccessKeyMetadata": []
}
```

### Expected Behavior

AccessKey should be created for the user

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)
```
localstack start
```
#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)
```
const user = new User(this, 'service-account-user', {
            userName: `test-user`
});
const accessKey = new CfnAccessKey(this, `test-user-access-key`, {
            userName: user.userName,
});
new CfnOutput(this, `test-user-access-key-id`, {value: accessKey.ref});
new CfnOutput(this, `test-user-access-key-secret`, {value: accessKey.attrSecretAccessKey});
```
```
cdklocal bootstrap
cdklocal deploy
```

### Environment

```markdown
- OS: Monterey 12.4
- LocalStack: 0.14.4
```

**Comment by itaibb** [comment]
Thank you @dominikschubert! I'm waiting to hear about developments on this feature.

**Comment by pinzon** [comment]
The feature has been merged. Thank you for the report!

**Comment by aazbeltran** [comment]
This change it's causing issue with cloudformation about Serial
