### ISSUE TITLE
bug: S3Exception  instead of NoSuchBucketException

### ISSUE THREAD

**Issue by vfedoriv** [localstack/localstack#6440]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

in latest version (0.14.5)
s3Client.getObject() throw S3Exception instead of NoSuchBucketException if wrong bucket name provided

### Expected Behavior

throw NoSuchBucketException as in previous versions (0.14.4)

### How are you starting LocalStack?

With a `docker run` command

### Steps To Reproduce

use a new (0.14.5) version instead previous (0.14.4)

### Environment

```markdown
- OS: macOS 12.4
- LocalStack: 0.14.5/0.14.4
```

**Comment by thrau** [comment]
This was fixed in #6348, please give the latest image (1.0.3) a try.
