### ISSUE TITLE
MacOS M1/ARM64 Cockpit Download Corrupted

### ISSUE THREAD

**Issue by Simonl9l** [localstack/localstack#6442]
On receiving a download link email, downloading the installer DMG and attempting to start the Application I get this error
<img width="257" alt="image" src="https://user-images.githubusercontent.com/66816457/178644790-69559785-c504-4096-9479-32bc6dc892a6.png">

I'm running on Monterey  12.4
Apple M1 Max
14-Inch Mac Book Pro

I tried the link with both Edge (chromium) and Safari with same error

**Comment by HarshCasper** [comment]
Hi @Simonl9l 👋 

Thanks for reporting this issue! It is a known issue and can be easily solved by downloading the Intel version instead of the M1 version.

Please try it out and let me know if it works out. I am closing this issue now but would be happy to re-open it and investigate further if it doesn't work.

**Comment by Simonl9l** [comment]
I am running the intel version but would prefer to run the Apple Silicon version, since it is reportedly offered and runs native which is more efficient on my system.

When  will the Apple Silicon version be fixed?

**Comment by HarshCasper** [comment]
> When will the Apple Silicon version be fixed?

We will look into it on an immediate basis post v1 release 😄

**Comment by Simonl9l** [comment]
If suggest in the meantime then it may be a good idea to remove the Apple Silicon download option to avoid future issues?

**Comment by Simonl9l** [comment]
@HarshCasper as related followup, it seems there is possible an incompatibly with the x64 version running on the M1 Mac (via Rosetta2) and the underlying docker image. 

Via Safari in the Web App I get these errors:
<img width="1039" alt="image" src="https://user-images.githubusercontent.com/66816457/180897031-5acbdafa-a362-42b5-978e-502d242d69c8.png">
Via Edge (chromium) it seem to work. 

With a trail API key set in the Cockpit configuration LOCALSTACK_API_KEY=XXX it does not seem launch correctly. 
In Edge I don't see the additional services that PRO makes available.

This is my setup
<img width="420" alt="image" src="https://user-images.githubusercontent.com/66816457/180897168-491f7d91-4d1d-4bd3-9e7a-8f90c10c91d8.png">
