### ISSUE TITLE
bug: Lambda unreachable in docker-compose with named network

### ISSUE THREAD

**Issue by eob** [localstack/localstack#6455]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Localstack's lambda service is unreachable when trying to connect across a docker-compose defined network.

### Expected Behavior

Invoking lambda APIs such as 'list-functions' should work.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

Below shows how to reproduce the bug with two files and a single command:

* A Dockerfile
* A docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker-compose --file docker-compose.test.yml run shell

#### docker-compose.test.yml file

```
version: '3.9'

networks:
  testing:
    name: testing
    driver: bridge

services:
  localstack:
    image: localstack/localstack
    environment:
      - SERVICES=lambda
      - DEBUG=1
      - HOSTNAME=localstack
      - HOSTNAME_EXTERNAL=localstack
      - LAMBDA_DOCKER_NETWORK=bridge
    networks:
      - testing
    ports:
      - "4566:4566"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  shell:
    build:
      dockerfile: Dockerfile.networking.test
    networks:
      - testing
    depends_on:
      - localstack
    command: aws lambda --region us-west-2 --endpoint http://localstack:4566 list-functions
```

#### Dockerfile.networking.test file

```
FROM amazonlinux
RUN yum install -y awscli
RUN mkdir ~/.aws
RUN echo "[default]" >> ~/.aws/credentials
RUN echo "aws_access_key_id = test" >> ~/.aws/credentials
RUN echo "aws_secret_access_key = test" >> ~/.aws/credentials
RUN echo "[default]" >> ~/.aws/config
RUN echo "region = us-west-2" >> ~/.aws/config
RUN echo "output = json" >> ~/.aws/config
```

### Environment

```markdown
- OS: MacOS 12.3.1
- LocalStack: latest (via docker pull)
- Docker: 4.10.0
```

### Anything else?

There are a few conditions under which everything works fine:

* **If I don't use named networks**, instead just use the `link` docker-compose property with the default network, everything works fine. But this is not a viable solution for me however for other reasons (the broader environment into which my configuration sits; not visible from this isolated bug report)

* **If I remove the `HOSTNAME` configuration variable**, but I need to refer to localstack from within lambda functions, and so having a stable hostname such as `http://localstack/..` is important.. Plus this doesn't seem like it ought to interact with the networking configuration above.

**Comment by MarcelStranak** [comment]
Hi @eob, can you please try using this `docker-compose.yml` if it still fails?
Can you please share the logs of the failure, and how are you setting the hostname in lambda functions? Thanks.

```docker
version: '3.9'

networks:
  testing:
    name: testing
    driver: bridge

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    environment:
      - SERVICES=lambda
      - DEBUG=1
      - HOSTNAME=localstack
      - HOSTNAME_EXTERNAL=localstack
      - LAMBDA_DOCKER_NETWORK=testing
    networks:
      - testing
    ports:
      - "4566:4566"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  shell:
    build:
      dockerfile: Dockerfile.networking.test
    networks:
      - testing
    depends_on:
      - localstack
    command: aws lambda --region us-west-2 --endpoint http://localstack:4566 list-functions
```
