### ISSUE TITLE
PRO: Enable mutliple ingress ports for EKS' embedded k3d cluster

### ISSUE THREAD

**Issue by baermat** [localstack/localstack#6457]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Right now specifying different ports for different ingresses which can then be accessed via the load balancer is not possible. The only thing that seems to be configurable is the port of the load balancer as stated in the [docs](https://docs.localstack.cloud/aws/elastic-kubernetes-service/#configuring-an-ingress-for-your-services). Making them configurable would enable multiple ingresses.

### 🧑‍💻 Implementation

as @dfangl suggested
1) use the same tag based approach as for volumes
2) make it globally configurable (this would potentially cause problems with multiple clusters running)

**Comment by whummer** [comment]
This has been implemented in the meantime, shared with the customer, documentation updated here: https://docs.localstack.cloud/aws/elastic-kubernetes-service/#exposing-the-kubernetes-load-balancer-on-custom-ports
