### ISSUE TITLE
bug: created apigateway does not persist 

### ISSUE THREAD

**Issue by nhidtran** [localstack/localstack#6463]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

starting up docker container with `localstack/localstack:latest` persists dynamodb data but does not persist deployed apigateway

I have reviewed:
https://docs.localstack.cloud/localstack/configuration/
https://github.com/localstack/localstack/issues/6398

### Expected Behavior

when I restart my container, I expected the previous deployed resources to exist 

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

```
docker-compose up localstack
sls deploy --stage local [should create a dynamodb table and api gateway]
aws dynamodb --endpoint-url http://localhost:4566 batch-write-item --request-items file://data.json
```
^^ 
`aws dynamodb scan --table-name SiteEng-FeatureFlags-local --endpoint-url http://localhost:4566` data exists yay!
`aws apigateway get-rest-apis --endpoint-url http://localhost:4566` apis exist

```
`docker-compose down`
`docker-compose up localstack`
```
-- at this point, the previous deployed db and seeded table exists but the api does not exist

```
version: "2"
services:
  # https://localstack.cloud/
  localstack:
    container_name: jubilantspork-localstack
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    # https://docs.localstack.cloud/localstack/configuration/
    # https://github.com/localstack/localstack/issues/6398
    environment:
      - SERVICES=s3,sqs,lambda,cloudformation,sts,iam,cloudwatch,apigateway,events,dynamodb
      - AWS_DEFAULT_REGION=us-east-1
      - LAMBDA_EXECUTOR=docker-reuse
      - LAMBDA_REMOTE_DOCKER=false
      - START_WEB=1
      - PERSISTENCE=1
      - DEBUG=1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./volume:/var/lib/localstack
```

### Environment

```markdown
- OS:macOS Monterey 12.4
- LocalStack: latest
```

**Comment by nallwhy** [comment]
I have the same issue with sqs

**Comment by nallwhy** [comment]
Sad...

https://docs.localstack.cloud/localstack/persistence-mechanism/

> In the past we supported a version of persistence – available in the Community version – based on a record-and-replay approach (basically, storing API calls and re-running them on restart), we discontinued this feature with [0.13.1](https://github.com/localstack/localstack/releases/tag/v0.13.1). Therefore, please note that persistence in LocalStack, as currently intended, is a Pro only feature (more on that in the [Technical Details](https://docs.localstack.cloud/localstack/persistence-mechanism/#technical-details) section).

**Comment by thrau** [comment]
@nallwhy As an alternative, you can mount shell scripts into `/docker-entrypoint-initaws.d` that use awslocal to pre-seed localstack with custom aws commands.

**Comment by thrau** [comment]
@nhidtran thanks for reporting, could you help us reproduce the issue by sharing your (or a minimal sample of) your serverless template?

**Comment by whummer** [comment]
Hi @nhidtran, thanks for the update. Please note that certain features, including full support for persistence, are only available in the Pro version of LocalStack. If you'd like to give it a try, you can create a free trial API key in our Web app under https://app.localstack.cloud . Hope that helps - please keep us posted on how it goes.. Thanks!

**Comment by giograno** [comment]
Closing this issue. As mentioned, persistence support is available in the Pro version of LocalStack. However, you can try [Community Cloud Pods](https://docs.localstack.cloud/user-guide/tools/cloud-pods/community/) to somehow manage persistence as a community user. We just released this feature and we would love to get some feedback 🙏
