### ISSUE TITLE
Invoking lambda more than once leads to 500 Internal Server Error

### ISSUE THREAD

**Issue by rohitsud** [localstack/localstack#6464]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The first invocation of a lambda after CreateFunction works fine. Then when the lambda is invoked again I check the existence of the lambda using GetFunction and then localstack returns an Internal Server Error 500.

Looks like [this MR](https://github.com/localstack/localstack/pull/5930) broke the usage of Lambdas with Images on non Pro accounts.

Debug logs say

> 2022-07-16T02:12:27.538 ERROR --- [uest_thread)] lambda_api                 : Exception on /2015-03-31/functions/myfunction [GET]
> Traceback (most recent call last):
>   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/flask/app.py", line 2077, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/flask/app.py", line 1525, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
>     return cors_after_request(app.make_response(f(*args, **kwargs)))
>   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/flask/app.py", line 1523, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/flask/app.py", line 1509, in dispatch_request
>     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
>   File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 1185, in get_function
>     return lookup_function(func, region, request.url)
>   File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 1034, in lookup_function
>     del result["Configuration"]["Layers"]
> KeyError: 'Layers'
> 2022-07-16T02:12:27.544  INFO --- [   asgi_gw_1] localstack.request.aws     : AWS lambda.GetFunction => 500 (500)

### Expected Behavior

Expect the lambda invoke to succeed and run the Lambda

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

>   mock-aws-services:
>     image: localstack/localstack
>     container_name: fake-aws
>     ports:
>       - "5353:5353"
>     environment:
>       - EDGE_PORT=5353
>       - SERVICES=s3,lambda,sts,iam,kms
>       - DEFAULT_REGION=us-west-1
>       - DOCKER_HOST=unix:///var/run/docker.sock
>       - HOST_TMP_FOLDER=${TMPDIR}
>       - DEBUG=1
>     volumes:
>       - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
>       - "/var/run/docker.sock:/var/run/docker.sock"
>       - ../../script/init_mock_aws_services.sh:/docker-entrypoint-initaws.d/init_mock_aws_services.sh #setup s3 buckets
>       - ../../lambda_functions/config/role.json:/docker-entrypoint-initaws.d/lambda_role.json

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    Commands are run through code, cannot post a minimal repro here.

### Environment

```markdown
- OS: OSX 12.4
- LocalStack: 0.14.4.dev and 1.0.1.dev
- Docker 4.10.1
```

**Comment by vmanikes-dd** [comment]
I am running into the same issue as well

**Comment by dfangl** [comment]
Hi, thanks for reporting this! I can confirm this is an issue when the PackageType is set to "Image".
A fix is on the way!

**Comment by dfangl** [comment]
Hi again! A fix for this behavior is currently being deployed, and the new image should be available in 1 hour. If this does not fix your problem completely (even though it should), please do not hesitate to reopen or create a new issue.
Thanks again for reporting!
