### ISSUE TITLE
issue: documentation uses deprecated EndpointResolverFunc type

### ISSUE THREAD

**Issue by sfc-gh-ssudakovich** [localstack/localstack#6467]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Main documentation shows deprecated function (https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/aws#EndpointResolverFunc)

```
  customResolver := aws.EndpointResolverFunc(func(service, region string) (aws.Endpoint, error) {
    if awsEndpoint != "" {
      return aws.Endpoint{
        PartitionID:   "aws",
        URL:           awsEndpoint,
        SigningRegion: awsRegion,
      }, nil
    }
```
But replacing it with what SDK is recommending does not work (see https://stackoverflow.com/questions/72606443/localstack-aws-was-not-able-to-validate-the-provided-access-credentials) and errors out with `AuthFailure: AWS was not able to validate the provided access credentials`.

### Expected Behavior

Documentation should use non-deprecated types/methods to resolve endpoints.

### How are you starting LocalStack?

Custom (please describe below)

### Steps To Reproduce

Starting localstack using `https://github.com/elgohr/go-localstack`. Relevant issue (https://github.com/elgohr/go-localstack/issues/560)

### Environment

```markdown
- OS: MacOS 12.4
- LocalStack: latest
```

**Comment by thrau** [comment]
thanks for reporting @sfc-gh-ssudakovich, i've raised an issue in the docs repository and will close this one
