### ISSUE TITLE
bug: Can't encrypt/decrypt using kms alias

### ISSUE THREAD

**Issue by cam-slyp** [localstack/localstack#6471]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Javascript aws-sdk v2 encounters an error if a key alias is provided as the KeyId parameter of kms.encrypt

### Expected Behavior

Encrypt and decrypt should succeed when called with a KeyId containing the key alias

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

Start latest localstack using default docker-compose.yml

[kms-bug.zip](https://github.com/localstack/localstack/files/9129607/kms-bug.zip)

Run `./createKeyAndAlias.sh`
Run `node index.js`

The error below will occur
![image](https://user-images.githubusercontent.com/98722781/179450608-4b3fd4cc-53d5-43d9-91f1-4c7f065f6df9.png)

### Environment

```markdown
- OS: MacOS 12.4
- LocalStack: localstack/localstack
```

**Comment by cam-slyp** [comment]
Similar issue: https://github.com/localstack/localstack/issues/6193

**Comment by taras-kobernyk-localstack** [comment]
Have a fix ready. But in order to merge it have to fix first an unrelated issue with localstack/moto, that causes CI tests to fail.

**Comment by taras-kobernyk-localstack** [comment]
The fix has been merged. Should become a part of the next release.
