### ISSUE TITLE
bug: Delete and create RDS Serverless Postgres database with same DBClusterIdentifier multi time from the CLI

### ISSUE THREAD

**Issue by parisnakitakejser** [localstack/localstack#6473]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I create an RDS Serverless Aurora Postgres database it works the first time, then I delete it and create it again, in sometimes doesn't allow me to work current with the database before I remove the LocalStack container and recreate all my resources again.

### Expected Behavior

When I use pgAdmin I have to connect to the database one time on a single port eg. 4510, when I remove the RDS and create it again enough times then it randomly makes the connection from pgAdmin not work until I restart and recreate my resources again then it's working.

I have to change the password success based on the new secrets I generated for testing.

### How are you starting LocalStack?

With a `docker run` command

### Steps To Reproduce

Run the cleanup and create commands enough times, many add different resources like ElastiCache and so on with multi ports in use. I have hit the bug 3-4 times in 4 hours.

**Deploy CLI code:**
``` bash
export RDS_PASSWORD=$(awslocal secretsmanager get-random-password --exclude-punctuation | jq -r ".RandomPassword")
export RDS_USERNAME=postgresql

export RDS_CLUSTER=$(awslocal rds create-db-cluster \
    --db-cluster-identifier test-serverless-cluster \
    --engine aurora-postgresql \
    --master-username $RDS_USERNAME \
    --master-user-password $(echo $RDS_PASSWORD) \
    --engine-mode serverless \
    --database-name datatask_cloud)

export RDS_IDENTIFIER=$(echo $RDS_CLUSTER | jq -r ".DBCluster.DBClusterIdentifier")
export RDS_DBNAME=$(echo $RDS_CLUSTER | jq -r ".DBCluster.DatabaseName")
export RDS_ENGINE=$(echo $RDS_CLUSTER | jq -r ".DBCluster.Engine")
export RDS_PORT=$(echo $RDS_CLUSTER | jq -r ".DBCluster.Port")
export RDS_HOST=$(echo $RDS_CLUSTER | jq -r ".DBCluster.Endpoint")
export RDS_ENDPOINT=$(echo $RDS_HOST | awk -v FS=':' '{print $1}')

awslocal secretsmanager create-secret \
    --name DBCredsServerless \
    --secret-string "{
            \"username\": \"$RDS_USERNAME\",
            \"password\": \"$RDS_PASSWORD\",
            \"dbClusterIdentifier\": \"$RDS_IDENTIFIER\",
            \"dbname\": \"$RDS_DBNAME\",
            \"engine\": \"$RDS_ENGINE\",
            \"port\": \"$RDS_PORT\",
            \"host\": \"$RDS_ENDPOINT\"
        }"
```

**Cleanup CLI commands:**
``` bash
awslocal secretsmanager delete-secret --secret-id DBCredsServerless --force-delete-without-recovery
awslocal rds delete-db-cluster \
    --db-cluster-identifier test-serverless-cluster
```

### Environment

```markdown
- OS: macOS 12.4
- LocalStack: 1.0.1.dev
```

**Comment by parisnakitakejser** [comment]
What I discovered when I tested even more on macOS its looks like it's port 4512 there makes me trouble in some way maybe.

maybe the focus should point to that port first? or if I can change the internal LocalStack service port range to get out of port conflicts.

**Comment by parisnakitakejser** [comment]
I'm trying on a different port to be sure it's not a port conflict, what I discovered is my cluster did not always start up.

I discovered the latest Docker images it's the developing images so I was forced to use v. 1.0.0 of the Docker images not, it's pretty sad the dev version is pushed out as the latest Docker images for the community it will create unnecessary bugs :)

This JSON output is my outcome for the setup.

``` json
{
    "DBClusters": [
        {
            "AllocatedStorage": 1,
            "DatabaseName": "datatask_cloud",
            "DBClusterIdentifier": "test-serverless-cluster",
            "Status": "error",
            "Endpoint": "localhost:6000",
            "MultiAZ": false,
            "Engine": "aurora-postgresql",
            "Port": 6000,
            "MasterUsername": "postgresql",
            "StorageEncrypted": false,
            "DBClusterArn": "arn:aws:rds:eu-central-1:000000000000:cluster:test-serverless-cluster",
            "IAMDatabaseAuthenticationEnabled": false,
            "EngineMode": "serverless",
            "TagList": []
        }
    ]
}
```

The new discovered look like its related to Lambda configurations look here

``` json
{
    "DBClusters": [
        {
            "AllocatedStorage": 1,
            "DatabaseName": "datatask_cloud",
            "DBClusterIdentifier": "test-serverless-cluster",
            "Status": "available",
            "Endpoint": "localhost:6000",
            "MultiAZ": false,
            "Engine": "aurora-postgresql",
            "Port": 6000,
            "MasterUsername": "postgresql",
            "StorageEncrypted": false,
            "DBClusterArn": "arn:aws:rds:eu-central-1:000000000000:cluster:test-serverless-cluster",
            "IAMDatabaseAuthenticationEnabled": false,
            "TagList": []
        }
    ]
}
```

The changes I have made are ignoring following environment in my Docker run command.
``` bash
-e DATA_DIR=/tmp/localstack/data
```

So my bootup script will now be

``` bash
docker run -d -it \
    --name localstack \
    -p 4566:4566 \
    -p 6000-6100:6000-6100 \
    -e EXTERNAL_SERVICE_PORTS_START=6000 \
    -e EXTERNAL_SERVICE_PORTS_END=6100 \
    -e DEBUG=1 \
    -e LOCALSTACK_API_KEY=7GyJorUT1p \
    -e AWS_DEFAULT_REGION=eu-central-1 \
    -e LAMBDA_EXECUTOR=docker \
    -e LAMBDA_REMOTE_DOCKER=true \
    -e LAMBDA_REMOVE_CONTAINERS=true \
    -v "/var/run/docker.sock:/var/run/docker.sock" \
    -v "/Users/pnk/Developer/tmp/localstack:/tmp/localstack" \
    localstack/localstack:1.0.0
```

And now my connection working locally but the connection between lambda and rds still won't work, hope it's some small thing, but will share my discovery.

**Comment by steffyP** [comment]
Hi @parisnakitakejser,

thanks for reaching out.
In your description you mention several different things, as it seems. So I have some clarifying questions.

1. Regarding your initial problem: You say that you delete and re-create the RDS database and then you are not able to re-connect to port 4510. 
            a) Could you verify, that the newly re-created database runs on port 4510 in that case? Could you check by running `awslocal rds describe-db-clusters`
            b) Is the state of the db-cluster "available"?
            c) Is there any log output in LocalStack, like a related error message? 


2. When you see the status "error" for a database cluster or instance, there should be some related logs in LocalStack. Could you please share those?

3. Regarding `DATA_DIR` 
    > The changes I have made are ignoring following environment in my Docker run command. 
    - `DATA_DIR` was deprecated with version 1.0. You can [read-up on deprecated envs in the docs](https://docs.localstack.cloud/localstack/configuration/#deprecated). 
    - We have also a [general guideline for migrating to 1.0](https://discuss.localstack.cloud/t/migrating-to-localstack-v1-0/58)

4. Regarding lambda and rds
    > And now my connection working locally but the connection between lambda and rds still won't work, hope it's some small thing, but will share my discovery.
    - Could you share how you are trying to make this connection?
    - Are you aware that there is a env [`LOCALSTACK_HOSTNAME`](https://docs.localstack.cloud/localstack/configuration/#read-only)  that should be used within lambda in order to resolve the endpoint to the LocalStack services correctly?

**Comment by steffyP** [comment]
Hi @parisnakitakejser,

unfortunately we were not able to reproduce your issue, and we haven't heard back from you. 

If you still experience this issue, could you please answer the questions above, and provide the related logs 🙏
