### ISSUE TITLE
feature request: RDS IAM Authentication

### ISSUE THREAD

**Issue by GeorgePals** [localstack/localstack#6480]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

RDS IAM Authentication is currently not supported by LocalStack.

Even if the argument `iam_database_authentication` (at the DB's resource config) is set to `true`, LocalStack ignores it and initializes the database with the default, `false`, value.
```
<IAMDatabaseAuthenticationEnabled>false</IAMDatabaseAuthenticationEnabled>
```

We need this feature to be implemented, in order to enable the token based authentication mechanism against an RDS.

**Comment by wonderslug** [comment]
+1

**Comment by windmgc** [comment]
+1

**Comment by mickjmason** [comment]
+1

**Comment by whummer** [comment]
Thanks for reporting @GeorgePals @wonderslug @windmgc @mickjmason, and apologies for the long delay on this one. We have now pushed a first version of IAM auth for RDS Postgres databases - changes are available in the `latest` Docker image. 

Please note that IAM auth is currently only available for RDS Postgres - IAM auth support for MySQL (and possibly MSSQL) will be added in the near future.

We have yet to update our documentation on it, but would be great if you could already give it a try. Looking forward to getting your feedback! Thanks

**Comment by thrau** [comment]
Closing the issue as fixed. Please open a new issue if problems with the solution surface.

**Comment by whummer** [comment]
Link to our docs for this feature, for reference: https://docs.localstack.cloud/user-guide/aws/rds/#iam-authentication-support
