### ISSUE TITLE
New localstack is not comaptible with python < 3.10

### ISSUE THREAD

**Issue by egobrain** [localstack/localstack#6503]
https://github.com/localstack/localstack/blob/e7efc768a20e75feafe3702a5a6e477a233feff2/localstack/utils/aws/aws_stack.py#L904

```
File "/usr/local/lib/python3.8/site-packages/localstack/services/generic_proxy.py", line 50, in <module>
from localstack.utils.aws import aws_stack
File "/usr/local/lib/python3.8/site-packages/localstack/utils/aws/aws_stack.py", line 904, in <module>
) -> dict[str, str]:
TypeError: 'type' object is not subscriptable
```

Please fix to `Dict[str, str]`

**Comment by thrau** [comment]
hi @egobrain, i've raised a PR anyway to fix the issue. however this is platform code which is only supported for LocalStack 3.10 (since we expect it to only run in our container environment).
