### ISSUE TITLE
bug: DynamoDB Stream not Triggered via NoSQL Workbench PutItem and PartiQL Insert

### ISSUE THREAD

**Issue by jericopulvera** [localstack/localstack#6507]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

DynamoDB Streams is not triggered via NoSQL Workbench PutItem and PartiQL Insert but it works when using CLI put-item.

### Expected Behavior

DynamoDB Streams should work using NoSQL Workbench.

### How are you starting LocalStack?

With a `docker run` command

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    LOCALSTACK_PERSISTENCE=1 docker run --rm -it -p 4566:4566 -p 4510-4559:4510-4559 localstack/localstack:1.0.1

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)
```sh
awslocal dynamodb create-table --table-name BarkTable --attribute-definitions AttributeName=Username,AttributeType=S AttributeName=Timestamp,AttributeType=S --key-schema AttributeName=Username,KeyType=HASH  AttributeName=Timestamp,KeyType=RANGE --provisioned-throughput ReadCapacityUnits=5,WriteCapacityUnits=5 --stream-specification StreamEnabled=true,StreamViewType=NEW_IMAGE
    
awslocal lambda create-function \
    --function-name index \
    --zip-file fileb://Archive.zip \
    --role roleARN \
    --handler index.handler \
    --timeout 5 \
    --runtime nodejs16.x

awslocal lambda create-event-source-mapping \
    --function-name index \
    --event-source <USE THE STREAM GENERATED FROM CREATE TABLE OR BY USING DESCRIBE TABLE>  \
    --batch-size 1 \
    --starting-position TRIM_HORIZON

    awslocal dynamodb put-item --table-name BarkTable --item '{"Username": {"S": "test123"}, "Timestamp": {"S": "11"} }'
```

### Environment

```markdown
- OS: macOS Ventura Public Beta
- LocalStack: 1.0.1
```

### Anything else?

<img width="1206" alt="image" src="https://user-images.githubusercontent.com/23246308/180600538-2f06d6d0-aeda-4069-aac4-90028a28e5c9.png">

l.s.a.lambda_executors triggered using CLI but not on NoSQL Workbench

**Comment by joe4dev** [comment]
Hi @jericopulvera Better late than never 😬  We would love to hear whether this issue persists in our new implementation 👂 . In particular, it would be interesting to know if/whether it's related to ESM persistence or something else.

Check out our new Lambda event source mapping (ESM) implementation in [LocalStack v4](https://blog.localstack.cloud/announcing-localstack-40-general-availability/) offering better functional and non-functional support for ESM 🚀 . The behavioral coverage documentation provides more details for your use case https://docs.localstack.cloud/user-guide/aws/lambda/#lambda-event-source-mappings

Feel free to open another issue or share your feedback if you experience any challenges👂
