### ISSUE TITLE
Creating API Gateway using JUnit Runner.

### ISSUE THREAD

**Issue by emeraldBazaar** [localstack/localstack#653]
I am using the JUnit test runner to create API Gateway. I tried to create a Rest API using the AWS SDK Java API "createRestApi()" as follows:

`AmazonApiGateway client = TestUtils.getClientApiGateway();`
`CreateRestApiResult api = client.createRestApi(new CreateRestApiRequest().withName("testapi"));`
`Assert.assertNotNull(api);`

I also modified the TestUtils file accordingly to support API Gateway. The createRestApi() function returns a valid response. But I don't see the API created on LocalStack when I use the following command ` aws --endpoint-url=http://localhost:4567 apigateway get-rest-apis`

**Comment by whummer** [comment]
Thanks for reporting @emeraldBazaar . Looks like you're creating a `CreateRestApiRequest`, but still need to use the `client` to actually send that request to the service? Can you share a fully self-contained (yet minimal) working example to reproduce the issue? Thanks
