### ISSUE TITLE
Message attributes are not delivered when publishing a message on a SNS topic and receiving it from an SQS queue when using raw message delivery

### ISSUE THREAD

**Issue by ccrolf** [localstack/localstack#655]
Relates to: https://github.com/localstack/localstack/issues/137

For the special case of using raw message delivery, the message attributes are not passed along to SQS. Trivial to reproduce from https://github.com/localstack/localstack/issues/137 after enabling raw message delivery for the subscription.

**Comment by cmpilato** [comment]
Seeing the same thing here.  "Attributes" seem to work fine, but not "MessageAttributes".  Tested with aws command-line and boto3 Python client -- same results.
