### ISSUE TITLE
bug: Can't get SSM secret parameter using localstack.

### ISSUE THREAD

**Issue by carrickkv2** [localstack/localstack#6551]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

This bug has been reported before here. https://github.com/localstack/localstack/issues/3128
Currently, I'm encountering the same issues.
The issue is that creating an SSM secret using the awslocal cli and trying to retrieve the secret using awslocal gives me a (ParameterNotFound) error.

### Expected Behavior

The expected behaviour is that I should successfully retrieve a stored secret instead of getting a (ParameterNotFound) error. 

### How are you starting LocalStack?

Custom (please describe below)

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

Starting local stack from the local stack cli by running `localstack start`

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)
Create secret
`awslocal secretsmanager create-secret --name TestSecret --secret-string "TT"`

Try to get secret
`awslocal ssm get-parameter --name TestSecret`

### Environment

```markdown
- OS:Windows 10 pro 20H2
- Python version - 3.10
- LocalStack version: 1.0.3.dev
- LocalStack: latest
```

### Anything else?

docker logs 
```
2022-07-29T13:36:46.005  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS secretsmanager.CreateSecret => 200

2022-07-29T13:37:28.515  INFO --- [   asgi_gw_1] localstack.request.aws     : AWS ssm.GetParameter => 400 (ParameterNotFound)

```

**Comment by whummer** [comment]
Thanks for reporting @carrickkv2 . Please note that you can retrieve the parameter via the predefined prefix `/aws/reference/secretsmanager/`, like so:

```
$ awslocal secretsmanager create-secret --name TestSecret --secret-string "TT"
{
    "ARN": "arn:aws:secretsmanager:us-east-1:000000000000:secret:TestSecret-16a459",
    "Name": "TestSecret",
    "VersionId": "a5c5c744-0d56-442a-aaf8-629c9b5e748d"
}
$ awslocal ssm get-parameter --name /aws/reference/secretsmanager/TestSecret
{
    "Parameter": {
        "Name": "/aws/reference/secretsmanager/TestSecret",
        "Type": "SecureString",
        "Value": "TT",
        "SourceResult": "{\"name\": \"TestSecret\", \"versionId\": \"a5c5c744-0d56-442a-aaf8-629c9b5e748d\", \"secretString\": \"TT\", \"versionStages\": [\"AWSCURRENT\"], \"createdDate\": 1659342526.0, \"ARN\": \"arn:aws:secretsmanager:us-east-1:000000000000:secret:TestSecret-16a459\"}",
        "LastModifiedDate": 1659342526.0
    }
}
```

This is the expected behavior - we've verified that it works the same way in real AWS. An integration test has been added in #6564 to assert this logic and avoid regressions in the future.

Hope that helps - please let us know if there are any other issues. Thanks!

**Comment by carrickkv2** [comment]
Thank you @whummer.
