### ISSUE TITLE
bug: cloudformation injects ARN instead of name for AWS::KinesisFirehose::DeliveryStream

### ISSUE THREAD

**Issue by qmg-geoff** [localstack/localstack#6570]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am using !Ref to pass the delivery stream name of a delivery stream resource in as an environment variable into a lambda.

When the lambda is executed, the provided value is the ARN of the delivery stream, not the name.

This causes publishing to fail as it needs the name, not the ARN.

!Ref should return the name of the delivery stream but it is returning the ARN.
(https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-ref.html).

### Expected Behavior

I expected !Ref NameOfDeliveryStream to return the name of the delivery stream.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

docker compose up

### Environment

```markdown
- OS: macOS Monterey 12.4
- LocalStack: 1.0.3
```

**Comment by whummer** [comment]
Hi @qmg-geoff , thanks for reporting. This issue should be fixed via #6580 - can you please pull the `latest` Docker image and give it another try? Please keep us posted on how it goes.. Thanks!

**Comment by qmg-geoff** [comment]
> Hi @qmg-geoff , thanks for reporting. This issue should be fixed via #6580 - can you please pull the `latest` Docker image and give it another try? Please keep us posted on how it goes.. Thanks!

Awesome, thanks @whummer, will give it a go today at some point and let you know 👍
