### ISSUE TITLE
issue: Installation failing due to cachetools~=5.0.0 (from localstack) 

### ISSUE THREAD

**Issue by devunixguy** [localstack/localstack#6574]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm trying to install localstack but failing due to the below error. I'm using a RH Linux, is there any OS version dependency for cachetools.

Collecting cachetools~=5.0.0 (from localstack)
  Could not find a version that satisfies the requirement cachetools~=5.0.0 (from localstack) (from versions: 0.0.0, 0.1.0, 0.2.0, 0.3.0, 0.3.1, 0.4.0, 0.5.0, 0.5.1, 0.6.0, 0.7.0, 0.7.1, 0.8.0, 0.8.1, 0.8.2, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.1.6, 2.0.0, 2.0.1, 2.1.0, 3.0.0, 3.1.0, 3.1.1, 4.0.0, 4.1.0, 4.1.1, 4.2.0, 4.2.1, 4.2.2, 4.2.3, 4.2.4)
No matching distribution found for cachetools~=5.0.0 (from localstack)

### How are you starting LocalStack?

Custom (please describe below)

### Steps To Reproduce

localstack installation is failing.

### Environment

```markdown
- OS: redhat linux 7.5
- LocalStack: latest
```

**Comment by dfangl** [comment]
Will close this issue for now, as it seems quite clear where the problem lies. For easily managing multiple python versions, I recommend using pyenv (https://github.com/pyenv/pyenv)
