### ISSUE TITLE
(InternalError) when calling the ListObjectsV2 operation 

### ISSUE THREAD

**Issue by yaminir** [localstack/localstack#6577]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

"An error occurred (InternalError) when calling the ListObjectsV2 operation (reached max retries: 2): We encountered an internal error. Please try again. 

### Expected Behavior

Should list the objects

### How are you starting LocalStack?

Custom (please describe below)

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal s3 mb s3://mybucket

### Environment

```markdown
- OS:
- LocalStack:
```

**Comment by thrau** [comment]
Hi @yaminir, could you please run LocalStack with the environment variable `LS_LOG=trace` and share the full log output here.
If you are really starting LocalStack with `docker run localstack/localstack` then i would also suggest the getting started guide
