### ISSUE TITLE
bug: Flask 2.2.0 released, broken. Localstack should pin to earlier versions.

### ISSUE THREAD

**Issue by AndySemenov** [localstack/localstack#6587]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Starting `localstack start --host` fails due to:
```
...
    from flask_cors import CORS
  File "/mnt/d/PyProjects/proj/venv3.9/lib/python3.9/site-packages/flask_cors/__init__.py", line 11, in <module>
    from .decorator import cross_origin
  File "/mnt/d/PyProjects/proj/venv3.9/lib/python3.9/site-packages/flask_cors/decorator.py", line 13, in <module>
    from flask import make_response, request, current_app
  File "/mnt/d/PyProjects/proj/venv3.9/lib/python3.9/site-packages/flask/__init__.py", line 4, in <module>
    from . import json as json
  File "/mnt/d/PyProjects/proj/venv3.9/lib/python3.9/site-packages/flask/json/__init__.py", line 8, in <module>
    from ..globals import current_app
  File "/mnt/d/PyProjects/proj/venv3.9/lib/python3.9/site-packages/flask/globals.py", line 56, in <module>
    app_ctx: "AppContext" = LocalProxy(  # type: ignore[assignment]
TypeError: __init__() got an unexpected keyword argument 'unbound_message'
```

Brief search in the Net leads to some updates made in Flask 2.2.0 released lately. The traceback shows this has nothing to do with the user of Flask package, it's internal, so Flask 2.2.0 seems broken.

### Expected Behavior

Localstack launches

### How are you starting LocalStack?

With the `localstack` script

#### Installation
`pip install localstack[full]`

(This installation is not covered within the welcome readme, sadly)

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    bin/localstack start --host

### Environment

```markdown
- OS: WSL2, Ubuntu 20.04.4 LTS
- LocalStack: 1.0.3
```

### Anything else?

After downgrading with `pip install -U 'flask<2.2.0'` (which resulted in Flask==2.1.3) localstack command stopped failing at the very beginning of the run.

**Comment by whummer** [comment]
Thanks for the pointer @AndySemenov ! This has been fixed in #6593, and will go out with our next release of the `localstack` package on pypi (next patch version likely to happen by mid next week). Thanks
