### ISSUE TITLE
bug: no logs written to the new filesystem in /var/lib/localstack/logs

### ISSUE THREAD

**Issue by mbalc** [localstack/localstack#6589]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I had problems with setting up an automated init script for S3 under /docker-entrypoint-initaws.d/ . While trying to figure out why it's not working, I viewed the /bin/docker-entrypoint.sh file in this file and saw the implementation of how this folder is handled.

From what I understand, you're checking if a `Ready.` line gets written into a specific log file.

However, I noticed that (at least on my setup) - no log files are written

### Expected Behavior

the `ls /var/lib/localstack/logs/ -a` should show any files getting created and written to after starting localstack

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

   docker-compose.yaml config:
   ```
...
version: "3.7"
services:
[...SNIP...]
  localstack:
    build:
      context: ./localstack/
    container_name: ${APP_NAME}-localstack
    ports:
      - "4563-4599:4563-4599"
    environment:
      - SERVICES=s3
      - DEBUG=${DEBUG- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DISABLE_CORS_CHECKS=1 # dev only
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - localstack_data:/var/lib/localstack
  [...SNIP...]
volumes:
  localstack_data:
  [...SNIP...]

   ```
- `docker-compose up`
- `docker-compose exec -it localstack bash`
- (inside) `ls /var/lib/localstack/logs/`
[[[the folder is totally empty - even when I check after running some calls against the S3 service (see the log below - that's what I saw in docker-compose log when trying to upload one file to S3, failing because a bucket doesn't exist, bucket not existing because my entrypoint scripts don't start), the logs folder is still empty - and I suspect this is why my entrypoint scripts aren't getting run]]]

```
APP-localstack  | SERVICES variable is ignored if EAGER_SERVICE_LOADING=0.
APP-localstack  | 
APP-localstack  |      __                     _______ __             __
APP-localstack  |     / /   ____  _________ _/ / ___// /_____ ______/ /__
APP-localstack  |    / /   / __ \/ ___/ __ `/ /\__ \/ __/ __ `/ ___/ //_/
APP-localstack  |   / /___/ /_/ / /__/ /_/ / /___/ / /_/ /_/ / /__/ ,<
APP-localstack  |  /_____/\____/\___/\__,_/_//____/\__/\__,_/\___/_/|_|
APP-localstack  | 
APP-localstack  |  💻 LocalStack CLI 1.0.3
APP-localstack  | 
APP-localstack  | [19:07:07] starting LocalStack in host mode 💻                 localstack.py:138
APP-localstack  | ──────────────── LocalStack Runtime Log (press CTRL-C to quit) ─────────────────
APP-localstack  | 
APP-localstack  | LocalStack version: 1.0.3
APP-localstack  | LocalStack build date: 2022-07-30
APP-localstack  | LocalStack build git hash: 055fcceb
APP-localstack  | 
APP-localstack  | 2022-08-03T19:07:11.145  INFO --- [  MainThread] localstack.utils.bootstrap : Execution of "prepare_installation" took 611.03ms
APP-localstack  | 2022-08-03T19:07:12.062  WARN --- [  Thread-108] hypercorn.error            : ASGI Framework Lifespan error, continuing without Lifespan support
APP-localstack  | 2022-08-03T19:07:12.062  WARN --- [  Thread-108] hypercorn.error            : ASGI Framework Lifespan error, continuing without Lifespan support
APP-localstack  | 2022-08-03T19:07:12.064  INFO --- [  Thread-108] hypercorn.error            : Running on https://0.0.0.0:4566 (CTRL + C to quit)
APP-localstack  | 2022-08-03T19:07:12.064  INFO --- [  Thread-108] hypercorn.error            : Running on https://0.0.0.0:4566 (CTRL + C to quit)
APP-localstack  | 2022-08-03T19:07:12.231  INFO --- [  MainThread] localstack.utils.bootstrap : Execution of "start_runtime_components" took 1085.73ms
APP-localstack  | Ready.
APP-localstack  | 2022-08-03T19:09:54.261  INFO --- [   asgi_gw_0] localstack.request.http    : OPTIONS /my-bucket/my-bucket/items/[REDACTED] => 200
APP-localstack  | 2022-08-03T19:09:54.632  INFO --- [  Thread-124] l.services.motoserver      : starting moto server on http://0.0.0.0:36511
APP-localstack  | 2022-08-03T19:09:54.633  INFO --- [   asgi_gw_0] localstack.services.infra  : Starting mock S3 service on http port 4566 ...
APP-localstack  | 2022-08-03T19:09:54.950  INFO --- [   asgi_gw_0] localstack.utils.bootstrap : Execution of "require" took 619.03ms
APP-localstack  | 2022-08-03T19:09:54.981  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS s3.CreateMultipartUpload => 404 (NoSuchBucket)

```

### Environment

```markdown
- OS: Docker v 20.10.17 under Arch Linux (rolling) on kernel: Linux 5.18.14-zen1-1-zen
- LocalStack: 1.0.3
- docker-compose: 2.6.1
```

**Comment by thrau** [comment]
hi @mbalc!

i'm not able to reproduce this. both with a bind mound and a named volume i can see logs when i bash into the container. see the attached screenshot.

could you please share your entire volume configuration? is it possible the named volume is read only somehow?

![image](https://user-images.githubusercontent.com/3996682/182698236-92b57f5a-c441-4b88-9e6d-f8172118494d.png)

**Comment by mbalc** [comment]
The volume config is just the thing I provided - so just a single yaml `localstack_data:` line, so that a named volume is created

I created a clean workspace with all the setup and I think I managed to track down the issue - we were using a custom Dockerfile that looks like this:

```
from localstack/localstack:1.0.3

VOLUME /tmp/localstack

# TODO: this doesn't get started by localstack - https://github.com/localstack/localstack/issues/6589
COPY scripts/init_bucket.sh /docker-entrypoint-initaws.d/1-autodl.sh

ENTRYPOINT ./bin/localstack start --host
```

and it looks like we just used an outdated entrypoint which neither bound the logs to be written to the /varlib/localstack/logs path, nor actually listened for the logs to trigger the hook

here's the playground that I used to write this comment: https://github.com/mbalc/localstack-playground

I'm wondering if there's anything left to address about this ticket - I don't remember why I added that ENTRYPOINT line 9 months ago to our Dockerfile; I remember that we tried to initialize our mock S3 by initializing the recorded_calls json ,but it's not there in 1.0 as far as I can see

maybe this issue itself will help someone in my situation

there's probably not a whole lot of things possible to do in the codebase; maybe you could prevent or warn people somehow about calling the binary directly within docker context... or sth, idk - but from my side, feel free to close this issue

**Comment by thrau** [comment]
ok, thanks for the insights @mbalc. It makes sense, our [entry point script](https://github.com/localstack/localstack/blob/master/bin/docker-entrypoint.sh) is fairly involved, so circumventing that will likely break things. I agree though that we could start making it easier to customize LocalStack images and also make the unit scripts more user friendly. Thanks for the feedback!
