### ISSUE TITLE
PRO- Unable to invoke lambda

### ISSUE THREAD

**Issue by ashameem123** [localstack/localstack#6590]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Keep getting error , 

![image](https://user-images.githubusercontent.com/54183749/182698771-23749789-d557-4ec0-b887-0c67952333b5.png)

Note: Before docker pull, I was successfully able to trigger the lambda without any issue.

### Expected Behavior

Should be able to trigger lambda with no exceptions.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

docker-compose up -d

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

aws --endpoint-url=http://localhost:4566 lambda create-function --function-name myDemoFunction1 --runtime java11 --handler com.myfunctions.MyDemoClass --role arn:aws:iam::0000000:role/abc --zip-file fileb://demoFunction.jar --environment Variables="{PROFILE=DEFAULT,AWS_REGION=us-east-1}"
TIMEOUT 2

aws --endpoint-url=http://localhost:4566 lambda invoke --function-name myDemoFunction1 response.json

[localstack-jenkins-demo-1.0-SNAPSHOT.jar.zip](https://github.com/localstack/localstack/files/9254624/localstack-jenkins-demo-1.0-SNAPSHOT.jar.zip)

### Environment

```markdown
- OS:windows
- LocalStack:LocalStack version: 1.0.4.dev
```

**Comment by alexrashed** [comment]
Hi @ashameem123!
Thanks for the report.
In your report you are referring to two different log lines:
- ```
   error while loading service azure: plugin localstack.aws.provider:azure:pro is disabled
   ```
   We will address this right away, however, it shouldn't have any impact on your lambda use-case.
- ```
   Empty event body specified for invocation of Lambda "<lambda-arn>"
   ```
   This is just an info log that your invocation does not have a request body (i.e. you are not sending any payload with your lambda invoke command).

Do you experience any functional issues when running your Lambda function?
Thanks!

**Comment by ashameem123** [comment]
Yes, My lambda isn’t getting invoked. Not getting the expected output.

**Comment by alexrashed** [comment]
This issue was a combination of multiple issues:
- The error log was misleading (this has been fixed by now).
- The lambda output is only logged on `DEBUG` level.
- The upgrade mentioned as pre-v1 to v1.

These issues have been resolved, therefore I'll close the issue for now.
