### ISSUE TITLE
bug: WS default route not working 

### ISSUE THREAD

**Issue by kingster307** [localstack/localstack#6615]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

websocket default route not being invoked when no route matches 

### Expected Behavior

$default route should be invoked when no other route keys match 

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

[repo here](https://github.com/kingster307/localstack_ws_bugs/tree/default_route_bug)

### Environment

```markdown
- OS: mac m1
- LocalStack: 1.0.3
```

### Anything else?

tested against AWS & default route works as expected

**Comment by buddhics** [comment]
Hi @whummer and @kingster307 ,
I would like to work on this.

**Comment by kingster307** [comment]
Please see updated reproducer [here](https://github.com/kingster307/localstack_ws_bugs/tree/localstack_ws_bugs_generic)

from AWS docs
`API Gateway calls the $default route if the route selection expression cannot be evaluated against the message or if no matching route is found.`

route selection expression cannot be evaluated against the message - this works 
no matching route is found - this does not work

**Comment by calvernaz** [comment]
Hi @kingster307  the "This no matching route is found" also works.

<img width="1283" alt="Screenshot 2023-11-08 at 20 57 43" src="https://github.com/localstack/localstack/assets/1269712/174bef25-e0e9-4325-a953-648a9a6d9b9c">

**Comment by kingster307** [comment]
@calvernaz both the default btns [should be returning this](https://github.com/kingster307/localstack_ws_bugs/blob/localstack_ws_bugs_generic/ws_api_route_handler_lambda/lambda_function.py#L27)

**Comment by paulrobello** [comment]
This issue is valid. The route key should contain "$default" rather than the requested route simply being passed through.
If the lambda needs to know what the requested route was, it can parse the body itself.

**Comment by cabeaulac** [comment]
Hey @calvernaz . I understand this isn't quite working per the AWS docs specification yet. Let me know if you want any additional assistance here. More AWS actual output coming from users here soon...

**Comment by cabeaulac** [comment]
reopening...

**Comment by calvernaz** [comment]
Hi all, gotcha my misunderstanding. The integration is being called, the integration bound to the default route however the bug and my misunderstanding is the route is the original one and not the default. Will fix it 👌

**Comment by kingster307** [comment]
tested against AWS....when route Key doesn't match a defined route then lambda gets invoked with routeKey of $default 

![Screenshot 2023-11-14 at 3 30 59 PM](https://github.com/localstack/localstack/assets/33669832/72cd1d24-9302-4a1f-92d0-0e430845c620)

**Comment by calvernaz** [comment]
Hi @kingster307 I have a fix in place just trying to get around some issues with the pipeline. Will ping back when it gets merged 👍

**Comment by calvernaz** [comment]
Hi @kingster307 I've merged the fix, would you mind trying the latest version?

**Comment by kingster307** [comment]
@calvernaz Just tested with latest, not seeing any changes 
![image](https://github.com/localstack/localstack/assets/33669832/b66b1b2f-8056-4bdf-a673-94c8c85bdcde)

**Comment by calvernaz** [comment]
Hi @kingster307 will ping the team to have an idea when a new image will be available

**Comment by calvernaz** [comment]
Hi @kingster307 there were some issues with the pipeline today, can you check if the image you have has the SHA - e53573ac5685e20e4956e15fedf4868e928a120210fae4aa945186c8b8796cc1 for localstack-pro ?

**Comment by kingster307** [comment]
@calvernaz Just flushed cache & re pulled image, sha matched the above, test came back successful! Appreciate all the work on this!
