### ISSUE TITLE
bug: cannot PutBucketOwnershipControls on s3 bucket

### ISSUE THREAD

**Issue by shonigbaum** [localstack/localstack#6634]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I start localstack in docker, create a s3 bucket and want to put bucket ownership controls on this s3 bucket I get the following message:

`An error occurred (IllegalLocationConstraintException) when calling the PutBucketOwnershipControls operation: The unspecified location constraint is incompatible for the region specific endpoint this request was sent to.`

When I do this directly on AWS via aws cli it works fine.

### Expected Behavior

PutBucketOwnershipControls should work properly.

### How are you starting LocalStack?

With a `docker run` command

### Steps To Reproduce

Run docker:
`docker run --name localstack_main --rm -it -e HOSTNAME_EXTERNAL="localhost" -e DISABLE_EVENTS="1" -p 4566:4566 -p 8080-8081:8080-8081 "localstack/localstack:1.0.3"`

Create s3 bucket:
`aws s3api create-bucket --endpoint http://localhost:4566 --region eu-central-1 --bucket "hallo" --create-bucket-configuration "LocationConstraint=eu-central-1"`

Put bucket ownership controls on this s3 bucket:
`aws s3api put-bucket-ownership-controls --bucket hallo --ownership-controls "Rules=[{ObjectOwnership=BucketOwnerEnforced}]"  --endpoint http://localhost:4566 --region eu-central-1` 

### Environment

```markdown
- OS: Ubuntu 20.04 (WSL2)
- LocalStack: 1.0.3
```

**Comment by pinzon** [comment]
The solution has been integrated to the latest release. Thanks for the report!
