### ISSUE TITLE
How can I create buckets in Localstack S3 for multiple regions

### ISSUE THREAD

**Issue by bhaskar20001** [localstack/localstack#664]
I'm not able to create bucket with same name across regions.

See the commands executed by me.

$ aws --endpoint-url=http://localhost:4572 --region=us-east-1 s3 mb s3://test-bucket
make_bucket: test-bucket
$ aws --endpoint-url=http://localhost:4572 s3 ls
2006-02-03 22:15:09 test-bucket
$ aws --endpoint-url=http://localhost:4572 --region=us-west-2 s3 mb s3://test-bucket
make_bucket failed: s3://test-bucket An error occurred (BucketAlreadyExists) when calling the CreateBucket operation: The requested bucket name is not available. The bucket namespace is shared by all users of the system. Please select a different name and try again

How can I avoid the above error?

**Comment by kkumler** [comment]
@bhaskar20001 If I may ask, is this just something that is coming up in a testing scenario? S3 itself [requires bucket names to be unique across all regions](https://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html#bucketnamingrules). I would think it should respond with that error unless the first bucket is deleted.

> A bucket name must be unique across all existing bucket names in Amazon S3. We recommend that all bucket names comply with DNS naming conventions.

**Comment by whummer** [comment]
Good catch @kkumler , thanks. Although LocalStack currently doesn't have multi-region support, the error message above reflects the same behavior as in AWS (bucket names are globally unique).

Going to close this issue - please choose unique names for different buckets @bhaskar20001 . Thanks

**Comment by bhaskar20001** [comment]
@kkumler Thanks for the response.
Thanks @whummer for letting me know that Localstack doesn't have support for multi-regions.
