### ISSUE TITLE
ImportError deploying Chalice app with dependencies

### ISSUE THREAD

**Issue by dhay** [localstack/localstack#6642]
I'm trying to deploy a Chalice app using `chalice-local` to my localstack instance.  However, when I attempt to run the `deploy` step, I get the following error:
```
botocore.exceptions.ClientError: An error occurred (InternalFailure) when calling the CreateFunction operation: Unable to get handler function from lambda code: cannot import name 'containers' from 'dependency_injector' (/tmp/function.zipfile.ec482df9/dependency_injector/__init__.py)
```
On the localstack size, I see this error:
```
localstack_myapp  |   File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 613, in _do_exec_lambda_code
localstack_myapp  |     handler_module = load_source(lambda_id, lambda_file)
localstack_myapp  |   File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 585, in load_source
localstack_myapp  |     return importlib.machinery.SourceFileLoader(name, file).load_module()
localstack_myapp  |   File "<frozen importlib._bootstrap_external>", line 548, in _check_name_wrapper
localstack_myapp  |   File "<frozen importlib._bootstrap_external>", line 1063, in load_module
localstack_myapp  |   File "<frozen importlib._bootstrap_external>", line 888, in load_module
localstack_myapp  |   File "<frozen importlib._bootstrap>", line 290, in _load_module_shim
localstack_myapp  |   File "<frozen importlib._bootstrap>", line 719, in _load
localstack_myapp  |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
localstack_myapp  |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
localstack_myapp  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
localstack_myapp  |   File "/var/lib/localstack/tmp/lambda_script_l_2a28ec80.py", line 10, in <module>
localstack_myapp  |     from chalicelib.app_container import app_container
localstack_myapp  |   File "/tmp/function.zipfile.ec482df9/chalicelib/app_container.py", line 3, in <module>
localstack_myapp  |     from dependency_injector import containers, providers
localstack_myapp  | ImportError: cannot import name 'containers' from 'dependency_injector' (/tmp/function.zipfile.ec482df9/dependency_injector/__init__.py)
localstack_myapp  |
localstack_myapp  | 2022-08-10T14:06:06.625  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS lambda.CreateFunction => 400 (InternalFailure)
```
I've installed all the dependencies and can run the service locally using `chalice-local local`.

Is there something about the packaging or process that isn't pulling in the Python dependencies?  I have a `requirements.txt` file  describing the dependencies I need.  I'm also using Python 3.9.12 locally.  From what I understand, Lambda/Chalice should just use the appropriate Python version to support that.

I'm sure I'm missing something obvious, but I can't see what it is.

**Comment by dfangl** [comment]
Hi @dhay !
I transferred this issue here since it is not an issue with the docs as much as with the core product.
Can you please mount your docker socket into the LocalStack container / check if you set `LAMBDA_EXECUTOR=docker`? This seems to be an issue with the local executor, which is not recommended for everyday use.

**Comment by dhay** [comment]
I added the `LAMBDA_EXECUTOR=docker` to my docker-compose.yml file.  I'm not finding any documentation for how to "mount your docker socket into the LocalStack container".  Can you point me at some instructions on how to do this?

**Comment by dfangl** [comment]
Great to see that! Will close this issue now.
You can also always look at our example docker compose file here: https://github.com/localstack/localstack/blob/8f157e56ba9808945e445950b749a3a58d6e953f/docker-compose.yml#L21 (the line with the docker socket should be highlighted).
