### ISSUE TITLE
bug: LocalStack lambda does not honor 4kb env variable limit

### ISSUE THREAD

**Issue by ReviakinAleksey** [localstack/localstack#6643]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I deployed lambda function with extremly big environment variable value to LocalStack it was deployed and I was able to run function with this varible.
But when I try to deploy same code to AWS it is fail with: `InvalidParameterValueException: Lambda was unable to configure your environment variables because the environment variables you have provided exceeded the 4KB limit`.

### Expected Behavior

Deploymnet such configuration to LocalStack should fail same as on real AWS.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

TBD later

### Environment

```markdown
- OS:
- LocalStack: LocalStack version: 1.0.2.dev
```

**Comment by sharmadhiraj86** [comment]
Can I contribute to this issue? If yes, can you please assign me this issue? @whummer @thrau @ReviakinAleksey @localstack-bot @olleolleolle

**Comment by mindriot101** [comment]
@sharmadhiraj86 I had started a branch over on [my fork](https://github.com/mindriot101/localstack/tree/feat/enforce-lambda-envar-size-limit) but I am happy if you want to take this issue? I should have announced that I was working on it sooner, sorry.

**Comment by whummer** [comment]
Hi @ReviakinAleksey , thanks for reporting. This should be fixed via https://github.com/localstack/localstack/pull/6862 - can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists.. Thanks!

**Comment by ayushpaharia** [comment]
@HarshCasper I'm interested in working on this issue

**Comment by HarshCasper** [comment]
Hi @ayushpaharia — As @whummer mentioned, it has been fixed in a latest release. Can you try replicating if this issue still exists by pulling the latest image and try to check if LocalStack Lambda honours the 4 KB env variable limit? We would count issue triaging for Hacktoberfest as well, and we would appreciate any contributions :)

**Comment by ayushpaharia** [comment]
Hey @HarshCasper need some help getting this setup correctly.
Can you point me to some places to get this setup on ubuntu 20.04. Having issues with the config

**Comment by simonrw** [comment]
@ReviakinAleksey I'm going to close this issue for now if that's ok. If it persists, please feel free to add further comments or open another issue. Thanks for reporting!
