### ISSUE TITLE
Improve AppSync with directives

### ISSUE THREAD

**Issue by nr-96** [localstack/localstack#6649]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

As of now, it throws out an error in the `Serverless` deployment when using `@aws_lambda` in the `.graphql` schema

```
type ExampleType @aws_lambda {
   ...
}
```

### Anything else?

References: 
* [Multi-Authorization with AWS Lambda](https://aws.amazon.com/blogs/mobile/appsync-lambda-auth/)
* [[AWS AppSync-provided directives](https://docs.amplify.aws/cli-legacy/graphql-transformer/directives/#aws-appsync-provided-directives)](https://docs.amplify.aws/cli-legacy/graphql-transformer/directives/#aws-appsync-provided-directives)

**Comment by whummer** [comment]
Thanks for reporting @nr-96 - we've pushed a few more changes, and this issue should be (hopefully) fixed in the meantime. Can you please pull the `latest` Docker image and give it another try? Please keep us posted on how it goes.. Thanks!

**Comment by nr-96** [comment]
Hey @whummer,
The improvement is working, thank you!
