### ISSUE TITLE
bug: S3 Lifecycle not showing expiration header 

### ISSUE THREAD

**Issue by FelipeNathan** [localstack/localstack#6654]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm configuring the S3 bucket to have a lifecycle, everything works fine, but when I get the object, the header `Expiration` is not showing

### Expected Behavior

According to the documentation, if the bucket have a `lifecycle configuration` enabled, the header `expiration` should appear in the response

Executing the command
```bash
$ awslocal s3api get-object help
```

We get the documentation of `get-object` command and in the `OUTPUT` section we have:
>Expiration -> (string)
>          If the object expiration is configured (see PUT  Bucket  lifecycle),
>          the  response  includes this header. It includes the expiry-date and
>          rule-id key-value pairs providing object expiration information. The
>          value of the rule-id is URL-encoded.

### How are you starting LocalStack?

With a docker-compose file

#### Created the bucket-lifecycle.json
```json
{
  "Rules": [
    {
      "ID": "My Rule ID",
      "Status": "Enabled",
      "Expiration": {
        "Days": 1
      },
      "NoncurrentVersionExpiration": {
        "NoncurrentDays": 1
      }
    }
  ]
}
```

####  Command for create the lifecycle configuration on a existing bucket
```bash
$ awslocal s3api put-bucket-lifecycle-configuration --bucket my-bucket --lifecycle-configuration file://bucket-lifecycle.json
```

#### Validate the configuration
```bash
$ awslocal s3api get-bucket-lifecycle-configuration --bucket my-bucket

output:
{
    "Rules": [
        {
            "Expiration": {
                "Days": 1
            },
            "ID": "My Rule ID",
            "Status": "Enabled",
            "NoncurrentVersionExpiration": {
                "NoncurrentDays": 1
            }
        }
    ]
}
```

#### Uploaded an object:
```bash
$ awslocal s3api put-object --bucket my-bucket --key teste.json --body bucket-lifecycle.json  --content-type application/json

output:
{
    "ETag": "\"eb702ecb4e41b09ca62934217d5f13af\""
}
```

#### Fetch the object
```bash
$ awslocal s3api get-object --bucket my-bucket --key teste.json bucket-lifecycle.json 

output:
{
    "AcceptRanges": "bytes",
    "LastModified": "2022-08-11T13:39:11+00:00",
    "ContentLength": 287,
    "ETag": "\"eb702ecb4e41b09ca62934217d5f13af\"",
    "VersionId": "null",
    "ContentLanguage": "en-US",
    "ContentType": "application/json",
    "Metadata": {}
}
```

### Environment

```markdown
- OS: MacOS Monterey
- LocalStack: 1.0.3
```

**Comment by octogene** [comment]
Any news on this issue, it’s kind of a blocker on my project ? If i can get some pointers as to where the fix should be made (in moto project ?) i could try to create a PR for this issue.

**Comment by luiznaac** [comment]
> Any news on this issue, it’s kind of a blocker on my project ? If i can get some pointers as to where the fix should be made (in moto project ?) i could try to create a PR for this issue.

@octogene working alongside with @FelipeNathan, we found a workaround by using `minio` instead of `localstack` for S3 in our project - https://registry.hub.docker.com/r/minio/minio.

**Comment by dgrandemange** [comment]
Same behavior observed this day with latest localstack 2.1.1.dev image : the expiration header does not show on GET/HEAD of an object subject to expiration given a bucket injected with appropriate lifecycle rules.
Any news on this ?

**Comment by bentsku** [comment]
Hi! It's currently in our backlog, I'll be taking a look and asserting how much work this will be, and I'll be coming back to you. Thanks!

**Comment by ccatterina** [comment]
Hi!
Looking at the code it seems to me that the problem is that now localstack store the lifecycle configuration without write it to moto bucket object and so the expiration logic is not applied by moto.


There is a comment in the localstack `put_bucket_lifecycle_configuration` that explain why it was not used the moto implementation of `put_bucket_lifecycle_configuration`.

https://github.com/localstack/localstack/blob/a5e443bcbf480f621031d9306f35ddfad761c7b2/localstack/services/s3/provider.py#L858-L874


I've just opened a PR into moto project  https://github.com/getmoto/moto/pull/6439 that should solve this issue allowing multiple Transitions/NonCurrentVersionTransitions in lifecycle configuration.

if it's okay with you I could also open a PR to make localstack use the moto `put_bucket_lifecycle_configuration`

**Comment by bentsku** [comment]
Sorry for the delay in coming back, but there's now a draft PR to implement this feature! This PR will only concern returning the `Expiration` header like it was asked, and won't delete the objects or transitions them yet, as managing all Lifecycle can be quite some work. But this is a good base to start on, and we can extend and iterate over it!

Thanks again for patience.

**Comment by bentsku** [comment]
The PR has now been merged, and should be part of `localstack/localstack:latest`. You can pull it and give it a try! Don't hesitate if you have any feedback.
