### ISSUE TITLE
API as an Amazon Kinesis Proxy

### ISSUE THREAD

**Issue by emeraldBazaar** [localstack/localstack#666]
Has anyone managed to create an API as a Kinesis Proxy working(https://docs.aws.amazon.com/apigateway/latest/developerguide/integrating-api-with-aws-services-kinesis.html)? 

I tried to implement the listStreams API using the CLI commands but I get the following error:
`{"message": "API Gateway integration type \"AWS\" for method \"GET\" not yet implemented"}`

Any help would be appreciated!

**Comment by steingold** [comment]
I encounter the same issue.
did you manage to work around it?

**Comment by el-cid** [comment]
The same issue happens when you specify the api-gateway put-integration --type parameter set to AWS. Any news about this issue?

**Comment by whummer** [comment]
Thanks for reporting @emeraldBazaar @steingold @el-cid . This should be fixed in #1760 - please give it a try with the latest version and report here if the problem persists. Thanks
