### ISSUE TITLE
bug: Can't run Python Pillow in Localstack

### ISSUE THREAD

**Issue by nathanwebsterdotme** [localstack/localstack#6663]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```
payload(\n                {"message": f"failed processing: {str(e)}"}, 502\n            )\n\n\ndef lambda_handler(event, context):\n    logger.debug(event)\n    image_processor = ImageProcessor()\n    return image_processor.main(event)\n' Traceback (most recent call last):
localstack    |   File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 595, in _do_exec_lambda_code
localstack    |     handler_module = load_source(lambda_id, lambda_file)
localstack    |   File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 567, in load_source
localstack    |     return importlib.machinery.SourceFileLoader(name, file).load_module()
localstack    |   File "<frozen importlib._bootstrap_external>", line 548, in _check_name_wrapper
localstack    |   File "<frozen importlib._bootstrap_external>", line 1063, in load_module
localstack    |   File "<frozen importlib._bootstrap_external>", line 888, in load_module
localstack    |   File "<frozen importlib._bootstrap>", line 290, in _load_module_shim
localstack    |   File "<frozen importlib._bootstrap>", line 719, in _load
localstack    |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
localstack    |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
localstack    |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
localstack    |   File "/var/lib/localstack/tmp/lambda_script_l_0dae9970.py", line 7, in <module>
localstack    |     from PIL import Image
localstack    |   File "/var/lib/localstack/tmp/zipfile.f99a9e5d/PIL/Image.py", line 100, in <module>
localstack    |     from . import _imaging as core
localstack    | ImportError: cannot import name '_imaging' from 'PIL' (/var/lib/localstack/tmp/zipfile.f99a9e5d/PIL/__init__.py)
```

Using a lambda layer as follows, this works: 

```
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      ...
      Layers:
        - arn:aws:lambda:eu-west-1:770693421928:layer:Klayers-p38-Pillow:4
```

I've downloaded this specific layer, unzipped it, and added this into my local lambda function directory, but the error above is still thrown when deploying to localstack, even though the layer python code is natively a part of the zip file.

### Expected Behavior

It should be possible to run my Python application that uses Pillow when bundling the lambda layer into the native lamba directory

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker-compose up -d

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    sam build && samlocal deploy

(also tried `sam build --use-container --build-image Function1=amazon/aws-sam-cli-build-image-python3.8 && samlocal deploy` )

### Environment

```markdown
- OS: Mac OS
- LocalStack: latest
```

### Anything else?

This works in AWS with a lambda layer, just not in local stack.  

I don't want to have to upgrade to localstack pro to make this work, there's no budget for that.

**Comment by pinzon** [comment]
Hi @nathanwebsterdotme, **Lambda Layers** is a PRO feature. [Here's](https://docs.localstack.cloud/aws/lambda/#lambda-layers) more information about it.
