### ISSUE TITLE
`ObjectCreated:CompleteMultipartUpload` is fired on the creation of a multipart upload

### ISSUE THREAD

**Issue by peter-lockhart-pub** [localstack/localstack#6676]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When interacting with `localstack` using the AWS node SDK v3, when starting a new multipart upload
```
const command = new CreateMultipartUploadCommand(multiPartParams);
await client.send(command);
```

the `ObjectCreated:CompleteMultipartUpload` event is fired. Once the multipart upload has been completed/assembled, another `ObjectCreated:CompleteMultipartUpload` event is fired.

### Expected Behavior

This is at odds with how it works in S3 where `ObjectCreated:CompleteMultipartUpload` is only fired at the point of the multipart upload being completed.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

docker-compose.yml
```
localstack:
    image: localstack/localstack:1.0.4
    environment:
      - SERVICES=s3,sqs
      - DEBUG=1
    ports:
      - 4566:4566
```

infra.tf
```
terraform {
  required_version = "= 1.2.1"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "= 3.62.0"
    }
  }
}

resource "aws_s3_bucket" "object-store" {
  bucket              = "object-store"
  acceleration_status = "Enabled"
  force_destroy       = true
}

resource "aws_s3_bucket_notification" "object-store-bucket-notification" {
  bucket = aws_s3_bucket.object-store.id
  queue {
    queue_arn = aws_sqs_queue.object-store-s3-events.arn
    events    = ["s3:ObjectCreated:*"]
  }
}

resource "aws_sqs_queue" "object-store-s3-events" {
  name = "object-store-s3-events"
}
```

Our application interacting with S3 is written in node, using `"@aws-sdk/client-s3": "^3.100.0"`

Initiate a multipart upload and do not complete it:
```
const command = new CreateMultipartUploadCommand(multiPartParams);
await client.send(command);
```

and observe a `ObjectCreated:CompleteMultipartUpload` event is added to the SQS queue

### Environment

```markdown
- OS: Monterey 12.5
- LocalStack: 1.0.4
- @aws-sdk/client-s3: ^3.100.0
```

### Anything else?

One of our engineers successfully patched the issue by adding

```
# Don't want to send notifications on creation of multipart uploads
        if ("CreateMultipartUpload" in query):
            return False
```

to [def is_query_allowable(method, query):](https://github.com/localstack/localstack/blob/e4719cbfa03594ddb505eff6a9e7c7e036d74bf6/localstack/services/s3/s3_listener.py#L1318 ) in `services/s3/s3_listener.py`

But we aren't sure if that is the correct place for the fix or if that is the right fix at all, and would prefer someone more familiar with the project look into it.  Many thanks.

**Comment by bentsku** [comment]
Hi @peter-lockhart-pub and thanks for your report.

We've done a great amount of work regarding S3, and this issue is now fixed in our latest version. Could you give it a try by pulling either `latest` or `localstack/localstack:2.1.0`? Thanks!

**Comment by bentsku** [comment]
I'll close the issue as it should be fixed in our latest version. Feel free to reopen if you still encounter the issue. Thanks!
