### ISSUE TITLE
bug: boto3 describe_user_pool response is missing keys

### ISSUE THREAD

**Issue by maciejstromich** [localstack/localstack#6678]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when calling 

```
import boto3
client = boto3.client('cognito-idp', region_name='us-east-1')
client.describe_user_pool(UserPoolId='userpoolid')
```
returned dict should return EstimatedNumberOfUsers in the response. currently it's missing

### Expected Behavior

Cognito responses should return all items listed in the boto3 docs https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/cognito-idp.html#CognitoIdentityProvider.Client.describe_user_pool

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

Take the example docker-compose.yml entry from the docs and run:
```
docker-compose up -d localstack
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)
Create User Pool
```
aws --endpoint-url http://localhost:4566 cognito-idp create-user-pool \
    --pool-name janus \
    --policies PasswordPolicy={MinimumLength=6} \
    --auto-verified-attributes email \
    --username-attributes email \
    --admin-create-user-config AllowAdminCreateUserOnly=true
```

### Environment

```markdown
- OS: MacOS 12.5
- LocalStack: 1.0.5.dev
```

**Comment by giograno** [comment]
Hi @maciejstromich, we released a fix introducing `EstimatedNumberOfUsers` as a field for `DescribeUserPool`. Please pull the `latest` Docker image and give it a try. Feel free to report any further problem 🙏
