### ISSUE TITLE
Ensure LocalStack/cdklocal is included in the GitHub runner images.

### ISSUE THREAD

**Issue by Simonl9l** [localstack/localstack#6683]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

It seem that currently the maintainers of the GitHub Workflow runner do not see the value in preinstalling the LocalStack/cdkLocal CLI along side all the other but in tools , including the core AWS CLI.

We have a similar request to the AWS CDK maintainers for same with that cli https://github.com/aws/aws-cdk/issues/21629

It seem that ti might be quite valuable to many than having to install the cdklocal cli each time.

please see the issue - https://github.com/actions/runner-images/issues/6089

### Anything else?

It's frustrating when building GitHub workflows to have to add steps to install the CDK local Cli each time.

**Comment by whummer** [comment]
Thanks for reporting @Simonl9l . While I do share your sentiment that it would be nice to have `cdklocal` pre-installed in the runners, I'm not entirely sure how we can influence it, given that the maintainers have essentially already decided against it.

As has been mentioned here, the tool can be installed in runtime, and should usually not take too long to execute: https://github.com/actions/runner-images/issues/6089#issuecomment-1216268644

Does that work for you, installing it as part of the CI build setup? In fact, that's also what we're doing in our own CI pipeline, and it has been working fine so far.. 👍 Thanks for the feedback

**Comment by Simonl9l** [comment]
We use Nuke Build but have had some success with calling npx.

However we have dropped our use of Localstack for the time being, as it's been to difficult together a consistent experience across a team of developers across Windows/Unix/MacOS - Apple Silicon, and concurrently deveoping. 

We wil keep an eye on Localstack evolution though...
