### ISSUE TITLE
bug: Exception  java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/ObjectMapper

### ISSUE THREAD

**Issue by egobrain** [localstack/localstack#6691]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

25 72.39 2022-08-17T14:49:08.980  INFO --- [   Thread-20] localstack.utils.run       : Restarting process (received exit code 1): ['java', '-Xmx256m', '-javaagent:/usr/lib/localstack/dynamodb/ddb-local-loader-0.1.jar', '-Djava.library.path=/usr/lib/localstack/dynamodb/DynamoDBLocal_lib', '-jar', '/usr/lib/localstack/dynamodb/DynamoDBLocal.jar', '-port', '60149', '-dbPath', '/var/lib/localstack/tmp/state/dynamodb']
#25 72.66 Waiting for all LocalStack services to be ready
#25 73.36 2022-08-17T14:49:09.946  INFO --- [   Thread-20] l.services.dynamodb.server : Initializing DynamoDB Local with the following configuration:
#25 73.36 2022-08-17T14:49:09.948  INFO --- [   Thread-20] l.services.dynamodb.server : Port:	60149
#25 73.36 2022-08-17T14:49:09.950  INFO --- [   Thread-20] l.services.dynamodb.server : InMemory:	false
#25 73.37 2022-08-17T14:49:09.955  INFO --- [   Thread-20] l.services.dynamodb.server : DbPath:	/var/lib/localstack/tmp/state/dynamodb
#25 73.38 2022-08-17T14:49:09.965  INFO --- [   Thread-20] l.services.dynamodb.server : SharedDb:	false
#25 73.38 2022-08-17T14:49:09.965  INFO --- [   Thread-20] l.services.dynamodb.server : shouldDelayTransientStatuses:	false
#25 73.38 2022-08-17T14:49:09.965  INFO --- [   Thread-20] l.services.dynamodb.server : CorsParams:	*
#25 73.38 2022-08-17T14:49:09.965  INFO --- [   Thread-20] l.services.dynamodb.server :
#25 75.29 2022-08-17T14:49:11.879  INFO --- [   Thread-20] l.services.dynamodb.server : Exception in thread "main" java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/ObjectMapper
#25 75.29 2022-08-17T14:49:11.882  INFO --- [   Thread-20] l.services.dynamodb.server : at com.amazonaws.services.dynamodbv2.local.main.ServerRunner.createServer(ServerRunner.java:124)
#25 75.30 2022-08-17T14:49:11.883  INFO --- [   Thread-20] l.services.dynamodb.server : at com.amazonaws.services.dynamodbv2.local.main.ServerRunner.createServerFromCommandLineArgs(ServerRunner.java:120)
#25 75.30 2022-08-17T14:49:11.885  INFO --- [   Thread-20] l.services.dynamodb.server : at com.amazonaws.services.dynamodbv2.local.main.ServerRunner.main(ServerRunner.java:75)
#25 75.30 2022-08-17T14:49:11.888  INFO --- [   Thread-20] l.services.dynamodb.server : Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.databind.ObjectMapper
#25 75.30 2022-08-17T14:49:11.888  INFO --- [   Thread-20] l.services.dynamodb.server : at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
#25 75.30 2022-08-17T14:49:11.889  INFO --- [   Thread-20] l.services.dynamodb.server : at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
#25 75.30 2022-08-17T14:49:11.889  INFO --- [   Thread-20] l.services.dynamodb.server : at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
#25 75.30 2022-08-17T14:49:11.890  INFO --- [   Thread-20] l.services.dynamodb.server : ... 3 more
#25 75.31 2022-08-17T14:49:11.901  INFO --- [   Thread-20] localstack.utils.run       : Restarting process (received exit code 1): ['java', '-Xmx256m', '-javaagent:/usr/lib/localstack/dynamodb/ddb-local-loader-0.1.jar', '-Djava.library.path=/usr/lib/localstack/dynamodb/DynamoDBLocal_lib', '-jar', '/usr/lib/localstack/dynamodb/DynamoDBLocal.jar', '-port', '60149', '-dbPath', '/var/lib/localstack/tmp/state/dynamodb']
#25 75.68 Waiting for all LocalStack services to be ready

### Expected Behavior

Kinesis mock started successfully

### How are you starting LocalStack?

With the `localstack` script

### Steps To Reproduce

pip3 install "localstack[runtime]"
EAGER_SERVICE_LOADING=1 SERVICES=kinesis localstack start --host

**Comment by whummer** [comment]
Hi @egobrain , thanks for reporting. Seems to be related to some JAR dependencies for DynamoDB we recently had to patch, due to security issues. 

Please note that the `--host` flag is no longer supported - we generally recommend running LocalStack inside the Docker container.

In this particular case, can you please try deleting the local contents of your LocalStack volume directory, in particular the folder `/usr/lib/localstack/dynamodb` (as this seems to be the volume dir, according to the log output above). On the next restart of LocalStack, the missing dependencies should get downloaded automatically..

Hope that helps - please keep us posted on how it goes. Thanks!

**Comment by egobrain** [comment]
@whummer no, re-downloading of artifacts doesn't help

**Comment by egobrain** [comment]
@whummer if i manually apply this https://github.com/localstack/localstack/commit/8f157e56ba9808945e445950b749a3a58d6e953f commit to the installed localstack install.py - everything works well

**Comment by whummer** [comment]
I see, thanks for confirming the fix @egobrain . This commit is already merged to  `master` branch, and available as a dev package on pypi.org.

You can upgrade your local installation to the latest dev release by adding the `--pre` flag:
```
pip install --upgrade --pre localstack
```

Hope that helps - please let us know if there are any other issues.. Thanks!
