### ISSUE TITLE
bug: Kinesis `GetRecords` consistently fails past a certain point in time

### ISSUE THREAD

**Issue by kingkupps** [localstack/localstack#6692]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

At some point, Localstack's Kinesis service consistently begins to throw the following errors for `GetRecords`:
```
Unexpected end of JSON input
```
and
```
Stream closed with error code NGHTTP2_PROTOCOL_ERROR
```

I see the following repeated quite often in Localstack logs when it starts to happen although this feels potentially unrelated:
```
Exception ignored in: <coroutine object worker_serve.<locals>._server_callback at 0xffff3331af10>
Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/hypercorn/asyncio/run.py", line 100, in _server_callback
    await TCPServer(app, loop, config, context, reader, writer)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/hypercorn/asyncio/tcp_server.py", line 70, in run
    async with TaskGroup(self.loop) as task_group:
RuntimeError: coroutine ignored GeneratorExit
```

### Expected Behavior

I would expect for `GetRecords` to succeed consistently

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

With the following compose file:
```
  localstack:
    container_name: localstack
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      DEBUG: 1
      DOCKER_HOST: unix:///var/run/docker.sock
      KINESIS_INITIALIZE_STREAMS: dbsync:1,dbsync.events:1
    volumes:
      - ./dbsync/localstack:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)
Using the node v3 SDK
```
function getRecords(
  shardIterator: string
): Promise<GetRecordsCommandOutput> {
  const command = new GetRecordsCommand({
    Limit: 2000,
    ShardIterator: shardIterator,
  });
  return kinesisClient.send(command);
}
```
The above consistently throws an exception with the messages at the start of this issue.

### Environment

```markdown
- OS: MacOS Monterey 12.4
- LocalStack: latest
```

**Comment by thrau** [comment]
Thanks for the report Jamie @kingkupps! We are re-working kinesis at the moment where we can hopefully address the issue, you can follow the development here #6166.

**Comment by ackdav** [comment]
Hello @kingkupps - thanks for raising this issue. As mentioned above, kinesis was reworked and is now merged into master for a couple months already. Could you please double-check whether you still see this issue?
I quickly did the following:
```
localstack start -d
awslocal kinesis create-stream --stream-name stream_name --shard-count 1
SHARD_ITERATOR=$(awslocal kinesis get-shard-iterator --stream-name kinesisStream --shard-id shardId-000000000000 --shard-iterator-type TRIM_HORIZON  | jq -r '.ShardIterator')
while :; do; awslocal kinesis get-records --shard-iterator $SHARD_ITERATOR;sleep 1; done
```
and in a different terminal:
```
while :; do; awslocal kinesis put-record --stream-name stream_name --data "$(date +%Y+%m+%dT%H+%M+%S)=" --partition-key x; sleep 1; done
```
And I don't see any issues while letting it run for a couple minutes.
