### ISSUE TITLE
bug: Kinesis stream names set to stream's ARN

### ISSUE THREAD

**Issue by leahfitchgraphika** [localstack/localstack#6696]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When deploying a stack with a kinesis stream, the stream name attribute is being set to the value of the stream's ARN instead of the stream's name. Since many boto3 functions require the stream name, it makes it very difficult to access the streams from other resources like lambdas.

### Expected Behavior

The expected behavior is that the `stream_name` attribute of a kinesis stream is set to the value of the stream name.

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

localstack start

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

An example cdk application showing the problem can be found here: https://github.com/leahfitchgraphika/localstack-stream-name-bug

### Environment

```markdown
- OS: OSX 12.3.1
- LocalStack: latest
```

**Comment by blake-ctrl** [comment]
Ran into this same error using CDK. Refs to the streamname are returning the arn in 1.0.4 and also in the dev 1.0.5 versions.

I thought I was going crazy for a while.

**Comment by pinzon** [comment]
@leahfitchgraphika could you check the reproducer you send? I don't see where is creating the Kinesis stream. 
@blake-ctrl could you also send a reproducer? 
I added a CFN Kinesis test but all it does is show that the creation of a Kinesis stream works correctly.

**Comment by blake-ctrl** [comment]
Sure thing @pinzon 
Repo to reproduce here: https://github.com/blake-ctrl/kinesis-localstack-issue

Comparing localstack and cloud AWS cdk deployment side by side.
The first, using localstack shows the streamname ref returning the ARN, the second on AWS, correctly returns only the stream name.
![image](https://user-images.githubusercontent.com/65546032/186725180-607a892a-98b1-4eca-96d7-4df6bc21bf4b.png)

**Comment by pinzon** [comment]
Thanks @blake-ctrl. I can confirm that I have same output.

**Comment by leahfitchgraphika** [comment]
Sorry about that. Forgot to push updates to the repo. The example is visible now.

**Comment by pinzon** [comment]
No worries. I already made a PR with the fix.

**Comment by pinzon** [comment]
The solution for this issue has been merged. Thank you for the report!
