### ISSUE TITLE
bug: LocalStack copies lots of lambda binary  to `/tmp` directory

### ISSUE THREAD

**Issue by DeLion13** [localstack/localstack#6698]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently on each `terraform apply` I see that my `/tmp` directory is filling by lambda binary archive copies. In some cases it may gain tens of GBs of memory, if I run lot's of applies in short period for testing.

<img width="505" alt="Screenshot 2022-08-18 at 16 33 02" src="https://user-images.githubusercontent.com/47575978/185421369-4a0860a7-d09e-4ad8-a64b-e7650206ed1c.png">

<img width="628" alt="Screenshot 2022-08-18 at 16 33 42" src="https://user-images.githubusercontent.com/47575978/185421700-94387712-9963-4cf1-8e32-6de7fb72ae8a.png">

### Expected Behavior

It'd be great to have a possibility to not to copy lambdas in case if we use the same `S3 bucket` path in different deployments.

### How are you starting LocalStack?

With a `docker run` command

### Steps To Reproduce

It must be possible to reproduce it by running chunk of different `terraform applies` in one localstack container.

### Environment

```markdown
- OS: Tested on Debian 11, but it's relevant for other Linux systems
- LocalStack: 0.14.2
```

**Comment by whummer** [comment]
Thanks for reporting @DeLion13 . We have introduced a couple of enhancements with our version 1.0 release, including a new filesystem layout and better cleanup of these temporary Lambda directories. Can you please update your Docker image to one of the latest tags (e.g., `1.0.4` or `latest`) and give it another try? Thanks!
