### ISSUE TITLE
Java LambdaExecutor ClassCastException: LinkedHashMap cannot be cast to KinesisEvent

### ISSUE THREAD

**Issue by andrezimmermann** [localstack/localstack#670]
Here it gets from the map the "Kinesis" key.
https://github.com/localstack/localstack/blob/32da2d47079ac632891c7899c172d02434263f16/localstack/ext/java/src/main/java/cloud/localstack/LambdaExecutor.java#L65

But here
 https://github.com/localstack/localstack/blob/551eaad4fc48c833347d10afb430ffeae52ff97d/localstack/services/awslambda/lambda_api.py#L194
It creates the input with "kinesis" key, failing to create the KinesisEvent since the key is not the same.

**Comment by rahulshyam79** [comment]
@andrezimmermann I faced the same issue yesterday after using latest docker image of localstack.
I tried to fix this issue locally by changing the java code and building docker image using the Makefile, but for some reason still get this when the lambda get invoked of kinesis.

**Comment by andrezimmermann** [comment]
The workaround is to implement the RequestHandler with
```
RequestStreamHandler {
    public void handleRequest(InputStream inputStream, OutputStream outputStream, Context context)
            throws IOException { ... }
}
```

The current codebase is unable to handle custom pojos

**Comment by whummer** [comment]
Closing this issue as outdated/fixed. Please open a follow-up issue if the problem persists. Thanks
