### ISSUE TITLE
feature request: Support for CFn resource "AWS::Lambda::Url"

### ISSUE THREAD

**Issue by dominikschubert** [localstack/localstack#6704]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Add support for `AWS::Lambda::Url` resources.

### Anything else?

Docs: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-url.html

**Comment by Simonl9l** [comment]
@dominikschubert an idea on an ETA?

**Comment by dominikschubert** [comment]
> @dominikschubert an idea on an ETA?

It's available on latest now :+1:
