### ISSUE TITLE
feature request: Supply an official localstack image to AWS ECR public gallery

### ISSUE THREAD

**Issue by acommodari** [localstack/localstack#6706]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

You already publish an official docker image to docker hub but I was wondering if you would be interested in publishing one to AWS ECR public gallery as well. Right now there are a ton of unofficial images (seen [here](https://gallery.ecr.aws/?searchTerm=localstack)) but I do not want to use them for obvious reasons. This would be a great help at least for my company as we are slowly moving away from docker hub to AWS ECR.

Thank you

### Anything else?

https://gallery.ecr.aws/

**Comment by whummer** [comment]
Hi @acommodari , thanks for reporting. In fact, we're already pushing the image to the public ECR repository `public.ecr.aws/localstack/localstack` via our pipelines (should contain the same images and tags as on Docker Hub) - this is not super well covered in our docs yet, we'll make sure to better document it.. 👍

**Comment by acommodari** [comment]
Amazing thanks! Not sure why it wasn't showing up when I was searching 🤔 This is great news 😁

**Comment by jprema7** [comment]
Hi - can this be reopened?

I am getting an unauthorized response when trying to access: public.ecr.aws/localstack/localstack 

```
{
  "errors": [
    {
      "code": "DENIED",
      "message": "Not Authorized"
    }
  ]
}
```
