### ISSUE TITLE
An error occurred (InternalFailure) when calling the CreateApi operation: API action 'CreateApi' for service 'apigatewayv2' not yet implemented

### ISSUE THREAD

**Issue by jesswales** [localstack/localstack#6721]
Trying to create an API gateway in local stack but receiving not yet implemented message.

This is my command:

awslocal apigatewayv2 create-api --name myapp_http_api --protocol-type HTTP --target arn:aws:lambda:us-east-1:000000000000:function:cert-lambda-function

Response:

An error occurred (InternalFailure) when calling the CreateApi operation: API action 'CreateApi' for service 'apigatewayv2' not yet implemented

**Comment by whummer** [comment]
Thanks for reporting @jesswales . Please note that certain features and services (including API Gateway v2) are only available in the Pro version of LocalStack.

If you'd like to give it a try, you can sign up for a free trial under https://app.localstack.cloud and configure an API key for your LocalStack instance, which will enable the advanced features. Hope that helps - please keep us posted on how it goes.. Thanks!
