### ISSUE TITLE
bug: Cannot request emails for localstack_/ses when emails are sent with ses v2 api.

### ISSUE THREAD

**Issue by peterehik-px** [localstack/localstack#6725]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

There's a problem with the send email sesv2 api: Once you send an email, you can't then retrieve it using the _localstack/ses endpoint because the api expects the email you sent to have a 'source' parameter even though in the sesv2 api, source and sourceArn have been replaced with 'fromEmailAddress' and 'fromEmailAddressIdentityArn' https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_SendEmail.html. Therefore when you send an email and try to retreive it, you get this error on localstack:

```2022-08-22T15:37:41.704 ERROR --- [   asgi_gw_5] l.aws.handlers.logging     : exception during call chain
Traceback (most recent call last):
  File "/opt/code/localstack/localstack/aws/chain.py", line 57, in handle
    handler(self, self.context, response)
  File "/opt/code/localstack/localstack/aws/handlers/internal.py", line 31, in __call__
    response.update_from(self.resources.dispatch(context.request))
  File "/opt/code/localstack/localstack/http/router.py", line 234, in dispatch
    return self.dispatcher(request, handler, args)
  File "/opt/code/localstack/localstack/http/dispatcher.py", line 74, in _dispatch
    result = fn(request, **args)
  File "/opt/code/localstack/localstack/services/ses/provider.py", line 108, in on_get
    if filter_source in (msg["Source"], None, ""):
KeyError: 'Source'
```

### Expected Behavior

The expected behavior should be that when you've sent an email using the sesv2 api, you can retrieve it using the _localstack/ses http api with no issues. This is super useful in test code because it's currently the only way to verify that an email has been sent. 

### How are you starting LocalStack?

Custom (please describe below)

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

I'm using the localstack helm chart to start it in minikube. 

### Environment

```markdown
- OS:
- LocalStack:
```

**Comment by peterehik-px** [comment]
This is the breaking PR: https://github.com/localstack/localstack/pull/6340

**Comment by viren-nadkarni** [comment]
@peterehik-px Thank you for reporting this. 

Could you please confirm that this was encountered when sending a Raw email type?

**Comment by peterehik-px** [comment]
> @peterehik-px Thank you for reporting this.
> 
> Could you please confirm that this was encountered when sending a Raw email type?

yeah this was while sending a raw email.
