### ISSUE TITLE
bug: CloudFormation alarm arn is being resolved as the name.

### ISSUE THREAD

**Issue by thantos** [localstack/localstack#6726]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://user-images.githubusercontent.com/289213/186028491-6f213ba9-b93b-46a7-b67f-08447d7e2a42.png)

the above cloudformation returns the following error:

> 2022-08-22T22:06:41.047 DEBUG --- [  Thread-304] l.u.c.template_deployer    : Error applying changes for CloudFormation stack "sfnStack": An error occurred (MalformedPolicyDocument) when calling the PutRolePolicy operation: Resource sfnStack-parent15Alarm396D538E-7af57e00 must be in ARN format or "*". Traceback (most recent call last):

### Expected Behavior

`GetAtt("Arn")` on an Alarm should return an ARN.

```yml
Fn::GetAtt:
   - parent15Alarm396D538E
   - 'Arn'
```

### How are you starting LocalStack?

With the `localstack` script

### Steps To Reproduce

Try to deploy a cloudformation template with a alarm arn reference.

json for the alarm and role

```json
{
  "parent15Alarm396D538E": {
    "Type": "AWS::CloudWatch::Alarm",
    "Properties": {
      "ComparisonOperator": "GreaterThanOrEqualToThreshold",
      "EvaluationPeriods": 1,
      "MetricName": "Errors",
      "Namespace": "AWS/Lambda",
      "Period": 300,
      "Statistic": "Average",
      "Threshold": 1
    }
  },
  "parent15fnRoleDefaultPolicy79A71794": {
    "Type": "AWS::IAM::Policy",
    "Properties": {
      "PolicyDocument": {
        "Statement": [
          {
            "Action": "cloudwatch:DescribeAlarms",
            "Effect": "Allow",
            "Resource": { "Fn::GetAtt": ["parent15Alarm396D538E", "Arn"] }
          }
        ],
        "Version": "2012-10-17"
      },
      "PolicyName": "parent15fnRoleDefaultPolicy79A71794",
      "Roles": [{ "Ref": "parent15fnRoleB900B1C1" }]
    }
  },
  "parent15fnRoleB900B1C1": {
    "Type": "AWS::IAM::Role",
    "Properties": {
      "AssumeRolePolicyDocument": {
        "Statement": [
          {
            "Action": "sts:AssumeRole",
            "Effect": "Allow",
            "Principal": { "Service": "states.us-east-1.amazonaws.com" }
          }
        ],
        "Version": "2012-10-17"
      }
    }
  }
}
```

### Environment

```markdown
- OS: windows/wsl2/ubuntu
- LocalStack: 1.0.4
```

**Comment by thantos** [comment]
The stack ends up in a bad state after this error too.

> 2022-08-22T22:42:18.975  WARN --- [ Thread-1197] l.u.c.template_deployer    : Error calling <bound method ClientCreator._create_api_method.<locals>._api_call of <botocore.client.SFN object at 0x7f65c1867d30>> with params: {} for resource: {'Type': 'AWS::StepFunctions::StateMachine', 'DependsOn': ['parent15fnRoleDefaultPolicy79A71794', 'parent15fnRoleB900B1C1'], 'LogicalResourceId': 'parent15fnD82104EC', 'Properties': {'RoleArn': 'arn:aws:iam::000000000000:role/sfnStack-parent15fnRoleB900B1C1-2dd581fd', 'DefinitionString': '{"StartAt":"Initialize Functionless Context","States":{"Initialize Functionless Context":{"Type":"Pass","Parameters":{"fnl_context":{"null":null}},"ResultPath":"$","Next":"{ MetricAlarms } = await $AWS.SDK.CloudWatch.describeAlarms({AlarmNames: [a"},"{ MetricAlarms } = await $AWS.SDK.CloudWatch.describeAlarms({AlarmNames: [a":{"Type":"Task","Resource":"arn:aws:states:::aws-sdk:cloudwatch:describeAlarms","Next":"MetricAlarms","Parameters":{"AlarmNames":["sfnStack-parent15Alarm396D538E-7af57e00"]},"ResultPath":"$.heap0"},"MetricAlarms":{"Type":"Pass","Next":"return MetricAlarms[0].Namespace","ResultPath":"$.MetricAlarms","InputPath":"$.heap0[\'MetricAlarms\']"},"return MetricAlarms[0].Namespace":{"Type":"Pass","End":true,"ResultPath":"$","InputPath":"$.MetricAlarms[0].Namespace"}}}', 'StateMachineType': 'STANDARD', 'StateMachineName': 'sfnStack-parent15fnD82104EC-1e91911c'}, '_state_': {}, 'PhysicalResourceId': None}
2022-08-22T22:42:18.986 DEBUG --- [ Thread-1197] l.u.c.template_deployer    : Error applying changes for CloudFormation stack "sfnStack": Parameter validation failed:
Missing required parameter in input: "stateMachineArn" Traceback (most recent call last):

**Comment by thantos** [comment]
Update: 

Looks like our Cfn has an empty value in it...

```json
        {
         "Ref": "AWS::NoValue"
        }
```

However... AWS does not fail on this template, but localstack does.

**Comment by thantos** [comment]
Alright, diving it, it seems that some of the CDK constructs inject invalid resource values into the managed policies.

For example, Dynamo adds an empty resource string (above) in some cases.

https://github.com/aws/aws-cdk/blob/v1.169.0/packages/@aws-cdk/aws-dynamodb/lib/table.ts#L1579-L1580

AWS doesn't seem to care about this, but localstack fails.

**Comment by pinzon** [comment]
The solution to this issue has been merged. Thank you for the report!
