### ISSUE TITLE
bug: infra service crashes regularly

### ISSUE THREAD

**Issue by dhay** [localstack/localstack#6738]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm running localstack in a docker-compose configuration.  I'm seeing frequent, random crashes of the `infra` service, even when I'm not running any AWS commands against the docker container.  
```
localstack_my-app  | 2022-08-23T21:26:51.279  WARN --- [  Thread-108] hypercorn.error            : ASGI Framework Lifespan error, continuing without Lifespan support
localstack_my-app  | 2022-08-23T21:26:51.279  WARN --- [  Thread-108] hypercorn.error            : ASGI Framework Lifespan error, continuing without Lifespan support
localstack_my-app  | 2022-08-23T21:26:51.280  INFO --- [  Thread-108] hypercorn.error            : Running on https://0.0.0.0:4566 (CTRL + C to quit)
localstack_my-app  | 2022-08-23T21:26:51.280  INFO --- [  Thread-108] hypercorn.error            : Running on https://0.0.0.0:4566 (CTRL + C to quit)
localstack_my-app  | Ready.
localstack_my-app  | 2022-08-23 21:32:16,653 INFO exited: infra (terminated by SIGKILL; not expected)
localstack_my-app  | 2022-08-23 21:32:16,725 INFO spawned: 'infra' with pid 8440
localstack_my-app  | 2022-08-23 21:32:17,732 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
localstack_my-app  |
localstack_my-app  | LocalStack version: 1.0.5.dev
localstack_my-app  | LocalStack Docker container id: 31c8c0a097b2
localstack_my-app  | LocalStack build date: 2022-08-09
localstack_my-app  | LocalStack build git hash: d991caa2
```

I haven't found any existing issues that might explain this, nor have I seen any configuration options that might suggest some kind of timeout or error handling strategy.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

```
docker compose up
```

I also have a setup script in the `localstack` directory that creates an s3 bucket:
```
aws --endpoint-url=http://localstack:4566 s3 mb s3://my-bucket --region us-west-2
```

### Environment

```markdown
- OS:Darwin Davids-MBP 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000 x86_64

- LocalStack: 1.0.5
```

**Comment by whummer** [comment]
Thanks for reporting @dhay - can you please share some details about the log output / error message you're seeing when LocalStack crashes? Please try enabling `DEBUG=1` in your container environment, to enable debug logs. 

Also, please verify that sufficient RAM and disk space is available in your Docker environment 👍  - running out of disk space can be a frequent source of errors.. Thanks!

**Comment by dhay** [comment]
I realized my docker environment was only running with 2GB of RAM.  Increasing this to 4GB seems to have improved the stability.  I haven't had issues with LocalStack crashing since I did that. 

Thanks for the tip!
