### ISSUE TITLE
bug: Should respect SQS 256 KB limitation per message OR batch

### ISSUE THREAD

**Issue by eau-de-la-seine** [localstack/localstack#6740]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am able to send SQS messages that are greater than 256 KB, but according to [AWS sqs limitation](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/quotas-messages.html) I should not be able to do that.

### Expected Behavior

Should respect SQS 256 KB limitation and not be able to send a message OR batch greater than 262,144 bytes. Should emulate and throw the same error message than AWS

### How are you starting LocalStack?

With the `localstack` script

### Steps To Reproduce

Code to reproduce:
```typescript
      // GIVEN
      const elements = [];
      const readInterface = readline.createInterface({
        input: fs.createReadStream('./test/resources/mock-out-of-limit-odp-object.json')
      });

      for await (const line of readInterface){
        elements.push(line);
      }

      // WHEN
      const response = await sendMessageBatch(sqsClient, QueueUrl, elements);

      // THEN
      expect(response.length).toEqual(1);
      const getQueueAttributesCommandOutput: GetQueueAttributesCommandOutput = await sqsClient.send(new GetQueueAttributesCommand({
        QueueUrl,
        AttributeNames: ['ApproximateNumberOfMessages'],
      }));
      expect(getQueueAttributesCommandOutput?.Attributes?.ApproximateNumberOfMessages).toEqual('1');
      console.log(`Sending BIG: ${JSON.stringify(elements).length}`);
```

`mock-out-of-limit-odp-object.json` is a file with 1 line of +400 KB, I successfully send it to localstack and retrieve the queue size (= 1). The `console.log` of AWS `response`:
```json
[
  {
    "$metadata": {
      "httpStatusCode": 200,
      "attempts": 1,
      "totalRetryDelay": 0
    },
    "Successful": [
      {
        "Id": "0",
        "MessageId": "a617f6f7-8c5a-4307-90ac-60b5a0a6926b",
        "MD5OfMessageBody": "47d0974436a10505b479b623f5d2a6c8"
      }
    ]
  }
]
```
=> **It should not be "Successful", localstack should offer closer emulation to AWS' behavior**

### Environment

```markdown
- OS: Ubuntu 20.04
- LocalStack: 1.0.4
```

**Comment by thrau** [comment]
Thanks for reporting Gokan @eau-de-la-seine, seem like we don't have any checks in place. `MaximumMessageSize` already defaults to 256k, so we would just need to check against that, and add some tests against AWS to also check the batching behavior.

**Comment by thrau** [comment]
hi @eau-de-la-seine. fix for this should be available in about an hour. thanks to @rjmcginness for the community contribution!
