### ISSUE TITLE
feature request: Support for AWS::SecretManager:SecretTargetAttachachment in CloudFormation

### ISSUE THREAD

**Issue by Tedsterh** [localstack/localstack#6748]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

I am trying to spin up an Aurora Serverless instance but it fails due to LocalStack not currently supporting the creation of `AWS::SecretManager:SecretTargetAttachachment`, i can create the secret but am unable to link the secret to the database which in turn throws an error when creating the database.

Here is an example cdk stack for creating the Aurora DB Cluster which is currently failing to be build, although a successful deploy is returned:

```typescript 
// Generates a secret to be used as credentials for our database
const databaseCredentialsSecret = new secretsManager.Secret(
  this,
  `DB-CredentialsSecret`,
  {
    secretName: `DB-credentials`,
    generateSecretString: {
      secretStringTemplate: JSON.stringify({
        username: "postgres",
      }),
      excludePunctuation: true,
      includeSpace: false,
      generateStringKey: "password",
    },
  }
);

// Create the VPC needed for the Aurora Serverless DB cluster
const vpc = new ec2.Vpc(this, "DBVPC");

// Create the Serverless Aurora DB cluster; set the engine to Postgres
const cluster = new rds.ServerlessCluster(this, "AuroraDBCluster", {
  engine: rds.DatabaseClusterEngine.AURORA_POSTGRESQL,
  parameterGroup: rds.ParameterGroup.fromParameterGroupName(
    this,
    "ParameterGroup",
    "default.aurora-postgresql10"
  ),
  defaultDatabaseName: "DB",
  vpc,
  scaling: { autoPause: Duration.seconds(0) },
  credentials: rds.Credentials.fromGeneratedSecret("postgres", {
    secretName: "DB-credentials",
  }),
});
```

The current errors in the console:
```Unable to deploy resource type "SecretsManager::SecretTargetAttachment"```

I am also getting this error which might be unrelated but it doesn't seem to be creating the Aurora DB Cluster properly either, this might be related to the `SecretsManager` but i am not entirely sure:
```Unable to startup DB instance: {'S': 'FATAL', 'V': 'FATAL', 'C': '3D000', 'M': 'database "DB" does not exist', 'F': 'postinit.c', 'L': '855', 'R': 'InitPostgres'}``` 

This is currently stopping me using LocalStack to develop my backend locally as the only alternative i can find, would be to use DynamoDB instead of Aurora.

**Comment by mikkilevon** [comment]
This is a feature that would be needed

**Comment by deepak2431** [comment]
As discussed with @pinzon, I am taking up this issue to work on.

**Comment by simonrw** [comment]
Hi @Tedsterh , thanks for posting this issue. Unfortunately I cannot recreate your example on AWS. When I run the example on AWS I get the error:

> The operation failed because the secret DB-credentials already exists. (Service: SecretsManager, Status Code: 400, Request ID: b09e611d-5806-4a39-bef3-eab48d807a7d)"

Would it be possible to supply a reproduction case that works against AWS?

**Comment by JohnGrayUoY** [comment]
I have encountered this issue on the most recent localstack/localstack-pro:2.2.0 docker image and I have submitted a reproduction case and diagnose.json file to pro support via email (Slack app was having issues).

I will also attach both here again in case it helps resolve this issue as it is a real showstopper for us.

[AWSSecretsManagerSecretTargetAttachmentRepro.zip](https://github.com/localstack/localstack/files/12239911/AWSSecretsManagerSecretTargetAttachmentRepro.zip)

[diagnose.json.gz](https://github.com/localstack/localstack/files/12239912/diagnose.json.gz)

If you need any further info let me know.

Cheers.
