### ISSUE TITLE
No arm64 lambda support for localstack/lambda:python3.9

### ISSUE THREAD

**Issue by fzonneveld** [localstack/localstack#6756]
Forced to which from amd64/x86_64 architecture to arm64. We are using localstack to simulate e2e tests with some lambda running in the stack. Using AWS cdk to deploy. I would also like this to run on my macbook. Lambdas are zipped and contain some shared objects. These objects cannot not be loaded into the lambda (localstack/lamnda:python3.9) because the zip file was locally created on a arm64 , but the docker container is amd64. Would it be possible to make the arm64 version available on https://hub.docker.com/r/localstack/lambda, so that I can also natively use localstack on my macbook.

Thanks Frank,

**Comment by thrau** [comment]
hi Frank @fzonneveld, thanks for the report! We're aware that lambda currently has some limitations with arm64. We are currently working on a completely new lambda provider which will hopefully solve the problem #6724. We also have all the ARM limitations tracked here: #4921.

**Comment by fzonneveld** [comment]
I have used DOCKER_DEFAULT_PLATOFRM=linux/amd64 to for the lambda to be build for amd64. This solves the not provided arm64 lambda image.
Can be closed.

**Comment by dfangl** [comment]
Great to hear that!
In our new provider, we are supporting lambda arm64 images as well, so please do not hesitate to try it out using `PROVIDER_OVERRIDE_LAMBDA=asf`.

**Comment by fzonneveld** [comment]
Thanks for closing the issue.

Regards,
Frank

Op wo 21 dec. 2022 om 15:13 schreef Daniel Fangl ***@***.***>:

**Comment by joe4dev** [comment]
@fzonneveld
Using our new lambda provider implementation, LocalStack now supports lambda functions running on arm64 (only on ARM hosts, see https://github.com/localstack/localstack/issues/7637), even with public ARM layers (pro feature, see https://github.com/localstack/localstack/issues/4932) 🚀 

1. Pull the latest LocalStack image `docker pull localstack/localstack-pro`
2. Start LocalStack with the environment variable [configuration](https://docs.localstack.cloud/references/configuration/) `PROVIDER_OVERRIDE_LAMBDA=v2`
