### ISSUE TITLE
PutBucketLogging giving MalformedXML error for payload working with real AWS

### ISSUE THREAD

**Issue by ashish4710** [localstack/localstack#6764]
Hi,

I am using below payload for PutBucketLogging api and getting MalformedXML error in response. I have checked it with real AWS and it is working perfectly fine. Am I missing something or this needs a fix in localstack?

`"LoggingEnabled": {
            "TargetBucket": "test_bucket_name",
            "TargetPrefix": "log",
            "TargetGrants": [
                {
                    "Grantee": {
                        "URI": "http://acs.amazonaws.com/groups/s3/LogDelivery",
                        "Type": "Group",
                    },
                    "Permission": "WRITE",
                },
                {
                    "Grantee": {
                        "URI": "http://acs.amazonaws.com/groups/s3/LogDelivery",
                        "Type": "Group",
                    },
                    "Permission": "READ_ACP",
                },
            ],
        }
 `

**Comment by bentsku** [comment]
Hi @ashish4710 and thanks for your report,

I'm reproducing the issue, and indeed AWS is not raising an exception. However, granting those permissions to the `LogDelivery` group does not actually grants it permission. You would need to do it with Bucket ACL, see here: https://docs.aws.amazon.com/AmazonS3/latest/userguide/ServerLogs.html

The `TargetGrants` allows you to give access to the logs once those are publishing to the `TargetBucket`, but the `LogDelivery` group will need access before that. You can read more about it in the examples here as well: https://docs.aws.amazon.com/cli/latest/reference/s3api/put-bucket-logging.html

In the meantime, I think LocalStack should not raise an exception if AWS does not, so I'll keep this issue open and work on the validation of the payload.
