### ISSUE TITLE
bug: MD5 returned by SQS does not match the calculation on the original request. (Message Attributes)

### ISSUE THREAD

**Issue by mvillafuertem** [localstack/localstack#6794]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

https://github.com/localstack/localstack/issues/3022#issuecomment-1231366317

Attempting to write to sqs on localstack versions > 0.14.3 results in an MD5 checksum error. The error is specific to the message attributes hash value and not the hash value on the message body.

localstack > 0.14.3

This code works perfectly with localstack 0.14.2

https://github.com/mvillafuertem/localstack-error

```scala

SendMessageRequest
          .builder()
          .messageAttributes(
            Map(
              "Body" -> MessageAttributeValue
                .builder()
                .dataType("Binary")
                .binaryValue(SdkBytes.fromByteArray(java.util.Base64.getEncoder.encode("user:pass".getBytes(StandardCharsets.UTF_8))))
                .build()
            ).asJava
          )
          .messageBody("")
          .build()

```

### Expected Behavior

Ability to write a message successfully to sqs using the alpakka sqs messaging template. Ability to read message
from the queue.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

I have created a simple project with CI where you can reproduce the error

https://github.com/mvillafuertem/localstack-error

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack:0.14.3

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    sbt test
    
    
 

### Environment

```markdown
- OS:
- LocalStack:
```

**Comment by rjmcginness** [comment]
Looks like issue #3022 was similar.

**Comment by sergio41** [comment]
Do we have any news in this regard??

**Comment by mvillafuertem** [comment]
hey, any news?

**Comment by alexrashed** [comment]
Since it seems that the issue is not reproducible, I am going to close this issue for now.
Please feel free to open a new ticket if you are still experiencing any issues.
Thanks!
