### ISSUE TITLE
bug: Cloudformation Stack Fails to Update

### ISSUE THREAD

**Issue by thantos** [localstack/localstack#6796]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Updating an existing stack fails with error

> Stack [stack] already exists

### Expected Behavior

Update the stack

### How are you starting LocalStack?

With the `localstack` script

### Steps To Reproduce

* Create cloudformation stack
* Deploy
* Update
* Deploy

### Environment

```markdown
- OS: WSL2/Ubuntu
- LocalStack: latest
```

### Anything else?

I was using CDK, if that matters, these tests used to work and were able to be run over and over before.

**Comment by thrau** [comment]
hi Sam @thantos. Could you please share the stack or at least a minimal example so we can reproduce the issue? Thanks.

**Comment by thantos** [comment]
It might have been transient when upgrading because it isn't happening now, I killed lcoalstack a few times and now it doesn't complain.
