### ISSUE TITLE
localstack command is not recognized after following and installing the prerequisite

### ISSUE THREAD

**Issue by itlinkedin** [localstack/localstack#680]
Windows Installation 

Installed via pip

successfully installed but not recognized the local stack command

λ localstack start
'localstack' is not recognized as an internal or external command,
operable program or batch file.

**Comment by sa-jepstein** [comment]
Your PATH does not likely contain the director where `pip` is installing dependencies. I am not sure about the specifics of your Windows version and `python` / `pip` install method (please post if you are having issues), but this [guide](https://github.com/BurntSushi/nfldb/wiki/Python-&-pip-Windows-installation) hopefully will help. Good luck!

**Comment by whummer** [comment]
Thanks for reporting @itlinkedin , and thanks for providing an help @sa-jepstein ! I'm going to close this issue as a non-LocalStack issue, for the sake of keeping the backlog clean. Thanks for your understanding.
