### ISSUE TITLE
bug: Lambda containers not respecting timeout with infinite loop and Multiple lambda containers are spawning

### ISSUE THREAD

**Issue by Dharmik8478** [localstack/localstack#6800]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Lambda container is not stopping(hanged container) with lambda on infinite loop and creating multiple docker containers.

### Expected Behavior

Lambda container should stop after the lambda timeout.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker-compose up -d localstack

docker-compose.yml file

```
   localstack:
      container_name: "localstack"
      hostname: localstack
      image: localstack/localstack:latest
      ports:
        - 4569:4569
      environment:
        - SERVICES=secretsmanager,sqs,sns,lambda
        - AWS_DEFAULT_REGION=ap-south-1
        - AWS_ACCESS_KEY_ID=""
        - AWS_SECRET_ACCESS_KEY=""
        - DEBUG=9
        - DATA_DIR=./localstack
        - LAMBDA_EXECUTOR='docker-reuse'
        - KINESIS_ERROR_PROBABILITY=0.0
        - DOCKER_HOST=unix:///var/run/docker.sock
        - EAGER_SERVICE_LOADING=1
        - EDGE_PORT=4569
        - LS_LOG=debug
      volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
        - /tmp/localstack:/var/lib/localstack

```
Lambda details:
    python 3.8
    lambda for reproducting
```
import time

def loop(event, context):
    while True:
        print('looping....')
        time.sleep(10)
```

### Environment

```markdown
- OS:Ubuntu 18.04.5 LTS
- LocalStack: latest 1.0.4dev
```

### Anything else?

![image](https://user-images.githubusercontent.com/10184207/187893113-533d35fd-4c52-4f50-85fa-7a05a8b2b6d8.png)

**Comment by dfangl** [comment]
Will close this now, as timeouts are supported in the new provider, and should work fine.
