### ISSUE TITLE
Support Lambda runtime nodejs16.x

### ISSUE THREAD

**Issue by jpage-godaddy** [localstack/localstack#6804]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

The node 16 runtime for lambdas does not appear to be available for localstack 1.0.4.

> Serverless: Configuration warning at 'provider.runtime': should be equal to one of the allowed values \[dotnetcore2.1, dotnetcore3.1, go1.x, java11, java8, java8.al2, nodejs10.x, nodejs12.x, nodejs14.x, provided, provided.al2, python2.7, python3.6, python3.7, python3.8, python3.9, ruby2.5, ruby2.7\]

### 🧑‍💻 Implementation

If this can't be baked in outright, the ability to install lambda runtimes would be a helpful feature.

**Comment by HarshCasper** [comment]
Hi 👋 

Thanks for reporting this issue — If it's possible, could you please provide a small sample or a few snippets of your test code? That would be very helpful for us to replicate the scenario end-to-end.

Coming to the support, we do have NodeJS 16.x as an available runtime — Please take the following example for a run on your local machine and it would just working fine for NodeJS 16.x itself: https://github.com/localstack/localstack-pro-samples/tree/master/lambda-function-urls

**Comment by jpage-godaddy** [comment]
Thanks. The sample code requires localstack Pro to run, and I don't have that. I'll try to provide some details, but I'm new to this code base and localstack so please bear with me if we have to do some back and forth. With this docker compose YML:

```
version: '3.9'

services:
  localstack:
    image: ${LOCALSTACK_IMAGE:-localstack/localstack:1.0.4}
    ports:
      - "4566:4566"
    privileged: true
    container_name: localstack_main
    network_mode: bridge
    environment:
      - AWS_DEFAULT_REGION=us-west-2
      - DEFAULT_REGION=us-west-2
      - AWS_ACCESS_KEY_ID=fakeid
      - AWS_SECRET_ACCESS_KEY=fakekey
      - LOCALSTACK_HOSTNAME=localhost
      - SERVICES=dynamodb,kinesis,s3,lambda,cloudformation,sts,iam,apigateway
      - HOST_TMP_FOLDER=${TMPDIR}
      - LAMBDA_EXECUTOR=docker
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEBUG=1
      - LAMBDA_REMOTE_DOCKER=0
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

...when I try to deploy a lambda:

```
service: myservice-lambdas

plugins:
  - serverless-deployment-bucket
  - serverless-localstack

variablesResolutionMode: 20210326

custom:
  localstack:
    debug: true
    stages:
      - local
    host: http://localhost
    edgePort: 4566
    lambda:
      mountCode: True
  stage: ${opt:stage, 'local'}
  region: ${opt:region, 'us-west-2'}
  account_local: '000000000000'
  account_id: ${self:custom.account_${self:custom.stage}}

provider:
  name: aws
  runtime: nodejs16.x
  timeout: 30
  region: ${self:custom.region}
  deploymentBucket:
    name: gd-configstor-${self:custom.stage}-serverless-files
  stage: ${self:custom.stage}
  lambdaHashingVersion: "20201221"
  environment:
    ENVIRONMENT: ${self:custom.stage}

package:
  ${file(./serverless-package.yml)}

functions:
  - ${file(./serverless-api-functions.yml)}
  - ${file(./serverless-functions.yml)}

resources:
  Resources:
    ...
```

...deployment gave that posted error.

I did find the release that added node 16 support _pre_ 1.0.0, and when I use the `0.14.5` image it started working, so I wonder if node 16 support got dropped accidentally.

**Comment by jpage-godaddy** [comment]
I'm going to close this. I think what happened is that our Lambda is created indirectly through a service catalog product, and I discovered that the product version we were using didn't support node 16, so this might not be related to localstack at all. Thanks for your time, though!

**Comment by gavinvangent** [comment]
Hi All,

I've just hit this issue too ... Is there anything we can do to resolve this? Is there possibly somewhere we can log an issue or support ticket so that we can track updates to this?

**Comment by gavinvangent** [comment]
K, I might have been too impulsive... I saw this warning in the deploy step:

```sh
Serverless: Configuration warning at 'provider.runtime': should be equal to one of the allowed values [dotnetcore2.1, dotnetcore3.1, go1.x, java11, java8, java8.al2, nodejs10.x, nodejs12.x, nodejs14.x, provided, provided.al2, python2.7, python3.6, python3.7, python3.8, python3.9, ruby2.5, ruby2.7]
Serverless:  
Serverless: Learn more about configuration validation here: http://slss.io/configuration-validation
```

Decided to see what localstack would do if I try invoke the function:

```sh
ulling Docker image: localstack/lambda:nodejs16.x
2022-10-27T00:53:04.010 DEBUG --- [uncthread232] l.u.c.container_client     : Getting the entrypoint for image: localstack/lambda:nodejs16.x
2022-10-27T00:53:04.031 DEBUG --- [uncthread232] l.s.a.lambda_executors     : Creating docker-reuse Lambda container localstack_lambda_arn_aws_lambda_eu-west-1_000000000000_function_my-function from image localstack/lambda:nodejs16.x
```

It failed to run the code, but that appears to be a result of something having changed after upgrading to nodejs16. I have an error output from the lambda container that localstack created, which tells me everything localstack/lambda is 100%, it could just be that i have an old version of serverless where the supported runtimes are static and a newer version of serverless might see this warning disappear.
