### ISSUE TITLE
feature request: Support for ---additional-python-modules argument in Glue start_job_run command

### ISSUE THREAD

**Issue by jasonboutwell** [localstack/localstack#6805]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

We have a wheel stored in S3 that needs to be available for Glue Pyspark jobs to run.
[
](https://docs.aws.amazon.com/glue/latest/dg/aws-glue-programming-python-libraries.html)

**Comment by jasonboutwell** [comment]
https://docs.aws.amazon.com/glue/latest/dg/aws-glue-programming-python-libraries.html

**Comment by whummer** [comment]
Thanks for reporting @jasonboutwell - this has been added in the meantime, as also discussed on Slack. Please keep us posted on how it goes, or if there are any issues with the implementation of this feature.. Thanks!
