### ISSUE TITLE
Lambda Environment Variables

### ISSUE THREAD

**Issue by blueshirts** [localstack/localstack#681]
Is passing environment variables to Lamdas supported?  They don't seem to be showing up.  I am using LAMBDA_EXECUTOR=docker, not sure if that affects anything.  I have code that sets the environment variable that works natively on AWS though doesn't seem to work on localstack.  The environment variables are always empty.

    --environment Variables={S3_BUCKET=Test} \

```
aws lambda  create-function \
--region us-east-1 \
--function-name ReturnBucketName \
--zip-file fileb://file-path/Test_Environment_Variables.zip \
--role role-arn \
--environment Variables={S3_BUCKET=Test} \
--handler index.handler \
--runtime nodejs6.10 \
--version  version \
--profile default
```

**Comment by rzhao0817** [comment]
+1. Also getting the same issue when using update-function-configuration

**Comment by amitdhawan** [comment]
Any fix for the issue?

**Comment by d-me-tree** [comment]
+1

**Comment by gmallar** [comment]
+1 
Is there any sort of workaround for this?  This is a pretty big issue for making lambdas work.

**Comment by whummer** [comment]
Thanks for reporting. This should be fixed in the latest version - a test has been added in #1684. Closing this issue - please re-open if the problem persists. Thanks
