### ISSUE TITLE
bug: step functions - new intrinsic functions fail to deploy via cloudformation.

### ISSUE THREAD

**Issue by thantos** [localstack/localstack#6811]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

On deployment of a cloud formation template that uses the new intrinsics (ex: States.ArrayRange).

> 'SCHEMA_VALIDATION_FAILED: The value for the field 'out.$' must be a valid JSONPath or a valid intrinsic function call at /States/array__objAccess = input.range[input.key]/Parameters'

### Expected Behavior

Should deploy. Same template succeeds on AWS.

### How are you starting LocalStack?

With the `localstack` script

### Steps To Reproduce

Create a CFN template with a SFN that uses the new intrinsics:

```json
{
    "StartAt": "test",
    "States": {
        "test": {
            "Type": "Pass",
            "Parameters": { 
                 "range.$": "States.ArrayRange(1, 2, 1)"
            },
            "End": true
        },
    }
}
```

Deploy

### Environment

```markdown
- OS:ubuntu/WSL2
- LocalStack:latest
```

### Anything else?

The [docker image](https://hub.docker.com/r/amazon/aws-stepfunctions-local) was updated 2 days ago, which aligns with the release of the new functions.

**Comment by epabst** [comment]
I'm running into the same issue.  I'm using testcontainers with localstack 1.2.0 on macOS Monterey with DockerDesktop 4.6.1.
I'm trying to use the intrinsic function States.Base64Encode and am getting:
com.amazonaws.services.stepfunctions.model.InvalidDefinitionException: Invalid State Machine Definition: ''SCHEMA_VALIDATION_FAILED: The value for the field 'ackToken.$' must be a valid JSONPath or a valid intrinsic function call at /States/Notify/Branches[0]/States/SnsForEachEntitlement/Iterator/States/BuildSnsMessage/Parameters'' (Service: AWSStepFunctions; Status Code: 400; Error Code: InvalidDefinition; Request ID: MN7Q1I2BGL46689Y4DO9WI9MV2Y4KNB26ZAIOGLBNC0Q2YINIG83; Proxy: null)

**Comment by dtabuenc** [comment]
Any updates or work-around for this?

**Comment by wojciechwroblewski** [comment]
@thantos I believe that there's an error in your state machine syntax, I've fixed the structure:
```
{
  "StartAt": "test",
  "States": {
    "test": {
      "Type": "Pass",
      "Parameters": {
        "range.$": "States.ArrayRange(1, 2, 1)"
      },
      "End": true
    }
  }
}
```
However, this problem is not exclusive to CloudFormation, attempting to create the same machine directly via awscli will also fail:
```
aws --endpoint-url=http://localhost:4566 stepfunctions create-state-machine --name test --definition '{"StartAt": "test", "States": {"test": {"Type": "Pass", "Parameters": {"range.$": "States.ArrayRange(1, 2, 1)"}, "End": true}}}' --role-arn "arn:aws:iam::000000000000:role/test-role"
```
> An error occurred (InvalidDefinition) when calling the CreateStateMachine operation: Invalid State Machine Definition: ''SCHEMA_VALIDATION_FAILED: The value for the field 'range.$' must be a valid JSONPath or a valid intrinsic function call at /States/test/Parameters''

I've tested it with `States.UUID()` function as well - same result. AFAIK, these functions are newer additions and this may be result of using outdated  docker image amazon/aws-stepfunctions-local in version 1.7.9. Couldn't find release notes for that to find out in which version these functions were added. Also, it seems that we're stuck with this version for now:

https://github.com/localstack/localstack/blob/0abb4830714a5a9916b17b6d4a26cb10d6935e22/localstack/services/stepfunctions/packages.py#L60-L63

**Comment by thantos** [comment]
Thanks for checking @wojciechwroblewski. I fixed my syntax in the description to avoid confusion for future readers (must have hand written this example).

These intrinsics are all new. Is there a work around until your SFN implementation is ready?

**Comment by wojciechwroblewski** [comment]
> These intrinsics are all new. Is there a work around until your SFN implementation is ready?

@thantos I'm not a maintainer, I've just run into the same issue as you did and decided to investigate. Unfortunately, I couldn't find any further details, especially anything about the SFN implementation.

**Comment by thantos** [comment]
Ha... Sorry for presuming @wojciechwroblewski.

**Comment by MEPalma** [comment]
We are currently involved in the development of our own customized backend for Step Functions. You can access this feature by setting the environment variable `PROVIDER_OVERRIDE_STEPFUNCTIONS=v2`. For a detailed overview of the support provided in this initial version of Step Functions, you can refer to the notes of https://github.com/localstack/localstack/pull/8779.

As we continue to enhance both the support and stability of this service, we believe that there is a potential that it might already fulfill your requirements. We are looking forward to your feedback!
