### ISSUE TITLE
feature request: More input audio formats for Transcribe

### ISSUE THREAD

**Issue by viren-nadkarni** [localstack/localstack#6818]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

LocalStack Transcribe should accept audio formats listed [here](https://docs.aws.amazon.com/transcribe/latest/dg/how-input.html):

- AMR
- FLAC
- MP3
- MP4
- Ogg
- WebM
- WAV

Currently only single-channel PCM WAV files are supported.

### 🧑‍💻 Implementation

Use [ffmpeg](https://ffmpeg.org/) to transcode the input file. 

Refer to: https://github.com/alphacep/vosk-api/blob/master/python/vosk/transcriber/transcriber.py

**Comment by Hussain0520** [comment]
Hi, I would like to contribute to this issue. Also it would be helpful in my academics.

**Comment by janofsun** [comment]
Hi @viren-nadkarni I have already created a pull request (#6852) for this issue. Please check it out. Thanks for your support.
