### ISSUE TITLE
High memory usage with large S3 objects

### ISSUE THREAD

**Issue by GeoffreyBooth** [localstack/localstack#682]
In my project, we need to test that uploads and downloads of large (> 1GB) files work, and we’re using LocalStack to emulate S3 for our local tests. On startup, our script uploads 3GB of files (most small, a few large) into LocalStack S3, and after that its memory usage balloons:

```
CONTAINER ID  NAME        CPU %  MEM USAGE / LIMIT    MEM %   NET I/O          BLOCK I/O       PIDS
1ce5b092620d  localstack  0.71%  6.178GiB / 11.71GiB  52.75%  3.58GB / 16.3MB  102kB / 8.19kB  14
```

I have my Docker for Mac configured to allow up to 12GB used by containers, and my machine has 64GB of RAM, so it works on my machine; but my colleagues with only 16GB of RAM and 8GB allocated to Docker report Docker crashing when this starts up.

Are these uploaded S3 objects simply stored in memory? Are they never written to disk? Could they perhaps be written to disk somewhere, in a path that I can mount as a volume?

Possibly related: https://github.com/spulec/moto/issues/395, https://github.com/localstack/localstack/issues/113

**Comment by whummer** [comment]
Thanks for reporting @GeoffreyBooth . Should be fixed upstream in `moto`. 👍

**Comment by DJanyavula** [comment]
Hi, is this feature already available in localstack? I too have observed that my containers are keeping all the data in memory
