### ISSUE TITLE
feature request: AWS::CloudFront::OriginAccessControl

### ISSUE THREAD

**Issue by marcguyer** [localstack/localstack#6837]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

The OAI method is [legacy, not recommended](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-restricting-access-to-s3.html#private-content-restricting-access-to-s3-oai). The OAC method is the new hotness and enables additional features. 

https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-restricting-access-to-s3.html

**Comment by HariVamsiK** [comment]
Hi
I want to contribute on this issue. Please assign it to me. 
Thanks

**Comment by pinzon** [comment]
The implementation of this feature has just been merged to LocalStack. Please pull the latest image of LocalStack Pro.
Thank you for reporting the issue.
