### ISSUE TITLE
SNS FilterPolicy

### ISSUE THREAD

**Issue by bolsunovskyi** [localstack/localstack#684]
Hello, Does filter policy for sns subscriptions work in localstack ?

**Comment by matuszeman** [comment]
It does work since version 0.8.6 but it does not support `String.Array` attribute type it seems like #674

**Comment by stevenmusumeche** [comment]
Filtering doesn't seem to be working on 0.8.7

**Comment by mfulton26** [comment]
I see where `FilterPolicy` is queried for but I do not see where it is persisted when subscribing:

https://github.com/localstack/localstack/blob/5970a62426b0c6fbbf64f2c480fc32128f0de9f0/localstack/services/sns/sns_listener.py#L71

`do_subscribe` seems to be lacking any knowledge of `FilterPolicy`:

https://github.com/localstack/localstack/blob/5970a62426b0c6fbbf64f2c480fc32128f0de9f0/localstack/services/sns/sns_listener.py#L144-L153

**Comment by DjCedrics** [comment]
Has this issue been fixed yet? I would like to pass _FilterPolicy_ at the time when I create an SNS subscription, but the value does not get stored in subscription attributes.

`awslocal sns subscribe --topic-arn arn:aws:sns:eu-central-1:123456789012:test-topic --protocol sqs --notification-endpoint arn:aws:sqs:eu-central-1:123456789012:test-queue --attributes '{"FilterPolicy":"{\"actionType\":[{\"prefix\":\"test\"}]}"}'`

**Comment by whummer** [comment]
Thanks for reporting @bolsunovskyi @matuszeman @stevenmusumeche @mfulton26 @DjCedrics @ryan-gustafson . This should be fixed in #1760 - please give it a try with the latest version and report here if the problem persists. Thanks
