### ISSUE TITLE
feature request: CloudMap support

### ISSUE THREAD

**Issue by maciejwalkowiak** [localstack/localstack#6844]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Add [CloudMap](https://aws.amazon.com/cloud-map/) support.

### Anything else?

We're adding [CloudMap support to Spring Cloud AWS](https://github.com/awspring/spring-cloud-aws/pull/506) and currently don't find a way to test it against Localstack. Perhaps you plan to add support anytime soon or it's been decided to not support this service at all.

**Comment by Jehan-h20220012** [comment]
I want to contribute to solve this issue, please let me contribute as it would help in my acedamics and your problem will be solved.

**Comment by whummer** [comment]
Hi @maciejwalkowiak , thanks for reporting. An initial version of `servicediscovery` (Cloud Map) is already available in the Pro service (which I believe you and your team have access to). 

Here's a simple example:
```
$ awslocal servicediscovery create-http-namespace --name ns1
...
$ awslocal servicediscovery list-namespaces
{
    "Namespaces": [
        {
            "Id": "9538ce62",
            "Arn": "arn:aws:servicediscovery:us-east-1:000000000000:namespace/9538ce62",
            "Name": "ns1",
            "Type": "HTTP"
        }
    ]
}
$ awslocal servicediscovery create-service --name service1 --namespace-id 9538ce62
{
    "Service": {
        "Id": "570ea4c8",
        "Arn": "arn:aws:servicediscovery:us-east-1:000000000000:service/570ea4c8",
        "Name": "service1",
        "NamespaceId": "9538ce62",
        "CreatorRequestId": "5580a829-7c6a-4083-9c4b-73725f268473"
    }
}
```

Can you replicate these results? Please let us know if any particular functionality is missing - happy to help out and get it supported for your team. 👍 Thanks

**Comment by JehanPatwa** [comment]
Sure, I will work on it.
I request you to assign me this isssue as I have to show my instructor that I am assigned with it.
Thank You.

**Comment by Jehan-h20220012** [comment]
Sure, I will work on it.
I request you to assign me this isssue as I have to show my instructor that I am assigned with it.
Thank You.

**Comment by maciejwalkowiak** [comment]
@whummer thank you! I missed that it's listed on the https://docs.localstack.cloud/aws/feature-coverage/ (was just looking at the sidebar with services list). Will give it a try!

**Comment by ackdav** [comment]
Hello @maciejwalkowiak - did you have a chance to test it? Is there any further features around cloudmap that you would like to have? Or can we close this issue?
Thanks!

**Comment by maciejwalkowiak** [comment]
@ackdav apologies I did not in the end. Feel free to close it and in I find anything not working I'll comment here and then perhaps you will consider reopening.

**Comment by ackdav** [comment]
Will do - thank you for the prompt answer, and I hope you have a chance to try it out sometime :)
