### ISSUE TITLE
bug: Not able to finish multipart upload for a big file

### ISSUE THREAD

**Issue by TheCanay** [localstack/localstack#6845]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm trying to upload a pretty big file to my localstack s3 bucket (size of the file is 5.4 Gb). After uploading all the parts via multipat upload I'm getting the 500 error from localstack so I'm not able to complete multipart uploading for it. Also after that localstack is restarting

Here is the logs:

 2022-09-09T12:35:34.733  INFO --- [   asgi_gw_1] localstack.request.aws     : AWS s3.UploadPart => 200
localstack_main  | 2022-09-09T12:35:38.178  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS s3.UploadPart => 200
localstack_main  | 2022-09-09T12:35:40.779  INFO --- [   asgi_gw_1] localstack.request.aws     : AWS s3.UploadPart => 200
localstack_main  | 2022-09-09T12:35:43.296  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS s3.UploadPart => 200
localstack_main  | 2022-09-09T12:35:45.832  INFO --- [   asgi_gw_1] localstack.request.aws     : AWS s3.UploadPart => 200
localstack_main  | 2022-09-09T12:35:48.361  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS s3.UploadPart => 200
localstack_main  | 2022-09-09T12:35:51.237  INFO --- [   asgi_gw_1] localstack.request.aws     : AWS s3.UploadPart => 200
localstack_main  | 2022-09-09T12:35:51.952  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS s3.UploadPart => 200
localstack_main  | 2022-09-09T12:39:44.207  INFO --- [   asgi_gw_2] localstack.request.aws     : AWS s3.CompleteMultipartUpload => 500 (500)
localstack_main  | 2022-09-09T12:39:44.206  INFO --- [   asgi_gw_6] localstack.request.aws     : AWS s3.CompleteMultipartUpload => 500 (500)
localstack_main  | 2022-09-09T12:39:45.505  INFO --- [  asgi_gw_11] localstack.request.aws     : AWS s3.GetObject => 404 (NoSuchKey)
localstack_main  | 2022-09-09T12:39:45.931 ERROR --- [uest_thread)] werkzeug                   : Error on request:
localstack_main  | Traceback (most recent call last):
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/werkzeug/serving.py", line 335, in run_wsgi
localstack_main  |     execute(self.server.app)
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/werkzeug/serving.py", line 322, in execute
localstack_main  |     application_iter = app(environ, start_response)
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/moto/moto_server/werkzeug_app.py", line 240, in __call__
localstack_main  |     return backend_app(environ, start_response)
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/flask/app.py", line 2091, in __call__localstack_main  |     return self.wsgi_app(environ, start_response)
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/flask/app.py", line 2076, in wsgi_applocalstack_main  |     response = self.handle_exception(e)
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
localstack_main  |     return cors_after_request(app.make_response(f(*args, **kwargs)))
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_applocalstack_main  |     response = self.full_dispatch_request()
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/flask/app.py", line 1519, in full_dispatch_request
localstack_main  |     rv = self.handle_user_exception(e)
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
localstack_main  |     return cors_after_request(app.make_response(f(*args, **kwargs)))
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/flask/app.py", line 1517, in full_dispatch_request
localstack_main  |     rv = self.dispatch_request()
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/flask/app.py", line 1503, in dispatch_request
localstack_main  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
localstack_main  |   File "/opt/code/localstack/localstack/utils/patch.py", line 38, in proxy
localstack_main  |     return new(target, *args, **kwargs)
localstack_main  |   File "/opt/code/localstack/localstack/utils/aws/request_context.py", line 172, in convert_to_flask_response_call
localstack_main  |     return fn(*args, **kwargs)
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/moto/core/utils.py", line 127, in __call__
localstack_main  |     result = self.callback(request, request.url, dict(request.headers))
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/moto/core/utils.py", line 261, in _wrapper
localstack_main  |     response = f(*args, **kwargs)
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/moto/s3/responses.py", line 1114, in key_response
localstack_main  |     response = self._key_response(request, full_url, self.headers)
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/moto/s3/responses.py", line 1210, in _key_response
localstack_main  |     return self._key_response_post(request, body, bucket_name, query, key_name)
localstack_main  |   File "/opt/code/localstack/localstack/utils/patch.py", line 38, in proxy
localstack_main  |     return new(target, *args, **kwargs)
localstack_main  |   File "/opt/code/localstack/localstack/services/s3/s3_starter.py", line 147, in s3_key_response_postlocalstack_main  |     result = fn(request, body, bucket_name, query, key_name, *args, **kwargs)
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/moto/s3/responses.py", line 1961, in _key_response_post
localstack_main  |     multipart, value, etag = self.backend.complete_multipart_upload(
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/moto/s3/models.py", line 1920, in complete_multipart_upload
localstack_main  |     multipart = bucket.multiparts[multipart_id]
localstack_main  | KeyError: 'KQrkmRu68I1QVGfmdBorFdWNnHI2RvKYTiRCnHDZ1EApHIRW5RWtg0Q03w'
localstack_main  | 2022-09-09T12:39:45.937 ERROR --- [uest_thread)] werkzeug                   : Error on request:
localstack_main  | Traceback (most recent call last):
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/werkzeug/serving.py", line 335, in run_wsgi
localstack_main  |     execute(self.server.app)
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/werkzeug/serving.py", line 322, in execute
localstack_main  |     application_iter = app(environ, start_response)
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/moto/moto_server/werkzeug_app.py", line 240, in __call__
localstack_main  |     return backend_app(environ, start_response)
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/flask/app.py", line 2091, in __call__localstack_main  |     return self.wsgi_app(environ, start_response)
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/flask/app.py", line 2076, in wsgi_applocalstack_main  |     response = self.handle_exception(e)
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
localstack_main  |     return cors_after_request(app.make_response(f(*args, **kwargs)))
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_applocalstack_main  |     response = self.full_dispatch_request()
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/flask/app.py", line 1519, in full_dispatch_request
localstack_main  |     rv = self.handle_user_exception(e)
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
localstack_main  |     return cors_after_request(app.make_response(f(*args, **kwargs)))
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/flask/app.py", line 1517, in full_dispatch_request
localstack_main  |     rv = self.dispatch_request()
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/flask/app.py", line 1503, in dispatch_request
localstack_main  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
localstack_main  |   File "/opt/code/localstack/localstack/utils/patch.py", line 38, in proxy
localstack_main  |     return new(target, *args, **kwargs)
localstack_main  |   File "/opt/code/localstack/localstack/utils/aws/request_context.py", line 172, in convert_to_flask_response_call
localstack_main  |     return fn(*args, **kwargs)
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/moto/core/utils.py", line 127, in __call__
localstack_main  |     result = self.callback(request, request.url, dict(request.headers))
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/moto/core/utils.py", line 261, in _wrapper
localstack_main  |     response = f(*args, **kwargs)
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/moto/s3/responses.py", line 1114, in key_response
localstack_main  |     response = self._key_response(request, full_url, self.headers)
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/moto/s3/responses.py", line 1210, in _key_response
localstack_main  |     return self._key_response_post(request, body, bucket_name, query, key_name)
localstack_main  |   File "/opt/code/localstack/localstack/utils/patch.py", line 38, in proxy
localstack_main  |     return new(target, *args, **kwargs)
localstack_main  |   File "/opt/code/localstack/localstack/services/s3/s3_starter.py", line 147, in s3_key_response_postlocalstack_main  |     result = fn(request, body, bucket_name, query, key_name, *args, **kwargs)
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/moto/s3/responses.py", line 1961, in _key_response_post
localstack_main  |     multipart, value, etag = self.backend.complete_multipart_upload(
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/moto/s3/models.py", line 1920, in complete_multipart_upload
localstack_main  |     multipart = bucket.multiparts[multipart_id]
localstack_main  | KeyError: 'KQrkmRu68I1QVGfmdBorFdWNnHI2RvKYTiRCnHDZ1EApHIRW5RWtg0Q03w'
localstack_main  | 2022-09-09 12:39:50,237 INFO exited: infra (terminated by SIGKILL; not expected)
localstack_main  | 2022-09-09 12:39:51,364 INFO spawned: 'infra' with pid 832
localstack_main  | SERVICES variable is ignored if EAGER_SERVICE_LOADING=0.
localstack_main  | Persistence mode was activated using the DATA_DIR variable. DATA_DIR is deprecated and its value is ignored. The data is instead stored into /var/lib/localstack/state in the LocalStack volume.
localstack_main  | 2022-09-09 12:39:53,120 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

My docker-compose.yml:
version: '3'

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack:latest
    network_mode: bridge

    ports:
      - "127.0.0.1:53:53"
      - "127.0.0.1:53:53/udp"
      - "127.0.0.1:443:443"
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4571:4571"

    environment:
      - SERVICES=s3, s3api, cloudwatch, logs, lambda
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEFAULT_REGION=eu-west-1
      - AWS_ACCESS_KEY_ID=foobar
      - AWS_SECRET_ACCESS_KEY=foobaraccess

    
    volumes:
      - "aws-volume:/tmp/localstack"
      - "aws-sock:/var/run/docker.sock"
      - "aws-bin:/docker-entrypoint-initaws.d"
      

volumes:
  aws-volume:
  aws-sock:
  aws-bin:

### Expected Behavior

Multipart upload will be finished.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

docker-compose up

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

aws --endpoint-url=http://127.0.0.1:4566 s3 mb s3://localdev

uploading file with Java SDK. Files with size near to 1.6 gb are uploading fine, but bigger file with size 5.4 does not uploading

### Environment

```markdown
- OS:windows 10
- LocalStack: latest
```

**Comment by yaduraj** [comment]
Any update on this?

**Comment by TheCanay** [comment]
Hello! Well yes, but actually no. The issue was reproducing because of running out of RAM. So I don't have a solution for this case.

**Comment by bentsku** [comment]
Hello @TheCanay and thanks for your report! We've been working on an experimental S3 provider, allowing to not load the full object in memory, also when completing a `MultipartUpload`. This is still experimental and will have issue if you have `PERSISTENCE` enabled.

We're also working on a revamped S3 implementation, which would support it by default, which could be available in the next months.

The PR just has been merged, so the image should be available in a couple of hours. Could you please then run `docker pull localstack/locastack:latest` and start localstack with the following environment variable: `PROVIDER_OVERRIDE_S3=stream` and see if that solves your issue? 

\cc @ashin-czi
