### ISSUE TITLE
feature request: alias records in route53

### ISSUE THREAD

**Issue by dominikschubert** [localstack/localstack#6847]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Route53 alias A-records are similar to normal CNAME records in the DNS spec but can be used in top-level domains such as `example.com` and are usually used to point towards AWS-service generated domains such as API Gateway REST APIs, CloudFront distributions or ALBs.

 

### 🧑‍💻 Implementation

This will need tighter coupling between the DNS server and route53 where route53/the dns server needs to actually communicate with our other AWS services to query the IPs it needs to hand out to the requester.

### Anything else?

* https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/resource-record-sets-choosing-alias-non-alias.html
* https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-aliastarget.html

**Comment by pacarvalho** [comment]
Was this implemented? We are planning to use LocalStack to test our AWS integration locally to ease development and this would be a requirement.

**Comment by steffyP** [comment]
Hi @pacarvalho,

a simplified implementation of alias targets is now available in the `latest` image for LocalStack Pro.

Resource records in route53 using the following pattern can now be resolved:
```
{
            "Name": "my.test.",
            "Type": "A",
            "AliasTarget": {
                "HostedZoneId": "Z2FDTNDATAQYW2",
                "DNSName": "http://aab1b20cd3e.cloudfront.net/",
                "EvaluateTargetHealth": true
            }
}
```

When trying to resolve `my.test` the IP address of the resolved address for `DNSName` will be returned.

It has the following limitations:
- There is no check if the `DNSName` is a valid or an existing target (no validation if API Gateway, Load Balancer, Cloudfront etc. really exists).
- `EvaluateTargetHealth` is ignored


If you experience any issues or have further requirements, please open a new ticket describing your use-case in detail.
