### ISSUE TITLE
Degree of CloudFormation simulation

### ISSUE THREAD

**Issue by niron1** [localstack/localstack#685]
Hi, does LocalStack use the same **Amazon Linux** CloudFormation stack for executing Lambda functions, or is it using the local OS for running them? @nicwolff #thanks

**Comment by whummer** [comment]
Hi @niron1 - LocalStack has different modes of execution (see `LAMBDA_EXECUTOR` in the README)

By default, we use the Amazon Linux stack for executing. Specifically, we're using Docker containers whose images are based on https://github.com/lambci/docker-lambda
