### ISSUE TITLE
bug: Unknown parameter in input: "Serial", must be one of: UserName

### ISSUE THREAD

**Issue by aazbeltran** [localstack/localstack#6861]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Recently was merged the next feature: https://github.com/localstack/localstack/issues/6425

This is good but an issue was introduced, since the [create_access_key](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/iam.html#IAM.Client.create_access_key) boto function only allows `UserName` argument, and if you're passing the Status & Serial, will cause the next error: `Unknown parameter in input: "Serial", must be one of: UserName`.

### Expected Behavior

It should work if you pass all [parameters](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-iam-accesskey.html) allowed.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

1. Create a cloudformation stack
2. Add an access key with serial and status

### Environment

```markdown
- OS: Docker
- LocalStack: latest
```

**Comment by pinzon** [comment]
The solution has been merged. Please pull the latest image of LocalStack.
