### ISSUE TITLE
bug: <API GW V2 sets or removes requestContext.authorizer.jwt.scopes

### ISSUE THREAD

**Issue by hectorcanto** [localstack/localstack#6864]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Claims has scope, but scopes is `null`, in AWS, it is not.
```
{
  'authorizer': {'jwt': {'authorizer_type': 'jwt',
                         'claims': {'aud': 'example.com/endpoint',
                                    'azp': 'client_id',
                                    'exp': 123456,
                                    'gty': 'client-credentials',
                                    'iat': 123456,
                                    'iss': 'auth0',
                                    'scope': ['some_scope']
                                    },
                         'context': {},
                         'identity': {'cognitoIdentityId': None,
                                      'cognitoIdentityPoolId': None},
                         'scopes': None}},
  'domainName': 'some_hash.execute-api.localhost.localstack.cloud',
}
```

### Expected Behavior

Scopes has some of the scopes listed  in claims
```
{
  'authorizer': {'jwt': {'authorizer_type': 'jwt',
                         'claims': {'aud': 'example.com/endpoint',
                                    'azp': 'client_id',
                                    'exp': 123456,
                                    'gty': 'client-credentials',
                                    'iat': 123456,
                                    'iss': 'auth0',
                                    'scope': ['some_scope']
                                    },
                         'context': {},
                         'identity': {'cognitoIdentityId': None,
                                      'cognitoIdentityPoolId': None},
                         'scopes': None}},
  'domainName': 'some_hash.execute-api.localhost.localstack.cloud',
}
```

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker-compose up -d

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```
awslocal acm request-certificate --domain-name api.local.citnow.com | jq '.CertificateArn' | xargs -n 1 -I certificate awslocal apigatewayv2 create-domain-name
```

### Environment

```markdown
- OS: Ubuntu 22.04
- LocalStack: latest (12 sept 2022), tried older ones too
```

### Anything else?

We are parsing the API GW V2 event with AWS lambda powertools and it expects the Scopes to be a list of string as you can see in [this piece code](https://github.com/awslabs/aws-lambda-powertools-python/blob/v1.29.0/aws_lambda_powertools/utilities/parser/models/apigwv2.py#L28).

Anyway, real API GW has it filled, so it would be nice to mimic it.

Thanks for the assistance and great tool.

**Comment by whummer** [comment]
Thanks for reporting @hectorcanto . We have pushed a couple of changes that should (hopefully) resolve this issue. Can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists.. Thanks!

**Comment by whummer** [comment]
Closing as resolved - please let us know if there are any other issues. Thanks!
