### ISSUE TITLE
Local stack is not able to mock/create lambda /opt directory

### ISSUE THREAD

**Issue by jatinmehrotra** [localstack/localstack#6876]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have a jest test case which tried to read file from  this path `/opt/nodejs/node_modules/books/${this.httpConfig.book}.sdb`, however test case is failed due to fact that localstack does not have this path `[Error: ENOENT: no such file or directory, open '/opt/nodejs/node_modules/books/2px(%fcBXLyo_diff.sdb']`
```

await axios.put(
      response.data.upload_url.whole_book,
      fs.readFileSync(
        `/opt/nodejs/node_modules/books/${this.httpConfig.book}.sdb`
      ),
      {
        headers: {
          'Content-Type': 'application/zip',
        },
      }
    )
```

test case 

```
describe('fullfill', () => {
    describe('When everything is ok', () => {
      test('The method should complete expectedly', async () => {
        jest.spyOn(axios, 'request').mockResolvedValueOnce({
          data: {
            upload_url: {
              whole_book: chance.string(),
            },
          },
        })
        jest.spyOn(axios, 'put').mockResolvedValueOnce({})
        await expect(driver.fullfill(chance.string())).resolves.toBeUndefined()
      })
    })
  })
```

### Expected Behavior

Test case should have been passed.

### How are you starting LocalStack?

With a `docker run` command

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    npm run docker:up

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    npm run test

### Environment

```markdown
- OS: macOS
- LocalStack:
```

**Comment by dfangl** [comment]
Hi! On the latest LocalStack image, this should be fixed in the new Lambda provider. Please try it by setting `PROVIDER_OVERRIDE_LAMBDA=asf` (until it is the default).
Layers should now be correctly unpacked in /opt.

**Comment by dfangl** [comment]
Will close this now as the new provider should have all the layers correctly in /opt.
