### ISSUE TITLE
feature request: implement 'appconfigdata' 

### ISSUE THREAD

**Issue by oliverbrixel** [localstack/localstack#6891]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

I would like to use 'appconfigdata' as described here https://awscli.amazonaws.com/v2/documentation/api/latest/reference/appconfigdata/index.html, so that we can test feature flags locally with localstack.

Before the useage 'appconfigdata' I store the data via 
```awslocal appconfig create-hosted-configuration-version ...```

and deploy the configuration via

```awslocal appconfig start-deployment ...```

**Comment by gooftroop** [comment]
[Pro] +1 for this request

**Comment by mickjmason** [comment]
+1

**Comment by mrjpierce** [comment]
+ 1

**Comment by ackdav** [comment]
Hello @oliverbrixel - thanks for the report! 
I'm not deeply familiar with appconfig, but LocalStack does have some coverage, see:
- docs: https://docs.localstack.cloud/user-guide/aws/appconfig/
- coverage: https://docs.localstack.cloud/references/coverage/coverage_appconfig/

The coverage includes the operations you mentioned (`CreateHostedConfigurationVersion` & `StartDeployment`). Would this coverage already fulfill this feature request, or could you specify more what you're missing from LocalStack side? (specific operations / parity / ...)
Thanks!

**Comment by whummer** [comment]
Hi again, quick update @oliverbrixel @mrjpierce @mickjmason - we have now pushed an initial implementation of the `appconfigdata` service. When you get a chance, can you please pull the latest Pro image and give it another try? Please let us know if there are any questions or issues.. Thanks!
