### ISSUE TITLE
[Pro] feature request: add support for AppConfig (cdk)

### ISSUE THREAD

**Issue by gooftroop** [localstack/localstack#6892]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

It appears that AppConfig is not supported for cdk and is a necessary resource for our CI/CD strategy. Would it be possible to have supported added?

### Anything else?

On the latest localstack docker image I'm getting errors like `Unexpected resource type AppConfig::Application`.

**Comment by gooftroop** [comment]
Wanted to see if there was an update or plan for this?

**Comment by gooftroop** [comment]
Is there any update on this? We're currently mocking AppConfig for testing but we do need to fully start integrating app config

**Comment by pinzon** [comment]
The PR that adds the CFn models for the AppConfig service is now in review :+1:

**Comment by gooftroop** [comment]
awesome - thank you!

**Comment by pinzon** [comment]
Hi @gooftroop, the PR has been merged, make sure to download the lastest image version.
Thanks for reporting this issue.
