### ISSUE TITLE
bug: lamba invoke payload is throwing error "The payload is not JSON" using url-connection-client

### ISSUE THREAD

**Issue by cpsinghal** [localstack/localstack#6905]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

localstack version >=1.0.0 lamba invoke payload is throwing error "The payload is not JSON" using url-connection-client but working fine either with apache client or setting LEGACY_EDGE_PROXY=1.

Error
`The payload is not JSON: %7B%22envName%22%3A+%22TEST_ENV%22%7D= (Service: Lambda, Status Code: 415, Request ID: null)`
payload is adding additional `=` operator at end

### Expected Behavior

With url-connection-client also it should be working

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

Java invoke code
`var client = LambdaClient.builder()
                .credentialsProvider(StaticCredentialsProvider.create(AwsBasicCredentials.create("dummy", "dummy")))
                .region(Region.AP_SOUTH_1)
                .endpointOverride(URI.create("http://localhost:4566"))
                .httpClient(UrlConnectionHttpClient.builder().build())
                .build();
        final var str = "{\"envName\": \"TEST_ENV\"}";
        final var invokeRequest = InvokeRequest.builder()
                .functionName("arn:aws:lambda:ap-south-1:000000000000:function:environment-test-lambda")
                .payload(SdkBytes.fromUtf8String(str))
                .build();

        final var res = client.invoke(invokeRequest);
        String value = res.payload().asUtf8String() ;
        System.out.println(value);`

SDK dependency
`<dependency>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>url-connection-client</artifactId>
            <version>2.17.265</version>
        </dependency>
        <dependency>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>lambda</artifactId>
            <version>2.17.265</version>
                <exclusions>
                    
                    <exclusion>
                        <groupId>software.amazon.awssdk</groupId>
                        <artifactId>apache-client</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>software.amazon.awssdk</groupId>
                        <artifactId>netty-nio-client</artifactId>
                    </exclusion>
                </exclusions>
        </dependency>`

### Environment

```markdown
- OS:
- LocalStack: 1.1.0
```

**Comment by cpsinghal** [comment]
Any update on this?

**Comment by HarshCasper** [comment]
Hi — Can you try using our all-new ASF provider by setting `PROVIDER_OVERRIDE_lambda=asf`? ASF is our new and more stable provider, and currently the `old` provider is loaded by default.
