### ISSUE TITLE
feature request: Appsync HTTP Datasource

### ISSUE THREAD

**Issue by daverin** [localstack/localstack#6910]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

When attempting to use an http datasource in appsync I get the following error: `Unsupported AppSync GraphQL data source type: HTTP`

This feature is useful to bind a graphql endpoint to REST based services. 

PS: Would also be great to know the limitations of Localstack services upfront in the documentation. I had to manually go through an entire setup to figure out that localstack doesn't support my usecase.

**Comment by whummer** [comment]
Hi @daverin , thanks for reporting. We have now added initial support for HTTP resolvers / data sources in AppSync - can you please pull the `latest` Docker image and give it another try? Please let us know if the feature works for you, or if there are any issues.. Thanks!
