### ISSUE TITLE
feature request: API Gateway support for custom domain names 

### ISSUE THREAD

**Issue by calvernaz** [localstack/localstack#6926]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Custom domain names are simpler and more intuitive URLs that you can provide to your API users. With custom domain names, you can set up your API's hostname, and choose a base path (for example, myservice) to map the alternative URL to your API.

https://docs.aws.amazon.com/apigateway/latest/developerguide/how-to-custom-domains.html

**Comment by davecardwell** [comment]
@calvernaz is this simply not being implemented yet the cause of #7288? Sorry, I missed this the first time I searched.

**Comment by calvernaz** [comment]
> @calvernaz is this simply not being implemented yet the cause of #7288? Sorry, I missed this the first time I searched.

Hi @davecardwell no worries, this has been implemented since then, there is an example [here](https://github.com/localstack/localstack-terraform-samples/tree/master/apigateway-custom-domain) on how to configure and call the custom domain.
