### ISSUE TITLE
feature request: API Gateway improve support to OpenAPI import (swagger, 3.0)

### ISSUE THREAD

**Issue by calvernaz** [localstack/localstack#6932]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Localstack supports the import of a subset of OpenAPI specifications (Swagger, OpenAPI 3.0). 

- Extend support for Swagger and OpenAPI 3.0
- Separate Swagger from OpenAPI 3.0 code for maintenance ease

**Comment by davecardwell** [comment]
I believe this parity could still be improved here?

**Comment by davecardwell** [comment]
I think there is still work to do here so commenting to keep alive.

**Comment by bentsku** [comment]
Hello @davecardwell! Sure, the surface of API Gateway is massive, any pointers to something in particular that would need some work or where you would have issues?
