### ISSUE TITLE
feature request: SES CloneReceiptRuleSet

### ISSUE THREAD

**Issue by viren-nadkarni** [localstack/localstack#6934]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Implement the `CloneReceiptRuleSet` operation for SES.

https://docs.aws.amazon.com/ses/latest/APIReference/API_CloneReceiptRuleSet.html

**Comment by raunaqpahwa** [comment]
Hey, I'd like to work on this. @viren-nadkarni Can you guide me a bit?

**Comment by HarshCasper** [comment]
Hi @raunaqpahwa — Can you please let us know if you have setup LocalStack on your local machine and ran some examples? You can refer to the following [video explaining the development setup](https://youtu.be/XHLBy6VKuCM) and the [developer guide](https://docs.localstack.cloud/developer-guide/) to get started.
