### ISSUE TITLE
Cant install on centos8

### ISSUE THREAD

**Issue by eyekay234** [localstack/localstack#6948]
I tired installing using pip3 install localstack and came across this error message that halts the process

 Using cached https://files.pythonhosted.org/packages/59/74/7d12a5be66bfd5836788005f5d3dcb5eed2c383341931947347b0b8b169a/plux-1.3.1-py3-none-any.whl
Collecting cachetools~=5.0.0 (from localstack)
  Could not find a version that satisfies the requirement cachetools~=5.0.0 (from localstack) (from versions: 0.0.0, 0.1.0, 0.2.0, 0.3.0, 0.3.1, 0.4.0, 0.5.0, 0.5.1, 0.6.0, 0.7.0, 0.7.1, 0.8.0, 0.8.1, 0.8.2, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.1.6, 2.0.0, 2.0.1, 2.1.0, 3.0.0, 3.1.0, 3.1.1, 4.0.0, 4.1.0, 4.1.1, 4.2.0, 4.2.1, 4.2.2, 4.2.3, 4.2.4)
No matching distribution found for cachetools~=5.0.0 (from localstack)

How i do resolve this?

Thanks

**Comment by dfangl** [comment]
Hi!
Cachetools 5.0.0 does not support python 3.6 or lower anymore, which is why you cannot install the CLI.
Please upgrade your python version, as python 3.6 also is not supported by LocalStack anymore.

**Comment by eyekay234** [comment]
Thanks a lot @dfangl

**Comment by eyekay234** [comment]
@dfangl i still ran into the following issues below:

 ERROR: Command errored out with exit status 1:
   command: /bin/python3.6 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-qq2y8eux/localstack_ec00bef3db8a4d2589ff0ebb03575b2c/setup.py'"'"'; __file__='"'"'/tmp/pip-install-qq2y8eux/localstack_ec00bef3db8a4d2589ff0ebb03575b2c/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-bsg9wjma
       cwd: /tmp/pip-install-qq2y8eux/localstack_ec00bef3db8a4d2589ff0ebb03575b2c/
  Complete output (23 lines):
  running egg_info
  creating /tmp/pip-pip-egg-info-bsg9wjma/localstack.egg-info
  /usr/lib64/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'custom_headers'
    warnings.warn(msg)
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-qq2y8eux/localstack_ec00bef3db8a4d2589ff0ebb03575b2c/setup.py", line 101, in <module>
      "Topic :: Software Development :: Testing",
    File "/usr/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib64/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib64/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.6/site-packages/setuptools/command/egg_info.py", line 270, in run
      writer = ep.resolve()
    File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in resolve
      module = __import__(self.module_name, fromlist=['__name__'], level=0)
    File "/home/sotecorp/.local/lib/python3.6/site-packages/plugin/setuptools.py", line 9, in <module>
      from setuptools.command.egg_info import InfoCommon, write_entries
  ImportError: cannot import name 'InfoCommon'
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/19/46/7bdb68f31a8561d38d8d6ee473300f1b1d7ddb680c90b78b9f63bab28adb/localstack-0.1.5.tar.gz#sha256=754b1ee5490862aae72173cb91e0d2c442dcb06c0b94a2a829ff722f8d95a75d (from https://pypi.org/simple/localstack/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Cannot install localstack==0.12.15, localstack==0.12.15.1, localstack==0.12.16, localstack==0.12.16.1, localstack==0.12.16.2, localstack==0.12.17, localstack==0.12.17.1, localstack==0.12.17.2, localstack==0.12.17.3, localstack==0.12.17.4, localstack==0.12.17.5, localstack==0.12.18, localstack==0.12.18.1, localstack==0.12.18.2, localstack==0.12.18.3, localstack==0.12.18.4, localstack==0.12.18.5, localstack==0.12.19, localstack==0.12.19.1, localstack==0.12.19.2, localstack==0.12.19.3, localstack==0.12.19.4, localstack==0.12.20, localstack==0.13.0, localstack==0.13.0.1, localstack==0.13.0.10, localstack==0.13.0.11, localstack==0.13.0.2, localstack==0.13.0.3, localstack==0.13.0.4, localstack==0.13.0.5, localstack==0.13.0.6, localstack==0.13.0.7, localstack==0.13.0.8, localstack==0.13.0.9, localstack==0.13.1, localstack==0.13.1.1, localstack==0.13.1.2, localstack==0.13.2, localstack==0.13.2.1, localstack==0.13.3, localstack==0.13.3.1, localstack==0.13.3.2, localstack==0.13.3.3, localstack==0.13.3.4, localstack==0.13.3.5, localstack==0.13.3.6, localstack==0.14.0, localstack==0.14.0.1, localstack==0.14.0.10, localstack==0.14.0.2, localstack==0.14.0.3, localstack==0.14.0.4, localstack==0.14.0.5, localstack==0.14.0.6, localstack==0.14.0.7, localstack==0.14.0.8, localstack==0.14.0.9, localstack==0.14.1, localstack==0.14.1.1, localstack==0.14.1.2, localstack==0.14.1.3, localstack==0.14.2, localstack==0.14.2.1, localstack==0.14.2.10, localstack==0.14.2.11, localstack==0.14.2.2, localstack==0.14.2.3, localstack==0.14.2.4, localstack==0.14.2.5, localstack==0.14.2.6, localstack==0.14.2.7, localstack==0.14.2.8, localstack==0.14.2.9, localstack==0.14.3, localstack==0.14.3.1, localstack==0.14.3.2, localstack==0.14.3.3, localstack==0.14.3.4, localstack==0.14.3.5, localstack==0.14.3.6, localstack==0.14.4, localstack==0.14.5, localstack==1.0.0, localstack==1.0.1, localstack==1.0.2, localstack==1.0.3, localstack==1.0.4 and localstack==1.1.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    localstack 1.1.0 depends on cachetools~=5.0.0
    localstack 1.0.4 depends on cachetools~=5.0.0
    localstack 1.0.3 depends on cachetools~=5.0.0
    localstack 1.0.2 depends on cachetools~=5.0.0
    localstack 1.0.1 depends on cachetools~=5.0.0
    localstack 1.0.0 depends on cachetools~=5.0.0
    localstack 0.14.5 depends on localstack-client>=1.31
    localstack 0.14.4 depends on localstack-client>=1.31
    localstack 0.14.3.6 depends on localstack-client>=1.31
    localstack 0.14.3.5 depends on localstack-client>=1.31
    localstack 0.14.3.4 depends on localstack-client>=1.31
    localstack 0.14.3.3 depends on localstack-client>=1.31
    localstack 0.14.3.2 depends on localstack-client>=1.31
    localstack 0.14.3.1 depends on localstack-client>=1.31
    localstack 0.14.3 depends on localstack-client>=1.31
    localstack 0.14.2.11 depends on localstack-client>=1.31
    localstack 0.14.2.10 depends on localstack-client>=1.31
    localstack 0.14.2.9 depends on localstack-client>=1.31
    localstack 0.14.2.8 depends on localstack-client>=1.31
    localstack 0.14.2.7 depends on localstack-client>=1.31
    localstack 0.14.2.6 depends on localstack-client>=1.31
    localstack 0.14.2.5 depends on localstack-client>=1.31
    localstack 0.14.2.4 depends on localstack-client>=1.31
    localstack 0.14.2.3 depends on localstack-client>=1.31
    localstack 0.14.2.2 depends on localstack-client>=1.31
    localstack 0.14.2.1 depends on localstack-client>=1.31
    localstack 0.14.2 depends on localstack-client>=1.31
    localstack 0.14.1.3 depends on localstack-client>=1.31
    localstack 0.14.1.2 depends on localstack-client>=1.31
    localstack 0.14.1.1 depends on localstack-client>=1.31
    localstack 0.14.1 depends on localstack-client>=1.31
    localstack 0.14.0.10 depends on localstack-client>=1.31
    localstack 0.14.0.9 depends on localstack-client>=1.31
    localstack 0.14.0.8 depends on localstack-client>=1.31
    localstack 0.14.0.7 depends on localstack-client>=1.31
    localstack 0.14.0.6 depends on localstack-client>=1.31
    localstack 0.14.0.5 depends on localstack-client>=1.31
    localstack 0.14.0.4 depends on localstack-client>=1.31
    localstack 0.14.0.3 depends on localstack-client>=1.31
    localstack 0.14.0.2 depends on localstack-client>=1.31
    localstack 0.14.0.1 depends on localstack-client>=1.31
    localstack 0.14.0 depends on localstack-client>=1.31
    localstack 0.13.3.6 depends on localstack-client>=1.31
    localstack 0.13.3.5 depends on localstack-client>=1.31
    localstack 0.13.3.4 depends on localstack-client>=1.31
    localstack 0.13.3.3 depends on localstack-client>=1.31
    localstack 0.13.3.2 depends on localstack-client>=1.31
    localstack 0.13.3.1 depends on localstack-client>=1.31
    localstack 0.13.3 depends on localstack-client>=1.28
    localstack 0.13.2.1 depends on localstack-client>=1.28
    localstack 0.13.2 depends on localstack-client>=1.28
    localstack 0.13.1.2 depends on localstack-client>=1.28
    localstack 0.13.1.1 depends on localstack-client>=1.28
    localstack 0.13.1 depends on localstack-client>=1.28
    localstack 0.13.0.11 depends on localstack-client>=1.28
    localstack 0.13.0.10 depends on localstack-client>=1.24
    localstack 0.13.0.9 depends on localstack-client>=1.24
    localstack 0.13.0.8 depends on localstack-client>=1.24
    localstack 0.13.0.7 depends on localstack-client>=1.24
    localstack 0.13.0.6 depends on localstack-client>=1.24
    localstack 0.13.0.5 depends on localstack-client>=1.24
    localstack 0.13.0.4 depends on localstack-client>=1.24
    localstack 0.13.0.3 depends on localstack-client>=1.24
    localstack 0.13.0.2 depends on localstack-client>=1.24
    localstack 0.13.0.1 depends on localstack-client>=1.24
    localstack 0.13.0 depends on localstack-client>=1.24
    localstack 0.12.20 depends on localstack-client>=1.24
    localstack 0.12.19.4 depends on localstack-client>=1.24
    localstack 0.12.19.3 depends on localstack-client>=1.24
    localstack 0.12.19.2 depends on localstack-client>=1.24
    localstack 0.12.19.1 depends on localstack-client>=1.24
    localstack 0.12.19 depends on localstack-client>=1.24
    localstack 0.12.18.5 depends on localstack-client>=1.24
    localstack 0.12.18.4 depends on localstack-client>=1.24
    localstack 0.12.18.3 depends on localstack-client>=1.24
    localstack 0.12.18.2 depends on localstack-client>=1.24
    localstack 0.12.18.1 depends on localstack-client>=1.24
    localstack 0.12.18 depends on localstack-client>=1.24
    localstack 0.12.17.5 depends on docopt>=0.6.2
    localstack 0.12.17.4 depends on docopt>=0.6.2
    localstack 0.12.17.3 depends on docopt>=0.6.2
    localstack 0.12.17.2 depends on docopt>=0.6.2
    localstack 0.12.17.1 depends on docopt>=0.6.2
    localstack 0.12.17 depends on docopt>=0.6.2
    localstack 0.12.16.2 depends on docopt>=0.6.2
    localstack 0.12.16.1 depends on docopt>=0.6.2
    localstack 0.12.16 depends on docopt>=0.6.2
    localstack 0.12.15.1 depends on docopt>=0.6.2
    localstack 0.12.15 depends on docopt>=0.6.2

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies

**Comment by dfangl** [comment]
You can try installing a later localstack version, but in the end, you might encounter significant issues when staying on python3.6.
We have alternative ways of starting LocalStack, like directly via docker or docker-compose, please check out our docs here: https://docs.localstack.cloud/get-started/#docker-compose 
If you need explicit CLI functionality, please upgrade to at least python3.7, for example using pyenv, a great tool for managing multiple python versions on your system: https://github.com/pyenv/pyenv

**Comment by dfangl** [comment]
Closing this as EOL python versions are not supported by latest localstack pypi packages.
