### ISSUE TITLE
bug: Invoking Golang-based Lambda return an error

### ISSUE THREAD

**Issue by HarshCasper** [localstack/localstack#6967]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have the following code available in my `main.go`:

```go
package main

import "github.com/aws/aws-lambda-go/lambda"

func handleRequest() (string, error) {
	return "Hello from Go!", nil
}
func main() {
	lambda.Start(handleRequest)
}
```

It is built and packaged in the following manner:

```sh
$ go build main.go 
$ zip function.zip main
```

The Lambda is created and invoked in the following manner:

```sh
$ awslocal lambda create-function \
    --function-name lambda-example \
    --zip-file fileb://function.zip \
    --handler main \
    --runtime go1.x \
    --role cool-stacklifter

$ awslocal lambda invoke \
    --function-name lambda-example \
    --invocation-type "RequestResponse" \
    response.txt
```

The following error is returned: 

```txt
{"errorMessage":"RequestId: 992acf03-4612-1f9d-de37-de7be92961b5 Error: fork/exec /var/task/hello: exec format error","errorType":"exitError"}
```

### Expected Behavior

A new file called “response.txt” should be created in the directory. Reading the file, should contain “Hello from Go!”.

### How are you starting LocalStack?

With the `localstack` script

### Steps To Reproduce

Mentioned in `Current Behavior`

### Environment

```markdown
- OS: macOS 12.3
- LocalStack: 1.1.0
```

**Comment by ChandanChainani** [comment]
@HarshCasper working correctly in version `1.2.0`

**Comment by HarshCasper** [comment]
> @HarshCasper tested and verified working correctly in version `1.2.0`

Thanks! Will test it out today.

**Comment by dfangl** [comment]
This can happen if you build your go binary for arm64, but the docker images will be run in rosetta as amd64.
Please build the go binaries for amd64 for now!
