### ISSUE TITLE
guy, i have a problem installing a virtual environment

### ISSUE THREAD

**Issue by Michael-Azali2000** [localstack/localstack#697]
I'm trying to install a virtual environment on my mac using terminal, however when I write `sudo pip install virtualenv`, it gives me the following response:

```
_The directory '/Users/michaelazali/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/michaelazali/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting virtualenv
Trace/BPT trap: 5_
```
And afterwards when I type:` _virtualenv (name)_`
it responds with:
`_-bash: virtualenv: command not found_`
 can anyone help me figure out what the problem here is?

**Comment by whummer** [comment]
Hi @Michael-Azali2000 - I'm going to close this issue as unrelated to LocalStack. Please consult other resources (google, stackoverflow, etc) for general help on how to set up a virtual Python environment. You may also find some help by searching previous tickets in this repo. Thanks for your understanding.
