### ISSUE TITLE
bug: LocalStack CLI can't select profile using --profile prompt

### ISSUE THREAD

**Issue by MarcelStranak** [localstack/localstack#6981]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently, when you run, for example, ` localstack --profile=dev config show` it does not change the profile from `default` to `dev`.

### Expected Behavior

Running `localstack --profile=dev config show` should provide same results as running `CONFIG_PROFILE=dev localstack config show`

### How are you starting LocalStack?

With the `localstack` script

###

Follow steps mentioned here: https://docs.localstack.cloud/localstack/configuration/#profiles
- Create `dev.env` file under `~/.localstack`
- Add a line like `LAMBDA_CONTAINER_REGISTRY="dev.env file"` to easily see the difference
- run `localstack --profile=dev config show` 
- run `CONFIG_PROFILE=dev localstack config show`
- see the difference

### Environment

```markdown
- OS: Ubuntu 20.04
- LocalStack CLI: 1.1.0
```

**Comment by bentsku** [comment]
Fixed by #7329 (will need a release for it to be properly available in pip?)

**Comment by thrau** [comment]
Thanks for closing @bentsku , didn't see this issue! It's already part of 1.3.1 :-)
