### ISSUE TITLE
bug: QLDB: Incorrect number of bindings supplied.

### ISSUE THREAD

**Issue by arvenil** [localstack/localstack#7002]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Doesn't work:
```go
func update(txn qldbdriver.Transaction, accountID string, amount decimal.Decimal) error {
	const query = `
UPDATE account
   BY  account_id
  SET  balance    = balance + ?
WHERE  account_id = ?
`

	_, err := txn.Execute(query, amount, accountID)
	if err != nil {
		return fmt.Errorf("update balance: %w", err)
	}

	return nil
}
```

I get an error:
> operation error QLDB Session: SendCommand, https response error StatusCode: 400, RequestID: KVN2C4R2UTQE7WOO07VTZWI484FS4HYT8YRFP1OQ3OB5CHAM2ETC, BadRequestException: Unable to execute query: Incorrect number of bindings supplied. The current statement uses 1, and there are 2 supplied

Works:
```go
func update(txn qldbdriver.Transaction, accountID string, amount decimal.Decimal) error {
	const query = `
UPDATE account
   BY  account_id
  SET  balance    = ?
WHERE  account_id = ?
`

	_, err := txn.Execute(query, amount, accountID)
	if err != nil {
		return fmt.Errorf("update balance: %w", err)
	}

	return nil
}
```

### Expected Behavior

Below query works with real QLDB instance. It should work as well with localstack instance.
```sql
UPDATE account
   BY  account_id
  SET  balance    = balance + ?
WHERE  account_id = ?
```

### How are you starting LocalStack?

https://www.testcontainers.org/modules/localstack/ but with go.

### Steps To Reproduce

```go
func update(txn qldbdriver.Transaction, accountID string, amount decimal.Decimal) error {
	const query = `
UPDATE account
   BY  account_id
  SET  balance    = ?
WHERE  account_id = ?
`

	_, err := txn.Execute(query, amount, accountID)
	if err != nil {
		return fmt.Errorf("update balance: %w", err)
	}

	return nil
}
```

### Environment

```markdown
- OS: macOS 12.6
- LocalStack: localstack/localstack:latest
```

**Comment by whummer** [comment]
Hi @arvenil , thanks for reporting. We've been able to replicate this issue, and are currently working on a fix. We'll ping you soon with an update here. 👍

**Comment by whummer** [comment]
Hi again, quick update - we have now pushed a couple of enhancements for QLDB that should (hopefully) get this issue resolved. Can you please pull the `latest` Docker image and give it another try? Thanks!

**Comment by arvenil** [comment]
In the meantime my trial key expired :) I just gave it second chance and it works! Thanks for the fixes!
