### ISSUE TITLE
API Gateway re-deployment stucks while updating code

### ISSUE THREAD

**Issue by elbazon** [localstack/localstack#7013]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Once I attempt to update an existing API gateway deployment resource, it gets stuck on "Still modifying".
"aws_api_gateway_deployment.rest-api-gw-stage-deployment: Still modifying..."

### Expected Behavior

Should update accordingly with no issues.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

Raise localstack.
Create resources using terraform which contains API gateway resources and deployments.
Once done, update your API gateway - and apply.
You will see that it will continue running.

### Environment

```markdown
- OS: macOS Monterey v12.6
- LocalStack: latest
```

### Anything else?

As a paying customer for multiple user subscriptions - it is very frustrating that we cannot work properly!
We need to literally take localstack done and recreate everything in order to resume our work!

Please fix this!

**Comment by thrau** [comment]
hi @elbazon, sorry you're having issues with your application and localstack.
please help us reproduce the issue by providing the terraform files you are trying to deploy. if you are pro user you can also contact our customer support in slack and share it there.

**Comment by elbazon** [comment]
It seems that this issue has been resolved in the latest localstack version.
However, a new issue has been raised:
"
`╷
│ Error: Provider produced inconsistent final plan
│
│ When expanding the plan for
│ module.notifications-service.aws_api_gateway_deployment.rest-api-gw-stage-deployment
│ to include new values learned so far during apply, provider
│ "registry.terraform.io/hashicorp/aws" produced an invalid new value for
│ .triggers["redeployment"]: was
│ cty.StringVal("79fa7ded497f3ae563175108ec16273945a6e993"), but now
│ cty.StringVal("a28d2549c26ec3ce8bba48da25efec9616eda283").
│
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
╵`

We've currently disabled the redeploy trigger in our infrastructure in order to continue working.
You can replicate this matter by:
1. Create a rest-api resources (including a deployment stage).
2. In the deployment stage, add a trigger for redeploying.

**Comment by calvernaz** [comment]
Seems like a provider's issue. If this still happening provide us a sample and the terraform provider version 👍
