### ISSUE TITLE
Setting up localstack on my machine at work

### ISSUE THREAD

**Issue by gaston-cupido** [localstack/localstack#7014]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi, I am new to localstack and want to get it up and running on my machine at work. i have docker and the latest python running on my machine. the documentation is not so clear on trouble shooting. I would like to get it running on my machine to see how it can help the company.

I am getting this error
![image](https://user-images.githubusercontent.com/8736347/195311820-c35f5f08-8216-4717-8695-6ba1b9af4835.png)

### How are you starting LocalStack?

With the `localstack` script

### Steps To Reproduce

    docker run localstack/localstack

### Environment

```markdown
- OS: Windows
- LocalStack:
```

**Comment by MarcelStranak** [comment]
Hi, can you please try updating the pyOpenSSL libraries?

```bash
pip install pyOpenSSL --upgrade
pip install cryptography --upgrade
pip install localstack --upgrade
```

**Comment by gaston-cupido** [comment]
I am getting this error when doing the above
![image](https://user-images.githubusercontent.com/8736347/195326299-702f22f3-80cd-4116-b388-fa4fe6665dda.png)

**Comment by MarcelStranak** [comment]
Hi @gaston-cupido, can you please have a look at this stackoverflow page: https://stackoverflow.com/questions/49943410/pip-ssl-error-on-windows

The issue does not seem to be connected with LocalStack at all.

**Comment by dfangl** [comment]
Hi @gaston-cupido !
Is it possible your company has some kind of company proxy set up, which breaks up ssl connections?

**Comment by gaston-cupido** [comment]
Yes

**Comment by KurtMar** [comment]
You can try installing LocalStack's UI version, which is believe is more self-contained: https://localstack.cloud/products/cockpit/

**Comment by whummer** [comment]
Hi @gaston-cupido , we have now created some documentation to demonstrate how you can set up custom TLS certificates if you're behind a corporate network and facing issues with outbound connections: https://docs.localstack.cloud/references/custom-tls-certificates . Hope that helps - please keep us posted.. Thanks!

/cc @simonrw
