### ISSUE TITLE
bug: Lambda should correctly process FIFO queue event sources

### ISSUE THREAD

**Issue by dominikschubert** [localstack/localstack#7036]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Multiple lambda environments are spawned in parallel

### Expected Behavior

A single lambda environment should handle the messages sequentially.

### How are you starting LocalStack?

Custom (please describe below)

### Steps To Reproduce

Scenario:

1. Create a lambda with a set timeout (e.g. 30s) + fifo queue + disabled event source mapping
2. Send 5 messages to the queue with the same message group id ( => guarantees that they should be processed one by one in-order)
3. enable the event source mapping so that the Lambda service can start processing the messages
4. Wait for some time ( e.g. 90s) and check how many log streams have been created

### Environment

```markdown
-
```

**Comment by thrau** [comment]
confirmed to work with latest using the test you provided!
