### ISSUE TITLE
Solved: how to run localstack on docker for windows

### ISSUE THREAD

**Issue by robfe** [localstack/localstack#704]
Hi! i did a little write up of how i got localstack working in docker for windows: https://gist.github.com/robfe/9a858b59f4d394ef5deb2517833e75c6

Is there somewhere more official i can help document this?

**Comment by igorpupkinable** [comment]
This is very helpful! I managed to run Localstack on Windows natively (lcow) with these fixes.

**Comment by whummer** [comment]
Thanks @robfe , and apologies for the long delay. Could you kindly create a pull request against our README with a condensed version of these instructions? That would be great. Thanks! Closing this issue in the meantime.
