### ISSUE TITLE
bug: Error: error reading EC2 VPC (vpc-XXXXX) Attribute (enableNetworkAddressUsageMetrics): InvalidParameterValue: Value enable_network_address_usage_metrics is invalid for parameter.

### ISSUE THREAD

**Issue by gh-log** [localstack/localstack#7046]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```
tflocal apply

Error: error reading EC2 VPC (vpc-XXXXX) Attribute (enableNetworkAddressUsageMetrics): InvalidParameterValue: Value enable_network_address_usage_metrics is invalid for parameter.
       status code: 400, request id: A73EZ2RBQPMHGETDTSUYJ3NMY1JD3VSB1A1BI937V8L8IIL4ESER

   with data.aws_vpc.default_vpc,
   on main.tf line 19, in data "aws_vpc" "default_vpc":
   19: data "aws_vpc" "default_vpc" {

------------------------------------------------------------

data "aws_vpc" "default_vpc" {
  default = true
}
```

with AWS provider 4.35 it doesnt work. 4.34 works.

using AWS (not LS) works with AWS provider 4.35.

LocalStack 1.2.0

### Expected Behavior

no error message.

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    localstack start

### Environment

```markdown
- OS: ubuntu 24.04.1
- LocalStack: 1.2.0
```

**Comment by noatec** [comment]
Just dropped provider to 4.25.0 and it worked ok. Trying 4.34.0 now.

**Comment by noatec** [comment]
4.34.0 is working.

**Comment by bblommers** [comment]
FYI: This was added to Moto in https://github.com/spulec/moto/pull/5590, so the moment LS pulls in moto >= 4.0.9.dev6 this should be resolved.

**Comment by c1moore** [comment]
I'm also running into this problem.  Using Pulumi instead of TF directly.  When is this expected to go out?  I just tried repulling the localstack image and it's still breaking.

**Comment by apenella** [comment]
Just to let you know.

With the following setup:
- Localstack 1.2.0
- Terraform v1.3.4
- AWS provider 4.34.0

The following block is working properly:
```
data "aws_vpc" "this" {
    default = true
}
```

When I updated the AWS provider to 4.35.0, the error backs, and I decided to keep version 4.34.0.

**Comment by c1moore** [comment]
Thanks @catmeme , that seems to work.  I was hoping to wait for localstack to update, but seems like that might take a while.

**Comment by bamofah** [comment]
Hi, just wanted to know if there is any further update on this.

**Comment by algo7** [comment]
Any update?

**Comment by catmeme** [comment]
There was a release yesterday, `1.3.0` should include the fix for moto3.

**Comment by algo7** [comment]
`1.3.0` release confirmed to fix this problem. Tested on Ubuntu 22.04.1 LTS/

**Comment by arazdolski** [comment]
Yes, I can also confirm that updating localstack to version 1.3.0 solved the problem. 

To update localstack run: `localstack update all`
