### ISSUE TITLE
bug: Can't retrieve secrets ResourceNotFoundException

### ISSUE THREAD

**Issue by lukonjun** [localstack/localstack#7054]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We run Localstack in Kubernetes (Helm Chart):

Trying to retrieve the secret from the application container: 
```
aws secretsmanager get-secret-value \
>     --secret-id xxxxxxx \
>     --endpoint-url http://localstack:4566 \
>     --region eu-central-1 
An error occurred (ResourceNotFoundException) when calling the GetSecretValue operation: Secrets Manager can't find the specified secret.
```

When I run from the localstack container `kubectl exec -it` I can retrieve the secret
```
awslocal secretsmanager get-secret-value \
    --secret-id xxxxxxx \
    --region eu-central-1
   {
    "ARN": "arn:aws:secretsmanager:eu-central-1:000000000000:secret:xxxxxxxxxxxx",
    "Name": "xxxxxxxxx",
    "VersionId": "54c33b92-af6e-4612-a706-5b1e02ebf2bb",
...
    "CreatedDate": 1666274384.828636
}
```

### Expected Behavior

Retrieve the secret from the application container without a problem

### How are you starting LocalStack?

Custom (please describe below)

### Steps To Reproduce

1. Use latest image of Localstack
2. Try to retrieve secret with aws cli over network
```
aws secretsmanager get-secret-value \
    --secret-id xxxxxxxx \
    --endpoint-url http://localstack:4566 \
    --region eu-central-1 
```

### Environment

```markdown
- LocalStack: latest
```

### Anything else?

This used to work. We use Localstack for e2e testing in a pipeline however after the new release was pushed stoped working
![Screenshot 2022-10-20 at 16 18 24](https://user-images.githubusercontent.com/64301331/196974325-9d8cb561-709c-40da-ae13-63351e51d65f.png)

I pinned the version 1.2.0 (13 days old) in our helm chart and now it is working. Is this related to providing access credentials?

**Comment by dominikschubert** [comment]
> Is this related to providing access credentials?

Most likely, yes. We extract the account ID now from your access key ID, so if you still have other access key ID set (e.g. your production AWS Account), it may not find the resource since it's indexing the resource by account id + region.

You can try to setting the environment variable for the aws command:  `export AWS_ACCESS_KEY_ID="000000000000"`. `000000000000` is the default account ID in this case.

We'll have more information around this up in our docs soon :+1:

**Comment by dominikschubert** [comment]
@lukonjun We've reverted the change that was causing this for now. If you update `latest` it should now work as it did previously :+1:

**Comment by lukonjun** [comment]
Hey @dominikschubert thanks for fixing it so quickly! However I think we will stay on a pinned version for now, leaving it at latest was actually not intended. Thanks either way ✌️
