### ISSUE TITLE
bug: AllocateAddressRequest rejects empty value for optional `domain` parameter

### ISSUE THREAD

**Issue by kralicky** [localstack/localstack#7058]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When creating an EIP using the AllocateAddressRequest API, if the `domain` option is not set, the API will reject the request with the error message `InvalidParameterValue: Invalid value '' for domain` instead of defaulting to `vpc`.

### Expected Behavior

According to AWS docs [here](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_AllocateAddress.html), the `domain` parameter is optional, and will default to `vpc` or `default` if unset.

### How are you starting LocalStack?

Custom (please describe below)

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    Localstack Cockpit

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

I am using the pulumi `awsx` sdk to create a VPC, as follows:
```go
import (
	"github.com/pulumi/pulumi-awsx/sdk/go/awsx/ec2"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {
		_, err := ec2.NewVpc(ctx, "name", &ec2.VpcArgs{})
		if err != nil {
			return err
		}
		return nil
	})
}

```

### Environment

```markdown
- OS: Manjaro
- LocalStack: latest
```

### Anything else?

I think this is where the EIP is being created: https://github.com/pulumi/pulumi-awsx/blob/3465b1edfd031ba3a14495992319aa59ddf3d82b/awsx/ec2/vpc.ts#L206-L210

Error from localstack dashboard:
![image](https://user-images.githubusercontent.com/8194899/197059729-9a4b313f-fc07-4a75-b948-8c939b3f18f0.png)

Pulumi error:
```
Diagnostics:
  pulumi:pulumi:Stack (localstack):
    error: update failed
 
  aws:ec2:Eip (test-1):
    error: 1 error occurred:
        * Error creating EIP: InvalidParameterValue: Invalid value '' for domain.
        status code: 400, request id: MOD1KUWXUBZSLQJR9IC2MFOZRQXK31FTUPHKIVWQFZZGWUWYY8F2


```

**Comment by viren-nadkarni** [comment]
Hi @kralicky, we have released a fix in the latest image. Please let us know if this persists.
