### ISSUE TITLE
Elasticsearch still installed with 5.3 instead of 6.2

### ISSUE THREAD

**Issue by eabruzzese** [localstack/localstack#706]
Last week I had PR #694 pulled into master to bump the Ealsticsearch version from 5.3 to 6.2. A day or so later, a new release was tagged and a new Docker image was built.

In the latest Docker image, the old Elasticsearch version (5.3) is installed instead of the new one (6.2).

Can we run whatever process is necessary to get Elasticsearch updated in the container?

**Comment by whummer** [comment]
Good point, thanks for reporting @eabruzzese . The base image had to be updated, and a minor fix (#707) was needed in our codebase to integrate the latest ES version. Can you please give it a try with the latest version. Thanks

**Comment by eabruzzese** [comment]
It works! Thanks @whummer.
