### ISSUE TITLE
bug: ApiGateway Model schema stored in Wrong JSON format

### ISSUE THREAD

**Issue by salah-mueller** [localstack/localstack#7060]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

APiGateway Model that being created by CDK project stores the JSON schema with a single quotes instead of double quotes which leading to an error in parsing this json object. 

you can refere to this article to see the steps 

https://dev.to/dvddpl/reduce-lambda-invocations-and-code-boilerplate-by-adding-a-json-schema-validator-to-your-api-gateway-15af

and it works fine on AWS account 

also you can look on the attached image how localstack stores the JSON object with a single quotes, I tried to edit it manually through UI but it return it back with single quotes

![Screen Shot 2022-10-18 at 4 28 08 PM](https://user-images.githubusercontent.com/106184681/196769273-0834865a-2fb3-4efc-b3a9-9da6b2ad511d.png)

### Expected Behavior

store the json schema in correct JSON format

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    localstack start

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    cdklocal deploy

### Environment

```markdown
- OS:OSX
- LocalStack: 1.0.4
```

**Comment by adrianluisgonzalez** [comment]
I've run into this issue too.  It would be great to have a fix for this.

**Comment by bentsku** [comment]
Hi @adrianluisgonzalez, I'm going to work on this today, so we should have a fix ready pretty soon! Thanks for your report too.
