### ISSUE TITLE
bug: Localstack Glue is missing support for MySQL JDBC driver

### ISSUE THREAD

**Issue by snhardin** [localstack/localstack#7064]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When attempting to use the MySQL driver in a Python Glue job, the job fails because the JAR for the MySQL JDBC driver is missing from PySpark. The following stacktrace is produced for AWS Glue 2.0 jobs.

```
File "/usr/local/spark-2.4.3-bin-without-hadoop/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1257, in __call__
File "/usr/local/spark-2.4.3-bin-without-hadoop/python/lib/pyspark.zip/pyspark/sql/utils.py", line 63, in deco
File "/usr/local/spark-2.4.3-bin-without-hadoop/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py", line 328, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o48.getDynamicFrame.
: java.lang.ClassNotFoundException: com.mysql.jdbc.Driver 
```

A similar stacktrace is produced for AWS Glue 3.0 jobs. 0.9 and 1.0 were not tested.

### Expected Behavior

The Glue job should not fail due to missing MySQL JDBC driver. Copying the driver into the `localstack/bigdata` container fixes this issue. Copying in the appropriate version of the MySQL JDBC driver referencing [this link](https://docs.aws.amazon.com/glue/latest/dg/aws-glue-programming-etl-connect.html) fixes the issue.

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

```
# DEBUG and API KEY for PRO are set already
localstack start
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```
awslocal glue create-job --name 'my-team-ingestion-job' \
  --role 'data-import-glue-job-role' \
  --command '{"Name": "pythonshell", "ScriptLocation": "s3://my-ingestion/glue/src/glue_function.py", "PythonVersion": "3"}' \
  --glue-version '3.0' \
  --default-arguments "{\"--class\": \"GlueApp\", \"--additional-python-modules\": \"s3://my-ingestion-ingestion/glue/resources/wheels/PyMySQL-1.0.2-py3-none-any.whl,s3://my-ingestion-ingestion/glue/resources/wheels/dependency_injector-4.40.0-cp36-cp36m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl,s3://my-ingestion-ingestion/glue/resources/wheels/six-1.16.0-py2.py3-none-any.whl,s3://my-ingestion-ingestion/glue/resources/wheels/csco-1.0-py2.py3-none-any.whl\", \"--mysql_a_secret\": \"${a_secret_arn}\", \"--mysql_a_url\": \"${a_url_arn}\"}"
awslocal glue start-job-run --job-name 'my-team-ingestion-job' \
  --arguments '{"--s3_manifest_url": "s3://dl-test/sample-customer.manifest.json"}' \
```

### Environment

```markdown
- OS: Mac OS X 12.5.1
- LocalStack: 1.2.0
```

### Anything else?

Please see the relevant [AWS Documentation](https://docs.aws.amazon.com/glue/latest/dg/aws-glue-programming-etl-connect.html), specifically under the **JDBC connectionType values** heading, where the version of MySQL JDBC driver is indicated for the associated version of Glue being used.

**Comment by avisual** [comment]
Where did you copy the jar to? I am having the same issues with Postgres

**Comment by silv-io** [comment]
@avisual These are changes we need to make inside of the pro version of LocalStack. Feel free to create a new issue with the exact JAR files that are missing and we will add it. You can also reference this issue in yours.
