### ISSUE TITLE
bug: currentTimeMillis() is missing from GlueContext

### ISSUE THREAD

**Issue by snhardin** [localstack/localstack#7072]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`currentTimeMillis()` is a method that is available on the `GlueContext` class. Instances of this class should be able to call this method to get a consistent timestamp of the current time (please see the [aws-glue-libs source branch for Glue 2.0](https://github.com/awslabs/aws-glue-libs/blob/fc600c3674e5d8b80f201efefd551d1ef93d41f9/awsglue/context.py#L443)). However, calls to this function fail with an unknown method stack trace. This method should be available in Glue 2.0 and above.

### Expected Behavior

The call to `currentTimeMillis()` should not fail.

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    localstack start

### Environment

```markdown
- OS: Mac OS X 12.5.1
- LocalStack: 1.2.0
```

**Comment by whummer** [comment]
Hi @snhardin , apologies for the long delay on this one. We have now introduced some significant enhancements for Glue jobs - in the latest version, we have introduced a mode to spin up the required utilities (Spark, Hive, Presto, etc) directly in the main LocalStack container, without creating a separate `bigdata` container. 

This new mode is behind a feature flag and can be activating by setting `BIGDATA_MONO_CONTAINER=1` in the environment (it will become the default in a future release). Can you please give that a try with the `latest` image and see if it resolves the issue you've been facing? (We just gave it a quick try, and it seems that the `currentTimeMillis()` method is available with this config). Please keep us posted on how it goes.. Thanks for your help!

**Comment by whummer** [comment]
Sounds great @snhardin . Please reach out to us on Slack or via email if you'd like to continue your evaluation - happy to extend your trial by a couple of weeks! Going to close the issue in the meantime, but please do keep us in the loop on how things are going. Thanks!
