### ISSUE TITLE
feature request: Add Support for DescribeScalingActivities

### ISSUE THREAD

**Issue by mviamari** [localstack/localstack#7083]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

The Following API endpoint is not yet supported: DescribeScalingActivities

```
2022-10-24T15:03:41.984  INFO --- [   asgi_gw_1] localstack.aws.skeleton    : API action 'DescribeScalingActivities' for service 'autoscaling' not yet implemented or pro feature - check https://docs.localstack.cloud/aws/feature-coverage for further information
2022-10-24T15:03:41.985  INFO --- [   asgi_gw_1] localstack.request.aws     : AWS autoscaling.DescribeScalingActivities => 501 (InternalFailure)
```

### Anything else?

```
LocalStack version: 1.2.1.dev
LocalStack Docker container id: 53b9063f6e75
LocalStack build date: 2022-10-21
LocalStack build git hash: 1bbc0760
```

**Comment by taras-kobernyk-localstack** [comment]
@mviamari Hi Michael. Could you please let us know if you want to see read data about scaling events, or if you just want the call to return something so your setup, that uses the call, wouldn't fail?

Asking because we currently do not seem to have the actual autoscaling events in LocalStack. So in order to provide you with some actual data we would first have to implement that infrastructure. Might not be not an easy task - yeat to properly figure it out, though.

But if you it would be enough for LocalStack to pretend having some data - that should be relatively easy.

Alternatively, if you could tell me why you need this data, we might be able to figure out some workaround for you.

Please let me know what you think.

**Comment by mviamari** [comment]
Hi @taras-kobernyk-localstack,

This is API is used by terraform during apply when verifying that an ASG is deployed. It appears to be checking on the status of the ASG waiting for the ASG to have its capacity requirements satisfied. I'm not sure if pretending to have the data will work or not.

```
2022-11-02T14:38:12.197-0700 [ERROR] vertex "module.test.aws_autoscaling_group.default[0]" error: waiting for Auto Scaling Group (local-default-cluster-default-asg-1-us-east-1c) capacity satisfied: reading scaling activities: InternalFailure: API action 'DescribeScalingActivities' for service 'autoscaling' not yet implemented or pro feature - check https://docs.localstack.cloud/aws/feature-coverage for further information
        status code: 501, request id: XXX
```

**Comment by taras-kobernyk-localstack** [comment]
Thank you for the clarification, @mviamari. That was helpful.

May I ask you for yet another thing? Would you be able to provide me some minimal terraform config, which results in this error?

As far as I see, Autoscaling has `DescribeAutoScalingGroups`, which is supposed to show a result of `CreateAutoScalingGroup`. So not sure why Terraform calls `DescribeScalingActivities`. I am not familiar with this operation, but it looks like it is supposed to show information about some autoscaling events. Not sure how it is related to the creation of the groups themselves. Maybe I did miss something in the official AWS documentation, or maybe the connection is just not there. So debugging what Terraform does with your config might help us to understand it better.

**Comment by SanderHagen** [comment]
I'm also running into this issue with Pulumi. I believe it's currently also running v4.34

**Comment by mviamari** [comment]
@taras-kobernyk-localstack Sorry for the delay. I've attached a simple ASG example that generates this error response. 
[terraform-asg.zip](https://github.com/localstack/localstack/files/10070228/terraform-asg.zip)

**Comment by taras-kobernyk-localstack** [comment]
No worries at all!  And thanks. :-)
