### ISSUE TITLE
UnknownOperationException while creating dynamodb tables via terraform

### ISSUE THREAD

**Issue by mirak94** [localstack/localstack#709]
I'm trying to create dynamodb tables into localstack via terraform, and I've configured the aws provider as follows:
```
provider "aws" {
  profile = ""
  region = "eu-west-1"
  endpoints {
    dynamodb = "http://localhost:4569"
  }
}
```
I receive the same error for each table while making `terraform apply`, but I can see all tables are created (not sure properly or not) by making `aws dynamodb --endpoint-url http://localhost:4569 list-tables`
```
* module.{table_name}.aws_dynamodb_table.table: 1 error(s) occurred:
* aws_dynamodb_table.table: UnknownOperationException: An unknown operation was requested.
	status code: 400, request id: cd5ad25e-546a-4b84-a609-a23819e58451
```
Could anyone please help by sharing some ideas/insights about the cause of the problem here? Is it localstack issue or I am missing something?
If it is localstack issue, could someone please share some insights so that I submit a PR for it?

Thank you very much in advance.

**Comment by conorfoley** [comment]
I'm having the same issue, any suggestions?

**Comment by derickson82** [comment]
Local DynamoDB doesn't support all operations, like DescribeTimeToLive, which terraform calls. It looks like there was an issue (#599) that attempted to work around this problem.

**Comment by whummer** [comment]
Thanks @mirak94 @conorfoley @derickson82 - this should have been fixed in the meantime. Please re-open this issue if the problem persists.
