### ISSUE TITLE
feature request: Implement ResourceGroupsTaggingApi AWS service.

### ISSUE THREAD

**Issue by taras-kobernyk-localstack** [localstack/localstack#7092]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

LocalStack is currently missing [ResourceGroupsTaggingApi service](https://docs.aws.amazon.com/resourcegroupstagging/latest/APIReference/overview.html). Might be useful to implement it at some point.

Why might we need it? [This ticket](https://github.com/localstack/localstack/issues/7073) is an example. There seems to be no way in ApiGateway to get an ARN for an ApiKey created with [CreateApiKey](https://docs.aws.amazon.com/apigateway/latest/api/API_CreateApiKey.html). But such ARNs are required to change tags on ApiKeys with [TagResource](https://docs.aws.amazon.com/apigateway/latest/api/API_TagResource.html). It is possible I am missing some other way to get such ARNs, but looks like ResourceGroupsTaggingApi is at least some way to get them.

### 🧑‍💻 Implementation

Implementing this service might not be easy - it has to keep track of all tags across all AWS services. But we do not have a centralized storage for tags, every service keeps track of its own.

So we most probably would have higher priorities with other stuff. Still, if we get some time, might be useful to implement this.

### Anything else?

Tagging it seems interchangeable between APIs, ServiceAPI to tag and the ResourceGroupsTaggingApi. Example:

* Tags created using the ServiceApi (in this case APIGateway).
```
aws resourcegroupstaggingapi get-resources                                                      6 (33.987s) 
{
    "ResourceTagMappingList": [
        {
            "ResourceARN": "arn:aws:apigateway:eu-west-1::/apikeys/8i2x7nr99d",
            "Tags": [
                {
                    "Key": "organization",
                    "Value": "demo-org"
                }
            ]
        },
        {
            "ResourceARN": "arn:aws:apigateway:eu-west-1::/restapis/yt9igwxvlk/stages/dev",
            "Tags": [
                {
                    "Key": "org",
                    "Value": "localstack"
                }
            ]
        }
    ]
}

```

* Tag create using the ResourceGroupsTaggingApi
```
aws resourcegroupstaggingapi tag-resources --resource-arn-list "arn:aws:apigateway:eu-west-1::/restapis/yt9igwxvlk/stages/dev" --tags "Foo=Bar"
{
    "FailedResourcesMap": {}
}
```

* List tags using ResourceGroupsTaggingApi
```
aws resourcegroupstaggingapi get-resources                                                       0 (1.516s) < 09:02:40
{
    "ResourceTagMappingList": [
        {
            "ResourceARN": "arn:aws:apigateway:eu-west-1::/apikeys/8i2x7nr99d",
            "Tags": [
                {
                    "Key": "organization",
                    "Value": "demo-org"
                }
            ]
        },
        {
            "ResourceARN": "arn:aws:apigateway:eu-west-1::/restapis/yt9igwxvlk/stages/dev",
            "Tags": [
                {
                    "Key": "org",
                    "Value": "localstack"
                },
                {
                    "Key": "Foo",
                    "Value": "Bar"
                }
            ]
        }
    ]
}
```

* List tags using the Service API
```
aws apigateway get-tags --resource-arn "arn:aws:apigateway:eu-west-1::/restapis/yt9igwxvlk/stages/dev"
{
    "tags": {
        "Foo": "Bar",
        "org": "localstack"
    }
}
```

**Comment by HarshCasper** [comment]
We have shipped this in the `localstack/localstack:latest` image. Please have a look at our coverage here — https://docs.localstack.cloud/references/coverage/coverage_resourcegroupstaggingapi/
