### ISSUE TITLE
feature request: [SecretsManager] support creating secrets for regions other than the current or default region

### ISSUE THREAD

**Issue by cmoralesmx** [localstack/localstack#7095]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

In my testing for #6221 I need to create secrets in two or three regions distinct from the current region. In AWS I do this by specifying `--region` to my requests. Thus, I can create secrets for regions B and C while my default region is A.
This, however, is not possible in `LocalStack` 

### 🧑‍💻 Implementation

The CRUD operations for SecretsManager should accept an additional parameter for the region. I think this involves changing `models.py` and `responses.py` in `moto/secretsmanager/`
With some guidance from `LocalStack` engineers I could do the changes and send a PR

**Comment by whummer** [comment]
Hi @cmoralesmx, thanks for reporting. 

Regions should already be supported for SecretsManager. Can you please share some details about your use case, ideally a few snippets of your client code, to help us replicate this issue?

To give an example, consider the following sequence of `awslocal` commands:
```
$ awslocal --region us-east-1 secretsmanager create-secret --name s1 --secret-string 's1'
{
    "ARN": "arn:aws:secretsmanager:us-east-1:000000000000:secret:s1-blmRFF",
    "Name": "s1",
    "VersionId": "9a88a56f-0fe0-448c-a194-3fd0df11d452"
}
$ awslocal --region us-east-2 secretsmanager create-secret --name s2 --secret-string 's2'
{
    "ARN": "arn:aws:secretsmanager:us-east-2:000000000000:secret:s2-exNida",
    "Name": "s2",
    "VersionId": "01792780-f355-4d19-893c-64e6f26144ef"
}

$ awslocal secretsmanager --region us-east-1 list-secrets
{
    "SecretList": [{...}]
}
$ awslocal secretsmanager --region us-east-2 list-secrets
{
    "SecretList": [{...}]
}
$ awslocal secretsmanager --region eu-central-1 list-secrets
{
    "SecretList": []
}
```

Are you able to replicate these results with the `latest` version of LocalStack?

**Comment by thrau** [comment]
Closing this issue for now. Please open a new issue if the problem persists with instructions on how to reproduce the issue.
