### ISSUE TITLE
bug: Localstack stepfunctions Parallel State returns output in incorrect order

### ISSUE THREAD

**Issue by epabst** [localstack/localstack#7105]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I use a Parallel State in step functions and set the ResultPath to something, it puts an array into the ResultPath location but the items in the array don't match the order of the states within the Parallel State.  I only had 2 states and they were pretty consistently in the opposite order.

### Expected Behavior

The output of a Parallel State should be in the same order as the states are defined within the Parallel state.

### How are you starting LocalStack?

Custom (please describe below)

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

testcontainers

### Environment

```markdown
- OS: macOS
- LocalStack: 1.2.0
```

### Anything else?

Thank you so much for creating localstack.  It is AWESOME!

**Comment by MEPalma** [comment]
We are currently involved in the development of our own customized backend for Step Functions. You can access this feature by setting the environment variable PROVIDER_OVERRIDE_STEPFUNCTIONS=v2. For a detailed overview of the support provided in this initial version of Step Functions, you can refer to the notes of https://github.com/localstack/localstack/pull/8779.

As we continue to enhance both the support and stability of this service, we believe that there is a potential that it might already fulfill your requirements. We are looking forward to your feedback!

**Comment by MEPalma** [comment]
I am marking this issue as resolved since it appears to be addressed in the latest version of LocalStack. If the problem persists on your end, please inform us so that we can investigate further.
