### ISSUE TITLE
bug: sqs sendMessageBatch should mimic AWS batch size limit 

### ISSUE THREAD

**Issue by wilkenm** [localstack/localstack#7106]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Using the SQS sendMessageBatch command allows batches of more than 10 messages to be sent.  This does not match the behavior in AWS, where a batch of more than 10 records is rejected.

[AWS docs](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_SendMessageBatch.html) specify a maximum of 10 messages can be in a batch.

### Expected Behavior

Sending more than 10 messages in a batch should result in an error similar to the AWS result below

Exception text
```Error AWS.SimpleQueueService.TooManyEntriesInBatchRequest: Maximum number of entries per request are 10. You have sent 20.```

Returned JSON response
```
 {
  code: 'AWS.SimpleQueueService.TooManyEntriesInBatchRequest',
  time: 2022-10-27T23:04:39.592Z,
  requestId: 'c0050ad4-f697-54b5-b207-5101e6504ee3',
  statusCode: 400,
  retryable: false,
  retryDelay: 63.132585413620056
}
```

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker-compose.yml

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```
const AWS = require("aws-sdk");

const QUEUE_URL = "quey_url_goes_here"
const NUM_MESSAGES = 20

const messages = []

for (let i = 0; i < NUM_MESSAGES; i++) {
    const message = {
        Id: Math.floor(Math.random() * 10000).toString(),
        MessageBody: 'Message body text',
        DelaySeconds: 10
    }
    messages.push(message)
}

const batchMessage = {
    Entries: messages,
    QueueUrl: QUEUE_URL
}

const sqs = new AWS.SQS({apiVersion: '2012-11-05'})

sqs.sendMessageBatch(batchMessage, (err, data) => {
    if (err) {
        console.log("Error", err)
    } else {
        console.log("Success:", data);
    }
})
```

The above snippet works without any issues when using a Localstack SQS queue, but fails with a "TooManyEntriesInBatchRequest" error in AWS.

### Environment

```markdown
- OS: OSX
- LocalStack: 1.2.0
```

**Comment by thrau** [comment]
@giograno is #7107 the fix for this, or is something else needed?

**Comment by giograno** [comment]
@thrau yes, it is! Forgot it here, thanks for bringing it up. The fix is obviously in the `latest` Docker image.
