### ISSUE TITLE
bug: AppConfig GetConfiguration - Cannot specify configuration profile name in request - only configuration profile id works

### ISSUE THREAD

**Issue by dakotajd** [localstack/localstack#7108]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When calling the GetConfiguration API via CLI or an SDK, AWS expects that the following be provided in the request:
- application name or id
- environment name or id
- configuration profile name or id
- client id
- etc

Source: https://docs.aws.amazon.com/appconfig/2019-10-09/APIReference/API_GetConfiguration.html

Most parameters claim that you should be able to pass the id or the name, but for the configuration profile parameter, LocalStack is only working when you pass the id.

### Expected Behavior

LocalStack should be consistent with the documentation and accept configuration profile name or id when calling GetConfiguration.

### How are you starting LocalStack?

With a `docker run` command

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)
# Setup #
1. **Create an application:**

```
aws --endpoint-url=http://localhost:4566 appconfig create-application --name=test-application
```
Output:
```
{
    "Id": "78dfd50",
    "Name": "test-application"
}
```

2. **Create a configuration profile (update application id in command from previous output):**
```
aws --endpoint-url=http://localhost:4566 appconfig create-configuration-profile --name=test-config-profile --application-id=78dfd50 --location-uri=not-relevant
```
Output:
```
{
    "ApplicationId": "78dfd50",
    "Id": "1c895e2",
    "Name": "test-config-profile",
    "LocationUri": "not-relevant"
}
```
3. **Create an environment (update application id in command from previous output):**
```
aws --endpoint-url=http://localhost:4566 appconfig create-environment --name=test-environment --application-id=78dfd50
```
Output:
```
{
    "ApplicationId": "78dfd50",
    "Id": "ffc2499",
    "Name": "test-environment",
    "State": "READY_FOR_DEPLOYMENT"
}
```
4. **Create a hosted configuration version (update ids in command from previous outputs):**
Content is not important, in this case I've just added a trivial string which needs to be base64 encoded.
```
aws --endpoint-url=http://localhost:4566 appconfig create-hosted-configuration-version --application-id=78dfd50 --configuration-profile-id=1c895e2 --content-type=text/html --content=U29tZSBkYXRhIGZvciBhcHBjb25maWc= outfile
```
Output:
```
{
    "ApplicationId": "78dfd50",
    "ConfigurationProfileId": "1c895e2",
    "VersionNumber": "1",
    "ContentType": "text/html"
}
```
Ideally after doing all of this, you'd do a deployment, but LocalStack doesn't care about that and for this case you don't need to.

# The problem #
Now that we have all of that in place we can observe the issue.
For background and as an example, the current names/ids from the outputs of the commands above are as follows:
```
Application name: "test-application"
Application id: "78dfd50"
Configuration profile name: "test-config-profile"
Configuration profile id: "1c895e2"
Environment name: "test-environment"
Environment id: "ffc2499"
```
When attempting to retrieve the configuration AWS expects:
- application name or id
- environment name or id
- configuration profile name or id
- client id
- etc

Source: https://docs.aws.amazon.com/appconfig/2019-10-09/APIReference/API_GetConfiguration.html

If we try to specify names for all parameters, it does not work:
```
aws --endpoint-url=http://localhost:4566 appconfig get-configuration --application=test-application --environment=test-environment --configuration=test-config-profile --client-id=123  outfile
```
Output:
```
An error occurred (ResourceNotFoundException) when calling the GetConfiguration operation: HostedConfigurationVersion with Id test-config-profile-1 could not be found for account 000000000000.
```
But if I specify the id for configuration instead, it works:
```
aws --endpoint-url=http://localhost:4566 appconfig get-configuration --application=test-application --environment=test-environment --configuration=1c895e2 --client-id=123  outfile
```
Output:
```
{
    "ConfigurationVersion": "1",
    "ContentType": "text/html"
}
```

This is inconsistent with the rest of the parameters as well as the AWS documentation.

### Environment

```markdown
- OS: MacOS Big Sur
- LocalStack: 1.2.0/latest
```

**Comment by whummer** [comment]
Thanks for reporting @dakotajd . We have now pushed a couple of enhancements for our AppConfig implementation, which should also resolve the issue with not being able to specify the profile name in the request. 

When you get a chance, can you please pull the `latest` Docker image and give it another try? (Please note that since our recent v2.0 release you'll now need to pull the `localstack/localstack-pro` image)

Please keep us posted on how it goes.. Thanks!

**Comment by dakotajd** [comment]
Everything looks good and works as expected after using the latest localstack-pro image. Thanks for the update!
