### ISSUE TITLE
Cannot create Lambda function via Serverless

### ISSUE THREAD

**Issue by alanjds** [localstack/localstack#711]
`moto` may be not building the ARN correctly on the CloudFormation output XML. 
Exemple: (see: https://github.com/temyers/serverless-localstack/issues/24#issuecomment-373911443)
>```xml
> <DescribeStacksResponse>
>   <DescribeStacksResult>
>    <Stacks>
>      <member>
>        <Outputs>
>          <member>
>            <OutputKey>HelloLambdaFunctionQualifiedArn</OutputKey>
>            <OutputValue><moto.awslambda.models.LambdaVersion object at 0x7f82f8363090></OutputValue>
>          </member>
>          <member>
>            <OutputKey>ServiceEndpoint</OutputKey>
>            <OutputValue>https://<moto.apigateway.models.RestAPI object at 0x7f82f8363c10>.execute-api.us-east-1.amazonaws.com/local</OutputValue>
>          </member>
>        </Outputs>
>      </member>
>    </Stacks>
>  </DescribeStacksResult>
> </DescribeStacksResponse>
> ```
(some members were suppressed on this sample above)

I guess that `<moto.awslambda.models.LambdaVersion object at 0x7f82f8363090>` should had been coerced to its ARN, and `<moto.apigateway.models.RestAPI object at 0x7f82f8363c10>` to its URL.

Should patches land here or in https://github.com/whummer/moto repo?

**Comment by justinm** [comment]
Upstream has responded with a fix. I'm guessing we'll now need to wait for a new version of moto to be published?

**Comment by alanjds** [comment]
I really do not know. Some docs says that a vendored version is used. Maybe sync the changes...

**Comment by justinm** [comment]
It looks like boto-1.3.4 contains the fix reported in https://github.com/spulec/moto/issues/1588. It looks like localstack upgraded to boto-1.3.4 about 6 days ago. Can you retest this off of the latest localstack version?
