### ISSUE TITLE
bug: cli ignores some configuration options

### ISSUE THREAD

**Issue by gsx95** [localstack/localstack#7113]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm using the localstack cli to start localstack in docker.

I'm now trying to setup SMTP with the configuration options [mentioned here](https://docs.localstack.cloud/localstack/configuration/#emails), but it always says "SMTP settings not configured". Then I tried some other configuration, like REQUIRE_PRO, and that also doesn't seem to work. Other options like DEBUG or DISABLE_CORS_CHECK are working though.

I've tried setting the configuration via my default profile in ~/.localstack and also via environment variables.

**Example:** 

I've started localstack with the following configuration:

```
LOCALSTACK_REQUIRE_PRO=1
REQUIRE_PRO=1
DEBUG=1
DISABLE_CORS_CHECKS=1
```

and localstack starts successfully - which it shouldn't with the REQUIRE_PRO option.

**Another example:** 

When starting localstack with the following options:
```
LOCALSTACK_REQUIRE_PRO=1
LOCALSTACK_API_KEY=xxxx
REQUIRE_PRO=1
DEBUG=1
DISABLE_CORS_CHECKS=1
SMTP_HOST=smtp.gmail.com
SMTP_USER=xxx@gmail.com
SMTP_PASS=xxx
SMTP_EMAIL=xxx@gmail.com
```
 and trying to get cognito to send a verifcation email, I get `SMTP settings not configured`. When looking into the localstack debug logs, I can see the options that DO work in the logs when localstack starts the docker container, but the options that seemingly don't work, are also missing from the debug output.

```
[    Thread-2] l.u.c.docker_cmd_client    : Run container with cmd: ['docker', 'run', '--rm', '--name', 'localstack_main', '--privileged', '-v', '/Users/[xxx]/Library/Caches/localstack/volume:/var/lib/localstack', '-v', '/var/run/docker.sock:/var/run/docker.sock', '-p', '127.0.0.1:4566:4566', '-p', '127.0.0.1:4571:4571', '-p', '127.0.0.1:4510-4559:4510-4559', '-e', 'LOCALSTACK_API_KEY=xxxxxx', '-e', 'DEBUG=1', '-e', 'DISABLE_CORS_CHECKS=1', '-e', 'TEST_AWS_ACCOUNT_ID=000000000000', '-e', 'DEFAULT_REGION=us-east-1', '-e', 'DOCKER_HOST=unix:///var/run/docker.sock', '-e', 'HOST_TMP_FOLDER=/opt/homebrew/lib/python3.10/site-packages/.filesystem/var/lib/localstack/tmp', '-e', 'SET_TERM_HANDLER=1', 'localstack/localstack']
``` 

So it seems to me, that the localstack cli is not adding the REQUIRE_PRO and SMTP_* options to the docker run command.

### Expected Behavior

With the REQUIRE_PRO option and no localstack pro API key, localstack shouldn't start.
With API Key and SMTP_* options, cognito should be able to send emails.

In general, all configuration options mentioned in the documentation should work with the localstack CLI.

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    localstack start

### Environment

```markdown
- OS: MacOS 12.1 arm64
- LocalStack: 1.2.0
```

**Comment by alexrashed** [comment]
This seems to be related to #8039. Since this issue is quite old, and the structure of localstack has changed a lot (cli packages have changed, images have been separated), I will close this one as a duplicate and would like to foster a discussion / a resolution in the new ticket. Please feel free to chime in there! Thanks!
