### ISSUE TITLE
bug: No 'accept-ranges' header for mp4 files

### ISSUE THREAD

**Issue by leszko** [localstack/localstack#7114]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

For MP4 files, there is no `accept-ranges` header in the HTTP response.

```
$ curl --head -v http://localhost:4566/rafal-bucket/Big_Buck_Bunny_1080_10s_1MB.mp4
*   Trying 127.0.0.1:4566...
* Connected to localhost (127.0.0.1) port 4566 (#0)
> HEAD /rafal-bucket/Big_Buck_Bunny_1080_10s_1MB.mp4 HTTP/1.1
> Host: localhost:4566
> User-Agent: curl/7.84.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 
HTTP/1.1 200 
< content-type: video/mp4
content-type: video/mp4
< Content-Length: 1046987
Content-Length: 1046987
< Server: Werkzeug/2.1.2 Python/3.10.8
Server: Werkzeug/2.1.2 Python/3.10.8
< Date: Fri, 28 Oct 2022 11:26:46 GMT
Date: Fri, 28 Oct 2022 11:26:46 GMT
< content-md5: pRepzzwMELsAy2FU3y+9Lg==
content-md5: pRepzzwMELsAy2FU3y+9Lg==
< ETag: "a517a9cf3c0c10bb00cb6154df2fbd2e"
ETag: "a517a9cf3c0c10bb00cb6154df2fbd2e"
< last-modified: Fri, 28 Oct 2022 09:34:14 GMT
last-modified: Fri, 28 Oct 2022 09:34:14 GMT
< x-amzn-requestid: 6K0zdGWEQDWmcVDF8xwMQIbdGhrHhsQ9SUzGPQnnxuyaAo5vIsMK
x-amzn-requestid: 6K0zdGWEQDWmcVDF8xwMQIbdGhrHhsQ9SUzGPQnnxuyaAo5vIsMK
< Access-Control-Allow-Origin: *
Access-Control-Allow-Origin: *
< Connection: close
Connection: close
< x-amz-request-id: 695FC1F0668BEBE5
x-amz-request-id: 695FC1F0668BEBE5
< x-amz-id-2: MzRISOwyjmnup695FC1F0668BEBE57/JypPGXLh0OVFGcJaaO3KW/hRAqKOpIEEp
x-amz-id-2: MzRISOwyjmnup695FC1F0668BEBE57/JypPGXLh0OVFGcJaaO3KW/hRAqKOpIEEp
< date: Fri, 28 Oct 2022 11:26:46 GMT
date: Fri, 28 Oct 2022 11:26:46 GMT
< server: hypercorn-h11
server: hypercorn-h11

< 
* Closing connection 0
```

### Expected Behavior

Video files should return the `accept-ranges` header.

### How are you starting LocalStack?

With a `docker run` command

### Steps To Reproduce

1. Start localstack with docker
2. Upload a video file into a bucket
3. CURL for headers to check that no `accept-ranges` header is included.

### Environment

```markdown
- OS: macos
- LocalStack: 1.2.0
```

**Comment by steffyP** [comment]
Hi @leszko, 

thanks for reporting! We are currently working to improve s3 and will keep you updated.

**Comment by steffyP** [comment]
Hi @leszko,

we have recently added a [new and improved provider for S3](https://discuss.localstack.cloud/t/localstack-release-v1-3-0/170#migration-of-s3-and-lambda-to-asf-provider-4), that should fix your reported issue.

Could you please use either image version `1.3.0` or  `latest` and try to set one of the following environment variables in order to activate the ASF S3 Provider:
`PROVIDER_OVERRIDE_S3=asf` (if you are using the community version)
`PROVIDER_OVERRIDE_S3=asf_pro` (if you are using the LocalStack Pro).

Thank you!

**Comment by leszko** [comment]
I made a test and it worked fine. Thanks for the fix. 

Just wonder, why isn't it enabled by default, but one has to specify `PROVIDER_OVERRIDE_S3=asf`? I tried without any env variable and then the bug still exists.

**Comment by steffyP** [comment]
Hi @leszko,

great to hear that it works now! 

> Just wonder, why isn't it enabled by default, but one has to specify PROVIDER_OVERRIDE_S3=asf

As stated in our [release notes](https://discuss.localstack.cloud/t/localstack-release-v1-3-0/170#migration-of-s3-and-lambda-to-asf-provider-4), we are re-writing some of our old implementation to use the new ASF provider pattern (you can read [here about the AWS Server Framework](https://localstack.cloud/blog/2022-08-04-parity-explained/), in case you are interested). 

Long story short: the new provider more transparent handling of requests, and as we move services to the new ASF providers, we only fix bugs in the ASF providers. 

As S3 is one very important service, we didn't want to move from the old to the new provider instantly. We did a lot of testing of course, but there might also be things we missed. Therefore, we are using the feature flag, starting from version `1.3.0`. Starting from version `2.0.0` the new ASF provider will be the default (but there will still be the possibility to use the old one for a while, before it will be removed). 

If you find any issues with the new S3 provider, please do not hesitate to report it!
