### ISSUE TITLE
bug:  "localstack start" results in KeyError "State"

### ISSUE THREAD

**Issue by cons0l3** [localstack/localstack#7133]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After installing localstack in a fresh condaenv (versions see below), and trying to start it via `localstack start` it results in a KeyError for "State". During the start it seems localstack executes `docker ps --format '{{ json . }}'`. The resulting json does not contain the key "State".

```
DEBUG:localstack.utils.run:Executing command: ['docker', 'ps', '--format', '{{json . }}']
Traceback (most recent call last):
  File "C:\tools\Anaconda3\envs\localstack-play\Scripts\localstack", line 23, in <module>
    main()
[...]
get_running_container_names
    result = self.list_containers(all=False)
  File "C:\tools\Anaconda3\envs\localstack-play\lib\site-packages\localstack\utils\container_utils\docker_cmd_client.py", line 229, in list_containers
    "status": container["State"],
KeyError: 'State'
```

### Expected Behavior

it should start localstack docker via cli (as it used to in the past ;-))

### How are you starting LocalStack?

With the `localstack` script

### Steps To Reproduce

1. install localstack (with versions see below)
2. start localstack via `localstack start`

### Environment

```markdown
python==3.9.13
pip==22.2.2
localstack==1.2.0
docker-server==20.10.20
docker-compose==2.12.1
docker-cli==19.03.12
OS: windows 11 22H2
```

**Comment by HarshCasper** [comment]
Hi 👋 

Can you please share how you have installed LocalStack? I see that you are using a Conda environment. 

Have you also tried running LocalStack via Docker or Docker-Compose? Please follow our [documentation](https://docs.localstack.cloud/get-started/)

**Comment by cons0l3** [comment]
Hi,
even though I use a conda env, I have installed via `pip install localstack`. I am trying to start with `localstack start`. When starting via `docker run --rm -it -p 4566:4566 -p 4510-4559:4510-4559 localstack/localstack` The container starts flawlessly. 

```log
Waiting for all LocalStack services to be ready
2022-11-06 19:30:57,605 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2022-11-06 19:30:57,607 INFO supervisord started with pid 16
2022-11-06 19:30:58,610 INFO spawned: 'infra' with pid 21
2022-11-06 19:30:59,612 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

LocalStack version: 1.2.1.dev
LocalStack build date: 2022-11-04
LocalStack build git hash: a4d60b3f

2022-11-06T19:31:00.431  WARN --- [-functhread5] hypercorn.error            : ASGI Framework Lifespan error, continuing without Lifespan support
2022-11-06T19:31:00.431  WARN --- [-functhread5] hypercorn.error            : ASGI Framework Lifespan error, continuing without Lifespan support
2022-11-06T19:31:00.434  INFO --- [-functhread5] hypercorn.error            : Running on https://0.0.0.0:4566 (CTRL + C to quit)
2022-11-06T19:31:00.434  INFO --- [-functhread5] hypercorn.error            : Running on https://0.0.0.0:4566 (CTRL + C to quit)
Ready.
```

```bash
ps> docker ps --format "{{ json . }}"
{
  "Command": "\"docker-entrypoint.sh\"",
  "CreatedAt": "2022-11-06 20:28:27 +0100 CET",
  "ID": "91afe8b7ee2a",
  "Image": "localstack/localstack",
  "Labels": "maintainer=LocalStack Team (info@localstack.cloud),authors=LocalStack Contributors,description=LocalStack Docker image",
  "LocalVolumes": "1",
  "Mounts": "b40cf9f5eb93bd…",
  "Names": "amazing_buck",
  "Networks": "bridge",
  "Ports": "0.0.0.0:4510-4559->4510-4559/tcp, 0.0.0.0:4566->4566/tcp, 5678/tcp",
  "RunningFor": "54 seconds ago",
  "Size": "0B",
  "Status": "Up 50 seconds (healthy)"
}
```
But, when I try to use `localstack status` or any `localstack logs` on the started localstack docker container, it throws the same exception KeyError: "State" in the construction of the dict `"status": container['State']` KeyError "State` (see above).

Personally, I think that `docker ps` does not have a "State" key, but a "Status" key in the dict. Maybe a rename has happend?

I also have tried the docker-compose route. A `localstack config validate` results in 
```bash
✔ config valid
```

I have attached the `docker version` additionally:
```
Client:
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.12
 Git commit:        0ed913b8-
 Built:             07/28/2020 16:36:03
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Desktop 4.13.1 (90346)
 Engine:
  Version:          20.10.20
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.7
  Git commit:       03df974
  Built:            Tue Oct 18 18:18:35 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.8
  GitCommit:        9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by cons0l3** [comment]
When running under "wsl" I have a docker-cli version 20.10.20. A `wsl> docker ps --format "{{ json . }}" | jq`  contains the "State" key. The docker-cli 19.03.12 seems to be incomaptibe. I will upgrade my windows "docker.exe". This requires a reboot LoL. I will come back with the results.

**Comment by cons0l3** [comment]
I have managed to upgrade the docker-cli to version 20.10.20. I was fight some "choco" issues with properly uninstalling. Windows, LoL. The upgraded version of the client fixed it. Thanks for your support.
