### ISSUE TITLE
Using additional files within init script

### ISSUE THREAD

**Issue by IvanDanilau** [localstack/localstack#7136]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

I have the following init script:

```
import os

import yaml


def init_pub_sub():
    with open('config.yaml', 'r') as file:
        config = yaml.safe_load(file)
        for topic in config["aws"]["pub-sub"]["topics"]:
            create_topic(topic)
        for subscription_group, subscriptions in config["aws"]["pub-sub"]["subscription"].items():
            for subscription in map(lambda subscr: f"{subscription_group}-{subscr}", subscriptions):
                create_subscription(subscription)
```
So I would like to have possibility add to the volume additional yaml file, not only .py or .sh. Or at least few py files, and store constants in one of them

**Comment by simonrw** [comment]
Hi @IvanDanilau, thanks for this report. Currently the reason the file cannot be found is that when your script is run in the localstack container, its current working directory is not where your init script is. Init scripts are mounted under e.g. `/etc/localstack/init/ready.d` but the current working directory of your script is different to that. This means it cannot find your `config.yml` file. You could hard-code the absolute path to your config file, e.g. `/etc/localstack/init/ready.d/config.yml`, which would work now, or you could use the path relative to this current script (*note*: this would require changes to localstack), e.g.:

```python
from pathlib import Path

config_file = Path(__file__).parent / "config.yml"
with config_file.open() as file:
    # continue as usual
```

Would hard-coding the path be satisfactory for now, while we work out the best way to progress on our side?

**Comment by IvanDanilau** [comment]
That's work for now, thank you! Anyway for yaml case I need to install yaml module. Go with workaround
