### ISSUE TITLE
bug: Creation of AWS SES using localstack

### ISSUE THREAD

**Issue by dazn-ritesh** [localstack/localstack#7140]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

I was not able to create an AWS SES using localstack . I have been trying for days but was not able to figure the mistake. I get this error whenever I execute my tests - java.lang.IllegalStateException: Service to port mapping has not been determined yet.

### Expected Behavior
Should able to create a AWS SES

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker compose up

----------------------------- docker-compose.yml
version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "4566:4566"            # LocalStack Gateway
      - "8082:8082"            # LocalStack Gateway
      
    environment:
      - DEBUG=${DEBUG-}
      - PERSISTENCE=${PERSISTENCE-}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY-}  # only required for Pro
      - DOCKER_HOST=unix:///var/run/docker.sock
      - PORT_WEB_UI=8082
      - AWS_DEFAULT_REGION=eu-central-1
      - AWS_SECRET_ACCESS_KEY=kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk
      - AWS_ACCESS_KEY_ID=asndkjnsajdnsajdnasjnd
      - SMTP_HOST=localhost
      - SMTP_USER=test
      - SMTP_PASS=test
      - SMTP_EMAIL=sender@example.com      
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

### Environment

```markdown
- OS:windows
- LocalStack:latest
```

### Anything else?

version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "4566:4566"            # LocalStack Gateway
      - "8082:8082"            # LocalStack Gateway
      
    environment:
      - DEBUG=${DEBUG-}
      - PERSISTENCE=${PERSISTENCE-}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY-}  # only required for Pro
      - DOCKER_HOST=unix:///var/run/docker.sock
      - PORT_WEB_UI=8082
      - AWS_DEFAULT_REGION=eu-central-1
      - AWS_SECRET_ACCESS_KEY=kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk
      - AWS_ACCESS_KEY_ID=asndkjnsajdnsajdnasjnd
      - SMTP_HOST=localhost
      - SMTP_USER=test
      - SMTP_PASS=test
      - SMTP_EMAIL=sender@example.com      
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

**Comment by viren-nadkarni** [comment]
Hi @dazn-ritesh, could you please try the suggestion in https://github.com/localstack/localstack/issues/1970?
