### ISSUE TITLE
bug: RDS Data interface type mismatch

### ISSUE THREAD

**Issue by comppaz** [localstack/localstack#7141]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The current implementation of the RDS Data API for Postgres returns the following structure for the metadata of a column in its response set: 

`"ColumnMetadata": {
   ... 
   "nullable": true / false, 
   ...
}`

This leads to an unmarshal error in the Go AWS SDK.

### Expected Behavior

It should return an Integer instead of a Boolean according to the AWS documentation: 
https://docs.aws.amazon.com/pt_br/rdsdataservice/latest/APIReference/API_ColumnMetadata.html

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    localstack start

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    We are accessing the client through the Go AWS SDK.

### Environment

```markdown
- OS: macOS Ventura 13.0
- LocalStack:latest
```

**Comment by steffyP** [comment]
Hi @comppaz,

thanks for reporting! The issue should be fixed in the `latest` version. 
Please run `docker pull localstack/localstack:latest` and let us know if your use case is working now!
