### ISSUE TITLE
bug: Getting service to port mapping has not been determined yet.

### ISSUE THREAD

**Issue by dazn-ritesh** [localstack/localstack#7143]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I'm trying to create LocalStack as a testcontainer in my springboot application. I am getting 
```
java.lang.IllegalStateException: Service to port mapping has not been determined yet.  
```

Code for test container creation.
```
  @ClassRule
  public static final LocalStackContainer localStackContainer =
    new LocalStackContainer(DockerImageName.parse("localstack/localstack").withTag("0.14.2"))
      .withServices(Service.SES)
      .withEnv("AWS_ACCESS_KEY_ID", "accesskey")
      .withEnv("AWS_SECRET_ACCESS_KEY", "secretkey");
```

---------------------------------------------------------------------------------------------------

Code for AwsSes client creation:

    public MailSender localMailSender(AmazonSimpleEmailService amazonSimpleEmailService) {
      String someEndpoint= Localstack.INSTANCE.getEndpointSES();
      EndpointConfiguration endpoint = new EndpointConfiguration(someEndpoint, "eu-central-1");
      return new SimpleEmailServiceMailSender(AmazonSimpleEmailServiceClientBuilder
        .standard()
        .withEndpointConfiguration(endpoint)
        .withCredentials(new AWSStaticCredentialsProvider(new AnonymousAWSCredentials()))
        .build());
    }

### Expected Behavior

Ideally this should create a mock Aws Ses server.

### How are you starting LocalStack?

Custom (please describe below)

### Steps To Reproduce

I am starting it in java code as I am running it as a test container.

### Environment

```markdown
- OS:windows
- LocalStack:lts
```

**Comment by silv-io** [comment]
Hi @dazn-ritesh, I'm noticing that you're using the outdated `0.14.2` version. Since then we had a couple of big releases (among it `1.0`). Can you please try using the `latest` tag, or the `1.2.0` tag?
