### ISSUE TITLE
bug: s3 `Location` parameter for `samlocal package` followed by `samlocal deploy` isn't usable

### ISSUE THREAD

**Issue by bamajap** [localstack/localstack#7144]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Same issue as #4965 - that issue was closed, but the problem is still happening, so this is to re-open it.

### Expected Behavior

See #4965 

### How are you starting LocalStack?

With the `localstack` script

### Steps To Reproduce

See #4965 

### Environment

```markdown
- OS: any
- LocalStack: latest
```

**Comment by steffyP** [comment]
Hi @bamajap,
can you please confirm you are using the latest `samlocal`?
`$ pip list | grep aws-sam-cli-local`

**Comment by bamajap** [comment]
> Hi @bamajap, can you please confirm you are using the latest `samlocal`?
`$ pip list | grep aws-sam-cli-local`

Done:
`aws-sam-cli-local   1.55.0`

**Comment by macnev2013** [comment]
Thank you for reporting the issue @bamajap. We couldn't replicate it in the latest `LocalStack` version. Could you please try with the `latest` version and update me if the issue persists?

Thank you.
