### ISSUE TITLE
bug: API Gateway Websocket "RouteSelectionExpression" should be ignored for $connect and $disconnect routes

### ISSUE THREAD

**Issue by fmaronnaud** [localstack/localstack#7153]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Create a new websocket api using the following:
```
WebSocketApiGateway:
      Type: AWS::ApiGatewayV2::Api
      Properties:
        Name: ${self:custom.serviceName}
        Description: "Websocket api gateway"
        ProtocolType: WEBSOCKET
        RouteSelectionExpression: "$request.body.foobar"
```

- When connecting/disconnecting to/from the API, the `$connect` and `$disconnect` routes integration are not triggered since it's looking for `$request.body.foobar` defined in the RouteSelectionExpression
- All other routes work w/ the defined RouteSelectionExpression `$request.body.foobar`

### Expected Behavior

Create a new websocket api using the following:
```
WebSocketApiGateway:
      Type: AWS::ApiGatewayV2::Api
      Properties:
        Name: ${self:custom.serviceName}
        Description: "Websocket api gateway"
        ProtocolType: WEBSOCKET
        RouteSelectionExpression: "$request.body.foobar"
```

- When connecting/disconnecting to/from the API, the `$connect` and `$disconnect` routes integration are triggered since it's ignoring the RouteSelectionExpression `$request.body.foobar` and use instead `$request.body.action`
- All other routes work w/ the defined RouteSelectionExpression `$request.body.foobar`

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

`docker-compose up`
   
```
version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack:latest
    network_mode: bridge
    ports:
      - "127.0.0.1:53:53"                
      - "127.0.0.1:81:80"                
      - "127.0.0.1:53:53/udp"            
      - "127.0.0.1:447:443"            
      - "127.0.0.1:4510-4530:4510-4530"  
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4571:4571"
    environment:
      - SERVICES=${SERVICES- }
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - LAMBDA_EXECUTOR=docker
      - LOCALSTACK_API_KEY=XXXXXXX
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=C:\localstack\tmp
      - DOCKER_FLAGS=1
      - EXTRA_CORS_ALLOWED_HEADERS=sentry-trace
      #- LAMBDA_DOCKER_NETWORK=development
    volumes:
      - 'C:\temp:/var/lib/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'

volumes:
  localstack-vol:
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal s3 mb s3://mybucket

### Environment

```markdown
- OS:Windows 10
- LocalStack: 1.2.1.dev
```

**Comment by fmaronnaud** [comment]
Hi folks,

I was wondering if I could have some updates on this and realize that more explanation could be useful to you too.

By default, the API gateway route selection expression is equal to `$request.body.action`. When that route selection expression is evaluated, it will produce a route key. You can then map actions against route keys.

Let's now assume two scenarios:

**_Scenario1:_** A user connect to the websocket and send a message with the following payload:
```
{
  "action": "hello"
}
```

**_Scenario2:_** A user connect to the websocket and send a message with the following payload:
```
{
  "foo": "hello"
}
```

Now let's assume we have two websockets with the same list of route keys ($default, $connect, $disconnect, $hello):

**_Websocket1:_** 
no custom route selection expression
**_Websocket2:_** 
custom route selection expression equal to `$request.body.foo`


### Expected:
- Scenario1/Websocket1: websocket is connected ($connect) and actions mapped to the "hello" route are executed.
- Scenario1/Websocket2: websocket is connected ($connect) but the default ($default) route actions are executed.
- Scenario2/Websocket1: websocket is connected ($connect) but the default ($default) route actions are executed.
- Scenario2/Websocket2: websocket is connected ($connect) and actions mapped to the "hello" route are executed.

### Current:
- Scenario1/Websocket1: websocket is connected ($connect) and actions mapped to the "hello" route are executed.
- Scenario1/Websocket2: websocket is NOT connected ($connect) and ONLY the default ($default) route actions are executed.
- Scenario2/Websocket1: websocket is connected ($connect) but the default ($default) route actions are executed.
- Scenario2/Websocket2: websocket is NOT connected ($connect), the default ($default) route actions are executed and actions mapped to the "hello" route are executed.


I believe the 3 predefined routes ($connect/$disconnect/$default) should always ignore the API route selection expression.

Please let me know if you need anything else, happy to directly connect if necessary.

Thank you

**Comment by whummer** [comment]
Thanks for reporting @fmaronnaud , and apologies for the long delay. We have now pushed a couple of enhancements for API Gateway WebSocket APIs, including better parity with AWS around `$connect`/`$disconnect` routes. When you get a chance, can you please pull the `latest` Docker image and give it another try? Thanks for your help!

**Comment by fmaronnaud** [comment]
Hi there,

I confirm everything works now as expected. Thank you very much

**Comment by fmaronnaud** [comment]
Hi folks,

After more testing we realized that the route selection expression is still used for the predefined routes (`$connect`/`$disconnect`).
It's a little bit better as it was before as the websocket seems to still keep the connection open, however the lambda associated to the predefined routes are never triggered and it's using the $default route instead.

Please see the following logs when using the following web socket route selection expression: `$request.body.detail-type`

```
localstack_main | LocalStack version: 1.4.1.dev
localstack_main | LocalStack Docker container id: 9012bc22a434
localstack_main | LocalStack build date: 2023-03-03
localstack_main | LocalStack build git hash: f51e5e23
....
localstack_main | 2023-03-08T22:56:09.920 DEBUG --- [ncthread1034] l.s.a.integrations         : Unable to extract API Gateway route (result: ) - expression "$request.body.detail-type", context: {'request': {'body': {'action': '$connect'}}}
localstack_main | 2023-03-08T22:56:09.922 DEBUG --- [ncthread1034] l.s.apigateway.authorizers : Processing API V2 invocation
localstack_main | 2023-03-08T22:56:09.923 DEBUG --- [ncthread1034] l.s.a.integrations         : Invoking Lambda arn:aws:lambda:us-east-1:000000000000:function:foo-bar-default for integration of API ID e52ea415
localstack_main | 2023-03-08T22:56:09.933 DEBUG --- [uest_thread)] l.s.awslambda.lambda_api   : Running lambda arn:aws:lambda:us-east-1:000000000000:function:foo-bar-default
```
