### ISSUE TITLE
bug: CloudWatch PutMetricData with arrays of values not working

### ISSUE THREAD

**Issue by kshangx** [localstack/localstack#7154]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

PutMetricData with arrays of values does not work properly. Zero values seem to be published. PutMetricData with a single value works as expected. This happens to both CLI and SDK.

### Expected Behavior

PutMetricData with arrays of values should work as publishing a single value.

### How are you starting LocalStack?

With a `docker run` command

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack:1.2.0

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)
```
awslocal cloudwatch put-metric-data --namespace test --metric-data MetricName=TestCounter,Values=10,1,Counts=1,1
awslocal cloudwatch get-metric-statistics --namespace test --metric-name TestCounter --statistics Maximum --period 60 --start-time 2022-11-9T00:00:00Z --end-time 2022-11-11T00:00:00Z
{
    "Label": "TestCounter",
    "Datapoints": [
        {
            "Timestamp": "2022-11-09T23:25:10+00:00",
            "Maximum": 0.0,
            "ExtendedStatistics": {}
        },
        {
            "Timestamp": "2022-11-09T23:27:10+00:00",
            "Maximum": 0.0,
            "ExtendedStatistics": {}
        }
    ]
}
```

### Environment

```markdown
- OS: Mac Monterey
- LocalStack: 1.2.0
```

**Comment by crestonbunch** [comment]
Perhaps this is a different issue, but I believe StatisticValues are also broken.

```
aws --endpoint=http://localhost:4566 cloudwatch put-metric-data --namespace test --statistic-values "Maximum=10,Minimum=1,Sum=50,SampleCount=5" --timestamp 2022-11-15T18:00:00Z --unit Count --metric-name "TestMetric"
```

```
aws --endpoint=http://localhost:4566 cloudwatch get-metric-statistics --metric-name TestMetric --namespace test --start-time 2022-11-15T00:00:00Z --end-time 2022-11-15T20:00:00Z --period 60 --statistics Average
{
    "Label": "TestMetric",
    "Datapoints": [
        {
            "Timestamp": "2022-11-15T18:00:00+00:00",
            "Average": 0.0,
            "Unit": "Count",
            "ExtendedStatistics": {}
        }
    ]
}
```

**Comment by steffyP** [comment]
Hi @crestonbunch,

could you please elaborate on the expected outcome of your example? If you already tested it against AWS it would be very helpful if you could also add your findings here!

I would kindly ask you to create another github issue for this, as it doesn't seem to be directly related.
The original issue with array of values for `metric-data` is due to a missing implementation of parsing the array.

**Comment by steffyP** [comment]
Hi @kshangx, 
the issue with using a list of values for `PutMetricData` has been fixed. Please pull the `latest` image from docker.

@crestonbunch I will create a new issue with the `statistic-values` as it will be fixed separately.
