### ISSUE TITLE
Error getaddrinfo EAI_AGAIN when making api call from lambda (nodejs)

### ISSUE THREAD

**Issue by mfedorovich-trolley** [localstack/localstack#7155]
Hello, 

I am getting a bizarre error (EAI_AGAIN) trying to call an API (any public API) from nodeJS executed in Lambda. The same call ran from my local environment works well.  

Here are some details:

- Localstack running as a docker container
- Image Version: 1.2.0 (also tried the latest)
- Lambda Runtime Environment: NODEJS_16_X
- DOCKER Environment variables
      - SERVICES=serverless,cognito,rds,sqs,sns,cloudformation,kms 
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LAMBDA_EXECUTOR=docker
      - HOST_TMP_FOLDER=${TMPDIR}
      - LOCALSTACK_API_KEY=xxxxxxx (masked - I am using PRO edition)
      - LAMBDA_DOCKER_NETWORK=host 
      - DNS_ADDRESS=1.1.1.1
      - LAMBDA_DOCKER_DNS=1.1.1.1
      - DEFAULT_REGION=us-east-1
- Error:
getaddrinfo EAI_AGAIN api.fungenerators.com
>     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26) {
>   errno: -3001,
>   code: 'EAI_AGAIN',
>   syscall: 'getaddrinfo',
>   hostname: 'api.fungenerators.com',
>   config: {
>     transitional: {
>       silentJSONParsing: true,
>       forcedJSONParsing: true,
>       clarifyTimeoutError: false
>     },
>     adapter: [Function: httpAdapter],
>     transformRequest: [ [Function: transformRequest] ],
>     transformResponse: [ [Function: transformResponse] ],
>     timeout: 0,
>     xsrfCookieName: 'XSRF-TOKEN',
>     xsrfHeaderName: 'X-XSRF-TOKEN',
>     maxContentLength: -1,
>     maxBodyLength: -1,
>     validateStatus: [Function: validateStatus],
>     headers: {
>       Accept: 'application/json, text/plain, */*',
>       'User-Agent': 'axios/0.23.0'
>     },
>     method: 'get',
>     url: 'https://api.fungenerators.com/name/categories.json?start=0&limit=5',
>     data: undefined
>   },
>   request: <ref *1> Writable {
>     _writableState: WritableState {
>       objectMode: false,
>       highWaterMark: 16384,
>       finalCalled: false,
>       needDrain: false,
>       ending: false,
>       ended: false,
>       finished: false,
>       destroyed: false,
>       decodeStrings: true,
>       default...

Please advise,

Thanks!

**Comment by dfangl** [comment]
Hi!
First of all: please do not use `DNS_ADDRESS=1.1.1.1`. The DNS_ADDRESS variable specifies the bind address of the dns server, and should not be altered in the container. (even though LocalStack should override this).

Can you try your setup using the default docker-compose file specified here: https://github.com/localstack/localstack/blob/master/docker-compose-pro.yml . Host networking is not supported, and there are a couple more issues with your configuration, so it is easier to start afresh.
