### ISSUE TITLE
bug: Permission problems

### ISSUE THREAD

**Issue by dirkoberhaus** [localstack/localstack#7163]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We are using Localstack with our Openshift Cluster. The default behavior is, that every pod gets a random UID.
With the current Localstack Image we get the following error:

`/usr/local/bin/docker-entrypoint.sh: line 73: /var/lib/localstack/logs/localstack_infra.log: Permission denied`

Reproducible with following command: 

`docker run -ti --rm --user 6666 localstack/localstack:1.2.0`

From inspecting the dockerfile I would expect "rwx" permissions for user/group/others but in the running container I can see that group and others have only "rx" permissions. I think the permissions will be changed because the original directory /var/lib/localstack will be copied into a volume. 

Is it possible to remove this volume from dockerfile?

### Expected Behavior

`docker run -ti --rm --user 6666 localstack/localstack:1.2.0`

starts localstack without permission problems

### How are you starting LocalStack?

Custom (please describe below)

### Steps To Reproduce

localstack will be startet es container from put Gitllab Runner (Kubernetes/Openshift) because we use it as service in a pipeline job.

### Environment

```markdown
- OS:RedHat
- LocalStack:1.2.0 (latest)
```

**Comment by dschiavu** [comment]
Has this one been solved in the latest release? I'm experiencing exactly the same issue, however I'm running LocalStack inside a Docker on AWS CodeBuild.

**Comment by alexrashed** [comment]
Hi @dschiavu!
Could you please perform your tests with these versions? If you are facing issues, could you please create a new GitHub issue with a detailed description how to reproduce your issue, and with the logs of the localstack container?
Thanks!
