### ISSUE TITLE
feature request: Add support for AppSync Pipeline Resolvers

### ISSUE THREAD

**Issue by silv-io** [localstack/localstack#7172]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Add support for pipeline resolvers as described here: 

https://docs.aws.amazon.com/appsync/latest/devguide/pipeline-resolvers.html

**Comment by amitassaraf** [comment]
Would love this too!

**Comment by whummer** [comment]
Hi @amitassaraf , quick update - we have now pushed a few enhancements to add initial support for pipeline resolvers (available in the `latest` Docker image). 

You can now define pipeline resolvers as a sequence of processing functions, each with request/response mapping templates, including features like the `$ctx.stash` or `$ctx.result` variable to transfer state across pipeline stages.

Please note that the logic of functions currently still relies on VLT templates - JavaScript functions in resolvers are not yet available, but will be added in an upcoming version shortly.

Hope that helps as a starting point. It would be great if you could share more details about your requirements, ideally a few snippets of your client application, so we can ensure that your use case is covered. Thanks for your help!
