### ISSUE TITLE
bug: Non-existent KMS key does not return an error when passed through S3 copyObject and putObject

### ISSUE THREAD

**Issue by kdelalic** [localstack/localstack#7177]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

copyObject and putObject (and perhaps other requests) requests are accepted and do not return an error when an SSE KMS key is specified. 

### Expected Behavior

The error which should be returned is KMS.NotFoundException.

### How are you starting LocalStack?

Custom (please describe below)

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    Localstack testcontainers 

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

   Call copyObject/putObject via latest version using AWS SDK V2 and specific a ssekmsKeyId.

```java
final var copyObjectRequestBuilder =
        CopyObjectRequest.builder()
            .serverSideEncryption(ServerSideEncryption.AWS_KMS)
            .ssekmsKeyId("NON-EXISTENT KMS KEY")
            .sourceBucket(sourceBucketName)
            .sourceKey(sourceKey)
            .destinationBucket(destinationBucket)
            .destinationKey(destinationKey);
final var copyObjectResponse = sourceRegionS3Client.copyObject(copyObjectRequest); // Error should be thrown here but localstack does not return an error
```

### Environment

```markdown
- OS: MacOS 13.0
- LocalStack: Latest (v1.2.0)
```

**Comment by bentsku** [comment]
Hi @kdelalic and thanks for your report!

This feature has been added with #7448, however it will only be available with the new implementation of S3 that we have been working on, available under a feature flag. You can use this new implementation with `PROVIDER_OVERRIDE_S3=asf` (for configuration of LocalStack, you can see [here](https://docs.localstack.cloud/references/configuration/)). An additional feature flag for the specific validation of the KMS key needs to be set as well, to not introduce a breaking change: `S3_SKIP_KMS_KEY_VALIDATION=0` needs to be set.

You can give a try by pulling the `latest` image of `localstack`. Thank you!
