### ISSUE TITLE
bug: access token not working with Appsync Cognito User Pool Auth.

### ISSUE THREAD

**Issue by dpretty** [localstack/localstack#7178]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Appsync returns HTTP 401 when using the `Authorization: <accessToken>` header

### Expected Behavior

I have tested against AWS that the following auth headers work:

 - `Authorization: <accessToken>`
 - `Authorization: Bearer <accessToken>`
 - `Authorization: <idToken>`
 - `Authorization: Bearer <idToken>`
 
Importantly,[ the amplify-js library uses the `Authorisation: <accessToken>` header](https://github.com/aws-amplify/amplify-js/blob/e1b0b5be3e8ccb3c76e8e2e2f43f910d40d73254/packages/api-graphql/src/GraphQLAPI.ts#L174), which is not currently working with localstack.
 
 Localstack appears to currently support only  the `Authorization: Bearer <idToken>` header.
 
 

### How are you starting LocalStack?

With the `localstack` script

### Steps To Reproduce

I have created a minimal CDK project which reproduces the issue in a failing test case:

https://github.com/LaunchlabAU/localstack-testing

See README for steps to reproduce

### Environment

```markdown
- OS: both macOS 13.0 and Arch Linux
- LocalStack: latest
```

**Comment by MarcelStranak** [comment]
Hi @dpretty.
We have now implemented changes which, we hope, will resolve the issue. Please update the Docker image (`docker pull localstack/localstack-pro:latest`) and try again. 

Thank you.

**Comment by dpretty** [comment]
Thanks @MarcelStranak I can confirm the issue is resolved.

**Comment by fancywriter** [comment]
@MarcelStranak  could you confirm which exact change caused and solved this and which versions are affected (and which are not)?
