### ISSUE TITLE
bug: Cannot kms import-key-material

### ISSUE THREAD

**Issue by nmguse-bighealth** [localstack/localstack#7199]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After starting localstack (via docker image `localstack/localstack`), I am attempting to import a KMS key. It appears that the PublicKey returned by get-parameters-for-import may be invalid.

These exact same commands work perfectly, when using aws, but not awslocal.

Error:
```
unable to load Public Key
pkeyutl: Error initializing context
140667184231616:error:0D0680A8:asn1 encoding routines:asn1_check_tlen:wrong tag:../crypto/asn1/tasn_dec.c:1149:
140667184231616:error:0D07803A:asn1 encoding routines:asn1_item_embed_d2i:nested asn1 error:../crypto/asn1/tasn_dec.c:309:Type=X509_ALGOR
140667184231616:error:0D08303A:asn1 encoding routines:asn1_template_noexp_d2i:nested asn1 error:../crypto/asn1/tasn_dec.c:646:Field=algor, Type=X509_PUBKEY
```

### How are you starting LocalStack?

With a `docker run` command

### Steps To Reproduce

Note, this basically copies the guide: https://docs.aws.amazon.com/kms/latest/developerguide/importing-keys-get-public-key-and-token.html

Can test this with openssl bundled with the same localstack image (after starting localstack separately):
`docker run --rm --entrypoint sh -it localstack/localstack`

```
openssl rand -out PlaintextKeyMaterial.bin 32

key_id=$(awslocal kms create-key --origin EXTERNAL --query "KeyMetadata.KeyId" --output text)
awslocal kms get-parameters-for-import --key-id $key_id --wrapping-algorithm RSAES_OAEP_SHA_1 --wrapping-key-spec RSA_2048 --query "ImportToken" --output text > ImportToken.b64
openssl enc -d -base64 -A -in ImportToken.b64 -out ImportToken.bin

awslocal kms get-parameters-for-import --key-id $key_id --wrapping-algorithm RSAES_OAEP_SHA_1 --wrapping-key-spec RSA_2048 --query "PublicKey" --output text > PublicKey.b64
openssl enc -d -base64 -A -in PublicKey.b64 -out PublicKey.bin

openssl pkeyutl \
    -in PlaintextKeyMaterial.bin \
    -out EncryptedKeyMaterial.bin \
    -inkey PublicKey.bin \
    -keyform DER -pubin \
    -encrypt \
    -pkeyopt rsa_padding_mode:oaep \
    -pkeyopt rsa_oaep_md:sha1
```

### Environment

```markdown
- LocalStack: docker localstack/localstack
```

**Comment by sannya-singal** [comment]
Hey @nmguse-bighealth, I'll close this issue. Thanks again for the report and if you encounter any other issues, feel free to open another issue.
