### ISSUE TITLE
feature request: Lambda ASF provider code hot-reload

### ISSUE THREAD

**Issue by dfangl** [localstack/localstack#7200]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

The new ASF provider should feature the option for hot reloading for all supported languages.
It should only restart environments when necessary, and should be easy to use.

### 🧑‍💻 Implementation

Any volume mounts should be readonly.
Probably a filewatcher on the mounted directory with debounced infrastructure restart in the environments.

**Comment by uriyaka** [comment]
Can't wait to use this feature. This is the key thing that can turn LocalStack to a truly viable solution for our team.

**Comment by davecardwell** [comment]
I’m not sure if you implement one combined solution for all runtimes, or if it varies based on the language/version, but Node v18 introduced [watch mode](https://nodejs.org/api/cli.html#--watch) which might be a nice way of quickly detecting and restarting the lambda without needing to restart the entire container.

**Comment by dfangl** [comment]
Good hint, thanks! Our solution will however be runtime agnostic, basically we will restart the whole RIC (or whatever custom runtime someone is starting) and all other infrastructure (extensions, etc) within the container, letting it therefore reload.
It will basically be the same kind of reset which happens after a timeout, both in LS and in AWS, the environment is resetted, but not recreated (i.E. local files in /tmp will still be there, any data in the interpreter / process (like global state) will be lost).
It will probably result in some ms delay for the first invocation afterwards, but it should be negligible.

**Comment by dfangl** [comment]
I have some results for this to share!
Python3.9 lambda, results will vary depending on the cold-start time of the specific runtime:
Cold invocation (including container start, with hot reloading): 593.60ms
Hot invocation (no changes in hot reloading dir): 16.73ms
Hot invocation (changes since last invocation): 83.94ms

So we see around 70ms additional delay here, since we have to restart the python interpreter here.
Currently the interpreter only restarts 500ms after the last file system change was detected (to debounce massive copy operations a bit), the path is mounted as read only from the host (to avoid in-lambda changes to trigger a problem).

A reset will result in the lambda returning nothing, but also not failing, for now (so active executions will be cancelled).

**Comment by dfangl** [comment]
Hello all!
This functionality should be available (in about an hour) in our latest images!
Please feel free to try it out and please report any issues you have!

Some short notes:
* The "hot reloading identifier" changed from `__local__` to `hot-reload`. This was needed as a valid s3 name is required by some tools. The S3 Key is, as currently, the path to the local files. Please take into account that for compiled runtimes, this has to be the folder containing the bootstrap file. In any case, it should be the folder which represents the contents you would normally upload as zip archive.
* You need to enable the new provider using `PROVIDER_OVERRIDE_LAMBDA=asf`
* Once you make a change, it can take, depending on your system, up to 1s for it to be represented in your lambda. On linux docker it should only be 500ms, on any platform using Docker Desktop it might be up to 1s.
This is because of some debouncing we need, in case of bulk file operations, we cannot restart the internal infrastructure 10000 times if someone copies a node modules folder into the watched folders. Until this period passed, the lambda invocation might still be using the older code.
* The first invocation after a change will take a little bit longer, as reinitialization will take place.
