### ISSUE TITLE
bug: ServiceDiscovery Private DNS Namespace name not accepted

### ISSUE THREAD

**Issue by SanderHagen** [localstack/localstack#7205]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When trying to deploy a private DNS namespace to Localstack I get the error the name does not match the regex.

It can be reproduced by using this code
``` 
const dronePrivateDnsNamespace = new aws.servicediscovery.PrivateDnsNamespace('drone-private', {
    name: 'drone-private',
    description: 'Drone private DNS namespace',
    vpc: vpc.id,
  });
```
or using awslocal 
```
awslocal servicediscovery create-private-dns-namespace --name test-dns --vpc test
```
The error 
![image](https://user-images.githubusercontent.com/28562438/202712007-a5392d90-1f10-45e4-8a4e-918ff78fb0cf.png)

### Expected Behavior

I expect the namespace to be created with the given name. Since AWS does accept the value

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    localstack start

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    pulumilocal up 

### Environment

```markdown
- OS:Ubuntu 22.04
- LocalStack:latest
```

**Comment by SanderHagen** [comment]
After some more experimenting I found out it requires a `.` in the name. AWS doesn't require this, so it confused me a bit

**Comment by m1r4c** [comment]
+1 on this!

**Comment by whummer** [comment]
Thanks for reporting @SanderHagen @m1r4c . We have now pushed a few enhancements for ServiceDiscovery which should improve the parity with real AWS. Can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists.. Thanks!

**Comment by whummer** [comment]
Closing as resolved - please do let us know if the problem persists.. Thanks!
