### ISSUE TITLE
pip 10.0.0 breaks localstack build

### ISSUE THREAD

**Issue by jharriman** [localstack/localstack#721]
`make docker-build` seems to be failing both locally and in the travis builds.

At least one dependency (`warrant-ext`) uses parts of the `pip` package as an API (e.g. it calls `from pip.req import parse_requirements`). Version 10.0.0 of `pip` makes it very clear that `pip`'s modules are not to be used by anyone else by putting everything into a new `_internal` package. (https://mail.python.org/pipermail/distutils-sig/2017-October/031642.html)

It looks like localstack does a `pip install --upgrade pip` before installing anything, so it always uses `pip==10.0.0`, and then tries to build requirements (like `warrent-ext`) which try to use what's been moved to the internal package. localstack will need to do either or both of these steps:

1. Pin pip to version `9.0.3`
2. Remove or update dependencies that use this internal API incorrectly.

**Comment by OliverHofkens** [comment]
I've sent a PR to `warrant-ext` (https://github.com/capless/warrant/issues/96) to fix this, but haven't gotten any response yet.

**Comment by numberoverzero** [comment]
Trying to install localstack with pip 9.0.3 is also failing, and this looks like a similar error.  I've pulled out some of the noise but tried to keep all the intermediate package installs:

```
 [23] > pip --version
pip 9.0.3 from .venv/lib/python3.6/site-packages (python 3.6)

 [24] > pip install "localstack>=0.8.6,<0.9.0"
Collecting localstack<0.9.0,>=0.8.6
Collecting airspeed==0.5.5.dev20160812 (from localstack<0.9.0,>=0.8.6)
Collecting awscli>=1.14.18 (from localstack<0.9.0,>=0.8.6)
Collecting boto==2.46.1 (from localstack<0.9.0,>=0.8.6)
Requirement already satisfied: boto3>=1.4.4
Collecting coverage==4.0.3 (from localstack<0.9.0,>=0.8.6)
Collecting docopt==0.6.2 (from localstack<0.9.0,>=0.8.6)
Collecting elasticsearch==6.2.0 (from localstack<0.9.0,>=0.8.6)
Requirement already satisfied: flake8>=3.5.0
Collecting flake8-quotes>=0.11.0 (from localstack<0.9.0,>=0.8.6)
Collecting flask==0.10.1 (from localstack<0.9.0,>=0.8.6)
Collecting flask-cors==3.0.3 (from localstack<0.9.0,>=0.8.6)
Collecting flask_swagger==0.2.12 (from localstack<0.9.0,>=0.8.6)
Collecting jsonpath-rw==1.4.0 (from localstack<0.9.0,>=0.8.6)
Collecting localstack-ext>=0.8.1 (from localstack<0.9.0,>=0.8.6)
Collecting localstack-client==0.4 (from localstack<0.9.0,>=0.8.6)
Collecting moto-ext==1.2.0 (from localstack<0.9.0,>=0.8.6)
Collecting nose==1.3.7 (from localstack<0.9.0,>=0.8.6)
Collecting psutil==5.4.3 (from localstack<0.9.0,>=0.8.6)
Collecting pyOpenSSL==17.0.0 (from localstack<0.9.0,>=0.8.6)
Collecting python-coveralls==2.7.0 (from localstack<0.9.0,>=0.8.6)
Collecting pyYAML==3.12 (from localstack<0.9.0,>=0.8.6)
Requirement already satisfied: requests==2.18.4
Collecting requests-aws4auth==0.9 (from localstack<0.9.0,>=0.8.6)
Collecting six==1.10.0 (from localstack<0.9.0,>=0.8.6)
Collecting subprocess32-ext==3.2.8.2 (from localstack<0.9.0,>=0.8.6)
Collecting xmltodict==0.10.2 (from localstack<0.9.0,>=0.8.6)
Collecting cachetools==0.8.0 (from airspeed==0.5.5.dev20160812->localstack<0.9.0,>=0.8.6)
Collecting rsa<=3.5.0,>=3.1.2 (from awscli>=1.14.18->localstack<0.9.0,>=0.8.6)
Collecting botocore==1.10.4 (from awscli>=1.14.18->localstack<0.9.0,>=0.8.6)
Collecting colorama<=0.3.7,>=0.2.5 (from awscli>=1.14.18->localstack<0.9.0,>=0.8.6)
Collecting s3transfer<0.2.0,>=0.1.12 (from awscli>=1.14.18->localstack<0.9.0,>=0.8.6)
Requirement already satisfied: docutils>=0.10
Requirement already satisfied: jmespath<1.0.0,>=0.7.1
Requirement already satisfied: urllib3<1.23,>=1.21.1
Requirement already satisfied: mccabe<0.7.0,>=0.6.0
Requirement already satisfied: pyflakes<1.7.0,>=1.5.0
Requirement already satisfied: pycodestyle<2.4.0,>=2.0.0
Collecting Werkzeug>=0.7 (from flask==0.10.1->localstack<0.9.0,>=0.8.6)
Requirement already satisfied: Jinja2>=2.4
Collecting itsdangerous>=0.21 (from flask==0.10.1->localstack<0.9.0,>=0.8.6)
Collecting ply (from jsonpath-rw==1.4.0->localstack<0.9.0,>=0.8.6)
Requirement already satisfied: decorator
Collecting dnslib==0.9.7 (from localstack-ext>=0.8.1->localstack<0.9.0,>=0.8.6)
Collecting pyaes==1.6.0 (from localstack-ext>=0.8.1->localstack<0.9.0,>=0.8.6)
Collecting pyminifier==2.1 (from localstack-ext>=0.8.1->localstack<0.9.0,>=0.8.6)
Collecting srp-ext==1.0.7.1 (from localstack-ext>=0.8.1->localstack<0.9.0,>=0.8.6)
Collecting warrant-ext>=0.2.0.5 (from localstack-ext>=0.8.1->localstack<0.9.0,>=0.8.6)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/gh/phg7.../T/pip-build-806.../warrant-ext/setup.py", line 37, in <module>
        'test': parse_requirements('requirements_test.txt')
      File "/private/var/folders/gh/phg7.../T/pip-build-806.../warrant-ext/setup.py", line 6, in parse_requirements
        lineiter = (line.strip() for line in open(filename))
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements_test.txt'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/gh/phg7.../T/pip-build-806.../warrant-ext/
You are using pip version 9.0.3, however version 10.0.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by numberoverzero** [comment]
It's not great that both localstack and warrant are loaded in through corresponding `-ext` dependencies, which don't specify if their source is the same as the non-suffixed version.

https://pypi.org/project/localstack-ext/
https://pypi.org/project/warrant-ext/

To demonstrate the problem, here's the chain for `warrant-ext`:

```
Collecting warrant-ext>=0.2.0.5 (from localstack-ext>=0.8.1->localstack<0.9.0,>=0.8.6)
```

So `warrant-ext` should be in the `setup.py` of `localstack-ext` but the pypi page for `localstack-ext` points to this github repo (localstack/localstack) which doesn't mention `warrant-ext` at all: https://github.com/localstack/localstack/blob/master/requirements.txt

It could be that the `-ext` versions are part of the [extended library](https://github.com/localstack/localstack/blob/1bc2d0292e914216eba910f2563912b8b72c6de3/setup.py#L8-L9) and the marker `#extended-lib` was removed from [requirements.txt](https://github.com/localstack/localstack/blob/1bc2d0292e914216eba910f2563912b8b72c6de3/requirements.txt#L18) but it's harder to track down since the pypi packages are set up a bit differently.

**Comment by jharriman** [comment]
@numberoverzero Looks like someone (@whummer?) tried putting @OliverHofkens fix into `warrent-ext` with the latest release (0.6.1) https://pypi.org/project/warrant-ext/0.6.1/#history

**Comment by jharriman** [comment]
More clarity on why `localstack-ext` exists and how it is created would be helpful here. On inspection, it looks like it contains additional services (`ec2`, `sts`,`iam`, and `cognito`). These might be the 'Extended AWS Services' that are planned to be provided in the 'paid' version of localstack (https://localstack.cloud). 

There are no references in this code to how that package is built, and it doesn't look like anything in this repo depends on it. So why is it here?

**Comment by whummer** [comment]
Thanks for reporting @jharriman . The base image has been rebuilt and we have a clean master build again. Closing this issue, please comment here if the problem persists.

**Comment by JsonFn** [comment]
Unfortunately the update doesn't fix my problem. Switching to localstack 0.1.13 doesn't work either, except the error message this time is different from the one reported here. 

    error reading /tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/aws-java-sdk-dynamodb-1.11.151.jar; zip file is empty
    [info] error: error reading /tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/httpcore-4.4.4.jar; zip file is empty
    [info] error: error reading /tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/httpclient-4.5.2.jar; zip file is empty
    [info] error: error reading /tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/aws-java-sdk-kinesis-1.11.151.jar; zip file is empty
    [info] error: error reading /tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/jackson-core-2.6.6.jar; zip file is empty
    [info] error: error reading /tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/amazon-kinesis-client-1.7.6.jar; zip file is empty
    [info] error: error reading /tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/joda-time-2.8.1.jar; zip file is empty
    [info] error: error reading /tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/commons-logging-1.1.3.jar; zip file is empty
    [info] error: error reading /tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/ion-java-1.0.2.jar; zip file is empty
    [info] error: error reading /tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/protobuf-java-2.6.1.jar; zip file is empty
    [info] error: error reading /tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/commons-codec-1.9.jar; zip file is empty
    [info] error: error reading /tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/jackson-annotations-2.6.0.jar; zip file is empty
    [info] error: error reading /tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/jmespath-java-1.11.151.jar; zip file is empty
    [info] error: error reading /tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/aws-java-sdk-s3-1.11.151.jar; zip file is empty
    [info] error: error reading /tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/commons-lang-2.6.jar; zip file is empty
    [info] error: error reading /tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/aws-java-sdk-cloudwatch-1.11.151.jar; zip file is empty
    [info] error: error reading /tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/aws-java-sdk-kms-1.11.151.jar; zip file is empty
    [info] error: error reading /tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/guava-18.0.jar; zip file is empty
    [info] error: error reading /tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/jackson-databind-2.6.6.jar; zip file is empty
    [info] error: error reading /tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/aws-java-sdk-core-1.11.151.jar; zip file is empty
    [info] error: error reading /tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/jackson-dataformat-cbor-2.6.6.jar; zip file is empty

Building from source (by `git clone https://github.com/localstack/localstack.git`) yields the same error. 

    (test `which virtualenv` || pip install --user virtualenv) && \
	(test -e .venv || virtualenv  .venv) && \
	(. .venv/bin/activate && pip -q install pip==9.0.3) && \
	(test ! -e requirements.txt || (. .venv/bin/activate; pip install -q six==1.10.0 ; pip -q install -r requirements.txt) && \
	. .venv/bin/activate; PYTHONPATH=. exec python localstack/services/install.py testlibs)
    Running virtualenv with interpreter /usr/bin/python2
    New python executable in /tmp/localstackx/localstack/.venv/bin/python2
    Also creating executable in /tmp/localstackx/localstack/.venv/bin/python
    Installing setuptools, pkg_resources, pip, wheel...done.
    You are using pip version 9.0.3, however version 10.0.0 is available.
    You should consider upgrading via the 'pip install --upgrade pip' command.
    ERROR: 'javac -cp "/tmp/localstackx/localstack/localstack/infra/amazon-kinesis-client/aws-java-sdk- sts.jar:/tmp/localstackx/localstack/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/aws-java- sdk-dynamodb-1.11.151.jar:/tmp/localstackx/localstack/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/httpcore-4.4.4.jar:/tmp/localstackx/localstack/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/httpclient-4.5.2.jar:/tmp/localstackx/localstack/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/aws-java-sdk-kinesis-1.11.151.jar:/tmp/localstackx/localstack/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/jackson-core-2.6.6.jar:/tmp/localstackx/localstack/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/amazon-kinesis-client-1.7.6.jar:/tmp/localstackx/localstack/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/joda-time-2.8.1.jar:/tmp/localstackx/localstack/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/commons-logging-1.1.3.jar:/tmp/localstackx/localstack/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/ion-java-1.0.2.jar:/tmp/localstackx/localstack/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/protobuf-java-2.6.1.jar:/tmp/localstackx/localstack/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/commons-codec-1.9.jar:/tmp/localstackx/localstack/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/jackson-annotations-2.6.0.jar:/tmp/localstackx/localstack/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/jmespath-java-1.11.151.jar:/tmp/localstackx/localstack/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/aws-java-sdk-s3-1.11.151.jar:/tmp/localstackx/localstack/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/commons-lang-2.6.jar:/tmp/localstackx/localstack/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/aws-java-sdk-cloudwatch-1.11.151.jar:/tmp/localstackx/localstack/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/aws-java-sdk-kms-1.11.151.jar:/tmp/localstackx/localstack/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/guava-18.0.jar:/tmp/localstackx/localstack/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/jackson-databind-2.6.6.jar:/tmp/localstackx/localstack/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/aws-java-sdk-core-1.11.151.jar:/tmp/localstackx/localstack/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/jackson-dataformat-cbor-2.6.6.jar:/tmp/localstackx/localstack/localstack/utils/kinesis/java" /tmp/localstackx/localstack/localstack/utils/kinesis/java/com/atlassian/*.java': error: error reading /tmp/localstackx/localstack/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/aws-java-sdk-dynamodb-1.11.151.jar; zip file is empty
    error: error reading /tmp/localstackx/localstack/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/httpcore-4.4.4.jar; zip file is empty
    error: error reading /tmp/localstackx/localstack/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/httpclient-4.5.2.jar; zip file is empty
    error: error reading /tmp/localstackx/localstack/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/aws-java-sdk-kinesis-1.11.151.jar; zip file is empty
    error: error reading /tmp/localstackx/localstack/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/jackson-core-2.6.6.jar; zip file is empty
    error: error reading /tmp/localstackx/localstack/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/amazon-kinesis-client-1.7.6.jar; zip file is empty
    error: error reading /tmp/localstackx/localstack/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/joda-time-2.8.1.jar; zip file is empty
    error: error reading /tmp/localstackx/localstack/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/commons-logging-1.1.3.jar; zip file is empty
    error: error reading /tmp/localstackx/localstack/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/ion-java-1.0.2.jar; zip file is empty
    error: error reading /tmp/localstackx/localstack/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/protobuf-java-2.6.1.jar; zip file is empty
    error: error reading /tmp/localstackx/localstack/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/commons-codec-1.9.jar; zip file is empty
    error: error reading /tmp/localstackx/localstack/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/jackson-annotations-2.6.0.jar; zip file is empty
    error: error reading /tmp/localstackx/localstack/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/jmespath-java-1.11.151.jar; zip file is empty
    error: error reading /tmp/localstackx/localstack/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/aws-java-sdk-s3-1.11.151.jar; zip file is empty
    error: error reading /tmp/localstackx/localstack/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/commons-lang-2.6.jar; zip file is empty
    error: error reading /tmp/localstackx/localstack/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/aws-java-sdk-cloudwatch-1.11.151.jar; zip file is empty
    error: error reading /tmp/localstackx/localstack/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/aws-java-sdk-kms-1.11.151.jar; zip file is empty
    error: error reading /tmp/localstackx/localstack/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/guava-18.0.jar; zip file is empty
    error: error reading /tmp/localstackx/localstack/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/jackson-databind-2.6.6.jar; zip file is empty
    error: error reading /tmp/localstackx/localstack/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/aws-java-sdk-core-1.11.151.jar; zip file is empty
    error: error reading /tmp/localstackx/localstack/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/jackson-dataformat-cbor-2.6.6.jar; zip file is empty
    21 errors

    Traceback (most recent call last):
      File "localstack/services/install.py", line 185, in <module>
        install_amazon_kinesis_client_libs()
      File "localstack/services/install.py", line 115, in install_amazon_kinesis_client_libs
        run('javac -cp "%s" %s' % (classpath, java_files))
      File "/tmp/localstackx/localstack/localstack/utils/common.py", line 653, in run
        return do_run(cmd)
      File "/tmp/localstackx/localstack/localstack/utils/common.py", line 650, in do_run
        raise e
    subprocess32.CalledProcessError: Command 'javac -cp "/tmp/localstackx/localstack/localstack/infra/amazon-kinesis-client/aws-java-sdk-sts.jar:/tmp/localstackx/localstack/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/aws-java-sdk-dynamodb-1.11.151.jar:/tmp/localstackx/localstack/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/httpcore-4.4.4.jar:/tmp/localstackx/localstack/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/httpclient-4.5.2.jar:/tmp/localstackx/localstack/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/aws-java-sdk-kinesis-1.11.151.jar:/tmp/localstackx/localstack/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/jackson-core-2.6.6.jar:/tmp/localstackx/localstack/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/amazon-kinesis-client-1.7.6.jar:/tmp/localstackx/localstack/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/joda-time-2.8.1.jar:/tmp/localstackx/localstack/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/commons-logging-1.1.3.jar:/tmp/localstackx/localstack/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/ion-java-1.0.2.jar:/tmp/localstackx/localstack/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/protobuf-java-2.6.1.jar:/tmp/localstackx/localstack/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/commons-codec-1.9.jar:/tmp/localstackx/localstack/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/jackson-annotations-2.6.0.jar:/tmp/localstackx/localstack/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/jmespath-java-1.11.151.jar:/tmp/localstackx/localstack/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/aws-java-sdk-s3-1.11.151.jar:/tmp/localstackx/localstack/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/commons-lang-2.6.jar:/tmp/localstackx/localstack/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/aws-java-sdk-cloudwatch-1.11.151.jar:/tmp/localstackx/localstack/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/aws-java-sdk-kms-1.11.151.jar:/tmp/localstackx/localstack/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/guava-18.0.jar:/tmp/localstackx/localstack/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/jackson-databind-2.6.6.jar:/tmp/localstackx/localstack/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/aws-java-sdk-core-1.11.151.jar:/tmp/localstackx/localstack/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/jackson-dataformat-cbor-2.6.6.jar:/tmp/localstackx/localstack/localstack/utils/kinesis/java" /tmp/localstackx/localstack/localstack/utils/kinesis/java/com/atlassian/*.java' returned non-zero exit status 1
    Makefile:13: recipe for target 'install' failed

**Comment by JsonFn** [comment]
The problem remains. But this looks like related to https://github.com/localstack/localstack/issues/337, which might be because of empty amazon_kclpy lib get installed (not sure why). A temporary solution could be 1.) reinstall amazon_kclpy within venv, and then 2.) commenting out the end line of install task in Makefile. But this would requires a previously working version of $HOME/.local file.

**Comment by harsha-ravs** [comment]
The same issue still persists. Any hints will be much appreciated.


	C:\git_hr\localstack>pip show localstack
	WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
	Name: localstack
	Version: 1.1.0
	Summary: LocalStack - A fully functional local Cloud stack
	Home-page: https://github.com/localstack/localstack
	Author: LocalStack Contributors
	Author-email: info@localstack.cloud
	License: Apache License 2.0
	Location: c:\python310\lib\site-packages
	Requires: apispec, boto3, cachetools, click, localstack-client, localstack-ext, plux, psutil, python-dotenv, pyyaml, requests, rich, semver, stevedore, tailer
	Required-by: localstack-ext

	C:\git_hr\localstack>localstack --version

	C:\git_hr\localstack>python "C:\Python310\Scripts\\localstack" --version
	Traceback (most recent call last):
	  File "C:\Python310\Scripts\\localstack", line 23, in <module>
	    main()
	  File "C:\Python310\Scripts\\localstack", line 17, in main
	    from localstack.cli import main
	ImportError: No module named localstack.cli

	C:\git_hr\localstack>

I have also provided this information in [#724](https://github.com/localstack/localstack/issues/724)
