### ISSUE TITLE
Athena select query on table with OpenCSVSerde format getting error when the table contains an integer column type  

### ISSUE THREAD

**Issue by amineSt** [localstack/localstack#7218]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

**CSV S3 file content  (one line for exemple) :** 

`,,,45,,pageview,question,13,faq,device,question,,,tags,100`

CSV stored in S3 bucket at path : `s3://bucket-name/stats/dt=2022-11-21/data.csv`

**Query for table creation :** 

``` sql
CREATE EXTERNAL TABLE IF NOT EXISTS `default`.`kb_13_fr` (
                      `current_url` string,
                      `origin` string,
                      `question_id` string,
                      `resource_id` string,
                      `resource2_id` string,
                      `event_type` string,
                      `event_name` string,
                      `knowledgebase_id` int,
                      `channel` string,
                      `device` string,
                      `resource_type` string,
                      `resource2_type` string,
                      `related_search_query` string,
                      `tags` string,
                      `count` int
                      )
                    PARTITIONED BY (`dt` string)
                    ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
                    WITH SERDEPROPERTIES ('separatorChar' = ',','quoteChar' = '\"','escapeChar' = '\"')
                    STORED AS TEXTFILE
                    LOCATION 's3://bucket-name/stats/dt=2022-11-21'
                    TBLPROPERTIES ('has_encrypted_data'='false');
```

**Athena query to get data :** 

```sql
select * from kb_1_fr
```

**Result (localstack container logs) :** 

2022-11-22T09:32:17.271  INFO --- [  Thread-254] l.services.athena.provider : Athena error for query "select * from kb_13_fr":
Unable to get result from Presto server after 15 retries: PrestoQueryError(type=INTERNAL_ERROR, name=GENERIC_INTERNAL_ERROR, message="java.lang.String cannot be cast to java.lang.Number", query_id=20221122_093215_00000_jpbnb) Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/athena/provider.py.enc", line 49, in O
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/athena/query_utils.py.enc", line 25, in execute_query
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/utils/hadoop.py.enc", line 116, in execute_presto_query
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/utils/hadoop.py.enc", line 135, in execute_presto_queries
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/utils/hadoop.py.enc", line 132, in G
Exception: Unable to get result from Presto server after 15 retries: PrestoQueryError(type=INTERNAL_ERROR, name=GENERIC_INTERNAL_ERROR, message="java.lang.String cannot be cast to java.lang.Number", query_id=20221122_093215_00000_jpbnb)

### Expected Behavior

Athena query return the query result.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

   With docker compose, localstack container integrated in our docker-compose backend dev environment  

### Environment

```markdown
- OS: Arch linux Manjaro
- LocalStack: 1.1.0
```

**Comment by ebsmarttribune** [comment]
+1

**Comment by samail** [comment]
+1

**Comment by whummer** [comment]
Hi @amineSt @ebsmarttribune @samail @Eadroma @xavierbriole , thanks for reporting this issue. 

Please note that we have recently added a significant refactoring of the Athena service: previously, we were spinning up a separate `localstack_bigdata` Docker container alongside the `localstack_main` container, and in the new implementation we are starting up the bigdata services (Hive, Presto, etc) directly inside the LocalStack container, which helps improve the stability and reliability of Athena queries.

This behavior is currently behind a feature flag and can be enabled by setting `BIGDATA_MONO_CONTAINER=1` in the LocalStack container environment. Can you please try enabling this setting, and let us know if the problem persists with this setting? Meanwhile, we'll continue to triage this issue on our end as well, to see if we can replicate it. Thanks for your help!

**Comment by whummer** [comment]
Hi @amineSt @ebsmarttribune @samail @Eadroma @xavierbriole, another quick update. We looked into this issue in more detail, and can confirm that the sample works with the new bigdata mono container mode in LocalStack.

Can you please start up LocalStack with `BIGDATA_MONO_CONTAINER=1` enabled in the environment. You can then run the following script to reproduce the sample end-to-end:

```
#!/bin/bash

echo ',,,45,,pageview,question,13,faq,device,question,,,tags,100' > /tmp/test.csv
awslocal s3 mb s3://bucket-name
awslocal s3 cp /tmp/test.csv s3://bucket-name/stats/dt=2022-11-21/data.csv

query=$(cat <<-EOQ
CREATE EXTERNAL TABLE IF NOT EXISTS default.kb_13_fr (
    current_url string,
    origin string,
    question_id string,
    resource_id string,
    resource2_id string,
    event_type string,
    event_name string,
    knowledgebase_id int,
    channel string,
    device string,
    resource_type string,
    resource2_type string,
    related_search_query string,
    tags string,
    count int
    )
  PARTITIONED BY (dt string)
  ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
  WITH SERDEPROPERTIES ('separatorChar' = ',','quoteChar' = '\"','escapeChar' = '\"')
  STORED AS TEXTFILE
  LOCATION 's3://bucket-name/stats/'
  TBLPROPERTIES ('has_encrypted_data'='false');
EOQ
)

queryId=$(awslocal athena start-query-execution --query-string "$query" | jq -r .QueryExecutionId)

while true; do
	status=$(awslocal athena get-query-execution --query-execution-id $queryId | jq -r .QueryExecution.Status.State)
	echo $status
	if [ $status = "SUCCEEDED" ] || [ $status = "FAILED" ]; then break; fi
	sleep 2
done

awslocal athena start-query-execution --query-string "MSCK REPAIR TABLE default.kb_13_fr"
sleep 3

awslocal athena start-query-execution --query-string "select * from default.kb_13_fr" | jq -r .QueryExecutionId
```

Please note that the script contains a `MSCK REPAIR TABLE ...` query - this is required for the Hive metastore to pick up the partitions (`dt=2022-11-21`) created in S3. Alternatively, you could also use the `ALTER TABLE ... ADD PARTITION ...` query.

At the end of the script execution, you should see the following logs in the LocalStack instance (with `DEBUG=1` enabled):
```
2022-12-27T10:42:33.218 DEBUG --- [   Thread-27] l.services.athena.provider : Athena result for query "select * from default.kb_13_fr":
{'rows': [['', '', '', '45', '', 'pageview', 'question', '13', 'faq', 'device', 'question', '', '', 'tags', '100', '2022-11-21']], 'columns': [['current_url', 'varchar'], ['origin', 'varchar'], ['question_id', 'varchar'], ['resource_id', 'varchar'], ['resource2_id', 'varchar'], ['event_type', 'varchar'], ['event_name', 'varchar'], ['knowledgebase_id', 'varchar'], ['channel', 'varchar'], ['device', 'varchar'], ['resource_type', 'varchar'], ['resource2_type', 'varchar'], ['related_search_query', 'varchar'], ['tags', 'varchar'], ['count', 'varchar'], ['dt', 'varchar']]}
```

Hope that helps - please let us know if you can replicate these results. Thanks!

**Comment by samail** [comment]
Hi, 
Thanks for your feedback, we were quite busy last weeks but we will check that asap and get back to you

**Comment by whummer** [comment]
Hi again @samail, closing this issue as resolved - when setting `BIGDATA_MONO_CONTAINER=1` and using the `latest` LocalStack Docker image. Please do let us know if the problem persists.. Thanks!
