### ISSUE TITLE
bug: Localstack lambda with self-managed kafka cluster does not work

### ISSUE THREAD

**Issue by fcoutinho-uolinc** [localstack/localstack#7219]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Lambda is not invoked after publishing a message to the kafka topic

### Expected Behavior

I expected my lambda to be invoked after publishing a message to the kafka topic

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

1. Setup localstack following the exact steps described in the [HOWTO](https://github.com/localstack/localstack/blob/master/doc/external_services_integration/kafka_self_managed_cluster/HOWTO.md) section with the very same [docker-compose.yml](https://github.com/localstack/localstack/blob/master/doc/external_services_integration/kafka_self_managed_cluster/docker-compose.yml)

2. Publish a message to the `t1` topic that you created and you'll observe that the lambda is not invoked and no errors is shown.

### Environment

```markdown
- OS:Ubuntu 20.04.5 LTS

Tested on:
- LocalStack: latest (1.2.1.dev)
- LocalStack: 1.2.0
```

### Anything else?

![image](https://user-images.githubusercontent.com/73192437/203304174-3e1be82e-e2f6-4b27-9907-85830ca2bd73.png)

**Comment by jean-pasqualini** [comment]
@thrau tu peux rajouter le tag kms 🙏 ?

**Comment by thrau** [comment]
Hello! The lambda integration with self-managed kafka clusters is part of our MSK implementation and also a pro feature.  We've clarified the part in the docs!
