### ISSUE TITLE
Error starting infrastructure: HTTPSConnectionPool... Max retries exceeded with url

### ISSUE THREAD

**Issue by doijunior** [localstack/localstack#723]
I installed localstack on Ubuntu 17.10 with Python 3.5.0 (pyenv) and but was unable to start due this error:

`requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=4564): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3e9021f710>: Failed to establish a new connection: [Errno 111] Connection refused',))
`
Following issue #514 I remove infra directory and started again in debug mode, but now I got this:

`Error starting infrastructure: HTTPSConnectionPool(host='s3-eu-west-1.amazonaws.com', port=443): Max retries exceeded with url: /softwaremill-public/elasticmq-server-0.13.8.jar (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fcb5412fcc0>: Failed to establish a new connection: [Errno 110] Connection timed out',))`

**Comment by whummer** [comment]
Closing this issue as outdated - should not happen anymore in recent releases running in Docker. Thanks
