### ISSUE TITLE
bug: software.amazon.awssdk.services.dynamodb.model.ResourceNotFoundException

### ISSUE THREAD

**Issue by benkeil** [localstack/localstack#7233]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Since ~ 1 day we get this error while running our tests.

```kotlin
val awsCredentials = AwsBasicCredentials.create("test-access-key-id", "test-access-key-secret")
val dynamoDbClient = DynamoDbClient.builder()
    .endpointOverride(localstack.getEndpointOverride(LocalStackContainer.Service.DYNAMODB))
    .credentialsProvider { awsCredentials }
    .region(Region.of(localstack.region))
    .build()
val dynamoDbEnhancedClient = DynamoDbEnhancedClient.builder().dynamoDbClient(dynamoDbClient).build()

val variationSalesStatisticTableSchema = DataClassTableSchema(VariationSalesStatistic::class)
val variationSalesStatisticTable = dynamoDbEnhancedClient.table(variationSalesStatisticTableName, variationSalesStatisticTableSchema)

println(dynamoDbClient.listTables().tableNames())
println(variationSalesStatisticTable.scan { it.build() }.flatMap { it.items() })

// WORKS
println(
    variationSalesStatisticTable.putItem(
        VariationSalesStatistic(
            variationId = "v1",
            date = LocalDate.now(),
            productId = "p1",
            productBaseClass = "pbc1",
            revenue = 10,
            soldItems = 1,
            ttl = 123,
        )))

// FAILS
val batches =
    WriteBatch.builder(VariationSalesStatistic::class.java)
        .mappedTableResource(variationSalesStatisticTable)
        .addPutItem(
            VariationSalesStatistic(
                variationId = "v1",
                date = LocalDate.now(),
                productId = "p1",
                productBaseClass = "pbc1",
                revenue = 10,
                soldItems = 1,
                ttl = 123,
            ))
        .build()
dynamoDbEnhancedClient.batchWriteItem { it.writeBatches(batches).build() }

```

There was a commit that tries to fix something with the region, maybe its related: https://github.com/localstack/localstack/commit/260e37485eb8aba06a626b3af8820be86ce5d84e

### Expected Behavior

The tables should be found.

### How are you starting LocalStack?

Custom (please describe below)

### Steps To Reproduce

```kotlin
class ImportSalesStatisticsUseCaseTest :
    FunSpec({
      val localstack =
          install(
              TestContainerExtension(
                  LocalStackContainer(DockerImageName.parse("localstack/localstack")).apply {
                    withServices(
                        LocalStackContainer.Service.DYNAMODB,
                        LocalStackContainer.Service.SQS,
                        LocalStackContainer.Service.CLOUDWATCH)
                  }))
      ...
    })
```

### Environment

```markdown
- OS:
- LocalStack: latest
```

### Anything else?

`DataClassTableSchema`. is from `io.andrewohara.dynamokt`

When I downgrade the local stack container to `1.2.0` everything works.

**Comment by viren-nadkarni** [comment]
Hi @benkeil, DynamoDB now supports [multi-accounts](https://docs.localstack.cloud/tools/multi-account-setups/). This means that the same set of access key ID and region must be used for both creating and retrieving the resource. 

Could you please provide the series of awscli commands or code snippets that I can use to reproduce this?

**Comment by benkeil** [comment]
I updated the description. The problem is occurs only during a batch write and **not** in an older local stack version.

**Comment by benkeil** [comment]
If I set the accessKeyId to `000000000001` it works again.

```kotlin
val awsCredentials = AwsBasicCredentials.create("000000000001", "test-access-key-secret")
```

It's wired that the problem only occurs in a batch request.

**Comment by benkeil** [comment]
But it sounds like a bug, or?

**Comment by viren-nadkarni** [comment]
Hi @benkeil, we have pushed a fix on the latest image. Please give it a go and let us know if the issue persists.

**Comment by lashd** [comment]
Hi, I have pulled the latest image and continue to see the same/a very similar problem.

```
LocalStack version: 1.3.1.dev
LocalStack build date: 2022-12-07
LocalStack build git hash: 4abe1966
```

I posted the observed behaviour in response to https://github.com/localstack/localstack/issues/7118 as my issue is not specifically with multi accounts but I do see the same outcome when trying to batchwrite.

**Comment by benkeil** [comment]
works now
