### ISSUE TITLE
bug: _localstack/ses invalid destination schema

### ISSUE THREAD

**Issue by driverpt** [localstack/localstack#7236]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If we send SES via Raw Data, `Destination` is empty, it returns `[]`. e.g.:

```
Destination: [],
```

If we send SES via non-Raw Data,  it contains values, it returns a json object:
```
Destination: {
  "ToAddresses": [
    "Address1", "Address2"
  ]
}
```

### Expected Behavior

To have a consistent schema

### How are you starting LocalStack?

With a `docker run` command

### Steps To Reproduce

1. Send a SES Message using Raw Data 
2. Send SES Message using non-Raw Data Fields.

Access <localstack>/_localstack/ses

### Environment

```markdown
- OS: MacOS
- LocalStack: 1.1.0
```

**Comment by viren-nadkarni** [comment]
Hi, thanks for reporting this to us. The response should now use a consistent scheme. Please let us know if there are any further issues.
