### ISSUE TITLE
UI support view Step Function Express executation

### ISSUE THREAD

**Issue by lee-butn** [localstack/localstack#7238]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Currently , when I use localstack.cloud web UI version to browse Step Function Express then got error message. 
It is now supported that function in AWS . https://aws.amazon.com/about-aws/whats-new/2022/10/aws-step-functions-adds-new-execution-observability-features-express-workflows/

Please add this feature to your web UI. 

Thanks

**Comment by ackdav** [comment]
Hi @lee-butn - thanks for your feature request! I have trouble understanding what you actually refer to here - are you referring to our [Resource Browser](https://docs.localstack.cloud/user-guide/web-application/resource-browser/)? There is some support regarding step functions there - can you specify what you're missing?
Thanks!
