### ISSUE TITLE
feature request: Add support for DescribeSecurityGroupRules

### ISSUE THREAD

**Issue by mauriciocm9** [localstack/localstack#7245]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

I'm trying to deploy a terraform project using tflocal, however I'm getting this error:
`Error: describing security group rules: describing security group rules: InternalFailure: API action 'DescribeSecurityGroupRules' for service 'ec2' not yet implemented or pro feature - check https://docs.localstack.cloud/aws/feature-coverage for further information`
Is this feature in the roadmap?

**Comment by algo7** [comment]
Any news?

**Comment by uzaxirr** [comment]
Hey, I would like to take up this issue.
From my understanding I have to add a new module in `localstack/services` with a `provider.py` file and other files as well if necessary. also a new module will be needed in `localstack/localstack/aws/api` which contains a `DescribeSecurityGroupAPI` class and the `provider.py` will have a class `DescribeSecurityGroupProvider` which will inherit `DescribeSecurityGroupAPI` and `ServiceLifecycleHook` class. 

@mauriciocm9 can you also provide the tf script you used for my help

**Comment by uzaxirr** [comment]
I'm able to re-produce the issue as well
<img width="1027" alt="Screenshot 2022-12-17 at 1 34 55 PM" src="https://user-images.githubusercontent.com/72073401/208232239-55681fba-ded1-40bf-87a0-4a33c9b43897.png">

**Comment by algo7** [comment]
Any update on this?

**Comment by uzaxirr** [comment]
@steffyP Can you please validate my above comment and assign this to me so that i may start working on it

**Comment by steffyP** [comment]
Hi @ackdav,
could you please provide an update, e.g. are you actively working on this, or is it free to grab? 🙂

**Comment by ackdav** [comment]
Hi @steffyP - feel free to grab it 👍

**Comment by steffyP** [comment]
Hi @uzaxirr,

we need to coordinate if this issue is already in development.

In general regarding your questions:
there is a `provider.py` for every AWS service - the `DescribeSecurityGroupRules` belongs to ec2, and there is already a corresponding [provider](https://github.com/localstack/localstack/blob/master/localstack/services/ec2/provider.py) file.

The provider implements the `[Ec2Api](https://github.com/localstack/localstack/blob/master/localstack/aws/api/ec2/__init__.py)`, which was created by the `scaffold.py` according to the official service specifications. You can find a [detailed explanation of the concepts](https://docs.localstack.cloud/contributing/concepts/#aws-server-framework-asf) in our docs. 

As far as I remember there was discussion if it would be more appropriate to implement this missing feature in moto. Maybe @ackdav can share his findings.

**Comment by ackdav** [comment]
@steffyP 
ah yes, we discussed this internally a bit, and would agree that this endpoint would fit into upstream moto the best (securitygroups and securityrules are already in moto iirc). I briefly looked at this before the Christmas holidays (still off today), but never added an endpoint into moto myself - and therefore it got delayed for a bit... 
it would be a great value add as it is a highly demanded endpoint 👍

**Comment by steffyP** [comment]
@uzaxirr
can you start working with the information provided, and also take the decision it would be more appropriate add the implementation directly in moto? 
I have seen that you were already aware of the moto `models` for another RDS issue. The models for ec2 seem to be located [here](https://github.com/spulec/moto/tree/master/moto/ec2/models).

**Comment by uzaxirr** [comment]
Thankss for the valuable info @ackdav @steffyP 

I'll go ahead and add up this endpoint in moto as other security groups related functions are implemented over there itself, however I do have a few questions.

1. Do I always have to restart localstack host whenever i make changes in moto?
	I'm running localstack in host mode and have installed the local version of moto using `pip install -e ../moto/` . I wish that 		the changes made to my local moto should be picked up by localstack automatically.

2. I can see that whenever i send a request using `aws --endpoint-url=http://localhost:4566 ec2 create-security-group --group-name my-sg --description "My security new"` it runs the [create_security_group](https://github.com/localstack/moto/blob/localstack/moto/ec2/models/security_groups.py#L480) method of the `SecurityGroupBackend` class.  And i also see a [describe_security_group](https://github.com/localstack/moto/blob/localstack/moto/ec2/models/security_groups.py#L505) method in the same class. so i think that it should be fired upon when an request to describe security group is received. But it don’t so what's the purpose of that method. I was thinking to create a new method by `describe_security_group` in `SecurityGroupBackend` class but as i said it already exists.

Please tell me how do i proceed further.

**Comment by steffyP** [comment]
Thanks for picking this up @uzaxirr!

I am trying to answer your questions to the best of my knowledge:

ad 1) For local development/testing, please use localstack's [moto-fork](https://github.com/localstack/moto) (I think you already referenced it though). It might be the case that you need to restart LocalStack to pick up changes. 
For implementation I would recommend using a test-driven approach in the original [moto repo](https://github.com/spulec/moto). 
There seem to be some [security-group related tests here](https://github.com/localstack/moto/blob/localstack/tests/test_ec2/test_security_groups.py).

ad 2) It's true, there is an implementation for [`describe_security_groups`](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ec2/describe-security-groups.html). However, in this ticket the API [`describe_security_group_rules`](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ec2/describe-security-group-rules.html) is outlined as being missing. 
Personally, I haven't worked with EC2 yet, sorry that I cannot give you any more insights.

ad 3) correct, when you add this in moto you will not have to do anything in the providers. I just wanted to explain how the providers work in general 🙂 
Once your pull request was approved and merged in the original moto repo, we would do a rebase on our fork and release and update the linked moto-ext version we use in LocalStack.

Hope that makes sense, and helps you a bit 🙏

**Comment by uzaxirr** [comment]
Thanks for the informative comment @steffyP 
This is how i plan to approach it
1. This development should take place in original [moto repo](https://github.com/spulec/moto) not in the localstack fork
2. I have to initially write tests for the  [describe_security_group_rules](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ec2/describe-security-group-rules.html) endpoint
3. Then implement a `describe_security_group_rules` method in the `SecurityGroupBackend` class.

Do you recommend me to open up a new issue in the original moto repo for the same?

**Comment by steffyP** [comment]
Yes, sounds like a plan, @uzaxirr 🔝 

I don't think it is necessary to open a new ticket, you can however. 
It should be fine when you add a detailed description to your PR, and you could link this issue as well 🙂

**Comment by uzaxirr** [comment]
Hey @steffyP The PR https://github.com/getmoto/moto/pull/5841 got merged can you rebase the localstack's fork with it

**Comment by fmalk** [comment]
Glad this issue was picked up. I'll just add my scenario which incur in this error, with localstack-pro running from a local docker:

- RDS instance is correctly picked up by localstack, first time `apply` sees it, everything works fine
- Another TF resource is planned, new `apply` is submitted
- Somehow, terraform needs to list/verify whats already there, and regarding RDS instances it tries the following:

```
2023-01-19T03:31:08.287  INFO --- [   asgi_gw_7] localstack.request.aws     : AWS ec2.DescribeSecurityGroups => 200
2023-01-19T03:31:08.309  INFO --- [   asgi_gw_2] localstack.request.aws     : AWS rds.DescribeDBInstances => 200
2023-01-19T03:31:08.347  INFO --- [   asgi_gw_1] localstack.request.aws     : AWS ec2.DescribeSecurityGroupRules => 501 (InternalFailure)
2023-01-19T03:31:08.346  INFO --- [   asgi_gw_1] localstack.aws.skeleton    : API action 'DescribeSecurityGroupRules' for service 'ec2' not yet implemented or pro feature - check https://docs.localstack.cloud/user-guide/aws/feature-coverage for further information
```

Destroy also doesn't work after that, it still tries to do that action as well.
So the only way I have to recover and keep working is to stop the container, delete local state and start fresh. As long as there is an RDS instance any terraform action gets stuck.

**Comment by ackdav** [comment]
Hey @uzaxirr the rebase is in the works, as it sometimes creates conflicts, it takes a bit of time.

Wonderful @fmalk - always feel free to report issues. Additionally, Please be aware that the flag `MOCK_UNIMPLEMENTED` is [deprecated](https://docs.localstack.cloud/references/configuration/#miscellaneous).

**Comment by ackdav** [comment]
The moto bump went through and therefore it's now possible to:
```
awslocal ec2 describe-security-group-rules
{
    "SecurityGroupRules": [
        {
            "SecurityGroupRuleId": "sgr-82357ed5044a2a456",
            "GroupOwnerId": "000000000000",
            "IsEgress": true,
            "IpProtocol": "-1",
            "CidrIpv4": "0.0.0.0/0"
        }
    ]
}
```
If you want to use this, be sure to pull the latest version. Thank you again to @uzaxirr for implementing it 💪 great job!
