### ISSUE TITLE
Datadog lambda layer can't be applied

### ISSUE THREAD

**Issue by ricoli** [localstack/localstack#7255]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have a Pro license key. When I try to apply the Datadog extension lambda layer (`arn:aws:lambda:eu-west-2:464622532012:layer:Datadog-Extension:32`) I get this error (from the debug output of localstack):
```
2022-11-28T16:52:08.608 DEBUG --- [uncthread133] l.s.a.lambda_extended      : Copy function code layer arn:aws:lambda:eu-west-2:464622532012:layer:Datadog-Extension:32 to /home/ricoli/projects/<redacted>/infra/../__layers__
2022-11-28T16:52:08.608 DEBUG --- [uncthread133] localstack.utils.run       : Executing command: ['unzip', '-o', '-q', '/var/lib/localstack/lib/arn_aws_lambda_eu-west-2_464622532012_layer_Datadog-Extension_32/layer.zip']
2022-11-28T16:52:08.729 DEBUG --- [uncthread133] l.s.a.lambda_extended      : Copy function code arn:aws:lambda:eu-west-2:000000000000:function:svc-microservice-template-local-hello-world to /home/<redacted>/infra/../
2022-11-28T16:52:09.110 DEBUG --- [uest_thread)] l.s.awslambda.lambda_utils : Unknown error: expected str, bytes or os.PathLike object, not NoneType Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 1240, in create_function
    result = set_function_code(lambda_function)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 641, in set_function_code
    run_for_max_seconds(config.LAMBDA_CODE_EXTRACT_TIME, _set_and_configure)
  File "/opt/code/localstack/localstack/utils/run.py", line 147, in run_for_max_seconds
    raise result
  File "/opt/code/localstack/localstack/utils/run.py", line 128, in _worker
    fn_result = _function(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 629, in _set_and_configure
    plugin.init_function_code(lambda_function)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/awslambda/lambda_extended.py.enc", line 118, in init_function_code
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/awslambda/lambda_extended.py.enc", line 216, in copy_function_code
  File "/usr/local/lib/python3.10/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

2022-11-28T16:52:09.114  INFO --- [   asgi_gw_3] localstack.request.aws     : AWS lambda.CreateFunction => 500 (InternalFailure)
```

### Expected Behavior

I expected the lambda layer to be successfully applied and the lambda to be successfully created.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

`docker compose up`

And here is my docker-compose.yml localstack service:
```
  localstack:
    image: localstack/localstack
    pull_policy: always
    profiles:
      - fullstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
      - "127.0.0.1:443:443"              # LocalStack HTTPS Gateway (only required for Pro)
    environment:
      - DEBUG=${DEBUG-}
      - PERSISTENCE=${PERSISTENCE-}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      - LAMBDA_REMOTE_DOCKER=false
      - LAMBDA_DOCKER_FLAGS=-p 9229:9229
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY-}  # only required for Pro
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./.localstack-volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      resources:
        limits:
          memory: 1024M
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal s3 mb s3://mybucket

### Environment

```markdown
- OS: Ubuntu 22.04
- LocalStack: latest as of writing (https://hub.docker.com/layers/localstack/localstack/latest/images/sha256-fba53b8686e699a8bc478874fe0beaf9cb463ad06386e474ebf3284395d1b4d5?context=explore)
```

**Comment by joe4dev** [comment]
Thank you for reaching out @ricoli 

We just implemented fetching shared lambda layers in our new lambda provider implementation. Could you try:

1. Pulling the latest LocalStack Pro image: `docker pull localstack/localstack-pro`
2. Starting LocalStack with the feature flag `PROVIDER_OVERRIDE_LAMBDA=v2`

Please let us know if there are any further challenges with Lambda extensions. We are actively testing them with the new lambda provider and would appreciate any feedback.
Having a Pro license, feel free to reach out to LocalStack [Pro Support](https://docs.localstack.cloud/getting-started/help-and-support/#pro-support).

**Comment by dominikschubert** [comment]
Hi @ricoli 

Please note that you have to use `hot-reload` as a bucket name with using the new lambda `v2` implementation.
See here for more details: https://docs.localstack.cloud/references/lambda-asf-provider/#changes-in-hot-swapping

The reason we switched the default here is that `__local__` is not a valid bucket name according to AWS spec which caused various issues with official AWS tools.

**Comment by ricoli** [comment]
> Hi @ricoli
> 
> Please note that you have to use `hot-reload` as a bucket name with using the new lambda `v2` implementation. See here for more details: https://docs.localstack.cloud/references/lambda-asf-provider/#changes-in-hot-swapping
> 
> The reason we switched the default here is that `__local__` is not a valid bucket name according to AWS spec which caused various issues with official AWS tools.

thanks for letting me know - I changed the s3 bucket name and now the lambda is created successfully with the lambda layer attached to it! That sorts this issue, but fyi I did find something else : logs don't land in cloudwatch logs when using `PROVIDER_OVERRIDE_LAMBDA=v2` in the docker-compose.yml file, whereas they do land there if I remove this environment variable.

**Comment by joe4dev** [comment]
> but fyi I did find something else : logs don't land in cloudwatch logs when using `PROVIDER_OVERRIDE_LAMBDA=v2` in the docker-compose.yml file, whereas they do land there if I remove this environment variable.

@ricoli This shouldn't be the case. I just tested CloudWatch logs with our latest pro sample [lambda-php-bref-cdk-app](https://github.com/localstack/localstack-pro-samples/tree/master/lambda-php-bref-cdk-app) using [docker-compose.yml](https://github.com/localstack/localstack/blob/master/docker-compose-pro.yml#L21) (remember to mount the Docker socket) and everything works as expected. Feel free to open another issue describing your setup if this problem persists.

**Comment by ricoli** [comment]
> > but fyi I did find something else : logs don't land in cloudwatch logs when using `PROVIDER_OVERRIDE_LAMBDA=v2` in the docker-compose.yml file, whereas they do land there if I remove this environment variable.
> 
> @ricoli This shouldn't be the case. I just tested CloudWatch logs with our latest pro sample [lambda-php-bref-cdk-app](https://github.com/localstack/localstack-pro-samples/tree/master/lambda-php-bref-cdk-app) using [docker-compose.yml](https://github.com/localstack/localstack/blob/master/docker-compose-pro.yml#L21) (remember to mount the Docker socket) and everything works as expected. Feel free to open another issue describing your setup if this problem persists.

Hi @joe4dev - I've reported the issue at https://github.com/localstack/localstack/issues/7838

**Comment by joe4dev** [comment]
> Hi @joe4dev - I've reported the issue in #7838

Good catch 👏  Thank you for reporting @ricoli 
We plan to resolve it in the coming days.
