### ISSUE TITLE
feature request: sso-admin

### ISSUE THREAD

**Issue by labmonkey42** [localstack/localstack#7270]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

I'd like to emulate our `sso-admin` permissions scheme in localstack to facilitate (among other things) local verification of SSO assume-role behavior.  In the ideal case this would support cross-account access, but I don't think Organizations multiple account functionality is sufficient in localstack to really cover that scenario.

**Comment by thrau** [comment]
Hello everyone! The latest version of the pro image contains a simple mock implementation of sso-admin. The changes will be available with the 2.1 release by the end of this week. Please open up new tickets if you need specific features of sso-admin!
