### ISSUE TITLE
feature request: add SMTP_PORT to configuration

### ISSUE THREAD

**Issue by bakhtiyarneyman** [localstack/localstack#7275]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Currently SES seems to only be able to connect to the SMTP server running on port 25. This port might not be available in host mode.  Please provide a way to bind to a different address.

### 🧑‍💻 Implementation

It would be nice if SMTP_PORT variable could override the port.

**Comment by bakhtiyarneyman** [comment]
Now that I look at it more I realize that the `SMTP_HOST` refers to the address within the container, not on the host.  Which I think it makes it impossible to use SES through `localstack` CLI, because docker-compose seems to be the only way to launch the SMTP service inside the container.

**Comment by alexrashed** [comment]
Hi @bakhtiyarneyman! 
Actually, the `SMTP_HOST` allows adding the port with a colon, f.e. `SMTP_HOST=smtp.example.com:1025`.

- You can use the awesome [MailHog]( https://github.com/mailhog/MailHog) to simply start a mock SMTP server locally with docker:
  ```
  docker run -p 1025:1025 -p 8025:8025 mailhog/mailhog
  ```
  This will run an SMTP server on your local machine and the webinterface (showing the sent emails) can be reached via `http://localhost:8025`.
- You can then use this server as your SMTP test server.
  - Make sure that LocalStack can reach the mail server. If it's running on your host machine, make sure to use your docker host IP. In my case this is `172.17.0.1`.
  - So for me, the config would be: `SMTP_HOST="172.17.0.1:1025"`
 
Afterwards you can send your mail:
```
awslocal ses verify-email-identity --email-address test@example.com
awslocal ses send-email --from test@example.com --destination ToAddresses=test@example.com --message Body={Text={Data=test}},Subject={Data=Test}
```
And it will show up in MailHog:
![image](https://user-images.githubusercontent.com/2796604/205970623-36274df6-8751-4f73-85b1-b7a2d7a461bb.png)

Let me know if you have any issues with the config, in the meantime I'll update the docs to make it a bit more specific. ;)

**Comment by alexrashed** [comment]
The docs have already been updated. I'll close this issue for now. Please feel free to comment here or create a new issue if you are experiencing any issues with defining the port for the SMTP server.
