### ISSUE TITLE
create stream with 1 shard - but it tells me I have two

### ISSUE THREAD

**Issue by rayjlinden** [localstack/localstack#7279]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I create a stream called "Maxwell".  I create it with 1 shard.

It seems to create fine and I have a process that is writing to it that all appears to work.

Then I try to read:
```
./sbin/read-kinesis-stream.sh maxwell
info: Searching for stream; stream_name=maxwell
info: Getting records from stream; stream_name=maxwell nshards=2
info: Reading shard; shard_id=shardId-000000000001 shard_iterator=AAAAAAAAAAGjpJuzXV4R+i7wS57e6mZ56Ns4QEnH0yN7GLJW4SgojHyrzy5PZsp4W3zEIjNklnZzHfM2N0o3dWH5RZz4wgNNbVIxuoHk1uojM3DC416wtoxk6zSJ7O8YYdSv+QqKpGUmZ59hSezhEriO7kcsLIVlLNB4JpELG4wXRtVbPNGuvZQjcAUinz5dX48gYyPK5Kc=
info: Reading shard; shard_id=shardId-000000000000 shard_iterator=AAAAAAAAAAGEGTCjp4sDhKjZE73abmSmMGVe0Y6TXTxZjYwN0rRNrIr7V0YxTNHTNfZ3sd+3REfTVeNH1Cvr3LeKY3yZrr9u8K7xqWCwIn3rGb/z1DSA+fJ8MIpdLNzn5naoJIA7M1FwrLwUZVnRDwg7gGs6nJg973+tu9s4OGpgkLFVyKzv1sBDEevOAE/n82aPlhAICjw=

An error occurred (ResourceInUseException) when calling the GetRecords operation: Shard ShardId(shardId-000000000000,0) is not active

An error occurred (ResourceInUseException) when calling the GetRecords operation: Shard ShardId(shardId-000000000000,0) is not active
```

Why is it telling my I have 2 shards now?  And it appears broken as well...

### Expected Behavior

I expect the create stream to have 1 shard not 2.  And I expect it not to fail when I read from it.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

Unfortunately, I do not have a small use case I could put here.  It is part of a much larger system that would be tough to put here...

### Environment

```markdown
- OS:
- LocalStack:
```

**Comment by ackdav** [comment]
Dear @rayjlinden - thank you for raising the issue. Unfortunately, without more context and a description of how this error surfaces, it's impossible to reproduce or fix.
What I tried, in response to your description:
> I create a stream called "Maxwell". I create it with 1 shard.  

```> awslocal kinesis create-stream --stream-name maxwell --shard-count 1```

> It seems to create fine and I have a process that is writing to it that all appears to work.  
```
> awslocal kinesis put-record --stream-name maxwell --data '{"symbol": "TEST","sampleno":42}' --partition-key test1 
{
    "ShardId": "shardId-000000000000",
    "SequenceNumber": "49635850411434853650527752897445152692793959784107737090",
    "EncryptionType": "NONE"
}
```
> Then I try to read:  
> Why is it telling my I have 2 shards now? And it appears broken as well...
```
> SHARD_ITERATOR=$(awslocal kinesis get-shard-iterator --stream-name maxwell --shard-id shardId-000000000000 --shard-iterator-type TRIM_HORIZON  | jq -r '.ShardIterator')
> awslocal kinesis get-records --shard-iterator $SHARD_ITERATOR | jq -r '.Records[0].Data' | base64 --decode

{"symbol": "TEST","sampleno":42}% 
```
So it works as expected without being broken

```
> awslocal kinesis describe-stream --stream-name maxwell | jq '.StreamDescription.Shards' | jq length
1
```
So I only appear to have 1 shard.

Could you please provide more details about how you use kinesis and how this error appears? Thanks

**Comment by rayjlinden** [comment]
Sure.  Two things I can add that might help....

1) I'm using Maxwell Daemon which reads a mysql BIN log and is putting all
DB changes on a kinesis stream.  So that is what is producing the data in
the kinesis stream.
2) Here is what I get which I list the shards:
```
awslocal kinesis list-shards --stream-name maxwell
{
    "Shards": [
        {
            "ShardId": "shardId-000000000000",
            "HashKeyRange": {
                "StartingHashKey": "0",
                "EndingHashKey": "340282366920938463463374607431768211455"
            },
            "SequenceNumberRange": {
                "StartingSequenceNumber":
"49635840660121805160233355536970837921478917506809724930",
                "EndingSequenceNumber": "9223372036854775807"
            }
        },
        {
            "ShardId": "shardId-000000000001",
            "HashKeyRange": {
                "StartingHashKey": "0",
                "EndingHashKey": "340282366920938463463374607431768211455"
            },
            "SequenceNumberRange": {
                "StartingSequenceNumber":
"49635840663712225137196785862758088563375304396467339282"
            }
        }
    ]
}
```

I have learned (since originally posting) that the
EndingSquenceNumber field there means that it is a closed shard.  So I
guess I only have one open shard.  So when reading I apparently need to
ignore the closed one and just read from open shards.

However, I have now idea how a shard got closed in the first place.  Is
this something the producer can cause?  Why?

Ray

**Comment by ackdav** [comment]
> I have learned (since originally posting) that the
EndingSquenceNumber field there means that it is a closed shard. 

That's also my understanding as open shards have a ` EndingSequenceNumber` of null.

I'm not sure whether a producer could trigger resharding, as I'm not deeply familiar with that process. However, [the docs](https://docs.aws.amazon.com/streams/latest/dev/kinesis-using-sdk-java-resharding.html) helped clear it up a bit for me.

Also [this page](https://docs.aws.amazon.com/streams/latest/dev/kinesis-record-processor-scaling.html) says `Resharding enables you to increase or decrease the number of shards in a stream in order to adapt to changes in the rate of data flowing through the stream. Resharding is typically performed by an administrative application that monitors shard data-handling metrics.` 

Does LocalStack's behavior regarding shards not match AWS?

**Comment by rayjlinden** [comment]
Ok.  I just learned a couple of more things to help.  

1) I'm running latest version of localstack.  I've now pined it to 1.2.0 and I'm no longer getting the 2 shards.  Just the one I expect.
2) The new behavior is actually more broken.  I have a lambda tied to a kinesis event source.  My lambda is actually not getting called at all anymore.  By pinning to 1.2.0 - my lambda now gets properly called.

So something clearly broke in kinesis on the way to 1.3.0...

(But the good news for me is I'm unstuck by pinning the version!)

**Comment by ackdav** [comment]
Okay, nice to see some progress!

Can you please help me identify a minimum viable example of how to reproduce your error? For now, I understand that a lambda gets called from a kinesis event source.  What else is there? Do you use any special type of data?
