### ISSUE TITLE
Add option to disable collection of usage metrics

### ISSUE THREAD

**Issue by numberoverzero** [localstack/localstack#728]
First, thanks for the great alternative to using DynamoDBLocal directly.  I'm hoping to replace my integ tests and user documentation for [bloop](https://github.com/numberoverzero/bloop) with pointers to localstack instead, since it supports newer features like TTL which I'd like to continue testing (numberoverzero/bloop#117)

I'm a little concerned about the [Examples of Anonymized Usage Data](https://github.com/localstack/localstack/tree/df75f79c12baae17c4ea97f08146ab181e7ae059/doc/end_user_license_agreement#examples-of-anonymized-usage-data) which [from the source](https://github.com/localstack/localstack/blob/9ce1eb0f2fe80a613ff97e17ee8b4ca99370c0ef/localstack/utils/analytics/event_publisher.py) appears to fire [in multiple places](https://github.com/localstack/localstack/search?q=fire_event) including [table creation and deletion](https://github.com/localstack/localstack/blob/df75f79c12baae17c4ea97f08146ab181e7ae059/localstack/services/dynamodb/dynamodb_listener.py#L171-L180).  From looking through [`utils/analytics/event_publisher.py::poll_and_send_messages`](https://github.com/localstack/localstack/blob/9ce1eb0f2fe80a613ff97e17ee8b4ca99370c0ef/localstack/utils/analytics/event_publisher.py#L117-L120) this appears to send out to [`localstack/constants.py::API_ENDPOINT`](https://github.com/localstack/localstack/blob/df75f79c12baae17c4ea97f08146ab181e7ae059/localstack/constants.py#L78).

Is it possible to add an option during startup that disables this behavior?  I can appreciate that usage data helps prioritize feature development but in a number of cases users shouldn't be publishing table names to a third party endpoint.  This can be a hard constraint, even if the table name was being securely hashed, but in this case the [existing hash function](https://github.com/localstack/localstack/blob/9ce1eb0f2fe80a613ff97e17ee8b4ca99370c0ef/localstack/utils/analytics/event_publisher.py#L130-L136) is not secure; it relies on python's built-in `hash` function which is [designed for speed](https://stackoverflow.com/a/7646681).

**Comment by numberoverzero** [comment]
I looked through the `fire_event` search results a bit more, and the following are insecurely hashed and uploaded:

* [kinesis stream name](https://github.com/localstack/localstack/blob/93e82f8970ebd9f75ede31ef03fcb1fc8059f345/localstack/services/kinesis/kinesis_listener.py#L35)
* [sqs queue url](https://github.com/localstack/localstack/blob/3d75ead01a42802a9f0b054491d4ab53b3bdf74d/localstack/services/sqs/sqs_listener.py#L51)
* [dynamodb table name](https://github.com/localstack/localstack/blob/ed561f027b01b3dd9086b3d95846e4b51b190573/localstack/services/dynamodb/dynamodb_listener.py#L174-L175) (and [here](https://github.com/localstack/localstack/blob/ed561f027b01b3dd9086b3d95846e4b51b190573/localstack/services/dynamodb/dynamodb_listener.py#L178-L179))
* [lambda function name](https://github.com/localstack/localstack/blob/1bc2d0292e914216eba910f2563912b8b72c6de3/localstack/services/awslambda/lambda_api.py#L464-L465) (and [here](https://github.com/localstack/localstack/blob/1bc2d0292e914216eba910f2563912b8b72c6de3/localstack/services/awslambda/lambda_api.py#L562-L563))
* [s3 bucket name](https://github.com/localstack/localstack/blob/32da2d47079ac632891c7899c172d02434263f16/localstack/services/s3/s3_listener.py#L490)

**Comment by jayniz** [comment]
I, too, wonder.

**Comment by whummer** [comment]
Thanks for pointing this out. Event collection has been disabled by default and is now only enabled if the `LOCALSTACK_API_KEY` environment variable is configured (for the LocalStack Pro edition). Thanks
