### ISSUE TITLE
feature request: Add postgresql 14 and postgis extension

### ISSUE THREAD

**Issue by chris-stetter** [localstack/localstack#7285]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Currently, only postgresql version 11,12 and 13 are supported. As AWS already supports 14, it would be great to have that available. Also, on AWS it is possible to install the [PostGIS extension](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Appendix.PostgreSQL.CommonDBATasks.PostGIS.html), which would be very helpful for localstack as well.

**Comment by steffyP** [comment]
Hi @chris-stetter,

just a short update: with the `localstack/localstack-pro:latest` we just released a version that supports postgres v14 and v15. 

We haven't added the PostGIS extension yet. We will keep you posted on that matter.

**Comment by chris-stetter** [comment]
But would it be possible to manually install the PostGIS extension as described in the AWS docs?

**Comment by steffyP** [comment]
Hi @chris-stetter,
happy to inform you that we recently added postgis support RDS 🥳 
Please pull the `latest` localstack-pro image to use the new feature. We would be very happy to get your feedback. 
Also we included support for postgres 15 and 16 in the meantime 🙂
