### ISSUE TITLE
Duplicate HTTP `Date:` and `date:` headers (without legacy edge proxy)

### ISSUE THREAD

**Issue by dmaze** [localstack/localstack#7297]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

An HTTP request to list the contents on an S3 bucket includes both `Date:` and `date:` headers.  (Also both `Server:` and `server:`.)

```shellsession
$ curl -v http://localhost:4566/bucket-name
< HTTP/1.1 404 
< Content-Type: application/xml; charset=utf-8
< Content-Length: 227
< Server: Werkzeug/2.1.2 Python/3.10.8
< Date: Wed, 07 Dec 2022 17:28:21 GMT
< accept-ranges: bytes
< content-language: en-US
< date: Wed, 07 Dec 2022 17:28:21 GMT
< server: hypercorn-h11
```

This presents a problem using at least the AWS Java SDK v1.  This sees a duplicated HTTP header and combines the two values together as a single comma-separated string.  That results an an error parsing it as a date/time, and you eventually get an exception

```none
com.amazonaws.retry.ClockSkewAdjuster: Unable to parse clock skew offset from response
java.lang.IllegalArgumentException: Invalid format
```

### Expected Behavior

There should only be one `Date:` header with a single value.

### How are you starting LocalStack?

With a `docker run` command

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run -p 4566:4566 localstack/localstack:1.3.0

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    curl http://localhost:4566/bucket-name

### Environment

```markdown
- OS: MacOS Ventura 13.0.1
- Docker: Docker Desktop 4.14.1; Engine: 20.10.21
- LocalStack: 13.0
```

### Anything else?

This is similar to #676.

Setting `LEGACY_EDGE_PROXY=1` seems to avoid this problem.  In my actual Kubernetes environment, though, it has stability issues, and I hesitate to enable a "legacy" option.

**Comment by dmaze** [comment]
Testing this out with the local scenario described in this ticket, with `docker run -s PROVIDER_OVERRIDE_S3
asf`, I do in fact see only one `date:` header (and similarly only one `server:`).  I'll also evaluate this in the Kubernetes/Helm environment I hinted at earlier.  Setting an override value for a future-standard implementation would be a reasonable outcome.

**Comment by bentsku** [comment]
As it's been 2 weeks and the issue seems to be fixed, I'll close the issue. However, if you encounter any issue with those headers in a different environment, feel free to comment again and I'll gladly reopen!

Thanks a lot for your feedback again, and happy holidays!
