### ISSUE TITLE
Localstack Pro: Free for Open Source?

### ISSUE THREAD

**Issue by ThisIsMissEm** [localstack/localstack#730]
Hi! I've just seen the news about LocalStack Pro, and I love this move. Will Localstack Pro be free for open-source projects? (e.g., this could be useful for say, Mastodon, to ensure AWS integration works correctly).

**Comment by ChristopheBougere** [comment]
I'm also interested to know if the Pro Edition is still in the roadmap or not ([last website update ](https://github.com/localstack/localstack/tree/master/doc) was 8 months ago)

**Comment by whummer** [comment]
The Pro edition has been released now. 👍  Please contact us directly (see contact details on the website) for any license-related inquiries. Thanks
