### ISSUE TITLE
feature request: QLDB missing support for document metadata via committed views

### ISSUE THREAD

**Issue by amccarthy1** [localstack/localstack#7300]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Localstack is missing support for QLDB's "Committed Views" (`_ql_committed_${tableName}`) which contain metadata like versions and sequence numbers. For example, the following query fails on localstack:
```sql
SELECT * FROM _ql_committed_aggregations as d WHERE d.data.dateBucket = ?
```
I get the following error message when I try to run these types of queries
```
org.partiql.lang.eval.EvaluationException: No such binding: _ql_committed_aggregations
	Evaluator Error: at line 1, column 15: Binding does not exist, <UNKNOWN> : <UNKNOWN>
```
Whereas native QLDB correctly returns the row with its associated metadata.

For my use case, sequence numbers and versions are essential features, so having any kind of solution for allowing these queries to work would be great.

### Anything else?

https://docs.aws.amazon.com/qldb/latest/developerguide/working.metadata.html (AWS documentation about committed views in QLDB)

**Comment by jarredkenny** [comment]
I am in the same boat and would absolutely benefit from having this available in localstack.

At the moment, we work around this using a dedicated QLDB ledger in AWS for local development, but obviously this has its limitations.

**Comment by nnascim** [comment]
That's great to hear. Do you have an ETA (I won't hold you to it 😅)? It will help us to plan for the short-term.

**Comment by nnascim** [comment]
@amccarthy1 @jarredkenny I found a potential work-around. 

Using the problematic query originally posted: `SELECT * FROM _ql_committed_aggregations as d WHERE d.data.dateBucket = ?`

you should be able to replace it with the following: `SELECT * FROM history(aggregations) WHERE data.dateBucket = ?`

I hope this helps. If you need further support let me know.

**Comment by whummer** [comment]
@amccarthy1 @jarredkenny @nnascim Quick update - we have now added support for querying `_ql_committed_*` metadata tables. Can you please pull the `latest` Docker image and give it another try? Please keep us posted on how it goes.. Thanks!

**Comment by whummer** [comment]
Closing as resolved - please do let us know if the problem persists, happy to look into it in more detail in that case.. 👍  Thanks!
