### ISSUE TITLE
feature request: support aws-sdk inside locally executed nodejs lambdas

### ISSUE THREAD

**Issue by joshbalfour** [localstack/localstack#7308]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

First off, big fan of what you're doing here, really fills the gap between local and production :D

When using the local lambda executor the aws sdk isn't available, whereas it is in AWS.
This is mostly an issue when you don't control the code being run, which is often the case when pulling things in from cdk, such as the custom provider framework.

### 🧑‍💻 Implementation

As a crude workaround i'm applying this patch to [localstack/services/awslambda/lambda_executors.py](https://github.com/localstack/localstack/blob/v1.3.0/localstack/services/awslambda/lambda_executors.py)

lambda_executors.py.patch:
```patch
1387a1388,1390
>         environment["NODE_PATH"] = "/usr/lib/node_modules" # exposes the localstack container's global node modules to the lambda
>         environment["NODE_TLS_REJECT_UNAUTHORIZED"] = "0" # stops aws-sdk throwing cert errors
> 
1759c1762
< }
---
> }
\ No newline at end of file

```

Dockerfile that applies it:
```Dockerfile
FROM localstack/localstack-pro:1.3.0

COPY lambda_executors.py.patch /opt/code/localstack/localstack/services/awslambda

RUN apt install patch -y && \
  cd /opt/code/localstack/localstack/services/awslambda && \
  patch lambda_executors.py lambda_executors.py.patch && \
  apt remove patch -y

RUN npm install -g aws-sdk @aws-sdk/client-secrets-manager

```

**Comment by joshbalfour** [comment]
here's the patch i'm applying to [localstack/services/awslambda/lambda_executors.py](https://github.com/localstack/localstack/blob/v1.3.0/localstack/services/awslambda/lambda_executors.py)

```lambda_executors.py.patch
1387a1388,1390
>         environment["NODE_PATH"] = "/usr/lib/node_modules"
>         environment["NODE_TLS_REJECT_UNAUTHORIZED"] = "0"
> 
1759c1762
< }
---
> }
\ No newline at end of file

```

**Comment by joshbalfour** [comment]
Hiya! I'm using code mounting for hot swapping, I thought it was required for that as I'm also running localstack inside docker(?)

**Comment by dfangl** [comment]
Actually, it is not!
You can use hot reloading also with the docker provider. You just have to make sure to mount your docker socket into the container (please checkout our sample docker compose file, as example: https://github.com/localstack/localstack/blob/master/docker-compose.yml)

Or, even better, I would suggest trying out our new lambda provider implementation: Please follow the instructions here: https://github.com/localstack/localstack/issues/7200#issuecomment-1355311772

It should be way faster, and provides hot-reloading.
It would be nice if you can report back if this is a suitable solution for you or if you encounter any problems with it!
