### ISSUE TITLE
feature request: support of asymmetric keys for KMS

### ISSUE THREAD

**Issue by cwkang1998** [localstack/localstack#7311]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

As stated in the title, add support for asymmetric keys for KMS. More specifically, add support for:

- RSA_2048
- RSA_3072
- RSA_4096
- ECC_NIST_P256 (secp256r1)
- ECC_NIST_P384 (secp384r1)
- ECC_NIST_P521 (secp521r1)
- ECC_SECG_P256K1 (secp256k1), commonly used for cryptocurrencies.

Support for both encryption and signing should be added for these keys, where they are applicable.
 
Expecting full implementation for this to take some effort, since there are multiple types of asymmetric keys to support, possibly support can be done in batches.

### 🧑‍💻 Implementation

Currently looking into cryptography or pycryptodome as the library that can be used for the implementation of this feature. Will probably start from ecc and work from there since I'm personally more familiar with ecc keys.

**Comment by whummer** [comment]
Thanks for reporting @cwkang1998 . Can you please share some details about the use case (and a few snippets of a sample client app) - in fact, some of these asymmetric keys should already be supported, e.g., if you look here: https://github.com/localstack/localstack/blob/821377073f7aa20d7ef0b3aada699db31594ab7c/localstack/services/kms/models.py#L44-L55 

Would be great if you could provide a sample that demonstrates which functionality is still missing (in the `latest` version) - then we can provide more guidance.. 👍 Thanks!

**Comment by TheGreatAxios** [comment]
Is there any update on this? Would love to be able to use an assymetric key for blockchain based signers.

**Comment by TheGreatAxios** [comment]
Hey!

I have created this package: https://www.npmjs.com/package/@dirtroad/kms-signer

That uses the AWS Asymmetric Key to sign an Ethereum transaction. You can see all the necessary pieces under this section: https://www.npmjs.com/package/@dirtroad/kms-signer#setup-on-aws and then Creating the KMS Key. 

I.e Asymmetric, Sign & Verify, ECC_SECG_P256K1

The documentation states that Asymmetric is not currently supported, but it would be great to have this functional so that during development I (and others) don't need to pay for testing and using this key which currently I do. 

Thanks!

**Comment by alexrashed** [comment]
Hi @TheGreatAxios!
I think this issue might not be up to date anymore.
KMS has seen a lot of new features in the last few months and the docs have been updated with https://github.com/localstack/docs/pull/572.
Do you still have issues running your package against LocalStack?
If so, which exact issues are you facing?
Thanks!

**Comment by TheGreatAxios** [comment]
Issue #1 in the attached image. There is also no list of supported key specs in the docs which would be nice. 

![image](https://github.com/localstack/localstack/assets/20197130/970011b0-3e79-43d3-a721-87c1288a3712)
