### ISSUE TITLE
bug: SES Events notification messages are missing property tags

### ISSUE THREAD

**Issue by egimenos** [localstack/localstack#7323]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

This is a follow up to these PR from @simonrw https://github.com/localstack/localstack/pull/7244 and https://github.com/localstack/localstack/pull/7207

Setting up a configuration set for SES enables us  to receive event notification from SES when different events happen (sent, delivered, bounced, opened etc) 

The implementation in Localstack to mimic this behaviour was recently merged in the mentioned PR, but not all the properties from the payload are present. One property we would need are tags, specifically the custom tags which can be attached with the email request in order to better process the events later.

For example this email request:

```
aws ses send-email --destination '{"ToAddresses”:[“xxx@xxxcom"]}' --message '{"Subject":{"Data":"Test Link"},"Body":{"Html":{"Data":"<a href=\"nba.com\">Link test</a>"}}}' --configuration-set-name ses_config_set --from ‘yyy@oyyycom' --region eu-central-1 --tags Name=identifier,Value=testidentifier --output table | cat
````

Should generate events that contains the custom tag "Identifier" (among other generic tags from SES)

In real AWS:

```
{
   "Type":"Notification",
   "MessageId":"91873157-d824-57d9-8228-6d457e4cd029",
   "TopicArn":"arn:aws:sns:eu-central-1:736957585402:ses_events_topic",
   "Subject":"Amazon SES Email Event Notification",
   "Message":"{\"eventType\":\"Delivery\",\"mail\":{\"timestamp\":\"2022-12-13T16:11:19.531Z\",\"source\":\"xxx\",\"sourceArn\":\"arn:aws:ses:eu-central-1:736957585402:identity/xxx\",\"sendingAccountId\":\"736957585402\",\"messageId\":\"010701850c413a6b-9f7f1f77-2ec7-44b1-80a3-4d2c840d67a2-000000\",\"destination\":[\"yyy@gmail.com\"],\"headersTruncated\":false,\"headers\":[{\"name\":\"From\",\"value\":\"xxx\"},{\"name\":\"To\",\"value\":\"yyy@gmail.com\"},{\"name\":\"Subject\",\"value\":\"Test Link\"},{\"name\":\"MIME-Version\",\"value\":\"1.0\"},{\"name\":\"Content-Type\",\"value\":\"text/html; charset=UTF-8\"},{\"name\":\"Content-Transfer-Encoding\",\"value\":\"7bit\"}],\"commonHeaders\":{\"from\":[\"xxx\"],\"to\":[\"yyy@gmail.com\"],\"messageId\":\"010701850c413a6b-9f7f1f77-2ec7-44b1-80a3-4d2c840d67a2-000000\",\"subject\":\"Test Link\"},\"tags\":{\"identifier\":[\"testidentifier\"],\"ses:operation\":[\"SendEmail\"],\"ses:configuration-set\":[\"ses_config_set\"],\"ses:source-ip\":[\"3.68.108.181\"],\"ses:from-domain\":[\"yyy.com\"],\"ses:caller-identity\":[\"nw-admin\"],\"ses:outgoing-ip\":[\"69.169.224.1\"]}},\"delivery\":{\"timestamp\":\"2022-12-13T16:11:20.279Z\",\"processingTimeMillis\":748,\"recipients\":[\"yyy@gmail.com\"],\"smtpResponse\":\"250 2.0.0 OK  1670947880 6-20020a056000156600b00236c23d73ddsi99176wrz.662 - gsmtp\",\"reportingMTA\":\"b224-1.smtp-out.eu-central-1.amazonses.com\"}}\n",
   "Timestamp":"2022-12-13T16:11:20.388Z",
   "SignatureVersion":"1",
   "Signature":"C3BAipDonFzymok4kMnj7rwZFxi4447VQNZLpy8TApeSY/FZaN9WS4YtALDQvTiWANMk8ad/hbVrrNtzN90xZNJVNlCiDFA1g9qkFrzwZ7/2UNhQSIStHmsQbGTxGZybv8SucCz3OZlFrTqYyQg8RsgUtke0+BgWJErFAAWszd1ActeGjFTLUY3vwSBIUe7zkJakEqzg+XndjU+IjtBBEgI31reIhrTlYPvlvABLi8SeyvB04dvH5Uekshw5rbYe12556vYzqA6N8Kd1n3J+BMK/mIPUcYeMC/PMmzTpeOWaov7v65dkZtrJD4sTvLx5wCIBeiwod2UI4pttId2Zug==",
   "SigningCertURL":"https://sns.eu-central-1.amazonaws.com/SimpleNotificationService-56e67fcb41f6fec09b0196692625d385.pem",
   "UnsubscribeURL":"https://sns.eu-central-1.amazonaws.com/?Action=Unsubscribe&SubscriptionArn=arn:aws:sns:eu-central-1:736957585402:ses_events_topic:c5810a4e-f8e6-41a6-bfca-b5b7e9dfe33e"
}
```
Currently in Localstack:

```
{
   "Type":"Notification",
   "MessageId":"1d579434-7249-415f-87cf-c25be7105d31",
   "TopicArn":"arn:aws:sns:eu-central-1:000000000000:ses_events_topic",
   "Message":"{\"eventType\": \"Delivery\", \"mail\": {\"timestamp\": \"2022-12-13T15:56:04.071889+00:00\", \"source\": \"Sender <sender@test.com>\", \"sourceArn\": \"arn:aws:ses:eu-central-1:000000000000:identity/Sender <sender@test.com>\", \"sendingAccountId\": \"000000000000\", \"destination\": [\"Recipient <recipient@test.com>\"], \"messageId\": \"ytjtivdqeyygqyhj-dxkcrufx-tppt-hinv-ohqa-qzdyybhobphe-owevcr\"}, \"delivery\": {\"recipients\": [\"Recipient <recipient@test.com>\"], \"timestamp\": \"2022-12-13T15:56:04.071889+00:00\"}}",
   "Timestamp":"2022-12-13T15:56:04.088Z",
   "SignatureVersion":"1",
   "Signature":"EXAMPLEpH+..",
   "SigningCertURL":"https://sns.us-east-1.amazonaws.com/SimpleNotificationService-0000000000000000000000.pem",
   "UnsubscribeURL":"http://localhost:4566/?Action=Unsubscribe&SubscriptionArn=arn:aws:sns:eu-central-1:000000000000:ses_events_topic:b8d988ba-62c9-4c2c-8857-74984bdbe26b",
   "Subject":"Amazon SES Email Event Notification"
}
```

### Expected Behavior

The SES event notification payload should include tags, specially the custom ones. ("identifier", in this case)

```
"tags\":{\"identifier\":[\"testidentifier\"],\"ses:operation\":[\"SendEmail\"],\"ses:configuration-set\":[\"ses_config_set\"],\"ses:source-ip\":[\"33.61.18.181\"],\"ses:from-domain\":[\"yyy.com\"],\"ses:caller-identity\":[\"xx-admin\"],\"ses:outgoing-ip\":[\"79.143.224.1\"]}},
```

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

```

services:
  localstack:
    image: localstack/localstack:latest
    environment:
      - SERVICES=sqs,sns,ses
      - AWS_DEFAULT_REGION=eu-central-1
      - EDGE_PORT=4566
    ports:
      - '4566-4597:4566-4597'
    volumes:
      - ./localstack_setup.sh:/docker-entrypoint-initaws.d/setup.sh
      - '${TMPDIR:-/tmp/localstack}:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
networks:
  default:
    name: development-network
    external: true
```
**Verify email address**

`aws --endpoint-url=http://localhost:4566 ses verify-email-identity --email-address sender@test.com --profile test-profile --region eu-central-1 --output table | cat`

**create queue for SNS - SES events**

```
aws --endpoint-url=http://localhost:4566 sqs create-queue --queue-name ses_emails_feedback_queue
 --attributes '{"SqsManagedSseEnabled": "false"}' --profile test-profile --region eu-central-1 --output table | cat
```

**create SNS topic for SES events**

`aws --endpoint-url=http://localhost:4566 sns create-topic --name ses_events_topic --region eu-central-1 --profile test-profile --output table`

**subscribe queue to topic**

`aws --endpoint-url=http://localhost:4566 sns subscribe --topic-arn arn:aws:sns:eu-central-1:000000000000:ses_events_topic --protocol sqs --notification-endpoint arn:aws:sqs:eu-central-1:000000000000:ses_emails_feedback_queue --profile test-profile --region eu-central-1 --output table | cat`

**create config set**

`aws --endpoint-url=http://localhost:4566 ses create-configuration-set --configuration-set "{\"Name\":\"ses_config_set\"}" --profile test-profile --region eu-central-1 --output table | cat`

**create event destination**

`aws --endpoint-url=http://localhost:4566 ses create-configuration-set-event-destination --configuration-set-name ses_config_set --event-destination '{"Name":"some_name2","Enabled":true,"MatchingEventTypes":["send","bounce","delivery","open","click"],"SNSDestination":{"TopicARN":"arn:aws:sns:eu-central-1:000000000000:ses_events_topic"}}' --profile test-profile --region eu-central-1 --output table | cat`

**Send email with custom tag included:**

`aws --endpoint-url=http://localhost:4566 ses  send-email --destination '{"ToAddresses”:[“xxx@xxx.com"]}' --message '{"Subject":{"Data":"Test Link"},"Body":{"Html":{"Data":"<a href=\"nba.com\">Link test</a>"}}}' --configuration-set-name ses_config_set --from ‘sender@test.com' --region eu-central-1 --tags Name=identifier,Value=testidentifier --output table | cat`

### Environment

```markdown
- OS: macOS 12.6.1
- LocalStack: "1.3.0.dev"
```

**Comment by simonrw** [comment]
Hi @egimenos , thanks for reporting this issue and helping us improve our SES implementation!

In terms of priorities - how important are the AWS tags to you? They seem to indicate some information that I can see being useful (configuration set, operation) and some that are likely not (e.g. ip addresses). In addition, some of the tags may be more involved to emulate on our side.

If you're only using the custom tags you supply yourself for your purposes then can I suggest we focus on including custom tags and leave the AWS tags for now?

**Comment by egimenos** [comment]
Hi @simonrw , yes I totally agree, we can focus on the custom tags. 
Thanks a lot!

**Comment by simonrw** [comment]
@egimenos that's great, thanks. I'll keep you updated on progress :+1:

**Comment by simonrw** [comment]
My PR is merged, but it takes a little while to release a new docker image. I'll let you know when this is ready

**Comment by simonrw** [comment]
Ok if you `docker pull localstack/localstack:latest` you should be able to pick up the new changes. Let me know how you get on.

**Comment by egimenos** [comment]
Hey @simonrw on a first look it works as expected, thank you so much!
