### ISSUE TITLE
Unable to Connect to ElasticSearch

### ISSUE THREAD

**Issue by MakarandPundlik** [localstack/localstack#7326]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Trying to connect to elasticsearch domain using lambda and elasticsearch client but getting connection error.
this is my docker-compose.yml file 
```
version: "2.1"
services:
  localstack:
    image: "localstack/localstack:latest"
    container_name: "localstack"
    ports:
      - "4566-4620:4566-4620"
      - "127.0.0.1:8055:8080"
    environment:
      - DEBUG=1
      - EDGE_PORT=4566
      - DATA_DIR=/var/lib/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
      - LAMBDA_EXECUTOR=docker
      - DYNAMODB_SHARE_DB=1
      - DISABLE_CORS_CHECKS=1
      - AWS_DDB_ENDPOINT=http://localhost:4566
    volumes:
      - "${TMPDIR:-/var/lib/localstack}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - "local"

  
networks:
  local:
    driver: "bridge"
 
```

this is my elasticsearch client 
```
const {Client} = require('@elastic/elasticsearch')
module.exports.elasticClient = new Client({
    node : "http://localhost:4566"
})
```

I'm trying to create index from client but connection is refused. 

### Expected Behavior

It should create index using Client connector.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal s3 mb s3://mybucket

### Environment

```markdown
- OS:windows 11
- LocalStack: 1.3.0
```

**Comment by thrau** [comment]
Hi @MakarandPundlik!

The elasticsearch clusters are exposed on generated domain endpoints. You can find more information [in the docs](https://docs.localstack.cloud/user-guide/aws/elasticsearch/#interact-with-the-cluster)

essentially, `create-elasticsearch-domain` will create an endpoint that looks something like `http://my-domain.us-east-1.es.localhost.localstack.cloud:4566`, which is the URL you need to use in your client code.
if your client code is in a separate container, you also need to make sure that the container can resolve `my-domain.us-east-1.es.localhost.localstack.cloud` to the localstack container within your docker network.

I don't think this is a bug, just a problem with the configuration. Please let us know if this helped!

**Comment by MakarandPundlik** [comment]
> > Hi @MakarandPundlik!
> > I don't think this is a bug, just a problem with the configuration.
> > The elasticsearch clusters are exposed on generated domain endpoints. You can find more information [in the docs](https://docs.localstack.cloud/user-guide/aws/elasticsearch/#interact-with-the-cluster)
> > essentially, `create-elasticsearch-domain` will create an endpoint that looks something like `http://my-domain.us-east-1.es.localhost.localstack.cloud:4566`, which is the URL you need to use in your client code. if your client runs on your host, it should work like this out of the box, simply by replacing ` node : "http://localhost:4566"` with the correct URL.
> > if your client code is in a separate container, you also need to make sure that the container can resolve `my-domain.us-east-1.es.localhost.localstack.cloud` to the localstack container within your docker network.
> > Please let us know if this helped!
> 
> Hi, @thrau actually i'm using serverless framework with localstack, so my entire code will run on a single container as mentioned in the docker-compose file. I have executed the `create-elasticsearch-domain` command and that worked well, giving some endpoints and arns. Now you just want me to replace `http://localhost:4566` with `http://my-domain.us-east-1.es.localhost.localstack.cloud:4566` if i'm not wrong ?

I tried replacing the URL now i'm getting this ``` Lambda process returned with error. Result: {"errorType":"ConfigurationError","errorMessage":"Invalid protocol: 'mydomain.us-east-1.es.localhost.localstack.cloud:'"}. Output:
2022-12-14T13:11:45.942Z        undefined       ERROR   Uncaught Exception      {"errorType":"ConfigurationError","errorMessage":"Invalid protocol: 'mydomain.us-east-1.es.localhost.localstack.cloud:'","name":"ConfigurationError","stack":["ConfigurationError: Invalid protocol: 'mydomain.us-east-1.es.localhost.localstack.cloud:'","    at new BaseConnection (/var/task/node_modules/@elastic/transport/lib/connection/BaseConnection.js:116:19)","    at new Connection (/var/task/node_modules/@elastic/transport/lib/connection/UndiciConnection.js:38:9)","    at WeightedConnectionPool.createConnection (/var/task/node_modules/@elastic/transport/lib/pool/BaseConnectionPool.js:141:28)","    at WeightedConnectionPool.addConnection (/var/task/node_modules/@elastic/transport/lib/pool/BaseConnectionPool.js:164:59)","    at new Client (/var/task/node_modules/@elastic/elasticsearch/lib/client.js:180:33)","    at Object.<anonymous> (/var/task/utils.js:4:32)","    at Module._compile (internal/modules/cjs/loader.js:999:30)","    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)","    at Module.load (internal/modules/cjs/loader.js:863:32)","    at Function.Module._load (internal/modules/cjs/loader.js:708:14)"]} ```

**Comment by thrau** [comment]
@MakarandPundlik, got it. ``http://my-domain.us-east-1.es.localhost.localstack.cloud:4566`` was just an example. you should replace it with the URL of the elasticsearch cluster. you can find it by calling `awslocal es describe-elasticsearch-domain --domain-name <your elasticsearch domain name>`

**Comment by MakarandPundlik** [comment]
> @MakarandPundlik, got it. `http://my-domain.us-east-1.es.localhost.localstack.cloud:4566` was just an example. you should replace it with the URL of the elasticsearch cluster. you can find it by calling `awslocal es describe-elasticsearch-domain --domain-name <your elasticsearch domain name>`. It's all described in our docs https://docs.localstack.cloud/user-guide/aws/elasticsearch/#creating-an-elasticsearch-cluster :-)

this is the exact URL that i'm getting after creating a domain. I think elasticsearch connector needs some more parameters.

**Comment by MakarandPundlik** [comment]
> @MakarandPundlik, got it. `http://my-domain.us-east-1.es.localhost.localstack.cloud:4566` was just an example. you should replace it with the URL of the elasticsearch cluster. you can find it by calling `awslocal es describe-elasticsearch-domain --domain-name <your elasticsearch domain name>`. It's all described in our docs https://docs.localstack.cloud/user-guide/aws/elasticsearch/#creating-an-elasticsearch-cluster :-)

also one more thing, whenever i check my cluster health using ```curl -s http://mydomain.us-east-1.es.localhost.localstack.cloud:4566/_cluster/health``` this command i get ```"status":"yellow"``` this status. Is it because of this it is happening?

**Comment by MakarandPundlik** [comment]
for my curiosity i went to postman with the above URL, it is working perfectly fine. I don't know what is the problem with Elasticsearch connector.

**Comment by Shreyashi-Samaddar** [comment]
facing the same issue

**Comment by RahulKumar-Cxone** [comment]
Even We are facing the same issue.

**Comment by siddharth810** [comment]
We are facing the same issue

**Comment by RKV8309** [comment]
Even we are facing the same issue.
