### ISSUE TITLE
How to start specific services

### ISSUE THREAD

**Issue by franciszabala** [localstack/localstack#733]
I tried 

./localstack start sns
./localstack infra sqs,sns start

any many other combinations but get it to run. I can find anything on the documents.

**Comment by franciszabala** [comment]
SERVICES=sqs,sns localstack start

Maybe an example on the documentation would be helpful?

**Comment by whummer** [comment]
Sure, good idea - would you be able to raise a small PR to fix that? Thanks!

**Comment by emanuelef** [comment]
Just ended up here while searching, from what I understand now services are loaded only when used, so they always appear as available in /health.
https://github.com/localstack/localstack/issues/6007#issuecomment-1118470048
So apparently is no longer needed to select which ones.

**Comment by anentropic** [comment]
I just installed localstack and this was completely baffling me

e.g. in Cockpit they show as 0 running, 36 available and so I was wondering how to start them so they are 'running' since there didn't seem to be any option
