### ISSUE TITLE
feature request: Pass all networks assigned from localstack to lambda container

### ISSUE THREAD

**Issue by kelhelawy** [localstack/localstack#7338]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Allow lambda container to have multiple networks not just one.
With the current implementation Lambda network only gets a single network, even though the Localstack container accepts multiple network values.
this is how it works currently:

> Gets the main network of the LocalStack container (if we run in one, bridge otherwise)
    If there are multiple networks connected to the LocalStack container, we choose the first as "main" network

### 🧑‍💻 Implementation

This is where the "main" network value is retrieved, may be it should be a List?
https://github.com/localstack/localstack/blob/a71e661fa6b0189e54b468713f710f0ae1b93791/localstack/utils/container_networking.py#L14

**Comment by dfangl** [comment]
I do not think it would be wise to do this per default for all containers. We can only add one network on start, so would have to have additional network connect requests afterwards. While this is possible, it would slow down all container creations significantly, most notable in lambda.

Can you share a little more about your usecase? Would only adding multiple ones if you specify multiple ones in `LAMBDA_DOCKER_NETWORK`, comma separated do the trick for you? I think this is a quite specialized usecase, as for most users only one connected network should suffice.

**Comment by dfangl** [comment]
Seems like a reasonable addition! Will put this on accepted for now, I cannot promise an ETA though.
