### ISSUE TITLE
S3 pre-signed url and LambdaExecutor with S3Event object

### ISSUE THREAD

**Issue by aggansu** [localstack/localstack#735]
Hi,

I am running localstack inside docker container with environment variable LAMBDA_EXECUTOR=local. I upload a file to S3 using pre-signed url via aws java sdk. It has some query parameters in the pre-signed url as follows-

http://s3-bucket.localhost:4572/folder/file.txt?x-amz-meta-filename=file.txt&x-amz-meta-fileSource=source

The file is upload to S3 successfully but notification to lambda is not triggered. Though if I put the same file via aws cli and put-object command, the lambda is invoked.

Out of curiosity I was looking at the code of https://github.com/localstack/localstack/blob/master/localstack/services/s3/s3_listener.py and found a flag 'should_send_notifications' which seems to prevent notifications to lambda if url contains query parameters.

Can you please advise on why s3 notification is not triggered via pre-signed url file upload to s3?

Also, when the lambda is invoked using file upload via put-object (aws-cli), I see the below error in localstack logs (could be related to https://github.com/localstack/localstack/issues/491) -

Exception in thread "main" java.lang.ClassCastException: java.util.LinkedHashMap cannot be cast to com.amazonaws.services.lambda.runtime.events.S3Event

Thanks

**Comment by demisx** [comment]
What was the solution prompting to close this issue? A sentence or two would be helpful.
