### ISSUE TITLE
feature request: Lambda URLs HTTPS support

### ISSUE THREAD

**Issue by dmarkey** [localstack/localstack#7350]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

The cert that localstack uses does not cover *.lambda-url.<region>.localhost.localstack.cloud

```
curl -vvv https://8065a3a3503ebd54ce27e3e4eb02c2a1.lambda-url.us-west-2.localhost.localstack.cloud:4566/
*   Trying 127.0.0.1:4566...
* Connected to 8065a3a3503ebd54ce27e3e4eb02c2a1.lambda-url.us-east-1.localhost.localstack.cloud (127.0.0.1) port 4566 (#0)
* ALPN: offers h2
* ALPN: offers http/1.1
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* (304) (OUT), TLS handshake, Client hello (1):
* (304) (IN), TLS handshake, Server hello (2):
* (304) (IN), TLS handshake, Unknown (8):
* (304) (IN), TLS handshake, Certificate (11):
* (304) (IN), TLS handshake, CERT verify (15):
* (304) (IN), TLS handshake, Finished (20):
* (304) (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / AEAD-CHACHA20-POLY1305-SHA256
* ALPN: server accepted h2
* Server certificate:
*  subject: CN=localhost.localstack.cloud
*  start date: Oct  1 11:00:49 2022 GMT
*  expire date: Dec 30 11:00:48 2022 GMT
*  subjectAltName does not match 8065a3a3503ebd54ce27e3e4eb02c2a1.lambda-url.us-east-1.localhost.localstack.cloud
* SSL: no alternative certificate subject name matches target host name '8065a3a3503ebd54ce27e3e4eb02c2a1.lambda-url.us-east-1.localhost.localstack.cloud'
* Closing connection 0
curl: (60) SSL: no alternative certificate subject name matches target host name '8065a3a3503ebd54ce27e3e4eb02c2a1.lambda-url.us-east-1.localhost.localstack.cloud'
More details here: https://curl.se/docs/sslcerts.html
```

It would be very nice for localstack to support https on these urls as modern development methodologies assume them these days.

### 🧑‍💻 Implementation

Add alternative names? (perhaps they dont support wildcard domains?)

**Comment by dfangl** [comment]
Hi!
Yes, this would be a useful addition. However, we are currently limited in our certificates, what we can support. Alone lambda urls would require us to have ~30 alt names in the certificate (wildcards only work on one layer, so we would have to have one name per region), with a maximum of 100 supported per cert.

This definitely makes sense, but brings some complexity, so it might take a while to implement. Thank you for creating this issue, though!

**Comment by dmarkey** [comment]
Probably makes sense to only do us-east-1, thats kind of the assumed region in localstack usually?

**Comment by dfangl** [comment]
This should be resolved now.
You can find the regions the certificate is valid for here: https://github.com/localstack/localstack-artifacts/blob/master/local-certs/certificate-regions

Please note that you might need to trigger a redownload of the cert, by removing the localstack volume (or the cache subdirectory of it): https://docs.localstack.cloud/references/filesystem/#localstack-volume
