### ISSUE TITLE
feature request: Add simple 4566 proxy from localhost to remote localstack docker localstack instances

### ISSUE THREAD

**Issue by dmarkey** [localstack/localstack#7351]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Most documentation assumes that localstack in running locally on 127.0.0.1:4566. With a remote DOCKER_HOST that is a false assumption. 

The localstack CLI could provide a simple forwarding mechanism to forward 127.0.0.1 on the host that runs `localstack start` to the address of the machine actually running the localstack docker container.

### 🧑‍💻 Implementation

A simple thread that forwards on the request.

**Comment by dfangl** [comment]
Thank you for the feature request!
As a workaround, you could use the tool `ncat` (currently ships with `nmap`) to get a similar behavior.

Usage would be like this:
```
ncat --sh-exec "ncat <remote-host> 4566" -l 4566 --keep-open
```

To forward your local port 4566 to the remote 4566. To forward a different local port, change the value of the `-l` parameter, to use a different remote, change the port after <remote-host>.
