### ISSUE TITLE
feature request: Please Add Additional IoT GreenGrass Related Support (IoT::RoleAlias)

### ISSUE THREAD

**Issue by ewx-mjanda** [localstack/localstack#7357]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

We have added AWS IoT GreenGrass setup in our CDK project recently. Getting the below error message:

Unexpected resource type IoT::RoleAlias when resolving references of resource

This is not listed as a part of the officially supported IoT types in the documentation and we would request that it please be added.

**Comment by pinzon** [comment]
This feature has been just merged. Make sure to pull the latest image of localstack-pro. Thank you for reporting the issue.
