### ISSUE TITLE
feature request: Implement API action GetPasswordData for EC2 service

### ISSUE THREAD

**Issue by ifzal-ahmed-npl** [localstack/localstack#7362]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

I get the below error when trying to create a EC2 instance with the 'get_password_data` option enabled

```
│ Error: InternalFailure: API action 'GetPasswordData' for service 'ec2' not yet implemented or pro feature - check https://docs.localstack.cloud/user-guide/aws/feature-coverage for further information
│       status code: 501, request id: 6100OEDHZF9T334DUNKGH8MACB7VRUDT442I5220BH4EL60TNO9G
```

Can this API action be implemented please.

**Comment by viren-nadkarni** [comment]
Hi @ifzal-ahmed-npl, this is now available on the latest image of LocalStack.
