### ISSUE TITLE
bug: IoT CreateKeysAndCertificate creates invalid PEM certificates

### ISSUE THREAD

**Issue by viren-nadkarni** [localstack/localstack#7366]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`IoT:CreateKeysAndCertificate` operation creates an invalid PEM certificate, public and private key.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)
```
$ awslocal iot create-keys-and-certificate
{
    "certificateArn": "arn:aws:iot:us-east-1:000000000000:cert/17e785378f0004b5e0924e5b28d6447770da71da5710218993773b89d05e2d67",
    "certificateId": "17e785378f0004b5e0924e5b28d6447770da71da5710218993773b89d05e2d67",
    "certificatePem": "EtQh23sJurYGziXyB8fN",
    "keyPair": {
        "PublicKey": "Y2TeXuRUmNSPmfAR9e0d",
        "PrivateKey": "UciVQfevDoEvNNwFpWAH"
    }
}
```

### Environment

```markdown
- OS: Ubuntu 22.04
- LocalStack: latest
```

### Anything else?

From <https://discuss.localstack.cloud/t/iot-in-node-js-example-flow/164>

**Comment by electricmonk** [comment]
Hi, thanks for resolving this issue - is it already available in the latest Localstack docker container?

**Comment by viren-nadkarni** [comment]
Hi @electricmonk, this is included in the moto-ext 4.0.12.post2 and can be used in the latest LocalStack image.

**Comment by electricmonk** [comment]
Hi
Using localstack 1.3.1, I'm still getting invalid format for cert and keys

Docker log:
```
e2e-localstack-1  | LocalStack version: 1.3.1
e2e-localstack-1  | LocalStack build date: 2022-12-16
e2e-localstack-1  | LocalStack build git hash: 0c095708
```

I call `CreateKeysAndCerts` and get this:
```
privateKey = "HzlJdogCh6aDPVuGQ5Yr"
certificatePem = "r8oRjBXOIqouJllvmJzG"
```

**Comment by viren-nadkarni** [comment]
I meant the `localstack:latest` image. This is yet to be included in a versioned release.
