### ISSUE TITLE
bug: Lambda is not able to connect to ports outside docker container

### ISSUE THREAD

**Issue by MakarandPundlik** [localstack/localstack#7369]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

Not able to access elasticsearch image running on ```port 9200``` throught localstack which is running on ```port 4566```.
It does not throw any error 
Even i created a new server at ```port 3000``` which just takes one route i.e. get ```GET``` request ,
```
const express = require('express')

const app = express();
const { Client } = require('@elastic/elasticsearch');
let counter = 0;
const elasticClient = new Client({
  node: "http://localhost:9200"
});

app.listen(3000, () => {
    console.log('listening to the port 3000')
})

app.get("/", (req, res) => {
  counter++;
  console.log("this is a req body",counter)
  res.json({
    "msg":"hello from localhost:3000",
  })
})
```

  Problem is my lambdas from localstack is not throwing any connection errors, neither anything is getting printed on localhost 3000 logs 

This is my localstack docker-image 
```
version: "2.1"

services:
  localstack:
    image: "localstack/localstack"
    container_name: "localstack"
    ports:
      - "4566-4620:4566-4620"
      - "127.0.0.1:8055:8080"
    environment:
      - SERVICES=s3,es,dynamodb,apigateway,lambda,sns,sqs,sloudformation
      - DEBUG=1
      - EDGE_PORT=4566
      - DATA_DIR=/var/lib/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
      - LAMBDA_EXECUTOR=docker
      - DYNAMODB_SHARE_DB=1
      - DISABLE_CORS_CHECKS=1
      - AWS_DDB_ENDPOINT=http://localhost:4566

    volumes:
      - "${TMPDIR:-/var/lib/localstack}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - "local"

networks:
  local:
    driver: "bridge"
```
do i need to give any kind of port number in docker configuration ?

### Expected Behavior

Expected to print incoming request on port 3000 from lambda 

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal s3 mb s3://mybucket

### Environment

```markdown
- OS: windows 11
- LocalStack: latest
```

**Comment by dfangl** [comment]
Hi!
Can you please use the default docker-compose.yml, as some configuration options you provide are quite unclear (https://github.com/localstack/localstack/blob/master/docker-compose.yml).
Also, can you please provide the snippet of your lambda code doing the request to the express server? Where is this express server running (on your host, in a docker container, another host, etc.)?

**Comment by MakarandPundlik** [comment]
> Hi! Can you please use the default docker-compose.yml, as some configuration options you provide are quite unclear (https://github.com/localstack/localstack/blob/master/docker-compose.yml). Also, can you please provide the snippet of your lambda code doing the request to the express server? Where is this express server running (on your host, in a docker container, another host, etc.)?

Hi @dfangl , thanks for your response
 Yeah i'll use the default docker image 
 and attaching the code snippet of my lambda
 My express server is running independently on ```port 3000``` 
 And i also have one elasticsearch image which is a part of the same file where localstack image is placed 
 I'm unable to connect with elastic search too. Thant issue i have described over here 
 https://stackoverflow.com/questions/74846406/unable-to-connect-to-elasticsearch-service-using-aws-lambda 
 
 this is my lambda snippet 
 ```
 module.exports.myLambda = async () => {
    let response;
    axios.get("http://localhost:3000").then((result) => {
        response = result
        console.log(result)
    }).catch((err) => {
        console.log(err)
    });
    console.log("this is the second line")
    return {
        statusCode: 200,
        body: JSON.stringify({
            response,
            msg:"hello from ES"
        })
    }
}

**Comment by dfangl** [comment]
Hi @MakarandPundlik !
Your lambda is running inside docker. So `localhost` actually addresses your docker container, not your host machine.
If you run your express server on the host, please use `host.docker.internal` as hostname, which will address the host from your docker container.
Same with elasticsearch, if it is running on the host.
So basically, your code would look like this:
```
module.exports.myLambda = async () => {
   let response;
   axios.get("http://host.docker.internal:3000").then((result) => {
       response = result
       console.log(result)
   }).catch((err) => {
       console.log(err)
   });
   console.log("this is the second line")
   return {
       statusCode: 200,
       body: JSON.stringify({
           response,
           msg:"hello from ES"
       })
   }
} 
```
(haven't tested the code itself, but this address should work)
If you run them in separate docker containers, I would recommend adding them to the same network (in docker compose, the easiest would be adding them to the same stack), and address them by name.

**Comment by MakarandPundlik** [comment]
Hi @dfangl, **thank you soo much** this is working, now i'm able to connect to my server at ```port 3000``` using lambda 
I can see the logs on port 3000 i.e. i've received a request from my lambda 
Now I'm also getting ```Error executing Lambda function arn:aws:lambda:us-east-1:000000000000:function:localstack-lambda-local-hello: {"errorType": "TimeoutError", "errorMessage": "Function execution timed out", "stackTrace": []} Traceback (most recent call last):``` this error with ```statusCode 500```
Do you have any inputs on this why it is happening?

**Comment by dfangl** [comment]
This usually happens when the function execution takes longer than the default, which is 3 seconds.
Does your express server correctly log the request by the lambda?
You can try increasing the timeout of your function, by adding `Timeout=30` to your function creation parameters, if it barely exceeds this, but I would guess it hangs for some other reason.

**Comment by MakarandPundlik** [comment]
> This usually happens when the function execution takes longer than the default, which is 3 seconds. Does your express server correctly log the request by the lambda? You can try increasing the timeout of your function, by adding `Timeout=30` to your function creation parameters, if it barely exceeds this, but I would guess it hangs for some other reason.

I can't thank you enough man @dfangl, you have solved my huge headache, i was searching for this localstack network issue from last 2 weeks, you came in as a ray of hope.

**Comment by dfangl** [comment]
Great to hear it is being resolved! Will close this now, if you have any more questions, please do not hesitate to ask. For questions regarding the usage, and not so much a bug report, you can also use our discussion pages: https://discuss.localstack.cloud/
