### ISSUE TITLE
feature request: implement efs.DescribeLifecycleConfiguration

### ISSUE THREAD

**Issue by SanderHagen** [localstack/localstack#7370]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm using Localstack in combination with Pulumi. When creating a simple efs FileSystem it throws the error efs.DescribeLifecycleConfiguration is not implemented or a pro feature. I am using a Pro API key. 

This is a simple block of Pulumi code that triggers the issue
```
import * as aws from '@pulumi/aws';
import * as pulumi from '@pulumi/pulumi';

  // ECS - EFS
  new aws.efs.FileSystem('subspaceEfs', {
    tags: {
      Name: 'subspace',
    },
  });
```

### Expected Behavior

In this case I think `DescribeLifecycleConfiguration` should return some kind of response showing there is no lifecycle configuration. 

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    localstack start

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)
  new aws.efs.FileSystem('subspaceEfs', {
    tags: {
      Name: 'subspace',
    },
  });

### Environment

```markdown
- OS:22.04
- LocalStack: pro 1.3.1
```

**Comment by dfangl** [comment]
Hi!
As seen here: https://docs.localstack.cloud/references/coverage/#efs this operation is currently not implemented. I will mark this as a feature request instead, as it is not technically a bug.

**Comment by whummer** [comment]
Hi @SanderHagen , thanks for reporting, and apologies for the long delay. We have now pushed a couple of enhancements for EFS, including the `DescribeLifecycleConfiguration` API. Can you please pull the `latest` Docker image and give it another try deploying the Pulumi stack? Please keep us posted on how it goes.. Thanks!

**Comment by whummer** [comment]
Closing as resolved - please do let us know if the problem persists.. Thanks!
