### ISSUE TITLE
bug: Can't create a cloudwatch log group using latest AWS SDK/CLI

### ISSUE THREAD

**Issue by ricoli** [localstack/localstack#7378]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

A 500 error happens in localstack that indicates localstack might need a boto upgrade to get newly added functionality:
```
2022-12-21T16:51:43.172  INFO --- [   asgi_gw_4] localstack.request.http    : POST / => 500
2022-12-21T16:51:48.727 ERROR --- [   asgi_gw_0] l.aws.handlers.logging     : exception during call chain
Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/model.py", line 362, in operation_model
    model = self._service_description['operations'][operation_name]
KeyError: 'ListTagsForResource'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/code/localstack/localstack/aws/protocol/parser.py", line 172, in wrapper
    return func(*args, **kwargs)
  File "/opt/code/localstack/localstack/aws/protocol/parser.py", line 895, in parse
    operation = self.service.operation_model(operation_name)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/utils.py", line 1419, in _cache_guard
    result = func(self, *args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/model.py", line 364, in operation_model
    raise OperationNotFoundError(operation_name)
botocore.model.OperationNotFoundError: ListTagsForResource

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/code/localstack/localstack/aws/chain.py", line 90, in handle
    handler(self, self.context, response)
  File "/opt/code/localstack/localstack/aws/handlers/service.py", line 63, in __call__
    return self.parse_and_enrich(context)
  File "/opt/code/localstack/localstack/aws/handlers/service.py", line 76, in parse_and_enrich
    operation, instance = parser.parse(context.request)
  File "/opt/code/localstack/localstack/aws/protocol/parser.py", line 176, in wrapper
    raise UnknownParserError(
localstack.aws.protocol.parser.UnknownParserError: An unknown error occurred when trying to parse the request.
```

### Expected Behavior

CloudWatch Log group to be successfully created

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal logs create-log-group --log-group-name test

### Environment

```markdown
- OS: Ubuntu 22.04
- LocalStack: latest, and also 1.3.1
```

**Comment by steffyP** [comment]
Hi @ricoli, 
thanks for reporting! I was just about to create a ticket myself. 

You are right, we need to upgrade, but we are still facing some other issues related to the upgrade, that need to be resolved first.

I assume the replication with `awslocal s3 mb s3://mybucket` is just a remainder of the bug-template LocalStack provides?


### Workaround in the meantime
**AWS CLI**
* use older CLI version (<= 2.9.7, see also[ change logs](https://raw.githubusercontent.com/aws/aws-cli/v2/CHANGELOG.rst))
* use the deprecated cloudwatch APIs, e.g. `ListTagsLogGroup`

**Terraform**
* use `terraform-provider-aws` version <= 4.46
* e.g. in your terraform.tf:
```
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "= 4.46.0"
    }
  }
}
```
* and then run `tflocal init -upgrade`

**Comment by ricoli** [comment]
> I assume the replication with awslocal s3 mb s3://mybucket is just a remainder of the bug-template LocalStack provides?

Indeed it was - sorry, I've edited it now. Thanks for pinpointing the exact version before this change was picked up by the terraform AWS provider, most helpful!

**Comment by cabeaulac** [comment]
This just broke all of our pulumi pipelines. Changing dev containers to version specified above now.

**Comment by cabeaulac** [comment]
If you're using pulumi typescript for your IaC. Make sure to set the version of `@pulumi/aws` to `5.23.0` without the `^`.
This will get you the version of the aws-sdk for javascript that works with the older CloudWatchLogs.
```
{
  "name": "app",
  "devDependencies": {
    "@types/node": "^18.11.17"
  },
  "dependencies": {
    "@aws-sdk/client-cloudfront": "^3.236.0",
    "@aws-sdk/credential-providers": "^3.236.0",
    "@pulumi/aws": "5.23.0",
    "@pulumi/awsx": "^1.0.1",
    "@pulumi/command": "^0.7.0",
    "@pulumi/postgresql": "^3.6.0",
    "@pulumi/pulumi": "^3.50.2"
  }
}
```

**Comment by steffyP** [comment]
Hi @ricoli, hi @cabeaulac,

we recently pushed changes, that should fix the problem. Could you please pull the `latest` localstack image and confirm that the issue is resolved?

**Comment by cabeaulac** [comment]
Changes fixed creation of log group!
Now I'm blocked from using latest with this:
https://github.com/localstack/localstack/issues/7391

**Comment by lorengordon** [comment]
@steffyP Thanks! I can also confirm the latest docker image fixes the issue I was seeing with recent versions of the aws provider and calls to logs:ListTagsLogGroup.

**Comment by lorengordon** [comment]
@steffyP Do you happen to have a timeline on a new release that will include the patch for this issue?

**Comment by steffyP** [comment]
Hi @lorengordon,

we do not have a timeline yet, but the patch will definitely be included in the next release. 
Hope you can work with the `latest` image in the meantime! 🙏

**Comment by seed-doordash** [comment]
How do i get around this without using docker?

Our local env is set up with pip install localstack
