### ISSUE TITLE
S3 does not trigger Lambda when the event is s3:ObjectAcl:Put

### ISSUE THREAD

**Issue by gustavotemple** [localstack/localstack#7407]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

S3 does not trigger Lambda when the event is:
`s3:ObjectAcl:Put`

With the event below e.g. works fine:
`s3:ObjectCreated:Put`

### Expected Behavior

In the AWS works fine, S3 triggers the Lambda with both events:
`s3:ObjectAcl:Put`
`s3:ObjectCreated:Put`

### How are you starting LocalStack?

Custom (please describe below)

#### Starting localstack:

    docker-compose down -v --remove-orphans && docker-compose up

#### Put the trigger:

```shell
aws --endpoint-url=http://localhost:4566 s3api put-bucket-notification-configuration --bucket bucket --notification-configuration file://notification.json
```
```json
{
  "LambdaFunctionConfigurations": [
    {
      "Id": "xxxxxxxxxx",
      "LambdaFunctionArn": "arn:aws:lambda:us-east-1:000000000000:function:xxxxxxxxxx",
      "Events": [ "s3:ObjectAcl:Put" ],
      "Filter": {
        "Key": {
          "FilterRules": [
            {
              "Name": "suffix",
              "Value": ".json"
            }
          ]
        }
      }
    }
  ]
}
```

#### Check the trigger:

```shell
aws --endpoint-url=http://localhost:4566 s3api get-bucket-notification-configuration --bucket bucket
```

#### Change ACL:

The command below works fine, but do not trigger the Lambda:
```shell
aws --endpoint-url=http://localhost:4566 s3api put-object-acl --bucket bucket --key key --grant-full-control id=canonical
aws --endpoint-url=http://localhost:4566 s3api get-object-acl --color on --bucket bucket --key key
```

#### Try with SDK:

Even using `s3AsyncClient.putObjectAcl`, similar to the code below, the Lambda is not triggered:
https://github.com/awsdocs/aws-doc-sdk-examples/blob/main/javav2/example_code/s3/src/main/java/com/example/s3/SetAcl.java

### Environment

```markdown
- OS: Ubuntu 18.04
- LocalStack: latest
```

### Anything else?

However, if I change the event e.g. to `s3:ObjectCreated:Put`, the Lambda trigger works fine:
```shell
aws --endpoint-url=http://localhost:4566 s3 cp notification.json s3://bucket/notification.json
```

**Comment by bentsku** [comment]
Hi @gustavotemple,

You're right, `s3:ObjectAcl:Put` is currently not supported.

The list of current supported events is :
- `PutObject`
- `CopyObject`
- `CompleteMultipartUpload`
- `PostObject`
- `PutObjectTagging`
- `DeleteObjectTagging`
- `DeleteObject`
- `DeleteObjects`

I'll start working on it next week, I'll link the PR to the issue so you can follow.
Thanks for the report!

**Comment by bentsku** [comment]
Hi @gustavotemple! #7409 just implemented support for it. However, to get that feature, you'll need to use the new implementation of S3 we've been working and that will be the default in the next major release. You can use this new implementation with `PROVIDER_OVERRIDE_S3=asf` (for configuration of LocalStack, you can see [here](https://docs.localstack.cloud/references/configuration/)). Thanks again for your report!
