### ISSUE TITLE
feature request: add support to Athena engine version 3

### ISSUE THREAD

**Issue by yuvalshi0** [localstack/localstack#7419]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Amazon announced [Athena engine version 3](https://aws.amazon.com/about-aws/whats-new/2022/10/amazon-athena-announces-upgraded-query-engine/) which adds more functionality - more functions and also trino support. The current Athena implementation only support Athena engine version 2 which uses presto only,

**Comment by whummer** [comment]
Hi @yuvalshi0 , thanks for reporting. We have in the meantime pushed a number of enhancements for Athena, including support for Trino (now the default). 

Please note that these changes are currently behind a feature flag that can be enabled by setting `BIGDATA_MONO_CONTAINER=1` in the LocalStack container environment. 

Can you please give that a try and let us know if it works for you. Looking forward to getting your feedback! If you can share some details about your requirements, we can ensure that your use case is covered.. 👍 Thanks!

**Comment by yuvalshi0** [comment]
@whummer closing since I don't have a concrete example, we dropped out the spec of the feature which required trino specific feature
