### ISSUE TITLE
bug: RDS includeResultMetadata Unable to execute statement: unhashable type: 'UniqueList'

### ISSUE THREAD

**Issue by amitassaraf** [localstack/localstack#7421]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We are using Localstack Pro w/ AppSync and RDS. 
We've setup an AppSync resolver on RDS and are executing this query -  

`"SELECT name, customer_id, card_number, expiration, COALESCE(books.status, cards.status) as status, type, COALESCE(books.user_id, cards.user_id) as user_id, CASE WHEN books.user_id IS NOT NULL THEN 'Book' WHEN cards.user_id IS NOT NULL THEN 'Card' ELSE 'User' END as __typename FROM users LEFT OUTER JOIN books ON users.id = books.user_id LEFT OUTER JOIN cards ON users.id = cards.user_id"`

And we've been getting the following error -
BadRequestException: An error occurred (BadRequestException) when calling the ExecuteStatement operation: Unable to execute statement: unhashable type: 'UniqueList'

After a lot of digging, we found it is **not** an issue with AppSync but with the following statement inside the `appsync/resolvers.py.enc` file:
`execute_statement(resourceArn=get_rds_cluster_arn(J),secretArn=K,database=I,sql=M,includeResultMetadata=True);`
The issue is that this statement fails when you pass `includeResultMetadata=True`, in the case that you pass `False`, this error disappears.

This makes us think that the issue is with the RDS implementation, not AppSync. 

**Also note that this issue seems to be related to the COALESCE / CASE statements, without them it works fine.**
Can you please apply a fix to this?

### Expected Behavior

The statement should successfully execute and return the result.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

We've managed to reproduce this error outside of AppSync, by just calling execute_statement with boto3 -
`client.execute_statement(resourceArn="OUR_CLUSTER", secretArn="OUR_SECRET", database="postgres", sql="SELECT name, customer_id, card_number, expiration, COALESCE(books.status, cards.status) as status, type, COALESCE(books.user_id, cards.user_id) as user_id, CASE WHEN books.user_id IS NOT NULL THEN 'Book' WHEN cards.user_id IS NOT NULL THEN 'Card' ELSE 'User' END as __typename FROM users LEFT OUTER JOIN books ON users.id = books.user_id LEFT OUTER JOIN cards ON users.id = cards.user_id", includeResultMetadata=True)`

BadRequestException: An error occurred (BadRequestException) when calling the ExecuteStatement operation: Unable to execute statement: unhashable type: 'UniqueList'

### Environment

```markdown
- OS: macOS 13.1 M1
- LocalStack: localstack-pro:latest
```

**Comment by steffyP** [comment]
Hi @amitassaraf,

thanks for reporting. 
Could you please add some more details - best case would be a reproducible example from scratch, so we can take a look on the issue 🙂 
In particular, the database version you are specifying would be most helpful (from your execute statement I assume you use engine `postgres`).

**Comment by amitassaraf** [comment]
@bentsku Seems like this is due to the usage of sql_metadata library which implements UnqiueList, for us this happens due to us using `column as nickname`, patching the sql_metadata library in the localstack docker to use our version which implements __hash__ for the UnqiueList they implemented works :) https://github.com/landaio/sql-metadata

**Comment by bentsku** [comment]
I was looking at it, but making the list hashable does not implement the right behaviour down the line. I'll submit a fix and come back once the fix is available in the latest image.

**Comment by bentsku** [comment]
Hello again @amitassaraf,

It seems the fix is now available in the latest image. Could you try running `docker pull localstack/localstack-pro:latest` and see if your issue is resolved? I've tried running queries and I don't have the issue anymore. 

Thanks for your feedback!

**Comment by amitassaraf** [comment]
@bentsku will take a look today

**Comment by amitassaraf** [comment]
@bentsku Seems resolved!
