### ISSUE TITLE
bug: Update Queries in QLDB do not return the updated documentId, instead return b'null'

### ISSUE THREAD

**Issue by amitassaraf** [localstack/localstack#7433]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In QLDB when running an update query, the cursor returns the updated documentIds, just like in insert.

Seems that when doing this in localstack QLDB the cursor returns b'null' values, while doing insert works fine.

`UPDATE Book SET name = ? WHERE Book.id = ?`

result._page returns - 
`{'Values': [{'IonBinary': {'documentId': b'null'}}}]`

### Expected Behavior

I would expect the documentId be the documents that I updated in the query.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

### Environment

```markdown
- OS: macOS M1 13.1 
- LocalStack: localstack-pro:latest
```

**Comment by whummer** [comment]
Hi @amitassaraf , quick update - we have pushed a few changes to improve the handling of `UPDATE` queries, and to properly return `documentId` of updated documents. When you get a chance, can you please pull the `latest` Docker image and give it another try? Thanks!

**Comment by whummer** [comment]
Closing as resolved - please do let us know if the problem persists.. Thanks
