### ISSUE TITLE
feature request: Add support to Athena for Iceberg table

### ISSUE THREAD

**Issue by MarcelStranak** [localstack/localstack#7435]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Add support for Iceberg tables for Athena service.
Queries and setup can be found on: https://docs.aws.amazon.com/athena/latest/ug/querying-iceberg-creating-tables.html

It should be partially supported in Athena v2 and fully supported in Athena v3.

### Anything else?

Request based on [Slack channel](https://localstack-community.slack.com/archives/C03L6CDN5T7).

**Comment by whummer** [comment]
Initial support for Iceberg tables in Athena has been added (available in the `latest` Docker image) - closing this issue. See also conversation in https://github.com/localstack/localstack/issues/7497
