### ISSUE TITLE
When using localstack with serverless, Invalid security token error is thrown.

### ISSUE THREAD

**Issue by somu90091** [localstack/localstack#744]
Hi,

I am trying to deploy a simple node js app with serverless onto localstack. Getting the below error:

Serverless: Configuring serverless offline -> localstack
Serverless: Configuring serverless offline -> kinesis consumer
Serverless: Packaging service...
Serverless: Excluding development dependencies...
 
  Serverless Error ---------------------------------------
 
  ServerlessError: The security token included in the request is invalid.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless
 
  Your Environment Information -----------------------------
     OS:                     linux
     Node Version:           4.2.6
     Serverless Version:     1.26.1

Please help me in this.

**Comment by jonaskint** [comment]
@somu90091 did you specify your endpoint? Try something that looks like:
```
aws --endpoint-url=http://localhost:4574 lambda invoke --function LAMBDANAME '{}'
```

**Comment by whummer** [comment]
Thanks for reporting @somu90091 . Can you please provide more details about your node.js application. Judging from the output above, it seems that you're using the [serverless offline](https://github.com/dherault/serverless-offline) plugin. Any chance you can point us to a github repository with your app code, to reproduce this error? Thanks

**Comment by somu90091** [comment]
Hi,

I am using sls deploy with localstack configured. I am getting the below
error:
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Using serverless-localstack-plugin

Serverless Error ---------------------------------------

ServerlessError: Service Unavailable

When Accessing the localstack resources from code, it is working. Only when
trying to deploy on local using serverless, it is failing.
Kindly help me.

**Comment by whummer** [comment]
Closing this issue for now - should be fixed with the latest changes on `master`. Please re-open or comment here if the problem persists. thanks
