### ISSUE TITLE
Flag to disable enforcement of "Lambda's 4KB environment variable size limit”

### ISSUE THREAD

**Issue by ayeganyan** [localstack/localstack#7442]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

In previous Localstack versions "Lambda's 4KB environment variable size limit” was not enforced, therefore we used as a  workaround for not using wrapper script (https://docs.aws.amazon.com/lambda/latest/dg/runtimes-modify.html#runtime-wrapper). With 1.3.1 our flow is breaking.

I would expect some option when running localstack to ignore lambda 4kb size limit.

**Comment by dfangl** [comment]
Hi @ayeganyan !
Our new, beta, lambda provider (enable using `PROVIDER_OVERRIDE_LAMBDA=asf`) supports lambda wrapper scripts the same way as AWS does.
Would using this provider, to drop your workaround, be a sufficient solution for you? I just filed a PR to verify this functionality is indeed working as expected, and it does.
Please keep in mind wrapper scripts are only supported for amazon linux 2 runtimes, except `provided.al2`.

**Comment by ayeganyan** [comment]
Hi @dfangl,
Thanks for the update!
Does this mean we still have to create a lambda layer? (like AWS does)

We still are on the basic localstack, and don't have access to layers (Pro)

**Comment by dfangl** [comment]
While it is, for reusability, recommended and present in the example, this is not necessary.
You can include the wrapper script in your deployment archive, and set the environment variable to the path `/var/task/<path_inside_archive>` and it should work identically.

**Comment by ayeganyan** [comment]
The problem here is that we don't actually control the archive build...

Can we prioritize having an option to just disable enforcement? or maybe there is some other workaround?

**Comment by dfangl** [comment]
For now, as a workaround, you could use the `LAMBDA_DOCKER_FLAGS` to mount the wrapper script manually into (all) lambda containers (for those lambdas where you need it you will have to set the `AWS_LAMBDA_EXEC_WRAPPER`, for others it will be present but affect nothing).

As an example:
set `LAMBDA_DOCKER_FLAGS=-v /home/user/project/lambda_wrapper:/opt/lambda_wrapper` (lambda_wrapper has to be executable), and for the lambda set, as environment variable, `AWS_LAMBDA_EXEC_WRAPPER=/opt/lambda_wrapper`.

Please test if that would work for you! There are many validations in place for the lambda providers, and having config options to disable all of them, and maintain those configs, is something I'd rather avoid.

**Comment by ayeganyan** [comment]
Hi @dfangl,
Actually after removing AWS_LAMBDA_EXEC_WRAPPER, error is gone, and the reason was that volumes are not mounted into the lambda container.

My localstack env is:
> LAMBDA_DOCKER_FLAGS=-v /home/user/project/lambda-wrapper.sh:/opt/lambda-wrapper.sh 
where the source is the path in local machine

and lambda env is:
>"AWS_LAMBDA_EXEC_WRAPPER": "/opt/lambda-wrapper.sh"

I also passed -e option to `LAMBDA_DOCKER_FLAGS` and it also is not added to environment.

Any suggestions, how to proceed?

**Comment by dfangl** [comment]
Hi!
Sorry about that. This feature was added a couple of days after 1.3.1, so it does not yet contain it. Can you switch to `latest` for now, and check if it works there? I know it is not ideal, but there has not been a tagged release yet with this change.

**Comment by ayeganyan** [comment]
Ahh, I see... Is there any timeline for the new release?

I've tried with the latest and having this timeout error (posted also in a support channel)
Here is the steps to reproduce:

1. Run Localstack with the command:
`docker run --rm -d -v /Users/ayeganyan/workspace/sandbox/lambda-nodejs/artifacts:/artifacts -p 4566 -e LAMBDA_DOCKER_FLAGS="-v /Users/ayeganyan/workspace/sandbox/lambda-nodejs/artifacts/lambda-wrapper.sh:/armen/lambda-wrapper.sh" -e PROVIDER_OVERRIDE_LAMBDA=asf -v "/var/run/docker.sock:/var/run/docker.sock:rw" localstack/localstack:1.3.1`
2. ssh to the container
3. Create lambda:
`awslocal lambda create-function --function-name test1 --role arn:aws:iam::000000000000:role/DummyRole --runtime python3.8 --handler python.main.handle --zip-file fileb:///artifacts/python.zip --memory-size 1024 --timeout 20 --environment '{"Variables": {"AWS_LAMBDA_EXEC_WRAPPER": "/armen/lambda-wrapper.sh"}}'`
4. Invoke the lambda:
`awslocal lambda invoke --function-name test2 --payload '{"var": "TEST_ENV"}'   --invocation-type RequestResponse out   && cat out`
The 4th step is hanging then exits with timeout.


While execution I see container starting and stopping (retrying), but I see the volume is not attached.

**Comment by ayeganyan** [comment]
Also I have tried to make the zip with wrapper script, and it also throws an error:
here is the zip file:
>   Length      Date    Time    Name
> ---------  ---------- -----   ----
>       212  01-12-2023 12:43   lambda.js
>       525  01-17-2023 15:39   lambda-wrapper.sh
> ---------                     -------
>       737                     2 files

I create function with:
> awslocal lambda create-function --function-name test1 --role arn:aws:iam::000000000000:role/DummyRole --runtime nodejs14.x --handler node.handler --zip-file fileb:///artifacts/node.zip --memory-size 1024 --timeout 20 --environment '{"Variables": {"AWS_LAMBDA_EXEC_WRAPPER": "/lambda-wrapper.sh"}}'

And when I invoke, I see in the spinned container `/lambda-wrapper.sh: does not exist` error

**Comment by ayeganyan** [comment]
Hi @dfangl

Found the cause of confusion (why it worked in some cases and did not work in other). Localstack uses lambci/lambda docker image internal to start the lambda, and in python3.7 lambda wrapper does not work and in python3.8 it is working…
I think the above should be considered in the next release.

Also can confirm behavior is the same in localstack:latest and localstack:1.3.1 ( I see you have added tests covering `AWS_LAMBDA_EXEC_WRAPPER` functionality)

**Comment by dfangl** [comment]
The new lambda provider you are enabling (with PROVIDER_OVERRIDE_LAMBDA=asf) should not use the lambci images anymore. If you see this in the logs, something went wrong with setting the provider.

Nevertheless, I am glad it is now working! Please note that it does not work on python3.7 due to restrictions on AWS itself: https://docs.aws.amazon.com/lambda/latest/dg/runtimes-modify.html#runtime-wrapper
> Wrapper scripts are supported on all native [Lambda runtimes](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html) which use the Amazon Linux 2 operating system. The custom provided.al2 runtime does not support wrapper scripts.

This excludes python3.7, as it is on amazon linux 1.

**Comment by ayeganyan** [comment]
Hi @dfangl 
Just saw what PROVIDER_OVERRIDE_LAMBDA is doing, and seems the new image is not supporting `LAMBDA_DOCKER_FLAGS`, is it known issue?

**Comment by dfangl** [comment]
This is the part which is only supported in :latest and not :1.3.1. The exec wrappers worked before, but the lambda docker flags do not. Can you try again with a freshly pulled :latest , then the LAMBDA_DOCKER_FLAGS should be respected.

**Comment by ayeganyan** [comment]
Hey @dfangl, thanks for your active support! it is working now!
Still have trouble but not related to this issue (related to lambda with dynamodb as an event source), so I guess this ticket can be closed

**Comment by dfangl** [comment]
Great to hear! If you have any more problems, please do not hesitate to open another issue. You can also post to our discussion pages (https://discuss.localstack.cloud/) if it is more of a question than a bug report.

**Comment by joe4dev** [comment]
Hi @ayeganyan  

We [recently](https://github.com/localstack/localstack/commit/aeb3000b8e71ba79743d206d23ea1cdf63a84518#diff-8ee48b2bcad465473db1a1b202781ca2c7c23db7bd1670e79d45668fb2bd718fR703) made this limit configurable. You can try to increase the limit for `LAMBDA_LIMITS_MAX_FUNCTION_ENVVAR_SIZE_BYTES` beyond the current default of `4096` bytes (i.e., 4 KB).
Remember to pull the latest Docker image, which will contain the LocalStack v2.0 release (candidate). See https://github.com/localstack/localstack/issues/7882

We have not added these limits to the officially supported lambda [configuration](https://docs.localstack.cloud/references/configuration/#lambda) documentation to avoid configuration overload. However, we can envision more configurable limits in the future if that is a desired feature.
