### ISSUE TITLE
bug: S3 ASF Provider does not appear to support virtual-host style requests

### ISSUE THREAD

**Issue by poconnor-lab49** [localstack/localstack#7449]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Using the S3 ASF provider, trying to fetch an object using S3 virtual-host style requests like

`curl -H "Host: test-bucket.localhost.localstack.cloud" http://localhost.localstack.cloud:4566/testfile.txt`

results in an error

```xml
<?xml version='1.0' encoding='utf-8'?>
<Error><Code>NoSuchBucket</Code><Message>The specified bucket does not exist</Message><RequestId>CC1D26J86EMA9PP8UJY4AMKUBPS0E188KTPMO8HQVECZ58J04LKF</RequestId><BucketName>testfile.txt</BucketName></Error>
```

Path style requests like `curl http://localhost.localstack.cloud:4566/test-bucket/testfile.txt` work fine, and so does the legacy S3 provider.

### Expected Behavior

Path and Virtual Host requests work the same in both providers

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)
`docker compose up`

Using _docker-compose.yaml_

```yaml
services:
  ###
  # AWS services
  # localstack home: https://github.com/localstack/localstack
  ###
  localstack:
    image: local/localstack:1.3.2.dev0
    ports:
      - 4566:4566
    expose:
      - 4566
    networks:
      curl:
    environment:
      PROVIDER_OVERRIDE_S3: asf
      EAGER_SERVICE_LOADING: 1
      SERVICES: s3
      DEBUG: ${DEBUG_LOCALSTACK:-0}
networks:
  curl:
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```sh
$ aws --endpoint http://localhost.localstack.cloud:4566 s3api list-buckets \
     && aws --endpoint http://localhost.localstack.cloud:4566 s3api create-bucket --bucket test-bucket
$ echo "Text file body" >> testfile.txt
$ curl -T testfile.txt http://localhost.localstack.cloud:4566/test-bucket/testfile.txt
<?xml version='1.0' encoding='utf-8'?>
<PutObjectOutput />
$ aws --endpoint http://localhost.localstack.cloud:4566 s3api list-objects --bucket test-bucket
{
    "Contents": [
        {
            "Key": "testfile.txt",
            "LastModified": "2023-01-06T16:44:57+00:00",
            "ETag": "\"05e863e3ae1d9452c450d9f43333d3fe\"",
            "Size": 15,
            "StorageClass": "STANDARD",
            "Owner": {
                "DisplayName": "webfile",
                "ID": "75aa57f09aa0c8caeab4f8c24e99d10f8e7faeebf76c078efc7c6caea54ba06a"
            }
        }
    ]
}

$ curl http://localhost.localstack.cloud:4566/test-bucket/testfile.txt
Text file body
$ curl -H "Host: test-bucket.localhost.localstack.cloud" http://localhost.localstack.cloud:4566/testfile.txt
<?xml version='1.0' encoding='utf-8'?>
<Error><Code>NoSuchBucket</Code><Message>The specified bucket does not exist</Message><RequestId>CC1D26J86EMA9PP8UJY4AMKUBPS0E188KTPMO8HQVECZ58J04LKF</RequestId><BucketName>testfile.txt</BucketName></Error>
```

### Environment

```markdown
- OS: Slackware-current (5.19.17)
- LocalStack: latest (d3f51d516af88ab56b06f29ca30bb4142595c8d4)
```

### Anything else?

Comment out `PROVIDER_OVERRIDE_S3: asf`  in the _docker-compose.yaml_ file and everything works fine.

**Comment by bentsku** [comment]
Hi @poconnor-lab49 and thanks for your report!

The fact that the `localhost.localstack.cloud` endpoint worked as a virtual-host endpoint for S3 was more of an issue than a feature, unfortunately, and could lead to conflicts with other services.
The official S3 endpoint to access your buckets in a virtual-host style is `s3.localhost.localstack.cloud`, and it is supported in the new provider. We will need to change the S3 documentation entry to match this change, sorry for that.

I hope this fix your issue, don't hesitate to give any feedback about the new provider and this change.
Thanks again!

**Comment by poconnor-lab49** [comment]
Thanks for the quick response!  I'd be happy to provide feedback on the updated documentation when you have a change ready for it.

In the meantime, could you give me a working example? I'm still running into issues, but at least they're different issues.  Is there some port environment variable I'm missing?

```sh
$ echo $(date --iso-8601=seconds) >| testfile.txt
$ curl -T testfile.txt http://s3.localhost.localstack.cloud:4566/test-bucket/testfile.txt
<?xml version='1.0' encoding='utf-8'?>
<PutObjectOutput />
$ curl http://s3.localhost.localstack.cloud:4566/test-bucket/testfile.txt
2023-01-07T11:27:25-05:00
$ curl -H "Host: test-bucket.s3.localhost.localstack.cloud" http://s3.localhost.localstack.cloud:4566/testfile.txt
<?xml version='1.0' encoding='utf-8'?>
<Error><Code>InternalError</Code><Message>exception while calling s3 with unknown operation: MyHTTPConnectionPool(host='s3.localhost.localstack.cloud', port=80): Max retries exceeded with url: /test-bucket/testfile.txt (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7f4b8add9510&gt;: Failed to establish a new connection: [Errno 111] Connection refused'))</Message><RequestId>0R70XJJFZVYILZH8FPCFBCIRJVMVR1WX4HRR4K14Y010G2ND29IV</RequestId></Error>
```

I also tried with `s3.us-east-1.localhost.localstack.cloud` but got the same results.

**Comment by bentsku** [comment]
Yes, the issue might stem from the fact that your Host header does not give the same port as the URL, and it seems you only exposed `4566` here.
Is there a particular reason you are manipulating the `host` header? 
Here's a sample I just tested locally.
```bash
$ awslocal s3api create-bucket --bucket test
{
    "Location": "/test"
}
$ echo "test file" > /tmp/testfile.txt 
$ curl -T /tmp/testfile.txt http://test.s3.localhost.localstack.cloud:4566/testfile.txt 
$ curl http://test.s3.localhost.localstack.cloud:4566/testfile.txt            
test file
# manipulating host headers
$ curl -H "Host: test.s3.localhost.localstack.cloud:4566" http://s3.localhost.localstack.cloud:4566/testfile.txt
test file
# here with a simple `localstack start` this worked, but this might be DNS/configuration related
$ curl -H "Host: test.s3.localhost.localstack.cloud" http://s3.localhost.localstack.cloud:4566/testfile.txt 
test file
```
For me, it works even without without the port specified in the `host` header, but it must come from DNS settings/port being exposed. This is an interesting issue (under the hood, we redirect virtual host addressed bucket requests to a path addressed route to make use of of our parsing framework, so effectively, it is like the container sending a request to `s3.localhost.localstack.cloud:80`, using your host header. We will look into it if changes need to be made). But maybe manipulating `host` header is not mandatory here, and would avoid this kind of issue. 

Tell me if this example works for you, and thanks again, I'll ask for feedback on the docs once it's done.

**Comment by poconnor-lab49** [comment]
@bentsku You are absolutely right and thanks for the help!  I should have opened this as a question.

I was setting the `host` header while trying to reproduce an error in a client library and was trying to eliminate misconfiguration of localstack on my part.  I completely forgot to validate the localstack configuration with a simple browser GET.

For reference, this is what sent me down the header path:

```txt
GET /filename.txt HTTP/1.1
Host: test-bucket.s3.localhost.localstack.cloud
Content-Length: 0
amz-sdk-invocation-id: 6e201a85-dcc0-bbba-884f-5ff962fdaf20
amz-sdk-request: attempt=1; max=1
Range: bytes=0-8388607
User-Agent: aws-sdk-java/2.18.38 Linux/5.19.17 OpenJDK_64-Bit_Server_VM/17.0.5+8-LTS Java/17.0.5 vendor/Red_Hat__Inc. io/async http/s3crt cfg/retry-mode/legacy ft/s3-transfer CRTS3NativeClient/0.1.x
X-Amz-Date: 20230108T142533Z
x-amz-content-sha256: UNSIGNED-PAYLOAD
Authorization: AWS4-HMAC-SHA256 Credential=localstack/20230108/us-east-1/s3/aws4_request, SignedHeaders=amz-sdk-invocation-id;amz-sdk-request;content-length;host;range;x-amz-content-sha256;x-amz-date, Signature=8301704f76b8e9215fb5dabd5ec8abbd5efd019956ed3cfe7fe8ec66b59c0370

HTTP/1.1 500 
Content-Type: application/xml
Content-Length: 521
x-amz-request-id: 73AFDLIMKAJ3MGMO80GE17HUICO3W89EF0T0BDIEL54ZE6G4QYXO
x-amz-id-2: MzRISOwyjmnup73AFDLIMKAJ3MGMO80GE17HUICO3W89EF0T0BDIEL54ZE6G4QYXO7/JypPGXLh0OVFGcJaaO3KW/hRAqKOpIEEp
Connection: close
date: Sun, 08 Jan 2023 14:25:33 GMT
server: hypercorn-h11

<?xml version='1.0' encoding='utf-8'?>
<Error><Code>InternalError</Code><Message>exception while calling s3 with unknown operation: MyHTTPConnectionPool(host='s3.localhost.localstack.cloud', port=80): Max retries exceeded with url: /test-bucket/filename.txt (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7f85475d3040&gt;: Failed to establish a new connection: [Errno 111] Connection refused'))</Message><RequestId>WWNWITGE0RKZDT0INYFVF2EPBCUTYLJVFK4HTJWTDMVHBAEPJOLI</RequestId></Error>
```
It seems like the client library might be dropping the `port` from the host header (or more misconfiguration by me), so I'll chase my issue in that project.

Really appreciate the help and if you'd like me to review documentation changes, please tag me when its ready!

**Comment by poconnor-lab49** [comment]
Just in case anyone else needs to work around a similar bug, I wanted to add that everything works perfectly if I proxy through nginx and manually add the port to the host header. Kind of dirty, but ...

Add a `service` to _docker-compose.yaml_:

```yaml
  ### 
  # Nginx
  # proxy connections to localstack
  ###
  nginx:
    image: nginx:${NGINX_VERSION}
    ports:
      - 8181:8181
    expose:
      - 8181
    networks:
      demo:
        aliases:
          - test-bucket.s3.localhost.localstack.cloud
    volumes:
      - ./nginx/conf.d/nginx-localstack.conf:/etc/nginx/conf.d/localstack.conf:ro
    depends_on:
      - localstack
```

with a _nginx-localstack.conf_ file that looks something like:

```nginx
upstream localstack {
  server localstack:4566;
}

server {
  listen 8181;
  server_name localhost;
  
  location / {
    proxy_pass http://localstack/;
    
    proxy_set_header        Host            $host:4566;
    proxy_set_header        X-Custom-Use    appending_port;
    proxy_set_header        X-Real-IP       $remote_addr;
    proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
  }
}
```

This should work for misbehaving clients both inside and outside the docker network.

**Comment by poconnor-lab49** [comment]
@bentsku Is there a way I can close this as "not a bug"?

**Comment by bentsku** [comment]
Hi @poconnor-lab49,

Thanks again for the feedback and the detailed write-up and workaround for the client misbehaving. We've encountered a similar issue but a it more explicitly here: https://github.com/localstack/localstack/issues/7295#issuecomment-1343058900
The JS SDK v3 is mangling the port from the URL as well, making it a bit easier to understand what is going on.

I have trouble understanding why the JDK client is manipulating `host` headers, and maybe we could work on preventing this kind of issue or at least logging a good exception message explaining what is happening. 

I can change the label of the issue to `question` if you prefer it, and you're then free to close the issue. 

Thank you again for your report, it was very helpful and it is good to uncover weird behaviour! I'll tag you once the documentation is updated.

**Comment by poconnor-lab49** [comment]
I was evaluating the (newly out of _-PREVIEW_) [CRT version of the AWS Java SDK v2 S3TransferManager](https://aws.amazon.com/blogs/developer/introducing-crt-based-s3-client-and-the-s3-transfer-manager-in-the-aws-sdk-for-java-2-x/) for a project.  Seems like there are still a few bugs to work out....

The default version of the S3AsyncClient works fine, but I wanted to use the CRT version for the multipart upload support and performance improvements. I'll report the issue to Amazon and see what they say.  

Thanks again for the engagement! Really appreciate your help on this!
