### ISSUE TITLE
bug: Creating EC2 via terraform throws InvalidParameterValue: Value (disableApiStop)

### ISSUE THREAD

**Issue by Lapsusone** [localstack/localstack#7469]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

> Error: reading EC2 Instance (i-9173ec676151d4d85) attribute: InvalidParameterValue: Value (disableApiStop) for parameter attribute is invalid. Unknown attribute.

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

```bash
localstack start
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)
With the following terraform file:
```terraform
provider "aws" {
  region     = "us-west-2"
  access_key = "PUT-YOUR-ACCESS-KEY-HERE"
  secret_key = "PUT-YOUR-SECRET-KEY-HERE"
}

resource "aws_instance" "myec2" {
  ami           = "ami-082b5a644766e0e6f"
  instance_type = "t2.micro"
}
```
```bash
tflocal init
tflocal apply
```

### Environment

```markdown
- OS: macOS 13.1
- LocalStack: 1.3.1
```

### Anything else?

Refer to https://github.com/localstack/localstack/issues/6509#issuecomment-1374707579

**Comment by viren-nadkarni** [comment]
Hi @Lapsusone , I'm afraid I could not to reproduce this. Some follow up questions:
- Which edition of LocalStack are you using, community or pro?
- Is anything reported in LocalStack logs? Could you share them?

**Comment by Lapsusone** [comment]
Hi @viren-nadkarni, I'm sorry I'm unable to reproduce. It is working now, I don't know what caused this.
