### ISSUE TITLE
bug: An error occurred (InvalidParameter) when calling the Subscribe operation: Invalid parameter: SQS endpoint ARN

### ISSUE THREAD

**Issue by barkhabajaj** [localstack/localstack#7471]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello Team,

I am getting this error when I am trying to subscribe to ARN:

`An error occurred (InvalidParameter) when calling the Subscribe operation: Invalid parameter: SQS endpoint ARN`

### Expected Behavior

I should be able to subscribe to ARN

### How are you starting LocalStack?

With the `localstack` script

### Steps To Reproduce

-configure AWS localstack profile 
`aws configure set aws_access_key_id "dummy" --profile localstack
aws configure set aws_secret_access_key "dummy" --profile localstack
aws configure set region "eu-central-1" --profile localstack
aws configure set output "table" --profile localstack
`
- Start localstack 
`localstack start -d `

- create SNS 
`aws --endpoint-url=http://localhost:4566 sns create-topic --name dummy-events --region eu-central-1 --profile localstack --output table | cat`

- create SQS 
`aws --endpoint-url=http://localhost:4566 sqs create-queue --queue-name dummy-pipe --profile localstack --region eu-central-1 --output table | cat`

- subscribe to ARN 
`aws --endpoint-url=http://localhost:4566 sns subscribe --topic-arn arn:aws:sns:eu-central-1:000000000000:dummy-events --profile localstack  --protocol sqs --notification-endpoint http://localhost:4566/000000000000/dummy-pipe --output table | cat`

I am getting error while subscribing to ARN

### Environment

```markdown
- OS: Apple M1 Pro, macOS Ventura 13.0
- LocalStack: 1.3.1
```

**Comment by bentsku** [comment]
Hello @barkhabajaj and thanks for your report.

We added some validation while creating SNS subscriptions to be more in line with AWS.

[From the AWS documentation](https://docs.aws.amazon.com/sns/latest/api/API_Subscribe.html), when subscribing to an SNS topic with the SQS protocol, the notification endpoint must be the SQS queue ARN, and not its URL. This is in line with AWS behaviour, as it will throw the same exception while trying those steps against it.

Could you try running those same operation but with the SQS queue ARN passed as the `--notification-endpoint` parameter? Thanks!

**Comment by barkhabajaj** [comment]
Thank you very much for quick response @bentsku. It indeed worked. Thanks a lot
