### ISSUE TITLE
bug: User information from Cognito generated JWT does not get passed to Lambda event through Appsync

### ISSUE THREAD

**Issue by romuaa** [localstack/localstack#7475]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We have localstack 1.3.1 set up with Cognito, AppSync and Lambdas. When we query the GraphQL API with ID token the Lambda event does not contain the user information from the id token. Here is the event data we actually receive:

```
{
  'arguments': {},
  'args': {},
  'info': {
    'fieldName': 'user',
    'parentTypeName': 'Query',
    'variables': {},
    'selectionSetList': [],
    'selectionSetGraphQL': 'query {\n user {\n id\n }\n}'
  },
  'stash': None,
  'identity': {
    'sub': 'admin'
  }
}
```

### Expected Behavior

We expect to receive the proper user information in the Lambda event as it is provided in the live AWS environment

```
{
  'arguments': {},
  'identity': {
    'claims': {
      'at_hash': 'qfwdfwdf',
      'sub': 'rgwrgwrgrw',
      'cognito:groups': [
        'eu-west-1_wrgwrgrgerg',
        'GROUP_1',
        'GROUP_2'
      ],
      'email_verified': False,
      'iss': 'https://cognito-idp.eu-west-1.amazonaws.com/eu-west-wefwfwfwref',
      'cognito:username': 'aad_wefwfwef.com',
      'given_name': 'wefwefwef',
      'nonce': 'qerwerwerwer',
      'custom:groups': '[DEV_GROUP_1, DEV_GROUP_2]',
      'origin_jti': 'wdfwfwdf',
      'aud': 'werwerwer',
      'identities': [
        {
          'dateCreated': '1671628379356',
          'userId': 'werwerwer.com',
          'providerName': 'AAD',
          'providerType': 'SAML',
          'issuer': 'https://werwerwer/',
          'primary': 'true'
        }
      ],
      'token_use': 'id',
      'auth_time': 1673358794,
      'name': 'werwerwer',
      'custom:user_organisation': 'werwerwer',
      'exp': 1673359094,
      'iat': 1673358794,
      'family_name': 'qwerwerwer',
      'jti': 'wewerwer',
      'email': 'werwerwer.com'
    },
    'defaultAuthStrategy': 'ALLOW',
    'groups': [
      'eu-west-1_werwerwer',
      'GROUP_1',
      'GROUP_2'
    ],
    'issuer': 'https://cognito-idp.eu-west-1.amazonaws.com/eu-west-werwerwer',
    'sourceIp': [
      'xxx.yyy.zzz.jjj'
    ],
    'sub': 'werwerwer',
    'username': 'werwerwerwe.com'
  },
  'source': None,
  'request': {
    'headers': {
      ...
    },
    'domainName': 'wefwefwefewf'
  },
  'prev': None,
  'info': {
    'fieldName': 'wefwfwefewf',
    'selectionSetList': [
      'id',
      'name',
      'created',
      'status',
      'startDate',
      'endDate',
      '__typename'
    ],
    'selectionSetGraphQL': '...',
    'parentTypeName': 'Query',
    'variables': {}
  },
  'stash': {}
}
```

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

Set up cognito
Set up Appsync
Set up a lambda
Retrieve token from cognito
call the lambda

### Environment

```markdown
- OS: MacOS Monterey, Apple M1
- LocalStack: 1.3.1
```

### Anything else?

There was previously a unanswered question for you about the same issue that was autoclosed by a bot
https://github.com/localstack/localstack/issues/5791

**Comment by simonrw** [comment]
Hi @romuaa, we have corrected the issue and the fix should be available in the latest docker image. Can you `docker pull localstack/localstack:latest` and try again? If you find any further issues, feel free to create a new issue.
