### ISSUE TITLE
bug: AppSync GraphQL schema directives require AND instead of OR with groups

### ISSUE THREAD

**Issue by romuaa** [localstack/localstack#7476]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When specifying a GraphQL schema

  endpoint: [Result!]!
    @aws_cognito_user_pools(cognito_groups: ["GROUP_1", "GROUP_2"])
    @aws_auth(cognito_groups: ["GROUP_1", "GROUP_2"])
    
localstack requires both of the groups assigned to the user in Cognito

### Expected Behaviour

Only one of the groups should be enough for authorising the user to call the endpoint as is the behaviour in live AWS

### How are you starting LocalStack?

With the `localstack` script

### Steps To Reproduce

Set up cognito, Appsync and a Lambda
Assign user to a group in cognito
define graphql schema that has an endpoint that requires user to have group(s) assigned
call the endpoint with the user ID token (only one group assigned)

### Environment

```markdown
- OS: MacOS Monterey, Apple M1
- LocalStack: 1.3.1
```

**Comment by dfangl** [comment]
Hi! We have pushed an update which should fix this issue. There were several other issues in the parity of the appsync API which occurred during testing, so the behavior might have slightly changed, but should be more on parity with AWS.
For example, erroring @aws_auth directives will result in an error in the errors section returned by the response, not a immediate 401 (this is reserved for issues with the jwt token, for example).

**Comment by romuaa** [comment]
I can confirm that the cognito_groups now work as expected with cognito auth directives and indeed the error messaging is now much better. Thank you!
