### ISSUE TITLE
bug: Unable to forward SNS message to SQS

### ISSUE THREAD

**Issue by QwerTech** [localstack/localstack#7479]
### Is there an existing issue for this?

- [X] I have searched the existing issues

#### Pre-configuration
I have a SNS topic and SQS queue.
There is also a valid subscription between them.

#### Behavior
When I send a message to SNS topic via `aws sns publish` and receive `MessageId` in response.

#### Current response
I receive nothing from SQS via `aws sqs receive-message`

### Expected Behavior

Once the message sent to SNS with existing SQS subscription the `aws sqs receive-message` should show the message.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

I have `docker-compose.yml` like this
```
version: '3.8'
services:
  localstack:
    container_name: "localstack"
    image: localstack/localstack:1.3.1
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
      - "127.0.0.1:53:53"                # DNS config (only required for Pro)
      - "127.0.0.1:53:53/udp"            # DNS config (only required for Pro)
    environment:
      - EAGER_SERVICE_LOADING=1
      - SERVICES=sns,sqs
      - DEBUG=1
      - PERSISTENCE=${PERSISTENCE-}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_DEFAULT_REGION=eu-west-1
      - HOSTNAME_EXTERNAL=localstack
    volumes:
      - "./init-localstack.sh:/etc/localstack/init/ready.d/init-aws.sh"  # ready hook
      - "./docker/localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

`init-localstack.sh` contains script below:
```
#!/usr/bin/env bash
 set -euo pipefail

 # enable debug
 # set -x

export AWS_ACCESS_KEY_ID="123456789012"
export AWS_SECRET_ACCESS_KEY="test"
export AWS_DEFAULT_REGION="eu-west-1"

awslocal sns create-topic --name test-topic --endpoint-url=http://localhost:4566
awslocal sqs create-queue --queue-name test-queue --endpoint-url=http://localhost:4566
awslocal sns subscribe --topic-arn arn:aws:sns:eu-west-1:123456789012:test-topic  \
  --protocol sqs \
  --notification-endpoint http://localhost:4566/123456789012/test-queue \
  --endpoint-url=http://localhost:4566
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

Once the message sent to SNS with existing SQS subscription with command below
```
aws sns publish --endpoint-url=http://localhost:4566 --topic-arn arn:aws:sns:eu-west-1:123456789012:test-topic --message "Hello World" --profile test
```
I receive `MessageId` in response. 

But script for receiving messages does not return message.
```
while sleep 1; do aws sqs receive-message --queue-url http://localhost:4566/123456789012/test-queue --endpoint-url http://localhost:4566 --profile test --no-cli-pager; done
```

### Environment

```markdown
- OS: MacOS 12.6.1(M1)
- Docker: 4.15.0 (93002)
- LocalStack: docker image 1.3.1
```

### Anything else?

Similar to https://github.com/localstack/localstack/issues/6315

There is no errors or anything suspicious in logs.

Noticed that the scenario worked in version `1.1` and starting from `1.2` and in `1.3.1` and today's `latest` it's not working.

**Comment by bentsku** [comment]
Hello @QwerTech  and thanks for your report.

We added some validation while creating SNS subscriptions to be more in line with AWS.

[From the AWS documentation](https://docs.aws.amazon.com/sns/latest/api/API_Subscribe.html), when subscribing to an SNS topic with the SQS protocol, the notification endpoint must be the SQS queue ARN, and not its URL. This is the same validation as AWS, as it will throw the same exception while trying those steps against it. Maybe the exception is not being logged from the script?

Could you try running those same operation but with the SQS queue ARN passed as the --notification-endpoint parameter? Thanks!

**Comment by nick-xero** [comment]
I ran into this problem as well & the exception was properly logged. @bentsku 

From the AWS CLI doc, [For the sqs protocol, the endpoint is the ARN of an Amazon SQS queue.](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/sns/subscribe.html)

**Comment by bentsku** [comment]
Hi @nick-xero and thanks for the feedback! I'll close the issue then.
