### ISSUE TITLE
Contributors not loading up. Broken links for backers and Contributors.  

### ISSUE THREAD

**Issue by Ayushverma8** [localstack/localstack#748]
Links like this https://opencollective.com/localstack/sponsor/X/website won't exist.
Just symlinks to https://opencollective.com/localstack#contributors.

**Comment by whummer** [comment]
Thanks for reporting @Ayushverma8 - where exactly are you seeing the broken links? Looks like the README is rendering properly now, may have been a temporary issue on Open Collective side?

**Comment by abdulrahman-khankan** [comment]
@whummer the README link is broken https://github.com/localstack/localstack/blob/master/graphs/contributors
