### ISSUE TITLE
No hosted zone is created when creating a private dns namespace

### ISSUE THREAD

**Issue by m1r4c** [localstack/localstack#7486]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello,

I am using the AWS Typescript CDK with Localstack and have an issue when creating a private dns namespace using a cloudmap construct.
The private dns namespace is created but no corresponding hosted zone seems to get created.

The hosts in the private dns namespace do not resolve in the localstack container either.

### Expected Behavior

When creating a private dns namespace in AWS a hosted zone is created as well, I am expecting the same to happen with Localstack.

Hosts created in this private dns namespace should resolve in the localstack container as well as any containers created by localstack or lambda functions.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

I created a repository with a small sample demonstrating the issue, located here:
https://github.com/m1r4c/localstack_issue_privatenamespace

### Environment

```markdown
- OS: WSL (Ubuntu 20.04) on Windows 10
- LocalStack: latest docker image of localstack-pro
```

### Anything else?

Repo demonstrating the issue:
https://github.com/m1r4c/localstack_issue_privatenamespace

**Comment by giograno** [comment]
Hi @m1r4c, thanks for opening this issue. You will find a fix in the `latest` Docker image. Please let us know if you have any other issue.
