### ISSUE TITLE
bug: lambda invoke fails with asf provider - Error message: ResourceConflictException

### ISSUE THREAD

**Issue by SchmitzChristian** [localstack/localstack#7490]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Using the new lambda Provider asf, lamda failed to invoke (on nodejs16 and nodejs18) With the old provider the same setup works for me.

Debug Logs:
`2023-01-13T16:46:15.603 DEBUG --- [Executor-1_0] l.s.a.i.version_manager    : Lambda 'arn:aws:lambda:eu-central-1:000000000000:function:lambda:$LATEST' changed to failed. Reason: Docker not available
 Traceback (most recent call last):
   File "/opt/code/localstack/localstack/services/awslambda/invocation/version_manager.py", line 160, in start
     get_runtime_executor().prepare_version(self.function_version)
   File "/opt/code/localstack/localstack/services/awslambda/invocation/docker_runtime_executor.py", line 309, in prepare_version
     CONTAINER_CLIENT.pull_image(image_name)
   File "/opt/code/localstack/localstack/utils/container_utils/docker_sdk_client.py", line 220, in pull_image
     self.client().images.pull(docker_image)
   File "/opt/code/localstack/localstack/utils/container_utils/docker_sdk_client.py", line 51, in client
     raise ContainerException("Docker not available")
 localstack.utils.container_utils.container_client.ContainerException: Docker not available`

`An error occurred (ResourceConflictException) when calling the Invoke operation: The operation cannot be performed at this time. The function is currently in the following state: Failed`

Also using LAMBDA_DOCKER_NETWORK option does not help.

### Expected Behavior

Lambda should run like without the asf Provider option.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack
    docker compose up

##### docker compose file
```
version: '3.5'
services:
  localstack:
    image: localstack/localstack:1.3.1
    ports:
      - "4669:4566"
    volumes:
      - ./localstack/lambda-stub.zip:/opt/code/lambda-stub.zip
      - ./localstack/init-localstack.sh:/etc/localstack/init/ready.d/init-localstack.sh
    environment:
      - DEFAULT_REGION=eu-central-1
      - SERVICES=lambda
      - SQS_PORT_EXTERNAL=4569
      - START_WEB=0
      - PROVIDER_OVERRIDE_LAMBDA=asf
      - DEBUG=1
```

##### lambda stub file (as zip file)
```
module.exports.handler =  async function(event, context) {
  console.log("EVENT: \n" + JSON.stringify(event, null, 2))
  return context.logStreamName
}
```

##### init-localstack.sh

```
#!/usr/bin/env bash
set -Eeuo pipefail
IFS=$'\n\t'
trap 'echo "Aborting due to errexit on line $LINENO. Exit code: $?" >&2' ERR


 awslocal lambda create-function \
    --region eu-central-1 \
    --function-name lambda \
    --runtime nodejs16.x \
    --handler lambda-stub.handler \
    --memory-size 128 \
    --zip-file fileb:///opt/code/lambda-stub.zip \
    --role arn:aws:iam::123456789012:role/irrelevant

awslocal lambda invoke --function-name lambda /tmp/lambda.out

echo "init localstack done"
```

### Environment

```markdown
- OS: Ubuntu 22.04
- LocalStack: 1.3.1
```

**Comment by jairov4** [comment]
Tried with python and gets the same issue

**Comment by dominikschubert** [comment]
Hi @jairov4 ! The new lambda implementation depends on docker being available in the container which does not seem the be the case based upon the `docker-compose` file you provided and the message in the logs.

Could you please try mounting the docker socket into the container?

You can do this by adding 
```
volumes:
  - "/var/run/docker.sock:/var/run/docker.sock"
```

to your `docker-compose` file.

**Comment by SchmitzChristian** [comment]
@dominikschubert it fixed it for me, sorry for the late response. I still have to figure out why it take several attemps but now it seems to be stable.
