### ISSUE TITLE
feature request: implement DELETE /_localstack/ses endpoint

### ISSUE THREAD

**Issue by ert78gb** [localstack/localstack#7491]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Provide an URL where I can delete stored SES emails.
My motivation is to write integration tests much easier, if I could delete the stored emails from the localstack before each test case. 

I use the docker image to run localstack. Mount the `/var/lib/localstack` folder to the host and delete the files from the `tmp/state/ses` is cumbersome because of the file permission issue of docker.

I think the simplest way to achieve the empty SES emails state is to implement a new endpoint in a same way as to the GET /_localstack/ses has been implemented:

**path:** /_localstack/ses
**method:** DELETE

### 🧑‍💻 Implementation

I am not a python developer, but I think one solution is to extend the [SesServiceApiResource](https://github.com/localstack/localstack/blob/590de96b3dd65e349709300b668e70f1f9664e99/localstack/services/ses/provider.py#L121) with an `on_delete` method.

Open question for me is either delete the `/var/lib/localstack/tmp/state/ses` folder or just delete the files of the `ses` folder.
The folder does not exist when the container starts. It is created when the first email received and saved by the service.
I think both solutions have the same performance impact, so the real question is what is preferred by the maintainers.

As I mentioned I am not familiar with python ecosystem but I am happy to help implementing the feature if you accept the request.

**Comment by TheSwarnim** [comment]
Hi Guys,
I'm new here and wanted to contribute to the project. Can anyone please assign this issue to me?

**Comment by gsilverstein** [comment]
Hello, just adding myself as a subscriber and happy to help out in testing if something comes of this. I have a similar case and currently waste a bit of CPU and we restart localstack to "clear" the emails when we re-run our tests but being able to just clear them explicitly in the test flow via an API call would be great.

**Comment by ert78gb** [comment]
Currently, I am very busy but I am planning to implement it at the beginning of February unless anyone does.

**Comment by marcuslange** [comment]
We are also looking for this functionality. It would also be very helpful in integration testing to have the ability to delete the message by id.

path: /_localstack/ses/ucppwjopwzbhfbxa-avxbjepo-qpxj-qfcx-actv-ntdeeqgfjikp-fajleq
method: DELETE

**Comment by shadowmaxxl** [comment]
I am new to this I would love to help great advice or insight into this problem would be helpful.

**Comment by gsilverstein** [comment]
Hi @shadowmaxxl what sort of information would you be looking for?
