### ISSUE TITLE
S3 Copy Object API doesn't handle URL-encoded slashes properly

### ISSUE THREAD

**Issue by dcormier** [localstack/localstack#750]
When I use aws cli (`aws-cli/1.11.129 Python/2.7.10 Darwin/17.5.0 botocore/1.5.92`), the [`aws s3api copy-object` command](https://docs.aws.amazon.com/cli/latest/reference/s3api/copy-object.html) doesn't work. I get this output:

`An error occurred (500) when calling the CopyObject operation (reached max retries: 4): Internal Server Error`

Running with `--debug` reveals the response body:
```html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>
```

I'm using the latest version of [this docker image](https://hub.docker.com/r/localstack/localstack/).

I found this while trying to use [the corresponding S3 `PUT Object - Copy` API](https://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectCOPY.html) in a test I've been working on.

**Comment by whummer** [comment]
Thanks for reporting @dcormier . This issue seems to be fixed in the meantime - working both, with escaped and unescaped slashes:
```
$ awslocal s3 cp test.xml s3://test/foo/bar/
$ awslocal s3api copy-object --copy-source test/foo/bar/test.xml --bucket test --key test1.xml
$ awslocal s3api copy-object --copy-source "test/foo%2Fbar%2Ftest.xml" --bucket test --key test2.xml
$ awslocal s3 ls s3://test
                           PRE foo/
2019-11-08 23:45:16       7046 test.xml
2019-11-08 23:45:29       7046 test1.xml
2019-11-08 23:49:59       7046 test2.xml
```
