### ISSUE TITLE
bug:Unable to start up EMR cluster

### ISSUE THREAD

**Issue by rafaelleru** [localstack/localstack#7501]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When creating a new EMR cluster I am getting this info log:

```
INFO --- [functhread17] l.services.emr.provider    : Unable to start up EMR cluster: Unable to find requested versionUnable to find requested version '2.4.8' for package 'Spark'
```

### Expected Behavior

EMR cluster to run successfully

### How are you starting LocalStack?

With a docker-compose file

```
  s3-aws:
    image: localstack/localstack-pro:latest  # required for Pro
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
      - "127.0.0.1:53:53"                # DNS config (required for Pro)
      - "127.0.0.1:53:53/udp"            # DNS config (required for Pro)
      - "127.0.0.1:443:443"              # LocalStack HTTPS Gateway (required for Pro)
    environment:
      - DEBUG=1
      #- PERSISTENCE=${PERSISTENCE-}
      - LAMBDA_EXECUTOR=docker
      - LOCALSTACK_API_KEY=<key>  # required for Pro
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      #- "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"


```

### Steps To Reproduce

* Start localstack
* Create an emr cluster

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```
aws --profile localstack --endpoint-url https://localhost.localstack.cloud:4566 emr create-cluster \                                                                                                  
    --region us-east-1 \
    --release-label emr-5.36.0 \
    --os-release-label 2.0.20220406.1 \
    --service-role EMR_DefaultRole \
    --ec2-attributes InstanceProfile=EMR_EC2_DefaultRole \
    --instance-groups InstanceGroupType=MASTER,InstanceCount=1,InstanceType=m4.large InstanceGroupType=CORE,InstanceCount=1,InstanceType=m4.large
```

### Environment

```markdown
- OS: Ubuntu 20.04
- LocalStack: latest
```

**Comment by whummer** [comment]
Hi @rafaelleru  , thanks for reporting. We have recently introduced some significant enhancements for EMR - in the latest version, we have introduced a mode to spin up the required utilities (Spark, Hive, Presto, etc) directly in the main LocalStack container, without creating a separate `bigdata` container. 

This new mode is behind a feature flag and can be activating by setting `BIGDATA_MONO_CONTAINER=1` in the environment (it will become the default in a future release). Can you please give that a try with the `latest` image and see if it resolves the issue you've been facing? 

Please keep us posted on how it goes.. Thanks for your help!

**Comment by whummer** [comment]
Hi @rafaelleru - another quick update. We have recently pushed a few more fixes. Can you please try again after pulling the `latest` LocalStack image, and using the `BIGDATA_MONO_CONTAINER=1` configuration? Thanks!

**Comment by whummer** [comment]
Closing as resolved. Please do let us know if the problem persists @rafaelleru - happy to re-open the issue and look into it in more detail in that case.. Thanks!
