### ISSUE TITLE
feature request: Implement list-crawls for AWS Glue

### ISSUE THREAD

**Issue by MarcelStranak** [localstack/localstack#7507]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Implement `list-crawls` for Glue service.

```bash
awslocal glue list-crawls --crawler-name "crawler1"
```

```bash
An error occurred (InternalFailure) when calling the ListCrawls operation: API action 'ListCrawls' for service 'glue' not yet implemented or pro feature - check https://docs.localstack.cloud/user-guide/aws/feature-coverage for further information
```

### Anything else?

Request coming from [customer ](https://localstack-community.slack.com/archives/C0366PZUBV4)

**Comment by uzaxirr** [comment]
Hey!
I have a approach in mind, if that's correct i'm happy to take this up

I need to make changes in the original [moto repo](https://github.com/getmoto/moto)

implement a `list_crawls` for the `GlueBackend` class In `moto/glue/models.py` 
Also implement `list_crawls` for the `GlueResponse` class In `moto/glue/response.py` 

Please correct me if i'm wrong

**Comment by MarcelStranak** [comment]
Implemented in the latest version of LocalStack. 
https://github.com/localstack/localstack-ext/pull/1325
