### ISSUE TITLE
bug: It is 2023.

### ISSUE THREAD

**Issue by QuinnyPig** [localstack/localstack#7515]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The copyright date is out of date now.

### Expected Behavior

I expected time to stop; it did not. 

### How are you starting LocalStack?

Custom (please describe below)

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    I begin by looking at the calendar and feeling a sense of unease.

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

      I then check the footer and begin grunting and pointing frantically, unable to communicate my discomfort in any way that could remotely be described as "articulate." 

### Environment

```markdown
- OS:
- LocalStack:
```

**Comment by whummer** [comment]
Thanks for reporting @QuinnyPig ! We'll get that fixed as soon as possible - unless you'd be willing to create a pull request with this change? 🙏 😄
