### ISSUE TITLE
bug: Error: requesting ACM Certificate (api-top.com): UnrecognizedClientException: The security token included in the request is invalid.

### ISSUE THREAD

**Issue by ze-ahmed** [localstack/localstack#7530]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello,

I'm creating an ACM Certificate (This tf works fine), I need to attach the certificate on an apigateway and having the following error
`│ Error: requesting ACM Certificate (api-vcert.fr): UnrecognizedClientException: The security token included in the request is invalid.
│ 	status code: 400,`

When removing the link between the certificate and the apigateway everything works 

`resource "aws_api_gateway_domain_name" "domain_name" {
  domain_name               = "api.${var.root_domain_name}"
  regional_certificate_name = "top-api"
  certificate_arn           = module.acm_module.vcert_certificate_ARN
  endpoint_configuration {
    types = ["REGIONAL"]
  }
}`

as soon as I remove the `certificate_arn` attribute it works but I need the link with the certificate 

Thanks for the analysis

### Expected Behavior

Certificate is linked to the apigateway via aws_api_gateway_domain_name resource 

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

   ` localstack start -d`

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    launch the creation: 
         `tflocal init`
          `tflocal validate`
          `tflocal apply --auto-approve`

### Environment

```markdown
- OS:Mac OS 13.1
- LocalStack: 1.3.1
```

**Comment by whummer** [comment]
Hi @ze-ahmed , thanks for reporting. Do you think you could share a copy of your Terraform script, or at least a minimal example that exposes this issue? This would be very helpful for us to replicate and resolve this issue.. Thanks for your help!

**Comment by ze-ahmed** [comment]
Hello @whummer 

Nothing confidential, I've reused scripts available on localstack github and updated them a little (available [here](https://github.com/ze-ahmed/acm-apigateway/tree/master))
Please note that if you execute the acm-route53 alone it works and if you execute the apigateway-custom-domain without the certificate_arn           = module.acm_module.vcert_certificate_ARN  on "aws_api_gateway_domain_name" it works also.

Thanks in advance

**Comment by ppetershagen** [comment]
I'm getting the same error while creating a certificate with [ latest localstack-pro ](https://hub.docker.com/layers/localstack/localstack-pro/latest/images/sha256-fb6f2ebad22a05f00ebfb1c271cb4e6b2c56da6a2d8f8d67c7ce95edc1235091?context=explore) , basically using very similar set up to @ze-ahmed using `tflocal init; tflocal apply`,

**Comment by czomo** [comment]
I always facing `UnrecognizedClientException: The security token included in the request is invalid` issue when I forget to specify endpoint for IAM/STS in my terraform provider. @ppetershagen Try this ⬇️ 

```
provider "aws" {
  region = var.region

  endpoints {
    iam = "http://localstack:4566"
    sts = "http://localstack:4566"
  }
}

```

**Comment by ppetershagen** [comment]
Thanks @czomo , just tested with latest `localstack-pro:2.0.2` but still getting the above mentioned error :( `tflocal plan` says its all green and wants to add the certificate, then `tflocal apply` fails. Any other thoughts?

**Comment by ppetershagen** [comment]
I got it working now, by just adding another endpoint definition for the acm subsystem:

```
  endpoints {
    iam = "http://localhost:4566"
    sts = "http://localhost:4566"
    route53 = "http://localhost:4566"
    acm = "http://localhost:4566"
  }
```

**Comment by alexrashed** [comment]
Hi @ze-ahmed, @czomo, and @ppetershagen.
Sorry for the late response. I just tried to reproduce the issue with the sample provided by @ppetershagen in https://github.com/localstack/localstack/issues/7530#issuecomment-1420193955. Thanks for providing the reproducible sample!
For me the terraform configuration can be applied just fine. The comment by @ppetershagen that the issue can be fixed by setting the endpoints indicates that ACM is not yet supported in the version of `tflocal` (or more concrete in `localstack-python-client`). Your issue should be resolved by updating `tflocal` and its dependencies to the latest version.
I'll close the issue for now. Please feel free to open a new issue if you are still experiencing any issues.
Thanks!
