### ISSUE TITLE
bug: boto3 client fails with "The security token included in the request is invalid" when invoked from asf lambda provider

### ISSUE THREAD

**Issue by dpretty** [localstack/localstack#7534]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When localstack is started with `PROVIDER_OVERRIDE_LAMBDA=asf` the credentials within a lambda function are invalid when calling a cognito-idp client.

The coginto api call executes successfully when `PROVIDER_OVERRIDE_LAMBDA=asf` is omitted.

### Expected Behavior

The same behaviour (successful boto3 api call) is expected for both lambda providers.

### How are you starting LocalStack?

With the `localstack` script

### Steps To Reproduce

A minimal example (using CDK)  is provided here: https://github.com/LaunchlabAU/LaunchlabAU-localstack-lambda-security-token-issue

Follow instructions in that repo's README to reproduce

### Environment

```markdown
- OS: MacOS 13.1
- LocalStack:


LocalStack version: 1.3.2.dev
LocalStack Docker container id: 21dea032071d
LocalStack build date: 2023-01-22
LocalStack build git hash: 9397fd82
```
```


### Anything else?

_No response_

**Comment by dpretty** [comment]
An update in case anyone else bumps into this issue: transparent endpoint injection isn't yet available with the asf lambda provider. The the workaround is to set `endpoint_url` explicitly.

e.g.

```
LOCALSTACK_HOSTNAME = os.environ.get("LOCALSTACK_HOSTNAME")
client = boto3.client(
      "cognito-idp", verify=False, endpoint_url=f"http://{LOCALSTACK_HOSTNAME}:4566"
 )

```

**Comment by dominikschubert** [comment]
Thanks for the update @dpretty 

Transparent endpoint injection is now also available in the new lambda implementation (`asf`/`v2`)  for python, nodejs, ruby and java runtimes when using LocalStack PRO.

Please let us know if you continue to experience any further issues with the latest version. Thanks!
