### ISSUE TITLE
feature request: RDS should use the appropriate MySQL/MariaDB container based on 'EngineVersion' value

### ISSUE THREAD

**Issue by snhardin** [localstack/localstack#7537]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Consider the following code:

```python
import boto3


rds_client = boto3.client("rds", endpoint_url=ENDPOINT_URL, region_name="us-east-1")

msg("Creating RDS cluster...")
rds_client.create_db_cluster(
    DBClusterIdentifier=RDS_DB_CLUSTER_IDENTIFIER,
    DatabaseName=RDS_DB_NAME,
    Engine="aurora-mysql",
    EngineVersion="5.7.mysql_aurora.2.10.2",
)
```

When executing this code to create an RDS cluster, Localstack will spin up a MariaDB 10 database to connect to. This poses a problem for me as most of my SQL is compatible only with MySQL 5.7. I've tried different EngineVersions, but they all seem to spin up a MariaDB 8 or 10 instance. It would be nice if I could get a MySQL 5.7 instance when specifying the Aurora engine.

I should note that even [specifying a version of MySQL directly](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_MySQL.html#MySQL.Concepts.VersionMgmt) results in a MariaDB instance with a version that doesn't match the specified version.

**Comment by steffyP** [comment]
Hi @snhardin, 

thanks for reaching out. We recently introduced a feature to support MySQL database as it was requested in issue #6782. 
The feature is available in the `latest` localstack-pro image and can be activated by setting the environment variable `RDS_MYSQL_DOCKER=1`.

When using the engine `mysql` or `aurora-mysql` it will spin up a MySQL database using the official images by MySQL in a new docker container. The `version` attribute can be used to specify the image-tag that will be used to spin up the MySQL container (which should correlate to the MySQL version). 

Please also [check our docs](https://docs.localstack.cloud/user-guide/aws/rds/#mysql-engine) for the details.

For MariaDB it is not currently not possible to select another version. However, from your use case it seems like you are primarily interested in MySQL anyhow?

Could you let us know if the feature works for you? 🙏

**Comment by snhardin** [comment]
Hey @steffyP!

I finally got around to testing this. Unfortunately, this still does not appear to be working. I am using the following terraform to spin up an RDS instance:

```terraform
resource "aws_db_instance" "default" {
  allocated_storage    = 10
  db_name              = "my_appl"
  engine               = "mysql"
  engine_version       = "5.7"
  instance_class       = "db.t3.micro"
  username             = "admin"
  password             = "****" # Placeholder. Is actually set to a real password in real terraform.
  parameter_group_name = "default.mysql5.7"
  skip_final_snapshot  = true
}
```

I have also tried the following `awslocal` command:

```bash
awslocal rds create-db-cluster --db-cluster-identifier db1 --engine mysql --database-name my_appl --engine-version 5.7
```

Both of these approaches still result in a MariaDB instance. Shall I reopen this issue?

**Comment by steffyP** [comment]
Hi @snhardin,
please check your Localstack image version, and make sure to run `docker pull localstack/localstack-pro:latest` if you are using the `latest` Localstack version.

Be aware that the default is still maria-db, and you have to activate the feature by setting the env `RDS_MYSQL_DOCKER=1` when starting Localstack. 

Please check the docs I have linked in my last post.
