### ISSUE TITLE
bug: AWS s3 is returning a different XML object than localstack does with the new Localstack s3 provider

### ISSUE THREAD

**Issue by daringordon** [localstack/localstack#7541]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

S3 requests to localstack are failing using aws clients written in various languages (Elixir, Rust).

I illustrate the crash in Elixir using the following executable example [HERE](https://github.com/Dowwie/localstack_s3_xml_issue)

If you wish to reproduce this problem with Rust, simply clone the official [aws-sdk-rust](https://github.com/awslabs/aws-sdk-rust) library and run `LOCALSTACK=true cargo run --bin use-localstack` from the root directory, after you've installed rust (using rustup).

as per @thrau :
> anyway i checked and can confirm AWS s3 is returning a different XML object than localstack with our new s3 provider.
by default, list-buckets returns a <ListAllMyBucketsResult> object (that is not defined in the spec actually - happens often in s3), but we return a <ListBucketsOutput> object (which is the default name in the spec). this is probably why the official aws sdks can handle the response. the parsed response is the same, it's just the container that's different (edited) 

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

see the README of the project I link to in the description above

### Environment

```markdown
- OS:  macos (m1)
- LocalStack:  latest
```

**Comment by Dowwie** [comment]
@macnev2013 I recommend checking every response for this disconnect, as I also experienced the same issue with `list_objects`
