### ISSUE TITLE
bug: Getting error when creating lambda function with dynamodb as event stream

### ISSUE THREAD

**Issue by ayeganyan** [localstack/localstack#7548]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Getting error when trying to attach dynamodb to lambda as an event source:
> 2023-01-19T15:20:52.121 ERROR --- [functhread28] l.s.a.e.stream_event_sourc : 'StartingPosition'
> Traceback (most recent call last):
>   File "/opt/code/localstack/localstack/services/awslambda/event_source_listeners/stream_event_source_listener.py", line 345, in _monitor_stream_event_sources
>     source["StartingPosition"],
> KeyError: 'StartingPosition'

This worked fine on localstack:0.14.5

### How are you starting LocalStack?

With a `docker run` command

### Steps To Reproduce

* Run localstack:
> docker run --rm -d -v /Users/ayeganyan/workspace/sandbox/lambda-nodejs/artifacts:/artifacts -p 4566 -e PROVIDER_OVERRIDE_LAMBDA=asf -v "/var/run/docker.sock:/var/run/docker.sock:rw" localstack/localstack

* ssh to running localstack

* Executes the following commands, which basically creates lambda (provide anything as code and runtime), and dynamodb
> awslocal dynamodb create-table --table-name dx-ref-java-quarkus-im-lambda-ddb --attribute-definitions AttributeName=key,AttributeType=S --key-schema AttributeName=key,KeyType=HASH --billing-mode PAY_PER_REQUEST --stream-specification StreamEnabled=true,StreamViewType=NEW_AND_OLD_IMAGES
> export DYNAMO_DX_REF_JAVA_QUARKUS_IM_LAMBDA_DDB_STREAM_ARN=$(awslocal dynamodb describe-table --table-name dx-ref-java-quarkus-im-lambda-ddb --query 'Table.LatestStreamArn' --output text)
> awslocal lambda create-function --function-name ddblambda --role arn:aws:iam::000000000000:role/DummyRole --runtime python3.8 --handler python.main.handle --zip-file fileb:///artifacts/python.zip --memory-size 1024 --timeout 20 --environment '{"Variables": {"OUT_QUEUE_NAME": "dx-ref-java-quarkus-im-lambda-ddb-out"}}'

* Add event source:
> awslocal lambda create-event-source-mapping --function-name "ddblambda" --event-source-arn "$DYNAMO_DX_REF_JAVA_QUARKUS_IM_LAMBDA_DDB_STREAM_ARN"

Then you will see the following error (continuously):
> 2023-01-19T15:20:52.121 ERROR --- [functhread28] l.s.a.e.stream_event_sourc : 'StartingPosition'
> Traceback (most recent call last):
>   File "/opt/code/localstack/localstack/services/awslambda/event_source_listeners/stream_event_source_listener.py", line 345, in _monitor_stream_event_sources
>     source["StartingPosition"],
> KeyError: 'StartingPosition'

### Environment

```markdown
- OS: MacOS Ventura 13.1
- LocalStack: latest
```

**Comment by ayeganyan** [comment]
Hello, We are still on 0.14.5 and this bug will prevent us for upgrading to the next version, can someone provide an update whether this will be fixed in the next release, or not?

**Comment by pinzon** [comment]
Hi @ayeganyan we the old lambda provider we didn't really use the StartingPosition parameter, but the new ASF provider does. Sadly most of the parameters validations need to be implemented yet, we could lead into problems like yours. With PR #7696 the lambda api will correctly throw a ValildationException like it should.

**Comment by pinzon** [comment]
We've updated to the new ASF provider and now require the StartingPosition parameter. However, some parameter validations are missing, which could cause issues. We've submitted a pull request (#7696) to fix this.
