### ISSUE TITLE
"DeliveryStreamType: KinesisStreamAsSource" not supported

### ISSUE THREAD

**Issue by ewaltman** [localstack/localstack#755]
Looking at https://github.com/localstack/localstack/blob/master/localstack/services/firehose/firehose_api.py#L166, it appears that `DeliveryStreamType` is not supported when creating an AWS Firehose Delivery Stream. I'd love to see this feature or find out if there's something I'm missing.

**Comment by portenez** [comment]
Yeah, so you cannot follow a stream via firehose. Or are we missing something?

**Comment by whummer** [comment]
Thanks for reporting @ewaltman @portenez . This issue has been fixed in the meantime - an integration test has been added here: https://github.com/localstack/localstack/blob/0181a1fc056b7538547d5f43f6b6d21bb126286a/tests/integration/test_integration.py#L119-L131
