### ISSUE TITLE
bug: Cognito API Unreachable

### ISSUE THREAD

**Issue by corinz** [localstack/localstack#7553]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am following the Cognito Localstack instructions to create a Cognito pool, client, and user. I follow the instructions for accessing the Cognito UI to login. I am able to login when my pod is port forwarded to localhost:4566 and I reach the /login endpoint with embedded Cognito parameters. The issue is that I am unable to login when Localstack is executing in my cluster and I am routing traffic through an Ingress. Strangely, I am able to resolve the UI, but when I click "Sign In" a pop-up says 
```
Unable to initiate authentication via Cognito API: NetworkingError: Network Failure
```
*There are no logs whatsoever produced in the Localstack pod when this error occurs.*

But when I request the Cognito page in the first place (before attempting to Sign In), I can see (with trace logging) that Localstack is sending a js page that includes the environment variable `COGNITO_IDP_URL = \'http://localhost:4566/\'` which is inaccurate since Localstack is not at localhost:4566, it is actually at my ingress address `aws.local`. I believe the root cause of the issue is the inability to resolve localhost:4566. As I mentioned above, when I port-forward the pod to localhost:4566, this issue goes away and the Sign In works.

### Expected Behavior

Sign In would be able to resolve the Localstack endpoint and sign in works.

### How are you starting LocalStack?

Custom (please describe below)

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

Official Helm Chart here is my values.yaml. There are a lot of parameters I injected for debugging purposes like `AWS_REGION`
```
image:
  tag: '1.3.1'
  pullPolicy: IfNotPresent
volumes:
  - name: init-scripts
    # Mounted by kind.yaml
    hostPath:
      path: /localstack/init-scripts
volumeMounts:
  - name: init-scripts
    mountPath: /etc/localstack/init/ready.d
    readOnly: true
ingress:
  enabled: true
  hosts:
    - host: aws.local
      paths:
        - path: /
          pathType: ImplementationSpecific
extraEnvVars:
  - name: DISABLE_EVENTS
    value: "1"
  - name: DNS_ADDRESS
    value: "0"
  - name: PROVIDER_OVERRIDE_S3
    value: asf
  - name: DISABLE_CORS_CHECKS
    value: "1"
  - name: LOCALSTACK_API_KEY
    value: *******             <-- redacted
  - name: AWS_REGION
    value: us-east-1
  - name: AWS_DEFAULT_REGION
    value: us-east-1
  - name: EXTRA_CORS_ALLOWED_ORIGINS
    value: http://app.mycomany.local
  - name: HOSTNAME_EXTERNAL
    value: aws.mycomany.local
  - name: LOCALSTACK_HOSTNAME
    value: aws.mycomany.local
  - name: COGNITO_IDP_URL
    value: aws.mycomany.local
  # Debug Trace Mode
  - name: LS_LOG
    value: trace
  - name: DEBUG
    value: "1"
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)
I am following these instructions exactly: https://docs.localstack.cloud/user-guide/aws/cognito/

```
#!/bin/sh
pool_id=$(awslocal cognito-idp create-user-pool --pool-name test | jq -rc ".UserPool.Id")
client_id=$(awslocal cognito-idp create-user-pool-client --user-pool-id $pool_id --client-name test-client | jq -rc ".UserPoolClient.ClientId")
awslocal cognito-idp sign-up --client-id $client_id --username admin --password Admin123! --user-attributes Name=email,Value=redacted@redacted.com
```
I then confirm the user manually with the confirmation code according to the docs.

### Environment

```markdown
- OS: Mac 12.5
- LocalStack: 1.3.1
```

### Anything else?

This is part of a bid to implement Localstack at my company where Cognito is required. I appreciate any prompt responses and I will return likewise in order to come to a resolution. Much appreciated, thank you all!

**Comment by whummer** [comment]
Hi @corinz , thanks for reporting, and apologies for the delayed response. As you mentioned, seems like we have an incorrect configuration for `COGNITO_IDP_URL` when opening the Cognito login page in a non-localhost enpoint. Just to confirm - what is the URL that you're using to open the Cognito login page, is it `http://aws.local:4566/login`? 

We'll probably need to add an override to make the request directly to that same domain name (where the UI is being accessed), instead of hardcoding `localhost:4566`. Should be doable - we'll try to push out a fix shortly.. 👍  Thanks!

**Comment by whummer** [comment]
Hi again @corinz , quick update - we have now pushed a few enhancements for the Cognito login UI, which should enable you to run the signup/signin commands against a remote (non-localhost) instance. Can you please pull the `latest` Docker image and give it another try? Please keep us posted on how it goes.. Thanks!

**Comment by corinz** [comment]
If it doesn't do Implicit Auth flow or response_type=token, I'll need to run Auth Code, which means I need the well-known openid config usually located at `<issuer_url>/<pool_id>/.well-known/jwks.json` but I don't see this endpoint available. @whummer Let me know how to proceed.

**Comment by whummer** [comment]
Thanks @corinz , can you please share a few screenshots of your browser, also the Network and Console tabs in the developer tools view. Thanks

> Are there any settings to change to indicate localstack is running behind a reverse proxy ? Can I now set COGNITO_IDP_URL?

The way it works now that the browser should make a request to `location.origin` directly (via JS), so as the base URL it should be using `http://aws.mycompany.local/` in your case. Can you confirm that this is the case when opening the Network tab in the browser developer tools?

**Comment by corinz** [comment]
@whummer I think the issue is that I am trying to do an implicit auth flow i.e. `response_type=token`. Does Localstack support Implicit?
