### ISSUE TITLE
Localstack S3 emulation does not check precondition headers for CopyObject operation

### ISSUE THREAD

**Issue by rlauer6** [localstack/localstack#7555]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

CopyObject API does not check precondition headers such as `x-amz-copy-source-if-modified-since`. Instead it seems to always copy the object.

### Expected Behavior

The API should return a 412 response with content similar to:

```
<Error><Code>PreconditionFailed</Code><Message>At least one of the pre-conditions you specified did not hold</Message><Condition>x-amz-copy-source-If-Modified-Since</Condition><RequestId>14HR9PXJRG5B1GR5</RequestId><HostId>HztBs2jYea1fzzPWo1JWy33NQJqo1S1IsK62rkbnVEI04PnGNCi8sPVrichGQxH3FQwLA2RIyF4=</HostId></Error>
```

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```
aws s3  --profile localstack --endpoint-url http://s3.localhost.localstack.cloud:4566 \
  ls s3://net-amazon-s3-test/Makefile.am
2023-01-25 10:47:40        537 Makefile.am

aws s3api copy-object --copy-source net-amazon-s3-test/Makefile.am --key Makefile.am.2 \
  --bucket net-amazon-s3-test2 --profile localstack --endpoint-url http://s3.localhost.localstack.cloud:4566 \
  --copy-source-if-modified-since "Wed, 25 Jan 2023 16:16:27 GMT"
{
    "CopyObjectResult": {
        "ETag": "\"46ada9d1fe8f8a311ff4504c226e061c\"",
        "LastModified": "2023-01-25T16:18:43+00:00"
    }
}
```

### Environment

```markdown
- OS: penguin
- LocalStack: latest
```

**Comment by thrau** [comment]
looks like moto doesn't have that feature, but we could add it by implementing pre-condition checking in our new provider here: https://github.com/localstack/localstack/blob/e8a7f54e012b513a1ac2b31f90ee01f86fd87731/localstack/services/s3/provider.py#L386-L396 

cc @bentsku @macnev2013 

also this actually looks like a good first issue :-)

**Comment by shivanii1702** [comment]
hey Thrau, I want to work on this issue, It would be great if I get some guidance from your side.

**Comment by bhanuunrivalled** [comment]
> looks like moto doesn't have that feature, but we could add it by implementing pre-condition checking in our new provider here:
> 
> https://github.com/localstack/localstack/blob/e8a7f54e012b513a1ac2b31f90ee01f86fd87731/localstack/services/s3/provider.py#L386-L396
> 
> cc @bentsku @macnev2013
> 
> also this actually looks like a good first issue :-)

HI @thrau 

do you mean some thing like this?

I tried to see some precondition checks in s3 provider but could fine


please let me know if this basic idea is correct 

```
 @handler("CopyObject", expand=False)
    def copy_object(
        self,
        context: RequestContext,
        request: CopyObjectRequest,
    ) -> CopyObjectOutput:
        if not config.S3_SKIP_KMS_KEY_VALIDATION and (sse_kms_key_id := request.get("SSEKMSKeyId")):
            moto_backend = get_moto_s3_backend(context)
            bucket = get_bucket_from_moto(moto_backend, bucket=request["Bucket"])
            validate_kms_key_id(sse_kms_key_id, bucket)

        response: CopyObjectOutput = call_moto(context)
        **last_modified = response.CopyObjectResult.LastModified
        if_modified_since = context.request.headers.get("x-amz-copy-source-if-modified-since")
        if if_modified_since:
            if_modified_since = parse_rfc822(if_modified_since)
            if if_modified_since >= last_modified:
                raise PreconditionFailed("The copy source has been modified since the specified time")**
        self._notify(context)
        return response

```

could you please throw some light in to this?

**Comment by ashish1500616** [comment]
@bhanuunrivalled 

In my understanding, the function call_moto(context) appears to be forwarding the copy object request to the backend. However, it seems necessary to perform precondition checks prior to dispatching the request to the moto backend.

@thrau @bentsku @macnev2013 Please take a look at the changes and let me know what you think? 

```python
    @handler("CopyObject", expand=False)
    def copy_object(
        self,
        context: RequestContext,
        request: CopyObjectRequest,
    ) -> CopyObjectOutput:
        moto_backend = get_moto_s3_backend(context)
        bucket = get_bucket_from_moto(moto_backend, bucket=request["Bucket"])
        if not config.S3_SKIP_KMS_KEY_VALIDATION and (sse_kms_key_id := request.get("SSEKMSKeyId")):
            validate_kms_key_id(sse_kms_key_id, bucket)
        source_bucket, source_key = os.path.split(request["CopySource"])
        source_bucket = get_bucket_from_moto(moto_backend, bucket=source_bucket)
        source_key = get_key_from_moto_bucket(source_bucket, key=source_key)
        source_object = moto_backend.get_object(source_bucket.name, source_key.name)
        source_object_last_modified = str_to_rfc_1123_datetime(source_object.last_modified_RFC1123)
        condition = None
        if request["CopySourceIfModifiedSince"]:
            precondition_check_date_time = str_to_rfc_1123_datetime(
                rfc_1123_datetime(request["CopySourceIfModifiedSince"])
            )
            if source_object_last_modified <= precondition_check_date_time:
                condition = "CopySourceIfModifiedSince"
        elif request["CopySourceIfUnmodifiedSince"]:
            precondition_check_date_time = str_to_rfc_1123_datetime(
                rfc_1123_datetime(request["CopySourceIfUnmodifiedSince"])
            )
            if source_object_last_modified > precondition_check_date_time:
                condition = "CopySourceIfUnmodifiedSince"
        elif request["CopySourceIfMatch"]:
            if source_object.etag and source_object.etag.strip('"') != request[
                "CopySourceIfMatch"
            ].strip('"'):
                condition = "CopySourceIfMatch"
        elif request["CopySourceIfNoneMatch"]:
            if source_object.etag and source_object.etag.strip('"') != request[
                "CopySourceIfNoneMatch"
            ].strip('"'):
                condition = "CopySourceIfNoneMatch"
        if condition:
            LOG.info("Precondition failed: %s", condition)
            raise PreconditionFailed(
                "At least one of the pre-conditions you specified did not hold.",
                Condition=condition,
            )
        else:
            response: CopyObjectOutput = call_moto(context)
        self._notify(context)
        return response
```

**Comment by bentsku** [comment]
Hi @ashish1500616! Sorry for the delay, I missed the mention.

This looks pretty good already, the best would be to open a pull request and add some AWS validated tests going with it, and I'd be glad to shepherd that PR and get it merged! For example, I think stripping the `"` from the ETag might not be necessary if we follow AWS behaviour, but I'm not certain, and some AWS validated tests would help us there.

You can find our guide for contributing and writing integration tests here: https://docs.localstack.cloud/contributing/integration-tests/ and https://docs.localstack.cloud/contributing/parity-testing/

Thanks again!

**Comment by ashish1500616** [comment]
Hi @bentsku,

Thanks for the feedback and the suggestion.
I will definitely take a look at the links you provided and see how I can integrate those tests into the code.

Thanks again for your time and feedback!
