### ISSUE TITLE
EventBridge PutTargets does not check the syntax of target IDs.

### ISSUE THREAD

**Issue by wunderbarb** [localstack/localstack#7567]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

For instance providing a target ID such as the ARN of a SQS queue is accepted by localstack.  In real, the ID must follow regex [a-z0-9.-_]+ and be less than 64 characters.

### Expected Behavior

Issue an error message

### How are you starting LocalStack?

With a `docker run` command

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack-pro

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)
```golang
...
pti := &eventbridge.PutTargetsInput{
		Rule: aws.String(ruleName),
		Targets: []types2.Target{
			{
				Arn: aws.String(q.GetARN()),
				Id:  aws.String(ruleName + q.GetARN()),
			},
		},
		EventBusName: nil,
	}
	_, err = c.PutTargets(context.Background(), pti)
```

### Environment

```markdown
- OS: Ubuntu 20.04
- LocalStack: localstack-pro: latest
```

**Comment by Datashri** [comment]
please give me access to this bug.
I have an idea to solve this.
