### ISSUE TITLE
AppSync support

### ISSUE THREAD

**Issue by iartarisi** [localstack/localstack#757]
Hi, are there any plans for AppSync support? Queries, Mutations, Subscriptions might be a nice place to start. 

I'd be interested in contributing, too.

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-306) by [Unito](https://www.unito.io/learn-more)

**Comment by deadcoder0904** [comment]
AWS AppSync is a complete game changer. I would love to have this too :)

**Comment by lightsofapollo** [comment]
For anyone using appsync we're actively working on an emulator solution (initially for us to use) : https://github.com/ConduitVC/aws-utils/tree/master/packages/appsync-emulator-serverless .

It's early but we're interested in collecting feedback on any use cases that would be interesting for others.

**Comment by deadcoder0904** [comment]
Once its ready, why not incorporate that into `localstack` so 1 tool to rule them all

Bdw @lightsofapollo any ETA on AppSync Emulator 1.0❓

**Comment by lightsofapollo** [comment]
@deadcoder0904 Not sure about an official `1.0` but we're actively building applications on top of the emulator . Once one has shipped (August) then I think we can consider the emulator "stable" right now it's migrated into a "beta" condition (aka works on a few humans machines :D)

**Comment by patrickkempff** [comment]
Any updates on AppSync support? We are looking into the possibilities of localstack and AppSync is something we would like to use.

**Comment by asavage** [comment]
According to the [GitHub page](https://github.com/localstack/localstack) Appsync is supported.  However [the pro sample for appsync](https://github.com/localstack/localstack-pro-samples/tree/master/appsync-graphql-api) does not work.  It appears from the error message that a basic dynamodb getitem is not supported:

`{
    "errors": [
        "Unsupported AppSync DynamoDB template operation \"GetItem\"\n\nGraphQL request:2:7\n1 |     query  {\n2 |       getPostDDB (id: \"id1234\")\n  |       ^\n3 |             {"
    ]
}`

**Comment by mihow** [comment]
@asavage Were you able to get Appsync working with the pro version of localstack?

**Comment by theBenForce** [comment]
@mihow I'm trying to get it to work now and I'm just getting a bunch of errors.

**Comment by thrau** [comment]
closing this issue for now. if you still have problems with appsync, please create issues with the specific problem so we can better track and triage them.
