### ISSUE TITLE
bug: DynamoDB resolver mapping results to `$context.result` not `$context.result.items`

### ISSUE THREAD

**Issue by lashd** [localstack/localstack#7579]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The [AWS docs](https://docs.aws.amazon.com/appsync/latest/devguide/resolver-mapping-template-reference-dynamodb.html#query-list) state that results returned by DynamoDB should be available under `$context.result.items`. Results appear to be directly under `$context.result`

### Expected Behavior

Mapped results from DynamoDB should be under `$context.result.item`

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

I've forked the [localstack/localstack-pro-samples](https://github.com/localstack/localstack-pro-samples) repo and have modified the `appsync-graphql-api` example to demonstrate this.

To use it

1. Clone [repo](git@github.com:lashd/localstack-pro-samples.git) in to a remote container volume using VSCode
2. Add your `LOCALSTACK_API_KEY` to `.devcontainer/docker-compose.yml`
3. Use VScode to rebuild the container and use the `LOCALSTACK_API_KEY`
4. `cd appsync-graphql-api`
5. `make install`
6. `make run`
7. Observe console output showing the data that was used to render the the response.

The above steps result in a query being made to DynamoDB for which `./appsync-graphql-api/templates/ddb.Scan.response.vlt` is used to render the results as JSON. It uses `$context.result` not `$context.result.items` the content of which can be seen in the localstack container logs, which `make run` prints out.

### Environment

```markdown
- OS: Using published docker container
- LocalStack: latest
```

### Anything else?
Thanks for your help! LocalStack is great

_No response_

**Comment by silv-io** [comment]
Hi @lashd, we implemented a fix for this issue which will arrive soon in the latest Docker image. We'll notify you when it is ready.

**Comment by lashd** [comment]
Thanks @silv-io, let me know when it's available and I'll give a go. Very grateful for your help, this fix will help a lot.

**Comment by silv-io** [comment]
Hi @lashd, it should be in the `latest` image now. Can you check if it works for you?

**Comment by darbinyanbabken** [comment]
@silv-io I am having the same issue with Scan operation on DynamoDB + VTL. Using latest localstack/localstack-pro image

**Comment by radmanz** [comment]
+1 👍

**Comment by hieudv91** [comment]
+1 👍

**Comment by simonrw** [comment]
Hi, we believe this issue should be fixed now with the latest image. It has been fixed since late October. Sorry for the delay in posting this update. I will close this issue for now, but feel free to re-open it if you continue to experience any issues.
