### ISSUE TITLE
`perm = 0 >> 16` equates to "a-rwx" on OSX. Is the intended behaviour?

### ISSUE THREAD

**Issue by alanjds** [localstack/localstack#758]
On Lambda deployment via serverless, the cloudstack is changing the files permissions to "a-rwx". This leads to "Permission Denied" errors later.

I am testing on OSX, but is this right on any OS anyway?

https://github.com/localstack/localstack/blob/debb24a792a7e2a1751ddf1f30d5c79f80b4885f/localstack/utils/common.py#L513

**Comment by alanjds** [comment]
PR that fixes it: #759

**Comment by whummer** [comment]
Thanks!
