### ISSUE TITLE
bug: PreTokenGeneration trigger does not override cognito:groups as expected

### ISSUE THREAD

**Issue by romuaa** [localstack/localstack#7581]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When overriding Cognito groups with PreTokenGeneration trigger the groups are not assigned to te user as expected

```
group_config = event['request']['groupConfiguration']
event['response'] = {
        "claimsOverrideDetails": {
            "groupOverrideDetails": {
                "groupsToOverride": ['GROUP_1', 'GROUP_2'],
                "iamRolesToOverride": group_config['iamRolesToOverride'],
                "preferredRole": group_config['preferredRole']
            }
        }
    }
```

### Expected Behavior

When PreTokenGeneration trigger overrides the user group information the user gets assigned to the groups and appsync schema directives can be used for authorisation using those groups. Also the groups are shown in the lambda event payload.

`  'groups': [
      'eu-west-1_werwerwer',
      'GROUP_1',
      'GROUP_2'
    ],`

### How are you starting LocalStack?

Custom (please describe below)

### Steps To Reproduce

cd backend && EXTRA_CORS_ALLOWED_ORIGINS=* LAMBDA_MOUNT_CWD=$(pwd) serverless deploy -c serverless.local.yml --stage local

Set up a PreTokenGeneration trigger
- override the groups by returning the correct payload in the trgger event response attribute
Set up appsync & GraphQL schema using app synch rectives for authorising user with overridden groups
Set up lambda that is protected by those app sync directives
Call the lambda through appsync and log the lambda event payload

### Environment

```markdown
- OS: MacOs Ventura
- LocalStack: 1.3.1
localstack/localstack-pro              latest      b1fdedd34828   20 hours ago   1.87GB
localstack/localstack                  latest      5f8634a35f24   20 hours ago   1.87GB
localstack/localstack-docker-desktop   0.3.1       6bad91e0ac0c   2 weeks ago    16.7MB
localstack/lambda                      python3.9   32338420b623   7 months ago   499MB
```

**Comment by whummer** [comment]
Hi @romuaa , thanks for reporting. We have pushed a few changes which should enhance the parity of the `groups` attribute in Cognito token claims (applying the overrides from `groupOverrideDetails`). 

When you get a chance, can you please pull the `latest` Docker image and give it another try? Please keep us posted on how it goes.. Thanks!

**Comment by romuaa** [comment]
Thank You! I can confirm that the groupOverrideDetails now work as expected with the PreTokenGeneration trigger and the groups overridden can be used to authorise the user with appSync directives.

However the PreTokenTrigger does not receive all the needed user information in the event that is needed for building the groupOverrideDetails.

Please find below the PreTokenGeneration trigger event that we receive when executing in live AWS environment (We are especially interested in the custom:groups)

`{
  'version': '1',
  'triggerSource': 'TokenGeneration_RefreshTokens',
  'region': 'eu-west-1',
  'userPoolId': 'eu-west-1_blah',
  'userName': 'aad_blah@example.com',
  'callerContext': {
    'awsSdkVersion': 'aws-sdk-unknown-unknown',
    'clientId': 'blah'
  },
  'request': {
    'userAttributes': {
      'sub': 'blah',
      'cognito:user_status': 'EXTERNAL_PROVIDER',
      'identities': '[{"userId":"aad_blah@example.com","providerName":"AAD","providerType":"SAML","issuer":"wefwefw","primary":true,"dateCreated":1673593079329}]',
      'email_verified': 'false',
      'name': 'Blah Blah',
      'custom:user_organisation': 'FooBar',
      'given_name': 'Blah',
      'family_name': 'Blah',
      'email': 'blah.blah@foobar.com',
      'custom:groups': '[DEV_GROUP_1, DEV_GROUP_2]'
    },
    'groupConfiguration': {
      'groupsToOverride': [
        'eu-west-1_blah_AAD'
      ],
      'iamRolesToOverride': [],
      'preferredRole': None
    }
  },
  'response': {
    'claimsOverrideDetails': None
  }
}`

Please find below the PreTokenGeneration trigger event that we receive when running with localstack (most of the userAttributes are missing):

`{
  'version': '$LATEST',
  'triggerSource': 'TokenGeneration_Authentication',
  'region': 'us-east-1',
  'userPoolId': 'us-east-1_4819e0e5ddb84714befd2d140a80b8ef',
  'callerContext': {
    'awsSdkVersion': 'aws-sdk-unknown-unknown',
    'clientId': 'xqxkjz0wit1znjvep133tk9rvt'
  },
  'request': {
    'userAttributes': {
      'sub': '4c0ce6e1-4885-40bd-8446-f7e00ecee9da',
      'cognito:user_status': 'CONFIRMED'
    },
    'groupConfiguration': {
      'groupsToOverride': [],
      'iamRolesToOverride': [],
      'preferredRole': None
    }
  },
  'response': {
    'claimsOverrideDetails': None
  },
  'userName': 'testuser'
}`

**Comment by whummer** [comment]
Hi @romuaa , thanks for the update and apologies for the delay. We've pushed a couple more enhancements for Cognito triggers in the meantime - can you please let us know if the problem still persists in the `latest` image? Thanks for your help! 🙌

**Comment by romuaa** [comment]
Yes, Thank you. This issue was resolved already together with the LocalStack Pro support. I just tested with the most recent image and works as expected (still). Will close the issue. Thank you again.
