### ISSUE TITLE
Problem with init hooks

### ISSUE THREAD

**Issue by luistmbraga** [localstack/localstack#7596]
I used this example (https://docs.localstack.cloud/references/init-hooks/)

```
version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"
    environment:
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/path/to/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh"  # ready hook
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock" 
```

But I keep getting 

```
ERROR --- [  MainThread] localstack.runtime.init    : Error while running script Script(path='/etc/localstack/init/ready.d/01-profile-creation.sh', stage=READY, state=ERROR): [Errno 13] Permission denied: '/etc/localstack/init/ready.d/01-profile-creation.sh'
```

**Comment by thrau** [comment]
hi @luistmbraga, i moved the issue to the localstack repository. 

sometimes this error appears if init scripts aren't executable. does the problem persist if you run `chmod +x /path/to/init-aws.sh`?

if yes, could you tell us a bit more about your setup? what operating system are you using, and what localstack version are you using?

**Comment by prinal10** [comment]
I facing the same issue. I'm using **MAC M1 PRO** machine and using locakstack with testcontainers confiugration. The `init-aws.sh` file exists on the localstack container in the specified path `/etc/localstack/init/ready.d/init-aws.sh` and i also ran the `chmod` command on file. But im getting permission denied error in container logs.

**Comment by luistmbraga** [comment]
I'm using the exact same machine.

**Comment by luistmbraga** [comment]
Hi @thrau ! 
Meanwhile, I managed to do what I wanted. Creating the resources using a aws-cli container that creates the resources on localstack.
I'm using a mac m1 pro with monterey. I'm using localstack:1.3.1
Are you saying to run `chmod +x /path/to/init-aws.sh` on the host machine right ?

**Comment by thrau** [comment]
Hey @luistmbraga glad you found a solution.
Yes, running that on the host should make it work.

We tested it internally on Mac M1 with this script, and it seems to work fine:

```bash
#!/usr/bin/env bash

set -euo pipefail

awslocal s3 mb s3://foo
```

**Comment by luistmbraga** [comment]
Nice !! Thank you for investigating this @thrau !

**Comment by luistmbraga** [comment]
And, by the way, localstack is a great solution !!

**Comment by whummer** [comment]
Great that it's working, thanks for confirming @luistmbraga . Please do let us know if there are any other issues.. Thanks!

**Comment by EvanGranthamBrown** [comment]
For anyone else running into this issue, the problem arises due to this bit in docker-compose:

    volumes:
      - "/path/to/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh"  # ready hook

The container can't manage permissions on a mapped volume; since the mapped volume is actually a directory on the host, the container has to live by whatever permissions the host has set. That's why running chmod -x on the host fixes it, but running the same command inside the container does not.

I didn't like that solution, because the whole point of Docker is to be portable. You shouldn't have to run a special command on your host before your Docker setup works. What I came up with was to remove the mapped volume entirely, and replace the line

    image: localstack/localstack

with

    build: ./docker/aws

Then I put the following in `./docker/aws/Dockerfile`:

    FROM localstack/localstack
    COPY --chown=localstack /path/to/init-aws.sh /etc/localstack/init/ready.d/init-aws.sh

Presto, everything works and you don't have to mess around with permissions on the host.

**Comment by ipsi-apant** [comment]
If anyone facing the same issue on Windows machine, then verify EOL setting for .sh file. Open the `init.sh` file in an editor (Example: VS Code) and set the EOL as LF. Might need to verify EOL for this file after reboot or OS update.

**Comment by hkecho** [comment]
![image](https://github.com/user-attachments/assets/b29ad36c-ae1e-4793-a648-2f1025a23c52)
Still met the issue, don't know why, the init_aws.sh works when I manually executed it in container of localstack, could someone help?
