### ISSUE TITLE
Lambda create function does not work on AWS Linux ec2 instance

### ISSUE THREAD

**Issue by rpanigra18** [localstack/localstack#7603]
Localstack lambda create function does not work on AWS linux ami.

Steps to recreate,

I have two terminal open on the linux instance. One one terminal, i spin up localstack using docker-compose. On the other terminal, i run my commands to create service, Interestingly, SSM put/get parameters work. So does lambda list-functions, it returns me an emty array since there are no lambdas. However, when I run the create function, I dont even see the request hitting the localstack container.

My docker compose for reference.

```
version: '3.8'

services: 
  localstack:
    image: localstack/localstack:latest
    environment: 
      - AWS_REGION=us-east-1
      - USE_SINGLE_REGION=1
      - DEFAULT_REGION=us-east-1
      - SERVICES=${SERVICES-lambda,s3,ssm}
      - DEBUG=1
      - DATA_DIR=${DATA_DIR-}
      - PORT_WEB_UI=${PORT_WEB_UI-}
      - PROVIDER_OVERRIDE_LAMBDA=asf
      - LAMBDA_EXECUTOR=local
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY-}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LAMBDA_DOCKER_NETWORK=kiosk-automation-aws-functional-tests_default
      - HOST_TMP_FOLDER=${TMPDIR}
      - EDGE_PORT=4566
      - SERVICES=lambda,s3,cloudformation,sts,ssm
      
    ports: 
      - '4566-4597:4566-4597'
    volumes: 
      - "${TEMPDIR:-/tmp/localstack}:/temp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```
      
      
      Terminal 1 - Adding/updating service
![image](https://user-images.githubusercontent.com/46056069/216445773-bafe0404-df48-498d-b898-cb267da70497.png)

Terminal 2 - watching the container logs
![image](https://user-images.githubusercontent.com/46056069/216445880-b2b6242c-47cf-4663-bac7-1870b8b09b26.png)

**Comment by dfangl** [comment]
Hi there! 
You have a lot of environment variables set. Can you try starting fresh with the docker-compose.yml here: https://github.com/localstack/localstack/blob/master/docker-compose.yml , and just set the `PROVIDER_OVERRIDE_LAMBDA=asf`.
Please also provide `DEBUG=1` and `LS_LOG=trace` and send the logs again of the create function call - something seems to go wrong there.

**Comment by rpanigra18** [comment]
Thanks for quick response, @dfangl 
I updated my docker-compose per your suggestion however I lambda create function still doesn't work. 

version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=${DEBUG-}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - PROVIDER_OVERRIDE_LAMBDA=asf
      - DEBUG=1
      - LS_LOG=trace
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

create function
![image](https://user-images.githubusercontent.com/46056069/216476092-ea75c73e-d0bc-44a4-825c-edf6a009d2b4.png)

logs

![image](https://user-images.githubusercontent.com/46056069/216475871-4eab2b82-af29-4518-b7a4-ff9b1c192a58.png)


If you notice, the list function still works but lambda create does not even make it to the logs.

**Comment by dfangl** [comment]
According to the logs, the request does not even seem to hit LocalStack's edge.
Can you try setting the debug flag `--debug` right after `aws`, to see what the CLI does in this case, and send the logs?

**Comment by rpanigra18** [comment]
Exactly, I agree. That is what I am trying to report in this Issue.

Per your suggestion, this is my updated cli

 aws --debug --endpoint-url=http://localhost:4566 lambda create-function --function-name ComcastInitPayment --runtime java11 --handler csg.kiosk.payment.comcast.initiatepayment.function.InitiatePaymentFunction --role arn:aws:iam::123456722222:role/ComcastInitPaymentFunction --zip-file fileb://comcast-init-payment.zip --environment file://variables.json --region us-east-1 --timeout 30

I also tried to append --memory 512 (with or without) I still get error, however, slightly different concerning memory. 


![image](https://user-images.githubusercontent.com/46056069/216485600-5476f0c6-ea07-4973-962f-b6579d90301b.png)
![image](https://user-images.githubusercontent.com/46056069/216485722-abf00673-9d48-4460-a9c3-8f212b6dcec1.png)

**Comment by dfangl** [comment]
This might be related to a read only filesystem on the EC2 instance, is this possible?
This seems related: https://github.com/aws/aws-cli/issues/5047 
Can you try setting TMPDIR to a rw filesystem or follow the other instructions in that thread?

**Comment by rpanigra18** [comment]
Hi , I tried several things, but no luck. I spent couple of hours in following workarounds from other thread, could you please provide me a way to implement TMPDIR with RW mode ? 
Also, Not sure if its a clue - just looking at the error message from other thread, even though the last error message is same (memory err), the lines prior to it are different and the class in the trace is different as well.

**Comment by dfangl** [comment]
Hi!
This depends on the filesystem layout on your EC2 instance. Do you have any partition mounted where RW access is possible? Then I would try setting TMPDIR to this directory.
It still might be that you have a different issue, but it seems we are on the track here.

**Comment by rpanigra18** [comment]
Hi, I updated the CLI on the linux ami.
Now, i am seeing a different error

CLI create function returns error - 
Connection was closed before we received a valid response from endpoint URL: "http://localhost:4566/2015-03-31/functions".

In the LS logs - 
![image](https://user-images.githubusercontent.com/46056069/217665955-a8f5a340-13c1-4919-a103-a26c081bd0f2.png)
