### ISSUE TITLE
Firehose doesn't auto-set S3 date path/prefix

### ISSUE THREAD

**Issue by ewaltman** [localstack/localstack#763]
In the AWS docs for firehose it specifies that the S3Destination buckets get auto-prefixed by the date at which the records are inserted:

https://docs.aws.amazon.com/firehose/latest/APIReference/API_S3DestinationConfiguration.html

The file keys are also dynamically generated by date. Unfortunately, when using a localstack Firehose, I'm only seeing a uuid for the file key and no dynamic date-prefix.

**Comment by whummer** [comment]
Thanks for reporting, this should be working as expected in the meantime - see here: https://github.com/localstack/localstack/blob/master/localstack/services/firehose/firehose_api.py#L105-L113 Please report here if the problem persists. Thanks!
