### ISSUE TITLE
feature request: Store RDS, S3 data in Cloud Pod

### ISSUE THREAD

**Issue by QAnders** [localstack/localstack#7632]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

We use Localstack (LS) for various tasks, developer related mostly, but also for integration testing and some QA testing. We have a bunch of shell scripts today that populates and setup the LS containers but those are kind of arduous to maintain and difficult for some less technical people to run.

The Cloud Pods would be an awesome addition where we could "pre-populate" some containers and store them as cloud pods, ready to bring down for any developer or QA person needing to test.

Since we need to add some "base data" to both S3 Buckets and RDS DB's we'd need to be able to store the Cloud Pod including some pre-populated data.
Today we can't store the S3 or RDS data with the Cloud Pod so feature would be to be able to add data to the Cloud Pod.

**Comment by QAnders** [comment]
I can add that being able to have DynamoDB data stored would also be great (but I haven't actually tested that if it works now or not)

**Comment by steffyP** [comment]
Hi @QAnders,

with [LocalStack release 2.0](https://github.com/localstack/localstack/releases/tag/v2.0.0) we have included several improvements regarding persistence for snapshots and cloudpods. 
S3, DynamoDB and RDS (Postgres, MySQL, MariaDB) and other services listed in our [docs](https://docs.localstack.cloud/references/persistence-mechanism/#supported--tested) have been tested and verified. 

Please let us know if your use case is working with the latest LocalStack version, and reach out if you encounter any issues 🙏

**Comment by steffyP** [comment]
Hi @QAnders, 
as we have not received any response from you in the past 2 months, and persistence for snapshot and cloudpods is generally supported (as already outlined in my last post) we will close this issue now.
