### ISSUE TITLE
feature request: PROVIDER_OVERRIDE_LAMBDA=asf, Lambda container prefix

### ISSUE THREAD

**Issue by elsam** [localstack/localstack#7635]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

We're trying to switch from the old lambda implementation to asf. In the old lambda implementation, when using `LAMBDA_EXECUTOR=docker-reuse`, the lambda container name received a prefix that was equal to that of the local stack container in docker. (This was not the case for all `LAMBDA_EXECUTOR` flavours)

This way, we were able to track the lambda containers that were started for a given localstack instance, print the logs, kill them when necessary.

Request: Would it be possible to prefix the lambda containers with the name of the local stack container itself if present?

**Comment by dominikschubert** [comment]
I agree, would be nicer to be able to distinguish the running containers by name.

We'll look into this. :+1:
