### ISSUE TITLE
Query not supported in API Gateway?

### ISSUE THREAD

**Issue by PatrickStoklasa** [localstack/localstack#765]
I was just trying to call the API Gateway URL with a query like this:

http://localhost:4567/restapis/57A-Z8811198/beta/_user_request_/device?foo=bar

but it tells me that there is no path matching the request. However, if I remove the query it finds the correct integration/path. So I was looking into the source code for the API Gateway and couldn't find the queryStringParamters property anywhere since this would be required in my lambda function. Am I assuming correctly that queries are not supported as of now? Or is there any workaround to do this?

**Comment by mcuervoe** [comment]
+1

**Comment by mhmoudgmal** [comment]
+1

**Comment by mhmoudgmal** [comment]
https://github.com/localstack/localstack/pull/960

**Comment by mhmoudgmal** [comment]
This should be fixed now :) #960

@PatrickStoklasa we can close this issue if it is fixed. Thanks!

**Comment by PatrickStoklasa** [comment]
Thanks!
