### ISSUE TITLE
bug: Kinesis PutRecord/PutRecords does not support stream ARN

### ISSUE THREAD

**Issue by 56KBs** [localstack/localstack#7654]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When attempting to call `PutRecord` or `PutRecords` with a `stream-arn`, localstack returns an error:

```
An error occurred (InternalError) when calling the PutRecord operation (reached max retries: 4): exception while calling kinesis.PutRecord: KinesisProvider.put_record() got an unexpected keyword argument 'stream_arn'
```

### Expected Behavior

Successful putting of records

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal kinesis create-stream --stream-name example
    awslocal kinesis describe-stream --stream-name example <-- extract StreamARN
    root@edab333956f5:/opt/code/localstack# awslocal kinesis put-record --stream-arn arn:aws:kinesis:eu-west-2:000000000000:stream/example --data 'example' --partition-key 1

### Environment

```markdown
- OS: Ubuntu 20.04
- LocalStack: Latest
```

### Anything else?

`put_record` does not allow stream_arn as an argument: https://github.com/localstack/localstack/blob/master/localstack/services/kinesis/provider.py#L116-L124

`put_records` does not allow stream_arn as an argument: https://github.com/localstack/localstack/blob/master/localstack/services/kinesis/provider.py#L133-L135

**Comment by Kaushik-Iyer** [comment]
What exactly needs to be done? If I want to try to work on this?

**Comment by steffyP** [comment]
Hi @Kaushik-Iyer,

for this issue we actually already have a PR prepared.
In this case the `provider.py` for kinesis, which is is implementing the [`KinesisApi`](https://github.com/localstack/localstack/blob/master/localstack/aws/api/kinesis/__init__.py#L853-L874), was missing some parameters of the operations it is overwriting/implementing.

**Comment by steffyP** [comment]
Hi @56KBs,

the reported issue should be fixed in the `latest` LocalStack version. Could you please confirm it is working for you now? 🙏

**Comment by 56KBs** [comment]
@steffyP I can confirm this looks to be fixed now
