### ISSUE TITLE
Quickstart tutorial fails when run

### ISSUE THREAD

**Issue by Ausqa21** [localstack/localstack#7659]
First of all, great product 💯!

I'm new and trying to get localstack setup following the quickstart tutorial. When I get to the part where I'm supposed to serve the web app locally, using `npm run web`, npm gives this output

```
npm ERR! Missing script: "web"
npm ERR! 
npm ERR! To see a list of scripts, run:
npm ERR!   npm run
```

I'm thinking an update might be due, or maybe I'm doing something wrong 😅

**Comment by whummer** [comment]
Hi @Ausqa21 , thanks for reaching out. Just to confirm, you are referring to the sample app in this repo, right? https://github.com/localstack/localstack-demo Please note that we have recently added some changes/simplifications to the demo app, and it should now no longer be required to run the `npm run web` step. Can you please refer to the updated instructions in the repo README?  

Also, if you could point us to a place in our documentation where the sample app instructions are incorrect, we'd appreciate it. Thanks!

**Comment by Ausqa21** [comment]
Woah, that was fast! I'm super impressed. Thanks
