### ISSUE TITLE
feature request: Support for AWS::EKS::Cluster, AWS::EKS::FargateProfile in CloudFormation

### ISSUE THREAD

**Issue by hrishi-hugo** [localstack/localstack#7664]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Hi,
We have seen that LocalStack supports EKS but through cloudformation it is not supported.
We have a PRO license
Currently we need support for these types
AWS::EKS::Cluster
AWS::EKS::FargateProfile

**Comment by dominikschubert** [comment]
> Hey @dominikschubert Thanks for adding EKS support in cloudformation. But I see that the Cloudformation stack status goes into CREATE_COMPLETE status before the cluster gets to ACTIVE status. We are running kubectl commands after the stacks goes into CREATE_COMPLETE but the kubectl commands fail as the cluster is in CREATING status.

Unfortunately this is still a limitation that we have with nearly all of the current CFn resources. As a workaround you can use the CLI (or an SDK) with a waiter after the stack deployment. e.g. `awslocal eks wait cluster-active --name your-cluster-name`

**Comment by hrishi-hugo** [comment]
thanks for the info. we are using a waiter with the SDK for now.
Closing this issue
