### ISSUE TITLE
ec2 - Failed to get D-Bus connection: Operation not permitted

### ISSUE THREAD

**Issue by tehuelche** [localstack/localstack#7666]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

I’m trying the PRO version.
If I try to create an ec2 instance which runs a service get this error:
<img width="1162" alt="01-error-linux-service" src="https://user-images.githubusercontent.com/1951333/218298446-3053cf19-101f-4c73-ba18-58eb10d6ac7b.png">

Is it possible to add commands at the time localstack creates the container that simulates the instance?
(example)
```bash
docker run -d --tmpfs /run -v /sys/fs/cgroup:/sys/fs/cgroup:ro  …
```

I did a quick test to be able to run an ec2 instance similar to the real thing (running a service)

<img width="1162" alt="02-scratch-change" src="https://user-images.githubusercontent.com/1951333/218298558-6b3bf8f5-a05b-4051-a952-bdbedaf2aaff.png">

<img width="1162" alt="03-containers" src="https://user-images.githubusercontent.com/1951333/218298570-25259693-f17c-4277-8f30-10c2e793763e.png">

<img width="1162" alt="04-linux-service-ok" src="https://user-images.githubusercontent.com/1951333/218298580-3c0b1c03-2c79-42cd-978f-680fbdb69082.png">

Is this option valid?

Thanks.

### 🧑‍💻 Implementation

<img width="1162" alt="02-scratch-change" src="https://user-images.githubusercontent.com/1951333/218298663-eedc33b9-7184-4bea-a68b-8fc0ad182b42.png">

https://github.com/tehuelche/localstack/commit/46f3e39c9bb833b56fc962912291608663ec1fdb

**Comment by viren-nadkarni** [comment]
Hi @tehuelche , it is now possible to pass flags directly to Docker Engine. Please see [this section](https://docs.localstack.cloud/user-guide/aws/elastic-compute-cloud/#passing-additional-flags-to-docker) for more details. Let us know how this works for you.
