### ISSUE TITLE
Validation error when writing an SSM parameter

### ISSUE THREAD

**Issue by ricoli** [localstack/localstack#7672]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm trying to execute the following command:
```
aws --region eu-west-2 --endpoint-url=http://localhost:4566 --profile localstack ssm put-parameter --name test --value test
```
And I get this output:
```
An error occurred (ValidationException) when calling the PutParameter operation: 1 validation error detected: Value 'None' at 'type' failed to satisfy constraint: Member must satisfy enum value set: [SecureString, StringList, String]
```
And here are is the localstack log entry:
```
2023-02-13T12:34:37.624  INFO --- [   asgi_gw_1] localstack.request.aws     : AWS ssm.PutParameter => 400 (ValidationException)
```

### Expected Behavior

Expected the CLI call to succeed in writing the SSM parameter

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

docker-compose.yml:
```
services:
  localstack:
    image: localstack/localstack-pro:1.4
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
      - "127.0.0.1:443:443"              # LocalStack HTTPS Gateway (only required for Pro)
    environment:
      - DEBUG=${DEBUG-}
      - PERSISTENCE=${PERSISTENCE-}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      - LAMBDA_REMOTE_DOCKER=false
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY-}  # only required for Pro
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./.localstack-volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

`aws --region eu-west-2 --endpoint-url=http://localhost:4566 --profile localstack ssm put-parameter --name test --value test`

### Environment

```markdown
- OS: PopOS 22.04
- LocalStack: 1.4 (pro docker image)
- AWS CLI: 2.7.7
```

**Comment by dominikschubert** [comment]
Hi @ricoli . This also won't work against AWS. You need to set a type for the parameter explicitly via `--type`.

In your case the command would be: `aws --region eu-west-2 --endpoint-url=http://localhost:4566 --profile localstack ssm put-parameter --name test --value test --type String`

**Comment by ricoli** [comment]
> Hi @ricoli . This also won't work against AWS. You need to set a type for the parameter explicitly via `--type`.
> 
> In your case the command would be: `aws --region eu-west-2 --endpoint-url=http://localhost:4566 --profile localstack ssm put-parameter --name test --value test --type String`

ah indeed you are very much right - `--type` is only optional when updating a parameter... weirdly localstack didn't use to throw an error before when creating a param without it

**Comment by joe4dev** [comment]
> weirdly localstack didn't use to throw an error before when creating a param without it, but glad that it does now!

This is one of many improvements with the new lambda provider v2 (see [Lambda Provider Behavioral Changes#API](https://docs.localstack.cloud/references/lambda-asf-provider/#api)): "Parity with AWS has been increased across all Lambda API methods. Another improvement is the stricter input validation, so expect more invalid input to fail."
