### ISSUE TITLE
Make install issue

### ISSUE THREAD

**Issue by cristal2431** [localstack/localstack#768]
I am getting version issue on make install. 

`$ make install
(test `which virtualenv` || pip install --user virtualenv) && \
		(test -e .venv || virtualenv  .venv) && \
		(. .venv/bin/activate && pip -q install pip==9.0.3) && \
		(test ! -e requirements.txt || (. .venv/bin/activate; pip install -q six==1.10.0 ; pip -q install -r requirements.txt) && \
		. .venv/bin/activate; PYTHONPATH=. exec python localstack/services/install.py testlibs)
Collecting virtualenv
  Could not find a version that satisfies the requirement virtualenv (from versions: )
  No matching distribution found for virtualenv
make: *** [install] Error 1`

**Comment by whummer** [comment]
This is not a LocalStack issue, but looks like a general issue in your Python environment. Closing this issue for housekeeping reasons.

Please make sure you can install pip packages in your environment - in particular, please make sure the following commands work before proceeding with the installation of LocalStack. Thanks
```
pip install --user virtualenv
virtualenv --version
```
