### ISSUE TITLE
Initialisation scripts

### ISSUE THREAD

**Issue by ricardogama** [localstack/localstack#769]
A really nice feature to have would be the ability of running some initialisation scripts when the localstack container is created, very similar to the `docker-entrypoint-initdb.d` folder used by the [postgres](https://github.com/docker-library/postgres/blob/c4cb816b3deccc29393b8278d1a5f144d2be26f1/9.6/Dockerfile#L43) and [mysql](https://github.com/docker-library/mysql/blob/fc3e856313423dc2d6a8d74cfd6b678582090fc7/5.7/Dockerfile#L22) Dockerfiles.

This way, it would be easy to setup the testing environment by just creating a volume to some script files that would run some `aws` client commands, like creating DynamoDB tables, instead of making that bootstrap after the container is running.

**Comment by ajainvivek** [comment]
@ricardogama you can initialize setup scripts via docker by mounting the volume

`setup.sh`

```
#!/bin/bash

set -ex

# CREATE EVENTS STREAM
# - in non-local environments, this stream is managed by a different system
# list streams: aws --region=us-west-2 --endpoint-url=http://localhost:4568 kinesis list-streams
aws --region=us-west-2 --endpoint-url=http://localstack:4568 kinesis create-stream --stream-name events-stream --shard-count 1
echo "created Kinesis stream - events-stream"
```


`docker-compose.yaml`
```
version: '3'

services:
    localstack:
        image: localstack
        ports:
            - 4568:4568
        volumes:
            - $PROJECT_ROOT/localstack:/docker-entrypoint-initaws.d
        environment:
            - SERVICES=kinesis,s3,sqs,dynamodb
            - HOSTNAME_EXTERNAL=localstack
            - DEBUG=1
```

**Comment by whummer** [comment]
👍  Has been added in the meantime, see README: https://github.com/localstack/localstack#initializing-a-fresh-instance Thanks
