### ISSUE TITLE
bug: unable to create S3 bucket with tflocal: no such host

### ISSUE THREAD

**Issue by iwt-kschoenrock** [localstack/localstack#7692]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Attempting to create an S3 bucket with terraform (via `tflocal`) fails:

```
$ tflocal apply
...
Plan: 1 to add, 0 to change, 0 to destroy.
aws_s3_bucket.my-bucket: Creating...
aws_s3_bucket.my-bucket: Still creating... [10s elapsed]
aws_s3_bucket.my-bucket: Still creating... [20s elapsed]
╷
│ Error: creating Amazon S3 (Simple Storage) Bucket (teste): RequestError: send request failed
│ caused by: Put "http://teste.s3.localhost.localstack.cloud:4566/": dial tcp: lookup teste.s3.localhost.localstack.cloud on 192.168.178.1:53: no such host
│
│   with aws_s3_bucket.my-bucket,
│   on main.tf line 10, in resource "aws_s3_bucket" "my-bucket":
│   10: resource "aws_s3_bucket" "my-bucket" {
│
╵
```

I used this terraform configuration:
```
terraform {
  backend local {}
}

provider "aws" {
    //  s3_use_path_style           = true
}

// S3
resource "aws_s3_bucket" "my-bucket" {
  bucket = "teste"
}
```

Setting the parameter `s3_use_path_style=true` does not help:

```
Plan: 1 to add, 0 to change, 0 to destroy.
aws_s3_bucket.my-bucket: Creating...
aws_s3_bucket.my-bucket: Still creating... [10s elapsed]
aws_s3_bucket.my-bucket: Still creating... [20s elapsed]
╷
│ Error: creating Amazon S3 (Simple Storage) Bucket (teste): RequestError: send request failed
│ caused by: Put "http://s3.localhost.localstack.cloud:4566/teste": dial tcp: lookup s3.localhost.localstack.cloud on 192.168.178.1:53: no such host
│
│   with aws_s3_bucket.my-bucket,
│   on main.tf line 10, in resource "aws_s3_bucket" "my-bucket":
│   10: resource "aws_s3_bucket" "my-bucket" {
│
╵
```

### Expected Behavior

The bucket `teste` is created.

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    localstack start

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    tflocal init
    tflocal apply -auto-approve

### Environment

```markdown
- OS: macOS 13.1
- LocalStack: 1.4.0
```

### Anything else?

The bucket can be created with `awslocal` without issue.
```
awslocal s3api create-bucket --bucket teste
```

**Comment by whummer** [comment]
Thanks for reporting @iwt-kschoenrock . Looks like this could be a DNS resolution issue - are you behind a corporate firewall, by any chance?

Can you please share the output of these commands:
```
$ host localhost.localstack.cloud
$ host s3.localhost.localstack.cloud
$ host teste.s3.localhost.localstack.cloud
$ dig teste.s3.localhost.localstack.cloud
```

As a workaround, you could try setting `S3_HOSTNAME=localhost` in your environment (in the terminal session where you're running `tflocal`) - does that work?

**Comment by iwt-kschoenrock** [comment]
It's a company machine, but not in their network (as far as these tests are concerned).

`host localhost.localstack.cloud` shows nothing, here is `host -v localhost.localstack.cloud:
<details>

<summary>

`host -v localhost.localstack.cloud`
</summary>

```
Trying "localhost.localstack.cloud"
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 6472
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;localhost.localstack.cloud.	IN	A

Received 44 bytes from 192.168.178.1#53 in 1 ms
Trying "localhost.localstack.cloud"
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 5448
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0

;; QUESTION SECTION:
;localhost.localstack.cloud.	IN	AAAA

;; AUTHORITY SECTION:
localstack.cloud.	3587	IN	SOA	ns1.gandi.net. hostmaster.gandi.net. 1672403174 10800 3600 604800 10800

Received 104 bytes from 192.168.178.1#53 in 2 ms
Trying "localhost.localstack.cloud"
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 30186
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0

;; QUESTION SECTION:
;localhost.localstack.cloud.	IN	MX

;; AUTHORITY SECTION:
localstack.cloud.	3587	IN	SOA	ns1.gandi.net. hostmaster.gandi.net. 1672403174 10800 3600 604800 10800
```
</details>


<details>

<summary> 

`host s3.localhost.localstack.cloud` 

</summary>

```
s3.localhost.localstack.cloud is an alias for localhost.localstack.cloud.
s3.localhost.localstack.cloud is an alias for localhost.localstack.cloud.
```
</details>

<details>

<summary> 

`host teste.s3.localhost.localstack.cloud ` 

</summary>

```
teste.s3.localhost.localstack.cloud is an alias for localhost.localstack.cloud.
teste.s3.localhost.localstack.cloud is an alias for localhost.localstack.cloud.
```
</details>


<details>

<summary> 

`dig teste.s3.localhost.localstack.cloud` 

</summary>

```
dig teste.s3.localhost.localstack.cloud

; <<>> DiG 9.10.6 <<>> teste.s3.localhost.localstack.cloud
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 56545
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;teste.s3.localhost.localstack.cloud. IN	A

;; Query time: 6 msec
;; SERVER: 192.168.178.1#53(192.168.178.1)
;; WHEN: Mon Feb 20 08:23:44 CET 2023
;; MSG SIZE  rcvd: 53
```

</details>

Adding `S3_HOSTNAME=localhost` before `tflocal` worked.

```
❯ awslocal s3api list-buckets
BUCKETS	2023-02-20T07:31:14+00:00	teste
```

Most curious of all, though, is that `tflocal` works _without_ having to set `S3_HOSTNAME` if I'm in the company VPN. 

<details>

<summary>

`host localhost.localstack.cloud`
</summary>

```
localhost.localstack.cloud has address 127.0.0.1
```
</details>

**Comment by gurleensethi** [comment]
Any update on this?

**Comment by bentsku** [comment]
Hi @gurleensethi, this issue seems to be specific to the setup and DNS resolution of @iwt-kschoenrock (by the way, any progress on the issue? was the workaround provided enough?).

Do you have a similar issue, did the workaround given work? 

Feel free to either share it here if similar, or open a new issue with more informations.

**Comment by gurleensethi** [comment]
@bentsku I am making the request to a presigned url in Go.

**Comment by bentsku** [comment]
@gurleensethi okay, so this doesn't seem to have anything to do with this issue.

Feel free to open a new issue, or, if it's more of a question, in https://discuss.localstack.cloud. You might want to have a look at https://docs.localstack.cloud/references/network-troubleshooting/ before, you might find your answer there. Thanks!

**Comment by theahura** [comment]
I am also running into this. Running `terraform init && terraform apply` results in the following:

```
Error: reading Amazon S3 (Simple Storage) Bucket (user-uploads): RequestError: send request failed
caused by: Head "http://user-uploads.s3.localhost.localstack.cloud:4566/": dial tcp: lookup user-uploads.s3.localhost.localstack.cloud on 127.0.0.53:53: no such host
```

When I run `host localhost.localstack.cloud` I get nothing, as per above. Unfortunately running `export S3_HOSTNAME=localhost` does not fix the issue for me

Any ideas for how I can debug this?

**Comment by theahura** [comment]
Update: I ended up being able to fix this by changing the wifi I was on. My guess is that something on my local router was blocking the call out to localhost.localstack.cloud :thinking: in case anyone else digs deeper, it may be helpful to include a note in the s3 docs for localstack about how to configure a router to allow in/outbound requests to that domain

**Comment by anatoli-klamer** [comment]
have the same issue
```
host localhost.localstack.cloud
localhost.localstack.cloud has address 127.0.0.1
```
also setting
`export S3_HOSTNAME=localhost`

seems doesn't help too:
```
Error: creating Amazon S3 (Simple Storage) Bucket (test-example-foo): RequestError: send request failed
      │ caused by: Put "http://test-example-foo.localhost:4566/": dial tcp: lookup dev-test-example-foo.localhost on 100.64.0.1:53: no such host
```

```
version: '3'
services:
  localstack:
    image: localstack/localstack
    platform: linux/arm64/v8
    ports:
      - "4566-4599:4566-4599"
    environment:
      - DEBUG=1
      - LAMBDA_DOWNLOAD_AWS_LAYERS=0
      - AWS_REGION=us-west-2
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      localstack-net:
        ipv4_address: 172.20.1.1
networks:
  localstack-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
```

**Comment by skorfmann** [comment]
Ran into this as well, had Tailscale active where I got 

> s3.localhost.localstack.cloud on 100.100.100.100:53: no such host

Deactivating Tailscale resolved to my local router somehow. Changing the DNS settings from my router to Google DNS (`8.8.8.8`) made it work eventually.

**Comment by birbirsbirbirs** [comment]
$ export S3_HOSTNAME=localhost
before running
$ tflocal apply
solve this issue for me. I am using Ubuntu 24.04.2 LTS x86_64

**Comment by birbirsbirbirs** [comment]
I have issue in mac using local install localstack, solved by using docker compose work in mac. docker-compose.yml,

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack:latest-arm64
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

main.tf

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "6.25.0"
    }
  }
}

resource "aws_s3_bucket" "ptm-dev-bucket" {
  bucket        = "ptm-dev-bucket"
  force_destroy = true

  tags = {
    name        = "tag-ptm-dev-bucket"
    environment = "dev"
  }
}
