### ISSUE TITLE
feature request: Support of Web Application Firewall v2 (WAFv2)

### ISSUE THREAD

**Issue by ppetershagen** [localstack/localstack#7725]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

As full stack development team,
we would like to execute all of our Terraform scripts to create AWS in the same way for each environment (LocalStack or AWS),
so that we make sure, our infrastructure code is valid and creates the expected resources.

In relation to an API Gateway v2 resource we also create ACLs with WAFv2 to restrict incoming traffic as much as possible. For feature branch builds or local testing a complete firewall implementation is not required. However, we'd like to see the Terraform scripts executed and the resources created (CRUD).

WAFv2 resources are currently not supported, like: `aws_wafv2_web_acl, aws_wafv2_ip_set, aws_wafv2_web_acl_association `

### Anything else?

- https://docs.aws.amazon.com/waf/latest/APIReference/Welcome.html
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/wafv2_web_acl.html

**Comment by davecardwell** [comment]
It would be sufficient for us as a first pass if the CRUD operations succeeded so we can avoid having to special-case our config in development for Localstack.

Then if possible in the future, implementing WAF features and the AWS-managed rulesets would be welcome.

**Comment by HarshCasper** [comment]
Hi @ppetershagen — Thanks for creating the issue! We have shipped a CRUD implementation that should unblock you. Please pull the `localstack/localstack-pro:latest` Docker image, and let us know your feedback! 🙏
