### ISSUE TITLE
bug: Specifying `LOCALSTACK_API_KEY` changes Lambda executor method

### ISSUE THREAD

**Issue by rcambrj** [localstack/localstack#7726]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Only enabling `LOCALSTACK_API_KEY` causes Lambda execution to fail with:

```
localstack_main  | 2023-02-21T14:18:19.479 DEBUG --- [uest_thread)] l.u.c.docker_sdk_client    : Starting container 8718150a67759dbc419e1a0b5d5ef5be5c74e0a65194412fbce59a2630912d48
localstack_main  | 2023-02-21T14:18:25.344 DEBUG --- [uest_thread)] l.s.a.lambda_executors     : Lambda arn:aws:lambda:eu-central-1:000000000000:function:my-lambda result / log output:
localstack_main  | {"errorMessage":"2023-02-21T14:18:25.215Z db407c3e-5c47-1a45-13f4-461bebfdf198 Task timed out after 3.00 seconds"}
localstack_main  | >tail: unrecognized file system type 0x794c7630 for ‘/tmp/__daemons.out’. please report this to bug-coreutils@gnu.org. reverting to polling
localstack_main  | > START RequestId: db407c3e-5c47-1a45-13f4-461bebfdf198 Version: $LATEST
```

### Expected Behavior

Lambda execution does not fail when only changing `LOCALSTACK_API_KEY`

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

```
  localstack:
    image: localstack/localstack
    container_name: localstack_main
    ports:
      - "127.0.0.1:4566:4566"
    environment:
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY:-}
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./localstack}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

Using `tf-local` to bring up ApiGateway and Lambdas.

### Environment

```markdown
- OS: MacOS 12.6
- LocalStack: 1.3.2.dev
```

### Anything else?

Seems to be fixed by also specifying `PROVIDER_OVERRIDE_LAMBDA=asf` as recommended in #7527, but this isn't necessary when not using `LOCALSTACK_API_KEY`.

Further, this container attribute changed:

```
// without LOCALSTACK_API_KEY (working)
'image_name': 'localstack/lambda:go1.x'
```

```
// with LOCALSTACK_API_KEY (broken)
'image_name': 'lambci/lambda:go1.x',
```

```
// with LOCALSTACK_API_KEY & PROVIDER_OVERRIDE_LAMBDA=asf (working)
'image_name': 'public.ecr.aws/lambda/go:1',
```

This happens with `localstack/localstack` and `localstack/localstack-pro`

**Comment by rcambrj** [comment]
@joe4dev you're correct and yes it does, although I used `asf` instead of `v2` but they appear to be aliases.

It's the unexpected change when enabling `LOCALSTACK_API_KEY`. _Only_ enabling this breaks Lambdas.

If v2 isn't far away and you don't want to fix this, then hopefully this issue will point folks in the right direction should they decide to upgrade to pro on anything older.

**Comment by joe4dev** [comment]
Thank you for the quick clarification @rcambrj 
I guess some additional pro features might cause problems in the old provider, which would explain the unexpected change.

Agreed, I think we can close this issue on the note that it works using the [new lambda provider ](https://docs.localstack.cloud/references/lambda-asf-provider/)`PROVIDER_OVERRIDE_LAMBDA=v2`
