### ISSUE TITLE
feature request: Support of $context.requestOverride in apigateway

### ISSUE THREAD

**Issue by tukutela** [localstack/localstack#7727]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

I make quite extensive use of `requestOverride` in request templates, for example:

```
#set($context.requestOverride.header.Authorization = "token SomeTOKEN")
```

Any suggestions on how I can bypass this for localstack dev would be appreciated... Thanks!

**Comment by tukutela** [comment]
same with `responseOverride`....

**Comment by agershman** [comment]
Any chance we can get some movement on this?

**Comment by calvernaz** [comment]
Hi @agershman a fix for this should be out soon, at least a minimal support for it that we hope to improve over time.

**Comment by calvernaz** [comment]
Hi @agershman, the fix has been merged. Would be great if you could try with the latest, thanks :+1:

**Comment by agershman** [comment]
@calvernaz This is working for me. Thanks!
