### ISSUE TITLE
feature request: KMS HMAC support

### ISSUE THREAD

**Issue by josemartins-form3** [localstack/localstack#7736]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Support AWS KMS key with `customer_master_key_spec` value `HMAC_256`. 

Additionally:
- [KMS user-guide](https://docs.localstack.cloud/user-guide/aws/kms/) makes it look like localstack supports HMAC keys.
- The [current-differences-between-localstack-kms-and-aws-kms](https://docs.localstack.cloud/user-guide/aws/kms/#current-differences-between-localstack-kms-and-aws-kms) doesn't say anything about HMAC.
-  The [source code](https://github.com/localstack/localstack/blob/master/localstack/services/kms/models.py#L161-L173) is really clear on not supporting HMAC.

### 🧑‍💻 Implementation

I don't have an idea on what's required but I'm happy to help out if someone can point me in the right direction.

**Comment by sannya-singal** [comment]
Thanks for reporting @josemartins-form3. We have added this feature in #8047.  
Can you please pull the `latest` docker image and give it a try?

**Comment by josemartins-form3** [comment]
Hi @sannya-singal! Awesome news! I'll test it next week and post some feedback here. Thanks!

**Comment by josemartins-form3** [comment]
HMAC keys are working like a charm for `GENERATE_VERIFY_MAC`. Thanks for implementing this :tada:
