### ISSUE TITLE
bug: [PRO] Cognito jwks have hardcoded `kid` value

### ISSUE THREAD

**Issue by cooperaustinj** [localstack/localstack#7741]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

We have a multi-tenant application with one user pool per tenant. Our application queries and saves the jwks for each user pool. When we validate a jwt, the `kid` header in the token is used to identify which jwk needs to be used.

jwks generated at `/<user-pool-id>/.well-known/jwks.json` have a hardcoded value (`test-key`) for the `kid` property. When validating a jwt, it isn't possible to figure out which jwk is the right one since all the identifiers are the same.

Example data:
```sh
curl http://localhost:4566/<user-pool-id>/.well-known/jwks.json
{"keys": [{"kty": "RSA", "alg": "RS256", "use": "sig", "kid": "test-key", "n": "0VWQzEFrWUfJNX2h9laDDhS5BJimTBRdBU36K7TpnkP4pWK_DWLA4q96vXaVwQYdLmaU57ZmB-fUa1VSZpvaG-ySmaZz_sesoREF7n6JVK4WWB5nRiXc4AzCReTGZDuxX3MRdtY_P1m4mwx0QZ1Wk-OF_KzTzoHjQ4AbTUONeXviswejxP-0Hou6vdz3xniAuCFVg3rqIh9v3NcEj9aFwRQ_KndYbOo6vdgrkgXXcg0K2mXqkDtqoQv9QNvPKCKywOUDak-0mtSeSZokFGekeiQOZom4h_0-8RizdIHHaRhw23_HqooSEj71_5A0DRqA3rVQFG78xSm-qr3mSpi5HQ", "e": "AQAB"}]}
```

### Expected Behavior

I would expect the `kid` property on each jwk to be unique to each jwk. This is the behavior in AWS's Cognito. The behavior should match so implementations depending on the property can integrate with localstack.

**Note:** the jwt returned during authentication also needs the same unique `kid` value in its header.

Example expectation:
```sh
curl http://localhost:4566/<user-pool-id>/.well-known/jwks.json
{"keys": [{"kty": "RSA", "alg": "RS256", "use": "sig", "kid": "830f51a8-44b3-4efb-bc7c-6e23be85c234", "n": "0VWQzEFrWUfJNX2h9laDDhS5BJimTBRdBU36K7TpnkP4pWK_DWLA4q96vXaVwQYdLmaU57ZmB-fUa1VSZpvaG-ySmaZz_sesoREF7n6JVK4WWB5nRiXc4AzCReTGZDuxX3MRdtY_P1m4mwx0QZ1Wk-OF_KzTzoHjQ4AbTUONeXviswejxP-0Hou6vdz3xniAuCFVg3rqIh9v3NcEj9aFwRQ_KndYbOo6vdgrkgXXcg0K2mXqkDtqoQv9QNvPKCKywOUDak-0mtSeSZokFGekeiQOZom4h_0-8RizdIHHaRhw23_HqooSEj71_5A0DRqA3rVQFG78xSm-qr3mSpi5HQ", "e": "AQAB"}]}
```

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

1. Start localstack
2. Run terraform to create a user pool, user pool client, and a user
3. `curl http://localhost:4566/<user-pool-id>/.well-known/jwks.json`

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker compose up -d

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    curl http://localhost:4566/<user-pool-id>/.well-known/jwks.json

### Environment

```markdown
- OS: MacOS (M1 MacBook Pro)
- LocalStack: latest
```

**Comment by cooperaustinj** [comment]
@giograno is that possibly still deploying? I see the latest tag is from yesterday. I am still replicating the issue with the most recent image (sha256:fed938f90...)

**Comment by giograno** [comment]
@cooperaustinj are you still experiencing the issue as today with the latest image?
