### ISSUE TITLE
bug: LocalStack Cockpit shows error for missing `.localstack` folder

### ISSUE THREAD

**Issue by sayor-basu** [localstack/localstack#7743]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The app shows the following error during initialization and does not allow to also create a profile

![image](https://user-images.githubusercontent.com/53848885/221056586-7b178895-7923-46de-ae12-d89b2505ddf7.png)

### Expected Behavior

When Cockpit launches there should not be any error if prerequisites (Docker) are present. Any app specific required files/folders should be created by the app

### How are you starting LocalStack?

Custom (please describe below)

#### How are you starting localstack Cockpit

- For the first launch: override signing issue by ctrl+click to open the app
- click on app or search and open

### Environment

```markdown
- OS: MacOS 13.2.1 (M1)
- LocalStack: 1.4.0
- Cockpit install location: https://localstack.cloud/products/cockpit/ ; note: only Mac(Intel) platform, current M`x` option
```

### Anything else?

 The error is resolved by manually creating the `.localstack` folder in the location

**Comment by HarshCasper** [comment]
[LocalStack Desktop](https://docs.localstack.cloud/user-guide/tools/localstack-desktop/) replaces the previous Cockpit. Cockpit isn’t available or maintained anymore and we recommend you to use LocalStack Desktop instead. Please let us know if that fixes your issue!
