### ISSUE TITLE
bug: EC2 service does not recognize AMI images created by Podman

### ISSUE THREAD

**Issue by sha-shrestha** [localstack/localstack#7744]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

AMI images aren't discovered as per the docs here: https://docs.localstack.cloud/user-guide/aws/elastic-compute-cloud/

This is most likely caused by the fact that `Podman` tags the local images with `localhost/` prefix.
https://github.com/containers/buildah/issues/1034

`
aws --endpoint http://localhost.localstack.cloud:4566 ec2 describe-images --filters Name=tag:ec2_vm_manager,Values=docker
{
    "Images": []
}
`

### Expected Behavior

AMI images are listed.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

     docker-compose.yml

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)
    podman tag ubuntu:focal localstack-ec2/ubuntu-focal-ami:ami-000001
    awslocal ec2 describe-images --filters Name=tag:ec2_vm_manager,Values=docker

### Environment

```markdown
- OS: RHEL8
- LocalStack:1.4.1
- Podman: 4.2.0
```

**Comment by sha-shrestha** [comment]
@whummer

**Comment by whummer** [comment]
Thanks for reporting @sha-shrestha . This issue has now been resolved - listing EC2 container images created by Podman should now work 👍  (available in the `latest` Docker image, will also be shared as a custom image shortly).
