### ISSUE TITLE
bug: Localstack Cockpit does not pass on IMAGE_NAME as documented in the App

### ISSUE THREAD

**Issue by brianczapiga** [localstack/localstack#7756]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Localstack Cockpit does not pass on IMAGE_NAME as documented in the App.

Add a run configuration named `old`. Specify `IMAGE_NAME=localstack:1.3.9` in the environment variables. Click `START`. Localstack Cockpit runs the latest image.

### Expected Behavior

Setting IMAGE_NAME in the environments should allow us to specify arbitrary image names and tags so we can pin to a specific version.

Currently, it only allows using localstack:latest.

Alternatively, if localstack-cli is manually used to startup, we can specify an arbitrary image/tag. Localstack Cockpit can see the running services and logs from the manually started application.

### How are you starting LocalStack?

Custom (please describe below)

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

Specifically for this issue, Localstack is started up using the START button within the Localstack Cockpit interface.

### Environment

```markdown
- OS: MacOS Monterey 12.4
- Arch: Apple M1
- LocalStack: 1.4.1.dev
- LocalStack Cockpit: v0.2.0
```

**Comment by HarshCasper** [comment]
[LocalStack Desktop](https://docs.localstack.cloud/user-guide/tools/localstack-desktop/) replaces the previous Cockpit. Cockpit isn’t available or maintained anymore and we recommend you to use LocalStack Desktop instead. Please let us know if that fixes your issue!
