### ISSUE TITLE
bug: [PRO] local_daemon.py uses address range 192.168.123.* on en0

### ISSUE THREAD

**Issue by brianczapiga** [localstack/localstack#7759]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

local_daemon.py arbitrarily uses the address range `192.168.123.*` in the variable `LOCAL_BIND_ADDRESS_PATTERN` regardless of the address range of the adapter.

further, there is no effort to ensure the addresses do not conflict with existing addresses on the local network.

### Expected Behavior

either create a virtual bridge on the host on which to bind addresses (do not bind to en0), or detect the address range of en0 and use DHCP/ping to avoid collisions on the adapter

do not arbitrarily bind to sequential addresses in the 192.168.123.* range

### How are you starting LocalStack?

```
docker-compose up -d
localstack daemons start
```

### Steps To Reproduce

```
docker-compose up -d
localstack daemons start
# set AMI to an ec2 docker image
awslocal ec2 run-instances --image-id $AMI --count 1 --key-name localstack --query "Instances[0].InstanceId" | jq -r
ifconfig -a
```

### Environment

```markdown
- OS: MacOS Ventura
- LocalStack: 1.4.1dev (Pro Trial)
```

**Comment by viren-nadkarni** [comment]
Local daemon is deprecated and will be removed. See https://github.com/localstack/localstack-ext/pull/1746
