### ISSUE TITLE
Is kinesis analytics service exist?

### ISSUE THREAD

**Issue by norfarahim** [localstack/localstack#776]
Hi. So you already know my question based on the title. I assumed the service still do not have in localstack since in the readme you guys didn't list it. Also, I got an error whenever I want to start create-application under kinesis analytics service but just wanna ask you guys just to be sure. Thank you :)

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-308) by [Unito](https://www.unito.io/learn-more)

**Comment by thrau** [comment]
we have basic kinesis analytics support in pro!

/cc @whummer i think we could include this in the feature coverage
