### ISSUE TITLE
bug: ELB does not forward path parameters

### ISSUE THREAD

**Issue by sha-shrestha** [localstack/localstack#7761]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

ELB does not forward the URL path parameters.

Setup as done as per the guide here:
https://docs.localstack.cloud/user-guide/aws/elastic-load-balancing/

### Expected Behavior

ELB forwards the URL path parameters

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker-compose.yml

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

Executed the commands as per the guide here:
https://docs.localstack.cloud/user-guide/aws/elastic-load-balancing/

### Environment

```markdown
- OS: RHEL8
- LocalStack: 1.4.1
```

**Comment by sha-shrestha** [comment]
@whummer

**Comment by whummer** [comment]
Thanks for reporting @sha-shrestha . This has been resolved in the meantime, the fix should be available in the `latest` Docker image (and will soon be replicated into custom Enterprise images). 👍  Closing this issue for now.. Thanks!
