### ISSUE TITLE
bug: lambda Add permission accepts non-compliant statement IDs

### ISSUE THREAD

**Issue by wunderbarb** [localstack/localstack#7763]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Statement ID should be [0-9a-zA-z_/-]+  but localstack accepts for instance "example.com"

### How are you starting LocalStack?

With a `docker run` command

### Steps To Reproduce

```golang
	c := lambda.NewFromConfig(cfg)
	api := &lambda.AddPermissionInput{
		Action:              aws.String("lambda:InvokeFunction"),
		FunctionName:        aws.String(arn),
		Principal:           aws.String("events.amazonaws.com"),
		StatementId:         aws.String("example.com),
		EventSourceToken:    nil,
		FunctionUrlAuthType: "",
		PrincipalOrgID:      nil,
		Qualifier:           nil,
		RevisionId:          nil,
		SourceAccount:       nil,
		SourceArn:           aws.String(rnARN),
	}
	_, err = c.AddPermission(context.Background(), api)
```

### Environment

```markdown
- OS: Ubuntu 20.04
- LocalStack: 1.4.0  pro
```

**Comment by joe4dev** [comment]
Hi @wunderbarb Thank you for sharing this missing validation.

We implemented a fix that will become available shortly (as part of PR https://github.com/localstack/localstack/pull/7762). We will let you know when it is available in the latest Docker image.

**Comment by joe4dev** [comment]
Hi @wunderbarb The fix should be available in the latest Docker image. Can you please `docker pull localstack/localstack-pro` and give it a try?
