### ISSUE TITLE
Make ES version configurable

### ISSUE THREAD

**Issue by will3216** [localstack/localstack#777]
Currently, there is no way to configure which version of elasticsearch localstack uses. It would be nice if we could configure it! In my case, I have plugins that I require which run on 5.x.x but not 6.x.x so I have to run elasticsearch separately to support them.

That said, this is an awesome project and I really appreciate the hard-work that's gone into it!

**Comment by whummer** [comment]
Thanks for reporting - it should now be possible in the `latest` version to specify the Elasticsearch version when creating a new ES domain (specific versions are downloaded to a temporary folder on request). Please report here if there are any issues - thanks!
