### ISSUE TITLE
feature request: AWS::ApiGatewayV2::ApiMapping

### ISSUE THREAD

**Issue by QuinnyPig** [localstack/localstack#7775]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

I'd like it if the AWS::ApiGatewayV2::ApiMapping resource was supported; I'm attempting to deploy a stack that depends upon it. 

### 🧑‍💻 Implementation

I would simply tab-complete my way through GitHub Copilot and watch as the robot takes away the job I am very bad at.

**Comment by pinzon** [comment]
The PR for this feature has just been merged. Please make sure to pull the latest image of LocalStack Pro.
