### ISSUE TITLE
Persistence instability with the latest image

### ISSUE THREAD

**Issue by giograno** [localstack/localstack#7776]
We are currently in the process of reworking a lot of code related to persistence ---both the regular [persistence feature](https://docs.localstack.cloud/references/persistence-mechanism/) enabled with `PERSISTENCE=1` and [CloudPods](https://docs.localstack.cloud/user-guide/tools/cloud-pods/)--- with the goal of releasing a more stable, efficient, and well-tested state management mechanism spanning across both features for our upcoming v2 release!

Therefore, if you are relying on these features and you are using the `latest` Docker tag, you may experience regressions or other limitations around LocalStack restoring state correctly.

To implement these improvements quickly and efficiently, we may be introducing regressions that may manifest as:
* service resources not restoring correctly;
* service infrastructure (like OpenSearch clusters, RDS instances, or similar infrastructure) not fully spinning up correctly after restoring their state;
* Cloud Pods created with older LocalStack versions not correctly or entirely restored.
* Requests to services blocking indefinitely

We are aware of these issues and are working to solve them quickly even on the latest docker image tag. 
However, if you need stable persistence, we would recommend using the :v1.4 [tag](https://hub.docker.com/layers/localstack/localstack/1.4/images/sha256-4a966e42eff4bbeec44afe13c2d24a67954742b191caae7c15e56186cc0b9ed8?context=explore), until we release the next major version.

Thank you very much for your patience.
The LocalStack Team.

**Comment by tiagoposse** [comment]
Is there any ETA (however wrong a prediction it may be) of a v2 release?

**Comment by thrau** [comment]
@tiagoposse Likely sometime within the eight weeks. We'll let you know when the release date is finalized

**Comment by thrau** [comment]
With v2.0 we have now stabilized the persistence implementation and started documenting coverage and known limitations https://docs.localstack.cloud/references/persistence-mechanism/#service-coverage

We will work to continuously improve persistence coverage!
