### ISSUE TITLE
bug: Cannot list roles which have permission boundaries attached

### ISSUE THREAD

**Issue by bhavikkumar** [localstack/localstack#7779]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When attempting to list roles where permission boundaries are attached the response cannot be serialized 

`aws --endpoint-url=http://localhost:4566 iam list-roles --region ap-southeast-2`
```
An error occurred (InternalError) when calling the ListRoles operation (reached max retries: 2): exception while calling iam.ListRoles: Invalid type when serializing AttachedPermissionsBoundary: '<Element 'member' at 0xffff8275ef20>' cannot be parsed to structure.
```

### Expected Behavior

Expect that all roles are listed

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

* Create an IAM policy
* Create an IAM role which used the policy as a permission boundary
* Attempt to list all roles with `aws --endpoint-url=http://localhost:4566 iam list-roles --region ap-southeast-2`

### Environment

```markdown
- OS: MacOS
- LocalStack: latest
```

**Comment by slapula** [comment]
I can confirm that I'm seeing this behavior as well.  I'm running on Localstack version `2.0.1`.

**Comment by dfangl** [comment]
Hi @bhavikkumar !

Thank you for your report. This should now be fixed, the fix image will be available soon.
