### ISSUE TITLE
Alpakka s3 connector multipartCopy fails

### ISSUE THREAD

**Issue by armeltd** [localstack/localstack#778]
The multipartCopy operation of alapakka S3 connector works fine with aws s3 but it doesn't work with the localstack container.
I get this message  : "One or more of the specified parts could not be found. The part might not have been uploaded, or the specified entity tag might not have matched the part's entity tag."
Do you know the reason ?

**Comment by whummer** [comment]
Thanks for reporting - This should (likely) be solved in the latest version. Closing this for lack of details to reproduce. Please report here with an isolated example to help reproduce this issue. Thanks!
