### ISSUE TITLE
Error creating S3 bucket in parallel in us-east-2

### ISSUE THREAD

**Issue by andrii-dovzhenko** [localstack/localstack#7781]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The following code raises an exception on "localstack/localstack:1.4.0":
```terraform
resource "aws_s3_bucket" "vault_bucket" {
  for_each = module.s3_bucket_names.escaped

  bucket              = "${each.value}-${module.aws_s3_bucket_uniq_token.value}"
  force_destroy       = true
  object_lock_enabled = true
}
```

The error looks like the following:
```
  │ Error: error creating S3 Bucket (...): IllegalLocationConstraintException: The unspecified location constraint is incompatible for the region specific endpoint this request was sent to.
  │ 	status code: 400, request id: (...), host id: (...)
  │ 
  │   with aws_s3_bucket.vault_bucket["fake-vault-123456"],
  │   on main.tf line 44, in resource "aws_s3_bucket" "vault_bucket":
  │   44: resource "aws_s3_bucket" "vault_bucket" {
  │ 
```
Our theory is that this is a concurrency bug in Localstack that manifests itself when creating buckets in parallel.
Because Terraform obviously always sets the correct location constraint ([more here](https://github.com/hashicorp/terraform-provider-aws/blob/a65002b873e17df5d0f19a6d16ff53d0c91a5aab/internal/service/s3/bucket.go#L676-L685)).

We believe that the problem is parallelism because these errors occur randomly.

### Expected Behavior

Expect this code to create an s3 bucket

### How are you starting LocalStack?

We start it using Docker SDK for Rust

### Environment

```markdown
- OS: Debian 11, AMD 64
- LocalStack: 1.4.0
```

**Comment by chris-stetter** [comment]
I have experienced the same behaviour using Pulumi.

**Comment by chris-stetter** [comment]
I just did and I was still facing this error.

**Comment by bentsku** [comment]
Hello and thanks for your patience! We finally found the root cause of the issue, and the fix should be part of the `latest` image. Could you give it a try by running `docker pull localstack/localstack:latest`?
