### ISSUE TITLE
Issue with debugging JVM lambda methods

### ISSUE THREAD

**Issue by logicMark** [localstack/localstack#7788]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm trying to debug the localstack lambda function as mention in your docs at https://docs.localstack.cloud/user-guide/tools/lambda-tools/debugging/#debugging-jvm-lambdas

It suggests to add two options in the docker-compose.yml which are 
  
  LAMBDA_JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=*:5050
  LAMBDA_DOCKER_FLAGS=-p 127.0.0.1:5050:5050
  
 When followed the same approach as mentioned in your above doc link "debugging-jvm-lambdas" , it gives the below error in the docker logs
 
```
  <function cloudwatch at 0x7f6d5c634790>)
localstack_demo | 2023-03-02T20:13:57.650 DEBUG --- [   asgi_gw_2] plugin.manager             : loading plugin localstack.aws.provider:cloudwatch:default
localstack_demo | 2023-03-02T20:13:57.689 DEBUG --- [   asgi_gw_2] l.services.plugins         : checking service health cloudwatch:4566
localstack_demo | 2023-03-02T20:13:57.835  INFO --- [functhread40] localstack.utils.threads   : Thread run method <function LambdaExecutor.execute.<locals>.do_execute at 0x7f6d3f389990>(None) failed: Lambda process returned with error. Result: Unable to use shared archive.. Output:
localstack_demo | Picked up JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=*:5050
localstack_demo | An error has occurred while processing the shared archive file.
localstack_demo | Tool agent requires sharing to be disabled.
localstack_demo | Error occurred during initialization of VM Traceback (most recent call last):
localstack_demo |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 667, in run_lambda_executor
localstack_demo |     result, log_output = self.execute_in_container(
localstack_demo |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 1295, in execute_in_container
localstack_demo |     return DOCKER_CLIENT.start_container(
localstack_demo |   File "/opt/code/localstack/localstack/utils/container_utils/docker_sdk_client.py", line 473, in start_container
localstack_demo |     raise ContainerException(
localstack_demo | localstack.utils.container_utils.container_client.ContainerException: Docker container returned with exit code 1
localstack_demo |
localstack_demo | The above exception was the direct cause of the following exception:
localstack_demo |
localstack_demo | Traceback (most recent call last):
localstack_demo |   File "/opt/code/localstack/localstack/utils/threads.py", line 58, in run
localstack_demo |     result = self.func(self.params, **kwargs)
localstack_demo |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 484, in do_execute
localstack_demo |     return _run(func_arn=func_arn)
localstack_demo |   File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 183, in wrapped
localstack_demo |     raise e
localstack_demo |   File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 179, in wrapped
localstack_demo |     result = func(*args, **kwargs)
localstack_demo |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 471, in _run
localstack_demo |     raise e
localstack_demo |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 467, in _run
localstack_demo |     result = self._execute(lambda_function, inv_context)
localstack_demo |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 790, in _execute
localstack_demo |     result = self.run_lambda_executor(lambda_function=lambda_function, inv_context=inv_context)
localstack_demo |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 712, in run_lambda_executor
localstack_demo |     raise InvocationException(
localstack_demo | localstack.services.awslambda.lambda_executors.InvocationException: Lambda process returned with error. Result: Unable to use shared archive.. Output:
localstack_demo | Picked up JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=*:5050
localstack_demo | An error has occurred while processing the shared archive file.
localstack_demo | Tool agent requires sharing to be disabled.
localstack_demo | Error occurred during initialization of VM

```
 It does work normally without the options mentioned above, it is throwing the error only when i try to debug as mentioned in the article. docker image localstack/localstack:latest.
 
 
 

### Expected Behavior

It should hit the breakpoint and should work as mentioned at https://docs.localstack.cloud/user-guide/tools/lambda-tools/debugging/#debugging-jvm-lambdas

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    aws s3 mb s3://mybucket --endpoint-url=http://localhost:4566 --region us-east-1
    
### assign the notification configuration 

     aws s3api put-bucket-notification-configuration --endpoint-url=http://localhost:4566 --region us-east-1 --notification-configuration file://C:/Users/username/config.json --bucket mybucket
     
     config.json
     
     {
       "LambdaFunctionConfigurations": [
     {
      "Id": "s3eventlambda",
      "LambdaFunctionArn": "arn",
      "Events": ["s3:ObjectCreated:*"]
     }
    ]
    } 

    
Note, the setup works as exepected and invokes the lambda normally but the issue is with following debug approach followed in the mentioned article

### Environment

```markdown
- OS: docker env
- LocalStack:latest
```

### Anything else?

![image](https://user-images.githubusercontent.com/32538849/223624119-a51fcbb7-6645-4821-973a-e4d8b7f2ed82.png)

![image](https://user-images.githubusercontent.com/32538849/222545973-9f357d84-8a15-4124-ac20-343484d2f1a7.png)

_No response_

**Comment by albanf** [comment]
I worked around this issue by modifying the java lambda container to set `Xshare` to `off`:

Dockerfile:
```
FROM lambci/lambda:java8

ENTRYPOINT ["/usr/bin/java", "-XX:MaxHeapSize=2834432k", "-XX:MaxMetaspaceSize=163840k", "-XX:ReservedCodeCacheSize=81920k", "-XX:+UseSerialGC", "-Xshare:off", "-XX:-TieredCompilation", "-Djava.net.preferIPv4Stack=true", "-jar", "/var/runtime/lib/LambdaJavaRTEntry-1.0.jar"]
```
Then: `docker build -t lambci/lambda:java8 .`

This was tested with localstack 1.4.0

**Comment by joe4dev** [comment]
Hi @logicMark and @albanf 

To fix the following error related to `processing the shared archive file`:

```
localstack_demo | Picked up JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=*:5050
localstack_demo | An error has occurred while processing the shared archive file.
localstack_demo | Tool agent requires sharing to be disabled.
localstack_demo | Error occurred during initialization of VM
```

We need to set `-Xshare:off`.

For some reason, the default AWS entrypoint explicitly enables Xshare and takes precedence over `JAVA_TOOL_OPTIONS`. To force `-Xshare:off`, we can set the environment variable `_JAVA_OPTIONS` (an undocumented flag according to this [openjdk bug](https://bugs.openjdk.org/browse/JDK-4971166)). For example:

```bash
awslocal lambda create-function --function-name debugfunc \
    --zip-file fileb://java-handler.zip \
    --handler myindex.handler \
    --runtime java8.al2 \
    --timeout 150 \
    --role arn:aws:iam::000000000000:role/lambda-role \
    --environment '{"Variables": {"_JAVA_OPTIONS": "-Xshare:off -agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=0.0.0.0:5050"}}'
```


We just updated our documentation for JVM Lambda debugging accordingly: https://docs.localstack.cloud/user-guide/tools/lambda-tools/debugging/#debugging-jvm-lambdas

We are looking forward to hearing your feedback 🚀
