### ISSUE TITLE
bug: Lambda throws an exception when runtime gets upgraded to node18.x

### ISSUE THREAD

**Issue by Bohdan-Kalynovskyi** [localstack/localstack#7797]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The lambda errors with the following message when runtime is set to node18.x: 

`
{"__type": "InternalError", "message": "exception while calling lambda with unknown operation: the JSON object must be str, bytes or bytearray, not Response"}
`

### Expected Behavior

Lambda should output `Hello World`

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    I've installed localstack via pip, then ran `localstack start -d`. It prints `starting LocalStack in Docker mode 🐳 ` when starting :)
    
    I've also tried the latest docker container with the same result. 

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    - git clone https://github.com/kuros/blog-code.git
    - cd blog-code/terraform/fix-lambda-localstack
    - terraform init && terraform apply
    - curl the lambda, ensure it outputs `Hello World`
    - now change the runtime to node18.x, as in this PR: https://github.com/kuros/blog-code/pull/30/files
    - terraform apply
    - curl the lambda again
    - see the error

### Environment

- OS: MacOS Ventura 13.2.1 (22D68)
- LocalStack: 1.4.0

### Anything else?

I've got the same result running `awslocal lambda create-function ... --runtime nodejs18.x ...`

**Comment by dfangl** [comment]
Hi @Bohdan-Kalynovskyi !
Thank you for reporting this issue.
Can you please try setting `PROVIDER_OVERRIDE_LAMBDA=v2` and check if this fixes your issue?
If not, please share the logs of LocalStack with `DEBUG=1` set, so we can take a closer look.

**Comment by Bohdan-Kalynovskyi** [comment]
Hi @dfangl adding `PROVIDER_OVERRIDE_LAMBDA=v2` didn't change the output. Let me check for the logs...

**Comment by lauriv** [comment]
I've stumbled on the same issue and the troubleshooting led me to believe it's the same issue as https://github.com/localstack/localstack/issues/7527 

Adding the `PROVIDER_OVERRIDE_LAMBDA=asf` to docker-compose, restarting and redeploying the function made it work.

Initial error logs included for reference below.

`localstack_main             | 2023-05-10T14:29:26.286 ERROR --- [   asgi_gw_1] l.aws.handlers.logging     : exception during call chain: the JSON object must be str, bytes or bytearray, not Response
localstack_main             | 2023-05-10T14:29:26.287  INFO --- [   asgi_gw_1] localstack.request.http    : POST / => 500
localstack_main             | 2023-05-10T14:36:08.805  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS lambda.CreateFunction => 409 (ResourceConflictException)
localstack_main             | 2023-05-10T14:37:30.612  INFO --- [   asgi_gw_1] l.s.a.lambda_executors     : Running lambda: arn:aws:lambda:us-east-1:000000000000:function:localstack-lambda-url-example
localstack_main             | 2023-05-10T14:37:32.761  INFO --- [   asgi_gw_1] l.s.a.lambda_executors     : writing log to file '/var/lib/localstack/tmp/lambda_pvj2ns72.log'
localstack_main             | 2023-05-10T14:37:32.782  INFO --- [   asgi_gw_1] l.s.awslambda.lambda_api   : Error executing Lambda function arn:aws:lambda:us-east-1:000000000000:function:localstack-lambda-url-example: Lambda process returned with error. Result: . Output:
localstack_main             |  Traceback (most recent call last):
localstack_main             |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/docker/api/client.py", line 268, in _raise_for_status
localstack_main             |     response.raise_for_status()
localstack_main             |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
localstack_main             |     raise HTTPError(http_error_msg, response=self)
localstack_main             | requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.42/containers/create
localstack_main             | 
localstack_main             | During handling of the above exception, another exception occurred:
localstack_main             | 
localstack_main             | Traceback (most recent call last):
localstack_main             |   File "/opt/code/localstack/localstack/utils/container_utils/docker_sdk_client.py", line 565, in create_container
localstack_main             |     container = create_container()
localstack_main             |   File "/opt/code/localstack/localstack/utils/container_utils/docker_sdk_client.py", line 547, in create_container
localstack_main             |     return self.client().containers.create(
localstack_main             |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/docker/models/containers.py", line 870, in create
localstack_main             |     resp = self.client.api.create_container(**create_kwargs)
localstack_main             |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/docker/api/container.py", line 430, in create_container
localstack_main             |     return self.create_container_from_config(config, name)
localstack_main             |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/docker/api/container.py", line 441, in create_container_from_config
localstack_main             |     return self._result(res, True)
localstack_main             |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/docker/api/client.py", line 274, in _result
localstack_main             |     self._raise_for_status(response)
localstack_main             |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/docker/api/client.py", line 270, in _raise_for_status
localstack_main             |     raise create_api_error_from_http_exception(e)
localstack_main             |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
localstack_main             |     raise cls(e, response=response, explanation=explanation)
localstack_main             | docker.errors.ImageNotFound: 404 Client Error for http+docker://localhost/v1.42/containers/create: Not Found ("No such image: lambci/lambda:nodejs18.x")
localstack_main             | 
localstack_main             | During handling of the above exception, another exception occurred:
localstack_main             | 
localstack_main             | Traceback (most recent call last):
localstack_main             |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/docker/api/client.py", line 268, in _raise_for_status
localstack_main             |     response.raise_for_status()
localstack_main             |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
localstack_main             |     raise HTTPError(http_error_msg, response=self)
localstack_main             | requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.42/images/create?tag=nodejs18.x&fromImage=lambci%2Flambda
localstack_main             | 
localstack_main             | During handling of the above exception, another exception occurred:
localstack_main             | 
localstack_main             | Traceback (most recent call last):
localstack_main             |   File "/opt/code/localstack/localstack/utils/container_utils/docker_sdk_client.py", line 220, in pull_image
localstack_main             |     self.client().images.pull(docker_image)
localstack_main             |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/docker/models/images.py", line 446, in pull
localstack_main             |     pull_log = self.client.api.pull(
localstack_main             |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/docker/api/image.py", line 430, in pull
localstack_main             |     self._raise_for_status(response)
localstack_main             |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/docker/api/client.py", line 270, in _raise_for_status
localstack_main             |     raise create_api_error_from_http_exception(e)
localstack_main             |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
localstack_main             |     raise cls(e, response=response, explanation=explanation)
localstack_main             | docker.errors.NotFound: 404 Client Error for http+docker://localhost/v1.42/images/create?tag=nodejs18.x&fromImage=lambci%2Flambda: Not Found ("manifest for lambci/lambda:nodejs18.x not found: manifest unknown: manifest unknown")
localstack_main             | 
localstack_main             | The above exception was the direct cause of the following exception:
localstack_main             | 
localstack_main             | Traceback (most recent call last):
localstack_main             |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 667, in run_lambda_executor
localstack_main             |     result, log_output = self.execute_in_container(
localstack_main             |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 1276, in execute_in_container
localstack_main             |     container_id = DOCKER_CLIENT.create_container(
localstack_main             |   File "/opt/code/localstack/localstack/utils/container_utils/docker_sdk_client.py", line 567, in create_container
localstack_main             |     self.pull_image(image_name)
localstack_main             |   File "/opt/code/localstack/localstack/utils/container_utils/docker_sdk_client.py", line 224, in pull_image
localstack_main             |     raise ContainerException() from e
localstack_main             | localstack.utils.container_utils.container_client.ContainerException
localstack_main             | 
localstack_main             | The above exception was the direct cause of the following exception:
localstack_main             | 
localstack_main             | Traceback (most recent call last):
localstack_main             |   File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 459, in run_lambda
localstack_main             |     result = LAMBDA_EXECUTOR.execute(
localstack_main             |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 494, in execute
localstack_main             |     return do_execute()
localstack_main             |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 484, in do_execute
localstack_main             |     return _run(func_arn=func_arn)
localstack_main             |   File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 183, in wrapped
localstack_main             |     raise e
localstack_main             |   File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 179, in wrapped
localstack_main             |     result = func(*args, **kwargs)
localstack_main             |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 471, in _run
localstack_main             |     raise e
localstack_main             |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 467, in _run
localstack_main             |     result = self._execute(lambda_function, inv_context)
localstack_main             |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 790, in _execute
localstack_main             |     result = self.run_lambda_executor(lambda_function=lambda_function, inv_context=inv_context)
localstack_main             |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 712, in run_lambda_executor
localstack_main             |     raise InvocationException(
localstack_main             | localstack.services.awslambda.lambda_executors.InvocationException: Lambda process returned with error. Result: . Output:`

**Comment by dfangl** [comment]
Yes, that is expected.
The new lambda provider became default with 2.0 (please update if you haven't already, as there are some more bugfixes and improvements to the lambda provider).
We will not provide support for newer runtimes in the old lambda provider, as it is deprecated now, and we do not have a good control over the images.

**Comment by joe4dev** [comment]
@Bohdan-Kalynovskyi Please upgrade to [LocalStack v2](https://localstack.cloud/blog/2023-03-29-announcing-localstack-2.0-general-availability/), which comes with a completely [new Lambda implementation](https://discuss.localstack.cloud/t/new-lambda-implementation-in-localstack-2-0/258).

Your example works nicely with `nodejs18.x`:
<img width="1406" alt="Screenshot 2023-05-22 at 17 26 01" src="https://github.com/localstack/localstack/assets/8161292/040f89a6-b8ef-467f-b4eb-75c89a6dacc7">
