### ISSUE TITLE
feature request: Support emulating different versions of NeptuneDB

### ISSUE THREAD

**Issue by mjjames** [localstack/localstack#7798]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

NeptuneDB now has multiple versions which internally use different versions of Gremlin. To allow us to test our migration path & to allow our test suite to still work post migration we need to be able to indicate the version of NeptuneDB to emulate.

### 🧑‍💻 Implementation

Allow the Neptune Engine Version to be provided by an environment variable , 1.1.0.0, 1.1.1.0, 1.2.0.0 etc With a sensible default.

Then dependent on that value spin up the correct version of Gremlin as needed. 

NeptuneDB 1.2.0.2 = Gremlin 3.5.2
NeptuneDB 1.2.0.1 = Gremlin 3.5.2
NeptuneDB 1.2.0.0 = Gremlin 3.5.2
NeptuneDB 1.1.1.0 = Gremlin 3.5.2 
NeptuneDB 1.1.0.0 = Gremlin 3.4.11

Note we would only expect support of NeptuneDB versions that AWS still support as per https://docs.aws.amazon.com/neptune/latest/userguide/engine-releases.html

**Comment by steffyP** [comment]
Hi @mjjames, 

Neptune is now installing different versions of Gremlin, depending on the selected `Engine` version, as you have suggested. 
Please pull the `latest` LocalStack image and let us know if anything is not working as expected 🙏
