### ISSUE TITLE
Any plans for emulating Secrets Manager?

### ISSUE THREAD

**Issue by pingvinen** [localstack/localstack#780]
https://aws.amazon.com/secrets-manager

**Comment by pingvinen** [comment]
I have made the following which supports my use-case. https://github.com/skarpdev/hapi-aws-secrets-manager-emulator

I wrote it in nodejs and it includes a tiny (horrible) ui. Not sure if LocalStack can use this as a starting point.

**Comment by damacus** [comment]
I think this can be closed now?

Looks like it's implemented?.

**Comment by vergnes** [comment]
It is partly supported by moto-ext 1.3.7.1: only one secret at a time.

**Comment by duongpv7** [comment]
This already fixed in the latest version - some integration tests has been added in [#2223](https://github.com/localstack/localstack/pull/2223)
