### ISSUE TITLE
feature request: Add postgresql 15

### ISSUE THREAD

**Issue by davecardwell** [localstack/localstack#7802]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

PostgreSQL v15 for RDS was [released on Feb 28th](https://aws.amazon.com/about-aws/whats-new/2023/02/amazon-rds-postgresql-major-version-15/).

LocalStack currently only supports up to v13, falling back to v11 if you choose v15.

Can something be done to make a regular PostgreSQL release cadence more manageable for LocalStack?

### Anything else?

Separate request for v14: #7285

**Comment by thrau** [comment]
Closing the issue as fixed. Please open a new issue if problems with the solution surface.
