### ISSUE TITLE
feature request: add JavaScript - appsync resolvers

### ISSUE THREAD

**Issue by MarcelStranak** [localstack/localstack#7808]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Add JavaScript AppSync resolvers to the LocalStack.
Follow up on  #7172
Details: https://docs.aws.amazon.com/appsync/latest/devguide/resolver-reference-overview-js.html

**Comment by whummer** [comment]
Support for JavaScript AppSync resolvers has been added in the meantime. More detailed follow-up tickets to be created, as needed 👍
