### ISSUE TITLE
EKS failed when creating

### ISSUE THREAD

**Issue by techonelab** [localstack/localstack#7815]
is there any pre-requisite needed when creating eks? as per documentation it should be as simple as creating the cluster

but after couple of minutes waiting for the cluster to be created decided to check describe-cluster but getting below instead.

```
{
    "cluster": {
        "name": "demo-cluster",
        "arn": "arn:aws:eks:us-east-1:000000000000:cluster/demo-cluster",
        "createdAt": 1678193910.063,
        "version": "1.22",
        "roleArn": "r1",
        "resourcesVpcConfig": {
            "securityGroupIds": [],
            "endpointPublicAccess": true,
            "endpointPrivateAccess": false,
            "publicAccessCidrs": [
                "0.0.0.0/0"
            ]
        },
        "identity": {
            "oidc": {
                "issuer": "https://localhost.localstack.cloud/eks-oidc"
            }
        },
        "status": "FAILED",
        "platformVersion": "eks.5",
        "tags": {}
    }
}
```

no relevant error message can be found on localstack log
```
INFO --- [uncthread568] l.services.eks.k8s_utils   : Error creating cluster demo-cluster - deleting and retrying: Timeout while waiting for EKS startup...
```

**Comment by ackdav** [comment]
Hello @techonelab 

I just pulled the latest image and executed the commands from the [docs](https://docs.localstack.cloud/user-guide/aws/elastic-kubernetes-service/):
```
localstack start -d
awslocal eks create-cluster --name cluster1 --role-arn r1 --resources-vpc-config '{}'
# waited ~4 minutes
awslocal eks describe-cluster --name cluster1
```
and it successfully starts (`"status": "ACTIVE"`). 

Since EKS is a [pro service](https://docs.localstack.cloud/user-guide/aws/elastic-kubernetes-service/), the only requirement is a valid api_key. 
Could you pull the latest docker image and try again? Do you maybe have a custom kubernetes installation (`$HOME/.kube/config`)?

**Comment by techonelab** [comment]
```
`Since EKS is a [pro service](https://docs.localstack.cloud/user-guide/aws/elastic-kubernetes-service/), the only requirement is a valid api_key.
Could you pull the latest docker image and try again? Do you maybe have a custom kubernetes installation ($HOME/.kube/config)?`
```

yes I do have valid api_key
yes I do have running kind cluster, will delete and remove the config to check if will go through, thanks for this.

**Comment by techonelab** [comment]
just circling back on this, thanks for pointing at current .kube/config that was the root cause why I cannot create via localstack.
closing ticket

**Comment by anandabdvtlocalstack** [comment]
Hi All,

I am facing the same issue "deleting and retrying: Timeout while waiting for EKS startup" even after providing a valid Team license key.  It works fine in a computer where it is not behind corporate proxy. But when I try in my VDI desktop which is behind proxy it fails and gives timeout error mentioned earlier.

I tried starting localstack directly using "localstack start -d" (before this command had set the license key). Also using docker run comment. In both cases EKS cluster command fails.

Any pointers how to resolve this issue?

Thanks,
Ananda
