### ISSUE TITLE
Version/release history documentation?

### ISSUE THREAD

**Issue by jhovell** [localstack/localstack#782]
I was wondering if there is a place where the dates of releases that have occurred is documented. Possibly with release history.

I noticed 0.8.0 was pushed to Docker Hub a day ago, but 0.8.6 (I would guess a more recent version) is 2 months old:

https://hub.docker.com/r/localstack/localstack/tags/

I'm trying to find out if a commit was part of an older release or not but cannot find where this might be documented (either through github tags, github releases, website documentation, etc)

https://github.com/localstack/localstack/pull/416

Thanks!

**Comment by amcconnell** [comment]
I'd find that useful as well. In particular b/c my integration tests (that use the latest Docker image) are now failing with Cloudformation error:

com.amazonaws.services.cloudformation.model.AmazonCloudFormationException: The resource with the name requested already exists. (Service: AmazonCloudFormation; Status Code: 400; Error Code: AlreadyExists; Request ID: cd30caa4-f28e-4ac4-bdbb-d54c1d40ec20)

Worked yesterday.....

**Comment by whummer** [comment]
Hi, the dates of historical releases are not documented in the README (only in the Git history), but we're planning to always create Github releases (which do include the timestamps), moving forward. Thanks
