### ISSUE TITLE
feature request: custom ids for cognito via tags

### ISSUE THREAD

**Issue by thetrevdev** [localstack/localstack#7823]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Cognito should support custom ids via tagging similar to apigateway
https://docs.localstack.cloud/user-guide/aws/apigatewayv2/#aws-api-gateway-custom-id-via-tags

This should work for 
AWS::Cognito::UserPool
AWS::Cognito::UserPoolClient
AWS::Cognito::IdentityPool

This is important because cognito ids are used in many places and implementing things like SSO would prove extremely difficult

**Comment by whummer** [comment]
Hi @thetrevdev , thanks for reporting. We have now pushed a small change to enable specifying a custom ID for via a `_custom_id_` tag for Cognito user pools and identity pools. Please note that it doesn't work yet for user pool clients, as they do not currently support tagging via the API.

We have yet to update our docs, but when you get a chance, can you please pull the `latest` Docker image and give it a try? Looking forward to getting your feedback - in particular, does it work for you with the tags for user/identity pools, or are custom IDs for user pool clients also a strict requirement? Thanks!

**Comment by vt-rcheng** [comment]
I don't think this is working properly. I can create user pool with custom id fine, but it will not create user pool client with that custom id.

```
root@41d0964488d5:/etc/localstack/init/ready.d# awslocal cognito-idp list-user-pools --max-results 100
{
    "UserPools": [
        {
            "Id": "awakenpoolid",
            "Name": "awakenpoolname",
            "LambdaConfig": {},
            "LastModifiedDate": 1694988263.663275,
            "CreationDate": 1694988263.663277
        }
    ]
}
```
```
root@41d0964488d5:/etc/localstack/init/ready.d# awslocal cognito-idp list-user-pool-clients --user-pool-id awakenpoolid
{
    "UserPoolClients": []
}
```
```
root@41d0964488d5:/etc/localstack/init/ready.d# awslocal cognito-idp create-user-pool-client --user-pool-id awakenpoolid --client-name awakenpoolclient

An error occurred (ResourceNotFoundException) when calling the CreateUserPoolClient operation: Unable to create client for non-existing user pool awakenpoolid

```

**Comment by vt-rcheng** [comment]
nevermind, the custom id I set was improper, but it should have thrown an error instead

**Comment by serozhenka** [comment]
@whummer hi, is there still a possibility you add support for setting custom id when creating pool user client with boto3?

**Comment by whummer** [comment]
@vt-rcheng @serozhenka Thanks for the update. Please note that the custom user pool ID should have the format `<region>_<custom_pool_id>` (e.g., `us-east-2_myid123`). Can you please give it a try if that works? This is currently incorrect in our docs - we'll look into updating the docs shortly! Thanks

**Comment by serozhenka** [comment]
@whummer thanks for the follow up. Yes it does `_custom_id_`: `<region>_<custom_pool_id>` in `UserPoolTags` does  work when issuing `create_user_pool` operation. But my question was how to set a custom id when creating a user pool client (`create_user_pool_client` method). Thank you

**Comment by whummer** [comment]
Thanks for clarifying @serozhenka . The problem is that `create_user_pool_client(..)` does not support passing tags at this point, so our options are a bit limited. We could look into supporting custom tags when specifying a predefined format for the `ClientName` parameter, though (e.g., something like `ClientName="_custom_id_:myid123"`). Would that work? We'll look into that and will share an update shortly.. 👍 /cc @giograno

**Comment by serozhenka** [comment]
@whummer I guess it would work, but I am wondering if someone may already be dependant of the client name.

**Comment by giograno** [comment]
Hi @serozhenka, we implemented what @whummer suggested above. It should be available in the `latest` image soon. We also updated the [documentation](https://docs.localstack.cloud/user-guide/aws/cognito/). Feel free to have a look and report any additional issues. Thank you 🙏

**Comment by serozhenka** [comment]
@giograno thank you 🙌

**Comment by odiazjs** [comment]
@giograno has this been released yet? thanks in advance.

**Comment by giograno** [comment]
@odiazjs yes this has been released. You can pull the `latest` docker image.

**Comment by odiazjs** [comment]
@giograno is this the latest version for the docker image? 

`localstack:
        image: localstack/localstack-pro:2.3.0`
