### ISSUE TITLE
go lambda logger

### ISSUE THREAD

**Issue by jney** [localstack/localstack#783]
how can i log for go lambda ? or where can i see it ?
using `fmt.Printf` or `log.Printf` i don't see anything in docker logs.

**Comment by TheMacNerd** [comment]
Perhaps one of these links might solve your problems:

https://docs.aws.amazon.com/lambda/latest/dg/python-logging.html
https://docs.aws.amazon.com/lambda/latest/dg/java-logging.html
https://docs.aws.amazon.com/lambda/latest/dg/nodejs-prog-model-logging.html

**Comment by jney** [comment]
maybe my question should be formulate: how do i access to cloudwatch logs?
because using `console.log` in `node` doesn't give me any output either

**Comment by bnegrao** [comment]
I also can't find the log messages from my lambdas in golang using localstack.

**Comment by kirbyjs** [comment]
https://github.com/localstack/localstack/issues/1623#issuecomment-583226472 is potentially a work around and worked for me.

**Comment by whummer** [comment]
Thanks for reporting @jney @NickSiena @bnegrao @kirbyjs . Looks like this should be working in the `latest` version. Please report here if the problem persists. Thanks!
