### ISSUE TITLE
bug: S3 not respecting CORS with CDK ( using cdklocal )

### ISSUE THREAD

**Issue by ansnoussi** [localstack/localstack#7836]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Deploying an S3 Bucket with cors config using CDK to LocalStack creates the bucket, but doesn't add the cors config to it.

### Expected Behavior

Deploying an S3 Bucket with cors config using CDK to LocalStack should add the cors config to the created bucket.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

- bootstrap LocalStack with CDK : `cdklocal bootstrap aws://000000000000/eu-west-3`
- deploy an example stack to LocalStack containing an S3 bucket with cors, here's an example configuration I'm using: 
```typescript
    this.bucket = new s3.Bucket(this, 'Bucket', {
      bucketName: 'dev-storage-local',
      removalPolicy: cdk.RemovalPolicy.RETAIN,
      versioned: true,
      objectOwnership: s3.ObjectOwnership.BUCKET_OWNER_ENFORCED,
      cors: [
        {
          allowedOrigins: ['*'],
          allowedHeaders: ['*'],
          maxAge: 3000,
          allowedMethods: [s3.HttpMethods.GET, s3.HttpMethods.HEAD, s3.HttpMethods.PUT, s3.HttpMethods.POST],
        },
      ],
    });
```
- after deployment with `cdklocal` verify that the bucket was correctly created : `awslocal s3api list-buckets --region eu-west-3`
- try getting the cors config for the bucket in local : `awslocal s3api get-bucket-cors --bucket dev-storage-local --region eu-west-3` 
=> the above command returns this error message that the CORS configuration doesn't exist: 
```
An error occurred (NoSuchCORSConfiguration) when calling the GetBucketCors operation: The CORS configuration does not exist
```

### Environment

```markdown
- OS: macOS Ventura 13.1
- LocalStack: 1.4.0
```

**Comment by thrau** [comment]
thanks for reporting @ansnoussi . seems like our `AWS::S3:Bucket` cfn resource does not have the [`CorsConfiguration`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-cors.html) property implemented. maybe @pinzon can confirm /cc @bentsku

**Comment by pinzon** [comment]
@thrau The CFn model of the S3 bucket doesn't make any mention of the CorsConfiguration attribute, so it's safe to assume that the model doesn't use it. It's a relative easy fix so I'm leaving it to @deepak2431 who is eager to contribute to LocalStack.

**Comment by deepak2431** [comment]
> @thrau The CFn model of the S3 bucket doesn't make any mention of the CorsConfiguration attribute, so it's safe to assume that the model doesn't use it. It's a relative easy fix so I'm leaving it to @deepak2431 who is eager to contribute to LocalStack.

I made the PR for it here: https://github.com/localstack/localstack/pull/7866
You can have a look @pinzon
