### ISSUE TITLE
[pro] creating ec2 instance when using api key causes Docker Not Available errors

### ISSUE THREAD

**Issue by skyleguy** [localstack/localstack#7839]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am currently using docker to spin up localstack for me with the following command:

docker run --rm -it -e AWS_REGION=us-east-1 -p 4566:4566 -p 4510-4559:4510-4559 -e SKIP_SSL_CERT_DOWNLOAD=1 -e LOCALSTACK_API_KEY=my_api_key localstack/localstack-pro

then i have a small python script that uses boto3 to attempt to create 3 ec2s:

```
import boto3

session = boto3.session.Session()
ec2_client = session.resource(service_name="ec2", endpoint_url="http://localhost:4566")

def create_instances(instanceCount):
    for i in range(instanceCount):
        ec2_client.create_instances(
            ImageId="ami-054abbd8192f620ae",
            MinCount=1,
            MaxCount=1,
            InstanceType="t2.micro",
            KeyName="KeyPair1",
            TagSpecifications=[
                {
                    "ResourceType": "instance",
                    "Tags": [
                        {"Key": "AppName", "Value": "my-app-name"},
                        {"Key": "Name", "Value": "my-instance-name"},
                        {"Key": "logicalEnvironment", "Value": "dit"},
                        {"Key": "pattern", "Value": "springboot"},
                        {"Key": "ApplicationId", "Value": "my-app-id"},
                        {"Key": "PatternTag", "Value": "1.4.2"},
                        {"Key": "DeploymentType", "Value": "green"},
                        {"Key": "aws:autoscaling:groupName", "Value": "my-asg"},
                        {"Key": "IsLive", "Value": "yes"},
                    ],
                }
            ]
        )

create_instances(3)
```

when running this i get the error:

`botocore.exceptions.ClientError: An error occurred (InternalError) when calling the RunInstances operation (reached max retries: 4): exception while calling ec2.RunInstances: Docker not available`

The bizarre part of this is if i switch my image to the non-pro version of localstack: localstack/localstack and stop passing in my api key as an env variable to the docker run command it all works fine. 

AND THEN if i pass my api key as an env variable to the non pro version it actually starts erroring out for the same reason. regardless of the localstack pro/non-pro it seems to break when i pass in an api-key. all the other commands ive tried to run have succeeded (creating subnet, launch configuration, vpc) even the pro feature of creating an asg worked.

I have even tried just using pip to install the localstack packages and running `localstack daemons` but i get the same error from that setup as well

### Expected Behavior

I would expect that when using localstack/localstack-pro, passing in my api-key to the docker run command, and using my python script to create an ec2 results in the ec2 successfully being created.

### How are you starting LocalStack?

With a `docker run` command

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

docker run --rm -it -e AWS_REGION=us-east-1 -p 4566:4566 -p 4510-4559:4510-4559 -e SKIP_SSL_CERT_DOWNLOAD=1 -e LOCALSTACK_API_KEY=my-api-key localstack/localstack-pro

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    see script above

### Environment

```markdown
- OS: macOS Ventura 13.2.1, using M1 chip
- LocalStack version: tried on 1.4.0 and 1.4.1.dev
```

### Anything else?

I saw others recommend setting OVERRIDE_IN_DOCKER to true or making sure to toggle some settings in docker itself but none of those seem to have worked

**Comment by brianczapiga** [comment]
I'm not staff, but it looks like you did not mount the docker socket into the localstack-pro container.

`-v/var/run/docker.sock:/var/run/docker.sock`

The reason it works without the API key is because the non pro version is a mock interaction (does not call docker).

Also see `https://docs.localstack.cloud/user-guide/aws/elastic-compute-cloud/` for information on tagging a docker image for use with localstack.

**Comment by skyleguy** [comment]
I do believe that fixed my problem as its actually telling me the ami id im trying to use does not exist. Thank you!
