### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by owst** [localstack/localstack#784]
Hi, 

Do you have any plans for when the next release will be made?

Thanks,
Owen.

**Comment by engrun** [comment]
I was reading the docs about the JUnit5 extensions.  However, the Extension classes are not present in 0.1.13.  Since the docs are mentioning JUnit5 support, is it possible to release 0.1.14?

**Comment by whummer** [comment]
Thanks for reporting @owst @engrun . New version `0.1.14` of Java libs, and version `0.8.7` of LocalStack released.
