### ISSUE TITLE
bug: S3 presigned URL doesn't expire 

### ISSUE THREAD

**Issue by aloysiustany** [localstack/localstack#7840]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am generating a S3 presigned URL for PUT with `S3Presigner`. The generated presigned URL never expires.
Tested the same code against a real AWS S3 bucket, and it works as expected.

Similar issue reported here: https://github.com/localstack/localstack/issues/2493, but it is closed as resolved.

### Expected Behavior

 Expect a forbidden error when trying to upload a file after the pre-signed url have expired.

### How are you starting LocalStack?

Custom (please describe below)

### Steps To Reproduce

with testcontainer

### Environment

```markdown
- OS: MacOS
- LocalStack: 1.17.6
```

Update: Edited for clarity

**Comment by thrau** [comment]
hi @aloysiustany, could you please provide specific instructions on how to reproduce the issue? thanks

**Comment by bentsku** [comment]
Hi @aloysiustany, it seems there was an issue previously with `Expires`. Could you try against with the latest version of LocalStack, starting at `2.0.1`? Thanks!

**Comment by thrau** [comment]
Closing the issue as fixed. Please re-open a new issue if the problem resurfaces.
