### ISSUE TITLE
aws_s3 postgres extension, localstack edition

### ISSUE THREAD

**Issue by daringordon** [localstack/localstack#7849]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

I’m using the aws_s3 RDS extension to facilitate transfer between s3 and RDS/Aurora.  This utility is extremely useful. I believe that the LocalStack project should maintain an analogous solution for local or test environments running localstack and using Postgresql.  There is an open source, python-based stored procedure solution written about 2 years ago called [postgres-aws-s3](https://github.com/chimpler/postgres-aws-s3) and the project isn’t being maintained.  This may be the best option available and is worth considering fork-acquiring.  This extension covers all user-customers who are using Postgres for local/test and RDS/Aurora for production and work with s3 datasets in postgres.  Thoughts?

### 🧑‍💻 Implementation

Fork `postgres-aws-s3` , licensing appropriately

**Comment by dan-hook** [comment]
Our team needs this feature, and the lack of it is what's blocking us from getting localstack pro.

**Comment by whummer** [comment]
Thanks for reporting @daringordon @dan-hook . Just a quick heads-up that we have this feature in the pipeline - we'll share an update in the upcoming days.

**Comment by whummer** [comment]
Hi @daringordon @dan-hook, quick update - we have now added initial support for S3 extension functions in RDS Postgres. Can you please pull the `latest` Docker image and give it another try? Please keep us posted on how it goes.. Thanks!

**Comment by psoares** [comment]
Can we test with the non-pro version?

**Comment by psoares** [comment]
@daringordon I subscribed so I could try this out. I couldn't get past the point where I have to associate IAM roles with the database in order to allow exports and imports from S3. Here are the relevant parts of my setup in terraform:

```hcl
resource "aws_s3_bucket" "reference_data_store" {
  bucket = "my-bucket"
}

resource "aws_rds_cluster" "backend" {
  cluster_identifier                  = local.aurora_cluster_name
  engine                              = "aurora-postgresql"
  # [...]
}

resource "aws_rds_cluster_role_association" "rds_s3_read" {
  db_cluster_identifier = aws_rds_cluster.backend.id
  role_arn              = aws_iam_role.aurora_s3_import.arn
  feature_name          = "s3Import"
}

resource "aws_rds_cluster_role_association" "rds_s3_write" {
  db_cluster_identifier = aws_rds_cluster.backend.id
  role_arn              = aws_iam_role.aurora_s3_export.arn
  feature_name          = "s3Export"
}
# [...]
```

When I apply this with `tflocal apply ...`, I get:

```
╷
│ Error: creating RDS DB Cluster (aurora-cluster-serverlessv2-sandbox) IAM Role (arn:aws:iam::000000000000:role/aurora_s3_import) Association: InternalFailure: API action 'AddRoleToDBCluster' for service 'rds' not yet implemented or pro feature - check https://docs.localstack.cloud/user-guide/aws/feature-coverage for further information
│       status code: 501, request id: J2S9WQYSL7E3Y9TMA68UF3EF6IESLWDROFQRV5AESX0QQNYN1SC5
│
│   with aws_rds_cluster_role_association.rds_s3_read,
│   on iam.tf line 238, in resource "aws_rds_cluster_role_association" "rds_s3_read":
│  238: resource "aws_rds_cluster_role_association" "rds_s3_read" {
│
╵
╷
│ Error: creating RDS DB Cluster (aurora-cluster-serverlessv2-sandbox) IAM Role (arn:aws:iam::000000000000:role/aurora_s3_export) Association: InternalFailure: API action 'AddRoleToDBCluster' for service 'rds' not yet implemented or pro feature - check https://docs.localstack.cloud/user-guide/aws/feature-coverage for further information
```

I think the feature needs the `AddRoleToDBCluster` API call to be implemented as well.

**Comment by whummer** [comment]
Thanks for the pointer @psoares . Indeed it looks like we have support for `add_role_to_db_instance`, but `add_role_to_db_cluster` is still missing. We'll make sure to add that shortly!

**Comment by whummer** [comment]
Hi @psoares , quick update - we have now pushed a few enhancements to increase parity with AWS for this feature (in particular support for `add_role_to_db_cluster`, as well as a few other enhancements). When you get a chance, can you please pull the `latest` Docker image and try again? Please keep us posted on how it goes.. Thanks!

**Comment by whummer** [comment]
Closing as resolved - please do let us know if there are any questions or issues. Thanks

**Comment by psoares** [comment]
@whummer I'm trying to test, but my stack still has some rds unimplemented features. e.g. rds subnet groups crash with errors like:

```
│ Error: reading RDS DB Subnet Group (rds-subnet-group-1): InternalFailure: API for service 'rds' not yet implemented or pro feature - please check https://docs.localstack.cloud/references/coverage/ for further information
│       status code: 501, request id: 8APHKNWC1W3GEYBTVOSM7YYQIRIO80BIUJ94FEL46Z2R2LJ4N2BP
│
│   with aws_db_subnet_group.rds,
│   on vpc.tf line 128, in resource "aws_db_subnet_group" "rds":
│  128: resource "aws_db_subnet_group" "rds" {
```

**Comment by psoares** [comment]
@whummer I can connect to the database and I see the aws_commons, aws_lambda, and aws_s3 packages.
Unfortunately, I'm hitting an S3 issue that prevents me to upload files to S3, so I couldn't test reading data through the aws_s3 package.

This may be a known issue, but when I do...
`awslocal s3 cp afile.txt s3://my-bucket/afile.txt` 
... I get:

```
upload failed: afile.txt to s3://my-bucket/afile.txt An error occurred (InternalError) when calling the PutObject operation (reached max retries: 2): exception while calling s3.PutObject: 'NoneType' object has no attribute 'convert_dict_to_tags_input'
```
