### ISSUE TITLE
feature request: add dark mode

### ISSUE THREAD

**Issue by Shoaib19** [localstack/localstack#7853]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Add dark mode theme for web users.

**Comment by whummer** [comment]
Hi @Shoaib19 , thanks for reporting. This has been added in the meantime - please make sure to hard-refresh the page https://app.localstack.cloud 

![image](https://user-images.githubusercontent.com/2807888/226432500-ca388610-734d-4778-878f-138ffcf46678.png)

Looking forward to getting your feedback.

**Comment by Shoaib19** [comment]
great, thats big relief to eyes.
can you add dark theme for documentation pages as well

[documentation](https://docs.localstack.cloud/overview/)
as I see entire site is on dark mode but when user goes to documentation he see bright white page.

**Comment by thrau** [comment]
I migrated the issue to the docs issue tracker https://github.com/localstack/docs/issues/535
