### ISSUE TITLE
feature request: Provide support for additional AWS Timestream functions

### ISSUE THREAD

**Issue by yumarg** [localstack/localstack#7867]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Hi, my team has an immediate use case for specific AWS Timestream functions, but it appears that some functions are currently not supported in LocalStack Pro.

Here is the list of functions we use in our queries:
1. `create_time_series(time, measure_value)`
2. `from_milliseconds(time)`
3. `to_milliseconds(time)`
4. `sequence(start, stop, step)`
5. `sum(x)`
6. `min(x)`
7. `max(x)`
8. `interpolate_fill(timeseries, array[timestamp], double)`
9. `unnest(timeseries)`
10. `cross join`

It is not clear from https://docs.localstack.cloud/user-guide/aws/timestream/#date--time-functions which ones from the above list are already supported, but we have observed the following error suggesting that at least `sequence` is not supported: `syntax error at or near the "h"` when the `sequence` step is `1h`

**Comment by yumarg** [comment]
Hi LocalStack team, is there any update on this? My team is not able to make progress on LocalStack integration because not all of the AWS Timestream functions we need is currently supported in LocalStack Pro. Thank you!

**Comment by ackdav** [comment]
Hello @yumarg - thank you for raising this. Unfortunately, Timestream is still under active development and there are still gaps in terms of parity.

To triage this a bit - first, let's create a dummy example:
```
awslocal timestream-write create-database --database-name db1
awslocal timestream-write create-table --database-name db1 --table-name table1
awslocal timestream-write write-records --database-name db1 --table-name table1 --common-attributes '{"Dimensions":[{"Name":"region","Value":"us-east-1","DimensionValueType":"VARCHAR"}],"MeasureName":"cpu","MeasureValueType":"DOUBLE","TimeUnit":"SECONDS"}' --records='[{"MeasureValue": "1", "Time": "1"}]'
awslocal timestream-write write-records --database-name db1 --table-name table1 --common-attributes '{"Dimensions":[{"Name":"region","Value":"us-east-1","DimensionValueType":"VARCHAR"}],"MeasureName":"cpu","MeasureValueType":"DOUBLE","TimeUnit":"SECONDS"}' --records='[{"MeasureValue": "10", "Time": "2"}]'
```

okay, so for each of your functions, I'll create a sample - some will be using the dummy example, some won't. I execute them all using `awslocal timestream-query query --query-string "QUERY"`. If you use the functions significantly different, let me know!

1. create_time_series(time, measure_value)
`SELECT CREATE_TIME_SERIES(time, measure_value::double) as cpu FROM db1.table1 WHERE measure_name='cpu'`
works

2. from_milliseconds(time)
`SELECT from_milliseconds(1)`
does not work -> should be doable, as it is a similar approach as the other supported [time conversions](https://docs.localstack.cloud/user-guide/aws/timestream/#date--time-functions)

3. to_milliseconds(time)
`SELECT to_milliseconds(TIMESTAMP '2022-06-17 17:44:43.771000000')`
does not work -> same as above

4. sequence(start, stop, step)
`SELECT sequence(1,10,2)`
does not work -> I'm guessing this is relatively easy as we have quite similar functions available.

5. sum(x)
`SELECT SUM(measure_value::double) as cpu FROM db1.table1`
works

6. min(x)
`SELECT MIN(measure_value::double) as cpu FROM db1.table1`
works

7. max(x)
`SELECT MAX(measure_value::double) as cpu FROM db1.table1`
works

8. interpolate_fill(timeseries, array[timestamp], double)
`SELECT interpolate_fill(CREATE_TIME_SERIES(time, measure_value::double),0) as cpu FROM db1.table1`
does not work (function unavailable) -> needs investigation

9. unnest(timeseries)
`SELECT unnest(CREATE_TIME_SERIES(time, measure_value::double)) as cpu FROM db1.table1 WHERE measure_name='cpu'`
does not work (function unavailable) -> needs investigation

10. cross join
`SELECT * FROM db1.table1 as t1 cross join table1 as t2`
does execute, provides results but raises an exception -> needs a better example to test.

I'm aware that some of this usage isn't really correct (especially `8.`-`10.`) - my goal was to test whether the function fires and not get caught in syntax errors.

At this point I think cases `2.`-`4.` should be reasonably straight forward (will do next), but `8.-`10.` needs a bit more investigation.
We will keep you updated!

**Comment by ackdav** [comment]
Hello @yumarg - apologies for the delay. We've been restructuring timestream in the background - it is now in a state where we can make iterate and improve parity much quicker. From the above mentioned functions `1-7` should now be working, hopefully following up with the rest shortly. Please note that some functions are overloaded (e.g. `sequence` can be called with many different parameter combinations) - there might be still some parity gaps there.
I will follow up again once we have an initial implementation of all functions.

**Comment by yumarg** [comment]
Thank you @ackdav for the detailed update!

**Comment by whummer** [comment]
Hi @yumarg , again apologies for the delay. We have added a couple more enhancements for Timestream, and also added support for `interpolate_fill`. These changes are now available if you pull the `latest` Docker image. 

We are going to tackle `unnest` and `cross join` next - we'll keep you posted here once we have more updates. Thanks for your support in resolving this!

**Comment by whummer** [comment]
Hi @yumarg , another quick update - we have now added support for the `UNNEST(..)` function, and also further enhanced the parity around the interpolation functions (`interpolate_linear`/`interpolate_fiill`). We are now working on further testing around support for `cross join` queries. 

When you get a chance, can you please pull the `latest` Docker image and give it a try if the query functionality supports your use cases so far? We'll provide an update on the next enhancements here soon.. Thanks!

**Comment by yumarg** [comment]
Hi @whummer, thank you and the LocalStack team for working on the requested query functionality! I have been trying to verify that all our use cases are supported, and I'm running into some issues but I'm not able to verify if it is due to missing functionality, bugs, or misconfiguration on my end. I have reached out to LocalStack Pro Support in Slack, but I'd also like to ask some general questions here - would appreciate your help in answering! Thank you!

1) When using the write_records API, I don't see a difference when setting `Time` to epoch seconds and specifying `TimeUnit` as `NANOSECONDS` vs specifying `TimeUnit` as something else. Is that intentional?
2) I have observed errors when I try to specify `str(time.time_ns())` as `Time` with `TimeUnit`=`NANOSECONDS` even though this doesn't give me errors when writing to AWS Timestream. Is this a bug?
3) When my query selects all columns, I do not see columns that should have been present after writing a record with `MeasureValueType`=`MULTI` and specifying `MeasureValues` with different names. Is this a bug?
4) Does LocalStack Pro support specifying the table schema?
5) Does LocalStack Pro support `get_paginator('query')`?

**Comment by whummer** [comment]
Hi @yumarg , as also discussed in the Slack channel, most of the points above should now be resolved. When you get a chance, can you please pull the `latest` Docker image and give it another try? Looking forward to getting your feedback.. Thanks!
