### ISSUE TITLE
bug: describe-image-attribute always return LaunchPermissions attributes

### ISSUE THREAD

**Issue by vbauchart** [localstack/localstack#7884]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The following command should get the productCodes for an AMI, but it always return the LaunchPermissions attribute, whatever the requested attribute

example:
```
$ aws ec2 describe-image-attribute --attribute productCodes --image-id ami-d2f06e32
{
    "ImageId": "ami-d2f06e32",
    "LaunchPermissions": []
}
```

### Expected Behavior

Result on a real AWS account :

```
$ aws ec2 describe-image-attribute --attribute productCodes --image-id ami-06e7851954c462359
{
    "ImageId": "ami-07e7851944c462357",
    "ProductCodes": []
}

```

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run -e SKIP_SSL_CERT_DOWNLOAD=1 -d --name localstack localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal ec2 describe-image-attribute --attribute productCodes --image-id ami-ekswin

### Environment

```markdown
- OS: Ubuntu 
- Docker version 23.0.1
- LocalStack version: 1.3.2.dev
```

**Comment by viren-nadkarni** [comment]
<https://github.com/localstack/localstack/labels/good%20first%20issue> hint: Add `productCode` to `moto.ec2.responses.amis.DESCRIBE_IMAGE_ATTRIBUTES_RESPONSE`

**Comment by tushar5526** [comment]
Hey, I would like to try this if its not picked internally ?

**Comment by tushar5526** [comment]
> DESCRIBE_IMAGE_ATTRIBUTES_RESPONSE

I checked more on this and found `productCode` missing from `moto` 's response. Is this to be fixed in `moto` project ?

**Comment by viren-nadkarni** [comment]
@tushar5526 correct. Please leave a note when the Moto PR is merged and I'll take care of bumping it here

**Comment by viren-nadkarni** [comment]
@tushar5526: Thanks, I'll bump moto so we can have this fix in LocalStack!

**Comment by viren-nadkarni** [comment]
Fixed with https://github.com/localstack/localstack/pull/8270
