### ISSUE TITLE
DynamoDB hangs on PutItem on non existent table

### ISSUE THREAD

**Issue by snypelife** [localstack/localstack#789]
# Scenario
Attempt to put item into a non existent table

## Expected
An `ResourceNotFoundException` would be returned back, much like performing an UpdateItem on a table that doesn't exist.
```
aws --endpoint-url=http://localhost:4569 dynamodb update-item --table-name gdffg --key='{}'

An error occurred (ResourceNotFoundException) when calling the UpdateItem operation: Cannot do operations on a non-existent table
```

## Actual
Call hangs and does not return anything. You can see in the containers logs that the error occurred, it just doesn't get returned it seems.

```
2018-05-28T18:26:22:ERROR:localstack.services.generic_proxy: Error forwarding request: An error occurred (ResourceNotFoundException) when calling the DescribeTable operation: Cannot do operations on a non-existent table Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 181, in forward
    path=path, data=data, headers=forward_headers)
  File "/opt/code/localstack/localstack/services/dynamodb/dynamodb_listener.py", line 44, in forward_request
    ProxyListenerDynamoDB.thread_local.existing_item = find_existing_item(data)
  File "/opt/code/localstack/localstack/services/dynamodb/dynamodb_listener.py", line 208, in find_existing_item
    schema = ddb_client.describe_table(TableName=table_name)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/client.py", line 612, in _make_api_call
    raise error_class(parsed_response, operation_name)
ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the DescribeTable operation: Cannot do operations on a non-existent table
```

**Comment by snypelife** [comment]
@nityanandagohain I'm gonna say open a new issue rather than jumping on this one. That way it can be tracked appropriately/independently.

**Comment by desniaak** [comment]
@snypelife have you solve this issue? I am getting the same error here and this only happens when trying to putItem. query or describe table works as expected

**Comment by snypelife** [comment]
Unfortunately, I haven't pinpointed the exact cause the of the hanging call.

It looks like it might be related to the `updated_item = find_existing_item(data)` call in `dynamodb_listener.py`. The update-item call has that lookup, whereas the put-item does not.

I've tried adding some integration tests for this use case explicitly, but haven't gotten them passing yet (hence my uncertainty of the root cause). 

If I manage to figure it out though, I'll push up a PR.

**Comment by whummer** [comment]
Thanks for reporting @snypelife . This should be fixed in the latest version. 
```
$ aws --endpoint-url=http://localhost:4569 dynamodb update-item --table-name gdffg --key='{}'

An error occurred (ResourceNotFoundException) when calling the UpdateItem operation: Cannot do operations on a non-existent table
```
Closing this issue - please reopen if the problem persists. Thanks

**Comment by dominicbarnes** [comment]
I came across this issue after hitting this behavior tonight.

Even after updating to the latest version, it looks like the same problem affects "PutItem". Looking back over the issue, the name says "PutItem", but the description and fix both reference "UpdateItem", so I'm unsure if I should create a new issue or re-open this one.

Can the same fix made for "UpdateItem" also be given to "PutItem"?

**Comment by snypelife** [comment]
The original issue was for `PutItem` into a non existent table. 

The reference to `UpdateItem` was just for example of how `PutItem` should handle the case.

**Comment by whummer** [comment]
Thanks @snypelife @dominicbarnes - this should now also be fixed for the `PutItem` case.
