### ISSUE TITLE
bug: InternalFailure: API action 'RequestCertificate' for service 'acm' not yet implemented or pro feature

### ISSUE THREAD

**Issue by davecardwell** [localstack/localstack#7891]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After updating to the `:latest` version of `localstack-pro` I’m suddenly unable to call ACM’s `RequestCertificate`:

> An error occurred (InternalFailure) when calling the RequestCertificate operation: API action 'RequestCertificate' for service 'acm' not yet implemented or pro feature - check https://docs.localstack.cloud/user-guide/aws/feature-coverage for further information

### Expected Behavior

No error.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    # using https://github.com/localstack/localstack/blob/master/docker-compose-pro.yml
    docker compose up

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal acm request-certificate --domain-name example.com

### Environment

```markdown
OS: macOS 13.2.1

localstack@localstack:/opt/code/localstack$ bin/localstack status
┌─────────────────┬──────────────────────────────────────────────────────────┐
│ Runtime version │ 1.4.1.dev                                                │
│ Docker image    │ tag: latest, id: 70e6f5e5f8eb, 📆 2023-03-16T13:24:57    │
│ Runtime status  │ ✔ running (name: "vault-localstack-1", IP: 192.168.48.3) │
└─────────────────┴──────────────────────────────────────────────────────────┘
```

**Comment by thrau** [comment]
hey dave @davecardwell. sorry i can't seem to reproduce your issue.

running
```
docker run --rm -it --name localstack-main -e DEBUG=1 -e LOCALSTACK_API_KEY=... -p 4566:4566 localstack/localstack
```

and then `awslocal acm request-certificate --domain-name example.com` works just fine:

```
2023-03-17T17:24:29.611 DEBUG --- [   asgi_gw_0] l.services.plugins         : checking service health acm:4566
2023-03-17T17:24:29.772  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS acm.RequestCertificate => 200
```

could you please start localstack with `DEBUG=1` and provide the full log output?

**Comment by davecardwell** [comment]
Thank you for checking in on this for me, @thrau. I cleared out my Docker image cache and re-tried with the latest `:latest` and everything is back to working again.
