### ISSUE TITLE
bug: SQS Lambda Listener, message attributes are getting passed in body attribute of SQSEvent of lambda handler

### ISSUE THREAD

**Issue by bajajyog** [localstack/localstack#7897]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

TestContainer Local stack version **1.4.0**

**Input msg to SQS:-**
{
  "Records": [
    {
      "messageId": "d9144555-9a4f-4ec3-99a0-34ce359b4b54",
      "receiptHandle": "13e7f7851d2eaa5c01f208ebadbf1e72==",
      "body": "{ \"traceId\":\"8908118f-06e6-460f-8297-1be74d4ff03f\"},
      "attributes": {
        "ApproximateReceiveCount": "1",
        "SentTimestamp": "1601975706495",
        "SenderId": "AROAIFU437PVZ5L2J53F5",
        "ApproximateFirstReceiveTimestamp": "1601975706499"
      },
      "messageAttributes": {
      },
      "md5OfBody": "13e7f7851d2eaa5c01f208ebadbf1e72",
      "eventSource": "aws:sqs",
      "eventSourceARN": "arn:aws:sqs:eu-central-1:123456789012:TestLambda",
      "awsRegion": "eu-central-1"
    }
  ]
}

**Message received at Lambda Handler for SQSEvent body attribute**

:{"records":[{"messageId":"d9144555-9a4f-4ec3-99a0-34ce359b4b54","receiptHandle":"13e7f7851d2eaa5c01f208ebadbf1e72==","body":"{\n  \"traceId\":\"8908118f-06e6-460f-8297-1be74d4ff03f\"

### Expected Behavior

**Expected Result for SQSEvent Body attribute at java lambda handler**
****
"{\n  \"traceId\":\"8908118f-06e6-460f-8297-1be74d4ff03f\"

### How are you starting LocalStack?

Custom (please describe below)

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    LocalStack localstack=new LocalStackContainer().withServices(Service.LAMBDA, Service.SQS)
                            .withEnv("DEFAULT_REGION", Region.US_EAST_1.toString())
                            .withNetwork(Network.SHARED)
                            .withNetworkAliases(localstackNetworkAlias)
                            .withEnv("LAMBDA_DOCKER_NETWORK", ((Network.NetworkImpl) Network.SHARED).getName())
                            .withEnv("SQS_DOCKER_NETWORK", ((Network.NetworkImpl) Network.SHARED).getName())
                            .withFileSystemBind(
                                    new File("target/").getPath(), "/opt/code/localstack/target", BindMode.READ_ONLY);
localstack.start();

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

   **Message Sent to SQS:-**
**localStack.execInContainer**
                ("awslocal",
                        "sqs", "send-message", "--queue-url",
                        "http://127.0.0.1:4566/000000000000/note-queue", "--message-body", messageJson);

### Environment

```markdown
- OS:1.4.0
- LocalStack:Test Container
--Language :- Java 11
```

**Comment by thrau** [comment]
hey @bajajyog, i wrote an integration test for this in #7900, and unfortunately cannot reproduce the behavior with the latest docker image.

could you please give `latest` a try and double check whether the message attributes are really the issue?

i noticed that you didn't post the entire message from the lambda. all i can see is:

:{"records":[{"messageId":"d9144555-9a4f-4ec3-99a0-34ce359b4b54","receiptHandle":"13e7f7851d2eaa5c01f208ebadbf1e72==","body":"{\n "traceId":"8908118f-06e6-460f-8297-1be74d4ff03f"

the rest of the payload is missing from your logs. could you please post the entire payload so we can check the difference? the integration test shows that the attributes are received in the lambda correctly, so i don't know why it shouldn't show up in your lambda.

if it still doesn't work with latest, i would need a minimal reproducible example so i can reproduce the issue. thanks!

**Comment by bajajyog** [comment]
here is the complete SQS message received at lambda handler. Bolded json is issue. 

{Records: [{messageId: 283d76f0-4dec-4a64-8d08-aacc7627cfec,receiptHandle: MmMzNzY0YzQtYmZhMy00Mzk4LWI1NDQtZGY0Y2M2MmVjMmFkIGFybjphd3M6c3FzOnVzLWVhc3QtMTowMDAwMDAwMDAwMDA6bm90ZS1xdWV1ZSAyODNkNzZmMC00ZGVjLTRhNjQtOGQwOC1hYWNjNzYyN2NmZWMgMTY3OTA3Mjk0Mi4yNzg0MDg1,eventSourceARN: arn:aws:sqs:us-east-1:000000000000:note-queue,eventSource: aws:sqs,awsRegion: us-east-1,**body: {"records":[{"messageId":"d9144555-9a4f-4ec3-99a0-34ce359b4b54","receiptHandle":"13e7f7851d2eaa5c01f208ebadbf1e72==**","body":"{\n  \"traceId\":\"8908118f-06e6-460f-8297-1be74d4ff03f\",\n  \"xxx\":\"yyyy\",\n  \"zzz\":\"rrr-sdt\",\n  \"occurredOn\":\"2021-08-15T09:00:09.266138-05:00\",\n  \"ccc\":{\n    \"c\":\"abc\",\n    \"id\":\"6a74d77a\"\n  },\n  \"events\":[\n    {\n      \"type\":\"CREATED\",\n      \"r\":\"N8CD#e89c46c2#2021-04-01#FE0000-005#O#0025\",\n      \"ri\":\"li\",\n      \"body\":{\n        \"message\":\"John's Note 1\",\n        \"user\":\"john\",\n        \"status\": \"ACTIVE\"\n      }\n    }\n  ]\n}","md5OfBody":"13e7f7851d2eaa5c01f208ebadbf1e72","eventSourceArn":"arn:aws:sqs:eu-central-1:123456789012:TestLambda","eventSource":"aws:sqs","awsRegion":"eu-central-1","attributes":{"ApproximateReceiveCount":"1","SentTimestamp":"1601975706495","SenderId":"AROAIFU437PVZ5L2J53F5","ApproximateFirstReceiveTimestamp":"1601975706499"},"messageAttributes":{}}]},md5OfBody: 9bfcd1b4133c9989e0485a8da3b81511,attributes: {SenderId=000000000000, SentTimestamp=1679072941383, ApproximateReceiveCount=1, ApproximateFirstReceiveTimestamp=1679072942278},messageAttributes: {}}]}

**Comment by thrau** [comment]
to me this looks like the input is already faulty json. could you please share the exact `MessageBody` data of your `SendMessage` call?

**Comment by bajajyog** [comment]
I buildup a minimum  code base to reproduce the issue. Please run Junit test handleRequest_simple_success in class SQSComponenetTest. Search for this msg in console logs :- "traceId is marked non-null but is null". I am logging the sqs event and you can see that body json is not coming fine. . Please advise, if I am doing some step wrong way.. I also checked with latest local  stack docker image, issue is reproducible. I tested with AWS lambda base image and  it works fine.

Here the GitHub code repo url :- https://github.com/bajajyog/spring-lambda-localstack.git

**Comment by bajajyog** [comment]
the issue  is fixed. Need to pass message body instead of SQS event.
