### ISSUE TITLE
Improving the web dashboard

### ISSUE THREAD

**Issue by crash7** [localstack/localstack#791]
Hi there!

I've been using the docker image for the last few days and I would love to add more features to the web dashboard (like checking QUEUE items or last sent emails) but before start working on that, I would like to know if there are existing efforts/ideas/roadmap regarding this feature.

Thanks!

cc @whummer who seems to be pretty active here 😄

**Comment by whummer** [comment]
Hi @crash7 , no immediate plans to extend the dashboard right now, but would love to accept pull requests with additional features!! Thanks

**Comment by crash7** [comment]
@whummer excellent! any problem if I drop angular in favor of react? That `"angular": "1.3.12"` is killing me :stuck_out_tongue:

**Comment by whummer** [comment]
> any problem if I drop angular in favor of react? 

Sounds like a pretty involved change :) , but please go ahead - no strong feelings against it. Thanks for taking up this task!

**Comment by crash7** [comment]
@whummer hi! probably this can go in a different issue, but any idea how I can record/get the sent messages by SES? Same for SNS but I guess that he proxy-listener is going to help checking that.
For most of the information I can use the AWS API directly, but there are some pieces that aren't exposed through there.
Thanks again!

**Comment by pingvinen** [comment]
Any progress on this @crash7 ?

I would really love to see messages from SNS and SES :)

**Comment by whummer** [comment]
> any idea how I can record/get the sent messages by SES

@crash7 Were you able to create a proxy listener to intercept the SES messages? Any updates on the new UI features?
