### ISSUE TITLE
bug:  Lambda function not triggering

### ISSUE THREAD

**Issue by channel-dante** [localstack/localstack#7918]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If I map only one lambda function to the DB table stream, it works fine. When two or more lambdas are linked to a stream, the lambdas are not called randomly. Looking at the log inside the docker container, there is no error, but it is not running. If you register the lambda function one by one, it works normally. Also, it is working normally in the aws environment. mapping multiple lambda functions to one stream also doesn't work, and mapping lambda functions to multiple table streams doesn't work either.

### Expected Behavior

works normally even if there are more than two stream and lambda mappings.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

```
	aws lambda create-event-source-mapping --function-name test-lambda1 \
		--batch-size 150 --starting-position LATEST \
		--event-source-arn $(shell aws dynamodb describe-table --table-name table_name --region ap-northeast-2 --endpoint-url http://localhost:4566 --query 'Table'.'LatestStreamArn') \
		--maximum-batching-window-in-seconds 60 \
		--region ap-northeast-2 \
		--output table \
		--endpoint-url http://localhost:4566

	aws lambda create-event-source-mapping --function-name test-lambda2 \
		--batch-size 150 --starting-position LATEST \
		--event-source-arn $(shell aws dynamodb describe-table --table-name table_name --region ap-northeast-2 --endpoint-url http://localhost:4566 --query 'Table'.'LatestStreamArn') \
		--maximum-batching-window-in-seconds 60 \
		--region ap-northeast-2 \
		--output table \
		--endpoint-url http://localhost:4566
```

### Environment

```markdown
- OS: Ventura 13.0.1 (Apple M1 Pro)
- LocalStack: latest
```

**Comment by joe4dev** [comment]
@channel-dante It's worth giving our new Lambda event source mapping implementation a try 🚀 

Check out our new Lambda event source mapping (ESM) implementation in [LocalStack v4](https://blog.localstack.cloud/announcing-localstack-40-general-availability/) offering better functional and non-functional support for ESM 🚀 . The behavioral coverage documentation provides more details for your use case https://docs.localstack.cloud/user-guide/aws/lambda/#lambda-event-source-mappings

Feel free to open another issue or share your feedback if you experience any challenges👂
