### ISSUE TITLE
DockerHub Tag Versioning

### ISSUE THREAD

**Issue by davidgoate** [localstack/localstack#792]
Hi there, firstly thanks for the awesome project.

I have a concern about the way version tags on Dockerhub are being managed. At the time of writing https://hub.docker.com/r/localstack/localstack/tags/ has tags like:

Tag Name|Compressed Size|Last Updated
--- | --- | ---
latest|504 MB|6 days ago
0.8.0|570 MB|7 days ago
0.8.6|505 MB|2 months ago

The particular issues I'm concerned with are:

1. 0.8.0  seems to be "newer" than 0.8.6
1. latest is the "newest" (as expected) but there is no associated tag with 0.8.0 being the closest by date.

I'd prefer not to rely on "latest" but equally the tags don't appear to be following a regular semver style convention given 0.8.0 seems to be newer than 0.8.6 and latest is newer than all with no associated tag version such as a 0.8.7, for example.

Thanks in advance for your support.

**Comment by whummer** [comment]
Thanks for reporting @davidgoate . The `0.8.0` tag has recently been pushed manually by mistake, hence the updated timestamp. We'll make sure that this doesn't happen again in the future.
