### ISSUE TITLE
Lambda - Nodejs 8.10

### ISSUE THREAD

**Issue by benjamin-halter** [localstack/localstack#794]
I'm unable to successfully get Node.js 8.10 to execute through API Gateway.

I'm using the stock example from Lambda:
```
exports.handler = async (event) => {
    // TODO implement
    return 'Hello from Lambda!'
};
```
However results in: 
```
File "/opt/code/localstack/localstack/services/apigateway/apigateway_listener.py", line 224, in forward_request
response.status_code = int(parsed_result.get('statusCode', 200))
AttributeError: 'unicode' object has no attribute 'get'
```
If I pass a full object though: `{ statusCode: 200, body: 'Hello from Lambda!' }` it works fine. 

Am I missing something regarding getting it setup to better emulate AWS?

**Comment by whummer** [comment]
Closing as outdated - should have been fixed in the meantime. Please re-open if the problem persists.
