### ISSUE TITLE
bug: timestream outputs measure values of type DOUBLE with one decimal point precision

### ISSUE THREAD

**Issue by apekkar** [localstack/localstack#7949]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

>       assert localstack_timestream_output == excepted_output
E       AssertionError: assert '5.0' == '5.00'
E         - 5.00
E         ?    -
E         + 5.0

>       assert localstack_timestream_output == excepted_output
E       AssertionError: assert '1000.0' == '1000'
E         - 1000
E         + 1000.0
E         ?     ++

### Expected Behavior

Before it used to output the expected (see above) measure values
but now it outputs measure values of type DOUBLE with one decimal point precision

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

1. insert some values with type DOUBLE
2. query those (used python and boto3)

### Environment

```markdown
- LocalStack: 1.4.0 (and latest)
```

**Comment by ackdav** [comment]
Hi @apekkar - thx for this report. We reworked timestream quite a bit - could you please pull the latest localstack version and double check if this issue still persists for you?
Thanks!
