### ISSUE TITLE
bug: aws_vpc resource fails to deploy to localstack with the error 'enableNetworkAddressUsageMetrics' InvalidParameter

### ISSUE THREAD

**Issue by soheil-salimian1-NHSD** [localstack/localstack#7956]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

aws_vpc resource fails to deploy to localstack with the error 'enableNetworkAddressUsageMetrics' InvalidParameter on terraform version 1.3.9 and aws provider >=4.54

![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/124372286/227543674-ab0e00f2-9830-4411-8095-a1a024e5acb4.png)

### Expected Behavior

enableNetworkAddressUsageMetrics should not be expected when it is false, but it complains it doesnt exist regardless

### How are you starting LocalStack?

Custom (please describe below)

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)
 run a make-file which contains the command localstack-restart 

### Environment

```markdown
- OS: Ubuntu 20.04 on WSL
- LocalStack: 1.4.0
```

**Comment by thrau** [comment]
hi @soheil-salimian1-NHSD, could you please share in detail how to reproduce the issue? ideally including a complete terraform file that we can run. thanks!
