### ISSUE TITLE
bug: aws_default_security_group resource never completes it's deployment stuck in the 'still creating' state

### ISSUE THREAD

**Issue by soheil-salimian1-NHSD** [localstack/localstack#7957]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

aws_default_security_group resource never completes it's deployment stuck in the 'still creating' state, gave up after 10 minutes

### How are you starting LocalStack?

Custom (please describe below)

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    via make-file command uses localstack-restart

### Environment

```markdown
- OS: 20.04
- LocalStack: 1.4.0
```

**Comment by thrau** [comment]
hi @soheil-salimian1-NHSD, there's not very much to go on with this issue. can you please provide clear instructions on how to reproduce the issue?
