### ISSUE TITLE
feature request: Support Update operation for IAM Policy in Cloudformation

### ISSUE THREAD

**Issue by pinzon** [localstack/localstack#7963]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Current CloudFormation implementation doesn't support the **UPDATE** operation on a CFn Iam::Policy Resource.

**Comment by deepak2431** [comment]
@pinzon I have checked this out, as the current CFn Iam model doesn't have the update/add policy implemented in their configurations after the creation. We can use the IAM service CreatePolicyRequest to attach the policies through the cloud formation template.  Can I take this up to work on?

**Comment by pinzon** [comment]
The solution to this issue has been merged.
