### ISSUE TITLE
zsh: command not found: awslocal

### ISSUE THREAD

**Issue by stevebanik** [localstack/localstack#7966]
Executing this command in README.md:

user.name@mac git % awslocal sqs create-queue --queue-name sample-queue

Results in:

zsh: command not found: awslocal

**Comment by thrau** [comment]
hey @stevebanik, could you double check that you've installed the aws cli and awslocal correctly? it can be installed via pip: `pip install awscli awscli-local`

**Comment by stevebanik** [comment]
@thrau that fixed it - thanks.  I don't recall seeing that in the README.md, but perhaps I missed it.  Thanks for your help.
