### ISSUE TITLE
bug: docker not available error during java11 runtime lambda creation

### ISSUE THREAD

**Issue by nicofari** [localstack/localstack#7979]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Trying to create a function with java11 runtime I get this error:

Pulling Docker image: public.ecr.aws/lambda/java:11
multiprinter-localstack-1  | 2023-03-27T10:52:17.316728418Z 2023-03-27T10:52:17.314 DEBUG --- [Executor-1_0] l.s.a.i.version_manager    : Changing Lambda 'arn:aws:lambda:eu-west-1:000000000000:function:it.multidialogo.multiprinter.MyAwsLambdaExposedFunction:$LATEST' to failed. Reason: Docker not available
multiprinter-localstack-1  | 2023-03-27T10:52:17.316735574Z Traceback (most recent call last):
multiprinter-localstack-1  | 2023-03-27T10:52:17.316737472Z   File "/opt/code/localstack/localstack/services/awslambda/invocation/version_manager.py", line 194, in start
multiprinter-localstack-1  | 2023-03-27T10:52:17.316739266Z     get_runtime_executor().prepare_version(self.function_version)
multiprinter-localstack-1  | 2023-03-27T10:52:17.316740897Z   File "/opt/code/localstack/localstack/services/awslambda/invocation/docker_runtime_executor.py", line 386, in prepare_version
multiprinter-localstack-1  | 2023-03-27T10:52:17.316742543Z     CONTAINER_CLIENT.pull_image(image_name, platform)
multiprinter-localstack-1  | 2023-03-27T10:52:17.316743976Z   File "/opt/code/localstack/localstack/utils/container_utils/docker_sdk_client.py", line 222, in pull_image
multiprinter-localstack-1  | 2023-03-27T10:52:17.316745499Z     self.client().images.pull(docker_image, platform=platform)
multiprinter-localstack-1  | 2023-03-27T10:52:17.316746931Z   File "/opt/code/localstack/localstack/utils/container_utils/docker_sdk_client.py", line 53, in client
multiprinter-localstack-1  | 2023-03-27T10:52:17.316748804Z     raise ContainerException("Docker not available")
multiprinter-localstack-1  | 2023-03-27T10:52:17.316750569Z localstack.utils.container_utils.container_client.ContainerException: Docker not available

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

docker compose up -d

my docker-compose file:

version: '3.8'
services:
  localstack:
    image: localstack/localstack:latest
    environment:
      - DEBUG=1
      - DEFAULT_REGION=eu-west-1
      - SERVICES=lambda,logs,efs
    ports:
      - '4566-4583:4566-4583'
    volumes:
      - ./efs:/efs

aws create function command:

aws --endpoint-url=http://localhost:4566 \
lambda create-function --function-name it.multidialogo.multiprinter.MyAwsLambdaExposedFunction \
--zip-file fileb://build/distributions/Multiprinter.zip \
--environment Variables={NB_PORT="9001",NB_OUTPUT_PATH="/output}" \
--handler index.handler --runtime sam/build-java11 \
--role arn:aws:iam::000000000000:role/lambda-role

### Environment

```markdown
- OS: ubuntu 18.04
- LocalStack:
```

**Comment by dfangl** [comment]
Please mount your docker socket into the container by adding 
````
 - /var/run/docker.sock:/var/run/docker.sock
 ```
To your docker compose file, like demonstrated in our sample [docker-compose.yml](https://github.com/localstack/localstack/blob/master/docker-compose.yml).

This should fix the errors you have with lambda right now. For more information, see https://github.com/localstack/localstack/issues/7882

**Comment by nicofari** [comment]
It works thank you very much @dfangl !

**Comment by engrnazmulbari** [comment]
It resolved my python lambda issue. Thanks a lot @dfangl
