### ISSUE TITLE
feature request: [ECS] Support for update-service, stop, start tasks in CLI

### ISSUE THREAD

**Issue by hrishi-hugo** [localstack/localstack#7986]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

In ECS AWS CLI commands like update-service, stop task, start task currently have no effect and do not work. 
Can you please add this feature ?

**Comment by hrishi-hugo** [comment]
@whummer Thanks for taking this up. When do you think this might be available ? Because currently we are not able to use ECS due to this, as we want to restart the ECS task for some function of our app.

**Comment by whummer** [comment]
Hi @hrishi-hugo , we already have this feature in our pipeline - looking to get it out within the next couple of days.. 👍  Will ping you here with an update soon!

**Comment by whummer** [comment]
Hi again @hrishi-hugo , quick update - we have now added support for stop/start task, and generally improved the parity of the ECS implementation a bit further. Can you please pull the `latest` Docker image and give it a try? Looking forward to getting your feedback!

Regarding support for update-service - this is still in our pipeline, can you please share a few details about your specific use case? Ideally a few snippets of your client code with your service configuration, and the types of updated you'd expect to happen. This would be helpful for us to ensure that your requirements are covered. Thanks!

**Comment by hrishi-hugo** [comment]
@whummer. Thanks I'll test this, but basically we want to run this command from the cli which kills the current task and starts a new task with the same task definition. For now, if this command runs as expected, it should be enough for us.

```aws ecs update-service --cluster my-cluster --service my-service --force-new-deployment```

**Comment by hrishi-hugo** [comment]
@whummer any update on the `--force-new-deployment` ?

**Comment by whummer** [comment]
Hi @hrishi-hugo , quick update - we have a fix for this feature in our pipeline, and should be able to provide an update soon (in the upcoming days). Thanks for your help in resolving this.

**Comment by whummer** [comment]
Hi @hrishi-hugo , apologies for the delay on this one. We have now enhanced the support and parity around ECS services and tasks. In particular, you should now be able to update a service with `--force-new-deployment`, and then the task containers should get restarted accordingly.

Can you please pull the `latest` Docker image and give it a try? Please keep us posted on how it goes.. Thanks!

**Comment by hrishi-hugo** [comment]
@whummer just tried and got this error
```An error occurred (InternalError) when calling the UpdateService operation (reached max retries: 4): exception while calling ecs.UpdateService: Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/aws/chain.py", line 90, in handle
    handler(self, self.context, response)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/aws/handlers/service.py", line 123, in __call__
    handler(chain, context, response)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/aws/handlers/service.py", line 93, in __call__
    skeleton_response = self.skeleton.invoke(context)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/aws/skeleton.py", line 154, in invoke
    return self.dispatch_request(context, instance)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/aws/skeleton.py", line 166, in dispatch_request
    result = handler(context, instance) or {}
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/aws/skeleton.py", line 118, in __call__
    return self.fn(*args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/ecs/provider.py.enc", line 350, in update_service
    C._deploy_service(G,A,force_redeploy=A.response_object.get('forceNewDeployment'));return UpdateServiceResponse(service=A.response_object)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/ecs/models.py.enc", line 121, in response_object
    A['networkConfiguration']=B.network_configuration;return A
AttributeError: 'Service' object has no attribute 'network_configuration'
```

**Comment by whummer** [comment]
Hi @hrishi-hugo , just to confirm - do you have persistence enabled via `PERSISTENCE=1`? If so, can you please disable persistence (or flush the state of the persistent state in the LocalStack volume). Thanks

**Comment by hrishi-hugo** [comment]
@whummer Yes. I have persistence enabled before. Now I disabled it and it is working. But we need persistence for other services like RDS. 

I tried again with persistence enabled. The task started but the --force-new-deployment gives an error. Now it gave a different but similar error.
```
An error occurred (ServerException) when calling the UpdateService operation: An error occurred (InternalError) when calling the RunTask operation (reached max retries: 4): exception while calling ecs.RunTask: Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/aws/chain.py", line 90, in handle
    handler(self, self.context, response)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/aws/handlers/service.py", line 123, in __call__
    handler(chain, context, response)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/aws/handlers/service.py", line 93, in __call__
    skeleton_response = self.skeleton.invoke(context)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/aws/skeleton.py", line 154, in invoke
    return self.dispatch_request(context, instance)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/aws/skeleton.py", line 166, in dispatch_request
    result = handler(context, instance) or {}
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/aws/skeleton.py", line 118, in __call__
    return self.fn(*args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/ecs/provider.py.enc", line 280, in run_task
    for Z in range(F):B=Task(cluster=A,task_definition=M,container_instance_arn=_A,resource_requirements=I,overrides=L or{},started_by=R or'',tags=tags or[],launch_type=K or'',networking_configuration=Q,group=P);G.append(B);E.tasks[A.name][B.task_arn]=B
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/ecs/models.py.enc", line 77, in __init__
    A.network_configuration=D;E=D['awsvpcConfiguration'];I=ec2_backends[A._account_id][A.region_name];B=I.create_network_interface(subnet=E[H][0],private_ip_address=random_private_ip(),group_ids=E['securityGroups'],description=_K);B.status='in-use';B.device_index=0;A.attachments.append({'id':str(mock_random.uuid4()),_D:'ElasticNetworkInterface',_I:'ATTACHED','details':[{_B:'subnetId',_E:E[H][0]},{_B:'networkInterfaceId',_E:B.id},{_B:'macAddress',_E:B.mac_address},{_B:'privateDnsName',_E:B.private_dns_name},{_B:'privateIPv4Address',_E:B.private_ip_address}]})
AttributeError: 'ELBv2Backend' object has no attribute 'create_network_interface'```

**Comment by whummer** [comment]
Ok, thanks for confirming @hrishi-hugo . Unfortunately, it can happen that the persistence state of certain services becomes incompatible after a code/feature update. We're working on making this more reliable in the future. 👍 

You should be able to selectively reset individual service states by deleting the corresponding folders in the LocalStack volume dir, e.g., deleting the directory `<LOCALSTACK_VOLUME_DIR>/state/api_states/ecs` to reset the persistence state for ECS.

We have now pushed a couple more enhancements for the ECS service - when you get a chance, can you please pull the `latest` Docker image and give it another try? Thanks for your help in resolving this! 🙌

**Comment by alexrashed** [comment]
Hi @hrishi-hugo.
ECS has seen quite a lot of enhancements in the last few months, and it seems like your issue should be resolved by now.
I'll close this issue for now, please feel free to create a new issue if you are still experiencing any issues with the latest version of LocalStack!
Thanks!
