### ISSUE TITLE
bug: Localstack on Testcontainers with Transcribe service -  cannot load library libvosk.so

### ISSUE THREAD

**Issue by kkocel** [localstack/localstack#7988]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When sdk client requests transcription local stack responds with 500 error

### How are you starting LocalStack?

Custom (please describe below)

### Steps To Reproduce

LocalStack ran using testcontainers + docker image:

```kotlin
    @Container
    val localstack: LocalStackContainer = LocalStackContainer(DockerImageName.parse("localstack/localstack"))
        .withServices(
            Service.S3,
            EnabledService.named("transcribe")
        )
        .withCreateContainerCmdModifier { it: CreateContainerCmd -> it.withPlatform("linux/x86_64") }
```

The project that reproduces the issue can be found here: https://github.com/kkocel/local-stack-transcribe-repro

### Environment

```markdown
- OS: mac
- LocalStack: TestContainers + newest LocalStack from the docker image
```

### Anything else?

Logs:
```
exception while calling transcribe.StartTranscriptionJob: cannot load library '/opt/code/localstack/.venv/lib/python3.10/site-packages/vosk/libvosk.so': /opt/code/localstack/.venv/lib/python3.10/site-packages/vosk/libvosk.so: undefined symbol: _ZNSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEEC1Ev (Service: Transcribe, Status Code: 500, Request ID: UT3NGYF7QEOHP36NR29URIG575YEZU0D1URZN1W3Y22LKKXILVYJ)
```

**Comment by kkocel** [comment]
@bentsku when it comes to triaging I can provide more details if needed

**Comment by viren-nadkarni** [comment]
Hi @kkocel, LocalStack Transcribe has limited support for aarch64/Apple Silicon.

Please try the amd64 build of LocalStack:

```
docker pull localstack/localstack:2.0.0 --platform amd64
```

**Comment by kkocel** [comment]
@viren-nadkarni I applied your advice:

```kotlin
    @Container
    val localstack: LocalStackContainer = LocalStackContainer(DockerImageName.parse("localstack/localstack:latest-amd64"))
        .withServices(
            Service.S3,
            EnabledService.named("transcribe")
        )
```

And it works indeed. I found some discrepancies between real Amazon Transcribe service and LocalStack - I will report them in the other tickets
