### ISSUE TITLE
Question: python version support <3.10?

### ISSUE THREAD

**Issue by klaymo** [localstack/localstack#7994]
The readme states that python versions 3.7+ are supported, however based on the typing definitions used throughout the code, notably the alternative syntax for the `Union` type (using a pipe `|`) is only supported in 3.10+.

Should the documentation be updated and you only intend to support python 3.10+ or do you plan to change the typing syntax used to support 3.7+?

While it is up to you on what you want to support, I would suggest updating the typing to support the python languages that AWS supports for lambda, because in some cases we will develop locally in the same environment we will run the lambda.

**Comment by thrau** [comment]
Hi @klaymo, thanks for pointing out that this is confusing. The Python support really refers only to the localstack CLI that you can install with `pip install localstack`. The actual AWS emulator, or "runtime" as we call it, that runs in the container, runs using Python 3.10. There is a bit of code overlap, but we make sure that the code used in the CLI is compatible with 3.7+.

Both of those things are completely unrelated to the AWD Python Lambda runtimes, for which we have the same support as AWS.

I hope this helps for now. We should definitely update the section in the docs to make this more clear!

**Comment by klaymo** [comment]
Yes I think I understand. I was under the impression that the full library was meant to support other versions. For example

`from localstack.utils import testutil`

Will throw a `TypeError` exception because it also imports modules, which import modules, etc. But that has some convenience functions in it.

Perhaps that is not how you intend that to be used though which is fine.

Thanks for the quick reply
