### ISSUE TITLE
enhancement request: Sagemaker Serverless Endpoints

### ISSUE THREAD

**Issue by rbavery** [localstack/localstack#8020]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Enhancement description

It looks like there is support for Real-time endpoints, which are useful for very bursty ML inference, but not Serverless endpoints, which are more useful for low-latency inference.

LocalStack docs describing real-time endpoint support: https://docs.localstack.cloud/user-guide/aws/sagemaker/

Sagemaker Serverless Inference Docs: https://docs.aws.amazon.com/sagemaker/latest/dg/serverless-endpoints.html

### 🧑‍💻 Implementation

No clue, apologies!

**Comment by lukqw** [comment]
Hey there @rbavery!

Our Sagemaker provider already support serverless endpoints. Please feel free to take a look at [this sample](https://github.com/localstack/mnist-sagemaker) and report back with any questions or feedback you might have.

**Comment by alexrashed** [comment]
Hi @rbavery!
It seems like your feature should already be implemented, which is why I'll close this issue for now. Please take a look at our samples and docs, and feel free to create a new issue if you are still experiencing any issues!
Thanks!
