### ISSUE TITLE
bug: CFn stack name creation standards not set

### ISSUE THREAD

**Issue by deepak2431** [localstack/localstack#8027]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

AWS only allows a stack name to declared with following characters
"Stack name can include letters (A-Z and a-z), numbers (0-9), and dashes (-)."

In localstack, there's no validation of stack name while creating it. Creating a stack with the name s3_bucket also successfully creates one.

### Expected Behavior

While creating a stack with stack name which doesn't follows the standard, it should throw out an error with the message. 

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

 python -m localstack.cli.main start --host      

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    `awslocal cloudformation deploy --stack-name test_s3_bucket --template-file "cfn_iam.yaml"`

This command with an invalid stack name also creates an stack successfully.

### Environment

```markdown
- OS: macOS
- LocalStack:
```

**Comment by deepak2431** [comment]
I can take up this issue to work on after the issue status is confirmed.

**Comment by dominikschubert** [comment]
Implemented in https://github.com/localstack/localstack/pull/8166
