### ISSUE TITLE
bug: CreateMultipartUpload should return InitiateMultipartUploadResult element

### ISSUE THREAD

**Issue by pguillory** [localstack/localstack#8030]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Initiating a multipart S3 upload to LocalStack returns an XML document with a root element CreateMultipartUploadOutput. This causes an error in the ex_aws_s3 library I'm using. We've used the combination of LocalStack + ex_aws_s3 successfully for a few years and the error started occurring a few days ago.

### Expected Behavior

The element should be called InitiateMultipartUploadResult.

### How are you starting LocalStack?

With a `docker run` command

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run -p 4566:4566 localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    aws --debug --endpoint-url=http://localhost:4566 s3api create-multipart-upload --bucket my-bucket --key 'multipart/01'

### Environment

```markdown
- OS: Ubuntu 20.04.5 LTS
- LocalStack: latest
```

### Anything else?

S3 docs specifying InitiateMultipartUploadResult:
https://docs.aws.amazon.com/AmazonS3/latest/API/API_CreateMultipartUpload.html

Reference in official AWS Java client:
https://github.com/aws/aws-sdk-java/blob/ef22b94750d4c155d74b09012b3be5d9d98bbd33/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/model/transform/XmlResponsesSaxParser.java#L1865

Where our particular error gets raised in ex_aws_s3:
https://github.com/ex-aws/ex_aws_s3/blob/7e12f2b0578b2620c047d2e44c40a6de8773584a/lib/ex_aws/s3/parsers.ex#L78

**Comment by bentsku** [comment]
Hi @pguillory and thanks for your report! I've answered in your PR as well: https://github.com/localstack/localstack/pull/8032#issuecomment-1492774815

We are currently taking a look at all the operations returning a root XML node different that was is specified in the specs, and will try to correct most of them quickly. Thanks again for your report!

**Comment by bentsku** [comment]
Hi @pguillory, the PR has now been merged, the fix should be available in the `latest` Docker image. You can pull it and give a try! Thanks a lot for the kind words on your PR as well 😄

**Comment by pguillory** [comment]
Verified the fix works and our tests are passing. Thanks again for your help!

**Comment by bentsku** [comment]
Awesome, thanks for the feedback! I'm glad we could fix all the issues in one go, this issue was worrying me a bit. Glad to hear it fixes your issue! 🎉
