### ISSUE TITLE
bug: EventBridge PutRule fails with invalid AWS region name error

### ISSUE THREAD

**Issue by denniszelada** [localstack/localstack#8038]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When attempting to create a rule using the EventBridge PutRule operation with LocalStack, the command fails with an "invalid AWS region name" error. 

### Expected Behavior

When running the EventBridge PutRule operation with LocalStack, the command should succeed without any errors, regardless of the current date. The rule should be created in LocalStack's EventBridge service, and no "invalid AWS region name" error should be encountered.

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    ACTIVATE_PRO=0 localstack start

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

  Run the PutRule command using the AWS CLI:
`aws events put-rule --name my-rule --schedule-expression 'rate(1 minute)' --endpoint-url=http://localhost:4566 --region us-east-1`

The command fails with the following error:
`An error occurred (InternalError) when calling the PutRule operation (reached max retries: 2): exception while calling events.PutRule: '20230401' is not a valid AWS region name for events`

LocalStack logs show the following error and traceback:
```2023-04-01T16:56:33.999  INFO --- [uncthread181] localstack.utils.threads   : Thread run method <function EventsProvider.get_scheduled_rule_func.<locals>.func at 0x7f23926bc9d0>(None) failed: Provided region_name '20230401' doesn't match a supported format. Traceback (most recent call last):
File "/opt/code/localstack/localstack/utils/threads.py", line 58, in run
result = self.func(self.params, **kwargs)
File "/opt/code/localstack/localstack/services/events/provider.py", line 74, in func
client = aws_stack.connect_to_service("events")
File "/opt/code/localstack/localstack/utils/aws/aws_stack.py", line 308, in connect_to_service
new_client = boto_factory(
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/boto3/__init__.py", line 92, in client
return _get_default_session().client(*args, **kwargs)
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/boto3/session.py", line 299, in client
return self._session.create_client(
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/session.py", line 918, in create_client
region_name = self._resolve_region_name(region_name, config)
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/session.py", line 1002, in _resolve_region_name
validate_region_name(region_name)
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/utils.py", line 1272, in validate_region_name
raise InvalidRegionError(region_name=region_name)
botocore.exceptions.InvalidRegionError: Provided region_name '20230401' doesn't match a supported format.```



### Environment

```markdown
- OS: MacOS 13.2.1 (22D68)
- LocalStack: 2.0.0.post1
```

**Comment by thrau** [comment]
Hey Dennis @denniszelada. I can't seem to reproduce the issue with the latest image and `awslocal`.

Hey @Dennis Zelada, it works fine for me with the latest image when using awslocal:

```
 % awslocal events put-rule --name my-rule --schedule-expression 'rate(1 minute)' 
{
    "RuleArn": "arn:aws:events:us-east-1:000000000000:rule/my-rule"
}
```

localstack log says:
```
2023-04-01T20:48:20.057  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS events.PutRule => 200
```

Might this be an issue with your `~/.aws/config` and `AWS_PROFILE` ?

**Comment by denniszelada** [comment]
Hello @thrau Thank you very much for your prompt reply. this is my `~/.aws/config`
` [profile localstack]
   region = us-east-1
   output = json`

And my `AWS_PROFILE`
`localstack`

But still failing, I try running this with the latest docker container and still the same issue, any other idea of what could be?

Thanks

**Comment by denniszelada** [comment]
I found the solution, I was running the command as
`aws events put-rule --name my-rule --schedule-expression 'rate(1 minute)' --endpoint-url=http://localhost:4566 --region us-east-1`
but when I removed the --region flag it worked
`aws events put-rule --name my-rule --schedule-expression 'rate(1 minute)' --endpoint-url=http://localhost:4566`
Thanks for your help, closing this.

**Comment by leandroribeiro** [comment]
@denniszelada just a tip, try remove all whitespace in your .config file, this solved my problem. like region=us-east-1 without whitespace
