### ISSUE TITLE
bug: `localstack/localstack-pro:2.0.0-bigdata` is missing from the Amazon ECR Public Library

### ISSUE THREAD

**Issue by yuvalshi0** [localstack/localstack#8041]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The tag does not exist in https://gallery.ecr.aws/localstack/localstack-pro, it appears to be only in the dockerhub registry

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal s3 mb s3://mybucket

### Environment

```markdown
- OS:
- LocalStack:
```

**Comment by whummer** [comment]
Hi @yuvalshi0, thanks for reporting, and apologies for the delay. Currently we're only publishing the main LocalStack images to the ECR public library, the main source of distribution still remains Docker Hub. 

Can you please share some more details about your use case and requirements - are you able to pull images from Docker Hub, or are you facing certain network restrictions in your environment? 

We'll look into pushing the bigdata flavor of the image as well (at least the tagged releases). Thanks for your support and patience!
