### ISSUE TITLE
bug: Lambda does not trigger when plugged to DynamoDB Streams

### ISSUE THREAD

**Issue by TRAD-Anthony-CKO** [localstack/localstack#8046]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

- Given I create and map a C# .NET 6 Lambda to a DynamoDB Stream table 
- And I use the new Lambda provider (v2) -> PROVIDER_OVERRIDE_LAMBDA=v2 (by default from version 2.0.0)
- When I PUT any item in my DynamoDB table
- **Then the Lambda does not get triggered**

### Expected Behavior

- Given I create and map a C# .NET 6 Lambda to a DynamoDB Stream table
- And I use the new Lambda provider (v2) -> PROVIDER_OVERRIDE_LAMBDA=v2 (by default from version 2.0.0)
- When I PUT any item in my DynamoDB table
- **Then the Lambda should get triggered automatically**

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

Create a DynamoDB table with a stream, a .NET lambda that links to that stream and try to PUT any item in the DynamoDB table. 
I have the default Lambda handler from the AWS Templates:
```
public void FunctionHandler(DynamoDBEvent dynamoEvent, ILambdaContext context)
    {
        context.Logger.LogInformation($"Beginning to process {dynamoEvent.Records.Count} records...");

        foreach (var record in dynamoEvent.Records)
        {
            context.Logger.LogInformation($"Event ID: {record.EventID}");
            context.Logger.LogInformation($"Event Name: {record.EventName}");

            // TODO: Add business logic processing the record.Dynamodb object.
        }

        context.Logger.LogInformation("Stream processing complete.");
    }
```

### Environment

```markdown
- OS: MacOSX (M1)
- LocalStack: 2.0.0
- Lambda: C# and .NET 6
```

### Anything else?

- If I change the `PROVIDER_OVERRIDE_LAMBDA=v2` to `PROVIDER_OVERRIDE_LAMBDA=legacy` in my docker-compose, everything works normally.
- Doing this after the init scripts: `awslocal lambda get-function --function-name $NAME` shows `"State": "Active"`
- Doing this after the init scripts: `awslocal lambda list-event-source-mappings --function-name $NAME` shows `"State": "Enabled"`

With the legacy provider, I see the logs that show that localstack is invoking the Lambda. I don't see anything of the sort with the new provider. 

If i set `DEBUG=1` I get the following after my PUT request:
```
023-04-03T09:29:24.195 DEBUG --- [functhread37] l.s.a.e.adapters           : Encountered an exception while handling lambda invoke
Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/awslambda/event_source_listeners/adapters.py", line 190, in invoke_with_statuscode
    payload=to_bytes(json.dumps(payload or {})),
  File "/usr/local/lib/python3.10/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable
2023-04-03T09:29:25.276 DEBUG --- [functhread37] l.s.a.e.adapters           : Encountered an exception while handling lambda invoke
Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/awslambda/event_source_listeners/adapters.py", line 190, in invoke_with_statuscode
    payload=to_bytes(json.dumps(payload or {})),
  File "/usr/local/lib/python3.10/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable
```

**Comment by TRAD-Anthony-CKO** [comment]
The issue persists within localstack `2.0.2`

**Comment by jaybe78** [comment]
The issue still persists today.
It works for a couple of updates and then suddenly the stream does not get updated anymore.
The last timestamp column remains the same

**Comment by tonestrike** [comment]
Any update on this? Has anyone been able to figure this out?

**Comment by joe4dev** [comment]
@TRAD-Anthony-CKO @jaybe78 @tonestrike, Thank you for raising and reminding us about this issue. We have re-implemented Lambda Event Source Mappings from scratch to tackle many challenges with the prior implementation. The code causing the abovementioned serialization error has been gone since LocalStack v4 🧹 .

Check out our new Lambda event source mapping (ESM) implementation in [LocalStack v4](https://blog.localstack.cloud/announcing-localstack-40-general-availability/) offering better functional and non-functional support for ESM 🚀 . The behavioral coverage documentation provides more details for your use case https://docs.localstack.cloud/user-guide/aws/lambda/#lambda-event-source-mappings

Feel free to open another issue or share your feedback if you experience any challenges👂
