### ISSUE TITLE
bug: ECR repository creation allows capital letters

### ISSUE THREAD

**Issue by lukqw** [localstack/localstack#8051]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

ECR repository creation allows capital letters in name:
```
❯ awslocal ecr create-repository --repository-name tesTing
{
    "repository": {
        "repositoryArn": "arn:aws:ecr:us-east-1:000000000000:repository/tesTing",
        "registryId": "000000000000",
        "repositoryName": "tesTing",
        "repositoryUri": "localhost.localstack.cloud:4510/tesTing",
        "createdAt": "2023-04-03T19:21:56+02:00",
        "imageTagMutability": "MUTABLE",
        "imageScanningConfiguration": {
            "scanOnPush": false
        },
        "encryptionConfiguration": {
            "encryptionType": "AES256"
        }
    }
}
```

### Expected Behavior

Expecting repository creation to fail when improper characters are used in repository name, such as capital letter:
```
❯ aws ecr create-repository --repository-name tesTing 

An error occurred (InvalidParameterException) when calling the CreateRepository operation: Invalid parameter at 'repositoryName' failed to satisfy constraint: 'must satisfy regular expression '(?:[a-z0-9]+(?:[._-][a-z0-9]+)*/)*[a-z0-9]+(?:[._-][a-z0-9]+)*''
```

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    localstack start

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal ecr create-repository --repository-name tesTing

### Environment

```markdown
- OS: macos
- LocalStack: CLI - 2.0.0.post1, docker image - latest
```

**Comment by Narcos101** [comment]
hey @lukqw  can i take on this issue? If yes, any hints or things to take care off? Thanks!

**Comment by lukqw** [comment]
Hi there @Narcos101 👋 
Just realized this is one of our pro services, so sadly not! Will remove the `good first issue` badge.

**Comment by Narcos101** [comment]
Ah! Anyways @lukqw are there any beginner friendly issues to take care off?

**Comment by lukqw** [comment]
@Narcos101 Any marked as `good first issue` should be beginner friendly :) 
This one for example: https://github.com/localstack/localstack/issues/7935

**Comment by bentsku** [comment]
Sorry to come in here, but there's already a PR open for #7935: #7936. Maybe another one? 😄

**Comment by lukqw** [comment]
Welp, I guess any other issue that is marked as `good first issue` and has no PR attached to it should suffice then:
E.g.: https://github.com/localstack/localstack/issues/7884 or https://github.com/localstack/localstack/issues/7555 😅

**Comment by ackdav** [comment]
Hello @lukqw - thanks for the report. The corresponding fix has been merged within moto and is awaiting a moto bump within LocalStack (likely in the coming few days) - I'll keep an eye out for that :eyes: . Thanks again :rocket:
