### ISSUE TITLE
bug: ElastiCache clusters dont start automatically with the new SNAPSHOT_LOAD_STRATEGY=on_startup  feature in v2.0

### ISSUE THREAD

**Issue by hrishi-hugo** [localstack/localstack#8065]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The state for ElastiCache clusters do not load automatically with SNAPSHOT_LOAD_STRATEGY=on_startup. It works with RDS MySQL. But ElastiCache clusters do not start on localstack startup. When I use `awslocal elasticache describe-cache-clusters` then they load.

### How are you starting LocalStack?

With a `docker run` command

### Steps To Reproduce

Using docker run command

### Environment

```markdown
- OS:
- LocalStack:
```

**Comment by thrau** [comment]
HI @hrishi-hugo , thanks for reporting. ElastiCache clusters not starting is currently a known limitation: https://docs.localstack.cloud/references/persistence-mechanism/#known-limitations

We'll let you know once it works!

**Comment by giograno** [comment]
Hi @hrishi-hugo, thanks for reporting the issue. We implemented proper persistence for the ElastiCache clusters. You can give it a try by pulling the `latest` Docker image. Please keep in mind that we only implemented support for redis cluster mode disabled. Cluster mode with replicas is still work in progress. Thank you!
