### ISSUE TITLE
Cloudformation script unable to parse GlobalSecondaryIndexes Read/Write CapacityUnits given as string value

### ISSUE THREAD

**Issue by sankargireesan** [localstack/localstack#809]
![image](https://user-images.githubusercontent.com/24869107/41616570-40a2c1f4-73cc-11e8-9f54-cd84199b2359.png)

When ProvisionedThroughput of GlobalSecondaryIndexes Read/Write CapacityUnits is given as a string, cloudformation service is unable to parse it. It needs int or long.
(was able to run once I changed throughput to number)

But when ProvisionedThroughput of a table is given as a string, it is parsing it correctly.

**Comment by whummer** [comment]
Thanks for reporting @sankargireesan . This should be fixed in #2828 - can you please do a `docker pull localstack/localstack` and give it another try with the `latest` version of the Docker image? Please report here if the problem persists. Thanks!
