### ISSUE TITLE
bug: 'pictures' a reserved word for an S3 bucket name?

### ISSUE THREAD

**Issue by kyllerss** [localstack/localstack#8090]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I created an S3 bucket with the name `pictures`. Each time I tried to write to it, I would get a CORS error. 

I used the same code as I used for another bucket which was working fine (`originaluploads`). I even verified that the same code path that was causing issues under `pictures` worked fine when pointed against the `originaluploads` bucket. 

When I renamed the `pictures` bucket to `userpictures`, the code worked fine. 

Is `pictures` a reserved bucket name in LocalStack? If so, I couldn't find any documentation. Otherwise, seems like a bug. 

### Expected Behavior

`pictures`-named S3 buckets shouldn't reject with CORS errors.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

Attempt to write to an S3 bucket named `pictures`.

### Environment

```markdown
- OS: Docker
- LocalStack: 2.0.0
```

**Comment by bentsku** [comment]
Hello @kyllerss and thanks for your report! I'm going to start looking into it, but would you have a small reproducible sample or something I could follow to reproduce?

Do you have any CORS configuration on your bucket? Or do you use CORS settings of LocalStack (https://docs.localstack.cloud/references/configuration/#security)?
How are you writing to your bucket? Using a SDK from the browser?

I'll try to reproduce in the meantime, but it would be nice to be sure we're reproducing the same issue. Thanks!

**Comment by bentsku** [comment]
Thanks a lot, this should be enough to look into it, thanks a lot for taking the time to share the data. I'm going to look into it! I'm not aware of a `pictures` specific thing on CORS issue on LocalStack side. This seems interesting! I'll come back once I have more informations, thanks again for the report!

**Comment by bentsku** [comment]
I've tried to reproduce, and it doesn't seem there's an issue with the `pictures` bucket name and CORS. We will need the LocalStack logs when the issue happen, to know exactly what is happening on LocalStack side. It could also be that there's an unexpected error and we wouldn't populate CORS headers correctly after that, but it would be hidden by the browser because of CORS: often CORS is the first to fail and hide the real issue underneath.

You can get more verbose logs by setting `LS_LOG=trace` and `DEBUG=1` before starting LocalStack.

Sorry for asking more, I'd understand if that takes time! I've also tried to look and there isn't a trace of `pictures` hardcoded anywhere that would be linked to that specific issue.

**Comment by kyllerss** [comment]
No problem! And thank you for looking into this:

```
docker-localstack-1  | 2023-04-06T15:12:40.035 DEBUG --- [   asgi_gw_9] l.aws.serving.wsgi         : GET localhost:4566/_localstack/health
docker-localstack-1  | 2023-04-06T15:12:50.422 DEBUG --- [   asgi_gw_4] l.aws.serving.wsgi         : GET localhost:4566/_localstack/health
docker-localstack-1  | 2023-04-06T15:12:51.026 DEBUG --- [  asgi_gw_12] l.aws.serving.wsgi         : OPTIONS pictures.s3.localhost.localstack.cloud/2023/4/6/b2652605-108b-4273-a4a2-5ef050c1eb90.jpg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=test%2F20230406%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Date=20230406T151250Z&X-Amz-Expires=86400&X-Amz-Signature=e237956ffcd59effb23f223d8beb7d6eb0faec79994a7023bdd2f1442b7228ec&X-Amz-SignedHeaders=host&x-id=PutObject
docker-localstack-1  | 2023-04-06T15:12:51.028  INFO --- [  asgi_gw_12] localstack.request.http    : OPTIONS /2023/4/6/b2652605-108b-4273-a4a2-5ef050c1eb90.jpg => 200; Request(b'', headers={'Host': 'pictures.s3.localhost.localstack.cloud', 'Connection': 'close', 'Pragma': 'no-cache', 'Cache-Control': 'no-cache', 'Accept': '*/*', 'Access-Control-Request-Method': 'PUT', 'Access-Control-Request-Headers': 'content-type', 'Origin': 'https://www.dev.mydomain.com', 'User-Agent': 'Mozilla/5.0 (iPhone; CPU iPhone OS 13_2_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Mobile/15E148 Safari/604.1', 'Sec-Fetch-Mode': 'cors', 'Sec-Fetch-Site': 'same-site', 'Sec-Fetch-Dest': 'empty', 'Referer': 'https://www.dev.mydomain.com/', 'Accept-Encoding': 'gzip, deflate, br', 'Accept-Language': 'en-US,en;q=0.9,es-MX;q=0.8,es;q=0.7'}); Response(b'', headers={'Access-Control-Allow-Origin': 'https://www.dev.mydomain.com', 'Access-Control-Allow-Credentials': 'true', 'Vary': 'Origin, Access-Control-Request-Headers, Access-Control-Request-Method', 'Access-Control-Allow-Methods': 'POST, GET, HEAD, DELETE, PUT', 'Access-Control-Allow-Headers': 'content-type', 'Access-Control-Expose-Headers': 'ETag', 'Access-Control-Max-Age': '3600', 'x-amz-request-id': 'U3SZ7HXRBO8UWPXLN0I9B6U6E8FASDGL7WI6OYO44498TO9F9DUE', 'x-amz-id-2': 'MzRISOwyjmnupU3SZ7HXRBO8UWPXLN0I9B6U6E8FASDGL7WI6OYO44498TO9F9DUE7/JypPGXLh0OVFGcJaaO3KW/hRAqKOpIEEp', 'Content-Length': '0', 'Connection': 'close'})
docker-localstack-1  | 2023-04-06T15:12:51.039 DEBUG --- [   asgi_gw_7] l.aws.serving.wsgi         : PUT pictures.s3.localhost.localstack.cloud/2023/4/6/b2652605-108b-4273-a4a2-5ef050c1eb90.jpg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=test%2F20230406%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Date=20230406T151250Z&X-Amz-Expires=86400&X-Amz-Signature=e237956ffcd59effb23f223d8beb7d6eb0faec79994a7023bdd2f1442b7228ec&X-Amz-SignedHeaders=host&x-id=PutObject
docker-localstack-1  | 2023-04-06T15:12:51.040  INFO --- [   asgi_gw_7] l.aws.handlers.cors        : Blocked CORS request from forbidden origin https://www.dev.mydomain.com
docker-localstack-1  | 2023-04-06T15:13:00.828 DEBUG --- [   asgi_gw_8] l.aws.serving.wsgi         : GET localhost:4566/_localstack/health
docker-localstack-1  | 2023-04-06T15:13:11.196 DEBUG --- [   asgi_gw_3] l.aws.serving.wsgi         : GET localhost:4566/_localstack/health
docker-localstack-1  | 2023-04-06T15:13:21.541 DEBUG --- [   asgi_gw_2] l.aws.serving.wsgi         : GET localhost:4566/_localstack/health
docker-localstack-1  | 2023-04-06T15:13:31.891 DEBUG --- [  asgi_gw_10] l.aws.serving.wsgi         : GET localhost:4566/_localstack/health
```

One thing I didn't mention was that I am using a reverse proxy that handles SSL termination. It's a fairly straightforward configuration, but figured it would be helpful to paint the fuller picture - though I wouldn't expect it to be relevant to this issue as it works just fine with `originaluploads` but doesn't with `pictures`:

```
server {
    listen 443 ssl;
    server_name ~^(terraform|originaluploads|pictures)\.dev\.mydomain\.com$;                               

    proxy_set_header Host $1.s3.localhost.localstack.cloud;
    client_max_body_size 100M;

    include conf.d/ssl.conf;
    location / {
        proxy_pass http://$NGINX_LOCALSTACK_URL;
    }
}
```

... where `NGINX_LOCALSTACK_URL` is `localstack:4566` within the docker compose environment.

Let me know if you need additional logs.

**Comment by bentsku** [comment]
Okay thanks for the precision! Trying while using virtual host addressing instead of path style like I was doing earlier does indeed fail... this is extremely interesting! Thanks for bringing this to our attention.

**Comment by kyllerss** [comment]
In case it helps, I originally ran into this problem on version `1.4`, which led me to update to `2.0` and still find the issue. Good luck!

**Comment by bentsku** [comment]
Thanks! It seems I've found the issue, and it might be more widespread that originally thought. It seems to be a conflict with other AWS services. I think I have a fix, I will create a PR and link it to this issue!
