### ISSUE TITLE
bug: Cloudtrail events are returning readOnly true even for write/update/delete events on an AWS entity

### ISSUE THREAD

**Issue by bharath-nz** [localstack/localstack#8107]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```
"EventId": "3871fc86-419a-4748-808f-7c7a47853fb8",
"EventName": "CreateBucket",
"ReadOnly": "true",
"AccessKeyId": "ABCTEST0000000123",
"EventTime": 1678804132.704,
"EventSource": "[s3.amazonaws.com](http://s3.amazonaws.com/)",
"Username": "testuser",
"Resources": [],
```

### Expected Behavior

In the above cloudtrail event, "CreateBucket" is a write event however the ReadOnly flag above seems to be showing true. The expected value is false.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    aws --endpoint-url http://localhost:4566 cloudtrail create-trail --name test-cloudtrail --s3-bucket-name cloudtrail-docker.internal --s3-key-prefix test-prefix --is-multi-region-trail
    
    aws  --endpoint-url http://localhost:4566 cloudtrail put-event-selectors --trail-name test-cloudtrail  --event-selectors '[{"ReadWriteType": "All","IncludeManagementEvents": true}]'

    aws --endpoint-url http://localhost:4566 cloudtrail start-logging  --name  test-cloudtrail 

    aws --endpoint-url=http://localhost:4566 s3api create-bucket --acl public-read-write --bucket test-bucket --region us-east-2

Now The cloudtrail event registers with a "CreateBucket" action and comes up as "ReadOnly": "true".

Actual AWS Output:
``` 
   "eventTime": "2023-03-10T03:43:08Z",
    "eventSource": "s3.amazonaws.com",
    "eventName": "CreateBucket",
    "awsRegion": "us-east-2",
    "readOnly": false,
    "eventType": "AwsApiCall",
    "managementEvent": true,
    "recipientAccountId": <AWS-ACCOUNT-ID>,
    "eventCategory": "Management",
```

### Environment

```markdown
- OS: Mac OS 13.3
- LocalStack: 1.3.0
```

**Comment by steffyP** [comment]
Hi @bharath-nz, 

thanks for reporting! We have just released a fix, can you please pull `localstack/localstack-pro:latest` and verify it is working for you now? 🙏

**Comment by steffyP** [comment]
assuming the "thumbs up" means it's working now 🙂 closing the ticket, please let us know if you have any other issues, @bharath-nz.

**Comment by bharath-nz** [comment]
@steffyP sorry was traveling and hence couldn't verify. Please feel free to close. Thanks again!
