### ISSUE TITLE
SNS and SQS subscription is not working

### ISSUE THREAD

**Issue by shambhand** [localstack/localstack#8111]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

start the localstack 
`docker run --rm -it -p 4566:4566 -p 4571:4571 localstack/localstack -e "SERVICES=dynamodb,s3,sns,sqs"`

1. create a queue
`aws sqs create-queue --queue-name email --endpoint-url http://localhost:4566`

2. create sns topic
`awslocal sns create-topic --name email --endpoint-url http://localhost:4566`

3. subscribe queue to the sns topic - failed
`aws sns subscribe --topic-arn arn:aws:sns:us-east-1:000000000000:email --protocol sqs --notification-endpoint http://localhost:4566/queue/email --endpoint-url http://localhost:4566`

the 3rd step is failing with an error `An error occurred (InvalidParameter) when calling the Subscribe operation: Invalid parameter: SQS endpoint ARN` and in the logs `2023-04-11T08:40:14.454  INFO --- [   asgi_gw_1] localstack.request.aws     : AWS sns.Subscribe => 400 (InvalidParameter)`

### Expected Behavior

the sns sqs subscription should succeed

### How are you starting LocalStack?

With a `docker run` command

### Steps To Reproduce

start the localstack 
`docker run --rm -it -p 4566:4566 -p 4571:4571 localstack/localstack -e "SERVICES=dynamodb,s3,sns,sqs"`

1. create a queue
`aws sqs create-queue --queue-name email --endpoint-url http://localhost:4566`

2. create sns topic
`awslocal sns create-topic --name email --endpoint-url http://localhost:4566`

3. subscribe queue to the sns topic - failed
`aws sns subscribe --topic-arn arn:aws:sns:us-east-1:000000000000:email --protocol sqs --notification-endpoint http://localhost:4566/queue/email --endpoint-url http://localhost:4566`

the 3rd step is failing with an error `An error occurred (InvalidParameter) when calling the Subscribe operation: Invalid parameter: SQS endpoint ARN` and in the logs `2023-04-11T08:40:14.454  INFO --- [   asgi_gw_1] localstack.request.aws     : AWS sns.Subscribe => 400 (InvalidParameter)`

### Environment

```markdown
- OS: macOS Monterey v12.5.1 
- LocalStack version: 2.0.2.dev
- LocalStack build date: 2023-04-09
- LocalStack build git hash: ed7e02f1
```

**Comment by dfangl** [comment]
As you can see here: https://docs.aws.amazon.com/cli/latest/reference/sns/subscribe.html
The `notification-endpoint` for a subscription to sqs has to be the queue arn, not the queue url. This is why the given SQS endpoint ARN is invalid, it is not an ARN at all, but the queue url.

Please try using the queue url instead.

**Comment by shambhand** [comment]
Thanks! working fine after replacing it with the queue arn
