### ISSUE TITLE
bug: The specified bucket does not exist error when curling OpenSearch

### ISSUE THREAD

**Issue by ansnoussi** [localstack/localstack#8115]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Getting `The specified bucket does not exist` error when running curl to get the OpenSearch cluster health.

### Expected Behavior

running `curl http://test-domain.eu-west-3.opensearch.localhost.localstack.cloud:4566/_cluster/health` should hit the OpenSearch service in localstack and return the cluster health

### How are you starting LocalStack?

With a `docker run` command

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run --rm -it -p 4566:4566 -p 4510-4559:4510-4559 localstack/localstack:1.4.0

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal opensearch create-domain --domain-name test-domain --region eu-west-3
    curl http://test-domain.eu-west-3.opensearch.localhost.localstack.cloud:4566/_cluster/health

### Environment

```markdown
- OS: MacOS Ventura 13.1
- LocalStack: 1.4.0
```

**Comment by simonrw** [comment]
Hi @ansnoussi , it's possible that LocalStack is still downloading the OpenSearch binary which powers our opensearch implementation.

If you re-run your docker command adding `-e DEBUG=1` and create your domain, do you see log lines like `Written 1048576 bytes... to /var/lib/localstack/cache/...`? 

If this is the case, you can either wait until those lines stop and try again, or you can run something like

```
awslocal opensearch describe-domain --domain-name test-domain --region eu-west-3 --query DomainStatus.Processing
```

after creating your domain to check the "processing" status. Wait until the describe-domain command returns `false` and you should be able to send requests to your cluster's health endpoint. 

If this still does not work, then please let us know.

**Comment by ansnoussi** [comment]
Thanks @simonrw , this was actually the issue.

IMO the error returned by LocalStack when the the OpenSearch is being download asynchronously is misleading and threw me down a rabbit hole thinking this was a networking.

If you agree, I think the issue should stay open to track and fix the returned error to truly reflect the state of LocalStack. But I would be happy to close if you see otherwise.

Thanks again, and have a great day 🙏.

**Comment by ansnoussi** [comment]
Update : 
When going back to my original use-case which is preparing a development environment and sharing it using a cloud pod, I ran into the same issue again.
here are the steps to reproduce : 
1. Start LocaStack : `docker run --rm -it -p 4566:4566 -p 4510-4559:4510-4559 localstack/localstack:1.4.0`
2. Create an OpenSearch domain : `awslocal opensearch create-domain --domain-name test-domain --region eu-west-3`
3. To be extra cautious, I waited for the domain to be ready before exporting to a cloud pod : waited until I got back `false` from `awslocal opensearch describe-domain --domain-name test-domain --region eu-west-3 --query DomainStatus.Processing`
4. Save the LocalStack state to a pod : `localstack pod save file:///Users/$(whoami)/Desktop/test-localstack-pod`
5. Stop and re-run localstack using the same command : `docker run --rm -it -p 4566:4566 -p 4510-4559:4510-4559 localstack/localstack:1.4.0`
6. Load the cloud pod : `localstack pod load file:///Users/$(whoami)/Desktop/test-localstack-pod`
7. Verify that the OpenSearch Domain is ready : got back `false` from `awslocal opensearch describe-domain --domain-name test-domain --region eu-west-3 --query DomainStatus.Processing`
8. ⚠️ but now running `curl http://test-domain.eu-west-3.opensearch.localhost.localstack.cloud:4566/_cluster/health` returns this error : 
```
<?xml version='1.0' encoding='utf-8'?>
<Error><Code>NoSuchBucket</Code><Message>The specified bucket does not exist</Message><RequestId>JD1Z5J6FZ80Z5G5W2Y90O93R4LE5QWJWL9T2LPA6G7HJRCCUKTWW</RequestId></Error>
```

**Comment by simonrw** [comment]
I think this is the same issue. If you add `-e DEBUG=1` again after restarting docker, you can see LocalStack downloading the `opensearch` binary again. If you wait until the logs display something like `cluster on http://127.0.0.1:<port> is ready` then the cluster should be up and running.

We save the state of the domain when the cloud pod is created, which persists `Processing=false`, but we have to start the cluster up again after a cloud pod restore, and this requires downloading the opensearch binary again. I don't think this is the _wrong_ behaviour since cloud pods reflect the state of the infrastructure at point of creation, but I agree it's confusing.

---

One option if you want to have a fast restart is to mount a volume from your host to the container so you do not have to re-download opensearch each time you restart LocalStack. See the [LocalStack volume docs](https://docs.localstack.cloud/references/filesystem/#localstack-volume) and add a flag similar to `-v $PWD/volume:/var/lib/localstack` to your docker command.

**Comment by ansnoussi** [comment]
Thanks again for your response, it makes a lot of sense.
Running with `-e DEBUG=1` when loading the pod, I don't see LocalStack downloading OpenSearch ( folder `volume/lib` is empty ).
But I do see an error in the logs, related to other resources in the pod ( a lambda + sqs subscription ) : 
```
api-localstack  | 2023-04-12T09:36:57.718 DEBUG --- [   asgi_gw_0] l.s.awslambda.urlrouter    : Registering parameterized Lambda routes.
api-localstack  | 2023-04-12T09:36:57.995 ERROR --- [   asgi_gw_0] localstack.utils.functions : error calling function on_after_state_load
api-localstack  | Traceback (most recent call last):
api-localstack  |   File "/opt/code/localstack/localstack/utils/functions.py", line 41, in call_safe
api-localstack  |     return func(*args, **kwargs)
api-localstack  |   File "/opt/code/localstack/localstack/services/awslambda/provider.py", line 260, in on_after_state_load
api-localstack  |     for esm in state.event_source_mappings.values():
api-localstack  | AttributeError: 'list' object has no attribute 'values'
```
It looks related to this line : https://github.com/localstack/localstack/blob/master/localstack/services/awslambda/provider.py#L261

This error is not crashing LocalStack, but it's preventing it from downloading OpenSearch. This happens because the pod I'm loading does in fact contain other resources (mainly sqs queues and lambda functions) which seems to cause the issue.

Will try and debug that myself and open another issue if needed because this is no longer related to `The specified bucket does not exist error when curling OpenSearch` per say.

Thanks 🙏.

**Comment by simonrw** [comment]
Thanks again for raising this issue, and please do raise another issue that's more specific to the error you posted :+1:
