### ISSUE TITLE
enhancement request: Support for latest Kubernetes version

### ISSUE THREAD

**Issue by jyesudian** [localstack/localstack#8117]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Enhancement description

As per the localstack-pro:latest (April 2023), the kubernetes version seems to be 1.22. Do we have any plans to support the latest version 1.25? The k3s latest seems to support Kubernetes v1.26.

```
$ kubectl get nodes
NAME                      STATUS   ROLES                  AGE    VERSION
k3d-gw-cluster-server-0   Ready    control-plane,master   7d6h   v1.22.6+k3s1
```

### Anything else?

https://github.com/k3s-io/k3s/releases

**Comment by whummer** [comment]
Hi @jyesudian , we have now pushed a few enhancements to support custom Kubernetes version when creating EKS clusters. 

We have yet to update our documentation - but in the meantime, can you please pull the `latest` image and give it a try with specifying the 
```
$ awslocal eks create-cluster --name c1 --role-arn r1 --resources-vpc-config '{}' --kubernetes-version 1.23
```

.. and the node versions would then be reported as follows:

$ kubectl get nodes

NAME              STATUS   ROLES                  AGE   VERSION
k3d-c1-server-0   Ready    control-plane,master   84s   v1.23.17+k3s1
```

Please keep us posted on how it goes.. Thanks!

**Comment by jyesudian** [comment]
Hi @whummer 

I am able to use the flag and create the kubernetes cluster with version 1.26. Thanks for the fix.

```
qhuser@qhuser-virtual-machine:~/localstack/docker$ kubectl get nodes
NAME                      STATUS   ROLES                  AGE     VERSION
k3d-gw-cluster-server-0   Ready    control-plane,master   6m58s   v1.26.4+k3s1
qhuser@qhuser-virtual-machine:~/localstack/docker$
```

Regards
Yesudian Rajkumar
