### ISSUE TITLE
bug: Localstack not running startup scripts

### ISSUE THREAD

**Issue by seankolczynski** [localstack/localstack#8127]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am using localstack in a kubernetes pod, pulling from this [docker image](https://hub.docker.com/r/localstack/localstack). My config has `startupScriptContent`, which is successfully getting picked up my localstack and being placed under `/docker-entrypoint-initaws.d/<pod-name>init-scripts-config.sh`. However, in the pod's startup process, I am seeing this log:
```
2023-04-12T14:04:33.411 DEBUG --- [  MainThread] localstack.runtime.init    : Init scripts discovered: {BOOT: [], START: [], READY: [], SHUTDOWN: []}
```
So the startup content is in the expected directory, but localstack doesn't discover it at runtime. 
- I have confirmed that I can see and run the file as `root` with no problems from within the pod.
- This is a new issue that began for us on 3/24, and although we have had consistent code changes over that time, I have not been able to pinpoint any localstack config changes at that time. In other words, this began happening to us randomly

Full pod logs:
[localstack.logs.txt](https://github.com/localstack/localstack/files/11213626/localstack.logs.txt)

### Expected Behavior

We expect localstack to be able to discover the startup scripts that it itself has already acknowledged and placed in a specific location.

### How are you starting LocalStack?

With a `docker run` command

#### How are you starting localstack 

Helm deploy, with the values:

```
image:
     repository: "<our artifactory>/docker/localstack/localstack"
  startServices: sqs, s3
  enableStartupScripts: true
  service:
    type: ClusterIP
    edgeService:
      name: edge
      targetPort: 4566
      nodePort: ""
    apiServices: []
  livenessProbe:
    initialDelaySeconds: 180
  debug: true
startupScriptContent: |
    echo "Hello from Sean"
    which awslocal
    awslocal sqs create-queue --queue-name sqs-test-queue-dlq
    awslocal sqs create-queue --queue-name sqs-test-queue --attributes '{ "RedrivePolicy": "{\"deadLetterTargetArn\":\"arn:aws:sqs:us-east-1:000000000000:sqs-test-queue-dlq\",\"maxReceiveCount\":3}" }'
    awslocal s3api create-bucket --bucket cht-notification-stg
```

### Environment

```markdown
- OS: Linux 2
- LocalStack: latest (2.0.2.dev)
```

### Anything else?

I see a similar issue for this [here](https://github.com/localstack/localstack/issues/8048)

**Comment by thrau** [comment]
hi @seankolczynski! the `/docker-entrypoint-initaws.d/` init location was deprecated with 1.0 and removed with localstack 2.0.

The new equivalent would be `/etc/localstack/init/ready.d`. Please give that a try, and you can find more information on our docs: https://docs.localstack.cloud/references/init-hooks/

**Comment by seankolczynski** [comment]
hi @thrau, thanks for getting back to me! 

I did see this doc in my search for an answer, and it's worth noting that in the document it still references the old location
```
├── ready.d          <-- executed when localstack becomes ready (currently equivalent to `/docker-entrypoint-initaws.d`)
```

I'll try with this new location, although I'm not sure how to set this manually, as I assumed localstack did this itself. However this is a great lead, thanks for pointing out that version change!

**Comment by seankolczynski** [comment]
I see that I could set `INIT_SCRIPTS_PATH`, but that is also marked as deprecated. Is there another config value I should set to ensure this path is correct? It's worth noting that I am currently not doing anything to affect this path, in which case I had assumed localstack would use this new path as the default

**Comment by seankolczynski** [comment]
Okay, so adding this to my helm values resolved my problem:
```
localstack:
  startServices: sqs, s3, lambda
  config:
    INIT_SCRIPTS_PATH: /etc/localstack/init
```

This works for me, but I'm just a little surprised that I have to set that path myself, since it's the default Perhaps something with the docker config is changing it?

Thanks again to @thrau for the help, and to everyone for making localstack so useful!

**Comment by thrau** [comment]
Hey @seankolczynski, thanks for pointing out there outdated docs, we'll update those!
Setting the path variable should not be necessary but I'm glad you got it to run!

**Comment by frankjkelly** [comment]
@thrau can you let me know when this works - I tried upgrading from Helm chart 0.4.1 to 0.5.5 and could not get it to work. Probably missing something silly but could not find docs to show the migration path with the new localstack 2.0

**Comment by glaubermd-leaf** [comment]
I've tested on localstack:latest Docker image and it's not working as expected. It works on localstack:1.4 though.

By running a tail on the container logs, I can see it found the startup scripts only when running image version 1.4:

```
$ docker-compose logs -f|egrep "(READY|ERROR|Init scripts discovered|ready\.d)"

localstack-1_4-local | 2023-09-12T22:43:32.022 DEBUG --- [  MainThread] localstack.runtime.init    : Init scripts discovered: {BOOT: [], START: [], READY: [Script(path='/etc/localstack/init/ready.d/01-dynamodb.sh', stage=READY, state=UNKNOWN)], SHUTDOWN: []}
localstack-1_4-local | 2023-09-12T22:43:33.247 DEBUG --- [  MainThread] localstack.runtime.init    : Running READY script /etc/localstack/init/ready.d/01-dynamodb.sh
```

**Comment by joebowbeer** [comment]
@glaubermd-leaf see https://github.com/localstack/localstack/issues/8048#issuecomment-1716884504
