### ISSUE TITLE
bug: Application-autoscaling policies get invalid ARN

### ISSUE THREAD

**Issue by daniel-westerfeld** [localstack/localstack#8132]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am trying to create an application-autoscaling Policy which I want to use as an alarm action for a metric alarm. Using 
```
awslocal application-autoscaling put-scaling-policy --service-namespace ecs \
--scalable-dimension ecs:service:DesiredCount \
--resource-id my_resource \
--policy-name my_policy_name
--policy-type StepScaling
```
results into a Policy with an ARN of the following format
`arn:aws:autoscaling:eu-central-1:scalingPolicy: xxxx:resource/ecs/my_resource:policyName/my_policy_name`
**without** an account ID!

This causes problems since I can't pass the non-valid ARN to my metric alarm. I tested this with Localstack 1.3 (which I am currently using) but also tried it with Localstack 2.0 with the same result. 

### Expected Behavior

I would expect that a Policy with an ARN of the form
`arn:aws:autoscaling:eu-central-1:account_id:scalingPolicy: xxxx:resource/ecs/my_resource:policyName/my_policy_name`
would be created.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

The steps to produce this bug are already described above. Just use the awslocal command to create the Policy and check the ARN in the output.

### Environment

```markdown
- OS: Debian Bullseye
- LocalStack: 2.0
```

**Comment by viren-nadkarni** [comment]
Hi @daniel-westerfeld, we've pushed a fix for this which is available on the latest LocalStack image
