### ISSUE TITLE
bug: ECS doesn't pass command from containerOverrides

### ISSUE THREAD

**Issue by chris-stetter** [localstack/localstack#8141]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When running an ECS task manually and overriding the command, it does not get passed to the container. One can see an empty array in the localstack logs:

```bash
2023-04-14 13:03:38 2023-04-14T11:03:38.385  INFO --- [  Thread-147] l.services.ecs.provider    : Starting ECS task in Docker: image localhost.localstack.cloud:4510/repo-e8dd8a8:latest, container localstack_my-task_1_0_e7994934, command []
2023-04-14 13:03:38 2023-04-14T11:03:38.387  INFO --- [   asgi_gw_2] localstack.request.aws     : AWS ecs.RunTask => 200
2023-04-14 13:03:38 2023-04-14T11:03:38.418 DEBUG --- [  Thread-147] l.services.ecs.provider    : Image: localhost.localstack.cloud:4510/repo-e8dd8a8:latest Name: localstack_my-task_1_0_e7994934 Cmd: [] kwargs: {'ports': <PortMappings: {}>}
```

### Expected Behavior

Similiar to the bug in https://github.com/localstack/localstack/issues/4666, I was expecting that the command gets passed to the task container. 

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal ecs run-task  --cluster $FARGATE_CLUSTER --task-definition $TASK_DEFINITION --launch-type="FARGATE" --network-configuration '{ "awsvpcConfiguration": { "assignPublicIp":"ENABLED", "securityGroups": ["sg-8bdc9639e2d2ce038"], "subnets": ["subnet-fd77cf09"]}}' --overrides '{ "containerOverrides": [ { "name": "CONTAINER_NAME_FROM_TASK", "command": ["sleep", "30"], "environment": [ { "name": "TEST_NAME", "value": "123" } ] } ] }'

### Environment

```markdown
- OS: WSL Ubuntu
- LocalStack: 2.0.1
```

**Comment by chris-stetter** [comment]
@dfangl Are there any plans to fix this in the next release?

**Comment by thrau** [comment]
Hi @chris-stetter! We have a fix in the pipeline which will hopefully be rolled out this week! We'll let you know once it's in the latest image.

**Comment by chris-stetter** [comment]
Awesome! Would be great if you can comment here once included in the latest image 👍
