### ISSUE TITLE
bug: Memory leak in SQS

### ISSUE THREAD

**Issue by michael-robertson** [localstack/localstack#8142]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

With a lot of SQS queues (>300 in our case), localstack python process exhibits a memory leak.

Simply creating the queues, without any activity, is enough.

The exact number of queues to trigger the behavior is unknown.

### Expected Behavior

Memory usage in usual patterns.

### How are you starting LocalStack?

With the `localstack` script

### Steps To Reproduce
```
pip3 install localstack

export DISABLE_EVENTS=1
export EAGER_SERVICE_LOADING=1 SERVICES=sns,sqs,s3
export LS_LOG=warn
export GATEWAY_LISTEN=0.0.0.0:4566 EDGE_PORT=4566
export DNS_ADDRESS=0

localstack start
```
In another terminal:
```
for i in $(seq 300); do
  aws --endpoint-url http://localhost:4566 sqs create-queue --queue-name mprtest$(printf "%03d" $i)
done
```
Then watch the memory step up ~1MB/minute until system dies from starvation, or docker memory limit hit.

### Environment

```markdown
- OS: Ubuntu 22.04 LTS, GCP e2-standard x86/64
- LocalStack: latest (2.0.1)
```

### Anything else?

This also occurred in the previous Localstack 1.x versions, so it was not introduced in 2.0.

**Comment by baermat** [comment]
Hi @michael-robertson , thank you for reporting this! I tried to reproduce this, and you might be right with the leak, however this will take time to track down.
Since you reported ~1MB/minute, let's assume it's 100MB/hour. What tasks are you running that this is blocking you? This shouldn't hit a memory limit any time soon, so it would be really interesting to know how you encountered this. Thank you!

**Comment by michael-robertson** [comment]
Thanks @baermat  - I'm happy to provide more info.

So we are running our whole stack in isolated test environments, meant to be disposable, but complete enough for engineering teams to develop and test their applications. Part of the stack is S3/SQS/SNS, difficult to orchestrate with real AWS, so it is the perfect use case for localstack really, and it does work well. But we found that it regularly died after 3 days as the system runs out of memory, in that case 8GB. Of course we can increase the instance size to give it more memory runway, enough to support longer lifespans, but as you can guess, that puts some constraints on what we can deem "temporary". 

This is the pattern I am seeing, just a script that checks RSS every second, the last number is the positive diff:
```
121916 Mon Apr 17 13:11:09 UTC 2023 264
122180 Mon Apr 17 13:11:10 UTC 2023 264
122444 Mon Apr 17 13:11:12 UTC 2023 264
122708 Mon Apr 17 13:11:13 UTC 2023 264
122972 Mon Apr 17 13:11:16 UTC 2023 264
123240 Mon Apr 17 13:11:17 UTC 2023 268
123504 Mon Apr 17 13:12:13 UTC 2023 264
123768 Mon Apr 17 13:12:14 UTC 2023 264
124032 Mon Apr 17 13:12:15 UTC 2023 264
124296 Mon Apr 17 13:12:16 UTC 2023 264
124300 Mon Apr 17 13:13:11 UTC 2023 4
124568 Mon Apr 17 13:13:12 UTC 2023 268
124832 Mon Apr 17 13:13:13 UTC 2023 264
125096 Mon Apr 17 13:13:15 UTC 2023 264
125364 Mon Apr 17 13:13:16 UTC 2023 268
125628 Mon Apr 17 13:13:17 UTC 2023 264
```
So on roughly one-minute intervals, it adds a short blast of 264K or 268K chunks to the heap.

**Comment by michael-robertson** [comment]
We suspect it has something to do with metrics, which we don't really need (would be nice, but they are secondary). If there is a configuration option we can drop in and keep it happy, that would do just fine.

**Comment by thrau** [comment]
hey folks! @steffyP has made a change to SQS that is now in `latest`, which adds a config option to disable cloudwatch metrics. if you start localstack with `SQS_DISABLE_CLOUDWATCH_METRICS=1`, SQS will no longer send metrics to cloudwatch (which continuously collects metrics in memory, and may be the cause for the memory increase you are seeing)

please give this a try and let us know if this is an acceptable workaround for now!

**Comment by michael-robertson** [comment]
`pip install localstack` still only pulls version 2.0.2.

Specifying latest does not work either:
"ERROR: No matching distribution found for localstack==latest"

Am I missing something?

**Comment by michael-robertson** [comment]
Thinking out loud ...
Since this is a significant functional issue, maybe cloudwatch should be opt-in rather than opt-out.

**Comment by michael-robertson** [comment]
This is looking much better now. The problem I had: while the docker image "latest" has the new options, `pip install localstack` just gets version 2.0.2, which does not propagate the new env vars to the docker run with the `localstack start`. 
I inserted it with `DOCKER_FLAGS` "-e" and that did the trick. 

> how we deal with cross-service integrations in a generalized way

Indeed. Good luck with your efforts. And thanks again.
