### ISSUE TITLE
Is there a way to stop and remove the localstack docker container upon TestRunner completion?

### ISSUE THREAD

**Issue by justinborromeo** [localstack/localstack#815]
Currently, when the LocalstackDockerTestRunner finishes its tests, the container is stopped.  Over time, if those tests are repeatedly run, the number of stopped containers piles up.   Is there any way to stop and remove the localstack docker container upon TestRunner completion?

**Comment by whummer** [comment]
Thanks for reporting @justinborromeo . Should be fixed in #1162
