### ISSUE TITLE
bug: localstack not found after install

### ISSUE THREAD

**Issue by 4ydx** [localstack/localstack#8155]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

pip3 install --upgrade localstack
pip3 list -l

```
localstack        2.0.2
localstack-client 2.0
localstack-core   2.0.2
localstack-ext    2.0.2
```

```
$ localstack
bash: /home/user/.local/bin/localstack: No such file or directory
```

```
python3 -m localstack.cli.main
/usr/bin/python3: Error while finding module specification for 'localstack.cli.main' (ModuleNotFoundError: No module named 'localstack.cli')
```

### Expected Behavior

That localstack cli be available.

### Environment

```markdown
Distributor ID:	Pop
Description:	Pop!_OS 22.04 LTS
Release:	22.04
Codename:	jammy

pip3 list -l
localstack        2.0.2
localstack-client 2.0
localstack-core   2.0.2
localstack-ext    2.0.2
```

**Comment by ackdav** [comment]
Hi @4ydx - is this issue still relevant? And if so, have you considered our installation page here: https://docs.localstack.cloud/getting-started/installation/ ? Thanks!
