### ISSUE TITLE
feature request: CodeArtifact

### ISSUE THREAD

**Issue by vmjorge** [localstack/localstack#8157]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Enhancement description

Localstack is doing a great job allowing developers/Company build their local stack for development, but I believe a stack without a package manager is not a full "package", having [CodeArtifact](https://aws.amazon.com/codeartifact/) implemented will allow for easier and faster development/testing and deploy of applications since it will mimic the AWS environment to its core stack. Even when there are small developments it makes sense, example, when developing lambdas, there could be libraries for logging, for monitoring, for third party integration... that are custom dependencies, built by other teams that you want to incorporate in your current development and keep up to date/patched that could be pulled from LocalStack Artifactory, the same way are pulled from aws CodeArtificat. 

### 🧑‍💻 Implementation

I am not a developer, but there are several OpenSource Projects that could be used as a starting point:
Sonatype Nexus: Nexus 
Apache Archiva
JitPack

### Anything else?

Taken from AWS:
"CodeArtifact allows you to store artifacts using popular package managers and build tools like Maven, Gradle, npm, Yarn, Twine, pip, and NuGet. CodeArtifact can automatically fetch software packages on demand from public package repositories so you can access the latest versions of application dependencies."

**Comment by thegeorgeous** [comment]
Would be nice to have this to test CodeArtifact pipelines without AWS
