### ISSUE TITLE
bug: Issue while calling API Gateway From Test Container Local stack

### ISSUE THREAD

**Issue by bajajyog** [localstack/localstack#8163]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Following error is coming while invoking api gateway end point

API gateway URL :- http://0gopmns3dy.execute-api.localhost.localstack.cloud:4566/Stage/v2/notes/bd5f40de-4168-4d74-b692-d59d68e91234

GET [http://0gopmns3dy.execute-api.localhost.localstack.cloud:4566/Stage/v2/notes/bd5f40de-4168-4d74-b692-d59d68e91234] request body[null] : response [{"__type": "InternalError", "message": "exception while calling apigateway with unknown operation: Unable to find operation for request to service apigateway: GET /Stage/v2/notes/bd5f40de-4168-4d74-b692-d59d68e91234"}]

### Expected Behavior

API gateway call should invoke the lambda and return sucess response

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    This test is done as part of Junit test and I am starting the local stack test container

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal s3 mb s3://mybucket

### Environment

```markdown
- OS:MAC
- LocalStack: 1.4.0
```

### Anything else?

I am checking the test container local stack status  at URL https://app.localstack.cloud/resources/gateway/v1/0gopmns3dy.
API Gateway is created fine in local stack test container. But I am not able to invoke it. Any recommendations to resolve this issue will be helpful

**Comment by bajajyog** [comment]
Thanks for update. I will look into this issue.

**Comment by bajajyog** [comment]
in my component test, I am able to invoke lambda and send msg to queue, why I am not  able to call api gateway in local stack. Please advise do i need to set up Shared docker network for api gateway.

new LocalStackContainer()
                            .withServices(Service.LAMBDA,
                                    Service.SQS,
                                    Service.S3,
                                    Service.IAM,
                                    Service.API_GATEWAY,
                                    Service.CLOUDWATCH,
                                    Service.CLOUDWATCHLOGS,
                                    Service.SSM)
                            .withNetwork(Network.SHARED)
                            .withNetworkAliases(localstackNetworkAlias)
                            .withEnv("LAMBDA_DOCKER_NETWORK", ((Network.NetworkImpl) Network.SHARED).getName())
                            //.withEnv("APIGATEWAY_DOCKER_NETWORK", ((Network.NetworkImpl) Network.SHARED).getName())
                            .withEnv("SQS_DOCKER_NETWORK", ((Network.NetworkImpl) Network.SHARED).getName());

Does APIGATEWAY_DOCKER_NETWORK ENV variable is available in loaclstack?

**Comment by bajajyog** [comment]
Using AWS Local in my junit test, I am invoking the api gateway. now API gateway and lambda getting invoked. My issue is, my path param is not getting passed property. in lambda API, path param value is coming as {noteId} instead of "123"

 LocalStackgetInstance().execInContainer(
                "awslocal", "apigateway", "test-invoke-method", "--rest-api-id", System.getProperty("apiKeyId"), "--http-method", "GET",
                "--resource-id", System.getProperty("resourceId"), "--path-with-query-string", "'" + "/v2/notes/123 + "'", "--stage-variables",
                "{\"local\":\"\"}", 


        );

Any recommendation to pass path params in test-invoke-method.

**Comment by bajajyog** [comment]
Yes,  Still in my test container I am not able to invoke API gateway. I need to do exec in container with curl to make it work. Please advise , how to make it work api gateway from test container.

**Comment by bajajyog** [comment]
my requirement is invoke Local Stack API gateway from Junit test class instead of exec in local stack container. Please advise how to make it work with latest local stack image.

**Comment by alexrashed** [comment]
Hi @bajajyog!
The issue seems that all your testcontainer resources are running in a Docker network (as you configured it), but that means that they are not automatically reachable from your host.
Could you maybe describe a bit why you are explicitly defining a network?
I think your issue might just be resolved by removing all the networking config.

And as a side-note: There is no `SQS_DOCKER_NETWORK` and nor is there an `APIGATEWAY_DOCKER_NETWORK`, since both of these services don't require starting any other docker containers (like it is for lambda).
`LAMBDA_DOCKER_NETWORK` is used to tell the lambda implementation in which docker network new lambda containers should be started (such that they can reach LocalStack, i.e. are in the same network).

**Comment by bajajyog** [comment]
The issue is resolved. In latest local stack, from my test class, I am able to make HTTP call to Local stack API gateway. Any way, i removed networking configs.  In local stack 1.40, it was not working. Thanks for fixing this Local stack 2.x release.
Please close the ticket.
