### ISSUE TITLE
bug: Docker containers in the same network cannot access LocalStack subdomains

### ISSUE THREAD

**Issue by joe4dev** [localstack/localstack#8168]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When trying to access a resource created by LocalStack (e.g., apigateway) from a custom container (see [networking docs](https://docs.localstack.cloud/references/network-troubleshooting/created-resources/#from-your-container)), the client fails to connect to LocalStack subdomains (e.g., `https://ranfcr8c58.execute-api.localhost.localstack.cloud:4566/local`) because Docker networking resolves subdomains to 127.0.0.1 instead to the IP of the LocalStack container (e.g., 192.168.112.2).

```
curl https://ranfcr8c58.execute-api.localhost.localstack.cloud:4566/local
curl: (7) Failed to connect to ranfcr8c58.execute-api.localhost.localstack.cloud port 4566 after 184 ms: Connection refused
```

This issue basically breaks cross-resource container communication 🙀 

Docker networking only resolves the exact domain correctly. For example, `curl https://localhost.localstack.cloud:4566/_localstack/health` works.

#### Upstream Docker Issues

* https://github.com/moby/moby/pull/43444
* https://github.com/docker/compose/issues/7493

#### Related LocalStack Issues

* https://github.com/localstack/localstack/issues/7521
* (potentially) https://github.com/localstack/localstack/issues/8163

### Expected Behavior

Docker containers in the same network as resources created by LocalStack should be able to connect to subdomains. For example, `curl https://*.execute-api.localhost.localstack.cloud:4566/local` should connect to LocalStack successfully.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

Reproducer serverless example: https://github.com/localstack/troubleshooting-issues/tree/main/issue_apigw-subdomain#networking-with-container-client

### Environment

```markdown
- Computer: MacBook Pro M1
- OS: macOS Ventura 13.3.1
- LocalStack: latest (2023-04-19)
- Docker: Docker version 20.10.24, build 297e128
```

**Comment by joe4dev** [comment]
### Further testing

Setup: custom Docker container in the same `ls` network as LocalStack trying to reach LocalStack:

:white_check_mark: Works:
http://localhost.localstack.cloud:4566/_localstack/health
https://localhost.localstack.cloud:4566/_localstack/health

http://localstack:4566/_localstack/health
http://localstack-main:4566/_localstack/health
http://host.docker.internal:4566/_localstack/health

:x: SSL error:
https://localstack:4566/_localstack/health
https://localstack-main:4566/_localstack/health
https://host.docker.internal:4566/_localstack/health

**Comment by joe4dev** [comment]
✅ `localhost.localstack.cloud` resolves correctly

```
dig localhost.localstack.cloud

; <<>> DiG 9.18.11 <<>> localhost.localstack.cloud
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 64150
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;localhost.localstack.cloud.    IN      A

;; ANSWER SECTION:
localhost.localstack.cloud. 600 IN      A       192.168.112.2

;; Query time: 2 msec
;; SERVER: 127.0.0.11#53(127.0.0.11) (UDP)
;; WHEN: Wed Apr 19 08:57:17 UTC 2023
;; MSG SIZE  rcvd: 86
```

❌ Any subdomain `*.localhost.localstack.cloud` resolves to `127.0.0.1`

```
dig ranfcr8c58.execute-api.localhost.localstack.cloud

; <<>> DiG 9.18.11 <<>> ranfcr8c58.execute-api.localhost.localstack.cloud
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 11355
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
; COOKIE: 706c66f843b64abe (echoed)
;; QUESTION SECTION:
;ranfcr8c58.execute-api.localhost.localstack.cloud. IN A

;; ANSWER SECTION:
ranfcr8c58.execute-api.localhost.localstack.cloud. 4502 IN CNAME localhost.localstack.cloud.
localhost.localstack.cloud. 752 IN      A       127.0.0.1

;; Query time: 16 msec
;; SERVER: 127.0.0.11#53(127.0.0.11) (UDP)
;; WHEN: Wed Apr 19 08:56:18 UTC 2023
;; MSG SIZE  rcvd: 120
```

**Comment by unoscar** [comment]
Is there any work around for this. Having the exact same limitation which is preventing me from using this on my development environment

**Comment by simonrw** [comment]
I've started documenting a potential workaround that may help with this situation: https://github.com/localstack/docs/pull/629 [[rendered](https://localstack-docs-preview-pr-629.surge.sh/references/network-troubleshooting/endpoint-url/#wildcard-dns-access)]. I'd like to know your thoughts.

**Comment by BehbudSh** [comment]
@simonrw Hi. Thanks for the solution. Could you please give an example of the configuration?

**Comment by simonrw** [comment]
@BehbudSh I've updated the [preview](https://localstack-docs-preview-pr-629.surge.sh/references/network-troubleshooting/endpoint-url/#wildcard-dns-access) with more concrete usage. Is that what you were after?

You can take the default [docker-compose.yml](https://github.com/localstack/localstack/blob/a3145fde97e873966f63f8ce90d18a89f8a0c881/docker-compose-pro.yml) and add the [extra configuration listed in the example](https://localstack-docs-preview-pr-629.surge.sh/references/network-troubleshooting/endpoint-url/#wildcard-dns-access). Is that enough to get you started?

**Comment by mmn01-sky** [comment]
I had the same issue and solved it following this section of the docs:
https://docs.localstack.cloud/user-guide/aws/apigateway/#alternative-url-format 

I create a Docker network called `aws-local` that my localstack container and my python application container uses which allows the use of container names as the host (docker flag `--name`).

I also changed the default localstack container name to `localstack,.dev` so it passes any regex validations in the boto3 client.

This should be the url format you use to invoke your API Gateway URL:

```
http://{localstack_container_name}:4566/restapis/{rest_api_id}/{rest_api_stage}/_user_request_/{rest_api_path}

Example:
http://localstack.dev:4566/restapis/s0wzwtrjlf/portingxs/_user_request_/broadcast-notification

```

**Comment by simonrw** [comment]
With the new LocalStack DNS server functionality introduced by v2.3.0, you should be able to use subdomains of `localhost.localstack.cloud` from your docker container, with some minor configuration changes shown in our [updated documentation](https://docs.localstack.cloud/references/network-troubleshooting/endpoint-url/#from-your-container). Let me know how you get on with these changes.
