### ISSUE TITLE
bug: S3 returns PutObject => 404 (NoSuchKey) when creating a folder with special character

### ISSUE THREAD

**Issue by ramysiha** [localstack/localstack#8174]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When trying to create a folder with special characters ( e.g. a@a ) S3 will return 404 (NoSuchKey)  error.
what is interesting that the folder will actually be created eventually

` <ListBucketResult>
<IsTruncated>false</IsTruncated>
<Marker/>
<Contents>
<Key>a@a/</Key>
<LastModified>2023-04-20T12:05:04Z</LastModified>
<ETag>"d41d8cd98f00b204e9800998ecf8427e"</ETag>
<Size>0</Size>
<StorageClass>STANDARD</StorageClass>
<Owner>
<DisplayName>webfile</DisplayName>
<ID>
75aa57f09aa0c8caeab4f8c24e99d10f8e7faeebf76c078efc7c6caea54ba06a
</ID>
</Owner>
</Contents>`

### Expected Behavior

S3 PutObject command shall return 200 instead of 404

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    localstack start

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    import boto3
    from localstack_client.patch import enable_local_endpoints
    enable_local_endpoints()
    s3 = boto3.client("s3")
    buckets = s3.list_buckets()
    print(s3.put_object(Bucket='my-test-bucket', Key=('a@a/')))
    print(buckets)

#### Command output
>Traceback (most recent call last):
  File "/tmp/test.py", line 7, in <module>
    print(s3.put_object(Bucket='my-test-bucket', Key=('aaabbg%40derr/')))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rmagdy/.local/lib/python3.11/site-packages/botocore/client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rmagdy/.local/lib/python3.11/site-packages/botocore/client.py", line 960, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.NoSuchKey: An error occurred (NoSuchKey) when calling the PutObject operation: The specified key does not exist.

### Environment

```markdown
- OS: CentOS 7
- LocalStack: 2.0.3.dev
```

**Comment by parthvnp** [comment]
Happy to work on this if needed!

**Comment by giograno** [comment]
Hi @ramysiha, thanks for reporting the issue. You should find a fix in the `latest` Docker image. Please let us know if you have any other issues 🙏

**Comment by ramysiha** [comment]
Thanks @giograno problem has been fixed

**Comment by bentsku** [comment]
Hello @ricardoekm,

I've tried to reproduce your issue with the latest docker image at the moment, and I didn't get the same issue. Would you mind sharing what fails for you, with some LocalStack logs and maybe a small sample?

```
LocalStack version: 2.0.3.dev20230524121028
LocalStack Docker container id: b4273d890d69
LocalStack build date: 2023-05-24
LocalStack build git hash: a726abb
```

My tests:
```python
key = "test@key/"
resp = aws_client.s3.put_object(Bucket=s3_bucket, Key=key, Body=b"test")
{
  "ETag": "\"098f6bcd4621d373cade4e832627b4f6\""
}
resp = aws_client.s3.list_objects_v2(Bucket=s3_bucket)
{
  "EncodingType": "url",
  "IsTruncated": false,
  "KeyCount": 1,
  "MaxKeys": 1000,
  "Name": "test-bucket-localstack",
  "Prefix": "",
  "Contents": [{
    "ETag": "\"098f6bcd4621d373cade4e832627b4f6\"",
    "Key": "test@key/",
    "LastModified": "<datetime>",
    "Size": 4,
    "StorageClass": "STANDARD"
  }]
}
resp = aws_client.s3.get_object(Bucket=s3_bucket, Key=key)
{
  "AcceptRanges": "bytes",
  "Body": "test",
  "ContentLength": 4,
  "ContentType": "binary/octet-stream",
  "ETag": "\"098f6bcd4621d373cade4e832627b4f6\"",
  "LastModified": "<datetime>",
  "Metadata": {}
}
aws_client.s3.delete_object(Bucket=s3_bucket, Key=key)
```

**Comment by ricardoekm** [comment]
Can you please try with the following key 'file%2Fname'?

**Comment by ricardoekm** [comment]
It seems it only breaks with % like in this example 'file%2Fname' @bentsku.

**Comment by bentsku** [comment]
Hi @ricardoekm, I can reproduce the issue and will issue a fix shortly. Thanks!
