### ISSUE TITLE
bug: S3 (AccessDenied) while trying to remove the file from the versioned bucket with legal hold locking enabled

### ISSUE THREAD

**Issue by nickperov** [localstack/localstack#8183]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

1. Create a bucket with object locking enabled.
2. Enable versioning in this bucket.
3. Upload file with **key**.  Received **version1** for this file.
4. Put a legal hold lock on the file (  **key** - **version1**).
5. Upload another file with the same **key**.  Received **version2** for this file.
6.  Put a legal hold lock on the file (  **key** - **version2**).
7. Remove the legal hold lock from the first version of the file  (  **key** - **version1**).
8. Try to delete the first version of the file (  **key** - **version1**) -> get An error occurred (AccessDenied) when calling the DeleteObject operation: Access Denied.

The script would run successfully if we change the order of commands (basically remove versions  of the file in reverse order):
(We have one file with version1 and version2, both locked)

- First, remove the lock from the version2.
- Delete version2.
- Remove the lock from version1.
- Delete version1.

### Expected Behavior

After the legal hold lock removed (Status=OFF) from the first uploaded version of the file, files should be accessible for deletion by its key and version.

### How are you starting LocalStack?

With the `localstack` script

### Steps To Reproduce

```
#!/bin/bash

echo -e "\033[0;32mCreate two text files\033[0m"

echo "Some text version 01..." > example-v1.txt
echo "Some text version 02..." > example-v2.txt

echo -e "\033[0;32mCreate bucket\033[0m"
awslocal s3api create-bucket --bucket my-bucket-001 --create-bucket-configuration LocationConstraint=ap-southeast-2 --region ap-southeast-2 --object-lock-enabled-for-bucket

echo -e "\033[0;32mEnable versioning\033[0m"
awslocal s3api put-bucket-versioning --bucket my-bucket-001 --versioning-configuration Status=Enabled

echo -e "\033[0;32mUpload first version of the file\033[0m"
version1=$(awslocal s3api put-object --bucket my-bucket-001 --key 123456789 --body example-v1.txt | jq -r '.VersionId')

echo -e "\033[0;32mPut lock on the version1 of the file\033[0m"
awslocal s3api put-object-legal-hold --bucket my-bucket-001 --key 123456789 --version-id $version1 --legal-hold Status=ON

echo -e "\033[0;32mUpload second version of the file\033[0m"
version2=$(awslocal s3api put-object --bucket my-bucket-001 --key 123456789 --body example-v2.txt | jq -r '.VersionId')

echo -e "\033[0;32mPut lock on the version2 of the file\033[0m"
awslocal s3api put-object-legal-hold --bucket my-bucket-001 --key 123456789 --version-id version2 --legal-hold Status=ON

echo -e "\033[0;32mRemove lock from the version1 of the file\033[0m"
awslocal s3api put-object-legal-hold --bucket my-bucket-001 --key 123456789 --version-id version1 --legal-hold Status=OFF

echo -e "\033[0;32mDelete version1 of the file\033[0m"
awslocal s3api delete-object --bucket my-bucket-001 --key 123456789 --version-id $version1
```

### Environment

```markdown
- OS: macOS 13.3.1
- LocalStack: latest, 2.0.2, 2.0.3.dev
```

**Comment by bentsku** [comment]
Hi @nickperov and thanks for your report!

I can confirm the issue, it seems it stems from the fact that we ignore the versionId provided when calling `put-object-legal-hold`, so it always set it to the last version. I'm currently working on a fix and will come back here once it's fixed. Thanks again!
