### ISSUE TITLE
bug: resourcegroupstaggingapi does not return consistent results

### ISSUE THREAD

**Issue by miki725** [localstack/localstack#8191]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`resourcegroupstaggingapi` does not seem to return consistent responses. have some buckets/lambdas with tags however locally CLI does not return them correctly

`--resource-type-filters` seems to be completely broken as it never returns any information:

```
➜ awslocal resourcegroupstaggingapi get-resources --resource-type-filters=lambda:s3
{
    "ResourceTagMappingList": []
}


➜ awslocal resourcegroupstaggingapi get-resources --resource-type-filters=lambda:lambda
{
    "ResourceTagMappingList": []
}
```

however querying without filters I get only buckets:

```
➜ awslocal resourcegroupstaggingapi get-resources
{
    "ResourceTagMappingList": [
        {
            "ResourceARN": "arn:aws:s3:::test",
            "Tags": [
                {
                    "Key": "foo",
                    "Value": "bar"
                }
            ]
        }
    ]
}
```

even though some lambdas exist with tags:

```
➜ awslocal lambda list-tags --resource=arn:aws:lambda:us-east-1:000000000000:function:test
{
    "Tags": {
        "Keyfoo": "bar"
    }
}
```

### Expected Behavior

would expect `--resource-type-filters` to filter resources by the resource type vs returning no resources

also expectation is that all tagged resources should be returned including lambdas and other taggable resources as per https://docs.aws.amazon.com/ARG/latest/userguide/supported-resources.html

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

```
docker compose up localstack
```

with compose file service:

```
  localstack:
    image: localstack/localstack-pro:2.0.2
    ports:
      - 4566:4566
    env_file:
      - docker/localstack.config.env
    volumes:
      - localstack:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
```

with env vars:

```
# https://docs.localstack.cloud/localstack/configuration/
ACTIVATE_PRO=0
DEFAULT_REGION=us-east-1
EDGE_PORT=4566
PERSISTENCE=0
LAMBDA_REMOVE_CONTAINERS=1
LAMBDA_DOCKER_NETWORK=co
LAMBDA_LIMITS_CONCURRENT_EXECUTIONS=3
DYNAMODB_SHARE_DB=1
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```
➜ awslocal s3 mb s3://test

➜ awslocal s3api put-bucket-tagging --bucket test --tagging "TagSet=[{Key=foo,Value=bar}]"

➜ awslocal lambda create-function \
          --function-name test \
          --runtime python3.9 \
          --zip-file fileb://$PWD/lambda.zip \
          --handler main.handler \
      	  --role arn:aws:iam::000000000000:role/lambda-role \
		  --tags=Keyfoo=bar
```

the lambda.zip is just a zip of hello world `main.py`:

```python
def handler(event, context):
    print(event)
    print(context)
    return event
```

### Environment

```markdown
- OS: Linux


➜ uname -a
Linux earth 6.1.4-arch1-1 #1 SMP PREEMPT_DYNAMIC Sat, 07 Jan 2023 15:10:07 +0000 x86_64 GNU/Linux
```

- LocalStack: docker container with version 2.0.2
```


### Anything else?

_No response_

**Comment by parthvnp** [comment]
Happy to contribute a fix to this issue if it still needs attention!
