### ISSUE TITLE
bug: Different dynamo behavior in newer localstack (1.4/2.0) vs older localstack (1.2)

### ISSUE THREAD

**Issue by adamdavis40208** [localstack/localstack#8192]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Using localstack:1.2, we can create dynamo tables and quickly use them. Without a wait. We can also list tables with aws cli and see the table we created.

We recently tried updating our images to 1.4/2.0 and experience failing tests around dynamo. Not only does it seem we need to wait a bit before using the table, we're also unable to list the table with the aws cli. 

Re-running the code throws a `ResourceInUseException: Cannot create preexisting table`, so it is getting created "somewhere", I just can't list it with the CLI. 

### Expected Behavior

I'd expect localstack to return a 200 when the table has been created and is ready to use.

I'd expect the aws CLI to list dynamo tables. 

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

My intern and I spun up a repo: 

https://github.com/kevinvuong01/Local_Stack_Issue

### Environment

```markdown
- OS: monterey 12.6.3
- LocalStack: 1.2/2.0
```

**Comment by adamdavis40208** [comment]
Big props to my intern @kevinvuong01 for learning go, docker, and localstack to reproduce this issue in a repo without all of our proprietary cruft in the repo :P

**Comment by steffyP** [comment]
Hi @adamdavis40208,

thanks for reporting. The link to the reproducible sample does not work - could you please check if the repo is public? 🙏 

We are currently working on a fix for a related issue #8100, which might solve your issue as well.

**Comment by adamdavis40208** [comment]
Lol! It was late, nice catch. 

Yell if you want me to test a fix.

Kevin I'm not at work today can you open up your repo to public access and let us know when you get that done?? (another intern having to bail out his mentor)

**Comment by kevinvuong01** [comment]
Hello,

The repo should be public now.

**Comment by kevinvuong01** [comment]
Hello @steffyP ,

I just changed my repo to public now. Let me know if it's not available.

**Comment by adamdavis40208** [comment]
looks good! thanks Kevin <3

**Comment by alexrashed** [comment]
Hi @kevinvuong01!
This issue could have been related to #8194. This PR re-adds a package necessary for DynamoDB to the default Docker image (which removes the necessity of downloading it on demand when the DynamoDB service in LocalStack is initialized).
The fix is already in `localstack/localstack:latest` on DockerHub. Could you maybe verify if this fix resolves your issue as well?
Thanks!

**Comment by kevinvuong01** [comment]
Hey @alexrashed !

When I tested the docker image with `localstack/localstack:latest` or `localstack/localstack:latest@sha256:2e4e6c1c4f19c1832059e64dfad731b627c51be42caa9402c2e3dd7dff686fbb`, I ended up getting the same error involving `ResourceNotFoundException: Cannot do operations on a non-existent table`

**Comment by kevinvuong01** [comment]
Hey @alexrashed,

Sorry for the late reply, I was working on simplifying the demo. I made a separate branch called "simple_table" to hopefully make it easier to debug where in main(), it will set up the client, create the table, and put the item into the table. The difference between the branches would be for this demo, we don't need to read in the .yml files. 

Information to note:
In my main.go: 

- Changes I made starts at line 20-70 (should appear once you are in the new branch)

- Table created in line 37-54

- Line 72-75, I commented out the loop where we loop through until we can PutItem the table. When I tested it, it will unfortunately in the logs it will output this repeatedly for 2.0:
`local_stack_issue-localstack-1  | 2023-05-01T19:45:11.621  INFO --- [   asgi_gw_2] localstack.request.aws     : AWS dynamodb.PutItem => 400 (ResourceNotFoundException)`

- Tested for 1.2, and it works!

New Branch: https://github.com/kevinvuong01/Local_Stack_Issue/tree/simple_table

**Comment by viren-nadkarni** [comment]
@kevinvuong01 I see that in your Docker Compose spec, you are using the [array syntax for environment variables](https://docs.docker.com/compose/compose-file/05-services/#environment):
```
environment:                                                                
  - AWS_ACCESS_KEY_ID="test"                                                
  - AWS_SECRET_ACCESS_KEY="test"                                            
  - AWS_REGION=us-west-2
```
This is causing the `"`s to be taken as literals.

For LocalStack to work correctly, only alphanumeric characters must be used for `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`.
