### ISSUE TITLE
bug: DynamoDB Streams cannot send Byte properties

### ISSUE THREAD

**Issue by TRAD-Anthony-CKO** [localstack/localstack#8199]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Given I create a DynamoDB Table with DynamoDB streams enabled.

When I PUT an item into that table having a Byte property (B)

Then the Lambda plugged into that stream is not triggered. (Version 2.0.2)
OR the Lambda plugged into that stream triggered without this property. (Version 1.4.0)

### Expected Behavior

Given I create a DynamoDB Table with DynamoDB streams enabled.
When I PUT an item into that table having a Byte property (B)
Then the Lambda plugged into that stream will be triggered with the Byte property.

Note that this is the expected behavior on AWS.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker compose up

### Environment

```markdown
- OS: MacOsx M1
- LocalStack: 2.0.2 and 1.4.0
```

### Anything else?

When I enable debug mode with `DEBUG=1`, I can the following error on localstack 2.0.2:

```
2023-04-26T06:36:34.937 DEBUG --- [uncthread156] l.s.a.e.adapters           : Encountered an exception while handling lambda invoke
Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/awslambda/event_source_listeners/adapters.py", line 190, in invoke_with_statuscode
    payload=to_bytes(json.dumps(payload or {})),
  File "/usr/local/lib/python3.10/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable
```

Below is a JSON item example:
```
{
    "pk": {
      "S": "testPK"
    },
    "sk": {
      "S": "testSK"
    },
    "request": {
      "B": "VGhpc0lzQVRlc3Q="
    }
}
```

**Comment by TRAD-Anthony-CKO** [comment]
Tracing back the error, it seems the error is tracing back to [here](https://github.com/localstack/localstack/blob/master/localstack/services/awslambda/event_source_listeners/adapters.py)

Is changing `payload=to_bytes(json.dumps(payload or {}))` to `payload=to_bytes(json.dumps(payload.decode("utf-8") if isinstance(payload, bytes) else payload or {}))` an option here? AFAIK it does apply to other payloads as well

**Comment by giograno** [comment]
Hey @TRAD-Anthony-CKO, thanks for raising the issue. You traced the error correctly. We released a small fix with the `latest` Docker image. Let us know if you have any other issues.

**Comment by TRAD-Anthony-CKO** [comment]
@giograno I just updated to `latest` (localstack 2.2.0), but it seems there's a follow-up problem: 

When localstack invokes the Lambda, it doesn't send the `B` as a Base64 string like AWS does. With the same setup as before, you'll get this log:

```
localstack    | 2023-08-02T18:13:58.793 DEBUG --- [functhread40] l.s.a.i.docker_runtime_exe : Sending invoke-payload
{
    "invoke-id": "509b6ea0-c342-4d72-9173-f58d8baaa6da",
    "invoked-function-arn": "arn:aws:lambda:eu-west-1:000000000000:function:OMITTED",
    "payload": "{\"Records\": [{\"eventID\": \"c1e58428\", \"eventVersion\": \"1.0\", \"awsRegion\": \"eu-west-1\", \"eventName\": \"INSERT\", \"eventSourceARN\": \"arn:aws:dynamodb:eu-west-1:000000000000:table/OMITTED/stream/2023-08-02T17:50:37.362\", \"eventSource\": \"aws:dynamodb\", \"dynamodb\": {\"ApproximateCreationDateTime\": 1690998667.0, \"Keys\": {\"pk\": {\"S\": \"lavender\"}, \"sk\": {\"N\": \"3093338870456911667\"}}, \"NewImage\": {\"pk\": {\"S\": \"lavender\"}, \"sk\": {\"N\": \"3093338870456911667\"}, \"created_on\": {\"S\": \"2023-08-02T17:51:07.473Z\"}, \"request\": {\"B\": \"\\n\\tFantastic\\u0012\\u0004feed\\u001a\\bmagnetic\\\"\\blavender*\\u001330933388704569116672\\u0014Money Market Account:\\btransmitB\\u0003HDDJ\\u0007invoiceP\\u000fZ\\u0004limeb\\u0006matrixj:\\n\\u000bAmeliorated\\u0012\\nwithdrawal\\u001a\\u0006Sports\\\"\\u0003PCI*\\u0005Spurs2\\u000btransparentr\\nSeychellesx\\u0004\\ufffd\\u0001\\u0003\\ufffd\\u0001\\ufffd\\ufffd\\ufffd\\ufffd\\ufffd\\ufffd\\ufffd\\ufffd\\ufffd\\u0001\\ufffd\\u0001\\nconnecting\\ufffd\\u0001\\ufffd\\ufffd\\u00bf\\ufffd\\ufffd\\ufffd\\ufffd\\ufffd\\u0001\\ufffd\\u0001\\fBedfordshire\\ufffd\\u0001:\\t/\\ufffduB\\ufffd?\\ufffd\\u0001\\r\\b\\u0001\\u0010\\ufffd\\ufffd\\ufffd\\ufffd\\ufffd\\ufffd\\u0001\\ufffd\\u0001\\u0003\\ufffd\\u0001\\f\\b\\u0001\\u0010\\u0002 \\u0001(\\u00040\\u0002@\\u0004\\ufffd\\u0001\\u0001\\ufffd\\u0001\\rrevolutionary\\ufffd\\u0001\\u0003RSS\\ufffd\\u0001\\u000b\\b\\u0002\\u0011LsnU;u\\ufffd?\\ufffd\\u0001\\ufffd\\u0001\\n\\u0011clicks-and-mortar\\u0012\\nsynthesize\\u001a%\\n\\u0003USB\\u0012\\u0017Fantastic Frozen Gloves\\u001a\\u0005Zloty\\u001a-\\n\\u0006Israel\\u0012\\u0017Gorgeous Concrete Shoes\\u001a\\ne-business\\u001a1\\n\\ftransmitting\\u0012\\u001aSlovakia (Slovak Republic)\\u001a\\u0005index\\}"
```

Can you advise if I should open a seperate issue for this? Thank you

**Comment by giograno** [comment]
Hi @TRAD-Anthony-CKO, sorry for being so late in the reply! I missed the follow-up message 🙏 
Totally, please open a follow-up separate issue. Thank you very much
