### ISSUE TITLE
Should Lambda invocation type "async" default to False?

### ISSUE THREAD

**Issue by ghost** [localstack/localstack#820]
Hello :)
I've got a question regarding line 179 in localstack/localstack/services/awslambda/lambda_api.py. Should the fourth parameter "async=True" default to False? As currently, it cannot get output from docker images if it gets triggered by the sns. Thanks! :)

**Comment by whummer** [comment]
Thanks for reporting. There have been lots of enhancements in Lambda in the meantime, execution logs should now always get forwarded to CloudWatch logs for consumption. Closing this issue - please report here if the problem persists.
