### ISSUE TITLE
bug: RoleARN should be required but isn't for aws_cloudwatch_event_target

### ISSUE THREAD

**Issue by evbo** [localstack/localstack#8224]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

You can create a resource for `aws_cloudwatch_event_target` that refers to the `arn` of a step function when using LocalStack:

### Expected Behavior

An error should be thrown if the `role_arn` attribute isn't set, which is currently what the actual AWS provider will do, like:

>
│ Error: Creating EventBridge Target failed: ValidationException: RoleArn is required for target arn:aws:states:us-east-1:111111111111:stateMachine:workflow.
│       status code: 400, request id: 6abae953-cc33-42e3-993a-100da8b254d6

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)
terraform apply, with configuration for aws_cloudwatch_event_target that is missing `role_arn`:
```terraform
resource "aws_cloudwatch_event_target" "some_workflow" {
  rule = aws_cloudwatch_event_rule.upload_event.name
  arn  = aws_sfn_state_machine.workflow.arn
  # role_arn is missing and shouldn't be but LocalStack permits it...
}
```

### Environment

```markdown
- OS: arm64v8/ubuntu:22.04
- LocalStack: 1.4.0-arm64
```

### Anything else?

See this topic discussed here: https://stackoverflow.com/a/75677037/1080804

**Comment by rahulmlokurte** [comment]
@evbo The rolearn is optional, but according to terraform provider document, it is Required if ecs_target is used or target in arn is EC2 instance, Kinesis data stream, Step Functions state machine, or Event Bus in different account or region.

Here is the reference. https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_event_target#role_arn 

I can work on this if you don't mind. We need to add few validations in the file localstack/services/events/provider.py on function put_targets. I see, we already have validation for Id field.
