### ISSUE TITLE
bug: Error finding AMI using the BastionHostLinux CDK construct

### ISSUE THREAD

**Issue by russelltaga** [localstack/localstack#8228]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We're using the AWS CDK v2. If you use the [BastionHostLinux CDK construct](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ec2.BastionHostLinux.html), the CDK will pick out an AMI to use to for the new EC2 instance. localstack can't seem to find the AMI although a search in the [AWS EC2 console](https://us-east-1.console.aws.amazon.com/ec2/home?region=us-east-1#Images:visibility=public-images;v=3;$case=tags:false%5C,client:false;$regex=tags:false%5C,client:false) shows that it exists.

### TypeScript CDK snippet
```ts
import {
    BastionHostLinux,
    InstanceClass,
    InstanceSize,
    InstanceType,
} from 'aws-cdk-lib/aws-ec2';

...

const bastionHost = new BastionHostLinux(this, 'bastion-host', {
    vpc,
    instanceType: InstanceType.of(InstanceClass.T2, InstanceSize.MICRO),
    instanceName: `Bastion Host`,
});
```

### Error
`The image id 'ami-06d3b5e1ed9e1d982' does not exist`

```
2023-04-28 15:05:15 botocore.exceptions.ClientError: An error occurred (InvalidAMIID.NotFound) when calling the RunInstances operation: The image id 'ami-06d3b5e1ed9e1d982' does not exist
```

### us-east-1 EC2 console screenshot 
![Screenshot 2023-04-28 at 3 06 22 PM](https://user-images.githubusercontent.com/27798268/235261924-85c9a8cb-8bc1-4de4-a1dc-604da7b4606c.png)

### Expected Behavior

localstack is able to find the AMI

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

Using `docker-compose.yml` and running `docker-compose up -d localstack`

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

Please see description in current behavior section

### Environment

```markdown
- OS: macOS 13 (Ventura)
- LocalStack:

2023-04-28 15:04:40 LocalStack version: 2.0.3.dev20230424170116
2023-04-28 15:04:40 LocalStack Docker container id: 102cf65e3038
2023-04-28 15:04:40 LocalStack build date: 2023-04-26
2023-04-28 15:04:40 LocalStack build git hash: 48fa428
```
```


### Anything else?

_No response_

**Comment by alexrashed** [comment]
Hi @russelltaga!
You can add any images as AMIs to LocalStack by following a specific naming scheme on your local Docker host.
You can find more information in our docs on EC2: https://docs.localstack.cloud/user-guide/aws/elastic-compute-cloud/#base-images
So you can just pull the AMI image, tag it according to your convention, and LocalStack will find it.
Does that resolve your issue?

**Comment by russelltaga** [comment]
Apologies that I overlooked that in the doc. Will confirm this morning, thank you!

**Comment by russelltaga** [comment]
Verified that downloading and tagging the image as explained in [the doc](https://docs.localstack.cloud/user-guide/aws/elastic-compute-cloud/#base-images) fixes it

1. Note AMI ID from localstack error
2. `docker pull amazonlinux:latest`
3. Look up AMI name based on AMI ID in the EC2 console
4. Tag the docker image. Here's the AMI name and ID we were using as an example:

```
docker tag amazonlinux localstack-ec2/amzn2-ami-kernel-5.10-hvm-2.0.20230320.0-x86_64-gp2:ami-04581fbf744a7d11f
```
