### ISSUE TITLE
Lambda invocation status codes do not match AWS API

### ISSUE THREAD

**Issue by ryaanwells** [localstack/localstack#823]
Hello!

We noticed an issue when trying to invoke a Lambda with the "Event" invocation type: the status codes returned by LocalStack do not match the AWS API expectations. From the AWS [docs:](https://docs.aws.amazon.com/lambda/latest/dg/API_Invoke.html#API_Invoke_ResponseSyntax)

- For the RequestResponse invocation type this status code will be 200. 
- For the Event invocation type this status code will be 202. 
- For the DryRun invocation type the status code will be 204.

This looks to be due to how the implementation of the return value from the lambda invocation is handled ([see here](https://github.com/localstack/localstack/blob/master/localstack/services/awslambda/lambda_api.py#L714-L717)). We need to support the Event invocation type and want to check on the correct status code in the response object. We're currently stubbing this out locally by uploading a mocked Lambda which explicitly returns a Flask `Response` object with the status code set to 202 which triggers [this block](https://github.com/localstack/localstack/blob/master/localstack/services/awslambda/lambda_api.py#L715-L716). Ideally we'd like to be in the situation where we could invoke our actual lambda without needing any special wrapper to set the status code we expect.

I'll raise an MR to accurately return the correct status code :)

**Comment by whummer** [comment]
Fixed in #824 - thanks!

**Comment by ryaanwells** [comment]
Thanks @whummer - could you release a new versioned docker release please? 😄
