### ISSUE TITLE
bug: Hypercorn error on initial install.

### ISSUE THREAD

**Issue by Sprbb** [localstack/localstack#8230]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

   / /   ____  _________ _/ / ___// /_____ ______/ /__
   / /   / __ \/ ___/ __ `/ /\__ \/ __/ __ `/ ___/ //_/
  / /___/ /_/ / /__/ /_/ / /___/ / /_/ /_/ / /__/ ,<
 /_____/\____/\___/\__,_/_//____/\__/\__,_/\___/_/|_|

 💻 LocalStack CLI 2.0.2

[16:17:54] starting LocalStack in Docker mode 🐳               localstack.py:142
──────────────── LocalStack Runtime Log (press CTRL-C to quit) ─────────────────

LocalStack version: 2.0.3.dev
LocalStack Docker container id: 5d204224da38
LocalStack build date: 2023-04-27
LocalStack build git hash: 3716e922

2023-04-30T14:17:57.970  INFO --- [-functhread5] hypercorn.error            : Running on https://0.0.0.0:4566 (CTRL + C to quit)
2023-04-30T14:17:57.970  INFO --- [-functhread5] hypercorn.error            : Running on https://0.0.0.0:4566 (CTRL + C to quit)
2023-04-30T14:17:58.183  INFO --- [  MainThread] localstack.utils.bootstrap : Execution of "start_runtime_components" took 602.35ms
Ready.

### Expected Behavior

No errors.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack.

I use these instructions:
https://docs.localstack.cloud/getting-started/installation/#localstack-cli

python3 -m pip install localstack
localstack start.

### Environment

```markdown
- OS: Mint Vera
- LocalStack: 2.0.3.dev
```

**Comment by alexrashed** [comment]
Hi @Sprbb!
Actually, this is not an error. This is how our log message are structured:
```
2023-04-30T14:17:57.970 INFO --- [-functhread5] hypercorn.error : Running on https://0.0.0.0:4566/ (CTRL + C to quit)
^ date                  ^ level  ^ thread       ^ logger name     ^ log message
```
Here's the line in the code actually specifying the format:
https://github.com/localstack/localstack/blob/599e59d742254863107ab5b7d50dc0cf47cc5460/localstack/logging/format.py#L11

So the the `hypercorn.error` here in your example is actually the logger's namespace. And this is what Hypercorn, an underlying library we are using, uses to also log info statements.
You can find the respective section here in Hypercorn:
https://github.com/pgjones/hypercorn/blob/8ae17ca68204d9718389fb3649ca0ed6ba851906/src/hypercorn/logging.py#L104
And the log is written here:
https://github.com/pgjones/hypercorn/blob/8ae17ca68204d9718389fb3649ca0ed6ba851906/src/hypercorn/trio/run.py#L53-L74

If you are experiencing any actual issues, please let us know by creating a new issue. I'll close this one for now. Thanks!

**Comment by raymcdermott** [comment]
ngl, it's a confusing first experience but good to see that it's documented and is not an error.
