### ISSUE TITLE
bug: CEATE_FAILED deployment failed with cdklocal

### ISSUE THREAD

**Issue by Lacoz** [localstack/localstack#8254]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When i try deploy application infra to localstack via cdk (that is already running without problems against real AWS account) i get error when creating ec2 instance 
Jobly-Environment-Development-BastionStack: creating CloudFormation changeset...

 ❌  DevelopmentEnvironment/BastionStack (Jobly-Environment-Development-BastionStack) failed: Error: The stack named Jobly-Environment-Development-BastionStack failed to deploy: CREATE_FAILED (Deployment failed)
    at FullCloudFormationDeployment.monitorDeployment (/home/zigo/almacareer/jobly-serverless/cdk/node_modules/aws-cdk/lib/index.js:359:10236)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async deployStack2 (/home/zigo/almacareer/jobly-serverless/cdk/node_modules/aws-cdk/lib/index.js:362:144773)
    at async /home/zigo/almacareer/jobly-serverless/cdk/node_modules/aws-cdk/lib/index.js:362:128787
    at async run (/home/zigo/almacareer/jobly-serverless/cdk/node_modules/aws-cdk/lib/index.js:362:126793)

 ❌ Deployment failed: Error: Stack Deployments Failed: Error: The stack named Jobly-Environment-Development-BastionStack failed to deploy: CREATE_FAILED (Deployment failed)
    at deployStacks (/home/zigo/almacareer/jobly-serverless/cdk/node_modules/aws-cdk/lib/index.js:362:129094)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async CdkToolkit.deploy (/home/zigo/almacareer/jobly-serverless/cdk/node_modules/aws-cdk/lib/index.js:362:146822)
    at async exec4 (/home/zigo/almacareer/jobly-serverless/cdk/node_modules/aws-cdk/lib/index.js:417:51795)

Stack Deployments Failed: Error: The stack named Jobly-Environment-Development-BastionStack failed to deploy: CREATE_FAILED (Deployment failed)

BastionStack is name of CDK stack that creates ec2 instance. 

Docker logs with DEBUG=1 shows following errors:
jobly-serverless-localstack-1  | 2023-05-04T10:14:21.850 DEBUG --- [uncthread173] l.s.c.e.template_deployer  : Converted parameters: {'InstanceType': 't3.nano', 'ImageId': 'ami-0990f25dae5f0ae14'}
jobly-serverless-localstack-1  | 2023-05-04T10:14:21.851  WARN --- [uncthread173] l.s.c.e.template_deployer  : Error calling <bound method ClientCreator._create_api_method.<locals>._api_call of <botocore.client.EC2 object at 0x7f8df1887d60>> with params: {'InstanceType': 't3.nano', 'ImageId': 'ami-0990f25dae5f0ae14'} for resource: {'Type': 'AWS::EC2::Instance', 'DependsOn': ['bastionInstanceRoleDefaultPolicyAF88F25C', 'bastionInstanceRole5FE40889'], 'Metadata': {'aws:cdk:path': 'DevelopmentEnvironment/BastionStack/bastion/Resource/Resource'}, 'LogicalResourceId': 'bastion2B0A2D9E', 'Properties': {'AvailabilityZone': 'eu-west-1a', 'IamInstanceProfile': 'Jobly-Environment-Development-bastionInstanceProfileE5-8f40614b', 'ImageId': 'ami-0990f25dae5f0ae14', 'InstanceType': 't3.nano', 'SecurityGroupIds': ['sg-4d3a2cc645ce873d2'], 'SubnetId': 'subnet-d8fb88ee', 'Tags': [{'Key': 'Account', 'Value': 'dev'}, {'Key': 'Author', 'Value': 'Stavek Boritel'}, {'Key': 'Environment', 'Value': 'development'}, {'Key': 'Name', 'Value': 'BastionHost'}, {'Key': 'Project', 'Value': 'jobly'}], 'UserData': 'IyEvYmluL2Jhc2g=', 'MinCount': 1, 'MaxCount': 1}, '_state_': {}}
jobly-serverless-localstack-1  | 2023-05-04T10:14:21.852 DEBUG --- [uncthread173] l.s.c.e.template_deployer  : Error applying changes for CloudFormation stack "Jobly-Environment-Development-BastionStack": Parameter validation failed:
jobly-serverless-localstack-1  | Missing required parameter in input: "MaxCount"
jobly-serverless-localstack-1  | Missing required parameter in input: "MinCount" Traceback (most recent call last):
jobly-serverless-localstack-1  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/services/cloudformation/engine/template_deployer.py", line 786, in invoke_function
jobly-serverless-localstack-1  |     result = function(**params)
jobly-serverless-localstack-1  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/client.py", line 530, in _api_call
jobly-serverless-localstack-1  |     return self._make_api_call(operation_name, kwargs)
jobly-serverless-localstack-1  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/client.py", line 919, in _make_api_call
jobly-serverless-localstack-1  |     request_dict = self._convert_to_request_dict(
jobly-serverless-localstack-1  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/client.py", line 990, in _convert_to_request_dict
jobly-serverless-localstack-1  |     request_dict = self._serializer.serialize_to_request(
jobly-serverless-localstack-1  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/validate.py", line 381, in serialize_to_request
jobly-serverless-localstack-1  |     raise ParamValidationError(report=report.generate_report())
jobly-serverless-localstack-1  | botocore.exceptions.ParamValidationError: Parameter validation failed:
jobly-serverless-localstack-1  | Missing required parameter in input: "MaxCount"
jobly-serverless-localstack-1  | Missing required parameter in input: "MinCount"
jobly-serverless-localstack-1  | 
jobly-serverless-localstack-1  | During handling of the above exception, another exception occurred:
jobly-serverless-localstack-1  | 
jobly-serverless-localstack-1  | Traceback (most recent call last):
jobly-serverless-localstack-1  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/services/cloudformation/engine/template_deployer.py", line 1371, in _run
jobly-serverless-localstack-1  |     self.do_apply_changes_in_loop(changes, stack)
jobly-serverless-localstack-1  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/services/cloudformation/engine/template_deployer.py", line 1448, in do_apply_changes_in_loop
jobly-serverless-localstack-1  |     self.apply_change(change, stack=stack)
jobly-serverless-localstack-1  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/services/cloudformation/engine/template_deployer.py", line 1531, in apply_change
jobly-serverless-localstack-1  |     result = execute_resource_action(
jobly-serverless-localstack-1  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/services/cloudformation/engine/template_deployer.py", line 747, in execute_resource_action
jobly-serverless-localstack-1  |     result = configure_resource_via_sdk(
jobly-serverless-localstack-1  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/services/cloudformation/engine/template_deployer.py", line 889, in configure_resource_via_sdk
jobly-serverless-localstack-1  |     return invoke_function(resource_type, func_details, action_name, params, function, resource)
jobly-serverless-localstack-1  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/services/cloudformation/engine/template_deployer.py", line 803, in invoke_function
jobly-serverless-localstack-1  |     raise e
jobly-serverless-localstack-1  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/services/cloudformation/engine/template_deployer.py", line 798, in invoke_function
jobly-serverless-localstack-1  |     result = function(**converted_params)
jobly-serverless-localstack-1  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/client.py", line 530, in _api_call
jobly-serverless-localstack-1  |     return self._make_api_call(operation_name, kwargs)
jobly-serverless-localstack-1  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/client.py", line 919, in _make_api_call
jobly-serverless-localstack-1  |     request_dict = self._convert_to_request_dict(
jobly-serverless-localstack-1  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/client.py", line 990, in _convert_to_request_dict
jobly-serverless-localstack-1  |     request_dict = self._serializer.serialize_to_request(
jobly-serverless-localstack-1  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/validate.py", line 381, in serialize_to_request
jobly-serverless-localstack-1  |     raise ParamValidationError(report=report.generate_report())
jobly-serverless-localstack-1  | botocore.exceptions.ParamValidationError: Parameter validation failed:
jobly-serverless-localstack-1  | Missing required parameter in input: "MaxCount"
jobly-serverless-localstack-1  | Missing required parameter in input: "MinCount"
jobly-serverless-localstack-1  | 

### Expected Behavior

Finish deploy without errors

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

  docker compose

compose.yaml content

volumes:
  data:
services:
  db:
    image: mariadb:10.6.12
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: yes
      MYSQL_DATABASE: jobly
    volumes:
      - data:/var/lib/mysql
      - ./docker/mariadb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "6606:3306"

  localstack:
    image: localstack/localstack-pro
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      LOCALSTACK_API_KEY: <mysecretkey>
      DEBUG: 1
      DOCKER_SOCK:	/var/run/docker.sock
    volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
        - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    npm exec cdklocal deploy -- --all -c account-type=dev -c environment=development

### Environment

```markdown
- OS: Ubuntu 20.04.6 LTS
- LocalStack: localstack/localstack-pro
```

### Anything else?

cdk bootstrap looks sucessfull

 ⏳  Bootstrapping environment aws://000000000000/eu-west-1...
Trusted accounts for deployment: (none)
Trusted accounts for lookup: (none)
Using default execution policy of 'arn:aws:iam::aws:policy/AdministratorAccess'. Pass '--cloudformation-execution-policies' to customize.
CDKToolkit: creating CloudFormation changeset...
 ✅  Environment aws://000000000000/eu-west-1 bootstrapped.

**Comment by alexrashed** [comment]
HI @Lacoz!
Do you know if your stack work against AWS? Looking at the logs I can see some missing parameters.
But unfortunately, it's really hard to pin down your problem without a simple reproducible example.
Would it be possible to provide a minimal stack which just triggers your issue?

Also, when posting a long log, please use the "code" sections. This makes it more readable.
You can do this by using the backticks: \`\`\` your logs \`\`\`

Thanks!
