### ISSUE TITLE
Error: creating Cost And Usage Report Definition

### ISSUE THREAD

**Issue by SebRosander** [localstack/localstack#8275]
Hello team 👋 

I'm trying to create a Cost And Usage Report Definition using Localstack and I'm running into the following error:

```
Error: creating Cost And Usage Report Definition (xxx): InternalFailure: API for service 'cur' not yet implemented or pro feature - please check https://docs.localstack.cloud/references/coverage/ for further information
status code: 501, request id: 33b98d7f-34f9-4f0b-b0be-3c3c0728e836
```

It appears that Localstack does not yet support this feature. I would like to request that the Cost And Usage Report Definition be implemented in Localstack. This would be very helpful for developers who are trying to test and develop against the AWS Cost And Usage Report service.

Please let me know if there are any plans to implement this feature.

**Comment by thrau** [comment]
Thanks for the suggestion @SebRosander.

There are no concrete plans to support Cost And Usage Report Definition yet. Could you elaborate a bit on how you are using this service in your local development or testing flow? Are you automating something around the service and just need the integration to work, or are you looking into getting accurate numbers about costs/usage from localstack?

**Comment by SebRosander** [comment]
Hello @thrau 👋

We are a part of [AWS Service Provider Program](https://aws.amazon.com/partners/programs/solution-provider). As a part of that, we need to provide a third-party / self-developed solution for exposing costs. Since cost explorer and/or billing will showcase the business model for our customers. As a part of the automation of setting up new organizations and cost and usage reports, we are using Terraform and/or Pulumi. So the need is really to get the integration to work, no need for getting accurate numbers. 

In additional context, we are evaluating localstack and are planning on using Team if the request can make the roadmap 😄
