### ISSUE TITLE
AWS SAM docker container is not able to connect to Localstack docker container

### ISSUE THREAD

**Issue by bugidemaheshbabu** [localstack/localstack#8284]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Starting the localstack by running

`$Env:EDGE_BIND_HOST="0.0.0.0"; localstack start -d`

a docker container will be created and available at http://0.0.0.0:4566 mocking AWS services

Lambda Purpose is to return the weather report given city name,

- First search in s3 bucket with city_name if found return that data
- else call Openweatherapi by city_name and insert into s3 bucker and return the data

To run my lambda function with API gateway locally, by

`samlocal local start-api`

a new docker container will be created and available at http://172.0.0.1:3000 with API gateway endpoints

When trying to connect to localstack resources from sam-container,

```
response = requests.get(url="http://0.0.0.0:4566/health")
```

or

```
s3 = boto3.client('s3', endpoint_url="http://0.0.0.0:4566/")
print(s3.list_buckets())
```

Sam server is throwing below error

```
{'errorMessage': "HTTPConnectionPool(host='0.0.0.0', port=4566)
```

I have tried using --docker-network aswell, creating a docker network and add two containers to same network. Still the issue persists.

Is there anything needed to added or another approach to follow?

### Expected Behavior

To connect to s3

### How are you starting LocalStack?

With the `localstack` script

### Steps To Reproduce

Starting the localstack by running

`$Env:EDGE_BIND_HOST="0.0.0.0"; localstack start -d`

Inside lambda app.py
```
response = requests.get(url="http://0.0.0.0:4566/health")
```

To run my lambda function with API gateway locally, by

```
samlocal build
samlocal local start-api
```

### Environment

```markdown
- OS: Windows 10
- LocalStack:latest
- Language: python
```

**Comment by simonrw** [comment]
Hi @bugidemaheshbabu , thanks for raising this issue. 

The IP address `0.0.0.0` is special - it means "listen on all interfaces". It's not an IP address that you can connect with an HTTP client (like `requests`).

Instead, you can get the IP address of the LocalStack container by running `docker inspect localstack_main | jq -r .[0].NetworkSettings.IPAddress`. You can then substitute your IP address into your `requests.get` call.

In general, we have some [networking troubleshooting documentation](https://docs.localstack.cloud/references/network-troubleshooting/) that you may find helpful. In particular, the section on [accessing LocalStack from another docker container](https://docs.localstack.cloud/references/network-troubleshooting/endpoint-url/#from-your-container) may be relevant.
