### ISSUE TITLE
bug: S3 doesn't throw BucketAlreadyExistsException in case bucket already exists (again)

### ISSUE THREAD

**Issue by peter-ponzel** [localstack/localstack#8299]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I can create a bucket over and over again with the same name - without an `BucketAlreadyExistsException` being thrown

### Expected Behavior

when I try to create a bucket that already exists that a corresponding `BucketAlreadyExistsException` is thrown

### How are you starting LocalStack?

Custom (please describe below)

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)
```
final DockerImageName dockerImageName = DockerImageName.parse("localstack/localstack:2.0.2");
final LocalStackContainer localStackContainer = new LocalStackContainer(dockerImageName)
            .withNetworkAliases("localstack")
            .withServices(
                LocalStackContainer.Service.S3,
                LocalStackContainer.Service.SQS
            );
        localStackContainer.start()
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```
s3Client.createBucket(CreateBucketRequest.builder()
            .bucket("foobar")
            .build());

s3Client.createBucket(CreateBucketRequest.builder()
            .bucket("foobar")
            .build());
```

### Environment

```markdown
- OS: opensuse thumbleweed 20230414
- LocalStack: 2.0.2
- org.testcontainers:localstack:1.18.1
- software.amazon.awssdk:s3:2.20.62
- software.amazon.awssdk:sdk-core:2.20.62
```

### Anything else?

this issue was "solved" almost two years ago → https://github.com/localstack/localstack/issues/3540
have been using `localstack/localstack:0.12.7` without issues but now with `2.0.2` there seems to be a regress
... or is this intended, that an instance of `CreateBucketResponse` with all fields `null` is returned instead of throwing the aforementioned exception ?
best regards

**Comment by bentsku** [comment]
Hello @peter-ponzel and thanks for your report.

After testing, it seems we're following what AWS does in that case, specifically the idempotent behaviour of `CreateBucket` in `us-east-1`.

Creating a bucket in `us-east-1`:

```python
import boto3
from mypy_boto3_s3 import S3Client
from secrets import token_hex

session = boto3.Session(region_name="us-east-1")
s3_client: S3Client = session.client("s3")

bucket_name = f"test-bucket-{token_hex(4)}"

for _ in range(3):
    create_bucket = s3_client.create_bucket(Bucket=bucket_name)
    create_bucket.pop("ResponseMetadata")
    print(create_bucket)

s3_client.delete_bucket(Bucket=bucket_name)
> {'Location': '/test-bucket-35fbf7d0'}
> {'Location': '/test-bucket-35fbf7d0'}
> {'Location': '/test-bucket-35fbf7d0'}
```
I believe this specific exception (`BucketAlreadyExistsException`) is raised when the bucket already exists in AWS (must be unique globally), but is not owned by you.

However, this is where AWS behaves a bit weirdly:
- if you try to create a bucket that already exist in `us-east-1` in another region, then you would get a different exception (`BucketAlreadyOwnedByYou`): 
- or if you just try to create the same bucket twice in a different region than `us-east-1`

```python
import boto3
from mypy_boto3_s3 import S3Client
from secrets import token_hex

session = boto3.Session(region_name="us-east-1")
bucket_name = f"test-bucket-{token_hex(4)}"

for region in ("us-east-1", "eu-central-1"):
    s3_client: S3Client = session.client("s3", region_name=region)
    try:
        kwargs = {"Bucket": bucket_name}
        if region != "us-east-1":
            kwargs["CreateBucketConfiguration"] = {"LocationConstraint": region}
        create_bucket = s3_client.create_bucket(**kwargs)
        create_bucket.pop("ResponseMetadata")
        print(create_bucket)
    except s3_client.exceptions.ClientError as e:
        print(e)


s3_client.delete_bucket(Bucket=bucket_name)
# for `us-east-1`
> {'Location': '/test-bucket-19cffd89'}
# for `eu-central-1` after creating in `us-east-1`
> An error occurred (BucketAlreadyOwnedByYou) when calling the CreateBucket operation: Your previous request to create the named bucket succeeded and you already own it.
```

Replacing `for region in ("us-east-1", "eu-central-1"):` with `for region in ("eu-central-1", "us-east-1"):` or `for region in ("eu-central-1", "eu-central-1"):` returns:
```python
# for `eu-central-1`
> {'Location': 'http://test-bucket-efde2dc5.s3.amazonaws.com/'}
# for `us-east-1` or `eu-central-1`, second run
> An error occurred (BucketAlreadyOwnedByYou) when calling the CreateBucket operation: Your previous request to create the named bucket succeeded and you already own it.
```

LocalStack supports both behaviour, in parity with AWS. If you'd like to try in AWS as well, feel free to give us feedback if you think this behaviour is wrong.

**Comment by peter-ponzel** [comment]
@bentsku thank you for this insightful explanation - I also tried it with AWS and you're completely right :+1:
