### ISSUE TITLE
Install Error on Win10:  Could not find a version that satisfies the requirement pypiwin32==220

### ISSUE THREAD

**Issue by pfouilloux** [localstack/localstack#830]
Hi!
I'm trying to install localstack on Windows 10 Pro with python3.7 installed.
Has anyone seen this error before?

```
Collecting pypiwin32==220; sys_platform == "win32" and python_version >= "3.6" (from docker>=2.5.1->moto-ext==1.3.3->localstack)
  Could not find a version that satisfies the requirement pypiwin32==220; sys_platform == "win32" and python_version >= "3.6" (from docker>=2.5.1->moto-ext==1.3.3->localstack) (from versions: 219, 223)
No matching distribution found for pypiwin32==220; sys_platform == "win32" and python_version >= "3.6" (from docker>=2.5.1->moto-ext==1.3.3->localstack)
```

**Comment by IsaacClem** [comment]
I had the same error (with python 3.7 installed). I believe that python3.7 uses pypiwin32 223 rather than 220. Installing python 3.6.6 resolved the issue if this is an option for you.

**Comment by pfouilloux** [comment]
That worked for me!
However, when I try to run the localstack command, it opens the file itself instead of running the program...

Same thing with awscli-local...

I'm going to give up on this for now and run it in a docker container instead.

**Comment by AdilHindistan** [comment]
Same problem with 3.7. Any workarounds other than downgrading?

**Comment by whummer** [comment]
Installation has been entirely refactored - should be fixed in the latest version. Thanks
