### ISSUE TITLE
feature-request: re-add kinesis, provide slim docker image

### ISSUE THREAD

**Issue by kelseyh** [localstack/localstack#8300]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

As of localstack 2.x a number of dependencies are downloaded everytime a localstack container started/used. For example when using kinesis kinesis-mock.jar and dynamodb_local_latest.zip(both around 40Mb) are downloaded. 

I'm assuming this was done to cut down the container size. Of course I could provide a volume to persist "/var/lib/localstack" however this means adding said configuration in every project that uses localstack and you'll pay the cost in each project.  

### Expected Behavior

The image should just contain the required dependencies as before. 

### How are you starting LocalStack?

With a `docker run` command

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run -it --rm  -e DEBUG=true -e AWS_ACCESS_KEY_ID=foobar -e AWS_SECRET_ACCESS_KEY=foobar -e HOSTNAME_EXTERNAL=test-localstack --name test-localstack localstack/localstack:2.0.2

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)
  awslocal kinesis create-stream --stream-name some-stream --shard-count 1 --region eu-west-1

### Environment

```markdown
- OS: mac
- LocalStack: 2.0.2
```

**Comment by alexrashed** [comment]
Hi @kelseyh!
Unfortunately, there is a fine line between adding everything that's needed to run all the services VS the image size.
However, the conclusion is that for now we only want to include the infrastructure used for the top used services in the default images right now. The rest will be downloaded on demand and cached on the host (as you already mentioned).

We had a discussion in #8194, the conclusion is that for now we only want to include the infrastructure used for the top used services in the default images right now. The rest will be downloaded on demand and cached on the host (as you already mentioned). DynamoDB is a top-used service and has been added again with https://github.com/localstack/localstack/pull/8194 (this is already in `latest`). Kinesis will not be added for now.

In this issue, we also discussed several alternatives: https://github.com/localstack/localstack/pull/8194#issuecomment-1522025328

Please let me know if this helps! Thanks!

**Comment by kelseyh** [comment]
Hi @alexrashed 
Thank you for your response, I appreciate that you're trying to slim down the image. I wonder if following a similar approach to many other projects whereby they provide a `slim` version of the image would be a happy medium?

**Comment by alexrashed** [comment]
Hi @kelseyh!
We are thinking about providing a `slim` image in the future, but unfortunately I cannot give you a timeline for a change like this right now.
