### ISSUE TITLE
Enhancement request: implement Custom SMS sender Lambda trigger

### ISSUE THREAD

**Issue by MarcelStranak** [localstack/localstack#8305]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Enhancement description

Missing implementation of [Custom SMS sender Lambda trigger](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-custom-sms-sender.html)  
Based on [Slack](https://localstack-community.slack.com/archives/C04NFFHPL5V) request.

**Comment by rutviklhase** [comment]
Hello, I can take this up. Is anybody else working on this already?

**Comment by scottclary-level** [comment]
@rutviklhase This would be very helpful to get implemented!

**Comment by whummer** [comment]
Hi @scottclary-level , quick update - we have now pushed a couple of enhancements for Cognito, including initial support for `CustomSMSSender` Lambda triggers. When you get a chance, can you please pull the `latest` Docker image and give it a try? Please keep us posted on how it goes.. Thanks!

**Comment by scottclary-level** [comment]
@whummer 
This works for me now thank you!
