### ISSUE TITLE
bug: sts assume-role succeeds even if role doesn't exist

### ISSUE THREAD

**Issue by PikaBlue107** [localstack/localstack#8313]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When running `sts assume-role`, the request may succeed even if the role at the specified ARN is not already defined.

### Expected Behavior

When running `sts assume-role`, the request should fail if the role at the specified ARN is not already defined.

### How are you starting LocalStack?

With a `docker run` command

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal sts assume-role --role-arn arn:aws:iam::000000000000:role/this-role-doesnt-exist --role-session-name fear-me

### Environment

```markdown
- OS: macOS Monterey 12.6.5 (21G531)
- LocalStack: latest
```

### Anything else?

This actually makes things easier for me ([relevant xkcd](https://xkcd.com/1172/)), but still seems unintentional, or at least undocumented.

General references:
- LocalStack STS documentation: https://docs.localstack.cloud/references/coverage/coverage_sts/
- AWS CLI `sts assume-role` documentation: https://docs.aws.amazon.com/cli/latest/reference/sts/assume-role.html

**Comment by ccatterina** [comment]
Hi, I was looking at this issue because I would like to contribute to the project. But I don't think this is a bug because it is a documented and motivated behaviour of moto (http://docs.getmoto.org/en/latest/docs/services/sts.html) which I believe localstack uses to implement the sts service. 

> Assume an IAM Role. Note that the role does not need to exist. The ARN can point to another account, providing an opportunity to switch accounts.
