### ISSUE TITLE
Wrong Location returned using new Javascript SDK

### ISSUE THREAD

**Issue by luantoningalvan** [localstack/localstack#8315]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I upload something using the new  S3 javascript library, the Location attr returned is wrong(without de port). Obs: My bucket name is revendi.

```
import {
  CompleteMultipartUploadCommandOutput,
  S3Client,
} from "@aws-sdk/client-s3";
import { Upload } from "@aws-sdk/lib-storage";

export class WasabiService {
  private client: S3Client;

  constructor() {
    const endpoint =
      process.env.NODE_ENV === "production"
        ? "https://s3.wasabisys.com"
        : "http://localhost:4566";

    this.client = new S3Client({
      region: process.env.AWS_REGION,
      forcePathStyle: true,
      endpoint: endpoint,
    });
  }

  public saveFile(
    key: string,
    body: Buffer
  ): Promise<CompleteMultipartUploadCommandOutput> {
    const parallelUploads3 = new Upload({
      client: this.client,
      params: {
        Bucket: process.env.BUCKET_NAME,
        Key: key,
        Body: body,
        ACL: "public-read",
      },
    });

    return parallelUploads3.done();
  }
}
```

Returned Location: http://localhost/revendi/0z0wbqra97k.jpg

### Expected Behavior

But everthing works fine when I use the old SDK

import aws, { S3 } from "aws-sdk";

```
export class WasabiService {
  private client: S3;

  constructor() {
    this.client = new aws.S3({
      endpoint:
        process.env.NODE_ENV === "production"
          ? "https://s3.wasabisys.com"
          : "http://localhost:4566",
      s3ForcePathStyle: true,
    });
  }

  public async saveFile(
    key: string,
    body: Buffer
  ): Promise<S3.ManagedUpload.SendData> {
    const result: S3.ManagedUpload.SendData = await new Promise((res, rej) => {
      this.client.upload(
        {
          Bucket: process.env.BUCKET_NAME,
          Key: key,
          ACL: "public-read",
          Body: body,
        },
        (err, data) => {
          if (err) {
            rej(err);
          }
          res(data);
        }
      );
    });

    return result;
  }
}
```
Returned Location: http://localhost:4566/revendi/qkusljoq7z.jpg

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

Create a projet with the new S3 sdk

### Environment

```markdown
- OS:Ubuntu 22.04
- LocalStack:latest
```

**Comment by bentsku** [comment]
Hi @luantoningalvan and thanks for your report!

Sadly, this seems to be an issue on the AWS SDK side, and we have no control over it. Maybe you should open the issue directly [on their repo](https://github.com/aws/aws-sdk-js-v3) to see if they could fix that?

**Comment by jaymdq** [comment]
Hey guys! Found the same problem but using another provider. I found a workaround by passing the following configuration to the S3 client. Please, notice that this is not a FIX but a workaround until the AWS SDK team fixes this problem.

```
this.client = new S3Client({
   credentials: {
      accessKeyId: config.s3.accessKey,
      secretAccessKey: config.s3.secretKey,
    },
    region: 'us-east-1',
    forcePathStyle: true,
    endpoint: {
      protocol: 'http:',
      hostname: 'localhost:9000', // Here is the hack!
      path: '/',
     },
});
```

CC @luantoningalvan

**Comment by bentsku** [comment]
I'll close the issue as the workaround provided by https://github.com/localstack/localstack/issues/8315#issuecomment-1578321693 is working. Thanks for your report!

**Comment by bolt-juri-gavshin** [comment]
FYI: a [PR](https://github.com/aws/aws-sdk-js-v3/pull/6282) with a fix was just merged.
Hopefully the next AWS-SDK V3 version will include it.
