### ISSUE TITLE
bug: User guide article on self-managed kafka seems not to work

### ISSUE THREAD

**Issue by gudjonragnar** [localstack/localstack#8328]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am following this article from the user guide: https://docs.localstack.cloud/user-guide/integrations/kafka/
Following the guide works fine until step 5. The error I get is:
```
awslocal lambda create-event-source-mapping --topics t1 --source-access-configuration Type=SASL_SCRAM_512_AUTH,URI=arn:aws:secretsmanager:us-east-1:000000000000:secret:localstack-TDIuI --function-name arn:aws:lambda:us-east-1:000000000000:function:fun1 --self-managed-event-source '{"Endpoints":{"KAFKA_BOOTSTRAP_SERVERS":["localhost:9092"]}}'

An error occurred (InvalidParameterValueException) when calling the CreateEventSourceMapping operation: Unrecognized event source.
```
There is no more information in the docker logs that I can see.
I tried downgrading to localstack 1.4.0 but I faced another issue. The above command worked but in the docker logs I see:
```
localstack-main  | 2023-05-17T15:10:01.620 ERROR --- [   Thread-14] kafka.conn                 : Connect attempt to <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]> returned error 111. Disconnecting.
localstack-main  | 2023-05-17T15:10:01.669 ERROR --- [   Thread-14] kafka.conn                 : Connect attempt to <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]> returned error 111. Disconnecting.
localstack-main  | 2023-05-17T15:10:01.719 ERROR --- [   Thread-14] kafka.conn                 : Connect attempt to <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]> returned error 99. Disconnecting.
localstack-main  | 2023-05-17T15:10:01.719  INFO --- [   Thread-14] l.s.a.lambda_extended      : Unable to check Kafka topics ['t1'] in server localhost:9092 for new Lambda messages: NoBrokersAvailable
```

### Expected Behavior

I would expect the user guide to work without errors

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

Follow the steps in the user guide article: https://docs.localstack.cloud/user-guide/integrations/kafka/

### Environment

```markdown
- OS: MacOS Ventura 13.3.1 (Macbook Pro M2)
- LocalStack: latest (pro)
```

**Comment by mmarkell** [comment]
+1, I'm having the same issue

**Comment by janario** [comment]
Any updates here? I have the same issue :-/

**Comment by antoniopangallo** [comment]
+1 I'am getting same error

**Comment by joe4dev** [comment]
Hi @antoniopangallo @gudjonragnar @mmarkell @janario Our new Lambda event source mapping implementation provides better support for the Kafka source, including self-managed Kafka. Does our latest version resolve this issue?

Check out our new Lambda event source mapping (ESM) implementation in [LocalStack v4](https://blog.localstack.cloud/announcing-localstack-40-general-availability/) offering better functional and non-functional support for ESM 🚀 . The behavioral coverage documentation provides more details for your use case https://docs.localstack.cloud/user-guide/aws/lambda/#lambda-event-source-mappings

Feel free to open another issue or share your feedback if you experience any challenges👂
