### ISSUE TITLE
bug: "apigateway get-stages" returns object with "item" key  instead of "items."

### ISSUE THREAD

**Issue by n-arakawa** [localstack/localstack#8330]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

got  result with "item" key

```
$ awslocal apigateway get-stages --rest-api-id $key
    "item": [
        {

```

### Expected Behavior

according to the AWS document, key must be "items".

https://awscli.amazonaws.com/v2/documentation/api/latest/reference/apigatewayv2/get-stages.html#examples

```
$ awslocal apigateway get-stages --rest-api-id $key
    "items": [
        {

```

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```
#!/bin/sh
set -eux
API_NAME=my-Api
awslocal apigateway create-rest-api --name "$API_NAME"
api_id="$(awslocal apigateway  get-rest-apis --output text --query "items[?name=='$API_NAME'].id | [-1]")"
awslocal apigateway get-stages --rest-api-id "$api_id"
```

### Environment

```markdown
- OS: Ubuntu23.04
- LocalStack:latest(docker)
```

**Comment by viren-nadkarni** [comment]
Hi @n-arakawa, `apigateway` and `apigatewayv2` are distinct APIs.

`GetStages` for v1 is documented [here](https://docs.aws.amazon.com/apigateway/latest/api/API_GetStages.html) and for v2 [here](https://docs.aws.amazon.com/apigatewayv2/latest/api-reference/apis-apiid-stages.html). LocalStack returns the correct response as per these specs.

**Comment by n-arakawa** [comment]
Oh my,
This inconsistency in key must be  BUG in AWS!
