### ISSUE TITLE
bug: AWS::SES::ConfigurationSet doesn't appear to exist via CDK/Cloudformation but does via API

### ISSUE THREAD

**Issue by liam-careerhub** [localstack/localstack#8331]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm trying to deploy an `AWS::SES::ConfigurationSet` via the C# AWS CDK (local). I get the following error:

```
Unexpected resource type AWS::SES::ConfigurationSet when resolving references of resource SesConfigurationSet4DAFC9AF: {"Type": "AWS::SES::ConfigurationSet", "Metadata": {"aws:cdk:path": "EmailService/Development/SesConfigurationSet/Resource"}, "LogicalResourceId": "SesConfigurationSet4DAFC9AF", "Properties": {"Name": "ConfigurationSet", "ReputationOptions": {"ReputationMetricsEnabled": true}, "SendingOptions": {"SendingEnabled": true}}, "PhysicalResourceId": null}. To find out if AWS::SES::ConfigurationSet is supported in LocalStack Pro, please check out our docs at https://docs.localstack.cloud/user-guide/aws/cloudformation/#resources-pro--enterprise-edition
```

I found this issue: #7184 which shows examples of how these resources can be deployed via the CLI, so I think that the CloudFormation mappings for SES are missing.

### Expected Behavior

I expect to be able to deploy `AWS::SES::ConfigurationSet` to LocalStack via the CDK.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

docker compose up --wait --build --remove-orphans

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

Example CDK stack:

``` csharp
    public class DevelopmentStack : Stack {
        public DevelopmentStack(
            Construct scope,
            string id
        ) : base(scope, id, null) {
            var configSet = new ConfigurationSet(
                this,
                "SesConfigurationSet",
                new ConfigurationSetProps {
                    ConfigurationSetName = $"ConfigurationSet",
                    ReputationMetrics = true,
                    SendingEnabled = true
                }
            );

            var sesEventTopic = new Topic(
                this,
                "SesEventTopic",
                new TopicProps {
                    TopicName = "SesTopic",
                    Fifo = false
                }
            );

            configSet.AddEventDestination(
                "SesEventDestination",
                new ConfigurationSetEventDestinationOptions {
                    Destination = EventDestination.SnsTopic(sesEventTopic),
                    Events = new[] {
                        EmailSendingEvent.BOUNCE,
                        EmailSendingEvent.COMPLAINT,
                        EmailSendingEvent.DELIVERY,
                        EmailSendingEvent.REJECT
                    }
                }
            );
        }
    }
```

Deployed by `cdklocal deploy EmailService/Development`

### Environment

```markdown
- OS: Windows 11
- LocalStack container: localstack/localstack:2.0.2
- Deployment container: custom based on mcr.microsoft.com/dotnet/sdk:7.0 with `cdklocal`
- LocalStack: 2.0.2 and latest
```

### Anything else?

In the error message I see a link to https://docs.localstack.cloud/user-guide/aws/cloudformation/#resources-pro--enterprise-edition but that page doesn't list these resources anywhere (is it out of date?).

**Comment by simonrw** [comment]
Hi @liam-careerhub, thanks for raising this issue. I can confirm that currently `AWS::SES::ConfigurationSet` and `AWS::SES::ConfigurationSetEventDestination` are not supported by LocalStack. I'll update this issue with more information when they are available for use with CloudFormation.
