### ISSUE TITLE
enhancement request: Support for Glue Version 4.0

### ISSUE THREAD

**Issue by snhardin** [localstack/localstack#8334]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Enhancement description

Localstack seems to only recognize up to Glue Version 3.0. Amazon has (fairly recently) added support for Glue Version 4.0. This includes support for a newer version of Python and a newer version of Spark. See [here](https://docs.aws.amazon.com/glue/latest/dg/release-notes.html) for more information.

Right now, if you try to use Glue Version 4.0 when running a job in Localstack, it shows a message saying that the Glue Version is unrecognized and defaults to Spark 2. Spark 2 is likely to break Glue jobs that use version 3.0 and above.

### Anything else?

Related to #6374

**Comment by alexrashed** [comment]
Hi @snhardin!
We just implemented initial support for Glue 4.0 with Spark 3.3. It is already contained in the `localstack/localstack-pro:latest` and `localstack/localstack-pro:latest-bigdata` images on DockerHub.
I will close this issue for now. Please open a new issue if you are facing any issues with this newly implemented feature.
Thanks!
