### ISSUE TITLE
enhancement request: Support --extra-py-files flag for Glue

### ISSUE THREAD

**Issue by snhardin** [localstack/localstack#8335]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Enhancement description

It would be nice if Localstack supported some basic functionality of the `--extra-py-files` flag for Glue Jobs. More specifically, the functionality we'd really like is the ability to point this flag to a ZIP file and have Glue unzip these files right next to where our entrypoint script is. I'm currently doing this manually to our localstack instance and it seems to be working well:

```bash
docker cp my-library.zip localstack_main:/tmp
docker exec -it localstack_main /bin/bash
cd /tmp
unzip my-library.zip
# Exit container here and run Glue Job
# ...
# Glue Job references my-library.zip correctly
```

`--extra-py-files` seems to have support for `.egg` and `.whl` files as well, although we've been installing these dependencies just fine by using the `--additional-python-modules` flag, which Localstack does support. 🙂

Right now, if you try to use the `--extra-py-files` flag, Localstack does nothing. It does not seem to acknowledge this flag at all from what I can tell in the logs with `DEBUG=1`.

### Anything else?

More info on the flag [here](https://docs.aws.amazon.com/glue/latest/dg/aws-glue-programming-python-libraries.html).

**Comment by alexrashed** [comment]
Hi @snhardin!
Actually, LocalStack's Glue implementation already has support for extra python files. However, you have to add them to an S3 bucket and add these python files (with the `s3://` schema prefix) to the `--extra-py-files` argument.
These files will then be downloaded from S3 (internally in localstack) and added to the python path.
Please let me know if that works for you :)

**Comment by alexrashed** [comment]
I'll close this issue for now, please feel free to open a new issue if you are still having issues with this feature of Glue (or if you are experiencing any other issues). Thanks!
