### ISSUE TITLE
bug: Persistance for Lambda provisioned concurrency

### ISSUE THREAD

**Issue by joe4dev** [localstack/localstack#8347]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When using `PERSISTENCE=1`, Lambda provisioned concurrency is not restored upon restarting LocalStack. Hence, listing the provisioned concurrency (i.e., `lambda.GetProvisionedConcurencyConfig) config fails with an `AttributeError: 'NoneType' object has no attribute 'available'

### Expected Behavior

Lambda provisioned concurrency configuration should be restored after LocalStack restart when using `PERSISTENCE=1`.

### How are you starting LocalStack?

Custom (please describe below)

### Steps To Reproduce

1. Start LocalStack with `PERSISTENCE=1`
2. Create a Lambda function with [provisioned concurrency](https://docs.aws.amazon.com/lambda/latest/dg/provisioned-concurrency.html)
3. Listing the concurrency config works `awslocal lambda get-provisioned-concurrency-config --function-name my-lambda --qualifier latest`
4. Re-start LocalStack
5. Listing the concurrency config fails `awslocal lambda get-provisioned-concurrency-config --function-name my-lambda --qualifier latest`

```
$ awslocal lambda get-provisioned-concurrency-config --function-name my-lambda --qualifier latest

An error occurred (InternalError) when calling the GetProvisionedConcurrencyConfig operation (reached max retries: 4): exception while calling lambda.GetProvisionedConcurrencyConfig: Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/aws/chain.py", line 90, in handle
    handler(self, self.context, response)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/aws/handlers/service.py", line 123, in __call__
    handler(chain, context, response)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/aws/handlers/service.py", line 93, in __call__
    skeleton_response = self.skeleton.invoke(context)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/aws/skeleton.py", line 154, in invoke
    return self.dispatch_request(context, instance)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/aws/skeleton.py", line 166, in dispatch_request
    result = handler(context, instance) or {}
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/aws/skeleton.py", line 118, in __call__
    return self.fn(*args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/services/awslambda/provider.py", line 2483, in get_provisioned_concurrency_config
    AvailableProvisionedConcurrentExecutions=ver_manager.provisioned_state.available,
AttributeError: 'NoneType' object has no attribute 'available'
```

### Environment

```markdown
- OS: all
- LocalStack: 2.0.2 or `latest` (2023-05-22)
```

### Anything else?

The persistence issue was initially reported by @davecardwell in the feature request https://github.com/localstack/localstack/issues/7080

**Comment by indrabasak** [comment]
Any traction on provisioned concurrency? The latest image still has the same issue

**Comment by joe4dev** [comment]
Hi @davecardwell and @indrabasak 

Persistence for Lambda provisioned concurrency is now implemented. Please pull the `latest` LocalStack image and give it a try 🚀 

We are looking forward to hearing your feedback 👂
