### ISSUE TITLE
Localstack doesn't return bucket Name in case using TransferManager.java

### ISSUE THREAD

**Issue by dhirajsable** [localstack/localstack#8359]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I Have uploaded some file in S3 bucket and I can see all files in locatsack. Now my code is trying to download all files using TransferManager (aws-java-sdk-s3-1.12.466.jar)

`java.lang.IllegalArgumentException: The bucket name parameter must be specified when requesting an object's metadata
	at com.amazonaws.services.s3.AmazonS3Client.rejectNull(AmazonS3Client.java:4014)
	at com.amazonaws.services.s3.AmazonS3Client.getObjectMetadata(AmazonS3Client.java:1359)
	at com.amazonaws.services.s3.transfer.TransferManager.prepareDownload(TransferManager.java:1094)
	at com.amazonaws.services.s3.transfer.TransferManager.downloadDirectory(TransferManager.java:1488)
	at com.amazonaws.services.s3.transfer.TransferManager.downloadDirectory(TransferManager.java:1350)
	at com.amazonaws.services.s3.transfer.TransferManager.downloadDirectory(TransferManager.java:1341)`

its falling at this line for Localstack https://github.com/aws/aws-sdk-java/blob/1.12.466/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/AmazonS3Client.java#L1360

But my QA and Stage and Prod works perfectly fine with real AWS S3 bucket. 
Please guide How I can solve this issue?

Thanks.

### Expected Behavior

I should be able to download the file from S3 bucket.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    Upload files to S3 bucket and try to download it 

### Environment

```markdown
- OS: MAC OS
- LocalStack: 2.0.2
```

### Anything else?

NA

**Comment by bentsku** [comment]
Hello @dhirajsable and thanks for your report!

Could you share the Java snippet that is producing the error for you, so that we could reproduce? Thanks!

**Comment by dhirajsable** [comment]
This is code which is getting above exception 

`TransferManager transferManager = TransferManagerBuilder.standard().withS3Client(client).build();
            MultipleFileDownload xfer = transferManager.downloadDirectory(bucketName, key, path.toFile());
            xfer.waitForCompletion();`

the S3 client is passed is created for Localstack.

**Comment by bentsku** [comment]
Thanks! And how is the `bucketName` variable declared or retrieved?

**Comment by dhirajsable** [comment]
bucketName is declared in properties file. When I debug the code, I can see the correct bucket name

**Comment by bentsku** [comment]
Thanks! I could now reproduce, and the issue seems to stem from the fact that the following snippet returns a `bucketName=null` for the object summary:

```java
ObjectListing listObjectsResponse = s3.listObjects(new ListObjectsRequest().withBucketName(bucketName));
> [S3ObjectSummary{bucketName='null', key='pre_test1.txt', eTag='d41d8cd98f00b204e9800998ecf8427e', size=0, lastModified=Wed May 24 09:39:11 CEST 2023, storageClass='STANDARD', owner=S3Owner [name=webfile,id=75aa57f09aa0c8caeab4f8c24e99d10f8e7faeebf76c078efc7c6caea54ba06a]}, S3ObjectSummary{bucketName='null', key='pre_test2.txt', eTag='d41d8cd98f00b204e9800998ecf8427e', size=0, lastModified=Wed May 24 09:39:08 CEST 2023, storageClass='STANDARD', owner=S3Owner [name=webfile,id=75aa57f09aa0c8caeab4f8c24e99d10f8e7faeebf76c078efc7c6caea54ba06a]}, S3ObjectSummary{bucketName='null', key='test.txt', eTag='d41d8cd98f00b204e9800998ecf8427e', size=0, lastModified=Wed May 24 09:38:21 CEST 2023, storageClass='STANDARD', owner=S3Owner [name=webfile,id=75aa57f09aa0c8caeab4f8c24e99d10f8e7faeebf76c078efc7c6caea54ba06a]}, S3ObjectSummary{bucketName='null', key='test2.txt', eTag='d41d8cd98f00b204e9800998ecf8427e', size=0, lastModified=Wed May 24 09:38:26 CEST 2023, storageClass='STANDARD', owner=S3Owner [name=webfile,id=75aa57f09aa0c8caeab4f8c24e99d10f8e7faeebf76c078efc7c6caea54ba06a]}]
```

I'll try to work on a fix and I'll you know when there's any progress. Thanks!

**Comment by dhirajsable** [comment]
is this issue fixed now ?

**Comment by dhirajsable** [comment]
Thanks for fixing it. With latest docker image, I don't see the issue. That's really helpful

**Comment by bentsku** [comment]
Thanks for your feedback @dhirajsable, glad to hear we got it fixed!
