### ISSUE TITLE
S3 createBucket domain resolving issue for AWS SDK for PHP

### ISSUE THREAD

**Issue by BentCoder** [localstack/localstack#836]
Hi,

This issue is similar to [the one here](https://github.com/localstack/localstack/issues/43) but PHP version.

I have my application running on a vagrant box (`192.168.10.10`) and I have the localstack docker container running (`$ docker-compose up -d`) running on another vagrant box (`192.168.10.20`). I have `192.168.10.20 localstack` defined in `/etc/hosts` file of application vagrant box.

When I call `createBucket(['Bucket' => 'hello'])` method on `S3` in my application, I get the error below.

> Error executing "CreateBucket" on "http://hello.localstack:4572/"; AWS HTTP error: cURL error 6: Could not resolve host: hello.localstack (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

This error occurs because `hello.localstack` domain doesn't exist in `/etc/hosts` file. If I put it there, it works! However, as you can imagine this is not a viable solution because `hello` can be anything.

Is there a solution for this issue?

Thanks

**Comment by BentCoder** [comment]
Hi @whummer Apologies for direct messaging. Have you got any idea how issue above could possibly be resolved?

**Comment by bastuijnman** [comment]
Hi @BentCoder,

The solution is similar to what was described in the other issue. When creating the S3 client you can pass in: `use_path_style_endpoint=>true` into your config array.

That should solve the issue you're having.

**Comment by BentCoder** [comment]
It redirects to AWS host URL rather than application URL so I should somehow stop redirection completely after creating a bucket.

**Comment by whummer** [comment]
Thanks for reporting @BentCoder . Hope you've been able to get it working in the meantime. As mentioned by @bastuijnman , the recommended way is to configure your client to use path style endpoint addressing. Please re-open this issue if the problem persists. Thanks
