### ISSUE TITLE
enhancement request: Add Support for passing 'selectionSetList' in appsync graphQL request

### ISSUE THREAD

**Issue by mileemh** [localstack/localstack#8362]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Enhancement description

Current Behavior

We have localstack 2.0.2  set up with Clouldformation stack , AppSync and Lambdas. When we query the GraphQL API the Lambda event does not contain **selectionSetList** and **variables**. Find below the snippet of log received in lambda docker.

`{'stash': {}, 'request': '{}', 'prev': None, 'arguments': {}, 'identity': {'sub': 'admin'}, 'info': {'fieldName': 'getHealth', 'parentTypeName': 'Query', 'variables': {}, 'selectionSetList': [], 'selectionSetGraphQL': 'query MyQuery {\n    getHealth{\n        identity\n        region\n        metaVersion\n    }\n}'}}`

Can you please add support for passing variables, selectionSetList and other header data in AppSync GraphQL endpoints that have lambda resolvers.

We have added blow line in request mapping resolver file to explicitly include selectionSetList 
`"selectionSetList" : $uti.toJson($context.info.selectionSetList) `

Using below referenced file for starting localstack 
https://github.com/localstack/localstack/blob/master/docker-compose-pro.yml

On Side note I have already done` docker pull localstack/localstack:latest`

**Comment by thrau** [comment]
hey @mileemh, is there anything more you can share with us to help us reproduce the issue? it would be helpful to get the relevant parts from the cloudformation stack. thanks!

**Comment by daniil0kalbin** [comment]
Hello @thrau , we are having similar problem with Localstack, I added minimal description to Localstack Slack channel(#help), you can find steps how to reproduce it there: https://localstack-community.slack.com/archives/CMAFN2KSP/p1686137090144509

I would not like to share reproducible code here because of privacy concerns of a client, but if I can share it directly with Localstack team, it would be nice. 

Thanks for your help in advance and have a nice day.

**Comment by sbochoa** [comment]
I'm having the same issue, the selectionSetList is empty when received by the lambda function. Is there any workaround/config to solve this issue?

**Comment by simonrw** [comment]
Hi, this feature has been resolved. Please pull the latest `localstack/localstack-pro:latest` docker image. If you continue to see issues please raise another GitHub issue with us.
