### ISSUE TITLE
API Gateway Model creation results in error (but created) - terraform

### ISSUE THREAD

**Issue by elbazon** [localstack/localstack#8368]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When you create an API Gateway rest api model using terraform, it reaches the following error:
"Error: creating API Gateway Model (Error): ConflictException: Model name already exists for this REST API"

The resource didn't exist before creating it.
While the following error is provided, the resource is indeed being created - but exits with the error.

### Expected Behavior

Creating this resource will work properly with no errors...

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

docker compose up -d

**File Content:**
  # -------------- LocalStack --------------
  localstack:
    image: localstack/localstack-pro:2.0.2
    container_name: localstack
    ports:
      - "4566:4566"
      - "4571:4571"
      - "4600:4600"
    environment:
      - KINESIS_PROVIDER=kinesalite
      - DEFAULT_REGION=us-east-1
      - DEBUG=1
      - ENFORCE_IAM=1
      - LS_LOG=trace
      - PROVIDER_OVERRIDE_LAMBDA=asf
      - LAMBDA_REMOVE_CONTAINERS=true
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LOCALSTACK_API_KEY=$LOCALSTACK_API_KEY
      - LAMBDA_EXECUTOR=docker
      - LAMBDA_REMOTE_DOCKER=false
      - LAMBDA_DOCKER_NETWORK=local-dev_default
      - DNS_ADDRESS=0
      - DISABLE_PREFLIGHT_PROCESSING=1
      - DYNAMODB_IN_MEMORY=1
    volumes:
      # Docker Lambda executor requirements
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - /var/run/docker.sock:/var/run/docker.sock

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

Using Terraform, please see the attached rest-api configurations (due to upload limitations, please change the files type to .tf). 
[rest-api.txt](https://github.com/localstack/localstack/files/11564213/rest-api.txt)

[rest-api-model.txt](https://github.com/localstack/localstack/files/11564215/rest-api-model.txt)

[rest-api-iam.txt](https://github.com/localstack/localstack/files/11564212/rest-api-iam.txt)

### Environment

```markdown
- OS: Mac OS
- LocalStack: 2.0.2 - pro
```

**Comment by bentsku** [comment]
After doing more checks, it seems when creating a RestAPI with an OpenAPI file, the default models are not created. This will be fixed with #8371

**Comment by bentsku** [comment]
Hi @elbazon, could pull our latest image via `docker pull localstack/localstack-pro:latest` and give it a try? It should be resolved. Thanks!

**Comment by bentsku** [comment]
Hello, the issue should be fixed now, but feel free to reopen if you still have the issue. Thanks!
