### ISSUE TITLE
bug: Invoked AWS lambda - receiving input null

### ISSUE THREAD

**Issue by JackieDanes1990** [localstack/localstack#8383]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I invoke my lambda I always get input null

### Expected Behavior

Function receives the passed in behaviour

### How are you starting LocalStack?

Custom (please describe below)

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    testcontainer with lambda capability (from Java)

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

awslocal lambda create-function --function-name reverse --runtime java17 --handler org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleReques --role arn:aws:iam::123456789101:role/revers --zip-file fileb://lambda.jar

--wait for the lambda to be ready

awslocal lambda create-function-url-config --function-name lambda-name --auth-type NONE

in the container I then do:

curl receivedFunctionUrl -X POST -H 'Content-type: application/json' -d 'trap'

The above works fine when I run my lambda on AWS itself, but using the localstack testcontainer my function receives null.

### Environment

```markdown
- OS:
- LocalStack: latest
```

### Anything else?

The function itself just uses spring cloud 2022.0.3, spring cloud function context, spring cloud function adapter aws.

Function itself:

```
@Bean
	public Function<String,String> reverse() {
		return (s) -> "Reversed: " +  new StringBuilder(s).reverse();
	}
```

**Comment by JackieDanes1990** [comment]
On slack Florian Woelki also mentioned running into the issue while using golang.

**Comment by dfangl** [comment]
Hi @JackieDanes1990 !

Is it possible for you to provide a minimum viable example for this? This would make reproduction immensely easier for us.

**Comment by JackieDanes1990** [comment]
@dfangl the function itself was literally what was in the initial post, with the command being send to the localstack container.

**Comment by dfangl** [comment]
@JackieDanes1990 Yes, you are right. I was just wondering if you might already have a complete project lying around that we only need to run. If not, that's fine as well.

**Comment by dfangl** [comment]
@JackieDanes1990 

I used this example: https://github.com/spring-cloud/spring-cloud-function/tree/main/spring-cloud-function-samples/function-sample-aws to reproduce your issue.

Using java17 to build, with the following `FunctionConfiguration.java`:

```java
package example;

import java.util.function.Function;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

@SpringBootApplication
public class FunctionConfiguration {

	/*
	 * You need this main method (empty) or explicit <start-class>example.FunctionConfiguration</start-class>
	 * in the POM to ensure boot plug-in makes the correct entry
	 */
	public static void main(String[] args) {
	    SpringApplication.run(FunctionConfiguration.class, args);
	}

	@Bean
	public Function<String, String> uppercase() {
		return (s) -> "Reversed: " + new StringBuilder(s).reverse();
	}
}
```

This is the script used to deploy and test:
```bash
#!/bin/bash
mvn clean package
awslocal lambda create-function --function-name reverse --runtime java17 --handler org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest --role arn:aws:iam::000000000000:role/reverse --zip-file fileb://./target/function-sample-aws-0.0.1-SNAPSHOT-aws.jar
until [[ $(awslocal lambda get-function --function-name reverse | jq -r ".Configuration.State") = "Active" ]];
do
	echo "Waiting for lambda to be ready..."
	sleep 1
done
function_url=$(awslocal lambda create-function-url-config --function-name reverse --auth-type NONE | jq -r .FunctionUrl)
echo $function_url
curl -X POST -H "Content-type: application/json" $function_url -d "trap"
```

And get the result:
```
"Reversed: part"
```

So, I could not reproduce your issue with the latest version of LocalStack. Please double check if you use the latest version, and also try using this command (aws cli v2, otherwise please remove the `--cli-binary-format raw-in-base64-out` part):
```
awslocal lambda invoke --function-name reverse --payload '{"test": "test"}' --cli-binary-format raw-in-base64-out out && cat out
```

And provide the logs and outputs of it.
