### ISSUE TITLE
Unable to change ContentBasedDeduplication attribute on existing queue

### ISSUE THREAD

**Issue by pcalouche** [localstack/localstack#8397]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If I create a queue and try to change its `ContentDeduplication` attribute, I see this error:

` An error occurred (InvalidAttributeName) when calling the SetQueueAttributes operation: Unknown Attribute ContentBasedDeduplication.`

### Expected Behavior

I should be able to set `ContentBasedDeduplication` from `true` to `false` on an existing queue.  It appears to work on AWS.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```
aws sqs create-queue --queue-name test1.fifo --endpoint-url http://localhost:4566/ --attributes FifoQueue=true,ContentBasedDeduplication=true
{
    "QueueUrl": "http://localhost:4566/000000000000/test1.fifo"
}


aws sqs get-queue-attributes --endpoint-url http://localhost:4566/ --queue-url http://localhost:4566/000000000000/test1.fifo --attribute-names '["ContentBasedDeduplication"]'
{
    "Attributes": {
        "ContentBasedDeduplication": "true"
    }
}

aws sqs set-queue-attributes --endpoint-url http://localhost:4566/ --queue-url http://localhost:4566/000000000000/test1.fifo --attributes ContentBasedDeduplication=false

An error occurred (InvalidAttributeName) when calling the SetQueueAttributes operation: Unknown Attribute ContentBasedDeduplication.
```

### Environment

```markdown
- OS: MacOs Ventura 13.3.1 (a) 
- LocalStack: 2.1.0
```

**Comment by thrau** [comment]
thanks for reporting Philip @pcalouche. was easy to reproduce thanks to the instructions, fix is in the pipeline.

**Comment by Romasato** [comment]
Hi there,

I am still seeing the same `An error occurred (InvalidAttributeName) when calling the CreateQueue operation: Unknown Attribute ContentBasedDeduplication.` error in `localstack/localstack:latest` docker image when trying to create an SQS queue with `ContentBasedDeduplication=true`.

Has it been fixed or is there some other reason it does not accept this attribute?
