### ISSUE TITLE
Support for SES notifications through SNS

### ISSUE THREAD

**Issue by ambrusadrianz** [localstack/localstack#84]
It would be great if LocalStack supported SES notifications

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-311) by [Unito](https://www.unito.io/learn-more)

**Comment by ellisonleao** [comment]
is this already implemented?

**Comment by adriangalera** [comment]
+1

**Comment by adriangalera** [comment]
Implemented in https://github.com/spulec/moto/pull/2016/
I'll let you know when it's merged so you can update the moto version of localstack

**Comment by whummer** [comment]
Thanks for the update @adriangalera . Unfortunately, this implementation in `moto` will *not* ensure that things are also going to work in LocalStack. Whereas moto follows an in-memory approach to wire the different services together, LocalStack generally uses API calls to achieve that, making the services more decoupled from each other (this is specifically done so we can replace each service with a different backend implementation).

The trouble is with this method here:
https://github.com/spulec/moto/pull/2016/files#diff-d206c0506c227190d0c93f966ef78f82R155
Setting the notification topic configuration on the instance variable `self.sns_topics` and then calling `publish` on the SNS backend is not going to update the corresponding SNS backend in LocalStack.

**Comment by michaeljneelysd** [comment]
Would love to see this implemented! @whummer - what exactly is needed to update the corresponding SNS backend in LocalStack?

**Comment by conmanet** [comment]
+1

Any updates?

**Comment by whummer** [comment]
Added in https://github.com/localstack/localstack/pull/3571
