### ISSUE TITLE
Running on Widows in Docker

### ISSUE THREAD

**Issue by chikkam** [localstack/localstack#840]
I am running in docker on windows using

docker run localstack/localstack 

This is mapping docker ports 4567 thru 4583 and 8080 to the same ports on the host. However these are not accessible from a browser running on the host.

However when run it with the following command

docker run -P localstack/localstack

The mapping between dockers 4567 thru 4583 and 8080 is randomly assigned to host ports. These are accessible from a browser running on the host.
The problem with the later approach is randomness. Can you suggest if there is a way to avoid this random assignment and still have ports accessible from host.
Regards
Ravi Chikkam

**Comment by mattmeye** [comment]
I use `docker run -d -p 4575-4583:4575-4583 -p 8080:8080 --name some-localstack localstack/localstack:latest` but have also trouble with some services

**Comment by whummer** [comment]
Installation using `pip` should work now under Windows (see also the recent changes in #1631). Closing this issue - please re-open if the problem persists. Thanks
