### ISSUE TITLE
Feat: CloudFormation AWS::ElasticBeanstalk support

### ISSUE THREAD

**Issue by janaka** [localstack/localstack#8409]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Enhancement description

Please add AWS::ElasticBeanstalk support to CloudFormation. 

In my case using Beanstalk via AWS CDK. CDK currently only has L1 support.

**Comment by HarshCasper** [comment]
Hi — Thanks for creating the issue! We have shipped an implementation that should unblock you. Please pull the `localstack/localstack-pro:latest` Docker image, and let us know your feedback! 🙏
