### ISSUE TITLE
bug: kms generate-data-key-pair-without-plaintext command not working

### ISSUE THREAD

**Issue by calebvarberg** [localstack/localstack#8421]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm running localstack version `1.18.3` with the local KMS service. 

If you create a symmetric key 
`awslocal kms create-key --key-spec="RSA_2048" --key-usage="ENCRYPT_DECRYPT"`

Then take the keyId from the result and attempt to generate a data key pair without plaintext 
`awslocal kms generate-data-key-pair-without-plaintext --key-id="{keyId}" --key-pair-spec="RSA_2048"`

I am always getting the same error
`An error occurred (501) when calling the GenerateDataKeyPairWithoutPlaintext operation: Passed X-Amz-Target is not implemented`

### Expected Behavior

Based on the localstack docs it appears that generate-data-key-pair-without-plaintext should be supported and similar commands like `generate-data-key-without-plaintext` seem to work correctly. 

These same commands also work when hitting kms directly. 

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

`awslocal kms create-key --key-spec="RSA_2048" --key-usage="ENCRYPT_DECRYPT"`
`awslocal kms generate-data-key-pair-without-plaintext --key-id="{keyId}" --key-pair-spec="RSA_2048"`

### Environment

```markdown
- OS: MacOS M1
- LocalStack: 1.18.3
```

### Anything else?

-

**Comment by sannya-singal** [comment]
Hey @calebvarberg 👋,

With our `latest` image you are now able to `generate-data-key-pair-without-plaintext`. Please let us know if everything works for you as expected 🙏

Thank you!
