### ISSUE TITLE
bug : Getting "Unable to locate credentials" error when trying to create s3 bucket running localstack in docker on Ubuntu

### ISSUE THREAD

**Issue by ashokjanardhana** [localstack/localstack#8424]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am trying out basic AWS s3 bucket creation/deletion/listing using localstack. I am able to start docker successfully, but when I try to create s3 bucket, I am getting error as,
"make_bucket failed: s3://mytestbucket Unable to locate credentials".

 **localstack start logs:**
`apexoe@ptab-vm1:~/localstack$ docker-compose -f docker-compose.yml up -d --build

 Network localstack_default  Created                                                                                                                  0.1s
 Container cirrus            Started                                                                                                                  0.8s

apexoe@ptab-vm1:~/localstack$
`

**Error I am seeing when I try to create s3**
`apexoe@ptab-vm1:~/localstack$ aws --endpoint-url=http://localhost:4566 s3 mb s3://mytestbucket

make_bucket failed: s3://mytestbucket Unable to locate credentials

apexoe@ptab-vm1:~/localstack$`

### Expected Behavior

Since localstack application is running successfully, s3 creation should be successful.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack 

    docker-compose -f docker-compose.yml up -d --build

#### Client commands (s3 creation command from aws)

    aws --endpoint-url=http://localhost:4566 s3 mb s3://mytestbucket

#### Docker-compose file details:
`version: "3.8"

services:
  localstack:
    container_name: "test"
    image: localstack/localstack
    ports:
      - "4566:4566"            # LocalStack Gateway
      - "8082:8082"
    environment:
      - SERVICES=s3:4566
      - HOSTNAME_EXTERNAL=localhost
      - DEBUG=1
      - PORT_WEB_UI=8082
      - AWS_DEFAULT_REGION=us-west-1
      - AWS_SECERET_ACCESS_KEY=KKK
      - AWS_ACCESS_KEY_ID=AAAAA
    volumes:
      - ./localstack/:/docker-entrypoint-initaws.d/
`

### Environment

```markdown
- OS:Ubuntu 20.04.3 LTS
- LocalStack:latest
```

### Anything else?

None

**Comment by bentsku** [comment]
@ashokjanardhana thanks for the quick feedback! I'll close the issue as it seems resolved. Don't hesitate if you any issues.

**Comment by karthik101** [comment]
> Hello @ashokjanardhana and thanks for your report. The error you're seeing is actually raised by the AWS CLI, and not LocalStack. You will need to configure a (default) profile to use with LocalStack for the CLI by running `aws configure` and when prompted for the `AWS Access Key ID`, enter `test`, then `test` again and then your default region, `us-east-1` could do.
> 
> ```shell
> $ aws configure
> AWS Access Key ID [****************test]: test
> AWS Secret Access Key [****************test]: test
> Default region name [us-east-1]: us-east-1
> Default output format [None]: 
> ```
> 
> You can read about the AWS CLI and how to configure and use it with LocalStack and our `awslocal` wrapper in our documentation here: https://docs.localstack.cloud/user-guide/integrations/aws-cli/

Why wasn't this included as a note in the quick start docs ?
