### ISSUE TITLE
bug: Cannot list external agents and Reset initiated

### ISSUE THREAD

**Issue by aleRizzolo** [localstack/localstack#8432]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

Hello,
I was trying to run this code https://github.com/isislab-unisa/WeatherStation/tree/main
using AWS Lambda. Everytime I try to run the function, I got the following message on Docker container: 

```
2023-06-02 18:09:58 time="2023-06-02T16:09:58Z" level=warning msg="Cannot list external agents" func-go.amzn.com/lambda/agents.ListExternalAgentPaths fil mbda-runtime-init/lambda-runtime-init/lambda/agents/agent.go:71" error="open /opt/extensions: no such file or directory"

2023-06-02 18:10:02 time="2023-06-02T16:10:02Z" level=warning msg="Reset initiated: Timeout" func-go.amzn.com/lambda/rapid.handleReset file="/home/runner/work/lambda-runtime-in
it/lambda-runtime-init/lambda/rapid/start.go:589"
```

and checking the out file I got `{"errorMessage":"2023-06-02T16:10:02Z 5306f0c4-deab-4097-9214-ed92a6994374 Task timed out after 3.00 seconds"}`

### Expected Behavior

The function should execute without problem

### How are you starting LocalStack?

With a `docker run` command

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

docker run -d -v /var/run/docker.sock:/var/run/docker.sock --rm -p 4566:4566 --name aws localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

   All the ocmmands are available in the repository linked above

### Environment

```markdown
- OS: Windows 10 (WSL2) but I've also tried Ubuntu 23.04
- LocalStack: latest Docker image
```

**Comment by aleRizzolo** [comment]
@thrau I solved this issue by using LocalStack 1.4 so I don't need to solve this problem anymore. May I close it?

**Comment by thrau** [comment]
Hey @aleRizzolo , thanks for letting us know! We can keep the issue open so that you get a notice when you can upgrade :+1:

**Comment by dfangl** [comment]
Hello @aleRizzolo !

I just tested the linked project, and it works against the new lambda provider.

These are the changes necessary for it:

1. The endpoints set in the handler file are hardcoded to localhost. As the new provider executes all lambdas in separate containers, this has to be adapted. With 1.4, it also only would work in the local provider, as the lambda will be executed within the container, and `localhost` is therefore correct.
Here are the advised changes:
```
diff --git a/settings/avgFunc.py b/settings/avgFunc.py
index 6c8e393..24d5f6e 100644
--- a/settings/avgFunc.py
+++ b/settings/avgFunc.py
@@ -1,10 +1,12 @@
 import boto3
 import datetime
 import json
+import os

 def lambda_handler(event, context):
-       sqs = boto3.resource('sqs', endpoint_url='http://localhost:4566')
-       dynamodb = boto3.resource('dynamodb', endpoint_url="http://localhost:4566")
+       endpoint_url = f'http://{os.environ.get("LOCALSTACK_HOSTNAME")}:{os.environ.get("EDGE_PORT")}'
+       sqs = boto3.resource('sqs', endpoint_url=endpoint_url)
+       dynamodb = boto3.resource('dynamodb', endpoint_url=endpoint_url)

        table = dynamodb.Table('Campania')

@@ -40,4 +42,4 @@ def lambda_handler(event, context):
                                }
                                table.put_item(Item=item)
                        else:
-                               break
\ No newline at end of file
+                               break
```

2. The timeout has to be increased. Our old provider would not enforce timeouts, but the new one does. A run of this function takes around 60s, so the timeout has to be increased significantly from the default 3s.
I used this command to create the lambda function:
```
awslocal lambda create-function --function-name avgFunc --zip-file fileb://avgFunc.zip --handler settings/avgFunc.lambda_handler --runtime python3.9 --role arn:aws:iam::000000000000:role/lambdarole --timeout 600
```

The whole script I used for reproduction:
```
#!/bin/bash

awslocal sqs create-queue --queue-name Salerno
awslocal sqs create-queue --queue-name Caserta
awslocal sqs create-queue --queue-name Napoli
awslocal sqs create-queue --queue-name Avellino
awslocal sqs create-queue --queue-name Benevento
awslocal sqs create-queue --queue-name Errors

awslocal sqs list-queues

python3 settings/createTable.py

awslocal dynamodb list-tables

python3 settings/loadData.py

awslocal dynamodb scan --table-name Campania

awslocal iam create-role --role-name lambdarole --assume-role-policy-document file://settings/role_policy.json --query 'Role.Arn'

awslocal iam put-role-policy --role-name lambdarole --policy-name lambdapolicy --policy-document file://settings/policy.json

zip avgFunc.zip settings/avgFunc.py

awslocal lambda create-function --function-name avgFunc --zip-file fileb://avgFunc.zip --handler settings/avgFunc.lambda_handler --runtime python3.9 --role arn:aws:iam::000000000000:role/lambdarole --timeout 600

python3 IoTDevices.py

until [[ $(awslocal lambda get-function --function-name avgFunc | jq -r ".Configuration.State") = "Active" ]];
do
	echo "Waiting for lambda to be ready..."
	sleep 1
done
awslocal lambda invoke --function-name avgFunc --payload fileb://settings/city.json out && cat out
```

Closing this issue, as the provider behaves as expected.

**Comment by aleRizzolo** [comment]
Hello @dfangl.

Yeah I knew about the <code>localhost</code> issue, but I had no clue about the timeout. 

Thanks for your assistance
