### ISSUE TITLE
bug: Issue with global-write-forwarding and two cluster writers

### ISSUE THREAD

**Issue by Extrabeefy** [localstack/localstack#8463]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We have built a Aurora Global Cluster and have created two db clusters one in east-1 and one in west-2. The west-2 cluster has the global-write-forwarding and each cluster has three  db instances. As I was looking at the clusters I noticed that both east-1 and west-2 have a writer. It should be that only primary has the writer and secondary has 3 readers. Just wondering if there is anyway to resolve this?

This is for AuroraPostgres, and we have LocalStack Pro

Wasn't sure if this was a bug or just something I was doing wrong on setup

### Expected Behavior

Should only have writer in primary region and secondary cluster with global-write-forwarding has 3 readers

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

create-global-cluster with AuroraPostgres Engine
create-db-cluster with AuroraPostgres attached to Global DB Cluster in East-1 and West-2 with West-2 having global-write-forwarding flag
Run create-db-instance x3 for both East-1 and West-2. Then attach to db cluster in East-1 and West-2
describe-db-cluster and check IsClusterWriter for both regions
 

### Environment

```markdown
- OS: MacOS
- LocalStack: Pro latest
```

### Anything else?

https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/aurora-global-database-write-forwarding.html

**Comment by steffyP** [comment]
Hi @Extrabeefy,

thanks for bringing this to our attention 🙏 
We already had a private conversation on that topic, just summarizing what we already discussed:
* the `create-global-cluster` is not yet implemented leading to strange behavior you are seeing as outlined. 
* Using the "global-write-forwarding flag" does not relate to this at all. 
* You can expect initial support for the global-cluster very soon (with some limitations), that will correctly return the the `IsGlobalWriter` flags, and also support the `failover-global-cluster` operation. 

However, there is still another question that arised up when we were running your scenario on AWS: it turns out, that `aurora-postgresql` does not support the "global write forwarding" flag. 

Here is what we tested:
```
$ aws rds create-global-cluster --global-cluster-identifier my-global-clust
er --engine aurora-postgresql --engine-version 13.7
{
    "GlobalCluster": {
        "GlobalClusterIdentifier": "my-global-cluster",
        "GlobalClusterResourceId": "cluster-d93e2d9e6b8c9278",
        "GlobalClusterArn": "arn:aws:rds::837471453475:global-cluster:my-global-cluster",
        "Status": "available",
        "Engine": "aurora-postgresql",
        "EngineVersion": "13.7",
        "StorageEncrypted": false,
        "DeletionProtection": false,
        "GlobalClusterMembers": []
    }
}


$ aws rds create-db-cluster --db-cluster-identifier my-cluster --engine aurora-postgresql --engine-version 13.7 --database-name hello --enable-global-write-forwarding --global-cluster-identifier my-global-cluster --master-username test --master-user-password Test123!

An error occurred (InvalidParameterValue) when calling the CreateDBCluster operation: Global write forwarding is not supported for engine aurora-postgresql

```

It would be great if we could get some clarification on this, e.g. is there another way you are creating the clusters on AWS, or are you using `aurora-mysql`?

**Comment by Extrabeefy** [comment]
Hey sorry for the late response was on vacation end of last week. I think you are correct this doesn't appear to be supported by Postgres, we were testing a few Aurora databases and I think we got confused on which had this global-write-forwarding flag.

As long as the global-cluster returns the correct isWriter flag based on Primary vs Secondary clusters then I believe that's all we need. Thank you all so much for such a quick response to this!

**Comment by steffyP** [comment]
Hi @Extrabeefy,

you can pull `localstack/localstack-pro:latest` where we have added support for global-clusters. There are some limitations, e.g. when removing a cluster from global-cluster it will not be a standalone-cluster. 

Please let us know if your use case is now working, and let us know if you encounter any issues 🙏

**Comment by Extrabeefy** [comment]
When I tested adding the DBInstances manually to the secondary cluster it wiped east ones it was showing me and just ended up creating another 1x Writer and 2x Readers on the secondary

**Comment by Extrabeefy** [comment]
Yep it's no longer about the Global Writer Forwarding and it is about writers and readers.

**Comment by steffyP** [comment]
Hi @Extrabeefy, 

thanks for getting back to us! 

I am afraid I am having troubles understanding the issue, I hope you can provide some more details for reproduction. Ideally you could give a step-by-step sample on what you are doing, and what output you are expecting? 
That would help a bunch, thank you 🙏 

In particular:

1. 
> when I create a secondary cluster in a different region attached to the global cluster I am seeing that the secondary cluster is not having 3 Readers created. 

Do you expect the three readers to be created automatically in the secondary region? 


2. 
> I would expect to see 6 total DBInstances listed in this situation however I am only seeing the 1x Writer and 2x Readers from east.

Where exactly do you expect to see the DBInstances listed then? 
From the `describe-global-clusters` AFAIK it should only show the db-cluster members, along with a list of the `Readers`, e.g. the secondary clusters that read from the primary.

Here is a sample with a global cluster and two secondary clusters (tested on AWS). The primary has two instances, the second one has one instance, and the third one is headless - but this information is not showing up here:
```
"GlobalClusters": [
          {
            "DeletionProtection": false,
            "Engine": "aurora-postgresql",
            "EngineVersion": "13.7",
            "GlobalClusterArn": "arn:aws:rds::111111111111:global-cluster:<global-cluster-identifier:1>",
            "GlobalClusterIdentifier": "<global-cluster-identifier:1>",
            "GlobalClusterMembers": [
              {
                "DBClusterArn": "arn:aws:rds:<region>:111111111111:cluster:<db-cluster-id:1>",
                "IsWriter": true,
                "Readers": [
                  "arn:aws:rds:eu-west-1:111111111111:cluster:<db-cluster-id:2>",
                  "arn:aws:rds:eu-north-1:111111111111:cluster:<db-cluster-id:3>"
                ]
              },
              {
                "DBClusterArn": "arn:aws:rds:eu-west-1:111111111111:cluster:<db-cluster-id:2>",
                "GlobalWriteForwardingStatus": "disabled",
                "IsWriter": false,
                "Readers": []
              },
              {
                "DBClusterArn": "arn:aws:rds:eu-north-1:111111111111:cluster:<db-cluster-id:3>",
                "GlobalWriteForwardingStatus": "disabled",
                "IsWriter": false,
                "Readers": []
              }
            ],
            "GlobalClusterResourceId": "<global-cluster-resource-id:1>",
            "Status": "available",
            "StorageEncrypted": false
          }
        ]
```

For the default `describe-clusters` you should see the instances that have been added manually (each cluster is in a different region, so the `--region` attribute needs to be set as well). 

Is there another api that I am not aware of, where you would see all instances that belong to that global-cluster?


3. 
> When I tested adding the DBInstances manually to the secondary cluster it stopped showing the east ones and just ended up creating 1x Writer and 2x Readers on the secondary

Could you please describe how you are creating these, and what exactly you mean by "it stopped showing the east ones"? 🙏

**Comment by Extrabeefy** [comment]
For question one I would assume that 3 readers where automatically built. The reason being that when you do a Global Failover on the cluster it would promote one of the readers in the secondary cluster to a Writer. How you all currently has it there would be nothing to promote.. as only the primary has any DBInstances

For question two this is great except for the fact that I should also see the DBInstances for the Secondary cluster that were created also.

For Question three I ran aws local create-db-instance attached to the secondary cluster I have in the us-west-2 region. When I am looking at DB Cluster information for using describe-db-clusters I am only seeing the ones for the secondary cluster that I created, not the ones that also exist in the primary.

**Comment by Extrabeefy** [comment]
Hey @steffyP 
Talked with Chad today and after testing it with the cli everything looks good(was checking on yalls localstack console). Thank yall so much :).

**Comment by cabeaulac** [comment]
Hey @Extrabeefy . Thanks so much for checking that so quickly. I will talk to the platform team now about how it's displaying. So, can we close this ticket and open another one for anything else that comes up?

**Comment by Extrabeefy** [comment]
Yep we can close this!

**Comment by Extrabeefy** [comment]
Working as should
