### ISSUE TITLE
Enhancement request: Support AWS SQS's newly announced "SQS Dead-Letter Queue Redrive via AWS SDK or CLI"

### ISSUE THREAD

**Issue by christopher-nash** [localstack/localstack#8471]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Enhancement description

On June 8, 2023, Amazon just announced `support for dead-letter queue redrive via AWS SDK or CLI`

The SDK introduces three new 'tasks' that can be performed against an SQS dead letter queue:
* `StartMessageMoveTask`
* `CancelMessageMoveTask`
* `ListMessageMoveTasks`

LocalStack's SQS implementation should be updated to support these new DLQ redrive operations.

-------------------------

Not surprisingly when I attempting to do this the day after announcement, LocalStack doesn't yet support these operations. Using the latest LocalStack docker container tag of `2.1.0` and the latest Java AWS SDK version `2.20.82`, I attempted to perform one of these new `StartMessageMoveTask` against LocalStack using the following:
```java
StartMessageMoveTaskResponse moveTaskResponse =
      sqs.startMessageMoveTask(builder -> builder.sourceArn(dlqArn).destinationArn(qArn));
```
The container produced the following error message:
```
2023-06-09T17:06:50.098 ERROR --- [   asgi_gw_0] l.aws.handlers.logging     : exception during call chain: Operation detection failed.Operation StartMessageMoveTask could not be found for service ServiceModel(sqs).
2023-06-09T17:06:50.099347340Z 2023-06-09T17:06:50.099  INFO --- [   asgi_gw_0] localstack.request.http    : POST / => 500
```

### Anything else?

Relevant AWS announcements and API specs:
* https://aws.amazon.com/blogs/aws/a-new-set-of-apis-for-amazon-sqs-dead-letter-queue-redrive/
* https://aws.amazon.com/about-aws/whats-new/2023/06/amazon-sqs-dead-letter-queue-redrive-aws-sdk-cli/
* https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-configure-dead-letter-queue-redrive.html

**Comment by thrau** [comment]
Thanks for reporting @christopher-nash, that's an interesting development and something we can look into
