### ISSUE TITLE
bug: Secrets not passed to ECS Fargate task as environment variable

### ISSUE THREAD

**Issue by chris-stetter** [localstack/localstack#8492]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When creating an ECS Fargate task definition the command `awslocal ecs describe-task-definition` properly shows that a secret is defined to be fetched from ssm:

```json
"secrets": [
                    {
                        "name": "DB_PASSWORD",
                        "valueFrom": "arn:aws:ssm:eu-central-1:000000000000:parameter/db-master-password-da219cd"
                    }
                ],
```

However, when running a fargate task this secrets does not get passed as an environment variable to the docker container.

### Expected Behavior

I would expect to see this environment variable in the docker container localstack is starting.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker-compose up localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    `awslocal ecs describe-task-definition`

### Environment

```markdown
- OS: WSL2
- LocalStack:latest
```

**Comment by pinzon** [comment]
The feature has been just merge into the codebase. Make sure to pull the latest image of LocalStack. Thank you for reporting the issue.
