### ISSUE TITLE
bug: Running ECS task does not return `failures`

### ISSUE THREAD

**Issue by chris-stetter** [localstack/localstack#8493]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When using the AWS CLI [run task](https://docs.aws.amazon.com/cli/latest/reference/ecs/run-task.html) command against localstack, the response is supposed to [output](https://docs.aws.amazon.com/cli/latest/reference/ecs/run-task.html#output) a list of `failures` but only returns a list of `tasks`.

### Expected Behavior

A list of failures should be returned.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker-compose up localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal ecs run-task

### Environment

```markdown
- OS: WSL2/Ubuntu
- LocalStack: latest
```

### Anything else?

I am not sure if LocalStack uses moto, but if so this seems to implement the [failures output](https://github.com/getmoto/moto/blob/master/tests/test_ecs/test_ecs_boto3.py#L168). Note that is a signifcant bug as other packages like [Apache Airflow expect this response](https://github.com/apache/airflow/blob/v2-5-stable/airflow/providers/amazon/aws/operators/ecs.py#L483).

**Comment by chris-stetter** [comment]
This also applies to the `exitCode` property when running [aws ecs describe-tasks](https://docs.aws.amazon.com/cli/latest/reference/ecs/describe-tasks.html). It looks light there is quite a lot of inparity.

**Comment by francesco-esp** [comment]
Hello, this is still an issue on version `4.5.0`. Do want me to create a separate issue or can this be reopened?
