### ISSUE TITLE
[Feature Request] Lambda: Add support for SQS as event source 

### ISSUE THREAD

**Issue by nav-agarwal** [localstack/localstack#850]
Recently AWS came up with SQS as event source for lambda. Article [here](https://aws.amazon.com/blogs/aws/aws-lambda-adds-amazon-simple-queue-service-to-supported-event-sources/).

Would love to have this feature in localstack.

Thanks

**Comment by dknepprath** [comment]
Were all of these issues address in https://github.com/localstack/localstack/pull/904

**Comment by makaveli0129** [comment]
@dknepprath does this work with dotnet applications? I keep getting just emptiness even on the simplest of functions the code never reads anything from the SQS Queue but the queue shows messages.....Not sure if having the dotnet code deployed with the docker option breaks this or not?

**Comment by dknepprath** [comment]
I'm not sure why this would not work on dotnet application. I left my comment while doing some grooming of open issues. 

I recommend you ask a question in a new issues with more details on how you are using localstack in your environment with some code snippets.

**Comment by gregevari** [comment]
Despite #904, this one still doesn't seem to be working.

**Comment by sumit5113** [comment]
It do not work despite the #904 above fix.

**Comment by Psynbiotik** [comment]
Probably needs a similar change as issue 'Add S3Event Parser for Lambda #930 ':
https://github.com/localstack/localstack/pull/930/commits/95bd6a14d088f9ac65f5e6d0f2ec6c05e0d36354

This file currently has a TODO for sqs:
https://github.com/localstack/localstack/blob/master/localstack/ext/java/src/main/java/cloud/localstack/LambdaExecutor.java

@dknepprath are you still planning on working on this?

**Comment by dknepprath** [comment]
@Psynbiotik, I don't currently have any bandwidth planned.

**Comment by Psynbiotik** [comment]
I've done this myself, please see pull request: https://github.com/localstack/localstack/pull/1144

**Comment by whummer** [comment]
Should be fixed in #1144 - thanks!
