### ISSUE TITLE
bug: Logs not passed from ECS Fargate task to configure CloudWatch logs

### ISSUE THREAD

**Issue by chris-stetter** [localstack/localstack#8500]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I can confirm that my ECS task has a defined and existing log group using `awslocal ecs describe-task-definition`. Now when I watch the logs using `awslocal logs tail {LogGroupName} --follow --format json` and start the task using `awslocal ecs run-task`, no logs are being displayed.

### Expected Behavior

I would expect the docker container logs as started by localstack to be passed to the cloudwatch log group.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker-compose up localstack

### Environment

```markdown
- OS: WSL2/Ubuntu
- LocalStack: latest
```

**Comment by simonrw** [comment]
Hi @chris-stetter , do you have an example application or deploy process (e.g. CDK/Terraform/CloudFormation) that we can use to investigate further?

**Comment by chris-stetter** [comment]
No, sorry :(

**Comment by simonrw** [comment]
Reopening as this is still a problem

**Comment by simonrw** [comment]
A clarification: logs _are_ produced, but only when the task ends. We are aware of the problem and will close this issue when we have implemented incremental logging.
