### ISSUE TITLE
bug: Creating KMS alias with full ARN incorrectly created

### ISSUE THREAD

**Issue by nathanmcgarvey-modopayments** [localstack/localstack#8502]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When using the not-CLI (E.g. aws-sdk-go-v2) to create key aliases using the full ARN, the full ARN gets stored in localstack for the TargetKeyID, which renders the alias unusable (though that's a different discussion topic as the ARN is valid).

### Expected Behavior

Actual AWS truncates the TargetKeyID to be just the KeyID, not the full ARN, both by CLI and aws-sdk-go-v2. Localstack should do the same, or as a workaround, at least error-out and disallow the alias to be created with that specification.

### How are you starting LocalStack?

With a `docker run` command

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

Using the aws-sdk-go-v2, for example, but may work with others:
(replace the key ARN with a pre-created key)
```
	inputAlias := kms.CreateAliasInput{
		AliasName:   aws.String("alias/TestGoSDKDELETEME"),
		TargetKeyId: aws.String("arn:aws:kms:us-east-1:000000000000:key/00000000-0000-4bf3-0000-000000000000"),
	}
	_, err := client.CreateAlias(ctx, &inputAlias)
	if err != nil {
		fmt.Println(err.Error())
	}
```

Then try to operate on that alias on the command line

```aws --endpoint-url 'http://localhost:4576' kms describe-key --key-id 'alias/TestGoSDKDELETEME'

An error occurred (NotFoundException) when calling the DescribeKey operation: Invalid keyId arn:aws:kms:us-east-1:000000000000:key/00000000-0000-4bf3-0000-000000000000
```

What you'll see in the `list-aliases` output shows the issue (the TargetKeyID field):
```
awslocal kms list-aliases
{
    "Aliases": [
        {
            "AliasName": "alias/TestGoSDKDELETEME",
            "AliasArn": "arn:aws:kms:us-east-1:000000000000:alias/TestGoSDKDELETEME",
            "TargetKeyId": "arn:aws:kms:us-east-1:000000000000:key/00000000-0000-4bf3-0000-000000000000",
            "CreationDate": 1686759517.131898
        },
        {
            "AliasName": "alias/TestAWSCLIDELETEME",
            "AliasArn": "arn:aws:kms:us-east-1:000000000000:alias/TestAWSCLIDELETEME",
            "TargetKeyId": "00000000-0000-4bf3-0000-000000000000",
            "CreationDate": 1686760267.255624
        }
    ]
}
```

### Environment

```markdown
- OS: Mac OS X 13.4
- LocalStack: latest (as of ticket opening)
```

**Comment by sannya-singal** [comment]
Hey @nathanmcgarvey-modopayments! Thank you for reaching out to us.

I tried running the following commands in localstack: 

```
awslocal kms create-key
awslocal kms create-alias --alias-name alias/sample --target-key-id KEY_ARN
awslocal kms list-aliases
```

And I get `KeyId` in `TargetKeyId` field of the response. 

Furthermore, I also wrote the following golang script to reproduce the issue:

```
package main

import (
	"fmt"

	"github.com/aws/aws-sdk-go/aws"
	"github.com/aws/aws-sdk-go/aws/session"
	"github.com/aws/aws-sdk-go/service/kms"
)

func main() {
	// Initiate a new session
	sess, err := session.NewSession(&aws.Config{
		Region:   aws.String("us-west-2"),
		Endpoint: aws.String("http://localhost:4566/"),
	},
	)
	if err != nil {
		fmt.Println("Error creating session,", err)
		return
	}

	// Create a KMS service client
	svc := kms.New(sess)

	// Create the key
	keyOut, err := svc.CreateKey(&kms.CreateKeyInput{})
	if err != nil {
		fmt.Println("Error creating key,", err)
		return
	}
	fmt.Println("Created key", *keyOut.KeyMetadata.Arn)

	// Create alias
	aliasName := "alias/MyAlias"
	_, err = svc.CreateAlias(&kms.CreateAliasInput{
		AliasName:   aws.String(aliasName),
		TargetKeyId: aws.String(*keyOut.KeyMetadata.Arn),
	})
	if err != nil {
		fmt.Println("Error creating alias,", err)
		return
	}
	fmt.Println("Created alias", aliasName)
}
```

I get the `KeyId` in `TargetKeyId` field of the response here as well. 

I am unable to reproduce the issue, if you could please provide some more code snippets or a sequence of `awslocal` commands, that would be great to help us replicate your use case. Thanks!

**Comment by nathanmcgarvey-modopayments** [comment]
As of today, I can't reproduce this either. Closing.

Worth noting that the localstack container tags for have changed (even the versioned ones) since this ticket was opened. (E.g. a docker pull on my local system actually updated something, not just for latest, but for a :2.0.2 image, etc.)... I didn't think that was supposed to be a thing and I didn't bother spelunking to see what was the difference.
