### ISSUE TITLE
Should pass EncryptionContext down the call stack for KMS data key generation

### ISSUE THREAD

**Issue by nathanmcgarvey-modopayments** [localstack/localstack#8503]
This effectively makes data key generation broken:

https://github.com/localstack/localstack/blob/7e002033125f2cd8e758cb57166793809df5e34e/localstack/services/kms/provider.py#L594

There are also several other related TODOs in that file.

I'm not quite sure why those aren't implemented. It looks like the encrypt function/method and the API inputs both take encryption contexts and the data key generation just decides to drop it and not pass it down?

**Comment by sannya-singal** [comment]
Hey @nathanmcgarvey-modopayments, the issue should be now resolved, please pull the `latest` docker image and give it a try. Also, thanks for your feedback on #8517. The issue mentioned regarding the `GenerateDataKeyPair` handler was already in pipeline shall be rolled out today. Thank you!

**Comment by nathanmcgarvey-modopayments** [comment]
> Hey @nathanmcgarvey-modopayments, the issue should be now resolved, please pull the `latest` docker image and give it a try. Also, thanks for your feedback on #8517. The issue mentioned regarding the `GenerateDataKeyPair` handler was already in pipeline shall be rolled out today. Thank you!

Just tried the `:latest` tag with this change in it. Looks great and works both via CLI and the aws-go-sdk v2.
