### ISSUE TITLE
bug: KMS Decrypt fails when passing EncryptionContext

### ISSUE THREAD

**Issue by davecardwell** [localstack/localstack#8505]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Several KMS APIs take an optional encryption context argument. For example, when using `GenerateDataKey` if you pass an encryption context option you must pass the exact same context when later calling `Decrypt` on the key.

With LocalStack up to `v2.0.2` I don’t think the context was used correctly, but at least it would not fail when passing a context to decrypt. As of `v2.1.0` and `latest` the decrypt command throws an error.

The previous behavior of ignoring the context at least allowed legitimate requests to succeed.

### Expected Behavior

If `GenerateDataKey` was called with an encryption context, the `Decrypt` command should fail if you don’t pass the same context, and succeed if you do pass the same context. As of `v2.1.0` the opposite happens.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    # https://github.com/localstack/localstack/blob/master/docker-compose-pro.yml
    docker compose up

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```sh
awslocal kms create-key
# {
#     "KeyMetadata": {
#         "AWSAccountId": "000000000000",
#         "KeyId": "fc3a54e7-8d7b-467e-871b-17bd3ea565bb",
#         "Arn": "arn:aws:kms:us-east-1:000000000000:key/fc3a54e7-8d7b-467e-871b-17bd3ea565bb",
#         "CreationDate": 1686789632.373033,
#         "Enabled": true,
#         "Description": "",
#         "KeyUsage": "ENCRYPT_DECRYPT",
#         "KeyState": "Enabled",
#         "Origin": "AWS_KMS",
#         "KeyManager": "CUSTOMER",
#         "CustomerMasterKeySpec": "SYMMETRIC_DEFAULT",
#         "KeySpec": "SYMMETRIC_DEFAULT",
#         "EncryptionAlgorithms": [
#             "SYMMETRIC_DEFAULT"
#         ],
#         "MultiRegion": false
#     }
# }

# using the KeyId from above:
awslocal kms generate-data-key --key-id fc3a54e7-8d7b-467e-871b-17bd3ea565bb --encryption-context foo=bar
# {
#   "CiphertextBlob": "ZmMzYTU0ZTctOGQ3Yi00NjdlLTg3MWItMTdiZDNlYTU2NWJi51IjOsPnFmD2PKg5j+iXBwAAAAAAAAAAAAAAAAAAAADjN9UbJs0s4RxoNbIPE8gROLVcBH3zj2iqKmpXrFgw3Wt+0qqn0nGqpBfXbPlwD34=",
#   "Plaintext": "QfVwXhZBt9N2SySWT9WNPAM9/TB4HwyOJVCH5hGrgmc=",
#   "KeyId": "fc3a54e7-8d7b-467e-871b-17bd3ea565bb"
# }

# Using the CiphertextBlob from above:
echo -n 'ZmMzYTU0ZTctOGQ3Yi00NjdlLTg3MWItMTdiZDNlYTU2NWJi51IjOsPnFmD2PKg5j+iXBwAAAAAAAAAAAAAAAAAAAADjN9UbJs0s4RxoNbIPE8gROLVcBH3zj2iqKmpXrFgw3Wt+0qqn0nGqpBfXbPlwD34=' | base64 -d > /tmp/example.bin

# in v2.0.2 this succeeds:
awslocal kms decrypt --key-id fc3a54e7-8d7b-467e-871b-17bd3ea565bb --ciphertext-blob fileb:///tmp/example.bin --encryption-context foo=bar
# {
#   "KeyId": "arn:aws:kms:us-east-1:000000000000:key/fc3a54e7-8d7b-467e-871b-17bd3ea565bb",
#   "Plaintext": "QfVwXhZBt9N2SySWT9WNPAM9/TB4HwyOJVCH5hGrgmc="
# }

# in v2.0.2 this also succeeds, but it shouldn’t (missing context):
awslocal kms decrypt --key-id fc3a54e7-8d7b-467e-871b-17bd3ea565bb --ciphertext-blob fileb:///tmp/example.bin
# {
#     "KeyId": "arn:aws:kms:us-east-1:000000000000:key/fc3a54e7-8d7b-467e-871b-17bd3ea565bb",
#     "Plaintext": "QfVwXhZBt9N2SySWT9WNPAM9/TB4HwyOJVCH5hGrgmc="
# }

# now as of v2.1.0 passing the context also fails:
awslocal kms decrypt --key-id fc3a54e7-8d7b-467e-871b-17bd3ea565bb --ciphertext-blob fileb:///tmp/example.bin --encryption-context foo=bar
# An error occurred (InvalidCiphertextException) when calling the Decrypt operation: 
```

### Environment

```markdown
- OS: macOS Ventura 13.4
- LocalStack: 2.1.0/latest
```

**Comment by davecardwell** [comment]
This may be related to/a dupe of #8503 - that issue didn’t exist when I first noticed the problem earlier today, but there was a delay before I could create this Issue and reproduction.

**Comment by nathanmcgarvey-modopayments** [comment]
FWIW: I filed #8503 after experiencing this exact issue here and finding those nasty TODOs in the code. Thanks @davecardwell for the more thorough write-up with reproducibility.

**Comment by davecardwell** [comment]
@sannya-singal Wow, thanks for the fantastic turnaround on this! I tried it out with `localstack/localstack-pro:latest` and my immediate problem is fixed!

I’m happy for you to close this issue as complete if you want, though I noticed [some additional feedback](https://github.com/localstack/localstack/pull/8517#issuecomment-1594472353) from @nathanmcgarvey-modopayments on your PR after merge, so also fine if you want to keep this open.

**Comment by sannya-singal** [comment]
Hey @davecardwell, thanks for your feedback. We are delighted that the resolution is working 🚀. The issue @nathanmcgarvey-modopayments mentioned regarding the `GenerateDataKeyPair` handler was already in pipeline (shall be done by today) but just to roll out an immediate fix of the mentioned issue we released it on Friday. Thank you! 🙂
