### ISSUE TITLE
Lambda SQS event source listener calls are no longer identified as internal calls

### ISSUE THREAD

**Issue by thrau** [localstack/localstack#8525]
I've noticed that, since #8450, the SQS polling calls of an SQS event source listener will log every `ReceiveMessage` call, because it is no longer flagged as internal call here https://github.com/localstack/localstack/blob/0c507278b4410c4752f70c3c9afe7f081ca650fe/localstack/aws/handlers/logging.py#L85

Presumably this extends to other event source listeners, potentially also to other instances where we've replaced the internal clients, but I haven't tested it. /cc @viren-nadkarni

**Comment by dfangl** [comment]
Should be fixed with #8582 .
