### ISSUE TITLE
bug: lambda fails to write to /tmp mounted volume

### ISSUE THREAD

**Issue by SledgeHammer01** [localstack/localstack#8534]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Localstack 2.1.0 running on a Windows 10 x64 Pro.

I'm using docker-compose to mount a volume into the /tmp folder:

    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - /var/run/docker.sock:/var/run/docker.sock
      - c:\var\logs:/tmp/logs

When I open a terminal into the container, /tmp/logs is mounted, and I can see / share files with the host. Running Python from the command line and importing the lambda.py and calling the file writing code works. When the lambda attempts to write in response to a Kinesis event, I get cannot find file /tmp/logs/myprocessor.log.

### Expected Behavior

Be able to write to a mounted volume in the /tmp folder.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

docker-compose + terraform

### Environment

```markdown
- OS: Windows 10 x64 Pro
- LocalStack: 2.1.0
```

**Comment by dfangl** [comment]
Our lambda provider will spawn new containers as environments for lambda. Therefore, your mount will not be exposed to the containers, each environment will have it's own `/tmp`, as on AWS.

If you want to expose the host filesystem to a lambda, please use `LAMBDA_DOCKER_FLAGS`, like this: `LAMBDA_DOCKER_FLAGS=-v c:\var\logs:/tmp/logs`.

**Comment by SledgeHammer01** [comment]
@dfangl I updated my docker-compose to:

    environment:
      - AWS_DEFAULT_REGION=us-west-2
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - SERVICES=kinesis,dynamodb,lambda
      - DD_SERVICE=dtms-stream-processor
      - DD_ENV=staging
      - DD_LOGS_INJECTION=true
      - DD_AGENT_HOST=host.docker.internal
      - LAMBDA_DOCKER_FLAGS=-v c:\var\logs:/tmp/logs

Now I get a different failure:

2023-06-21T02:21:53.544  INFO --- [   asgi_gw_3] localstack.request.aws     : AWS sts.AssumeRole => 200
2023-06-21T02:21:53.553699700Z 2023-06-21T02:21:53.553  WARN --- [or:$LATEST_0] l.u.c.container_client     : Overwriting Docker container privileged flag None with new value False

**Comment by SledgeHammer01** [comment]
@dfangl I tried updating my docker-compose to localstack latest and now I get a further different message:

133  WARN --- [or:$LATEST_0] l.s.a.i.runtime_environmen : Failed to start runtime environment for ID=cfb27f22028358a96540fca0ddfe4841 with: 
2023-06-21T21:19:24.391083700Z 2023-06-21T21:19:24.

**Comment by SledgeHammer01** [comment]
@dfangl through experimentation, I found the issue. For Windows paths, you need to specify as: `- LAMBDA_DOCKER_FLAGS=-v c:\\var\\logs:/tmp/logs`

**Comment by dfangl** [comment]
Thanks for the correction, i did not try it out as I did not have a windows machine on me. it seems the backslashes need to be escaped. Does it work with this configuration?

**Comment by SledgeHammer01** [comment]
Yes, the lambda is now able to write the file to the mounted volume and its reflected back to the Windows host. Thanks!

**Comment by SledgeHammer01** [comment]
Issue resolved with escaping backslashes.

**Comment by mauleyzaola** [comment]
> Issue resolved with escaping backslashes

Probably the main reason I hate Windows.
