### ISSUE TITLE
S3 Static website Index.html returned as XML

### ISSUE THREAD

**Issue by ziphrax** [localstack/localstack#854]
Not sure if I'm doing something wrong  or missing something daft, but when I attempted to set up a static website on s3 and request the website, i get the html page rendered a xml in chrome. Is it because the Content-Type is application/xml? 

Expected behaviour
Using Chrome browse to http://192.168.99.100:4572/TestBucket/index.html returns my webpage rendered correctly

Steps to reproduce
from a working directory containing my index.html page.
aws --endpoint-url=http://192.168.99.100:4572 s3api create-bucket --bucket TestBucket
aws --endpoint-url=http://192.168.99.100:4752 s3 sync . s3://TestBucket --acl public-read
aws --endpoint-url=http://192.168.99.100:4752 s3 website s3://TestBucket --index-document index.html

**Comment by twhitbeck** [comment]
same issue here. Is it because of this?
https://github.com/localstack/localstack/blob/dd47af6e4a5f753fba97eae0d32551321382b258/localstack/services/s3/s3_listener.py#L556-L557

**Comment by benfonty** [comment]
Hello, I have the same issue with signed urls that access html files in a S3 bucket.

The html files are served with an 'application/xml' content type.

Is there a reason for the piece of python code shown above to exist ?

**Comment by benvandenberg** [comment]
I made a short-term fix that works for my team. In s3_listener.py, change the return_response method from

    # fix content-type: https://github.com/localstack/localstack/issues/618
    #                   https://github.com/localstack/localstack/issues/549
    if 'text/html' in response.headers.get('Content-Type', ''):
        response.headers['Content-Type'] = 'application/xml; charset=utf-8'

to

    # fix content-type: https://github.com/localstack/localstack/issues/618
    #                   https://github.com/localstack/localstack/issues/549
    if 'text/html' in response.headers.get('Content-Type', '')\
            and not response_content_str.startswith('<!doctype html'):
        response.headers['Content-Type'] = 'application/xml; charset=utf-8'

This assumes your HTML file starts with `<!doctype html>`. It's not a good long-term solution, but can be used to work around the problem for the time being.

**Comment by whummer** [comment]
Thanks for looking into this @benvandenberg @benfonty @jtcmedia @twhitbeck @ziphrax . Took the suggestion from @benvandenberg and added the change in PR #1671

**Comment by ricoli** [comment]
Hi @whummer , thank you for the PR, but as I've commented in https://github.com/localstack/localstack/pull/1671/files#r337993711, the check should be case insensitive though, as per the specification.

**Comment by whummer** [comment]
Yep, thanks for the comment @ricoli - good point, will be fixed in a follow-up PR. 👍

**Comment by quyentho** [comment]
Hello,

I'm still facing this issue. I'm using latest docker image from localstack/localstack.

When I access the endpoint **http://mybucket.localhost.localstack.cloud:4566/* the content is recognized as XML file
