### ISSUE TITLE
How to deploy serverless framework in localstack?

### ISSUE THREAD

**Issue by technoartista** [localstack/localstack#855]
https://www.npmjs.com/package/serverless-offline-localstack
https://www.npmjs.com/package/serverless-localstack

These 2 plugins doesn't seem to work very well , Does anyone have deployed serverless in local stack if so help us

**Comment by HoldenRiot** [comment]
I second this. This would be helpful for my current project(s). Thanks.

**Comment by lalarsson** [comment]
Same here! I have a configuration that should work but ends up with the following error every time.

Others have the same problem, please see https://github.com/temyers/serverless-localstack/issues/36

**Comment by edge0701** [comment]
Same issue here. About to go and do some digging. Will let you know what I find.

**Comment by garethmcc** [comment]
@edge0701 Any luck?

**Comment by ahmed-abdulmoniem** [comment]
Any update?

**Comment by jpcbarros** [comment]
It would also be very helpful for me. +1

**Comment by jackphilippi** [comment]
+1

**Comment by suryacaprice** [comment]
any updaes from the localstack team on this . This would be a great feature

**Comment by SpringSuliman** [comment]
+1

**Comment by Koalk** [comment]
+1

**Comment by whummer** [comment]
There have been some updates in LocalStack and changes in `serverless-localstack` recently. Can you please retry creating your stacks. There are still some corner cases and also a lot of unsupported resources, but the general e2e integration with Serverless should work.

Also @temyers - I noticed that the repo has been archived: https://github.com/temyers/serverless-localstack We would like to continue development on the plugin - would you mind transferring/sharing ownership of this npm package? https://www.npmjs.com/package/serverless-localstack (My npm username is `whummer`) Thanks!

**Comment by whummer** [comment]
For now, we have forked the project and released it under a new `npm` package: `localstack-serverless`. Going to close this issue now, please comment here or create specific follow-up issues for any problems that might come up. Thanks

**Comment by Koalk** [comment]
Can't seem to create tickets on the new project, feel free to copy this into it once issues are enabled on it.
I am trying to deploy a local version of 2 lambdas plus a stepfunction, all quite basic stuff.
I get a 500 error from the serverless side of the deployment and quite the amount of logs in the localstack side. I'll put both here in case they are of any use.
[Localstack logs](https://pastebin.com/TvHgRZ38)
[Serverless logs](https://pastebin.com/68RYTsLE)
[serverless.yml](https://pastebin.com/RkABm2HB)

Is suppose to be a basic "lambda one loads new data somewhere and lambda two does some processing on it" with the step function as a glue between them and failover.

**Comment by whummer** [comment]
Thanks @Koalk - issues are now enabled: https://github.com/localstack/localstack-serverless/issues/3

**Comment by lwoodson** [comment]
I am happy to see this being moved to the `localstack` org.  @whummer I would suggest you change the note on your old [temyers/serverless-localstack](https://github.com/temyers/serverless-localstack) project.  It currently reads:

## Archived
This project is no longer under active development.

Which had me wondering if the serverless-localstack plugin was simply abandoned.  I would change this note to be:

The serverless-localstack plugin has been taken over by the localstack org with [a fork of this project here](https://github.com/localstack/serverless-localstack).  This project is no longer under active development.

Which will guide people to the new project and let them know the plugin is not dead.

**Comment by winly19** [comment]
> Can't seem to create tickets on the new project, feel free to copy this into it once issues are enabled on it.
> I am trying to deploy a local version of 2 lambdas plus a stepfunction, all quite basic stuff.
> I get a 500 error from the serverless side of the deployment and quite the amount of logs in the localstack side. I'll put both here in case they are of any use.
> [Localstack logs](https://pastebin.com/TvHgRZ38)
> [Serverless logs](https://pastebin.com/68RYTsLE)
> [serverless.yml](https://pastebin.com/RkABm2HB)
> 
> Is suppose to be a basic "lambda one loads new data somewhere and lambda two does some processing on it" with the step function as a glue between them and failover.
