### ISSUE TITLE
bug: Terraform Lambda Function vpc_config doesn't get updated in terraform state

### ISSUE THREAD

**Issue by FarhanSajid1** [localstack/localstack#8556]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Whenever an apply is ran, the security group ids and subnet ids get updated to the same value.
```
      + vpc_config {
          + security_group_ids = [
              + "sg-30710aba47f78b56c",
            ]
          + subnet_ids         = [
              + "subnet-99026414",
            ]
        }
        # (4 unchanged blocks hidden)
    }
```

Looking at the terraform state file
```
       "tracing_config": [
              {
                "mode": "Active"
              }
            ],
            "version": "3",
            "vpc_config": []
          },
```

the `vpc_config` values are empty.

### Expected Behavior

A no op should occur

### How are you starting LocalStack?

With the `localstack` script

### Steps To Reproduce

localstack start
Create a lambda function with a vpc and security group
Reapply

### Environment

```markdown
- OS:
- LocalStack:
```

**Comment by dominikschubert** [comment]
Hi @FarhanSajid1 ! This issue should be fixed in the latest version, please pull the newest image and give it a try.
