### ISSUE TITLE
bug: can't create s3 bucket via terraform

### ISSUE THREAD

**Issue by SledgeHammer01** [localstack/localstack#8561]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Terraform:

```
provider "aws" {
  region                      = "us-west-2"
  access_key                  = "123"
  secret_key                  = "abc"
  skip_credentials_validation = true
  skip_metadata_api_check     = true
  skip_requesting_account_id  = true

  endpoints {
    kinesis  = "http://localhost:4566"
    dynamodb = "http://localhost:4566"
    lambda   = "http://localhost:4566"
    s3       = "http://localhost:4566"
  }
}

resource "aws_s3_bucket" "xxx-stage-atails" {
  bucket = "xxx-stage-atails"

  tags = {
    Name        = "xxx-stage-atails"
    Environment = "stage"
  }
}
```

terraform apply stuck in a loop on the bucket creation. All other resources are creating. I also tried switching to the us-east-1 region.

`awslocal s3api create-bucket --bucket test` fails and I need to specify `--region=us-east-1` which is why I tried switching the region to us-east-1.

Also note, I am running the terraform apply on the host Windows machine.

### Expected Behavior

That I'm able to create an S3 bucket through terraform.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal s3 mb s3://mybucket

### Environment

```markdown
- OS:Windows 10 Pro x64
- LocalStack: latest
```

**Comment by pmdurrant** [comment]
still happening 

![Image](https://github.com/user-attachments/assets/56ff6a3e-93e6-4c38-840f-bcaac016d622)

**Comment by rtoth11** [comment]
For me it was because of missing ListBucket permission
