### ISSUE TITLE
[question] Is there a quick way to "seed" s3?

### ISSUE THREAD

**Issue by jcswart** [localstack/localstack#857]
I have a lot of files that I want to put into localstack s3. It is currently taking a long time through `awslocal`. I am wondering if there is a better way.

**Comment by whummer** [comment]
Yes, there is - please refer to this section of the README: https://github.com/localstack/localstack#initializing-a-fresh-instance Thanks

**Comment by burmecia** [comment]
above link is broken, use `init-hooks` instead and the new doc is here https://docs.localstack.cloud/references/init-hooks/
