### ISSUE TITLE
enhancement request: cloudformation update_stack 

### ISSUE THREAD

**Issue by sankethsj** [localstack/localstack#8576]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Enhancement description

Please add support for "UsePreviousTemplate" parameter in update_stack API of Cloudformation service.

Currently, without TemplateBody or TemplateURL, get_template_body method just raises an Exception. I think we can get the template using get_template API.

### 🧑‍💻 Implementation

get_template_body function accepts req_data as parameter, so we can get the stack name from this and
if UsePreviousTemplate=True found in the req_data, we can fetch the template using the get_template API.

**Comment by alexrashed** [comment]
Hi @sankethsj!
Could you maybe give us a short sample illustrating your issue, as well as a log containing the stack trace of the exception you mentioned? Thanks!

**Comment by sankethsj** [comment]
Hi @alexrashed ,

Here's my code which uses **create_stack** to create an IAM Role and **update_stack** to update the role name.
```python
client = boto3.client('cloudformation')

stack_name = "test-stack"
stack_template = "https://s3.amazonaws.com/test-bucket/iam-role.yml"

response = client.create_stack(
    StackName=stack_name,
    TemplateURL=stack_template,
    Parameters=[
        {
            'ParameterKey': 'MyRoleName',
            'ParameterValue': 'sample-test-role'
        }
    ]
)

response = client.update_stack(
    StackName=stack_name,
    UsePreviousTemplate=True,
    Parameters=[
        {
            'ParameterKey': 'MyRoleName',
            'ParameterValue': 'sample-test-role-new'
        }
    ]
)
```


This is all I could get from the terminal.
```bash
localstack_main  | 2023-06-28T16:16:11.742 ERROR --- [   asgi_gw_1] l.aws.handlers.logging     : exception during call chain: Unable to get template body from input: {'StackName': 'test-stack', 'UsePreviousTemplate': True, 'Parameters': [{'ParameterKey': 'MyRoleName', 'ParameterValue': 'sample-test-role-new'}], 'Tags': [{'Key': 'User', 'Value': 'imposter'}]}
localstack_main  | 2023-06-28T16:16:11.746  INFO --- [   asgi_gw_1] localstack.request.aws     : AWS cloudformation.UpdateStack => 500 (InternalError)
```

As you can see, I'm passing  `'UsePreviousTemplate': True` instead of TemplateBody or TemplateURL.
As per [boto3 docs](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/cloudformation/client/update_stack.html), this is allowed.

The error message "Unable to get template body from input" is raised from the below code :
```python
# localstack/localstack/services/cloudformation/api_utils.py
def get_template_body(req_data: dict) -> str:
    ...
    raise Exception("Unable to get template body from input: %s" % req_data)
```

If I change my code to use TemplateURL instead, it works perfectly fine.
```python
response = client.update_stack(
    StackName=stack_name,
    # UsePreviousTemplate=True,
    TemplateURL=stack_template,
    Parameters=[
        {
            'ParameterKey': 'MyRoleName',
            'ParameterValue': 'sample-test-role-new'
        },
    ]
)
```
But I wanted to check if we can add support for `'UsePreviousTemplate': True` since it is supported by AWS.

I think we can update `get_template_body` function as I mentioned in the Implementation section above (or any other better way), right ?

**Comment by sankethsj** [comment]
Hi @alexrashed,

I tried to add `'UsePreviousTemplate': True` parameter support. Please check this code : https://github.com/localstack/localstack/commit/b16ca8af0b0ee91f11c2995ae7c9f15b3c5f8ca5

And now my above example code I shared is working fine with this update.

Please review and let me know if it's ok to submit a PR.

**Comment by simonrw** [comment]
Hi @sankethsj, thanks for providing this change, we really appreciate community contributions! 

Unfortunately the CloudFormation service in LocalStack is currently in a state of flux, and it's not a good time for community contributions right now. For this reason we have added this request (and contribution) to our backlog and we will use this issue to keep you informed. Is that ok?

**Comment by sankethsj** [comment]
Hi @simonrw , ok, no problem.
Thank you for your response.
I'll close this issue as 'Not planned'.
