### ISSUE TITLE
v0.8.7 - Uncaught (in promise) Error: the specified bucket does not exist

### ISSUE THREAD

**Issue by dlwire** [localstack/localstack#858]
Since updating to localstack 0.8.7, I now see this exception raised when trying to upload a file to a bucket. The bucket exists and the file can be uploaded using the aws cli.

We add a prefix to the key of the format: `<dir>/<key>`

The bucket that the network response indicates is missing is `<dir>`.

Uploading a file to `<dir>` within the bucket and then trying the same request fails in the same fashion.

**Comment by dlwire** [comment]
I checked 0.8.6.2 and that version still has the issue. I did not check 0.8.6.1 but 0.8.6 works fine. If I find time this weekend or next week I'll check in 0.8.6.1.

**Comment by intelease** [comment]
@dlwire Did you find a solution for this? I'm having similar issue with the current latest version (0.10.2). The bucket exists, according to AWS CLI. But my Java code gives `the specified bucket does not exist` as well..

**Comment by dlwire** [comment]
I don't believe so, no. Though to be honest, I haven't touched this since July of last year and I'm having some trouble remembering specifics.

**Comment by whummer** [comment]
Thanks for reporting @dlwire @intelease . Can you please provide a small, self-contained example (ideally a sequence of `awslocal` commands) to reproduce this issue?

**Comment by dlwire** [comment]
So, it's been over a year since we encountered this issue - unfortunately, that means I'm a little shorter on specifics than I'd like to be.

Based on my notes here, it appears as though the AWS CLI was interacting correctly with localstack but I can't say for certain:
> The bucket exists and the file can be uploaded using the aws cli.

I'm guessing here - but there appears to have been an issue with communication between amazon's python sdk (and presumably the java sdk as well based on intelease's comment) and localstack.

Since the same version of the SDK worked on the earlier versions of localstack and did not work on the later version, I opened a defect here.

All that said, we recently upgraded to localstack v0.10.4 and didn't encounter any issues so it seems likely this has somehow resolved itself. Though intelease's experience may be different.

**Comment by whummer** [comment]
Thanks for the update @dlwire . I'm tempted to close this one, for lack of concrete steps to reproduce. Our S3 API has been reworked significantly in the meantime - quite possibly this has already been fixed by now. Thanks again.

/cc @intelease - please give us an update if the problem persists for you. Thanks
