### ISSUE TITLE
Transparent Endpoint Injection for .net 

### ISSUE THREAD

**Issue by bokupna** [localstack/localstack#8586]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Enhancement description

PLease add support for for .NET for [Transparent Endpoint Injection](https://docs.localstack.cloud/user-guide/tools/transparent-endpoint-injection/)

**Comment by alexrashed** [comment]
Hi @bokupna!
The DNS based transparent endpoint injection is a pro feature which is supported for all Lambda runtimes.
Could you please add some more details?
What does your stack look like? How do you start localstack? What version are you on? How does the Lambda code - accessing other services - look like?
Thanks!
