### ISSUE TITLE
bug: Improper SES Validation on Tags

### ISSUE THREAD

**Issue by ajrice6713** [localstack/localstack#8588]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

SES allows invalid characters in the Tag list that dont match what AWS allows.

### Expected Behavior

Localstack SES returns a 400 if invalid characters are present in any tags

From AWS: 

```
Error: operation error SES: SendEmail, https response error StatusCode: 400, RequestID: 7a8b9317-e8c6-4ae9-a999-f7ee53ffe487, api error InvalidParameterValue: Invalid tag value <event:id:abc1234>: only alphanumeric ASCII characters, '_', and '-' are allowed.
```

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

Set a tag in SES sendEmail request to be `abc:123` in AWS 

### Environment

```markdown
- OS:
- LocalStack: latest
```

**Comment by sannya-singal** [comment]
Hi @ajrice6713! Thanks for reporting this issue. We have added the fix in #8639.
Please pull the `latest` docker image and give it a try. Thanks!
