### ISSUE TITLE
bug: AWS::ApiGateway::Method cloudformation fails due to REF tag 

### ISSUE THREAD

**Issue by pankajpreetsinghAW** [localstack/localstack#8597]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When creating api-gateway(rest api) trigger for lambda function it fails with error below. Same Coudformation template works for AWS account.
`Unexpected error processing resource type AWS::ApiGateway::Method: Exception: Parameter validation failed:
2023-06-29 12:18:05 Invalid type for parameter restApiId, value: {'Ref': 'ARMockIntegrationAPIGateway'}, type: <class 'dict'>, valid types: <class 'str'>
2023-06-29 12:18:05 Invalid type for parameter resourceId, value: {'Ref': 'ProxyResource'}, type: <class 'dict'>, valid types: <class 'str'> - {'AuthorizationType': 'NONE', 'HttpMethod': 'ANY', 'Integration': {'IntegrationHttpMethod': 'POST', 'Type': 'AWS_PROXY', 'Uri': {'Fn::Sub': ['arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaArn}/invocations', {'LambdaArn': {'Fn::GetAtt': ['ARMockIntegrationLambdaFunction', 'Arn']}}]}}, 'ResourceId': {'Ref': 'ProxyResource'}, 'RestApiId': {'Ref': 'ARMockIntegrationAPIGateway'}} - status: None
2023-06-29 12:18:05 2023-06-29T18:18:05.720  WARN --- [functhread24] l.s.c.resource_provider    : Unexpected error processing resource type AWS::ApiGateway::Method: Exception: Parameter validation failed:
2023-06-29 12:18:05 Invalid type for parameter restApiId, value: {'Ref': 'ARMockIntegrationAPIGateway'}, type: <class 'dict'>, valid types: <class 'str'>
2023-06-29 12:18:05 Invalid type for parameter resourceId, value: {'Ref': 'ProxyResource'}, type: <class 'dict'>, valid types: <class 'str'> - {'AuthorizationType': 'NONE', 'HttpMethod': 'ANY', 'Integration': {'IntegrationHttpMethod': 'POST', 'Type': 'AWS_PROXY', 'Uri': {'Fn::Sub': ['arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaArn}/invocations', {'LambdaArn': {'Fn::GetAtt': ['ARMockIntegrationLambdaFunction', 'Arn']}, 'AWS::Region': {'Ref': 'AWS::Region'}, 'AWS::Partition': {'Ref': 'AWS::Partition'}, 'AWS::StackName': {'Ref': 'AWS::StackName'}, 'AWS::AccountId': {'Ref': 'AWS::AccountId'}}]}}, 'ResourceId': {'Ref': 'ProxyResource'}, 'RestApiId': {'Ref': 'ARMockIntegrationAPIGateway'}} - status: None`

### Expected Behavior

Lambda created with apigateway trigger. 

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)
docker-compose.yml
`services:
 localstack:
    container_name: alocalstack
    image: localstack/localstack
    ports:
      - 4566:$4566
    volumes:
      - /init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh
      - /var/run/docker.sock:/var/run/docker.sock`

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)
#Create bucket
aws s3api create-bucket --bucket $L_S3_BUCKET --region us-east-1 --endpoint-url=$ENDPOINT --profile=$L_AWS_PROFILE

# upload lambda function
aws --endpoint-url=$(ENDPOINT)  s3 cp function.zip  $(L_S3_BUCKET_URI)/$(IDENTIFIER)

# deploy cloudformation
@aws --endpoint-url=$(ENDPOINT)  cloudformation create-stack --capabilities CAPABILITY_NAMED_IAM --stack-name $(CLOUDFORMATION_STACK_NAME) --template-body file://output.json --parameters file://parameters.json

**Output.json**
`{
    "Metadata": {
        "Cell": "test-function",
        "Name": "test-function"
    },
    "Parameters": {
        "TestArtifactKey": {
            "Description": "The key for the lambda source code.",
            "Type": "String"
        },
        "TestArtifactBucket": {
            "Description": "The S3 bucket the lambda artifacts are in.",
            "Type": "String"
        },
        "Cell": {
            "Description": "Cell name used to tag all resources.",
            "Type": "String"
        },
        "CellType": {
            "Description": "Cell type used to tag all resources.",
            "Type": "String"
        },
        "Environment": {
            "Description": "Environment name used to tag all resources",
            "Type": "String"
        },
        "Profile": {
            "Description": "Profile name used to tag all resources",
            "Type": "String"
        },
        "Tier": {
            "Description": "Tier used to tag all resources.",
            "Type": "String"
        }
    },
    "Resources": {
        "TestAPIGateway": {
            "Properties": {
                "EndpointConfiguration": {
                    "Types": [
                        "REGIONAL"
                    ]
                },
                "Name": {
                    "Fn::Join": [
                        "-",
                        [
                            {
                                "Ref": "Environment"
                            },
                            {
                                "Ref": "Cell"
                            },
                            "api"
                        ]
                    ]
                }
            },
            "Type": "AWS::ApiGateway::RestApi"
        },
        "TestApiDeployment": {
            "DependsOn": "RootAnyMethod",
            "Properties": {
                "Description": "Deployment stage for the API.",
                "RestApiId": {
                    "Ref": "TestAPIGateway"
                }
            },
            "Type": "AWS::ApiGateway::Deployment"
        },
        "TestApiStage": {
            "Properties": {
                "DeploymentId": {
                    "Ref": "TestApiDeployment"
                },
                "Description": "API stage for development",
                "RestApiId": {
                    "Ref": "TestAPIGateway"
                },
                "StageName": "prod"
            },
            "Type": "AWS::ApiGateway::Stage"
        },
        "TestLambdaFunction": {
            "Properties": {
                "Code": {
                    "S3Bucket": {
                        "Ref": "TestArtifactBucket"
                    },
                    "S3Key": {
                        "Ref": "TestArtifactKey"
                    }
                },
                "Environment": {
                    "Variables": {
                        "Environment": {
                            "Ref": "Environment"
                        }
                    }
                },
                "FunctionName": {
                    "Fn::Join": [
                        "-",
                        [
                            {
                                "Ref": "Environment"
                            },
                            {
                                "Ref": "Cell"
                            }
                        ]
                    ]
                },
                "Handler": "mock-integration",
                "MemorySize": 128,
                "Role": {
                    "Fn::GetAtt": [
                        "TestLambdaRole",
                        "Arn"
                    ]
                },
                "Runtime": "go1.x",
                "Timeout": 300
            },
            "Type": "AWS::Lambda::Function"
        },
        "TestLambdaRole": {
            "Properties": {
                "AssumeRolePolicyDocument": {
                    "Statement": [
                        {
                            "Action": [
                                "sts:AssumeRole"
                            ],
                            "Effect": "Allow",
                            "Principal": {
                                "Service": [
                                    "lambda.amazonaws.com"
                                ]
                            }
                        }
                    ],
                    "Version": "2012-10-17"
                },
                "Policies": [
                    {
                        "PolicyDocument": {
                            "Statement": [
                                {
                                    "Action": [
                                        "logs:CreateLogGroup",
                                        "logs:CreateLogStream",
                                        "logs:PutLogEvents"
                                    ],
                                    "Effect": "Allow",
                                    "Resource": [
                                        {
                                            "Fn::Sub": [
                                                "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${LambdaFunction}:*",
                                                {
                                                    "LambdaFunction": {
                                                        "Fn::Join": [
                                                            "-",
                                                            [
                                                                {
                                                                    "Ref": "Environment"
                                                                },
                                                                {
                                                                    "Ref": "Cell"
                                                                }
                                                            ]
                                                        ]
                                                    }
                                                }
                                            ]
                                        },
                                        {
                                            "Fn::Sub": [
                                                "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${LambdaFunction}",
                                                {
                                                    "LambdaFunction": {
                                                        "Fn::Join": [
                                                            "-",
                                                            [
                                                                {
                                                                    "Ref": "Environment"
                                                                },
                                                                {
                                                                    "Ref": "Cell"
                                                                }
                                                            ]
                                                        ]
                                                    }
                                                }
                                            ]
                                        },
                                        {
                                            "Fn::Sub": [
                                                "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/notification-${LambdaFunction}:*",
                                                {
                                                    "LambdaFunction": {
                                                        "Fn::Join": [
                                                            "-",
                                                            [
                                                                {
                                                                    "Ref": "Environment"
                                                                },
                                                                {
                                                                    "Ref": "Cell"
                                                                }
                                                            ]
                                                        ]
                                                    }
                                                }
                                            ]
                                        },
                                        {
                                            "Fn::Sub": [
                                                "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/notification-${LambdaFunction}",
                                                {
                                                    "LambdaFunction": {
                                                        "Fn::Join": [
                                                            "-",
                                                            [
                                                                {
                                                                    "Ref": "Environment"
                                                                },
                                                                {
                                                                    "Ref": "Cell"
                                                                }
                                                            ]
                                                        ]
                                                    }
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ],
                            "Version": "2012-10-17"
                        },
                        "PolicyName": "TestLambdaPolicy"
                    }
                ],
                "RoleName": {
                    "Fn::Join": [
                        "-",
                        [
                            {
                                "Ref": "Environment"
                            },
                            {
                                "Ref": "Cell"
                            }
                        ]
                    ]
                }
            },
            "Type": "AWS::IAM::Role"
        },
        "LambdaPermission": {
            "Properties": {
                "Action": "lambda:InvokeFunction",
                "FunctionName": {
                    "Fn::GetAtt": [
                        "TestLambdaFunction",
                        "Arn"
                    ]
                },
                "Principal": "apigateway.amazonaws.com",
                "SourceArn": {
                    "Fn::Sub": [
                        "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${RestApiId}/*",
                        {
                            "RestApiId": {
                                "Ref": "TestAPIGateway"
                            }
                        }
                    ]
                }
            },
            "Type": "AWS::Lambda::Permission"
        },
        "ProxyResource": {
            "Properties": {
                "ParentId": {
                    "Fn::GetAtt": [
                        "TestAPIGateway",
                        "RootResourceId"
                    ]
                },
                "PathPart": "{proxy+}",
                "RestApiId": {
                    "Ref": "TestAPIGateway"
                }
            },
            "Type": "AWS::ApiGateway::Resource"
        },
        "RootAnyMethod": {
            "Properties": {
                "AuthorizationType": "NONE",
                "HttpMethod": "ANY",
                "Integration": {
                    "IntegrationHttpMethod": "POST",
                    "Type": "AWS_PROXY",
                    "Uri": {
                        "Fn::Sub": [
                            "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaArn}/invocations",
                            {
                                "LambdaArn": {
                                    "Fn::GetAtt": [
                                        "TestLambdaFunction",
                                        "Arn"
                                    ]
                                }
                            }
                        ]
                    }
                },
                "ResourceId": {
                    "Ref": "ProxyResource"
                },
                "RestApiId": {
                    "Ref": "TestAPIGateway"
                }
            },
            "Type": "AWS::ApiGateway::Method"
        }
    }
}`

### Environment

```markdown
- OS: Mac
- LocalStack: latest
```

### Anything else?

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-method.html

**Comment by pinzon** [comment]
I just triaged this issue with the latest version of LocalStack and your template is deployable. Please let us know if you still encounter the same problem. Thanks.
