### ISSUE TITLE
Localstack Receive message failing with aws sdk v3 and Jdk 17

### ISSUE THREAD

**Issue by ab48917** [localstack/localstack#8600]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am using jdk17 + aws sdk 3.0.1 and localstack 1.18.3. 

I am able to create the localstack containers and push the messages to a sample queue by creating queue using same sqsAsyncClient bean as below, 

```
sqsAsyncClient.createQueue(CreateQueueRequest.builder().queueName("sample-queue")
                .attributes(Collections.singletonMap(QueueAttributeName.VISIBILITY_TIMEOUT, "1"))
                .build());

        SqsTemplate sqsTemplate = SqsTemplate.builder().sqsAsyncClient(sqsAsyncClient).build();
```

However, I am getting queuenotfound while trying to receive the messages from localstack. I can see the messages available in created queue using console command. Earlier I was using @SqsListener but couldn't see any exceptions even with debug so tried manually polling the message and seems with CompletableFuture<ReceiveMessageResponse>, Its failing to poll the messages or may be somehow messing the region. 

Below is snippet for manually polling the queue - 

```
CompletableFuture<ReceiveMessageResponse> responseFuture = sqsAsyncClient.receiveMessage(ReceiveMessageRequest.builder()
                .queueUrl(queueUrl).visibilityTimeout(2).waitTimeSeconds(2)
                .build());
        responseFuture
                .thenApply(receiveMessageResponse -> receiveMessageResponse.messages())
                .thenAccept(sqsMListener -> sqsMListener.forEach(sqsMessage -> {
                    log.debug("FreshSQSListener message received {}  ", sqsMessage.body());
                }));

```
<img width="1528" alt="Screenshot 2023-07-01 at 2 56 11 AM" src="https://github.com/localstack/localstack/assets/27356524/513df113-97c1-4c31-983a-aa4abcc7141e">

### Expected Behavior

I should be able to receive the messages using both polling and @SqsListener. It seems that region set in SqsAsyncClient is not getting reflected while polling the queue. 

Below is code snippet for SqsAsyncClient - 

```
@Bean
    public DockerImageName getDockerImageName() {
        return DockerImageName.parse("localstack/localstack:2.1.0");
    }

    @Bean
    public LocalStackContainer getLocalStackContainer(DockerImageName dockerImageName) {
        LocalStackContainer localStackContainer = new LocalStackContainer(dockerImageName)
                .withExposedPorts(4566)
                .withNetwork(Network.newNetwork())
                .withAccessToHost(true)
                .withEnv("LOCALSTACK_HOST","10.25.6.1")
                .withEnv("SKIP_SSL_CERT_DOWNLOAD", "true")
                .withEnv("OUTBOUND_HTTP_PROXY", "http://{proxy}:{port}")
                .withEnv("OUTBOUND_HTTPS_PROXY", "http://{proxy}:{port}")
                .withEnv("DEFAULT_REGION","us-east-1")
                .withServices(LocalStackContainer.Service.SQS);
        localStackContainer.start();
        localStackContainer.getEndpointOverride(LocalStackContainer.Service.SQS);
        return localStackContainer;
    }

    @Bean
    @Primary
    public SqsAsyncClient sqsAsyncClient(LocalStackContainer localStackContainer){
        return SqsAsyncClient.builder()
                .credentialsProvider(StaticCredentialsProvider
                        .create(AwsBasicCredentials.create(localStackContainer.getAccessKey(), localStackContainer.getSecretKey())))
                .endpointOverride(localStackContainer.getEndpointOverride(LocalStackContainer.Service.SQS))
                .region(Region.US_EAST_1).build();
    }
```
Please have a look at localstack side and assist if we are missing to set the region by any chance. I use to get same exception if I dont run the console command with region. 

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

I am starting the containers using above beans mentioned in code snippet from a @Configuration file called TestConfig and having a test that pushes the messages to queue after that a separate method from different class for consuming the messages and calling the method from test. 

### Environment

```markdown
- OS:Mac Ventura
- LocalStack: 1.18.3
```

**Comment by tinyg210** [comment]
The user reached out to us on the [community Slack](https://localstack-community.slack.com/archives/CLRFWBFC3/p1688190696920039) where we asked for a reproducible sample, which is still pending. We need the sample to determine the exact root of the problem before we label it. We also provided some working examples, that could serve as a guide.

**Comment by ab48917** [comment]
@tinyg210 will share the reproducible code in a while please.

**Comment by ab48917** [comment]
@tinyg210 Was occupied with other priority works. However, provided community slack solutions didn't work and we have moved for time being to TestContainers. I will get the working piece and can walk you through the main stream problem.
