### ISSUE TITLE
Localstack dynamodb stream events should contain binary fields as base64 encoded string

### ISSUE THREAD

**Issue by sumanthns-commits** [localstack/localstack#8608]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Enhancement description

Currently, the dynamodb events in localstack, contain binary value in plain binary format.

`{
    "eventID": "38fa349c",
    "eventVersion": "1.1",
    "dynamodb": {
        "ApproximateCreationDateTime": 1688456613,
        "SizeBytes": 756,
        "Keys": {
            "P": {
                "S": "primary"
            },
            "S": {
                "S": "sort"
            }
        },
        "NewImage": {
            "UUID": {
                "B": "y��#\u001A>\u0011�Qi�\\n�\u0002"
            }
        }
    },
    "awsRegion": "ap-south-1",
    "eventSource": "aws:dynamodb",
    "eventName": "INSERT",
    "tableName": "some-table"
}`

Observe that the value for "UUID" field is just in plain bytes. Its unknown if its encoded or not. If it is, its unknown what encoding it is using. 
It's not possible to deserialize this to back to any object without knowing how the bytes were encoded.

It would be great if something like base64 encoding is used, so that it becomes simpler to deserialize on consumer end.

**Comment by sumanthns-commits** [comment]
By the way, this is how it's done in real dynamo db as well. The binary field values are base64 encoded in stream events. See https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_streams_AttributeValue.html#DDB-Type-streams_AttributeValue-B

**Comment by nikhil-sarda** [comment]
Have been facing a similar issue with localstack integrated dynamodb stream events

**Comment by alexandersumer** [comment]
Facing the same problem.
