### ISSUE TITLE
enhancement request: Apprunner

### ISSUE THREAD

**Issue by dmarkey** [localstack/localstack#8613]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Enhancement description

Would be cool to have localstack support apprunner: https://aws.amazon.com/apprunner/

### 🧑‍💻 Implementation

I guess a mixture of ECS and ALB would be a good start.

### Anything else?

No

**Comment by thrau** [comment]
thanks for the suggestion @dmarkey, do you have any projects to showcase that run on apprunner, or demo deployments? anything that helps us establish the criteria for an MVP :-)

**Comment by dmarkey** [comment]
I have an apprunner app up, but on a work account so I wont be able to give you the details, but AppRunner is generally 2 parts, one part is given a docker container that has a HTTP listener, run the docker container, run healthchecks and expose on a domain https://123xyz.us-west-2.awsapprunner.com/ and autoscale given the Autoscaling configuration. The other part is the codebuild integration, this is integrated CI and deploy to AppRunner (this one is probably a lot more difficult).

**Comment by rodrigomata** [comment]
Having Apprunner support would be awesome, been using it with both Terraform and AWS CDK and it's really a great service. The workaround I've used so far for local development is relying on docker compose.

**Comment by UnderpantsGnome** [comment]
I would like to also chime in about the possibility to get AppRunner into localstack. 

Can you let me know what you would like to see from an active AppRunner stack? I can provide sanitized terraform outputs of a running service. Or possibly something else if that doesn't work.

**Comment by InvokedLambda** [comment]
I see that this issue is labled with feature and this issue is closed but I could not find it in the aws service list of the localstack website. Is it implemented or not?
