### ISSUE TITLE
bug: Deploys fails when trying to deploy a lambda code change via Serverless

### ISSUE THREAD

**Issue by mickfold** [localstack/localstack#8620]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Localstack errors when trying to deploy an update to a lambda when using serverless. 

### Expected Behavior

Deploy is successful

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

Minimal code sample: [localstack-serverless-minimal.zip](https://github.com/localstack/localstack/files/11957811/localstack-serverless-minimal.zip)

This project requires node 16 and yarn:

1. Unzip sample
2. Install dependencies - `yarn install --frozen-lockfile`
3. Deploy to localstack - `npx sls deploy --region=eu-west-2 --stage=local --verbose`
4. Deploy is successful
5. Amend handler.js body response. I changed hello to goodbye

```
exports.test = async function (event, context) {
  return {
    body: `goodbye ${event.pathParameters.value}`,
    headers: {},
    statusCode: 200,
  };
}
```
6. Deploy again - `npx sls deploy --region=eu-west-2 --stage=local --verbose`

### Environment

```markdown
- OS: AWS Workspace Linux
- LocalStack version: 2.1.1.dev20230702210139
- LocalStack Docker container id: e20cf1264284
- LocalStack build date: 2023-07-03
- LocalStack build git hash: 43a54a7
```

### Anything else?

Localstack error in logs: 

localstack_main | 2023-07-05T12:13:51.444  WARN --- [uncthread171] l.s.c.resource_provider    : Error calling <bound method ClientCreator._create_api_method.<locals>._api_call of <botocore.client.Lambda object at 0x7f92120dc5b0>> with params: {'FunctionName': 'locastack-test-local-test', 'CodeSha256': 'Yc7ZbniDCiSNpiIOeAKSKFN2LWCQqIgwXS5DsNtl13c='} for resource: {'Type': 'AWS::Lambda::Version', 'DeletionPolicy': 'Retain', 'LogicalResourceId': 'TestLambdaVersion3VQp3WCkjeW9SPLbakBjGXasKZdzsx3EPkfApjYixM', 'Properties': {'FunctionName': 'locastack-test-local-test', 'CodeSha256': 'Yc7ZbniDCiSNpiIOeAKSKFN2LWCQqIgwXS5DsNtl13c='}, '_state_': {}}
localstack_main | 2023-07-05T12:13:51.448 DEBUG --- [uncthread171] l.s.c.e.template_deployer  : Error applying changes for CloudFormation stack "locastack-test-local": An error occurred (InvalidParameterValueException) when calling the PublishVersion operation: CodeSHA256 (Yc7ZbniDCiSNpiIOeAKSKFN2LWCQqIgwXS5DsNtl13c=) is different from current CodeSHA256 in $LATEST (vbFL31rR+MMqqhTPwZZvKXLYtyIzZjXxMrtNMsY8N2I=). Please try again with the CodeSHA256 in $LATEST. Traceback (most recent call last):
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/services/cloudformation/engine/template_deployer.py", line 1182, in _run
localstack_main |     self.do_apply_changes_in_loop(changes, stack)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/services/cloudformation/engine/template_deployer.py", line 1255, in do_apply_changes_in_loop
localstack_main |     self.apply_change(change, stack=stack)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/services/cloudformation/engine/template_deployer.py", line 1376, in apply_change
localstack_main |     executor.deploy_loop(resource_provider_payload)  # noqa
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/services/cloudformation/resource_provider.py", line 585, in deploy_loop
localstack_main |     event = self.execute_action(resource_provider, payload)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/services/cloudformation/resource_provider.py", line 634, in execute_action
localstack_main |     return resource_provider.create(request)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/services/cloudformation/resource_provider.py", line 380, in create
localstack_main |     return self.create_or_delete(request)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/services/cloudformation/resource_provider.py", line 502, in create_or_delete
localstack_main |     result = invoke_function(
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/services/cloudformation/resource_provider.py", line 244, in invoke_function
localstack_main |     raise e
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/services/cloudformation/resource_provider.py", line 224, in invoke_function
localstack_main |     result = function(**params)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/client.py", line 530, in _api_call
localstack_main |     return self._make_api_call(operation_name, kwargs)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/client.py", line 964, in _make_api_call
localstack_main |     raise error_class(parsed_response, operation_name)
localstack_main | botocore.errorfactory.InvalidParameterValueException: An error occurred (InvalidParameterValueException) when calling the PublishVersion operation: CodeSHA256 (Yc7ZbniDCiSNpiIOeAKSKFN2LWCQqIgwXS5DsNtl13c=) is different from current CodeSHA256 in $LATEST (vbFL31rR+MMqqhTPwZZvKXLYtyIzZjXxMrtNMsY8N2I=). Please try again with the CodeSHA256 in $LATEST.

**Comment by whummer** [comment]
Thanks for sharing the detailed reproducible example @mickfold . We have been able to reproduce it and are looking into the issue.

As a workaround for now, you can try adding the `versionFunctions: false` flag, which will skip the function versioning, and hence we're not running into the `CodeSHA256` mismatch issue:
```
provider:
  name: aws
  runtime: nodejs16.x
  versionFunctions: false
  environment:
    NODE_ENV: dev
```

In general, setting this flag may be useful for local development - to avoid creating a large number of temporary Lambda versions if you are running many quick iteration cycles. 👍 

Btw, here's a pointer to the Lambda hot-reloading docs: https://docs.localstack.cloud/user-guide/tools/lambda-tools/hot-reloading/#hot-reloading-for-typescript-lambdas It can be a bit tricky to set up in combination with esbuild, we'll look into extending your sample to showcase how it can be configured locally. Thanks
