### ISSUE TITLE
bug: Javascript resolver utils package is empty

### ISSUE THREAD

**Issue by simonrw** [localstack/localstack#8624]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The public `@aws-appsync/utils` NPM package only contains type stubs, not function implementations, so using functions such as `util.dynamodb.toMapValues(...)` does not work.

### Expected Behavior

The following code should work:

```javascript
import { util } from '@aws-appsync/utils';

export function request(ctx) {
  return ctx;
}

export function response(ctx) {
  return {id: util.autoId()};
}
```

[[docs for example util usage](https://docs.aws.amazon.com/appsync/latest/devguide/built-in-util-js.html#26-1688569678205-1170)]

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker compose up

### Environment

```markdown
- OS: any
- LocalStack: latest
```

**Comment by charleswong28** [comment]
I faced the same problem. Does anyone have a workaround on this one?

**Comment by simonrw** [comment]
We added basic support for js utils starting with the dynamodb functions recently. Can you pull the latest `localstack/localstack-pro` docker image, and try again with `APPSYNC_JS_LIBS_VERSION=refresh`?

**Comment by simonrw** [comment]
I will close this issue as resolved for now, but if you experience problems please open another issue with a specific example that doesn't work.

**Comment by charleswong28** [comment]
@simonrw  Do we have any plan for the functionality of `util.error` and `util.http`?
