### ISSUE TITLE
Requests To localhost.localstack.cloud Can Be Blocked By Router DNS Configuration

### ISSUE THREAD

**Issue by adase11** [localstack/localstack#8625]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

My team noticed browser errors of `DNS_PROBE_FINISHED_NXDOMAIN` when using as the host name `localhost.localstack.cloud` for the localstack service. This made us unable to use the browser to connect to localstack services (for example when using presigned S3 URLs).

In our situation:
- Navigating using the IP address worked fine (i.e. `http://127.0.0.1:4566/health`)
- Navigating using the domain name resulted in the above error (i.e. `https://localhost.localstack.cloud:4566/health` )

We were able to pinpoint the issue to local network router configurations, specifically for those where the domain name was not working, their home network router included enabled DNS Rebind Protection. We were able to confirm that this DNS Rebind Protection was the source of the problems by adding in an exception record for loopback addresses (`127.0.0.0/8`) and then observing the domain name start to work again.

Preferring not to change router settings we settled on adding an entry in our host file (`/etc/hosts`) for `localhost.localstack.cloud` which also resolves the issue.

I don't have any suggestions for a fix but I thought this might be helpful for anyone that comes along with a similar issue.

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    LOCALSTACK_HOSTNAME=localhost.localstack.cloud localstack start -d

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    https://localhost.localstack.cloud:4566/health

### Environment

```markdown
- OS: MacOS
- LocalStack: 2.0.1
```

**Comment by dfangl** [comment]
Thank you for reaching out.
We are indeed aware of this issue, we have a section in our documentation for it: https://docs.localstack.cloud/user-guide/tools/transparent-endpoint-injection/dns-server/#dns-rebind-protection

As you said - there is not much to work with here. One of the solutions is to use our internal DNS server (Pro feature) where possible, which will take care of the DNS resolution of this name.

As this is documented behavior, I will close this for now. We are continuously working on improving the addressing of LocalStack, but for now this is an expected limitation.

**Comment by adase11** [comment]
Ah thanks, apologies I missed that in the documentation.
