### ISSUE TITLE
bug: The route53 CreateHostedZone endpoint misses the Location header in the response

### ISSUE THREAD

**Issue by stof** [localstack/localstack#8652]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When creating a route53 hosted zone, the location is not returned as a header in the response

### Expected Behavior

The response should match the AWS one

### How are you starting LocalStack?

With a `docker run` command

### Steps To Reproduce

See https://github.com/localstack/localstack/pull/5639#issuecomment-1064527918 for the report at the time route53 was migrated to use moto as a comment on the PR.

### Anything else?

the issue has been fixed upstream in moto: https://github.com/getmoto/moto/issues/6464 and https://github.com/getmoto/moto/pull/6492

So hopefully, updating moto should be enough to fix this

**Comment by stof** [comment]
In 2.3.2, the header is present thanks to the fix done in moto. But the URL uses `route53.amazonaws.com` as domain instead of the localstack domain.

**Comment by giograno** [comment]
Hey @stof, that's correct. LocalStack returns now a `Location` thanks to `moto`. Would you need a different URL for any particular use case?

**Comment by stof** [comment]
My own use case being to run the tests of a SDK does not care about the exact content of the URL. It only cares about required fields being provided.
However, if possible, it would be nice if localstack could rewrite the URL in the header to use the localstack host instead of the AWS one.

**Comment by giograno** [comment]
Thanks for the clarification @stof! Out of curiosity, do you have any particular use case in mind for the localstack host instead of the AWS one?

**Comment by giograno** [comment]
I am closing this issue since the Location header is now returned in the response. Feel free to open a new issue for further requirements. Thank you 🙏
