### ISSUE TITLE
bug: Setting a bucket lifecycle fails

### ISSUE THREAD

**Issue by octogene** [localstack/localstack#8662]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When trying to add a lifecycle to a bucket with the following command : 
`awslocal s3api put-bucket-lifecycle-configuration --bucket test-bucket --lifecycle-configuration file:///tmp/localstack/s3-lifecycle.json`

I get this error :
```
localstack       | 2023-07-10T11:48:41.260  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS s3.PutBucketLifecycleConfiguration => 400 (MalformedXML)
localstack       | 
localstack       | An error occurred (MalformedXML) when calling the PutBucketLifecycleConfiguration operation: The XML you provided was not well-formed or did not validate against our published schema
localstack       | 
localstack       | 2023-07-10T11:48:41.313 ERROR --- [  MainThread] localstack.runtime.init    : Error while running script Script(path='/etc/localstack/init/ready.d/init-aws.sh', stage=READY, state=ERROR)
localstack       | Traceback (most recent call last):
localstack       |   File "/opt/code/localstack/localstack/runtime/init.py", line 136, in run_stage
localstack       |     runner.run(script.path)
localstack       |   File "/opt/code/localstack/localstack/runtime/init.py", line 71, in run
localstack       |     raise OSError("Script %s returned a non-zero exit code %s" % (path, exit_code))
localstack       | OSError: Script /etc/localstack/init/ready.d/init-aws.sh returned a non-zero exit code 255
```

### Expected Behavior

Lifecycle should be added to the bucket which is the current behavior on 2.1.0

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal s3api put-bucket-lifecycle-configuration --bucket test-bucket --lifecycle-configuration file:///tmp/localstack/s3-lifecycle.json

#### Example lifecycle file 

```
{
    "Rules": [
        {
            "ID": "id-0",
            "Status": "Enabled",
            "Expiration": {
                "Days": 2
            }

        },
        {
            "ID": "id-1",
            "Prefix": "customer/",
            "Filter": {
                "Prefix": "customer/"
            }, 
            "Status": "Enabled", 
            "Expiration": {
                "Days": 7
            }
        },
        {
            "ID": "id-2",
            "Prefix": "admin/",
            "Filter": {
                "Prefix": "admin/"
            },
            "Status": "Enabled",
            "Expiration": {
                "Days": 1
            }
        }
    ]
}
```

### Environment

```markdown
- OS: OpenSUSE Tumbleweed
- LocalStack: latest
```

### Anything else?

This is maybe in relation with #6654 changes.

**Comment by bentsku** [comment]
Hi @octogene and thanks for your report. It seems this can be a regression from 

It seems the lifecycle does not follow the format from a `PutBucketLifecycleConfiguration` but instead `PutLifecycleConfiguration`, which is the deprecated one. I'll give it a try against AWS to see if that works, and if it does, I'll modify the validation to follow AWS.

**Comment by octogene** [comment]
I can add that if i remove the first rule ("id-0") it correctly adds the rules.

**Comment by bentsku** [comment]
Does that work against AWS?

**Comment by bentsku** [comment]
I just tried it against AWS and the same error is returned:

```bash
$ aws s3api put-bucket-lifecycle-configuration --bucket mybuckettest100723 --lifecycle-configuration file:///tmp/localstack/s3-lifecycle.json

An error occurred (MalformedXML) when calling the PutBucketLifecycleConfiguration operation: The XML you provided was not well-formed or did not validate against our published schema
```

So it seems we're in line with AWS now

**Comment by octogene** [comment]
Ok my bad, sorry for the inconvenience. Closing the issue.

**Comment by bentsku** [comment]
No problem, thanks a lot for reporting in the first case, AWS validation can be tricky and it's good we're aware of potential regressions, which I'm sure we can have from the new lifecycle PR. Glad your issue is resolved!
