### ISSUE TITLE
bug: S3 presigned url mismatch on key with equals sign in them

### ISSUE THREAD

**Issue by krisgeus** [localstack/localstack#8663]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have a test setup using localstack and delta-sharing docker containers where delta-sharing is generating pre-signed urls which are used to retrieve the files form s3.
When bumping to the latest localstack this started to fail with a signature mismatch error on specific keys 

I have created a small setup to test this. See attached files
[README.md](https://github.com/localstack/localstack/files/12001909/README.md)
[test-file-and-code.zip](https://github.com/localstack/localstack/files/12001924/test-file-and-code.zip)

### Expected Behavior

Localstack encoding the key before generating the signature like all other methods do

### How are you starting LocalStack?

Custom (please describe below)

### Steps To Reproduce

See attached files

### Environment

```markdown
- OS: MacOSX
- LocalStack: 2.1.0
```

**Comment by bentsku** [comment]
Hello @krisgeus and thanks for your report.

Generating pre-signed URL is purely a client side operation, and LocalStack doesn't have anything to do with that. I'm not sure I follow the code that is attached.

This code only shows the generation of the pre-signed URL, is that right? And depending on the client used, they will differ?
Or is that to show that a specific part in our code does not work?

**Comment by bentsku** [comment]
I'm currently writing tests for the specific use case and will come back to you with a fix soon! I can see the issue with the signature not matching now. Thanks again for the report!

**Comment by krisgeus** [comment]
@bentsku Thx. Indeed the checking of the signature is what is reporting a wrong signature. The attached code was to demonstrate the different methods used by Minio, Awscli and localstack. I copied the relevant parts from each of the libraries to show the difference.
Thx for looking into it and creating a testcase (and possible fix). Let me know if you want me to verfiy or help out in any way.

**Comment by bentsku** [comment]
Hi @krisgeus, thanks for trying out the PR already and confirming that it fixed your issue!

The image is now ready and available under the `localstack/localstack:latest` tag. We will have a new tagged release (`2.2`) next Thursday, which will include this fix. Thank you again for the sample to reproduce!
