### ISSUE TITLE
bug: Terraform Remote State Not Working

### ISSUE THREAD

**Issue by FarhanSajid1** [localstack/localstack#8665]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Create a module, store some remote state at s3 bucket terraform-state, and key key-exists.
Then try to reference this state

```
data "terraform_remote_state" "key_state" {

  backend = "s3"

  config = {
    bucket = "terraform-state"
    key    = "key-exists"
    region = "us-east-1"
  }
}
```

```
$ tflocal plan
╷
│ Error: AuthorizationHeaderMalformed: The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'eu-central-1'
│       status code: 400, request id: ZSNQ47CFQ2K0VWK4, host id: NKpL0rpMy8jthfG3qZUdBAwsXoGNFIRQFfjQXPuDopCkJgXYHIyGNyBSkgIymynsHkYSNfq5CCY=
│ 

```

### Expected Behavior

The state works properly

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal s3 mb s3://mybucket

### Environment

```markdown
- OS:
- LocalStack:
```

**Comment by bentsku** [comment]
Hi @FarhanSajid1 and thanks for your report! It seems you also opened the issue in the concerned repository here: https://github.com/localstack/terraform-local/issues/19, so I'll close this issue as duplicate. Thanks again for the report, we will continue the discussion on the other issue.
