### ISSUE TITLE
enhancement request: make moto server port configurable

### ISSUE THREAD

**Issue by jgao54** [localstack/localstack#8666]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Enhancement description

The moto server port by default [just looks for any free tcp port](https://github.com/localstack/localstack/blob/9c6e4a7ac03579d61721c1fb1d385747e502c683/localstack/services/motoserver.py#L38). It would be great to support a`MOTO_PORT` environment variable similar to `motoserver/moto` image [[ref](https://docs.getmoto.org/en/latest/docs/server_mode.html#run-using-docker)], or make the [`blocklist` arg](https://github.com/localstack/localstack/blob/9c6e4a7ac03579d61721c1fb1d385747e502c683/localstack/utils/net.py#L177) configurable via environment variable. I am running localstack with docker-compose and have a dependent container that relies on a static port assignment, but occasionally moto server will use it and generate a port conflict.

**Comment by bentsku** [comment]
Hello @jgao54 and thank you for your report.

Could I ask which version of LocalStack are you using? Since 2.0, our new implementation of S3 doesn't depend on `motoserver` and does not start it anymore. Maybe that could solve your issue as well? As we don't currently support older versions of LocalStack.

**Comment by jgao54** [comment]
Ah, we are currently on a very legacy version of localstack (0.13.3), will look into upgrading. thanks for the pointer!

**Comment by bentsku** [comment]
No problem, feel free to reach out if you need any help during upgrade, and if you encounter any issue.
We have those 2 guides, to migrate to `v1` then `v2`. 

- https://discuss.localstack.cloud/t/migrating-to-localstack-v1-0/58
- https://discuss.localstack.cloud/t/upcoming-changes-for-localstack-v2/239

Hope that will help!
