### ISSUE TITLE
CORS policy problem with AWS SES 

### ISSUE THREAD

**Issue by GabrieleT0** [localstack/localstack#8673]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi! I'm developing a small project and I'm using localstack community edition. I found a problem with the SES service. In particular, I want to create a personal dashboard for email sendend (by using the data that are returned throught this API endpoint offered by default from localstack: https://docs.localstack.cloud/user-guide/aws/ses/#sent-emails). 
I have the following problem, seems that in the response there isn't the 'Access-Control-Allow-Origin' in the header, so I can get data for example with curl, but from browser I get this error:

`Access to XMLHttpRequest at 'http://localhost:4566/_aws/ses' from origin 'http://localhost' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

In the docker-compose.yml I have also inserted this option - EXTRA_CORS_ALLOWED_ORIGINS=http://localhost

Is there a way to quick fix this?

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

For reproduce this,  first verify the email: `aws ses verify-email-identity --email-address example@example.com --endpoint-url http://localhost:4566`
Then try to send an email:
```
aws ses send-email \
    --from example@example.com \
    --message 'Body={Text={Data="Lorem ipsum dolor sit amet, consectetur adipiscing elit, ..."}},Subject={Data=Test Email}' \
    --destination 'ToAddresses=recipient1@example.com'
    --endpoint-url http://localhost:4566
```

Then is needed a simple piece of javscript code to fetch the data.

```
async function getData(){
    const response = await fetch("http://localhost:4566/_aws/ses")
    const jsonData = await response.json();

    return jsonData
}
```

### Environment

```markdown
- OS: Windows 11
- LocalStack: latest
```

**Comment by viren-nadkarni** [comment]
Hi @GabrieleT0, https://github.com/localstack/localstack/pull/8746 should have fixed this issue. Could you please try the `latest` image and let us know if the issue persists?

**Comment by GabrieleT0** [comment]
> Hi @GabrieleT0, #8746 should have fixed this issue. Could you please try the `latest` image and let us know if the issue persists?

Yes, now works. Thank you so much!
