### ISSUE TITLE
bug: EFS file system is not mounting with ECS container/task and local host both with Pro version

### ISSUE THREAD

**Issue by ashishhunka** [localstack/localstack#8678]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

EFS file system is not mounting/attaching to ECS container/task and local host
![efs-error](https://github.com/localstack/localstack/assets/57860870/51844bab-16c7-418f-bdc4-74bc7456f47f)

### Expected Behavior

EFS file system must be mount to ECS container/task and local host

### How are you starting LocalStack?

Custom (please describe below)

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    DEBUG=1  LOCALSTACK_API_KEY=XXXXXXXXXX localstack start

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

   Run attached terraform script
[ecs-efs.tf.txt](https://github.com/localstack/localstack/files/12016462/ecs-efs.tf.txt)

### Environment

```markdown
- OS: Amazon Linux
- LocalStack: Pro latest
```

**Comment by whummer** [comment]
Hi @ashishhunka , thanks for reporting, and apologies for the delay on this one. We have now added a couple of enhancements to the EFS service, including support for the `CreateMountTarget` API (among others). 

When you get a chance, can you please pull the `latest` Docker image and give it another try? Please keep us posted on how it goes - thanks for your help!
