### ISSUE TITLE
enhancement request: Use Kinesis Mock JS Distribution

### ISSUE THREAD

**Issue by etspaceman** [localstack/localstack#8680]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Enhancement description

Kinesis Mock is preparing a switch to a Javascript executable offering, which will remove the old GraalVM executables. This should be much easier to work with from Localstack's perspective, as well as remove the java dependency for users. But I'm unsure as to how to approach this in Localstack's code base, and am looking for some guidance / direction.

The current plan is to have 2 GitHub release assets:
- main.js
- main.js.map

To start the service, you'd simply do `./main.js`, as it should be an executable. You can use `node main.js` as well. 

I also plan to publish this to NPM if that is an easier grab for localstack. 

References:

https://github.com/etspaceman/kinesis-mock/pull/531
https://github.com/etspaceman/kinesis-mock/blob/scalajs/docker/Dockerfile

### 🧑‍💻 Implementation

Update these lines to execute a nodejs command instead:

https://github.com/localstack/localstack/blob/master/localstack/services/kinesis/kinesis_mock_server.py#L101

Upgrade this to the newest version (planning for 0.4.0):

https://github.com/localstack/localstack/blob/master/localstack/services/kinesis/kinesis_mock_server.py#L101

Update this to get the `main.js` file for all platforms:

https://github.com/localstack/localstack/blob/master/localstack/services/kinesis/kinesis_mock_server.py#L101

**Comment by etspaceman** [comment]
Any thoughts on this @whummer or @alexrashed any thoughts on this one?

**Comment by alexrashed** [comment]
Hi @etspaceman!
Thanks a lot for the heads-up! 🚀 You already analyzed the changes which would be necessary quite well, I think it should just be a few lines of code (in the package installer and the server implementation).

> To start the service, you'd simply do ./main.js, as it should be an executable.

You would sill need a node runtime to execute it, right?
We currently already have NodeJS 18 in the Docker images installed, but to be honest, we were thinking about removing it at some point (we only use it for very few services now).
The static builds were actually pretty awesome, may I ask why you are moving towards ScalaJS? In your PR you mention that there were issues with Apple Silicon, but we haven't really seen any reports such alike...

**Comment by etspaceman** [comment]
> You would sill need a node runtime to execute it, right?

Correct.

> The static builds were actually pretty awesome, may I ask why you are moving towards ScalaJS? In your PR you mention that there were issues with Apple Silicon, but we haven't really seen any reports such alike...

M1 users could not use the static builds as there was no good way of generating that with github actions. They had to fallback to a fat-jar. I had 2 docker images generated as a result; one that used a linux static image, and the other that used a fat-jar. 

I could certainly go back to the static approaches with Graal. But Graal in particular is very difficult to maintain across the respective platforms. There's a lot of overhead in generating them, and it slows build times pretty horrendously as a result. It is also very sensitive to which java version is used in a project. NodeJS is much easier with that in mind, as all platforms can easily install NodeJS versions. 

There is an interesting other alternative with scala-native, which would require an LLVM environment. But I'm not sure that we want to introduce that requirement to users. NodeJS was already in use so it seemed like a good option with that in mind. 

Let me know what you're thinking.

**Comment by etspaceman** [comment]
Another option could be to build self-contained binaries from the NodeJS application as well via something like this:

https://github.com/vercel/pkg

But like Graal/Native, this can be challenging for multiple platforms.

**Comment by alexrashed** [comment]
I see. We have similar issues concerning the lack of M1 GHA runners with https://github.com/localstack/localstack-cli (we are hoping for the public availability according to their roadmap in Q4 - https://github.com/github/roadmap/issues/528).
In our community edition, we might remove NodeJS, but if it comes to that, vercel/pkg or other alternatives might help us there :)

**Comment by etspaceman** [comment]
Yeah, we could certainly introduce `pkg` if NodeJS gets removed. I feel like that's a reasonable 2nd step here. And I think `pkg` is a lot easier to work with in terms of x-platform, as I don't think I'd need a specific M1 runner to accomplish it.

**Comment by alexrashed** [comment]
Sounds like a plan. :)

**Comment by etspaceman** [comment]
@whummer In terms of timeline, I'm basically ready to go as soon as I'm unblocked by an upstream dependency change (which I suspect will be in the next few days). So I planned to release a new version as soon as that's done.

BTW - I am also planning to publish this to NPM. I know we have an issue with rate-limits to the kinesis assets in GitHub when starting Localstack, so maybe using NPM would help here? I'm not a big JS expert though, so I'll lean on you to suggest if that is a better pull for Localstack to make.

**Comment by etspaceman** [comment]
Published artifacts are available:

https://www.npmjs.com/package/kinesis-local
https://github.com/etspaceman/kinesis-mock/releases/tag/v0.4.1
https://github.com/etspaceman/kinesis-mock/pkgs/container/kinesis-mock/114529109?tag=0.4.1

**Comment by alexrashed** [comment]
Hi @etspaceman!
I'm currently drafting a PR to upgrade to the new version.
But I was stumbling across the TLS cert config: The new version seems to need a TLS cert keypair, while the previous one might have created them on demand. Is there a chance to disable setting the `server.json`, ship it with the package, or disable TLS in general (we are proxying all requests through LocalStack, accessing `kinesis-mock` via `localhost`)?

**Comment by etspaceman** [comment]
Ah hm. I'll look into that. I'd still like to be able to service TLS routes, so I'll see what I can do to fix that

**Comment by etspaceman** [comment]
Created https://github.com/etspaceman/kinesis-mock/pull/551 to hopefully resolve this issue.

**Comment by alexrashed** [comment]
@etspaceman #8790 upgrades to the latest version of `kinesis-mock`. The PR has been merged and the changes will be included in the next builds. Thanks again for the pro-active collaboration!
