### ISSUE TITLE
bug: latest image missing aspectjweaver-1.9.7.jar and version of StepFunctionsLocal.jar  not support --eventbridge-endpoint

### ISSUE THREAD

**Issue by rosscdh-tpg** [localstack/localstack#8682]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Thanks for this fantastic system 🙏 🙇 

currently not able to run step functions in docker-compose at all

notated in wrong repo: https://github.com/localstack/helm-charts/issues/5#issuecomment-1630267558

trying to run stepfunctions in latest `sha256:a92aac1f292a8a8c178b33887a0237e0ab668a31a926cbc9c9cbc28d1ac0ac3a`

the aspectjweaver-1.9.7.jar is completely absent in the image and StepFunctionsLocal.jar  does not support the event-bridge integration `Unrecognized option: --eventbridge-endpoint`

### Expected Behavior

step functions runs

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

docker-compose up

### Environment

```markdown
- OS: osx ventura 13.0
- LocalStack: 2.1.1.dev


version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    # user: "503"
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=1
      - LAMBDA_DOCKER_FLAGS='-p 19891:19891'
      - DOCKER_HOST=unix:///var/run/docker.sock
      - TZ=Australia/Sydney
      - GITHUB_API_TOKEN=$GITHUB_PERSONAL_TOKEN_CLASSIC_SSO
      - ALLOW_NONSTANDARD_REGIONS=1
      # - SKIP_SSL_CERT_DOWNLOAD=1
    volumes:
      - localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/tmp/localstack:/tmp/localstack"
volumes:
  localstack: {}
```
```


### Anything else?

load the image latest at sha256:a92aac1f292a8a8c178b33887a0237e0ab668a31a926cbc9c9cbc28d1ac0ac3a
and simply run

```
find /var -name "aspectjweaver*"
find / -name "StepFunction*"
```

**Comment by alexrashed** [comment]
Hi @rosscdh-tpg!
Actually, these libraries for stepfunctions are downloaded on demand.
If you are interested in the internals, this happens in the stepfunctions package installer:
https://github.com/localstack/localstack/blob/0abb4830714a5a9916b17b6d4a26cb10d6935e22/localstack/services/stepfunctions/packages.py

At runtime, this is downloaded into the var lib directory. It seems you are mounting the var libs directory from a volume. This avoids that the package is downloaded every single time the container starts up (which saves time and bandwidth, you can find [more information on that in our docs](https://docs.localstack.cloud/references/filesystem/)).
But maybe the var libs volume ended up in a corrupt state (when downloading it the first time). This way the installer will not be executed again, but it will also fail to run.
You should be able to fix that by removing the `localstack` volume.
Could you give this a try and tell us if this fixed your issue?
Thanks!

**Comment by rosscdh-tpg** [comment]
Thanks yep makes sense. Was being corrupted by network policies on this end! thanks for the info and amazing product.
