### ISSUE TITLE
I can not pull localstack-pro ....

### ISSUE THREAD

**Issue by aurelsandu** [localstack/localstack#8687]
Hello,
I would like to buy a subscription for this emulator for learning

I used the command   docker pull localstack/localstack-pro:latest  on my windows 11 laptop but command frozen .... no feedback ....... what is this?

Thanks,
Aurel

**Comment by ackdav** [comment]
Hello @aurelsandu!
Can you please check the following:
- Do you have a working internet connection?
- Maybe double check the documentation here: [https://docs.docker.com/engine/reference/commandline/pull/](https://docs.docker.com/engine/reference/commandline/pull/)
- Try again with `docker pull localstack/localstack-pro`

If that doesn't work, it would be helpful if we get a bit more information - what does the terminal say before it freezes?

Thanks

**Comment by aurelsandu** [comment]
Hello ,
Before buying the pro edition, I would like to see the community edition.
I created a venv and I installed localstack api  and I run localstack --version and I get 2.1.0 , correct
Then I try to run localstack start -d (to lunch the emulator) but I  get a error (I attach the error)

![Screenshot 2023-07-13 094829](https://github.com/localstack/localstack/assets/12221112/5be40a58-b6e5-4f22-8310-8af604afb927)


Best regards,
Aurel

**Comment by aurelsandu** [comment]
I closed by mistake ...

**Comment by dfangl** [comment]
Hi, your screenshot is truncated at the end. Could you please try to send us the complete error message?
