### ISSUE TITLE
bug: EC2 user data not processed correctly if multipart-mime

### ISSUE THREAD

**Issue by srstrong** [localstack/localstack#8693]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Creating an instance through run-instances and specifying a multipart-mime file for the user-data causes the cloud-init process to fail.  From the local stack logs when `DEBUG=1`, you can see:

```
l.u.c.docker_sdk_client    : Executing command in container localstack-ec2.i-50e26b87d95bdd37d: ['sh', '-c', '/var/lib/cloud/instances/i-50e26b87d95bdd37d/user-data.txt 2>&1 | tee --append /var/log/cloud-init-output.log']
```

this would only work if user-data.txt is just a shell script, however if it is a multipart-mime file, as supported by AWS, then the attempt to just run it with `sh` will not work

### Expected Behavior

multipart-mime files are processed in accordance with the AWS documentation

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    localstack start

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal ec2 run-instances --image-id 'ami-00a002' --user-data file://mime.txt

where mime.txt is

```
Content-Type: multipart/mixed; boundary=//
MIME-Version: 1.0

--//
Content-Type: text/x-shellscript; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Content-Disposition: attachment; filename="userdata.txt"

#!/bin/bash
echo Hi > /tmp/out

--//
```

### Environment

```markdown
- OS: Ubuntu 22.04
- LocalStack: latest pro
```

**Comment by pandomic** [comment]
HI @srstrong, wanted to let you know we are working on the issue and the fix will likely be included in the next patch or minor release
