### ISSUE TITLE
API Gateway post requests do not accept content-type application/x-www-form-urlencoded

### ISSUE THREAD

**Issue by mcuervoe** [localstack/localstack#871]
I trying to call an API Gateway endpoint using a post request where the body is coded as application/x-www-form-urlencoded. I set correctly the content-type but nevertheless localstack refurse to process the request and produces the following exception:

> 2018-07-28T19:08:48:ERROR:localstack.services.generic_proxy: Error forwarding request: No JSON object could be decoded Traceback (most recent call last):
>   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 181, in forward
>    path=path, data=data, headers=forward_headers)
>   File "/opt/code/localstack/localstack/services/apigateway/apigateway_listener.py", line 158, in forward_request
>      data = data and json.loads(to_str(data))
>    File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
>      return _default_decoder.decode(s)
>    File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
>      obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>    File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
>      raise ValueError("No JSON object could be decoded")
>  ValueError: No JSON object could be decoded
> 
> 

The same request works fine if I point it to AWS. It looks like localstack only is only acepting a json payload

**Comment by redigaffi** [comment]
I'm also unable to post to a API Gateway endpoint using "application/x-www-form-urlencoded" encoded data.

**Comment by whummer** [comment]
Thanks for reporting @mcuervoe @redigaffi . This should be fixed in #1796 - can you please give it a try with the `latest` version of the Docker image. Please re-open this issue if the problem persists. Thanks
