### ISSUE TITLE
bug:  Aurora DB Cluster, not creating read endpoints using localstack-pro version

### ISSUE THREAD

**Issue by Pankajjain-sentryc** [localstack/localstack#8715]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

 I have created Aurora DB Cluster using localstack-pro with following command but Read nodes/endpoints are not created in Aurora DB cluster (Postgres). Please suggest.
command : awslocal rds create-db-cluster --db-cluster-identifier db1 --engine aurora-postgresql --database-name test
response :
 "DBCluster": {
    "AllocatedStorage": 1,
    "DatabaseName": "test",
    "DBClusterIdentifier": "db1",
    "DBClusterParameterGroup": "default.aurora-postgresql",
    "Status": "creating",
    "Endpoint": "localhost:4510",
    "MultiAZ": false,
    "Engine": "aurora-postgresql",
    "Port": 4510,
    "MasterUsername": "test",
    "DBClusterMembers": [],
    "VpcSecurityGroups": [
      {
        "VpcSecurityGroupId": "sg-bff138665b79bb420",
        "Status": "active"
      }
    ],
    "StorageEncrypted": false,
    "DBClusterArn": "arn:aws:rds:us-east-1:000000000000:cluster:db1",
    "IAMDatabaseAuthenticationEnabled": false,
    "TagList": []
  }
}
I tried the below commands but could not find the Read nodes/endpoints.
awslocal rds describe-db-instances
awslocal rds describe-db-cluster-endpoints

### Expected Behavior

It should create read endpoints as it is created by AWS CLI

AWS ouput 
{
    "DBCluster": {
        "Endpoint": "sample-pg-cluster.cluster-cnpexample.us-east-1.rds.amazonaws.com",
        "HttpEndpointEnabled": false,
        "DBClusterMembers": [],
        "EngineMode": "provisioned",
        "CopyTagsToSnapshot": false,
        "HostedZoneId": "Z2R2ITUGPM61AM",
        "IAMDatabaseAuthenticationEnabled": false,
        "AllocatedStorage": 1,
        "VpcSecurityGroups": [
            {
                "VpcSecurityGroupId": "sg-0b9130572daf3dc16",
                "Status": "active"
            }
        ],
        "DeletionProtection": false,
        "StorageEncrypted": false,
        "BackupRetentionPeriod": 1,
        "PreferredBackupWindow": "09:56-10:26",
        "ClusterCreateTime": "2023-02-27T23:26:08.371Z",
        "DBClusterParameterGroup": "default.aurora-postgresql13",
        "EngineVersion": "13.7",
        "Engine": "aurora-postgresql",
        "Status": "creating",
        "DBClusterIdentifier": "sample-pg-cluster",
        "MultiAZ": false,
        "Port": 5432,
        "DBClusterArn": "arn:aws:rds:us-east-1:123456789012:cluster:sample-pg-cluster",
        "AssociatedRoles": [],
        "DbClusterResourceId": "cluster-ANPAJ4AE5446DAEXAMPLE",
        "PreferredMaintenanceWindow": "wed:03:33-wed:04:03",
    "**ReaderEndpoint**": "sample-pg-cluster.cluster-ro-cnpexample.us-east-1.rds.amazonaws.com",
        "MasterUsername": "master",
        "AvailabilityZones": [
            "us-east-1a",
            "us-east-1b",
            "us-east-1c"
        ],
        "ReadReplicaIdentifiers": [],
        "DBSubnetGroup": "default"
    }
}

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack-pro

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

   awslocal rds create-db-cluster --db-cluster-identifier db1 --engine aurora-postgresql --database-name test

### Environment

```markdown
- OS:
- LocalStack:
```

**Comment by steffyP** [comment]
Hi @Pankajjain-sentryc,

thanks for reporting!
The aws-cli command you are using to create the rds cluster, indicates that you create a serverless v2 cluster. 

[Reading into the docs](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/Aurora.CreateInstance.html#heading34-1689682957031-2753) it states that you have to manually create an instance in that case:

> If you use the console to create a DB cluster, then Amazon RDS automatically creates the primary instance (writer) for your DB cluster. If you use the AWS CLI to create a DB cluster, you must explicitly create the primary instance for your DB cluster. The primary instance is the first instance that is created in a DB cluster. Until you create the primary DB instance, the DB cluster endpoints remain in the Creating status.

However, I agree that LocalStack deviates from the responses that you see from LocalStack, mainly:
 * missing the `ReaderEndpoint` field from the `describe-db-clusters`
 * not showing the endpoints for `describe-db-cluster-endpoints`

Adding here the main parts for future reference (I ran this against AWS using ` aws rds create-db-cluster --db-cluster-identifier db1 --engine aurora-postgresql --database-name test --master-username test --master-user-password $PASSWD`):
```
$ aws rds describe-db-clusters
{
    "DBClusters": [
        {
            "AllocatedStorage": 1,
            "AvailabilityZones": [
                "us-east-1c",
                "us-east-1b",
                "us-east-1d"
            ],
            "DatabaseName": "test",
            "DBClusterIdentifier": "db1",
             ....
            "Status": "available",
            "EarliestRestorableTime": "2023-07-18T12:18:27.383Z",
            "Endpoint": "db1.cluster-cv7ssqk8cl0y.us-east-1.rds.amazonaws.com",
            "ReaderEndpoint": "db1.cluster-ro-cv7ssqk8cl0y.us-east-1.rds.amazonaws.com",
            "MultiAZ": false,
            "Engine": "aurora-postgresql",
            "EngineVersion": "14.6",
            ....
        }
    ]
}

---
$ aws rds describe-db-instances
{
    "DBInstances": []
}
---

$ aws rds describe-db-cluster-endpoints
{
    "DBClusterEndpoints": [
        {
            "DBClusterIdentifier": "db1",
            "Endpoint": "db1.cluster-cv7ssqk8cl0y.us-east-1.rds.amazonaws.com",
            "Status": "creating",
            "EndpointType": "WRITER"
        },
        {
            "DBClusterIdentifier": "db1",
            "Endpoint": "db1.cluster-ro-cv7ssqk8cl0y.us-east-1.rds.amazonaws.com",
            "Status": "creating",
            "EndpointType": "READER"
        }
    ]
}
```

As LocalStack is mocking the clusters, i.e. there is only one database running in the background, the `ReaderEndpoint` would also point to the same address as `Endpoint`. 
To make up the parity, we would therefore add the property `ReaderEndpoint` to the `describe-db-clusters` response, and make sure the `describe-db-cluster-endpoints` returns a similar result. 

Hope that solution would work for you, happy to get your feedback!

**Comment by Pankajjain-sentryc** [comment]
Hi Team,

Thanks for your quick response. When can we expect "ReaderEndpoint" in the response. Can we get it also in the create-cluster response.

Thanks
Pankaj Jain

________________________________

**Comment by steffyP** [comment]
Hi @Pankajjain-sentryc,

sorry for the delayed response. We released a fix for the reported issue, which is available for the `latest` image. 
The `ReaderEndpoint` has been added to the `describe-db-cluster` response, and we verified the returned endpoints for the `describe-db-cluster-endpoints` responses. 
Please pull `localstack/localstack-pro:latest` and let us know if the returned responses now work as you expected. 🙏
