### ISSUE TITLE
How to use Kinesis Firehose and ElasticSearch?

### ISSUE THREAD

**Issue by veqryn** [localstack/localstack#873]
I have a production application that is sending data to AWS Kinesis Firehose, which then forwards it onward to AWS ElasticSearch Service, where it is then read.

I would like to be able to use and test my application in development on my laptop, and also be able to run application integration tests in my CI/CD environment.

Localstack looks like it would fit this use case perfectly, however I am a bit stumped on how to start and there doesn't seem to be much in the way of tutorials or docs.

Assuming I am using your localstack docker container, do I need to run AWS CLI commands against it in order to create and configure Firehose and ElasticSearch?

My production and test environments in AWS are created by Terraform, and ideally I would use a version of this to configure localstack.  Is that possible?

If not, is there a way to have localstack automatically start with the configuration I want, that way when the docker container comes up it configures itself and is ready to go?

What is the suggested way to start up and configure a localstack container in an automated environment like jenkins/travis or other CI?

**Comment by veqryn** [comment]
@whummer Can you help please?

**Comment by rayjlinden** [comment]
I want to do the same thing.  Is this possible?

**Comment by Gurkaran1120** [comment]
Yes, you can totally do that! I think you might have figured it out but if not then:
1) You would have to use a credentials object with accesskeyId and secretaccesskey with default values to something random string remember not empty.
const credentials = {
  accessKeyId: 'random;,
  secretAccessKey:'random',
};

and then later while using the aws you could do something like:
const s3 = new AWS.S3({
  credentials,
  endpoint: 'S3 localstack endpoint',
};

More info for how to configure localstack can be found here: https://github.com/localstack/localstack

Hope that helps!

**Comment by whummer** [comment]
Thanks for providing these details @Gurkaran1120 !

> My production and test environments in AWS are created by Terraform, and ideally I would use a version of this to configure localstack. Is that possible?

@veqryn @rayjlinden  This simple sample project could be a good starting point if you want to use Terraform against LocalStack: https://github.com/localstack/localstack-pro-samples/tree/master/terraform-resources

Closing this issue as resolved, but please feel free to open follow-up issues with any specific requests. Thanks
