### ISSUE TITLE
bug: localstack config validate: `Errno 2 no such file or directory: 'docker-compose'`

### ISSUE THREAD

**Issue by noahehall** [localstack/localstack#8732]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

- following the [installation steps](https://docs.localstack.cloud/getting-started/installation/) fails when validating localstack configuration

- error
![image](https://github.com/localstack/localstack/assets/10324554/d82ef62e-c8b8-402e-8195-e691733cfeb1)

- localstack is indeed running
![image](https://github.com/localstack/localstack/assets/10324554/44d7180a-5090-416d-afa9-c4eaaedca33e)

### Expected Behavior

- localstack can consume the path I pass `--file`

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker compose up -d
    localstack config validate --file ./compose.yaml

### Environment

```markdown
OS: Ubuntu 20.04
    LocalStack: latest
```

### Anything else?

- you can reproduce [on this branch](https://github.com/noahehall/localstack/tree/rds) if it still exists
  - else switch to the develop branch

**Comment by dfangl** [comment]
Hi @noahehall !
You are right. Currently, the CLI uses `docker-compose` to validate the config. On some systems with newer docker compose versions (>2), there is no alias from `docker-compose` to `docker compose`, which leads to this error.

We will fix this in the next version of the `localstack` CLI.

**Comment by noahehall** [comment]
@dfangl thanks for the update!
