### ISSUE TITLE
bug: localstack container potentially doesnt consume $AWS_ENDPOINT_URL env var

### ISSUE THREAD

**Issue by noahehall** [localstack/localstack#8735]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm unsure if this is an AWS-CLI issue or a localstack container issue

if I create a named profile for localstack and set the endpoint_url in the config, all aws-cli commands return errors

please see this ticket in aws/aws-cli: https://github.com/aws/aws-cli/issues/8052

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker compose up -d

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

   all aws cmds fail when using the $ENDPOINT_URL env var

### Environment

```markdown
OS: Ubuntu 20.04
    LocalStack: latest
```

**Comment by alexrashed** [comment]
Hi @noahehall!
You already closed the linked issue (https://github.com/aws/aws-cli/issues/8052).
Does this mean your issue has been resolved?
Thanks!
