### ISSUE TITLE
[Question] How to read data from SNS `platformEndpoint`  ?

### ISSUE THREAD

**Issue by slawalata** [localstack/localstack#874]
i know that we can subscribe a Sns topic to Sqs Queue.
```
String queueUrl = amazonSQS.createQueue("test-queue").getQueueUrl();

CreateTopicResult topicOne = amazonSNS.createTopic("topicOne");

amazonSNS.subscribe(topicOne.getTopicArn(), "sqs", queueUrl);

amazonSNS.publish(topicOne.getTopicArn(), "test send to topic one");

ReceiveMessageResult receiveMessageResult = amazonSQS
               .receiveMessage(
                        new ReceiveMessageRequest(queueUrl)
                                .withMaxNumberOfMessages(1)
                                .withWaitTimeSeconds(5)
                );
```
but i cant subscribe a Sns either _platformApplicationArn_ or `platformEndpointArn`  to a Sqs queue.

it returns `com.amazonaws.services.sns.model.AmazonSNSException: null (Service: AmazonSNS; Status Code: 404; Error Code: 404 Not Found; Request ID: null)`

or more general, is there any way to read data pushed to _sns' platformEndpoint_ ?

thank you,

**Comment by bsideup** [comment]
It seems that moto it storing the messages it receives:
https://github.com/mvantellingen/moto/blob/34c711189f4961eeee6a5de32e8106ec0bdb48bf/moto/sns/models.py#L160

Would be nice to be able to get them back

**Comment by joseluisdiaz** [comment]
Looks like localstack isn't forwarding _SNS_ messages to moto. Moto has an [api]( https://github.com/spulec/moto/blob/master/docs/docs/moto_apis.rst) to check for the state of the model. When starting as localstack is starting (using directly a service name) does not route the HTTP request to the proper service (`moto-api`) sended a few days ago a [PR[(https://github.com/spulec/moto/pull/1806) to solve that.

I'm using that api to retrieve messages in moto.

**Comment by palmithor** [comment]
There hasn't been any discussion on this for quite a while now - I am very interested in being able to automate my push notification tests and being able to somehow verify via platform endpoint published messages via LocalStack would be very beneficial! (Guess I am not the only one...)

**Comment by whummer** [comment]
Thanks for reporting @slawalata @bsideup @palmithor @joseluisdiaz . This is a fairly old request, but just to let you know that this has now been added in #2818 . This feature should be available in the `latest` image on Docker Hub. Please report here if the problem persists. Thanks

**Comment by gregplaysguitar** [comment]
@whummer I'm trying to subscribe a queue to a platform application in localstack, and getting the 404 saying the topic arn doesn't exist, for both the platform and endpoint arns. Is there a trick to this?
