### ISSUE TITLE
bug: dynamodbstreams: list_streams ignores the table name

### ISSUE THREAD

**Issue by bram-tv** [localstack/localstack#8759]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The dynamodbstreams list-streams operation ignores the `table-name` parameter and instead returns the streams of all the tables.

### Expected Behavior

The `table-name` parameter is not ignored and only the stream enabled for that table (if any) are retruned similar to the AWS implementation.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

##### Create tables

```
$ ./awslocal dynamodb create-table --table-name 'table1' --attribute-definitions 'AttributeName=pk,AttributeType=S' 'AttributeName=sk,AttributeType=S' --key-schema 'AttributeName=pk,KeyType=HASH' 'AttributeName=sk,KeyType=RANGE'  --billing-mode PAY_PER_REQUEST
(...)
$ ./awslocal dynamodb create-table --table-name 'table2' --attribute-definitions 'AttributeName=pk,AttributeType=S' 'AttributeName=sk,AttributeType=S' --key-schema 'AttributeName=pk,KeyType=HASH' 'AttributeName=sk,KeyType=RANGE'  --billing-mode PAY_PER_REQUEST
(...)
```
##### List initial streams (i.e. no streams)

```
$ ./awslocal dynamodbstreams list-streams
{
    "Streams": []
}
$ ./awslocal dynamodbstreams list-streams --table-name=table1
{
    "Streams": []
}
$ ./awslocal dynamodbstreams list-streams --table-name=table2
{
    "Streams": []
}
```

##### Enable stream on table2

```
$ ./awslocal dynamodb update-table --table-name table2 --stream-specification '{"StreamEnabled": true, "StreamViewType": "NEW_AND_OLD_IMAGES"}'
(...)
```

##### List streams

```
$ ./awslocal dynamodbstreams list-streams
{
    "Streams": [
        {
            "StreamArn": "arn:aws:dynamodb:us-east-1:000000000000:table/table2/stream/2023-07-27T14:43:05.624",
            "TableName": "table2",
            "StreamLabel": "2023-07-27T14:43:05.624"
        }
    ]
}
$ ./awslocal dynamodbstreams list-streams --table-name=table1
{
    "Streams": [
        {
            "StreamArn": "arn:aws:dynamodb:us-east-1:000000000000:table/table2/stream/2023-07-27T14:43:05.624",
            "TableName": "table2",
            "StreamLabel": "2023-07-27T14:43:05.624"
        }
    ]
}
$ ./awslocal dynamodbstreams list-streams --table-name=table2
{
    "Streams": [
        {
            "StreamArn": "arn:aws:dynamodb:us-east-1:000000000000:table/table2/stream/2023-07-27T14:43:05.624",
            "TableName": "table2",
            "StreamLabel": "2023-07-27T14:43:05.624"
        }
    ]
}
```

The `./awslocal dynamodbstreams list-streams --table-name=table1` command retuned incorrect output. There is no stream enabled for that table. (Which is also obvious from the output: it references table2 not table1.)

Running the above commands on AWS results in a final state with:
```
$ aws dynamodbstreams list-streams
{
    "Streams": [
        {
            "StreamArn": "arn:aws:dynamodb:***:***:table/table2/stream/2023-07-27T14:37:31.593",
            "TableName": "table2",
            "StreamLabel": "2023-07-27T14:37:31.593"
        }
    ]
}
$ aws dynamodbstreams list-streams --table-name table1
{
    "Streams": []
}
$ aws dynamodbstreams list-streams --table-name table2
{
    "Streams": [
        {
            "StreamArn": "arn:aws:dynamodb:***:***:table/table2/stream/2023-07-27T14:37:31.593",
            "TableName": "table2",
            "StreamLabel": "2023-07-27T14:37:31.593"
        }
    ]
}
```

### Environment

```markdown
- OS: Debian
- LocalStack: 2.2.1.dev
  - LocalStack version: 2.2.1.dev
  - LocalStack build date: 2023-07-27
  - LocalStack build git hash: ea7f26b4
```

### Anything else?

Looking at the source: https://github.com/localstack/localstack/blob/ea7f26b470551fd75500d6e18262330990b6da66/localstack/services/dynamodbstreams/provider.py#L136

It has the `table_name` argument but it's not used..

**Note:** the arguments `limit` and `exclusive_start_stream_arn` also appear to be unused?

**Comment by ackdav** [comment]
Hello @bram-tv - thanks for this detailed report! I just merged a fix for this, but please be aware that it could take a few hours until this is available through our latest docker image.
