### ISSUE TITLE
Camel support with Localstack 

### ISSUE THREAD

**Issue by shweta2202** [localstack/localstack#876]
Hello, 
We use Apache Camel is all our applications for message routing. I'm looking into adopting local stack for local testing. I haven't been able to get localstack working with Camel as it expects the path in certain path format. 

The challenge that I'm facing at the moment is that, the camel routes are supposed to defined as: "aws-sqs:queuename.." but when I run localstack my queue endpoint is like: "http://localist:37010/queue/queuename".

Is it not possible to get it working with Camel? I couldn't find any working examples. 
Thanks!

**Comment by daviangelo** [comment]
Following the URI format, you can use the param "queueUrl" in the configuration options:
https://camel.apache.org/components/3.16.x/aws2-sqs-component.html#_component_option_queueUrl

Example: 
`aws-sqs://queuename?queueUrl=http://localhost:37010/queue/queuename`

I was facing the same problem.

Commenting just to help someone who lands here.
