### ISSUE TITLE
Please add 'cache-control' and 'x-requested-with' to CORS_ALLOWED_HEADERS

### ISSUE THREAD

**Issue by kitzilla** [localstack/localstack#877]
Hello,

I had trouble using Dropzone (https://www.dropzonejs.com/) with CORS-enabled S3 bucket on Localstack.

I have configured my mock S3 bucket as follows using Boto3
```
cors = resource.BucketCors('my-bucket')
cors.put(
  CORSConfiguration={
    'CORSRules': [
      {
        'AllowedHeaders': [ '*', ],
        'AllowedMethods': [ 'PUT', 'GET', 'POST', 'DELETE', 'HEAD', ],
        'AllowedOrigins': [ '*' ],
        'MaxAgeSeconds': 3000
      }
   ]
)
```
Then, I have made PUT requests the bucket using signed URL but they were blocked by browser. As firebug tells that
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:4572 (Reason: missing token 'cache-control' in CORS header 'Access-Control-Allow-Headers' from CORS preflight channel)
```

This was not the case when working with real S3 bucket (in eu-west-1). The real S3 bucket returns the following header for me
```
# CORS config in my real S3
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
<CORSRule>
    <AllowedOrigin>http://example.com</AllowedOrigin>
    <AllowedMethod>PUT</AllowedMethod>
    <AllowedMethod>POST</AllowedMethod>
    <AllowedMethod>GET</AllowedMethod>
    <AllowedMethod>HEAD</AllowedMethod>
    <AllowedMethod>DELETE</AllowedMethod>
    <MaxAgeSeconds>3000</MaxAgeSeconds>
    <AllowedHeader>*</AllowedHeader>
</CORSRule>
</CORSConfiguration>

# The preflight header from this bucket when AllowedHeader is *
Access-Control-Allow-Headers: cache-control, content-type, x-requested-with
```

After some investigation, I have monkey patched **line 26 of localstack/services/generic_proxy.py** as follows.
```
CORS_ALLOWED_HEADERS = ('authorization', 'content-type', 'content-md5', 'cache-control', 'x-requested-with',
```
With this, my dropzone works for me again. (Dropzone uses Cache-Control and X-Requested-With headers by default)

If you could tweak generic_proxy.py as above, that would be helpful. 

Thank you,

**Comment by tmaier** [comment]
Hi,

you can add `x-requested-with` without the need for monkey patching with the env variable `EXTRA_CORS_ALLOWED_HEADERS`

`EXTRA_CORS_ALLOWED_HEADERS=x-requested-with`

**Comment by kitzilla** [comment]
Thank you for the tip. `EXTRA_CORS_ALLOWED_HEADERS` worked for my situation
