### ISSUE TITLE
bug: Attempting to create an Elasticache replication group on redis7 creates one on redis6 instead

### ISSUE THREAD

**Issue by swwu** [localstack/localstack#8773]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Running against localstack with these arguments for a replication group in Pulumi:
```js
    {
      multiAzEnabled: true,
      automaticFailoverEnabled: true,
      atRestEncryptionEnabled: true,
      nodeType: "cache.r6g.large",
      engineVersion: "7.0",
      parameterGroupName: "default.redis7.cluster.on",
      numNodeGroups: 2,
      replicasPerNodeGroup: 1,
      securityGroupIds: [elasticacheSecurityGroup.id],
      subnetGroupName: elasticacheSubnetGroup?.id,
    },
 ```
 creates a redis cluster with `redis_version:6.0.16`. The same command, when run against AWS, properly creates a cluster on redis7.

### Expected Behavior

The above parameters should create a cluster on redis7 on localstack.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal s3 mb s3://mybucket

### Environment

```markdown
- OS: macOS 12.5
- LocalStack: localstack/localstack-pro:2.2.0
```

**Comment by ackdav** [comment]
Hi @swwu - thanks for this report. I'm not very familiar with elasticache, but since the report didn't have a fully reproducible example, I quickly tried to produce one...
If I execute the following:
```
$ awslocal elasticache create-replication-group \
    --replication-group-id "mygroup" \
    --replication-group-description "my group" \
    --cache-node-type "cache.r6g.large" \
    --engine-version "7.0" \
    --multi-az-enabled \
    --automatic-failover-enabled \
    --at-rest-encryption-enabled \
    --cache-parameter-group-name "default.redis7.cluster.on" \
    --num-node-groups 2 \
    --replicas-per-node-group 1 \
    --cache-subnet-group-name "test"\
    --engine "redis"
[...]
$ awslocal elasticache describe-cache-clusters
[...]
            "CacheNodeType": "cache.r6g.large",
            "Engine": "redis",
            "EngineVersion": "7.0",
            "CacheClusterStatus": "available",
[...]
```
So on first sight it seems that the engine version is per default, and via argument set to 7.0.
Could you assist in trying to create a reproducible example so we can more easily work on this? Thx

**Comment by swwu** [comment]
Hi @ackdav! Thanks for looking into this.

I believe that replication is the same as what I'm doing. You're correct that `awslocal` reports that the localstack cluster is running on redis 7. However, on my machine, the actual cluster itself is not running on redis 7.

e.g. in my case, i see this:
```
➜  ~ aws --endpoint-url=http://localhost:4566 elasticache describe-cache-clusters | grep -i port -m 1
                "Port": 4511
➜  ~ redis-cli -p 4511 info | grep redis_version
redis_version:6.0.16
```
and redis7-specific commands fail:
```
➜  ~ redis-cli -p 4511 lmspop 1 foo
(error) ERR unknown command `lmspop`, with args beginning with: `1`, `foo`,
```
