### ISSUE TITLE
enhancement request: AWS::Scheduler::Schedule and AWS::Scheduler::ScheduleGroup

### ISSUE THREAD

**Issue by viren-nadkarni** [localstack/localstack#8777]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Enhancement description

https://github.com/localstack/localstack/pull/8754 added EventBridge Scheduler support however LocalStack is missing support for resource types: `AWS::Scheduler::Schedule` and `AWS::Scheduler::ScheduleGroup`

Follow up on https://github.com/localstack/localstack/issues/7268

### 🧑‍💻 Implementation

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-scheduler-schedule.html

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-scheduler-schedulegroup.html

**Comment by Rayyan98** [comment]
Is this open for open source contribution ?
