### ISSUE TITLE
bug: Lambda: Execution environment startup failed : Permission denied

### ISSUE THREAD

**Issue by mgnfcnt** [localstack/localstack#8806]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have been facing some permission issues while trying to trigger lambda function. But I get following error:

Execution environment startup failed: {"errorMessage": "[Errno 13] Permission denied: '/var/task/index.py'", "errorType": "PermissionError", "stackTrace": ["  File \"/var/lang/lib/python3.8/imp.py\", line 300, in find_module\n    with open(file_path, 'rb') as file:\n"]}

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)
index.py

```
def lambda_handler(event, context):
  print("Hello, Lambda!")
  return {
    "statusCode": 200,
    "body": "Hello, Lambda!"
  }
```
Dockerfile:

```
FROM localstack/localstack:latest
# or if using the pro image:
#FROM localstack/localstack-pro:latest
USER root
COPY all.crt /usr/local/share/ca-certificates/cert-bundle.crt
RUN update-ca-certificates
ENV CURL_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
ENV REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
```

docker-compose.yml

```
version: "3.9"
services:
  localstack:
    image: spec-localstack
    container_name: localstack
    ports:
      - "4566:4566"  # Port for AWS services
    environment:
      - DEBUG=1
      - SERVICES=lambda, s3, logs  # Only start the Lambda service
      - LAMBDA_EXECUTOR=docker-reuse  # To use Docker for Lambda execution
      - DOCKER_HOST=unix:///var/run/docker.sock
      - PROVIDER_OVERRIDE_LAMBDA=asf
    volumes:
      - ./lambda_function:/var/task  # Mount the lambda_function directory to /var/task in the container
      - /var/run/docker.sock:/var/run/docker.sock  # Mount the Docker socket into the container
    networks:
      - localstack_network

networks:
  localstack_network:
```

execution-role.json

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": "*",
      "Resource": "*"
    }
  ]
}
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

`aws --endpoint-url=http://localhost:4566 iam create-role --role-name spec-lambda-executor-role --assume-role-policy-document file://execution-role.json`

I can see it is successfull:

AWS iam.CreateRole => 200

```
aws --endpoint-url=http://localhost:4566 \
lambda create-function --function-name spec-upload \
--zip-file fileb://deploy.zip \
--handler index.lambda_handler --runtime python3.8 \
--role arn:aws:iam::000000000000:role/spec-lambda-executor-role  --region us-east-1
```
Changing Lambda 'arn:aws:lambda:us-east-1:000000000000:function:spec-upload:$LATEST' (id 30db9326) to active

But when i try to tigger it fails:

`aws lambda --endpoint-url="http://localhost:4566" invoke --function-name spec-upload --payload '{"key": "value"}' output.txt`

`2023-08-02 15:54:15 2023-08-02T12:54:15.954  WARN --- [   asgi_gw_1] l.s.a.i.executor_endpoint  : Execution environment startup failed: {"errorMessage": "[Errno 13] Permission denied: '/var/task/index.py'", "errorType": "PermissionError", "stackTrace": ["  File \"/var/lang/lib/python3.8/imp.py\", line 300, in find_module\n    with open(file_path, 'rb') as file:\n"]}`

### Environment

```markdown
- OS:Windows
- LocalStack: Latest
```

**Comment by mgnfcnt** [comment]
I checked this: but steps mentioned there is not working also: https://github.com/localstack/localstack/issues/2969

**Comment by dominikschubert** [comment]
@mgnfcnt Did you try this with the original `localstack` image directly?
Why you are mounting into `/var/task` of the localstack container. :thinking: 

Please give it a try with the docker-compose file from our repo:
https://github.com/localstack/localstack/blob/838f1ff0dcd374e4ca71e84fcedc10448f5d01ef/docker-compose.yml#L1-L15

Please also note that `PROVIDER_OVERRIDE_LAMBDA=asf` is not needed anymore and default since LocalStack 2.0 and `LAMBDA_EXECUTOR=docker-reuse` has no effect in this case (now the default behavior as well).

**Comment by mgnfcnt** [comment]
@dominikschubert I also tried with what you suggested prevoiously. I am behind corporate Proxy and i was facing ssl issues hence İ created a custom image including ssl certificates and pointed docker compose to the image

**Comment by mgnfcnt** [comment]
docker-compose.yml

```
version: "3.8"
services:
  localstack:
    container_name: localstack_main
    image: spec-localstack
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
    environment:
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - ./.localstack:/var/lib/localstack
      - "/var/run/docker.sock:/var/run/docker.sock"
```

I tried 3 different types to create zip , zip command on git bash, winrar, 7zip but unfortunatelly I have following issue:
```

2023-08-03T05:02:13.371 ERROR --- [   asgi_gw_1] l.s.awslambda.provider     : Error while invoking lambda
2023-08-03T05:02:13.371755993Z Traceback (most recent call last):
2023-08-03T05:02:13.371767483Z   File "/opt/code/localstack/localstack/services/awslambda/provider.py", line 1268, in invoke
2023-08-03T05:02:13.371774692Z     invocation_result = result.result()
2023-08-03T05:02:13.371778001Z   File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 458, in result
2023-08-03T05:02:13.371781150Z     return self.__get_result()
2023-08-03T05:02:13.371784014Z   File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
2023-08-03T05:02:13.371787032Z     raise self._exception
2023-08-03T05:02:13.371789822Z   File "/opt/code/localstack/localstack/services/awslambda/invocation/version_manager.py", line 429, in invocation_loop
2023-08-03T05:02:13.371792924Z     environment.invoke(invocation_event=queued_invocation)
2023-08-03T05:02:13.371795789Z   File "/opt/code/localstack/localstack/services/awslambda/invocation/runtime_environment.py", line 260, in invoke
2023-08-03T05:02:13.371799000Z     "payload": to_str(invocation_event.invocation.payload),
2023-08-03T05:02:13.371804443Z   File "/opt/code/localstack/localstack/utils/strings.py", line 34, in to_str
2023-08-03T05:02:13.371807514Z     return obj.decode(encoding, errors) if isinstance(obj, bytes) else obj
2023-08-03T05:02:13.371810683Z UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9e in position 0: invalid start byte
2023-08-03T05:02:13.371861305Z 2023-08-03T05:02:13.371  INFO --- [   asgi_gw_1] localstack.request.aws     : AWS lambda.Invoke => 500 (ServiceException)
```

**Comment by mgnfcnt** [comment]
> Hey @mgnfcnt I created this sample repo to help you troubleshoot. You'll have to add the Dockerfile to create the custom image. Try to remove the `/var/task` mount like @dominikschubert said. I cannot reproduce the issue on my Mac with this repo. I've included python and node Lambdas for your convenience.
> 
> https://github.com/localstack-samples/sample-simple-invoke-lambda

I used this repo directly but issue still happens
