### ISSUE TITLE
Official helm chart 🎉

### ISSUE THREAD

**Issue by sidhuko** [localstack/localstack#882]
I'm currently writing a contribution and looking to help maintain a localstack incubator chart within helm/charts for the localstack community. They're is already an [unofficial project](https://github.com/everpeace/helm-charts/tree/master/localstack) which can be improved upon with permission of the author and a few interested contributors - please get in touch if you're still interested! 

There are some requirements to making the chart stable which would need to be discussed with maintainers of localstack organisation. For instance, the [technical requirements](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#technical-requirements) specify all docker image source code needs to be in Github repositories. I've hit a problem that the dependent image (`localstack/java-maven-node-python`) is not available. After inspecting the image locally it seems to be relatively simple and I was wondering whether you could push this and setup integrations for security screening and github on your docker hub account please? In return I will gladly look at using a [multistage build](https://docs.docker.com/v17.09/engine/userguide/eng-image/multistage-build/) to reduce the image size further.

Also, it is preferred to use fixed versions rather than a latest tag within helm conventions so the way latest is tagged without another reference is likely to cause a conflict when trying to get a recently patched build.

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-313) by [Unito](https://www.unito.io/learn-more)

**Comment by whummer** [comment]
Thanks for your effort to create an official LocalStack Helm chart @sidhuko !

As far as the technical requirements are concerned, the source code of `localstack/java-maven-node-python` is part of this repo. The image can be built via:
```
make docker-build-base
```

Please let me know how to proceed. Happy to help out where needed to get this over the line. Thanks!

**Comment by whummer** [comment]
Hey @sidhuko , any progress on creating the Helm chart? Anything we can help with? Would be great to get that over the line!

**Comment by sidhuko** [comment]
There was WIP branch here: https://github.com/sidhuko/charts/pull/1/files

**Comment by rpocase** [comment]
@sidhuko  Did you make any more progress on this? I'll have a need for localstack in k8s very soon and would prefer a semi-official chart than having to fork the previous works.

**Comment by mforutan** [comment]
@sidhuko I'd be happy to help as well if there is something here that can speed up the process.

**Comment by boreasops** [comment]
@sidhuko - happy to help with getting this progressed, the [WIP](https://github.com/sidhuko/charts/pull/1/files) is looking good so far.

**Comment by mforutan** [comment]
@sidhuko @whummer @boreasops, I think a request should be added here to create a new repository under localstack organization as [stable](https://github.com/helm/charts) repository doesn't accept any new chart anymore, the new chart can be hosted in that new chart repository via git-pages using this [GitHub Action](https://github.com/helm/chart-releaser-action)

**Comment by siavashs** [comment]
What's the current status of the chart?
I also have an implementation which I've been using privately at work but can release.

**Comment by whummer** [comment]
Hi @siavashs @mforutan @boreasops - if you could help us raise the request to create an official Helm chart, that would be much appreciated! Thanks for your help.

**Comment by mforutan** [comment]
hi @whummer, how can I help you here? what is the process for discussing about the options?

**Comment by JamesArthurHolland** [comment]
@sidhuko  How is the WIP coming along? I need this helm chart badly

**Comment by mforutan** [comment]
I went ahead and created a PR to release the above Helm chart in this repo via GitHub Actions: #3312 

I thought this could be a starting point for a discussion instead of waiting for a decision on how to release the helm chart, feel free to add your comment there or ask any question.

**Comment by JamesArthurHolland** [comment]
@whummer I'm having issues with this helm chart, it says 

```
2020-12-07T20:31:28:WARNING:localstack.services.plugins: Service "secretsmanager" not yet available, retrying...
Waiting for all LocalStack services to be ready
```

I have secretsmanager set to "enabled" in my values file. Do you recognise this error?

**Comment by JamesArthurHolland** [comment]
I had to remove the health / readiness checks for it to stop restarting over this issue...
