### ISSUE TITLE
bug: S3 Content-Length not set with AWS SDK for Java

### ISSUE THREAD

**Issue by bropyro** [localstack/localstack#8841]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When reading a file of a bucket with the Java AWS SDK the content-length is not set in the GetObjectResponse.

![image](https://github.com/localstack/localstack/assets/90579580/4c89a103-b064-4061-a91e-2012b19b838f)

![image](https://github.com/localstack/localstack/assets/90579580/8f52adf0-1205-4d6f-8fd0-6d026cac6db6)

### Expected Behavior

The content-length is included in the response

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

This is the content of my docker-compose file:
`  s3:
    container_name: "s3test"
    image: "localstack/localstack:2.2.0"
    ports:
      - "4566:4566"
    volumes:
      - ./src/test/local/s3/data:/var/lib/localstack/s3
      - ./src/test/local/s3/init-s3.sh:/etc/localstack/init/ready.d/init-s3.sh`

In the init script I create a bucket and put some file to it:
`awslocal s3api create-bucket --bucket test-bucket
aws s3api put-object --body /var/lib/localstack/s3/test.png --bucket test-bucket --key storage/test.png --content-type image/png --endpoint-url http://localhost:4566`

Then I query the file using the getObject Method of the S3Client of the Java AWS SDK

### Environment

```markdown
- OS: Windows 10
- LocalStack:2.2.0
```

### Anything else?

This behavior starts with version 2.2.0. Using version 2.1.0 everything works as expected

**Comment by bentsku** [comment]
Hello @bropyro and thanks for your report. I'm currently unable to reproduce your issue. Could you share a reproducible sample? Which version of the Java SDK are you using?

**Comment by bentsku** [comment]
Hi @bropyro, I could reproduce the issue, and I'll try to get a fix up soon. Basically, it seems it happens when using the virtual host addressing of the bucket, is that right? Accessing S3 with the bucket as part as the host?
