### ISSUE TITLE
make install fails without Building wheel for amazon-kclpy  

### ISSUE THREAD

**Issue by hckrbaba** [localstack/localstack#8847]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Getting the following error on `make install`
```
Successfully built localstack-core
Failed to build amazon-kclpy
ERROR: Could not build wheels for amazon-kclpy, which is required to install pyproject.toml-based projects
make: *** [install-dev] Error 1
```

Have searched and found [this](https://github.com/localstack/localstack/issues/1033), but running `pip install amazon-kclpy==2.1.1` in the venv fails with 
```
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for amazon-kclpy
  Running setup.py clean for amazon-kclpy
Failed to build amazon-kclpy
ERROR: Could not build wheels for amazon-kclpy, which is required to install pyproject.toml-based projects
```

What am I doing wrong ?

### Expected Behavior

make install should've run successfully

### How are you starting LocalStack?

Custom (please describe below)

### Steps To Reproduce

Can't start yet as `make install ` itself is failing.
Following the steps mentioned [here](https://docs.localstack.cloud/contributing/development-environment-setup/)

### Environment

```markdown
- OS:macos 13.4.1


localstack % python --version
Python 3.10.4
localstack % node --version
v18.17.0
localstack % npm --version
9.6.7
localstack % javac --version
javac 20.0.2
```
```


### Anything else?

_No response_

**Comment by alexrashed** [comment]
Hi @hckrbaba!
Thanks for the issue report! You definitely shouldn't have to pin any dependencies (if they are not already pinned in our `setup.cfg`). Could you please send us the logs where you call `make install` (and remove the previously created `.venv` before)? There has - coincidentally - also been a release of the kinesis client in the meantime: https://github.com/awslabs/amazon-kinesis-client-python/releases/tag/v2.1.3

**Comment by hckrbaba** [comment]
Closing this as the error I had observed was 
```
      Failed to retrieve https://search.maven.org/remotecontent?filepath=software/amazon/awssdk/http-client-spi/2.19.2/http-client-spi-2.19.2.jar: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>
```
Which was a python certificate issue on my front. 
Fixed that. And now it is working fine.
