### ISSUE TITLE
bug: LOCALSTACK_HOST does not work with s3 path style URLS

### ISSUE THREAD

**Issue by speedofsound99** [localstack/localstack#8849]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If I only set the LOCALSTACK_HOST variable to LOCALSTACK_HOST=test.dev:4566 in my docker compose file, and if I try to use the s3ForcePathStyle option for S3, localstack still returns non path style urls (it would return https://my-bucket-name.s3.localhost.localstack.cloud:4566/... instead of the expected https://test:dev:4566/my-bucket-name/...)

If I set HOSTNAME_EXTERNAL=test.dev it works but according to documentation it has been deprecated and should be replaced with LOCALSTACK_HOST

### Expected Behavior

Expected localstack would respect LOCALSTACK_HOST value for S3 path style URLS.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

docker compose -f localstack.yml --no-build --force-recreate

### Environment

```markdown
- OS: linux
- LocalStack: 2.2
```

**Comment by bentsku** [comment]
Hello @speedofsound99 and thanks for your report.

Using `s3ForcePathStyle` on the client will have no influence on how the Location URL are returning from LocalStack, this is only a client setting which is not communicated directly to LocalStack.

We currently have a case in LocalStack that if `HOSTNAME_EXTERNAL` is set, the Location URL will be returned in path style, and if not, will return the default host. This might need to be changed with the deprecation, I will try to update it and open a PR for it. Thanks!

**Comment by bentsku** [comment]
Hello @speedofsound99! With our latest release `3.0.0`, this should now be fixed. Could you give it a try again with `LOCALSTACK_HOST` and see if that works for you? 

I just tried it with starting LocalStack with `LOCALSTACK_HOST=test.dev:4566`:
```bash
awslocal s3api create-bucket \
    --bucket my-bucket \
    --region eu-west-1 \
    --create-bucket-configuration LocationConstraint=eu-west-1
{
    "Location": "http://test.dev:4566/my-bucket/"
}
```

I'll close this issue as this is now fixed, but feel free to re-open or comment if it doesn't work for you. Thanks!
