### ISSUE TITLE
Lambda in Go ends up in `Read timed out`

### ISSUE THREAD

**Issue by takkyuuplayer** [localstack/localstack#885]
A lambda function written in Golang ends up in

```
HTTPConnectionPool(host='localhost', port=4574): Read timed out. (read timeout=60)
```

when I run through `localstack/localstack`, while running through `lambci/lambda:go1.x` or AWS succeeds.

This is how to reproduce.
https://gist.github.com/takkyuuplayer/589f78de9fe186581b6b6dd8132ac626

Do you have any idea to solve?

Thank you.

**Comment by calbertts** [comment]
I'm having same issue deploying a NodeJS lambda.

**Comment by whummer** [comment]
Thanks for reporting - this is a fairly old issue that should be fixed in the meantime. Please report here if the problem persists. Thanks!
