### ISSUE TITLE
bug: KINESIS_INITIALIZE_STREAMS not set in latest docker image

### ISSUE THREAD

**Issue by etspaceman** [localstack/localstack#8895]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Setting `KINESIS_INITIALIZE_STREAMS` no longer is taking in the newest localstack/localstack:latest image. You can see some logs here:

https://github.com/etspaceman/kinesis4cats/actions/runs/5835796510/job/15828063287

`initializeStreams` is null

```
[info] kinesis.mock.KinesisMockService$ 2023-08-11T18:33:21.836147Z contextId=1ce47d17-0b9a-4ad5-927d-4e9fed8b5829, cacheConfig={"awsAccountId":"000000000000","awsRegion":"us-east-1","createStreamDuration":{"length":0,"unit":"MILLISECONDS"},"deleteStreamDuration":{"length":0,"unit":"MILLISECONDS"},"deregisterStreamConsumerDuration":{"length":0,"unit":"MILLISECONDS"},"initializeStreams":null,"logLevel":"INFO","mergeShardsDuration":{"length":0,"unit":"MILLISECONDS"},"onDemandStreamCountLimit":10,"persistConfig":{"fileName":"000000000000.json","interval":{"length":5,"unit":"SECONDS"},"loadIfExists":true,"path":"../../../var/lib/localstack/tmp/state/kinesis","shouldPersist":true},"registerStreamConsumerDuration":{"length":0,"unit":"MILLISECONDS"},"shardLimit":100,"splitShardDuration":{"length":0,"unit":"MILLISECONDS"},"startStreamEncryptionDuration":{"length":0,"unit":"MILLISECONDS"},"stopStreamEncryptionDuration":{"length":0,"unit":"MILLISECONDS"},"updateShardCountDuration":{"length":0,"unit":"MILLISECONDS"}} Logging Cache Config
```

Reverting to 2.2.0 resolves the issue.

### Expected Behavior

`KINESIS_INITIALIZE_STREAMS` sets values

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack:latest

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal kinesis list-streams

### Environment

```markdown
- OS: ubuntu
- LocalStack: latest
```

**Comment by viren-nadkarni** [comment]
Just to note, we deprecated `KINESIS_INITIALIZE_STREAMS` in LocalStack. We start a distinct instance of Kinesis Mock per account to provide account-level namespacing https://github.com/localstack/localstack/pull/7230. `KINESIS_INITIALIZE_STREAMS` has the potential to break things by creating streams with ARNs in wrong accounts.

**Comment by etspaceman** [comment]
I was not aware of that. Is there a way that we could adjust the environment variable here to work with this setup?

**Comment by etspaceman** [comment]
Cool. I reintroduced it here: https://github.com/localstack/localstack/pull/8896

This feature is pretty heavily used by the kinesis mock users, so I'd love to be able to work on making it work better with multi account support.

**Comment by viren-nadkarni** [comment]
Brilliant, thanks for the fix @etspaceman, I will merge this and we will revisit the multi-account conflict at a later point

**Comment by viren-nadkarni** [comment]
Fixed with https://github.com/localstack/localstack/pull/8896

Thanks @etspaceman :raised_hands:
