### ISSUE TITLE
bug: unable to invoke localstack deployed lambda function, UnicodeDecodeError

### ISSUE THREAD

**Issue by avoidik** [localstack/localstack#8906]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have deployed a sample golang lambda function from here https://docs.aws.amazon.com/lambda/latest/dg/golang-handler.html and then I was trying to invoke it, however it just fails whenever I provide a payload

This one works

```terminal
$ aws lambda invoke --function-name test-function /dev/stdout
```

and gives

```
"Hello !"{
    "StatusCode": 200,
    "ExecutedVersion": "$LATEST"
}
```

This one fails

```terminal
$ aws lambda invoke --function-name test-function --payload '{"name": "test"}' /dev/stdout
```

with

```
Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/awslambda/invocation/version_manager.py", line 429, in invocation_loop
    environment.invoke(invocation_event=queued_invocation)
  File "/opt/code/localstack/localstack/services/awslambda/invocation/runtime_environment.py", line 260, in invoke
    "payload": to_str(invocation_event.invocation.payload),
  File "/opt/code/localstack/localstack/utils/strings.py", line 34, in to_str
    return obj.decode(encoding, errors) if isinstance(obj, bytes) else obj
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9d in position 0: invalid start byte
```

### Expected Behavior

Both requests should work.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

Follow https://docs.localstack.cloud/getting-started/installation/#docker-compose

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

Get sample code from here - https://docs.aws.amazon.com/lambda/latest/dg/golang-handler.html

Build it as follows

```
env GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -tags lambda.norpc -o bootstrap main.go
zip lambda.zip bootstrap
```

Deploy as follows

```
aws lambda create-function --function-name test-function \
    --runtime provided.al2 --handler bootstrap \
    --architectures arm64 \
    --role arn:aws:iam::111111111111:role/lambda-runtime-role \
    --zip-file fileb://lambda.zip
```

### Environment

```markdown
- OS: MacOS Ventura 13.5 (22G74) + colima vm
- LocalStack: localstack/localstack:2.2
```

**Comment by avoidik** [comment]
Unfortunately neither 'arm64' nor 'x86_64' works

**Comment by MarcelStranak** [comment]
Hi, can you please try adding ` --cli-binary-format raw-in-base64-out` to the invoke command? Similar to the [AWS CLI v2 example](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/lambda/invoke.html#examples).

`$ aws lambda invoke --function-name test-function --cli-binary-format raw-in-base64-out --payload '{"name": "test"}' /dev/stdout`

**Comment by avoidik** [comment]
amazing, thanks @MarcelStranak, that was it
