### ISSUE TITLE
bug: Cannot resolve CF fn::Join {'Fn::Join': ['', ['Default Authenticated Role for Identity Pool 

### ISSUE THREAD

**Issue by Nikola-Milovic** [localstack/localstack#8933]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I was playing around with Localstack pro and CDK, using the `cdklocal` wrapper I bootstrapped my environment and tried to create a Cognito stack and deploy it. But it kept failing, after some debugging the culprit is the `IdentityPool` resource. I submited an issue to the `cdklocal` repo but they directed me to post here https://github.com/localstack/aws-cdk-local/issues/86

Basically if we use `import { IdentityPool, UserPoolAuthenticationProvider } from '@aws-cdk/aws-cognito-identitypool-alpha'`

We will fail with a `The stack named AuthStack failed to deploy: CREATE_FAILED`

### Expected Behavior

It would get deployed and work as expected, since Identity Pools are supported, but it seems that the `Identity Roles` created by the identity pool is not supported yet and is causing this issue

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

  
  ```
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack-pro  # required for Pro
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
      - "127.0.0.1:53:53"                # DNS config (required for Pro)
      - "127.0.0.1:53:53/udp"            # DNS config (required for Pro)
      - "127.0.0.1:443:443"              # LocalStack HTTPS Gateway (required for Pro)
    environment:
      - DEBUG=${DEBUG-1}
      - PERSISTENCE=${PERSISTENCE-}
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY-}  # required for Pro
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./.localstack}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

### Environment

```markdown
- OS: Ubuntu 20.04 
- LocalStack: latest
```

### Anything else?

https://github.com/Nikola-Milovic/cdklocal-issue

Demo with logs and steps to reproduce

**Comment by whummer** [comment]
Reported as resolved in https://github.com/localstack/aws-cdk-local/issues/86 👍  - closing.
