### ISSUE TITLE
enhancement request:  Allow static routing

### ISSUE THREAD

**Issue by kfirgollan** [localstack/localstack#8941]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Enhancement description

Allow static configuration of the route to a service.
A classic example is running a single service like so

```
docker run -p 9090:4566 -e SERVICES=s3 -e DEBUG=1 localstack/localstack:latest
```
Here we are running only S3, yet we will still run into routing related issues.
A simple example is to list the buckets configured.
```bash
curl -X GET "http://localhost:9090/"
```

This will result in an empty response and with the following log
```
2023-08-20T09:11:02.783 DEBUG --- [   asgi_gw_0] l.aws.handlers.service     : no service set in context, skipping request parsing
2023-08-20T09:11:02.783  INFO --- [   asgi_gw_0] localstack.request.http    : GET / => 200
```

Looking in the source we can see that this is due to the way the code detects the wanted service.
We can do a hack, by simulating that we use the aws cli (based on [this](https://github.com/localstack/localstack/blob/1ec4e7ff5126f2d7a85b536e70b432502b5bad25/localstack/aws/protocol/service_router.py#L209)).
```bash
curl -X GET -H "User-Agent: aws-cli/" "http://localhost:9090/"
```

This modification makes the router understand we want the S3 api and we get the wanted result.

### 🧑‍💻 Implementation

I suggest bypassing the routing mechanism by allowing user to configure it.
e.g if there is only a single service defined -> all requests will go to that service.
if there are multiple services, allow each to specify different port for each service, bypassing the routing mechanism.

**Comment by thrau** [comment]
Thanks for the suggestion Kfir @kfirgollan. We do support this kind of static routing the same way AWS does through the use of endpoint prefixes (subdomains). The router will resolve `<service>.localhost.localstack.cloud` to the respective service, regardless of the HTTP request parameters.

```console
curl s3.localhost.localstack.cloud:4566                                                     
<?xml version='1.0' encoding='utf-8'?>
<ListAllMyBucketsResult><Owner><DisplayName>webfile</DisplayName><ID>75aa57f09aa0c8caeab4f8c24e99d10f8e7faeebf76c078efc7c6caea54ba06a</ID></Owner><Buckets /></ListAllMyBucketsResult>
```

If you'd rather call `localhost`, then you can also use the Host header:
```console
curl -H 'Host: s3.localhost.localstack.cloud' localhost:4566
<?xml version='1.0' encoding='utf-8'?>
<ListAllMyBucketsResult><Owner><DisplayName>webfile</DisplayName><ID>75aa57f09aa0c8caeab4f8c24e99d10f8e7faeebf76c078efc7c6caea54ba06a</ID></Owner><Buckets /></ListAllMyBucketsResult>
```

If your system supports it you could even use the `localhost` subdomains: `curl s3.localhost:4566`

**Comment by kfirgollan** [comment]
Thanks for the fast reply, while I understand the response, I think that adding this feature will make it simpler to use for local development.

Anyway, adding here my example usage using docker compose, in case it helps others.

```yaml
version: '2'

services:
  s3.localstack:
    image: localstack/localstack:latest
    environment:
      SERVICES: "s3"
      DEBUG: 1

  sqs.localstack:
    image: localstack/localstack:latest
    environment:
      SERVICES: "sqs"
      DEBUG: 1
```

Then based on dns resolution of docker-compose you can do
```bash
$ curl http://s3.localstack:4566
<?xml version='1.0' encoding='utf-8'?>
<ListAllMyBucketsResult><Owner><DisplayName>webfile</DisplayName><ID>75aa57f09aa0c8caeab4f8c24e99d10f8e7faeebf76c078efc7c6caea54ba06a</ID></Owner><Buckets /></ListAllMyBucketsResult>
```

While this does work, I would much rather eliminate the subdomain part, just be able to use `s3` or `sqs` as the domain would be nice.

**Comment by thrau** [comment]
We could do some implicit magic configuration based on the services variable only containing one value, it just seems a bit arbitrary to me. I don't see which problem exactly this example is solving. Why not just one LocalStack instance and route using Domains or host headers? This is also how AWS works.

Happy to learn more though

**Comment by kfirgollan** [comment]
well, it is easier to test failure scenarios like this. e.g take down the s3 service to simulate connectivity failure.
It is easier to clear state of a service during a test ("flush everything in SQS etc).
Regarding the domains use case, personally I use a development VM to run my workloads, and I don't set up a dns server for that, simply work with the ip of my vm and map different ports to the services that I need

I guess it is possible to do these actions with a single instance, I just find it easier to reason about these things when they are separated.
