### ISSUE TITLE
bug: PROVIDER_OVERRIDE_STEPFUNCTIONS=v2 - InternalFailure: API action 'ListTagsForResource' for service 'stepfunctions' not yet implemented or pro feature

### ISSUE THREAD

**Issue by BrianMcBrayer** [localstack/localstack#8949]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am using `PROVIDER_OVERRIDE_STEPFUNCTIONS=v2`.

When I try to run my terraform, the step function is created as reflected in the terraform state (and I cannot rerun my terraform without deleting the state).

But, I get the error

```
 Error: listing tags for SFN (Step Functions) State Machine (arn:aws:states:us-east-1:000000000000:stateMachine:sample_state_machine): InternalFailure: API action 'ListTagsForResource' for service 'stepfunctions' not yet implemented or pro feature - please check https://docs.localstack.cloud/references/coverage/coverage_stepfunctions/ for further information
│       status code: 501, request id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
```

Before I made the provider change, this worked 100% of the time.

Checking the PR for the provider https://github.com/localstack/localstack/pull/8779 `ListTagesForResource` should be working.

I use docker-compose, and it's a pretty basic docker-compose file.

Thank you so much for this project! It is amazing to work with, even with the bugs (that every project has).

### Expected Behavior

I expect that creating the state machine works.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

`docker-compose up -d`
`terraform init`
`terraform apply --auto-approve`

### Environment

```markdown
- OS: Mac
- LocalStack: latest
```

**Comment by BrianMcBrayer** [comment]
@MEPalma I'm sorry to ping you directly but I'm curious if you know if this is expected or not

**Comment by BrianMcBrayer** [comment]
Interestingly, I am only observing this with the latest `hashicorp/aws` provider. Once I change that provider, this issue goes away.

**Comment by MEPalma** [comment]
@BrianMcBrayer thank you for compiling this issue. 
At the moment StepFunctions v2 does not support resource tagging. However, we are indeed looking to add this functionality during the coming weeks.

**Comment by MEPalma** [comment]
We merged some initial support for Resource Tagging in Step Functions v2 here https://github.com/localstack/localstack/pull/8990. Please do let us know this resolves the issue that was brought up

**Comment by BrianMcBrayer** [comment]
@MEPalma thank you very much! This issue was resolved.

It opened another issue using this provider that I will open another issue for here.
