### ISSUE TITLE
Watchdog Inode event autoreload

### ISSUE THREAD

**Issue by MichaelCombs28** [localstack/localstack#895]
Is there a discussion around building a localstack official tool (similar to webpack) that will autoreload lambda functions / apigateway, etc during development?

If there is any interest in this, I've created a very very ad-hoc solution for now simply using python watchdog and a set of paths that continuously push lambda functions based on a mapping between function name and function directory. Obviously I'd rather help a community driven solution rather than releasing code meant for a single project.

**Comment by whummer** [comment]
Thanks for the suggestion @MichaelCombs28 . In the meantime, we have added a [local code mounting mode](https://github.com/localstack/localstack#using-local-code-with-lambda) which can significantly speed up the dev loop, as file changes are immediately reflected in deployed Lambdas.

If you have ideas for additional tooling of autoreload, then please feel free to sketch out your solution or create a pull request in this repo. Thanks!
