### ISSUE TITLE
FYI: Compression support for SDK's

### ISSUE THREAD

**Issue by bblommers** [localstack/localstack#8963]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Enhancement description

The AWS SDK's will start sending compressed requests, at some point in the future. This means that LocalStack (and Moto) will have to uncompress the incoming request body, before it can be inspected/acted upon.

Note that this only applies to specific circumstances:
 - Only some operations in CloudWatch will use this (at first)
 - Only for large requests (> 10 MB)

The Botocore team reached out to Moto to let us know this change was in the works - and I figured this may affect LS as well. Unless ASF already handles this?

This Moto issue has more info:
https://github.com/getmoto/moto/issues/6692

**Comment by bentsku** [comment]
Hello @bblommers and thanks a lot for the heads up!

ASF should already handle this case, we also support the special case with S3 as described in the linked issue (we however skip it for the whole `s3` service, might to adjust it at some point!)

https://github.com/localstack/localstack/blob/master/localstack/aws/handlers/codec.py

It's really nice to see the SDK team reaching out, and thanks a lot again for making us aware of this. 

But we never know if something can happen, at least we know something might change in the future, and we will know where to look!

**Comment by bblommers** [comment]
Ah, gotcha - that looks like a nice and clean implementation in ASF. I'll close this then.
