### ISSUE TITLE
bug: Error: No such command 'dns'.

### ISSUE THREAD

**Issue by Nikola-Milovic** [localstack/localstack#8971]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```console
> sudo localstack dns systemd-resolved
Usage: localstack [OPTIONS] COMMAND [ARGS]...
Try 'localstack -h' for help.

Error: No such command 'dns'.
```

Following the [docs](https://docs.localstack.cloud/user-guide/tools/transparent-endpoint-injection/dns-server/#systemd-resolved) for DNS resolution.

This may be deprecated but it would be nice that the docs then get updated

### Expected Behavior

The dns command exists

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

```console
sudo tar xvzf ~/Downloads/localstack-cli-2.2.0-linux-*-onefile.tar.gz -C /usr/local/bin
sudo localstack dns systemd-resolved
```

### Environment

```markdown
- OS:Ubuntu 20.04
- LocalStack: 2.2.0
```

**Comment by dfangl** [comment]
Hi @Nikola-Milovic !
I am sorry you are experiencing errors with our DNS integration.
To use this feature, you have to be logged in to your localstack account (using `localstack login`). Can you confirm that this issue persists when you are logged in?

**Comment by Nikola-Milovic** [comment]
This isn't mentioned in the docs, and I am not sure how to login considering I signed up via Github I believe

**Comment by HarshCasper** [comment]
Hi @Nikola-Milovic — We have shipped a new Auth Token mechanism which would allow you to use the `localstack dns systemd-resolved` without explicitly logging in.

Here is what a workflow would look like after installing the latest version of LocalStack:

```bash
$ localstack dns --help
Usage: localstack dns [OPTIONS] COMMAND [ARGS]...

  Manage the usage of the LocalStack DNS on your host.

  This command provides tools to configure your the DNS on your host machine
  to use the LocalStack DNS on your host machine. The LocalStack DNS is used
  for certain Pro features (like the transparent endpoint injection).

  Visit https://docs.localstack.cloud/user-guide/tools/transparent-endpoint-injection/dns-server/
  for more information on the LocalStack DNS and how it is used.

Options:
  -h, --help  Show this message and exit.

Commands:
  systemd-resolved  Manage LocalStack DNS in systemd-resolved

$ localstack dns systemd-resolved
👋 This feature is part of our paid offering!
=============================================
You tried to use a LocalStack feature that requires a paid subscription,
but the license activation has failed! 🔑❌

Reason: No credentials were found in the environment. Please make sure to
either set the LOCALSTACK_AUTH_TOKEN variable to a valid auth token,
or the LOCALSTACK_API_KEY variable to a valid LocalStack API key. If
you are using the CLI, you can also run `localstack auth set-token`.

Due to this error, LocalStack has quit.

- Please check that your credentials are set up correctly and that you have an active license.
  You can find your credentials in our webapp at https://app.localstack.cloud.
- If you haven't yet, sign up on the webapp and get a free trial!

$ export LOCALSTACK_AUTH_TOKEN="<auth-token>"
$ localstack dns systemd-resolved
Configuring systemd-resolved...
```

Please grab your Auth Token by following our documentation — https://docs.localstack.cloud/getting-started/auth-token/
