### ISSUE TITLE
500 Internal Server Error when listing objects versions on S3 with Java AWS SDK

### ISSUE THREAD

**Issue by derf-github** [localstack/localstack#899]
Hi guys,

When trying to list the versions of the objets in my S3 using the Java SDK, I've got the following error message :  

```
DEBUG [org.apache.http.impl.conn.PoolingHttpClientConnectionManager] Connection released: [id: 0][route: {}->http://localhost:4572][total kept alive: 1; route allocated: 1 of 50; total allocated: 1 of 50] 
DEBUG [com.amazonaws.services.s3.internal.S3ErrorResponseHandler] Failed in parsing the error response : <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>
 
javax.xml.stream.XMLStreamException: ParseError at [row,col]:[1,55]
Message: Des espaces sont obligatoires entre les ID publicId et systemId.
	at com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.next(XMLStreamReaderImpl.java:604)
	at com.amazonaws.services.s3.internal.S3ErrorResponseHandler.createException(S3ErrorResponseHandler.java:115)
	at com.amazonaws.services.s3.internal.S3ErrorResponseHandler.handle(S3ErrorResponseHandler.java:64)
	at com.amazonaws.services.s3.internal.S3ErrorResponseHandler.handle(S3ErrorResponseHandler.java:51)
```

I can list the versions of the files using the cli command : 
`aws --endpoint-url=http://localhost:4572 s3api list-object-versions --bucket my-example --prefix example` but I've got no luck with the SDK.

I've created the following project which reproduces the issues : 
[https://github.com/derf-github/localstack-list-version.git](https://github.com/derf-github/localstack-list-version.git)

I've provided the files and the script I use to upload them on my local S3.
I've created a small Java application which recreates the issue.
All the instructions should be in the README.md.

I'm running the example under Ubuntu 18.04 LTS with the following Java version : 
openjdk version "1.8.0_171"
OpenJDK Runtime Environment (build 1.8.0_171-8u171-b11-0ubuntu0.18.04.1-b11)
OpenJDK 64-Bit Server VM (build 25.171-b11, mixed mode)

Could anybody tell me what I'm doing wrong?

Thank you guys!

**Comment by dinya007** [comment]
Hi! I also encountered the same problem and was able to fix it this way:
```java
new ListVersionsRequest()
                        .withEncodingType("")
                        .withBucketName(bucketName)
                        .withPrefix(key);
```

**Comment by whummer** [comment]
Thanks for reporting and for providing a sample project @derf-github . This issue appears to be fixed in the latest version - I was able to run the provided script and Java program without any errors. Closing this issue - please re-open if the problem persists. Thanks

**Comment by desiderati** [comment]
Hey guys, I have the same problem but when calling this method: amazonS3.putObject(bucketName, key, new ByteArrayInputStream(content), objectMetadata); Any ideas?
