### ISSUE TITLE
bug: Websocket API asyncio error on connection

### ISSUE THREAD

**Issue by james-symbiote** [localstack/localstack#9002]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When connecting to an APIGatewayV2 websocket endpoint ws:/localhost:4510/ I am receive: 
`Connected (press CTRL+C to quit)` 
and I am able to enter a payload to send. 
 
When I run the command `wscat -c ws:/localhost:4510` I am receiving the following the logs in the localstack container: 
`2023-08-29T05:46:45.946  INFO --- [functhread68] websockets.server          : connection open
2023-08-29T05:46:46.010  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS dynamodb.PutItem => 200
2023-08-29T05:46:46.017  INFO --- [   asgi_gw_0] localstack.request.http    : POST /_localstack_lambda/37bcd434118d64dff174a15c26b3f370/invocations/ccb2c74b-450e-4247-9f74-6e48d0240d1b/logs => 202
2023-08-29T05:46:46.038  INFO --- [   asgi_gw_0] localstack.request.http    : POST /_localstack_lambda/37bcd434118d64dff174a15c26b3f370/invocations/ccb2c74b-450e-4247-9f74-6e48d0240d1b/response => 202
2023-08-29T05:46:46.058 ERROR --- [functhread68] asyncio                    : Exception in callback _chain_future.<locals>._set_state(<Future pendi...ask_wakeup()]>, <Future at 0x...StopIteration>) at /usr/local/lib/python3.10/asyncio/futures.py:379
handle: <Handle _chain_future.<locals>._set_state(<Future pendi...ask_wakeup()]>, <Future at 0x...StopIteration>) at /usr/local/lib/python3.10/asyncio/futures.py:379>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.10/asyncio/futures.py", line 381, in _set_state
    _copy_future_state(other, future)
  File "/usr/local/lib/python3.10/asyncio/futures.py", line 357, in _copy_future_state
    dest.set_exception(_convert_future_exc(exception))
TypeError: StopIteration interacts badly with generators and cannot be raised into a Future
2023-08-29T05:46:46.059  INFO --- [cthread14303] localstack.utils.threads   : Thread run method <function AdaptiveThreadPool.submit.<locals>._run at 0x7fcd6668be20>(None) failed:  Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/utils/threads.py", line 58, in run
    result = self.func(self.params, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/utils/asyncio.py", line 30, in _run
    return fn(*args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/apigateway/integrations.py.enc", line 99, in A
    with RequestContextManager(R):B=v2_invoke_action_from_websocket(A,D,E)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/apigateway/integrations.py.enc", line 142, in v2_invoke_action_from_websocket
    C=IntegrationResponse.from_response(C);S=get_event_request_context(B);C=ws_integration_response(A,H,D,C,S);return C
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/apigateway/integrations.py.enc", line 177, in ws_integration_response
    B=response;C=integr_details.get(_M);A=next(filter(lambda ir:ir.get(_M)==C,api_details.integration_responses.values()))
StopIteration`

If I then try to send the payload `{"message":"hello", "header": "111", "id": "111"}` no further logs are created in the localstack or lambda container. 

### Expected Behavior

Deploying the same infrastructure in AWS I am able to:
1. Connect to the websocket endpoint `wscat -c wss://xxx.execute-api.region.amazonaws.com/production`
2. Connect to the websocket on a 2nd terminal with the same command
3. On either terminal send the payload {"message":"hello", "header": "111", "id": "111"}
4. Receive the following output on terminal(sender): 
wscat -c wss://xxx.execute-api.region.amazonaws.com/production
Connected (press CTRL+C to quit)
> {"message":"hello", "header": "111", "id": "111"}
< {"header":"111","message":"hello","id":1693288935849}
< Data sent.
5. Receive the following output on terminal(receiver) 
wscat -c wss://xxx.execute-api.region.amazonaws.com/production
Connected (press CTRL+C to quit)
< {"header":"111","message":"hello","id":1693288935849}

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)
Using the example docker-compose file:

docker-compose file: 
[docker-compose.txt](https://github.com/localstack/localstack/files/12460983/docker-compose.txt)
running `docker-compose up -d`

HOW TO DEPLOY: 
We are using this sample from AWS https://github.com/aws-samples/simple-websockets-chat-app/blob/master/template.yaml 
Which we converted into this terraform file: 
[apigatewayv2_websocket.txt](https://github.com/localstack/localstack/files/12461020/apigatewayv2_websocket.txt)

Code for onconnect lambda https://github.com/aws-samples/simple-websockets-chat-app/tree/master/onconnect
Code for ondisconnect https://github.com/aws-samples/simple-websockets-chat-app/tree/master/ondisconnect
Code for sendmessage https://github.com/aws-samples/simple-websockets-chat-app/tree/master/sendmessage

Run the following: 
1. docker-compose up -d
2. tflocal init 
3. tflocal apply -var "abs_path=$$ABS_PATH --auto-approve (ABS_PATH is the path to the lambdas) 
4. run `wscat -c wscat -c ws://localhost:4510` - this step will produce the logs in the localstack container

### Environment

```markdown
- OS:Ubuntu 20.04
- LocalStack: latest
```

**Comment by bentsku** [comment]
Hello!

The given code was a bit incomplete, especially the packaging of the lambdas. I’ve worked to make it run against LocalStack:
- the S3 code for lambda cannot be used as is. I’ve done a workaround by manually packaging it as `.zip` files, and manually creating an S3 Bucket and uploading the lambda code to it
- the Terraform code for the lambda handler is not pointing to the right file. The current handler is `main.handler` in the provided Terraform file, I’ve replaced it with `index.handler` and renamed the JS files accordingly
- it seems the DynamoDB table name was not passed to the lambda as an environment variable as required in the lambda code, I’ve added it to the Terraform configuration
- the Terraform file is specifying `node18` as the lambda version, but the lambda code is using the `aws-sdk` v2, and `node18` does not package it anymore, only v3 (maybe it was packaged differently with SAM, and it manually added the `aws-sdk`). I’ve changed it to be `node16` which still packaged the SDK used in the lambda code
- there was an issue in the lambda code regarding `postToConnection` as it used the domain name which is returned as `localhost` from LocalStack, so I’ve adapted the lambda code to work with LocalStack. This is a limitation from LocalStack at the moment.
- the message sent did not follow the format required by the lambda code for `ws-send`, namely it did not have a `data` field which was required to be returned as an echo. It seems it might not have been mandatory against AWS, but I did not verify. I’ve adapted the lambda code to return an empty string in the case the `data` field is not sent.

You can try the following repository with some instructions to deploy against LocalStack: https://github.com/bentsku/simple-websockets-chat-app-tf

Can you confirm if it runs for you?

**Comment by calvernaz** [comment]
Hi @james-symbiote can you try @bentsku sample and check if you still have the issue?

**Comment by bentsku** [comment]
I'll close the issue, if you still encounter an issue, please feel free to re-open!
