### ISSUE TITLE
bug: PROVIDER_OVERRIDE_STEPFUNCTIONS=v2 - Getting `InvalidDefinition: None` for a valid state machine definition

### ISSUE THREAD

**Issue by kevle1** [localstack/localstack#9006]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

I have the following state machine definition in Terraform that fails when using `tflocal` to deploy to Localstack. 

```
resource "aws_sfn_state_machine" "test_sfn" {
  name     = "test-state-machine"
  role_arn = aws_iam_role.state_machine_role.arn

  definition = jsonencode({
    "StartAt": "CheckCondition",
    "States": {
      "CheckCondition": {
        "Type": "Task",
        "Resource": module.check.lambda_function_arn,
        "ResultPath": "$.result",
        "Next": "CheckResult"
      },
      "CheckResult": {
        "Type": "Choice",
        "Choices": [
          {
            "Variable": "$.result.done",
            "BooleanEquals": true,
            "Next": "Send"
          },
          {
            "Variable": "$.result.done",
            "BooleanEquals": false,
            "Next": "CheckCondition"
          }
        ]
      },
      "Send": {
        "Type": "Task",
        "Resource": module.send.lambda_function_arn,
        "End": true
      }
    }
  })
}
```

When creating the state machine with `tflocal apply`, I get the error:
```
aws_sfn_state_machine.ingest_sfn: Modifying... [id=arn:aws:states:ap-southeast-2:000000000000:stateMachine:test-state-machine]
╷
│ Error: updating Step Functions State Machine (arn:aws:states:ap-southeast-2:000000000000:stateMachine:test-state-machine): InvalidDefinition: None
│
│   with aws_sfn_state_machine.test_sfn,
│   on test.tf line 1, in resource "aws_sfn_state_machine" "test_sfn":
│    1: resource "aws_sfn_state_machine" "test_sfn" {
```

I am running an instance of Localstack using the following Docker run command
```
docker run -e PROVIDER_OVERRIDE_STEPFUNCTIONS=v2 -v //var/run/docker.sock:/var/run/docker.sock -p 4566:4566 -p 4571:4571 localstack/localstack
```

I am using the `PROVIDER_OVERRIDE_STEPFUNCTIONS=v2` environment variable as another state machine is failing for other validation reasons without this override. 

The error message gives **no** information as to what validation error has occurred with the definition. 
```
InvalidDefinition: None
```

I have tried the following to find the validation error, if there is even any: 

- Pasting the definition into the AWS console 
  - Passes validation, state machine created
- Running a local Docker image of `amazon/aws-stepfunctions-local` and attempting to create a state machine with the same definition using the AWS CLI
  - Passes validation, state machine created
- Hardcoded Localstack Lambda function ARNs
  - Passes validation, state machine created

### Expected Behavior

State machine is created successfully.

### How are you starting LocalStack?

With a `docker run` command

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

```
docker run -e PROVIDER_OVERRIDE_STEPFUNCTIONS=v2 -v //var/run/docker.sock:/var/run/docker.sock -p 4566:4566 -p 4571:4571 localstack/localstack
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```
tflocal init
tflocal apply
```

### Environment

```markdown
- OS: Windows 10 x64
- LocalStack: latest
```

**Comment by BrianMcBrayer** [comment]
I can confirm that I am getting this as well -- in my case, it has something to do with the `parameters`. If I use a dynamic parameter set to a static (which is invalid), I get this.

If I use a dynamic parameter `"someParam.$": "$$.State.Name"` or something, I get `index out of range`.

This has completely stopped me from using the v2 provider.

Thank y'all for looking into these issues!

**Comment by MEPalma** [comment]
Unfortunately I am unable to replicate this behaviour for the state definition provided:
```json
{
    "StartAt": "CheckCondition",
    "States": {
      "CheckCondition": {
        "Type": "Task",
        "Resource": "<resource>",
        "ResultPath": "$.result",
        "Next": "CheckResult"
      },
      "CheckResult": {
        "Type": "Choice",
        "Choices": [
          {
            "Variable": "$.result.done",
            "BooleanEquals": true,
            "Next": "Send"
          },
          {
            "Variable": "$.result.done",
            "BooleanEquals": false,
            "Next": "CheckCondition"
          }
        ]
      },
      "Send": {
        "Type": "Task",
        "Resource": "<resource>",
        "End": true
      }
    }
  }
```
is it possible you're using a slightly different definition? 
We are already working on a fix for top level `TimeoutSeconds` definitions, which currently leads to `InvalidDefinition` errors. 
For the time being you can review the supported language features here https://github.com/localstack/localstack/pull/8779.


On another note, fixes concerning the evaluation of jsonpaths are also already on their way, and should resolve issues such as the one described of `index out of range`. I'll keep you updated on this.

**Comment by kevle1** [comment]
Thanks for looking into this @MEPalma

This is strange, it looks like if I create the state machine using the AWS CLI, with the same definition, it is created successfully. 

```
aws stepfunctions create-state-machine --endpoint http://localhost:4566 --name test-sfn --definition "$(cat sfn.json)" --role-arn arn:aws:iam::000000000000:role/state_machine_role

{
    "stateMachineArn": "arn:aws:states:ap-southeast-2:000000000000:stateMachine:test-sfn",
    "creationDate": 1693444405.956471
}
```

But if I create the same one using `tflocal` it fails with `InvalidDefinition: None`. 

```
terraform {
  required_version = "1.5.5"
}

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "4.64.0"
    }
  }
}

locals {
  region = "ap-southeast-2"
}

provider "aws" {
  profile = "local"
  region  = local.region
}

resource "aws_sfn_state_machine" "test_sfn" {
  name     = "test-state-machine"
  role_arn = aws_iam_role.state_machine_role.arn

  definition = jsonencode({
    "StartAt" : "CheckCondition",
    "States" : {
      "CheckCondition" : {
        "Type" : "Task",
        "Resource" : "arn:aws:lambda:ap-southeast-2:123456789012:function:placaeholder-check",
        "Next" : "CheckResult"
      },
      "CheckResult" : {
        "Type" : "Choice",
        "Choices" : [
          {
            "Variable" : "$.result.done",
            "BooleanEquals" : true,
            "Next" : "Send"
          },
          {
            "Variable" : "$.result.done",
            "BooleanEquals" : false,
            "Next" : "CheckCondition"
          }
        ]
      },
      "Send" : {
        "Type" : "Task",
        "Resource" : "arn:aws:lambda:ap-southeast-2:123456789012:function:placeholder-send",
        "End" : true
      }
    }
  })
}

resource "aws_iam_role" "state_machine_role" {
  name = "state_machine_role_test"

  assume_role_policy = jsonencode({
    Version = "2012-10-17",
    Statement = [
      {
        Action = "sts:AssumeRole",
        Effect = "Allow",
        Principal = {
          Service = "states.amazonaws.com"
        }
      }
    ]
  })
}
```

Have also tried it on Linux and no luck. Not sure where to go from here with debugging, need a more helpful error :(

**Comment by MEPalma** [comment]
We appreciate you sharing additional details with us! We have recently implemented some changes that are designed to address this issue. Please feel free to inform us if you encounter any similar problems moving forward.

**Comment by kevle1** [comment]
Thank you very much! Pulling the latest image and using the same flags, the state machine now is successfully deployed. Appreciate the speedy response, I owe you a coffee.
