### ISSUE TITLE
bug: request-parameters for adding a new header is ignored

### ISSUE THREAD

**Issue by marco-luzzara** [localstack/localstack#9013]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have an API Gateway with Lambda integration (AWS type) and I am trying to add a new header that should be passed to the lambda. I am doing it with the `--request-parameters` option:

```bash
awslocal apigateway put-integration \
        --rest-api-id "$_REST_API_ID" \
        --resource-id "$_RESOURCE_ID" \
        --http-method "$_HTTP_METHOD" \
        --type AWS \
        --integration-http-method POST \
        --uri "$_INTEGRATION_URI" \
        --passthrough-behavior WHEN_NO_MATCH \
        --request-parameters "{ \"integration.request.header.spring_cloud_function_definition\": \"'$_FUNCTION_NAME'\" }"
```

While this code perfectly works on AWS, Localstack ignores it and the lambda does not receive the header.

### Expected Behavior

The `--request-parameters` option should add the header to the integration request

### How are you starting LocalStack?

Custom (please describe below)

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

With the Localstack module of Testcontainer

### Environment

```markdown
- OS: Ubuntu 22.04
- LocalStack: 2.2.0
```

### Anything else?

I have created [this repo](https://github.com/marco-luzzara/aws-apigw-lambda-testing/tree/request_parameter_append_header) that reproduces the issue. You can verify it with [this test](https://github.com/marco-luzzara/aws-apigw-lambda-testing/blob/94f818ba067f669babfe2273c0659a40be58b7dd/src/test/java/org/example/ui/lambda/LambdaIT.java#L38).

**Comment by calvernaz** [comment]
Hi @marco-luzzara I have a sample that works in Localstack https://github.com/localstack/localstack-terraform-samples/tree/master/apigateway-aws-lambda.

The sample configures a request parameter header that is visible to the lambda payload as seen below.
```
Received event: {
"body-json": {},
"params": {
"path": {},
"querystring": {},
"header": {
"Host": "a5jary3xj2.execute-api.localhost.localstack.cloud:4566",
"User-Agent": "curl/7.86.0",
"Accept": "*/*",
 "x-localstack-tgt-api": "apigateway",
 "X-Forwarded-For": "127.0.0.1, a5jary3xj2.execute-api.localhost.localstack.cloud:4566",
 "x-localstack-edge": "http://a5jary3xj2.execute-api.localhost.localstack.cloud:4566",
 "X-Random-Header": "'X-Random-Value'"
}
 },
...
```

**Comment by marco-luzzara** [comment]
Hi @calvernaz , thanks for the working sample. It seems that the AWS adapter for spring cloud function loads the headers in a `Message` only when the input contains the `headers` key. This is the request mapping template I have used:

```vtl
{
  "headers": {
    #foreach($param in $input.params().header.keySet())
      "$param": "$util.escapeJavaScript($input.params().header.get($param))"
      #if($foreach.hasNext),#end
    #end
  },
  "body" : %s
}
```

Then, for each request, I have used the `format` function to customize the body, or keep the current one by specifying `$input.json('$')`. In any case, the mapping template is necessary. 

Thank you again
