### ISSUE TITLE
bug: Lambda - Failed to start runtime environment

### ISSUE THREAD

**Issue by alexey-tr** [localstack/localstack#9016]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Localstack failed to start runtime environment  because parameter validation failed:

```
localstack_main  | 2023-08-30T02:29:12.992  WARN --- [-g:$LATEST_0] l.s.l.i.runtime_environmen : Failed to start runtime environment for ID=347b7abb3b6dfaa3ff89b7e8370ab803 with: Parameter validation failed:
localstack_main  | Invalid length for parameter RoleSessionName, value: 1, valid min length: 2
localstack_main  | Traceback (most recent call last):
localstack_main  |   File "/opt/code/localstack/localstack/services/lambda_/invocation/runtime_environment.py", line 172, in start
localstack_main  |     self.runtime_executor.start(self.get_environment_variables())
localstack_main  |   File "/opt/code/localstack/localstack/services/lambda_/invocation/runtime_environment.py", line 92, in get_environment_variables
localstack_main  |     credentials = self.get_credentials()
localstack_main  |   File "/opt/code/localstack/localstack/services/lambda_/invocation/runtime_environment.py", line 268, in get_credentials
localstack_main  |     return sts_client.assume_role(
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/client.py", line 535, in _api_call
localstack_main  |     return self._make_api_call(operation_name, kwargs)
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/client.py", line 936, in _make_api_call
localstack_main  |     request_dict = self._convert_to_request_dict(
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/client.py", line 1007, in _convert_to_request_dict
localstack_main  |     request_dict = self._serializer.serialize_to_request(
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/validate.py", line 381, in serialize_to_request
localstack_main  |     raise ParamValidationError(report=report.generate_report())
localstack_main  | botocore.exceptions.ParamValidationError: Parameter validation failed:
localstack_main  | Invalid length for parameter RoleSessionName, value: 1, valid min length: 2
localstack_main  | 2023-08-30T02:29:12.994 DEBUG --- [-g:$LATEST_0] l.u.c.docker_sdk_client    : Stopping container: localstack-main-lambda-g-347b7abb3b6dfaa3ff89b7e8370ab803
localstack_main  | 2023-08-30T02:29:13.010 DEBUG --- [-g:$LATEST_0] l.s.l.i.runtime_environmen : Unable to shutdown runtime handler '347b7abb3b6dfaa3ff89b7e8370ab803'
```

### Expected Behavior

Localstack should start runtime environment and lambda

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker-compose up

```
version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack:2.2.0
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - SERVICES=sqs,lambda,s3
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./localstack:/etc/localstack"
      - "./resources:/resources"
    networks:
      - localstack-network
      
networks:
  localstack-network:
      name: localstack-network
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)
ready.d/init.sh

```
#!/bin/bash

awslocal lambda create-function \
    --region us-east-1 \
    --function-name g \
    --runtime=nodejs16.x \
    --timeout=100 \
    --memory-size 256 \
    --handler handleCLSPreprocessing.handler \
    --role arn:aws:iam::000000000000:role/lambda-role \
    --zip-file fileb:///resources/lambda.zip  \
    --environment file:///resources/environment.json

awslocal sqs create-queue \
    --region us-east-1 \
    --queue-name cls-preprocessing-fifo \
    --attributes '{"VisibilityTimeout": "600"}'

awslocal sqs create-queue \
    --region us-east-1 \
    --queue-name lambda-out \
    --attributes '{"VisibilityTimeout": "900"}'

awslocal sqs create-queue \
    --region us-east-1 \
    --queue-name lambda-in \
    --attributes '{"VisibilityTimeout": "600"}'

awslocal lambda create-event-source-mapping \
  --region us-east-1 \
  --function-name g \
  --batch-size 1 \
  --event-source-arn arn:aws:sqs::000000000000:lambda-in \
  --starting-position LATEST

awslocal s3 mb s3://bucket
```

index.js:
```
exports.handler = async (event, context) => {
    const record = event.Records ? event.Records[0] : event.records[0];
    let body = JSON.parse(record.body);
    console.log(`body=>${body}`);
};
```

environment.json:
```
{
  "Variables": {
    "ENVIRONMENT": "IT"
  }
}
```

After LocalStack started, send message to `lambda-in` queue:
```
aws sqs send-message --endpoint-url http://localhost:4566 --queue-url http://localhost:4566/000000000000/lambda-in --message-body file://message.json
```

### Environment

```markdown
- OS: macOS Ventura 13.5.1
- LocalStack: 2.2.0
```

### Anything else?

Similar setup works with LocalStack 1.4.0

**Comment by dfangl** [comment]
Thank you for reporting this. The error is caused by the function name - if you would use a function name with 2 characters minimum, it will work.

Of course this is still a bug, thank you for reporting it.

**Comment by raiatul14** [comment]
Hi, I'm fairly new to this project and would like to contribute to the fix of this issue. Can you please guide me on how to proceed further with it? I'm able to understand the issue going through the comments but still confused on the "Expected Behaviour" part.

**Comment by SkandaPrasad-S** [comment]
HI there! I would like to pick this up if no one else has at the moment!

**Comment by SkandaPrasad-S** [comment]
Hi @joe4dev ! thank you so much! I will get this going, will ask for your help if I run into any roadblocks

**Comment by raiatul14** [comment]
hi @joe4dev, thanks for the reply. The issue originates from(localstack/services/lambda_/invocation/execution_environment.py: get_credentials()):

`RoleSessionName=self.function_version.id.function_name`

and renaming it to:
`RoleSessionName=f"role_session_{self.function_version.id.function_name}"`

made your test pass.
However, I'm still not sure if this is what we are looking for a fix. Please let me know if there should be any changes. Thanks!

**Comment by kevcube** [comment]
@dfangl I'm seeing this error on localstack pro 2.3.1 with a function name that is more than 2 characters, I am creating 3 functions and I only see the error once I run the following command to set bucket notifications to one of the functions.

```sh
awslocal s3api put-bucket-notification-configuration --bucket "${BUCKET}" --notification-configuration file://infra/s3/sts-local-media-storage/s3-bucket-notifications.json
```

**Comment by joe4dev** [comment]
Thank you for your efforts @raiatul14 and @SkandaPrasad-S 🙏🙏 

The best way to do this is by matching the AWS behavior. I [adjusted](https://github.com/localstack/localstack/commit/fd330bc859c39d2447c4c985a817d6f47f11baed) the test to inspect the assumed role within the Lambda function. It reveals that AWS adds the suffix `@lambda_function` for the special case of a single-character function 💡 

 Can you please rebase upon the updated branch and run the renamed test `test_assume_role`?

**Comment by raiatul14** [comment]
@joe4dev I have raised a PR https://github.com/localstack/localstack/pull/9328. The tests are passing. Please let me know if any changes needs to be done. Thanks for guiding me!

**Comment by joe4dev** [comment]
Both solutions https://github.com/localstack/localstack/pull/9327 and https://github.com/localstack/localstack/pull/9328 fix the issue. Nice work @raiatul14 and @SkandaPrasad-S 👏 

It seems we're going double-track here. I would like to credit you both 👏👏 and suggest adding you both as co-authors when I squash the commit into master. Does that sound fair to you? 

The preflight checks of https://github.com/localstack/localstack/pull/9328 are green. @raiatul14 Can you please change the PR to target the master branch at localstack? I will then approve the CI, review it, and merge it with both of you as co-authors 🚀

**Comment by joe4dev** [comment]
Hi @alexey-tr 

Your reported issue has been fixed by community contributions from @raiatul14 and @SkandaPrasad-S 🚀 

Please pull the last LocalStack image and try again. We are looking forward to hearing your feedback.
