### ISSUE TITLE
localstack not installing and starting

### ISSUE THREAD

**Issue by ranvijayj** [localstack/localstack#902]
Installed localstaack npm etc. 

`pip install localstack`

then I do 

`localstack start`

Following are the errors

> 2018-08-16T11:51:55:INFO:localstack.services.install: Downloading and installing local Elasticsearch server. This may take some time.
2018-08-16T11:51:55:WARNING:localstack.utils.common: Unable to open zip file: /tmp/localstack.es.zip: File is not a zip file
2018-08-16T11:51:55:INFO:localstack.services.install: Unable to extract file, re-downloading ZIP archive: /tmp/localstack.es.zip
2018-08-16T11:51:55:INFO:localstack.services.install: Downloading and installing local Kinesis server. This may take some time.

Then I stopped it and started again getting this error:

> Starting mock ES service (http port 4578)...
> Starting mock Lambda service (http port 4574)...
> 2018-08-16T11:54:39:ERROR:localstack.services.generic_proxy: Error forwarding request: HTTPConnectionPool(host='127.0.0.1', port=4564): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8be462f5d0>: Failed to establish a new connection: [Errno 111] Connection refused',)) Traceback (most recent call last):
>   File "/home/ubuntu/.local/lib/python2.7/site-packages/localstack/services/generic_proxy.py", line 201, in forward
>     headers=forward_headers)
>   File "/home/ubuntu/.local/lib/python2.7/site-packages/requests/api.py", line 112, in post
>     return request('post', url, data=data, json=json, **kwargs)
>   File "/home/ubuntu/.local/lib/python2.7/site-packages/requests/api.py", line 58, in request
>     return session.request(method=method, url=url, **kwargs)
>   File "/home/ubuntu/.local/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
>     resp = self.send(prep, **send_kwargs)
>   File "/home/ubuntu/.local/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
>     r = adapter.send(request, **kwargs)
>   File "/home/ubuntu/.local/lib/python2.7/site-packages/requests/adapters.py", line 508, in send
>     raise ConnectionError(e, request=request)
> ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=4564): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8be462f5d0>: Failed to establish a new connection: [Errno 111] Connection refused',))

AND 

From inside the repo
I ran `docker-compose up -d`
got following error:

> ubuntu@ip-172-30-1-197:~/localstack$ sudo docker-compose up -d
> Traceback (most recent call last):
>   File "/usr/bin/docker-compose", line 9, in <module>
>     load_entry_point('docker-compose==1.8.0', 'console_scripts', 'docker-compose')()
>   File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
>     return get_distribution(dist).load_entry_point(group, name)
>   File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
>     return ep.load()
>   File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2229, in load
>     return self.resolve()
>   File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
>     module = __import__(self.module_name, fromlist=['__name__'], level=0)
>   File "/usr/lib/python2.7/dist-packages/compose/cli/main.py", line 17, in <module>
>     from ..bundle import get_image_digests
>   File "/usr/lib/python2.7/dist-packages/compose/bundle.py", line 14, in <module>
>     from .service import format_environment
>   File "/usr/lib/python2.7/dist-packages/compose/service.py", line 13, in <module>
>     from docker.utils import LogConfig
> ImportError: cannot import name LogConfig
> 

Solved the above by upgrading docker-py

now getting 

> > ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
> For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/

**Comment by aw230012** [comment]
I'm having similar issues.  I created a new EC2 instance for the free image of Windows 10.  I installed Python 3 so I could get pip.  I ran pip install localstack, no errors reported.  I bounced the EC2 instance.  Then when I try to run localstack start, I receive "'localstack' is not recognized as an internal or external command, operable program or batch file."

The documentation says it's as easy as running the pip install command.  What am I missing?

**Comment by muniyalr** [comment]
@ranvijayj Its to do with the docker-compose version used, Even i had the same issue, my Mac had `docker-compose version 1.8.1, build 878cff1` version installed and was throwing the error. Even the docker documentation suggests - 

`Version 2.1

An upgrade of version 2 that introduces new parameters only available with Docker Engine version 1.12.0+. Version 2.1 files are supported by Compose 1.9.0+. 
`

Installed with pip, and used it after setting the variable 
TMPDIR=/private$TMPDIR
$HOME/venv/bin/docker-compose up

i could get it working  with docker-compose version of 
`docker-compose version 1.22.0, build f46880f
docker-py version: 3.5.0
CPython version: 2.7.14
OpenSSL version: OpenSSL 1.0.2o  27 Mar 2018`

**Comment by whummer** [comment]
Thanks for reporting @ranvijayj , and thanks for providing a fix @muniyalr . Closing this issue, as it seems to be fixed - please re-open if the problem persists.
