### ISSUE TITLE
bug: describeTimeToLive should throw resource not found

### ISSUE THREAD

**Issue by matusfaro** [localstack/localstack#9030]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Calling `describeTimeToLive` to a non-existent table returns a result rather than throwing resource not found.

Test case pseudo-code:
```
try {
  dynamo.describeTimeToLive(new DescribeTimeToLiveRequest()
         .withTableName("non-existent-table"));
  fail();
} catch (ResourceNotFoundException ex) {
  // Pass
}
```

### Expected Behavior

Expecting call to throw 

### How are you starting LocalStack?

Custom (please describe below)

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    TestContainers from Java

### Environment

```markdown
- OS: MacOS
- LocalStack: 2.2.0
```

**Comment by ackdav** [comment]
Nice find @matusfaro - I reproduced it like this:
```
$ awslocal dynamodb describe-time-to-live --table-name test
{
    "TimeToLiveDescription": {
        "TimeToLiveStatus": "DISABLED"
    }
}

$ aws dynamodb describe-time-to-live --table-name test
An error occurred (ResourceNotFoundException) when calling the DescribeTimeToLive operation: Requested resource not found: Table: test not found
```

**Comment by matusfaro** [comment]
@ackdav Thanks for taking this on, my code relies on this exception to perform a create-if-not-exists logic.

**Comment by ackdav** [comment]
:+1: just merged a fix - please be aware that it takes a bit of time until the changes are available in the latest docker image. Hope that resolves the problem & your code runs as expected! :crossed_fingers:
