### ISSUE TITLE
bug: UploadPart & PutObject Return Non-Empty Body

### ISSUE THREAD

**Issue by RobertLeahy** [localstack/localstack#9032]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

UploadPart returns a non-empty body containing the following vacuous XML:

```
<?xml version='1.0' encoding='utf-8'?>
<UploadPartOutput />
```

PutObject has a similar issue:

```
<?xml version='1.0' encoding='utf-8'?>
<PutObjectOutput />
```

### Expected Behavior

UploadPart and PutObject should return an empty body as documented:

- https://docs.aws.amazon.com/AmazonS3/latest/API/API_UploadPart.html
- https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutObject.html

### How are you starting LocalStack?

With a `docker run` command

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run -d --rm --name=rleahy-localstack-2 localstack/localstack:2.2.0

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

Attempting to UploadPart via the libs3 C API

### Environment

- OS: Ubuntu 22.04
- LocalStack: 2.2.0

### Anything else?

The error in libs3 is raised here: https://github.com/bji/libs3/blob/287e4bee6fd430ffb52604049de80a27a77ff6b4/src/request.c#L279

libs3 succeeds when performing UploadPart and PutObject against Amazon S3 (and LocalStack 1.1.0).

Removing/modifying/avoiding the linked line (through modification to libs3) allows UploadPart and PutObject to succeed against LocalStack 2.

**Comment by RobertLeahy** [comment]
This also seems to apply to PutObject, I have updated the title and initial issue description accordingly.

**Comment by bentsku** [comment]
Hi @RobertLeahy and thank for your report! It seems the issue might be there for many API calls using the `PUT` method. Most of them should not return a body, but there are some exceptions like `CopyObject` for example. I'll be working on a fix and you should be updated soon on the progress. Thanks!
