### ISSUE TITLE
enhancement request: DynamoDB implement ReturnValuesOnConditionCheckFailure

### ISSUE THREAD

**Issue by sidekick-eimantas** [localstack/localstack#9040]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Enhancement description

When a DynamoDB item operation fails (PutItem, DeleteItem) etc, due to a conditional check failure, by specifying `ReturnValuesOnConditionCheckFailure="ALL_OLD"`, you can receive back the item which failed the check.

Localstack response for a DeleteItem with a failed condition check:
```
{
    "Error": {
        "Message": "The conditional request failed",
        "Code": "ConditionalCheckFailedException"
    },
    "ResponseMetadata": {
        "RequestId": "a7231c8c-8ebf-4d3e-a0df-882699b432b5",
        "HTTPStatusCode": 400,
        "HTTPHeaders": {
            "content-type": "application/json",
            "x-amzn-errortype": "ConditionalCheckFailedException",
            "content-length": "90",
            "x-amzn-requestid": "a7231c8c-8ebf-4d3e-a0df-882699b432b5",
            "x-amz-crc32": "2238609904",
            "connection": "close",
            "access-control-allow-origin": "*",
            "access-control-allow-methods": "HEAD,GET,PUT,POST,DELETE,OPTIONS,PATCH",
            "access-control-allow-headers": "authorization,cache-control,content-length,content-md5,content-type,etag,location,x-amz-acl,x-amz-content-sha256,x-amz-date,x-amz-request-id,x-amz-security-token,x-amz-tagging,x-amz-target,x-amz-user-agent,x-amz-version-id,x-amzn-requestid,x-localstack-target,amz-sdk-invocation-id,amz-sdk-request",
            "access-control-expose-headers": "etag,x-amz-version-id",
            "date": "Thu, 31 Aug 2023 23:26:53 GMT",
            "server": "hypercorn-h11"
        },
        "RetryAttempts": 0
    },
    "message": "The conditional request failed"
}
```

DynamoDB response for a DeleteItem with a failed condition check:
```
{
    "Error": {
        "Message": "The conditional request failed",
        "Code": "ConditionalCheckFailedException"
    },
    "ResponseMetadata": {
        "RequestId": "I8G1PLIEDA3C385FC62ULTVH6BVV4KQNSO5AEMVJF66Q9ASUAAJG",
        "HTTPStatusCode": 400,
        "HTTPHeaders": {
            "server": "Server",
            "date": "Thu, 31 Aug 2023 23:26:45 GMT",
            "content-type": "application/x-amz-json-1.0",
            "content-length": "177",
            "connection": "keep-alive",
            "x-amzn-requestid": "I8G1PLIEDA3C385FC62ULTVH6BVV4KQNSO5AEMVJF66Q9ASUAAJG",
            "x-amz-crc32": "3111827422"
        },
        "RetryAttempts": 0
    },
    "Item": {
        "owner_guid": {
            "S": "1234"
        },
        "LockID": {
            "S": "test"
        }
    }
}
```

### Anything else?

https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/dynamodb/table/delete_item.html

**Comment by tustvold** [comment]
It would appear the underlying issue is that dynamodb-local, which localstack uses, does not yet support this functionality

https://repost.aws/questions/QUNfADrK4RT6WHe61RzTK8aw/dynamodblocal-support-for-returnvaluesonconditioncheckfailure-for-single-write-operations

**Comment by emopti-jrufer** [comment]
This functionality was just released in DynamoDB Local. https://aws.amazon.com/about-aws/whats-new/2023/12/amazon-dynamodb-local-two-api-features/

**Comment by giograno** [comment]
Hi @sidekick-eimantas, thanks for opening this issue. As @emopti-jrufer correctly pointed out, the last release of DynamoDB Local supports now this feature. We added a test in [this PR](https://github.com/localstack/localstack/pull/9984) to verify the correct behavior in LocalStack. Please feel free to report any other issues. Thanks 🙏

**Comment by tustvold** [comment]
Running against the localstack docker containers I am not able to get this to work? It could be PEBCAC, but is this perhaps expected? Is the version of dynamodb-local pinned in the docker containers somehow?

**Comment by giograno** [comment]
@tustvold the `latest` Docker image should contain the latest dynamodb local that supports this feature.

**Comment by tustvold** [comment]
Can confirm this now works, not sure why this wasn't working for me before
