### ISSUE TITLE
bug: PROVIDER_OVERRIDE_STEPFUNCTIONS=v2 - `$$State.Name` not available for use

### ISSUE THREAD

**Issue by BrianMcBrayer** [localstack/localstack#9047]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Using `PROVIDER_OVERRIDE_STEPFUNCTIONS=v2`, I am passing `$$State.Name` as an input to one of my step functions.

I get the following error:
```
The JSONPath '$.State.Name' could not be found in the input '{"Execution": {"Id": "arn:aws:states:us-east-1:000000000000:execution:my-lambda:1892c755-c9f8-4d70-bd23-9672c2c41241", "Input": {"data": [1,2,3,4,5]}, "Name": "my-step-function", "RoleArn": "arn:aws:iam::000000000000:role/my-step-function", "StartTime": "16:50:47.640450"}, "StateMachine": {"Id": "TODO", "Name": "my-step-function"}, "State": null, "Task": null, "Map": null}'' at '[ASL] [gene] [PayloadBindingPathContextObj]: '(PayloadBindingPathContextObj| {'field': 'lambdaName', 'path_context_obj': '$.State.Name'})'.'
```

NOTE: I am correctly using `$$State.Name`, but the error log shows `$State.Name`

### Expected Behavior

It appears that `$$State` is `null` looking at the error output. I would expect that this would be populated with the state information as specified in https://docs.aws.amazon.com/step-functions/latest/dg/input-output-contextobject.html .

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

Sample step function definition (will need to point to a lambda):
```json
{
  "Comment": "My Step Function",
  "StartAt": "Lambda1",
  "States": {
    "Lambda1": {
      "Type": "Task",
      "Resource": "arn:aws:states:::lambda:invoke",
      "End": true,
      "ResultPath": null,
      "Parameters": {
        "FunctionName": "my-lambda",
        "Payload": {
          "lambdaName.$": "$$.State.Name"
        }
      }
    }
  }
}
```

I run localstack with docker-compose and just docker-compose up

### Environment

```markdown
- OS: Mac 13.5.1 Intel
- LocalStack: latest
```

### Anything else?

Thank you so much for all your efforts on localstack!

**Comment by MEPalma** [comment]
Thank you for continuing to compile bug reports for Step Functions v2! We were able to reproduce the issue and have recently merged some changes that should fix some scenarios for which the context object was not accessible through json path. Please do let us know if you continue to experience this issue
