### ISSUE TITLE
bug: S3 range requests where end < last return a 416, instead of returning the entire content.

### ISSUE THREAD

**Issue by sjperkins** [localstack/localstack#9076]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When a "range: bytes=start-end" header is supplied where end < start, localstack's S3 implementation returns a 416 response.

https://github.com/localstack/localstack/blob/279aea173dc56ab58fcae7f25d5a0e515c3aff6d/localstack/services/s3/utils.py#L208-L222

By contrast AWS returns the entire content.

### Expected Behavior

AWS Behaviour returns the entire content if end < start:

```bash
$ echo "Hello World" > test.txt
$  aws s3 cp test.txt s3://ratt-public-data   # Permissions needed to upload, but I've left test.txt here
$ curl  -H "range: bytes=1-0" https://ratt-public-data.s3.af-south-1.amazonaws.com/test.txt
Hello World
$ curl  -H "range: bytes=15-1" https://ratt-public-data.s3.af-south-1.amazonaws.com/test.txt
Hello World
```

### How are you starting LocalStack?

With the `localstack` script

### Steps To Reproduce

Localstack behaviour for a "range: bytes=1-0" header returns a 416 response:

```bash
$ echo "Hello World" > test.txt
$ localstack start -d
$ awslocal s3api create-bucket --bucket sample-bucket --region=us-east-1
{
    "Location": "/sample-bucket"
}
$ awslocal s3api put-object --bucket sample-bucket --key test.txt --body test.txt --region=us-east-1
{
    "ETag": "\"e59ff97941044f85df5297e1c302d260\""
}
$ curl -H "range: bytes=1-0" http://localhost:4566/sample-bucket/test.txt
<?xml version='1.0' encoding='utf-8'?>
<Error><Code>InvalidRange</Code><Message>The requested range is not satisfiable</Message><RequestId>aa8a2346-5dc0-4728-971c-a74839b3f1b0</RequestId><ActualObjectSize>12</ActualObjectSize><RangeRequested>bytes=1-0</RangeRequested></Error>
```

### Environment

```markdown
- OS: Ubuntu 20.04
- LocalStack: 2.2.0
```

**Comment by bentsku** [comment]
Hi @sjperkins and thanks a lot for your report. I've skimmed over the discussion in the linked PR, and as it's been mentioned, it seems AWS handling of range requests might be invalid. Nonetheless, LocalStack strives to achieve parity with AWS behaviour, so if they treat it as valid, so should we. 

The range behaviour and S3 implementation is currently based on `moto`, but we've been moving towards on our implementation and it is normally ready for use with a feature flag. In any case, I'll open a PR upstream to get this fix to be in-line with AWS, and also fix the codepath you've been mentioning above, as this concerns our new implementation. 

Thank you again for the report and the reproducible sample!

**Comment by sjperkins** [comment]
Thanks for looking into this @bentsku. I had a closer look at the [rfc](https://www.rfc-editor.org/rfc/rfc9110.html#name-range-requests) and it looks like a server may choose to ignore an invalid range request:

> **A server that supports range requests MAY ignore or reject a [Range](https://www.rfc-editor.org/rfc/rfc9110.html#field.range) header field that contains an invalid [ranges-specifier](https://www.rfc-editor.org/rfc/rfc9110.html#rule.ranges-specifier) ([Section 14.1.1](https://www.rfc-editor.org/rfc/rfc9110.html#range.specifiers))**, a [ranges-specifier](https://www.rfc-editor.org/rfc/rfc9110.html#rule.ranges-specifier) with more than two overlapping ranges, or a set of many small ranges that are not listed in ascending order,

This may explain AWS's behaviour

**Comment by bentsku** [comment]
Hello @sjperkins, the PR has now been merged and the behaviour you've seen should now be in line with AWS in our `latest` image tag. Thanks a lot again for the report!

**Comment by sjperkins** [comment]
Thanks for the fix!
