### ISSUE TITLE
bug: Cannot upload an image after using generate_presigned_post. Text file upload works

### ISSUE THREAD

**Issue by hsbgowd** [localstack/localstack#9094]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When i upload a jpg file, the upload fails with the below error message. However, there's no error when i upload this python script which is named as `test_upload.py`

```
Failed to upload image. Status code: 500. resp={"message": "Unexpected exception", "error": "400 Bad Request: The browser (or proxy) sent a request that this server could not understand.", "type": "ClientDisconnected"}
```

Here's my test code
```
#!/usr/bin/env python
import boto3
import datetime
import requests
import os
from botocore.client import Config

CRED = '\033[91m'
CGREEN  = '\33[32m'
CEND = '\033[0m'

# Configure your AWS credentials and S3 bucket information
aws_access_key = 'test'
aws_secret_key = 'test'
aws_bucket_name = 'my-bucket'
aws_region = 'us-east-1'
endpoint_url='http://localhost:4566/'

file_to_upload = "IMG_0600.jpg"
# file_to_upload = "test_upload.py"

# Initialize an S3 client
s3 = boto3.client('s3', 
        endpoint_url=endpoint_url,
        aws_access_key_id=aws_access_key, 
        aws_secret_access_key=aws_secret_key, 
        region_name=aws_region)

# s3 = boto3.client('s3', endpoint_url='http://localhost:4566', config=Config(signature_version='s3v4'))


# Specify the object (file) name and expiration time
file_name = os.path.basename(file_to_upload)
object_key = f'uploads/{file_name}'
expiration = datetime.timedelta(hours=1)  # Set the expiration time as needed
mime_type = "multipart/form-data"

# Generate a pre-signed POST form for uploading the object
try:
    post_data = s3.generate_presigned_post(
        Bucket=aws_bucket_name,
        Key=object_key,
        ExpiresIn=10000,  # expiration.total_seconds(),
        Fields={"Content-Type": mime_type},
        Conditions=[{"Content-Type": mime_type}], 
    )
except Exception as e:
    print("Error generating pre-signed POST form:", e)
    raise

# Return the pre-signed POST form data
print("Generated Pre-signed POST Form:")
print(post_data)

# Set the s3_post_url to the URL from the pre-signed POST form
s3_post_url = post_data["url"]

# Send the POST request with the form data and file
with open(file_to_upload, "rb") as f:
    files = {"file": (file_to_upload, f)}
    response = requests.post(s3_post_url, data=post_data["fields"], files=files)

# Check if the upload was successful
if response.status_code == 204:
    print("Image uploaded successfully.")
else:
    print(f"\n{CRED}Failed to upload image. Status code: {response.status_code}. resp={response.text}{CEND}")
```

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    localstack start -d

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal s3api create-bucket --bucket my-bucket

### Environment

```markdown
- OS: MAC M1
ProductName:            macOS
ProductVersion:         13.3.1
ProductVersionExtra:    (a)
BuildVersion:           22E772610a

- LocalStack: 2.2.0
```

**Comment by bentsku** [comment]
Hello @hsbgowd and thanks for your report!

Could you share LocalStack logs when this issue happens? You can have more verbose logs by starting LocalStack with the following environment variable: `LS_LOG=trace`. 

Also, could you share the size of your image? This issue sounds familiar, and looks like https://github.com/localstack/localstack/issues/6588

However, this has been fix a while ago, are you sure you are running LocalStack `2.2.0`? Could you share the git hash from LocalStack logs when you are starting it? It should looks like the following: 
```bash
LocalStack version: 2.2.0
LocalStack Docker container id: 9fbfeec45355
LocalStack build date: 2023-07-20
LocalStack build git hash: 2d70f768

2023-09-08T02:05:14.091  INFO --- [-functhread3] hypercorn.error            : Running on https://0.0.0.0:4566 (CTRL + C to quit)
2023-09-08T02:05:14.091  INFO --- [-functhread3] hypercorn.error            : Running on https://0.0.0.0:4566 (CTRL + C to quit)
Ready.
```
To update your LocalStack image, you can use `localstack update docker-images`, or `docker pull localstack/localstack:latest` or `localstack/localstack:2.2.0`. 

Also, quick tip from the sample given:
When setting the `mime_type` of the S3 object with a pre-signed POST, no need to set it to `multipart/form-data`, it should be the mime type of the actual object (like `image/jpg` in your case) and not the one of the request, not sure if that's on purpose. Otherwise, when you'll retrieve the file from your browser, it is going to interpret it as form data instead of the image you want.

**Comment by hsbgowd** [comment]
localstack was installed from poetry with the poetry package version set as below.
```
[tool.poetry.dev-dependencies]
localstack = "^2.2.0"
localstack-client = "^2.3"
```


Below is the git hash you requested. (i have removed log lines that i didnt think were essential)
```
$ localstack start

 💻 LocalStack CLI 2.2.0
Waiting for all LocalStack services to be ready
2023-09-08 03:06:15,433 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2023-09-08 03:06:15,434 INFO supervisord started with pid 16
2023-09-08 03:06:16,450 INFO spawned: 'infra' with pid 21
2023-09-08 03:06:17,471 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

LocalStack version: 1.3.1.dev
LocalStack Docker container id: eee7e4dc6b24
LocalStack build date: 2022-12-10
LocalStack build git hash: e3fc4965

Ready.
```

After updating the docker image as you suggested by running `localstack update docker-images`, I am not able to reproduce this issue. 

We may close this ticket. But before that, could you please advice why the installation of `localstack` and `localstack-client` was not sufficient to update the docker image?

**Comment by bentsku** [comment]
I believe the `localstack` package is only the CLI, and it will start the LocalStack image if you already have one, and might not try to pull the latest tag to avoid breaking your current setup.
But I agree that it should maybe suggest it to you? I'll send this feedback back to the team. 
Thanks for confirming it works!
