### ISSUE TITLE
bug: Special Character, particularly '%' makes S3 gives error

### ISSUE THREAD

**Issue by Chitranshagarwal2000** [localstack/localstack#9112]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When trying to put object in S3 with special characters (tested with %) makes S3 give `NoSuchKey` error.
Tried multiple times with % sign and got the error, but after changing the % to _ everything works

### Expected Behavior

Special characters should not create a problem 

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    I start localstack via docker-compose.yml file, below is the snippet for localstack
    
`version: '3.8'
services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "8080:8080"
    environment:
      - SERVICES=s3,sqs,secretsmanager,ssm
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - LS_LOG=trace
    volumes:
      - "./tmp/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"`
      
I am using Spring Boot version 3.1.1 and localstack version 2.2.0. I use software.amazon.awssdk.services.s3.S3Client to put requests in the bucket

`@Bean
    public S3Client s3Client() {
        return S3Client.builder()
                       .region(Region.of(region))
                       .forcePathStyle(true)
                       .credentialsProvider(StaticCredentialsProvider.create(AwsBasicCredentials.create("test", "test")))
                       .endpointOverride(URI.create("http://localhost:4566"))
                       .build();}`
    
    This is my S3Client bean which I use to put Object

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    `PutObjectRequest request = PutObjectRequest.builder().
                    bucket("my-bucket").key("A12345%John%Smith%%01%XYZ-ABC.pdf").build();
            s3Client.putObject(request, RequestBody.fromBytes(stream));`
            
Here stream is a byte array
            
From the logs I can see `localstack.request.aws     : AWS s3.PutObject => 404 (NoSuchKey)`
            
Also if I try to list the files in a folder I get the below error
            
`exception during call chain: Unable to parse response (not well-formed (invalid token): line 1, column 433), invalid XML received. Further retries may succeed:
b'<?xml version="1.0" encoding="UTF-8"?><ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Name>my-bucket</Name><Prefix>services/local/processor/pdf/</Prefix><MaxKeys>1000</MaxKeys><KeyCount>12</KeyCount><Delimiter>/</Delimiter><IsTruncated>false</IsTruncated><Contents></Contents></ListBucketResult>'` 

Removed unnecessary text.

Do pardon if any mistakes I made in creating this issue

### Environment

```markdown
- OS: MacOS 13.5.2
- LocalStack: 2.2..0
```

**Comment by bentsku** [comment]
Hello @Chitranshagarwal2000 and thank you for your report! 

Could you give it a try with our latest Docker image by using `localstack/localstack:latest` in your `docker-compose.yml` file and see if that resolve your issue? Some changes were made regarding handling of special characters which might have fixed your issue. If it does not, please say so and we will investigate further. Thank you!

**Comment by Chitranshagarwal2000** [comment]
Hello @bentsku - Thanks for reaching out, I tried this but still getting the issue. I am posting the logs from localstack as well and the code as well.

In the below image please check that I am doing a putObject operation but it fails saying that key does not exist
![image](https://github.com/localstack/localstack/assets/42971454/fab1094f-d32a-4165-b73e-1b14ba94cdcb)

`2023-09-12T16:34:43.370  INFO --- [   asgi_gw_2] localstack.request.aws     : AWS s3.PutObject => 404 (NoSuchKey); 000000000000/us-east-1; PutObjectRequest({'ACL': None, 'Bucket': 'my-bucket', 'CacheControl': None, 'ContentDisposition': None, 'ContentEncoding': None, 'ContentLanguage': None, 'ContentLength': 4009, 'ContentMD5': None, 'ContentType': 'application/octet-stream', 'ChecksumAlgorithm': None, 'ChecksumCRC32': None, 'ChecksumCRC32C': None, 'ChecksumSHA1': None, 'ChecksumSHA256': None, 'Expires': None, 'GrantFullControl': None, 'GrantRead': None, 'GrantReadACP': None, 'GrantWriteACP': None, 'Key': 'services/local/file-processor/clients/efi/eligibility/business-file/ABCD%MOHONAYI%JOHN%%01%XML.xml', 'Metadata': {}, 'ServerSideEncryption': None, 'StorageClass': None, 'WebsiteRedirectLocation': None, 'SSECustomerAlgorithm': None, 'SSECustomerKey': None, 'SSECustomerKeyMD5': None, 'SSEKMSKeyId': None, 'SSEKMSEncryptionContext': None, 'BucketKeyEnabled': None, 'RequestPayer': None, 'Tagging': None, 'ObjectLockMode': None, 'ObjectLockRetainUntilDate': None, 'ObjectLockLegalHoldStatus': None, 'ExpectedBucketOwner': None, 'Body': <_io.BufferedReader>}, headers={'Host': 'localhost:4566', 'amz-sdk-invocation-id': '13016f86-5037-a1e8-76e2-f8846405eede', 'amz-sdk-request': 'attempt=1; max=4', 'Authorization': 'AWS4-HMAC-SHA256 Credential=test/20230912/us-east-1/s3/aws4_request, SignedHeaders=amz-sdk-invocation-id;amz-sdk-request;content-length;content-type;host;x-amz-content-sha256;x-amz-date;x-amz-decoded-content-length, Signature=d4283012b30a042ec833e3af31c178e7a6a787ff0142ccfee272b27dfec3a3e4', 'Content-Type': 'application/octet-stream', 'Expect': '100-continue', 'User-Agent': 'aws-sdk-java/2.20.63 Mac_OS_X/13.5.2 OpenJDK_64-Bit_Server_VM/17.0.8.1+8-LTS Java/17.0.8.1 vendor/Amazon.com_Inc. io/sync http/Apache cfg/retry-mode/legacy', 'x-amz-content-sha256': 'STREAMING-AWS4-HMAC-SHA256-PAYLOAD', 'X-Amz-Date': '20230912T163443Z', 'x-amz-decoded-content-length': '3835', 'Content-Length': '4009', 'Connection': 'Keep-Alive', 'x-localstack-tgt-api': 's3', 'x-moto-account-id': '000000000000'}); NoSuchKey(The specified key does not exist., headers={'Content-Type': 'application/xml', 'Content-Length': '305', 'x-amz-request-id': 'b0fc5c5b-759f-49d8-89de-cba186abb966', 'x-amz-id-2': 's9lzHYrFp76ZVxRcpX9+5cjAnEH2ROuNkd2BHfIa6UkFVdtjf5mKR3/eTPFvsiP/XV/VLi31234='})`

Please see the logs from localstack above 

Also attaching the screenshot of localstack latest running 

![image](https://github.com/localstack/localstack/assets/42971454/b72597bf-308f-4c1d-97dd-3554a02334ad)

Please note that replacing the '%' with '_' works flawlessly 

I may be doing something stupid, please let me know if you think so too :)

**Comment by Chitranshagarwal2000** [comment]
Hello @bentsku,
Just wanted to ask were you able to reproduce this ?

**Comment by bentsku** [comment]
Hello @Chitranshagarwal2000, yes, I could reproduce, I'll start working on a fix now. Thanks again for the report!
