### ISSUE TITLE
bug: init-hooks not working on localstack:latest Docker image

### ISSUE THREAD

**Issue by glaubermd-leaf** [localstack/localstack#9127]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When mapping a init-hook shell script to `localstack:latest` Docker image, it does not detect the script, giving no hint or error messages.

If instead I use the `image: localstack/localstack:1.4`, it works.

### Expected Behavior

Detect and use the provided init-hook scripts when using Localstack `latest ` Docker image.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

Example `docker-compose.yml`:

```
version: '3.8'
services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack-latest
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_DEFAULT_REGION=sa-east-1
      - AWS_ACCESS_KEY_ID=000000000000
      - AWS_SECRET_KEY=test
      - AWS_BUCKET_NAME=bucket-local
      - LS_LOG=debug
      - DYNAMODB_OPTIMIZE_DB_BEFORE_STARTUP=0
      - DYNAMODB_DELAY_TRANSIENT_STATUSES=0
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./config/docker/localstack/init-dynamodb.sh:/etc/localstack/init/ready.d/01-dynamodb.sh"
```

Then run `docker-compose up -d` command.

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```
awslocal dynamodb create-table \
	--region sa-east-1 \
	--table-name my-store-dummy \
	--attribute-definitions AttributeName=id,AttributeType=S \
	--key-schema AttributeName=id,KeyType=HASH \
	--provisioned-throughput ReadCapacityUnits=1,WriteCapacityUnits=1
```

I validated that behavior by searching the logs, when running the `1.4` image:

```
$ docker-compose logs -f|egrep "(READY|ERROR|Init scripts discovered|ready\.d)"

localstack-1_4-local | 2023-09-12T22:43:32.022 DEBUG --- [  MainThread] localstack.runtime.init    : Init scripts discovered: {BOOT: [], START: [], READY: [Script(path='/etc/localstack/init/ready.d/01-dynamodb.sh', stage=READY, state=UNKNOWN)], SHUTDOWN: []}
localstack-1_4-local | 2023-09-12T22:43:33.247 DEBUG --- [  MainThread] localstack.runtime.init    : Running READY script /etc/localstack/init/ready.d/01-dynamodb.sh
```

Those lines are not shown when runing the `latest` image.

### Environment

```markdown
- OS: Ubuntu 23.04
- LocalStack: latest (Docker image)
```

### Anything else?

Documentation here might be outdated: https://docs.localstack.cloud/references/init-hooks/

**Comment by glaubermd-leaf** [comment]
Current "latest" points to the following digest: `Digest:sha256:9a25b0ecc49903885e8b2c90382b22863e5071dd7e0fe81a531f53f462884f8c`

**Comment by alexrashed** [comment]
Hi @glaubermd-leaf!

I just tried to reproduce your issue, where I performed the following tasks:
- Create a new `docker-compose.yml` with exactly your content.
- Execute the following commands:
  ```bash
  mkdir -p ./config/docker/localstack/
  cat <<EOF > ./config/docker/localstack/init-dynamodb.sh
  #!/bin/bash
  echo "Test"
  EOF
  chmod +x ./config/docker/localstack/init-dynamodb.sh
  docker-compose up
  ```

The script is then executed just fine:
```
...
Init scripts discovered: {BOOT: [], START: [], READY: [Script(path='/etc/localstack/init/ready.d/01-dynamodb.sh', stage=READY, state=UNKNOWN)], SHUTDOWN: []}
...
Running READY script /etc/localstack/init/ready.d/01-dynamodb.sh
Test
...
```

Could you maybe give us some more info on your scripts?
What are the permissions of your scripts?
Could you give us, for example. the output of `ls -al ./config/docker/localstack`?
Thanks!

**Comment by glaubermd-leaf** [comment]
Hi @alexrashed 

Sure, here they are:

```
ls -al ./config/docker/localstack
total 16
drwxrwxr-x 2 glauber glauber 4096 set 12 18:27 .
drwxrwxr-x 3 glauber glauber 4096 set  4 20:33 ..
-rwxrwxr-x 1 glauber glauber  336 set 12 18:27 init-dynamodb.sh
-rw-rw-r-- 1 glauber glauber  288 set  8 19:52 kms-seed.yml
```

I just changed from `localstack:1.4` to `localstack:latest` and it stopped working (my tests depend on a table that needs to exists before they start, so I got `"Cannot do operations on a non-existent table"`).

Anytime I execute my tests, I destroy the containers with `docker-compose up -d --force-recreate`. By doing this using the `latest` I see no log entry with `"Init scripts discovered"` text.

If I just change back to `localstack:1.4`, it starts working.

The init shell script starts with a shebang entry and is executable.

**Comment by alexrashed** [comment]
Hmm, okay, that's weird, especially because I ran some tests just today with the latest image. Are you sure your latest tag is up to date?
Could you please try to perform a pull and run your tests again just to make sure?
```
docker pull localstack/localstack 
```
Or you could use `docker-compose pull`.
Thanks!

**Comment by glaubermd-leaf** [comment]
I'm using `local-kms` also, I don't know if this could affect the behavior.
The complete `docker-compose.yml` file is:

```
version: '3.8'
services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack-latest-local
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_DEFAULT_REGION=sa-east-1
      - AWS_ACCESS_KEY_ID=000000000000
      - AWS_SECRET_KEY=test
      - AWS_BUCKET_NAME=bucket-local
      - LS_LOG=debug
      - DYNAMODB_OPTIMIZE_DB_BEFORE_STARTUP=0
      - DYNAMODB_DELAY_TRANSIENT_STATUSES=0
      - KMS_PROVIDER=local-kms
      - KMS_REGION=sa-east-1
      - KMS_ACCOUNT_ID=000000000000
      - KMS_SEED_PATH=/tmp/kms-seed.yml
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./config/docker/localstack/kms-seed.yml:/tmp/kms-seed.yml"
      - "./config/docker/localstack/init-dynamodb.sh:/etc/localstack/init/ready.d/01-dynamodb.sh"
```

To make it work, I just change this:
```
localstack:
    image: localstack/localstack:latest
    container_name: localstack-latest-local
```
to this:
```
localstack:
    image: localstack/localstack:1.4
    container_name: localstack-1_4-local
```

**Comment by glaubermd-leaf** [comment]
Now it works, after updating with `docker-compose pull` and using `localstack/localstack:latest`:
```
$ docker-compose pull
Pulling localstack ... done
```

It's now working as expected:
```
$ docker image ls |grep localstack
localstack/localstack                                                          latest    ecb0bc5127be   2 hours ago     1.13GB
localstack/localstack                                                          1.4       c14c35995461   7 months ago    1.87GB
localstack/localstack                                                          1.3       734ffaffb39d   9 months ago    1.84GB
``` 

Thank you :)
