### ISSUE TITLE
feature request: MemoryDB for Redis

### ISSUE THREAD

**Issue by viren-nadkarni** [localstack/localstack#9133]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Enhancement description

> MemoryDB for Redis is a durable, in-memory database service that delivers ultra-fast performance. It is purpose-built for modern applications with microservices architectures.
>
> MemoryDB is compatible with Redis, a popular open source data store, enabling you to quickly build applications using the same flexible and friendly Redis data structures, APIs, and commands that they already use today. With MemoryDB, all of your data is stored in memory, which enables you to achieve microsecond read and single-digit millisecond write latency and high throughput. 

https://docs.aws.amazon.com/memorydb/

**Comment by thrau** [comment]
MemoryDB is released in LocalStack Pro 3.1
