### ISSUE TITLE
bug: Localstack crashes everytime in around 1 hr

### ISSUE THREAD

**Issue by nirupamadsk** [localstack/localstack#9156]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm running localstack 2.2 in docker and using s3,lambda,kinesis,dynamodb,sns,cloudwatch in localstack. 
After every 1 hr or so, localstack crashes. 

Check the docker memory stats, it grows with 10+ GB every 10 minutes and eventually crashes with the following log messages. I suspect there is some sort of memory leak while handling DynamoDB or Kinesis stream GetRecords call. 

Please let me know how I can help more to find the root cause? This memory usage patten is very consistent with every run. 

<img width="1446" alt="image" src="https://github.com/localstack/localstack/assets/145045767/6559657f-7ef7-43e1-a720-2433aaf28e17">

`tRecords, contextId=60fc3a06-fc8f-4d1e-9607-cea359e138b6 Parsing auth header
2023-09-11 14:56:03 2023-09-11T20:55:28.758  INFO --- [functhread32] l.s.k.kinesis_mock_server  : 2023-09-11T20:55:28.306Z [WARNING] Your app's responsiveness to a new asynchronous event (such as a new connection, an upstream response, or a timer) was in excess of 100 milliseconds. Your CPU is probably starving. Consider increasing the granularity of your delays or adding more cedes. This may also be a sign that you are unintentionally running blocking I/O operations (such as File or InetAddress) without the blocking combinator.
2023-09-11 14:56:03 2023-09-11T20:55:37.372  INFO --- [functhread32] l.s.k.kinesis_mock_server  : 2023-09-11T20:55:36.154Z [WARNING] Your app's responsiveness to a new asynchronous event (such as a new connection, an upstream response, or a timer) was in excess of 100 milliseconds. Your CPU is probably starving. Consider increasing the granularity of your delays or adding more cedes. This may also be a sign that you are unintentionally running blocking I/O operations (such as File or InetAddress) without the blocking combinator.
2023-09-11 14:56:03 2023-09-11T20:55:39.507  INFO --- [functhread32] l.s.k.kinesis_mock_server  : [debug] kinesis.mock.cache.Cache 2023-09-11T20:55:37.348585Z contextId=12748db1-b235-4d79-a6c8-e75d713fa1cd, fileName=000000000000.json, path=../../../var/lib/localstack/tmp/state/kinesis Persisting stream data to disk
2023-09-11 14:56:03 2023-09-11T20:55:58.033  INFO --- [functhread32] l.s.k.kinesis_mock_server  : 2023-09-11T20:55:53.377Z [WARNING] Your app's responsiveness to a new asynchronous event (such as a new connection, an upstream response, or a timer) was in excess of 100 milliseconds. Your CPU is probably starving. Consider increasing the granularity of your delays or adding more cedes. This may also be a sign that you are unintentionally running blocking I/O operations (such as File or InetAddress) without the blocking combinator.
2023-09-11 14:56:04 LocalStack supervisor: localstack process (PID 15) returned with exit code -9
`

### Expected Behavior

Localstack should continue to run for more hours without consuming so much of memory.

### How are you starting LocalStack?

With a `docker run` command

### Steps To Reproduce

  localstack:
    container_name: "fdxs-localstack"
    image: "..."
    ports:
      - "4566:4566" # LocalStack Gateway
      - "4510-4559:4510-4559" # External services port range
      - "7050:7050" # Lambda debug
    env_file:
      - .env
    environment:
      - MAIN_CONTAINER_NAME=fdxs-localstack
      - LS_SERVICES=iam,cloudwatch,dynamodb,s3,sns,sts,kinesis,kms
      - LS_LOG=warn
      - DEBUG=1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - ".:/fdxs"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "${LOCALSTACK_VOLUME_DIR:-/var/lib/localstack}:/var/lib/localstack"
      - "./runlocal/localstack/scripts/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh"

### Environment

```markdown
- OS: Host - Apple M1 Pro, VenturaOS 13.5.2
- LocalStack: 2.2
```

**Comment by dfangl** [comment]
Hi @nirupamadsk !

Thank you for your detailed report. Would it be possible to share more information about the stack you are running, perhaps something to reproduce it?
You are absolutely right, that kind of memory consumption should not happen, but it can be rather service specific, so any information about the concrete stack you are able to provide can help.

**Comment by nirupamadsk** [comment]
Hello @dfangl 

Please find the versions I'm at: 
Docker version 4.22.0
Mac OS Ventura 13.5.2 Apple M1 Chip
Localstack: 2.2.1.dev

Using the localstack init hooks I'm installing iam,cloudwatch,dynamodb,s3,sns,sts,kinesis,kms through terraform mainly. 

After the bootup, the entire infra is left idle. The localstack memory usage keeps growing from the very first minute roughly at a rate of 100 MB/min and then after 50 mins or so, the localstack crashes when it overshoots the total assigned memory to docker (11 GB in my case). 

While it's being idle - no application workflows are executed and the only things that happen there are:
1. One app container is actively listening to kinesis.
2. Another container/Apache flink task manager is listening to DynamoDB streams. 

**Step 1**
I tried to simply hunt here by elimination method and stopped all other containers one after the other. So in the end, only localstack was running and it was still consuming the memory in a growing manner but at a slower pace this time, nearly 60 MB/min. Refer to `Step 1 Idle logs` down below.

**Step 2**
Then my next step was to not deploy the lambda function. This time there was even more quietness in the logs. Memory is still growing but at a rate of 30 MB/min for about 2-3 mins and then the memory usage stabilized around 714 MB for 2-3 mins and then kept growing again at the rate of 20-30 MB/min and then a stable pattern appears.. for 2-3 mins. These two patterns keeps going on in a loop. Overall memory is still growing but at a much slower pace. 100 MB over 15 Mins. A lot stable!

Only one recurring log message every 5 seconds.
`
fdxs-localstack  | 2023-09-18T19:08:57.282  INFO --- [functhread35] l.s.k.kinesis_mock_server  : [debug] kinesis.mock.cache.Cache 2023-09-18T19:08:57.274605Z contextId=b3ea7b46-40c3-464c-add9-739aba89017c, fileName=000000000000.json, path=../../../var/lib/localstack/tmp/state/kinesis Successfully persisted stream data
`
**Step 3**
Didn't deploy the lambda function but added the app container which listens to a kinesis stream. 
This time the additional log messages were about dynamodb.UpdateItem and dynamodb.GetRecords
Memory usage is still growing at a rate of 50MB/min when looking at a 5-minute window.


*Summary so far* 
1. Somewhat stable or very less memory growth when not deploying lambda and just localstack is running (no app containers) with sns,s3,cloudwatch,dynamodb,sts,kms,iam

2. 50/min growth rate when using localstack with the above services (no lambda) but using one app container which uses kinesis streams. 

3. 60 MB/min growth rate when using localstack with above services and lambda. No other app containers are running. 

4. 100 MB/min growth rate when using localstack with above services + lambda + app container polling kinesis + apache flink task manager polling DynamoDB stream. 


How can I assist more in this debugging? I'll be happy to jump on a zoom call and help reproduce. Please let me know. 





** Step 1 Idle logs** 
`
fdxs-localstack  | 2023-09-18T19:04:31.587  INFO --- [functhread54] l.s.k.kinesis_mock_server  : [debug] kinesis.mock.KinesisMockRoutes 2023-09-18T19:04:31.590964Z contextId=70e4346c-dcc4-4a4a-b2c0-0a6a13f476fb, x-amz-id-2=wo55xIzV3nZ941EO5E8929HWmCvlQtA5BMneVAZ2qNplJrmBxculg3ckM4TGC+7a4wcb9M7mxlgwNfvGC4LF0ZxxVaFLWbvi, x-amzn-RequestId=8efcbfd0-fa28-4cc2-8912-b774235106fd, action=GetRecords Assembled headers
fdxs-localstack  | 2023-09-18T19:04:31.587  INFO --- [functhread54] l.s.k.kinesis_mock_server  : [debug] kinesis.mock.KinesisMockRoutes 2023-09-18T19:04:31.590991Z x-amz-id-2=wo55xIzV3nZ941EO5E8929HWmCvlQtA5BMneVAZ2qNplJrmBxculg3ckM4TGC+7a4wcb9M7mxlgwNfvGC4LF0ZxxVaFLWbvi, contentType=application/x-amz-json-1.1, x-amzn-RequestId=8efcbfd0-fa28-4cc2-8912-b774235106fd, action=GetRecords, contextId=70e4346c-dcc4-4a4a-b2c0-0a6a13f476fb Parsing auth header
fdxs-localstack  | 2023-09-18T19:04:31.589  INFO --- [functhread54] l.s.k.kinesis_mock_server  : [debug] kinesis.mock.cache.Cache 2023-09-18T19:04:31.592882Z x-amz-id-2=wo55xIzV3nZ941EO5E8929HWmCvlQtA5BMneVAZ2qNplJrmBxculg3ckM4TGC+7a4wcb9M7mxlgwNfvGC4LF0ZxxVaFLWbvi, contentType=application/x-amz-json-1.1, x-amzn-RequestId=8efcbfd0-fa28-4cc2-8912-b774235106fd, action=GetRecords, contextId=70e4346c-dcc4-4a4a-b2c0-0a6a13f476fb Processing GetRecords request
fdxs-localstack  | 2023-09-18T19:04:31.589  INFO --- [functhread54] l.s.k.kinesis_mock_server  : [debug] kinesis.mock.cache.Cache 2023-09-18T19:04:31.593114Z x-amz-id-2=wo55xIzV3nZ941EO5E8929HWmCvlQtA5BMneVAZ2qNplJrmBxculg3ckM4TGC+7a4wcb9M7mxlgwNfvGC4LF0ZxxVaFLWbvi, contentType=application/x-amz-json-1.1, x-amzn-RequestId=8efcbfd0-fa28-4cc2-8912-b774235106fd, action=GetRecords, contextId=70e4346c-dcc4-4a4a-b2c0-0a6a13f476fb Successfully got records
fdxs-localstack  | 2023-09-18T19:04:31.591  INFO --- [functhread54] l.s.k.kinesis_mock_server  : [debug] kinesis.mock.KinesisMockRoutes 2023-09-18T19:04:31.595439Z contextId=47acbf23-278d-401a-998b-7aa4f13c13cb Received POST request
fdxs-localstack  | 2023-09-18T19:04:31.592  INFO --- [functhread54] l.s.k.kinesis_mock_server  : [debug] kinesis.mock.KinesisMockRoutes 2023-09-18T19:04:31.595749Z contextId=47acbf23-278d-401a-998b-7aa4f13c13cb, x-amz-id-2=hK7EhQ40EWdA0fdnlU9kKFzyZ1dgUL00lNp8pbgXBCcE4THiMc61pWINDzJVYjSqQ1I6mM7y782xJjt4yS2FKKuLgGtrK0ia, x-amzn-RequestId=602d7834-dda6-4f8a-ab35-85d7cb634bac, action=GetRecords Assembled headers
fdxs-localstack  | 2023-09-18T19:04:31.592  INFO --- [functhread54] l.s.k.kinesis_mock_server  : [debug] kinesis.mock.KinesisMockRoutes 2023-09-18T19:04:31.595781Z x-amz-id-2=hK7EhQ40EWdA0fdnlU9kKFzyZ1dgUL00lNp8pbgXBCcE4THiMc61pWINDzJVYjSqQ1I6mM7y782xJjt4yS2FKKuLgGtrK0ia, contentType=application/x-amz-json-1.1, x-amzn-RequestId=602d7834-dda6-4f8a-ab35-85d7cb634bac, action=GetRecords, contextId=47acbf23-278d-401a-998b-7aa4f13c13cb Parsing auth header
fdxs-localstack  | 2023-09-18T19:04:31.594  INFO --- [functhread54] l.s.k.kinesis_mock_server  : [debug] kinesis.mock.cache.Cache 2023-09-18T19:04:31.597789Z x-amz-id-2=hK7EhQ40EWdA0fdnlU9kKFzyZ1dgUL00lNp8pbgXBCcE4THiMc61pWINDzJVYjSqQ1I6mM7y782xJjt4yS2FKKuLgGtrK0ia, contentType=application/x-amz-json-1.1, x-amzn-RequestId=602d7834-dda6-4f8a-ab35-85d7cb634bac, action=GetRecords, contextId=47acbf23-278d-401a-998b-7aa4f13c13cb Processing GetRecords request
fdxs-localstack  | 2023-09-18T19:04:31.594  INFO --- [functhread54] l.s.k.kinesis_mock_server  : [debug] kinesis.mock.cache.Cache 2023-09-18T19:04:31.598004Z x-amz-id-2=hK7EhQ40EWdA0fdnlU9kKFzyZ1dgUL00lNp8pbgXBCcE4THiMc61pWINDzJVYjSqQ1I6mM7y782xJjt4yS2FKKuLgGtrK0ia, contentType=application/x-amz-json-1.1, x-amzn-RequestId=602d7834-dda6-4f8a-ab35-85d7cb634bac, action=GetRecords, contextId=47acbf23-278d-401a-998b-7aa4f13c13cb Successfully got records
fdxs-localstack  | 2023-09-18T19:04:31.598  INFO --- [functhread54] l.s.k.kinesis_mock_server  : [debug] kinesis.mock.KinesisMockRoutes 2023-09-18T19:04:31.601768Z contextId=8e9faec6-7c34-42c7-ba22-29765d1010bb Received POST request
fdxs-localstack  | 2023-09-18T19:04:31.598  INFO --- [functhread54] l.s.k.kinesis_mock_server  : [debug] kinesis.mock.KinesisMockRoutes 2023-09-18T19:04:31.602085Z contextId=8e9faec6-7c34-42c7-ba22-29765d1010bb, x-amz-id-2=NvG74I6/fIkxSCi2Ij+92wopTl3hT1Oi/yTHZTsdnnKcZjIRpUtL34iHW9ety8876ETuhYdQMZLdUIPp5TmlIOg2PZZhR525, x-amzn-RequestId=8b6205b9-60b4-4b48-985f-7dbb13232e22, action=GetRecords Assembled headers
fdxs-localstack  | 2023-09-18T19:04:31.598  INFO --- [functhread54] l.s.k.kinesis_mock_server  : [debug] kinesis.mock.KinesisMockRoutes 2023-09-18T19:04:31.602115Z x-amz-id-2=NvG74I6/fIkxSCi2Ij+92wopTl3hT1Oi/yTHZTsdnnKcZjIRpUtL34iHW9ety8876ETuhYdQMZLdUIPp5TmlIOg2PZZhR525, contentType=application/x-amz-json-1.1, x-amzn-RequestId=8b6205b9-60b4-4b48-985f-7dbb13232e22, action=GetRecords, contextId=8e9faec6-7c34-42c7-ba22-29765d1010bb Parsing auth header
fdxs-localstack  | 2023-09-18T19:04:31.600  INFO --- [functhread54] l.s.k.kinesis_mock_server  : [debug] kinesis.mock.cache.Cache 2023-09-18T19:04:31.603872Z x-amz-id-2=NvG74I6/fIkxSCi2Ij+92wopTl3hT1Oi/yTHZTsdnnKcZjIRpUtL34iHW9ety8876ETuhYdQMZLdUIPp5TmlIOg2PZZhR525, contentType=application/x-amz-json-1.1, x-amzn-RequestId=8b6205b9-60b4-4b48-985f-7dbb13232e22, action=GetRecords, contextId=8e9faec6-7c34-42c7-ba22-29765d1010bb Processing GetRecords request
fdxs-localstack  | 2023-09-18T19:04:31.600  INFO --- [functhread54] l.s.k.kinesis_mock_server  : [debug] kinesis.mock.cache.Cache 2023-09-18T19:04:31.604113Z x-amz-id-2=NvG74I6/fIkxSCi2Ij+92wopTl3hT1Oi/yTHZTsdnnKcZjIRpUtL34iHW9ety8876ETuhYdQMZLdUIPp5TmlIOg2PZZhR525, contentType=application/x-amz-json-1.1, x-amzn-RequestId=8b6205b9-60b4-4b48-985f-7dbb13232e22, action=GetRecords, contextId=8e9faec6-7c34-42c7-ba22-29765d1010bb Successfully got records
`
** Step 3 log messages** 
`
fdxs-localstack  | 2023-09-18T19:33:31.562  INFO --- [  asgi_gw_11] localstack.request.aws     : AWS kinesis.GetRecords => 200
fdxs-localstack  | 2023-09-18T19:33:31.562  INFO --- [functhread33] l.s.k.kinesis_mock_server  : [debug] kinesis.mock.cache.Cache 2023-09-18T19:33:31.562540Z x-amz-id-2=g8FFSr65RP0sVH9mts0FqML73Jbs3bhKtSlMYEF16By5IBbKohpPMH4+P7ymeuXwBUW5Ec0O3g0Cx3y6gcXQ6+NMLuKGU39P, contentType=application/x-amz-json-1.1, x-amzn-RequestId=5559d83f-06cb-4f24-92d1-6e3be8b596af, action=GetRecords, contextId=7b8a835e-17bb-4ca7-b6b9-ab0347138441 Successfully got records
fdxs-localstack  | 2023-09-18T19:33:31.565  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS kinesis.GetRecords => 200
fdxs-localstack  | 2023-09-18T19:33:32.428  INFO --- [functhread33] l.s.k.kinesis_mock_server  : [debug] kinesis.mock.cache.Cache 2023-09-18T19:33:32.428705Z contextId=4f1799b0-5632-4e5d-8b67-4703277c1e5f, fileName=000000000000.json, path=../../../var/lib/localstack/tmp/state/kinesis Persisting stream data to disk
fdxs-localstack  | 2023-09-18T19:33:32.431  INFO --- [functhread33] l.s.k.kinesis_mock_server  : [debug] kinesis.mock.cache.Cache 2023-09-18T19:33:32.432082Z contextId=4f1799b0-5632-4e5d-8b67-4703277c1e5f, fileName=000000000000.json, path=../../../var/lib/localstack/tmp/state/kinesis Successfully persisted stream data
fdxs-localstack  | 2023-09-18T19:33:32.457  INFO --- [  asgi_gw_12] localstack.request.http    : GET /_localstack/init/ready => 200
fdxs-localstack  | 2023-09-18T19:33:32.570  INFO --- [   asgi_gw_3] localstack.request.aws     : AWS dynamodb.UpdateItem => 200
fdxs-localstack  | 2023-09-18T19:33:32.573  INFO --- [   asgi_gw_7] localstack.request.aws     : AWS dynamodb.UpdateItem => 200
fdxs-localstack  | 2023-09-18T19:33:32.578  INFO --- [   asgi_gw_4] localstack.request.aws     : AWS dynamodb.UpdateItem => 200
fdxs-localstack  | 2023-09-18T19:33:32.581  INFO --- [   asgi_gw_9] localstack.request.aws     : AWS dynamodb.UpdateItem => 200
fdxs-localstack  | 2023-09-18T19:33:33.079  INFO --- [functhread33] l.s.k.kinesis_mock_server  : [debug] kinesis.mock.KinesisMockRoutes 2023-09-18T19:33:33.079303Z contextId=3f073a83-1f5b-47b6-ad11-e9b5a3b69783 Received POST request
fdxs-localstack  | 2023-09-18T19:33:33.079  INFO --- [functhread33] l.s.k.kinesis_mock_server  : [debug] kinesis.mock.KinesisMockRoutes 2023-09-18T19:33:33.080043Z contextId=3f073a83-1f5b-47b6-ad11-e9b5a3b69783, x-amz-id-2=giSpH36etByJI8fQp+kc1QiFA7kKaZsA04RrnqFs7++o/ztgTMTOiCI9BZGNHixVCLHYKFZHMwiBA5aGgCF/MSOcMSyXTCeG, x-amzn-RequestId=a9c30539-4ab2-4aca-99e8-4b8bcbf05448, action=GetRecords Assembled headers
fdxs-localstack  | 2023-09-18T19:33:33.080  INFO --- [functhread33] l.s.k.kinesis_mock_server  : [debug] kinesis.mock.KinesisMockRoutes 2023-09-18T19:33:33.080113Z x-amz-id-2=giSpH36etByJI8fQp+kc1QiFA7kKaZsA04RrnqFs7++o/ztgTMTOiCI9BZGNHixVCLHYKFZHMwiBA5aGgCF/MSOcMSyXTCeG, contentType=application/x-amz-json-1.1, x-amzn-RequestId=a9c30539-4ab2-4aca-99e8-4b8bcbf05448, action=GetRecords, contextId=3f073a83-1f5b-47b6-ad11-e9b5a3b69783 Parsing auth header
fdxs-localstack  | 2023-09-18T19:33:33.083  INFO --- [functhread33] l.s.k.kinesis_mock_server  : [debug] kinesis.mock.cache.Cache 2023-09-18T19:33:33.082242Z x-amz-id-2=giSpH36etByJI8fQp+kc1QiFA7kKaZsA04RrnqFs7++o/ztgTMTOiCI9BZGNHixVCLHYKFZHMwiBA5aGgCF/MSOcMSyXTCeG, contentType=application/x-amz-json-1.1, x-amzn-RequestId=a9c30539-4ab2-4aca-99e8-4b8bcbf05448, action=GetRecords, contextId=3f073a83-1f5b-47b6-ad11-e9b5a3b69783 Processing GetRecords request
fdxs-localstack  | 2023-09-18T19:33:33.083  INFO --- [functhread33] l.s.k.kinesis_mock_server  : [debug] kinesis.mock.cache.Cache 2023-09-18T19:33:33.082785Z x-amz-id-2=giSpH36etByJI8fQp+kc1QiFA7kKaZsA04RrnqFs7++o/ztgTMTOiCI9BZGNHixVCLHYKFZHMwiBA5aGgCF/MSOcMSyXTCeG, contentType=application/x-amz-json-1.1, x-amzn-RequestId=a9c30539-4ab2-4aca-99e8-4b8bcbf05448, action=GetRecords, contextId=3f073a83-1f5b-47b6-ad11-e9b5a3b69783 Successfully got records
fdxs-localstack  | 2023-09-18T19:33:33.090  INFO --- [functhread33] l.s.k.kinesis_mock_server  : [debug] kinesis.mock.KinesisMockRoutes 2023-09-18T19:33:33.090896Z contex
`

**Comment by dfangl** [comment]
Hi! Thanks for the more detailed description. I assume the lambdas have some event source mapping to the kinesis stream as well?

With #9134 we fixed some important cache misses, which might have an impact on your issue. Could you try pulling the latest image, and check if the memory consumption increase slowed down?

**Comment by nirupamadsk** [comment]
Hi @dfangl I tried pulling in the latest (d0db54bb), looks like the issue is fixed now. Memory usage is stable at around 1.3 GB after 5 mins. 

`
2023-09-20 10:11:10 LocalStack version: 2.2.1.dev
2023-09-20 10:11:11 LocalStack Docker container id: d6494e00d52f
2023-09-20 10:11:11 LocalStack build date: 2023-09-20
2023-09-20 10:11:11 LocalStack build git hash: d0db54bb
`

But just for my understanding, my previous localstack version was the same. I didn't notice the git hash last time though. When does the build version get updated?

**Comment by dfangl** [comment]
Great to hear that!
The `:latest` image gets updated with every build on master in this repository, so it can change quite a bit.
Only the pinned versions (like `2.2.0`) stay the same all the time.

I will close this now, if you have any more issues with the memory, please raise another issue so we can track it separately.
Thank you for reporting this!
