### ISSUE TITLE
Could not fill out survey

### ISSUE THREAD

**Issue by jordanboston** [localstack/localstack#916]
Went to [link](https://lambdastudy.typeform.com/login/?utm_source=typeform.com&utm_medium=typeform&utm_content=typeform-private&utm_campaign=kDUvvy) and got, **"Oops! This typeform is private."**

Not a real issue, just thought I'd mention it.  Thanks! 😃

**Comment by whummer** [comment]
Hi @jordanboston . The survey has been closed in the meantime (we have collected a sufficient amount of responses), but thanks for letting us know.

A draft of the paper discussing the findings can be found here: https://peerj.com/preprints/27005.pdf
