### ISSUE TITLE
Kinesis Error Probability - wrong HTTP Status code returned

### ISSUE THREAD

**Issue by applike-ss** [localstack/localstack#917]
When trying to setup our localstack to include the error probability to test our setup, we encountered an issue with it.
Regarding the documentation, on an error like ProvisionedThroughputExceededException it should return a 400 http status code, but instead we get a 200.
Due to this, our retries option set in the client does not work as expected and we can not test some scenarios.

**Comment by Jeremyyang920** [comment]
@applike-ss Super late response to this so not sure if relevant, but I actually just ran into this issue as well, and to get around that, I manually modified the file and mounted it to my docker container but putting in the volumes section.

- "$PWD/kinesis_listener.py:/opt/code/localstack/localstack/services/kinesis/kinesis_listener.py"

But I do wish it returned 400 by default and not a 200 ok.
