### ISSUE TITLE
bug: SNS issue when publishing to a disabled Mobile Push Endpoint

### ISSUE THREAD

**Issue by bentsku** [localstack/localstack#9173]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Issue reported on the community Slack channel:

> I’m trying to write some integration tests using SNS and localstack. I stumbled upon https://github.com/getmoto/moto/issues/2333 which prevents us from testing some flows. But this is not what I want to ask about here. (Actually I don’t know if this is issue is the same one in localstack and not sure if localstack uses moto under the hood, but the symptoms are the same)
> The issue I want to ask about is this. I have an SNS endpoint that I disable by setting its “Enabled” attribute to “false”. I verify that the attribute is set correctly using the aws cli. Now, when I try to send messages to this endpoint I expect the call to AmazonSNS#publish to throw [EndpointDisabledException](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-sns/classes/endpointdisabledexception.html) but it doesn’t. Instead, the message is, unexpectedly, published and I can see it using the aws cli.
> I looked around in the github project issues but found nothing related to this. I’m hopeful that I get some help here.

### Expected Behavior

SNS would raise the proper exception, and we could properly check idempotency of `CreatePlatformEndpoint` (there's an skipped test for it).

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    localstack start

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```python
response = sns_client.create_platform_application(
    Name=f"test-{short_uid()}",
    Platform="GCM",
    Attributes={"PlatformCredential": "123"},
)
platform_arn = response["PlatformApplicationArn"]
response = sns_client.create_platform_endpoint(
    PlatformApplicationArn=platform_arn, Token="test1",
)
endpoint_arn = response["EndpointArn"]

sns_client.set_endpoint_attributes(EndpointArn=endpoint_arn, Attributes={"Enabled": "false"})

# this should fail
sns_client.publish(TargetArn=endpoint_arn, MessageStructure="json", Message=json.dumps({"GCM": '{ "notification": {"title": "Title of notification", "body": "It works" } }'}))
```

### Environment

```markdown
- OS:macOS Ventura 13.5
- LocalStack: `latest`
```

**Comment by dogruis** [comment]
This is still an issue and Sns still publishes even though the endpoint is set to  `{"Enabled", "false"} `

**Comment by drymus** [comment]
> This is still an issue and Sns still publishes in the tests even though the endpoint is set to `{"Enabled", "false"} `. I work on java.

This works as expected for me in versions 2.3.1 and 3.1.0 of localstack. What version of the container are you using?
