### ISSUE TITLE
bug: Not so much a bug... Issue 7792 is broken

### ISSUE THREAD

**Issue by rcollette** [localstack/localstack#9182]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Issue #7792 is returning a 500 when trying to open.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal s3 mb s3://mybucket

### Environment

```markdown
- OS:
- LocalStack:
```

**Comment by keyvhinng** [comment]
Couldn't replicate. It works for me

**Comment by rcollette** [comment]
Yep looks like whatever it was is fixed now.
