### ISSUE TITLE
enhancement request: integrate localstack pro with features from former2

### ISSUE THREAD

**Issue by wweevv-johndpope** [localstack/localstack#9183]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Enhancement description

https://github.com/iann0036/former2
I click on this - install the widget it can scan through my lambda functions - and create a cloudformation script

if falls short on actually interacting with aws layers / python code in my lambda function.

I have scripts to go out and download this

something like this
```python

"""
Ensure you ahve already run `aws configure` and set up your access/secret keys then run this on your desktop
"""

import os
import sys
from urllib.request import urlopen
import zipfile
from io import BytesIO
import json
import tempfile
import boto3
import shutil

client = boto3.client("lambda")
session = boto3.Session(region_name='ap-south-1')

def getFunctions():
    funcs = []
    paginate = True
    next_marker = None

    while paginate:
        if next_marker:
            resp = client.list_functions(Marker=next_marker)
        else:
            resp = client.list_functions()

        for func in resp["Functions"]:
            funcs.append(func)

        if "NextMarker" in resp:
            next_marker = resp["NextMarker"]
        else:
            paginate = False

    functions_code_url = []

    for lambda_func in funcs:
        fn_code = client.get_function(FunctionName=lambda_func.get("FunctionName"))

        function_export_dir = os.path.join(os.getcwd(), lambda_func.get("FunctionName"))
        os.makedirs(function_export_dir, exist_ok=True)

        download_lambda_function_code(lambda_func.get("FunctionName"), fn_code.get("Code").get("Location"), function_export_dir)

        # get_layers(function_export_dir, lambda_func)
        print("S3 bucket:", fn_code.get("Code").get("Location"))

        functions_code_url.append({
            "FunctionName": lambda_func.get("FunctionName"),
            "FunctionCodeLocation": fn_code.get("Code").get("Location")
        })

    return functions_code_url
def get_layers(function_export_dir, lambda_func):
    # Export associated layers for each Lambda function and package them into a ZIP
    layers = client.list_layers(
        CompatibleRuntime=lambda_func.get('Runtime')
    )
    layers_info = []

    with tempfile.TemporaryDirectory() as temp_dir:
        for layer in layers['Layers']:
            layer_name = layer['LayerName']
            layer_arn = layer['LayerArn']
            layer_info = {
                'LayerName': layer_name,
                'LayerArn': layer_arn
            }
            # Export layer details to JSON file in the subdirectory
            with open(os.path.join(function_export_dir, f'layer_{layer_name}.json'), 'w') as layers_file:
                json.dump(layer_info, layers_file, indent=2)

            # Extract the layer name and version from the ARN
            layer_name_parts = layer_arn.split(':')[-1].split(':')
            layer_version = layer_name_parts[-1]

            # Download the layer content to the temporary directory
            print("layer_arn:",layer_arn)
            response = client.get_layer_version_by_arn( Arn=layer_arn )
            #arn:aws:lambda:ap-south-1:711304199600:layer:AWS-Loggin
            layer_zip_filename = os.path.join(temp_dir, f'{layer_name}_{layer_version}.zip')
            with open(layer_zip_filename, 'wb') as layer_zip_file:
                layer_zip_file.write(response['Content'].read())
            print(f"Downloaded layer '{layer_name}' (version {layer_version}) to '{layer_zip_filename}'.")

        # Package all layers into a ZIP file
        layers_zip_filename = os.path.join(function_export_dir, 'layers.zip')
        shutil.make_archive(layers_zip_filename[:-4], 'zip', temp_dir)
        print(f"Packaged layers into '{layers_zip_filename}'.")


def download_lambda_function_code(fn_name, fn_code_link, dir_path):
    # Create a directory for the Lambda function
    function_path = os.path.join(dir_path, fn_name)
    os.makedirs(function_path, exist_ok=True)

    # Download the Lambda function code from the S3 location
    with urlopen(fn_code_link) as lambda_extract:
        with zipfile.ZipFile(BytesIO(lambda_extract.read())) as zfile:
            zfile.extractall(function_path)

if __name__ == "__main__":
    inp = sys.argv[1:]
    print("Destination folder:", inp)
    
    if inp and os.path.exists(inp[0]):
        dest = os.path.abspath(inp[0])
        fc = getFunctions()
        print(f"There are {len(fc)} Lambda functions")
        for item in fc:
            print(f"Download {item.get('FunctionName')}")
            try:
                download_lambda_function_code(item.get("FunctionName"), item.get("FunctionCodeLocation"), dest)
            except Exception as e:
                print("🔥:", e)
    else:
        print("Destination folder doesn't exist")

```

### 🧑‍💻 Implementation

this software - should be able to add on the smarts from former2 - and get my lambdas from an existing infrastructure.

### Anything else?

that's it.

**Comment by alexrashed** [comment]
Hi @wweevv-johndpope!
Unfortunately, I'm not really sure what you mean exactly.
So former2 seems to be a tool which generate CloudFormation or Terraform templates from existing AWS resources.
And you would like to use former2 against LocalStack, is that correct?
LocalStack itself really implements AWS on an API level, so if you can redirect former2 to LocalStack (f.e. by setting some kind of endpoint URL), it might just work out of the box.
So I'm afraid it seems that this is the wrong place to ask for the enhancement request.
Would you mind asking in the `former2` repo if it is possible to redirect to a local instance instead of always using the production AWS environments?

**Comment by wweevv-johndpope** [comment]
backing up - 
the problem I want to solve
- I built 80 lambda functions in the cloud - 
- now I need testing...
- I understand this backwards - but thats my usecase.
- can localstack introspec the production environments to download anything? I don't think so. 
- instead - former2 can - and Im suggesting this as an enhancement. or you need to make the ui clearer on how to import stuff.

**Comment by alexrashed** [comment]
Hmm, okay, but the result of former2 is an Infrastructure as Code snippet (like terraform or cloudformation).
You can just use this code and run it against localstack.

- Here are the docs on how to use Terraform with LocalStack: https://docs.localstack.cloud/user-guide/integrations/terraform/
- And here are our docs on how to use CloudFormation with LocalStack: https://docs.localstack.cloud/user-guide/aws/cloudformation/

So the process would be:
- Use former2 to generate the code from your AWS environment.
- Use that code and run it against LocalStack to recreate your AWS environment in LocalStack.

Please let us know if this answers your question.

**Comment by wweevv-johndpope** [comment]
thanks for helpful response. I will give it a whirl tomorrow.  
the ticket represents an enhancement to localstack - where you can integrate (cherry pick) this technology. scope may only be lambda functions with different layers etc. the cloud formation import should give me some mileage - thanks again.

**Comment by iann0036** [comment]
Hey there,

Former2 author here 👋

I concur with @alexrashed's suggestion. LocalStack can use the Former2 output as its own CFN/TF template, so you can take the generated template and load it in.

The actual source code from the Lambda functions would indeed have to be re-downloaded and uploaded into a LocalStack S3 bucket - but it looks like you've already seen that and are across it.

Remember to review the generated templates for sensitive data if present, and that minor template bugs can occur. Also note that LocalStack has non-complete coverage of all possible resources - check [here](https://docs.localstack.cloud/user-guide/aws/feature-coverage/) for more info.

**Comment by alexrashed** [comment]
> Remember to review the generated templates for sensitive data if present, and that minor template bugs can occur.

I would say sensitive data isn't really an issue if everything runs locally. 😛
But yes, the coverage is a good point. LocalStack supports a lot, but not all operations and resources provided in production AWS.
