### ISSUE TITLE
bug: Web App won't let us use Pro Features

### ISSUE THREAD

**Issue by kbret1** [localstack/localstack#9188]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We have been using pro version for over a year.   The localstack container validates our license and everything is created.  As of yesterday, when any of our developers log into app.localstack.com it states we need a Pro license for a bunch of features.    When we view our Account it says our license is Pro and valid.  All of API keys are correct.

The web app makes a call to: https://api.localstack.cloud/v1/plans/subscriptions and the response has "status": "active", "name": "Pro Edition - Individual Developer (yearly license)", "current_period_end": 1716186097, "current_period_start": 1684563697, etc

### Expected Behavior

This web app should validate our Pro license and allow access to all the features that have been available.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    export LOCALSTACK_API_KEY=<xxxxxxx>
    docker run localstack/localstack
    Log in to app.localstack.com and go to resource browser

### Environment

```markdown
- OS: NA
- LocalStack Pro: latest image
```

**Comment by thrau** [comment]
thanks for the report @kbret1, @lukqw pushed a fix and it should work now!

**Comment by kbret1** [comment]
Yes, I confirm it is working now. Thank you!
