### ISSUE TITLE
S3 HTTP 500 error when max-keys=0

### ISSUE THREAD

**Issue by sdnakhla** [localstack/localstack#919]
I am testing code leveraging Apache Camel that is to read and write from an S3 bucket.  When using localstack, I get an HTTP 500 error when the max-keys parameter is set to 0.  I have an Nginx proxy in front of localstack so I can see the traffic and return calls.  The calls and errors I see in the logs look like this:

> 172.18.0.1 - - [05/Sep/2018:16:22:13 +0000]  500 "GET /mytestbucket/?max-keys=0&encoding-type=url HTTP/1.1" 291 "-" "aws-sdk-java/1.11.301 Mac_OS_X/10.13.6 Java_HotSpot(TM)_64-Bit_Server_VM/25.144-b01 java/1.8.0_144" "-"
> 172.18.0.1 - - [05/Sep/2018:16:22:13 +0000]  500 "GET /mytestbucket/?max-keys=0&encoding-type=url HTTP/1.1" 291 "-" "aws-sdk-java/1.11.301 Mac_OS_X/10.13.6 Java_HotSpot(TM)_64-Bit_Server_VM/25.144-b01 java/1.8.0_144" "-"
> 172.18.0.1 - - [05/Sep/2018:16:22:13 +0000]  500 "GET /mytestbucket/?max-keys=0&encoding-type=url HTTP/1.1" 291 "-" "aws-sdk-java/1.11.301 Mac_OS_X/10.13.6 Java_HotSpot(TM)_64-Bit_Server_VM/25.144-b01 java/1.8.0_144" "-"
> 172.18.0.1 - - [05/Sep/2018:16:22:13 +0000]  500 "GET /mytestbucket/?max-keys=0&encoding-type=url HTTP/1.1" 291 "-" "aws-sdk-java/1.11.301 Mac_OS_X/10.13.6 Java_HotSpot(TM)_64-Bit_Server_VM/25.144-b01 java/1.8.0_144" "-"
> 

Within my Java logs, I see the following output from the AWS SDK when the Camel Route attempts to start:

> 12:21:56,828 DEBUG [com.amazonaws.http.AmazonHttpClient] (MSC service thread 1-7) Retriable error detected, will retry in 96ms, attempt number: 1
> 12:21:56,929 DEBUG [com.amazonaws.auth.AWS4Signer] (MSC service thread 1-7) AWS4 Canonical Request: '"GET
> /mytestbucket/
> encoding-type=url&max-keys=0
> amz-sdk-invocation-id:93f48bbc-72a3-f042-196e-0ce4fc295f35
> amz-sdk-retry:2/96/490
> content-type:application/octet-stream
> host:mdmx.odyssi.net
> user-agent:aws-sdk-java/1.11.301 Mac_OS_X/10.13.6 Java_HotSpot(TM)_64-Bit_Server_VM/25.144-b01 java/1.8.0_144
> x-amz-content-sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
> x-amz-date:20180905T162156Z
> 
> amz-sdk-invocation-id;amz-sdk-retry;content-type;host;user-agent;x-amz-content-sha256;x-amz-date
> e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
> 12:21:56,929 DEBUG [com.amazonaws.auth.AWS4Signer] (MSC service thread 1-7) AWS4 String to Sign: '"AWS4-HMAC-SHA256
> 20180905T162156Z
> 20180905/us-east-1/s3/aws4_request
> 4c48136bb09d6fbf91ffd42df68832a363eaebce285297feccbf0042f703d5c2"
> 12:21:56,944 DEBUG [com.amazonaws.services.s3.internal.S3ErrorResponseHandler] (MSC service thread 1-7) Failed in parsing the error response : <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
> <title>500 Internal Server Error</title>
> <h1>Internal Server Error</h1>
> <p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>
> : com.ctc.wstx.exc.WstxUnexpectedCharException: Unexpected character '"' (code 34) in DOCTYPE declaration; expected a space between public and system identifiers
>  at [row,col {unknown-source}]: [1,55]
> 	at com.ctc.wstx.sr.StreamScanner.throwUnexpectedChar(StreamScanner.java:653)
> 	at com.ctc.wstx.sr.BasicStreamReader.startDTD(BasicStreamReader.java:2569)
> 	at com.ctc.wstx.sr.BasicStreamReader.nextFromPrologBang(BasicStreamReader.java:2485)
> 	at com.ctc.wstx.sr.BasicStreamReader.nextFromProlog(BasicStreamReader.java:2144)
> 	at com.ctc.wstx.sr.BasicStreamReader.next(BasicStreamReader.java:1181)
> 	at com.amazonaws.services.s3.internal.S3ErrorResponseHandler.createException(S3ErrorResponseHandler.java:115)
> 	at com.amazonaws.services.s3.internal.S3ErrorResponseHandler.handle(S3ErrorResponseHandler.java:64)
> 	at com.amazonaws.services.s3.internal.S3ErrorResponseHandler.handle(S3ErrorResponseHandler.java:51)
> 	at com.amazonaws.http.AwsErrorResponseHandler.handleAse(AwsErrorResponseHandler.java:50)
> 	at com.amazonaws.http.AwsErrorResponseHandler.handle(AwsErrorResponseHandler.java:38)
> 	at com.amazonaws.http.AwsErrorResponseHandler.handle(AwsErrorResponseHandler.java:24)
> 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1612)
> 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1302)
> 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1056)
> 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743)
> 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717)
> 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
> 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
> 	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
> 	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
> 	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4330)
> 	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4277)
> 	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4271)
> 	at com.amazonaws.services.s3.AmazonS3Client.listObjects(AmazonS3Client.java:835)
> 	at org.apache.camel.component.aws.s3.S3Endpoint.doStart(S3Endpoint.java:112)
> 	at org.apache.camel.support.ServiceSupport.start(ServiceSupport.java:61)
> 	at org.apache.camel.util.ServiceHelper.startService(ServiceHelper.java:75)
> 	at org.apache.camel.impl.RouteService.doWarmUp(RouteService.java:157)
> 	at org.apache.camel.impl.RouteService.warmUp(RouteService.java:145)
> 	at org.apache.camel.impl.DefaultCamelContext.doWarmUpRoutes(DefaultCamelContext.java:3949)
> 	at org.apache.camel.impl.DefaultCamelContext.safelyStartRouteServices(DefaultCamelContext.java:3856)
> 	at org.apache.camel.impl.DefaultCamelContext.doStartOrResumeRoutes(DefaultCamelContext.java:3642)
> 	at org.apache.camel.impl.DefaultCamelContext.doStartCamel(DefaultCamelContext.java:3494)
> 	at org.apache.camel.impl.DefaultCamelContext.access$000(DefaultCamelContext.java:209)
> 	at org.apache.camel.impl.DefaultCamelContext$2.call(DefaultCamelContext.java:3253)
> 	at org.apache.camel.impl.DefaultCamelContext$2.call(DefaultCamelContext.java:3249)
> 	at org.apache.camel.impl.DefaultCamelContext.doWithDefinedClassLoader(DefaultCamelContext.java:3272)
> 	at org.apache.camel.impl.DefaultCamelContext.doStart(DefaultCamelContext.java:3249)
> 	at org.apache.camel.support.ServiceSupport.start(ServiceSupport.java:61)
> 	at org.apache.camel.impl.DefaultCamelContext.start(DefaultCamelContext.java:3165)
> 	at org.apache.camel.impl.DefaultCamelContext$Proxy$_$$_WeldClientProxy.start(Unknown Source)
> 	at org.apache.camel.cdi.CdiCamelExtension.afterDeploymentValidation(CdiCamelExtension.java:425)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:95)
> 	at org.jboss.weld.injection.MethodInvocationStrategy$SpecialParamPlusBeanManagerStrategy.invoke(MethodInvocationStrategy.java:144)
> 	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:330)
> 	at org.jboss.weld.event.ExtensionObserverMethodImpl.sendEvent(ExtensionObserverMethodImpl.java:123)
> 	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:308)
> 	at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:286)
> 	at org.jboss.weld.util.Observers.notify(Observers.java:172)
> 	at org.jboss.weld.event.ObserverNotifier.notifySyncObservers(ObserverNotifier.java:285)
> 	at org.jboss.weld.event.ObserverNotifier.notify(ObserverNotifier.java:273)
> 	at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:177)
> 	at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:171)
> 	at org.jboss.weld.bootstrap.events.AbstractContainerEvent.fire(AbstractContainerEvent.java:53)
> 	at org.jboss.weld.bootstrap.events.AbstractDeploymentContainerEvent.fire(AbstractDeploymentContainerEvent.java:35)
> 	at org.jboss.weld.bootstrap.events.AfterDeploymentValidationImpl.fire(AfterDeploymentValidationImpl.java:28)
> 	at org.jboss.weld.bootstrap.WeldStartup.validateBeans(WeldStartup.java:499)
> 	at org.jboss.weld.bootstrap.WeldBootstrap.validateBeans(WeldBootstrap.java:93)
> 	at org.jboss.as.weld.WeldStartService.start(WeldStartService.java:97)
> 	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1736)
> 	at org.jboss.msc.service.ServiceControllerImpl$StartTask.execute(ServiceControllerImpl.java:1698)
> 	at org.jboss.msc.service.ServiceControllerImpl$ControllerTask.run(ServiceControllerImpl.java:1556)
> 	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
> 	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1985)
> 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1487)
> 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1378)
> 	at java.lang.Thread.run(Thread.java:748)

Also, I see the same HTTP 500 when trying to access that URL with the max-keys=0 parameter via a browser.  Increasing max-keys to 1 or higher results in a 200 with the expected XML being returned.

I am using the localstack Docker image to start my localstack environment.

**Comment by dvh312** [comment]
+1 here. The error is from moto.

https://github.com/spulec/moto/blob/850496f29a66b109b87f9d26d4c5b8456b3b195f/moto/s3/responses.py#L382

**Comment by dvh312** [comment]
+1 here. The error is from moto.

https://github.com/spulec/moto/blob/850496f29a66b109b87f9d26d4c5b8456b3b195f/moto/s3/responses.py#L382

This command will not work if you have some files in S3. Empty bucket works.
aws s3api list-objects --bucket=mybucket --endpoint-url http://localhost:4572 --page-size 0

**Comment by whummer** [comment]
Thanks for reporting @sdnakhla @dvh312 . This should be fixed in #1863 . Can you please give it a try with the latest version of the Docker image? Please report here if the problem persists.

**Comment by mseelye-gravie** [comment]
@whummer I'm using the latest localstack and when using max-keys with a 0 I'm getting some set of keys back instead of the expected 0 keys.  Did this change make it so sending 0 for max-keys works, but returns keys? In testing against aws s3 sending max-keys 0 returns 0 keys.  

Wondering if someone else can confirm what I'm seeing.
