### ISSUE TITLE
Why not add all localstack services default ports to lambda?

### ISSUE THREAD

**Issue by mhmoudgmal** [localstack/localstack#923]
It's very likely that lambda will talk to other services, so does it make sense to include all other localstack services default ports to lambda while creating the container? 

https://github.com/localstack/localstack/blob/fcad0c1f60487734c8546619eefc8aafbbdf9409/localstack/services/awslambda/lambda_executors.py#L235

If it does make sense, I can submit a PR for this.
Thanks!

**Comment by whummer** [comment]
Thanks for this suggestion. I'm tempted to close this request, as it hasn't received much uptake from the community over quite some time. Also, as the number of services is growing, this would result in ever more variables to be passed to the Lambda environment.

Also, mid-term things seem to be moving into the direction that we're going to use a single entrypoint for the services, which we're already experimenting with in LocalStack Pro.

Please do continue to post suggestions for improvement, though - always appreciated! Thanks
