### ISSUE TITLE
bug: DB parameter groups not working

### ISSUE THREAD

**Issue by jandroav** [localstack/localstack#9231]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am setting log_bin_trust_function_creators with Terraform as a DB parameter group:

```
resource "aws_db_parameter_group" "aurora" {
  name   = "aurora-pg"
  family = "mysql8.0"
  parameter {
    name  = "autocommit"
    value = 1
  }
  parameter {
    name  = "automatic_sp_privileges"
    value = 1
  }
  parameter {
    name  = "log_bin_trust_function_creators"
    value = "1"
  }
}
```

But after the instance creation, `log_bin_trust_function_creators` is still **OFF**:

![image](https://github.com/localstack/localstack/assets/67458478/228752a8-c939-4a8e-b9ed-e12b31bb9391)

### Expected Behavior

`aws_db_parameter_group` needs to set parameters on the DB

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

`localstack start -d `

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```
tflocal init 
tflocal apply  
awslocal rds describe-db-instances --db-instance-identifier aurora-mysql-primary-cluster-instance 
awslocal rds describe-db-parameters --db-parameter-group-name aurora-pg 
```

### Environment

```markdown
- OS: macOS Ventura 13.6
- LocalStack: 2.2.0
```

**Comment by jandroav** [comment]
@steffyP This can be closed as resolved by localstack 3.0 right?

**Comment by steffyP** [comment]
Hi @jandroav, 

it seems like the issue has been resolved for you? 

For `postgres` the DB parameters should be applied indeed, but for other engine types you will probably still only a mocked behavior (e.g. the `describe-db-parameters` will return the correct result, but the parameters are not actually applied to the running database). 
Starting from LocalStack 3.0 we changed the default behavior for `mysql` engines, e.g. a real mysql-image is started in a separate docker-container. Previously, LocalStack used an instance of `mariadb`. 
So it might be, that some default parameters are by chance matching the parameters you are trying to set. 

If you still experience issues, please provide a more detailed description about the database type you are using, and the parameters you want to set.

**Comment by jandroav** [comment]
Hey @steffyP ! Are parameter groups still mocked for DocumentDB?

**Comment by steffyP** [comment]
Hey @jandroav, yes it's only mocked on DocumentDB.
