### ISSUE TITLE
enhancement request: Add Support for ED25519 Key Pairs

### ISSUE THREAD

**Issue by jrindy-iterable** [localstack/localstack#9237]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Enhancement description

Localstack currently only works with an RSA key pair for the aws_key_pair resource. I was trying to use an ED25519 key pair and it kept saying it was an invalid format. It would be good to add support for ED25519 key pairs as well.

**Comment by alexrashed** [comment]
Hi @jrindy-iterable!
Actually, there are several services which work with asymmetric encryption keys (KMS, EKS,...).
Could you please elaborate a bit on which service and which service operations you are referring to?

**Comment by jrindy-iterable** [comment]
Hi there, yes. I had mentioned in the main body that it was with the `aws_key_pair` resource that is used to import a key pair into EC2. I am not able to use an ED25519 key generated with `ssh-keygen`, but I am able to use a RSA key generated in the same manner.

I have tried supplying the ED25519 key normally and as base64 encoded, and neither work.

Providers have endpoints set to http://localhost:4566 where localstack is running.

Sample TF code:
```hcl
resource "aws_key_pair" "fake_key_pair" {
  key_name   = "test-key"
  public_key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIImv2SB05uBF88J5NsfbfZ+XiMUpvMMhMfgC4qPC00K0 fake-key for module tests"
}
```
Error from running the code:
```
❯ terraform apply -auto-approve

Terraform used the selected providers to generate the following execution plan. Resource actions are
indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # aws_key_pair.fake_key_pair will be created
  + resource "aws_key_pair" "fake_key_pair" {
      + arn             = (known after apply)
      + fingerprint     = (known after apply)
      + id              = (known after apply)
      + key_name        = "test-key"
      + key_name_prefix = (known after apply)
      + key_pair_id     = (known after apply)
      + key_type        = (known after apply)
      + public_key      = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIImv2SB05uBF88J5NsfbfZ+XiMUpvMMhMfgC4qPC00K0 fake-key for module tests"
      + tags_all        = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.
aws_key_pair.fake_key_pair: Creating...
╷
│ Warning: AWS account ID not found for provider
│
│   with provider["registry.terraform.io/hashicorp/aws"],
│   on providers.tf line 1, in provider "aws":
│    1: provider "aws" {
│
│ See https://www.terraform.io/docs/providers/aws/index.html#skip_requesting_account_id for
│ implications.
│
│ (and one more similar warning elsewhere)
╵
╷
│ Error: importing EC2 Key Pair (test-key): InvalidKeyPair.Format: Key is not in valid OpenSSH public key format
│ 	status code: 400, request id: 6eb5f484-4ad8-4824-a4d3-50bc36ec8ac5
│
│   with aws_key_pair.fake_key_pair,
│   on main.tf line 1, in resource "aws_key_pair" "fake_key_pair":
│    1: resource "aws_key_pair" "fake_key_pair" {
│
╵
```

**Comment by jrindy-iterable** [comment]
@alexrashed, I checked directly via awslocal as well, just to cover all my bases. The `import-key-pair` command via CLI requires the key to be in base64 whereas TF handles the encode usually, but I included both outputs to show it more clearly. [From the docs](https://docs.aws.amazon.com/cli/latest/reference/ec2/import-key-pair.html):
> --public-key-material (blob)
>
>The public key. For API calls, the text must be base64-encoded. For command line tools, base64 encoding is performed for you.

Sample output:
```bash
❯ awslocal ec2 import-key-pair --key-name 'test-key' --public-key-material 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIImv2SB05uBF88J5NsfbfZ+XiMUpvMMhMfgC4qPC00K0 fake-key for module tests'

Invalid base64: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIImv2SB05uBF88J5NsfbfZ+XiMUpvMMhMfgC4qPC00K0 fake-key for module tests"

❯ awslocal ec2 import-key-pair --key-name 'test-key' --public-key-material 'c3NoLWVkMjU1MTkgQUFBQUMzTnphQzFsWkRJMU5URTVBQUFBSUltdjJTQjA1dUJGODhKNU5zZmJmWitYaU1VcHZNTWhNZmdDNHFQQzAwSzAgZmFrZS1rZXkgZm9yIG1vZHVsZSB0ZXN0cw=='

An error occurred (InvalidKeyPair.Format) when calling the ImportKeyPair operation: Key is not in valid OpenSSH public key format

**Comment by viren-nadkarni** [comment]
This is now implemented in the `latest` image, thanks for reporting!

**Comment by jrindy-iterable** [comment]
Thanks for this one also @viren-nadkarni!
