### ISSUE TITLE
bug: ApiGateway -> DynamoDB boolean is mapped as python variable

### ISSUE THREAD

**Issue by ifursov** [localstack/localstack#9250]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Localstack 2.2.0

Stack:
ApiGateway with specification where one parameter is boolean.
MappingTemplate which basically translates it to DynamoDb put_item
DynamoDb 

When writhing boolean then before transfromation it is:
```
2023-09-28 15:06:38 2023-09-28T12:06:38.481  INFO --- [   asgi_gw_5] l.s.apigateway.templates   : Method request body before transformations: {........ "my_boolean":true," ........ }
```
after transformation:
```
2023-09-28 15:06:38 {
2023-09-28 15:06:38   "TableName": "my_table",
2023-09-28 15:06:38   "Item": {
........
2023-09-28 15:06:38                                                   "my_boolean": {"BOOL": True)}
```

### Expected Behavior

After transformation it should be:

```
 "my_boolean": {"BOOL": true)}
```

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

docker-compose up -d

Terraform apply --auto-approve

### Environment

```markdown
- OS: MacOs
- LocalStack: 2.2.0
```

**Comment by MarcelStranak** [comment]
Hello @ifursov,
Please try it with the new version of LocalStack v2.3.1 and let us know if the issue is still present. If yes, please share a working sample that we can use to replicate the issue.
Thanks.

**Comment by calvernaz** [comment]
Hi @ifursov thanks for reaching out, I've made a complete sample using terraform that you can find [here](https://github.com/localstack/localstack-terraform-samples/tree/master/apigateway-dynamodb). 

You can see the log showing the correct mapping:

```
l.s.apigateway.templates   : Method request body before transformations: { "PetType": "dog", "PetName": "tito", "PetPrice": 250 }
l.s.apigateway.templates   : Endpoint request body after transformations:
{"TableName":"Pets","Item":{"id":{"S":"77851b6f"},"PetType":{"S":"dog"},"PetName":{"S":"tito"},"PetPrice":{"N":"250"},"PetBoolean":{"BOOL":true}}}

```

**Comment by ifursov** [comment]
Hello @MarcelStranak @calvernaz ,
I have tested with localstack 2:3:2.
The boolean is fixed thank you.

However, now I have to specify in the request all api properties, even non-mandatory once.

It transforms them to None and I get the followin error:
```
 Failed validating 'type' in schema['properties']['confs']['properties']['myconf']:
2023-10-19 09:51:23     {'type': 'string'}
2023-10-19 09:51:23 
2023-10-19 09:51:23 On instance['confs']['myconf']:
2023-10-19 09:51:23     None
```

It started to happen from 2.2.0 version.

**Comment by calvernaz** [comment]
> Hello @MarcelStranak @calvernaz , I have tested with localstack 2:3:2. The boolean is fixed thank you.
> 
> However, now I have to specify in the request all api properties, even non-mandatory once.
> 
> It transforms them to None and I get the followin error:
> 
> ```
>  Failed validating 'type' in schema['properties']['confs']['properties']['myconf']:
> 2023-10-19 09:51:23     {'type': 'string'}
> 2023-10-19 09:51:23 
> 2023-10-19 09:51:23 On instance['confs']['myconf']:
> 2023-10-19 09:51:23     None
> ```
> 
> It started to happen from 2.2.0 version.

Hi @ifursov thanks for confirming it works, since you seem to have a different issue now, feel free to use the sample I have provided with the new changes that we can reproduce the issue.
