### ISSUE TITLE
moto_server is not restarted if it crashes

### ISSUE THREAD

**Issue by phihag** [localstack/localstack#926]
I'm running the localstack/localstack docker image with s3 only. When moto_server crashes - which happens quite regularly for an unknown reason, as I cannot find any logfiles - it is not restarted. To reproduce, run

```
$ docker run --rm --name ls_s3  -e SERVICES=s3:1234  localstack/localstack &
(...)
$ docker exec -it ls_s3 /bin/bash
bash-4.3# pstree
supervisord-+-make---sh---python---python
            `-make---sh---python---sh---moto_server
bash-4.3# killall moto_server
bash-4.3# pstree
supervisord-+-make---sh---python---python
            `-make---sh---python
bash-4.3# 
```

The offending process seems to be `python bin/localstack start`. It should either exit when all of its children die, or go out of the way in the first place by exiting after it has launched its child processes.

**Comment by whummer** [comment]
Thanks for reporting. Closing this issue as outdated. We haven't recently received any issues reporting that the moto_server process crashes. Please re-open if the problem persists. Thanks
