### ISSUE TITLE
ModuleNotFoundError: No module named 'localstack.services.awslambda.invocation' error with latest localstack docker image

### ISSUE THREAD

**Issue by yiumen-britive** [localstack/localstack#9277]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

docker-compose up
/opt/code/localstack/.venv/bin/python -m localstack.cli.main pod load file:///mnt/data/tenant.pod

[+] Building 0.0s (0/0)                                                                                                                                                                  
[+] Running 1/1
 ✔ Container localstack_main  Started                                                                                                                                               0.8s 
localstack_main  | 
localstack_main  | LocalStack version: 2.3.2.dev
localstack_main  | LocalStack Docker container id: 80a44a3c3823
localstack_main  | LocalStack build date: 2023-10-02
localstack_main  | LocalStack build git hash: 6e8915ac
localstack_main  | 
localstack_main  | 2023-10-02T17:56:37.842  INFO --- [-functhread4] hypercorn.error            : Running on https://0.0.0.0:4566 (CTRL + C to quit)
localstack_main  | 2023-10-02T17:56:37.842  INFO --- [-functhread4] hypercorn.error            : Running on https://0.0.0.0:4566 (CTRL + C to quit)
localstack_main  | Ready.
localstack_main  | ─────────────────────────── Updating LocalStack CLI ────────────────────────────
localstack_main  | ✔ LocalStack CLI updated
localstack_main  | Restoring tenant data
localstack_main  | 2023-10-02T17:56:50.082  INFO --- [   asgi_gw_0] localstack.request.http    : GET / => 200
localstack_main  | 2023-10-02T17:56:50.322  INFO --- [   asgi_gw_0] localstack.request.http    : GET /_localstack/pods/environment => 200
localstack_main  | 2023-10-02T17:56:51.947  WARN --- [   asgi_gw_0] l.pods.load                : A state for dynamodbstreams already exists for account 000000000000 and region us-east-1. The new state will overwrite the old one.
localstack_main  | 2023-10-02T17:56:53.848  WARN --- [   asgi_gw_0] l.pods.load                : A state for dynamodbstreams already exists for account 000000000000 and region us-east-1. The new state will overwrite the old one.
localstack_main  | 2023-10-02T17:56:53.848  WARN --- [   asgi_gw_0] l.pods.load                : A state for dynamodbstreams already exists for account 000000000000 and region us-east-1. The new state will overwrite the old one.
localstack_main  | 2023-10-02T17:56:54.410 ERROR --- [   asgi_gw_0] l.pods.manager             : Error while injecting state of service lambda from pod
localstack_main  | Traceback (most recent call last):
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack_persistence/pods/manager.py", line 24, in inject
localstack_main  |     try:B.accept_state_visitor(F)
localstack_main  |         ^^^^^^^^^^^^^^^^^^^^^^^^^
localstack_main  |   File "/opt/code/localstack/localstack/services/plugins.py", line 140, in accept_state_visitor
localstack_main  |     self._provider.accept_state_visitor(visitor)
localstack_main  |   File "/opt/code/localstack/localstack/services/lambda_/provider.py", line 226, in accept_state_visitor
localstack_main  |     visitor.visit(lambda_stores)
localstack_main  |   File "/usr/local/lib/python3.11/functools.py", line 946, in _method
localstack_main  |     return method.__get__(obj, cls)(*args, **kwargs)
localstack_main  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack_persistence/pods/load.py", line 24, in _
localstack_main  |     with A.zip.open(F)as G:H=A.decoder.decode(G);B[C][E].__dict__.update(H.__dict__)
localstack_main  |                              ^^^^^^^^^^^^^^^^^^^
localstack_main  |   File "/opt/code/localstack/localstack/state/pickle.py", line 255, in decode
localstack_main  |     return self.unpickler_class(file).load()
localstack_main  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/dill/_dill.py", line 419, in load
localstack_main  |     obj = StockUnpickler.load(self)
localstack_main  |           ^^^^^^^^^^^^^^^^^^^^^^^^^
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/dill/_dill.py", line 409, in find_class
localstack_main  |     return StockUnpickler.find_class(self, module, name)
localstack_main  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
localstack_main  | ModuleNotFoundError: No module named 'localstack.services.awslambda.invocation'

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

docker-compose up -d

### Environment

```markdown
- OS: MacOS
- LocalStack: latest
```

### Anything else?
docker-compose.yml configuration for localstack

    volumes:
       - <project directory>/data/localstack/podfiles:/mnt/data
       - <project directory>/data/localstack/podload.sh:/etc/localstack/init/ready.d/podload.sh
       - <project directory>/data/localstack/data:/var/lib/localstack
       - /var/run/docker.sock:/var/run/docker.sock

contents of podload.sh:

# This was needed with the latest 2.0 version of localstack to pull in pod support.   Hopefully harmless in the future
/opt/code/localstack/.venv/bin/python -m localstack.cli.main update localstack-cli

if [ -s /mnt/data/tenant.pod ]; then
    echo Restoring tenant data
    /opt/code/localstack/.venv/bin/python -m localstack.cli.main pod load file:///mnt/data/tenant.pod
elif [ -s /mnt/data/localstack.pod ]; then
    echo Restoring base terraform data
    /opt/code/localstack/.venv/bin/python -m localstack.cli.main pod load file:///mnt/data/localstack.pod
elif [ -s /mnt/data/kms.pod ]; then
    echo Restoring default KMS
    /opt/code/localstack/.venv/bin/python -m localstack.cli.main pod load file:///mnt/data/kms.pod
fi

**Comment by giograno** [comment]
Hi @yiumen-britive, thanks for reporting the issue. Unfortunately, we changed the package name for lambda in the latest release (see https://github.com/localstack/localstack/pull/8861). This broke your Cloud Pod, unfortunately. You should either re-generate your pod with the latest version of LocalStack or load it with v2.2. 

We are working to ensure LocalStack version upgrades won't break old Cloud Pods in the future. I am really sorry for the inconvenience. Please let us know if you have any further questions.
