### ISSUE TITLE
bug: APIGatewayV2 WebSocket -> SNS:   Unsupported integration URI

### ISSUE THREAD

**Issue by adamzcog** [localstack/localstack#9280]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am attempting to run LocalStack PRO with the terraform that is applied and working with AWS Cloud.
What I want is API Gateway WebSocket to send a message to SNS on connect/disconnect.
WebSocket API has a custom authorizer Lambda that works fine and authorizes the request.

Unfortunately what I get is this error:
2023-10-02T12:40:49.013582296Z     if E==_Q:raise ConnectionDeniedException(f"Exception during $connect action: {K}")from K
2023-10-02T12:40:49.013583859Z localstack_ext.services.apigateway.models.ConnectionDeniedException: Exception during $connect action: Unsupported integration URI "arn:aws:apigateway:eu-west-1:sns:path/000000000000/SNSTopicName" for Websocket API ID "e272733c"

In documentation I was not able to find a list of supported or not integration types so I assume my setup might be wrong?

### Expected Behavior

Message to be sent to SNS

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal s3 mb s3://mybucket

### Environment

```markdown
- OS:Windows 11
- LocalStack:latest
```

**Comment by MarcelStranak** [comment]
Hi @adamzcog,

Please have a look at our terraform samples for ApiGateway deployments. 
https://github.com/localstack/localstack-terraform-samples
If this isn't helpful, please provide us with a functioning sample that we can use to replicate the issue.
Thanks.

**Comment by adamzcog** [comment]
@MarcelStranak I do not see a sample of WS -> SNS which might be my case.
Is that even supported? I would check the localstack code but APIGatewayV2 is not public code.
It not going to be easy to make terraform I am using showable to you.

**Comment by calvernaz** [comment]
Hi @adamzcog unfortunately we don't support Websockets with SNS backend integration. I'll take it and implement it, you should hear from me soon!

**Comment by bentsku** [comment]
Hello @adamzcog! The feature should now be part of `localstack/localstack-pro:3.2` and `localstack/localstack-pro:latest`. Could you please pull the image and give it a try? Thanks!
