### ISSUE TITLE
"Unable to find handler script in Lambda archive." when creating Lambda function

### ISSUE THREAD

**Issue by jeanreis** [localstack/localstack#929]
Hello, I'm trying to create a lambda function in localstack, it's failing with the following error:
`Unable to find handler script in Lambda archive.`

Running with docker-compose.

Lambda code:
index.js
```
exports.handler = function (event, context, callback) {
    let response = "Hello, World";

    callback(null, response);
}
```
CLI command:
`aws lambda create-function --function-name hello-world --runtime node6.10 --memory-size 128 --role dummy-role --handler index.handler --region eu-west-1 --zip-file fileb://lambda.zip --endpoint http://localhost:4574`
(lambda.zip contains only index.js)

Verbose error from Localstack:
```
localstack_1  | 2018-09-11T10:47:32:DEBUG:localstack.services.awslambda.lambda_api: Lambda archive content:
localstack_1  | total 8
localstack_1  | drwxr-xr-x    4 root     root           128 Sep 11 10:47 .
localstack_1  | drwxr-xr-x    9 root     root           288 Sep 11 10:47 ..
localstack_1  | -rw-r--r--    1 root     root           196 Sep 11 10:47 index.js
localstack_1  | -rw-r--r--    1 root     root           362 Sep 11 10:47 original_lambda_archive.zip
localstack_1  |
localstack_1  | 2018-09-11T10:47:32:WARNING:localstack.services.awslambda.lambda_api: Unable to find handler script in Lambda archive.
```

The result is the same wether using `TMPDIR=/private$TMPDIR docker-compose up` or just plain `docker-compose up`.

Environment:
macOS 10.13.6
Docker 18.06.1-ce

**Comment by mturner** [comment]
I am experiencing this same issue.  My attempts to upload the most basic possible lambda function result in the same behavior.  @jeanreis did you find a solution to this?

**Comment by jeanreis** [comment]
@mturner no, I didn't. In the meantime I moved on to other things, all I can say is that the same environment works fine with a Go function, so whatever case this is triggering seems to be Node-specific 🤔

**Comment by jeanreis** [comment]
Spotted my mistake, --runtime argument should be **nodejs6.10** instead of **node6.10**.

Closing.

**Comment by mturner** [comment]
Heh I made exactly the same mistake :(

**Comment by hafizmuhammadshoaib** [comment]
can anybody here told me what i have done wrong here? i am creating lambda function with localstack.

Please help me. I am new to localstack :( 

![image](https://user-images.githubusercontent.com/26689197/87035244-7cef4480-c202-11ea-9bab-27bd010bff7c.png)
