### ISSUE TITLE
Add CloudHSM

### ISSUE THREAD

**Issue by paracycle** [localstack/localstack#93]
There is a [Docker based SoftHSM instance](https://github.com/rolandshoemaker/docker-hsm) that might be used to emulate a CloudHSM instance.

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-317) by [Unito](https://www.unito.io/learn-more)

**Comment by whummer** [comment]
Are you still interested in this feature @paracycle - would you be able to contribute a pull request? 

Looks like this particular integration hasn't received much attention/interest from the community. I wouldn't add it as a default service to LocalStack, but we could enable it as an optional service that can be integrated. 

The API entrypoints section [here](https://github.com/localstack/localstack/blob/master/localstack/services/infra.py#L137) would be a good starting point if you want to give it a try. Thanks!
