### ISSUE TITLE
bug: ElastiCache replication group does not respect cluster mode

### ISSUE THREAD

**Issue by thrau** [localstack/localstack#9317]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When creating a new replication group in ElastiCache, localstack attempts to create redis instances in clustered mode.

```console
awslocal elasticache create-replication-group \
  --replication-group-id my-redis-replication-group-2 \
  --replication-group-description 'my replication group' \
  --engine redis \
  --automatic-failover-enabled \
  --cache-node-type cache.t2.micro \
  --num-cache-clusters 2
```

This later leads to the following error when trying to connect to the cluster:
```
redis-cli -p 4513 set foo bar
(error) CLUSTERDOWN Hash slot not served
```

Moreover, this actually creates a redis cluster, so you can connect with `redis-cli -c -p ...` and run `cluster nodes`:

```
127.0.0.1:4510> cluster nodes
455c3afff747e81df15fed094ea5c2bcc1649d3c :4510@14510 myself,master - 0 0 1 connected 0-16383
```

### Expected Behavior

This is not the behavior of AWS. In AWS, replication groups with one node group are by default in non-clustered mode, unless enabled explicitly. Instead of creating a cluster, the instances are managed via `REPLICAOF`

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    LOCALSTACK_API_KEY=... localstack start

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

See steps in description

### Environment

```markdown
- OS: Linux Mint 21.2
- LocalStack: latest
```

**Comment by MarcelStranak** [comment]
Hi @thrau could this be closed now?

**Comment by thrau** [comment]
yes, with v3 we release a new elasticache provider that fixes this issue. thanks @MarcelStranak !
