### ISSUE TITLE
SQS backend api does not start 

### ISSUE THREAD

**Issue by danonorato** [localstack/localstack#932]
STRs
1) start up the local infrastructure
```make  infra```
2) notice successful startup display with external ports
```~/src/localstack danonorato [master] $ make infra```
```(. .venv/bin/activate; exec bin/localstack start)
Starting local dev environment. CTRL-C to quit.
Starting mock API Gateway (http port 4567)...
Starting mock DynamoDB (http port 4569)...
Starting mock SES (http port 4579)...
Starting mock Kinesis (http port 4568)...
Starting mock Redshift (http port 4577)...
Starting mock S3 (http port 4572)...
Starting mock CloudWatch (http port 4582)...
Starting mock CloudFormation (http port 4581)...
Starting mock SSM (http port 4583)...
Starting mock SQS (http port 4576)...
Starting local Elasticsearch (http port 4571)...
Starting mock SNS (http port 4575)...
Starting mock DynamoDB Streams service (http port 4570)...
Starting mock Firehose service (http port 4573)...
Starting mock Route53 (http port 4580)...
Starting mock ES service (http port 4578)...
Starting mock Lambda service (http port 4574)...
2018-09-13T14:16:51:WARNING:infra.pyc: Service "elasticsearch" not yet available, retrying...
2018-09-13T14:16:54:WARNING:infra.pyc: Service "elasticsearch" not yet available, retrying...
Ready.
```
3) attempt to use SQS endpoint for run BasicFunctionalityTest.testLocalSQSAPI()
4) Notice proxy error, can't find backend service.  
```
2018-09-13T14:17:53:ERROR:localstack.services.generic_proxy: Error forwarding request: HTTPConnectionPool(host='127.0.0.1', port=4561): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10db405d0>: Failed to establish a new connection: [Errno 61] Connection refused',)) Traceback (most recent call last):
  File "/Users/danonorato/src/localstack/localstack/services/generic_proxy.py", line 198, in forward5)
```
 5) Notice ```netstat -a | grep 4561``` is missing any listener on port 4561 (the defined backend port for SQS)

**Comment by tzaitsev** [comment]
Any update on this? I'm having the same issue on a fresh install as well.

**Comment by thetumper** [comment]
Having same issue.

**Comment by jiamo** [comment]
Try to find a right `infra/elasticmq/elasticmq-server.jar`
I can't work when I update localstack. However I replace the jar with my old version. It works.

     MD5 (elasticmq/elasticmq-server.jar) = e0b2d26273cf64bbab1a8e9f077eb04c

**Comment by whummer** [comment]
Thanks for reporting. The recommended/supported way of starting LocalStack is in Docker. Occasionally, the installation/download of various infrastructure components can fail, e.g., due to temporary networking issues.

Unfortunately, we can no longer support the various installation issues of the dev environment across different operating systems, python/pip versions, etc.

One thing you can try is to delete the folders in `localstack/infra/*` and restart `make infra`. Hope that helps, thanks.
