### ISSUE TITLE
bug: Lambda error messaging absent for initializing a container lambda without existing container

### ISSUE THREAD

**Issue by kevcube** [localstack/localstack#9322]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Performing the steps below will not give an error message when the lambda fails to create.

create-function expectedly returns 201 because async operation, but then when adding bucket notifications we will get a 400 and also a message that the docker socket is not mounted.

If run with DEBUG=1 we see that the lambda function fails to create because it can not pull the initial container image, but this error is not exposed without DEBUG.

All this can be avoided by pushing a container before creating lambdas, but I was hoping to do all my initialization hands-free.

If `docker` client CLI were included in the pro image I would probably download and push a hello-world image to the repo after creation.

### Expected Behavior

When the lambda fails to create, raise an error outside of DEBUG mode.

Also do not raise error that docker socket is not mounted because this is incorrect/misleading information.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker compose with mounted docker socket

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```sh
awslocal s3api create-bucket xyz
awslocal ecr create-repository xyz

awslocal lambda create-function \
  --function-name xyz \
  --role arn:aws:iam::112233445566:role/irrelevant \
  --code ImageUri=localhost.localstack.cloud:4510/xyz:latest \
  --timeout 120 \
  --memory-size 1024 \
  --package-type Image

awslocal s3api put-bucket-notification-configuration --bucket "xyz" --notification-configuration file://xyz-bucket-to-function.json
```

### Environment

```markdown
- OS: Mac
- LocalStack: 2.3.1-pro
```

**Comment by andreluis-oliveira** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Current Behavior
> Performing the steps below will not give an error message when the lambda fails to create.
> 
> create-function expectedly returns 201 because async operation, but then when adding bucket notifications we will get a 400 and also a message that the docker socket is not mounted.
> 
> If run with DEBUG=1 we see that the lambda function fails to create because it can not pull the initial container image, but this error is not exposed without DEBUG.
> 
> All this can be avoided by pushing a container before creating lambdas, but I was hoping to do all my initialization hands-free.
> 
> If `docker` client CLI were included in the pro image I would probably download and push a hello-world image to the repo after creation.
> 
> ### Expected Behavior
> When the lambda fails to create, raise an error outside of DEBUG mode.
> 
> Also do not raise error that docker socket is not mounted because this is incorrect/misleading information.
> 
> ### How are you starting LocalStack?
> With a docker-compose file
> 
> ### Steps To Reproduce
> #### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)
> ```
> docker compose with mounted docker socket
> ```
> 
> #### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)
> ```shell
> awslocal s3api create-bucket xyz
> awslocal ecr create-repository xyz
> 
> awslocal lambda create-function \
>   --function-name xyz \
>   --role arn:aws:iam::112233445566:role/irrelevant \
>   --code ImageUri=localhost.localstack.cloud:4510/xyz:latest \
>   --timeout 120 \
>   --memory-size 1024 \
>   --package-type Image
> 
> awslocal s3api put-bucket-notification-configuration --bucket "xyz" --notification-configuration file://xyz-bucket-to-function.json
> ```
> 
> ### Environment
> ```
> - OS: Mac
> - LocalStack: 2.3.1-pro
> ```
> 
> ### Anything else?
> _No response_

Thanks for opening this up @kevcube
