### ISSUE TITLE
bug: EC2 key pair fingerprint calculation

### ISSUE THREAD

**Issue by viren-nadkarni** [localstack/localstack#9337]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

AWS uses different fingerprinting methods for key pairs based on their origin and types.

<https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/verify-keys.html#how-ec2-key-fingerprints-are-calculated>

LocalStack currently uses MD5 for all cases.

### Expected Behavior

![image](https://github.com/localstack/localstack/assets/5170829/65d0d3c0-7bfd-4fcf-bbe2-8cc906e14262)

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

### Environment

```markdown
- OS: Ubuntu 22.04
- LocalStack: 2.3
```

**Comment by iambary44** [comment]
> ### Is there an existing issue for this?
> 
> - [X] I have searched the existing issues
> 
> ### Current Behavior
> 
> AWS uses different fingerprinting methods for key pairs based on their origin and types.
> 
> 
> 
> <https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/verify-keys.html#how-ec2-key-fingerprints-are-calculated>
> 
> 
> 
> LocalStack currently uses MD5 for all cases.
> 
> ### Expected Behavior
> 
> ![image](https://github.com/localstack/localstack/assets/5170829/65d0d3c0-7bfd-4fcf-bbe2-8cc906e14262)
> 
> 
> 
> ### How are you starting LocalStack?
> 
> With a docker-compose file
> 
> ### Steps To Reproduce
> 
> #### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)
> 
> 
> 
>     docker run localstack/localstack
> 
> ### Environment
> 
> ```markdown
> - OS: Ubuntu 22.04
> 
> - LocalStack: 2.3
> ```
> 
> 
> ### Anything else?
> 
> _No response_

**Comment by nifadyev** [comment]
Hey @viren-nadkarni . I made [PR](https://github.com/getmoto/moto/pull/8235) in `moto`, could you please take a look?
