### ISSUE TITLE
localstack-core 2.3.2 requires cachetools~=5.0.0, but you have cachetools 5.3.0 which is incompatible

### ISSUE THREAD

**Issue by rishabhAjay** [localstack/localstack#9340]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Error while running `cdk synth`:

<img width="936" alt="image" src="https://github.com/localstack/localstack/assets/63163183/58c784d8-fbc6-4c11-a7d3-f6eb15a54eba">

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

I am trying to run `cdk synth` and our project uses `cachetools==5.3.0`. I get the above error while the command tries to install all the packages. 

### Environment

```markdown
- OS: Windows 10
- LocalStack: 2.3.0
- localstack-core: 2.3.2
```

### Anything else?

Is there a way to upgrade cachetools or increasing the range of acceptable versions.

**Comment by thrau** [comment]
@dfangl i can see we set this in https://github.com/localstack/localstack/pull/6324
can you remember why it was exactly `~=5.0.0` and not `>= 5.0.0.` ?

**Comment by dfangl** [comment]
No, cannot remember. We could probably relax it to `~=5.0` or even `>= 5.0.0`

**Comment by thrau** [comment]
thanks for reporting @rishabhAjay , it's merged now and will be in a dev release in around an hour. you can use `pip install -U --pre localstack` to install the latest dev version

**Comment by rishabhAjay** [comment]
Awesome. Thank you!
