### ISSUE TITLE
bug: `DbClusterResourceId` is not returned while using Neptune's `DescribeDbClusters` API

### ISSUE THREAD

**Issue by HarshCasper** [localstack/localstack#9345]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After creating a Neptune cluster and an instance if we describe the cluster using `DescribeDbClusters` API, the user is not able to verify the `DbClusterResourceId`. 

### How are you starting LocalStack?

With the `localstack` script

### Steps To Reproduce

```bash
$ awslocal neptune create-db-cluster \
    --engine neptune \
    --db-cluster-identifier my-neptune-db

$ awslocal neptune create-db-instance \
    --db-cluster-identifier my-neptune-db \
    --db-instance-identifier my-neptune-instance \
    --engine neptune \
    --db-instance-class db.t3.medium

$ awslocal neptune describe-db-clusters
```

### Environment

```markdown
- OS: macOS
- LocalStack: 2.3.2
```

**Comment by pinzon** [comment]
The PR that fixes this issue has been merged.
