### ISSUE TITLE
bug: Cognito with phone and email as username, lambda Trigger doesn't seem to pass enough info

### ISSUE THREAD

**Issue by vt-rcheng** [localstack/localstack#9349]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

this is slightly related to issue #9348 

Note that I am new to cognito, so my understanding of it may be incorrect.
when I created the Cognito UserPool, I opted for parameter

```
        UsernameAttributes=[
            'phone_number',
            'email',
        ],

```
I then try to signup  a user with phone and then a user with email. for each sign up a lambda trigger happens

----

`awslocal cognito-idp sign-up --client-id od8i79jcw3raxc3ei4vkii6tsb --username <a phone> --password Aa123456 --user-attributes Name=name,Value=<a real name>
`

`awslocal cognito-idp sign-up --client-id od8i79jcw3raxc3ei4vkii6tsb --username <an email> --password Aa123456 --user-attributes Name=name,Value=<a real name>
`

```
root@c127eb79ec4c:/opt/code/localstack# awslocal cognito-idp list-users --user-pool-id us-east-1_awakenpoolid
{
    "Users": [
        {
            "Username": "6d04c47b-f5e5-4fc9-9f2c-3404031b9af7",
            "Attributes": [
                {
                    "Name": "name",
                    "Value": "<a real name>"
                },
                {
                    "Name": "cognito:username",
                    "Value": "<a email>"
                },
                {
                    "Name": "email",
                    "Value": "<a email>"
                },
                {
                    "Name": "sub",
                    "Value": "6d04c47b-f5e5-4fc9-9f2c-3404031b9af7"
                },
                {
                    "Name": "email_verified",
                    "Value": "false"
                }
            ],
            "UserCreateDate": 1697273661.566098,
            "UserLastModifiedDate": 1697273661.566098,
            "Enabled": true,
            "UserStatus": "UNCONFIRMED"
        },
        {
            "Username": "3194669d-22b5-4f78-beb9-cb0526658efa",
            "Attributes": [
                {
                    "Name": "name",
                    "Value": "<a real name>"
                },
                {
                    "Name": "cognito:username",
                    "Value": "<a phone number>"
                },
                {
                    "Name": "phone_number",
                    "Value": "<a phone number>"
                },
                {
                    "Name": "sub",
                    "Value": "3194669d-22b5-4f78-beb9-cb0526658efa"
                },
                {
                    "Name": "phone_number_verified",
                    "Value": "false"
                }
            ],
            "UserCreateDate": 1697279271.45157,
            "UserLastModifiedDate": 1697279271.45157,
            "Enabled": true,
            "UserStatus": "UNCONFIRMED"
        }
    ]
}



```

----

When I check the event and context I get for the signup I get 

```
for email username:

DEBUG    23/10/14 16:54:21.919 .../apps/cognito/rest/handlers.py:24 cognito trigger: CustomEmailSender_SignUp - {'version': '$LATEST', 'triggerSource': 'CustomEmailSender_SignUp', 'region': 'us-east-1', 'userPoolId': 'us-east-1_awakenpoolid', 'callerContext': {'awsSdkVersion': 'aws-sdk-unknown-unknown', 'clientId': 'CLIENT_ID_NOT_APPLICABLE'}, 'request': {'userAttributes': {}, 'validationData': {}, 'clientMetadata': {}, 'session': [], 'code': 'AgV42gkRoquMDexKaJ2gUTQ7tiwXEQ8Nz1tViqlrwuJrHq4AXwABABVhd3MtY3J5cHRvLXB1YmxpYy1rZXkAREEvSzF5ckhTQUFSVHZIVG9JU0lBVnlTTUdFZ0hJYlBENTNuTXJpVVllVUUrOUtLQk15QnJrVVNjN29tMGpEMk5Pdz09AAEAB2F3cy1rbXMAS2Fybjphd3M6a21zOnVzLWVhc3QtMTowMDAwMDAwMDAwMDA6a2V5LzAwMDAwMDAwLTAwMDAtMDAwMC0wMDAwLTAwMDAwMDAwMDAwMQB0MDAwMDAwMDAtMDAwMC0wMDAwLTAwMDAtMDAwMDAwMDAwMDAxUPCQdV1pZFdJQuzC4I2PhxVItpXMFLRfqF8i+AE9xLDP/d7+wWXXf8jY79bAs+Yh7GGwwyrlJGTOsQeyWRkLc+NM/3zgOlHuJuIRp2u68UcCAAAQANv16ssbQM6OhZsCyVfiknQ0OtCOw2p2cB66WJ675cUvuZeU2jJaesXXMixvGpWU4/////8AAAABAAAAAAAAAAAAAAABAAAABhiusXBAdHdsQB+JDOHAocGJsAnJmREAZzBlAjEA3/3rNzQ/+vqAcjxVwnER53R/yxbzv8Ru1D2aHnjbyQH7qlZisJAGUqxu8Jm3UuuVAjAokrB99U8/i767Xa10TAYQ6EIJo3X76U3yvsJsLH+hePSCjjZhhgAeRKxH+QoO5Lg='}, 'response': {}, 'userName': '<an email>'} / {'identity': {'cognito_identity_id': None, 'cognito_identity_pool_id': None}}
```

```
for phone username:

DEBUG    23/10/14 18:27:51.429 .../apps/cognito/rest/handlers.py:24 cognito trigger: PreSignUp_SignUp - {'version': '$LATEST', 'triggerSource': 'PreSignUp_SignUp', 'region': 'us-east-1', 'userPoolId': 'us-east-1_awakenpoolid', 'callerContext': {'awsSdkVersion': 'aws-sdk-unknown-unknown', 'clientId': 'od8i79jcw3raxc3ei4vkii6tsb'}, 'request': {'userAttributes': {'name': '<a real name>', 'cognito:user_status': 'UNCONFIRMED', 'username': '3194669d-22b5-4f78-beb9-cb0526658efa', 'client_id': 'od8i79jcw3raxc3ei4vkii6tsb'}, 'validationData': {}, 'clientMetadata': {}, 'session': []}, 'response': {}, 'userName': '3194669d-22b5-4f78-beb9-cb0526658efa'} / {'identity': {'cognito_identity_id': None, 'cognito_identity_pool_id': None}}

```

both triggers are missing a lot of user attribute data.
the behavior is very different from not opting to use phone and email as username

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal s3 mb s3://mybucket

### Environment

```markdown
- OS:
- LocalStack:
```

**Comment by vt-rcheng** [comment]
can you please investigate into this issue, I cannot have a proper user signup workflow at the moment

when I use real cognito on aws, the trigger event I got was 




`{'version': '1', 'region': 'us-west-2', 'userPoolId': 'us-west-2_XK4MGCQqb', 'userName': 'd8411330-6061-70eb-ec7d-e9eb17f8f222', 'callerContext': {'awsSdkVersion': 'aws-sdk-unknown-unknown', 'clientId': '5dvett3sa037ilq69b7fnsl7k7'}, 'triggerSource': 'PreSignUp_SignUp', 'request': {'userAttributes': {'name': 'name', 'email': 'xxxxxx@yyyy.zzzz'}, 'validationData': None}, 'response': {'autoConfirmUser': False, 'autoVerifyEmail': False, 'autoVerifyPhone': False}}`



on localstack I get

`{'version': '$LATEST', 'triggerSource': 'PreSignUp_SignUp', 'region': 'us-east-1', 'userPoolId': 'us-east-1_awakenpoolcustomer', 'callerContext': {'awsSdkVersion': 'aws-sdk-unknown-unknown', 'clientId': 'p8w33471ldtuf4hy4wszt2dk1m'}, 'request': {'userAttributes': {'cognito:user_status': 'UNCONFIRMED', 'username': 'xxxxxx@yyyy.zzzz', 'client_id': 'p8w33471ldtuf4hy4wszt2dk1m'}, 'validationData': {}, 'clientMetadata': {}, 'session': []}, 'response': {}, 'userName': 'xxxxxx@yyyy.zzzz'}
`


the trigger event data localstack returns does not have sub uuid, and have many other differences depending on settings.

**Comment by Nikola-Milovic** [comment]
The biggest difference seems to be that the `userName` is an email in `localstack` but its the user id in actual aws, and there seems to be no way of getting the user id in the localstack impl.  

Custom message trigger

Actual aws
```
2024/02/02 10:01:27 INFO processing event event="{CognitoEventUserPoolsHeader:{Version:1 TriggerSource:CustomMessage_SignUp Region:eu-central-1 UserPoolID:eu-central-1_TnVq9aK7j CallerContext:{AWSSDKVersion:aws-sdk-js-3.499.0 ClientID:7bofuhbiojn0agarbi57m5b55d} UserName:d8b61dd9-eaea-4fd3-b0a5-ac1821d0491b} Request:{UserAttributes:map[cognito:email_alias:example@gmail.com cognito:user_status:UNCONFIRMED email:example@gmail.com email_verified:false name:John Doe sub:d8b61dd9-eaea-4fd3-b0a5-ac1821d0491b] CodeParameter:{####} UsernameParameter: ClientMetadata:map[]} Response:{SMSMessage: EmailMessage: EmailSubject:}}"
```

Localstack
```
1 UserPoolID:eu-central-1_87bbd2ea7dff4a878a4e4cfce29d1cdd CallerContext:{AWSSDKVersion:aws-sdk-unknown-unknown ClientID:CLIENT_ID_NOT_APPLICABLE} UserName:example@gmail.com} Request:{UserAttributes:map[] CodeParameter:590459 UsernameParameter:example@gmail.com ClientMetadata:map[]} Response:{SMSMessage: EmailMessage: EmailSubject:}}"
```

**Comment by giograno** [comment]
Hi @vt-rcheng, we released a few improvements for the `PreSignUp` trigger in the `latest` Docker image. Would you please give it another try and let us know about any other implementation gaps? Thank you 🙏

**Comment by vt-rcheng** [comment]
> Hi @vt-rcheng, we released a few improvements for the `PreSignUp` trigger in the `latest` Docker image. Would you please give it another try and let us know about any other implementation gaps? Thank you 🙏

not fixed, I have opened a new ticket
