### ISSUE TITLE
Python Pillow Lambda issue

### ISSUE THREAD

**Issue by ambrusadrianz** [localstack/localstack#935]
We have an issue with uploading a lambda function that uses `pillow` for some imaging work. I've tested this lambda with the `latest` localstack without success.

So, we are trying to upload a `python3.6` lambda function to localstack as a ZIP file. I'll attach the zip to the issue. The issue is the following:

```
Unknown error: ('Unable to get handler function from lambda code.', ImportError('cannot import name _imaging',)) Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 516, in create_function
    result = set_function_code(data['Code'], lambda_name)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 450, in set_function_code
    raise Exception('Unable to get handler function from lambda code.', e)
Exception: ('Unable to get handler function from lambda code.', ImportError('cannot import name _imaging',))
```

It seems like the library is not available when the `imp.load_module` is called. I'm a beginner in Python, so it's just speculation. 

Tried to execute the lambda function manually with the `python3.6` lambci-lambda, and it worked fine.

[test.zip](https://github.com/localstack/localstack/files/2395874/test.zip)

**Comment by whummer** [comment]
Thanks for reporting - should be fixed in the latest version, as we're now also using `lambci-lambda` under the covers. Thanks
