### ISSUE TITLE
bug: API Gateway as Proxy to S3 Service

### ISSUE THREAD

**Issue by elliotvargas** [localstack/localstack#9356]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We created a REST API Gateway that serves as a proxy to an S3 bucket. The REST API has 2 path parameters that are used by a **template** in the integration request to create the proper S3 URI. We tested the API running in AWS successfully. 
We exported this API as a OpenAPI JSON file and used it to create the same API in Localstack PRO 2.3. Unfortunately, calling the API when running in localstack doesn't work. The error message follows:

```
Parameter validation failed:\nInvalid bucket name \"{bucket}\": Bucket name must match the regex \"^[a-zA-Z0-9.\\-_]{1,255}$\" or be an ARN matching the regex \"^arn:(aws).*:(s3|s3-object-lambda):[a-z\\-0-9]*:[0-9]{12}:accesspoint[/:][a-zA-Z0-9\\-.]{1,63}$|^arn:(aws).*:s3-outposts:[a-z\\-0-9]+:[0-9]{12}:outpost[/:][a-zA-Z0-9\\-]{1,63}[/:]accesspoint[/:][a-zA-Z0-9\\-]{1,63}$\"",
```

The placeholder `{bucket}` is part of the S3 URI configured during the creation part and it is replaced by the actual bucket name by the request template. Our understanding is that the **template** is not been applied before validating the S3 URI. 

We've created an example project very similar to the actual project code. I'm attaching a ZIP file with all the terraform and OpenAPI files to test it locally.

### Expected Behavior

We were expecting the API to behave exactly as it does in AWS. Namely, that we can successfully download files from the S3 bucket when calling the REST API.

### How are you starting LocalStack?

Custom (please describe below)

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

localstack start -e DEBUG=1

#### Client commands 
[localstack-api-s3-test-terraform.zip](https://github.com/localstack/localstack/files/12922314/localstack-api-s3-test-terraform.zip)

(I'm attaching a ZIP file with the Terraform scripts for creating the API in localstack)

terraform init
terraform apply -auto-approve

### Environment

```markdown
- OS: MacOS Ventura 13.5.2
- LocalStack: 2.3.2
```

**Comment by bentsku** [comment]
Hello @elliotvargas and thanks for your report!

I can confirm the issue: the template is applied, but we don't take `context.requestOverride.path` into consideration at the moment. I'm currently on something regarding the APIGateway -> S3Integration, and I'll try to add this feature as well, I have something experimental now that makes your sample work.

```bash
$ curl http://localhost:4566/restapis/test-api/local/_user_request_/v1/2/2
{
  "id": 2,
  "name": "Document Two"
}
```

I hope I can get this ready soon, I'll keep you informed of the progress here.
Thanks again!

**Comment by bentsku** [comment]
Hello again! The new API Gateway provider has been officially released, you can read more about it in our release announcement for 3.8: https://blog.localstack.cloud/localstack-release-v-3-8-0/#new-api-gateway-provider

This issue should now be fixed by using the feature flag. Thank you!
