### ISSUE TITLE
Kinesis events map to Map

### ISSUE THREAD

**Issue by garygan-seekers** [localstack/localstack#936]
I created a lambda to handle kinesis stream event, but when the kinesis trigged the lambda, I get below error:
```
Exception in thread "main" java.lang.ClassCastException: java.util.LinkedHashMap cannot be cast to com.amazonaws.services.lambda.runtime.events.KinesisEvent
	at com.seekerscapital.aqt.trade_generator_lambda.TicketHandler.handleRequest(TicketHandler.java:26)
	at cloud.localstack.LambdaExecutor.main(LambdaExecutor.java:100)
```
Looks like the bug is 
at localstack/localstack/ext/java/src/main/java/cloud/localstack/LambdaExecutor.java line 59
```java
if (records.stream().anyMatch(record -> record.containsKey("Kinesis"))) {
```
the "K" in "Kinesis" is upper case,
but in  localstack/localstack/services/awslambda/lambda_api.py line 
```py
            for rec in records:
                event['Records'].append({
                    'eventID': 'shardId-000000000000:{0}'.format(rec['sequenceNumber']),
                    'eventSourceARN': stream_arn,
                    'kinesis': rec
                })
            run_lambda(event=event, context={}, func_arn=arn)
```
the  k in 'kinesis' is not upper case

**Comment by whummer** [comment]
Thanks for reporting @garygan-seekers - this should be fixed in the latest version 👍 
https://github.com/localstack/localstack/blob/master/localstack/ext/java/src/main/java/cloud/localstack/LambdaExecutor.java#L71
