### ISSUE TITLE
Redis Implementation with localStack

### ISSUE THREAD

**Issue by surajtikoo** [localstack/localstack#939]
Hi Team,

I am using local stack for my local development. I find it is very useful and very handy to use it.Other than I am also using Redis cache for my application which is currently not present in your  localstack. For that i have downloaded a redis docker image by which i am able to test my appliction.

I have small suggestion  if you can intergrate redis with it  that would be very nice

**Comment by whummer** [comment]
Thanks for the suggestion - closing this as a duplicate of #158

**Comment by ashameem123** [comment]
@surajtikoo  -- can you provide some details how you tested Redis and share the docker-compose for redis?

**Comment by surajtikoo** [comment]
@ashameem123  I used the docker image of Redis which is available in the docker hub. For testing, I created a sample spring-boot application.
https://www.journaldev.com/18141/spring-boot-redis-cache
