### ISSUE TITLE
enhancement request: support fixed-response action type in ALB

### ISSUE THREAD

**Issue by paulrobello** [localstack/localstack#9396]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Enhancement description

Seems like the fixed response action type would be pretty trivial to implement and would simplify responding with a 404 in a default action.

**Comment by cabeaulac** [comment]
Done

**Comment by robertlcx** [comment]
@cabeaulac I don't see an attached PR here. Where's its PR?
