### ISSUE TITLE
Kinesis describe-stream output: can't get encryptionType or keyId

### ISSUE THREAD

**Issue by sahas-** [localstack/localstack#940]
Apologies for a naive question. I created a stream, putting records and subscribed to the stream as well. On the consumer side data comes out encrypted which is fine.
1. I wanted to get the key-id so that I can decrypt. When I executed describe-streams, command output doesn't align with the documentation. I dont see encryptionType or keyId in the output. Below is what I see, am I missing something ?
2. Even if I want to stop-stream-encryption, I need the key-id. Not sure how to get key-id from localstack. 

<img width="668" alt="localstack-issue" src="https://user-images.githubusercontent.com/10361685/45933993-2c3f2680-bf5d-11e8-9ec9-6b1c1a65ee94.png">

**Comment by whummer** [comment]
Thanks for reporting @sahas- . We're using https://github.com/mhart/kinesalite under the covers, and to my knowledge it does not currently use or even support encryption (please correct me if I'm wrong). Please provide a small, self-contained example that allows to reproduce this issue. Thanks
