### ISSUE TITLE
enhancement request: OpenSearch 2.9 support

### ISSUE THREAD

**Issue by theahura** [localstack/localstack#9408]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Enhancement description

OpenSearch 2.9 supports a lot of useful features that AWS opensearch also supports, such as being able to use filters in on FAISS searches in the KNN plugin. It would be great to have these in localstack!

### 🧑‍💻 Implementation

this may be as trivial as a version bump? As far as I can tell, localstack is just pulling the opensearch docker image

**Comment by theahura** [comment]
hey @ackdav thanks for accepting this feature request. Curious what the timeline is for looking into this!

**Comment by alexrashed** [comment]
Hi @theahura!
Thanks for your initial contribution and @viren-nadkarni for bringing it over the line! I just merged the PR, and it will be available in `localstack/localstack` with the next build on `master`, and in `localstack/localstack-pro` in the next few hours.
Thanks again!

**Comment by theahura** [comment]
Fantastic. Any idea when the next build on master would be?
