### ISSUE TITLE
bug: Localstack running in Buildkite fails to become healthy

### ISSUE THREAD

**Issue by jghassall** [localstack/localstack#9409]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

On the latest tag for docker, when using buildkite to bring the image up specifically it fails to initialise the docker container

### Expected Behavior

Using docker tag 2.3.2 it works as expected the container is brought up and works as expected.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

      localstack:
        container_name: "localstack"
        image: localstack/localstack
        ports:
          - 8000:4566
        networks:
          - app_net
        environment:
          DEBUG: 1
          SERVICES: "dynamodb"
          DATA_DIR: "/tmp/localstack/data"
        volumes:
          - ${TMPDIR:-/tmp/localstack}:/tmp/localstack"
          - /var/run/docker.sock:/var/run/docker.sock

#### Snippet when bringing the container up in buildkite

      Creating localstack ... done
      | ERROR: for java-build  Container "443f6c265b56" is unhealthy.
      | ERROR: Encountered errors while bringing up the project.
      | 🚨 Error: The command exited with status 1

### Environment

```markdown
- OS: Buildkite latest version
- LocalStack: latest
```

**Comment by alexrashed** [comment]
Hi @jghassall!
Could you give us any more information? The logs of the container maybe? And the exact way of how you configure LocalStack in Buildkite? Since LocalStack works in pretty much every other environment, it seems there might be an issue with either how LocalStack is configured, or how Buildkite starts the container.
Thanks!
