### ISSUE TITLE
bug: DynamoDB API inconsistency

### ISSUE THREAD

**Issue by mschfh** [localstack/localstack#9412]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The value is implicitly converted to a string and the request succeeds.

### Expected Behavior

The request fails with a HTTP 400 error:
```
Unhandled rejection: SerializationException: NUMBER_VALUE cannot be converted to String
```

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

Write a Number as integer using the `@aws-sdk/client-dynamodb` NodeJS client:
```
Myvalue: {
    N: fs.statSync(path).size
}
```

### Environment

```markdown
LocalStack: latest


LOCALSTACK_BUILD_GIT_HASH=e4a6b649
```

### Anything else?

https://stackoverflow.com/a/71495703

**Comment by ackdav** [comment]
Hello @mschfh - thanks for your report. Unfortunately, I have trouble reproducing this issue. Can you please add some context of what you're trying to do, and add a minimal reproducible example?
Thank you!
