### ISSUE TITLE
enhancement request: cognito:DeleteUser implementation

### ISSUE THREAD

**Issue by marco-luzzara** [localstack/localstack#9417]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Enhancement description

The `cognito:DeleteUser` API is not implemented, only the `cognito:AdminDeleteUser` is implemented. The advantage I see in the `cognito:DeleteUser` is that I just need to pass the authorization token as input, which is particularly convenient in a `DELETE /users/me` API. 

Instead, with the `cognito:AdminDeleteUser`, I need to get the username claim and the user pool id, which does not require a big effort. Perhaps, the biggest downside is the side effects it can have if called with the wrong parameters (like deleting another user). I don't think it is a priority enhancement, but worth to be mentioned. 

Thanks

**Comment by giograno** [comment]
Hi @marco-luzzara, thanks for opening the issue. We implemented the `DeleteUser` operation in the `latest` Docker image. Please let us know if you have any further issues. Thanks 🙏
