### ISSUE TITLE
Docker Image Pull timeout when pullNewImage=false

### ISSUE THREAD

**Issue by mcwhitak** [localstack/localstack#943]
Currently if pullNewImage = false but the image does not exist on the machine the run command will result in a pull. This pull however is not governed by the PullCommand in localstack so the timeout is only 1 minute which can result in localstack failing. 

Given that this pull command is implicit (the result of a run command without it's depedencies met) should it be governed by the 10 minute timeout (as then it would gracefully succeed after pulling the image) or should the behavior stay the same as it is now?

Attached is a file of the info log showing the issue (the run command returns an error instead of the containerId).

This has been tested with pullNewImage=true where the image pull succeeds as the timeout is 10 minutes on an explicit 'PullCommand'.

[output.txt](https://github.com/localstack/localstack/files/2425243/output.txt)

**Comment by MeiSign** [comment]
I was running in the same issue but could also workaround it by setting pullNewImage to true.

Would be nice if the timeout could be adjusted when the image needs to be pulled. Maybe the readychecker should start with a timeout of 10 minutes but decrease it to 1 minutes if it doesn't spot download messages in the logs.

**Comment by whummer** [comment]
Thanks for reporting @mcwhitak @MeiSign . I'm aware it's been quite a while since this issue was opened, but seems like you were pointing out a decent solution approach. Would you be able to contribute a small pull request to fix this issue? We'd be very happy to merge it. Thanks!

**Comment by mcwhitak** [comment]
@whummer it looks like your PR in December (https://github.com/localstack/localstack/pull/1901) covers this issue. Are you still interested in finding a more dynamic solution or do you think it would be appropriate to close this issue?

**Comment by whummer** [comment]
Thanks for the hint @mcwhitak . I think we can close this one off for now - but happy to discuss ideas or merge pull requests with an more advanced/dynamic solution!
