### ISSUE TITLE
Kinesis - maxRetries

### ISSUE THREAD

**Issue by walshe-boylesoftware** [localstack/localstack#944]
Lets say I have a consumer consuming 'Kinesis' records from localstack (with a "maxRetries": 10 config).. 

if I throw an error or fail to checkpoint a record in the consumer, will Localstack actually replay the message just like Kinesis would ?

**Comment by Matt343** [comment]
This is entirely up to your application/client implementation. Kinesis itself has no concept of checkpointing or whether or not a client has successfully processed a record (or even a concept of a client really), it just returns the records from a shard starting at a particular iterator or sequence number. The client is responsible for keeping track of where it is in the stream by recording the sequence number of the latest successfully processed message in each shard. The KCL handles this for you using a DynamoDB table, but it's not actually a Kinesis feature. Localstack will behave like the real Kinesis, it will return the messages starting at a particular iterator, so if your client is well behaved it should work the same way.

**Comment by whummer** [comment]
Thanks for providing this very useful answer, @Matt343 👍
