### ISSUE TITLE
LocalStack EC2 logs does not show the log for connection

### ISSUE THREAD

**Issue by Daniel-derf** [localstack/localstack#9470]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am following the official tutorial about localstack EC2  (https://docs.localstack.cloud/user-guide/aws/elastic-compute-cloud/#docker-backend), but in the "Test the Python Web Server 
" step i am not getting full logs, as in the tutorial, but only the log:

2023-10-25T12:28:49.536  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS ec2.RunInstances => 200

With only this, i can not access my localstack aws to testing.

### Expected Behavior

Accordingly to tutorial, i should receive the following log:

2023-08-16T17:18:29.702  INFO --- [   asgi_gw_0] l.s.ec2.vmmanager.docker   : Instance i-b07acefd77a3c415f will be accessible via SSH at: 127.0.0.1:12862, 172.17.0.4:22
2023-08-16T17:18:29.702  INFO --- [   asgi_gw_0] l.s.ec2.vmmanager.docker   : Instance i-b07acefd77a3c415f port mappings (container -> host): {'8000/tcp': 29043, '22/tcp': 12862}

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

docker compose file:
version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

To reproduce the issue, just follow the steps of official docs (https://docs.localstack.cloud/user-guide/aws/elastic-compute-cloud/#docker-backend)

### Environment

```markdown
- OS: debian 12
- LocalStack: latest
```

**Comment by steffyP** [comment]
Hi @Daniel-derf, 

thanks for reaching out! Are you running LocalStack community or Pro?
The community version for EC2 only mocks the service responses. When you use LocalStack Pro you will be able to actually run EC2 instances, and then you will also see the port mappings. 

From the [docs](https://docs.localstack.cloud/user-guide/aws/elastic-compute-cloud/#introduction):
> LocalStack supports a mock implementation of EC2 via the Community offering while a fully-emulated implementation is available in the Pro/Team offering, allowing you to use the EC2 APIs in your local environment to create and manage your EC2 instances.

**Comment by Daniel-derf** [comment]
> Hi @Daniel-derf,
> 
> thanks for reaching out! Are you running LocalStack community or Pro? The community version for EC2 only mocks the service responses. When you use LocalStack Pro you will be able to actually run EC2 instances, and then you will also see the port mappings.
> 
> From the [docs](https://docs.localstack.cloud/user-guide/aws/elastic-compute-cloud/#introduction):
> 
> > LocalStack supports a mock implementation of EC2 via the Community offering while a fully-emulated implementation is available in the Pro/Team offering, allowing you to use the EC2 APIs in your local environment to create and manage your EC2 instances.

I was using Community version... Thank you
