### ISSUE TITLE
 No matching distribution found for localstack 2.x for manylinux_2_28_x86_64 platform

### ISSUE THREAD

**Issue by waiyan1612** [localstack/localstack#9477]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm trying to install localstack for `manylinux_2_28_x86_64` since I need to deploy my app to AWS Lambda. This is the command I used:
```
 pip install localstack==2.2 --platform manylinux_2_28_x86_64 --only-binary=:all: --target /tmp/mylocal-stack
```
I am getting this error.
> ERROR: Could not find a version that satisfies the requirement localstack==2.2 (from versions: 0.12.19.1, 0.12.19.2, 0.12.19.3, 0.12.19.4, 0.12.20, 0.13.0, 0.13.0.1, 0.13.0.2, 0.13.0.3, 0.13.0.4, 0.13.0.5, 0.13.0.6, 0.13.0.7, 0.13.0.8, 0.13.0.9, 0.13.0.10, 0.13.0.11, 0.13.1, 0.13.1.1, 0.13.1.2, 0.13.2, 0.13.2.1, 0.13.3, 0.13.3.1, 0.13.3.2, 0.13.3.3, 0.13.3.4, 0.13.3.5, 0.13.3.6, 0.14.0, 0.14.0.1, 0.14.0.2, 0.14.0.3, 0.14.0.4, 0.14.0.5, 0.14.0.6, 0.14.0.7, 0.14.0.8, 0.14.0.9, 0.14.0.10, 0.14.1, 0.14.1.1, 0.14.1.2, 0.14.1.3, 0.14.2, 0.14.2.1, 0.14.2.2, 0.14.2.3, 0.14.2.4, 0.14.2.5, 0.14.2.6, 0.14.2.7, 0.14.2.8, 0.14.2.9, 0.14.2.10, 0.14.2.11, 0.14.3, 0.14.3.1, 0.14.3.2, 0.14.3.3, 0.14.3.4, 0.14.3.5, 0.14.3.6, 0.14.4, 0.14.5, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.1.0, 1.2.0, 1.3.0, 1.3.1.dev20221207092718, 1.3.1.dev20221208144623, 1.3.1, 1.3.2.dev20221219124041, 1.3.2.dev20230104092258, 1.3.2.dev20230111091637, 1.3.2.dev20230116082152, 1.3.2.dev20230123090109, 1.3.2.dev20230123214937, 1.3.2.dev20230204140326, 1.3.2.dev20230204140327, 1.3.2.dev20230206202801, 1.4.0.dev1, 1.4.0.dev20230211183227, 1.4.0, 1.4.1.dev20230214124715, 1.4.1.dev20230214162849, 1.4.1.dev20230215143756, 1.4.1.dev20230215215857, 1.4.1.dev20230215233822, 1.4.1.dev20230220091228, 1.4.1.dev20230221142230, 1.4.1.dev20230221181016)
ERROR: No matching distribution found for localstack==2.2

### Expected Behavior

The binaries were available for 1.x so I am hoping it is also available for 2.x.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

Run
```
 pip install localstack==2.2 --platform manylinux_2_28_x86_64 --only-binary=:all: --target /tmp/mylocal-stack
```

### Environment

```markdown
- OS:manylinux_2_28_x86_64
- LocalStack: 2.2
```

**Comment by alexrashed** [comment]
Sorry for the late answer!
Unfortunately, there is no Python binary package of the `localstack` package on PyPi, we only publish source distributions.
But with `--only-binary=:all:` you limit `pip` to only search for binary distributions, which is why it can't find any.
However, if you want to use the CLI, you can use our binary builds.
Take a look at our installation page: https://docs.localstack.cloud/getting-started/installation/
I'll close this issue for now, please let us know if you run into any other issues.
