### ISSUE TITLE
Running Lambda Invoke causes UnrecognizedClientException: The security token included in the request is invalid.

### ISSUE THREAD

**Issue by aedemo** [localstack/localstack#948]
**I just started learning localstack.

Localstack is running perfectly. The following is my docker-compose.yml:**

```
version: '2.1'
  
services:
  localstack:
    image: localstack/localstack
    ports:
      - "4567-4583:4567-4583"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=${SERVICES- }
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=docker
      - LAMBDA_REMOTE_DOCKER=true
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

I start localstack with the following command:
`TMPDIR=/private$TMPDIR docker-compose up`

I use terraform to build the dynamoDB (main.tf):

```
provider "aws" {
    access_key = "foo"
    secret_key = "foo"
    skip_credentials_validation = true
    region = "us-east-1"
    endpoints {
      dynamodb="http://localhost:4569"
    }
}
resource "aws_dynamodb_table" "test" {
    name = "Books"
    read_capacity = 5
    write_capacity = 5
    hash_key = "ISBN"
    attribute {
      name = "ISBN"
      type = "S"
    }
}

resource "aws_dynamodb_table_item" "test" {
  table_name = "${aws_dynamodb_table.test.name}"
  hash_key = "${aws_dynamodb_table.test.hash_key}"
  item = <<ITEM
  {
    "ISBN": {"S": "978-1420931693"},
    "Title": {"S": "The Republic"},
    "Author": {"S": "Plato"}
  }
  ITEM
}
```

**The terraform executes perfectly and insert 1 record into the table.

Next I create a Lambda function (main.go):**

```
package main

import (
	"log"

	"github.com/aws/aws-lambda-go/lambda"
)

type book struct {
	ISBN   string `json:"isbn"`
	Title  string `json:"title"`
	Author string `json:"author"`
}

func show() (*book, error) {
	// Fetch a specific book record from the DynamoDB database. We'll
	// make this more dynamic in the next section.
	bk, err := getItem("978-1420931693")
	if err != nil {
		return nil, err
	}
	log.Println("thien")
	return bk, nil
}

func main() {
	lambda.Start(show)
}
```

**The following are the commands I used:
1.  `env GOOS=linux GOARCH=amd64 go build -o /tmp/main books`
2. `zip -j /tmp/main.zip /tmp/main`
3.  `awslocal lambda create-function --function-name books40 --runtime go1.x --handler main --zip-file fileb:///tmp/main.zip --role admin`
4.   awslocal lambda invoke --function-name books40 /tmp/output.json**

**On the 4th step, I get the following error:**
  `localstack_1  | 2018-10-05T01:49:50:WARNING:localstack.services.awslambda.lambda_executors: Empty event body specified for invocation of Lambda "arn:aws:lambda:us-east-1:000000000000:function:books40"
localstack_1  | 2018-10-05T01:49:52:WARNING:localstack.services.awslambda.lambda_api: Error executing Lambda function: Lambda process returned error status code: 1. Output:
localstack_1  | START RequestId: 68fc4b22-614c-19f5-6ce8-c567d542ea36 Version: $LATEST
localstack_1  | END RequestId: 68fc4b22-614c-19f5-6ce8-c567d542ea36
localstack_1  | REPORT RequestId: 68fc4b22-614c-19f5-6ce8-c567d542ea36	Duration: 692.41 ms	Billed Duration: 700 ms	Memory Size: 1536 MB	Max Memory Used: 12 MB	
localstack_1  | {
localstack_1  |   "errorMessage": "UnrecognizedClientException: The security token included in the request is invalid.\n\tstatus code: 400, request id: DU4H37U98C8N30P6FBF9LI8SMNVV4KQNSO5AEMVJF66Q9ASUAAJG",
localstack_1  |   "errorType": "requestError"
localstack_1  | }
localstack_1  |  Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 300, in run_lambda
localstack_1  |     event, context=context, version=version, asynchronous=asynchronous)
localstack_1  |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 136, in execute
localstack_1  |     result, log_output = self.run_lambda_executor(cmd, environment, asynchronous)
localstack_1  |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 69, in run_lambda_executor
localstack_1  |     (return_code, log_output))`

Please provide guidance because I ran out of ideas to try out.  Thanks.

**Comment by tusharnikam1** [comment]
@aedemo I am also having the same issue. Did you find any solution for this?

**Comment by lucianthorr** [comment]
I'm running into the same issue.  Has anyone found a workaround?

**Comment by whummer** [comment]
Hi @lucianthorr @tusharnikam1 @aedemo . When accessing LocalStack services from your Lambda code, you need to use a special endpoint address which should be available in the `LOCALSTACK_HOSTNAME` environment variable.

So, similar to how you configure your endpoint for DynamoDB in the test (`dynamodb="http://localhost:4569"`), you can configure the endpoint as `"http://$LOCALSTACK_HOSTNAME:4569"` in your Lambda code, where `$LOCALSTACK_HOSTNAME` needs to be replaced with the environment variable.

Hope that help - please let us know if that works.

**Comment by tusharnikam1** [comment]
@whummer  Thanks. It worked 👍
