### ISSUE TITLE
bug: $util.parseJson() does not return a JSON-parsable string

### ISSUE THREAD

**Issue by marco-luzzara** [localstack/localstack#9487]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am using an API Gateway where I have integrated a State Machine. The integration type is AWS and I want to return just the state machine output, so I have specified a response mapping template

```
$util.parseJson($input.path('$.output'))
```

However, with the following `output`:

```
"[{\"val\": 0}, {\"val\": 2}, {\"val\": 4}]"
```

I get this error:

```
Unable to parse template result as JSON: Expecting property name enclosed in double quotes: line 1 column 3 (char 2) - [{'val': 0}, {'val': 2}, {'val': 4}]
```

### Expected Behavior

The returned output should be 

```
[{"val": 0}, {"val": 2}, {"val": 4}]
```

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

I can provide them if you need them

### Environment

```markdown
- OS:Ubuntu 22.04
- LocalStack: latest (2.3.3.dev), image id: 6ccfae37b8ca
```

### Anything else?

I have taken a look at the source code: 
https://github.com/localstack/localstack/blob/f2afa76787f2c58f7ec82306c5efbfe9dd0e8992/localstack/services/apigateway/templates.py#L134-L136

The problem is that the `airspeed` library (that you are currently using) stringifies it and does not care whether it becomes a JSON or something else. After all, the `parseJson` function is part of the namespace that you pass. One possible solution, is to override the `__str__` method for the object returned by `parseJson`, something like:

```python
class JsonSerializableObject:
    def __init__(self, obj):
        self.obj = obj 

    def __str__(self):
        return json.dumps(self.obj)

    def __getattr__(self, attr):
        return getattr(self.obj, attr) 

class VelocityUtilApiGateway():
    def parseJson(self, s: str):
        obj = json.loads(s)
        return JsonSerializableObject(AttributeDict(obj) if isinstance(obj, dict) else obj)
```

I have tested it with:

```python
namespace = {
    "util": VelocityUtilApiGateway()
}

t = airspeed.Template('''
    {
        "result": $util.parseJson("[{\\"val\\": 0}, {\\"val\\": 2}, {\\"val\\": 4}]")
    }''')
print(t.merge(namespace))

t = airspeed.Template('''
    {
        "result": $util.parseJson("{\\"val\\": 0}")
    }''')
print(t.merge(namespace))

t = airspeed.Template('''
    #set($output = $util.parseJson("{\\"val\\": 0}"))
    {
        "result": $output.val
    }''')
print(t.merge(namespace))
```

And the object is correctly JSON-serialized. I hope this can help you solve the issue quickier. Thank you very much for all the work

**Comment by calvernaz** [comment]
Hi @marco-luzzara, I ran the same tests and don't have the same issues. I do find a different one handling function arguments that are a list of dictionaries. I'm looking into this. Thanks
