### ISSUE TITLE
Document how to disable ssl cert checking in AWS clients

### ISSUE THREAD

**Issue by kojiromike** [localstack/localstack#951]
This issue is to help people not have to do the several hours of searching I had to do to learn how to disable ssl cert checking in the Java Kinesis client. Thanks to [TJC in this other issue](https://github.com/mhart/kinesalite/issues/56#issuecomment-352625282) you can use

```bash
java -Dcom.amazonaws.sdk.disableCertChecking
```

when running the java sdk to avoid cert checking.

**Comment by whummer** [comment]
Thanks for reporting this fix @kojiromike - would you mind raising a pull request which adds a small paragraph to the `Troubleshooting` section of the README? (Users are more likely to find it there, rather than in this issue.) That would be great, thanks!

**Comment by khitsik** [comment]
@kojiromike @whummer what about aws sdk for node js? maybe you know something. I`m looking for the the solution for 2 days already

**Comment by ravimajji** [comment]
thanks much
