### ISSUE TITLE
bug: Library versions are mismatched in Glue 4.0, resulting in failed execution

### ISSUE THREAD

**Issue by snhardin** [localstack/localstack#9526]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Running a job in Glue 4.0 mode in Localstack results in the wrong libraries being downloaded. Spark is consistent with the version expected for Glue 4.0 (3.3.0), but other libraries such as Log4J are still using versions expected for Glue 3.0. This is causing compatibility issues that is causing our Glue job to fail.

For example, Localstack is still pulling Log4J 2.14.0 when it should be pulling a version >2.17.0 (as referenced by the `amazon/aws-glue-libs:glue_libs_4.0.0_image_01` docker image). We suspect that this is causing the following stacktrace:

![log4j problem](https://github.com/localstack/localstack/assets/16845804/ffba299a-ee57-43f0-9813-64270e441784)

This error does not occur when running the job for Glue 3.0.

### Expected Behavior

The Glue job successfully executes as it does when set to run in Glue 3.0.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

Run a Glue job that uses PySpark and creates a dataframe set to run for Glue 4.0. A library compatibility issue will cause the execution to fail.

### Environment

```markdown
- OS: Mac OS X 12.7
- LocalStack: 2.3.0
```

**Comment by silv-io** [comment]
Hi @snhardin, thank you for submitting the issue.
We have pushed changes that should resolve the problem. I will be included in the upcoming release.
