### ISSUE TITLE
Docker image 0.8.7 got overwritten 3 days ago

### ISSUE THREAD

**Issue by ducanhkhu-ovo** [localstack/localstack#953]
We have been using localstack `0.8.7` for the past 3 months. Today, we got an error in our CICD pipeline and we managed to pin it down to localstack `0.8.7` version has been silently overwritten 3 days ago. From this screenshot, it looks like the same thing has happened to version `0.8.0` where the Docker image was also overwritten. Is there a reason why instead of releasing `0.8.8`, localstack chose to override `0.8.7` version or did something go wrong with the release process?

<img width="1920" alt="screenshot 2018-10-08 at 16 32 09" src="https://user-images.githubusercontent.com/36504063/46619037-f7b09a80-cb18-11e8-831a-bedbdb3a90d7.png">

**Comment by mrobinsn** [comment]
We're running into the same issue. Downgrading to `0.8.6` (which hasn't been overwritten yet) seems to have fixed our test failures for now.

**Comment by mangatmodi** [comment]
@mrobinsn Downgrading to 0.8.6 fixed mine issues too!

**Comment by matelang** [comment]
Happened to us as well. I think it's pointless to version binary artifacts if you can't take their immutability for granted.

**Comment by ewaltman** [comment]
👍

**Comment by portenez** [comment]
👍  and 😢

**Comment by whummer** [comment]
Thanks for reporting @ducanhkhu-ovo . The image got pushed accidentally - this should indeed not happen. We'll make sure this doesn't happen again in the future.
