### ISSUE TITLE
enhancement request: Add support for Fn::GetAZs CloudFormation intrinsic function

### ISSUE THREAD

**Issue by lukasz-mazur2** [localstack/localstack#9534]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Enhancement description

Hello,

Localstack Pro user here.
We are in the process of adapting Localstack to our workflow/pipelines to reduce the load on our AWS accounts. In out organization we are heavily using CloudFormation and unified custom modules for IaC components. Some of the modules rely on the Fn::GetAZs CloudFormation intrinsic function. It would be a great help if it was supported in Localstack as well.

**Comment by pinzon** [comment]
The feature has been merged. Please pull the latest image.
