### ISSUE TITLE
enhancement request: SNS respect subscription retry configuration (http(s) subscriber)

### ISSUE THREAD

**Issue by ls-robert-holosynskyi** [localstack/localstack#9542]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Enhancement description

When AWS SNS sends a SubscriptionConfirmation message to an HTTP endpoint the endpoint must ack the subscription by calling AWS API as [described here](https://docs.aws.amazon.com/sns/latest/dg/SendMessageToHttp.prepare.html). 

If the endpoint error out while processing a request or the message does not arrive to the endpoint for more other reason AWS SNS claims that the message will be delivered based on the delivery policy of the subscription. This behaviour is described [here in point 6](https://docs.aws.amazon.com/sns/latest/dg/SendMessageToHttp.prepare.html). 

Localstack does not retry failed deliveries.

In my app I am provisioning SNS topics and should start using them once the subscription is confirmed. So I am testing the error cases locally and discovered this.

### 🧑‍💻 Implementation

Respective delivery policy could be complicated to implement. The delivery policy allows to configure throttling and backoff functions for the retries. In my specific case I do not need localstack to handle all aspects of delivery policy. Handling just the retries is enough.

**Comment by bentsku** [comment]
Hello @ls-robert-holosynskyi and thanks for your feature request! We already have this feature request here with #8513.

I'll close this in favor of the already opened one, you can go and react with a 👍 there so that we could prioritize the request. Thank you!
