### ISSUE TITLE
AWS Bedrock Support

### ISSUE THREAD

**Issue by chezsmithy** [localstack/localstack#9544]
We are interested in AWS Bedrock support.

Perhaps as an early use case we could implement a kind of wiremock type request response model where we could take in the prompts and return a canned set of responses based on an input to output mapping model for each test case.

**Comment by chcohen** [comment]
Hi, is there any update regarding this?

**Comment by bhargav-11** [comment]
Bump

**Comment by chcohen** [comment]
Hi everyone, here is an answer I got in Localstack's slack channel:
"We have a first preview released on the latest. Please check our docs to learn more: https://docs.localstack.cloud/user-guide/aws/bedrock/
The implementation is mocked right now! We are soon coming up with full emulation with LLMs running on your local machine."

**Comment by silv-io** [comment]
Hi @chezsmithy, @bhargav-11 and @chcohen! Happy to announce that we have added initial Bedrock support in LocalStack 4.0! You can now locally run LLMs, use the `converse` and `invoke-model` endpoints and do batch processing.

You can check our [release blog for more info](https://blog.localstack.cloud/announcing-localstack-40-general-availability/)
