### ISSUE TITLE
Receiving SQS Messages seeing a different behaviour in my test between localstack version 1.0.3 vs  >=1.0.4

### ISSUE THREAD

**Issue by manoj-fd** [localstack/localstack#9546]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am running a tests which retrieve the SQS messages from queue and validate the number of messages received.

Observing a difference in behaviour between localstack versions 1.0.3 vs >=1.0.4, which results to a test assertion failure

java.lang.AssertionError: 
**Expected size: 9 but was: 8 in:**

Code used to retrieve SQS Messages
```

final ReceiveMessageRequest receiveMessageRequest = new ReceiveMessageRequest(
					sqs.getQueueUrl( queueName ).getQueueUrl() )
					.withMaxNumberOfMessages( 10 );
messagesList.addAll( sqs.receiveMessage( receiveMessageRequest ).getMessages() );

return messagesList;
```

### Expected Behavior

Expecting consistent behaviour with latest localstack versions

### How are you starting LocalStack?

Custom (please describe below)

### Steps To Reproduce

Using Java + LocalStack container

Initialising the container with below code
```

LocalStackContainer aws = new LocalStackContainer( 
					DockerImageName.parse(localstack/localstack:2.3.0 ) ).withServices( SNS, SQS, S3 )
					.withEnv( "S3_SKIP_SIGNATURE_VALIDATION", "0" );
```

### Environment

```markdown
- OS: macOS Monterey
- LocalStack: LocalStack v2.3.0
```

**Comment by bentsku** [comment]
Hello @manoj-fd and thanks for your report.

This issue does not really indicate what is AWS behaviour, did you run your test case against it? Behaviour of LocalStack is bound to change between versions, as we are striving to get closer and closer to how AWS behaves, which will result in bug fixes and changes. Could you confirm your test case runs against AWS and the behaviour is now wrong?
