### ISSUE TITLE
PORT_WEB_UI does not work with localstack start --docker

### ISSUE THREAD

**Issue by stuartleylandcole** [localstack/localstack#956]
https://github.com/localstack/localstack/issues/303 includes a fix to override the port that the web UI runs on. This was reported as working when running Localstack like this:

```
PORT_WEB_UI=9080 docker-compose up
```

but does not work when running Localstack in Docker like this:

```
PORT_WEB_UI=9010 localstack start --docker
```

This is the output from `docker ps` on my machine after running the above command:

```
539e23c18c5a        localstack/localstack                                       "/usr/bin/supervisor…"   8 minutes ago       Up 8 minutes        4567-4568/tcp, 0.0.0.0:4569->4569/tcp, 4570-4583/tcp, 0.0.0.0:8080->8080/tcp   clever_lewin
```

You can see that Docker port 8080 is still mapped to local port 8080.

This issue has been reported in https://github.com/localstack/localstack/issues/303 but the issue has been closed since September 2017. I'm happy for this issue to be closed and the original one re-opened if that's preferable but I felt like it was worth raising separately for visibility.

**Comment by brettcooper** [comment]
I'm facing this issue as well.

**Comment by Marco-Ruggiero** [comment]
When running `localstack start --docker`, it at least echos the docker command. For now, I've been copy pasting that command and editing te first -p argument from `8080:8080` to  `$PORT_WEB_UI:$PORT_WEB_UI`, like

docker run -it -e SERVICES="s3" -e LOCALSTACK_HOSTNAME="localhost" -e PORT_WEB_UI="8081" -p `8081:8081`  -p 4572:4572 -v "/tmp/localstack:/tmp/localstack" -v "/var/run/docker.sock:/var/run/docker.sock" -e DOCKER_HOST="unix:///var/run/docker.sock" -e HOST_TMP_FOLDER="/tmp/localstack" "localstack/localstack"

**Comment by jdarling** [comment]
This is a problem for me as well

**Comment by whummer** [comment]
Thanks for reporting @stuartleylandcole - should be fixed in the latest version.
