### ISSUE TITLE
Unimplemented ElastiCache API - Part 2

### ISSUE THREAD

**Issue by Ramilito** [localstack/localstack#9571]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Trying to create an aws_elasticache_cluster using Terraform:
```
resource "aws_elasticache_cluster" "example" {
  cluster_id           = "cluster-example"
  engine               = "redis"
  node_type            = "cache.t3.micro"
  num_cache_nodes      = 1
  parameter_group_name = "default.redis6.x"
  port                 = 6379
  engine_version       = "6.2"
}

```

Getting this error:
```
creating ElastiCache Cache Cluster (cluster-example): InternalFailure: API for service 'elasticache' not yet implemented or pro feature - please check https://docs.localstack.cloud/references/coverage/ for further information
        status code: 501, request id: f382f666-692b-4ee3-b928-34ec289be2da

  on main.tf line 67, in resource "aws_elasticache_cluster" "example":
  67: resource "aws_elasticache_cluster" "example" {

```

### Expected Behavior

I'm expecting a aws_elasticcache_cluster to be created, other resources are working fine such as s3 and dynamodb.
Also using the cli works fine:
aws --no-verify-ssl --endpoint-url=https://localstack.mydomain.local:443 es create-elasticsearch-domain --domain-name my-domain

### How are you starting LocalStack?

Custom (please describe below)

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

I'm using the helm chart to install localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

Terraform with the manual steps:
provider "aws" {
  access_key = "fakeAccessKeyId"
  secret_key = "fakeSecretAccessKey"
  region     = "eu-north-1"

  # only required for non virtual hosted-style endpoint use case.
  # https://registry.terraform.io/providers/hashicorp/aws/latest/docs#s3_use_path_style
  s3_use_path_style           = true
  skip_credentials_validation = true
  skip_metadata_api_check     = true
  skip_requesting_account_id  = true

  insecure = true
  endpoints {
    s3             = "https://localstack.mydomain.local:443"
    dynamodb       = "https://localstack.mydoma$.local:443"
    elasticache    = "https://localstack.mydomaind.local:443"
    elasticsearch  = "https://localstack.mydomain.local:443"
  }
}
resource "aws_elasticache_cluster" "example" {
  cluster_id           = "cluster-example"
  engine               = "redis"
  node_type            = "cache.t3.micro"
  num_cache_nodes      = 1
  parameter_group_name = "default.redis6.x"
  port                 = 6379
  engine_version       = "6.2"
}

### Environment

```markdown
- OS: Ubuntu 22.04
- LocalStack: helm chart version 0.6.5
```

### Anything else?

Tried with terraform cli version 0.13.7 as suggested in the Tips section

**Comment by alexrashed** [comment]
Hi @Ramilito!
With the current efforts to release LocalStack version 3, there will be a newly written ElastiCache provider.
The changes are already in the `latest` tag (since 9th of November) and will be released tomorrow.
Could you please try if this issue also occurs with the latest image? Please make sure to explicitly pull the `latest` tag with `docker pull localstack/localstack:latest` to make sure it's up to date.
Thanks!

**Comment by Ramilito** [comment]
Hey!
Tried it again multiple times, first deleting the image and then doing a manual pull but getting the same issue error. Anything else I need to do or try?

**Comment by alexrashed** [comment]
Hi @Ramilito!
Sorry for the inconvenience, my last suggested command was wrong.
ElastiCache is a service only supported in our paid offerings (as the error message implies).
If you have a paid subscription, please make sure to update the `localstack/localstack-pro` image (`docker pull localstack/localstack-pro:latest`).
Thanks!

**Comment by Ramilito** [comment]
Oh I see! Thought I checked the docs that it was on free tier, closing the issue!
