### ISSUE TITLE
bug: VTL $util.time and string.indexOf, string.substring() not working

### ISSUE THREAD

**Issue by lqtruong** [localstack/localstack#9589]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi Pro Team,

We use Localstack Pro and in our VTL template, we use the `$util.time` package to convert time to a long timestamp number. 
But it returns empty
```
#set($seconds = $util.time.epochMilliSecondsToSeconds($milliSeconds)) ==> failed, $seconds is empty or undefined
#set($milliSeconds = $util.time.parseISO8601ToEpochMilliSeconds($date)) ==> failed, $milliSeconds is empty or undefined
```

Also, we use `$util.escapeJavaScript` and it failed. The result is empty or undefined

And we use `$string.substring(from,to)` as well as `$string.indexOf('char')`, both returned empty or undefined value

```
#set($productPK = "PRODUCTID#123-123-123")
#set($productPKOffset = $productPK.SK.indexOf('#') + 1) ## failed
#set($productId = $productPK.substring($productPKOffset, $productPK.length())) ## failed
```

References:

- Util time [helpers](https://docs.aws.amazon.com/appsync/latest/devguide/time-helpers-in-util-time.html)

Thank you very much for your support.
cc @simon

### Expected Behavior

We expect that 

- All functionalities in package $util.time that work perfectly without errors
- `$string.indexOf('char')` and `$string.substring(from,to)`  that work perfectly without errors

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker-compose up

### Environment

```markdown
- OS: MacOs Monterey
- LocalStack: Pro latest
```

### Anything else?

No.

**Comment by lqtruong** [comment]
More infos on the error of .indexOf('char') can be seen as below
```
{
    "data": {
        "listUsers": null
    },
    "errors": [
        {
            "message": "Error in template '<string>' at position 213-257 in expression: ($userIdOffset = $item.PK.indexOf('#') + 1)\n\nTypeError: can only concatenate str (not \"int\") to str",
            "locations": [
                {
                    "line": 2,
                    "column": 3
                }
            ],
            "path": [
                "listUsers"
            ],
            "errorType": "TemplateExecutionError"
        }
    ]
}
```
Thanks

**Comment by simonrw** [comment]
Hi @lqtruong thanks for reporting these issues. We believe that `string.indexOf` and `string.substring` should be fixed in our upstream dependency for VTL rendering: https://github.com/localstack/airspeed/pull/16. This is not in the latest image right now but we will update this issue when we have included the latest package.

We will continue to work on the missing `$util.time` helper functions in the meantime. Thank you for your patience.

**Comment by simonrw** [comment]
Hi @lqtruong , the `string.indexOf` and `string.substring` changes should be in the latest docker image. Could you pull that and see if your issues are fixed. 

I will split out the `$util.time` helper function issue into a new issue to track that bug.
