### ISSUE TITLE
bug: DynamoDB Scan Filter Expression not working anymore

### ISSUE THREAD

**Issue by lqtruong** [localstack/localstack#9594]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi LS Pro Team,

This is the `regression issue` when previous Localstack Pro was working. But from latest pull one day ago (from `9-Nov-2023`), the Scan operation VTL did not work any longer

# Steps to reproduce the issue

- Create a DynamoDB table `User` with PK=HASH and SK=RANGE keys
- Insert data to this table with users, PK=USERID#<id>, SK=METADATA as pattern
- Scan this table using filtering expression

VTL DynamoDB template
```
{
  "version": "2018-05-29",
  "operation": "Scan",
  "consistentRead": true,
  "filter": {
    "expression": "#SK=:SK",
    "expressionNames": {
      "#SK": "SK"
    },
    "expressionValues": {
      ":SK": $util.dynamodb.toDynamoDBJson("METADATA")
    }
  }
}
```

This Scan operation gave error as below
```
{
    "data": {},
    "errors": [
        {
            "message": "Parameter validation failed:\nInvalid type for parameter ScanFilter.expression, value: #SK=:SK, type: <class 'str'>, valid types: <class 'dict'>\nMissing required parameter in ScanFilter.expressionNames: \"ComparisonOperator\"\nUnknown parameter in ScanFilter.expressionNames: \"#SK\", must be one of: AttributeValueList, ComparisonOperator\nMissing required parameter in ScanFilter.expressionValues: \"ComparisonOperator\"\nUnknown parameter in ScanFilter.expressionValues: \":SK\", must be one of: AttributeValueList, ComparisonOperator",
            "locations": [
                {
                    "line": 2,
                    "column": 3
                }
            ],
            "path": [
                "listUsers"
            ],
            "errorType": "ParamValidationError"
        }
    ]
}
```

### Expected Behavior

It would be very grateful to get it work with Scan Filter Expression.
Many thanks for your support.

cc @simonrw

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker-compose up

### Environment

```markdown
- OS: Monterey
- LocalStack: Pro License
```

### Anything else?

No.

**Comment by simonrw** [comment]
Hi @lqtruong, we recently merged some changes into the latest image. Could you pull the latest image and verify? I will close this issue as fixed, but if the problem continues please feel free to either re-open this issue or create a new issue with the specific problem.

**Comment by lqtruong** [comment]
Hi @simonrw 

Thank you very much for your very kind support. I will try to recheck them and let us know soon. Many thanks
