### ISSUE TITLE
Bug: creating sqs queue in localstack:  localstack.aws.protocol.parser.ProtocolParserError: Operation detection failed. Missing Action in request for query-protocol service ServiceModel(sqs).

### ISSUE THREAD

**Issue by petrovskyyanton** [localstack/localstack#9610]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

    queue = sqs.create_queue(QueueName="Queue")

    queue = sqs.create_queue(QueueName="Queue")
/usr/local/lib/python3.11/site-packages/botocore/client.py:535: in _api_call
    return self._make_api_call(operation_name, kwargs)
/usr/local/lib/python3.11/site-packages/botocore/client.py:980: in _make_api_call
    raise error_class(parsed_response, operation_name)
E   botocore.exceptions.ClientError: An error occurred (500) when calling the CreateQueue operation (reached max retries: 4): <?xml version='1.0' encoding='utf-8'?>
E   <ErrorResponse xmlns="http://queue.amazonaws.com/doc/2012-11-05/"><Error><Code>InternalError</Code><Message>exception while calling sqs with unknown operation: Traceback (most recent call last):
E     File &quot;/opt/code/localstack/localstack/aws/chain.py&quot;, line 90, in handle
E       handler(self, self.context, response)
E     File &quot;/opt/code/localstack/localstack/aws/handlers/service.py&quot;, line 64, in __call__
E       return self.parse_and_enrich(context)
E              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E     File &quot;/opt/code/localstack/localstack/aws/handlers/service.py&quot;, line 77, in parse_and_enrich
E       operation, instance = parser.parse(context.request)
E                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E     File &quot;/opt/code/localstack/localstack/aws/protocol/parser.py&quot;, line 172, in wrapper
E       return func(*args, **kwargs)
E              ^^^^^^^^^^^^^^^^^^^^^
E     File &quot;/opt/code/localstack/localstack/aws/protocol/parser.py&quot;, line 366, in parse
E       raise ProtocolParserError(
E   localstack.aws.protocol.parser.ProtocolParserError: Operation detection failed. Missing Action in request for query-protocol service ServiceModel(sqs).
E   </Message></Error><RequestId>a3709c18-14cf-4665-8fec-8201fc31a871</RequestId></ErrorResponse>

### Expected Behavior

Must create sqs queue

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    environment:
      - SERVICES=sqs, sns
      - AWS_DEFAULT_REGION=eu-west-1
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_ENDPOINT_URL=http://localstack:4566
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - PORT_WEB_UI=8080
      - LAMBDA_EXECUTOR=docker-reuse
    ports:
      - "4566-4599:4566-4599"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:4566/health"]
      interval: 10s
      timeout: 30s
      retries: 3
    tty: true
    networks:
      - network

### Environment

```markdown
- OS: MacOS Sonoma 14.0
- LocalStack: localstack/localstack:latest
```

**Comment by Idane** [comment]
Something similar happened to me, switching to tag `2.3.2` solved it

**Comment by petrovskyyanton** [comment]
> Something similar happened to me, switching to tag `2.3.2` solved it

Unfortunately,  switching to tag 2.3.2 didn't work in my case.

**Comment by bentsku** [comment]
Hi, this is a duplicate from #8267. However, we've been working on a fix, could you try pulling the `latest` image and try again to see if that would solve your issue? Thanks! 

I'll close in favor of the mentioned issue.

**Comment by anubhav8421** [comment]
I am using aws cli to interact with localstack. 

I have updated the localstack docker images using `localstack update docker-images` and restarted the localstack using `localstack start -d`

I am still facing this issue. 

Please help

**Comment by bhagyashree-marekar-polestar** [comment]
Switching to 2.3.2, did not work

**Comment by bhagyashree-marekar-polestar** [comment]
Hi @anubhav8421, thank you for quickly responding to my query. Actually, I was encountering an issue with creating an SQS queue in localstack: localstack.aws.protocol.parser.ProtocolParserError: Operation detection failed. Missing Action in request for query-protocol service ServiceModel(sqs). However, I resolved it by downgrading the version of the AWS CLI.

**Comment by getblad** [comment]
The problem was also solved by updating to version 3.0.3

**Comment by HaroonSaid** [comment]
When do we expect a container version of V3.0.3

**Comment by dheimann-nyt** [comment]
Also running into the same issue on the docker image, waiting on 3.0.3

**Comment by douglasjam** [comment]
For me, this fixes: `composer update  aws/aws-sdk-php:3.283.12`

**Comment by redging-very-well** [comment]
I had the same issue in my localstack logs, followed by a 500 error. My typescript application was throwing an exception  when trying to enqueue a message to SQS, which was pretty unhelpful:

```
    "statusCode": 500,
    "reason": "",
    # .... headers and other stuff...
 ```

I was on localstack 2.3.2; upgrading to the latest (3.1 at the time of writing) solved the issue for me.
I was using the typescript aws sqs client (@aws-sdk/client-sqs) version 3.509.0.

**Comment by sorcer007** [comment]
docker always solve my problem 😄 
`docker run --rm -it -p 4566:4566 -p 4510-4559:4510-4559 localstack/localstack:3.0.2`

**Comment by andrelegault** [comment]
This started happening again with the release of this image: https://hub.docker.com/layers/localstack/localstack/latest-amd64/images/sha256-f6796a299e845f2bd9f7cd1e46564c29e9276bd5d1bba24c486fa8d4d3c1c888?context=explore

**Comment by dlazarevAtC8** [comment]
Can confirm this is reproducing now as well, but what's funny we have same issue on actual was sqs

**Comment by adiberk** [comment]
I know this is super old but what do we do if we can't upgrade past 2.3.2 as of now? We are coming to the point where we can't pin the botocore library to 1.31.80 anymore.
