### ISSUE TITLE
bug: SQS createQueue fails with Service sqs-query is not enabled

### ISSUE THREAD

**Issue by holomekc** [localstack/localstack#9615]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

With docker image tag 2.3.3 sqs.createQueue fails with:
AWS sqs-query.CreateQueue => 501

Service 'sqs-query' is not enabled. Please check your 'SERVICES' configuration variable.

Rollback to 2.3.2 works fine again.

### Expected Behavior

SQS queue creation is working fine.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker-compose.yml

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal --region=<some-region> sqs create-queue --queue-name <some-name>

### Environment

```markdown
- OS: macOS 14.1
- LocalStack: 2.3.3
```

**Comment by dfangl** [comment]
This will be fixed with #9607 .
