### ISSUE TITLE
Step Function V2 Wait using timestamp broken

### ISSUE THREAD

**Issue by adiberk** [localstack/localstack#9623]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior
USING PROVIDER_OVERRIDE_STEPFUNCTIONS=v2 flag!
I apologize if this should be posted somewhere else, but I would appreciate any help if possible.
I tested the wait part of the step function in aws and didn't have any issues (You can also remove the Lambda Function call and just have it end after the wait step - the issue should still show up)

I have a step function with the following configuration
```{
  "Comment": "A description of my state machine",
  "StartAt": "Wait",
  "States": {
    "Wait": {
      "Type": "Wait",
      "Next": "Invoke Lambda Email Service",
      "TimestampPath": "$.timeToWaitToSendEmail"
    },
    "Invoke Lambda Email Service": {
      "Type": "Task",
      "Resource": "arn:aws:states:::lambda:invoke",
      "OutputPath": "$.Payload",
      "Parameters": {
        "Payload.$": "$",
        "FunctionName": "arn:aws:lambda:us-east-1:000000000000:function:forward_emails_to_email_service"
      },
      "End": true
    }
  }
}
```

When I call it from awscli or from my python application 
`awslocal stepfunctions start-execution --state-machine-arn "arn:aws:states:us-east-1:000000000000:stateMachine:send_emails" --input '{"timeToWaitToSendEmail": "2023-11-13T21:26:00Z"}'`

I then get the following error

`2023-11-14T02:25:23.417 ERROR --- [ead-8 (eval)] l.s.s.a.c.eval_component   : Exception '<class 'TypeError'>':'strptime() argument 1 must be str, not list' at '[ASL] [gene] [TimestampPath]: '(TimestampPath| {'path': '$.timeToWaitToSendEmail'})'.'`

`localstack  | 2023-11-14T02:25:23.417 ERROR --- [ead-8 (eval)] l.s.s.a.c.eval_component   : Exception '<class 'TypeError'>':'strptime() argument 1 must be str, not list' at '[ASL] [gene] [StateWait]: '(StateWait| {'comment': None, 'input_path': (InputPath| {'input_path_src': '$'}), 'output_path': (OutputPath| {'output_path': '$'}), 'state_entered_event_type': 'WaitStateEntered', 'state_exited_event_type': 'WaitStateExited', 'name': 'Wait', 'state_type': <StateType.Wait: 20>, 'continue_with': <localstack.services.stepfunctions.asl.component.state.state_continue_with.ContinueWithNext object at 0xffff7fe04050>, 'wait_function': (TimestampPath| {'path': '$.timeToWaitToSendEmail'})})'.'`

### Expected Behavior

I expect that the function will wait until the expected time and then execute the lambda function

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker-compose.yml

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal  stepfunctions create-state-machine --name ${file_name} --definition "${function}" --role-arn arn:aws:iam::000000000000:role/step-function-lambda
    
    awslocal stepfunctions start-execution --state-machine-arn "arn:aws:states:us-east-1:000000000000:stateMachine:send_emails" --input '{"timeToWaitToSendEmail": "2023-11-13T21:26:00Z"}'

### Environment

```markdown
- OS: Mac Sonoma 14.1
- LocalStack: 2.3.0 and 2.3.2
```

**Comment by MEPalma** [comment]
Thanks for putting together this report. I'll mark this issue as resolved since it appears to be addressed in the latest version of LocalStack. If the problem persists on your end, please inform us so that we can further investigate.

**Comment by adiberk** [comment]
Unfortunately - I can't upgrade past localstack 2.3.2 due to infrastructure issues at my company.  Happy to do the fix myself and create my own private release.  Can anyone point me in the right direction? @MEPalma
