### ISSUE TITLE
bug: RDS -  describe-db-instances  does not work with dbi-resource-id

### ISSUE THREAD

**Issue by MarcelStranak** [localstack/localstack#9625]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The `dbi-resource-id` is not currently supported as an option in the `--filters` under the command `aws rds describe-db-instances`.

### Expected Behavior

It is expected to function in a manner similar to that of the previously implemented `db-instance-id`.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

```bash
localstack start
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```bash

awslocal rds create-db-instance --db-instance-identifier test-postgres-instance --db-instance-class db.t3.micro --engine postgres

DBINSTANCEID=$(awslocal rds describe-db-instances --query DBInstances[0].DBInstanceIdentifier --output text)
DBI=$(awslocal rds describe-db-instances --query DBInstances[0].DbiResourceId --output text)

awslocal rds describe-db-instances --filters Name=dbi-resource-id,Values=$DBI
awslocal rds describe-db-instances --filters Name=db-instance-id,Values=$DBINSTANCEID
```

### Environment

```markdown
- OS: Windows 11
- LocalStack: latest
```

### Anything else?

This filter method is used in Terraform, but it fails to deploy multiple RDS instances because it cannot find the resource RDS and confirm the deployment.

```
"http.request.body": "Action=DescribeDBInstances&Filters.Filter.1.Name=dbi-resource-id&Filters.Filter.1.Values.Value.1=db-6C82833A&Version=2014-10-31",

error: reading RDS DB Instance (postgresqltest314): couldn't find resource"
```

**Comment by leviem1** [comment]
@steffyP This directly relates to #9577 as this was the exact issue I was encountering

**Comment by leviem1** [comment]
@steffyP Is this issue also resolved?

**Comment by MarcelStranak** [comment]
Hi @leviem1, this is now resolved.
