### ISSUE TITLE
bug: V3 S3 Provider .. object LastModified timestamps too precise?

### ISSUE THREAD

**Issue by matt-mercer** [localstack/localstack#9637]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when querying the s3api  against latest localstack LastModified timestamps are being displayed to microsecond precision ..  I THINK this may be causing problems for us when using s3 sync ...

previously we could do 
`awslocal  s3 sync s3://local-resources/ca-refresh/ /tmp/certs --exact-timestamps --exclude="*" --include=crl.pem --no-progress` and if the file was unchanged ... it would not be re-downloaded, since pulling latest, now running 
`awslocal  s3 sync s3://local-resources/ca-refresh/ /tmp/certs --exact-timestamps --exclude="*" --include=crl.pem --no-progress` will download the file every time .. regardless even if the source file has not been modified 

I suspec this may be down to the LastModified timestamp format?

this is a s3api list-objects-v2 response from localstack
awslocal s3api list-objects-v2 --bucket local.crl.store
```{
    "Contents": [
        {
            "Key": ".well-known/jwks.json",
            "LastModified": "2023-11-14T22:22:51.188952+00:00",
            "ETag": "\"7c6fae6e0f26d2ca3d30b05c771af40d\"",
            "Size": 1632,```

this is one from aws 

aws s3api list-objects-v2 --bucket=crl.nhs.uk
```{
    "Contents": [
        {
            "Key": "PTL/",
            "LastModified": "2022-08-04T15:49:35+00:00",
```

### Expected Behavior

repeatedly running `aw s3 sync` with `--exact-timestamps` should not redownload a file if the source s3 object has not been modified ...

should be able to run a command like this against localstack and only download file once 
`awslocal  s3 sync s3://local-resources/ca-refresh/ /tmp/certs --exact-timestamps --exclude="*" --include=crl.pem --no-progress`

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

  docker-compose.yml

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```shell
echo 'hello' > test.txt
awslocal s3 cp ./test.txt s3://local-resources/
mkdir -p sync
awslocal  s3 sync s3://local-resources/ ./sync --exact-timestamps --exclude="*" --include=test.txt --no-progress
# download: s3://local-resources/test.txt to sync/test.txt

awslocal  s3 sync s3://local-resources/ ./sync --exact-timestamps --exclude="*" --include=test.txt --no-progress
# download: s3://local-resources/test.txt to sync/test.txt

awslocal  s3 sync s3://local-resources/ ./sync --exact-timestamps --exclude="*" --include=test.txt --no-progress
# download: s3://local-resources/test.txt to sync/test.txt
```

### Environment

```markdown
- OS: Ubuntu 22.04
- LocalStack: latest
```

**Comment by matt-mercer** [comment]
think may also be an issue v3 release / s3 provider  https://github.com/localstack/localstack/issues/9519

**Comment by bentsku** [comment]
Hello @matt-mercer, you're right! I'll get a fix shortly today. Thanks for the report!

**Comment by matt-mercer** [comment]
> Hello @matt-mercer, you're right! I'll get a fix shortly today. Thanks for the report!

awesome .. I would have fixed, but I couldn't obviously spot the datetime to string serialisation ..

**Comment by bentsku** [comment]
No worries! I was a bit aware this might happen, S3 has 2 datetime format, the RFC1123 and ISO8601 without milliseconds.
The default serialization is happening in our ASF serializer, but as this is S3 specific, I believe I might be able to return a string directly. I'll try that 😄

**Comment by bentsku** [comment]
The PR has now been merged, the new `latest` image will be available in the next hour or so. Thank you so much again for your report! 

The issue should now be fixed, I could also confirm with `s3 sync`:
```bash
$ echo 'hello' > test.txt
$ awslocal s3 mb s3://local-resources
make_bucket: local-resources
$ awslocal s3 cp ./test.txt s3://local-resources/
upload: ./test.txt to s3://local-resources/test.txt           
$ mkdir -p sync
$ awslocal  s3 sync s3://local-resources/ ./sync --exact-timestamps --exclude="*" --include=test.txt --no-progress
download: s3://local-resources/test.txt to sync/test.txt
$ awslocal  s3 sync s3://local-resources/ ./sync --exact-timestamps --exclude="*" --include=test.txt --no-progress
$ awslocal  s3 sync s3://local-resources/ ./sync --exact-timestamps --exclude="*" --include=test.txt --no-progress
```
