### ISSUE TITLE
Kinesis - checkpointing tables

### ISSUE THREAD

**Issue by walshe-boylesoftware** [localstack/localstack#964]
If I am using localstack to simulate kinesis locally.. how can I stop it using real remote dynamodb tables for checkpointing etc ?

**Comment by Matt343** [comment]
You need to configure your dynamodb client to point to the localstack endpoint for dynamodb instead of the real endpoint. The checkpointing tables are managed by the KCL, not Kinesis itself.

**Comment by walshe-boylesoftware** [comment]
any idea how I do this ?

**Comment by whummer** [comment]
Thanks for providing a solution - closing this one as resolved. Please report here if the problem persists. Thanks
