### ISSUE TITLE
bug: APIGW Websockets postToConnections wont work when stage name is appended to apiEndpoint

### ISSUE THREAD

**Issue by kingster307** [localstack/localstack#9649]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In AWS stage_name needs to be appended to apiEndpoint in order for a connect event to succeed 

In LS if stage name is appended to apiEndpoint connect will succeed but any message send from lambda back to client utilizing post_to_connection will fail

In LS If stageName is not appended to apiEndpoint connect will succeed and any message sent back to client will also succeed  

### Expected Behavior

post_to_connection should work when connect is made with stage_name appended to apiEndpoint

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

[please See repo/branch here. Once Cloned run `make all run-ui`](https://github.com/kingster307/localstack_ws_bugs/tree/localstack_ws_bugs_generic)

### Environment

```markdown
- OS: Mac M1 
- LocalStack: latest && 2.3.2
```

**Comment by kingster307** [comment]
[solution can be tested in AWS by simply switching out PulumiUtil.awsProvider (just comment one out then uncomment the other) ](https://github.com/kingster307/localstack_ws_bugs/blob/localstack_ws_bugs_generic/iac/src/pulumi-provider.ts#L14)

**Comment by calvernaz** [comment]
Hi @kingster307 thanks for providing always a way to reproduce the issue. Just so I get the same behaviour I should use one of the red buttons to connect and then use the "ws ping" button to exercise the post_to_connection API right?

I do receive a response from ping.
<img width="500" alt="Screenshot 2023-11-19 at 23 15 30" src="https://github.com/localstack/localstack/assets/1269712/f35494c7-8574-4415-9b8f-099aaa66ec39">

**Comment by kingster307** [comment]
@calvernaz if you hit the blue connect then hit ping you'll be able to visually see what the response should look like....the blue connect works in LS but not in AWS while the red connects work in AWS but not in LS (localstack)

**Comment by kingster307** [comment]
@calvernaz Just checking in, any update on this?

**Comment by calvernaz** [comment]
Hi @kingster307 tackling this at the moment, first I had to fix the handling stage property being passed or extracted as request parameters on another issue, and now coming back to this. It's failing before it reaches the API Management so it might require some extra validation.

Will report back once is done.

**Comment by calvernaz** [comment]
Hi @kingster307 the fix should be available in the latest image, so please give it a go 👍
