### ISSUE TITLE
bug: API action 'CreateActivity' for service 'stepfunctions' not yet implemented or pro feature

### ISSUE THREAD

**Issue by abdulbasit1149** [localstack/localstack#9660]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello, I have been using localstack for a little while to mock out step function locally and recently I upgraded to localstack version `3.0.0`  and have been getting the follow error:

```
2023-11-16T15:30:18.963  INFO --- [   asgi_gw_0] localstack.aws.skeleton    : API action 'CreateActivity' for service 'stepfunctions' not yet implemented or pro feature - please check https://docs.localstack.cloud/references/coverage/coverage_stepfunctions/ for further information
```

It seems that `CreateActivity` is not available for version `3.0.0` even tho on the  documentation (https://docs.localstack.cloud/references/coverage/coverage_stepfunctions/), it specifies that `CreateActivity` is available for `community` edition 

Are there plans to fully implement `CreateActivity` for version `3.0.0` and what major difference are there between version `2.0.0` and `3.0.0` for step function? (like aws sdk differences or something else)

Thank you

### Expected Behavior

Localstack step function provider should work in version `3.0.0` as it did in `2.0.0` (unless there are major underlying aws skd changes, in which case, then I will have to upgrade the aws sdk version on my service before using the new version of localstack) 

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    localstack start 

Then our service makes request to localstack to create step function activities using aws sdk version 1 

### Environment

```markdown
- OS: 13.6 (22G120)
- LocalStack: 3.0.0
```

**Comment by MEPalma** [comment]
Thank you for summarizing this matter. In version 3.0, the StepFunctions provider underwent an update featuring a new native implementation. Support for Activities, although planned, is not yet implemented in this new provider. Until support is integrated, Activities can still be accessed through the old provider by setting `PROVIDER_OVERRIDE_STEPFUNCTIONS=legacy`. I will gladly provide an update on this issue once support for Activities on the new provider is introduced.

**Comment by abdulbasit1149** [comment]
Thanks @MEPalma, I will use `PROVIDER_OVERRIDE_STEPFUNCTIONS=legacy` in the meantime

**Comment by abdulbasit1149** [comment]
Also, why does it mention now that on https://docs.localstack.cloud/references/coverage/coverage_stepfunctions/, `CreateActivity` is only available for `pro`, will the `community` edition continue to have support for `CreateActivity` in version `3.0.0` and onwards?
