### ISSUE TITLE
About the 3.0.0 release

### ISSUE THREAD

**Issue by chenrui333** [localstack/localstack#9661]
👋 as the 3.0.0 pypi artifact got yanked, can we cut off a new release as 3.0.1? Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/154533

**Comment by alexrashed** [comment]
Hi @chenrui333!
Sorry for the inconvenience, we had some small issues with the Python package releases.
We currently plan on publishing a proper `3.0.1` bugfix release by the end of next week.

**Comment by chenrui333** [comment]
That sounds great, thanks!!

**Comment by chenrui333** [comment]
Closing for now. Thanks folks!
