### ISSUE TITLE
AWS cdklocal deployement is failing

### ISSUE THREAD

**Issue by Rajesh-Itilite** [localstack/localstack#9669]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

5:54:16 PM | UPDATE_FAILED        | AWS::IAM::Role                   | LamdaDeployementE9CE7A4D
'NoneType' object has no attribute 'get'

	new Role (/var/folders/_8/1ywtn4gj3fn47yy8_mrcvdyw0000gp/T/jsii-kernel-GOgBLe/node_modules/aws-cdk-lib/aws-iam/lib/role.js:1:5794)
	\_ Kernel._Kernel_create (/private/var/folders/_8/1ywtn4gj3fn47yy8_mrcvdyw0000gp/T/tmpa6w5r69v/lib/program.js:10071:25)
	\_ Kernel.create (/private/var/folders/_8/1ywtn4gj3fn47yy8_mrcvdyw0000gp/T/tmpa6w5r69v/lib/program.js:9742:93)
	\_ KernelHost.processRequest (/private/var/folders/_8/1ywtn4gj3fn47yy8_mrcvdyw0000gp/T/tmpa6w5r69v/lib/program.js:11658:36)
	\_ KernelHost.run (/private/var/folders/_8/1ywtn4gj3fn47yy8_mrcvdyw0000gp/T/tmpa6w5r69v/lib/program.js:11618:22)
	\_ Immediate._onImmediate (/private/var/folders/_8/1ywtn4gj3fn47yy8_mrcvdyw0000gp/T/tmpa6w5r69v/lib/program.js:11619:46)
	\_ process.processImmediate (node:internal/timers:478:21)

 ❌  DevFastApiLocalBackendStack failed: Error: The stack named DevFastApiLocalBackendStack failed to deploy: CREATE_FAILED ('NoneType' object has no attribute 'get'): 'NoneType' object has no attribute 'get'
    at FullCloudFormationDeployment.monitorDeployment (/opt/homebrew/lib/node_modules/aws-cdk/lib/api/deploy-stack.ts:512:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Object.deployStack2 [as deployStack] (/opt/homebrew/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:287:24)
    at /opt/homebrew/lib/node_modules/aws-cdk/lib/util/work-graph.ts:105:11

 ❌ Deployment failed: Error: The stack named DevFastApiLocalBackendStack failed to deploy: CREATE_FAILED ('NoneType' object has no attribute 'get'): 'NoneType' object has no attribute 'get'
    at FullCloudFormationDeployment.monitorDeployment (/opt/homebrew/lib/node_modules/aws-cdk/lib/api/deploy-stack.ts:512:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Object.deployStack2 [as deployStack] (/opt/homebrew/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:287:24)
    at /opt/homebrew/lib/node_modules/aws-cdk/lib/util/work-graph.ts:105:11

The stack named DevFastApiLocalBackendStack failed to deploy: CREATE_FAILED ('NoneType' object has no attribute 'get'): 'NoneType' object has no attribute 'get'

### Expected Behavior

it as to deploy

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

cdklocal deploy

### Environment

```markdown
- OS: mac
- LocalStack: latest
```

### Anything else?

No

**Comment by simonrw** [comment]
Hi thanks for raising this issue. To help us reproduce your error, could you share a minimal example of a CDK stack that fails to deploy, as well as the debug logs from the LocalStack container (add `DEBUG=1` to your compose file) please?
