### ISSUE TITLE
bug: SQS FIFO: The maximum length of MessageDeduplicationId must be 128 characters

### ISSUE THREAD

**Issue by mbermas** [localstack/localstack#9678]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Now it is 127 characters:
https://github.com/localstack/localstack/blob/32a7946f878ace1a8bdd098bb3c9d53898424a78/localstack/services/sqs/provider.py#L435-L438

### Expected Behavior

The maximum length of MessageDeduplicationId is 128 characters. AWS docs:
https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_SendMessage.html#API_SendMessage_RequestSyntax

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal s3 mb s3://mybucket

### Environment

```markdown
- OS:
- LocalStack:
```

**Comment by hanshal101** [comment]
Hello @mbermas , I checked the AWS Documentation, and reviewed the code the max MessageDeduplicationId should be 128 Characters. 
Correct me if I'm wrong , here it should be :
```len(fifo_id) <= 128```
