### ISSUE TITLE
SNS: LocalStack returns HTML if nextToken is sent as an empty string with list-topics

### ISSUE THREAD

**Issue by pingvinen** [localstack/localstack#969]
Providing an empty string as `NextToken` for a call to `sns list-topics` makes LocalStack return a 500 internal server error html page.

One thing is not doing this from the commandline, but the AWS SDK for .NET has a method called `FindTopicAsync` which is using `list-topics` with `NextToken=string.Empty` for the first call.

The same thing can be triggered from the commandline:
```
aws sns list-topics --endpoint-url=http://localhost:4575 --region=eu-central-1 --starting-token=
```

I have made a small project that shows the problem. https://github.com/pingvinen/aws-sdk-net-sns-findtopic-issue

**Comment by duongpv7** [comment]
This issue already fixed in latest version.
