### ISSUE TITLE
bug: Bucket name and key are swapped when using S3 via AWS Java SDK v2

### ISSUE THREAD

**Issue by lbenedetto** [localstack/localstack#9693]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```
s3Client.getObject(GetObjectRequest.builder()
  .bucket("my-bucket")
  .key("test.txt")
  .build());
```

> localstackissue8545reproducer-localstack300-1  | 2023-11-20T19:56:28.838 DEBUG --- [   asgi_gw_0] l.aws.serving.wsgi         : GET my-bucket.localhost:4566/test.txt
> localstackissue8545reproducer-localstack300-1  | 2023-11-20T19:56:28.839  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS s3.ListObjects => 404 (NoSuchBucket); 000000000000/eu-west-1; ListObjectsRequest({'Bucket': 'test.txt', 'Delimiter': None, 'EncodingType': None, 'Marker': None, 'MaxKeys': None, 'Prefix': None, 'RequestPayer': None, 'ExpectedBucketOwner': None, 'OptionalObjectAttributes': None}, headers={'Host': 'my-bucket.localhost:4566', 'amz-sdk-invocation-id': '55a41be4-a3e0-457a-f459-9fd77d735bc0', 'amz-sdk-request': 'attempt=1; max=4', 'Authorization': 'AWS4-HMAC-SHA256 Credential=asdf/20231120/eu-west-1/s3/aws4_request, SignedHeaders=amz-sdk-invocation-id;amz-sdk-request;host;x-amz-content-sha256;x-amz-date;x-amz-te, Signature=0126706ebf8bda1265886af8fd39fc48e7e6615a1b24ff4831171211cbcf84c2', 'User-Agent': 'aws-sdk-java/2.21.26 Linux/5.15.0-88-generic OpenJDK_64-Bit_Server_VM/17.0.6+10-LTS Java/17.0.6 vendor/Amazon.com_Inc. io/sync http/Apache cfg/retry-mode/legacy hll/cross-region', 'x-amz-content-sha256': 'UNSIGNED-PAYLOAD', 'X-Amz-Date': '20231120T195628Z', 'x-amz-te': 'append-md5', 'Connection': 'Keep-Alive', 'x-localstack-tgt-api': 's3', 'x-moto-account-id': '000000000000'}); NoSuchBucket(The specified bucket does not exist, headers={'Content-Type': 'application/xml', 'Content-Length': '225', 'x-amz-request-id': '75baae79-591a-4a69-8302-fa77237cf371', 'x-amz-id-2': 's9lzHYrFp76ZVxRcpX9+5cjAnEH2ROuNkd2BHfIa6UkFVdtjf5mKR3/eTPFvsiP/XV/VLi31234='})

Notice how it says: `'Bucket': 'test.txt'`? Seems like it's mixed up the inputs. If I swap them like this, it works:
```
s3Client.getObject(GetObjectRequest.builder()
  .bucket("test.txt")
  .key("my-bucket")
  .build());
```

> localstackissue8545reproducer-localstack300-1  | 2023-11-20T20:00:42.802 DEBUG --- [   asgi_gw_0] l.aws.serving.wsgi         : GET test.txt.localhost:4566/my-bucket
> localstackissue8545reproducer-localstack300-1  | 2023-11-20T20:00:42.803  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS s3.ListObjects => 200; 000000000000/eu-west-1; ListObjectsRequest({'Bucket': 'my-bucket', 'Delimiter': None, 'EncodingType': None, 'Marker': None, 'MaxKeys': None, 'Prefix': None, 'RequestPayer': None, 'ExpectedBucketOwner': None, 'OptionalObjectAttributes': None}, headers={'Host': 'test.txt.localhost:4566', 'amz-sdk-invocation-id': 'b6567140-fab7-c463-6f73-a4de549af15d', 'amz-sdk-request': 'attempt=1; max=4', 'Authorization': 'AWS4-HMAC-SHA256 Credential=asdf/20231120/eu-west-1/s3/aws4_request, SignedHeaders=amz-sdk-invocation-id;amz-sdk-request;host;x-amz-content-sha256;x-amz-date;x-amz-te, Signature=e87c89f2d57687a04ac6de3479c24d74e266465e1f7678684b62cadd3f1dfdee', 'User-Agent': 'aws-sdk-java/2.21.26 Linux/5.15.0-88-generic OpenJDK_64-Bit_Server_VM/17.0.6+10-LTS Java/17.0.6 vendor/Amazon.com_Inc. io/sync http/Apache cfg/retry-mode/legacy hll/cross-region', 'x-amz-content-sha256': 'UNSIGNED-PAYLOAD', 'X-Amz-Date': '20231120T200042Z', 'x-amz-te': 'append-md5', 'Connection': 'Keep-Alive', 'x-localstack-tgt-api': 's3', 'x-moto-account-id': '000000000000'}); ListObjectsOutput({'IsTruncated': False, 'Name': 'my-bucket', 'MaxKeys': 1000, 'Prefix': '', 'Marker': '', 'Contents': [{'Key': 'test.txt', 'ETag': '"d41d8cd98f00b204e9800998ecf8427e"', 'Owner': {'DisplayName': 'webfile', 'ID': '75aa57f09aa0c8caeab4f8c24e99d10f8e7faeebf76c078efc7c6caea54ba06a'}, 'Size': 0, 'LastModified': datetime.datetime(2023, 11, 20, 19, 50, 25, 613030, tzinfo=zoneinfo.ZoneInfo(key='GMT')), 'StorageClass': 'STANDARD'}], 'BucketRegion': 'eu-west-1'}, headers={'Content-Type': 'application/xml', 'x-amz-bucket-region': 'eu-west-1', 'Content-Length': '487', 'x-amz-request-id': 'b217e37b-cd9b-4163-9d04-ca82877103e1', 'x-amz-id-2': 's9lzHYrFp76ZVxRcpX9+5cjAnEH2ROuNkd2BHfIa6UkFVdtjf5mKR3/eTPFvsiP/XV/VLi31234='})

### Expected Behavior

No error

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

I have created an issue reproducer (make sure you clone the right branch):
https://github.com/lbenedetto/LocalstackIssue8545Reproducer/tree/S3-Issue

```
docker compose up
./gradlew test
```

### Environment

```markdown
- LocalStack: 3.0.0
- software.amazon.awssdk:s3: 2.21.26
```

### Anything else?

I discovered this issue while testing SQS with extended payload support via S3. SQS complained it couldn't find the payload in S3 but I could see clearly that it was in the bucket using aws cli commands. The same issue does not happen when deployed to real AWS.

**Comment by lbenedetto** [comment]
Oh, I was looking at this the wrong way. It's not the arguments that are swapped, it's that it's interpreting the request as the wrong request type. It doesn't see the bucket in the subdomain, so it thinks the request is `localhost/bucket` instead of `bucket.localhost/file` so it sees the GetObjectRequest as a ListObjectsRequest. Swapping the args just makes the ListObjectsRequest succeed but doesn't do anything to help the GetObjectRequest do anything useful.

**Comment by bentsku** [comment]
Hello @lbenedetto and thanks for your report.

It seems this issue stems from a misconfiguration of your Java client and a bug in the SDK when specifying `localhost` as the endpoint it seems.

We also have documentation in how to configure your Java client: https://docs.localstack.cloud/user-guide/integrations/sdks/java/

It is not due to LocalStack, as this is the request incoming from your SDK:
`GET localhost:4566/test.txt/my-bucket`
We can clearly see that the key and the bucket are inverted, but this comes from the SDK, which is strange. You can circumvent the issue by specifying the S3 specific endpoint for your S3 client.

In your case, your client should be initialized like that.
I've added the configuration for path style, but it's not mandatory.
See https://docs.localstack.cloud/user-guide/aws/s3/#path-style-and-virtual-hosted-style-requests

```java
@BeforeAll
public static void init() {
    // the S3Configuration part is optional, you don't need it but it might be easier to have it.
    S3Configuration config = S3Configuration.builder()
            .pathStyleAccessEnabled(true)
            .build();

    s3Client = S3Client.builder()
            .endpointOverride(URI.create("https://s3.localhost.localstack.cloud:4566"))
            .serviceConfiguration(config)
            .region(Region.EU_WEST_1)
            .build();
}
```
The result is this:
`GET s3.localhost.localstack.cloud:4566/my-bucket/test.txt`
```
 AWS s3.GetObject => 404 (NoSuchKey); 000000000000/eu-west-1; GetObjectRequest({'Bucket': 'my-bucket', 'IfMatch': None, 'IfModifiedSince': None, 'IfNoneMatch': None, 'IfUnmodifiedSince': None, 'Key': 'test.txt', 'Range': None, 'ResponseCacheControl': None, 'ResponseContentDisposition': None, 'ResponseContentEncoding': None, 'ResponseContentLanguage': None, 'ResponseContentType': None, 'ResponseExpires': None, 'VersionId': None, 'SSECustomerAlgorithm': None, 'SSECustomerKey': None, 'SSECustomerKeyMD5': None, 'RequestPayer': None, 'PartNumber': None, 'ExpectedBucketOwner': None, 'ChecksumMode': None}
```

The request is now properly constructed and parsed. I'm not sure why the SDK is doing something so weird, but the issue doesn't come from LocalStack.

**Comment by bentsku** [comment]
I've just seen your second comment, and that's also where my comment about path style requests came from. LocalStack is not able to parse the request when it comes with the bucket in front of localhost. 

With the configuration shared, you should be able to make it work, even with `.endpointOverride(URI.create("http://localhost:4566"))` as long as you specify the path style configuration.

**Comment by lbenedetto** [comment]
Thanks. Changing the URI or enabling path style access both work to fix this issue.

**Comment by bentsku** [comment]
Awesome, thanks!
