### ISSUE TITLE
enhancement request: Support selecting/installing postgres extensions

### ISSUE THREAD

**Issue by JordanWeir** [localstack/localstack#9694]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Enhancement description

RDS Postgres 15 supports the pgvector extension by default, but it doesn't come setup in localstack.

It's also not clear in the localstack documentation the right way to install the plugin.

Through trial and error, I've found that if I use a script that runs on ready, continuously poll for the presence of postgres 15, and then install the pgvector plugin **after** the postgres 15 gets installed by RDS, then I can use pgvector inside my localstack rds postgres instance.  This seems pretty hacky though, and required a lot of trial and error to understand exactly how localstack manages DBs, what the lifecycle looks like inside the localstack container, etc.

### 🧑‍💻 Implementation

Maintain a list of plugins that are installed in the postgres container on AWS, and either 1) Install all of them to have feature parity, or 2) receive an ENV var with a list of plugins to install, and install everything on the list that is also on the AWS list.

**Comment by circulon** [comment]
This should be reopened as this is still an issue

I am using Pro.

Trying to use pg_cron and pg_partman for partitioned tables is just not possible as these extensions are not included with localstacks Postgres 16 implementation.

This requires code workarounds disabling cron and partition management for the localstack environment only.
