### ISSUE TITLE
Does localstack expose ECR?

### ISSUE THREAD

**Issue by adamdavis40208** [localstack/localstack#970]
I noticed Moto supports ECR, but localstack doesn't seem to call it out anywhere. 

If it needs to be added, would that be a welcome PR?

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-318) by [Unito](https://www.unito.io/learn-more)

**Comment by NickCoad-NewsPerform** [comment]
I was just looking for this information, and I agree, it should be called out in the readme or something. I'm evaluating whether we can use this or not since we need ECR and it looks like the pro version supports it perhaps? But it isn't advertised anywhere. You nearly lost a sale!

**Comment by thrau** [comment]
We have support for ECR in pro (see our [feature coverage](https://github.com/localstack/localstack/blob/master/doc/feature_coverage.md)) please let us know if you have specific feature requests.
