### ISSUE TITLE
bug: lambda with self-managed kafka cluster fails with "Unrecognized event source."

### ISSUE THREAD

**Issue by deadcore** [localstack/localstack#9700]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When following the steps mentioned under Localstacks documentation here [doc/external_services_integration/kafka_self_managed_cluster
/HOWTO.md](https://github.com/localstack/localstack/blob/master/doc/external_services_integration/kafka_self_managed_cluster/HOWTO.md), specifically when specifically executing this line of code:
```bash
awslocal lambda create-event-source-mapping \
    --topics t1 \
    --source-access-configuration Type=SASL_SCRAM_512_AUTH,URI=arn:aws:secretsmanager:us-east-1:000000000000:secret:localstack-TDIuI \
    --function-name arn:aws:lambda:us-east-1:000000000000:function:fun1 \
    --self-managed-event-source '{"Endpoints":{"KAFKA_BOOTSTRAP_SERVERS":["localhost:9092"]}}'
```
The even source mapping fails with the following error:
```
An error occurred (InvalidParameterValueException) when calling the CreateEventSourceMapping operation: Unrecognized event source.
```

### Expected Behavior

The event source mapping successfully creates

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)
Steps unidentified [here](https://github.com/localstack/localstack/blob/master/doc/external_services_integration/kafka_self_managed_cluster/HOWTO.md) within Localstacks documentation

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)
```
awslocal lambda create-event-source-mapping \
    --topics t1 \
    --source-access-configuration Type=SASL_SCRAM_512_AUTH,URI=arn:aws:secretsmanager:us-east-1:000000000000:secret:localstack-TDIuI \
    --function-name arn:aws:lambda:us-east-1:000000000000:function:fun1 \
    --self-managed-event-source '{"Endpoints":{"KAFKA_BOOTSTRAP_SERVERS":["localhost:9092"]}}'
```

### Environment

```markdown
- OS: OSX
- LocalStack: latest
```

### Anything else?

Looking into the code, it seems to be validating the presence of an `EventSourceArn` which according to the documentation strays for the expected, as an `EventSourceArn` for a locally managed Kafka cluster will never be present. 

https://github.com/localstack/localstack/blob/f7890b2b1d1681368a3fde0c029a31e4691530f5/localstack/services/lambda_/provider.py#L1594

The even source mapping can be forced to attach if we provide **any** ARN:
```
--event-source-arn="arn:aws:lambda:us-west-2:000000000000:ignore:ignore"
```

However if we attempt this in Terraform we are greeted with another blocker:
```
│ Error: Conflicting configuration arguments
│
│   with module.module.aws_lambda_event_source_mapping.name,
│   on module/lambda_name.tf line 189, in resource "aws_lambda_event_source_mapping" "name":
│  189: resource "aws_lambda_event_source_mapping" "name" {
│
│ "self_managed_kafka_event_source_config": conflicts with event_source_arn
```

**Comment by deadcore** [comment]
Related to:
- https://github.com/localstack/localstack/issues/8898
- https://github.com/localstack/localstack/issues/8328

The work arounds present in the tickets however would not work when deploying via terraform

**Comment by aschade92** [comment]
The issue is this line [https://github.com/localstack/localstack/blob/0217fedbf8ca7c4b8fc2516fc2a5a2a750ddd538/localstack/services/lambda_/provider.py#L1658](here)

`EventSourceArn` is not in reality a required field if you're creating a trigger from a self managed kafka image.

**Comment by joe4dev** [comment]
@deadcore Our new Lambda Event Source Mapping implementation comes with improved support for self-hosted Kafka: https://blog.localstack.cloud/localstack-release-v-3-8-0/#new-default-lambda-event-source-mapping-implementation
