### ISSUE TITLE
bug: `CallerReference` field not returned consistently across endpoints

### ISSUE THREAD

**Issue by frank-lenormand** [localstack/localstack#9707]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The [`list_hosted_zones`](https://botocore.amazonaws.com/v1/documentation/api/latest/reference/services/route53/client/list_hosted_zones.html) and [`list_hosted_zones_by_name`](https://botocore.amazonaws.com/v1/documentation/api/latest/reference/services/route53/client/list_hosted_zones_by_name.html) should return a `CallerReference` field in each entry of the `HostedZones` array, but LocalStack doesn’t implement that part of the spec.

### Expected Behavior

A `CallerReference` field should be present and set correctly in each entry of the `HostedZones` array.

Note that this has already been implemented in a [Pull Request](https://github.com/localstack/moto/pull/71) that was subsequently merged, but only for the [`get_hosted_zone`](https://botocore.amazonaws.com/v1/documentation/api/latest/reference/services/route53/client/get_hosted_zone.html#Route53.Client.get_hosted_zone) endpoint.

There may be other endpoints that should be returning a `CallerReference`, but don’t.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker compose run -d

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```console
$ aws --endpoint-url=http://localstack:4566 route53 create-hosted-zone --name test.me --caller-reference test-me-uniq
{
    "Location": "https://route53.amazonaws.com/2013-04-01/hostedzone/GUX52NHLAXBAGHD",
    "HostedZone": {
        "Id": "/hostedzone/GUX52NHLAXBAGHD",
        "Name": "test.me.",
        "Config": {
            "PrivateZone": false
        },
        "ResourceRecordSetCount": 2
    },
    "ChangeInfo": {
        "Id": "/change/C1PA6795UKMFR9",
        "Status": "INSYNC",
        "SubmittedAt": "2017-03-15T01:36:41.958000Z"
    },
    "DelegationSet": {
        "Id": "",
        "NameServers": [
            "ns-2048.awsdns-64.com",
            "ns-2049.awsdns-65.net",
            "ns-2050.awsdns-66.org",
            "ns-2051.awsdns-67.co.uk"
        ]
    }
}
```

```console
$ aws --endpoint-url=http://localstack:4566 route53 list-hosted-zones
{
    "HostedZones": [
        {
            "Id": "/hostedzone/GUX52NHLAXBAGHD",
            "Name": "test.me.",
            "Config": {
                "PrivateZone": false
            },
            "ResourceRecordSetCount": 2
        }
    ]
}
```

```console
$ aws --endpoint-url=http://localstack:4566 route53 list-hosted-zones-by-name 
{
    "HostedZones": [
        {
            "Id": "/hostedzone/GUX52NHLAXBAGHD",
            "Name": "test.me.",
            "Config": {
                "PrivateZone": false
            },
            "ResourceRecordSetCount": 2
        }
    ],
    "IsTruncated": false
}
```

### Environment

```markdown
- OS: Ubuntu v20 Focal
- LocalStack: v3.0.0
```

### Anything else?

This is a follow-up to #8921.

**Comment by giograno** [comment]
Hi @frank-lenormand, we addressed the issue in [moto](https://github.com/getmoto/moto/pull/7097). It will be soon available it LocalStack as well. We will keep you posted. Thanks for reporting.

**Comment by giograno** [comment]
The fix is now available in the `latest` image.
