### ISSUE TITLE
enhancement request: add support for lambda runtime nodejs20.x

### ISSUE THREAD

**Issue by mh1622** [localstack/localstack#9708]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Enhancement description

As of 15th Nov 2023, Node.js 20.x runtime is now available in AWS Lambda: https://aws.amazon.com/blogs/compute/node-js-20-x-runtime-now-available-in-aws-lambda/

Please add nodejs20.x to the current set of supported runtimes: [java17, provided, nodejs16.x, nodejs14.x, ruby2.7, python3.10, java11, python3.11, dotnet6, go1.x, nodejs18.x, provided.al2, java8, java8.al2, ruby3.2, python3.7, python3.8, python3.9]

**Comment by mh1622** [comment]
It looks like there's a PR for this already: https://github.com/localstack/localstack/pull/9659

**Comment by dfangl** [comment]
All new runtimes will be added with #9697 , which should be merged this week.
