### ISSUE TITLE
Elasticsearch persistent storage

### ISSUE THREAD

**Issue by bastuijnman** [localstack/localstack#971]
I have a quick question, I'm using localstack in our local testing environment and I want to have Elasticsearch persist it's data across sessions.

I've noticed that running `docker-compose down` and `docker-compose up` in our environment causes the ES service deletes it's data every time on startup

https://github.com/localstack/localstack/blob/master/localstack/services/es/es_starter.py#L39

Services like S3 do seem to persist, is there a way around this for ES or was this done by design? In the latter case would you guys accept PR's to allow for persistance of ES data?

Kind regards,

Bas Tuijnman
24i

**Comment by lucasbraum** [comment]
Could you find a solution for this? I am facing the same problem

**Comment by Ghazgkull** [comment]
@whummer Could you possibly share any insight into this issue? It does appear that ElasticSearch is hard-coded to delete all start on startup at https://github.com/localstack/localstack/blob/master/localstack/services/es/es_starter.py#L25

Is there any history behind this? Some reason the persisted data can't be used on restart?

**Comment by devingd** [comment]
Also interested if this has been addressed or is in the works? Am willing to help with a solution, if needed.

**Comment by devingd** [comment]
#1760 appears to have resolved this. I just pulled the `latest` docker image and using `DATA_DIR` my data persists across restarts.

**Comment by whummer** [comment]
Thanks for confirming that this works in the latest version @devingd . Closing - please reopen if the problem persists @Ghazgkull @lucasbraum @bastuijnman . Thanks
