### ISSUE TITLE
bug: EventBridge `anything-but` event pattern does not match null field

### ISSUE THREAD

**Issue by aaronrenner** [localstack/localstack#9711]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When using the following `anything-but` event pattern on localstack, I'm getting some inconsistencies with the actual eventbridge behavior.

**Event Rule**
```json
{
  "detail": {
    "foo": [{
      "anything-but": ["baz"]
    }]
  }
}
```
**Event that matches on AWS and LocalStack**
```json
{
  "id": "42c61f75-5cf5-4aa8-b430-6fd3d0d8a404",
  "account": "000000000000",
  "source": "myapp",
  "time": "2023-11-22T20:27:11Z",
  "region": "us-east-1",
  "resources": [],
  "detail-type": "MyEvent",
  "detail": { "foo": "a" }
}
```
**Event that matches in AWS, but NOT Localstack**
```json
{
  "id": "42c61f75-5cf5-4aa8-b430-6fd3d0d8a404",
  "account": "000000000000",
  "source": "myapp",
  "time": "2023-11-22T20:27:11Z",
  "region": "us-east-1",
  "resources": [],
  "detail-type": "MyEvent",
  "detail": { "foo": null }
}
```

### Expected Behavior

Both event examples should match in Localstack like they do in AWS.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

Docker-compose.yml

```yaml
version: "3.9"

services:
  localstack:
    image: "localstack/localstack"
    ports:
      - "4566:4566"
```
   
#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

Setup commands

    awslocal events create-event-bus \
        --name detail-bus-1
    
    awslocal sqs create-queue \
        --queue-name "detail-sqs-1"
    
    awslocal events put-rule \
        --name "detail-rule-1" \
        --event-bus-name "detail-bus-1" \
        --event-pattern '{ "detail": { "foo": [ {"anything-but": ["baz"]} ] } }'
    
    awslocal events put-targets \
        --rule "detail-rule-1" \
        --event-bus-name "detail-bus-1" \
        --targets "Id"="detail-target-rule-1","Arn"="arn:aws:sqs:us-east-1:000000000000:detail-sqs-1"

Send event that matches

    awslocal events put-events --entries '[{"DetailType": "test", "Source": "aws.test", "Detail": "{ \"foo\": \"a\" }", "EventBusName": "detail-bus-1"}]'
    awslocal sqs receive-message --queue-url http://localhost:4566/000000000000/detail-sqs-1

Send event that SHOULD match, but doesn't

    awslocal events put-events --entries '[{"DetailType": "test", "Source": "aws.test", "Detail": "{ \"foo\": null }", "EventBusName": "detail-bus-1"}]'
    awslocal sqs receive-message --queue-url http://localhost:4566/000000000000/detail-sqs-1

### Environment

```markdown
- OS: Mac OS 13.6.1
- LocalStack: 3.0.1-dev
```

**Comment by maxhoheiser** [comment]
I wanted to bring your attention to PR #9925, where we've successfully fixed the above-described issues. 

To test the new functionality, please ensure you're running the latest Docker container.
