### ISSUE TITLE
delete-bucket-intelligent-tiering-configuration   Accessdenied

### ISSUE THREAD

**Issue by krishgopi007** [localstack/localstack#9718]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

delete-bucket-intelligent-tiering-configuration is working in single account scenario.
But in crossaccount scenario, after executing assume role command, its observed that delete-bucket-intelligent-tiering-configuration  is giving accessdenied.

Localstack needs DeleteBucketIntelligentTieringConfiguration permission to remove IntelligentTieringConfiguration from the bucket but actual AWS don't need. Actual AWS needs only permission for PutIntelligentTieringConfiguration. Is there any reason for this discrepancy?

### Expected Behavior

delete-bucket-intelligent-tiering-configuration   should happen without error

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

There are two account 000000000001 and 000000000002 

In 000000000002 : 
 1. Create bucket
  2. create a role with  assume role policy (000000000001:root)  and bucket policy for  put intelligent tiering permission 
  
In 000000000001: 
Execute assume role command 

Again In 000000000002 : 
awslocal s3api put-bucket-intelligent-tiering-configuration --bucket rainyday1 --id "ExampleConfig" --intelligent-tiering-configuration file://intelligent-tiering-configuration.json
awslocal s3api delete-bucket-intelligent-tiering-configuration --bucket rainyday1 --id ExampleConfig
 

### Environment

```markdown
- OS: windows
- LocalStack: latest
```

**Comment by krishgopi007** [comment]
@localstack-bot 
Hi  @bentsku  ,
Could you please help to resolve this issue.

Regards,
Krishna G

**Comment by krishgopi007** [comment]
Hi @dfangl,
Are you able to reproduce this issue

**Comment by dfangl** [comment]
Yes, there is a fix in the pipeline already, which will be released once it is ready.
Thank you for reporting this issue!

**Comment by krishgopi007** [comment]
Hi @dfangl 
Thanks for the update. Please let me know once the localstack with fix is released.
