### ISSUE TITLE
bug: api error InternalError: exception while calling ec2.DescribeNetworkInterfaces aws-sdk-go-v2

### ISSUE THREAD

**Issue by renanqts** [localstack/localstack#9720]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm facing 

```
 operation error EC2: DescribeNetworkInterfaces, exceeded maximum number of attempts, 3, https response error StatusCode: 500, RequestID: aeb414dd-020f-48f3-9dff-d2d569986a29, api error InternalError: exception while calling ec2.DescribeNetworkInterfaces: ''"
```
I saw some similar issues but in another APIs

### Expected Behavior

it just should work.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    kubernetes deployment with the image localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    try to use ec2.DescribeNetworkInterfaces in  aws-sdk-go-v2 
github.com/aws/aws-sdk-go-v2 v1.23.1
github.com/aws/aws-sdk-go-v2/config v1.25.5
github.com/aws/aws-sdk-go-v2/service/ec2 v1.137.1

### Environment

```markdown
- OS: Linux
- LocalStack: 3.0 and 2.3
```

**Comment by renanqts** [comment]
I found the issue, it was client configuration. It should work using something like that

```golang
	cfg, err := config.LoadDefaultConfig(ctx, config.WithRegion(region),
		config.WithEndpointResolverWithOptions(aws.EndpointResolverWithOptionsFunc(
			func(service, region string, options ...interface{}) (aws.Endpoint, error) {
				return aws.Endpoint{URL: "http://localstack:4566"}, nil
			}),
		),
	)
```

**Comment by arunsriniv** [comment]
I am facing a very similar issue (actually same InternalError) with ec2.DescribeVpcs using GoLang SDK v2. Tried the above client configuration. But it does not seem to help. I could get the LocalStack responding to Python SDK though.

Any pointers?
