### ISSUE TITLE
bug: startup freeze when running localstack in Docker mode on MacOS

### ISSUE THREAD

**Issue by maslokeeper01** [localstack/localstack#9727]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When running `localstack start -d`, program freezes on "configuring container" phase and won't pass through that phase.

<img width="1050" alt="image" src="https://github.com/localstack/localstack/assets/61380431/0c9b8646-269c-4bda-a0bd-6d6dc54ff54d">

### Expected Behavior

System should start without freezing.

### How are you starting LocalStack?

With the `localstack` script

### Steps To Reproduce

Run localstack in Docker mode with command `localstack start -d` on the MacOS platform.

### Environment

```markdown
- OS: MacOS Monterey v12.6.8
- LocalStack: latest
```

**Comment by simonrw** [comment]
Hi @maslokeeper01, thanks for reaching out to us. Could you try running LocalStack setting the environment variable `DEBUG=1` and paste the output please? This will help us understand what the problem is.
