### ISSUE TITLE
Suggestion: Support AWS Elastic Transcoder

### ISSUE THREAD

**Issue by pedrofurtado** [localstack/localstack#973]
:+1:  :heart:

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-319) by [Unito](https://www.unito.io/learn-more)

**Comment by qasimzee** [comment]
Any updates on this?

**Comment by whummer** [comment]
@pedrofurtado @qasimzee No plans to support AWS Elastic Transcoder as of now, but would be very happy to accept a pull request! I'm sure we could find some open source transcoding tools to get this working, and then the basic API plumbing could be built around it. Anyone willing to take a first stab at it?

Also, can you please share some small sample projects that illustrate how you're currently using this API? Thanks

**Comment by qasimzee** [comment]
O yeah, I use it for video transcoding from Mp4 to dash. I can also take a stab at creating a PR

**Comment by HarshCasper** [comment]
Hi,

The Elastic Transcoder service is now available in `localstack/localstack-pro:latest` image. Please pull the image to get started. Here are the docs: https://docs.localstack.cloud/user-guide/aws/elastictranscoder/
