### ISSUE TITLE
bug: Unable to provision FIFO SNS Topic via CDK

### ISSUE THREAD

**Issue by tbellerose-godaddy** [localstack/localstack#9741]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When attempting to provision a FIFO SNS topic in LocalStack via CDK using `cdklocal`, e.g.:

```typescript
const topic = new sns.Topic(this, 'FIFOTopic', {
  displayName: 'topic.fifo',
  fifo: true,
  contentBasedDeduplication: true,
});
```

The resulting topic created in LocalStack is not FIFO:

![Screenshot 2023-11-27 at 12 26 44 PM](https://github.com/localstack/localstack/assets/77160631/fe0079be-1197-4a8b-8405-8014f3d633f1)

This doesn't appear to be an issue with `cdklocal`, because the template output does appear to have the correct properties:

```json
{
 "Resources": {
  "FIFOTopic5C947601": {
   "Type": "AWS::SNS::Topic",
   "Properties": {
    "ContentBasedDeduplication": true,
    "DisplayName": "topic.fifo",
    "FifoTopic": true,
    "TopicName": "SNSStack-FIFOTopic-99AA2860.fifo"
   },
   ...
   
 }
```

### Expected Behavior

A FIFO SNS Topic would be provisioned when setting `fifo: true` on the CDK construct.

### How are you starting LocalStack?

With the `localstack` script

### Steps To Reproduce

I created this git repository to provide an example duplicating the issue: https://github.com/tbellerose-godaddy/ls-fifo-sns-cdk-bug

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    localstack start -d

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    
    cdklocal bootstrap
    cdklocal deploy '*'

### Environment

```markdown
- OS: macOS Ventura 13.5.2
- LocalStack: 2.3.2
```

### Anything else?

Creating a FIFO SNS Topic via the `awslocal-cli` works as expected. This is only an issue when creating via CDK.

**Comment by tbellerose-godaddy** [comment]
@bentsku,

I noticed that this was closed, and that the change was listed as part of the v3.0.2 release. I upgraded to v3.0.2 and tested again, but it looks like the issue persists. When creating a FIFO SNS topic via CDK, a non-FIFO topic is created.

**Comment by bentsku** [comment]
Hi @tbellerose-godaddy, I'll give it a try, we normally have a test covering this, but I'll try to reproduce!

**Comment by tbellerose-godaddy** [comment]
Thanks, if it makes it easier, I have an example repo here: https://github.com/tbellerose-godaddy/ls-fifo-sns-cdk-bug

**Comment by bentsku** [comment]
Just gave it a try and it works for me. Are you sure the started image is `3.0.2` and not an old `latest` version? Could you try either starting LocalStack with `IMAGE_NAME=localstack/localstack:3.0.2 localstack start -d` or before starting LocalStack, pull `docker pull localstack/localstack:latest`, and try it again? 

My FIFO topic created with CDK:
```bash
$ awslocal sns get-topic-attributes --topic-arn arn:aws:sns:us-east-1:000000000000:test-topic.fifo
{
    "Attributes": {
        "Owner": "000000000000",
        "Policy": "...",
        "TopicArn": "arn:aws:sns:us-east-1:000000000000:test-topic.fifo",
        "DisplayName": "test-topic.fifo",
        "SubscriptionsPending": "0",
        "SubscriptionsConfirmed": "0",
        "SubscriptionsDeleted": "0",
        "DeliveryPolicy": "",
        "EffectiveDeliveryPolicy": "...",
        "FifoTopic": "true",
        "ContentBasedDeduplication": "false"
    }
```

**Comment by tbellerose-godaddy** [comment]
Yep, that was it. I upgraded the CLI but not the docker image. Working as expected after pulling the latest docker image. Thanks for the super quick turn around and response!
