### ISSUE TITLE
bug: SFN - `States.StringSplit` errors when the same value in AWS succeeds

### ISSUE THREAD

**Issue by BrianMcBrayer** [localstack/localstack#9742]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When using the `States.StringSplit` intrinsic function for AWS Step Functions, I get the following error:

```
│ Error: creating Step Functions State Machine (repro): InvalidDefinition: Error=ValueError Args=["Expected 2 arguments for function type '<class 'localstack.services.stepfunctions.asl.component.intrinsic.function.statesfunction.string_operations.string_split.StringSplit'>', but got: '(FunctionArgumentList| {'arg_list': [], 'size': 0}'."] in definition '{
│   "Comment": "States.StringSplit error",
│   "StartAt": "WillStatesStringSplitError",
│   "States": {
│     "WillStatesStringSplitError": {
│       "Type": "Task",
│       "Resource": "arn:aws:states:::lambda:invoke",
│       "End": true,
│       "Parameters": {
│         "FunctionName": "SomeFunction",
│         "Payload": {
│           "inputArray.$": "States.StringSplit($$.Execution.Input.csv, ',')"
│         }
│       }
│     }
│   }
│ }
│ '.
│ 
│   with module.step_function.aws_sfn_state_machine.this[0],
│   on .terraform/modules/step_function/main.tf line 15, in resource "aws_sfn_state_machine" "this":
│   15: resource "aws_sfn_state_machine" "this" {
```

See repro for state machine definition that produces this error. The same repro works in AWS.

### Expected Behavior

I expect the step function to behave as intended and to split the CSV into an array.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

I'm using docker-compose with the following step function definition:

```json
{
  "Comment": "States.StringSplit error",
  "StartAt": "WillStatesStringSplitError",
  "States": {
    "WillStatesStringSplitError": {
      "Type": "Task",
      "Resource": "arn:aws:states:::lambda:invoke",
      "End": true,
      "Parameters": {
        "FunctionName": "SomeFunction",
        "Payload": {
          "inputArray.$": "States.StringSplit($$.Execution.Input.csv, ',')"
        }
      }
    }
  }
}
```

### Environment

```markdown
- OS: MacOS Ventura
- LocalStack: latest
```

### Anything else?

Thank you for all your hard work!

**Comment by MEPalma** [comment]
Hello, thank you for compiling the report. I can confirm that the issue arose from accessing the ContextObject in Intrinsic Function arguments. We recently merged some changes, and upon replicating your sample, I can confirm that this issue has been resolved in the latest nightly build. The linked PR addresses the parity issue with the split logic, and I anticipate that this concern will be resolved as well. Please note that the issue you're currently experiencing should already be resolved in the latest nightly release.

**Comment by BrianMcBrayer** [comment]
@MEPalma thank you so much!
