### ISSUE TITLE
starting local stack using pip install in detach mode 

### ISSUE THREAD

**Issue by atanupanda** [localstack/localstack#976]
Hi Team,

We have started the localstack like below, and it it is showing ready state and it's just waiting like that. which is Ok.

But How we can run the service as detach mode.
<pre>
#!/bin/bash

export HTTPS_PROXY="xyz"
export HTTP_PROXY="abc"

pip install --user localstack
pip install --user --upgrade pip 
cd /var/home/ci/.local/bin
python localstack start
</pre>

I have also checked the below issue
[(https://github.com/localstack/localstack/issues/430)  ]

Please suggest.

**Comment by atanupanda** [comment]
Because i want to do some task  once localstack is in ready state

**Comment by whummer** [comment]
@atanupanda Please check out this section of the README which describes how to run startup scripts after LocalStack has booted up: https://github.com/localstack/localstack#initializing-a-fresh-instance . Thanks
