### ISSUE TITLE
bug: ACM: Subject Alternative Names Not Added To Certificates

### ISSUE THREAD

**Issue by ScottFinlaysonGMSL** [localstack/localstack#9768]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When creating a certificate which requires multiple domains, the additional domains are not included as part of the certificate. The following command creates a certificate which contains only the domain name passed in but none of the subject alternative names.

```
aws --endpoint http://localhost:4566 --region eu-central-1 acm request-certificate --domain-name test.example.com --subject-alternative-names test.example.com another.domain.com
```
The above command results in the following response:
```
{
    "CertificateSummaryList": [
        {
            "CertificateArn": "arn:aws:acm:eu-central-1:000000000000:certificate/fd59a6b7-1a8f-4bbc-9f23-fae3f22f6fb0",
            "DomainName": "test.example.com",
            "SubjectAlternativeNameSummaries": [
                "test.example.com"
            ],
            "HasAdditionalSubjectAlternativeNames": false,
            "Status": "PENDING_VALIDATION",
            "Type": "AMAZON_ISSUED",
            "KeyAlgorithm": "RSA-2048",
            "KeyUsages": [],
            "ExtendedKeyUsages": [],
            "InUse": false,
            "RenewalEligibility": "INELIGIBLE",
            "CreatedAt": "2023-11-29T14:02:37.340101+00:00"
        }
    ]
}
```

### Expected Behavior

The certificate created would have the subject alternative names added to it. This aligns with the behaviour within AWS as well.

### How are you starting LocalStack?

With a `docker run` command

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

docker run -d --rm \
	--publish 4566:4566 \
	--publish 4510-4559:4510-4559 \
	localstack/localstack:3.0.1

##### Create the certificate
aws --endpoint http://localhost:4566 --region eu-central-1 acm request-certificate --domain-name test.example.com --subject-alternative-names test.example.com *.domain.com

##### Print details of certificates
aws --endpoint http://localhost:4566 --region eu-central-1 acm list-certificates

### Environment

```markdown
- OS: Ubuntu 22.04 (WSL)
- LocalStack:3.0.1
- AWS CLI: 2.13.15
```

### Anything else?

Initially, I was looking at adding a wildcard domain which wasn't working. Hopefully there's nothing extra beyond fixing this for wildcard domains but mentioning in case there is.

I was testing this via `terraform test` initially before resorting to the aws cli so modifying the request (if required) to get this to work is not an option.

**Comment by maxhoheiser** [comment]
I wanted to bring your attention to PR #9897 , where we've successfully fixed the above-described issues. 

To test the new functionality, please ensure you're running the latest Docker container.

**Comment by ScottFinlaysonGMSL** [comment]
Confirmed as working on latest version, thanks!
