### ISSUE TITLE
OneOf property is failing during OAS Schema Validation

### ISSUE THREAD

**Issue by RPS044** [localstack/localstack#9777]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello Team,

Requesting you to please check this issue and help. Performing schema validation with oneOf, discriminator and mapping property in oas3.0.

Error:

{
"fault": {
"faultstring": "OASValidation MAM-EXT-SpecValidation with resource "oas://openapi.yaml": failed with reason: "[ERROR - An error occurred during schema validation - com.google.common.util.concurrent.UncheckedExecutionException: java.lang.NullPointerException.: []]"",
"detail": {
"errorcode": "steps.oasvalidation.Failed"
}
}
}
yaml file looks like:

image

image

Json payload looks like:

--data '{ "billableHeader": { "sourceSystem": "UPSTREAM_APP", "sourceTransactionType": "INVOICE", "eventType": "BATCH", "messageCreationDatetime": "20220811140203", "timeZoneCode": "GMT", "isBulkProcessing": true, "product": "Airlcl" },

### Expected Behavior

Hit Airlcl schema only and validate

### How are you starting LocalStack?

Custom (please describe below)

### Steps To Reproduce

N/A

### Environment

```markdown
- OS:
- LocalStack:
```

**Comment by alexrashed** [comment]
Hi @RPS044!
Could you please extend your issue description a bit with some more information?
- What service are you even referring to?
- What schema are you referring to? What's Airlcl?
- How exactly can we reproduce your issue such that we can look into the issue?
- What version of LocalStack are you using?

Thanks!
