### ISSUE TITLE
Tag latest docker image with a version number

### ISSUE THREAD

**Issue by Nighthawk14** [localstack/localstack#978]
Hello,

It would be quite useful to tag the latest docker image when you guys publish a new version of it. Instead of just having `latest` as a tag, so we can effectively target the latest version without fear that it could be updated.

For example here we should have a tag that is equivalent to latest but with a fixed number:
![screen shot 2018-10-23 at 16 31 07](https://user-images.githubusercontent.com/2417908/47372302-65e08a00-d6e1-11e8-9333-313a799bd93c.png)

Thanks!

**Comment by whummer** [comment]
Thanks for reporting @Nighthawk14 . What you're posting seems to have been an accidental push of the `latest` image that was not tagged with a version.

In general, we push a new tagged image whenever a new version of the pip package is released, and `latest` should always point to the latest release version.

<img width="395" alt="image" src="https://user-images.githubusercontent.com/2807888/50724165-088c9000-10b7-11e9-86ca-38014a41dc44.png">

Closing this issue as resolved.
