### ISSUE TITLE
bug: Localstack S3 ignoring CORS configuration for environment variables and for bucket CORS policy

### ISSUE THREAD

**Issue by diegosasw** [localstack/localstack#9780]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Other similar issues suggest that the default S3 provider (v3) has CORS configuration in place, but CORS in S3 is not working as described by the documentation.

The browser is blocking CORS despite having configured localstack to allow the specific origins (or all) and the specific http verbs (or all). The preflight OPTIONS is getting blocked.
It does not matter if I set an environment variable `DISABLE_CORS_CHECKS=1` or if I configure the CORS policy in the bucket itself. It is ignored. I am using pre-signed URLs for S3.

### Expected Behavior

The expectation is that setting `DISABLE_CORS_CHECKS=1` should be sufficient for the browser not to block any request to the localstack url. Also, the expectation is for the S3 bucket CORS configuration to apply.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)
I am using docker-compose with the latest localstack as per today.

```
version: '3.8'
services:
  # other services
  # ...
  aws:
    image: localstack/localstack
    container_name: aws
    ports:
      - 127.0.0.1:4566:4566
      - 127.0.0.1:4510-4559:4510-4559
    environment:
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DISABLE_CORS_CHECKS=1 # Removing this line does not make any difference
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)
After spinning up localstack container, I use the CLI to successfully create a bucket
```
aws s3api create-bucket --bucket foo --region us-east-1 --endpoint-url=http://localhost:4566 --profile localstack
```
And then I configure the CORS policy
```
aws s3api put-bucket-cors --bucket foo  --cors-configuration file://cors-config.json/ --endpoint-url=http://localhost:4566 --profile localstack
```
where the `cors-config.json` is
```
{
  "CORSRules": [
    {
      "AllowedHeaders": ["*"],
      "AllowedMethods": ["GET", "POST", "PUT", "DELETE"],
      "AllowedOrigins": ["https://localhost:3000"],
      "ExposeHeaders": ["ETag"]
    }
  ]
}
```
NOTE: I have also tried with  `"AllowedOrigins": ["*"]`, with URLS with and without trailing slash, and without ` "ExposeHeaders"`, but no difference.

A **PUT** request to a pre-signed URL for localstack s3 will be blocked by the browser during preflight (i.e: OPTIONS)
Example of blocked url
```
https://foo.localstack:4566/client/46085b4970d243bcb889520b895ba99a?X-Amz-Expires=60&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=dummy%2F20231130%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20231130T123527Z&X-Amz-SignedHeaders=host&X-Amz-Signature=ee77fd4a2ef8a79dc0a6d5ebaf8fa16b62ef0161864e84006caeb8949d8f325a
```

The headers in the OPTIONS preflight show
```
Access-Control-Request-Headers: x-crsf
Access-Control-Request-Method: PUT
Origin: https://localhost:3000
Referer: https://localhost:3000/
Sec-Fetch-Mode: cors
Sec-Fetch-Site: cross-site
```
so it looks Ok to me from a client's perspective

### Environment

```markdown
- OS: Windows 11 (Docker Desktop)
- LocalStack: latest
```

### Anything else?
Checking through AWS CLI the cors configuration of the bucket shows the expected one

**Comment by diegosasw** [comment]
Localstack UI does not show the updated config from AWS CLI and it messes up with the internal one which includes the localstack cloud url

In any case, if I manage to have the following
```
$ aws s3api get-bucket-cors --bucket rubiko-saas-bucket-dev --endpoint-url=http://localhost:4566 --profile localstack
{
    "CORSRules": [
        {
            "AllowedHeaders": [
                "*"
            ],
            "AllowedMethods": [
                "GET",
                "POST",
                "PUT",
                "DELETE"
            ],
            "AllowedOrigins": [
                "*"
            ],
            "ExposeHeaders": [
                "ETag"
            ]
        },
        {
            "AllowedHeaders": [
                "*"
            ],
            "AllowedMethods": [
                "GET",
                "POST",
                "PUT",
                "DELETE"
            ],
            "AllowedOrigins": [
                "https://app.localstack.cloud"
            ],
            "ExposeHeaders": [
                "ETag"
            ]
        }
    ]
}

```
and still I'm getting CORS error in the browser when accessing PUT S3 presigned url

**Comment by diegosasw** [comment]
Thank you for your reply, setting `s3.localhost.localstack.cloud:4566` as serviceURL in the code which generates the presigned url solved the issue.

By default, with that, CORS was blocking the url.
Setting the ` DISABLE_CORS_CHECKS=1` as environment variable didn't make any difference.

But when configuring CORS directly in the bucket, the policy was correctly applied and respected, and now CORS to the specified origin is allowed.

PS: The scenario was, localstack running as a docker compose service, and the back-end and frond-end apps running on localhost without any container)

**Comment by GustavoOS** [comment]
> Thank you for your reply, setting `s3.localhost.localstack.cloud:4566` as serviceURL in the code which generates the presigned url solved the issue.
> 
> By default, with that, CORS was blocking the url. Setting the ` DISABLE_CORS_CHECKS=1` as environment variable didn't make any difference.
> 
> But when configuring CORS directly in the bucket, the policy was correctly applied and respected, and now CORS to the specified origin is allowed.
> 
> PS: The scenario was, localstack running as a docker compose service, and the back-end and frond-end apps running on localhost without any container)

How did you manage to do that? By changing the compose file?

**Comment by GustavoOS** [comment]
> Thank you for your reply, setting `s3.localhost.localstack.cloud:4566` as serviceURL in the code which generates the presigned url solved the issue.
> 
> By default, with that, CORS was blocking the url. Setting the ` DISABLE_CORS_CHECKS=1` as environment variable didn't make any difference.
> 
> But when configuring CORS directly in the bucket, the policy was correctly applied and respected, and now CORS to the specified origin is allowed.
> 
> PS: The scenario was, localstack running as a docker compose service, and the back-end and frond-end apps running on localhost without any container)

@diegosasw How did you manage to do that? Was your compose file modified?

**Comment by bentsku** [comment]
@GustavoOS I believe they only set the endpoint URL of the SDK client generating the pre-signed URL (running on their host) to `s3.localhost.localstack.cloud:4566`.  What issue are you encountering?

**Comment by GustavoOS** [comment]
for me browser is like
`Access to fetch at 'http://s3.localhost.localstack.cloud:4566/my-bucket/s3-srlckfxsnq?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=test%2F20240523%2Fus-east-2%2Fs3%2Faws4_request&X-Amz-Date=20240523T192207Z&X-Amz-Expires=3600&X-Amz-Signature=d8ae4625b04c20a96172df1feabe31936d272b638740ce5ecf601a16486ee9fa&X-Amz-SignedHeaders=host&x-id=PutObject' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

he mentioned something like setting CORS policy directly on the bucket
