### ISSUE TITLE
PyPI package still broken for python 3.7

### ISSUE THREAD

**Issue by tommp4** [localstack/localstack#979]
Hi,

As I'm sure you're aware ([especially because it was fixed](https://github.com/localstack/localstack/commit/fa1a64c954b89b88ac30e77fd12930efc04c04c5)), python 3.7 introduced some changes that prevented localstack from starting. In particular, `async` is now a reserved keyword and cannot be used as a variable name.

I was wondering what your release strategy is, because both PyPI and this repository report a version of 0.8.7, yet the PyPI package is still using code from before the fix was introduced. Since I was able to clone and build this package locally using python 3.7, I wanted to ask whether there was a specific reason for not upgrading the PyPI package.

Cheers!

**Comment by kiwiholmberg** [comment]
I ran into this issue as well. Docs state support for python 3.x but in practice when installing with pip, it should be 3.0.x - 3.6.x

**Comment by whummer** [comment]
Thanks for reporting - should be fixed in the meantime.
