### ISSUE TITLE
AWS SAM Function fails to create in v3.0.2

### ISSUE THREAD

**Issue by JohnathanBarclay** [localstack/localstack#9795]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Since the v3.0.2 release, the AWS SAM CLI for Localstack (samlocal) fails to deploy functions.

We set the region to `eu-west-1` in the SAM configuration file, and this is picked up by the tool:

![image](https://github.com/localstack/localstack/assets/84143638/9a37df0f-b9d1-49ff-87b2-56def50d08fc)

However, functions fail to create, with the following error:

![image](https://github.com/localstack/localstack/assets/84143638/d4251aab-a7a8-4e19-ba60-b57acbcb610a)

It looks like it's looking for the function in `us-east-1` rather than `eu-west-1`.

Reverting back to v3.0.1 fixes the issue.

### Expected Behavior

Functions should create successfully.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker-compose.yml

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    samlocal deploy

### Environment

```markdown
- OS: ubuntu-20.04
- LocalStack: v3.0.2
```

**Comment by viren-nadkarni** [comment]
Hi @JohnathanBarclay 

This must be related to https://github.com/localstack/localstack/pull/9787.

Could you please try the latest image and let us know if this persists?

**Comment by JohnathanBarclay** [comment]
> Hi @JohnathanBarclay
> 
> This must be related to #9787.
> 
> Could you please try the latest image and let us know if this persists?

Looks like it's all sorted. Thanks @viren-nadkarni 👍.
