### ISSUE TITLE
bug: API Gateway + OpenAPI with Integration doesn't respect integration httpMethod

### ISSUE THREAD

**Issue by zollf** [localstack/localstack#9804]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When using `x-amazon-apigateway-integration` and setting `httpMethod`, it won't use `httpMethod` that is set, instead it looks like it is using the incoming request method.

Here is an example:

```terraform
resource "aws_api_gateway_rest_api" "main" {
  name = "TestApiGateway"

  body = jsonencode({
    openapi = "3.0.3"
    #...other properties
    paths = {
      # ... other methods
      "/" = {
        delete = {
          summary = "DELETE Test"
          description = "DELETE Test"
          "x-amazon-apigateway-integration" = {
            httpMethod           = "POST"
            type                 = "aws"
            passthroughBehaviour = "WHEN_NO_TEMPLATES"
            uri                  = "arn:aws:apigateway:${local.region}:events:action/PutEvents"
            requestTemplates     = {
              "application/json" = "..."
            }
          }
          responses = {
            "200" = {
              description = "Success"
              content = {}
            }
          }
        }
      }
    }
  })
}
```

In `x-amazon-apigateway-integration` I have `httpMethod` "POST", however the current behaviour is using "DELETE" when integrating with AWS services. This setup works on AWS

This breaks `arn:aws:apigateway:${local.region}:events:action/PutEvents` as it expects "POST" but receives "DELETE"

This is the output when sending a DELETE request to that endpoint

```bash
egration for API Gateway ID 'uhy3xhv50s': API Gateway integration type "AWS", method "DELETE", URI "arn:aws:apigateway:ap-southeast-2:events:action/PutEvents" not yet implemented
```

### Expected Behavior

Expected behaviour is for `httpMethod` within `x-amazon-apigateway-integration` to control the method used within for aws integrations. 

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

I've created a replication repository using terraform and docker-compose: https://github.com/zollf/localstack-apigateway-integration-bug

### Environment

```markdown
- OS: macOS Sonoma Version 14.0
- LocalStack: latest
```

**Comment by mmarkus-twilio** [comment]
Hello!
We have stumbled onto the same issue. This issue is closed but it doesn't look like this has been included in the latest release. Can you confirm?

**Comment by bentsku** [comment]
Hello @mmarkus-twilio!

I believe the fix should be part of the release, what `latest` release are you on? Could try pulling it again or use `3.1` and see if that would work? If not, could you open a new issue with your use-case. Thanks!

**Comment by mmarkus-twilio** [comment]
We tried with the version `3.1.0` and the `httpMethod` was ignored, we could put anything there, it didn't even validate the value is legal. However, we are trying to `PUT` and from the logs we can see that it is trying to `GET` instead.

**Comment by bentsku** [comment]
Okay, that doesn't sound too good. Could you share a small snippet so that we could validate it and fix the issue then?
For what integration type is it configured? I think this fixed it for `AWS` integration type, but it looks like it might still not be correct for `HTTP` or `HTTP_PROXY`.

If you could share a small snippet like the OP provided, that could help narrow down the issue and get a fix out quickly. Thanks!
