### ISSUE TITLE
bug: Error deleting lambda

### ISSUE THREAD

**Issue by phildunphytoo** [localstack/localstack#9819]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Running `aws --endpoint-url http://<localstack_ip>:4566 lambda delete-function --function-name <lambda_name>` returns error:
`An error occurred (ResourceNotFoundException) when calling the DeleteFunction operation: Function not found: arn:aws:lambda:us-east-1:00000000000:function:my_lambda`

When running `aws ... lambda list-functions` I do see that lambda

### Expected Behavior

Lambda is deleted

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

docker-compose.yml with following parameters:
DEBUG=1

(Running without internet connection:)
SKIP_SSL_CERT_DOWNLOAD=1
DISABLE_EVENTS=1

Created the lambda using the `lambda create-function` API successfully.

### Environment

```markdown
- OS: RHEL 8.6 (Docker version 20.10.7)
- LocalStack: 3.0 and 3.0.2 (latest)
```

**Comment by lakkeger** [comment]
Hi @phildunphytoo,
Thank you for getting in touch with us. I've looked into your issue, however unfortunately I was unable to reproduce it by the available information. Could you please provide us the run logs and the diagnostic endpoint's response by doing the following:
- start up localstack with `DEBUG=1`
- run `curl <localstack_ip>:4566/_localstack/diagnose`

**Comment by phildunphytoo** [comment]
when running in Debug I see:
```
exception during call chain
...
...
...
ValueError; Unable to find version manager for arn:aws:lambda:us-east-1:0000000000:function:<MyFunction>:$LATEST
```

In the curl I see I'm missing all the docker-dependent-image-hashes, I'm running offline, how can I change the path of those I need?

**Comment by phildunphytoo** [comment]
The issue was that the Lambda wasn't being created correctly as I didn't configure LAMBDA_RUNTIME_IMAGE_MAPPING setting. Now it's working fine!

**Comment by phildunphytoo** [comment]
The issue was that the Lambda wasn't being created correctly as I didn't configure LAMBDA_RUNTIME_IMAGE_MAPPING setting. Now it's working fine!
