### ISSUE TITLE
bug: ServiceDiscovery Create Duplicate Service Behavior is Inconsistent between the SDK API and with the CLI

### ISSUE THREAD

**Issue by cbjogura** [localstack/localstack#9823]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

As previously reported, and currently fixed the CLI now behaves properly when creating a service with duplicate name.

```
awslocal servicediscovery list-services

awslocal servicediscovery create-service --name duplicate-service --
namespace c99725e7 --dns-config "NamespaceId=ns-
c99725e7,RoutingPolicy=WEIGHTED,DnsRecords=[{Type=CNAME,TTL=300}]"

awslocal servicediscovery create-service --name duplicate-service --
namespace c99725e7 --dns-config "NamespaceId=ns-
c99725e7,RoutingPolicy=WEIGHTED,DnsRecords=[{Type=CNAME,TTL=300}]"
```

Results in `An error occurred (ServiceAlreadyExists) when calling the CreateService operation: Service already exists.`

However, when using the SDK (v3) the Service is created without any error resulting in duplicate services:

```
      const createServiceInput: CreateServiceCommandInput = {
        Name: serviceName,
        Description: description || 'No description provided',
        DnsConfig: {
          NamespaceId: 'namespaceId'
          RoutingPolicy: 'WEIGHTED', //ROUTING_POLICY,
          DnsRecords: [
            {
              TTL: 300,
              Type: 'CNAME',
            },
          ],
        },
      };

      const createServiceResponse = await this.serviceDiscoveryClient.send(new CreateServiceCommand(createServiceInput));
```

### Expected Behavior

To throw an error similar to the response from the CLI

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker-compose up --wait -d

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

Uses AWS SDK (v3) javascript: 

```
      const createServiceInput: CreateServiceCommandInput = {
        Name: serviceName,
        Description: description || 'No description provided',
        DnsConfig: {
          NamespaceId: 'namespaceId'
          RoutingPolicy: 'WEIGHTED', //ROUTING_POLICY,
          DnsRecords: [
            {
              TTL: 300,
              Type: 'CNAME',
            },
          ],
        },
      };

      const createServiceResponse = await this.serviceDiscoveryClient.send(new CreateServiceCommand(createServiceInput));
```

### Environment

```markdown
- OS: MacOS Ventura
- LocalStack: 3.0.2 (pro)
```

**Comment by alexrashed** [comment]
Hi @cbjogura!
Thanks for reporting this issue!
The difference was in fact that with the CLI calls you set the namespace directly on the service, where on the SDK calls you set it on the DNS config.
However, we just fixed this issue in the latest localstack-pro image. Please make sure to explicitly pull to make sure your latest tag is up to date.
I'll close this issue for now. Please let us know if you experience any more issues.
Thanks!
