### ISSUE TITLE
AWS lambda on localstack not seeing its dependencies 

### ISSUE THREAD

**Issue by ladams81** [localstack/localstack#983]
Hi guys. I am running localstack 0.8.7 and i am encountering problems running a lambda function that has external dependencies. The zip file works well in a real AWS environment but fails in localstack because it cannot find the dependencies.

Adding lambda
`
aws --endpoint-url=http://localhost:4574 lambda create-function --function-name=myfunction --runtime=java8 --role=r1 --handler=com.my.UpdateHandler --zip-file fileb://my-lambda-0.1.0-1540476215-64df908.zip
`

Executing lambda
`
aws lambda --endpoint-url=http://localhost:4574 invoke --invocation-type RequestResponse --function-name myfunction --region eu-west-1 --payload {\"store\":\"9722\"\,\"pos\":\"80\"\,\"app\":\"price\"} out.txt
`

This is the stacktrace
`
Exception: Lambda process returned error status code: 1. Output:
Exception in thread "main" java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    at cloud.localstack.LambdaExecutor.getHandler(LambdaExecutor.java:138)
    at cloud.localstack.LambdaExecutor.main(LambdaExecutor.java:52)
Caused by: java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/ObjectMapper
    at my.create(Houston.java:56)
    at my.UpdateHandler.<init>(UpdateHandler.java:17)
    ... 6 more
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.databind.ObjectMapper
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 8 more
`

I'm suspicious that the problem could be with localstack since the zip file with the structure

-lib    (dependencies)
-com (lambda)

 works fine in AWS but has problems in localstack. 

Help. 

A guy in need.

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-321) by [Unito](https://www.unito.io/learn-more)

**Comment by oripwk** [comment]
I can confirm we're experiencing the same problem

**Comment by fioreggianni** [comment]
This might be a problem with the buggy logics LocalStack uses to split the name file and the handler function in `com.my.UpdateHandler`. I recommend you have a try with your handler defined in a file in the main namespace like `my.UpdateHandler` where `my.java` is a file in your first level directory in the zip file. They assume you set there handler in the form `filename.function`, but prepared no logics in case you have got a string there with the `filename[.extension]` (where `extension` is derived by them when they look at the runtime you declare) nested in packages.

**Comment by rsosnin** [comment]
I am having same issue... Using same lambda artifact (zip containing the lambda code + external dependencies) - working in AWS, but cannot deploy in localstack:

```
localstack-init_1        | Lambda | Error occurred while creating Function: save_event | Details: An error occurred (InternalFailure) when calling the CreateFunction operation (reached max retries: 4): Unknown error: ('Unable to get handler function from lambda code.', ImportError('No module named <MY_DEPENDENCY>',)) Traceback (most recent call last):
```

**Comment by rsosnin** [comment]
Getting this error actually when running `LAMBDA_EXECUTOR: local`
But if I use `LAMBDA_EXECUTOR: docker-reuse` - i don't have that issue

**Comment by toddtarbox-vertex** [comment]
I'm having the same issue as the original post, `java.lang.ClassNotFoundException`, on all external dependencies. Has anyone been able to figure out how to get this working in localstack?

**Comment by whummer** [comment]
Thanks for reporting @ladams81 @oripwk @fioreggianni @rsosnin @toddtarbox-vertex . Can you please provide a small, self-contained example that helps reproducing this issue? Thanks!

**Comment by duongpv7** [comment]
Thanks for reporting @ladams81, @oripwk, @rsosnin, @toddtarbox-vertex.
We added an integration test with java lambda zip files in #3704, can you please pull the latest Docker image and give it another try?
Please let us know if the problem persists. Thanks
