### ISSUE TITLE
bug: Lambda doesn't assume execution role

### ISSUE THREAD

**Issue by barbern** [localstack/localstack#9830]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

A lambda runs as the root user ([GetCallerIdentity](https://docs.aws.amazon.com/STS/latest/APIReference/API_GetCallerIdentity.html) returns its ARN).

### Expected Behavior

It should assume its execution role.

This can be done explicitly with [AssumeRole](https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRole.html).

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

LOCALSTACK_AUTH_TOKEN=... DEBUG=1 ENFORCE_IAM=1 localstack start

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

I'm currently testing with the Go SDK but I can include some code snippets around `GetCallerIdentity`/`AssumeRole` if it would be useful.

### Environment

```markdown
- OS: macOS Sonoma 14.1.2
- LocalStack: 3.0.2
```

**Comment by dfangl** [comment]
Hi @barbern !
Lambda does indeed assume the role provided as execution role. You can check the `AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY` and `AWS_SESSION_TOKEN` variables in your container. Can you please double check if those are set in your environment? You might have to check if your SDK is configured to ignore them / override them.

**Comment by barbern** [comment]
@dfangl you're right. Silly mistake on my end initializing a session.

Thanks for the help. This can be closed.
