### ISSUE TITLE
bug: ACM is supported but ACM-PCA isn’t

### ISSUE THREAD

**Issue by frank-lenormand** [localstack/localstack#9836]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Pointing `boto3` to LocalStack using the `acm-pca` service name yields an error:

```
E           botocore.exceptions.ClientError: An error occurred (InternalFailure) when calling the CreateCertificateAuthority operation: API for service 'acm-pca' not yet implemented or pro feature - please check https://docs.localstack.cloud/references/coverage/ for further information
```

I see that ACM is supported by LocalStack:

https://docs.localstack.cloud/references/coverage/coverage_acm/

I think that the overlap between the functionality of ACM and ACM-PCA is substantial, and implementing the API for the latter would be reasonably easy, using the code for the former.

Are there any plans to fill that gap?

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal s3 mb s3://mybucket

**Comment by HarshCasper** [comment]
Hi @frank-lenormand — Thanks for creating the issue! We have shipped a CRUD implementation that should unblock you. Please pull the `localstack/localstack-pro:latest` Docker image, and let us know your feedback! 🙏

**Comment by frank-lenormand** [comment]
Thanks for that!

Unfortunately I do not have access to the Pro image, would it be possible to push that changeset to mainstream? Or maybe a separate Docker image hash, so I can pull it specifically?

I can also generate the image myself based off your patch, as a last resort.
