### ISSUE TITLE
bug: Lambda function url automatically base64 encoding the body

### ISSUE THREAD

**Issue by adiberk** [localstack/localstack#9842]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It seems that my request to my lambda function (using lambda function url) is automatically being encoded to base64 even though the content type is set to application/json. This is resulting in issues. This isn't happening in my real aws environment

### Expected Behavior

I would expect the lambda function url to supply the actually body from the request and not encode it

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal s3 mb s3://mybucket

### Environment

```markdown
- OS: Mac M1
- LocalStack: 2.3.2
```

### Anything else?

Here is how I create the lambda function url

```
create_function_url() {
	local FUNCTION_NAME=$1
	local AUTH_TYPE=$2
	local FUNCTION_URLS=$(awslocal lambda list-function-url-configs --function-name $FUNCTION_NAME)
	if ! echo "$FUNCTION_URLS" | grep -q "$FUNCTION_NAME"; then
		echo "$(awslocal lambda create-function-url-config --function-name "$FUNCTION_NAME" --auth-type "$AUTH_TYPE")"
	else
		local FUNCTION_URL=$(echo "$FUNCTION_URLS" | jq -r --arg fname "$FUNCTION_NAME" '.FunctionUrlConfigs[] | select(.FunctionArn | contains($fname)).FunctionUrl')
		echo "${FUNCTION_NAME} already has a URL: ${FUNCTION_URL}"
	fi
}
```

**Comment by adiberk** [comment]
Figured it out - it can also happen based on payload size

**Comment by salmankhalid-plt** [comment]
@adiberk what was the solution i am running into the similar issue ... the payload i am using is over 250KB .. how to stop it from being auto encoded ?
