### ISSUE TITLE
enhancement request: implement timestream persistence

### ISSUE THREAD

**Issue by chris-schulz-labs** [localstack/localstack#9849]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Enhancement description

The Timestream state is currently not being persisted or loaded correctly. Please implement persistence for Timestream, preferably for both the infrastructure state (database, tables, etc.) and the application state (time series data).

**Comment by giograno** [comment]
Hi @chris-schulz-labs, we implemented persistence for timestream. You will find the implementation in the `latest` Docker image. Please feel free to report any particular issue you might encounter. Thanks.
