### ISSUE TITLE
Official Docker Hub repository

### ISSUE THREAD

**Issue by greenkiwi** [localstack/localstack#985]
I am assuming that this is the officially maintained docker repo:
https://hub.docker.com/r/localstack/localstack/

It doesn't have much if any information about the owner of the repo, the dockerfile or the repo itself.  

It would be great if this repo had move information that helped people understand that it was the official repo.  

As an example, if you look at the repo for Flyway
https://hub.docker.com/r/boxfuse/flyway/

You can see that the owner is clearly called out, there is some documentation and the dockerfile itself is clearly visible.  This gives me as a developer more confidence in using it and helps make the devops engineers on our team happy.

Some changes that might help would be having it point to a repo in your github org that had the docker files in it.

**Comment by devoto13** [comment]
See third bullet point under [Announcements](https://github.com/localstack/localstack#announcements), so probably answer is "Yes, this is an official Docker image".

But I would also like to have a trusted build configured to be able to see the `Dockerfile` used to build the image.

**Comment by whummer** [comment]
Thanks for reporting. The README on Docker Hub has been updated. We're currently using a custom Docker build which gives us more flexibility for small customizations (e.g., using a base image, then squashing the final image into a single layer), but the image is built and pushed by TravisCI - the configuration is available in the repository as well. Thanks
