### ISSUE TITLE
Second call to S3.UploadPart returns invalid response if first call is cancelled

### ISSUE THREAD

**Issue by adam-fowler** [localstack/localstack#9851]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If a call to `S3.UploadPart` is cancelled halfway through and then called again the `Etag` header returned in the second call's response is set to "None".

### Expected Behavior

I would expect the `Etag` header to have a valid Etag in it.

### How are you starting LocalStack?

With a docker run command

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

I found this while testing Soto the unofficial Swift SDK for AWS. It is hard to replicate using the CLI as each run of the CLI creates a new multipart upload. You can find the test that fails here https://github.com/soto-project/soto/blob/92623a6943cbbed9e57af80468d318506abce13c/Tests/SotoTests/Services/S3/S3Tests%2Basync.swift#L623. It starts a multipart upload, and cancels it half way through and then calls a resume function which will retry uploading the parts that haven't fully uploaded.

### Environment

```markdown
- OS: MacOS 14.1.2
- LocalStack: 3.0.3.dev
```

**Comment by bentsku** [comment]
Hello @adam-fowler and thanks for your report!

Nice to see LocalStack being used here 😄
I'll try running the tests myself, and fix this issue. Thanks a lot again for reporting!

**Comment by bentsku** [comment]
Hello @adam-fowler and thanks again for the report!
The issue should be fixed in the `latest` image. Don't hesitate to report any issues with LocalStack. I'll give a try to the tests being skipped in your test suite 😄 thanks again!
