### ISSUE TITLE
Starting with localstack - possible to run in a docker container with no python installed locally?

### ISSUE THREAD

**Issue by ababkin** [localstack/localstack#986]
Hi
From reading the instructions in the readme, it looks like one needs a python env in order to run `localstack` either locally or in a container.
I however would like to keep my local machine completely python-free, so would like to know how to go about containerizing all parts that require python.

Thank you

**Comment by mhmoudgmal** [comment]
You don't need python installed if you use the `localstack` docker image, check https://github.com/localstack/localstack/blob/master/docker-compose.yml

you can also not use docker-compose bu you need to transform the docker-compose file to a command.

hint:

```sh
docker run -d -p "4567-4583:4567-4583"                        \
             -p $LOCALSTACK_PORT_WEB_UI:$LOCALSTACK_PORT_WEB_UI \
             -v $LOCALSTACK_TMPDIR:$LOCALSTACK_TMPDIR           \
             -v /var/run/docker.sock:/var/run/docker.sock       \
             -e SERVICES=$LOCALSTACK_SERVICES                   \
             -e DEBUG=$LOCALSTACK_DEBUG                         \
             -e DATA_DIR=$LOCALSTACK_DATA_DIR                   \
             -e PORT_WEB_UI=$LOCALSTACK_PORT_WEB_UI             \
             -e LAMBDA_EXECUTOR=$LOCALSTACK_LAMBDA_EXECUTOR     \
             -e KINESIS_ERROR_PROBABILITY=$LOCALSTACK_KINESIS_ERROR_PROBABILITY   \
             -e DYNAMODB_ERROR_PROBABILITY=$LOCALSTACK_DYNAMODB_ERROR_PROBABILITY \
             -e DOCKER_HOST=unix:///var/run/docker.sock \
             --name my_localstack \
             localstack/localstack
```

**Comment by ababkin** [comment]
will try this, thank you!

**Comment by suryacaprice** [comment]
when running docker with this command

docker: invalid publish opts format (should be name=value but got '4567-4583:4567-4583').
See 'docker run --help'.

**Comment by Minakami92** [comment]
I have the same problem.

$ docker run -itd -p 10080:80 -p 100443:443 --name ubuntu ubuntu-bionic 
docker: invalid publish opts format (should be name=value but got '10080:80').
See 'docker run --help'.

Please help me!

**Comment by Allen2Git** [comment]
> I have the same problem.
> 
> $ docker run -itd -p 10080:80 -p 100443:443 --name ubuntu ubuntu-bionic
> docker: invalid publish opts format (should be name=value but got '10080:80').
> See 'docker run --help'.
> 
> Please help me!

The TCP port should be in 0~65535, please change 100443 to less than 65535 for example 6443 to go ahead.
