### ISSUE TITLE
enhancement request: EC2 API and IMDS support for Karpenter

### ISSUE THREAD

**Issue by stirlingalgermissen** [localstack/localstack#9869]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Enhancement description

Karpenter (https://karpenter.sh/) for EKS relies on a number of EC2 and IMDS API calls that are currently not fully supported LocalStack. Specifically:

- [x] ec2:DescribeInstanceTypes 
  - Also covered in #9854
- [ ] ec2:DescribeInstanceTypeOfferings
- [x] Instance Metadata Sevice 
  - Also covered in #8911
  - CSI Drivers for EFS, Mountpoint, and EBS all depend on the EC2 Instance Metadata Service (IMDS) — this is unrelated to Karpenter but shows that the IMDS is a cross-cutting dependency for many EKS integrations
  - Example error: 
    - `{"level":"DEBUG","time":"2023-11-29T02:27:34.042Z","logger":"controller","message":"retrieving region from IMDS","commit":"1072d3b"}
panic: failed to get region from metadata server: EC2MetadataRequestError: failed to get EC2 instance identity document
caused by: RequestError: send request failed
caused by: Get "http://169.254.169.254/latest/dynamic/instance-identity/document": dial tcp 169.254.169.254:80: connect: connection refused` 
- There may be others

This request is for Karpenter support with EKS running on LocalStack.

**Comment by viren-nadkarni** [comment]
Hi @stirlingalgermissen, we recently added the instance metadata service to EC2 Docker backend.

https://docs.localstack.cloud/user-guide/aws/elastic-compute-cloud/#instance-metadata-service

Please give it a try and let us know any feedback!

**Comment by stirlingalgermissen** [comment]
Thank you!!

**Comment by drewm-jpl** [comment]
Thanks @viren-nadkarni!

We can't wait to give this a try.
