### ISSUE TITLE
AWS Lambda Dead Letter Queue is not working?

### ISSUE THREAD

**Issue by jiseruk** [localstack/localstack#988]
Hi I am creating a lambda, passing with a DeadLetterConfig with a valid queue arn as a TargerArn param, but when the lambda fails it doesn't send the event to that queue.

This is the code of my lambda:
```
def handler(event, context):
    print('Loading function')
    # Get the queue
    endpoint = os.getenv('subscriber_url', None)
    topic = os.getenv('topic', None)
    message = json.loads(event['Records'][0]['Sns']['Message'])
    payload = {"message": message, "topic": topic}
    r = requests.post(endpoint, json=payload, headers={"Content-type": "application/json"})
    print("POST message result: ", r.status_code)
    if r.status_code >= 400:
        raise Exception("Fail posting to " + endpoint + " Response: " + str(r.status_code) + "|" + r.content)
```

When I force the request that the lambda makes to fail twice or more times, I throw an exception. But the event is not sent to the dead-letter-queue.

Is the dead letter queue functionality implemented in localstack? Or maybe I'm doing something bad.

Can you help me ? 

Thanks!
Regards.

**Comment by poupougnac** [comment]
I have the same issue. Dead-letter-queue doesn't seems to work with lambdas based on sqs queues.

**Comment by whummer** [comment]
Thanks for reporting @jiseruk @poupougnac . Support for Lambda dead letter queues has been added in #1898 - can you please give it a try with the latest version of the Docker image. Thanks

**Comment by ashameem123** [comment]
@jiseruk @poupougnac   - Could you please elaborate how you mapped the dlq and lambda together? if any redrive policy was used ?
