### ISSUE TITLE
bug: Step Functions Map ProcessorConfig should be optional

### ISSUE THREAD

**Issue by guillaume-macquat** [localstack/localstack#9882]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm trying to create a state machine using the following definition that I validated on AWS:

```json
{
  "StartAt": "SetupVariables",
  "States": {
    "SetupVariables": {
      "Type": "Pass",
      "Parameters": {
        "items": []
      },
      "Next": "Map"
    },
    "Map": {
      "Type": "Map",
      "ItemsPath": "$.items",
      "ItemProcessor": {
        "StartAt": "Pass",
        "States": {
          "Pass": {
            "Type": "Pass",
            "End": true
          }
        }
      },
      "End": true
    }
  }
}
```

I get the following error:

```
│ Error: updating Step Functions State Machine (arn:aws:states:eu-west-3:000000000000:stateMachine:my-state-machine): InvalidDefinition: Error=ValueError Args=['Expected a ProcessorConfig declaration at \'"ItemProcessor":{"StartAt":"Pass","States":{"Pass":{"Type":"Pass","End":true}}}\'.'] in definition '{
│   "StartAt": "SetupVariables",
│   "States": {
│     "SetupVariables": {
│       "Type": "Pass",
│       "Parameters": {
│         "items": []
│       },
│       "Next": "Map"
│     },
│     "Map": {
│       "Type": "Map",
│       "ItemsPath": "$.items",
│       "ItemProcessor": {
│         "StartAt": "Pass",
│         "States": {
│           "Pass": {
│             "Type": "Pass",
│             "End": true
│           }
│         }
│       },
│       "End": true
│     }
│   }
│ }
│ '.
│ 
│   with aws_sfn_state_machine.main,
│   on stepFunction.tf line 1, in resource "aws_sfn_state_machine" "main":
│    1: resource "aws_sfn_state_machine" "main" {
```

On AWS the ProcessorConfig field is optional.
[The AWS documentation](https://docs.aws.amazon.com/step-functions/latest/dg/concepts-asl-use-map-state-inline.html) specifies that this field is optional and provides [an example omitting it](https://docs.aws.amazon.com/step-functions/latest/dg/concepts-asl-use-map-state-inline.html).
When using the AWS workflow editor I get an error saying "Map (ItemProcessor.ProcessorConfig): Value is mandatory."  but the creation still succeeds.

### Expected Behavior

The definition should be considered valid and the state machine should be created.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

Create a state machine using the provided definition.

### Environment

```markdown
- LocalStack: 3.0.3.dev20231207105008
```

**Comment by MEPalma** [comment]
Thanks a lot for providing this detailed issue report. We have implemented changes to tackle the concerns in the Step Functions v2 interpreter. Continuous improvement is our priority, and inputs like yours are incredibly valuable. If you have more feedback or encounter any issues, please don't hesitate to reach out in the future. Much appreciated!

**Comment by guillaume-macquat** [comment]
Thanks a lot to you too and to the LocalStack team! I have been very impressed by how efficiently you managed to tackle these issues and I'm super enthusiast to use LocalStack.
I'd like to use this opportunity to ask you could you please take a look at [this one](https://github.com/localstack/localstack/issues/9809#issuecomment-1857868355) too?
