### ISSUE TITLE
bug:  SQS state getting lost in pro image

### ISSUE THREAD

**Issue by nitesh237** [localstack/localstack#9890]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Resources created in SQS are getting lost on the pod restart in the pro image, even with persistence `PERSISTENCE: 1` turned on.

Note: the pods are lunched and managed using stateful set with `/var/lib/localstack` path being mounted the host.

### Expected Behavior

Upon pod restart, the SQS queues created must be retained.

### How are you starting LocalStack?

With a `docker run` command

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

We are using custom helm charts to deploy localstack as stateful set in local minikub. The manifest can be seen as below:
```
------
Containers:
  localstack:
    Container ID: 
    Image:          localstack/localstack-pro:3.0.2
    Image ID:       XXXX
    Port:           4566/TCP
    Host Port:      0/TCP
    Environment Variables from:
      localstack-env  ConfigMap  Optional: false
    Environment:      <none>
    Mounts:
      /var/lib/localstack from localstack-data (rw,path="localstack")
----
podEnv:
  SERVICES: sqs, sns, s3, dynamodb, sts, kms, kinesis
  DEFAULT_REGION: ap-south-1
  PORT_WEB_UI: 8015
  SQS_DISABLE_CLOUDWATCH_METRICS: 1
  LOCALSTACK_AUTH_TOKEN: XXXXXX
  ACTIVATE_PRO: 1
  PERSISTENCE: 1
  EAGER_SERVICE_LOADING: 1
  DNS_ADDRESS: 0
  SNAPSHOT_LOAD_STRATEGY: ON_STARTUP
  SNAPSHOT_FLUSH_INTERVAL: 120
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)
1. Create any queue in any region
```
awslocal sqs create-queue --attributes '{ "VisibilityTimeout": "3" }' --queue-name test-queue --region ap-south-1
```
2. Wait for the snapshot to succeed
3. Restart the pod/container
```
kubectl rollout restart statefulset <statefuset-name>
```
4. Run command to list queues 
```
awslocal sqs list-queues --region ap-south-1
```

### Environment

```markdown
- OS: Ubuntu
- LocalStack:localstack-pro:3.0.2
```

### Anything else?

We know the configuration for the persistence with the auth key activation is working for sure as persistence is working for other services like S3 and SNS. The resources, in case of these services are retained upon pod restarts.

**Comment by MarcelStranak** [comment]
Hello @nitesh237,

Please download the latest LocalStack docker image `docker pull localstack/localstack-pro:latest` and set your docker-compose file. The new version should already contain the necessary fixes for the reported issue.
