### ISSUE TITLE
can't run localstack on a clean ubuntu 18.10 installation

### ISSUE THREAD

**Issue by avizana** [localstack/localstack#991]
I tried running localstack on a fresh clean installation of Ubuntu 18.10.
I installed all the packages needed in order to actually run make install for localstack:
git, python-dev, make, docker.io, python-pip, python-virtualenv, openjdk-8-jdk, npm

cloned the project:
git clone https://github.com/localstack/localstack.git

ran make install, it finished successfully.

then I ran make docker-build but it keeps failing with:

Step 11/24 : RUN make install
 ---> Running in c895abd7f87d
(test `which virtualenv` || pip install --user virtualenv) && \
	(test -e .venv || virtualenv  .venv) && \
	(test ! -e requirements.txt || (. .venv/bin/activate; pip -q install -r requirements.txt) && \
	. .venv/bin/activate; PYTHONPATH=. exec python localstack/services/install.py testlibs)
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f13119c7910>: Failed to establish a new connection: [Errno -3] Try again',)': /simple/airspeed/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f13119c7b90>: Failed to establish a new connection: [Errno -3] Try again',)': /simple/airspeed/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f13119c7cd0>: Failed to establish a new connection: [Errno -3] Try again',)': /simple/airspeed/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f13119c7e10>: Failed to establish a new connection: [Errno -3] Try again',)': /simple/airspeed/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f13119c7f50>: Failed to establish a new connection: [Errno -3] Try again',)': /simple/airspeed/
  Could not find a version that satisfies the requirement airspeed==0.5.5.dev20160812 (from -r requirements.txt (line 4)) (from versions: )
No matching distribution found for airspeed==0.5.5.dev20160812 (from -r requirements.txt (line 4))

I googled about this error, tried running pip install localstack but still the same issue.

am I missing something here? am I doing something wrong?

**Comment by mhmoudgmal** [comment]
If you just want to run localstack, you don't have to build the docker image yourself.
You can either use docker-compose against the compose file in this repo, or normally run localstack as a docker container. You can check my comment here https://github.com/localstack/localstack/issues/986#issuecomment-435528964

**Comment by avizana** [comment]
I'm modifying the source code. Therefore I need to build a new container. 

The error that I posted here is from the original source code without my changes.

**Comment by mhmoudgmal** [comment]
@avizana I had similar issues today. Can you try remove the base image `*localstack/java-maven-node-python*` (in my case it was 2 months old and cached) and rebuild from scratch. Not sure if that can help you.

**Comment by whummer** [comment]
Thanks for reporting, and for providing the solutions. Closing this issue as outdated - please re-open if the problem persists. Thanks
