### ISSUE TITLE
bug: <title> 404 error on POST to notification-endpoint during subscribe

### ISSUE THREAD

**Issue by mhlmhlmhlmhl** [localstack/localstack#9916]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

'awslocal sns subscribe' is getting a 404 when publishing 'SubscriptonConfirmation' -- but only when running in a docker container:
`2023-12-19 10:25:01 ++ awslocal --endpoint-url=http://localhost:4566 sns subscribe --topic-arn arn:aws:sns:us-west-2:000000000000:disclosure --protocol http --notification-endpoint http://localhost.localstack.cloud:4566/queue/us-west-2/000000000000/coi_aggregator_disclosure --region us-west-2
2023-12-19 10:25:01 2023-12-19T18:25:01.632 DEBUG --- [   asgi_gw_0] l.services.sns.publisher   : Topic 'arn:aws:sns:us-west-2:000000000000:disclosure' publishing 'SubscriptionConfirmation' to subscribed 'arn:aws:sns:us-west-2:000000000000:disclosure:2a78a2d5-0fe7-481c-8c6f-cf02a17f6af0' with protocol 'http' (Id='cd5912ec-a3db-4d80-9969-58434011717b', Subscription='http://localhost.localstack.cloud:4566/queue/us-west-2/000000000000/coi_aggregator_disclosure')
2023-12-19 10:25:01 2023-12-19T18:25:01.632  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS sns.Subscribe => 200
2023-12-19 10:25:01 2023-12-19T18:25:01.635  INFO --- [   asgi_gw_0] localstack.request.http    : **POST /queue/us-west-2/000000000000/coi_aggregator_disclosure => 404**
2023-12-19 10:25:01 2023-12-19T18:25:01.636  INFO --- [   sns_pub_0] l.services.sns.publisher   : Received error on sending SNS message, putting to DLQ (if configured): 404 Client Error:  for url: http://localhost.localstack.cloud:4566/queue/us-west-2/000000000000/coi_aggregator_disclosure
2023-12-19 10:25:01 + subscription='{
2023-12-19 10:25:01     "SubscriptionArn": "arn:aws:sns:us-west-2:000000000000:disclosure:2a78a2d5-0fe7-481c-8c6f-cf02a17f6af0"
2023-12-19 10:25:01 }'`

I tried running the same command manually from an iTerm outside the container, and got:

```
awslocal --endpoint-url=http://localhost:4566 sns subscribe --topic-arn arn:aws:sns:us-west-2:000000000000:disclosure --protocol http --notification-endpoint http://localhost.localstack.cloud:4566/queue/us-west-2/000000000000/coi_aggregator_disclosure --region us-west-2
{
    "SubscriptionArn": "arn:aws:sns:us-west-2:000000000000:disclosure:2a78a2d5-0fe7-481c-8c6f-cf02a17f6af0"
}
```

### Expected Behavior

The same results inside the container as outside! The SubscriptionConfirmation should get a 200, not 404, response.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

I ran 'awslocal --version' both inside the container and outside:

- inside: aws-cli/1.30.5 Python/3.11.6 Linux/6.5.11-linuxkit botocore/1.32.5
- outside: aws-cli/2.15.2 Python/3.11.6 Darwin/23.1.0 exe/x86_64 prompt/off

The container version is obtained via docker-compose "image: localstack/localstack:latest".

The version running from iTerm was installed via Homebrew:

```
 brew list awscli-local --versions
awscli-local 0.21.1
```

Here is my docker-compose file (edited to focus on localstack and sqs/sns):
```

name: coi_local_dependencies
services:
  localstack:
    privileged: true
    image: localstack/localstack:latest
    ports:
      - '4563-4599:4563-4599'
      - '8055:8080'
    environment:
      - SERVICES=sns,sqs
      - DEBUG=1
      - DEFAULT_REGION=us-west-2
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOSTNAME_EXTERNAL=localhost
      - SQS_ENDPOINT_STRATEGY=path
      - SQS_QUEUE_NAME=eform_admin_tenant_products
      - COI_AGGREGATOR_DISCLOSURE=coi_aggregator_disclosure
      - SNS_TOPIC_DISCLOSURE=disclosure
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./src/testIntegration/resources/aws/init:/etc/localstack/init/ready.d
```
I have 3 files in ./src/testIntegration/resources/aws/init:

1. aws_configure.sh which configures the aws_access_key_id and aws_secret_access_key.  This seems to work ok.
2. sns_init.sh which sets up several sns topics, including: `awslocal sns create-topic --name ${SNS_TOPIC_DISCLOSURE} --region ${DEFAULT_REGION} `
3. sqs_init.sh, which has these lines:

```
awslocal --endpoint-url=http://${HOSTNAME_EXTERNAL}:4566 sqs create-queue --queue-name ${COI_AGGREGATOR_DISCLOSURE} --region ${DEFAULT_REGION} --attributes VisibilityTimeout=30

awslocal --endpoint-url=http://${HOSTNAME_EXTERNAL}:4566 sns subscribe \
 --topic-arn arn:aws:sns:us-west-2:000000000000:${SNS_TOPIC_DISCLOSURE} --protocol http \
 --notification-endpoint http://localhost.localstack.cloud:4566/queue/${DEFAULT_REGION}/000000000000/${COI_AGGREGATOR_DISCLOSURE} \
--region ${DEFAULT_REGION}
```
The last line is the one that is failing. This is the one that works fine when I run it manually outside the container.

### Environment

```markdown
- OS:MacOS Sonoma 14.1 on an Apple M3 Pro
- LocalStack: latest
```

### Anything else?

I don't understand why localstack is version 1.3.5 when running inside the docker container, considering that I specified "latest".  That seems like an obsolete version.

I tried substituting the ARN for the URL in the endpoint-url parameter of the sns subscribe command -- but that produced another error indicating it was the wrong parameter type.

**Comment by bentsku** [comment]
Hello @mhlmhlmhlmhl and thanks for your report.

Are you trying to publish an SNS message to an SQS queue? In that case, you need to properly select the type of subscriber to `SQS`, SQS won't be able to parse the `HTTP` notification type. 

This would be the command to use to subscribe an SQS queue to an SNS topic:
```bash
awslocal --endpoint-url=http://${HOSTNAME_EXTERNAL}:4566 sns subscribe \
 --topic-arn arn:aws:sns:us-west-2:000000000000:${SNS_TOPIC_DISCLOSURE} --protocol sqs \
 --notification-endpoint <SQS-QUEUE-ARN> --region ${DEFAULT_REGION}
```

Even though the command runs from outside the container, it won't work when actually trying to publish to the SNS topic. the format of notification between SQS and HTTP subscriptions is different. Also, it would not work against AWS.

For the version of the CLI, it seems it returns the version of the underlying `awscli`. `aws-cli/1.30.5` is one of the latest version of the AWS CLI v1, and is not obsolete.

**Comment by mhlmhlmhlmhl** [comment]
Problem solved - thank you.

**Comment by bentsku** [comment]
Awesome, thanks for the feedback! I'll close the issue.
