### ISSUE TITLE
enhancement request: Support InputTransformer on Event Bridge Rule Targets

### ISSUE THREAD

**Issue by shawncarr** [localstack/localstack#9918]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Enhancement description

Currently `InputTransformer`, which is part of a target for a Event Bridge rule is not implemented. `InputPath` is which sends what ever the object is at the provided path. But the `InputTransformer` alllows customization what is sent to the target which is helpful in a ton of situations. 

### 🧑‍💻 Implementation

In the [Events/Provider](https://github.com/localstack/localstack/blob/master/localstack/services/events/provider.py#L166) you check for it the property as part of the target. 

You also have `extract_jsonpath` which is used as part of `InputPath`. Seems like you could do a simple loop through the `InputPathsMap` and get the key/value pairs then do a replace in the `InputTemplate` which would then would be used as the `event` object.

**Comment by maxhoheiser** [comment]
I wanted to bring your attention to PR #10159 , where we've successfully fixed the above-described issues. To test the new functionality, please ensure you're running the latest Docker image.
