### ISSUE TITLE
enhancement request: basic support for identitystore

### ISSUE THREAD

**Issue by joelmccoy** [localstack/localstack#9933]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Enhancement description

Requesting basic support for mocking out the creation of users and groups in [identitystore](https://docs.aws.amazon.com/singlesignon/latest/IdentityStoreAPIReference/welcome.html).

Identitystore is the foundation for using the sso-admin APIs.  Eventually I would like to see support for all the identity center APIs (sso-admin, identity-store). By having these identitystore APIs in place, basic functionality for sso-admin can come later.

Requesting basic CRUD operations for users and groups.  At the very minimum the following API calls:

1. create, describe, list, delete groups
2. create, describe, list, delete users

### 🧑‍💻 Implementation

[moto](https://docs.getmoto.org/en/latest/docs/services/identitystore.html) already has many of these calls mocked out.  Suggestion is that we use the moto models to implement these basic CRUD operations.

### Anything else?

I am open to working on this feature as a new contributor.  I have extensive experience with the AWS IAM Identity Center APIs and could be of value adding functionality to localstack.

**Comment by HarshCasper** [comment]
Hi @joelmccoy — Thanks for creating the issue! We have shipped a CRUD implementation that should unblock you. Please pull the `localstack/localstack-pro:latest` Docker image, and let us know your feedback! 🙏
