### ISSUE TITLE
bug: Private EKS Cluster fails to pull images from private ECR repositories (connection refused)

### ISSUE THREAD

**Issue by nicc777** [localstack/localstack#9936]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have a complete setup documented in a public GitHub repository. You can follow the steps  [from here](https://github.com/nicc777/localstack-cheatsheet/blob/1-trying-to-resolve-dns-resolution-in-private-eks-cluster-pulling-images-form-ecr/scenarios/README.md#goal-eks-deployed-in-a-private-vpc)

The images are in a Private ECR repository and I have successfully pushed the ArgoCD images to it ([process documented](https://github.com/nicc777/localstack-cheatsheet/blob/1-trying-to-resolve-dns-resolution-in-private-eks-cluster-pulling-images-form-ecr/scenarios/eks/0110-ecr-argocd.md) in the repo mentioned above):

```shell
$ curl -X GET https://localhost.localstack.cloud:4511/v2/_catalog
{"repositories":["argocd","argocd-dex","argocd-redis"]}

$ curl -X GET https://localhost.localstack.cloud:4511/v2/argocd/tags/list
{"name":"argocd","tags":["latest"]}
```

As part of the process, all the image locations in the ArgoCD manifest is updated:

```shell
$ cat /tmp/argocd.yaml | grep "image:" | sort -u
        image: localhost.localstack.cloud:4511/argocd-dex:latest
        image: localhost.localstack.cloud:4511/argocd:latest
        image: localhost.localstack.cloud:4511/argocd-redis:latest
```

When ArgoCD is deployed to the EKS cluster, I see the following:

```shell
$ kubectl get pods -n argocd
NAME                                                READY   STATUS                  RESTARTS   AGE
argocd-redis-5f66fc5974-94smf                       0/1     ImagePullBackOff        0          25m
argocd-application-controller-0                     0/1     ImagePullBackOff        0          25m
argocd-dex-server-b9b8f7b9-8cglf                    0/1     Init:ImagePullBackOff   0          25m
argocd-applicationset-controller-769fcf99cd-m9tvx   0/1     ImagePullBackOff        0          25m
argocd-notifications-controller-54cb6b45f5-4hhbf    0/1     ImagePullBackOff        0          25m
argocd-server-668f685b84-bwckg                      0/1     ImagePullBackOff        0          25m
argocd-repo-server-578b778cd-h5z8d                  0/1     Init:ImagePullBackOff   0          25m

$ kubectl describe pod argocd-server-668f685b84-bwckg -n argocd | tail
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                  From               Message
  ----     ------     ----                 ----               -------
  Normal   Scheduled  25m                  default-scheduler  Successfully assigned argocd/argocd-server-668f685b84-bwckg to k3d-cluster1-agent-eks-cluster1-nodegroup-az3-0
  Normal   Pulling    24m (x4 over 25m)    kubelet            Pulling image "localhost.localstack.cloud:4511/argocd:latest"
  Warning  Failed     24m (x4 over 25m)    kubelet            Failed to pull image "localhost.localstack.cloud:4511/argocd:latest": rpc error: code = Unknown desc = failed to pull and unpack image "localhost.localstack.cloud:4511/argocd:latest": failed to resolve reference "localhost.localstack.cloud:4511/argocd:latest": failed to do request: Head "https://localhost.localstack.cloud:4511/v2/argocd/manifests/latest": dial tcp 127.0.0.1:4511: connect: connection refused
  Warning  Failed     24m (x4 over 25m)    kubelet            Error: ErrImagePull
  Warning  Failed     24m (x6 over 25m)    kubelet            Error: ImagePullBackOff
  Normal   BackOff    47s (x109 over 25m)  kubelet            Back-off pulling image "localhost.localstack.cloud:4511/argocd:latest"
```

From within one of the EKS Nodes, I tested connectivity to confirm the error:

```shell
$ docker exec -it k3d-cluster1-agent-eks-cluster1-nodegroup-az3-1 sh
/ # nslookup localhost.localstack.cloud
Server:         127.0.0.11
Address:        127.0.0.11:53

Non-authoritative answer:
Name:   localhost.localstack.cloud
Address: 127.0.0.1

Non-authoritative answer:

/ # telnet localhost.localstack.cloud 4511 
telnet: can't connect to remote host (127.0.0.1): Connection refused
```
I tested DNS resolution from my host:

```shell
$ dig localhost.localstack.cloud

; <<>> DiG 9.18.18-0ubuntu0.22.04.1-Ubuntu <<>> localhost.localstack.cloud
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 61589
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;localhost.localstack.cloud.    IN      A

;; ANSWER SECTION:
localhost.localstack.cloud. 300 IN      A       192.168.2.18

;; Query time: 0 msec
;; SERVER: 127.0.0.53#53(127.0.0.53) (UDP)
;; WHEN: Sun Dec 24 09:02:47 CET 2023
;; MSG SIZE  rcvd: 71
```

> [!NOTE]
> The `192.168.2.18` address is my test system LAN address

I have tried several configurations following instructions from:

* https://docs.localstack.cloud/user-guide/aws/elastic-kubernetes-service/#utilizing-ecr-images-within-eks
* https://docs.localstack.cloud/user-guide/aws/route53/#customizing-internal-endpoint-resolution
* https://docs.localstack.cloud/user-guide/tools/dns-server/
* https://docs.localstack.cloud/references/network-troubleshooting/ (including child pages)

I have not yet found a configuration that works.

> [!IMPORTANT]
> If I use the default images (the default ArgoCD manifest), the images are pulled from the default repositories and the application is deployed without any issue.

### Expected Behavior

I expect the images to be pulled from ECR

### How are you starting LocalStack?

With the `localstack` script

### Steps To Reproduce

Complete instructions are documented at https://github.com/nicc777/localstack-cheatsheet/blob/1-trying-to-resolve-dns-resolution-in-private-eks-cluster-pulling-images-form-ecr/scenarios/README.md#goal-eks-deployed-in-a-private-vpc

### Environment

```markdown
- OS: Linux (Ubuntu 22.04.3 LTS)
- LocalStack: 3.0.3.dev
```

### Anything else?

I suspect I am missing something small, but perhaps this is a bug. I am just not 100% sure at this point.

I realize the steps to reproduce is rather long and I apologize for that. I am trying to build a working localstack private EKS cluster to allow me to develop "offline" from AWS. It goes without saying that these steps all work perfectly well for AWS (with some adaptations required for the AWS account).

**Comment by dfangl** [comment]
Hello @nicc777 !
I think I understand your error. Our multi-node support is quite new, and it seems we are not injecting the DNS into all of the worker node docker containers.

While I try to reproduce this on my side, could you please check if this also happens if you if you start the cluster without additional nodes as well.

**Comment by dfangl** [comment]
Hi @nicc777 !
The next LocalStack Pro release will contain a fix for this issue. Please feel free to reopen if that does not fix your issue.
Should be pushed to the :latest tag in a couple of hours!
Thank you for reporting this!
