### ISSUE TITLE
bug: StepFunction with JMESPath yields "Unexpected character"

### ISSUE THREAD

**Issue by phildunphytoo** [localstack/localstack#9937]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When running a step function that includes a ResultSelector with this json:
```
{
  "FailedTasks.$": "$[?(@.Status != '201')]"
}
```

Localstack fails with error:
```
Exception=JsonPathLexerError, Details=['Error on line 1, col 2: Unexpected character: ? '] ...
```

### Expected Behavior

Expected behaviour as in AWS
(Specifically here: the following should check if any of the results contains a status that's not '201')

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

Run localstack with docker-compose
Create the step function with a map and ResultSelector as described
Run the step function and see it fail :(

### Environment

```markdown
- OS:Rhel 8.6
- LocalStack: 3.0
```

**Comment by phildunphytoo** [comment]
I found this: https://github.com/h2non/jsonpath-ng/issues/8
It could be related

**Comment by phildunphytoo** [comment]
The same in 3.0.3

**Comment by phildunphytoo** [comment]
Thanks! Waiting for the release :)

**Comment by MEPalma** [comment]
The StepFunctions interpreter now correctly delegates to the jsonpath library, which resolves several issues related to parsing and accessing JSON path definitions. However, it's important to note that the jsonpath_ng library doesn't always adhere completely to the spec (as discussed in [h2non/jsonpath-ng#8](https://github.com/h2non/jsonpath-ng/issues/8)).

Considering this, I am staling this issue for now. Going forward, I will keep an eye on the progress of [h2non/jsonpath-ng#8](https://github.com/h2non/jsonpath-ng/issues/8) to ensure alignment with the specifications. Additionally, the tests added in this PR will remain enabled for filtering JSON path definitions.

Feel free to reopen this issue or raise any further concerns if needed. Thank you again for your contribution!

**Comment by phildunphytoo** [comment]
Hi, I'm testing this in localstack 3.3 but it seems it doesn't work right.
I have a condition: "$[?(@.Status != '200')]" and it catches outputs that have Status = 200.. Any ideas?
