### ISSUE TITLE
bug: cdk to create ec2 instance failed with MaxCount/MinCount required

### ISSUE THREAD

**Issue by leecarney** [localstack/localstack#9939]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Using CDK to create an ec2 instance fails with:
```
6:48:30 PM | CREATE_FAILED        | AWS::EC2::Instance                    | Ins
tanceLocalstack99C06A68
Parameter validation failed:
Missing required parameter in input: "MaxCount"
Missing required parameter in input: "MinCount"
```

These appear to be parameters for Instances inside an ASG rather than single ec2 instance.

### Expected Behavior

The ec2 instance should be created without needing to add min and max values as the ec2 instance module doesn't support them

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker compose using localstack recommended config and pro licence

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)
```
    import * as cdk from 'aws-cdk-lib'
import {
  Instance,
  Vpc,
  MachineImage,
  InstanceType,
  CfnKeyPair,
} from 'aws-cdk-lib/aws-ec2'
import { Construct } from 'constructs'

export class LocalstackCdkStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props)

    const vpc = new Vpc(this, 'VpcLocalstack', {
      maxAzs: 1
    })

    const keyPair = new CfnKeyPair(this, 'KeyPairLocalstack', {
      keyName: 'localstack-ec2-key'
    })

    const instance = new Instance(this, 'InstanceLocalstack', {
      vpc,
      instanceType: new InstanceType('t4g.small'),
      machineImage: MachineImage.genericLinux({
        'us-west-2': 'ami-ff0fea8310f3'
      }),
      keyName: keyPair.keyName
      // TODO: new keypair format


    })
  }
}
```
```
cdklocal bootstrap
cdklocal deploy
```
### Environment

```markdown
- OS: Mac Ventura 13.6.2
- LocalStack: pro  2.3.3.dev20231111104446
```

**Comment by MarcelStranak** [comment]
Hi @leecarney,

Could you please confirm if this issue has been resolved in the `latest` release of the LocalStack Docker image? If that is the case, kindly mark the matter as resolved. Thank you.

**Comment by leecarney** [comment]
Works great thanks!
