### ISSUE TITLE
localstack start doensn't works

### ISSUE THREAD

**Issue by Danver97** [localstack/localstack#995]
**System info:** I'm running Win10 Home

After multiple attempts i managed to get every C++ library needed to run `pip install localstack` successfully.
But when i run `localstack start` from PowerShell, windows asks me which program should he use to open the file.

Seems that instead of running localstack Win10 finds a text file called 'localstack' and ask me how to open it.

Anybody had this quite silly problem?

Thanks in advance for any kind of help!

**Comment by cspotcode** [comment]
What do you see when you run these commands in powershell?

```
get-command localstack
where.exe localstack
```

**Comment by Danver97** [comment]
Here's the output:
```
PS D:\Users\christian\Documents> get-command localstack

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     localstack                                         0.0.0.0    C:\Users\christian\AppData\Local\Programs\Python\Python37\Scripts\localstack
```

```
PS D:\Users\christian\Documents> where.exe localstack
C:\Users\christian\AppData\Local\Programs\Python\Python37\Scripts\localstack
```

I looked at the location and that's the same "text" file I saw opening it with a text editor.
Running `python C:\Users\christian\AppData\Local\Programs\Python\Python37\Scripts\localstack` it starts, but I've some problems with 'async' that is a reserved word in Python 3.7 (but that's another problem for now).

Is there a way to avoid to specify the path to the script every time?

Should I put `.py` exension to `localstack` file?

Thank you!

**Comment by cspotcode** [comment]
Windows doesn't support shebangs, so if it's relying on one of those to
launch, that's why it's failing.  You might try running in WSL or asking
the localstack devs to add Windows support.

**Comment by Danver97** [comment]
@cspotcode I'm not a python developer. What does it means that windows don't support shebangs?

Actually I managed to get it started.

I installed python 3.6, run `python C:\Users\christian\AppData\Roaming\Python\Python36\Scripts\localstack start`, but it ended up with a 
```
ERROR: 'cd "C:\Users\christian\AppData\Roaming\Python\Python36\site-packages\localstack/infra/dynamodb" && zip -u DynamoDBLocal.jar log4j2.xml || true': b'\tzip warning: DynamoDBLocal.jar not found or empty
tzip warning: name not matched: log4j2.xml
"true" not recognized as internal or external command, executable program or file batch.'
```

Should I give up and embrace WSL? (I didn't know it before, seems awesome!)

**Comment by cspotcode** [comment]
Shebangs are a Linux thing, not python.  Google should give you some good
info.

**Comment by whummer** [comment]
Installation should work now under Windows (see also the recent changes in #1631). Closing this issue - please re-open if the problem persists. Thanks
