### ISSUE TITLE
bug: Amplify not initialized, not run, not start project

### ISSUE THREAD

**Issue by IgorDePaula** [localstack/localstack#9966]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://github.com/localstack/localstack/assets/2833993/c2851f13-1234-43e9-a683-b015f253b841)
I installed the amplify plugin, but I got this error.

### Expected Behavior

![image](https://github.com/localstack/localstack/assets/2833993/9fec8925-f3df-46ba-8440-7f966639371c)
Project created with no error, like docs.

### How are you starting LocalStack?

With the `localstack` script

### Steps To Reproduce

1- $ localstack start
2- $ npm install -g amplify-localstack
3- $ amplify plugin add amplify-localstack
4- $ amplify init --use-localstack true <- here happens the error

### Environment

```markdown
- OS: ubuntu 22.04
- LocalStack: 3.0.2
```

### Anything else?

I'm using amplify cli  12.10.0

**Comment by MarcelStranak** [comment]
Hi @IgorDePaula, 

Can you please confirm if you are running LocalStack Pro version?
You can find the steps in our documentation: https://docs.localstack.cloud/getting-started/auth-token/

**Comment by IgorDePaula** [comment]
@MarcelStranak 

![image](https://github.com/localstack/localstack/assets/2833993/917f130a-b370-4204-b67d-0c25f10a902d)

**Comment by MarcelStranak** [comment]
Hi @IgorDePaula,

Thank you for the confirmation. You will need to switch to the LocalStack Pro version to use the Amplify service.

**Comment by IgorDePaula** [comment]
Should I pay even if the tool doesn't have all the features?

![image](https://github.com/localstack/localstack/assets/2833993/c13492c2-a0e5-46a5-bea5-94ef0c1996fa)


In my opinion, pro version only for tool that have all features.

**Comment by MarcelStranak** [comment]
@IgorDePaula, please take advantage of the 14-day trial period to test the Pro features and then decide if paying for the Pro service is acceptable. You can create an account and active the trial on https://app.localstack.cloud/.
