### ISSUE TITLE
bug: kinesis doesn't start with localstack 2.3.0 and +

### ISSUE THREAD

**Issue by CyrilDevOps** [localstack/localstack#9969]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We use kinesis in localstack,
I tried to update our version of localstack (2.0.2), but there is a big change with 2.3.0 and it doesn't work on Mac M1 or M2.
I tried arm64 and amd64 image of localstack, both have the same behavior.
First kinesis command stay stuck.
When logging into localstack and doing a ps I see :
❯ docker exec -ti l2-platform-localstack bash
root@0c66d90518cb:/opt/code/localstack# ps -ef
UID        PID  PPID  C STIME TTY          TIME CMD
root         1     0  0 06:51 ?        00:00:00 /opt/code/localstack/.venv/bin/python /opt/code/localstack/.venv/bin/localstack-supervisor
root        15     1  1 06:51 ?        00:00:05 /opt/code/localstack/.venv/bin/python -m localstack.runtime.main
root        36    15  1 06:51 ?        00:00:04 java -Xmx256m -javaagent:/usr/lib/localstack/dynamodb-local/latest/ddb-local-loader-0.1.jar -Djava.library.path=/usr/lib/localstack/dynamodb-local/latest/DynamoDBLocal_lib -jar /usr/lib/localstack/dynamodb-local/latest/DynamoDBLocal.jar -port 6
root       162     0  0 06:52 ?        00:00:00 bash -f //tmp/01-kinesis-init.sh --populate-only
root       167   162  0 06:52 ?        00:00:01 /usr/local/bin/python /usr/local/bin/aws kinesis --endpoint-url=http://127.0.0.1:4566 --region us-east-1 describe-stream --stream-name l2-command-journal-test
root       169    15  0 06:52 ?        00:00:01 npm install kinesis-local@0.4.2
root       700     0  0 06:56 pts/0    00:00:00 bash
root       706   700  0 06:56 pts/0    00:00:00 ps -ef

The /root/.npm/_logs/... file show :
0 verbose cli /usr/bin/node /usr/bin/npm
1 info using npm@9.8.1
2 info using node@v18.18.0
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 2ms
5 timing config:load:file:/usr/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 2ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/var/lib/localstack/lib/kinesis-local/0.4.2/.npmrc Completed in 0ms
10 timing config:load:project Completed in 0ms
11 timing config:load:file:/root/.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:/var/lib/localstack/lib/kinesis-local/0.4.2/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 1ms
15 timing config:load:setEnvs Completed in 0ms
16 timing config:load Completed in 6ms
17 timing npm:load:configload Completed in 6ms
18 timing config:load:flatten Completed in 1ms
19 timing npm:load:mkdirpcache Completed in 0ms
20 timing npm:load:mkdirplogs Completed in 0ms
21 verbose title npm install kinesis-local@0.4.2
22 verbose argv "install" "--prefix" "/var/lib/localstack/lib/kinesis-local/0.4.2" "kinesis-local@0.4.2"
23 timing npm:load:setTitle Completed in 1ms
24 timing npm:load:display Completed in 0ms
25 verbose logfile logs-max:10 dir:/root/.npm/_logs/2024-01-02T06_57_00_083Z-
26 verbose logfile /root/.npm/_logs/2024-01-02T06_57_00_083Z-debug-0.log
27 timing npm:load:logFile Completed in 4ms
28 timing npm:load:timers Completed in 0ms
29 timing npm:load:configScope Completed in 0ms
30 timing npm:load Completed in 20ms
31 timing config:load:flatten Completed in 0ms
32 timing arborist:ctor Completed in 0ms
33 timing arborist:ctor Completed in 0ms
34 silly logfile done cleaning log files
35 timing idealTree:init Completed in 6ms
36 timing idealTree:userRequests Completed in 1ms
37 silly idealTree buildDeps
38 silly fetch manifest kinesis-local@0.4.2

### Expected Behavior

I expect kinesis to start transparently like in previous version and simulate aws kinesis correctly.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

  localstack:
    image: dockerhub-remote.art-bobcat.autodesk.com/localstack/localstack:2.3.0
    container_name: l2-platform-localstack
    environment:
      EAGER_SERVICE_LOADING: 1
      SERVICES: kinesis,cloudwatch,dynamodb,sts,s3,sqs,sns,secretsmanager
      KINESIS_ERROR_PROBABILITY: ' '
      LAMBDA_REMOTE_DOCKER: 'false'
      AWS_ACCESS_KEY_ID: dev
      AWS_SECRET_ACCESS_KEY: dev
      DEFAULT_REGION: us-east-1
      AWS_CBOR_DISABLE: 'true'
      CBOR_ENABLED: 'true'
      TZ: 'UTC'
      LS_LOG: 'error'
      DEBUG: '0'
    healthcheck:
      test: /healthcheck/test.sh
      interval: 20s
      timeout: 20s
    networks:
      l2-platform:
        aliases:
          - l2-platform-localstack
          - l2-platform-localstack.localstack.cloud
    ports:
      - 14566:4566
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - type: bind
        source: ./localstack/healthcheck
        target: /healthcheck
        read_only: true

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal kinesis describe-stream / create-stream command

### Environment

```markdown
- OS:OSX on Macbook pro m2
- LocalStack: 2.3.0  and newer version
```

**Comment by MarcelStranak** [comment]
Hi @CyrilDevOps,

I'm unable to replicate the issue with Kinesis in `localstack/localstack:2.3.0` or newer versions. I would recommend updating to the latest LocalStack version 3.0.2 or the `latest`.

Starting fresh with the default [docker-compose.yml](https://github.com/localstack/localstack/blob/master/docker-compose.yml) may help troubleshoot.

If you face network restrictions, be aware that LocalStack requires downloading 3rd party tools for specific services.

For more details on Kinesis, please visit our documentation: https://docs.localstack.cloud/user-guide/aws/kinesis/


For the full change logs please visit: 
https://discuss.localstack.cloud/t/localstack-release-v2-3-0/533
https://discuss.localstack.cloud/t/upcoming-changes-for-localstack-v3/576/3
https://discuss.localstack.cloud/t/networking-migration-guide-for-localstack-3-0/588

**Comment by CyrilDevOps** [comment]
Hi,
The 'problem' is our internal company network isn't allow to connect to npm registry because we overload them,
we had to go through an internal proxy. (I never done much of npm stuff).

I had to add an npm config in /root/.npmrc through a file mapping in docker-compose to make the internal npm use of localstack being able to download the packages.

You can close this ticket.
(Maybe a NPM_REGISTRY or some sort of env variable for the overwrite would be nice)

**Comment by MarcelStranak** [comment]
I am pleased that you have found the solution. I will forward your suggestion to our team. Thank you.

**Comment by CyrilDevOps** [comment]
It seems that you can simply add a env variable on the localstack service in docker-compose.yaml file
with the name npm_config_registry to overwrite the npm registry url.

npm_config_registry: 'https://.....'

**Comment by guylemon** [comment]
> It seems that you can simply add a env variable on the localstack service in docker-compose.yaml file with the name npm_config_registry to overwrite the npm registry url.
> 
> npm_config_registry: 'https://.....'

I can confirm that this worked for me with the latest version of localstack-pro circa 2024-03-19.

```
  version: "3.8"

  services:
    localstack:
      image: localstack/localstack-pro
      # [ ... ]
      environment:
          # exported from .env
        - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN}
          # exported from .env
        - npm_config_registry=${NPM_CONFIG_REGISTRY_URL_OVERRIDE:-}
```
