### ISSUE TITLE
using --no-sign-request forces the region to us-east-1

### ISSUE THREAD

**Issue by Eric-Payapps** [localstack/localstack#9976]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Using the --no-sign-request argument should have no impact on the region.

### Expected Behavior

Using the --no-sign-request argument forces the region to us-east-1.

For instance:

aws --no-sign-request --endpoint-url=http://localhost:4566 sqs --region ap-southeast-2 create-queue --queue-name TEST
=>
{
    "QueueUrl": "http://sqs.us-east-1.localhost.localstack.cloud:4566/000000000000/TEST"
} 

aws --endpoint-url=http://localhost:4566 sqs --region ap-southeast-2 create-queue --queue-name TEST
=>
{
    "QueueUrl": "http://sqs.ap-southeast-2.localhost.localstack.cloud:4566/000000000000/TEST"
}

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal s3 mb s3://mybucket

### Environment

```markdown
- OS: Windows 11
- LocalStack: Latest
```

**Comment by bentsku** [comment]
Hello @Eric-Payapps and thanks for your report. LocalStack makes all services available on a single endpoint (which can be `localhost`, `localhost.localstack.cloud`, etc...). 

And with that, the region data will only be encoded in the signature of the request, in the `Authorization` header:
```
Authorization: AWS4-HMAC-SHA256 Credential=test/20240103/us-east-1/sqs/aws4_request, SignedHeaders=content-type;host;x-amz-date;x-amz-target, Signature=397780d0547e591cd92d14fd7c94a3edf7a4b18914eaaa226504ce5ab7736bd2
``` 

The region will be encoded as such: `Credential=test/20240103/us-east-1/sqs/aws4_request`

Without the signature, we don't have a way to know which region was selected.

Is there a specific reason you'd want to use `--no-sign-request`?
We list not using `--no-sign-request` as a limitation in our documentation: https://docs.localstack.cloud/user-guide/integrations/aws-cli/#limitations
> Please also note there is a known limitation for issuing requests using --no-sign-request with the AWS CLI. LocalStack’s routing mechanism depends on the signature of each request to identify the correct service for the request. Thus, adding the flag --no-sign-requests provokes your request to reach the wrong service. One possible way to address this is to use the awslocal CLI instead of AWS CLI.

Thanks!

**Comment by Eric-Payapps** [comment]
Thank you for your answer; that clarifies it.
We will try to avoid using the --no-sign-request argument then.

**Comment by bentsku** [comment]
Thanks, I'll close the issue then! Thanks again for the report.
