### ISSUE TITLE
bug: ACM: Incorrectly Prepending "test" onto `ValidationDomain` value within `DomainValidationOptions` for Subject Alternative Names

### ISSUE THREAD

**Issue by ScottFinlaysonGMSL** [localstack/localstack#9977]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When creating a certificate (via terraform) with Subject Alternative Names (SANs), the `ValidationDomain` for `altDomain` is incorrectly set to `test.altDomain` resulting in the following error when creating a new certificate:
```
 * missing another.domain.com DNS validation record: test.another.domain.com
```

The certificate is created but the `ValidationDomain` value is incorrectly set for SANs:
- For a fully qualified domain, it has `test` prepended resulting in `test.another.domain.com` instead of `test.another.domain.com`
- For a wildcard domain, the `*` is replaced with `test` resulting in `test.mytest.example.com` instead of `*.mytest.example.com`

### Expected Behavior

The `ValidationDomain` should be set to `altDomain`. I am unaware why `DomainName` would differ to `ValidationDomain` as I haven't come across a scenario where that is the case yet but I'd be interested to know if there is such a scenario.

### How are you starting LocalStack?

With a `docker run` command

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

docker run -d --rm \
  --publish 4566:4566 \
  --publish 4510-4559:4510-4559 \
  localstack/localstack:3.0.2

<details>
<summary>
Example: Creating New Certificate via Localstack
</summary>

#### Create the certificate
```
aws --endpoint http://localhost:4566 --region eu-central-1 acm request-certificate --domain-name mytest.example.com --subject-alternative-names mytest.example.com test.another.domain.com *.mytest.example.com
{
    "CertificateArn": "arn:aws:acm:eu-central-1:000000000000:certificate/fd2d95e2-3080-4aee-9216-101d356d55e2"
}
```

#### Describe the certificate
```
aws --endpoint http://localhost:4566 --region eu-central-1 acm describe-certificate --certificate-arn arn:aws:acm:eu-central-1:000000000000:certificate/fd2d95e2-3080-4aee-9216-101d356d55e2
{
    "Certificate": {
        "CertificateArn": "arn:aws:acm:eu-central-1:000000000000:certificate/fd2d95e2-3080-4aee-9216-101d356d55e2",
        "DomainName": "mytest.example.com",
        "SubjectAlternativeNames": [
            "*.mytest.example.com",
            "test.another.domain.com",
            "mytest.example.com"
        ],
        "DomainValidationOptions": [
            {
                "DomainName": "mytest.example.com",
                "ValidationDomain": "mytest.example.com",
                "ValidationStatus": "SUCCESS",
                "ResourceRecord": {
                    "Name": "_d930b28be6c5927595552b219965053e.mytest.example.com.",
                    "Type": "CNAME",
                    "Value": "_c9edd76ee4a0e2a74388032f3861cc50.ykybfrwcxw.acm-validations.aws."
                },
                "ValidationMethod": "DNS"
            },
            {
                "DomainName": "*.mytest.example.com",
                "ValidationDomain": "test.mytest.example.com",
                "ValidationStatus": "SUCCESS",
                "ResourceRecord": {
                    "Name": "test.mytest.example.com",
                    "Type": "CNAME",
                    "Value": "test123"
                },
                "ValidationMethod": "DNS"
            },
            {
                "DomainName": "test.another.domain.com",
                "ValidationDomain": "test.test.another.domain.com",
                "ValidationStatus": "SUCCESS",
                "ResourceRecord": {
                    "Name": "test.test.another.domain.com",
                    "Type": "CNAME",
                    "Value": "test123"
                },
                "ValidationMethod": "DNS"
            }
        ],
        "Serial": "644781311987505433280939016122775760629002631461",
        "Subject": "CN=mytest.example.com",
        "Issuer": "Amazon",
        "CreatedAt": "2024-01-03T10:13:15.553510+00:00",
        "IssuedAt": "2024-01-03T10:13:15.553510+00:00",
        "Status": "ISSUED",
        "NotBefore": "2024-01-03T10:13:15+00:00",
        "NotAfter": "2025-01-02T10:13:15+00:00",
        "KeyAlgorithm": "RSA-2048",
        "SignatureAlgorithm": "SHA512WITHRSA",
        "InUseBy": [],
        "Type": "AMAZON_ISSUED",
        "KeyUsages": [
            {
                "Name": "DIGITAL_SIGNATURE"
            },
            {
                "Name": "KEY_ENCIPHERMENT"
            }
        ],
        "ExtendedKeyUsages": [
            {
                "Name": "TLS_WEB_SERVER_AUTHENTICATION",
                "OID": "1.3.6.1.0.1.2.3.0"
            },
            {
                "Name": "TLS_WEB_CLIENT_AUTHENTICATION",
                "OID": "1.3.6.1.0.1.2.3.4"
            }
        ],
        "RenewalEligibility": "INELIGIBLE",
        "Options": {
            "CertificateTransparencyLoggingPreference": "ENABLED"
        }
    }
}
```
</details>

<details>
<summary>
Example: Creating New Certificate via AWS
</summary>

#### Create the certificate
```
aws acm request-certificate --domain-name mytest.example.com --subject-alternative-names mytest.example.com test.another.domain.com *
.mytest.example.com
{
    "CertificateArn": "arn:aws:acm:<AWS_REGION>:<REDACTED>:certificate/<CERT_ID>"
}
```
#### Describe the certificate
```
aws acm describe-certificate --certificate-arn arn:aws:acm:<AWS_REGION>:<REDACTED>:certificate/<CERT_ID>
{
    "Certificate": {
        "CertificateArn": "arn:aws:acm:<AWS_REGION>:<REDACTED>:certificate/<CERT_ID>",
        "DomainName": "mytest.example.com",
        "SubjectAlternativeNames": [
            "mytest.example.com",
            "test.another.domain.com",
            "*.mytest.example.com"
        ],
        "DomainValidationOptions": [
            {
                "DomainName": "mytest.example.com",
                "ValidationDomain": "mytest.example.com",
                "ValidationStatus": "PENDING_VALIDATION",
                "ValidationMethod": "DNS"
            },
            {
                "DomainName": "test.another.domain.com",
                "ValidationDomain": "test.another.domain.com",
                "ValidationStatus": "PENDING_VALIDATION",
                "ValidationMethod": "DNS"
            },
            {
                "DomainName": "*.mytest.example.com",
                "ValidationDomain": "*.mytest.example.com",
                "ValidationStatus": "FAILED",
                "ValidationMethod": "DNS"
            }
        ],
        "Subject": "CN=mytest.example.com",
        "Issuer": "Amazon",
        "CreatedAt": "2024-01-03T10:37:39.309000+00:00",
        "Status": "FAILED",
        "KeyAlgorithm": "RSA-2048",
        "SignatureAlgorithm": "SHA256WITHRSA",
        "InUseBy": [],
        "FailureReason": "ADDITIONAL_VERIFICATION_REQUIRED",
        "Type": "AMAZON_ISSUED",
        "KeyUsages": [],
        "ExtendedKeyUsages": [],
        "RenewalEligibility": "INELIGIBLE",
        "Options": {
            "CertificateTransparencyLoggingPreference": "ENABLED"
        }
    }
}

```

Note: ignore the failed status as these are usually obvious dummy domains which won't work.
</details>

### Environment

```markdown
- OS: Ubuntu 22.04 (WSL)
- LocalStack:3.0.2
- AWS CLI: 2.15.5
```

### Anything else?

Found after testing the fix for https://github.com/localstack/localstack/issues/9768

I did find issue https://github.com/localstack/localstack/issues/7340 but I created this issue for the following reasons:
- There has also been no progress on that issue
- that issue uses pullimi for the reproduction so possibly harder to reproduce for devs (my examples use localstack with a comparison to aws so hopefully easier to find the required fix)
- I have also highlighted that wildcard domains are affected by the use of `test`

Feel free to collapse this issue into that issue but I wasn't able to update the description and didn't want to lose visibility on the wildcard issue which is what brought me to this originally.

**Comment by maxhoheiser** [comment]
I wanted to bring your attention to [PR#10027](https://github.com/localstack/localstack/pull/10027), where we've successfully fixed the above-described issues. 
We could build on a recent fix in moto and implement the correct representation of subject alternative names `DomainValidationOptions`.

To test the new functionality, please ensure you're running the latest Docker image. 

Also kudos to @ScottFinlaysonGMSL for the issue description especially including the complete code to reproduce it on AWS, this makes it much faster to fix issues.

**Comment by ScottFinlaysonGMSL** [comment]
@maxhoheiser tested this afternoon and all working as expected. Thanks! 🙏

**Comment by ScottFinlaysonGMSL** [comment]
@maxhoheiser just testing this in our CI pipeline and it's failing because the image fetched doesn't include the new changes. Is it possible for the tag `3` on [Docker hub](https://hub.docker.com/r/localstack/localstack/tags) to be updated to include the latest changes? At the moment, it's only the `latest` tag which includes this fix.
