### ISSUE TITLE
Disallow bucket names that real S3 does not accept

### ISSUE THREAD

**Issue by ababkin** [localstack/localstack#998]
If I create a bucket named `myTest` localstack allows it and creates the bucket fine but real S3 gives the `InvalidBucketName` error.

**Comment by rjaduthie** [comment]
The rules are given here: https://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html
In an effort to test various mock AWS environments, I made a set ot tests focussing on S3, the test for InvalidBucket is here:
https://gist.github.com/rjaduthie/0f2573cc82792dfff1754b44adeb3341

**Comment by whummer** [comment]
Thanks for reporting @ababkin @rjaduthie . This should be fixed in #1807 - please re-open this issue if the problem persists. Thanks
