### ISSUE TITLE
Add support for SecretsManager:BatchGetSecretValue

### ISSUE THREAD

**Issue by flarocca** [localstack/localstack#9982]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Enhancement description

AWS SecretsManager has officially released the BatchgetSecretValue api (see announcement [here](https://aws.amazon.com/about-aws/whats-new/2023/11/aws-secrets-manager-batch-retrieval-secrets/) and official documentation [here](https://docs.aws.amazon.com/secretsmanager/latest/userguide/retrieving-secrets_batch.html))

It would be awesome to include support for it so we can start using that API

**Comment by hpaskalev** [comment]
I have submitted a PR to the moto repository to add the missing implementation. 
If it receives approval, I would be glad to contribute here as well.

**Comment by hpaskalev** [comment]
I see that the PR has been merged into the moto fork as well, so I can finish this one and open a PR in the localstack repo. On it.
