### ISSUE TITLE
Invoking CF stack destroy API call seems to delete the stack but not the resources it has provisioned

### ISSUE THREAD

**Issue by ababkin** [localstack/localstack#999]
in particular I see the buckets and lambdas remaining. The same call works as expected and de-provisions the resources when invoked against real AWS

**Comment by Muraligowtham** [comment]
I have the same issue

**Comment by twellspring** [comment]
Same issue. Here are more details.
```
$ localstack --version
0.9.4
```


**cloudformation-s3.yml**
```
AWSTemplateFormatVersion: 2010-09-09
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: test-bucket-1
```

**Evidence of issue**
```
$ awslocal s3 ls
$ awslocal cloudformation create-stack --stack-name test2 --template-body file://cloudformation-s3.yml
{
    "StackId": "arn:aws:cloudformation:us-east-1:123456789:stack/test2/51158bc1-690d-48aa-8c1c-cdc0845b11bd"
}
$ awslocal cloudformation list-stacks
{
    "StackSummaries": [
        {
            "StackId": "arn:aws:cloudformation:us-east-1:123456789:stack/test2/51158bc1-690d-48aa-8c1c-cdc0845b11bd",
            "StackName": "test2",
            "TemplateDescription": "None",
            "CreationTime": "2011-05-23T15:47:44Z",
            "StackStatus": "CREATE_COMPLETE"
        }
    ]
}
$ awslocal s3 ls
2006-02-03 08:45:09 test-bucket-1
$ awslocal cloudformation delete-stack --stack-name test2
$ awslocal cloudformation list-stacks
{
    "StackSummaries": [
        {
            "StackId": "arn:aws:cloudformation:us-east-1:123456789:stack/test2/787bfc37-df90-4da4-9260-4b7e499f50aa",
            "StackName": "test2",
            "TemplateDescription": "None",
            "CreationTime": "2011-05-23T15:47:44Z",
            "StackStatus": "DELETE_COMPLETE"
        }
    ]
}
$ awslocal s3 ls
2006-02-03 08:45:09 test-bucket-1
```

**Comment by whummer** [comment]
Thanks for reporting @ababkin @Muraligowtham @twellspring . The basic mechanics for deleting CF stack resources has been added in #1888 .

Currently, only a subset of service resources are supported for deletion, though (including SQS/SNS/Kinesis/S3). Any resources currently not yet supported will print a log line like:
```
localstack.utils.cloudformation.template_deployer: WARNING: Action "delete" for resource type ApiGateway::GatewayResponse not yet implemented
```

We can add support for additional resources as we go. Please open follow-up tickets or contribute a small PR if you depend on deletion of a specific resource. Thanks!

**Comment by Kadambari87** [comment]
Hi,

I am still facing this issue on localstack v 0.10.6. I have created Kinesis/SQS resources via cloud formation and they do not get destroyed via API call. Can you please help in resolving this issue?

Thanks,
Kadambari

**Comment by krnbr** [comment]
same for me, unable to delete the dynamo db table
