### ISSUE TITLE
Localstack does not support calling SQS from API WS GW on $disconnect endpoint

### ISSUE THREAD

**Issue by israelItzhakov** [localstack/localstack#9991]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

- create API WS GW
- for $disconnect add integration for SQS 
- connecting to  API WS GW
- and after a few seconds disconnect

Seems Localstack does not support calling SQS from API WS GW on the disconnect endpoint, however, real AWS does
Error invoking integration request for the route "$disconnect": Unsupported integration URI "arn:aws:apigateway:us-east-1:sqs:path/000000000000/local-sdpv2-agent-sqs-disconnect" for Websocket API ID "d5879b4d"
<img width="1364" alt="Screenshot 2024-01-04 at 14 16 03" src="https://github.com/localstack/localstack/assets/87303410/259f3ace-7850-4b9e-ac77-b510bf41e85e">
,

### Expected Behavior

the SQS needs to be triggered.

### How are you starting LocalStack?

With a `docker run` command

### Steps To Reproduce

n/a

### Environment

```markdown
- OS: macOS
- LocalStack: 3.0.1
```

**Comment by calvernaz** [comment]
Hi @israelItzhakov thanks for reporting this, the fix is up and should be available in the latest image, so please give it a go 👍

**Comment by FaigerLev** [comment]
Hi @calvernaz 
I have last version: 3.1.0
I have same problem like @israelItzhakov 

Error invoking integration request for route "$disconnect": Unsupported integration URI "arn:aws:apigateway:us-east-1:sqs:path/000000000000/local-sdpv2-agent-sqs-disconnect" for Websocket API ID "d9b11aa8"

**Comment by calvernaz** [comment]
Hi @FaigerLev, can you try this sample and make sure you have the latest image - remove and pull just in case. 

Also, can you try this [sample](https://github.com/localstack-samples/localstack-terraform-samples/tree/master/apigatewayv2-ws-sqs), or if possible a sample you created yourself so we can reproduce?
