### ISSUE TITLE
bug: (EventBridge) Cannot re-enable an event-bridge rule after it was disabled or configured from the beginning with status=DISABLED.

### ISSUE THREAD

**Issue by robertchinezon** [localstack/localstack#9994]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The event rule never fires after toggling the status from disabled to enabled.

### Expected Behavior

The event rule enables and should start routing messages.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    DEBUG=1 LAMBDA_DOCKER_FLAGS="-p 19891:19891" localstack start -d

Steps to Reproduce:

1) Create a lambda function:

cd /tmp
echo "
import time

def handler(event, context):
    time.sleep(60)
    response = {
        'statusCode': 200,
        'body': 'Slept for 60s.'
    }
    return response
" > /tmp/sleep_handler.py
zip function.zip sleep_handler.py 
awslocal lambda create-function     --function-name localstack-lambda-url-example1     --runtime python3.10     --zip-file fileb://function.zip     --handler sleep_handler.handler     --role arn:aws:iam::000000000000:role/lambda-role

2) Create an event-bridge rule

awslocal events put-rule \
    --name my-scheduled-rule \
    --schedule-expression 'rate(1 minute)'

3) Add lambda permission for the event-bridge rule

awslocal lambda add-permission     --function-name localstack-lambda-url-example1     --statement-id my-scheduled-event     --action 'lambda:InvokeFunction'     --principal events.amazonaws.com     --source-arn arn:aws:events:us-east-1:000000000000:rule/my-scheduled-rule

4) Create the event-bridge targets:

echo '
[     
    {
      "Id": "1", 
      "Arn": "arn:aws:lambda:us-east-1:000000000000:function:localstack-lambda-url-example1"
    }
]' > /tmp/targets.json

awslocal events put-targets     --rule my-scheduled-rule     --targets file://targets.json

5) Disable enable the event-bridge rule:

awslocal events disable-rule --name "my-scheduled-rule"
awslocal events enable-rule --name "my-scheduled-rule"

### Environment

```markdown
- OS: Ubuntu 22.04
- LocalStack: 3.0.2
```

**Comment by maxhoheiser** [comment]
Dear all, we introduced the new EventBridge v2 with our release 3.5 officially last week. Amongst many other improvements and parity fixes, the new EventBridge v2 also handles `disable_rule` and èndable_rule`correctly - thus further improving the parity with AWS.

You can use the new EventBridge v2 by setting the environment variable PROVIDER_OVERRIDE_EVENTS=v2.

Please give us feedback regarding this or any other issues.
